### ISSUE TITLE
StateList Horizontal - HomeKitTitle

### ISSUE THREAD

**Issue by LoDDl** [Zefau/ioBroker.jarvis#1000]
Hey,

ich habe gerade zum 3. mal angefangen auf Jarvis 3.0 umzusteigen und zum 3. mal hab ich doch wieder einen Rollback gemacht. Meine Jarvis - Oberfläche ist mittlerweile ziemlich groß und für mich auch übersichtlich. Deswegen möchte ich eigentlich auch gern vom Layout her alles so in Etwa beibehalten wie bisher. Mich stört aber diese Umwandlung in HomeKitTitle extrem, da es einfach nicht vergleichbar mit Statelist Horizontal ist. Warum gibt es diese StateList nicht mehr? Ich hänge mal Beispiele an, die ich einfach in der Form nicht nachbauen kann.

Ich hoffe, dass Statelist Horizontal wieder implementiert wird oder aber der HomeKit Baustein noch weiter anpassbar wird (mehr Zeilen, Skalierung, Zeitstempel nicht in schwarz und unveränderbar.. etc.

Vielen Dank und liebe Grüße :)

![image](https://user-images.githubusercontent.com/52470482/133334965-f95e73f8-fb5b-416f-bbbd-e021cb4c269d.png)
![image](https://user-images.githubusercontent.com/52470482/133335379-f24bf8b9-eed6-4c72-aa21-d754b866b260.png)
![image](https://user-images.githubusercontent.com/52470482/133335498-d747b9a8-e8de-47e1-94fc-5c095da8c9a2.png)
![image](https://user-images.githubusercontent.com/52470482/133335580-ab8c68ce-f9e4-4227-ba69-cb49f54a5d06.png)

Mit den HomeKit Bausteinen ist dann einfach alles voneinander getrennt, nicht skalierbar, der Text passt nicht in den Baustein, außer man zieht ihn extrem groß was auch wieder doof aussieht.

Danke auf jedenfall für den schönen Adapter! :)

**Comment by Zefau** [comment]
Welche Auflösung hast du in diesem Beispiel?

**Comment by Zefau** [comment]
Erscheint mir der Bug https://github.com/Zefau/ioBroker.jarvis/issues/999 zu sein.

Du kannst alle Widgets flexibel in Breite und Höhe anpassen. In deinem Fall scheint aufgrund des responsive Designs die Breite auf 100% geändert worden zu sein?

**Comment by LoDDl** [comment]
Ne das meinte ich nicht. Ja, man kann die Widgets relativ frei skalieren aber der Inhalt eben nicht. Wie in dem Screenshot zu sehen soll in dem Widget das Icon, Label, State und darunter noch die secondary States angezeigt werden. Das ist mit dem HomeKits nicht möglich, außer man zieht diese groß und sie sehen nicht mehr kompakt aus oder man skaliert die Schrift die man dann nicht mehr lesen kann. Außerdem kann man Buttons wie in meiner Alexa Übersicht nicht mehr schön nebeneinander gestalten da jedes Widget seinen eigenen Rahmen hat und man auch nicht das Icon über die ganze Fläche des Icons anzeigen kann sondern nur in den vorgegebenen Positionen.
Mit der Auflösung hat meine Anfrage nix zutun.

Hier nochmal in der Handyansicht. Leider hab ich gestern keine Screenshots von meinem Problem gemacht. Die mach ich evtl heute Abend wenn ich nochmal Lust hab auf die 3.0 zu wechseln.

![Screenshot_20210915-092419](https://user-images.githubusercontent.com/52470482/133398817-87f4a08c-b2b3-428e-81e2-9293bfddde63.png)
![Screenshot_20210915-092400](https://user-images.githubusercontent.com/52470482/133398845-37af5eff-2157-4ba7-95fe-cb229067967b.png)

**Comment by Zefau** [comment]
Dann mach nochmal Screenshots von der v3 Konvertierung und dann schauen wir mal, wie wir es optimiert bekommen.

**Comment by Kaskadeur111** [comment]
Ich kann dem zu 100% zustimmen. Ich habe auch nur wegen der HomeKit Tiles wieder zur 2.2 zurückwechseln müssen. Es fehlt einfach eine Gruppierungsmöglichkeit von Homekittiles um sie gescheit auf Mobilgeräten darstellen zu können.

Aktuell wird jedes Tile auf 100% breite Skaliert wenn ich jarvis auf dem Smartphone öffne.
Die StatelistHorizontal stellt wenigstens 2 bzw 3 Icons nebeneinander dar.

Bitte gib uns die Möglichkeit der StatelistHorizontal wieder. (oder geht das nicht?)

Wie der Threadersteller bereits schrieb, sind die Homekitiles KEIN Ersatz sondern lediglich eine weitere Form der Darstellung.
Nicht falsch verstehen, die Tiles sind Klasse, aber bieten eben NICHT die Funktionen welche die Statelist Horizontal bieten (Gruppierte Darstellung von "Tiles" nebeneinander).

Für mich spricht nichts dagegen beide Elemente anzubieten und dem Benutzer die Möglichkeit zur Auswahl zu geben welches für seinen Anwendungsfall das bessere ist.

Gruß Jens

**Comment by Kaskadeur111** [comment]
Desktop 2.2 StatelistHorizontal
![image](https://user-images.githubusercontent.com/28257942/146916527-740dfdef-ae0c-4b2e-9dc6-18903b9bcd01.png)

Handy 2.2 StatelistHorizontal
![image](https://user-images.githubusercontent.com/28257942/146916665-787e3ab0-339a-4beb-8bef-3cdae84c437c.png)

Desktop 3.0 Homekittiles
![image](https://user-images.githubusercontent.com/28257942/146916768-dd28a6a7-e45c-4fb9-a65c-d26ac600c165.png)

Handy 3.0 Homekittiles
![image](https://user-images.githubusercontent.com/28257942/146916967-e0a08c6d-a7be-45e4-81d5-3bcefbf34b4a.png)

Ich denke es ist erkennbar dass die Handydarstellung der Homekittiles nicht optimal ist. Ich wünsche mir wie gesagt entweder eine Art Container in welcher man die Homekittiles anordnen kann, damit man mindestens mal 3 Tiles nebeneinander bekommt, oder eben die Skalierung der Homekittiles nicht auf 100%.

**Comment by Zefau** [comment]
Hast du mal das Handy Layout in v3 probiert?

**Comment by Kaskadeur111** [comment]
Ich muss ehrlich gestehen, dass ich mir das kurz angeschaut habe und mir der Gedanke durch den Kopf geschossen ist, dass ich ja dann wieder "2 Oberflächen" pflegen muss, obwohl doch genau das bei Version 2 so super funktioniert... ich baue mir EINE Visualisierung und muss mich nicht darum kümmern wie es auf mobilen endgeräten aussieht, sondern es passt einfach!

Erstes Problem: Die Handyansicht ist nach Migration von 2.2 komplett leer und ich muss alle Widgets aller Tabs händisch hinzufügen.
Zweites Problem: Ich füge in der Desktoplayout Widgets hinzu und muss immer daran denken, dass ich das dann auch nochmal fürs Handy mache.

Also Ja, ich habe es gerade probiert, mit der Handyansicht komme ich durch Probieren und basteln zum Ziel, mit dem Ergebnis, dass ich wieder zusätzlichen Aufwand in der Pflege habe. :-( Das war der Hauptgrund von VIS wegzugehen, weil ich dort genau das gleiche Thema habe: für Mobilgeräte eine eigene Visualisierung zu bauen und separat verwalten zu müssen.

Jarvis 2: Widget dazu, Desktop: Passt, Tablet: Passt Handy klein: Passt Handy groß: passt
Jarvis 3: Widget dazu, Desktop: Passt, Tablet: Widget fehlt
              ..... Widget in die Handyansicht reingenommen: Ansicht passt nicht, Layout anpassten passt.
              ..... Morgen: Widget im Dektoplayout verschoben ... nicht ans Handy gedacht .... Handy Widget ist noch immer an aler Stelle.

Ich finds nicht gut :-)

**Comment by Kaskadeur111** [comment]
Davon abgesehen fehlt mir bei den Homekittiles eine 4. Layoutzeile.
Bei der StatelistHorizontal hatte ich übereinander: Icon, Label, Dropdow Trigger, Subelemente

Das bekomme ich nicht hin mit den Homekittiles. sobald ich das Icon nach links oder rechts packe passt die Darstellung des Labels daneben nicht mehr... es sieht einfach kacke aus, also verzichte ich jetzt auf die Subelemente.

ICh möchte nicht nerven, aber spricht aus deiner Sicht etwas gegen eine "friedliche Koexistenz" von Homekittiles und StatelistHorizontal?

**Comment by Kaskadeur111** [comment]
Kann es sein, dass es beim Handylayout keine automatische Höhenanpassung der Widgets gibt? Ich habe (wie vermutlich der Großteil der Jarvis Nutzer) viele StateLists (die normalen, nicht die Horizontal ;-).

Wenn diese Statelists sich verändern (ich füge States/Schalter hinzu) bleibt das Widget in der Handyansicht bei der fest eingestellten Größe und wächst nicht mit, wie auf der Desktop-Ansicht?

**Comment by Kaskadeur111** [comment]
So, zweiter Versuch auf V3 umzusteigen wird jetzt abgebrochen. Ich muss wieder auf 2.2 zurück. Solange keine StatelistHorizontal in V3 vorhanden ist, macht es für mich keinen Sinn. Ich habe jetzt mehrere Stunden gebastelt und mir die Homekittiles auf fast allen Tabs zurechtgeschustert (schön wars vorher, schöner wirds nicht). Jetzt stelle ich fest, dass auf den Tablets die Smartphone Layout gar nicht greift, sondern das Desktop-Layout...

Guess what: Jetzt zerreist es mir die Homekittiles und zerreist sie wieder, stellt sie nicht nebeneinander sondern übereinander dar und alle anderen Widgets werden umgeordnet...

Das macht alles keinen Sinn, ich brauche das StateListHorizontal, schade um die Zeit :-(

So leid es mir um die ganzen anderen schönen Features tut die ich alle gebrauchen könnte, aber einfachheit und einfache Administration sowie Plattformunabhängikeit sind mir wichtiger.

**Comment by Zefau** [comment]
@Kaskadeur111 mit `v3.0.0-beta.20` gibt es die StateListHorizontal nun wieder. Hierzu die StateList auswählen und die dortigen Optionen aktivieren.

**Comment by Zefau** [comment]
@mcuiobroker fyi

**Comment by Kaskadeur111** [comment]
Danke Dir aus vollem Herzen. Ich hau dir nachher noch eine Donation rein. :-)

**Comment by Kaskadeur111** [comment]
Könnte man bei der Statelist mit aktivierter Horizontaler Darstellung eine Zusatzeinstellung "minimale Breite) einbauen?
Ich habe aktuiell das Problem, dass ein Gerät mit kurzem Namen (Mond) eine schmale Schaltfläche ergibt und mit längerem Namen eine breitere.

Ich möchte erreichen, dass die Schalter gleichmäßig verteilt sind und mindestens mal quadratisch. D.H. wenn man eine Mindestbreite angeben könnte (zb 300px, oder 2w).

![image](https://user-images.githubusercontent.com/28257942/148899473-1920cbeb-a69d-4d40-9a51-a8d1a869a6fc.png)

**Comment by Zefau** [comment]
mit `v3.0.7` sollte es passen

**Comment by gimli1980** [comment]
Der Thread ist zwar schon älter aber passt zu meinem Anwendungsfall:

Ich möchte gerne meine Lichtszenen als Homekit-Tiles abbilden, jedoch so dass ich nur ein Widget mit den bei mir aktuell sechs Szenen habe.

Ich so etwas möglich?

Aktuell habe ich ein Statelist Widget mit den sechs Szenen, hier stört mich allerdings dass ich immer auf den Button drücken muss um die Szene zu schalten und nicht "irgendwo" auf dem entsprechenden State so wie es bei Homekit-Tile ist.

Die Triggeraction statt dem Popup zu konfigurieren geht ja in der Statelist nicht, oder? 

Ich hoffe man versteht was ich meine. 

So hätte ich halt sechs separate Homekit-Tiles nebeneinander was ich nicht sehr schon finde.

![image](https://user-images.githubusercontent.com/120038224/229179979-eedd2758-1a74-4ba7-8945-3ff060384f5b.png)

![image](https://user-images.githubusercontent.com/120038224/229180030-43ccfaa4-95f9-45dd-b40b-1baf3457c33f.png)

**Comment by Kaskadeur111** [comment]
Ja, das kann ich gut verstehen. Hatte vor 3 Wochen auch wieder dieses Verlangen.

Es müsste halt in der Statelist möglich sein für jedes Element eine Vollflächig Trigger anstatt des Popups geben. Es ist halt einfach bissl fummelig genau den switch oder den acrionbutton zu treffen. Obendrein muss man immer dran denken das Popup zu deaktivieren (aber das ist eine andere Geschichte).

Ich bin auch sehr dafür, die vollflächige Triggeraction in der Statelist (auch in der  Horizontal Einstellung) nutzbar zu machen.

Die Homekittiles sind halt einfach mal Sch....umständlich zu konfigurieren... und du machst das halt für jedes Gerät einzeln. Am Ende zerrupft es dir dann auch noch die einzelnen Elemente auf dem Rablet oder Handy... und es sieht nicht mehr schön aus.

**Comment by gimli1980** [comment]
Schade das klingt so als würde es keine Lösung geben. 

Ansonsten bin ich bis jetzt mit JARVIS sehr zufrieden, aber das stört mich schon sehr.

**Comment by mcuiobroker** [comment]
Evtl kann man was mit scripts machen. 
Wenn man die komplette Statelistzeile als Klickauslöser haben möchte, kann man aber kein Geräte-Popup aufrufen mit der Zeile.

**Comment by Kaskadeur111** [comment]
> Evtl kann man was mit scripts machen. 
> Wenn man die komplette Statelistzeile als Klickauslöser haben möchte, kann man aber kein Geräte-Popup aufrufen mit der Zeile. 

Kannst du das erklären, das würde mich interessieren. Das Popup wird bei dem Anwendungsfall dann tatsächlich nicht benötigt.

Wie meinst du das mit scripts? Gibt es in Jarvis scripts??

**Comment by mcuiobroker** [comment]
Mit PRO kann man auch scripts nutzen. Bin jetzt unterwegs.  Kann ich später oder evtl morgen erklären.

**Comment by Kaskadeur111** [comment]
> Mit PRO kann man auch scripts nutzen. Bin jetzt unterwegs.  Kann ich später oder evtl morgen erklären. 

Gerne. Pro bin ich.

**Comment by mcuiobroker** [comment]
Also was soll beim Klicken auf die StateListzeile genau passieren?
Soll es nur dann passieren, wenn ein Actionelement `SwitchAction` aktiviert wurde?

**Comment by gimli1980** [comment]
Ich bin auch, das wäre genau das was ich suche.

Die Popups benötige ich auch nicht.

**Comment by Kaskadeur111** [comment]
> Also was soll beim Klicken auf die StateListzeile genau passieren?
> Soll es nur dann passieren, wenn ein Actionelement `SwitchAction` aktiviert wurde?
> 
> ![slItemClick Beispiel](https://user-images.githubusercontent.com/84818934/229306946-3f92a758-c802-45a9-b5ef-4ca84c4ef669.gif)
> 

Das sieht schon gut aus. ICH würde den switch komplett weglassen und nur über das Icon vorn den Zustand signalisierte wollen. (zb Lampe gelb ist an und Grau ist aus). Egal was ich anklicke (Icon oder Text) soll einfach true und false wechseln.

**Comment by gimli1980** [comment]
Exakt, so habe ich es mir auch vorgestellt. 

Wie hast du das jetzt umgesetzt

**Comment by mcuiobroker** [comment]
Das wird alles, wie immer, in der Doku unter `scripts` erklärt. Muss es aber noch schreiben. Hoffe, es ist bis heute Abend fertig.

**Comment by gimli1980** [comment]
Ich bin mir der Doku als absoluter Anfänger kläar gekommen. 

Funktioniert einwandfrei und genau wie ich es wollte. 

Tausend Dank für deine Mühe!!

**Comment by mcuiobroker** [comment]
Kannst du gerne machen, damit es nicht vergessen wird. Es gibt aber noch viele andere.
Wichtiger aus meiner Sicht wäre es mehrere DPs in einer StateListzeile verarbeiten zu können mit Buttons usw.
Also mehrere Schalter in einer StateList Zeile im Standard?

**Comment by Zefau** [comment]
Jo, dafür gibt es meine ich einen Feature Request
