### ISSUE TITLE
Jarvis after Upgrade from 2.2.2 to 2.2.3 Users no more working

### ISSUE THREAD

**Issue by florian1984** [Zefau/ioBroker.jarvis#1002]
Jarvis Version 2.2.3

Receive after login a 404 Message:

![image](https://user-images.githubusercontent.com/12068197/133440435-e99d1769-9a6a-4c71-aa6b-787e852888e6.png)

This happens after upgrade from 2.2.2. The login with the admin user still works normally.  Also tryed to restart iobroker and created another user. same issue :(

**Comment by Zefau** [comment]
Please upload the adapter
```
iobroker upload jarvis
```

**Comment by florian1984** [comment]
I run it, but issue still exist :(

upload [5] jarvis.admin /opt/iobroker/node_modules/iobroker.jarvis/admin/zefau.jpg zefau.jpg image/jpeg
upload [4] jarvis.admin /opt/iobroker/node_modules/iobroker.jarvis/admin/words.js words.js application/javascript
upload [3] jarvis.admin /opt/iobroker/node_modules/iobroker.jarvis/admin/jarvis.png jarvis.png image/png
upload [2] jarvis.admin /opt/iobroker/node_modules/iobroker.jarvis/admin/index_m.html index_m.html text/html
upload [1] jarvis.admin /opt/iobroker/node_modules/iobroker.jarvis/admin/admin.js admin.js application/javascript
upload [0] jarvis.admin /opt/iobroker/node_modules/iobroker.jarvis/admin/admin.css admin.css text/css
upload [200] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/media/jsoneditor-icons.15f2789d.svg static/media/jsoneditor-icons.15f2789d.svg image/svg+xml
upload [150] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/media/11.2dcc6324.png static/media/11.2dcc6324.png image/png
upload [100] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/46.94bc69d8.chunk.js static/js/46.94bc69d8.chunk.js application/javascript
upload [90] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/41.4cda66c0.chunk.js static/js/41.4cda66c0.chunk.js application/javascript
upload [80] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/37.d8e1e7f7.chunk.js static/js/37.d8e1e7f7.chunk.js application/javascript
upload [70] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/32.729b3cd1.chunk.js static/js/32.729b3cd1.chunk.js application/javascript
upload [60] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/28.6466f838.chunk.js.map static/js/28.6466f838.chunk.js.map application/json
upload [50] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/23.e8ef9d93.chunk.js.map static/js/23.e8ef9d93.chunk.js.map application/json
upload [40] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/2.71eba6ca.chunk.js static/js/2.71eba6ca.chunk.js application/javascript
upload [30] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/15.e262a4e2.chunk.js static/js/15.e262a4e2.chunk.js application/javascript
upload [20] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/1.1aa34924.chunk.js.map static/js/1.1aa34924.chunk.js.map application/json
upload [19] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/1.1aa34924.chunk.js static/js/1.1aa34924.chunk.js application/javascript
upload [18] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/0.77ba99e2.chunk.js.map static/js/0.77ba99e2.chunk.js.map application/json
upload [17] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/0.77ba99e2.chunk.js.LICENSE.txt static/js/0.77ba99e2.chunk.js.LICENSE.txt text/plain
upload [16] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/js/0.77ba99e2.chunk.js static/js/0.77ba99e2.chunk.js application/javascript
upload [15] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/css/main.d4b7edcc.chunk.css.map static/css/main.d4b7edcc.chunk.css.map application/json
upload [14] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/css/main.d4b7edcc.chunk.css static/css/main.d4b7edcc.chunk.css text/css
upload [13] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/css/2.0cb40693.chunk.css.map static/css/2.0cb40693.chunk.css.map application/json
upload [12] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/static/css/2.0cb40693.chunk.css static/css/2.0cb40693.chunk.css text/css
upload [11] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/manifest.json manifest.json application/json
upload [10] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/jarvis512.png jarvis512.png image/png
upload [9] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/jarvis192.png jarvis192.png image/png
upload [8] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/jarvis.svg jarvis.svg image/svg+xml
upload [7] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/index.html index.html text/html
upload [6] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/favicon16x16.ico favicon16x16.ico image/vnd.microsoft.icon
upload [5] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/favicon.txt favicon.txt text/plain
upload [4] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/favicon.ico favicon.ico image/vnd.microsoft.icon
upload [3] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/favicon-96x96.png favicon-96x96.png image/png
upload [2] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/favicon-32x32.png favicon-32x32.png image/png
upload [1] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/favicon-16x16.png favicon-16x16.png image/png
upload [0] jarvis /opt/iobroker/node_modules/iobroker.jarvis/www/asset-manifest.json asset-manifest.json application/json

**Comment by Zefau** [comment]
It is an ioBroker error, not Jarvis. Try to reinstall and / or reboot the whole machine.

**Comment by florian1984** [comment]
I tryed everthing of this :(, also reinstalled the older 2.2.1 version and the issue also occured in this version.  So it's not a bug from the upgrade :(.  I also added the other user into admin grp. But always receiving this strange message.  I don't see any further information about this 404 message :(. Its only on the jarvis gui, all other gui/interfaces have no issue at all.

**Comment by Zefau** [comment]
Are you on Windows or Linux?

Did you restart Web Adapter and / or ioBroker?
Do you have Puffer deactivated in Web Adapter?

The iobroker-data path has a files subfolder, which should hold a Jarvis folder. What is in there?

**Comment by florian1984** [comment]
Im running it on Linux. I've tryed follow yet:

- Reboot Server 
- iobroker update all
- uninstall adapter & instance => web & jarvis
- unflag cache in web.0
- sudo npm cache clean

Files:

/opt/iobroker/iobroker-data/files/jarvis
/opt/iobroker/iobroker-data/files/jarvis/favicon.ico
/opt/iobroker/iobroker-data/files/jarvis/_data.json
/opt/iobroker/iobroker-data/files/jarvis/favicon-96x96.png
/opt/iobroker/iobroker-data/files/jarvis/favicon16x16.ico
/opt/iobroker/iobroker-data/files/jarvis/jarvis.svg
/opt/iobroker/iobroker-data/files/jarvis/manifest.json
/opt/iobroker/iobroker-data/files/jarvis/static
/opt/iobroker/iobroker-data/files/jarvis/static/media
/opt/iobroker/iobroker-data/files/jarvis/static/media/8.9011b110.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/18.d4bb4d43.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/10.f723ab13.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/15.59413df7.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/jsoneditor-icons.15f2789d.svg
/opt/iobroker/iobroker-data/files/jarvis/static/media/10.636bb339.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/3.13b133db.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/23.09d8a035.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/StateList4.20cba125.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/StateList2.80772e80.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/paypal.6e9cd511.webp
/opt/iobroker/iobroker-data/files/jarvis/static/media/Chart1.f8783a9b.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/Map1.ff2fce82.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/14.70aed19e.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/13.28cfa995.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/19.9ffa5282.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/7.cf20f842.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/2.29f75db9.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/3.a451d661.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/11.2dcc6324.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/2.ff38fad0.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/24.3f480ec5.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/15.a88798db.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/16.4cfb5002.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/9.9dc0f52e.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/13.a630a54d.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/20.80127422.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/1.8846187f.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/7.439d10db.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/9.f7e60138.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/28.26fa25b2.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/12.ee46662d.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/6.1435f645.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/17.38b2c7a7.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/LightColorBody.f8c51553.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/5.6d9f449c.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/12.436b3798.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/26.28674df5.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/29.fdc223a8.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/17.41a91497.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/6.201eee37.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/4.61c6ba58.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/5.5334b7ac.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/AdapterStatus1.c6728d55.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/8.dece6009.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/11.640e700e.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/27.c8330381.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/zefau.a31ad1d9.jpg
/opt/iobroker/iobroker-data/files/jarvis/static/media/1.6d4b68da.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/22.8b8c1aed.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/21.f3b5ba0a.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/18.f6520049.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/25.b9d0e8d2.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/14.0df353ed.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/16.89f6b8f7.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/0.389f1683.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/4.6da093c5.png
/opt/iobroker/iobroker-data/files/jarvis/static/media/19.3d4147e1.png
/opt/iobroker/iobroker-data/files/jarvis/static/js
/opt/iobroker/iobroker-data/files/jarvis/static/js/46.94bc69d8.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/42.17ba5c0c.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/28.6466f838.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/2.71eba6ca.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/13.864a2ea3.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/11.c78c798b.chunk.js.LICENSE.txt
/opt/iobroker/iobroker-data/files/jarvis/static/js/2.71eba6ca.chunk.js.LICENSE.txt
/opt/iobroker/iobroker-data/files/jarvis/static/js/3.c8fe7309.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/24.64807e23.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/6.97ea0742.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/17.6e9b632c.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/36.a96368df.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/30.bf22ecd6.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/42.17ba5c0c.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/0.77ba99e2.chunk.js.LICENSE.txt
/opt/iobroker/iobroker-data/files/jarvis/static/js/39.b68ab910.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/19.329ba512.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/61.9a353a6c.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/11.c78c798b.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/49.4ed78a4d.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/runtime-main.25771fde.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/13.864a2ea3.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/52.22834fb0.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/27.a22fcfa6.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/44.890682da.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/4.af3e467e.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/35.711dd357.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/54.20d891bb.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/21.221260e8.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/27.a22fcfa6.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/53.15816c7a.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/32.729b3cd1.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/41.4cda66c0.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/57.b46e22e3.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/main.88d11915.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/50.c9de5a9e.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/26.99dc6537.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/15.e262a4e2.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/60.6caed032.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/47.286530be.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/37.d8e1e7f7.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/main.88d11915.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/36.a96368df.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/7.23e9264f.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/37.d8e1e7f7.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/56.9b879db1.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/31.05599e24.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/35.711dd357.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/11.c78c798b.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/55.ccfa019e.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/7.23e9264f.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/38.69f67802.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/43.95380c7d.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/48.ec4b15a6.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/61.9a353a6c.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/43.95380c7d.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/33.fca30c85.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/5.bcaaf27f.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/26.99dc6537.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/8.944dd67a.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/29.f074ed27.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/runtime-main.25771fde.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/18.8376a382.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/31.05599e24.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/25.c28830c3.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/8.944dd67a.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/23.e8ef9d93.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/45.bd3a098d.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/58.c8c3e63c.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/16.c66f1f4c.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/45.bd3a098d.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/18.8376a382.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/59.429fd52f.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/14.6a760246.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/24.64807e23.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/33.fca30c85.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/12.1783ef5e.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/51.cd9ac3f4.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/55.ccfa019e.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/22.2f5675ef.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/40.fb474445.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/32.729b3cd1.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/46.94bc69d8.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/53.15816c7a.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/51.cd9ac3f4.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/60.6caed032.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/6.97ea0742.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/0.77ba99e2.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/23.e8ef9d93.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/39.b68ab910.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/15.e262a4e2.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/5.bcaaf27f.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/6.97ea0742.chunk.js.LICENSE.txt
/opt/iobroker/iobroker-data/files/jarvis/static/js/3.c8fe7309.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/44.890682da.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/30.bf22ecd6.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/14.6a760246.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/1.1aa34924.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/34.c73d7735.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/48.ec4b15a6.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/38.69f67802.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/17.6e9b632c.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/54.20d891bb.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/49.4ed78a4d.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/25.c28830c3.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/52.22834fb0.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/3.c8fe7309.chunk.js.LICENSE.txt
/opt/iobroker/iobroker-data/files/jarvis/static/js/4.af3e467e.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/2.71eba6ca.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/34.c73d7735.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/58.c8c3e63c.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/22.2f5675ef.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/20.d0ac7e2a.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/59.429fd52f.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/19.329ba512.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/21.221260e8.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/0.77ba99e2.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/12.1783ef5e.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/28.6466f838.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/16.c66f1f4c.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/41.4cda66c0.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/40.fb474445.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/20.d0ac7e2a.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/56.9b879db1.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/1.1aa34924.chunk.js.map
/opt/iobroker/iobroker-data/files/jarvis/static/js/57.b46e22e3.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/50.c9de5a9e.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/29.f074ed27.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/js/47.286530be.chunk.js
/opt/iobroker/iobroker-data/files/jarvis/static/css
/opt/iobroker/iobroker-data/files/jarvis/static/css/2.0cb40693.chunk.css
/opt/iobroker/iobroker-data/files/jarvis/static/css/main.d4b7edcc.chunk.css.map
/opt/iobroker/iobroker-data/files/jarvis/static/css/2.0cb40693.chunk.css.map
/opt/iobroker/iobroker-data/files/jarvis/static/css/main.d4b7edcc.chunk.css
/opt/iobroker/iobroker-data/files/jarvis/favicon-32x32.png
/opt/iobroker/iobroker-data/files/jarvis/vendor
/opt/iobroker/iobroker-data/files/jarvis/vendor/jsoneditor.css
/opt/iobroker/iobroker-data/files/jarvis/vendor/images
/opt/iobroker/iobroker-data/files/jarvis/vendor/images/marker-icon.png
/opt/iobroker/iobroker-data/files/jarvis/vendor/images/marker-shadow.png
/opt/iobroker/iobroker-data/files/jarvis/vendor/images/layers-2x.png
/opt/iobroker/iobroker-data/files/jarvis/vendor/images/marker-icon-2x.png
/opt/iobroker/iobroker-data/files/jarvis/vendor/images/layers.png
/opt/iobroker/iobroker-data/files/jarvis/vendor/leaflet.css
/opt/iobroker/iobroker-data/files/jarvis/favicon.txt
/opt/iobroker/iobroker-data/files/jarvis/jarvis512.png
/opt/iobroker/iobroker-data/files/jarvis/index.html
/opt/iobroker/iobroker-data/files/jarvis/asset-manifest.json
/opt/iobroker/iobroker-data/files/jarvis/jarvis192.png
/opt/iobroker/iobroker-data/files/jarvis/favicon-16x16.png
/opt/iobroker/iobroker-data/files/jarvis.admin
/opt/iobroker/iobroker-data/files/jarvis.admin/_data.json
/opt/iobroker/iobroker-data/files/jarvis.admin/jarvis.png
/opt/iobroker/iobroker-data/files/jarvis.admin/zefau.jpg
/opt/iobroker/iobroker-data/files/jarvis.admin/words.js
/opt/iobroker/iobroker-data/files/jarvis.admin/admin.js
/opt/iobroker/iobroker-data/files/jarvis.admin/index_m.html
/opt/iobroker/iobroker-data/files/jarvis.admin/admin.css

**Comment by florian1984** [comment]
I've also upgraded the core to 3.3.18. First it didnt worked but from nothing it started to work again.  I dont have good feeling about that :(. 

Thanks anyways for your support, work.

**Comment by Zefau** [comment]
we keep an eye on it :-)
