### ISSUE TITLE
v3: Lange Ladezeit auf Handy für 1. Seite

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1003]
Die Ladezeit für die erste Seite ist sehr lang. Werden evtl alle Seiten direkt geladen? Kann man dort die Selektierte Seite mit Priorität laden und erst dann alles andere?

https://user-images.githubusercontent.com/84818934/133463783-d5cea4f6-9ba7-4424-a7b6-2cbe94e2ab0d.mp4

**Comment by Zefau** [comment]
Schwierig. Probier mal mit `v3.0.0-alpha.79`, ob es etwas besser ist.

**Comment by mcuiobroker** [comment]
Leider nein. Keine Veränderung erkennbar.

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.81`. Habe nun die gesamte Architektur nochmal umgebaut. Es sollte nun wesentlich schneller sein.

Dadurch, dass ich so extrem viel anpassen musste, kann es sein, dass es im Zusammenhang mit der Anzeige oder dem Schalten von States zu (neuen) Fehlern kommt. Diese dann bitte direkt hier rein.

**Comment by mcuiobroker** [comment]
Also: 

- [ ] Es wurden beim Update Icons gelöscht und woanders auch in ganz andere StateLists verwendet, wo vorher andere waren.
- [ ] Im Popup fehlen die ActionElemente Schalter sind nicht da nur die Statewerte
![image](https://user-images.githubusercontent.com/84818934/134803855-8604edf0-4ae6-4264-84ee-db234391a964.png)
![image](https://user-images.githubusercontent.com/84818934/134803886-f864546c-16c0-4781-a587-fca7cdd6282b.png)

- [ ] Auch die Iconfarbe wird nicht korrekt dargestellt.

**Comment by mcuiobroker** [comment]
Zu den Icons:
vorher wurde bei der Jalousie das Standard-Icon angezeigt.
![image](https://user-images.githubusercontent.com/84818934/134804246-3b691e19-08f4-426b-9af8-41ab632db3a3.png)

Wenn ich nur in der Jalousie das Icon anpasse, wird es in mehreren Widgets geändert:
![image](https://user-images.githubusercontent.com/84818934/134804224-3ac35f65-88f3-4d11-9c18-aeaad3a34716.png)
![image](https://user-images.githubusercontent.com/84818934/134804231-6ecb4fb9-6ae5-4cdc-a881-cc17bbc0f29b.png)

**Comment by mcuiobroker** [comment]
Bei einem Dropdown kommt die Meldung, ist aber bei allen DropdownAction
![image](https://user-images.githubusercontent.com/84818934/134804399-5b030536-44e5-4bf8-a13b-19381b1e2722.png)

obwohl vorhanden
![image](https://user-images.githubusercontent.com/84818934/134804387-39efcc7c-5529-49f3-8698-b44eebb40cf6.png)

**Comment by mcuiobroker** [comment]
- [ ] Zahl schalten funktioniert nicht mehr
![image](https://user-images.githubusercontent.com/84818934/134805180-55024fe8-b568-405e-b94c-147677dc6933.png)

Der SwitchButton wird nicht umgesetzt nach dem Schalten. Er bleibt in der Position stehen. Die Zahl wird korrekt eingetragen. Nach F5 Reload ist der Button wieder an der richtigen Stelle.

**Comment by mcuiobroker** [comment]
- [ ] Mouse-over-Effekt im anderen Widget?
![v3-81-mouseover-effekt im anderen Widget](https://user-images.githubusercontent.com/84818934/134805318-cd885ebe-608b-4eb5-8ca5-4365bcc0390b.gif)

**Comment by mcuiobroker** [comment]
- [ ] Popup von einem Gerät

Die ohne eigenes Label, werden nicht korrekt angezeigt. Dort müsste ja der DP-Bezeichner stehen
Mit eigenem Label:
![image](https://user-images.githubusercontent.com/84818934/134805404-f725cab4-a394-43be-b41e-b6ce65968cdc.png)
Ohne eigenes Label:
![image](https://user-images.githubusercontent.com/84818934/134805431-17e39f60-7f1c-4303-967d-3b94e0bf633a.png)

![image](https://user-images.githubusercontent.com/84818934/134805376-ad1ed50d-94e5-42ae-82a6-ccee4de44aa9.png)

**Comment by Zefau** [comment]
> Mouse-over-Effekt im anderen Widget?

Liegt glaube ich an deinen Styles?

**Comment by mcuiobroker** [comment]
Jetzt komme ich gar nicht mehr in die Konfiguration, bleibt schwarz.

**Comment by mcuiobroker** [comment]
In der Instanz sind Textüberschneidungen:
![image](https://user-images.githubusercontent.com/84818934/134805875-9ad6b945-3e42-485b-856b-a36ce654cf8e.png)

**Comment by Zefau** [comment]
>  Die F2 funktioniert nicht mehr.

Daran habe ich nichts geändert und es funktioniert (bei mir) auch noch.

**Comment by mcuiobroker** [comment]
> > Mouse-over-Effekt im anderen Widget?
> 
> Liegt glaube ich an deinen Styles?

Habe CSS komplett rausgenommen, trotzdem bleibt es bie dem Effekt.

**Comment by mcuiobroker** [comment]
> > Die F2 funktioniert nicht mehr.
> 
> Daran habe ich nichts geändert und es funktioniert (bei mir) auch noch.

Ich hatte F2 genutzt und bekam einen schwarzen Bildschirm? Jetzt läuft es auch wieder bei mir. Echt komisch.

**Comment by mcuiobroker** [comment]
- [ ] LevelBody zeigt wieder alle Werte an bei Schrittweite 1, obwohl Anzahl der Markierungen auf 10 steht:

![image](https://user-images.githubusercontent.com/84818934/134816424-5fac406e-a474-459f-80cb-5278322c4da0.png)

![image](https://user-images.githubusercontent.com/84818934/134816440-8cf7c4ba-b812-421d-b068-84549245b9fd.png)

**Comment by mcuiobroker** [comment]
- [ ] Binding reagiert nicht sofort, bzw. Änderung in ioBroker werden nicht in jarvis umgesetzt. Erst nach F5 erscheint der korrekte Wert.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.82` Popup weiterhin nicht korrekt
![image](https://user-images.githubusercontent.com/84818934/134823366-7bee914e-08a2-48ab-8553-84e51f8b6237.png)

**Comment by Zefau** [comment]
Ich hab abgehakt, woran ich gearbeitet habe. Nur Dropdown und ActionElemente im Popup. Die Icons sind noch offen.

**Comment by mcuiobroker** [comment]
Die Label sind das Problem.

**Comment by Zefau** [comment]
Auch daran habe ich nicht gearbeitet.

**Comment by mcuiobroker** [comment]
Vorher war es so bei den Labels: Wenn der DP im Gerät kein Label hatte, so wurde der DP-Bezeichner als Label für das Popup verwendet. Also es muss dort was geändert worden sein. Sonst wären bei mir noch alle Labels (DP-Bezeichner) zu sehen und nicht das Geräte-Label.

**Comment by Zefau** [comment]
siehe Text von https://github.com/Zefau/ioBroker.jarvis/issues/1003#issuecomment-927270609

**Comment by Zefau** [comment]
Wegen des Labels: Ich habe die folgenden Möglichkeiten zur Auswahl
1. Label aus dem Layout (nicht im Popup)
2. Label aus dem Datenpunkt
3. Datenpunkt-Bezeichner (nur Popup)
4. Geräte-Name
5. Geräte-Label

Die obige Reihenfolge wird aktuell angewandt. Also, wenn ein Wert nicht da ist, greift der nächste Wert.
Also sprich wenn kein Label im Layout (`#1`) angegeben ist und kein Label im Datenpunkt (`#2`), dann greift der Geräte-Name (`#4`) (sofern nicht im Popup). Im Popup würde `#3` greifen.

**Comment by Zefau** [comment]
Das mit dem Label ist mit `v3.0.0-alpha.84` nun angepasst.

**Comment by mcuiobroker** [comment]
Offene Punkte einzeln eingestellt. Hier zu unübersichtlich geworden.
