### ISSUE TITLE
v3: Beim ersten Seitenaufruf wird der TAB (z.b.:Home) nicht selektiert, obwohl er angezeigt wird

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1005]
`v3.0.0-alpha.78` Er blinkt kurz blau auf wird wieder "deselektiert"? 
![image](https://user-images.githubusercontent.com/84818934/133465604-057714b5-0d26-4160-964a-4462800c61c1.png)

**Comment by Zefau** [comment]
Die URL ist ohne Tab Angabe?

**Comment by mcuiobroker** [comment]
War noch alter Aufbau:
`http://192.168.178.70:8082/jarvis/index.html#/instance=0`
