### ISSUE TITLE
v3: Anzeigevariante (JSON Format) funktioniert nicht mehr

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1006]
3.0.0-alpha.78

Nach Installation der Version jarvis 3.0.0-alpha.78 (ohne Neustart vom IOBroker) war noch alles OK.
Aber nach dem Neustart vom IOBroker funktioniert die Anzeigevariante (JSON Format) nicht mehr.

Folgendes steht bei mir als Format drin:
{"true":"Online","false":"Offline"}

Angezeigt wird aber jetzt nur noch "true" oder "false".
Es betrifft aber nicht alle Geräte, z.B. hab ich das bei dem Shelly Adapter.
Es wird nur das angezeigt, was tatsächlich im Datenpunkt steht

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1009

**Comment by Bernd9000** [comment]
Dieses Issues war das Orginal und kein Duplikat
