### ISSUE TITLE
v3: TABs auch in Abhängigkeit von Werten (Bindings) Klassen zuordnen können

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1007]
KEIN BUG, falsche geklickt, ändern auf feature.
Ziel: (zusätzliches Feld "TAB-Stil")
Falls sich besondere Werte ändern und diese sind in TAB-Stil definiert, so kann man dadurch die Tabs vergrößern, blinken lassen, Hintergrundfarbe ändern, Text ändern, Icon ändern usw.

**Comment by Zefau** [comment]
closed in the favor of https://github.com/Zefau/ioBroker.jarvis/issues/1352
