### ISSUE TITLE
v3:  ICON mit base64-Code Klassen zuordnen können

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1008]
Bsilang auch in v2 ist es so, dass man den Icons mit base64 keine Klassen zuordnen kann.
Bei anderen Icons funktioniert es : 
`{"0":"home blink"}` -> Das home-Icon blinkt.
Mit base64-Icons:
`{"0":"data:image/png;base64,iVBORw0KGgoAA.....xxcxssc blink"}` funktioniert es nicht.
Obwohl in base64 keine Leerzeichen vorkommen dürfen.

**Comment by Zefau** [comment]
please test and verify with `v3.0.0-alpha.79`.

**Comment by mcuiobroker** [comment]
Funktioniert.Prima.Danke.
