### ISSUE TITLE
v3: "Anzeigevariante" is no longer working at all (alpha-78)

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1009]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

v3.0.0 alpha-78

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

"Anzeigevariante" is no longer working at all (alpha-78). Was working with alpha-77

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

All devices do not show the configured "Anzeigevariante" any more
![image](https://user-images.githubusercontent.com/79741077/133494027-2dad5feb-47f5-436c-ab60-09b71e050fff.png)

 Example-Config for "Wohnzimmerluftbefeuchter", but the error is there for all :-(
![image](https://user-images.githubusercontent.com/79741077/133494183-443d1777-182e-43e7-a615-dff249ee932b.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.79`.

**Comment by Zefau** [comment]
@RkcCorian geht wieder?

**Comment by RkcCorian** [comment]
@Zefau: Die Anzeige ja. Jetzt habe ich aber einen anderen Fehler... ioBroker reagiert nicht mehr auf Eingaben von JARVIS. Wenn ich einen Switch schalte oder einen Button drücke passiert nichts :-|

**Comment by Zefau** [comment]
Siehe https://github.com/Zefau/ioBroker.jarvis/issues/670

Welcher Benutzer ist im Web Adapter einstellt?

**Comment by RkcCorian** [comment]
@Zefau: Schaue gerade auf einen Switch: Interessant ist, dass der DP-Wert gesetzt wird, allerdings bestätigt. Das führt dazu dass nichts passiert. Hab es gerade manuell nachstellen können. Wenn der DP-Wert unbestätigt gesetzt wird reagiert auch der Adapter. Bestätigt reagiert er nicht. (Nach meinem Verständnis sollte JARVIS auch unbestätigt setzen).

**Comment by RkcCorian** [comment]
> Siehe #670
> 
> Welcher Benutzer ist im Web Adapter einstellt?

Admin
