### ISSUE TITLE
True\False command for ButtonAction\IconButtonAction 

### ISSUE THREAD

**Issue by vvfrwl** [Zefau/ioBroker.jarvis#1010]
ButtonAction and IconButtonAction do not have an option to set a state to "false".
The button sends "true" always.
It`s impossible to make the "Switch Off" button without an additional state and script for inverting the signal. 
- Jarvis v2.2.1 

Thank you,
Best regards,

**Comment by Zefau** [comment]
This has been changed in v3. Please upgrade and enjoy :-)

**Comment by mcuiobroker** [comment]
Funktioniert.
