### ISSUE TITLE
v3: LevelBody zu nahe am Secondary State

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1012]
jarvis 3.0.0-alpha.79

Meiner Meinung nach sind die Body Elemente "LevelBody" zu weit nach rechts gezogen seit Version alpha.79
Die Secondary State sind bei kleiner Auflösung nur noch schlecht zu lesen.

![Unbenannt](https://user-images.githubusercontent.com/77005685/133695034-c80609ef-e2cf-44cb-9a8e-c60e5e513b59.jpg)

**Comment by mcuiobroker** [comment]
Ausserdem waren sonst LevelBody und Label auf gelicher Höhe. Dies scheint eine Variante fürs Handy zu sein. Da macht es Sinn.
Bild aus einem Popup auf dem PC:
![image](https://user-images.githubusercontent.com/84818934/133695816-aa8f1e19-2b79-4643-b2ce-ae9b27d3d9e4.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/997
