### ISSUE TITLE
setState without ack

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1015]
> Schaue gerade auf einen Switch: Interessant ist, dass der DP-Wert gesetzt wird, allerdings bestätigt. Das führt dazu dass nichts passiert. Hab es gerade manuell nachstellen können. Wenn der DP-Wert unbestätigt gesetzt wird reagiert auch der Adapter. Bestätigt reagiert er nicht. (Nach meinem Verständnis sollte JARVIS auch unbestätigt setzen).

_Originally posted by @RkcCorian in https://github.com/Zefau/ioBroker.jarvis/issues/1009#issuecomment-921560220_

**Comment by Zefau** [comment]
@RkcCorian back to normal with `v3.0.0-alpha.80`.

**Comment by RkcCorian** [comment]
@Zefau: Ja, läuft wieder.
