### ISSUE TITLE
v3: secondary state nicht lesbar

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1016]
3.0.0-alpha.79

Werte im secondary state können nicht abgelesen werden weil die Zahl vom LevelBody hier den Wert überlagert:

![Unbenannt](https://user-images.githubusercontent.com/77005685/133772766-5317b156-1791-4c58-a669-fca77035ce7e.jpg)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/997
