### ISSUE TITLE
Jarvis startet nicht 

### ISSUE THREAD

**Issue by lowmax256** [Zefau/ioBroker.jarvis#1017]
jarvic v.2.2.1

Jarvis bleibt beim ladescreen hängen. Chrome, Firefox, Opera alles gleiches Problem.
![Jarvis1](https://user-images.githubusercontent.com/90929243/133834897-49997250-a98d-4c4c-aab2-3e8cf3e6872a.JPG)
![Jarvis2](https://user-images.githubusercontent.com/90929243/133835359-4ce96c0f-0dbe-47de-bcc0-8d29f8007785.JPG)

**Comment by Zefau** [comment]
Wie ist der Web-Adapter und der Socket-Adapter eingestellt?

**Comment by lowmax256** [comment]
![Jarvis3](https://user-images.githubusercontent.com/90929243/133879332-cd8ffc47-ec9b-4548-9c6d-585301e87c62.JPG)
Secket Adapter ist nicht installiert sondern im web integriert.

**Comment by lowmax256** [comment]
Kriege ich keine Hilfe hier?

Am Tablet geht die Seite auf. Ist aber total schlecht zu bedienen die Programmierung.

**Comment by Zefau** [comment]
Die Einstellung des Web Adapters sieht gut aus. Könntest höchstens nochmal Socket.io installieren und im Web Adapter umstellen.

Alternativ kannst du auch die v3 probieren.
