### ISSUE TITLE
v3: Auswahlwert auch mit Funktionen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1018]
Zurzeit kann man ja in den Feldern bestimmten Statewerten ein Icon, Anzeigewert oder anderes zuordnen.
Für manche Funktionen ist auch interessant, was steht in dem State, dafür bräuchte man eine Funktion innerhalb vom "Auswahlwert"

"Auswahlwert" ist ja jetzt  ` {"0":"TEST0","1":"TEST1"}`
Dort sollte es auch die Möglichkeit geben:
folgende Funktionen abbilden zu können:
Länge vom String-Statewert: 
`{"length(value)>10":"TESTlang","length(value)<0":"Fehler"}`
Inhalt vom Statewert:
`{"indexOf(value)='TEST'":"gefunden"}`
parseFloat, parseInt usw, also alle Funktionen, die man in javascript direkt verwenden kann, ist die angebenen Funktion nicht vorhanden, so bekommt man schon bei der bestätigten Eingabe von dem JSON einen Hinweis, das es diese nicht gibt.

Würde man diese Funktionen mit in der Datenpunkt-Eigenschaft umsetzen so würde sich ja der WERT(val) ändern und diesen könnte man dann nicht mehr anzeigen lassen

**Comment by Zefau** [comment]
Für die Begriffserklärung: Generell ist `val` immer der Rohwert und wird nie geändert. `value` ist der auf `val` basierende Wert abhängig von `display` und Callback Funktion.

**Comment by Zefau** [comment]
@mcuiobroker auch wenn das Binding gerade etwas Buggy ist, ist dieser Feature Request mit v3.1 umgesetzt
