### ISSUE TITLE
3.0.0-alpha.80: HomekitTile nicht im Backend aber im Frontend

### ISSUE THREAD

**Issue by Hohenbostler** [Zefau/ioBroker.jarvis#1022]
Ich sehe in der config 4 Widget´s für anwesenheit,
Im frontend gibt aber noch ein verstecktes
![unknown](https://user-images.githubusercontent.com/42488069/134165331-f9a32cfc-cc9d-4cf7-8f28-3ef267712d4f.png)
![unknown1](https://user-images.githubusercontent.com/42488069/134165332-a3ed56c7-e003-4308-8f11-2eadc4e90474.png)

**Comment by Zefau** [comment]
Bitte die Konfiguration komplett screenshoten. Was für ein Gerät nutzt du? Tablet?

**Comment by Zefau** [comment]
Was für ein Gerät nutzt du für die Front-End-Anzeige?

Ein HomeKitTile überlagert ganz links oben ein anderes Widget.

**Comment by Hohenbostler** [comment]
Naja aufgefallen ist es mir auf dem 27" Desktopmonitor. Auf dem Handy war alles richtig. 

Und as Homekittile war genau das was ich gesucht habe. Es hat sich im Backend links versteckt angezeigt wurde es rechts. Jetzt passt soweit alles bis auf das sich rechts ein Leeraum eingestellt hat

![grafik](https://user-images.githubusercontent.com/42488069/134288016-b2f38e8b-0cf1-413a-89fb-874e1b7e74f1.png)

**Comment by Zefau** [comment]
In deiner Konfiguration ist rechts aber auch ein Balken

**Comment by Hohenbostler** [comment]
Stimmt gerade gesehen. Wie bekomme ichden weg ?

**Comment by Zefau** [comment]
Die Widgets größer ziehen. Jeweils unten rechts an der Ecke ziehen

**Comment by Zefau** [comment]
Ich mach es nochmal auf als Erinnerung, dass ich eine Warnung einfüge, wenn sich Widgets überlagern.
