### ISSUE TITLE
Add possibility to differentiate Name and Shown Text for Widgets

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1033]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is and how your feature request helps solving it

----- OR -----

**Describe the solution you'd like**
A clear and concise description of what you want to be added.

I try to use the same structure of my widgets in different tabs. In my case I created different rooms which shall all have e.g. "Entertainment", "Klima", Beleuchtung", ... I started to create them for multiple rooms (with different configurations as defined by room) but realized that it is hard to differentiate them. Please provide a given name to a widget which can be different to the shown name. Compare also my screenshot (I just started therefore you see only one conflict)
![image](https://user-images.githubusercontent.com/79741077/134711341-626dd033-bfb9-4fab-9771-412e902552d9.png)

**Comment by RkcCorian** [comment]
Hab mir mal als Workaround eine Tabelle mit den IDs gebastelt um die einzelnen Widgets auseinanderhalten zu können...
![image](https://user-images.githubusercontent.com/79741077/134741994-e3bf9a23-c303-4b1b-a0ac-2e214b94a7be.png)

**Comment by RkcCorian** [comment]
@Zefau: Ich habe nochmal drüber nachgedacht was am Besten wäre. Was will ich erreichen: Sehen welches Widget ich bearbeiten möchte, irgendwo einfügen, aber ggf. auch welches Widget gar nicht mehr verwendet wird. Auch soll das funktionieren, wenn eine Widget an mehreren Stellen verwendet wird. Eine eigene Namensgebung ist da nicht soo hilfreich, da diese keine Mehrfachnutzung widerspiegeln kann und aufgrund manueller Vorgabe nicht immer der Wahrheit entspricht (Menschen machen Fehler). Daher wäre aus meiner Sicht eine Spalte "Where used" o.ä. sinnvoll.

Um mein Problem zu verdeutlichen...
![image](https://user-images.githubusercontent.com/79741077/135706400-92f34f0a-8846-4cbf-8d9c-7330f3eb4d8e.png)

**Comment by Zefau** [comment]
schau mal mit `v3.0.0-alpha.123`

**Comment by RkcCorian** [comment]
Hmmm... die Anzahl hilft mir nicht wirklich... ich möchte wissen "Where used", am besten im Klarnamen. Siehe folgende Konfig... weißt Du wo welches Widget verwendet wird?
![image](https://user-images.githubusercontent.com/79741077/141423105-6e8e1adf-04a4-4444-9b95-234f646a191d.png)

**Comment by Zefau** [comment]
Was meinst du mit wo? Den Tab?

**Comment by RkcCorian** [comment]
Ja genau. Ich habe ein paar Tabs nach Zimmer erstellt. Jedes Zimmer hat bspw. ein Widget Beleuchtung. Wenn ich nun neue Widgets ergänzen will oder Kopiere wird es schwierig die Widgets zu unterscheiden. Wenn ich bspw. wüsste "dieses" Beleuchtungs-Widget wird in dem Tab "Wohnzimmer" verwendet hilft das bei der Bearbeitung. Herausforderung: Ein Widget kann in mehreren Tabs verwendet werden.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.124`.

**Comment by RkcCorian** [comment]
Sehr geil!!! Auch die Direktverlinkung.
Was noch gut wäre, ist wenn Du die ID (wie vorher) drin lässt. Wenn Du nämlich ein Widget anlegst und dort den Namen einträgst kommt Beleuchtung ja auch mehrfach vor. Da habe ich immer von den Widgets direkt die ID kopiert. Daher bitte ID wieder einfügen.
Außerdem gibt es noch ein weiteren Bug. Wenn Du im Layout ein neues Widget anlegst und dort das Widget zuweist und direkt ScaleContentToWidget = false auswählst wird das Widget wieder rausgeworfen und muss ein zweites Mal hinzugefügt werden.

**Comment by mcuiobroker** [comment]
So eine Direktverlinkung wäre natürlich auch für die Geräte interessant.

**Comment by Zefau** [comment]
Für die Geräte dann mit v3.1.x

Die ID findest du als Tooltip im Titel und bei Klick in der Zwischenablage.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1171

**Comment by RkcCorian** [comment]
> Außerdem gibt es noch ein weiteren Bug. Wenn Du im Layout ein neues Widget anlegst und dort das Widget zuweist und direkt ScaleContentToWidget = false auswählst wird das Widget wieder rausgeworfen und muss ein zweites Mal hinzugefügt werden.

Wie möchtest Du diesen Bug verfolgen?

**Comment by RkcCorian** [comment]
> Die ID findest du als Tooltip im Titel und bei Klick in der Zwischenablage.

Sehr gut!!!

**Comment by Zefau** [comment]
> Wenn Du im Layout ein neues Widget anlegst und dort das Widget zuweist und direkt ScaleContentToWidget = false auswählst wird das Widget wieder rausgeworfen und muss ein zweites Mal hinzugefügt werden.

schau bitte nochmal mit `v3.0.0-alpha.125`

**Comment by RkcCorian** [comment]
Passt, kannst schließen :-)
