### ISSUE TITLE
v3: Bei Änderung (PC) werden geöffnete Seiten auf unterschiedlichen Browser nicht aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1036]
Hat man mehrere Seiten von jarvis geöffnet, am Tablet , Handy usw. und man ändert die jarvis-Seite auf dem PC, so wird nur die PC-Jarvis-Seite erneuert. Die anderen Seiten bleiben unverändert.
Bin mir grade nicht sicher, ob es als Feature anzusehen ist? Wenn ja, dann entsprechend ändern.

**Comment by mcuiobroker** [comment]
Gerade festgestellt, die Farbe wird geändert, aber nicht der Effekt. Hatte man vorher keinen Effekt eingetragen und eine Seite auf dem Tablet ist offen mit dieser Einstellung, man ändert jetzt den Effekt auf "blink" auf dem PC, so wird die "PC-Seite" geändert, aber nicht die "Tablet-Seite".

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.108`
Änderung im Layout, werden nur am PC geändert angezeigt, nicht auf dem Handy.
Label geändert
![image](https://user-images.githubusercontent.com/84818934/139556616-f9bc0e8c-3728-4df9-b7bd-d0c7e9c1ed87.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-alpha.112`

**Comment by mcuiobroker** [comment]
Labeländerung im Layout funktioniert.
Neu:
Bei Änderung im Gerät jetzt "Gerätename" wird dieser nicht in allen geöffneten Browsern geändert angezeigt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.113`

**Comment by mcuiobroker** [comment]
Lösche ich ein Element im Layout und speichere es, wird auf dem PC korrekt (gelöscht) angezeigt, auf dem Tablet ist es noch da. Nach Pull-to-refresh ist es weg.
Label-Änderung passt.

**Comment by Zefau** [comment]
> Lösche ich ein Element im Layout und speichere es, wird auf dem PC korrekt (gelöscht) angezeigt, auf dem Tablet ist es noch da. Nach Pull-to-refresh ist es weg.

Was meinst du mit Element? Lösche ich ein Widget im Tab dann funktioniert es bei mir. Auch das Löschen eines Eintrags im Modul StateList wird aktualisiert.

>  Änderung beim Icon in dem Gerät wird nicht an alle übertragen. (Änderung von normalen Icon zu Binding) Hinweis: Zugehörige TAB-Seite von dem Gerät war nicht offen, jarvis schon.

Also die Änderung des Icons ohne Binding funktioniert bei mir, kannst du das bestätigen?

Mit dem Binding und insbesondere dem Seitenwechsel funktioniert bei mir. Kannst du das Beispiel konkretisieren, ggf. per Video?

>  Dabei ist mir aufgefallen, dass das Label aus dem Gerät vorgeschlagen wird, aber nicht editierbar ist? Soll das so?

Ja. Der Vorschlag aus dem Gerät kann überschrieben werden. Sofern nichts eingetragen ist, greift der Eintrag aus dem Gerät.

> Denn, wenn mam mit Bindings arbeitet und diese dann im Layout anpassen möchte, muss man erst ins Gerät es kopieren und dann im Layout anpassen?

Verstehe ich nicht ganz. Wenn du nichts im Layout definierst, dann greift der Eintrag aus dem Gerät. Du musst nichts doppelt pflegen. Wenn das Layout abweichen soll, dann dort pflegen.

**Comment by mcuiobroker** [comment]
Ja , funktioniert alles.
>Denn, wenn man mit Bindings arbeitet

Es geht darum, wenn man im Gerät ein kompliziertes Binding eingetragen hat, dass man dann im Layout dieses Binding nicht bearbeiten kann. Vielleicht aber auch 1 Fall aus 1000, wo man es benötigt.
Ich schließe dann mal. Danke.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.130`
Habe gerade eine Änderung am Layout durchgeführt. Diese wurde aber nicht auf alle Geräte weitergeleitet.
Auf dem PC wird Änderung angezeigt. Auf einem Tablet wird nur der Widget-Rahmen angezeigt, und auf einem anderen Tablet wird gar keine Veränderung angezeigt.
PC
![20211125_195135](https://user-images.githubusercontent.com/84818934/143490657-8f49204f-6ba4-48c4-bb07-cf3163a989ac.jpg)
Tablet A
![20211125_195144](https://user-images.githubusercontent.com/84818934/143490690-842b6721-e46c-4961-a98e-3c5fcda5ecf7.jpg)
Tablet B
![20211125_195140](https://user-images.githubusercontent.com/84818934/143490706-b4d2f675-9fc7-478c-bef0-b0fc691ea1f1.jpg)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.10`

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.15`
Auflistung der Funktionen die getestet wurden:
Geräte-DP-Änderung. Name geändert 
  -> funktioniert, auf dem Tablet wird der Name geändert und anschließend, obwohl unnötig das Icon neugeholt. Dafür wird 
 das "alte" Icon ausgeblendet? und nach ca. 1 Sekunde das "neue" Icon eingeblendet. 
Alle anderen Prüfungen Widget-, Layoutänderungen werden umgesetzt.
Danke.
