### ISSUE TITLE
v3: Charts Rückblickwerte funktionieren nicht richtig

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1037]
3.0.0-alpha.81
In charts habe ich folgenden Fehler:

1.) Rückblickwerte werden bei zu kleinen Werten bei Sekunden,Minuten und Stunden nicht angezeigt.
2.) Der Zoombereich hat ein Versatz von 2 Stunden

Beispiel 1: Rückblickwert 5 Minuten, chart wird nicht angezeigt
![1](https://user-images.githubusercontent.com/77005685/134809525-e8fdd585-0c2a-4126-84f1-4b9ce8323efc.jpg)

Beispiel 2: Rückblickwert 240 Minuten, chart wird jetzt angezeigt.
Zoombereich sollte zwischen ca. 11 und 15 Uhr liegen (4 Stunden), liegt aber zwischen 13 und 15 Uhr
![2](https://user-images.githubusercontent.com/77005685/134809616-56983939-a498-47a6-a49c-2eeccd52b55b.jpg)

**Comment by Zefau** [comment]
Dafür gibt es schon ein Issue: https://github.com/Zefau/ioBroker.jarvis/issues/880
