### ISSUE TITLE
v3: DropDownAction - Display Attribut des Datenpunkts XXX muss definiert werden!

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#1038]
Seit der v3.0.0-alpha.81 funktioniert DropDownAction nicht mehr.

![Bildschirmfoto 2021-09-26 um 15 21 23](https://user-images.githubusercontent.com/48379591/134810007-d83fd25d-e091-4f6b-a05e-d57b20ade265.jpg)

Hier die Einstellungen:

![Bildschirmfoto 2021-09-26 um 15 20 41](https://user-images.githubusercontent.com/48379591/134810018-26c62cf3-9b51-4129-afd6-9a3b626618cb.jpg)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.82` wieder passen

**Comment by bogaboo** [comment]
ja, mit der v3.0.0-alpha.82 funktioniert es wieder...
