### ISSUE TITLE
v3: null-Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1041]
`v3.0.0-alpha.83`

![image](https://user-images.githubusercontent.com/84818934/134825078-9bb7b3d3-1f9f-4047-84c8-509906fa8b6e.png)

![image](https://user-images.githubusercontent.com/84818934/134825106-cb60792d-8fcd-4392-94f1-9ec481e20e7c.png)

**Comment by RkcCorian** [comment]
Wann tritt der Fehler auf? Sobald man auf alpha-83 aktualisiert und dann beim JARIVS Start?! Blocker, sprich auf alpha-84 warten?

**Comment by mcuiobroker** [comment]
Ja. Sind noch andere Kleinigkeiten. Zefau ist schon dran.

**Comment by RkcCorian** [comment]
Danke, dann warte ich nochmal

**Comment by Zefau** [comment]
hopefully resolved with `v3.0.0-alpha.84`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/134988994-ceb088c4-2b86-442c-850c-6360ec4b777b.png)

**Comment by Zefau** [comment]
Hast du im LastBodyChange ein falsches Zeitformat drin?

**Comment by mcuiobroker** [comment]
Ja das blieb noch vom Test übrig. Stand `formatDistrictNow` drin. Letzter Fehler ist jetzt weg. `null` bleibt aber.

**Comment by mcuiobroker** [comment]
Mehr Details

![image](https://user-images.githubusercontent.com/84818934/134989936-e79fb101-20b6-469a-8895-532cc2c45fa6.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/135068253-4f965bd4-24c9-4339-8d85-f024473806f7.png)

**Comment by mcuiobroker** [comment]
Bin jetzt mal auf PROD. Dort gibt es nur noch ein "null". Also hängt es evtl mit nicht vorhandenen IDs zusammen. Kann man da nicht die ID anzeigen, die er sucht?

**Comment by mcuiobroker** [comment]
Ich hab jetzt mal ein Programm geschrieben, wo die IDs ermittelt werden, die nicht in ioBroker vorhanden sind. Habe diese gelöscht und keine "null" Anzeige mehr.
Vielleicht kannst ein existsState für die states mit einbauen und prüfen, ob die ID auch wirklich vorhanden ist. Und demtsprechend diese einmal im Log ausgeben und aber auch in der Geräteiste rot markierst.

**Comment by RkcCorian** [comment]
Eine Meldung/Suche in den Einstellungen fände ich besser, da ansonsten an allen Geräten ggf. eine Fehlermeldung  kommt / es lange dauert.
Aus techn. Interesse: Um welche IDs geht es? Datenpunkte?

**Comment by mcuiobroker** [comment]
Ja die DPs, die in den Geräten definiert wurden. Wenn diese nicht mehr da sind, kommt es zu Problemen.

**Comment by RkcCorian** [comment]
Tja, ... ich habe dann wohl leider solche Datenpunkte. JARVIS lädt auf meinem Testsystem nicht. Ohne Behebung dieses Fehlers kann ich aktuell leider nicht weiter testen :-|

**Comment by RkcCorian** [comment]
@mcuiobroker: Wie konntest Du die nicht vorhandenen DPs rausfinden?
@Zefau: Finde das aktuelle Verhalten kritisch. Wenn ich es richtig verstehe startet JARVIS nicht mehr, wenn ich bspw. einen DP umbenenne oder lösche. Wenn ich das rausfinde wäre es dann bereits zu spät und ich kann es nicht mehr korrigieren?!

**Comment by mcuiobroker** [comment]
Stelle das Programm am Abend im Forum zur Verfügung.

**Comment by RkcCorian** [comment]
Top

**Comment by mcuiobroker** [comment]
Programm zur Prüfung der States: https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/5209

**Comment by RkcCorian** [comment]
Vielen Dank! Hab tatsächlich 2 DPs gehabt, welche ich aufgeräumt habe. Leider bekomme ich immer noch Fehler...
![image](https://user-images.githubusercontent.com/79741077/135676973-4e3a82ff-1dae-41e9-a7f5-48d85d2e4523.png)

Im Log sieht es nicht schlimm aus...
![image](https://user-images.githubusercontent.com/79741077/135677019-6816edeb-91e3-4f48-ba88-238b396b925b.png)

Leider kann ich so nicht weitertesten 😥

**Comment by Zefau** [comment]
Was steht in `jarvis.0.notifications` bei dir drin? Kannst du das mal validieren, ob das valides JSON ist? Via https://jsonformatter.curiousconcept.com/

**Comment by Zefau** [comment]
In deinem Screenshot steht noch alpha-80. Lösch mal den Cache.

**Comment by RkcCorian** [comment]
Habe bislang nie Notifications benutzt (steht noch auf der Liste). Daher ist es leer.
![image](https://user-images.githubusercontent.com/79741077/135678643-57644bb1-462b-4dd3-a13d-84e62260dfa8.png)

**Comment by Zefau** [comment]
Ok, leer ist ok. Hast du aktualisiert und Cache geleert?

**Comment by RkcCorian** [comment]
Hab schon Backup eingespielt. Ich probiere es nochmal. Cache ist vermutlich Browser-Cache?!

**Comment by Zefau** [comment]
Jo

**Comment by RkcCorian** [comment]
Neustart vom Container hat die Lösung gebracht 🙃

**Comment by RkcCorian** [comment]
@Zefau : Wie verhält es sich, wenn ich einen DP umbenenne oder lösche. Wenn ich diesen dann noch mit altem Namen in JARVIS habe... startet JARVIS, sodass ich den Fehler beheben kann? Wenn nein würde ich diesen Issue nicht schließen (wollen)

**Comment by Zefau** [comment]
Umbenennen / Löschen hat keine Auswirkungen auf jarvis.

**Comment by RkcCorian** [comment]
Ok. D.h. bei mir war nur der Neustart des Containers ausschlaggebend. Das ich 2 DPs in JARIVS hatte die es nicht mehr gar hat keinen null-Fehler hervorgerufen?!
