### ISSUE TITLE
v3: Notification Bilder werden direkt in der Übersicht angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1043]
Schickt man Bilder als Notification, sow erden die Bilder nicht nur als Popup angezeigt, sondern auch direkt in der rechten Übersicht der Notifications. D.h. man sieht nur die letzten 2-3 Bilder in der rechten Spalte? Soll das so?
Dort sollte es es doch nur eine Übersicht der Überschriften zu den Notifications geben? Dann kann man dort drauf klicken und die Notification wird wieder angezeigt.

**Comment by Zefau** [comment]
Es gibt eine Überschrift mit kurzer Nachrichtenvorschau. Wenn in der Vorschau HTML ist, wird dieses angezeigt. Bei dir wohl ein Bild, dass dann zu viel Platz nimmt?

Kannst du das mal screenshoten?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/134858656-f86418a7-ffc9-48c7-938a-fc720121cc46.png)
Obwohl ich width=100% angebe wird die Karte nicht komplett angezeigt?
`jarvisNotify.message= '<iFrame src="http://192.168.178.89/download/Weltkarte.jpg" height="auto" width="100%"></iFrame>';`

**Comment by Zefau** [comment]
Ist ein iFrame. Nach man `<img .. />`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/134860693-6dd6e5d2-908d-4a18-b8d8-ad26fccb0b64.png)
Klappt. Ich dachte man könnte auch img mit iFrame schicken?

**Comment by Zefau** [comment]
iFrame ist eigentlich immer für komplette externe Seiten gedacht. Ich nutze es in jarvis als Workaround auch zT anders, aber ist so eigentlich nicht gedacht.

**Comment by Zefau** [comment]
kann das Issue dann zu?

**Comment by mcuiobroker** [comment]
Ja.

**Comment by mcuiobroker** [comment]
Wäre es nicht sinnvoll in der rechten Seite die Anzeige kleiner zu gestalten?

**Comment by Zefau** [comment]
Was genau? Die einzelnen Zeilen?

**Comment by mcuiobroker** [comment]
Ja genau. Das man dort die Höhe begrenzt?

**Comment by mcuiobroker** [comment]
Wenn möglich bitte die Überschrift drüber:
![image](https://user-images.githubusercontent.com/84818934/134990417-a8c2952f-cf4b-49b3-879b-61a87a2cd5a4.png)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.85`

**Comment by mcuiobroker** [comment]
jarvisNotify.title = "Wichtige Meldung";
Überschrift fehlt noch, sonst super.
![image](https://user-images.githubusercontent.com/84818934/135696859-017534fa-5842-4a29-83f7-fe23a895d69b.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/135738918-0e919168-1639-4f0c-a542-09ea44c2ffec.png)
Kleinigkeit ist nocht der Scrollbalken rechts ist überflüssig. Hat aber keine Prio.
