### ISSUE TITLE
v3: Binding reagiert nicht sofort, bzw. Änderung in ioBroker werden nicht in jarvis umgesetzt. Erst nach F5 erscheint der korrekte Wert.

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1046]
- [ ] Binding reagiert nicht sofort, bzw. Änderung in ioBroker werden nicht in jarvis umgesetzt. Erst nach F5 erscheint der korrekte Wert.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1003#issuecomment-927338851_

**Comment by Zefau** [comment]
Kann ich so nicht bestätigen. Funktioniert bei mir tadellos und auch unmittelbar.

Wie sieht dein Binding aus? Hängt es mit https://github.com/Zefau/ioBroker.jarvis/issues/1041 zusammen?
Wenn du das Binding testweise entfernst, kommt der `null` Fehler dann noch immer?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/135181766-c3d0703e-8094-48fe-8307-e894ca4ad35e.png)


![v3-84-Binding nicht aktuell](https://user-images.githubusercontent.com/84818934/135181737-dae6a2bd-2786-40e7-ac18-39d1b7d9ab28.gif)

**Comment by Zefau** [comment]
Ah ok. Dann liegt es wohl am Stil. Mit Icon geht es bei mir. Ich schaue heute Abend mal

**Comment by mcuiobroker** [comment]
Auch Icon funktioniert bei mir nicht. Ist dasgleiche Verhalten. 
Icon-Feld:
`{"{0_userdata.0.Zahl_SONOS}=0":"home","{0_userdata.0.Zahl_SONOS}=1":"home-account"}`
Warum kommt plötzlich der `map-marker` 
![v3-84-Binding falsche Icon](https://user-images.githubusercontent.com/84818934/135213205-c7f45f16-cfeb-41ff-a65d-2d76a6822afe.gif)

**Comment by Zefau** [comment]
Map marker ist der default für das Gewerk nehme ich an. Solange der Wert nicht geladen ist erscheint der.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/135218549-6493e1a7-aa15-456a-bc5b-7be7fe197b6f.png)

**Comment by Zefau** [comment]
Hö? OK, stimmt scheinbar einiges nicht. :-/

**Comment by mcuiobroker** [comment]
Bindings werden auf der ersten Seite auch erst dann verarbeitet, nachdem die komplette Seite mit allen TABs geladen wurde, anstatt die erste Seite erst komplett zu laden?

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.85`

**Comment by mcuiobroker** [comment]
Binding zieht jetzt gar nicht mehr.
![image](https://user-images.githubusercontent.com/84818934/135697192-0adbf828-bbcd-4fc9-8b29-28987ac16000.png)
![image](https://user-images.githubusercontent.com/84818934/135697211-65f45fd0-a16b-4805-b088-dd7e5cddd546.png)
![image](https://user-images.githubusercontent.com/84818934/135697220-5f6d964e-ab8f-4979-ac30-f74b221f3912.png)
![image](https://user-images.githubusercontent.com/84818934/135697253-271f6360-e160-499c-ac49-9bd80f56cf8e.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
Er setzt das Binding jetzt direk um, aber wenn der Binding-Wert nicht stimm nimmt er Normal-Zustand (ohne Background-color) nicht wieder an. er bleibt Zustand, der mit dem Binding eeingestellt wurde.
In meinem Fall bleibt er im Hintergrund gelb. Erst nach F5 ist auch der Background wieder normal.

**Comment by Zefau** [comment]
Dasselbe Verhalten bei Bindings mit icons?

**Comment by mcuiobroker** [comment]
Nein. Nur die Icons-Stil Einstellungen werden, bei den DPs mit Bindings in einem anderen Parameter anscheinend nicht umgesetzt.
Bei mir. Binding im Body-Stil und Icon-Stil abhängig nur vom Statewert. Der Icon Stil wird dort unabhängig vom Binding selbst, nicht umgesetzt.

**Comment by Zefau** [comment]
> Er setzt das Binding jetzt direk um, aber wenn der Binding-Wert nicht stimm nimmt er Normal-Zustand (ohne Background-color) nicht wieder an. er bleibt Zustand, der mit dem Binding eeingestellt wurde.

Sollte mit `v3.0.0-alpha.87` wieder passen.

> Binding im Body-Stil und Icon-Stil abhängig nur vom Statewert. Der Icon Stil wird dort unabhängig vom Binding selbst, nicht umgesetzt.

Hast du ein Beispiel ?

**Comment by mcuiobroker** [comment]
>Hast du ein Beispiel ?

Hatte sich erledigt, es war ein falsche Eintrag im Icon-Stil.

Der einzige Punkt der hier noch offen ist:
Ist ein Binding im Icon, so wird das Icon erst nach 5 Sekunden korrekt umgesetzt. Das sieht nicht so schön aus.
ImVideo oben "Zuhause", dort ist im Icon ein Binding. 
`{"{0_userdata.0.Zahl_SONOS}=0":"home","{0_userdata.0.Zahl_SONOS}=1":"home-account"}`
![v3-alpha-87-HandyansichtzuHauseIcon](https://user-images.githubusercontent.com/84818934/135784385-0b8e4801-e23f-4848-940b-f0c6eac2868c.gif)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1090
