### ISSUE TITLE
v3: Zahl schalten funktioniert nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1047]
- [x] Zahl schalten funktioniert nicht mehr
![image](https://user-images.githubusercontent.com/84818934/134805180-55024fe8-b568-405e-b94c-147677dc6933.png)

Der SwitchButton wird nicht umgesetzt nach dem Schalten. Er bleibt in der Position stehen. Die Zahl wird korrekt eingetragen. Nach F5 Reload ist der Button wieder an der richtigen Stelle.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1003#issuecomment-927286195_

**Comment by Zefau** [comment]
Das funktioniert bei mir (leider) auch tadellos. In der Browser-Konsole steht nichts?

Gerät:
![image](https://user-images.githubusercontent.com/14368811/135154810-bd347fcf-4123-4c8c-9965-c7842bf61657.png)

Schalten
![Schalten](https://user-images.githubusercontent.com/14368811/135155554-3c79e00b-9982-460c-a428-c63affbffd6f.gif)
:

**Comment by mcuiobroker** [comment]
Bei mir ist ein state-Wert
![image](https://user-images.githubusercontent.com/84818934/135160879-3ca87bb4-4cce-4c11-a629-ea0de728db63.png)
Unabhängig davon, ich hatte es auch auf "vaule" geändert. Es funktioniert nicht.
Ich habe alle Browser (Chrome,Firefox,Edge) getestet. Die SwitchButton-Action wird nicht durchgeführt. Der Wert wird geschaltet, nur der Button nicht.

**Comment by mcuiobroker** [comment]
![v3-84-ToggleButtonAction funktioniert nicht](https://user-images.githubusercontent.com/84818934/135164956-f2c6d76b-30c0-4e87-8130-f21f526dfa87.gif)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1058

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
Funktioniert.
