### ISSUE TITLE
v3: Icons werden nicht korrekt dargestellt, Farben passen nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1048]
Die Icons werden nicht korrekt dargestellt. sieh auch #1003 .
Und es werden Iconfarben in Bezug auf Icon-Style nicht korrekt dargestellt.

**Comment by Zefau** [comment]
Die icons selbst passen aber? Nur die Styles sind inkorrekt?

**Comment by mcuiobroker** [comment]
Nein. Auch die Icons werden teilweise falsch dargestellt. Also die, die angegeben sind im Gerät, werden nicht gezogen, sondern das "letzte" was verwendet wurde, mein Eindruck?

**Comment by Zefau** [comment]
Reihenfolge nach der die Icons gezogen werden (ab `v3.0.0-alpha.86` dann auch korrekt dargestellt):

1. Datenpunkt (durch Benutzer definiert)
2. Gerät (durch Benutzer definiert)
3. Datenpunkt (Standard)
4. Gewerk (Standard)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
Die Reihenfolge wird nicht eingehalten:
![image](https://user-images.githubusercontent.com/84818934/135739884-7d6fbb22-8ca1-42dc-9c9d-53c46090ba8c.png)
Vermute da der DP-Inhalt als nicht richtig erkannt wurde wird auch das Icon nicht dargestellt?
Da sollte dann aber ein "Stop"-Schild erscheinen? z.B.: openmoji:stop-sign. Dann erkennt der User sofort, hier muss ich was tun.

**Comment by mcuiobroker** [comment]
Bei dem letzten Punkt war die Farbzuordnung falsch
![image](https://user-images.githubusercontent.com/84818934/135763974-03b8c208-c4a1-4afd-862f-b44a6b687041.png)
Man muss `{"true":{"color":"yellow"}}` eintragen. Dann funktioniert es.

**Comment by Zefau** [comment]
> Vermute da der DP-Inhalt als nicht richtig erkannt wurde wird auch das Icon nicht dargestellt?

Dein Beispiel funktioniert bei mir. Inwiefern wurde der DP-Inhalt als nicht richtig erkannt?

Kannst du es nochmal bei einem anderen DP probieren?

> Da sollte dann aber ein "Stop"-Schild erscheinen? z.B.: openmoji:stop-sign. Dann erkennt der User sofort, hier muss ich was tun.

Wo soll ein Stop-Schild erscheinen und weshalb?

Im Backend werden keine DP-Werte vorgehalten, falls du darauf Bezug nimmst.

**Comment by mcuiobroker** [comment]
Es geht darum, der Trash-DP ist im Test-System nicht vorhanden. Der Wert bzw die Anzeige ist aber im Layout definiert. Also ist es momentan so, dass er das  Icon vom Trash nicht anzeigt, sondern auf dem Icon-Platz den blauen Kreis dreht.
Das Icon ist aber definiert und könnte angezeigt werden.
Ist der drehende Kreis weg bzw fertig nach 1 Minute, dann erscheint kein Icon, obwohl definiert und anzeigbar.
Deswegen war mein Gedanke, dass man bei solchen DPs im Layout, deren DP nicht vorhanden ist im ioBroker, ein Stop-Schild anzeigt und keinen drehenden Kreis, der nach 1 Minute verschwindet.
Sonst würde ich denken, das Icon kann nicht geladen werden. Beim einem Stop-Schild würde mir das Problem auffallen?
Denn mal sieht es so aus:
![image](https://user-images.githubusercontent.com/84818934/135785785-ff90bc67-810c-4717-8330-7e56b0e857b3.png)
Jetzt sollte hier das Billd mit dem drehenden Kreis rein, der wird aber momentan nicht mehr angezeigt.

**Comment by Zefau** [comment]
#1091
