### ISSUE TITLE
v3: Widget-ID in die Widget-Box

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1051]
![image](https://user-images.githubusercontent.com/84818934/135002770-5886f366-ee87-4d76-9601-b5be8b76db5b.png)
Bei eingetragenen Widget sollte die zugehöirge Widget-ID oben neben Widget angezeigt werden, dann kann sie direkt ablesen und für CSS verwenden. Sonst muss immer in die Widgets gehen und sich die Nummer raussuchen.

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.85`

**Comment by mcuiobroker** [comment]
Passt. Danke.
