### ISSUE TITLE
v3: Direkt nach Konvertierung v2.2.3->v3 Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1055]
Direkt nach einer Konvertierung von v2.2.3 nach v3 wird jedsmal bei Reload der Fehler angezeigt:
![image](https://user-images.githubusercontent.com/84818934/135064468-1aec9289-8ccd-48ee-89a1-6c9a28e2943f.png)

![image](https://user-images.githubusercontent.com/84818934/135064867-b1ff2937-a1dc-4bc3-aa81-5d6952a2c79b.png)

**Comment by Zefau** [comment]
Dafür gab es schon ein Issue https://github.com/Zefau/ioBroker.jarvis/issues/989

**Comment by Zefau** [comment]
Sieht aber korrekt aus laut Screenshot. Er schafft die Verbindung erst nicht und beim dritten Anlauf war es dann erfolgreich. 

Also insgesamt OK. Wie wäre deine Erwartungshaltung?

**Comment by mcuiobroker** [comment]
Vorher gab es die Fehler nicht. Da hat die Verbindung direkt geschafft? Also ist irgendwo ein timeout anders?

**Comment by Zefau** [comment]
Ich schau nochmal heute Abend. Er benutzt erst einen falschen Port.
