### ISSUE TITLE
v3: ButtonAction Einstellungen werden nicht gespeichert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1056]
![image](https://user-images.githubusercontent.com/84818934/135159386-e837c5fc-e0b4-45cb-ba8c-65a6f2a95b2a.png)
Speichert man es, wird es nicht umgesetzt.

**Comment by Zefau** [comment]
Was meinst du konkret mit `nicht umgesetzt` ? Also wenn du wieder in den Dialog gehst, steht der alte Wert und nicht der eigentlich ausgewählte da? Oder der neue Wert steht drin, wird aber in jarvis nicht genutzt (nach einem Reload?) ?

**Comment by mcuiobroker** [comment]
![v3-84-ButtonAction nicht gespeichert](https://user-images.githubusercontent.com/84818934/135163204-8aed1f08-728f-49ee-aca5-9a5f6ee474f2.gif)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
Zustand wird jetz gespeichert. Aber es ist noch ein anderes Problem, wenn man Dtanepunkt-Wert anzeigen auf true setzt:

![image](https://user-images.githubusercontent.com/84818934/135740386-624000a4-65bc-4f8e-a1aa-aef1684ced67.png)

Video

![v3-alpha-86-ButtonActionImPopupanders](https://user-images.githubusercontent.com/84818934/135740462-dadd7e1a-f075-4587-b5f7-a767575858ad.gif)

**Comment by Zefau** [comment]
Musst schon schreiben was das Problem ist ;-)

Dass er den Wert toggled ist korrekt und gewollt.

War mal ein Feature Request. Kann dafür aber auch eine Option einbauen.

Oder meinst du etwas anderes?

**Comment by mcuiobroker** [comment]
Datenpunkt-Wert anzeigen auf true führt zu dem komischen Effekt: Im Popup kann man schalten, im Widget nicht.

**Comment by Zefau** [comment]
Hast du denn sowohl im Popup als auch im Layout auf aktiviert?

**Comment by mcuiobroker** [comment]
Nur im Layout. Also im Gerät nicht. Popup?

**Comment by Zefau** [comment]
Ja, Gerät meine ich mit Pop-up .

> Wenn ich Datenpunkt-Wert anzeigen einschalte, ist der IconButton weg im Widget, siehe Video.

Das ist korrekt. Dafür ist die Einstellung in den Komponenten vorgesehen.

> Nur im Popup ist er dann noch da, aber dort wird kein Datenpunkt-Wert angezeigt. 

Dafür musst du es im Gerät aktivieren. Popup = Gerät.

**Comment by mcuiobroker** [comment]
>Das ist korrekt. Dafür ist die Einstellung in den Komponenten vorgesehen.

Ja aber wie man im Video erkennt, bei `true` wird der Datenpunkt-Wert angezeigt, bei `false`, ist der Button wieder da.

**Comment by Zefau** [comment]
Kannst du mal die Konfiguration von dem Gerät und vom Widget posten? Entweder ist ein Fehler oder wir reden aneinander vorbei ;-)

**Comment by mcuiobroker** [comment]
Datenpunt Gerät:
![image](https://user-images.githubusercontent.com/84818934/135964227-d6f5f15b-f2b1-496b-8136-49726f4ffd0b.png)
![image](https://user-images.githubusercontent.com/84818934/135964258-ab044b58-3991-40cd-b8f3-67e154e310f5.png)
![image](https://user-images.githubusercontent.com/84818934/135964316-522e8eb5-720f-49d0-a62a-902f53f7c35b.png)
![image](https://user-images.githubusercontent.com/84818934/135964354-9748193f-615d-4016-92ea-52c232fd7423.png)
Ansicht, ich seh den Zustand, kann nicht schalten!
![image](https://user-images.githubusercontent.com/84818934/135964420-1ec1ccee-4042-4100-88db-63b7affaebf6.png)
Klicke auf die Zeile, sehe Popup, dort kann ich schalten, sehe aber keine Zustand:
![image](https://user-images.githubusercontent.com/84818934/135964485-06725d87-776c-4276-9e26-66aea1d5f7c6.png)

Müsste ich nicht auch in der Ansicht schalten können? Wofür brauch ich sonst die IconButtonAction?

**Comment by Zefau** [comment]
Sieht alles richtig aus.

`Datenpunkt-Wert anzeigen` auf `true` bedeutet, dass der Button bewusst verschwindet und nur der Wert angezeigt wird. Die Einstellung hast du im Layout aktiviert, aber nicht im Gerät. Da es im Gerät nicht aktiviert ist, wird der Button weiterhin angezeigt. 

Steht auch in der Info:
> Zeigt Datenpunkt Wert (wenn true) oder den Button (wenn Wert false)

Wenn du die Einstellung angleichst, wird es sich auch gleich verhalten.

Wenn du sowohl Wert als auch Button gleichzeitig zeigen willst, dann musst du die Option in den `Component Options` deaktivieren und die Option außerhalb der Component Options (direkt im Layout bzw. Gerät) aktivieren.

**Comment by mcuiobroker** [comment]
Ja schön, aber dann bitte verschwinden bei True und bei false. Denn bei false wird der Button angezeigt.

**Comment by Zefau** [comment]
Ist doch aber so gewollt oder reden wir aneinander vorbei?

Wie die Info sagt
> Zeigt Datenpunkt Wert (wenn true) oder den Button (wenn Wert false)

**Comment by mcuiobroker** [comment]
Zeigt Datenpunkt Wert (wenn der Schalter auf true steht ) oder den Button ( wenn der Schalter auf false steht). 
Steht der Datenpunkt Wert auf TRUE, dann soll er beim Statewert "true" den Wert an anzeigen, ist der Statewert "false" soll er aus anzeigen. Er zeigt aber dann den Button.
Sieht man im Video oben (mitte rechts). Wenn man den Datenpunkt-Wert anzeigen angeklickt hat, dann soll er für alle Statewerte den Datenpunkt-Wert anzeigen.
