### ISSUE TITLE
v3: Sortierung bei jsonTable funktioniert nicht mit float-Werten

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1057]
![image](https://user-images.githubusercontent.com/84818934/135182182-31961dc3-88fb-4c88-896c-9b3ec64c4914.png)

Es tritt auf beim Versuch die Tempaturen zu sortieren:
![image](https://user-images.githubusercontent.com/84818934/135182254-b8689333-1838-4077-b6e7-8fb96489efe1.png)
Die Werte kommen vom hue-extended-Adapter.
Und dann dauert es auch ca 1 Minute bis man die anderen Werte wieder sortieren kann.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
Passt.
