### ISSUE TITLE
v3: SwitchAction funktioniert nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1058]
![image](https://user-images.githubusercontent.com/84818934/135185685-aa010d03-3f22-4bde-8805-4f33a8def312.png)

![v3-84-Schalter normal funktioniert nicht nur im Popup](https://user-images.githubusercontent.com/84818934/135185405-1886de7e-4516-46eb-bc29-2870747f781f.gif)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
Funktioniert.
