### ISSUE TITLE
v3: F9 - Sprung ins Layout direkt zur aktuellen Seite 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1059]
Bislang kommt man mit F9 direkt ins Layout. Besser wäre es, wenn man direkt auf das TAB springt, welches in der Seite geöffnet war.
Da man ja deswegen ins Layout springt, um diese Seite zu verändern. (Meistens)

**Comment by Zefau** [comment]
Das ist inzwischen in v3.1 realisiert

**Comment by mcuiobroker** [comment]
Nur teilweise.
Es funktioniert mit F2 auf der ersten Seite. Aber nicht bei anderen Seiten.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.57`

**Comment by mcuiobroker** [comment]
Passt. Danke.
