### ISSUE TITLE
Layout may overlap on small devices

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#106]
https://forum.iobroker.net/post/492561

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/500509

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/500567

**Comment by cryptedx** [comment]
Hier noch ein paar weitere Beispiele unter MacOS mit Chrome:

![image](https://user-images.githubusercontent.com/20707078/96293382-f14c3780-0fea-11eb-8282-0dafce5fb6fc.png)

![image](https://user-images.githubusercontent.com/20707078/96293411-fd37f980-0fea-11eb-8c67-b842c409f367.png)

![image](https://user-images.githubusercontent.com/20707078/96293428-045f0780-0feb-11eb-84c9-73590c64c559.png)

**Comment by Zefau** [comment]
@cryptedx Prüf mal bitte `v1.1.0-beta.114? , ob es damit besser geworden ist.

**Comment by cryptedx** [comment]
Here it looks fine:

![image](https://user-images.githubusercontent.com/20707078/99779779-d737d480-2b15-11eb-86bb-b0fef0c6c2b9.png)

**Comment by Zefau** [comment]
Looks a bit squeezed though

**Comment by cryptedx** [comment]
I have seen that I have posted the wrong screenshot. Here is the right one with the actual situation:

![image](https://user-images.githubusercontent.com/20707078/99824510-16861580-2b56-11eb-8aa2-0f5930d97195.png)

**Comment by Zefau** [comment]
Looks better :-)
