### ISSUE TITLE
v3: jsonTable Label anpassen funktioniert nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1060]
`[{"field":"deviceid","name":"ID","style":{"width":"50px"}}]` ist eingetragen. Eigentlich sollte der Name sich jetzt ändern:

![image](https://user-images.githubusercontent.com/84818934/135237814-35cbd718-e8f7-40c3-8094-01dacf622531.png)

Musste "label" nutzen.

- [x] Trotzdem wird der Style nicht umgesetzt.

- [x] Die Überschrift bleibt auch nicht oben stehen, wenn man runterscrollt. So verliert man die Zusammenhang zwischen Wert und Spaltenüberschrift.

**Comment by Zefau** [comment]
kannst das zugehörige JSON posten? Oder zumindest einen Eintrag davon?

**Comment by Zefau** [comment]
`name` hat keine Auswirkungen. `label` definiert den Spaltentitel. Das ist also so korrekt.

Die Spalteneinstellungen greifen grundsätzlich nur, wenn das JSON Einträge hat.

Mit der `v3.0.0-alpha.86` wird die Titelzeile daher ausgeblendet, wenn keine Einträge vorhanden sind.

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.86`

**Comment by mcuiobroker** [comment]
Titelzeile bleibt jetzt beim Runterscrollen stehen. Super. Am Style hattest du nichts gemacht? Ich hab jetzt nicht getestet.

**Comment by Zefau** [comment]
Dafür bräuchte ich das JSON ist zumindest einen Eintrag davon.

**Comment by mcuiobroker** [comment]
Spaltenoption für die nachfolgende JSON:
`[{"field":"Nr","label":"Nummer","style":{"width":"50px"}},{"field":"ZEIT","label":"Zeit","style":{"width":"50px"}},{"field":"KANAL","label":"Kanal","style":{"width":"50px"}},{"field":"TITEL","label":"Titel","style":{"width":"50px"}}]`

`[{"Nr":"1","ZEIT":"09:55","KANAL":"ard","TITEL":"Tagesschau"},{"Nr":"2","ZEIT":"10:00","KANAL":"welt","TITEL":"Nachrichten"},{"Nr":"3","ZEIT":"10:15","KANAL":"ntv","TITEL":"Nachrichten"},{"Nr":"4","ZEIT":"10:30","KANAL":"welt","TITEL":"Nachrichten"},{"Nr":"5","ZEIT":"11:00","KANAL":"ard","TITEL":"Tagesschau"},{"Nr":"6","ZEIT":"11:00","KANAL":"ntv","TITEL":"Nachrichten"}]`

Ergebnis ungleiche Breite der Spalten:
![image](https://user-images.githubusercontent.com/84818934/135745311-22af0edf-33c4-45ce-9813-f73cd4108131.png)

**Comment by Zefau** [comment]
Style sollte mit `v3.0.0-alpha.87` wieder passen

**Comment by mcuiobroker** [comment]
Es hat sich nichts geändert. Die Spalte sind weiterhin so wie oben im Bild.

**Comment by Zefau** [comment]
Habe vergessen zu sagen, dass `style` kein Objekt ist sondern ein String: `"style":{"width:50px"}`

**Comment by mcuiobroker** [comment]
Sind auch dann unterschiedlich breit:
`[
  {
    "field": "Nr",
    "label": "Nummer",
    "style": "width:50px"
  },
  {
    "field": "ZEIT",
    "label": "Zeit",
    "style": "width:50px"
  },
  {
    "field": "KANAL",
    "label": "Kanal",
    "style": "width:50px"
  },
  {
    "field": "TITEL",
    "label": "Titel",
    "style": "width:50px"
  }
]`

![image](https://user-images.githubusercontent.com/84818934/135802616-256cf636-7339-4e35-a896-8a5b4b56d158.png)

**Comment by Zefau** [comment]
Nimm mal bitte zum Test bei einer Spalte raus. Die Tabelle wird ja auf 100% gezogen, daher geht es wahrscheinlich nicht für alle Spalten.

**Comment by mcuiobroker** [comment]
Ja. Da ist gut.

![image](https://user-images.githubusercontent.com/84818934/135837658-9031b069-062e-4546-a054-7415075007d0.png)
