### ISSUE TITLE
v3: Secondary state not visible

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1065]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

alpha-80

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

When I configure a "secondaryStatesKeys" "LEVEL" right after configuration it is visible but get's lost after browser refresh. The problem for you might be that this is not allways the case. Several configured "secondaryStatesKeys" are normally visible but a few not.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

Config for a working "secondaryStatesKeys" "LEVEL"
```
  "86a03f9c-8a64-4da3-8b21-1c7ba3d23b88": {
    "id": "86a03f9c-8a64-4da3-8b21-1c7ba3d23b88",
    "config": {
      "dense": false
    },
    "icon": "home-thermometer",
    "title": "Klima",
    "module": "StateList",
    "items": [
      {
        "type": "device",
        "deviceId": "wohnzimmerthermostat_cbfe1",
        "secondaryStatesKeys": [
          "OPERATION_MODE",
          "HUMIDITY_REL"
        ],
        "primaryStateKey": "TEMPERATURE_ACTUAL",
        "bodyElement": null,
        "bodyStateKey": null,
        "showState": true,
        "actionElement": null,
        "id": "6e29f01e-b4c0-4fdb-9f84-96913f2def3d"
      },
      {
        "type": "device",
        "deviceId": "wohnzimmerluftbefeuchter_bfa1b",
        "primaryStateKey": "HUMIDIFICATION",
        "secondaryStatesKeys": [],
        "bodyElement": null,
        "bodyStateKey": null,
        "showState": true,
        "actionElement": null,
        "id": "642e5faa-aa18-42c4-8ed8-0d9f1ff09f33"
      },
      {
        "type": "divider",
        "id": "f9cab539-22d4-4594-8b34-1eb16ccd8e9a"
      },
      {
        "type": "device",
        "deviceId": "balkonrollladenlinks_281b0",
        "primaryStateKey": "STATUS",
        "actionType": "state",
        "actionElement": null,
        "bodyStateKey": "",
        "bodyElement": null,
        "showState": true,
        "id": "8b05fd5b-f00c-463d-9bec-56ff48d31386",
        "secondaryStatesKeys": [
          "LEVEL"
        ]
      },
      {
        "type": "device",
        "deviceId": "balkonrollladenrechts_d6d1c",
        "primaryStateKey": "STATUS",
        "bodyElement": null,
        "bodyStateKey": "",
        "showState": true,
        "actionElement": null,
        "id": "e9534c1a-8351-4d8e-b06d-9ee8285b2ed9",
        "secondaryStatesKeys": [
          "LEVEL"
        ]
      },
      {
        "type": "device",
        "deviceId": "schrankwandrollladen_1c75d",
        "primaryStateKey": "STATUS",
        "bodyElement": "LastChangeBody",
        "bodyStateKey": "",
        "showState": true,
        "actionElement": null,
        "id": "ae860e5d-c63a-4b48-98e5-7ebfe8bd5b48",
        "secondaryStatesKeys": [
          "LEVEL"
        ]
      }
    ],
    "hideTitle": false,
    "link": "f0c1c414-de3c-42b1-a5ba-5ac9dd91a5b9"
  },
```
Screenshot
![image](https://user-images.githubusercontent.com/79741077/135479485-9596d4c7-5028-4628-8dfc-692ab193f7fc.png)

Config for a non working "secondaryStatesKeys" "LEVEL"
```
  "75142168-f81b-465a-9021-22fe9c3c3029": {
    "id": "75142168-f81b-465a-9021-22fe9c3c3029",
    "config": {},
    "icon": "home-thermometer",
    "title": "Klima",
    "module": "StateList",
    "items": [
      {
        "type": "device",
        "deviceId": "küchenrollladen_96d80",
        "primaryStateKey": "STATUS",
        "bodyElement": null,
        "bodyStateKey": null,
        "showState": true,
        "actionElement": null,
        "id": "179b4f12-66c7-4ce3-9512-407552776615",
        "secondaryStatesKeys": [
          "LEVEL"
        ]
      }
    ],
    "hideTitle": false,
    "link": "f0c1c414-de3c-42b1-a5ba-5ac9dd91a5b9"
  },
```
Screenshot right after config
![image](https://user-images.githubusercontent.com/79741077/135479208-70b05c62-600c-467c-afa9-7568ac4bdb57.png)

Screenshot after Browser refresh
![image](https://user-images.githubusercontent.com/79741077/135479079-70e9c535-1eb3-4395-9fb9-d2d5100b6e09.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.85`

**Comment by RkcCorian** [comment]
@Zefau: Würde ich unglaublich gerne testen. Leider kann ich nicht, da ich lauter #1041 bekomme 😥

**Comment by RkcCorian** [comment]
Also... jetzt sehe ich zumindest konsistent gar keine SecondaryStates mehr

**Comment by Bernd9000** [comment]
Hier bei mir auch, es wird kein Secondary state mehr angezeigt

**Comment by mcuiobroker** [comment]
MIt `v3.0.0l-alpha.85` auch keine secondary.

**Comment by Zefau** [comment]
schaut mal bitte mit `v3.0.0-alpha.86`

**Comment by mcuiobroker** [comment]
Sind wieder da.

**Comment by RkcCorian** [comment]
@Zefau: Es funktioniert leider immer noch nicht. Folgendes....
Ich habe 2 Seiten: Wohnung und Räume. Bei Wohnung sind alle SecondaryState da, bei Räume kein einziges.

![image](https://user-images.githubusercontent.com/79741077/135756230-5656ea09-b011-4320-abb4-d93cac87164e.png)

**Comment by Zefau** [comment]
Und die stehen auch noch korrekt in der Konfiguration bzw. wurden vor einigen alpha-Versionen korrekt angezeigt?

Was passiert, wenn du direkt auf die Seite navigierst beim Laden? Also die Tab-URL direkt aufrufst? Werden die Secondary States dann angezeigt (und die der Hauptseite "Wohnung" nicht mehr?) ?

**Comment by RkcCorian** [comment]
@Zefau: Ja, stehen korrekt drin. Etwas interessantes ist mir aber aufgefallen. Auch an anderer Stelle sind die SecondaryStates nicht sichtbar. Außerdem auch das Symbol. Bei folgendem Beispiel müsste sowohl Symbol als auch SecondaryState geladen werden...
Das ist aber nicht reproduzierbar welche. 2 Beispiele, welche in unterschiedlichen Tabs, aber zeitlich nahe beieinander geladen wurden.
![image](https://user-images.githubusercontent.com/79741077/135804260-4e5deb58-9837-43b8-9018-08a8983ada24.png)
![image](https://user-images.githubusercontent.com/79741077/135804354-a5198f55-87ec-4420-8b2f-7aee890e3880.png)

**Comment by RkcCorian** [comment]
@Zefau: Ergänzung:
- Wenn ich JARIVS neu laden auf der Seite "Räume" und dann zu "Wohnung" wechsele, wo die gezeigten Rollläden sind gibt es dieses nicht reproduzierbare Verhalten. Ein paar Rollläden funktionieren nie, welche ich Zufall.
- Wenn ich JARVIS von "Wohnung" aus neu starte gehen immer alle Rollläden

**Daher gibt es einen Unterschied, je nachdem von welcher Seite ist starte**
**Es ist immer der Datenpunkt "LEVEL" meiner Rollläden betroffen**

Darüber hinaus:
Die SecondaryStates unter "Räume", welche in einem anderen Raum als dem ersten ("Wohnzimmer") sind laden tlw. nie. Bspw. nach einem manuellen Refresh explizit von "Küche". Küchenrollladen unter Sicherheit geht immer, Klima niemals. Auch hier ist immer "LEVEL" betroffen, welcher an mehreren Stellen angezeigt wird.
![image](https://user-images.githubusercontent.com/79741077/135817379-7e2f0181-e4c7-4fd7-8b1f-0c83f56665a6.png)

**Comment by Zefau** [comment]
Hast du Warnings im Log?

**Comment by RkcCorian** [comment]
@Zefau: Hab gerade auch mal auf Debug stellt, allerdings keine Warnings. Er lädt einfach nicht "fertig"
![image](https://user-images.githubusercontent.com/79741077/135831473-c819ab0a-e3eb-46a6-af35-76019cd78da6.png)

**Comment by RkcCorian** [comment]
@Zefau: Anbei mal die Konfig von einem Rollladen bei mir. Evtl. stimmt damit was nicht?!
```
  "balkonrollladenlinks_281b0": {
    "name": "Balkonrollladen Links",
    "icon": "window-shutter",
    "label": "",
    "function": "blind",
    "states": {
      "STATUS": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Links.STATUS",
        "display": {
          "0": "Benutzer",
          "1": "Aussperrschutz",
          "2": "Lüften",
          "3": "Sonnenuntergang",
          "4": "Beschattung",
          "5": "Anwesenheitssimulation",
          "6": "Sonnenaufgang"
        },
        "icon": {
          "0": "account",
          "1": "lock-off-outline",
          "2": "tailwind",
          "3": "weather-sunset-down",
          "4": "shield-sun",
          "5": "human-greeting-proximity",
          "6": "weather-sunset-up"
        },
        "label": "Betriebsmodus",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "STATUS",
        "actionElement": null
      },
      "LEVEL": {
        "showState": false,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Links.LEVEL",
        "action": "alias.0.Wohnzimmer.Balkonrollladen_Links.BLIND_COMMAND",
        "display": {
          "0": "Oben 0",
          "50": "Mitte 50",
          "100": "Unten 100"
        },
        "icon": {
          "100": "window-shutter",
          "<100": "window-shutter-open"
        },
        "actionElement": "BlindLevelAction",
        "hide": false,
        "iconStyle": {
          "100": {
            "color": "#aaaaaa"
          }
        },
        "label": "Level",
        "properties": {
          "max": 0,
          "min": 100
        },
        "bodyElement": "LevelBody",
        "stateKey": "LEVEL",
        "BlindLevelActionConfig": {
          "activityState": "LEVEL",
          "stopAction": "LEVEL"
        }
      },
      "AZIMUTH": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Links.AZIMUTH",
        "unit": "°",
        "icon": "axis-z-rotate-clockwise",
        "label": "Rollladenausrichtung",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "AZIMUTH",
        "actionElement": null
      },
      "AZIMUTH_RANGE_SHIELD_SUN": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Links.AZIMUTH_RANGE_SHIELD_SUN",
        "unit": "°",
        "icon": "angle-acute",
        "label": "Beschattungsbereich (+/-)",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "AZIMUTH_RANGE_SHIELD_SUN",
        "actionElement": null
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Alias Devices",
        "namespace": "alias"
      },
      "_created": 1613160982790,
      "_updated": 1623909310417
    },
    "id": "balkonrollladenlinks_281b0"
  }
```

**Comment by Zefau** [comment]
Nicht das ioBroker Log, sondern im Browser mit F12

**Comment by Zefau** [comment]
Konfiguration von Gerät sieht OK aus. Hast du noch das von Layout / Widget zur Hand?

**Comment by RkcCorian** [comment]
Einmal Widget
```
  "75142168-f81b-465a-9021-22fe9c3c3029": {
    "id": "75142168-f81b-465a-9021-22fe9c3c3029",
    "config": {},
    "icon": "home-thermometer",
    "title": "KlimaTest",
    "module": "StateList",
    "items": [
      {
        "type": "device",
        "deviceId": "küchenrollladen_96d80",
        "primaryStateKey": "STATUS",
        "bodyElement": null,
        "bodyStateKey": null,
        "showState": true,
        "actionElement": null,
        "id": "179b4f12-66c7-4ce3-9512-407552776615",
        "secondaryStatesKeys": [
          "LEVEL"
        ]
      }
    ],
    "hideTitle": false,
    "link": "f0c1c414-de3c-42b1-a5ba-5ac9dd91a5b9"
  }
```

Einmal Layout
```
      {
        "icon": "chef-hat",
        "title": "Küche",
        "id": "bb7c0910-8994-4eba-931c-fac4d17b37cb",
        "widgetsDesktop": [
          {
            "x": 0,
            "y": 0,
            "w": 4,
            "h": 3,
            "i": "341b73fe-10e5-464e-bf92-92f445e31c61",
            "moved": false,
            "scaleToFitContents": false,
            "items": [
              "44e5c7a1-f7bd-4457-81e7-c09be7089c0b"
            ]
          },
          {
            "x": 0,
            "y": 3,
            "w": 4,
            "h": 2,
            "i": "d356fcd4-b0b3-4b6e-87b6-0ee97c76b4d0",
            "moved": false,
            "items": [
              "75142168-f81b-465a-9021-22fe9c3c3029"
            ],
            "scaleToFitContents": false
          },
          {
            "x": 4,
            "y": 0,
            "w": 4,
            "h": 6,
            "i": "7827c215-9fb4-4eba-937a-8154564a3720",
            "moved": false,
            "scaleToFitContents": false,
            "items": [
              "0b6322d4-45fe-484d-ba3d-257a87d7ac99"
            ]
          }
        ],
        "widgetsSmartphone": []
      }
```

**Comment by RkcCorian** [comment]
Log... welche wären interessant?!
![image](https://user-images.githubusercontent.com/79741077/135836932-df84c7b3-2b72-4cb0-8f33-ef7bf79fd81b.png)

**Comment by RkcCorian** [comment]
@Zefau : Welcher Fehler würde Dich für Details interessieren? Was würde Dir (und damit uns :-)) helfen?

**Comment by Zefau** [comment]
Die Fehler hängen alle nicht damit zusammen. Kannst du mal einen anderen Browser nutzen und dort in F12 schauen?

**Comment by RkcCorian** [comment]
> Die Fehler hängen alle nicht damit zusammen. Kannst du mal einen anderen Browser nutzen und dort in F12 schauen?

Exakt gleiche Fehler in Mozilla
![image](https://user-images.githubusercontent.com/79741077/136000937-8b4cd020-f1df-4e32-a95f-6069a816e9a1.png)
![image](https://user-images.githubusercontent.com/79741077/136001065-84223446-966a-465e-a94a-62e4caed7124.png)

**Comment by RkcCorian** [comment]
@Zefau: Ich habe jetzt mal andere SecondaryStates konfiguriert. Spannend ist, dass ausschließlich "LEVEL" ein Problem verursacht. Andere Datenpunkte haben kein Problem.
![image](https://user-images.githubusercontent.com/79741077/136085121-bed9d4ea-dbca-4b47-8914-b02333119cfd.png)
![image](https://user-images.githubusercontent.com/79741077/136085384-5627ea8b-ee6d-4f65-b028-fb9b1e659386.png)

**Comment by RkcCorian** [comment]
@Zefau: Hab jetzt nochmal was probiert. Ich habe "LEVEL" in "LEVEL_Test" umbenannt. Damit habe ich keine Probleme. Hast Du irgendwo "LEVEL" hard-codiert? Ist das irgendwo ein Schlüsselwort?

**Comment by RkcCorian** [comment]
@Zefau: Leider doch nicht, war wohl Zufall. Ich habe gerade alle "LEVEL" in "LEVEL_Bug" umbenannt, hat aber doch nicht geholfen

**Comment by RkcCorian** [comment]
@Zefau: Auch mein Test mit anderen Datenpunkten als Secondary konnte ich nicht reproduzieren. Ich denke die einzige verbliebene Gemeinsamkeit bei dem Fehler ist, dass es sich allesamt um Rollläden handelt. :-(
Sorry für die Verwirrung und Falschmeldungen 😥

**Comment by RkcCorian** [comment]
@Zefau: Ja, wirklich nur bei Rollläden. Mir ist inzw. aufgefallen dass es auch nicht nur SecondaryStates betrifft. Du siehst auf den Rolllädenbildern sowohl SecondaryStates als auch States (Links der BlindLevelAction), welche nicht laden. Evtl. ist es daher ein anderer Fehler...
Was immer Dir hilft kann ich versuchen mit meinem bescheidenem Wissen zu ermitteln. Ggf. wäre auch eine DebugSession möglich

**Comment by Zefau** [comment]
Kannst du nochmal in der "Konsole" schauen, ob es dort Fehler gibt? Du hast den Reiter "Elemente" angewählt und ich bin mir unsicher, ob das, was dort zu sehen ist, nicht doch etwas anderes ist.

**Comment by RkcCorian** [comment]
@Zefau: Im Zusammenhang mit ALIAS gibt es ja auch noch #1035

**Comment by Zefau** [comment]
dann mach ich dieses Issue zu, da der Fehler sicherlich mit ALIAS zusammenhängt.

Warum das so ist muss ich analysieren. Keine Ahnung, warum diese so besonders sind. jarvis behandelt diese wie normale Datenpunkte.

**Comment by RkcCorian** [comment]
@Zefau: Phuuu... nun weiß ich auch nicht wie ich weitermachen soll... Ich möchte ungerne alle ALIAS entfernen....

**Comment by RkcCorian** [comment]
@Zefau: Hast Du irgendwelche Timeoutzeiten drin? Sprich wenn die Daten von einem ALIAS zu lange brauchen...

**Comment by Zefau** [comment]
Ich schau heute Abend mal.

Timeout ist drin, aber für alle Datenpunkte gleich. Ich meine 20s

**Comment by RkcCorian** [comment]
Was mir auch aufgefallen ist... die Sonnenaufgangs- und -untergangszeit dauer recht lange zum laden. Ist irgendwann so aufgetreten.

**Comment by mcuiobroker** [comment]
Was möchtest du wie umrechen? Datenpunkt-Eigenschaften, siehe meine Doku

**Comment by RkcCorian** [comment]
In dem Fall kommt das Warndreieck nur manchmal, hab Fehler bei genau einem ALIAS, nämlich LEVEL. Warum auch immer lädt dieser oftmals nicht in JARVIS; ist zumeist sporadisch, bis auf eine Stelle, da lädt er zu 100% nicht. Ein neuer ALIAS bringt auch nicht.

**Comment by mcuiobroker** [comment]
Datenpunkt-Eigenschaften:
`{"value":"val => Math.round(((val * 100) * -1) + 100)"}`

**Comment by RkcCorian** [comment]
Klappt nicht...
![image](https://user-images.githubusercontent.com/79741077/137591981-4c83d4ec-c731-4930-b232-d1f5ddb9f9a4.png)

Da müssten 66% stehen, jedoch steht da 0,44 und die Einheit fehlt
![image](https://user-images.githubusercontent.com/79741077/137592018-f32517e3-2803-41e0-a3fd-3493c6c0f18b.png)
![image](https://user-images.githubusercontent.com/79741077/137592029-d8d77581-6ee8-4f64-8ae3-895e4082eda6.png)

**Comment by Zefau** [comment]
Gilt das auch für https://github.com/Zefau/ioBroker.jarvis/issues/1035 ?

**Comment by RkcCorian** [comment]
@Zefau: Ja. Ich habe hier auch anstelle des ALIAS den original DP benutzen müssen

**Comment by mcuiobroker** [comment]
0,44 scheint der Val zu sein. Dann wird beim BlindLevelAction der val genutzt und nicht der value.

**Comment by RkcCorian** [comment]
Kann ich da was machen?
Neben dem falsch angezeigten Wert fehlt dann auch auf einmal die Einheit

**Comment by mcuiobroker** [comment]
Trag mal bei Einheit `{"default":" %"}` ein.

**Comment by mcuiobroker** [comment]
Ich wäre dafür, dass man im Gerät eine Option bei den Parametern hat, ob dieser auf den val oder value bezogen werden soll. 
Oder als Option für die ActionElemente?

**Comment by RkcCorian** [comment]
So, hab jetzt ein paar Dummy-DP nebst Skript eingebaut. Jetzt geht es, schön ist es aber nicht. Ich hoffe @Zefau findet des Pudels Kern 🙈

**Comment by RkcCorian** [comment]
Ist echt ein signifikanter Perfomance-Unterschied. Die direkten DPs werden deutlich schneller geladen als die ALIAS

**Comment by mcuiobroker** [comment]
> Bezieht sich immer auf `value`

Aber im LevelBody anscheinend nicht?

**Comment by mcuiobroker** [comment]
Ausrufezeiche kommt auch, wenn im Layout die Zuordnung fehlt:
![image](https://user-images.githubusercontent.com/84818934/139556127-4f6a2dec-7550-4d60-9246-672f09ea67f4.png)
![image](https://user-images.githubusercontent.com/84818934/139556136-bba8af22-7fd0-4f9d-a756-71873391e2f3.png)

**Comment by Zefau** [comment]
> alpha-105: Wenn der Wert "0" ist fehlt der "blaue Punkt"

und

>  Ausrufezeiche kommt auch, wenn im Layout die Zuordnung fehlt:

sollte mit `v3.0.0-alpha.109` behoben sein

**Comment by mcuiobroker** [comment]
Ausrufezeichen ist weg, wenn im Layout ein Fehler ist. Trotzdem empfehle ich in dem Fall ein anderes Icon anzuzeigen z.B. 
mdi:alert-rhombus-outline
![image](https://user-images.githubusercontent.com/84818934/139557693-5c3de543-a794-4da9-b3d8-144b60d32791.png)

**Comment by Zefau** [comment]
Wann soll das angezeigt werden? Es wird weiterhin ein Warndreieck angezeigt, wenn der Datenpunkt falsch ist.

**Comment by mcuiobroker** [comment]
In meinem Fall war kein Bodyelement und keine Action-Element ausgewählt, da ich vorher den DP gelöscht hatte.

**Comment by RkcCorian** [comment]
> > alpha-105: Wenn der Wert "0" ist fehlt der "blaue Punkt"
> 
> und
> 
> > Ausrufezeiche kommt auch, wenn im Layout die Zuordnung fehlt:
> 
> sollte mit `v3.0.0-alpha.109` behoben sein

"blauer" Punkt ist bei 0 wieder da :-)
