### ISSUE TITLE
v3: stateHtml Daten werden nicht aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1067]
Bei Änderungen im DP (ioBroker) werden diese in jarvis nicht angepasst. Erst nach F5 stimmen die Daten wieder.

**Comment by mcuiobroker** [comment]
Timeout-Problem gelöst

**Comment by mcuiobroker** [comment]
Wenn in dem HTML Code ein File fest hinterlegt ist und dieses ändert sich wird das Bild / File nicht angepasst.
Es wird nur aktualisiert, wenn man zusätzlich den Text zum Bild ändert
`<div><img width="100%" height="auto" src ="http://192.168.178.89:8082/vis.0/main/ring/bild1.jpg" alt="Bild1" ></div>`

`<div><img width="100%" height="auto" src ="http://192.168.178.89:8082/vis.0/main/ring/bild2.jpg" alt="Bild2" ></div>`

Trotzdem hat er auch beim Wechsel noch die Daten vom alten Bild1, wenn man danach die Daten für Bild1 überschreibt.

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.85`

**Comment by mcuiobroker** [comment]
Jetzt nur noch laufender Strich
![image](https://user-images.githubusercontent.com/84818934/135697388-6dc70c20-b28e-4730-ad09-13fa9e8935e6.png)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.86`

**Comment by mcuiobroker** [comment]
StateHtml wird jetzt wieder normal aktualisiert. Aber jetzt schaltet die ButtonAction nicht mehr korrekt? Ganz komisch.
Die ButtonAction löst zwar den Zeitstempel aus, aber es wird nicht "durchgeschaltet". Hier ein Video dazu:
![v3-alpha-86-ButtonActionschaltet nicht](https://user-images.githubusercontent.com/84818934/135739357-5508bb4a-1b69-4ff0-9056-b7ec654431f8.gif)
