### ISSUE TITLE
Secondary state does not show up

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1069]
**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

Version 3.0.0.85

Secondary state is configured
<img width="1374" alt="Bildschirmfoto 2021-10-02 um 10 55 48" src="https://user-images.githubusercontent.com/2972703/135710074-25c5ce0a-26cf-4fc6-8fb3-16725cb220e2.png">

But does not show up
<img width="783" alt="Bildschirmfoto 2021-10-02 um 10 56 59" src="https://user-images.githubusercontent.com/2972703/135710094-2c633573-a7dc-48f0-9cf4-2c2551d76e88.png">

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1065
