### ISSUE TITLE
v3: Kontrolle der DPs

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1071]
Ich mach mal ein eigenes Issue dafür auf:

![image](https://user-images.githubusercontent.com/84818934/135739637-1e6365db-d852-4163-a9f8-82840072e5c3.png)

![image](https://user-images.githubusercontent.com/84818934/135739655-cd7e9d5f-7c19-4cc2-989a-34d6ca1b50a6.png)

![image](https://user-images.githubusercontent.com/84818934/135739673-81739189-0c1d-45c8-9e31-822fbefa930a.png)

Es gibt den DP gar nicht. Dann sollte es doch ein Error geben?
siehe #1048 Stop-Schild

Anderes Beispiel:
![image](https://user-images.githubusercontent.com/84818934/135741651-37b009e1-c70b-44a2-b0be-56fb0c12046d.png)
Fehler kommt erst, wenn man auf die Seite geht:
![image](https://user-images.githubusercontent.com/84818934/135741689-6fd733d8-a0a3-4c33-9166-8fd398698d93.png)

Die Einträge sollten im ioBroker-Log stehen, da nimmt man sie auch besser wahr.

**Comment by Zefau** [comment]
> Es gibt den DP gar nicht. Dann sollte es doch ein Error geben?

Was ist das Problem? Es zeigt doch eine Warnung an?

Das kann ich noch in das ioBroker Log Brunnen, aber sonst passt es doch jetzt?

Error gibt es nur wenn jarvis abstürzt.

**Comment by mcuiobroker** [comment]
Ja, wenn im ioBroker-Log drin steht. Dann fällt es wohl auf. ok.

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.87` nun Warnungen auch im ioBroker Log

**Comment by mcuiobroker** [comment]
Ein bisschen zu lang und doppelt

`0_userdata.0.jarvis.positions.horizontal is not a valid state` das würde reichen

`
<html>
<body>


jarvis.0 | 2021-10-04 04:01:18.003 | warn | (26768) 0_userdata.0.jarvis.positions.horizontal, 0_userdata.0.jarvis.positions.horizontal is not a valid state, {"name":"Error","message":"0_userdata.0.jarvis.positions.horizontal is not a valid sta
-- | -- | -- | --
jarvis.0 | 2021-10-04 04:01:17.992 | warn | (26768) 0_userdata.0.jarvis.positions.vertical, 0_userdata.0.jarvis.positions.vertical is not a valid state, {"name":"Error","message":"0_userdata.0.jarvis.positions.vertical is not a valid state","s
jarvis.0 | 2021-10-04 04:01:11.006 | warn | (26768) 0_userdata.0.jarvis.system.jsonOnline, 0_userdata.0.jarvis.system.jsonOnline is not a valid state, {"name":"Error","message":"0_userdata.0.jarvis.system.jsonOnline is not a valid state","stac


<br class="Apple-interchange-newline">
</body>
</html>`

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.90`

**Comment by mcuiobroker** [comment]
Sehr schön. Danke.

**Comment by mcuiobroker** [comment]
Ich arbeite immer mit "sonstige" und definier kein Icon. Deswegen kamen bei mir jetzt so viele hoch. Sobald ein Icon im Gerät ist wird das angezeigt.

**Comment by Zefau** [comment]
Das würde bedeuten man muss für jedes Gerät im Gewerk Sonstiges ein Icon vergeben. 

Es soll schon ein Icon sein, was auch bewusst bleiben könnte.

**Comment by mcuiobroker** [comment]
mdi:home-circle-outline , 
mdi:floor-plan,
mdi:power-socket-eu

**Comment by Zefau** [comment]
Es erscheint ein Ausrufezeichen wenn der State nicht vorhanden ist. Das dass Icon nicht vorhanden ist geht nicht mehr, da immer ein Standardicon zieht (wenn https://github.com/Zefau/ioBroker.jarvis/issues/1071#issuecomment-940689850 korrekt funktioniert).

**Comment by mcuiobroker** [comment]
ok

**Comment by mcuiobroker** [comment]
Icon wird bei Auswahl nicht gesetzt.
![image](https://user-images.githubusercontent.com/84818934/137601351-f0b4ccf7-0dcd-49a7-b973-6f052123b56f.png)
In der Liste aber vorhanden:
![image](https://user-images.githubusercontent.com/84818934/137601358-eba630b6-a9c9-458f-b32e-37ec351cbbae.png)
