### ISSUE TITLE
v3: Handyansicht extrem verkleinert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1072]
2 Bilder und ein Video dazu:
Ist auch wieder Browser-abhängig: Firefox funktioniert, Chrome hat diesen Fehler, Edge hat hat auch diesen Fehler.

![image](https://user-images.githubusercontent.com/84818934/135740757-571e724d-b45f-473f-9743-b7a61ec7750d.png)
![image](https://user-images.githubusercontent.com/84818934/135740784-adcf150b-0343-4b64-9557-f661ebf1a220.png)
![v3-alpha-86-Handyansicht](https://user-images.githubusercontent.com/84818934/135741381-2d710b4b-fcb5-4c75-8471-21c08fea5c5a.gif)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.87` wieder passen

**Comment by mcuiobroker** [comment]
Passt
