### ISSUE TITLE
v3: Return nach Eingabe im Input öffnet Popup

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1074]
`v3.0.0-alpha.86`
Ändert man einen Wert im InputAction, so wird der Wert geändert und gleichzeitig das Popup zum DP aufgerufen.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.87` wieder passen

**Comment by mcuiobroker** [comment]
Passt
