### ISSUE TITLE
v3: Weather Widget Scaling to fit content scales too much with mobile phone (fully browser)

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1076]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

alpha-86

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Weather Widget Scaling to fit content scales too much with mobile phone (fully browser)
Works on Tablet and PC

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![Screenshot_20211003_175028_de ozerov fully](https://user-images.githubusercontent.com/79741077/135761750-457ef3b4-5583-4e58-aac2-946802a502c5.jpg)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1072
