### ISSUE TITLE
V3 Hinzufügen von Geräten aus dem MQTT Adapter funktioniert nicht mehr

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#1077]
Ich kann keine Geräte aus dem MQTT Adapter mehr hinzufügen. Bei der Auswahl ist in dem Ordner nichts mehr enthalten

![image](https://user-images.githubusercontent.com/22911084/135802908-bfc3d5bf-459e-4c3c-b227-c11a8aa11bb4.png)

so sieht es unter Objekten aus:

![image](https://user-images.githubusercontent.com/22911084/135802997-27dabd22-9eba-49c8-82ed-c4dad475b62d.png)

**Comment by Zefau** [comment]
Liegt am MQTT Adapter, da die Channels nicht richtig angelegt sind. Du siehst, dass in der Spalte wo bei anderen Zeilen `state` steht, steht dort nichts. Die müssen öffentlich definiert sein.

Melde das gerne im MQTT Adapter als Bug, da muss nachgebessert werden.

Als Workaround gibt es bei der Eingabe des Datenpunktes (Anzeige) eine Auto Vervollständigung beim Tippen.

**Comment by Zefau** [comment]
@MarkSau mit `v3.0.0-alpha.126` sollten die Datenpunkte nun auswählbar sein.
