### ISSUE TITLE
Dark Mode

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#108]

**Comment by WW1983** [comment]
Wäre cool wenn man auch eine Einstellung hätte, dass Jarvis zwischen White- und Darkmode je nach Uhrzeit wechselt

**Comment by juli99** [comment]
Ich fände besser, wenn es unter Objects einen Datenpunk für den Dark-Mode geben würde, den ich selbst aus einem Skript (bspw. Blockly) triggern kann.

**Comment by Zefau** [comment]
Aufgrund der Nachfrage gibt es den Dark Mode jetzt ab `v1.1.0-beta.14`.
