### ISSUE TITLE
v3: HomeKitTile value defined as "boolean" is set as "string"

### ISSUE THREAD

**Issue by simonssoftware** [Zefau/ioBroker.jarvis#1086]
**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? v3.0.0-alpha.87
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
1. Create userstate with type boolean and role state
2. Create HomeKitTile which sets the created userstate
3. Press button on HomeKitTile

**Screenshots**

![image](https://user-images.githubusercontent.com/50638485/136445854-8c991e32-0ef9-4c85-8c0e-6772a6b77b04.png)

![image](https://user-images.githubusercontent.com/50638485/136446560-0f64c236-0194-49a5-9a75-8e833c64c5e3.png)

![image](https://user-images.githubusercontent.com/50638485/136446685-607b4d50-e304-4788-b72f-b0a43d0de600.png)

![image](https://user-images.githubusercontent.com/50638485/136446821-65fa75cc-d792-4947-bd38-5a69e7a90e34.png)

![image](https://user-images.githubusercontent.com/50638485/136445658-f32f7922-d31f-47dc-8d2d-bca27c6ff899.png)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.89`.

**Comment by simonssoftware** [comment]
Funktioniert wieder wie erwartet, danke für die schnelle Lösung! 👍
