### ISSUE TITLE
Icon aus Binding lädt spät

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1090]
Ist ein Binding im Icon, so wird das Icon erst nach 5 Sekunden korrekt umgesetzt. Das sieht nicht so schön aus.
Im Video oben "Zuhause", dort ist im Icon ein Binding. 
`{"{0_userdata.0.Zahl_SONOS}=0":"home","{0_userdata.0.Zahl_SONOS}=1":"home-account"}`
![v3-alpha-87-HandyansichtzuHauseIcon](https://user-images.githubusercontent.com/84818934/135784385-0b8e4801-e23f-4848-940b-f0c6eac2868c.gif)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1046#issuecomment-933094018_

**Comment by Zefau** [comment]
Ist das noch aktuell?

**Comment by mcuiobroker** [comment]
Das ist nicht mehr aktuell.
