### ISSUE TITLE
Icon Ladeverhalten

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1091]
> Es geht darum, der Trash-DP ist im Test-System nicht vorhanden. Der Wert bzw die Anzeige ist aber im Layout definiert. Also ist es momentan so, dass er das  Icon vom Trash nicht anzeigt, sondern auf dem Icon-Platz den blauen Kreis dreht.

> Das Icon ist aber definiert und könnte angezeigt werden.

> Ist der drehende Kreis weg bzw fertig nach 1 Minute, dann erscheint kein Icon, obwohl definiert und anzeigbar.
Deswegen war mein Gedanke, dass man bei solchen DPs im Layout, deren DP nicht vorhanden ist im ioBroker, ein Stop-Schild anzeigt und keinen drehenden Kreis, der nach 1 Minute verschwindet.

> Sonst würde ich denken, das Icon kann nicht geladen werden. Beim einem Stop-Schild würde mir das Problem auffallen?
Denn mal sieht es so aus:
![image](https://user-images.githubusercontent.com/84818934/135785785-ff90bc67-810c-4717-8330-7e56b0e857b3.png)
Jetzt sollte hier das Billd mit dem drehenden Kreis rein, der wird aber momentan nicht mehr angezeigt.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1048#issuecomment-933100259_

**Comment by Zefau** [comment]
@mcuiobroker ist das noch aktuell?

**Comment by mcuiobroker** [comment]
Nein. Kann zu.
