### ISSUE TITLE
Blind level stop ist deaktiviert

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1093]
**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

alpha 89

Bei den Rollladen ist der Stop Button deaktiviert obwohl bei dem Stop Datenpunkt aktiviert ist
<img width="1010" alt="Bildschirmfoto 2021-10-10 um 10 27 14" src="https://user-images.githubusercontent.com/2972703/136688520-7f3b0cef-c1d4-4f16-83ba-a2d97176a5c9.png">

<img width="817" alt="Bildschirmfoto 2021-10-10 um 10 27 41" src="https://user-images.githubusercontent.com/2972703/136688522-330dee65-0f39-4933-b4df-98b366104712.png">

Auch im Popup ist der Stop Button beim BlindLevelAction deaktiviert. Der Stop Button ganz unten funktioniert.

**Comment by stephan1827** [comment]
Wenn ich beim Widget die activity lösche dann funktioniert es

<img width="515" alt="Bildschirmfoto 2021-10-10 um 10 45 00" src="https://user-images.githubusercontent.com/2972703/136688984-dbed78b4-5700-4429-ab6d-d775f04d862e.png">
s

**Comment by stephan1827** [comment]
> @stephan1827 Wenn du im Datenpunkt Aktivität `level` auswählst, funktioniert es dann?

@mcuiobroker yep, das geht

**Comment by mcuiobroker** [comment]
@stephan1827 Kann der Issue dann geschlossen werden?

**Comment by stephan1827** [comment]
> @stephan1827 Kann der Issue dann geschlossen werden?

@mcuiobroker nö, muss da nicht auch activity als Datenpunkt funktionieren?

**Comment by menthido** [comment]
Kann ich den Stop Button selber irgendwie entfernen? Ich kriege meine Qubino Shutter nicht gestoppt und der Stopp Button ist beim runterfahren immer deaktiviert. Deswegen würde ich den Button gern ganz entfernen.

**Comment by Zefau** [comment]
In den Eigenschaften `activity` und `stop` leer lassen

**Comment by menthido** [comment]
@Zefau Besten Dank. Leider funktioniert das aber nur bis ich Up/Down drücke. Dann erscheint der Stop Button automatisch wieder, obwohl activity und stop nun leer sind.

**Comment by Zefau** [comment]
Bei mir geht es. Hast du die Einstellung sowohl im Gerät als auch im Layout vorgenommen?

**Comment by stephan1827** [comment]
Leider ist das Problem wieder zurück, aktuell verwende ich die v3.0.0-beta.18 aber das Problem muss schon früher wieder reingekommen sein. Ich hatte den Stop Button nicht belegt und jetzt wieder neu hinzugefügt. Auf der linken Seite ist er die ganze Zeit aktiv, auf rechten bei Küche nur wenn die Rollos sich bewegen. Einer von beiden ist also nicht korrekt. Ich habe alle Datenpunkte über CSS verglichen und sie sehen identisch aus. Bei allen ist Stop und Activity angebunden. 
<img width="1469" alt="Bildschirmfoto 2021-12-21 um 06 50 28" src="https://user-images.githubusercontent.com/2972703/146878851-e0985ba3-cb48-4e3e-9a47-acb6e0305395.png">

<img width="515" alt="Bildschirmfoto 2021-12-21 um 06 46 48" src="https://user-images.githubusercontent.com/2972703/146878863-029e7987-e403-4cb8-8e80-b0d721ea7b87.png">

Wenn ich das Popup bei Wohnzimmer öffne ist Stop deaktiviert

<img width="806" alt="Bildschirmfoto 2021-12-21 um 06 55 53" src="https://user-images.githubusercontent.com/2972703/146879074-c7b7b6b9-e6be-432f-b681-e5a8aff9e1c0.png">

**Comment by Zefau** [comment]
Den Datenpunkt `activity` gibt es im Gerät gar nicht, oder?

**Comment by Zefau** [comment]
@mcuiobroker kannst du das Folgende in deine Dokumentation aufnehmen?

Der Stop-Button wird nur angezeigt, wenn `activity` und `stop` ausgewählt sind.
- `activity` (`boolean`) beeinflusst ob der Stop-Button ausgegraut (`false`) oder auswählbar (`true`) ist
- sofern ein Adapter kein `boolean` vorhält, kann ich als Entwickler Ausnahmen implementieren. Dies ist z.B. bei `hm-rpc` der Fall, wo die Werte `1` (= `true`), `2` (= `true`) und `3` (= `false`) die Aktivität angeben.
- `stop` ist lediglich der Datenpunkt an den die Aktion geschickt wird. Hier wird kein Wert geladen, der die Visualisierung beeinflusst. Der Wert, der geschickt wird, kann über die Datenpunkt Eigenschaften via `stop` festgelegt werden. Im Standard (`default`) wird `true` geschickt.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/rolllaeden-blind#rolllaeden-blind

**Comment by stephan1827** [comment]
> @stephan1827 Den Datenpunkt `activity` gibt es im Gerät "Rollo Motor" gar nicht, oder?

Doch den gibt es bei allen Geräten. Alle Rollos verwenden das selbe Gerät und sind gleich konfiguriert. Zumindest soweit ich das sehen kann.

**Comment by Zefau** [comment]
Im Popup fehlt er. Stell man bitte die JSON config zur Verfügung

**Comment by stephan1827** [comment]
Hier ist der JSON Code für Wohnzimmer.

"wohnzimmerrollomotor_2f843": {
    "name": "Wohnzimmer Rollo Motor",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "level": {
        "showState": false,
        "state": "hm-rpc.1.001158A9913862.4.LEVEL",
        "action": "hm-rpc.1.001158A9913862.4.LEVEL",
        "label": "Level",
        "actionElement": "BlindLevelAction",
        "iconStyle": {
          "default": {
            "fontSize": 28,
            "color": "#4287f5"
          },
          ">50": {
            "fontSize": 28,
            "color": "#090"
          }
        },
        "display": {
          "0": "Unten",
          "100": "Oben"
        },
        "unit": {
          "0": "",
          "100": "",
          "default": "%"
        },
        "properties": {
          "min": "0",
          "max": "100"
        },
        "icon": "",
        "bodyElement": "LastChangeBody",
        "key": "level",
        "stateKey": "level",
        "BlindLevelActionConfig": {
          "activityState": "activity"
        }
      },
      "activity": {
        "showState": true,
        "state": "hm-rpc.1.001158A9913862.4.ACTIVITY_STATE",
        "label": "Zustand",
        "properties": "",
        "display": {
          "1": "Hoch",
          "2": "Runter",
          "3": "Wartet"
        },
        "action": "",
        "actionElement": null,
        "bodyElement": "LastChangeBody",
        "key": "activity",
        "stateKey": "activity"
      },
      "stop": {
        "showState": true,
        "state": "hm-rpc.1.001158A9913862.4.STOP",
        "action": "hm-rpc.1.001158A9913862.4.STOP",
        "bodyElement": "LastChangeBody",
        "key": "stop",
        "stateKey": "stop"
      }
    },
    "options": {
      "hiddenStates": []
    },
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "HomeMatic IP",
        "namespace": "hm-rpc"
      },
      "_updated": 1619096782606
    },
    "id": "wohnzimmerrollomotor_2f843"
  },

Und hier der für die Küche

"kücherollomotor_cbf10": {
    "name": "Küche Rollo Motor",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "level": {
        "showState": false,
        "state": "hm-rpc.1.001158A9913810.4.LEVEL",
        "action": "hm-rpc.1.001158A9913810.4.LEVEL",
        "label": "Level",
        "iconStyle": {
          "default": {
            "fontSize": 28,
            "color": "#4287f5"
          },
          ">50": {
            "fontSize": 28,
            "color": "#090"
          }
        },
        "display": {
          "0": "Unten",
          "100": "Oben"
        },
        "unit": {
          "0": "",
          "100": "",
          "default": "%"
        },
        "icon": "",
        "actionElement": "BlindLevelAction",
        "bodyElement": "LastChangeBody",
        "key": "level",
        "stateKey": "level"
      },
      "activity": {
        "showState": true,
        "display": {
          "1": "Hoch",
          "2": "Runter",
          "3": "Wartet"
        },
        "state": "hm-rpc.1.001158A9913810.4.ACTIVITY_STATE",
        "action": "",
        "actionElement": null,
        "label": "Zustand",
        "bodyElement": "LastChangeBody",
        "key": "activity",
        "stateKey": "activity"
      },
      "stop": {
        "showState": true,
        "state": "hm-rpc.1.001158A9913810.4.STOP",
        "action": "hm-rpc.1.001158A9913810.4.STOP",
        "bodyElement": "LastChangeBody",
        "key": "stop",
        "stateKey": "stop"
      }
    },
    "options": {
      "hiddenStates": []
    },
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "HomeMatic IP",
        "namespace": "hm-rpc"
      },
      "_updated": 1619096794642
    },
    "id": "kücherollomotor_cbf10",
    "revision": "bf796"
  },

**Comment by Zefau** [comment]
Ich sehe auch nur den Unterschied, dass beim Wohnzimmer explizit

```
"BlindLevelActionConfig": {
   "activityState": "activity"
}
```

angegeben ist. Ist aber eigentlich auch der `default`, insofern sollte es gleich sein.

> Auf der linken Seite ist er die ganze Zeit aktiv, auf rechten bei Küche nur wenn die Rollos sich bewegen.

Die rechte Seite ist das korrekte Verhalten. Stop ist nur aktiv, wenn eine Bewegung vorliegt.

**Comment by stephan1827** [comment]
Habe die Geräte gelöscht und neu hinzugefügt. Jetzt scheint es zu gehen.

**Comment by Zefau** [comment]
Hab mit `v3.0.0-rc.1` nochmal etwas angepasst. Hoffe, dass der bug nun behoben ist.

**Comment by Zefau** [comment]
@RkcCorian
> Wie kann man über CSS die Farbe des STOP-Buttons anpassen, bei ACTIVITY = false (= true funktioniert weiterhin mit der beta)?

Ist Activity vom Adapter oder hast du das fix auf `true`? Wenn du den Button immer sehewillst, mach einen DP auf immer `true`

**Comment by RkcCorian** [comment]
> @RkcCorian
> 
> > Wie kann man über CSS die Farbe des STOP-Buttons anpassen, bei ACTIVITY = false (= true funktioniert weiterhin mit der beta)?
> 
> Ist Activity vom Adapter oder hast du das fix auf `true`? Wenn du den Button immer sehewillst, mach einen DP auf immer `true`

Hab jetzt den DP vom Adapter genommen und nicht fix auf true. Bislang verwende ich Folgendes, was auch bei ACTIVITY = true funktioniert...
```
.BlindLevelAction .text-negative .q-btn__wrapper {
	background-color: rgba(170,170,170,0.15) !important;
	color: #aaaaaa !important;
	border-color: #aaaaaa !important;
}
```

**Comment by RkcCorian** [comment]
Mein Wunsch wäre, dass der STOP Button immer sichtbar ist, ggf. ausgegraut wenn ACTIVITY=false

**Comment by Zefau** [comment]
Wenn `activity` nicht `null` ist wird dieser angezeigt.

**Comment by RkcCorian** [comment]
> Wenn `activity` nicht `null` ist wird dieser angezeigt.

Top!

**Comment by RkcCorian** [comment]
> > @RkcCorian
> > > Wie kann man über CSS die Farbe des STOP-Buttons anpassen, bei ACTIVITY = false (= true funktioniert weiterhin mit der beta)?
> > 
> > 
> > Ist Activity vom Adapter oder hast du das fix auf `true`? Wenn du den Button immer sehewillst, mach einen DP auf immer `true`
> 
> Hab jetzt den DP vom Adapter genommen und nicht fix auf true. Bislang verwende ich Folgendes, was auch bei ACTIVITY = true funktioniert...
> 
> ```
> .BlindLevelAction .text-negative .q-btn__wrapper {
> 	background-color: rgba(170,170,170,0.15) !important;
> 	color: #aaaaaa !important;
> 	border-color: #aaaaaa !important;
> }
> ```
> 
> Hinweis: Bei der aktuell v3.0.1 kommt bei mir der STOP-BUTTON nie, egal ob ACTIVITY = true oder false

```beta-28```
![image](https://user-images.githubusercontent.com/79741077/147661466-55056b93-e620-4b26-be87-41ae0770bdc1.png)


```v3.0.1```
![image](https://user-images.githubusercontent.com/79741077/147662477-da03bddc-7450-4980-acb5-e6db246b3d5c.png)


Konfig
```
  "schlafzimmerrollladen_03b60": {
    "name": "Schlafzimmerrollladen",
    "icon": "window-shutter",
    "label": "",
    "function": "blind",
    "states": {
      "STATUS": {
        "showState": true,
        "state": "alias.0.Schlafzimmer.Schlafzimmerrollladen.STATUS",
        "display": {
          "0": "Benutzer",
          "1": "Aussperrschutz",
          "2": "Lüften",
          "3": "Sonnenuntergang",
          "4": "Beschattung",
          "5": "Anwesenheitssimulation",
          "6": "Sonnenaufgang"
        },
        "icon": {
          "0": "mdi:account",
          "1": "mdi:lock-off-outline",
          "2": "mdi:tailwind",
          "3": "mdi:weather-sunset-down",
          "4": "mdi:shield-sun",
          "5": "mdi:human-greeting-proximity",
          "6": "mdi:weather-sunset-up"
        },
        "label": "Betriebsmodus",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "STATUS"
      },
      "LEVEL": {
        "showState": false,
        "state": "0_userdata.0.Schlafzimmer.Schlafzimmerrollladen.level",
        "action": "alias.0.Schlafzimmer.Schlafzimmerrollladen.BLIND_COMMAND",
        "display": {
          "0": "Oben",
          "100": "Unten"
        },
        "icon": {
          "100": "mdi:window-shutter",
          "<100": "mdi:window-shutter-open"
        },
        "actionElement": "BlindLevelAction",
        "stateStyle": "",
        "properties": {
          "max": 0,
          "min": 100
        },
        "iconStyle": {
          "100": {
            "color": "#aaaaaa"
          }
        },
        "label": "Level",
        "bodyElement": "LevelBody",
        "stateKey": "LEVEL",
        "BlindLevelActionConfig": {
          "activityState": "ACTIVITY",
          "stopAction": "LEVEL"
        },
        "unit": {
          "0": "",
          "100": "",
          "default": " %"
        }
      },
      "ACTIVITY": {
        "stateKey": "ACTIVITY",
        "showState": true,
        "state": "alias.0.Schlafzimmer.Schlafzimmerrollladen.ACTIVITY",
        "hide": true
      },
      "AZIMUTH": {
        "showState": true,
        "state": "alias.0.Schlafzimmer.Schlafzimmerrollladen.AZIMUTH",
        "unit": "°",
        "icon": "mdi:axis-z-rotate-clockwise",
        "label": "Rollladenausrichtung",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "AZIMUTH"
      },
      "AZIMUTH_RANGE_SHIELD_SUN": {
        "showState": true,
        "state": "alias.0.Schlafzimmer.Schlafzimmerrollladen.AZIMUTH_RANGE_SHIELD_SUN",
        "unit": "°",
        "icon": "mdi:angle-acute",
        "label": "Beschattungsbereich (+/-)",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "AZIMUTH_RANGE_SHIELD_SUN"
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Alias Devices",
        "namespace": "alias"
      },
      "_created": 1613160982790,
      "_updated": 1623909349151
    },
    "id": "schlafzimmerrollladen_03b60",
    "revision": "325b6"
  },
```

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.2-beta.0`

**Comment by RkcCorian** [comment]
Darauf habe ich gewartet :-) Sehe es noch nicht, warte... *MitDenHufenScharren*

**Comment by RkcCorian** [comment]
Leider keine Änderung

**Comment by RkcCorian** [comment]
Ist aktuell der (hoffentlich) letzte Fehler, damit ich meine Visualisierung mal zeigen kann 🙃

**Comment by RkcCorian** [comment]
Hast Du bereits einen issue für Folgenden neuen (bezogen auf meine (```beta-28```) Fehler?
<img width="1575" alt="image" src="https://user-images.githubusercontent.com/79741077/147795130-2931eca0-b017-4aeb-a688-ef781da36335.png">

**Comment by Zefau** [comment]
Der Text ist debugging wegen https://github.com/Zefau/ioBroker.jarvis/issues/1407

**Comment by Zefau** [comment]
> Leider keine Änderung 

Er zeigt bei dir den Stop-Button nach wie vor gar nicht an? Echt merkwürdig, weil nun gar keine Prüfung mehr auf `activity` drin ist.

**Comment by RkcCorian** [comment]
> > Leider keine Änderung
> 
> Er zeigt bei dir den Stop-Button nach wie vor gar nicht an? Echt merkwürdig, weil nun gar keine Prüfung mehr auf `activity` drin ist.

Hmm.... was kann ich tun? 🙈

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.2`

**Comment by RkcCorian** [comment]
Nein, leider nein 😥

**Comment by RkcCorian** [comment]
Anbei mal mein Objektbaum von einem meiner Rollläden, falls es hilft.
[alias.0.Wohnzimmer.Balkonrollladen_Links.zip](https://github.com/Zefau/ioBroker.jarvis/files/7797752/alias.0.Wohnzimmer.Balkonrollladen_Links.zip)

**Comment by Zefau** [comment]
stell mal bitte in den Komponenten-Optionen von `activity` und `LEVEL` jeweils auf etwas anderes um und dann wieder zurück. Sowohl im Layout als auch im Gerät.

Ich hab deine alias bei mir eingebunden und in jarvis integriert. Ein Stop-Button wird angezeigt, allerdings funktioniert nichts, da die Verknüpfung zu den originalen Datenpunkten im ioBroker natürlich nicht gegeben ist.

**Comment by RkcCorian** [comment]
Also....
- In der Layout Konfig. sind tatsächlich falsche Daten drin. Keine Ahnung wo die herkommen, so haben meine DPs noch nie geheißen (Meine sind alle groß geschrieben, diese aber klein)
- Nachdem ich diese in der Layout Konfig. korrigiert habe, keine Verbesserung
- Nun habe ich angefangen bei einem Rollladen, alle anderen DPs zu löschen und zu speichern. Ergebnis: Auf JARVIS-Seite sind die STOPs alle da. Gehe ich in ein Gerät rein (Popup) sind diese im Popup nicht da. Mache ich einen Refresh (F5) sind alle STOP-DPs wieder weg. Das ganze ist Reproduzierbar. Wenn ich an einem anderen Rollladen die DPs lösche sind temporär auf der JARVIS-Seite wieder sichtbar. Erneut F5 und alle sind wieder weg.

**Comment by RkcCorian** [comment]
Hab auch mal in der Konsole geschaut, sehe aber keine Fehlermeldung

**Comment by Zefau** [comment]
Discord?

**Comment by RkcCorian** [comment]
PN

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.4-beta.1`

**Comment by stephan1827** [comment]
MIt der letzten Beta sind bei mir die Stop Button bei einigen ganz weg. 
<img width="1586" alt="Bildschirmfoto 2022-01-03 um 07 05 58" src="https://user-images.githubusercontent.com/2972703/147903342-dbdf9c99-ea4e-465a-ad5f-bf16257d1096.png">

In den Einstellungen waren activity und stop leer, ich habe sie neu ausgewählt aber der Stop Button ist immer noch leer.

<img width="1330" alt="Bildschirmfoto 2022-01-03 um 07 06 37" src="https://user-images.githubusercontent.com/2972703/147903352-e982c9c4-28a9-405f-979b-766b12f23ecc.png">

**Comment by RkcCorian** [comment]
```v3.0.4-beta.1```
Gute Nachricht: STOP-Button ist jetzt überall wieder da. Allerdings nicht überall richtig bzgl. ACTIVITY = true / false.
Im folgenden Screenshot sieht man, dass der 2 der 4 STOP Buttons aktiv sind (hellgrau vs. dunkelgrau), obwohl es im Popup richtigerweise inaktiv ist (dunkelgrau).
![image](https://user-images.githubusercontent.com/79741077/147905988-0e2c2641-b099-4ef3-9160-878cab84146e.png)
![image](https://user-images.githubusercontent.com/79741077/147906009-6e526f7e-cd51-41c3-a40b-25adb5c9eb0d.png)

**Comment by Zefau** [comment]
@RkcCorian @stephan1827 schaut bitte nochmal mit `v3.0.4-beta.2`

**Comment by RkcCorian** [comment]
Funktioniert

**Comment by stephan1827** [comment]
@Zefau Ich musste bei den betroffenen Datenpunkt den Trigger manuell nochmal auswählen, dann geht es. Selbst wenn ich das Gerät lösche und neu erzeuge geht es sonst nicht obwohl der Trigger Datenpunkt in dem Fenster korrekt angezeigt wird. Im source code sieht man das er fehlt.

<img width="973" alt="Bildschirmfoto 2022-01-04 um 07 26 12" src="https://user-images.githubusercontent.com/2972703/148018301-9e76ae86-2de5-4155-b445-51e6d1dbb41d.png">

**Comment by Zefau** [comment]
mit `3.0.4` sollte es passen

**Comment by RkcCorian** [comment]
Bei mir nach wie vor alles gut

**Comment by RkcCorian** [comment]
Auch nach 2 Tagen keine Probleme festgestellt :-)

**Comment by Zefau** [comment]
@stephan1827 mit `v3.0.5-beta.0` sollte es auch bei dir passen

**Comment by Zefau** [comment]
@stephan1827

**Comment by stephan1827** [comment]
Yep, sieht gut aus
