### ISSUE TITLE
Labels for states

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#11]
Although I understand your intention to implement translations, I assume that most users will only use one language. Besides that I think that there will be situations where a state name may have different translations depending on the device. 

Instead of translating states in jarvis.0.settings it may be a good idea to implement the possibility to set the name (label) of the state in the state.

```
{
   "esszimmer_fenster":{
      "name":"Esszimmer",
      "room":"esszimmer",
      "function":"window",
      "states":{
         "open":{
            "state":"hm-rpc.1.XXXXXXXXXX.1.STATE",
            "label":"Status"
         }
      },
      "jarvis":{
         "group":"fenster_erdgeschoss"
      }
   }
}
```

_Originally posted by @braindead1 in https://github.com/Zefau/ioBroker.jarvis/issues/9#issuecomment-596758024_

**Comment by Zefau** [comment]
Added with v0.0.5. Could you please test and verify? Thanks

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/wiki/Einstellungen#einstellung-theme-

**Comment by braindead1** [comment]
This is working in v0.0.5.
