### ISSUE TITLE
Jarvis startet nicht mehr nach Update auf aktuelle Alpha.90

### ISSUE THREAD

**Issue by benny000004** [Zefau/ioBroker.jarvis#1101]
Nach einem Update von einer vorherigen Alpha (genaue Versionsnummer weiß ich leider nicht mehr), startet Jarvis in der aktuellen Alpha nicht mehr - weder in Safari, noch Chrome am PC, noch Chrome am Handy.

Folgende Fehlermeldungen werden mir angezeigt (in der Weboberfläche und Chrome-Console), im Log von ioB sehe ich nichts, auch nicht, wenn ich den Adapter auf Debug stelle.

<img width="1680" alt="Screenshot 2021-10-12 at 20 40 22" src="https://user-images.githubusercontent.com/56674793/137011192-20a752b1-25a2-4ef3-a088-38798137a5e3.png">

<img width="771" alt="Screenshot 2021-10-12 at 20 37 08" src="https://user-images.githubusercontent.com/56674793/137011230-50f4d42a-f988-4b8c-9241-4b0c93d0c20b.png">

**Comment by benny000004** [comment]
Könnte das auch das Problem mit den Fehlern lösen (dann würde ich es nochmals versuchen)? Ich habe jetzt ein manuelles Downgrade per ZIP-Datei auf die Alpha.80 gemacht und siehe da, Jarvis startet wieder :-)

**Comment by benny000004** [comment]
Habe es erneut versucht, diesmal auch - um sicher zu gehen, dass es nicht an einem fehlerhaften Git-Download lag - mit der ZIP-Datei (wie beim Downgrade auf die .80) und dasselbe Problem wieder. .90 (aktuelle Master) startet mit obiger Fehlermeldung nicht. Nach einem Downgrade auf .80 aus der ZIP funktioniert es wieder problemlos.

Ich werde jetzt einfach mal bei der .80 bleiben, weil ich leider auch keine weiteren sachdienlichen Fehlermeldungen einreichen kann. Vielleicht hat jemand anders ja noch dasselbe Problem?

**Comment by Zefau** [comment]
- in den ioBroker.jarvis Adapter-Einstellungen: Den Host hast du in der Whitelist bzw. alle Hosts erlaubt?
- SSL Zertifikat (sofern vorhanden) ist angenommen?
- Was kommt, wenn du die im Fehler angegeben URLs manuell im Browser aufrufst?

**Comment by Zefau** [comment]
@MarkSau Mit `https` im Web Adapter aus geht es (also `http` mode). Mit `https` an geht es aktuell auch bei mir nicht.

**Comment by Zefau** [comment]
Keine Ahnung warum das nicht mehr funktioniert. Hab in den letzten Releases daran nichts geändert. Bin gerade etwas ratlos.

**Comment by mcuiobroker** [comment]
@MarkSau Kannst du bitte im ioBroker-Forum mal die einzelnen Schritte aufzeigen, die notwendig waren, um jarvis mit https anzusteuern. Danke.

**Comment by Zefau** [comment]
einfach im Web Adapter https auswählen und Zertifikate einstellen.
