### ISSUE TITLE
v3: Notifications within Notification-Bar on Mobile not readable / cut

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1104]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

```alpha-86```

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Notifications within Notification-Bar on Mobile not readable / cut.
The Notification itself is OK

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![Screenshot_20211014_114241_de ozerov fully](https://user-images.githubusercontent.com/79741077/137293411-2d486ccc-fdac-4aab-8214-f2b59003ab2e.jpg)
![Screenshot_20211014_114554_de ozerov fully](https://user-images.githubusercontent.com/79741077/137293891-87520107-f853-46d0-ad6d-f770c9f94c68.jpg)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.92` wieder passen.
