### ISSUE TITLE
v3: Wrong CSS resets JARVIS fully

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1105]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

```alpha-86```

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Once I add a wrong CSS (because keep trying some stuff) JARVIS will be reseted completely. All "Geräte", "Widget", ... are gone... In case of wrong CSS ignore it / throw an error instead setting back JARVIS please.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Fehler in der Browser Konsole?

Durch einen falschen Style werden keine Geräte oder das Layout gelöscht. Der Style wird einfach als Text interpretiert und genutzt. Sofern der fehlerhaft ist, passiert mit den anderen Daten nichts.

Prüf mal bitte die Datenpunkte `jarvis.0.devices`, `jarvis.0.layout` und `jarvis.0.widgets`.

**Comment by Zefau** [comment]
Hast du ein Beispiel mit dem ich den Fehler nachstellen kann?

**Comment by Zefau** [comment]
Funktioniert bei mir ohne Fehler.

Nochmal zur Sicherheit (sorry für's Nachhaken): Aber die Datenpunkte `jarvis.0.layout` und `jarvis.0.widgets` bzw. `jarvis.0.devices` sind richtig leer und OHNE Inhalt? Oder was steht da drin, wenn der Fehler passiert?

**Comment by RkcCorian** [comment]
@Zefau : Hmm... 
Sie sind auf Ursprungszustand. Sie sind nicht null, aber es sind keinerlei Geräte, Widgets etc. drin.

Vorgehen: Ich ändere CSS fehlerhafterweise und drücke auf speichern
Meine Vermutung: Es kommt zu einem Fehler, aufgrund dessen Geräte, Widgets und Layout als "Leer" übergeben werden und da es ein Speichervorgang ist werden diese leeren Daten in die DPs geschrieben

**Comment by RkcCorian** [comment]
Ich musste aber auch mehrfach probieren, es hatte nicht aufs erste Mal geklappt

**Comment by RkcCorian** [comment]
Dann kann ich ruhig schlafen, danke! 😘😊
