### ISSUE TITLE
After Update to v2.2.3 frequent restarts and no connection to host

### ISSUE THREAD

**Issue by mrkskhnr** [Zefau/ioBroker.jarvis#1106]
PlatformBetriebssystem:linux
Architektur:arm
CPUs:4
Geschwindigkeit:1400 MHz
Modell:ARMv7 Processor rev 4 (v7l)
RAM:923.2 MB
System-Betriebszeit:21:41:33
Node.js:v12.22.7
Datenträgergröße:28.9 GB
Festplatte frei:25.6 GB
NPM:v6.14.15
Adapter-Anzahl:441
Betriebszeit:00:00:22
Aktive Instanzen:4
Pfad:/opt/iobroker/

After updating to v2.2.3, the adapter no longer runs permanently but restarts again and again and reports 

> "no connection to host"

Downgrading and reinstalling did not bring any improvement.

Regardless of the error messages, Jarvis can be opened normally and just throws the error `TypeError: e is null `
(see screenshot Chromium).

Thanks in advance/Danke im Voraus!
_

![Bildschirmfoto vom 2021-10-14 22-26-51](https://user-images.githubusercontent.com/80929315/137391159-a2045314-8a51-4b1e-8ea6-0a3c1e4ed9f1.png)
![Bildschirmfoto vom 2021-10-14 22-18-19](https://user-images.githubusercontent.com/80929315/137391161-f37c33c6-13d9-4269-b84d-4dccb4c22498.png)
*
![Bildschirmfoto vom 2021-10-14 22-34-04](https://user-images.githubusercontent.com/80929315/137391452-d07f50d1-6a08-4f2b-9415-7b0c26225ea7.png)

**Comment by Zefau** [comment]
Was steht im Datenpunkt `jarvis.0.notifications` ? Sofern leer, bitte `[]` eintragen.

**Comment by mrkskhnr** [comment]
War leer. Klammern gesetzt und bestätigt. Neustart des Adapters führt  leider zum selben Ergebnis.
