### ISSUE TITLE
v3: 2.Seite TAB-Anzeige falsch

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1108]
`v3.0.0-alpha.92`
Normale Anzeige der TAB-Zeile
![image](https://user-images.githubusercontent.com/84818934/137595179-a33e1cd5-1049-4382-ae2a-53e8d74ea48a.png)
2.Seite
![image](https://user-images.githubusercontent.com/84818934/137595189-2d9be9fc-aae9-484b-a104-50e645370a36.png)

**Comment by Zefau** [comment]
Weil es nur ein Tab ist? Tab Leiste kommt erst ab zwei Tabs

**Comment by mcuiobroker** [comment]
Sollte nicht trotzdem das TAB-Icon angezeigt werden?

**Comment by mcuiobroker** [comment]
Mit dem 2. Tab wird korrekt anegezeigt.

**Comment by Zefau** [comment]
Ist korrekt so. Warum die Tab Leiste zeigen? Gibt ja nur einen Tab.
