### ISSUE TITLE
Change view based on certain events

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#111]
> Was geil wäre: Ein Event-Hook, so dass die VIS auf eine bestimmte Ansicht (ein bestimmtes Tab) springt, wenn ein bestimmtes Ereignis (ein State ändert sich) eintritt.

> So könnte man beispielsweise die Vis auf das Tab "Überwachsungskameras" springen lassen, sobald jemand an der Tür klingelt (vorausgesetzt man hat die Klingel smart gemacht) und hätte so einen digitalen Türspion.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/56

**Comment by mcuiobroker** [comment]
Kann man ja auch schon mit den Notifications.

**Comment by Zefau** [comment]
das stimmt, eigl. doppelt zu https://github.com/Zefau/ioBroker.jarvis/issues/56
