### ISSUE TITLE
v3: Timeout too small

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1112]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [X] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [X] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

alpha-94

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Ich habe von unterwegs über VPN JARIVS auf meinem Handy geladen. Allerdings dauerte das Laden aufgrund schlechter Verbindung (Willkommen in D) recht lange. Dadurch haben alle Datenpunkte das Warndreieck bekommen. Etwas später wurden die Datenpunkte dann doch geladen, jedoch andere Teile gar nicht mehr (Vgl. Screenshot, bspw. das Wetter-Widget).
Daher sollte der Timeout erhöht werden, ansonsten kann JARVIS ggf. anteilig unterwegs bei schlechter Verbindung gar nicht genutzt werden.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![Screenshot_20211017_161904_de ozerov fully](https://user-images.githubusercontent.com/79741077/137639745-d07bb7ff-b909-4c0b-9e19-367d8cbff590.jpg)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Timeout liegt bereits bei 30s. Kann ich gerne auf 60s hochstellen.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-alpha.95`
