### ISSUE TITLE
add option for `value` or `val`

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1113]
- add options to components, defaults to `val`
- add color option (primary, secondary, accent)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.109` behoben sein

**Comment by mcuiobroker** [comment]
Leider nein.
![image](https://user-images.githubusercontent.com/84818934/139557514-ffab6c44-2330-46f9-8230-290dbca234a1.png)

**Comment by Zefau** [comment]
Das ist im Layout oder im Popup? Und PC oder Mobil?

**Comment by mcuiobroker** [comment]
Das ist im Layout auf dem PC und Handy.

**Comment by Zefau** [comment]
Bei mir funktioniert es und ich weiß nicht so recht, wo der Fehler liegt.

![image](https://user-images.githubusercontent.com/14368811/139558135-7dcf1bde-4276-487a-83bb-38b915249e52.png)

**Comment by mcuiobroker** [comment]
Also ich habe im Layout Levelbody mit "val" und " mit "value" probiert, immer dasgleiche.
![image](https://user-images.githubusercontent.com/84818934/139558189-b85365cf-a472-4712-8fb5-9ff6e95a1d8d.png)

**Comment by Zefau** [comment]
im Chrome funktioniert es tatsächlich nicht; im Firefox (den ich immer nutze) geht es

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.110`
