### ISSUE TITLE
JSON Models pro Gewerk anlegen

### ISSUE THREAD

**Issue by Hohenbostler** [Zefau/ioBroker.jarvis#1115]
Hallo, 

gibt es nicht irgendwie die möglichkeiten JSON anzeigevarianten direkt in den Gewerken zu hinterlegen ? zB das alls Fenster identisch aussehen sofern im eigenen Gerät nichts drin steht ? Ich bin gerade dabei viele Fenster Kontakte einzubauen und muss überall JSON Anzeigevarianten usw anlegen, das geht doch sicher auch einfacher oder ?

**Comment by Zefau** [comment]
Was weicht denn ab?

**Comment by mcuiobroker** [comment]
Sorry, hab ich mich falsch ausgedrückt, ich meinte den DP opened von dem neuen Fenster Küche.

**Comment by Zefau** [comment]
wie geschrieben einen Screenshot vom Gerat und dem Layout

**Comment by Zefau** [comment]
Vom Layout, wo alle Geräte drin sind.
