### ISSUE TITLE
v3: Binding

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1135]
"display": "",

Anscheinend funktioniert das Ausblenden von Statelist-Elementen nur dann, wenn es dort im Gerät ein "display"-Eintrag gibt.
Wann kommt dieser Eintrag zustande?

Denn bei den neu angelegten Gerät funktioniert es mit dem Ausblenden nicht mehr.
Mit dem Gerät funktioniert es: (altes Gerät)
```
"Zuhause": {
        "showState": false,
        "icon": {
          "default": "home mein"
        },
        "state": "javascript.0.HAUS.ALLGEMEIN.STATUS_ZUHAUSE",
        "action": "javascript.0.HAUS.ALLGEMEIN.STATUS_ZUHAUSE",
        "actionElement": "SwitchAction",
        "label": "Zuhause",
        "iconStyle": {
          "true": {
            "color": "yellow"
          }
        },
        "stateStyle": "",
        "display": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "Zuhause",
        "bodyStyle": {
          "{0_userdata.0.testwert}=0": {
            "display": "none"
          }
        }
      }
```

Neu angelegtes Gerät:

```
"pinInput": {
        "stateKey": "pinInput",
        "showState": true,
        "state": "0_userdata.0.jarvis.pin.pinInput",
        "actionElement": "InputAction",
        "InputActionConfig": {},
        "bodyStyle": {
          "{0_userdata.0.testwert}=0": {
            "display": "none"
          }
        }
      },
```
Dabei ist mir aufgefallen, dass man im JSON-Editor (Geräte) keine Zeile hinzufügen kann.

Also mit dem display:"" hat es nichts zu tun, da muss es einen anderen Grund geben.

Klassen vom funktionierenden Gerät Zuhause
![image](https://user-images.githubusercontent.com/84818934/138975681-f6cf736e-2f7b-4538-a783-3d1b39488988.png)
Geräte pinInput
![image](https://user-images.githubusercontent.com/84818934/138975746-72855e00-24cb-4ac3-a71a-252e8cb97586.png)

Also echt komisch, wenn man einmalig ein Wert ändert von dem DP(pinInput) mit dem Binding im Gerät Security, dann funktioniert es wieder? Das war anscheinend auch nur irgendein Zufall. Nachwievor funktioniert es nicht.
Info Text
![image](https://user-images.githubusercontent.com/84818934/138980568-addaed98-d7cd-4676-8532-c6976c70cd65.png)
pinInput (Zufallsereignis)

![image](https://user-images.githubusercontent.com/84818934/138980588-42df181a-bc6d-4c61-a057-69241f089c64.png)

![image](https://user-images.githubusercontent.com/84818934/138980786-d024b48b-57b0-4326-9e5e-41063cfb10b6.png)

![jarvis-Binding-Problem-v104](https://user-images.githubusercontent.com/84818934/138980702-2a0901aa-0e48-4f09-ad04-3279b4f97ef9.gif)

**Comment by Zefau** [comment]
@hosabeni das Icon wird mit `primary state` gezogen. Mir scheint, dass in deinem Layout keins definiert ist? Kannst du bitte ein Screenshot vom Layout posten?

**Comment by Zefau** [comment]
Probiert mal bitte mit `v3.0.0-alpha.111`.

Bitte - sofern es nicht auf Anhieb funktioniert - folgendes im Chrome einstellen:

![image](https://user-images.githubusercontent.com/14368811/139574132-9c07bb2f-8295-44e2-b318-b0fc203097bd.png)

und dort `Disable cache`:

![image](https://user-images.githubusercontent.com/14368811/139574164-9f04e293-7acf-4efd-ae6f-60ef544d2b1d.png)


Dann nochmal mit komplettem Neuladen der Seite probieren, um Fehler auszuschließen.

**Comment by hosabeni** [comment]
> 
> 
> @hosabeni das Icon wird mit `primary state` gezogen. Mir scheint, dass in deinem Layout keins definiert ist? Kannst du bitte ein Screenshot vom Layout posten?

![grafik](https://user-images.githubusercontent.com/77939385/139578952-04fee54b-ad3f-4a1d-a7c8-bfae0068a19e.png)

Hier ist im Feld Icon ein Leerzeichen: (siehe Issue [https://github.com/Zefau/ioBroker.jarvis/issues/1116](url))

![grafik](https://user-images.githubusercontent.com/77939385/139578964-42d05eba-0108-49a4-bbf8-3d7a13e66ea8.png)

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.111`
Keine Verbesserung. Es werden weiterhin beim ersten Start die Bindings im Label angezeigt. Auszublendende Elemente bleiben weiterhin angezeigt.

**Comment by Zefau** [comment]
Hast du die Konsole offen und die Einstellung drin?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/139583214-277dc0c3-d506-4001-a372-a9445fd7a405.png)
Welche Einstellung?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1135#issuecomment-955656951

**Comment by mcuiobroker** [comment]
Gibt es bei mir nicht:
![image](https://user-images.githubusercontent.com/84818934/139583365-1e42d39a-ca8e-4305-8cbf-d16b7b1c5a01.png)

**Comment by Zefau** [comment]
In F12! Dort in die Einstellungen, wie im Screenshot. Nicht in die Chrome Einstellungen.

**Comment by mcuiobroker** [comment]
Gefunden
![image](https://user-images.githubusercontent.com/84818934/139583570-b1c01514-22d1-4ebb-94a8-b06931205ba4.png)
Trotzdem dasgleiche Ergebnis.

**Comment by Zefau** [comment]
Hast du das Problem noch bei anderen Datenpunkten mit Bindings?

**Comment by mcuiobroker** [comment]
Dieses Binding funktioniert teilweise, kann evtl auch daran liegen, das es schon etwas länger drin ist?
![image](https://user-images.githubusercontent.com/84818934/139589178-2a783167-b7d3-4d3c-98bc-f1f20c173bca.png)
Geht man in die Konfig und geht auf abbrechen, wird das Element angezeigt, obwohl es von den Werten her ausgeblendet werden sollte. Nach F5 ist es das Element weg.

**Comment by mcuiobroker** [comment]
Der andere DP mit den gleichen Einstellungen bleibt immer stehen:
![image](https://user-images.githubusercontent.com/84818934/139589599-6df325e1-4002-4257-ac24-af9c3d1f347b.png)
Der nächste wird wieder teilweise ausgeblendet
![image](https://user-images.githubusercontent.com/84818934/139589621-8259e4b0-d999-490a-b947-ff6d1ced5f87.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-alpha.112`

**Comment by mcuiobroker** [comment]
Das Binding bzw der Text wird nicht mehr angezeigt. Trotzdem bleiben die Elemente sichtbar: Bild direkt nach "Abbrechen" in Konfig
![image](https://user-images.githubusercontent.com/84818934/139600345-0b8002df-43b5-41b8-8919-e725708e1ad7.png)

**Comment by Zefau** [comment]
mach mal `"display: none"`, also als String, nicht als Objekt.

**Comment by mcuiobroker** [comment]
```{"{0_userdata.0.jarvis.pin.activeSecurity} = true":"display:none"}```
Kein Unterschied.

**Comment by Zefau** [comment]
Keine Ahnung. Funktioniert bei mir alles wie geschnitten Brot.

Versuch's mal bitte im Firefox.

**Comment by mcuiobroker** [comment]
Firefox auch dasgleiche Ergebnis.

**Comment by Zefau** [comment]
Wenn er das anzeigt, dann stimmt die Abfrage nicht. Also was soll denn kommen, wenn activeSecurity `false` ist und `pinOk` `true` ? Dafür gibt es keinen Wert.

**Comment by mcuiobroker** [comment]
Das ist aber nicht das Problem, mache ich aber auch. Das Problem ist, dass er die anderen DPs nicht ausblendet.

**Comment by Zefau** [comment]
Was ist denn das "richtige"? Welchen Wert haben denn die Datenpunkte? 

Kurz nach dem Speichern hat jarvis noch keine Datenpunkt-Werte. Die werden erst geladen. Mit dem Laden der Werte wird dann das Binding ausgewertet.

Sonst nimm `default` rein.

**Comment by mcuiobroker** [comment]
Datenpunkt Wert wird nicht verändert, erst später durch jarvis:
![image](https://user-images.githubusercontent.com/84818934/139601539-299a02c1-b0a0-40be-90e9-733cbd4ff016.png)
![image](https://user-images.githubusercontent.com/84818934/139601552-055fa04b-dcac-4800-8e76-055db0a41c10.png)

**Comment by Zefau** [comment]
Kannst du den Wert im Datenpunkt mal bestätigt setzen? Macht das einen Unterschied?

**Comment by Zefau** [comment]
Jo, das bekomme ich nicht nachgestellt mit den Informationen. Bei mir funktioniert es.

## LAYOUT KONF.

![image](https://user-images.githubusercontent.com/14368811/139601319-fd55aaac-0c2f-4bc6-a2f3-25d07b5b6b28.png)


## GERÄT KONF.

![image](https://user-images.githubusercontent.com/14368811/139601366-d6491908-6831-456c-8c35-5743c096236a.png)

## LAYOUT

![Binding](https://user-images.githubusercontent.com/14368811/139601599-cf212216-01d6-43a8-82a4-0ea05b24cf18.gif)

**Comment by mcuiobroker** [comment]
```{"default":{"display":"none !important"}}```
Wenn ich das setze sind sie auf jeden Fall ausgeblendet.
Ich sehe auch in dem anderen Fall gar kein "display" zum Element, welches ausgeblendet werden soll. Es wird also gar nicht gesetzt.

**Comment by Zefau** [comment]
`default` war auf das `label` bezogen (also nicht auf das Ausblenden).

**Comment by mcuiobroker** [comment]
Ich wollte nur testen, wie es überhaupt funktioniert.
Beim Label habe ich es auch gemacht, da wird das "default" dirket nach dem Speichern gezeigt und erst nach F5 der gesetzte Wert.

**Comment by Zefau** [comment]
Jetzt geht es bei mir auf einmal auch nicht mehr. Oh man. Aber immerhin nachgestellt. Warum auch immer das jetzt der Fall ist.

**Comment by mcuiobroker** [comment]
Wenn ich jetzt den default durch einen bestimmten Wert, das "display" wegnehme, ist er kurz da für eine 1/2 Sekunde und dann wieder weg. Also er wird durch irgendetwas überschrieben.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.113`

**Comment by mcuiobroker** [comment]
Passt. Woran lag es?

**Comment by Zefau** [comment]
Bindings mehrfach oder selber Datenpunkt wie in irgendeinem Gerät

**Comment by mcuiobroker** [comment]
Geht man in die Konfiguration und klickt direkt auf "Abbrechen", so werden die Werte mit den Bindings falsch angezeigt(Werte display:none sind sichtbar). Nach F5 wieder ok.

**Comment by mcuiobroker** [comment]
AnzeigeVariante mit Binding:
```{"{0_userdata.0.jarvis.fenster.fenster1}=true || {0_userdata.0.jarvis.fenster.fenster2}=true ":"geöffnet","default":"geschlossen"}```
Wird der Wert im Datenpunkt-Anzeige (0_userdata.0.jarvis.fenster.fenster1) der Wert auf "true" gesetzt, so wird dieser Wert in "grün" angezeigt.
Wird dieses "true" durch das Binding in der AnzeigeVariante erzeugt, so wird dieses "true" normal in grau angezeigt.

Das Binding an sich funktioniert, aber teilweise auch erst nach F5.

Weiterhin ist anscheinend die Icon-Suche durcheinander: Es wird teilweise, obwohl Icons definiert sind, das "Ausrufezeichen" Icon angezeigt. Und der DP ist in ioBroker definiert.
Ich musste, um das Ausrufezeichen wegzubekommen, direkt in den DPs Icons setzen und im Widget.

Klicke ich dann auf den DP im Layout zum Popup, werden die Icons teilweise mit kreisenden blauen Ringen wieder gesucht, obwohl vorhanden.
![image](https://user-images.githubusercontent.com/84818934/140432437-6f97f747-2671-4f2b-8245-dbc25cc0744e.png)
![image](https://user-images.githubusercontent.com/84818934/140432453-b330cca1-079a-43aa-af99-bd2c488f4ae1.png)

![image](https://user-images.githubusercontent.com/84818934/140432502-e9cd9531-c1b4-4f94-a85f-d66adaffe3dc.png)
![image](https://user-images.githubusercontent.com/84818934/140432531-ae83a52c-ece5-4f7b-b4a3-f2eb689dc8d9.png)

**Comment by mcuiobroker** [comment]
Bekomme auch diese Fehler?
![image](https://user-images.githubusercontent.com/84818934/140433183-d875283c-1887-471f-87d3-8a0630cbc431.png)

**Comment by mcuiobroker** [comment]
Auch mit anderen Binding Einstellungen "ohne || " kommen die Fehler:
![image](https://user-images.githubusercontent.com/84818934/140434585-95687588-959a-40c5-8497-adc5331a473d.png)

Grundlage war dort das Binding
{"{0_userdata.0.jarvis.fenster.fenster1}=true":"geöffnet","{0_userdata.0.jarvis.fenster.fenster2}=true ":"geöffnet","default":"geschlossen"}
und
{"{0_userdata.0.jarvis.fenster.fenster1}=true":"mdi:window-open-variant"," {0_userdata.0.jarvis.fenster.fenster2}=true":"mdi:window-open-variant","default":"mdi:window-closed-variant"}

**Comment by Zefau** [comment]
Nutzt du die Datenpunkte aus dem Binding noch anderweitig? Also hast du damit noch mehr Bindings oder ggf. direkt in einem Gerät?

Schau nochmal mit `v3.0.0-alpha.114`.

**Comment by mcuiobroker** [comment]
Ja. Die Bindings-DPs werden auch in einem Gerät mehrfach genutzt.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/140576279-9c317402-383f-4a6c-9549-6b6236e2e35c.png)
DP ist aber vorhanden
fenster1
{
  "common": {
    "read": true,
    "write": true,
    "name": "Fenster 1 geöffnet",
    "type": "boolean",
    "role": "state",
    "def": false
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1636063357951,
  "_id": "0_userdata.0.jarvis.fenster.fenster1",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

fenster2
{
  "common": {
    "read": true,
    "write": true,
    "name": "Fenster 2 geöffnet",
    "type": "boolean",
    "role": "state",
    "def": false
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1636063357952,
  "_id": "0_userdata.0.jarvis.fenster.fenster2",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Zefau** [comment]
Schau nochmal mit `v3.0.0-alpha.115`.

**Comment by mcuiobroker** [comment]
Für das Fenster funktioniert es jetzt.
Es werden jetzt die Werte nicht mehr sichtbar, wenn die Binding-Werte nicht stimmen. 
Dort sollten jetzt zwei weitere DPs angezeigt werden
![image](https://user-images.githubusercontent.com/84818934/140586292-3ae6c1ea-f6d9-4b9d-b38c-7b4ada39e460.png)
Auch "default" hilft da nicht:
![image](https://user-images.githubusercontent.com/84818934/140586323-36e65cdd-7a75-4233-a33e-159651661c10.png)

**Comment by mcuiobroker** [comment]
Wird der Datenpunkt im Hintergrund beschrieben, so wird er angezeigt?
![jarvis-v300-alpha-115-Binding](https://user-images.githubusercontent.com/84818934/140587906-e92f8007-bf9f-466d-8bc2-808832d6d45a.gif)

**Comment by RkcCorian** [comment]
Moin Zusammen, hab ne Verständnisfrage... sollte bei folgender Konfig (ICON) nicht meine Ladeanimation erscheinen, abhängig davon ob das Ladegerät eingeschaltet wurde?!
Die Animation funktioniert, wenn ich sie ohne Binding einstelle

```
{
  "{alias.0.Flur.Flurtabletladegerät.STATUS}=true": "home animationBatteryCharge",
  "<10": "battery-outline blinkAus",
  "<20": "battery-low",
  "<65": "battery-medium",
  "<=100": "battery-high"
}
```

**Comment by RkcCorian** [comment]
Fehler gefunden, Reihenfolge war falsch. Funktioniert :-)

**Comment by mcuiobroker** [comment]
Welche Reihenfolge passte denn?

**Comment by RkcCorian** [comment]
```
{
  "<10": "battery-outline blinkAus",
  "<20": "battery-low",
  "<65": "battery-medium",
  "<=100": "battery-high",
  "{alias.0.Flur.Flurtabletladegerät.STATUS}=true": "home animationBatteryCharge",
}
```

**Comment by RkcCorian** [comment]
Hat aber eine Verzögerung in der Reaktion. Wenn ich das Ladegerät ein-/ausschalte dauert es ca. 4 Sekunden bis die Ladeanimation entsprechend reagiert.

**Comment by RkcCorian** [comment]
Nachdem die einfache Version geht versuche ich es etwas komplizierter (Meine Endausbaustufe :-)). Leider klappt es nicht. Irgendeine Idee? Das Binding hat hier keinen Effekt. Die Frage ist Bug oder DAU? 🤪

```
{
  "<10": "battery-outline blinkAus",
  "<20": "battery-low",
  "<65": "battery-medium",
  "<=100": "battery-high",
  "<10 && {0_userdata.0.testLadegerät}=true": "home animationEmptyBatteryCharge",
  "<20 && {0_userdata.0.testLadegerät}=true": "home animationLowBatteryCharge",
  "<=100 && {0_userdata.0.testLadegerät}=true": "home animationMedBatteryCharge"
}
```

**Comment by Zefau** [comment]
"<10": "battery-outline blinkAus",
  "<20": "battery-low",
  "<65": "battery-medium",
  "<=100": "battery-high",
  "{val}<10 && {0_userdata.0.testLadegeraet}=true": "home animationEmptyBatteryCharge",
  "{val}<20 && {0_userdata.0.testLadegeraet}=true": "home animationLowBatteryCharge",
  "{val}<=100 && {0_userdata.0.testLadegeraet}=true": "home animationMedBatteryCharge"
}

**Comment by RkcCorian** [comment]
Danke, klappt fast. Merkwürdiges Verhalten... erst nachdem ich das Popup öffne geht die "richtige" Animation...
![VIS Responsiv](https://user-images.githubusercontent.com/79741077/140604431-d978a81d-65ba-43c8-bcfd-5664a0443fbb.gif)

**Comment by Zefau** [comment]
Jo, deswegen ist das issue noch offen

**Comment by RkcCorian** [comment]
Ahh, gut zu wissen :-)

**Comment by Zefau** [comment]
schaut bitte nochmal mit `v3.0.0-alpha.116`

**Comment by mcuiobroker** [comment]
`v3.0.00-alpha.117`
![jarvis-v300-alpha-117-binding-wird-ohne-änderung-angezeigt](https://user-images.githubusercontent.com/84818934/140614513-561f6966-250e-4e4d-af53-1d0c5bd13ca8.gif)

**Comment by Zefau** [comment]
Schau nochmal bitte mit `v3.0.0-alpha.118`.

**Comment by mcuiobroker** [comment]
Bzgl "abbrechen" der Konfig, passt es jetzt. Danke.

**Comment by RkcCorian** [comment]
@Zefau:
Hmmm... bei mir funktioniert es jetzt mit alpha-118 gar nicht mehr, auch nicht wenn ich das Popup öffne... Hab von oben Folgendes probiert... er nimmt allerdings "battery-outline blinkAus". Neustart des Containers nach Installation von alpha-118 habe ich gemacht.
```
{
  "<10": "battery-outline blinkAus",
  "<20": "battery-low",
  "<65": "battery-medium",
  "<=100": "battery-high",
  "{val}<10 && {0_userdata.0.testLadegeraet}=true": "home animationEmptyBatteryCharge",
  "{val}<20 && {0_userdata.0.testLadegeraet}=true": "home animationLowBatteryCharge",
  "{val}<=100 && {0_userdata.0.testLadegeraet}=true": "home animationMedBatteryCharge"
}
```

**Comment by RkcCorian** [comment]
Update... musste die Reihenfolge umstellen, dann ging es fast...
```
{
  "{val}<10 && {0_userdata.0.testLadegeraet}=true": "home animationEmptyBatteryCharge",
  "{val}<20 && {0_userdata.0.testLadegeraet}=true": "home animationLowBatteryCharge",
  "{val}<=100 && {0_userdata.0.testLadegeraet}=true": "home animationMedBatteryCharge",
  "<10": "battery-outline blinkAus",
  "<20": "battery-low",
  "<65": "battery-medium",
  "<=100": "battery-high"
}
```

Was nicht geht ist "{val}<=100". Wenn ich es ändere auf "{val}<100" geht es. D.h. das "Gleich" im "KleinerGleich" geht nicht

**Comment by RkcCorian** [comment]
> Wird der Datenpunkt im Hintergrund beschrieben, so wird er angezeigt? ![jarvis-v300-alpha-115-Binding](https://user-images.githubusercontent.com/84818934/140587906-e92f8007-bf9f-466d-8bc2-808832d6d45a.gif)

@mcuiobroker : Hast Du eine Doku darüber? Würde es jetzt auch angehen :-)

**Comment by RkcCorian** [comment]
Was wäre das Gegenteil von "{"display":"none"}", sprich das Gegenteil von "none"?

**Comment by RkcCorian** [comment]
@Zefau:, @mcuiobroker : Ich jetzt mal eine PIN Absicherung implementiert. Allerdings gibt es noch ein Problem bzgl. konfigurierter Sichtbarkeit. In meinem Beispiel (So würde ich es im Ziel nutzen): Der PIN wird korrekt eingegeben und die PIN Anzeige wieder ausgeblendet. Das klappt auch. Wenn ich das Popup aber ohne weitere Änderung erneut öffne ist es wieder sichtbar. Meine Konfig...

```
{
  "{0_userdata.0._testUeberwachungAktiv} = false || ({0_userdata.0._testUeberwachungAktiv} = true && {0_userdata.0._testUeberwachungAktivCommandPin} = true)": {
    "display": "none"
  }
}
```
![Binding](https://user-images.githubusercontent.com/79741077/140651444-f5d71db0-6bf5-4f5f-a1db-6e42f3f5ce9b.gif)

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/security
Nimm mal "none !important".

**Comment by RkcCorian** [comment]
> https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/security Nimm mal "none !important".

Leider gleiches Ergebnis.
Bei mir soll die Pin nur im Popup sichtbar werden.
Fehlt Dir evl. ActionElement = InputAction?

**Comment by mcuiobroker** [comment]
Nimm mal den Teil oben Warum? raus.
{0_userdata.0._testUeberwachungAktiv} = false || ({0_userdata.0._testUeberwachungAktiv} = true

**Comment by RkcCorian** [comment]
Logik von Ausblenden:
Entweder ist Überwachung inaktiv > Keine PIN Eingabe sichtbar
ODER (Überwachung ist aktiv UND keine Abschaltung gefordert) > Keine PIN Eingabe sichtbar

Besser fände ich (mir wäre bei bewusstem Einblenden eigentlich wohler, kenn aber das Gegenteil von display:none nicht)
Überwachung ist aktiv UND Abschaltung gefordert > PIN Eingabe sichtbar

```
{
  "{0_userdata.0._testUeberwachungAktiv} = false || ({0_userdata.0._testUeberwachungAktiv} = true && {0_userdata.0._testUeberwachungAktivCommandPin} = true)": {
    "display": "none !important"
  }
}
```


![image](https://user-images.githubusercontent.com/79741077/140654337-1d97178f-ade2-4ed9-ab91-0df2536a97bb.png)
![image](https://user-images.githubusercontent.com/79741077/140654347-a1e6d379-3eb2-452a-940c-9bf7f1f26a23.png)

**Comment by RkcCorian** [comment]
> Nimm mal den Teil oben Warum? raus. {0_userdata.0._testUeberwachungAktiv} = false || ({0_userdata.0._testUeberwachungAktiv} = true Wo ist das überhaupt drin. Zeig mal die Einstellungen zu den DPs.

Klammerung muss beachtet werden

**Comment by mcuiobroker** [comment]
```
{
  "{0_userdata.0._testUeberwachungAktiv} = false": {
    "display": "none !important" ,"{0_userdata.0._testUeberwachungAktiv} = true && {0_userdata.0._testUeberwachungAktivCommandPin} = true)": {
    "display": "none !important"
  }
}
```

**Comment by RkcCorian** [comment]
Leider jedes Mal das gleiche Problem

**Comment by RkcCorian** [comment]
Nach einem Browser-Refresh ist es weg, wenn ich den Popup öffne. Wenn es ihn das 2te Mal öffne ist die Eingabe wieder da und wird nicht mehr versteckt.

**Comment by mcuiobroker** [comment]
Ich bau es gleich mal nach, dauert ein wenig.

**Comment by RkcCorian** [comment]
Brauchst Du was von mir damit es schneller geht?

**Comment by mcuiobroker** [comment]
Ist bei mir auch so. 
![image](https://user-images.githubusercontent.com/84818934/140655347-bf7ccea5-0e5e-405c-8798-fdca64555ce0.png)

![image](https://user-images.githubusercontent.com/84818934/140655332-e4a45e72-f260-4418-bf80-fc2b47d91d70.png)

![image](https://user-images.githubusercontent.com/84818934/140655358-3a2c01bd-b82c-4dee-adc3-4915488b93ed.png)

**Comment by RkcCorian** [comment]
Ist es ein Popup spezifisches Problem, was @Zefau noch fixen müsste?!

**Comment by mcuiobroker** [comment]
Sieht so aus, wie gesagt in dem anderen Fall hatte es bei mir ja funktioniert.

**Comment by RkcCorian** [comment]
Danke für Deine Unterstützung!! Dann warte ich mal auf einen Fix.

**Comment by Zefau** [comment]
versucht es nochmal mit `v3.0.0-alpha.119` (auch bzgl. `<=`/`>=`).

**Comment by RkcCorian** [comment]
Yes!!!!! Beides geht, also PIN Eingabe mit Popup, sowie <=. Dankeeeee!

**Comment by Zefau** [comment]
endlich :-)

**Comment by mcuiobroker** [comment]
Ich sag es echt ungerne, aber ich noch das Problem, dass er es nicht ausblendet, bei den neuen DPs. Und das Icon wird bei einem auch falsch gesetzt.
![image](https://user-images.githubusercontent.com/84818934/140693314-c58057da-1bdd-46d0-b20d-522a863d676d.png)
![image](https://user-images.githubusercontent.com/84818934/140693341-13e97852-cfdb-41d5-918f-db08fe86b03a.png)
![image](https://user-images.githubusercontent.com/84818934/140693385-bbd46fb3-9d33-48e6-a116-977c464355cb.png)
![image](https://user-images.githubusercontent.com/84818934/140693448-f1b7d038-1fae-4523-b794-1c387a465a4e.png)
