### ISSUE TITLE
v3: Icon von SwitchAction nicht auf dem Kreis

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1140]
`v3.0.0-alpha.106` 
Icon wird im "Aus"-Zustand neben dem Kreis?
![image](https://user-images.githubusercontent.com/84818934/139141070-b2a8bac7-9e95-4818-a2fa-0e14612b115b.png)

**Comment by mcuiobroker** [comment]
Ich habe nichts bewusst gemacht, jetzt ist es richtig?
![image](https://user-images.githubusercontent.com/84818934/139554906-2b2de5e3-6ce5-462b-8b80-2be5b6553334.png)

**Comment by Zefau** [comment]
das Label-Problem im Popup behoben mit `v3.0.0-alpha.110`

**Comment by mcuiobroker** [comment]
Popup-Problem passt.

**Comment by Zefau** [comment]
States ist null wenn noch nicht geladen. Daher fehlte es einfach.

**Comment by mcuiobroker** [comment]
Zur Info:
Wenn man `display: inline-flex` raus nimmt ist das Icon auf dem Kreis.

**Comment by Zefau** [comment]
mit `3.0.4` sollte es passen

**Comment by mcuiobroker** [comment]
Zur Info, hinter dem Icon bei false ist ein Unterstrich
![image](https://user-images.githubusercontent.com/84818934/148307736-3fd84f81-2c75-426f-8ed9-688ad4693ff2.png)
Sonst passt es.

**Comment by Zefau** [comment]
Bekommst du raus wo das her kommt? Ist das wegen der Umstellung?

**Comment by mcuiobroker** [comment]
Das hängt mit dem Icon power-off zusammen. Bei power im false Zustand ist dort kein Unterstrich.

**Comment by Zefau** [comment]
In https://github.com/Zefau/ioBroker.jarvis/issues/1140#issuecomment-1004547178 war der Strich auch zu sehen. Also an der Änderung liegt es nicht, es war vorher schon.

Muss ich heute Abend bei schauen wo das her kommt. Ggf. von einem Style?

**Comment by Zefau** [comment]
https://github.com/quasarframework/quasar/issues/11958

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.5`

**Comment by mcuiobroker** [comment]
Passt. Super. Danke.
