### ISSUE TITLE
v3: DropDownAction / Anzeigevarianten Sortierung als Option abschaltbar

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1141]
Bei der Anzeigenvariante ist eine nachgelagerte Sortierung der Elemente eingeschaltet.
Damit man es so sortieren kann, wie man es haben möchte, sollte es eine option in der DropdownAction oder der Anzeigenvariante geben, in der man die Sortierung abschalten kann.
Die Einträge in der Anzeigenvariante würden dann von links nach rechts umgesetzt in der DropDownAction von oben nach unten.

**Comment by Zefau** [comment]
Mit `v3.0.0-alpha.119` kann nun mittels `_noSort` als zusätzlichen Eintrag / Schlüssel die Sortierung verhindert werden.

**Comment by mcuiobroker** [comment]
Wie muss der angegeben werden?
```{"0":"Leichtes Sprühen","1":"Starkes Sprühen","2":"Aus","noSort":""}``` funktioniert nicht.

**Comment by mcuiobroker** [comment]
"Aus" soll eigentlich laut Definition oben stehen?

![image](https://user-images.githubusercontent.com/84818934/140812888-005ea559-c595-4b04-a689-e69d77630d19.png)
->
![image](https://user-images.githubusercontent.com/84818934/140813039-981b3406-44da-4681-b8d3-38dace9bd542.png)

**Comment by Zefau** [comment]
Ich muss es nochmal zu 3.1.x schieben. Hab es im Frontend umgesetzt, aber nicht im Editor. Hab vergessen, dass das Input automatisch bereits schon sortiert. Wenn du es direkt im JSON machst, sollte es im Frontend klappen.

**Comment by Bernd9000** [comment]
Gibt es inzwischen eine Möglichkeit ?

**Comment by mcuiobroker** [comment]
Wäre es hier möglich, weil evtl einfacher für einige, einmal Sortierung nach key (alphabetisch auf und ab, numerisch auf und ab) und einmal Sortierung (alphabetisch auf und ab, numerisch auf und ab) nach value?
-> {"key":"value",...,"_sort":"key"}

"_sort": "keynumUp", "_sort": "keynumdown", -> 1,1.5,2,2.5 usw (keyNumup) 20,19.5,19,.. (keyNumDown)
"_sort": "keyalphaUp", "_sort": "keyalphadown", -> A,--Z (keyAplhaUp), Z,--A (keyAlphaDown)

"_sort": "valuenNumUp", "_sort": "valueNumdown", -> 1,1.5,2,2.5 usw (keyNumup) 20,19.5,19,.. (keyNumDown) zuerst dann alpha
"_sort": "valueAlphaUp", "_sort": "valueAlphadown", -> A,--Z (keyAplhaUp), Z,--A (keyAlphaDown) zuerst dann num?

Beispiel Auswahl WLED Programme
Dort sind die KEY Werte Zahlen
![image](https://user-images.githubusercontent.com/84818934/216100881-d3751567-79c8-498b-8754-ad9966e99cf6.png)
Da will ich doch nicht alle einzelnen Werte jetzt in ein Array schreiben sondern nur sagen sortiere mir die value nach dem Alphabet.
```
{"0":"Solid","1":"Blink","2":"Breathe","3":"Wipe","4":"Wipe Random","5":"Random Colors","6":"Sweep","7":"Dynamic","8":"Colorloop","9":"Rainbow","10":"Scan","11":"Scan Dual","12":"Fade","13":"Theater","14":"Theater Rainbow","15":"Running","16":"Saw","17":"Twinkle","18":"Dissolve","19":"Dissolve Rnd","20":"Sparkle","21":"Sparkle Dark","22":"Sparkle+","23":"Strobe","24":"Strobe Rainbow","25":"Strobe Mega","26":"Blink Rainbow","27":"Android","28":"Chase","29":"Chase Random","30":"Chase Rainbow","31":"Chase Flash","32":"Chase Flash Rnd","33":"Rainbow Runner","34":"Colorful","35":"Traffic Light","36":"Sweep Random","37":"Running 2","38":"Red & Blue","39":"Stream","40":"Scanner","41":"Lighthouse","42":"Fireworks","43":"Rain","44":"Merry Christmas","45":"Fire Flicker","46":"Gradient","47":"Loading","48":"Police","49":"Police All","50":"Two Dots","51":"Two Areas","52":"Circus","53":"Halloween","54":"TriChase","55":"TriWipe","56":"TriFade","57":"Lightning","58":"ICU","59":"Multi Comet","60":"Scanner Dual","61":"Stream 2","62":"Oscillate","63":"Pride 2015","64":"Juggle","65":"Palette","66":"Fire 2012","67":"Colorwaves","68":"BPM","69":"Fill Noise","70":"Noise 1","71":"Noise 2","72":"Noise 3","73":"Noise 4"}
```
![image](https://user-images.githubusercontent.com/84818934/216102704-c5fd6b42-f151-42d7-86fe-50834ef7dd26.png)

Dann sollte es auch eine Einlesemöglichkeit von dem ioBroker-DP-States für die Anzeigevariante geben. Einfach per Klick auf Import-Icon und schon wird der Eintrag von den states (vom ioBroker-DP, der im Datenpunkt Anzeige steht ausgelesen und eingefügt?

**Comment by Zefau** [comment]
dann ab der nächsten beta:

- `_sort`:
  - `none` -> aus
  - `key` -> nach `key`
  - `value` -> nach `value`
  - `[ .. , .. ]` -> bestimmte Reihenfolge

- `_order`: `up` / `down`

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.17`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/216167898-b3056191-216a-4e7c-bed6-fa73ba50fe6b.png)
Es wird order-Wert up oder down als Listenwert angezeigt
![image](https://user-images.githubusercontent.com/84818934/216168053-0840db60-fbd2-42d8-a7ce-8f418f09f9fa.png)
Sonst sieht es gut aus.

**Comment by mcuiobroker** [comment]
>Dann sollte es auch eine Einlesemöglichkeit von dem ioBroker-DP-States für die Anzeigevariante geben. Einfach per Klick auf Import-Icon und schon wird der Eintrag von den states (vom ioBroker-DP, der im Datenpunkt Anzeige steht ausgelesen und eingefügt?

Ist das zu kompliziert?

**Comment by Zefau** [comment]
Der Aufwand steht aus meiner Sicht in keinem Verhältnis zum Mehrwert, wenn ich mir die Menge an Feature Requests anschaue.

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.18`
ok. Sonst passt es. Danke.
