### ISSUE TITLE
v3: jsonTable Reihenfolge nicht einstellbar

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1144]
In den Einstellungen ist die Reihenfolge festegelegt mit
```
[{"label":"Zeit","field":"Zeit","align":"left"},{"label":"Ort","field":"Ort","align":"left"},{"label":"Frage","field":"Frage","align":"left"},{"label":"Antwort","field":"Antwort","align":"left"}]
```
In der Anzeige kommt aber zuerst der Ort, wie es auch im JSON ist:
![image](https://user-images.githubusercontent.com/84818934/139193387-2f30f2a9-ce20-4471-967f-2d3f393f1177.png)

**Comment by Zefau** [comment]
schau mal mit `v3.0.0-alpha.123`

**Comment by mcuiobroker** [comment]
Jetzt wird nur noch ein Fehler angezeigt:
![image](https://user-images.githubusercontent.com/84818934/141385936-7652c350-f755-413e-94ee-1e0a29a3db2b.png)
![image](https://user-images.githubusercontent.com/84818934/141385956-67148086-4b0d-4e8c-b39a-9dec2e43a168.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.124`.

**Comment by mcuiobroker** [comment]
Leider kein Unterschied
![image](https://user-images.githubusercontent.com/84818934/141598959-fd965529-57c2-45a8-a8e6-8359703d9ee9.png)

**Comment by Zefau** [comment]
Wie ist die Konfiguration des JSON bzgl der Spalten?

**Comment by mcuiobroker** [comment]
[{"label":"Zeit"},{"label":"Minuten"},{"label":"Besuch"}]

[{"label":"KW","align":"center"},{"label":"Tag","align":"right"},{"label":"Verbrauch","align":"right"},{"label":"DauerHM","align":"center"}]

[{"label":"name","title":"Name"},{"label":"dateFormat"},{"label":"age"},{"label":"daysLeft"}]

[{"label":"ip"},{"label":"device"},{"label":"online"}]
Das letzte funktioniert sehe ich gerade
[{"label":"Zeit","field":"Zeit","align":"left"},{"label":"Ort","field":"Ort","align":"left"},{"label":"Frage","field":"Frage","align":"left"},{"label":"Antwort","field":"Antwort","align":"left"}]

**Comment by Zefau** [comment]
Fehlt fast überall `field`

**Comment by mcuiobroker** [comment]
Ja brauchte man früher nicht. Brauchte man erst, wenn man den Titel anpassen wollte.

**Comment by Zefau** [comment]
Jetzt ist es wegen der Reihenfolge nötig

**Comment by mcuiobroker** [comment]
Kein Problem, muss man halt nachpflegen.

**Comment by mcuiobroker** [comment]
json Inhalt
![image](https://user-images.githubusercontent.com/84818934/141613597-7def2cd2-001f-4315-9a27-c175c66ca51f.png)

![image](https://user-images.githubusercontent.com/84818934/141613608-1621e542-6e47-4be0-8f1f-efbdbde150aa.png)
Es werden nicht alle Felder aus dem JSON ahngezeigt.
![image](https://user-images.githubusercontent.com/84818934/141613618-44dd0817-571e-4a2e-991e-45d382a169ff.png)

**Comment by Zefau** [comment]
Dann hast du das Feld nicht definiert

**Comment by mcuiobroker** [comment]
Genau. Ich hätte jetzt angenommen, dass er die Felder, die nicht definiert sind, ausblendet, diese aber trotzdem in der Auswahl hat.

**Comment by Zefau** [comment]
Dafür die `visible` Option

**Comment by Zefau** [comment]
Das mit dem nicht definierten `field`passe ich nochmal an

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.125` ist es nun so, dass `field` nicht mehr obligatorisch ist. Dann wird (natürlich) die Reihenfolge der Quelldaten verwendet.
