### ISSUE TITLE
v3: Farbe Schalter SwitchAction vertauscht

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1145]
v3.0.0-alpha.108

Scheinbar sind die Angaben in den Component Options vertauscht.
Bei Farbe(an) wird Farbe aus gesetzt und umgekert.
Außerdem scheint Farbe (an), was bei mir Farbe (aus) ist, nicht zu funktionieren.
Es sollte rot werden, ist aber weiß.

![3](https://user-images.githubusercontent.com/77005685/139285488-b8fc9b9d-4d12-4b3c-a188-91b9ad0000b7.jpg)

![1](https://user-images.githubusercontent.com/77005685/139285500-f263530b-d172-4387-8e0a-d470cb198c25.jpg)
![2](https://user-images.githubusercontent.com/77005685/139285509-2501e266-df35-4bc9-9a06-0a4f614bf485.jpg)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.109` behoben sein

**Comment by Bernd9000** [comment]
v3.0.0-alpha.110
Jetzt ist es bei allen Geräten wieder gleich.
Aber im ausgeschaltetem Zustand ist der Kreis/Punkt vom switch bei mir immer weiß (siehe Bild oben).
Ist das so richtig?
Problem: Im Dark Modus überstrahlt das weiß so stark, das einige Mitglieder des Hauses denken der Schalter wäre eingeschaltet.

**Comment by Zefau** [comment]
>  Aber im ausgeschaltetem Zustand ist der Kreis/Punkt vom switch bei mir immer weiß (siehe Bild oben).
Ist das so richtig?

Korrekt. 

>  Problem: Im Dark Modus überstrahlt das weiß so stark, das einige Mitglieder des Hauses denken der Schalter wäre eingeschaltet.

Ist immer weiß im ausgeschalteten Zustand, siehe https://quasar.dev/vue-components/toggle#dark-and-disable

Lässt sich auch nicht umstellen. Ggf. kannst du mittels CSS eingreifen.

**Comment by Zefau** [comment]
```
.q-toggle__thumb {
   background: #ccc;
}
```

**Comment by Bernd9000** [comment]
Ja, Danke für die Info, ich war auch schon am suchen.
Aber das scheint über css nicht zu gehen.
"background" verändert nur die Hintergrundfarbe vom Kreis (Quadrat). aber nicht den switch selbst.
"color" verändert nur die Farbe im eingeschaltetem Zustand.
"border-color macht gar nichts.
Hab schon diverse variablen durch.

**Comment by Zefau** [comment]
Für color gibt es doch eine Option für an und aus in jarvis

**Comment by Bernd9000** [comment]
Option ? Wo?

**Comment by Zefau** [comment]
In den Optionen vom SwitchAction

**Comment by Bernd9000** [comment]
Ich glaube wir schreiben einander vorbei :-)
Du meinst jetzt wieder die Component Options, aber da funktioniert es ja nicht mit der Farbe (aus), siehe oben.
Deswegen suche ich ja die Möglichkeit über css Code das hinzukriegen.
Man kann den weißen Kreis auch einfärben aber das geht wohl nicht über reinen css code.

**Comment by Zefau** [comment]
Oben CSS Code für den Kreis wenn ausgeschaltet + Option in den Component Options für den Hintergrund. Was fehlt?

**Comment by Bernd9000** [comment]
Dann sieht das bei mir so aus:

Aus:
![1](https://user-images.githubusercontent.com/77005685/139595179-be012cb5-6f82-4401-93cb-f753de0b0c2d.jpg)
Ein:
![2](https://user-images.githubusercontent.com/77005685/139595180-0c165c29-3a95-49c3-b9e2-8f5c438d8bbb.jpg)

**Comment by mcuiobroker** [comment]
@Bernd9000 Wo steht das? `Man kann den weißen Kreis auch einfärben`

![image](https://user-images.githubusercontent.com/84818934/139596902-4f598104-dad8-458f-8419-7354dcdb50c2.png)

**Comment by Zefau** [comment]
Nicht für den ausgeschalteten Zustand. Dort steht ja `for truthy state only`. Oder interpretiere ich das falsch? Auf der Seite gibt es auch kein Beispiel eines gefärbten Kreises beim ausgeschalteten Zustand.

**Comment by Zefau** [comment]
Mit dem CSS Code müsste es gehen:
```
.q-toggle__thumb::after {
   background: #f00;
}
```

**Comment by Bernd9000** [comment]
Super, genau damit geht es.
Danke
