### ISSUE TITLE
v3: DisplayImage - Aktualisierungsintervall

### ISSUE THREAD

**Issue by fprobst170** [Zefau/ioBroker.jarvis#1146]
v3.0.0-alpha.108

Ich hab bei Bildern einen Aktualisierungsintervall eingestellt. Aber die Bilder werden nicht neu geladen / aktualisiert.
Wenn ich die Seite im Browser aktualisiere (F5) wird das neue Bild angezeigt.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.109` behoben sein

**Comment by fprobst170** [comment]
Super, passt wieder. Bilder werden aktualisiert.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/discussions/1151

**Comment by Zefau** [comment]
@fprobst170 schau nochmal mit `v3.0.0-alpha.115`. Hier müsstest du nun in den Einstellungen die Option zur Refresh Methode auf `Zufällige Nummer der URL anfügen` stellen.

@MarkSau bezogen auf die Diskussion #1151 schau nochmal mit `v3.0.0-alpha.115`. Hier müsstest du nun in den Einstellungen die Option zur Refresh Methode auf `Leerzeichen der URL anfügen` stellen.

**Comment by fprobst170** [comment]
Ich hab soeben mit `v3.0.0-alpha.115` getestet. Die Methode `Zufällige Nummer der URL anfügen` funktioniert.
