### ISSUE TITLE
Blind stop button do not work

### ISSUE THREAD

**Issue by MubiTec** [Zefau/ioBroker.jarvis#1148]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] v3.0.0 alpha 112

![Screenshot_2021-10-31-20-29-10-85](https://user-images.githubusercontent.com/44448393/139599584-4f39acb2-2faf-4ff7-93b4-a93c81e04ec7.jpg)

Everthing works great at the bkind.
The only problem is that the STOP button does not work, there is no effect on pushing it.

**Comment by Zefau** [comment]
Set `BlindLevelAction` as an action in the `level` state. In the options of `BlindLevelAction` set `activity` and `stop`. 

- `activity` shall be boolean indicating the movement of the blind.
- `stop` is only used as a trigger (no state is retrieved or used)

The Stop-Button will be usable when `activity` is `true` (meaning blind is moving). Then `stop` will be send once clicked.

**Comment by MubiTec** [comment]
Thank you, this way it works.
In version 100 it was possible to set ACTUAL as value at bodylevel and LEVEL as trigger. So it was possible to set the new value with bodylevel and see how the ACTUAL state is rising or falling to specified value

**Comment by Zefau** [comment]
This has not been changed since and should be working. Try it with states which are not ALIAS states, as they are delayed by nature of ioBroker.

**Comment by MubiTec** [comment]
OK, thank you. So I removed the alias states but without any success.
Here my configuration.

Thanks in advance!

![Uploading Screenshot_2021-11-01-21-30-37-69.jpg…]()

**Comment by Zefau** [comment]
@MubiTec da ist der Upload scheinbar fehlgeschlagen. Kannst es nochmal uppen?

**Comment by MubiTec** [comment]
![Screenshot_2021-11-01-21-30-37-69](https://user-images.githubusercontent.com/44448393/139787031-dacc2b90-381a-4e00-8469-342bb48f8823.jpg)

**Comment by MubiTec** [comment]
@Zefau könntest du einmal gucken, was ich anders auswählen muss, damit er daa actual zeigt aber trotzdem level als action nimmt? Danke schon mal!

**Comment by Zefau** [comment]
Versteh die Frage nicht. Einfach `ACTUAL` statt `level` auswählen? Bei `ACTUAL` dann im Gerät den entsprechenden Datenpunkt Trigger definieren, wie bei `level`, damit er da auf das Gleiche geht. Meinst du das?

**Comment by MubiTec** [comment]
Ja, genau das meinte ich. Danke hat geklappt jetzt :-)
