### ISSUE TITLE
SQL as history adapter won't work

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1149]
https://forum.iobroker.net/post/696568

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/696568

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/697255

**Comment by Zefau** [comment]
@fprobst170 der Fehler aus https://github.com/Zefau/ioBroker.jarvis/issues/901#issuecomment-962421625 sollte mit `v3.0.0-alpha.116` behoben sein. Ich habe es mal hier dokumentiert, weil das das richtige Issue ist.

**Comment by fprobst170** [comment]
Nach Installation der `v3.0.0-alpha.116`  und nachdem ich bei den Einstellungen etwas umgestellt hab funktioniert nun alles.
