### ISSUE TITLE
add possibility to configure options for Body and Action Components

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#115]
**Configuration of min / max values for LevelBody / BlindLevelAction**

https://forum.iobroker.net/post/493558
>  Das gleiche Problem habe ich mit meinen Z-Wave Aktoren auch. Sie verlangen einen Wert von 0-99.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/494223
> Meine Osram GU10 Lampen kennen kein Kelvin oder Brightness in %. Ich muss es also irgendwie bei CT von 153 auf 370 begrenzen und Bri von 0 bis 254.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/83

**Comment by Zefau** [comment]
added with `1.1.0-beta.32`

**Comment by Zefau** [comment]
Habe deinen Kommentar hier übersehen. Absolut richtig. Muss ich nochmal drüber nachdenken. Ich will es eigentlich nur an einer Stelle haben, sonst wird es irgendwann zu kompliziert für die Benutzer.

**Comment by WW1983** [comment]
> Habe deinen Kommentar hier übersehen. Absolut richtig. Muss ich nochmal drüber nachdenken. Ich will es eigentlich nur an einer Stelle haben, sonst wird es irgendwann zu kompliziert für die Benutzer.

Dann wäre die Einstellungsmöglichkeit nur unter Geräte vielleicht sinnvoller. Damit wärst du flexibeler. Bzw. es kann jeder Datenpunkt bearbeitet werden.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/506273

**Comment by CC1337** [comment]
Ich bin durch andere Geräte mit Werten von 2-255 / 254 gerade auch auf das Problem gestoßen.
Ich bräuchte es auch bei den Geräten eigentlich, da ich viele Einstellungen im Modal verwende. Dieser Wertebereich ist ja recht weit verbreitet.
Aber, sollte das bereits gehen bei den Widgets? 
![grafik](https://user-images.githubusercontent.com/4866744/98484841-76a1c100-2212-11eb-8efc-3b22ec5b02b3.png)
In beta88 passiert nichts, wenn ich auf den Schraubenschlüssel bei LevelBody klicke.

**Comment by Zefau** [comment]
@CC1337 this is finally changed now in `v1.1.0-beta.89`.

`min` / `max` werden nun im Gerät direkt definiert:
![image](https://user-images.githubusercontent.com/14368811/98598914-74f00000-22db-11eb-9d90-4e2f1f390dea.png)

Die Body und Action Elemente können nun ebenfalls im Gerät konfiguriert werden. Die Konfiguration wird in das Widget übernommen, kann dort aber bei Bedarf auch überschrieben werden.

**Comment by CC1337** [comment]
Sehr nice!
Leider kann ich es aber noch nicht benutzen, denn nach Update auf beta89 sehe ich nur eine weiße Seite, auch im provate tab.
![grafik](https://user-images.githubusercontent.com/4866744/98601126-e2516000-22de-11eb-8efe-6b8090cf6c7e.png)

**Comment by CC1337** [comment]
@Zefau auch in beta90 tot :( finde gerade nicht raus wich ich zu einem einzelnen Commit zurück kann im ioBroker. Dann könnte ich rausfinden welcher Schuld ist.

**Comment by Zefau** [comment]
Bitte mit `v1.1.0-beta.91` nochmal probieren.

**Comment by WW1983** [comment]
Hier steht einfach nur step = 1

![IMG_3832](https://user-images.githubusercontent.com/56581564/98728379-b5ae4e80-2399-11eb-94d6-93e380762079.png)

**Comment by Zefau** [comment]
Das ist korrekt. Siehe https://github.com/Zefau/ioBroker.jarvis/issues/115#issuecomment-724291575.

**Comment by WW1983** [comment]
Verstehe ich nicht! Was heißt Step 1. Was soll ich da eintragen, bzw. Wo würde ich die min/max Werte eintragen?

**Comment by Zefau** [comment]
Im Gerät wird `min`/`max` definiert, siehst du doch im Screenshot? Unter "Datenpunkt Eigenschaft" wird das hinterlegt. So hattest du es doch auch angefragt?

`step` ist die Schrittweite zwischen den Werten. Also wenn auf 1, dann bewegt sich der Slider immer mit 1 weiter. Die Präzision sozusagen.

**Comment by WW1983** [comment]
Ah ok! Also trage ich die min/max Werte bei dem Punkt Datenpunkt Eigentschaften ein. War auf den ersten Blick nicht erkennbar. Bin davon ausgegangen, dass wenn ich auf den Schrauebschlüssel klicke, ich doch die Werte eintragen kann. So wie beim Action Element. War grad irgendwie nicht selbsterklärend

**Comment by Zefau** [comment]
Ist anders als bisher. Beim Action Element ist es ebenso. Der Schraubenschlüssel enthält nur noch spezifische Optionen für die Komponenten. Geräte-Spezifika werden nun auch im Gerät definiert.

**Comment by WW1983** [comment]
Danke dir!

**Comment by CC1337** [comment]
Mein jarvis ist wieder back mit der .94 und die min/max Config ist (und funzt) super!!
