### ISSUE TITLE
v3: Wenn im Layout ein Fehler ist, oder Einträge leer sind, ein anderes Icon anzuzeigen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1152]
Ausrufezeichen ist weg, wenn im Layout ein Fehler ist. Trotzdem empfehle ich in dem Fall ein anderes Icon anzuzeigen z.B. 
mdi:alert-rhombus-outline
![image](https://user-images.githubusercontent.com/84818934/139557693-5c3de543-a794-4da9-b3d8-144b60d32791.png)
#1065 danach folgende

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1065#issuecomment-955590227_

**Comment by Zefau** [comment]
was meinst du mit Fehler im Layout?

**Comment by Zefau** [comment]
> In meinem Fall war kein Bodyelement und keine Action-Element ausgewählt, da ich vorher den DP gelöscht hatte.

Ist kein Fehler und kann ja bewusst vorkommen um nur den Datenpunkt zu zeigen.
