### ISSUE TITLE
v3: ICON JSON not considered correctly

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1156]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

alpha-113

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

ICON JSON not considered correctly, hat bis alpha-110 korrekt bei einem Wert unter 100 den "offenen" Rollladen angezeigt

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/79741077/140038033-4a6ed158-fa41-495c-8e04-93b407172df5.png)
![image](https://user-images.githubusercontent.com/79741077/140038219-a7a4637a-986f-46f0-9467-bb878e087f3c.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Bernd9000** [comment]
alpha-113
Und "Icon Stil (JSON Format)" funktioniert auch nicht mehr.

**Comment by Bernd9000** [comment]
Beim Icon Stil JSON gibt es auch Probleme

**Comment by Zefau** [comment]
sollte `v3.0.0-alpha.114` behoben sein

**Comment by RkcCorian** [comment]
Bei mir passt es mit alpha-114

**Comment by Bernd9000** [comment]
Im "Icon (JSON Format)" funktioniet es bei mir jetzt auch.
Beim "Icon Stil (JSON Format)" funktioniert es bei mir nicht wenn ein Binding mit drin ist.
Soll das auch behoben sein?

**Comment by Zefau** [comment]
Das ist vermutlich https://github.com/Zefau/ioBroker.jarvis/issues/1135

Schau nochmal mit `v3.0.0-alpha.115`.

**Comment by Bernd9000** [comment]
v3.0.0-alpha.115

Leider nein, 

![Unbenannt](https://user-images.githubusercontent.com/77005685/140585680-07a4670e-9e9c-4c84-aac3-5c4c237d3f25.jpg)

**Comment by Zefau** [comment]
Versuch mal
``` 
{
  "default": {
    "color": "#00F"
  },
  "{mqtt.0.tele.Kellerlicht2.LWT}='Online'": {
    "color": "#F00"
  },
  "ON": {
    "color": "#0F0"
  },
  "OFF": {
    "color": "#F00"
  }
}
```

Also `'Online'` mit `'`.

**Comment by Bernd9000** [comment]
Nein, keine Änderung, selber Fehler in der Browser Konsole.
Es wird nur die default Farbe Blau angezeigt.
Nemme ich das Binding raus funktioniert es mit den anderen Farben.

**Comment by Bernd9000** [comment]
Komisch das es bei den Rolladen ohne Probleme funktioniert

**Comment by Bernd9000** [comment]
Kurze Frage mal zum Quellcode in der "app.81dbce1a.js"
Kann es sein das Variable t kein Wert enthält ?
Weil in der Browser Konsole kein Wert auftaucht.

Zeile 3678
console.warn("Inkorrekt callback function (" + s + ") supplied to " + this.name + " (" + t + ")!", o)

**Comment by Zefau** [comment]
> Komisch das es bei den Rolladen ohne Probleme funktioniert

Wie sind die Einstellungen dort?

**Comment by Bernd9000** [comment]
Bei den Rollladen im Datenpunkt-Bezeichner "level" habe ich folgendes stehen:

{
  "default": {
    "color": "#F00"
  },
  "{0_userdata.0.Shelly.Stube-Rolladen-1.Online}=false": {
    "color": "#FF0"
  },
  ">5": {
    "color": "#0F0"
  }
}

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.116` unter Beachtung des Hinweises https://github.com/Zefau/ioBroker.jarvis/issues/1156#issuecomment-962261253

**Comment by Bernd9000** [comment]
Hier nochmal ein anderes Gerät mit einem anderen Fehler.
Einfache Steckdose mit Tasmota als Firmware.
Nur zwei Datenpunkte: power, status.
Sobald das Binding drin ist läßt Sie sich nicht mehr schalten und das gelbe Icon Symbo erscheint.


![1](https://user-images.githubusercontent.com/77005685/140610862-2216eb86-fe99-46c6-bc8f-272626a55c59.jpg)

![2](https://user-images.githubusercontent.com/77005685/140610865-7ce3ea49-2585-4e83-adcb-44848aa28922.jpg)

![3](https://user-images.githubusercontent.com/77005685/140610867-974a144a-b6bf-46be-8bd5-202534c1a323.jpg)

![4](https://user-images.githubusercontent.com/77005685/140610871-e322ddf6-b01a-434f-8853-eb37ab51cd32.jpg)

![5](https://user-images.githubusercontent.com/77005685/140610876-91d33cdf-2dc6-4bb5-8ffa-922424173ff3.jpg)

**Comment by Bernd9000** [comment]
Ups, probier ich gleich aus

**Comment by Bernd9000** [comment]
v3.0.0-alpha.116
Keine Änderung, nur bei den Rolladen funktionierte es richtig.

**Comment by Zefau** [comment]
Zeig bitte nochmal das Binding in den Geräte-Einstellungen und die Fehlermeldung in der Browser-Konsole

**Comment by Bernd9000** [comment]
[#1156](https://github.com/Zefau/ioBroker.jarvis/issues/1156#issuecomment-962449918)

**Comment by Zefau** [comment]
bei deinem Binding fehlt das `}`

**Comment by Bernd9000** [comment]
Stimmt, habe ich korrigiert, das kommt vom vielen testen.
Steckdose läßt sich wieder schalten.
Farbe bleibt allerdings auf Aus-Wert (rot).
Variable i hat jetzt kein Wert.

Binding korrigiert:
{
  "default": {
    "color": "#00F"
  },
  "{mqtt.0.tele.Steckdose-3.LWT}='Online'": {
    "color": "#F00"
  },
  "ON": {
    "color": "#0F0"
  },
  "OFF": {
    "color": "#F00"
  }
}

Browser Konsole:

![2](https://user-images.githubusercontent.com/77005685/140613418-79074721-0d34-4e91-a41f-35ca2fcd605e.jpg)

![1](https://user-images.githubusercontent.com/77005685/140613423-4ee4005e-b700-4a4c-b18e-5ff4d0817373.jpg)

**Comment by Bernd9000** [comment]
Hab jetzt eine andere Frabe genommen für das Binding um es zu unterscheiden.
Es wird tatsächlich jetzt die richtige Farbe angezeigt wenn offline (gelb).
Jetzt funktionieren aber die Schaltzustände nicht mehr (rot =aus / grün=ein)
Fehler in der Browser Konsole bleibt ( i ist undefiniert)

Binding:
{
  "default": {
    "color": "#00F"
  },
  "{mqtt.0.tele.Steckdose-3.LWT}='Offline'": {
    "color": "#FF0"
  },
  "ON": {
    "color": "#0F0"
  },
  "OFF": {
    "color": "#F00"
  }
}

**Comment by Zefau** [comment]
versuch nochmal mit `v3.0.0-alpha.117`

**Comment by Bernd9000** [comment]
Hurra, jetzt geht es, brauche jetzt ne Pause.
Die anderen Geräte versuch ich später.
Danke

**Comment by Bernd9000** [comment]
v3.0.0-alpha.117
So, ein anderes Gerät, ein Shelly Dimmer.Hier funktioniert es auch nicht richtig mit den Farben beim Icon Stil.
Das Binding selbst funktioniert wenn ich bei "false" KEIN Hochkomma benutze (')
Dann funktionieren allerdings die Farben bei den Schaltztuständen nicht (grün=an / rot=aus)
Nehme ich das Binding raus funktionieren die Farben für die Schaltzustände.
In der Browser Konsole taucht bei diesem Gerät KEIN Fehler auf.

Binding:
{
  "default": {
    "color": "#00F"
  },
  "{0_userdata.0.Shelly.Hobbyraum-Licht-1.Online}=false": {
    "color": "#FF0"
  },
  "true": {
    "color": "#0F0"
  },
  "false": {
    "color": "#F00"
  }
}


![0](https://user-images.githubusercontent.com/77005685/140620428-b8063dad-0965-4a4d-8a5c-1ee35fc36c5c.jpg)

![1](https://user-images.githubusercontent.com/77005685/140620432-e4358295-95b1-46b4-a87e-ab36b049d8d3.jpg)

![2](https://user-images.githubusercontent.com/77005685/140620437-bc56c2aa-671a-4246-be9c-e1ea22a0b170.jpg)

Geräteliste:

 "shelly-dimmer-1_fc866": {
    "name": "Hobbyraum-Licht-1",
    "icon": "",
    "label": "",
    "function": "light",
    "states": {
      "Status": {
        "showState": true,
        "state": "0_userdata.0.Shelly.Hobbyraum-Licht-1.Online",
        "stateStyle": "",
        "iconStyle": "",
        "properties": "",
        "bodyElement": null,
        "display": {
          "true": "Online",
          "false": "----------"
        },
        "label": "",
        "action": "",
        "stateKey": "Status",
        "key": "Status"
      },
      "power": {
        "showState": true,
        "state": "shelly.0.SHDM-2#F4CFA2E1199D#1.lights.Switch",
        "action": "shelly.0.SHDM-2#F4CFA2E1199D#1.lights.Switch",
        "actionElement": "SwitchAction",
        "iconStyle": {
          "default": {
            "color": "#00F"
          },
          "{0_userdata.0.Shelly.Hobbyraum-Licht-1.Online}=false": {
            "color": "#FF0"
          },
          "true": {
            "color": "#0F0"
          },
          "false": {
            "color": "#F00"
          }
        },
        "display": {
          "true": "An",
          "false": "Aus"
        },
        "stateStyle": "",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "power",
        "key": "power"
      },
      "firmware": {
        "showState": true,
        "state": "shelly.0.SHDM-2#F4CFA2E1199D#1.firmware",
        "action": "shelly.0.SHDM-2#F4CFA2E11DF9#1.firmware",
        "actionElement": "IconButtonAction",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "firmware",
        "key": "firmware"
      },
      "temperature": {
        "showState": true,
        "state": "shelly.0.SHDM-2#F4CFA2E1199D#1.temperatureC",
        "action": "",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "temperature",
        "key": "temperature"
      },
      "version": {
        "showState": true,
        "state": "shelly.0.SHDM-2#F4CFA2E1199D#1.version",
        "action": "",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "version",
        "key": "version"
      },
      "level": {
        "showState": true,
        "state": "shelly.0.SHDM-2#F4CFA2E1199D#1.lights.brightness",
        "action": "shelly.0.SHDM-2#F4CFA2E1199D#1.lights.brightness",
        "actionElement": "",
        "bodyElement": "LevelBody",
        "label": "",
        "stateKey": "level",
        "LevelBodyConfig": {
          "showMarkersSteps": true,
          "markStep": "10"
        },
        "key": "level"
      },
      "powerCounter": {
        "showState": true,
        "state": "shelly.0.SHDM-2#F4CFA2E1199D#1.lights.Energy",
        "unit": " Wh",
        "action": "",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "powerCounter",
        "key": "powerCounter"
      },
      "powerMeter": {
        "showState": true,
        "state": "shelly.0.SHDM-2#F4CFA2E1199D#1.lights.Power",
        "unit": " W",
        "action": "",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "powerMeter",
        "key": "powerMeter"
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Shelly",
        "namespace": "shelly"
      },
      "_created": 1619168545808,
      "_updated": 1621162045396
    },
    "id": "shelly-dimmer-1_fc866",
    "revision": "ed903"
  },

**Comment by mcuiobroker** [comment]
Funktioniert das?
```
{
"default": {
"color": "#00F"
},
"{0_userdata.0.Shelly.Hobbyraum-Licht-1.Online}=false": {
"color": "#FF0"
},
"{0_userdata.0.Shelly.Hobbyraum-Licht-1.Online}=true" && {val}=true": {
"color": "#0F0"
},
"{0_userdata.0.Shelly.Hobbyraum-Licht-1.Online}=true" && {val}=false": {
"color": "#F00"
}
}

```

**Comment by Bernd9000** [comment]
Da krieg ich ein Parse Error on Line 8:

![3](https://user-images.githubusercontent.com/77005685/140620843-dc1cafe5-7e24-47a7-a991-4768efac8cc2.jpg)

**Comment by mcuiobroker** [comment]
" zuviel geändert oben,bitte nochmal

**Comment by Bernd9000** [comment]
Super, funktioniert jetzt.
Danke Dir.
Aber da wäre ich nie von alleine drauf gekommen.

**Comment by Bernd9000** [comment]
Issue kann dann wohl geschlossen werden.

**Comment by Zefau** [comment]
> Das Binding selbst funktioniert wenn ich bei "false" KEIN Hochkomma benutze (')

Hochkomma generell nur bei Strings, nicht bei Zahlen oder Boolean.


Icon Stil Binding:
```
{
  "default": {
    "color": "#00F"
  },
  "{0_userdata.0.Shelly.Hobbyraum-Licht-1.Online}=false": {
    "color": "#FF0"
  },
  "true": {
    "color": "#0F0"
  },
  "false": {
    "color": "#F00"
  }
}
```

Das sollte so funktionieren, wie du es gepostet hast. Die Variante von @mcuiobroker ist die Langversion bzw. ausgeschriebene Version und ebenfalls korrekt.

Der Unterschied liegt darin, dass bei der Kurzversion mehrere Schlüssel zutreffen könnten. Bei der Variante von @mcuiobroker wird das ausgeschlossen.

Bezogen auf die Kurzversion bedeutet das, dass die erste korrekte Variante übernommen wird. Wenn `0_userdata.0.Shelly.Hobbyraum-Licht-1.Online` also `false` ist, wird immer das genommen. Wenn es nicht `false` ist, wird `true`, dann `false` ausgewertet.

Bitte gib mir nochmal Feedback, ob die Kurzversion so funktioniert wie beschrieben. Wenn nicht, muss ich nochmal schauen.

**Comment by Bernd9000** [comment]
Die Kurzversion funktioniert leider nicht.
1.) Wenn {0_userdata.0.Shelly.Hobbyraum-Licht-1.Online} auf "false" steht wird das Icon gelb  (richtig)
2.)Wenn {0_userdata.0.Shelly.Hobbyraum-Licht-1.Online} auf "true" steht wird das Icon blau  (falsch- sollte rot oder grün werden)
3.)Wird der Schalter betätigt bleibt Icon blau (falsch- sollte rot oder grün werden)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.119`

**Comment by Bernd9000** [comment]
Ja, funktioniert jetzt

**Comment by mcuiobroker** [comment]
Ich schreib es mal hier rein.
Beide DPs sind nicht mehr in ioBroker vorhanden, trotzdem wird bei einem das Sonstige Icon angezeigt.
![image](https://user-images.githubusercontent.com/84818934/140697058-22fe5ff0-ba47-4fb5-8f02-b36663eaf338.png)
Beim 1. kommt die Meldung:
![image](https://user-images.githubusercontent.com/84818934/140697338-cf994c20-9ee4-4c11-b200-2b021c5536c8.png)

Beim 2. kommt die Meldung:
![image](https://user-images.githubusercontent.com/84818934/140697290-7b37cb0e-0da3-49bb-965d-00a6877e0d6a.png)

**Comment by Zefau** [comment]
Was steht im Gerät als Konfiguration für das Icon?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/140714330-ecd7b7b7-337c-4730-b1a3-1818d40bdada.png)

**Comment by Zefau** [comment]
Also im Layout auch gleich drin?

Scheinbar gibt es für den ersten Eintrag noch den State in ioBroker, aber kein Objekt mehr. Daher funktioniert der noch. Und daher auch die Fehlermeldung von ioBroker, dass `has no existing object`. Das ist kein jarvis Fehler.

Also nicht richtig gelöscht scheinbar.

**Comment by Zefau** [comment]
also da kann ich wenig machen. Ich könnte auch das Objekt abfragen, aber dann wird es massiv viele Fehler bei den Usern für falsch erstellte eigene Datenpunkte geben.
