### ISSUE TITLE
Hide number in circle widget

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1160]
Version v3.0.0-alpha.113

When you have a small circle widget, the number disturbs the view. It would be nice to have an option to disable the number.

<img width="126" alt="Bildschirmfoto 2021-11-05 um 19 50 11" src="https://user-images.githubusercontent.com/2972703/140563573-6d1bbbaf-5f13-42fa-953e-612689605d47.png">

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.114` hab ich eine Option hinzugefügt

**Comment by mcuiobroker** [comment]
Wie kann man die 0 im Circle entfernen?
![image](https://user-images.githubusercontent.com/84818934/140583642-80898581-9d8f-47da-b649-43ba0b1281ed.png)

**Comment by Zefau** [comment]
![image](https://user-images.githubusercontent.com/14368811/140583890-034158d5-a691-4c16-99cd-4cb1dda34011.png)

`Werte-Label verstecken`

**Comment by mcuiobroker** [comment]
Ja das hab ich ja gemacht, der Wert 20 wird auch ausgeblendet. Die 0 aber nicht.

**Comment by Zefau** [comment]
Das kommt von der Achse. Blende ich mit der nächsten alpha aus.

**Comment by Zefau** [comment]
Schau nochmal mit `v3.0.0-alpha.115`.

**Comment by mcuiobroker** [comment]
Passt.
![image](https://user-images.githubusercontent.com/84818934/140589473-ee5329ae-12dc-4173-a2c6-33a39896ae69.png)

**Comment by stephan1827** [comment]
Funktioniert, besten Dank
