### ISSUE TITLE
Iframe motioneye videostream

### ISSUE THREAD

**Issue by MubiTec** [Zefau/ioBroker.jarvis#1163]
V3.0.0 112
I have an iframe with Videostream from motioneye. I have the "keep alive" true.
I see the stream and it works about 5 seconds, after that the picture is frozen. After 10 more seconds the iframe loads the stream new and the procedure starts from beginning.
Any idea what to to?
If I watch the stream in normal browser everything works fine.

**Comment by Zefau** [comment]
Do you have the refresh option turned off or on?

**Comment by MubiTec** [comment]
It is on, 300 seconds

**Comment by Zefau** [comment]
Any difference if you turn it off by setting 0 ?

Do you have the problem when turning off the `keep alive` option?

Did you try to play with the options regarding sandboxing?

**Comment by MubiTec** [comment]
Not really. It seems to be a wallpanel issue.in Firefox there is no problem.
