### ISSUE TITLE
v3: Link öffnet nicht in Safari

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1165]
Auf Safari öffnet sicher der Link nicht wenn man auf das i klickt.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/13101074/140642759-a9e96e79-a4fa-4be2-9f7a-5f95f502de90.png">

**Comment by Zefau** [comment]
schau mal mit `v3.0.0-alpha.123`

**Comment by AFPass** [comment]
Passt.
