### ISSUE TITLE
v3: Gruppenswitch "tlw. an" funktioniert nicht

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1166]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

alpha-119

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Der Gruppenswitch sollte nach meiner Erinnerung "in der Mitte" stehen für tlw. an.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/79741077/140661181-f8e0497b-c785-4c86-912b-472d72ca8dad.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
schau mal mit `v3.0.0-alpha.122`

**Comment by RkcCorian** [comment]
Funktioniert mit alpha-122 wieder
