### ISSUE TITLE
Kein Einstellungen Button in iOS 15.0.2

### ISSUE THREAD

**Issue by danieltrapp** [Zefau/ioBroker.jarvis#1168]
Der Einstellungen Button wird in iOS 15.0.2 nicht angezeigt. 
Safari 
Firefox Daylight 38.1 (6216)

Jarvis 3.0.0-alpha 119

Im Firefox auf Windows und Safari in MacOS ist er zu sehen.

**Comment by Zefau** [comment]
Der Button wird auf mobil / tablet nicht angezeigt.
