### ISSUE TITLE
v3: CSS not working any more

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1169]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

alpha-121

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

CSS not working any more

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/79741077/141192730-5adc680c-a59a-4776-a9a3-0f83a1086494.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
Ergänzung: Alles was ich im CSS konfiguriert habe, wie bspw. Hintergrundbild, Größe BlindCommand, Blinken, ... funkioniert nicht mehr. Daher denke ich, dass CSS komplett nicht mehr funktioniert

**Comment by RkcCorian** [comment]
Ergänzung: Es fehlen weitere Element, wie das Benachrichtigungssymbol rechts oben und die Seitennavigation...
![image](https://user-images.githubusercontent.com/79741077/141357480-1d47caf0-d3d1-482e-be7d-7d2c687b2dd5.png)

![image](https://user-images.githubusercontent.com/79741077/141357578-4ca0d852-9c96-44d1-8af7-fd54916d597c.png)

**Comment by Zefau** [comment]
schau mal mit `v3.0.0-alpha.122`

**Comment by RkcCorian** [comment]
Passt mit alpha-122
