### ISSUE TITLE
Allow user defined global CSS styles overwriting any default styles

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#117]

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/509877

**Comment by Zefau** [comment]
added with `v2.1.0-beta.22`.

To use custom CSS the state `jarvis.0.css` has been introduced. This state shall hold the custom CSS, which will be applied in jarvis.

**Comment by duczz** [comment]
Sehr geil danke, klappt hervorragend.
Wenn du in den Settings nochn Editor mit einbauen könntest wäre es top

**Comment by Zefau** [comment]
hab mit `v2.1.0-beta.25` eine Konfiguration in die UI aufgenommen.
