### ISSUE TITLE
Ausrichtung Kalender inkorrekt

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1178]
![image](https://user-images.githubusercontent.com/84818934/135707960-2fb82c22-5643-4533-b6d7-3c6e0f1419df.png)

![image](https://user-images.githubusercontent.com/84818934/135707970-6ccd945a-4f9d-400b-bf8c-994da47abf36.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/832#issuecomment-932701602_

**Comment by Zefau** [comment]
@mcuiobroker @ma-gu-16 habt ihr das Problem hier noch?

**Comment by mcuiobroker** [comment]
Wird mittig angezeigt. ok.

**Comment by Zefau** [comment]
top
