### ISSUE TITLE
Flexible Layout: Allow lines in tabs

### ISSUE THREAD

**Issue by mla4ger** [Zefau/ioBroker.jarvis#118]
In addition to the columns, it would also be nice if there were lines

**Comment by Zefau** [comment]
is this actually a duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/129 ?

**Comment by mla4ger** [comment]
Ja. Wenn ich das richtig interpretiere. Was ich mir gewünscht habe war, 
dass ich z. B. ein Line Widget oben über die gesamte Breite habe und 
darunter z. B. drei Spalten Widget. Vielen Dank



------------------------------------------------------------------------
Gesendet mit der Telekom Mail App
<https://kommunikationsdienste.t-online.de/redirects/email_app_android_sendmail_footer>


--- Original-Nachricht ---
Von: Zefau
Betreff: Re: [Zefau/ioBroker.jarvis] Flexible Layout: Allow lines in tabs 
(#118)
Datum: 31. Januar 2021, 16:16
An: Zefau/ioBroker.jarvis
Cc: mla4ger, Author



is this actually a duplicate to #129
<https://github.com/Zefau/ioBroker.jarvis/issues/129> ?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/Zefau/ioBroker.jarvis/issues/118#issuecomment-770398066> 
, or unsubscribe

**Comment by Zefau** [comment]
Ok, dann ist es dasselbe. Dann schließe ich dieses Issue, da doppelt zu https://github.com/Zefau/ioBroker.jarvis/issues/129.
