### ISSUE TITLE
Position of widgets

### ISSUE THREAD

**Issue by MubiTec** [Zefau/ioBroker.jarvis#1180]
V3.0.0 125

Ich will zwei history Graphen untereinander platzieren (siehe Screenshot).
In der Ansicht sind diese jedoch grundsätzlich nebeneinander.
Hab ich etwas vergessen zu definieren? Ich krieg es einfach nicht hin
![Screenshot_2021-11-15-20-55-02-47](https://user-images.githubusercontent.com/44448393/141845802-9471a16b-e442-49cb-b164-5146ea41583e.jpg)

Danke schon mal!

**Comment by Zefau** [comment]
Bei dem blauen Kasten kannst du rechts unten die Größe ziehen. Dort kleiner ziehen und den anderen Kasten daneben platzieren.

**Comment by MubiTec** [comment]
Hab ich schon probiert, hatte die erst in der Konfiguration untereinander, jetzt nebeneinander, aber am Resultat ändert sich nichts, die sind immer nebeneinander.

![Screenshot_2021-11-16-05-21-45-26](https://user-images.githubusercontent.com/44448393/141915023-0566d31a-74ea-49d7-a6a0-eb9641dfa4b1.jpg)
![Screenshot_2021-11-16-05-21-38-02](https://user-images.githubusercontent.com/44448393/141915044-c6adaf46-50e1-41f1-9906-121a71f95b73.jpg)

**Comment by Zefau** [comment]
Ok, hab mich verlesen. Wenn die Graphen untereinander sein sollen war die Konfiguration deines ersten Posts richtig.

Du musst in den Einstellungen dann noch die Breakpoints anpassen, da du wahrscheinlich auf dem Tablet bist und Jarvis aufgrund der Größe im Responsive Modus.

**Comment by MubiTec** [comment]
OK, danke. Jetzt müsstest du mir nur noch eben helfen, wo ich die Breakpoints finde :-)

**Comment by Zefau** [comment]
Unter Einstellungen

**Comment by MubiTec** [comment]
Sorry, find ich irgendwie nicht. In welchen Einstellungen? Vom widget und vom tab find ich das nicht

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/142036340-0942f3be-14fc-46ad-b424-01d469bbfb0d.png)

https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/bildschirmgroesse

**Comment by MubiTec** [comment]
Nun klappt es, vielen Dank!
