### ISSUE TITLE
Schrittweite bei LevelBody

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1181]
Man kann zwar die Schrittweite bei Levelbody angeben, aber das Frontend hält sich nicht dran. 

Schrittweite 10 und im Frontend dennoch 1ner Schritte. 

Aktuelle Alpha

Gruss

**Comment by Zefau** [comment]
Im Layout oder Pop-up?

**Comment by ma-gu-16** [comment]
> Im Layout oder Pop-up?

sry. ich benutzte den nur im popup.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.126` passen

**Comment by ma-gu-16** [comment]
klappt.
