### ISSUE TITLE
HistoryGraph - Anzeige

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1187]
Version 3 - 127

Ich habe folgende Einstellung:
<img width="1260" alt="image" src="https://user-images.githubusercontent.com/13101074/142743451-0c9d2062-967c-43e8-934d-4c812b4c2b88.png">

Es werden aber mehr Daten angezeigt als ausgewählt.
<img width="486" alt="image" src="https://user-images.githubusercontent.com/13101074/142743480-b84bd77a-83a8-4bd5-b691-96fe737be144.png">

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.132`

**Comment by AFPass** [comment]
Passt. Danke.
