### ISSUE TITLE
LevelBody: Einheit im Slider-Label berücksichtigen

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1188]
Versuche mit aktuellste alpha die Labels anpassen.

https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/rolllaeden-blind

Bei Einheit sowie anzeige Variante versucht. Scheint nicht zu gehen. 

![image](https://user-images.githubusercontent.com/22169074/142767201-23e8eba5-4d7e-4107-a6f0-250648a2381d.png)

**Comment by Zefau** [comment]
Bitte etwas konkreter. Was genau hast du wie versucht? Und was geht konkret nicht bzw. was ist deine Erwartungshaltung?

Gibt es einen Fehler in der Browser Konsole (F12)?

**Comment by ma-gu-16** [comment]
Hab doch einen Link gepostet, wie der Anleitung zu entnehmen, habe ich Versucht beim LevelBody bei der 0 unten zu schreiben und bei der 100 oben zu schreiben. Alle andern Steps sollten Zahlen bleiben.  

Den Wert habe ich bei Anzeigevariante und Einheit versucht, geht beides nicht. Console Errors gibt es keine. 

Zumindest suggestiert die Anleitung das dies möglich ist und ich glaube ich hatte das auch mal so eingestellt. Aber mit den diversen Updates verloren gegangen.

**Comment by Zefau** [comment]
Die Zahlenreihe unter dem Slider ist nicht veränderlich, falls du diese versuchst zu beeinflussen.

**Comment by ma-gu-16** [comment]
Ok, dachte das beschreibt diese Anleitung. 
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/rolllaeden-blind

Du hast ja schon ein Feature Flag gesetzt , denke das wäre noch Nett diese Möglichkeit. statt einem Label wäre auch ein Icon praktisch. 

Anwendungsfall: 

Bei meinem Slider 0-100 geht es um die Behanghöhe der Rolladen/Storen. Gäste wie auch hin und wieder ich selbst fragen sich dann jedesmal beim ändern was ist offen und was ist geschlossen. 
Das gleiche gilt für die Einstellung der Lamellen bei Storen.  

Gut wäre: 
offen - 10 - 20 -30 -40 -50 -60 -70 - 80- 90- geschlossen 

Ticket kann von mir aus geschlossen werden ;-)

**Comment by mcuiobroker** [comment]
In der Anleitung geht es dort nur um die Einheit.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.128`

**Comment by ma-gu-16** [comment]
fast, das label zieht es raus. 

![image](https://user-images.githubusercontent.com/22169074/142903821-6fe2e63d-c809-480f-acdf-3202e41bcf61.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/997
