### ISSUE TITLE
Widget anlegen nicht möglich, keine Fehlerasgabe

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1189]
Folgendes lässt sich nicht anlegen. Keine Ahnung wieso. 
Praktisch wären sicher auch eine Validierung bzw deren Fehlerausgabe. 

![image](https://user-images.githubusercontent.com/22169074/142768036-940814fe-ca01-4b36-a0c6-8ccd6710841a.png)

**Comment by Zefau** [comment]
Fehler in der Browser Konsole (F12)?

**Comment by Zefau** [comment]
Was für eine Validierung fehlt dir?

**Comment by ma-gu-16** [comment]
Mir ist grad aufgefallen, wenn ich das Modul zuerst Weather wähle und dann wechsel auf Statelist, geht es nicht mehr. 

ich vermute da das Modul Weather ja Pflichtfelder hat, das diese dann nicht wieder gelöscht werden wenn man auf Statelist wechselt. 

Hoffe du kannst es nachvollziehen. Gruss

**Comment by ma-gu-16** [comment]
Mit Validierung bzw Ausgabe meinte ich wieso man nicht "übernehmen" klicken kann, den dort ist nur der mauszeiger bzw der button disabled. 

Aber vermutlich ist das Problem, s.o.

**Comment by Zefau** [comment]
Ah ok

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.128`

**Comment by ma-gu-16** [comment]
jetzt ist es korrekt, danke
