### ISSUE TITLE
Datetime Modul v & h align

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1190]
![image](https://user-images.githubusercontent.com/22169074/142769962-5f75b855-0117-45fa-bfb7-80616d0189b6.png)

![image](https://user-images.githubusercontent.com/22169074/142770024-8c7a0c33-50f1-4c3f-9498-e0fed01185d9.png)

Alignment klappt nicht.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.128`

**Comment by ma-gu-16** [comment]
klappt.
