### ISSUE TITLE
Install bug

### ISSUE THREAD

**Issue by BA2000** [Zefau/ioBroker.jarvis#1191]
Hi,
habe Probleme bei der Installation von Jarvis2. Während der Gerätesuche kommt der rote Bildschirm.
Gruss BA200
![Jarvis_error](https://user-images.githubusercontent.com/62898625/142772009-7843e50e-6c4d-4f7b-8281-67ecf372d4ee.jpg)
0

**Comment by Zefau** [comment]
Bitte auf v3 gehen
