### ISSUE TITLE
Modul Chart - es wird nur ein Wert angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1192]
Im Modul Chart wird nur ein Wert von den historischen Daten angezeigt:
![image](https://user-images.githubusercontent.com/84818934/142773757-2dd98ce6-6aed-4ce3-b6d1-f8576f117bf9.png)
![image](https://user-images.githubusercontent.com/84818934/142773765-180377c8-92e7-4cad-9783-462ff39a6591.png)
![image](https://user-images.githubusercontent.com/84818934/142773839-353dbca2-7070-40d1-8ec8-d615c7362044.png)
![image](https://user-images.githubusercontent.com/84818934/142773785-aff5484b-9f7a-46e7-8f11-b6e5391ef9af.png)

Unter v2 gab es die Möglichkeit dort die Anzahl der Tage auszuwählen?
![image](https://user-images.githubusercontent.com/84818934/142773982-b3dc4d64-5788-430c-820d-5c66156e7dc4.png)

Gibt es für Chart ein Breaking Change? Nur noch für einzelne DPs und deren Einzelwerte nutzbar?
Upgrade v2-> v3 macht aus Chart(v2) ein HistoryGraph(v3).

**Comment by Zefau** [comment]
Das Chart aus v2 entspricht dem HistoryGraph in v3.

Das Chart in v3 ist somit neu und stellt Werte verschiedener Datenpunkte gegenüber. Ein Auslesen der History erfolgt nicht. 

Es wird nur der Datenpunkt-Wert dargestellt.

**Comment by mcuiobroker** [comment]
Kann man bei dem Chart(v3) eine Funktion ergänzen, damit man mehrere Werte aus einem Array in einem Bar-,Pie- oder Circle-Chart darstellen kann?

**Comment by Zefau** [comment]
Nein. Die aktuelle Implementierung nimmt die aktuellen Werte verschiedener Datenpunkte. Als Workaround müsstest du das Array in verschiedene Datenpunkte schreiben.

**Comment by mcuiobroker** [comment]
Chart-Werte schlecht lesbar, nur die ersten zwei werden fett und weiß dargestellt?
![jarvis-Chart-Circle-WerteNichtLesbar](https://user-images.githubusercontent.com/84818934/142777285-e1bac48d-b0b3-47b2-ac3e-6b8e44ba37bd.gif)
Anzeige prozentual zu höchsten Wert?
