### ISSUE TITLE
Chart-Werte schlecht lesbar

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1193]
Chart-Werte schlecht lesbar, nur der Erste und Letzte werden fett und weiß dargestellt?
![jarvis-Chart-Circle-WerteNichtLesbar](https://user-images.githubusercontent.com/84818934/142777285-e1bac48d-b0b3-47b2-ac3e-6b8e44ba37bd.gif)
Anzeige prozentual zu höchstem Wert?

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1192#issuecomment-974887028_

**Comment by mcuiobroker** [comment]
Vielleicht sollte man die Werte rechts in einer Tabelle (Farbe-Wert) darstellen?

**Comment by Zefau** [comment]
Grundsätzlich eine gute Idee, gibt es aber bei echarts nicht, oder?

**Comment by mcuiobroker** [comment]
So ähnlich?
![image](https://user-images.githubusercontent.com/84818934/143646478-b695131e-9832-42f4-a6d4-e80253ee2f08.png)

**Comment by mcuiobroker** [comment]
Die Ringdarstellung von oben ist das eine Bar-Varainte?
![image](https://user-images.githubusercontent.com/84818934/143647672-4f988115-4e5a-46e0-8eb9-c613cb5685b0.png)

**Comment by Zefau** [comment]
Kannst du zum ersten Beitrag den Link posten?

**Comment by mcuiobroker** [comment]
https://echarts.apache.org/examples/en/editor.html?c=pie-nest

**Comment by mcuiobroker** [comment]
https://echarts.apache.org/handbook/en/basics/release-note/5-2-0
![image](https://user-images.githubusercontent.com/84818934/143655598-cedbdfe1-11c1-4ace-bdc8-d60b2d05808d.png)

**Comment by Zefau** [comment]
bringt ja nichts, wenn die Anzeige zu klein ist

**Comment by mcuiobroker** [comment]
bar-width? Dann kann man die Werte besser lesen?
![image](https://user-images.githubusercontent.com/84818934/143657671-308f4f16-35ae-4c4e-8b41-33d6109f274e.png)

**Comment by mcuiobroker** [comment]
Mit Distance und Offset kann die Werte verscheieben
![image](https://user-images.githubusercontent.com/84818934/143657975-ca8f5efd-9d36-4187-a21e-e86683019167.png)

**Comment by mcuiobroker** [comment]
opacity runter bei selected-> dann sieht man die Schrift besser
und Schrift Bold und größer?
![image](https://user-images.githubusercontent.com/84818934/143658774-8deabb81-2567-4940-a00c-51cf4e51b436.png)

**Comment by mcuiobroker** [comment]
```
label: {
      show: true,
      fontWeight: "bold",
      color: "rgba(0, 0, 0, 1)",
      position: "start"
    }
```

**Comment by mcuiobroker** [comment]
Alternativ auch : https://echarts.apache.org/examples/en/editor.html?c=gauge-ring

**Comment by Zefau** [comment]
schau mal mit `v3.0.0-alpha.132`

**Comment by mcuiobroker** [comment]
Das sieht schon besser aus, ich habe nur für meinen Dark.Mode die falsche Farbe gewählt color: "rgba(0, 0, 0, 1)",
Im Dark-Mode müsste es color: "rgba(255, 255, 255, 1)", sein
![image](https://user-images.githubusercontent.com/84818934/143662218-c2729323-331d-4689-aab3-5990b0a8bd79.png)

**Comment by Zefau** [comment]
Falscher Winkel? Was meinst du damit?

**Comment by mcuiobroker** [comment]
Die Ringe beginnen nicht alle bei 90°.

**Comment by Zefau** [comment]
Jo, stimmt. Was passiert, wenn du den Büro Wert ausblendest?

**Comment by mcuiobroker** [comment]
Büro-Wert entfernt, dann wird es schlimmer: (Hatte 2 Stunden Probleme mit Github, du auch?)
![image](https://user-images.githubusercontent.com/84818934/143722367-abfe31a7-9dc7-433c-88d4-bf81a9646321.png)

**Comment by Zefau** [comment]
Jo, Github hat gerade arg Probleme.

Hast du `min` / `max` im Modul definiert?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/143722603-b8fae9f0-9f3a-4469-bbf7-656af249ecdf.png)

**Comment by mcuiobroker** [comment]
Bei nur min = 0: (Max und min stehen falsch rum, also erst max dann min?)
![image](https://user-images.githubusercontent.com/84818934/143722629-4fbf129f-ad6f-4fae-aa7e-d22dcf54dcac.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.1`

**Comment by stony2k** [comment]
Habe mal in der Beta 6 einen kurzen Test gemacht (Circle Chart) und es sieht so aus. Sehr gut lesbar, oder habe ich evtl. die "falschen" Einstellungen gewählt, wollte den Fehler von @mcuiobroker nachstellen.

![image](https://user-images.githubusercontent.com/16526471/144131018-70636387-4334-46d3-9725-180a91f8ab3f.png)

**Comment by mcuiobroker** [comment]
Der Fehler tritt nur dann auf, wenn du keine Min und Max-Werte festlegst.

**Comment by Zefau** [comment]
`min` sollte jetzt raus sein? Daher sollte der Fehler nicht mehr vorkommen.

**Comment by mcuiobroker** [comment]
Hatte ich noch gar nicht gesehen. Tja dann kann man den Fehler auch nicht mehr nachstellen!

**Comment by Zefau** [comment]
Du formulierst das du negativ? :-)

**Comment by tschortschde** [comment]
Kann man den Chart auch um 180° drehen, sodass er von unten über links nach recht dreht? 
Allerdings muss ja dann die Legende nochmals gedreht werden? 
Wie kann man das verwirklichen? 
![image](https://github.com/user-attachments/assets/043ee94b-d0c5-4bd4-a99d-a09d6b28f76a)

**Comment by Zefau** [comment]
@tschortschde Bitte nicht in einem alten Issue fragen, sondern via [Discussions](https://github.com/Zefau/ioBroker.jarvis/discussions) oder im Forum (bitte in einem dedizierten Thread).
