### ISSUE TITLE
Taster / Button Icons

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1195]
Button wie folgt eingestellt: 

Der Anzeigedatenpunkt ist auf false, ich möchte nun das bei false auch das false icon angezeigt wird. scheinbar greift aber  "Icon im JSON Format"

![image](https://user-images.githubusercontent.com/22169074/142905570-acc4d678-a88a-4e3b-971c-cad418a7b2e0.png)

![image](https://user-images.githubusercontent.com/22169074/142905606-851072bf-1bba-46e3-afda-50a64b04a039.png)

**Comment by ma-gu-16** [comment]
Frontend Icon stimmt nicht überein. 

![image](https://user-images.githubusercontent.com/22169074/142906387-8d28a758-750a-445d-a633-caab56ef8340.png)

**Comment by ma-gu-16** [comment]
Ebenso stimmt das Label nicht. sehr strange...

**Comment by ma-gu-16** [comment]
Also irgendwas stimmt hier nicht. Kannst du das nachvollziehen ? 

![image](https://user-images.githubusercontent.com/22169074/142907859-7d2ae6e9-8564-4ced-ab1b-e610aa044d09.png)

![image](https://user-images.githubusercontent.com/22169074/142907963-8401aea0-ef0f-4bf1-a4b2-404f46c10864.png)


```

  "07d412b0-56ab-461e-899b-969075ffdddf": {
    "name": "aktion_licht_an",
    "icon": "",
    "label": "",
    "function": "user",
    "states": {
      "state": {
        "showState": false,
        "action": "scene.0.Licht.Lichter",
        "actionElement": "IconButtonAction",
        "icon": {
          "default": "lightbulb-group"
        },
        "label": "Alle Lichter einschalten",
        "state": "0_userdata.0.taster_jarvis_dummy",
        "bodyElement": null,
        "stateKey": "state",
        "display": "",
        "IconButtonActionConfig": {
          "flat": false,
          "pushButton": false,
          "iconTurnOff": "mdi-power"
        },
        "properties": {
          "initial": true,
          "setOn": true,
          "setOff": true
        }
      }
    },
    "options": {
      "suppressPopup": true
    },
    "attributes": {
      "_created": 1607018175598,
      "_updated": 1607018838179
    },
    "id": "07d412b0-56ab-461e-899b-969075ffdddf",
    "revision": "aa505"
  },
  "ffdc1a9b-7aed-4dd4-bdcb-10228c51b242": {
    "name": "aktion_licht_aus",
    "icon": "",
    "label": "",
    "function": "user",
    "states": {
      "state": {
        "showState": false,
        "action": "scene.0.Licht.Lichter",
        "actionElement": "IconButtonAction",
        "ButtonActionConfig": {
          "label": "ausschalten"
        },
        "icon": {
          "default": "lightbulb-group-off"
        },
        "label": "Alle Lichter ausschalten",
        "bodyElement": null,
        "properties": {
          "initial": false,
          "setOn": false,
          "setOff": false
        },
        "state": "0_userdata.0.taster_jarvis_dummy",
        "stateKey": "state",
        "IconButtonActionConfig": {
          "iconTurnOff": "mdi-power",
          "pushButton": false,
          "flat": false,
          "iconTurnOn": "mdi-power"
        }
      }
    },
    "options": {
      "suppressPopup": true
    },
    "attributes": {
      "_created": 1607018381172,
      "_updated": 1607217426885
    },
    "id": "ffdc1a9b-7aed-4dd4-bdcb-10228c51b242",
    "revision": "c1c6d"
  },
```

**Comment by Bernd9000** [comment]
Und wenn ein zweiter Schalter auf den selben Datenpunkt zugreift funktioniert dieser nicht richtig.

**Comment by Zefau** [comment]
> Und wenn ein zweiter Schalter (mit Datenpunkeigenschaft setOn/setOff) auf den selben Datenpunkt zugreift funktioniert dieser nicht richtig.

Bitte mal Seite komplett refreshen via F5. Besteht der Fehler dann immernoch?

**Comment by Bernd9000** [comment]
v3.0.0-beta.9
Ja, Fehler bleibt, auch beim neustart vom IOBroker und Browser refresh.
Oder mache ich was falsch?

Hier nochmal wie ich getestet habe:
Nur ein Datenpunkt im IOBroker unter "0_userdata.0.Test.Test-Datenpunkt.power"
Datenpunkt ist als string angelegt, Fehler ist aber auch bei anderen Datentypen.
Zwei Taster mit IconButtomAction.
Der erste soll nur "Ein" setzen, der zweite nur "Aus"
Ergebnis: Erster Taster funktioniert, zweiter sendet nur "Ein"
In der Browser Konsole ist kein Fehler


Einfaches Widget mit zwei Taster
![1](https://user-images.githubusercontent.com/77005685/144753615-ec9187f8-5184-4bf9-b231-f0539f970d76.jpg)
r

Taster 1:
![2](https://user-images.githubusercontent.com/77005685/144753630-7ce46b3a-b4c4-49ad-bf4d-eebd3009fcab.jpg)

Taster 2:
![3](https://user-images.githubusercontent.com/77005685/144753636-07752ce1-d76e-41ad-8c13-1ee6445728df.jpg)

**Comment by ma-gu-16** [comment]
> Also irgendwas stimmt hier nicht. Kannst du das nachvollziehen ?
> 
> ![image](https://user-images.githubusercontent.com/22169074/142907859-7d2ae6e9-8564-4ced-ab1b-e610aa044d09.png)
> 
> ![image](https://user-images.githubusercontent.com/22169074/142907963-8401aea0-ef0f-4bf1-a4b2-404f46c10864.png)
> 
> ```
> 
>   "07d412b0-56ab-461e-899b-969075ffdddf": {
>     "name": "aktion_licht_an",
>     "icon": "",
>     "label": "",
>     "function": "user",
>     "states": {
>       "state": {
>         "showState": false,
>         "action": "scene.0.Licht.Lichter",
>         "actionElement": "IconButtonAction",
>         "icon": {
>           "default": "lightbulb-group"
>         },
>         "label": "Alle Lichter einschalten",
>         "state": "0_userdata.0.taster_jarvis_dummy",
>         "bodyElement": null,
>         "stateKey": "state",
>         "display": "",
>         "IconButtonActionConfig": {
>           "flat": false,
>           "pushButton": false,
>           "iconTurnOff": "mdi-power"
>         },
>         "properties": {
>           "initial": true,
>           "setOn": true,
>           "setOff": true
>         }
>       }
>     },
>     "options": {
>       "suppressPopup": true
>     },
>     "attributes": {
>       "_created": 1607018175598,
>       "_updated": 1607018838179
>     },
>     "id": "07d412b0-56ab-461e-899b-969075ffdddf",
>     "revision": "aa505"
>   },
>   "ffdc1a9b-7aed-4dd4-bdcb-10228c51b242": {
>     "name": "aktion_licht_aus",
>     "icon": "",
>     "label": "",
>     "function": "user",
>     "states": {
>       "state": {
>         "showState": false,
>         "action": "scene.0.Licht.Lichter",
>         "actionElement": "IconButtonAction",
>         "ButtonActionConfig": {
>           "label": "ausschalten"
>         },
>         "icon": {
>           "default": "lightbulb-group-off"
>         },
>         "label": "Alle Lichter ausschalten",
>         "bodyElement": null,
>         "properties": {
>           "initial": false,
>           "setOn": false,
>           "setOff": false
>         },
>         "state": "0_userdata.0.taster_jarvis_dummy",
>         "stateKey": "state",
>         "IconButtonActionConfig": {
>           "iconTurnOff": "mdi-power",
>           "pushButton": false,
>           "flat": false,
>           "iconTurnOn": "mdi-power"
>         }
>       }
>     },
>     "options": {
>       "suppressPopup": true
>     },
>     "attributes": {
>       "_created": 1607018381172,
>       "_updated": 1607217426885
>     },
>     "id": "ffdc1a9b-7aed-4dd4-bdcb-10228c51b242",
>     "revision": "c1c6d"
>   },
> ```

Noch immer Buggy, siehe obige Config. Gleiche Labels, gleiche Funktion, obwohl unterschiedlich konfiguriert.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.10`

**Comment by Bernd9000** [comment]
Ich glaube v3.0.0-beta.10 gibt es noch nicht :-)

![Unbenannt](https://user-images.githubusercontent.com/77005685/144931603-254c69b1-3bd6-4540-9774-d76f2c499fff.jpg)

**Comment by Zefau** [comment]
`v3.0.0-beta.10` ist nun oben

**Comment by Bernd9000** [comment]
Ja, jetzt hats geklappt.
Mußte allerdings IOBroker neu starten, Bildschirm war rot:
![Unbenannt](https://user-images.githubusercontent.com/77005685/144933570-7d0779b3-eca7-4377-8c68-37a6a1a90c48.jpg)

Bei mir funktioniert es jetzt.

**Comment by ma-gu-16** [comment]
Scheint zu klappen. BETA 11 :-) freu ich mich. Werde nun alle Taster ändern...
