### ISSUE TITLE
support import of device HmIP-DRSI1

### ISSUE THREAD

**Issue by isi07** [Zefau/ioBroker.jarvis#1196]
Hello Zefau
please add Homematic IP HmIP-DRSI1 device for import.

I list it here as light but maybe more general as socket

```
// lights
"light": {
	"hmip-drsi1": {
		"power": {
			"state": ".2.STATE",
			"action": ".3.STATE"
		}
	}
}
```

Thanks, Christian

![image](https://user-images.githubusercontent.com/65848350/142911819-df5a3e78-bae2-4df3-88df-7f793703c41e.png)
![image](https://user-images.githubusercontent.com/65848350/142911898-639fef9c-75ee-4f77-baba-62fe8ba34ebb.png)
![image](https://user-images.githubusercontent.com/65848350/142911984-68631d35-95be-440a-a8da-991c9589fbba.png)

**Comment by Zefau** [comment]
@isi07 Gerät mit `v3.0.0-alpha.131` hinzugefügt

**Comment by isi07** [comment]
Danke. hab das Ticket aus versehen geschlossen. Hoffe, das verursacht keine Probleme.

**Comment by Zefau** [comment]
Ne, passt, wenn es für dich passt.
