### ISSUE TITLE
snake-Effekt-Problem

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1198]
Was mir noch aufgefallen ist, bei dem neuen "snake-Effekt", wird dieser nicht mehr korrekt dargestellt, nach der Konvertierung. Das Bild werde ich über die App versuchen hinzuzufügen.
Sonst, wie gesagt echt Klasse gemacht.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/814#issuecomment-890407357_
![image](https://user-images.githubusercontent.com/84818934/143042724-9ea707cf-13d3-4b88-9502-93cf8e84c7a3.png)

Das Problem hängt mit einem Eintrag zusammen
![image](https://user-images.githubusercontent.com/84818934/143042115-8e3e3665-b777-4206-a3c0-78249a37079e.png)
Warum ist der drin? Kann man den wieder raus nehmen?
Wenn ich das rausnehme, sieht wieder alles normal aus
![image](https://user-images.githubusercontent.com/84818934/143042992-0788dec8-0d7b-4f76-a697-db31bf9ab7d2.png)
Vielleicht hilft das ein wenig?
![image](https://user-images.githubusercontent.com/84818934/143044354-1ee53fb3-ece4-4ac5-9346-fcb8a65692f1.png)

Hab in der CSS-Styles die margin raus genommen:
```
p {
	margin: 0px !important;
}
```

**Comment by mcuiobroker** [comment]
Darum wolltest du Dich eigentlich in der beta kümmern. 
Da es einige einsetzen, führt es nach dem Update zum Fehler?

**Comment by Zefau** [comment]
Einfach bei deinen Styles (https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/beispiele/styles/effekte/snake-laufende-umrahmung) Folgendes aufnehmen:
```
.card p {
	margin: 0;
}
```

**Comment by mcuiobroker** [comment]
Kann ich machen, aber warum ist das drin?
Kann es so nicht im Programm geändert werden?

**Comment by Zefau** [comment]
Der Snake-Effekt erfordert scheinbar viel CSS. Da stört das nicht, oder? Warum sollte ich für den Effekt das Programm ändern? Wer weiß, worauf sich das überall auswirkt.

**Comment by mcuiobroker** [comment]
ok
