### ISSUE TITLE
On value of dimmable lights

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#12]
In jarvis it is possible to turn on dimmable lights without selecting the brightness level. By default the light is then turned on with 100%. It would be great if you could implement an option to set the on value.

**Comment by Zefau** [comment]
Has been added with v0.1.3 and can be defined in the `jarvis` options by defining `defaultValue`:

![image](https://user-images.githubusercontent.com/14368811/77861300-53db1300-7214-11ea-9e3e-5f2a24ac5ba4.png)

Could you please test and verify? Thanks

**Comment by braindead1** [comment]
After installing v0.1.3 it is generally working, but not described as on the screenshot above. Besides that there is a minor bug, that needs to be fixed to get it to work.

* After clicking on "Add new option" and starting to type a "d" you can select "defaultValue". The option is then added and saved as "defaultvalue". This will not work and you have to manually change the JSON to "defaultValue" to get it to work.
* My dimmer was configured as yours with a power state and a level state. With this configuration it does not work, no matter if "defaultValue" or "defaultvalue". I had to delete the power state to get it to work.

**Comment by braindead1** [comment]
Another thing I noticed while testing: Clicking on "An" to switch on a group of lights does not take the "defaultValue" of dimmers into account. Instead dimmers are set to 100%.

![dimmer](https://user-images.githubusercontent.com/2136249/77882269-ef927080-7260-11ea-81dd-6f8d71d90565.png)

**Comment by Zefau** [comment]
> After clicking on "Add new option" and starting to type a "d" you can select "defaultValue". The option is then added and saved as "defaultvalue". This will not work and you have to manually change the JSON to "defaultValue" to get it to work.

This is will be fixed

>My dimmer was configured as yours with a power state and a level state. With this configuration it does not work, no matter if "defaultValue" or "defaultvalue". I had to delete the power state to get it to work.

Is the normal behaviour. If a `power` state is defined, it will be used and triggers the respective datapoint in the ioBroker backend. If `power` is omitted, jarvis will fallback to `level` if provided. Due to this though, `defaultValue` will only be applied when `power` is not given.

> Another thing I noticed while testing: Clicking on "An" to switch on a group of lights does not take the "defaultValue" of dimmers into account. Instead dimmers are set to 100%.
Will be added

**Comment by Zefau** [comment]
Please check no. 1 and 3 if this has been fixed by `v0.1.4`, thanks.

**Comment by braindead1** [comment]
In v0.1.4 no. 3 is working as expected.

No. 1 needs some rework. After clicking on "Add new option" and entering "defaultValue", it is not shown in the UI, but it is available in the JSON under "Raw Editor Devices".

**Comment by Zefau** [comment]
Could you try again installing from Github? Version stays the same (`v0.1.4`) but no. 1 should work now.

**Comment by braindead1** [comment]
"defaultValue" is shown in the UI, but in the JSON it is available as string. How does Jarvis know if it has to be stored as number or string? Is there a build in conversion?

**Comment by Zefau** [comment]
Is it still not working correctly? There is no conversation to a number. It is treated as string all the way I think.

**Comment by braindead1** [comment]
I can confirm, that "defaultValue" is working correctly, although it is stored as string in the JSON.

**Comment by Zefau** [comment]
I probably will rename it in future version to something like `defaultLevelValue`, because it is addressing the `level` state only (at least at the moment). For now it is working so I'll close this issue.

**Comment by braindead1** [comment]
Just one comment: You should consider to make it consistent to other options, where it is possible to configure more than one state. There may be cases were a device has more than one level e.g. brightness and light color.

**Comment by Zefau** [comment]
Due to all our discussion, I will evaluate to move all state related options from `jarvis` to `states` (to the specific key). This also removes complexity from the options, which is a lot of nesting at the moment.

**Comment by braindead1** [comment]
Sorry for being so annoying. :-) I really appreciate all the affort you put into this project.

**Comment by Zefau** [comment]
Due to all changes, this feature got lost on the way.

**Comment by Zefau** [comment]
added with `1.1.0-beta.32`

**Comment by Zefau** [comment]
@braindead1 Could you test this? This is a new option in the Widget config.

**Comment by Zefau** [comment]
@braindead1 probier bitte nochmal die `v1.1.0-beta.99`.

Ab jetzt wird `level` im Gerät (im neuen Feld `Datenpunkt Eigenschaften`) definiert (nachfolgendes Beispiel dimmt damit auf `10` statt voll auf):
![image](https://user-images.githubusercontent.com/14368811/99114064-86454f00-25f0-11eb-82a1-aad660dc8fce.png)

**Comment by braindead1** [comment]
Mit `v1.1.0-beta.99` funktioniert es wie beschrieben.
