### ISSUE TITLE
Picture/Videostream Widget

### ISSUE THREAD

**Issue by mla4ger** [Zefau/ioBroker.jarvis#120]
a widget without Icons or widgetname. The videostream should have the same size like the widget (shown all over the widget)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/116

**Comment by Zefau** [comment]
Widget fullscreen option added with `1.1.0-beta.11`, see https://github.com/Zefau/ioBroker.jarvis/issues/116
