### ISSUE TITLE
Seltener Effekt : Icon, Value und Einheit falsch

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1201]
`v3.0.0-alpha.129`
Manchmal tritt ein komischer Effekt auf.
Das Icon, der Wert und die Einheit werden falsch dargestellt.
![image](https://user-images.githubusercontent.com/84818934/143063749-5a4e3a79-60c5-4175-b122-a53e8ad875c5.png)
![jarvis-icon falsch](https://user-images.githubusercontent.com/84818934/143064748-a1bc6a9c-456b-4d41-a873-942cb17781bf.gif)

Tritt anscheinend immer nach der Bearbeitung der Konfiguration auf, unabhängig davon, ob man was geändert hat.
Zunächst wird der richtige Wert, Icon usw angezeigt, aber nach ca 0.5 Sekunden ist es der falsche Wert,Icon usw.

**Comment by Zefau** [comment]
Liegt das ggf. daran, dass derselbe ioBroker-Datenpunkt 2x in einem Gerät verwendet ist?

**Comment by mcuiobroker** [comment]
Nein. In dem Gerät sind 4 unterschiedliche iobroker DPs.
Layout
![image](https://user-images.githubusercontent.com/84818934/143949744-2049beae-417f-4c55-b151-7c82d7ebd454.png)
Gerät - der DP wo es auftritt:
![image](https://user-images.githubusercontent.com/84818934/143949848-bc90185a-568a-49e7-a87d-ce4180736258.png)

**Comment by Zefau** [comment]
Also ich konnte es bei mir beobachten, dass das Icon sich im Layout ändert, wenn ich das Popup geöffnet habe. 

Du sagst der Effekt tritt nach der Konfiguration auf. Vor der Konfiguration passiert das nicht?
Gibt es sonst Hinweise, wie es reproduzierbar wäre?

**Comment by mcuiobroker** [comment]
Reproduzierbar ist es. Immer wenn ich in die Konfig gehe und nichts mache und speichere, wird dann die Seite korrekt angezeigt. Eine halbe Sekunde später ist der DP mit den Icon plötzlich umgestellt auf das "Sonstige"-Icon, der Wert und die Einheit sind auch falsch.

**Comment by mcuiobroker** [comment]
Dergleiche ist auch bei einem anderen Geräte-DP. Jetzt habe ich mal in der Konfig auf einen anderen TAB geklickt und gespeichert. Jetzt ist mal der eine DP falsch und mal der andere. Echt komisch.

**Comment by mcuiobroker** [comment]
Auf einer anderen TAB-Seite habe ich den Effekt gehabt, dass er ein falsches Icon durch die Aktualisierung vom Wert korrigert hat.

**Comment by mcuiobroker** [comment]
Der Effekt tritt bei allen TAB-Seiten mit der Kombination auf? HUE und Lichtlevel
![image](https://user-images.githubusercontent.com/84818934/143952893-07489518-7eb3-4659-bc8c-4088c3946d7f.png)

**Comment by RkcCorian** [comment]
Moin Zusammen,
bin mir nicht sicher, ob mein Fehlerbild auch zu diesem hier passt... Nach "einiger" (kann nicht sagen wie lange genau) Zeit wird anstelle der konfigurierten Farbe die Primärfarbe angezeigt. Sobald ich das Popup öffne, oder den DP in der Oberfläche anklicke kommt sofort wieder die richtige Farbe (Grau: Licht aus, Gelb: Licht an, Fehlerbild: Blau, sollte eigentlich bei Lampen bei mir nie sichtbar sein).

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.10`

**Comment by RkcCorian** [comment]
Werde mein Fehlerbild mal beobachten. Schwierig zu sagen, da bei mir sporadisch. Vielleicht kann @mcuiobroker mehr dazu sagen 🙈

**Comment by mcuiobroker** [comment]
Leider passt es nocht nicht:
![image](https://user-images.githubusercontent.com/84818934/144931638-8455e202-bf13-4e23-922f-8d86fa6aa719.png)

**Comment by RkcCorian** [comment]
Mir ist gerade aufgefallen, dass ich gar nicht die ```beta-10``` habe, sondern die ```beta-9```. Im Browser zeigt er auch noch die 9 an...

**Comment by mcuiobroker** [comment]
Zeigt bei mir auch 9 an obwohl ein Update gelaufen ist:
![image](https://user-images.githubusercontent.com/84818934/144932207-fbcf9948-3674-4991-a1b8-25bae600ee7c.png)

**Comment by Zefau** [comment]
`v3.0.0-beta.10` ist nun oben

**Comment by RkcCorian** [comment]
Jetzt ist es verfügbar

**Comment by Zefau** [comment]
HistoryGraph ist allerdings defekt, bitte aufpassen

**Comment by RkcCorian** [comment]
Hmmm... nicht nur der. JARVIS ist kurz sichtbar, dann kommt...
![image](https://user-images.githubusercontent.com/79741077/144933269-4c68f7f6-bf48-42c2-8585-15dc7f692678.png)

**Comment by Bernd9000** [comment]
IOBroker neu starten, hatte ich auch

**Comment by Zefau** [comment]
ggf. genügt ein Upload des Adapters?

**Comment by RkcCorian** [comment]
*$%§%&... hab gerade Backup wieder hergestellt... dann auf ein Neues 🙈

**Comment by RkcCorian** [comment]
Hab's nochmal probiert, ging. Allerdings muss ich dennoch wieder zurück...
![image](https://user-images.githubusercontent.com/79741077/144935177-65c5d25f-8baa-4359-8720-fc2808d5a22e.png)
![image](https://user-images.githubusercontent.com/79741077/144935231-e1de957a-93e6-4141-9055-8fd4bf87f84d.png)

**Comment by Zefau** [comment]
Ist das jeweils der Geräte-Name oder was ist das, dass er überall das gleiche anzeigt?

**Comment by RkcCorian** [comment]
Ja, so sieht es noch mit beta-8 aus... :-)
![image](https://user-images.githubusercontent.com/79741077/144936466-7595d7ba-2410-4897-927d-aba86d751a2f.png)

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.11`
Jetzt fehlt einiges:
![image](https://user-images.githubusercontent.com/84818934/144938823-28a2401f-772d-486c-9162-7cea479e60e1.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.12`

**Comment by mcuiobroker** [comment]
Bei sieht es gut aus.

**Comment by Zefau** [comment]
Und bezogen auf das ursprüngliche Problem? :-)

**Comment by mcuiobroker** [comment]
Hatte gerade wieder ein komisches Verhalten. Er hatte plötzlich keine Werte mehr in der Anzeige?
Bezogen auf das ursprüngliche Problem ist es behoben.

**Comment by RkcCorian** [comment]
Gleiche Problem tritt bei mir nach einiger Zeit ebenfalls auf. Daten werden nicht angezeigt

**Comment by Zefau** [comment]
Wie bekomme ich da denn nachgestellt? :-\

**Comment by RkcCorian** [comment]
Bei mir trat der Fehler auf dem Tablet nach einiger Zeit (glaub ein paar Minuten) auf. Direkt nach dem Refresh nicht. Daher denke ich Du musst das Fenster "lange genug" offen lassen.
Auf dem Produktivsystem bin ich noch auf der beta vor dem Verhalten...

**Comment by mcuiobroker** [comment]
Zum Beispiel: Konfiguration nur abbrechen. Dann durch die TABs langsam klicken:
![image](https://user-images.githubusercontent.com/84818934/145465304-1d32ac71-19e5-465f-8e71-4d375f7d1dc3.png)

**Comment by Zefau** [comment]
Funktioniert trotzdem bei mir. oh man :-\

**Comment by mcuiobroker** [comment]
Vermute es hat hiermit was zu tun?
![image](https://user-images.githubusercontent.com/84818934/145470083-4e3ca824-239b-4cc3-85e7-6d8eb5c7276f.png)

**Comment by Zefau** [comment]
hö? Da macht er keinen reconnect? Steht danach nichts mit reconnected!?

Hast du auch Fehler im klassischen ioBroker Log? Was kommt, wenn du der URL folgst die dort eingeblendet ist?

**Comment by Zefau** [comment]
@RkcCorian hast du das gleiche Fehlerbild?

**Comment by mcuiobroker** [comment]
Nee, danach stand dort kein reconnect. Ich schau nochmal.

**Comment by RkcCorian** [comment]
Bei mir waren tlw. die Labels, als auch Werte nicht mehr da. Als Symbole wurden nicht mehr die des DP genommen, sondern vom Gerät. So wie auch im Forum von anderen Benutzern berichtet.
Muss gerade nach dem Kleinen schauen, ich kann später im Testsystem nochmal den Fehler nachstellen... welche Infos brauchst Du dann?

**Comment by Zefau** [comment]
Ich kann das Fehlerbild so überhaupt nicht nachstellen. Bei mir funktioniert alles problemlos. Kein Plan warum :-(

Also alles was hilft dem Fehler näher zu kommen.

**Comment by mcuiobroker** [comment]
Scheint etwas mit der CSS-Änderung allgemein zu tun zu haben.
Wenn ich den Eintrag raus nehme und speichere sind die Daten auf anderen TABs weg.

**Comment by Zefau** [comment]
schaut nochmal bitte mit `v3.0.0-beta.13`

**Comment by mcuiobroker** [comment]
Obwohl er nach dem Update ein Connect aufgebaut hat er die Seiten nicht aktualisert,
![image](https://user-images.githubusercontent.com/84818934/145488566-c6c5fe8c-888c-46aa-8d61-316c8711d302.png)
![image](https://user-images.githubusercontent.com/84818934/145488589-f4a21768-9157-4dad-a784-b13be83c0939.png)
Ich habe nocht nicht mit F5 akutalisiert.
Beobachte jetzt nach F5.

**Comment by RkcCorian** [comment]
Bei einem Popup wurde das Label geladen und direkt danach wieder zurück gesetzt auf den "nackten" DP Namen...

**Comment by mcuiobroker** [comment]
Jetzt kommt nach der Speicherung aus der CSS direkt der Hinweis auf falsche DPs. Warum nur wenn man vorher auf CSS-TAB war?
![image](https://user-images.githubusercontent.com/84818934/145496940-6cb90198-cbd2-444e-b5ee-fe43d00d80ed.png)

**Comment by RkcCorian** [comment]
Gleiche Problem mit ```beta-13```. Gegenüber @mcuiobroker verändere ich nichts an der Konfig, geschweige den CSS. Ich warte "nur"...

![image](https://user-images.githubusercontent.com/79741077/145586617-eba5a453-1591-419c-99cb-8721d6b25743.png)

![image](https://user-images.githubusercontent.com/79741077/145586901-514c18c8-4c95-4013-b31e-6fe96f357261.png)

**Comment by RkcCorian** [comment]
So sieht es richtig aus mit ```beta-8```
![image](https://user-images.githubusercontent.com/79741077/145587667-02d53c85-c5cd-4654-8285-ceda34140df0.png)

**Comment by Zefau** [comment]
schaut mal bitte mit `v3.0.0-beta.14`

**Comment by RkcCorian** [comment]
```beta-14``` konnte den Fehler nicht beobachten. Hab JARVIS 30 Minuten in Ruhe gelassen (Tablet an der Wand) und dann geschaut. Vorher war der Fehler dann immer "irgendwo" sichtbar.
Ist leider kein Beweis, aber immerhin.... mal schauen ob es woanders auftritt...

**Comment by Zefau** [comment]
Beruhigend :-)

**Comment by mcuiobroker** [comment]
Mit `v3.0.0-beta.18` habe ich das Problem mit "Nicht anzeigen" der Werte bei "nur" `abbrechen` aus der Konfig.
![image](https://user-images.githubusercontent.com/84818934/146991199-7477c6c9-c604-4dc6-802e-eab6adc01f2b.png)
Nutze ich `Speichern & Zurück` werden nach 1 Sekunde die Werte geladen.

**Comment by Zefau** [comment]
ist inzwischen schon stark off-topic

schau mal bitte, ob das mit ` v3.0.0-beta.19` immer noch so ist, sonst mach ein neues Issue auf

**Comment by Zefau** [comment]
Problem besteht noch, konnte es bei mir gerade nachstellen. Ich kümmer mich drum.
