### ISSUE TITLE
Widgets werden nach Refresh zunächst verkleinert dargestellt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1202]
`v3.0.0-alpha.129`
Alle Widgets werden nach Refresh zunächst verkleinert dargestellt:
![jarvis-widget-geschrumpft](https://user-images.githubusercontent.com/84818934/143065711-5c8df965-2676-4e52-ba42-e074a52944b8.gif)

**Comment by Zefau** [comment]
beim initialen Laden skalieren die Inhalte auf die Widget-Größe. Da diese erst mit dem Laden bekannt ist, entsteht dieser Effekt.

**Comment by mcuiobroker** [comment]
War aber vorher nicht so intensiv? Sonst wäre es ja schon aufgefallen?

**Comment by Zefau** [comment]
ah, ok, ist es mit der letzten alpha so stark?

**Comment by mcuiobroker** [comment]
Kann auch sein , dass es vorher schneller war und man hat es nicht so wahrgenommen?

**Comment by Zefau** [comment]
wie sieht es mit `v3.0.0-alpha.130` aus?

**Comment by mcuiobroker** [comment]
Das sieht sehr gut aus!. Danke.
