### ISSUE TITLE
v3 iOS shortcut icon

### ISSUE THREAD

**Issue by danieltrapp** [Zefau/ioBroker.jarvis#1203]
Hi,
wenn ich im Safari in iOS ein Shortcut von Jarvis auf dem Home-Bildschirm erstellen will, wird nicht das Favicon als icon verwendet, sondern ein screenshot der Seite. Unter Jarvis 2.x wurde das favicon verwendet. 

<img width="1180" alt="fav" src="https://user-images.githubusercontent.com/25320876/143106612-11b4a0d7-b994-4777-b240-03d04925874e.png">

![IMG_0004](https://user-images.githubusercontent.com/25320876/143107488-6992d4ce-03d0-4a1d-9b27-546148893926.png)

iOS 15.0.2
Jarvis v3.0.0-alpha.119

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.132`

**Comment by danieltrapp** [comment]
Wie ist die installations url für die v3.0.0-alpha.132? 
Mit https://github.com/Zefau/ioBroker.jarvis.git wird mir ja die v3.0.0-beta.4 installiert

**Comment by danieltrapp** [comment]
Funktioniert leider nicht

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.0.0-beta.9`

**Comment by danieltrapp** [comment]
Nein, klappt leider nicht. Habe auf mehreren Geräten Browserdaten gelöscht und ausprobiert.

**Comment by Zefau** [comment]
Bist du sicher auf beta.9 ? ;-)

Laut Google müsste es mit `<link rel="apple-touch-icon" href="icon-192x192.png">` im Quellcode funktionieren.
Kannst du mal schauen, ob das bei dir drin ist?

Rechtsklick --> Inspect und dann mal nach `apple-touch-icon` suchen.

**Comment by danieltrapp** [comment]
Oh Sorry, mein Fehler. Hatte beta.8 installiert. Mit der beta.9 funktioniert es. Vielen Dank!

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/729023

**Comment by Zefau** [comment]
@danieltrapp kannst du mal mit 3.0.0 bzw. 3.0.1 schauen, ob das noch geht? Laut https://forum.iobroker.net/post/729023 scheint es wieder defekt.

**Comment by danieltrapp** [comment]
v 3.0.1 funktioniert. (iOS 15.2)

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/730298
