### ISSUE TITLE
jarvis Crash

### ISSUE THREAD

**Issue by dentro-git** [Zefau/ioBroker.jarvis#1204]
Wenn ich ein neues Gerät per Hand anlegen will kommt die Meldung wann immer ich den Datenpunkt verknüpfen will.
Also sobald ich hier auf den Schraubenschlüssel drücke 
![image](https://user-images.githubusercontent.com/77006779/143274482-d9caa1d0-9066-4553-8b71-d53a2abd2ba8.png)

Es ist dabei egal ob ich
- einen Datenpunkt in einem neuen Gerät anlege
- einen Datenpunkt zu einem bestehenden Gerät hinzufüge
- einen vorhandenen Datenpunkt bearbeiten will

das einzige was ich kürzlich gemacht habe ist die Node.js Version zu aktualisieren
![image](https://user-images.githubusercontent.com/77006779/143275329-d5c8a288-f0f9-4d3c-81f8-b3c5fd669ee8.png)

Ich nutze aktuell die Version 2.2.1 des Jarvis Adapters:
![image](https://user-images.githubusercontent.com/77006779/143274828-b6d0bda2-094e-4db2-a492-4ae1b1ac6c8e.png)

![image](https://user-images.githubusercontent.com/77006779/143274996-c49087fd-05e3-48c4-93ba-e376d00ad145.png)

**Comment by mcuiobroker** [comment]
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/5148
Auf v2.2.3 oder v3 gehen.
