### ISSUE TITLE
Flackern bei Wertdarstellung im Popup

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1205]
`v3.0.0-alpha.129`
![image](https://user-images.githubusercontent.com/84818934/143287416-49ac688f-5617-4742-94db-f9e528b91f0e.png)
Dort sollte eigentlich 14 Sek. stehen. Da er das nicht immer hinbekommt, fängt es an zu flackern.
![jarvis-flackern bei Wertdarstellung](https://user-images.githubusercontent.com/84818934/143287541-cf7d9cd7-2d8a-4e1a-a431-53a94891bf97.gif)

**Comment by Zefau** [comment]
Ist das ein Countdown bei dem sich der Wert ändert?

**Comment by mcuiobroker** [comment]
Ja.

**Comment by mcuiobroker** [comment]
Scheint mit `v3.0.0-alpha.130` auch behoben zu sein. Hattest du da was gemacht?

**Comment by Zefau** [comment]
Nein, eigentlich nicht.

**Comment by mcuiobroker** [comment]
Dann werde ich das mal weiter beobachten. Wie gesagt zurzeit ok. Ich mach den Issue mal zu, wenn es wieder auftaucht, schreib ich wieder hier rein.
