### ISSUE TITLE
LastChangeBody-Zeitwerte werden nicht aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1206]
`v3.0.0-alpha.129`
Die Zeitwerte vom LastChangeBody werden nicht aktualisiert.
Erst nach F5 wieder aktuell.
![jarvis-ZeitwertehabenKeinUpdatemehr](https://user-images.githubusercontent.com/84818934/143297286-08826ffe-4bf3-4211-80eb-c602ad693889.gif)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.130` behoben sein

**Comment by mcuiobroker** [comment]
Sieht auch sehr gut. Danke.
