### ISSUE TITLE
Lange Ladezeit der Icons von der 1. Seite

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1207]
War auch schon vor `v3.0.0-alpha.129`
#1003 
Ist so ähnlich wieder da.

https://user-images.githubusercontent.com/84818934/143323115-432eff6d-8fac-4287-b4f3-919f2fa88667.mp4

**Comment by RkcCorian** [comment]
So sieht es bei mir auch aus, insb. bei den DPs, welche ALIAS sind. Ich hoffe es gibt doch eine Lösung :-)

**Comment by Bernd9000** [comment]
Seit v3.0.0-beta.14 hab ich das jetzt auch, und nicht nur bei der ersten Seite.
Auch im Popup tacht jetzt bei sehr vielen Geräten das "mdi-spin" auf.

**Comment by Zefau** [comment]
@Bernd9000 mit `v3.0.0-beta.15` auch noch?

**Comment by Bernd9000** [comment]
Bei einigen Datenpunkten wird bei mir das Icon erst dann richtig angezeigt wenn der Datenpunkt vom Gerät selbst aktualisiert wird. Es scheint so als wenn jarvis beim ersten Aufruf einer Seite auf eine Aktualisierung wartet, die nicht kommt

**Comment by Bernd9000** [comment]
Ja, mit v3.0.0-beta.15 ist es bei mir schlimmer geworden

**Comment by Bernd9000** [comment]
Hier z.B. ein Widget in dem Ich mir den Online Status von allen Geräten anzeigen lasse.
Das läßt sich irgendwie keinem Gerät zuordnen, mal ist es das eine Gerät, mal das andere.

![Bild2](https://user-images.githubusercontent.com/77005685/145784626-1a3ae05b-78d4-4a07-a2b7-a11009735980.jpg)

**Comment by Bernd9000** [comment]
Hab mal weiter getestet....
Bei einigen Geräten konnte ich noch feststellen das es an fehlende oder falsche Werte beim Body State oder Body Element liegt.
Danach waren die Icons und Werte bei den Geräten sofort da.

Bei den Geräten mit Dimmer ist es so das wenn ich beim Body State statt "Level" zum Test "status" einstelle ebenfalls die Icons und Werte sofort da sind.Nur dann fehlt der Slider.

**Comment by Bernd9000** [comment]
Noch eine Auffälligkeit bei meinen Shelly Dimmern.
Gehe ich in die jarvis Konfiguration OHNE etwas zu verändern und drücke nur "speichern" dann werden die Icons und Werte im Popup sofort richtig angezeigt und im Widget nach drücken von F5.

**Comment by Zefau** [comment]
Kannst du mal von einem Gerät das JSON posten sowie auch das Layout-JSON dazu?

**Comment by Bernd9000** [comment]
Okay, hab ein Test Gerät (Shelly Dimmer 2) mit jarvis importiert und dann so eingerichtet wie ich es haben wollte.
Verändert habe ich die Datenpunkte "reachability" und "power"
Öffnet man hier das Popup wird Datenpunkt "reachability" nicht angezeigt und das Icon fehlt.

![1](https://user-images.githubusercontent.com/77005685/146093125-e6bc0b6e-1e3f-4d39-96b4-f777f1bcb5ba.jpg)
![2](https://user-images.githubusercontent.com/77005685/146093134-0ef067a1-6461-409c-aec9-bde67e4a6fbe.jpg)


Das Icon und der Wert tauchen erst auf wenn ich die jarvis Konfiguration öffne und speicher:

![3](https://user-images.githubusercontent.com/77005685/146094212-66360a86-b621-4f46-8d19-4675b55912cf.jpg)

JSON Layout:

{
        "icon": "mdi-tab",
        "title": "Test3",
        "id": "de55ae85-286c-4043-9682-d02742f9178a",
        "revision": "723b5",
        "widgetsDesktop": [
          {
            "x": 0,
            "y": 0,
            "w": 5,
            "h": 5,
            "i": "bcc3d0ba-60ac-4534-b976-4701e5c002e3",
            "moved": false,
            "items": [
              "7ca56e1c-e21f-46d4-87de-97148f76abd4"
            ]
          }
        ],
        "widgetsSmartphone": [],
        "iconColor": "#ff0000"
      }
    ],





Json Gerät:

"shelly-dimmer-reserve_a4876": {
    "name": "Shelly-Dimmer-Reserve",
    "icon": "",
    "label": "",
    "function": "light",
    "states": {
      "power": {
        "state": "shelly.0.SHDM-2#3C6105E4A16C#1.lights.Switch",
        "action": "shelly.0.SHDM-2#3C6105E4A16C#1.lights.Switch",
        "actionElement": "SwitchAction",
        "stateKey": "power",
        "stateStyle": "",
        "display": {
          "true": "An",
          "false": "Aus"
        },
        "icon": {
          "{shelly.0.SHDM-2#3C6105E4A16C#1.online}=false": "lightbulb-on blink",
          "true": "lightbulb-on",
          "false": "lightbulb-off-outline"
        },
        "iconStyle": {
          "default": {
            "color": "#00F"
          },
          "{shelly.0.SHDM-2#3C6105E4A16C#1.online}=false": {
            "color": "#FF0"
          },
          "true": {
            "color": "#0F0"
          },
          "false": {
            "color": "#F00"
          }
        }
      },
      "firmware": {
        "state": "shelly.0.SHDM-2#3C6105E4A16C#1.firmware",
        "action": "shelly.0.SHDM-2#3C6105E4A16C#1.firmwareupdate",
        "actionElement": "IconButtonAction",
        "stateKey": "firmware"
      },
      "temperature": {
        "state": "shelly.0.SHDM-2#3C6105E4A16C#1.temperatureC",
        "stateKey": "temperature"
      },
      "version": {
        "state": "shelly.0.SHDM-2#3C6105E4A16C#1.version",
        "stateKey": "version"
      },
      "reachability": {
        "state": "shelly.0.SHDM-2#3C6105E4A16C#1.online",
        "stateKey": "reachability",
        "display": {
          "true": "Online",
          "false": "----------"
        },
        "icon": {
          "default": "default",
          "false": "wifi-alert blink",
          "true": "wifi"
        },
        "iconStyle": {
          "default": {
            "color": "#00F"
          },
          "false": {
            "color": "#F00"
          },
          "true": {
            "color": "#0F0"
          }
        }
      },
      "level": {
        "state": "shelly.0.SHDM-2#3C6105E4A16C#1.lights.brightness",
        "action": "shelly.0.SHDM-2#3C6105E4A16C#1.lights.brightness",
        "actionElement": "",
        "bodyElement": "LevelBody",
        "stateKey": "level"
      },
      "powerCounter": {
        "state": "shelly.0.SHDM-2#3C6105E4A16C#1.lights.Energy",
        "unit": " Wh",
        "stateKey": "powerCounter"
      },
      "powerMeter": {
        "state": "shelly.0.SHDM-2#3C6105E4A16C#1.lights.Power",
        "unit": " W",
        "stateKey": "powerMeter"
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Shelly",
        "namespace": "shelly"
      }
    },
    "id": "shelly-dimmer-reserve_a4876",
    "revision": "ae5fe"
  }

**Comment by Bernd9000** [comment]
Und noch eine Merkwürdigkeit.....
Speichere ich eine Widget Seite (mit fehlerhaften Icons oder Werten) unter Lesezeichen im Firefox Browser ab und starte diese Seite durch klick auf das Lesezeichen direkt, sind alle Icons sofort da.
Ob der IOBroker Web Adapter vielleicht fehlerhaft ist ? Der wurde in letzter Zeit ja auch mehrmals aktualisiert.

**Comment by Zefau** [comment]
Die Icons werden von Iconify geladen. Also per extra Request. Insofern dauert es länger. Das ist meine Vermutung.

Mit der letzten beta habe ich Iconify für Material Design Icons abgeschaltet. Also die sollten nun direkt angezeigt werden, da lokal. Ggf. ist deine Beobachtung mit dem Lesezeichen dem zuzuordnen?

Dass das Icon initial lädt ist notwendig, da dieses ja abhängig vom Wert des Datenpunkts ist und der Datenpunkt-Wert erst geladen werden muss um festzustellen, was für ein Icon überhaupt angezeigt werden soll.

**Comment by Bernd9000** [comment]
>  Ggf. ist deine Beobachtung mit dem Lesezeichen dem zuzuordnen?
Ja, ich denke schon.
Rufe ich das Widget aber vom jarvis Menü auf kommen die Icons nicht.
Da stellt sich mir die Frage was läuft da anders.

Jedenfalls hab ich zum Test nochmal die alten Versionen vom IOBroker web und Socket.io Adapter geladen.
Ohne Erfolg, daran liegt es auch nicht.

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.17`
Ist auf dem Handy nachwievor so wie im ersten Post.

**Comment by Bernd9000** [comment]
Im debug Modus im jarvis Modul habe ich einige Fehler bei den Verbindungen:
Connection: Origin detected with http://xxx.xxx.xxx.xxx:8082...
Könnte das damit zu tun haben ?

**Comment by Bernd9000** [comment]
@Zefau
Könntest Du nicht ein Mouseover für die mdi-spin Icons einrichten wie bei den gelben Dreiecken das man ablesen kann was hier falsch läuft ?
![Unbenannt](https://user-images.githubusercontent.com/77005685/146645404-8a4156b6-4cf2-4811-8843-bf9a8daf8da8.jpg)

**Comment by mh-hdl** [comment]
...wenn es bzgl. des Problems hilft:

Ich habe das Problem mit den Icons (!!!inkl. Status der einzelnen DP!!!), wenn ich auf Jarvis per VPN (von /über Fritzbox, Android- Handy mit VPNcilla) zugreifen will. Im normalen WLAN läuft es mit den Icons normal. Außer die Sonnenauf- und untergangszeiten im Widget -Date / Time-. Die brauchen immer Zeit (Lade-Circle-Anzeige ca. 5-7s).

**Comment by RkcCorian** [comment]
> Außer die Sonnenauf- und untergangszeiten im Widget -Date / Time-. Die brauchen immer Zeit (Lade-Circle-Anzeige ca. 5-7s).
Ist bei mir auch so, war glaub auch schon in den Alpha-Versionen so 😐

**Comment by Bernd9000** [comment]
Mit v3.0.0-beta.18 sieht es gut aus, Icons und Werte sind wieder da :-)

**Comment by mcuiobroker** [comment]
Auf dem Handy nach F5 einmal diese Anzeige:
![image](https://user-images.githubusercontent.com/84818934/146850184-4350939e-d228-4302-89b1-d3c6be118740.png)
Nochmal F5 wieder ok?

**Comment by mcuiobroker** [comment]
Bei Tabwechsel dauert es noch ca 2 Sekunden bis er erstmalig zum Tab umschaltet, dann, wenn einmal geladen dauert es ca 0.5 Sekunden. Man erhält beim Drücken auf den Ziel-Tab nicht sofort eine visuelle Bestätigung, dass man den TAB gedrückt hat.
Die visuelle Bestätigung kommt erst ca 1.5 Sekunden später durch kurze Aufhellung vom Icon-Hintergrund.
Kann man das so einstellen, daß man diese Aufhellung direkt beim Drücken macht. So weiß man, daß man den TAB gedrückt hat.

**Comment by mh-hdl** [comment]
...mit beta18:

Keine Probleme mehr mit Icons, weder per WLAN noch mit VPN. Sonnendaten kommen auch sofort bis zügig. Auch OK... 
DANKE!

Leider neues Problem mit beta18 (gehört wohl dann aber nicht mehr hierher):
CSS- Einstellungen aus Styles-Tab der Konfig. werden beim ersten Start am Desktop nicht geladen. Wenn man in die Konfig geht und 1x speichert, wird CSS geladen. Beim nächsten Aufruf ist erst einmal CSS wieder weg. Mobil (Handy) geht CSS gar nicht (Konfig-Aufruf geht mobil bei mir nicht, aber wohl auch normal und ist aj auch keine Lösung). Ich hoffe die neue tolle mobile Performance hängt nicht an diesem Issue....

**Comment by RkcCorian** [comment]
Ähnliche Verhakten hier. Krass wie schnell die Symbole geladen werden können. Bitte immer so 🙈
@Zefau: Nun sind auch die Alias super schnell, kein Unterschied zu anderen 

- CSS gleiches Verhalten wie bei @mh-hdl 
- ```amazon``` icon lädt nicht
- Sonnenaufgang, etc. lädt gar nicht (DateTime Widget)

**Comment by Zefau** [comment]
>  CSS lädt wieder normal. Soweit so gut, aber es muss irgendwie einen Zusammenhang mit ISSUE #1207 geben. Das Laden der Icons (scheinbar dann wohl CSS-frei) war mit beta18 an jeden Gerät (mit WLAN und auch VPN) problemlos. Jetzt laden die Icons am Desktop und Handy auch normal, aber der, in #1207 beschriebene, Umstand bei VPN-Verbindung ist wieder da. Da dauert es wieder lange oder geht gar nichts mit den Icons. Das Ganze dann auch mit dem Status der jeweiligen Datenpunkte, die auch nicht geladen werden. D.h. kein Schalten etc. möglich...

_Originally posted by @mh-hdl in https://github.com/Zefau/ioBroker.jarvis/issues/1337#issuecomment-999557592_

**Comment by Zefau** [comment]
@RkcCorian was meinst du mit `amazon` icon?

**Comment by RkcCorian** [comment]
@Zefau : Ich habe für meinen FireTvCube das Icon ```amazon``` eingestellt, das lädt nicht. Komischerweise alle meine anderen schon (soweit ich gesehen habe).
```beta-18```
![image](https://user-images.githubusercontent.com/79741077/147098448-adcb2928-5ba1-4387-a9c0-39fedd6f8c61.png)

```beta-8```
![image](https://user-images.githubusercontent.com/79741077/147098887-f5319391-8d3f-4ac5-bd34-d95ece21ff88.png)

**Comment by Zefau** [comment]
Aus welchem Icon Set soll das sein? Ist kein Material Design Icon?

**Comment by RkcCorian** [comment]
Phuuu... das weiß ich nicht mehr auswendig. JARVIS muss es aber wissen, da das Icon gefunden wird 🙈
Eines von...
https://icon-sets.iconify.design/?query=amazon

**Comment by Zefau** [comment]
Du musst es richtig eingeben. `ant-design:amazon-outlined`. Ohne Vorzeichen wird es als `mdi:` interpretiert und dort gibt es das Icon nicht.

**Comment by RkcCorian** [comment]
Ahhh, ok. Warum ging es dann bis zur ```beta-8```?!
Wie dem auch sei... kann ich ändern. Dann bitte "nur noch...
- CSS gleiches Verhalten wie bei @mh-hdl
- Sonnenaufgang, etc. lädt gar nicht (DateTime Widget)
...lösen und die Ladegeschwindigkeit beibehalten 🙈

**Comment by Zefau** [comment]
- CSS sollte mit der aktuellen beta wieder passen
- Sonnenaufgang zieht sich die Koordinaten von deinem ioBroker und darauf basierend die Zeiten. Hast du das richtig eingestellt?

**Comment by RkcCorian** [comment]
Jup, CSS geht wieder mit ```beta-19```
Meine Koordinaten passen. Es lädt auch mit ```beat-8```. Dort auch ziemlich langsam, nur jetzt eben gar nicht mehr.

**Comment by RkcCorian** [comment]
Mit ```beta-19``` laden die Icons wieder langsamer. Scheint einen Quereffekt zwischen CSS und der Ladezeit der Icons zu geben...

**Comment by Zefau** [comment]
Ist jetzt so wie es ist. Es laden einfach sehr viele Dinge zu Beginn (Pro Status, Geräte, alle Datenpunkt-Werte, Layout, Settings, Styles, ioBroker Einstellungen, Notifications, ioBroker Objektliste, Status der Instanzen, Status der Skripte, ) da gibt es nur noch wenig Optimierungspotential.

**Comment by RkcCorian** [comment]
Verstehe... dann bleibt auf der Liste noch...
- Sonnenaufgang, etc. lädt gar nicht (DateTime Widget)

**Comment by Zefau** [comment]
Ist dasselbe Problem. Ich spiele mal etwas rum, dann schauen wir in der nächsten beta mal, ob es besser wird.

**Comment by RkcCorian** [comment]
> Ist jetzt so wie es ist. Es laden einfach sehr viele Dinge zu Beginn (Pro Status, Geräte, alle Datenpunkt-Werte, Layout, Settings, Styles, ioBroker Einstellungen, Notifications, ioBroker Objektliste, Status der Instanzen, Status der Skripte, ) da gibt es nur noch wenig Optimierungspotential.

Ist glaub im direkten Vergleich immer noch schneller als vorher

**Comment by mh-hdl** [comment]
...wäre trotzdem schön, wenn man das noch im Auge behält. 
Wie gesagt, bei mir läuft es mit beta19 im normalen WLAN ganz gut, war aber prinzipiell auch bei beta17 so. 
Es bleibt für mich das besagte VPN-Problem (s.o.), welches ggw. Jarvis für mich nicht remote benutzbar macht. Ergänzend sei noch gesagt, dass ich den Android "Fully"-Browser nutze und die Icons und der Status der DP sporadisch geladen wird. Muster nicht erkennbar.
Zur Erinnerung: Mit beta18 (CSS-Problem) war es über VPN problemlos. Ich habe jetzt testweise mal in der beta19-Konfig die Styles gelöscht und dann noch mal VPN getestet. Geht aber auch nicht besser. Irgendwas war in beta18 mit dem Icons laden anders / besser...

Hat einer eine Idee? Es muss ja nicht unbedingt an Jarvis liegen, aber es gab eben die beta18, wo es ohne CSS lief.

**Comment by Zefau** [comment]
@mh-hdl wie läuft es mit `v3.0.0-beta.20` ?

**Comment by mh-hdl** [comment]
...direkt in beta21 gestartet:

Nach anfänglichen Problemen ("Verification failed- roter Bildschirm / 2x Reboot / Reinstall Adapter) läuft die beta21 im WLAN (Desktop / Tablet / Mobil) normal. Ich musste im Smartphone-Layout einige Widget-Höhen anpassen, aber ansonsten OK...
Mein Problem mit dem VPN ist aber leider nicht verschwunden. Icons und DP-Status hängen meistens nach Aufruf, kein Schalten etc.. Sporadisch ohne erkennbare Muster / Einstellung kommen die Icons und DP.  Einige Einstellungsspielereien in der VPN-Verbindung helfen auch nicht. Ist ja vielleicht auch ein Luxus-Problem. Vielleicht gibt's ja  doch noch andere Stellschrauben. Ansonsten muss ich mich wohl mit meiner vis-Oberfläche mobil behelfen. Die läuft problemlos....

**Comment by Zefau** [comment]
Eine Stellschraube hab ich noch für die nächste beta

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.22`

**Comment by RkcCorian** [comment]
> ...direkt in beta21 gestartet:
> 
> Nach anfänglichen Problemen ("Verification failed- roter Bildschirm / 2x Reboot / Reinstall Adapter) läuft die beta21 im WLAN (Desktop / Tablet / Mobil) normal. Ich musste im Smartphone-Layout einige Widget-Höhen anpassen, aber ansonsten OK... Mein Problem mit dem VPN ist aber leider nicht verschwunden. Icons und DP-Status hängen meistens nach Aufruf, kein Schalten etc.. Sporadisch ohne erkennbare Muster / Einstellung kommen die Icons und DP. Einige Einstellungsspielereien in der VPN-Verbindung helfen auch nicht. Ist ja vielleicht auch ein Luxus-Problem. Vielleicht gibt's ja doch noch andere Stellschrauben. Ansonsten muss ich mich wohl mit meiner vis-Oberfläche mobil behelfen. Die läuft problemlos....

VPN nutze ich auch, ich will nur eine Oberfläche (warten)... ich schau auch mal bei mir...

**Comment by mh-hdl** [comment]
Update zu beta22:
Super!!!
VPN- Laden (inkl. DP's) funktioniert nun einwandfrei. Alles andere läuft auch soweit. Es gab / gibt wohl einige Layout-Korrekturen. Z.B. war meine, CSS-gepimpte, TAB-Kopfleiste etwas "verrutscht" und ich musste wieder in der Smartphone-Ansicht ein paar Widget-Höhen nachregeln.. Ansonsten brauchen im Date / Time Widget die Sonnenzeiten weiterhin Ladezeit. Ich glaube schwankend, mal schneller, mal langsamer, aber gefühlt zu lang. Alles in allem aber ist beta22 ein Schritt in die richtige Richtung. DANKE!

**Comment by Zefau** [comment]
Wunderbar. Wegen dem DateTime schaue ich nochmal

**Comment by RkcCorian** [comment]
Hallo Zusammen,

- Performance > OK
- VPN > OK
- DateTime Problem unverändert > NOK, siehe auch Beobachtung von @mh-hdl 
- Anzeige des Wertes bei BlindLevelAction an "falscher" Position > NOK
  @Zefau Ist das ein Bug oder Feature?! Falls Feature... wie bekomme ich die WerteAnzeige wieder links von dem BlindLevelAction?!
  Bisher (OK)
  ![image](https://user-images.githubusercontent.com/79741077/147391698-ac5ea70d-9c07-49ed-a77f-53375df5040b.png)
  Neu (NOK)
  ![image](https://user-images.githubusercontent.com/79741077/147391663-af5dc2fa-1a5f-4db6-98f0-06b7d9c4e06c.png)


Viele Grüße!

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/issues/1361

**Comment by RkcCorian** [comment]
Top!!!

**Comment by mh-hdl** [comment]
Mit beta27,nach ersten Tests, alle Probleme erst mal beseitigt!!! DANKE!!! Ich glaube meine Widget-Höhen muss ich wieder in der Smartphone- Ansicht korrigieren. Ist aber kein Problem.....
