### ISSUE TITLE
Mobile Navigation, swipe left, defekt.

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1209]
Hi 

auf Mobile (Samsung TAB 10.1) ist es wie folgt: 

Wenn ich von dem linken Rand swipe um das Menu zu öffnen, kommt dieses, jedoch geht es nicht mehr zu. 
Egal was ich anklicke(menupunkt,close,content).

Wenn ich das Menu über den Hamburger öffne geht das alles einwandfrei. 

Gruss

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.132`

**Comment by ma-gu-16** [comment]
Ich habe gerade aktualisiert und alle angelegten Seiten sind weg. :-( unlucky.

**Comment by ma-gu-16** [comment]
Ich habe nun PRO abgeschlossen, aber de Seiten sind noch immer Weg. :-( 

![image](https://user-images.githubusercontent.com/22169074/143772425-434a206e-f25a-4d1b-83a5-94eaa539b8da.png)

**Comment by ma-gu-16** [comment]
Zum Ticket: 

Geht nicht. Gleiches Problem wie beschrieben.  Aktuellste Beta und PRO.

**Comment by ma-gu-16** [comment]
Was mir noch aufgefallen ist auf dem Tablet zeigt es das Hamburger Menu an und auf Desktop mit gleicher Auflösung die Seitennavigation mit den Icons.

**Comment by ma-gu-16** [comment]
Sidebar -Minimode heisst die Option, diese ist nicht auf dem Tablet obwohl genügend Platz vorhanden ;-)

**Comment by ma-gu-16** [comment]
ERgänzung: Ebenso wenn ich von der Seite "reinswipe" bleibt das Menu hängen so bei ca 30%. 

d.h. es fährt nur 30% in den Screen und lässt sich nciht klicken , nicht schliessen. weder auf rest screen noch auf Menuclose.

**Comment by Zefau** [comment]
> Was mir noch aufgefallen ist auf dem Tablet zeigt es das Hamburger Menu an und auf Desktop mit gleicher Auflösung die Seitennavigation mit den Icons.

Die Einstellungen sind "optimiert" für Desktop und werden automatisch auf Mobil / Tablet ausgeblendet.

Die grundsätzliche Herausforderung ist, dass ich nicht sicher sagen kann, welche Auflösung besteht. Selbst Handys haben riesige Auflösungen, aber kleine Bildschirme. Kann ich mir in einer v3.1.x sonst aber nochmal anschauen.

> Sidebar -Minimode heisst die Option, diese ist nicht auf dem Tablet obwohl genügend Platz vorhanden ;-)

Gleiche Begründung.

> ERgänzung: Ebenso wenn ich von der Seite "reinswipe" bleibt das Menu hängen so bei ca 30%.
> d.h. es fährt nur 30% in den Screen und lässt sich nciht klicken , nicht schliessen. weder auf rest screen noch auf Menuclose.

Bei mir funktioniert es auf dem Handy. Kannst du das filmen, um das Fehler zu zeigen?

**Comment by Zefau** [comment]
> Geht nicht. Gleiches Problem wie beschrieben. Aktuellste Beta und PRO.

Bei mir funktioniert es auf dem Handy.
- [x] Öffnen via Icon und schließen via Icon
- [x] Öffnen via Icon und schließen via Backdrop (= klick auf die Seite)
- [x] Öffnen via Swipe und schließen via Icon
- [x] Öffnen via Swipe und schließen via Backdrop (= klick auf die Seite)

**Comment by Zefau** [comment]
@mcuiobroker würdest du mal bei dir schauen, wenn du Zeit hast?

**Comment by mcuiobroker** [comment]
Bzgl Auflösung @zefau vielleicht solltest du die Einstellungen eine OPtion einbauen, die man einschalten kann und womit dann die tatsächliche Auflösung angezeigt wird für 20 Sekunden oder so.
sonst
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/bildschirmgroesse-handy-jarvis
Thema swipen funktioniert auf Tablet Samsung TAB A und Handy Samsung
Browser FireFox Mobile, Version `v3.0.0-beta.7`
![image](https://user-images.githubusercontent.com/84818934/144746920-99fc00c3-bcb3-43d9-911c-0eaca09323f9.png)
`v3.0.0-beta.9` gleiches Verhalten, aus meiner Sicht ok
Gibt es beim Samsung TAB 10.1 besondere Einstellungen bzgl Swipe?

**Comment by Zefau** [comment]
Mit "aktualisieren" meinst du F5 oder Speichern in der Konfiguration?

**Comment by mcuiobroker** [comment]
Pull-To-Refresh

**Comment by Zefau** [comment]
Pull-To-Refresh? Den gibt es in jarvis und im Firefox Mobil nicht, oder?

Also in jarvis habe ich den entfernt. Und in Firefox kommt bei mir kein pull-to-refresh.

**Comment by mcuiobroker** [comment]
Auf dem Tablet funktioniert er in Chrome und Edge. Runterziehen und er aktualisiert.

**Comment by Zefau** [comment]
>  Bei mir funktioniert Swipe nach unten "aktualisieren" nicht (FireFox), Chrome funktioniert und Edge funktioniert auch.

Achso, jetzt verstehe ich, was du geschrieben hast. Ja, es gibt eben kein Pull-To-Refresh im Firefox. In jarvis sowieso nicht (mehr). Also ist browser-spezifisch und hat nichts mit jarvis zu tun.

**Comment by Zefau** [comment]
@ma-gu-16 könntest du bitte nochmal prüfen, ob https://github.com/Zefau/ioBroker.jarvis/issues/1209#issuecomment-986218703 bei dir funktioniert wie bei @mcuiobroker und mir? Danke dir.

**Comment by ma-gu-16** [comment]
Also los gehts: 

jarvis aktuellste beta 9. neu gestartet und cache geleert. 
Grundsätzlich ist es leider noch immer buggy. 

Iphone XR/Safari:

Swipe to right, menu geht auf, klick auf seite, seite öffnet. swipe/slide oben die tabs (nichts klicken) und jetzt swipe ich wieder vom linken rand um das seitenmenu zu öffnen. das menu und die seite springen wild. 
siehe video anbei. 

Auf Android/Chrome (aktuellstes Android und Chrome)
klappt das obige Problem. 

https://user-images.githubusercontent.com/22169074/144912055-bfbeb92a-6d35-4b08-b262-0c9d70eb77e9.mp4

Auf dem Galaxy TAB funktioniert es noch immer nicht. Gleiches Problem wie bereits beschrieben.
Ich nutze den KIOSK Mode (Fully Kiosk Browser, v 1.42.5) und dessen Browser, ich glaube ist die Chrome Engine. 

Ich kann das Seitenmenu öffnen, fährt teilweise nur zu 75% raus. und schliessen geht dann nicht mehr. 
Ich kann die Menupunkte zwar anklicken, aber nix anderes. auch das klicken neben dem menu klappt nicht. 

Gruss

**Comment by Zefau** [comment]
Also die Sidebar fährt bewusst nur 3/4 auf

**Comment by ma-gu-16** [comment]
UPDATE: Hab eben den Fully aktualisiert. scheint nun zu gehen. 
Alle die von dir genannten Punkte. 

Bleibt nur noch das Iphone Problem.

**Comment by Zefau** [comment]
@ma-gu-16 ist dies mit der aktuellen alpha stabiler?
