### ISSUE TITLE
hide last update in the status

### ISSUE THREAD

**Issue by mla4ger** [Zefau/ioBroker.jarvis#121]
normally is the last update shown under the statusname (device). There should be an option to hide this.

**Comment by Zefau** [comment]
added with `1.1.0-beta.11`.

**Comment by Zefau** [comment]
>  ich denke du sprichst von dem Last Body Change, das habe ich mir auch schon gedacht aber leider kann ich den nicht leer lassen oder löschen. Wird immer wieder gefüllt mit LastChangeBody

**Comment by mla4ger** [comment]
Ja genau das meinte ich

**Comment by Zefau** [comment]
Sollte mit `v1.1.0-beta.14` nun behoben sein.

**Comment by Zefau** [comment]
Also considered `StateListHorizontal` with `1.1.0-beta.18`.
