### ISSUE TITLE
Instanz-Neustart

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1210]
Woher kann das kommen?

<html>
<body>

jarvis.0 | 2021-11-25 14:16:18.085 | error | Cannot read property 'ack' of null
-- | -- | -- | --
jarvis.0 | 2021-11-25 14:16:18.082 | error | TypeError: Cannot read property 'ack' of null at Adapter.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/websocket.io.js:87:67) at Adapter.emit (events.js:326:22) at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5710:38) at processImmediate (internal/timers.js:461:21)
jarvis.0 | 2021-11-25 14:16:18.072 | error | uncaught exception: Cannot read property 'ack' of null

</body>
</html>

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.131` behoben

**Comment by mcuiobroker** [comment]
Schreib es mal hier rein:
![image](https://user-images.githubusercontent.com/84818934/143505314-98861e1a-bc49-431c-8f6a-46649c773a07.png)

**Comment by Zefau** [comment]
Arg, das sind meine Spielereien.

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.132`

**Comment by mcuiobroker** [comment]
Bislang keine Neustarts. Ok.
