### ISSUE TITLE
Chart: Reihenfolge wird vertauscht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1211]
`v3.0.0-alpha.131`
Die Chart-Anzeige zeigt auf unterschiedlichen Tablets plötzlich unterschiedliche Reihenfolgen der DPs?
In dem Fall sind WZ und PC vertauscht, obwohl alle gleich sein sollten.
PC
![image](https://user-images.githubusercontent.com/84818934/143509874-edadfdf1-c161-4172-92cd-1c3491fcfc86.png)

Tablet A
![image](https://user-images.githubusercontent.com/84818934/143509692-e87a29b1-0abf-410e-a10c-9b39bcdec43c.png)
Tablet B
![image](https://user-images.githubusercontent.com/84818934/143509719-7e118f79-1e7a-4acc-99ad-74eb5c2528b1.png)

Nach F5 Refresh, haben alle wieder die gleiche Reihenfolge.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.19`

**Comment by mcuiobroker** [comment]
Passt. Danke.
