### ISSUE TITLE
RangeError: Invalid time value

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#1212]
Hallo,

der Fehler tritt auf, sobald ich in Jarvis unter Einstellungen ein neues Gerät hinzufügen möchte und auf den Schraubenschlüssel für die Datenpunkauswahl klicke.

Den Layout Code habe ich bereits mit dem JSON Validator geprüft. Keine Probleme vorhanden.
Jarvis habe ich über Adapter wiederaufgebaut, ohne Erfolg.

Jarvis Version: v2.2.1

Viele Grüße
![Screenshot 2021-11-26 072544](https://user-images.githubusercontent.com/95069101/143538004-bc535e93-8e1f-4468-9950-b2380cf1074e.png)

**Comment by Zefau** [comment]
Vermutlich ein falscher Wert beim DateTime Modul. Das müsstest du im JSON fixen.

Besser wäre aber du gehst auf v3.

**Comment by SlipKoRn88** [comment]
Ich hatte nun v3.0.0-alpha.131 installiert. Leider erhalte ich einen schwarzen Bildschirm, sobald ich in Jarvis die Einstellungen (Zahnrad) öffne und kann daher nichts konfigurieren. Bei v2.2.3 erhalte ich wieder Invalid Time Value.

**Comment by Zefau** [comment]
Hast du Web Adapter und ggf. ioBroker mal neugestartet?

Hast du einen Fehler ind er Browser Konsole (via F12) ?

**Comment by SlipKoRn88** [comment]
Web Adapter, Jarvis und ioBroker hatte ich neu gestartet, aber es half nichts.
Ich habe darauf hin Backups eingespielt und dann v2.21 wieder ordnungsgemäß zum Laufen gebracht, auch ohne Invalid Time Value Error. Seltsam, da ich zwischen letztem Backup und gestern nichts geändert hatte.
Nun habe ich nochmal v3.0.0-alpha.131 installiert und es funktioniert bisher problemlos.
