### ISSUE TITLE
Variable primary für Farbe wird in Icon Stil nicht berücksichtigt

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#1213]
Version: V3, Alpha 132

In den Einstellungen ist als Primärfarbe des Themes #1976d2 eingestellt. Laut https://quasar.dev/style/color-palette#Color-List müsste ich als color doch primary angeben können.

In meinem Beispiel funktioniert die Variable nicht, das Icon wird schwarz gefärbt. Red oder auch ein Hexcode werden allerdings angenommen:

`{
  "false": {
    "color": "primary"
  },
  "true": {
    "color": "red"
  }
}`

Oder wie kann ich die Primärfarbe des Themes als Variable eintragen? Oder muss ich erst im CSS Tab eine anlegen? Wenn ja, wie?
![Screenshot 2021-11-28 123830](https://user-images.githubusercontent.com/16526471/143766518-d9f66831-9d17-49c0-936d-b10afc680cef.png)
![Screenshot 2021-11-28 123936](https://user-images.githubusercontent.com/16526471/143766519-91d7c6b6-bdb3-4dc8-aed2-4247f03d2cd2.png)
![Screenshot 2021-11-28 124000](https://user-images.githubusercontent.com/16526471/143766521-5fc1211a-f6cc-49e9-878f-68d1f9606535.png)

**Comment by Zefau** [comment]
`primary`, `secondary` und `accent` können via [CSS Variable](https://developer.mozilla.org/en-US/docs/Web/CSS/Using_CSS_custom_properties) genutzt wrden.

Versuch daher mal bitte `var(--q-color-primary)`.

**Comment by stony2k** [comment]
quasi so?
`{"0":{"color":"var(--q-color-primary)"},"1":{"color":"red"}}`

Icon leider immer noch schwarz.

**Comment by Zefau** [comment]
Jo, eigentlich so. Ich schau nochmal.

**Comment by stony2k** [comment]
Witzig: "--q-colorseconday" und "--q-coloraccent" nimmt er an (wird dann grün und lia) :) Dann wirst du das mit primary sicher schnell fixen können.

**Comment by Zefau** [comment]
Also wenn die beiden gehen, sollte `primary` auch funktionieren. Ist ja analog implementiert.

**Comment by Zefau** [comment]
Ggf. mal Seite neuladen?

**Comment by stony2k** [comment]
Tatsache, war dann wohl ein Cache Problem. Vielen Dank für den Tipp mit der Variable. Hast du schon eine Idee wann das Betastadium erreicht wird? Mach weiter so! :)

**Comment by Zefau** [comment]
Beta ist heute morgen raus. Latest folgt vor Weihnachten hoffentlich.
