### ISSUE TITLE
Beschriftung der Markierungen von LevelBody gehen nur bis zur hälfte (mobile Ansicht)

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#1215]
Version: Beta 3.0.0 Beta 3

In der mobilen Ansicht (Tablet und Handy) werden beim LevelBody die Beschriftungen nur bis zur Hälfte angezeigt.
![mobile](https://user-images.githubusercontent.com/16526471/143770276-3602b8e1-5be0-4079-9677-00d9a23b3b92.png)

Auf dem Desktopbrowser ist die Ansicht wie gewohnt.
![desktop](https://user-images.githubusercontent.com/16526471/143770286-3c45d54c-3203-4b88-98ea-73d88b57755e.png)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-beta.6`

**Comment by stony2k** [comment]
Perfekt, die Anzeige ist mit der Beta 6 wieder korrekt.
