### ISSUE TITLE
v3 Calender Widget Kalender Vorschau nicht mehr abwählbar

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#1216]
V 3.0.0 Beta1

Ich weiss nicht genau, ab welcher Version es aufgetreten ist.  Nun ist es mir aber aufgefallen, weil das Widget, aufgrund mehrerer Termine skaliert.
Ich kann im Kalender Widget die Vorschau zwar deaktivieren, jedoch hat das keine Funktion.

![image](https://user-images.githubusercontent.com/22911084/143771231-28b23887-d34f-4d6e-9e89-b859bd6346ab.png)

![image](https://user-images.githubusercontent.com/22911084/143771251-35775c8c-c6f7-4ac4-ba93-4688ba92cecc.png)

**Comment by MarkSau** [comment]
Zusatz: Ich habe versucht eine weiteres Kalender Widget anzulegen. Da kann ich keine Kalender hinzufügen:
es läuft nur der blaue Balken:

![image](https://user-images.githubusercontent.com/22911084/143771499-d2c19fdc-1183-4540-847c-e0c68226c39a.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.6`

**Comment by MarkSau** [comment]
Super, funktioniert wieder..Danke
