### ISSUE TITLE
Pro Version: keine Seiten mehr

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1217]
Ich habe nun PRO abgeschlossen, aber de Seiten sind noch immer Weg. :-( 

![image](https://user-images.githubusercontent.com/22169074/143772425-434a206e-f25a-4d1b-83a5-94eaa539b8da.png)

_Originally posted by @ma-gu-16 in https://github.com/Zefau/ioBroker.jarvis/issues/1209#issuecomment-981096263_

Habe auch schon Adapter usw neugestartet. Was übersehe ich ?

**Comment by Zefau** [comment]
Wurde die Lizenz korrekt in den Datenpunkt übernommen?

**Comment by ma-gu-16** [comment]
![image](https://user-images.githubusercontent.com/22169074/143772576-5237a6de-1114-4ba9-a718-b6c9f9309ced.png)

scheinbar ja

**Comment by MarkSau** [comment]
Bei mir auch nicht...ich bin auch gar nicht gefragt worden, was ich bei PP zahlen soll...Das wäre schön zu wissen...bevor ich da zustimme.

**Comment by ma-gu-16** [comment]
Ja das siehst du erst wenn du paypal abonnieren und die ganzen steps klickst, zum schluss hast du ja dann den endgültigen kauf button, dort steht dann auch oben klein 12 euro und irgendwo wo das es im jahr ist. 

aber stimme dir zu es sollte noch vor dem ganzen stehen direkt auf der PRO Seite. 12 Euro / Jahr. fertig. ;-)

**Comment by Zefau** [comment]
Nehme ich gerne mit auf.

Die Lizenz in `jarvis.0.info.pro` kopieren. Steht auch auf der Rechnung.

**Comment by MarkSau** [comment]
> Die Lizenz in `jarvis.0.info.pro` kopieren. Steht auch auf der Rechnung.

gemacht...tut aber trotzdem nicht...

![image](https://user-images.githubusercontent.com/22911084/143773142-5f4c26f7-a2a6-4978-ae36-8cd5c9a08189.png)

**Comment by Zefau** [comment]
Du bist auf der letzten beta? Und du hast die gesamte Lizenz reinkopiert? Also alles, was grau hinterlegt ist?

**Comment by MarkSau** [comment]
Ja Beta 4,ja,ja

**Comment by Zefau** [comment]
Da scheint noch etwas bei der Validierung nicht zu stimmen. Ich fixe..

**Comment by ma-gu-16** [comment]
Bei mir hat es nun geklappt. Alles kopiert zu jarvis.0.info.pro, und dann ein reboot des Adapters. 

Seiten sind wieder da.

**Comment by MarkSau** [comment]
bei mir noch nichts

**Comment by Zefau** [comment]
versuch mal bitte `v3.0.0-beta.5`

**Comment by SlipKoRn88** [comment]
Bei mir leider das Gleiche, auch mit v3.0.0-beta.5
Der Lizenzcode ist korrekt kopiert und eingetragen. 

In Jarvis steht aber:

- Only a single page is allowed without Pro. A single page may hold infinite tabs though..
- Only 5 tabs are allowed without Pro.

Änderungen in "Styles" werden nicht übernommen und die Seiten in der Seitenleiste werden nicht angezeigt

Viele Grüße

**Comment by MarkSau** [comment]
> versuch mal bitte `v3.0.0-beta.5`

Passt bei mir jetzt.
