### ISSUE TITLE
Favicon pink anstatt blau

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#1219]
Jarvis V3 Beta 4

Seit einiger Zeit ist das Favicon pink. Mir ist aufgefallen, dass das Icon im Dateimanager auch schon pink ist. Habe die Icons gelöscht, den Adapter von Github neu installieren lassen und es werden dieser die pinke Icons geladen. Das ganze Jarvis Thema war doch immer blau, ist das ein Bug oder wurde es tatsächlich pink gemacht?
![Screenshot 2021-11-28 160848](https://user-images.githubusercontent.com/16526471/143773778-b16f17d5-9b98-40e9-8d99-e81ffad21425.png)
![Screenshot 2021-11-28 161002](https://user-images.githubusercontent.com/16526471/143773811-a999178b-4ce5-4290-bdd2-c798cab77bc9.png)

**Comment by Zefau** [comment]
Das ist das v3 Logo
