### ISSUE TITLE
Jarvis not working if web adapter uses https

### ISSUE THREAD

**Issue by thost96** [Zefau/ioBroker.jarvis#122]
Hi, 

Jarvis UI at URL iobroker:8082/jarvis is returning "Failed to connect!" if HTTPS is enabled in web instance. As normal HTTP does work, this might be a linking or resource loading issue. Thanks!

**Comment by Zefau** [comment]
I'm using https, so it should be working. Are you using socket.io? What is the url when you open from ioBroker dashboard?

**Comment by thost96** [comment]
Hi, no I'm not using socket.io. Web.0 wasn't installed earlier on my setup, so it came with jarvis installation and if HTTPS get's enabled and you go to "https://iobroker:8082/jarvis/index.html" the error "Failed to connect!" is only displayed.

**Comment by Zefau** [comment]
You have to open it from the ioBroker Dashboard. All necessary connection details will be attached then. In case of a secure connection `#socketSecure=true` needs to be attached to the URL. This setting will then be cached by jarvis, but it is necessary the first time and every time the Browser cache has been emptied.

**Comment by thost96** [comment]
Maybe a redirect or a similar solution  with all needed URL attachments would be better, as this isn't a great solution for external usage without access to the admin instance.

**Comment by Zefau** [comment]
I'm not happy with the solution myself, but how to solve it?

The main issue is that I do not know the connection details to ioBroker (especially the port; even though the default values are usually not changed). Do you have any ideas?

**Comment by rschneider1509** [comment]
i want to attach myself to this. got the same problem :(

**Comment by Zefau** [comment]
I'm reworking the way the initial connection is established. For now though, please consider https://github.com/Zefau/ioBroker.jarvis/issues/122#issuecomment-699514478.

**Comment by Zefau** [comment]
@thost96 @rschneider1509 Could you check with the latest beta if the connection problems have been resolved?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/180

**Comment by rschneider1509** [comment]
upgraded to 1.0.9 and yes, it works :) ty
