### ISSUE TITLE
Fehlende Funktionen nach Update auf v3.x

### ISSUE THREAD

**Issue by dentro-git** [Zefau/ioBroker.jarvis#1220]
Ich habe gerade mein Jarvis auf 3.0.0-beta. 5 geupdated.
(Hatte es auch schonmal in einer Alpha und hatte den gleichen Effekt.
Ich nutze hier die HMIP Adapter, der Punkt mit den Slidern betrifft aber auch meinen Phillips HUE Adapter.

Folgendes ist mir aufgefallen.
1.) Nach dem Update werden keine Werte mehr im Popup angezeigt weil dies in der Gerätekonfig nun so konfiguriert ist.
![image](https://user-images.githubusercontent.com/77006779/143824197-ce0f2955-615f-4450-b548-225ed5a5bc52.png)
Resultat:
![image](https://user-images.githubusercontent.com/77006779/143824240-693a7585-7307-4365-8493-79c25b569970.png)
Dies kann man ja aber per Hand wieder setzen, auch wenn es bei einer großen Installation echt aufwändig ist.

2.) Zum einstellen der Solltemp habe ich immer den Level Blinder, also den Schieberegler verwendet.
Das ist leider wie oben zu sehen auch umkonfiguriert. 
![image](https://user-images.githubusercontent.com/77006779/143824787-6b7566d0-f596-488a-b27f-05b3c6f3e20b.png)

Kann man hier evtl. den Standard anpassen oder es beim "Import" aus 2.3.0 übernehmen?

@Zefau : Jarvis 3 ist ansonsten Bombe, die Ladezeiten sind echt der Hammer. Freue mich schon auf mehr. Werde hier gerne auf Pro gehen da ich schon wirklich viel Freude mit Jarvis hatte. Weiter so!

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1176

**Comment by Zefau** [comment]
@dentro-git hast du noch das v2 Layout von dem du konvertiert hast? Die Option `Datenpunkt-Wert anzeigen` wird aktiviert, wenn in v2 das `Action Element` `State` hinterlegt war.

Wie war das bei dir?

**Comment by dentro-git** [comment]
@Zefau : Sorry dachte ich hätte die alten Backups noch. Aber der Backitup überschreibt die nach 7 Tagen. Und im Adapter selber ist auch nichts mehr. Und erinnern tue ich mich leider ebenfalls nicht mehr.
Ich habe am Ende, auch weil wir es in einem anderen Bug diskutiert hatten alle Geräte neu importiert. Das hatte zwar andere Effekte aber die oben beschriebenen waren damit erst mal gelöst.

Sorry das ich hierzu aktuell keine weiteren Infos geben kann.
