### ISSUE TITLE
Ich kann jarvis nicht installieren: Keine Versionsinfo für web

### ISSUE THREAD

**Issue by shurik239** [Zefau/ioBroker.jarvis#1221]
Ich kann jarvis Adapter nicht installieren. Nach dem Klick auf Plus Zeichen bekomme ich den Hinweis: 'Keine Versionsinfo für web' mit ausgegrautem 'Hinzüfügen' Button.

 
![adapters - serve](https://user-images.githubusercontent.com/9530524/143840248-c1ed942b-fbc1-4e52-a9e6-0c7b7e16ca0c.png)

**Comment by Zefau** [comment]
Bitte Web Adapter installieren

**Comment by shurik239** [comment]
> Bitte Web Adapter installieren

Dank für die schnelle Rückmeldung. 
Web Server, socket.io Adapters installiert. Werden aber nicht in installierten Adapters angezegeit, aber Instances laufen.

**Comment by shurik239** [comment]
Kann es sein, dass Port 8083 bei web Adapter eine Role spielt? Default 8082 ist bei mir besetzt.

**Comment by Zefau** [comment]
Kann ich wenig zu sagen. Ist ein ioBroker Fehler, nicht jarvis. Ggf. Web Adapter nochmal deinstallieren? Oder ioBroker mal durchstarten?

**Comment by shurik239** [comment]
Host neustarten hat geholfen. Danke!
