### ISSUE TITLE
v3: CSS Styles nur für bestimmte jarvis Seite

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1222]
Da im HTML Code keine ID für eine jarvis Seite vorhanden ist, kann man im css code kein Selektor anwenden.
Anwendungsbeispiel:
Ich hab eine eigene Seite nur für Handys mit eigenen Tabs/Widgets angelegt.
Hier möchte ich den css code nur für diese Seite anwenden.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.6`

**Comment by mcuiobroker** [comment]
Hast du dort einen neuen Selektor für die Seite eingefügt?

**Comment by Zefau** [comment]
Jo, `jarvis-page- ... id ...`, z. B. `jarvis-page-2add0205-c31d-4bc7-b8b8-694dc09e4a30`

**Comment by mcuiobroker** [comment]
Welche ID soll man da nehmen? Ich sehe keine Seiten-ID im DOM.

**Comment by Bernd9000** [comment]
Super, funktioniert
Danke

**Comment by mcuiobroker** [comment]
@Bernd9000 Welche ID hast du genommen?

**Comment by Bernd9000** [comment]
Beispiel:
.jarvis-page-xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx .q-item__section--main {
min-height: 80px;
}

ID aus den jarvis Einstellungen

**Comment by mcuiobroker** [comment]
Aus dem Layout JSON
![image](https://user-images.githubusercontent.com/84818934/143955774-5d55bfba-cae2-49b3-8d3a-d80afff830ca.png)

**Comment by Bernd9000** [comment]
![Unbenannt](https://user-images.githubusercontent.com/77005685/143955901-a02a0022-c6ba-4d96-abc6-dca126ad9336.jpg)

**Comment by mcuiobroker** [comment]
Hab sie gerade gefunden. Danke.
