### ISSUE TITLE
Jarvis möchte "[object Object]" als Spotify Wiedergabegerät setzen

### ISSUE THREAD

**Issue by simonssoftware** [Zefau/ioBroker.jarvis#1223]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? v3.0.0-beta.5
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

1. Jarvis öffnen
2. Zu dem Tab gehen auf dem der Player ist

In meinem Fall müsste nicht "spotify-premium.0.devices.[object Object].useForPlayback", sondern "spotify-premium.0.devices.simon-tv.useForPlayback" gesetzt werden.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![grafik](https://user-images.githubusercontent.com/50638485/143905632-a11aeab4-8daa-4ef6-8d82-6a3f328909a1.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Funktioniert bei mir problemlos. Was wird dir denn im Dropdown angezeigt? Steht da auch `[object Object]` ?

**Comment by simonssoftware** [comment]
Im Dropdown wird bei mir nichts angezeigt.
Ich komm aber gar nicht zur Auswahl, wenn ich Jarvis öffne und auf den Tab wechsle auf dem das MediaControl ist, wird sofort versucht `[object Object]` zu setzen und der Spotify Adapter stürzt ab.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-rc.1` wieder passen

**Comment by simonssoftware** [comment]
Schaut gut aus, habs zumindest nicht mehr nachstellen können 😄 
Danke dir 👍
