### ISSUE TITLE
Browsersprache wird anstatt der eingestellten Sprache benutzt

### ISSUE THREAD

**Issue by simonssoftware** [Zefau/ioBroker.jarvis#1224]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? v3.0.0-beta.5
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Jarvis benutzt die im Browser eingestellte Sprache, in meinem Fall ist Firefox auf Englisch eingestellt, Jarvis auf Deutsch.
Trotzdem wird alles auf Englisch angezeigt.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![grafik](https://user-images.githubusercontent.com/50638485/143922748-36b95844-2e1f-40e1-84df-2c28e72f8cca.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by simonssoftware** [comment]
Hab das ganze gerade eben noch mit Google Chrome probiert, da ist das gleiche Problem, sobald der Browser auf Englisch ist ist Jarvis auch auf Englisch, obwohl Deutsch eingestellt ist. Andersrum genau das gleiche Browser auf Deutsch, Jarvis auf Englisch, Browsersprache wird angezeigt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.6`

**Comment by simonssoftware** [comment]
Funktioniert, danke 👍
