### ISSUE TITLE
Einstellungbutton unten links fehlt

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1225]
Version: v3.0.0-beta.5

Unten links der Einstellungsbutton ist plötzlich weg. Ein Neustart vom Adapter brachte keine Lösung.

**Comment by mcuiobroker** [comment]
Meinst du diesen?
![image](https://user-images.githubusercontent.com/84818934/143939944-eb36f800-bc08-43a9-9d6a-cadbae7a23c1.png)

**Comment by Zefau** [comment]
Ggf. hast du den aktiv ausgeblendet in den Einstellungen? Mittels F2 gelangst du via Shortcut in die Einstellungen.

**Comment by AFPass** [comment]
> Ggf. hast du den aktiv ausgeblendet in den Einstellungen? Mittels F2 gelangst du via Shortcut in die Einstellungen.

Peinlich. Du hast Recht.
