### ISSUE TITLE
Wert Runden

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1226]
Mit JSON Formatierung kenn ich mich nicht so aus. Immer nur erfolgreich Copy&Paste. ;-P

Wir bekomme ich eine Zahl mit JSON gerundet? Also von 1,23456789 auf 1,23?

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/beispiele/geraete-einstellungen/datenpunkt-eigenschaften/nachkommastellen-auto
