### ISSUE TITLE
Import device HomeMatic Wired blind actor HMW-LC-Bl1-DR

### ISSUE THREAD

**Issue by stan23** [Zefau/ioBroker.jarvis#1228]
Could you please add this device:

```
"HMW-LC-Bl1-DR": {
  "level": {
    "state":  "3.LEVEL",
    "action":  "3.LEVEL"
  },
  "activity": {
    "state":  "3.WORKING"
  },
  "stop": {
    "action":  "3.STOP"
  }
}
```

Objects in ioBroker:
![grafik](https://user-images.githubusercontent.com/4477518/144097202-8b501a94-5c96-43f5-a484-0b8d345b27e9.png)

**Comment by Zefau** [comment]
added with `v3.0.0-beta.7`

**Comment by stan23** [comment]
Thanks for the super-fast implementation, it is working fine in beta.7
