### ISSUE TITLE
--q-color-negativ usw.

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1229]
Irgendwo, ich weiß nicht mehr wo, habe ich gelesen, dass man bei den Stielen für color auch die Variablen --q-color-negativ, --q-color-positiv usw. nutzen kann.

Ich habe im Icon Stil folgendes:
{"false":{"color":"var(--q-color-negativ)"}}

Aber leider wird es dann nur grau. Hab ich was falsch verstanden?

**Comment by Zefau** [comment]
`negative` mit e am Ende, da Englisch

**Comment by AFPass** [comment]
> `negative` mit e am Ende, da Englisch

Wie immer, der Fehler vor der Tastatur. Danke
