### ISSUE TITLE
Layout: Changing a tab to fullscreen breaks the layout

### ISSUE THREAD

**Issue by Loi83** [Zefau/ioBroker.jarvis#123]
Nachdem ich einen Tab als Fullscreen anzeigen geklickt habe, habe ich nun ein leeres Bild und komme auf keine Einstellungen mehr. Es wird kurz angezeigt das die Einstellungen geladen werden und das wars dann.

After I clicked a tab as fullscreen, I now have an empty picture and can no longer access any settings. 
It is briefly displayed that the settings are being loaded and that's it.

**Comment by Zefau** [comment]
Could you check the Browser Console for any error messages?

**Comment by Loi83** [comment]
![image](https://user-images.githubusercontent.com/45265773/94345717-52a26b80-0028-11eb-95ea-f97cfca49203.png)
yeah there a few

**Comment by Zefau** [comment]
Were you able to recover your layout?

**Comment by Zefau** [comment]
@Loi83 Could you explain in detail what the layout looked like before you clicked the option?

**Comment by Zefau** [comment]
![image](https://user-images.githubusercontent.com/14368811/94348384-f3e6ed00-003b-11eb-831e-271a714519d2.png)

**Comment by Zefau** [comment]
@Loi83 Could you actually share your layout configuration? See `jarvis.0.layout`.

**Comment by Loi83** [comment]
> @Loi83 Could you actually share your layout configuration? See `jarvis.0.layout`
here it comes
`[{"title":"","tabs":[{"title":"Home","icon":"home","_fullscreen":{"moduleConfig":{},"module":"DateTime","title":"Test","devices":[],"index":0}},{"title":"Rollo","icon":"window-shutter","_fullscreen":{"moduleConfig":{},"module":"StateList","title":"Rollo","devices":[{"type":"device","deviceId":"rolloschlafzimmer_2e4c7","bodyStateKey":"level","primaryStateKey":"level","actionType":"action","actionElement":"BlindLevelAction"},{"type":"device","deviceId":"rolloküche_0af7a","bodyStateKey":"level","primaryStateKey":"level","actionType":"action","actionElement":"BlindLevelAction","bodyElement":null},{"type":"device","deviceId":"rollowohnzimmerli_74b3b","primaryStateKey":"level","actionType":"action","actionElement":"BlindLevelAction","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rollowohnzimmerre_dc1ca","actionType":"action","actionElement":"BlindLevelAction","primaryStateKey":"level","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rollowc_d810e","actionType":"action","actionElement":"BlindLevelAction","primaryStateKey":"level","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rollobad_34f92","primaryStateKey":"level","secondaryStatesKeys":[],"actionType":"action","actionElement":"BlindLevelAction","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rollobalkon_ba2f0","actionType":"action","actionElement":"BlindLevelAction","primaryStateKey":"level","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rolloterasse_0cf20","actionType":"action","actionElement":"BlindLevelAction","primaryStateKey":"level","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rollonoah_0cc0c","actionType":"action","actionElement":"BlindLevelAction","primaryStateKey":"level","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rolloeliah_db37d","actionType":"action","actionElement":"BlindLevelAction","primaryStateKey":"level","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rollobüro_8dc19","actionType":"action","actionElement":"BlindLevelAction","primaryStateKey":"level","bodyStateKey":"level","bodyElement":null},{"type":"device","deviceId":"rolloflur_8e8da","actionType":"action","actionElement":"BlindLevelAction","primaryStateKey":"level","bodyStateKey":"level","bodyElement":null}],"icon":"window-shutter","iconStyle":{"color":"#FFFFFF","fontSize":"36"},"index":0}},{"title":"Heizung","icon":"thermometer","_fullscreen":{"moduleConfig":{},"module":"StateList","title":"Heizung","iconStyle":{"color":"#FFFFFF","fontSize":"48"},"icon":"thermometer","devices":[{"type":"device","deviceId":"heizkörperbad_b4a7c","primaryStateKey":"temperature","secondaryStatesKeys":["boost"]},{"type":"device","deviceId":"heizkörpernoah_4450a","primaryStateKey":"temperature","secondaryStatesKeys":["boost"],"actionType":"state","actionElement":""},{"type":"device","deviceId":"heizkörpereliah_318cd","primaryStateKey":"temperature","secondaryStatesKeys":["boost"]}],"index":0}},{"title":"Beleuchtung","icon":"lightbulb-outline","_fullscreen":{"moduleConfig":{},"module":"StateList","title":"Lichter","icon":"lightbulb-outline","devices":[{"type":"device","deviceId":"philips_hue.wohnzimmer_eeeaf","actionType":"action","actionElement":"SwitchAction","bodyStateKey":null},{"type":"device","deviceId":"philips_hue.flur_d04da","actionType":"action","actionElement":"SwitchAction"},{"type":"device","deviceId":"philips_hue.schlafzimmer_e925a","actionType":"action","actionElement":"SwitchAction"},{"type":"device","deviceId":"philips_hue.bad_2c1f1","actionType":"action","actionElement":"SwitchAction","bodyStateKey":null,"bodyElement":"LevelBody"}],"iconStyle":{"color":"#FFFFFF","fontSize":"48"},"index":0}}]}]`

**Comment by Zefau** [comment]
Looks good. Could you update to 1.0.2? Does the error persist with that? Difficult to actually find the bug.

**Comment by Loi83** [comment]
Cant found the version 1.0.2. Every time i try i still on 1.1.0 rc...

**Comment by Loi83** [comment]
cant install teh version 1.0.2. After a update iam still on 1.1.0.

**Comment by Zefau** [comment]
Just to be sure: You have the `Puffer` option deactivated in the web adapter settings, right?
I think you have to backup your layout and devices (simply copy `jarvis.0.devices` and (`jarvis.0.layout`), uninstall and then install 1.0.2 from latest repo.

**Comment by Loi83** [comment]
Puffer is deactivated. So i deleted the Adapter, changed to latest, but cant find the Adapter. 
![Screenshot_20200927-180135](https://user-images.githubusercontent.com/45265773/94369671-95794780-00eb-11eb-9fc0-bf697320f2ef.jpg)

Sorry normaly iam really fit in iobroker.

**Comment by Zefau** [comment]
The adapter is definitely in the latest repo. Did you refresh the adapter list?

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/494842

**Comment by Zefau** [comment]
Should be finally resolved with `v1.0.3`.
