### ISSUE TITLE
History Chart: Influxdb nicht mehr auswählbar

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1230]
Ich wollte gerade unter v3.0.0-beta.7 einen neuen History Graph anlegen. Kann aber bei history meine Influx nicht auswählen.

**Comment by mcuiobroker** [comment]
Mit beta.7 weiterhin auswählbar
![image](https://user-images.githubusercontent.com/84818934/144133134-1e172b81-bad0-448a-9d84-a3f28608c92e.png)

**Comment by AFPass** [comment]
Ich sehe nichts.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/144134637-aa71f027-b83d-43b0-99d5-faf35fc156d6.png)
Beide?

**Comment by AFPass** [comment]
Auch bei "beide" bleibt die Adapter Auswahl leer.

**Comment by mcuiobroker** [comment]
Der DP ist auch für influxdb zugeordnet?

**Comment by AFPass** [comment]
Ja. Der DP ist Influx zugeordnet.

**Comment by mcuiobroker** [comment]
Laut influx: 
![image](https://user-images.githubusercontent.com/84818934/144136466-8ba469a7-9b07-41a2-85aa-4957b0ca1ccd.png)

**Comment by mcuiobroker** [comment]
Schon mal die influx-Instanz neugestartet?

**Comment by Zefau** [comment]
Der Fehler 429 kommt von Sentry.

Klapp mal bitte bei der Timeout Warnung das `Object` auf.

**Comment by AFPass** [comment]
> Der Fehler 429 kommt von Sentry.
> 
> Klapp mal bitte bei der Timeout Warnung das `Object` auf.
<img width="1015" alt="Bildschirmfoto 2021-11-30 um 23 41 43" src="https://user-images.githubusercontent.com/13101074/144139890-832adee3-84c5-45c7-806d-b6bd6c829de1.png">

**Comment by AFPass** [comment]
> Schon mal die influx-Instanz neugestartet?

Ja. Keine Änderung.

**Comment by Zefau** [comment]
`object` aufklappen (hinterer Teil), nicht die Warnung

**Comment by AFPass** [comment]
> `object` aufklappen (hinterer Teil), nicht die Warnung
<img width="1015" alt="Bildschirmfoto 2021-11-30 um 23 50 06" src="https://user-images.githubusercontent.com/13101074/144140796-d2cdebbe-8d4f-4841-ae94-ac98a4615975.png">

**Comment by Zefau** [comment]
Wenn du die Jarvis Instanz durchstartest, steht dann im ioBroker Log die korrekte Version?

Kannst du bei dir lokal schauen, ob die `websocket.io.js` die Funktion `subscribeSpecial` hat?
Siehe https://github.com/Zefau/ioBroker.jarvis/blob/736ac6186c27b51b488f5098496300c7141071ef/lib/websocket.io.js#L823

**Comment by AFPass** [comment]
> Wenn du die Jarvis Instanz durchstartest, steht dann im ioBroker Log die korrekte Version?
> 
> Kannst du bei dir lokal schauen, ob die `websocket.io.js` die Funktion `subscribeSpecial` hat? Siehe
> 
> https://github.com/Zefau/ioBroker.jarvis/blob/736ac6186c27b51b488f5098496300c7141071ef/lib/websocket.io.js#L823
Im Log steht:
starting. Version 3.0.0-beta.7

Die Funktion ist da:
`      subscribeSpecial(messageId, key) {
                this._subscribeOthers[key] = this._subscribeOthers[key] || [];
                
                if (this._subscribeOthers[key].indexOf(messageId) === -1) {
                        this._subscribeOthers[key].push(messageId);
                        this.getSpecial(key);
                }
        }
`
