### ISSUE TITLE
HTML in StateListModule is only available to Pro users v2.2.2

### ISSUE THREAD

**Issue by dan1-de** [Zefau/ioBroker.jarvis#1231]
Hi @Zefau, 

ich nutze schon seit längerem die v2.2.2. 
Seit heute morgen zeigt er mir bei der State List mit HTML den Fehler "HTML in StateListModule is only available to Pro users" an.
Eigentlich sollte das mit der Pro Version doch nur die v3 User betreffen oder ? 

Ich würde gerne die v2 behalten, da ich noch keine Zeit finde auf v3 zu migrieren.

VG
Daniel

**Comment by Floewillinator** [comment]
Hi,
ich habe das selbe Problem allerdings auf v2.2.3.

VG Floewillinator

**Comment by dan1-de** [comment]
Nachtrag: Das runden über die "Datenpunkt Eigenschaften (JSON Format)" funktioniert ebenfalls nicht mehr

**Comment by uwe72** [comment]
Hi,
ich habe das selbe Problem allerdings auf v2.2.1

**Comment by Zefau** [comment]
sollte mit v2.2.5 wieder passen
