### ISSUE TITLE
iFrame - Sandbox options can not be selected after reset

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1232]
V3 Beta 7

When you reset the sandbox options so that nothing is selected, you can no longer select anything from drop down menu

![35AEF6A2-0050-4A54-A073-B96CC2C68CDD](https://user-images.githubusercontent.com/2972703/144228603-76901770-8340-43f5-b312-f47aeb1862fb.GIF)

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.0.0-beta.9`

**Comment by stephan1827** [comment]
Yep, tuts wieder

**Comment by mcuiobroker** [comment]
Mit v3.0.11 wieder nicht auswählbar, nachdem man einmal Sandbox deaktiviert hat:
![image](https://user-images.githubusercontent.com/84818934/154755855-4053d128-f023-4b05-a2c2-fdc5c78b41b2.png)
