### ISSUE TITLE
HistoryGraph Legende

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1235]
Version: v3.0.0-beta.7

Ist der Daten Zoom Slider aus, wird die Legende auf die Beschriftung der X-Achse geblendet.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.8`

**Comment by AFPass** [comment]
Legende oben:
<img width="560" alt="Bildschirmfoto 2021-12-06 um 08 52 47" src="https://user-images.githubusercontent.com/13101074/144808197-413cda6b-fe24-4ee7-be18-ad19af260869.png">

Legende unten:
<img width="560" alt="Bildschirmfoto 2021-12-06 um 08 54 08" src="https://user-images.githubusercontent.com/13101074/144808311-f38d2428-028a-4dfa-b9db-5fa440ded26e.png">

Ist die Legende oben, ist die Beschriftung der X Achse im Daten-Zoom Slider.
Nicht ganz so schlimm ist es, wenn die Legende unten ist.

**Comment by Zefau** [comment]
Kannst du mal einen Screenshot der Widget Konfiguration posten, damit ich alle Einstellungen exakt übernehmen kann?

**Comment by AFPass** [comment]
<img width="1397" alt="image" src="https://user-images.githubusercontent.com/13101074/145106154-0131c6e9-80d2-4eae-920c-abca7db11cdd.png">
<img width="572" alt="image" src="https://user-images.githubusercontent.com/13101074/145106045-3f854f85-f3c8-4a6e-af68-1d812052f2c1.png">


<img width="1397" alt="image" src="https://user-images.githubusercontent.com/13101074/145106203-a728d57c-d459-4854-b0ac-47fa1ae86744.png">
<img width="556" alt="image" src="https://user-images.githubusercontent.com/13101074/145106263-69297382-be5c-4057-b21d-a64c43cac961.png">

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.12`

**Comment by AFPass** [comment]
Passt.
<img width="563" alt="image" src="https://user-images.githubusercontent.com/13101074/145486574-b3210f33-9756-45a0-88b2-5159ef67fe6f.png">

<img width="563" alt="image" src="https://user-images.githubusercontent.com/13101074/145486654-2d8d74ad-7e0c-4c89-a31a-a1337cfd390f.png">
