### ISSUE TITLE
v3: Popup too small

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1236]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
beta-7

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
Popup too small. I found this not very often. It might be that this happens in case a slider is the last element but I'm not sure.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![image](https://user-images.githubusercontent.com/79741077/144321455-b76b0aed-67b0-45fa-b781-d84877a45204.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
Hinweis: War auch schon in der alpha-125 (aktuell meine Produktive Version). Ist mir nur bislang nicht aufgefallen

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.8`

**Comment by RkcCorian** [comment]
Passt, konnte kein Problem mehr finden
