### ISSUE TITLE
jarvis.0.clients.connected leer obwohl verbunden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1237]
`v3.0.0-beta.7`
Der DP jarvis.0.clients.connected ist {} leer, obwohl ein client verbunden ist?
![image](https://user-images.githubusercontent.com/84818934/144342868-33b58e69-82a0-4142-96bf-38ab43c1ad46.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1253

**Comment by Zefau** [comment]
sollte mit `v3.0.0-beta.20` behoben sein

**Comment by Zefau** [comment]
Hinweis: Namespace von eindeutiger ID angepasst auf IP + Browser für eine bessere Lesbarkeit

**Comment by mcuiobroker** [comment]
Funktioniert. Danke.
