### ISSUE TITLE
add option to hide TopBar

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#124]

**Comment by WW1983** [comment]
Wäre es vielleicht möglich zusätzliche Einstellungmöglichkeiten für die TopBar einzufügen. Es wäre schön wenn man die TopBar auf eine Zeile Reduzieren könnte. Und ggf. die Icons "zusammen rücken" können, wenn keine Schrift verwendet wird. Sonst muss man immer Scrollen, wenn etwas mehr Icons vorhanden sind.
![Screenshot 2020-11-24 160255](https://user-images.githubusercontent.com/56581564/100111911-ef3d8a00-2e6e-11eb-8875-bf2a8b1024d6.png)

**Comment by uwe72** [comment]
I would like to ask if this ticket cannot be solved within version 2.0? For me it is not just a minor topic. It changes the final available place for my visualizations.

**Comment by uwe72** [comment]
i pity that the priority of this issue is so low, i my point of view too low because it is a big opticial bug

**Comment by Zefau** [comment]
Why do you need to complain about such a nonsense? First off: This is not a bug, because you have the title and title icon hidden, which causes this. Secondly: With more votes the Feature Request becomes more important. Why should I prioritize this when other Feature Request have way more votes? Thirdly, it is on the Roadmap already.

**Comment by uwe72** [comment]
ok, i shut up from now

**Comment by Zefau** [comment]
I'm sorry if that was rough: I'm happy for all the help and feedback.

I suggest you to "advertise" this Feature Request to get more votes for it. 👍 🥇

**Comment by Zefau** [comment]
added an option in `v2.2.0-beta.5`.

**Comment by uwe72** [comment]
Thanks for resolving this feature request. Works very well! Thanks!
