### ISSUE TITLE
Hinweis aus Instanzübersicht ioBroker Admin 5.2.1

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1241]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/1240

<div type='discussions-op-text'>

<sup>Originally posted by **mcuiobroker** December  2, 2021</sup>
![image](https://user-images.githubusercontent.com/84818934/144348463-d5fe1752-0500-4d46-8e96-0bc36c8a303f.png)
</div>

**Comment by Zefau** [comment]
@mcuiobroker schau nochmal mit `v3.0.0-beta.8`

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.12`
![image](https://user-images.githubusercontent.com/84818934/145121043-2f785f27-7300-4527-9160-ce5676205f65.png)

**Comment by Zefau** [comment]
Der Fehler sollte für neue Installationen behoben sein. Für bestehende Installationen auskunftsgemäß nicht schlimm (siehe https://github.com/hacki11/ioBroker.valloxmv/issues/61#issuecomment-990669269).
