### ISSUE TITLE
DateTime Widget: konfigurierbar machen

### ISSUE THREAD

**Issue by voxid70** [Zefau/ioBroker.jarvis#1242]
Falls möglich sollte das Widget konfigurierbarer gemacht werden. In meinem Fall zum einen, die Schriftgröße und die 
der Kalenderwoche sollte folgendes Erscheinungsbild haben: KW 48 (KW davor und Punkt weg)
![grafik](https://user-images.githubusercontent.com/76115848/144446658-955b9b90-e416-4171-b4b8-c747cf66eb4a.png)

**Comment by Zefau** [comment]
Schriftgröße via CSS

**Comment by mcuiobroker** [comment]
Übergangsweise evtl mit HTML?
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/statehtml/dateweatherdwd

**Comment by mcuiobroker** [comment]
Modul DateTime: Die angezeigten Sonnenaufgang und -untergangszeiten sind immer die von Hamburg, also bei mir jedenfalls.

**Comment by Zefau** [comment]
> Modul DateTime: Die angezeigten Sonnenaufgang und -untergangszeiten sind immer die von Hamburg, also bei mir jedenfalls.

Das wäre aber ein Bug. Eigentlich sollten die Koordinaten, die in ioBroker definiert sind, entsprechend aufgelöst werden. Hast du da welche hinterlegt?

**Comment by mcuiobroker** [comment]
Hast Recht alles zurück, falsche Werte eingegeben gehabt.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.22` habe ich die `KW` angepasst

**Comment by mcuiobroker** [comment]
Bei den Einstellungen zum Modul-> zu große Eingabe-Felder
![image](https://user-images.githubusercontent.com/84818934/176316078-905ae91e-bd24-414e-a4be-3fea2a61669f.png)

**Comment by Zefau** [comment]
Ist bewusst, da mehrzeilenfähig
