### ISSUE TITLE
HistoryGraph - datamin

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1243]
Hat man bei dem HistoryGraph mehr als ein DP zu Anzeige, klappt die Konfiguration der Y Achse mit dataMin und dataMax nicht mehr.
Bei der Anzeige von 2 DP sollte der Eintrag `[{"min":"dataMin","max":"dataMax"},{"min":"dataMin","max":"dataMax"}]` für die Y Achse links und rechts den Wertebereich anpassen.

**Comment by Zefau** [comment]
Du bist Pro User, korrekt? Die Konfiguration der Achsen ist ein Pro-Feature.

Wenn du zwei Y-Achsen definierst, gehe ich davon aus, dass du jeweils ein DP einer Achse zugewiesen hast?
Mit der von dir geposteten Konfiguration fehlt eine Achsen-ID

**Comment by Zefau** [comment]
In beta.7 werden die Achsen nicht korrekt aktualisiert, wenn die Seite nicht refreshed wird. Das behebe ich. Ansonsten sollte die Konfiguration, die du angegeben hast aber funktionieren (sofern Pro). Mach mal bitte nach der Änderung einen full-refresh der Seite.

**Comment by AFPass** [comment]
Ja. Pro User. 
Ja zwei DP. 
Einer soll für linke und einer für rechte y-Achse sein.

Wie gebe ich die Achsen ID bei der Konfiguration an?

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/historygraph#beispiel-fuer-temperaturen

**Comment by Zefau** [comment]
> Ja. Pro User.
> Ja zwei DP.
> Einer soll für linke und einer für rechte y-Achse sein.
> 
> Wie gebe ich die Achsen ID bei der Konfiguration an?

Mit beta.8 sollte es auch ohne ID gehen.

Hast du denn mal einen kompletten Refresh der Seite gemacht, wie geschrieben?

> Wenn du zwei Y-Achsen definierst, gehe ich davon aus, dass du jeweils ein DP einer Achse zugewiesen hast? 

Kannst du einfach mal die Konfiguration des Widgets mit den zugewiesenen Geräten screenshoten?

Und bitte auch mal ein Screenshot des Ergebnisses (also dem Layout; nach kompletten Seitenreload).

**Comment by AFPass** [comment]
Ja. kompletter Refresh.

Das sind die Einstellungen:
<img width="1456" alt="Bildschirmfoto 2021-12-06 um 08 46 31" src="https://user-images.githubusercontent.com/13101074/144807430-7d81efad-6087-4f56-bb28-d2d42a22a396.png">

Und das Ergebnis:
<img width="560" alt="Bildschirmfoto 2021-12-06 um 08 49 54" src="https://user-images.githubusercontent.com/13101074/144807793-0b278c29-84d7-443e-8719-702267134754.png">

Die Linien sehen jetzt schon etwas anders aus. Aber es fehlt die Beschriftung der Y-Achsen.

**Comment by Zefau** [comment]
Hast du das -5 / +5 mal raus gelassen? Bin mir nicht sicher, ob das so unterstützt wird.

**Comment by AFPass** [comment]
<img width="551" alt="Bildschirmfoto 2021-12-06 um 10 37 56" src="https://user-images.githubusercontent.com/13101074/144823412-fd9d78d8-7896-4d88-8e38-bc427afddb05.png">

Ohne -5/+5 geht es.

Die Linen sind zwar unübersichtlich, aber es klappt. Vielleicht kannst Du da noch etwas optimieren.

**Comment by Zefau** [comment]
Was soll ich genau optimieren? Etwas heller machen?

**Comment by Zefau** [comment]
sonst schau auch gerne in der Echarts Doku was noch mögloch ist

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1255

**Comment by AFPass** [comment]
> Was soll ich genau optimieren? Etwas heller machen?

Bei dataMin/dataMax sind ja nun sehr viele Linien drinnen wenn der Wertebereich nicht gleich ist.
Weiß nicht ob die Chart das anbietet, aber übersichtlicher wäre es, wenn es weniger Linien sind. Hm, lässt sich schwer erklären was ich meine.

<img width="550" alt="image" src="https://user-images.githubusercontent.com/13101074/144850915-3baea3cf-fcd7-4979-9252-3973aeb696dc.png">

Zum Beispiel die Linie für 50%. Diese gar nicht erst Zeichnen und dafür die 30° Linie nutzen und rechts den Wert berechnen der da hin müsst. 47/48 % oder so.

**Comment by Zefau** [comment]
Da müsstest du schauen ob Echarts da eine Option anbietet. Das Zeichen der Linie kann ich sonst nicht beeinflussen.

**Comment by AFPass** [comment]
> Da müsstest du schauen ob Echarts da eine Option anbietet. Das Zeichen der Linie kann ich sonst nicht beeinflussen.

Ok. Danke
