### ISSUE TITLE
Add Stop DP for HmIP-BROLL

### ISSUE THREAD

**Issue by dentro-git** [Zefau/ioBroker.jarvis#1247]
Hey, ich nutze inzwischen nur noch Jarvis für meine Steuerung der Home Automation.
Mich stört schon länger das bei den HMIP-BROLL Adaptern die ich für alle meien Jalousien verwende der Stop-Knopf nicht funktioniert.
Ich habe hier jetzt mal testweise den entsprechenden Datenpunkt im IOBroker als Stop DP Hinzugefügt und alles funktioniert super.

Diesen könnte man in den Standard übernehmen, das würde denke ich vielen das leben leichter machen.

![image](https://user-images.githubusercontent.com/77006779/144562365-4bf95883-94e1-4528-8d8f-4c7f1b6e8968.png)
![image](https://user-images.githubusercontent.com/77006779/144562773-b6855881-7f17-4d72-95e7-c2c44f2b8154.png)

Zudem arbeitet HMIP für den Shutter level mit einem Wert 0=open und 1=closed, das habe ich so angepasst, könnte auch in den Standard..
![image](https://user-images.githubusercontent.com/77006779/144562821-eee945e0-e0ea-4dea-9196-b2da849e8b94.png)

Hier nochmal meine Konfig zu dem Fenster. Da kann man bestimmt noch viel besser machen. Habe es soweit angepasst das es funktioniert.
```
  "fensterbüro_52263": {
    "name": "Fenster Büro",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "unreach": {
        "showState": false,
        "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.0.unreach",
        "action": "",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "unreach"
      },
      "lowBattery": {
        "showState": false,
        "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.0.lowBat",
        "action": "",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "lowBattery"
      },
      "level": {
        "showState": true,
        "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.shutterLevel",
        "action": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.shutterLevel",
        "properties": {
          "min": "1",
          "max": "0"
        },
        "LevelBodyConfig": {
          "step": "0.1",
          "val": "value"
        },
        "display": "",
        "unit": "",
        "icon": {
          "default": "window-shutter-open",
          "<0.2": "window-shutter-open",
          ">=0.8": "window-shutter"
        },
        "label": "",
        "bodyElement": "LevelBody",
        "stateKey": "level",
        "BlindLevelActionConfig": {}
      },
      "activity": {
        "showState": false,
        "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.processing",
        "action": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.stop",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "activity"
      },
      "stop": {
        "stateKey": "stop",
        "showState": true,
        "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.stop",
        "IconButtonActionConfig": {}
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "HomeMatic IP via Access Point",
        "namespace": "hmip"
      },
      "_updated": 1624005671976
    },
    "id": "fensterbüro_52263",
    "revision": "ebd85"
  },
```
Gruß und sorry wenn bei mir die Sachen immer etwas gestückelt kommen. Hab viel zu wenig Zeit mich damit richtig auseinander zu setzten.

**Comment by dentro-git** [comment]
> Hey, ich nutze inzwischen nur noch Jarvis für meine Steuerung der Home Automation. Mich stört schon länger das bei den HMIP-BROLL Adaptern die ich für alle meien Jalousien verwende der Stop-Knopf nicht funktioniert. Ich habe hier jetzt mal testweise den entsprechenden Datenpunkt im IOBroker als Stop DP Hinzugefügt und alles funktioniert super.
> 
> Diesen könnte man in den Standard übernehmen, das würde denke ich vielen das leben leichter machen.
> 
> ![image](https://user-images.githubusercontent.com/77006779/144562365-4bf95883-94e1-4528-8d8f-4c7f1b6e8968.png) ![image](https://user-images.githubusercontent.com/77006779/144562773-b6855881-7f17-4d72-95e7-c2c44f2b8154.png)
> 
> Zudem arbeitet HMIP für den Shutter level mit einem Wert 0=open und 1=closed, das habe ich so angepasst, könnte auch in den Standard.. ![image](https://user-images.githubusercontent.com/77006779/144562821-eee945e0-e0ea-4dea-9196-b2da849e8b94.png)
> 
> Hier nochmal meine Konfig zu dem Fenster. Da kann man bestimmt noch viel besser machen. Habe es soweit angepasst das es funktioniert.
> 
> ```
>   "fensterbüro_52263": {
>     "name": "Fenster Büro",
>     "icon": "",
>     "label": "",
>     "function": "blind",
>     "states": {
>       "unreach": {
>         "showState": false,
>         "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.0.unreach",
>         "action": "",
>         "label": "",
>         "bodyElement": "LastChangeBody",
>         "stateKey": "unreach"
>       },
>       "lowBattery": {
>         "showState": false,
>         "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.0.lowBat",
>         "action": "",
>         "label": "",
>         "bodyElement": "LastChangeBody",
>         "stateKey": "lowBattery"
>       },
>       "level": {
>         "showState": true,
>         "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.shutterLevel",
>         "action": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.shutterLevel",
>         "properties": {
>           "min": "1",
>           "max": "0"
>         },
>         "LevelBodyConfig": {
>           "step": "0.1",
>           "val": "value"
>         },
>         "display": "",
>         "unit": "",
>         "icon": {
>           "default": "window-shutter-open",
>           "<0.2": "window-shutter-open",
>           ">=0.8": "window-shutter"
>         },
>         "label": "",
>         "bodyElement": "LevelBody",
>         "stateKey": "level",
>         "BlindLevelActionConfig": {}
>       },
>       "activity": {
>         "showState": false,
>         "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.processing",
>         "action": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.stop",
>         "label": "",
>         "bodyElement": "LastChangeBody",
>         "stateKey": "activity"
>       },
>       "stop": {
>         "stateKey": "stop",
>         "showState": true,
>         "state": "hmip.0.devices.3014F711A0001118A9914BCE.channels.1.stop",
>         "IconButtonActionConfig": {}
>       }
>     },
>     "options": {},
>     "attributes": {
>       "imported": true,
>       "manufacturer": {
>         "name": "HomeMatic IP via Access Point",
>         "namespace": "hmip"
>       },
>       "_updated": 1624005671976
>     },
>     "id": "fensterbüro_52263",
>     "revision": "ebd85"
>   },
> ```
> 
> Gruß und sorry wenn bei mir die Sachen immer etwas gestückelt kommen. Hab viel zu wenig Zeit mich damit richtig auseinander zu setzten.

**Comment by dentro-git** [comment]
sorry :-(

**Comment by Zefau** [comment]
Die Import-Konfiguration von`HmIP-BROLL` sieht bereits den `stop` Datenpunkt vor:

```
"HmIP-BROLL": {
	"level": {
		"state": ".channels.1.shutterLevel",
		"action": ".channels.1.shutterLevel",
		"properties": {
			"min": "0",
			"max": "1"
		}
	},
	"activity": {
		"state": ".channels.1.processing"
	},
	"stop": {
		"action": ".channels.1.stop"
	}
}
```

Kannst du nochmal via Importer schauen, ob dieser wirklich nicht angeboten wird?
Nicht existierende Datenpunkte werden durch den Importer rausgesammelt. Das könnte hier passiert sein, auch wenn es keinen Sinn ergibt, da dieser ja existiert.

**Comment by Zefau** [comment]
Die `properties` für `level` habe ich aufgenommen.

**Comment by dentro-git** [comment]
Hey, ich habe es nochmal alles neu importieren lassen und dann sieht das so aus:

```
 "fensterbad_6036c": {
    "id": "fensterbad_6036c",
    "name": "Fenster Bad",
    "function": "blind",
    "states": {
      "unreach": {
        "state": "hmip.0.devices.3014F711A0001118A9914BCF.channels.0.unreach"
      },
      "lowBattery": {
        "state": "hmip.0.devices.3014F711A0001118A9914BCF.channels.0.lowBat"
      },
      "level": {
        "state": "hmip.0.devices.3014F711A0001118A9914BCF.channels.1.shutterLevel",
        "action": "hmip.0.devices.3014F711A0001118A9914BCF.channels.1.shutterLevel",
        "actionElement": "InputAction"
      },
      "activity": {
        "state": "hmip.0.devices.3014F711A0001118A9914BCF.channels.1.processing"
      },
      "stop": {
        "action": "hmip.0.devices.3014F711A0001118A9914BCF.channels.1.stop",
        "actionElement": "IconButtonAction"
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "HomeMatic IP via Access Point",
        "namespace": "hmip"
      }
    }
  },
```

Stop ist also da 

Bezüglich der properties hat er das leider nicht übernommen. Hier habe ich jetzt händisch wieder die 3 Anpassungen für 
- Datenpunkt Eigenschaften
- Icon
- Body Element
selber gesetzt so das die angepasste Kombi wie folgt aussieht

```
 "fensterbad_6036c": {
    "name": "Fenster Bad",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "unreach": {
        "state": "hmip.0.devices.3014F711A0001118A9914BCF.channels.0.unreach",
        "stateKey": "unreach"
      },
      "lowBattery": {
        "state": "hmip.0.devices.3014F711A0001118A9914BCF.channels.0.lowBat",
        "stateKey": "lowBattery"
      },
      "level": {
        "state": "hmip.0.devices.3014F711A0001118A9914BCF.channels.1.shutterLevel",
        "action": "hmip.0.devices.3014F711A0001118A9914BCF.channels.1.shutterLevel",
        "actionElement": "BlindLevelAction",
        "stateKey": "level",
        "properties": {
          "min": "1",
          "max": "0"
        },
        "LevelBodyConfig": {
          "step": "0.1",
          "val": "val"
        },
        "icon": {
          "default": "window-shutter-open",
          "<0.2": "window-shutter-open",
          ">=0.8": "window-shutter"
        },
        "bodyElement": "LevelBody",
        "showState": false
      },
      "activity": {
        "state": "hmip.0.devices.3014F711A0001118A9914BCF.channels.1.processing",
        "stateKey": "activity"
      },
      "stop": {
        "action": "hmip.0.devices.3014F711A0001118A9914BCF.channels.1.stop",
        "actionElement": "IconButtonAction",
        "stateKey": "stop"
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "HomeMatic IP via Access Point",
        "namespace": "hmip"
      }
    },
    "id": "fensterbad_6036c",
    "revision": "1b50c"
  },
```

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.0.0-beta.10`

**Comment by dentro-git** [comment]
so, mit  `v3.0.0-beta.12` sieht es wie folgt aus:

an den drei markierten Stellen musste ich nochmal Hand anlegen
![image](https://user-images.githubusercontent.com/77006779/145346613-12a7518b-e368-40d7-834c-28e444dea315.png)
1.) min - max vertauscht, dann gehen die Level Action Knöpfe fasch rum....
2.) die Schrittweite 1 macht bei 0 bis 1 Wertebereich nicht viel Sinn
3.) ich bevorzuge beim Action Type den Blind Level Action


dann sieht es so aus und funktioniert :-)
![image](https://user-images.githubusercontent.com/77006779/145346675-264ff7b1-8ea4-41e0-a587-e25110de126a.png)

**Comment by Zefau** [comment]
Danke für die Details! Probier nochmal bitte mit `v3.0.0-beta.21`.

**Comment by Zefau** [comment]
@dentro-git

**Comment by dentro-git** [comment]
@Zefau, habe gerade mit `v3.0.4-beta.1` getestet.

Leider sind jetzt bei allen meinen Shuttern die Stop Datenpunkte aus der Shutter Config verschwunden.
Und das nicht nur für die HMIP Datenpunkte sondern auch für meine zu Fuß angelegten KLF200 DAtenpunkte.
Mit der `v3.0.1` gestern ging das alles noch

![image](https://user-images.githubusercontent.com/77006779/147909260-4dd334ec-0733-43cc-ac16-8ab6b9bb3f97.png)

**Comment by Zefau** [comment]
Ist testweise wegen https://github.com/Zefau/ioBroker.jarvis/issues/1093#issuecomment-1003901533

**Comment by dentro-git** [comment]
Ok, habe gerade mit `v3.0.4-beta.2` getestet.

Für die HMIP Geräte ist aller wieder Takko.
Hier meine HMIP Geräte:
![image](https://user-images.githubusercontent.com/77006779/148030356-b6c68a16-ce50-4fcb-a389-1e8fc8f0b802.png)

Leider bei meinen KLF Dachfenstern immer noch weg :-(
![image](https://user-images.githubusercontent.com/77006779/148030653-9a6b8c99-52df-4c80-b7ea-b14135c15640.png)
![image](https://user-images.githubusercontent.com/77006779/148031241-9934912c-757a-4cfc-9cf3-c3174657c255.png)


```
"670d7642-8b8c-43b5-9e34-3deb36d09a6f": {
    "name": "Dachfenster Bad DG",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "activity": {
        "showState": false,
        "state": "klf200.0.products.0.runStatus",
        "label": "",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "activity"
      },
      "level": {
        "showState": false,
        "state": "klf200.0.products.0.currentPosition",
        "action": "klf200.0.products.0.targetPosition",
        "properties": {
          "min": "100",
          "max": "0"
        },
        "display": {},
        "unit": "%",
        "LevelBodyConfig": {
          "step": "10"
        },
        "icon": {
          "default": "window-shutter-open",
          "<20": "window-shutter-open",
          ">=80": "window-shutter"
        },
        "label": "",
        "BlindLevelActionConfig": {
          "activityState": "activity",
          "stopAction": "stop"
        },
        "bodyElement": "LastChangeBody",
        "stateKey": "level"
      },
      "stop": {
        "showState": false,
        "state": "klf200.0.products.0.stop",
        "label": "",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "stop"
      }
    },
```

**Comment by Zefau** [comment]
@dentro-git passt es inzwischen mit `v3.0.9`?

**Comment by dentro-git** [comment]
hey, ja mit `v3.0.9` ist er wieder da, und funktioniert auch. 
Der Knopf "Stop" wird nur leider nicht rot wenn das Rolo fährt. (Für HMIP geht alles! nur bei meinen Dachfenstern habe ich das Thema.)

Sieht im Moment also alles recht gut aus. Ohne kleine Baustellen würde es ja auch keinen Spaß machen. 

Gruß

**Comment by Zefau** [comment]
Dort wo der Stop-Button nicht rot wird, ist dort `activity` ein Boolean? Betrifft das `klf200.0.products.0.runStatus`?

**Comment by dentro-git** [comment]
Nein, es ist kein Boolean und ja, es betrifft den `klf200.0.products.0.runStatus`

Hab den so konfiguriert:
![image](https://user-images.githubusercontent.com/77006779/149655433-e67c41a6-58b1-4b93-95c9-6c147e0095ef.png)

Das wird aber das Problem sein, kann man da die Variable über ein JSON anpassen?

Gruß

**Comment by Zefau** [comment]
dann einfach einen Datenpunkt in jarvis anlegen, der Boolean ist und dem Level in in den Component Options zuordnen (statt `activity`).

Also hier dann einen Datenpunkt auswählen, der Boolean ist:

![image](https://user-images.githubusercontent.com/14368811/149656495-882787ee-7885-497f-b84e-f2604bbafcb2.png)

**Comment by martinbrecko** [comment]
@Zefau Kannst du den letzten Punkt nochmal für "doofe" erklären? 

Ich habe jetzt meine HmIP-Brolls über den Devices-Adapter in Jarvis eingepflegt, aber dort funktioniert dann die Anzeige der Aktivität nicht mehr.
