### ISSUE TITLE
F2 oder Konfiguration sporadisch nicht erreichbar

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1250]
`v3.0.0-beta.7`
Nach Bearbeitung vom Layout und Speicherung kam es einige Male vor, dass die Konfiguration mit F2 nicht mehr erreichbar war.
Bei mir hat sogar eine Eingabe der Adresse `http://192.168.178.89:8082/jarvis/index.html#/configuration` in die Browserzeile zeitweise nicht geholfen.

https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-beta-just-another-remarkable-vis/70 ff
Dort konnte man dann mit Eingabe von `http://192.168.178.XXX:8082/jarvis/index.html#/configuration/styles` wieder in die Konfiguration.

**Comment by martenumberto** [comment]
Habe auch grade das Problem nachdem ich ein Gerät geändert habe. Neustart hat nichts gebracht. Auf Styles und co. komme ich über die Direkte URL, allerdings lässt sich der Tab für die Gerätekonfig nicht mehr öffnen. Da tut sich einfach nichts.

**Comment by mcuiobroker** [comment]
```http://192.168.178.10:8082/jarvis/index.html#/configuration/devices```
Funktioniert der direkte Zugang?
Und öffne mal das Get

**Comment by Zefau** [comment]
sollte mit `v3.0.0-beta.10` nicht mehr vorkommen

**Comment by mcuiobroker** [comment]
`v3..0-beta.15` bislang keine weiteren Effekte.
