### ISSUE TITLE
Error Failed connecting to http://.... Rote Error Seite

### ISSUE THREAD

**Issue by fladdie** [Zefau/ioBroker.jarvis#1251]
Bei dem Versuch auf Jarvis zuzugreifen kommt folgender Fehler:
Interessanterweise tritt dies nur bei Chrome und Edge auf. Bei Firefox geht es. Den Cache habe ich vollständig gelöscht.

verwendet wird v3.0.0-beta.7
Verschiedene Ports und Socket Ports habe ich schon durchprobiert. Ebenso habe ich es mit installiertem Socketio Adapter + Umstellung im Web Adapter auf Socketio versucht.

![image](https://user-images.githubusercontent.com/6246796/144746641-0f8f206d-eb1f-40dd-9236-bee7919b4494.png)

**Comment by Zefau** [comment]
Hast du das SSL Zertifikat akzeptiert, was hinter der HTTPs Seite liegt?
