### ISSUE TITLE
jarvis ist wegen eines Fehlers abgestürzt V2.2.1

### ISSUE THREAD

**Issue by stoertebecker2** [Zefau/ioBroker.jarvis#1252]
Ich habe das erste mal jarvis über iobroker nach der Installation des Adapters geöffnet. Nach dem ich angegeben habe, dass ich keine automatische Einrichtung möchte, sondern dies manauell tuen möchte, ist jarvis abgestürzt:

jarvis Version: 2.2.1
iobroker Version: 5.1.25
![Absturz](https://user-images.githubusercontent.com/95575525/144749391-5e7cce87-54c9-4275-b13d-0545770d1837.jpg)

![k1](https://user-images.githubusercontent.com/95575525/144749398-a2bcfa59-adc1-43b6-b7bb-93e0b860ca9b.jpg)
![konsole](https://user-images.githubusercontent.com/95575525/144749402-76becd70-3de3-4cef-a628-411dc31f95a7.jpg)

iobroker und jarvis laufen auf einem raspberry Pi 3b+.

**Comment by Zefau** [comment]
Bitte direkt auf v3 gehen (Installation aktuell noch via Github URL, siehe auch https://mcuiobroker.gitbook.io/jarvis-infos/v3-fuer-einsteiger/installation-jarvis-v3)
