### ISSUE TITLE
Automatische Löschung der clients, die einen Tag lang nicht genutzt wurden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1253]
Da die Liste der clients teilweise sehr lang wird durch Änderung / Updates der Browser usw, wäre es sinnvoll die client-Verbindungen herauszunehmen, die länger als einen TAG nicht genutzt wurden:
![image](https://user-images.githubusercontent.com/84818934/144755946-1a0016e4-8961-4e38-901e-d67097be00bb.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-beta.20` behoben sein

**Comment by mcuiobroker** [comment]
setTabId funktioniert nicht mehr.
Was muss man jetzt angeben? Früher zB.: home0 (Id vom TAB)

**Comment by Zefau** [comment]
Das connected unter Info ist für ioBroker und bezieht sich auf die Instanz von jarvis selbst.

TabId ist nach vor die ID

**Comment by Zefau** [comment]
Sorry, hab mich vertan. Das andere connected ist alt. Kannst du löschen.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.22` sollte das Wechseln des Tabs wieder funktionieren

**Comment by mcuiobroker** [comment]
Wechsel funktioniert.
Meldungen die keinen Sinn machen, da sich der ID-Aufbau sich geändert hat?

```
jarvis.0 | 2021-12-25 03:33:37.610 | warn | State "jarvis.0.clients.b7b2a111-e201-5d9a-9574-52e83b7c9aa7.setTabId" has no existing object, this might lead to an error in future versions
```

**Comment by Zefau** [comment]
Jo einfach Baum Löschen

**Comment by mcuiobroker** [comment]
Es ist jetzt ein Tag vergangen:
![image](https://user-images.githubusercontent.com/84818934/147390675-e932b254-c724-45e5-82ac-a0a2abee3764.png)

Wann werden denn die "alten" clients gelöscht?
Bislang wurde keiner gelöscht.
![image](https://user-images.githubusercontent.com/84818934/147390696-48799067-f3a2-46a6-ac28-46649f78f5ae.png)

**Comment by Zefau** [comment]
Siehe https://github.com/Zefau/ioBroker.jarvis/blob/16b31498f1f84660b0b5f02ef4aeeca1935236e7/jarvis.js#L488

Wenn der Client vgl. `lastSeen` 7d nicht gesehen wurde, wird er entfernt.
