### ISSUE TITLE
HistoryGraph: Löschen von Y-Achsen Konfig

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1254]
Beim löschen der Konfiguration der Y-Achse kommt es zu einem Fehler:

<img width="743" alt="Bildschirmfoto 2021-12-06 um 09 09 08" src="https://user-images.githubusercontent.com/13101074/144810462-2bced8d2-594b-460e-8047-95783f838f42.png">
(Die Konfig ist nur Beispielhaft)

Beiden DP ist jeweils eine Y-Achsen Konfiguration zugeordnet.

Wird nun der Eintrag in der Konfiguration Y-Achsen gelöscht, wird keine Beschriftung der Y-Achse angezeigt.
<img width="743" alt="Bildschirmfoto 2021-12-06 um 09 09 17" src="https://user-images.githubusercontent.com/13101074/144810759-c0e52227-7605-4276-b40a-cca0e7f20f78.png">

Der Grund scheint zu sein, das für DP2 die Konfiguration nicht richtig gelöscht wird
<img width="743" alt="Bildschirmfoto 2021-12-06 um 09 09 40" src="https://user-images.githubusercontent.com/13101074/144810841-d66a7956-7ffe-4a35-a911-8a559f5eb7aa.png">
.

**Comment by Zefau** [comment]
Ich verstehe das Problem nicht ganz. Wie hast du denn die Y-Achse "gelöscht"? Und was genau ist der Fehler?

Das Eingabefeld muss komplett leer sein, wenn du wirklich löschen willst. Wenn dort `[{"":""},{"":""}]` steht, dann ist das ein syntaktisch valider Eintrag. Die Frage ist, wie kam der Zustande!?

> Wird nun der Eintrag in der Konfiguration Y-Achsen gelöscht, wird keine Beschriftung der Y-Achse angezeigt.

Das ist auch korrekt und gewollt. Wenn du keine Y-Achsen definierst, dann gibt es nur eine und alle DPs werden dieser einen Achse zugeordnet.

**Comment by AFPass** [comment]
[{"":""},{"":""}] ist nur Beispielhaft. Der Fehler kommt auch zum Beispiel bei  [{"min":"dataMin"},{"max":"dataMax"}].

1. Im Feld "Konfiguration der y-Achse" steht eine gültige Konfiguration
![](https://user-images.githubusercontent.com/13101074/144810462-2bced8d2-594b-460e-8047-95783f838f42.png)
Jedem DP ist eine y-Achse zugewiesen

2. Das Feld "Konfiguration der y-Achse" wird geleert
![](https://user-images.githubusercontent.com/13101074/144810759-c0e52227-7605-4276-b40a-cca0e7f20f78.png)

3. Nach dem Speichern und laden der Seite mit dem HistoryGraph Widget wird das Widget ohne Beschreibung der y-Achse angezeigt




Gibt man nun in der Konfiguration vom Widget im Feld "Konfiguration der y-Achse" einen Wert ein, erscheint auch beim DP wieder das Feld "Y Axis". Dort ist zu sehen, dass im DP1 das Feld leer ist und im DP2 das Feld mit "1" gefüllt ist.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.12`
