### ISSUE TITLE
HistoryGraph: Farbe y Skala

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1255]
Werden für die y-Achse links und rechts Gültigkeitsbereiche festgelegt, sind die Linien zur Markierung Schwarz.
Ohne Gültigkeitsbereiche leicht grau.
<img width="547" alt="Bildschirmfoto 2021-12-06 um 10 52 56" src="https://user-images.githubusercontent.com/13101074/144825556-a1eac6d1-57c5-43ce-a729-9beca3194da4.png">

**Comment by Zefau** [comment]
mit `v3.0.0-beta.11` farblich harmonisiert

**Comment by AFPass** [comment]
Jap. Passt.
