### ISSUE TITLE
Unterschiedlich Anzeige von Gerät / Widget in der Übersicht

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1256]
Vielleicht auch nur ein Verständnis Problem bei mir.
In der Gerätliste werden die Geräte mit Namen angezeigt:
<img width="607" alt="image" src="https://user-images.githubusercontent.com/13101074/144864102-216d2761-6fb9-4b6c-8702-9fee8dabba87.png">

In der Widgetliste werden die Widget mit dem Label angezeigt:
<img width="570" alt="image" src="https://user-images.githubusercontent.com/13101074/144864250-2feb46c7-bcf2-48af-8da6-396bf5e54abe.png">

Ordne ich einem Widget ein Gerät zu, wähle ich das Gerät anhand des Namens aus:
<img width="485" alt="image" src="https://user-images.githubusercontent.com/13101074/144864437-78ea29e6-55df-4666-a35a-811cbf7c8862.png">

Das Widget wird im Layout über den Titel zugeordnet.
![image](https://user-images.githubusercontent.com/13101074/144893389-5a34baf1-506d-4b1f-b410-ccc392da040d.png)

In der Anzeige ist dann Widget-Titel und Gerät-Label
<img width="564" alt="image" src="https://user-images.githubusercontent.com/13101074/144894554-317c57e7-6199-46cf-858d-651eb08d7bda.png">

Müsste im Frontend nicht der Widget-Label zu sehen sein statt des Titels?

Ich finde die Unterschiedlichen Bezeichnungen mit Titel / Name leicht verwirrend.

Geräte-Name / Widget-Name sollte doch im Backend überall in den Auswahllisten sein und
Geräte-Label / Widget-Label sollte doch dann im Frontend sein?

**Comment by Zefau** [comment]
Valider Punkt, den ich anpassen sollte.

Aktuell noch nicht durchgehend so umgesetzt, aber mein Vorschlag:

>  In der Gerätliste werden die Geräte mit Namen angezeigt:

- [x] Name für Frontend / Backend
- [ ] Label für Backend (überschreibt Name) [ falls man ein vom Gerät abweichenden Bezeichner definieren möchte ]

> In der Widgetliste werden die Widget mit dem Label angezeigt:

- [x] Hier ist es bereits so, dass der Titel (= Name) greift, aber vom Label überschrieben wird [ falls man ein vom Titel abweichenden Bezeichner definieren möchte ]

> Ordne ich einem Widget ein Gerät zu, wähle ich das Gerät anhand des Namens aus:

- [ ] hier würde ich neben dem Namen auch das Label bei der Suche berücksichtigen

> Das Widget wird im Layout über den Titel zugeordnet.

- [ ] hier würde ich neben dem Titel dann auch das Label bei der Suche berücksichtigen

> In der Anzeige ist dann Widget-Titel und Gerät-Label

Das ist so korrekt. Widget-Label ist für das Backend bestimmt.

- [ ] Geräte-Label ist fälschlicherweise im Frontend berücksichtigt, das stimmt. Die Reihenfolge sollte sein: Layout Label -> Datenpunkt Label -> Geräte Name

**Comment by Zefau** [comment]
mit `v3.0.0-beta.17` - wie im vorherigen Post dargestellt - angeglichen
