### ISSUE TITLE
HistoryGraph: Widget Link Aufruf

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1257]
Ich habe zwei Widget per Widget Link mit einander verknüpft. Dabei ist ein Widget davon ein HistoryGraph.
Springe ich nun von W1 zu W2 mit dem HistoryGraph ist die Anzeige wie es soll.
Springe ich von W2 zu W1 und wieder zurück zu W2 ist der Data Zoom Slider voll aufgezogen.

Beim ersten öffnen:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/13101074/144906028-6238c45e-4474-465b-a6a8-1072a6a5336e.png">

Beim zweiten öffnen:
<img width="558" alt="image" src="https://user-images.githubusercontent.com/13101074/144906072-26a05e61-1aad-4971-b33c-b6aff5105357.png">

**Comment by Zefau** [comment]
mit der aktuellen beta kannst du die Breite des Daten-Zoom Sliders einstellen (0 bis 100):

![image](https://user-images.githubusercontent.com/14368811/146264149-af1d7d1c-e260-492a-a5c5-c2cfdc5fd901.png)
