### ISSUE TITLE
jsonTable: Spalte (Sortierung) in Widget Eigenschaft wird nicht berücksichtigt

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#1258]
Jarvis 3 Beta 10

Wenn ich in den Widget Eigenschaften der json Table die Spalte Status zum Sortieren angebe, wird nicht automatisch danach sortiert:
![image](https://user-images.githubusercontent.com/16526471/144936467-a57cd79e-2ff7-4dca-b092-f74ce927a625.png)
![image](https://user-images.githubusercontent.com/16526471/144936505-a04eecfa-5a64-4f93-ae2e-ce4c93603676.png)

Eine manuelle Sortierung funktioniert:
![image](https://user-images.githubusercontent.com/16526471/144936552-f1d5691a-9474-4534-8676-d4876e5b97e8.png)

Ist es möglich im Spalteneditor im JSON eine Sortierung der Spalte(n) einzutragen?

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/jsontable/v3.x.x
https://quasar.dev/vue-components/table#defining-the-columns
```
 sortable: true,

    // (optional) compare function if you have
    // some custom data or want a specific way to compare two rows
    sort: (a, b, rowA, rowB) => parseInt(a, 10) - parseInt(b, 10),
    // function return value:
    //   * is less than 0 then sort a to an index lower than b, i.e. a comes first
    //   * is 0 then leave a and b unchanged with respect to each other, but sorted with respect to all different elements
    //   * is greater than 0 then sort b to an index lower than a, i.e. b comes first

    // (optional) override 'column-sort-order' prop;
    // sets column sort order: 'ad' (ascending-descending) or 'da' (descending-ascending)
    sortOrder: 'ad', // or 'da'
```

**Comment by stony2k** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/jsontable/v3.x.x
-> Habe ich mir angeschaut und daraufhin zum Test Formatierungen erstellt:

`[
  {
    "field": "lfd",
    "label": "laufende Nummer",
    "visible": false
  },
  {
    "field": "Sensor ID",
    "label": "Sensor ID",
    "visible": false
  },
  {
    "field": "Sensor Name",
    "label": "Name",
    "visible": true
  },
  {
    "field": "Raum",
    "label": "Raum",
    "visible": true
  },
  {
    "field": "U Nenn",
    "label": "Nennspannung",
    "visible": true
  },
  {
    "field": "U Ist",
    "label": "Ist-Spannung",
    "visible": true
  },
  {
    "field": "U Limit",
    "label": "",
    "visible": true
  },
  {
    "field": "%bat",
    "label": "Akkustand",
    "visible": true
  },
  {
    "field": "%live",
    "label": "verbleibend",
    "visible": false
  },
  {
    "field": "Status",
    "label": "Status",
    "visible": true,
    "sortable": true,
    "sortOrder": "ad"
  },
  {
    "field": "DC",
    "label": "Deadcheck eingerichtet?",
    "visible": true
  }
]`

Leider keine automatische Sortierung.

**Comment by mcuiobroker** [comment]
Der Eintrag wäre aus meiner Sicht so schon richtig:
```{ "field": "Status", "label": "Status", "visible": true, "sortable": true, "sortOrder": "ad" }```
Muss @zefau sich anschauen.

**Comment by OberstVonGatow** [comment]
Funktioniert bei mir leider auch nicht. Ich hätte gern nach Datum Absteigend sortiert.
{ "label": "Datum", "sortable": true, "sortOrder": "da" } funktioniert aber nicht.

**Comment by Zefau** [comment]
Eine initiale Sortierung ist nicht implementiert aktuell. `sortable` steuert lediglich, dass eine Spalte grundsätzlich sortierbar ist.

**Comment by stony2k** [comment]
@Zefau: Worauf bezieht sich die Einstellung **Spalte (Sortierung)**? Denn sortierbar sind ja alle Spalten. Auch ohne JSON Formatierung.

**Comment by Zefau** [comment]
Jo, stimmt. Ich prüfe das eben

**Comment by Zefau** [comment]
mit `v3.0.0-beta.14` sollte es wieder passen

**Comment by stony2k** [comment]
Die Einstellung **Spalte (Sortierung)** sortiert nun automatisch in der Beta 14. Im JSON angegebenes **"sortOrder": "da"** wird leider noch ignoriert (**Spalte (Sortierung)** vorher geleert).

**Comment by OberstVonGatow** [comment]
Dachte mir ist ja kein Problem mach ich mir ein kurzes Script, dass mir die Werte einfach umsortiert in einen separaten Datenpunkt schreibt. Sieht aber so aus als wird immer automatisch aufsteigend sortiert. Selbst wenn ich die Sortierbarkeit im Layout komplett abschalte.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.15`

**Comment by stony2k** [comment]
Leider keine automatische Sortierung im JSON mit
> "field": "Status", "label": "Status", "visible": true, "sortable": true, "sortOrder": "ad" }

oder

> "field": "Status", "label": "Status", "visible": true, "sortOrder": "ad" }

Es lässt sich aber weiterhin über die Widget Einstellung sortieren.

Leider ist jetzt etwas "neues" kaputt gegangen. Konnte man vorher noch per **"Max. Einträge"** = 0 sich alle Einträge anzeigen lassen, werden nun (wie im Standard) nur 10 Einträge pro Seite angezeigt. Soll ich dafür eine neue Issue eröffnen?

**Comment by Zefau** [comment]
Im JSON brauchst du da nichts eintragen. Es gibt dafür eine extra Option

**Comment by stony2k** [comment]
Ich meinte mit "Max. Einträge" = 0 diesen Eintrag:
![image](https://user-images.githubusercontent.com/16526471/145858780-07e093de-31fc-4bbf-86ae-3190005f8a50.png)

Dennoch werden aktuell trotzdem nur 10 pro Seite angezeigt. Bin mir aber fast sicher, dass in einer älteren Beta mit der Einstellung 0 alle Einträge angezeigt wurden.

**Comment by Zefau** [comment]
Ja, das ist richtig. Schaue ich mir nochmal an.

> Im JSON brauchst du da nichts eintragen. Es gibt dafür eine extra Option

War auf `sortOrder` bezogen.

**Comment by Zefau** [comment]
Die `max` Option in Kombination mit den Datensätzen je Seite sollte mit `v3.0.0-beta.16` wieder passen

**Comment by stony2k** [comment]
Habe 3x den Adapter von Github installiert und es ist noch immer die Beta 15. Stimmt was mit meiner Installation nicht?

**Comment by stony2k** [comment]
Beta 16 installiert, leider weiterhin nur 10 Einträge pro Seite.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.17`

**Comment by stony2k** [comment]
Diese gut :) Funktioniert wieder. Besten Dank :)
