### ISSUE TITLE
HistoryGraph dataMin und dataMax funktionieren nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1259]
`v3.0.0-beta.11`
Es wird ein Bereich von 0 bis 30 angezeigt, obwohl dataMin und dataMax berücksichtigt werden sollten. Woher kommt 0-30?
![image](https://user-images.githubusercontent.com/84818934/144957408-1fc43487-ed01-4490-8865-4ac2c0520940.png)
```
[
  {
    "position": "left",
    "name": "Bad",
    "nameLocation": "center",
    "nameGap": 40,
    "offset": -10,
    "padding": 5,
    "min": "dataMin",
    "max": "dataMax",
    "axisLabel": {
      "formatter": "{value} °C",
      "margin": 5,
      "showMaxLabel": true,
      "showMinLabel": true
    }
  },
  {
    "position": "right",
    "name": "Büro",
    "nameLocation": "center",
    "nameGap": 40,
    "offset": -5,
    "padding": 5,
    "min": "dataMin",
    "max": "dataMax",
    "axisLabel": {
      "formatter": "{value} °C",
      "margin": 5
    }
  }
]
```
![image](https://user-images.githubusercontent.com/84818934/144957533-1cf63e10-c167-4b4e-9a3c-1c59ee84ad18.png)

**Comment by Zefau** [comment]
Die Konfiguration funktioniert bei mir.

Sonst nimm die mal raus, speichere und setze die dann wieder rein.
Ggf. auch mal ein vollen refresh?

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.12`
![image](https://user-images.githubusercontent.com/84818934/145121371-cd7b4fb7-6c39-46d8-ba0d-0bb3bc15198b.png)
Rausgenommen, gespeichert, aktualisiert, reingesetzt, gespeichert, aktualisiert -> gleiches Ergebnis.

**Comment by mcuiobroker** [comment]
Geht man in die Konfig und geht auf "abbrechen" -> erscheint
![image](https://user-images.githubusercontent.com/84818934/145122208-0f497af1-c99b-4fe5-9454-ed6a4b0bc80c.png)
Der HistoryGraph wird nicht komplett geladen.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.14` sollte es wieder passen

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.14`
Keine Veränderung
![image](https://user-images.githubusercontent.com/84818934/145693594-2267df64-96b9-4460-a1d2-8b0e9f801463.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1279

**Comment by mcuiobroker** [comment]
x-Achse Wert fehlen
![image](https://user-images.githubusercontent.com/84818934/145733866-e9490e93-e3ea-445e-b3b1-c28a1d1dd054.png)

**Comment by Zefau** [comment]
Aber datamin geht!

**Comment by mcuiobroker** [comment]
Ja datamin funktionier.

**Comment by Zefau** [comment]
Die x-Achse sollte mit `v3.0.0-beta.16` wieder passen

**Comment by mcuiobroker** [comment]
Passt Danke.
