### ISSUE TITLE
Kalender zeigt agenda nicht an

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1260]
v3.0.0-beta.11

Beim Kalender werden die Ereignisse zwar angezeigt wenn ich mit der Maus über das Datum gehe, aber nicht in der Agenda darunter. 
<img width="384" alt="Bildschirmfoto 2021-12-07 um 06 40 07" src="https://user-images.githubusercontent.com/2972703/144973687-e3a6bc98-f4d7-463c-a4b7-37b61269a79b.png">
Wenn ich auf den nächsten Tag clicke wird die Agenda sporadisch richtig angezeigt.
<img width="376" alt="Bildschirmfoto 2021-12-07 um 06 41 00" src="https://user-images.githubusercontent.com/2972703/144973790-787893d0-fd36-44d1-8aef-9b1ec24876cc.png">

Meine Konfiguration sieht wie folgt aus
<img width="1394" alt="Bildschirmfoto 2021-12-07 um 06 41 28" src="https://user-images.githubusercontent.com/2972703/144973836-562b3d3a-d73c-41f1-978c-7f02f1c2c89e.png">

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.13`

**Comment by stephan1827** [comment]
Die Tage werden jetzt richtig angezeigt, aber es ist beim Laden immer eine ganze Woche ausgewählt, obwohl ich als Vorschau 0 Tage eingestellt habe.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.14` sollte es wieder passen

**Comment by stephan1827** [comment]
Sieht gut aus. Besten Dank
