### ISSUE TITLE
Beim Circle Chart werden die Zahlen abgeschnitten

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1261]
v3.0.0-beta.11

Macht man das Circle Chart in dem folgenden Seitenverhältnis, dann werden die Zahlen am unteren Rand abgeschnitten.
<img width="134" alt="Bildschirmfoto 2021-12-07 um 06 42 08" src="https://user-images.githubusercontent.com/2972703/144974115-b053f90d-fc48-4855-b08d-24981e015f87.png">

Die Konfiguration ist wie folgt

<img width="1275" alt="Bildschirmfoto 2021-12-07 um 06 53 12" src="https://user-images.githubusercontent.com/2972703/144974221-1cdea8e1-866e-4a70-be20-daaadd9280c3.png">

<img width="1043" alt="Bildschirmfoto 2021-12-07 um 06 53 53" src="https://user-images.githubusercontent.com/2972703/144974260-188ce666-22fe-4bd6-a6d2-422dd72cd2c0.png">

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.12`

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.12`
![image](https://user-images.githubusercontent.com/84818934/145121890-f762efa5-d40d-443c-a295-5042cb721511.png)

**Comment by stephan1827** [comment]
Jetzt passt es!

Besten Dank

**Comment by Zefau** [comment]
@mcuiobroker schau nochmal mit `v3.0.0-beta.15`: es gibt eine Option, mit der du den Radius selbst definieren kannst. Eine automatisch Anpassung an die Größe geht mit der Echarts API nicht so einfach, daher die manuelle Option.

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.15`
Stellt man den Wert von maximalen Achsenwert auf 0, so sollte eigentlich der MaximalWert = 100% und die anderen entsprechend ihres Wertes prozentual abgebildet, so war es sonst.
![image](https://user-images.githubusercontent.com/84818934/145883244-124f9c13-143b-4c73-ac51-e0ce210d7bb4.png)
Jetzt scheint er den ersten Wert als 100% zu nehmen:
![image](https://user-images.githubusercontent.com/84818934/145883665-b0414ecb-d475-4d47-9d23-8eae41e76658.png)

**Comment by mcuiobroker** [comment]
Als Pie-Chart sind die Aufteilungs-Zahlen verdeckt und bei Mouseover wird die GeräteID angezeigt?.
Werte auf dem PIE schlecht lesbar, fett?
![image](https://user-images.githubusercontent.com/84818934/145892786-0b43f33a-0bad-4d9d-a2fe-2181e7c4e6a4.png)

**Comment by Zefau** [comment]
mit `v3.0.0-beta.16` sollte es mit dem `maximalen Achsenwert` und den `Aufteilungs-Zahlen` funktionieren

**Comment by mcuiobroker** [comment]
Kannst du bitte die Werte in **fett** darstellen und im darkMode true (white) false (black).
Danke.
Sonst passt es.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.17`

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.17`
PIE-Chart wird gar nicht mehr angezeigt.
Auch Bar-Chart nicht mehr.
Circle Chart erst nach F5.
Dan Wechsel zu Bar-Chart:
![image](https://user-images.githubusercontent.com/84818934/146278220-bbe2b669-d055-4fc2-be2f-d69d39f8a8d2.png)
Nach F5:
![image](https://user-images.githubusercontent.com/84818934/146278283-b623d3e8-eb70-4b53-9fd8-eb1837154879.png)
Wechsel zu PIE:
Egal ob so oder mit F5 -< keine Anzeige

**Comment by Zefau** [comment]
Oh man, warum das auf einmal? Hast du Fehler im Log?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/146372622-7c00cc39-9bda-4ece-8394-5d832a649a80.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`
