### ISSUE TITLE
Chart: Bar-Chart - object-Object

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1267]
Ich habe gerade das Chart Widget probiert.
Im Frontend steht [object Object] hinter den Werten.
<img width="568" alt="image" src="https://user-images.githubusercontent.com/13101074/145032713-69d95ea1-9f08-4fcf-b9b2-9ec6f1aa8781.png">

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.12`

**Comment by AFPass** [comment]
Jetzt steht undefined
<img width="534" alt="image" src="https://user-images.githubusercontent.com/13101074/145423833-968b83f0-835c-4b6b-a605-e9a84d9c1d0c.png">


Im HistoryChart Widget nicht.
<img width="840" alt="image" src="https://user-images.githubusercontent.com/13101074/145423210-ce6c1499-0535-443a-8927-5400a5a36c41.png">

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.13`

**Comment by AFPass** [comment]
In Chart Widget steht noch immer undefinied
<img width="347" alt="image" src="https://user-images.githubusercontent.com/13101074/145486196-ab90737e-cda1-427a-9f87-4c5911e115c2.png">

HistoryChart Widget steht nach dem Wert nichts.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/13101074/145486161-ff1aab86-15b0-47d8-8cde-afdc0a8230c6.png">

**Comment by Zefau** [comment]
@AFPass

**Comment by AFPass** [comment]
Nein.
Passt.
