### ISSUE TITLE
Datenpunkte in einer Statelist lässt sich mit Bindings  nicht auszublenden

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#1270]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/1263

<div type='discussions-op-text'>

<sup>Originally posted by **stony2k** December  7, 2021</sup>
Ich habe mir jetzt die Postings hier und auch Beispiele im Wiki von mcuiobroker angeschaut, aber bekomme es nicht hin.

Ich würde den Datenpunkt "Sind Batterien leer" gerne ausblenden, sofern dieser gleich 0 ist:
![image](https://user-images.githubusercontent.com/16526471/144991300-ce9b173c-3040-4abe-99fd-cb33c9af2a25.png)

Versucht habe ich Gerät, bei der Eigenschaft Body Stil folgende Dinge ausprobiert:
{"{javascript.0.BatterieUeberwachung.EmptyBatCount}=0":{"display":"none !important"}}
{"{javascript.0.BatterieUeberwachung.EmptyBatCount}=0":{"visibility":"hidden"}}
{"0":{"visibility":"hidden"}}
{"0":{"display":"none !important"}}

Ich spreche hier ja keinen anderen Datenpunkt an, daher müsste "{javascript.0.BatterieUeberwachung.EmptyBatCount}" ja eig. nicht erforderlich sein.
![image](https://user-images.githubusercontent.com/16526471/144991687-aef8831b-d7aa-4902-ae87-e22565f15b9e.png)

Ich habe doch irgendwo einen totalen Denkfehler, oder?</div>

**Comment by Zefau** [comment]
```
{"0":"display: none"}
```

**Comment by stony2k** [comment]
@Zefau Wird auch damit im Popup ausgeblendet, aber nicht im Statelist Widget
![image](https://user-images.githubusercontent.com/16526471/146957059-bd8be7c0-c7f4-4161-b2f5-2cb84bbd694d.png)
![image](https://user-images.githubusercontent.com/16526471/146957119-6a2d397f-3dfe-4929-b709-116a9469fc78.png)
![image](https://user-images.githubusercontent.com/16526471/146957157-49008186-c6e5-4bc6-b9e1-233c75ad3d06.png)

**Comment by Zefau** [comment]
Bei mir geht's. Und Popup / Layout sind eigentlich gleich.

Was steht denn im DOM Inspektor? Hast du noch irgendwelche Styles drin?

**Comment by mcuiobroker** [comment]
@stony2k Kannst du mal mit important probieren.
```
{"0":"display: none !important"}
```

**Comment by stony2k** [comment]
Ich habe Styles, aber diese testweise mal raus genommen. Browser ist Chrome 96. Hat leider auch nicht geholfen.

DOM Inspektor: Meinst die die Konsole in den Entwicklertools und die Log angefangen mit "App Welcome to jarvis v3.0.0-beta.18"?

**Comment by Zefau** [comment]
@mcuiobroker @stony2k ist hier noch etwas offen?

**Comment by stony2k** [comment]
Ja. Klappt bei mir ja leider nicht. Konnten dir meine Logs helfen? Irgendwie ist hier der Wurm drin, was können wir noch machen um das Problem zu beheben?

**Comment by mcuiobroker** [comment]
Zeig mal bitte den DP "batterycount" und die Statelist Layoutdefinition, wo die drin ist.

**Comment by stony2k** [comment]
Würde ich sehr gerne machen, aber aktuell komme ich nicht mehr in die Jarvis Konfigurationsoberfläche, da automatisch von "jarvis/index.html#/configuration" auf "jarvis/index.html#/" weitergeleitet wird (V3.0.9). Ich will hier jetzt auch nicht großartig 20 neue Issues mixen. Muss das erstmal irgendwie hinbekommen (hoffentlich).

**Comment by mcuiobroker** [comment]
Gib mal jarvis/index.html#/configuration/devices ein, oben in der Adresszeile

**Comment by stony2k** [comment]
Perfekt, mit "jarvis/index.html#/configuration/devices" hat es geklappt und jetzt scheint Jarvis wieder zu laufen.

### Datenpunkt batterycount

```
"fcb15739-1f8e-427a-81eb-42cc18c2d720": {
    "name": "Akkustände",
    "icon": "battery",
    "label": "",
    "function": "_defaults",
    "states": {
      "batterycount": {
        "stateKey": "batterycount",
        "showState": true,
        "label": {
          "0": "keine leeren Batterien",
          "1": "1 leere Batterie",
          ">1": "mehrere leere Batterien"
        },
        "state": "javascript.0.BatterieUeberwachung.EmptyBatCount",
        "display": "",
        "icon": {
          "0": "battery-high",
          "1": "battery-medium",
          ">1": "battery-low"
        },
        "properties": "",
        "iconStyle": {
          "0": {
            "color": "var(--q-color-primary)"
          },
          ">0": {
            "color": "red"
          }
        },
        "bodyStyle": {
          "0": "display: none !important"
        },
        "bodyElement": "LastChangeBody",
        "CustomTextBodyConfig": {
          "text": "{\"0\":\"nein\",\">0\":\"ja\"}"
        },
        "stateStyle": "",
        "unit": {
          "0": "alle voll",
          "1": "Batterie",
          ">1": "Batterien"
        }
      },
      "lastmessage": {
        "stateKey": "lastmessage",
        "showState": true,
        "state": "javascript.0.BatterieUeberwachung.LastMessage"
      },
      "jsontable": {
        "stateKey": "jsontable",
        "showState": true,
        "state": "javascript.0.BatterieUeberwachung.JSONTable",
        "hide": true
      }
    },
    "options": {},
    "attributes": {},
    "id": "fcb15739-1f8e-427a-81eb-42cc18c2d720",
    "revision": "14c1d"
  }
```

### Statelist
```
"7af1647a-fd2f-4b37-a128-7fd42c843715": {
    "id": "7af1647a-fd2f-4b37-a128-7fd42c843715",
    "config": {
      "dense": false
    },
    "icon": "window-closed-variant",
    "title": "Fenster & Türen",
    "module": "StateList",
    "revision": "21ca6",
    "items": [
      {
        "type": "device",
        "deviceId": "ef12cf22-0856-4995-91d2-859ae3be062b",
        "id": "10e8e53c-30ab-46b2-9f35-206e468a1a8d",
        "primaryStateKey": "",
        "bodyStateKey": "open",
        "bodyElement": "LastChangeBody",
        "secondaryStatesKeys": [],
        "LastChangeBodyConfig": {
          "open": {
            "time": "lc"
          }
        }
      },
      {
        "type": "device",
        "deviceId": "2a30fc84-014b-45b5-b69b-14334782e3a0",
        "id": "7c3245b5-8805-4345-ae13-c16d0b19ba13",
        "primaryStateKey": "",
        "bodyStateKey": "open",
        "bodyElement": "LastChangeBody"
      },
      {
        "type": "device",
        "deviceId": "0471658e-aa18-43ed-bde3-b8e5a7906b6b",
        "id": "117cebf0-8945-4356-8e70-4a624275b0e2",
        "primaryStateKey": "",
        "bodyStateKey": "open",
        "bodyElement": "LastChangeBody"
      },
      {
        "type": "device",
        "deviceId": "7cd7871f-2ec8-419a-a9aa-8357a49152d8",
        "id": "55552593-6a09-4d26-876f-8da435904666",
        "primaryStateKey": "",
        "bodyStateKey": "open",
        "bodyElement": "LastChangeBody"
      },
      {
        "type": "device",
        "deviceId": "40481b62-c457-4a56-8879-969002a67ef2",
        "id": "99384377-83c0-404d-84b4-d77a88aad05e",
        "primaryStateKey": "",
        "bodyStateKey": "open",
        "bodyElement": "LastChangeBody",
        "label": "Wohnungstür"
      },
      {
        "type": "device",
        "deviceId": "wohnungstür_9528d",
        "id": "0cae350c-1d7e-4414-86cb-9249c0791237",
        "primaryStateKey": "",
        "bodyStateKey": "lockState",
        "bodyElement": "LastChangeBody",
        "label": "Tüschloss",
        "secondaryStatesKeys": []
      },
      {
        "type": "device",
        "deviceId": "fcb15739-1f8e-427a-81eb-42cc18c2d720",
        "id": "f9d79219-7c10-40df-a211-226eb9fd8152",
        "primaryStateKey": "",
        "bodyStateKey": "batterycount",
        "bodyElement": "LastChangeBody",
        "label": ""
      }
    ],
    "hideTitle": true,
    "label": "Hauptseite: Fenster & Türen"
  }
```

**Comment by mcuiobroker** [comment]
Jetzt ist batterycount=0?
Dann im Frontend auf die Zeile "batterycount" in der StateList und dort "rechte Mauste" -> Untersuchen
-> 
![image](https://user-images.githubusercontent.com/84818934/149655276-46677da2-a9f2-4ee4-8c44-4444b2e05cc1.png)

**Comment by stony2k** [comment]
Ja, ist aktuell 0. Hilft dir das so weiter?

![image](https://user-images.githubusercontent.com/16526471/149655742-2b7289d6-4803-49d8-a694-bb6678bc4faa.png)

**Comment by mcuiobroker** [comment]
Auf die Zeile gehen
![image](https://user-images.githubusercontent.com/84818934/149655777-dd9311ac-8933-4f81-9c19-0986cd59d7c3.png)

**Comment by stony2k** [comment]
![image](https://user-images.githubusercontent.com/16526471/149656042-ad32e139-5564-4cd4-a00b-e26ef4b9763f.png)

**Comment by mcuiobroker** [comment]
Das muss eingerahmt sein:
![image](https://user-images.githubusercontent.com/84818934/149656089-d9fcdc5c-a8e0-45a2-b9f9-8f4d6a0a5441.png)

**Comment by mcuiobroker** [comment]
Wenn du mal im element.style
![image](https://user-images.githubusercontent.com/84818934/149656251-47265d3b-e9a9-4965-bc62-9ba835203c14.png)
![image](https://user-images.githubusercontent.com/84818934/149656276-47dbcfd9-93dc-4a3e-bfae-d687b033ea3a.png)
eingibst, was verschwindet?

**Comment by stony2k** [comment]
> Wenn du mal im element.style ![image](https://user-images.githubusercontent.com/84818934/149656251-47265d3b-e9a9-4965-bc62-9ba835203c14.png) ![image](https://user-images.githubusercontent.com/84818934/149656276-47dbcfd9-93dc-4a3e-bfae-d687b033ea3a.png) eingibst, was verschwindet? Irgendwie sind beide "Türschloss" und "batterycount" miteinander vermixt?

Sorry, hatte den falschen Punkt markiert :D Tatsache, wenn ich display: none; dort eingebe, dann ist das Element erwartungsgemäß ausgeblendet.

Wie vorgeschlagen nach oben verschoben, Datenpunkt wird trotzdem angezeigt.

Jetzt die Lösung:
![image](https://user-images.githubusercontent.com/16526471/149656924-5eb49296-3b77-435a-9c0b-f4700dda43d9.png)

Ich habe zum Test mal auch im Datenpunkt Stil das gleiche wie im Body Stil eingetragen: Jetzt wurde die Statelist ausgeblendet! Dann testweise die Zeile aus dem Datenpunkt Stil gelöscht: Es funktioniert weiterhin. Ist batterycount = 0 ausgeblendet, ansonsten eingeblendet.. verrückt oder? Evtl. ein "Fehler" aus den Alpha oder Beta Zeiten, sodass der Datenpunkt Stil nicht richtig gesetzt wurde oder was auch immer?

![1](https://user-images.githubusercontent.com/16526471/149657101-5fdf5fe1-2b38-4b65-80de-20c3e965a2a1.gif)

**Recht herzlichen Dank für euren mega super schnellen und guten Support! :)**
