### ISSUE TITLE
Display Image, Buffer JPG

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1272]
Hatte bisher DisplayImage Widget wie folgt: 

![image](https://user-images.githubusercontent.com/22169074/145109495-16a9c760-7d95-48dc-8ecd-3baa883a9825.png)

Doorbird Adapter legt das Bild dort rein: 
{"type":"Buffer","data":[255,216,255,224,0,16 usw...

Hat bisher immer funktioniert, aktuell BETA 11, kann nicht genau sagen seit wann es nicht mehr geht.

**Comment by Zefau** [comment]
Da es ein Buffer ist, solltest du es innerhalb von ioBroker in ein base64 konvertieren und dann den Datenpunkt nutzen.
