### ISSUE TITLE
Option to disable Swipe 

### ISSUE THREAD

**Issue by Sheldor0** [Zefau/ioBroker.jarvis#1274]
For mobile devices the swipe function is very usefull. But for tablets especialy when they are wallmounted it leads to unwanted page-changes. If you have a horizontal slider for dimming a light, shadder or ajusting temperature and you slide over the slider the page also changes.... 

I would prefer a main switch in the jarivs-settings to completely disable the swipe-function. 

If you know a solution to disable the swipe function directly in my system i would also be happy.

Thanks

**Comment by Zefau** [comment]
There is an option already in the settings to disable tab swipe.

**Comment by Sheldor0** [comment]
I hav only the option "Tab-Swipe animieren" wich contolls the animation and not the Swipe itselft. 
Or am i wrong?

I am on (v3.0.0-beta.12) with Pro abo. 

Tanks for quick answering ;)

**Comment by Zefau** [comment]
Yeah sorry, you're right

**Comment by stony2k** [comment]
I would love to to see this function (voted already) :)

**Comment by ma-gu-16** [comment]
Same here. Especially if its possible for different viewports.

**Comment by Sheldor0** [comment]
If this would work, i would buy a few more licences.

**Comment by Zefau** [comment]
this has in fact been introduced in v3.1

**Comment by Sheldor0** [comment]
Nice ;) Thank you!
