### ISSUE TITLE
Keine Werte im Geräte-Popup

### ISSUE THREAD

**Issue by raspilaurent** [Zefau/ioBroker.jarvis#1275]
Version 3.0.0.beta12
Im Geräte-Popup werden keine Werte angezeigt, obwohl diese vorhanden sind (Luftfeuchtigkeit, Temperatur, Batterie, Link quality; siehe Screenshot).
Ausprobiert unter macOS mit Safari, Crome, Firefox und unter aktuellem iOS
<img width="1040" alt="Bildschirmfoto 2021-12-08 um 13 05 06" src="https://user-images.githubusercontent.com/57768691/145211372-3a8207fe-c29f-4c5d-bdb8-f19a14003252.png">

**Comment by Zefau** [comment]
Kommst du von v2? Hast du im Gerät aktiviert, dass der Wert angezeigt wird?

**Comment by Zefau** [comment]
Könntest du das JSON deines V2 Layouts teilen? Hast du das noch?

**Comment by raspilaurent** [comment]
Also ich habe von Jarvis ein Backup der letzten 10 Tage mit dem Backup-Adapter gemacht. Da müsste die noch dabei sein. Aber ich kenn ich nicht so gut aus, kannst du mir in etwa sagen, wo ich das finde? Ist das eine Datei? Dann helfe ich gerne...

**Comment by Zefau** [comment]
@raspilaurent hast du es mit den Informationen von @mcuiobroker gefunden?

Auf Linux finden sich die Dateien unter `/opt/iobroker/iobroker-data/jarvis/0`. Hier benötige ich die `_BACKUP_LAYOUT.json`.
