### ISSUE TITLE
Automatische Sicherung jarvis devices,layout,widgets funktioniert nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1276]
`v3.0.0-beta.12`
Nur CSS-Sicherungen funktionieren

![image](https://user-images.githubusercontent.com/84818934/145450717-1633171f-f4f4-4b9d-b586-c34310d9548f.png)
![image](https://user-images.githubusercontent.com/84818934/145450877-e893c6cf-048e-445a-b57f-6b2720a44b3a.png)
![image](https://user-images.githubusercontent.com/84818934/145450942-f6c97dac-c595-4d1f-a092-686c9ebb5a46.png)

**Comment by Zefau** [comment]
Glaube deine Dateien sind zu groß und können nicht mehr via Socket transportiert werden.

**Comment by mcuiobroker** [comment]
Kannst du dann da nicht ein Grenze anlegen, dass dann weniger unterschiedliche Einträge vorhanden sind? Normal scheint ja 10 Einträge zum Objekt zu sein?
Wo kann ich denn die Größe der Dateien die angehängt werden müssten sehen? Ist doch eigentlich nur der Inhalt vom entsprechenden DP z.B. jarvis.0.devices. 
Wie groß darf die denn sein?

**Comment by Zefau** [comment]
25 Einträge werden gespeichert. Bin überrascht, dass es trotzdem eine solche Größe von 100ten MB erreicht.

**Comment by Zefau** [comment]
Ich kenne die maximale Größe nicht, die über Socket übertragbar ist. Es gibt da eine Option, die zu erhöhen, aber die scheint nicht korrekt zu greifen.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/145487903-f38aeb45-7181-40f8-8566-d06125c36aeb.png)
Meine devices hat eine Größe von 247KB.
Das ist viel?

**Comment by Zefau** [comment]
Nein, überhaupt nicht.

Aber auf dem Screenshot oben waren es ja mehrere MB?

![image](https://user-images.githubusercontent.com/14368811/145488098-8f65e88c-0ed4-482b-931e-3be4223bf7a2.png)

**Comment by mcuiobroker** [comment]
Die Anzeige ist in Bytes.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/145488366-cb055037-abdf-40e6-b54a-3743c3764a38.png)

**Comment by Zefau** [comment]
Ok, ist wohl Zeit für's Bett.. ;-)

**Comment by dentro-git** [comment]
Morgen zusammen,

aktuell` v3.0.0-beta.13`

ich habe glaube ich das gleiche Problem. Unter den Sicherungen in den Adaptereinstellungen sind bei mir immer noch die von Version 2.x Alles was ich in den letzten Wochen unter ` v3.0.0-beta.x` gemacht habe fehlt..

![image](https://user-images.githubusercontent.com/77006779/145529766-8f15f6fc-1e02-4eea-8709-161beffb8e1f.png)

**Comment by MarkSau** [comment]
Tatsächlich habe ich auch keine "aktuelle" Sicherung.  alle aus September.

![image](https://user-images.githubusercontent.com/22911084/145672032-c6746af2-1032-4bb0-9fb0-5690a614d9ae.png)

![image](https://user-images.githubusercontent.com/22911084/145672047-d046ca31-b8d2-48d6-a93d-2037a1734220.png)

**Comment by Zefau** [comment]
mit `v3.0.0-beta.14` sollte es wieder passen

**Comment by mcuiobroker** [comment]
Nein. Änderung im devices gemacht und diese wurde nicht gesichert.
![image](https://user-images.githubusercontent.com/84818934/145695089-5e505291-54e6-4872-8660-1980050436f0.png)
![image](https://user-images.githubusercontent.com/84818934/145695098-78e014e0-9dc0-4494-97aa-32bf35318038.png)
![image](https://user-images.githubusercontent.com/84818934/145695125-720de18c-3661-47d5-80f7-0b1d67715c5e.png)

**Comment by dentro-git** [comment]
Hey, ich habe unter `v3.0.0-beta.14` nochmal überall geändert und es geht nur bei Styles, alles andere wurde nicht gesichert

![image](https://user-images.githubusercontent.com/77006779/145718335-4017aaa8-1d55-4fc9-87a8-0726015e8684.png)
![image](https://user-images.githubusercontent.com/77006779/145718384-3893d1db-10a9-4341-8490-1c5dc9ac264a.png)
![image](https://user-images.githubusercontent.com/77006779/145718391-69b6efd9-fb54-4719-a285-539e6f4a1af7.png)
![image](https://user-images.githubusercontent.com/77006779/145718400-8a0dcab4-76ae-423f-a2d1-8cf0bdabc123.png)
![image](https://user-images.githubusercontent.com/77006779/145718411-36abb2e1-19ab-4e98-b231-5e1ff9d0a764.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.15`

**Comment by dentro-git** [comment]
Hey, mit  `v3.0.0-beta.15` geht es!

Devices, Layout, Settings und Widgets angepasst und die Sicherungen sind da...
![image](https://user-images.githubusercontent.com/77006779/145765135-ab487b82-92fd-4d65-a036-acb7db49483b.png)
![image](https://user-images.githubusercontent.com/77006779/145765154-38bb241f-4e48-459c-af2d-76b14cd3fe78.png)
![image](https://user-images.githubusercontent.com/77006779/145765190-dbfe737c-da4a-4d41-a9d2-2cbc5d00b6f5.png)
![image](https://user-images.githubusercontent.com/77006779/145765202-637a8d0a-ab37-4f2e-b7f2-65ba680cce9f.png)

..da Styles bei mir leer ist kann ich dazu nur sagen das er das in der Vergangenheit immer leer gespeichert hat. Das hat er heute nicht gemacht, wohl aber bei den versuchen gestern...
![image](https://user-images.githubusercontent.com/77006779/145765353-c2e0a0e2-40cb-45a9-a1a5-a6edc30aa8b1.png)
