### ISSUE TITLE
Instanzeinstellungen WIKI springt zu v2 WIKI

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1277]
Klickt man auf WIKI sprint zu v2 WIKI-> https://zefau.gitbook.io/jarvis-v2/
![image](https://user-images.githubusercontent.com/84818934/145451196-6492d6a4-11d8-40db-af24-afbaff82497e.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.13`

**Comment by mcuiobroker** [comment]
Ja. Passt Danke.
