### ISSUE TITLE
HistoryGraph - Daten Zoom Slider Description

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1278]
Beta12
Die Description fehlt.
<img width="347" alt="image" src="https://user-images.githubusercontent.com/13101074/145485270-047e3f28-0cb3-4921-a99d-1e31e84a7fca.png">

**Comment by Zefau** [comment]
> Daten-Zoom in Prozent von 0 (ausblenden) bzw. 1 bis 100.

Mit der nächsten beta ist das behoben.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.14` sollte es wieder passen

**Comment by AFPass** [comment]
Passt
