### ISSUE TITLE
HistroyGraph - minx/max y-Achse

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1279]
Beta 13
Konfiguration wie folgt:
<img width="719" alt="image" src="https://user-images.githubusercontent.com/13101074/145487131-3eb68927-9554-4f10-8fd9-3210c180a2cc.png">

Darstellung:
<img width="555" alt="image" src="https://user-images.githubusercontent.com/13101074/145487205-d0a25be4-f505-4623-a812-1976009c13ec.png">

y-links: Konfiguriert ist 0-40. Angezeigt wird 0-30

y-rechts: Konfiguriert ist 10-60. Angezeigt wird 0-60

**Comment by Zefau** [comment]
duplicate https://github.com/Zefau/ioBroker.jarvis/issues/1259

**Comment by Zefau** [comment]
Wobei sorry, nicht exakt Duplikat.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.14` sollte es wieder passen
