### ISSUE TITLE
Trigger-Element wird nicht vererbt. 

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1280]
Problem war das im Widget nochmal die Button Action augewählt war und somit meine Einstellungen von dem Gerät überschrieben hat. 
Wenn ich dort nichts auswähle müsste dann nicht die Default einstellung vom Gerät kommen ? 
Bei mir kommt da nichts. 

Das Trigger-Element sollte ja leer sein und dann sollte das vom Gerät genommen werden, oder nicht ? 

![image](https://user-images.githubusercontent.com/22169074/145257925-b83eb9aa-a41c-486b-9a08-561bc5742b5d.png)

_Originally posted by @ma-gu-16 in https://github.com/Zefau/ioBroker.jarvis/discussions/1175#discussioncomment-1774490_

**Comment by Zefau** [comment]
Nein. Wenn du nichts auswählst, dann erscheint auch nichts. Alles andere wäre irreführend.

**Comment by ma-gu-16** [comment]
@Zefau  Dann verstehe ich aber nicht wieso man die Möglichkeit hat es bei den Geräten zu konfigurieren? Dieses ist doch dann überflüssig. Da ich die gleiche Arbeit wiederholt machen muss bei dem Widget.

**Comment by Zefau** [comment]
Du kannst die Sachen unterschiedlich visualisieren. Wenn du die gleiche Komponente wählst werden die Einstellungen dessen übernommen.

**Comment by Zefau** [comment]
Mach aber gerne ein Feature Request auf

**Comment by ma-gu-16** [comment]
> Du kannst die Sachen unterschiedlich visualisieren. Wenn du die gleiche Komponente wählst werden die Einstellungen dessen übernommen.

Eben und das tut es nicht ;-) Ist es ein Bug ? 

Ggfl wenn man etwas anpasst und dann wieder zurücksetzt, das es nicht funktioniert ?

**Comment by Zefau** [comment]
Wenn du im Layout anpasst, dann greift keine Vererbung mehr.

**Comment by ma-gu-16** [comment]
> Wenn du im Layout anpasst, dann greift keine Vererbung mehr.

Und wenn man es wieder rauslöscht, danach wieder anlegt, greift es noch immer nicht. 
Das ganze klappt nur beim ersten mal anlegen sauber, wenn man bestehende editiert nicht.

**Comment by Zefau** [comment]
Wie gesagt

> Wenn du im Layout anpasst, dann greift keine Vererbung mehr.

**Comment by ma-gu-16** [comment]
Und wann greift den dann genau die Vererbung ? 

Wie bekomme ich es hin das ich bei den Geräten die Action konfiguriere und diese dann ohne weiteres zutun mit dieser Konfig im Layout/Frontend ersichtlich ist ? 

Danke dir.

**Comment by Zefau** [comment]
Bitte schau nochmal mit `v3.0.11`. Die Komponenten Optionen sollten nun korrekt vererbt werden (mit entsprechender Anmerkung).

**Comment by ma-gu-16** [comment]
das geht noch immer nicht. wenn ich z.b. die ActionElemente haben will und diese beim Gerät bereits angelegt habe, sind diese nicht im Frontend. Erst wenn ich bei dem Widget nochmal alles hinzufüge... Meiner Meinung nach doppelt.

**Comment by Zefau** [comment]
@ma-gu-16 ich hab's nun endlich geschafft umzusetzen. Schau nochmal mit `v3.1.0-alpha.53`.
