### ISSUE TITLE
Installation zerstört beim Update

### ISSUE THREAD

**Issue by MubiTec** [Zefau/ioBroker.jarvis#1282]
Hi,

Hab vorgestern auf die v3 beta 12 geupdated. Anschließend war die jarvis Installation zerstört.
Konnte sie dann per iobroker backup wieder herstellen.
Grundsätzlich wird ja gewarnt davor, github Versionen zu installieren. Woran kann cih bei jarvis erkennen, dass ich das gerade problemlos machen kann? Ich weiß, dass jarvis 3 noch beta ist, das meine ich auch nicht mit problemlos.

Das separate backup von jarvis über den backitup funktioniert noch nicht. Kann ich da ein issue erstellen? Hier oder beim backitup?

Generell mal: vielem Dank für den guten adapter!

**Comment by Zefau** [comment]
Was genau funktionierte nicht? Gab es eine Fehlermeldung?

Der Entwickler vom backitup Adapter arbeitet bereits an einem Update.

**Comment by MubiTec** [comment]
Eine Fehlermeldung hab ich nicht bekommen, die Anzeige war nur leer. Vermute mal, dass man wieder was neues anlegen hätte können, also der Adapter an sich funktioniert, aber die Daten waren halt weg

**Comment by MubiTec** [comment]
Ah, super, dass beim Update schon was am laufen ist, danke!

**Comment by mcuiobroker** [comment]
@MubiTec Macht man ein Update von v2 auf v3 dauert es ca 1 Minute bis er alles umgesetzt hat.
Danach, wenn man, so wie in Deinem Fall, nichts sieht, einmal ein Refresh durchführen mit F5.
Dann sollte auch normalerweise alles zu sehen sein, was umgesetzt wurde.

**Comment by stony2k** [comment]
@MubiTec Ja, das hilft dir jetzt um Nachhinein erstmal nur Bedingt, aber evtl. für die Zukunft: Ich hatte genau das gleiche wie du. Seit dem kopiere ich mir in den erweiterten Einstellungen den JSON Code für Geräte, Widgets etc. raus, um im Fall der Fälle möglichst unkompliziert alles wiederherstellen zu können. Und jetzt ganz neu (aber das ist eher ein Spezialfall) erstelle ich vor dem Jarvis Update einen Snapshot meiner ioBroker VM.

Hoffe das hilft dir :)

**Comment by MubiTec** [comment]
OK, werde das das nächste Mal ausprobieren. Jetzt seht ja alles wieder :-)
Aber noch mal die andere frage: kann ich zu jeder Zeit gefahrlos von github updaten oder muss ich irgendwo drauf achten?

**Comment by stony2k** [comment]
Bei mir hat das Update von Github bis auf 1x jedes mal geklappt. Keine Ahnung in welcher Konstellation es in dem Fall dann kaputt gegangen ist.

**Comment by Zefau** [comment]
@MubiTec waren denn die Datenpunkte `jarvis.0.devices`, `jarvis.0.layout` und co. tatsächlich komplett leer bzw. auf `null` ?

**Comment by MubiTec** [comment]
Hi,

Kann ich leider nicht mehr nachvollziehen. Achte ich beim nächsten Mal darauf, was hoffentlich nicht kommt 😂
