### ISSUE TITLE
Wetter Widget keine Vorschau mehr

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#1283]
v3.0.0-beta.13

Im Wetter Widget wird beim klickt auf den Wochentag keine Vorschau mehr angezeigt.

Fehler tritt mit verschiedenen Browsern (Desktop und Mobil) auf.

**Comment by Zefau** [comment]
Funktioniert bei mir. Welchen Browser nutzt du?

**Comment by bogaboo** [comment]
Ich hoffe ich wurde nicht falsch verstanden, es handelt sich nicht um die "kurz" Vorschau der Tage,
das funktioniert sondern um das Popup das geöffnet wird wenn man den Tag anklickt.

Ich benutze auf dem Desktop Safari, der Fehler tritt hier aber auch mit Firefox oder Chrome auf.
Unter iOS (Safari) das gleiche Problem.

Was mir gerade aufgefallen ist:

In der Anzeige habe ich jetzt:      Heute - Morgen - Dienstag - Mittwoch - Donnerstag

beim Donnertag (zweites Bild) öffnet sich das Popup  Fenster, bei allen anderen Tagen nicht.




![Bildschirmfoto 2021-12-12 um 09 16 38](https://user-images.githubusercontent.com/48379591/145705386-7f5e435f-5f80-468b-b0ed-bbf00e8c612b.jpg)


 
![Bildschirmfoto 2021-12-12 um 09 18 46](https://user-images.githubusercontent.com/48379591/145705439-d7ed182c-5a81-48dc-bf57-8bf71b5a1941.jpg)

**Comment by Zefau** [comment]
Hatte ich du verstanden.

Hast du Fehler in der Browser Konsole (via F12)?

**Comment by bogaboo** [comment]
Ja,

   09:36:26 | ERROR |  | Error: Cannot find module './wind/set1/wind_set1_46.png'

Ich habe das "Icon Set Wind" jetzt auf "Set 3" umgestellt , jetzt funktioniert es wieder überall.

Also der Fehler tritt nur mit "Icon Set Wind - Set 1"

**Comment by Zefau** [comment]
Ah ok, danke

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.15`

**Comment by bogaboo** [comment]
Ja prima, mit der  v3.0.0-beta.15 funktioniert des "Wind Icon Set 1" wieder.
