### ISSUE TITLE
jarvis ist wegen eines Fehlers abgestürzt

### ISSUE THREAD

**Issue by Minta79** [Zefau/ioBroker.jarvis#1284]
![Jarvis](https://user-images.githubusercontent.com/95684908/145691316-8913978f-88a1-4a12-997a-f433c3f79e03.png)

**Comment by Zefau** [comment]
Entweder auf v3 gehen oder Backup einspielen.

Der Fehler wird vermutlich durch inkorrekte oder fehlende Koordinaten im Map Modul verursacht.

**Comment by Minta79** [comment]
Was

> Entweder auf v3 gehen oder Backup einspielen.
> 
> Der Fehler wird vermutlich durch inkorrekte oder fehlende Koordinaten im Map Modul verursacht.

Denke auch, dass es am Map Modul liegt, denn nach einer Änderung darin kam der Fehler.
Was bedeutet auf v3 gehen? Ein Backup hatte ich leider noch nicht erstellt.

**Comment by Zefau** [comment]
jarvis erstellt automatisch ein Backup bei jeder Änderung. Einfach bei der Instanz-Einstellung schauen, dort sind die auswählbar.

v3 ist aktuell beta und nur über Github installierbar.

**Comment by Minta79** [comment]
Vielen Dank für den Tipp mit den Backups. Das wusste ich nicht. Läuft wieder

**Comment by Zefau** [comment]
schau mal im Wiki vorbei: https://github.com/Zefau/ioBroker.jarvis/wiki

Ein guter erster Anlaufpunkt
