### ISSUE TITLE
html im DP wird nicht mehr umgesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1285]
`v3.0.0-beta.14`
![image](https://user-images.githubusercontent.com/84818934/145693565-c154d1f0-ceca-4153-bb34-fd33b4152b58.png)

**Comment by Zefau** [comment]
Die ganzen issues sind wegen Pro. Fixe ich umgehend

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.15`, damit sollte dein Pro wieder passen

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.15`
Pro wird erkannt, CSS funktioniert nicht.

**Comment by Zefau** [comment]
Sollte eigl. auch funktionieren. Hast du noch irgendwelche Hinweis in der Browser Konsole? Kannst du im Inspector mal nach `#customStyles` suchen, ob es dort drin ist? Valides CSS ist es (https://jigsaw.w3.org/css-validator/#validate_by_input)?

**Comment by mcuiobroker** [comment]
#customstyles ist nicht drin

**Comment by Zefau** [comment]
Die Welcome Message ist fix und soll auf Pro hinweisen, weil es sonst zuviele Verirrungen gibt.

**Comment by Bernd9000** [comment]
Das mit der welcome message finde ich auch störend.
Hab versucht Sie unsichtbar zu machen:
.q-notifications__list {
visibility:hidden;
}
Leider werden die eigenen styles ziemlich spät aktiviert so das man den Anfang doch noch sieht.
Eine Funktion um es wieder abzuschalten wäre nicht schlecht. :-)

**Comment by Zefau** [comment]
Das passiert doch nur einmalig beim Start?

**Comment by Bernd9000** [comment]
Ja, normal schon, aber
1) Im Moment muß ich öfter die Anzeige aktualisieren da sonst Icons oder Werte nicht angezeigt werden.
Daher taucht die welcome Message bei mir öfter auf. [#1207](https://github.com/Zefau/ioBroker.jarvis/issues/1207)

2.) Bei der Haussteuerung möchte ich wenn möglich nicht durch weitere Zusatzinfomationen gestört werden.
Seite aufrufen, schalten, fertig.
