### ISSUE TITLE
Notification feature only for Pro User Message

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1286]
![image](https://user-images.githubusercontent.com/84818934/145694083-b1b4452f-5026-4708-9ec1-81c701b4abbb.png)

**Comment by Zefau** [comment]
Pro not working, see https://github.com/Zefau/ioBroker.jarvis/issues/1285

**Comment by Zefau** [comment]
@mcuiobroker hast du die Lizenz aus der Rechnung 1-zu-1 im ioBroker drin?
