### ISSUE TITLE
CSS funktioniert überhaupt nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1287]
Seit `v3.0.0-beta.14` funktioniert folgender CSS-Selektor nicht mehr:
Damit konnte man bisher das Widget ausblenden.
```
.jarvis-page-887349d5-d5b7-408c-99a7-73a2a72b7194 .jarvis-widget-20f32ee7-60f1-448c-9aa8-851958a44fec {
	display: none !important;
}
```
Auch folgendes funktioniert nicht mehr? TAB ausblenden
```
[href="#/home0"] {
	display: none !important;
}
```
So wie es aussieht zieht CSS überhaupt nicht mehr.

**Comment by Zefau** [comment]
Pro not working, see https://github.com/Zefau/ioBroker.jarvis/issues/1285
