### ISSUE TITLE
JsonTable optional Suchleiste ausblenden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1288]
Suchleiste verbergen ist schon als Option eingebaut.
Besser wäre es wenn man selber entscheiden kann, welche Boxen von der Suchleiste ausblendbar wären.
![image](https://user-images.githubusercontent.com/84818934/145723418-358cf19e-a4bb-4ab2-847b-691f5092fc8d.png)
Zusätzliche 3 Optionsschalter: Suche, Column-Auswahl, Vergrößerung
oder wie auch im Gerät als JSON-Einstellung.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.19` gibt es nun wie gewünscht jeweils eine Option

**Comment by mcuiobroker** [comment]
Passt Danke.
