### ISSUE TITLE
JsonTable zeigt kein HTML

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1289]
https://forum.iobroker.net/post/719293

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/720494

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/721438

**Comment by Coalado** [comment]
Ich habe keine Ahnung warum, aber plötzlich wird HTML richtig dargestellt. Ich bin gerade auf v3.0.0-beta.14.

**Comment by Zefau** [comment]
Super :-)
