### ISSUE TITLE
Flexible Layout: Allow Widgets to span accross columns

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#129]

**Comment by ninja-warrior** [comment]
I would really appreciate to have such a feature. 

Taking a look at my current use case, I have to columns with different types of widgets. As you can see in the screenshot attached, the user experience would be much better if I could double the width of second column.

![Example](https://user-images.githubusercontent.com/73721169/97959099-ea754100-1dae-11eb-9324-809ed7a40a3a.PNG)

**Comment by Zefau** [comment]
Introduced with v3
