### ISSUE TITLE
Pop-up window if clicking on a device in a state list

### ISSUE THREAD

**Issue by kaikus** [Zefau/ioBroker.jarvis#1290]
I would like that after clicking on a sensor device (like temperatur) a pop-up window is opening with a history graph. How can I do that (jarvis3) ?

thanks

**Comment by mcuiobroker** [comment]
Vielleicht als zusätzliche Option im Gerät einbauen?
![image](https://user-images.githubusercontent.com/84818934/145866172-314b0906-ada9-41c2-9c76-194efa5515c1.png)
Genauso wie im HomeTileKit.
![image](https://user-images.githubusercontent.com/84818934/145866299-5ed76263-12a8-42c8-8494-c5dcbaf7fdc3.png)

**Comment by Zefau** [comment]
Duplicate https://github.com/Zefau/ioBroker.jarvis/issues/292
