### ISSUE TITLE
Popup You are Pro 

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1291]
Kannst Du das Popup "You are Pro" wieder wegnehmen oder nur einmal, nach dem Freischalten einblenden?

**Comment by mcuiobroker** [comment]
Ich würde es optional ausschalten in den Einstellungen. Dort könnte man es dann zur Prüfung wieder einschalten.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.16` gibt es nun eine Option in den Einstellungen

**Comment by AFPass** [comment]
Funktioniert. 
Wenn der Account abläuft, 1 Monat vorher kannst du ja eine Meldung einblenden.
