### ISSUE TITLE
Taster funktioniert wieder nicht 

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1293]
aktuelle BETA 15

1. lädt das Icon unendlich lange.
2. wenn ich den dazugehörigen Taster drücke geht das Licht wie gewünscht an und kurz darauf wieder aus.
![image](https://user-images.githubusercontent.com/22169074/145892662-014db72f-4fc9-4ccb-a73d-159356b273e9.png)

Config: 

```
"box_links_7cd3f": {
    "name": "Box (links)",
    "icon": "",
    "label": "",
    "function": "light",
    "states": {
      "power": {
        "showState": false,
        "state": "sonoff.0.box_links.POWER",
        "action": "sonoff.0.box_links.POWER",
        "actionElement": "SwitchAction",
        "label": "an / aus",
        "icon": "",
        "IconButtonActionConfig": {
          "showState": false
        },
        "bodyElement": null,
        "stateKey": "power"
      },
      "dimmer": {
        "showState": true,
        "state": "sonoff.0.box_links.Dimmer",
        "action": "sonoff.0.box_links.Dimmer",
        "unit": "",
        "label": "Dimmer",
        "icon": {},
        "LevelBodyConfig": {
          "step": "10"
        },
        "bodyElement": "LevelBody",
        "stateKey": "dimmer"
      },
      "hue": {
        "showState": false,
        "state": "sonoff.0.box_links.Hue",
        "action": "sonoff.0.box_links.Hue",
        "label": "Farbe",
        "icon": "",
        "bodyElement": "LightHueBody",
        "stateKey": "hue",
        "actionElement": null
      },
      "on": {
        "showState": false,
        "state": "0_userdata.0.taster_jarvis_dummy",
        "action": "sonoff.0.box_links.CW_POWER",
        "actionElement": "IconButtonAction",
        "label": "Weiss schalten",
        "icon": {
          "default": "palette"
        },
        "bodyElement": null,
        "stateKey": "on",
        "IconButtonActionConfig": {
          "iconTurnOn": "mdi-power",
          "pushButton": true,
          "flat": true,
          "iconTurnOff": "mdi-power",
          "buttonSize": "lg"
        },
        "properties": {
          "initial": true,
          "setOn": true,
          "setOff": true
        }
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Sonoff",
        "namespace": "sonoff"
      },
      "_created": 1606824239924,
      "_updated": 1609197254728
    },
    "id": "box_links_7cd3f",
    "revision": "d21b7"
  },
```

**Comment by Zefau** [comment]
Also nur das Icon was nicht funktioniert?

**Comment by ma-gu-16** [comment]
> * lädt das Icon unendlich lange.
> * wenn ich den dazugehörigen Taster drücke geht das Licht wie gewünscht an und kurz darauf wieder aus.

**Comment by Zefau** [comment]
Das ist doch der Sinn des Taster?! Wenn du den Zustand nicht zurück ändern willst, konfiguriere ohne Taster.

**Comment by Bernd9000** [comment]
Er hat setOn und setOff auf true gesetzt.
Bei mir ist der Fehler jetzt auch seit der letzten Beta wenn ich mich das erste mal verbinde.
Drücke ich F5 im Browser funktioniert der Taster wieder.

**Comment by Bernd9000** [comment]
@ma-gu-16
Schau mal ob die Taster Funktion noch eingeschaltet ist, das löst den Fehler auch aus.

![Bild3](https://user-images.githubusercontent.com/77005685/145972988-327c4cfb-9a7f-45b8-aabe-48f073f26f5d.jpg)

**Comment by ma-gu-16** [comment]
> b die Taster Funktion beim IconButtonAction noch eingeschaltet ist, das löst den Fehler auch aus.
> Und Taste F5 im Browser nicht vergessen

Alles klar , Also Button und nicht Taster mit setOn und setOff... 
scheint zu gehen. Dieses Verhalten hat sich doch aber sicher geändert? Da es bisher immer funktionierte. 

Ich werde nun alle Leuchten bei mir anpassen. Zumindest klappt das so jetzt. Danke dir vielmals!

**Comment by Bernd9000** [comment]
Kann sein das sich das Verhalten geändert hat, bin mir nicht sicher.
Jedenfalls hab ich mir gemerkt den Taster Modus in den Component Options gar nicht erst einzuschalten.
Der Taster Modus macht wohl nur bei dem SwitchAction (Umschalter) Sinn.
