### ISSUE TITLE
DateTime Einstellungen werden erst mit F5 korrekt dargestellt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1294]
`v3.0.0-beta.15`
Stellt man momentan die Einstellungen zum DateTime-Modul um, so werden die korrekten Werte erst mit F5 angezeigt.
Es wird sonst immer die vorherige Einstellung angezeigt.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-beta.16` nun funktionieren

**Comment by mcuiobroker** [comment]
Passt.

**Comment by michiproep** [comment]
May I reopen this issue? I'm running v3.0.11
DateTime is only updated on pageLoad

**Comment by Zefau** [comment]
please try with v3.1
