### ISSUE TITLE
tr-064 Importer fehlerhaft

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1298]
Button werden nicht korrekt eingestellt:
![image](https://user-images.githubusercontent.com/84818934/146010881-1379d4b2-ab84-4853-b069-e05dcc0b4e22.png)

![image](https://user-images.githubusercontent.com/84818934/146010924-d3e849e2-8bbf-4eaa-ac2d-cf594eade9ff.png)
Da es sich hierbei um Button handelt, muss man da nicht auch auf Taster umstellen?
![image](https://user-images.githubusercontent.com/84818934/146011091-0458f1c3-3dcf-462c-b634-56a1738dba29.png)

**Comment by Zefau** [comment]
Was ist fehlerhaft? Warum Taster?

**Comment by mcuiobroker** [comment]
Beim Importieren werden bei den Button von tr-064, keine Datenpunkt(Anzeige) Einträge erstellt.
Taster, da Button ja eine Tasterfunktionalität ist?

**Comment by Zefau** [comment]
> Beim Importieren werden bei den Button von tr-064, keine Datenpunkt(Anzeige) Einträge erstellt.

Das ist korrekt, da kein Datenpunkt zur Anzeige da ist. Die Datenpunkte führen nur aus und halten selbst keinen Wert vor.

>  Taster, da Button ja eine Tasterfunktionalität ist?

Dann würde meines Wissens nach beim Adapter 2x eine Aktion getriggert.

**Comment by mcuiobroker** [comment]
Ich dachte, dass die Icon-Problematik die beschrieben wurde, damit zusammenhängt, dass dort kein Datenpuntk(Anzeige) definiert ist. Wenn nicht, dann kann es geschlossen werden.

**Comment by Zefau** [comment]
Nein, ist gewollt. Die Icon Problematik hängt aber glaube ich damit zusammen. Das muss ich mir noch näher anschauen.
