### ISSUE TITLE
Modul DateTime zeigt keine Werte mehr an

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1300]
v3.0.0-beta.16
Es wird nur noch die Stadt angezeigt ?

![Unbenannt](https://user-images.githubusercontent.com/77005685/146097651-ff0beff8-23b5-4431-8db1-d2f8db8ee0f3.jpg)

**Comment by mcuiobroker** [comment]
iobroker upload jarvis?
Was hängen geblieben?

**Comment by Bernd9000** [comment]
Ne, keine Änderung.Bei Dir läuft alles ?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Bernd9000** [comment]
Hab gerade den Fehler gefunden:
In der Modul Konfiguration stand bei mir folgendes:
EEEE , dd. MMMM yyyy , HH:mm

Keine Ahnung wie das da rein kam, EEEE, entfernt und es läuft wieder.

**Comment by Bernd9000** [comment]
Hmmmmm
@Zefau
In der vendor.9cd5c900.js finde auch dieses EEEE.
Wo für ist das ?

i = "EEEE, LLLL d, yyyy, h:mm a";
