### ISSUE TITLE
Performance issues

### ISSUE THREAD

**Issue by Kaskadeur111** [Zefau/ioBroker.jarvis#1304]
Version 2.2 is way more responsive in therms of performance. Also Loading Times of Widgets are much slower.

Compared 2.2 to 3.0 beta

If i click on a switch in a stateList Widget in 2.2 the switch and the device is activated instantly
in jarvis 3.0 there is a delay of 0.5-1 second until the switches respond to the click action.

Also in 2.2 if i load jarvis the Widgets are shown simultaneous. In 3.0 some widgets are loading several seconds
until they show up the switches and stuff inside it.

**Comment by Zefau** [comment]
>  in jarvis 3.0 there is a delay of 0.5-1 second until the switches respond to the click action.

This is due to the fact, that in v2 it was set instantly in the vis and in parallel send to the backend.

In v3 it is send to the backend and the vis is updated based on the actual state update in ioBroker, which is pushed to jarvis after the state update in ioBroker. This can probably be more optimized but will most likely be always a bit slower than v2.

> Also in 2.2 if i load jarvis the Widgets are shown simultaneous. In 3.0 some widgets are loading several seconds
until they show up the switches and stuff inside it.

This can probably be optimized.

**Comment by Kaskadeur111** [comment]
Thanks. I expected your first answer. If i had a wish, could you please provide a general setting (maybe off in default) that commands are sent the same way as in v2 (instantly to vis and parallel to the backend). The feeling when using v2 is just so much better than v3. V3 feels really slow. I understand the benefits of waiting for the answer from the backend, but it just feels "wrong" and laggy.

btw. Jarvis is a genious product, i even donatet yesterday :-) Keep up the great work, realy appreciate it!!

**Comment by Zefau** [comment]
> Also in 2.2 if i load jarvis the Widgets are shown simultaneous. In 3.0 some widgets are loading several seconds until they show up the switches and stuff inside it.

should be better with `v3.0.0-beta.18`

**Comment by Kaskadeur111** [comment]
Perfect! I can confirm, that my whole visualisation now loads instant! Thank you!! :-)

**Comment by Zefau** [comment]
@Kaskadeur111 schau mal bitte mit 3.0.5

**Comment by Kaskadeur111** [comment]
Gerade geupdatet von 3.04.. Haut hin! die switches reagieren jetzt wieder sofort. :-) Perfekt.
