### ISSUE TITLE
Pie Chart wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1305]
Mit Version Beta17 werden bei mir keine Pie Charts mehr angezeigt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`

**Comment by mcuiobroker** [comment]
Wird wieder angezeigt.

**Comment by AFPass** [comment]
Bei mir wird es nicht richtig angezeigt. ![image](https://user-images.githubusercontent.com/13101074/146849830-2e1db336-0472-464d-83ad-b8b8a4afad56.jpeg)

**Comment by Zefau** [comment]
wie müsste es aussehen?

**Comment by AFPass** [comment]
Vermutlich das F5 Problem. Nach einem Reload der Seite sieht es richtig aus.
![grafik](https://user-images.githubusercontent.com/13101074/146904431-99fa7b98-b147-46ae-9918-752b006c09fd.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.19`

**Comment by AFPass** [comment]
Passt
