### ISSUE TITLE
Gelbes Dreieck aber der Wert ist nicht null

### ISSUE THREAD

**Issue by jvpihole** [Zefau/ioBroker.jarvis#1308]
Hier meine Umgebung: pro User und v3.0.0-beta.15.

Zunächst habe ich ein Problem mit dem gelben Dreieck mit dem Fragezeichen. Entgegen der Doku hat der Datenpunkt bei mir nicht den Wert null. Hier ein paar Screenshots dazu.
Wenn ich in die Seite reingehe, wird der Wert nicht angezeigt

![image](https://user-images.githubusercontent.com/59318539/146337540-01388acf-cf86-4403-82d7-fe40cf78ec57.png)

Wenn ich dann einen Reload mache, sieht das Ganze so aus und in der Console erscheint eine Warnung.

![image](https://user-images.githubusercontent.com/59318539/146337584-108e7a55-c15a-4fd8-b9ef-bfb03c3b21d8.png)

**Comment by Zefau** [comment]
Welchen Wert hat der Datenpunkt?

**Comment by Zefau** [comment]
@jvpihole Welchen Wert hat der Datenpunkt?

**Comment by jvpihole** [comment]
In dem Beispiel im Forum waren es 20 und 32. Aber das Dreieck erscheint bei jedem Wert auch bei 0 oder 100.  Ich vermute eher, dass es etwas mit der Datenpunktdefinition zu tun hat.
Hab aber keine Idee voran's liegt.
Es handelt sich um ein Knx-Dpt.
Hier die Definition des Dpts:

{
  "_id": "knx.0.Jalousie.UG_Büro_Tür_Status_Position_",
  "type": "state",
  "common": {
    "name": "UG Büro Tür Status Position ",
    "type": "number",
    "role": "value",
    "read": true,
    "unit": "%",
    "max": 100,
    "min": 0
  },
  "native": {
    "dpt": "DPT5.001",
    "address": "1/3/102",
    "addressRefId": "P-021C-0_GA-176",
    "statusGARefId": "",
    "actGARefId": "P-021C-0_GA-181",
    "update": "",
    "objRef": "",
    "devName": "",
    "devInst": "",
    "objectSize": ""
  },
  "acl": {
    "object": 1636,
    "state": 1636,
    "file": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1639846908278
}

Hab auch schon einmal versucht die Einheit in der Definition rauszunehmen "unit": "%", hat aber nichts gebracht.

**Comment by Zefau** [comment]
Wenn du mit der Maus über das Icon fährst zeigt er den Fehler an. Was für ein Fehler steht da bei dir?

**Comment by jvpihole** [comment]
Bei mir wird dabei gar nichts angezeigt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.20`

**Comment by jvpihole** [comment]
Hab jetzt die beta.21 getestet. Gelbes Dreieck immer noch vorhanden. Per Mouse over sehe ich jetzt eine Fehlermeldung (Cannot read properties ...), die der Fehlermeldung über die Console entspricht.
![image](https://user-images.githubusercontent.com/59318539/147351700-4bc86b5e-73af-4cf4-a1ab-f30ec3fb3b60.png)

![image](https://user-images.githubusercontent.com/59318539/147351783-ebc885c9-d8de-48b2-8526-fcf64d7725d3.png)

Werte sind 2 und 0.

**Comment by Zefau** [comment]
schwierig. schau bitte nochmal mit `v3.0.0-beta.22`

**Comment by jvpihole** [comment]
Es funktioniert mit beta.22 - danke.
