### ISSUE TITLE
Ein Schalter schaltet zwei verschiedene Datenpunkte

### ISSUE THREAD

**Issue by jvpihole** [Zefau/ioBroker.jarvis#1309]
Es wäre schön, wenn es die Möglichkeit in einem Schalter gäbe z.B. bei IconState unterschiedliche Datenpunkte für on und off zu hinterlegen? Beispiel on - schaltet Datenpunkt pause auf true, off - schaltet Datenpunkt resumepause auf true.

**Comment by Zefau** [comment]
Duplikat zu https://github.com/Zefau/ioBroker.jarvis/issues/695. Bitte dort voten.
