### ISSUE TITLE
Kopien sind keine Kopien, sondern Duplikate

### ISSUE THREAD

**Issue by jvpihole** [Zefau/ioBroker.jarvis#1310]
Hier meine Umgebung: pro User und v3.0.0-beta.15.

Wenn ich ein Widget oder einen kompletten Tab kopiere, erhalte ich keine Kopien, sondern Duplikate (gleiche Id) d.h., wenn ich ein Widget verändere, ändert sich auch das Duplikat. Eigentlich will ich ja wirklich Kopien, die dann nach dem kopieren unabhängig voneinander sind.

**Comment by Zefau** [comment]
Kann ich so nicht bestätigen. Wenn du via GUI kopierst, werden neue IDs generiert. Sowohl für Tabs, als auch für die Widgets.

Wie kopierst du denn genau? Kannst du beschreiben, wie du vorgehst und ein paar Screenshots machen? Danke dir.

**Comment by jvpihole** [comment]
Hast du meine Mail bekommen ? Soll ich in Zukunft hier über diesen Weg antworten?

**Comment by Zefau** [comment]
Besser hier. Wann hast die denn geschickt?

**Comment by jvpihole** [comment]
Die Mails habe ich um 21.46 und um 22.11 Uhr geschickt.

**Comment by jvpihole** [comment]
Hast du die Mails bekommen?

**Comment by Zefau** [comment]
Du beziehst die Zeiten auf heute? Nein. Ging das an iobroker.jarvis@mailbox.org ?

**Comment by jvpihole** [comment]
Nein, wenn ich auf deine Mail antworte geht das an: notifications@github.com

**Comment by Zefau** [comment]
Das sind nicht meine Emails, sondern Benachrichtigungen von Github. Die Email-Adresse gehört der Plattform, nicht mir.

**Comment by jvpihole** [comment]
Hier der Inhalt meiner Mail, die scheinbar irgendwo bei github verschollen ist. Deshaln in Zukunft hier.

Neuen Tab angelegt und darin ein neues Widget erzeugt

![image](https://user-images.githubusercontent.com/59318539/146839006-626b6710-3e3b-446f-a16d-2fde61d358d5.png)

Hier die Id des Widgets

![image](https://user-images.githubusercontent.com/59318539/146839068-0c48e2b7-98fc-4722-a64d-3e8f854ea937.png)

Über die Kopierfunktion im erstellten Widget (neben dem Stift) das Widget kopiert.

![image](https://user-images.githubusercontent.com/59318539/146839126-6e7070a1-2d78-4d62-a932-0f7dc7fc577a.png)

Hier das Duplikat. Und hier die Id des Duplikats:

![image](https://user-images.githubusercontent.com/59318539/146839169-5a8cb23e-482f-466b-90bb-671ec018e3ad.png)


Beide Widgets haben die gleiche Id.
Name der Kopie geändert und wie zu erwarten, ändert sich auch der Name des Originals.

![image](https://user-images.githubusercontent.com/59318539/146839226-ef3c9ff3-a901-4392-ba5e-5ed85d5c8d8f.png)

Nun habe ich das vorher neu erstellte Tab über die Oberfläche kopiert.

![image](https://user-images.githubusercontent.com/59318539/146839291-9411b512-730b-4684-9597-c7361fe8faa9.png)

Die Ids der beiden Tabs sind unterschiedlich.

![image](https://user-images.githubusercontent.com/59318539/146839348-1be0ecd1-d280-4479-a858-5f0e8f64064b.png)

Den Namen des neuen Tabs kann ich auch folgerichtig ändern.

Im neuen Tab habe ich die beiden identischen Widgets vom ersten Tab noch einmal. Jetzt habe ich im neuen Tab den Namen eines Widgets geändert und habe nun vier identische Widgets.
Zwei im alten Tab und zwei im neuen Tab.

![image](https://user-images.githubusercontent.com/59318539/146839396-bee0075f-ae0e-48d0-8aff-4c9833fcd3e5.png)

![image](https://user-images.githubusercontent.com/59318539/146839422-66e517d9-36e6-4502-8623-03d9d0479474.png)

Im Reiter Widgets sieht man den Zustand exakt.

![image](https://user-images.githubusercontent.com/59318539/146839473-8df4a149-1371-4f65-80af-0aaa8238b703.png)

Wenn ich im Reiter Widgets das Widget Test1... kopiere, dann entsteht eine wirkliche Kopie mit einer neuen Id.

![image](https://user-images.githubusercontent.com/59318539/146839512-c2cf2d7b-0e60-43b5-a7d3-32476f2d65a0.png)

Und hier das Ergebnis. Hier kann ich auch unabhängig von den anderen Test1-Widgets den Namen ändern.

![image](https://user-images.githubusercontent.com/59318539/146839565-08d52737-7013-4a4a-a75b-368e8575b7f4.png)


Und auch in dem zweiten Tab einfügen.

![image](https://user-images.githubusercontent.com/59318539/146839595-8d449698-aaea-4a0e-9285-3992f6f02466.png)


Ich hoffe es ist etwas deutlicher geworden. Gerade "echte" Kopien von Tabs wären eine deutliche Arbeitserleichterung, gerade wenn man Räume erstellt.

**Comment by Zefau** [comment]
Es handelt sich hierbei tatsächlich um das gewollte Verhalten.

Die Widgets werden nicht kopiert, sondern bewusst verlinkt. Du kannst auf diese Weise dasselbe Widget mehrfach nutzen (auf mehreren Seiten bzw. Tabs oder auch für die Smartphone-Ansicht).

Verstehe aber durchaus, dass das zu Verwirrungen führt.

Auf der anderen Seite würde ich ungern bei jedem Kopiervorgang das Widget kopieren. Da wäre die Liste an Widgets sonst ggf. ungewollt endlos lang.

**Comment by jvpihole** [comment]
Auch wenn das Verhalten gewollt ist, halte ich es nicht für gut. 

Wie oft brauche ich dasselbe Widget mehrfach. Dagegen gibt es durchaus Situationen bei denen ich verschiedene Tabs immer aus den gleichen Widgets aufbaue z.B. Räume enthalten bei mir immer die gleichen Widgets. 

Auch dem Argument, dass durch die Kopien eine endlose lange Liste von Widgets entsteht kann ich nicht teilen. 
Um beim Beispiele Räume zu bleiben. Ob ich einen Tab kopiere (richtig kopiere) oder einen Tab neu anlege und darin die gleichen Widgets mit anderen Datenpunkten neu anlege, ändert nichts an der Anzahl der Widgets. Auch wenn ich nicht kopieren kann, lege ich für jeden Raum einen Tab an. Nur mit mehr Arbeit.

Zudem ist das "Kopierverhalten" nicht durchgängig. Bei Tabs kopieren und Widgets kopieren über die Taboberfläche werden Links erzeugt. Wenn ich im Reiter Widgets Widgets kopiere, entsteht eine richtige Kopie des Widgets.

Wäre schön, wenn du deine Meinung noch ändern würdest. 

Wenn du Bedenken wegen der Anzahl hast, gäbe es auch noch die Möglichkeit von Templates bei denen nur bestimmte Teile über Variablen veränderbar sind, z.B. die Labels und die Datenpunkte. Aber ich möchte nicht noch ein größeres Faß aufmachen.

Auch wenn ich in dieser Sache nicht deiner Meinung bin, finde ich Jarvis richtig gut.

**Comment by Zefau** [comment]
Von der Logik her sind die Widgets den Tabs zugeordnet, analog der Zuordnung der Geräte zu den Widgets. Wenn ich ein Widget kopiere, dann kopiere ich ja auch nicht die Geräte, sondern habe dieselben Geräte zugeordnet.

Nichtsdestotrotz kann ich das absolut nachvollziehen. Mit der nächsten beta wird nicht mehr Referenz kopiert, sondern eine echte Kopie des Widgets erstellt. Die Geräte im Widget bleiben natürlich Referenzen.

**Comment by jvpihole** [comment]
Passt.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.20` umgesetzt

**Comment by jvpihole** [comment]
Mit beta.21 getestet. Kopieren funktioniert  wie gewünscht als Kopie und nicht als Duplikat. Sowohl beim Tab als auch beim Widget.

**Comment by funky4t** [comment]
Vielleicht ist ein `Clon` und eine `Kopie` tatsächlich eine gute Idee. Ich bau grade meine V2 um auf V3 um und gehe dabei in der Tat auch raumweise vor, wobei die Raumstruktur per Widget recht identisch ist. Darum auch die Kopie der Tabs. Dabei habe ich schon einige Male ungewollt das Ursprungs-Widgets verändert, was ich aber erst wieder im finalen Layout gesehen habe. Da drehst manchmal echt ein paar "Zusatzrunden" bis du das ungewollt geänderte Original-Widget und dann die Widget-Kopie wieder korrigiert hast..... Für einen reinen "Anwender" fehlt mir an der Stelle die sonst von Jarvis gewohnte Intuition beim Vorgehen, aber vielleicht liegt es an mir.... Der Rest ist wie V2 echt sensationell, wenn man sich nach nem Jahr mal wieder etwas in System reingroovt! :) Sobald die V3 die "WAF-Abnahme" hat, geh ich dann auch mal "PRO" :-)

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` nun `kopieren` (erstellt neues Widget) und `duplizieren` (referenziert bestehendes Widget)
