### ISSUE TITLE
Assign Widget to Box - DropDown Box

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1311]
In Beta 17 ist die Liste um ein Widget einer Box zuzuordnen größer als des Fenster.

![grafik](https://user-images.githubusercontent.com/13101074/146356366-fa6a0711-a860-42a7-95c9-42dcda47d51e.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`

**Comment by AFPass** [comment]
Passt
