### ISSUE TITLE
Assign Widget to Box - Suche

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1312]
Seit Beta 17 funktioniert die Suchbox nicht mehr.

![grafik](https://user-images.githubusercontent.com/13101074/146356786-902f463e-aed4-4e4d-81c0-9588180d8d05.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`

**Comment by AFPass** [comment]
Funktioniert.
