### ISSUE TITLE
Variablen für Farben

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1313]
Gibt es eine Möglichkeit für die  Line Color auch Variablen zu benutzen statt immer die Farbcodes?

_Originally posted by @AFPass in https://github.com/Zefau/ioBroker.jarvis/discussions/1301_

**Comment by Zefau** [comment]
implemented with `v3.1.0-alpha.26`

**Comment by mcuiobroker** [comment]
Beispiel? Beide ziehen nicht.
![image](https://user-images.githubusercontent.com/84818934/181512549-5c891b1e-0d5b-439c-8547-f8e08217eafb.png)
![image](https://user-images.githubusercontent.com/84818934/181512643-d094a9cd-270d-4183-963f-d9463ad83a73.png)

![image](https://user-images.githubusercontent.com/84818934/181512861-fc47ba77-a864-43a6-b143-1a9401aff74b.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.28`

**Comment by mcuiobroker** [comment]
Funktioniert. Danke.
