### ISSUE TITLE
Icons teilweise weg. 

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1319]
Hin und wieder kommt es vor das Icons fehlen. 

Im Widget und auch im Popup 

![image](https://user-images.githubusercontent.com/22169074/146571069-68acbbf8-b459-4d15-9ccc-45b22751c7ec.png)

Beta 17

**Comment by Zefau** [comment]
Wahrscheinlich https://github.com/Zefau/ioBroker.jarvis/issues/1302

**Comment by ma-gu-16** [comment]
Bin mir nicht sicher. 


Wenn ich in die Geräteconf schaue: 

z.b. 
![image](https://user-images.githubusercontent.com/22169074/146573435-068b1b79-79be-41d9-b628-94aabc94cbde.png)

da geht es , siehe oben. 

und die andern beiden sind leer. 
![image](https://user-images.githubusercontent.com/22169074/146573492-aa67bffd-d9a7-41a0-a279-b4bcab8c5932.png)

ich habe nirgends "eigene" hinterlegt, sind die welche als placeholder meist drin waren.

**Comment by Zefau** [comment]
ah ok, danke für den Hinweis

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`

**Comment by Zefau** [comment]
@ma-gu-16

**Comment by ma-gu-16** [comment]
scheint alles wieder da zu sein. Danke dir.
