### ISSUE TITLE
Json Table Max Entries

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1320]
![image](https://user-images.githubusercontent.com/22169074/146583587-8d222c8f-09fc-412c-b010-a75104806c33.png)

Mach wohl kein Sinn bei der Json Table Records per page: 10  1-7 of 7   
und deutsch wäre auch gut :-)

Danke

**Comment by Zefau** [comment]
Mit `v3.0.0-beta.18` wird die Leiste ausgeblendet wenn initial weniger `Records` (Zeilen) vorhanden sind als bei `Records per page` eingestellt ist. Außerdem nun auf deutsch.

**Comment by ma-gu-16** [comment]
klappt nicht. 

egal was ich einstelle. 

![image](https://user-images.githubusercontent.com/22169074/148702319-eede819c-3ac2-443b-9bd1-a2cc15573ea6.png)


![image](https://user-images.githubusercontent.com/22169074/148702335-e0a1bcd1-cda5-4b9c-83e4-2c99947fe89b.png)

**Comment by ma-gu-16** [comment]
(v3.0.5-beta.0)

**Comment by Zefau** [comment]
musste ich wieder rückgängig machen wegen https://github.com/Zefau/ioBroker.jarvis/issues/1362

**Comment by mcuiobroker** [comment]
@ma-gu-16 Falls du es ausblenden möchtest:
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/module/jsontable#zeilen-pro-seite-info-ausblenden

**Comment by ma-gu-16** [comment]
> @ma-gu-16 Falls du es ausblenden möchtest: https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/module/jsontable#zeilen-pro-seite-info-ausblenden

perfekt danke dir.
