### ISSUE TITLE
Widgets werden nach dem Speichern nicht mehr zugeordnet

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1322]
`v3.0.0-beta.17` erstmal für displayImage, andere nicht getestet.
Widgets werden nach dem Speichern nicht zugeordnet.
![image](https://user-images.githubusercontent.com/84818934/146640083-90631ff6-47df-49dd-86a8-8c48f36bb871.png)
ADD WIDGET
![image](https://user-images.githubusercontent.com/84818934/146640113-1fdeb3c2-708a-4d2e-870e-023a9adf4d0f.png)
Speichern
Gleiche Box:
![image](https://user-images.githubusercontent.com/84818934/146640132-85187e51-4e02-4cbe-8a6e-fcc313a5d6d2.png)
Man muss sie dann noch zuordnen:
![image](https://user-images.githubusercontent.com/84818934/146640155-99eef1ef-b850-477d-8e22-134c0fba1431.png)

**Comment by sigi2345** [comment]
> erstmal für displayImage, andere nicht getestet.

Ist auch bei anderen so.

**Comment by mcuiobroker** [comment]
displayImage:
Bei Änderung vom Bild (URL-http://...)  im Widget und speichern, wird das Bild im Frontend nicht geändert bzw aktualisiert.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`

**Comment by sigi2345** [comment]
> schau nochmal mit `v3.0.0-beta.18`

Danke, funktioniert bei mir wieder.

**Comment by mcuiobroker** [comment]
Ist wieder ok.
