### ISSUE TITLE
Google Kalender - Jährlich wiederkehrende Termine falsch

### ISSUE THREAD

**Issue by j-fk1987** [Zefau/ioBroker.jarvis#1324]
Hallo :-)

habe angefangen iobroker mit Jarvis zu nutzen. Bei dem Kalender Widget ist mir aufgefallen, dass meine jährlich wiederkehrenden Termine falsch dargestellt werden. Die Termine stehen einen Tag verzögert (+1) und jeden Monat drin.

Habe mal einen Screenshot beigefügt.

![Screenshot_20211219-072139_Chrome](https://user-images.githubusercontent.com/96358153/146672053-64483e5a-605d-4185-8041-1240c4402f7d.jpg)

Ich nutze Jarvis in der Version 2.2.5

Viele Grüße
j-fk1987

**Comment by Zefau** [comment]
Bitte auf v3 gehen
