### ISSUE TITLE
DisplayImage not updating

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1325]
Bei Änderung vom Bild (URL-http://...)  im Widget und speichern, wird das Bild im Frontend nicht geändert bzw aktualisiert. Man muss mit F5 die komplette Seite aktualisieren, damit das richtige Bild angezeigt wird.

_Originally posted by @mcuiobroker

**Comment by mcuiobroker** [comment]
Bild im Original werden gar nicht angezeigt:
https://mcuiobroker.gitbook.io/jarvis-infos/v3-fuer-einsteiger/module/displayimage#keine-anpassung-bild-im-original

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`
