### ISSUE TITLE
Update HistoryGraph-Konfig-Werte erst nach F5 aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1326]
`v3.0.0-beta.17`
Bei Änderung der Konfigwerte 
![image](https://user-images.githubusercontent.com/84818934/146688607-f0298059-482d-4147-b358-09557fd0411c.png)
werden diese erst nach F5 (Seite Frontend) korrekt dargestellt.

**Comment by mcuiobroker** [comment]
Beispiel HistoryGraph-Änderung vom Zoom-Slider Wert 80 auf 10, 80% auf 10% der Gesamtzeit.
![jarvis-v300-beta17-verhaltenHistoryGraphbeiÄnderung](https://user-images.githubusercontent.com/84818934/146691282-c3c44f1f-33c5-4450-a415-b967d5399a87.gif)
Aufnahme direkt nach Speichern & Zurück

**Comment by mcuiobroker** [comment]
Einstellungen im Frontend durcgeführt, werden nicht korrekt umgsetzt.
![image](https://user-images.githubusercontent.com/84818934/146691801-46e0a947-4b86-40f0-836c-2d8ea64ce4cc.png)
Der Zeitbereich wurde unten geändert auf 01.12.2021 - 19.12.2021. Es wird aber eine Kurve vom 14.12.2021 angezeigt.

**Comment by mcuiobroker** [comment]
Wechsel von Zeitleiste auf Rückblick und umgekehrt, werden die Tagesauswahl-Optionen nicht richtig umgestellt:
![image](https://user-images.githubusercontent.com/84818934/146692025-b194e147-dbaa-4d37-be20-f367a7416f3b.png)
Bei `Zeitleiste` dürfte nur der Kalenderbereich stehen und bei `Rückblick` nur die Anzahl Tage.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.24`

**Comment by mcuiobroker** [comment]
Funktioniert. Danke.
