### ISSUE TITLE
HomeKitTile zeigt kein Body-Element

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1327]
Obwohl ein Body-Element ausgewählt ist "LastChangeBody" wird dieses nicht angezeigt (Oben rechts).
![image](https://user-images.githubusercontent.com/84818934/146694205-30df00cc-6d17-47fb-8d11-2f755024306c.png)

Weiterhin ist es auch hier so, dass die Aktualisierung bei Neuanlage von einem HomeKitTile im Layout erst durch F5 wirksam wird.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`

**Comment by mcuiobroker** [comment]
Nein wird weiterhin nicht angezeigt.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.19`

**Comment by mcuiobroker** [comment]
Passt Danke.
