### ISSUE TITLE
Module Devices in Widgets lassen sich nicht löschen

### ISSUE THREAD

**Issue by pparvin** [Zefau/ioBroker.jarvis#1328]
Version 3 beta 17

Bei Widgets lassen sich keine Objekte (Devices/Trenner) mehr durch den Mülleimer löschen. Passiert auch bei einem ganz neuen Widget.

![image](https://user-images.githubusercontent.com/8461116/146791128-307936b7-6e13-40ae-a246-2e2724f97303.png)

**Comment by Zefau** [comment]
Funktioniert bei mir. 

Hast du Fehler im Log? Wie sieht das JSON des Layouts aus?

**Comment by pparvin** [comment]
jetzt geht es wieder. Ich hatte mir zwischenzeitlich mit dem Expertenmodus geholfen.

Danke für Deine Antwort
