### ISSUE TITLE
Aktuellen TAB in ein ioBroker-Objekt schreiben

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1330]
Man kann zurzeit einen Tabwechsel durch eintragen der Tabid in ein entsprechendes Objekt unter clients durchführen.
Sinnvoll ist auch in ioBroker zu wissen, wie der aktuelle Tab auf dem genutzten Gerät zurzeit ist.
Dazu bitte ein anderes ioBroker-Objekt mit den aktuellen Daten füllen.

**Comment by Zefau** [comment]
added with `v3.0.9-beta.0`

**Comment by mcuiobroker** [comment]
Funktioniert. ok.
