### ISSUE TITLE
StateList-Elemente erst nach F5 korrekt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1333]
`v3.0.0-beta.17`
Auf der Seite werden andere StateLists normal angezeigt.
![image](https://user-images.githubusercontent.com/84818934/146827434-64d26a89-d068-43e7-aa7f-d92c768ca67b.png)
Die Seite war nicht aktiv und jarvis wurde längere Zeit nicht bearbeitet bzw die Browserseite war nicht im Fokus.

**Comment by Zefau** [comment]
Ich glaub ich muss wieder einen kompletten Reload einbauen.

**Comment by mcuiobroker** [comment]
Mit  `v3.0.0-beta.18` wieder ok.
