### ISSUE TITLE
iFrame info bei URL fehlt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1334]
![image](https://user-images.githubusercontent.com/84818934/146830926-5038061d-edbc-4c73-b125-b62eddc0d037.png)

Die Info zum "i" fehlt.
Und bei Sandbox-Optionen
![image](https://user-images.githubusercontent.com/84818934/146831078-2e5071a2-d5e6-4bad-bd63-3c4b3d716327.png)

**Comment by Zefau** [comment]
entfernt mit `v3.0.0-beta.18`
