### ISSUE TITLE
iFrame zeigt kein Bild?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1335]
`v3.0.0-beta.17`
![image](https://user-images.githubusercontent.com/84818934/146838249-ba5a5c6a-bd07-4f80-be58-351719efd66b.png)
![image](https://user-images.githubusercontent.com/84818934/146838451-5fd1ac77-c5d8-4707-9cc3-1876507bfcc2.png)
Egal ob ohne Sandbox
![image](https://user-images.githubusercontent.com/84818934/146838559-0f0455e4-0f8c-4006-9290-151d5c9a7cd6.png)
oder mit Sandbox
![image](https://user-images.githubusercontent.com/84818934/146838605-ab4d2bc9-3ed2-4768-8d3c-edbfcdda33d0.png)
Es wird kein Bild angezeigt.

**Comment by Zefau** [comment]
Liegt vermutlich nicht an jarvis, sondern am Server, der die Anfrage ablehnt. Probier mal mit einer anderen externen Quelle bzw. binde das Bild mal bei vis ein.

**Comment by mcuiobroker** [comment]
Ich pack es mal hier rein: Bin mir nicht sicher, ob es am Bild liegt?
![image](https://user-images.githubusercontent.com/84818934/146850843-68287f2e-3063-41ad-b76f-e51c2b514a5f.png)

**Comment by Zefau** [comment]
ist vom Chart / HistoryGraph (Tooltip beim Mouseover)

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.19`
2 Probleme? Nach F5 war das Bild wieder auf richtiger Höhe angepasst.
![image](https://user-images.githubusercontent.com/84818934/147171201-e9a60818-4a25-4e6e-bdb6-9360243dd257.png)

DisplayImage EInstellungen:
![image](https://user-images.githubusercontent.com/84818934/147171268-446c720b-832d-4b78-aa6f-b5d8db915329.png)

iFrame Einstellungen:
![image](https://user-images.githubusercontent.com/84818934/147171361-0fc9760f-b7d7-4a7b-81ba-715a5d4dc6b3.png)

**Comment by Zefau** [comment]
Ist dies hier noch aktuell / offen? iFrame skaliert nicht richtig auf die Widget-Größe?

**Comment by mcuiobroker** [comment]
Ja hier ist das Problem, dass das Bild gar nicht gefunden wird, obwohl die gleiche Adresse verwendet wird, wie bei displayImage.

**Comment by Zefau** [comment]
Habe es gerade bei mir probiert und da geht es. Ich gehe davon aus, dass du die URL normal im Browser öffnen kannst?

Bitte wie oben geschrieben mal probieren:
> Liegt vermutlich nicht an jarvis, sondern am Server, der die Anfrage ablehnt. Probier mal mit einer anderen externen Quelle bzw. binde das Bild mal bei vis ein.

**Comment by Bernd9000** [comment]
@mcuiobroker 
Das Bild ist doch bestimmt nur über https erreichbar?

**Comment by mcuiobroker** [comment]
Nein, deswegen hab ich es ja extra nochmal als displayImage gezeigt. Gleicher Eintrag.
![image](https://user-images.githubusercontent.com/84818934/153082202-a741243d-f8e1-4e40-880b-329c55f5d654.png)

**Comment by mcuiobroker** [comment]
Also mit vis.0-Verzeichnis funktioniert es:
http://192.168.178.89:8082/vis.0/wegamstrand.jpg
Echt komisch.

**Comment by Zefau** [comment]
Ist da eine `.htaccess` oder ähnliches im `download` Ordner?

**Comment by mcuiobroker** [comment]
Nein.

**Comment by Bernd9000** [comment]
`v3.0.10`
Komisch, bei mir ist der Fehler im Modul DisplayImage
Hab mal eben mit einem eigenem Bild getestet.
Die Adresse ist bei mir "http://192.168.0.100/cadeau1.jpg"
Im Browser wird daraus:
Get  "http://192.168.0.100:8082/192.168.0.100/cadeau1.jpg

Im Iframe Modil funktionierte es.

**Comment by mcuiobroker** [comment]
Lag bei mir tatsächlich an der Einstellung vom apache2 Fileserver. Man muss dort `AllowOverride All` einstellen.
https://askubuntu.com/questions/421233/enabling-htaccess-file-to-rewrite-path-not-working
