### ISSUE TITLE
Nach F5 wird keine CSS mehr aktiv umgesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1337]
`v3.0.0-beta.18`
Nach F5 der Seite wird keine CSS mehr umgesetzt.
![image](https://user-images.githubusercontent.com/84818934/146846525-ffafbda5-e00d-4b3b-a0a6-95ee031b6659.png)
Geht man in die Konfig und Speichert:
![image](https://user-images.githubusercontent.com/84818934/146846584-2f7c3032-2925-48a0-a96f-23c854a8d1e0.png)

**Comment by mh-hdl** [comment]
v3beta18: 
CSS- Einstellungen aus Styles-Tab der Konfig. werden beim ersten Normal-Start / Aufruf (Link) am Desktop nicht geladen. Wenn man in die Konfig geht und speichert / abbricht, wird CSS geladen. Beim nächsten Aufruf ist erst einmal CSS wieder weg. Mobil (Android-Handy) geht CSS gar nicht (Konfig-Aufruf, für Test, geht mobil bei mir nicht, aber wohl auch normal und ist ja auch keine Lösung).

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.19`

**Comment by mh-hdl** [comment]
beta19:
CSS lädt wieder normal. Soweit so gut, aber es muss irgendwie einen Zusammenhang mit ISSUE #1207 geben. Das Laden der Icons (scheinbar dann wohl CSS-frei) war mit beta18 an jeden Gerät (mit WLAN und auch VPN) problemlos. Jetzt laden die Icons am Desktop und Handy auch normal, aber der, in #1207 beschriebene, Umstand bei VPN-Verbindung ist wieder da. Da dauert es wieder lange oder geht gar nichts mit den Icons. Das Ganze dann auch mit dem Status der jeweiligen Datenpunkte, die auch nicht geladen werden. D.h. kein Schalten etc. möglich...
