### ISSUE TITLE
Pie Chart wird nicht fehlerhaft angezeigt

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1338]
Die Pie Chart wird mit Beta 18 falsch angezeigt.
Der zweite Wert fehlt.
![grafik](https://user-images.githubusercontent.com/13101074/146887700-5e97ed7f-4dc6-49ea-b034-62ab442c75c1.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1305
