### ISSUE TITLE
Widget dynamische Höhe analog v2

### ISSUE THREAD

**Issue by MarkTyr** [Zefau/ioBroker.jarvis#1339]
Dynamische Inhalte wie z.B. der Kalender mit immer unterschiedliche längen / höhen. Die nachfolgenden Inhalte sollen entsprechend später beginnen.
Die Höheneinheiten sollen also nicht starr sein.

https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-beta-just-another-remarkable-vis/264

**Comment by Zefau** [comment]
Du kannst skalieren oder den Scroll Balken einblenden. Die Grid Architektur in v3 lässt logisch nichts anderes zu, weil es sonst kein Grid mehr ist.

Im Zweifel einfach die Box größer ziehen / darstellen?

**Comment by Rookiestyle** [comment]
Das Issue ist zwar closed und auch schon älter, aber wäre `autoSize` nicht genau das, was MarkTyr (und ich) suchen?

Bei mir wäre es JsonTable, bei der ich nicht blättern/im Widget scrollen möchte, sondern die Seite hoch-/runterscrollen will.
https://jbaysolutions.github.io/vue-grid-layout/guide/properties.html#autosize

> Says if the container height should swells and contracts to fit contents.

**Comment by mcuiobroker** [comment]
Dafür hat man doch den Vollbild Button?

**Comment by Rookiestyle** [comment]
Ja, das geht.
Allerdings habe ich dann immer den dicken Balken vom .q-table__control, dass den Vollbildbutton enthält und ich denke, dass `autoSize` vielleicht helfen könnte.

Wenn "Vollbild erlauben" auch die Höhe ändern würde, wäre das auch eine super Alternative, leider wird das Widget bei mir damit nur auf 100% Breite gezogen und die Höhe bleibt unverändert.
Ich probiere dann mal noch etwas und mache dann ggf. ein feature request dafür auf.
![image](https://user-images.githubusercontent.com/36454520/212561782-b739920f-3f4f-4719-9973-d569b93437a6.png)

**Comment by Zefau** [comment]
Das sollte so funktionieren wie gewünscht. Mach mal bitte einen Screenshot damit wir über dasselbe reden.

**Comment by Rookiestyle** [comment]
So sieht's auf meinem Tab aus:
![image](https://user-images.githubusercontent.com/36454520/213687368-ea911cc7-e6bb-43ab-85af-1befeacf06f2.png)


Im Feature Requests geht's mir um eine Möglichkeit, dass die Größe des mittleren Widgets sich an den Inhalt anpasst und nicht statt dessen Scrollbalken innerhalb des Widget angezeigt werden.
Wenn ich die Beschreibung von "autoSize" da falsch verstehe und das nicht geht, dann ist das halt so.

Bei dem (vermuteten) Bug geht's um die Anzeige, nachdem ich über das Dreieck rechts oben dieses Widget in den Vollbildmodus schalte.
Sollte das Widget da auch nicht die verfügbar Höhe voll ausnutzen?
![image](https://user-images.githubusercontent.com/36454520/213687877-bed2df4e-512d-475f-99f2-0b147e6e0c05.png)

**Comment by Zefau** [comment]
Betrifft es nur JsonTable?

**Comment by Rookiestyle** [comment]
Ich nutze StateList, DateTime, HistoryGraph, JsonTable, IFrame und Weather.

Ü*Test 1: Bei allen Widgets Vollbild erlauben aktiv, Skaliere Inhalt zur Widgetgröße nicht aktiv*Ü
StateList: Ist betroffen
DateTime: Vollbildsymbol wird nicht angezeigt (rot markiert im Screenshot)
HistoryGraph: Ist betroffen
JsonTable: Ist betroffen
IFrame: Ist betroffen
Weather: Ist betroffen

**Test 2: Bei allen Widgets Vollbild erlauben aktiv, Skaliere Inhalt zur Widgetgröße aktiv**
StateList: Nicht betroffen
DateTime: Nicht betroffen
HistoryGraph: Ist betroffen
JsonTable: Ist betroffen (keine "Skaliere" Option vorhanden)
IFrame: Ist betroffen (keine "Skaliere" Option vorhanden)
Weather: Nicht betroffen





![image](https://user-images.githubusercontent.com/36454520/213775304-5df0d61a-ae92-4721-806a-701139b026ce.png)
Fehlendes Vollbildsymbol bei Test 1

**Comment by Rookiestyle** [comment]
Als Zusatzinfo:

Wenn "Skaliere Inhalt zur Widgetgröße" aktiv ist, dann werden auf meinem Smartphone diese Widgets nicht mit 1h angezeigt sondern in der tatsächlich benötigten Höhe ohne Skalierung: StateList, DateTime, Weather

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by Rookiestyle** [comment]
Nutze aktuell 3.1.3-beta15
Test 1: Bei allen Widgets Vollbild erlauben aktiv, Skaliere Inhalt zur Widgetgröße nicht aktiv
Test 2: Bei allen Widgets Vollbild erlauben aktiv, Skaliere Inhalt zur Widgetgröße aktiv

Ergebnis in beiden Fällen:
HistoryGraph: Ist noch nicht OK 
IFrame: Ist noch nicht OK
StateList: Ist jetzt OK
DateTime: Ist jetzt OK
JsonTable: Ist jetzt OK
Weather: Ist jetzt OK

Wenn ich das Browserfenster bei Test 2 verkleinere, sieht es so aus wie auf dem Screenshot
Die Widgets sind nicht mehr untereinander sondern in zwei Spalten nebeneinander.
Der Inhalt ist nicht mehr so skaliert, dass er zur eigentlichen Widgethöhe passt, sondern die Widgethöhe wird angepasst.
Ist das so gewollt?

Vollbild:
![image](https://user-images.githubusercontent.com/36454520/215581085-a149423a-72b5-47d7-a91d-23dd2d444591.png)

Fenster verkleinert (2548 x 1941)
![image](https://user-images.githubusercontent.com/36454520/215580837-89bb1d3c-5391-4623-96e4-59ab2f8aedc6.png)

**Comment by mcuiobroker** [comment]
Welche Einstellungen hast du denn hier?
![image](https://user-images.githubusercontent.com/84818934/215585234-ba887e7e-940f-466b-a095-33773466d1e2.png)
Welche Breite hat das Fenster in der Verkleinerung?

**Comment by Rookiestyle** [comment]
Breakpoint small: 600
Breakpint medium: 1024

Wenn das Fenster breiter ist als die 1024px aus breakpoint-md, dann werden die Widgets alle untereinander angezeigt - also so, wie im Layout angeordnet
Wenn das Fensterbreite zwischen 600px und 1024px liegt, dann werden die Widgets nebeneinander angeordnet
Wenn das Fensrer schmaler ist als die 600px aus breakoint-sm, dann werden die Widgets alle untereinander angezeigt

Alle Widgets in dem Testtab haben die Maße 5w x 1h

Unabhängig von der Fensterbreite werden StateList, DateTime, JsonTable und Weather in der Höhe so skaliert, dass der Inhalt angezeigt wird, wenn `Skaliere Inhalte zur Widget-Größe` aktiv ist.
Die Widgets sind also nicht mehr 1h, sondern höher. Das ist von meinem Verständnis her genau andersrum als das, was die Option sagt

**Comment by Zefau** [comment]
iFrame sehe ich, was nicht funktioniert. Was aber geht bei HistoryGraph nicht? Kannst du das mal screenshoten?

**Comment by Rookiestyle** [comment]
Das hier ist die Vollbildansicht des HistoryGraph, das Widget ist aber nach wie nur 1h hoch. Das sollte doch auch höher werden, oder nicht?
![image](https://user-images.githubusercontent.com/36454520/217643396-b2e98420-9e51-4824-bc9d-c1966345d3da.png)

html dazu
```
<div class="jarvis-HistoryGraph" style="min-width: 100%; min-height: 100%; width: 1536px; height: 25px;">
  <x-vue-echarts class="echarts" _echarts_instance_="ec_1675888024665" style="user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); position: relative;">
    <div style="position: relative; width: 1536px; height: 25px; padding: 0px; margin: 0px; border-width: 0px;">
      <canvas data-zr-dom-id="zr_0" width="3840" height="62" style="position: absolute; left: 0px; top: 0px; width: 1536px; height: 25px; user-select: none; -webkit-tap-highlight-color: rgba(0, 0, 0, 0); padding: 0px; margin: 0px; border-width: 0px;"></canvas>
    </div>
    <div class=""></div>
  </x-vue-echarts>
</div>
```
Das ist zwar alles in einem div mit class `jarvis-widget-scaler full-width` und `height: auto`, aber da steht bei zwei divs und canvas `height: 25px` und bei canvas zusätzlich noch `height=62` 
Ganz verstehe ich es nicht, aber für mich sieht's aus als wird das 1:1 von der kleinen Anzeige auf dem Tab übernommen und nicht angepasst

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.31` bzgl. HistoryGraph und iFrame

**Comment by Rookiestyle** [comment]
Die beiden Widgets nutzen jetzt auch die volle Höhe im Vollbildmodus.

Allerdings werden mit `3.1.3-beta.31` wieder einige Icons nicht im Quick Jumper angezeigt, bspw. `fluent:conference-room-20-regular` oder `ic:round-local-dining`
Weiter im geschlossenen #2097 oder neues Issue?
