### ISSUE TITLE
Popup wird nicht unterdrückt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1342]
`v3.0.0-beta.18`
![image](https://user-images.githubusercontent.com/84818934/146945679-dddc8da0-0764-4bd5-888d-31f21352ce49.png)
Popup wird nicht unterdrückt.
Klickt man auf die Widgetfläche wird das Popup angezeigt.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.19`

**Comment by mcuiobroker** [comment]
Passt Danke.
