### ISSUE TITLE
Adapter Widget - Starten/Stoppen lässt Jarvis abstürzen

### ISSUE THREAD

**Issue by M0nk3yOo** [Zefau/ioBroker.jarvis#1344]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ v3.0.0-beta.17 ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ 
<img width="1790" alt="image" src="https://user-images.githubusercontent.com/32765291/147083688-a61db2bb-0eca-42ce-b736-8cf4249db432.png">
] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Starten/Stoppen eines Adapters über das Widget
<img width="803" alt="image" src="https://user-images.githubusercontent.com/32765291/147083845-6c5527ef-3d68-4ae4-a30b-684c3cf5fbe6.png">

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.19`

**Comment by M0nk3yOo** [comment]
Jap, damit kommt nun kein Fehler und Absturz mehr
