### ISSUE TITLE
Falsches Icon nach Aktualisierung im Browser (Binding im Datenpunkt) 

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1345]
v3.0.0-beta.19 (auch schon bei v3.0.0-beta.18)
Betroffen: Mehrere Geräte Steckdosen, Rolladen außer Dimmer
Fehler im Browser: Nein

Bei den Geräten lasse ich mir u.a. durch blinkendes gelbes Icon anzeigen das ein Gerät offline ist.
Dazu benutze ich ein Binding im Datenpunkt Level zum Datenpunkt Status (hier z.B. bein einem Shelly 2.5 Rolladensteuerung):

{"default":"window-shutter-alert","{shelly.0.SHSW-25#483FDA8D30EE#1.online}=false":"window-shutter-alert blink","<5":"window-shutter",">95":"window-shutter-open"}

Ist jarvis geöffnet und ich schalte die Geräte Spannungslos blinken die Icons gelb, das ist richtig.
Aktualisiere ich jetzt aber mit F5 die Anzeige im Browser blinken einige Geräte nicht mehr.
Die Icon zeigen dann den letzten Schaltzustand an, grün=eingeschaltet oder auf, rot= ausgeschaltet oder zu.

Hier wird z.B. nur der Dimmer als Offline angezeigt:
![Unbenannt](https://user-images.githubusercontent.com/77005685/147107061-e2af31ab-d3a6-4f13-b500-7a2ba4544ca4.jpg)

**Comment by Zefau** [comment]
Bitte komplette Config posten. Das mit den Farben kann ich nicht nachvollziehen, da ich die Config nicht kenne.

**Comment by Zefau** [comment]
Du weißt auch, dass bei einem Wert >=5 und <=95 (also z.B. 50) der `default` greift? Der ist mit `window-shutter-alert` (ohne `blink`) definiert. Ist das gewollt?

```
{
	"default":"window-shutter-alert",
	"{shelly.0.SHSW-25#483FDA8D30EE#1.online}=false":"window-shutter-alert blink",
	"<5":"window-shutter",
	">95":"window-shutter-open"
}
```

**Comment by Bernd9000** [comment]
Ja, die default Werte hatte ich teilweise eingeführt wegen verschwundener Icons aus einem anderen Issue.

Nehmen wir erstmal ein einfaches Gerät.
Hier mal die Konfiguration der "Steckdose-3" aus dem oberen Bild und von default Werten bereinigt.
Die hat nur zwei Datenpunkte "state" und "power".
Das Icon soll  gelb blinken wenn offline, grün für Steckdose eingeschaltet, rot für ausgeschaltet.
Solange jarvis im Browser geöffnet ist funktioniert alles.
Jetzt schalte ich die Steckdose spannungslos, nach kurzer Zeit blinkt das gelbe Icon , genau das was ich haben wollte.
Und wenn ich jetzt das Browserfenster aktualisiere mit z.B. F5 oder den Browser neu starte dann sollte auch wieder das Icon blinken.tut es aber nicht, es bleibt bei mir rot für ausgeschaltet.
Gleichzeitig wird im Popup beim Datenpunkt "status" aber ganz normal das blinkende Wifi Symbol angezeigt für Offline in rot.

Geräte Konfiguration:

"d029147d-3e22-47d7-bf49-14aef9a65122_f5b43": {
    "name": "Steckdose-3",
    "icon": "",
    "label": "Steckdose-3",
    "function": "socket",
    "states": {
      "state": {
        "showState": true,
        "stateStyle": "",
        "state": "mqtt.0.tele.Steckdose-3.LWT",
        "iconStyle": {
          "Offline": {
            "color": "#F00"
          },
          "Online": {
            "color": "#0F0"
          }
        },
        "icon": {
          "Offline": "wifi-alert blink",
          "Online": "wifi"
        },
        "label": "",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "state",
        "display": "",
        "key": "Status"
      },
      "power": {
        "showState": true,
        "action": "mqtt.0.cmnd.Steckdose-3.POWER",
        "state": "mqtt.0.stat.Steckdose-3.POWER",
        "stateStyle": "",
        "properties": {
          "on": "ON",
          "off": "OFF"
        },
        "iconStyle": {
          "{mqtt.0.tele.Steckdose-3.LWT}='Offline'": {
            "color": "#FF0"
          },
          "ON": {
            "color": "#0F0"
          },
          "OFF": {
            "color": "#F00"
          }
        },
        "display": "",
        "icon": {
          "{mqtt.0.tele.Steckdose-3.LWT}='Offline'": "power-socket-de blink",
          "ON": "power-socket-de",
          "OFF": "power-socket-de"
        },
        "label": "",
        "bodyElement": null,
        "stateKey": "power",
        "key": "power",
        "SwitchActionConfig": {
          "val": "val"
        },
        "actionElement": "SwitchAction"
      }
    },
    "options": {
      "suppressPopup": false
    },
    "attributes": {
      "_created": 1609743537279,
      "_updated": 1620160015547
    },
    "id": "d029147d-3e22-47d7-bf49-14aef9a65122_f5b43",
    "revision": "39bf4"
  },


![1](https://user-images.githubusercontent.com/77005685/147346597-3e61a5d9-4546-454b-952d-717659e4f620.jpg)
![2](https://user-images.githubusercontent.com/77005685/147346602-5b4ac5b5-703f-4e0c-bf6b-6d7b410e6535.jpg)

**Comment by Bernd9000** [comment]
Wenn ich den Datenpunkt mqtt.0.tele.Steckdose-3.LWT nochmal selbst mit dem selben Wert auf "Offline" setze funktioniert das Binding wieder und das Icon blinkt gelb.Es hängt also mit der Aktualisierung zusammen.
Scheinbar wartet jarvis nach der Browser Aktualisierung auf eine Änderung beim Datenpunkt die aber nicht eintritt weil das Gerät nach wie vor Offline ist.
jarvis müßte also nach der Browser Aktualisierung den Binding Wert abfragen.

**Comment by Zefau** [comment]
@Bernd9000 probier nochmal bitte mit `v3.0.0-beta.23`

**Comment by Bernd9000** [comment]
v3.0.0-beta.23
Fehler ist noch vorhanden

**Comment by Zefau** [comment]
Nein, @RkcCorian auch, siehe https://github.com/Zefau/ioBroker.jarvis/issues/1369

**Comment by Zefau** [comment]
Verwendest du den Datenpunkt des Bindings (`shelly.0.SHSW-25#483FDA8D30EE#1.online`) sonst irgendwo in einem Gerät?

**Comment by Bernd9000** [comment]
> Nein, @RkcCorian auch, siehe #1369
Hab ich gelesen, beim Ihm ist es aber sporadisch seit beta-24, bei mir dauerhaft seit beta.18
Daher denke ich das es ein anderes Problem sein könnte


> Verwendest du den Datenpunkt des Bindings (`shelly.0.SHSW-25#483FDA8D30EE#1.online`) sonst irgendwo in einem Gerät?
Ja, auf einer anderen javis Seite.
Dort habe ich eine Übersicht über alle Geräte und deren Online Status als Übersicht.

**Comment by Bernd9000** [comment]
Der Testschalter ist ganz einfach erstellt, zwei Datenpunkte z.B. "state" und "power" unter 0_userdata.0. anlegen und bei einem neuen Gerät diese Datenpunkte anlegen.Dann das Binding mit Verweis auf "state" im Icon, fertig.

Beispiel Binding:
{"{0_userdata.0.Test.Test-Datenpunkt2.status}=false":"mdi:lightbulb-on blink","true":"mdi:lightbulb-on","false":"mdi:lightbulb-off-outline"}

![1](https://user-images.githubusercontent.com/77005685/147394588-082fcf2d-9d78-443e-bb79-ce14291b0efd.jpg)
![2](https://user-images.githubusercontent.com/77005685/147394589-78814964-e2b5-43bd-a0cb-677fc8650620.jpg)

**Comment by Zefau** [comment]
Jo, danke dir. Ich hab das Problem inzwischen bei mir nachgestellt bekommen. Nu ist die Frage, wo der Fehler liegt :-)

**Comment by RkcCorian** [comment]
Brauchst Du dann noch ne Konfig von mir? Wollte gerade eine Posten, ist aber recht länglich :-)

**Comment by Bernd9000** [comment]
Könnte es vielleicht mit den Geräte Typ selbst zusammenhängen?
Denn das Auffälligste ist ja, das der shelly Dimmer 2 bei mir funktioniert.
Und diesen hattest Du glaube ich schon mal bei einem anderen Issue dir vorgeknüpft.
Da hatte ich schon mal ein ähnliches Problem mit der Anzeige der Icons oder mit den Farben.

**Comment by Zefau** [comment]
Hab den Fehler.

**Comment by Zefau** [comment]
probiert nochmal bitte mit `v3.0.0-beta.25`

**Comment by RkcCorian** [comment]
Fast... Binding funktioniert richtig, allerdings kommst nach ein paar Sekunden...
![image](https://user-images.githubusercontent.com/79741077/147395202-a5e70e34-ed55-4d8b-98f7-477596d0eabb.png)

**Comment by Bernd9000** [comment]
Dito
![Unbenannt](https://user-images.githubusercontent.com/77005685/147395229-7db9a517-f282-407e-84cb-8cf65a30753d.jpg)

**Comment by Zefau** [comment]
`3.0.0-beta.26`

**Comment by RkcCorian** [comment]
Bindings funktionieren nicht zuverlässig. Dieses Issue oder ein Neues? Hab Folgendes Verhalten bei 2 Geräten

Korrekt:
![image](https://user-images.githubusercontent.com/79741077/147408090-2d010a34-a2f9-44eb-a7ec-6819df7109c5.png)

Fehler:
![image](https://user-images.githubusercontent.com/79741077/147408101-089845a6-23c0-474f-85e7-fa8ac34d7570.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.27`

**Comment by RkcCorian** [comment]
Geht :-)

**Comment by Bernd9000** [comment]
v3.0.0-beta.27
Funktioniert bei mir jetzt auch, super :-)
Hab allerdings jetzt mit einer Trägheit beim Seitenaufbau zu kämpfen.
Ich kann förmlich zuschauen wie jedes einzelne Icon sich auf der Seite aufbaut.
In der Browserkonsole habe ich in wenigen Sekunden 500-1000 Warnmeldungen.
Browser hat zu diesem Zeitpunkt 30% CPU Auslastung.


![Unbenannt](https://user-images.githubusercontent.com/77005685/147420394-6981442a-7928-431b-a6b0-25f676062d59.jpg)

**Comment by Zefau** [comment]
arg, das sind meine Debugging Sachen, die muss ich wieder raus nehmen mit der nächsten beta

**Comment by Bernd9000** [comment]
Hab ich mir fast gedacht, Okay :-)

**Comment by RkcCorian** [comment]
Hatte ich mir doch auch schon gedacht, dass es sehr zäh ist :-)
