### ISSUE TITLE
Icon Feld fälschlicherweise als Pro Feature ausgewiesen

### ISSUE THREAD

**Issue by danickel** [Zefau/ioBroker.jarvis#1346]
Jarvis v3.0.0 beta 19

In der Gerätekonfiguration erscheint neben dem Icon (Json) Feld ein "Pro" Icon. Die Icon Konfiguration ist weiterhin möglich, daher ist das "Pro-Icon" vermutlich falsch.

![grafik](https://user-images.githubusercontent.com/90868055/147165039-a47933c7-6c3c-4cb2-a8bf-65b4f304ffab.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-beta.20` behoben sein
