### ISSUE TITLE
Labels im Layout werden nicht übernommen

### ISSUE THREAD

**Issue by danickel** [Zefau/ioBroker.jarvis#1347]
jarvis v3.0.0 beta 19

Labels die im Layout vergeben werden, werden nicht übernommen. 
Stattdessen wird das Label aus dem Gerätenamen übernommen. Wenn dort kein Label vergeben wurde, wird der Gerätenamen angezeigt.

![grafik](https://user-images.githubusercontent.com/90868055/147165191-033e38ba-1111-4df0-b540-a6536699bf94.png)

**Comment by Zefau** [comment]
Kann ich so nicht bestätigen. Bei mir übernimmt er die Label Konfiguration aus dem Layout. Kannst du mal screenshoten was du konkret meinst, damit wir über dasselbe reden?

Layout:

![image](https://user-images.githubusercontent.com/14368811/147239445-f1f113eb-9947-44ef-a857-cc9110561f8c.png)

Frontend:

![image](https://user-images.githubusercontent.com/14368811/147239498-52aba0aa-e11c-4264-bccd-3b19dbcbf74f.png)

**Comment by Zefau** [comment]
@danickel

**Comment by Zefau** [comment]
@disaster123 Kannst du das mal screenshoten? Ich kann das nicht nachstellen.

**Comment by disaster123** [comment]
Klar:

Anzeige;
![image](https://user-images.githubusercontent.com/861558/147419750-4fe59460-9efe-47ab-a1db-613d7f91a9c4.png)

Settings:
![image](https://user-images.githubusercontent.com/861558/147419775-ecaf1b66-7556-4d38-b6f0-6a69b2dc225f.png)

**Comment by Zefau** [comment]
Geräte Label ist nur für das Backend. Das ist so gewollt.

Die Reihenfolge der Anzeige ist
1. Label Layout
2. Label State
3. Geräte Name

**Comment by disaster123** [comment]
OK danke. War aber irgendwann mal anders ;-) Ich fand es ganz gut einen extra visaible Name definieren zu können der anders als der technische Gerätename ist.

**Comment by Zefau** [comment]
Ja war man anders, aber das ist ja auch so wie du es brauchst oder?


> Ich fand es ganz gut einen extra visaible Name definieren zu können der anders als der technische Gerätename ist.

Name hast du im Frontend. Label im Backend

**Comment by Zefau** [comment]
Kann das geschlossen werden ?
