### ISSUE TITLE
HomeKitTile nicht zentriert, da plötzlich zusätzliche Werte?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1349]
HomeKitTile sind nicht mehr zentriert
![image](https://user-images.githubusercontent.com/84818934/147170093-b8b88fb5-2d95-4ed4-9606-6989f920a6ad.png)
Es wird in alle HomeKitTile plötzlich zusätzlich etwas rein geschrieben
Links habe ich alle Werte nicht eingetragen.
![image](https://user-images.githubusercontent.com/84818934/147170176-ea4eb4a0-831b-42e3-adc9-b965e20e8289.png)
Auch, wenn man die linken Werte wieder raus nimmt, wird es nicht zentriert angezeigt.

- [ ] linke Einstellungen wurde nicht angezeigt?
- [ ] linke Einstellungen wurde per Programm zusätzlich hinzugefügt
- [ ] Elemente Mitte nicht zentriert dargestellt

**Comment by mcuiobroker** [comment]
Vielleicht kann man beim Body-Element die Schrfdit noch vertikal zentrieren?
![image](https://user-images.githubusercontent.com/84818934/147276011-fe320dd1-e136-4e05-ac2e-e9a28c38edaf.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-beta.20` behoben sein

**Comment by mcuiobroker** [comment]
Werte werden wieder zentriert angezeigt, nur noch für Body-Element offen
![image](https://user-images.githubusercontent.com/84818934/147291807-654c1c41-c855-4ff4-b4ad-a916e5ea0f8a.png)

**Comment by Zefau** [comment]
probier nochmal bitte mit `v3.0.0-beta.21`

**Comment by mcuiobroker** [comment]
Das sieht gut aus. Danke.
![image](https://user-images.githubusercontent.com/84818934/147298675-0a772a93-07c3-4f26-b8c1-ab91477db594.png)

**Comment by SliX185** [comment]
Leider hab auch ich immer noch Probleme mit der Zentrierung... ich hab gehofft es wär mit dem Issue behoben, leider nein.
jedoch sind bei mir die "Secondary States" nicht zentriert. Alle anderen auswählbaren Elemente werden zentriert.

![config](https://user-images.githubusercontent.com/47434006/147511920-987135ed-96d1-4171-804f-1358611e2218.JPG)

![tile3](https://user-images.githubusercontent.com/47434006/147511923-0d393809-d8ce-4e5a-a142-fd7539e795d4.JPG)

...wobei der container anscheinend grundsätzlich zentriert ist.
![tile2](https://user-images.githubusercontent.com/47434006/147511960-81e3f353-b6ed-40a2-a886-c1643ac48a4e.JPG)

und nochmal im gesamten.
![tile1](https://user-images.githubusercontent.com/47434006/147512053-6f51cc6a-7b3d-4934-8fbe-3bcea67c1d20.JPG)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.1`

**Comment by SliX185** [comment]
Schaut gut aus! Besten Dank!

![tile4](https://user-images.githubusercontent.com/47434006/147603211-86549904-51f5-4e66-a04e-ff4a25127fd8.JPG)

meckern auf hohen Niveau: Vertikal passt die Zentrierung, Horizontales spacing nicht ganz. bisschen zu tief... könnt ich aber leben mit ;)
![tile5](https://user-images.githubusercontent.com/47434006/147603356-c1a7ce57-7d47-4941-8e29-9d4a5821b676.JPG)

**Comment by Zefau** [comment]
Bei mir passt es. Bei dir sehe ich auch, dass es nicht 100% zentriert ist. Kannst du die Ursache im DOM ausmachen? Ist irgendwo noch ein Spacing drin?

**Comment by SliX185** [comment]
![padding](https://user-images.githubusercontent.com/47434006/147648594-35fcc3d3-494f-4fe0-b4a8-15359a900f78.png)

`.HomeKitTile.grid .center {
    margin: auto !important;
}`

... mit !important funktionierts, finde aber leider den Ursprung nicht.

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.2-beta.0`

**Comment by SliX185** [comment]
Du hast jetzt das implementiert:

`.HomeKitTile.grid .center {
    margin-left: auto !important;
    margin-right: auto !important;
    text-align: center;
}`

ändert leider nichts. "Fehlerbild" bleibt identisch.
funktioneren würde es mit:

`.HomeKitTile.grid .center {
    margin: auto !important;
    text-align: center;
}`

oder auch alleinig mit `margin-bottom:`

`.HomeKitTile.grid .center {
    margin-bottom: auto !important;
    text-align: center;
}`

-----------------

=> Ursache wird aber die `margin-bottom: 0;` sein. Hat wohl ne höhere Prio. Wenn man die bottom margin raus nimmt, alles tip top.


`.HomeKitTile.grid .bottom > div {
    margin-top: auto;
    margin-bottom: 0;
}`

**Comment by Zefau** [comment]
Ah okay

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.2`

**Comment by SliX185** [comment]
... Erstmal wünsch ich Dir ein Gutes neues Jahr! 

Tip Top! v3.0.2 funktioniert. 

Besten Dank!

**Comment by Zefau** [comment]
Dir auch ein frohes Neues! :-)
