### ISSUE TITLE
Calendar not shown

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1350]
https://forum.iobroker.net/post/725190

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/725308

**Comment by M0nk3yOo** [comment]
Hallo zusammen,
auch wenn meine Fehlermeldung etwas anders aussieht, wird mein Kalender nicht angezeigt.
Ich wollte jetzt kein neues Issue dazu aufmachen.

Hintergrund: Apple Familienkalender - iCal - öffentlich freigegeben.
Problem: Kalender wird nur bei diesem Familienkalender nicht angezeigt. Ein Testkalender, sowie ein Müll Abfuhrkalender werden problemlos angezeigt. Die Entiwicklerkonsole gibt mir Fehler aus.

<img width="549" alt="image" src="https://user-images.githubusercontent.com/32765291/147470470-a7f8e3a0-da33-47ba-804d-b876ec4c6781.png">

Im iCal Adapter werden die Inhalte korrekt geladen.

**Comment by Zefau** [comment]
Die ical Daten scheinen falsch zu sein. Musst mal googeln, was "Missing Parameter value" für "X-APPLE-STRUCTURED-LOCATION" bedeutet.

**Comment by M0nk3yOo** [comment]
Greifst Du denn selbstständig auf die iCal zu, oder auf den iCal-Adapter? Wie gesagt, der Adapter liest es problemlos aus.
Ich suche aber mal ne Runde

**Comment by M0nk3yOo** [comment]
Ich habe es lösen können. FYI: ich habe in alten Terminen ein Standort hinterlegt, mit dem er wohl nicht so zurecht kam. Im Konsolenlog konnte ich meine Adresse auslesen. Die entsprechenden Termine habe ich gelöscht (weil alt), und dann ging es.

**Comment by Zefau** [comment]
Super!

**Comment by Zefau** [comment]
ical Adapter wird nur Initial als Quelle für die Kalender genutzt. Diese Daten liest und wertet jarvis aber selbst aus
