### ISSUE TITLE
Komischer Effekt Secondary Farbflackern beim Mouseover von SwitchAction vorgelagerter Widgets

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1351]
Bei den Secondary Werten flackert die Farbe bei Mouseover über SwitchAction vorgelagerter Widgets
![jarvis-farbFlackernMouseoverSwitchAction](https://user-images.githubusercontent.com/84818934/147276822-2faf525e-d273-4097-a37e-0245790a2f79.gif)
Bin ich der einzige?

**Comment by Zefau** [comment]
Kannst du bei den Transparenz rausnehmen? Flackert es dann auch noch?

**Comment by mcuiobroker** [comment]
Komplette CSS rausgenommen. Gleiches Problem.

**Comment by Zefau** [comment]
Browserunabhängig?

**Comment by mcuiobroker** [comment]
Probleme treten bei Chrome und Edge auf, Firefox ist ok.

**Comment by Zefau** [comment]
Versuch mal: https://www.it-swarm.com.de/de/html/weird-css3-transition-flimmern/1067345047/
> Ich habe das Flackern los. Fügen Sie «-webkit-backface-visibility: hidden;» zu den Elementen hinzu, die Sie überführen.

**Comment by mcuiobroker** [comment]
Wo rein?
![image](https://user-images.githubusercontent.com/84818934/147279623-587f2556-24b9-4af6-99b2-ac56ad108063.png)

**Comment by Zefau** [comment]
Element Style ist richtig. Aber das vom Secondary State. Also das, was flackert.

**Comment by Zefau** [comment]
Ansonsten mal googeln. Scheint ein Webkit Problrm zu sein.

**Comment by mcuiobroker** [comment]
Ja flackert dann nicht mehr, ist aber auch wesentlich dunkler bie rot.
![image](https://user-images.githubusercontent.com/84818934/147280059-0336e9b4-367f-4ab6-9719-3018bde56cdb.png)

Flackern ist auch bei den Icons.

**Comment by Zefau** [comment]
Soll ich's denn so übernehmen?

**Comment by mcuiobroker** [comment]
Ja. Dann muss halt bei Secondary das auf "fett" einstellen? Ich versuch es mal.

**Comment by Zefau** [comment]
Und wenn du alternativ mal `-webkit-transform: translate3D(0, 0, 0);` probierst?

**Comment by mcuiobroker** [comment]
Der macht das bold zunichte.
![image](https://user-images.githubusercontent.com/84818934/147281085-bc5da903-a40e-4fc5-a8bc-8063aabe7d74.png)
![image](https://user-images.githubusercontent.com/84818934/147281100-3321eb8a-64c4-4295-a8ce-bafe267864d2.png)

**Comment by Zefau** [comment]
Aber auch damit flackert es nicht mehr? Und wird auch nicht dunkler?

**Comment by mcuiobroker** [comment]
Grundeinstellung vom Programm:
![image](https://user-images.githubusercontent.com/84818934/147281408-7ebcbaaf-6dcf-4d0d-9387-23c85694f131.png)
![image](https://user-images.githubusercontent.com/84818934/147281543-65f80e7c-298f-4a2b-bbaa-0531296f6c5a.png)

Mit `-webkit-transform: translate3D(0, 0, 0);`
![image](https://user-images.githubusercontent.com/84818934/147281459-6d1662b4-8c9c-4f28-9c9e-096d749c45d9.png)

**Comment by Zefau** [comment]
Also ich würde dann `-webkit-backface-visibility: hidden;` übernehmen, aber ohne `font-weight`. Das kann jeder im Zweifel für sich machen.

**Comment by mcuiobroker** [comment]
Ja. Prima. Danke.

**Comment by Zefau** [comment]
probier nochmal bitte mit `v3.0.0-beta.21`

**Comment by mcuiobroker** [comment]
Kein Flackern mehr. Danke.

**Comment by mcuiobroker** [comment]
Hab das Flackern wieder [v3.2.0-alpha.59]

**Comment by Zefau** [comment]
Kannst du mal mit `-webkit-backface-visibility: hidden;` probieren? Alternativ sonst `backface-visibility: visible;`. Das ging damals laut https://github.com/Zefau/ioBroker.jarvis/issues/1351#issuecomment-1000539373

**Comment by mcuiobroker** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/764b2fa3-021e-4a78-a90b-45c85a77442e)
So passt es

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.1` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.1` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Flackern ist noch sichtbar

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.6` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.6` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Flackern noch da. Es geht um die Statewerte.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6f0b4a16-cbdc-4eec-b485-acddee4d45f8)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9d618f8b-e5b0-4711-aac7-a99c5ba8b598)

**Comment by Zefau** [comment]
Bei welcher Klasse kann ich das denn einfügen, damit es weg geht? Hab es aktuell bei `.jarvis-State-Value` drin.

**Comment by mcuiobroker** [comment]
Nimm mal `.jarvis-State`
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/f3b13440-f0ec-4e50-aecd-3bfcbf26522a)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.7` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.7` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
