### ISSUE TITLE
v3: Bindings für Seiten und Tabs

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#1352]
Ich würde mir wünschen, dass ich über Binding den Text, das Icon und die Iconfarbe einer SEITE ändern kann:
![image](https://user-images.githubusercontent.com/61848539/147283204-fcd5e61c-639a-4fc4-92b2-67ee2a35853e.png)

Zusätzlich würde ich mir das gleiche auf Ebene Tab wünschen.

**Comment by Zefau** [comment]
Duplikat zu https://github.com/Zefau/ioBroker.jarvis/issues/1007 ?

**Comment by uwe72** [comment]
Duplikat zu Tabs, ja. Ist in #1007 auch die Seite adressiert?

**Comment by Zefau** [comment]
Mein Verständnis ist: Ihr wollt über Binding haben ;-)

**Comment by uwe72** [comment]
:-)
Du musst zugeben, dass beim Menüpunkt "Lampen" es nicht so schlecht wäre, gleich zu erkennen, ob mindestens eine Lampen ein ist (Iconfarbe --> gelb) und eventuell noch den Namen zu ändern "Lampen (3)", wenn 3 Lampen ein sind ;-)

**Comment by Zefau** [comment]
Den Mehrwert bezweifle ich nicht ;-) Ich will nur nicht 100 Issues für dieselbe Thematik.

**Comment by uwe72** [comment]
Du möchtest ja nicht so viele "Binding" Tickets. Deshalb hänge ich dies mal noch hier hinzu. Auch Die Liste der Items im DropDown wäre mehr als nützlich wenn man diese generisch befüllen könnte:
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2231

Ich glaub Du weißt mittlerweile, dass viele User bindings als sehr wichtig ansehen. Der einzige Nachteil zu VIS im Moment. Führe gerne ein Jarvis pro PLUS Modell ein, wo man eben mehr bezahlt und solche Features noch bekommt. Ich bin bereit dafür zu bezahlen.
