### ISSUE TITLE
Horizontale Statelist funktioniert nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1354]
Es wird kurz der Gerätename nebeneinander angezeigt und danach sieht es so aus:
![image](https://user-images.githubusercontent.com/84818934/147292819-d80d223e-38be-4900-9e94-b7bb48936c76.png)
Man muss auch nebeneinander auswählen
![image](https://user-images.githubusercontent.com/84818934/147292927-002c5059-2e51-447b-b3ad-5bc00907f1ec.png)
Wofür dann zwei Optionen, da die erste (Nur horiziontal) nicht gut aussieht?
Secondary Werte müssten auch darunter sein?
![image](https://user-images.githubusercontent.com/84818934/147293079-85c53662-93e9-4811-8a1c-c25198fd64bc.png)

**Comment by Zefau** [comment]
Das sind zwei verschiedene Anzeige-Optionen. Einmal das klassische StateListHorizontal (wenn beide Optionen aktiviert sind) oder die Variante vom ersten Screenshot (wenn du eine Option aktiviert ist).

>  Secondary Werte müssten auch darunter sein?

Das sieht falsch aus und muss darunter, ja.

**Comment by Zefau** [comment]
Dass nur die erste Option nicht gut aussieht kann jeder für sich entscheiden. Ich find's nicht so schlecht:

![image](https://user-images.githubusercontent.com/14368811/147293475-82e98ac1-b0b0-44a1-842f-1935e2e75959.png)

**Comment by mcuiobroker** [comment]
Das stimmt. Kannst du es bitte zentrieren, wenn man beide Option eingeschaltet hat.

**Comment by Zefau** [comment]
>  Stellst du dann auch die Konvertierung um v2->v3?

Ist bereits angepasst.

**Comment by Zefau** [comment]
probier nochmal bitte mit `v3.0.0-beta.21`

**Comment by mcuiobroker** [comment]
Ist zentriert Danke.

**Comment by LoDDl** [comment]
Hallo,
seit dem aktuellen Update funktioniert die Statelist Horizontal wieder nicht mehr.
Es wird alles untereinander angezeigt, nicht nebeneinander.
![image](https://user-images.githubusercontent.com/52470482/147458858-4f92b679-cda8-4ca6-b093-5ccba0e74854.png)

**Comment by Zefau** [comment]
Bitte auch die config

**Comment by LoDDl** [comment]
![image](https://user-images.githubusercontent.com/52470482/147459538-a469ab3b-8265-419f-aef8-07aadbd81b33.png)
![image](https://user-images.githubusercontent.com/52470482/147459589-54705b8c-d5cb-41d5-bc15-fedd3219d34d.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-rc.1` wieder passen

**Comment by Kaskadeur111** [comment]
jetzt wollte ich gerade das selbe schreiben :-) Nun gut alles gesagt.

Wichtig wäre mir die zentrierte Darstellung je Gerät, aber Horizontal nebeneinander (quasi genau wie bei der alten Statelist Horizontal). Dann wäre ich wunschlos glücklich.
By the Way: Das Pro Abo wird sobald die Statelist Horizontal wieder läuft auch gebucht! Jarvis ist mit Abstand die sinnvollste Visu für iOBroker, vor allem ist da noch so viel Potenzial drin! Klasse und vielen vielen Dank!

**Comment by Kaskadeur111** [comment]
Bestätige, dass die Statelist als Horizontale Darstellung in rc1 jetzt funktioniert wie die StatelistHorizontal in V2 (und zusätzlich noch flexibler geworden ist!).

Eine Frage hierzu noch:

Ich habe nur das Desktop Layout aktiv -> Widget Breite 4w, Statelist Horizontal und Informationen untereinander beides aktivaktiv

Auf dem Desktop stellt er 4 Icons nebeneinander dar (auf einem drittel der Seitenbreite)
auf dem Handy stellt er 2 Icons nebeneinander dar (auf der gesamten Breite), es wäre aber optisch noch platz für ein drittes icon. Ist da noch etwas möglich, meiner Meinung nach fehlen nur wenige Pixel?

Desktop
![image](https://user-images.githubusercontent.com/28257942/147481069-b7644a60-e0d1-4b41-a559-776e00806d0c.png)

Handy
![image](https://user-images.githubusercontent.com/28257942/147481047-63446f7e-ee55-4907-b04b-adad34f4ffcb.png)

**Comment by Zefau** [comment]
Auf dem Handy ist nicht genügend Platz, sonst würde jarvis nicht in die nächste Zeile gehen. Kannst du im DOM Inspektor mal untersuchen und mit CSS die Breite justieren.
