### ISSUE TITLE
Statelist Horizontal (Option) - Anzeigen überschneiden sich

### ISSUE THREAD

**Issue by M0nk3yOo** [Zefau/ioBroker.jarvis#1355]
Spitze, ich war eben auf der Suche nach der Horizontalen Widget Anzeige und war enttäuscht dass es rausgeflogen war. Zufällig habe ich dann eben die neue Beta gesehen, und gesehen dass es nun wieder drin ist :-)

Ich habe folgenden Anzeigefehler (Überschneidungen)

<img width="1198" alt="image" src="https://user-images.githubusercontent.com/32765291/147293715-bd0f1894-3253-4a98-a433-0385381eb096.png">

Version: v3.0.0-beta.20

**Comment by Zefau** [comment]
Welche Optionen sind genau aktiviert?

So? Inkl. `Kompakter Ansicht`?

![image](https://user-images.githubusercontent.com/14368811/147296139-411a201d-8f5e-4120-b22b-4377368ac2ef.png)

**Comment by Zefau** [comment]
probier nochmal bitte mit `v3.0.0-beta.21`

**Comment by M0nk3yOo** [comment]
So ist es momentan eingestellt:
<img width="736" alt="image" src="https://user-images.githubusercontent.com/32765291/147342326-5e87855d-bfed-4182-bd2e-841ffc4b785a.png">

Ich probiere später nochmal die neue Version, muss jetzt erstmal etwas für's Fest machen.

**Comment by M0nk3yOo** [comment]
Solved!
