### ISSUE TITLE
Widget im Layout lässt sich nicht entfernen

### ISSUE THREAD

**Issue by M0nk3yOo** [Zefau/ioBroker.jarvis#1356]
Ein Widget im Layoutmenü lässt sich nicht entfernen. Klick auf den den Mülleimer bewirkt nichts.

<img width="1057" alt="image" src="https://user-images.githubusercontent.com/32765291/147294163-05a99635-9e6c-48b0-b3f6-67bef385a4b2.png">

Hier ebenfalls:
<img width="1199" alt="image" src="https://user-images.githubusercontent.com/32765291/147294151-98bf4d70-9c61-48f8-aa29-45063dc9eaa3.png">

Version: v3.0.0-beta.20 - habe ich aber auch schon unter beta 19 festgestellt

**Comment by Zefau** [comment]
@M0nk3yOo funktioniert beides bei mir. Hast du Fehler in der Browser Konsole (F12) ?

**Comment by M0nk3yOo** [comment]
Okay, hat sich scheinbar erledigt. Ich habe es gerade nochmal mit Chrome getestet und festgestellt, dass eine Bestätigungsabfrage "Wollen Sie wirklich?" kommt. Die kam gestern (Safari) nicht. Jetzt habe ich es nochmal in Safari getestet und dort kommt die Abfrage nun auch (wieder).
Komisch, aber dann hat es wohl daran gelegen.

Frohes Fest!
