### ISSUE TITLE
Tab Icon wird nicht angezeigt

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1357]
Beta21
Ist nur ein Tab auf einer Seite, wird das Icon nicht angezeigt.
![grafik](https://user-images.githubusercontent.com/13101074/147325820-24a551a2-a589-446e-9732-6f71b19d8186.png)

**Comment by Zefau** [comment]
ist so gewollt. Es gibt keine Tab Leiste, da nur ein Tab da ist.

**Comment by AFPass** [comment]
Ok. Verstehe nicht warum. Ich gebe ein Logo an, dann sollte es auch angezeigt werden. 

Wenn das Logo nicht angezeigt wird, ist die Leiste auch kleiner. Auf dem Telefon schlechter zu erreichen. (Zumindest Web
wenn das Menü unten ist. )

**Comment by Zefau** [comment]
Logo? Du meinst ein Icon?

**Comment by AFPass** [comment]
> Logo? Du meinst ein Icon?

Ja. Sorry.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.22` wird nun auch bei einem Tab die Tab-Leiste angezeigt

**Comment by Zefau** [comment]
@AFPass
