### ISSUE TITLE
Nach Update auf beta 21 startet Jarvis nicht mehr

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#1358]
beta 21

Nach einem Update auf die Beta 21 beendet sich der Adapter immer wieder.

![Bildschirmfoto 2021-12-24 um 08 16 47](https://user-images.githubusercontent.com/48379591/147328653-59d193e9-50ae-407f-9547-312198e1e522.jpg)

**Comment by stephan1827** [comment]
Habe das selbe Problem

**Comment by AFPass** [comment]
Kein generelles Problem. Bei mir läufts.

**Comment by Bernd9000** [comment]
Bei mir läufts auch, ich muß allerdings IOBroker fast immer neu starten nach einem neuen  jarvis Update sonst funktioniert es nicht.

**Comment by stephan1827** [comment]
Neu gestartet habe ich schon, kann es sein das dies Problem mit dem neuen JS controller zusammen hängt? Ich habe heute auf 3.3.22 geupdatet.

**Comment by AFPass** [comment]
Den neuen Adapter hab ich auch. Bis jetzt keine Probleme.

**Comment by Bernd9000** [comment]
Jo, hier auch alles auf dem neusten Stand:
Admin Adapter auch aktualisiert ?

Node.js    v14.18.2
NPM       v6.14.15
Admin Adapter 5.2.2
JS Controller     3.3.22

**Comment by Zefau** [comment]
Liegt sicherlich an Jarvis. Hängt mit den Änderungen bei den Geräte Übersicht zusammen

**Comment by Zefau** [comment]
mit `v3.0.0-beta.22` sollte es wieder passen

**Comment by bogaboo** [comment]
Ja, prima mit der Beta 22 läuft es wieder....

Vielen Dank und frohes Fest
