### ISSUE TITLE
HomeMatic IP Device

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1359]
> Does this help? I guess most of the states should be pretty similar to normal thermostat?
![Wandthermostat_States](https://user-images.githubusercontent.com/9281382/145545863-5edb6f8f-bcc5-4ca3-a6f7-f20ad1851419.png)

_Originally posted by @Chris0706 in https://github.com/Zefau/ioBroker.jarvis/discussions/1200#discussioncomment-1784275_

**Comment by Zefau** [comment]
@Chris0706 was für eine Geräte-ID ist das? `HmIP-STH` ?

**Comment by Zefau** [comment]
`HmIP-WTH` und `HmIP-WTH-2` werden durch den Importer bereits erkannt. Was fehlt dir hier konkret?

**Comment by Chris0706** [comment]
Habe gerade Update auf v3 gemacht und die Geräte neu suchen lassen. Wandthermostat läuft immer noch unter inkorrekte Konfiguration.
Die Geräte-ID ist aber auch HmIP-WTH-B nicht HmIP-WTH-2 wie von dir vorgeschlagen. Wahrscheinlich ist das der Fehler und du musst nur zusätzlich noch HmIP-WTH-B mappen?

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.4-beta.1`

**Comment by Chris0706** [comment]
Wird erkannt :) Danke!

Auch wenn das ganze wohl nicht mein eigentliches Problem war.

Hintergrund: Ich will mit dem Wandthermostat zwei Heizkörper ansteuern. Das funktioniert aktuell bei im RaspberryMatic über eine Gruppe der drei Geräte.
Wenn ich den SETPOINT nun über das Geräte Wandthermostat ändere, sendet die CCU nichts an die Heizkörper. Das ist anscheinend normal oder ein Bug.
Man muss den Wert in der Gruppe ändern, damit er neu an alle Gruppenmitglieder gesendet wird.
Dazu:
Neue hm-rpc Instanz anlegen und hier als Daemon 'Virtuel Devices' auswählen. Nun sollte ioBroker die Gruppen finden. Von der entsprechenden Gruppe habe ich nun die SETPOINT-ID kopiert und in Jarvis den Geräte-Datenpunkt SETPOINT des Wandthermostat auf eben die SETPOINT-ID der Gruppe aus ioBroker gemappt. Nun macht er was ich wollte :)

**Comment by Zefau** [comment]
In was umbenennen?
