### ISSUE TITLE
Datenpunkt Wert jetzt über Switchsymbol - Bug oder Feature ?

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#1361]
Beta 22

Der Datenpunktwert wird anstatt vor dem "Switchsymbol" jetzt über den  "Switchsymbol" angezeigt.

![Bildschirmfoto 2021-12-24 um 17 16 12](https://user-images.githubusercontent.com/48379591/147364497-4106fd66-af26-4ccf-bf80-a0cbad1a7543.jpg)

**Comment by Zefau** [comment]
fixed with `v3.0.0-beta.23`

**Comment by RkcCorian** [comment]
Funktioniert bei mir wieder, Anzeige ist normal
