### ISSUE TITLE
jsonTable bei einem Eintrag falsch

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1362]
Hat man nur einen Eintrag im JSON wird eine falsche Tabelle angezeigt.
```
[{"ZeitTS":1640395328746,"Zeit":"25.12.2021 02:22","Besuch":false,"Minuten":286.1}]
```
![image](https://user-images.githubusercontent.com/84818934/147375550-65ff86ee-dd8e-4653-9e22-b6ed65a8ebd7.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1314

**Comment by Zefau** [comment]
fixed with `v3.0.0-beta.23`

**Comment by mcuiobroker** [comment]
`v3.0.0-beta.24`
Überschriften passen nicht mehr zum Eintrag, sie sind verschoben?:
![image](https://user-images.githubusercontent.com/84818934/147395342-d8bd6bb3-4878-4d9a-a422-4f75bfee88b1.png)

**Comment by Zefau** [comment]
> Überschriften passen nicht mehr zum Eintrag, sie sind verschoben?: 

Du hast die Überschriften zentriert und die Werte sind aber links- bzw. rechtsbündig. Würde sagen, dass das an deiner Konfiguration liegt?

>  Lässt man alle Datensätze anzeigen fehlt die Anzahl der Datensätze.

Klingt als wäre das gewollt. Kannst du das genauer beschreiben?

Wenn die Anzahl der Datensätze kleiner ist als die Zeilen pro Seite, dann wird die Auswahl ausgeblendet, siehe https://github.com/Zefau/ioBroker.jarvis/issues/1320.

**Comment by mcuiobroker** [comment]
Die Konfig gilt doch für alle?
```
[{"label":"KW","field":"KW","align":"center"},{"label":"Tag","field":"Tag","align":"right"},{"label":"Verbrauch","field":"Verbrauch","align":"right"},{"label":"DauerHM","field":"DauerHM","align":"center"}]
```
Es werden alle angezeigt und es sind mehr als eine Seite:
![image](https://user-images.githubusercontent.com/84818934/147409653-e56a5dd6-f443-43cd-b221-9a45bf296bbe.png)

**Comment by Zefau** [comment]
Kannst du deine gesamte JsonTable Konfig screenshoten?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/147409993-6fb29a07-fefd-4516-b7e2-45e1db027f5d.png)

**Comment by Zefau** [comment]
Kannst du mal testweise deine Custom Styles via CSS löschen? Ist das dann immer noch?

**Comment by Zefau** [comment]
> Es werden alle angezeigt und es sind mehr als eine Seite:

Mehr als eine Seite? Du hast die Seiten deaktiviert (Wert `0`) ist eingetragen.

**Comment by mcuiobroker** [comment]
Komplette CSS raus, gleicher Effekt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.28`

**Comment by mcuiobroker** [comment]
Passt. Danke.
