### ISSUE TITLE
"Hakelige" Dimmleiste

### ISSUE THREAD

**Issue by MubiTec** [Zefau/ioBroker.jarvis#1364]
v3.0.0-beta.22

Hab ein Problem auf meinem Fire hd8.
Dort ist das einstellen den Helligkeit sehr "hakelig", also es funktioniert zwar irgendwie schon aber nicht jedes Mal und nicht flüssig.
Wenn ich die Dimmleiste direkt als bodylevel einstelle, also dass sie direkt sichtbar ist und nicht erst nach dem draufklicken, funktioniert es wunderbar.
Am Handy funktioniert alles wunderbar, da ist kein hakeln.
Wenn du mehr Infos brauchst sag gerne Bescheid.
Danke schon mal! 
![Screenshot_2021-12-25-07-53-47-17](https://user-images.githubusercontent.com/44448393/147379392-8f6be9d9-dcc3-424d-9afa-15736d4f1f76.jpg)

**Comment by Zefau** [comment]
@MubiTec besteht das Problem mit v3.1 noch?
