### ISSUE TITLE
DateTime: Sonnenzeiten laden lange

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1365]
> Ansonsten brauchen im Date / Time Widget die Sonnenzeiten weiterhin Ladezeit. Ich glaube schwankend, mal schneller, mal langsamer, aber gefühlt zu lang.

_Originally posted by @mh-hdl in https://github.com/Zefau/ioBroker.jarvis/issues/1207#issuecomment-1001041684_

**Comment by Zefau** [comment]
@mh-hdl @RkcCorian schaut bitte nochmal mit `v3.0.0-beta.24`

**Comment by RkcCorian** [comment]
Daten sind sofort da, was gut ist. Leider kommt folgender Bildschirm nach wenigen Sekunden, vermutlich im weiteren Ladeverlauf. Docker-Container > ioBroker wurde schon komplett neu gestartet

![image](https://user-images.githubusercontent.com/79741077/147393170-a599e9cd-f924-4c13-a314-056c2c855100.png)

**Comment by Zefau** [comment]
Sollte jetzt wieder gehen

**Comment by RkcCorian** [comment]
> Sollte jetzt wieder gehen

MIt welcher Version? Sehe noch ```beta-24```

**Comment by Zefau** [comment]
Sollte ohne Update wieder passen?

**Comment by RkcCorian** [comment]
> Sollte ohne Update wieder passen?

Ok, wie?
Bin auf dem Weg :-)

**Comment by RkcCorian** [comment]
Ja, geht.
Was hast Du geändert, was lokal einen Effekt hat?

**Comment by Zefau** [comment]
Ist eine Abfrage der Version im Github Repo, um lokal anzuzeigen, dass es ein Update gibt. Ist aber nicht final implementiert.
