### ISSUE TITLE
Secondary Werte auseinander gezogen?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1367]
`v3.0.0-alpha.23`
Die Secondary-Werte sind jetzt wesentliche weiter auseinander gezogen:
Leerzeichen davor gesetzt?
![image](https://user-images.githubusercontent.com/84818934/147392906-3bdb0153-4cbe-47bc-baeb-c02bbe786cc6.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-beta.24`

**Comment by mcuiobroker** [comment]
Passt wieder. Danke.
