### ISSUE TITLE
Es werden immer alle jarvis Objekte gesichert, nicht nur geänderte

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1368]
`v3.0.0-beta.23`
Klickt man auf Speichern & Zurück werden immer alle jarvis Objekte gespeichert. Eigentlich sollen nur die zusätzlich gespeichert werden, die sich geändert haben?
Ich habe kein Eintrag geändert, nur `Speichern & Zurück` geklickt.
Oder ist nur das Log falsch?
![image](https://user-images.githubusercontent.com/84818934/147393019-2f55ad4d-00c7-401d-83db-553a89f93cd8.png)

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.0.0-beta.25`

**Comment by mcuiobroker** [comment]
Sieht gut aus. Danke.
