### ISSUE TITLE
v3: Sporadisch wird Binding ignoriert für Formatierung

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1369]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

beta-24

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.

Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
Sporadisch wird Binding ignoriert für Formatierung. Meistens nach F5, unklar ist, wann es etwas später wieder geht. Ob es einfach "nur" Zeit braucht länger zu laden oder was auch immer bewirkt. Zumindest hilft Warten von ca. 1 Minute. Es betrifft auch gar nicht alle DPs, nur der markierte zeigt dieses Verhalten bei mir.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

Normal
![image](https://user-images.githubusercontent.com/79741077/147393786-c9d1f4c8-540b-47e9-b707-ac5ca95259a2.png)

Fehler
![image](https://user-images.githubusercontent.com/79741077/147393796-76f97aec-53a3-4ff7-832e-587bb1a5cea1.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
Verhalten gleich auf Surface und Handy

**Comment by RkcCorian** [comment]
Leider auch an anderer Stelle geht es nicht mehr...
![image](https://user-images.githubusercontent.com/79741077/147393906-3ab11fcc-8f9b-4d42-87ec-a4e163ab4b98.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1345
