### ISSUE TITLE
Nach Aktualisierung auf neue jarvis-Version - Frontends werden nicht aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1370]
Unabhängig von der Version:
Nach einem Versions-Update und automatischem Neustart vom Adapter bzw Instanz, werden die Frontend-Seiten nicht aktualisiert.
Geht man direkt nach dem Update mit F2 in die Konfig, so ist noch die alte Version vorhanden.
Eigentlich sollten sich die Seiten (verbundene Browser) doch nach Neustart von der Instanz neu laden?

**Comment by Zefau** [comment]
Nein. Es findet bisher kein refresh der Seite statt. Mit der nächsten beta gibt es einen Versionsvergleich. Wenn die Version unterschiedlich sind, gibt es einen Reload.

**Comment by Zefau** [comment]
mit `v3.0.0-beta.27` nun eingeführt. Funktioniert dann aber erst ab dem nächsten Update.

**Comment by mcuiobroker** [comment]
Reload wird sogar angekündigt. Sehr schön.
