### ISSUE TITLE
Nach Update auf Beta 25 : Error: Verification failed (App blocked)

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#1371]
Nach dem Update auf die Beta 25 startet Jarvis nicht mehr.

Es wird ganz kurz die erste Seite angezeigt, "Pro User Info" erscheint und dann kommt der rote Bildschirm mit
dem Fehler: Error: Verification failed (App blocked)

**Comment by Algieio** [comment]
Ist bei mir auch so.

**Comment by stglei** [comment]
bei  mir auch das gleiche Verhalten

**Comment by disaster123** [comment]
+1 - das gleiche

**Comment by disaster123** [comment]
Noch ein Hinweis - selbst mit gültigem Pro Abo kommt der Fehler. Bin zurück auf Beta24

**Comment by RkcCorian** [comment]
Siehe ebenfalls #1345

**Comment by Zefau** [comment]
`3.0.0-beta.26`

**Comment by RkcCorian** [comment]
Fehler ist weg

**Comment by disaster123** [comment]
funktioniert

**Comment by benny000004** [comment]
In 3.0.2. derselbe Fehler (auch ein Downgrade auf 3.0.0 löst das Problem nicht).

**Comment by RkcCorian** [comment]
Bei mir läuft es im Docker, hatte auch erst das Problem. Musste einmal neu starten, dann ging es.

**Comment by benny000004** [comment]
Tatsache, Neustart des Servers hat geholfen... Interessant. Danke!
