### ISSUE TITLE
Statt Gerätelabel wird nun Gerätename angezeigt

### ISSUE THREAD

**Issue by disaster123** [Zefau/ioBroker.jarvis#1374]
Bis zur BetaXX glaube 10 oder so wurde das Geräte Label in einer Statelist als Name angezeigt. Nun wird der Gerätename angezeigt und nicht mehr das Label.

**Comment by Zefau** [comment]
Duplikat, siehe https://github.com/Zefau/ioBroker.jarvis/issues/1347

----

Kannst du das mal screenshoten? Ich kann das nicht nachstellen.
