### ISSUE TITLE
series-Einstellungen in HistoryGraph einfügen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1377]
HistoryGraph
series-Einstellungen für den HistoryGraph einstellbar, wie x-Achse und y-Achse.
https://echarts.apache.org/en/option.html#series

Evtl die komplette "setOption" als Variante zum HistoryGraph -> eChart

**Comment by Zefau** [comment]
- [ ] Callback to change data of series

**Comment by Zefau** [comment]
implemented with `v3.1.0-alpha.26`

**Comment by mcuiobroker** [comment]
Die series Einstellungen greifen anscheinend nur beim hover?
![image](https://user-images.githubusercontent.com/84818934/181619246-ccacc132-9298-4094-b40d-6ae034256e05.png)
Beispiele

```
{  "symbol": "rect",  "symbolSize": 9,  "label":{    "show": true  }}
```

``` 
{
  "symbol": "rect",
  "symbolSize": 9,
  "label": {
    "show": false
  },
  "showAllSymbol": true,
  "colorBy":"data"
}
``` 
Normale Anzeige:
![image](https://user-images.githubusercontent.com/84818934/181619966-e1be7e59-dbe9-4205-90ab-6bea5fe09cda.png)


Callback zieht
```(val) => val /10 ```
Temperaturen werden durch 10 geteilt angezeigt. Dafür werden die Temperaturen ohne "°C! angezeigt.
Laut y-Achsen Einstellung -> ` "formatter": "{value} °C",`
![image](https://user-images.githubusercontent.com/84818934/181620182-f1b58723-22a3-4ffd-84e2-e66834473486.png)

```
[
  {
    "position": "left",
    "name": "Bad",
    "nameLocation": "center",
    "nameGap": 70,
    "offset": -5,
    "padding": 10,
    "min": "dataMin",
    "max": "dataMax",
    "axisPointer": {
      "show": true
    },
    "splitLine": {
      "show": true,
      "lineStyle": {
        "color": "rgba(193, 22, 22, 1)",
        "type": "dotted"
      }
    },
    "axisLabel": {
      "formatter": "{value} °C",
      "margin": 25,
      "showMaxLabel": false,
      "showMinLabel": true,
      "color": "rgba(255, 255, 255, 1)"
    }
  },
  {
    "position": "right",
    "name": "Büro",
    "nameLocation": "center",
    "nameGap": 70,
    "offset": 0,
    "padding": 10,
    "min": "dataMin",
    "max": "dataMax",
    "axisLabel": {
      "formatter": "{value} °C",
      "margin": 25
    }
  }
]
```

**Comment by Zefau** [comment]
> Die series Einstellungen greifen anscheinend nur beim hover?

Ist das noch aktuell? Bei mir zeigt er es mit alpha-50 ohne hover komplett an.

>  Temperaturen werden durch 10 geteilt angezeigt. Dafür werden die Temperaturen ohne "°C! angezeigt.

Ist das noch aktuell? Wo fehlt dir die Anzeige der Einheit?

**Comment by mcuiobroker** [comment]
`v3.1.0-alpha.50 `
Ist noch aktuell. Ja.

- [ ] Rechts müsste °C stehen wird aber nicht angezeigt.
- [ ] Namen werden weder links noch rechts angezeigt

![image](https://user-images.githubusercontent.com/84818934/193353333-c151e940-bbf0-4112-8ebc-d513ad35cd0c.png)

Series Einstellung prüfe ich noch.

**Comment by mcuiobroker** [comment]
Series-Einstellungen
```
{  "symbol": "rect",  "symbolSize": 20,  "label": {    "show": false  },  "showAllSymbol": true,  "colorBy": "data"}
```
Die Symbole werden bei mir nur beim hover angezeigt.
hover-Bild:
![image](https://user-images.githubusercontent.com/84818934/193354912-8f6930e1-e9cd-40ed-95f2-642bc223736a.png)

**Comment by Zefau** [comment]
>  Rechts müsste °C stehen wird aber nicht angezeigt.

Ist mit dem nächsten Release behoben

>  Namen werden weder links noch rechts angezeigt

Spiel mal mit deinen Werten rum, insbesondere:
```
    "nameGap": 70,
    "offset": -5,
    "padding": 10,
```

Label wird korrekt angezeigt, wenn du alles raus löscht. Aufgrund der Werte verschiebt es sich außerhalb des Views.

**Comment by Zefau** [comment]
Bei mir geht es auch ohne Hover inkl. der ganzen Konfiguration, die du gepostet hast:

**Comment by mcuiobroker** [comment]
Nehme ich die drei Wert raus, sieht es so aus:
![image](https://user-images.githubusercontent.com/84818934/193355430-4dbd8a48-15b0-4f1b-9efd-dcdfc01b3d48.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/193355541-7a2a4edd-0b29-42a8-a11a-acfa7992a8c2.png)

**Comment by Zefau** [comment]
Du hast die Option "Markierungen / Symbole in Chart-Linie anzegen" (`showSymbol`) aus und auch nicht selbst in deiner Konfiguration definiert (siehe https://echarts.apache.org/en/option.html#series-line.showSymbol):
```
{
  "showSymbol": true,
  "symbol": "rect",
  "symbolSize": 9,
  "label": {
    "show": false
  },
  "showAllSymbol": true,
  "colorBy":"data"
}
```
statt
```
{
  "symbol": "rect",
  "symbolSize": 9,
  "label": {
    "show": false
  },
  "showAllSymbol": true,
  "colorBy":"data"
}
```

**Comment by mcuiobroker** [comment]
Jo das war es.
![image](https://user-images.githubusercontent.com/84818934/193356693-5acb6a6d-e1d0-4859-a6e5-0fb4048331ba.png)
Dann können wir schließen, da der Rest mit dem Update kommt?

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by mcuiobroker** [comment]
Passt. Danke.
