### ISSUE TITLE
MAP Änderungen erst nach F5 wirksam

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1378]
MAP
Änderungen in den Einstellungen sind erst nach F5 wirksam.
Vorher werden auch die Icon zu den eingetragenen Positionen Markers nicht angezeigt.
![image](https://user-images.githubusercontent.com/84818934/147415375-3073a28e-aef8-45f6-bb5a-81ad72d24944.png)
Das gleiche Verhalten ist so, wenn man aus der Konfig direkt "abbrechen" klickt.
War die font-weight nicht vorher mal "bold"?
![image](https://user-images.githubusercontent.com/84818934/147415802-6579531f-b1a7-4b91-871c-6cf021f694e0.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.28`

**Comment by mcuiobroker** [comment]
Die Änderungen weden jetzt wirksam, aber jetzt kann man nicht mehr zu den Marker-Positionen springen. 
Es wird beim Klick nichts mehr geändert.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-rc.1` wieder passen

**Comment by mcuiobroker** [comment]
Passt. Danke.
