### ISSUE TITLE
Mobile App: Android

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#138]
https://cordova.apache.org/#getstarted

**Comment by braindead1** [comment]
This would be awesome together with the possibility to connect to jarvis via the internet.

**Comment by TZanke** [comment]
This sounds like a lot of work. Jarvis is running on mobile browsers and i think this is the best solution.
On my Samsung S10 i put a icon on my Homescreen, which opens the Website as a fullscreen App. Done.

https://phandroid.com/2021/01/05/how-to-add-a-website-shortcut-to-your-android-home-screen/

So the only missing part is the connection from outside the house. But i think this isn't the problem of Jarvis. If you like to access you smart-home from remote, you will use a VPN anyway. Maybe you own a FritzBox ? Problem also solved in seconds.

**Comment by Zefau** [comment]
Android-App released: https://github.com/Zefau/ioBroker.jarvis/releases/tag/v3.1.3-beta.9

**Comment by mcuiobroker** [comment]
Start-Bildschirm bei v3.1.3-beta.9
Hoch und Quer Fehler bei Connect
![image](https://user-images.githubusercontent.com/84818934/214711852-94a186a3-7b53-4b6a-b321-d0640ac21d4a.png)
Quer
![image](https://user-images.githubusercontent.com/84818934/214711915-408a4d50-b5ad-4e41-ae10-6bda057fe90d.png)

**Comment by mcuiobroker** [comment]
Läuft auf Android 9 nicht?
![image](https://user-images.githubusercontent.com/84818934/214718648-d833250e-2b85-4b08-b487-8de9d8d69de6.png)

**Comment by TZanke** [comment]
@mcuiobroker Das Layout Problem habe ich auf meinem Samsung S10 auch.

Außerdem hat es mir nachdem ich mit der App Jarvis einmalig angesehen habe die Widgets zerhauen. Meine Layouts im Jarvis hatten plötzlich alle keine Widgets mehr.
![image](https://user-images.githubusercontent.com/1613368/214801761-64a9a5e4-dd1e-4eae-b98b-7350a83c3f70.png)

Siehe: https://github.com/Zefau/ioBroker.jarvis/issues/2191
Scheinbar ist der Bug auch in der Version [v3.1.3-beta.9](https://github.com/Zefau/ioBroker.jarvis/releases/tag/v3.1.3-beta.9) die du gestern veröffentlicht hast.

Restore über BackIt-Up und Jarvis Restore hat aber geklappt.

**Comment by mcuiobroker** [comment]
Hast du erst den Server upgedatet mit v3.1.3-beta.9? Und erst dann die App installiert  und gestartet?

**Comment by TZanke** [comment]
@mcuiobroker Hätte man das tun sollen? Die hat irgendeinen Version-Mismatch angezeigt und in dem Moment waren aber auch schon die Widgets hinweg. Scheinbar ist die App nicht nur ein Browser-Viewer. Wenns so gefährlich ist, halt ich mich lieber wieder raus. Hatte gestern Abend halt eine Mail für das Release bekommen und aufm Sofa nebenbei installiert. Jetzt hatten wir im Freundeskreis halt Spaß alle unsere Jarvis Installationen zu restoren :). Aber jetzt wissen wir wie es geht.

PS: Unter dem Loginscreen ist so viel Platz, da könnte doch während der Beta eine rote Warnmeldung für Leute auf dem Sofa stehen....was man beachten muss.

**Comment by mcuiobroker** [comment]
Sorry für die Unannehmlichkeiten. Bei mir trat der Fehler nicht mehr und @zefau meinte ich habe es gefixed. 
Vielleicht kann er ja noch ein Zusatz-Hinweis angeben, bevor man sich einloggt.
P.S. Veröffentlichen kann nur einer -> @zefau.

**Comment by Bernd9000** [comment]
Mobil App v3.1.3-beta.9
Bei mir sind auch die widgets weg, hatte noch die 3.1.2 drauf.
Ich wußte leider nicht das man vorher jarvis in ioBroker aktualisieren sollte.

**Comment by mcuiobroker** [comment]
@Bernd9000 Erstmal abwarten, Zefau sucht noch den Fehler.

**Comment by Zefau** [comment]
> Ich dachte es wäre behoben. Ein Update des Servers vor der App ist in diesem Fall nicht nötig und auch sonst nur in Ausnahmefällen. Es hätte also nicht passieren dürfen.

Sollte nun mit beta-11 behoben sein.

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.13`
wird in der App trotzdem als v3.1.3-beta.11 angezeigt. Sehr wahrscheinlich ist in der --jarvis-version Variable die Andoird-App-Version und nicht die geladene Web-Version?
Es wird bei Verbdinungsverlust auf der App ein Mismatch angezeigt und dadurch neu geladen. Angzeigt wird aber wieder die Version v3.1.3-beta.11 während der Startphase.

Vielleicht sollte man für die App andere Variablen verwenden?
--jarvis-android
--jarvis-windows
Die können ja mal auseinander laufen, so weiß man dann welche Version man hat.

**Comment by Zefau** [comment]
Jetzt mischt du den Windows- und Android-Thread etwas. Leere mal den Cache auf Android (via Einstellungen) bzw. Windows (via `C:\Users\%username%\AppData\Roaming\jarvis`) und schau, ob es dann geht?

**Comment by mcuiobroker** [comment]
Bzgl Android v9 habe ich den Cache gelöscht und trotzdem erscheint wie weißer Bildschirm.

**Comment by Zefau** [comment]
Notiz für mich: `Android 9 (API level 28)`, https://developer.android.com/studio/releases/platforms

**Comment by mcuiobroker** [comment]
Welchen API Level hast du bislang genutzt?

**Comment by Zefau** [comment]
Mit Cordova. Bisher habe ich nichts explizit angegeben, also vermute ich, dass irgendein default greift. Weiß ich aber nicht. Aber ich stell es auf API-Level 28.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/215338839-5bc5c0ea-18a6-4b65-bdf6-05ae6595cab1.png)

**Comment by mcuiobroker** [comment]
Es gibt es bei einem Tablet (android 11) mit App (jarvis) und Fully Kiosk Browser einen besonderen Effekt.
Dort wird in den clients kein Unterschied festgestellt. (nutzen anscheinend die gleiche Grundlage?)
-> nur ein Eintrag in den clients.
![image](https://user-images.githubusercontent.com/84818934/215343077-20c62d24-e10e-4933-9acb-33fe3eac2d6d.png)

**Comment by mcuiobroker** [comment]
Evtl. wichtige Option für Tablets
Bildschirm-Timeout einstellbar?

**Comment by Zefau** [comment]
> Wenn man da rangeht, evtl. auch Infos vom System (battery, brightness, wlan, usw.) mit in die client-Infos nehmen als JSON?

Jo, eins nach dem anderen. Mit der "nativen" Android-App gibt es nun unzählige Möglichkeiten. Auch hinsichtlich Notifications.

**Comment by RkcCorian** [comment]
Kann mit der beta.11 leider nicht verbinden. Mir fällt auf, dass in der Fehlermeldung die IP nicht übernommen wurde.
![Screenshot_20230129_222504_jarvis](https://user-images.githubusercontent.com/79741077/215356542-dd191b07-c4a1-4fa5-afe0-c0ded65ab91c.jpg)

**Comment by Zefau** [comment]
Verbinde mal bitte auf den jarvis-socket-port, also `8400` für Instanz 0, `8401` für Instanz 1, etc.

**Comment by RkcCorian** [comment]
Hat geklappt. Hab tlw. in VIS Navigationslinks. Leider bleibt die App nicht "in sich selbst", sondern geht über den Browser, also aus der App raus

**Comment by Zefau** [comment]
Jo, ist auch kein Browser.

**Comment by RkcCorian** [comment]
Hintergrund: ich hab ein paar VIS als iFrames in JARVIS drin, bspw. mit nem Grundriss, und wenn ich auf ein Zimmer klicke wird eine URL von JARVIS angesprungen. Im Fully gibt es die Möglichkeit URLs in Fully selber zu behandeln, sodass Fully die URL im gleichen Fenster öffnet. Sowas bräuchte zumindest ich auch in der App, ansonsten funktioniert mein Navigationskonzept tlw. nicht mehr. Solange JARVIS nicht auch VIS komplett beinhaltet wäre ein solche Feature vermutlich auch für andere interessant.
Zumindest ich kann ansonsten nicht vollständig wechseln, was ich aber natürlich lieben gerne würde 🙃

**Comment by Zefau** [comment]
Also die Ziel-URL hat denselben Host, richtig?

**Comment by RkcCorian** [comment]
> Also die Ziel-URL hat denselben Host, richtig?

Ja, genau. Ich befinde mich in JARVIS, dort ist über iFrame eine VIS drin. Diese hat für ein paar Objekte einen Link auf einen der JARVIS-Tabs. Damit navigiere ich von JARVIS nach JARVIS, nur zu einem anderen Tab.

**Comment by hosabeni** [comment]
Die Version `v3.1.3-beta.16` der App verbindet sich nicht. 
Der Server ist auch auf der Version,

![Image](https://user-images.githubusercontent.com/77939385/216147870-57941814-e69e-4b12-95a1-8190995761c7.png)

**Comment by Zefau** [comment]
@hosabeni schau nochmal mit `v3.1.3-beta.17`

**Comment by hosabeni** [comment]
Mit der `v3.1.3-beta.17` geht es bei mir

**Comment by hosabeni** [comment]
Ich hab Android 11 mit WebView 109 und App Working --> YES.

**Comment by mcuiobroker** [comment]
Android 13 Level 36 -> läuft.

**Comment by Zefau** [comment]
Android API Level 36 gibt es nicht, siehe https://source.android.com/docs/setup/about/build-numbers. Du meinst wahrscheinlich die KNOX-API, die von Samsung ist.

**Comment by mcuiobroker** [comment]
Ja bei mir steht immer KNO API level xx.
