### ISSUE TITLE
v3: Notification Bar flickers when scrolling is needed

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1380]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
```beta-28```

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Notification Bar flickers when scrolling is needed

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![Notification](https://user-images.githubusercontent.com/79741077/147424186-3a47d6d7-9ff7-4957-a851-e2066e8bff92.gif)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
@Zefau: Moin Zefau, hab 2 Fragen 🙈
- Sicher, kannst Du das erst in der v3.1.x lösen willst? Ist schon ne blöde Sache, so sind Notifications unbrauchbar, sobald ein Scrollbalken auftaucht und der taucht bereits ab 8 Notifications auf, obwohl der Bildschirm viel mehr her gibt...
![image](https://user-images.githubusercontent.com/79741077/147540402-e4daecc0-a809-4a41-8ad0-771d19dc6df1.png)

- Weißt Du schon welche Projektsicht Du für die v3.1.x nutzen wirst? Ich sehe jetzt 2 Projekte 🙃

Weiterhin gutes Gelingen!

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.1`

**Comment by RkcCorian** [comment]
```v3.0.1```
- BlindLevelAction hat keinen STOP Button mehr
 
<img width="1308" alt="image" src="https://user-images.githubusercontent.com/79741077/147604338-c080d37f-2914-4be8-b875-15f859b6e417.png">

- Es werden keine Notifications mehr angezeigt
<img width="582" alt="image" src="https://user-images.githubusercontent.com/79741077/147604368-8fc490f8-d6ea-4478-bca3-5e84a57d7ac2.png">

**Comment by Zefau** [comment]
Am BlindLevelAction hab ich gar nichts gedreht von 3.0.0 auf 3.0.1 :-\

Hast du da eine Aktivität ausgewählt und hat der Datenpunkt einen korrekten Wert? Hast du Fehler in der Browser-Konsole (F12)?

**Comment by Zefau** [comment]
installier' die mal bitte die aktuelle v3.0.1 vom Github neu (neue Variante, gleiche Versionsnummer)

**Comment by RkcCorian** [comment]
Mit der neuen ```v3.0.1``` sehe ich die Benachrichtigungen wieder und ich kann durch die Liste Scrollen ohne Probleme.
Allerdings funktioniert das CSS für die Symbole in der Benachrichtigungszentrale nicht mehr. Ich bin mir nun aber nicht mehr sicher ab wann das nicht mehr geht.

Der Fehler mit dem Rollladenstop bleibt. Hab da auch nichts geändert, sondern "nur" die neue Version installiert.
<img width="748" alt="image" src="https://user-images.githubusercontent.com/79741077/147613273-207f756a-143e-4afd-8c8d-2ed9d422f200.png">

Sehr doof außerdem und kritisch... mit F2 bin ich "nur" in der Geräte-Konfig. Die anderen Bereiche sind nicht mehr zugänglich / sichtbar.
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/79741077/147613476-1568c3cc-d572-4f05-8c31-3593fcc38214.png">

**Comment by RkcCorian** [comment]
Wenn ich F2 drücke kommt folgender Fehler in der Konsole...
<img width="1920" alt="image" src="https://user-images.githubusercontent.com/79741077/147613720-05027dcc-9552-4136-a538-eb2b91b11298.png">

**Comment by Zefau** [comment]
>  Allerdings funktioniert das CSS für die Symbole (Benachrichtigungszentrale & Benachrichtigung) nicht mehr. Ich bin mir nun aber nicht mehr sicher ab wann das nicht mehr geht.

Was meinst du damit genau?

**Comment by Zefau** [comment]
> Der Fehler mit dem Rollladenstop bleibt. Hab da auch nichts geändert, sondern "nur" die neue Version installiert.

Die Konfiguration ist falsch. Siehe https://github.com/Zefau/ioBroker.jarvis/issues/1093#issuecomment-1000556635
Da gab es eine Änderung mit rc.1.

**Comment by RkcCorian** [comment]
> > Allerdings funktioniert das CSS für die Symbole (Benachrichtigungszentrale & Benachrichtigung) nicht mehr. Ich bin mir nun aber nicht mehr sicher ab wann das nicht mehr geht.
> 
> Was meinst du damit genau?

Ich habe über CSS eine Farbe vorgegeben...
```
.jarvis-notification-event-popup-title .jarvis-icon svg {
	/* Icon-Farbe Benachrichtigung (Default, wenn nicht überschrieben) */
	color: #ffffff !important;
}
```
und
```
.jarvis-notifications-item.notificationInfo .iconify {
	/* Icon - Farbe Benachrichtigungszentrale */
	color: #0099FF !important;
}
```

**Comment by RkcCorian** [comment]
> > Der Fehler mit dem Rollladenstop bleibt. Hab da auch nichts geändert, sondern "nur" die neue Version installiert.
> 
> Deine Konfiguration ist falsch. Siehe [#1093 (comment)](https://github.com/Zefau/ioBroker.jarvis/issues/1093#issuecomment-1000556635) Da gab es eine Änderung mit rc.1.

??? Auch mit Lesen von #1093 finde ich keinen Fehler. Mit ```beta-28``` auch kein Problem. Was wäre "falsch", sprich was wurde geändert?

**Comment by Zefau** [comment]
hm, da hatte ich auch etwas in der beta geändert: Die Material Design Icons laufen nicht mehr über Iconify, sondern sind lokal (für die Performance, damit diese schneller geladen werden). 

Daher sind es aber auch keine `svg`'s mehr bzw. trifft die CSS-Klasse `.iconify` nicht mehr zu.

Versuch mal bitte:
```
.jarvis-notification-event-popup-title .jarvis-icon .q-icon,
.jarvis-notification-event-popup-title .jarvis-icon svg {
	/* Icon-Farbe Benachrichtigung (Default, wenn nicht überschrieben) */
	color: #ffffff !important;
}
```
und
```
.jarvis-notifications-item.notificationInfo .q-icon,
.jarvis-notifications-item.notificationInfo .iconify {
	/* Icon - Farbe Benachrichtigungszentrale */
	color: #0099FF !important;
}
```

**Comment by Zefau** [comment]
> ??? Auch mit Lesen von #1093 finde ich keinen Fehler. Mit beta-28 und allen vorhergehenen alpha-versionen auch kein Problem. Was wäre "falsch", sprich was wurde geändert?

Du hast sowohl für Aktivität als auch für Stop `LEVEL` als Datenpunkt gewählt, aber `activity` muss ein Boolean sein.

**Comment by RkcCorian** [comment]
> > ??? Auch mit Lesen von #1093 finde ich keinen Fehler. Mit beta-28 und allen vorhergehenen alpha-versionen auch kein Problem. Was wäre "falsch", sprich was wurde geändert?
> 
> Du hast sowohl für Aktivität als auch für Stop `LEVEL` als Datenpunkt gewählt, aber `activity` muss ein Boolean sein.
> 

Hmm... dann muss ich erstmal schauen wie ich die Info bekomme... Bislang war die nicht notwendig... D.h. STOP erscheint nur bei Aktivität?! Was wäre wenn ich den konstant auf true setzte? Dann habe ich das Verhalten wie vorher?

**Comment by Zefau** [comment]
installiere dir nochmal die aktuelle v3.0.1 von Github, dann sind die anderen Fehler weg

**Comment by Zefau** [comment]
> D.h. STOP erscheint nur bei Aktivität?! Was wäre wenn ich den konstant auf true setzte? Dann habe ich das Verhalten wie vorher?

Ja. Wenn `false` ist der Button ausgegraut, wenn `true` ist er rot.

**Comment by RkcCorian** [comment]
Hab's gerade ausprobiert, mit dem Ergebnis...
- Icons bei Notifications sind jetzt > OK
- Konfiguration ist wieder zugänglich > OK
- Wenn ich in die Konfig gehe kommt folgende Fehler > NOK
![image](https://user-images.githubusercontent.com/79741077/147654482-fc98207a-465b-4824-a31b-e31db2ad71d5.png)
- Hab ACTIVITY erstellt, allerdings trotzdem keinen STOP Button > NOK
```
  "balkonrollladenlinks_281b0": {
    "name": "Balkonrollladen Links",
    "icon": "mdi:window-shutter",
    "label": "",
    "function": "blind",
    "states": {
      "STATUS": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Links.STATUS",
        "display": {
          "0": "Benutzer",
          "1": "Aussperrschutz",
          "2": "Lüften",
          "3": "Sonnenuntergang",
          "4": "Beschattung",
          "5": "Anwesenheitssimulation",
          "6": "Sonnenaufgang"
        },
        "icon": {
          "0": "mdi:account",
          "1": "mdi:lock-off-outline",
          "2": "mdi:tailwind",
          "3": "mdi:weather-sunset-down",
          "4": "mdi:shield-sun",
          "5": "mdi:human-greeting-proximity",
          "6": "mdi:weather-sunset-up"
        },
        "label": "Betriebsmodus",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "STATUS",
        "actionElement": null
      },
      "LEVEL": {
        "showState": false,
        "state": "0_userdata.0.Wohnzimmer.Balkonrollladen_Links.level",
        "action": "alias.0.Wohnzimmer.Balkonrollladen_Links.BLIND_COMMAND",
        "display": {
          "0": "Oben",
          "100": "Unten"
        },
        "icon": {
          "100": "mdi:window-shutter",
          "<100": "mdi:window-shutter-open"
        },
        "actionElement": "BlindLevelAction",
        "hide": false,
        "iconStyle": {
          "100": {
            "color": "#aaaaaa"
          }
        },
        "label": "Level",
        "properties": {
          "max": 0,
          "min": 100
        },
        "bodyElement": "LevelBody",
        "stateKey": "LEVEL",
        "BlindLevelActionConfig": {
          "activityState": "ACTIVITY",
          "stopAction": "LEVEL"
        },
        "unit": {
          "0": "",
          "100": "",
          "default": " %"
        }
      },
      "ACTIVITY": {
        "stateKey": "ACTIVITY",
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Links.ACTIVITY",
        "hide": true
      },
      "AZIMUTH": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Links.AZIMUTH",
        "unit": "°",
        "icon": "mdi:axis-z-rotate-clockwise",
        "label": "Rollladenausrichtung",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "AZIMUTH",
        "actionElement": null
      },
      "AZIMUTH_RANGE_SHIELD_SUN": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Links.AZIMUTH_RANGE_SHIELD_SUN",
        "unit": "°",
        "icon": "mdi:angle-acute",
        "label": "Beschattungsbereich (+/-)",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "AZIMUTH_RANGE_SHIELD_SUN",
        "actionElement": null
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Alias Devices",
        "namespace": "alias"
      },
      "_created": 1613160982790,
      "_updated": 1623909310417
    },
    "id": "balkonrollladenlinks_281b0",
    "revision": "09d14"
  },
```
- FRAGE: Wie kann man über CSS die Farbe des STOP-Buttons anpassen, bei ACTIVITY = false (= true funktioniert weiterhin mit der beta)?

**Comment by Zefau** [comment]
> Wenn ich in die Konfig gehe kommt folgende Fehler > NOK

Was ist da falsch? Sieht alles gut aus. Der Fehler im Log ist von Sentry und kann ignoriert werden.

**Comment by RkcCorian** [comment]
> > Wenn ich in die Konfig gehe kommt folgende Fehler > NOK
> 
> Was ist da falsch? Sieht alles gut aus. Der Fehler im Log ist von Sentry und kann ignoriert werden.

OK

**Comment by RkcCorian** [comment]
Was ist mit dem fehlenden STOP Button und meiner Frage bzgl. CSS für ACTIVITY = false? Hast Du da eine Idee?

**Comment by Zefau** [comment]
Lass das bitte in https://github.com/Zefau/ioBroker.jarvis/issues/1093 diskutieren, da hier off-topic

**Comment by RkcCorian** [comment]
ok
