### ISSUE TITLE
1. TAB auf Seite X ausblenden -> Kein Zugriff auf die Seite über Menü

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1385]
Blendet man den ersten TAB auf der Seite aus mit:
```
[href="#/home0"] {
	display: none !important;
}
```
Hat man im Menü keinen Zugriff mehr auf die Seite
![image](https://user-images.githubusercontent.com/84818934/147484592-c056e205-fc8d-41e7-90c4-3d23ab0728ca.png)
Normalerweise sieht es so aus:
![image](https://user-images.githubusercontent.com/84818934/147484668-732332d7-ed8d-4ac4-97f6-9c73b520e1f1.png)

**Comment by Zefau** [comment]
Für eigene Styles kann ich keine Gewährleistung geben.

Ändere den Style ab und packe `.jarvis-tabs` davor oder so?
