### ISSUE TITLE
Label in Widget falsch

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1389]
Ich habe ein Gerät.
![grafik](https://user-images.githubusercontent.com/13101074/147542129-0f9b136f-fc5e-4481-a595-04cdf07be2e9.png)

Das einem Widget zugeordnet ist.
![grafik](https://user-images.githubusercontent.com/13101074/147542204-be29d595-3c5d-477c-85cf-e3ab81503102.png)

Im Widget ist angegeben, dass das Label für das Gerät "Gerät 1" sein soll.

Angezeigt wird aber
![grafik](https://user-images.githubusercontent.com/13101074/147542285-e8e297d9-9857-43fe-8aa3-d205163df51e.png)

**Comment by Zefau** [comment]
Da kam es zu einem Fehler mit dem Datenpunkt, daher das gelbe Dreieck mit Ausrufezeichen. Welchen Fehler erhältst du in der Browser Konsole (F12)?

**Comment by AFPass** [comment]
Es geht nicht um das gelbe Ausrufezeichen. Auch wenn ich einen validen DP angebe ist die Bezeichnung falsch.

**Comment by Zefau** [comment]
Ok, verstehe. Die Anzeige in der Konfiguration ist falsch. Das Geräte-Label ist für das Backend bestimmt.

Die Reihenfolge für das Frontend ist: Label im Layout -> Bezeichner im Datenpunkt -> Name des Geräts

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.1`

**Comment by Kaskadeur111** [comment]
habe v3.0.2 draufgezogen. Passt wieder, Danke!
