### ISSUE TITLE
Chart wird nicht angezeigt V3.0.1

### ISSUE THREAD

**Issue by Algieio** [Zefau/ioBroker.jarvis#1395]
Nach Update auf V3.0.1 werden alle Diagramme nicht mehr angezeigt.

**Comment by Zefau** [comment]
Meinst du Chart oder HistoryGraph? Daran habe ich gar nichts gemacht. Hast du einen Fehler in der Browser Konsole (F12)? 

Ist es einfach leer? Kannst du mal screenshoten?

**Comment by Algieio** [comment]
Ich hatte hier ein Chart. In V3.0.0 wurde es auch angezeigt.
F12 funktioniert bei mir irgendwie nicht. Ist die Tastenbelegung bei einem Mac gleich?

<img width="1166" alt="Bildschirmfoto 2021-12-28 um 21 44 23" src="https://user-images.githubusercontent.com/96116321/147605934-6d547257-8bfb-450b-a8d9-4b252436f080.png">

Komischerweise komme ich nicht mehr in die Jarvis-Konfiguration. Es wird eine leere Seite angezeigt.

**Comment by Algieio** [comment]
in die Konfiguration komme ich jetzt. Aber F12 funktioniert bei mir nicht.

**Comment by Zefau** [comment]
F12 ist die Entwickler-Konsole, siehe https://intercom.help/scoutpad/de/articles/2419374-so-offnest-du-die-entwickler-konsole für Mac

**Comment by Algieio** [comment]
Super, vielen Dank!
Hier das Screenshot 
![image](https://user-images.githubusercontent.com/96116321/147609823-fad5ca6d-d335-4aca-be0c-691124bad36c.png)

**Comment by Zefau** [comment]
bitte installiere nochmal v3.0.1 von Github und prüfe, ob es nun geht

**Comment by Algieio** [comment]
Leider funktioniert es immer noch nicht.

**Comment by Zefau** [comment]
installiere dir nochmal die aktuelle v3.0.1 von Github bitte

**Comment by Algieio** [comment]
Mit dieser Version funktioniert es wieder. Vielen Dank!
