### ISSUE TITLE
HistoryGraph - history.0 not reachable!

### ISSUE THREAD

**Issue by Sev7eNup** [Zefau/ioBroker.jarvis#1397]
Ich habe vorhin Jarvis auf Version 3.0.0 von Github angehoben. Die Migration hat soweit funktioniert, jedoch werden mir seit dem keinerlei Charts mehr über das HistoryGraph Widget angezeigt. Ich nutze die InfluxDB zwecks Speicherung der Historie. Die Verlaufsdaten sind gefüllt und die Datenpunkte werden regelmäßig aktualisiert. Es erscheint folgende Fehlermeldung. Mit Version 2.2.x hat alles noch funktioniert.

![image](https://user-images.githubusercontent.com/79143581/147611161-bf4dad73-27fc-413d-a54c-7081740f7fff.png)

Exception output:
![image](https://user-images.githubusercontent.com/79143581/147611080-fb2774bc-ef05-4293-9db6-d17b5223343f.png)

Unter der Widget-Ansicht sehe ich, dass die InfluxDB korrekt ausgewählt ist.

![image](https://user-images.githubusercontent.com/79143581/147611269-6d4fc397-7b00-4565-b9da-1a1fb90e3edc.png)

**Comment by Zefau** [comment]
Kannst du dort wo `influxdb.0` ausgewählt ist was anderes auswählen? Wenn ja, bitte kurz was anderes wählen und dann wieder zurück. Der Wert vom Standard greift scheinbar falsch.

**Comment by Sev7eNup** [comment]
Das war es. Danke für die schnelle Rückmeldung. 8/9 Charts werden mir korrekt angezeigt. Ein einzelnes nicht. Graph wird korrekt erstellt, jedoch ohne Werte. Kann es etwas mit dem Datentyp des Datenpunkts zu tun haben? Auch dieser Chart war zuvor funktional.

![image](https://user-images.githubusercontent.com/79143581/147612909-a0b11cf1-4f70-4ca5-96dd-99666112578a.png)

**Comment by Zefau** [comment]
Hast du einen Fehler in der Browser Konsole (F12) ?

**Comment by Sev7eNup** [comment]
Keine Fehler, nur wenige Warnings. Diese hier kann ich nicht zuordnen, aber deuten eher auf alle Charts hin ohne dass es eine Auswirkung hat.

![image](https://user-images.githubusercontent.com/79143581/147613205-adda325a-dbca-481b-8fd9-f48bcab1c79f.png)

und...

![image](https://user-images.githubusercontent.com/79143581/147613245-9c5da43d-41b1-49b5-b77f-43cd26829654.png)

**Comment by Sev7eNup** [comment]
Beim Aktualisieren des betroffenen Charts werden folgende Meldungen ausgegeben.

![image](https://user-images.githubusercontent.com/79143581/147613441-c46237a4-f85c-4f8f-b9ae-028492633293.png)

**Comment by Zefau** [comment]
Die ersten 3 sind wegen den Fonts und nicht in dieser Sache. Die anderen sind meine Debugging Protokollierungen, die ich im Code vergessen habe zu entfernen. 

Wenn du mit dem Zeitraum spielst, ändert sich dann was? Ggf. auch mit der Vorschau-Leiste unten?

**Comment by Sev7eNup** [comment]
Fehler gefunden. Liegt auf meiner Seite. Der Wert des Datenpunkts besteht nicht nur aus einer Zahl, sondern aus einer Mischung aus Zahlen und einen String (Werteeinheit), z.B. "80 g" Die alte Version scheint hier fehlertoleranter zu sein was den Inhalt eines Datenpunkts betrifft und hat alles nach der Zahl abgeschnitten. Mit einer reinen Zahl im Datenpunkt klappt es.

Danke für die schnelle Hilfe!

**Comment by Zefau** [comment]
Dann nehme ich den Punkt nochmal auf.

**Comment by Zefau** [comment]
mit `v3.0.2-beta.0` sollte es nun wieder etwas fehlertoleranter sein
