### ISSUE TITLE
Verbindungsfehler

### ISSUE THREAD

**Issue by Loi83** [Zefau/ioBroker.jarvis#1398]
Hi 
ich habe mit meinem Tablet das Problem das keine Verbindung aufgebaut wird. Handy und Laptop gehen einwandfrei.
Auf dem Tablet und Handy nutze ich Wallpanel. Aber auch mit Chrome oder Fully bekomme ich keine Verbindung.
![Screenshot_20211229-090338_Chrome](https://user-images.githubusercontent.com/45265773/147640750-5f0b1378-40cd-4c4d-90fc-a20a09e8626f.jpg)
.

**Comment by Zefau** [comment]
Was kommt, wenn du direkt die URL mit dem Port `8400` aufrufst?

**Comment by Loi83** [comment]
Dann kommt "Die Webseite ist nicht erreichbar"

**Comment by Zefau** [comment]
Da stellt sich die Frage, warum das so ist. Insbesondere, warum du auf anderen Geräten da drauf kommst? Hast du Fehler im ioBroker Log? Ansonsten müsstest du mal schauen, ob der Port / die Website auf dem Gerät irgendwie gesperrt ist?

Es sollte die folgende Meldung erscheinen:
> This is the jarvis socket.io port!

**Comment by Loi83** [comment]
muss ich socket.io aktivieren? 
Habs grad auf nem anderen Samsung Tablet probiert, selbes problem.

**Comment by Zefau** [comment]
> muss ich socket.io aktivieren?

Nein, das bringt jarvis mit.

`8400` ist für Instanz 0, `8401` ist für Instanz 1, und so weiter.
Jede jarvis Instanz macht einen eigenen Socket auf.

**Comment by Loi83** [comment]
Okay, ich hatte mal zwei Instanzen. die jarvis.0 habe ich gelöscht. Das Tablet greift trotzdem auf den Port `8400` zu.

**Comment by Zefau** [comment]
Die Instanz kannst du via URL mitgeben. Einfach aus de mm Iobroker Dashboard heraus öffnen.

**Comment by Zefau** [comment]
`%web_protocol%://%ip%:%webPort%/jarvis/index.html#/%instance%/&socketHost=%socketHost%&socketPort=%socketPort%&socketSecure=%socketSecure%`

**Comment by Loi83** [comment]
okay jetzt scheint es zu gehen. So kam der Link aus iobroker
`http://192.168.178.36:8082/jarvis/index.html#/1/home0`
Ich habe ihn in 
`http://192.168.178.36:8082/jarvis/index.html#/1/home1` 
geändert und nun gehts.

**Comment by Loi83** [comment]
Das habe ich so probiert. Aber er holt sich immer wieder den Port `8400` egal was ich eingebe

**Comment by Zefau** [comment]
Ja, Instanz 0 holt immer 8400, Instanz 1 holt 8401. Du steuerst es über die URL welche Instanz du willst.

**Comment by Loi83** [comment]
Ja, das ist mir bewusst. Ich gebe in der Url die Instanz 1 und den Port 8401 an, aber es wird trotzdem der Port 8400 aufgerufen.

**Comment by Zefau** [comment]
Jo, muss ich heute Abend prüfen.

**Comment by Zefau** [comment]
Es muss `#/1/` sein.

**Comment by Zefau** [comment]
Versuch also mal: `http://192.168.178.36:8082/jarvis/index.html#/1/&socketHost=192.168.178.36&socketPort=8401&socketSecure=false`

**Comment by Loi83** [comment]
Ich hatte am Anfang die Jarvis URL aus dem Browser übernommen, deswegen das `home0`. 

> Versuch also mal: `http://192.168.178.36:8082/jarvis/index.html#/1/&socketHost=192.168.178.36&socketPort=8401&socketSecure=false`

Damit funktioniert es auf meinem Tablet, aber beim Handy nimmer :D. 

Ich hab gestern noch eine Instant jarvis.0 erstellt, die ganzen Sachen importiert und seitdem läuft es wie gewohnt, nur mit `8400` Port.
Was mir noch aufviel, ich muss, egal welchen Browser ich nutze, min dreimal refreshen bevor Jarvis geladen wird.

**Comment by Zefau** [comment]
>  Was mir noch aufviel, ich muss, egal welchen Browser ich nutze, min dreimal refreshen bevor Jarvis geladen wird.

Was wird denn nicht geladen? Wie kann ich noch helfen?

**Comment by Loi83** [comment]
Mit der neuen Beta 3.0.4 keine Verbindungsfehler mehr
