### ISSUE TITLE
Icon: Default not applied to null value

### ISSUE THREAD

**Issue by CJohannimloh93** [Zefau/ioBroker.jarvis#1399]
- Version 3.0.0

All values expect "Bio" are currently (null) because it's the end of the year.
![image](https://user-images.githubusercontent.com/42354108/147657870-3bb1b077-133d-4d72-8bdd-7bc1409fcd38.png)

In the v2 Version the default property was applied.

Icon-Json: {"0":"delete-restore blink2s5x","1":"delete-restore","default":"delete-empty"}

**Comment by Zefau** [comment]
`null` Werte sind in v3 nicht gerne gesehen. Warum steht da kein ordentlicher Wert drin?

**Comment by CJohannimloh93** [comment]
Der adapter trashschedule gibt für daysleft (null) als Value an wenn kein nächster Termin gefunden wird

**Comment by Zefau** [comment]
Hmpf :-/

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.2`

**Comment by CJohannimloh93** [comment]
Jau funktioniert jetzt. Danke für die schnelle Umsetzung
