### ISSUE TITLE
Jarvis über iobroker Cloud

### ISSUE THREAD

**Issue by Schimi1983** [Zefau/ioBroker.jarvis#1402]
gibt es eine möglichkeit auf Jarvis über die iobroker Cloud zuzugreifen?

Ohne eine App... direkt übern Browser......

Ansonsten würden ja nur Weiterleitungen und Portfreigaben übrig bleiben (VPN natürlich auch)... was ich (und bestimmt viele andere) gerne vermeiden würde...

Einsatzzweck sind Geräte ohne App (und/oder VPN) Möglichkeit z.b. Browser im Auto (z.B. Tesla Browser)

**Comment by Zefau** [comment]
Siehe https://github.com/Zefau/ioBroker.jarvis/issues/71
