### ISSUE TITLE
v3: Adapter Widget takes "Title", Admin Adapter takes "TitleLang" > Confusing / Missunderstandable

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1404]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

```v3.0.1``` / ```beta-28```

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Adapter Widget takes "Title", Admin Adapter takes "TitleLang" > Confusing / Missunderstandable

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.2-beta.0`

**Comment by RkcCorian** [comment]
Ja, passt. Tlw. stand bei mir noch was mit {eng: Xbox} drin. Nachdem ich den Namen einmalig geändert habe hat auch der Eintrag unter ```system.adapter....``` gepasst. Super!
