### ISSUE TITLE
Defaults don't apply correctly

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1405]
https://forum.iobroker.net/post/729182
https://forum.iobroker.net/post/729654

**Comment by Zefau** [comment]
Workaround
> Ich habe dann als Eingabekomponente auf die andere umgestellt (wo man die Farbwerte auswählen) kann und danach wieder auf LevelBody zurückgestellt dann hat es funktioniert.

**Comment by Coalado** [comment]
Workaround:
Das klappt bei mir nicht. In der UI einen anderes Body Element wählen, und dann wieder zurück auf LevelBody sorgt nur dafür, dass in der JSON wieder "nichts" steht.
Für mich klappt es nur, wenn ich in die JSON "Manuel"         "bodyElement": "LevelBody" eintrage.

**Comment by Zefau** [comment]
@Coalado schau nochmal mit `v3.0.2-beta.1`

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/730301

**Comment by Coalado** [comment]
> @Coalado schau nochmal mit `v3.0.2-beta.0`

Scheint zu gehen
