### ISSUE TITLE
provide selected colours as CSS variable

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1406]
All colours which are selected within jarvis (drawer, Tabs, calendar, etc.) shall be in provided as s CSS variable for further usage.

- [x] ~~Drawer~~ _not possible anymore due to the replacement of colors with styles_
- [x] ~~Tabs~~ _not possible anymore due to the replacement of colors with styles_
- [x] Calendars
- [x] Chart
- [x] HistoryGraph

**Comment by Zefau** [comment]
implemented with `v3.1.0-alpha.40`

**Comment by mcuiobroker** [comment]
Wie kann man drauf zugreifen?

**Comment by Zefau** [comment]
https://www.w3schools.com/css/css3_variables.asp
