### ISSUE TITLE
Display Image Change picture

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#1409]
Hallo, 

kann ich bei einen Display Image das Bild bei DP Wert true einblenden und bei DP Wert false ein anderes Bild nehmen? Ähnlich wie in Vis Sichtbarkeit?

LG
Sigi

**Comment by TiboTake** [comment]
Da bin ich auch für, dann kann man das auch für Anwesenheitsbilder nutzen.

**Comment by mcuiobroker** [comment]
Alternativvorschlag, solange es nicht umgesetzt wurde:
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/module/displayimage#alternative-fuer-bild-umschalten-html

**Comment by mcuiobroker** [comment]
Ist mit `v3.1.0.-beta.7` durchführbar. Einträge in der Anzeigevariante vom Geräte-DP.
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/module/displayimage#bilderwechsel-bei-unterschiedlichen-statewerten-mit-eintraegen-in-der-anzeigevariante
