### ISSUE TITLE
Add filter / search option to device list

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#141]
https://forum.iobroker.net/post/497434
> ich finde es mühsam das richtige Gerät zu identifizieren... wäre es möglich ein en Filter für den Adapternamen der das Gerät bereitstellt aufzuführen?
> also, Shelly, Zigbee, Homematic etc.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/190

**Comment by WW1983** [comment]
Eine Suchfunktion, ähnlich wie im WIdget (Auswahl des Gerätes), wäre auch sehr nützlich wenn man viele Geräte hat

**Comment by Zefau** [comment]
Die geplante Filter-Funktion beinhaltet eine umfangreiche Suche nach

- [ ] Namen des Geräts
- [ ] ID des Geräts
- [ ] Gewerk des Geräts
- [ ] ID der Datenpunkte des Geräts
- [ ] Label der Datenpunkte des Geräts
- [ ] State sowie Action Trigger der Datenpunkte des Geräts
- [ ] Hersteller

**Comment by Zefau** [comment]
@WW1983 @cryptedx added with `v2.1.0-beta.1`.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/538381

**Comment by Zefau** [comment]
added info box with `v2.1.0-beta.15`.
