### ISSUE TITLE
TypeError: Cannot read properties of null (reading 'click')

### ISSUE THREAD

**Issue by RdTrxx** [Zefau/ioBroker.jarvis#1413]
**Prerequisites / Voraussetzungen**
- Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!** 
 2.2.1

**Describe the bug / Beschreibe den Fehler**
Nach erstem Start Klick auf "Einstellungen"

**Screenshots**
![Opera Momentaufnahme_2022-01-01_094228_192 168 27 10](https://user-images.githubusercontent.com/81949574/147847219-126f0934-ab06-486b-b6b6-da5386a2f615.png)
____

**Comment by Zefau** [comment]
I recommend you to move to v3.

**Comment by RdTrxx** [comment]
Done. Now testing ;-)
Thanx for that nice peace of work!
