### ISSUE TITLE
Converter v2->v3

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1415]
> Darüber hinaus hat es sehr viele Datenpunkte zerhauen, ist das weil das nur in Pro geht? Beispiele:
  ![x](https://user-images.githubusercontent.com/14368811/147851738-1b77c121-4fc5-4e1c-9304-5ce47a9219ee.png)

> SwitchAction ist weg und schöne Bezeichnung im Popup auch
   ![SwitchAction](https://user-images.githubusercontent.com/14368811/147851740-e9968583-a416-4c49-a412-04e4fa30e837.png)

> Graphen sind alle so:
   ![y](https://user-images.githubusercontent.com/14368811/147851787-5bccfe0d-3bcf-44f3-b5c5-ca38e5e9a8c3.png)

> Icons sind anders oder weg
  ![icon](https://user-images.githubusercontent.com/14368811/147851785-a8c98a7f-480b-475a-bf4a-9b14adef25c1.png)

**Comment by Zefau** [comment]
Könntest du mir zur Unterstützung die Datenpunkte jarvis.0.devices und jarvis.0.layout mit den v2-Werten zukommen lassen (ggf. aus einem Backup)?

Aus v3 zum Vergleich wäre es klasse, wenn du mir jarvis.0.devices und jarvis.0.layout sowie jarvis.0.widgets schicken könntest.

**Comment by CC1337** [comment]
Für's Protokoll, Datenpunkte wurden zugemailt. Hoffe das ist angekommen.

**Comment by CC1337** [comment]
Graphen wurden mit 3.0.2 behoben.

**Comment by Zefau** [comment]
Was ist konkret falsch?

1. ![x](https://user-images.githubusercontent.com/14368811/147851738-1b77c121-4fc5-4e1c-9304-5ce47a9219ee.png)
    Hier fehlt im Popup (rechts) die Datenpunkt Anzeige und im Layout (links) ist `LastChangeBody` drin, obwohl es leer sein müsste?

2. ![SwitchAction](https://user-images.githubusercontent.com/14368811/147851740-e9968583-a416-4c49-a412-04e4fa30e837.png)
   Popup (links) ist korrekt. Im Layout (rechts) fehlt der SwitchAction? Oder der Datenpunkt Anzeige?

**Comment by Zefau** [comment]
@CC1337

**Comment by CC1337** [comment]
Hi, 
zu 1.
> Hier fehlt im Popup (rechts) die Datenpunkt Anzeige
Genau
> Im Layout (links) ist LastChangeBody drin, obwohl es leer sein müsste?
Die Markierung zeigt nur "welches" Popup man hier sieht und dass die Werte dort vorhanden sind, da ist sonst nichts falsch

zu 2.
> Popup (links) hat den falschen Bezeichner. Was müsste das eigentlich stehen?
"Heizungsabsenkung", das Label Attribut aus dem Gerät "a34f695a-292c-40dd-85e6-23656c3c3aef" (s. json der v2 Config)
Evtl. war hier früher ein Fallback denn ich sehe das Label des DP "power" war vorher schon leer. Ggf. muss man das jetzt einfach beheben, wenn es nur am Konvertieren lag.
> Im Layout (rechts) fehlt der SwitchAction? Oder der Datenpunkt Anzeige?
SwitchAction fehlt. Da war eventuell auch eine Anzeige, weiß ich aber nicht mehr genau
`"display": {
                    "false": "Normal",
                    "true": "Deaktiviert"
                }`

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.5`

**Comment by Zefau** [comment]
Leider müsstest du die Konvertierung erneut durchlaufen. Hast du ein Testsystem, auf dem du das machen könntest?

Für das bestehende System kannst du https://forum.iobroker.net/post/737401 als Workaround nutzen.

**Comment by CC1337** [comment]
Ich hatte noch nichts geändert und habe die v2 Backups in die devices und layout DP geschrieben.
Vorher jarvis gestoppt, nach Update wieder gestartet.
Sieht nun sehr gut aus!
Lediglich das falsche Icon und wie mir jetzt auffällt vermutlich die Anzeige der Temperatur im primären DP fehlt
![grafik](https://user-images.githubusercontent.com/4866744/148704439-e1ee18a0-85eb-4f4b-9f6b-bd927615d540.png)
Ob das aber nun am Converter liegt oder ich da vorher etwas nicht korrekt hatte weiß icxh nicht, die wenigen Stellen würde ich jetzt manuell beheben. Betrifft z.B. Gerät mit ID "kellerwerkstatttemperatur_19aee"

Und ich bekomme auch errors dass Callbacks nur in Pro möglich sind.
Das Abo funktioniert bei mir nach wie vor nicht, Spinner nach Login im PayPal Fenster. Kann man das auch anderweitig lösen?

**Comment by Zefau** [comment]
beim Icon ist die Reihenfolge `primaryState` => `bodyState` => `Gerät` => `Gewerk`.

Was wurde denn bei v2 angezeigt?

**Comment by Zefau** [comment]
In deiner v2 Konfiguration ist bei dem Gerät auch nichts hinterlegt.

**Comment by CC1337** [comment]
Ich habe keine v2 mehr da. Evtl. war es leer und ich hab's nicht gemerkt, und jetzt ist es ein default nach Gewerk oder so.
Danke für's Beheben der anderen Sachen :)
