### ISSUE TITLE
Geräte Icon als Icon im HomeKitTile verwenden

### ISSUE THREAD

**Issue by simonssoftware** [Zefau/ioBroker.jarvis#1418]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is and how your feature request helps solving it

Wie in #1401 angesprochen könnte man einbauen, dass man das Geräte Icon als Icon im HomeKitTile verwenden kann?

----- OR -----

**Describe the solution you'd like**
A clear and concise description of what you want to be added.

**Comment by Zefau** [comment]
implemented with `v3.1.0-alpha.26`
