### ISSUE TITLE
List of symbols is not displayed when I is clicked.

### ISSUE THREAD

**Issue by Zwer2k** [Zefau/ioBroker.jarvis#1424]
Jarvis-Version 3.0.3

Beim Klicken auf auf "I" Symbol wird keine Liste der Icons angezeigt:
![image](https://user-images.githubusercontent.com/10438794/147985792-3b8c1307-eaee-4b99-acb5-0d4ff2dc748c.png)

**Comment by Zefau** [comment]
mit `v3.0.4-beta.2` behoben
