### ISSUE TITLE
Max-HUE einstellbar machen

### ISSUE THREAD

**Issue by Zwer2k** [Zefau/ioBroker.jarvis#1425]
Hallo,

ich verwende für LED-Steuerung AskSin++ (Homematic) Bibliothek, genauer HB-RC-2-PBU-LED . Dies Bibliothek verwendet für HUE Werte von 0 bis 255, Jarvis hingegen verwendet Werte bis 359. Bitte eine Möglichkeit in Jarvis schaffen Max-HUE festlegen zu können. Der Farbverlauf sollte entsprechend angepasst werden. Wenn nicht bereits implementiert, bitte auch für andere Schieberegler vorsehen (z.B. Dimmer).

**Comment by Zefau** [comment]
mittels `min`/`max` im Gerät, siehe https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/beispiele/geraete-einstellungen/datenpunkt-eigenschaften/min-und-max

**Comment by Zwer2k** [comment]
Für HUE funktioniert es leider nicht. Habe ich bereits getestet.

**Comment by mcuiobroker** [comment]
HUE-Slider gibt den falschen Wert zurück:
![image](https://user-images.githubusercontent.com/84818934/147993565-1a82fa73-4eb0-4344-a644-ac155e2f533e.png)
![image](https://user-images.githubusercontent.com/84818934/147993584-fa330430-eafa-4646-95e6-24425b146928.png)
Das ist ein Bug.

**Comment by Zefau** [comment]
Max-Hue nun mit `v3.1.0-alpha.9` konfigurierbar:

![image](https://user-images.githubusercontent.com/14368811/171285530-2807d31b-cc9b-4649-984c-49912eacac73.png)
