### ISSUE TITLE
Blank settings page

### ISSUE THREAD

**Issue by fir3drag0n** [Zefau/ioBroker.jarvis#1427]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**

v3.0.4-beta.2

- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]

![image](https://user-images.githubusercontent.com/36398628/147997454-eefcff92-7e8c-4f87-8bb4-3665e186caf6.png)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

I just wanted to change some color settings and then I wanted to change settings

auf deutsch: ich bin gerade dabei, mich in jarvis einzuarbeiten und habe angefangen, Farbeinstellungen zu ändern. Plötzlich komme ich aber nicht mehr auf die Einstellungsseite und mir wird nur eine weiße Seite angezeigt. Reload des Adapters und Deaktivierung des Sentry Mode haben nicht weitergeholfen.

Bei Google finde ich ein ähnliches Problem, damals war die Empfehlung, eine alte Beta zu installieren.
____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Meinst du die gesamte Konfigurationsseite? Also jeden Tab Geräte, Widgets, Layout, Styles UND Einstellungen?

Oder NUR die Seite mit den Einstellungen?

**Comment by Zefau** [comment]
Welche Farbeinstellungen hast du konkret geändert? Primär-und Sekundärfarbe? Was hast du dort eingetragen?

**Comment by Zefau** [comment]
Bekommst du noch andere Fehler / Warnungen, wenn du auf die Einstellungsseite zugreifst? Der Screenshot von dir ist grundsätzlich richtig, hat aber keine konkreten Hinweise auf den Fehler, sondern anderweitige Sachen.

**Comment by fir3drag0n** [comment]
> Meinst du die gesamte Konfigurationsseite? Also jeden Tab Geräte, Widgets, Layout, Styles UND Einstellungen?
> 
> Oder NUR die Seite mit den Einstellungen?

Nur die Einstellungsseite

**Comment by fir3drag0n** [comment]
> Welche Farbeinstellungen hast du konkret geändert? Primär-und Sekundärfarbe? Was hast du dort eingetragen?

Vom blau oder grau. Tabfarbe

**Comment by fir3drag0n** [comment]
> Bekommst du noch andere Fehler / Warnungen, wenn du auf die Einstellungsseite zugreifst? Der Screenshot von dir ist grundsätzlich richtig, hat aber keine konkreten Hinweise auf den Fehler, sondern anderweitige Sachen.

Nee, die Seite ist einfach leer. Hab jetzt neu installiert und nun Funktioniert es wieder.

**Comment by Zefau** [comment]
hm ok, sehr merkwürdig

**Comment by Zefau** [comment]
> Vom blau oder grau. Tabfarbe

Du hast normal ein Hex-Code ausgewählt / eingetragen? Oder was individuelles?

**Comment by Zefau** [comment]
Ich schließe das Issue erst mal. Sollte es wieder auftreten, dann gerne neu öffnen und einen Screenshot posten. Dann suche ich nochmal.
