### ISSUE TITLE
HUE-Slider gibt den falschen Wert zurück:

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1428]
HUE-Slider gibt den falschen Wert zurück:
![image](https://user-images.githubusercontent.com/84818934/147993565-1a82fa73-4eb0-4344-a644-ac155e2f533e.png)
![image](https://user-images.githubusercontent.com/84818934/147993584-fa330430-eafa-4646-95e6-24425b146928.png)
Das ist ein Bug.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1425#issuecomment-1004440324_

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1425
