### ISSUE TITLE
Statelist wird bei Änderung im Gerät nicht im Frontend aktualisiert, erst mit F5

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1429]
`v3.0.4-beta.2`
Bei Änderung der Einstellung im Gerät (Datenpunkt Stil), wird nach Speicherung die Statelist im Frontend nicht entsprechend angepasst.
Im Popup passt es.

**Comment by Zefau** [comment]
mit `3.0.4` sollte es passen

**Comment by mcuiobroker** [comment]
Passt.`v3.0.5` Danke.
