### ISSUE TITLE
iobroker.pro connect

### ISSUE THREAD

**Issue by Ptikbrn** [Zefau/ioBroker.jarvis#1430]
Error with connect via iobroker.pro

ChunkLoadError: Loading chunk 3 failed. (error: https://iobroker.pro/jarvis/static/js/3.c8fe7309.chunk.js)
a.e@https://iobroker.pro/jarvis/index.html:1:3416
i@https://iobroker.pro/jarvis/static/js/main.08fc3d34.chunk.js:1:1148176
y/t<@https://iobroker.pro/jarvis/static/js/main.08fc3d34.chunk.js:1:306699
_s/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1069198
_s@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1069347
bl@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1061293
ml@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1061216
sl@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1058225
Xi/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1009596
t.unstable_runWithPriority@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1084998
qi@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1009305
Xi@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1009543
Gi@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1009476
nl@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1055007
enqueueSetState@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1013304
w.prototype.setState@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:959043
value/</</<@https://iobroker.pro/jarvis/static/js/main.08fc3d34.chunk.js:1:276099
h.prototype.onack@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:717129
h.prototype.onpacket@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:716534
e.exports/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:718470
r.prototype.emit@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:275264
h.prototype.ondecoded@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:708019
e.exports/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:718470
r.prototype.emit@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:275264
d.prototype.add@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:393904
h.prototype.ondata@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:707972
e.exports/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:718470
r.prototype.emit@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:275264
u.prototype.onPacket@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1109707
u.prototype.setTransport/<@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1107310
r.prototype.emit@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:275264
o.prototype.onPacket@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:396558
o.prototype.onData@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:396507
f.prototype.addEventListeners/this.ws.onmessage@https://iobroker.pro/jarvis/static/js/11.c78c798b.chunk.js:2:1128323

**Comment by Zefau** [comment]
I'm not associated with ioBroker or ioBroker.pro and have no access / possibilities to help in this regard. I think you have to open an issue at ioBroker.cloud adapter.

**Comment by Ptikbrn** [comment]
but it run before the Update ...

**Comment by Zefau** [comment]
What did you update?

**Comment by Zefau** [comment]
The errors in the cloud (iobroker.pro) are for v2. If you have updated to v3 I have no idea what needs to be done on iobroker.pro because I have not association with it.

**Comment by MeisterTR** [comment]
for iobroker.pro i need a http webinstance so i have one web instance with https for my local vis and one http web instance for the cloud connection (iobroker cloud need a http instance) if i select in jarvis conf the second instance with port 8083 i get an error while loading
![2022-01-07_05h21_19](https://user-images.githubusercontent.com/6328382/148491250-9dcdaf48-ff85-4405-9c3a-764b3bde31ae.png)

**Comment by Ptikbrn** [comment]
what ist the Version of Jarvis ?

if it is v3 there is no communication via iobroker.pro

**Comment by Zefau** [comment]
Die Umstellung auf v3 muss serverseitig auf ioBroker.pro erfolgen. Dazu muss dort ein Feature Request gestellt werden. Dies würde ich machen, wenn mehr Benutzer auf v3 sind als auf v2.

**Comment by Trrw** [comment]
Gibt es hierzu bereits ein update?

**Comment by Zefau** [comment]
Nicht in meiner Macht, siehe https://github.com/ioBroker/ioBroker.cloud/issues/290

Bitte dort nachfragen.

**Comment by cbroeker1224** [comment]
Ich wäre auch sehr an diesem Feature interessiert. Gibt es hierzu Neuigkeiten?

**Comment by uwe72** [comment]
Mich würde nur den Status interessieren? D.h. Thema bekannt, wird sich aber so schnell nichts dran ändern?

**Comment by Zefau** [comment]
Ich selbst kann hier überhaupt nichts machen. Ich habe mit ioBroker und den Servern (iobroker.pro) nichts zu tun. Das kann nur Bluefox scheinbar und der meldet sich nicht.

**Comment by uwe72** [comment]
Danke dir! Alles gut. Viele Grüße

**Comment by Zefau** [comment]
Ich schließe das Issue, da es bei den Kollegen von ioBroker liegt, nicht bei jarvis. 

In jarvis wird https://github.com/Zefau/ioBroker.jarvis/issues/71 das Problem hoffentlich umgehen.

**Comment by Apollon77** [comment]
Ich möchte hier die aktuellen Infos sharen: Es liegt nach aktuellen Infos eher daran das Jarvis 3 ein weiterer eigener Websocket Port benötigt wuird und das kann die iobroker Cloud nicht routen.
Für Cloud Support muss alles über den Web adapter über Socket.io/webspckets laufen
