### ISSUE TITLE
Datenpunktwerte nicht sichtbar bei Klick auf Datenpunkt

### ISSUE THREAD

**Issue by Sev7eNup** [Zefau/ioBroker.jarvis#1432]
Version: v3.0.4-beta.2

Wenn ich auf einen Datenpunkt klicke, der einen validen Wert enthält, öffnet sich wie auch in Version 2.x ein weiteres Fenster mit allen Datenpunkten des Geräts. Diese sind derzeit leer bzw. die Werte sind nicht sichtbar, siehe Screenshot. In der alten Version ging es noch.

![image](https://user-images.githubusercontent.com/79143581/148105022-dc30f92c-5814-43f2-a494-9fff31cb4332.png)

**Comment by Zefau** [comment]
Ist ein Problem mit dem Converter, siehe https://github.com/Zefau/ioBroker.jarvis/issues/1415. Insofern Duplikat.

Du kannst das Popup im Gerät pflegen und dort den Switch "Show State" aktivieren.
