### ISSUE TITLE
Problem mit / durch Fritzbox-VPN, Fully Browser u.a. => Schalten etc. möglich, aber keine Reaktion der UI bis Reload

### ISSUE THREAD

**Issue by mh-hdl** [Zefau/ioBroker.jarvis#1433]
Hallo!
Bitte mal die Problematik bzgl. Web-Adapter unter

https://github.com/ioBroker/ioBroker.web/issues/148#issuecomment-1005441689

ansehen. Mein Problem ist dort beschrieben und ist nicht unbedingt ein direktes JARVIS-Problem.

Vielleicht kann Zefau dazu was beitragen...

Hier auch nochmal ein Teil der Fehlerbeschreibung als Zitat:

"Das Verhalten war / ist eigentlich immer gleich. Die VPN- Verbindung ist sowieso recht "lahmarschig" (mal besser, mal schlechter, wohl ein AVM/ Fritzbox-Thema), aber die grundsätzliche responsive Bedienung der JARVIS-Oberfläche über VPN geht nur mit dem Samsung Browser, d.h. nur hier "bewegt" sich optisch die Oberfläche. Bei den Anderen schaltet es, aber man sieht es erst nach Seiten-Reload."

Ergänzung:
Ganz, ganz selten, während zahlreicher Tests (Fully Browser auf / zu /VPN an /aus) reagierte JARVIS mal normal. Ein Muster war / ist nicht erkennbar.

**Comment by Zefau** [comment]
Wie sind denn deine Web Adapter Einstellungen? Hast du mal ein Downgrade probiert?

**Comment by mh-hdl** [comment]
Nachdem ich auf Basis eines Comment unter dem WEB- Adapter-Issue etwas herumgetestet habe und z.B. ein Socktio-Downgrade probiert habe, zeigte sich keine Verbesserung bzgl. meines VPN-Problems.
Ich habe keine Detail-Ahnung vom Background und kann nicht genau einschätzen, ob die Ursache nun bei Jarvis, im Web-Adapter, im socketio-Adapter oder vielleicht auch im VPN liegt. 
Was ich sagen kann ist, dass zumindest der Android-Samsung- Internet-Browser responsiv reagiert und es mit Jarvis 2.x und wohl (ich kann mich genau erinnern) auch mit einer der 3.x-betas funktionierte...

**Comment by Zefau** [comment]
Ein Socktio-Downgrade bringt nichts, da jarvis dies nun nativ mitbringt. Socket-io Adapter wird mit v3 nicht mehr genutzt.

Vermutlich liegt es an jarvis.

Die Architektur ist so gestaltet, dass beim Schalten der Datenpunkt in ioBroker gesetzt wird und visuell in jarvis nichts geändert wird. Auf Basis der Schaltung wird der geänderte Datenpunkt danach wieder nach jarvis gepushed, wodurch dann die visuelle Anpassung erfolgt.

Die Rückmeldung scheint auszubleiben bzw. stark verzögert zu sein. Hast du mobil eine Browser Konsole (F12) aus der du ggf. Informationen beziehen kannst?

**Comment by mh-hdl** [comment]
Das mit der Konsole werde ich mal probieren. Wird aber erst später etwas...
Ich werde zum Test mal meinen PC aus dem WLAN nehmen und über VPN verbinden.

**Comment by mh-hdl** [comment]
@Zefau 
So, ich habe mal das Ganze mal PC versucht. Im Chrome Browser läuft Jarvis über VPN normal und reagiert wie erwartet. Ich kann zwar jetzt über F12 Informationen liefern, aber ich habe keine Ahnung welche und ob die überhaupt helfen. Schließlich läuft Jarvis ja am PC über VPN normal. 
Ich kann das mit den Konsolen- Infos auch auf meinem Handy machen, wenn das irgendwie geht. Ich brauche dann aber mal Unterricht, wie das zu bewerkstelligen ist. Mit dem Fully Browser wird's wohl nichts, aber vielleicht mit Chrome oder Firefox (bei denen das Problem genauso besteht => gerade noch einmal getestet) oder auch eine spezielle App.

Vielleicht noch ein Hinweis: Fritzbox- VPN lässt sich auf neuestem Android (V12) und auch in Windows 10 nicht über das eingebaute VPN einrichten. AVM als Hersteller ist da wohl nicht ganz auf der Höhe der Zeit. Man muss Fremdsoftware nutzen. Ich nutze VPNcilla und habe auch mal die Original-FRITZ App von AVM eingerichtet. Geht aber auf Android so oder so nicht.

**Comment by mh-hdl** [comment]
Good Job!

Mit 3.0.5 (final) habe ich keine Probleme mehr! Fully reagiert perfekt und generell lädt Jarvis sehr schnell (gefühlt schneller als vorher).
Woran lag es?

Auf alle Fälle: DANKE!

**Comment by Zefau** [comment]
Das freut mich, auch wenn es mich wundert. Von welcher Version bist du auf 3.0.5 gegangen?

**Comment by mh-hdl** [comment]
...habe in der letzten Zeit jede Zwischenversion mitgenommen. Ich kam von 3.0.5.beta0...
