### ISSUE TITLE
Binding are not up-to-date after "some time"

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1434]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

```v3.0.4```

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

After refresh and also for "some" time the binding information will be taken correctly. I use them e.g. for formatting some text and icons. But after "some" time it will not update anymore. This means the values are updating but the formatting is still old.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/79741077/148213948-cfff8f6f-627d-4ce0-a609-73526ee9e268.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
@Zefau : Wie bereits angesprochen haben ich den Fehler aus der beta nun mit der 3.0.4 beobachtet. Leider tritt er dort nach einiger Zeit auf. Viele Grüße!

**Comment by RkcCorian** [comment]
@Zefau FYI: ```v3.0.7-beta.0``` Problem besteht weiterhin...
![image](https://user-images.githubusercontent.com/79741077/149013965-5b605268-5f4a-4a69-9d85-c385993b6d1a.png)

**Comment by Zefau** [comment]
Was steht denn in der Browser Konsole bzw. gibt es etwas, was du machst, dass darauf zurückzuführen wäre?

**Comment by RkcCorian** [comment]
Ich sehe leider bislang nichts.... ich lasse einfach das Browserfenster offen und warte
![image](https://user-images.githubusercontent.com/79741077/149032056-a393fe07-0192-41fa-ad1e-585039aba78e.png)

**Comment by RkcCorian** [comment]
@Zefau : Moin Zefau! Konntest Du den Fehler nachstellen? Du willst den Fehler "erst" in 3.1.x lösen?! Der Fehler fällt mir aktuell sehr häufig auf 😟 Viele Grüße!

**Comment by Zefau** [comment]
Ohne konkrete Hinweise bzgl. der Ursache kann ich es schwer beheben.

**Comment by RkcCorian** [comment]
Verstehe ich, daher zuerst die Frage ob Du es nachstellen konntest 😃

**Comment by Zefau** [comment]
Ich benutze aktuell kein Binding.

**Comment by RkcCorian** [comment]
Dann wäre das der richtige Zeitpunkt damit anzufangen?! 😄
Wenn ich es richtig überblicke fangen immer mehr an es zu nutzen...

Ich arbeite jetzt mal an einer Übersicht meiner Visualisierung zur Veröffentlichung 🙃

**Comment by RkcCorian** [comment]
Hab nochmal geschaut, sehe aber keine Fehlermeldung... OK wird nach Binding aber Grün formatiert. Gelb war es zuvor.
![image](https://user-images.githubusercontent.com/79741077/153079086-b0ca6f91-e370-4b84-90b9-5c4121177acc.png)

**Comment by Zefau** [comment]
1. Wenn du die Seite mittels F5 neu lädst und
2. dann den Adapter neu startest (damit die Socket-Verbindung abbricht)

Hast du das Problem dann auch?

Also tritt das Problem mit dem Bindung auf, wenn die Socket Verbindung abgebrochen ist (bzgl. der Warnung um 17:51:00 Uhr)?

**Comment by RkcCorian** [comment]
Ja. Was habe ich gemacht...
1. Variable auf "rote Formatierung" geändert
2. F5 Refresh
3. JARVIS Adapter gestoppt
4. Variable geändert auf "grüne Formatierung"
5. JARVIS Adapter gestartet
6. Screenshot aufgenommen
![image](https://user-images.githubusercontent.com/79741077/153082579-7e13bc10-2988-4e9b-9eaf-b3f43addde23.png)

**Comment by uwe72** [comment]
Sieht aus wie mein Problem wo ich hatte wenn man die Jarvis Seite lange stehen lässt. Auch ich nutze binding. Mein Workarround war ja, die Seite nach einem "idle" von ein paar Minuten neu zu laden. Was natürlich nicht die Lösung sein kann.

Kann meinem Vorredner nur zustimmen. Binding ist wichtig ;-) und es existiert definitiv ein Problem wenn die Jarvis-Seite lange steht.

**Comment by RkcCorian** [comment]
> Sieht aus wie mein Problem wo ich hatte wenn man die Jarvis Seite lange stehen lässt. Auch ich nutze binding. Mein Workarround war ja, die Seite nach einem "idle" von ein paar Minuten neu zu laden. Was natürlich nicht die Lösung sein kann.
> 
> Kann meinem Vorredner nur zustimmen. Binding ist wichtig ;-) und es existiert definitiv ein Problem wenn die Jarvis-Seite lange steht.
> 
> Siehe letzten Kommentare: #1509
> 
> Gleiches Thema aus meiner Sicht

Yup, meine Rede

**Comment by RkcCorian** [comment]
Hmmm.. bei normalen DPs habe ich es bislang nicht beobachtet, evtl. ist es mir aber nur noch nicht aufgefallen. Was ich gesehen habe ist außerdem, dass die Uhrzeit von dem DateTimeWidget nicht aktualisiert wird. Scheint dann ein allgemeines Problem zu sein.
@Zefau: Hast Du schon eine Idee? Aktuell habe ich einen Workaround (ohne Einfluss auf Benutzer), wenn mein Tablet aus geht, da 10 Minuten keine Bewegung, Aktualisiere ich. Aber wenn meine Frau zu Hause ist, läuft sie andauernd dran vorbei, da hilft es nicht...

**Comment by mcuiobroker** [comment]
Ist jetzt zwar kein Binding hilft aber vielleicht. PC im Energiespar Modus -> aufgeweckt
`Vorher`
![image](https://user-images.githubusercontent.com/84818934/155242408-73b8f49a-b7fa-4ecb-973e-402accd1f93b.png)
`Aufgeweckt`
![image](https://user-images.githubusercontent.com/84818934/155242851-b46b9b7f-18f6-4f73-80ee-4daf0e16780e.png)
`Nach ca 10 Minuten`
Read till Wed Feb 23 2022 01:27:09 GMT+0100 (Mitteleuropäische Normalzeit) instrument.ts:129
![image](https://user-images.githubusercontent.com/84818934/155242907-f5af936f-d631-4134-a984-d7acbcf0ddd9.png)

**Comment by Bernd9000** [comment]
Ist das der selbe Effekt wenn in der Zwischenzeit jarvis neu gestartet wird ?

Hier hab ich mal ein Test Schalter erstellt wo das Icon gelb blinkt wenn online status false ist.
Der zweite Testschalter simuliert/verändert den Online status also den Datenpunkt vom Binding.

Normaler Zustand:
![Animation1](https://user-images.githubusercontent.com/77005685/155853136-ea974e25-ede4-440e-9489-ceed07737000.gif)

Nach neu starten von jarvis wird das Binding nicht mehr verändert.
Schalter und secondary Datenpunkt funktioniert.
Icon blinkt nicht mehr:
![Animation2](https://user-images.githubusercontent.com/77005685/155853140-d6725de7-c044-4cdf-a03c-9cfea741a242.gif)

**Comment by uwe72** [comment]
Für mich geht dieser mittlerweile schon Richtung Blocker-Bug, mindestens Critical.

Wenn eine Meldung kommt "Session abgelaufen, o.ä." kann man als Anwender (der Jarvis-VIS) damit leben, aber es werden eben falsche, inkonsistente Daten angezeigt. Für mich hat dieses Thema eine sehr hohe Kritikalität.

**Comment by Bernd9000** [comment]
Komisch ist das ich keine Unterbrechung zum Socket Port habe.
Hab mal ein Tag lang eine Seite mit Binding offen gelassen, es wurde immer richtig angezeigt.
Kann es sein das das Problem nur bei https auftaucht ? Oder bei bestimmten Modulen ?

**Comment by uwe72** [comment]
> Komisch ist das ich keine Unterbrechung zum Socket Port nach einer bestimmten Zeit habe. Hab mal ein Tag lang eine Seite mit Binding offen gelassen, es wurde immer richtig angezeigt. Kann es sein das das Problem nur bei https auftaucht ? Oder bei bestimmten Modulen ?

Ich habe das Problem auch und nutze kein https. 

Habe allerdings das Gefühl, dass es mit dem Handy sehr oft auftritt und an meiner Jarvis-VIS auf dem externen Monitor weniger (oder nie?!).

Beim Handy ist es leider schon sehr sehr oft aufgetreten

**Comment by Bernd9000** [comment]
Ich ging davon aus das da ein zusätzliches Problem mit dem Browser vorhanden ist, aber dem ist wohl nicht so.
Bei den Mobil Geräten taucht das wohl häufiger auf weil diese sich z.B. mit einem neuen Access Point verbinden.
Egal, es bleibt das Problem das nach wieder verbinden die Bindings nicht mehr funktionieren.

**Comment by uwe72** [comment]
hatte das Problem heute auch wieder am esternren Monitor.

Aber leider heute auch sehr oft am Handy..

Es ist nicht mein Projekt, bin zuständig für andere IT-Projekte, aber es ist echt ein wichtiger Bugfix, der eigentlich das komplette Jarvis in Frage stellt. Jarvis ist VIS haushoch überlegen, aber man sollte die Lücken zu VIS bei deren Vorteile schließen und das ist eben das zuverlässige Binding. Ohne Binding geht heute nichts. Und ehrlich gesagt. ja das brauch man eigentllich an fast jeder Stelle.

Nicht, dass es falsch rüber kommt. Ich setze komplett auf Jarvis. Die "Pixelschubserei" von VIS brauche ich nicht. Ich schätzte bei VIS eben nur das Binding, aber dieses ist auch wichtig. Neben den Bugfixes, sollte dieses eigentlich der Schwerpunkt der nächsten Monate sein. Gratulation für diesen tollen Adapter!!

**Comment by RkcCorian** [comment]
Moin! Hab die ```v3.1.0-alpha.11```installiert, bekommen aber eine Fehler, dass ich keine Lizenz habe. Fehler ist braucht es für 3.1.0 ne neue Lizenz?

**Comment by mcuiobroker** [comment]
Ist bekannt siehe #1670 .

**Comment by RkcCorian** [comment]
Dankeee

**Comment by Bernd9000** [comment]
`v3.1.0-alpha.16`
Leider Fehler noch vorhanden.
Ist Verbindung unterbrochen wird Binding bei mir nicht aktualisiert

**Comment by Zefau** [comment]
bitte nochmal mit `v3.1.0-alpha.33` prüfen

**Comment by Bernd9000** [comment]
Ich kann es leider nicht testen wegen [v3.1.0-alpha.25 Binding schaltet anderen Datenpunkt #1783](https://github.com/Zefau/ioBroker.jarvis/issues/1783)

**Comment by Bernd9000** [comment]
Seit `v3.1.0-alpha.33/34` funktioniert es bei mir wieder, super !
