### ISSUE TITLE
Keine Socket Verbindung bei der Benutzung eines Fully Kiosk Browsers

### ISSUE THREAD

**Issue by Zwer2k** [Zefau/ioBroker.jarvis#1438]
Bei der Benutzung eines Fully Kiosk Browsers kann auf manchen Geräten die Socket Verbindung nicht aufgebaut werden (bei mir Huawai Mediapad M5). Problem besteht erst seit Jarvis 3.0.x . Nach dem Zurücksetzen des Browsers funktioniert die Verbindung 1x, danach nicht mehr. Unter anderen Browsern auf dem selben Tablet funktioniert Jarvis. Alle andere Seiten/Visualisierungen funktionieren unter dem Fully ohne Probleme. Auf einem Samsung Smartphone funktioniert Jarvis unter Fully auch.

![image](https://user-images.githubusercontent.com/10438794/148298810-edffe6b1-6f35-48e0-a8ca-5c867a5425f6.png)

**Comment by mh-hdl** [comment]
Hallo,

ich bin nicht vom Fach, aber könnte es sein, dass das Problem auch mit 

https://github.com/Zefau/ioBroker.jarvis/issues/1433#issue-1094061108

bzw.  dem Issue unter dem Iobroker.web-Adapter 

https://github.com/ioBroker/ioBroker.web/issues/148

zusammenhängt?

Ich selbst habe keine Probleme mit Fully im eigenen WLAN, aber sowie ich es mobil bzw. aus einem anderen WLAN per Fritzbox-VPN nutzen will, reagiert Fully beim Schalten nicht optisch (Aktion passiert, aber Schalter ändert sich nicht in der UI)

**Comment by ozwo71** [comment]
Hallo,
bei mir läuft iobroker unter docker auf einem raspi 4.
Eben habe ich in admin.0 und web.0 auf HTTPS und Authentifikation umgestellt und erhalte nun beim Zugriff auf jarvis genau die gleich Fehlermeldung wie der Thread-Ersteller.
Allerdings nur mit Firefox. Edge funktioniert ohne Probleme.
web v3.4.16
admin v5.2.3
jarvis v3.0.3

Die Ausgabe der Firefox-Konsole liefert:
`App Welcome to jarvis v3.0.3 app.ffec0caf.js:1:1118297
App Using instance 0. app.ffec0caf.js:1:1118348
17:03:48 | INFO | CONNECTION | Connecting to https://chaosdocker.lan:8400 (#1)... app.ffec0caf.js:1:537694
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://chaosdocker.lan:8400/jarvis-socket/?EIO=4&transport=polling&t=Num8Sjm. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://chaosdocker.lan:8400/jarvis-socket/?EIO=4&transport=polling&t=Num8Sxu. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://chaosdocker.lan:8400/jarvis-socket/?EIO=4&transport=polling&t=Num8Tgi. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

17:03:53 | ERROR | CONNECTION | Failed connecting to https://chaosdocker.lan:8400 (#1)! app.ffec0caf.js:1:537694
17:03:53 | INFO | CONNECTION | Connecting to http://chaosdocker.lan:8400 (#2)... app.ffec0caf.js:1:537694
Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://chaosdocker.lan:8400/jarvis-socket/?EIO=4&transport=polling&t=Num8Ty1. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://chaosdocker.lan:8400/jarvis-socket/?EIO=4&transport=polling&t=Num8UH1. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf https://chaosdocker.lan:8400/jarvis-socket/?EIO=4&transport=polling&t=Num8Um7. (Grund: CORS-Anfrage schlug fehl). Statuscode: (null).

17:03:58 | ERROR | CONNECTION | Failed connecting to http://chaosdocker.lan:8400 (#2)!`

Die Konsole in Edge liefert
`App Welcome to jarvis v3.0.3
app.ffec0caf.js:1 App Using instance 0.
app.ffec0caf.js:1 16:45:38 | INFO | CONNECTION | Connecting to https://chaosdocker.lan:8400 (#1)...
app.ffec0caf.js:1 16:45:38 | INFO | SOCKET | Connected to https://chaosdocker.lan:8400.
app.ffec0caf.js:1 16:45:38 | INFO | PRO | Valid Pro User: Mein Name`

Vis in Firefox lässt sich ohne Probleme öffnen.

Was braucht Ihr noch zur Fehleranalyse?

Danke & Grüße
Oliver

**Comment by ozwo71** [comment]
Jo - das war's. Vollkommen logisch. Aber da muss man trotzdem erstmal drauf kommen...

**Comment by ozwo71** [comment]
Vielen Dank!

**Comment by Zefau** [comment]
@Zwer2k bei dir auch ?

**Comment by ozwo71** [comment]
BTW: im Fully Browser habe ich "Ignore SSL Errors" bei den "Advanced Web Settings" eingeschaltet, damit der Zugriff mit selbstsignierten Zertifikaten klappt.

**Comment by Zwer2k** [comment]
"Ignore SSL Errors" habe ich bereits getestet gehabt, dürfte aber bei der Benutzung der unverschlüsselten Verbindung (Port 8082 + 8400) keine Auswirkungen haben. 

Hab jetzt Verschlüsselte Verbindung (Port 8482 + 8400) getestet, da bekomme ich auch gleiche Fehlermeldung .
![image](https://user-images.githubusercontent.com/10438794/148536053-8464dfa8-c26b-49cd-a66c-dfea5c529537.png)

Anschließend mit Chrome auf einem Windows Rechner.
In der Browser-Konsole steht:        
`       Mixed Content: The page at 'https://iobroker1:8482/jarvis/index.html#/0/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://iobroker1:8400/jarvis-socket/?EIO=4&transport=polling&t=NuqE_xP'. This request has been blocked; the content must be served over HTTPS.
`

Und wenn Websocket Adresse aufrufe,  scheint da kein Zertifikat mitzukommen.
![image](https://user-images.githubusercontent.com/10438794/148537332-2d5c7e43-910e-4902-80bf-cdfa587e9e20.png)
![image](https://user-images.githubusercontent.com/10438794/148537439-99c10fc3-51ce-40fe-b6c5-7b574fb17513.png)

Ohne Verschlüsselung kann ich Websocket-Seite abrufen, da hat aber Webbrowser was dagegen (siehe Meldung oben)
![image](https://user-images.githubusercontent.com/10438794/148536592-25f97b74-d3fe-47cc-838b-801f87c243b6.png)

**Comment by Zefau** [comment]
@Zwer2k wie hast du die Whitelist konfiguriert?

![image](https://user-images.githubusercontent.com/14368811/148686444-98e8b16a-fce9-4568-a98e-9af1c1addf51.png)

Hast du Fehler im ioBroker Log im ioBroker Backend?

Dass du via Browser nicht auf die URL kommst ist schon merkwürdig.

**Comment by Zwer2k** [comment]
So wie in deinem Screenshot. Hab aber jetzt auch testweise eine IP in die Whitelist eingetragen. Bringt leider auch nichts.
Im Log gibt es keine Fehler. Leider sehe ich auch nicht im Log wenn eine Verbindung von einem Client zum Socket-Port aufgebaut wird, auch bei funktionierenden Clients nicht. Loglevel habe ich auch auf DEBUG gestellt. Hier wehre eventuell etwas mehr Logging sinnvoll.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.6-beta.0`, damit sollte mehr Log drin sein

**Comment by Zwer2k** [comment]
Vielen Dank für die Erweiterung.
Ich bekomme nur folgende Log-Einträge beim Starten des Adapters, beim Verbinder der Seite kommt aber nichts
<html>
<body>


jarvis.0 | 2022-01-10 23:29:17.063 | info | Found Backups for devices.
-- | -- | -- | --
jarvis.0 | 2022-01-10 23:29:17.058 | error | require(...).ht is not a function
jarvis.0 | 2022-01-10 23:29:17.057 | debug | Connection: ioBroker host detected with iobroker1 (IP: 192.168.44.7)
jarvis.0 | 2022-01-10 23:29:17.054 | info | Found Backups for widgets.
jarvis.0 | 2022-01-10 23:29:17.054 | info | Found Backups for styles.
jarvis.0 | 2022-01-10 23:29:17.053 | info | Found Backups for settings.
jarvis.0 | 2022-01-10 23:29:17.053 | info | Found Backups for layout.
jarvis.0 | 2022-01-10 23:29:17.047 | debug | Web Configuration: {"port":"8082","auth":false,"secure":false,"bind":"0.0.0.0","cache":true,"socketio":"","simpleapi":true,"defaultUser":"admin","ttl":"3600","certPublic":"defaultPublic","certPrivate":"defaultPrivate","certChained":"","addUserName":false,"forceWebSockets":false,"whiteListEnabled":false,"leEnabled":false,"leUpdate":false,"leCheckPort":80,"lePort":"80","whiteListSettings":{"default":{"user":"admin","object":{"read":true,"list":true,"write":true,"delete":true},"state":{"read":true,"list":true,"write":true,"create":true,"delete":true},"file":{"read":true,"list":true,"write":true,"create":true,"delete":true}}},"loginBackgroundColor":"","loginBackgroundImage":false,"basicAuth":false,"disableExtensions":false,"disableStates":false,"disableFilesObjects":false,"defaultRedirect":""}
jarvis.0 | 2022-01-10 23:29:17.010 | info | starting. Version 3.0.6-beta.0 in /opt/iobroker/node_modules/iobroker.jarvis, node: v16.13.1, js-controller: 3.3.22


</body>
</html>


Hab jetzt mit Remote-Debugging versucht, aber auch da kann ich nur sehen, dass die Verbindung nicht zustande kommt

![image](https://user-images.githubusercontent.com/10438794/148850491-7ccd647e-3233-4681-b965-2e5b328b72d7.png)

**Comment by Zefau** [comment]
`require(...).ht` ist mit `v3.0.7` nun behoben (und mehr im Log sein).

**Comment by Zwer2k** [comment]
Die require Fehlermeldung ist jetzt weg. Problem mit Fully besteht weiterhin

<html>
<body>


jarvis.0 | Zeit | silly | Nachricht
-- | -- | -- | --
jarvis.0 | 2022-01-12 08:18:48.523 | debug | Client with IP 192.168.42.35 disconnected: transport error
jarvis.0 | 2022-01-12 08:18:43.530 | debug | Connection: Origin detected with http://iobroker1:8082 (allowed due to all)
jarvis.0 | 2022-01-12 08:18:43.530 | debug | Connection: Origin detected with http://iobroker1:8082...
jarvis.0 | 2022-01-12 08:18:43.492 | info | Client with IP 192.168.42.35 connected
jarvis.0 | 2022-01-12 08:18:43.492 | debug | Websocket-Handler for client initialized
jarvis.0 | 2022-01-12 08:18:43.483 | info | Client connecting...


</body>
</html>

**Comment by Zefau** [comment]
Hast du Fehler in der Browser Konsole (F12) von jarvis?

**Comment by Zwer2k** [comment]
Chrome unter Windows hat keine Fehler.

Unter Fully scheint die Socket Verbindung zu Stande zu kommen, bricht aber scheinbar nach kurzen Zeit ab.
![image](https://user-images.githubusercontent.com/10438794/149217338-6fce6e87-e3a8-4703-b621-baefcd9522fd.png)

**Comment by Zwer2k** [comment]
Gibt es eventuell Probleme wegen der Umleitung

![image](https://user-images.githubusercontent.com/10438794/149219614-1f83f6bc-4c43-4022-8664-602085463d99.png)

**Comment by Zefau** [comment]
Deine Versionen sind inkonsistent. Starte mal den Web Adapter durch.

**Comment by Zwer2k** [comment]
Umleitung kommt jetzt nicht mehr, unter Fully funktioniert es aber immer noch nicht

![image](https://user-images.githubusercontent.com/10438794/149232134-05962dc1-8027-40cf-a0ae-1c1746ac78ae.png)

**Comment by Zefau** [comment]
Bitte dran denken auf dem Gerät das selbst signierte Zertifikat anzunehmen.

**Comment by Zwer2k** [comment]
Ich verwende doch keine SSL Verbindung, die Meldung kommt (so wie ich es verstehe) nur weil Jarvis beide Varianten (verschlüsselt + unverschlüsselt) durprobiert. Die unverschlüsselte Verbindung kommt auch zustande, wird aber scheinbar gleich wieder abgebrochen.
Hab auch "Ignore SSL errors " aktiviert. Hab auch versucht Zertifikat anzunehmen, da kommt aber nur ERR_SSL_PROTOCOL_ERROR direkt auf der Seite. 
Wie wird das Zertifikat am Port 8400 bereit gestellt? Bzw. wird es überhaupt bereitgestellt wenn ich keine verschlüsselte Verbindung will (also per http://*:8082 verbinde)?

**Comment by Zefau** [comment]
> Wie wird das Zertifikat am Port 8400 bereit gestellt?

Über die Auswahl im Web Adapter. Wenn keine verschlüsselte Verbindung im Web Adapter gewählt wird, kann das natürlich alles ignoriert werden.


Mit der aktuellen Version sollte mehr im ioBroker.Log stehen. Gibt es da keine weiteren hilfreichen Informationen?

**Comment by Zefau** [comment]
Also du kannst die URL `http://iobroker1:8400` auf dem gleichen Gerät - auf dem du auch Fully Browser laufen - problemlos aufrufen, richtig?

**Comment by Zwer2k** [comment]
Ja, Chrome, Firefox, Opera alle funktionieren auf dem gleichen Gerät ohne Probleme.

Hab noch was rausgefunden: Hab das gerät komplett zurück gesetzt, anschließend lief Jarvis unter Fully, die Oberfläche sah aber etwas komisch aus. 
![image](https://user-images.githubusercontent.com/10438794/149421012-1477f3e4-c7ea-4d32-8868-95a8d4bde729.png)
Fully hat dabei eine Meldung angezeigt, "Please update Chrome, current Version 70". D.h. WebView war veraltet. Nach dem Aktualisieren kommt wieder bekannte Fehlermeldung. 
Hab dann Chrome wieder auf die alte Version gebracht und zusätzlich Chrome Dev Installiert, dann kann ich im Fully zwischen dem veralten und aktuelle VebView umschalten. D.h. entweder habe ich roten Bildschirm mit Fehlermeldung oder Jarvis ohne Schaltflächen wie im Screenshot.

**Comment by Zwer2k** [comment]
Das kommt im Log
<html>
<body>


jarvis.0 | 2022-01-14 00:10:00.924 | debug | Client with IP 192.168.42.35 disconnected: transport close
-- | -- | -- | --
jarvis.0 | 2022-01-14 00:09:55.922 | debug | Connection: Origin detected with http://iobroker1:8082 (allowed due to all)
jarvis.0 | 2022-01-14 00:09:55.921 | debug | Connection: Origin detected with http://iobroker1:8082...
jarvis.0 | 2022-01-14 00:09:55.894 | info | Client with IP 192.168.42.35 connected
jarvis.0 | 2022-01-14 00:09:55.893 | debug | Websocket-Handler for client initialized
jarvis.0 | 2022-01-14 00:09:55.881 | info | Client connecting...
jarvis.0 | 2022-01-14 00:09:55.877 | debug | Connection: Origin detected with http://iobroker1:8082 (allowed due to all)
jarvis.0 | 2022-01-14 00:09:55.877 | debug | Connection: Origin detected with http://iobroker1:8082...
jarvis.0 | 2022-01-14 00:09:55.795 | debug | Connection: Origin detected with http://iobroker1:8082 (allowed due to all)
jarvis.0 | 2022-01-14 00:09:55.795 | debug | Connection: Origin detected with http://iobroker1:8082...


</body>
</html>

**Comment by Zwer2k** [comment]
Hab jetzt endlich eine Möglichkeit gefunden Jarvis unter Fully zum laufen zu bekommen. Der Fehler schein nur dann aufzutreten, wenn Hardware-Grafikbeschleunigung aktiviert ist, sobald ich auf Software-Beschleunigung umstelle, funktioniert alles. 
![image](https://user-images.githubusercontent.com/10438794/149564429-d7fbe7d4-bc16-475c-9c4a-a7984962a9a8.png)

Bin beim Testen WallPanel App drauf gekommen, da ist der Fehler auch aufgetreten, zum Glück gibt es da nicht so viele Einstellmöglichkeiten wie bei Fully, daher bin ich schnell drauf gekommen.

Ich frag mich aber trotzdem wieso der Fehler nur mit Jarvis auftritt. Ich vermute, dass Jarvis hier ein Timing-Problem hat, denn in seltenen Fällen wurde ja die Oberfläche aufgebaut.

**Comment by Zefau** [comment]
@mcuiobroker könntest du das in die Doku aufnehmen? Komischer Fix, aber wenn's funktioniert.

**Comment by mcuiobroker** [comment]
Jo, mach ich.

**Comment by bastian1607** [comment]
> Hab jetzt endlich eine Möglichkeit gefunden Jarvis unter Fully zum laufen zu bekommen. Der Fehler schein nur dann aufzutreten, wenn Hardware-Grafikbeschleunigung aktiviert ist, sobald ich auf Software-Beschleunigung umstelle, funktioniert alles. ![image](https://user-images.githubusercontent.com/10438794/149564429-d7fbe7d4-bc16-475c-9c4a-a7984962a9a8.png)
> 
> Bin beim Testen WallPanel App drauf gekommen, da ist der Fehler auch aufgetreten, zum Glück gibt es da nicht so viele Einstellmöglichkeiten wie bei Fully, daher bin ich schnell drauf gekommen.
> 
> Ich frag mich aber trotzdem wieso der Fehler nur mit Jarvis auftritt. Ich vermute, dass Jarvis hier ein Timing-Problem hat, denn in seltenen Fällen wurde ja die Oberfläche aufgebaut.

Danke!! Ich dachte es liegt am Tablet selbst. Mir kam der Fehler auch bei Wallpanel gestern unter beim Test. Sehr, sehr hilfreich! Ich teste!

**Comment by bastian1607** [comment]
> Jo, mach ich.

Hi,
ich habe das auf dem Fully auf dem FireHD 10 getestet und es klappt nicht. Hast du zudem noch Chrome installiert gehabt? 
Beste Grüße

**Comment by bastian1607** [comment]
Siehe https://github.com/Zefau/ioBroker.jarvis/issues/1479#issuecomment-1013649463 und https://github.com/Zefau/ioBroker.jarvis/issues/1479#issuecomment-1013622122
werde nun Chrome installieren und weiter testen.

**Comment by Zwer2k** [comment]
Ja, Crome ist auf meinem Tablet der Standard-Browser.

**Comment by StefCGN** [comment]
Hallo,
Ich habe das gleiche Problem. Der Workaround mit "Graphics Accelaration Mode" klappt zwar, jedoch ist das Tablet dann nicht mehr nutzbar. Diese Einstellung ist bei Fully auch nicht empfohlen.
Mit dem Chrome Browser komme ich von allen Geräten problemlos auf Jarvis.

**Comment by BadgerRox** [comment]
Genau das gleiche Problem mit FF. Unter Chrome gehts ohne Probleme.
Gibts dafür schon eine Lösung?

**Comment by Zefau** [comment]
Via https -> selbst signiertes Zertifikat annehmen.

**Comment by BadgerRox** [comment]
Das selbst signierte Zertifikat von iobroker habe ich akzeptiert.
Nur leider hilft das nichts.

**Comment by HeliosXenon** [comment]
> Via https -> selbst signiertes Zertifikat annehmen.

Kannst du das erklären wie man das macht?

**Comment by Zefau** [comment]
> Kannst du das erklären wie man das macht?

Die Seite die es zu laden gilt im Browser direkt öffnen. Dann sollte der Browser eine Fehlermeldung bzgl. des Zertifikats anzeigen und du kannst es akzeptieren.

**Comment by HeliosXenon** [comment]
> > Kannst du das erklären wie man das macht?
> 
> Die Seite die es zu laden gilt im Browser direkt öffnen. Dann sollte der Browser eine Fehlermeldung bzgl. des Zertifikats anzeigen und du kannst es akzeptieren.

Funktioniert leider nicht. Wenn ich jarvis mit https:..... aufrufe steht da: "ERR_SSL_PROTOCOL_ERROR"
Nicht im normalen Browser und auch nicht im Fully...

**Comment by Zefau** [comment]
Dann ist was mit dem Zertifikat kaputt. Google sonst mal ERR_SSL_PROTOCOL_ERROR
