### ISSUE TITLE
Toggle Buttons

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1442]
> ich habe gerade von der v2 auf die v3 gewechselt und auch direkt das Abo mitgenommen, um das Projekt zu unterstützen, auch wenn ich vermutlich die Pro Feature nicht brauche. Soweit funktioniert auch alles ohne Probleme nur bei den Gruppen Aktionen fehlt mir aktuell etwas. In der V2 hatte ich für die Gruppen Aktionen immer das Element "ButtonAction" mit zwei dezierten Schaltflächen für AN und AUS, so konnte ich immer schön direkt das für die Gruppe anwenden was ich wollte. Gerade wenn einige Schalter unterschiedliche States hatten, war das eine feine Sache:

   ![jarvis_group_v2](https://user-images.githubusercontent.com/7381762/148388679-413abe23-aa20-4f60-ba67-c514cb82bd99.png)

> In der V3 habe ich nun irgendwie nur noch einen Button und wenn ich wie im Bild gesehen nun auf AUS schalte, gehen alle in der Gruppe an und erst durch einen zweiten Druck kann ich dann alle ausschalten. Irgendwie ist das nicht das was ich möchte. Habe gefühlt bereits mit allen Einstellungen herumgespielt aber nicht die richtige gefunden.
![jarvis_group_v3](https://user-images.githubusercontent.com/7381762/148388682-c0176909-259d-4181-86f7-b82aa129ecbc.png)

Wernn ich auf "SwitchAction" umstelle, sieht es irgendwie ganz komisch aus:
![jarvis_group01_v3](https://user-images.githubusercontent.com/7381762/148389263-55f88251-d027-40e5-9147-50c7f1cbc31b.png)

Jetzt nur die Frage, sitzt hier das Problem zwischen Stuhl und Tastatur, oder sind das noch Bugs der noch sehr jungen Version 3?
Würde mich hier über Hilfe freuen.

_Originally posted by @BooosesThaSnipper in https://github.com/Zefau/ioBroker.jarvis/discussions/1441_

**Comment by Algieio** [comment]
Hallo, 
Ich hätte auch gerne zwei Buttons als jeweils eins für Ein und Aus.

Wird das noch umgesetzt?

**Comment by BooosesThaSnipper** [comment]
@Zefau 
wie schaut es aus, wann kann man den damit rechnen, dass ein Feature welches es in v2 gab nun auch endlich in v3 wieder nutzen kann?

**Comment by BooosesThaSnipper** [comment]
@Zefau 
ich muss nochmals nachfragen. Die erste Anfrage hatte ich Anfang des Jahres gestellt:
https://github.com/Zefau/ioBroker.jarvis/discussions/1441

Leider bis heute keine wirkliche Reaktion wie es hier weitergeht, schließlich war das ein Feature welches es in der 2er Version gab und nun in der 3er Version nichtmehr Verfügbar ist. Bin daher ein wenig unhappy, hab bei der Umstellung gerne gezahlt, aber dann sollte auch ein gewisser Fortschritt erkennbar sein. Aktuell kennt die Zahl der Issues nur eine Richtung :-(

**Comment by Zefau** [comment]
Die Umstellung auf v3 war sehr mühsam, daher hab ich das nicht geschafft. Die Anzahl der Issues machen es nicht leichter.
Werde das mit v3.1 wieder nachliefern.

**Comment by Zefau** [comment]
@mcuiobroker @Algieio @BooosesThaSnipper mit `v3.1.0-alpha.18` gibt es nun `ButtonGroupAction`. 

Damit können entweder zwei Buttons definiert werden, oder mittels Datenpunkt-Anzeige beliebig viele (hierfür in den Komponenten Optionen aktivieren, damit die Datenpunkte-Anzeige verwendet wird).

![image](https://user-images.githubusercontent.com/14368811/174501149-1733e810-642f-44a7-ad75-71c21f4b2701.png)

**Comment by mcuiobroker** [comment]
`v3.1.0-alpha.50 `
ButtonGroupAction wird nicht angezeigt? Unabhängig, ob eine Gruppen ButtonGroupAction verwendet wird. Auch diese wird nicht angezeigt.
Besondere Einstellungen?
![image](https://user-images.githubusercontent.com/84818934/192650962-053db001-862e-47d0-85d6-5b48793d289f.png)
![image](https://user-images.githubusercontent.com/84818934/192651022-2e8b2a53-77d2-48ef-9ede-4e03933bc77a.png)
![image](https://user-images.githubusercontent.com/84818934/192651228-ad3ddc3c-6ec5-4e08-a1c0-c5dd7ce9c123.png)

` mittels Datenpunkt-Anzeige beliebig viele` ? Wie sollen die dann geschaltet werden, wie die Icons zugeordnet?

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by mcuiobroker** [comment]
Nein wird weiterhin nicht angezeigt.
![image](https://user-images.githubusercontent.com/84818934/193367799-68347475-b4ef-484e-bf1d-998fb803ba6f.png)
![image](https://user-images.githubusercontent.com/84818934/193367817-99e7f711-3df8-4886-b849-94bbee9e104c.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.53`

**Comment by mcuiobroker** [comment]
#1934
