### ISSUE TITLE
Beim schalten falscher Wert im Datenpunkt

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1445]
v3.03 und v3.05
Hab Heute jarvis zum Test von Version 3.01 nach 3.03 und 3.05 aktualisiert.
Dabei mußte ich feststellen das keine WLAN Steckdose (Tasmota Firmware) mehr eingeschaltet wurde, ausschalten funktionierte noch.
In der Browser Konsole kein Fehler, IOBroker Log meldet folgendes:
mqtt.0 : State value to set for "mqtt.0.cmnd.Steckdose-3.POWER" has to be type "string" but received type "number".
In den Datenpunkt Eigenschaften in jarvis der WLAN Steckdosen habe ich folgendes stehen:
{"on":"ON","off":"OFF"}

Fehler in jarvis:
Beim ausschalten wird "OFF" im Datenpunkt eingetragen = richtig
Beim einschalten wird der Wert "100" vom Typ number eingetragen = falsch, hier sollte "ON" eingetragen werden.

Der MQTT Adapter reagierte darauf ziemlich empfindlich und nahm keine Werte bei diesem Datenpunkt mehr an und mußte neu gestartet werden.

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.5`

**Comment by Bernd9000** [comment]
`v3.0.5`
Funktioniert wieder, Danke
Kann geschlossen werden.
