### ISSUE TITLE
Jarvis crashed during the autoconfig

### ISSUE THREAD

**Issue by RudyReindeer** [Zefau/ioBroker.jarvis#1446]
**Prerequisites / Voraussetzungen**
- jarvis V2.2.1 *
- [ ] Fehler / Screenshot siehe Anhang

**Describe the bug / Beschreibe den Fehler**
Ich habe Jarvis gerade neu installiert, autokonfiguriert und das Intro "abgearbeitet". Hatte also noch nicht viele Gelegenheite selbst etwas falsch zu machen. 
Jarvis started jetzt wieder ohne Fehler. Falls die Informationen interessant, aber nicht ausreichend sind, liefere ich gerne nach. Wenn das ein bekanntes / irrelevantes Problem ist, einfach schließen.

**Screenshots**
Siehe Anhang.
____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

![2022-01-06_Jarvis_log](https://user-images.githubusercontent.com/52382012/148530685-b10a26a4-caab-4855-b7b7-7510d88a396d.jpg)

**Comment by Zefau** [comment]
bitte direkt auf v3 gehen

**Comment by Zefau** [comment]
ist im latest und kommt jetzt im Januar ins stable
