### ISSUE TITLE
Upgrade vom v2.2.5 zu v3.0.3: Runden von Nachkommastellen funktioniert nicht mehr

### ISSUE THREAD

**Issue by dma7** [Zefau/ioBroker.jarvis#1447]
Mein Setup:  Linux Fedora 34 Host, dort läuft ioBroker in einem Docker Container (buanet), bzw. in einem Portainer Stack zusammen mit MariaDB und MQTT-Broker mosquitto.
js-controller: 3.3.22
node.js. 12.22.8

Ich habe soeben das Upgrade von 2.2.5 auf 3.0.3 gemacht. Es hat eigentlich sehr gut funktioniert, bis auf die Tatsache, dass ich mich erstmal nicht verbinden konnte, weil der Port 8400 nicht im Stack exponiert war. Das scheint neu bei v3 zu sein.

Mein Problem ist ein anderes,, geht in Richtung Kosmetik:

Ich habe ein paar Aqara Temp/Hum Sensoren, die ihre Werte zweistellig liefern. An anderen Stellen berechne ich aus solchen Werten die absolute Feuchtigkeit (für taupunkt-gesteuerte Lüftung) - dort können Werte mit vielen Nachkommastellen rauskommen. 

In der UI möchte ich max. eine Nachkommastelle sehen. Hierzu hatte ich bisher in den Datenpunkt-Eigenschaften 

`{"value":"val => parseFloat(val).toFixed(1)"}`

stehen gehabt. Das scheint nicht mehr zu funktionieren. 

![grafik](https://user-images.githubusercontent.com/12501460/148569618-926b3942-3793-457f-9cc8-8f3bc4b2c3d4.png)

Was mache ich falsch?

Danke für deine Arbeit Zefau!

Grüße
dma

**Comment by Zefau** [comment]
Die Nutzung des Callbacks ist ein Pro-Feature. Bist du Pro und es funktioniert nicht? Als Nicht-Pro-User sollte eigentlich eine Warnung kommen.

**Comment by dma7** [comment]
War mir nicht klar. Eine Warnung ist in der UI nicht gekommen, soweit ich mich entsinnen kann.
