### ISSUE TITLE
Tuneable White Slider

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1448]
Vielleicht kann man es in den HUE-Slider mit einbauen, als Alternative?
![image](https://user-images.githubusercontent.com/84818934/148617409-1664b62b-2771-4bab-b4e1-3b3df70eeef2.png)

https://codepen.io/stephanrusu/pen/zYOJdbm
`
 background: linear-gradient(
    to right,
    #ff5000 0%,
    #fff000 33%,
    #ffffff 50%,
    #00cfff 83%,
    #009fff 100%
  );
`
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/5967
Vielleicht Farben anpassen.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/styles/slider/tuneable-white-slider

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/751032
