### ISSUE TITLE
Paypal Zahlung funktioniert nicht

### ISSUE THREAD

**Issue by dma7** [Zefau/ioBroker.jarvis#1450]
Ich würde gerne das Abo abschließen.

Gehe dazu auf das Herz-Icon unten links. 
Auf der Seite erscheint 
![grafik](https://user-images.githubusercontent.com/12501460/148639344-dcb1d904-64d8-45b3-82f3-06458651ff85.png)

(im Screenshot fehlt der Anmelden-Button von Paypal, weil ich das gerade vorher gemacht habe)

Die Paypal-Anmeldung wird korrekt durchgeführt (im Popup-Window), danach "hängt" die Weiterleitung ewig. Popup-Fenster bleibt einfach leer. Bei anderen Shops funktioniert alles problemlos.

**Comment by dma7** [comment]
Das ist das Popup

![grafik](https://user-images.githubusercontent.com/12501460/148639504-6ce5d403-c976-47f7-afdb-f0f6af3998e5.png)

(ich habe es in der gleichen Browser-Session wiederholt, deswegen wohl "remembered" im Link).
Wenn ich den Browse schließe und anschließend wieder versuche, gleiches Bild (allerdings mit einem frischen Paypal-Link im Popup)

**Comment by dma7** [comment]
Gibt's eine alternative Möglichkeit, an das Abo zu kommen?

**Comment by Zefau** [comment]
Wenn der Login sich aufhängt und du die Seite neu lädst bist du trotzdem nicht eingeloggt?

**Comment by Zefau** [comment]
da das ein Paypal Plugin ist hab ich da wenig Einfluss drauf. Hast du Fehler in der Browser Konsole?

**Comment by dma7** [comment]
Das da oben ist mit Firefox passiert.

Ich habe jetzt gerade Chrome zur Abwechslung mal ausprobiert (benutze ich normalerweise nicht).
Damit scheint der Kauf durchgegangen zu sein. 

Die alte Funktionalität (siehe [Issue 1447](https://github.com/Zefau/ioBroker.jarvis/issues/1447) ) geht wieder.
