### ISSUE TITLE
Grad Celsius wird in Chart nicht angezeigt

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1451]
Version v3.0.5-beta.0

Ich habe in einem Chart bei Y Achse "°C" als Einheit eingetragen-
<img width="709" alt="Bildschirmfoto 2022-01-09 um 08 51 42" src="https://user-images.githubusercontent.com/2972703/148673961-040c67f0-cb0b-48e6-b903-df6b1f782393.png">

Im Chart wird die Einheit hinter dem Wert nicht angezeigt. Andere Einheiten wie % oder W sch
<img width="591" alt="Bildschirmfoto 2022-01-09 um 08 51 27" src="https://user-images.githubusercontent.com/2972703/148673983-454b7ccd-419e-4dee-b710-1124c065d934.png">
einen zu gehen.

**Comment by Zefau** [comment]
Ich bin mir nicht sicher, ob deine Einstellung für das gedacht ist, was du beabsichtigst.

Hast du die Einheit im Gerät im State eingetragen, der im Chart angezeigt wird?

**Comment by stephan1827** [comment]
Das stimmt der Wert kommt garnicht von da sondern vom Gerät hier funktioniert es aber nur wenn man den Standard Wert
<img width="1008" alt="Bildschirmfoto 2022-01-09 um 20 19 01" src="https://user-images.githubusercontent.com/2972703/148697488-771ba151-1b22-43b7-81b4-d13b3b4ad584.png">

ändert in

<img width="1012" alt="Bildschirmfoto 2022-01-09 um 20 19 09" src="https://user-images.githubusercontent.com/2972703/148697494-db6aa14d-fc50-4533-8193-cd1e06c40175.png">

**Comment by Zefau** [comment]
Ok, danke für den Hinweis

**Comment by stephan1827** [comment]
Sieht gut aus
