### ISSUE TITLE
Wetter-Widget Formatierungsfehler

### ISSUE THREAD

**Issue by MubiTec** [Zefau/ioBroker.jarvis#1453]
V3.04

Hab einen "schöner Wohnen" - Fehler im Wetter-Widget.
Wenn kein Niederschlag vorausgesagt ist, verschwindet die Anzeige. Dadurch rutscht auch der Windrichtungspfeil hoch und die Zeilen kommen durcheinander.
Kann man stattdessen dann 0mm anzeigen? Dann bleibt die Formatierung schön.

Danke! 
![Screenshot_2022-01-09-08-32-20-99](https://user-images.githubusercontent.com/44448393/148675906-5b8432c6-40b2-4bd6-9bff-fde4738fc814.jpg)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.5`

**Comment by MubiTec** [comment]
Ja, passt jetzt. Danke!
