### ISSUE TITLE
Sortierung in Geräteliste stimmt nicht

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1454]
Version 3.0.5-beta 0
Die Sortierung in der Geräteliste stimmt nicht
<img width="419" alt="image" src="https://user-images.githubusercontent.com/13101074/148683855-fa53392b-6003-43dc-b9af-e5c9a5479a3c.png">

**Comment by Zefau** [comment]
wahrscheinlich ist es bei dir nach ID sortiert?

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.5`

**Comment by AFPass** [comment]
Ich habe nach Name sortiert. bzw. dort drauf geklickt.

Auch in Version 3.0.7 beta stimmt die Sortierung nicht.

**Comment by Zefau** [comment]
Kannst du einen Screenshot der ganzen Seite liefern, damit ich mehr Kontext habe?

**Comment by Zefau** [comment]
@AFPass
