### ISSUE TITLE
Sortierung Mobile / Desktop. 

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1455]
Sortierung des Layouts ist unterschiedlich auf Mobile zum Desktop. 

Mobile scheint komplett durcheinander zu sein, sehe da kein Muster wie die Widgets angeordnet sind.

**Comment by Zefau** [comment]
Die Zahlen in den Widgets links oben in der Konfiguration geben die Reihenfolge an. Aktuell nur über Expertenmodus änderbar. Feature request bereits vorhanden.
