### ISSUE TITLE
favicon im browser wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1456]
![image](https://user-images.githubusercontent.com/22169074/148704607-a4347d06-1006-44c7-ae67-0347ccff7e71.png)

dort sollte 

![image](https://user-images.githubusercontent.com/22169074/148704619-c94f7900-e158-431d-8b52-6b07a4fdd33c.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.6-beta.0`

**Comment by ma-gu-16** [comment]
firefox schient zu gehen, chrome nicht.

**Comment by Zefau** [comment]
https://developers.google.com/search/docs/advanced/appearance/favicon-in-search?visit_id=637775117317754429-3805117628&rd=1
> Das Favicon muss ein Vielfaches von 48 px sein, z. B. 48 x 48 px, 96 x 96 px oder 144 x 144 px. SVG-Dateien haben keine bestimmte Größe. Jedes gültige Favicon-Format wird unterstützt.

**Comment by ma-gu-16** [comment]
Habe nochmal rein und raus. Nun ist es da. Danke.

**Comment by SliX185** [comment]
![tab](https://user-images.githubusercontent.com/47434006/150549946-2b6c2dc2-8383-4d32-b0b5-48e4bdf73406.JPG)
Im Tab wird es bei mir in Firefox angezeigt,
wenn ich es jedoch als Lesezeichen setze...

![bookmark](https://user-images.githubusercontent.com/47434006/150550057-e8e919e3-1a8a-48b3-9724-b30ac71d6512.png)

dann nicht mehr?
In Chromium basierten Browsern wird es garnicht angezeigt.

Javis 3.0.10-beta.3

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10`

**Comment by SliX185** [comment]
Bei Chromium Browsern funktionierts einwandfrei, DANKE! 👍

Firefox bleibt leider gleich... Im Tab Ja, als Lesezeichen gespeichert kommt das Standardsymbol. 
Kann ich aber so mit Leben, mir gings nur um Android / Chrome.
