### ISSUE TITLE
Icon im Konfigurator verschoben

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1457]
![image](https://user-images.githubusercontent.com/22169074/148704778-23b9f559-c939-44c8-b366-a20840b8e56b.png)

**Comment by Zefau** [comment]
Kannst du die Konfiguration screenshoten?

**Comment by Zefau** [comment]
Und Info, welchen Browser du nutzt. Im Firefox passt es bei mir.

**Comment by mcuiobroker** [comment]
Auch bei mir im Edge:
![image](https://user-images.githubusercontent.com/84818934/148843779-28e37057-b112-4e0b-8447-8545a8a44c67.png)
Firefox:
![image](https://user-images.githubusercontent.com/84818934/148843861-ad104829-031c-4648-adb5-4c1491035195.png)
Chrome:
![image](https://user-images.githubusercontent.com/84818934/148843946-797880e7-eb2d-4fc5-a822-21a5ffe6beef.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.6-beta.0`

**Comment by ma-gu-16** [comment]
passt.
