### ISSUE TITLE
DisplayImage Module / Datenpunkt

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1458]
DisplayImage sollte auch die Möglichkeit haben einen Datenpunkt anzugeben in dem das base64 drin steht. Bei änderung ggfl selbst aktualisieren ? 

![image](https://user-images.githubusercontent.com/22169074/148705480-da5a81c0-535a-452c-8f1d-730b80193ef1.png)

**Comment by mcuiobroker** [comment]
Es gibt doch ADD Device ,da kannst das zuordnen?
Oder möchte du hier den DP direkt angeben können? -> Feature 
![image](https://user-images.githubusercontent.com/84818934/148725366-02939bb6-24bc-442c-b7ea-a09bd797c0c8.png)

**Comment by Zefau** [comment]
> DisplayImage sollte auch die Möglichkeit haben einen Datenpunkt anzugeben in dem das base64 drin steht. Bei änderung ggfl selbst aktualisieren ?

Dem ist auch so. Du kannst das Gerät auswählen, wie mcu auch schreibt. Dann aktualisiert auch das Image bei DP Änderung.

**Comment by ma-gu-16** [comment]
klappt bei mir nicht ? 
```

  "23b0bb4a-29d8-4416-974d-088ceaef5b3f": {
    "name": "doorbird",
    "icon": "",
    "label": "",
    "function": "server",
    "states": {
      "image": {
        "stateKey": "image",
        "showState": false,
        "state": "javascript.0.doorbird.snapshot"
      }
    },
    "options": {
      "suppressPopup": true
    },
    "attributes": {},
    "id": "23b0bb4a-29d8-4416-974d-088ceaef5b3f",
    "revision": "d413c"
  }
```

Widget:
```

  "15dfa23c-d93b-4546-92d7-ec5b0854a0ca": {
    "id": "15dfa23c-d93b-4546-92d7-ec5b0854a0ca",
    "config": {
      "url": "",
      "refresh": "0",
      "height": "500",
      "width": "750",
      "size": "fit",
      "repeat": "no-repeat",
      "refreshMethod": "whitespace"
    },
    "icon": "cctv",
    "title": "Aussen Klingel",
    "module": "DisplayImage",
    "items": [
      {
        "type": "device",
        "deviceId": "23b0bb4a-29d8-4416-974d-088ceaef5b3f",
        "id": "e862344d-4798-4839-b342-e2f829840952",
        "primaryStateKey": "image",
        "bodyStateKey": "image",
        "bodyElement": "LastChangeBody"
      }
    ],
    "hideTitle": true,
    "hideSeparator": true,
    "revision": "bc38a"
  },

```

**Comment by Zefau** [comment]
Also bei mir funktioniert die base64 Anzeige eines Datenpunkts inklusive Aktualisierung.

**Comment by Zefau** [comment]
@ma-gu-16 Womit startet dein base64? 
```
data:image/png;base64...
```

**Comment by ma-gu-16** [comment]
Nein dieses ist aus einem BufferStream: fängt so an : /9j/4AAQSkZJRgABAgE

let buff = new Buffer(jpg);
let base64data = buff.toString('base64');

**Comment by Zefau** [comment]
Dann ist es kein base64, sondern ein Buffer ;-)

Dann geht es natürlich nicht, aber das kann ich fixen.

**Comment by ma-gu-16** [comment]
Ja die Quelle war ein Buffer von Doorbird daraus mache ich ja den base64 string. 
Wäre cool wenn du das implementieren kannst.

**Comment by Zefau** [comment]
Kannst du mir mal das Original an ioBroker.jarvis@mailbox.org schicken was du in den Datenpunkt hast, damit ich es testen kann?

**Comment by ma-gu-16** [comment]
> [ioBroker.jarvis@mailbox.org](mailto:ioBroker.jarvis@mailbox.org)

hab dir meins gesendet. 

du kannst auch jedes Bild z.b. hier hochladen : https://base64.guru/converter/encode/image   und dort wählst du base64 plain text. 

grüsse

**Comment by Zefau** [comment]
ah ok. Ich war nur wegen dem Buffer verwirrt.

**Comment by Zefau** [comment]
@ma-gu-16 versuch nochmal mit `v3.0.9-beta.0`

**Comment by Zefau** [comment]
@funky4t die Methode in v2 ist `zufällige Nummer der URL anfügen`. Es war in v2 die einzige Option, daher gab es keine dedizierte Auswahl.

Der wesentliche Unterschied ist, dass in v2 im `<img />` Tag gerendert wird und im v3 als Hintergrundbild. Das scheint Probleme zu verursachen. Bei mir geht es (leider). 

Nutzt du Firefox oder Chrome?
