### ISSUE TITLE
HistoryGraph formatter-Parameter unterstützt keine Callback function

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1459]
`v3.0.5`
```
"axisLabel": {
      "formatter": "function (value) { var newVal = Math.round(value * 10) / 10; return newVal; }",
      "margin": 25,
      "showMaxLabel": true,
      "showMinLabel": true
}
```
Auch andere Funktionen  `parseFloat(value).toFixed(2)`  funktionieren nicht.

![image](https://user-images.githubusercontent.com/84818934/148724638-9adf1374-4ad9-4019-9df7-a739160c2dd8.png)

![image](https://user-images.githubusercontent.com/84818934/148724873-42457218-2f53-4c0a-8556-796b69bea05b.png)

**Comment by Zefau** [comment]
fixed with `v3.1.0-alpha.26`
