### ISSUE TITLE
Map Fehler?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1460]
`v3.0.5`
MAP funktioniert eigentlich, es kommt nur ein Fehler bei F12:
![image](https://user-images.githubusercontent.com/84818934/148819974-14ad7803-bb5f-40eb-b351-721a3bf0ef5c.png)

**Comment by Zefau** [comment]
Kannst du feststellen, bei welcher Aktion in jarvis der Fehler konkret auftritt?

**Comment by mcuiobroker** [comment]
`v3.0.7` tritt momentan nicht mehr auf. Ich schließe es erstmal.
