### ISSUE TITLE
Reading 0?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1461]
`v3.0.5`
Fehler kommt direkt nach F5:
![image](https://user-images.githubusercontent.com/84818934/148820181-1ed9c237-1914-4303-8930-e213db63c759.png)

Und etwas anderes, pack es hier mit rein:
![image](https://user-images.githubusercontent.com/84818934/148831817-74966c6a-f3f0-428e-b263-850ddf256e09.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.6-beta.0`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/148848937-a9c6de6d-5878-48af-a604-b64169d3748c.png)

**Comment by mcuiobroker** [comment]
Zurück auf v3.0.5 -> 
![image](https://user-images.githubusercontent.com/84818934/148850803-95cfcdfa-e96d-4959-8954-f11953667e2e.png)

![image](https://user-images.githubusercontent.com/84818934/148850849-1604a637-58fb-4f3b-81e1-71318995c9e1.png)

**Comment by Zefau** [comment]
Bei verification failed bitte Adapter upload

**Comment by mcuiobroker** [comment]
Hatte ich gemacht, hatte aber nichts gebracht. Jetzt installier ich gerade 3.0.7-beta.0 . Mal schauen.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/148950415-4b4dec59-a7fc-49e7-ab07-877ff84b93ad.png)

**Comment by Zefau** [comment]
Den Fehler kann ich nicht einordnen. Würde behaupten, dass das nicht von jarvis kommt, sondern einem iFrame?

Was machst du in jarvis, dass der Fehler auftritt?

**Comment by mcuiobroker** [comment]
Kommt aus dem TAB History, dort ist kein iFrame drin: 
weather, map, htmltable, statehtml, displayimage. statlist, chart, datetime, historygraph

  "icon": "chart-areaspline-variant",
        "title": "HiSTORY",
        "id": "acd37feb-1f50-4b88-9581-33965ecb7db2",

**Comment by mcuiobroker** [comment]
Jetzt kommt es auch beim TAB home0 und da wurde bei mir nichts geändert:
![image](https://user-images.githubusercontent.com/84818934/149038096-0f9d948c-b1da-42b3-bcb7-417f5786e614.png)

**Comment by mcuiobroker** [comment]
Nach F5:
![image](https://user-images.githubusercontent.com/84818934/149044779-cf231873-29e0-49c6-8724-5fb958acf913.png)

**Comment by mcuiobroker** [comment]
Im Firefox bekomme ich diese Fehlermeldungen:
![image](https://user-images.githubusercontent.com/84818934/149088798-465c4b08-92be-46e8-b1a6-8631a99ab9b7.png)

![image](https://user-images.githubusercontent.com/84818934/149088857-01cc8b11-85e2-4756-8628-1274bcdae914.png)

![image](https://user-images.githubusercontent.com/84818934/149088926-ad34feed-c432-4f5f-8bbb-5151bb293251.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by mcuiobroker** [comment]
Keine Fehler mehr.
Hattest du die Versionsnummer mit in die Error-Log-Anzeige (rote Seite) genommen?
Damit man direkt erkennen kann, welche Version installiert ist, wenn jemand einen Fehler hat.
