### ISSUE TITLE
Graph stellt default Einstullungen nicht wieder her

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1462]
v3.0.5

Wenn man beim Graph die Konfiguration für die Y-Achse verwendet, erscheint eine neue Spalte neben den Datenpunkten, wo man die Y-Achse wählen kann. Löscht man die Konfiguration für die Y-Achse dann verschwindet auch wieder die Spalte für die Y-Achse aber die eingestellten Werte bleiben erhalten und der Graph ist leer.

Wenn die Spalte verschwindet, sollten auch die Werte in den Einstellungen mit gelöscht werden.

**Comment by Zefau** [comment]
> Wenn die Spalte verschwindet, sollten auch die Werte in den Einstellungen mit gelöscht werden.

Die Einstellungen bleiben im Backend erhalten, werden im Frontend aber ignoriert und alles sollte in einem Chart angezeigt werden. Funktioniert es nach einem Reload auch nicht?

**Comment by stephan1827** [comment]
Leider nein, Graph ist immer noch leer.

<img width="660" alt="Bildschirmfoto 2022-01-12 um 06 05 20" src="https://user-images.githubusercontent.com/2972703/149067189-e7c44faa-2838-4a36-8ac8-624c2da6d556.png">

**Comment by Zefau** [comment]
Kannst du mal die Konfiguration screenshoten?

**Comment by Zefau** [comment]
Also beide Varianten (mit und ohne Y-Achsen-Konfiguration)

**Comment by stephan1827** [comment]
So sieht der Graph aus wenn er funktioniert.
<img width="1569" alt="Bildschirmfoto 2022-01-12 um 18 57 29" src="https://user-images.githubusercontent.com/2972703/149195899-d66e0925-a1d7-4c0f-aea3-e60bb59dd5d7.png">

Das ist die Konfiguration
<img width="1393" alt="Bildschirmfoto 2022-01-12 um 18 57 56" src="https://user-images.githubusercontent.com/2972703/149195960-214e67d4-b4b1-4988-91a0-924664f00e94.png">

Und das ist die Konfiguration der Y-Achse
<img width="711" alt="Bildschirmfoto 2022-01-12 um 18 58 04" src="https://user-images.githubusercontent.com/2972703/149196013-43b8574a-a6bd-41bc-8fba-5b67655c5159.png">

Wenn ich JSON Konfiguration entferne dann ist die Konfiguration für die Y-Achse weg.
<img width="1287" alt="Bildschirmfoto 2022-01-12 um 19 00 37" src="https://user-images.githubusercontent.com/2972703/149196244-bd1c7e87-c761-4103-b61a-c3b3260b8550.png">

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by stephan1827** [comment]
Sieht gut aus
