### ISSUE TITLE
Jarvis findet keine Verbindung

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1463]
3.0.6-beta.0

Nach dem Update auf die aktuelle Version über GitHub läuft Jarvis nicht mehr.
![grafik](https://user-images.githubusercontent.com/13101074/148895467-2b153ac7-cae7-470b-8c48-befbd8c47b62.png)

**Comment by dlehmann69iob** [comment]
der gleiche Fehler hier mit etwas anderen Fehlermeldungen.

![image](https://user-images.githubusercontent.com/79025492/148896712-f1cae378-4fd7-4787-a3fc-b17c9b815e77.png)

**Comment by Zefau** [comment]
- ist die Domain in der Whitelist?
- wurde Jarvis von ioBroker Dashboard aus aufgerufen mit der korrekten URL (da diese die Verbindungsdetails beinhaltet) ?

**Comment by dlehmann69iob** [comment]
Eine Whitelist habe ich nicht gepflegt. Ging bisher auch immer ohne.
Ich habe einmal iobroker über die URL aufgerufen. Der Fehler bleibt bestehen.

![image](https://user-images.githubusercontent.com/79025492/148900666-5e0c1eaf-e54f-4654-a89e-923b7d74ebad.png)

**Comment by Zefau** [comment]
Uploade bitte nochmal den Adapter.

**Comment by AFPass** [comment]
Die Meldung bleibt gleich.
Bis vor dem Update lief es.
Welche Whitelist? War bisher nicht notwendig.
Ja aus ioBroker Dashboard

**Comment by dlehmann69iob** [comment]
Meldungen bleiben nach Upload auch bei mir die Gleichen

**Comment by Zefau** [comment]
probiert mal bitte 3.0.6

**Comment by Bernd9000** [comment]
Hab das auch mal getestet, hab den gleichen Fehler.
Im IOB log steht:

jarvis.0 | 2022-01-11 10:33:43.371 | error | require(...).ht is not a function

**Comment by AFPass** [comment]
Auch mit 3.0.6. kommt der Fehler noch.
![grafik](https://user-images.githubusercontent.com/13101074/148918993-ef516e7d-d259-41ec-a271-787741d24eda.png)

**Comment by Bernd9000** [comment]
@Zefau Vielleicht in der vendor Groß und Kleinschreibung vertauscht ?
function ht / Ht /hT ?

**Comment by Zefau** [comment]
Jo, da ist das "building" schief gelaufen.

**Comment by Zefau** [comment]
`v3.0.7-beta.0`

**Comment by AFPass** [comment]
Update über GitHub installiert die Version 3.0.6. Ohne Beta

**Comment by AFPass** [comment]
Jup läuft jetzt

**Comment by dlehmann69iob** [comment]
ja läuft hier jetzt auch
