### ISSUE TITLE
Jarvis crashes

### ISSUE THREAD

**Issue by SiebeS91** [Zefau/ioBroker.jarvis#1464]
**Prerequisites / Voraussetzungen**
- node v14.18.2
- npm 6.14.15
- admin v5.2.3
- Jarvis v2.2.1

**Describe the bug / Beschreibe den Fehler**
Nachdem ich ein Modul von StateListe auf CustomHTML umgestellt habe, ist der Adapter gecrashed.
In der State Liste war ein Trennstreifen enthalten

**Screenshots**
![image](https://user-images.githubusercontent.com/94370199/148941926-d6a994dc-3e1c-406f-87f0-0fd6c02c3a7b.png)

**Comment by mcuiobroker** [comment]
Sicherung aus jarvis (Instanz) zurückholen. Grundsätzlich über den Wechsel nach v3 nachdenken.
![image](https://user-images.githubusercontent.com/84818934/148963562-97aecd9a-29d9-4edf-a8b8-a0232c156520.png)
