### ISSUE TITLE
Verfication failed

### ISSUE THREAD

**Issue by Matzeb15** [Zefau/ioBroker.jarvis#1465]
**Prerequisites / Voraussetzungen**
Node.js v14.18.2
Admin v5.2.3
jarvis v3.0.5
npm v6.14.15

**Describe the bug / Beschreibe den Fehler**
Nach dem Update des jarvis Adapters von 3.0.4 auf 3.05 wird mir nach kurzer Aufbau-Zeit der Fehler "Varification failed (App blocked) angezeigt. Leider gelange ich auch nicht in die Einstellungen damit der pro account überprüft werden kann, ist aber vorhanden.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/74245935/148947802-13b265fb-b20b-4787-86cc-5d5b55881c73.png)

**Comment by mcuiobroker** [comment]
Ist mit v3.07-beta.0 behoben.

**Comment by Matzeb15** [comment]
Passt. Vielen Dank
