### ISSUE TITLE
Icons fehlen

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1466]
In der Version 3.0.7-beta fehlen bei mir wieder einige Icons
![grafik](https://user-images.githubusercontent.com/13101074/148953824-5af708b5-1217-401d-97b2-7b47714d745f.png)

![grafik](https://user-images.githubusercontent.com/13101074/148953945-334f66c5-75b7-4f63-9af9-d17b7f2f1d74.png)

![grafik](https://user-images.githubusercontent.com/13101074/148954002-8e35c0dd-f493-4689-8252-9c66c7b30967.png)

**Comment by Zefau** [comment]
mit `v3.0.7` sollte es passen

**Comment by AFPass** [comment]
Ja passt.
Den Fehler gab es schon einmal. Andere Ursache?
