### ISSUE TITLE
Geräte ID wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#1467]
Version 3.0.7 beta

Die ID der Geräte wird nicht mehr angezeigt. Ich meine damit die lange Zahl.
![grafik](https://user-images.githubusercontent.com/13101074/148955491-2143dab3-5046-4bef-b5a7-38c4d488c5fb.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/148956062-0717f77f-5b37-402d-8bf6-02109eb031d7.png)

**Comment by AFPass** [comment]
> ![image](https://user-images.githubusercontent.com/84818934/148956062-0717f77f-5b37-402d-8bf6-02109eb031d7.png) Mit der Maus über das Kopier-Icon fahren, Dann wird die ID sichtbar. Oder kopieren.

Das hab ich auch schon entdeckt. Aber bisher wars da, jetzt nicht mehr.

Dann sollte aber auch die Sortierung nach Name und nicht ID sein. Aber das ist ein anderer Issue ;-)
