### ISSUE TITLE
Jarvis crashes after update

### ISSUE THREAD

**Issue by Kielemnascharo** [Zefau/ioBroker.jarvis#1469]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
Admin 5.2.3
Jarvis 3.0.6
nodejs 14.18.3
nodjs  14.18.3
(lief bis zum heutigen update auf 3.0.6 einige Wochen stabil ohne probleme auf 3.0.x

**Describe the bug / Beschreibe den Fehler**
Log:
jarvis.0 | 2022-01-11 19:17:18.647 | error | require(...).ht is not a function

Jarvis http://192.168.178.37:8082/jarvis/index.html#/0/

**Screenshots**

____

**Please note that bug reports may be closed if the information above are not given!**
![Bildschirmfoto 2022-01-11 um 19 36 14](https://user-images.githubusercontent.com/97550185/149001677-9dc0b9f2-7ef5-4ef9-b6fa-436efacae698.png)

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Schimi1983** [comment]
habe das selbe... beim  restart vom Adapter kommt

"<html>
<body>


jarvis.0 | 2022-01-11 19:51:13.209 | error | require(...).ht is not a function
-- | -- | -- | --



</body>
</html>"

im log

**Comment by Schimi1983** [comment]
über "die katze" bekomme ich nur die beta.0

**Comment by Zefau** [comment]
sorry, jetzt

**Comment by Schimi1983** [comment]
bei mir funktioniert es wieder (mit der beta.1)
