### ISSUE TITLE
Theming

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#147]
Allow to override all styles provided by [Material UI](https://material-ui.com/customization/theming/).

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/117

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/512100

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/512100
https://forum.iobroker.net/post/513107

**Comment by duczz** [comment]
Iconsfarbe von "themeColorPrimary": "#1f1f1f", lösen
![image](https://user-images.githubusercontent.com/25475385/99155701-89a50d00-26ba-11eb-9973-6431df523fb2.png)
