### ISSUE TITLE
 Error: Verification failed

### ISSUE THREAD

**Issue by lemflo** [Zefau/ioBroker.jarvis#1470]
**Prerequisites / Voraussetzungen**
- jarvis v3.0.7-beta.0
- admin 5.2.3
- npm 8.3.0
- nodejs 14.18.2

Debug-Console:
[error.log](https://github.com/Zefau/ioBroker.jarvis/files/7849117/error.log)

**Describe the bug / Beschreibe den Fehler**
Wenn ich jarvis starte wird mir für 5 Sekunden die korrekte Seite angezeigt, anschließend erscheint der Fehler "Error: Installation inconsistent" und kurz danach "Error: Verification failed"
Das Problem tritt bei mehreren Endgeräten (Handy, Tablet, PC) und Browsern (Samsung, Chrome, Firefox) auf.
Neustart vom ioBroker und Neuinstallation von Jarvis bringt keine Veränderung.

**Screenshots**
![screenshot](https://user-images.githubusercontent.com/97549237/149003217-2d325a51-4da1-4c27-b1db-eb8c03b355d8.jpg)

**Comment by Zefau** [comment]
probier mal bitte `v3.0.7-beta.1`

**Comment by Zefau** [comment]
Sorry, jetzt

**Comment by lemflo** [comment]
Leider keine Änderung.

**Comment by Schimi1983** [comment]
probiere die beta.1 nochmal zu installieren (über die Katze).. beim ersten mal hat er bei mir auch nochmal die 0 installiert (wahrscheinlich war ich "zu schnell")

**Comment by lemflo** [comment]
Die Instanz wird bei mir als beta.1 eingezeigt, in der debug-Console begrüßt er mich noch als beta.0 - das wird aber bestimmt nur ein Schönheitsfehler sein.
Trotzdem bekomme ich nach (ziemlich genau) 5 Sekunden den roten Bildschirm.

**Comment by lemflo** [comment]
Vielen! Dank, es lag am Web-Adapter.
Nach Neustart funktioniert es.

**Comment by wired-ed** [comment]
Moin, habe leider das gleiche Problem und weder Neustart jarvis + web Adapter, noch Reboot haben geholfen :-( Fehlermeldung anbei.

Kann ich noch was anderes versuchen? Vielen Dank!

![image](https://user-images.githubusercontent.com/75878370/149079771-e969758e-4e9a-427c-97f9-956d2b8cb2f7.png)

**Comment by mcuiobroker** [comment]
Welche Version ist denn installiert?

**Comment by Zefau** [comment]
Bitte unbedingt auf 3.0.7 gehen

**Comment by wired-ed** [comment]
Mit 3.0.7 läuft es wieder, wunderbar, besten Dank für den schnellen Support! 🙏👍
