### ISSUE TITLE
Absturz / Timeout beim Laden von Jarvis

### ISSUE THREAD

**Issue by SebastianSchultz** [Zefau/ioBroker.jarvis#1471]
**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]
V3.0.4 aber auch mit der aktuellen Beta und der 3.0.5 habe ich das Gleiche Verhalten.

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Jarvis fängt erst an zu laden beim Aufruf (Ladebalken sichtbar), irgendwann sieht es jedoch so aus:

![image](https://user-images.githubusercontent.com/12255583/149017217-64262bed-3c35-4437-8fa6-e27c42a6d627.png)

Hier ein Browser-Log:

`app.ffec0caf.js:1 App Welcome to jarvis v3.0.3
app.ffec0caf.js:1 App Using instance 0.
app.ffec0caf.js:1 21:03:08 | INFO | CONNECTION | Connecting to http://192.168.178.241:8400 (#1)...
app.ffec0caf.js:1 21:03:08 | INFO | SOCKET | Connected to http://192.168.178.241:8400.
app.ffec0caf.js:1 21:04:09 | WARN | SOCKET | MESSAGE TIMEOUT:  9da077b7-70f8-4adc-9e64-e6c9ca2c7e66 Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:04:09 | WARN | SOCKET | MESSAGE TIMEOUT:  2b67e573-d5c1-49f5-b479-8e63d86f037f Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:04:09 | WARN | SOCKET | MESSAGE TIMEOUT:  b396a121-710a-4886-9876-f19ad011bda9 Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:05:10 | WARN | SOCKET | MESSAGE TIMEOUT:  161e0a75-a7e6-42e0-91b6-5fc20b57ad7a Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 App-lUZ53KTivl TIMEOUT Error: TIMEOUT
    at app.ffec0caf.js:1
(anonymous) @ app.ffec0caf.js:1
index.html#/0/:1 Failed to decode downloaded font: http://192.168.178.241:8082/jarvis/fonts/materialdesignicons-webfont.606b1642.woff2
index.html#/0/:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
app.ffec0caf.js:1 21:06:11 | WARN | SOCKET | MESSAGE TIMEOUT:  446cea18-bce7-4b15-9a79-8e2d53c9bdee Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 App-PQfG1vrOa7 TIMEOUT Error: TIMEOUT
    at app.ffec0caf.js:1
(anonymous) @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:06:11 | WARN | SOCKET | MESSAGE TIMEOUT:  bfb2dcb4-c628-4672-8967-542a4cc8909c Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 App-GAcA7qDpf5 TIMEOUT Error: TIMEOUT
    at app.ffec0caf.js:1
(anonymous) @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:06:11 | WARN | SOCKET | MESSAGE TIMEOUT:  07f5ae82-7c8c-469e-8adb-0952a91d9051 Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 App-Ro6cAsoL86 TIMEOUT Error: TIMEOUT
    at app.ffec0caf.js:1
(anonymous) @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:06:11 | WARN | SOCKET | MESSAGE TIMEOUT:  bd050b58-7bd9-438c-9290-fa3607d53746 Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 App-McGn2K9ZAg TIMEOUT Error: TIMEOUT
    at app.ffec0caf.js:1
(anonymous) @ app.ffec0caf.js:1
app.ffec0caf.js:1 Notifications Notifications is only available to Pro!
(anonymous) @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:07:12 | WARN | SOCKET | MESSAGE TIMEOUT:  bf5ce3c7-c63c-4921-905c-a397c30c7d86 Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:07:12 | WARN | SOCKET | MESSAGE TIMEOUT:  620b58e4-deee-4052-a2de-95fbbb1aa4da Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 App-AmgnhGejwn TIMEOUT
(anonymous) @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:07:12 | WARN | SOCKET | MESSAGE TIMEOUT:  d68390a7-8126-441b-8405-498911fadb37 Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:07:12 | WARN | SOCKET | MESSAGE TIMEOUT:  5bad2091-3b4c-42cd-a1f3-e4869305c1b9 Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 21:07:12 | WARN | SOCKET | MESSAGE TIMEOUT:  e03a3625-f539-45ea-b65e-d1ca44a685be Object
_message @ app.ffec0caf.js:1
app.ffec0caf.js:1 Uncaught TypeError: Cannot read properties of undefined (reading 'sendUsageData')
    at Object.callback (app.ffec0caf.js:1)
    at u.processIncomingMessage (app.ffec0caf.js:1)
    at app.ffec0caf.js:1
index.html#/0/:1 Failed to decode downloaded font: http://192.168.178.241:8082/jarvis/fonts/materialdesignicons-webfont.606b1642.woff2
index.html#/0/:1 OTS parsing error: Failed to convert WOFF 2.0 font to SFNT
`

Downgrade auf 3.0.4. sowie Upgrade auf die aktuelle Beta (via Github) brachten leider keine Änderung.

**Comment by Zefau** [comment]
bitte 3.0.7 von Github installieren

**Comment by SebastianSchultz** [comment]
Mit der 3.0.7-beta.1 besteht das Problem leider auch.

**Comment by Zefau** [comment]
Sollte behoben sein damit. Bitte Web Adapter restarten und sonst mal rebooten.

**Comment by Zefau** [comment]
Hast du noch Fehler im ioBroker Log?

**Comment by SebastianSchultz** [comment]
Hat sich erledigt. Durch den Neustart des Web Adapters nach Update auf die 3.0.7 geht es nun.
Vielen Dank für die schnelle und absolut kompetente Hilfe!
