### ISSUE TITLE
Jarvis startet nicht / Timed Out

### ISSUE THREAD

**Issue by ZwiebelCebula** [Zefau/ioBroker.jarvis#1472]
**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
v3.0.6
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]
![image](https://user-images.githubusercontent.com/75208564/149028383-65509214-26c1-417d-968f-960de7f9a925.png)

**Describe the bug / Beschreibe den Fehler**
Wenn ich Jarvis im iO-Broker starten möchte, bekomme ich lediglich eine Time-Out Meldung.

Ich möchte hier einmal dazu anmerken, dass ich Jarvis heute das erste Mal gestartet habe und dementsprechend vielleicht einen "Anfängerfehler" begangen habe. Dies ist auch der Grund warum ich ein neues Issue aufgemacht hab, obwohl ich gesehen habe das ein anderes mit einem ähnlichen Fehler bereits eröffnet wurde...

**Screenshots**

![image](https://user-images.githubusercontent.com/75208564/149028076-4bbc8612-5432-4d18-90e8-4224e8b5aea1.png)

Nach einiger Zeit wird das "delay" dann auch zum Timeout.

Hier auch einmal meine Einstellungen bei socketiO und dem web adapter (dort habe ich bisher alles auf "Werkeinstellungen" gelassen):
![image](https://user-images.githubusercontent.com/75208564/149028773-fea3b77b-fcf3-4b5d-b7cc-02c5e89d51f6.png)
![image](https://user-images.githubusercontent.com/75208564/149028839-7e86af70-6fff-40fe-a467-c1b2776ad1d9.png)

Vielen Dank vorab für die Hilfe!

**Comment by mcuiobroker** [comment]
Bitte `v3.0.7` installieren.

**Comment by ZwiebelCebula** [comment]
> 

Auch wenn es mir ein wenig peinlich ist.. Aber wie installiert man die neuste Version?

Bisher habe ich dies immer über den IOBroker unter den Adaptern gemacht. Dort finde ich lediglich die Version v3.0.6.

Repository ist natürlich auf "latest" gestellt und IOBroker hatte ich auch nochmal neugestartet.

![image](https://user-images.githubusercontent.com/75208564/149030654-e144fe8e-03b3-4a6d-bd50-af9cfe1e8f41.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/149031313-66245241-eccd-455f-a01d-bf491ab353a5.png)
![image](https://user-images.githubusercontent.com/84818934/149031348-e7b39a13-6f6a-4f1d-b4dd-b3037bccba57.png)

**Comment by CC1337** [comment]
Läuft ioBroker in Docker und ist der zusätzliche Port 8084 freigegeben?
Ich spreche aus Erfahrung :)

**Comment by ZwiebelCebula** [comment]
Mit der aktuellen Version hat es geklappt. Danke für die Info zum manuellen Download. Das Wissen hatte gefehlt. ;)
