### ISSUE TITLE
v3: DP icon property is now case sensitive even if boolean

### ISSUE THREAD

**Issue by CC1337** [Zefau/ioBroker.jarvis#1473]
In 3.0.5 (and other 3.0.x) icons disappeared on most homematic devices because it has boolean values UPPERCASED in the objects.
In v2 this worked as icon property of the power state of a device:
`{"true":"lightbulb-on","false":"lightbulb-ouline"}`
In v3 icon is empty now. It needs to be changed to
`{"TRUE":"lightbulb-on","FALSE":"lightbulb-ouline"}`
to be shown again.

Maybe it makes sense to compare this case insensitive.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by CC1337** [comment]
Sieht gut aus!
