### ISSUE TITLE
v3: Widget height calculation is wrong for horizontal StateList

### ISSUE THREAD

**Issue by CC1337** [Zefau/ioBroker.jarvis#1474]
On v3.0.5, the horizontal StateList height calculation is wrong, it seems that it still considers vertical layout.
Maybe there is an option I did not find yet?

How it looks by default:
![grafik](https://user-images.githubusercontent.com/4866744/149032142-792234d9-25f7-4fb9-a827-6a9a0876d18f.png)

How it looks for horizontal=true
![grafik](https://user-images.githubusercontent.com/4866744/149032388-5e981fa4-3b5e-4280-b970-53dc4608babe.png)
I expected it to be not higher than necessary...
Some settings:
![grafik](https://user-images.githubusercontent.com/4866744/149032423-34578c99-6227-44dd-9043-e044810ad5ed.png)
![grafik](https://user-images.githubusercontent.com/4866744/149032448-8d6da223-f4d2-46e9-b550-78a50aecf2e8.png)
![grafik](https://user-images.githubusercontent.com/4866744/149032481-db37ab86-3b0c-4688-a174-84c8dbe72ac9.png)

**Comment by Zefau** [comment]
In v3 the widget won't adapt its height to the content because it is part of a grid and may span across rows and / or columns.

You have to adjust the height in the layout configuration. The content itself will be scaled if necessary.
