### ISSUE TITLE
CSS TAB href funktioniert nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1475]
Vorher konnte man mit den Einstellungen in CSS den TAB-Hintergrund beeinflussen. Dies geht mit v3.0.7 nicht mehr.

[href="#/home0"] {
	background: green;
}
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/beispiele/styles/besondere-klassen/jarvis-tab (das war v2)
jarvis-tab-#tabname geht auch nicht mehr

**Comment by Zefau** [comment]
Das `[href="#/home0"]` habe ich geändert. Dafür sollte die Performance nun besser sein. Die Tabs werden nun initial geladen und nicht erst beim Klick darauf.

`jarvis-tab-#tabname` kann ich wieder einführen.

**Comment by mcuiobroker** [comment]
jarvis-tab-#tabname gerne wieder einführen.
Aber wegen der Performance habe ich keine Verbesserung festgestellt.
Auf dem Handy dauert es ca 2 Sekunden, bis die neue TAB Seite geladen wird, wenn man auf den neuen TAB klickt.
Sind die TAB geladen, dauert es beim Umschalten nur 1 Sekunde.
Auf dem PC ist es etwas schneller.

**Comment by Zefau** [comment]
Ich weiß gar nicht mehr, auf welchem Element die CSS Klasse `jarvis-tab-..` war. Auf dem Tab oben in der Tab-Leiste?

**Comment by mcuiobroker** [comment]
Auf den Tab oben in der Tab-Leiste, ja.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by mcuiobroker** [comment]
Funktioniert. Danke.
