### ISSUE TITLE
disconnect ins log schreiben

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1476]
Im Log stehen die connect-Daten, aber nicht disconnected:
Eine Ergänzung wäre sinnvoll.
![image](https://user-images.githubusercontent.com/84818934/149093428-cdee3bbc-b5c9-4d80-81bb-3863fb01ea23.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by mcuiobroker** [comment]
disconnect-Meldung kommt jetzt, komisch nur dass teilweise disconnected nacheinander erscheint?
![image](https://user-images.githubusercontent.com/84818934/150358937-cb18f7cb-a3dc-4c16-905e-7958bb6c87e9.png)

**Comment by Zefau** [comment]
Kann vorkommen, z. B. wenn mit mehreren Browsern verbunden.
