### ISSUE TITLE
Anzeige von Labels im Frontend

### ISSUE THREAD

**Issue by Ma-Kra** [Zefau/ioBroker.jarvis#1477]
Jarvis v3.0.7

Im Frontend, z.B. StateList, erscheinen bei mir jetzt plötzlich die Bezeichner der Geräte und nicht mehr wie vorher der gewünschte Text.

![image](https://user-images.githubusercontent.com/97596876/149117233-38b63441-0b3a-4592-a575-ebfafe312d05.png)

![image](https://user-images.githubusercontent.com/97596876/149117444-c3bc658e-ad3a-4e7b-b749-d69ddc0240fa.png)

Im Gerät wurden hier anscheinend der Inhalt von Name und Label getauscht. Aus meiner Sicht macht es so Sinn und ich bin auch gerne bereit das in allen Geräten wieder zu tauschen (habe noch nicht so viele ;-)). Aber dann sollte das Verhalten im Widget genauso sein, denn dort wird der Name und nicht das Label im Frontend angezeigt.

![image](https://user-images.githubusercontent.com/97596876/149118091-7aeef5a6-5c6a-4c7f-8e2a-bd49ce842158.png)

**Comment by Zefau** [comment]
Das ist so gewollt. Geht leider nicht anders. Bitte in der Geräte-Konfiguration die neue Option "Actions" nutzen, um die Bezeichner zu drehen. Dann sollte es wieder passen.

**Comment by Ma-Kra** [comment]
Danke für den Tip, die Funktion habe ich glatt übersehen. Das Drehen in den Geräten hat wunderbar geklappt. Kann das in den Widgets auch angepasst werden, dass dort auch das Label im Frontend angezeigt wird anstatt dem Namen?

**Comment by Zefau** [comment]
Das sollte bei den Widgets schon so sein? Kannst du das mal screenshoten? Konfiguration vs. Frontend

**Comment by Ma-Kra** [comment]
Ist schon oben zu sehen:
erster Screenshot: Frontend mit Anzeige "Außenbereich"
dritter Screenshot: Konfiguration des Widgets: Name "Außenbereich", Label "light_Outdoor"

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by Ma-Kra** [comment]
Anzeige im Widget und im Popup ist jetzt korrekt, alles sauber.
