### ISSUE TITLE
Beim schalten der Farbe einer Philips Lightbar kommt der Fehler State value to set for "deconz.0.Lights.8.hue" has to be type "number" but received type "string"

### ISSUE THREAD

**Issue by Asche1985** [Zefau/ioBroker.jarvis#1481]
Hi ich verwende die Version 3.0.7 und wenn ich die Farbe meiner Lightbar ändere, dann kommt im IoBroker Log der Fehler 
State value to set for "deconz.0.Lights.8.hue" has to be type "number" but received type "string". 
Ist das ein Bug oder habe ich nur was falsch eingestellt. 
Das hat auf jedenfall zur Folge, dass ich keine Farben mehr einstellen kann.
Hier noch ein Screenshot, damit du die Einstellungen auch sehen kannst. 
![LightbarEinstellung](https://user-images.githubusercontent.com/50178286/149226199-a69783ff-a1b5-473f-8799-5ae2c1013613.PNG)

**Comment by Asche1985** [comment]
Wenn noch weitere Infos benötigt werden, dann liefere ich die natürlich nach :-)

**Comment by mcuiobroker** [comment]
Steht im LOG ein jarvis davor oder ein deconz, sehr wahrscheinlich deconz. Damit wäre dann der deconz-Adapter dafür zuständig.
![image](https://user-images.githubusercontent.com/84818934/149314043-5d77b7af-0d90-47a5-924e-b5bee0b59d80.png)

**Comment by Asche1985** [comment]
Nee ist ein Jarvis davor.  Hier noch ein Screenshot
![image](https://user-images.githubusercontent.com/50178286/149326723-824f075c-01ee-4533-b346-c270c509f7f1.png)

**Comment by Asche1985** [comment]
Den Deconz Adapter würde ich fast schon ausschließen, den wenn ich die Farbwerte der Lampe im IoBroker direkt im Deconz Adapter überschreibe funktioniert alles. Irgendwie scheint also das mappen von Jarvis in den Deconz Adapter Probleme zu machen. 

Hab noch etwas im Log herumgesucht und auch noch folgende Einträge gefunden. 

![image](https://user-images.githubusercontent.com/50178286/149327168-37f6653b-4ac5-468a-be2c-25878075dbe5.png)

Interessant ist dann auch noch der invalid Length Eintrag. Ich weiß aber gerade nicht, ob dieser direkt was mit dem Fehler hier zu tun hat.

**Comment by Zefau** [comment]
Ich kann den Fehler bzgl. hue bestätigen.

**Comment by Zefau** [comment]
`Invalid IV length` kommt von einer fehlgeschlagenen Verschlüsselung. Aktuell setzt nur das Calendar Modul die Verschlüsselung ein, um das Passwort zu verschlüsseln.

Behebt das Neusetzen des Passworts den Fehler bzw. die Meldung im Log?

**Comment by Asche1985** [comment]
Dann warte ich mit voller Vorfreude auf die Fix Version :-) 
Wegen der "Invalid IV length" habe ich das Passwort neu gesetzt und es scheint weg zu sein. Ich werde es aber beobachten und gegenbenenfalls ein neues Ticket dann für dich erstellen.

**Comment by Zefau** [comment]
behoben mit `v3.0.8-beta.0`

**Comment by Asche1985** [comment]
Ich habe heute die 3.0.9 installiert und es funktioniert alles jetzt wieder. Super :-) Ich schließ das Ticket dann.
