### ISSUE TITLE
Fehler Darstellung StateList horizontal

### ISSUE THREAD

**Issue by jvpihole** [Zefau/ioBroker.jarvis#1482]
Bei Version 3.07 ist mir beim Widget StateList folgendes aufgefallen. Einstellung:
![image](https://user-images.githubusercontent.com/59318539/149228702-0531f5dd-700a-43d0-9a68-6a55c655172e.png)

Label und State liegen übereinander. Darstellung:
![image](https://user-images.githubusercontent.com/59318539/149228824-33c1ce6a-2ae0-4be9-b44c-189f11bf62f6.png)

Hat mit 3.05 noch funktioniert.

**Comment by Zefau** [comment]
behoben mit `v3.0.8-beta.0`

**Comment by jvpihole** [comment]
Alles klar, geht wieder. Danke.
