### ISSUE TITLE
In CSS das Popup von einem StateList-DP mit WidgetId beeinflussen.

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1483]
Wie kann man in CSS das Popup von einem StateList-DP beeinflussen.
Was funktioniert:
```
.jarvis-device-1d042465-1f5a-4be9-92c6-d0142a7b6d0b .jarvis-StateListItem-Popup .jarvis-StateListItem-Body {
 display: none !important;
}
  
.jarvis-device-1d042465-1f5a-4be9-92c6-d0142a7b6d0b .jarvis-StateListItem-Popup .q-item__section--avatar {
 display: none !important;
}
```
damit ist es aber nur vom Gerät abhängig.
Ich möchte es auch vom Widget abhängig machen, so dass nur bei Popup bezogen auf das gewählte Widget die Einschränkung gilt.
Es gibt einen Selektor `widget` der wird aber als [Object object] angezeigt, so dass ich im CSS-Selektor anscheinend darauf keinen Zugriff habe?
![image](https://user-images.githubusercontent.com/84818934/148283667-4077c91b-a85a-47ae-81ec-bbc20105e4ce.png)
Soll ich dafür ein Feature Request erstellen?

Das funkioniert nicht:
```
.jarvis-device-1d042465-1f5a-4be9-92c6-d0142a7b6d0b .jarvis-StateListItem-Popup [widget="e9778391-5859-4cca-a562-f5c21ff2ec18"] .jarvis-StateListItem-Body {
	display: none !important;
}

.jarvis-device-1d042465-1f5a-4be9-92c6-d0142a7b6d0b .jarvis-StateListItem-Popup  [widget="e9778391-5859-4cca-a562-f5c21ff2ec18"] .q-item__section--avatar {
	display: none !important;
}
```

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/discussions/1437_

**Comment by Zefau** [comment]
Verstehe nicht, was du benötigst. Du willst das Popup stylen, aber abhängig vom Widget. Was für ein Widget meinst du? Das Popup ist immer vom Modul StateList und zeigt ein Gerät. Hier kommen keine Widgets zum Tragen?

**Comment by mcuiobroker** [comment]
Habe ich mehrere Widget, wo das Gerät genutzt wird, möchte ich es einem Widget ausgeblendet haben, im anderen nicht.
```
.jarvis-device-1d042465-1f5a-4be9-92c6-d0142a7b6d0b .jarvis-StateListItem-Popup .jarvis-StateListItem-Body {
 display: none !important;
}
```
Dies zieht in allen Widgets, wo das Gerät genutzt wird.
