### ISSUE TITLE
Hue-Slider funktioniert nicht mit Kommawerten für Hue-Farbwert

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#1484]
Habe leider immer noch den Fehler mit dem HUE-Slider. Verwende die neueste Version (v3.0.7).

Steuere ich direkt im Datenpunkt "HUE" wird der modifizierte Wert an die Lampe übertragen:

Trage ich dort beispielsweise 150 ein, so wird nach kurze Zeit der Wert von der Lampe (in etwa) bestätigt:
![image](https://user-images.githubusercontent.com/61848539/149293461-aee05be7-69e9-497a-a29f-e1b3b2ea6d0b.png)

Nehme ich den Schieberegler
![image](https://user-images.githubusercontent.com/61848539/149293525-f02c4d4b-5053-4c68-bdb9-19aef77c80d2.png)

so wird in den Datenpunkt folgendes geschrieben:

![image](https://user-images.githubusercontent.com/61848539/149293594-77d77ed7-a994-4232-bffe-1609c2572f35.png)

Konfig sieht so aus:

![image](https://user-images.githubusercontent.com/61848539/149293653-e51f96bd-dd36-4070-96f6-76bc9b09302a.png)

![image](https://user-images.githubusercontent.com/61848539/149293684-c23918f6-c419-4476-9754-13a9a2408229.png)

**Es liegt sicherlich daran, dass die Lampe einen Kommawert für den Datenpunkt Hue liefert. Ich habe eine andere Installation mit einer anderen Lampe (ohne Kommawert), da funktioniert alles.**

**Comment by Zefau** [comment]
behoben mit `v3.0.8-beta.0`

**Comment by uwe72** [comment]
Hat funktioniert, danke schön!!
