### ISSUE TITLE
Module: DispayImage - aktualisiert sich nicht mehr / Module: DispayImage - Image no longer updates

### ISSUE THREAD

**Issue by Mike-Meiers** [Zefau/ioBroker.jarvis#1485]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
3.0.6
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Die Bilder der Webcam werden nicht mehr aktualisiert. In älteren Versionen funktionierte die Aktualisierung ohne Probleme. 
Der Aktualisierungsintervall steht auf 1 sec.

The webcam images are no longer updated. In older versions the update worked without any problems.
The update interval is 1 sec.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/97680681/149343533-1340db5c-12f5-4aa1-8d13-bf95ab396e3b.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
> In älteren Versionen funktionierte die Aktualisierung ohne Probleme.

In welcher Version funktionierte es denn noch? Hast du mal die `Refresh Methode` gewechselt?

**Comment by Mike-Meiers** [comment]
Ja die andere Refresh Methode habe ich schon probiert.
Leider kann ich dir die letzte funktionierende Version nicht sagen.
Es war auf jeden Fall bevor durch ein Update das Design der Oberfläche angepasst wurde.

**Comment by Zefau** [comment]
änder mal bitte das Aktualisierungsintervall auf 10s. Ändert das etwas?

**Comment by Zefau** [comment]
@funky4t die Methode in v2 ist `zufällige Nummer der URL anfügen`. Es war in v2 die einzige Option, daher gab es keine dedizierte Auswahl.

Der wesentliche Unterschied ist, dass in v2 im `<img />` Tag gerendert wird und im v3 als Hintergrundbild. Das scheint Probleme zu verursachen. Bei mir geht es (leider). 

Nutzt du Firefox oder Chrome?

**Comment by Zefau** [comment]
@funky4t @Mike-Meiers ladet ihr das Bild mit einer `http` und habt jarvis aber in `https` laufen?

**Comment by funky4t** [comment]
Moin,

nutze den Safari auf Monterey, hab es aber eben auch im Firefox aufm Mac getestet, gleiches Verhalten, kein Update.
IoBroker läuft `https` und jarvis in `http` in der Tat wie vermutet, diese Konstellation war aber bei Jarvis 2 auch gegeben.

**Comment by Zefau** [comment]
Du hast ioBroker s auf https aber jarvis normalerweise auf http? Aber auch mit http aktualisiert es bei dir nicht?

**Comment by funky4t** [comment]
Also der Broker selbst läuft über `https://192.168.x.y:8081`, Jarvis erreiche ich über `http://192.168.x.y:8082` Ist das irgendwie eher ungewöhnlich? Ich frag mal doof, bin nach wie vorher tendenziell "Anwender": Kann/soll ich Jarvis auf https: "umstellen", finde da adhoc keine Option für? Oder meinst du den Broker mal testweise auf `http` umstellen um zu sehen, ob die Cams refresht werden?

Die Cams geben ihr Bild über `http` an Jarvis, nur eben nicht wie gehofft, alle 5s...

Ich habe den "alten" Broker mit Jarvis 2 immer noch aktiv auf Raspberry im gleichen Netz während ich auf NUC mit Jarvis 3 umgezogen bin. Auf die Art versuche ich grade die Visu von Jarvis2 auf Jarvis 3 umzubauen. Auf der "alten" Kombi Rapsberry mit Jarvis2 aktualisier die Cams einwandfrei, iObroker `https` und Jarvis2 `http` die Cams sind unverändert....

**Comment by Mike-Meiers** [comment]
> @funky4t @Mike-Meiers ladet ihr das Bild mit einer `http` und habt jarvis aber in `https` laufen?

Läuft beides mit http da nur intern erreichbar.

**Comment by Mike-Meiers** [comment]
> @funky4t die Methode in v2 ist `zufällige Nummer der URL anfügen`. Es war in v2 die einzige Option, daher gab es keine dedizierte Auswahl.
> 
> Der wesentliche Unterschied ist, dass in v2 im `<img />` Tag gerendert wird und im v3 als Hintergrundbild. Das scheint Probleme zu verursachen. Bei mir geht es (leider).
> 
> Nutzt du Firefox oder Chrome?

Bei der Methode "Zufällige Nummer anfügen" wird das Bild gar nicht mehr geladen.
Das ist Browserunabhängig. Auch auf meinem Android Smartphone aktualisiert sich das Bild nicht mehr.

**Comment by funky4t** [comment]
Hab bei mir den Broker testweise mal auf `http` umgestellt, bringt keine Änderung bei mir.
Das wäre analog zu @Mike-Meiers Aussage `beides http`
 ABER: Verhalten mit `Zufällige Nummer` hab ich nach erhöhter Refreshzeit ein anderes Verhalten. Jarvis lädt das neue Bild scheinbar über ein "Leerbild", sprich kurzeitig verschwindet das Cam Bild, es bleibt der graue Hintergrund vom Widget, dann kommt ein neue aktuelleres Bild. Setze ich die Refresh Rate auf 1s bleibt das Bild permanent grau, scheinbar erfolgt die nächste Aktualisierung BEVOR das vorangegangene Bild gezeigt wurde. Bei V2 wurde das neue Bild scheinbar im Hintergrund geladen und ohne "Greyscreen" direkt über das alte gelegt. Man hat eigentlich nur gesehen, wie der Timestamp im Cam Bild sich geändert hat. Jetzt "blinkt" quasi das ganze Bild je nach Refreshtime....
 
Ich hoffe ich konnte es halbwegs deutlich beschreiben...

**Comment by Mike-Meiers** [comment]
> Hab bei mir den Broker testweise mal auf `http` umgestellt, bringt keine Änderung bei mir. Das wäre analog zu @Mike-Meiers Aussage `beides http` ABER: Verhalten mit `Zufällige Nummer` hab ich nach erhöhter Refreshzeit ein anderes Verhalten. Jarvis lädt das neue Bild scheinbar über ein "Leerbild", sprich kurzeitig verschwindet das Cam Bild, es bleibt der graue Hintergrund vom Widget, dann kommt ein neue aktuelleres Bild. Setze ich die Refresh Rate auf 1s bleibt das Bild permanent grau, scheinbar erfolgt die nächste Aktualisierung BEVOR das vorangegangene Bild gezeigt wurde. Bei V2 wurde das neue Bild scheinbar im Hintergrund geladen und ohne "Greyscreen" direkt über das alte gelegt. Man hat eigentlich nur gesehen, wie der Timestamp im Cam Bild sich geändert hat. Jetzt "blinkt" quasi das ganze Bild je nach Refreshtime....
> 
> Ich hoffe ich konnte es halbwegs deutlich beschreiben...
> 
> Hab mal zwei kurze Video gemacht, V3 vs V2
> 
>  Bildschirmaufnahme.2022-01-16.um.18.05.18.mov 
>  Bildschirmaufnahme.2022-01-16.um.18.04.40.mov



> Hab bei mir den Broker testweise mal auf `http` umgestellt, bringt keine Änderung bei mir. Das wäre analog zu @Mike-Meiers Aussage `beides http` ABER: Verhalten mit `Zufällige Nummer` hab ich nach erhöhter Refreshzeit ein anderes Verhalten. Jarvis lädt das neue Bild scheinbar über ein "Leerbild", sprich kurzeitig verschwindet das Cam Bild, es bleibt der graue Hintergrund vom Widget, dann kommt ein neue aktuelleres Bild. Setze ich die Refresh Rate auf 1s bleibt das Bild permanent grau, scheinbar erfolgt die nächste Aktualisierung BEVOR das vorangegangene Bild gezeigt wurde. Bei V2 wurde das neue Bild scheinbar im Hintergrund geladen und ohne "Greyscreen" direkt über das alte gelegt. Man hat eigentlich nur gesehen, wie der Timestamp im Cam Bild sich geändert hat. Jetzt "blinkt" quasi das ganze Bild je nach Refreshtime....
> 
> Ich hoffe ich konnte es halbwegs deutlich beschreiben...
> 
> Hab mal zwei kurze Video gemacht, V3 vs V2
> 
>  Bildschirmaufnahme.2022-01-16.um.18.05.18.mov 
>  Bildschirmaufnahme.2022-01-16.um.18.04.40.mov

Habe das dann auch mal gerade probiert.
Leider kommt bei meinen Cams so nach 10s das Greyscreen und kein aktualisiertes Bild.
So lässt sich immerhin erkennen, dass eine Aktualisierung versucht wird :-)

**Comment by funky4t** [comment]
@Mike-Meiers meinst du nach zwischenzeitlichen Refreshes und dann 10s oder bei Refreshzeit 10s und dem ersten Bild? Könnte mir vorstellen, dass wenn deine Cam ne "dünne" WLAN Connection hat, sie >10s für Refresh braucht....analog zu meinen, die <3s auch im Greyscreen "verschwinden"...stell doch testweise mal höher auf 20s oder so?
Mit 4 aktiven Cams auf der Jarvis Seite hab ich mich jetzt selbst hypnotisiert... 😵‍💫 aber wir scheinen uns der Ursache zu nähern... 👍🏼

**Comment by Zefau** [comment]
schaut bitte nochmal mit `v3.0.10-beta.2`

**Comment by funky4t** [comment]
Bei mir läufts mit der Version wieder flüssig wie in alter Weise! 👍🏼👍🏼 Besten Dank

**Comment by funky4t** [comment]
#1514 scheint mit der 10beta .2 reingekommen zu sein.
Ich kann jetzt leider auch im Widget keine StateList mehr auswählen, das ging zuvor einwandfrei...

**Comment by Zefau** [comment]
Bitte die Issues nicht mischen

**Comment by Mike-Meiers** [comment]
So jetzt bin endlich dazu gekommen mit der 3.0.10-beta3  zu testen.
Meine Webcam Bilder werden jetzt wieder mit der Methode "Zahl anhängen" aktualisiert.
Super, vielen Dank dafür.
