### ISSUE TITLE
setOff: "1" setzt die SwitchAction nicht auf false

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1486]
`v3.0.8-beta.0`
Im Gerät ist folgender Eintrag:
![image](https://user-images.githubusercontent.com/84818934/149452944-aa32da75-8a19-402e-a067-18c0cbb618a9.png)
Im Layout
![image](https://user-images.githubusercontent.com/84818934/149453008-06306cfb-5664-4249-991c-5704edb9956c.png)
Frontend Off-Schalter ist blockiert:
![image](https://user-images.githubusercontent.com/84818934/149453114-cd4b9dd4-37ba-4498-8989-6c395f9818a6.png)
Ist ein anderer Wert als 1 angezeigt, so wird zwar beim "Schalten" auf "false", der Wert auf 1 gesetzt, aber der Schalter nicht auf "false"-Position?
Eigentlich müsste doch der Schalter auf die "false"-Position gehen, oder?

**Comment by Zefau** [comment]
Nein. `false` ist 0. Müsstest du sonst mit `off` ummappen.

**Comment by mcuiobroker** [comment]
Problem ist, wenn ich den Wert "128" mit dem Schalter einschalte und er gesetzt wird, geht das WLED an auf bri 128. Wenn ich jetzt den Wert "1" setze mit jarvis, wird dieser nicht mehr umgesetzt. -> WLED bekommt den Wert "1", schaltet die bri aber nicht um.
Gehe ich in WLED und setze dort den Wert manuell, dann wird die bri umgesetzt.

**Comment by Zefau** [comment]
Also wenn der Wert gesetzt wird dann arbeitet jarvis korrekt. Warum der Adapter den Wert nicht verarbeitet weiß ich nicht.

Weitergegeben wird immer gleich und ohne `ack`.

**Comment by Bernd9000** [comment]
Meine Meinung:
Ist eigentlich auch gut so das ein ausgeschalteter Schalter in jarvis nur den Wert "0" oder "false" annehmen kann.
Man stelle sich vor jemand schaltet in jarvis ein Schalter auf "aus" weil er in der Elektroinstallation arbeiten muß und dann ist doch noch Spannung vorhanden. Klar, als Elektriker muß man die 5 Sicherheitsregeln beachten, aber wie viele tun das ?
Hat also auch Sicherheitsgründe.

Anderseits kann man verstehen, das der Wunsch da ist einen speziellen Schalter zu haben mit dem man solche Dinge wie MCU angegeben hat machen kann. Aber das muß dann per Script gelöst werden.
