### ISSUE TITLE
jarvis 2.Instanz Start aus den Instanzen zeigt Inhalt von 1.Instanz

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1487]
`v3.0.8-beta.0`
- [ ] Edge

2.Instanz
![image](https://user-images.githubusercontent.com/84818934/149457425-a1ac337a-f1ec-47cb-a165-e2300500fc9f.png)

Nach F5 wird der Inhalt von der 2. Instanz angezeigt
![image](https://user-images.githubusercontent.com/84818934/149457628-14bcb1c2-c07f-4f46-87bd-d2d16daa198c.png)

- [ ] Chrome

![image](https://user-images.githubusercontent.com/84818934/149457731-c911f5cd-c9f8-4578-af46-d17572e0f90c.png)

Firefox zeigt es richtig an

1.Instanz
![image](https://user-images.githubusercontent.com/84818934/149457563-72ceb2a3-ae6e-4cd9-afdd-6b2ac7060924.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by mcuiobroker** [comment]
Passt. Danke.
