### ISSUE TITLE
StateList Einträge filtern funktioniert nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1488]
Mit dem Eintrag (mit/ohne ") kommt keine Änderung in der Ansicht.
![image](https://user-images.githubusercontent.com/84818934/149467966-91245b4a-4046-4f28-8539-237bf55fb68d.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by mcuiobroker** [comment]
Er filtert jetzt, kommt aber mit Error hoch und meldet es auch für 3 Sekunden unten.
![image](https://user-images.githubusercontent.com/84818934/149608699-939074dc-0415-4ba8-bc5c-33f1e297d8bc.png)

**Comment by Zefau** [comment]
Deine `"` müssen raus

**Comment by mcuiobroker** [comment]
Hatte ich rausgenommen, dann war die Fehlermeldung bevor ich rausgenommen hatte. ok.
