### ISSUE TITLE
Einstellungen setzen sich automatisch auf default Werte zurück

### ISSUE THREAD

**Issue by Cinigua** [Zefau/ioBroker.jarvis#1489]
- v.3.07
- Änderungen die man in den Einstellungen durchgeführt hat wie z.B. "Titel im Browser", "Sidebar Mini Mode" werden nach bestimmter Zeit wieder automatisch zurückgesetzt.

Nachdem man die oben beschriebenen Werte geändert hat, sind diese am nächsten Tag ca.12h? wieder auf default Werte zurückgesetzt. Die Funktion ist somit nicht brauchbar, oder man muß jeden Tag diese wieder anpassen.

**Comment by Zefau** [comment]
Hast du Skripte laufen, die auf Datenpunkte in `jarvis.0.settings` zugreifen?

**Comment by Zefau** [comment]
Ich kann den Fehler jedenfalls so nicht bestätigen. Habe mehrere Sachen angepasst und diese bleiben unverändert bestehen.

Die Einstellungen werden in `jarvis.0.settings` gespeichert. Die Frage wäre, ob der Datenpunkt bei dir noch anderweitig gesetzt wird?

**Comment by Cinigua** [comment]
Hi also ich schalte nur nach Astrofunktion den Darkmode an und wieder aus. Vermutlich liegt hier das Problem?
<img width="617" alt="Bildschirmfoto 2022-01-14 um 17 15 08" src="https://user-images.githubusercontent.com/97731412/149548573-c3ed0e19-b336-4507-8e69-0bf710008ef4.png">
!

**Comment by Zefau** [comment]
Das wird der Fehler sein. Ich werde mal schauen

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.8-beta.1`

**Comment by Cinigua** [comment]
> schau nochmal mit `v3.0.8-beta.1`

Habe es gerade installiert und gebe Rückmeldung, nach dem Test!

**Comment by Cinigua** [comment]
Bugfix hat geklappt und die Änderungen bleiben jetzt gespeichert. Danke
