### ISSUE TITLE
"Konfiguration&Hilfe" wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by Marko1963** [Zefau/ioBroker.jarvis#1490]
Version: 3.0.0 (gleiches Fehlerbild nach Update auf 3.0.7)

Fehler:
Meine Seite lädt ganz normal und ist auch normal bedienbar.

Console vom Laden der Seite
![image](https://user-images.githubusercontent.com/81255941/149514743-7231b552-bfcf-483f-8db2-c182c72b3c90.png)

Wähle ich dann links unten "Konfiguration&Hilfe"
![image](https://user-images.githubusercontent.com/81255941/149514240-6ded047c-2813-4d12-92ed-5c3843f96032.png)

zuckt am auf der Seite nur kurz die Leiste mit oben mit "Geräte" "Widgets" etc. auf und unten die Leiste mit "abbrechen" "speichern", dann bleibt die komplette Seite grau.
![image](https://user-images.githubusercontent.com/81255941/149515327-155c7132-2984-4a5f-bb45-5929a90aff48.png)

Habe es auf mehreren Displays versucht, Verschiedene Skalierungen, Vollbild,...
Habe versucht aus den Backups die Widgets und Layouts die funktioniert haben wieder herzustellen.
Habe die Adapter neu gestertet.
Habe den Pi neu gestartet
Habe von 3.0.0 auf 3.0.7 geupdated

**Comment by mcuiobroker** [comment]
In der Adresszeile oben hinter configuration/devixes oder /Layout ergänzen

**Comment by Marko1963** [comment]
> In der Adresszeile oben hinter configuration/devices oder /layout ergänzen

Danke!
Was ist der Grund dass es sich so verknoten kann?
Hätte es geholfen den browsercash zu leeren?

**Comment by Zefau** [comment]
Sollte mit deinem Update auf 3.0.7 nicht mehr vorkommen.
