### ISSUE TITLE
Impossible to move Widgets inside a Tab

### ISSUE THREAD

**Issue by HeliosXenon** [Zefau/ioBroker.jarvis#1491]
Jarvis: v3.0.7

I updated to v3.0.7 and now its impossible to move Widgets inside a Tab.
I tried even the browsers Opera, Chrome, Firefox

Wenn ich versuche ein Widget zu verschieben markiert es mir nur den Text.
Ist es wirklich ein Bug oder gibt es eine andere Methode Widgets zu verschieben?

![Unbenannt](https://user-images.githubusercontent.com/95089684/149518917-e59c776f-c691-4e8d-8e4d-e81ca4f2f82f.PNG)

**Comment by Zefau** [comment]
Geht bei mir. Hast du Fehler in der Browser Konsole (F12) ?

**Comment by Zefau** [comment]
Ich schließe. Einfach wieder öffnen, wenn es wieder auftritt und einen Screenshot der Browser Konsole (F12) posten.
