### ISSUE TITLE
Version in Fehler Log

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1493]

**Comment by Zefau** [comment]
mit `v3.0.8` integriert

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/149625850-066e9d13-bb54-4fea-b674-a77ce4d26f2a.png)

**Comment by Zefau** [comment]
Da gibt es doch 4 Log-Einträge. Welche sind denn das?

Ich kann gar nichts prüfen ohne Socket-Verbindung - leider.

**Comment by Zefau** [comment]
`v3.0.9-beta.0`
