### ISSUE TITLE
Unberechtigter Zugang zu den Einstellungen

### ISSUE THREAD

**Issue by Marko1963** [Zefau/ioBroker.jarvis#1495]
v3.0.7

Habe eine Hintertüre gefunden, die ich aktuell nicht abschaffen kann.
Ich möchte den Zugang zu den Einstellungen sperren, da am Display im Hausflur natürlich keiner irgendwelche Einstellungen vornehmen soll/darf.

Ich kann nun den Button "Konfiguration&Hilfe" ausblenden lassen.
![image](https://user-images.githubusercontent.com/81255941/149617795-4c17447c-b3b0-42f6-98bb-62bad5dd5688.png)
![image](https://user-images.githubusercontent.com/81255941/149617981-0fcb3202-5771-4e15-8547-707f7e828eaf.png)

Jedoch gibt es keine Einstellung den Button "Pro Account" ausblenden zu lassen.
![image](https://user-images.githubusercontent.com/81255941/149617795-4c17447c-b3b0-42f6-98bb-62bad5dd5688.png)
Wenn ich auf "Pro Account" klicke kann man direkt in die anderen Einstellungen wechseln.

Das ist für mich eine Sicherheitslücke.

**Comment by Zefau** [comment]
mit `v3.0.8` behoben
