### ISSUE TITLE
HistoryGraph ignoriert Splitline Parameter

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1496]
v3.0.8-beta.1

Ich habe versucht die Hintergrundfarbe des Graphen über splitLine.lineStyle zu ändern, aber die Farbe änder sich nicht. Auch Splitline.Show wird ignoriert wenn man versucht die Linie ganz auszublenden.

```
[
  {
    "position": "left",
    "name": "Temperatur",
    "nameRotate": 90,
    "nameLocation": "center",
    "nameGap": 25,
    "min": 15,
    "max": "25",
    "splitLine": {
      "lineStyle": {
        "color": "['#aaa', '#ddd']"
      }
    }
  },
  {
    "position": "right",
    "name": "Ventil",
    "nameRotate": 270,
    "nameLocation": "center",
    "nameGap": 25,
    "min": 0,
    "max": 100,
    "splitLine": {
      "lineStyle": {
        "color": "['#aaa', '#ddd']"
      }
    }
  }
]
```

**Comment by Zefau** [comment]
Die Konfiguration der Achsen wird unverändert übernommen, insofern wird das kein jarvis Fehler sein, sondern eine falsche Konfiguration.

Schau dir die Dokumentation unter https://echarts.apache.org/en/option.html#yAxis.splitLine genau an.
`splitLine` unterstützt keine Hintergrundfarbe. Ggf. meinst du `areaStyle`, siehe https://echarts.apache.org/en/option.html#yAxis.splitArea.areaStyle?

**Comment by mcuiobroker** [comment]
color wird unterstützt:
![image](https://user-images.githubusercontent.com/84818934/149619693-e5efc35e-36c0-47c2-9f27-677d8f33af54.png)

**Comment by stephan1827** [comment]
Denke auch das sollte gehen, splitLine.Show geht auch nicht

<img width="722" alt="Bildschirmfoto 2022-01-15 um 12 17 17" src="https://user-images.githubusercontent.com/2972703/149619796-d9b602f9-4b20-49a8-b2c8-8a7c7340e3dd.png">

**Comment by Zefau** [comment]
Ok, ist ein Fehler in jarvis. Ich gestehe es widerwillig ein. ;-)

**Comment by Zefau** [comment]
`v3.0.8`

**Comment by stephan1827** [comment]
Die Farben gehen aber show geht noch nicht oder habe ich das falsch formatiert?

    "splitLines": {
      "show": "false"
    }

**Comment by Zefau** [comment]
Boolean ohne `"`

**Comment by stephan1827** [comment]
Habe ich auch probiert

    "splitLines": {
      "show": false
    }

geht auch nicht :-/

**Comment by stephan1827** [comment]
Alles zurück, show scheint doch zu gehen. Habs jetzt noch ein paar mal probiert und jetzt geht es.

**Comment by mcuiobroker** [comment]
Wenn jetzt alles unterstützt werden soll, warum funktioniert dann "formatter" callback nicht?

**Comment by Zefau** [comment]
Das ist eine Funktion. Die muss erst geparsed werden.
