### ISSUE TITLE
Beim schalten falscher Wert im Datenpunkt

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1497]
`v3.0.8`
Erneut, wie schon bei v3,03 und 3.05, lassen sich WLAN Steckdosen nicht schalten.

In den "Datenpunkt Eigenschaften" der Geräte in jarvis habe ich folgendes stehen:
{"on":"ON","off":"OFF"}

Fehler in jarvis:
Beim schalten wird "true" vom Type boolean gesendet.
"Datenpunkt Eigenschaften" wird scheinbar ignoriert.

Fehler im IOB durch jarvis.0 und mqtt.0 :
State value to set for "mqtt.0.cmnd.Steckdose-3.POWER" has to be type "string" but received type "boolean"

**Comment by Zefau** [comment]
Merkwürdig, `setOn` / `setOff` nutzt du nicht, richtig?

**Comment by Zefau** [comment]
Und du beziehst dich nach wie vor auf `SwitchAction`, richtig?

**Comment by Bernd9000** [comment]
Korrekt, `SwitchAction`.
`setOn` und `setOff` brauchte ich bei den vorherigen jarvis Versionen nicht eintragen, ging ohne Angabe.
Teste ich gleich mal.....

![Unbenannt](https://user-images.githubusercontent.com/77005685/149638112-867ae689-ead2-4b4f-a9aa-417161b008b3.jpg)

**Comment by Zefau** [comment]
Brauchst nicht eintragen. Ging nur darum, den Fehler einzugrenzen. Versuch mal mit `v3.0.9-beta.0`.

**Comment by Bernd9000** [comment]
Ja, funktioniert wieder. :-)
