### ISSUE TITLE
setTabId Umschaltung funktioniert nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1498]
`v3.0.8`
Tab-Umschaltung mit setTabId funktioniert nicht mehr.
Im Log nach Benutzung der setTabId:
![image](https://user-images.githubusercontent.com/84818934/149626972-befdb79a-59d2-4864-be2f-dc2116df54d6.png)
Er setzt die Browserzeile
http://192.168.178.89:8082/jarvis/index.html#/home0
aber er schaltet nicht um.

**Comment by Zefau** [comment]
Die Client ID ist falsch. Bitte löschen.

**Comment by Zefau** [comment]
Die Client ID hat nun das Format `IP-Adresse`-`Browser`.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/149627329-66cc8fc3-6b99-47f9-837e-bf1c2121fa53.png)

**Comment by mcuiobroker** [comment]
Vielleicht passt es #1330 mit einzubinden?

**Comment by Zefau** [comment]
Jo, schon geschehen ;-)

**Comment by Zefau** [comment]
`v3.0.9-beta.0`

**Comment by mcuiobroker** [comment]
Browser werden synchron geschaltet. Soll das so? Wenn man auf einem Browser der TAB wechselt, wird auf allen anderen auch der TAB ausgewählt. Ist eigentlich nicht so gut, da man dann verfolgen kann, was einer an einem anderen Tablet so macht?

**Comment by Zefau** [comment]
> Browser werden synchron geschaltet

Das soll (eigentlich) nicht so. Passiert aber auch nur je Gerät, nicht Geräte-übergreifend. Also zwei Browser auf einem Gerät, da `setTabId` ja auf das Gerät zielt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.9-beta.1`

**Comment by Zefau** [comment]
sorry, da war ich zu schnell, bitte nochmal `v3.0.9-beta.1` drüber installieren

**Comment by mcuiobroker** [comment]
Springt nachwievor auf verschiedenen Browsern um, wenn ich einem die setTABid setze.
Beim Auswählen des TABs ist es jetzt nicht mehr synchron.
Aber der automatische Reload des Clients ist nicht mehr, war noch mit beta.0 ok.

**Comment by mcuiobroker** [comment]
`v3.0.9` läuft. Prima. Danke.
