### ISSUE TITLE
v3.0.7 MediaControl - Alexa.2.0

### ISSUE THREAD

**Issue by sir0drake** [Zefau/ioBroker.jarvis#1499]
Hallo Zefau
ich habe mehr als die beiden in der DropDown-Liste angezeigten Alexa-Endgeräte.
Ist das gewollt limitiert oder muss ich etwas setzen/schalten, um alle Alexa-Endgeräte angezeigt zu bekommen ? 

v3.0.7

![image](https://user-images.githubusercontent.com/77205165/149626880-a897392b-4d98-4504-8e04-1690c4f5e4c9.png)

viele Grüße & Dank

**Comment by Zefau** [comment]
Es werden nur Player angezeigt, die `alexa2.0.Echo-Devices.<ID>.online` auf `true` haben und einen vorhandenen Datenpunkt (unabhängig vom Wert) `alexa2.0.Echo-Devices.<ID>.Player.currentState`.

**Comment by sir0drake** [comment]
Hallo Zefau,
genau das wars !
ich musste meine Alexa-Cookies neu ziehen und dann wurden die Online-States entsprechend korrekt gesetzt.

vielen Dank für deine Hilfe
