### ISSUE TITLE
Hide log and configuration button on small screens

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#15]
On small screens the buttons to open the log and the configuration disturb the clean look of jarvis. Besides that I believe that especially the configuration is done on larger screens. Maybe you could also think about changing the log pop-up to an tab of the configuration pop-up. An option to hide the buttons on small screens would be good.

**Comment by Zefau** [comment]
Should be fixed with `v0.1.2`. Could you please test and verify? Thanks

**Comment by braindead1** [comment]
In v0.1.2 this works as expected.
