### ISSUE TITLE
Log wird geflutet

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1501]
Keine Ahnung was da plötzlich los ist ? 

![image](https://user-images.githubusercontent.com/22169074/149641347-56275d08-cb17-4ca7-a2b7-f3868f49f0fa.png)

**Comment by Zefau** [comment]
Version?

**Comment by Zefau** [comment]
Zieh mal eine Zeile komplett ab. Die Informationen sind etwas dünn.

**Comment by ma-gu-16** [comment]
(v3.0.7-beta.0)

dahinter stand eigentlich nur noch der geräte name , jedes geräts. also einige. 

hat sich aber glaub gelöst. Ich hatte noch irgendwo im chrome paarmal jarvis geöffnet in der konfig. vermutlich alte versionen. 
kann das zu den logs geführt haben?

**Comment by Zefau** [comment]
Geh mal auf 3.0.8 bei Gelegenheit.

Die Logs kommen daher, dass eine Nachricht von jarvis an das Backend nicht beantwortet wird, daher der Message Timeout. Das Kommando sehe ich aber nicht, woran es scheitert. Aber ja, kann an unterschiedlichen / alten Versionen liegen.
