### ISSUE TITLE
jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1502]
`v3.0.9-beta.0`

Gibt es für diesen Fehler eine Erklärung ?
Ist Heute Morgen einmal aufgetreten.

`<html><body>

jarvis.0 | 2022-01-16 07:12:28.474 | info | Found Backups for widgets.
-- | -- | -- | --
jarvis.0 | 2022-01-16 07:12:28.465 | info | Found Backups for devices.
web.0 | 2022-01-16 07:12:28.468 | debug | system.adapter.jarvis.0: logging true
jarvis.0 | 2022-01-16 07:12:28.458 | info | Found Backups for layout.
jarvis.0 | 2022-01-16 07:12:28.457 | info | Found Backups for settings.
jarvis.0 | 2022-01-16 07:12:28.457 | info | Found Backups for styles.
jarvis.0 | 2022-01-16 07:12:28.455 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2022-01-16 07:12:28.417 | info | starting.  Version 3.0.9-beta.0 in  C:/Software/iobroker/SmartHome/node_modules/iobroker.jarvis, node:  v14.18.2, js-controller: 3.3.22
host.ServerSmartHome) | 2022-01-16 07:12:27.676 | info | host.Server(SmartHome) instance system.adapter.jarvis.0 started with pid 7016
web.0 | 2022-01-16 07:11:57.662 | debug | system.adapter.jarvis.0: logging false
host.ServerSmartHome) | 2022-01-16 07:11:57.656 | info | host.Server(SmartHome) Restart adapter system.adapter.jarvis.0 because enabled
host.ServerSmartHome) | 2022-01-16 07:11:57.655 | error | host.Server(SmartHome) instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
jarvis.0 | 2022-01-16 07:11:57.119 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
jarvis.0 | 2022-01-16 07:11:57.119 | info | terminating
jarvis.0 | 2022-01-16 07:11:57.119 | info | Adapter stopped und unloaded.
jarvis.0 | 2022-01-16 07:11:57.118 | error | Cannot read property 'ip' of undefined
jarvis.0 | 2022-01-16 07:11:57.118 | error | TypeError:  Cannot read property 'ip' of undefined    at  ioWebSocket.eventFromClient  (C:\Software\iobroker\SmartHome\node_modules\iobroker.jarvis\lib\websocket.io.min.js:1:4231)     at ioWebSocketClient._parentMessage  (C:\Software\iobroker\SmartHome\node_modules\iobroker.jarvis\lib\websocket.io.min.js:1:6960)     at ioWebSocketClient.disconnect  (C:\Software\iobroker\SmartHome\node_modules\iobroker.jarvis\lib\websocket.io.min.js:1:8946)     at Socket.<anonymous>  (C:\Software\iobroker\SmartHome\node_modules\iobroker.jarvis\lib\websocket.io.min.js:1:8138)     at Socket.emit (events.js:400:28)    at Socket.emitReserved  (C:\Software\iobroker\SmartHome\node_modules\iobroker.jarvis\node_modules\socket.io\dist\typed-events.js:56:22)     at Socket._onclose  (C:\Software\iobroker\SmartHome\node_modules\iobroker.jarvis\node_modules\socket.io\dist\socket.js:358:14)     at Client.onclose  (C:\Software\iobroker\SmartHome\node_modules\iobroker.jarvis\node_modules\socket.io\dist\client.js:239:20)     at Socket.emit (events.js:412:35)    at Socket.onClose  (C:\Software\iobroker\SmartHome\node_modules\iobroker.jarvis\node_modules\engine.io\build\socket.js:303:18)
jarvis.0 | 2022-01-16 07:11:57.117 | error | uncaught exception: Cannot read property 'ip' of undefined
jarvis.0 | 2022-01-16 07:11:26.994 | info | Client with IP 192.168.0.48 disconnected.
jarvis.0 | 2022-01-16 07:05:26.952 | info | Client with IP 192.168.0.48 connected.
jarvis.0 | 2022-01-16 07:05:26.934 | info | Client connecting...

</body>
</html>`

**Comment by Zefau** [comment]
fixed mit `v3.0.10-beta.0`

**Comment by Bernd9000** [comment]
:-) Super, das ging ja schnell.
Werde das weiter beobachten, ich schliesse mal hier.

**Comment by Bernd9000** [comment]
Reopen...
Jetzt hab ich folgendes im IOB Log:

`<html><body>


jarvis.0 | 2022-01-16 14:19:23.784 | info | Client with IP (unknown) connected.
-- | -- | -- | --
jarvis.0 | 2022-01-16 14:19:23.775 | info | Client connecting...
jarvis.0 | 2022-01-16 14:19:12.520 | info | Client with IP (unknown) connected.
jarvis.0 | 2022-01-16 14:19:12.505 | info | Client connecting...
jarvis.0 | 2022-01-16 14:19:11.782 | info | Client with IP (unknown) disconnected.
jarvis.0 | 2022-01-16 14:19:02.307 | info | Client with IP (unknown) connected.
jarvis.0 | 2022-01-16 14:19:02.293 | info | Client connecting...


</body>
</html>`

**Comment by Bernd9000** [comment]
Ist aber wohl nur ein Anzeigefehler im Debug Log ?

![Unbenannt](https://user-images.githubusercontent.com/77005685/149662023-22a6693b-af67-41bc-99a8-9f82e65e9020.jpg)

**Comment by Zefau** [comment]
`v3.0.10-beta.1`

**Comment by Bernd9000** [comment]
`v3.0.10-beta.1`
Beim connected wird die IP jetzt angezeigt.
Bei disconnected steht noch unknown

`<html><body>


jarvis.0 | 2022-01-16 15:48:49.108 | info | Client with IP (unknown) disconnected.
-- | -- | -- | --
jarvis.0 | 2022-01-16 15:48:26.403 | info | Client with IP 192.168.0.100 connected.
jarvis.0 | 2022-01-16 15:48:26.392 | info | Client connecting...
jarvis.0 | 2022-01-16 15:48:25.754 | info | Client with IP (unknown) disconnected.
jarvis.0 | 2022-01-16 15:47:53.215 | info | Client with IP 192.168.0.100 connected.
jarvis.0 | 2022-01-16 15:47:53.202 | info | Client connecting...


</body>
</html>`

**Comment by Zefau** [comment]
Meine Flüchtigkeitsfehler :-\

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10-beta.2`

**Comment by Bernd9000** [comment]
Jo, sieht gut aus,
