### ISSUE TITLE
Tab Label mittig zentrieren

### ISSUE THREAD

**Issue by tofrie** [Zefau/ioBroker.jarvis#1505]
Man kann das Icon deaktivieren, den Text bekommt man nicht weg. Wenn man das Menü links nutzt wäre es schön, wenn man es deaktivieren und nur die Hamburgernavigation nutzen kann.

**Comment by Zefau** [comment]
Du willst die Tab-Leiste ausblenden, wenn nur ein Tab drin ist?

**Comment by tofrie** [comment]
Genau, so kann man es sagen. Das Icon kann man ja bereits ausblenden. Den Text leider nicht. Dieser ist bei ausgeblendeten Icon unten fixiert und wandert nicht nach oben.

**Comment by Zefau** [comment]
Aber willst du "nur" den Text nach oben geschoben haben oder soll die komplette Tab-Leiste ausgeblendet werden?

**Comment by tofrie** [comment]
Ich denke den Text als „Überschrift“ nach oben schieben sollte ausreichen.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10-beta.1`

**Comment by tofrie** [comment]
Top, sieht richtig gut aus.

**Comment by mcuiobroker** [comment]
@tofrie Kannst du bitte genau darstellen, was du, wo gemacht hast? Mit Ergebnis-Bild. Ich würde es in die Doku mit aufnehmen. Danke

**Comment by tofrie** [comment]
Ich habe mir die oben genannte Version installiert. Anschließen habe ich die Seite und den Tab ausgewählt. Das Feld Tab Icon habe ich leer gelassen und anschließend wurde mir nur der Name angezeigt. Das Ergebnis sieht so aus:
![Bildschirmfoto 2022-01-17 um 08 53 48](https://user-images.githubusercontent.com/60553702/149729263-eb7aa00f-4973-482d-8540-46f938321340.png)

**Comment by mcuiobroker** [comment]
Ich dachte du hattest nur ein TAB pro Seite und wolltest das TAB-Label als die "Überschrift" zentriert über die TAB-Zeile?

**Comment by tofrie** [comment]
In der vorherigen Version war die Schrift unten, jetzt ist sie zentriert nach oben gewandert.
