### ISSUE TITLE
Refresh bei Display Image Widget funktioniert nicht

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#1508]
Hi Zefau,

erstmal großes Lob, ein bissl hatte ich mich auch nach Sprung von Jarvis 2 auf 3 "erschrocken", aber wenn man die Logik mal blickt, ist es doch ziemlich ähnlich "hands-on" wie Jarvis 2 mit weitaus besseren Darstellungsoptionen.

Ich bin auf der 3.0.10 beta .0 und hab festgestellt, dass leider meine Webcams im Image Display Widget nicht refresht werden. Ich hab die Einstellungen 1:1 aus Jarvis2 kopiert, Bilder sind auch ja da und werden bei erzwungenem Refresh der Site per F5 auch upgedatet. Nicht jedoch automatisch ohne den erzwungenen F5 Reload. 

Ich hab alle drei Refresh Methoden, also mit Zahl, Leerzeichen und ganz leer probiert. Das Webcam Bild ändert sich nicht, gut zu sehen am Timestamp im Webcam Bild. Bei Methode NUMMER oder ganz ohne Input, sehe ich nach dem F5 Refresh kurz das Bild und dann verschwindet gänzlich es anstatt zu aktualisieren.... 
Bei Methode LEERZEICHEN bleibt es vorhanden, aktualisiert aber nicht in der 5s Vorgabe.

In Jarvis 2 hab ich nur die 5s hinterlegt, eine Methode gabs da ja nicht. Dort laufen die Cams top und ich bekomme alle 5s einen neues Bild.

Bug oder sitzt der Error vorm Bildschirm? :)
LG Sven

**Comment by Zefau** [comment]
Duplikat zu https://github.com/Zefau/ioBroker.jarvis/issues/1485
