### ISSUE TITLE
Zeilen ausblenden funktioniert initial nicht beim Öffnen von Popups

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#1509]
Version v3.0.9

Folgendes Feature funktioniert nicht (immer):
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/styles/statelist-1/zeile-ausblenden#body-stil-geraet

Leider funktionierte dies mit der 3.0.7 Version nicht 100% zuverlässig. Manchmal refreshte die Zeile einfach nicht, d.h. sie hätte eigentlich ausgeblendet werden müssen (und eine andere Zeile eingeblendet).

Aus diesem Grunde ging ich heute auf die 3.0.9 Version. Da funktioniert es leider noch deutlich schlechter. Beim Öffnen des Popups wird die Bedingung
![image](https://user-images.githubusercontent.com/61848539/149668186-f8f7e7c5-21e6-461e-ba67-fd498cbe5632.png)
gar nicht mehr ausgewertet. Wenn ich dann die Bedingung ändere, funktioniert es. Beim erneute Öffnen des Popups wieder das gleiche, dass die Bedingung nicht ausgewertet wird.

Video habe ich auch dazu gemacht (hier kann ich es nicht hochladen), dann Link bitte aus dem Post entnehmen:
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/992

Anmerkung von MCU: Hinweis, dass anscheinend nicht alle Elemente (Binding) in dem Array berücksichtigt werden. Er kürzt ein Binding-Array um ein Element, so wie es aussieht.
Wichtige Einträge sind:
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1002
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1010

Grundsätzlich soll so die Funktionsweise sein:

Aber nur grundsätzlich, wenn ich während der Popup offen ist den Schalter hin und herschalte funktioniert alles gut. Das sind die richtigen Zustände:

Schalter aus --> Weißmodus --> Farbtemperatur wird angezeigt
![image](https://user-images.githubusercontent.com/61848539/149668357-9153c813-da00-47a3-a667-1d46a06793ef.png)

Schalter ein --> RGB-Farbmodus --> Farbwert wird angezeigt
![image](https://user-images.githubusercontent.com/61848539/149668369-3687f333-6e35-4d03-93d9-206d4c5a50e1.png)

Nur wenn Popup geöffnet wird, werden eben Farbtemperatur UND Farbwert inital angezeigt. Erst nach dem ersten Betätigen des Schalters funktioniert es wieder korrekt.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.10-beta.3`

**Comment by uwe72** [comment]
Habe es gerade getestet. Konnte leider keinen Unterschied feststellen. Anbei ein Video (musste es leider in ein ZIP verpacken).
Hatte die neueste Version und auch F5 bzw. Inkogitio-Modus verwendet. Beim initialen öffnen sind immer beide Zeilen dargestellt (Fehler), erst wenn der Popup offen ist und ich dann die Bedingung (Schalter im Popup) ändere, funktioniert die Sichtbarkeitsteuerung der 2 Zeilen korrekt, d.h. immer eine ist ein bzw. ausgeblendet.

[FREITAG_Screen Recording (21.01.2022 08-52-15).wmv.zip](https://github.com/Zefau/ioBroker.jarvis/files/7911308/FREITAG_Screen.Recording.21.01.2022.08-52-15.wmv.zip)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10`

**Comment by uwe72** [comment]
Leider immer noch gleiches Verhalten, siehe Video.

[SONNTAG_Screen Recording (23.01.2022 20-04-06).wmv.zip](https://github.com/Zefau/ioBroker.jarvis/files/7921194/SONNTAG_Screen.Recording.23.01.2022.20-04-06.wmv.zip)

**Comment by Zefau** [comment]
änder mal bitte in `{"display":"none"}`, ändert das etwas?

**Comment by Zefau** [comment]
Wie zeichnest du die Videos auf?

**Comment by uwe72** [comment]
Ich kann es schon mal ändern, ich habe folgende EInstellungen: 
![image](https://user-images.githubusercontent.com/61848539/150697734-194e1a9b-2d8c-43e6-b3a5-1f0374ae0b6a.png)

**Comment by uwe72** [comment]
Das Tool heißt 
![image](https://user-images.githubusercontent.com/61848539/150697776-feeb87e0-17ea-4cb7-b2f7-a46f3719627e.png)

**Comment by Zefau** [comment]
Bei mir geht es mit folgendem Settings:

![image](https://user-images.githubusercontent.com/14368811/150697783-9fbc96a5-9003-4ed4-9893-2cf71fe11106.png)
![image](https://user-images.githubusercontent.com/14368811/150697790-2a2b68c4-265c-4e04-a31d-672cb3d41dc5.png)
![image](https://user-images.githubusercontent.com/14368811/150697797-3cd194e5-8864-493a-a848-455e2775eb54.png)

**Comment by uwe72** [comment]
ich schau genau auf dein setting. Ich habe halt "none !important"}}

**Comment by mcuiobroker** [comment]
Warum denn ==?

**Comment by Zefau** [comment]
`=` gibt es nicht und wird intern zu `==`. Sollte aber keinen Unterschied machen.

**Comment by Zefau** [comment]
Mit `!important` scheint es tatsächlich nicht zu gehen.

**Comment by uwe72** [comment]
Ich habe nun das !important weggelassen und nun funktioniert es! Wirklich ganz herzlichen Dank für diesen Fix! Jetzt kann ich richtig angreifen :-)

**Comment by Zefau** [comment]
Ich fixe das mit `!important` noch. Kannst es also sonst auch drin lassen, falls es noch irgendwo vorhanden ist.

**Comment by Zefau** [comment]
`3.0.11-beta.0`

**Comment by uwe72** [comment]
Ich gebe dir morgen früh final bescheid. Möchte noch, dass mein Bekannter testet. Bei mir hat es nun auch mit !important funktioniert.

**Comment by uwe72** [comment]
Passt soweit, danke! Wirklich großes Dankeschön!

**Comment by uwe72** [comment]
@Zefau 

Im Webbrowser funktioniert das Ein- und Ausblenden der Zeilen ohne Probleme.
Desöfteren kommt es aber bei Handys zur Situation, dass das binding nicht greift. Die Zeilen werden nicht mehr ein- und ausgeschalten. Leider ist das Verhalten und der Zeitpunkt wann das auftritt nicht reproduzierbar. Wenn man die App (Fully Kiosk)/Browser komplett schließt und neu aufmacht, geht es im Normalfall wieder.

Hast Du eine Idee, was ich noch probieren könnte?

**Comment by uwe72** [comment]
Ich versuche erst einmal selber das Thema einzugrenzen auf meiner Seite. Irgendwie hat es auch zu tun wenn mehrere Devices auf den gleiches "Schalter" (im popup) zeigen.

**Comment by uwe72** [comment]
@Zefau 

Habe nun im Fully Kiosk Browser eingestellt, dass er ab 60 Sekunden "idle" die Startseite neu laden soll (werde ich sicherlich noch erhöhen). Seitdem ist der Fehler nicht mehr aufgetreten. 

Bin mir schon ziemlich sicher, dass es daran liegt, dass wenn die Jarvis-Seite länger nicht benutzt wird, das Problem auftritt.
