### ISSUE TITLE
href ausblenden mit CSS funktioniert nicht mit Fully Kiosk Browser

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1510]
Wenn man im CSS folgenden Eintrag macht:
[href="#/home0"] {
	display: none !important;
}
blendet man dadurch den Eintrag im Menü aus
![image](https://user-images.githubusercontent.com/84818934/149670178-d5503e63-57fc-4243-b08d-041983c5b72b.png)
Ist es eingeblendet sieht es so aus:
![image](https://user-images.githubusercontent.com/84818934/149670216-7a37b7c3-c3f6-46c8-a335-a5630f94cf09.png)
Nun wird es aber auf dem Tablet zeitgleich nicht ausgeblendet.
Liegt am Fully Kiosk Browser.
Mit FireFox, Edge,Chrome ist der Eintrag weg.
Obwohl die Seite ausgeblendet ist, wird sie durch initiale Adresse (http://192.168.178.89:8082/jarvis/index.html#/home0) geladen.
Dann fehlt allerdings der erste TAB, der genauso heißt, wie der Eintrag im Menü.

Kann man automatisch initial zur nächsten Seite springen, wenn die aktuelle ausgeblendet ist?
![image](https://user-images.githubusercontent.com/84818934/149670747-762d269c-a2a0-453c-b2ac-670a1b93c7af.png)

**Comment by Zefau** [comment]
Bitte kein `href` als Sektor nehmen. Soll ich da eine Klasse reinmachen mit ID?

**Comment by mcuiobroker** [comment]
Ja gerne. Es geht mir darum, dass man den Eintrag im Menü ausblenden kann und die zugehörige Seite. 
Bislang werden auch wenn die Seite mit .jarvis-page-0980sd0sdf0 ausblende, bleibt die Tableiste von der Seite sichtbar.
Wenn möglich sollte auch initial die Seite automatisch wechseln, wenn die gewählte Seite über CSS ausgeblendet ist?

**Comment by Zefau** [comment]
mit `v3.0.10-beta.2` nun diverse zusätzliche CSS-Klassen, die du nutzen kannst

**Comment by Bernd9000** [comment]
Nur zur Info:
Ich hab da jetzt den Effekt das die Seitenleiste unterschiedliche Zeilenhöhen hat, genau die Zeilenhöhe die ich auf diesen Seiten angegeben hab.Ich vermute mal das ich die Zeilenhöhe jetzt genauer eingrenzen muß per css.

![Unbenannt](https://user-images.githubusercontent.com/77005685/149706863-9e2979a6-45d0-4231-9bf3-1a77399b4878.jpg)

**Comment by mcuiobroker** [comment]
Hier bräuchte man eine seitenabhängige Klasse: row nowrap .jarvis-header-#sideID ?
![image](https://user-images.githubusercontent.com/84818934/149714631-5788c2da-f919-4e57-b958-82f961850dbd.png)

**Comment by Zefau** [comment]
Fehlt jetzt irgendwo noch etwas oder kann dieses Issue zu?

**Comment by mcuiobroker** [comment]
Nein, das passt schon, hab es anders gelöst.
