### ISSUE TITLE
Jarvis nach Aktualisierung nicht mehr funktionsfähig

### ISSUE THREAD

**Issue by Jaschster** [Zefau/ioBroker.jarvis#1511]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- v3.0.9 Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- 
![image](https://user-images.githubusercontent.com/81528437/149676845-f6cdd8dd-7ce6-4bb9-b6a7-375d4a0d4b17.png) Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Nachdem ich heute die Aktualisierung von v3.0.7 auf v3.0.9 durchgeführt habe, erhalte ich leider immer eine Fehlermeldung, dass meine Installation inkonsistent sei.
Ich verfüge über eine valide Pro-Lizenz.
Ich bitte um Unterstützung bei der Lösung des Problems. Ich habe bereits einige Anläufe unternommen, unter Anderem neue Instanzen des Adapters hinzugefügt. Das Fehlverhalten ist jedoch immer noch das Gleiche...
Komisch ist, dass es zunächst funktioniert. Irgendeine Überprüfungslogik sorgt dann aber wohl dafür, dass die Anzeige rot wird und dieser Error angezeigt wird.
Dementsprechend denke ich, dass es unter Umständen mit der Verifizierung meiner Lizenz zusammenhängen könnte. Hat sich dort vielleicht etwas verändert?

Über eine kurze Rückmeldung und Unterstützung würde ich mich sehr freuen, denn so kann ich dieses Frontend leider nicht mehr verwenden, was ich sehr schade finde!

PS: Vielen Dank für dieses großartige Projekt. Hat tatsächlich noch sehr viel potenzial und bildet alles sehr elegant ab!! :-)

Vielen Dank im Voraus und viele Grüße

Jaschster

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Web Adapter neugestartet? Sonst ioBroker neustarten bitte.

**Comment by Jaschster** [comment]
Vielen Dank für das super schnelle Feedback! Es funktioniert nun wieder. Habe allerdings auch ein paar Anläufe benötigt. Es scheint, als würde jedes Mal wenn ich eine Aktualisierung von Jarvis durchführe, die Konfiguration verloren gehen, sodass Jarvis nicht mehr auf die entsprechende Web-Instanz zugreifen kann. Bei mir hat es nämlich erst wieder funktioniert, nachdem ich den Web-Adapter anders konfiguriert habe. Finde es komisch, da es ja vor der Aktualisierung auch erst geklappt hat. Auch fällt mir jetzt rückblickend auf, dass solch ein Ereignis nach einer Aktualisierung von Jarvis ggf. auch schon Mal in der Vergangenheit bei mir geschehen seien könnte...

**Comment by Zefau** [comment]
Nach dem Update am besten immer 1x von ioBroker Dashboard aufrufen, damit die Verbindungsdetails mitgegeben werden.
