### ISSUE TITLE
Konfigurationsseite bleibt weiß

### ISSUE THREAD

**Issue by disaster123** [Zefau/ioBroker.jarvis#1512]
**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**

Getestet mit 3.0.10-beta1, 3.0.9, 3.0.7

- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

![image](https://user-images.githubusercontent.com/861558/149677628-87d9a6b9-2674-423a-8356-1280a8d80b6b.png)

**Describe the bug / Beschreibe den Fehler**

Die Konfigurationsseite bleibt plötzlich einfach weiß. Keine Fehlermeldung im Log - Browser Cache auch schon geleert.

**Screenshots**

siehe oben
____

PS: kann man als Pro User eigentlich auch anders Probleme melden?

**Comment by Zefau** [comment]
Wie ist die URL? Wenn diese auf `/#/configuration/` endet, dann einfach erweitern auf `/#/configuration/layout`.

> PS: kann man als Pro User eigentlich auch anders Probleme melden? 

Immer auch per Email an ioBroker.jarvis@mailbox.org.
Auch via Discord Channel.

**Comment by disaster123** [comment]
danke, ich schick mal ne Mail;-)

**Comment by Zefau** [comment]
@disaster123 hast du die Email schon geschickt oder ist sie mir untergegangen? Kannst du sie sonst nochmal schicken?

**Comment by disaster123** [comment]
Jo sorry war alles geklärt
