### ISSUE TITLE
State in StateList ausblenden mit Binding (ioBroker App auf iOS)

### ISSUE THREAD

**Issue by Ma-Kra** [Zefau/ioBroker.jarvis#1513]
Jarvis v3.0.10-beta.1

Ich habe eine Philips Hue Lampe und möchte das Gerät aus einer StateList ausblenden, wenn die Lampe nicht erreichbar ist (am Schalter ausgeschaltet). Stattdessen wird dann ein anderer State (ohne SwitchAction) eingeblendet. In Chrome scheint das auch sauber zu funktionieren, aber nicht in der ioBroker App auf dem Smartphone (iOS). Dort verschwindet die Zeile in den meisten Fällen nicht.

Body Stil für den State:
`{"{hue-extended.0.lights.006-kugellampe.state.reachable}===false":{"display":"none"}}`

**Comment by Zefau** [comment]
Kann ich nicht viel zu sagen, da ich die ioBroker App nicht kenne / nutze. Geht es mit einem Browser auf mobil? Chrome Mobile? Oder dem Fully Browser?

**Comment by Ma-Kra** [comment]
Die ioBroker App scheint im Hintergrund Safari im Vollbildmodus zu nutzen. Ich habe Safari und Chrome getestet, da war es auch nicht sauber. Ich habe den Body Stil jetzt mal geändert auf:
{
  "default": {
    "display": "flex"
  },
  "{hue-extended.0.lights.006-kugellampe.state.reachable}===false": {
    "display": "none"
  }
}

Sieht besser aus, ich teste noch weiter, da es vorher auch nur ein sporadischer Effekt war.

**Comment by mcuiobroker** [comment]
Besser immer 
```
"display": "none !important"
```
nutzen

**Comment by uwe72** [comment]
Klingt ja verwandt zu "meinem" Thema:
https://github.com/Zefau/ioBroker.jarvis/issues/1509

**Comment by Ma-Kra** [comment]
Das Problem beim Öffnen eines Popups habe ich auch

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.10-beta.3`

**Comment by Zefau** [comment]
@uwe72 @Ma-Kra passt das? Kann ich das Issue schließen?

**Comment by Ma-Kra** [comment]
Hatte in der letzten Zeit nicht so viel Zeit zum Testen und weiterbauen der Oberfläche. 
Das Problem ist jetzt behoben, Issue kann geschlossen werden.

**Comment by uwe72** [comment]
Kann geschlossen werden. Danke!
