### ISSUE TITLE
Module Devices - Gerät hinzufügen - begrenzte Auswahlmöglichkeit

### ISSUE THREAD

**Issue by LoDDl** [Zefau/ioBroker.jarvis#1514]
Hallo,

seit dem letzten Update kann ich nicht mehr alle Gerätegruppen auswählen:
![image](https://user-images.githubusercontent.com/52470482/149679800-16ebeeda-29ef-47fe-bc8c-e65f7738bd16.png)

Diese sind aber verfügbar:
![image](https://user-images.githubusercontent.com/52470482/149679815-d42bc822-0732-4be5-91a9-c08cd5e89476.png)

Die letzten beiden werden abgeschnitten.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.10-beta.3`

**Comment by LoDDl** [comment]
wieder alles wunderbar. Danke!
