### ISSUE TITLE
MIX DP Anzeige != Trigger, SwitchAction schaltet, thumb wird nicht versetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1515]
MIt bug nicht so sicher?
disabled (oben in der Statelist) ist ein String, status ist auch ein String
![image](https://user-images.githubusercontent.com/84818934/149758591-abdedfb3-28a5-476b-8604-e19171ae9b06.png)

MIX (unten in der StateList)
Datenpunkt Anzeige != Datenpunkt Trigger
![image](https://user-images.githubusercontent.com/84818934/149757191-590481a6-83ec-42cc-9a63-6ee8cd6b1075.png)

![image](https://user-images.githubusercontent.com/84818934/149757248-ff6a2bfc-dddc-4613-a887-6a617a7660dd.png)
Alternativ setOn genutzt

![image](https://user-images.githubusercontent.com/84818934/149758522-101e3325-dab8-4468-8559-6e301e1cf1f3.png)
Layout

![image](https://user-images.githubusercontent.com/84818934/149758369-33cd938a-46b4-460c-80c9-eaf17a49160f.png)

![stateList-Action schaltet nicht](https://user-images.githubusercontent.com/84818934/149757101-fde59fe5-ca86-4c66-9627-3d31d61fd83d.gif)

Kann es damit zusammenhängen, das Datenpunkt-Eigenschaft sich auf den Datenpunkt (Anzeige) bezieht?
Bin mir über die Funktion von Datenpunkt-Eigenschaft unsicher?
Wann bezieht es sich auf die Anzeige, wann auf Trigger? (setOn,setOff)?

**Comment by Bernd9000** [comment]
Den Fehler hatten wir doch gestern erst.
Welche Version hast Du gerade installiert und was wird beim schalten im Datenpunkt eingetragen ?

[#1497](https://github.com/Zefau/ioBroker.jarvis/issues/1497)

**Comment by Bernd9000** [comment]
Ich hab die Erfahrung gemacht das die "Datenpunkt Eigenschaften" angeben was beim Datenpunkt Trigger eingefügt werden soll.
Die Umschaltung des Schalters wird aber nur "gezeichnet" wenn der Wert auch im "Datenpunkt Anzeige" ankommt.
Ich nehme mal an das bei dir "Datenpunkt Anzeige" leer ist ?

**Comment by mcuiobroker** [comment]
> Ich nehme mal an das bei dir "Datenpunkt Anzeige" bei mix leer ist ?
siehe oben der DP ist gefüllt.
Ein DP soll so genutzt werden, dass man mit dem Trigger etwas schaltet und mit der Anzeige etwas anzeigt. Beide sind dann unabhängig voneinander.
Es geht um Fenster:
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1036
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1053
Und dies soll möglichst in einer Zeile angezeigt werden.
Warum sollte so was nicht möglich sein?
> es wird nur nicht angezeigt weil die Rückmeldung fehlt.
Dann müsste man eine Rückmeldungsmöglichkeit einbauen?

**Comment by Bernd9000** [comment]
Ach so....
Und secondary state ist nicht erwünscht ?

**Comment by mcuiobroker** [comment]
Ja genau, wenn man es doch in einem Geräte-DP eigentlich erledigen kann. Einige haben viele solcher Konstellationen. Bei höherer Anzahl, kann man verstehen, dass man nicht mit CSS-Einträgen arbeiten möchte.

**Comment by Bernd9000** [comment]
Für mich wäre das verwirrend am Schalter Zustände angezeigt zu bekommen die mit dem Schalter gar nichts zu tun haben.
Ich hätte das z.B. mit dem Fenster Icon gelöst.
Fenster offen = Icon rot und blinkend
Fenster geschlossen = Icon grün
Da sieht man auf einem Blick ob Fenster offen oder geschlossen sind.

**Comment by Zefau** [comment]
Ist hier noch was offen oder kann das Issue geschlossen werden?

`on`/`off` konvertiert den eingehenden Wert und mappt um. `setOn` / `setOff` schickt benutzerspezifische Werte an den Trigger.

**Comment by mcuiobroker** [comment]
Mach ich erstmal zu, wäre sowieso ein Feature: Gleichzeitige Nutzung von unterschiedlichen DPs (Anzeige/Trigger) unabhängig voneinander. Der eine zeigt nur den Wert, der andere schaltet nur.
