### ISSUE TITLE
Notification backgroundColor, fontColor werden nicht verarbeitet

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1516]
`v3.0.10-beta.2`
```
jarvisNotify.fontColor = "black";
jarvisNotify.backgroundColor = "black";
```
Keine der Farben zieht in der Notification. Nur color 
```
jarvisNotify.color = "red";
```
![image](https://user-images.githubusercontent.com/84818934/149794168-74f793cd-ffc8-45c3-b859-7f0e2098b8bd.png)

**Comment by Zefau** [comment]
Es gibt nur `color` und `textColor`.

**Comment by mcuiobroker** [comment]
Ok.
