### ISSUE TITLE
Incorrect callback function

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1518]
```
{"{val}='OFF'&&{0_userdata.0.jarvis.test.status}='geschlossen'":{"display":"none !important"}}
```
![image](https://user-images.githubusercontent.com/84818934/149839270-fd965abc-798a-4312-ad11-2a315488e1a2.png)

![image](https://user-images.githubusercontent.com/84818934/149839301-ee887699-8f87-437b-88b8-46b3c7187bd7.png)

**Comment by Zefau** [comment]
Versuch mal bitte
```
{"'{val}'=='OFF'&&{0_userdata.0.jarvis.test.status}=='geschlossen'":{"display":"none !important"}}
```

**Comment by mcuiobroker** [comment]
Das funktioniert. Es kommen auf jeden Fall mometan keine Fehlermeldungen.
Sind beide Bedingungen erfüllt, wird display nicht ausgeführt.

**Comment by Zefau** [comment]
Dafür gibt es ein Issue

**Comment by mcuiobroker** [comment]
Nicht im Popup, in der StateList.

**Comment by mcuiobroker** [comment]
```
{"'{val}'='OFF'&& {0_userdata.0.jarvis.test.status}='geschlossen'":{"display":"none !important"}}
```
So funktioniert es momentan, nach einige Male F5.
Man muss nach Einstellung vom neuen Binding, immer erst F5 drücken, damit es funktioniert.
