### ISSUE TITLE
TypeError: Cannot read properties of undefined

### ISSUE THREAD

**Issue by Zwer2k** [Zefau/ioBroker.jarvis#1519]
Jarvis v3.0.9

<html>
<body>

jarvis.0 | 2022-01-17 22:37:32.347 | info | Adapter stopped und unloaded.
-- | -- | -- | --
jarvis.0 | 2022-01-17 22:37:32.342 | error | Cannot read properties of undefined (reading 'ip')
jarvis.0 | 2022-01-17 22:37:32.342 | error | TypeError: Cannot read properties of undefined (reading 'ip') at ioWebSocket.eventFromClient (/opt/iobroker/node_modules/iobroker.jarvis/lib/websocket.io.min.js:1:4231) at ioWebSocketClient._parentMessage (/opt/iobroker/node_modules/iobroker.jarvis/lib/websocket.io.min.js:1:6959) at ioWebSocketClient.disconnect (/opt/iobroker/node_modules/iobroker.jarvis/lib/websocket.io.min.js:1:8944) at Socket.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/websocket.io.min.js:1:8136) at Socket.emit (node:events:390:28) at Socket.emitReserved (/opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/typed-events.js:56:22) at Socket._onclose (/opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/socket.js:358:14) at Client.onclose (/opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/client.js:239:20) at Socket.emit (node:events:402:35) at Socket.onClose (/opt/iobroker/node_modules/iobroker.jarvis/node_modules/engine.io/build/socket.js:303:18)
jarvis.0 | 2022-01-17 22:37:32.341 | error | uncaught exception: Cannot read properties of undefined (reading 'ip')

</body>
</html>

**Comment by Zefau** [comment]
ist in 3.0.10 bereits behoben

**Comment by Zwer2k** [comment]
perfekt danke
