### ISSUE TITLE
Chart - only showing one graph for devices with multiple datapoints

### ISSUE THREAD

**Issue by Wolfilux** [Zefau/ioBroker.jarvis#152]
Hi,

I have an issue displaying multiple graphs in the chart widget.

There is one device (information of heating system) with several datapoints (e.g. pump speed, heating temperature target and actual). When I'm choosing two or more datapoints from this device only one of them shows up in de chart.

Maybe it's a bug or am I missing something?

**Comment by Zefau** [comment]
Did you close on purpose? Did you fix this yourself?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/153

**Comment by Wolfilux** [comment]
Sorry, double posting...
