### ISSUE TITLE
HistoryGraph jarvis Selektor Klassen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1522]
Es fehlen noch einige Klassen, um auch beim HistoryGraph die Einstellungen beeinflussen zu können:
![image](https://user-images.githubusercontent.com/84818934/149998426-955249c2-5039-462a-9ff1-e8cef5eff82c.png)
![image](https://user-images.githubusercontent.com/84818934/149998465-7c17b932-4c4c-4fcf-bb75-7c59c76372d1.png)
Hier kann man sich mit der schon vorhanden Klasse Einstellungen anpassen:
![image](https://user-images.githubusercontent.com/84818934/149998544-4686d9e4-a94d-497d-a4b9-f82194fc4a90.png)
```
.chartConfiguration-56410bd8-f6ab-4843-98d8-6129a0c478e7 span {
	background: red;
	color: white;
}

.chartConfiguration-56410bd8-f6ab-4843-98d8-6129a0c478e7:hover {
	background: red;
	color: white;
}
```
Sinnvoll wäre aber auch hier durchgängig .jarvis-historyGraph-klassen

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.22` hinzugefügt

**Comment by mcuiobroker** [comment]
Danke.
