### ISSUE TITLE
Notifikation Icon wird mit Tab- Leiste mitverschoben

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#1523]
Version `v3.0.10-beta.2`

Das Notifikation Icon wir bei kleiner Auflösung mit der Tab- Leiste mitverschoben und bleibt nicht in der Ecke.

![grafik](https://user-images.githubusercontent.com/77939385/150008008-92ec9e7a-acfb-4037-b946-9ef3fc51428a.png)

**Comment by tofrie** [comment]
In dem Zusammenhang... Kann man das Icon auch komplett deaktivieren?

**Comment by mcuiobroker** [comment]
Bei mehreren TABs ist es auch verschoben:
![image](https://user-images.githubusercontent.com/84818934/150150395-bfa87ea5-99ca-4e10-a15b-07eb6af011d4.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.10-beta.3`

**Comment by hosabeni** [comment]
Funktioniert jetzt wieder.

Danke!
