### ISSUE TITLE
Media Control Anzeigefehler

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#1524]
Hallo, Anzeige Media Control Fehler?

Weißer Balken sollte Volume sein? Da geht nix. Music Adapter:  Alexa2
Bei abspielen fehlen auch die 2 Icons

Edit:

Zeitanzeige Falsch

![Screenshot (4654)_LI](https://user-images.githubusercontent.com/41079106/150128755-d5505728-10d9-4178-b5af-7adf728d905c.jpg)

Edit2:

Bei abspielen via Amazon Musik wird alles korrekt angezeigt.

![Screenshot (4655)](https://user-images.githubusercontent.com/41079106/150137742-5364e7c5-2696-49d8-ae4c-3a1f074d7456.png)

Edit3

Falsche Anzeige kommt bei tuneIn 

Edit 4

Wird schon, bis auf die {{

![Screenshot (4662)](https://user-images.githubusercontent.com/41079106/150694463-f026d2df-fa39-464c-a58c-f5a93728c421.png)

Plattform: Windows
RAM: 16 GB 
NODE.JS: V14.18.3
NPM: 6.14.15
JS Controller: 3.3.22
Admin: 5.2.3
Web: 3.4.16
Socket.io: 3.1.4
Script Engine: 5.2.19
VIS: 1.4.7
Jarvis: 3.0.9

**Comment by mcuiobroker** [comment]
Auch die Zeit wird falsch angezeigt:
![image](https://user-images.githubusercontent.com/84818934/150129422-481e64fc-652b-4640-9d11-cb5b4035edc5.png)

**Comment by Zefau** [comment]
Zeit ist inkorrekt. Die Vor-/Zurück-Buttons fehlen aber mit Absicht bei Radio-Sendern, da die Navigation ja nicht möglich ist.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10`

**Comment by mcuiobroker** [comment]
Man kann keine andere Alexa mehr auswählen, nachdem man eine gestartet hat:
![image](https://user-images.githubusercontent.com/84818934/150686692-1b3da673-7665-4229-a1d5-a9809492d6b1.png)

**Comment by Zefau** [comment]
Hab ich abgeschaltet für Radio. Gegenfrage: Wie kann ich in den ioBroker Datenpunkte die Wiedergabe im Alex2 Adapter auf ein anderes Gerät umschalten?

**Comment by mcuiobroker** [comment]
Aber, wenn man auf Pause drückt, müsste man doch eine andere auswählen können, oder nicht?
Umschalten: auf dem einen Gerät stoppen und auf dem anderen Gerät starten. Mir ist keine direkt Umleitung bekannt. Vielleicht weiß apollon77 mehr?

**Comment by mcuiobroker** [comment]
Geht doch: schiebe meine Musik auf Flur im `command`

**Comment by Zefau** [comment]
Ich brauch einen Datenpunkt in Alexa2, den ich triggern kann. Ggf. auch mehrere. `textCommand` ist kein Datenpunkt in Alexa2, oder?

**Comment by mcuiobroker** [comment]
alexa2.0.Echo-Devices.G2A0U204*.Commands.textCommand

**Comment by sigi2345** [comment]
Hallo, gibt es was neues wegen 

Edit 4

Wird schon, bis auf die **{{**
