### ISSUE TITLE
Notification wird verspätet angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1526]
Mit addNotification landet die Notification direkt als zusätzliche Zahl an der Glocke, wird aber erst 5 Sekunden später als Popup angezeigt.
Teilweise wird es auf jedem Gerät unterschiedlich, aber mindestens 3 Sekunden, später angezeigt.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.10-beta.3`

**Comment by mcuiobroker** [comment]
Passt.Danke.
