### ISSUE TITLE
Chart - Issue showing more than one graph of the same device

### ISSUE THREAD

**Issue by Wolfilux** [Zefau/ioBroker.jarvis#153]
Hi,

I have an issue displaying multiple graphs in the chart widget.

There is one device (information of heating system) with several datapoints (e.g. pump speed, heating temperature target and actual). When I'm choosing two or more datapoints from this device only one of them shows up in de chart.

Maybe it's a bug or am I missing something?

**Comment by Zefau** [comment]
Looks like one device being used multiple times does not work correctly. I will fix this tomorrow.

**Comment by Zefau** [comment]
Could you check if this got solved with `1.1.0-beta.21` ?

**Comment by Wolfilux** [comment]
Seems to work. Great!
Thank you very much.

**Comment by Zefau** [comment]
@Wolfilux

**Comment by Zefau** [comment]
fixed with `v1.0.8`
