### ISSUE TITLE
Man kann die Widget Gaps negativ einstellen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1530]
Man kann die Widgets Gaps negativ einstellen?
Soll das so? Führt zur Überlagerung der Widgets.

**Comment by Zefau** [comment]
Würde ich verbieten. Braucht man nicht, oder?

**Comment by mcuiobroker** [comment]
Ja verbieten, braucht man nicht.
Komische Berechnung bei voxid:
https://forum.iobroker.net/post/744926
9*45 = 405 + 5  = 410 gezeigt wird 400?
![image](https://user-images.githubusercontent.com/84818934/150338789-54cb785e-d406-4737-aef7-dad40fb84213.png)
![image](https://user-images.githubusercontent.com/84818934/150338850-e27c8532-42c4-4e42-a0ba-130c9d67ae3b.png)

**Comment by Zefau** [comment]
Die Widget Gaps ergeben sich aus den benachbarten Widgets. Also wenn neben dem Widget auf der Höhe von 9h mehrere Widgets sind, dann zählen die Gaps in die Höhe rein.

**Comment by mcuiobroker** [comment]
Wenn jetzt kein Widget daneben ist, müsste er 405px anzeigen?

**Comment by Zefau** [comment]
https://jbaysolutions.github.io/vue-grid-layout/guide/events.html#gridlayout

**Comment by Zefau** [comment]
Also wie dein Screenshot zeigt bringt jede Höhe einen Gap mit. Also es ist immer die Formel `Zeilen * (Höhe + Gap)`

**Comment by Zefau** [comment]
Warum oben bei 9 Zeilen = 400px raus kommt ist verwirrend. Es müsste 445px raus kommen (9 * (45 + 5) - 5).

**Comment by mcuiobroker** [comment]
Ok. 
Wie gesagt ich vermute er hatte zu dem Zeitpunkt 40px als Widget-Höhe eingestellt.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.10-beta.3`

**Comment by mcuiobroker** [comment]
Keine Ahnung, wo ich es einstellen soll:
![image](https://user-images.githubusercontent.com/84818934/150437285-c214ee68-2d2d-4659-8d8b-c77a7cd773ba.png)

**Comment by Zefau** [comment]
Wie meinst du das? In den Tabs bei der Layout Konfiguration.

**Comment by mcuiobroker** [comment]
Wusste nicht wo ich den Fehler zuordnen soll. Hab ihn deswegen  einfach hier reingestellt.

**Comment by Zefau** [comment]
Der Fehler kommt von einer Hue oder RGB Komponente, die den Wert `0` nicht konvertieren kann (da kein valider Farbcode).

Werde ich fixen und zukünftig in schwarz übersetzen.

**Comment by mcuiobroker** [comment]
Das Problem ist wieder, dass er aus HUE ein hex-Wert macht.
![image](https://user-images.githubusercontent.com/84818934/150546114-eec445c3-3adc-4cf9-9988-cc5442b607fc.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10`

**Comment by mcuiobroker** [comment]
Passt. Danke.
