### ISSUE TITLE
Update ioBroker Host 3.3.15 auf 3.3.22 - JARVIS nicht mehr Pro wegen ungültiger Lizenz

### ISSUE THREAD

**Issue by Kaskadeur111** [Zefau/ioBroker.jarvis#1532]
![image](https://user-images.githubusercontent.com/28257942/150492830-463404c7-be46-4586-add7-29626e194e70.png)

Ergänzung: Als ich nach Erhalt der Meldung das erste mal auf den Reiter "Pro Account" gewechselt bin, stand oben in einem gelben Fenster "Not signed in" und ich hab erstmal auf den Paypal Anmelden Knopf gedrückt um mich anzumelden. der Account ist auch der richtige, sonst würde er ja sicher nicht die Rechnung und so weiter anzeigen. (jw8x@xxxx.xx)

**Comment by AFPass** [comment]
Ebenfalls Probleme. Bei mir schaut es so aus:
![grafik](https://user-images.githubusercontent.com/13101074/150495581-151c5f7a-f24c-45b2-8215-3d5e6eec5a8a.png)

**Comment by Kaskadeur111** [comment]
Ja genau so sah es auch bei mir aus. Nur konnte ich mich wieder per Button bei Paypal einloggen. Lizenz ist aber trotzdem ungültig

**Comment by Zefau** [comment]
Die Lizenz ist ordentlich in jarvis.0.info.pro hinterlegt? Im Datenpunkt, nicht dem Objekt?

**Comment by Kaskadeur111** [comment]
Sieht so aus, ja. Steht alles drin, mein Name Meine Rechnungsnummer PayerID etcetc.

**Comment by Kaskadeur111** [comment]
aber warum stehen in der Dropdown Box 2 iOBroker Installationen mit unterschiedlichen ids drin, ich hab doch nur eine? Hängt das vielleicht mit dem Javascript Update zusammen?

**Comment by Zefau** [comment]
Das ist die Kennung der ioBroker ID. Also hattest du zwei Installationen auf dem System?

Schick gerne mal deine Lizenz und einen Screenshot wie du diese im Datenpunkt hinterlegt hast an iobroker.jarvis@mailbox.org, dann schaue ich mir das an.

**Comment by Kaskadeur111** [comment]
Mach ich Danke schonmal :-)

**Comment by Kaskadeur111** [comment]
geschickt

**Comment by Zefau** [comment]
Bitte entfernt `ioBrokerId` aus der Lizenz, falls diese da reingerutscht ist.

**Comment by Kaskadeur111** [comment]
Erledigt, bin wieder Pro! 👍

**Comment by Zefau** [comment]
behoben mit `v3.0.10`
