### ISSUE TITLE
Chart Buble wird nicht topmost angezeigt

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1533]
v3.0.10-beta.3

Bei dem Chart in dem Bild wird das Detailfenster nicht über dem Widget links daneben angezeigt. Bei den anderen funktioniert dies.

![image](https://user-images.githubusercontent.com/2972703/150497869-93114552-2a05-4417-a206-fa0be690ef95.png)

Ich nehme an das Problem kommt daher, das ich die Reihenfolge der Widgets geändert habe. 

![image](https://user-images.githubusercontent.com/2972703/150498270-2a196d49-8199-4d25-98cd-02354b88ae62.png)

Außerdem wäre es schön wenn das Fenster nach rechts ausgerichtet wird wenn man zu weit links am Rand ist.
![image](https://user-images.githubusercontent.com/2972703/150500068-c0f22af6-f143-4c11-836e-021e2c88baec.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10`

**Comment by stephan1827** [comment]
Der unten rechts ist jetzt richtig aber alle anderen sind jetzt falsch :-)
<img width="665" alt="Bildschirmfoto 2022-01-23 um 18 38 43" src="https://user-images.githubusercontent.com/2972703/150690790-535e80b2-fe36-4c12-98f0-f10697113997.png">

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.11-beta.5`

**Comment by Zefau** [comment]
@stephan1827
