### ISSUE TITLE
Schriftfarbe AdapterStatus Widget im DarkMode und Tab als Vollbild

### ISSUE THREAD

**Issue by kohennigs** [Zefau/ioBroker.jarvis#1536]
Moin Moin!  

Bin neu hier,  deshalb erstmal nur eine Kleinigkeit:

Vorbedingungen:

- Jarvis v2.2.0
- Theme auf Dark Mode
- Adapter Status Widget als Vollbild-Tab ein (nur eine Spalte)

Problem: 

- Adapter Namen sind kaum / schlecht lesbar
- Schriftfarbe des Adapter Namens ist kaum zu lesen, weil diese nicht auf "hell" umgestellt wird.
Bei der Versionsnummer des Adapters schauts gut aus.
<img width="423" alt="Bildschirmfoto 2022-01-22 um 05 31 38" src="https://user-images.githubusercontent.com/45618309/150624871-df0b4db3-a74b-47fe-b4bf-5481876aff6c.png">

**Comment by Zefau** [comment]
Danke dass du Jarvis nutzt. V2 ist nicht mehr supported. Bitte geh auf v3. Die kommt dieses WE auch ins stable.

**Comment by kohennigs** [comment]
Oh sorry, das hab ich übersehen! :D 

Dann wechsel ich mal, wenn die stable v3 raus ist.
