### ISSUE TITLE
Icon von IconButtonAction nicht zentriert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1537]
Icon auf der IconButtonAction ist nicht zentriert:
![image](https://user-images.githubusercontent.com/84818934/150640338-91ac75d9-47eb-45ec-95ff-b7ebdaa78c0c.png)
"nbsp; " verschiebt es nach links:
![image](https://user-images.githubusercontent.com/84818934/150641084-0495511d-ac81-461a-a0f1-e35e80159d01.png)

Wenn du schon daran gehst, kannst du dort auch den Zustand als Klasse mit reinnehmen? Dann kann man in Abhängigkeit von Zustand (false/true) die Hintergrundfarbe setzen, oder du nimmst es mit in die Config vom IconButtonAction und ButtonAction?
![image](https://user-images.githubusercontent.com/84818934/150641193-6a3d77a7-8839-4147-85eb-1cd9c2c4da3e.png)

![image](https://user-images.githubusercontent.com/84818934/150641328-8f374e11-2954-4c44-82a3-66e3c4e6f301.png)

**Comment by Zefau** [comment]
fixed with `v3.1.0-alpha.26`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/181510103-f485f534-f29d-4479-bf9b-b50df63702d9.png)
Passt von der Höhe nicht ganz, aber wichtiger wäre mir die background-color.
![image](https://user-images.githubusercontent.com/84818934/181510262-785ea858-2f29-41bc-8e2b-2a6455fd7782.png)
Bitte die Background-Color auf der hover-Ebene ergänzen.

![image](https://user-images.githubusercontent.com/84818934/181511324-d7f483ee-4acf-4ad4-b079-691ab5d24f16.png)

![image](https://user-images.githubusercontent.com/84818934/181511573-da7f7f75-92bf-4fca-941d-6d306da66c5c.png)
oder
![image](https://user-images.githubusercontent.com/84818934/181511660-0443ca24-2f94-4959-ab6c-d93156c10d8d.png)
Wenn keine Farb gesetzt, dann kommt normal der hover-Effekt.

**Comment by Zefau** [comment]
ist ein Feature Request. Löse es sonst gerne via CSS
