### ISSUE TITLE
fixed-right überlagert Scrollbalken

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1539]
Der Bereich fixed-right? überlagert den Scrollbalken, deswegen kann man den Scrollbalken-Thumb auch sehr schlecht selektieren:
![image](https://user-images.githubusercontent.com/84818934/150645254-7bc6986f-da94-4c4d-8878-cc322861df45.png)
Man muss ganz nach links klicken, um den Scrollbalken-Thumb bewegen zu können.

Habe versucht mit `z-index: 99 !important;` zu arbeiten, das funktioniert aber nicht.
Mit folgender Lösung geschafft:
```
.scroll {
	z-index: 2099 !important;
}
```
Bitte die Ebenen für scroll höher legen?

**Comment by Zefau** [comment]
Wieso `.scroll`?

**Comment by mcuiobroker** [comment]
Hab es nur probiert und es klappte? Kein Grund.

**Comment by Zefau** [comment]
Also `fixed-right` vom Notification Panel überlagert den Scrollbalken von der Seite meinst du? Oder beziehst du dich auf den Scrollbalken von JsonTable?

**Comment by mcuiobroker** [comment]
Auf den Scrollbalken von der jsonTable.

**Comment by Zefau** [comment]
Ok. Auf die vertikale für die Zeilen, richtig? Es gab ja noch irgendwie einen offen Bug für den vertikalen Scrollbalken, oder?

**Comment by mcuiobroker** [comment]
Ja. Gibt es noch, ein ähnlicher Fall. Dort ging es um den Button das Dreieck. Man muss es genau treffen, damit rauf und runter scrollen kann.

**Comment by Zefau** [comment]
Ok, hast du eine eigene interime CSS Lösung?

**Comment by mcuiobroker** [comment]
Nee, noch nicht ganz. War mir ja gestern um den Ohren geflogen, wegen scroll funktionierte die Auswahl der Gewerke nicht mehr.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1540

**Comment by Zefau** [comment]
der fix wäre
```
.jarvis-widget {
  z-index: 2;
}

.q-drawer__opener {
  z-index: 1 !important;
}
```

Könnte aber sein, dass das Nebeneffekte mit sich bringt.

**Comment by mcuiobroker** [comment]
Ok. Ich probier es gleich mal. Melde mich.

**Comment by mcuiobroker** [comment]
Also ich kann momentan keine Nebeneffekte feststellen.

**Comment by Zefau** [comment]
dann liefer ich das mit dem nächsten Release so aus

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10`

**Comment by mcuiobroker** [comment]
Passt. Danke.
