### ISSUE TITLE
BlindLevelAction Konfiguration noch englisch

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1541]
![image](https://user-images.githubusercontent.com/84818934/150658749-4844afda-f2f2-4242-8240-67a71f032ec8.png)

**Comment by Zefau** [comment]
`Component Options` meinst du?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10`

**Comment by mcuiobroker** [comment]
Layout config-> 
![image](https://user-images.githubusercontent.com/84818934/150874107-52faff59-14b4-4fb0-bf0d-720d93e85a7a.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.11-beta.1` behoben sein
