### ISSUE TITLE
Icon Größe / Seitenverhältnis

### ISSUE THREAD

**Issue by Rincewind0** [Zefau/ioBroker.jarvis#1543]
Hi,
nach dem Wechsel von 3.0.9 auf 3.0.10 (beta 3) hat sich scheinbar etwas verändert, in der Art, wie man den Icon Stil verändern kann.
Für meinen Sat-Receiver habe ich Senderlogos als Icon definiert, um damit die Programme umzuschalten. Die Größe und das Seitenverhältnis der Icons hatte ich mit **{"default":{"width":"125px","height":"75px"}}** angepasst. Das funktioniert jetzt nicht mehr. Die Größe kann ich zwar jetzt über **{"fontSize":"96px"}** anpassen, aber die Icons sind immer quadratisch. Ist das so beabsichtigt? Oder gibt es eine andere Möglichkeit das Seitenverhältnis wieder anzupassen?
Der Datenpunkt ist jeweils in ein HomeKitTile Widget eingebunden, über den ich die Umschaltung des Programms steuere.

Bisherige Geräteconfig:

![Geräteconfig (alt)](https://user-images.githubusercontent.com/86548134/150674298-44e65546-0b29-42b0-8c0e-da4418544871.jpg)

Neue Geräteconfig:

![Geräteconfig (Neu)](https://user-images.githubusercontent.com/86548134/150674341-82864d5e-dde0-4b0c-8bee-e80fc27e6714.jpg)

Links mit neuer Geräteconfig und rechts mit der bisherigen:

![Icons](https://user-images.githubusercontent.com/86548134/150674413-9bc9ce34-708a-4497-a88c-4d02e2de5eb9.jpg)

Widget Config:

![Widget Config](https://user-images.githubusercontent.com/86548134/150674429-e6f0770e-c5ac-4c50-9f25-e94d26324424.jpg)

Ich hoffe das war halbwegs verständlich ausgedrückt...
Gruß

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.10`

**Comment by Rincewind0** [comment]
Jupp, jetzt sieht´s wieder gut aus. Vielen Dank!
