### ISSUE TITLE
Chart-Fehler?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1544]
![image](https://user-images.githubusercontent.com/84818934/150688414-2d050a3a-9a76-4741-82b6-45e075dadb2a.png)

**Comment by Zefau** [comment]
Einfach so oder nach einer bestimmten Aktion?

**Comment by mcuiobroker** [comment]
Einfach so? Nur update installiert.

**Comment by mcuiobroker** [comment]
Nach F5 habe ich es noch nicht wieder gehabt. Vielleicht nur direkt nach Update?

**Comment by Zefau** [comment]
sollte mit `v3.0.11-beta.1` behoben sein

**Comment by Zefau** [comment]
@mcuiobroker passt das? Kann ich das Issue schließen? Danke dir.

**Comment by mcuiobroker** [comment]
Bislang nicht wieder aufgetreten.
