### ISSUE TITLE
Statelist-Gruppenschalter Fehlverhalten bei Geräten mit DP-Konvertierung

### ISSUE THREAD

**Issue by j1s2e3** [Zefau/ioBroker.jarvis#1545]
Jarvis Version 3.0.9 und 3.0.10
Keine Fehler in der JS Konsole

Alle meine virt. Geräte haben einen DP `.ON` (readonly, liefert boolean true/false) und einen anderen DP `.SET` (writeonly, number 0=off, 1=on, 2=...). Das Jarvisgerät bündelt diese in einem DP power (siehe Bild):
![Screenshot from 2022-01-23 16-13-36](https://user-images.githubusercontent.com/92024911/150744505-f1b84164-5ac8-412e-9172-b348d28ebe07.png)

Die Konvertierung des internen ActionElement-State erfolgt damit:
`{"off":"false","on":"true","setOff":0,"setOn":1}`

Mehrere solcher Jarvis-Geräte gruppiere ich dann in einer Statelist:
![Screenshot from 2022-01-23 15-37-48](https://user-images.githubusercontent.com/92024911/150744939-060b55fb-4dbe-4a70-8cc6-3b0d1be5c07d.png)

Jedes einzelne Element der Statelist ist korrekt schaltbar und funktioniert. D.h. on/off = true/false wird gemappt auf 0 und 1 und dann korrekt in den DP `.SET` geschrieben -> per Skipt nach HW-DP -> Aktor schaltet. Wenn ich den Aktor nicht via Jarvis schalte, sondern z.B. mit einem Lichtschalter an der Wand, dann ändert sich der DP `.ON` und Jatvis zeigt korrekt den neuen State an. D.h. beide Richtungen Lesen/Schreiben (aus Sicht des Actionelements) gehen.

Nun füge ich der Statelist einen Gruppenschalter hinzu. Siehe Foto oben.

Dieser zeigt IMMER den Zustand "Aus", egal in welchen Zustand (An/Aus) die Elemente der Gruppe sind. D.h. die Leserichtung des Gruppenschalters geht nicht: `*.ON` der Elemente -> Zustand on/off des Gruppenschalters.
![Screenshot from 2022-01-23 13-48-08](https://user-images.githubusercontent.com/92024911/150745971-cb4cb7e1-0af0-430c-858a-641e2d3aef8f.png)

Wenn ich den Gruppenschalter anklicke, dann wird in die DP `*.SET` der Elemente `true` geschrieben (Gruppenschalter ist ja aus). Das ist falsch. Es fehlt das Mapping. Nach `.SET` sollte 0 bzw 1 geschrieben werden. Ein fehlerhaftes Beispiel-Log:
`state ff94dd80.CMD changed: true (ack = false) state: {"val":"true","ack":false,"ts":1643011187361,"q":0,"c":"script.js.common.VirtualDevices.virt_FSSA","from":"system.adapter.javascript.0","user":"system.user.admin","lc":1643011187361} `

D.h. es sieht so aus, als ob der Gruppenschalter noch Probleme hat, wenn in Jarvisgeräten zw. Anzeige/Trigger-DP und Actionelement Werte gemappt werden.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.11-beta.5`.

**Comment by Zefau** [comment]
@j1s2e3
