### ISSUE TITLE
Update 3.0.9 -> 3.0.10: Installation inconsistent

### ISSUE THREAD

**Issue by Crazyachmed** [Zefau/ioBroker.jarvis#1546]
Nach dem Update von Jarvis 3.0.9 auf 3.0.10 wechselt die Jarvis-Ansicht nach wenigen Sekunden zu einer roten Seite mit der Meldung:

```
Error: Installation inconsistent
Hide Log (7)
Connecting to http://iobroker.lan:8400 (#1)...
24.01.2022, 09:19:44 | INFO | CONNECTION
Connected to http://iobroker.lan:8400.
24.01.2022, 09:19:44 | INFO | SOCKET
Received an Update for Settings.
24.01.2022, 09:19:44 | DEBUG |
Received an Update for Devices.
24.01.2022, 09:19:44 | DEBUG |
Received an Update for Layout.
24.01.2022, 09:19:44 | DEBUG |
Received an Update for Styles.
24.01.2022, 09:19:44 | DEBUG |
Incorrect State given, , [object Object]
24.01.2022, 09:19:44 | WARN | BLINDLEVELACTION
```

Ich habe ohne Erfolg probiert den Browser-Cache zu löschen und die Instanz neu zu starten.

Node.js: 14.18.3
npm: 8.3.2
jscontroller: 3.3.22

Die Installation ist ein Update von Version 2, in der ich aber schon ein paar kleine Änderungen konfiguriert habe.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/fehler-hinweise-v3#installation-inconsistent

**Comment by mcuiobroker** [comment]
Npm ist ein wenig neu? 7 wird kaum unterstützt?

**Comment by Crazyachmed** [comment]
Das mit dem Web Adapter wars
