### ISSUE TITLE
HistoryGraph - "Übernehmen" -Button ausgegraut

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#1550]
Im HistoryGraph Modul können Änderungen nicht mehr übernommen werden, da der "Übernehmen"-Button ausgegraut ist und nicht click-bar.

Zudem werden z.B. in den Geräten geänderte "Label"-Namen nicht im Chartmodul übernommen und angezeigt

Jarvis v3.0.11-beta.0

**Comment by mcuiobroker** [comment]
Konnte es ohne Probleme ändern.

**Comment by SlipKoRn88** [comment]
Welche Änderung spielt keine Rolle. "Übernehmen" ist direkt ausgegraut, sobald man das Widget zum bearbeiten öffnet.
Bei allen anderen Widgets kann direkt "Übernehmen" geklickt werden, egal ob etwas geändert wurde oder auch nicht.

**Comment by Zefau** [comment]
Kannst du das mal screenshoten?

**Comment by SlipKoRn88** [comment]
![Chart](https://user-images.githubusercontent.com/95069101/150921999-93923764-dcb8-4735-b5c5-4f0b787aec5f.jpg)

**Comment by Algieio** [comment]
Hallo, 
Ich habe gestern auch festgestellt, dass das "übernehmen" erst geht, wenn bei "Daten-Zoom Slider" eine Zahl drin steht. Z.B. 0

Ist wohl neu dazu gekommen.

![image](https://user-images.githubusercontent.com/96116321/150925717-2d9ae8d5-dfa3-4940-8d23-94df2de6fed3.jpeg)

**Comment by SlipKoRn88** [comment]
> Hallo, Ich habe gestern auch festgestellt, dass das "übernehmen" erst geht, wenn bei "Daten-Zoom Slider" eine Zahl drin steht. Z.B. 0
> 
> Ist wohl neu dazu gekommen.
> 
> ![image](https://user-images.githubusercontent.com/96116321/150925717-2d9ae8d5-dfa3-4940-8d23-94df2de6fed3.jpeg)

Jawoll! Daran lag es... Danke dir!

**Comment by Zefau** [comment]
sollte mit `v3.0.11-beta.1` behoben sein
