### ISSUE TITLE
iFrame Widget zeigt keinen Inhalt

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#1551]
Der Inhalt von iFrames wird nicht mehr angezeigt. Das Widget bleibt in der Hintergrundfarbe. Fehler werden im iFrame Widget keine angezeigt.

Jarvis v3.0.11-beta.0

**Comment by Zefau** [comment]
Ist aufrechterhalten aktiviert? Geht es ohne?

**Comment by SlipKoRn88** [comment]
Wenn ich "aufrecht erhalten" deaktiviere werden die iFrames angezeigt.
Aktiviere ich es wieder, sind sie wieder nicht sichtbar.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/977
