### ISSUE TITLE
Icon auf SwitchAction im Popup wird nicht angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1552]
![image](https://user-images.githubusercontent.com/84818934/150916746-64c9cc4e-73f1-41dc-8c57-e8b26ee1ccb8.png)

**Comment by Zefau** [comment]
Ist es im Gerät definiert?

**Comment by mcuiobroker** [comment]
Nein. Alles klar.
