### ISSUE TITLE
Notifaction Message Buttons with english lables even german is configured

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1553]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

```v3.0.10-beta.3```

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Notifaction Message Buttons with english lables even german is configured

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/79741077/150988202-4deeb32a-98bd-42bf-820f-1ee53cd46858.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
sollte mit `v3.0.11-beta.1` behoben sein

**Comment by RkcCorian** [comment]
Je nach Anzeigegerät wird es leider auf 2 Reihen angezeigt und auch der Platz nicht gut ausgenutzt
![image](https://user-images.githubusercontent.com/79741077/151973596-583f7fbb-b2a0-497d-a5c4-98c216b91a93.png)

Kann man ARCHIVIEREN und ALS GELESEN MARKIEREN weiter nach "links" schieben. Evtl. ist im Deutschen auch ALS GELESEN MARIEREN zu lang und man sollte es auf GELESEN kürzen?! Was meinst Du?

**Comment by RkcCorian** [comment]
Gerade nochmal nachgeschaut... am Tablet ist es weiter links und es passt ohne Probleme auf eine Zeile. Vermutlich muss also tatsächlich nur weiter "nach links" verschoben werden

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` nun korrekt

**Comment by RkcCorian** [comment]
Geil!! Hast es auch auf dem Handy hinbekommen. Beide Daumen 👍👍
