### ISSUE TITLE
iFrame im Hintergrund eingebrannt

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#1554]
Ich habe eben festgestellt, dass wenn ich ein iFrame anschaue und danach auf einen anderen Tab wechsle, das iFrame Bild sich im Hintergrund eingebrannt hat und nicht mehr verschwindet.

Version: v3.0.11-beta.0

Hier der iFrame
![iFrame](https://user-images.githubusercontent.com/95069101/151037447-809a8a47-665c-4950-b1a5-4ee280c84880.jpg)

und im anderen Tab ist es in den Spalten zwischen den Tabs noch zu sehen:

![iFrame2](https://user-images.githubusercontent.com/95069101/151037550-04318caf-63bc-4543-8691-9cd2ebf939d1.jpg)

Und eben habe ich noch festgestellt, dass es sich komplett über die Konfigurationsseite legt 
![iFrame WTF](https://user-images.githubusercontent.com/95069101/151037937-f16c79d4-8e14-401b-b6b1-05ca0402c50f.jpg)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/977

**Comment by Zefau** [comment]
deaktiviere mal bitte die Option "aufrechterhalten"

**Comment by SlipKoRn88** [comment]
Das habe ich bereits deaktiviert da die iframes sonst gar nicht angezeigt werden. Darüber hatten wir es ja heute Morgen schon. 

Mit mehrmals (ca. 5-8x) verschwindet es dann wieder.

**Comment by Zefau** [comment]
> und im anderen Tab ist es in den Spalten zwischen den Tabs noch zu sehen:

und

> Und eben habe ich noch festgestellt, dass es sich komplett über die Konfigurationsseite legt

Also das liegt an der Einstellung bzgl. Aufrechterhalten.

Hast du es überall deaktiviert? 

Ich schaff es leider nicht die Option ordentlich zu entbuggen :-\

**Comment by SlipKoRn88** [comment]
Hm ok, das ist dann seltsam. In jedem iFrame habe ich aufrechterhalten deaktiviert. 

Was auffällig ist, ist das immer nur das iFrame bugt, welches ich als letztes aufrechterhalten deaktiviert habe. 

Ich kann leider nicht helfen, da ich von programmieren 0 verstehe.

**Comment by Zefau** [comment]
bitte schau nochmal mit `v3.0.11` bei aktivierter Option

**Comment by SlipKoRn88** [comment]
Moin!
Leider scheint es noch immer Probleme zu geben. Siehe im Screenshot, links unten. Nach mehrmaligem F5 ist es jedoch erst mal verschwunden. Ich werde es weiter beobachten.
Die iFrames werden nun mit aktivierter Option alle angezeigt, wobei jedoch die eigentliche Funktion Aufrechterhalten wohl noch Probleme hat. Beim Wechseln durch die Tabs werden die iFrames neu geladen.
![Uploading Screenshot 2022-02-07 063919.jpg…]()

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/977
