### ISSUE TITLE
HIstoryGraph Änderung Datumsformat der x-Achse funktioniert nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1555]
`v3.0.11.-beta.0`
HH:mm|dd.MM. -> HH:mm bewirkt keine Änderung
![image](https://user-images.githubusercontent.com/84818934/151067592-82f49d08-7475-4a1d-ab89-486cb99a6fac.png)

![image](https://user-images.githubusercontent.com/84818934/151067777-ff328362-07e8-4755-a635-8e4b539bada3.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.11-beta.1` behoben sein

**Comment by stephan1827** [comment]
Da ist glaube ich was kapuut gegangen. In der X Achse werden mit der neuen Version keine Stunden und Datum angezeigt.
<img width="875" alt="Bildschirmfoto 2022-02-01 um 06 41 37" src="https://user-images.githubusercontent.com/2972703/151918555-4bfbc6e7-ca76-4e24-841d-4e8a1e21d9b3.png">

**Comment by Zefau** [comment]
Ich musste das Format ändern, insofern sind die Angaben in geschweifte Klammern zu setzen `{..}`. Ich kann das noch korrigieren, dass es automatisch konvertiert wird, wenn es bereit gesetzt ist. Wenn du es rauslöscht und neu setzt, dann sollte es sich von selbst beheben.

**Comment by stephan1827** [comment]
Ich habe versucht geschweifte Klammern hinzuzufügen aber ich bekomme einen Syntax Fehler. So sieht das aktuelle aus

`[
  {
    "position": "left",
    "name": "Leistung",
    "min": 0,
    "max": "dataMax",
    "minInterval": 1000,
    "axisLabel": {
      "showMaxLabel": true
    },
    "splitLine": {
      "show": false
    }
  },
  {
    "position": "right",
    "nameRotate": 270,
    "nameLocation": "center",
    "nameGap": 25,
    "name": "Ladung",
    "min": 0,
    "max": 100,
    "splitLine": {
      "lineStyle": {
        "color": "#404040"
      }
    }
  }
]`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/152027739-561a9ece-b231-4e9f-9960-6b6b33fa0818.png)
Ergebnis
![image](https://user-images.githubusercontent.com/84818934/152027801-6667672e-5443-4060-b4ff-493d02969d05.png)

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` sollte es nun auch rückwärts kompatibel sein

**Comment by mcuiobroker** [comment]
Passt soweit, kannst du bitte die Breite von den Balken definierbar einstellen oder breiter machen in Abhängigkeit von deren gezeigten Anzahl?

**Comment by Zefau** [comment]
Du meinst die Trennstreifen oder was genau? Kannst du vielleicht mit Screenshot markieren?

**Comment by mcuiobroker** [comment]
Die bunten Wertebalken
![image](https://user-images.githubusercontent.com/84818934/152593744-a68f11e6-6fcc-4a7e-bc48-6073562b9a9a.png)
