### ISSUE TITLE
Neues Chart kann nicht mehr angelegt werden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1557]
`v3.0.11-beta.0` auch schon mit `v3.0.10`
Neues Chart kann nicht mehr angelegt werden. Übernehmen wird blockiert.
Halteverbotszeichen auf dem ÜBERNEHMEN (bei Screenshot ausgeblendet)
![image](https://user-images.githubusercontent.com/84818934/151078796-7a5b7723-7861-4630-9125-bd43ce4eac11.png)

**Comment by Zefau** [comment]
Kannst du mal bei den optionalen Sachen rumspielen, ob diese ggf. fälschlicherweise required sind?

**Comment by mcuiobroker** [comment]
Hab ich alles verändert, keine Wirkung.

**Comment by MubiTec** [comment]
hab genau das gleiche Problem. kann das ohne Problem als historygraph speichern, aber sofort beim umstellen auf Chart ist der "Übernehmen"-Button ausgegraut.
Jarvis v3.0.10 von npm
Wenn ich irgendwie helfen kann durch Infos gerne!

**Comment by Zefau** [comment]
sollte mit `v3.0.11-beta.1` behoben sein

**Comment by MubiTec** [comment]
Ja, geht jetzt, danke dir!
