### ISSUE TITLE
Rolladen Datenpunkt stop über Datenpunkt Eigenschaften nicht einstellbar

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1560]
v3.0.10
Es soll über den Datenpunkt `stop` in jarvis ein anderer Wert als `true` gesendet werden.
Dazu habe ich unter Datenpunkt Eigenschaften folgendes eingetragen:
`stop`
Jedoch wird nach wie vor `true` gesendet.

### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/1559

<div type='discussions-op-text'>

<sup>Originally posted by **Bernd9000** January 26, 2022</sup>
Wie kann ich in den Datenpunkt Eigenschaften des Datenpunkt "stop" bei einem Rolladen angeben das "stop" gesendet wird?

Hab es versucht mit {"stop":"stop"} {"default":"stop"} ect, aber es wird immer nur true gesendet.

Laut [jarvis-Infos](https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/geraet/gewerk/rolllaeden-blind-v3) ist das einstellbar ?
Zitat:
stop ist lediglich der Datenpunkt an den die Aktion geschickt wird. Hier wird kein Wert geladen, der die Visualisierung beeinflusst. Der Wert, der geschickt wird, kann über die Datenpunkt Eigenschaften via stop festgelegt werden. Im Standard (default) wird true geschickt.</div>

**Comment by mcuiobroker** [comment]
Hast du mal "on":"stop" versucht?

**Comment by Bernd9000** [comment]
`{"on":"stop"}` und `{"setOn":"stop"}` funktioniert auch nicht

**Comment by mcuiobroker** [comment]
Hast du, da du ja bei Datenpunkt-Eigenschaften etwas eingetragen hast auch umgestellt auf value?
![image](https://user-images.githubusercontent.com/84818934/151175585-a966749e-d278-4222-b2b0-fe743423cf57.png)

**Comment by Bernd9000** [comment]
Geht leider auch nicht

**Comment by Zefau** [comment]
@Bernd9000 kannst du die Konfiguration nochmal screenshoten? Also wie hast du BlindLevelAction konfiguriert und wie den Stop-Datenpunkt?

`{"stop":"stop"}` muss in die Datenpunkt-Eigenschaften des Datenpunkts, bei dem du BlindLevelAction setzt. Nicht beim Stop-Datenpunkt.

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` sollte es passen

**Comment by Bernd9000** [comment]
Ja, Danke funktioniert, ist übrigens ein shelly 2.5 der nicht über den ioBroker shelly Adapter sondern direkt mit dem Mosquitto Broker verbunden ist.

Weil das gerade zum Thema paßt kurze Frage :-)
Kann ich auch den Datenpunkt  `activity` selbst einstellen oder muß Du das direkt als Außnahme programmieren?
Der shelly schreibt auf dem "activity" Datenpunkt  close,open,stop als Rückmeldung
Also "close" und "open" = Bewegung und "stop" = keine Bewegung
Hab es unter Datenpunkt Eigenschaften bei activity mal mit {"close":true,"open":true,"stop":false} versucht,
Aber das klappt leider nicht.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1582
