### ISSUE TITLE
Geräte Gewerk Heizung LevelBody Schrittweite wird nicht korrekt gespeichert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1561]
Änderung in den LevelBody Schrittweite Einstellungen zum DP settemperature wird nicht gespeichert (angezeigt?).
Gibt man 0.5 oder 0,5 ein, speichert es und schaut hinterher nach, ist der Werte wieder bei 1.
![image](https://user-images.githubusercontent.com/84818934/151213229-dcead294-6585-4e31-867f-cd46c94d4c2e.png)
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1476
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1478

**Comment by Algieio** [comment]
Hallo,
Kann es sein, das dies automatisch wieder auf 1 springt, weil die " Anzahl der Markierungen" auf 10 stehen?

Somit kann bei einer Spanne von 15-25 Grad nur in 1 Grad Schritte angezeigt und verschoben werden.

Die Anzahl der Markierungen muss auf 20 gestellt werden, dann geht es wahrscheinlich.

**Comment by Zefau** [comment]
> Kann es sein, das dies automatisch wieder auf 1 springt, weil die " Anzahl der Markierungen" auf 10 stehen?

Nein, ist unabhängig.

**Comment by RkcCorian** [comment]
Ist dass das gleiche Problem, wie hier?!
![image](https://user-images.githubusercontent.com/79741077/152573842-b60bea91-8af5-4b4e-a426-72e05cfab1b0.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.11-beta.4`

**Comment by mcuiobroker** [comment]
Passt wieder, Danke.
