### ISSUE TITLE
Neu angelegte MAP meldet Fehler bei Koordinaten

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1563]
Neue MAP mit zugeordnetem, schon vorhandenem Widget, meldet Fehler bei Koordinaten
![image](https://user-images.githubusercontent.com/84818934/151255641-83cc5bb8-6204-4e28-98e7-11fb28c89ed6.png)
![image](https://user-images.githubusercontent.com/84818934/151255666-950bf75f-bff0-47ea-8032-c88677374a86.png)
Alte MAP mit gleichem Widget funktioniert:
![image](https://user-images.githubusercontent.com/84818934/151255878-46698655-b393-4d1d-b1fc-97aeee2311bc.png)
?
![image](https://user-images.githubusercontent.com/84818934/151256036-12434310-5453-4d44-9d25-c9cc83f7850b.png)

**Comment by Zefau** [comment]
Deine Koordinaten für die Karte sind inkorrekt. Was hast du im Modul definiert? Wenn dort nichts: Was steht in ioBroker bei den Koordinaten in der übergreifenden Konfiguration?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/151256291-53e285ba-612b-4fc8-b60c-1d65491577f0.png)

**Comment by Zefau** [comment]
Mach mal bitte einen Screenshot der Modul Konfiguration.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/151256442-dc51ddd5-9823-4875-89a7-7a26982297f0.png)

**Comment by Zefau** [comment]
Und was steht in den ioBroker Systemeinstellungen?

![image](https://user-images.githubusercontent.com/14368811/151256611-3534c83e-64ca-49b7-982b-a8a86449cfd3.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/151256961-57b39813-17a2-411e-903a-781d125c406f.png)

**Comment by mcuiobroker** [comment]
Jetzt kommen die Fehler nicht mehr, aber trotzdem werden bei dem neuen, die Icons nicht angezeigt.
![image](https://user-images.githubusercontent.com/84818934/151257650-116c66ef-5344-42ad-8927-f9ed3773dd63.png)
Klicken auf die Icon und an die Position fahren funktioniert.

**Comment by mcuiobroker** [comment]
Jetzt kommt dieser Fehler, aber verspätet?
![image](https://user-images.githubusercontent.com/84818934/151259842-4f03252f-0b8f-477f-bda3-c15e3afcf435.png)

**Comment by Zefau** [comment]
Schau bitte noch mal mit `v3.0.11-beta.2`. Bin mir aber unsicher, ob ich den Fehler erwischt habe.

**Comment by mcuiobroker** [comment]
Es kommt jetzt der Hinweis:
![image](https://user-images.githubusercontent.com/84818934/152450360-0b4bc4f6-c0e4-4c5b-a15d-9025e13d10ab.png)

Aber es fehlen auch noch die Icons auf den Marker:
![image](https://user-images.githubusercontent.com/84818934/152450401-99c0e7e6-1665-418b-b52e-1813ddb5e390.png)

Komischerweise in einem Widget wird es angezeigt, in dem anderen als dupliziertes Widget nicht?
Beide haben die gleiche WidgetID
Funktioniert
![image](https://user-images.githubusercontent.com/84818934/152450596-e30c37b2-055f-4a51-a3a1-a6485285d561.png)
![image](https://user-images.githubusercontent.com/84818934/152450631-1ccc6841-e548-4b7f-889e-c1fd5cdb0e3a.png)
Funktioniert nicht
![image](https://user-images.githubusercontent.com/84818934/152450655-b0e1639e-cfa8-48e0-8fc9-c2f8efed6f14.png)
![image](https://user-images.githubusercontent.com/84818934/152450685-748fb74f-b175-42c1-83be-e2fa9b96cd99.png)

**Comment by Zefau** [comment]
Die Warnung kommt von Web Adapter. Jarvis nutzt ein eigenes Socket. Also kein jarvis Fehler.

Den Rest schau ich mir an.

**Comment by Zefau** [comment]
> Aber es fehlen auch noch die Icons auf den Marker:
> Komischerweise in einem Widget wird es angezeigt, in dem anderen als dupliziertes Widget nicht?
> Beide haben die gleiche WidgetID

Bekomme ich leider nicht nachgestellt - Funktioniert bei mir. Was steht denn im DOM bei den fehlenden Icons? Kannst du das mal prüfen?

**Comment by mcuiobroker** [comment]
Es hängt mit der color zusammen?
![image](https://user-images.githubusercontent.com/84818934/152700721-1d12bf3a-76b2-4e9d-b815-f62a17d4022c.png)

**Comment by Zefau** [comment]
Super, danke für die Analyse.

**Comment by Zefau** [comment]
bitte schau nochmal mit `v3.0.11`

**Comment by mcuiobroker** [comment]
Passt. Danke.
