### ISSUE TITLE
HomeKitTile Hide Widget Title and Icon (an) Anzeige inkorrekt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1564]
Hat man die Option Hide Widget Title and Icon ausgewählt, wird kein ausgewählter Inhalt mehr angezeigt, sondern nur noch der Gerätename angezeigt: (und die Optionsbeschreibung ist noch auf englisch)
![image](https://user-images.githubusercontent.com/84818934/151259499-17898b37-d029-445a-9811-2887d9c47728.png)
Widget-Einstellungen
![image](https://user-images.githubusercontent.com/84818934/151259451-a17499eb-d3c3-4e7b-9bd0-ff18446b5b17.png)

https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1497

Plötzlich wird auch nicht mehr der richtige Label angezeigt?
![image](https://user-images.githubusercontent.com/84818934/151265264-4cda2ff5-10a8-45c1-a0fd-7e15896ec31b.png)
Jetzt wird auch dort der Geräte-Label angezeigt.
Komischerweise ist bei den alten HKT alles OK:
![image](https://user-images.githubusercontent.com/84818934/151265421-78f0cec0-793f-41da-aa2c-05df3b822920.png)

**Comment by Zefau** [comment]
> Hat man die Option Hide Widget Title and Icon ausgewählt, wird kein ausgewählter Inhalt mehr angezeigt, sondern nur noch der Gerätename angezeigt: (und die Optionsbeschreibung ist noch auf englisch)

Kann ich so nicht bestätigen. Liegt in deinem Fall laut Screenshot wohl daran, dass du keinen Action State ausgewählt hast? Daher wird kein Icon und auch kein State gezeigt (wovon auch, da nichts ausgewählt).

> Plötzlich wird auch nicht mehr der richtige Label angezeigt?

Hängt vermutlich auch damit zusammen?

**Comment by mcuiobroker** [comment]
Nochmal mit ausgewähltem ActionState
![image](https://user-images.githubusercontent.com/84818934/152243523-1769e5c1-e49d-4ddd-aa91-4499d183c438.png)
Es wird der Geräte-Label angezeigt, nicht der Geräte-DP-Label.
![image](https://user-images.githubusercontent.com/84818934/152243599-3990ca8d-5232-43d1-8692-d8205dcf8628.png)
Alter HKT:
![image](https://user-images.githubusercontent.com/84818934/152243766-4d3f07c2-6531-4eef-8f25-fb0b1113e50c.png)

![image](https://user-images.githubusercontent.com/84818934/152243800-3ffe2bad-6e2c-4d62-a6cd-c36366a3550d.png)

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` sollte das nun passen

**Comment by mcuiobroker** [comment]
Passt. Danke.
