### ISSUE TITLE
Not work Settings page

### ISSUE THREAD

**Issue by itProfi** [Zefau/ioBroker.jarvis#1565]
Yesterday by paid license. All work successfuly. But today Settings page not work.
![Скриншот 27-01-2022 090259](https://user-images.githubusercontent.com/6728198/151301517-dfe868c3-755b-4145-a020-b1b5215920cc.jpg)

**Comment by mcuiobroker** [comment]
Yout have add `layout` or `devices` after  in the browser address
http://192.168.178.xx:8082/jarvis/index.html#/configuration/
-> http://192.168.178.xx:8082/jarvis/index.html#/configuration/layout

**Comment by itProfi** [comment]
Yes, when i try seconf scring one time, it work after that..

**Comment by Zefau** [comment]
@itProfi
