### ISSUE TITLE
LevelBody mit DP Eigenschaften funktioniert nur in einer Richtung

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1567]
Bug? Feature? Ich denke es war mal möglich.
Ziel: Den Wertebereich 0-254 mit LevelBody 0-100 abbilden.
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1502
Orig Wertebereich: 0-254
Nutzt man den LevelBody mit DP Eigenschaften Eintrag
```{"value":"val => parseInt(val/2.54)"}```
wird der richtige Wert im LevelBody angezeigt, wenn ich in `ioBroker den Wert anpasse`.
Setze ich den `Wert mit LevelBody` wird der ausgewählte Wert vom LevelBody gesetzt und dann aufgrund DP Eigenschaften angepasst.
siehe Video
![LevelBody mit DP Eigenschaften](https://user-images.githubusercontent.com/84818934/151384338-f1c1ba8e-3aea-4114-9c17-e4833f130eeb.gif)
LevelBody-Einstellungen (Layout)
![image](https://user-images.githubusercontent.com/84818934/151383024-100d4db0-3f26-4e5e-8e01-1682d0d59c0b.png)

**Comment by Zefau** [comment]
Wenn du den Wert auswählst, dann wird dieser zum ioBroker geschickt und dort gesetzt. Kommt der Wert dann wieder in jarvis an, wird deine angegebene Formel berechnet und der Wert wird durch 2,54 geteilt.

**Comment by mcuiobroker** [comment]
Der ioBroker-Wert wird  ja schon vorher mit Formel verändert und korrekt im LevelBody angezeigt. Setze ich dann einen anderen Wert im LevelBody müsste ja der ioBroker-Wert um das 2.54 fache multipliziert werden? 
Das oben würde bedeuten, dass man den LevelBody zum Setzen beim verarbeiteten Wert gar nicht nutzen kann?

**Comment by Zefau** [comment]
Jo, geht so nicht. Müsste einen Callback beim Setzen geben.

**Comment by mcuiobroker** [comment]
Machst du dann ein Feature Request daraus?

**Comment by Zefau** [comment]
Nein, kommt gleich was.

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` über einen neuen Callback in den Komponenten Optionen

**Comment by mcuiobroker** [comment]
Sollte dann bei Verarbeiteter Wert (value) unten Marker Labe (Pro) nicht
`(val, unit) => value` stehen?
![image](https://user-images.githubusercontent.com/84818934/152546870-7e1eeac1-69d3-4a21-ba3c-598a02e40cb4.png)
Egal was unten eintrage, ich erhalte nur den Wert, den ich auswähle in ioBroker. Dort muss aber der 2.54-fache Wert ankommen
`{"val":"value=> value*2.54"}` oder `{"value":"val=> val*2.54"}`
![image](https://user-images.githubusercontent.com/84818934/152548270-89e56a18-ada7-4135-989b-0e3eb2dbb999.png)

**Comment by mcuiobroker** [comment]
Bei {"min":"0","max":"254"} werden jetzt mehr Marker angezeigt als angegeben:
Anzahl der Markierungen: 10
![image](https://user-images.githubusercontent.com/84818934/152555385-b48e9c57-5dc4-4dbc-b14c-6ffef9cdf83e.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.11-beta.3`

Der Callback dient nur der Anzeige. Er zeigt andere Werte an als die, die genutzt werden.
Die Werte des Sliders ergeben sich auf `min` / `max` aus dem Gerät. Dort dann z. B. `{"min":0,"max":255}` für den Wertebereich von 0 bis 255. Um aber nur den Bereich 0-100 anzuzeigen und 0-255 darüber zu "mappen") würde dann im Callback etwas stehen wie `val => val / 2.55`.

**Comment by mcuiobroker** [comment]
Läuft. Danke.
