### ISSUE TITLE
Kopierbutton für IDs (Gerät) kopiert den Namen nicht die ID

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1568]
Im Gerät
![image](https://user-images.githubusercontent.com/84818934/151441638-53d5950e-0e33-4bd2-bfe5-33c01bf2dbfa.png)
Der Name wir kopiert, nicht die ID.

Widget kopiert die ID.

**Comment by funky4t** [comment]
Moin, Kopieren hab ich in den letzten Tagen öfter genutzt, dabei wäre es auch super, dem kopierten Device oder Widget ein `Copy` in den Namen zu schreiben. Wenn ein Widget bereits im Layout ist und du dann eine Kopie vom Widget erzeugts, siehst du in der Widgetliste leider nicht auf Anhieb, welches der zwei bereits im Layout ist. Da der Name zu 99,9% eh bearbeitet wird, wäre es cool einen Namen als  `Device(copy)` als Kopie anzulegen. Wollte da kein Issue zu aufmachen, ist vielleicht nur eine kleine aber hiflreiche Optimierung...

**Comment by Zefau** [comment]
> Der Name wir kopiert, nicht die ID.
>
> Widget kopiert die ID.

Verstehe ich nicht genau. Was meinst du? ID wird immer neu generiert. MUSS AUCH, da es eindeutig sein MUSS. Sonst gibt es Probleme. Widget sollte hier auch eine neue ID generieren. Ist dem nicht so? Über ein Beispiel wäre ich dir dankbar.

> Moin, Kopieren hab ich in den letzten Tagen öfter genutzt, dabei wäre es auch super, dem kopierten Device oder Widget ein Copy in den Namen zu schreiben. Wenn ein Widget bereits im Layout ist und du dann eine Kopie vom Widget erzeugts, siehst du in der Widgetliste leider nicht auf Anhieb, welches der zwei bereits im Layout ist. Da der Name zu 99,9% eh bearbeitet wird, wäre es cool einen Namen als Device(copy) als Kopie anzulegen. Wollte da kein Issue zu aufmachen, ist vielleicht nur eine kleine aber hiflreiche Optimierung...

Ok, das kann ich machen.

**Comment by mcuiobroker** [comment]
>Der Name wir kopiert, nicht die ID.

Wenn ich auf den Button klicke, soll ja die ID kopiert werden, es wird aber der Name kopiert.

**Comment by Zefau** [comment]
ah ok, das klingt falsch

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` sollte es nun korrekt kopieren

**Comment by mcuiobroker** [comment]
Danke. Passt.
