### ISSUE TITLE
Problem beim Laden mit timeout

### ISSUE THREAD

**Issue by jvpihole** [Zefau/ioBroker.jarvis#1570]
Habe folgendes Problem: 
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/1558

Gibt es eine Möglichkeit den Timeout hoch zusetzen?
Gibt es eine Möglichkeit diesen Fehler von Aussen zu erkennen, um darauf reagieren zu können? Im Fullybrowser (remote administration oder Fully Adapter) sehe ich nicht, dass da irgendwas schief gelaufen ist.

**Comment by Zefau** [comment]
Der Timeout ist fest und kann nicht geändert werden. Was steht denn in der Browser Konsole bzw. in dem aufklappbaren Bereich, wenn der Fehler erscheint? Timeout entsteht ja, wenn die Verbindung nicht hergestellt werden kann. Dann wird irgendwann abgebrochen.

**Comment by jvpihole** [comment]
Wo gibt's beim fully eine Konsole? Ich hab nur einen roten Bildschirmhintergrund mit den oben beschriebenen Texten.

**Comment by Zefau** [comment]
Einfach den Dropdown aufklappen der beim Timeout gezeigt wird.

**Comment by jvpihole** [comment]
Da wird kein Dropdown angezeigt.
![image](https://user-images.githubusercontent.com/59318539/151881217-8d049849-3153-466d-b5bf-916a1bc00a4f.png)

**Comment by Zefau** [comment]
Das `Hide Log (4)` sollte klappbar sein?

**Comment by jvpihole** [comment]
Fehlermeldung heisst:
Connecting to http://iobroker:8400
Failed connecting http://iobroker:8400
Die zwei Zeilen erscheinen zweimal.

**Comment by Zefau** [comment]
Dann ist der Socket unter http://iobroker:8400 für jarvis nicht erreichbar. Was passiert, wenn du es direkt im Browser öffnest?

Funktioniert es auf anderen Geräten?

**Comment by jvpihole** [comment]
Ich hab zwei baugleiche Tablets mit fully. Auf beiden tritt der Fehler manchmal auf. Auf allen anderen Geräten (PC, Tablet, Handy) hab ich kein Problem damit (allerdings kein fully). Wenn ich direkt  http://iobroker:8400 im fully eingebe, bekomme ich : This is the jarvis socket.io port!. Wie gesagt Fehler tritt nicht permanent auf.

**Comment by jvpihole** [comment]
Hab im Logcat vom fully noch ein paar Meldungen gefunden. Vielleicht hilfts:
01-31 23:02:32.468  2145  2532 E chromium: [ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -107
01-31 23:02:32.489  2145  2532 E chromium: [ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -107
01-31 23:02:33.660  2145  2532 E chromium: [ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -107
01-31 23:02:33.672  2145  2532 E chromium: [ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -107
01-31 23:02:35.040  2145  2532 E chromium: [ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -107
01-31 23:02:35.057  2145  2532 E chromium: [ERROR:ssl_client_socket_impl.cc(996)] handshake failed; returned -1, SSL error code 1, net_error -107
01-31 23:04:55.538  2145 28699 I BufferQueueProducer: [SurfaceTexture-0-2145-0](this:0x7cd3e4e000,id:0,api:4,p:344,c:2145) queueBuffer: slot 4 is dropped, handle=0x7cee224d80

**Comment by Zefau** [comment]
Da ist offensichtlich etwas mit dem SSL Handshake falsch gelaufen. Ist sehr wahrscheinlich kein jarvis Fehler.

Läuft die Verbindung denn überhaupt über SSL (also `https://`) ?

**Comment by jvpihole** [comment]
Nein, es wird kein SSL verwendet

**Comment by Zefau** [comment]
Dann mal googeln, warum der fully so eine Fehlermeldung auswirft.

**Comment by jvpihole** [comment]
Alles klar, probiere jetzt noch die Einstellung Ignore ssl-Error im Fully.
