### ISSUE TITLE
Falsche Widgetgröße auf weiteren Tabs

### ISSUE THREAD

**Issue by vwccvr6** [Zefau/ioBroker.jarvis#1571]
Moin, 

mir ist ein vermeintlicher Bug aufgefallen. Auf der Dashboardseite funktionieren die Auswahl der Widgetgröße ohne Probleme. In einem anderen Tab ist dieses nicht der Fall. 

Im Bild kannst du sehen, dass beide Widgets von der "gezogenen" Größe her gleich sind. Die Pixel jedoch anders sind. Hier scheint die Berechnung nicht zu funktionieren. 

Somit hat jedes Widget (Auch wenn sie gleich groß sein sollen und optisch sind) eine andere Pixelgröße. 
![Größen_Bug_anderer_Tab](https://user-images.githubusercontent.com/97767702/151547689-5afab2b1-18dc-4032-bcbd-d409b66c698e.png)

Version: v3.0.7

Beste Grüße

**Comment by Zefau** [comment]
Bitte auf 3.0.11 von GitHub gehen. Damit sollte es passen.

**Comment by Zefau** [comment]
@vwccvr6

**Comment by vwccvr6** [comment]
Moin,

sorry für die späte Rückmeldung, bin jetzt erst dazu gekommen. Ich habe auf die Version geupdatet, allerdings besteht der Fehler weiterhin.

**Comment by Zefau** [comment]
@vwccvr6 sollte mit v3.1 inzwischen passen?
