### ISSUE TITLE
Update der PrimaryColor über ioBroker DP wird nur teilweise aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1572]
Er aktualisiert nur die SwitchAction, nicht die Icons
![image](https://user-images.githubusercontent.com/84818934/151573684-ce48f47c-a11b-41c4-a771-30d37e768b9d.png)
Dunkelblau wurde eingegeben.
Man muss F5 betätigen:
![image](https://user-images.githubusercontent.com/84818934/151573852-bbd2bc0a-4bfd-4115-9d63-ba7104642ae9.png)

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` sollte das passen

**Comment by mcuiobroker** [comment]
Passt.Danke.
