### ISSUE TITLE
Status in ButtonAction verdreht / Statusicon für Zigbee-Geräte falsch

### ISSUE THREAD

**Issue by 1337gut** [Zefau/ioBroker.jarvis#1573]
**Prerequisites / Voraussetzungen**
- Version: v3.0.10
- Fehler / Screenshot der Browser Konsole (F12): 
![image](https://user-images.githubusercontent.com/8449450/151663924-c9e7d47b-fad9-4dee-b054-1733d1150e3c.png)

**Describe the bug / Beschreibe den Fehler**
Der Status im Element ButtonAction ist verdreht. Statt "Turn On" im ausgeschalteten Zustand wird "Turn Off" gezeigt und andersherum.
Zudem wird die Anzeige des Status-Icons (ganz vorne) je nach Protokoll unterschiedlich interpretiert. Im Screenshot sind alle Geräte ausgeschaltet, die Zigbee-Geräte Schlafzimmerstehlampe und Küche werden jedoch als eingeschaltet angezeigt.

**Screenshots**
![image](https://user-images.githubusercontent.com/8449450/151664152-87bc06a9-85a5-42d6-ad63-f615502b6794.png)

**Comment by 1337gut** [comment]
Klar, kein Problem:
![image](https://user-images.githubusercontent.com/8449450/151859191-c00c5494-dec7-4651-9c39-2cc7e34d43c7.png)
(nicht wundern, die Schlafzimmerlampe ist noch dazu gekommen - auch Zigbee, selbes Bild)
Und so sieht der passende Datenpunkt dazu aus:
![image](https://user-images.githubusercontent.com/8449450/151859399-2af9fe96-91d3-4d34-a9cd-bf5f042e0ab1.png)

**Comment by Zefau** [comment]
mit `v3.0.11-beta.2` nun gedreht

**Comment by Zefau** [comment]
@1337gut funktioniert es? Kann ich das Issue schließen?

Und off-topic Frage: Hast du eine Email-Adresse, die mit `ego@` beginnt? Ich hab für die bei PayPal hinterlegte Email-Adresse bei der Rechnungszustellung einen Mail Delivery System Fehler erhalten. Hast du die Rechnung per Email erhalten?

**Comment by 1337gut** [comment]
Blöde Frage, aber wie installiere ich die Beta? 🙈

**Comment by Zefau** [comment]
Direkt von Github. In ioBroker über die Katze und dann die Github URL, quasi wie hier gezeigt https://mcuiobroker.gitbook.io/jarvis-infos/v3-fuer-einsteiger/installation-jarvis-v3#upgrade-von-v2.2.3-auf-v3.0.0-alpha

**Comment by 1337gut** [comment]
Ah, ich hatte es zwar über Github probiert, aber direkt über den Github-Reiter mit dem Dropdown-Menü. Danke!

Jetzt scheint alles zu passen, vielen Dank!

**Comment by 1337gut** [comment]
> Und off-topic Frage: Hast du eine Email-Adresse, die mit `ego@` beginnt? Ich hab für die bei PayPal hinterlegte Email-Adresse bei der Rechnungszustellung einen Mail Delivery System Fehler erhalten. Hast du die Rechnung per Email erhalten?

Ja, das ist korrekt. Eine Rechnung habe ich nicht erhalten, ist aber auch nicht schlimm. Mag dein Server vielleicht kein Greylisting?

**Comment by Zefau** [comment]
Verschicke die Emails über meinen Email-Anbieter `mailbox.org`. Habe auch beim manuellen Versuch denselben Fehler erhalten.

Würde dir gerne die Rechnung zukommen lassen, da dort auch die Lizenz dran hängt, falls du mal ioBroker neu installieren solltest.

**Comment by 1337gut** [comment]
Ich habe den Server mal neugestartet und DNSBL deaktiviert.

**Comment by 1337gut** [comment]
Ist angekommen, danke!
