### ISSUE TITLE
Keine automatische Aktualisierung des Kalenderwidgets

### ISSUE THREAD

**Issue by SarasarMQ** [Zefau/ioBroker.jarvis#1574]
System: Android 7 mit einem Samsung S2 Tablet
Browser: Fully Browser v1.45
Jarvis: v3.0.10

Das Kalenderwidget zeigt zwar beim öffnen die aktuellen Kalendereinträge an, aber es erfolgt kein automatischer Refresh.
Erst durch manuellen Eingriff (F5, Neustart des Browsers) werden die Daten aktualisiert. Auch auf ein Tageswechsel hin wird nicht reagiert.

Alle anderen Widgets, die zeitgesteuert sind, funktionieren korrekt (z.B. Uhrzeit, Wetterstation usw.)

Einstellungen am Browser haben zu keiner Änderung geführt und da die anderen Widgets korrekt funktionieren, kann es nicht direkt an dem Browser liegen.

**Comment by Zefau** [comment]
sollte mit `v3.0.11-beta.1` behoben sein

**Comment by pphlwmarcel** [comment]
leider ist der Fehler bei mir nach einem Update auf v3.0.11-beta.1 weiter vorhanden.
Die Uhr im Kalender-Widget bleibt auf dem Wert stehen bei dem diese aufgerufen wurde. Aktualisieren der Webseite führt auch zur Aktualisierung der Uhrzeit.
Neustart des Adapters (ohne manuellen Reload der Seite) führt jetzt auch zum aktualisieren der Uhrzeit, falls das hilft den Fehler einzugrenzen.

![konsole](https://user-images.githubusercontent.com/14854093/152146119-92667e71-da74-405d-bc3f-cb4920faf54b.png)

**Comment by Zefau** [comment]
@SarasarMQ

**Comment by MiniAdnim** [comment]
habe gleiches problem, ist aber nicht besser geworden mit der aktuellen beta version!?
kann ich infos liefern? es gibt halt keine Fehler nix im LOG

**Comment by Zefau** [comment]
will be solved via https://github.com/Zefau/ioBroker.jarvis/issues/1656
