### ISSUE TITLE
DisplayImage Modul gibt kein svg bild wieder

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#1575]
Das DisplayImage gibt kein QR Code in svg Stil wieder

Beispiel: fb-checkpresence.0.guest.wlanQR

**Comment by Zefau** [comment]
Kannst du bitte den Inhalt des Datenpunkts posten? Ich nutze den Adapter nicht und würde dann mit einem eigenen Datenpunkt simulieren.

**Comment by duczz** [comment]
@Zefau Ging in der V2 bereits
https://github.com/Zefau/ioBroker.jarvis/issues/641

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.11-beta.4`

**Comment by duczz** [comment]
Nope, klappt noch nicht

**Comment by Zefau** [comment]
Bei mir geht's

**Comment by Zefau** [comment]
Das ist mein Code https://github.com/Zefau/ioBroker.jarvis/issues/641#issuecomment-771177730

**Comment by duczz** [comment]
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 35 35"><path fill="white" d="M1 1h7v7h-7zM11 1h4v1h1v-1h3v1h1v1h-2v-1h-1v1h-2v1h-1v-1h-2v-1h-1zM20 1h1v1h-1zM22 1h1v1h-1zM27 1h7v7h-7zM2 2v5h5v-5zM10 2h1v1h-1zM21 2h1v1h-1zM25 2h1v2v1h-1v1h-2v-2h1v-2h-2v-1h1v-2h1v-1h1v-1h-1v-1h3zM28 2v5h5v-5zM3 3h3v3h-3zM9 3h1v1h2v2h-1v-1h-1v3h1v-1h1v1h1v1h-1v1h1v-1h1v2h-2v2h1v3h2v-2h1v-1h-1v-1h1v-2h-1v-3h-1v-1h2v-1h1v1h1v2h-1v-1h-1v1h1v1h1v1h1v1h1v1h-2v-1h-1v1h1v1h-1v1h2v-1h1v1h2v1h-2v1h3v1h1v1h-2v-1h-1v2h-1v-2h-1v-2h-3v3h-1v-1h-3v-3h-1v-3h-1v-2h-1zM17 3h1v1h2v1h-3zM20 3h1v1h-1zM29 3h3v3h-3zM13 4h1v1h-1zM15 4h1v1h-1zM21 4h1v1h-1zM20 5h1v1h-1zM13 7h1v1h-1zM19 7hv1h-1zM26 32h4v1h1v1h-3v-1h-1v1h-2v-1h1zM31 32h1v1h-1zM9 33h1v1h-1zM32 33h1v1h-1z"/></svg>`

**Comment by Zefau** [comment]
aus deinen `path` muss `fill="white"` weiß raus bzw. muss sonst dein Hintergrund != weiß sein.

**Comment by duczz** [comment]
Die Farbe vom QR code kann man im Adapter hinterlegen, default ist black und dunkler hintergrund mit schwarzer schrift ist doof

**Comment by Zefau** [comment]
Hast du Dark Mode an?

**Comment by duczz** [comment]
jup

**Comment by Zefau** [comment]
Welchen Browser nutzt du? Firefox und Chrome klappt bei mir. Was zeigt er im DOM an?

**Comment by duczz** [comment]
Nutze Chrome, was ist Dom?

**Comment by Zefau** [comment]
Kannst du einen Screenshot deiner Konfiguration machen?

**Comment by Zefau** [comment]
Ich vermute du hast `fb-checkpresence.0.guest.wlanQR` oben bei URL eingetragen, statt es über ein Gerät zu machen / ein Gerät auszuwählen?

**Comment by duczz** [comment]
Genau das war's, nun klappt es, top 👍🏻. 
Hatte beides gepflegt.
Dann hab ich dies vermutlich in V2 schon hinterlegt gehabt und in v3 kam es erst zu Problemen
