### ISSUE TITLE
Kopie eines Tabs im Layout erzeugt Widget Dubletten

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#1576]
Ich hab ein Tabs im Layout (Büro) kopiert um einen neuen Raum in gleiche Struktur aufzubauen. Dabei stelle ich fest, dass die im ursprünglichen Layout existierenden Widgets dupliziert werden. Nach dem Löschen des zuvor kopierten Tabs bleiben die Widget Dubletten erhalten. Siehe Widgets nach Kopier und Löschen: 

![grafik](https://user-images.githubusercontent.com/57875762/151800991-a1e9563f-971e-4ff2-8627-6485ca419f2a.png)

Erwartet hätte ich, dass die Tab-Kopie die gleichen Widgets hat wie der Ursprungstab, also die Summe der vorhandenen Widgets durch Kopie des Tabs nicht erhöht wird. Sollte die Duplizierung der Widgets gewollt sein, wäre es ebenfalls hilfreich dahinter "Kopie" anzufügen, da sonst nach Tab-Kopie sehr unklar ist, ob man das Widget auf dem Kopie-Tab bearbeitet oder auf dem Ursprung.

Ich bin auf der v3.0.11-beta.0

**Comment by Zefau** [comment]
gewolltes Verhalten, siehe https://github.com/Zefau/ioBroker.jarvis/issues/1310#issuecomment-999513431

denkbar wäre die Einführung einer "Kopie als Klonen" Optionen, die neben einer "Kopie als Referenz" besteht.

**Comment by funky4t** [comment]
Ich close mal, sorry, die #1310 hatte ich beim suchen nicht gesehen, ich hänge da nochmal nen Satz an 1310
