### ISSUE TITLE
Widget DateTime wird nicht aktualisiert

### ISSUE THREAD

**Issue by pphlwmarcel** [Zefau/ioBroker.jarvis#1578]
Version v3.0.11-beta.1 (bestand auch in v3.0.10 und vorher)
Die Uhr im Kalender-Widget bleibt auf dem Wert stehen bei dem diese aufgerufen wurde. Aktualisieren der Webseite führt zur Aktualisierung der Uhrzeit. Automatisch wird die Uhrzeit aber nicht aktualsiert.
Neustart des Adapters (ohne manuellen Reload der Seite) führt zum Aktualisieren der Uhrzeit, falls das hilft den Fehler einzugrenzen.

Andere Status (beim Wetter konnte ich es noch nicht prüfen) werden ohne Probleme aktualisiert, wenn diese sich ändern (z.B. Türsensoren und ähnliches)

Browserkonsole zeigt keine Auffälligkeiten. Getestet mit FireHD FullyBrowser und Firefox 96.0.3

![152146119-92667e71-da74-405d-bc3f-cb4920faf54b](https://user-images.githubusercontent.com/14854093/152184255-1c57c448-4b17-4be0-8251-72643c6fafb2.png)
.

**Comment by Zefau** [comment]
Bitte Screenshot der Konfiguration des Moduls

**Comment by pphlwmarcel** [comment]
![2022-02-03 14_01_57-png](https://user-images.githubusercontent.com/14854093/152348108-9ad33fea-8547-48b6-a6d2-65720e81dfa6.png)
Reicht dir das oder benötigst du noch was anderes?

**Comment by Zefau** [comment]
> Die Uhr im Kalender-Widget 

OK danke dir. Du meinst denn hier wahrscheinlich DateTime? :-)

**Comment by pphlwmarcel** [comment]
Sorry, natürlich DateTime wie es auch in der Überschrift des Issues steht ;)

**Comment by Zefau** [comment]
Ich hab die Konfiguration bei mir übernommen und bei mir aktualisiert die Zeit. Gibt es etwas in deiner Konfiguration was ich noch beachten muss? Tritt es erst unter bestimmten Umständen auf?

**Comment by pphlwmarcel** [comment]
Gibt es da Abhängigkeiten zu anderen Adaptern was Sockets oder anderes angeht? 
mir ist zumindest nichts bewusst was andere Abhängigkeiten der Konfiguration auslösen könnte. Es tritt immer auf. Egal ob auf dem Tablet oder auf einem Windows PC

**Comment by Zefau** [comment]
Kannst du testweise die 3 Optionen deaktivieren?

**Comment by pphlwmarcel** [comment]
Welche Optionen? Stadt, Sonnenaufgang und KW?

**Comment by Zefau** [comment]
Jo

**Comment by Zefau** [comment]
@pphlwmarcel und? Geht es ohne Optionen?

**Comment by pphlwmarcel** [comment]
Ohne Optionen geht es.
Ich hab nach und nach die Optionen wieder aktiviert: 
- Mit Option Stadt geht es auch. 
- mit Option Stadt und KW geht es auch. 
- nach Reaktivierung aller Optionen scheint es aber auch weiterhin zu gehen. 

Ich hab nach dem Update von jarvis 2 auf 3 an dem Widget nichts verändert gehabt bisher.

**Comment by Zefau** [comment]
Dann geht es also? Merkwürdig. 

Ich hätte mir vorstellen können, dass es am Sonnenauf- und -Untergang liegt. Hierzu werden die Koordinaten aus ioBroker gezogen (die, die dort konfiguriert sind), um die Zeiten zu berechnen. Hätte mir vorstellen, dass hier etwas nicht korrekt funktioniert.

Sonst würde ich das Issue schließen und wenn es wieder vorkommt, dann öffnest du es wieder?
