### ISSUE TITLE
Use foreign device state values as input for state or icon style ("Binding")

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#158]
https://forum.iobroker.net/post/499239

> kann ich auch im Datenpunk Stil eines Geräts einen anderen Datenpunkt als abfrage nehmen?
Also habe z.b. den Temperaturwert von Gerät 1 und ich möchte, dass dieser Temperaturwert rot angezeigt wird, wenn die Batterie unter 20% fällt.

**Comment by Zefau** [comment]
Binding has landed in v3 now (with `v3.0.0-alpha.63`)!

Can be used via `{ ...state... }`, e.g. `{0_userdata.0._test.level}`.
Example:
```
{
   "{0_userdata.0._test.level}=100":"window-shutter",
   "{0_userdata.0._test.level}<100":"window-shutter-open"
}
```

![screencapture-localhost-3001-1630691244403](https://user-images.githubusercontent.com/14368811/132046828-76b0ef54-2521-45d2-8195-b7dda4416719.png)

**Comment by Zefau** [comment]
@mcuiobroker willst du dir das mal anschauen? :-)

**Comment by mcuiobroker** [comment]
Würde ich gerne. Es wird nur .61 angezeigt.

**Comment by mcuiobroker** [comment]
Können auch mehrfach Bindings geprüft werden?
`{
   "{0_userdata.0._test.level}=100 &&{0_userdata.0._test.levelnew}=200":"window-shutter",
   "{0_userdata.0._test.level}<100 && val":"window-shutter-open"
}`
oder anders?

**Comment by Zefau** [comment]
Nein. Ist das wirklich notwendig so komplizierte Abfragen machen zu können?

**Comment by mcuiobroker** [comment]
Also man sollte mindestens den Statewert und ein zusätzlichen miteinander abfragen können, um dann eine Farbe oder ein Effekt ändern/auslösen zu können. ({"val":"<=100" && "{0_userdata.0.test}":"50" : {"color":"green"}})

**Comment by mcuiobroker** [comment]
Funktioniert der Upload nicht mehr?

**Comment by Zefau** [comment]
Ne, muss ich gleich bei schauen

**Comment by mcuiobroker** [comment]
Schon das Problem bzgl Upload gefunden?

**Comment by Zefau** [comment]
Ist jetzt hochgeladen.

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.64` nun auch mit mehrfachen Bedingungen:

```
{
   "{0_userdata.0._test.level}>50 && {0_userdata.0._test.state}=false":"window-shutter",
   "default":"window-shutter-open"
}
```

![image](https://user-images.githubusercontent.com/14368811/132142486-552a4afe-4c6c-459a-b35e-6e4ca741edba.png)

**Comment by mcuiobroker** [comment]
Muss man den Statewert dann auch mit Objekt-DP angeben oder reicht "val"?

**Comment by Zefau** [comment]
Dafür reicht `{val}`.

**Comment by mcuiobroker** [comment]
Prima. Teste ich morgen. Danke.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.65` getestet mit kleinem Beispiel: FUNKTIONIERT
`{
  "{0_userdata.0.Power0}>10 && {val}=100": "mdi-trash",
  "{0_userdata.0.Power0}<10 && {val}=100": "mdi-power"
}`
![v3-alpha65-Bindings mit mehreren Werten](https://user-images.githubusercontent.com/84818934/132145366-4765012a-4438-417a-a741-797a84be588d.gif)

**Comment by mcuiobroker** [comment]
Kann dann geschlossen werden?

**Comment by disaster123** [comment]
@Zefau geht das auch für den Icon Stil?

**Comment by Zefau** [comment]
Im Gerät, ja.

**Comment by disaster123** [comment]
@Zefau OK super - gibt es eine Möglichkeit an die Werte des Secondary state via JS zu kommen?

```
zum Debug:
(value, val, state, device) => console.log(device.states)
```
zeigt leider keine val Werte der device.states sondern nur die Eigenschaften:
```
{__ob__: Mt}
disable: (...)
status: (...)
_any: (...)
__ob__: Mt {value: {…}, dep: vt, vmCount: 0}
get disable: ƒ ()
set disable: ƒ (e)
get status: ƒ ()
set status: ƒ (e)
get _any: ƒ ()
set _any: ƒ (e)
[[Prototype]]: Object
```

**Comment by Zefau** [comment]
`device.states.disable.val` ?

**Comment by disaster123** [comment]
Leider nicht denn (hier am Beispiel status und nicht disable):
```
(value, val, state, device) => console.log(device.states.status)


{…}
IconButtonActionConfig: (...)
action: (...)
actionElement: (...)
bodyElement: (...)
display: (...)
iconStyle: (...)
showState: (...)
state: (...)
stateKey: (...)
__ob__: Mt {value: {…}, dep: vt, vmCount: 0}
get IconButtonActionConfig: ƒ ()
set IconButtonActionConfig: ƒ (e)
get action: ƒ ()
set action: ƒ (e)
get actionElement: ƒ ()
set actionElement: ƒ (e)
get bodyElement: ƒ ()
set bodyElement: ƒ (e)
get display: ƒ ()
set display: ƒ (e)
get iconStyle: ƒ ()
set iconStyle: ƒ (e)
get showState: ƒ ()
set showState: ƒ (e)
get state: ƒ ()
set state: ƒ (e)
get stateKey: ƒ ()
set stateKey: ƒ (e)
[[Prototype]]: Object
```

**Comment by Zefau** [comment]
Stimmt, geht aktuell tatsächlich nicht mehr. Ich musste in einer alpha Version die Datenstruktur wegen den Bindings anpassen, daher wird es nicht mehr durchgereicht.

**Comment by disaster123** [comment]
Irgendeine Möglichkeit?

**Comment by ChrisGitHub42** [comment]
Ich bin gerade etwas überfordert mit dieser Thematik, eigentlich ganz simpel...

Ich habe eine Shelly RGBW Glühbirne und möchte dass das Icon in der aktuell eingestellten Farbe angezeigt wird...
Den Wert finde in im Object/lights/rgbw - als role wird "level.color.rgb" angezeigt um im Wert ist der Hexcode der Farbe.

Was muss ich da nun genau im "Icon Stil (JSON Format) eintragen?

**Comment by Zefau** [comment]
`{"color":"{val}"}`

**Comment by ChrisGitHub42** [comment]
sorry, ich hab mich mit allen JSON Einträgen bisher endlos abgemüht... Im "val" muss ich jetzt ja irgendwie sagen, woher er den val nehmen muss...

Leider habe ich auch via Google kein Beispiel gefunden...

**Comment by Zefau** [comment]
`{val}` ist der Wert des aktuellen Datenpunkts. Wenn du einen anderen Datenpunkt brauchst, dann einfach den Datenpunkt eintragen.

Ansonsten mal unter https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/geraet/binding schauen.

**Comment by Zefau** [comment]
Einfach `{"color":"{val}"}` - mehr nicht. Der Datenpunkt `shelly.0.SHCB-1#98CDAC1E6474#1.lights.rgbw` steht im Gerät ja bereits in der "Datenpunkt-Anzeige".

**Comment by ChrisGitHub42** [comment]
Es ist ja der "Power Button", also der "Switch", dieser ist aber auch im "lights"

Als Datenpunkt für die Icon Color soll er aber "rgbw", respektive "leve.color.rgb" nehmen, es funktionieren aber weder:
- {"color":"level.color.rgb"}
- {"color":"rgbw"}

Trage ich zum Test einfach "blue" ein, oder sonst ein Hex Wert geht es aber

Problem wird wohl sein, dass im Datenpunkt als Hex Wert jedoch #00FF0000 steht, hat meiner Meinung nach 2 Stellen zu viel...

**Comment by Zefau** [comment]
Schau doch ins Wiki ;-)

Wenn du den Wert eines anderen Datenpunkts brauchst, dann diesen explizit angeben:
```
{"color":"{shelly.0.SHCB-1#98CDAC1E6474#1.lights.rgbw}"}
```

**Comment by ChrisGitHub42** [comment]
das haben wir nun soweit alles - Problem ist jetzt nur noch, das warum auch immer, im Shelly im RGBW Feld zwei 0 zu viel im Wert sind..., anstatt #00FF0000 was aktuell als Wert drin steht, müsste JSON/Jarvis nur #00FF00 haben... Sprich ich muss die zwei Stellen von Rechts noch irgendwie elimnieren...

**Comment by Zefau** [comment]
Sollte auch mit den zwei 00en mehr funktionieren. Die definieren den Alpha-Kanal.

**Comment by ChrisGitHub42** [comment]
jein, bei:
- {"color":"{shelly.0.SHCB-1#98CDAC1E6474#1.lights.rgbw}"} --> Icon ist "weiss", obwohl #00FF0000 im Datenpunkt steht
- {"color":"rgbw"} --> Icon ist "weiss"
- {"color":"{rgbw}"} --> Icon ist "weiss"

- {"color":"#00FF0000"} --> Icon "verschwindet", weil er wohl keine gültige Farbe auslesen kann
- {"color":"#00FF00"} --> das Icon wird korrekt in der Farbe "Grün" angezeigt

Bei weissen Icon liest er wohl schon wo was aus, da wenn gar kein Wert eingetragen ist, das Icon im "default blau" von Jarvis ist...

**Comment by Zefau** [comment]
```
{"color":"rgbw"} --> Icon ist "weiss"
{"color":"{rgbw}"} --> Icon ist "weiss"
```
Das sind keine gültigen Varianten.

`{"color":"#00FF0000"}` ist vermutlich einfach nicht sichtbar, weil `00` im Alpha-Kanal 0% bedeutet.

**Comment by ChrisGitHub42** [comment]
also geht keiner...?

Wir sind beim Button Ein/Aus-Schalter im Datenpunkt:
shelly.0.SHCB-1#98CDAC1E6474#1.lights.Switch

Hier soll das Icon die Farbe haben, welche eben im Datenpunkt:
shelly.0.SHCB-1#98CDAC1E6474#1.lights.rgbw
--> hier ist eben der Wert als Beispiel der Farbe eingetragen im Format "#00FF0000"

Eingetragen ist...

Gefühlt alle möglichen Varianten sind durchprobiert...

**Comment by Zefau** [comment]
Will sagen: Es funktioniert (auch bei dir), aber der Wert `#00FF0000` müsste `#00FF00FF` (bzw. auch nur `#00FF00`) sein. Der Alpha-Kanal führt dazu, dass du es nicht siehst, trotz dessen, dass der Wert korrekt übernommen wird.

**Comment by ChrisGitHub42** [comment]
gut, aber der Wert ist nun mal #00FF0000 der im Datenpunkt .lights.rgbw drin steht...
Wenn es eine andere Farbe ist, dann ist es #XXXXXX00

Also Lösung, man müsste noch eine Formel machen, dass er nur die ersten 7 Zeichen beachtet...

Nur haben wir das Gefühl, dass der Wert gar nicht erst angesteuert wird...

Da:
{"color":"#00FF0000"} --> Icon "verschwindet", weil er wohl keine gültige Farbe auslesen kann

--> Dieses Verhalten haben wir NUR bei dieser Eingabe... 
Würde also wie du sagst, 
{"color":"{shelly.0.SHCB-1#98CDAC1E6474#1.lights.rgbw}"}
den Wert #00FF0000 als Color Eintragen, müsste es sich genau gleich Verhalten, wie oben... Nur tut es dass eben nicht...?
