### ISSUE TITLE
Bei manchen Slider wird die Teilung nicht mehr angezeigt.

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#1580]
v3.0.11-beta.2

Bei den Slider der Heizung werden die Teiler nicht mehr angezeigt. Beim Laden der Seite sieht man die Markierung für einen kurzen Augenblick aber dann ist sie weg.
<img width="793" alt="Bildschirmfoto 2022-02-04 um 06 44 18" src="https://user-images.githubusercontent.com/2972703/152478947-8f136b74-8744-4dfa-9392-172d06f65a86.png">

Beim Licht ist die Teilung noch OK. Hier sind die Einstellungen für die Heizung. Ich habe erst gedacht das Problem kommt von der
Schrittweite < 1 aber auch eine Schrittweite von 1 löst das Problem nicht.
<img width="497" alt="Bildschirmfoto 2022-02-04 um 06 44 48" src="https://user-images.githubusercontent.com/2972703/152479031-46f0b1aa-0926-4c9f-b03e-c9f8dc37b8cb.png">

**Comment by Zefau** [comment]
Ich müsste das Ding nochmal auf ihren, deswegen wahrscheinlich.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.11-beta.3`

**Comment by stephan1827** [comment]
Die Teilung ist wieder da, aber irgendwie stimmt jetzt die Beschriftung nicht mehr. Auf dem Handy sind Beschriftung nicht mehr lesbar, weil sie sich überlappen. Ich meine das war vorher so das er die Teilung zwar angezeigt hat aber nur so viele Beschriftet hat wie nebeneinander passen.

Auf dem Tablet sieht das so aus
<img width="1180" alt="20220205_161038871_iOS" src="https://user-images.githubusercontent.com/2972703/152649433-b8a2186e-9005-42da-9441-3e486fb25f9a.png">

und auf dem Handy so

![Screenshot_20220205-171702](https://user-images.githubusercontent.com/2972703/152651395-fcac9461-ff6e-4811-9008-61ab4121b531.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.11-beta.5`

**Comment by stephan1827** [comment]
jetzt passt es wieder, vielen Dank
