### ISSUE TITLE
Pro Version und Meldungen dazu

### ISSUE THREAD

**Issue by mproper23** [Zefau/ioBroker.jarvis#1581]
Hallo,

habe geraden auf die aktuellste Stable Version geupdatet und bin Pro User.
Bekomme wenn ich in die Konfigseite gehe die Meldungen:
Custom Styles are only available to Pro!
und 
Device (Fritzbox): Callback for "value" only available in Pro

**Comment by Zefau** [comment]
Stable ist noch V2. Pro ist für v3. Stable wird demnächst aktualisiert. Bitte auf latest gehen.
