### ISSUE TITLE
Rolladen Datenpunkt activity

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1582]
Wunsch:
Datenpunkt `activity` über z.B.  `Datenpunkt Eigenschaften` einstellbar machen für verschiedene Geräte.

Es gibt Geräte die als Rückmeldung ob Sie sich bewegen nicht "true" oder "false" melden sondern z.B.
close , open , stop
Hier wäre es sinnvoll die Datenpunkt Eigenschaften selbst anzugeben wann sich z.B. der Rolladen bewegt oder wann nicht.
Das erspart weitere scripte für den Benutzer und @Zefau braucht keine Ausnahmen programmieren.

**Comment by Zefau** [comment]
Shelly wird automatisch gemappt mit
```
{
	"open": true,
	"close": true,
	"stop": false
}
```

Unabhängig davon kann der `activity` Datenpunkt aber in den Datenpunkt Eigenschaften von BlindLevelAction angepasst werden:

![image](https://user-images.githubusercontent.com/14368811/175830955-81a8cec2-3e05-4dd6-9608-e0a573286bd5.png)

**Comment by Bernd9000** [comment]
> Shelly wird automatisch gemappt mit
> 
> ```
> {
> 	"open": true,
> 	"close": true,
> 	"stop": false
> }
> ```
> 

Wenn der Hersteller es nicht ändert......
Aber kein Problem, hab das sowieso anders gelöst.




> Unabhängig davon kann der `activity` Datenpunkt aber in den Datenpunkt Eigenschaften von BlindLevelAction angepasst werden:
> 
> ![image](https://user-images.githubusercontent.com/14368811/175830955-81a8cec2-3e05-4dd6-9608-e0a573286bd5.png)

Die kann ich mit der aktuellen Version `v3.1.0-alpha.21` im Widget nicht öffnen.


![Animation2](https://user-images.githubusercontent.com/77005685/175833680-e2d71de4-0a58-4cdf-ab08-25b1d1227e79.gif)

**Comment by Bernd9000** [comment]
Nachtrag:
Im Gerät läßt es sich allerdings öffnen, nur im Widget nicht.

**Comment by Bernd9000** [comment]
Ich mach wieder dicht, lag am vielen probieren mit activity und stop.
Stellt man korrekte Werte ein kann man es auch wieder öffnen
