### ISSUE TITLE
Das Action Element BlindLevelAction sollte auch für elektrische Fenster verfügbar sein

### ISSUE THREAD

**Issue by LeLonsch** [Zefau/ioBroker.jarvis#1583]
Danke vorab und ein großes Lob an alle Mitwirkende!

Feature Request:
Ich habe im Dachgeschoss elektrische Dachflächenfenster von Velux verbaut.
Diese möchte ich (genau wie elektrische Rollladen) mit dem Action Element BlindLevelAction steuern.
Das Element ist jedoch nur im Gewerk Rollladen/Jalousie verfügbar.
Mein Workaround derzeit ist es, die Fenster diesem Gewerk zuzuordnen.
Ordentlicher wäre es allerdings, das BlindLevelAction Element auch im Gewerk Fenster zur Verfügung zu haben.

Danke und VG
LeLonsch

**Comment by Zefau** [comment]
implemented with `v3.1.0-alpha.26`
