### ISSUE TITLE
Zusätzliche Klasse für die TAB-abhängige Page

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1586]
damit man auch die einzelne Seiten von dem ausgewählten TAB beeinflussen benötigt man ein zusätzliche Klasse hinter der page.
Nach `jarvis-page-887349d5-d5b7-408c-99a7-73a2a72b7194` müsste es noch eine TAB-abhängige Klasse geben z.B. `jarvis-page-home0`. Dann könnte man auch TAB-abhängig z.B. Background  einstellen.
![image](https://user-images.githubusercontent.com/84818934/152654337-76e3d197-b6c8-4979-8cd6-d995a5d126dd.png)

**Comment by Zefau** [comment]
schau bitte mit `v3.0.11-beta.5`

**Comment by mcuiobroker** [comment]
Zieht nicht:
```
.jarvis-page-887349d5-d5b7-408c-99a7-73a2a72b7194 .jarvis-tab-bad1 {
	background-color: red;
	background: url("https://images.hdqwalls.com/download/legion-abstract-8k-5p-1920x1080.jpg") !important;
}
```

![image](https://user-images.githubusercontent.com/84818934/152675756-febf400d-7b79-4b4e-a589-407cf2acb0fc.png)
