### ISSUE TITLE
Verbindung fehlgeschlagen - Web Adapter Update?

### ISSUE THREAD

**Issue by ChrizZz90** [Zefau/ioBroker.jarvis#1588]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- Version: 2.2.1
- Screenshot
![220206_jarvis_firefox_console](https://user-images.githubusercontent.com/53112257/152688566-7462907b-7b74-4de5-b424-b117f812b83a.png)

**Describe the bug / Beschreibe den Fehler**
Vermutlich seit dem letzten Update des Web Adapters funktioniert der Zugriff auf die Jarvis Oberfläche nicht mehr. Ich habe es mit https und ohne probiert, mit SocketIO und ohne und trotz all diesen Möglichkeiten konnte ich das Problem nicht selbst lösen. Neben Firefox habe ich auch den Zugriff per Chrome getestet. Da ich nur "stable" Versionen nutze, wird mir wohl Jarvis v3 nicht angezeigt. Falls dies aber den Fehler behebt, kann ich auch gerne wechseln (sag ich mal so spontan).

**Comment by Zefau** [comment]
Nutzt du im Web Adapter die Verschlüsselung? Ggf. musst du das Zertifikat akzeptieren?

Sonst bitte auf v3 gehen. Diese kommt auch zeitnah ins stable repo. Die v3 nutzt ein eigenes Socket-IO und ist unabhängig vom Web Socket-IO bzw. dem Socket-IO Adapter. Damit kommt es dann nicht mehr zu solchen Fehlern.

**Comment by ChrizZz90** [comment]
Hatte keine Verschlüsselung drin, aber auch egal...Mit v3 geht wieder alles. Danke & schönen Sonntag noch
