### ISSUE TITLE
Nach Update auf 3.0.11 waren States in der Statelist verschwunden

### ISSUE THREAD

**Issue by TheBermud** [Zefau/ioBroker.jarvis#1594]
Hallo,

nach Update auf Version 3.0.11 waren 2 States dauerhaft verschwunden konnten in keiner Statelist sichtbar gemacht werden.

Im Bodystil der States war folgendes eingetragen:

`{"default":{"display":"none !important"}}`

Diesen Text habe ich jedoch nicht selber eingetragen, ich kann nicht sagen, wie der da rein gekommen ist. Ich kann nur sagen, vor dem Update stand es da nicht drin. 

Ich habe leider kein akutelles Backup um den Fehler reproduzieren zu können.

**Comment by Zefau** [comment]
Solche Einträge werden von jarvis nicht einfach so hinzugefügt. Über den Expertenmodus einfach wieder entfernen und gerne beobachten, ob es wieder auftritt.

**Comment by TheBermud** [comment]
Okay mache ich.
