### ISSUE TITLE
Alte Sicherungen bei Update erhalten _old-Dateien erstellen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1595]
Hab es als Issue angelegt, sonst vergisst man es.

Sicherungen werden bei einem Update gelöscht. Diese sollten aber erhalten bleiben.
Dann musst du vielleicht _old-Dateien erstellen, also vorher umbenennen?
Nur weil man ein Update macht, hat man plötzlich keine interne Sicherung mehr.
So hat man noch die Möglichkeit durch umbenennen sich die alten Sicherungen zurückzuholen.
Eigentlich musst du die Dateien doch nur neu schreiben, wenn sie nicht vorhanden sind?

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/discussions/1538#discussioncomment-2023060_

**Comment by Zefau** [comment]
Darauf habe ich keinen Einfluss auf Adapter-Sicht.

Der gesamte Adapter Ordner wird leer gemacht. Das würde auch `_old` Dateien betreffen. Sonst könnte ich die vorhandenen Backups ja auch einfach erhalten.

Das ist durch ioBroker so und notwendig, damit nach einem Update nicht alte Dateien geladen / genutzt werden.

Alles bzgl. Backup sollte über backitup erfolgen.

Kann man dort nicht eine definierte Instanz erstellen und nur jarvis mit einer hohen Frequenz sichern?

**Comment by Zefau** [comment]
Ja, es liegt definitiv an dem Flag. Das Flag ist aber bewusst gesetzt, damit bei einem Adapter-Update die alten JS / CSS Dateien gelöscht werden, damit der Browser nach dem Update auch die neuen Dateien nimmt und nicht die Alten.

Hab schon überlebt ein Tutorial zu schreiben, in dem einfach täglich die relevanten Datenpunkte gesichert werden. das würde ja komplett Abhilfe schaffen.
