### ISSUE TITLE
switchAction Problem mit setOn , setOff

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1596]
`v3.0.10` oder früher
Ich gebe unter Datenpunkt Eigenschaften für ein switchAction Werte mit setOn , setOff vor.
Das funktioniert scheinbar nicht mehr ?
Z.B: `{"setOn":"On","setOff":"Off"}` oder `{"setOn":"Ein","setOff":"Aus"}`

Folgende Möglichkeit funktioniert bei mir noch: `{"setOn":true,"setOff":false}`

![1](https://user-images.githubusercontent.com/77005685/152877658-348662a5-fe6c-4eec-8f4c-739431f64dc9.jpg)

**Comment by Bernd9000** [comment]
Wenn ich unter Datenpunkt Eigenschaften folgendes verwende funktioniert es:
{"on":"Ein","off":"Aus"}
Was ist eigentlich der Unterschied zwischen den Werten  "setOn" und "on" bzw. "setOff" und "off" ?

**Comment by Zefau** [comment]
@Bernd9000 besteht das Problem mit v3.1 noch?

**Comment by Bernd9000** [comment]
Ja, Fehler ist noch vorhanden.
Allerdings nutze ich es nicht mehr, hab allen Geräten beigebracht nur noch auf true oder false zu hören.
Issue kann geschlossen werden.
