### ISSUE TITLE
Suche nach Gerät mit Filter nicht sichtbar, mit Expert Mode schon

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1599]
Gerätesuche nicht erfolgreich.
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2038
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2039
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2042

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/759393
> in welchem Feld kam `Wohnung` denn vor?

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.17`
bislang nicht mehr vorgekommen.
Schließe erstmal.
