### ISSUE TITLE
Position of configuration pop-up 

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#16]
In contrast to the log pop-up, the configuration pop-up is not in the middle of the screen.

**Comment by Zefau** [comment]
With `v0.1.2` the pop-up of the log screen is bind to top as well. Could you please test and verify? Thanks

**Comment by braindead1** [comment]
After updating to v0.1.2 the log pop-up shows the same effect as described initially. Below screenshot shows the full width of my screen.

![1](https://user-images.githubusercontent.com/2136249/77860243-6ce0c580-720e-11ea-91e3-c2d04189de46.png)

**Comment by Zefau** [comment]
Thought you meant the vertical center, but you mean horizontal? I will have a look at this again.

**Comment by braindead1** [comment]
Well, before v0.1.2 at least the log pop-up worked as expected. Maybe you can revert the change and change the config pop-up accordingly?

**Comment by Zefau** [comment]
Should be fixed with v0.1.4, could you please verify? Thanks

**Comment by braindead1** [comment]
In v0.1.4 both pop-ups are working as expected in Google Chrome on Windows 10.
