### ISSUE TITLE
Kalender zeigt keine Einträge

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1600]
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2041
Hab es auch bei mir als Widget so hinzugefügt und bekomme nur Fehler, keine Anzeige
![image](https://user-images.githubusercontent.com/84818934/153223807-abff0386-98fb-49e6-886d-4e1b85b4065d.png)

https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2043

In vielen ics-Kalendern steht `DTSTART;TZID=Europe/Berlin:20220418
DTEND;TZID=Europe/Berlin:20220419`
statt `DTSTART;VALUE=DATE:20220101
DTEND;VALUE=DATE:20220102`

Was mir noch aufgefallen ist. Es dauert entweder sehr lange bis neue Kalenderdaten angenommen werden, oder man muss immer F5 nutzen?
Ich hatte den Kalender komplett gewechselt und trotzdem hat er mir noch die Daten vom alten angezeigt.

**Comment by Zefau** [comment]
Der Schulferien Kalender hat kein `http`, daher wird es als Datei-Pfad interpretiert.

**Comment by Zefau** [comment]
Sehe auch gerade, dass du es ja in https://forum.iobroker.net/post/759226 mehr als korrekt beantwortet hast.

**Comment by mcuiobroker** [comment]
Vielleicht kannst du es ja anpassen, so dass auch die Kalender korrekt umgesetzt werden.

**Comment by Zefau** [comment]
hat sich das mit `v3.1.0-alpha.17`ggf. ebenfalls gelöst?

**Comment by mcuiobroker** [comment]
Es werden auch zeitweise noch alte Einträge angezeigt, wenn man die Kalender geändert bzw. gelöscht hat. Auch obwohl man F5 genutzt hat.

In diesem Fall nicht: (Es kommen keine Fehlermeldungen im DOM)
```
BEGIN:VCALENDAR
X-LOTUS-CHARSET:UTF-8
VERSION:2.0
PRODID:ZMS-Berlin
BEGIN:VTIMEZONE
TZID:Europe/Berlin
X-LIC-LOCATION:Europe/Berlin
BEGIN:DAYLIGHT
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
TZNAME:CEST
DTSTART:19700329T020000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=3
END:DAYLIGHT
BEGIN:STANDARD
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
TZNAME:CET
DTSTART:19701025T030000
RRULE:FREQ=YEARLY;INTERVAL=1;BYDAY=-1SU;BYMONTH=10
END:STANDARD
END:VTIMEZONE
METHOD:REQUEST
BEGIN:VEVENT
UID:ics.terminsysteme.de1547805085
DTSTAMP:20190118T105125
CLASS:PUBLIC
DTSTART;TZID=Europe/Berlin:20220411T
DTEND;TZID=Europe/Berlin:20220423T
LOCATION: NRW
SUMMARY:Osterferien
DESCRIPTION:Osterferien NRW
END:VEVENT
END:VCALENDAR
```

**Comment by mcuiobroker** [comment]
Nach einiger Zeit (10 min~)
![image](https://user-images.githubusercontent.com/84818934/173700873-df4dff4f-edad-4608-9ab5-0e0be277d32a.png)

**Comment by Zefau** [comment]
> Es werden auch zeitweise noch alte Einträge angezeigt, wenn man die Kalender geändert bzw. gelöscht hat. Auch obwohl man F5 genutzt hat.

Das liegt daran, dass die Daten gecached / zwischengespeichert werden. Die Aktualisierung kann in der Konfiguration angepasst werden und steht im Standard auf 5 Minuten.

**Comment by Zefau** [comment]
Hattest du die Warnung mit `v3.1.0-alpha.21` noch bzw. könntest das mal beobachten?

**Comment by Zefau** [comment]
@mcuiobroker Hattest du die Warnung mit `v3.1.0-alpha.21` noch bzw. könntest das mal beobachten?

**Comment by mcuiobroker** [comment]
Die Warnung habe ich nicht mehr. Ich mach erstmal zu. Danke.
