### ISSUE TITLE
After Upgrade to Jarvis 3, Jarvis is no longer reachable via reverse Proxy

### ISSUE THREAD

**Issue by domi1893** [Zefau/ioBroker.jarvis#1602]
Hi zusammen,

nachdem ich jetzt von Jarvis 2 auf 3 gewechselt bin, kann ich Jarvis von außen via DDNS nicht mehr erreichen. Lokal funktioniert alles, von außen komme ich auf die Login Seite, nach dem Login kommt folgendes:

![tempsnip](https://user-images.githubusercontent.com/63353061/153253402-613ca83c-3376-42d0-b6ce-30a66f36a252.png)

Ich habe an den Einstellungen des Web-Adapters nichts geändert, lediglich das Upgrade durchgeführt.
Mein IO-Broker läuft im Docker auf einer Syno. Von außen greife ich über den Reverse-Proxy der Syno auf den Broker zu. Bisher hat alles ohne Probleme funktioniert. Kennt jemand das Thema bzw. kann mir dort weiterhelfen? 
Ich werde wohl erstmal wieder versuchen downzugraden.

Grüße,

Domi

**Comment by Zefau** [comment]
Hast du in den Adapter-Einstellungen die Option von allen Hosts Verbindungen zu erlauben bzw. hast du die Whitelist gepflegt, falls ausgewählt?

![image](https://user-images.githubusercontent.com/14368811/153272960-e3189292-f0d2-45f3-804c-bfe3577bb1f8.png)


Ansonsten verstehe ich nicht viel vom Reverse-Proxy. Ggf. hilft https://github.com/Zefau/ioBroker.jarvis/issues/847 ?

**Comment by domi1893** [comment]
Hab alle erlauben aktiv. Was mich wundert ist, dass es mit der V2 funktioniert.

**Comment by Zefau** [comment]
v3 nutzt ein eigenes Socket auf Port `8400`. Web Port läuft auf `8082` (je nachdem, wie im Web Adapter konfiguriert). Ggf. deswegen?

Wie gesagt, ich kenne mich mit Reverse-Proxy nicht aus und weiß nicht, wie es funktioniert, weshalb ich nicht sagen kann, warum es bei v2 geht und bei v3 nicht.

Ich wäre aber interessiert daran, es zu debuggen, sofern du / wir nachvollziehen können, worin der Fehler begründet liegt.

**Comment by domi1893** [comment]
Dann liegt es vermutlich an dem Port 8400. Der ist von von außen nicht frei. Mein Reverse verweist auf den Webport. Die Frage ist, ob es eine Lösung gibt, ohne den Port 8400 nach draußen zu hosten? Bzw. wie eine Lösung aussehen kann, um von außen sicher zuzugreifen, ohne VPN?

**Comment by Zefau** [comment]
Keine Ahnung. Wie gesagt, ich hab kein Plan von Reverse-Proxy und das wäre ja hier die Antwort: Wie kann es anders funktionieren, wenn Web und Socket nicht auf demselben Port laufen.

**Comment by Zefau** [comment]
Kannst du nicht 2 Ports freischalten? Also Web und Socket.io?

**Comment by Zefau** [comment]
Probier mal bitte mit `3.0.12-beta.0` komplett auf dem Port `8400` - also sowohl mit Socket als auch Web. Der Port nimmt nun auch den Request an und redirected dann intern auf `8082`. Geht das bei dir dann auch mit dem Reverse-Proxy?

**Comment by domi1893** [comment]
Das geht leider nicht von außen. Wenn ich an Port 8400 weiterleite sehe ich, dass die Beta intern an 8082, dann ist die Website nicht erreichbar, vermutlich weil die Weiterleitung auf eine lokale Adresse geht?

Als Ergänzung noch: Wenn ich in Jarvis beide Ports auf 8400 Stelle, kann ich auch in der Web Instanz logischerweise keinen Port 8400 verwenden.

**Comment by Zefau** [comment]
Also Reverse-Proxy klappt nicht bei einer Weiterleitung? :-\

Ich kriege es leider nicht anders hin. Der Web Adapter stellt den Server, der die Seite hostet. jarvis nutzt einen eigenen Socket, wodurch den ich Web-Server des Web-Adapters (und damit den Port) nicht gleichzeitig nutzen kann. In v2 hat alles der Web Adapter gemacht (auch das Socket), wodurch das ging.

**Comment by n0bbi** [comment]
Ich stehe vor genau dem gleichen Problem und habe mein halbes WE damit verbracht, jarvis irgendwie hinter dem NGINX Reverse Proxy erreichbar zu machen. Bisher leider ohne Erfolg. 

Falls ich irgendwie unterstützen kann, bitte Bescheid geben, ansonsten probiere ich weiter. Vielleicht gibt es ja doch eine Möglichkeit.

**Comment by Kelran123** [comment]
Ich habe gestern auch in meiner Proxmox Umgebung Nginx im Docker installiert. Haupstsächlich, da ich Nextcloud und Bitwarden daheim hosten und für mich von extern verfügbar machen will. Ich dachte als netten Beifang bekomme ich den Jarvis auch von außen in den Zugriff, leider habe ich auch die hier schon beschriebenen Probleme. Da Nginx ja auch vorher eine Username/PW abfrage vorschaltet relativ sicher.  Ich muss aber erstmal in dem Thema noch fitter werden um evtl. etwas beisteuern zu können.

**Comment by domi1893** [comment]
Ich hab's aktuell noch nicht probiert, weil ich mir unsicher bin bzgl. der Sicherheit. Also mach ich direkt alle Tore auf, wenn ich den Port 8400 zusätzlich noch ins Netz route?

**Comment by jardleex** [comment]
Hallo,

ich bin heute nach dem Update von v2 auf v3 ebenfalls über diesen Fall gestolpert.

Zu meinem Setup bezogen auf diesen Fall:

- Intel NUC mit Debian 10
- Portainer zur Containerverwaltung
- Ein Stack in Portainer deployt alle meine Container via docker-compose
- traefik als ReverseProxy außerhalb von Docker auf dem NUC
- Konfiguration von traefik über Labels an Container soweit als möglich
- iobroker ohne jegliche Zertifiakte deployt
- traefik übernimmt sämtliche SSL-Terminierung (mittels LetsEncrypt)
- Verbindungseinstellungen in jarvis stehen auf auto
- jarvis version 3.0.12-beta.1
- Zugriffe erfolgen alle nur im lokalen Netzwerk; aus dem Internet dann nur per VPN; keine Portfreigaben in der Firewall für iobroker

Nach einigen Tests konnte ich das Problem so lösen:

- einen zusätzlichen EntryPoint in traefik auf Port 8400
- folgende Label an den iobroker Container angefügt

```yaml
      - traefik.http.routers.$redacted.rule=Host(`$redacted.$redacted.$redacted`)
      - traefik.http.routers.$redacted.entrypoints=websecure
      - traefik.http.routers.$redacted.tls=true
      - traefik.http.routers.$redacted.service=$redacted
      - traefik.http.services.$redacted.loadbalancer.server.port=8083
      - traefik.http.routers.$redacted.middlewares=$redacted_root
      - traefik.http.middlewares.$redacted_root.redirectregex.regex=^https://$redacted.$redacted.$redacted/$$
      - traefik.http.middlewares.$redacted_root.redirectregex.replacement=https://$redacted.$redacted.$redacted/jarvis/index.html
      - traefik.http.middlewares.$redacted_root.redirectregex.permanent=true
      
      - traefik.http.routers.$redacted-socket.rule=PathPrefix(`/jarvis-socket`)
      - traefik.http.routers.$redacted-socket.entrypoints=jarvis-socket
      - traefik.http.routers.$redacted-socket.tls=true
      - traefik.http.routers.$redacted-socket.service=$redacted-socket
      - traefik.http.services.$redacted-socket.loadbalancer.server.port=8400
```

Es wäre schön wenn diese Dual-Port-Lösung nur ein Workaround ist und zukünftig alles wieder über einen laufen könnte. Es sei gesagt dass ich das ganze als IT-Admin und Anwender sehe, mir fehlt das Wissen als IT-Entwickler.

Weitere Infos oder Tests sind gern möglich.

**Comment by Zefau** [comment]
Sehe gerade, dass ein gemeinsamer Port technisch gehen könnte, siehe https://github.com/ioBroker/ioBroker.web/blob/master/WEB-EXTENSIONS-HOWTO.md. Ich werde das mal probieren.

**Comment by Zefau** [comment]
Habt ihr in v2 für den Reverse-Proxy im Web Adapter das Socket über `integrated` oder `socket-io` gehabt?

Über die Option `socket-io` wären es ja auch zwei Ports: 8082 für Web und 8084 für den Socket.

**Comment by jardleex** [comment]
Mein web.0 Adapter steht bei der socket.io-Einstellung auf **integriert**. Alternative wäre **keins**.

**Comment by domi1893** [comment]
> 

Korrekt, so war es bei mir auch

**Comment by Zefau** [comment]
mit `v3.0.12-beta.2` sollte es nun auf Port 8400 klappen

**Comment by n0bbi** [comment]
Hi, 

bei mir klappt das nicht. Ich wäre eigentlich auch davon ausgegangen, dass die Socket-Verbindung ebenfalls über Port 8082 laufen muss und nicht mehr über Port 8400?

**Comment by Zefau** [comment]
Socket und Web läuft auf 8400. Web Adapter port ist nicht relevant

**Comment by n0bbi** [comment]
Dann stehe ich auf dem Schlauch. Meine URL ist http://192.168.178.38:8082/jarvis/index.html#/0/dashboard0 und hier ist doch Port 8082 festgelegt? 

Okay, ich ergänze gleich: Über http://192.168.178.38:8400/#/dashboard0 ist Jarvis ebenfalls erreichbar. Leider kommt es dann trotzdem noch zu einem Fehler:

![image](https://user-images.githubusercontent.com/59010376/158558858-3e842cc8-0d97-4201-95af-f8af6fcfacee.png)

**Comment by Zefau** [comment]
probier nochmal mit `v3.0.12-beta.3`

**Comment by n0bbi** [comment]
Vielen Dank, jetzt klappt zumindest der Zugriff lokal. Über den Reverse Proxy geht es ebenfalls, solange ich keine SSL-Verschlüsselung verwende. Kann ich gerade nicht nachvollziehen, der Weg vom Reverse Proxy (in meinem Fall NGINX) zu Jarvis ist ja weiterhin unverschlüsselt.

![image](https://user-images.githubusercontent.com/59010376/158761494-53a249a4-ba2c-4db3-a119-3face9ac9f97.png)

**Comment by dmkif** [comment]
Das Problem an der Sache ist, dass der Reverse-Proxy (egal ob NGINX oder TRAEFIK) wahrscheinlich auf Port 80 und 443 lauschen und dann die ankommenden Anfragen auf den passenden Port (8400) umrouten. Wie auf euren Screenshots zu sehen ist, wird versucht die Verbindung über den Port 8400 aufzubauen und das funktioniert natürlich nicht. Jarvis sollte intern versuchen den aufzurufenden Url zu ermitteln und nicht an jede Anfrage fest den Port hinzufügen. Ich denke, so könnte es klappen. z.B. die Javascript-Variable "window.location.host" beinhaltet die nötigen Informationen. Sollte explizit ein Port angegeben sein, dann steht dieser auch mit in der Variable und sollte kein Port angegeben sein (z.B. wegen SSL auf Port 443) so ist dort nur Domain-Name zu finden.

**Comment by Trrw** [comment]
Gibt es hierzu einen neuen Stand?

**Comment by 9Mad-Max5** [comment]
> Hallo,
> 
> ich bin heute nach dem Update von v2 auf v3 ebenfalls über diesen Fall gestolpert.
> 
> Zu meinem Setup bezogen auf diesen Fall:
> 
> * Intel NUC mit Debian 10
> * Portainer zur Containerverwaltung
> * Ein Stack in Portainer deployt alle meine Container via docker-compose
> * traefik als ReverseProxy außerhalb von Docker auf dem NUC
> * Konfiguration von traefik über Labels an Container soweit als möglich
> * iobroker ohne jegliche Zertifiakte deployt
> * traefik übernimmt sämtliche SSL-Terminierung (mittels LetsEncrypt)
> * Verbindungseinstellungen in jarvis stehen auf auto
> * jarvis version 3.0.12-beta.1
> * Zugriffe erfolgen alle nur im lokalen Netzwerk; aus dem Internet dann nur per VPN; keine Portfreigaben in der Firewall für iobroker
> 
> Nach einigen Tests konnte ich das Problem so lösen:
> 
> * einen zusätzlichen EntryPoint in traefik auf Port 8400
> * folgende Label an den iobroker Container angefügt
> 
> ```yaml
>       - traefik.http.routers.$redacted.rule=Host(`$redacted.$redacted.$redacted`)
>       - traefik.http.routers.$redacted.entrypoints=websecure
>       - traefik.http.routers.$redacted.tls=true
>       - traefik.http.routers.$redacted.service=$redacted
>       - traefik.http.services.$redacted.loadbalancer.server.port=8083
>       - traefik.http.routers.$redacted.middlewares=$redacted_root
>       - traefik.http.middlewares.$redacted_root.redirectregex.regex=^https://$redacted.$redacted.$redacted/$$
>       - traefik.http.middlewares.$redacted_root.redirectregex.replacement=https://$redacted.$redacted.$redacted/jarvis/index.html
>       - traefik.http.middlewares.$redacted_root.redirectregex.permanent=true
>       
>       - traefik.http.routers.$redacted-socket.rule=PathPrefix(`/jarvis-socket`)
>       - traefik.http.routers.$redacted-socket.entrypoints=jarvis-socket
>       - traefik.http.routers.$redacted-socket.tls=true
>       - traefik.http.routers.$redacted-socket.service=$redacted-socket
>       - traefik.http.services.$redacted-socket.loadbalancer.server.port=8400
> ```
> 
> Es wäre schön wenn diese Dual-Port-Lösung nur ein Workaround ist und zukünftig alles wieder über einen laufen könnte. Es sei gesagt dass ich das ganze als IT-Admin und Anwender sehe, mir fehlt das Wissen als IT-Entwickler.
> 
> Weitere Infos oder Tests sind gern möglich.

Ich habe ein sehr ähnliches Setup, fürchte allerdings das ich deinen Labels nicht ganz folgen kann.
Wofür stehen die $redacted variablen?
Ist das dein eigenes System zur Vergabe der Namen, also mit etwa einer .ENV?
Wie sieht die gesamte config damit aus und wo müsste man was anpassen nur die .rule?

**Comment by 9Mad-Max5** [comment]
Ich fürchte ich kann nicht ganz folgen.
http://lokale-ip:8400 bekomme ich nur die Meldung das hier socket.io von Jarvis ist.
Oder muss ich dafür eine hier genannte Beta oder Alpha installieren?
Ich habe aktuell noch die 3.0.11.

**Comment by n0bbi** [comment]
Mit der v3.1.0-alpha.8 funktioniert das auch noch nicht. 

(Eine höhere Alpha-Version läuft bei mir nicht, weil er die Pro-Aktivierung nicht mehr erkennt.)

**Comment by Zefau** [comment]
> Ich fürchte ich kann nicht ganz folgen.
> http://lokale-ip:8400 bekomme ich nur die Meldung das hier socket.io von Jarvis ist.
> Oder muss ich dafür eine hier genannte Beta oder Alpha installieren?
> Ich habe aktuell noch die 3.0.11.
> 

Ja, du brauchst die v3.1, die zZ aber nur Alpha ist

**Comment by Zefau** [comment]
> Mit der v3.1.0-alpha.8 funktioniert das auch noch nicht. 
> 
> (Eine höhere Alpha-Version läuft bei mir nicht, weil er die Pro-Aktivierung nicht mehr erkennt.) 

Was kann ich noch tun? Web Port und Socket Port sind identisch. Was geht denn nicht und warum? Http oder https?

**Comment by 9Mad-Max5** [comment]
@Zefau Ich habe nun geupdatet, aber ich glaube, das Problem bleibt dasselbe.
Bei den Reverse Proxys liegt das Problem so weit ich es sehe in der Weiterleitung.
Würde ich normal intern die Seite aufrufen also mit der IP 192.168.2.6:8082/jarvis lande ich auf der Jarvis Seite.
Also alles gut, weil den socket den er aufruft also 192.168.2.6:8400 ja eben genau dieselbe IP hat und ich bin im selben Netzwerk.
Komme ich jetzt über meinen Proxy, habe ich aber eben https://meinedomain.dns.army/jarvis in der Kopfzeile stehen.
Die wird intern auf 192.168.2.6:8082/jarvis oder mit der neuen Version 192.168.2.6:8400 weitergeleitet.

Versucht nun Jarvis seinen Socket zu erreichen, nimmt er meine Originale Adresse also, mit der ich in das lokale Netzwerk gekommen bin und packt dort hintendran den Port.
Also wird aus https://meinedomain.dns.army/jarvis oder bei der neuen Version https://meinedomain.dns.army die Adresse https://meinedomain.dns.army:8400.

Da ich den Port 8400 aber nicht freigegeben habe, scheitert diese Anfrage.
Mögliche Lösungen, die mir jetzt einfallen würden:

- **QUICK and DIRTY** Port 8400 zu öffnen und auf meine lokale IP zu verweisen.
- Widerstrebt aber eigentlich dem Grundgedanken von einem ReverseProxy möglichste keine Ports freizugeben
- Und ich weiß nicht was auf dem Port passiert oder passieren kann...(Nicht Ideal)

- **Etwas besser** Ich bin mir nicht mehr sicher wie, aber ich meine mal, man konnte etwa mit PiHole oder der Fritzbox eine Route einrichten, damit definierte Domains direkt lokal aufgelöst werden.
- Somit könnte der Port 8400 zu bleiben und alles müsste klappen ohne allzu große Risiken.

- **Ideal** Wenn jarvis nicht meine ankommende domain oder IP verwendet, um sich mit dem Socket zu verbinden, sondern entweder eine zu definierende oder etwas vergleichbar wie localhost.
Normalerweise müsste der socket ja immer auf derselben IP wie der jarvis Port laufen, oder?

**Comment by Zefau** [comment]
Bitte den Port 8082 vergessen und ausblenden! NUR Port 8400. Da läuft der Web-Server und der Socket (mit v3.1).

>  Bei den Reverse Proxys liegt das Problem so weit ich es sehe in der Weiterleitung.

Gibt es nicht auf Port 8400. Rufst du 192.168.2.6:8400 im Browser auf dann kommst du auf jarvis.

**Comment by 9Mad-Max5** [comment]
Ich bin wirklich dankbar für deine Arbeit und bin froh, dass du dir die Zeit nimmst hier so schnell zu antworten.

Doch leider bekomme ich den roten Bildschirm und sehe wieder das https://meinedomain.dns.army:8400.
Möglicherweise ist es keine Weiterleitung, aber trotzdem versucht er mit dem Port 8400 zu sprechen.
![2022-06-10 00_30_41-Window](https://user-images.githubusercontent.com/29258083/172956193-85305de8-218b-4993-8ab5-b42497ed68eb.png)

**Comment by Zefau** [comment]
Glaube wir reden aneinander vorbei. Bist du bei Discord? Lass uns sonst mal direkt sprechen.

**Comment by Zefau** [comment]
> Möglicherweise ist es keine Weiterleitung, aber trotzdem versucht er mit dem Port 8400 zu sprechen.

Jo natürlich. Über 8400 läuft ja wie gesagt Web und Socket von jarvis

**Comment by Zefau** [comment]
@n0bbi @Trrw @domi1893 ich konnte das Problem @9Mad-Max5 das Problem (mehr oder weniger) lösen.

**Das Problem** ist, dass jarvis die URL nimmt und den Port `8400` ran packt, um in Richtung ioBroker zu connecten. Im Falle von Reverse-Proxy führt das dazu, dass man quasi den Port doppelt hat (1x durch den Reverse Proxy und dann, weil jarvis es ran packt).

**Die Lösung:** Ihr könnt mittels URL Parameter das Verhalten konfigurieren. Konkret könnt ihr mit `socketPort=XXXX` beispielsweise den Port ändern und hier auf `80` oder `443` gehen (je nachdem was ihr im Reverse Proxy nutzt). Dadurch sollte jarvis dann die Verbindung in Richtung ioBroker schaffen.

Die möglichen Parameter sind:
- `socketHost`
- `keepParams`=`true`
- `socketSecure=true` oder `=false`
- `socketUrl`

**Comment by Zefau** [comment]
Der Workaround funktioniert scheinbar auch nur bedingt. Es kommt zeitnah eine neue alpha, die das Problem adressiert (ohne zusätzliche Konfiguration eurerseits).

**Comment by Zefau** [comment]
schaut nochmal mit `3.1.0-alpha.15`

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.0-alpha.16`

**Comment by n0bbi** [comment]
Danke @Zefau Mit der neuesten Alpha klappt es bei mir nun.

**Comment by Zefau** [comment]
Super

**Comment by domi1893** [comment]
Ich muss die Tage erst noch testen, werde dann Rückmeldung geben. Bei mir ist gerade viel los. Scheint jetzt ja wieder zu klappen :-). Danke schon Mal im vorraus fürs Kümmern und deine Support. Die Pro Version werde ich mir ziehen :-)

**Comment by eppi72** [comment]
@Zefau 
Ich bin neu bei ioBroker und habe mir Javis-Pro gekauft. Heute morgen habe ich die v3.1.0-alpha.23 installiert um zu testen, ob diese mit meinem Nginx-Proxy Manager funktioniert - was sie auch einwandfrei macht auf Port 8400 - Danke dafür! Da diese Alpha noch einige Bugs hat (bei mir werden die offenen Fenster nicht aktualisiert) muss ich wieder zurück auf die Stable-Version. Kannst du ungefähr abschätzen, wann es eine Version geben wird, die Stable ist und mit meinem Proxy Manager funktioniert, wie die aktuellste Alpha-Version? Danke und viele Grüsse Eppi

**Comment by Zefau** [comment]
Eigentlich gestern. Hoffe heute, aber definitiv die Tage jetzt via v3.0.12.

**Comment by Kelran123** [comment]
Vielen Dank!! Funktioniert bei mir nun auch Wunderbar mit nginx reverse proxy

**Comment by Grmlrckr** [comment]
Sorry, dass ich das nochmal hoch hole, aber ich stehe gerade wie der Ochs' vorm Berg...
Ich habe mir das ganze Issue hier durchgelesen, scheine aber irgendwo den Anschluss zu verlieren.

Kurz vor dem Close hier gab es eine neue Alpha (die inzwischen ja schon lange stable und weiterentwickelt ist). Damit hat es wohl funktioniert. Dann der Close und noch ein paar Erfolgsmeldungen. 

Aber mir erschließt sich jetzt nicht wirklich, was wo getan werden muss. Im Adapter selbst wohl nichts. 
Und im nginx? @Kelran123 @eppi72 Eure Meldungen lese ich als "funktioniert". Könntet Ihr Eure nginx-Konfig posten bzw. bei mir kurz drüberschauen damit ich sehe, ob ich da irgendeinen (Denk-)Fehler habe?

Ich muss dazu sagen, dass ich mit nginx erst anfange.
![image](https://user-images.githubusercontent.com/35227463/202906104-e9c0f262-de81-4bd6-a18f-bae707f6a043.png)
![image](https://user-images.githubusercontent.com/35227463/202906112-e4ae8e6c-a391-4105-a8e0-c9d5d332020a.png)

Prinzipiell funktioniert mein nginx und leitet mich nach der Password-Abfrage auf Port 8082 weiter.
Wenn ich im ersten Bild den Forward Port direkt auf 8400 stelle funktioniert es, dass ich direkt in Jarvis lande. Aber ich würde das gerne eher über eine Custom Location machen.

Danke!

**Comment by eppi72** [comment]
> Sorry, dass ich das nochmal hoch hole, aber ich stehe gerade wie der Ochs' vorm Berg... Ich habe mir das ganze Issue hier durchgelesen, scheine aber irgendwo den Anschluss zu verlieren.
> 
> Kurz vor dem Close hier gab es eine neue Alpha (die inzwischen ja schon lange stable und weiterentwickelt ist). Damit hat es wohl funktioniert. Dann der Close und noch ein paar Erfolgsmeldungen.
> 
> Aber mir erschließt sich jetzt nicht wirklich, was wo getan werden muss. Im Adapter selbst wohl nichts. Und im nginx? @Kelran123 @eppi72 Eure Meldungen lese ich als "funktioniert". Könntet Ihr Eure nginx-Konfig posten bzw. bei mir kurz drüberschauen damit ich sehe, ob ich da irgendeinen (Denk-)Fehler habe?


Hi @Grmlrckr
Anbei meine Printscreens, funktioniert so bei mir einwandfrei. Ich nutze die aktuelle Stable-Version 3.0.15 von Jarvis. Zusätzlich noch ein Printscreen meiner Jarvis-Konfig in ioBroker. Viel Erfolg und LG eppi72
![1](https://user-images.githubusercontent.com/6312572/202916680-310c1cc1-24ff-43fc-9f2c-dfd54c5f4bef.PNG)
![2](https://user-images.githubusercontent.com/6312572/202916681-b95a826a-47f3-4f8e-ab18-b02902626036.PNG)
![3](https://user-images.githubusercontent.com/6312572/202916682-6992fd86-9f03-4828-a90c-59c932241bce.PNG)
![4](https://user-images.githubusercontent.com/6312572/202916683-3b1b1fb7-c9a5-4219-a1ed-3f1a51546f2d.PNG)
![5](https://user-images.githubusercontent.com/6312572/202916817-891a720e-f096-43e4-baed-6b7952d93a2c.PNG)

**Comment by Grmlrckr** [comment]
@eppi72 Vielen Dank! Ich hatte gehofft, dass das bei Dir über eine Custom Location läuft. Aber Du machst den Forward auch direkt, ohne Custom Location. So funktioniert es bei mir ja auch.
Dann mache ich es auch erstmal so und muss mal weiter graben, wie die Custom Locations funktionieren bzw. was da mit der Custom Konfig gemacht werden kann.

**Comment by domi1893** [comment]
Jetzt muss ich mich auch nochmal melden. Ich bin erst jetzt dazu gekommen, zu testen --> Baby kam inzwischen :-). Bei funktioniert das mit den Settings aus V2 nicht. Ich habe Jarvis in 3.1.0-beta.28 installiert. Auf der Synology habe ich den Reverse Proxy auf Port 8082 geleitet --> Anmeldemaske erscheint, sobald ich mich anmelde kommt wieder der Fehler mit Port 8400 nicht erreichbar. die Web-Server-Instanz ist auf 8082 erreichbar mit Einstellung socket.io integriert, an den Jarvis Verbindungseinstellungen ist nichts geändert. Auch wenn ich die Webserver-Instanz auf 8400 stelle und den Reverse dann auch auf 8400 zeigt sich das gleiche Verhalten. Lokal klappt nach wie vor alles wunderbar.

Grüße

**Comment by mcuiobroker** [comment]
V3.1.2 mal probiert?

**Comment by domi1893** [comment]
> V3.1.2 mal probiert?

gerade upgedatet, gleiches Verhalten

**Comment by Zefau** [comment]
@domi1893 Ohne Umstellen von Einstellungen den Reverse-Proxy auf Port `8400` konfigurieren.

**Comment by Zefau** [comment]
@domi1893

**Comment by domi1893** [comment]
> @domi1893 Ohne Umstellen von Einstellungen den Reverse-Proxy auf Port `8400` konfigurieren.

Sorry, ich teste morgen
