### ISSUE TITLE
Verbindung fehlgeschlagen nach IO-Broker neustart /Backup einspielen

### ISSUE THREAD

**Issue by jarvisde** [Zefau/ioBroker.jarvis#1604]
Bei diesem Post handelt es sich um 2 Probleme.

Da ich gerne meine Visualisierung von jarvis 2.2.1 auf V3 Upgrade will habe ich eine neue SD Karte für meinen PI bestellt und soweit vorbereitet. IO-Broker installiert einige Adapter installiert (ebenfalls Jarvis V2.2.1) und nun wollte ich unter Objekte die JASON Zeichenkette für devices und Layout einfügen die ich zuvor in einer txt Datei gesichert hatte. Bei Devices hat er meine Daten einfach übernommen. Bei layout kam die Meldung kein object. Ein Weiterkommen war für mich an dieser stelle nicht möglich. 

Also dachte ich mir damit ich erstmal wieder eine Visualisierung habe steck ich die alte SD Karte ein.
Also hab ich den PI vom Strom getrennt, die SD Karten gewechselt und den Neustart abgewartet.
IO-Broker Oberfläche war nach kurzer Zeit erreichbar, leider konnte ich das jarvis nicht mehr erreichen. Es wird nur ein roter Bildschirm mit Verbindung fehlgeschlagen angezeigt. Hierzu die folgenden Screenshots mit dem Fehler und meiner Parametrierung:

![Jarvis_Fehler01](https://user-images.githubusercontent.com/99388414/153359375-eadaefc9-8afb-45c4-9820-3864acbe8ddd.jpg)
![Jarvis_Fehler02](https://user-images.githubusercontent.com/99388414/153359380-d71aff18-9d50-41cb-8785-e022b9183d04.jpg)
![Jarvis_Fehler03](https://user-images.githubusercontent.com/99388414/153359369-0d499faa-a855-4ac1-a405-b1e6b48ab30f.jpg)
![Jarvis_Fehler04](https://user-images.githubusercontent.com/99388414/153359374-48a28ad6-d2ef-4adb-b0af-4046601f1e9b.jpg)

**Comment by Zefau** [comment]
Du bist noch auf V2. Sofern du bereits v3 drauf hast, hat das nicht geklappt.

Die Verbindung von jarvis zu ioBroker klappt nicht. Hast du Socket im Web Adapter aktiviert?

**Comment by jarvisde** [comment]
aktuell habe ich auf beiden SD Karten die V2 installiert daran kann es also nicht liegen das die Backups nicht gehen.

Hier meine Einstellungen vom WEB Adapter und vom Socket-io 

![jarvis_web](https://user-images.githubusercontent.com/99388414/153371031-ad30b74c-7f20-4276-9309-2e1fc4cdb73d.jpg)
![jarvis_socket](https://user-images.githubusercontent.com/99388414/153371056-3c7c12c1-d2d3-4890-95f8-e10d65ce8690.jpg)

Dies müsste so passen oder?

**Comment by Zefau** [comment]
Force Web Sockets raus und lieber statt integrated auf Socket-io umstellen

**Comment by jarvisde** [comment]
vielen Dank für die schnelle Antwort habe die einstellungen angepasst und die Jarvis Instanz neugestartet leider hat sich das Verhalten nicht geändert

**Comment by jarvisde** [comment]
Gibt es noch andere Lösungsansätze die ich probieren könnte?

**Comment by jarvisde** [comment]
ja das stimmt aber ich will gerne die es SD Karte wechseln daher wäre doch der erste Schritt meine Konfiguration in die Objetkte auf der neuen SD Karte zu schreiben die geht aber wie in Eingangspost erwähnt nicht spielt die Reihenfolge beim beschreiben der Objekte eine Rolle oder wo könnte dort mein Fehler sein ?

**Comment by mcuiobroker** [comment]
Hast du Notepad++? -> Json prüfen
![image](https://user-images.githubusercontent.com/84818934/153482251-cc20bb2e-2b88-4575-9241-a85fca1824f5.png)

**Comment by jarvisde** [comment]
ich habe meine Visualisierung auf der neuen SD Karte durch einfügen der JSON Zeichenketten wieder ans laufen gebracht. nun möchte ich diese gerne auf V3.0.11 updaten wie mache ich das im Adapter Menü steht das Jarvis in Version 2.2.1 verfügbar ist und ich diese installiert habe?

**Comment by Zefau** [comment]
Adapter Liste aktualisieren. Jarvis ist seit heute im stable

**Comment by jarvisde** [comment]
Update auf V3.0.11 hat einwandfrei geklappt
Das Problem mit der 2.2.1 ist daher nicht mehr relevant
