### ISSUE TITLE
Nach Stromausfall und Neustart Verbindung verloren

### ISSUE THREAD

**Issue by fk0711** [Zefau/ioBroker.jarvis#1606]
**Prerequisites / Voraussetzungen**
- [ x] Jarvis Adapter 2.1.1 und IoBroker 5.2.3 auf RPi mit 4GB RAM
- [ x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]

![image](https://user-images.githubusercontent.com/99428132/153476562-1c8cf77e-6991-4025-b7c5-de81263c5ea1.png)

![image](https://user-images.githubusercontent.com/99428132/153477460-56c69820-235f-46fa-8e2e-3cd31daf1d65.png)

Ich hatte eine lauffähige Jarvisanwendung, die sowohl im Browser (Safari, Google Chrom als auch von Mobile Device) über die IP-Adresse erreichbar war und gut funktionierte.

Als ich zuletzt ein Gerät editierte, hatten wir leider eine Stromausfall. Nach dem Neustart des Raspi und des IoBrokers bekomme ich seitdem beim Start der Jarvis-Instanz den roten Screen mit "Verbindung fehlgeschlagen".

Folgende Maßnahmen habe ich bereits erfolglos ausprobiert:
- Backup von Vortag und VorVortag eingespielt
- zweite Jarvis Instanz installiert
- Jarvis-Adapter deinstalliert und neu installiert 
- Web.0-Instanzeinstellungen von integrated auf socketio umgestellt

Mit der Bitte um Hilfe

**Comment by mcuiobroker** [comment]
Stell mal Dein letztes Backup rein, was noch lief. 
Als 
![image](https://user-images.githubusercontent.com/84818934/153519318-5bc94906-5231-47e5-9bfa-4a6c63fd38fd.png)

**Comment by fk0711** [comment]
vielen Dank für die schnelle Antwort. Habe alles umgesetzt, jedoch leider erfolglos. Bekomme weiterhin beim Start der Jarvis-Instanz den roten Screen mit der Meldung "Verbindung fehlgeschlagen".

![image](https://user-images.githubusercontent.com/99428132/153592126-9e8335eb-cdfa-4bad-ae18-0a507e04c8df.png)

![image](https://user-images.githubusercontent.com/99428132/153592346-3c2f4dc8-172c-4576-a4b2-6af2c51a4f44.png)

**Comment by Zefau** [comment]
Ich empfehle ein Upgrade auf v3

**Comment by fk0711** [comment]
V3.0.11 funktioniert!

Besten Dank!!!
