### ISSUE TITLE
Client disconnecting: transport close

### ISSUE THREAD

**Issue by bastian1607** [Zefau/ioBroker.jarvis#1607]
Ich nutze: 
Jarvis v3.0.12-beta.0
Fullybrowser v2.0.10
FireHD 10 Tablet

Node.js v14.19.0
NPM 6.14.16

Tablet hängt am WLAN Fritz Wlan Repeater 600, welcher mit einem AP verbunden ist.

Ich habe Jarvis Beta vor zwei Wochen installiert und eingerichtet, vor einer Woche bin ich "live gegangen" Zuhause an unserem Tablet.   Mir fällt auf, dass Jarvis andauernd neu lädt. Das ist wirklich störend, da dies mehrmals in der Stunde passiert. 
Ich habe heute den Debug auf Jarvis und Fullybrowser eingeschaltet und mir ist die Zeile aufgefallen:
Client with IP xxx disconnecting: transport close. 

Später connected das Tablet auch wieder (3 Sekunden später). Das ist der Reload. Sehr merkwürdig. Die Wlan-Verbindung ist stabil. 

![image](https://user-images.githubusercontent.com/79959369/153549959-a7725d35-3213-40e2-9cf5-d81a6b318fb6.png)

Ich hatte erst an den 120 Sekunden gedacht wo Jarvis wieder zur ersten Seite zurück soll, aber das ist nicht der Fall.

**Comment by Zefau** [comment]
siehe https://socket.io/docs/v4/troubleshooting-connection-issues/#problem-the-socket-gets-disconnected, ggf. einer der dort genannten Punkte?

**Comment by Zefau** [comment]
oder auch https://socket.io/docs/v4/troubleshooting-connection-issues/#problem-the-socket-is-stuck-in-http-long-polling

Kannst du mal im Network Tab schauen, was für Requests ausgetauscht werden?

**Comment by bastian1607** [comment]
Ich bin ganz ehrlich, ich verstehe nur Bahnhof. Da muss ich mich erstmal einlesen.

Ich kann nur sagen, dass ich das Problem mit der normalen Vis nicht hatte, aber das scheint dir klar zu sein. ':-)

**Comment by bastian1607** [comment]
Es scheint am Client zu liegen. Auf dem Laptop oder Handy keinerlei Probleme.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1438#issuecomment-1013351449

**Comment by bastian1607** [comment]
Siehe https://github.com/Zefau/ioBroker.jarvis/issues/1479#issuecomment-1013649463 und https://github.com/Zefau/ioBroker.jarvis/issues/1479#issuecomment-1013622122
werde nun Chrome installieren und weiter testen.

**Comment by bastian1607** [comment]
Chrome und den Web installiert, keine Besserung.

**Comment by Zefau** [comment]
@bastian1607 besteht das Problem mit v3.1 noch?
