### ISSUE TITLE
Kalender Sortierung

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#1608]
Ich fände es cool wenn man im Kalender pro Kalender sortieren könnte, und man der Sortierung einen Namen geben könnte

![image](https://user-images.githubusercontent.com/25475385/153602309-ade1de58-857f-49fa-a333-016649bdce5d.png)

**Comment by Zefau** [comment]
Der Screenshot zeigt aber kein jarvis Modul

**Comment by Zefau** [comment]
Dann ist es doch dasselbe wie https://github.com/Zefau/ioBroker.jarvis/issues/529 ?

**Comment by duczz** [comment]
Ne, außer du hattest eine Kategorisierung der einzelnen Kalender im selben Zuge mit vor
