### ISSUE TITLE
Widget DisplayImage does not refresh

### ISSUE THREAD

**Issue by Tom54497** [Zefau/ioBroker.jarvis#1609]
Widget DateTime doesn't pull sunrise and sunset anymore
Widget DisplayImage doesn't refresh pic any more

**Comment by Zefau** [comment]
Regarding DateTime: Can you screenshot your configuration? Did you activate sunset / sunrise option? Did you maintain the GPS coordinates within ioBroker for jarvis to be able to calculate the times?

Regarding DisplayImage: Can you screenshot your configuration? What refresh time and method did you configure? Is it a device or URL?

**Comment by Tom54497** [comment]
DateTime issue has been solved. Admin adapter lost GPS koordinates somehow. Works flawlessly again.

DisplayImage has been tried with all refresh methods but doesn't update the pic even if refreshing time is set to 1 second. With Jarvis V2 it worked. It is an URL of an IP cam.

When will there be an adapter for IP Cams?

**Comment by Tom54497** [comment]
![Screenshot (73)_LI](https://user-images.githubusercontent.com/40543008/153748777-5ec8d8a7-c171-4d29-b6f7-ccc32418898e.jpg)

**Comment by Zefau** [comment]
Hast du mal mit dem Aktualisierungsintervall "gespielt" und mal 10s probiert?

**Comment by Tom54497** [comment]
Actually it works although nothing has been changed on my side. Thx for support.
