### ISSUE TITLE
Asksin++ Homebrew Geräte

### ISSUE THREAD

**Issue by 63chris** [Zefau/ioBroker.jarvis#1612]
Auch hier noch mal Respekt und Dank für die tolle Arbeit.

ist angedacht (oder möglich) die Erkennung für Asksin++ Geräte, speziell die Homebrew-Geräte einzubauen. Die sind wirklich fantastisch und haben eine recht grosse Fangemeinde (zu Recht).
Die Liste ist mittlerweile ziemlich lang, das sind wohl zu viele. Ggfls. Implementierung einzelner Geräte auf Anfrage?
https://github.com/jp112sdl/JP-HB-Devices-addon
https://asksinpp.de/Sketche/#eigentwicklungen (die ist bei weitem nicht vollständig :-) )

Ich habe z.Z. die folgenden Geräte im Einsatz/Vorbereitung
- [HB-UNI-Sen-LEV-US](https://github.com/jp112sdl/HB-UNI-Sen-LEV-US)
- [HB-UNI-Sen-TEMP-DS18B20](https://github.com/jp112sdl/HB-UNI-Sen-TEMP-DS18B20)
- [HB-UNI-SenAct-4-4](https://github.com/jp112sdl/HB-UNI-SenAct-4-4)
- [HB-UNI-Sen-DUMMY-BEACON](https://github.com/jp112sdl/HB-UNI-Sen-DUMMY-BEACON)
- [HB-UNI-Sen-VOLT](https://github.com/jp112sdl/HB-UNI-Sen-VOLT)
- [HB-UNI-Sen-CAP-MOIST](https://github.com/jp112sdl/HB-UNI-Sen-CAP-MOIST)
- [HB-UNI-Sen-RFID-RC](https://github.com/jp112sdl/HB-UNI-Sen-RFID-RC)

falls das überhaupt eine Option ist und ich dazu Info's beitragen kann, bitte um Rückmeldung

Danke und Gruss
Chris

**Comment by 63chris** [comment]
Hallo,

wow, das war schnell.
Über den hm-rpc Adapter. Diese Geräte arbeiten wie alle HM classic Geräte mit rfd, Protocoll im Adapter ist XML-RPC? 
Die Datenpunkte der Arduinos werden dann über CCU addons übergeben, z.B. das JP-HB-Devices-addon (https://github.com/jp112sdl/JP-HB-Devices-addon). Denke mal, in diesen XML's sind die Datenpunkte für Jerome's Geräte definiert (https://github.com/jp112sdl/JP-HB-Devices-addon/tree/master/src/addon/firmware/rftypes).

Ich kann gerne screenshots der Objekte in ioBroker machen, aber erst in gut 2 Wochen. Die Geräte sind in der Datscha (bzw noch im Aufbau) und früher komme ich da (leider) nicht hin.

Gruss
Chris
![grafik](https://user-images.githubusercontent.com/34574073/153744662-1ece4d5c-36ce-44d8-9c62-d511d364c68d.png)

**Comment by Zefau** [comment]
> Ich kann gerne screenshots der Objekte in ioBroker machen, aber erst in gut 2 Wochen. 

Jo bitte, dann kann ich es integrieren.

**Comment by 63chris** [comment]
brauch noch etwas Zeit, bin noch nicht dazu gekommen

**Comment by 63chris** [comment]
so, bin endlich dazu gekommen. Im Anhang die Geräte, die mir persönlich am wichtigsten sind. 4 muss ich noch bauen, damit die angelernt werden können
Falls etwas fehlt, bitte um Rückmeldung

viele Grüße
Chris
[HM-Homebrew Geräte - 1.odt](https://github.com/Zefau/ioBroker.jarvis/files/8842784/HM-Homebrew.Gerate.-.1.odt)

**Comment by Zefau** [comment]
Danke dir! Habe jetzt auch gesehen, dass du https://github.com/jp112sdl/JP-HB-Devices-addon/tree/master/src/addon/firmware/rftypes verlinkt hast, wo ja alles drin steht. Ich versuche mal, dass ich alle Geräte reinbringe.

**Comment by 63chris** [comment]
das wäre natürlich der Traum.

PS: bin zwar ein Programmier-Legasteniker, aber wenn es ein Tool (oder template) geben würde, womit Du die Daten schnell und effizient einbauen könntest. Es kommen ja immer wierder neue Geräte. Dann könnte die Community etwas Vorarbeit machen. Nur so ein Gedanke

Grüße
Chris

**Comment by Zefau** [comment]
@63chris die Datenpunkte aus der GitHub Dokumentation zu ziehen ist sehr aufwendig.

Kannst du mir deine Geräte aus dem Objekt-Baum exportieren? Dann kann ich die Informationen einfacher abziehen.

![image](https://user-images.githubusercontent.com/14368811/196789009-05c4ef16-4b0b-46f5-bd43-d8c61444377c.png)

**Comment by 63chris** [comment]
mache ich asap

Chris

**Comment by Zefau** [comment]
@63chris kannst du mir das noch downloaden und schicken? iobroker.jarvis@mailbox.org

**Comment by 63chris** [comment]
siehe mail, vielen Dank

Chris

**Comment by Zefau** [comment]
Schau mal bitte mit `v3.1.0-beta.33`. Sag gerne Bescheid, wenn dir noch Datenpunkte fehlen.

**Comment by 63chris** [comment]
Herzlichen Dank, mache ich
