### ISSUE TITLE
Fehlende/unvollständige HM-IP Geräte

### ISSUE THREAD

**Issue by 63chris** [Zefau/ioBroker.jarvis#1613]
bei u.a. Geräten sind Datenpunkte entweder nicht vorhanden oder unvollständig. 
Falls weiter Info's gewünscht/erforderlich sind, kann ich gerne versuchen, die nachzureichen. Falls eine Aufteilung in einzelne feature requests wegen Übersichtlichkeit besser ist, mache ich das natürlich. Info genügt.

- HmIP-SCI Kontaktschnittstelle (keine Datenpunkte)
- HMIP-PSM Steckdose mit Leistungsmessung (fehlende Datenpunkte wie current, energy_counter, voltage, ...)
- HMIP-RCV-50 virtuelle Taster der CCU (keine Datenpunkte, btw, gilt für HM-RCV-50 auch)
- HmIP-SWO-PR - Wetterstation

kann man ja alles mauell konfigurieren, ist also ein "convenience" request, somit low priority

Danke & Gruss
Chris

**Comment by Machinimo** [comment]
Virtuelle Geräte des HomeMatic RPC-Adapters lassen sich mit der v3 ebenfalls nicht mehr importieren (mit der v2 ging das noch), da angeblich States fehlen. Ich habe hier beispielsweise 2 Heizkörperthermostate zu einem virtuellen Gerät zusammengefasst. Falls weitere Infos gewünscht sind, liefere ich die natürlich gerne nach.

Danke

**Comment by 63chris** [comment]
@Machinimo 
jetzt, wo Du es sagst, ja, die Datenpunkte z.B. einer Heizungsgruppe werden nicht übernommen. Die möchte man ja zentral steuern.
Kann man auch händisch machen, ist aber deutlich aufwändiger.
![grafik](https://user-images.githubusercontent.com/34574073/154830872-b6636924-4ba3-42aa-9767-e222cdb16e6c.png)

**Comment by Zefau** [comment]
Über `hm-rpc` (CCU) oder `hmip` (Access Point) ?

## `HmIP-SCI`
Ist nicht definiert. Ich brauche ich eine Angabe welcher Datenpunkte importiert werden sollen, z. B.
```
"HmIP-BSM": {
	"power": {
		"state": ".4.STATE",
		"action": ".4.STATE"
	},
		"powerMeter": {
		"state": ".7.POWER"
	},
	"powerVoltage": {
		"state": ".7.VOLTAGE"
	},
	"powerFrequency": {
		"state": ".7.FREQUENCY"
	}
}
``` 

## `HmIP-PSM`
Ist wie folgt hinterlegt:
```
"HmIP-PSM": {
	"power": {
		"state": ".3.STATE"
	},
	"meter": {
		"state": ".6.POWER"
	}
}
```

## `HmIP-RCV-50`
nicht definiert

## `HmIP-SWO-PR`
nicht definiert, aber `HmIP-SWO-B` ist wie folgt definiert
```
"HmIP-SWO-B": {
	"humidity": {
		"state": ".1.HUMIDITY"
	},
	"wind": {
		"state": ".1.WIND_SPEED"
	},
	"temperature": {
		"state": ".1.ACTUAL_TEMPERATURE"
	},
	"illumination": {
		"state": ".1.ILLUMINATION"
	},
	"sunshineDuration": {
		"state": ".1.SUNSHINEDURATION"
	}
}
```

**Comment by 63chris** [comment]
bei mir alles über hm-rpc. Ist die Info so hilfreich, Beispiel HMIP-SCM (nur ausgewählte Datenpunkte).
Wenn ja, schiebe ich das so für die anderen Geräte auch einzeln rüber

![grafik](https://user-images.githubusercontent.com/34574073/154845585-fe6136dc-8022-4c71-a5ae-7464659f48c4.png)
-----------------------------------------------------------
{
  "type": "state",
  "common": {
    "name": "Anwesenheit:0.LOW_BAT",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.lowbat"
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 5,
    "MAX": true,
    "FLAGS": 9,
    "ID": "LOW_BAT",
    "TYPE": "BOOL",
    "DEFAULT": false
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1644680453967,
  "_id": "hm-rpc.1.001E1D898A3A21.0.LOW_BAT",
  "acl": {
    "object": 1636,
    "state": 1636,
    "file": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
---------------------------------------------------------------------------
{
  "type": "state",
  "common": {
    "name": "Anwesenheit:0.RSSI_DEVICE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -128,
    "max": 127,
    "unit": "dBm",
    "role": "value.rssi"
  },
  "native": {
    "MIN": -128,
    "OPERATIONS": 5,
    "MAX": 127,
    "FLAGS": 1,
    "ID": "RSSI_DEVICE",
    "TYPE": "INTEGER",
    "DEFAULT": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1644680453989,
  "_id": "hm-rpc.1.001E1D898A3A21.0.RSSI_DEVICE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "file": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
--------------------------------------------------------------------------------------
{
  "type": "state",
  "common": {
    "name": "Anwesenheit:0.UNREACH",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.unreach"
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 5,
    "MAX": true,
    "FLAGS": 25,
    "ID": "UNREACH",
    "TYPE": "BOOL",
    "DEFAULT": false
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1644680453973,
  "_id": "hm-rpc.1.001E1D898A3A21.0.UNREACH",
  "acl": {
    "object": 1636,
    "state": 1636,
    "file": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
-------------------------------------------------------------------------------------------
{
  "type": "state",
  "common": {
    "name": "Anwesenheit:1.STATE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1,
    "states": {
      "0": "CLOSED",
      "1": "OPEN"
    },
    "role": "value.window"
  },
  "native": {
    "MIN": "CLOSED",
    "UNIT": "\"\"",
    "OPERATIONS": 5,
    "MAX": "OPEN",
    "FLAGS": 1,
    "ID": "STATE",
    "TAB_ORDER": 0,
    "TYPE": "ENUM",
    "DEFAULT": "CLOSED",
    "VALUE_LIST": [
      "CLOSED",
      "OPEN"
    ],
    "CONTROL": "DOOR_SENSOR.STATE"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1644680454036,
  "_id": "hm-rpc.1.001E1D898A3A21.1.STATE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "file": 1632,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Machinimo** [comment]
Die Heizungsgruppen laufen auch über den hm-rpc Adapter. Anbei die relevanten Einstellungsmöglichkeiten:

{
  "type": "state",
  "common": {
    "name": "Heizung Wohnzimmer INT0000001:0.LOW_BAT",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.lowbat"
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 5,
    "MAX": true,
    "FLAGS": 9,
    "ID": "LOW_BAT",
    "TYPE": "BOOL",
    "DEFAULT": false
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1635255802087,
  "_id": "hm-rpc.2.INT0000001.0.LOW_BAT",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

{
  "type": "state",
  "common": {
    "name": "Heizung Wohnzimmer INT0000001:0.UNREACH",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.unreach"
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 5,
    "MAX": true,
    "FLAGS": 25,
    "ID": "UNREACH",
    "TYPE": "BOOL",
    "DEFAULT": false,
    "CONTROL": "MAINTENANCE.UNREACH"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1635255802093,
  "_id": "hm-rpc.2.INT0000001.0.UNREACH",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

{
  "type": "state",
  "common": {
    "name": "Heizung Wohnzimmer INT0000001:1.ACTUAL_TEMPERATURE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -3276.8,
    "max": 3276.7,
    "unit": "°C",
    "role": "value.temperature",
    "smartName": {
      "de": "Wohnzimmer Heizung",
      "smartType": "THERMOSTAT"
    }
  },
  "native": {
    "MIN": -3276.8,
    "OPERATIONS": 5,
    "MAX": 3276.7,
    "FLAGS": 1,
    "ID": "ACTUAL_TEMPERATURE",
    "TYPE": "FLOAT",
    "DEFAULT": 0,
    "CONTROL": "HEATING_CONTROL_HMIP.TEMPERATURE"
  },
  "_id": "hm-rpc.2.INT0000001.1.ACTUAL_TEMPERATURE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1635255802189
}

{
  "type": "state",
  "common": {
    "name": "Heizung Wohnzimmer INT0000001:1.BOOST_MODE",
    "def": false,
    "type": "boolean",
    "read": false,
    "write": true,
    "role": "switch.mode.boost",
    "smartName": false
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 6,
    "MAX": true,
    "FLAGS": 1,
    "ID": "BOOST_MODE",
    "TYPE": "BOOL",
    "DEFAULT": false,
    "CONTROL": "HEATING_CONTROL_HMIP.BOOST_MODE"
  },
  "_id": "hm-rpc.2.INT0000001.1.BOOST_MODE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1636493839521
}

{
  "type": "state",
  "common": {
    "name": "Heizung Wohnzimmer INT0000001:1.CONTROL_MODE",
    "def": 0,
    "type": "number",
    "read": false,
    "write": true,
    "min": 0,
    "max": 3,
    "role": "indicator"
  },
  "native": {
    "MIN": 0,
    "OPERATIONS": 2,
    "MAX": 3,
    "FLAGS": 1,
    "ID": "CONTROL_MODE",
    "TYPE": "INTEGER",
    "DEFAULT": 0,
    "CONTROL": "HEATING_CONTROL_HMIP.CONTROL_MODE"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1635255802130,
  "_id": "hm-rpc.2.INT0000001.1.CONTROL_MODE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

{
  "type": "state",
  "common": {
    "name": "Heizung Wohnzimmer INT0000001:1.PARTY_MODE",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "switch.mode.party"
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 5,
    "MAX": true,
    "FLAGS": 1,
    "ID": "PARTY_MODE",
    "TYPE": "BOOL",
    "DEFAULT": false,
    "CONTROL": "HEATING_CONTROL_HMIP.PARTY_MODE"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1635255802125,
  "_id": "hm-rpc.2.INT0000001.1.PARTY_MODE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

{
  "type": "state",
  "common": {
    "name": "Heizung Wohnzimmer INT0000001:1.SET_POINT_TEMPERATURE",
    "def": 4.5,
    "type": "number",
    "read": true,
    "write": true,
    "min": 4.5,
    "max": 30.5,
    "unit": "°C",
    "role": "level.temperature",
    "smartName": {
      "de": "Wohnzimmer Heizung",
      "smartType": "THERMOSTAT"
    }
  },
  "native": {
    "MIN": 4.5,
    "UNIT": "�C",
    "OPERATIONS": 7,
    "MAX": 30.5,
    "FLAGS": 1,
    "ID": "SET_POINT_TEMPERATURE",
    "TYPE": "FLOAT",
    "DEFAULT": 4.5,
    "CONTROL": "HEATING_CONTROL_HMIP.SETPOINT"
  },
  "_id": "hm-rpc.2.INT0000001.1.SET_POINT_TEMPERATURE",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1635255802160
}

**Comment by 63chris** [comment]
Hallo, hier die "wichtigsten" Datenpunkte zur Wetterstation HmIP-SWO-PR

**Low Batterie**
 "type": "state",
  "common": {
    "name": "Wetterstation:0.LOW_BAT",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.lowbat"
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 5,
    "MAX": true,
    "FLAGS": 9,
    "ID": "LOW_BAT",
    "TYPE": "BOOL",
    "DEFAULT": false
**Unreach**
 "type": "state",
  "common": {
    "name": "Wetterstation:0.UNREACH",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
    "role": "indicator.unreach"
  },
  "native": {
    "MIN": false,
    "OPERATIONS": 5,
    "MAX": true,
    "FLAGS": 25,
    "ID": "UNREACH",
    "TYPE": "BOOL",
    "DEFAULT": false
**Temperatur**
"type": "state",
  "common": {
    "name": "Wetterstation:1.ACTUAL_TEMPERATURE",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": -3276.8,
    "max": 3276.7,
    "unit": "°C",
    "role": "value.temperature",
**Humidity**
"type": "state",
  "common": {
    "name": "Wetterstation:1.HUMIDITY",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 100,
    "unit": "% rF",
    "role": "value.humidity",
**Helligkeit**
"type": "state",
  "common": {
    "name": "Wetterstation:1.ILLUMINATION",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 163830,
    "role": "value.brightness",
**Regen J/N**
"type": "state",
  "common": {
    "name": "Wetterstation:1.RAINING",
    "def": false,
    "type": "boolean",
    "read": true,
    "write": false,
**Regenzähler**
"type": "state",
  "common": {
    "name": "Wetterstation:1.RAIN_COUNTER",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 1638,
    "unit": "mm",
**Sonnenscheindauer**
"type": "state",
  "common": {
    "name": "Wetterstation:1.SUNSHINEDURATION",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 16383,
    "unit": "min",
**Windrichtung**
 "type": "state",
  "common": {
    "name": "Wetterstation:1.WIND_DIR",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 357.5,
    "unit": "Grad"
**Windgeschwindigkeit**
 "type": "state",
  "common": {
    "name": "Wetterstation:1.WIND_SPEED",
    "def": 0,
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 200,
    "unit": "km/h",

![grafik](https://user-images.githubusercontent.com/34574073/156915790-67c02ad0-3720-474d-bcfc-55914be34eae.png)
![grafik](https://user-images.githubusercontent.com/34574073/156915813-a3836e34-a9b1-4d0b-a241-570c2355cc93.png)

**Comment by Zefau** [comment]
@Machinimo Was genau ist das ein Gerät von dem du die Datenpunkt beschrieben hast? Ich bräuchte dazu die Kennung, also `HmIP-xxxxx`

**Comment by Zefau** [comment]
@Machinimo
