### ISSUE TITLE
Absturz des Adapters bei Nutzung eines iPads mit ioBroker App

### ISSUE THREAD

**Issue by saint-hh** [Zefau/ioBroker.jarvis#1614]
Jarvis 3.0.11 Pro
System: Raspi 4 - Raspbian Linux 10, Linux 5.10.63-v7l+ auf armv7
ioBroker: 3.3.22, Node.js v14.19.0, NPM 6.14.16

Heute das Upgrade auf V3 vollzogen und auch gleich die Pro gekauft. Auf dem Mac läuft es, auf dem iPhone (ioBroker App ) auch - nur wenn ich versuche Jarvis auf dem iPad mit der ioBroker App aufzurufen, stürzt der Adapter im ioBroker ab und Jarvis ist auch von den anderen Geräten nicht mehr erreichbar.

Die Fehlermeldungen im ioBroker sind:

pberrypi | 2022-02-13 18:04:52.994 | error | instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
jarvis.0 | 2022-02-13 18:04:52.329 | error | Cannot read property 'replace' of null
jarvis.0 | 2022-02-13 18:04:52.329 | error | TypeError: Cannot read property 'replace' of null at Namespace.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/websocket.io.min.js:1:7075) at Namespace.emit (events.js:400:28) at Namespace.emitReserved (/opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/typed-events.js:56:22) at /opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/namespace.js:141:26 at processTicksAndRejections (internal/process/task_queues.js:77:11)
jarvis.0 | 2022-02-13 18:04:52.328 | error | uncaught exception: Cannot read property 'replace' of null

So lange ich das iPad außen vor lasse, läuft Jarvis V3 prima. Ist da etwas bekannt?

**Comment by saint-hh** [comment]
Mit dem zweiten iPad in der Familie getestet. Die ioBroker App erstinstalliert und mit den selben Einstellungen wie bei den (funktionierenden) iPhones versehen. Selber Fehler. 
Anbei Screenshots vom iPad
Log vom ioBroker:


i | 2022-02-13 19:23:42.910 | warn | Do not restart adapter system.adapter.jarvis.0 because restart loop detected
-- | -- | -- | --
host.raspberrypi | 2022-02-13 19:23:42.910 | info | Restart adapter system.adapter.jarvis.0 because enabled
host.raspberrypi | 2022-02-13 19:23:42.908 | error | instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
jarvis.0 | 2022-02-13 19:23:42.236 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
jarvis.0 | 2022-02-13 19:23:42.235 | info | terminating
jarvis.0 | 2022-02-13 19:23:42.234 | info | Adapter stopped und unloaded.
jarvis.0 | 2022-02-13 19:23:42.229 | error | Cannot read property 'replace' of null
jarvis.0 | 2022-02-13 19:23:42.228 | error | TypeError: Cannot read property 'replace' of null at Namespace.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/websocket.io.min.js:1:7075) at Namespace.emit (events.js:400:28) at Namespace.emitReserved (/opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/typed-events.js:56:22) at /opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/namespace.js:141:26 at processTicksAndRejections (internal/process/task_queues.js:77:11)
jarvis.0 | 2022-02-13 19:23:42.227 | error | uncaught exception: Cannot read property 'replace' of null



![IMG_0084](https://user-images.githubusercontent.com/25373251/153769673-5f3b2c95-cb03-4c63-89e2-c46d6fd2a138.jpg)
![IMG_0085](https://user-images.githubusercontent.com/25373251/153769689-8ffe2527-cb65-40cd-85b7-639c34a4642d.jpg)
.

**Comment by Zefau** [comment]
Installiere dir mal bitte die aktuelle `v3.0.12-beta.1` von Github (https://github.com/Zefau/ioBroker.jarvis) via Katze in ioBroker. Damit sollte es passen?

**Comment by saint-hh** [comment]
Moin Zefau,
installiert, schneller Test: jawoll, kann ich bestätigen - passt damit.
Beste Grüße in die Nachbarschaft und Danke für deine Arbeit!

![IMG_4C0FECBAA655-1](https://user-images.githubusercontent.com/25373251/153772212-3f0bcb78-2799-4136-8383-04de812f58c8.jpeg)
!
