### ISSUE TITLE
Mittige ausrichtung

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#1617]
Bei kleinen Grids wir der Text bei mittige Ausrichtung über das Grid unten weg verschoben.

**Comment by Zefau** [comment]
Bitte screenshot

**Comment by duczz** [comment]
![image](https://user-images.githubusercontent.com/25475385/154425888-6aea547b-71f3-4429-963b-3179d9785b60.png)

Andere Frage am Rande: Ist es eig nicht möglich n Grid automatisch zu vergrößern wenn der Inhalt zu groß wird (z.b. wie bei der Kalender Liste)?

**Comment by Zefau** [comment]
Was ist das für ein Module?

**Comment by duczz** [comment]
StateHTML war das

**Comment by Zefau** [comment]
@duczz besteht das Problem mit v3.1 noch?
