### ISSUE TITLE
HistoryGraph auto update

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1619]
Es fehlt beim HistoryGraph eine Einstellung mit der man den Graphen nach gewisser Zeit automatisch aktualisieren lassen kann.
Oder eine Refresh-Automatik, sobald sich die Werte im History-Adapter bzgl. der ausgewählten DPs ändern?

**Comment by Zefau** [comment]
Der HistoryGraph aktualisiert automatisch

**Comment by mcuiobroker** [comment]
Also bei Änderung von den DPs in der History, wird auf jeden Fall nicht aktualisiert. Vielleicht ist Zeit zu lang?
Variabel einstellbar wäre besser?

**Comment by TobiKr** [comment]
Solange das Feature nicht implementiert ist, lässt sich das ggf mit einem Javascript aktualisieren?

**Comment by anaCIRdes** [comment]
Hallo, wann könnte man hier mit einer Lösung rechnen oder sollte dies schon funktionieren? Verwende im Moment die Version 3.0.11 und dort wird leider nichts automatisch aktualisiert im History-Graph.

**Comment by Zefau** [comment]
@mcuiobroker @TobiKr @anaCIRdes bitte mal mit `v3.1.0-alpha.26` schauen

**Comment by mcuiobroker** [comment]
Keine Veränderung. Wann sollte sich der Graph ändern?

**Comment by mcuiobroker** [comment]
`v3.1.0-alpha.28`
Jetzt wird die Farbe mit Variable angezeigt. Der Graph hat sich jetzt verschoben und ein Achsenname ist wieder aufgetaucht.
![image](https://user-images.githubusercontent.com/84818934/181864283-d4856efa-5843-497f-8325-103158263e85.png)

**Comment by Zefau** [comment]
Ist das denn richtig oder falsch? Wenn falsch, zeig / kopiere mir nochmal deine Konfiguration zum nachstellen.

**Comment by mcuiobroker** [comment]
Es ist falsch

Konfiguration y-Achse
```
[
  {
    "position": "left",
    "name": "Bad",
    "nameLocation": "center",
    "nameGap": 70,
    "offset": -5,
    "padding": 10,
    "min": "dataMin",
    "max": "dataMax",
    "axisPointer": {
      "show": true
    },
    "splitLine": {
      "show": true,
      "lineStyle": {
        "color": "rgba(193, 22, 22, 1)",
        "type": "dotted"
      }
    },
    "axisLabel": {
      "formatter": "{value} °C",
      "margin": 25,
      "showMaxLabel": false,
      "showMinLabel": true,
      "color": "rgba(255, 255, 255, 1)"
    }
  },
  {
    "position": "right",
    "name": "Büro",
    "nameLocation": "center",
    "nameGap": 70,
    "offset": 0,
    "padding": 10,
    "min": "dataMin",
    "max": "dataMax",
    "axisLabel": {
      "formatter": "{value} °C",
      "margin": 25
    }
  }
]
```
Konfiguration der Serie
```
{
  "symbol": "rect",
  "symbolSize": 9,
  "label": {
    "show": false
  },
  "showAllSymbol": true,
  "colorBy": "data"
}
```
Callback
```
(val) => val /10
```

Widget
```
"4acb0466-f47c-4eff-a1a6-22c836cabc7f": {
    "id": "4acb0466-f47c-4eff-a1a6-22c836cabc7f",
    "config": {
      "chartType": "line",
      "maxEntries": "500",
      "legend": "top",
      "showSymbol": false,
      "zoom": false,
      "dataZoom": "100",
      "timeReviewValue": "1",
      "timeReviewUnit": "hours",
      "timeConfigurable": true,
      "dateFormat": "{HH}:{mm}",
      "timeType": "review",
      "yAxis": "[\n  {\n    \"position\": \"left\",\n    \"name\": \"Bad\",\n    \"nameLocation\": \"center\",\n    \"nameGap\": 70,\n    \"offset\": -5,\n    \"padding\": 10,\n    \"min\": \"dataMin\",\n    \"max\": \"dataMax\",\n    \"axisPointer\": {\n      \"show\": true\n    },\n    \"splitLine\": {\n      \"show\": true,\n      \"lineStyle\": {\n        \"color\": \"rgba(193, 22, 22, 1)\",\n        \"type\": \"dotted\"\n      }\n    },\n    \"axisLabel\": {\n      \"formatter\": \"{value} °C\",\n      \"margin\": 25,\n      \"showMaxLabel\": false,\n      \"showMinLabel\": true,\n      \"color\": \"rgba(255, 255, 255, 1)\"\n    }\n  },\n  {\n    \"position\": \"right\",\n    \"name\": \"Büro\",\n    \"nameLocation\": \"center\",\n    \"nameGap\": 70,\n    \"offset\": 0,\n    \"padding\": 10,\n    \"min\": \"dataMin\",\n    \"max\": \"dataMax\",\n    \"axisLabel\": {\n      \"formatter\": \"{value} °C\",\n      \"margin\": 25\n    }\n  }\n]",
      "xAxis": "",
      "callback": "(val) => val /10",
      "series": "{\n  \"symbol\": \"rect\",\n  \"symbolSize\": 9,\n  \"label\": {\n    \"show\": false\n  },\n  \"showAllSymbol\": true,\n  \"colorBy\":\"data\"\n}"
    },
    "title": "Temperaturen",
    "module": "HistoryGraph",
    "items": [
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "fb0e23f5-ecbf-4eff-86dd-bf5dc0b0df8b",
        "primaryStateKey": "HUE_BAD_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "influxdb.0",
        "moduleConfig": {
          "color": "var(--main-bg-color)",
          "yaxis": 0
        },
        "label": "Bad"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "4120ce50-c168-4604-8990-889b1a994412",
        "primaryStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "color": "#359eb8",
          "yaxis": 1
        },
        "label": "Buero"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "f18c0a7f-dec6-4b94-99a5-a29aded91f4a",
        "primaryStateKey": "HUE_SZ_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "yaxis": "",
          "color": "#b50707"
        },
        "label": "SZ"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "faeeb094-dafd-4b7a-b688-56a71b7196a6",
        "primaryStateKey": "HUE_KUECHE_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "yaxis": "",
          "color": "#c6d40b"
        },
        "label": "Küche"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "3ec9d998-34bb-4ff7-8cdb-c77949f4a3ff",
        "primaryStateKey": "HUE_FLUR_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "yaxis": "",
          "color": "#005c59"
        },
        "label": "Flur"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "09b520f8-86af-47e4-af19-5b8119912c38",
        "primaryStateKey": "HUE_WZ_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "yaxis": "",
          "color": "#0300c2"
        },
        "label": "WZ"
      }
    ],
    "revision": "a4885"
  },
```

**Comment by Zefau** [comment]
Auto-Update funktioniert, oder? Dann würde ich den Rest im Issue https://github.com/Zefau/ioBroker.jarvis/issues/1737 weiterverfolgen, da doppelt?

**Comment by mcuiobroker** [comment]
Auto-Update funktioniert nicht.

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by mcuiobroker** [comment]
Einmal nach F5 hat er aktualisiert.
Kannst du ein Log setzen, wenn er aktualisiert und wenn aktualisieren soll?
Und bitte in die Module Konfig eine Zeit setzbar für Aktualisierung:
![image](https://user-images.githubusercontent.com/84818934/193365952-51d21fdd-7650-47b1-8ab2-fb5cb1c37b5a.png)

![image](https://user-images.githubusercontent.com/84818934/193365695-78081140-83ad-4c16-bf53-8eb71841433a.png)
Nach F5
![image](https://user-images.githubusercontent.com/84818934/193365733-22bed026-6449-451d-9630-335a7c349c23.png)

**Comment by mcuiobroker** [comment]
Es kommt auch diese Warnung, wenn man nicht auf der History Seite ist:
![image](https://user-images.githubusercontent.com/84818934/193367423-99f66e60-1c9d-4a3a-8c2c-6332d7bfcfdc.png)
Dort bitte die Warnung ergänzen mit der WidgetID? Damit man weiß, vorher sie kommt.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.59` sollte der auto-update nun endlich funktionieren

**Comment by mcuiobroker** [comment]
`v3.1.0-alpha.60`
Welche Zeit ist da vorgegeben? 
Oder aktualisiert er nachdem ein Historywert hinzugefügt wurde zu einem DP?
Was sind die Bedingungen für eine Akualisierung?
Es wird nicht aktualisiert.
![jarvis-HistoryGraph-Aktualisierung](https://user-images.githubusercontent.com/84818934/196551174-8181e61e-72cf-42fc-8bcb-2a0bcdf54ff0.gif)

**Comment by Zefau** [comment]
Die Aktualisierung ist abhängig von der `Standard-Einheit des hist. Rückblicks`:
- Sekunden und Minuten aktualisieren minütlich
- Stunden aktualisieren stündlich (das werde ich nochmal auf alle 15 Minuten reduzieren)
- Tage aktualisieren alle 6 Stunden
- Wochen aktualisieren täglich
- Monate aktualisiert wöchentlich

Die Aktualisierung funktioniert bei mir. Bei mir ist die Standard-Einheit auf `Minuten` eingestellt.

**Comment by mcuiobroker** [comment]
Ich würde es einstellbar machen, da man sich zwar eine Übersicht über einen Tag anschaut, diese aber ständig aktuell sehen möchte. Und da sind die Bedürfnisse sicherlich unterschiedlich. Deswegen unabhängig von der Standardzeit, sondern die eingestellt Aktualisierungszeit.
Ansonsten auf jeden Fall, wenn du dabei bleiben möchtest, eine Aktualisierung alle 5 Minuten.

**Comment by Zefau** [comment]
Ich kann es zusätzlich noch konfigurierbar machen.

Die Frage ist eher, warum es be dir nicht funktioniert? Was hast du eingestellt?

**Comment by mcuiobroker** [comment]
Ich hatte den Standard-Bereich auf Stunden stehen und hab dann "nur" 10 Minuten gewartet. Aber da es ja so eingestellt ist, bei Stunden -> stündlich zu aktualisieren, ist klar, da es nicht funktionieren konnte.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.61` nun konfigurierbar

**Comment by mcuiobroker** [comment]
Sieht gut aus. Danke.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/v3-fuer-einsteiger/module/historygraph#auto-aktualisierungs-einstellung
Sind das jetzt die richtigen "auto" Zeiten?

**Comment by Zefau** [comment]
Ist so korrekt
