### ISSUE TITLE
wiki: Screenshots missing

### ISSUE THREAD

**Issue by bjoernbusch** [Zefau/ioBroker.jarvis#162]
In the wiki, in the modules section:

https://github.com/Zefau/ioBroker.jarvis/wiki/de-Modules

all the images for the screenshots are missing, e.g.:

https://raw.githubusercontent.com/Zefau/jarvis/master/src/modules/AdapterStatus/screenshots/AdapterStatus1.png

Any chance you could upload these as well?

Thanks!

**Comment by Zefau** [comment]
thanks for letting me know. I fixed this.
