### ISSUE TITLE
Adapter Info in ioBroker - Link zum Wiki

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1620]
Es fehlt im ioBroker-Adapter "?" mindestens ein Link zum Wiki , falls jemand dort Hilfe sucht.
![image](https://user-images.githubusercontent.com/84818934/154556228-1e958203-dc9d-4487-b18c-5d3d630b2a29.png)

**Comment by Zefau** [comment]
Mit `v3.1.0-alpha.9` wurde ein Info-Link hinzugefügt.

**Comment by mcuiobroker** [comment]
ok
