### ISSUE TITLE
Cannot read property 'native' of null

### ISSUE THREAD

**Issue by px51** [Zefau/ioBroker.jarvis#1621]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
Version 3.0.11
Ich komme leider nicht auf die JARVIS URL. Habe aber die folgenden Fehler im Log von IO-Broker. Ganz schlau werde ich daraus nicht. 
Wenn ich es irgendwie schaffen sollte packe ich noch, sofern vorhanden die Infos aus der Browser-Console dazu.

Ich nutze den aktuellen Edge, NODE.JS: V12.16.3, NPM: 6.14.4, keine SSL-Zertifikate. 
Jarvis habe ich ein paar mal in verschiedenen Versionen installiert, was am Fehlerbild leider nichts geändert hat. 
Auch geänderte Konfigurationen in Socket.io bzw. dem Web Adapter haben keinen Unterschied gemacht.. 

`<html>
<body>

host.Veriton | 2022-02-18 20:43:27.230 | warn | Do not restart adapter system.adapter.jarvis.0 because restart loop detected
-- | -- | -- | --
host.Veriton | 2022-02-18 20:43:27.229 | info | Restart adapter system.adapter.jarvis.0 because enabled
host.Veriton | 2022-02-18 20:43:27.226 | error | instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
jarvis.0 | 2022-02-18 20:43:25.736 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
jarvis.0 | 2022-02-18 20:43:25.732 | info | terminating
jarvis.0 | 2022-02-18 20:43:25.729 | info | Adapter stopped und unloaded.
jarvis.0 | 2022-02-18 20:43:25.707 | error | Cannot read property 'native' of null
jarvis.0 | 2022-02-18 20:43:25.706 | error | TypeError: Cannot read property 'native' of null at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:136:66) at processImmediate (internal/timers.js:458:21)
jarvis.0 | 2022-02-18 20:43:25.703 | error | uncaught exception: Cannot read property 'native' of null
jarvis.0 | 2022-02-18 20:43:25.656 | info | Found Backups for settings.
jarvis.0 | 2022-02-18 20:43:25.638 | info | Found Backups for devices.
jarvis.0 | 2022-02-18 20:43:25.634 | info | Found Backups for layout.
jarvis.0 | 2022-02-18 20:43:25.600 | info | No Backup found for styles, thus backing up initially.
jarvis.0 | 2022-02-18 20:43:25.597 | info | No Backup found for widgets, thus backing up initially.
jarvis.0 | 2022-02-18 20:43:25.518 | info | starting. Version 3.0.11 in /opt/iobroker/node_modules/iobroker.jarvis, node: v12.16.3, js-controller: 3.3.22

</body>
</html>`

**Comment by mcuiobroker** [comment]
Upgrade nodejs auf 14?

**Comment by px51** [comment]
Eben gemacht, leider gleicher Fehler:

<html>
<body>


host.Veriton | 2022-02-20 18:13:48.659 | info | Restart adapter system.adapter.jarvis.0 because enabled
-- | -- | -- | --
host.Veriton | 2022-02-20 18:13:48.657 | error | instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
jarvis.0 | 2022-02-20 18:13:47.944 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
jarvis.0 | 2022-02-20 18:13:47.940 | info | terminating
jarvis.0 | 2022-02-20 18:13:47.936 | info | Adapter stopped und unloaded.
jarvis.0 | 2022-02-20 18:13:47.759 | error | Cannot read property 'native' of null
jarvis.0 | 2022-02-20 18:13:47.757 | error | TypeError: Cannot read property 'native' of null at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:136:66) at processImmediate (internal/timers.js:466:21)
jarvis.0 | 2022-02-20 18:13:47.753 | error | uncaught exception: Cannot read property 'native' of null
jarvis.0 | 2022-02-20 18:13:47.718 | info | Found Backups for settings.
jarvis.0 | 2022-02-20 18:13:47.699 | info | Found Backups for devices.
jarvis.0 | 2022-02-20 18:13:47.694 | info | Found Backups for layout.
jarvis.0 | 2022-02-20 18:13:47.595 | info | No Backup found for styles, thus backing up initially.
jarvis.0 | 2022-02-20 18:13:47.591 | info | No Backup found for widgets, thus backing up initially.
jarvis.0 | 2022-02-20 18:13:47.415 | info | starting. Version 3.0.11 in /opt/iobroker/node_modules/iobroker.jarvis, node: v14.19.0, js-controller: 3.3.22


</body>
</html>

**Comment by px51** [comment]
Sind allerdings schon etwas weiter:

Scheint wohl irgendwie an meiner Konfiguration zu liegen, auch wenn ich noch nicht genau weiß, was das Problem ist. 
Socket.io wird von Jarvis nicht genutzt, oder? 

![image](https://user-images.githubusercontent.com/74839878/154856262-60a6bb09-bd04-494a-a70d-f4a37edb4a6a.png)

**Comment by px51** [comment]
Offenbar sind mein Socket.io und/oder web-Adapter nicht korrekt eingestellt.
Web.1 lässt alle IPs zu, läuft auf port 8082 und nutzt die Socket.io Instanz sonst ist nichts eingestellt oder angehakt.

Socket.io hört auf allen IPs seit eben auf 8400. im oberen Post war es noch 8083 
Mit 8400 sehen die Fehler schon mal anders aus. Finde in der Doku aber gerade auch nicht, was die korrekte Konfiguration ist.

![image](https://user-images.githubusercontent.com/74839878/154856726-6bc6ec8a-0828-4364-ba9b-58410e9678f4.png)

**Comment by mcuiobroker** [comment]
Dann zeig mal die Einstellungen vom WEB und jarvis

**Comment by Zefau** [comment]
jarvis zieht die Konfiguration immer aus `web.0`. Hast du die Instanz? Der Socket-IO Adapter wird nicht genutzt.

**Comment by Zefau** [comment]
Da entsteht der Fehler: 

https://github.com/Zefau/ioBroker.jarvis/blob/0d0c047474436474532ecf8e3d2fb5ea90b71c19/jarvis.js#L136

Wenn `system.adapter.web.0` geladen wird hat `obj` den Wert `null`, daher kann nicht auf `obj.native` zugegriffen werden:

https://github.com/Zefau/ioBroker.jarvis/blob/0d0c047474436474532ecf8e3d2fb5ea90b71c19/jarvis.js#L135

**Comment by px51** [comment]
Danke für die Antworten, ihr zwei! 

Ich hatte zwei Instanzen vom Web-Adapter laufen. Weswegen weiß ich nicht mehr, allerdings waren es web.1 und web.2. Daher kam auch immer der gleiche Fehler, weil die Config aus einem Adapter kommen sollte, den es gar nicht gab. Habe jetzt wieder web.0 und damit auch Jarvis am laufen!

Vielen Dank für die Hilfe und die geile Vis!
