### ISSUE TITLE
iFrame lädt Grafana Panels  beim herabscrollen nicht nach

### ISSUE THREAD

**Issue by Floatcher** [Zefau/ioBroker.jarvis#1622]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [V3 ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ kein Screenshot] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
Wenn man eine Grafana Seite mit vielen Panels untereinander hat und diese per iFrame in Jarvis integriert, werden nur die ersten Panels geladen, wenn man dann herunter scrollt, werden nicht mehr die weiteren Panels nachgeladen.

Scrollt man sofort herunter, sobald Jarvis die Grafana Seite anzeigt, werden diese nachgeladen.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by mcuiobroker** [comment]
Welche Version 3.0.11?

**Comment by Floatcher** [comment]
Ja, 3.0.11

**Comment by Zefau** [comment]
Beim iFrame habe ich nicht viele Möglichkeiten. Geht das bei vis denn?
