### ISSUE TITLE
Hamburger Menü für Seiten Navigation bei nur einer vorhandenen Seite ausblenden

### ISSUE THREAD

**Issue by Floatcher** [Zefau/ioBroker.jarvis#1624]
**Is your feature request related to a problem? Please describe.**

----- OR -----

**Describe the solution you'd like**
Wenn man nur 1 Seite in seinem Layout definiert hat, soll das Seitenmenü inkl. Hamburger Icon komplett ausgeblendet/deaktiviert werden, da es nutzlos ist. Gerade in der Mobilen Ansicht nimmt das Hamburger Menu Icon sehr viel Platz weg. Die Option Sidebar Mini Mode hat in der Mobile View keine Auswirkung und ist hier auch kein Mehrwert für den Platz.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/styles/menue

**Comment by Floatcher** [comment]
Leider sind custom CSSs nur in der Pro Version möglich. Diese Funktion in den Einstellungen wäre schön, da in der Free Variante das Seitenmenü kein Mehrwert hat.

**Comment by rschneider1509** [comment]
ich suche auch schon seit ner Weile nach ner Möglichkeit, die Sidebaar zu deaktivieren. Wenigstens in der Mobile Ansicht :)
Wie @Floatcher schon sagte, hat die Sidebar als free User sowieso keine Aufgabe, oder? außer dem "Settings" Button in der PC Ansicht.
Daher klinke ich mich mal hier ein :)
