### ISSUE TITLE
Feature Request: Black Mode

### ISSUE THREAD

**Issue by bmueller77** [Zefau/ioBroker.jarvis#1625]
Hallo, wäre es möglich, einen Black Mode zusätzlich zu integrieren? Ich habe erst kürzlich bei meiner Smarthome-Zentrale auf OLED umgestellt und für einen solchen Fall wäre ein Black Mode perfekt.

**Comment by mcuiobroker** [comment]
?
![image](https://user-images.githubusercontent.com/84818934/154812731-ffc44df9-cd04-4232-a59b-3ee47a411b74.png)
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/styles/metallisches-design
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/system-effektprog./v3-effektprogramme/cssthemes

**Comment by Zefau** [comment]
@bmueller77 Dark Mode existiert bereits. Kann der Feature Request geschlossen werden?

**Comment by mcuiobroker** [comment]
Es wäre sinnvoll die Farbeinstellungen zum Dark-Mode einstellbar zu gestalten, da jeder unter Dark-Mode aufgrund der Bildschirm-Varianten evtl. andere Farben benötigt bzw einstellen möchte. (tiefschwarz, gräulich, usw.)
