### ISSUE TITLE
Es ist aktuell nicht möglich "on" / "off" in den Datenpunkt zu schreiben.

### ISSUE THREAD

**Issue by kolbenhans** [Zefau/ioBroker.jarvis#1626]
**Prerequisites / Voraussetzungen**
- [Jarvis - version 3.0.11 ] 
Fehler: (Bei Anbindung Shelly über MQTT)
Es ist aktuell nicht möglich `on` / `off` in den Datenpunkt zu schreiben. (benötigt von Shelly)

Beschreibung:
Über die Konfiguration: `{"on":"on","off":"off"}` wird zwar `on` geschrieben, für `off` kommt aber `true`

folgendes habe ich ebenfalls -ohne Erfolg- getestet:
`{"true":"on","false":"off"}`
`{"on":"true","off":"false"}`
`{"setOn":"on","setOff":"off"}`

**Comment by Zefau** [comment]
Auf welche Komponente beziehst du dich? `SwitchAction`?

**Comment by Bernd9000** [comment]
@kolbenhans
Was mit der `v3.0.11` und `SwitchAction` noch geht ist `{"on":"On","off":"Off"}` und dann umwandeln per script in on/off
Oder `{"on":"Ein","off":"Aus"}` ist auch eine Möglichkeit

![1](https://user-images.githubusercontent.com/77005685/154850140-3cbf54c5-d041-42e8-b496-43000a5726a9.gif)

**Comment by kolbenhans** [comment]
> Auf welche Komponente beziehst du dich? `SwitchAction`?

Ja die Datenpunkt Eigenschaften für die Switch Action.


@Bernd9000 
Ja da hast du recht, und ich habe es aktuell auch über ein script gelöst, aber dennoch wollte ich das Ticket erstellen für den Fall das es noch ein bug ist.

Ich habe nun übrigens einen Trick gefunden :) zusätzliche Leerzeichen am ende der Wörter funktionieren für mich.
{"on":"on ","off":"off "}

**Comment by Bernd9000** [comment]
Stimmt, hast recht, die shellys reagieren auch wenn ein Leerzeichen am Ende steht. :-)

**Comment by Zefau** [comment]
Also `off` wird nicht geschickt, aber alle anderen Werte? Seltsam

**Comment by kolbenhans** [comment]
Ja genau, on und dann true statt off.

**Comment by dma7** [comment]
@kolbenhans 

Ich versuche gerade, genau das zu erreichen, was du oben beschreibst: ein Shelly Plug S welches über MQTT an ioBroker angebunden ist aus Jarvis heraus schaltbar zu machen. 

Dein Trick mit den Leerzeichen klang für mich, als ob du das hingekriegt hast. Leider funktioniert das bei mir nicht. 

Die Gerätedefinition schaut bei mir so aus:

![grafik](https://user-images.githubusercontent.com/12501460/160494966-bfabbf34-20fa-4b9e-9bc8-37ca03056e41.png)

Was mache ich falsch?

**Comment by kolbenhans** [comment]
@dma7
Ja genau so hatte ich es gemacht und es hatte funktioniert.

Mittlerweile habe ich mir aber den shelly Adapter von Matthias installiert, damit kann ich es einfach mit einem true/false schalten.

Gruß K.

**Comment by dma7** [comment]
@kolbenhans 

Danke fürs Feedback. 

Mir war die Lebenszeit zu schade, nach einem funktionierenden Workaround zu suchen, bzw. rauszufinden, warum der obige nicht geht.
So habe ein generisches Skript für meine knapp 10 Shellies entwickelt und das funzt auch sehr gut.

Grüße
dma

**Comment by pehon** [comment]
Habe das gleiche Problem. Mal kommt true, mal geht nur ON und OFF nicht, mal geht beides.

@kolbenhans Wie hast du das mit einem Script gelöst, hast du ein Beispiel?

Gruss,
Peter

**Comment by pehon** [comment]
> Mir war die Lebenszeit zu schade, nach einem funktionierenden Workaround zu suchen, bzw. rauszufinden, warum der obige nicht geht. So habe ein generisches Skript für meine knapp 10 Shellies entwickelt und das funzt auch sehr gut.

Habe das gleiche Problem. Mal kommt true, mal geht nur ON und OFF nicht, mal geht beides.

@dma7 Wie hast du das mit einem Script gelöst, hast du ein Beispiel?

Gruss,
Peter

**Comment by dma7** [comment]
@pehon 

Hier ist mein Skript.

In dem map Array musst du alle zu konvertierenden Shellies eintragen. Und du musst manuell pro Shelly einen virtuellen Datenpunkt erzeugen (könnte man auch im Skript automatisch machen.

`var mqtt = 'mqtt.0';

const map = [
    {virt: "0_userdata.0.Switch.Shelly.AAA", phys: "mqtt.0.shellies.AAA.relay.0",  mqttCmd: "shellies/AAA/relay/0/command"},
    {virt: "0_userdata.0.Switch.Shelly.BBB",   phys: "mqtt.0.shellies.BBB.relay.0",    mqttCmd: "shellies/BBBr/relay/0/command"},
    {virt: "0_userdata.0.Switch.Shelly.server",         phys: "mqtt.0.shellies.shelly-srv.relay.0",             mqttCmd: "shellies/shelly-srv/relay/0/command"},
];

initStates();

var virtualShellySwitches = [];
var physicalShellySwitches = [];

// build subscription arrays
map.forEach(dev => { 
    virtualShellySwitches.push(dev.virt);
    physicalShellySwitches.push(dev.phys);
});

// Subscribe all VIRTUAL switches
// Triggered by VISUALIZATION
on({id: virtualShellySwitches, change: "ne", ack: false}, function (obj) {
    var dev = map.find(o => o.virt === obj.id);
    var value = obj.state.val;
    var mqttCmd = dev.mqttCmd;
//    console.log("VIRT2PHYS: " + mqttCmd + " set to " + (value? "on" : "off"));
    sendTo(mqtt, 'sendMessage2Client', {topic: mqttCmd, message: (value? "on" : "off")});    
});

// Subscribe all PHYSICAL switches
// Triggered by manual switching
on({id: physicalShellySwitches, change: "ne", ack: true}, function (obj) {
    var dev = map.find(o => o.phys === obj.id);
    var mappedDevice = dev.virt;
    var valueToSet = obj.state.val === "on"? true : false;
//    console.log("PHYS2VIRT: " + mappedDevice + " setting to " + valueToSet);
    setState(mappedDevice, valueToSet);
});

// Iter all physical devices, retrieve current state and set virtual switch appropriately
function initStates() {
    map.forEach(dev => {
        var state = getState(dev.phys).val;
        var shellyState = state === "on"? true : false;
        setState(dev.virt, shellyState);
    });
};
`

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.24`
