### ISSUE TITLE
Bug oder Feature? Dynamisches ICON wird für alle gleich angezeigt, im Popup für jedes richtig

### ISSUE THREAD

**Issue by gitpower2017** [Zefau/ioBroker.jarvis#1629]
Version 3.0.11

Hallo Service Team.

Ich habe 6 Rollos mit Dynamischen Icons.
![Rollo1](https://user-images.githubusercontent.com/30797648/155088291-a21c52c7-2ae4-425d-abe2-d5967725e443.png)

In der Ansicht sieht man, das im Hauptbild alles vom BAD abhängt. Im Popup alles richtig angezeigt wird.
![Rollo2](https://user-images.githubusercontent.com/30797648/155088881-9bec90aa-fab6-4027-9e4c-4559a5e6ce67.png)

**Comment by Zefau** [comment]
Ist ein Bug. Ist das Verhalten direkt nach F5 so oder erst nach einiger Zeit?

Kannst du bitte das Layout dazu posten?

**Comment by gitpower2017** [comment]
kann das erst nach Ostern.
vielleicht erinnert mich jemand

17.04.2022 11:58:41 Zefau ***@***.***>:

**Comment by Zefau** [comment]
@gitpower2017
