### ISSUE TITLE
app.hash.json kann nicht geladen werden

### ISSUE THREAD

**Issue by azmodan2k** [Zefau/ioBroker.jarvis#1633]
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
v3.0.11

- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]
bei dem versuch die app.hash.json zu laden wird durch den substring eine falsche url zusammen gebaut
`const n = window.location.href.substr(0, window.location.href.indexOf("/jarvis") + 7);`
führt bei einem FQDN von z.B. http://jarvis.my.domain/jarvis zu folgender url --> http://jarvis/js/app.hash.json

wenn du den indexOf entsprechend anpasst, dann bleiben custom FQDN davon unberührt und der benutzer ist nicht gezwungen seine URL zu ändern

`const n = window.location.href.substr(0, window.location.href.indexOf("/jarvis/") + 7);`

**Comment by Zefau** [comment]
mit `v3.0.12-beta.3` behoben

**Comment by Zefau** [comment]
@azmodan2k passt das mit beta-3?

**Comment by azmodan2k** [comment]
@Zefau sorry für die verspätete rückmeldung, ja das passt so 👌 ... danke und grüße stefan
