### ISSUE TITLE
Switch has different color on mobile

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1635]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

v3.0.11

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Switch has different color on mobile. On mobile very bad to see the switch with dark theme. Shall be white (the same) like on PC and Tablet.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

PC/Tablet (As expected)
![image](https://user-images.githubusercontent.com/79741077/155812200-8ffed3d2-f535-4d18-96d1-1d2e8b5725c6.png)

Mobile (Wrong)
![Screenshot_20220225-233120](https://user-images.githubusercontent.com/79741077/155812274-2a2d5a20-55ed-4f1b-958b-91d6ba1b1669.jpg)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
@Zefau : Moin! Weißt Du schon mit welcher Version ein Fix kommen wird? Viele Grüße!

**Comment by Zefau** [comment]
Ne. Wüsste nicht mal woran das liegt. Hast mal alle Styles gelöscht?

**Comment by RkcCorian** [comment]
Ja, hab gerade mal alle Styles gelöscht. Gleiches Verhalten. Ich nutze das Dark Theme.

**Comment by RkcCorian** [comment]
@Zefau : Moin! Hab gerade den Grund gefunden... auf dem Handy nutze ich den FullyBrowser. Standardmäßig übernimmt er die DarkMode Einstellung vom Handy. Wenn ich Fully derart konfiguriere, dass der DarkMode des Handys zwangsweise ausgeschaltet wird, sind die Switches auch weiß, wie erwartet. Ich bin mir nicht sicher, ob Du da was machen kannst. Aktuell passt es für mich, so wie es ist. Wie siehst Du es?

**Comment by RkcCorian** [comment]
@Zefau : Hi Zefau, sollen wir schließen?! Viele Grüße!

**Comment by RkcCorian** [comment]
@Zefau : Ich schließe mal...
