### ISSUE TITLE
Datenpunkt Anzeige der Aktualisierung 

### ISSUE THREAD

**Issue by darkdevil373** [Zefau/ioBroker.jarvis#1636]
Hallo, mir ist aufgefallen, dass sich die Zeit der datenpunkte nicht „nach oben“ ändert. Soll heißen: 
Ich lasse mir Temperaturen ich einem eigenen tab anzeigen, nach einiger Zeit (wenn sich die Temperaturen ändern) steht bei allen datenpunkten „vor weniger als 10 Sekunden“. Aktualisiere ich die Seite dann, werde korrekte Zeiten (zb vor 27 Minuten) angezeigt. 

Ich verwende jarvis in Version v3.0.11

**Comment by Zefau** [comment]
Kannst du mal bitte mit `v3.1.0-alpha.31` prüfen, ob das behoben ist?
