### ISSUE TITLE
Navigation im Kalender Widget funktioniert auf dem Tablet nicht

### ISSUE THREAD

**Issue by weidlix** [Zefau/ioBroker.jarvis#1637]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] 3.0.11
- [ ] Im Kalender Widget kann man ja in den Monaten navigieren und aud Tage klicken. Das funktioniert auch im Chrome Browser auf meinem Laptop. Auf meinem Tablet funktioniert die Navigation leider nicht. Ich benutze da Fully und hatte vis Version 2.5 nie Probleme

**Comment by Zefau** [comment]
@weidlix sorry, das Issue ist mir untergegangen. Funktioniert es in v3.1?

**Comment by Zefau** [comment]
@weidlix
