### ISSUE TITLE
Icon Reihenfolge wird nicht eingehalten

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1638]
Icon im DP:
![image](https://user-images.githubusercontent.com/84818934/156276215-b8ecc378-0b9a-4959-8946-c8a890ca63be.png)
Icon im Device:
![image](https://user-images.githubusercontent.com/84818934/156276280-322ca180-9238-4ac2-868d-a233a4d3b9a9.png)
Wenn der Wert der Zeit >0 ist soll das Icon blinken, ist der Wert =0 soll nur das Icon aus dem Device angezeigt werden.

![image](https://user-images.githubusercontent.com/84818934/156276449-af5874d1-8be6-45d6-9844-a887102ddc57.png)

Es wird aber das Standard-Icon angezeigt, welches eigentlich nur dann angezeigt werden soll, wenn sonst keins definiert wurde?.
Auch nach F5 keine Besserung oder Änderung.

**Comment by mcuiobroker** [comment]
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2356

**Comment by Zefau** [comment]
bitte mit `v3.1.0-alpha.33` prüfen

**Comment by mcuiobroker** [comment]
Passt. Danke.
