### ISSUE TITLE
Geräte-Popup mit zusätzlicher Klasse für das Device .jarvis-device-DeviceId

### ISSUE THREAD

**Issue by TheBermud** [Zefau/ioBroker.jarvis#1639]
Hallo,

ich würde mir in den Pop Ups eine zusätzliche Klasse für das Device .jarvis-device-DeviceId wünschen.

![Unbenannt](https://user-images.githubusercontent.com/59181681/156899780-8ea76517-2890-4b2c-853a-4a9c8860eb94.PNG)

Das Ziel meines Wunsches ist es, in einem Pop den Statewert eines bestimmtes Gerätes durch einen Wert eines anderen Datenpunktes zu ersetzen.
Der Datenpunkt den ich mir anzeigen lassen möchte ist ein String. Er enthält den LastChangeBody von einem anderen Datenpunkt. 

Um verständlicher zu werden bzw. auf meinen Anwendungsfall einzugehen:
Ich schalte mit einem Datenpunkt meinen Bewegungsmelder "scharf". Ich möchte dort anstatt "an" oder "aus" anzeigen lassen, wann der Bewegungsmelder das letzte mal eine Bewegung erkannt hat. 

Nach Rücksprache mit MCU bräuchte ich dafür die besagte Klasse um das ganze auf bestimmte Datenpunkte begrenzen zu können.

Alternativ könnte ich mir auch vorstellen, dass eine Möglichkeit eingefügt wird, den LastChangeBody mit einem Binding auf einen anderen Datenpunkt zu beziehen.

**Comment by Zefau** [comment]
CSS-Klasse mit `v3.1.0-alpha.9` hinzugefügt

**Comment by mcuiobroker** [comment]
Wenn möglich bitte hinter jarvis-popup Selektor setzen, da Umrahmungen bei jarvis-popup-container nicht ziehen
```
.jarvis-popup-container {
	border: 1px solid white;
}
```

![image](https://user-images.githubusercontent.com/84818934/174495001-75e0ac42-d6d6-4d9c-9c87-82067597d134.png)
