### ISSUE TITLE
HMIP (access point) adapter: float instead of integer

### ISSUE THREAD

**Issue by fajabird** [Zefau/ioBroker.jarvis#164]
I use the iobroker.hmip adapter to directly access devices via the cloud based access point. Unfortunately it seems that some values are reported differently than via e.g. CCU. Here is an example for my HMIP-BROLL shutters:

hmip.0.devices.XXX.channels.1.shutterLevel state is a value from 0 to 1 (e.g. 0.78 = 78%) - so the level is not reported in a percent value but as an float. This make in incompatible to the current implementation of shutters in jarvis. Would it be possible to add another "type" of level to jarvis that is using float instead of integers?

**Comment by Zefau** [comment]
@fajabird added with `1.1.0-beta.32`. This is a new option in the Widget config. Could you test this? Thanks

**Comment by fajabird** [comment]
Hi, thanks. I can test in about a week. Currently Im not at home.

**Comment by fajabird** [comment]
Hi - that seems to work, although I noticed a few small bugs:
1. if I set min=1 and max=0 (to reverse logic) the slider is not working anymore - so better prevent entering such values
2. if I leave "number steps" empty it renders jarvis completely broken - nothing is being displayed anymore and I have to reset jarvis
3. if I set min=0, max=1 and leave number steps=11 this results in some rounding issues with some numbers (3 and 6) - those are displayed as: e.g. 6 becomes "6.00000000001".

**Comment by cryptedx** [comment]
![image](https://user-images.githubusercontent.com/20707078/97991598-f3cbd100-1de1-11eb-8068-b4cd20e1167c.png)

![image](https://user-images.githubusercontent.com/20707078/97991635-ffb79300-1de1-11eb-85f6-a4a77c5afae3.png)

**Comment by Zefau** [comment]
@fajabird your remarks should be resolved with `v1.1.0-beta.89`.
 @cryptedx should be resolved with `v1.1.0-beta.89`: `markSteps` are now calculated based on `step`. `min` and `max` are defined in the device from now on, e.g.:

![image](https://user-images.githubusercontent.com/14368811/98598768-3f4b1700-22db-11eb-9d7b-8259ee893714.png)

**Comment by fajabird** [comment]
v1.1.0-beta.90 seem to be very much broken - cannot enter Datapoint (Trigger) at all, after closing the editor and opening it again the field is restored to either empty of some preset from the device-type setting (e.g. "shutters"). So currently I cannot test anything.

**Comment by Zefau** [comment]
> v1.1.0-beta.90 seem to be very much broken - cannot enter Datapoint (Trigger) at all, after closing the editor and opening it again the field is restored to either empty of some preset from the device-type setting (e.g. "shutters"). So currently I cannot test anything.

Is resolved now with `v1.1.0-beta.91`.

> But still rounding issues: I set "step" to "0.1" and min=0 max=1. The levels seem to be fine now - but e.g. changing my shutters to "0.1" with the slider results in something close to 0.099999999 beeing reported afterwards and stored to the object.

Is resolved now with `v1.1.0-beta.92`.

**Comment by Zefau** [comment]
@fajabird @cryptedx Have you guys had the possibility to test everything? Is it working as expected?

**Comment by cryptedx** [comment]
Yes, it's working great since you fixed it! Let's wait for feedback from @fajabird
