### ISSUE TITLE
Nach Reboot alles gelöscht

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1641]
Habe soeben mein proxmox aktualisiert und alles neugestartet. nach dem reboot von iobroker. 
sind nun alle konfigs in jarvis komplett weg. ich hatte das "intro" / tour. auch die ganzen objekte sind leer (css,layout,usw...) 

wie kann das passieren ?

**Comment by ma-gu-16** [comment]
So musst ein Backup einspielen und die anderen Adapter/ApiKeys usw alle neu einrichten. Sehr mühsam. 

Wie so etwas passieren kann ist mir ein Rätsel? Zumal alles andere da war, lediglich die Objekte / Jarvis Daten waren weg.... Kann ein Reboot das verursachen ? 

Ich hatte die aktuellste stable aus dem Repo. 3.0.11  jetzt habe ich die 3.0.12-beta.1

**Comment by ma-gu-16** [comment]
Evtl passiert das bei einem iobroker update. (js-controller, usw.) via ssh.

**Comment by Zefau** [comment]
Sollte natürlich eigentlich nicht passieren. Kann ich mir auch nicht erklären :-/ hast du hier noch was rausgefunden?
