### ISSUE TITLE
Im Popup haben alle Datenpunkte den Label Namen vom Gerät

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1646]
`v3.0.12-beta.2`
Obwohl unterschiedliche Namen in den Gerätedatenpunkten vergeben wurden haben im Popup alle Datenpunkte die Bezeichnung vom Gerät. Hier "Kellerlicht2"
![1](https://user-images.githubusercontent.com/77005685/158497958-fab651ce-d459-464c-872d-f1420e6f0750.jpg)

**Comment by Algieio** [comment]
Bei mir ist das auch so.
Gibt es dafür schon eine Lösung?

Ich habe v3.0.12 beta 3

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.9`

**Comment by Bernd9000** [comment]
Kann ich leider nicht testen da v3.1.0 wegen [#1670](https://github.com/Zefau/ioBroker.jarvis/issues/1670) bei mir nicht läuft.
@Algieio ?

**Comment by Algieio** [comment]
Soweit ich es testen konnte funktioniert das mit 3.1.0 Alpha 9
Aber mir dieser Version wird die Pro-Lizenz nicht erkannt und die Pro-Features nicht freigeschaltet.

**Comment by Zefau** [comment]
Ok danke für den Hinweis
