### ISSUE TITLE
Komische Anzeige für Update von jarvis

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1647]
Es wird nicht die mögliche Version angezeigt?
System ist komplett neu aufgesetzt mit js-controller 4.0.21 und Admin 5.3.1
![image](https://user-images.githubusercontent.com/84818934/158633756-c13621e8-d8f1-4997-83ec-7c22454cba42.png)

**Comment by Zefau** [comment]
Da müsstest du ein Issue beim Admin auf machen.

**Comment by mcuiobroker** [comment]
Ist aber nur bei jarvis so?

**Comment by Apollon77** [comment]
Ja genau liegt am > in den release notes ... ist ein Admin 4 UI issue was auch nicht gehiben wird. Du kannst im GitHub die io-package news "fixen",dann verschwindet es mit dem nächsten Repo update
