### ISSUE TITLE
Button Auswahl 

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#1648]
Jarvis v3.0.11
Seit kurzem funktioniert bei mir die Button Auswahl nirgends mehr
![tracklist](https://user-images.githubusercontent.com/25475385/158637969-d19d01ea-d5d4-4655-b185-124af402ac1e.gif)

**Comment by Zefau** [comment]
Also es kann ja nicht einfach so kaputt gehen ;-) Hast du einen Fehler in der Browser Konsole?

**Comment by duczz** [comment]
Das ist mir durchaus bewusst ^^
Ne nen Fehler gibt er nicht aus

**Comment by mcuiobroker** [comment]
Hast du in letzter Zeit System-Updates gemacht? Web-Adapter , js-controller usw?
Browser-Daten mal gelöscht?

**Comment by duczz** [comment]
Ja, die ganz normalen Updates, javascript etc, alles im stable.
Jup Browser wurde auch bereits gewechselt oder cache gelöscht - kanns gerne live herzeigen

**Comment by Zefau** [comment]
Sonst mal v3.0.12?

**Comment by duczz** [comment]
Hatte ich bereits, bei der ist es mir das erste Mal aufgefallen, dann bin ich wieder zurück, brachte aber nix

**Comment by Bernd9000** [comment]
Anderen Browser mal getestet ? Browser Plugin installiert ?

**Comment by Bernd9000** [comment]
Irgendein Browser Plugin neu installiert ?

**Comment by Bernd9000** [comment]
Ich hab das nur wenn ich oben den Text bei Gewerk lösche, dann kommt bei mir auch kein DropDown Menü mehr.

**Comment by duczz** [comment]
@Bernd9000 du hast recht, es betrifft alle Geräte in Gewerken die selbst angelegt wurden. - Danke
@Zefau kannst du das wieder korrigieren?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/188

**Comment by Zefau** [comment]
@duczz sollte mit v3.1 inzwischen korrigiert sein?
