### ISSUE TITLE
State-Explorer zeigt mehrere Werte als ausgewählt an

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1649]
`v3.0.11`
Es wird nicht nur ein State als ausgewählt angezeigt
![image](https://user-images.githubusercontent.com/84818934/158860663-f7136ad2-4dc6-42cc-9d97-0a9fe5dda71a.png)

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.9`

**Comment by mcuiobroker** [comment]
`v31.0-alpha.52 und vorher`
![image](https://user-images.githubusercontent.com/84818934/193368489-438bfc2b-01df-44ee-95e1-913fc2f25289.png)

Passt. Danke.
