### ISSUE TITLE
Map Anzeigepunkt wird nicht aktualisiert 

### ISSUE THREAD

**Issue by Chris25122** [Zefau/ioBroker.jarvis#1653]
Hallo,

ich habe das Problem, dass das Icon auf der Map nicht aktualisiert wird wenn sich die Koordinaten ändern, es sei denn ich drücke F5.
Bei Jarvis V2 ist der Map Punkt mit gesprungen sobald sich die Werte / Koordinaten geändert haben.
Für die Koordinaten nutze ich den life360 Adapter.

Ich habe gestern auf die Beta Version v3.0.12-beta.3 geupdated in der Hoffnung das Problem damit zu beheben, es ist allerdings immer noch vorhanden.

![image](https://user-images.githubusercontent.com/48753907/159665147-3b78d028-0256-415a-ba72-be7dba8a2cb4.png)

**Comment by Chris25122** [comment]
@Zefau gibt es dazu Neuigkeiten ?

**Comment by Zefau** [comment]
@Chris25122 kannst du mal mit `v3.1.0-alpha.20` schauen?

**Comment by Chris25122** [comment]
> @Chris25122 kannst du mal mit `v3.1.0-alpha.20` schauen?

Funktioniert jetzt, danke !
