### ISSUE TITLE
Graph from JSONTable

### ISSUE THREAD

**Issue by MubiTec** [Zefau/ioBroker.jarvis#1654]
Hi,

maybe I didn't found it, but I would like to draw a graph out of an jsonTable e.g. from "pvforecast" adapter. There are 2 datapoints available:

pvforecast.0.PV_Haupt.JSONGraph:
`
{"graphs":[{"data":[{"t":"2022-03-24 06:10:00","y":0},{"t":"2022-03-24 06:35:00","y":78},{"t":"2022-03-24 07:00:00","y":380},{"t":"2022-03-24 08:00:00","y":924},{"t":"2022-03-24 09:00:00","y":1869},{"t":"2022-03-24 10:00:00","y":2846},{"t":"2022-03-24 11:00:00","y":3606},{"t":"2022-03-24 12:00:00","y":4117},{"t":"2022-03-24 13:00:00","y":4291},{"t":"2022-03-24 14:00:00","y":4192},{"t":"2022-03-24 15:00:00","y":3723},{"t":"2022-03-24 16:00:00","y":2944},{"t":"2022-03-24 17:00:00","y":1904},{"t":"2022-03-24 18:00:00","y":870},{"t":"2022-03-24 18:26:00","y":174},{"t":"2022-03-24 18:52:00","y":0},{"t":"2022-03-25 06:08:00","y":0},{"t":"2022-03-25 06:34:00","y":73},{"t":"2022-03-25 07:00:00","y":356},{"t":"2022-03-25 08:00:00","y":834},{"t":"2022-03-25 09:00:00","y":1616},{"t":"2022-03-25 10:00:00","y":2435},{"t":"2022-03-25 11:00:00","y":3217},{"t":"2022-03-25 12:00:00","y":3842},{"t":"2022-03-25 13:00:00","y":4158},{"t":"2022-03-25 14:00:00","y":4185},{"t":"2022-03-25 15:00:00","y":3798},{"t":"2022-03-25 16:00:00","y":3049},{"t":"2022-03-25 17:00:00","y":1933},{"t":"2022-03-25 18:00:00","y":867},{"t":"2022-03-25 18:27:00","y":174},{"t":"2022-03-25 18:54:00","y":0}],"tooltip_AppendText":" Watt","legendText":"PV_Haupt","yAxis_id":0,"type":"bar","displayOrder":0,"barIsStacked":true,"color":"#000000","barStackId":1,"datalabel_color":"#000000","datalabel_fontSize":10}]}
`
pvforecast.0.PV_Haupt.JSONTable:
`
[{"Uhrzeit":"2022-03-24 06:10:00","Leistung":0},{"Uhrzeit":"2022-03-24 06:35:00","Leistung":78},{"Uhrzeit":"2022-03-24 07:00:00","Leistung":380},{"Uhrzeit":"2022-03-24 08:00:00","Leistung":924},{"Uhrzeit":"2022-03-24 09:00:00","Leistung":1869},{"Uhrzeit":"2022-03-24 10:00:00","Leistung":2846},{"Uhrzeit":"2022-03-24 11:00:00","Leistung":3606},{"Uhrzeit":"2022-03-24 12:00:00","Leistung":4117},{"Uhrzeit":"2022-03-24 13:00:00","Leistung":4291},{"Uhrzeit":"2022-03-24 14:00:00","Leistung":4192},{"Uhrzeit":"2022-03-24 15:00:00","Leistung":3723},{"Uhrzeit":"2022-03-24 16:00:00","Leistung":2944},{"Uhrzeit":"2022-03-24 17:00:00","Leistung":1904},{"Uhrzeit":"2022-03-24 18:00:00","Leistung":870},{"Uhrzeit":"2022-03-24 18:26:00","Leistung":174},{"Uhrzeit":"2022-03-24 18:52:00","Leistung":0},{"Uhrzeit":"2022-03-25 06:08:00","Leistung":0},{"Uhrzeit":"2022-03-25 06:34:00","Leistung":73},{"Uhrzeit":"2022-03-25 07:00:00","Leistung":356},{"Uhrzeit":"2022-03-25 08:00:00","Leistung":834},{"Uhrzeit":"2022-03-25 09:00:00","Leistung":1616},{"Uhrzeit":"2022-03-25 10:00:00","Leistung":2435},{"Uhrzeit":"2022-03-25 11:00:00","Leistung":3217},{"Uhrzeit":"2022-03-25 12:00:00","Leistung":3842},{"Uhrzeit":"2022-03-25 13:00:00","Leistung":4158},{"Uhrzeit":"2022-03-25 14:00:00","Leistung":4185},{"Uhrzeit":"2022-03-25 15:00:00","Leistung":3798},{"Uhrzeit":"2022-03-25 16:00:00","Leistung":3049},{"Uhrzeit":"2022-03-25 17:00:00","Leistung":1933},{"Uhrzeit":"2022-03-25 18:00:00","Leistung":867},{"Uhrzeit":"2022-03-25 18:27:00","Leistung":174},{"Uhrzeit":"2022-03-25 18:54:00","Leistung":0}]
`

If you need more info please let me know.

Thanks in advance!

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1410
