### ISSUE TITLE
Refactor and Performance Improvements

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1655]
- [x] Upgrade Core Dependencies, see https://github.com/Zefau/ioBroker.jarvis/issues/1214
- [x] Migrate from Webpack to Vite
- [X] Migrate from Vuex to Pinia
- [x] Refactor State & Binding processing
- [ ] Move from Vue Options API to Composition API
  - **Components**
    - [ ] ...
  - **Functions**
    - [ ] ButtonAction / IconButtonAction
    - [x] ButtonGroupAction
    - [ ] CheckboxAction / SwitchAction
    - [ ] CustomTextBody
    - [x] DatePickerAction
    - [x] DatePickerBody
    - [ ] DropdownAction
    - [ ] IconState
    - [ ] InputAction
    - [ ] LastChangeBody
    - [ ] LevelBody
    - [x] SecondaryStates
    - [x] State
    - [x] TimePickerAction
    - [x] TimePickerBody
    - [ ] Title
    - [ ] BlindLevelAction
    - [ ] ...
  - **Modules**
    - [x] AdapterLogs
    - [x] AdapterStatus
    - [x] Calendar
    - [ ] Chart
    - [x] DateTime
    - [ ] DisplayImage
    - [x] HistoryGraph
    - [x] HomeKitTile
    - [x] HtmlTable / JsonTable
    - [ ] iFrame
    - [x] Map
    - [x] MediaControl
    - [x] ScriptStatus
    - [x] StateHtml
    - [x] StateList
    - [x] Weather
  - **Pages**
    - [ ] Main
    - [x] Drawer / Sidebar
    - [x] Tabs
    - [x] Notifications
    - [x] Device Popup
    - [x] Page
    - [x] Tab
    - [x] Widget
    - [x] Login
  - **Configuration**
    - [x] AccountPage
    - [ ] DevicesPage
      - [x] DevicesPage
      - [x] DevicePage
      - [ ] ImportDevices
    - [x] HelpPage
    - [x] LayoutsPage
    - [x] SettingsPage
    - [x] StylesPage
    - [x] WidgetsPage

**Comment by Zefau** [comment]
CSS 3 wird bereits unterstützt.

**Comment by mcuiobroker** [comment]
Sorry, hatte mich vertan, meinte SCSS/SASS?

**Comment by Zefau** [comment]
Nicht geplant. Wofür brauchst du das?

**Comment by mcuiobroker** [comment]
Brauche ich nicht direkt. Ich stöbere nur immer einige Beispiel-Seiten z.B. Buttons : https://webdeasy.de/top-css-buttons/ und dort sieht man immer wieder statt CSS (SCSS) als CodeTab. Vielleicht funktionieren ja auch einige in CSS, mal schauen. 
Wollte nur die Info, um solche Beispiele dann auch schon zu speichern und evtl dann umsetzen, um mit dem Design flexibler zu werden.
![image](https://user-images.githubusercontent.com/84818934/163425083-e4b90e11-a7d4-4a42-a3ef-fb1590dc7ac0.png)
