### ISSUE TITLE
Tageswechsel im Kalender Widget funktioniert nicht (v3.0.11)

### ISSUE THREAD

**Issue by Andr3asB** [Zefau/ioBroker.jarvis#1656]
Läuft das Dashboard über Mitternacht hinaus, dann wird zwar das Datum/Uhr Widget aktualisiert, aber der Kalender bleibt auf dem alten Tag hängen und aktualsisiert sich nicht.

Browser: Chromium auf RPi.

![chrome_uw9Zs1HOs2](https://user-images.githubusercontent.com/44557554/160238761-9df0b3f9-da6b-4171-a6e2-9c0c72d11714.jpg)

**Comment by Andr3asB** [comment]
Ich sehe gerade, dass es ggf. ein Duplicate zu [#1574](https://github.com/Zefau/ioBroker.jarvis/issues/1574) sein könnte.

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.4`
