### ISSUE TITLE
Jarvis Verbunden mit Host 

### ISSUE THREAD

**Issue by mitsche72** [Zefau/ioBroker.jarvis#1657]
Hallo,
ich habe Jarvis 3.0.11 installiert.
Nach der installaytion des Adapters verbindet sich Jarvis nicht mit dem Host.
Ich habe im Anhan einen Screenshot angefügt, hoffe ich habe alles informationen drin und du kannst mir weiter helfen.

Grüße

Michael

**Comment by Zefau** [comment]
Da fehlt der Screenshot. Nutzt du ggf. https und hast das selbst signierte Zertifikat auf dem Port nicht angenommen?

**Comment by mitsche72** [comment]
![Jarvis](https://user-images.githubusercontent.com/5873292/160295153-618d69c0-efd5-4e62-b8e5-139ca92a00b7.jpg)
![Jarvis2](https://user-images.githubusercontent.com/5873292/160295210-ea24c75c-8d68-423c-8682-0d7c608cdc8c.jpg)


Wow, du hast aber schnell geantowrtet. 
Ich kenne mich hier noch nicht so gut aus, ich hoffe das mit den Screenshots hat jetzt geklappt.
Der Fehler ist schon gleich in den Instanzen.
Ich hoffe du kannst mir weiter helfen.

HG

Michael

**Comment by Zefau** [comment]
Was sagt das ioBroker Log? Scheinbar ist der Adapter abgestürzt.

**Comment by mitsche72** [comment]
![Jarvis3](https://user-images.githubusercontent.com/5873292/160296261-9f9c3f99-a148-4fd9-94fc-b853087950ed.jpg)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/160296511-bde36317-30c9-45b1-a6cb-63d709e3d946.png)

**Comment by mitsche72** [comment]
vieln dank, es läuft
