### ISSUE TITLE
backitup-Sicherung anpassen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1658]
Zurzeit werden in der Extra-Sicherung für jarvis nur die Sicherungsdaten von jarvis gesichert, nicht die DPs. 
![image](https://user-images.githubusercontent.com/84818934/160432199-8856278f-b016-47cc-a50c-42f01b443fb3.png)

Bitte die DPs mit integrieren, damit man leichter an die Jarvis-Daten kommt. Sonst muss man die jarvis Daten immer aus einer riesigen backup.json holen, diese kann >100MB sein.

**Comment by Zefau** [comment]
Bitte FR beim Backitup Adapter öffnen. Ich programmiere dort nicht mit.

**Comment by mcuiobroker** [comment]
Kann ich machen, ist aber nicht besser, wenn es von Dir kommt?

**Comment by mcuiobroker** [comment]
https://github.com/simatec/ioBroker.backitup/issues/655
