### ISSUE TITLE
Backup settings im Protokoll

### ISSUE THREAD

**Issue by Merexor** [Zefau/ioBroker.jarvis#1659]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] v3.0.11
- [ ] ![Protokoll](https://user-images.githubusercontent.com/68726324/161136746-f4869a75-dd93-4bb4-9b62-8ad77194b9f6.png)

**Describe the bug / Beschreibe den Fehler**
Ich weiß nicht genau ob es ein "Fehler" ist. Im Protokoll werden alle 5 Sekunden ein Log von Jarvis gemacht wie oben im Screenshot. Ist das normal ? Nachdem ich nichts dazu sonst gefunden habe dachte ich, ich frag mal nach.

**Comment by mcuiobroker** [comment]
Setzt du evtl den `DarkMode` mit einem Script? Und das Script prüft alle 5 Sekunden?
`jarvis.0.settings.themeDarkMode`

**Comment by Merexor** [comment]
@mcuiobroker Ja genau das mache ich!
Das werde ich ändern.. wusste nicht das ich das dadurch einen Log-Eintrag auslöse. Aber vielleicht hilft der Eintrag ja dem nächsten.
