### ISSUE TITLE
Passwortgeschützter Bereich

### ISSUE THREAD

**Issue by Trrw** [Zefau/ioBroker.jarvis#1660]
Hallo,

schön wäre eine Einstellung mit der man eine Seite (in der Seitenleiste) mit einem Passwort versehen könnte. Dahinter könnten Schalter und Widgets platziert werden, die für die "normalen" Bewohner nicht zugänglich sein sollen zum rumspielen.

Danke :)

**Comment by Zefau** [comment]
Duplikat https://github.com/Zefau/ioBroker.jarvis/issues/965
