### ISSUE TITLE
Nur eine Seitenleiste/Menüpunkt trotz Premiumabo

### ISSUE THREAD

**Issue by florian84z** [Zefau/ioBroker.jarvis#1661]
![error](https://user-images.githubusercontent.com/23108104/161305788-31364be1-75ba-4d29-8680-000721409031.JPG)
(v3.0.11)

Leider bekomme ich nur eine Seitenleiste, bzw Menüpunkt eingebaut trotz Pro-Account

Neustarten des Adapters hat nichts gebracht.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/allgemein/pro-account#es-wird-kein-pro-account-angezeigt-obwohl-ihr-eine-rechnung-bekommen-habt
Inhalt von info.txt in den DP kopieren `jarvis.0.info.pro`

**Comment by Zefau** [comment]
@florian84z hast du das lösen können?
