### ISSUE TITLE
Bearbeiten von History Graphen und Swipen zwischen Tabs kommt sich in die Quere

### ISSUE THREAD

**Issue by Pongard** [Zefau/ioBroker.jarvis#1662]
Wenn man am History Graphen rumbastelt (verschieben von Bereichen) swiped man laufend versehentlich vor und zurück. Da hätte ich lieber dass swipen zwischen tabs nur on top möglich ist, oder über Buttons gelöst ist. So kann man auf den History Graphen gar nicht ordentlich navigieren, da jede zweite Aktion einen auf einen anderen Tab befördert.

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.22` behoben sein
