### ISSUE TITLE
Clock not refreshing

### ISSUE THREAD

**Issue by SKB-CGN** [Zefau/ioBroker.jarvis#1663]
Hi,
when leaving the dashboard open, with stable connection and all things, all states are refreshed - except the clock.

Have a look here:
![2022-04-03 15_06_53-jarvis - just another remarkable vis](https://user-images.githubusercontent.com/58603329/161429619-d4792280-b0a9-4c3d-b1ea-ca50ed81791c.png)
![2022-04-03 15_07_15-](https://user-images.githubusercontent.com/58603329/161429621-4b4cf7de-bca3-47c0-964f-daa33b64acd6.png)

**Comment by Zefau** [comment]
Do you have any errors / warnings in the browser console (via F12) ?

**Comment by SKB-CGN** [comment]
No,
There are no errors. 
Even in Fully Kiosk there is no clock refreshing.
Should the clock refresh?

**Comment by Zefau** [comment]
Everything should be up-to-date and refreshing itself without refreshing the page

**Comment by SKB-CGN** [comment]
Ok, on my side, the clock is not refreshing on Chrome on the Laptop, on Fully Kiosk on Android and directly in Chrome on Android.

**Comment by pphlwmarcel** [comment]
@SKB-CGN I had the same issue but it was resolved by just disabling all
Options in DateTime module (Sunrise/sunset and location) could that be a solution for you issue?

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.22` behoben sein
