### ISSUE TITLE
JARVIS-Page öffnet sich nicht mit Firefox 99.0

### ISSUE THREAD

**Issue by Harry423** [Zefau/ioBroker.jarvis#1664]
Hallo,

nach dem Update von Firefox auf die neue Version 99.0  (Mac) startet die Homepage nicht mehr:

<img width="705" alt="Screenshot 07 04 2022 um 20 33 14 PM" src="https://user-images.githubusercontent.com/73777886/162273734-10a5ab25-d3f8-46a1-8ced-40d8d4d5f682.png">

Ich habe sowohl die Jarvis-Instanz als auch den ganzen IOBroker-Server neu zu starten - ohne Erfolg.
Wenn ich die Seite mit Safari öffne, startet sie ohne Probleme.
Die Schutzmaßnahmen von Firefox habe ich für die Webseite alle deaktivert:

<img width="403" alt="Screenshot 07 04 2022 um 20 41 26 PM" src="https://user-images.githubusercontent.com/73777886/162274214-85f1af86-711a-43b8-98a1-dcd57c49ba67.png">

Leider ohne Erfolg...

Ach so das Zertifikat hat IOBroker ausgestellt, da ich die Seite nicht online habe, kann ich LetsEncrypt nicht nutzen...

**Comment by Zefau** [comment]
Hast du die URL mit dem Port 8400 aufgerufen und das selbst signierte Zertifikat angenommen?

**Comment by Zefau** [comment]
:-)
