### ISSUE TITLE
3.1.0-Alpha.5 Bugs

### ISSUE THREAD

**Issue by Algieio** [Zefau/ioBroker.jarvis#1672]
Version 3.1.0-Alpha.5

- [x] Datenpunkt Stil: Die Eingaben im Datenpunkt Stil greifen nicht mehr.
- [x] Einstellung Breakpoint: Die Spalten werden beim Smartphone nicht verändert.
- [x] Widget Icons: Einige Icons werden nicht mehr angezeigt

**Comment by Zefau** [comment]
>  Datenpunkt Stil: Die Eingaben im Datenpunkt Stil greifen nicht mehr.

Funktioniert bei mir. Kannst du mir mal die konkrete Config posten und den Datenpunkt Wert?

>  Widget Icons: Einige Icons werden nicht mehr angezeigt

Welche fehlen? Sind es nicht Material Design Icons? Also andere Icon Sets?

**Comment by Algieio** [comment]
Datenpunkt Stil: 
ich habe eingestellt, dass alles unter 20°C blau ist und größer 22°C rot. Sonst grün.
<img width="445" alt="Bildschirmfoto 2022-04-19 um 21 29 46" src="https://user-images.githubusercontent.com/96116321/164081078-8887f1a8-43a8-4a75-af13-f909c6319a27.png">

mit 3.0.11:
<img width="476" alt="3 0 11_1" src="https://user-images.githubusercontent.com/96116321/164080731-217f8513-a3b3-4433-9d4e-fb69de4b34f5.png">
<img width="476" alt="3 0 11_2" src="https://user-images.githubusercontent.com/96116321/164082129-672acf05-69c5-460b-b4b7-568d73189629.png">

mit 3.1.0 Alpha 5 (°C in der zweiten Zeile wird auch nicht mehr angezeigt)
<img width="476" alt="3 1 0_1" src="https://user-images.githubusercontent.com/96116321/164080789-a260450b-2630-49f1-9589-0e79b71042dd.png">
 
Hier wird auch angezeigt, dass keine Lampen an sind, obwohl einige eingeschaltet sind:
<img width="465" alt="Bildschirmfoto 2022-04-19 um 21 25 29" src="https://user-images.githubusercontent.com/96116321/164081268-086a1b95-e4a5-4239-b33a-690c3741e6cd.png">
Config:
<img width="814" alt="Bildschirmfoto 2022-04-19 um 21 32 13" src="https://user-images.githubusercontent.com/96116321/164081424-4d91a96e-1748-4d73-9495-486a19b32139.png">
(mit 3.0.11 wird alles richtig angezeigt)

Widgets Icons:
unter anderem folgendes icon wird nicht mehr angezeigt:
<img width="48" alt="3 0 11_3" src="https://user-images.githubusercontent.com/96116321/164081663-e1daab6d-a231-4def-b370-a43309714804.png">
Widget Icon: emojione-monotone:family-man-woman-girl-boy

**Comment by Algieio** [comment]
Ich habe die eingestellte Schriftgrösse hat sich auch verändert. Es ist wieder alles mit kleiner Schrift.

**Comment by Algieio** [comment]
mit Alpha 8 hat sich leider auch nichts geändert.

Das Scrollen auf dem iPhone ist mit 3.1.0 auch sehr schlecht geworden. 

Version 3.0.11 funktioniert bis jetzt am besten.

**Comment by Algieio** [comment]
am IPhone ist das Scrollen auch fast nicht möglich, da keine Reaktion. 

Die Eingaben in Datenpunkt Stil greifen auch nicht. 

![image](https://user-images.githubusercontent.com/96116321/172114298-68bfef7f-869c-4484-9499-e1ccae8fd06f.jpeg)

**Comment by Zefau** [comment]
@Algieio sollte mit `v3.1.0-alpha.19` nun alles passen, kannste das mal prüfen?

**Comment by Algieio** [comment]
leider funktioniert immer noch nicht alles. Hier einige Punkte.
- Das mit den Spritpreisen (Datenpunkt Eigenschaften) funktioniert jetzt.
- Einige Icons werden immer noch nicht angezeigt
- Eingabe in "Datenpunkt Stil" greift nicht
- Eingabe in "Anzeigevariante" greift nicht
- Stateliste kann nicht mehr geschalten werden (ab 3.1.0 alpha 19) Licht schaltet sich nicht mehr ein
- Scrollen auf dem iPhone funktioniert oft nicht. Nur sehr verzögert oder gar nicht.

Seit der Version 3.0.11 hatte ich nur Probleme und wechsle immer wieder zurück auf diese Version.

**Comment by mcuiobroker** [comment]
>Stateliste kann nicht mehr geschalten werden (ab 3.1.0 alpha 19) Licht schaltet sich nicht mehr ein

Hängt dem neuen ACK zusammen, der steht standardmäßig auf  TRUE. Ich musste auch einige umstellen auf FALSE.

>Einige Icons werden immer noch nicht angezeigt

Welche Icons? Iconify ist ja jetzt wieder aktiv.

**Comment by Algieio** [comment]
Ich habe die neue alpha getestet. 
Die Icons werden jetzt angezeigt. 
Die anderen Punkte sind noch offen.

**Comment by Zefau** [comment]
@Algieio sind die Punkte mit der letzten Alpha behoben? Sonst lass uns bitte dedizierte Issues aufmachen, sofern nicht schon geschehen.

**Comment by Algieio** [comment]
Die Punkte sind jetzt behoben. Vielen Dank!
