### ISSUE TITLE
HomeKitTile Jarvis v3.0.12-beta.3 Crash

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#1673]
Sobald ich HomeKitTiles erstelle, crasht die Visualisierung auf den Android Tablets. Am Windows PC kommt keine Fehlermeldung.

Beim Aufruf über ein Tablet sehe ich für einige Sekunden die Visualisierung und danach folgt:

Log (29)
Connecting to http://192.168.178.71:8400/ (#1)...
24,04 2022, 1332 44 | INFO I CONNECTION
Connected to http://192.168.178.71:8400/.
24.04 2022, 13:32 44 L INFO | SOCKET
Received an Update for Settings.
24 04.2022, 13:32 44 | DEBUG I
de-DE
24.04.2022, 13 32 44 L INFO]
de-DE
24.04 2022 13 32-441 INFO:
sing 4dd716ba-ce67-d03a-Ode8-cfbae83bddc4, (object Object]
24 04 2022, 13 32 441 DEBUG I PRO
Valid Pro User: **** ******
24 04 2022 13 32,44
Received an Update for Devices.
24-04-2022
Received an Update for Layout
24.04.202
Received an Update for Styles.
24.04-2022, 13.32
created(,2c9c57cb-d7b1-4e56-ba32-36565ffa8d0f
24.04.2022, 13:32:45 1 DEV CALENDAI
No events for calendar1 (c7d4cb40-eb98-46f8-a745-5e39d36cfc5a, 2022-3) in cache, set events from cached ical data...
24.04 2022, 13 32 45 | DEBUG | CALENDAR-4630560E No events for Abfall (d7de7562-614f-498c-95b6-826f761ac915, 2022-3) in cache, set events from cached ical data..
24.04.2022, 13 32:45 | DEBUG | CALENDAR-463D560E No events for calendar1 (c7d4cb40-eb98-46f8-a745-5e39d36cfc5a, 2022-2) in cache, set events from cached ical data.
24 04.2022, 13:32:45 | DEBUG | CALENDAR-463D560E No events for Abfall (d7de7562-614f-498c-95b6-826f761ac915, 2022-2) in cache, set events from cached ical data...
24.04 2022, 13:32:45 | DEBUG | CALENDAR-463D560E No events for calendar1 (c7d4cb40-eb98-46f8-a745-5e39d36cfc5a, 2022-4) in cache, set events from cached ical data...
24.04.2022, 13:32:45 | DEBUG | CALENDAR-463D560E No events for Abfall (d7de7562-614f-498c-95b6-826f761ac915, 2022-4) in cache, set events from cached ical data...
mounted0,269c57cb-d7b1-4e56-ba32-36565ffa8d0f
Got ical data for Abfall (d7de7562-614f-498c-95b6-826f761ac915) from cache.
Got ical data for calendar1 (c7d4cb40-eb98-46f8-a745-5e39d36cfc5a) from URL.
No events for calendar1 (c7d4cb40-eb98-4618-a745-5e39d36cfc5a, 2022-3) in cache, set events from cached ical data...
No events for Abfall (d7de7562-6141-498c-95b6-8261761ac915, 2022-3) in cache, set events from cached ical data...
No events for calendar1 (c7d4cb40-eb98-46f8-a745-5e39d36cfc5a, 2022-2) in cache, set events from cached ical data...
No events for Abfall (d7de7562-614f-498c-95b6-826f761ac915, 2022-2) in cache, set events from cached ical data....
No events for calendar1 (c7d4cb40-eb98-46f8-a745-5e39d36cfc5a, 2022-4) in cache, set events from cached ical data...
No events for Abfall (d7de7562-614f-498c-95b6-826f761ac915, 2022-4) in cache, set events from cached ical data...
destroy(,2c9c57cb-d7b1-4e56-ba32-36565ffa8d0f
destroyed0), 269C57cb-d7b1-4e56-ba32-36565ffa8d0f
Connection to http://192.168.178.71:8400/ lost!

Das entfernen der HomeKitTiles löst den Crash nicht. Ich musste immer ein Backup einspielen, damit es wieder läuft

**Comment by Zefau** [comment]
Besteht das Problem noch? Welche version hast du im Einsatz?
