### ISSUE TITLE
3.1.0-alpha.5 Anzeigevariante wird kein Wert mehr angezeigt

### ISSUE THREAD

**Issue by Hohenbostler** [Zefau/ioBroker.jarvis#1674]
Hallo nach meinem Update heute auf die 3.1.0-alpha.5 kann ich meine Heizung nicht mehr steuern. Wo genau der Fehler liegt kann ich nicht sagen. Hier nur Bilder zur veranschaulichung.

Das sind die Werte in den Objekten.
![grafik](https://user-images.githubusercontent.com/42488069/165036689-b84792c5-5ac6-408a-869d-7b6add83b790.png)

Hier die Einstellungen in Jarvis.

![grafik](https://user-images.githubusercontent.com/42488069/165036812-a2de891a-f760-41af-a151-14c0c156cc4b.png)

Und hier das was im Jarvis Frontend raus kommt.

![grafik](https://user-images.githubusercontent.com/42488069/165037009-9228c722-54b4-41f9-815c-5019e21a5404.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.9` behoben sein

**Comment by Hohenbostler** [comment]
Hallo. Vorab ich hatte noch keine Zeit an den PC aber auf dem Handy bekomme ich mit der Version direkt Lizenz Probleme. Lizenz ist vorhanden. 

![Screenshot_2022-06-01-06-08-45-686_com android chrome](https://user-images.githubusercontent.com/42488069/171325685-4b9bef09-2dbc-43b5-9acf-cc6b271bea27.jpg)

**Comment by Hohenbostler** [comment]
Anscheinend ist es  nicht möglich das die paypalDaten gespeichert bleiben.

**Comment by Zefau** [comment]
@Hohenbostler schau nochmal mit der aktuellen alpha bitte. Damit sollte die Installation nicht mehr als inkonsistent gemeldet werden.

**Comment by Hohenbostler** [comment]
Hey leider nur vom Handy. Aber Jarvis geht jetzt gar nicht mehr. 
![Screenshot_2022-07-13-22-18-01-665_com android chrome](https://user-images.githubusercontent.com/42488069/178827220-c49523fe-6f2b-418d-aebc-1da5ff2cd361.jpg)

**Comment by Hohenbostler** [comment]
![IMG_20220713_222126](https://user-images.githubusercontent.com/42488069/178827495-f28ce267-466d-4185-8938-ff44dcfd3691.jpg)

**Comment by Zefau** [comment]
Merkwürdig. Hast du Fehler im ioBroker Log? Was passiert, wenn du die URL aus dem Screenshot (mit Port 8400) direkt aufrufst?

**Comment by Hohenbostler** [comment]
Hallo wenn ich direkt den Port Aufrufe kommt die selbe Meldung. 
![Screenshot_2022-07-20-18-44-15-235_com android chrome](https://user-images.githubusercontent.com/42488069/180037642-6d87ce55-2813-4c55-b3e0-8f768fe33eef.jpg)
![Screenshot_2022-07-20-18-45-27-294_com android chrome](https://user-images.githubusercontent.com/42488069/180037768-6ac989e8-d974-41f3-9448-4fe32b8a07e8.jpg)


Error im Log nicht so richtig. Siehe auch screen

**Comment by Zefau** [comment]
Das Problem sollte mittlerweile (`v3.1.0-alpha.31`) behoben sein. Hattest du in jüngster Vergangenheit noch Probleme?
