### ISSUE TITLE
3.1.0-alpha.5 Änderungen können nicht gespeichert werden.

### ISSUE THREAD

**Issue by Hohenbostler** [Zefau/ioBroker.jarvis#1675]
Beim Versuch das Layout zu speichern passiert nichts. Die Konsole wirft diesen Fehler aus .

![grafik](https://user-images.githubusercontent.com/42488069/165090089-b87799fe-f048-4edb-84bd-a6eb19f3d765.png)

**Comment by Zefau** [comment]
Was hast du geändert?

**Comment by Hohenbostler** [comment]
Naja das Update auf die Beta. Aber auch ein downgrade im iobroker lösen das Problem leider nicht

**Comment by Zefau** [comment]
Offtopic: Welche Node.js Version hast du im Einsatz? Ich frage wegen https://github.com/Zefau/ioBroker.jarvis/issues/1670, da du ja die alpha zumindest zum Laufen bekommst.

**Comment by Zefau** [comment]
> Was hast du geändert?

Ich meine, was du konkret in den Einstellungen / im Layout geändert hast in dem Moment, wo du speicherst. Also Geräte, Widget, Layout, Style oder Einstellungen ?

Oder ist es egal, was du änderst und der Fehler kommt immer?

Ich frage, weil bei mir alles flüssig speichert.

**Comment by Hohenbostler** [comment]
Achso sorry. Ich habe über den Trash scheduleadapter neue Datenpunkte eingebaut in JarVIS. Und dann im Layout verschiedene Widgets probiert. Aktuell ist dort noch ein homekitile drin . 

Hier Infos zum system:

Systeminformationen
IoBroker
Plattform
docker
Betriebssystem
linux
Architektur
x64
CPUs
2
Geschwindigkeit
2001 MHz
Modell
Intel(R) Celeron(R) CPU J3355 @ 2.00GHz
RAM
9.58 GB
System-Betriebszeit
9 T. 14:42:15
Node.js
v12.22.11 (Es gibt eine neuere Version: v12.22.12 - Empfohlene Version v14.19.1)
time
1651271172223
timeOffset
-120
Anzahl der Adapter
407
NPM
6.14.16
Datenträgergröße
3.49 TB
freier Festplattenspeicher
2.38 TB
Betriebszeit
9 T. 14:35:50
Aktive Instanzen
27
location
/opt/iobroker/
Hostname
IoBroker

**Comment by Hohenbostler** [comment]
Hallo leider ist mein Problem noch immer nicht gelöst. ich glaube mittlerweile es ist unabhängig von der Version . Bin jetzt wieder auf der v3.0.8 und habe die selben Probleme

Anbei einmal der KOnsolen export
[console-export-2022-6-9_8-33-53.txt](https://github.com/Zefau/ioBroker.jarvis/files/8867528/console-export-2022-6-9_8-33-53.txt)

**Comment by Zefau** [comment]
```
Device with ID 2c861f78-c490-49c8-ae90-22925693ce68 not found!
```

Scheinbar ist das Gerät irgendwo im Layout aber nicht als Gerät definiert. Check auch mal dein Layout auf `null`

**Comment by Hohenbostler** [comment]
Wie mache ich das ?

**Comment by Zefau** [comment]
Im Datenpunkt `jarvis.0.layout` kannst du nach `2c861f78-c490-49c8-ae90-22925693ce68` bzw. `null` suchen.

Respektive dürftest du in `jarvis.0.devices` keinen Eintrag mit `2c861f78-c490-49c8-ae90-22925693ce68` finden.

**Comment by Hohenbostler** [comment]
``Hallo leider finde ich 2c861f78-c490-49c8-ae90-22925693ce68 weder bei Layout  noch bei Devise.

Null finde ich beim Layout auch nicht. Lediglich einmal bei Devices.
`"9a5f3a8f-0e14-47a2-a0ec-4e6de20004c8": {
			"name": "Lea TV",
			"icon": "",
			"label": "",
			"function": "other",
			"states": {
				"aktuellerStatus": {
					"showState": true,
					"state": "sonoff.0.DVES_0430E1.POWER",
					"action": "sonoff.0.DVES_0430E1.POWER",
					"label": "",
					"bodyElement": "LastChangeBody",
					"stateKey": "aktuellerStatus",
					"actionElement": null
				},
				"aktuellerVerbrauch": {
					"showState": true,
					"state": "sonoff.0.DVES_0430E1.ENERGY_Power",
					"unit": "W",
					"label": "",
					"action": "",
					"bodyElement": "LastChangeBody",
					"stateKey": "aktuellerVerbrauch"
				}`

**Comment by Zefau** [comment]
Sorry, ist etwas in Vergessenheit geraten. Besteht das Problem noch?
