### ISSUE TITLE
Jarvis bleibt nach Upgrade auf Host  4.0.23 rot 

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#1676]
Ich habe den ioBroker Host auf v4.0.23 upgegradet. Danach bleibt Jarvis rot
![Jarvis](https://user-images.githubusercontent.com/95069101/165448168-4d643904-f37c-47bd-9734-dacf0ebee886.jpg)
![Host](https://user-images.githubusercontent.com/95069101/165448169-7a8052ee-9aa7-4c71-a8f2-0777cb31fa39.jpg)
![Log1](https://user-images.githubusercontent.com/95069101/165448170-f6b98275-511a-46b8-9ef8-80e603abf16b.jpg)
![Log2](https://user-images.githubusercontent.com/95069101/165448172-7ce4fd09-7dce-441d-8d53-6f11196a90ce.jpg)
t

**Comment by Zefau** [comment]
Was steht im ioBroker Log im Backend?

**Comment by SlipKoRn88** [comment]
`<html>
<body>


jarvis.0 | 2022-04-27 18:34:19.922 | debug | Connection: Origin detected with http://192.168.178.71:8082 (allowed due to all)
-- | -- | -- | --
jarvis.0 | 2022-04-27 18:34:19.921 | debug | Connection: Origin detected with http://192.168.178.71:8082...
jarvis.0 | 2022-04-27 18:34:19.903 | info | Client with IP 192.168.178.23 connected
jarvis.0 | 2022-04-27 18:34:19.901 | debug | Websocket-Handler for client initialized
jarvis.0 | 2022-04-27 18:34:19.823 | info | Client connecting...
jarvis.0 | 2022-04-27 18:34:19.817 | debug | Connection: Origin detected with http://192.168.178.71:8082 (allowed due to all)
jarvis.0 | 2022-04-27 18:34:19.817 | debug | Connection: Origin detected with http://192.168.178.71:8082...
jarvis.0 | 2022-04-27 18:34:19.794 | debug | Connection: Origin detected with http://192.168.178.71:8082 (allowed due to all)
jarvis.0 | 2022-04-27 18:34:19.793 | debug | Connection: Origin detected with http://192.168.178.71:8082...
jarvis.0 | 2022-04-27 18:34:18.495 | info | Client with IP 192.168.178.23 disconnected
jarvis.0 | 2022-04-27 18:34:18.494 | debug | Client with IP 192.168.178.23 disconnected: transport close
jarvis.0 | 2022-04-27 18:33:53.626 | debug | Push update of scripts..
jarvis.0 | 2022-04-27 18:33:25.698 | debug | Connection: Origin detected with http://192.168.178.71:8082 (allowed due to all)
jarvis.0 | 2022-04-27 18:33:25.698 | debug | Connection: Origin detected with http://192.168.178.71:8082...
jarvis.0 | 2022-04-27 18:33:25.677 | info | Client with IP 192.168.178.23 connected
jarvis.0 | 2022-04-27 18:33:25.671 | debug | Websocket-Handler for client initialized
jarvis.0 | 2022-04-27 18:33:25.626 | info | Client connecting...
jarvis.0 | 2022-04-27 18:33:25.616 | debug | Connection: Origin detected with http://192.168.178.71:8082 (allowed due to all)
jarvis.0 | 2022-04-27 18:33:25.615 | debug | Connection: Origin detected with http://192.168.178.71:8082...
jarvis.0 | 2022-04-27 18:33:25.568 | debug | Connection: Origin detected with http://192.168.178.71:8082 (allowed due to all)
jarvis.0 | 2022-04-27 18:33:25.567 | debug | Connection: Origin detected with http://192.168.178.71:8082...
jarvis.0 | 2022-04-27 18:33:24.970 | warn | Alias alias.0.Home.Sonos.STATE has no target 12
jarvis.0 | 2022-04-27 18:33:23.631 | debug | Push update of instances..
jarvis.0 | 2022-04-27 18:33:23.251 | info | State value to set for "jarvis.0.settings.breakpoint-md" has to be type "number" but received type "string"
jarvis.0 | 2022-04-27 18:33:23.225 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2022-04-27 18:33:23.196 | debug | Connection: Using options: {}
jarvis.0 | 2022-04-27 18:33:23.195 | debug | Connection: Using non-secure HTTP-Server
jarvis.0 | 2022-04-27 18:33:23.193 | debug | Connection: ioBroker host detected with pi (IP: 192.168.178.71)
jarvis.0 | 2022-04-27 18:33:23.177 | debug | Web Configuration: {"port":"8082","auth":false,"secure":false,"bind":"0.0.0.0","cache":false,"socketio":"","simpleapi":false,"defaultUser":"admin","ttl":3600,"certPublic":"defaultPublic","certPrivate":"defaultPrivate","certChained":"","addUserName":false,"forceWebSockets":false,"whiteListEnabled":false,"leEnabled":false,"leUpdate":false,"leCheckPort":80,"loginBackgroundColor":"","loginBackgroundImage":false,"basicAuth":false,"disableExtensions":false,"disableStates":false,"disableFilesObjects":false,"defaultRedirect":"","whiteListSettings":{"default":{"user":"admin"}},"usePureWebSockets":false}
jarvis.0 | 2022-04-27 18:33:23.165 | info | Found Backups for widgets.
jarvis.0 | 2022-04-27 18:33:23.159 | info | Found Backups for devices.
jarvis.0 | 2022-04-27 18:33:23.158 | info | Found Backups for styles.
jarvis.0 | 2022-04-27 18:33:23.157 | info | Found Backups for settings.
jarvis.0 | 2022-04-27 18:33:23.153 | info | Found Backups for layout.
jarvis.0 | 2022-04-27 18:33:23.039 | info | starting. Version 3.0.9 in /opt/iobroker/node_modules/iobroker.jarvis, node: v16.14.2, js-controller: 4.0.23
jarvis.0 | 2022-04-27 18:33:22.563 | debug | States connected to redis: 127.0.0.1:9000
jarvis.0 | 2022-04-27 18:33:22.504 | debug | States create User PubSub Client
jarvis.0 | 2022-04-27 18:33:22.502 | debug | States create System PubSub Client
jarvis.0 | 2022-04-27 18:33:22.469 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
jarvis.0 | 2022-04-27 18:33:22.418 | debug | Objects connected to redis: 127.0.0.1:9001
jarvis.0 | 2022-04-27 18:33:22.409 | debug | Objects client initialize lua scripts
jarvis.0 | 2022-04-27 18:33:22.307 | debug | Objects create User PubSub Client
jarvis.0 | 2022-04-27 18:33:22.306 | debug | Objects create System PubSub Client
jarvis.0 | 2022-04-27 18:33:22.303 | debug | Objects client ready ... initialize now
jarvis.0 | 2022-04-27 18:33:22.223 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
jarvis.0 | 2022-04-27 18:33:18.778 | info | Terminated (START_IMMEDIATELY_AFTER_STOP): Without reason
jarvis.0 | 2022-04-27 18:33:18.709 | info | starting. Version 3.0.9 in /opt/iobroker/node_modules/iobroker.jarvis, node: v16.14.2, js-controller: 4.0.23


</body>
</html>`
![Error1](https://user-images.githubusercontent.com/95069101/165571144-71a4b83d-5c57-44bb-8a7a-a494f5865fb8.jpg)

![Error2](https://user-images.githubusercontent.com/95069101/165571160-a50025b8-2794-4962-afe6-06cf226e8e82.jpg)

**Comment by Zefau** [comment]
Besteht das Problem noch? Welche version hast du im Einsatz?
