### ISSUE TITLE
Daten-Zoom-Slider kann größer als 100 eingetragen werden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1678]
![image](https://user-images.githubusercontent.com/84818934/166114790-74c4bd01-62f2-466c-96d8-d4eea9aea732.png)
wird auch gespeichert. Im Frontend angezeigt wird nur 100%.

**Comment by Zefau** [comment]
fixed with `v3.1.0-alpha.26`

**Comment by mcuiobroker** [comment]
Passt. Danke.
