### ISSUE TITLE
HistoryGraph xAxis-axisLabel color wird nicht korrekt umgesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1680]
Einstellungen zur xAxis:
```
{
  "show": true,
  "position": "bottom",
  "name": "Zeit",
  "nameLocation": "middle",
  "nameGap": 30,
  "nameTextStyle": {
    "color": "green"
  },
  "splitNumber": 10,
  "axisLine": {
    "lineStyle": {
      "color": "red",
      "width": 3
    }
  },
  "splitLine": {
    "show": true
  },
  "axisLabel": {
    "lineHeight": 45,
    "rotate": 20,
    "color": "red"
  }
}
```

![image](https://user-images.githubusercontent.com/84818934/166127835-2552d1b6-ef7c-4990-9ec4-3f9084c4e482.png)

Das Datumsformat wird nicht korrekt umgesetzt, sollte so aussehen aber in rot:
![image](https://user-images.githubusercontent.com/84818934/166127888-959983e9-408c-4ce1-ac7f-cc57aeb105b8.png)

**Comment by Zefau** [comment]
einfach ohne `rotate` und `lineHeight` ?

```
{
  "show": true,
  "position": "bottom",
  "name": "Zeit",
  "nameLocation": "middle",
  "nameGap": 30,
  "nameTextStyle": {
    "color": "green"
  },
  "splitNumber": 10,
  "axisLine": {
    "lineStyle": {
      "color": "red",
      "width": 3
    }
  },
  "splitLine": {
    "show": true
  },
  "axisLabel": {
    "color": "red"
  }
}
```

**Comment by mcuiobroker** [comment]
Ja. Passt. Danke.

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.28`
Ziel er soll auf der x-Achse alle Zeitwerte auf "nur Tage" zusammenfassen und anzeigen.
-> yAxis -value-Werte sollen addiert zu einem Tag und stacked dargestellt werden.

Versuch gerade xAxisLabel zu beeinflussen-> zeigt trotzdem auch Stunden an?:
```
{
  "type": "time",
  "axisLabel": {
    "formatter": "{d}"
  }
}
```

Series-Einstellungen
```
{
  "stack": true,
  "label": {
    "show": true
  }
}
```

![image](https://user-images.githubusercontent.com/84818934/202857863-65c94f8e-f70a-4306-9bfb-1c723ea70038.png)

**Comment by Zefau** [comment]
Das Beispiel der Doku ist nicht bezogen auf xAchsen mit Zeitwerten. 

siehe https://echarts.apache.org/en/option.html#series-bar.stack:

> Notice: stack only supports stacking on value and log axis for now. time and category axis are not supported.

**Comment by Sineos** [comment]
Geht, war aber ein heiliges Gefummel: https://github.com/VolkovLabs/volkovlabs-echarts-panel/blob/main/examples/stacked_bar_graph_influxdb.md

**Comment by mcuiobroker** [comment]
Wie bekomme ich das denn in den HistoryGraph?

**Comment by Sineos** [comment]
Die Frage kann ich dir leider nicht beantworten, da bist du der Experte 😉 
Ich hab das mit dem eChart Plugin in Grafana gebastelt.
