### ISSUE TITLE
Homematic IP Geräte - HmIP-FSM16  - HmIP-PDT

### ISSUE THREAD

**Issue by isi07** [Zefau/ioBroker.jarvis#1683]
Hallo
Kannst Du bitte noch die beiden HmIP Geräte hinzufügen:

HmIP-FSM16
![grafik](https://user-images.githubusercontent.com/65848350/167217167-6868efce-9337-492a-994f-c2ca4cf72d09.png)
![grafik](https://user-images.githubusercontent.com/65848350/167217500-2022887b-ea03-47e9-92b8-0fa6c24c2933.png)
![grafik](https://user-images.githubusercontent.com/65848350/167217547-1c2441c6-185c-4e27-b173-cd68a1e86c7a.png)
![grafik](https://user-images.githubusercontent.com/65848350/167217571-beed0d88-04d9-46c0-aee7-08fe53b14901.png)

HmIP-PDT
![grafik](https://user-images.githubusercontent.com/65848350/167217292-4ead1b15-267c-4701-ae6f-214d499c6c7c.png)
![grafik](https://user-images.githubusercontent.com/65848350/167217334-5b5b8712-8177-4f44-a92b-e5aa60fa7c98.png)
![grafik](https://user-images.githubusercontent.com/65848350/167217413-da2dc0ca-80ca-411f-8353-c9c38803fd00.png)

Danke und Grüße
Christian

**Comment by Zefau** [comment]
@isi07 ich habe es endlich geschafft die Geräte zu integrieren. Sorry für die lange Wartezeit. Schau mal mit `v3.1.0-alpha.52`.

**Comment by isi07** [comment]
habe mir testweise einen iobroker mit hm-rpc und der Jarvis v3.1.0-alpha.52 eingerichtet.

Die beiden Geräte werden in Jarvis importiert.

Zu HmIP-BDT (aber auch anderen HmIP Lichtern mit Dimmen/LEVEL)
Was mir jetzt im Vergleich zu der Version v.3.0.13 auffällt, ist das Umgehen mit einer Inkonsistenz in Homematic IP zum Skalieren vom LEVEL Datenpunkt.
Das wird beschrieben in:
#https://github.com/ioBroker/ioBroker.hm-rpc/issues/337
#https://github.com/ioBroker/ioBroker.hm-rpc/issues/347
#https://github.com/ioBroker/ioBroker.hm-rpc/issues/680

HomematicIP skaliert auf dem Eingabe Wert (.3.LEVEL) mit 100% und auf dem Ausgabewert (.2.LEVEL) mit %.

In der Jarvis Version v3.0.13 scheint Jarvis irgendwie damit umgehen zu können und zeigt bei einem Dimmerlevel von zB 35% auch 35% an.
In der Jarvis Version  v3.1.0-alpha.52 wird dann 0,35 angezeigt.

Muss ich in der Jarvis Konfiguration etwas ändern, um das gleiche Verhalten wie in v3.0.13 zu erreichen oder hat sich in Jarvis etwas geändrt?

**Comment by Zefau** [comment]
Sollte auch in v3.1 funktionieren und funktioniert auch bei mir noch so.

Wichtig ist, dass der Datenpunkt in jarvis den Schlüssel `level` oder `dimmer` hat und vom Gewerk Licht (`light`) ist. Das sollte aber durch den Importer so sein. 

Kannst du mal das Gerät + Layout/Widget in jarvis screenshoten und das Ergebnis in der vis?

**Comment by isi07** [comment]
HmIP-PDT, gedimmt bei 50%

Gerät
![grafik](https://user-images.githubusercontent.com/65848350/193427861-78499853-b6fb-44f2-88c6-63dd4810b830.png)

Widget
![grafik](https://user-images.githubusercontent.com/65848350/193427893-ae37a079-1e96-4778-bfb3-9e76f5c38f0b.png)


Visu
![grafik](https://user-images.githubusercontent.com/65848350/193427742-78222db8-f2e6-423b-8a6a-4605cceb96c3.png)

Objekt
![grafik](https://user-images.githubusercontent.com/65848350/193427968-80bba53e-f34e-4f15-90e3-8585af9abe67.png)

**Comment by isi07** [comment]
Ich denke, ich hab es gefunden.
Es muss in Body Element und Action Element zusätzlich auf Verarbeiteter Wert (statt Rohwert) umgeschaltet werden.
Dann sieht es gut aus.
![grafik](https://user-images.githubusercontent.com/65848350/193429007-69b70e27-e122-4354-83ab-c8bbd26c26e5.png)


Was jetzt aber noch nicht funktioniert: Wenn ich über den Switch, das Licht ausschalte, dann bewegt sich der Slider nicht nach links auf 0, sondern bleibt beim Dimmwert stehen. Hover zeigt NaN an.
Anschalten funktioniert. Der Slider springt direkt auf den Dimm-Wert.
![grafik](https://user-images.githubusercontent.com/65848350/193428951-6fad2641-8dfc-47c3-9249-0c92ea37d497.png)

**Comment by Zefau** [comment]
> Was mit noch auffällt, in der v3.0.13 wird zB im Feld Anzeigevariante in der Geräte konfiguration so leicht angegraut eine Standardkonfiguration im Hintergrund angezeigt ( {0:"aus"} ). Ähnliches zB auch im Feld Datenpunkt Stil.

Werde ich mit der nächsten Version beheben.

> Kann es sein, dass sich dies auf den LevelBody auswirkt, wenn dieser auf verarbeiteter Wert eingestellt ist.

Ja. Der verarbeitete Wert ist der Rohwert mit allen Anpassungen, also insbesondere die Anzeige-Variante.
Du kannst den verarbeiteten Wert daher nicht nutzen, wenn du gleichzeitig einen String (also `aus`) mit drin hast.

Du musst den Rohwert nehmen für LevelBody in Kombination mit `{"min":0,"max":1}` in der Datenpunkt-Eigenschaft des Geräts und  `(marker, unit) => (parseFloat(marker) * 100) + unit` in der Konfiguration des LevelBody:

![image](https://user-images.githubusercontent.com/14368811/197061889-7ed7fc83-1f29-4867-bb17-1af5e941cea5.png)

@mcuiobroker könntest du das in deine Dokumentation übernehmen?

**Comment by Zefau** [comment]
> Was mit noch auffällt, in der v3.0.13 wird zB im Feld Anzeigevariante in der Geräte konfiguration so leicht angegraut eine Standardkonfiguration im Hintergrund angezeigt ( {0:"aus"} ). Ähnliches zB auch im Feld Datenpunkt Stil.

mit `v3.1.0-beta.1` wieder drin

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/geraet/body-element/levelbody#levelbody-fuer-werte-0-1-homematicip

**Comment by isi07** [comment]
hm... ich habe jetzt lange und viel versucht, aber es klappt mit den HmIP Dimmer Geräten nicht bei mir
meine Konfiguration
![grafik](https://user-images.githubusercontent.com/65848350/197303903-8dc7d487-b082-4206-afe9-844ef08cf3d6.png)

![grafik](https://user-images.githubusercontent.com/65848350/197303931-9eca2882-aa3d-4a2d-bc39-f706906e7dc6.png)

![grafik](https://user-images.githubusercontent.com/65848350/197303967-9558573e-8ea0-4d16-980e-bb864624d228.png)

![grafik](https://user-images.githubusercontent.com/65848350/197304038-0c7a00f5-9e68-45eb-b0fd-9e8fdc96b77c.png)

![grafik](https://user-images.githubusercontent.com/65848350/197304163-f54542e5-b09d-440d-9e2e-99f878b90cc7.png)


Ich kann den Slider nur auf 0 oder 100 setzen. Dazwischen geht nichts.
Leider setzt der Slider auf 100 dann nur den Wert 1% auf das Gerät, womit es dunkel bleibt.

![grafik](https://user-images.githubusercontent.com/65848350/197304278-3d653835-5004-4316-8226-3ffb1e6be62d.png)

![grafik](https://user-images.githubusercontent.com/65848350/197304356-c4da491d-894e-47f8-b601-8587c7c83c32.png)

**Comment by Zefau** [comment]
Die einen Komponenten Optionen sind auf Rohwert, aber die anderen auf verarbeiteten Wert. Ist das beides LevelBody? Bzw. was ist das zweite? Was passiert, wenn du auf Rohwert stellst?

**Comment by Zefau** [comment]
Aber ich seh auch gerade, dass der Trigger anders ist als der State, daher setzt er dort nur Werte von 0 bis 1%.

**Comment by Zefau** [comment]
Du müsstest also in den Datenpunkt Eigenschaften noch `setOn` verwenden, also `setOn: val => val * 100`

**Comment by isi07** [comment]
Könnt Ihr mir helfen, wie ich den Level-Datenpunkt genau konfigurieren muss. Das war in Version 3.0 deutlich einfacher.
Ich habe einen HmIP-BDT. Dimmbarer Licht-Aktor.
Herausforderung wie oben geschrieben 
der Anzeige-Datenpunkt .3.LEVEL ist 0 - 1, der Trigger-Datenpunkt .4.LEVEL geht von 0 - 100.
In der Version 3.0 hat sich Jarvis irgendwie im Hintergrund selbst um diesen Unterschied gekümmert.

Ich möchte Folgendes erreichen:
-Der Wert des Datenpunkte soll in der Oberfläche als 0 - 100% angezeigt werden.
-So soll auch die Skala von Level-Body aussehen.
-Ich möchte Level Body von 0 -100% nutzen können.
-Ebenfalls möchte ich SwitchAction nutzen können. Beim Einschalten von SwitchAction soll auf 35% gedimmt werden.
-Der Anzeige-Wert von Switch-Action soll als 0 -100% angezeigt werden.

Wie muss ich konfigurieren:
-Anzeigevariante
-Datenpunkt Eigenschaft
-Level Body Komponenten Optionen
-Switch Action  Komponenten Optionen
-wo Rohwert, wo verarbeiteten WErt

**Comment by isi07** [comment]
v 3.1.0-beta.4
Ich habe jetzt folgende Settings gefunden, mit denen es fast funktioniert.

Was jetzt noch stört: beim Ein- und Umschalten springen die Wert-Anzeige und der Level Body ganz kurz auf einen Wert *100
zB beim Einschalten auf 35%, sprint die Anzeige auf 3500% und der Level Body Balken auf 100% (max 100). Dann im nächsten Moment springen beide zurück auf 35%.
Kann man dieses "Zucken" auf *100 des Trigger-Wertes irgendwie unterdrücken?

![grafik](https://user-images.githubusercontent.com/65848350/197400423-49e57eb3-baf7-4db8-ae1c-fc54b7d76f6a.png)
![grafik](https://user-images.githubusercontent.com/65848350/197401147-281fc945-f675-49f7-be6a-b03507cb6d39.png)



Das funktioniert in 3.0.15 besser/schöner und einfacher.

level
![grafik](https://user-images.githubusercontent.com/65848350/197400300-0733fd1a-87b6-435b-93ad-d878f25ad563.png)

level Body
![grafik](https://user-images.githubusercontent.com/65848350/197400329-517421ca-5bf8-4217-a35b-e924272e467e.png)

switch action
![grafik](https://user-images.githubusercontent.com/65848350/197400350-f627f835-7986-4b6e-a4ff-1a76061fa781.png)

**Comment by Zefau** [comment]
Schau bitte nochmal mit `v3.1.0-beta.35`. Es ist keine spezielle Konfiguration notwendig, da jarvis wieder alles korrekt aus dem Standard ziehen sollte. Du musst lediglich LevelBody in den Komponenten-Optionen von `val` auf `value` umstellen.

**Comment by isi07** [comment]
Danke.
Hab ein ganz frische sTest-System aufgedeckt - nur mit hm-rpc/hm-rega und jarvis beta 35

Test mit 

HmIP-PDT
Datenpunkt Eigenschaften gesetzt auf 
`{"level":35,"min":0,"max":100,"on":35,"off":0}`
Level Body State Value gesetzt auf
`value`
Action Element  - Switch Action - State Value gesetzt auf
`value`
ebenso ist dann in der Widget Konfiguration für Body Level und Switch Action
`value`
gesetzt

Anzeige des Level Body ist jetzt richtig skaliert von 0% - 100%
Einstellen per Slider funktioniert auch gut.
Der Switch Action reagiert richtig auf das Einstellen per Slider.

Anschalten per Switch Action funktioniert auch. Er sprint auf den eingestellten Level Wert.

Das einzige Prblem ist jetzt noch:
Das Ausschalten per Switch Action schaltet zwar die Leuchte aus.
Aber der Level Body springt nicht auf 0% sondern bleibt an der letzten Position stehen.
Der Hover zeigt jetzt "NaN" an.
![grafik](https://user-images.githubusercontent.com/65848350/203861892-e3f216e9-2f3a-48d4-8633-b6eec91a1910.png)

Kann das noch gelöst werden?

**Comment by Zefau** [comment]
hm, mist. Also `NaN` steht für `Not a Number`, was dadurch bedingt ist, dass `value` genutzt wird. Das ist ja der verarbeitete Wert und nimmt bei 0 den Wert `light#level#off` (`aus`) an.

**Comment by Zefau** [comment]
> Wenn ich dort folgendes eintrage: {"0":0}

Jo, wäre das Einzige, was mir auch einfallen würde, was es möglich macht.

**Comment by isi07** [comment]
für mich damit in Ordnung und abgeschlossen.
Vielen Dank!!
