### ISSUE TITLE
Adapterstatus u. Updates wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by Matschk0pf** [Zefau/ioBroker.jarvis#1689]
**Prerequisites / Voraussetzungen**
v3.0.11

**Describe the bug / Beschreibe den Fehler**
1. In Widget Konfig ist _Adapter Updates_ nicht aktiviert, angezeigt werden die Updates trotz dessen
2. Der Adapterstatus wird z.T. nicht richtig angezeigt (z.B. beim denon u. innogy-smarthome Adapter)

**Screenshots**
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2439

**Comment by Zefau** [comment]
@Matschk0pf besteht das Problem mit v3.1-alpha noch?

**Comment by Zefau** [comment]
@Matschk0pf
