### ISSUE TITLE
Hide Pro Notification

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#1690]
Trotz aktivierem Schalter 
![image](https://user-images.githubusercontent.com/25475385/170509284-9f704085-352e-4233-bc30-3a383a46e976.png)
erhalte ich trotzdem folgenden Popup
![image](https://user-images.githubusercontent.com/25475385/170509208-8da3a126-0fb2-41a6-99ab-5e767d8c2b57.png)

**Comment by mcuiobroker** [comment]
Der Schalter hat nur etwas mit der Nachricht zu tun, die man bekommt, wenn man die PRO-Version hat.
Hat man diese, so würde beim Start vom Frontend eine 3-sekündige Begrüßung erscheinen. Mit dem Schalter `Hide Pro Notification` schaltet man diese Begrüßung ab.
Den Popup erhälst du, da du irgendwo in dem Gerät FritzBox ein Callnack definiert hast, der nur mit der PRO genutzt werden kann.

**Comment by duczz** [comment]
Kann man diese popups ggf auch deaktivierbar machen?

**Comment by duczz** [comment]
Naja, willst für die Zukunft schon drin stehen lassen.

**Comment by Zefau** [comment]
@mcuiobroker @duczz Notifications können nun deaktiviert werden in den Einstellungen. Das Issue kann damit zu?
