### ISSUE TITLE
Zugriff auf Jarvis nicht mehr möglich (timeout)

### ISSUE THREAD

**Issue by fila612** [Zefau/ioBroker.jarvis#1692]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Fehler bei Stable-Version 3.0.11 UND auch bei 3.1.0 Alpha 8

**Describe the bug / Beschreibe den Fehler**
Seit kurzen kann weder aus ioBroker heraus noch via Direktlink auf Jarvis Zugreifen.

Web Configuration: {"port":8082,"auth":false,"secure":false,"bind":"0.0.0.0","cache":false,"socketio":"","simpleapi":false,"defaultUser":"admin","ttl":3600,"certPublic":"","certPrivate":"","certChained":"","addUserName":false,"forceWebSockets":false,"whiteListEnabled":false,"leEnabled":false,"leUpdate":false,"leCheckPort":80,"loginBackgroundColor":"","loginBackgroundImage":false,"basicAuth":false,"disableExtensions":false,"disableStates":false,"disableFilesObjects":false,"defaultRedirect":"","usePureWebSockets":false,"compatibilityV2":true}

**Screenshots**
schwierig, da die Seite sich nicht aufbaut

**Comment by Zefau** [comment]
Fehler im ioBroker Log?
Was genau steht in der Browser Konsole via F12?
Welche Web Adapter Version?
Klappt der Zugriff über Port 8400?

**Comment by fila612** [comment]
da ich nicht genau weiß wie ich die Konsole im Safari öffne, habe ich zufällig den Aufruf mit Opera probiert.
Jetzt bin ich verwirrt: der Aufruf klappt. 
Scheint daher ein Problem mit meinem Safari zu sein.

Oder könnte es auch ein Problem von JARVIS in Verbindung mit Safari sein?

Fehler im iobroker Log habe ich keine, jedoch sehe bei Nutzung mit Safari auch keine Bewegung von JARVIS im Log (u.a. die Einträge, dass ein Client sich verbunden hat).
WebAdapter ist die 5.2.0

Zugriff die Port 8400 klappt auch nicht, ich meinte das gestern auch schon einmal probiert zu haben und da erschien nur eine Plaintext Zeile das dies nicht der richtige Port sei.

**Comment by Zefau** [comment]
Wenn du vom ioBroker Dashboard aus in Safari öffnest geht es auch nicht?

**Comment by fila612** [comment]
Nein, da kommt auch nichts. Seite bleibt weiß und der schmale blaue Balken unterhalb der URL-Leiste in Safari bleibt stehen.

**Comment by fila612** [comment]
ich denke ich kann hier schließen. Es wird mit hoher Wahrscheinlichkeit an meinem Netzwerk liegen. Wenn ich aus meinem Netzwerk mich via VPN wieder in mein NW reinwähle (macht ja keinen Sinn) kann ich via Safari auf Jarvis zugreifen. die VPN Verbindung ist nur für den ersten Zugriff notwendig, wenn ich mal auf der Site bin, kann ich auch ohne VPN navigieren.
