### ISSUE TITLE
Pie-Chart with variable unit

### ISSUE THREAD

**Issue by SKB-CGN** [Zefau/ioBroker.jarvis#1694]
Hi,
i have inserted a Pie-Chart into Jarvis, but the unit is mentioned as "undefined".
The unit for the displaying values is dynamically.

The JSON unit is entered like this:
`"{">1000":"kWh","<1000":"Wh"}"`

Pie-Chart:
![2022-06-02 14_39_22-jarvis - just another remarkable vis — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/171833174-a81e3329-7e93-4531-a06c-d20b136535f9.png)

**Comment by Zefau** [comment]
fixed with `v3.1.0-alpha.30`
