### ISSUE TITLE
Failed to set an indexed property on 'CSSStyleDeclaration'

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1695]
![image](https://user-images.githubusercontent.com/84818934/172071285-cf26b639-85ca-4927-ac73-09e2a79830f2.png)

Jede Menge davon:
![image](https://user-images.githubusercontent.com/84818934/172071291-661725dc-9799-460d-8138-4c680933472c.png)

`{"{0_userdata.0.jarvis.timeTable.week.today}='tuesday'":{"background-color":"rgba(63,63,63,0.7)","border":"1px solid white"}}`
![image](https://user-images.githubusercontent.com/84818934/172071631-015a13af-a8f0-4556-aa45-947d72069738.png)

Icon werden teilweise nicht angezeigt:
![image](https://user-images.githubusercontent.com/84818934/172071441-873e925a-a7fe-43b7-876a-2a5236ee1f75.png)
Schalter wird teilweise nicht korrekt angezeigt?
![image](https://user-images.githubusercontent.com/84818934/172071456-90017f19-1318-4243-bd27-94863859fb96.png)

Wettersymbole fehlen:
![image](https://user-images.githubusercontent.com/84818934/172072219-b87cb8ac-1fa0-4710-9b9e-7c0add6b8d4b.png)

Umschalten auf anderen TAB:
![image](https://user-images.githubusercontent.com/84818934/172072265-9812abe6-506b-45c4-a7e4-2fd554961a37.png)

![image](https://user-images.githubusercontent.com/84818934/172072431-76cd3e99-a3ec-4259-a769-498e054f1b9d.png)

![image](https://user-images.githubusercontent.com/84818934/172075741-caecff6e-c614-41e8-834e-ee8e4b622c82.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1146886723_

**Comment by Zefau** [comment]
>Das Tab umschalten geht mit keinem deiner Tabs oder nur nicht mit bestimmten Tabs? Bei mir geht das Umschalten. Liegt ggf. an einem bestimmten Modul?

Das ist eher zeitweise.

>Kannst du identifizieren, bei welchem Gerät der CSSStyleDeclaration Fehler auftritt?

Nein
![image](https://user-images.githubusercontent.com/84818934/172236531-da4365af-f3db-4b26-b91e-56904e36bbd1.png)

Anscheinend dieser?
![image](https://user-images.githubusercontent.com/84818934/172239129-7ca38723-fbee-49cf-95bf-0b82d2b4e49d.png)
![image](https://user-images.githubusercontent.com/84818934/172239271-db1c4590-7c63-4d10-8c92-f59dc86adea1.png)
`{"13":{"animation":"in_set_red 1s  infinite"}}` gelöscht
Ja daran lag es.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1147843891_

**Comment by Zefau** [comment]
@mcuiobroker tritt der `CSSStyleDeclaration` Fehler noch auf?

**Comment by mcuiobroker** [comment]
Nein. Kann geschlossen werden.

**Comment by Zefau** [comment]
bzgl. `CSSStyleDeclaration` schau nochmal mit `v3.1.0-alpha.21`
