### ISSUE TITLE
Scripting

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1696]
Wenn man dann eine Variable in einem Script definiert hat und dieses Script mit <script>let testVar = 0;  </script> definiert hat, wie muss man darauf im Binding zugreifen?
`{"{testVar}=0":"....."}`
Wenn die testVar ein String ist dann auch wieder
`{"'{testVar}'='0'":"....."}`

oder ist scripts schon der Inhalt von einem <script> </script>?
Kann man im Scripts auch zusätzlich Dateien als Script einfügen mit <script src="../test/javascript.js"></script>?

Beispiel-Test -> wird nicht berücksichtigt
![image](https://user-images.githubusercontent.com/84818934/172151059-39b60aa0-c50c-4cc2-9905-f50b9af45265.png)
![image](https://user-images.githubusercontent.com/84818934/172151318-f17db727-69b8-4332-add5-57455008e677.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1147303951_

**Comment by Zefau** [comment]
>{"testVar=0":"....."}

> Ist die Variable auf 1 wird es trotzdem ausgeführt?
  ![image](https://user-images.githubusercontent.com/84818934/172154255-3a3b015c-37f0-4b72-95e6-21e440f3535a.png)
  ![image](https://user-images.githubusercontent.com/84818934/172154315-abcc7610-2de5-4d3c-901e-b4426fcc1feb.png)
  ![image](https://user-images.githubusercontent.com/84818934/172154396-903f7021-13ab-4945-9191-72633ee48163.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1147360165_

**Comment by Zefau** [comment]
Scripts beim Start
Warum 3x subscribeStates?
```
window.Socket.subscribeState('0_userdata.0.temperature', ({ err, state }) => {
   console.log('SUBSCRIBESTATE'+state);
});

window.Socket.getState('0_userdata.0.temperature', ({ err, state }) => {
   console.log('GETSTATE'+state);
});
```
![image](https://user-images.githubusercontent.com/84818934/172413518-7fa2c07d-ad03-403e-9b9d-ab58cbfd11b1.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1148793506_

**Comment by Zefau** [comment]
Scripts
Im Rückgabe Wert state sind objekte mehrfach enthalten:
1x im config-Objekt und dann nochmal einzeln?
Da im config eigentlich mehrere Objekte sein können, da eine ioBroker-ID mehrfach in mehreren Devices sein kann, sollte `config` eigentlich ein `Array` sein?
Es fehlt auch ein Bezug auf das ioBroker-Objekt(s.u.)
```
{
	"val": 156,
	"ack": false,
	"ts": 1654612496248,
	"q": 0,
	"from": "system.adapter.admin.0",
	"user": "system.user.admin",
	"lc": 1654612496248,
	"id": "0_userdata.0.Power0",
	"key": "power0",
	"stateKey": "power0",
	"value": "dim156%",
	"config": {
		"bodyElement": "LevelBody",
		"display": {
			"true": "defaults#on",
			"false": "defaults#off"
		},
		"stateStyle": {
			"true": {
				"color": "#090",
				"fontWeight": "bold"
			},
			"false": {
				"color": "#999"
			}
		},
		"showState": true,
		"state": "0_userdata.0.Power0",
		"label": "",
		"LevelBodyConfig": {
			"step": "6.25",
			"markStep": "16"
		},
		"properties": {
			"value": "val => 'dim'+Math.floor(val)+'%'"
		},
		"action": "0_userdata.0.Power0",
		"stateKey": "power0"
	},
	"bodyElement": "LevelBody",
	"stateStyle": {
		"true": {
			"color": "#090",
			"fontWeight": "bold"
		},
		"false": {
			"color": "#999"
		}
	},
	"state": "0_userdata.0.Power0",
	"actionElement": "DropdownAction",
	"action": "0_userdata.0.Power0",
	"properties": {
		"value": "val => 'dim'+Math.floor(val)+'%'"
	}
}
```
![image](https://user-images.githubusercontent.com/84818934/172437161-ebddc0b0-2940-4e02-bf17-fdb6f5cf2ee8.png)
type, common.type,, role usw wären auch wichtige Werte, die man in Scripts abfragen können sollte?

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1148916621_

**Comment by mcuiobroker** [comment]
getObejct liefert undefined?
![image](https://user-images.githubusercontent.com/84818934/172698427-0504b757-4531-4dfa-9310-b526968bf731.png)
```
window.Socket.getObject('0_userdata.0.temperature', ({ err, state}) => {
   console.log('GETOBJECT'+state);
});
```

**Comment by mcuiobroker** [comment]
Sollte man auch existsState und existsObject als Funktionen mit anbieten? 
Oder werden diese schon vorab mit getState, setState, usw. geprüft?

**Comment by Zefau** [comment]
`object` statt `state`:
```
window.Socket.getObject('0_userdata.0.temperature', ({ err, object }) => {
   console.log('GETOBJECT'+object );
});
```

Promises fängst du mit `then( ... )` ab, siehe https://www.w3schools.com/js/js_promise.asp

**Comment by mcuiobroker** [comment]
Editor auch für scripts und CSS?
![image](https://user-images.githubusercontent.com/84818934/173159116-4b752a24-3f2d-47c7-9506-98b1709ab756.png)

**Comment by mcuiobroker** [comment]
v3.1.0-alpha.16 subscribeStates nur noch 2x:
![image](https://user-images.githubusercontent.com/84818934/173160162-b5f8262d-fcef-4b4e-be55-5cd35739917f.png)

**Comment by mcuiobroker** [comment]
`scripts` wurden mal angezeigt, jetzt nicht mehr?
![image](https://user-images.githubusercontent.com/84818934/173708730-65531250-0b66-4b99-a75e-a066dd6ce5ba.png)

**Comment by sigi2345** [comment]
> `scripts` wurden mal angezeigt, jetzt nicht mehr? 
Bei mir sieht es so aus:

![Screenshot (4944)](https://user-images.githubusercontent.com/41079106/173768537-b9a75082-e92e-458e-a09a-82972a1f08f8.png)

**Comment by mcuiobroker** [comment]
JSON-Wert wird mit `getState` nicht gelesen.
```
function test(e){
        console.log('Zeile ' + e + ' gewählt!');
	window.Socket.getState('0_userdata.0.forum.recentJSON', ({ err, state }) => {
		console.log(state);
                if (err){
			console.log('Error JSON holen');
		}else{
			console.log('JSON geholt');
			console.log(JSON.stringify(state));
			let jsonArr = state;
			alert(jsonArr[e].creator);
		}
	});  
}
```
Wenn man den gleichen Wert mit `subscribeState` liest, werden die Daten angezeigt?
```
window.Socket.subscribeState('0_userdata.0.forum.recentJSON', ({ err, state }) => {
   console.log('SUBSCRIBESTATE: '+JSON.stringify(state));
});
```

**Comment by Zefau** [comment]
Die Funktion musst du natürlich irgendwo aufrufen.

**Comment by mcuiobroker** [comment]
Mach ich vom Button aus.
![image](https://user-images.githubusercontent.com/84818934/173916611-3dae5954-9c77-4070-b04a-6df9d794b705.png)

**Comment by mcuiobroker** [comment]
setState funktioniert mit `string`. Andere noch nicht getestet.
```
function recentTable(e){
        console.log('Zeile ' + e + ' gewählt!');
        window.Socket.setState('0_userdata.0.forum.activeNum',e,false);
}
```

**Comment by mcuiobroker** [comment]
Gibt es die Möglichkeit Dateien als Skript in `scripts` zu importieren?
`import 'http://192.168.178.70/jarvis/scripts/export.js'`
Oder einen anderen Befehl?

**Comment by Zefau** [comment]
Ist hier noch was offen? `getState` funktioniert bei mir und den Rest hatten wir in anderen Issues geklärt oder?

**Comment by mcuiobroker** [comment]
Das Problem mit testVar=0 von oben ist noch vorhanden.
![image](https://user-images.githubusercontent.com/84818934/184446516-d142177c-51d1-45d0-af04-50c14df94128.png)
`{"testVar=0":{"background-color":"yellow"}}`
In Scripts
`let testVar = 1;`

**Comment by mcuiobroker** [comment]
`{"{testVar}=0":{"background-color":"yellow"}}`
`{"{testVar}==0":{"background-color":"yellow"}}` auch keine Besserung.

**Comment by mcuiobroker** [comment]
`v3.1.0-alpha.32` nicht hochgeladen?

**Comment by mcuiobroker** [comment]
`v31.0.-alpha.35`
Es dauert ca 25 Sekunden bis die Icon in der StateList angezeigt werden. Unabhängig, ob ich die Seite direkt neu aufrufe (F5) oder beim Seiten/TAB-Wechsel aufrufe.
Nur bei der ersten Seite. In meinem Fall HOME Seite. Hängt eventuell mit der dort eingesetzten `testVar` Variable zusammen?

**Comment by Zefau** [comment]
ist hier noch was offen?

**Comment by mcuiobroker** [comment]
Ja.
- testVar (im Script hinterlegt) zieht nicht im Binding
- Wenn man Speichert und Beenden klickt bei Änderung oder auch nicht
![image](https://user-images.githubusercontent.com/84818934/189201047-d35a232c-7c3b-455b-946d-23b13a5ab7b4.png)

**Comment by Zefau** [comment]
> Wenn man Speichert und Beenden klickt bei Änderung oder auch nicht

Hier sollte jarvis reloaden. Das ist das Problem, was ich unter https://github.com/Zefau/ioBroker.jarvis/issues/1805#issuecomment-1203133476 beschrieben habe. Da kann ich nicht viel machen.

**Comment by mcuiobroker** [comment]
Das macht jarvis eben nicht. Er führt dann kein automatischen Reload durch sondern startet die Seite mit dem Fehler.
Kann man da ne Abfrage einbauen, wenn Script error null -> Reload?

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.45`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/190878468-118638d8-a6b5-4cd3-bf20-af80417d08a4.png)
Bitte ohne Popup.

**Comment by Zefau** [comment]
Ohne Pop-up verwirrt die User, weil jarvis dann gefühlt 'einfach so' reloaded.

**Comment by mcuiobroker** [comment]
Ok. Dann kann man unten, wie beim Update in rot eine Nachricht kurz anzeigen.
Man kommt ja gerade aus der Konfiguration.  Also wäre eine direkter Reload nicht störend nur verwunderlich,  dafür die rote Nachricht?

**Comment by hosabeni** [comment]
Ist es auch möglich den Werte einer Script Variable (ScriptVar) als Wert eines Datenpunktes anzuzeigen?
Zum Beispiel als Datenpunkt Eigenschaft mit `{"value": "val => ScriptVar"}`

**Comment by mcuiobroker** [comment]
`{"value":"val => testVar"}` geht noch nicht.
![image](https://user-images.githubusercontent.com/84818934/190928012-9960177d-89e3-4754-b757-02fba606effd.png)

`{"value":"val => {testVar}"}` geht noch nicht.
![image](https://user-images.githubusercontent.com/84818934/190927972-05c80db9-92b5-47ba-bd72-a03abb633a2b.png)

**Comment by mcuiobroker** [comment]
Das Problem mit dem Popup für den Reload ist, dass man es auf allen Gerät machen muss?
Auf allen connected Systemen (Tablet, Handys).
![image](https://user-images.githubusercontent.com/84818934/192167793-05db8f78-4816-486c-8ed4-66916c3bb769.png)

**Comment by Zefau** [comment]
Mit `v3.1.0-alpha.61` geht `{"value":"val => testVar"}` bei mir. Kannst du das bestätigen?

**Comment by Zefau** [comment]
Und ich habe den Reload angepasst. Jede Änderung bei Skripten führt direkt zu einem Reload (ein entsprechender Hinweis ist im Tab platziert).

**Comment by mcuiobroker** [comment]
Reload wird nicht angezeigt und auch nicht durchgeführt.
![image](https://user-images.githubusercontent.com/84818934/196802390-95a69ac9-6972-4c8f-968b-9752a6d6d833.png)

Also der Wert wird dann korrekt angezeigt.
`{"value":"val => testVar"}` 
Wird dann aber der Wert im Scripts geändert wird keine Änderung angezeigt.

Weiterhin bleibt das Problem von oben:
`{"{testVar}=0":{"background-color":"yellow"}}` z.B. im Body Stil

**Comment by Zefau** [comment]
Es gibt keinen extra Hinweis, da es ja direkt auf der Seite steht:

![image](https://user-images.githubusercontent.com/14368811/197017181-a67354c5-a048-4753-aa10-e0f87581a87a.png)

**Comment by mcuiobroker** [comment]
Kann man die anderen geöffneten Seiten nicht auch neu laden, wie beim Update?

**Comment by Zefau** [comment]
>  Neuladen ist ja auch notwendig, wenn keine Scripte geändert werden, das ist das das Problem.

Warum?

**Comment by mcuiobroker** [comment]
Weil er anscheinend mit den schon vorhandenen Variablen nicht klar kommt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.1`, damit sollte er alle offenen Fenster neuladen

**Comment by mcuiobroker** [comment]
Es wird noch nicht neugeladen.
![image](https://user-images.githubusercontent.com/84818934/197063741-2d840dd3-376d-47fb-8f01-96b188311427.png)

Aber es wird die Variable erkannt: `{"{testVar}=2":{"background-color":"green"}}`
Obwohl noch die Warnungen kommen.

**Comment by Zefau** [comment]
zeig mal bitte die Konfiguration dafür

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/197065558-03eff1bb-d5fb-4b14-b003-3cd22b85e960.png)

{"{testVar}=2":{"background-color":"green"}}

**Comment by mcuiobroker** [comment]
Jetzt zeigt er es auch im Frontend direkt an:
![image](https://user-images.githubusercontent.com/84818934/197069326-1d5d3b98-2aca-4607-948c-cbea66841a95.png)
Warum mit Zeitverzögerung? Auch auf dem Handy.

**Comment by mcuiobroker** [comment]
`v3.10.beta.4`
Er reagiert auf testVar.
`{"testVar=2":{"background-color":"green"}}` muss drin stehen, dann wird beim erstmaligem Start die Variable erkannt.
Wird diese im Laufe der Zeit geändert auf einen anderen Wert, so bekommt er das nicht mehr mit.

**Comment by hosabeni** [comment]
`v3.1.0.beta.4`
Mit `{"value":"val => {uptime}"}` in der Anzeigevariante wir nicht der Wert der Variable `uptime` sondern der Wert vom DP.



![Image](https://user-images.githubusercontent.com/77939385/197414554-0c130ad4-2a70-4824-b4f0-068b7d1c6129.png)



![Image](https://user-images.githubusercontent.com/77939385/197414586-006b2482-c561-4551-b2e5-f9abb828def2.png)


```
let uptime;

window.Socket.subscribeState('rpi2.0.uptime.uptime', ({ err, state }) => {
  uptime = parseInt(state.val/60/60/24/365,0,0) + 'J ' + parseInt(state.val/60/60/24%365,0) + 'T ' +  parseInt(state.val/60/60%24,0) + 'h ' + parseInt(state.val/60%60,0) +  'm ' +  parseInt(state.val%60,0) + 's';
  console.log(uptime);
});

```

Das sollte eigentlich angezeigt werden (Log Konsole):
![Image](https://user-images.githubusercontent.com/77939385/197414596-e2dc73de-31ff-481e-a5ca-181adfce5319.png)

Das wird angezeigt:
![Image](https://user-images.githubusercontent.com/77939385/197414802-020da97c-c65b-4fe4-b5ce-53a92ef205fc.png)

**Comment by Zefau** [comment]
Das Problem ist, dass die ausgeführten Funktionen des Socket asynchron sind. Der initiale Wert also verwendet wird und dann nicht aktualisiert wird, weil das Update erst nach dem Laden kommt und jarvis nicht weiß, für welches Gerät hier das Update zu erfolgen hat.

Insofern gibt es nun mit `v3.1.0-beta.6` die Funktion `applyDeviceState(deviceId, stateKey, state)`. Mit dieser kann der Wert aktualisiert werden.

Verwendung:
```
let uptime;

window.Socket.subscribeState('rpi2.0.uptime.uptime', ({ err, state }) => {
  uptime = parseInt(state.val/60/60/24/365,0,0) + 'J ' + parseInt(state.val/60/60/24%365,0) + 'T ' +  parseInt(state.val/60/60%24,0) + 'h ' + parseInt(state.val/60%60,0) +  'm ' +  parseInt(state.val%60,0) + 's';
  console.log(uptime);

  applyDeviceState("b9462fc8-ebcf-...", "Uptime"); // aktualisiert das Binding im Gerät
});
```
oder
```
let uptime;

window.Socket.subscribeState('rpi2.0.uptime.uptime', ({ err, state }) => {
  uptime = parseInt(state.val/60/60/24/365,0,0) + 'J ' + parseInt(state.val/60/60/24%365,0) + 'T ' +  parseInt(state.val/60/60%24,0) + 'h ' + parseInt(state.val/60%60,0) +  'm ' +  parseInt(state.val%60,0) + 's';
  console.log(uptime);

  applyDeviceState("b9462fc8-ebcf-...", "Uptime", { ...state, "val": uptime }); // aktualisiert den Wert des Geräts
});
```

**Comment by hosabeni** [comment]
Diese Version funktioniert bei mir. Bindings mit Script Variablen habe ich noch nicht im Einsatz.
```
let uptime;

window.Socket.subscribeState('rpi2.0.uptime.uptime', ({ err, state }) => {
  uptime = parseInt(state.val/60/60/24/365,0,0) + 'J ' + parseInt(state.val/60/60/24%365,0) + 'T ' +  parseInt(state.val/60/60%24,0) + 'h ' + parseInt(state.val/60%60,0) +  'm ' +  parseInt(state.val%60,0) + 's';
  console.log(uptime);

  applyDeviceState("b9462fc8-ebcf-...", "Uptime", { ...state, "val": uptime }); // aktualisiert den Wert des Geräts
});
```

**Comment by hosabeni** [comment]
Ich hab das mal so als Anzeigevariante eingegeben, hat leider nicht funktioniert. Ich hab das mit `v3.1.0.beta.5` getestet, mit `v3.1.0.beta.7` und `v3.1.0.beta.8` haben sie Seiten nicht richtig aufgebaut und auch nicht mehr richtig reagiert.

![Image](https://user-images.githubusercontent.com/77939385/198720323-82f2f058-4e2e-4931-95d4-69d1125948e8.png)

**Comment by mcuiobroker** [comment]
In die DatenpunktEgenschaften:
`{"value":"val => parseInt(val/60/60/24/365,0) + 'J ' + parseInt(val/60/60/24%365,0) + 'T ' + parseInt(val/60/60%24,0) + 'h ' + parseInt(val/60%60,0) + 'm ' + parseInt(val%60,0) + 's'"}`

![image](https://user-images.githubusercontent.com/84818934/198722937-00df0d59-63d2-477f-942c-4a1b94e22bf1.png)

**Comment by hosabeni** [comment]
Unter Datenpunkt-Eigenschaften geht es.
Danke!

**Comment by Zefau** [comment]
@mcuiobroker kannst du die Funktionsweise mit `applyDeviceState(deviceId, stateKey)` bestätigen, um zu aktualisieren?

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.7`
scripts wurden bei mir kurz nicht gespeichert? Musste Instanz neu starten.

Problem: Es wird nicht aktualisiert, obwohl scripts geändert wurde.

Übersehe ich was?
```
let dataVal=0;
let testVar = 0;
setTimeout(function(){
	testVar = 2;
	console.log('Wechsel vom Inhalt der Variable: '+testVar);
	window.Socket.subscribeState('0_userdata.0.jarvis.test.number', ({ err, state }) => {
		testVar = state.val;
		console.log('testVar: '+testVar);

		applyDeviceState("bbea1d7b-d2ba-4c1f-9afd-ee0ab7f60065", "testVar"); // aktualisiert das Binding im Gerät
	});
},10000);
```
![image](https://user-images.githubusercontent.com/84818934/198841716-998556d8-d447-4995-a2d2-13bfa015aa74.png)

**Comment by Zefau** [comment]
Mein Fehler: `refreshDeviceState` muss es heißen. Schau nochmal mit `v3.1.0-beta18`.

> Trägt man in dem Binding z.B. (body stil) {"var(--testVar)=2":{"background-color":"yellow"}} ein, so kommt keine Fehlermeldung, es wird aber auch nicht korrekt angezeigt.

`var()` ist nur bei CSS.

**Comment by mcuiobroker** [comment]
Ist das jetzt bei beiden Funktionen refreshDevicecState?
let uptime;

window.Socket.subscribeState('rpi2.0.uptime.uptime', ({ err, state }) => {
  uptime = parseInt(state.val/60/60/24/365,0,0) + 'J ' + parseInt(state.val/60/60/24%365,0) + 'T ' +  parseInt(state.val/60/60%24,0) + 'h ' + parseInt(state.val/60%60,0) +  'm ' +  parseInt(state.val%60,0) + 's';
  console.log(uptime);

  refreshDeviceState("b9462fc8-ebcf-...", "Uptime"); // aktualisiert das Binding im Gerät
});
oder

let uptime;

window.Socket.subscribeState('rpi2.0.uptime.uptime', ({ err, state }) => {
  uptime = parseInt(state.val/60/60/24/365,0,0) + 'J ' + parseInt(state.val/60/60/24%365,0) + 'T ' +  parseInt(state.val/60/60%24,0) + 'h ' + parseInt(state.val/60%60,0) +  'm ' +  parseInt(state.val%60,0) + 's';
  console.log(uptime);

  refreshDeviceState("b9462fc8-ebcf-...", "Uptime", { ...state, "val": uptime }); // aktualisiert den Wert des Geräts
});

**Comment by mcuiobroker** [comment]
Sonst sieht es gut aus.
Also die auch refresh..?
`refreshDeviceState("b9462fc8-ebcf-...", "Uptime", { ...state, "val": uptime }); `

**Comment by mcuiobroker** [comment]
Also bei mir steht ja in den Scripts ein Import drin -> keine Änderung erkannt.
Aber auch mit Ändeung wird kein Reload ausgeführt.
Deswegen bitte eine Option in den Einstellungen, daß bei Speicherung automatisch ein Reload gemacht wird.
Sonst startet er und ich muss trotzdem ein Reload durchführen, also doppelt.

**Comment by mcuiobroker** [comment]
Bekomme manchmal trotzdem die Meldung:
![image](https://user-images.githubusercontent.com/84818934/201250490-982d02d9-b306-4862-80b2-f9b630d966fc.png)

**Comment by Zefau** [comment]
> Ist das jetzt bei beiden Funktionen refreshDeviceState?

Ja. Beide Varianten updaten das Binding. Die zweite Variante updated noch den Wert des Geräts selbst.

**Comment by Zefau** [comment]
> Wie wäre die Bindingabfrage bei String Wert?
> Auch mit '?
> {"'{testVar}'='2'":{"background-color":"yellow"}}

Sieht korrekt aus und sollte so funktionieren.

**Comment by Zefau** [comment]
> Also bei mir steht ja in den Scripts ein Import drin -> keine Änderung erkannt.

Zeig mal bitte, was du meinst. Imports werden aufgelöst, folgen aber einer bestimmten Syntax,

> Deswegen bitte eine Option in den Einstellungen, daß bei Speicherung automatisch ein Reload gemacht wird.
> Sonst startet er und ich muss trotzdem ein Reload durchführen, also doppelt.

Bei Speicherung erfolgt immer automatisch ein Reload, wenn Scripts geändert werden. In allen anderen Fällen sollte es nicht notwendig sein.

> Oder man fragt import (scripts) ab, ob vorhanden -> Reload immer bei jeglicher Konfigurationsänderung..

Ok, jetzt verstehe ich. Du änderst NICHTS an den Skripten aber durch den Import funktioniert es nicht und er macht auch keinen Reload?

**Comment by mcuiobroker** [comment]
Zum letzten Punkt-> ja
Ich ändere nix und trotzdem meckert er die schon vorhandene Variable an.
Bin noch nicht zuhause. Andere später.

**Comment by mcuiobroker** [comment]
>Zeig mal bitte, was du meinst. Imports werden aufgelöst, folgen aber einer bestimmten Syntax,

![image](https://user-images.githubusercontent.com/84818934/201542060-ac6a496c-5b2c-4b99-84e8-89746b80fe80.png)
```

import "https://code.jquery.com/jquery-3.6.0.js";

import "http://192.168.178.89/download/widgetsDisplay.js";
```

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.20`

**Comment by mcuiobroker** [comment]
Korrekte meldung unten als Popup, aber nicht als console.log im DOM zur Nachverfolgung.
![image](https://user-images.githubusercontent.com/84818934/201545022-18558fec-67d3-4a0c-9c7b-0f4b1316d2fc.png)

In Styles was geändert -> Speichern und beenden -> kein Reload ->
![image](https://user-images.githubusercontent.com/84818934/201545173-beaf6295-5db6-474e-b0d7-47f650104fe1.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.21`

**Comment by mcuiobroker** [comment]
Reload wird jetzt gemacht.
Bleibt nur noch die Fehlermeldung auch als console.log im DOM. Dann sind wir hiermit fertig.

**Comment by mcuiobroker** [comment]
Sah so gut aus:
Jetzt kommt eine Fehlermeldung: testVar nicht vorhanden, obwohl vorhanden. Aber auch nur sporadisch.
Scheint etwas mit den Lade-Zeiten zu tun zu haben.
![image](https://user-images.githubusercontent.com/84818934/201549470-44dc51f9-7952-4107-b554-9017fac7eb4a.png)

![image](https://user-images.githubusercontent.com/84818934/201549487-eee17717-41f2-493f-ad63-68aef1e18258.png)

![image](https://user-images.githubusercontent.com/84818934/201549500-bf532559-ae30-40c8-b73a-f299f959f1b5.png)

**Comment by mcuiobroker** [comment]
Diese Fehlermeldung, die als Popup kommt:
![image](https://user-images.githubusercontent.com/84818934/202015224-cf1ab378-5c0f-4d9d-82f2-5a2a12a4678b.png)

sollte auch im console.log erscheinen, damit man es nachverfolgen kann. Der Popup ist nach 3 Sekunden weg, im LOG bleibt es.
![image](https://user-images.githubusercontent.com/84818934/202015366-f1dfbe35-e6ac-4c2d-84dd-05c4ceda8095.png)

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-beta.22`

**Comment by mcuiobroker** [comment]
Fehlermeldung kommt jetzt auch im console.log.

Bleibt nur noch das Problem mit den Ladezeiten bei `import`.

Anscheinend werden die import-Datei nicht schnell genug geladen und findet deswegen die Variable `testVar` nicht und meckert dies an.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.24`

**Comment by mcuiobroker** [comment]
Bei abbrechen kommt noch der Fehler -> kein Reload:
![image](https://user-images.githubusercontent.com/84818934/202300152-36d244f7-db1e-4f1d-bcb9-653c232877c1.png)

**Comment by Zefau** [comment]
Beim Abbrechen sollte eigentlich nun ein `reload=true` in der URL stehen, worauf Jarvis dann reloaded.

**Comment by mcuiobroker** [comment]
Steht drin, aber kein reload.

**Comment by Zefau** [comment]
Erscheint denn bei dir in der Browser-Konsole die folgende Meldung?
> Received an Update for Scripts, which requires a reload of the page!

**Comment by mcuiobroker** [comment]
Nein

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-beta.27`

**Comment by mcuiobroker** [comment]
Reload läuft.
![image](https://user-images.githubusercontent.com/84818934/202576109-2dc42690-18b5-41cc-9693-f686ff1272c5.png)

**Comment by Zefau** [comment]
Kann dann zu? :-)

**Comment by mcuiobroker** [comment]
Nein . Ladezustand. Testvar

**Comment by Zefau** [comment]
Zeig bitte nochmal den Code aus dem Import und wie du diesen benutzt.

Bringt es nichts die Variable vorher zu definieren?

Auch wenn ich es jetzt früher in jarvis laden würde: Die Abfragen mittels Socket sind immer asynchron und dadurch mit einem delay. Insofern muss die Variable die du manipulierst zwingend vorher definiert sein.

Wenn dem so ist, dann muss ich in jarvis was ändern.

**Comment by mcuiobroker** [comment]
scripts-Inhalt
```
import "https://code.jquery.com/jquery-3.6.0.js";
/* let testVar; */

 /* import "http://192.168.178.89/download/widgetsDisplay.js";  */
 import "http://192.168.178.89/download/scripts.js";
```

Direkt im Import scripts.js 
```
let dataVal=0;
let testVar = 1;
let displayOffArr ={};
setTimeout(function(){
	//testVar = 2;
	//console.log('Wechsel vom Inhalt der Variable: '+testVar);
	window.Socket.subscribeState('0_userdata.0.jarvis.test.number', ({ err, state }) => {
		testVar = state.val;
		console.log('testVar: '+testVar);

		refreshDeviceState("bbea1d7b-d2ba-4c1f-9afd-ee0ab7f60065", "BesuchDa"); // aktualisiert das Binding im Gerät
	});
},10000);
```

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.31`

**Comment by mcuiobroker** [comment]
sieht Super aus. Danke.
