### ISSUE TITLE
Paypal-Anmeldung funktioniert nicht mehr

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1697]
Paypal-Anmeldung funktioniert nicht mehr. Wenn man sich dort anmeldet wird innerhalb vom Anmeldefenster(Paypal) nach Anmeldung jarvis angezeigt.
![image](https://user-images.githubusercontent.com/84818934/172156266-9bf8ed59-4b7b-4523-b7e6-69eb9e3444b2.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1147355144_

**Comment by Zefau** [comment]
Besteht das Problem noch?

**Comment by mcuiobroker** [comment]
Schau morgen mal nach

**Comment by mcuiobroker** [comment]
Auf dem Handy war es ok. Kann erst nächste Woche wieder normal testen.

**Comment by Zefau** [comment]
alles klaro, kein Stress

**Comment by mcuiobroker** [comment]
Ok. 
Mir ist aufgefallen, dass wenn man schon ein Abo hat, noch eins abschließen könnte. Eigentlich müsste es ausgeblendet werden?
Man dürfte nur noch das Abbestellen sehen?
![image](https://user-images.githubusercontent.com/84818934/185767794-655a2728-c149-4033-92b2-d1cf56b36a92.png)
Erst ab dem Zeitpunkt
![image](https://user-images.githubusercontent.com/84818934/185767810-c03d3263-d638-434a-9781-97b7b6426eae.png)
dürfte man die 
![image](https://user-images.githubusercontent.com/84818934/185767818-ddf18181-82b5-4c57-98cb-1e28f0d7a167.png)
![image](https://user-images.githubusercontent.com/84818934/185767847-4160809b-b992-4877-b81f-41ebd0459621.png)

sehen.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.40`
