### ISSUE TITLE
Calendar wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1698]
Calendar wird nicht korrekt angezeigt. Bei Eingabe vom Password wird das Passwort alphanumerisch im DOM angezeigt?
![image](https://user-images.githubusercontent.com/84818934/172250236-c8aa7875-035b-4ceb-9028-6b302457fcdb.png)
![image](https://user-images.githubusercontent.com/84818934/172250309-2975589b-efdc-4467-97c6-51d42642e0a3.png)
![image](https://user-images.githubusercontent.com/84818934/172250367-16b9089f-b068-44dc-b2b2-0340af893215.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1147938193_

**Comment by Zefau** [comment]
@mcuiobroker sollte mit `v3.1.0-alpha.17` wieder funktionieren (ggf. müssen die Passwörter neu eingegeben werden).

**Comment by mcuiobroker** [comment]
Wo soll das hin?
![image](https://user-images.githubusercontent.com/84818934/173685489-947433fd-7702-497d-beeb-35b6c706ec8b.png)

**Comment by mcuiobroker** [comment]
Es steht bei den Terminen immer "all day"?
Hier zum falschen Termin?
![image](https://user-images.githubusercontent.com/84818934/173688799-12a5ca4b-393b-409a-bddf-c9c16c4faab1.png)

**Comment by mcuiobroker** [comment]
Im Log steht
![image](https://user-images.githubusercontent.com/84818934/173699430-74208c43-0193-43b9-acb9-dd53979fdba2.png)

Besser wäre die id vom Widget, denn man evtl mehrere Calendar im Einsatz.
Warum wird 2x gelogged / refreshed?

**Comment by Zefau** [comment]
> Bei vielen Termine überlappt es den Bereich? overflow?
Kann man das einstellen -> automatisch bei overflow Scrollbalken?

Das ist ja die bekannte Option im Widget. Was hast du da konfiguriert?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/173832518-8ae83215-7d8c-4326-8805-34ddf9ba8d3e.png)
Wird jetzt plötzlich wieder umgesetzt? Vielleicht durch Upload?

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.22` behoben sein
- [x] https://github.com/Zefau/ioBroker.jarvis/issues/1698#issuecomment-1155690968
- [x] https://github.com/Zefau/ioBroker.jarvis/issues/1698#issuecomment-1155712955
- [x] https://github.com/Zefau/ioBroker.jarvis/issues/1698#issuecomment-1155769588
