### ISSUE TITLE
MediaControl mit Fehlermeldung

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1699]
Auf einer Seite mit MediaControl kommt diese Meldung:
![image](https://user-images.githubusercontent.com/84818934/172249183-f0ad8d0b-5a68-4826-be5a-1e6d792958ec.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1147930537_

**Comment by Zefau** [comment]
schau mal bitte mit `v3.1.0-alpha.34`

**Comment by mcuiobroker** [comment]
Kommt keine Meldung mehr. ok.

**Comment by mcuiobroker** [comment]
Nach F5 ... 
![image](https://user-images.githubusercontent.com/84818934/185771679-549a0053-be65-4929-8dc1-d6ccf1b0d2fe.png)

Bis die Anzeige erscheint dauert es ca. 7-8 Sekunden? Gibt es dafür einen Grund, die DPs, die abgefragt werden sind gefüllt und direkt verfügbar? Bei den anderen DP-Abfragen dauert es nur insgesamt 1-2 Sekunden.

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by mcuiobroker** [comment]
Nach F5 braucht er 13 Sekunden, um die DPs zu lesen?
Die Fehlermeldung kommt nicht mehr.

**Comment by mcuiobroker** [comment]
Wegen der Lautstärke wäre die Idee, dort auf der Fläche vom MediaControl das Mausrad bzw. Touchmove abzufragen und bei Down-Bewegung (oder Scrollrad bei Maus runter) die Lautstärke zu reduzieren. Und entsprechend umgekehrt für Lautstärke rauf.

Ist ja immer `alexa2.0.Echo-Devices.AusgewähltesDevice.Player.volume`
Feature Request?

**Comment by mcuiobroker** [comment]
Control-Tasten bei Musiktitel fehlen: (Nächter / Vorheriger / Shuffle)
![image](https://user-images.githubusercontent.com/84818934/193393872-cd927f88-752e-44c3-a5ad-1086c947b72e.png)
So sieht normalerweise nur bei Radioprogrammen aus.

**Comment by mcuiobroker** [comment]
zur Info mit `v3.1.0-alpha.54` dauert es jetzt ca 26 Sekunden, nach Aufruf der Seite mit MediaControl, bis er die Daten anzeigt.

- [ ] Wovon ist die Farbe vom Icon  abhängig, war sonst lila / violett 
![image](https://user-images.githubusercontent.com/84818934/193480345-69f86982-4e77-41f1-9294-5df1032c2899.png)

**Comment by Zefau** [comment]
> Wegen der Lautstärke wäre die Idee, dort auf der Fläche vom MediaControl das Mausrad bzw. Touchmove abzufragen und bei Down-Bewegung (oder Scrollrad bei Maus runter) die Lautstärke zu reduzieren. Und entsprechend umgekehrt für Lautstärke rauf.

> Ist ja immer alexa2.0.Echo-Devices.AusgewähltesDevice.Player.volume
und bei spotify-premium: spotify-premium.0.player.volume
Feature Request?

Ja, mach gerne auf. v3.1 ist Feature freeze.

**Comment by Zefau** [comment]
>  Wovon ist die Farbe vom Icon abhängig, war sonst lila / violett

Sollte noch so sein. Ist bei mir auch noch so (im White sowie im Dark Mode). Ggf. aufgrund deiner Styles?

**Comment by Zefau** [comment]
Schau nochmal mit `v3.1.0-beta.3` bzgl. der Buttons. Hat sich die Performance ggf. gebessert? Weiß nicht wirklich, was da schief läuft.

**Comment by mcuiobroker** [comment]
Nein, Performance weiterhin bei ca 30 Sekunden für das erstmalige Laden. Buttons sind da, haben aber Doppel:hover?
shuffle is on und off auf einem Icon?
![jarvis-MediaControl-Dopelhover](https://user-images.githubusercontent.com/84818934/197364229-43ef7cf2-8b44-4f2e-8d19-36655f44e629.gif)

**Comment by Zefau** [comment]
Das mit dem Icon und dem Tooltip sollte inzwischen behoben sein. Bei der Performance bin ich etwas ratlos.

**Comment by mcuiobroker** [comment]
Du liest doch nur die DPs? Oder wird sonst noch was zeitraubendes gemacht? Kannst du den Code zeigen?

**Comment by mcuiobroker** [comment]
Übersetzung fehlt noch bei den Schaltern?
![image](https://user-images.githubusercontent.com/84818934/200428475-e59908d8-46d5-42ed-8624-79175eeba7de.png)

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.17`
Übersetzung passt. Danke.
Keine Verbesserung bei der Zeit. ( Kann auch an meinem System liegen?)
Ich mach erstmal zu.
