### ISSUE TITLE
Layout configuration not available

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#17]
My layout is configured via JSON and working well in jarvis. When I try to change the configuration via the UI, it is not available in easy and raw configuration.

![layout_configuration](https://user-images.githubusercontent.com/2136249/77846001-3cb80900-71b3-11ea-8930-14a851715eca.png)

**Comment by Zefau** [comment]
What's your browser? Could you open the browser console and check for errors?

**Comment by braindead1** [comment]
I'm using Google Chrome. While testing it again, I noticed that the first time I open the layout tab the configuration is available. After closing and reopening the layout configuration it's gone.

The following screenshot shows the log after the first opening. The log does not change after closing and reopening.

![log](https://user-images.githubusercontent.com/2136249/77857289-d952c900-71fc-11ea-9e18-916a7a9a9863.png)

**Comment by Zefau** [comment]
Should be fixed with `v0.1.2`. Could you please test and verify? Thanks

**Comment by braindead1** [comment]
In v0.1.2 this works as expected.
