### ISSUE TITLE
Popup funktioniert manchmal nicht

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1701]
Popup funktioniert auch manchmal nicht.
![image](https://user-images.githubusercontent.com/84818934/172196797-ac5a5b61-c0d3-4513-9ebc-aa1a56a24905.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1147599937_

**Comment by Zefau** [comment]
Besteht das Problem noch? Kann du die Ursache eingrenzen?

**Comment by mcuiobroker** [comment]
Nein. Kann zu.
