### ISSUE TITLE
Dense Mode funktioniert nicht mehr

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1703]
Dense Mode funktioniert nicht mehr:
![image](https://user-images.githubusercontent.com/84818934/172262937-6c5f0ed6-d7ec-461c-ac6a-6683cfff8d71.png)
wird nicht angezeigt, nur noch:
![image](https://user-images.githubusercontent.com/84818934/172262989-b4da7491-c9cb-4bbd-8a81-1fff73b2a4eb.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1148014056_

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.15` sollte das Problem behoben sein

**Comment by Zefau** [comment]
Build Fehler. Bitte `v3.1.0-alpha.16`

**Comment by mcuiobroker** [comment]
Ok. Danke. Kann geschlossen werden.
