### ISSUE TITLE
Connection lost -> dauerhafte rote Anzeige (wie PRO-User-Anzeige)

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1704]
![image](https://user-images.githubusercontent.com/84818934/172453101-2bdc0854-54a0-41fa-ac20-cda206a5771c.png)

Solange bis re-subscribe erscheint
![image](https://user-images.githubusercontent.com/84818934/172453676-946b465e-f5f0-46f6-9334-42b1aa07dd8f.png)

**Comment by Zefau** [comment]
Ist das noch aktuell?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
Also wenn ich jarvis offen habe und den Adapter via ioBroker restarte, dann kommt in der Konsole:

![image](https://user-images.githubusercontent.com/14368811/175830713-7fb27177-6b07-4eeb-9b9b-12bc50388b06.png)

Was soweit auch korrekt ist. Die jarvis Seite bleibt normal offen, ohne rot.

Kannst du das mal giffen?

**Comment by mcuiobroker** [comment]
War meine eigene Socket Verbindung von damals.
![image](https://user-images.githubusercontent.com/84818934/175831056-a69c0abc-898d-4ea8-8fae-f28a02bce3e1.png)
Dann mach ich mal zu.
