### ISSUE TITLE
Handy Scrollfunktion bzw. Auf-/Abwischen ist deaktiviert?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1705]
v3.1.0-alpha.12
Man kann auf dem Handy die TAB-Seite nicht nach unten scrollen bzw. wischen.

**Comment by Zefau** [comment]
funktioniert es nun mit `v3.1.0-alpha.29` ?

**Comment by mcuiobroker** [comment]
Ja.
