### ISSUE TITLE
Safari HomeScreen Link not working with IOS 15.5

### ISSUE THREAD

**Issue by Sempre** [Zefau/ioBroker.jarvis#1708]
- Jarvis Version 3.0.11 (stable)
- Weißer Bildschirm ohne irgendeinen Inhalt

Seit dem Update auf IOS 15.5 ist es nicht mehr möglich einen Link auf den HomeScreen zu legen bzw. dieser zeigt nur eine weiße Seite an und keinen Inhalt. In anderen Browsern (Firefox / Chrome) funktioniert der Zugriff es scheint also nur im Vollbildmodus des Safari nicht mehr zu funktionieren. Auch ein aufruf der Seite in Safari direkt lädt sich zu Tode und es wird kein Inhalt dargestellt.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/172712343-49b703df-d270-44d9-93ea-a96525ea6d35.png)
Schon Website-Daten gelöscht?

**Comment by Sempre** [comment]
Hi,

clear History and Website Data habe ich nicht getestet wo gibt es denn die Option? Habe im Safari und dem Adapter geschaut und nichts gesehen.

Habe dann aber da Thema mit dem Limit IP Adresse Tracking getestet und das hat zum Erfolg geführt. Was mich wundert einmal aus und schon ging es. Ich hätte erwartet wenn ich die Option wieder einschalte das ich es dann reproduzieren kann, aber auch mit wieder eingeschalteter Option funktioniert es weiterhin, sehr komisch.

**Comment by mcuiobroker** [comment]
Website-Daten löschen:
Einstellungen -> Safari -> Verlauf und Websitedaten löschen

**Comment by Sempre** [comment]
Danke!!

Das Problem scheint aber mit dem Tracking zusammen zu hängen. Hatte das Problem gestern erneut und nachdem ich die Option ausgeschalten habe ging es dann sofort wieder. Scheinbar tritt es erst wieder auf wenn man das WLAN verlassen hat und sich dann zu einem späteren Zeitpunkt wieder in das WLAN einwählt. Ich habe nun mal alle Websitedaten gelöscht und die Option wieder aktiviert. Ich beobachte ob es nun erneut auftritt oder nun behoben ist.

**Comment by Zefau** [comment]
@Sempre @mcuiobroker ist hier noch was offen? 

> Das Problem scheint aber mit dem Tracking zusammen zu hängen

jarvis trackt nichts. Lediglich Sentry sendet Fehlerdaten, aber das ist abschaltbar.
