### ISSUE TITLE
Inputfelder funktionieren am Handy nicht

### ISSUE THREAD

**Issue by Coalado** [Zefau/ioBroker.jarvis#1709]
v 3.0.11
Ich habe eine Gerät mit einem Number Datenpunkt, und habe als Action in der Statelist "Input" gewählt. 
Am PC gebe ich die Zahl ein, drücke Enter, und der Wert wird übernommen. Unter Android gebe ich den Wert ein, drücke "enter", und der Wert wird nicht übernommen. Der Fokus springt aber zum nächsten Feld.

**Comment by Coalado** [comment]
![Screenshot_2022-06-08-23-19-20-333_com android chrome](https://user-images.githubusercontent.com/21013026/172719449-ac6fffa8-e621-4bf9-8210-74d2bec15390.jpg)

**Comment by Coalado** [comment]
Chrome geht nicht Firefox geht. Xiaomi note 10. Ich denke das müsste die Google Tastatur sein.

**Comment by sten-tor** [comment]
@mcuiobroker @Coalado Ich habe das Problem bei zwei anderen Geräte/Tastatur-Kombinationen auch. Das Problem besteht darin, dass die Return-Taste automatisch zu einer Tab-Taste wechselt. Beim letzten Eingabefeld bleibt es bei Return und dort ist die Eingabe möglich. 

<img width="431" alt="image" src="https://user-images.githubusercontent.com/92914169/174986357-df60dfaa-ca82-43a6-84b4-0cee69f4a491.png"><img width="429" alt="image" src="https://user-images.githubusercontent.com/92914169/174986192-146b94e1-3f19-4217-888a-01d3fecb858a.png">

**Comment by MaxZelmer** [comment]
Ich kann das Problem mit meinem Google Pixel 4a und einem sauberen Android bestätigen.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/tipps/allgemein/android#probleme-bei-der-eingabe-inputaction

**Comment by Zefau** [comment]
prüft mal bitte mit `v3.0.12`

**Comment by mcuiobroker** [comment]
v3.0.12 Keine Verbesserung.

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.24`

**Comment by mcuiobroker** [comment]
Weiterhin keine Verbesserung, es kommt in der Tastatur "Weiter" und nicht "return, öffnen".

**Comment by mcuiobroker** [comment]
https://user-images.githubusercontent.com/84818934/179425051-eb847427-e0af-4fb6-9b3c-a375bc8cad1e.mp4

**Comment by mcuiobroker** [comment]
Setz doch mal bitte den `type` auf `search`
![image](https://user-images.githubusercontent.com/84818934/179426271-a94b6c61-352e-4165-baeb-510833f777af.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.25`

**Comment by mcuiobroker** [comment]
Jetzt wird der Wert gesetzt.
