### ISSUE TITLE
Tab reagiert nicht

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1710]
Maus reagiert nicht. Klicken auf TAB nicht möglich.
![image](https://user-images.githubusercontent.com/84818934/172724822-3fe50b0e-05a7-4c4d-a887-eef8f290f7de.png)
Klickt man nach einiger Zeit dann auf ein TAB, wird nicht umgeschaltet.
Der RangeError kommt dann immer 2x, nachdem man auf einen anderen TAB klickt.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1670#issuecomment-1150458889_

**Comment by Zefau** [comment]
@mcuiobroker Ich gehe davon aus, dass das nicht bei jedem Tab passiert oder? Sondern nur bei Tabs mit bestimmten Modulen oder ggf. bei Tabs mit Geräten, die ein Binding haben?

**Comment by mcuiobroker** [comment]
Kommen jetzt auch solche Meldungen:
![image](https://user-images.githubusercontent.com/84818934/172924388-0d90e12b-573c-4d2b-a196-0f1acc4725d3.png)
Jetzt gerade ein Fall:
Nach F5 direkt auf anderen TAB geschaltet und wurde angezeigt, bleibt dann aber im Nirwana stehen.

Anderer TAB
Ist auf dem TAB ein DP nicht korrekt kommt anscheinend inconsistent?
![image](https://user-images.githubusercontent.com/84818934/172925238-aacd8d21-496d-44e9-889f-f16802865994.png)
![image](https://user-images.githubusercontent.com/84818934/172925334-672e90da-ad82-4ccb-8049-d5c20deadd71.png)

**Comment by Zefau** [comment]
Also hat sich das Issue erledigt?

Kannst du nochmal die fehlerhafte Konfiguration teilen, damit ich das ggf. jarvis-seitig vorbeugen kann?

**Comment by mcuiobroker** [comment]
Nein, noch nicht. Das waren unterschiedliche Fälle.
Ich warte erst auf v3.1.0-alpha.16. Und dann weiter.

**Comment by mcuiobroker** [comment]
Jetzt kommt eine neue Variante von Meldungen:
![image](https://user-images.githubusercontent.com/84818934/173147237-5e741e88-e2cc-4c6c-9350-0f6330181b34.png)

**Comment by mcuiobroker** [comment]
Läuft insgesamt langsamer beim F5 Neuladen.
PRO-Meldung wird noch nicht angezeigt? User ... ist PRO.

**Comment by Zefau** [comment]
`getBindings` ist von mir für's debuggen. Die Geschwindigkeit bei mir ist besser geworden und mich wundert, warum bei den meisten anderen scheinbar nicht.

Pro sollte ebenfalls normal funktionieren.

**Comment by mcuiobroker** [comment]
Pro scheint erstmal zu funktionieren, es kommt nur keine Meldung mehr , dass man PRO ist.
![image](https://user-images.githubusercontent.com/84818934/173150372-28906a30-22fa-4853-b013-44c67cdb369c.png)

**Comment by Zefau** [comment]
Hast du es in den Einstellungen ggf. so aktiviert?

![image](https://user-images.githubusercontent.com/14368811/173150518-3f756670-db31-429c-bb44-bb791f70458f.png)

**Comment by mcuiobroker** [comment]
Ja.
![image](https://user-images.githubusercontent.com/84818934/173150637-7c0ed8f7-2232-4b4f-8b1c-5013fac679a6.png)
Aber trotzdem kam im DOM immer die Anzeige trotzdem, unabhängig vom Schalter.

**Comment by Bernd9000** [comment]
Bei mir ist die Geschwindigkeit jetzt auch schnell nachdem ich die Bindings in jarvis korrigiert hatte.
Müßte bei den Bindings überall das Hochkomma einsetzen.
TAB wechsel lief nach der Korrektur ohne F5 zu drücken.
Nur ein spezieller TAB und bei "Konfiguration & Hilfe" muß ich noch F5 drücken.

**Comment by Bernd9000** [comment]
> @Bernd9000 Waren die Bindings alle für `string` Werte? Oder hast du es auch bei `boolean` und `number` Vergleichswerten gesetzt

Waren alle für string Werte

**Comment by Zefau** [comment]
kann das hier zu oder ist noch etwas offen?

**Comment by mcuiobroker** [comment]
War oben weiter hat nicht direkt mit Theam zu tun? Neuen Issue?
![image](https://user-images.githubusercontent.com/84818934/189202598-ba8cafdd-1564-47b6-9981-472ab353a530.png)
Kannst bei den Fehlern den Namen von der StateList und den devState mit angeben?

**Comment by Zefau** [comment]
Schau nochmal in der aktuellen Alpha. Da sollte etwas mehr Log stehen. Was steht da bei dir nun?

**Comment by Zefau** [comment]
Lass uns das Thema hier https://github.com/Zefau/ioBroker.jarvis/issues/1796#issuecomment-1200398490 weiter verfolgen, da wir uns dort schon darüber ausgetauscht hatten
