### ISSUE TITLE
DOM-Logs in jarvis.0.clients.192-168-178-115_Android-Browser.logDOM schreiben

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1711]
Logs vom Browser in den noch nicht genutzten LOG-DP `jarvis.0.clients.192-168-178-115_Android-Browser.logDOM` schreiben. Damit können auch "normale" User, von ioBroker aus ,  erkennen, dass etwas im Browser falsch läuft.
![image](https://user-images.githubusercontent.com/84818934/173098861-e5f9a347-baa1-4f59-923f-5078fca03151.png)

Definierbar in jarvis-Einstellungen (nur Fehler, nur Fehler und Warnungen oder all, bzw. System oder eigene LOGs von Scripts z.B.), Inhalt täglich löschen?

![image](https://user-images.githubusercontent.com/84818934/173099392-5d57156b-ccf2-4ed3-acc0-9f13382adcd4.png)

Zusätzlich Infos über die Ladezeiten in ein INFO Verzeichnis.
Dort können dann die Ladezeiten, die im DOM angezeigt werden auch als Vergleichsmöglichkeit dienen.
![image](https://user-images.githubusercontent.com/84818934/174423328-a1f36ffa-5d2f-45d0-a508-fd60b4d94fde.png)
![image](https://user-images.githubusercontent.com/84818934/174423332-1ec624ea-cc01-4834-bf7d-d47b9f84cc17.png)
![image](https://user-images.githubusercontent.com/84818934/174423337-78e52ba6-d6b4-4efe-ab37-2524067d7110.png)
![image](https://user-images.githubusercontent.com/84818934/174423346-5b69b2d7-5c55-4807-a9fb-0bf6dc7bb75f.png)
![image](https://user-images.githubusercontent.com/84818934/174423355-eb03640f-a6e3-4bc1-961d-24683931e3a1.png)

**Comment by mcuiobroker** [comment]
Hat sich mit v3.2.0-alpha.47 erledigt.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2550
