### ISSUE TITLE
v3.1.0-alpha.16 openToolTip undefined error

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1715]
![image](https://user-images.githubusercontent.com/84818934/173197653-44a55913-dceb-4fa0-8a1b-f021325adbf3.png)

**Comment by Zefau** [comment]
@mcuiobroker sollte mit `v3.1.0-alpha.17` wieder funktionieren (ggf. müssen die Passwörter neu eingegeben werden).

**Comment by mcuiobroker** [comment]
Es kommt:
![image](https://user-images.githubusercontent.com/84818934/173829973-4f135203-aeee-4fd1-aa8b-9921b06b1731.png)

**Comment by mcuiobroker** [comment]
MAP?
![image](https://user-images.githubusercontent.com/84818934/175773746-0ae56ade-c294-4f93-b80e-c40bae94812c.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.22` behoben sein

**Comment by mcuiobroker** [comment]
Es kommt noch:
![image](https://user-images.githubusercontent.com/84818934/176310925-d3ad90df-f526-4f38-b6d9-9365830325a9.png)

**Comment by Zefau** [comment]
Wann kommt es zu der Fehlermeldung? Tritt diese nach einer bestimmten Aktion auf? Ich kann es leider nicht nachstellen.

Gibt es negative Auswirkungen aufgrund der Fehlermeldung?

**Comment by mcuiobroker** [comment]
Zurzeit nicht. Ich beobachte es weiter. Schließe erstmal.

**Comment by mcuiobroker** [comment]
Zu früh, beim Wechsel von einer MAP-Seite zu einer anderen Hauptseite kommt jetzt
![image](https://user-images.githubusercontent.com/84818934/183761594-b927cbb5-dac0-47d4-8c9e-f2375062d18e.png)

**Comment by Zefau** [comment]
@mcuiobroker kann das hier zu?

**Comment by mcuiobroker** [comment]
Ja, kommen keine Meldungen mehr.
