### ISSUE TITLE
v3.1.0 : Rolladen Problem

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1716]
`v3.1.0-alpha.16`
Enthält ein Widget ein Rolladen als Gerät, erscheinen folgende Fehlermeldungen in der Browser Konsole:

TypeError: CSS2Properties doesn't have an indexed property setter for '0'

Eventuell javascript Problem?

Betriebssystem: Windows 10
NODE.js: v16.15.1
NPM: 8.11.0
JS Controller: 4.0.23
Admin: 6.0.3

![Unbenannt](https://user-images.githubusercontent.com/77005685/173230430-1b2f00e3-13f6-453b-8c81-d77a88ff9c8f.jpg)

**Comment by Bernd9000** [comment]
Datenpunkteigenschaft {"stop":"stop"} für BlindLevelAction:

Der Wert `stop,` der geschickt wird, kann über die Datenpunkt Eigenschaften nicht verändert werden.
Eingetragen ist der Wert bei Datenpunkt-Eigenschaften beim BlindLevelAction .
Es wird immer `true` gesendet.

![Unbenannt](https://user-images.githubusercontent.com/77005685/173290975-28f6135c-cce5-43ff-bb8b-6c7790cb93d2.jpg)

**Comment by Zefau** [comment]
@Bernd9000 kannst du mir die Styles des Geräts mal als Text reinpasten? Also Icon Style, Body Style und State Style (sofern vorhanden)

**Comment by Bernd9000** [comment]
Hier mal die Komplette Geräte Konfiguration, Styles sind entfernt weil es daran nicht liegt.
1.) "Test Rolladen" ist ein neu angelegtes Gerät das funktioniert.
2.) "Test Rolladen 2" ist eine Datenübernahme aus V3.0.11 und Stop Taste funktioniert nicht und TypeError: CSS2Properties

"b9cc9afe-5629-4458-ae50-29f2784569d3": {
    "name": "Test Rolladen",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "stop": {
        "stateKey": "stop",
        "showState": true,
        "state": "0_userdata.0.Shelly.Shelly-25-Reserve.command.Aktiv",
        "actionElement": "IconButtonAction"
      },
      "activity": {
        "stateKey": "activity",
        "showState": true,
        "state": "0_userdata.0.Shelly.Shelly-25-Reserve.Stop"
      },
      "level": {
        "stateKey": "level",
        "showState": true,
        "state": "0_userdata.0.Shelly.Shelly-25-Reserve.Position",
        "unit": "",
        "actionElement": "BlindLevelAction",
        "properties": {
          "stop": "stop"
        },
        "stateStyle": "",
        "icon": "",
        "display": "",
        "iconStyle": "",
        "action": "0_userdata.0.Shelly.Shelly-25-Reserve.command.Position"
      }
    },
    "options": {},
    "attributes": {},
    "id": "b9cc9afe-5629-4458-ae50-29f2784569d3",
    "revision": "2a038"
  },

---------------------------------------------------------------------------

 "shelly2.5reserve_dddc7_199c4": {
    "name": "Test Rolladen 2",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "stop": {
        "action": "",
        "actionElement": "IconButtonAction",
        "stateKey": "stop",
        "state": "0_userdata.0.Shelly.Shelly-25-Reserve.command.Aktiv",
        "bodyElement": null,
        "properties": "",
        "showState": true,
        "BlindLevelActionConfig": {
          "val": "value"
        },
        "display": ""
      },
      "activity": {
        "state": "0_userdata.0.Shelly.Shelly-25-Reserve.Stop",
        "actionElement": null,
        "action": "",
        "display": "",
        "stateKey": "activity",
        "properties": "",
        "showState": true
      },
      "level": {
        "state": "0_userdata.0.Shelly.Shelly-25-Reserve.Position",
        "action": "0_userdata.0.Shelly.Shelly-25-Reserve.command.Position",
        "actionElement": "BlindLevelAction",
        "stateKey": "level",
        "stateStyle": "",
        "display": "",
        "icon": "",
        "iconStyle": "",
        "properties": {
          "stop": "stop"
        },
        "unit": "",
        "showState": true
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Shelly",
        "namespace": "shelly"
      }
    },
    "id": "shelly2.5reserve_dddc7_199c4",
    "revision": "d3b0b"
  }

**Comment by Bernd9000** [comment]
Ich glaube Du hast recht.

Datenpunkt Stil im Schlüssel "level" macht Probleme:

{"0":{"color":"#F00"},"100":{"color":"#0F0"}}

**Comment by Bernd9000** [comment]
Einheit:
{"0":"","100":"","default":" %"}

Datenpunkt Stil:
{"0":{"color":"red"},"100":{"color":"green"}}

Anzeigevariante:
{"0":"Zu","100":"Auf"}

Datenpunkt Eigenschaften:
{"stop":"stop"}

Icon:
{"default":"window-shutter-alert","'{0_userdata.0.Shelly.Shelly-25-Reserve.Online}'='false'":"window-shutter-alert blink","<5":"window-shutter",">95":"window-shutter-open"}

Icon Stil:
{"default":{"color":"#F00"},"'{0_userdata.0.Shelly.Shelly-25-Reserve.Online}'='false'":{"color":"#FF0"},">5":{"color":"#0F0"}}

**Comment by mcuiobroker** [comment]
blindLevelAction Aussehen hat sich verändert:
v3.0.11
![image](https://user-images.githubusercontent.com/84818934/174456156-3e8d0304-63e5-483d-b836-c88e4157fdee.png)

v.3.1.0-alpha.17
![image](https://user-images.githubusercontent.com/84818934/174456147-45f333dc-812a-4aa3-a5f3-925934a197e6.png)

**Comment by Zefau** [comment]
besteht das Problem mit `v3.1.0-alpha.19` noch?

**Comment by mcuiobroker** [comment]
Vom Aussehen passt es wieder:
![image](https://user-images.githubusercontent.com/84818934/175749105-5694c6a6-0308-412d-ac55-922ce8977c40.png)

**Comment by Bernd9000** [comment]
`v3.1.0-alpha.20`
Problem noch vorhanden,
Gleiche Fehlermeldung in der Browser Konsole
Stop Taster läßt sich nicht betätigen.

Datenpunkt Stil:
{"0":{"color":"red"},"100":{"color":"green"}}

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.21`

**Comment by Bernd9000** [comment]
`v3.1.0-alpha.21`
Stop Taster funktioniert jetzt gar nicht mehr.
Weder mit "echten" Geräten noch mit der "blind-Simulation" von mcuiobroker.

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.22` behoben sein

**Comment by mcuiobroker** [comment]
Statewert Anzeige? Wo kann man noch schauen?
![image](https://user-images.githubusercontent.com/84818934/175835085-59da70fe-2343-474f-a219-dc036a30c5f9.png)
Gehört zu den Rolläden
![image](https://user-images.githubusercontent.com/84818934/175835100-f4cb4436-5879-46d6-8f99-412f0fe2a867.png)
![image](https://user-images.githubusercontent.com/84818934/175835116-b34687f7-f60a-417e-9557-2e0718cee822.png)

**Comment by Bernd9000** [comment]
@mcuiobroker
Wegen dem Statelist:
Hatte mit der "blind-Simulation" getestet, bei mir war der IOB Datenpunkt "activity" auf einmal kein Typ Boolean mehr sondern vom Typ string.Vielleicht liegt es daran.

@Zefau
Stop funktioniert leider immer noch nicht, vielleicht ist es auch nur bei mir so ?

**Comment by mcuiobroker** [comment]
@Bernd9000 Bei mir sind die Objekte STOP und Activity `boolean` und level `number`.

**Comment by Bernd9000** [comment]
Okay, bei mir ist der Statelist Fehler übrigens nicht vorhanden.

**Comment by mcuiobroker** [comment]
Hab es ohne Styles und Scripts versucht. Trotzdem bleibt die Anzeige auch nach F5.

**Comment by mcuiobroker** [comment]
ACK true gesetzt -> kann nicht wieder zurück auf false gesetzt werden.
![image](https://user-images.githubusercontent.com/84818934/175836055-2b175a9f-ed8c-4fd9-8f22-14b03f8f3800.png)

**Comment by Bernd9000** [comment]
Jo, hatte ich auch, ich mußte das Gerät neu anlegen

**Comment by mcuiobroker** [comment]
In der Alpha-Phase denkbar, aber nicht als stable Rollout?

**Comment by Bernd9000** [comment]
Mit der "blind-Simulation" kann man glaub ich aktuell nicht testen.
Da tauchen dann verschiedene Fehler im IOB Log auf:
![Unbenannt](https://user-images.githubusercontent.com/77005685/175836170-03ffa327-3274-43c3-a212-db76438509ba.jpg)

**Comment by Bernd9000** [comment]
stable Rollout ?

**Comment by mcuiobroker** [comment]
Das gehört nicht hierhin. Bitte in den Zusatzprogramm-Link gehen.

**Comment by Bernd9000** [comment]
Ich denke nicht das es am script liegt, sollte nur ein Hinweis sein falls jemand damit testet.

**Comment by Zefau** [comment]
Die Warnung deines Screenshots sagt, dass der State gar nicht existiert.

**Comment by Zefau** [comment]
@Bernd9000 Screenshote mir mal bitte deine Geräte Konfiguration insbesondere mit level, activity und stop. Und bitte auch die Kompetenzen Konfiguration von BlindLevelAction.

Ich hab Shelly's 2.5 und bei mir funktioniert der Stop Button.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1582

**Comment by Bernd9000** [comment]
@Zefau
Hab noch was herausgefunden:
Wenn ich nach jeder Aktion (Hoch, Runter, Stop, Level)  F5 im Browser drücke wird es richtig angezeigt und es funktioniert dann auch der Stop Button.Das heißt die Datenpunkte sind richtig aber es fehlt die Rückmeldung zum Client.
Der Fehler ist wohl seit `v3.1.0-alpha.21` ?

off-topic:
Das erklärt dann auch warum bei mir einige IconButtonAction aus anderen Geräten bei mir nicht mehr funktionieren.
Auch hier muß ich F5 drücken damit der aktuelle Zustand angezeigt wird

**Comment by Zefau** [comment]
@Bernd9000 ist das noch aktuell oder inzwischen behoben?

**Comment by Bernd9000** [comment]
Hab eben eine Testschaltung aufgebaut.
Funktioniert wieder.
Ich mach mal hier dicht.
