### ISSUE TITLE
Nach Update 3.1.0-alpha.16 keine Pro

### ISSUE THREAD

**Issue by mproper23** [Zefau/ioBroker.jarvis#1719]
Nach dem Update kommen lauter Meldungen mit:
Device (PC): Callback for "value" only available in Pro.

**Comment by mcuiobroker** [comment]
Schon mal ein Upload gemacht: `iob upload jarvis`

**Comment by mproper23** [comment]
ja ist windows Version.
den Upload command im Command Fenster?

**Comment by mcuiobroker** [comment]
Die neue v3.1.0-alpha funktioniert momentan nur mit Nodejs 16. siehe #1670

**Comment by mproper23** [comment]
Der Resscreen kam auch, aber nur wenn ich auf eine andere Seite/Tab gewechselt hab. muss das Update 3.1.0 Alpha.16 erst wieder installieren dann schick ich dir die Bwoser-Konsole

**Comment by mproper23** [comment]
![grafik](https://user-images.githubusercontent.com/25171131/173805577-e6158d7f-1792-44ff-b675-ad0132bf55bb.png)

**Comment by mproper23** [comment]
Update auf node.js 16 hab ich gemacht

**Comment by Zefau** [comment]
@mproper23 besteht das Problem mit der aktuellen alpha noch?

**Comment by mproper23** [comment]
Hallo,

aktuell bin ich nciht auf der alpha version. Könnte ich ne 2te Instanz machen? und diese auf die Alpha updaten?

**Comment by Zefau** [comment]
Nein, mit zweiter Instanz geht es leider nicht. Das lässt ioBroker nicht zu. Du brauchst eine zweite ioBroker Instanz.
