### ISSUE TITLE
Version:  3.1.0-alpha.17 Geräteimport nicht möglich

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#1720]
Hallo,

Geräteimport nicht möglich , keine Reaktion beim klick auf die Schaltfläche.

![Screenshot (4940)](https://user-images.githubusercontent.com/41079106/173687181-a1338697-c446-477a-b9bd-6dfb5724484c.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.18` wieder funktionieren

**Comment by sigi2345** [comment]
> sollte mit `v3.1.0-alpha.18` wieder funktionieren

Jupp, Danke.
