### ISSUE TITLE
Version: 3.1.0-alpha.17 Widgets keine Änderung, verschieben oder bearbeiten, löschen möglich

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#1721]
Hallo,

die automatisch erstellten Widgets lassen sich nicht bearbeiten, keine Reaktion.

Beim klick darauf friert Jarvis ein.

![Screenshot (4941)_LI](https://user-images.githubusercontent.com/41079106/173699981-d1a3cd59-3d8d-41f1-bfab-9e0713bf09da.jpg)

![Screenshot (4942)](https://user-images.githubusercontent.com/41079106/173700536-3e8d6021-d4de-42b3-a80b-e5f4dc68c838.png)

**Comment by Zefau** [comment]
bitte mit `v3.1.0-alpha.19` nochmal neu einlesen, dann sollte es funktionieren

**Comment by sigi2345** [comment]
> bitte mit `v3.1.0-alpha.19` nochmal neu einlesen, dann sollte es funktionieren

Jupp, geht wieder.
