### ISSUE TITLE
Einheiten - 3.0.12.beta.1

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1723]
Habe versucht die Einheiten zu setzten wie folgt: 

![image](https://user-images.githubusercontent.com/22169074/174037671-4437b05d-31d4-413a-bf7b-83425c8e7b6a.png)

![image](https://user-images.githubusercontent.com/22169074/174037795-b92e8968-6c3f-4ea1-b42e-d40ccf9fed3a.png)

Auch hier beschrieben:
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/system-effektprog./blindlevelupdown#einheit

Scheint nicht zu gehen.

**Comment by mcuiobroker** [comment]
Das angezeigte Programm im Link ist ein Zusatzprogramm, welches als Zusatz zum jarvis-Standard arbeitet. Dies soll nur für Fälle genutzt werden, wenn man BlindLevel-Taster für andere Funktionen (Temperatur-Steuerung, usw) genutzt werden soll. Also hier als Link nicht sinnvoll, da du kein `blindLevelAction` nutzt.
Du arbeitest mit `levelBody`.
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/geraet/body-element/levelbody

**Comment by ma-gu-16** [comment]
Ich möchte: 

geschlossen - 10 % - 20% - 30% - 40% - 50% - 60% - 70% - 80% - 90% - offen 

Das ging definitiv mal :-) Scheinbar nicht mehr bzw ich hoffe einfach anderst ;-)

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/geraet/body-element/levelbody#markerwerte-anfang-ende-setzen

**Comment by ma-gu-16** [comment]
Ok das klappt, Danke dir. 

Dachte mir fast das es plötzlich wo anderst ist :-) Werde alle meine Slider nun anpassen müssen.

**Comment by Zefau** [comment]
Was fehlt hier noch? Wenn es um die Rundung der Zahlen geht, bitte nochmal mit `v3.1.0-alpha.18` schauen.

**Comment by mcuiobroker** [comment]
Zahlen werden noch mit falscher Rundung angezeigt.

![image](https://user-images.githubusercontent.com/84818934/174501691-43e4cfec-53a7-47fe-ac47-4bf1dff2ba32.png)

**Comment by Zefau** [comment]
Was für ein Setup liegt dahinter?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/174534752-e73132ee-4432-4c05-b655-1757e30d8e9c.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.19` nun passen

**Comment by mcuiobroker** [comment]
Jetzt ist der Popup falsch:
Gerät-Def
![image](https://user-images.githubusercontent.com/84818934/175749366-4253a69a-e7e3-4a80-8d96-287e8dc0951e.png)
Gerät-Popup-Anzeige
![image](https://user-images.githubusercontent.com/84818934/175749484-07e583e2-f00b-4f9c-9598-db416e8d74e7.png)

Layout-Def
![image](https://user-images.githubusercontent.com/84818934/175749406-c0195ee9-7177-4003-9883-49c4c162e1eb.png)
Layout-Anzeige
![image](https://user-images.githubusercontent.com/84818934/175749446-09afdd9e-481c-424e-b404-0c2423563962.png)
Es fehlt 0 und 254-Anzeige. `aus`und `offen` werden nicht angezeigt.

**Comment by Zefau** [comment]
Ich schau's mir nochmal an.

Nur als Hinweis, weil du immer `254` nutzt. Die Skala sollte eigentlich von 0-255 gehen (256 insgesamt, da 2^8). Machen aber leider einige Adapter auch falsch.

**Comment by Zefau** [comment]
Für mich, da ich sonst immer wieder abtippe: `val => {if (val===0){return "aus";} if (val===254){return "offen";} }`

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.20`

**Comment by mcuiobroker** [comment]
Das sieht gut aus.
Layout:
![image](https://user-images.githubusercontent.com/84818934/175773968-346bfdc8-f7a0-4292-961e-5c6d86180d70.png)
Popup:
![image](https://user-images.githubusercontent.com/84818934/175773999-f4e267d4-eb40-4cca-81bd-1239d29a25b7.png)
