### ISSUE TITLE
Datetime Modul extra divs

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#1724]
![image](https://user-images.githubusercontent.com/22169074/174056899-cc12135f-9adb-4c58-9a38-d7c099d8c41b.png)

Wäre gut wenn man dem DateTime Ausgabe evtl das Datum und auch die Zeit in eigene Divs packt, so könnte man diese seperat via CSS formatieren. 

Fände es gut wenn die Uhrzeit Gross/Fett  und darunter das Datum. 

Solange flexbox, dann könnte man via order die Reihenfolge DAtum/Uhrzeit/Sonnenaufgang/ usw selbst setzten.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.22` eingeführt
