### ISSUE TITLE
Tab swipe eingeschaltet -> mobile kein Auf und abscrollen möglich

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1727]
Hat man TAB Swipe aktiviert
![image](https://user-images.githubusercontent.com/84818934/174426687-d2a3112e-cba9-4aba-b878-0e262352e3f0.png)
![image](https://user-images.githubusercontent.com/84818934/174426703-24b6b4f2-9d13-4255-aeb8-0385e33e91bc.png)
kann man auf dem Handy keine Seiten mehr scrollen(rauf/runter).

**Comment by TZanke** [comment]
Meinst du dieses Verhalten, oder noch was ganz anderes?

**Comment by mcuiobroker** [comment]
Nein. Wie hast du das denn hinbekommen?
Kannst du dort innerhalb von einem Widget scrollen?

**Comment by Zefau** [comment]
Glaube er hat die Option im Tab für Dashboard / 100% Höhe aktiviert

**Comment by TZanke** [comment]
@Zefau genau, also eigentlich will ich das aber gar nicht. Abschalten oder anschalten macht aber keinen unterschied bei der Option. Dann mach ich mal ein neues Ticket auf. Danke.
