### ISSUE TITLE
@import für CSS 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1728]
Unterstützung von `@import url("http://192.168.178.70/farbe.css')`
Damit lassen sich Projekt CSS besser unterscheiden.

**Comment by Zefau** [comment]
Das sollte eigentlich funktionieren. Geht es nicht? Was passiert, wenn du `@import` nutzt?

**Comment by mcuiobroker** [comment]
Nix.
![image](https://user-images.githubusercontent.com/84818934/175830408-cb7e6ddb-f709-40f0-b29b-c75728cc8b90.png)

**Comment by Zefau** [comment]
füg mal direkt im Datenpunkt in ioBroker hinzu und umgeh die Validierung

**Comment by mcuiobroker** [comment]
Zieht nicht, müsste blau sein.
![image](https://user-images.githubusercontent.com/84818934/175830530-4fa18f8c-4f39-494b-b571-1ea7e48567d7.png)

**Comment by Zefau** [comment]
Bei deiner Syntax fehlt ein `;` am Ende, dann wirft der Editor keinen Fehler mehr aus. Das parsen funktioniert aber der nächsten alpha.

**Comment by mcuiobroker** [comment]
Auf Änderungen in den CSS-Dateien wird dann aber nicht reagiert, oder?

**Comment by Zefau** [comment]
Jaein. Also beim Ändern der CSS-Dateien die durch Import eingebunden werden, wird nichts geändert. Ich bekomm hier ja technisch die Änderung nicht mitgeteilt (bei den ioBroker Datenpunkten bekomme ich dies ja gepushed).

Wenn die Konfiguration gespeichert wird, werden die `@import`'s aber neu geladen.

**Comment by Zefau** [comment]
implemented with `v3.1.0-alpha.26`

**Comment by mcuiobroker** [comment]
Funktioniert. Danke.
