### ISSUE TITLE
add new module MediaControl

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#173]
add new module to display and control Multimedia contents, e.g. Spotify, Plex, Alexa, etc.

- [x] Spotify
- [x] Alexa2
- [x] Plex

**Comment by Zefau** [comment]
> Sorry for the next new idea, but your adapter is so fantastic, I always think about new ideas to visualise in my personal Jarvis.

> First step could be the integration of a very simple Player visualisation with play/pause/skip options and maybe a cover section. I'm thinking of a simple interface for controlling services like Sonos, TuneIn, Amazon Music etc... Datapoints are coming manually from different adapters and have to be assigned by the user.

> 2nd step or even a Pro-Feature could be a more detailed player with library search or playlist function using datastructure of common brands as Sonos, Bose, Yamaha or so... I guess Step 2 is quite hard in programming compared to Step 1.

**Comment by Zefau** [comment]
added with `2.2.0-beta.1`.

Missing:
- [ ] Adjusting volume
- [ ] Multiplayer support

**Comment by duczz** [comment]
Bitte noch die Deviceauswahl von Spotity mit aufnehmen (Sprich an welchem Gerät es abgespielt werden soll, oder fällt das bei dir mit unter Multiplay Support?)
spotify-premium.0.devices

**Comment by o0shojo0o** [comment]
Wird es auch eine Sonos Unterstützung geben?

**Comment by Zefau** [comment]
Für Sonos brauche ich einen Screenshot der Adapter Struktur

**Comment by o0shojo0o** [comment]
Reicht dir das so? 
![image](https://user-images.githubusercontent.com/19333515/103937452-0f788e00-5129-11eb-94fb-c088a1a2119e.png)

**Comment by Zefau** [comment]
Jo

**Comment by florian84z** [comment]
> added with `2.2.0-beta.1`.
> 
> Missing:
> 
> * [ ]  Adjusting volume
> * [ ]  Multiplayer support

sehr cool! aber wo genau ist die PlayerID von Spotify/Alexa zu finden?

**Comment by Zefau** [comment]
Spotify braucht keine. Steht auch in der Info. Dort wird immer der letzte genommen (`spotify-premium.0.player`).

Alexa2 die ID unter `alexa2.0.Echo-Devices`

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/555662
> im Media Player Widget passt die „Zeit“ nicht. Ragt über das Widget hinaus. Siehe Screenshot
![image](https://user-images.githubusercontent.com/14368811/104134829-587c4c80-538c-11eb-95b0-f8b5e2395bec.png)

**Comment by Zefau** [comment]
added multiplayer and player selection support with `v2.2.0-beta.12`.

**Comment by duczz** [comment]
Play selection ist ohne Funktion, vermutlich gehst du nicht auf die useForPlayback OID

spotify-premium.0.devices.xxxxxxx.useForPlayback

**Comment by Zefau** [comment]
Doch, es wird `useForPlayback` angesprochen:

```
{
	"_namespace": "",
	
	// information
	"artist": ".player.artistName",
	"album": ".player.album",
	"track": ".player.trackName",
	"year": null,
	"cover": ".player.albumImageUrl",
	
	// actions
	"play": {
		"state": ".player.isPlaying", // isPlaying
		"action": ".devices.{PLAYER}.useForPlayback"
	},
	"pause": {
		"action": ".player.pause"
	},
	"resume": {
		"action": ".play"
	},
	"stop": {
		"action": null
	},
	"previous": {
		"action": ".player.skipMinus"
	},
	"next": {
		"action": ".player.skipPlus"
	},
	
	// attributes
	"progress": {
		"state": ".player.progress",
		"convert": convertToSeconds,
		"action": ".player.progressMs",
		"setter": seconds => {
			return seconds * 1000
		}
	},
	"duration": {
		"state": ".player.duration",
		"convert": convertToSeconds
	},
	
	// options
	"repeat": {
		"state": ".player.repeat",
		"action": ".player.repeat",
		"display": {
			"off": "off",
			"item": "track",
			"all": "context"
		}
	},
	"shuffle": {
		"state": ".player.shuffle",
		"action": ".player.shuffle",
		"display": {
			"off": "off",
			"on": "on"
		}
	},
	"volume": {
		"state": ".player.device.volume",
		"action": ".player.device.volume",
		"display": {
			"off": 0
		}
	}
}
```

**Comment by JayRHa** [comment]
Funktioniert auch bei mir nicht zuverlässig. Manchmal geht es und manchmal nicht

**Comment by zucki** [comment]
Ich hatte nachgefragt ob man das Widget auch den musiccast Adapter [(GitHub Link](https://github.com/foxthefox/ioBroker.musiccast)) unterstützen könnte. Wie gewünscht ([Foren Post](https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/2940?_=1610566098310)), hier die gemappte Aufstellung:
Allgemein besitzt der musiccast Adapter für alle Geräte ein Verzeichnis mit den Unterverzeichnissen _main_ und _netsub_ die interessant sind. Bei einigen Mappings hab ich als Kommentar noch offene Fragen eingefügt.

`{
	"_namespace": "",
	
	// information
	"artist": ".netusb.artist",
	"album": ".netusb.album",
	"track": ".netusb.track",
	"year": null,  // nicht verfügbar
	"cover": ".netusb.albumart_url",
	
	// actions
	"play": {
		"state": null, // mir ist nicht ganz klar was hier genau gemeint ist
		"action": null // hier ebenfalls
	},
	"pause": {
		"action": ".netusb.playPause"
	},
	"resume": {
		"action": ".netsub.playPause"
	},
	"stop": {
		"action": ".netsub.stop"
	},
	"previous": {
		"action": ".netsub.prev"
	},
	"next": {
		"action": ".netsub.next"
	},
	
	// attributes
	"progress": {
		"state": ".player.progress",
		"convert": convertToSeconds,
		"action": ".player.progressMs",
		"setter": seconds => {
			return seconds * 1000
		}
	},
	"duration": {
		"state": ".player.duration",
		"convert": convertToSeconds
	},
	
	// options
	"repeat": {
		"state": ".netsub.repeat_stat",
		"action": ".netsub.repeat",
		// "netsub.repeat" hat die role Button, ich weiß nicht ob der display
		// Abschnitt überhaupt nötig ist
		"display": {
			"off": "off",
			"on": "on"
		}
	},
	"shuffle": {
		"state": ".netsub.shuffle_stat",
		"action": ".netsub.shuffle",
		// hier gilt das selbe wie bei repeat
		"display": {
			"off": "off",
			"on": "on"
		}
	},
	"volume": {
		"state": ".main.volume",
		"action": ".main.volume",
		"display": {
			"off": 0
		}
	}
}`

Falls noch offene Fragen sind steh ich gern zur Verfügung :-)

**Comment by Zefau** [comment]
Kannst du mir noch ein Screenshot der Objekt-Struktur des Adapters posten, damit ich ein Gefühl für den Aufbau bekomme? Danke dir.

**Comment by zucki** [comment]
Gern

main:
![image](https://user-images.githubusercontent.com/4253035/104503364-3deee100-55e1-11eb-90a8-366d6000e711.png)

netsub:
![image](https://user-images.githubusercontent.com/4253035/104503291-257ec680-55e1-11eb-8ba8-38be311091f7.png)

**Comment by Zefau** [comment]
@zucki vielen Dank für deinen Support in dieser Sache.

Ich habe musiccast mit `v2.2.0-beta.15` hinzugefügt. Schau dir das mal an. Leider kann ich es nicht vortesten, da ich den Adapter nicht habe.
Eine Fortschrittsanzeige wirst du nicht haben, weil ich jetzt keinen Datenpunkt für den Fortschritt / Abspielzeit sehe? Nur die Gesamtlänge (`total_time`).

**Comment by zucki** [comment]
@Zefau Ich hab mal angefangen zu testen.

Zum Thema Fortschrittsanzeige. Es gibt unter _netusb_ den Wert _play_time_. Allerdings gibt der zumindest bei Net-Radio und Spotify nicht den Trackfortschritt sondern die gesamte Zeit seit der letzten Pause an. Außerdem ist das Aktualisierungsinterval des musiccast Adapters nicht allzu hoch. Ich denke es macht wenig Sinn den Wert zu nutzen. Ich muss es mal noch mit lokal gespeicherter Musik probieren. _total_time_ bleibt bei mir immer 0. Also auch der Wert scheint nicht verwendbar zu sein.

Ansonsten tut sich leider gar nichts.
![image](https://user-images.githubusercontent.com/4253035/104556596-2dba1e80-5640-11eb-8ad7-43f70a73ac05.png)

Die Datenpunkte werden aber in dem Versuch befüllt.
![image](https://user-images.githubusercontent.com/4253035/104557087-ef712f00-5640-11eb-92d7-24ddaf252a04.png)

Im Adapter kann es ja mehrere Geräte geben. Wie wird das denn im Widget dargestellt? Und beim anlegen des Mappings war mir ja nicht ganz klar was der Punkt "play" in den actions tut. Vielleicht ist da noch was falsch?
Es gibt übrigens den Datenpunkt .netusb.playback für jedes Gerät. Der wechselt zwischen Stop/Play/Pause je nach Status. Wird das Gerät ausgeschaltet wird auch Stop in den Datenpunkt geschrieben.

**Comment by duczz** [comment]
Wäre es auch möglich eine Album und Track Auswahl mit einzubauen?

**Comment by SaschaWeiher** [comment]
Hi Zefau, vorab vielen Dank für diesen tollen Adapter. Ich bewundere deine Arbeit. ;-)

Ich hätte zwei Anregungen zur Integration von Echo Devices über den Alexa2-Adapter. 

1. Echos lassen sich ja zu Lautsprecher-Gruppen zusammenfassen. Im Alexa-Adapter werden in diesem Fall die einzelnen Echos, sowie die konfigurierten Lautsprecher-Gruppen erkannt. Im Dropdown des Media Players in Jarvis werden nun Gruppen und Einzelgeräte ausgegeben. 

Es wäre genial, wenn man die im Dropdown anzuzeigenden Geräte eingrenzen könnte. Ich würde z. B. gerne nur meine Lautsprecher-Gruppen sehen, die einzelnen Echos sind mir wurscht.

2. Default Device Konfiguration: Die Auswahl eines Default Device wäre prima. Vorab haben wir je Device ein Media Player Widget konfiguriert. Nun benötigen wir nur noch ein Media Player Widget. 
In Jarvis suchen wir uns den Media Player und wählen über das Dropdown jedes Mal den gewünschten Player aus. Die Vorabdarstellung eines bevorzugten Devices wäre nicht nur für die Handhabung eine Bereicherung, ich denke auch das Design (Look&Feel) würde hiervon profitieren.

**Comment by Zefau** [comment]
@duczz Wüsste nicht wie. Eine Trackauswahl gibt es im Spotify Adapter so nicht, oder?

**Comment by Zefau** [comment]
@SaschaWeiher nehme ich für v2.3 auf die Agenda

**Comment by duczz** [comment]
@Zefau Über die OID "spotify-premium.0.html.tracks" lässt es sich via VIS steuern

**Comment by Zefau** [comment]
@JayRHa hast du den Fehler noch? Welche Version von Spotify hast du? Ich bekomme den Fehler nicht, bin aber auf dem stable repo.

**Comment by Zefau** [comment]
@duczz über `spotify-premium.0.html.tracks` lässt sich das nicht steuern. Der OID steht auf `write` `false` ?

**Comment by duczz** [comment]
@Zefau Richtig steht auf false
![tracklist](https://user-images.githubusercontent.com/25475385/105231027-83be2300-5b66-11eb-9f3f-014b132e5f0b.gif)

**Comment by Zefau** [comment]
@duczz ich bekomm den Datenpunkt gar nicht befüllt, wenn ich etwas abspiele. Muss ich da was machen?

**Comment by Zefau** [comment]
@duczz ich hab's mal für v2.3 aufgenommen: https://github.com/Zefau/ioBroker.jarvis/issues/616#issuecomment-763900928

**Comment by duczz** [comment]
Normal befüllt er sich automatisch, ich geh mal davon aus das du ne Playlist mit Tracks hast und den Adapter mit deinem Premium Acc verknüpft hast?

**Comment by duczz** [comment]
Also bei mir kann ich Spotify stoppen, aber nicht mehr mit play starten, hat das problem noch jemand?

**Comment by JayRHa** [comment]
> Also bei mir kann ich Spotify stoppen, aber nicht mehr mit play starten, hat das problem noch jemand?

Ja manchmal nicht immer läuft nicht so zuverlässig

**Comment by duczz** [comment]
Bezüglich des Play Buttons Problems, der Funktioniert bei mir nur wenn ich Play Drücke und dann das Lied wechsle, ansonsten tut sich da nix

**Comment by joerg2805** [comment]
Bei mir reagiert der PlayButton garnicht. Nur der NextTrackButton wechselt den Track und startet das Lied.

**Comment by simonssoftware** [comment]
> 
> 
> Play selection ist ohne Funktion, vermutlich gehst du nicht auf die useForPlayback OID
> 
> spotify-premium.0.devices.xxxxxxx.useForPlayback

Habe mit Spotify genau das gleiche Problem. Wenn ich versuche das Gerät zu wechseln kommt folgende Ausgabe im iobroker Log:
![grafik](https://user-images.githubusercontent.com/50638485/108105445-eaaef900-708c-11eb-8e2d-4b18795a4f25.png)

Auch geht bei mir der Play Befehl nicht, pausieren kann ich zwar aber dann nicht wieder starten.

Habe Version v2.2.0-beta.42 installiert.

**Comment by Zefau** [comment]
@simonssoftware @joerg2805 @duczz @JayRHa bitte schaut nochmal mit `v2.2.0-beta.43`, ob es damit besser geworden ist.

Sofern der Play-Button nicht funktioniert, bitte mal im ioBroker schauen, ob die Datenpunkte der Geräte unter `spotify-premium.0.devices` korrekt befüllt sind (insbesondere `.isAvailable`).

**Comment by duczz** [comment]
@Zefau Nope ist leider gleich geblieben

**Comment by Zefau** [comment]
Bitte mehr Infos. Geht's denn über den Spotify Adapter direkt? Wie sieht in ioBroker die Struktur aus? Sind die Player aktiv?

**Comment by duczz** [comment]
Über Spotify und Vis gehts einwandfrei. Player sind aktiv
![image](https://user-images.githubusercontent.com/25475385/108187533-db708f80-710e-11eb-880d-19cf4f3a80ee.png)

**Comment by joerg2805** [comment]
Keine Veränderung. Über den Spotify Adapter funktioniert es.

**Comment by Zefau** [comment]
bitte nochmal mit `v2.2.0-beta.46` probieren

**Comment by joerg2805** [comment]
Geht immer noch nicht. Unterschied zu vorher: Wenn man Play drückt verschwindet der Fortschrittsbalken für 2s. Ausserdem wird der Progress falsch angezeigt.

**Comment by simonssoftware** [comment]
Bei mir klappts leider auch nicht.

Wenn ich ein anderes Gerät auswähle, kommt immer noch der gleiche Fehler.
![grafik](https://user-images.githubusercontent.com/50638485/108593349-60f47980-7373-11eb-974e-a85a81f7fd60.png)

Ich hab mir oben mal deine Config für den Spotify Teil angeschaut, ich glaube da hat sich bei "resume" ein Fehler eingeschlichen, müsst die "action" nicht anstatt nur ".play" -> ".player.play" stehen?

Das Problem wie @joerg2805 es beschreibt hab ich nicht...

**Comment by Zefau** [comment]
probiert bitte nochmal `v2.2.0-beta.47`.

**Comment by simonssoftware** [comment]
Wiedergabe starten funktioniert jetzt, Spotify hängt sich in meinem Fall dann zwar auf, aber die Status im iobroker werden jetzt richtig gesetzt.

Bei Änderung des Wiedergabegerätes leider immernoch die gleiche Fehlermeldung 😕

**Comment by joerg2805** [comment]
Manchmal geht es, meistens jedoch springt er nun für 0.1s auf play und dann wieder von alleine auf pause. Die progress Zeit wird falsch angezeigt. Und ein klick auf den progress Balken springt nicht an die gewünschte Stelle, sondern wechselt den Track.

**Comment by Zefau** [comment]
Nicht ganz einfach. Den Fehler mit dem Klick auf den Progress-balken und springen zu einer bestimmten Stelle, den dann aber den Track wechselt, konnte ich bei mir nachstellen.

Das Wechseln des Wiedergabe-Geräts und den Fehler kann ich mir nicht erklären / nachstellen. Hab mal versucht das zu fixen, aber eher blind.

Auch, dass der Player nach dem Anschalten direkt wieder pausiert ist sehr merkwürdig. Und inwiefern wird die Progress-Zeit falsch angezeigt? Das wird bei jeder Aktualisierung aus ioBroker übernommen.

Versucht bitte nochmal die `v2.2.0-beta.49`.

**Comment by joerg2805** [comment]
Das Klicken in den Fortschrittsbalken funktioniert jetzt. Die Progress Zeit springt allerdings nicht auf die neue Zeit. Erst wenn die Seite neu geladen wird, stimmt die Zeit wieder. Von den Buttons (Start/Pause, Next, Previous) geht jetzt gar keiner mehr.

**Comment by duczz** [comment]
Bei mir geht der Play Button nun - Nice

**Comment by joerg2805** [comment]
Muss mich korrigieren. Jarvis Adapter, Web Adapter, Spotify Adapter neu gestartet, Browser Cache gelöscht: Jetzt geht alles, bis auf die Progress Anzeige.

**Comment by Zefau** [comment]
puh, ich war echt schon am verzweifeln ;-)

Der Wert kommt aus `spotify-premium.0.player.progress`. Aktualisiert dieser korrekt bei dir?

Welche Aktualisierung von Spotify hast du in den Adapter-Einstellungen drin?
![image](https://user-images.githubusercontent.com/14368811/108698800-cfb50c80-7504-11eb-9f1e-cffe9b845b93.png)

**Comment by joerg2805** [comment]
Der Wert spotify-premium.0.player.progress aktualisiert richtig. Die  Einstellungen des Spotify Adapters sind so, wie auf Deinem Bild oben.
Die Progress Anzeige entwickelt ein Eigenleben. Wenn ich mit Klick auf den Progress Balken irgendwohin springe, springt sie nicht mit, sondern zählt weiter hoch von ihrem bisherigen Wert. Nur wenn ich die Seite im Browser neulade, stellt sie sich auf den richtigen Wert.

**Comment by Zefau** [comment]
@joerg2805 mit `v2.2.0-beta.50` sollte es jetzt hoffentlich passen.

**Comment by joerg2805** [comment]
Vielen Dank für den Einsatz. Jetzt geht es.
