### ISSUE TITLE
echarts als iFrame kann nicht geladen werden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1731]
![image](https://user-images.githubusercontent.com/84818934/174459719-0eeed3c4-7a9d-46ec-a87d-01a03c166adf.png)
Dreht seine Runden
![image](https://user-images.githubusercontent.com/84818934/174459726-0f657ee5-c2b2-4049-95cd-515a2f4feaec.png)
![image](https://user-images.githubusercontent.com/84818934/174459745-085a4008-e5af-468b-bc6a-c03a47266dcc.png)
![image](https://user-images.githubusercontent.com/84818934/174459764-0b3d64ae-b6e8-41b8-9b8e-c726fb77a0e5.png)

**Comment by Zefau** [comment]
Der Fehler mit dem Socket kommt von Echarts Adapter. Bitte dort ein Issue aufmachen.

**Comment by Zefau** [comment]
Betrifft 3.0?

**Comment by Zefau** [comment]
Betrifft 3.0?

**Comment by sigi2345** [comment]
> Der Fehler mit dem Socket kommt von Echarts Adapter. Bitte dort ein Issue aufmachen.

https://github.com/ioBroker/ioBroker.echarts/issues/96#issuecomment-1159646140
