### ISSUE TITLE
Widget-Vergrößerung auch durch Doppelklick

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1732]
Für die Widget-Vergrößerung wurde ein kleines lila-Dreieck in der rechten oberen Ecke vom Widget eingeführt. Um einfacher ein Vergrößerung vom Widget zu bekommen, sollte auch ein Doppelklick auf die Überschrift vom Widget oder auf die freie Widgetfläche genutzt werden können.
Und das Dreieck sollte etwas größer sein, bzw festlegbar sein. Angabe von Pixelanzahl (Jetzt 16px )
![image](https://user-images.githubusercontent.com/84818934/174459944-1771ed79-3191-4fba-b039-b1eb5477b966.png)
25px
![image](https://user-images.githubusercontent.com/84818934/174459963-1ab206c3-aa51-4271-b67e-50a1679ab95f.png)
![image](https://user-images.githubusercontent.com/84818934/174459967-bd9c2fcd-3534-400c-8b67-8e2eb136fede.png)
-> Pixelanzahl

**Comment by Zefau** [comment]
Mit dem Doppelklick ist eine gute Idee. Die Größe kann mit CSS gemacht werden.

**Comment by Zefau** [comment]
Mit `v3.1.0-alpha.18` nun auch via Doppelklick auf das Widget

**Comment by mcuiobroker** [comment]
Funktioniert. Danke.

**Comment by mcuiobroker** [comment]
v3.1.0-alpha.22
Es funktioniert nicht mehr.

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.24`

**Comment by mcuiobroker** [comment]
Funktioniert leider nicht. Upload versucht -> auch nicht.

**Comment by Zefau** [comment]
Keine Fehlermeldung in der Browser Konsole?

**Comment by mcuiobroker** [comment]
Leider nein.

**Comment by Zefau** [comment]
Was genau funktioniert denn nicht? Geht es gar nicht erst auf?

**Comment by mcuiobroker** [comment]
Hatte Allow Fullscrrenn nicht an, deswegen. Passt. Sorry.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.25`

**Comment by mcuiobroker** [comment]
Passt. Danke.
