### ISSUE TITLE
selected TAB Stil definieren per Binding

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1733]
Zum Tab gibt es zurzeit Icon Stil und Body Stil.
![image](https://user-images.githubusercontent.com/84818934/174460006-2de54a0b-a6ee-46cd-adb8-8568dc51aebc.png)
Hier sollte man ein `selected Stil` ergänzen. Dieser sollte auch Binding-fähig sein und auch eine Möglichkeit bekommen, um Probleme beim Handy mit dem DarkMode zu umgehen. Hier ist es momentan so, dass bei selektierten TAB auf dem Handy im DarkMode der Unterstrich schwarz dargestellt wird. Dies ist auf dem Handy schlecht zu erkennen.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.22` eingeführt

**Comment by Zefau** [comment]
nur `{"color":"red"}`
