### ISSUE TITLE
TAB Selektion (TAB-Leiste) immer anzeigen als Option

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1736]
Scrollt man bei langen Inhalten im TAB nach unten, verschwindet immer die TAB-Selektion(TAB-Leiste). Hier wäre es sinnvoll, wenn man die TAB-Selektion immer oben sehen könnte, um schneller umschalten zu können. Damit man nicht erst wieder hochscrollen muss.

**Comment by mcuiobroker** [comment]
Bzw funktioniert nicht mehr:
![image](https://user-images.githubusercontent.com/84818934/174501945-dd8d5584-f035-4de4-b157-1ee44d1f39e2.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.22` behoben sein

**Comment by mcuiobroker** [comment]
Passt. Danke.
