### ISSUE TITLE
v3.1.0-alpha.17 HistoryGraph Mehrfach-Anzeige der Werte

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1737]
Mehrfach-Anzeige einer Temperatur
![image](https://user-images.githubusercontent.com/84818934/174494619-3f5b0b29-2c6b-4e25-aa50-952a51a3b584.png)

**Comment by mcuiobroker** [comment]
Gehört dazu ?
![image](https://user-images.githubusercontent.com/84818934/174544923-d54a3fe8-46ac-4be5-bf05-52da976b96da.png)

**Comment by Zefau** [comment]
ist der Fehler mit `v3.1.0-alpha.30` noch aktuell?

**Comment by mcuiobroker** [comment]
Ja.
![image](https://user-images.githubusercontent.com/84818934/183757334-dcb09c82-78fd-498f-9b72-37072d0f1432.png)

**Comment by Zefau** [comment]
Bekomm ich nicht nachgestellt. Kannst du mal deine Konfiguration posten? Liegt es ggf. daran? Überschreibst du irgendwelche Achsen-Einstellungen?

**Comment by mcuiobroker** [comment]
```
[  {    "position": "left",    "name": "Bad",    "nameLocation": "center",    "nameGap": 70,    "offset": -5,    "padding": 10,    "min": "dataMin",    "max": "dataMax",    "axisPointer": {      "show": true    },    "splitLine": {      "show": true,      "lineStyle": {        "color": "rgba(193, 22, 22, 1)",        "type": "dotted"      }    },    "axisLabel": {      "formatter": "{value} °C",      "margin": 25,      "showMaxLabel": false,      "showMinLabel": true,      "color": "rgba(255, 255, 255, 1)"    }  },  {    "position": "right",    "name": "Büro",    "nameLocation": "center",    "nameGap": 70,    "offset": 0,    "padding": 10,    "min": "dataMin",    "max": "dataMax",    "axisLabel": {      "formatter": "{value} °C",      "margin": 25    }  }]
```
Serie
`{  "symbol": "rect",  "symbolSize": 9,  "label": {    "show": false  },  "showAllSymbol": true,  "colorBy":"data"}`
Callback
`(val) => val /10`

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.31`

**Comment by mcuiobroker** [comment]
Kein Mehrfach-Werte mehr, aber jetzt falsche Rundung?
![image](https://user-images.githubusercontent.com/84818934/184227935-3a0e6709-51f3-49df-bd81-9ee71e454799.png)

**Comment by mcuiobroker** [comment]
Kurven werden nur teilweise korrekt ausgeblendet
![jarvis v3 - 10alpha31 - Problem Kurven History ausblenden](https://user-images.githubusercontent.com/84818934/184232876-c98fb661-df94-485d-93e1-4fab2c6fdff2.gif)

**Comment by Zefau** [comment]
Kannst du das JSON dazu mal zeigen? Steht da auch schon `Object` drin?

**Comment by mcuiobroker** [comment]
```
"4acb0466-f47c-4eff-a1a6-22c836cabc7f": {
    "id": "4acb0466-f47c-4eff-a1a6-22c836cabc7f",
    "config": {
      "chartType": "line",
      "maxEntries": "500",
      "legend": "top",
      "showSymbol": false,
      "zoom": false,
      "dataZoom": "100",
      "timeReviewValue": "1",
      "timeReviewUnit": "hours",
      "timeConfigurable": true,
      "dateFormat": "{HH}:{mm}",
      "timeType": "review",
      "yAxis": "[\n  {\n    \"position\": \"left\",\n    \"name\": \"Bad\",\n    \"nameLocation\": \"center\",\n    \"nameGap\": 70,\n    \"offset\": -5,\n    \"padding\": 10,\n    \"min\": \"dataMin\",\n    \"max\": \"dataMax\",\n    \"axisPointer\": {\n      \"show\": true\n    },\n    \"splitLine\": {\n      \"show\": true,\n      \"lineStyle\": {\n        \"color\": \"rgba(193, 22, 22, 1)\",\n        \"type\": \"dotted\"\n      }\n    },\n    \"axisLabel\": {\n      \"formatter\": \"{value} °C\",\n      \"margin\": 25,\n      \"showMaxLabel\": false,\n      \"showMinLabel\": true,\n      \"color\": \"rgba(255, 255, 255, 1)\"\n    }\n  },\n  {\n    \"position\": \"right\",\n    \"name\": \"Büro\",\n    \"nameLocation\": \"center\",\n    \"nameGap\": 70,\n    \"offset\": 0,\n    \"padding\": 10,\n    \"min\": \"dataMin\",\n    \"max\": \"dataMax\",\n    \"axisLabel\": {\n      \"formatter\": \"{value} °C\",\n      \"margin\": 25\n    }\n  }\n]",
      "xAxis": "",
      "callback": "(val) => val /10",
      "series": "{\n  \"symbol\": \"rect\",\n  \"symbolSize\": 9,\n  \"label\": {\n    \"show\": false\n  },\n  \"showAllSymbol\": true,\n  \"colorBy\":\"data\"\n}"
    },
    "title": "Temperaturen",
    "module": "HistoryGraph",
    "items": [
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "fb0e23f5-ecbf-4eff-86dd-bf5dc0b0df8b",
        "primaryStateKey": "HUE_BAD_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "color": "#c75300",
          "yaxis": 0
        },
        "label": "Bad"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "4120ce50-c168-4604-8990-889b1a994412",
        "primaryStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "color": "#359eb8",
          "yaxis": 1
        },
        "label": "Buero"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "f18c0a7f-dec6-4b94-99a5-a29aded91f4a",
        "primaryStateKey": "HUE_SZ_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "yaxis": "",
          "color": "#b50707"
        },
        "label": "SZ"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "faeeb094-dafd-4b7a-b688-56a71b7196a6",
        "primaryStateKey": "HUE_KUECHE_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "yaxis": "",
          "color": "#c6d40b"
        },
        "label": "Küche"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "3ec9d998-34bb-4ff7-8cdb-c77949f4a3ff",
        "primaryStateKey": "HUE_FLUR_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "yaxis": "",
          "color": "#005c59"
        },
        "label": "Flur"
      },
      {
        "type": "device",
        "deviceId": "1e7be28a-b475-4e73-bbf0-7e1405f436d9",
        "id": "09b520f8-86af-47e4-af19-5b8119912c38",
        "primaryStateKey": "HUE_WZ_TEMPERATURE",
        "bodyStateKey": "HUE_BUERO_TEMPERATURE",
        "bodyElement": "LastChangeBody",
        "historyAdapter": "history.0",
        "moduleConfig": {
          "yaxis": "",
          "color": "#0300c2"
        },
        "label": "WZ"
      }
    ],
    "revision": "2aada"
  },
```

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.32`

**Comment by mcuiobroker** [comment]
Passt nicht.
![image](https://user-images.githubusercontent.com/84818934/184473440-1357a16e-9230-4b2b-b8fd-8d33f17dcfad.png)
- Abrundung (Bad) passt nicht
- oberster Wert (max) fehlt, wurde sonst angezeigt
- Ausblenden Bad funktioniert nicht, weiterhin wird mit SZ ausgeblendet
- Büro Y-Achsen-Label fehlt

**Comment by Zefau** [comment]
> Abrundung (Bad) passt nicht

Ich vermute, dass es daran liegt, dass hier der Wert vom Gerät als niedrigster Wert 1-zu-1 in die Achse übernommen wird. Versuch mal beim `formatter` eine Funktion zu verwenden und mittels `toFixed(2)` zu steuern. Oder `"min": "dataMin"`
bzw. `"showMinLabel": true` mal rausnehmen?

Hier kann ich jedenfalls nicht viel machen, da es an der individuellen Achsen-Konfiguration liegt.

> oberster Wert (Bad max) fehlt, wurde sonst angezeigt

Du hast `showMaxLabel` auch auf `false`. Stell es auf `true`.

> Ausblenden Bad funktioniert nicht, weiterhin wird mit SZ ausgeblendet

Das liegt vermutlich daran, dass ein Fehler in einer früheren alpha nun fest in deinem JSON gespeichert ist.

Bezogen auf https://github.com/Zefau/ioBroker.jarvis/issues/1737#issuecomment-1212803397: Entferne bzw. korrigiere mal `yaxis` in `moduleConfig`, wenn es leer (also `""`) ist auf `0` oder `1` (je nachdem in welche Y-Achse es gehört).

> Büro Y-Achsen-Label fehlt

Ich vermute es liegt an dem langen Komma-Wert der linken Y-Achse, wodurch das Label aus dem Sichtbereich raus rutscht.

**Comment by Zefau** [comment]
Ich sehe gerade, der `formatter` wird im Code gar nicht übernommen. Ich korrigiere.. sorry..

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.45`

**Comment by mcuiobroker** [comment]
Hier ist noch ein Punkt offen:

Bad ist ausgeblendet mit dem obigen Schalter, aber wird noch angezeigt?
![image](https://user-images.githubusercontent.com/84818934/193451654-68093149-34bd-4477-9833-147f7689aba3.png)

Beim Buero wird die rechte Anzeige ausgeblendet:
![image](https://user-images.githubusercontent.com/84818934/193451737-e23c06d7-28f0-4ac1-8cf9-36f34c58391a.png)

**Comment by mcuiobroker** [comment]
Ja hängt damit zusammen, dann mache ich hier zu. Danke.
