### ISSUE TITLE
v3.1.0-alpha.18 Drehender Kreis bei MAP

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1738]
![image](https://user-images.githubusercontent.com/84818934/174545697-73425a80-d48b-4d80-85e0-8783ce8e8a55.png)
Gehört dazu?
![image](https://user-images.githubusercontent.com/84818934/174545790-38d5cd51-50b1-4758-a600-504bf369e7c2.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.19` nun passen

**Comment by mcuiobroker** [comment]
Im MAP selbst kein drehender Kreis mehr.
Gehört das hier hin?
![image](https://user-images.githubusercontent.com/84818934/175749626-2bd865bd-550d-488f-90c3-698c208f92d6.png)
