### ISSUE TITLE
Datenpunktstil & Icon Bedingungen greifen nach Update auf Alpha nicht mehr

### ISSUE THREAD

**Issue by Bloodsurfer** [Zefau/ioBroker.jarvis#1740]
Hallo @Zefau,

was hat sich denn zwischen Version 3.0.12 Beta 1 und 3.1.0 alpha 17 getan, dass meine Farben und blinkenden Icons nach dem Update nicht mehr hinhauen? Liegt das an der Alpha oder gab es irgendwelche Änderungen?

vor Update
![image](https://user-images.githubusercontent.com/74984485/174573526-c98d6849-f73c-4bc9-b161-c9de72fdc633.png)

nach Update
![image](https://user-images.githubusercontent.com/74984485/174573573-74ed328a-7dc6-48e5-9801-f5cc10ab585f.png)

Einstellungen sind ja geblieben
![image](https://user-images.githubusercontent.com/74984485/174573594-18db34cd-e11d-48c6-8135-f7146021f196.png)

https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2577

**Comment by Zefau** [comment]
Sollte mittlerweile wieder funktionieren. Kannst du das mit `v3.1.0-alpha.32` bestätigen?

**Comment by Bloodsurfer** [comment]
Habs jetzt mit der v3.1.0-alpha.35 ausprobiert, scheint eher noch schlimmer zu sein, weil Werte und oder Einheiten fehlen. Zudem ist links das Register auf einmal weiß.

vorher:
![image](https://user-images.githubusercontent.com/74984485/186392630-1b5e4346-6bd5-434e-8dc5-55e0b4dbcbe9.png)

nachher:
![image](https://user-images.githubusercontent.com/74984485/186392669-4110fdb1-fd9b-4593-9304-37d7ba0c99af.png)

**Comment by Zefau** [comment]
@Bloodsurfer sorry, das Issue ist mir untergegangen. Ist es mit `v3.1.0-alpha.44` behoben oder bestehen die Probleme noch?

**Comment by hosabeni** [comment]
Wenn Bindings mit `{val}` zum Einsatz kommen greifen die Bedingungen nicht

Hier greift nur der untere Teil:
```
{
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '10'": "mdi:battery-charging-outline charge_0",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '20'": "mdi:battery-charging-outline charge_10",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '30'": "mdi:battery-charging-outline charge_20",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '40'": "mdi:battery-charging-outline charge_30",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '50'": "mdi:battery-charging-outline charge_40",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '60'": "mdi:battery-charging-outline charge_50",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '70'": "mdi:battery-charging-outline charge_60",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '80'": "mdi:battery-charging-outline charge_70",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '90'": "mdi:battery-charging-outline charge_80",
  "'{ecovacs-deebot.0.info.deviceStatus}' == 'charging' && '{val}' < '100'": "mdi:battery-charging-outline charge_90",
  "< 10": "mdi:battery-outline",
  "< 20": "mdi:battery-10",
  "< 30": "mdi:battery-20",
  "< 40": "mdi:battery-30",
  "< 50": "mdi:battery-40",
  "< 60": "mdi:battery-50",
  "< 70": "mdi:battery-60",
  "< 80": "mdi:battery-70",
  "< 90": "mdi:battery-80",
  "< 98": "mdi:battery-90",
  "=100": "mdi:battery"
}
```

In der Konsole habe ich diese Warnung von der entsprechenden StateList in der das angezeigt wird: 

![Image](https://user-images.githubusercontent.com/77939385/190860315-7af5e5a7-dba8-4ef9-8b8b-8be200a69825.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.45`

**Comment by Bloodsurfer** [comment]
Super! Das sieht schon viel besser aus.

![image](https://user-images.githubusercontent.com/74984485/190887490-f601fa54-c8c8-4d4c-b452-4edcec997aec.png)
Ich denk das Issue kann zu. Einzig auf der linken Seite ist das Menü immer noch weiß.

**Comment by Bloodsurfer** [comment]
![image](https://user-images.githubusercontent.com/74984485/190887547-5b89a380-5cb2-4542-b0fb-f115faa38d0a.png)

**Comment by hosabeni** [comment]
`v3.1.0-alpha.45`
Das Passt jetzt.
Die Bindings funktionieren und die Warnung in der Konsole kommt auch nicht mehr.

Danke! Top!!!
