### ISSUE TITLE
AdapterLogs

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1741]
Modul-Einstellungen
![image](https://user-images.githubusercontent.com/84818934/174596527-5e9f9386-241e-4590-9664-b1f43831c2a5.png)

- [x] Überschriften und Erklärungen fehlen
- [x] Obwohl Datensätze je Seite 0 (für alle) eingestellt ist werden nur die ersten10 angezeigt.

![image](https://user-images.githubusercontent.com/84818934/174596575-d8d7d12b-8aa1-46b0-9347-453560525290.png)

- [x] Die Selektion sollte einen Schalter alle aus enthalten. Am Anfang sind alles Adapter selektiert (bei 76), wenn man nur 3 haben möchte, muss man 73 deaktivieren.
- [x] Man sollte Spalten ausblenden können, da man in erster Linie die Message sehen möchte. Auf dem Handy braucht die Time sehr viel Platz.
- [x] Obwohl ich das Modul erst am Nachmittag eingestellt, liefert es die LOG-Inhalte vom ganzen Tag. Soll das so?

**Comment by mcuiobroker** [comment]
Wie kann man dort die Überschrift Hintergrundfarbe beeinflussen?
```
.jarvis-AdapterLogs .q-table thead {
	background-color: lightblue !important;
}
```
Hiermit geht es nicht.
![image](https://user-images.githubusercontent.com/84818934/175779825-b02e5c88-89b0-4fac-9340-f8ac0ff397e0.png)

**Comment by Zefau** [comment]
>  Obwohl ich das Modul erst am Nachmittag eingestellt, liefert es die LOG-Inhalte vom ganzen Tag. Soll das so?

Ja. Es wird initial das Tages-Log geladen.

**Comment by Zefau** [comment]
> Man sollte Spalten ausblenden können, da man in erster Linie die Message sehen möchte. Auf dem Handy braucht die Time sehr viel Platz.

Nun mit `v3.1.0-alpha.28` möglich. 

Damit sollte alles drin sein.

**Comment by mcuiobroker** [comment]
Ja passt. Danke.
