### ISSUE TITLE
Scriptstatus

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1742]
- [x] Im Widget ist die Option "Skaliere Inahlte zur Widgetgröße" ausgewählt. Es wird aber kein Scrollbalken angezeigt.

![image](https://user-images.githubusercontent.com/84818934/174597120-ea891da7-1ccc-4407-8f0c-c98f71dc1dd0.png)

- [x] Weiterhin ist in der Liste der Scripte, die angezeigt werden sollen "jarvis" eingetragen, es werden aber alle angezeigt.

![image](https://user-images.githubusercontent.com/84818934/174597354-eb7fd2d8-105f-4b7e-83c8-4756d8c1cc81.png)
![image](https://user-images.githubusercontent.com/84818934/174597511-ea5e1a89-0f9c-41ab-8d8a-73cf1726d0a6.png)

- [ ] Es wird über den Rand der Box geschrieben

![image](https://user-images.githubusercontent.com/84818934/174599062-4cdb0d2c-c496-4ae7-8cc6-806f3855c937.png)

- [x] Klasse ergänzen, um die Schriftgröße zu verändern, da auf dem Handy die Darstellung klein ist

![image](https://user-images.githubusercontent.com/84818934/174604754-928a68a1-797d-4be4-87de-c3c84fdb3147.png)

**Comment by mcuiobroker** [comment]
Jetzt hat er plötzlich nach Umschalten auf "false" für Widget anpassen, den Scrollbalken an?
![image](https://user-images.githubusercontent.com/84818934/174655909-57c8ad40-a87f-483d-a183-9d1ce6ee8a0b.png)

Welches Datum ist das? Erstellungsdatum?
![image](https://user-images.githubusercontent.com/84818934/174656039-4e6a7ae8-c277-46a7-b431-2f179a1a68fa.png)

**Comment by mcuiobroker** [comment]
Darstellung auf dem Handy.

- [ ] Nach Neuladen der Seite (Falsche Darstellung) zu weit nach unten gezogen

![image](https://user-images.githubusercontent.com/84818934/174673240-2f2f2d6e-b5f4-41bf-8f5e-19988cd4fe61.png)
Nach Vergrößerung (Doppeltipp) -> Vollbild
Geht man wieder zurück -> kleinere normale Anzeige wie auf dem PC.
![image](https://user-images.githubusercontent.com/84818934/174673438-f91c0f64-eaf3-4ffe-a06b-533206973fe8.png)
PC
![image](https://user-images.githubusercontent.com/84818934/174673521-deae1ef6-72c6-4e14-a2f3-bba64da4462d.png)

**Comment by Zefau** [comment]
> Welches Datum ist das? Erstellungsdatum?

Ja.

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.19` nun passen

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/175749788-fb89bf4d-3679-4379-ac3c-eab9cdf2be9b.png)
Wie ist es einzutragen? Auch `*` versucht geht nicht.
![image](https://user-images.githubusercontent.com/84818934/175749807-9a90ecaa-5e57-459e-9010-ccf2a71e3e0d.png)
![image](https://user-images.githubusercontent.com/84818934/175749824-17e30d8a-d3cd-489d-b769-554214105914.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.20`

**Comment by mcuiobroker** [comment]
JARVIS* funktioniert.
Bitte noch bei den aktiven die Klasse `enable` oder so ergänzen, damit man dort die Farbe einstellen kann:
![image](https://user-images.githubusercontent.com/84818934/175775472-3ed92768-f0be-477e-9a6b-0d1d71175e22.png)
wie bei `disable`
![image](https://user-images.githubusercontent.com/84818934/175775494-c7d73570-996e-4785-9821-0c7eb87b299d.png)
Und bei einem Verzeichnis eine Klasse  (directory, list, oder so)
![image](https://user-images.githubusercontent.com/84818934/175775559-698f1139-e05a-491d-b63f-d24e184978dd.png)

![image](https://user-images.githubusercontent.com/84818934/175775545-1546a745-1b5f-4072-a7b0-c846fdea364a.png)

**Comment by mcuiobroker** [comment]
Angezeigte und nicht angezeigte Scripte gleichzeitg:?
![image](https://user-images.githubusercontent.com/84818934/175776344-23e0e20f-6ddf-43fc-b92e-eee733b19349.png)
AddDevice -Script sollte eigentlich nicht angezeigt werden?
![image](https://user-images.githubusercontent.com/84818934/175776325-882be4e9-2801-462b-a206-6df110a9d159.png)

**Comment by mcuiobroker** [comment]
Start Script funktioniert nicht.
Stop Script funktioniert.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.21`
- Schalten sollte nun funktionieren
- CSS-Klassen hinzugefügt
- Whitelist und Blacklist nun gleichzeitig nutzbar

**Comment by mcuiobroker** [comment]
White- und BlackList gleichezeitig funktioniert noch nicht.
![image](https://user-images.githubusercontent.com/84818934/175792631-cb797b70-b789-4383-8ce1-95b2a7ea137b.png)
![image](https://user-images.githubusercontent.com/84818934/175792643-6f478bc6-beb1-492c-967c-eb11e0371005.png)

**Comment by Zefau** [comment]
`*AddDevice*`mit Platzhaltern?

**Comment by mcuiobroker** [comment]
Klappt. Danke.
