### ISSUE TITLE
v3.1.0.alpha.18 Fehler während Konfigurationsbearbeitung

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1744]
Widget-Box bearbeiten klicken 
![image](https://user-images.githubusercontent.com/84818934/174674173-9736718f-00e3-47f1-89b0-a98b6e6ebfc6.png)

![image](https://user-images.githubusercontent.com/84818934/174674108-92dc8852-57f7-40f1-b98d-90ac0f2ba676.png)

**Comment by Zefau** [comment]
Ist das noch aktuell? Kommt der Fehler noch?

**Comment by mcuiobroker** [comment]
Momentan nicht. Mach ich erstmal zu.
