### ISSUE TITLE
v3.1.0-alpha.18 Icon werden nicht erkannt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1745]
Gleiche iconify-Version:
![image](https://user-images.githubusercontent.com/84818934/175183331-b0260683-bb1a-4bfc-9ec4-3770901abcc7.png)

![image](https://user-images.githubusercontent.com/84818934/175183359-60b9e943-baee-4522-b2dd-2090cf230705.png)
Obwohl es genutzt wird?
![image](https://user-images.githubusercontent.com/84818934/175183556-34a899de-64f6-49a0-8768-c823d3b75224.png)

Diese wird erkannt:
![image](https://user-images.githubusercontent.com/84818934/175183786-e0dab9c4-0892-4880-be55-fab7bf12e754.png)

**Comment by Zefau** [comment]
Die Material Design Icons sind aus Performance Gründen direkt eingebunden, ohne Iconify. Die Version ist aber `v6.7.96` und die Icons sind erst ab `v6.9.96` (siehe https://raw.githubusercontent.com/Templarian/MaterialDesign/master/meta.json) verfügbar. 

Die Dependency kann ich nicht selbst updaten, insofern stelle ich es wieder auf Iconify um.

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.19` nun passen

**Comment by mcuiobroker** [comment]
Passt Danke.
