### ISSUE TITLE
Devices with incorrect configuration (states not found) - Homematic IP wired

### ISSUE THREAD

**Issue by Nexwarrior** [Zefau/ioBroker.jarvis#1746]
All my Homematic IP Wired devices are shown as "Devices with incorrect configuration (states not found)" during import and no data points are transferred.

Specifically, the following devices are involved:
HmIPW-DRD3
HmIPW DRAP
HmIPW-DRS8
HmIPW-DRI32
HmIPW-DRS4
HmIPW-SMI55
HmIPW SPI

I have read in several places that this could also be laboriously entered manually. Is there a guide for this?
I am sending a few data points for HmIPW-DRS8 as an example:

![Bildschirmfoto 2022-06-23 um 09 07 42](https://user-images.githubusercontent.com/30155898/175238361-1762d1d6-0588-41eb-9727-475aeb4107c4.png)

**Comment by Zefau** [comment]
Can you either export the object structure as JSON or Screenshot the required objects for the devices
- [ ] HmIPW-DRD3
- [ ] HmIPW DRAP
- [ ] HmIPW-DRS8
- [ ] HmIPW-DRI32
- [ ] HmIPW-DRS4

**Comment by Nexwarrior** [comment]
Yes, here they are:

Really super fast response, thank you very much :-)
[json-structures.zip](https://github.com/Zefau/ioBroker.jarvis/files/8965256/json-structures.zip)

**Comment by Zefau** [comment]
Was brauchst du denn beim `DRAP`? Das ist der Router, oder?

**Comment by Nexwarrior** [comment]
Ja, das ist der Router. Ich persönlich brauche von ihm nichts, den hab ich nur zwecks Vollständigkeit aufgenommen. 
Hier noch eine Aufstellung, welche channel ich brauche:
DRS8: 2, 6, 10, 14, 18, 22, 26, 30
DRD3: 2, 6, 10
DRS4: 2, 6, 10, 14
DRI32: alle

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.22` hinzugefügt
