### ISSUE TITLE
v3.1.0-alpha.21 onBeforeUnmount und ButtonAction Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1749]
![image](https://user-images.githubusercontent.com/84818934/175793705-935894ec-c670-4986-a891-56b81f08b525.png)

![image](https://user-images.githubusercontent.com/84818934/175793712-6d39a130-8c41-4c40-a913-958b5d89b9f9.png)

![image](https://user-images.githubusercontent.com/84818934/175793727-83edc7ae-177f-4ae3-ab25-38cdd05e9e67.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.22` behoben sein

**Comment by mcuiobroker** [comment]
Kommt nicht mehr.
