### ISSUE TITLE
Violation: non-passive event listener to touchstart

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1750]
![image](https://user-images.githubusercontent.com/84818934/173685489-947433fd-7702-497d-beeb-35b6c706ec8b.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/1698#issuecomment-1155695728_

**Comment by Zefau** [comment]
Weiß jemand bei welchem Modul die Fehlermeldung entsteht?

**Comment by mcuiobroker** [comment]
Kommt momentan mit v3.1.0-alpha.21 nicht mehr.

**Comment by Zefau** [comment]
Dann schließe ich erstmal. Wenn es wieder vorkommt, gerne öffnen.
