### ISSUE TITLE
DisplayImage v3 - Url from DP

### ISSUE THREAD

**Issue by michiproep** [Zefau/ioBroker.jarvis#1751]
After upgrading to v3, the DisplayImage does not read images from a DP anymore.
DPs can contain URLs (also relative URLs to iobroker) or Base64 strings.

Currently, I only can configure a URL, a Base64-string but not a DP. This was working in v2

**Comment by Zefau** [comment]
Add a Device to DisplayImage Module, which defines the state pointing to the ioBroker DP:

![image](https://user-images.githubusercontent.com/14368811/175812498-99bd529b-0d44-4287-b440-8289405592be.png)

**Comment by michiproep** [comment]
Thanks for the info. I could not get it to work. Is there a docu on how to configure the "device"?

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/v3-fuer-einsteiger/module/displayimage

https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/module/displayimage
