### ISSUE TITLE
iFrame in fullscreen tab wrongly displayed

### ISSUE THREAD

**Issue by michiproep** [Zefau/ioBroker.jarvis#1752]
iFrame is missing "top", "left" and "posistion" in css on smaller (not smartphone) resolutions when used in a fullscreen tab.
See screenshots. On the second one you would have to scroll down to see any content.

Big resolution:
![grafik](https://user-images.githubusercontent.com/12296115/175821976-c4e0c0af-b898-4eea-9db2-cb35b944508f.png)

Small resolution:
![grafik](https://user-images.githubusercontent.com/12296115/175821987-03f61a13-ffe3-49b1-99c3-c60972c41604.png)

**Comment by Zefau** [comment]
Does this behavior change when you turn off the keep alive setting?

**Comment by michiproep** [comment]
Indeed, it does.

**Comment by Zefau** [comment]
Does this problem still exist in `v3.1.0-alpha.60`?

**Comment by michiproep** [comment]
Sorry, but at the moment I can't install alpha versions. Need to get another test environment setup again... But I'll tell you as soon as I can.

**Comment by Zefau** [comment]
will be handled through https://github.com/Zefau/ioBroker.jarvis/issues/977
