### ISSUE TITLE
v3.1.0-alpha.22 haut das LOG (DOM) voll

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1754]
Scheint zeitweise das Log damit zu fluten. Man kann dann nur den Browser-TAB schließen und neustarten.
![image](https://user-images.githubusercontent.com/84818934/175992920-217f35ab-2001-473d-9c89-b7550e50d730.png)
Der Zähler so schnell hoch
![jarvis-v310-alpha22-FehlerDOM](https://user-images.githubusercontent.com/84818934/175994372-7af2b33a-4e61-4f18-82f5-25701e372adc.gif)

**Comment by mcuiobroker** [comment]
Von diesen Meldungen kommen auch viele, kann es nicht zuordnen.
![image](https://user-images.githubusercontent.com/84818934/175993772-ce81dbc3-d8c9-42c5-89c0-5fb4fb2154ba.png)

**Comment by Zefau** [comment]
Schau nochmal mit `v3.1.0-alpha.23` (bzgl. erster Fehlermeldung). Die zweite Fehlermeldung gehört zum HistoryGraph.
