### ISSUE TITLE
Option im LevelBody "read-only"

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1756]
Eine Option im LevelBody "read-Only" würde ja dann reichen? Dann kann man ihn nicht mehr verstellen.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/discussions/1755#discussioncomment-3033945_

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.54` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.54`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt.Danke.
