### ISSUE TITLE
v3.1.0-alpha.23 Änderung SwitchAction , jsonTable usw. wird nicht aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1758]
Änderungen werden nicht aktualisiert.
Klickt man die SwitchAction und ein javascript setzt diesen zurück, wird es nicht angezeigt.
Ändert sich der Wert für die jsonTable, wird es nicht angezeigt. Erst nach F5.

**Comment by Bernd9000** [comment]
Mit oder ohne ack spielt keine Rolle, Änderungen werden nicht aktualisiert.

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.24`

**Comment by mcuiobroker** [comment]
Wenn ich in iobroker einen Wert ändere, wird dieser nicht in jarvis angezeigt.
![image](https://user-images.githubusercontent.com/84818934/179424664-99a60843-cbff-4f63-8fcb-2bb5c33fb16c.png)
![image](https://user-images.githubusercontent.com/84818934/179424676-aed61c1f-1ae8-4374-8cfc-33e6afc21a7a.png)

**Comment by mcuiobroker** [comment]
Noch ein Hinweis zum Thema Aktualisierung. Wenn ich im Layout ein Licht einschalte über den LevelBody wird der Schalter für das Licht nicht als "eingeschaltet" dargestellt. Gehe dann aber ins POPUP, wird der Zustand aktualisiert? Gehe wieder zurück ins Layout ist auch dort der Zustand aktualisiert.
![jarvis-v3-Thema Aktualisierung](https://user-images.githubusercontent.com/84818934/179460381-fa100475-2844-4676-a938-2397ff2b0327.gif)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.25`

**Comment by mcuiobroker** [comment]
Hab nicht alle Änderungsmöglichkeiten getestet, aber die Wertänderung in iobroker wird direkt angezeigt.

**Comment by mcuiobroker** [comment]
Geräte-Änderungen werden nicht aktualisiert. Ich ändere die Anzeigevariante für eine Auswahl während der Laufzeit. Diese Änderung wird nicht angezeigt.
![image](https://user-images.githubusercontent.com/84818934/179897710-7264b2ad-481a-4a9a-ae0e-609fcae929e7.png)
