### ISSUE TITLE
Widget/Modul JSONTable: Spaltenzentrierung unterschiedlich

### ISSUE THREAD

**Issue by LE-RKelly** [Zefau/ioBroker.jarvis#1759]
Überschrift und darunterliegende Zeilen werden unterschiedlich zentriert.
In der Modul-Konfiguration wird mit  "align": "center" zentriert.

![image](https://user-images.githubusercontent.com/57917737/176228912-356af30d-1169-42ea-9847-530be7a0ff08.png)

**Comment by mcuiobroker** [comment]
Hängt sehr wahrscheinlich mit dem Sortierungs-Element zusammen?

**Comment by Zefau** [comment]
Wenn du die Sortierung deaktivieren willst, dann mittels `"sortable": false`

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.28`
