### ISSUE TITLE
Neuer "Datenpunkt-Schlüssel" bei States eines Geräts

### ISSUE THREAD

**Issue by dalig83** [Zefau/ioBroker.jarvis#1760]
- jarvis v3.0.11
- Siehe Screenshot

Fehlerbeschreibung:
Beim manuellen Anlegen eines neuen "Datenpunkt-Schlüssels" wird der Text nicht übernommen.
Beim Tippen von "Status Testalarm" und dann ENTER, übernimmt er nur das "S". Manchmal auch nur "Stat".

Ich dachte zuerst, es ist nur ein Anzeigefehler. Aber er übernimmt wirklich nur einen Teil der Eingabe.

Warte ich einige Sekunden, übernimmt er alles.
<img width="987" alt="Bildschirmfoto 2022-06-28 um 23 02 58" src="https://user-images.githubusercontent.com/64753305/176288093-831dbe8f-513c-4199-9383-f90531cc99fb.png">

**Comment by dalig83** [comment]
Was ich zusätzlich noch bemerkt habe gerade eben:

- Wenn ich warte und der Eintrag wird übernommen, dann wird auch das Eingabefeld "neuer Datenpunkt-Schlüssel" geleert
- Wenn ich ENTER drücke, sobald ich fertig bin mit dem Schreiben, übernimmt er nur einen Teil und das Eingabefeld bleibt befüllt.

**Comment by mcuiobroker** [comment]
Auf der console `iob upload jarvis` gemacht?

**Comment by dalig83** [comment]
Gerade eben gemacht.
Tritt noch auf, nicht mehr so häufig, aber tritt auf.

Was bewirkt der Befehl genau?

**Comment by mcuiobroker** [comment]
Wenn bei der Installation einige Daten irgendwo nicht ordentlich übertragen wurden, kann man den Adapter nochmal neu hochladen.

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.24`
