### ISSUE TITLE
v3.1.0-alpha.23 - Einheit falsch dargestellt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1761]
![image](https://user-images.githubusercontent.com/84818934/176492168-f7f0c9d2-8633-4f75-9302-9c536dbbceb4.png)
![image](https://user-images.githubusercontent.com/84818934/176492464-3e7d9995-b590-4eb6-9e03-e9c689613c02.png)
![image](https://user-images.githubusercontent.com/84818934/176492520-6135270b-9493-46d7-99d0-01274b889199.png)
Mit v3.0.11 
![image](https://user-images.githubusercontent.com/84818934/176492895-2e7a5715-8ba2-48b6-b9d3-a5cdf22643a7.png)

**Comment by mcuiobroker** [comment]
Kommt.

**Comment by Zefau** [comment]
Die Formel in den Datenpunkt Eigenschaften ist nicht richtig. Hinter `:` kann kein `>=` kommen.

**Comment by mcuiobroker** [comment]
```
{"value":"val => val < 1000 ? parseFloat(val).toFixed(2) :val < 1000000 ? parseFloat(val/1000).toFixed(2) : val >= 1000000 ? parseFloat(val/1000000).toFixed(2): val"}
```
Einheit
```
{"<1000":"W","<1000000":"KW",">=1000000":"MW"}
```

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.24`

**Comment by mcuiobroker** [comment]
Die Einheit wird korrekt dargestellt. Danke.
