### ISSUE TITLE
v3.1.0-alpha.23 Fehler bei Bearbeitung der Konfiguration

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1764]
F2 -> Aufrufen der Konfiguration ->
![image](https://user-images.githubusercontent.com/84818934/176544234-913ea17c-ecac-42a8-b85c-93364966ab58.png)

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.24`

**Comment by mcuiobroker** [comment]
F2 bringt jarvis zum Absturz?
![image](https://user-images.githubusercontent.com/84818934/179425785-7c3a55ff-c149-49b9-9d94-a5a62344923c.png)
Dreht seine Runden und muss geschlossen werden.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.25`

**Comment by mcuiobroker** [comment]
`v3.1.0-alpha.27`
Jetzt gibt es keinen Absturz mehr, manchmal muss man öfter F2 drücken damit er in die Konfig springt?

**Comment by Zefau** [comment]
Dauert ein wenig, bis die Hotkeys registriert werden. Ich schließe mal hier.

**Comment by mcuiobroker** [comment]
Hängt sich anscheinend nach einiger Zeit auf?
![image](https://user-images.githubusercontent.com/84818934/181824982-02235892-dfe1-43c3-8e97-04c46ea6e04b.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.29` nicht mehr vorkommen

**Comment by mcuiobroker** [comment]
Wir können ja erstmal schließen, wenn dann was ist, öffnen wir wieder. Bis jetzt keine Probleme.
Was auffällt ist, dass das Umschalten von Konfig-TAB zu Konfig-TAB dauert es länger als sonst.
