### ISSUE TITLE
The "InputAction" accepts the entered text only after pressing the <Enter> key

### ISSUE THREAD

**Issue by exaware** [Zefau/ioBroker.jarvis#1767]
The "InputAction" accepts the entered text only after pressing the **Enter** key. In Android the **Enter** key doesn't work. So you can't change anything in "InputAction" if you opened jarvis in Android. It jumps instead to the next "InputAction" if you have more than one "InputAction" on a site. The **Enter** key only works at the last "InputAction" in Android.

**Comment by mcuiobroker** [comment]
@Zefau Vielleicht hilft das? `type="search"`?
https://stackoverflow.com/questions/70867312/how-to-avoid-html-input-field-from-showing-next-option-instead-of-go-on-mob

**Comment by exaware** [comment]
Ich hab die 3.0.11
Ich habe es mal im CSS Editor probiert mit nav-index:"-1" und ser-focus: none probiert.
Geht aber leider nicht.

**Comment by Zefau** [comment]
prüft mal bitte mit v3.0.12

**Comment by Zefau** [comment]
duplicate: https://github.com/Zefau/ioBroker.jarvis/issues/1709
