### ISSUE TITLE
displayImage - Wansview Q6 Kamera wird in Chrome & Edge nicht angezeigt

### ISSUE THREAD

**Issue by chappo59** [Zefau/ioBroker.jarvis#1768]
Jarvis 3.0.11
Hallo, ich lasse Snapshots von 6 IP Cams über Jarvis DisplayImage anzeigen. Fünf davon funktionieren einwandfrei. Bei der Wansview Q6 zeigt mir der Chrome und der Edge Browser nur ein schwarzes Feld für diese Cam an. Mit dem Firefox funktioniert es problemlos. 
Wenn ich die Adresse der Wansview direkt eingebe erscheint das Bild in allen Browsern.

**Comment by mcuiobroker** [comment]
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/2638 ff

**Comment by chappo59** [comment]
Note: Our cameras don’t support Edge Browser.
Zum einen versteh ich das so, dass das nur für Non Cloud Cameras gilt und da nur für Edge. Zum anderen verwende ich Chrome und habe nur zur Abklärung zusätzliche Tests mit Edge und Firefox gemacht. Wenn ich die Adresse direkt in die Browser eintrage funktioniert die Wansview sowieso überall anstandslos.

**Comment by Zefau** [comment]
Was für ein Bildformat / Dateityp ist es denn? Kannst du beispielhaft mal die URL reinkopieren? Gibt es irgendwelche Hinweise in der Browser-Konsole via F12? Siehst du in der Konsole den HTTP Status Code beim Aufruf der URL (unter Network) ?

**Comment by chappo59** [comment]
Es tut mir leid, das alles geht weit über meine Fähigkeiten und es war ja auch nur ein Test um die Funktionen von Jarvis besser kennen zu lernen. Nachdem es von mir nicht wirklich benötigt wird und sonst noch niemand ein Problem damit hat, können wir es einfach vergessen.
Danke und liebe Grüße!
Karl
