### ISSUE TITLE
DisplayImage Aktualisierungsintervall 

### ISSUE THREAD

**Issue by Trrw** [Zefau/ioBroker.jarvis#1770]
Mir ist gerade aufgefallen, dass wenn ein DisplayImage mit einem Aktualisierungsintervall eingebunden ist, die Bilder weiterhin im Hintergrund aktualisiert werden. Hier hätte ich angenommen, dass die Aktualisierung gestoppt wird, wenn man zum Beispiel den Tab wechselt. Dies ist anscheint aber nicht der fall wodurch viel Datenvolumen im Handynetz verbraucht wird.

**Comment by Zefau** [comment]
Auf welcher Version bist du? v3.0?

**Comment by Trrw** [comment]
v3.0.11

**Comment by Zefau** [comment]
@Trrw sorry, dass das so lange liegen geblieben ist. Hast du den Fehler noch mit v3.1?
