### ISSUE TITLE
v3.1.0-alpha.23 Darstellungsbeispiele fehlen bei Body Element Auswahl für einige Elemente

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1771]
![image](https://user-images.githubusercontent.com/84818934/178423862-c8c5cb7c-445d-41c0-81c0-fcb19d2e39cb.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.28`

**Comment by mcuiobroker** [comment]
2 fehlen noch LastChangeBody und SaturationSliderBody
![image](https://user-images.githubusercontent.com/84818934/181856910-5c9ac981-c419-437d-83c5-420d34a803d5.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.41`

**Comment by mcuiobroker** [comment]
v3.1.0-alpha.48
ActionElemente
![image](https://user-images.githubusercontent.com/84818934/192167696-22482ad8-47c5-499d-a64b-31a817af6181.png)

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by mcuiobroker** [comment]
Passt. Danke.
