### ISSUE TITLE
v3.0.12 Im Popup haben alle Datenpunkte den Label Namen vom Gerät

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1773]
Fehler ist wieder vorhanden.

Siehe [#1646](https://github.com/Zefau/ioBroker.jarvis/issues/1646)

**Comment by mcuiobroker** [comment]
Scheint nur bei Layout-StateList ohne Actionelement zu sein?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1477#issuecomment-1185405764

**Comment by Zefau** [comment]
`3.0.13`
