### ISSUE TITLE
v3.1.0-alpha.24 Layout Fehler 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1775]
- [ ] Falsche Anzeige der Prozentwerte

![image](https://user-images.githubusercontent.com/84818934/179429511-6f67ec0a-aadd-4bea-b8ed-b776d4efc254.png)

Größe: 12w -> 100%, ...

- [ ] Anzeige -> nur 50%?

![image](https://user-images.githubusercontent.com/84818934/179429549-92f9dfcc-4f1c-45ec-b881-0d31b6335145.png)

Von Geisterhand dann 3 Minuten später?
![image](https://user-images.githubusercontent.com/84818934/179429714-8881b6ec-c97d-4dac-bd15-855d7599e6e4.png)

Irgendwie abhängig von Bildschirmbreite?
![jarvis-v3-LayoutBreite vom Bildschirm abhängig](https://user-images.githubusercontent.com/84818934/179429841-95cc1c04-689a-47e4-9497-37314d5505e5.gif)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.31`

**Comment by mcuiobroker** [comment]
Werte sind wieder da und bei Änderung der Breite vom Fenster ist alles normal.
Danke.
