### ISSUE TITLE
v3.0.13 CSS-Editor funktioniert nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1776]
Man kann kein Return nutzen, um eine neue Zeile zu erstellen.
Mit v3.0.12 funktioniert es noch.

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
`3.1.0-alpha.25`

**Comment by mcuiobroker** [comment]
`v3.1.0-alpha.25` Änderungen (löschen) werden auch nicht gespeichert.

**Comment by Zefau** [comment]
Funktioniert bei mir problemlos. Sowohl enter als auch alles rauslöschen.

**Comment by mcuiobroker** [comment]
Ich hab es gerade noch mal installiert gehabt. Bleibt dabei funktioniert nicht.

**Comment by mcuiobroker** [comment]
#1795 Spielt vielleicht auch ne Rolle?

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.28`

**Comment by mcuiobroker** [comment]
Für v3.0.13 natürlich nicht, aber v3.1.0-alpha.28 erster Eindruck ist sehr gut.

**Comment by mcuiobroker** [comment]
Wurde mit `v3.0.15`behoben.
