### ISSUE TITLE
v3.0.12 Limit-Warnung?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1777]
![image](https://user-images.githubusercontent.com/84818934/179632800-a5b87333-2fec-41be-93c8-37dd54407939.png)

![image](https://user-images.githubusercontent.com/84818934/179632828-9d0021f6-8892-4364-9d0d-e94c9ef81b07.png)

**Comment by Zefau** [comment]
beobachte bitte nochmal mit `v3.1.0-alpha.32`

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.17`
Keinerlei Warnungen mehr erhalten.
Schließe erstmal.
