### ISSUE TITLE
Kein automatischer Reload bei Update von v3.0.11 auf v3.1.0-alpha.25

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1779]
Es wird kein automatischer Reload durchgeführt.

**Comment by Zefau** [comment]
besteht das Problem noch?

**Comment by mcuiobroker** [comment]
Die Struktur hat sich anscheinend geändert.
Anzeige unter v3.0.11
![image](https://user-images.githubusercontent.com/84818934/191112898-119d7f1c-dd75-458f-8e71-ef927920edf8.png)

Ja besteht noch 
![image](https://user-images.githubusercontent.com/84818934/191113447-32769fa7-0b10-4f0c-be95-9c67ed439f36.png)

**Comment by mcuiobroker** [comment]
Auch jetzt kein automatisher Reload von v3.1.0-alpha.45 -> v3.1.0-alpha.46.
![image](https://user-images.githubusercontent.com/84818934/191123644-d2156121-9397-4ccb-8ff9-01c751e311fd.png)

**Comment by mcuiobroker** [comment]
Was wurde an der Struktur verändert?
D.h. nicht rückwärtskompatibel? 
Wer einmal die alpha probiert, kann nicht mehr einfach zurück auf v3.0.11?
Dann müsste man neue Versionsnummer vergeben in layout?

**Comment by Zefau** [comment]
Jo, die Struktur der Widgets wird angepasst. Bisher waren direkt die Widgets im Datenpunkt. Nun ist es inklusive Versionsangabe in einer Unterebene. Restliche Struktur ist gleich. Kann also leicht manuell zurückgedreht werden.

**Comment by mcuiobroker** [comment]
Nur in den Widgets dann die version rausnehmen?

**Comment by Zefau** [comment]
aus
```
{
   ...
}
```
wurde
```
{
   "version":3,
   "signature":123,
   "widgets":{
      "..."
   }
}
```

**Comment by Zefau** [comment]
Dann mach ich erstmal zu

**Comment by mcuiobroker** [comment]
v3.1.0-beta.18 -> v3.0.15 -> keine automatischer Reload
v3.0.15 -> v3.0.11 -> kein automatischer Reload, keine Umsetzung von widgets, also inkompatibel (bleibt neue Version)
v3.0.11-> v3.1.0-beta.18 -> kein automatischer Reload

![image](https://user-images.githubusercontent.com/84818934/201427558-73745255-b859-4e45-929a-eae8dbb4a8e8.png)
