### ISSUE TITLE
Some Material-Design-Icons not working

### ISSUE THREAD

**Issue by w0nk1** [Zefau/ioBroker.jarvis#1780]
I am using v.3.0.13 and there are several icons from the material design icons which won't work, or wouldn't be recognized in the icon DP:

For example:
![Bildschirmfoto 2022-07-19 um 16 57 37](https://user-images.githubusercontent.com/6522814/179782757-9339a8cf-d4d7-45c3-8483-4761958227b3.png)

Is this a known issue? Could you upgrade the assets?

**Comment by mcuiobroker** [comment]
Basis for Icons are -> https://icon-sets.iconify.design/mdi/window-shutter-auto/

![image](https://user-images.githubusercontent.com/84818934/179899674-2920a9bf-153e-4da4-982d-c55367236e93.png)

**Comment by Zefau** [comment]
@mcuiobroker has this been resolved with v3.1 (alpha) or is this still an issue?

**Comment by mcuiobroker** [comment]
Resolved with v3.1.0-alpha.>25.
