### ISSUE TITLE
v3.1.0-alpha.25 Komischer Effekt bei Mausklick auf State-Element

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1781]
![jarvis-v3-310-alpha25 Komischer Effekt bei Mausklick](https://user-images.githubusercontent.com/84818934/179922486-d453f1a6-43a5-4945-9dfe-7083abba355a.gif)
Bei Mausklick verschwindet der StateDP-Label  bzw. wird schwarz.

**Comment by Zefau** [comment]
Auch wenn du deine Styles löschst und jarvis reloadest? Im White Mode auch?

**Comment by Zefau** [comment]
ist nun ein Duplikat zu https://github.com/Zefau/ioBroker.jarvis/issues/1776 oder?

**Comment by mcuiobroker** [comment]
Ja kann erstmal zu. Ist ja CSS.
