### ISSUE TITLE
v3.1.0-alpha.25 Binding schaltet anderen Datenpunkt

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#1783]
Hab hier zwei verschiendene Datenpunkte aus einem Gerät die mit IconButtomAction geschaltet werden (true/false)
Der eine Schalter hat im "Icon" und "IconStil" ein Binding zum anderen Datenpunkt um anzuzeigen ob das Gerät offline ist.
Schalte ich jetzt diesen Schalter, wird der andere Schalter mitgeschaltet.
Entferne ich das Binding im "Icon" und "IconStil" ist wieder alles i.O:
Kurz gefasst: Das Binding liest nicht nur den fremden Datenpunkt sondern beschreibt Ihn auch.

Icon:
{"{0_userdata.0.Test.TestSchalter6.online}=false":"lightbulb-on blink","true":"lightbulb-on","false":"lightbulb-off-outline"}

IconStil:
{"{0_userdata.0.Test.TestSchalter6.online}=false":{"color":"#FF0"},"true":{"color":"#0F0"},"false":{"color":"#F00"}}

![Animation2](https://user-images.githubusercontent.com/77005685/180103367-55595b39-96fa-40d5-bacd-42d3ad5eb612.gif)

**Comment by mcuiobroker** [comment]
Ähnlicher Fall:
Direkt nach Einstellung wurde der Wert (text) KW 15 als Wert von minus angezeigt.
Hab leider kein Bild davon, denn nach F5 war sofort wieder weg und das Ergebnis korrekt:
![image](https://user-images.githubusercontent.com/84818934/180125823-581241c1-961d-43fb-9f95-aaede8b72f68.png)
Doch noch ein Bild (nachdem ich den Wert von text KW geändert habe, kommt das als Ergebnis:
![image](https://user-images.githubusercontent.com/84818934/180125953-6cbede2e-0c05-478a-842b-3b0686490638.png)

Gerät
![image](https://user-images.githubusercontent.com/84818934/180125441-68f72bf5-c3f8-4327-984f-4ddbb2b21da2.png)
`{"default":"{0_userdata.0.jarvis.test.text}"}`
Layout
![image](https://user-images.githubusercontent.com/84818934/180125512-975bfbba-7a9b-40fb-b18e-0849dcdd7b7b.png)
DPs `minus` kommt aus testnumber
![image](https://user-images.githubusercontent.com/84818934/180125547-6738005a-c7f6-4f8b-a650-2e7f3fa1f19d.png)

![image](https://user-images.githubusercontent.com/84818934/180125612-d344a58a-6a1d-4ef8-bfbd-723b998d434d.png)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.1.0-alpha.34`

**Comment by Bernd9000** [comment]
Ja, funktioniert wieder seit `v3.1.0-alpha.34`
