### ISSUE TITLE
Jarvis Map

### ISSUE THREAD

**Issue by kilian-f-za** [Zefau/ioBroker.jarvis#1784]
Ich habe im Jarvis das Mal Widget hinzugefügt, soweit funktioniert alles aber die Datenpunkte werden nicht aktualisiert. Wenn sich der Standort ändert muss ich jedesmal die Seite komplett neu laden. Gibt es eine Möglichkeit einen auto refresh oder so einzufügen?

**Comment by mcuiobroker** [comment]
Welche Version?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/discussions/1785

**Comment by Zefau** [comment]
@kilian-f-za implementiert mit `v3.1.0-alpha.41`
