### ISSUE TITLE
Ipad Air - IOs 12.5.5 - no Connection since v.3.0.13

### ISSUE THREAD

**Issue by SebastianPaBu** [Zefau/ioBroker.jarvis#1786]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- ioBroker - jarvis 3.0.13
- Ipad Air - iOS 12.5.5 (neueste verfügbare Version)

**Describe the bug / Beschreibe den Fehler**
Seit Version 3.0.13 kann ich mit meinem IPad Air nicht mehr auf die Jarvis zugreifen. 
Das Ipad ist mein Zentraldisplay und damit ist es echt doof :-(
Fehler siehe Screenshot. 
Fehler tritt unabhängig vom verwendeten Browser auf (getestet Safari, Chrome)
Fehler tritt nur mit diesem Gerät auf. Sowohl Desktop, andere iPads (neueres iOS) und iPhones funktionieren einwandfrei.

Sollten logs benötigt werden, komm gern auf mich zu. 
![IMG_E74455167FF8-1](https://user-images.githubusercontent.com/109806829/180450439-4f09cc29-f522-4a56-80f0-b8e1a527180e.jpeg)

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/fehler-hinweise-v3#error-timeout-oefter-bei-unterschiedlichen-geraeten

**Comment by SebastianPaBu** [comment]
Bringt leider alles nichts. 

- caches gelöscht
- jarvis Adapter neu gestartet
- web Adapter neu gestartet
- iobroker neu gestartet
- Pi neu gestartet
- iPad resetet

Bringt alles nichts. 
Zurück auf 3.0.9 -> Verbindung geht.
wieder auf 3.0.13 -> keine Verbindung. (wiederholbar)

**Comment by Zefau** [comment]
Dann bleib gern auf 3.0.11. Unterschied ist unwesentlich.
