### ISSUE TITLE
HistoryGraph logarithm mode

### ISSUE THREAD

**Issue by TZanke** [Zefau/ioBroker.jarvis#1787]
**Prerequisites / Voraussetzungen**
v3.0.11 PRO

**Describe the bug / Beschreibe den Fehler**
Ich habe einen Lichtsensor, die Messwerte lasse ich als Chart darstellen. Da die Lichtwerte logarithmisch sind würde ich den Chart gerne im logarithmischen Modus laufen lassen, da aktuell wenig zu erkennen ist. Laut Apache EChart Dokumentation ist das möglich mit yaxis.type="log". Diese Option hat im jarvis entgegen anderer Optionen leider keine Wirkung.
```
{
  "min": "dataMin",
  "max": "dataMax",
  "type": "log",
  "axisLabel": {
    "formatter": "{value} LUX"
  }
}
```

**Screenshots**
![image](https://user-images.githubusercontent.com/1613368/180596547-bfedeb34-c99d-41b8-87ec-ea9efc832c00.png)

**Comment by Zefau** [comment]
fixed with `v3.1.0-alpha.26`

**Comment by TZanke** [comment]
Tested: `v3.1.0-alpha.41`

![image](https://user-images.githubusercontent.com/1613368/189524824-2868a518-b544-4832-9467-69cf061e3a4a.png)

**Comment by mcuiobroker** [comment]
Stellst du bitte auch die Parameter ein, dann übernehme ich die in die Doku. Danke.

**Comment by Zefau** [comment]
steht im Eingangspost:

```
{
  "min": "dataMin",
  "max": "dataMax",
  "typ": "log",
  "axisLabel": {
    "formatter": "{value} LUX"
  }
}
```

meinst du das?

**Comment by TZanke** [comment]
Der Parameter ist ganz normal über das Info Feld (in der Apache ECharts Doku) zu finden. In meinem initialen Post habe ich leider `typ` statt `type` geschrieben. Habe ich gerade noch angepasst.

**Comment by TZanke** [comment]
Hallo @Zefau 
Ich habe jetzt doch noch ein Problem mit dem Log-Modus. Ich dachte erst ich habe irgendwelche defekten Logdaten, das kann ich aber mittlerweile ausschließen.

Im normalen Modus (type:value) ist alles normal, stelle ich allerdings auf `type:log` um klappt das nicht soo richtig. Irgendwie vergisst er manchmal bis wohin der Graph gehen muss, und zeigt dann nur bis 10 an.

Y-Konfig: `{   "type":"log", "min": "dataMin",  "max": "dataMax",     "axisLabel": {      "formatter": "{value} LUX"    }}`

Ich weiß nicht so richtig wo es klemmt. Hast du eine Idee?

PS: Die ganzen scrollbars sind in der letzten final-Version nicht da. Die Alphas werfen damit aber um sich ;)

https://user-images.githubusercontent.com/1613368/191353807-60a5dd98-d298-47e8-8c7b-82e114b2b00e.mp4

**Comment by Zefau** [comment]
liegt wahrscheinlich an `"max": "dataMax"` oder? Vermutlich passt Echarts das auf den View an den du selektierst und kommt dann durcheinander. Funktioniert es, wenn du das raus nimmst?

**Comment by TZanke** [comment]
Danke für deine Rückmeldung. Leider macht das keinen Unterschied, gerade noch mal verifiziert.

**Comment by Zefau** [comment]
scheinbar verträgt Echarts beim type `log` keine `0` Werte

**Comment by Zefau** [comment]
Wenn du z.B. https://echarts.apache.org/examples/en/editor.html?c=line-log einen 0 Wert in irgendeine der Datenreihe einfügst, dann verschwindet die Chart-Linie komplett

**Comment by Zefau** [comment]
@TZanke schau nochmal mit `v3.1.0-beta.1` (mit der werden nun 0 Werte rausgesammelt)

**Comment by TZanke** [comment]
Klingt wie: https://github.com/apache/echarts/issues/12621

**Funktioniert!**
(PS: Ich habe seit einigen Alpha-Versionen alles voller Scrollbars)

![image](https://user-images.githubusercontent.com/1613368/197142008-63d0a6ab-51de-4be6-b3b7-346756cece1b.png)

**Comment by Zefau** [comment]
Hast du noch was spezielles konfiguriert?

**Comment by TZanke** [comment]
Ich hab die `v3.1.0-beta.1` installiert und dann ging es sofort.

**Comment by Zefau** [comment]
Ich meine mit Bezug zu den Scrollbalken. Die habe ich nicht. Ggf. kommen die wegen einer speziellen Konfiguration.

**Comment by TZanke** [comment]
Achso, das müsste ich mal ausprobieren. Bisher hatte ich die Hoffnung das es irgendwann verschwindet. Ich schau bei Gelegenheit mal rein.
