### ISSUE TITLE
v3.1.0-alpha.26 Error Connection Delayed lief aber vorher mit v3.1.0-alpha.25

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1792]
![image](https://user-images.githubusercontent.com/84818934/181367753-be3299bd-d3c2-4ea5-b9a1-24864358ecb9.png)

![image](https://user-images.githubusercontent.com/84818934/181367871-84bd3931-90df-4a88-90e9-6fb43105b749.png)

`ìob upload jarvis` hilft auch nicht

**Comment by mcuiobroker** [comment]
<html>
<body>


host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | instance system.adapter.jarvis.0 terminated with code 1 (JS_CONTROLLER_STOPPED)
-- | -- | -- | --
host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | Caught by controller[0]: }
host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | Caught by controller[0]: code: 'ERR_REQUIRE_ESM'
host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | Caught by controller[0]: at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:5:14) {
host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | Caught by controller[0]: Instead change the require of index.js in /opt/iobroker/node_modules/iobroker.jarvis/jarvis.js to a dynamic import() which is available in all CommonJS modules.
host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | Caught by controller[0]: Error [ERR_REQUIRE_ESM]: require() of ES Module /opt/iobroker/node_modules/got/dist/source/index.js from /opt/iobroker/node_modules/iobroker.jarvis/jarvis.js not supported.
host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | Caught by controller[0]: ^
host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | Caught by controller[0]: const _got = require('got');
host.iobrokerPROD | 2022-07-27 22:44:01.307 | error | Caught by controller[0]: /opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:5


</body>
</html>

**Comment by Zefau** [comment]
`v3.1.0-alpha.27`

**Comment by mcuiobroker** [comment]
Sieht gut aus. Danke.
