### ISSUE TITLE
v3.1.0-alpha.27 Sidebar Mini-Mode verursacht falsche Anzeige (Tabzeile fehlt)

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1794]
Mini-Mode ausgeschaltet:
![image](https://user-images.githubusercontent.com/84818934/181825797-2e758614-2e2f-4229-97e4-ecdf5c1d39ae.png)
Mini-Mode eingeschaltet:
![image](https://user-images.githubusercontent.com/84818934/181825975-a00fbd19-92e5-4fc0-8e76-9afba20e9d37.png)

**Comment by Zefau** [comment]
Wenn du mehr als 1 Tab drin hast, dann sollte die angezeigt werden.

**Comment by mcuiobroker** [comment]
Nur durch verkleinern vom Bildschirmbereich / Ohne Umschaltung von Mini-Mode (eingeschaltet):
![image](https://user-images.githubusercontent.com/84818934/181861421-41251841-f5c8-4d98-89d6-63374c575bb4.png)

![image](https://user-images.githubusercontent.com/84818934/181861439-7bcac52c-93a3-4427-bafc-ac4262587eee.png)

**Comment by Zefau** [comment]
Ist das korrekte Verhalten. 

Side Mode blendet Tab Leiste aus wenn nur ein Tab. Bei zwei und mehr wird die Tab Leiste angezeigt.

Außerdem wird Side Mode deaktiviert wenn zu wenig Platz.
