### ISSUE TITLE
v3.1.0-alpha.28 Seitenanzeige zu groß

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1797]
Seite wird zu groß angezeigt, obwohl nicht notwendig.
![image](https://user-images.githubusercontent.com/84818934/181861842-33704279-b1c6-43a6-bbbc-ab00ad1d78ee.png)

![image](https://user-images.githubusercontent.com/84818934/181861854-eb07d181-018a-4c74-a5f7-933522d4e293.png)
Der untere Bereich ist scollbar, wird aber nicht benötigt.

![image](https://user-images.githubusercontent.com/84818934/181861906-b5fae884-b0f3-46ae-8048-5b10b360e106.png)

**Comment by Zefau** [comment]
`v3.1.0-alpha.29`

**Comment by mcuiobroker** [comment]
Weiterhin vorhanden. Ist aber besser geworden, mein Eindruck.
![image](https://user-images.githubusercontent.com/84818934/182001775-b9be0531-f177-47fd-ab49-e0086b6df7f2.png)
Immer bei den Seiten wo die Widgets alle auf die Seite passen.
![image](https://user-images.githubusercontent.com/84818934/182001817-4c4dfb6c-727a-4dc1-a5aa-dca7bbb14408.png)

**Comment by Zefau** [comment]
Seltsam. Ich kann das wieder nicht nachstellen mit der Scrolleiste. Hab ein Widget drin und kein Scrollbalken. Muss ich was beachten?

Beim Smartphone Screenshot ist dein Hintergrundbild abgeschnitten. Die Widget Größe sieht ok aus. Der blaue Rand von Hintergrundbild unter dem Widget zeigt, dass das Widget die korrekte Größe hat, oder?

**Comment by Zefau** [comment]
Kannst du mir mal den CSS Code sowie das Bild zur Verfügung stellen? Kann es sein, dass das Bild in den Abmessungen einfach nicht groß genug ist und dadurch der schwarze Balken unten entsteht? Auf welches Element hast du das Bild gesetzt? Auf `body`?

**Comment by mcuiobroker** [comment]
```
/* CSS-ANHANG CSSTHEMES-EINSTELLUNGEN BEGIN */

.jarvis-page-container {
	background: url("https://images.hdqwalls.com/download/3d-cgi-geometry-pattern-bo-3840x2160.jpg");
}

.body--dark .jarvis-header {
	background: rgba(0,0,0,0.65) !important;
}

.jarvis-tabs-container {
	background: rgba(0,0,0,0.45) !important;
}

.jarvis-widget-container {
	background: rgba(0,0,0,0.45) !important;
}

.body--dark .jarvis-widget {
	background: rgba(0,0,0,0.45);
}

.body--light .jarvis-widget {
	background: rgba(255,255,255,1);
}

.body--dark .jarvis-tabs-container {
	background: rgba(0,0,0,0.45) !important;
}

/*
.q-table__container {
	background: transparent !important;
}
*/

/*
.q-header--bordered {
	border: 1px solid transparent !important;
}
*/

.jarvis-widget-icon {
	background: rgba(0,0,0,0.45);
}

.jarvis-header {
	background: rgba(0,0,0,0.65) !important;
}

.jarvis-sidebar {
	background: rgba(0,0,0,0.45) !important;
}

.jarvis-StateListItem-Popup {
	background: rgba(128,128,128,0.45) !important;
}

.jarvis-widget-header {
	background-color: transparent !important;
}

.q-item--dark {
	background-color: transparent;
}

.jarvis-widget-module-StateList {
	background-color: #303030;
}

.jarvis-JsonTable {
	background: transparent !important;
}

.row.items-center.q-card__section.q-card__section--vert {
	background-color: #303030;
}

.q-card__actions.q-card__actions--horiz.row.justify-end {
	background-color: #303030;
}

.cover {
	background-color: transparent !important;
}

.controls {
	background: transparent !important;
}

.track-information {
	background: rgba(25, 118, 210, 0) !important;
}

.track-duration {
	background: white;
}

.track-progress {
	background: blue;
}

.controls .jarvis-icon svg {
	color: white;
}

.controls .controlsLeft .q-btn__wrapper {
	background: transparent !important;
}

.controls .q-btn-group >.q-btn-item {
	background: transparent !important;
}

.fullscreen.scroll.jarvis-JsonTable.sticky-table-header {
	background-image: url("https://images.hdqwalls.com/download/black-gradient-b9-1920x1080.jpg") !important;
}

/* CSS-ANHANG CSSTHEMES-EINSTELLUNGEN END */

```
Auf `page-container`.

**Comment by mcuiobroker** [comment]
Scheinbar hat es etwas mit dem TAB-Wechsel zutun. Habe ich einen TAB mit Scrollleiste und klicke dann auf den daneben, wird auch die Scrollleiste angezeigt, obwohl bei dem TAB nicht erforderlich. Aktualisiere ich diese Seite ist kein Scrollbalken mehr da.

**Comment by Zefau** [comment]
Ich bekomm es leider nicht nachgestellt. Auch beim Wechsel von einer Seite / Tab mit Scrollleiste zu einer Seite / Tab ohne Scrollleiste funktioniert problemlos.

![Scroll](https://user-images.githubusercontent.com/14368811/184421859-2b5df88d-41ea-490e-a189-331b1fc7a1c5.gif)

**Comment by Zefau** [comment]
Was passiert, wenn du 
```
.jarvis-page-container {
	background: url("https://images.hdqwalls.com/download/3d-cgi-geometry-pattern-bo-3840x2160.jpg");
}
```
in änderst:
```
body {
	background: url("https://images.hdqwalls.com/download/3d-cgi-geometry-pattern-bo-3840x2160.jpg");
}

.q-layout {
    background-color: transparent;
}
```

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/184422299-57ee30cc-61d4-48c6-b01b-8267627233ae.png)
Kein Hintergrund mehr.

**Comment by Zefau** [comment]
Die Screenshots sind so klein bzw. abgeschnitten. Ich kann die nicht in Relation setzen und weiß gar nicht, was da defekt ist. Was ist denn bei deinem letzten Screenshot falsch?

Kann sein, dass es am iFrame liegt. Ist iFrame Vollbild?

**Comment by mcuiobroker** [comment]
iFrame ist kein Vollbild.
![image](https://user-images.githubusercontent.com/84818934/184426346-fbfe574b-ebc1-4121-9246-e3ad7f30f28f.png)
Wechsel auf BAD (braucht aber kein Scrollbalken, ist auch nicht da, wenn ich F5 nutze)
![image](https://user-images.githubusercontent.com/84818934/184426399-93efebb2-94cc-4153-a917-a2e81413d8c8.png)
Vom TAB Flur ausgehend auch mit Scrollbalken (F5) und Wechsel nach TAB BAD ist es normal
![image](https://user-images.githubusercontent.com/84818934/184427140-5a8f64b2-69f0-4713-9db6-e5a14d374e06.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.32`

**Comment by mcuiobroker** [comment]
Kein Unterschied. Weiterhin wird das iFrame (Home) beim Wechsel auf TAB BAD ca. 2 Sekunden auf dem TAB  BAD angezeigt und beeinflusst anscheinend dadurch die Höhenermittlung?

**Comment by mcuiobroker** [comment]
Hier ausgehend vom Flur auch mit Scrollbalken
![jarvis v3 - 10alpha32 - Problem iFrame Fenstergröße Flur](https://user-images.githubusercontent.com/84818934/184491824-840f62e0-9819-4232-b83d-ef53faaa722b.gif)

**Comment by Zefau** [comment]
Ist hier noch etwas offen, was NICHT mit einem iFrame zusammenhängt? Sonst würde ich es zu machen und via https://github.com/Zefau/ioBroker.jarvis/issues/977 bearbeiten.

**Comment by mcuiobroker** [comment]
Soweit ich beurteilen kann, hängt es "nur" mit dem iFrame zusammen. Also kann es zu.
