### ISSUE TITLE
v3.1.0-alpha.28 und einige vorher:  Aktualisierung vom Widgets-DP wird nicht im Frontend sichtbar

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1798]
Aktualisert man die die defaultPositon und den defaultZoom in einem Widget, direkt per Änderung im JSON (Widgets), so werden die Änderungen nicht im Frontend angezeigt. Erst nach F5 wird die Karte korrekt angezeigt. Dies lief unter v3.0.11.
#1784 und #1785

**Comment by mcuiobroker** [comment]
v3.1.0-alpha.29
![image](https://user-images.githubusercontent.com/84818934/182001953-9a4cfa33-a837-4ba2-998f-7d6b3ff721f2.png)
(auf History/Map info für mich)

**Comment by Zefau** [comment]
Das hattest du schon in irgendeinem Issue. Ist auch nur eine Warnung.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.41` aktualisieren nun `zoom` und `defaultPosition` wieder. Ich hab auch eine Option hinzugefügt, mit der ein Gerät verfolgt werden kann (sich die Position der Karte also dem Gerät festlegt).
