### ISSUE TITLE
v3.1.0-alpha.28: displayImage Height 1px zu viel -> Scrollbalken

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1799]
![image](https://user-images.githubusercontent.com/84818934/181862648-c13c67e0-877e-43ea-b683-762ac451123e.png)
Das Widget hat eine Höhe von 379px berechnet bekommen, aber das displayImage eine Höhe von 380px. Dadurch wird ein Scrollbalken angezeigt.

![image](https://user-images.githubusercontent.com/84818934/181862718-33ba8c1f-6153-4035-b6ca-8910bf231a9c.png)
Einstellungen:
![image](https://user-images.githubusercontent.com/84818934/181862754-cf18cdc8-f80d-4c4d-8824-cdf04517c7e8.png)

**Comment by Zefau** [comment]
`v3.1.0-alpha.29`

**Comment by mcuiobroker** [comment]
Passt. Danke.
