### ISSUE TITLE
Device configuration

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#18]
Instead of showing the configuration of devices in columns, it should be shown in rows. Especially on smaller screens this would improve the readability.

![configuration](https://user-images.githubusercontent.com/2136249/77846063-9fa9a000-71b3-11ea-850e-52ba26831a8d.png)

As my layout configuration is not visible (see #17) I cannot check if this refers only to devices.

**Comment by braindead1** [comment]
While playing with v0.1.3 I noticed that the layout configuration is far more intuitive than the configuration of devices. Instead of editing devices in columns (or rows) it would be great to have pop-ups to configure states.

I know the way devices are currently configured is due to the way the JSON is build: You first define the name of the device. Afterwards you define the states and in the last step you can customize the look of states.

From a users perspective it makes more sense to define the look of a state together with its label, state and action.

**Comment by Zefau** [comment]
Why is it more intuitive having pop-ups to configure states?

I though maybe it is best to have an optional "_guided tour_" through the declaration of a device? From a design perspective something like this: https://material-ui.com/components/steppers/

What do you think?

**Comment by braindead1** [comment]
The main issue I see regarding configuring devices is that the "Jarvis" column contains options for the device (e.g. "group", "label" and "divider") and options for states (e.g. "icon", "value" and "styles"). 

A "guided tour" only makes sense if you want to keep the way to configure devices, whiche means turning the columns into steps of the "guided tour". In my opinion this is not user firendly.

Instead you should configure devices like the layout: 
* Click on "Add device" and configure "name" group", "label" etc.
* Then click on "Add state" and configure "label", "state", "action" and "icon", "value", "style" etc.

**Comment by Zefau** [comment]
> The main issue I see regarding configuring devices is that the "Jarvis" column contains options for the device (e.g. "group", "label" and "divider") and options for states (e.g. "icon", "value" and "styles").

I agree, this is inconsistent and should be changed.

> A "guided tour" only makes sense if you want to keep the way to configure devices, whiche means turning the columns into steps of the "guided tour". In my opinion this is not user firendly.

I would see both. Keeping the table and additionally implement a guided tour which is started when a user clicks on `add new device` button for the first time.

> Instead you should configure devices like the layout:
> - Click on "Add device" and configure "name" group", "label" etc.
> - Then click on "Add state" and configure "label", "state", "action" and "icon", "value", "style" etc.

Good idea.

**Comment by Zefau** [comment]
@braindead1 Could you try and install v0.2.0 from Github ? I reworked the devices screen and would appreciate your feedback. Cheers

**Comment by braindead1** [comment]
The new dialog is a huge improvement! As you changed the JSON structure of devices I first had to adopt my JSON, but now it's working again. 

Some things I noticed:
- If I want to change an existing device I'm not able so save the device configuration until I remove the existing group and add it again.
- Saving a device does not mean that it is really saved. Instead the change is transferred into the device list, which then has to be saved. The save button of the device should be renamed to e.g. "Apply".
- The name of a device is used as display name. I have a tab for lights, with my room names as subcategories. I nearly every room I have ceiling spots. As I don't want to have the room name being part of the display name, a lot of my devices are called "Deckenspots", which is confusing in the device list. There should be the possibility to distinct between the device name "Wohnimmer Deckenspots" and the display name "Deckenspots".

**Comment by Zefau** [comment]
> If I want to change an existing device I'm not able so save the device configuration until I remove the existing group and add it again.

Should be fixed now.

> Saving a device does not mean that it is really saved. Instead the change is transferred into the device list, which then has to be saved. The save button of the device should be renamed to e.g. "Apply".

True story. I have changed that one.

> The name of a device is used as display name. I have a tab for lights, with my room names as subcategories. I nearly every room I have ceiling spots. As I don't want to have the room name being part of the display name, a lot of my devices are called "Deckenspots", which is confusing in the device list. There should be the possibility to distinct between the device name "Wohnimmer Deckenspots" and the display name "Deckenspots".

I added another field for a display name. Is that what u meant? The display name only applies for the list of devices in the configuration, right? Or is that also meant for the widget? Guess not, because then the device name would be obsolete.

> Defining subcategories is only possible via editing the JSON. It should also be possible via the UI dialog. Additionally the subcategory should be part of the group. As of now you define the group and the subcategory on the same level. The result is that if you add a device to multiple groups, they all include the subcategory which does not make sense in all cases.

True story. Since jarvis is still in an early version, there is much space for improvements. Could you create a new issue for this?

> New states of a device are added at the top. There should be the possibility to order states.

Added.

> It is not possible to enter JSON for Display and Icon of a new state. It is saved as string and is therefore not working.

True story. I have fixed that one.

**Comment by Zefau** [comment]
Would you test and verify v0.3.0 ? Thanks

**Comment by braindead1** [comment]
> > If I want to change an existing device I'm not able so save the device configuration until I remove the existing group and add it again.
> 
> Should be fixed now.

Fixed.

> > Saving a device does not mean that it is really saved. Instead the change is transferred into the device list, which then has to be saved. The save button of the device should be renamed to e.g. "Apply".
> 
> True story. I have changed that one.

Working as expected.
 
> > The name of a device is used as display name. I have a tab for lights, with my room names as subcategories. I nearly every room I have ceiling spots. As I don't want to have the room name being part of the display name, a lot of my devices are called "Deckenspots", which is confusing in the device list. There should be the possibility to distinct between the device name "Wohnimmer Deckenspots" and the display name "Deckenspots".
> 
> I added another field for a display name. Is that what u meant? The display name only applies for the list of devices in the configuration, right? Or is that also meant for the widget? Guess not, because then the device name would be obsolete.

This is not working as expected. I'll create a separate issue as my idea for configuration can be far more than having just one additional field.

> > Defining subcategories is only possible via editing the JSON. It should also be possible via the UI dialog. Additionally the subcategory should be part of the group. As of now you define the group and the subcategory on the same level. The result is that if you add a device to multiple groups, they all include the subcategory which does not make sense in all cases.
> 
> True story. Since jarvis is still in an early version, there is much space for improvements. Could you create a new issue for this?

I'll create a separate issue for that.

> > New states of a device are added at the top. There should be the possibility to order states.
> 
> Added.

This is not working. I'll create a separate issue.

> > It is not possible to enter JSON for Display and Icon of a new state. It is saved as string and is therefore not working.
> 
> True story. I have fixed that one.

Working as expected.
