### ISSUE TITLE
Jarvis Vis direkt öffnen

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#180]
Jarvis lässt sich über Port 8082 sowie 8084 nicht direkt öffnen, es braucht immer den weg über iobroker selbst

**Comment by Zefau** [comment]
@duczz bitte mal die `1.1.0-beta.35` probieren, damit sollte es nun besser klappen.

**Comment by darkdevil373** [comment]
Bei mir klappt es nun wieder. Danke
