### ISSUE TITLE
v3.1.0-alpha.28 Beim Umschalten zwischen den Tabs iframe bleibt länger sichtbar

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1800]
Auffallend ist ,dass ein iFrame beim Umschalten von einem TAB auf einen anderen TAB länger stehen bliebt als sonst.
![jarvis-v3-10alpha28 iFrame bleibt länger sichtbar auf anderem TAB](https://user-images.githubusercontent.com/84818934/181863127-a3a78e9d-6449-4988-85dc-250f4e76f31d.gif)

**Comment by Zefau** [comment]
Duplikat zu https://github.com/Zefau/ioBroker.jarvis/issues/977. Tritt wahrscheinlich nur mit aktivierter Option "aufrechterhalten" auf?

**Comment by mcuiobroker** [comment]
War aber mit v3.1.0-alpha.1x noch nicht aufgefallen. Aufrechterhalten ist aktiv.
