### ISSUE TITLE
v3.1.0-alpha.28: State Zustände werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1801]
![image](https://user-images.githubusercontent.com/84818934/181863450-03ad812b-7117-4354-bd95-951216330234.png)
Plötzlich `Use in Action` obwohl keine Gruppe definiert ist, nur Divider.
![image](https://user-images.githubusercontent.com/84818934/181863625-b5a06b44-04bc-4d15-b3ca-5478501dd050.png)
Auch nach F5 keine Besserung.
![image](https://user-images.githubusercontent.com/84818934/181863728-90ca7741-0dcc-4c1c-abf6-3b6fcf539be0.png)

![image](https://user-images.githubusercontent.com/84818934/181863699-ad5344d0-b2e6-4612-8d22-225fcb9aa123.png)

![image](https://user-images.githubusercontent.com/84818934/181863746-a9f9acc7-c425-4924-9020-962be8efc530.png)
Nur darunter ist eine Gruppe definiert.
Auch der Bezug 17 Tage ist nicht erklärbar. Schaltet man so werden die Lampen geschaltet und die LastChangeBody korrekt angezeigt. Drückt man dann F5 sind wieder 17Tage angezeigt und die Schalter sind eingeschaltet, obwohl das Licht aus ist.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.30`

**Comment by Zefau** [comment]
>  Alle Zustände sind falsch. Das hängt mit den Gruppen zusammen? Denn nur dort ist eine Gruppe darunter definiert.

Hast du das Problem auch, wenn du die Gruppen entfernst ?


>  Die Elemente haben ein Use in Action, obwohl keine Gruppe da ist. (siehe oben)

Ist in der ganzen StateList nur die eine Gruppe drin? Kannst du mal die ganze Konfiguration screenshoten?

Bei mir sieht es gut aus:

![image](https://user-images.githubusercontent.com/14368811/182469245-099d8e76-c23a-4ca5-88ca-a5021f807695.png)

![image](https://user-images.githubusercontent.com/14368811/182469501-d44b7518-8e32-4327-b1ec-510d6a21f46f.png)

**Comment by mcuiobroker** [comment]
Ist nicht mehr da?
![image](https://user-images.githubusercontent.com/84818934/182470154-917deeaf-3750-4f8d-8c22-992cb195949d.png)
Ich schick gleich mal die ganze JSON dazu.

**Comment by mcuiobroker** [comment]
Auch wenn ich die Gruppe rausnehme sind die Werte wie im GIF falsch.

**Comment by mcuiobroker** [comment]
Mit `v3.1.0-alpha.35` tritt es nicht mehr auf.
