### ISSUE TITLE
v3.1.0-alpha.28 Längere Zeit mit F12 gearbeitet -> Widgets werden beim F12 beenden nicht angepasst

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1802]
Hat man längere Zeit F12 an, so bei Abschalten mit F12 dieser Bildschirm angezeigt.
![image](https://user-images.githubusercontent.com/84818934/181864068-470f99cc-39d5-4133-9ae1-06450743cc9f.png)
Die Widgets werden nicht mehr angepasst.

**Comment by Zefau** [comment]
besteht das Problem mit v3.2 noch?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
Hast du eine Idee, wie ich da nachgestellt / reproduziert bekomme? Wenn ich die Browser-Konsole mit F12 länger offen habe passiert bei mir nichts. Gehst du mehrmals in die Konfiguration oder wechselst den Tab oder irgendwas bestimmtes?

**Comment by mcuiobroker** [comment]
Bei offenem F12-Log -> F5 und dann F12

**Comment by Zefau** [comment]
Ok, bei angedockter Browser-Konsole bekomme ich es natürlich nachgestellt. Hab das Ding bei mir immer als eigenes Fenster abgedockt.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.59` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.59` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
??
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/224bca23-0a97-4fac-bd94-7df98f58bad7)
