### ISSUE TITLE
Zeitweiliger Ausfall des Wettermoduls: Incorrect localidad or affiliate_id given!

### ISSUE THREAD

**Issue by Andr3asB** [Zefau/ioBroker.jarvis#1803]
Fehler: **"Incorrect localidad or affiliate_id given! Please provide exact localidad and affiliate_id in module config!"**

Bei mir läuft der javris Adapter v3.0.13 und ich sehe in der Version (aber auch schon ein paar Releases davor) immer wieder mal und nach längerer Benutzung (Display bootet morgens und läuft dann den ganzen Tag über) einen Fehler im Wettermodul. Die Meldung kommt tendenziell eher am Nachmittag/Abend, aber auch nicht täglich, sondern eher so alle 3-5 Tage.

![image](https://user-images.githubusercontent.com/44557554/182019379-3c420fbb-687a-4e34-9bef-0ba1a9f188cb.png)

Der Fehler sieht dann wie folgt aus:
**"Incorrect localidad or affiliate_id given! Please provide exact localidad and affiliate_id in module config!"**
![image](https://user-images.githubusercontent.com/44557554/182019428-64b9bae7-4e18-4c33-85a7-d37727dae6ae.png)

Die Konfig sieht wie folgt aus:
![image](https://user-images.githubusercontent.com/44557554/182019727-8a84584f-4e09-4fd3-ad78-1e71fcaa9aff.png)
der Ort ist eine 5-stellige Zahl und der API-Schlüssel funktioniert ja meistens, kann also auch nicht falsch sein.

Da am Display keine Tastatur angeschlossen ist, kann ich dort leider die Browserconsole nicht ohne weiteres starten und der Fehler tritt ja nicht geplant auf, sondern meist dann, wenn man es grade nicht passt.

**Comment by Zefau** [comment]
bitte mit `v3.1.0-alpha.38` beobachten, ob es noch auftritt

**Comment by RkcCorian** [comment]
@Zefau : Hab die ```v3.1.0-alpha.40``` im Einsatz und bei mir tritt es auch immer mal wieder auf

**Comment by Zefau** [comment]
bitte nochmal mit `v3.1.0-alpha.43` beobachten

**Comment by Andr3asB** [comment]
Der Fehler war bei mir nach dem Wechsel auf die Version 3.1.2 verschwunden. Jetzt hatte ich neulich zeitweise eine Beta installiert um #2331 zu testen und bin danach wieder auf 3.1.2 zurück (Backup eingespielt).
Plötzlich taucht der Fehler unter 3.1.2 wieder auf.
@Zefau Möchtest Du einen neuen Issue haben, oder den hier wieder öffnen?

**Comment by apachelance** [comment]
Kann ich bestätigen. Tritt bei mir auch im Browser nach einiger Zeit der Inaktivität auf. Nach einem Reload ist es wieder ok.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@Andr3asB Kam das nochmal vor mit der v3.2?

**Comment by Andr3asB** [comment]
@Zefau Ich bin noch auf 3.1.8. Ist 3.2 denn schon so weit, dass man das produktiv einsetzen kann?
