### ISSUE TITLE
Height option affects wrong Panel

### ISSUE THREAD

**Issue by TZanke** [Zefau/ioBroker.jarvis#1804]
**Prerequisites / Voraussetzungen**
3.0.11

**Describe the bug / Beschreibe den Fehler**
If option "Höhe aller Widgets identisch mit sichtbarer Seitenhöhe" is enabled for Desktop, and a Smartphone Layout is set, the option will affect the Smartphone Layout too. Ignoring the setting made for Smartphone layouts.

**Screenshots**
![image](https://user-images.githubusercontent.com/1613368/182031122-692ebc16-6b34-4698-8a0f-ec3cb44b092b.png)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.1.0-alpha.32`

**Comment by TZanke** [comment]
Tested: `v3.1.0-alpha.41`

Funktioniert jetzt wie gewünscht auf Mobilgeräten. Danke!
