### ISSUE TITLE
import Option und jquery Unterstützung für scripts

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1805]
Mit import "http://192.168.178.89/download/scripts.js"; kann man mometan keine Skripte importieren.
Es kommt der Fehler:
![image](https://user-images.githubusercontent.com/84818934/182241692-efba893f-feca-482a-bdff-1367edfc2695.png)

Ziel war es den ProjektCode von einem Projekt auszulagern und zu importieren.
Vielleicht ist es auch der falsche Ansatz?

`<script type="module" src="http://192.168.178.89/download/scripts.js"></script>` oder

`<link rel="module" as="script" crossorigin="" href="http://192.168.178.89/download/scripts.js">`
So funktioniert es auch nicht:
![image](https://user-images.githubusercontent.com/84818934/182242433-6d123a5a-4360-4e50-946d-5d3d8f006d84.png)

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.30`

**Comment by mcuiobroker** [comment]
Super. Funktioniert. Danke.

**Comment by mcuiobroker** [comment]
Hat man einen import definiert, ändert dann etwas in der Konfiguration und klickt dann aber auf `abrechen`, werden die Variablen teilweise angemeckert. 
![image](https://user-images.githubusercontent.com/84818934/182260481-685fd03d-5db5-4967-8b12-c8dfcd95f817.png)

**Comment by Zefau** [comment]
> Hat man einen import definiert, ändert dann etwas in der Konfiguration und klickt dann aber auf abrechen, werden die Variablen teilweise angemeckert.

Kann ich so nicht nachstellen. Kannst du mal den Script-Reiter zeigen und das File, dass du importierst?


> jQuery wird noch nicht unterstützt

Musst du selbst importieren via CDN https://releases.jquery.com/

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/182448790-d169bf22-dbd5-4364-a1a1-e6c043c99538.png)
Musste Endung ändern für github (kein js).
[scripts.txt](https://github.com/Zefau/ioBroker.jarvis/files/9244835/scripts.txt)

**Comment by Zefau** [comment]
`import "https://code.jquery.com/jquery-3.6.0.js";`

**Comment by mcuiobroker** [comment]
Den parse Fehler einfach auskommentieren.
![image](https://user-images.githubusercontent.com/84818934/182451128-63c72007-239f-4462-85e8-362bf198b93f.png)
![image](https://user-images.githubusercontent.com/84818934/182451211-a4b26f12-38a6-4d1a-b1d8-5cfd236bb1b8.png)

**Comment by Zefau** [comment]
> Hat man einen import definiert, ändert dann etwas in der Konfiguration und klickt dann aber auf abrechen, werden die Variablen teilweise angemeckert.

Weiß nicht, wie ich das lösen soll. Siehe https://stackoverflow.com/questions/9425910/load-and-unload-javascript-at-runtime:
> So what actually happens when you remove an external JavaScript or CSS file? Perhaps not entirely what you would expect actually. In the case of JavaScript, while the element is removed from the document tree, any code loaded as part of the external JavaScript file remains in the browser's memory. That is to say, you can still access variables, functions etc that were added when the external file first loaded

Scheinbar werden externe JavaScript Dateien in den Browser Memory geladen und sind auch nach dem Entfernen noch aufrufbar. 

jarvis entfernt beim Abbrechen oder Speichern die alten Imports und ersetzt diese mit den neuen Imports (auch, wenn es dieselben sind). Dadurch wird eine eventuelle Änderung innerhalb der Dateien übernommen - aber eben auch der von dir identifizierte Fehler ausgeworfen, weil die alte Datei noch im Memory ist.

Also entweder muss ich einen kompletten Reload machen, um den Memory zu löschen oder es gibt keinen Hot Reload der Inhalte der Import-Dateien.

Eine andere Lösung fällt mir gerade nicht ein :-\

**Comment by mcuiobroker** [comment]
Reload ist ok

**Comment by mcuiobroker** [comment]
Fehler kommt auch, wenn ich jQuery importiere
![image](https://user-images.githubusercontent.com/84818934/182461407-7cb0cc86-4315-42c8-b0c8-97feb0d4e921.png)
```
import "https://code.jquery.com/jquery-3.6.0.js";

import "http://192.168.178.89/download/scripts.js";

$("#Button5").on('click',function(){
   console.log('Jquery funktionierit');
});
```

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.31`

**Comment by mcuiobroker** [comment]
Sieht gut aus. Danke. Bitte bei Feststellung vom Fehler direkt neuladen, keine Popup-Anzeige:
![image](https://user-images.githubusercontent.com/84818934/184227471-0d03e076-c11b-427e-a6cc-7c0e61c032bd.png)
evtl. wie beim Update in rot unten kurz 2 Sekunden den Grund anzeigen, warum Reload und dann aber neu laden.
Danke.

**Comment by Zefau** [comment]
Was steht in der Browser Konsole? Gibt es da mehr Informationen?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/184303430-c194e509-5e46-4ca2-81d0-d8c1ac696398.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.32`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/184473960-6acec772-74f5-4a1a-b866-187e426e5bb1.png)

Gerät-Änderung -> Jetzt wird der Fehler nur im DOM angezeigt. Aber es wird nicht aktualisiert, auch die Veränderung im Gerät (Farbänderung) wird nicht angezeigt.

**Comment by Zefau** [comment]
ist nun ja ein Duplikat zu https://github.com/Zefau/ioBroker.jarvis/issues/1696#issuecomment-1213576280, insofern lass es uns dort weiterverfolgen
