### ISSUE TITLE
Keine Selektion mit Eingabe bei Widgetdefinition Module-Eingabe

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1807]
Hat man früher ein Text eingegeben bei der Module-Auswahl wurde je nach Eingabe direkt das Module eingegrenzt.
![image](https://user-images.githubusercontent.com/84818934/182414531-aa69f114-336c-407d-bee4-13a4350104a9.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.31`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/184235449-39d922d4-c87d-404b-b64b-0a97bbcba627.png)
Passt. Danke.
