### ISSUE TITLE
"Error: Installation inconsistent" auch nach Neuinstallation vom Adapter

### ISSUE THREAD

**Issue by Reto84** [Zefau/ioBroker.jarvis#1808]
Hallo zusammen,

Nach einem Update auf 3.0.11 startete Jarvis zwar, jedoch nach 2-3 Sekunden kommt eine rote Seite mit "Error: Installation inconsistent":

![jarvis](https://user-images.githubusercontent.com/81419898/183103108-4cd21d0f-90b6-40fc-8aa8-ca79f241e47a.JPG)

Ich weiss das der Fehler bekannt ist (auch im Wiki) habe dann folgendes pobiert ohne Erfolg:

- Jarvis Adapter neu gestartet
- Web Adapter neu gestartet
- Iobroker komplette VM neu gestartet
- Jarvis Adapter deinstalliert (iobroker neu gestartet)
- Jarvis Adapter neu installiert

Nach der Neuinstallation kam das Initialsetup, was jedoch auch nach ein paar Sekunden in der roten Seite endet.

Ich weiss zur Zeit nicht mehr weiter, bringe Jarvis nicht mehr zum laufen.

Hier noch die Iobroker Details:

_PlatformBetriebssystem:linux
Architektur:x64
CPUs:4
Geschwindigkeit:1800 MHz
Modell:Intel(R) Core(TM) i5-6260U CPU @ 1.80GHz
RAM:7.6 GB
System-Betriebszeit:01:45:31
Node.js:v12.22.12
time:1659711584990
timeOffset:-120
Adapter-Anzahl:423
NPM:8.16.0
Datenträgergröße:68.3 GB
freier Festplattenspeicher:51.3 GB
Betriebszeit:01:45:21
Aktive Instanzen:23
Pfad:/opt/iobroker/_

Danke!

Gruss Reto

**Comment by mcuiobroker** [comment]
Welche Version?

**Comment by Reto84** [comment]
Ja klar, habe ich vergessen: 3.0.11

**Comment by mcuiobroker** [comment]
Einstellungen von der Instanz als Bild.

**Comment by Reto84** [comment]
![Uploading jarvis2.JPG…]()

**Comment by Reto84** [comment]
"Evtl Programm laufen lassen"

![jarvis3](https://user-images.githubusercontent.com/81419898/183112819-0fd4254e-406f-4dd0-baec-c16a70e2456d.JPG)

**Comment by mcuiobroker** [comment]
Ist den noch was in den DPs?jarvis.0.devices?

**Comment by Reto84** [comment]
![image](https://user-images.githubusercontent.com/81419898/183113812-35c346eb-a4ce-450e-9b55-d75d6bde23ea.png)

![image](https://user-images.githubusercontent.com/81419898/183113931-e712c35f-b9de-47ea-8b09-9e1c7f1ae0e6.png)

**Comment by mcuiobroker** [comment]
Irgendetwas ist bei der Konvertierung schiefgelaufen. 
Du hast nur noch die Devices. Layout ist nicht konvertiert.
Die DPs hast du vorher gespeichert in txt Dateien?

**Comment by Reto84** [comment]
komisch, ich habe nochmals den Adapter gelöscht und wieder installiert, nun läufts...

Gerne würde ich aber noch die Device, Layout, settings und Widgets zurückspielen. Ich habe vorher in den Adaptereinstellungen unter Backups die Daten in Text-Dateien kopiert, wie kann ich diese wieder "zurückspielen".

Vielen Dank!

**Comment by mcuiobroker** [comment]
Musst du dir aus der Sicherung backitup zurückholen.

**Comment by Reto84** [comment]
PErfekt, vielen Dank für die Unterstütztung!

**Comment by mcuiobroker** [comment]
Wenn es bei Dir läuft, bitte den Issue schließen. Danke.
