### ISSUE TITLE
v3.1.0-alpha.30 - "undefined" bei Werten ohne Einheit

### ISSUE THREAD

**Issue by Joshude** [Zefau/ioBroker.jarvis#1809]
**Prerequisites / Voraussetzungen**
- **v3.1.0-alpha.30**

**Describe the bug / Beschreibe den Fehler**
Ist in den Eigenschaften des Datenpunktes kein Eintrag bei "Einheit" wird ein "undefined" angezeigt. 
Exemplarisch ist auf dem Screenshot für den Monat Feburar eine Einheit angegeben. 

**Screenshots**
![image](https://user-images.githubusercontent.com/46825690/183612360-bc1ae95b-d6a4-4a27-a989-7aa91e3ff43c.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.31`

**Comment by Joshude** [comment]
Passt, danke!
