### ISSUE TITLE
Allow JavaScript in CustomHTML module

### ISSUE THREAD

**Issue by msussek** [Zefau/ioBroker.jarvis#181]
Ich verwende folgendes CustomHTML, um den MJPEG-Stream meiner Überwachungskamera im Browser darzustellen:

```
<html>
<head>
</head>
<body>
    <img src="http://192.168.178.87/jpgmulreq/1/image.jpg?key=<<meinZugriffsschlüssel>>&amp;lq=0" width="640" height="480" class="myclass">

    <script>
        setInterval(function(){
			
            refreshImg();
        }, 1000);
        // 1000 = 1 seconds, change to whatever you like

        function refreshImg(){
			var j = 0;
            var x = document.querySelectorAll("img.myclass");
			for (var i = x.length - 1; i >= 0; i--) {
				j = j + 1;
                x[i].src = "http://192.168.178.87/jpgmulreq/1/image.jpg?key=<<meinZugriffsschlüssel>>&amp;lq=" + new Date().getTime();
                console.log(x[i].src);
            };
        }
		
	
    </script>
</body>
</html>
```

Das Javascript darin soll das image.jpg jede Sekunde durch ein aktuelles austauschen, dies geschieht, indem an die ImageSource noch ein Parameter` &lq=<<aktuellesDatum>>` per Javascript angehängt wird, wodurch das Bild neu geladen wird,

Leider funktioniert das jedoch nicht unter Verwendung von Custom HTML in Jarvis wie gewünscht, es wird dann nur der statische Inhalt (also ein Standbild) angezeigt, jedoch findet kein dynamischer Austausch des Parameters `&lq` statt.

Wenn ich obiges HTML jedoch in eine Datei speichere und diese direkt im Browser öffne, funktioniert es einwandfrei.

Ist dies eventuell noch ein Bug oder mache ich hier einen Fehler?

**Comment by Zefau** [comment]
Das Widget ist nicht für JavaScript gedacht. Ich muss es aber eh überarbeiten, weil es nicht so funktioniert wie gewollt. Ich werd mal schauen, ob ich das unter bekomme.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/502364
> Wie kann ich folgenden String in Jarvis anzeigen lassen? (In der normalen Vis mach ich das via HTML)
<script src="https://widgets.coingecko.com/coingecko-coin-price-static-headline-widget.js"></script>
<coingecko-coin-price-static-headline-widget coin-ids="bitcoin" currency="eur" locale="de" background-color="#ffffff"></coingecko-coin-price-static-headline-widget>

**Comment by Zefau** [comment]
@msussek bitte probiere mal die beta-35, ob es damit nun klappt.

**Comment by msussek** [comment]
Kannst du mir bitte sagen, wenn es diese Version auf npmjs gibt (latest repo)? Würde nur ungerne Adapter den direkt aus github installieren.

**Comment by Zefau** [comment]
> Kannst du mir bitte sagen, wenn es diese Version auf npmjs gibt (latest repo)? Würde nur ungerne Adapter direkt aus github installieren.

In Q4 jetzt denke ich. Solange es offene Issues gibt bleibt es beta. Die rc geht dann ins latest.
