### ISSUE TITLE
v3.1.0-alpha.32 Wetter nur blaues Laufband

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1810]
Wetter wird nicht mehr angezeigt.
![image](https://user-images.githubusercontent.com/84818934/184473694-ec5a49f0-859d-45db-8e38-7de736022b9c.png)

![image](https://user-images.githubusercontent.com/84818934/184508429-8972afec-0723-411c-897d-867d744b53c7.png)

**Comment by Zefau** [comment]
bitte mit `v3.1.0-alpha.33` prüfen

**Comment by mcuiobroker** [comment]
Blaues Laufband ist weg. Bilder werden aber nicht angezeigt. Gibt dazu nicht noch einen Issue?Auf dem Handy schlecht zu suchen.

**Comment by mcuiobroker** [comment]
![Screenshot_20220815-233546_Edge.jpg](https://user-images.githubusercontent.com/84818934/184723162-87605473-3d42-4b5a-be27-78339c445726.jpg)
![Screenshot_20220815-233438_Edge.jpg](https://user-images.githubusercontent.com/84818934/184723185-dbd8704d-a691-48ca-b5e4-d905d44a3b72.jpg)

**Comment by mcuiobroker** [comment]
Läuft wieder. Danke.
