### ISSUE TITLE
Uhrzeit

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1811]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.0.11] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Hallo,

wie bekomme ich die Uhr größer? Ich bin der Meinung in v2 war das sehr einfach möglich. Wie geht es in v3?

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/85995176/185335209-7ec47f66-6713-4ceb-b43c-013cc620e7e9.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/styles/datetime-groesse-und-farbe

**Comment by Mephisto090** [comment]
Danke
