### ISSUE TITLE
Anzeige des Rollstandes 0-1 bei Homematic IP Geräten

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#1812]
Hallo! Erstmal ist der Adapter wirklich gut! Komme gerade von Habpanel! Hol mir auch die Pro-Version, um den Entwickler zu unterstützen!  Meine Herausforderung. Der Level des Rollos wird von 0 - 1 angezeigt. Nicht von 0 - 100. Bei 50% ist es auch im Datenpunkt 0,5. Wie kann ich es in der Anzeige manipulieren? Leider habe ich fast keine Ahnung von Json. Hatte gedacht, ob der Wert vom Datenpunkt nicht mal 100 gerecht werden kann? Die Steuerungsanzeige wäre auch schön, wenn diese von 0-100 angezeigt werden könnte! Wollte nicht für jeden Rollo eine Alias anlegen!
![Bildschirmfoto 2022-08-18 um 12 30 23](https://user-images.githubusercontent.com/104907692/185377271-7d03ce7e-3bf3-4d1f-b719-c154952d773f.png)
![Bildschirmfoto 2022-08-18 um 12 32 08](https://user-images.githubusercontent.com/104907692/185377277-1805c109-ba30-4bea-a98a-527256993c6f.png)
![Bildschirmfoto 2022-08-18 um 12 30 58](https://user-images.githubusercontent.com/104907692/185377280-51c14a3b-6bf9-4bbb-b3ef-c7a2f272788f.png)
![Bildschirmfoto 2022-08-18 um 12 31 46](https://user-images.githubusercontent.com/104907692/185377282-3f1666c3-980f-4302-bced-6c26f2d31b07.png)

**Comment by mcuiobroker** [comment]
Datenpunkt-Eigenschaften im DP Level
`{"value" : "val => Math.floor(val*100)"}`
Bitte versuchen.

**Comment by bambi-arch** [comment]
Danke für die schnelle Antwort. Es kommt jedoch die Meldung das "Value" erst ab Pro geht! Wollte erst noch etwas schnuppern, bevor ich wirklich umsteige und das Abo abschließe! Gibt es noch eine andere Möglichkeit?
![Bildschirmfoto 2022-08-18 um 14 15 26](https://user-images.githubusercontent.com/104907692/185392338-5c303d8b-e3f8-4d32-abf1-7d08afe84023.png)
![Bildschirmfoto 2022-08-18 um 14 11 46](https://user-images.githubusercontent.com/104907692/185392343-6c120a87-5b47-4cb9-a111-d17ba426c3ac.png)

**Comment by mcuiobroker** [comment]
Nein.

**Comment by mcuiobroker** [comment]
Evtl mit alias arbeiten?

**Comment by bambi-arch** [comment]
Hatte ich auch schon überlegt! Aber bei 20 Stück!?

**Comment by mcuiobroker** [comment]
Jetzt gibt es das Abo noch für 12 Euro,  wer weiß wie lange noch?

**Comment by bambi-arch** [comment]
Hab ich schon gelesen! Versteh ich aber nicht? Einmal bezahlen und dann Abo beenden aber die Pro Funktionen weiter nutzen?

**Comment by mcuiobroker** [comment]
Du kannst die Pro Funktionen 1 Jahr nutzen.

**Comment by Zefau** [comment]
Du kannst in der v3.1 bei LevelBody das MarkerLabel (`marker`) ändern, siehe https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/geraet/body-element/levelbody#levelbody-fuer-werte-0-1-homematicip.

Ist allerdings auch Pro.
