### ISSUE TITLE
v3.1.0-alpha.35 HistoryGraph Zeitraum wird nicht eingehalten

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1814]
Hat man einen Zeitraum von 7 Tage für die Anzeige der Werte eingestellt, sollte auch der letzte Tag `heute` 18.08. sein?
Der DP liefert aber keinen Wert, da das Gerät gar nicht an ist.
![image](https://user-images.githubusercontent.com/84818934/185496219-daa9f293-bd49-4e7b-90fa-7ef7fbf722cb.png)
Bei den Benzin Preisen liefert er weiterhin Werte und diese werden korrekt angezeigt
![image](https://user-images.githubusercontent.com/84818934/185496552-04cc48bd-f861-4f67-9779-5ccc1adfa202.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.46`

**Comment by mcuiobroker** [comment]
Passt, Danke.
