### ISSUE TITLE
Homematic IP Rolladenaktor ohne Taster HMIP-Froll

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#1815]
Hallo,

die Geräte werden importiert, jedoch ohne die Funktion "Stop". Es werden auch sehr viele (22 Datenpunkte) übermittelt. Es würden eigentlich ja 5 reichen!
![Bildschirmfoto 2022-08-19 um 09 39 04](https://user-images.githubusercontent.com/104907692/185569977-e1b5cf3a-86d0-4f55-a0f4-898b6860f6dc.png)
![Bildschirmfoto 2022-08-19 um 09 37 52](https://user-images.githubusercontent.com/104907692/185569982-f21113b6-f09e-455b-aea4-fe965f362298.png)
! Beeinträchtigt das nicht die Ladezeit?

Es gibt unterschiede Anzahl der Datenpunkte und Bezeichnungen zu den Geräten Broll und Froll, siehe Bilder. Der Datenpunkt "stop" fehlt. Auch ist "activiti" nicht vorhanden bzw. hat einen anderen Namen.

**Comment by Zefau** [comment]
@bambi-arch Welche jarvis Version hast du im Einsatz? Und meinst du `hm-rpc` oder `hmip` ?

Die Datenpunkte kann ich so anhand der Konfiguration nicht nachvollziehen.

BROLL:
```
"HmIP-BROLL": {
	"level": {
		"state": ".3.LEVEL",
		"action": ".4.LEVEL"
	},
	"level2": {
		"state": ".3.LEVEL2",
		"action": ".4.LEVEL2"
	},
	"activity": {
		"state": ".3.ACTIVITY_STATE"
	},
	"stop": {
		"action": ".4.STOP"
	}
},
```

FROLL:
```
"HmIP-FROLL": {
	"level": {
		"state": ".3.LEVEL",
		"action": ".4.LEVEL"
	},
	"activity": {
		"state": ".3.ACTIVITY_STATE"
	},
	"stop": {
		"action": ".4.STOP"
	}
},
```

Kannst du die in der Konfiguration angegeben Datenpunkte mal mit deinem Objekt-Baum abgleichen?
Stimmen die? Fehlt was?

**Comment by bambi-arch** [comment]
Ich habe v3.0.13. Es geht um HMIP. 

Broll:
![image](https://user-images.githubusercontent.com/104907692/191181688-dc937f72-c2ca-4e76-8c18-d85f66bd7a84.png)

Froll:
![image](https://user-images.githubusercontent.com/104907692/191181966-b465f890-d27e-47f9-ac83-94abf493c95c.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.53`
