### ISSUE TITLE
Adpater Geräte Somfy Tahoma

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#1816]
Hallo,

bitte im Geräteimport mit integrieren. Wenn Datenstruktur benötigt wird, kann ich gerne per Screen liefern. Besonders die Dachfenster und Markiesensteuerung!
![Bildschirmfoto 2022-08-19 um 09 52 03](https://user-images.githubusercontent.com/104907692/185571537-ee5c8da0-c279-4bde-b30d-b6ea2dba1455.png)
![Bildschirmfoto 2022-08-19 um 09 52 28](https://user-images.githubusercontent.com/104907692/185571547-fe80c584-6fed-48bc-b5c5-5b468e382a70.png)
![Bildschirmfoto 2022-08-19 um 09 53 32](https://user-images.githubusercontent.com/104907692/185571551-fc48b7cd-b694-4707-b361-68d1a45a7d8e.png)
![Bildschirmfoto 2022-08-19 um 09 53 47](https://user-images.githubusercontent.com/104907692/185571555-6bb34170-a639-4d15-8869-c82404d7952f.png)

Danke im Voraus

**Comment by Zefau** [comment]
Ist das `tahoma.0`? Ist das ein Duplikat zu https://github.com/Zefau/ioBroker.jarvis/issues/740 ?

**Comment by bambi-arch** [comment]
> Ist das `tahoma.0`? Ist das ein Duplikat zu #740 ?

Ja es handelt sich um tahoma.0!

**Comment by Zefau** [comment]
Dann gerne #740 hochvoten.
