### ISSUE TITLE
v3.1.x > Button: ZEIGE NUR DATENPUNKT WERT funktioniert nicht korrekt

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1818]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [3.1.0-alpha.35] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [s.u.] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Erwartetes Verhalten:
- Wenn AUS dann Text anzeigen
- Wann AN dann Button anzeigen (zum Ausschalten) und keine Text

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

Falsches Verhalten mit v3.1.0-alpha.35: Text fehlt, obwohl entsprechend konfiguriert
<img width="658" alt="image" src="https://user-images.githubusercontent.com/79741077/185800695-1312513a-0bc2-494d-a088-277e1c0c038f.png">

Erwartetes Verhalten nur, wenn DATENPUNKT-WERT ANZEIGEN true ist, ABER dann wird der Wert auch mit dem Button angezeigt, was nicht gewünscht ist, siehe folgendes 2tes Bild
<img width="668" alt="image" src="https://user-images.githubusercontent.com/79741077/185800786-b0cef3d3-9c04-44e8-b9f3-ee37fa2b9ed6.png">

<img width="669" alt="image" src="https://user-images.githubusercontent.com/79741077/185800868-75d0fc5f-fd2b-42f4-9745-5040012e615b.png">

Vgl. auch Konfig...
<img width="755" alt="image" src="https://user-images.githubusercontent.com/79741077/185800955-7699c4ff-8e20-44e2-9a0c-fa880e1ae4a0.png">

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.39` behoben sein

**Comment by RkcCorian** [comment]
Jup, funktioniert. :-)
