### ISSUE TITLE
Import Silvercrest Branded HMIP Window Contacts 

### ISSUE THREAD

**Issue by sristo** [Zefau/ioBroker.jarvis#1822]
I have a mixture of original HmIP-SWDM Window contacts which are supported fine and Silvercrest (Lidl)-Branded ones which are not detected,

I figured out that they just have a different Type in the Object Tree:

Silvercrest (not imported)
  "native": {
    "TYPE": "HmIP-SWDM-B2",
    "SUBTYPE": "SWDM",

Original HmIP (imported just fine)
  "native": {
    "TYPE": "HmIP-SWDM",
    "SUBTYPE": "SWDM",

Apart from that the Object Tree is identical, as it is in fact the same device, just with another "TYPE".

If I manually change the type to "HmIP-SWDM" they are imported just fine. I have a lot of them and if the hm-rpc adapter reloads all devices, those manual changes are overwritten. 

So if you could just add an "alternative type name" or switch to the SubType for detection of those devices this would be perfect.

Thanks a lot for your great work.

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.39` importiert werden

**Comment by sristo** [comment]
tut wie erhofft :-)
getestet mit v3.1.0-alpha.41
