### ISSUE TITLE
v3.1.0-alpha.35 Darstellung mit einem TAB falsch

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1823]
Layout nur mit einem TAB
![image](https://user-images.githubusercontent.com/84818934/186650044-713985e4-e343-40b1-9c75-14f2b7dbf455.png)
Ansicht (falsch)
![image](https://user-images.githubusercontent.com/84818934/186649976-b7ed54e7-2d68-477d-b8a2-b3a2ae1e59cf.png)

Ergänzt man einen TAB erscheint es so
![image](https://user-images.githubusercontent.com/84818934/186649802-837e2f30-2c1d-44ae-86b3-b2c8a47df23d.png)

**Comment by Zefau** [comment]
ist das noch aktuell? bei mir schaut es gut aus

**Comment by mcuiobroker** [comment]
Definitiv. Ja.

**Comment by Zefau** [comment]
ach, das ist auf mobil? auf Desktop ok?

**Comment by mcuiobroker** [comment]
Auch mobil
![image](https://user-images.githubusercontent.com/84818934/188978515-7f54cf81-0379-4282-820f-06afce3ee154.png)

**Comment by Zefau** [comment]
Ok, ich hab Sidebar Minimode an. Wenn es aus ist, tritt der Fehler auf.

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.39` behoben sein

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/188988084-58056c2f-6076-411b-8639-e040003542a9.png)

**Comment by mcuiobroker** [comment]
margin-top scheint nicht korrekt zu sein?
![image](https://user-images.githubusercontent.com/84818934/189214102-e5c65a3c-e31a-497a-a244-889e88773766.png)
So ist es korrekt?
![image](https://user-images.githubusercontent.com/84818934/189214280-89f99bf6-c239-458b-8153-358050615267.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.40`

**Comment by mcuiobroker** [comment]
Passt. Danke.

**Comment by RkcCorian** [comment]
Auch für mich 😃. Bin jetzt mal auf die v3.1.0-alpha.40 umgestiegen.
