### ISSUE TITLE
v3.1.0-alpha.35 Fehler im time value?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1827]
Welcher DP /Gerät/ Widget betroffen?
![image](https://user-images.githubusercontent.com/84818934/186975992-0985924d-19e2-40bb-b118-7bd6584bef72.png)
Mehrere betroffen.
![image](https://user-images.githubusercontent.com/84818934/186976284-c1c80f87-c896-420e-b6ba-6d3850e0520f.png)

**Comment by Zefau** [comment]
kommt aus der JsonTable. Hast du einen Callback hinterlegt?

**Comment by mcuiobroker** [comment]
Könnte es mit den `ms` zusammenhängen?
![image](https://user-images.githubusercontent.com/84818934/188751111-3e4a1824-46d6-475b-9d49-0f51bd75b140.png)
