### ISSUE TITLE
v3.1.0-alpha.35 Close statt Schliessen im Popup

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1828]
![image](https://user-images.githubusercontent.com/84818934/186976902-7fa8f82c-1ef4-4268-9f0a-d6e9afaf3e31.png)

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.36` behoben

**Comment by mcuiobroker** [comment]
Ok. Danke.
