### ISSUE TITLE
jsonTable - json-Objekte in JSON-Table anzeigbar machen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1829]
![image](https://user-images.githubusercontent.com/84818934/186977781-b55bfea2-6deb-4003-b39a-2cdac9b790d6.png)
```
[
  {
    "adapterName": "admin",
    "instanzen": 2,
    "adapterVersion": "5.3.8",
    "datum": "Freitag 26.08.2022 21:15:04",
    "adapterDatum": "Sonntag 31.07.2022 23:56:17",
    "adapterVersionArray": [
      {
        "version": "5.3.8",
        "datum": "Sonntag 31.07.2022 23:56:17"
      }
    ],
    "datumTS": 1661541304824,
    "adapterDatumTS": 1659304577408
  },
  {
    "adapterName": "alexa2",
    "instanzen": 1,
    "adapterVersion": "3.13.0",
    "datum": "Freitag 26.08.2022 21:15:04",
    "adapterDatum": "Sonntag 21.08.2022 03:05:23",
    "adapterVersionArray": [
      {
        "version": "3.13.0",
        "datum": "Sonntag 21.08.2022 03:05:23"
      }
    ],
    "datumTS": 1661541304824,
    "adapterDatumTS": 1661043923783
  },
  {
    "adapterName": "backitup",
    "instanzen": 1,
    "adapterVersion": "2.4.12",
    "datum": "Freitag 26.08.2022 21:15:04",
    "adapterDatum": "Donnerstag 25.08.2022 19:51:21",
    "adapterVersionArray": [
      {
        "version": "2.4.12",
        "datum": "Donnerstag 25.08.2022 19:51:21"
      }
    ],
    "datumTS": 1661541304824,
    "adapterDatumTS": 1661449881096
  }
]
```

**Comment by Zefau** [comment]
Wie stellst du dir das vor? Das "Unterobjekte" dann komplett in einer Spalte oder dann auf eine Spalte je Schlüssel des Unterobjekts?

**Comment by mcuiobroker** [comment]
Die Unterobjekte würden in der Spalte untereinander mit entsprechender Überschrift dargestellt. Wie ne interne Tabelle?

**Comment by Zefau** [comment]
Untereinander? Dann wird die Zeile aber hoch.

**Comment by mcuiobroker** [comment]
Ja. Nur die Überschrift sollte ganz oben einmal vorhanden sein? Vielleicht kann man sie auch weg lassen?

**Comment by Sineos** [comment]
http://tabulator.info/examples/5.3#tree
http://tabulator.info/examples/5.3#nested-tables

Das wären für mich nützliche Beispiele

**Comment by mcuiobroker** [comment]
Die angeführten Beispiele (tabulator.info) stellen keine Tabellenwerte innerhalb einer Tabelle dar? Nicht gefunden.

**Comment by Zefau** [comment]
JSON Objekte werden aufgelöst und in je einer Spalte dargestellt. Der Feature Request ist also schon umgesetzt.

**Comment by mcuiobroker** [comment]
Leider nein.
![image](https://user-images.githubusercontent.com/84818934/192860659-ec4d00c2-de0f-4f1f-887e-f6cf608d66a0.png)

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by mcuiobroker** [comment]
werden jetzt nebeneinander angezeigt. Sie sollten untereinander angezeigt werden.
![image](https://user-images.githubusercontent.com/84818934/193360134-6d128314-0832-4203-ad64-e3e7bcb2ed47.png)

version                       datum
![image](https://user-images.githubusercontent.com/84818934/193360183-a7cf070a-70a6-4fa4-aee3-f4e0015b56a3.png)
![image](https://user-images.githubusercontent.com/84818934/193360203-55fe8382-34b4-44d6-971f-6b33cbc6e4bb.png)
![image](https://user-images.githubusercontent.com/84818934/193360213-c7febcdf-0d94-4655-acb9-4556f209af96.png)

**Comment by Zefau** [comment]
Geht nur nebeneinander. Alles andere wäre dann eine andere Technologie wie tabulator
