### ISSUE TITLE
v3.1.0-alpha.35 jsonTable Sortierversuch

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1831]
![image](https://user-images.githubusercontent.com/84818934/186979641-5951d781-fe38-4957-b28d-04c92ed66c43.png)

Bei Klick auf `adapterDatum` oder `datum` zur Sortierung

![image](https://user-images.githubusercontent.com/84818934/186979742-1b4daee3-9495-4059-b248-c3ba6d95c60e.png)

Beispiel-Daten
`
[
  {
    "adapterName": "admin",
    "instanzen": 2,
    "adapterVersion": "5.3.8",
    "datum": "26.08.2022 22:00:27",
    "adapterDatum": "31.07.2022 23:56:17",
    "adapterVersionArray": [
      {
        "version": "5.3.8",
        "datum": "31.07.2022 23:56:17"
      }
    ],
    "datumTS": 1661544027908,
    "adapterDatumTS": 1659304577408
  },
  {
    "adapterName": "alexa2",
    "instanzen": 1,
    "adapterVersion": "3.13.0",
    "datum": "26.08.2022 22:00:27",
    "adapterDatum": "21.08.2022 03:05:23",
    "adapterVersionArray": [
      {
        "version": "3.13.0",
        "datum": "21.08.2022 03:05:23"
      }
    ],
    "datumTS": 1661544027908,
    "adapterDatumTS": 1661043923783
  },
  {
    "adapterName": "backitup",
    "instanzen": 1,
    "adapterVersion": "2.4.12",
    "datum": "26.08.2022 22:00:27",
    "adapterDatum": "25.08.2022 19:51:21",
    "adapterVersionArray": [
      {
        "version": "2.4.12",
        "datum": "25.08.2022 19:51:21"
      }
    ],
    "datumTS": 1661544027908,
    "adapterDatumTS": 1661449881096
  },
  {
    "adapterName": "birthdays",
    "instanzen": 1,
    "adapterVersion": "2.1.0",
    "datum": "26.08.2022 22:00:27",
    "adapterDatum": "31.05.2022 15:14:26",
    "adapterVersionArray": [
      {
        "version": "2.1.0",
        "datum": "31.05.2022 15:14:26"
      }
    ],
    "datumTS": 1661544027908,
    "adapterDatumTS": 1654002866878
  }
]
`

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.36` behoben

**Comment by mcuiobroker** [comment]
Ok.Danke.
