### ISSUE TITLE
v3.1.0_alpha.35 HistoryGraph mouseover / hover-Anzeige zu weit rechts

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1832]
Die man bei der Mouseover/hover-Anzeige zu weit rechts im Darstellungs-Bereich werden die Werte nicht mehr angezeigt.
![image](https://user-images.githubusercontent.com/84818934/186989765-940c87f1-a637-419a-be9c-99bd39938929.png)

**Comment by Joshude** [comment]
Ich möchte noch hinzufügen, dass auch der z-index des mouseover-popups nicht passt. 
Bin inzwischen bei Alpha 40
![image](https://user-images.githubusercontent.com/46825690/189530351-5f822d4d-a99f-4151-b6ad-4464c84a2fc3.png)

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.42`

**Comment by mcuiobroker** [comment]
Bei mir passt es, Danke.
@Joshude ?
