### ISSUE TITLE
v3.1.0-alpha.35 BodyElement LastChangeBody

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1833]
Beim Start ist ok, dass das BodyElement LastChangeBody erst später angezeigt wird. 
Beim direkten Schalten, sollte es aber sofort aktualisiert werden.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.38`

**Comment by mcuiobroker** [comment]
sieht gut aus. Danke.
