### ISSUE TITLE
v3.0.11 - LightHueBody Farben stimmen nicht ganz 

### ISSUE THREAD

**Issue by Reto84** [Zefau/ioBroker.jarvis#1834]
Hallo zusammen,

Stelle ich den Hue Outdoor Strip via LightHueBody auf komplett Rot:

![image](https://user-images.githubusercontent.com/81419898/187082745-a901ff15-f15c-4aee-a56e-22e66074c332.png)

leuchtet der Strip nur Orange, in der App sieht man es dann:

![image](https://user-images.githubusercontent.com/81419898/187082856-cf2241a3-1dad-4304-b27d-4473fc760116.png)

Das ist auch mit dem Blau z.B. so. Man kommt mit dem LightHueBody einfach nicht ganz an den "Rand" des keises in der App. Kann man hier noch was einstellen?

Danke&Gruss Reto

**Comment by Zefau** [comment]
Was für ein Farbcode wird denn in den Datenpunkt geschrieben?

**Comment by Reto84** [comment]
Hier der Datenpunkt wenn ich LightHueBody komplett recht "voll Rot" schalte:
![image](https://user-images.githubusercontent.com/81419898/187085128-a8ef3224-c962-4a16-9d6d-00f4d56047f4.png)

und hier wenn ich via App auf +- ganz an den Rand "voll Rot" schalte:
![image](https://user-images.githubusercontent.com/81419898/187085195-16fee7fd-5fac-4f73-bd38-7c0afaa56b8b.png)

Bei der LightHueBody auf voll Rot sollten vermutlich Blue und Green auf 0 sein.

**Comment by Zefau** [comment]
In dem ersten Screenshot ist der `colormode` auf `hs`. Er nimmt also `hue` und `sat` (`saturation`). `sat` steht nur auf 140, geh dort mal auf 255 hoch.

Beim zweiten Screenshot steht es auf `xy`. Er nimmt also einen anderen Datenpunkt / Wert. Dadurch der Unterschied. Spiel mal mit `sat`und schau, was raus kommt.

**Comment by Zefau** [comment]
@Reto84 ich würde zu machen, da kein jarvis-spezifisches Issue, sondern hue Adapter?
