### ISSUE TITLE
Datenpunkt-acknowledge auch für LightColorBody und LightHueBody u.a.

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1837]
Bei ButtonAction, ButtonGroupAction, DatePickerAction, IconButtonAction, IconState, LightHueAction, LightColorBody und LightHueBody fehlt der ack für den Datenpunkt.
Wäre sinnvoll es für alle einstellbar zu machen?

- [ ] LighColorAction hat keine Einstellung?

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.40`

**Comment by mcuiobroker** [comment]
Ist vorhanden. Danke.
