### ISSUE TITLE
v3.1.0-alpha.35 customTextBody im Layout Labelbeschreibung fehlt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1838]
![image](https://user-images.githubusercontent.com/84818934/187741482-0b988b56-79a7-4155-8436-f24e7135b61b.png)

- [ ] #1862

**Comment by Zefau** [comment]
Ist das noch aktuell?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
![image](https://user-images.githubusercontent.com/14368811/188961614-692bbfce-9e22-4631-886a-c1a565a05dd4.png)

bei mir ist es übersetzt? Wo genau bist du da unterwegs?

**Comment by mcuiobroker** [comment]
Im Layout und dann umstellen auf customTextBody.

**Comment by Zefau** [comment]
Komisch..

![image](https://user-images.githubusercontent.com/14368811/188961956-13556e35-4c8e-4afa-988d-5cf5df5a14b6.png)

**Comment by mcuiobroker** [comment]
Auch nach einem Upload (iob upload jarvis) wird es noch falsch angezeigt.

**Comment by Zefau** [comment]
wie sieht es mit `v3.1.0-alpha.38` aus?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/188966716-d828e5c5-3d13-431d-a6cd-837d49e486b2.png)

**Comment by Zefau** [comment]
Kannst du mal ein Gerät neu der Liste hinzufügen und CustomText wählen. Ist es dann auch? Oder nur bei dem bestehenden Element?

**Comment by mcuiobroker** [comment]
Auch bei neu angelegtem Gerät.
![image](https://user-images.githubusercontent.com/84818934/188974169-43e3a00d-65b5-47af-bfcd-059c48e31d4f.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.39` behoben sein

**Comment by mcuiobroker** [comment]
Passt. Danke.
![image](https://user-images.githubusercontent.com/84818934/188990547-4022aaaa-78f2-4d66-a153-aff1ea56da42.png)
