### ISSUE TITLE
v3.1.0-alpha.35 DatePickerBody

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1839]
Es wird keine `Heute Button` angezeigt, obwohl in den Optionen auswählbar.
![image](https://user-images.githubusercontent.com/84818934/187748901-91383ac0-5836-4961-9c15-ec8c7706f917.png)
Setzt man Kompakt auf false erscheint
(immer nach F5 Aktualisierung)
![image](https://user-images.githubusercontent.com/84818934/187749206-391e301d-c708-4754-952d-14dfa2a767d0.png)
Mal so
![image](https://user-images.githubusercontent.com/84818934/187749891-7c28a4d2-d1b8-4e56-a35d-1472a3cbde4d.png)

**Comment by Zefau** [comment]
Ist das auf Desktop oder mobil?

**Comment by mcuiobroker** [comment]
Desktop

**Comment by mcuiobroker** [comment]
Alternative?
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/date
![image](https://user-images.githubusercontent.com/84818934/187775801-73d2af75-91c8-4853-86b1-204367c73d8c.png)

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.38` habe ich die `landscape` Option entfernt. Der Heute-Button erscheint nur, wenn der Minimal Mode aus ist.
