### ISSUE TITLE
WhiteSliderBody linear gradient umgekehrt darstellbar -> Heizung?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1842]
Mit einer zusätzlichen Option in den Komponenten-Optionen, könnte man die farblichen linear-gradient von orange-> blau umkehren, um sie auch für Heizungseinstellungen zu nutzen?

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.39` hinzugefügt

**Comment by mcuiobroker** [comment]
Passt. Danke.
