### ISSUE TITLE
v3.1.0-alpha.35 Gewerk Fenster blindLevelAction keine Standard-DP activity und stop

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1844]
Mit v3.1.0-alpha.35 oder vorher wurde BlindLevelAction auch für Fenster zugelassen.

- [ ] Standard-Datenpunkte

Sollte dann nicht auch die Standard-Datenpunkte entsprechend angepasst werden und activity und stop, die in den Optionen fest eingestellt sind, mit angelegt werden?

- [ ] Warnung beim Layout, das die festeingestellten DPs nicht angelegt sind, falls jemand ohne die Standard-DP arbeitet?
Oder die eingestellten DPs dort in den Optionen, dann löschen und nur als Hinweis anzeigen?

- [ ] Keine Farbänderung bei stop: true -> grau, stop:false -> grau? 
Sollte es bei stop: false nicht rot sein?

**Comment by Zefau** [comment]
Also `activity` und `stop` ergeben ja nur bei elektrischen Fenstern Sinn, oder? Insofern könnte es für alle anderen, die nur "normale" Fenster haben verwirrend sein, wenn die Datenpunkte mit drin sind. Was meinst du? Ggf. sonst ein ganz eigenes Gewerk?

**Comment by mcuiobroker** [comment]
War das nicht der Grund warum du es für Fenster eingerichtet hast? Es hat doch mit elektrischen Fenster den Issue angelegt. Kann momentan nicht nachschauen.

**Comment by Zefau** [comment]
Jo, das war der Grund. Die Frage war eher, ob es noch mehr Anwendungsfälle (bei Fenstern) gibt oder es sich nur darauf beschränkt.

Bin einfach nur am überlegen, was am besten ist. Also entweder zwei Gewerke, da die Datenpunkte doch so unterschiedlich sind oder nicht.

**Comment by mcuiobroker** [comment]
2. Gewerk wird wohl besser sein. Da die Frage, wenn schon an die Gewerke gehst, ob du dort eigene Gewerke direkt mitmachen kannst? Quasi, dass man im Feld Gewerke selbst was eingeben kann? Oder eigene Gewerke anlegen, die dann auch ausgewählt werden können? (Dürfte aber länger dauern?)

**Comment by Zefau** [comment]
So einfach / schnell ist das leider nicht implementiert.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.41` habe ich das Gewerk hinzugefügt

**Comment by mcuiobroker** [comment]
ok.
