### ISSUE TITLE
v3.1.0-alpha.35 Gruppe hinzufügen Übersetzung

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1845]
StateListe Gruppe hinzufügen
![image](https://user-images.githubusercontent.com/84818934/188025551-69c7bb80-4bc1-4282-b057-3b265129ca37.png)

- [x] Add Group -> Gruppe hinzufügen?

- [x] Group Element -> Gruppen Element

![image](https://user-images.githubusercontent.com/84818934/188025772-f5ea6b97-54c8-4c79-a930-bf662dde7915.png)

- [x] Anzeigevariante aus welchem DP für die Gruppe? Man müsste Gerät und den DP angeben können?
![image](https://user-images.githubusercontent.com/84818934/188025910-2ab7c293-b7b0-437a-af92-17faa04734d7.png)

- [x] ButtonGroupAction setzt keinen Wert? (siehe unten GIF) Nur für die Gruppe? Dann sollte es für die StateList nicht auswählbar sein?

![image](https://user-images.githubusercontent.com/84818934/188026336-467bf3c2-2e3a-451f-8490-f94a48596e0b.png)

- [x] ButtonGroupAction Schalter turn off ist Umschalter?
![jarvis v3 - alpha 35 ButtonGroupAction Fehler](https://user-images.githubusercontent.com/84818934/188027195-2fa70622-38b7-4066-9af8-340a0a2b4949.gif)

**Comment by Zefau** [comment]
`ButtonGroupAction` hatte ich bzgl. Gruppen gar nicht implementiert / vergessen. Funktioniert aktuell nur für normale StateList Einträge.

**Comment by Zefau** [comment]
Nachtrag: "normale" Einträge schalten nicht, wie du es schon darstellst. oh man...

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.36` behoben (Option "Anzeige-Variante benutzen" beim Gruppen-Element entfernt).

**Comment by mcuiobroker** [comment]
Es wird gar nichts mehr angezeigt?

![image](https://user-images.githubusercontent.com/84818934/188499999-5e306f40-1054-4ee5-8bc6-11c762eeac8c.png)


Anzeigevariante im normalen Schalter noch drin?

![image](https://user-images.githubusercontent.com/84818934/188499967-41f7467e-38c4-445a-956f-22d30f4323ec.png)

![image](https://user-images.githubusercontent.com/84818934/188499901-a5fbe2c5-5e28-4682-9e63-c4a652f05251.png)

**Comment by Zefau** [comment]
Jo, ich hab doch geschrieben 
> Option "Anzeige-Variante benutzen" beim Gruppen-Element entfernt

In der Gruppe habe ich die Option entfernt, da diese keine Anzeige-Variante hat. Die Option mit der Anzeige-Variante geht demnach nur bei Geräten.

**Comment by mcuiobroker** [comment]
Ja, aber was muss ich denn dort eintragen? {"false":"Nö","true":"Jo"} um auf den Buttons dann Nö und Jo zu sehen?

**Comment by Zefau** [comment]
Jo genau.
