### ISSUE TITLE
v3.1.0-alpha.35 IconButtonAction

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1846]
ButtonGröße Icon wächst nicht mit, bzw. verändert sich nicht.
![image](https://user-images.githubusercontent.com/84818934/188030197-0822d0f6-bf37-4e20-9ac8-d2fbbffb940d.png)
Das Icon bleibt immer gleich groß, egal was man einstellt

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.36` behoben

**Comment by mcuiobroker** [comment]
Das Icon ist nicht zentriert.
![image](https://user-images.githubusercontent.com/84818934/188499287-39dc6cd2-8ae2-441e-84ac-3115a13b9a50.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.37` passen (du bist aber auch sehr genau ;-) )

**Comment by mcuiobroker** [comment]
Die Position passt, super. Danke. Jetzt stimmt die Anzeige vom Datenpunkt-Wert nicht.
bei false wird nicht s angezeigt
![image](https://user-images.githubusercontent.com/84818934/188754430-4834aaa8-7e9d-49ff-b313-f98fb2753555.png)
bei true schon
![image](https://user-images.githubusercontent.com/84818934/188754496-8035b02c-1c46-4107-8d02-df74c244cfdc.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.38`

**Comment by mcuiobroker** [comment]
Passt. Danke.
