### ISSUE TITLE
v3.1.0-alpha.35 und vorher InputAction Number

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1847]
Wenn ein ioBroker-DP als number definiert ist, bekommt man immer einen Fehler im LOG angezeigt, da jarvis immer bei InputAction einen String sendet. Da sollte der Type vom hinterlegten DP abgefragt werden?

![image](https://user-images.githubusercontent.com/84818934/188058528-8fcd1c4d-d520-4b37-b039-f9e36b328bb2.png)

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.36` behoben

**Comment by mcuiobroker** [comment]
Bekomme immer noch die Meldung?
![image](https://user-images.githubusercontent.com/84818934/188498118-d6fc8ae3-9e74-46f1-9b62-69e25d7e7011.png)
![image](https://user-images.githubusercontent.com/84818934/188498142-93d4de7d-4704-4cc1-bb11-5a74ad4df51c.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.37` passen

**Comment by mcuiobroker** [comment]
Passt. Danke.
