### ISSUE TITLE
LightColorState Wählbares Icon mit der State-Farbe anzeigen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1848]
Es sollte erweitert werden, damit man damit auch ein ausgewähltes Icon(zusätzliche Option) in der State-Farbe darstellen lassen kann.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.36` implementiert

**Comment by Zefau** [comment]
`LightColorState` sollte nun analog zum normalen State die Farben und co. mitnehmen (ohne zusätzliche Option, per default)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/188505727-3d32dcfe-5114-4eee-9c63-df95b8fc9661.png)
![image](https://user-images.githubusercontent.com/84818934/188505758-adecc786-e280-4b66-a4c5-117b93e09e57.png)
Jetzt müsste was in rot dargestellt sein?

**Comment by Zefau** [comment]
Dann hatte ich es falsch verstanden. Es wird nun die Anzeige-Variante korrekt angewandt. Die wurde vorher ignoriert.

Jetzt weiß ich aber, was du mit State-Farbe meinst.

**Comment by mcuiobroker** [comment]
Ziel istes , daß man die ausgewählte Farbe auch sofort sieht, als Icon oder als farblichen Text. Deswegen auch die Auswahl von einem Icon für den LightColorState, so dass man das ausgewählte Icon (rechts) dann in der gewählten Farbe sehen kann.

**Comment by Zefau** [comment]
Mit `v3.1.0-alpha.37` nun mit entsprechender Option. Wenn deaktiviert, dann nutzt er den State-Wert.

**Comment by mcuiobroker** [comment]
Deaktiviere ich die Option, wird jetzt der State-Wert in der Farbe angezeigt. Super, Danke.
Wie würde eine passende Anzeige-Variante aussehen?

**Comment by Zefau** [comment]
Anzeige-Variante ist quatsch. Da war ich gedanklich noch beim der ButtonGroup. Der StateStyle für die Anzeige ist natürlich gemeint. Also der ganz normale aus dem Gerät. Ich korrigiere das Wording.

**Comment by mcuiobroker** [comment]
Kannst du bitte in die Komponenten-Optionen noch ein Icon reinsetzen, da es viele/einige Leute gibt, die gerne nur mit Icon-Anzeigen arbeiten? Also wird irgendwann wieder hoch kommen?

**Comment by Zefau** [comment]
Achso, haha, das meintest du mit dem Feature Request? Jetzt verstehe ich, was du willst.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.38`

**Comment by mcuiobroker** [comment]
Sehr schön. Danke.
![image](https://user-images.githubusercontent.com/84818934/188992017-94d67e12-409f-4ac7-a9bb-34614ed386fe.png)
