### ISSUE TITLE
v3.1.0-alpha.35 LightHueAction Wert wird nicht angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1849]
Bei der Auswahl sollte der Wert, rechts unten angezeigt werden.

![image](https://user-images.githubusercontent.com/84818934/188060799-2b6043e6-3ac2-4f4f-b70e-06c5e4a647c1.png)

Beim RGB-Wert wird er angezeigt, aber auch nur der schon definierte, nicht der ausgewählte.
![image](https://user-images.githubusercontent.com/84818934/188061016-26bb7d0e-dee6-4f1d-b490-3e4583ede70e.png)

- [x] Bei Auswahl vom neuen Wert verlängert sich die HUE Auswahl?
![image](https://user-images.githubusercontent.com/84818934/188061149-bb6b09ba-5182-41b1-adc9-8999ac18263a.png)
![image](https://user-images.githubusercontent.com/84818934/188061181-8be03eb8-439e-4a93-b6b4-5bbdff28b3f2.png)

- [x] Schliessen statt Close

- [x] Fehler Breite beim Aufrufen?
![jarvis v3 - alpha 35 LightHueAction Auswahl Fehler breite](https://user-images.githubusercontent.com/84818934/188062456-98ef563e-5f4e-46b5-9a7f-ccc3b2d5e9c4.gif)

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.36` behoben

**Comment by mcuiobroker** [comment]
Ok. Danke
