### ISSUE TITLE
Wrong data format for ColorTemp with Hue

### ISSUE THREAD

**Issue by tipp88** [Zefau/ioBroker.jarvis#1850]
Following message in the Logs: State value to set for "zigbee.0.001788010ba89186.colortemp" has to be type "number" but received type "string"
This is Philipps Hue bulb connected through Zigbee, When changing Color Temp in Jarvis the above message is given.

![image](https://user-images.githubusercontent.com/68737433/188110646-7f91afef-ab8d-4c99-8357-5d1cd39b0c0c.png)

**Comment by Zefau** [comment]
Which Component are you using in jarvis that is sending a string instead of a number?

**Comment by Zefau** [comment]
@tipp88 should be fixed via https://github.com/Zefau/ioBroker.jarvis/issues/1847, please confirm

**Comment by tipp88** [comment]
Keine Änderung mit der neusten Alpha Version. Ich verwende das StateList widget im Jarvis um die Farbtemparatur der Hue Lampe zu setzen die über Zigbee angebunden ist.

**Comment by tipp88** [comment]
Sorry, keine Änderung mit der neusten Alpha. Der Fehler kommt noch immer State value to set for "zigbee.0.001788010ba89186.colortemp" has to be type "number" but received type "string"

Ich verwende das StateList widget im Jarvis um die Farbtemperatur der über Zigbee angebundenen Hue Lampe zu setzen. Es funktioniert auch, aber diese Message oben wird jedesmal geloggt.

**Comment by Zefau** [comment]
Kannst du mir sagen mit welcher Komponente du schaltest? Oder einfach ein Screenshot.

**Comment by tipp88** [comment]
@Zefau 
Klar:
![Jarvis_String_Info1](https://user-images.githubusercontent.com/68737433/189327673-3ce88eee-a084-4e20-8ce1-179c7d163416.jpg)
![Jarvis_String_Info](https://user-images.githubusercontent.com/68737433/189327677-bd45b6ea-3cf1-4f0f-ab6d-88bf76e27ae3.jpg)
![jarvis_vers](https://user-images.githubusercontent.com/68737433/189327678-d77f5f25-2c47-4589-bcf0-7de3e0e5a421.jpg)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.41`

**Comment by tipp88** [comment]
@Zefau 
funktioniert überhaupt nicht. Der Adapter Adapter crasht mit uncaught exception
![image](https://user-images.githubusercontent.com/68737433/189510539-13d8581d-f018-4172-b425-d2d0b2b1b307.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.42`

**Comment by tipp88** [comment]
sieht gut aus
