### ISSUE TITLE
v3.1.0-alpha.>=35 Timepicker schreibt Uhrzeiten ohne führende Nullen

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#1855]
Betrifft Diskussion https://github.com/Zefau/ioBroker.jarvis/issues/569#issuecomment-1217197602
Ich wollte es nochmal nach oben bringen und habe jetzt dafür dieses Issue aufgemacht.

@Zefau . Du hattest es ja in v.35 schon angepasst. Jedoch wird der ausgewählte Wert, trotz Maskierung HH:mm nicht korrekt weggeschrieben:

![image](https://user-images.githubusercontent.com/22911084/188382591-542008bc-92dd-41b3-951e-a5e52ecea9c2.png)
![image](https://user-images.githubusercontent.com/22911084/188382654-7c0bc228-5b4e-40d8-a683-ac9f5c02f5ed.png)

**Comment by Zefau** [comment]
ich kümmere mich zeitnah drum (via 569)
