### ISSUE TITLE
Weather no icon at alpha 36

### ISSUE THREAD

**Issue by mericon** [Zefau/ioBroker.jarvis#1856]
Hi,

leider werden noch immer keine wetter icons angezeigt.

unter version 3.013:

`<img` src="img/weather_set5_9.9dc0f52e.png" alt="" `height="50">`

und unter version 3.1 Alpha 36

`<img` alt height="50">``

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.37` passen

**Comment by mericon** [comment]
Ist gefixt ;) genial wie schnell das ging :D
