### ISSUE TITLE
v3.1.0-alpha.36 ACE-Editor-Problem

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1857]
![image](https://user-images.githubusercontent.com/84818934/188706727-041a245e-bb3e-4021-8be1-52b24b67c978.png)
Nach jedem Tastendruck (Löschen oder hinzufügen von einem Buchstaben), springt der Editor direkt an den Anfang?

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.37` passen

**Comment by mcuiobroker** [comment]
Passt. Danke.
