### ISSUE TITLE
v3.1.0-alpha.36 Notifications auf dem Handy zu breit

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1858]
![image](https://user-images.githubusercontent.com/84818934/188707131-15439a25-d619-413d-a37b-e1c316bb1cb1.png)

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.37` passen

**Comment by mcuiobroker** [comment]
Passt. Danke.
