### ISSUE TITLE
v3.1.0-alpha.37 und vorher? Uncaught Meldung

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1859]
Die Meldung kommt nur, wenn ich ca 15 Tabs angeklickt habe und dann auf den TAB History komme.
Nach F5 oder nach nur vorher 10 Tabs kommt keine Meldung?
Woran kann es liegen?
![image](https://user-images.githubusercontent.com/84818934/188752064-b079eaab-ec7b-4a16-ac03-cd22e980032b.png)

![image](https://user-images.githubusercontent.com/84818934/188751331-c714760d-82ee-4fce-bb75-1fe94e91fd68.png)

Vermute einen Zusammenhang mit dem MediaControl.
Denn solange der Alexa-Elemente nicht eingetragen hat und ich dann umschalte auf den anderen Tab, dann kommt Uncaught.

**Comment by Zefau** [comment]
Das müsste vom Chart oder HistoryGraph kommen. In MediaControl gibt es keine `unit`. Hast du den Fehler noch? Sollte inzwischen behoben sein.

**Comment by mcuiobroker** [comment]
Nein, kommt zurzeit nicht mehr.
