### ISSUE TITLE
v3.1.x > Empty region below top menu

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1863]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.1.0-alpha.39] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

![image](https://user-images.githubusercontent.com/79741077/189086543-ae0e7f7f-0c33-457e-aca7-4022f13c490d.png)

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

s.o.
____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
@Zefau: Ansonsten sieht v3.1.x gar nicht soo schlecht aus auf den ersten Blick. Würde nach BugFix dieses Fehlern mal den Umstieg wagen, oder gibt es noch kritische Fehler, welche ich nicht direkt sehen kann?

**Comment by mcuiobroker** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1823#issuecomment-1239925021
