### ISSUE TITLE
Widget Chart kann nur 4 Bargraphen darstellen

### ISSUE THREAD

**Issue by otze75** [Zefau/ioBroker.jarvis#1864]
Vielleicht mache ich auch etwas falsch, aber sobald ich den fünften Bargraphen anlege wird nichts mehr angezeigt!? Ich wollte für jeden Monat einen Bargraphen darstellen.

![image](https://user-images.githubusercontent.com/113213826/189447692-2a18cf1e-c493-48c8-b19d-0442fd3b1332.png)

Beste Grüße

**Comment by Zefau** [comment]
bei mir zeigt er 5 (und mehr) an. Wie sieht denn deine Konfiguration aus und welche Datenpunkt-Werte stehen hinter den Einträgen? Hast du Fehler im in der Browser-Konsole (via F12)?

**Comment by otze75** [comment]
Nun klappt es. Keine Ahnung. Ich kann mir nur vorstellen, dass es mit dem Update auf v3.0.13 zu tun hat. Das habe ich gerade vor kurzem installiert und danach hatte ich nicht nochmal versucht den Bargraph anzupassen. Vielleicht war etwas schief und durch das Update wurde es gerade gezogen, Browser-Cache oder ich bin einfach zu blöd :-) Sorry. Vielen Dank für Deine Bemühungen.

![image](https://user-images.githubusercontent.com/113213826/190079990-af0420bf-b4ca-4258-b4a3-711da090610b.png)

**Comment by otze75** [comment]
Ein kleines Thema wäre noch die Darstellung auf dem Smartphone. Android. Test mit Edge, Chrome und Samsung Browser. Leider ist die Legende über den Bargraphen. Gibt es dort noch eine Einstellmöglichkeit über CSS?

![tempFileForShare_20220914-085848 (002)](https://user-images.githubusercontent.com/113213826/190083798-d64a64c8-4b60-4fc7-9473-3dfcf8e7c8a6.jpg)

**Comment by Zefau** [comment]
Dem Widget `padding-bottom` hinzufügen vielleicht?
