### ISSUE TITLE
 v3.1.0-alpha.40 JSON-Editor Übernehmen nicht möglich

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#1865]
Der ÜBERNEHMEN Button kann nicht betätigt werden.

![grafik](https://user-images.githubusercontent.com/77939385/189489526-aad6d178-1539-41cd-a13d-ca795c06fd59.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.41`

**Comment by TZanke** [comment]
Klappt leider auch nicht in der `v3.1.0-alpha.41`

**Comment by Zefau** [comment]
@TZanke bei mir geht's. Kannst du mal einen Screenshot machen und den nicht-funktionierenden JSON Code hier reinkopieren, damit ich das mal probieren kann?

**Comment by hosabeni** [comment]
Bei mir Passt es mit der `v3.1.0-alpha.42`

Danke!

**Comment by Zefau** [comment]
@TZanke bei dir auch?

**Comment by hosabeni** [comment]
Ich muss mich leider korrigieren.
DerÜBERNEHMEN Button funktioniert aber die Änderungen werden nicht gespeichert.

**Comment by TZanke** [comment]
Wenn ich jetzt mit der `v3.1.0-alpha.42` auf den folgenden Button klicke freezed der gesamte Browsertab.
![image](https://user-images.githubusercontent.com/1613368/190355757-21e6d7c5-a344-475b-808b-c7f87baf0333.png)
Ich kann also den Dialog gar nicht testen.

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.43` behoben sein

**Comment by TZanke** [comment]
@Zefau Ich hab jetzt zwar schon die `v3.1.0-alpha.44`, er übernimmt den Code aus dem Dialog aber auch hier. Super, danke! 

_Der Dialog selbst hängt aber noch ne Ewigkeit bevor er überhaupt auf geht wie oben schon beschrieben._

**Comment by Zefau** [comment]
> Der Dialog selbst hängt aber noch ne Ewigkeit bevor er überhaupt auf geht wie oben schon beschrieben.

schau nochmal mit `v3.1.0-alpha.45`

**Comment by TZanke** [comment]
> > Der Dialog selbst hängt aber noch ne Ewigkeit bevor er überhaupt auf geht wie oben schon beschrieben.
> 
> schau nochmal mit `v3.1.0-alpha.45`

Die Meldungen in der Console sind weg, hängen tut es aber trotzdem noch (leider).

**Comment by hosabeni** [comment]
In dem Editor für den Expert Mode werden die Änderungen beim Speichern nicht übernommen.
`v3.1.0-alpha.45`


![Image](https://user-images.githubusercontent.com/77939385/190914886-718bc135-82fb-46d7-9dd9-faaae350b3cb.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.46`

**Comment by hosabeni** [comment]
Geht mit der Version.

Danke!
