### ISSUE TITLE
v3.1.0-alpha.40 und vorher: Null (0) Werte werden nicht angezeigt

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#1866]
0- Werte werden nicht angezeigt

Hier sollte eigentlich 0W stehen.

![grafik](https://user-images.githubusercontent.com/77939385/189496394-7557d1a8-c029-4723-82e1-8b61eaf0bd79.png)

![grafik](https://user-images.githubusercontent.com/77939385/189496398-ec09213c-f0fa-4694-8455-78042f0ff782.png)

![grafik](https://user-images.githubusercontent.com/77939385/189496401-60a43688-b1cd-4d21-bd8f-4cdee34348dd.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.41`

**Comment by Schimi1983** [comment]
ist immer noch so.... Bei der "offizielen" ist alles richtig und bei der aktuellen beta wird 0 nicht angezeigt:

![image](https://user-images.githubusercontent.com/4581474/189727191-764ed429-4c23-4920-8752-91c0fc969f6d.png)

**Comment by hosabeni** [comment]
Bei mir Passt es jetzt mit `v3.1.0-alpha.42`

**Comment by Schimi1983** [comment]
in der "v3.1.0-alpha.42" scheint die 0 wieder angezeigt zu werden... Zumindest bei mir
