### ISSUE TITLE
v3.1.0-alpha.41 nach Update : uncaught exception: _uuid is not a function

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#1867]
Fehler nach Update von 40 auf 41 

jarvis.0 | 2022-09-11 10:02:21.966 | debug | Refresh Adapter Instances and Script Statuses..
jarvis.0 | 2022-09-11 10:01:52.186 | debug | Push update of scripts..
jarvis.0 | 2022-09-11 10:01:51.967 | debug | Refresh Adapter Instances and Script Statuses..
jarvis.0 | 2022-09-11 10:01:22.357 | debug | Push update of instances..
jarvis.0 | 2022-09-11 10:01:21.997 | info | State value to set for "jarvis.0.settings.pageHomeReturn" has to be type "number" but received type "string"
jarvis.0 | 2022-09-11 10:01:21.970 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2022-09-11 10:01:21.953 | debug | Connection: Using options: {}
jarvis.0 | 2022-09-11 10:01:21.952 | debug | Connection: Using non-secure HTTP-Server
jarvis.0 | 2022-09-11 10:01:21.951 | debug | Connection: ioBroker host detected with MSNUC-IOB (IP: 192.168.0.13).
jarvis.0 | 2022-09-11 10:01:21.941 | debug | Web Configuration: {"port":"8082","auth":false,"secure":false,"bind":"0.0.0.0","cache":false,"socketio":"system.adapter.socketio.0","simpleapi":true,"defaultUser":"admin","ttl":"3600","certPublic":"Priv_Public","certPrivate":"Priv_Private","certChained":"priv_chained","addUserName":false,"forceWebSockets":false,"whiteListEnabled":false,"leEnabled":false,"leUpdate":true,"leCheckPort":80,"loginBackgroundColor":"","loginBackgroundImage":false,"lePort":"80","whiteListSettings":{"default":{"user":"admin","object":{"read":true,"list":true,"write":true,"delete":true},"state":{"read":true,"list":true,"write":true,"create":true,"delete":true},"file":{"read":true,"list":true,"write":true,"create":true,"delete":true}}},"basicAuth":true,"disableExtensions":false,"disableStates":false,"disableFilesObjects":false,"leStaging":false,"defaultRedirect":"","usePureWebSockets":true,"compatibilityV2":true,"staticAssetCacheMaxAge":60,"language":""}
jarvis.0 | 2022-09-11 10:01:21.924 | info | Found Backups for widgets.
jarvis.0 | 2022-09-11 10:01:21.905 | info | Found Backups for devices.
jarvis.0 | 2022-09-11 10:01:21.878 | info | Found Backups for styles.
jarvis.0 | 2022-09-11 10:01:21.877 | info | Found Backups for settings.
jarvis.0 | 2022-09-11 10:01:21.872 | info | Found Backups for layout.
jarvis.0 | 2022-09-11 10:01:21.819 | info | starting. Version 3.1.0-alpha.41 (non-npm: Zefau/ioBroker.jarvis) in /opt/iobroker/node_modules/iobroker.jarvis, node: v16.17.0, js-controller: 4.0.23
jarvis.0 | 2022-09-11 10:00:48.008 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082 (allowed due to all)
jarvis.0 | 2022-09-11 10:00:48.008 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082...
jarvis.0 | 2022-09-11 10:00:48.004 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082 (allowed due to all)
jarvis.0 | 2022-09-11 10:00:48.004 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082...
jarvis.0 | 2022-09-11 10:00:47.998 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
jarvis.0 | 2022-09-11 10:00:47.997 | info | terminating
jarvis.0 | 2022-09-11 10:00:47.996 | info | Adapter stopped und unloaded.
jarvis.0 | 2022-09-11 10:00:47.985 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082 (allowed due to all)
jarvis.0 | 2022-09-11 10:00:47.985 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082...
jarvis.0 | 2022-09-11 10:00:47.970 | error | _uuid is not a function
jarvis.0 | 2022-09-11 10:00:47.970 | error | TypeError: _uuid is not a function at Namespace.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/lib/server.js:1:12043) at Namespace.emit (node:events:513:28) at Namespace.emitReserved (/opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/typed-events.js:56:22) at /opt/iobroker/node_modules/iobroker.jarvis/node_modules/socket.io/dist/namespace.js:141:26 at processTicksAndRejections (node:internal/process/task_queues:78:11)
jarvis.0 | 2022-09-11 10:00:47.968 | error | uncaught exception: _uuid is not a function
jarvis.0 | 2022-09-11 10:00:47.936 | debug | Client connecting...
jarvis.0 | 2022-09-11 10:00:47.919 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082 (allowed due to all)
jarvis.0 | 2022-09-11 10:00:47.919 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082...
jarvis.0 | 2022-09-11 10:00:47.883 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082 (allowed due to all)
jarvis.0 | 2022-09-11 10:00:47.881 | debug | Connection: Origin detected with http://msnuc-iob.mecksauer.local:8082...
jarvis.0 | 2022-09-11 10:00:32.082 | debug | Refresh Adapter Instances and Script Statuses..
jarvis.0 | 2022-09-11 10:00:03.913 | debug | Push update of scripts..
jarvis.0 | 2022-09-11 10:00:02.082 | debug | Refresh Adapter Instances and Script Statuses..
jarvis.0 | 2022-09-11 09:59:32.364 | debug | Push update of instances..
jarvis.0 | 2022-09-11 09:59:32.135 | info | State value to set for "jarvis.0.settings.pageHomeReturn" has to be type "number" but received type "string"
jarvis.0 | 2022-09-11 09:59:32.104 | info | Found Backups for devices.
jarvis.0 | 2022-09-11 09:59:32.089 | info | Found Backups for widgets.
jarvis.0 | 2022-09-11 09:59:32.085 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2022-09-11 09:59:32.060 | debug | Connection: Using options: {}
jarvis.0 | 2022-09-11 09:59:32.059 | debug | Connection: Using non-secure HTTP-Server
jarvis.0 | 2022-09-11 09:59:32.057 | debug | Connection: ioBroker host detected with MSNUC-IOB (IP: 192.168.0.13).
jarvis.0 | 2022-09-11 09:59:32.046 | debug | Web Configuration: {"port":"8082","auth":false,"secure":false,"bind":"0.0.0.0","cache":false,"socketio":"system.adapter.socketio.0","simpleapi":true,"defaultUser":"admin","ttl":"3600","certPublic":"Priv_Public","certPrivate":"Priv_Private","certChained":"priv_chained","addUserName":false,"forceWebSockets":false,"whiteListEnabled":false,"leEnabled":false,"leUpdate":true,"leCheckPort":80,"loginBackgroundColor":"","loginBackgroundImage":false,"lePort":"80","whiteListSettings":{"default":{"user":"admin","object":{"read":true,"list":true,"write":true,"delete":true},"state":{"read":true,"list":true,"write":true,"create":true,"delete":true},"file":{"read":true,"list":true,"write":true,"create":true,"delete":true}}},"basicAuth":true,"disableExtensions":false,"disableStates":false,"disableFilesObjects":false,"leStaging":false,"defaultRedirect":"","usePureWebSockets":true,"compatibilityV2":true,"staticAssetCacheMaxAge":60,"language":""}
jarvis.0 | 2022-09-11 09:59:32.044 | info | Found Backups for settings.
jarvis.0 | 2022-09-11 09:59:32.043 | info | Found Backups for styles.
jarvis.0 | 2022-09-11 09:59:32.037 | info | Found Backups for layout.
jarvis.0 | 2022-09-11 09:59:31.966 | info | starting. Version 3.1.0-alpha.41 (non-npm: Zefau/ioBroker.jarvis) in /opt/iobroker/node_modules/iobroker.jarvis, node: v16.17.0, js-controller: 4.0.23

**Comment by MarkSau** [comment]
Als zusätzlichen Hinweis...Jarvis funktioniert nun nicht mehr.

**Comment by MarkSau** [comment]
@Zefau Hast du schon eine Idee oder sogar eine Lösung? Ohne Jarvis bin ich ziemlich aufgeschmissen.

**Comment by mcuiobroker** [comment]
Geh doch zurück auf die alpha.40.

**Comment by MarkSau** [comment]
@mcuiobroker hab ich jetzt auch gemacht. Danke..Dachte es hilft vielleicht, wenn ich noch auf 41 bleibe und evtl. mit daten behilflich sein kann.

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.42`

**Comment by MarkSau** [comment]
Kann ich bestätigen. funktioniert jetzt.danke
