### ISSUE TITLE
v3.1.0-alpha.40 Chart Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1869]
![image](https://user-images.githubusercontent.com/84818934/189557207-968ee007-09a0-4e51-ad13-a91ec840819c.png)
Blaues Band
![image](https://user-images.githubusercontent.com/84818934/189557235-bc3e28f2-9a17-4697-a913-4e0128fced11.png)

**Comment by Zefau** [comment]
behoben mit `v3.1.0-alpha.42`

**Comment by mcuiobroker** [comment]
`v3.1.0-alpha.45`
![image](https://user-images.githubusercontent.com/84818934/190878524-3d0655e6-6209-415a-b45d-d95bdf20b737.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.46`

**Comment by mcuiobroker** [comment]
Taucht nicht mehr auf. Danke.
