### ISSUE TITLE
Chart widget uses unit of first state of device in tooltip

### ISSUE THREAD

**Issue by ottk3** [Zefau/ioBroker.jarvis#187]
It seems that the chart widget uses the first states unit of the device for the tooltip instead the refering unit for that state. 
In my case the device has a **humidity sensor** using the "%" as a unit and a **temperature sensor** using "°C" as a unit.

When I create a chart for the temperature it will show me the "%" as the unit in the hover tooltip

**device:**

	{
	  "b3523f77-8056-47cd-a3e7-511c08b4d78d":{
		"id":"b3523f77-8056-47cd-a3e7-511c08b4d78d",
		"states":{
		  "luftdaten.0.humidity":{
			"state":{
			  "node":"luftdaten.0.192_168_1_20.humidity"
			},
			"label":"Luftfeuchtigkeit",
			"unit":"%"
		  },
		  "luftdaten.0.temperature":{
			"state":{
			  "node":"luftdaten.0.192_168_1_20.temperature"
			},
			"label":"Temperatur",
			"unit":"°C"
		  }
		},
		"options":{
		  "hiddenStates":[
			
		  ]
		},
		"attributes":{
		  "_created":1602531777945,
		  "_updated":1602531856906
		},
		"name":"Wetterstation",
		"function":"other"
	  }
	}

**chart:**

	[
	  {
		"title":"",
		"tabs":[
		  {
			"title":"Tab hinzufügen",
			"icon":"home",
			"columns":[
			  [
				{
				  "moduleConfig":{
					"chartFilterTimeRangeUnit":"hours",
					"chartConfigyLeftAxisUnitBefore":"",
					"chartConfigyLeftAxisUnitAfter":""
				  },
				  "module":"Chart",
				  "title":"Temperaturverlauf",
				  "devices":[
					{
					  "type":"device",
					  "deviceId":"b3523f77-8056-47cd-a3e7-511c08b4d78d",
					  "primaryStateKey":"luftdaten.0.temperature"
					}
				  ],
				  "index":0
				}
			  ]
			]
		  }
		]
	  }
	]

If I change the order of the states inside the device the hover tooltip shows the other unit instead.

Br,
Sven

**Comment by Zefau** [comment]
Thanks for that. Sounds easy to fix and I will do so with the next beta.

**Comment by cryptedx** [comment]
I can confirm this behaviour.

**Comment by Zefau** [comment]
@ottk3 @cryptedx should be fixed with `1.1.0-beta.46`. Can you confirm?

**Comment by ottk3** [comment]
@Zefau can confirm, fixed the isssue for me. Thanks!

**Comment by cryptedx** [comment]
Thanks!
