### ISSUE TITLE
V3: Widget Adapter wird nicht mehr korrekt angezeigt!

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#1870]
Seit dem letzten Update wird das Widgit nicht mehr richtig angezeigt. Problem bei Safari, Chrome und Edge.

![image](https://user-images.githubusercontent.com/104907692/189619181-4104cc1f-c4dd-47ee-8bb7-c73e36f05875.png)

P.S. Ich hab den Admin Adapter leider wieder zurücknehmen müssen, weil ich große Probleme mit den Datenpunkten und der Struktur hatte!

**Comment by Zefau** [comment]
Auf welches Update beziehst du dich und welche jarvis Version ist im Einsatz?

**Comment by bambi-arch** [comment]
v3.0.13

**Comment by Zefau** [comment]
@bambi-arch das sollte mit v3.1 behoben sein, kannst du das bestätigen?
