### ISSUE TITLE
V3: Wetterwidget auf englisch bei Chrome

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#1871]
Hallo! Seit dem letzten Update ist in Chrome einiges in englisch, was zuvor auf deutsch war. In Edeg, Safari ist alles in deutsch. In den Jarvis Einstellungen wird im Auswahlfeld "blank" angezeigt. Wenn ich etwas auswähle wird "de" reingeschrieben, jedoch nach dem Speichern ist wieder "en" drin?!

![image](https://user-images.githubusercontent.com/104907692/189620851-c2efda62-e8b0-470d-bd96-1e980ce68d8a.png)

![image](https://user-images.githubusercontent.com/104907692/189621032-f10cd52d-7c73-4059-a690-50c42eb01325.png)

**Comment by Zefau** [comment]
Welche jarvis Version?

**Comment by bambi-arch** [comment]
v3.0.13

**Comment by Zefau** [comment]
@bambi-arch besteht das Problem noch mit v3.1?
