### ISSUE TITLE
MapMarker not in foreground + text always wrong

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1879]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.1.0-alpha.44] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

When I hover over an element (e.g. my own picture) it and I'm at home which means both picture are at the same location it does not bring me to the front + the text is always "Position (Map)"

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![image](https://user-images.githubusercontent.com/79741077/190854724-955c9bcb-8f16-4598-a264-b67ac861719c.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
Hab gerade gesehen, das es auch schon mit ```v3.1.0-alpha.40``` so ist

**Comment by Zefau** [comment]
Kannst du mal die Geräte Konfiguration zeigen? Wo kommt das seltsame Label her? Oder ist das Absicht?

**Comment by RkcCorian** [comment]
Ahhh... hast Du in den 3.1.x Versionen die Quelle für das Label geändert? Links unten für die Navigation nimmst Du nicht das Label des Gerätes, sondern von der Widget-Konfig. Das führte bei mir zu der Inkonsistenz im Namen > Ggf. nochmal anschauen
Darüber hinaus bleibt das Problem, dass beim markieren / hovern zwar der Text des Objektes auf der Karte "nach vorne" kommt, aber nicht das Bild / Icon.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.45`

**Comment by RkcCorian** [comment]
Passt
