### ISSUE TITLE
iFrame Interaktion verhindern

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1880]
> Hallo! Ich hab den Regenradar als Iframe eingefügt. Gibt es eine Möglichkeit zu verhindern, dass der User durch Klick auf diese Internetseite gelangt. Vielleicht über die Sandbox?

> Danke im Voraus

_Originally posted by @bambi-arch in https://github.com/Zefau/ioBroker.jarvis/discussions/1875_

**Comment by mcuiobroker** [comment]
Bitte als Option setzen, damit man bei einigen die Möglichkeit hat die Interaktion zu nutzen.

**Comment by Zefau** [comment]
Ist eine Option

**Comment by Zefau** [comment]
implementiert mit `v3.1.0-alpha.45`
