### ISSUE TITLE
v3.1.0-alpha.45 Fehler beim Anlegen vom Widget im Layout

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1881]
![image](https://user-images.githubusercontent.com/84818934/190881051-e7b268df-735f-4368-8915-9fd7c3f57e94.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.46`

**Comment by mcuiobroker** [comment]
Passt. Danke.
