### ISSUE TITLE
v3.1.0-alpha.45 und vorher: iobroker Log *.png Not exists

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#1882]
Beim Öffnen von Jarvis auf kommen gelegentlich folgende Meldungen im iobroker Log:

![grafik](https://user-images.githubusercontent.com/77939385/190915231-63b4cbb5-4027-429e-b946-1df49753d202.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.46`

**Comment by hosabeni** [comment]
Die Warnung kommt leider immer noch.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.47`

**Comment by hosabeni** [comment]
Der Adapter geht bei der Version `v3.1.0-alpha.47` in Fehler:

![grafik](https://user-images.githubusercontent.com/77939385/191829821-f937100f-e30e-4e35-80e9-057341239adc.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.48`

**Comment by hosabeni** [comment]
Die Meldung kommt nicht mehr.
Danke!
