### ISSUE TITLE
Update 3.0.10 auf 3.0.13 Jarvis startet nicht mehr!

### ISSUE THREAD

**Issue by Klaus28051967** [Zefau/ioBroker.jarvis#1883]
Hi , nach dem Update kommt folgende Fehlermeldung:

Error: Installation inconsistent
Connecting to http://192.168.178.171:8400 (#1)...
19.09.2022, 07:30:38 | INFO | CONNECTION
Connected to http://192.168.178.171:8400.
19.09.2022, 07:30:38 | INFO | SOCKET
Received an Update for Settings.
19.09.2022, 07:30:38 | DEBUG |
Using ec499e3e-fab6-98f9-b220-fa97519d57d5, [object Object]
19.09.2022, 07:30:38 | DEBUG | PRO
Valid Pro User: Klaus Baumann
19.09.2022, 07:30:38 | INFO | PRO
Received an Update for Devices.
19.09.2022, 07:30:38 | DEBUG |
Received an Update for Layout.
19.09.2022, 07:30:38 | DEBUG |
Received an Update for Styles.
19.09.2022, 07:30:38 | DEBUG |
Device not found:, b88214d4-09a7-4ae6-abd3-c5e0149320ae, Telefon In Json, [object Object]
19.09.2022, 07:30:39 | WARN | DEVICES-E52EB4C9
Device not found:, b88214d4-09a7-4ae6-abd3-c5e0149320ae, Telefon Missed, [object Object]
19.09.2022, 07:30:39 | WARN | DEVICES-E52EB4C9
Device not found:, b88214d4-09a7-4ae6-abd3-c5e0149320ae, Telefon In, [object Object]
19.09.2022, 07:30:39 | WARN | DEVICES-E52EB4C9
Device not found:, b88214d4-09a7-4ae6-abd3-c5e0149320ae, Telefon Out, [object Object]
19.09.2022, 07:30:39 | WARN | DEVICES-E52EB4C9

das wars dann auch ... 

Bitte um Lösungsvorschläge bzw. Hilfe!

viele liebe Grüße Klaus

**Comment by Zefau** [comment]
Adapter neu uploaden und Web Adapter neu starten

**Comment by Klaus28051967** [comment]
Hi Zefau , danke für die Schnelle Antwor, aber es hat nichts gebracht:

Habe habe Adapter neu geuploadet ohne Fehler:
$ iobroker upload jarvis --debug

upload [15] jarvis.admin C:/iobroker/node_modules/iobroker.jarvis/admin/admin.css admin.css text/css

upload [12] jarvis.admin C:/iobroker/node_modules/iobroker.jarvis/admin/i18n/en/translations.json i18n/en/translations.json application/json

upload [10] jarvis.admin C:/iobroker/node_modules/iobroker.jarvis/admin/i18n/fr/translations.json i18n/fr/translations.json application/json

upload [6] jarvis.admin C:/iobroker/node_modules/iobroker.jarvis/admin/i18n/pt/translations.json i18n/pt/translations.json application/json

upload [3] jarvis.admin C:/iobroker/node_modules/iobroker.jarvis/admin/index_m.html index_m.html text/html

upload [0] jarvis.admin C:/iobroker/node_modules/iobroker.jarvis/admin/zefau.jpg zefau.jpg image/jpeg

upload [153] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/apple-touch-icon-120x120.png apple-touch-icon-120x120.png image/png

upload [18] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/img/weather_set5_7.439d10db.png img/weather_set5_7.439d10db.png image/png

upload [16] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/img/weather_set5_9.9dc0f52e.png img/weather_set5_9.9dc0f52e.png image/png

upload [12] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/js/11.4bcf266d.js js/11.4bcf266d.js application/javascript

upload [10] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/js/4.63d34ec3.js js/4.63d34ec3.js application/javascript

upload [8] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/js/6.5bf0a8f5.js js/6.5bf0a8f5.js application/javascript

upload [7] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/js/7.069a7405.js js/7.069a7405.js application/javascript

upload [5] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/js/9.7b7467e4.js js/9.7b7467e4.js application/javascript

upload [4] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/js/app.f0023f28.js js/app.f0023f28.js application/javascript

upload [3] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/js/app.hash.json js/app.hash.json application/json

upload [1] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/js/vendor.2f36216f.js js/vendor.2f36216f.js application/javascript

upload [0] jarvis C:/iobroker/node_modules/iobroker.jarvis/www/socket.io-2.3.1.slim.js socket.io-2.3.1.slim.js application/javascript

Process exited with code 0

aber das gleiche Resultat mit genau den gleichen Meldungen wie OBEN!

und nun?

Gruß Klaus

**Comment by Klaus28051967** [comment]
Hi Zefau, nach Neustart von ioBroker läuft Jarvis wieder!

vielen Dank 

Problem erledigt!

**Comment by Yroge** [comment]
Hi
