### ISSUE TITLE
v3.1.0-alpha.46 und vorher: Quellübergreifende (Cross-Origin) Anfrage blockiert

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#1884]
Bei jedem wechseln eines Tabs und bei einem Reload kommt die Fehlermeldung in der Konsole. Bei wechseln des Tab kommt die eine Meldung sofort und eine zweite nach 1 bis 2 Sekunden.

![grafik](https://user-images.githubusercontent.com/77939385/191338947-bb37f961-7064-41d7-b3cf-7240f4d66205.png)

**Comment by Zefau** [comment]
Bei dir tritt eine Fehler auf, der zu Sentry geschickt wird, was aber nicht klappt, da blockiert. Sentry kannst du in den ioBroker.jarvis Adapter-Einstellungen deaktivieren, dann sollte die Meldung verschwinden.
