### ISSUE TITLE
Update von Jarvis Alpha xx verursacht möglicherweise Löschung in Javascript node_module Verzeichnis

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#1889]
In dem Moment, als der Update gestartet wurde, sind die Folder in /opt/iobroker/node_modules/iobroker.javascript/node_modules verschwunden. Nur ein Neustart der javascript instanz bringt die Dateien wieder zurück.

Ich habe schon bei javascript ein issue eröffnet.
Siehe https://github.com/ioBroker/ioBroker.javascript/issues/1146

Möglicherweise hat es auch hiermit zu tun:
https://github.com/ioBroker/ioBroker.js-controller/issues/2006

**Comment by Zefau** [comment]
Das sind die Tiefen von ioBroker. Da habe ich aus Adapter-Sicht keinen Einfluss drauf.
