### ISSUE TITLE
Jarvis über port 8400 extrem langsam

### ISSUE THREAD

**Issue by softwarecrash** [Zefau/ioBroker.jarvis#1890]
hallo,
seit der der v3.0.12 geht es ja das man jarvis über den socket port selbst aufruft, also eine super möglichkeit es hinter einem reverse proxy zu verstecken, in meinem fall authelia mit traefik.
allerdings ist die webseite unglaublich langsam, ladedauer insgessamt über 1minute, 
bei jedem neu laden der seite holt es auch die vendor und app js files, kein caching möglich?
aus dem eigenen netzwerk heraus (ohne ddns von ausen) ist es nur unmerklich schneller, deutlich schneller ist es über port 8082, allerdings funktioniert dann reverse proxy nicht mehr wegen corss origin und ssl error nicht mehr.
gibt es irgendeine möglichkeit das ein wenig zu beschleunigen?
achja, die images werden großteils auch nicht mit geladen.
aktuell im einsatz 3.0.13

![image](https://user-images.githubusercontent.com/44615614/191489775-2678f68d-e394-481b-8f98-89187749390f.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.47`

**Comment by softwarecrash** [comment]
danke für die schnelle antwort, eben auf alpha 47 aktualisiert, jarvis startet ohne murren, aber sobald ich ihn über port 8400 aufrufe stürzt der adapter ab und ich bekomm auf der anderen seite des proxy nur ein bad gateway

![image](https://user-images.githubusercontent.com/44615614/191685166-f7a4ac58-daa6-43c1-ae4a-162aa60bd645.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.48`. irgendeine Besserung?

**Comment by softwarecrash** [comment]
Das sieht auf jeden fall viel besser aus, nach einem initialen laden ist der refresh deutlich schneller, zumindest in chrome
![grafik](https://user-images.githubusercontent.com/44615614/192227472-4debb157-86d5-46b6-897f-44ec524431e1.png)

in firefox ist es schneller geworden, aber haut einem ne menge warnungen und ein zwei fehler um die ohren und probiert scheinbar bei einem reload trotzdem alles neu zu laden.
`downloadable font: rejected by sanitizer (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:0) source: https://xxxxx/jarvis/woff2/materialdesignicons-webfont-633d596f.woff2 `

`10:16:17:510 | WARN | SOCKET | d.get is not a function TypeError: d.get is not a function`

achso, eine kleinigkeit noch, das icon "balance" wird nicht geladen / angezeigt obwohl es teil des google material sets ist, oder hab ich da einfach einen fehler?

**Comment by Zefau** [comment]
`balance` finde ich nicht, siehe https://pictogrammers.github.io/@mdi/font/6.9.96/

In welcher Material Design Version schaust du?

**Comment by softwarecrash** [comment]
eigentlich da wo einen das kleine i hinbringt (hinter dem platz für den icon namen) dort dan google material design ausgewählt
ggf den link austauschen oder mehr infos dahin? den link zu pictogrammers kenne ich garnicht.
rein aus faulheit habe ich immer wenn ich neue icons gesucht habe auf das i geklickt, hat fast immer funktioniert

**Comment by Zefau** [comment]
Das `i` bringt dich zu https://icon-sets.iconify.design/, aber dort finde ich kein Icon mit dem Namen `balance`.

**Comment by softwarecrash** [comment]
Merk schon, irgendwas habe ich da nicht mit kopiert, aber auch die anderen gingen nicht die da gelistet sind. Mit denen aus deinem jetzigen Link funktioniert es auf Anhieb.
Gibt es da Nachteile wenn ich die Namen von der anderen Seite nehme statt den mdi-

**Comment by Zefau** [comment]
@softwarecrash bist du Pro user? Material Design Icons funktionieren immer. Die Iconify nur, wenn du Pro bist.

**Comment by softwarecrash** [comment]
Nein nur normaler User,
Bin davon ausgegangen das wenn ich nach Google Material filetere die richtigen erwische.
Dann notiere ich mir Mal den anderen Link.
Hast du auf die schnelle einen Tipp ob oder wie man da noch einen rtmp Stream reinbekommt?

**Comment by Zefau** [comment]
ggf. via StateHTML und https://www.w3schools.com/html/html5_video.asp ?

**Comment by softwarecrash** [comment]
Ah, vielen dank für den Tipp, da muss ich mich Mal einlesen.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.49` bzgl. `d.get`.

Die Warnungen zu den Fonts kann ich nicht verhindern.

**Comment by softwarecrash** [comment]
das schaut sehr gut aus, bis auf den font und die preload warnungen ist alles andere weg.
gibt es zu dem stateHTML irgendwo eine anleitung? ich kann das widget anlegen, dort muss ich ein gerät angeben, und innerhalb des gerätes den html code oder wie strukturiert sich das?

**Comment by mcuiobroker** [comment]
Beispiel
https://mcuiobroker.gitbook.io/jarvis-infos/tipps/adapter-spezifisch/fahrplan

**Comment by softwarecrash** [comment]
> Beispiel https://mcuiobroker.gitbook.io/jarvis-infos/tipps/adapter-spezifisch/fahrplan
> 
> Oder https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/module/statehtml

super, danke. da werd ich mich durchwühlen.

was mir gerade aufgefallen ist, vermutlich seit dem update auf die letzte alpha, zeigt es in der ersten seite bei einem statelist die werte nicht mehr an, bei allen anderen drumrum schon. wüsste nicht das ich da was verändert hab. wenn man drauf klickt sieht man die werte. wurde da irgendwas geändert oder hab ichs mal wieder selber unwissentlich verpfuscht

**Comment by mcuiobroker** [comment]
Bitte ein Bild dazu und evtl als Bug anlegen. Danke.

**Comment by softwarecrash** [comment]
> Bitte ein Bild dazu und evtl als Bug anlegen. Danke.

![grafik](https://user-images.githubusercontent.com/44615614/192746006-e3341ce3-07fb-4599-820f-1863fec50e14.png)
hier fehlen die werte
wenn man darauf klickt sieht man sich jedoch
![grafik](https://user-images.githubusercontent.com/44615614/192746102-7eafe630-e1b1-4ee2-b598-54ba9a98c92f.png)

in einem anderen tab geht es allerdings problemlos
![grafik](https://user-images.githubusercontent.com/44615614/192746188-8e76269c-ac5c-4c70-ba67-01f9ea9ef2a3.png)


hier die config von dem nicht funktionierenden
![grafik](https://user-images.githubusercontent.com/44615614/192746335-26003f98-1d59-4600-9cb1-238ec2edba90.png)
![grafik](https://user-images.githubusercontent.com/44615614/192746546-4833abd1-9a3a-4216-a495-374b499a5136.png)

sind eigentlich identisch mit dem funktionmierenden, klar bis auf die daten.
würde ungern ein bug anlegen, kann es nicht ganz nachvollziehen ob es jetzt am update liegt oder an mir oder config.
finde auch gerade ehrlich gesagt keine möglichkeit auf alpha 47 zurück zu gehen, nehme sonst den direkten link von github

**Comment by Zefau** [comment]
Kann das Issue hier zu? :-)

**Comment by softwarecrash** [comment]
Natürlich, erledigt :)

**Comment by softwarecrash** [comment]
> Beispiel https://mcuiobroker.gitbook.io/jarvis-infos/tipps/adapter-spezifisch/fahrplan
> 
> Oder https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/module/statehtml

leider ist es wohl nicht möglich ohne flash player ein rtmp stream einzubinden. mir ist auch nicht ganz klar warum frigate das nutzt und nicht hls oder dergleichen. da muss ich mir irgendwas anderes einfallen lassen

**Comment by softwarecrash** [comment]
ich muss glaub nochmal aufmachen, mit dem alpha 50 update ging es anfangs (vermutlich cache) aber jetzt tritt das Phänomen auf das es in chrome relativ schnell und fehlerfrei läd, in firefox aber mit verbindungsfehlern abbricht.
in chrome ist nur auffällig das eine websocket Verbindung als austehend markiert ist.
habe es auch nochmal in firefox protable getestet um auszuschließen das meine installierte version eine macke hat.

am reverse proxy (traefik) liegt es denke ich mal nicht, da iobroker selbst auch hinter selbigen versteckt ist, und die routen einstellungen identisch sind bis auf den port.

firefox:
![Screenshot 2022-09-29 192737](https://user-images.githubusercontent.com/44615614/193102016-926336ff-d3fe-499b-8792-1086b2be8faa.png)

chrome:
![grafik](https://user-images.githubusercontent.com/44615614/193101999-5bac81ca-64d4-4ec8-b13b-f016e98de260.png)

**Comment by Zefau** [comment]
Läuft es über `https` und hast du im Firefox das selbst-signierte Zertifikat auf Port 8400 angenommen? Die Socket-Anfrage über Port 8400 wird laut Screenshot abgelehnt.

**Comment by softwarecrash** [comment]
das wäre auf port 8400 garnicht möglich da er nicht nach außen geroutet ist, lediglich 443 und 80 sind offen, jarvis auf 8400 wird intern von traefik auf eine subdomain 80/443 geroutet.
ich hab keine idee woher er die daten hat dafür.
alle anfragen auf http werden zu https geroutet, das zertifikat wird akzeptiert (nicht selbst signiert)
aktuell rennt es wieder völlig problemlos.
wenn es probleme macht wird der erste teil geladen (das wo connecting, show log) steht, und dann bekommt er keine weitere verbindung auf dem port wo er den ersten teil geladen hatte.
das ganze hängt hinter einem lte router, ab und zu erwischt der eine zelle die voll ist, dann ist das netz nicht sonderlich schnell, wenn das so ist ist auch die iobroker seite anstrengend träge, aber wird geladen man braucht nur ein klein wenig mehr geduld. 
was mich eben stutzig macht das es in chrome und edge dann zwar merklich langsamer läd, aber doch aufbaut und in firefox abbricht.

**Comment by Zefau** [comment]
@softwarecrash was kann ich hier noch machen? bin mir unschlüssig, was ich hier in jarvis ändern kann

**Comment by softwarecrash** [comment]
@Zefau eingrenzen konnte ich es nicht weiter, allerdings habe ich letztens den iobroker neu aufgesetzt un die backups reingeholt, seitdem ist das problem eig nicht mehr aufgetreten.
