### ISSUE TITLE
v3.1.0-alpha.47 Fehler beim Kopieren vom Widget

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1895]
Die Kopie wird über das Original gelegt, ohne Angaben von Höhe und Breite.
![jarvisv310-alpha47 Kopie Widget Fehler](https://user-images.githubusercontent.com/84818934/191722279-47a171c5-667c-49e9-bfd7-ac7183503543.gif)
Passiert auch beim Duplizieren.

Widget verschieben auf einen anderen TAB? Feature Request?

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.48`; verschieben ist nun auch möglich

**Comment by mcuiobroker** [comment]
Es wird jetzt an die richtige Stelle kopiert. Es fehlt aber die Info über die Größe.
![image](https://user-images.githubusercontent.com/84818934/192166784-798af88b-876e-48dc-bf1c-4cb7f3959d81.png)

**Comment by mcuiobroker** [comment]
Hat man ein Widget kopiert und löscht dieses wieder wird es nicht aus der Widget Übersicht gelöscht. So kann es durch verklickern schnell apssieren, dass man zig Kopien von einem Widget hat?
![image](https://user-images.githubusercontent.com/84818934/192166858-d4cc270c-99b8-4670-b9cd-4e9c33a9d081.png)
Vielleicht sollte man da beim Löschen vom Widget im Layout nachfragen soll das Widget (copy) auch gelöscht werden ?

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`:
- wenn das Widget nur 1x verwendet wird (also in nur einer Box) kommt eine Abfrage, ob das Widget mitgelöscht werden soll (Dropdown mit zwei Optionen)
- wenn das Widget mehrfach verwendet wird, wird nach wie vor nur die Box gelöscht und das Widget erhalten (wird ja noch anderswo verwendet)

**Comment by mcuiobroker** [comment]
Es wird beim Löschen von der Widget-Copy nicht gefragt, ob auch das Widget (copy) gelöscht werden soll.
![image](https://user-images.githubusercontent.com/84818934/195084956-bf8b383a-32a4-4e1a-801e-e533514372c7.png)

**Comment by mcuiobroker** [comment]
![jarvis-v310-beta21-Fehler Widgets löschen](https://user-images.githubusercontent.com/84818934/202032677-3b7ed235-3b70-4caa-a6dd-6537ecffb03a.gif)


Weitere Punkte:

- [ ] Box ohne Widgetzuordnung nur "Box löschen", die andere Option überflüssig? 
![image](https://user-images.githubusercontent.com/84818934/202030928-65d63e2f-f726-427f-a5fd-a0e82886c6b9.png)

- [ ] Widgets in unterschiedlichen Layouts (Desktop/SmartPhone) werden doppelt in der Widgetzuordnung (Widgets) angezeigt, auch obwohl das Smarthone nicht aktiviert war.
![image](https://user-images.githubusercontent.com/84818934/202031343-2af5e157-dcc9-456a-a480-ff7875682158.png)

![image](https://user-images.githubusercontent.com/84818934/202031674-7a625970-204b-41bb-9f8e-f4453b0490f1.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.29`

**Comment by mcuiobroker** [comment]
Da du es schon so schön mit der anderen Farbe gelöst hast, wäre es dann nicht auch sinnvoll direkt beim Smartphone auch die Farbe als Hintergrundfarbe für die Widgets zu nutze? Man weiß dann sofort in welchem Bereich man arbeitet.

**Comment by Zefau** [comment]
`v3.1.0-beta.32`

**Comment by mcuiobroker** [comment]
Farbe passt.
Aber das SmartPhone-Layout schließt nicht, wenn man wieder Desktop auswählt?
![jarvis-v310-beta32-Layout schliesst nicht](https://user-images.githubusercontent.com/84818934/203171728-65a38d6f-06e4-4c92-9a8a-e9b2b050bccf.gif)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.33`
