### ISSUE TITLE
v3.1.0-alpha.47 Fehler beim Kopieren der widgetID

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1896]
Fehler tritt auf, wenn man in der WidgetListe versucht die WidgetID zu kopieren, durch Klick auf den Kopier-Button.
![image](https://user-images.githubusercontent.com/84818934/191732629-100d16fa-a3a4-4a6c-807e-d2718abf705b.png)

![image](https://user-images.githubusercontent.com/84818934/191732357-d28858de-7189-4c92-815c-0a90a840fe23.png)
Ist aber definiert:
![image](https://user-images.githubusercontent.com/84818934/191732788-ee1d9d8a-df6a-4dcd-a5fe-02d181c00df7.png)

**Comment by mcuiobroker** [comment]
Um eine Alternative zu haben, sollte man im Widget selbst auch die WidgetDI anzeigen:
![image](https://user-images.githubusercontent.com/84818934/191741801-65d23b1e-4a7c-4185-8388-c3bbd057892b.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.48`

**Comment by mcuiobroker** [comment]
Passt, trotzdem würde ich mir eine Anzeige der WidgetID im Widget selbst wünschen.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.49`
