### ISSUE TITLE
v3.1.0-alpha.47 Keine Widget-Selektion über die widgetID?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1897]
Man kann das Widget nicht über die WidgtID auswählen?
![image](https://user-images.githubusercontent.com/84818934/191743590-df418fc3-e0c3-4fb6-ba9d-f6d42fe446da.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.48`

**Comment by mcuiobroker** [comment]
Passt. Danke.
