### ISSUE TITLE
Swipe to switch between tabs

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#19]
On my smartphone I created a link on my homescreen to open and use jarvis like a native app. This works really well. To improve this "native app" feeling, it would be great to be able swipe between tabs.

**Comment by Zefau** [comment]
Should be added with `v0.1.2`. Could you please test and verify? Thanks

**Comment by braindead1** [comment]
On my smartphone, swiping to the left (open right tab) does not work as expected. With the first swipe, the screen turns grey. After swiping two to three more times the tab changes. Swiping right (open left tab) works as expected.

On my laptop swiping starts working when the window is small. As long as the cursor does not leave the window, it works as expected. If the cursor leaves the window while swiping, the tab is not changed.

![2](https://user-images.githubusercontent.com/2136249/77860494-00ff5c80-7210-11ea-9fd9-bb1185e530b2.png)

**Comment by braindead1** [comment]
Is it possible to revert the change until the foreign issue has been solved? I don't know if it related o the change and this issue, but on my smartphone pop-ups for states are to large in terms of width.

**Comment by Zefau** [comment]
I can revert it for now. Am I right that this issue only occurs on the first tab? Same issue as the swiping?

**Comment by Zefau** [comment]
Has been reverted with v0.1.4.

**Comment by braindead1** [comment]
No, the issue regarding swiping to the left (open right tab) occured on all tabs. The same is with the pop-ups for states that are to large.

I installed v0.1.4 and now the width of the pop-ups are fine againg.

**Comment by Zefau** [comment]
https://github.com/Swiggy/swipeable-tabs/issues/3

**Comment by Zefau** [comment]
should now be working with v3

**Comment by mcuiobroker** [comment]
Das swipen funktioniert. Nur wird der ausgewählte TAB nicht angezeigt im collapseTab: true Modus. Da die meisten dann auf dem Handy im "more" drin. Die TABs müssten sich auch im collapseTABs-Modus it nach links bzw rechts bewegen?

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.75` ist der ausgewählte Tab nun in der primären Farbe hervorgehoben (auch im Dropdown). Den ausgewählten Tab nach links / rechts bewegen ist mir an dieser Stelle zu aufwendig zu implementieren.

**Comment by mcuiobroker** [comment]
Funktioniert.

**Comment by Freemanzero** [comment]
kann mir jemand hefen. Ich suche die EInstellung wo ich einschalten kann, dass ich in der mobilen Version zwisc hen den Tabs swipen kann. Ich finde es nichtr mehr.

Vielen Dank für eure Hife

**Comment by Wacho1** [comment]
> Ich suche die EInstellung wo ich einschalten kann, dass ich in der mobilen Version zwisc hen den Tabs swipen kann. Ich finde es nichtr mehr.

Ich hänge gerade auch an dieser Stelle. 

Ich verwende das Map Modul, kann die Karte aber nicht nach links oder rechts verschieben (auf Smartphone), da dann immer das nächste Tab angezeigt wird. Daher würde ich die Funktion gerne abschalten.

**Comment by Wacho1** [comment]
Ok, ich habe die 3.0.11 noch am Start, dort fehlt der Eintrag

![image](https://user-images.githubusercontent.com/74119244/190252279-5cbfc071-3500-435f-bfa9-3381ca7d716d.png)

Ein Update auf 3.0.13 brachte mir einen "red screen", daher bin ich wieder zurück. 
Ist aber kein Problem mehr, die Karte des Map Modules lässt sich mit zwei Finger gleichzeitig verschieben...
