### ISSUE TITLE
DevicesPage: Group devices by functions and allow collapsing groups

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#190]
@Stephan-Schleich sagte in [jarvis \- just another remarkable vis](/post/502739):
> Ich würd hald unter Geräte gerne pro Anwendung eine Gruppe definieren wollen (Übersichtshalber) z.B. eine Gruppe für Tankerkönig, eine Gruppe für Klimaanlage, eine Gruppe für Fußball etc. und diese Guppengeräte will ich nur sehen wenn ich diese Gruppe aufklappe um nicht hunderte Geräte durchzuscrollen

**Comment by duczz** [comment]
Please add the collapsing feature on Device > States too

**Comment by Zefau** [comment]
This has been added with `v1.1.0-beta.130`. @duczz Could you have a look?

**Comment by cryptedx** [comment]
Indeed it looks nice. I love this feature!

![image](https://user-images.githubusercontent.com/20707078/99932925-d5f6e980-2d59-11eb-9ae9-5519a6b51198.png)

What would you say to stick this

![image](https://user-images.githubusercontent.com/20707078/99932966-f030c780-2d59-11eb-8a32-980a3ad8fbe2.png)

at the top so if we scroll it stays still visible?

![image](https://user-images.githubusercontent.com/20707078/99933025-16566780-2d5a-11eb-9cb5-e64f6df9e49f.png)

When adding devices I often had so scroll to the top. It was a bit annoying.

**Comment by duczz** [comment]
Sehr geil, danke Zefau - schaut gut aus.
Mir wäre auch noch eine Sache aufgefallen und zwar werden die Namen manuell definierter Gewerbe nicht angezeigt, sprich bleibt dann leer.

![image](https://user-images.githubusercontent.com/25475385/99935812-dc895f00-2d61-11eb-8471-80e4d556feea.png)

Des Weiteren sollte ein hinzugefügter state nicht gleich minimiert sein, sondern entfaltet.

**Comment by cryptedx** [comment]
When I add a new device it will not appear immediately. I switched to Group by Manufacturer and back. Then it appeared.

**Comment by Zefau** [comment]
resolved with `v1.1.0-beta.131`:

- [x] *When I add a new device it will not appear immediately. I switched to Group by Manufacturer and back. Then it appeared.*
- [x] *What would you say to stick this*
- [x] last selecting grouping will be remembered

Noch offen:
- [ ] *Des Weiteren sollte ein hinzugefügter state nicht gleich minimiert sein, sondern entfaltet.*

**Comment by Zefau** [comment]
completed with `v1.1.0-beta.132`.

**Comment by duczz** [comment]
Funktioniert, Top.

**Comment by duczz** [comment]
Funktioniert bei mir bis dato einwandfrei, bitte noch nach Namen sortieren, bei mir sind die gruppen nach Anlagezeitpunkt sortiert.

**Comment by Zefau** [comment]
Sollte mit `v1.1.0-beta.139` nun sortiert sein.

**Comment by duczz** [comment]
Perfekt, klappt - Danke
