### ISSUE TITLE
Lizens erwerben OHNE PAYPAL

### ISSUE THREAD

**Issue by Bluefish67** [Zefau/ioBroker.jarvis#1900]
Ich habe es mal als Feature request erstellt da es ja kein Käfer ist.

Wann wird es denn möglich sein, eine Lizens für Jarvis zu erwerben, ohne PAYPAL ?
Ich würde ja gerne eine Erwerben (unterstützt ja immerhin den/die Programmierer) , aber will mir nur dafür keinen Account bei PAYPAL anlegen. Ich habe fast 10Jahre ein Onlineshop geführt, ohne PAYPAL, und das will ich auch nicht ändern.

Wäre schön wenn das mal geändert werden würde.

**Comment by Zefau** [comment]
Finde ich super. Schreib mir gerne via iobroker.jarvis@mailbox.org, dann schicke ich dir die IBAN.

**Comment by Bluefish67** [comment]
Hallo Zefau, hab Dir eine  Nachricht per Email geschickt. Hatte das total vergessen....

**Comment by Zefau** [comment]
ab v3.1-beta kann Pro nun via Überweisung bezahlt werden:

![image](https://user-images.githubusercontent.com/14368811/200676515-891eb21f-1dc7-47bc-88a3-c081afcf057d.png)

1. Nach der Eingabe der Email-Adresse wird ein Code generiert, der bei der Überweisung zu nutzen ist
2. Nach Eingang der Überweisung wird eine Rechnung und Lizenz im Wert der Überweisung erstellt und an die angegebene Email-Adresse geschickt
