### ISSUE TITLE
Absturz roter Bildschirm 

### ISSUE THREAD

**Issue by derdoerk** [Zefau/ioBroker.jarvis#1901]
Hallo, 

ich habe seit dem Update auf 3.0.13 das Problem, dass meine Oberfläche abstürzt.

Ein Downgrade ist leider ohne erfolg. Laut Meldung habe ich Error: Verification failed

<img width="895" alt="image" src="https://user-images.githubusercontent.com/79893009/192097679-53c3d8db-02a5-402a-8d70-f3a39592da79.png">

**Comment by mcuiobroker** [comment]
Welche nodejs Version?

**Comment by anaCIRdes** [comment]
Das selbe Problem hatte ich auch, dann habe ich mein Backup wieder zurück spielen müssen und die Jarvis Version 3.0.11 wieder verwenden müssen. 
Ich habe die nodejs-Version 14.19.1

**Comment by Zefau** [comment]
bitte Node.js auf v16 upgraden und jarvis 3.1

**Comment by Zefau** [comment]
oder jarvis v3.0.15 ?
