### ISSUE TITLE
Port 8400 skips Web Adapter Authentication

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1904]
https://forum.iobroker.net/post/848861

**Comment by Hunduster** [comment]
Wie ist denn hier der Status? Mir ist der Bug auch gerade erst aufgefallen und ich musste deswegen den externen Zugriff deaktivieren.

**Comment by Zefau** [comment]
@Hunduster schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by Zefau** [comment]
@Hunduster

**Comment by Hunduster** [comment]
Bitte entschuldige die späte Antwort. Sieht gut aus! Der Request bleibt nun leer über einen fremden Browser.

**Comment by Zefau** [comment]
Super, dann schließe ich?
