### ISSUE TITLE
e.map Adapter Parcel jsonTable

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1910]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.0.13 ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [vendor.2f36216f.js:145 TypeError: e.map is not a function
    at a.flatten (app.f0023f28.js:1:933269)
    at a.parse (app.f0023f28.js:1:930332)
    at a.gotState (app.f0023f28.js:1:930186)
    at h.<anonymous> (app.f0023f28.js:1:167119)
    at l.emit (vendor.2f36216f.js:155:86344)
    at app.f0023f28.js:1:171276
    at Array.forEach (<anonymous>)
    at app.f0023f28.js:1:170754] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Ich füge die json Funktion vom Adapter in eine jsonTable ein und bekomme diesen Fehler

Hier die jsontable

```
{
   "sendungen":[
      {
         "id":"00000001",
         "hasCompleteDetails":true,
         "sendungsinfo":{
            "gesuchteSendungsnummer":"00000001",
            "sendungsname":"AMAZON - WRO2",
            "sendungsrichtung":"ANKOMMEND",
            "sendungsliste":"AKTUELL"
         },
         "sendungsdetails":{
            "sendungsnummern":{
               "sendungsnummer":"00000001",
               "multiFrankingIds":[
                  
               ]
            },
            "versender":{
               "name":"AMAZON - WRO2"
            },
            "panEmpfaenger":{
               "name":"Name",
               "ort":"Ort"
            },
            "sendungsverlauf":{
               "datumAktuellerStatus":"2022-09-26T01:37:00+02:00",
               "aktuellerStatus":"Die Sendung wird zum Weitertransport vorbereitet.",
               "kurzStatus":"Die Sendung wird zum Weitertransport vorbereitet.",
               "fortschritt":3,
               "maximalFortschritt":5,
               "farbe":0,
               "iconId":"3",
               "events":[
                  {
                     "datum":"2022-09-25T10:24:00+02:00",
                     "status":"Die Sendung wurde elektronisch angekündigt. Sobald die Sendung von uns bearbeitet wurde, erhalten Sie weitere Informationen.",
                     "ruecksendung":false
                  },
                  {
                     "datum":"2022-09-26T01:37:00+02:00",
                     "ort":"Stahnsdorf",
                     "status":"Die Sendung wird zum Weitertransport vorbereitet.",
                     "ruecksendung":false
                  }
               ]
            },
            "services":{
               "statusbenachrichtigung":{
                  "aktuellerStatus":true,
                  "geplanteZustellung":true,
                  "erfolgteZustellung":true
               },
               "verfuegen":{
                  "zsmShipmentToken":"Langer-Quatsch-den kein Mensch brauch"
               }
            },
            "zustellung":{
               "zustellzeitfensterVon":"2022-09-27T00:00:00+02:00",
               "zustellzeitfensterBis":"2022-09-27T00:00:00+02:00",
               "abholcodeAvailable":false,
               "benachrichtigtInFiliale":false
            },
            "zielland":"Deutschland",
            "istZugestellt":false,
            "ruecksendung":false,
            "retoure":false,
            "warenpost":false,
            "bahnpaket":false,
            "expressSendung":false,
            "quelle":"PAKET",
            "international":false,
            "anzeigeBriefbenachrichtigung":false,
            "nachhaltigkeitsstatus":{
               "bahnpaket":false,
               "ggpVersender":false,
               "ggVersender":true,
               "ggpEmpfaenger":false,
               "co2FreieZustellung":false,
               "klimafreundlicherEmpfang":false
            }
         },
         "versandDatumBenoetigt":false
      }
   ],
   "mergedAnonymousShipmentListIds":[
      
   ]
}
```

Ich habe jetzt etwas rausgelöscht... Hoffe das ist kein Problem.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Mephisto090** [comment]
könnte es daran liegen, das ganz am Anfang die [ und am ende ] fehlen?

Wenn ja, wäre es möglich bei Jarvis einzubauen, dass er diese, wenn es fehlt automatisch einsetzt?

**Comment by Mephisto090** [comment]
gerade getestet. Das Problem besteht aus zwei Gründen:

1. Am Anfang und am Ende fehlt [ ]
2. Jarvis kommt nicht damit klar, dass es sozusagen eine Tabelle in der Tabelle ist:

{"sendungen":
[{"id":"00000001", usw.

**Comment by Zefau** [comment]
Das mit der Klammer `[ ... ]` kann ich fixen, aber das Grundproblem ist, dass die eigentlichen Daten der Tabelle unter `sendungen` ist, das heißt jarvis würde es so anzeigen:

![image](https://user-images.githubusercontent.com/14368811/192616380-96fce767-b2c2-497a-be33-c437c4f42b1f.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.49`

**Comment by Mephisto090** [comment]
Wäre es nicht möglich eine Tabelle in der Tabelle darzustellen?

**Comment by Zefau** [comment]
Mit v3.1 wird die geschachtelte Hierarchie in eine flache Darstellung aufgelöst.

Für alles andere bitte für https://github.com/Zefau/ioBroker.jarvis/issues/1825 voten.
