### ISSUE TITLE
jsonTable

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1911]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.0.13] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Ich sage ihm zwar das genaue field er geht aber einfach mit den Daten von links nach rechts durch. Sprich wenn ich welche auslasse werden die Werte trotzdem so übernommen. Muss ich die json selbst ausdünnen oder gibt es eine Möglichkeit das javis nur das anzeigt, was ich auch über die Spalten Format Option festlege?

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

```
[
  {
    "flied": "id",
    "label": "ID",
    "align": "center",
    "sortable": "true"
  },
  {
    "flied": "sendungsinfo.gesuchteSendungsnummer",
    "label": "Sendungsnummer",
    "align": "left",
    "sortable": "false"
  },
  {
    "flied": "sendungsdetails.versender.name",
    "label": "Versender",
    "align": "left",
    "sortable": "true"
  },
  {
    "flied": "sendungsdetails.panEmpfaenger.name",
    "label": "Empfänger",
    "align": "left",
    "sortable": "true"
  },
  {
    "flied": "sendungsdetails.sendungsverlauf.aktuellerStatus",
    "label": "Aktueller Status",
    "align": "left",
    "sortable": "true"
  },
  {
    "flied": "sendungsdetails.zustellung.zustellzeitfensterVon",
    "label": "Zustellung von",
    "align": "left",
    "sortable": "true"
  },
  {
    "flied": "sendungsdetails.zustellung.zustellzeitfensterBis",
    "label": "Zustellung bis",
    "align": "left",
    "sortable": "true"
  },
  {
    "flied": "sendungsdetails.istZugestellt",
    "label": "Zugestellt",
    "align": "left",
    "sortable": "true"
  }
]
```

![image](https://user-images.githubusercontent.com/85995176/192267382-7af9ae77-90fb-45a7-a8f7-8f96b13571fe.png)

![image](https://user-images.githubusercontent.com/85995176/192267987-29067526-67da-4f6a-b075-6ba2a6a6b9a9.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by mcuiobroker** [comment]
Ändere mal flied auf field.

**Comment by Zefau** [comment]
`field` statt `flied`
