### ISSUE TITLE
v3.1.0-alpha.49 StateHTML wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1919]
Ohne Fehlermeldung
![image](https://user-images.githubusercontent.com/84818934/192635416-0a055187-a366-4a0c-9f7a-d829e5622177.png)

![image](https://user-images.githubusercontent.com/84818934/192635262-1dc31e63-4168-4c0f-9afc-86adebbb8bf2.png)

**Comment by Zefau** [comment]
`v3.1.0-alpha.50`

**Comment by mcuiobroker** [comment]
Passt. Danke.
Aufgefallen ist, hier auch kein automatischer Reload.
