### ISSUE TITLE
v3.1.0-alpha.50 LightColorState Farbe wird nicht korrekt angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1920]
![image](https://user-images.githubusercontent.com/84818934/192651841-7c2965ae-e91a-4c67-81d9-9265d4fee84f.png)

![image](https://user-images.githubusercontent.com/84818934/192651882-ba03385e-6cb3-4f4c-802d-7bcef28507dc.png)
![image](https://user-images.githubusercontent.com/84818934/192651981-41592879-7e73-44f8-85c4-cd3563e82290.png)

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by mcuiobroker** [comment]
Passt, Danke.
