### ISSUE TITLE
Untertitel

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1921]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.1.0-alpha.50] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

(Siehe Screenshot 1) unten "morgen", "heute" und die Tage stand früher das Datum. Alle kleine Anmerkung unten den Hauptaussagen sind weg :(

Im Widget ist alles wie vorher (Screen 2)

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/85995176/192771458-aa48d79f-2cbd-4347-bd4e-400a1be9584f.png)
(Screen 1)

![image](https://user-images.githubusercontent.com/85995176/192772390-6c5c53bd-e20d-4353-ac5d-3a3f588b349c.png)
(Screen 2)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Mephisto090** [comment]
Ist in ganz Jarvis weg unter allen Sachen :(

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/192773963-3d4b6c76-34af-4ce9-ba6b-5a6a25b65540.png)

unter Erreichbar würde jetzt 100% oder so stehen.

**Comment by mcuiobroker** [comment]
@Mephisto090 Versuch mal bitte mit `{"default":{"color":"#3441fe"}}` im Icon Stil. Ändert sich was?

**Comment by Zefau** [comment]
Ist das von alpha.49 auf alpha.50 passiert? Ich musste was an der internen API ändern.

**Comment by mcuiobroker** [comment]
Dadurch wurde der Bildaufbau jedenfalls gefühlt 3x so schnell.

**Comment by Mephisto090** [comment]
> Ist das von alpha.49 auf alpha.50 passiert? Ich musste was an der internen API ändern.

Ich habe direkt auf v50 geupdatet

> @Mephisto090 Versuch mal bitte mit `{"default":{"color":"#3441fe"}}` im Icon Stil. Ändert sich was?

leider nein

**Comment by Mephisto090** [comment]
@Zefau brauchst du noch Infos für den Fehler?

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by Mephisto090** [comment]
Top! Alles wieder da. Nur die Farbe der Mülltonnen noch nicht

![image](https://user-images.githubusercontent.com/85995176/193401254-f3025dfb-f22e-4f5a-ac6e-4932c491c1ea.png)

**Comment by Mephisto090** [comment]
Bio war vorher Braun
Rest Schwarz
Pappe Blau
Lichtstoff Gelb

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/193401322-818306e7-c351-4603-b8fa-e8a17aa4c02a.png)


Fehler gefunden

Muss jetzt so sein: {"default":{"color":"#3441fe"}}

und nicht mehr so: {"color":"#3441fe"}

**Comment by Zefau** [comment]
Sollte aber auch ohne gehen. Ich schaue nochmal

**Comment by Mephisto090** [comment]
Alles klar

**Comment by Mephisto090** [comment]
> Sollte aber auch ohne gehen. Ich schaue nochmal

habe es noch mal getestet ohne geht es nicht (`v3.1.0-alpha.52`)

**Comment by Zefau** [comment]
Ball liegt auch noch bei mir. Ich gebe Bescheid, wenn du testen kannst.

**Comment by Mephisto090** [comment]
> Ball liegt auch noch bei mir. Ich gebe Bescheid, wenn du testen kannst.

Ok, wusste ich nicht :)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.53`

**Comment by Mephisto090** [comment]
geht :)
