### ISSUE TITLE
SVG Image Gäste-WLAN über FritzBox-Adapter-Objekt

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1923]
**Voraussetzungen**
- [v3.1.0-alpha.50] Welche Version von jarvis nutzt du?

**Beschreibe den Fehler**

Hej,

ich bekomme mein Gäste-WLAN QR Code via Adapter "fb-checkpresence". Leider finde ich keine Möglichkeit es in Jarvis dazustellen. 

Verkürztes Beispiel:
```
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 35 35"><path fill="black" d="M1 1h7v7h-7zM10 1h2v1h-2zM14 1h2v1h2v1h-3v1h-1zM19 1h3v2h1v1h-2v1h2v1h-3v-3h1v-1h-2zM27 1h7v7h-7zM2 2v5h5v-5zM12 2h1v2h1v1h-2v-1h-2v1h1v2h-1v1h1v-1h1v2h-1v1h1v2h-1v1h-1v-1h-1v1h1v1h-1v1h1v1h-1v1h-1v-1h-1v-1h1v-1h-3v-1h1v-1h1v1h1v-1h-1v-1h1v-1h2v-1h-1v-6h3zM23 2h1v1h-1zM25 2h1v3h-1v1h-1v-1h-1v-1h1v-1h1zM28 2v5h5v-5zM3 3h3v3h-3zM29 3h3v3h-3zM15 4h2v2h1v2h-1v-1h-1v-2h-1zM18 4h1v1h-1zM14 5h1v2h-1zM12 6h1v1h-1zM23 6h1v2h-1zM13 7h1v4h-1v-1h-1v-1h1zM15 7h1v1h-1zM19 7h1v1h-1zM21 7h1v1h-1zM25 7h1v1h-1zM20 8h1v2h2v1h-3zM22 8h1v1h-1zM1 9h1v1h1v1h1v-1h-1v-1h5v1h-2v2h-1v1h-1v-1h-3zM15 9h1v1h-1zM17 9h2v1h-1v2h-2v-2h1zM23 9h1v1h-1zM27 9h5v1h-5zM24 10h3v1h-1v2h-1v-2h-1zM33 10h1v1h-1zM23 11h1v3h1v1h-2v-2h-1v-1h1zM28 11h4v1h1v1h-1v2h1v1h1v1h-1v1h-1v1h-2v-1h-1v-1h1v-1h1v-3h-1v1h-1v-1h-2v-1h1zM13 12h1v2h-2v-1h1zM15 12h1v1h-1zM20 12h1v1h-1zM1 13h1v1h-1zM3 13h1v1h-1zM17.........."/></svg>
```

**Screenshots**

![image](https://user-images.githubusercontent.com/85995176/192954315-6f9869a1-5bee-468f-a41f-ee9fb59816cf.png)

**Comment by mcuiobroker** [comment]
Welches Module nutzt du denn?

**Comment by Mephisto090** [comment]
DisplayImage... jetzt geht es auf einmal....

**Comment by Mephisto090** [comment]
Ich glaube der Adapter war in diesem Moment abgeraucht. Jetzt wo er wieder läuft wird auch was angezeigt :)

**Comment by Mephisto090** [comment]
Gibt es eine möglichkeit, wenn das Gäste-WLAN aus ist auch kein QR Code von Jarvis angezeigt wird. Sprich "An Bild da" "Aus Bild weg"?

![image](https://user-images.githubusercontent.com/85995176/192964710-b9447c14-3e61-4a80-8828-e923d811d485.png)

**Comment by mcuiobroker** [comment]
@zefau `{"default":{"display":"none !important"}}` wird für displayImage nicht mitgegeben im Frontend.

![image](https://user-images.githubusercontent.com/84818934/192969496-019ab60b-aae1-4165-9ad7-ffde9b470e7e.png)

**Comment by Mephisto090** [comment]
> @Mephisto090 `{"{tr-064.0.states.wlanGuest}=false":{"display":"none !important"}}` damit sollte es eigentlich funktionieren, ist aber noch nicht der Fall.

Kann ich das auch auf das hier beziehen?
https://github.com/Zefau/ioBroker.jarvis/discussions/1922

**Comment by mcuiobroker** [comment]
Auf jeden DP aus ioBroker.

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by mcuiobroker** [comment]
Landet im falschen div:
![image](https://user-images.githubusercontent.com/84818934/193362858-cb19afa6-f07c-4a8c-b51c-c06e071b65a3.png)
Müsste im obenren div genutzt werden jarvis-widget-widgetID
![image](https://user-images.githubusercontent.com/84818934/193363009-6088d8af-3779-42cb-aa8f-480479f46c48.png)
Dann ist es weg:
![image](https://user-images.githubusercontent.com/84818934/193363039-a38ca7ff-a7c7-402d-a85e-505dee795714.png)

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/193401122-72598d45-c649-4b95-8b2d-fbd318e713b8.png)
![image](https://user-images.githubusercontent.com/85995176/193401132-6b4623ca-498d-46f3-99f9-124a09dba949.png)
![image](https://user-images.githubusercontent.com/85995176/193401150-bf0bfd8e-11b9-4c35-9783-7c21882f8658.png)
![image](https://user-images.githubusercontent.com/85995176/193401174-4415b956-540b-4e2c-ad43-30e50b6eea6f.png)


Mache ich was falsch oder ist es noch nix Fixed?

**Comment by Mephisto090** [comment]
@Zefau lässt sich damit auch ein Secondary State verstecken?

**Comment by Mephisto090** [comment]
@mcuiobroker würde theoretisch auch `!=` gehen?

`{"{tr-064.0.states.wlanGuest}!=false":{"display":"none;"}}`

**Comment by Zefau** [comment]
Es geht nur auf der Ebene `jarvis-DisplayImage` oder darunter. Die `div`'s darüber kennen die Zustände der Datenpunkt nicht, da es sich um eine allgemeine Container-Struktur handelt. Die Daten werden erst im Modul geladen.

> lässt sich damit auch ein Secondary State verstecken?

Ja, einzelne Werte im Secondary State sollten mittels Datenpunkt-Stil ausblendbar sein.

> Muss ich bei einem String eigentlich ' setzen?

Ja.

> Ich spreche leider nur Software Programmiersprachen :(

Es ist alles Javascript.

> Incorrect callback function (deactivated!=sharp) supplied to Alarmanlage (password)!

Es fehlt `'`.

**Comment by Mephisto090** [comment]
> Es ist alles Javascript.

und genau da ist das Problem (`Javascript`) :D

> > Incorrect callback function (deactivated!=sharp) supplied to Alarmanlage (password)!
> 
> Es fehlt `'`.

Selbst mit `'` hat es nicht funktioniert

**Comment by Zefau** [comment]
Das `;` muss auch raus. Wie sieht es dann aus?

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/193418395-6bb74cd6-158b-47c1-8d38-03b13cf4586e.png)
![image](https://user-images.githubusercontent.com/85995176/193418304-036fc1e6-2a93-47da-a67c-6f204c0314af.png)
![image](https://user-images.githubusercontent.com/85995176/193418328-38d6e37f-dd5b-4186-8543-654667ce1ce4.png)

```
Incorrect callback function (sharp=='sharp') supplied to Alarmanlage (enable)!
sharp is not defined
```


nope, leider nicht

**Comment by Zefau** [comment]
`{"'{alarm.0.status.state}'!='sharp'":{"display":"none"}}`
statt
`{"{alarm.0.status.state}!=sharp":{"display":"none;"}}`

**Comment by Mephisto090** [comment]
> `{"'{alarm.0.status.state}'!='sharp'":{"display":"none"}}`
> statt
> `{"{alarm.0.status.state}!=sharp":{"display":"none;"}}`

![image](https://user-images.githubusercontent.com/85995176/193419757-bc53f1c6-a34f-4c56-9144-efbabf2100b7.png)
![image](https://user-images.githubusercontent.com/85995176/193419780-cdfa1b22-7d79-4df7-ac7c-3c5b2ba8ba64.png)
![image](https://user-images.githubusercontent.com/85995176/193419799-2a0bfc21-5cbe-4e55-9e3c-ba01bf162a34.png)


Leider nein! :(

**Comment by Mephisto090** [comment]
> {"'{alarm.0.status.state}'!='sharp'":{"display":"none"}}

Funktioniert!

**Comment by Mephisto090** [comment]
> wie sieht eine und/oder Verbindung aus?

UND: `&&`

ODER: `||`

`{"'{alarm.0.status.state}'='sharp' || '{alarm.0.status.state}'='gets activated'":{"display":"none"}}`

**Comment by Zefau** [comment]
Schau nochmal mit `v3.1.0-alpha.53`. Verschwinden wird das Widget aber nicht, nur das DisplayImage.

**Comment by mcuiobroker** [comment]
Funktioniert.
