### ISSUE TITLE
[Bug] Secondary state wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by Chris25122** [Zefau/ioBroker.jarvis#1925]
Hallo Zefau,

mit dem Version v3.1.0-alpha.50 werden die secondary states bei mir nicht mehr angezeigt.
In früheren Versionen hat es funktioniert.

![image](https://user-images.githubusercontent.com/48753907/193345121-2bf7a7c0-4df5-4b67-9fe0-d51ac9dd7cba.png)

![image](https://user-images.githubusercontent.com/48753907/193345172-33e65966-0681-47b5-a70d-d4c740049fee.png)

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-alpha.52`

**Comment by Chris25122** [comment]
> schau mal mit `v3.1.0-alpha.52`

Funktioniert damit wieder, danke.
