### ISSUE TITLE
`setOn` / `setOff` als Callback

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1926]
Jo, die Einstellungsmöglichkeiten sind alle lediglich für die Anzeige und rein visuell. `setOn` und `setOff` sind zum Schalten, unterstützen aber keinen Callback.

_Originally posted by @Zefau in https://github.com/Zefau/ioBroker.jarvis/discussions/1888#discussioncomment-3775677_

**Comment by Zefau** [comment]
@mcuiobroker schau mal mit `v3.1.0-alpha.52`

`setOn` im Gerät als Funktion, also `val => ...`

**Comment by mcuiobroker** [comment]
Besser wäre es, wenn man mit `min` und `max` einfach arbeiten könnte.
max=0 , min= min= 100.

**Comment by Zefau** [comment]
dann mach mal einen neuen Feature Request auf

**Comment by mcuiobroker** [comment]
Auch beim LevelBody in der StateList kommt die Warnung:
![image](https://user-images.githubusercontent.com/84818934/193361782-72fc0793-b379-4167-ba24-f60d024612d5.png)
setOn klappt nicht:
`{"setOn":"val => Math.floor(100-val)","min":100,"max":0}` 
![image](https://user-images.githubusercontent.com/84818934/193361823-b20bbcbb-17f6-41a0-8756-df8072afc53b.png)
![image](https://user-images.githubusercontent.com/84818934/193361847-7c0090b0-1c8c-456b-80a6-c6e644558b52.png)

**Comment by Zefau** [comment]
wie gesagt `"min":100,"max":0` ist nicht supported. `min` muss kleiner als `max` sein.

Den Callback fixe ich.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.53`

**Comment by mcuiobroker** [comment]
Callback funktioniert. Danke.
