### ISSUE TITLE
v3.1.0-alpha.52 Kalender wird nicht direkt geladen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1928]
Nach Neustart oder F5 wird der Kalender beim Umschalten auf den zugehörigen TAB nicht geladen.
![image](https://user-images.githubusercontent.com/84818934/193360667-63d1c913-78bb-4985-a4cb-58fac7f75557.png)

Erst nach F5 auf dem TAB wird der Kalender geladen.
![image](https://user-images.githubusercontent.com/84818934/193360881-2766bfed-f3a8-4fa5-9b3a-73a4770750e8.png)

![image](https://user-images.githubusercontent.com/84818934/193360984-c8ce131d-1bfb-4aba-ba1b-dd3c1f2a9666.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.54`

**Comment by Zefau** [comment]
@mcuiobroker

**Comment by mcuiobroker** [comment]
Scheint ok zu sein.
