### ISSUE TITLE
Falsche auswahl für Datenquelle history.0 statt influxdb bei Neu laden einer seite

### ISSUE THREAD

**Issue by softwarecrash** [Zefau/ioBroker.jarvis#1929]
Ich habe eine etwas ungewöhnliches Phänomen nach einem update von V2 auf V3,
ich habe mehrere "tabs" mit histographen, wenn man auf einem tab ist und die Seite neu lädt, baut sich der histograph nicht auf, klickt man auf ein anderes tab baut er sich auf, es betrifft also nur das tab was ausgewählt ist zum Zeitpunkt des neu Ladens.

bei `V3.0.13` stand dann immer noch eine Warnung da das history.0 nicht erreichbar ist. mit der aktuellen `alpha52` ist die Fehlermeldung verschwunden aber das Problem nicht das er nicht lädt.

auch in den logs taucht diese Meldung auf.

history Adapter ist und war nie installiert, einzig influxdb ist aktiv.
Jarvis wird direkt über port 8400 aufgerufen.

Bei neuladen von der seite steht in der adresszeile zb noch ':8400/#/schlafzimmer2' erwartet er dann evt noch weitere settings in der adresszeile die nicht da sind und nimmt daher standartmäsig den history adapter bzw versucht es?

hier ein stück log wenn man eine Page neu läd mit einem Graphen.
`<html><body>

jarvis.0 | 2022-10-01 10:31:43.939 | debug | subscribeHistory  (linkeddevices.0.Wetter.Schlafzimmer.humidity): 8248614434740057 \|  {"aggregate":"none","review":604800000,"count":9999999,"instance":"history.0","action":"subscribeHistory","force":true}
-- | -- | -- | --
jarvis.0 | 2022-10-01 10:31:43.938 | debug | subscribeHistory  (linkeddevices.0.Wetter.Schlafzimmer.humidity): 8248614434740057 \|  {"aggregate":"none","review":604800000,"count":9999999,"instance":"history.0"}
jarvis.0 | 2022-10-01 10:31:43.937 | debug | subscribeHistory  (linkeddevices.0.Wetter.Schlafzimmer.temperature): 4556566633810410 \|  {"aggregate":"none","review":604800000,"count":9999999,"instance":"history.0","action":"subscribeHistory","force":true}
jarvis.0 | 2022-10-01 10:31:43.936 | debug | subscribeHistory  (linkeddevices.0.Wetter.Schlafzimmer.temperature): 4556566633810410 \|  {"aggregate":"none","review":604800000,"count":9999999,"instance":"history.0"}

</body>
</html>`

nach dem neu laden, und klicken auf ein anderes tab mit Graph macht er was er soll, auch mit der richtigen Instanz
`<html><body>

jarvis.0 | 2022-10-01 10:40:30.693 | debug | subscribeHistory  (linkeddevices.0.Wetter.Wohnzimmer.humidity): 7582828414393573 \|  {"aggregate":"none","review":604800000,"count":9999999,"instance":"influxdb.0","action":"subscribeHistory","force":true}
-- | -- | -- | --
jarvis.0 | 2022-10-01 10:40:30.692 | debug | subscribeHistory  (linkeddevices.0.Wetter.Wohnzimmer.humidity): 7582828414393573 \|  {"aggregate":"none","review":604800000,"count":9999999,"instance":"influxdb.0"}
jarvis.0 | 2022-10-01 10:40:30.688 | debug | subscribeHistory  (linkeddevices.0.Wetter.Wohnzimmer.temperature): 8790756681411145 \|  {"aggregate":"none","review":604800000,"count":9999999,"instance":"influxdb.0","action":"subscribeHistory","force":true}
jarvis.0 | 2022-10-01 10:40:30.687 | debug | subscribeHistory  (linkeddevices.0.Wetter.Wohnzimmer.temperature): 8790756681411145 \|  {"aggregate":"none","review":604800000,"count":9999999,"instance":"influxdb.0"}

</body>
</html>`

**Comment by Zefau** [comment]
kannst du bitte prüfen, ob das Problem mit `v3.1.0-alpha.58` noch besteht?

**Comment by softwarecrash** [comment]
leider keine änderung mit alpha.58 im log taucht immer noch history.0 auf was auf dem system nicht exsitiert.
auch nur bei der aktuellen seite die man neu läd, nach dem laden auf anderen tabs funktioniert alles

**Comment by Zefau** [comment]
Bei mir funktioniert es. Kannst du das Gerät im Widget (nicht das Gerät selbst) mal neu hinzufügen?

**Comment by softwarecrash** [comment]
hab es eine weile nicht beobachtet, es scheint wohl an irgendwas anderem gelegen zu haben.
mitlerweile ist es weg, ggf war irgendein anderer adapter oder admin dafür verantwortlich.
