### ISSUE TITLE
Optischer Fehler

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1930]
Hej @Zefau,

Version: v3.1.0-alpha.52

![image](https://user-images.githubusercontent.com/85995176/193403521-e42a0560-3024-4f7e-8c32-0689eecc7ce2.png)

Das Komma müsste direkt hinter den ersten Wert kommen:

Falsch: `nicht Erreichbar , 97 %`
Richtig: `nicht Erreichbar, 97 %`

**Comment by mcuiobroker** [comment]
Scheint an dem Wert zu liegen:
number
![image](https://user-images.githubusercontent.com/84818934/193413159-9143ee18-f470-4d58-921b-691916471a37.png)

string
![image](https://user-images.githubusercontent.com/84818934/193413168-8edc87a9-b135-4ce8-b5ca-d6c6bb7dc28a.png)

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.0-alpha.53`

**Comment by mcuiobroker** [comment]
Passt. Danke.
