### ISSUE TITLE
v3.1.0-alpha.52 Import Homematic IP Rollladen funktioniert nicht

### ISSUE THREAD

**Issue by isi07** [Zefau/ioBroker.jarvis#1932]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
v3.1.0-alpha.52

**Describe the bug / Beschreibe den Fehler**
Beim automatischen Import von Geräten vom Adapter hm-rpc werden bei mir Rollläden vom Typ HmIP-BROLL nicht mehr erkannt.
Sie tauchen als fehlerhafte Geräte auf, die nicht importiert werden können.
In vorherigen Versionen von Jarvis hat der Import funktioniert.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/65848350/193420221-ae8cd08e-5763-4f51-83f6-b649a2b68df0.png)

**Comment by Zefau** [comment]
Merkwürdig. Die BROLL-Konfiguration habe ich nicht angepasst.

Kannst du mir mal ein BROLL Gerät exportieren?

![image](https://user-images.githubusercontent.com/14368811/193425371-5b9a2f85-3ed0-4d18-adcc-1e4c52680419.png)

**Comment by isi07** [comment]
anbei
[hm-rpc.2.XXX_HMIP-BROLL_XXX.json.zip](https://github.com/Zefau/ioBroker.jarvis/files/9691195/hm-rpc.2.XXX_HMIP-BROLL_XXX.json.zip)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.59`
