### ISSUE TITLE
v3.1.0-alpha.53 ButtonGroupAction Falsche Darstellung

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1934]
Falsche Darstellung:
![image](https://user-images.githubusercontent.com/84818934/193450245-5beb3841-1dc1-4af4-887f-cbc5dd629d26.png)

![image](https://user-images.githubusercontent.com/84818934/193450205-a689232d-387b-42bb-bc78-4521310ce5c1.png)

Hatten wir schon drüber geschrieben, hab es nicht mehr gefunden?

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.54`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/193479766-53ca2bb5-dea3-44b6-a1cb-b41f01e6297e.png)

- [ ] Warum bei on/off Icon über dem Label und bei up/down neben dem Label? Einstellbar machen?

![image](https://user-images.githubusercontent.com/84818934/193479803-dedef5b6-10b4-4d80-bc85-d67f89c1684b.png)

- [ ] Sonst war ein blauer Hintergrund zu sehen? Sollte ja noch anpassbar gemacht werden?
![image](https://user-images.githubusercontent.com/84818934/193479892-15e71730-569d-4b94-ab16-e03357944d52.png)

**Comment by mcuiobroker** [comment]
Ja, aber vorher wurde es mit Umrandung (siehe oben) mit blauem Hintergrund dargestellt, jetzt nicht mehr?

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.55`

**Comment by mcuiobroker** [comment]
Passt wieder. Die Hintergrundfarben-Einstellung kommt dann mit #1907 ?

**Comment by Zefau** [comment]
Für die Hintergrund Farbe wollte ich keine Einstellung machen. Das ist so kleinteilig und speziell, dass CSS hier besser ist
