### ISSUE TITLE
v3.1.0-alpha.53 Neue Widget Funktion übersetzen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1935]
![image](https://user-images.githubusercontent.com/84818934/193450318-4178de60-8b53-4c1f-b2d3-1a9494855d95.png)

**Comment by mcuiobroker** [comment]
Passt nicht zum Module displayImage? Da kann man nur einen auswählen.
![image](https://user-images.githubusercontent.com/84818934/193456667-d09d1b11-c78f-432f-b79d-0198bc117a4d.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.54`

**Comment by mcuiobroker** [comment]
Passt. Danke.
