### ISSUE TITLE
Zeitfehler

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1936]
Hej @Zefau,

v3.1.0-alpha.52

![image](https://user-images.githubusercontent.com/85995176/193450634-cd3cd534-c679-4413-9389-96dd1e849647.png)
![image](https://user-images.githubusercontent.com/85995176/193450652-7004f71f-47fd-4f2b-a9e3-191241ada4b3.png)

Zeit läuft nicht mehr richtig (nur noch jede Minute) und Sonnenauf und -untergang laden locker 2min.

**Comment by Zefau** [comment]
Läuft bei mir flüssig. Hast du Fehler in der Browser-Konsole?

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/193571839-8c9d6cb0-babd-49fb-8fe1-12831218dfa3.png)

**Comment by Mephisto090** [comment]
Bin jetzt auf v3.1.0-alpha.54 gegangen. Funktioniert immer noch nicht

**Comment by Zefau** [comment]
Da scheint eins deiner Chrome Extensions defekt zu sein

**Comment by Mephisto090** [comment]
Meinst du das liegt daran?

**Comment by Mephisto090** [comment]
auf dem Tablet mit Firefox geht's auch nicht

**Comment by Zefau** [comment]
Wundert mich nur, da es bei mir problemlos geht mit Firefox und Chrome auf Desktop.

**Comment by Zefau** [comment]
Kannst du deine Modul Einstellungen Mal screenshoten?

Hast du im ioBroker Backend in den Admin Einstellungen die Koordinaten deines Standorts drin?

**Comment by Mephisto090** [comment]
> Hast du im ioBroker Backend in den Admin Einstellungen die Koordinaten deines Standorts drin?

Ja, habe ich :)

> Kannst du deine Modul Einstellungen Mal screenshoten?

Na dann hoffen wir mal, dass ich nicht doof bin :D

![image](https://user-images.githubusercontent.com/85995176/193779396-65ad1357-86ed-4aa5-8e5d-4ee236a8a000.png)

**Comment by Bernd9000** [comment]
Ich hab das bei mir auch wenn ich so wie Mephisto090  Uhrzeit und Datum in dem ersten Feld eintippe.
Geht das so überhaupt ?
Bei mir steht Standartmäßig die Uhrzeit im zweiten Eingabefeld und dann läuft die Uhrzeit weiter

**Comment by Zefau** [comment]
Die Labels sind falsch. Links ist Datum und rechts Uhrzeit. Durch die Trennung gibt es zwei verschiedene CSS-Klassen, wodurch es unterschiedlich gestyled werden kann und auch ein Zeilenumbruch möglich ist.

**Comment by Bernd9000** [comment]
@Mephisto090
Tipp das Format mal in das zweite Eingabefenster und lösche das erste.
Dann funktioniert es.

![Unbenannt](https://user-images.githubusercontent.com/77005685/193926671-0d5e4933-5eee-4e7c-8e76-9f119e036c10.jpg)

**Comment by Mephisto090** [comment]
> Tipp das Format mal in das zweite Eingabefenster und lösche das erste.
> Dann funktioniert es.

![image](https://user-images.githubusercontent.com/85995176/193993979-e52912ac-c6f7-4b31-b21a-4b0842bce005.png)

Ja es funktioniert. Ist aber besonders lang geworden :D

Ich muss Links ein Leerzeichen einfügen

![image](https://user-images.githubusercontent.com/85995176/193994088-e5e51b75-eb8e-4147-8995-adc98f258c28.png)

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.0-alpha.55`
