### ISSUE TITLE
Ganztägige Ereignisse einen Tag zu früh

### ISSUE THREAD

**Issue by Deanna4711** [Zefau/ioBroker.jarvis#1937]
v3.1.0-alpha.50

Die ganztägigen Ereignisse werden einen Tag zu früh angezeigt, wenn man nur einen Tag auswählt ("Heute" Widget). Dies betrifft Feiertage genauso wie Geburtstage. Oder liege ich falsch, weil die Ereignisse ja innerhalb eines 24h Zeitfensters (=1 Tag) anfangen?

![Screenshot 2022-10-02 153648](https://user-images.githubusercontent.com/33905778/193457070-38f33269-8bda-4796-b925-4b70efd205c7.jpg)

**Comment by Zefau** [comment]
Sollte nicht angezeigt werden. Links ist auch ein Zeitraum ausgewählt aber nur ein Event. Sieht mir auch falsch aus.

Woher hast du die Feiertage? Manuell eingegeben oder von irgendwo geladen?

**Comment by Deanna4711** [comment]
Geladen über: http://i.cal.to/ical/53/niedersachsen/feiertage/dd9fcc35.df995274-e8a923bc.ics

Bin mir jetzt gerade nicht sicher, von welcher Original Seite die kamen.

**Comment by Deanna4711** [comment]
Ich habe es jetzt noochmal mit einem anderen Kalender probiert: https://onlinekalender.info/feiertage/deutschland/niedersachsen.ics

Das selbe Ergebnis:
![Screenshot 2022-10-02 160314](https://user-images.githubusercontent.com/33905778/193458131-768f718d-4f28-4200-8931-3f67ccb01d91.jpg)

**Comment by Zefau** [comment]
Ich bekomme es leider absolut nicht nachgestellt.

3. Oktober ausgewählt:
![image](https://user-images.githubusercontent.com/14368811/201537418-fe5ab2f8-0f9a-49b7-a639-39c7a5eb3ef9.png)



2. Oktober ausgewählt:

![image](https://user-images.githubusercontent.com/14368811/201537427-930f8b3c-4ff1-4484-a8cb-157d07282249.png)

**Comment by Zefau** [comment]
Kannst du mal bitte die aktuelle beta installieren und jarvis + web Adapter neustarten?

**Comment by Zefau** [comment]
@mcuiobroker wie stark nutzt du den Kalender? Ist hier dieses Issue mit ganztägigen Ereignissen auch schon unter gekommen?

**Comment by Deanna4711** [comment]
> Kannst du mal bitte die aktuelle beta installieren und jarvis + web Adapter neustarten?

3.1.0 beta 20 ist installiert, beide INstatnzen neu gestartet
![Screenshot 2022-11-13 221740](https://user-images.githubusercontent.com/33905778/201545045-8db1fa57-0968-477e-a2eb-280df1383f22.jpg)

**Comment by Zefau** [comment]
Kannst du mal die Konfiguration des "Heute" Widget zeigen?

Wenn du links im Kalender nur den 13 selektierst, kommst du dann auf dasselbe Ergebnis?

**Comment by Deanna4711** [comment]
![Screenshot 2022-11-13 222158](https://user-images.githubusercontent.com/33905778/201545258-46febd38-f9d4-4c5c-9546-e402d57e9a65.jpg)

Du meinst so? 
![Screenshot 2022-11-13 222306](https://user-images.githubusercontent.com/33905778/201545261-7b34517c-97eb-4797-8837-a3d3422f9847.jpg)

**Comment by Deanna4711** [comment]
> Wenn du links im Kalender nur den 13 selektierst, kommst du dann auf dasselbe Ergebnis?
Scheinbar stimmt es dann. Tritt es evtl. nur dann auf, wenn 1 Tag (24h) unterschritten ist? Das habe ich nch nicht genau beobachtet. Muss ich mal drauf achten.

**Comment by Zefau** [comment]
Du musst das heute Widget auf 0 konfigurieren.

**Comment by Deanna4711** [comment]
Ok, sorry.... da bin ich nicht drauf gekommen...

**Comment by Zefau** [comment]
alles gut :-)
