### ISSUE TITLE
v3.1.0-alpha.53: Tabs zusammenfassen geht nicht

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1940]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.1.0-alpha.53] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Wenn ich "Tabs zusammenfassen" aktiviere vermute ich, die sollte als DropDown Menü (wie früher) zusammengefasst werden?! Falls ja, passiert das nicht. Für mich nicht wichtig, da ich das Scrollen haben möchte, aber evtl. für jemand anderen...

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/79741077/193472819-dd29a099-001e-4e1f-b04b-5d2529846bdf.png)
![image](https://user-images.githubusercontent.com/79741077/193472881-332c1d43-237d-4b07-86bf-41d90fc43cbd.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.54`

**Comment by RkcCorian** [comment]
Funktioniert
