### ISSUE TITLE
v3.1.0-alpha.53: Drop-Down bei Selektion keine Aktion

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#1941]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.1.0-alpha.53] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Wenn ich ein Element in einem Drop-Down anklicke passiert nichts mehr 😟
Das wäre doch wichtig 🙃

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![image](https://user-images.githubusercontent.com/79741077/193473940-2b89cedf-865e-44da-8357-992628557b25.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
Es betrifft alle meine Drop-Downs, d.h. ein generelles Problem

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.54`

**Comment by RkcCorian** [comment]
Funktioniert wieder
