### ISSUE TITLE
v3.1.0-alpha.53 HistoryGraph Einstellung bei x-Achsen ziehen nicht mehr oder falsch

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1942]
Setzt man in der x-Achsenkonfiguration
`
{
  "show": true,
  "name": "Zeit",
  "nameLocation": "middle",
  "axisLine": {
    "lineStyle": {
      "color": "red",
      "width": 3
    }
  },
  "splitLine": {
    "show": true
  }
}
`

- [ ] in Konfiguration für die x-Achse so werden die Kurvennamen von der y-Achse ersetzt durch durch den x-Achsen Namen.

- [ ] SplitLine wird gar nicht angezeigt?

- [ ] x-Achsenlinie wird nicht verändert, müsste rot sein und 3px dick

![image](https://user-images.githubusercontent.com/84818934/193474835-ef5398f2-6687-4b49-ac3d-de0a1b23c6cb.png)

![image](https://user-images.githubusercontent.com/84818934/193474790-879c103c-914f-4518-a332-edb9faad3259.png)

**Comment by Zefau** [comment]
> Setzt man

Ist die Konfiguration für die X-Achse oder was genau?

**Comment by mcuiobroker** [comment]
Ja hatte ich in der Überschrift drin, im Text vergessen.Sorry.

**Comment by mcuiobroker** [comment]
Falsche Einstellung
