### ISSUE TITLE
v3.1.0-alpha.53 Wetter-Anzeige zeitweise ohne Icons

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1943]
Wetteranzeige: Zeitweise auch nach F5 ohne Icons
![image](https://user-images.githubusercontent.com/84818934/193475443-7269d08f-dcc7-4ee7-9db2-03f18714d2a2.png)
Nach 3x F5
![image](https://user-images.githubusercontent.com/84818934/193475466-b6e61641-3bda-46b7-8057-ce17cb8ce531.png)

**Comment by Zefau** [comment]
kam das nochmal wieder vor seit der beta?

**Comment by mcuiobroker** [comment]
Bis jetzt nicht bemerkt. Ich schließe erstmal.

**Comment by mcuiobroker** [comment]
`v3.1.0-beta. 21` habe es gerade wieder gehabt.
![image](https://user-images.githubusercontent.com/84818934/201549147-0212652b-c7a3-4113-b676-e8b852872048.png)

Nach F5:
![image](https://user-images.githubusercontent.com/84818934/201549161-c4d06338-afd0-4558-9809-4a0b7913cb2d.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.2`

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.2`
Tagesnamen werden erst kurz dann lang angezeigt?
![jarvis v313-beta2 Fehler wetter springt kurz-lang](https://user-images.githubusercontent.com/84818934/210486207-b535f48d-9a68-453b-b414-7c43eab0f01b.gif)

**Comment by mcuiobroker** [comment]
Aber ich ändere ja gar nicht die Breite. Schalte nur auf die andere Seite und dann ist die Größe (Breite, Höhe) bekannt?

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.3`

**Comment by mcuiobroker** [comment]
Beim wechseln der TAB-Seite wird immer noch von 4 auf 5 gewechselt.
Verhalten hat sich nicht verändert.
