### ISSUE TITLE
v3.1.0-alpha.53 Chart 0 auf x-Achse? und für 0-Werte werden bei hover Leer angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1944]
- [ ] Es wird eine 0 auf der x-Achse angezeigt?

![image](https://user-images.githubusercontent.com/84818934/193476131-3ce216be-f0bc-47f7-af54-b74d6c9ad51b.png)

- [ ] 0-Werte werden im hover als Leer angezeigt

![image](https://user-images.githubusercontent.com/84818934/193476192-18de3644-fbba-4c78-b307-4d27aca3b0f9.png)
![image](https://user-images.githubusercontent.com/84818934/193476197-5af1a18e-dc23-4343-8dae-cb87a7c28d0b.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.54`

**Comment by mcuiobroker** [comment]
Passt. Danke.
