### ISSUE TITLE
v3.1.0-alpha.54 lastChangeBody wird nicht aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1945]
SZ-Lämpchen  10 Sekunden
![image](https://user-images.githubusercontent.com/84818934/193486688-a9119f07-c540-4111-b956-6a9469902c41.png)
Nach F5 -SZ-Lämpchen 18 min
![image](https://user-images.githubusercontent.com/84818934/193486733-a6b3342d-3011-4bf5-a18d-6f2a61a3b047.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.59`

**Comment by mcuiobroker** [comment]
Nein, passt noch nicht. Weiterhin nach F5 andere Werte, wenn man die Seite einige Zeit ruhig stehen lässt und in einem anderen Browser-TAB arbeitet..

**Comment by mcuiobroker** [comment]
Beispiel: Obwohl auf der Seite DPs verändert wurden, werden einige lastChange nicht aktualisiert.
`Büro dunkel` -> aus 24 min werden plötzlich nach F5 44 min.
![image](https://user-images.githubusercontent.com/84818934/196542212-41d89329-048f-4155-a28e-431cf2ba3ec2.png)
![image](https://user-images.githubusercontent.com/84818934/196542470-f2f5fecb-e6fd-4289-9dd7-36d51b899320.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.3`

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.7`
Sieht gut aus. Danke.
