### ISSUE TITLE
InputAction Bug auf Android Geräten

### ISSUE THREAD

**Issue by sten-tor** [Zefau/ioBroker.jarvis#1948]
Sind mehrere InputActions in einem Widget oder Pop-up, kann nur die letzte der InputActions geändert werden. Bei allen vorherigen wechselt die Enter-Taste der Android-Tastatur auf "Tab" und damit kann der Input nicht bestätigt werden - er springt wieder auf den vorherigen Wert zurück.

Jarvis v3.0.13
Gerät: Samsung Galaxy S22
Browser: Chrome
Tastatur: Samsung, Swiftkey

![ezgif-4-02ba33b268](https://user-images.githubusercontent.com/92914169/193619480-b9dd1e26-3cc4-4792-ba81-88f419c22f32.gif)

**Comment by Zefau** [comment]
Sollte mit V3.1-alpha behoben sein. Bitte von GitHub installieren und testen

**Comment by Zefau** [comment]
@Bernd9000 mit `v3.0.14` sollte es drin sein
