### ISSUE TITLE
v3.1.0-alpha.54: Body Element wird angezeigt obwohl nicht parametriert 

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#1949]
Es wird das Body Element LastChangeBody bei der StateList angezeigt obwohl es nicht parametriert ist.

![grafik](https://user-images.githubusercontent.com/77939385/193649012-eb14489c-6bc7-4b03-b48d-390e0a216c06.png)

![grafik](https://user-images.githubusercontent.com/77939385/193649158-ec77656e-1238-44ff-b4a5-1252b509e02c.png)

![grafik](https://user-images.githubusercontent.com/77939385/193649320-05b1a9ac-213e-4dc3-af40-99aacbf7c864.png)

**Comment by Zefau** [comment]
Du musst entweder den Body State abwählen
-oder-
aus dem Dropdown ein Element auswählen und dann via `(x)` löschen

**Comment by hosabeni** [comment]
Ich hab mir die Widgets und Geräte bei den das aufgetreten ist im JSON angeschaut. Bei denen wo der Body State angezeigt wurde stand `"bodyElement": ""` das habe in `"bodyElement": null` geändert und dann passt es. 
Keine Ahnung wo das `"bodyElement": ""` hergekommen ist.

Danke!

**Comment by Zefau** [comment]
Damit hast du die von mir beschriebene Variante 2 genommen, aber es komplizierterweise direkt im JSON geändert. ;-)

Warum nicht einfach den Body State an sich abwählen? Dass du dort welche ausgewählt hast, hat doch keine Auswirkungen?
