### ISSUE TITLE
custom icon for group light

### ISSUE THREAD

**Issue by jhartlep** [Zefau/ioBroker.jarvis#195]
Hi,
I want to use a custom icon for the group (Gewerk) "Licht".
I set it to "mdi-led-strip-variant" on the configuration page of the light.

But the custom icon is not displayed.
The aspan container has the icon "mdi-lightbulb-on".

Is this a bug? Or is this an intended feature?

**Comment by Zefau** [comment]
That's a bug. Which version are you on ?

**Comment by Zefau** [comment]
I can confirm this issue with the current beta and will fix it with the next beta.

**Comment by Zefau** [comment]
fixed with `1.1.0-beta.34`.

**Comment by jhartlep** [comment]
Great! Thanks! I am still on 1.1.0-beta.24

Can I just reinstall the current version?

**Comment by Zefau** [comment]
yes, via the "cat" in ioBroker and pasting the Github url.

**Comment by jhartlep** [comment]
Done - Confirm fix on 1.1.0-beta.34!

Thanks!
