### ISSUE TITLE
regelmäßiger Reload konfigurierbar

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1952]

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.56` gibt es nun die Option eines nächtlichen Reloads

**Comment by mcuiobroker** [comment]
Besser wäre es hier eine zeitliche Einstellung zuzulassen. z.B. jede x Minuten

Wann wird denn der jetzigen Reload durchgeführt? 00:00 Uhr?

**Comment by Zefau** [comment]
> Besser wäre es hier eine zeitliche Einstellung zuzulassen. z.B. jede x Minuten und automatisch ausschalten, wenn man in der Konfiguration ist.

Wäre besser, aber komplizierter zu implementieren und gar nicht nötig oder?

> Wann wird denn der jetzigen Reload durchgeführt? 00:00 Uhr?

3 Uhr nachts

**Comment by mcuiobroker** [comment]
Auch bitte ein ioBroker DP um den Reload (für alle Clients) ausführen zu können. Danke.

**Comment by Zefau** [comment]
ab beta ist Feature freeze, also gerne via v3.2
