### ISSUE TITLE
v3.0.13 - iCloud Calender will not shown in Caldendar Modul

### ISSUE THREAD

**Issue by Schtallone** [Zefau/ioBroker.jarvis#1954]
Here is the link to the thread and discussion in the forum for further information and also an cutout of the browser console

https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/3091?loggedin=true

Greetings

**Comment by Zefau** [comment]
Bitte schick mir mal die URL via E-Mail an iobroker.jarvis@mailbox.org. 

Die scheint laut Fehlermeldung falsch zu sein und ein `;` drin zu haben?

**Comment by Schtallone** [comment]
Hallo,

welche URL denn genau?

**Comment by Schtallone** [comment]
mit der v3.1.0-alpha.54 geht jetzt übrigens der Kalender

**Comment by mcuiobroker** [comment]
Mit welchen Einstellungen? Mit oder ohne Passwort?

**Comment by Zefau** [comment]
Aber wenn es in 3.1 passt, dann genügt das. Die geht demnächst in die beta

**Comment by Zefau** [comment]
@Schtallone schau gerne nochmal mit der beta
