### ISSUE TITLE
v3.1.0-alpha.54 Inputfeld zu klein ohne "Standardwert"

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1955]
Hej @Zefau,

ist es möglich, dass die Größe vom Inputfeld anpassbar ist?

![image](https://user-images.githubusercontent.com/85995176/194050517-d17b7af7-9032-4287-bcd6-d512eada72b6.png)
![image](https://user-images.githubusercontent.com/85995176/194050571-25408888-91d2-43d5-b99a-46953b798fc3.png)

**Comment by Zefau** [comment]
Mittels CSS sollte das problemlos gehen

**Comment by mcuiobroker** [comment]
https://app.gitbook.com/s/-Mgj8AE5HtJg1UpnK1cN/jarvis/besonderheiten-v3/styles/inputaction

**Comment by Zefau** [comment]
Ich werde es im Standard etwas breiter machen.

Bei einer Option wüsste ich nicht, was ich da anbieten könnte?

**Comment by mcuiobroker** [comment]
Vorschlag: 
Als Option Länge im vorraussichtliche Buchstaben Anzahl. Diese dann mal 10px und fürnInputAcrion width nutzen.

**Comment by Mephisto090** [comment]
> Bei einer Option wüsste ich nicht, was ich da anbieten könnte?

Oder einfach die px in den Optionen eingeben



> Vorschlag:
> Als Option Länge in vorraussichtliche Buchstaben Anzahl. Diese dann mal 10px und für InputAcrion width nutzen.

das wäre natürlich eine sehr gute Idee. Geht man vom großem W aus und schaut wieviel Platz das braucht.

**Comment by Zefau** [comment]
Das hatten wir schonmal so drin und ich hatte es rausgenommen weil das nicht klappte.

Aber wir können es nochmal versuchen. Ich weiß natürlich auch nicht mehr was genau nicht klappte.

**Comment by mcuiobroker** [comment]
Wenn nicht genug Platz zur Anzeige da ist, muss entsprechend die Länge gekürzt werden?
Eingabe nur eine Zeile? Oder kann man auch bei der Eingabe mit Umbruch der Zeile arbeiten?

**Comment by Mephisto090** [comment]
Macht es nicht Sinn eine Zeile und mehrere Zeilen zu trennen?

In der Softwareprogrammierung ist es ja entweder ein Edit/Input oder eine Textbox. Dort ist es auch getrennt.

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.60` nun mit einer größeren Mindestbreite (20px) und es passt sich dem Inhalt bis zu einer maximalen Breite (200px) an.

**Comment by mcuiobroker** [comment]
Sieht gut aus. Danke.
@Mephisto090 ?

**Comment by Mephisto090** [comment]
Ich glaube es könnte noch etwas größer sein. 8 - 10 Zeichen sollten schon Standard sein. Sonst hat es bei mir funktioniert :)
