### ISSUE TITLE
v3.1.0-alpha.54 Tabs nicht verschiebbar 

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#1956]
Hej @Zefau 

kann leider nicht mehr die Tabs verschieben :(

Alle Lieferungen soll eigentlich nach ganz vorne 

![image](https://user-images.githubusercontent.com/85995176/194055007-c1554773-ae90-4661-8159-5e44ac2282b2.png)

**Comment by mcuiobroker** [comment]
Manchmal zickt er ein wenig, teilweise muss man es erst an die 2. Stelle setzen und dann z.B. Amazon dahinter. Probier mal?

**Comment by Mephisto090** [comment]
Wie machst du ein Gif, dann kann ich sowas auch mal machen, bei bedarf?

> Manchmal zickt er ein wenig, teilweise muss man es erst an die 2. Stelle setzen und dann z.B. Amazon dahinter. Probier mal?

Kann gar kein Tab mehr bewegen :(

**Comment by mcuiobroker** [comment]
ScreenToGif -> www.screentogif.com

**Comment by mcuiobroker** [comment]
Langsam ziehen.

**Comment by Mephisto090** [comment]
auch das geht leider nicht

**Comment by Bernd9000** [comment]
Bei mir taucht das Problem dann auf sobald ich ein Tab hinzufüge und eine zweite Zeile angefangen wird.

**Comment by Zefau** [comment]
Fehler in der Browser Konsole?

**Comment by Mephisto090** [comment]
Bei mir geht es heute wieder. Komisch!

Fehler Hergang (gestern):
- Das Layout (Alle Lieferungen) ist im Vollbild
- In Widgets wurde mir das Widget so angezeigt:
![image](https://user-images.githubusercontent.com/85995176/194261418-91608b0a-63c0-4060-9f93-2cf7587df139.png)
- In der Ausgabe wurde die Tabelle auch zwei mal angezeigt. Sprich alle Pakete waren doppelt drin
- Da ich die doppelten Einträge (Zeilen) nicht rausbekommen habe, habe ich den ganzen Tab gelöscht
- Danach sah es im Widgets so aus:
![image](https://user-images.githubusercontent.com/85995176/194261935-d43e0260-934b-415d-9ae4-1daad47b197a.png)
- Jetzt habe ich im Layout den Tab neu erstellt, auf Vollbild gestellt und das Widget dem Tab zugeordnet
- Jetzt sieht es bei Widgets so aus:
![image](https://user-images.githubusercontent.com/85995176/194262184-4b99f10e-bae2-4ab1-9e03-d6c5983a885b.png)
- Somit konnte ich die Tabs nicht mehr verschieben

Heute kann ich alle Tabs wieder verschieben

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.0-alpha.55`

**Comment by Bernd9000** [comment]
v3.1.0-alpha.55
Keine Änderung, nur wenn ich die Anzahl soweit reduziere das ich nur noch eine Zeile habe, kann ich die Tabs wieder hinschieben wo ich will.

**Comment by mcuiobroker** [comment]
Also bei mir ist besser geworden und ich habe 20 TABs. Manchmal hakt es etwas beim Verschieben, dann wird nicht sofort der neue Platz für den TAB angezeigt. Man muss es dann etwas bewegen und dann wird es auch wieder angezeigt. Keine Fehlermeldungen dazu in der Browserconsole.

![image](https://user-images.githubusercontent.com/84818934/194672805-72ae4d3f-108f-40b9-9144-100b02959d99.png)

**Comment by Bernd9000** [comment]
Hab mal ein GIF erstellt
Aufgefallen ist mir das mit dem weißen Unterstrich den ein TAB erhält wenn man Ihn markiert.
Also ich markiere das erste Tab (Mausklick) dann Maustaste gedrückt halten, Maustaste nicht los lassen und Stück für Stück verschieben.Man hat dann beim verschieben einen Ghost Unterstrich (zweiter Unterstrich), dieser zeigt an ob ich diesen Tab an der aktuellern Position verschieben kann.Hier im GIF kann ich den Tab nicht an Position 5 verschieben sondern nur an das Ende.


![Animation2](https://user-images.githubusercontent.com/77005685/194699664-15cfd1d0-8e18-4cbc-993d-480ab804c028.gif)

**Comment by Zefau** [comment]
Hast du danach einen Fehler in der Browser-Konsole? Welchen Browser benutzt du?

**Comment by Zefau** [comment]
Ich konnte es mit Chrome nachvollziehen. Fehler in der Browser Konsole habe ich keinen.

**Comment by Bernd9000** [comment]
Ja, ist bei jedem Browser so, Fehler hab ich beim verschieben nicht.
Nur vorher beim erstellen der zweiten Zeile (siehe oben) taucht ein Fehler auf.
Speicherst Du den Tab Index irgendwo ? Wird dann dieser Index verwendet um die Tabs zu verschieben ?
Das würde erklären warum beim verschieben kein Fehler auftaucht.

**Comment by Zefau** [comment]
bitte nochmal mit `v3.1.0-alpha.56` prüfen

**Comment by Bernd9000** [comment]
`v3.1.0-alpha.56`
Fehler ist noch vorhanden

**Comment by Zefau** [comment]
Also bei mir tritt es (im Chrome) nicht mehr auf. Schau nochmal mit `v3.1.0-alpha.57`.

**Comment by Bernd9000** [comment]
Okay, bei mir ist der Fehler in `v3.1.0-alpha.57` weiterhin bei allen Browser vorhanden.
Nur in der `v3.0.14` läuft es bei mir.
Dann muß ich wohl hier auf die Suche gehen...

**Comment by Bernd9000** [comment]
Es sieht so aus als wenn es mit der Browser Fenster Größe zusammenhängt.
Ich hab hier die Bildschirmauflösung 1920X1080
Wenn ich das Browserfenster verkleinere kann ich die Tabs überall hinschieben.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.59`

**Comment by Bernd9000** [comment]
Nein, geht auch nicht.
Nur wenn ich die horizontale Bildschirmauflösung auf <=1600 Pixel einstelle kann ich die Tabs überall hinschieben.
Ich vermute, das die Berechnung wann die neue Tab-Zeile anfängt, bei mir falsch läuft.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.60`

**Comment by Bernd9000** [comment]
Nein. leider nicht.

**Comment by Zefau** [comment]
Dann weiß ich auch nicht. Habe eine feste Größe vergeben und die Breite auf 95% beschränkt. Vielleicht kannst du mal mit den Werten im DOM Inspektor spielen und schauen, ob du es direkt hinbekommst?

**Comment by Bernd9000** [comment]
Ich vermute mal das das event "dragover" dafür Zuständig ist mit der function(e) ?
Ich weiß leider jetzt nicht wie ich das testen könnte, ich müßte die Variablen in der function einlesen und verändern.
Ist aber auch nicht wichtig, wenn kein anderer diesen Fehler hat kann das issue hier auch dicht.


![Unbenannt](https://user-images.githubusercontent.com/77005685/197380962-80286e17-60d6-41b5-a36a-666743ec7093.jpg)

**Comment by Zefau** [comment]
Besteht das Problem mit v3.2 noch? Konnte es mit Chrome und Firefox bei mir nicht mehr reproduzieren.

**Comment by Bernd9000** [comment]
Nein, Fehler ist jetzt weg.
