### ISSUE TITLE
Chart issues

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#196]
https://forum.iobroker.net/post/503184
> Ein "-" im Geräte Namen führt dazu das ein weiterer State mit dem Namen vor dem "-" mit angelegt wird.
Ist es möglich im Chart den Geräte Namen zu entfernen oder manuell zu hinterlegen?
Der Chart gibt eine Flasche Linie wieder (siehe Bild), die Spritkosten liegen über einem Euro (z.B. Wert: 1.01)

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/503153
> Wie du siehst hat sich der Sensor vor 3 Minuten aktualisiert, aber der Chart hängt noch bei 08:35.
> Gibt es eigentlich eine Möglichkeit, dass nur die Uhrzeit im Chart angezeigt wird und nicht das komplette Datum

**Comment by Zefau** [comment]
- [ ] Additionally, show an error message to the user

**Comment by duczz** [comment]
Update: Mit der aktuellen Beta lassen sich nun zwar State's mit "-" korrekt anlegen, jedoch werden die zugewiesenen Datenpunkte nicht gespiechert

**Comment by Zefau** [comment]
@duczz Is this issue solved? Could you also verify with `v1.1.0-beta.46` ?

**Comment by duczz** [comment]
Nope is not working, after safe datapoint will be removes and test1 is generated automatically
![image](https://user-images.githubusercontent.com/25475385/97070851-d88be500-15db-11eb-914c-53671e1f1a2d.png)

**Comment by Zefau** [comment]
@duczz Is this still not working or is it solved with the latest beta `v1.1.0-beta.76` ?

**Comment by duczz** [comment]
scheint mit der aktuellen beta wieder zu klappen
