### ISSUE TITLE
Grafana iFrame bleibt leer

### ISSUE THREAD

**Issue by firechhe** [Zefau/ioBroker.jarvis#1961]
**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? v3.0.13
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

![grafik](https://user-images.githubusercontent.com/43295016/194749713-84e0fea2-e43f-457e-857e-7356c14dc725.png)

**Describe the bug / Beschreibe den Fehler**
Ich habe die Grafana Konfiguration wie [hier](https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/module/iframe-v3/grafana-einbinden#grafana-einbinden) beschrieben geändert. Allerdings nicht per SSH Zugriff - da ich mit dem Befehl nicht auf das Verzeichnis kam. Ich bin dann hingegangen und habe mir die grafana.ini in mein Docker Verzeichnis gelegt. Und in der Synology Docker App hinterlegt.

![grafik](https://user-images.githubusercontent.com/43295016/194749789-a07159d5-69d6-45d5-a965-d4a1546994d1.png)

Dann habe ich sie per Notepad angepasst. Die geänderte Werte werden auch unter http://192.168.178.xxxx:3000/admin/settings korrekt angezeigt. Dennoch kann ich keine Grafana Diagramme in Jarvis einbinden. Die Widgets bleiben einfach leer.
Ich habe schon die verschiedenen Share Links von Grafana probiert - überall das gleich Ergebnis.

Binde ich das iFrame jedoch auf einer privaten Testhomepage ein die nur lokal auf meinem PC per XAMPP läuft, funktioniert alles wunderbar.

Könnt ihr mir hier weiterhelfen?

**Comment by Zefau** [comment]
Läuft jarvis über HTTPS?

**Comment by firechhe** [comment]
Ja, ich rufe es über https://192.168.178.2:8082/xxxx auf.

**Comment by firechhe** [comment]
Ich habe es nun nochmal per Chrome versucht. Da ist die Meldung etwas umfangreicher:
![grafik](https://user-images.githubusercontent.com/43295016/194755373-731f4a86-7423-4504-a4bf-2bb9e120f505.png)

Habe in Jarvis nun "https" vor dem Share Link ergänzt. Dann blendet Firefox diese Meldung ein:
![grafik](https://user-images.githubusercontent.com/43295016/194755418-7cb5b044-bb92-499e-b0c0-2707e2da9b6d.png)

**Comment by Zefau** [comment]
Stell jarvis auf HTTP um oder grafana auf HTTPS, dann geht es.

Das ist kein jarvis Fehler sondern ein Schutz der Browser, dass unsicherer Content (HTTP) nicht den sicheren Content (HTTPS) unterläuft.

**Comment by firechhe** [comment]
Ja, ich würde Jarvis gern auf HTTP umstellen. Ich konnte jedoch noch keine Einstellung dazu finden. Ändere ich die URL im Browser ab, kommt "Fehler: Verbindung unterbrochen"

**Comment by Zefau** [comment]
Im Web Adapter kannst du HTTPS deaktivieren.

**Comment by firechhe** [comment]
Super! Vielen lieben Dank... Es funktioniert!

**Comment by firechhe** [comment]
Vom PC komme ich nun drauf. Allerdings funktioniert die Verbindung aus der ioBroker Instanzübersicht vom Smartphone aus nicht mehr.

![PNG-Bild](https://user-images.githubusercontent.com/43295016/194768270-ba939f84-b367-4a2d-b039-d89bf1260c09.png)

**Comment by Zefau** [comment]
Ruf mal die http Adresse mit Port 8400 manuell in Browser auf. Was kommt dann?

**Comment by firechhe** [comment]
Die Seite kann nicht geöffnet werden => Netzwerkverbindung wurde unterbrochen.
Es kommt auch kein Jarvis Log o.ä.

**Comment by firechhe** [comment]
Hallo. Ich habe nun noch einmal alles neugestartet. Plötzlich klappt der Zugriff von allen Geräten.
