### ISSUE TITLE
v3.1.0-alpha.54 # Neue Datenpunkte werden nicht ordnungsgemäß angezeigt

### ISSUE THREAD

**Issue by ninja-warrior** [Zefau/ioBroker.jarvis#1962]
Hallo zusammen,

ich bin am Wochenende von Jarvis v3.0.13 auf v3.1.0-alpha.54 gewechselt. Seitdem kann ich zwar noch neue Datenpunkte zu bestehenden Geräten anlegen. Allerdings werden diese im Widget nur noch mit gelbem Ausrufezeichen dargestellt. 

Hier ein Beispiel:

Ich habe für das Gerät "Steckdose Arbeitszimmer PC" einen neuen Datenpunkt "EnergyToday" angelegt. Die anderen Datenpunkte wurden vor Migration auf v3.1.0-alpha.54 bereits angelegt:

![image](https://user-images.githubusercontent.com/73721169/194842545-8d2cd8bb-0ebd-4f5b-8fdb-678570d683f2.png)

Wenn ich nun in die Visualisierung auf die Geräte-Details wechsle, bekomme ich folgenden Fehler angezeigt:

![image](https://user-images.githubusercontent.com/73721169/194841969-d36162bf-b9dd-4d32-9991-213e2bd2ebf3.png)

Ich habe dazu schon etwas weiter getestet. Wenn ich bestehende Geräte einfach nur kopiere, funktioniert alles. Wenn ich einen bestehenden Datenpunkt kopiere, zeigt sich das selbe Fehlerbild. Ich habe schon versucht verschiedene Arten von Datenpunkten neu anzulegen. Immer mit dem selben Fehlerbild. 

Sitz das Problem vor dem Bildschirm oder liegt das an Jarvis?

**Comment by Zefau** [comment]
Wenn du die Konfiguration speicherst und die Seite komplett neu lädst, geht es dann?

**Comment by mcuiobroker** [comment]
Warum sind Anzeige DP und Trigger DP unterschiedlich?

**Comment by ninja-warrior** [comment]
> Wenn du die Konfiguration speicherst und die Seite komplett neu lädst, geht es dann?

Ich hätte schwören können, dass ich die Seite schon x-mal komplett neu aufgerufen habe. Jetzt habe ich die Seite einmal im Chrome Inkognito Modus aufgerufen und siehe da: Es geht. Jetzt geht es auch überall auf einmal... 

Danke dir!

**Comment by mcuiobroker** [comment]
Komisch eventuell stand bei mir Javascript auf der Anzeige und linkdevices auf der Trigger Seite?

**Comment by ninja-warrior** [comment]
> Komisch eben stand bei mir Javascript auf der Anzeige und linkdevices auf der Trigger Seite?

Ah, okay. Du hattest noch einen veralteten Screenshot gesehen. Sorry für die Verwirrung und danke für eure Hilfe!

**Comment by ninja-warrior** [comment]
Gut, dass du es nochmal angesprochen hast. Tatsächlich muss ich jetzt bei jedem neuen Datenpunkt nach dem Speichern immer erst Shift+F5 zum Reload der Seite ausführen, damit der Datenpunkt richtig dargestellt wird. Zuvor hatte ich immer zwei Tabs nebeneinander geöffnet (ein Tab zum Editieren und ein Tab zum Anschauen). Bei Änderungen in dem einen Tab habe ich das Ergebnis gleich ohne Reload im zweiten Tab gesehen.

Ich würde den Issue deshalb nochmal aufmachen.

**Comment by Zefau** [comment]
sollte mit `v3.1.0-alpha.60` nun direkt verfügbar sein

**Comment by ninja-warrior** [comment]
Danke, funktioniert jetzt wieder. 

Mir ist zuletzt' auch aufgefallen, dass bei vereinzelten Geräten und States auch der LastChangeBody teilweise erst mit zeitlicher Verzögerung von etwa 3 Sekunden angezeigt wird. Mit `v3.1.0-alpha.60` wird LastChangeBody jetzt auch wieder "in Echtzeit" ohne Verzögerung angezeigt.
