### ISSUE TITLE
v3.1.0-alpha.54 # Geräte in StateList verschieben

### ISSUE THREAD

**Issue by ninja-warrior** [Zefau/ioBroker.jarvis#1963]
Hallo @Zefau,

irgendwie scheint sich (spätestens) bei Jarvis v3.1.0-alpha.54 ein Bug zum Verschieben von Geräten in der StateList eingeschlichen zu haben. Wenn ich ein Gerät auswähle und mit gedrückter Maustaste an eine andere Position verschiebe, verschwinden plötzlich alle Geräte in der StateList. 

![Animation](https://user-images.githubusercontent.com/73721169/194930535-8e4921a6-a2c1-49f8-ac57-838f8f698fde.gif)

**Comment by ninja-warrior** [comment]
Ich habe nach Durchforsten eines ähnlichen Bugs auf v3.1.0-alpha.55 geupdatet und die Jarvis mit Shift+F5 neu geladen.

Es zeigt sich aber immer noch ähnliches komisches Verhalten:

![Animation](https://user-images.githubusercontent.com/73721169/194931453-2adf5f31-2002-4853-a4ca-e9916ba7763b.gif)

**Comment by ninja-warrior** [comment]
Darüber hinaus können Gruppen wohl nur am Ende eingefügt und auch nicht verschoben werden. 

![Animation](https://user-images.githubusercontent.com/73721169/194932265-10d66f37-30da-4dad-b5d4-25bd834ebada.gif)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.57`

**Comment by ninja-warrior** [comment]
Sehr gut - Funktioniert wieder. Ich konnte Gruppen und Geräte verschieben. Die Einfügeposition wird jetzt auch für Gruppen berücksichtigt. Fühlt sich auch bei der Bedienung jetzt wesentlich fliesender an als zuvor. 

Vielen Dank für deinen Support!

P.S.: Bin seit Version 1 bereits großer Fan von Jarvis und verfolge die Weiterentwicklungen mit großem Interesse! Mach weiter so und vielen Dank für deinen unermüdlichen Antrieb Jarvis voranzubringen. Das schafft einen enormen Mehrwert für die gesamte ioBroker Community!
