### ISSUE TITLE
v3.1.0-alpha.55 # "Change Widget Responsive Order" funktioniert nicht

### ISSUE THREAD

**Issue by ninja-warrior** [Zefau/ioBroker.jarvis#1964]
Hallo @Zefau,

sorry für die vielen Bug-Reports, aber ich habe noch etwas entdeckt:

Das Feature "Change Widget Responsive Order" ist soweit ich mich erinnere erst in v3.1.0-alpha dazugekommen und wollte ich gleich mal testen. Leider werden Änderung bei Verschieben der Widgets mittels des Features nicht gespeichert. Einen Effekt kann ich ebenfalls nicht wahrnehmen.

![Animation](https://user-images.githubusercontent.com/73721169/194935366-c0dbd3a5-ece2-44b7-9658-6739d2ea1496.gif)

Den Effekt habe ich mir auf dem Smartphone angeschaut und keinen Unterschied festgestellt. Es wird immer noch "Administrator Überwachung" als zweites Widget angezeigt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.58`

**Comment by ninja-warrior** [comment]
Vielen Dank, jetzt passt es :)
