### ISSUE TITLE
v3.1.0-alpha.55 # Widget ScriptStatus zeigt nicht alle Skripte

### ISSUE THREAD

**Issue by ninja-warrior** [Zefau/ioBroker.jarvis#1965]
Hallo @Zefau,

ich habe mir eben einmal das neue Widget "ScriptStatus" angeschaut und festgestellt, dass das Ergebnis irgendwie nur eine seltsame Teilmenge meiner laufenden JavaScripts zeigt.

Meine Konfiguration des Widgets:

![image](https://user-images.githubusercontent.com/73721169/194937868-14308766-fc58-458c-82dd-610053deec96.png)

Eine Auswahl meiner JavaScript Skripte:

![image](https://user-images.githubusercontent.com/73721169/194937960-846aa29a-5fdd-49da-b851-3c3695ea6077.png)

Das Ergebnis in jarvis. Das Verzeichnis Common fehlt komplett:

![image](https://user-images.githubusercontent.com/73721169/194938231-43565bf4-a37e-41f5-9517-79cab6d04855.png)

**Comment by Zefau** [comment]
Was meinst du mit _seltsame Teilmenge_? Also der Ordner `common` fehlt, aber fehlt noch mehr?

**Comment by Zefau** [comment]
Hast du im Ordner `common` nur Ordner und keine Skripts?

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.58`

**Comment by ninja-warrior** [comment]
> Hast du im Ordner `common` nur Ordner und keine Skripts?

Sorry, für die ungenaue Formulierung. Auf den zweiten Blick ist mir aufgefallen, dass "nur" alle Skripte aus `common` fehlen. In dem Verzeichnis existieren nur weitere Ordner zur besseren Verwaltung der Skripte. 

Passt jetzt, vielen Dank!
