### ISSUE TITLE
HistoryGraph showing wrong values

### ISSUE THREAD

**Issue by ScumbagSteve** [Zefau/ioBroker.jarvis#1968]
Jarvis v3.1alpha57

The history graph is showing values that I do not understand. 
The graph is showing total energy creation per day vs forecast from my solar panel. Both values should therefore only be rising within the day.

Jarvis however is showing different values to ioBroker history. Not only is the total generation sometimes declining within a day, the units are also shown in "W" instead of "kWh" (as configured within the respective device).
The blue line is fine, the green line however seems bugged:
![grafik](https://user-images.githubusercontent.com/8447146/195733242-7812e6a2-50ae-4586-a047-f20ed09caa0c.png)

ioBroker history for the green lines datapoint seems to be just fine. All rising until being reset end of day.
![grafik](https://user-images.githubusercontent.com/8447146/195733460-f4b20a6f-b3ad-4cf7-aaf6-44189d25b7b9.png)

Widget setup (first line is showing the incorrect values)
![grafik](https://user-images.githubusercontent.com/8447146/195736654-eb06aadb-95fb-47ab-912f-874d17d3f00b.png)

Device setup of this datapoint:
![grafik](https://user-images.githubusercontent.com/8447146/195736744-34060f01-f53c-4f18-8520-d5555ec18f79.png)

**Comment by ScumbagSteve** [comment]
I noticed another bug in HistoryGraph that may (or may not be) connected to this.
InfluxDB is showing these values for the green line history (Schlafzimmer). Most recent value is 18,5°C:
<img width="1332" alt="image" src="https://user-images.githubusercontent.com/8447146/196131081-26ca5366-121d-4f0d-a4f6-e07da6752ae5.png">

HistoryGraph however is sometimes showing 0 for a value:
<img width="722" alt="image" src="https://user-images.githubusercontent.com/8447146/196131687-3c8669db-672a-412a-8cc3-9b59e9fef8ae.png">

It appears to me, that this happens when the last datapoint update is a long time ago. 

When I zoom in as far as I can to that last history value, I can see in the HistoryGraph popup, that there seems to be a 0 value 1 second prior (?) the actual value-update that is not shown in the ioBroker influxDB history and should normally not be there:
<img width="723" alt="image" src="https://user-images.githubusercontent.com/8447146/196131420-8d749dbe-4547-4905-9911-808be6c84618.png">
<img width="720" alt="image" src="https://user-images.githubusercontent.com/8447146/196132203-25854a89-b051-4c8b-ade4-d819765bda0c.png">

At  this point the behaviour is inconsistent. not only should the 0 value not appear, as the 18,5°C value is one second later, the graph should show 18,5°C, not 0 for the next hours. There should only be a drop to 0 for 1 second.
Interestingly this wrong 0 value seems to vanish, as soon as another history value is added. 

Widget configuration:
<img width="1272" alt="image" src="https://user-images.githubusercontent.com/8447146/196133099-a282d22d-d234-4d91-9a15-b934c6d7ba7d.png">

**Comment by Zefau** [comment]
Where exactly is the wrong unit (W instead of the defined kWh) being shown?

**Comment by Zefau** [comment]
> HistoryGraph however is sometimes showing 0 for a value:

should be fixed by the current alpha

**Comment by Zefau** [comment]
>  The blue line is fine, the green line however seems bugged:

Could you please extract the history data from ioBroker and provide it for easier debugging? Please send it to iobroker.jarvis@mailbox.org.

**Comment by Zefau** [comment]
@ScumbagSteve are you still experiencing this issue?

**Comment by ScumbagSteve** [comment]
I think it's fixed. However since a few days I see that the popup doesn't contain the timestamp anymore - only a weird number on top. However I already found a ticket for this problem.
I also noticed when I scroll to the left or right on a HistoryGraph, that the value on the popup doesn't change anymore. The popup seems to stick with a value that I had before moving my mouse and doesn't update anymore.

It's not on all HistoryGraphs and it's only for a few days, but the popup did get worse in the last time.
Still great work in general, a lot of goods improvements!

**Comment by Zefau** [comment]
please have a look at `v3.1.0-beta.28` if that fixes your remaining issues

**Comment by ScumbagSteve** [comment]
That fixed it. 
However now I experience that two HistoryGraphs don't show anything.
The other ones work fine. Anything I can debug?

![grafik](https://user-images.githubusercontent.com/8447146/202901721-40827913-fb12-49de-8f28-bf8d46ecfe74.png)

**Comment by Zefau** [comment]
Any warning in the browser console via F12?

**Comment by Zefau** [comment]
probably related to https://github.com/Zefau/ioBroker.jarvis/issues/2057#issuecomment-1321204930

**Comment by Zefau** [comment]
please have a look at `v3.1.0-beta.29`

**Comment by ScumbagSteve** [comment]
Thanks, is fixed now :)
