### ISSUE TITLE
v3.1.0-alpha.55: HistoryGraph X Achse formatter Funktion wird nicht erkannt/ ausgeführt

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#1969]
Wenn ich in der Konfiguration der X Achse unter `formatter` diese Funktion eingebe wird der Text der Funkion als Label Angezeigt und nicht das Ergebnis der Funktion.

[https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter](https://echarts.apache.org/en/option.html#xAxis.axisLabel.formatter)

![grafik](https://user-images.githubusercontent.com/77939385/195932652-4886ea3c-79f0-4844-bb92-f41e655fbc38.png)

```
(value, ts, index) => {
    var date = new Date(value - 10000);
    var month = date.getMonth() + 1;
    return month ;
}
```

![grafik](https://user-images.githubusercontent.com/77939385/195933458-cd748401-6b85-4e5b-841e-12e4df4f6818.png)

**Comment by Zefau** [comment]
Wird mit der nächsten Version behoben.

Bitte beachte, dass du bei `type: 'time'` (was im Standard ist) bei dem Rückgabewert noch `{month| ... }` nutzen musst, siehe die von dir verlinkte Dokumentation:

![image](https://user-images.githubusercontent.com/14368811/196049304-783104cd-2b33-44ab-8a6b-3348bc46a2fa.png)

Wenn du auf `type: 'value'` umstellst brauchst du das nicht, aber dann veränderst du das Chart von einem Zeit- in einen Wertbezug.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.59`

**Comment by hosabeni** [comment]
Wenn ich die Funktion so eingebe:
![grafik](https://user-images.githubusercontent.com/77939385/196511316-42520623-71ed-4772-b6dc-1c171297246e.png)

`{
  "type": "time",
  "axisLabel": {
    "formatter": "function (value) {const date = new Date(value - 10000);            return '{month|' + (date.getMonth() + 1) + '月}' }"
  }
}`


erhalte ich diesen Fehler in der Konsole:
![grafik](https://user-images.githubusercontent.com/77939385/196511874-bf62fce0-3d50-4b84-a9dd-cc44a2280266.png)

**Comment by Zefau** [comment]
Ich bezog mich nur auf das `{month| ... }`. Die Pfeil-Funktion wie du sie im ersten Post hast ist sonst korrekt.

**Comment by Zefau** [comment]
Also
```
(value, ts, index) => {
    var date = new Date(value - 10000);
    var month = date.getMonth() + 1;
    return '{month|' + month '}';
}
```

**Comment by hosabeni** [comment]
> Also
> 
> ```
> (value, ts, index) => {
>     var date = new Date(value - 10000);
>     var month = date.getMonth() + 1;
>     return '{month|' + month '}';
> }
> ```

Funktioniert leider auch nicht:
![grafik](https://user-images.githubusercontent.com/77939385/196699993-5679d86d-c7a9-469a-b608-11cbb215a164.png)

Dann erhalte ich das in der Konsole:
![grafik](https://user-images.githubusercontent.com/77939385/196700531-ddef5bb5-623d-4ddc-82af-3a4349d454ea.png)

**Comment by Zefau** [comment]
Sorry, ich habe ein `+` vergessen, siehe editierten Post oben

**Comment by hosabeni** [comment]
So passt es.
Danke!

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.17`
Allerdings für yAxis
```
"axisLabel": {
      "formatter": "function (value, index) { return value + '°C';}",
      "margin": 25,
      "showMaxLabel": true,
      "showMinLabel": true,
      "color": "rgba(255, 255, 255, 1)"
    }
```
Fehler?
![image](https://user-images.githubusercontent.com/84818934/201217870-389dca6d-538c-4e25-969d-e178782c19ed.png)

**Comment by Zefau** [comment]
Und als Pfeilfunktion? "(value, Index) => ..."?

**Comment by mcuiobroker** [comment]
Leider nein:
![image](https://user-images.githubusercontent.com/84818934/201369681-ced2d34e-2b37-434c-85c4-92a9220248cd.png)

**Comment by Zefau** [comment]
@hosabeni @mcuiobroker schaut nochmal mit `v3.1.0-beta.19`

**Comment by hosabeni** [comment]
Mit der `v3.1.0-beta.19` passt das bei mir auch mit der Y-Achse.

Eine andere Frage:

Lässt sich die Funktion wie hier beschrieben auch umsetzen?

[https://echarts.apache.org/en/option.html#xAxis.max](https://echarts.apache.org/en/option.html#xAxis.max)

Ich habe es so versucht, dann wird aber nicht mehr angezeigt:


![Image](https://user-images.githubusercontent.com/77939385/201540954-29a4e937-e378-4d21-b4df-a342717f2391.png)

`"max": "(value, ts, index) =>  {return value.max + 20000;}"`

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.19`
Es wird nicht berechnet?
![image](https://user-images.githubusercontent.com/84818934/201541786-ed153bac-f995-4270-b6d2-41f9060e16c2.png)
```
 "axisLabel": {
      "formatter": "(value, index) => { value= value-10; return value + '°C';}",
      "margin": 25,
      "showMaxLabel": true,
      "showMinLabel": true,
      "color": "rgba(255, 255, 255, 1)"
    }
```
Dürften nur 8 stehen, nicht 18 und "°C" fehlt auch?

Weiterhin fällt auf, dass die Werte in "fett" dargestellt werden. Rechts werden die Werte in normal Schrift angezeigt.
![image](https://user-images.githubusercontent.com/84818934/201541942-4ee11b01-45c8-4ccd-ae52-4cf57c5a93f1.png)

**Comment by Zefau** [comment]
> Es wird nicht berechnet?

Die Funktion funktioniert so bei mir?

Versuch mal testweise:
```
{
  "axisLabel": {
    "formatter": "(value, index) => { value= value ? value-10 : -1000; return value + '°C';}",
    "margin": 25,
    "showMaxLabel": true,
    "showMinLabel": true,
    "color": "rgba(255, 255, 255, 1)"
  }
}
```

Wenn `value` keinen Wert hat springt er auf -1000. Nur mal um zu schauen.

**Comment by mcuiobroker** [comment]
Kein Unterscheid:
![image](https://user-images.githubusercontent.com/84818934/201542277-fc56f6b3-ea01-4044-9096-09a1272654d2.png)

**Comment by mcuiobroker** [comment]
Dürfen evtl. andere Werte nicht parallel drin sein?
```
[
  {
    "position": "left",
    "name": "Bad",
    "nameLocation": "center",
    "min": "dataMin",
    "max": "dataMax",
    "axisPointer": {
      "show": true
    },
    "splitLine": {
      "show": false,
      "lineStyle": {
        "color": "rgba(193, 22, 22, 1)",
        "type": "dotted"
      }
    },
    "axisLabel": {
      "formatter": "(value, index) => { value= value ? value-10 : -1000; return value + '°C';}",
      "margin": 25,
      "showMaxLabel": true,
      "showMinLabel": true,
      "color": "rgba(255, 255, 255, 1)"
    }
  },
  {
    "position": "right",
    "name": "Büro",
    "nameLocation": "center",
    "min": "dataMin",
    "max": "dataMax",
    "axisLabel": {
      "formatter": "{value} °C",
      "margin": 25
    }
  }
]
```

**Comment by Zefau** [comment]
> Dürfen evtl. andere Werte nicht parallel drin sein?

Jo, geht scheinbar nicht mit mehreren yAchsen.

**Comment by mcuiobroker** [comment]
Scheint noch ein anderes problem zu sein?
![image](https://user-images.githubusercontent.com/84818934/201542964-bcd5ca25-4dd2-43e0-8665-06a8b1331642.png)

```
[
  {
    "position": "left",
    "name": "Bad",
    "nameLocation": "center",
    "min": "dataMin",
    "max": "dataMax",
    "axisPointer": {
      "show": true
    },
    "splitLine": {
      "show": false,
      "lineStyle": {
        "color": "rgba(193, 22, 22, 1)",
        "type": "dotted"
      }
    },
    "axisLabel": {
      "formatter": "(value, index) => { value= value ? value-10 : -1000; return value + '°C';}",
      "margin": 25,
      "showMaxLabel": true,
      "showMinLabel": true,
      "color": "rgba(255, 255, 255, 1)"
    }
  }
]
```

**Comment by Zefau** [comment]
Ohne `[ .. ]`

**Comment by mcuiobroker** [comment]
Ja.
![image](https://user-images.githubusercontent.com/84818934/201543041-3d296583-bfed-4a18-9a46-e01a481bb1b2.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.20`

**Comment by mcuiobroker** [comment]
Ja, funktioniert jetzt als Array.
Bleibt noch der Punkt, warum fett-Schrift?

**Comment by Zefau** [comment]
Meinst du links die Komma-Zahlen? Die sehen mir nicht fett aus, sondern nur weiß (statt grau, wie rechts)

**Comment by Zefau** [comment]
`"color": "rgba(255, 255, 255, 1)"` im `axisLabel`

**Comment by mcuiobroker** [comment]
Ok. Danke. Dann kann es zu.
