### ISSUE TITLE
Bug: Page white when loading it after adding weather-widget with wrong locationid

### ISSUE THREAD

**Issue by jankem2** [Zefau/ioBroker.jarvis#197]
Hi,

First of all thanks for this great vis! I was very happy with it!

Sadly I made a mistake, i was already using the vis to switch lights and i wanted to add the weather-widget. 
At one point one has to enter the locationid, i was pasting something wrong in this field.
When i am now trying to load the page, it is being shown for less than a second and than the site is complety white.
Even when I am trying to get into the edit window - when fastly clickling in the time the window is loading and showing something it doesn't work. 

I think a expection case is missing - that if the weather widget has wrong data it will not be shown.

Can you give me a hint how i can change the locationid, when i am not getting the chance to get to the settings ?

**Comment by jankem2** [comment]
![jarvis_empty](https://user-images.githubusercontent.com/72887533/96034938-94be1080-0e62-11eb-879e-ea5bd4c9119b.gif)

**Comment by Zefau** [comment]
Which version are you on?

**Comment by jankem2** [comment]
Hi together, 
version:1.1.0beta24
Until know i didnt put to much effort in the vis, so i resolved the Problem the dirty way: deleting the instance, deleting all objects, creating a new instance and then setting everything up again, with the correct location id. Now it is working great!
But still i think there should be an exception

**Comment by Zefau** [comment]
In fact this should not happen in the current beta. Please update to the latest beta and verify this.

**Comment by Zefau** [comment]
Please update to beta-34, as this was a known bug and has been resolved already.

**Comment by jankem2** [comment]
oh - thanks for your quick replies! I could't find a problem description like this one - i don't know why but actually i cannot update to this beta from the admin panel - so i won't test it right now ( might be a problem that my system is not completly up-to-date?!)
![image](https://user-images.githubusercontent.com/72887533/96039961-ca1a2c80-0e69-11eb-8c6c-362942a795f4.png)

**Comment by Zefau** [comment]
You have to update manually via the "cat" and then paste the Github url from this repository.

**Comment by Zefau** [comment]
@jankem2 did you manage to install the latest beta?

**Comment by jankem2** [comment]
I am right now installing, reporting later
