### ISSUE TITLE
Version als Systemvariable mitgeben

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1975]
:root {
	--version: " v3.1.0-alpha.59";
}

Vorteil man kann dann auch im Frontend auf dem Handy sehen, welche Version man installiert hat.
.q-space:after {
	content: var(--version);
}
![image](https://user-images.githubusercontent.com/84818934/196305805-e95f5b56-54a0-4f4b-859b-5ee858aeb47e.png)

**Comment by Zefau** [comment]
`v3.1.0-alpha.60`

**Comment by mcuiobroker** [comment]
Passt. Danke.

**Comment by mcuiobroker** [comment]
Bitte auch als ioBroker-DP unter `settings`, dann kann man sie bei Zwischensicherungen mit nutzen.

**Comment by mcuiobroker** [comment]
Kann man sich auch aus dem Adapter holen.
