### ISSUE TITLE
v3.1.0-alpha.59 smartPhone-Layout wird für normalen PC angezeigt?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1978]
Wenn ich ein smartPhone-Layout aktiviere und Speichere, wird es auch für den PC angezeigt.
![image](https://user-images.githubusercontent.com/84818934/196493432-04c1fb3a-b2bf-475c-b902-a4d7d0c4f277.png)
Auch wenn die Styles rausnehme.
![image](https://user-images.githubusercontent.com/84818934/196494485-6b3ceac0-6851-4f32-b4c5-21043186b034.png)

**Comment by Zefau** [comment]
Jo, ich hatte das Smartphone hart codiert, um in dem anderen Issue zu testen. Hab vergessen es wieder zu entfernen vor dem Release....

**Comment by Zefau** [comment]
mit `v3.1.0-alpha.60` wieder raus
