### ISSUE TITLE
v3.1.0-alpha.59 leaflet Problem

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1979]
![image](https://user-images.githubusercontent.com/84818934/196501387-476bcb2a-bf61-4011-8fad-f86836269278.png)

**Comment by Zefau** [comment]
Kann eigentlich nicht sein, da die Datei lokal ausgeliefert wird. Sie ist auch im Release drin, siehe https://github.com/Zefau/ioBroker.jarvis/tree/master/www (vorletzte Datei).

Kommt der Fehler bei jeden Ladevorgang? Hast du die Datei lokal? 
Wie lautet die URL deiner jarvis-Seite? Nutzt du einen Reverse-Proxy?

**Comment by mcuiobroker** [comment]
Kommt nicht mehr. Hatte nochmal ein `iob upload jarvis` gemacht. Schließe erstmal.
