### ISSUE TITLE
Markieren in der InputAction öffnet das zugehörige Geräte-Popup

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1980]
Kann man das verhindern, dass beim Markieren vom Inhalt in der InputAction sich das Geräte-Popup öffnet?
![jarvis-InputAction-markierenÖffnetPopup](https://user-images.githubusercontent.com/84818934/196537506-cfa7cb88-8722-454a-9485-749641ed1c75.gif)

**Comment by Zefau** [comment]
Du darfst mit dem Cursor das Textfeld nicht verlassen. Also der Cursor darf nicht zur Hand werden.

Ich würde aber mit der nächsten Version verhindern, dass beim Doppelklick das Vollbild auf geht, dann kannst du mittels Doppelklick selektieren.
