### ISSUE TITLE
v3.1.0-alpha.60 InputAction gibt falschen Type zurück

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1981]
State value to set for "0_userdata.0.jarvis.system.saveJarvisDPs.saveInstance" has to be type "string" but received type "number"
![image](https://user-images.githubusercontent.com/84818934/196680372-802567b5-eb0c-4f7a-a570-5fcfbaee1de5.png)

**Comment by Zefau** [comment]
Zahlen werden als Type number geschickt. Ich kann aber eine Option einbauen.

**Comment by Zefau** [comment]
bzw. in diesem Fall kannst du doch einfach das Objekt anpassen? Zahlen als type `number` zu schicken ist ja eigl. korrekt?

**Comment by mcuiobroker** [comment]
Richtiger wäre es den korrekten type zurückzugeben. Du hast Recht in diesem Fall, kann ich den type ändern.
Das Problem ist ja das der Admin jede Type-Änderung sofort anmeckert. Das kommt sowieso als Thema hoch.

**Comment by Zefau** [comment]
> Richtiger wäre es den korrekten type zurückzugeben. Du hast Recht in diesem Fall, kann ich den type ändern.

Das stimmt, aber ich scheue den Aufwand dies zu tun. Sowohl aus Implementierungssicht, da es nur wenig Mehrwert bietet, als auch aus Performance-Sicht (laden aller Objekte in jarvis und herstellen der notwendigen Datenstruktur).

**Comment by Zefau** [comment]
ab v3.2 eine Option um den Cast in eine Nummer zu unterbinden.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.41` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.41`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
>ab v3.2 eine Option um den Cast in eine Nummer zu unterbinden.

Wo ist da jetzt was eingebaut?

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.43` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.43`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
