### ISSUE TITLE
v3.1.0 DropDownAction Type vom Objekt zurückgeben

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1984]
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/3197
Hintergrund Boolean-Wert schalten per DropDownAction.

**Comment by mcuiobroker** [comment]
Wird als boolean geschickt.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/876926

**Comment by Zefau** [comment]
> Wird als boolean geschickt.

kannst du das auch bestätigen? Oder basiert das auf meinem Test?

**Comment by mcuiobroker** [comment]
Basiert auf Deinen Test.
