### ISSUE TITLE
v3.1.0-beta.1 Änderung im Layout werden erst nach F5 umgesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1986]
Nach Änderung im Layout werden diese nicht umgesetzt?
Kann mit dem Scripting-Problem zusammenhängen? (Kein automatischer Reload)

**Comment by Zefau** [comment]
Was hast du denn geändert? Versuch es doch nochmal ohne Skripte, damit wir das ausschließen können.

**Comment by mcuiobroker** [comment]
Ja hängt mit den Scripts zusammen, sind keine drin aktualisiert er sofort. DP im Widget hinzugefügt.

**Comment by Zefau** [comment]
ok, dann machen wir das via https://github.com/Zefau/ioBroker.jarvis/issues/1696
