### ISSUE TITLE
v3.1.0-beta.1 DP in ioBroker nur kurzzeitig gelöscht, wird nur als Fehler erkannt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1987]
Löscht man den ioBroker-DP zum Geräte-DP (jarvis) nur kurzzeitig (Auswahlgründe) wird dieser Geräte-DP in Jarvis als Fehler-DP erkannt.
![image](https://user-images.githubusercontent.com/84818934/197289351-a7252214-3289-490d-9805-b2c8c5082d44.png)
Was ja auch erstmal in Ordnung ist. ist der DP aber wieder angelegt wird dieser nicht mehr korrigiert. Denn dann wäre das Fehlersymbol wieder weg. Er bekommt als die Neuanlage vom DP nicht mit?
Erst nach F5 ist wieder alles OK.

**Comment by Zefau** [comment]
Vermutlich liefert ioBroker die Info dann nicht mehr. Kann man das mit einem Blockly testen?

**Comment by mcuiobroker** [comment]
```
let dpSaveJarvisDPs   = '0_userdata.0.jarvis.system.saveJarvisDPs';
let dpRestoreSelect   = dpSaveJarvisDPs + '.restoreSelect';
let devStates={'':'auswählen'};
if (existsState(dpRestoreSelect)){
       deleteState(dpRestoreSelect);
       setTimeout(function(){
           createStateAsync(dpRestoreSelect, {read: true, write: true, name: "Jarvis Sicherung auswählen!", type: "string", role: "", def: "", states: devStates });
       },3000);
}else{
            createStateAsync(dpRestoreSelect, {read: true, write: true, name: "Jarvis Sicherung auswählen!", type: "string", role: "", def: "" , states: devStates});
}
```

**Comment by Zefau** [comment]
Ich meinte eher, ob man die State / Objekt Update auch mit Blocky empfängt, dann Objekt löscht + neuanlegt und schaut, ob man es dort noch empfängt.

Ich bezweifle nämlich, dass das grundsätzlich in ioBroker überhaupt vorgesehen ist.

**Comment by mcuiobroker** [comment]
Das hat er in den älteren Versionen nicht gemacht.

**Comment by mcuiobroker** [comment]
Setze jetzt direkt das Objekt.
