### ISSUE TITLE
v3.1.0-beta.1 Scripting Kommentarzeichen wirkt nicht (teilweise)?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1989]
Ein Import in Standard-Kommentarzeichen wird trotzdem geladen.
/* @import url("http://192.168.178.89/download/pageSelectCircle.css");  */

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-beta.4`

**Comment by mcuiobroker** [comment]
Passt. Danke.
