### ISSUE TITLE
v3.1.0-beta.4 Änderungen von ActionElement-Optionen werden nicht direkt umgesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1990]
Icon-Änderung wurde umgesetzt.
Die Optionsänderung zum IconButtonAction erst nach F5 wirksam.
Geändert wurde Icon (aus):
![image](https://user-images.githubusercontent.com/84818934/197395485-cf27464d-3e06-4e75-b26c-16cf28f2dc33.png)

`mdi:backup-restore`

unabhängig von scripts-Inhalten

**Comment by Zefau** [comment]
Verstehe ich nicht ganz. Du schreibst `Icon-Änderung wurde umgesetzt.`, aber wenn du `Icon (aus)` änderst, dann ändert er das nicht (erst nach F5)?

Bei mir ändert er das Icon. Hast du Fehler in der Browser-Konsole?

**Comment by mcuiobroker** [comment]
Die Änderung vom normalen Icon zum State wurde geändert auch ohne F5, aber eine Änderung von dem Icon unter den IconButtonAction-Optionen (Icon (aus)) wurde nicht ohne F5 geändert.
Keinen Fehler.

**Comment by Zefau** [comment]
![IconButtonAction](https://user-images.githubusercontent.com/14368811/197414834-3bf66f7c-38e5-44a5-bca0-4fa342dde698.gif)

**Comment by Zefau** [comment]
Meinst du das? Oder sprechen wir aneinander vorbei?

**Comment by mcuiobroker** [comment]
Genau das meine ich. Ich mache es in einem Fenster. Und nutze Speichern und zurück, nicht Speichern. Muss auch mal probieren.

**Comment by Zefau** [comment]
Im Gerät funktioniert es bei mir auch. Sorry für den Aufwand, aber könntest du mir das mal giffen?

**Comment by mcuiobroker** [comment]
![jarvis-Fehler IconButtonAction-Iconändern](https://user-images.githubusercontent.com/84818934/197417968-c9b50ee8-4cab-44df-9a5f-1d0000a036eb.gif)

**Comment by Zefau** [comment]
Ok, verstehe. Im Layout greift der Fallback aus dem Gerät, weil nichts Spezifisches konfiguriert ist. Beim Updaten des Geräts aktualisiert das Layout bzw. der Fallback-Wert aber nicht.

**Comment by Zefau** [comment]
schau bitte mal mit `v3.1.0-beta.12`

**Comment by mcuiobroker** [comment]
Bei Änderungen von einigen Werte und Einstellungen (Styles, Gerätekonfig) in der Konfiguration, ist es mit `v3.1.0-beta.17` momentan so, dass nicht sofort aktualisiert wird.
Soll ich einzelne Issues aufmachen oder alles hier reinschreiben, wenn was entdecke?

**Comment by Zefau** [comment]
Schreib erstmal hier rein. Wenn es zu kompliziert wird erstell ich davon dann ein dediziertes Issue
