### ISSUE TITLE
v3.1.0-beta.1 - Slider zur Lautstärkeregelung z.B. für Sonos funktioniert nicht mehr im HomeKitTile

### ISSUE THREAD

**Issue by somansch** [Zefau/ioBroker.jarvis#1991]
Im PopUp des Devices funktioniert es noch, jedoch nicht mehr im Slider des HomeKitTiles:
![Screenshot 2022-10-23 125407](https://user-images.githubusercontent.com/47367267/197398008-24be7bd8-56b1-4945-94dd-2dbdc8d9b6fa.jpg)
![Screenshot 2022-10-23 125447](https://user-images.githubusercontent.com/47367267/197398015-57713b76-022f-4635-b797-d855e2c65438.jpg)

**Comment by Zefau** [comment]
Was funktioniert nicht? Es wird kein Wert an ioBroker geschickt?

**Comment by somansch** [comment]
Ja, genau

**Comment by Zefau** [comment]
mit `v3.1.0-beta.5` behoben

**Comment by Zefau** [comment]
@somansch
