### ISSUE TITLE
v3.1.0-beta.1 - Primärfarbe des Themes ist nicht überall gesetzt

### ISSUE THREAD

**Issue by somansch** [Zefau/ioBroker.jarvis#1992]
Die Primärbe ist bei mir "Hellblau", jedoch sieht an einigen Stellen die Standardfarbe "Dunkelblau", z.B. bei Konfiguration & Hilfe, den Überschriften bei Layout, Widget und Gerätekonfiguration:
![Screenshot 2022-10-23 130706](https://user-images.githubusercontent.com/47367267/197398258-586d679c-953f-42b1-b952-277cf718eb06.jpg)

![Screenshot 2022-10-23 130150](https://user-images.githubusercontent.com/47367267/197398235-632c7abf-241b-450c-88be-dd31cd76bea1.jpg)
![Screenshot 2022-10-23 130255](https://user-images.githubusercontent.com/47367267/197398242-ba5508f4-7ff1-471a-8683-735db24b60c9.jpg)
![Screenshot 2022-10-23 130314](https://user-images.githubusercontent.com/47367267/197398244-f84e4f80-42bd-4ed3-86b6-fdcc96037bc2.jpg)
![Screenshot 2022-10-23 130351](https://user-images.githubusercontent.com/47367267/197398248-b5cfaeb0-8c91-4114-bfa6-89808ca3cd08.jpg)

**Comment by Zefau** [comment]
mit `v3.1.0-beta.5` behoben

**Comment by Zefau** [comment]
@somansch
