### ISSUE TITLE
v3.1.0-beta.4 Löschen von ActionElement im Layout bringt Fallback nicht zurück

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1995]
Erstellt man ein Widget wird normalerweise die EInstellung vom Gerät übernommen.
Ändert man die Einstellung im Layout / Widget und löscht diese Änderung wieder, kommt das Fallback baer nicht zurück. 
Man muß dann den Geräte-DP neu holen.

![image](https://user-images.githubusercontent.com/84818934/197524418-ced340b7-6adc-4270-8371-a7561997240e.png)

oben DP mit gelöschtem ActionElement.

**Comment by Zefau** [comment]
Also das grau schraffierte `IconButtonAction` wird nicht angezeigt meinst du, richtig?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
Betrifft das nur das Action oder auch den Body? Kannst du mal das zugehörige Frontend screenshoten?

**Comment by mcuiobroker** [comment]
Body wird anscheinend standardmäßig mit LastChangeBody gesetzt, egal ob im Gerät gesetzt oder nicht.
Layout
![image](https://user-images.githubusercontent.com/84818934/197619038-49ddb278-d5c7-414a-bf17-d475d653c01f.png)
Gerät
![image](https://user-images.githubusercontent.com/84818934/197619184-50374563-8efa-41bb-99f6-fc7117cfaae0.png)

**Comment by Zefau** [comment]
> Body wird anscheinend standardmäßig mit LastChangeBody gesetzt, egal ob im Gerät gesetzt oder nicht.

Ja. Wird denn alles im Frontend angezeigt?

**Comment by mcuiobroker** [comment]
Ich habe den Fall, wo ich die Einstellung vom Layout wieder gelöscht hatte, auch schon gelöscht.
Also du möchtest jetzt den Frontend vom gelöschten Eintrag zum ActionElement?
![image](https://user-images.githubusercontent.com/84818934/197620930-af66565f-2182-445e-afc7-43450586b743.png)
Der IconButtonAction ist dann weg.

**Comment by Zefau** [comment]
Ich kann den Fehler nicht nachstellen (übliches Problem ;-) ).

Das Beispiel das du da jetzt zeigst sieht korrekt aus. TriggerElement in der Konfiguration ist leer. Der Fallback greift nicht, da leer (nichts graues schraffiert hinterlegt). Beim BodyElement sieht man, dass etwas hinterlegt ist, und das greift auch.

Sobald du etwas auswählst und löscht, greift der Fallback nicht mehr, damit die Möglichkeit besteht, es ausdrücklich leer zu machen. Den Fallback bekommt man auch nicht mehr rein, sondern muss das Element dann bewusst auswählen.
