### ISSUE TITLE
v3.1.0-beta.4 HomeKitTile Body Stil funktioniert nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1997]
```
{
"1": {"background": "no-repeat center/80% url('http://192.168.178.89/download/bilder/ffn.png')"},
"2": {"background": "no-repeat center/80% url('http://192.168.178.89/download/bilder/NDR2.png')"}
}
```
Im Popup im DP:
![image](https://user-images.githubusercontent.com/84818934/197580945-0ae783c9-853c-4c9a-b37b-8ba5798632f0.png)
Aber nicht im HomeKitTile
![image](https://user-images.githubusercontent.com/84818934/197581064-38a4c766-0b7f-4a99-bea2-08ef34e09ecf.png)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.1.0-beta.7`

**Comment by mcuiobroker** [comment]
Passt. Danke.
