### ISSUE TITLE
v3.1.0-beta.4 HomeKitTile Bild wird nicht zentriert / nur teilweise angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#1998]
Nur bei 
![image](https://user-images.githubusercontent.com/84818934/197582139-851c0247-47f3-479b-8099-26c2f3b17583.png)
ist das Bild komplett zu sehen.
![image](https://user-images.githubusercontent.com/84818934/197582215-56126240-9bda-4b5c-843b-1fe0ad224b9c.png)
In der Anzeigevariante:
`{"1":"<img src='http://192.168.178.89/download/bilder/ffn.png'>","2":"<img src='http://192.168.178.89/download/bilder/NDR2.png'"}`
![image](https://user-images.githubusercontent.com/84818934/197582424-2f8c40d9-7be2-4603-850a-d7cc8d9076bd.png)
Man bekommt das Bild auch nicht kleiner?
max-width, width, height, usw alles probiert.

![image](https://user-images.githubusercontent.com/84818934/197583342-614ad419-6b7b-4185-a552-b8aee8b4c0a2.png)
Nur, wenn man dem Bild die Auflösung mitgibt:
`{"1":"<div class='imageHome' ><img src='http://192.168.178.89/download/bilder/ffn.png'  height='150px'></div>","2":"<div class='imageHome'><img src='http://192.168.178.89/download/bilder/NDR2.png' height='150px'></div>"}`
![image](https://user-images.githubusercontent.com/84818934/197583652-3bd23465-3d3c-43c1-8495-72f343d1b6af.png)

**Comment by Zefau** [comment]
HomeKitTile ist in 9 Quadranten unterteilt. Du hast State links oben, dann ist es natürlich nicht zentriert.

**Comment by mcuiobroker** [comment]
Ich hab die anderen ausgeblendet. Das passt schon mal.

**Comment by Zefau** [comment]
Weil das Grid mit den Quadranten im Hintergrund trotzdem drin ist, um die Ausrichtung der Elemente zu gewährleisten. Also wenn du einen Wert rechts oben auswählst, soll er ja auch da stehen, daher bleibt das Grid so drin.

**Comment by mcuiobroker** [comment]
Aber die anderen Grids sind ja alle ausgeblendet, somit müsste er doch die Höhe vom Widget als maximale Höhe erkennen, oder nicht?

```
.jarvis-widget-72f87a08-b209-44ae-a864-cbc2b55c5fd8 .top .center,
.jarvis-widget-72f87a08-b209-44ae-a864-cbc2b55c5fd8 .top .right,
.jarvis-widget-72f87a08-b209-44ae-a864-cbc2b55c5fd8 .middle,
.jarvis-widget-72f87a08-b209-44ae-a864-cbc2b55c5fd8 .bottom {
	display: none;
}
```

**Comment by Zefau** [comment]
Wie groß ist denn das Bild selbst? Ist es groß genug, dass es sich den Platz nimmt?

**Comment by mcuiobroker** [comment]
Wäre groß genug:
![image](https://user-images.githubusercontent.com/84818934/197597832-cd214c9c-c441-4765-949d-1ae46e521578.png)

**Comment by mcuiobroker** [comment]
`v3.10.beta.17`
Passt.
