### ISSUE TITLE
DisplayImage mit Geräte-DP anzeigen

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#1999]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/1996

<div type='discussions-op-text'>

<sup>Originally posted by **mcuiobroker** October 24, 2022</sup>
Wenn man in dem DP einen base64 hat klappt es.
Wenn man aber in der Anzeigenvariante unterschiedliche Bilder als base64-Strings setzt klappt es nicht?
`{"1":"data:image/png;base64,....","2":"data:image/png;base64,..."}`
Sollte doch eigentlich funktionieren?</div>

**Comment by mcuiobroker** [comment]
Falls es nicht ein Feature ist, kannst du bitte prüfen, ob man es auch mit http-Adressen hinbekommen kann?

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.6`

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.7`
Es versucht das Bild von falscher Stelle zu laden.
Anzeigevariante:
`{"1":"http.//192.168.178.89/download/bilder/ffn.png","2":"http.//192.168.178.89/download/bilder/NDR2.png"}`
Download-Adresse:
` http://192.168.178.89:8082/jarvis/http.//192.168.178.89/download/bilder/ffn.png`
![image](https://user-images.githubusercontent.com/84818934/197872979-729796b1-bfa4-4166-95ba-e370e0e38b56.png)

**Comment by mcuiobroker** [comment]
Funktioniert auch mit base64 image. Danke.
