### ISSUE TITLE
v3.1.0-beta.6 Browserseite hängt sich auf.

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2000]
![image](https://user-images.githubusercontent.com/84818934/197613540-78917aac-f274-4f61-a5a8-8e2c7518998c.png)

![image](https://user-images.githubusercontent.com/84818934/197613380-3b2e6233-3d95-49d1-bb1d-facb369c83cd.png)

**Comment by mcuiobroker** [comment]
Vermute HomeKitTile hat ein Problem, kein F12 mehr möglich?

**Comment by mcuiobroker** [comment]
Nochmal installiert, keine redis Fehler mehr aber trotzdem hängt sich der Browser auf.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.7`
