### ISSUE TITLE
v3.1.0-beta.7 display:none (body stil) blendet nur Label aus.

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2004]
![image](https://user-images.githubusercontent.com/84818934/197876175-c5f57b9b-b205-48a2-9166-0c0a8b22634a.png)
Body Stil Eintrag:
```
{
  "1": {
    "color": "transparent",
    "background-image": "url('http://192.168.178.89/download/bilder/ffn.png')",
    "background-size": "contain",
    "background-position": "center",
    "background-repeat": "no-repeat"
  },
  "2": {
    "color": "transparent",
    "background-image": "url('http://192.168.178.89/download/bilder/NDR2.png')",
    "background-size": "contain",
    "background-position": "center",
    "background-repeat": "no-repeat"
  },
  "3": {
    "color": "transparent",
    "background-image": "url('http://192.168.178.89/download/bilder/pumuckl.png')",
    "background-size": "contain",
    "background-position": "center",
    "background-repeat": "no-repeat"
  },
  "default": {
    "display": "none !important"
  }
}
```
F12 Konsole:

![image](https://user-images.githubusercontent.com/84818934/197876890-74984525-1f6b-4e5a-b5bf-37c56a5f7500.png)

Ändert man den Eintrag nur auf "default":"none !important" ist die zeile ausgeblendet.

**Comment by Zefau** [comment]
Kann ich mir nicht erklären, insbesondere die Ausgabe im Log. Habe alle Ausgaben entfernt, gerade nochmal gegen geprüft. Kannst du sicherheitshalber nochmal den Adapter uploaden?

**Comment by mcuiobroker** [comment]
Auch nach Upload.
![image](https://user-images.githubusercontent.com/84818934/197882409-8398eca5-1b7c-4840-8fcc-9f4de15919e1.png)

**Comment by Zefau** [comment]
Dass das Label nicht angezeigt wird liegt am color transparent oder nicht?

**Comment by mcuiobroker** [comment]
Ja. Hab die transparente mal geändert.
![image](https://user-images.githubusercontent.com/84818934/200064089-be69e034-75bf-4327-9a3a-bee120cc85af.png)

**Comment by mcuiobroker** [comment]
background-color zum HKT im Body Stil funktioniert auch nicht.

**Comment by Zefau** [comment]
Dann passt alles?

**Comment by mcuiobroker** [comment]
Tja sieht so aus. Mit v3.1.0-beta.11 ist er weg. Danke.

**Comment by mcuiobroker** [comment]
Ich hatte es jetzt nur mit default getestet. Nee das Problem ist ja die Abhängigkeit vom Wert.

**Comment by mcuiobroker** [comment]
Zu tief in anderen Dingen drin. Mach erstmal zu.
