### ISSUE TITLE
Datenübernahme 3.1: Datenpunkt Schlüssel Problem

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2006]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/2005

<div type='discussions-op-text'>

<sup>Originally posted by **Bernd9000** October 25, 2022</sup>
@Zefau 
Bei der Umstellung von Version 3.0 auf 3.1 werden bei mir z.B.  diverse Werte im Popup nicht angezeigt und der Levelbody fehlt.
Ich hab dann im Expert Modus herausgefunden das es an der Variable "key" liegt.
Wenn ich diesen entferne wird alles wieder korrekt angezeigt.
Ich denke die Variable wird durch ein Geräteimport angelegt ?
Wird diese Variable in Version 3.1 noch benutzt ?

Beispiel:

 "temperatur": {
        "showState": true,
        "state": "0_userdata.0.Shelly.Eckgrundstück-Licht2.Temperatur",
        "action": "",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "temperatur",
        `"key": "temperature",`
        "unit": "°C"
      },</div>

**Comment by Zefau** [comment]
@Bernd9000 schau nochmal mit `v3.1.0-beta.8`

**Comment by Bernd9000** [comment]
Jetzt fehlen noch mehr Werte im Popup.
Egal ob mit Variable "key" oder ohne.
Es werden nur noch Schalter angezeigt

**Comment by Bernd9000** [comment]
Ich teste nochmal den Versionswechsel, habe nur drüber installiert...

**Comment by Bernd9000** [comment]
Okay, aktueller Stand:

Der Name vom `Datenpunkt-Schlüssel` muß identisch sein mit der Variable `key`.
Wenn das nicht der Fall ist werden bei mir keine Werte angezeigt.

**Comment by Bernd9000** [comment]
Am besten so wieder herstellen wie es in beta.7 war.
Ich hab mal alle Variablen `key` bei den Geräten unter 3.0.15 gelöscht.
Das scheint keine weiteren Auswirkungen zu haben, scheint alles zu funktionieren.
Das wäre dann die einfachste Möglichkeit.

**Comment by Bernd9000** [comment]
Was mir noch zur Datenübernahme einfällt wo einige drüber stolpern könnten:

1). Bindings in Datenpunkten
Hier muß man an das Hochkomma denken bei der Übernahme-
Ich mach das so das ich bei der Datenübernahme  `"{` durch `"'{` und `}=` durch `}'=` ersetze.

2.) iframe Widget
Hier muß ich bei jedem "alten" iframe aus der alten Version diesen öffnen und die Sandbox aktivieren und bei den Sandbox Optionen alles aktivieren sonst funktionieren Sie nicht.

**Comment by Mephisto090** [comment]
wie komme ich eigentlich wieder zu einer Version meines Vertrauens zurück?

**Comment by mcuiobroker** [comment]
Für beta stehen hier URLhttps://mcuiobroker.gitbook.io/jarvis-infos/system-jarvis-neuigkeiten

**Comment by Zefau** [comment]
schaut bitte mal mit `v3.1.0-beta.9`

**Comment by Bernd9000** [comment]
`v3.1.0-beta.9`
-Werte werden jetzt immer angezeigt, egal ob mit oder ohne `"key":` 
-Bei einem selbst angelegten Datenpunkt Schlüssel wird kein `"key":` angelegt

Wird die Variable/Unterschlüssel `"key":` denn jetzt noch benötigt ?

-iframe Widget funktionieren jetzt auch beim Versionswechsel.
-Nur die Hochkommas beim Binding muß ich noch setzen.

**Comment by Mephisto090** [comment]
**v3.1.0-beta.9**
![image](https://user-images.githubusercontent.com/85995176/199696319-e5788dd1-9097-4d66-b8a5-a365b1a0cc23.png)
![image](https://user-images.githubusercontent.com/85995176/199696478-20c1080e-abe9-4234-ad16-f13ac2ddf225.png)

Bei mir fehlt jetzt die zweite Secondary Eigenschaft

**v3.1.0-beta.6**
![image](https://user-images.githubusercontent.com/85995176/199697009-c901974a-fa06-4eef-88ec-e5b300adee0d.png)

**Comment by Bernd9000** [comment]
@Mephisto090
Stimmt, Du hast Recht, ist mir gar nicht aufgefallen.
Es wird nur ein Secundary State angezeigt.

@Zefau
Liegt hier auch am `"key":`
Füge ich `"key":` bei allen Datenpunkt Schlüssel hinzu werden alle Secundary States wieder angezeigt

**Comment by Zefau** [comment]
> Wird die Variable/Unterschlüssel "key": denn jetzt noch benötigt ?

Nein. War noch ein Überbleibsel von v2.x und ist nun komplett entfernt.

> -iframe >Widget funktionieren jetzt auch beim Versionswechsel.

Kannst du das ausführen? Was genau meinst du hier?

> -Nur die Hochkommas beim Binding muß ich noch setzen.

sollte mit `v3.1.0-beta.10` nun passen

>  Füge ich "key": bei allen Datenpunkt Schlüssel hinzu werden alle Secondary States wieder angezeigt

sollte mit `v3.1.0-beta.10` nun auch im Secondary State passen

**Comment by Bernd9000** [comment]
Ja, sieht gut aus mit `v3.1.0-beta.10`

Zu dem IFrame Problem:
In der alten jarvis Version hatte ich die sandbox Option nie eingeschaltet weil diese bei mir auch ohne diese Option funktionierten.
Gehe ich jetzt auf die neue Version funktionieren die meisten iFrames nicht. Ich hatte dann gleich an die sandbox Option gedacht und wollte hier alle Optionen einschalten. Dies ging aber nicht, die Optionen waren sichtbar aber mit Mausklick nicht aktivierbar.
Was aber funktionierte war oben links der Schalter "select All" in den Sandbox Optionen.
Das habe ich dann bei allen iFrames gemacht und Sie funktionierten wieder.


Ich habs nocht nicht getestet aber ich denke es liegt hier an den eckigen Klammern.
Die Fehlen bei der alten Version:

Alte Version    : `"sandboxOptions": "",`
Neue Version : `"sandboxOptions": [],`



Falls es doch an was anderes liegt hier noch ausführlicher:

'--------------------------------------------------------------------------------------------------
Alter Version (v3.0):

 "7561ecc6-38c3-4a3d-a842-025112962ea9": {
    "id": "7561ecc6-38c3-4a3d-a842-025112962ea9",
    "config": {
      "url": "http://192.168.0.100:88/ui3.htm?maximize=1&tab=live&group=alle",
      "sandboxOptions": "",
      "sandbox": false,
      "keepalive": false,
      "refresh": 0
    },
    "module": "iFrame",
    "title": "Kamera Alle Handy",
    "icon": "mdi-bed-queen",
    "items": [],
    "hideTitle": true,
    "revision": "0da88"
  },


'--------------------------------------------------------------------------------------------------
Nach installation der v3.1 (sandbox Optionen nicht wählbar):

 "7561ecc6-38c3-4a3d-a842-025112962ea9": {
    "id": "7561ecc6-38c3-4a3d-a842-025112962ea9",
    "config": {
      "url": "http://192.168.0.100:88/ui3.htm?maximize=1&tab=live&group=alle",
      "sandboxOptions": "",
      "sandbox": false,
      "keepalive": false,
      "refresh": 0,
      "interaction": true
    },
    "module": "iFrame",
    "title": "Kamera Alle Handy",
    "icon": "mdi-bed-queen",
    "items": [],
    "hideTitle": true,
    "revision": "3e473"
  },

'-----------------------------------------------------------------------------------
Neu angelegter iFrame in v3.1 (ohne Fehler):

 "7e7067b1-33e9-4d0d-8463-86ee3aadd5d2": {
    "id": "7e7067b1-33e9-4d0d-8463-86ee3aadd5d2",
    "config": {
      "keepalive": false,
      "interaction": true,
      "refresh": 0,
      "sandbox": true,
      "sandboxOptions": [],
      "url": "http://192.168.0.100:88/ui3.htm?maximize=1&tab=live&group=alle"
    },
    "title": "Kamera Alle Handy",
    "module": "iFrame",
    "revision": "79c37",
    "items": []
  }
