### ISSUE TITLE
StateHTML mit eigenem CSS

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2007]
> Kommt von einem StateHTML der innen eine eigene css hat.
```
htmlDP = '<!DOCTYPE HTML><html>';
htmlDP = htmlDP + '<head>';
htmlDP = htmlDP + '<title>HUE-Tabelle</title>';
htmlDP = htmlDP + '<link rel ="stylesheet" type="text/css" href="http://192.168.178.89/download/jarvis.css">';
```

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/discussions/2002#discussioncomment-3963837_

**Comment by mcuiobroker** [comment]
Sollte einstellbar sein, ob man zu lassen möchte, dass man per HTML Seiten oder TAB-Hintergründe und Ähnliches beeinflussen kann. 
Ist die Option ausgeschaltet, würde man eine Warnung erhalten, dass das bestimmte StateHTML mit Angabe der WidgetID versucht Einstellungen im Fronend anzupassen.

**Comment by Zefau** [comment]
mit `v3.1.0-beta.11` werden Styles und Scripts nicht mehr akzeptiert, wenn der Benutzer nicht Pro ist

**Comment by mcuiobroker** [comment]
Ich bin ja PRO, hilft ja nicht dabei?

**Comment by Zefau** [comment]
Für Benutzer ohne Pro werden eingebundene Styles und Scripts rausgefiltert

**Comment by mcuiobroker** [comment]
Aber funktioniert ja auch kein Klick zur Auswahl mehr. Es sollte optional (direkt im Mdule StateHTML) sein, sonst kann man die HTML ja gar nicht mehr verwenden. Für die Styles sollte es einen Hinweis geben, so dass man erkennt, warum die Styles von jarvis evtl. nicht stimmen bzw. korrekt angezeigt werden?

**Comment by Zefau** [comment]
Glaube wir reden irgendwie aneinander vorbei. Meine Intention dieses Issue war / ist, dass eingebettete Styles / Scripts rausgefiltert werden, wenn ein Benutzer kein Pro ist. Wenn ein User Pro ist, funktioniert es weiterhin.

> Sollte einstellbar sein, ob man zu lassen möchte, dass man per HTML Seiten oder TAB-Hintergründe und Ähnliches beeinflussen kann.

Ich beabsichtige keine solche Einstellung. Aus meiner Sicht steht der Aufwand der Implementierung nur wenig Nutzen gegenüber. Da muss jeder selbst drauf achten, dass wenn er Code via StateHTML einbringt, dass das sauber ist.
