### ISSUE TITLE
Nach Update auf  v3.1.0-beta.8 teilweise keine Values mehr sichtbar

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#2009]
Nach dem Update von v3.1.0-beta.6 auf v3.1.0-beta.8 sehen meine Sreens recht traurig aus:

Viele Values und teilweise auch Icons werden nicht mehr geladen. Hier ein Beispiel, in dem eigentlich viele Werte stehen:

![image](https://user-images.githubusercontent.com/22911084/198202908-4747219e-ce9a-4eac-853f-09bdfc59c435.png)

Browser (Edge) zeigt dies:

![image](https://user-images.githubusercontent.com/22911084/198203185-263188ac-7b0c-401c-8eec-a4995ee32141.png)

**Comment by Bernd9000** [comment]
Vielleicht das selbe Problem wie [#2006](https://github.com/Zefau/ioBroker.jarvis/issues/2006) ?

**Comment by Zefau** [comment]
schaut bitte mal mit `v3.1.0-beta.9`

**Comment by MarkSau** [comment]
> schaut bitte mal mit `v3.1.0-beta.9`

Passt jetzt, danke
