### ISSUE TITLE
State Explorer vs. iobroker Objektbaum

### ISSUE THREAD

**Issue by Sineos** [Zefau/ioBroker.jarvis#2010]
**Prerequisites / Voraussetzungen**
- [x ] v3.1.0-beta.8
- [x ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

Firefox Konsole:
```
downloadable font: rejected by sanitizer (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:0) source: http://192.168.178.12:8082/jarvis/woff2/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ-83be7b2f.woff2
TypeError: n is undefined
    m http://192.168.178.12:8082/jarvis/js/QTree-0dc8bc4c.js:1
    expandNode http://192.168.178.12:8082/jarvis/js/index-aa124a2b.js:1
    expandNode http://192.168.178.12:8082/jarvis/js/index-aa124a2b.js:1
    mounted http://192.168.178.12:8082/jarvis/js/index-aa124a2b.js:1
    createHook http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    callWithErrorHandling http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    callWithAsyncErrorHandling http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    __weh http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    flushPostFlushCbs http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    flushJobs http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    promise callback*queueFlush http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    queueJob http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    effect http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    triggerEffect http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:1
    triggerEffects http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:1
    triggerRefValue http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:1
    set value http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:1
    Y http://192.168.178.12:8082/jarvis/js/index-aa124a2b.js:1
    kt/<.default</<.end</s[1]< http://192.168.178.12:8082/jarvis/js/index-aa124a2b.js:1
    withModifiers http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    callWithErrorHandling http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    callWithAsyncErrorHandling http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    emit$1 http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    w http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    x http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:25
    callWithErrorHandling http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    callWithAsyncErrorHandling http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    n http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    o http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:17
    _wrapEventTarget http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:17
    instrumentDOM http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:8
    addEventListener$1 http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    patchEvent http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    patchProp http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    L http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    D http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    P http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    be http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    run http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:1
    update http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    Ee http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    U http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    Z http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    P http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    $ http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    ee http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    P http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    $ http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    ee http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    P http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    $ http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    ee http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    P http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    $ http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    ee http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    P http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    $ http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    L http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
    D http://192.168.178.12:8082/jarvis/js/index-e8eb9d18.js:4
index-e8eb9d18.js:8:223
```

**Describe the bug / Beschreibe den Fehler**
Der State Explorer zeigt nicht die vorhandenen Objekte aus dem Objektbaum von iobroker

**Screenshots**
Iobroker Objekte:
![image](https://user-images.githubusercontent.com/4459312/198261348-2579a0a9-cc0b-4468-a18c-ad4feca7a1b8.png)

Jarvis State Explorer:
![image](https://user-images.githubusercontent.com/4459312/198261493-a3d29294-0a39-43a5-b14b-b0a8154344e0.png)

**Comment by Zefau** [comment]
Der Channel / Folder ist die State angelegt und wird so auch durch Jarvis dargestellt.

**Comment by Sineos** [comment]
> Der Channel / Folder ist die State angelegt und wird so auch durch Jarvis dargestellt.

Sorry, wenn ich auf dem Schlauch stehe, aber die Aussage verstehe ich nicht.

`mqtt.0.zigbee2mqtt.DimmerKitchenEG` --> Alle DPs haben den Typ State

Jarvis:
![image](https://user-images.githubusercontent.com/4459312/198870710-177b52ff-1d5e-4792-87c0-f4f0400eaa16.png)

Iobroker:
![image](https://user-images.githubusercontent.com/4459312/198870760-27778f1b-51e1-44a8-893b-8aa4cd9507b6.png)


Bei ein par passt es ja:

`mqtt.0.zigbee2mqtt.BlindsJona` --> An sich das Gleiche wie oben, nur hier passt es 

Jarvis:
![image](https://user-images.githubusercontent.com/4459312/198870907-78425e8f-2764-460d-9fdf-c88ca141a2d0.png)

Iobroker:
![image](https://user-images.githubusercontent.com/4459312/198870931-365ca189-7f26-4a6f-9647-219501f41209.png)

**Comment by Zefau** [comment]
Du hast einen Ordner `DimmerKtichenEG`, der aber als `state` angelegt ist in ioBroker. Das ist falsch. Wenn es ein Ordner ist, dann muss es als `channel` oder `folder` angelegt sein, damit er korrekt im StateExplorer angezeigt wird. Dass das im ioBroker geht ist falsch und der eigentliche Fehler, auch wenn es kulant ist.

**Comment by Zefau** [comment]
https://github.com/ioBroker/ioBroker.admin/issues/1772

**Comment by Sineos** [comment]
Ah, jetzt ist der Groschen gefallen. Danke für die Erklärung. Seltsam eigentlich, die hat Iobroker alle selber angelegt. Ich werde mal den kompletten Baum löschen.

**Comment by Zefau** [comment]
Kannst du machen, aber ich glaube, dass der zigbee2mqtt Adapter hier falsch arbeitet

**Comment by Sineos** [comment]
> Kannst du machen, aber ich glaube, dass der zigbee2mqtt Adapter hier falsch arbeitet

Der Iobroker Baum ist vom reinen MQTT Adapter. Ich hab jetzt tatsächlich auf den zigbee2mqtt iobroker Adapter (https://github.com/o0shojo0o/ioBroker.zigbee2mqtt) umgestellt und damit klappt das problemlos. Schade nur, dass er beim Device Import diesen Adapter scheinbar nicht kennt.

**Comment by mcuiobroker** [comment]
Es gibt ein Programm dafür.
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/system-effektprog./v3-systemprogramme/adddevice
Wenn es aber nur wenige DPs sind sollte man manuell hinzufügen.

**Comment by Sineos** [comment]
Manuell klappt gut. Die meisten Geräte brauchen eh nur einen oder max 3 DPs. Aber Faulheit rules 😉

**Comment by Zefau** [comment]
@Sineos kannst du mir mal ein Gerät aus `zigbee2mqtt` exportieren, damit ich es bei mir importieren und testen kann?
Erstellt der zigbee2mqtt Adapter die Datenpunkte unter `mqtt.0.` oder `zigbee2mqtt.0.`?

![image](https://user-images.githubusercontent.com/14368811/199841151-d4d3f36f-93e1-4a01-9d3a-78b41f074ef0.png)

**Comment by Sineos** [comment]
Der zigbee2mqtt Adapter zeigt das "problematische" Verhalten mit den Foldern nicht. Der reine mqtt Adapter leider schon (Subscribe auf `zigbee2mqtt/#`). Auch nach löschen des Trees und dem folgenden Neuaufbau hat sich das nicht gebessert.

In der angehängten Zip sind die Bäume beider Adapter. Vielen Dank für den unermüdlichen Einsatz!

[json.zip](https://github.com/Zefau/ioBroker.jarvis/files/9933571/json.zip)

**Comment by Zefau** [comment]
@Sineos habe es runtergeladen, bitte wieder aus deinem Post löschen

**Comment by Zefau** [comment]
sehe ich das richtig, dass `zigbee2mqtt` nicht selbst einen Baum unter `zigbee2mqtt.0` anlegt, sondern unter `mqtt.0.zigbee2mqtt.`? Außerdem scheinen die Knoten direkt unter `mqtt.0.zigbee2mqtt.` ohne Typ (weder `channel` noch `folder`) angelegt zu sein (was sich auch mit deinem Screenshot deckt).

Leider kann ich das nicht in den Importer integrieren :-(
Da muss der Adapter-Entwickler von zigbee2mqtt mit einer ordentlichen Baum-Struktur arbeiten.

**Comment by Zefau** [comment]
Nachtrag: Ich sehe gerade, dass es gar keinen zigbee2mqtt Adapter gibt? Wie ist denn das realisiert?

**Comment by Sineos** [comment]
Ich glaube wir reden aneinander vorbei:

* Basis ist https://github.com/Koenkk/zigbee2mqtt. Hiermit werden alle zigbee Geräte über mqtt steuerbar gemacht
* In Iobroker gibt es momentan 3 Möglichkeiten damit umzugehen
   1. https://github.com/ioBroker/ioBroker.zigbee --> Basiert auf zigbee2mqtt ist aber eine native Iobroker Lösung. Hier nicht Gegenstand der Diskussion
   2. https://github.com/ioBroker/ioBroker.mqtt/ --> Der "Standard" mqtt client / broker vom iobroker Projekt. Legt seine DPs als `mqtt.0.zigbee2mqtt.xxx` an und es scheint dabei irgendwas krumm: https://github.com/ioBroker/ioBroker.admin/issues/1772. Momentan also nicht kompatibel zum State Explorer
   3. https://github.com/o0shojo0o/ioBroker.zigbee2mqtt --> Verbindet sich über Websocket zur zigbee2mqtt Instanz und legt darüber die Datenpunkte an. Ligen dann in der Form `zigbee2mqtt.0.xxx`. Funktioniert wunderbar mit dem State Explorer
* Für Variante ii. und iii. habe ich den Iobroker Baum exportiert und oben angehängt

**Comment by Zefau** [comment]
> Für Variante ii. und iii. habe ich den Iobroker Baum exportiert und oben angehängt

Du hast (2x) deinen gesamten ioBroker Baum exportiert, ohne Filter / Selektion.

> https://github.com/o0shojo0o/ioBroker.zigbee2mqtt --> Verbindet sich über Websocket zur zigbee2mqtt Instanz und legt darüber die Datenpunkte an. Ligen dann in der Form zigbee2mqtt.0.xxx. Funktioniert wunderbar mit dem State Explorer

Das meinte ich und habe es nicht gefunden. Danke für den Link. Ich schaue nochmal.

**Comment by Sineos** [comment]
> Du hast (2x) deinen gesamten ioBroker Baum exportiert, ohne Filter / Selektion.

😵‍💫 Ups, so war das natürlich nicht gedacht. Sorry und vielen Dank fürs Dranbleiben 👍
