### ISSUE TITLE
v3.1.0-beta.8: Modul DateTime Uhrzeit falsch

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2011]
`v3.1.0-beta.8`
Uhrzeit mit `Sekunden` Anzeige bleibt auf dem Stand beim verlassen des Tab stehen.
Geht man auf diesem Tab mit der Uhrzeit zurück, läuft die Zeit weiter (Nachlauf).
Nur wenn die volle Minutenzahl erreicht wird oder mit F5 die Seite aktualisiert wird ist die Uhrzeit korrekt.

![Unbenannt](https://user-images.githubusercontent.com/77005685/198873986-8a9ece92-97a1-49f8-9232-f471ed76303a.jpg)

**Comment by Zefau** [comment]
schau bitte mal mit `v3.1.0-beta.12`

**Comment by Bernd9000** [comment]
`v3.1.0-beta.12`
Der grobe Fehler ist weg.
Nur noch ein kleiner Nachlauf von 1-2 Sekunden bei Seiten die längere Ladezeiten haben.
Das wird dann aber nach einer halben oder vollen Minute korrigiert.
