### ISSUE TITLE
v3.1.0-beta.8 Icons und SecondaryStates fehlen

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2016]
![image](https://user-images.githubusercontent.com/85995176/198967120-0def1cbd-2995-4efe-8ce1-0679c4f199e4.png)
![image](https://user-images.githubusercontent.com/85995176/198967407-0cbb4cea-ab11-4090-b47b-acef062b259c.png)
![image](https://user-images.githubusercontent.com/85995176/198967464-0b2447a0-60bf-4bb4-acb0-de39028f5bc5.png)
![image](https://user-images.githubusercontent.com/85995176/198967575-1964112f-5453-4b1f-9e99-5a6928a5b14c.png)
![image](https://user-images.githubusercontent.com/85995176/198967680-b0394cb0-aa37-458c-8261-974ca3e88a84.png)
![image](https://user-images.githubusercontent.com/85995176/198967874-303cff86-23b3-49db-85af-18ba782bfa79.png)
![image](https://user-images.githubusercontent.com/85995176/198968009-618be280-157a-4706-8b86-39b6de3ca4c0.png)

**Comment by Mephisto090** [comment]
unter der Schaltungsliste steht sowas wie Batterie und Erreichbarkeit

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/198993187-80cdfbb8-d290-4c0f-8fa3-007ab551b708.png)

Jarvis hat bei mir komplett die Hufe hochgerissen :(

**Comment by Mephisto090** [comment]
So wie es aussieht zeigt er überall den SecondaryState an als MainState

**Comment by Bernd9000** [comment]
Eventuell das selbe Problem wie [#2006](https://github.com/Zefau/ioBroker.jarvis/issues/2006)

**Comment by Zefau** [comment]
schaut bitte mal mit `v3.1.0-beta.9`

**Comment by Mephisto090** [comment]
Siehe https://github.com/Zefau/ioBroker.jarvis/issues/2006.

Ich habe wohl das gleiche Problem. ich denke es reicht, wenn wir das alles in https://github.com/Zefau/ioBroker.jarvis/issues/2006 zusammenfassen. @Zefau wenn du willst kannst du das hier schließen. :9
