### ISSUE TITLE
v3.1.0-beta.7 Theme-Einstellungen ziehen nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2019]
![image](https://user-images.githubusercontent.com/84818934/199564304-59f43719-cbf3-49ee-81b1-06f1ed813a78.png)

Es greifen nur noch feststehende Werte für die responsive Änderung vom Layout.
3-spaltig ab 1024px,
2-spalitg ab 600px

**Comment by Zefau** [comment]
sollte mit `v3.1.0-beta.10` nun passen

**Comment by mcuiobroker** [comment]
Passt. Danke.
