### ISSUE TITLE
display issue - current value of the LevelBody is overlapping

### ISSUE THREAD

**Issue by ottk3** [Zefau/ioBroker.jarvis#202]
The current value on the right side of the LevelBody in a Widget StateList is overlapping.

![image](https://user-images.githubusercontent.com/5236802/96192292-058a2900-0f46-11eb-9dea-3e9ff6c6f4a9.png)

Kind regards,
Sven

**Comment by Zefau** [comment]
Thanks for reporting. This is done with https://github.com/Zefau/ioBroker.jarvis/issues/106 (even though it is titled "on small devices")

**Comment by ottk3** [comment]
Oh, my bad! I missed that, sorry. Duplicate of #106
