### ISSUE TITLE
v3.1.0-beta.7 HomeKitTile Icon alle gleich

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2020]
Egal ob man Icon (State) oder Icon (device) auswählt es kommt immer das Device Icon.
![image](https://user-images.githubusercontent.com/84818934/199575817-7e4b44d0-259a-437f-a2f5-e01bbc89feda.png)
![image](https://user-images.githubusercontent.com/84818934/199576911-23456ff5-c6fd-4fc4-a4a2-3c7a427e436e.png)
Besonderer Fall insofern es sind mehrere DP mit gleichen Einstellungen, nur Icons und Datenpunkt-Eigenschaften sind anders:
![image](https://user-images.githubusercontent.com/84818934/199577091-cf87feb2-b366-4c0e-b25b-43e003e234c5.png)
![image](https://user-images.githubusercontent.com/84818934/199577328-56a85e0a-6462-4e99-aadb-80d8f1f3be51.png)

Icon wurden nicht gespeichert?

**Comment by Zefau** [comment]
Hat sich geklärt? War kein Icon im State definiert?

**Comment by mcuiobroker** [comment]
Genau. Ich dachte es war gespeichert, war aber wohl nicht, Zu viele Dinge gleichzeitig gemacht.
