### ISSUE TITLE
v3.1.0-beta.9 Jarvis kann nicht mehr verwendet werden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2022]
Auch ein Zurückspielen der v3.1.0-beta.7 hat nicht geholfen.
Extrem langsam alles. Kryptomining?
Auslastung von 60%?
Ram 4GB?
![jarvis-v310-beta9](https://user-images.githubusercontent.com/84818934/199606534-863522fc-6a00-4c53-a12c-88e2e3149d8e.gif)
Hinweis?
![image](https://user-images.githubusercontent.com/84818934/199766045-40cd56be-0150-4b77-b2dc-a84a63dd07d0.png)
iFrames mit Wetter-Inhalten gelöscht. Anscheinend betreibt dort einer Krytomining.
Auslastung wieder normal.

**Comment by Zefau** [comment]
Was war los?

**Comment by mcuiobroker** [comment]
Im Nachhinein scheint es an einem Fehler oder Hack von RPI oder vom System gelegen zu haben. Nach Updates vom System und Neustart und Rücksicherung von jarvis-DPs (wie vorher), läuft alles normal.

**Comment by mcuiobroker** [comment]
Habe die Vermutung, dass es mit einem Eintrag im Body Stil vom Tab zusammenhängt?
`{"'{0_userdata.0.jarvis.test.forumTestDP5}'='bad'":{"display":"none !important"}}`
Immer wenn ich den Eintrag drin habe, ist das System extrem langsam und haut sich den Speicher voll, echt komisch?
Kann doch eigentlich nicht sein, oder?

**Comment by Zefau** [comment]
schau mal bitte mit `v3.1.0-beta.21`

**Comment by mcuiobroker** [comment]
Lösung: Speicherungsfehler für die Parameter #2040
