### ISSUE TITLE
v3.1.0-beta.10 Unterschiedliche Anzeige auf unterschiedlichen Geräten (PC, Handy)

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2024]
Binding im Gerät (Anzeigevariante):

`{"true":"{0_userdata.0.forum.activeNum}"}`
oder
`{"true":"'{0_userdata.0.forum.activeNum}'"}` -> kein Unterschied

![image](https://user-images.githubusercontent.com/84818934/199852648-362e7c1b-6b42-458b-9301-a7a990fd15d9.png)

![image](https://user-images.githubusercontent.com/84818934/199852778-d9f85e3b-0cc0-4180-87d2-34f9bc132ad2.png)

- [ ] Wert ist ein String, sollte aber ohne Anführungsstriche angezeigt werden.

ioBroker-DP:
![image](https://user-images.githubusercontent.com/84818934/199852874-c53fe5c3-621a-4efd-aed0-536de0ac52a8.png)

**Comment by Zefau** [comment]
schau bitte mal mit `v3.1.0-beta.12`

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.17`
Passt.Danke.
