### ISSUE TITLE
v3.1.0-beta.11 bei F2 kommt teilweise diese Info und wird nicht ausgeführt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2025]
![image](https://user-images.githubusercontent.com/84818934/199855610-1002b412-2b39-4a2b-9e39-90e224224e47.png)

**Comment by Zefau** [comment]
beobachte das mal bitte mit `v3.1.0-beta.12`

**Comment by mcuiobroker** [comment]
`v3.1.0.-beta.17`
Meldungen kommen nicht mehr. Mache erstmal zu. Danke.
