### ISSUE TITLE
v3.1.0-beta.11 Styles werden nicht gespeichert

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#2028]
Styles werden nicht gespeichert. Keine Reaktion beim drücken der Buttons.

https://forum.iobroker.net/topic/59201/jarvis-v3-1-0-beta-just-another-remarkable-vis/2?_=1667647812692

Plattform: Windows
RAM: 16 GB 
NODE.JS: V16.18.0
NPM: 8.19.2
JS Controller: 4.0.23
Admin: 6.2.23
WS: 2.1.3
WEB: 5.2.10

**Comment by Zefau** [comment]
Keine Reaktion beim Speichern, aber keinen Fehler in der Browser Konsole? Ist ja merkwürdig.

Wird etwas in jarvis.0.css geschrieben?

**Comment by sigi2345** [comment]
> Keine Reaktion beim Speichern, aber keinen Fehler in der Browser Konsole? Ist ja merkwürdig.
> 
> Wird etwas in jarvis.0.css geschrieben?

Nein, es stehen nur die alten Daten drinnen.

**Comment by Zefau** [comment]
Bin ich etwas ratlos. Erscheint denn ein `CSS Validation Errors`?

![image](https://user-images.githubusercontent.com/14368811/200188284-0e8c5f91-dd56-44fb-bfe4-42260aaccc85.png)

**Comment by Zefau** [comment]
Kannst du mir mal das CSS zur Verfügung stellen, welches du versuchst zu speichern?

**Comment by sigi2345** [comment]
> Bin ich etwas ratlos. Erscheint denn ein `CSS Validation Errors`?
> 
> ![image](https://user-images.githubusercontent.com/14368811/200188284-0e8c5f91-dd56-44fb-bfe4-42260aaccc85.png)

Nein

**Comment by sigi2345** [comment]
> Kannst du mir mal das CSS zur Verfügung stellen, welches du versuchst zu speichern?

}
.jarvis-widgets-b16b3379-4803-4e67-84b0-5ee86c2e54e3 .q-table__bottom {
  display: none !important;
}

**Comment by Zefau** [comment]
Ist
```
}
.jarvis-widgets-b16b3379-4803-4e67-84b0-5ee86c2e54e3 .q-table__bottom {
display: none !important;
}
```

der ganze Code? Sieht unvollständig aus bzw. ist sonst falsch wegen dem führenden `}`.

**Comment by sigi2345** [comment]
> Ist
> 
> ```
> }
> .jarvis-widgets-b16b3379-4803-4e67-84b0-5ee86c2e54e3 .q-table__bottom {
> display: none !important;
> }
> ```
> 
> der ganze Code? Sieht unvollständig aus bzw. ist sonst falsch wegen dem führenden `}`.

Habe es von hier kopiert:

https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/styles/.jarvis-module-jsontable#zeilen-pro-seite-info-ausblenden

**Comment by mcuiobroker** [comment]
Und dort steht:
```
.jarvis-widgets-4a67ff2e-18ca-4d4c-9668-1655d14f7fc6 .q-table__bottom {
  display: none !important;
}
```

**Comment by sigi2345** [comment]
> Und dort steht:
> 
> ```
> .jarvis-widgets-4a67ff2e-18ca-4d4c-9668-1655d14f7fc6 .q-table__bottom {
>   display: none !important;
> }
> ```

Wird jetzt gespeichert aber keine Auswirkung.

**Comment by sigi2345** [comment]
> > Und dort steht:
> > ```
> > .jarvis-widgets-4a67ff2e-18ca-4d4c-9668-1655d14f7fc6 .q-table__bottom {
> >   display: none !important;
> > }
> > ```
> 
> Wird jetzt gespeichert aber keine Auswirkung.

![Screenshot (5119)](https://user-images.githubusercontent.com/41079106/200194425-b4cf7870-aef1-4bdf-9374-bb21b1b1ee9d.png)

**Comment by mcuiobroker** [comment]
Sorry falsch in der Doku: .jarvis-widget-....

**Comment by Zefau** [comment]
Du musst die ID anpassen, also `.jarvis-widgets-<ID> .q-table__bottom {`, wobei `<ID>` für die Widget ID steht, die du anpassen willst.

Da es nun aber gespeichert wird, schließe ich das Issue. Den Rest gerne via ioBroker Forum.
