### ISSUE TITLE
Alias has no target

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#2029]
Kann man die Meldung im Log abstellen wenn man im Alias kein zweites Target hinterlegt hat? Oder eine Blacklist Funktion mit einbauen?
![image](https://user-images.githubusercontent.com/25475385/200164771-d5358195-b46a-4202-a6fb-cbe841d77dc7.png)

**Comment by Zefau** [comment]
Wann kommen die Warnungen? Beim Adapter-Start, in einem regelmäßigen Intervall oder beim Aufruf der jarvis Seite?

**Comment by duczz** [comment]
Bei jedem Jarvis Seitenaufruf

**Comment by Zefau** [comment]
Kannst du mal jarvis auf debug stellen und schauen, was nach der Warnung noch für Debugging-Informationen im Log stehen?

**Comment by Zefau** [comment]
@Apollon77 mir erscheint, als wenn der Fehler direkt aus dem js-controller kommt? Kann ich den als Entwickler unterdrücken?

https://github.com/ioBroker/ioBroker.js-controller/blob/e95e5f3ede81fc5e53fba5a2585b2147a8a6556f/packages/adapter/src/lib/adapter/adapter.ts#L7443


https://github.com/ioBroker/ioBroker.js-controller/blob/e95e5f3ede81fc5e53fba5a2585b2147a8a6556f/packages/adapter/src/lib/adapter/adapter.ts#L7808


https://github.com/ioBroker/ioBroker.js-controller/blob/e95e5f3ede81fc5e53fba5a2585b2147a8a6556f/packages/adapter/src/lib/adapter/adapter.ts#L8194

**Comment by Apollon77** [comment]
Es gibt dazu auch ein js.controller issue und es hat nichts mit jarvis zu tun. Wenn es passiert einfach Adapter neu starte und es sollte weg sein.

Naja ... wenn  wir wüssten warum er passiert dann wäre der Fehler nicht mehr da ... Das er irgendwo her dort kommt wissen wir, aber warum und unter welchem Umständen nicht. Es gab auch noch keinen User der uns irgendwie eine Reproduktionsinfo geben konnte.
Es müssen irgendwelche Race conditions sein.

Wir werden den Code mit js-controller 4.1/5 optimieren und vereinfachen und hofen dem Thema so auf die Spur zu kommen bzw es zu vermeiden.

**Comment by Zefau** [comment]
ok, danke dir, dann schließe ich hier.
