### ISSUE TITLE
Chart is displaying primary and secondary datapoint at the same time

### ISSUE THREAD

**Issue by cryptedx** [Zefau/ioBroker.jarvis#203]
Hi,

I am displaying room e and the % value of it's heating actuator. For the first chart I am using the e and for the 2nd the actuator percentage. Both data points are in one device. Frist is  and 2nd %. I have temperature data points corresponding to the value what I need in chart at primary data point. 

**Problem:**
Both charts are showing e and %. Am I doing something wrong or is it a bug?

BTW this vis is so amazing!!! Keep up the good work!

![image](https://user-images.githubusercontent.com/20707078/96291969-28b9e480-0fe9-11eb-9cb6-98a07c603ec7.png)

![image](https://user-images.githubusercontent.com/20707078/96291949-2061a980-0fe9-11eb-9661-fa3ad753aad2.png)

![image](https://user-images.githubusercontent.com/20707078/96291926-18096e80-0fe9-11eb-9f33-b8956352f9b2.png)

![image](https://user-images.githubusercontent.com/20707078/96291885-0aec7f80-0fe9-11eb-8a5e-2598f94e4ecd.png)

**Comment by Zefau** [comment]
Thanks for the detailed bug report. What version are you on?

**Comment by cryptedx** [comment]
Oh sorry, how could I forget that. I am on v1.1.0-beta.24

**Comment by Zefau** [comment]
@cryptedx this should be solved with `v1.1.0-beta.46`, can you confirm?

**Comment by cryptedx** [comment]
Installierte Version:1.1.0-beta.47

**Problem solved!**

![image](https://user-images.githubusercontent.com/20707078/97079660-2c0b2c80-15f6-11eb-858a-72190b6b1c65.png)

Besten Dank!
