### ISSUE TITLE
2 Werte übergeben bei Trigger action

### ISSUE THREAD

**Issue by X-Renegade-X** [Zefau/ioBroker.jarvis#2030]
Hi,
gibt es bei Jarvis eine Möglichkeit Bei einem Switch Button den Trigger zu setzen und gleichzeitig einen Wert(String) in einen anderen Datenpunkt zu schreiben?

mfG

**Comment by Zefau** [comment]
Bitte für https://github.com/Zefau/ioBroker.jarvis/issues/695 voten
