### ISSUE TITLE
v3.1.0-beta.11: HomeKitTile - Aktion "Öffne Seite / Registerkarte" - keine Auswahl der Registerkarte mehr möglich

### ISSUE THREAD

**Issue by somansch** [Zefau/ioBroker.jarvis#2032]
Keine Auswahl der Registerkarte mehr möglich. Nur die Seite kann ausgewählt werden, jedoch funktioniert der Link dahinter auch nicht:
![image](https://user-images.githubusercontent.com/47367267/200183273-0629b618-b120-449c-a2fe-d2a005e8b10f.png)

**Comment by Zefau** [comment]
schau bitte mal mit `v3.1.0-beta.12`

**Comment by somansch** [comment]
Funktioniert wieder in "v3.1.0-beta.12"

Danke
