### ISSUE TITLE
Import / adapt devices and layout from ioBroker.zigbee2mqtt

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2033]
> Für Variante ii. und iii. habe ich den Iobroker Baum exportiert und oben angehängt

Du hast (2x) deinen gesamten ioBroker Baum exportiert, ohne Filter / Selektion.

> https://github.com/o0shojo0o/ioBroker.zigbee2mqtt --> Verbindet sich über Websocket zur zigbee2mqtt Instanz und legt darüber die Datenpunkte an. Ligen dann in der Form zigbee2mqtt.0.xxx. Funktioniert wunderbar mit dem State Explorer

Das meinte ich und habe es nicht gefunden. Danke für den Link. Ich schaue nochmal.

_Originally posted by @Zefau in https://github.com/Zefau/ioBroker.jarvis/issues/2010#issuecomment-1304888304_

**Comment by Zefau** [comment]
@Sineos schau bitte mal mit `v3.1.0-beta.12`

**Comment by Sineos** [comment]
Klappt soweit wunderbar. Vielen Dank! 

Zwei Kleinigkeiten, die mir aufgefallen sind:

![grafik](https://user-images.githubusercontent.com/4459312/200196570-955e96c9-e813-4450-9bd1-f9f5f1273a41.png)
Falls ein Gerät keinen Namen hat, dann Fallback auf ID?

![grafik](https://user-images.githubusercontent.com/4459312/200196630-53774ab2-407f-4079-a88b-f6c6963db620.png)
Wäre das nicht `ct`?

**Comment by Zefau** [comment]
ID als Fallback ist eine gute Idee.

CT heißt doch color temperature. Da der Datenpunkt colortemp heißt wird das so übernommen. Oder was meinst du?

**Comment by Sineos** [comment]
> CT heißt doch color temperature. Da der Datenpunkt colortemp heißt wird das so übernommen. Oder was meinst du?

Vielleicht ein Missverständnis von mir. Ich dachte Jarvis versucht seine internen Geräte States zu harmonisieren. Wie zum Beispiel wenn ich manuell ein Licht-Gerät anlege und mir die Standard-States dazu anlegen lasse. Zu diesen States passen dann auch die jeweiligen Body / Action Elemente.
Ich dachte also, dass Jarvis hier `colortemp` auf `ct` mappen würde.

**Comment by Zefau** [comment]
Ach das meinst du. Ja, das ist so. `colortemp` fehlt hier aber in der Auflistung bzw. dem Mapping. Nehme ich aber noch mit auf dann.

**Comment by Zefau** [comment]
@Sineos schau mal bitte mit `v3.1.0-beta.13`

**Comment by Sineos** [comment]
Also mit Beta 17 hat sich aus meiner Wahrnehmung nichts geändert:
* `colortemp` wird nicht auf `ct` gemappt
* Namenlose Geräte haben keinen Fallback auf die ID

**Comment by Zefau** [comment]
für
>  Namenlose Geräte haben keinen Fallback auf die ID 

ist ein erneuter Import notwendig.

> colortemp wird nicht auf ct gemappt

Wie ist denn hier deine Erwartungshaltung?

Der default definiert `LevelBody` als BodyElement mit den Eigenschaften:
```
	"properties": {
		"min": 2000,
		"max": 6500
	},
	
	"icon": {
		"default": "thermometer"
	},
	"unit": " °K"
```

**Comment by Sineos** [comment]
> ist ein erneuter Import notwendig.

* Browser Cache gelöscht
* Web Adapter neu gestartet
* Jarvis neu gestartet

![Animation](https://user-images.githubusercontent.com/4459312/201205572-06d76595-5dc6-47ec-9640-af02eb78f072.gif)


> Wie ist denn hier deine Erwartungshaltung?

![image](https://user-images.githubusercontent.com/4459312/201206845-910cb636-de80-44e5-a956-43e70ed6e36c.png)

Ich dachte, Jarvis legt für die gleiche Funktion auch immer den gleichen State an.
Das ist aber sicher nichts woran man sich aufhalten sollte. 

![image](https://user-images.githubusercontent.com/4459312/201207712-8295087c-10ae-4022-a6c7-61af1e8804c2.png)

Inhaltlich passt es bis auf die Einheit. Dieses Gerät gibt seine CT in "mired" (komische Einheit: `10E6 / Kelvin`) an.
Screenshot aus zigbee2mqtt:

![image](https://user-images.githubusercontent.com/4459312/201208437-6fcd2538-a2be-4bf6-86e7-cc212d497f6a.png)

Iobroker hat auch die richtige Einheit am DP:

![image](https://user-images.githubusercontent.com/4459312/201208587-c61562c4-1347-4a99-a0cc-4ad1c266a6de.png)

**Comment by Zefau** [comment]
> Ich dachte, Jarvis legt für die gleiche Funktion auch immer den gleichen State an.

Nein, das ist nicht so. Die Datenpunkte werden 1-zu-1 übernommen. Das "Mapping" erfolgt lediglich im Hintergrund indem die Standard-Werte hinterlegt werden.

> Inhaltlich passt es bis auf die Einheit. Dieses Gerät gibt seine CT in "mired" (komische Einheit: 10E6 / Kelvin) an.

ColorTemperature erwartet einen Wert von 2000 bis 6500.  `10E6` meint wahrscheinlich 10000000. Da müsstest du entweder in jarvis (wenn Pro) oder in ioBroker in den Standard umrechnen.

**Comment by mcuiobroker** [comment]
@zefau kannst du mal bei Gelegenheit das Mapping bzw. die Standard-Einstellungen dazu bekannt geben, damit ich in die Doku mit aufnehmen kann.

**Comment by Zefau** [comment]
für Licht:
```

export const icon = "lightbulb-on";
export const config = {
	"_any": {
	},
	"on": {
		"ignore": true,
		"substitute": true,
		"bodyElement": null,
		"actionElement": "SwitchAction",
		
		"icon": {
			"true": "lightbulb-on",
			"false": "lightbulb-off-outline"
		}
	},
	"power": { // SAME AS ON
		"bodyElement": null,
		"actionElement": "SwitchAction",
		
		"icon": {
			"true": "lightbulb-on",
			"false": "lightbulb-off-outline"
		}
	},
	"state": { // SAME AS ON
		"ignore": true,
		"bodyElement": null,
		"actionElement": "SwitchAction",

		"icon": {
			"true": "lightbulb-on",
			"false": "lightbulb-off-outline"
		}
	},
	"relay0": { // SAME AS ON
		"ignore": true,
		"bodyElement": null,
		"actionElement": "SwitchAction",
		
		"icon": {
			"true": "lightbulb-on",
			"false": "lightbulb-off-outline"
		}
	},
	"relay1": { // SAME AS ON
		"ignore": true,
		"bodyElement": null,
		"actionElement": "SwitchAction",
		
		"icon": {
			"true": "lightbulb-on",
			"false": "lightbulb-off-outline"
		}
	},
	"dimmer": {
		"ignore": true,
		"bodyElement": "LevelBody",
		"actionElement": null,
		
		"value": val => val > 0 && val <= 1 ? val * 100 : val,
		"unit": val => val > 0 ? " %" : null,
		"stateStyle": {
			"default": {},
			"0": {
				"color": "#999"
			}
		},
		"icon": {
			"default": "lightbulb-on",
			"0": "lightbulb-off-outline"
		},
		"display": {
			"0": "light#level#off"
		}
	},
	"brightness": { // SAME AS DIMMER
		"ignore": true,
		"bodyElement": "LevelBody",
		"actionElement": null,
		
		"value": val => val > 0 && val <= 1 ? val * 100 : val,
		"unit": val => val > 0 ? " %" : null,
		"stateStyle": {
			"default": {},
			"0": {
				"color": "#999"
			}
		},
		"icon": {
			"default": "lightbulb-on",
			"0": "lightbulb-off-outline"
		},
		"display": {
			"0": "light#level#off"
		}
	},
	"level": { // SAME AS DIMMER
		"substitute": true,
		"bodyElement": "LevelBody",
		"actionElement": null,
		
		"value": val => val > 0 && val <= 1 ? val * 100 : val,
		"unit": val => val > 0 ? " %" : null,
		"stateStyle": {
			"default": {},
			"0": {
				"color": "#999"
			}
		},
		"icon": {
			"default": "lightbulb-on",
			"0": "lightbulb-off-outline"
		},
		"display": {
			"0": "light#level#off"
		}
	},
	"ct": {
		"substitute": true,
		"bodyElement": "LevelBody",
		"actionElement": null,
		"properties": {
			"min": 2000,
			"max": 6500
		},
		
		"icon": {
			"default": "thermometer"
		},
		"unit": " °K"
	},
	"colortemp": {
		"ignore": true,
		"bodyElement": "LevelBody",
		"actionElement": null,
		"properties": {
			"min": 2000,
			"max": 6500
		},
		
		"icon": {
			"default": "thermometer"
		},
		"unit": " °K"
	},
	"colortemperature": {
		"ignore": true,
		"bodyElement": "LevelBody",
		"actionElement": null,
		"properties": {
			"min": 2000,
			"max": 6500
		},
		
		"icon": {
			"default": "thermometer"
		},
		"unit": " °K"
	},
	"hue": {
		"bodyElement": "LightHueBody",
		"actionElement": "LightColorState",
		
		"icon": {
			"default": "palette"
		},
		"unit": " °"
	},
	"rgb": {
		"bodyElement": "LightColorBody",
		"actionElement": "LightColorState",
		
		"icon": {
			"default": "palette"
		}
	},
	"hsv": {
		"substitute": true,
		"bodyElement": "LightColorBody",
		"actionElement": "LightColorState",
		
		"icon": {
			"default": "palette"
		}
	},
	"hex": {
		"bodyElement": "LightColorBody",
		"actionElement": "LightColorState",
		
		"icon": {
			"default": "palette"
		}
	}
}
```

**Comment by mcuiobroker** [comment]
Bitte auch für die anderen Gewerke. Danke.

**Comment by Sineos** [comment]
Danke, guter Hinweis mit der Umrechnung. Bin Pro und damit kann ich es zum ersten mal brauchen. Bisher wars nur als Geste gedacht 👍

**Comment by Zefau** [comment]
@mcuiobroker https://github.com/Zefau/jarvis.functions

**Comment by mcuiobroker** [comment]
Bleibt das? Dann referenziere ich nur.

**Comment by Zefau** [comment]
Jo, das bleibt.

**Comment by Zefau** [comment]
by the way: https://github.com/Zefau/jarvis.adapters
