### ISSUE TITLE
ButtonAction: State zeigt Action-Wert

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2035]
> Ich habe für state und action unterschiedliche Datenpunkte vergeben. Der Datenpunkt action verhält sich wie erwartet. Er springt für die Pulsdauer auf True und anschließend auf initial. Die Anzeige in meinem GIF links neben dem Button zeigt aber den Wet von Action und nicht state BISzu dem Zeitpunkt an dem der State in meinem Fall DimmerState wieder seinen Zustand ändert.

_Originally posted by @kevinhaybach in https://github.com/Zefau/ioBroker.jarvis/discussions/2027#discussioncomment-4070327_

**Comment by Zefau** [comment]
@kevinheyback schau mal bitte mit `v3.1.0-beta.13`

**Comment by kevinhaybach** [comment]
Ich bekomme eine Fehlermeldung bei der Installation. Spielen meine Node.js (v16.17.0) oder NPM(8:15.0) eine Rolle?
<img width="470" alt="image" src="https://user-images.githubusercontent.com/83004345/200622715-17d51118-fd10-4dfc-98bf-1e0bdd047885.png">

**Comment by kevinhaybach** [comment]
Nein hat leider keine Veränderung gebracht

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-beta.14`

**Comment by kevinhaybach** [comment]
Fixed in v3.1.0-beta.17
