### ISSUE TITLE
v3.1.0-beta.13: DropdownAction funktioniert nicht

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2036]
DropdownAction funktioniert seit `v3.1.0-beta.13` nicht mehr.
Wert kann zwar ausgewählt werden, Datenpunkt wird aber nicht geschrieben.

Fehler in der Konsole:

ReferenceError: assignment to undeclared variable val

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-beta.14`

**Comment by Bernd9000** [comment]
Läuft wieder
