### ISSUE TITLE
v3.1.0-beta.12 Binding-Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2037]
Binding ist ein boolean-Wert. Hat sich was geändert?
```
{
  "200": "mdi:lightbulb-group",
  "({hue-extended.0.lights.008-schreibtisch_unten.action.on}==false || {wifilight.0.192_168_178_62.on}==false) && {val}==0": "mdi:led-strip-variant",
  "({wifilight.0.192_168_178_62.on}==false || {hue-extended.0.lights.008-schreibtisch_unten.action.on}==false) && {val}==100": "mdi:lamps-outline",
  "{hue-extended.0.lights.008-schreibtisch_unten.action.on}==true  &&  {wifilight.0.192_168_178_62.on}==true": "mdi:lightbulb-group"
}
```
![image](https://user-images.githubusercontent.com/84818934/200431318-2325fcc7-e3b1-4a46-9dae-75bf10ecae6c.png)
![image](https://user-images.githubusercontent.com/84818934/200431358-d855dcb5-2d4a-46f1-8e62-d4b2fdddf9db.png)
![image](https://user-images.githubusercontent.com/84818934/200431601-a695401b-8baa-4bdd-a1b5-84225be674d3.png)

**Comment by Bernd9000** [comment]
Ich glaube das ist aktuell so, das der Vergleichswert immer mit Hochkomma eingeklammert ist ?
Zumindest ist es bei mir bei `v3.1.0-beta.12` so
`='false'`

**Comment by Zefau** [comment]
Ist gewollt, aber nur bei Strings. Muss ich für Boolean Werte noch verhindern.

**Comment by Bernd9000** [comment]
Ohj, dann hab ich dann bestimmt wieder ein großes Problem.....
Bei mir sind fast alle Werte mit `true` oder `false` vom Typ string

**Comment by Zefau** [comment]
Wenn du den Typ im Objekt meinst, dann hast du kein Problem. jarvis erkennt die Typen automatisch.

**Comment by Zefau** [comment]
schaut bitte nochmal mit `v3.1.0-beta.14`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/200676550-bf76ee20-a49f-43f9-803c-c94a56450ce8.png)

**Comment by Zefau** [comment]
`v3.1.0-beta.15`

**Comment by mcuiobroker** [comment]
Jetzt kam kein automatischer Reload.
