### ISSUE TITLE
v3.1.0-beta.15 Fehlermeldungen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2038]
![image](https://user-images.githubusercontent.com/84818934/200681219-b983d489-3258-4d0d-a200-49a153ec201c.png)

![image](https://user-images.githubusercontent.com/84818934/200681271-d01c8c83-33fd-454b-99a5-37bee800a28a.png)

![image](https://user-images.githubusercontent.com/84818934/200681344-629a8644-6317-4113-a221-d7587e83de0c.png)

**Comment by Zefau** [comment]
`v3.1.0-beta.16`

**Comment by Zefau** [comment]
`v3.1.0-beta.17`

**Comment by mcuiobroker** [comment]
Keine Fehlermeldungen mehr, aber auch kein automatischer Reload.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/200686355-2a9d510c-a69f-49d2-ad87-63eeed1e09d8.png)

**Comment by Zefau** [comment]
in https://raw.githubusercontent.com/Zefau/ioBroker.jarvis/master/www/js/index-c15ec56c.js finde ich `LightColorStateConfig` nicht?

**Comment by mcuiobroker** [comment]
Bis jetzt nicht wieder aufgetaucht. Mache erstmal zu.
`v3.1.0-beta.21`
