### ISSUE TITLE
v3.1.0-beta.16: Binding funktioniert nicht mehr

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2039]
Binding im Datenpunkt `power` funktioniert seit `v3.1.0-beta.16` nicht mehr.
Icon soll gelb blinken wenn Gerät offline.
**ioBroker Datenpunkt** ist ein `string` !  Datenpunkt hat den Wert `true` oder `false` als `string.`
Nehme ich das Hochkomma weg beim Wertevergleich funktioniert es wieder.
Wie erkennt jarvis ob der Wert boolean oder string ist ?

ioBroker Datenpunkt:

{
  "common": {
    "name": "online",
    "desc": "Manuell erzeugt",
    "role": "state",
    "type": "string",
    "read": true,
    "write": true,
    "def": ""
  },
  "type": "state",
  "native": {},
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1667945879240,
  "_id": "0_userdata.0.Test.TestSchalter6.online",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

Geräte Datenpunkt jarvis:

"a1311954-ed39-450f-8cb0-0b1d21995006_21e68_0a61c_35fcc_f8e53_f031a_7cb4b_f0d0f_87574_ff90d": {
    "name": "TestSchalter-6",
    "icon": "",
    "label": "",
    "function": "_defaults",
    "states": {
      "online": {
        "stateKey": "online",
        "showState": true,
        "state": "0_userdata.0.Test.TestSchalter6.online",
        "icon": {
          "default": "default",
          "false": "wifi-alert blink",
          "true": "wifi"
        },
        "display": {
          "true": "Online",
          "false": "Offline"
        },
        "iconStyle": {
          "default": {
            "color": "#00F"
          },
          "false": {
            "color": "#F00"
          },
          "true": {
            "color": "#0F0"
          }
        }
      },
      "power": {
        "stateKey": "power",
        "showState": true,
        "state": "0_userdata.0.Test.TestSchalter6.power",
        "stateStyle": "",
        "properties": "",
        "actionElement": "IconButtonAction",
        "ButtonActionConfig": {},
        "bodyElement": "LastChangeBody",
        "action": "",
        "IconButtonActionConfig": {
          "pushButton": false
        },
        "icon": {
          "{0_userdata.0.Test.TestSchalter6.online}='false'": "lightbulb-on blink",
          "true": "lightbulb-on",
          "false": "lightbulb-off-outline"
        },
        "label": "",
        "iconStyle": {
          "{0_userdata.0.Test.TestSchalter6.online}='false'": {
            "color": "#FF0"
          },
          "true": {
            "color": "#0F0"
          },
          "false": {
            "color": "#F00"
          }
        }
      }
    },

**Comment by mcuiobroker** [comment]
`'{0_userdata.0.Test.TestSchalter6.online}'='false'"`

**Comment by Bernd9000** [comment]
Das mit dem Hochkomma auf beiden Seite funktioniert bei `v3.1.0-beta.17` nicht.
Die Testschalter mit Testdatenpunkt sind kopien von den echten Geräten zum testen.
Was meinst Du mit Type vom Schalter ?

**Comment by mcuiobroker** [comment]
Der Type vom ioBroker-DP ist jetzt "string" -> sollte boolean sein?
![image](https://user-images.githubusercontent.com/84818934/200939216-ef5d6585-673a-477c-8623-5aeb43b6b9f9.png)

**Comment by Bernd9000** [comment]
Leider geben das die Geräte so vor.
Ich könnte das natürlich ändern, aber das muß ich dann bei allen Geräten händisch mit einem übergeordnetem System machen, wie schon jetzt teilweise bei jarvis 3.0
Was ist mit Geräten die mehrere Zustände in einem Datenpunkt mit dem Datentyp `string` schreiben ?
Z.B.:  0,1,Pause  oder  true,false,0
Wie erkennt jarvis hier automatisch um welchen Datenyp es sich handelt ? Typidentifizierung an Hand des Wertes ?
Es wäre gut wenn ich selbst beim Binding den Datentyp in jarvis angeben könnte.

**Comment by Zefau** [comment]
Bitte nicht ändern. Das macht jarvis. Funktioniert nur noch nicht wie es soll.

**Comment by Bernd9000** [comment]
Hab nochmal getestet, mir viel auf das bei einem Gerät das selbe Binding funktioniert.
Wenn der IOBroker Datenpunkt vom Binding von mir selbst geändert wird funktioniert das Binding.
Wenn der IOBroker Datenpunkt vom Binding durch jarvis selbst geändert wird, funktioniert es nicht.

**Comment by Bernd9000** [comment]
Das sind die Eigenschaften vom Datenpunkt.

Hier hat jarvis den Wert verändert, Binding funktioniert nicht:
![1](https://user-images.githubusercontent.com/77005685/201050329-d476ea86-ad93-45c7-a073-973308665d9a.jpg)

Und hier hat node-red den Datenpunkt verändert, Binding läuft:
![2](https://user-images.githubusercontent.com/77005685/201050344-c5f550e7-cc42-45c1-805f-50bdbee411eb.jpg)

**Comment by Zefau** [comment]
Ich vermute es macht einen Unterschied den Wert als Boolean oder String zu schreiben.

**Comment by Bernd9000** [comment]
Stimmt, jarvis selbst weist darauf hin das Er selbst ein Boolean gesendet hat... :-)

![3](https://user-images.githubusercontent.com/77005685/201176589-d1d0a799-b96e-4678-8e0e-f803bedeffe2.jpg)

Dann war der Testschalter von mir Schrott, das muß ich anders machen.
Dann kann eigentlich das Issue hier dicht ?

**Comment by Zefau** [comment]
Also in der Erkennung kann ich das noch korrigieren. Also, dass `true` / `false` immer als Boolean interpretiert wird, egal, mit welchem Typ es geliefert wird (siehe https://github.com/Zefau/ioBroker.jarvis/issues/2039#issuecomment-1309402486).

Was ich nicht (bzw. nur mit Aufwand) ändern kann ist, dass das mit einem anderen Typ als boolean geschickt wird. Also die Info deines letzten Beitrags.

**Comment by Bernd9000** [comment]
Hmmm, eigentlich denke ich Du solltest es so lassen wie es ist, nicht das danach jemand anders Schwierigkeiten hat ?
Und sorry für dieses Issue, konnte nicht ahnen das der Testschalter nicht mehr funktioniert  :-)
