### ISSUE TITLE
Bug: CutomHTML

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#204]
CustomHTML autosize not 100% working

![image](https://user-images.githubusercontent.com/25475385/96336479-6b7acb80-1080-11eb-8972-89afdb8ddef2.png)

Tables are not working correctly
![image](https://user-images.githubusercontent.com/25475385/96336522-bac0fc00-1080-11eb-822d-a8d7617c5d2a.png)

![image](https://user-images.githubusercontent.com/25475385/96336857-b564b100-1082-11eb-8d06-2b76e0e3d416.png)

**Comment by Zefau** [comment]
@duczz Could you provide the HTML code for the second and third screenshot?

**Comment by Zefau** [comment]
Regarding the first screenshot: Have you set a widget min/max height ?

**Comment by duczz** [comment]
First Screen:
Nope its empty, but i cant make it higher as in this in this screen, when i try it with 500 for example, this size is fix

Table Code:
`<center><table bordercolor="grey" border="2px" cellspacing="1" cellpadding="1" width="100%" rules="none" style="color:#BDBDBD;  font-size:16px; font-family:Helvetica;background-image: linear-gradient(42deg,black,black);"><tr height="35" style="color:#ffffff; font-size: 16px; font-weight: bold ;  border-bottom: 1px solid grey "><td width=auto align=left>&ensp;20:17&ensp;</td><td width=auto align=left>&ensp;Tankstelle&ensp;</td><td  align=center>&ensp;Diesel&ensp;</td><td align=center>&ensp;E5&ensp;</td><td  align=center>&ensp;E10&ensp;</td><td  align=center>&ensp;Status&ensp;</td></tr><tr bgcolor="#151515"><td align=left >&ensp;<img src=/vis.0/Penthouse/Meine_Icons/Tankstellen_logos/1200px-Agip_logo.svg.png height="30" width="30">&ensp;</td><td align=left>&ensp;Agip - &ensp;</td><td align=center>&ensp;1.02 €&ensp;</td><td align=center>&ensp;1.22 €&ensp;</td><td align=center>&ensp;1.17 €&ensp;</td><td align=center>&ensp;open&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<img src=/vis.0/Penthouse/Meine_Icons/Tankstellen_logos/1200px-Agip_logo.svg.png height="30" width="30">&ensp;</td><td align=left>&ensp;Agip - &ensp;</td><td align=center>&ensp;1.02 €&ensp;</td><td align=center>&ensp;1.22 €&ensp;</td><td align=center>&ensp;1.17 €&ensp;</td><td align=center>&ensp;open&ensp;</td></tr><tr bgcolor="#151515"><td align=left >&ensp;<img src=/vis.0/Penthouse/Meine_Icons/Tankstellen_logos/Avia.svg height="30" width="30">&ensp;</td><td align=left>&ensp;AVIA - &ensp;</td><td align=center>&ensp;1.02 €&ensp;</td><td align=center>&ensp;1.22 €&ensp;</td><td align=center>&ensp;1.17 €&ensp;</td><td align=center>&ensp;open&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<img src=/vis.0/Penthouse/Meine_Icons/Tankstellen_logos/Shell.png height="30" width="30">&ensp;</td><td align=left>&ensp;Shell - &ensp;</td><td align=center>&ensp;-&ensp;</td><td align=center>&ensp;-&ensp;</td><td align=center>&ensp;-&ensp;</td><td align=center>&ensp;closed&ensp;</td></tr><tr bgcolor="#151515"><td align=left >&ensp;<img src=/vis.0/Penthouse/Meine_Icons/Tankstellen_logos/innerbraz-omv-tankstelle-omv-logo.jpg height="30" width="30">&ensp;</td><td align=left>&ensp;OMV - &ensp;</td><td align=center>&ensp;1.02 €&ensp;</td><td align=center>&ensp;1.22 €&ensp;</td><td align=center>&ensp;1.17 €&ensp;</td><td align=center>&ensp;open&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<img src=/vis.0/Penthouse/Meine_Icons/Tankstellen_logos/Freie_Tankstelle.jpg height="30" width="30">&ensp;</td><td align=left>&ensp;Isar-Center - &ensp;</td><td align=center>&ensp;<font color="yellow"><b>1.00 €&ensp;</td><td align=center>&ensp;<font color="yellow"><b>1.20 €&ensp;</td><td align=center>&ensp;1.17 €&ensp;</td><td align=center>&ensp;open&ensp;</td></tr><tr bgcolor="#151515"><td align=left >&ensp;<img src=/vis.0/Penthouse/Meine_Icons/Tankstellen_logos/Freie_Tankstelle.jpg height="30" width="30">&ensp;</td><td align=left>&ensp;Real - &ensp;</td><td align=center>&ensp;1.00 €&ensp;</td><td align=center>&ensp;1.21 €&ensp;</td><td align=center>&ensp;<font color="yellow"><b>1.16 €&ensp;</td><td align=center>&ensp;open&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<img src=/vis.0/Penthouse/Meine_Icons/Tankstellen_logos/innerbraz-omv-tankstelle-omv-logo.jpg height="30" width="30">&ensp;</td><td align=left>&ensp;OMV - &ensp;</td><td align=center>&ensp;1.02 €&ensp;</td><td align=center>&ensp;1.22 €&ensp;</td><td align=center>&ensp;1.17 €&ensp;</td><td align=center>&ensp;open&ensp;</td></tr></table>`

**Comment by duczz** [comment]
First Screen works now since Beta 38

**Comment by Zefau** [comment]
The HTML Code for the table looks like that on my jarvis:

![image](https://user-images.githubusercontent.com/14368811/96385316-60649000-1193-11eb-9ad8-be229d6083eb.png)

Icons are located at `/vis.0/`, which is why those won't load. Rest looks fine though.

Is the code you have provided exactly the same in the state as well? Have you configure the device within jarvis in any special way?

**Comment by duczz** [comment]
hmm, it looks like the HTML View in Jarvis is broken when the state is updated in iobroker.

**Comment by duczz** [comment]
Beta39, auto size not correct (First Screen)

![image](https://user-images.githubusercontent.com/25475385/96451344-b67b1700-1217-11eb-975e-a8e531dfa14c.png)

**Comment by Zefau** [comment]
I have difficulties to find the problem. It works fine for me:

![image](https://user-images.githubusercontent.com/14368811/96926675-27d7f580-14b6-11eb-969d-65a150ce00c5.png)

Changing the state holding the HTML code does change the view correctly.

**Comment by Zefau** [comment]
@duczz Could you check with the current beta.47 ? I have changed some things in the hopes it solves this issue. thanks

**Comment by duczz** [comment]
@Zefau Die Tanktabelle passt scheinbar nun, dafür geht das Bitcoin Javascript nicht mehr und die Heiztabelle sieht auch noch wie oben aus

**Comment by Zefau** [comment]
@duczz hast du das ganze Skript von dem verlinkten ioBroker Beitrag so verwendet? Hast du einen Fehler in der Konsole?

**Comment by Zefau** [comment]
@duczz und hast du auch nochmal den Code für das Bitcoin Ding zur Hand?

**Comment by Zefau** [comment]
Probier nochmal die `v1.1.0-beta.52`. Mit der beta funktioniert bei mir Screenshot 1 und 2 deines ersten Beitrags.

Screenshot 3 fehlt mir der Code, um es nachzuvollziehen.

**Comment by duczz** [comment]
Die ersten 2 Bilder funktionieren wieder richtig, aber die Weite wird nun nicht mehr automatisch abgestimmt.

Hier der Code für das 3te Bild:
`<center><table bordercolor="grey" border="2px" cellspacing="3" cellpadding="3" width="auto" rules="all" style="color:#BDBDBD;  font-size:14px; font-family:Helvetica;background-image: linear-gradient(42deg,#424242,#424242);"><tr height="35" style="color:#BDBDBD; font-size: 16px; font-weight: normal ;  border-bottom: 3px solid white "><td width=auto align=left>&ensp;Schedule&ensp;</td><td width=auto align=left>&ensp;Gerät&ensp;</td><td  align=center>&ensp;&ensp;</td><td align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i><button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.0.enabled')">⏱</button><font color="red">Wohnzimmer Klimaanlage</i>&ensp;</td><td align=left>&ensp;<font color="red"><i>SET</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>false/true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<font color="yellow">25&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>ON with: true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>18:00</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>OFF with: false</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>22:00</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i><button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.1.enabled')">⏱</button><font color="red">Büro Klimaanlage</i>&ensp;</td><td align=left>&ensp;<font color="red"><i>SET</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>false/true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<font color="yellow">25&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i><button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.2.enabled')">⏱</button><font color="red">Schlafzimmer Klimaanlage</i>&ensp;</td><td align=left>&ensp;<font color="red"><i>SET</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>false/true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<font color="yellow">25&ensp;</td></tr></table><script> function setOnDblClickCustom( myvalue ) {	var Self = this; var objID = myvalue;	Self.servConn.getStates(objID, (error, states) => {  console.log(states);  Self.servConn.setState(objID, !states[objID].val); }); } </script>`

**Comment by Zefau** [comment]
Reminder: `width: 100%`, aber HTML nimmt keine volle Breite ein

**Comment by Zefau** [comment]
should be solved with `v1.1.0-beta.58`. Can you confirm all HTMLs are working incl. their height and with?

**Comment by duczz** [comment]
Bis aufs letzte bild schaut nun alles gut aus, das dritte bleibt gleich

**Comment by Zefau** [comment]
Kannst du mir einen Screenshot (ggf. deiner vis) zur Verfügung stellen, wie es aussehen müsste?
Bei sieht es so ok aus:
![image](https://user-images.githubusercontent.com/14368811/97798366-c0dcde00-1c25-11eb-8f74-28919e6587ab.png)

**Comment by Zefau** [comment]
Das Script am Ende wird nicht funktionieren, falls es das ist, was du brauchst:
```js
<script>
    function setOnDblClickCustom(myvalue) {
        var Self = this;
        var objID = myvalue;
        Self.servConn.getStates(objID, (error, states) => {
            console.log(states);
            Self.servConn.setState(objID, !states[objID].val);
        });
    }
</script>
```

Das Skript ist ioBroker.vis spezifisch (`Self.servConn`) und wird in jarvis nicht gehen.

**Comment by duczz** [comment]
Auf deinem Screenshot sieht es eigentlich passend aus

**Comment by Zefau** [comment]
Wie sieht es denn bei dir inzwischen aus? Hast du irgendwas im Widget noch konfiguriert? Ich weiß sonst nicht, was ich noch machen soll, insbesondere, wenn es bei mir geht und bei dir nicht? :-\

**Comment by duczz** [comment]
Aktuelle Beta:

im Vollbild:
![image](https://user-images.githubusercontent.com/25475385/96336857-b564b100-1082-11eb-8d06-2b76e0e3d416.png)

Ohne Vollbild:
![image](https://user-images.githubusercontent.com/25475385/97959008-c0bc1a00-1dae-11eb-827a-e4edd2d5239f.png)

**Comment by Zefau** [comment]
Also Vollbild funktioniert auch wie gewünscht?

**Comment by duczz** [comment]
Jup genau.

**Comment by duczz** [comment]
Das CustomHTML wird bei dieser Tabelle zu groß gemacht.
![image](https://user-images.githubusercontent.com/25475385/104157443-6f9e5700-53eb-11eb-9eec-939683eb2e48.png)

`<center><table bordercolor="grey" border="2px" cellspacing="3" cellpadding="3" width="auto" rules="all" style="color:#D8D8D8;  font-size:14px; font-family:Helvetica;background-image: linear-gradient(42deg,#424242,#424242);"><tr height="35" style="color:white; font-size: 16px; font-weight: normal ;  border-bottom: 2px solid white "><td width=130 align=left>&ensp;Zeitplan&ensp;</td><td width=130 align=left>&ensp;Gerät&ensp;</td><td  align=center>&ensp;Timer&ensp;</td><td align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.0.enabled')">⏱</button><font color="yellow">Wohnzimmer Klimaanlage&ensp;</td><td align=left>&ensp;Wohnzimmer Klimaautomatik&ensp;</td><td align=center>&ensp;false/true&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('alias.0.Wohnzimmer.Klimaautomatik.SET')">🔴</button>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;&ensp;</td><td align=left>&ensp;ON with: true&ensp;</td><td align=center>&ensp;18:00&ensp;</td><td align=center>&ensp;Mo&ensp;</td><td align=center>&ensp;Di&ensp;</td><td align=center>&ensp;Mi&ensp;</td><td align=center>&ensp;Do&ensp;</td><td align=center>&ensp;FR&ensp;</td><td align=center>&ensp;Sa&ensp;</td><td align=center>&ensp;So&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;&ensp;</td><td align=left>&ensp;OFF with: false&ensp;</td><td align=center>&ensp;22:00&ensp;</td><td align=center>&ensp;Mo&ensp;</td><td align=center>&ensp;Di&ensp;</td><td align=center>&ensp;Mi&ensp;</td><td align=center>&ensp;Do&ensp;</td><td align=center>&ensp;FR&ensp;</td><td align=center>&ensp;Sa&ensp;</td><td align=center>&ensp;So&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i><button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.1.enabled')">⏱</button><font color="red">Büro Klimaanlage</i>&ensp;</td><td align=left>&ensp;<font color="red"><i>Büro Klimaautomatik</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>false/true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('alias.0.Büro.Klimaautomatik.SET')">🔴</button>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>OFF with: false</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>23:00</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i><button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.2.enabled')">⏱</button><font color="red">Schlafzimmer Klimaanlage</i>&ensp;</td><td align=left>&ensp;<font color="red"><i>Schlafzimmer Klimaautomatik</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>false/true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('alias.0.Schlafzimmer.Klimaautomatik.SET')">🔴</button>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>ON with: true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>21:30</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>OFF with: false</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>23:45</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr></table><script> function setOnDblClickCustom( myvalue ) {	var Self = this; var objID = myvalue;	Self.servConn.getStates(objID, (error, states) => {  console.log(states);  Self.servConn.setState(objID, !states[objID].val); }); } </script>`

**Comment by Zefau** [comment]
@duczz ist das noch aktuell?

**Comment by duczz** [comment]
ja

**Comment by Zefau** [comment]
Was genau meinst du mit 
> Das CustomHTML wird bei dieser Tabelle zu groß gemacht.

Bei mir sieht es gut aus? 

![image](https://user-images.githubusercontent.com/14368811/108610615-52d84480-73d7-11eb-8af6-e328faeef17b.png)

**Comment by duczz** [comment]
Wie hier zu sehen https://github.com/Zefau/ioBroker.jarvis/issues/204#issuecomment-757687094 hört die höhe nicht nach der Tabelle auf sondern geht noch weiter

**Comment by Zefau** [comment]
Passiert bei mir mit der aktuellen beta auch nicht. Wie hast du das Widget konfiguriert? So wie https://github.com/Zefau/ioBroker.jarvis/issues/204#issuecomment-720951710 zu sehen, also ohne Angabe von Höhen?

**Comment by duczz** [comment]
So ist es eingebunden: 
![image](https://user-images.githubusercontent.com/25475385/108622321-47693580-7438-11eb-9a65-9ed600535f60.png)

**Comment by Zefau** [comment]
Also bei mir klappt es mit genau den Einstellungen. Wieder sehr merkwürdig.

Kannst du mal in den Source Code schauen (Rechtsklick auf das CustomHTML und dann `Inspect Element (Q)`). Wird es bei dir als iFrame gerendet?

![image](https://user-images.githubusercontent.com/14368811/108622739-0e7e9000-743b-11eb-9bcb-d938713173a2.png)

**Comment by duczz** [comment]
Jup wird als iframe angezeigt.

anbei mal nochmal der aktuelle inhalt:
`<center><table bordercolor="grey" border="2px" cellspacing="3" cellpadding="3" width="auto" rules="all" style="color:#D8D8D8;  font-size:14px; font-family:Helvetica;background-image: linear-gradient(42deg,#424242,#424242);"><tr height="35" style="color:white; font-size: 16px; font-weight: normal ;  border-bottom: 2px solid white "><td width=130 align=left>&ensp;Zeitplan&ensp;</td><td width=130 align=left>&ensp;Gerät&ensp;</td><td  align=center>&ensp;Timer&ensp;</td><td align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td><td  align=center>&ensp;&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i><button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.0.enabled')">⏱</button><font color="red">Wohnzimmer Klimaanlage</i>&ensp;</td><td align=left>&ensp;<font color="red"><i>Wohnzimmer</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>false/true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('alias.0.Wohnzimmer.Klimaautomatik.SET')">🔴</button>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>ON with: true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>18:00</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>ON with: true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>22:00</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i><button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.1.enabled')">⏱</button><font color="red">Büro Klimaanlage</i>&ensp;</td><td align=left>&ensp;<font color="red"><i>Büro</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>false/true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('alias.0.Büro.Klimaautomatik.SET')">🔴</button>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>OFF with: false</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>23:00</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i><button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('time-switch.0.onoff.2.enabled')">⏱</button><font color="red">Schlafzimmer Klimaanlage</i>&ensp;</td><td align=left>&ensp;<font color="red"><i>Schlafzimmer</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>false/true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;<font color="red"><i></i>&ensp;</td><td align=center>&ensp;&ensp;</td><td align=center>&ensp;<button style="border:none; background-color:transparent; color:white; font-size:1em; text-align:left" value="toggle" onclick="setOnDblClickCustom('alias.0.Schlafzimmer.Klimaautomatik.SET')">🔴</button>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>ON with: true</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>21:30</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr><tr bgcolor="#000000"><td align=left >&ensp;<font color="red"><i></i>&ensp;</td><td align=left>&ensp;<font color="red"><i>OFF with: false</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>23:45</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mo</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Di</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Mi</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Do</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>FR</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>Sa</i>&ensp;</td><td align=center>&ensp;<font color="red"><i>So</i>&ensp;</td></tr></table><script> function setOnDblClickCustom( myvalue ) {	var Self = this; var objID = myvalue;	Self.servConn.getStates(objID, (error, states) => {  console.log(states);  Self.servConn.setState(objID, !states[objID].val); }); } </script>`

**Comment by Zefau** [comment]
im Firefox geht das. Der Fehler scheint im Chrome zu sein?

**Comment by Zefau** [comment]
Wenn du das Widget nicht auf Vollbild machst sondern mit Titel, wäre es dann korrekt?

**Comment by duczz** [comment]
Ich nutze Chrome richtig.
Bei nicht Vollbild bleibt der Fehler bestehen

**Comment by Zefau** [comment]
Scheint am cellpadding und cellspacing der Tabelle zu liegen. Auf 0 tritt das Problem bei mir nicht auf.

**Comment by Zefau** [comment]
probier nochmal mit `v2.2.0-beta.49`.

**Comment by duczz** [comment]
Top Danke
