### ISSUE TITLE
Seiten und TAB Body Stil JSON nicht bindingfähig

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2040]
> ![image](https://user-images.githubusercontent.com/84818934/199588450-1688deea-67b0-4356-988c-9405c612194c.png)

> `{"'{0_userdata.0.jarvis.test.forumTestDP5}'='bad'":{"display":"none !important"}}`

> ![image](https://user-images.githubusercontent.com/84818934/199588536-63e4c050-fb9d-45a9-93f2-c93aaf796a14.png)

> ioBroker-Objekt:
![image](https://user-images.githubusercontent.com/84818934/199588589-caf453de-735c-460a-ba57-e5386a4ab9a4.png)

> Objekte Seite und TAB weiterhin zu sehen?
![image](https://user-images.githubusercontent.com/84818934/199589556-681c3398-7b8c-4b7c-9245-8134701c9e95.png)

> ![image](https://user-images.githubusercontent.com/84818934/199589716-b288586a-7093-41db-8ba8-f36690ab1211.png)

> Zeitweise wird so angezeigt:
![image](https://user-images.githubusercontent.com/84818934/199761457-d0509926-dd79-455c-b328-affd3d6a3e26.png)

> ![image](https://user-images.githubusercontent.com/84818934/199761503-2eb7f0b0-c5cc-4ec0-b393-b7a998e7c5f4.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/discussions/2021_

**Comment by Zefau** [comment]
@mcuiobroker schau nochmal mit `v3.1.0-beta.19`

**Comment by mcuiobroker** [comment]
#2022 
Der Effekt ist noch da.

Testweise das Binding in einen TAB gesetzt -> tut sich nix. Tab bleibt so wie er ist.

**Comment by mcuiobroker** [comment]
Auch die Variante zieht nicht:
```
{
  "{0_userdata.0.jarvis.test.forumTestDP5}=2": {
    "display": "none !important"
  }
}
```

**Comment by Zefau** [comment]
Funktioniert das bei dir?

![image](https://user-images.githubusercontent.com/14368811/201546332-f7e6ed54-7ece-42a1-932e-238a2aea32ab.png)

**Comment by mcuiobroker** [comment]
Ja

**Comment by mcuiobroker** [comment]
Irgendwie löscht er anscheinend das Binding aus der Seite? Komisch?
In der Seite oben stand `{"{0_userdata.0.DP.condition}=false":"mdi-home","{0_userdata.0.DP.condition}=true":"shield-home"}`
sieht man auch in den Sicherungen:
![image](https://user-images.githubusercontent.com/84818934/201546903-5ecc7952-8885-48db-8eb6-6933e570ee3b.png)

![image](https://user-images.githubusercontent.com/84818934/201546772-3a9f89d2-f12e-4772-801e-edada2179866.png)

**Comment by Zefau** [comment]
Jo, wird resettet. Ist mir auch gerade aufgefallen. Konnte jetzt auch https://github.com/Zefau/ioBroker.jarvis/issues/2022 nachvollziehen. Hängt hiermit zusammen.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.21`

**Comment by mcuiobroker** [comment]
Es wird jetzt gespeichert, aber es zieht nicht.

**Comment by Zefau** [comment]
Im Icon auch nicht?

**Comment by mcuiobroker** [comment]
Icon funktioniert.

**Comment by Zefau** [comment]
schau mal mit `v3.1.0-beta.22`

**Comment by mcuiobroker** [comment]
Seite wird jetzt ausgeblendet.
Änderungen werden hier nicht direkt umgesetzt-> erst nach F5.

TAB wird mit dem Eintrag nicht ausgeblendet.
![image](https://user-images.githubusercontent.com/84818934/202036900-69f60fab-e066-4ada-8559-27d3c75dc140.png)

![image](https://user-images.githubusercontent.com/84818934/202036957-d344d04c-63c1-4f07-a580-396539233158.png)

Kein display-Eintrag:
![image](https://user-images.githubusercontent.com/84818934/202037164-c0e9abf4-b6c6-474d-be44-5e91581efbcc.png)

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.1.0-beta.23`

**Comment by Zefau** [comment]
>  Änderungen werden hier nicht direkt umgesetzt-> erst nach F5.

Sollte jetzt funktionieren (BodyStyle gelb auf rot):

![Animation](https://user-images.githubusercontent.com/14368811/202282731-7a45154c-531f-41e1-9288-eca1212ecec6.gif)

**Comment by Zefau** [comment]
Tab ausblenden:

![Tab](https://user-images.githubusercontent.com/14368811/202283199-9f561a34-fd7f-41bd-bc69-16677048086d.gif)

**Comment by mcuiobroker** [comment]
Ich bezog es auf den TAB der noch angezeigt wird, wenn man die Seite auswählt.

**Comment by Zefau** [comment]
ok, ich sehe

**Comment by Zefau** [comment]
Mit normalen Styles geht es, oder? Nur mit display scheinbar nicht.

**Comment by Zefau** [comment]
versuch nochmal mit `v3.1.0-beta.24`

**Comment by mcuiobroker** [comment]
Leider immer noch da.

**Comment by Zefau** [comment]
> Leider immer noch da.

Aber nur auf Handy, nicht auf Desktop?

**Comment by mcuiobroker** [comment]
Auch auf dem Desktop.

**Comment by mcuiobroker** [comment]
Hab die Styless komplett entfernt, gleiches Verhalten.

**Comment by Zefau** [comment]
> Nach F5 ist nur das TAB-Icon oben verschwunden, der Inhalt vom TAB ist zu sehen.
> ...
> Beim Wischen zeigt er dann den TAB oben nicht mehr an, aber den Inhalt von dem TAB.

Das ist klar und wird sich auch nicht ändern, da der Tab ja noch da ist und intern normal behandelt wird. Hierzu gibt es https://github.com/Zefau/ioBroker.jarvis/issues/1249 bzw. https://github.com/Zefau/ioBroker.jarvis/issues/965.

>  {"{0_userdata.0.jarvis.test.forumTestDP5}=2":{"display":"none !important"}}

Schau bitte nochmal mit `v3.1.0-beta.25`. Ich hatte es ohne `!important`.

**Comment by mcuiobroker** [comment]
Funktioniert soweit. Dass der Inhalt von dem TAB stehen bleibt führt evtl. zu Diskussionen?

**Comment by Zefau** [comment]
Der Feature Request der dem zugrunde liegt dient die Tabs zu stylen. Das Verstecken ist nice-to-have, aber kein Feature, da es hierfür die eigenen Feature Requests gibt und ich da andere Sachen für implementieren muss.

Wird sicherlich zur Diskussionen führen, wenn die User hier nicht den Style-Fokus sehen.
