### ISSUE TITLE
v3.1.0-beta.17 Meldung bei Gerät hinzufügen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2043]
![image](https://user-images.githubusercontent.com/84818934/200944675-47aedb08-7819-48d3-b288-7757852c82c8.png)

- [x] Übersetzung
- [ ] Warum direkt nach Aufruf, beim Speichern ok

**Comment by Zefau** [comment]
> Warum direkt nach Aufruf, beim Speichern ok

Beim Speichern selbst gibt es keine Abfrage. Das einzubauen ist in der Tat umständlich, da ich architektonisch Anpassungen vornehmen muss.

Entweder (1) lasse ich es also so oder (2) ich befülle einen Standard-Wert wie z.B. `neues Gerät 123` (123 = zufällige Nummer).

Was meinst du?

**Comment by mcuiobroker** [comment]
Dann lass es so, nur noch die Übersetzung anpassen.

**Comment by Zefau** [comment]
`v3.1.0-beta18`

**Comment by mcuiobroker** [comment]
Passt. Danke.
