### ISSUE TITLE
Feature: Chart

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#205]
Make it possible to modify state outputs. 
Example: convert KB to MB (muliplikator)
![image](https://user-images.githubusercontent.com/25475385/96336485-7afa1480-1080-11eb-8117-29febdbc9aa9.png)

In this chart the left states are the half from the real iobroker state
Example: Chart 0.63 > iobroker 1.26
![image](https://user-images.githubusercontent.com/25475385/96336537-d3c9ad00-1080-11eb-8471-98c093e1b28f.png)

**Comment by Zefau** [comment]
An option for a multiplicator has been with `v1.1.0-beta.46`. Could you test and verify?

**Comment by duczz** [comment]
anzeige passt nicht
![image](https://user-images.githubusercontent.com/25475385/97069331-d7ed5180-15cf-11eb-9ab0-f3998041dde5.png)

**Comment by Zefau** [comment]
> Klappt einwandfrei, aber eigentlich sollte ich dafür gar kein Multiplikator benötigen da die Werte eigentlich in iobroker passen würden

Mit diesem Feature Request hattest du doch einen Multiplikator angefragt? Jetzt brauchst du ihn doch nicht?

**Comment by duczz** [comment]
kommt drauf an, die werte passen nun mit dem Multiplikator 2, aber es liegt meines Erachtens nen Fehler im Jarvis Chart vor.
Da die Werte in iobroker ja passen, in jarvis sinds aber halbiert, so stands oben auch.

**Comment by Zefau** [comment]
> kommt drauf an, die werte passen nun mit dem Multiplikator 2, aber es liegt meines Erachtens nen Fehler im Jarvis Chart vor.
Da die Werte in iobroker ja passen, in jarvis sinds aber halbiert, so stands oben auch.

Ok, habe ich dann falsch verstanden.

Kannst du für das zweite Chart im ioBroker die History Werte nochmal verifizieren? Wundert mich, dass jarvis hier einfach halbiert. Die Werte werden eigl. nur vom history Adapter gezogen und dargestellt.

**Comment by duczz** [comment]
Die Werte in der History passen.
![image](https://user-images.githubusercontent.com/25475385/97077730-5d7bfc00-15e6-11eb-9a99-cfe05ad69b82.png)

**Comment by Zefau** [comment]
Ah ok, jarvis summiert die Werte nach Zeiteinheit auf der x-Achse und bildet den Mittelwert. Aufgrund der 0 Werte wird's halbiert.

**Comment by Zefau** [comment]
Also es ist ioBroker.history. Der Adapter aggregiert alle Wert unabhängig vom `ack`. Nun macht es jarvis auf Basis der Rohdaten. Kannst du die `v1.1.0-beta.51?  prüfen, ob es nun passt?

**Comment by duczz** [comment]
Jetzt schauts gut aus, Top.
Wäre es noch Möglich in der Y-Achse die Komma stelle zu definieren (z.B. 2 Zahlen nach dem Komma anzeigen)

**Comment by duczz** [comment]
in der aktuellen Beta passen die Werte wieder nicht mehr zu den History werten

![image](https://user-images.githubusercontent.com/25475385/97962878-5a3afa00-1db6-11eb-8990-d40aba742c9f.png)
![image](https://user-images.githubusercontent.com/25475385/97962898-645cf880-1db6-11eb-82d0-ad8b7e987792.png)

**Comment by Zefau** [comment]
Bist du sicher? Zoom mal rein. Jarvis bildet je nach Zoom Stufe den Mittelwert. Deine Werte sind stündlich und dein Zoom ist auf Tagesbasis.

**Comment by duczz** [comment]
Jup, beim zoomen ändert sich nichts, Werte bleiben gleich - Zoom steht auf Woche

**Comment by Zefau** [comment]
Nutzt du history, influxdb oder sql?

**Comment by Zefau** [comment]
Das Verhalten der 3 Adapter ist leider unterschiedlich. Bitte probier mal `v1.1.0-beta.74`. Geht es damit nun?

**Comment by duczz** [comment]
ich nutz die history, kannst du die 0 nicht ignorieren? Wobei ne 0 ja den mittelwert nicht ändern sollte

**Comment by Zefau** [comment]
@duczz Ich will die 0 nicht ignorieren, da es sicherlich viele Use Cases anderer Benutzer gibt, wo eine 0 wichtig ist.

Ich ignore `ack` = `false`, was aber nicht korrekt funktioniert hat. Kannst du nochmal die aktuelle beta `v1.1.0-beta.76` prüfen, damit sollte es passen. Danke dir.

**Comment by duczz** [comment]
Schaut super aus, danke
