### ISSUE TITLE
`max` Callback der xAchse in HistoryGraph

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2050]
Lässt sich die Funktion wie hier beschrieben auch umsetzen?

[https://echarts.apache.org/en/option.html#xAxis.max](https://echarts.apache.org/en/option.html#xAxis.max)

Ich habe es so versucht, dann wird aber nicht mehr angezeigt:

![Image](https://user-images.githubusercontent.com/77939385/201540954-29a4e937-e378-4d21-b4df-a342717f2391.png)

`"max": "(value, ts, index) =>  {return value.max + 20000;}"`

_Originally posted by @hosabeni in https://github.com/Zefau/ioBroker.jarvis/issues/1969#issuecomment-1312806915_

**Comment by Zefau** [comment]
@hosabeni schau nochmal mit `v3.1.0-beta.20`

**Comment by hosabeni** [comment]
Geht leider nicht. 

Ich hab folgende Meldung in der Konsole, auch bei HistoryGraph Tabs in denen keine Funktion hinterlegt ist.


![Image](https://user-images.githubusercontent.com/77939385/201746479-e761f244-de6b-40e9-9154-58d09b77f56f.png)


Musst du eigentlich immer Anpassungen machen wenn für einen bestimmten Parameter z.B. `min`, `max` eine Funktion benötigt wird oder sollte das generell funktionieren?

**Comment by Zefau** [comment]
Schau nochmal mit `v3.1.0-beta.22`.

Grundsätzlich muss ich nur etwas tun, wenn es sich um Funktionen handelt, da ich diese im Code parsen muss. Alle anderen Parameter werden so übernommen.

**Comment by hosabeni** [comment]
Der Fehler in der Konsole ist nicht mehr da, aber es wird leider nichts angezeigt.



![Image](https://user-images.githubusercontent.com/77939385/202269250-0520172b-fc70-4efc-96ce-1998a8f60c45.png)


Ist meine Funktion denn so korrekt?

`"max": "(value, ts, index) => {return value.max + 10;}",`


![Image](https://user-images.githubusercontent.com/77939385/202267620-c044756d-1446-477c-b33e-afc7c42079c2.png)

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.1.0-beta.23`

**Comment by hosabeni** [comment]
Funktioniert. Aber leider ist das Ergebnis nicht so wie erwartet.

Ich habe gehofft mit der Funktion auch Werte Anzeigen zu können die in der Zukunft liegen. 

Wie hier mit Grafana:


![Image](https://user-images.githubusercontent.com/77939385/202281530-e3cafc90-bdb2-4033-a55e-2ae4d3fe8fb7.png)

Der Zeitbereich wird auch erweitert aber es werden die keine Werte angezeigt:


![Image](https://user-images.githubusercontent.com/77939385/202282454-fed94576-0791-4621-b452-abe2facae5c6.png)

Hast du da eine Idee?

**Comment by Zefau** [comment]
Es werden ja nur Werte angezeigt, die auch historisiert bzw. gespeichert sind. Wenn du was in der Zukunft anzeigen möchtest, musst du die Werte im History-Adapter (oder Influx, je nachdem, was du nutzt) manipulieren bzw. hinzufügen.

**Comment by hosabeni** [comment]
Die Forecast Werte werden über ein Skript in meine SQL Datenbank geschrieben. Die Werte sind auf jeden Fall da, weil aktuell zeige ich die Daten mit Grafana an (siehe Bild oben). In Grafana ist der Zeitbereich von `now-24h` bis `now+24h` angelegt. 
Ist das hier so nicht möglich?

**Comment by Zefau** [comment]
Es gibt zwei Modi:
1. Rückblick vom aktuellen Zeitpunkt mit einem frei wählbaren Fenster
2. Statischer Blick von einem bestimmten bis zu einem bestimmten Datum

Die Möglichkeit `now+24h` geht aktuell nicht

**Comment by Zefau** [comment]
Kannst aber gerne einen Feature Request aufmachen

**Comment by mcuiobroker** [comment]
Wie muss man die x-Achse und min und max Callback einstellen, damit man nur den heutigen Tag sieht, ab 00:00 Uhr?

**Comment by Zefau** [comment]
`(value,ts,index) => (ts> 1674777600000 {return value})` ergibt keinen Sinn, oder? Wenn du 0:00 Uhr anzeigen möchtest, kannst du nicht `value` als dynamischen Wert returnen, sondern einen statischen Wert.

Aus meiner Sicht müsstest du von `value` oder `ts` den Tag, Monat, Jahr extrahieren (mit `new Date`) und dann mit 0 Uhr zurückgeben.

**Comment by mcuiobroker** [comment]
Genau das verstehe ich noch nicht, mit dem statischen Wert. Wie muss ich denn die beiden statischen Werte eingeben?
Wo? In welcher Form?
`"min" = "1674777600000"` in der x-Achse ?
Dann wäre die Frage, wie kann ich dann min mit dem Callback setzen?
`(value,ts,index)=> return new Date("00:00").getTime();`

**Comment by Zefau** [comment]
Rein zum Test: `(value,ts,index) => 1674777600000` sollte funktionieren.

**Comment by mcuiobroker** [comment]
Nee.
![image](https://user-images.githubusercontent.com/84818934/215198262-7d25951a-355e-46fb-b7ae-6d78b8c1a4cc.png)
![image](https://user-images.githubusercontent.com/84818934/215198386-0f742554-1ae0-4e86-8bbd-319afcf7553e.png)

**Comment by Zefau** [comment]
Liegt an GMT vs. MEZ. Falsche Zeitzone würde ich sagen.

Probier mal
```
(value,ts,index) => {
   const now = new Date(1674853324000);
   return new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime()
}
```

**Comment by Zefau** [comment]
Wenn das auch eine Stunde zu früh ist, dann musst du noch die Zeitzone ausgleichen.

**Comment by mcuiobroker** [comment]
Muss die Funktion in beide Einstellungen ? x-Achse und Callback?
![image](https://user-images.githubusercontent.com/84818934/215199757-430e02ae-5059-4f6e-a7e1-7950eb5b8e69.png)

**Comment by Zefau** [comment]
`min` ist spezifisch für die Achse, also nicht in den Callback.

**Comment by mcuiobroker** [comment]
Das sieht erstmal gut aus.
![image](https://user-images.githubusercontent.com/84818934/215204096-d53c30b5-370a-4656-9651-c523efc70cc4.png)
Hab es jetzt so angepasst, mal schauen
```
{
  "type": "time",
  "min": "(value,ts,index) => { const now = new Date(new Date().getTime()); return new Date(now.getFullYear(), now.getMonth(), now.getDate()).getTime()}"
}
```

**Comment by mcuiobroker** [comment]
Da stimmt noch was nicht?
Obwohl ja die ermittelte min Zeit Heute 00:00 Uhr sein soll, nimmt er Werte von gestern? 
Eigentlich dürfte er nur 10 Minuten anzeigen.

![image](https://user-images.githubusercontent.com/84818934/215295321-af5691a5-94b8-482a-bad6-98a9c702d951.png)

**Comment by Zefau** [comment]
Hängt vermutlich damit zusammen wann heute Daten empfangen werden
