### ISSUE TITLE
v3.1.0-beta.21: Binding Problem

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2051]
Von Beta 18 auf 21 aktualisiert:
Binding werden nur aktualisiert wenn:
1.) Aufruf Popup vom Gerät 
2.) Eventuell bei F5
3.) SwitchAction wird betätigt.

Ansonsten wird der zu letzt angezeigte Wert angezeigt.
Im Browser keine Fehlermeldung.

**Comment by Zefau** [comment]
Kann ich nicht bestätigen. Bitte konkretes Beispiel.

**Comment by mcuiobroker** [comment]
`v3.1.0-beta.22`

`{"true":"'{0_userdata.0.forum.activeNum}'"}` wird nicht mehr umgesetzt.

![image](https://user-images.githubusercontent.com/84818934/202043590-ac7f77ce-3e3a-4141-8bcc-e170c6db2f2e.png)

**Comment by Bernd9000** [comment]
Beispiel:
Testschalter10 hat zwei Datenpunkte  "status" und "power"
"status" hat die Werte "Online" oder "Offline" / power die Werte "true" oder "false"
Schalter wird grün für eingeschaltet, rot für ausgeschaltet.
Icon soll gelb blinken wenn status = Offline
Der untere Schalter dient zum Test und schaltet den status um

Hier funktioniert es richtig (Version 3.0.15)
![Animation1](https://user-images.githubusercontent.com/77005685/202144978-7a420586-6fe2-4bcb-ae40-ce15210b4c37.gif)

Und hier in der `v3.1.0-beta.22` funktioniert es nicht.
Erst wenn ich das Popup aufrufe wird der Status angezeigt.

![Animation2](https://user-images.githubusercontent.com/77005685/202144987-4528eaac-12cc-4b55-a8bd-f24bce0bade6.gif)


"b950c530-5728-43d7-a9ad-38ef0573c064": {
    "name": "Testschalter-10",
    "icon": "",
    "label": "",
    "function": "_defaults",
    "states": {
      "status": {
        "stateKey": "status",
        "showState": true,
        "state": "0_userdata.0.Test.Testschalter10.status"
      },
      "power": {
        "stateKey": "power",
        "showState": true,
        "state": "0_userdata.0.Test.Testschalter10.power",
        "icon": {
          "'{0_userdata.0.Test.Testschalter10.status}'='Offline'": "pump blink",
          "true": "pump",
          "false": "pump"
        },
        "iconStyle": {
          "'{0_userdata.0.Test.Testschalter10.status}'='Offline'": {
            "color": "#FF0"
          },
          "true": {
            "color": "#0F0"
          },
          "false": {
            "color": "#F00"
          }
        }
      }
    },

**Comment by Zefau** [comment]
schaut nochmal bitte mit `v3.1.0-beta.23`

**Comment by Bernd9000** [comment]
Ja, bei mir gehts auch wieder.
