### ISSUE TITLE
v3.1.0-beta.24 Fehler Datenpunkt-Eigenschaft function

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2056]
![image](https://user-images.githubusercontent.com/84818934/202316592-22c34334-41ee-424b-a2c1-b0cd3da64b1b.png)

![image](https://user-images.githubusercontent.com/84818934/202316793-f21c112c-ee7c-48ef-873a-03216657edeb.png)

![image](https://user-images.githubusercontent.com/84818934/202316847-c5265b3c-5359-4646-bbf8-53afd9647d2d.png)

- [ ] GeräteID in die Warnung?

![image](https://user-images.githubusercontent.com/84818934/202316958-f68fc86e-3c12-4762-a32d-a18c60bbeb70.png)

**Comment by Zefau** [comment]
Schau bitte nochmal mit `v3.1.0-beta.25`.
