### ISSUE TITLE
v3.1.0-beta.24 Keine HistoryGraph-Anzeige mit Datenpunkt Eigenschaft incl. function substr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2057]
`{"value":"val => String(val).substr(0,4)+'<sup>'+String(val).substr(4,1)+'</sup>' + ' €'"}`

Nehme ich diese Funktion raus, so wird der HistoryGraph angezeigt.
Keine Fehlermeldung im console.log.

Wieso wird es dadurch überhaupt beeinflusst? Für den Graphen holt er doch nur den DP, oder?

![jarvis-v310-beta24 -Fehler Kein HistoryGraph bei DP Eigenschaften value](https://user-images.githubusercontent.com/84818934/202519406-ff74b633-4b3b-45ed-8873-dd6945f9da4e.gif)

**Comment by Zefau** [comment]
Hm Mist. Die Funktion wird genutzt um Werte zu manipulieren, analog zum konfigurierbaren Callback

Muss ich eine Option im HistoryGraph reinnehmen

**Comment by Zefau** [comment]
Schau bitte nochmal mit `v3.1.0-beta.25`.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/202567916-5b69ee57-7c96-46ff-bdc5-66cc48a3a27d.png)
![image](https://user-images.githubusercontent.com/84818934/202567961-c52c1478-d5af-45d3-b61b-9870b6283a00.png)

**Comment by Zefau** [comment]
`v3.1.0-beta.26`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/202572073-6c7d42e1-f478-46d9-ba4a-8317a581f00f.png)

**Comment by Zefau** [comment]
oh man :-D

**Comment by Zefau** [comment]
`v3.1.0-beta.27`

**Comment by mcuiobroker** [comment]
Passt jetzt. Danke.
Aber auch hier kein automatischer Reload mit rotem Info-Popup.

**Comment by MarkSau** [comment]
@Zefau Ich habe diesen Fehler auch bei mehreren Graphen..allerdings nicht bei allen, denke ich. Allerdings auch noch mit beta.28

![image](https://user-images.githubusercontent.com/22911084/202865897-89df7a4e-98d5-48aa-b366-f4126901c110.png)

**Comment by Deanna4711** [comment]
@mcuiobroker   Danke für den Hinweis. Ich hatte nach issues gesucht, aber wohl nicht gründlich genug. Ich hoffe, dieser Log ist der richtige...
![1](https://user-images.githubusercontent.com/33905778/202870165-10c14b5b-f697-4858-95c0-21bdb009535b.jpg)
![2](https://user-images.githubusercontent.com/33905778/202870187-6b9ea6d5-a2b9-41ab-8a11-724036c64018.jpg)

**Comment by mcuiobroker** [comment]
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/3333

**Comment by mcuiobroker** [comment]
Hab ich jetzt auch?
![image](https://user-images.githubusercontent.com/84818934/202918658-664e6999-5ed7-4f9c-8cd8-3e9a5f56769d.png)

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.0-beta.29`

**Comment by Deanna4711** [comment]
> schaut nochmal mit `v3.1.0-beta.29`
Also mit der Beta 31 sieht es bei mir wieder schick aus. 
![Screenshot 2022-11-20 233359](https://user-images.githubusercontent.com/33905778/202929966-801f7c9f-7c14-4bda-b21b-dc8f8376a33b.jpg)
