### ISSUE TITLE
3.1 B27: Fehler beim "Geräte Importieren"

### ISSUE THREAD

**Issue by Sineos** [Zefau/ioBroker.jarvis#2058]
Nach Druck auf "Read Adapters" bleibt der Dialog mit dem Kreisel hängen. In der Console:

![image](https://user-images.githubusercontent.com/4459312/202656569-afae8732-d1c1-455f-b909-b49e881fc284.png)

[console-export-2022-11-18_9-26-35.txt](https://github.com/Zefau/ioBroker.jarvis/files/10039512/console-export-2022-11-18_9-26-35.txt)

**Comment by Zefau** [comment]
Scheitert an der Struktur im MQTT Baum. Kannst das mal screenshoten?

**Comment by Zefau** [comment]
bitte schau nochmal mit `v3.1.0-beta.28`

**Comment by Sineos** [comment]
Gleiches Verhalten mit B28

Screenshot mqtt:

![image](https://user-images.githubusercontent.com/4459312/202842165-e4adebfe-1330-40f5-a86e-769864447c02.png)

**Comment by Zefau** [comment]
Zigbee2mqtt musst du in einem eigenen Baum haben dann kannst du den Importer dafür nutzen. 

Kannst du mir nochmal den Konsolen Export ziehen? Der Fehler müsste ein anderer sein.

**Comment by Sineos** [comment]
> Zigbee2mqtt musst du in einem eigenen Baum haben dann kannst du den Importer dafür nutzen.

Stimmt. Bisher einfach nicht aus MQTT rausgeworfen

> Kannst du mir nochmal den Konsolen Export ziehen? Der Fehler müsste ein anderer sein.

[console-export-2022-11-19_11-5-7.txt](https://github.com/Zefau/ioBroker.jarvis/files/10046692/console-export-2022-11-19_11-5-7.txt)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.29`

**Comment by Sineos** [comment]
B31 gleiches Verhalten:

[console-export-2022-11-21_13-4-12.txt](https://github.com/Zefau/ioBroker.jarvis/files/10056324/console-export-2022-11-21_13-4-12.txt)

**Comment by Zefau** [comment]
in dem Log ist eine Stelle:
```
Uncaught (in promise) 
Object { … }
```

Kannst du dort das `Object` noch weiter aufklappen?

Findet sich ziemlich am Ende nach 
```
Retrieved results from adapter zigbee2mqtt: 
Array(33) [ {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, … ]
index-9a251ba4.js:5:229
Retrieved results from adapter zwave2: 
Array []
index-9a251ba4.js:5:229
Parsed devices from zwave2: 
Array []
```

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.32`

**Comment by Sineos** [comment]
![image](https://user-images.githubusercontent.com/4459312/203240821-d74d89d8-a2da-4017-bbec-f367afb1d202.png)

[console-export-2022-11-22_7-15-29.txt](https://github.com/Zefau/ioBroker.jarvis/files/10064523/console-export-2022-11-22_7-15-29.txt)

Keine Ahnung ob es was hilft:
* Der Übeltäter ist "Das Wetter"
* Selektiere ich alles außer "Das Wetter" funktioniert es
* Ist nur "Das Wetter" selektiert kommt der Fehler

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.33`
