### ISSUE TITLE
Bug: State / Tab moving

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#206]
https://forum.iobroker.net/assets/uploads/files/1602912739240-jarvis.gif

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/504659

**Comment by duczz** [comment]
Edit: State moving is only not visible on Layout modifying Tab, but when you save it it works on Vis Layout

This is not working for the Topbar moving, this still not possible

**Comment by Zefau** [comment]
@duczz offtopic: How did you create the animated gif?

**Comment by duczz** [comment]
ScreenToGif ;)

**Comment by Zefau** [comment]
@duczz Could you check if this issue has been resolved with `1.1.0-beta.38` ?

**Comment by duczz** [comment]
It works now, Thanks
