### ISSUE TITLE
v3.1.0-beta.28 Verschieben von Widget klappt nicht bzw wird nicht korrekt angezeigt?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2060]
Die Widgets werden ausgeblendet, sind aber nicht auf dem neuen TAB? (War noch nicht gespeichert) ?
![image](https://user-images.githubusercontent.com/84818934/202855691-56ee70a0-c1bc-4261-b88f-65c337c985cd.png)

Es wird nichts angezeigt
![image](https://user-images.githubusercontent.com/84818934/202855751-fae8d6d3-e820-46c0-94d6-acc3282357e5.png)

Speichern und zurück

-> Werden aber umgesetzt.
![image](https://user-images.githubusercontent.com/84818934/202855799-83abd164-0c3f-46b1-b842-76aa4803dd75.png)

![image](https://user-images.githubusercontent.com/84818934/202855820-bef614bc-d43d-4ecb-86a5-26dfac68ff18.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-beta.29`

**Comment by mcuiobroker** [comment]
Passt. Danke.
