### ISSUE TITLE
v3.1.0-beta.28 Callback (PRO) Editor fehlt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2061]
![image](https://user-images.githubusercontent.com/84818934/202856005-3975f796-1754-4603-b7a9-e6230ef35a6f.png)

![image](https://user-images.githubusercontent.com/84818934/202855991-345755cf-8ca9-4431-b89a-e82bee714b47.png)

**Comment by Zefau** [comment]
Ist kein JSON Feld, daher kein JSON Editor.

**Comment by Zefau** [comment]
Die beispielhafte Eingabe von dir dort ist falsch.
