### ISSUE TITLE
v3.1.0-beta.31 HistoryGraph formatter - keine °C Anzeige

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2063]
[
  {
    "position": "right",
    "name": "Büro",
    "nameLocation": "center",
    "min": "dataMin",
    "max": "dataMax",
    "axisLabel": {
      "formatter": "{value} °C",
      "margin": 25
    }
  }
]

![image](https://user-images.githubusercontent.com/84818934/203133864-87f04f8a-0f6f-4ea9-8bf2-86cdd04dc630.png)

![image](https://user-images.githubusercontent.com/84818934/203133951-7135bb1c-d20f-4626-b867-1a08a10bc358.png)

**Comment by Zefau** [comment]
`v3.1.0-beta.32`

**Comment by mcuiobroker** [comment]
Passt. Danke.
