### ISSUE TITLE
v3.1.0-Beta.31: CPU Leistung nach Tab wechsel hoch

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#2068]
Mir ist aufgefallen, dass die CPU- Leistung nach einem Reload (F5) von Jarvis kurze Zeit hoch auf ca. 25% geht und dann wieder runter bis auf 0% (im Tab Dashboard). Wechsele ich jetzt zu einem beliebigen anderen Tab geht die CPU Leistung bis auf ca. 35% hoch und geht dann aber nicht mehr zurück, Sie bleibt dann auf dem hohen Wert auch wenn ich wieder zum Dashboard zurück wechsele. 

![Animation](https://user-images.githubusercontent.com/77939385/203409117-6d6321b8-6354-43b9-9983-3561dcfa2551.gif)

Mache ich einen Reload aus einem anderen Tab als dem Dashboard bleibt die CPU- Leistung auch hoch und geht nicht zurück.

Bei dem Test war im Firefox nur Jarvis offen!

**Comment by mcuiobroker** [comment]
Bindings in den TABs oder Seiten Body Styles?

**Comment by hosabeni** [comment]
> Bindings in den TABs oder Seiten Body Styles?

Nein, habe ich nicht.

**Comment by Zefau** [comment]
Also CPU Leistung im Firefox wenn du durch Webseiten navigierst wirst du auf jeder Website haben, nicht nur bei jarvis.

Welche Widgets hast du denn in den Tabs, die die CPU Last erzeugen?

**Comment by hosabeni** [comment]
> Also CPU Leistung im Firefox wenn du durch Webseiten navigierst wirst du auf jeder Website haben, nicht nur bei jarvis.
>
Das ist richtig. 
Ich finde es nur auffällig, dass die CPU Leistung nach einem Reload beim Dashboard auf 0% zurück geht und bei den andern Tabs nicht. Auch das nach dem wechseln vom Dashboard auf einen andern Tab die CPU Leistung nach einer Zeit nicht wieder zurück geht auch nicht nach 5 Minuten ohne etwas anzuklicken.

> Welche Widgets hast du denn in den Tabs, die die CPU Last erzeugen?
>

Dashboard:
- DateTime
- 2x StateList
- Weather
- Calandar
- 2x Chart

In dem Tab aus dem Gif:
- 2x StateList

**Comment by mcuiobroker** [comment]
Im Video ist zu erkennen, dass dort 2 Elemente die blauen Ladelinien haben. Sind das die 2x Charts?
![image](https://user-images.githubusercontent.com/84818934/203420567-93fa2026-b5a0-4403-b62e-6f18015d7350.png)

**Comment by hosabeni** [comment]
Das sind zwei LevelBoys in dem Tab AUSSEN in einer der beiden StateLists.
Die Charts sind im DASHBOARD und nicht sehen.

**Comment by Zefau** [comment]
Was hast du denn für Datenpunkte in den StateLists und wie oft werden die durch ioBroker aktualisiert? Sind da ggf. Datenpunkte dabei, die (mehrfach) in der Sekunde aktualisiert werden?

**Comment by hosabeni** [comment]
Ich habe das Problem eben etwas genauer analysiere und herausgefunden, dass das Verhalten bei Tabs auftrat bei den Rollladen mit einem BlindLeveAction hinterlegt waren. Die BlindLeveAction hatte ich versehentlich bei `Datenpunkt Aktivität` mit einem Datenpunkt vom Typ `number` verbunden. Als die entsprechend entfernt hatte, hat sich die CPU- Leistung normal verhalten.


![Image](https://user-images.githubusercontent.com/77939385/203636706-36cad4fd-afe0-4d05-a634-ed23cfe601ef.png)

Eventuell könnte hier eine Fehlermeldung in der Konsole kommen um das in Zukunft leichter zu erkennen.

**Comment by Zefau** [comment]
sehr stark! Da werde ich mal schauen, ob ich den Fehler im Quellcode direkt beheben kann. Danke für die Analyse.

**Comment by Zefau** [comment]
Kannst du mir mal die Konfiguration durchgeben, mit der die hohe CPU Last entstanden ist, damit ich es nachstellen kann?

**Comment by hosabeni** [comment]
Im Prinzip kannst du ein neues Gerät vom Gewerk `Rollladen/ Jalousie` erstellen und dann die Standard Datenpunkte anlegen. Den Punkt `level` mit einem Datenpunkt vom Typ `number` verbinden und im `BlindLevelAction` den Datenpunkt Aktivität auf `level` stellen.


![Image](https://user-images.githubusercontent.com/77939385/203858046-0ac3bd95-1587-4fec-9ba3-bb469cf1e91d.png)


Wenn du jetzt den `BlindLevelAction` in einem Tab darstellst geht die CPU Leistung hoch und bliebt dann auch hoch.
Ich hoffe das hilft dir.

**Comment by Zefau** [comment]
Ich kann es zwar damit nachstellen, aber alle meine Bemühungen es einzugrenzen laufen irgendwie ins Leere.
Generell habe ich eine Grundlast von einigen Prozentwerten im Firefox.

Schau bitte nochmal mit `v3.1.0`, ob es bei dir besser wird.

**Comment by Bernd9000** [comment]
Ich habe eventuell wohl das selbe Problem.
Habe eben von Beta.28 mal auf die Final 3.1.0 aktualisiert.
jarvis ist bei mir extrem träge geworden, bei den etwas komplexeren Seiten dauert es fast eine halbe Minute bis die Seite vollständig aufgebaut ist, man kann zuschauen wie die einzelenen Elemente gezeichnet werden.
Alle Browser sind betroffen.
Wie immer nach jarvis Aktualisierung folgende Schritte durchgeführt: IOB upload jarvis, iob neustart, Browser cache gelöscht.
Was mir auf den ersten Blick auffällt:
1.) Die CSS Styles greifen nicht mehr.
2.) Farbänderung der SwitchAction durch Binding (Icon Stil) greift nicht mehr.

Im Browserlog keine Auffälligkeiten bis auf die langen Prüfzeiten:

App Time - Got Devices, Layout and Widgets: 3608.00ms index-f7d919a5.js:95:591402
App Time - Got Config, Adapter, Scripts: 4988.00ms index-f7d919a5.js:95:592533
App Time - Verified installation: 4991.00ms

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.1`

**Comment by Bernd9000** [comment]
Ja, Geschwindigkeit ist hier wieder Top.
@hosabeni ?
