### ISSUE TITLE
attributes nicht mehr da?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2069]
Werden die attributes nicht mehr genutzt?
![image](https://user-images.githubusercontent.com/84818934/203632723-13ac552a-50ce-4301-8c32-669380f9b11b.png)

Neues Gerät
![image](https://user-images.githubusercontent.com/84818934/203632864-526fc7b2-9ea9-44d2-9f3b-0a66cbcd94ba.png)

**Comment by Zefau** [comment]
Finde dazu nichts im Quellcode von v3.1 oder v3.0. Habe ich scheinbar von v2.x auf v3.0 rausgeworfen.

**Comment by mcuiobroker** [comment]
Wäre es nicht sinnvoll für alle Elemente die attributes zu setzen? (devices, widgets, layout)
Dann köntte man evtl. nachschauen, was man wann verändert hat. -> Feature

**Comment by Zefau** [comment]
`v3.1.0-beta.35`

**Comment by mcuiobroker** [comment]
Bei den Widgets hat er _created angelegt statt _updated
Widget war schon da. Nur dense geändert.
![image](https://user-images.githubusercontent.com/84818934/203654794-f17dce8a-4e92-4a83-b158-b49f49c10c89.png)
Sonst. Prima. Danke.

**Comment by Zefau** [comment]
`v3.1.0-beta.36`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/203870326-58d615e7-a2f0-431c-a40c-933b680561c4.png)

Widget ist schon vorhanden gewesen, kommt aber als created rein?
Prüftst du, ob es ein created gibt und wenn ja, dann updated?
Ja scheint so zu sein.
![image](https://user-images.githubusercontent.com/84818934/203870547-e07783ab-626e-4452-910a-9fd011848a82.png)
Man denkt dann man hätte das Widget erst gerade angelegt, obwohl es noch aus alten Zeiten schon da war, unglücklich oder?

**Comment by mcuiobroker** [comment]
Sonst lassen wir es so es fällt sowieso nur mir auf. Danke.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0`

**Comment by mcuiobroker** [comment]
Passt Danke.
