### ISSUE TITLE
v3.1.0-beta.35 Speicherung der Änderungen läuft teilweise nicht 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2070]
Habe schon seit einigen Version den Eindruck, dass bestimmte Dinge nicht gespeichert werden.
Es ist aber nicht reproduzierbar.
Wiederholt man es so wird es gespeichert.

Beispiel
Auswahl eines Gerätes über die Suche. Hat man es ausgewählt und ändert irgendetwas, speichert es und geht zurück.
Öffnet man dann wieder die Konfiguration, ist das die Suche vom Gerät nicht mehr da, sondern die davor.

Layoutänderungen werden teilweise nicht gepeichert.
Hinzufügen eines Widgets. Ausfüllen der Daten und Speichern und Beenden. -> Es wird nicht angezeigt.
Wiederholt man es, genauso wie vorher. -> es wird gepeichert und angezeigt.

Da wir ja jetzt die updated und created haben, könnte man es ja nachvollziehen. Nein, es werden diese Werte nicht gespeichert, da die Änderungen grundsätzlich (in dem Moment)  nicht gespeichert wird.

GIF

![jarvis-v310-beta35 Fehler Speicherung](https://user-images.githubusercontent.com/84818934/203858983-2d863512-32dd-4200-9119-baded7fbadee.gif)

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.4`
Das sollte kein Voting Feature sein. Es ist ein immer häufiger auftretendes Problem, so dass man die Änderungen mehrfach machen muss.

**Comment by Zefau** [comment]
Ich vermute es hängt mit dem Reload zusammen (wegen der Skripte), der ggf. zu früh passiert, bevor vollständig gespeichert wurde?

**Comment by mcuiobroker** [comment]
Das würde bedeuten, wenn man erst `Speichern` klickt und dann erst `Speichern+Zurück  dürfte das nicht mehr auftreten?

**Comment by Zefau** [comment]
Beobachte das gerne nochmal komplett mit `v3.1.3-beta.12`. Damit sollte es nun (hoffentlich) nicht mehr auftreten.

**Comment by Zefau** [comment]
Bisher alles sauber? :-)

**Comment by mcuiobroker** [comment]
Ja. Muss ich noch weiter beobachten. Können ja zu machen und bei Bedarf wieder öffnen.

**Comment by mcuiobroker** [comment]
Habe wieder das Problem gehabt mit `v3.1.3-beta.17`.
Er hat die Einstellungen zur Anzeigevariante nicht gespeichert.

**Comment by mcuiobroker** [comment]
v3.1.4-beta.xx
Speicherung bei Änderungen vom Layout werden nicht immer gespeichert.
Auch Änderungen bei Scripts.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.6` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.6` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Auch mit v3.2.0-alpha.11 nicht behoben.

**Comment by mcuiobroker** [comment]
Sieht gut aus. Danke.
