### ISSUE TITLE
v3.1.0-beta.35 SwitchAction Icon nur mdi-Icons?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2071]
In den Komponenten-Eigenschaften zur SwitchAction wird das Icon angezeigt, aber nicht im Frontend.

`line-md:downloading-loop`

![image](https://user-images.githubusercontent.com/84818934/203804974-d3b45872-47fa-4436-b1ee-3bffb8632c48.png)

![image](https://user-images.githubusercontent.com/84818934/203805133-ee8b76fa-67d4-48c8-a05c-29eb6cff7fac.png)

![image](https://user-images.githubusercontent.com/84818934/203804884-9ed50958-a6b4-47ad-80c9-88e4468f56f4.png)

**Comment by Zefau** [comment]
https://github.com/quasarframework/quasar/issues/11958

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/204113917-adb95fc9-4a7b-4e8d-8b89-ff0c2f54ad7e.png)

**Comment by Zefau** [comment]
Ist von mir. Geht es denn?

**Comment by mcuiobroker** [comment]
Nein.
![image](https://user-images.githubusercontent.com/84818934/204137765-1365a62c-492e-4c64-b08f-bee7dcbbeb2d.png)

**Comment by Bernd9000** [comment]
Gibts vielleicht auch ein Positionsproblem ?
Hier werden Sie neben dem SwitchAction angezeigt.
![Animation2](https://user-images.githubusercontent.com/77005685/204212730-e880a10c-fe7b-43d1-ad7e-aa8bbe545b62.gif)

**Comment by mcuiobroker** [comment]
Bei mir nicht? `v3.1.2`
![image](https://user-images.githubusercontent.com/84818934/204213675-699cbfae-2da5-4a26-9062-4ef50061e485.png)
![image](https://user-images.githubusercontent.com/84818934/204213716-5ea6ef15-1761-4dda-9a61-6d9f29647a11.png)

**Comment by Bernd9000** [comment]
Merkwürdig, an den CSS Styles liegt es nicht, die hab ich mal testweise rausgenommen.

**Comment by mcuiobroker** [comment]
`iob upload jarvis`?

**Comment by Bernd9000** [comment]
Hängt vom Icon ab, hab das `Home` Icon in deinem Beispiel genommen und dann wird es richtig gezeichnet.
Das `lamp` Icon wird außerhalb gezeichnet.

**Comment by mcuiobroker** [comment]
Ist `lamp` ein mdi-Icon?

**Comment by Bernd9000** [comment]
Weiß ich jetzt gar nicht, hab willkürlich entschieden.
Es könnte also sein das `line-md:downloading-loop` funktioniert aber so weit außerhalb gezeichnet wird das es nicht sichtbar ist ?

**Comment by mcuiobroker** [comment]
Sieht so aus, als ob es gar nicht integriert wird.
![image](https://user-images.githubusercontent.com/84818934/204216870-3bf64575-4240-4386-bbc3-33ac2e8a1f75.png)

**Comment by Bernd9000** [comment]
`mdi:lamp`

![Unbenannt](https://user-images.githubusercontent.com/77005685/204217520-0c99983a-04fb-4d8d-be59-2e6b8eb53937.jpg)

**Comment by mcuiobroker** [comment]
`lamp` wird auch bei mir verschoben
![image](https://user-images.githubusercontent.com/84818934/204219954-73baa45a-360b-4ae8-95b0-fa0a25b52204.png)

**Comment by Bernd9000** [comment]
@Zefau 
Der Versatz ist Abhängig von der Anzahl Zeichen vor dem Doppelpunkt.
Das heißt die Trennung mit dem Doppelpunkt funktioniert wohl nicht richtig.

**Comment by Bernd9000** [comment]
Warscheinlich darf der Gruppenname `mdi` hier aktuell gar nicht angegeben werden.
`lamp` gehört jedenfalls auch zu `mdi` aber damit funktioniert es nicht

**Comment by mcuiobroker** [comment]
schlecht zu sehen, funktioniert aber.
![image](https://user-images.githubusercontent.com/84818934/217689722-7d13785c-cc17-4cab-ac92-384a21d10a1b.png)
`img:https://api.iconify.design/line-md/downloading-loop.svg`
![jarvis v313-beta30 loop-Icon](https://user-images.githubusercontent.com/84818934/217689583-8e857047-6abe-4d95-a0e5-8266b27535cd.gif)

**Comment by Zefau** [comment]
Es funktionieren nun auch normale Icons wie `line-md:downloading-loop` (vgl. Post 1 dieses Threads)

**Comment by mcuiobroker** [comment]
Das mit der Farbanpassung solltest du aber schon noch integrieren. Danke
