### ISSUE TITLE
v3.1.0-beta.36 Fehler bei Seitenauswahl

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2073]
Aber auch nur von Seite 1 auf Seite 2. Alle anderen Seiten, oder auch von Seite 3 auf Seite 2, funktioniert ohne Probleme.

![image](https://user-images.githubusercontent.com/84818934/204063436-8e0f8eb8-5885-47da-9027-a315e03c54f7.png)
![image](https://user-images.githubusercontent.com/84818934/204063543-4de7729e-9b94-45e6-842e-6a16b8e57265.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0`

**Comment by mcuiobroker** [comment]
Passt. Danke.
