### ISSUE TITLE
v3.1.0 Custom CSS wird nicht geladen

### ISSUE THREAD

**Issue by patrickbs96** [Zefau/ioBroker.jarvis#2074]
Seit dem Update auf v3.1.0 werden meine CSS Anpassungen nicht mehr geladen.
Mit der v3.1.0-beta.35 hat es noch funktioniert.

Den Browsercache habe ich vorsichtshalber einmal gelöscht aber ohne Erfolg.

In der Konsole sehe ich nur das hier:
![image](https://user-images.githubusercontent.com/49351462/204135034-29291c2d-8ec2-4488-a303-37b5198437e5.png)

**Comment by somansch** [comment]
Ich habe nach dem Update von Beta 15 auf v3.1.0 auch Probleme mit den CSS Anpassungen. Einige funktionieren noch, aber andere (sehr wichtige) leider nicht mehr, z.B.:

`/* Schriftgröße aller StateLists primary ActionKey */

.jarvis-StateListItem-Action-primaryStateKey {
	font-size: 20px !important;
}

/* Schriftgröße aller StateLists Bodys */

.jarvis-StateListItem-Body {
	font-size: 20px;
}

/* Schriftgröße aller DropDownAction */

.jarvis-page-container .q-field__control-container {
	font-size: 20px;
}

[role="option"] {
	font-size: 20px;
}`

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.1`

**Comment by mcuiobroker** [comment]
`v3.1.1`
Auch html in `Anzeigevariante` wird nicht mehr umgesetzt.
```
{"false":"<span class='wifi-off'> </span>","true":"<span class='wifi-on'> </span>"}
```
Styles
```

.wifi-off {
	display: inline-block;
	width: 1em;
	height: 1em;
	vertical-align: -0.125em;
	color: #1976d2;
	background: url('https://api.iconify.design/mdi/wifi-off.svg?color=lightblue') no-repeat center center / contain;
}

.wifi-on {
	display: inline-block;
	width: 1em;
	height: 1em;
	vertical-align: -0.125em;
	color: yellow;
	background: url('https://api.iconify.design/mdi/wifi.svg?color=yellow') no-repeat center center / contain;
}
```

**Comment by Zefau** [comment]
`3.1.2-beta.0`

**Comment by mcuiobroker** [comment]
Bei mir läuft es mit der Anzeigevariante wieder.

**Comment by patrickbs96** [comment]
Bei mir klappt es jetzt auch wieder, danke 👍🏻

**Comment by Zefau** [comment]
super, danke euch für das schnelle Feedback
