### ISSUE TITLE
Icon Style Logic ( different Colors ) is not being reflected if an "Action State" in Widget is set

### ISSUE THREAD

**Issue by sir0drake** [Zefau/ioBroker.jarvis#2077]
**Prerequisites / Voraussetzungen**
- [ (v3.0.15)  Non-Pro ]

If i add json-logic in "Devices-Item" like 

Icon (JSON Format)
{">0<=10":"mdi:thermometer-minus",">10<=20":"mdi:thermometer-low",">20":"mdi:thermometer-plus"}
Icon Style (JSON Format)
{">0<=10":{"color":"#18E5E8"},">10<=20":{"color":"#FFE033"},">20":{"color":"#E81818"}}
i am expecting a colored icon depend on Value ( here selected temperature of slider ) .

But standard grayed icon is shown.
reason is in "Widget -> Action State" if  different node/item "Action State" is set.
If i remove the additional State and let them empty, all is fine.

Color will be set to the standard icon.

Screenshots attached

brgds

![2022_11_28_Not_working_Widget](https://user-images.githubusercontent.com/77205165/204260971-3918b652-b3ae-4087-b75e-2551f5adca4d.png)
![2022_11_28_working_Widget](https://user-images.githubusercontent.com/77205165/204260977-0e6904a2-3c25-43b3-a7f4-d5728e5fec14.png)

![2022_11_28_devices_json_logic](https://user-images.githubusercontent.com/77205165/204260978-797ce099-7c7d-46eb-bf3f-ad4707098a9b.png)

![2022_11_28_Not_working_Action_State](https://user-images.githubusercontent.com/77205165/204260974-7336e9f0-d9f0-4e95-be36-97fb0d94d71c.png)

**Comment by mcuiobroker** [comment]
The binding is wrong.
Where did you find this example?

Icon
```
{"<=10":"mdi:thermometer-minus","<=20":"mdi:thermometer-low",">20":"mdi:thermometer-plus"}
```
Icon-Color
```
{"<=10":{"color":"#18E5E8"},"<=20":{"color":"#FFE033"},">20":{"color":"#E81818"}}
```

**Comment by sir0drake** [comment]
hi mcuiobroker,

have no idea where i found it as an example.
probably somewhere on the net.

will try to fix it and make test.
will response here.

thanks

**Comment by mcuiobroker** [comment]
But this won't solve the problem.

**Comment by sir0drake** [comment]
yes,
you are right.
i can cleanup the problem you found,
but it did not solve my problem.
thanks for helping !

**Comment by Zefau** [comment]
Works for me?

LAYOUT

![grafik](https://user-images.githubusercontent.com/14368811/215261810-ae46ab29-0391-4739-9ef5-1d6dd9f075cc.png)

DEVICE

![grafik](https://user-images.githubusercontent.com/14368811/215261834-5aa7374b-ba6d-4667-8bf7-87e84a2522fd.png)


RESULT

![grafik](https://user-images.githubusercontent.com/14368811/215261839-b2ea334f-2cc3-4beb-b40a-6e9c70cd0936.png)

**Comment by Zefau** [comment]
Probably fixed via https://github.com/Zefau/ioBroker.jarvis/issues/2179? Can you guys confirm?

**Comment by Zefau** [comment]
@sir0drake @mcuiobroker
