### ISSUE TITLE
Iobroker Update funktioniert nicht

### ISSUE THREAD

**Issue by BlackandGold1** [Zefau/ioBroker.jarvis#2078]
$ iobroker upgrade jarvis@3.1.0
Update jarvis from @3.0.15 to @3.1.0
Installing iobroker.jarvis@3.1.0... (System call)
host.d239a7666dc8 Cannot install iobroker.jarvis@3.1.0: 217
ERROR: Process exited with code 25

Weiss wer wieso?

*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstel len zu können.

**Screenshots**
Sofern

**Comment by mcuiobroker** [comment]
V3.1.2 probieren 
Adapter -Expertenmodus - Katze - guthub - jarvis

**Comment by BlackandGold1** [comment]
Geht auch nicht.

$ iobroker url Zefau/ioBroker.jarvis --host d239a7666dc8 --debug
install Zefau/ioBroker.jarvis
Installing Zefau/ioBroker.jarvis... (System call)
host.d239a7666dc8 Cannot install Zefau/ioBroker.jarvis: 217
ERROR: Process exited with code 25

**Comment by Sineos** [comment]
Das ist ja eine NPM Fehlermeldung. Vielleicht eine verkorkste nodejs Installation?

**Comment by BlackandGold1** [comment]
Puh…keine Ahnung. Alle anderen Adapter wie Web, Alexa2 u.s.w konnte ich Updaten. Iobroker macht sonst keine Probleme.

**Comment by Zefau** [comment]
Deine Nodejs Version ist vermutlich zu alt für v3.1. Was hast du installiert?

**Comment by BlackandGold1** [comment]
d239a7666dc8 
Plattform:docker
Betriebssystem:linux
Architektur:x64
CPUs:4
Geschwindigkeit:2196 MHz
Modell:Intel(R) Celeron(R) CPU J3455 @ 1.50GHz
RAM:7.62 GB
System-Betriebszeit:12T:00:19:27
Node.js:v16.18.1
time:1669660150181
timeOffset
-60
Anzahl der Adapter
537
NPM
8.19.2

**Comment by mcuiobroker** [comment]
Console 
node -v

**Comment by BlackandGold1** [comment]
V 16.18.1

**Comment by Zefau** [comment]
v16 passt. Merkwürdig.

**Comment by Zefau** [comment]
https://forum.iobroker.net/topic/55683/kein-update-mehr-m%C3%B6glich-mit-node-js-16/172?lang=en-GB

**Comment by BlackandGold1** [comment]
Bin das mal durchgegangen aber leider hilft das nicht. Werde den Container mal löschen und es neu installieren.

**Comment by isi07** [comment]
villeicht hilft das
https://forum.iobroker.net/topic/57337/fehler-25-bei-adapter-install-update-mit-npm8

**Comment by BlackandGold1** [comment]
So mit dem letzten link hat es geklappt. Hab zwar keine Ahnung was ich da gemacht habe aber es hat geholfen.
Hab gleich auf der Console das Update starten und erfolgreich Updaten können.   Viele vielen Dank. Wirklich Traumhaft eure Hilfe macht weiter so :)
