### ISSUE TITLE
Premium plötzlich weg...

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#2079]
Hi, 

heute wurde via Paypal die Jahresgebühr abgezogen.
Dennoch ist das Pemium komplett weg auf allen Instanzen. Die Informationen im Premium TAB sind auch nciht mehr hinterlegt.  

Ist sehr mühsam. Da ich alles in der SeitenNavigation drin habe und jetzt nichts mehr Bedienen kann.

**Comment by ma-gu-16** [comment]
![image](https://user-images.githubusercontent.com/22169074/204327129-84279d63-f0c9-4f11-b52f-bc690c589a49.png)

Stimmt natürlich nicht.

**Comment by mcuiobroker** [comment]
Welche Vwrsion?Daten noch in Info.pro?

**Comment by ma-gu-16** [comment]
(v3.0.15)

**Comment by ma-gu-16** [comment]
ja in info.pro scheinen doch daten drin zu sein.

**Comment by Zefau** [comment]
Ich kümmere mich zeitnah heute Abend. Sorry für die Umstände.

**Comment by Zefau** [comment]
@ma-gu-16 die Rechnung und Lizenz sollte nun angekommen sein. Kannst du das bestätigen?

**Comment by isi07** [comment]
bei mir ist es gerade angekommen. Danke.

**Comment by Zefau** [comment]
dann m

**Comment by ma-gu-16** [comment]
Rechnung ist angekommen, musste dennoch manuell die Lizenz abrufen und aktivieren. 
Da die Einzugsermächtung bei Paypal auch automatisch funktioniert, sollte Premium m. E. aktiv bleiben. 

Gruss

**Comment by Zefau** [comment]
> Es sollte eine Not-E-Mail geben, wo geprüft wird, ob die Absender-E-Mail im System bekannt ist und dann eine Verlängerung um 1 Woche als Code schicken. Dann hat man Zeit den Vorfall zu klären.

Was?

Wenn ich die Zahlung von PayPal erhalte, dann wird eine Rechnung und Lizenz erstellt. Sofern bereits eine Lizenz vorhanden ist, wird diese verlängert. 
Ab v3.1 geht dies auch mittels Überweisung. Außerdem erfolgt ab v3.1 innerhalb von jarvis die Abfrage, ob eine neue Lizenz vorliegt, die dann übernommen wird. Das funktioniert aber mit v3.0 noch nicht. Also alle, die vor dem Upgrade die Lizenz aktualisieren, müssen diese leider noch manuell einpflegen.

**Comment by mcuiobroker** [comment]
Warum gab es denn das Problem, dass jemand keine Lizenz bekommen hat, obwohl bezahlt wurde?

**Comment by Zefau** [comment]
Gestern war Jahrestag für den Pro-Account. Also es war das erste Mal, dass jemand ein zweites Mal bezahlt hat.

Nützlicherweise (Ironie) hat PayPal dafür eine andere Struktur als für die erste / initiale Zahlung. Dadurch konnten Informationen nicht richtig zugeordnet werden und es konnte keine Rechnung ausgestellt werden.

**Comment by Bernd9000** [comment]
Gut, hab aber Heute das selbe Problem und kann nichts mehr machen.
Rechnung wurde zugestellt, Werte in Pro eingetragen, Lizenz Abruf funktioniert nicht,
Das ist Mist, daher finde ich den Vorschlag mit kurzfristiger Verlängerung richtig.
Kann hier nichts mehr steuern..... :-(
Hab per Mail zurück geschrieben......

**Comment by ma-gu-16** [comment]
hast du bei der "neuen" Paypal Rechnung die Subscription-Id:  + deine E-Mail verwendet? Zumindest hat das bei mir mit den beiden Funktioniert und ich habe 2 Lizensen zur Auswahl bekommen und konnte dann die neuere/gültige auswählen. 


Aber klar grundsätzlich denke ich auch das die Lizenz etwa 1 Woche länger laufen sollte und in dieser Woche täglich ein Cronjob prüft ob Zahlung eingegangen/valide und ob der Account auch entsprechend verlängert wurde. Damit der Enduser nix tun muss und lediglich die Mail von Paypal archivieren ;)

**Comment by Bernd9000** [comment]
Ja, bei mir ist die `subscriptionId` und `E-Mail` aber identisch mit der vom letzten Jahr.
Nur die `signature` und `invoiceId` hat sich geändert.
Ich muß mir aber noch irgendein Reserve System ausdenken.......krieg die Garage nicht auf :-(

Auffällig ist noch folgender Fehler:
![1](https://user-images.githubusercontent.com/77005685/204803418-7ec944ab-772e-47cd-8b9b-a464c0648dfd.jpg)

**Comment by ma-gu-16** [comment]
>  Ich muß mir aber noch irgendein Reserve System ausdenken.......krieg die Garage nicht auf :-(

Ja das dachte ich auch, wenn alles darauf aufbaut ist natürlich blöd.  Ich hab in meinem Fall via iobroker,oder homematic direkt gesteuert. bzw auch ein kleines script via javascript um etwas spezielles zu triggern.  Kann man natürlich den Gästen oder Familie nicht zumuten :D

**Comment by SlipKoRn88** [comment]
Schließe mich hier an. Abonement ist automatisch verlängert und per Paypal abgebeucht. Rechnung und Lizenz habe ich erhalten. Automatisch wurde die PRO Version nicht verlängert. Habe die Lizenz manuell eingetragen, aber dies funktioniert auch nicht.
Rufe ich in Jarvis die Lizenz ab, erhalte ich ebenso d.map is not a function.  Es wird kein Status der Lizenz darunter angezeigt.

**Comment by Zefau** [comment]
Entschuldigt bitte. Ich kümmere mich asap.

**Comment by Zefau** [comment]
Ich musste leider umfangreich Anpassungen in der Routine vornehmen, da die PayPal-Struktur stark unterschiedlich zwischen dem initialen und der aktualisierten Bezahlung ist. Die neue Lizenz wurde mit einer falschen Zeit ausgestellt, daher war diese direkt abgelaufen.

Ihr solltet parallel eine neue Rechnung inkl. neuer Lizenz erhalten haben. Die Storno-Rechnung kommt zeitnah (das muss ich erst implementieren).

Bitte bestätigt mir kurz, ob alles wieder wie gewohnt funktioniert.

Ab nächsten Jahr sollte das problemlos aktualisieren und auch automatisch im Datenpunkt hinterlegt werden.

**Comment by mcuiobroker** [comment]
Auch wenn du es jetzt erledigt hast, solltest du eine Möglichkeit (Not-Lösung) erarbeiten, wenn PayPal die Struktur mal wieder ändert und du nicht direkt eine Anpassung vornehmen kannst.

**Comment by Bernd9000** [comment]
Meine Rechnung ist angekommen, jarvis läuft.
Lizenz abruf funktioniert nicht.

**Comment by Zefau** [comment]
>  Lizenz abruf funktioniert nicht.

Bitte hier nochmal prüfen. Sollte jetzt gehen (21:57 Uhr).

**Comment by Bernd9000** [comment]
Jo, funktioniert
