### ISSUE TITLE
nach Update auf 3.1.x funktioniert Calendar nicht mehr (401)

### ISSUE THREAD

**Issue by luetty** [Zefau/ioBroker.jarvis#2082]
Hallo,
ich habe letzte Woche Jarvis auf 3.1.x upgedated, bin heute auf 3.1.2.
Seit dem aktualisiert sich der Kalender nicht mehr, laut log bekomme ich einen 401/ unauthorized zurück.

URL & Zugangsdaten mehrfach geprüft, login per Browser lädt die ics einwandfrei herunter.
Gerade ein Backup der VM, in eine Testinstanz, wiederhergestellt und dort klappt die Aktualisierung weiterhin (v3.0.15).

Hat noch jemand das Problem?

**Comment by Zefau** [comment]
Hast du das Passwort nochmal neu eingegeben?

**Comment by luetty** [comment]
Ja, hab ich - mehrfach. Das war zumindest meine erste Idee dazu. 
Was mich zudem wundert: Ich habe sogar das Widget gelöscht, alles gespeichert. Lege ich ein neues widget an, erscheinen aber sofort Kalendername, URL und Passwort. Ich vermute (vermute!!!) das da irgendwo ein altes schnipsel Config festhängt?

Per ical-Adapter mit selben Daten funktioniert es auch.

...ich bin verwirrt :-)

**Comment by Zefau** [comment]
Das Passwort wird verschlüsselt gespeichert. Kannst du mal prüfen, ob das der Fall ist? Also im Datenpunkt `jarvis.0.widgets` das Calendar-Widget raus suchen. Dort sollte das Passwort nicht lesbar drin stehen.

**Comment by luetty** [comment]
ja, ist nicht lesbar!

**Comment by Zefau** [comment]
Ok, das ist gut, da es korrekt ist. Das Passwort wird dann zur Laufzeit entschlüsselt und verwendet.

Hat dein Passwort irgendwelche speziellen Zeichen? Ggf. scheitert die Entschlüsselung in v3.1 daran. Hast du die Möglichkeit mit einem Kalender und einem "einfachen" Passwort zu testen?

**Comment by Zefau** [comment]
Notiz am Rande: Der Abruf der Kalender-Daten erfolgt im ioBroker backend (nicht im jarvis frontend).

Heißt also: Probier mal den Adapter neuzustarten, nachdem du das Passwort geändert hast.

**Comment by luetty** [comment]
Leider alles ohne Erfolg.
Benutzer und PW sind einfach, keinerlei Sonderzeichen (CALDAV-Service ist nur intern erreichbar)

**Comment by luetty** [comment]
Ich hab jetzt nochmal die o.g. Wiederherstellung eines 2 Wochen alten Backups hochgefahren. (jarvis 3.0.15)
Dort mal das verschlüsselte PW aus dem Datenpunkt entnommen und in den Produktions-DP übernommen. 
Gleiches schlechtes Ergebnis :-( Das dass nicht funktionieren muss ist mir klar, war aber ne Chance...
Alles, außer dem pw ist 100% ident, funktioniert in der Wiederherstellung, aber nicht in "Produktion".

Allerdings scheint der json-String in der neuen Version anders aufgebaut:

alt (3.0.15):
![image](https://user-images.githubusercontent.com/89082199/204675231-ed30e99c-ffb4-45c7-9ae7-510140fcfe8c.png)

neu (3.1.2):
![image](https://user-images.githubusercontent.com/89082199/204675159-956ee27b-a860-4bb3-89ce-3d29aa60239d.png)


Getestet wurde auch eine Änderung der Anmeldedaten auf caldav/ caldav (auf caldav-Service & jarvis) - was auch nicht funktionierte.

Danke für Deine Unterstützung, aber jetzt erstmal GuNa!

**Comment by luetty** [comment]
So, ich hab mal ein kleines PHP-Script verwendet um die Authentifizierung zu testen.
Der Benutzername wird korrekt übergeben, aber das Passwort ist leer! Irgendwo ist ein Loch :-( Mit caldav2022 ist mein PW nun auch nicht hochkomplex, sodass die Entschlüsselung keine Probleme haben sollte. :-)

**Comment by gingerXpat** [comment]
Das gleiche Problem habe ich auch, auch nur in Jarvis.

**Comment by bacclux** [comment]
Glleiches Problem nach dem Update auf die neue Version von Jarvis. Ich habe zwei Kalender, eine in Outlook und eine in Google und diese funktionieren noch immer mit ICAL in der iobroker VIS.

**Comment by Torrid16V** [comment]
Ich habe seit dem Update auf V3.1 das gleiche Problem.

**Comment by HolgerDo** [comment]
Ich habe leider auch mehrere Probleme mit dem Kalender. Vor dem Upgrade konnte ich schon nicht mehr auf meinen Google Kalender zugreifen - also noch vor 3.1 - daran seid ihr ja irgendwie :-) 
Nach dem Update habe ich nun Probleme mit unserem Müllkalender. Per Link [https://abfall.alzey-worms.de/WasteManagementAlzeyworms/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=8089270001&AboID=208146&Fra=R;R;B;P;L;S;C](url) aber auch als download ics 
[Leerungstermine190574.zip](https://github.com/Zefau/ioBroker.jarvis/files/10435477/Leerungstermine190574.zip)
es erscheint nun statt dem Müllgut [object Ojbect]

06:00-07:00, [object Object]
Di., 17.01., vor etwa 9 Stunden
06:00-07:00, [object Object]
Di., 17.01., vor etwa 9 Stunden
06:00-07:00, [object Object]
Mi., 18.01., in etwa 15 Stunden

![calendar](https://user-images.githubusercontent.com/17078568/212913232-a93c44a4-9280-4a21-b710-a228bdb83d9e.png)

**Comment by Zefau** [comment]
Schaut nochmal mit `v3.1.3-beta.12`. Auf `debug` sollte mehr im ioBroker.Log an Informationen zu sehen sein.

Die Warnung beginnt bei euch mit `Failed getting ical data for ...`, richtig?
Danach sollte nun im Debug-Log der `Request` stehen. Darin auch das entschlüsselte Passwort für euch zum Vergleich.

**Comment by flickerfrei** [comment]
Hi Zefau,
ich habe das Update gemacht. Mit dem Debug ist zu erkennen, dass das Passwort nicht gespeichert wird.
Ausgabe Log: .... "username": "xxx", "password": null, "https": { "rejectUnauthorized": true } }
Egal ob bei einem bestehenden Kalender oder bei Neuanlage.

**Comment by Zefau** [comment]
Kannst du mir paar Informationen zu deinem System geben? Node Version, Windows / Linux, etc.

Hattest du in der Ausgabe auch einen Eintrag `encryptionKey`? Könntest du mal ein beliebiges "Passwort" setzen (irgendein Wort) und mir die verschlüsselte Zeichenkette sowie den `encryptionKey` an ioBroker.jarvis@mailbox.org schicken?

Ich würde gern mal schauen, ob ich entschlüsseln kann, was dein System verschlüsselt hat.

**Comment by toobe4** [comment]
Ich habe auch genau dieses Problem. iCal Adapter funktioniert ohne Probleme, jarvis wirft den 401 Fehler.

**Comment by Zefau** [comment]
@toobe4 die Aussage bringt mir nicht viel. Wenn du den Thread gelesen hast, dann weißt du, welche Informationen ich brauche um den Bug zu beheben.

**Comment by Zefau** [comment]
@toobe4 vielen Dank für die Email und die Informationen!! Das hat geholfen. Schaut bitte nochmal mit `v3.1.3-beta.28`.

**Comment by toobe4** [comment]
@Zefau Kalender-Einträge werden jetzt angezeigt! Vielen Dank!!!

**Comment by gingerXpat** [comment]
Bei mir (3.1.2) werden die Kalendar einträge weiterhin nicht geladen. Der .ics wird im Browser ohne Probleme runtergeladen und auch im VIS. Credentials sind nicht notwendig für diese Freigabe. Ich verwende zurzeit "http://iobroker.live/repo/sources-dist-latest.json" als Repo und sehe 3.1.3 noch nicht. Wenn da ein Fix kommen soll, dann kann ich warten. Wollte aber Bescheid geben das es für mich weiterhin nicht funktioniert.

**Comment by flickerfrei** [comment]
Nachdem ich das Widget gelöscht und neu angelegt habe funktioniert es nun.

**Comment by gingerXpat** [comment]
Auch das löschen und nersertellen des Widgets hat leider auch nicht geholfen. Ich habe das logging jetzt hochgedreht und folgendes gefunden:

![image](https://user-images.githubusercontent.com/38500626/218312098-3f749a3f-addd-46c4-8a1d-5c110d868076.png)

Da Englisch meine Muttersprache ist sind ja auch viele Sachen bei mir auf Englisch konfiguriert. Nachdem ich den Fehler gesehen habe, dachte es könnte an mein Kalendar liegen. Dann habe ich aber den Kalendar von der Müllabfuhr, was ich auch für TrashSchedule nutze, probiert. Gleiche fehler.

Ich hoffe diese Info hilft um eine Lösung zu finden. Vor 3.0 ging alles ohne Probleme.

**Comment by Zefau** [comment]
@gingerXpat bist du auf 3.1.3? update via GitHub oder warten, bis im Latest Repo

**Comment by gingerXpat** [comment]
> @gingerXpat bist du auf 3.1.3? update via GitHub oder warten, bis im Latest Repo

Ich habe noch 3.1.2 und bin im Latest Repo:
![image](https://user-images.githubusercontent.com/38500626/218313178-a637b6d8-1879-4a69-8fb0-6b56e3637548.png)

**Comment by Zefau** [comment]
dann wie gesagt warten bis 3.1.3 ins latest geht

**Comment by gingerXpat** [comment]
@Zefau Ok, eben mit 3.1.3-beta.32 probiert. Gleiche Fehler kommt und Kalendar wird weiterhin nicht geladen.

**Comment by Zefau** [comment]
Dann setz im Calendar Modul bitte die Passwörter nochmal neu oder füge das Modul komplett neu hinzu.

**Comment by gingerXpat** [comment]
Der Kalendar ist eine Freigabe was kein Username/Password braucht. Dies wurde auch bestätigt indem ich der URL in ein Privat Browser Session eingegeben habe und der Kalendar sofart runtergeladen wird. Auch im iCal sind die Events sichtbar.

jarvis 3.1.3-beta.32:
1. "Calendar" Module/Widget gelöscht.
2. iCal Adapter neugestartert
3. "Calendar" Module neukonfiguriet als neue Widget

Gleiche ergebnis.

**Comment by Zefau** [comment]
Kannst du die URL teilen?

**Comment by gingerXpat** [comment]
https://outlook.live.com/owa/calendar/a266a69f-ffdb-4856-9913-190165bb7bf8/99724d4a-b48e-493b-b2d0-f4968ff84542/cid-ADB8FF69D0BFAAFE/calendar.ics

**Comment by Zefau** [comment]
Wird bei mir geladen:
![grafik](https://user-images.githubusercontent.com/14368811/218323475-2c216934-f9c7-450c-a3aa-7237d6d987aa.png)

Einstellungen:

![grafik](https://user-images.githubusercontent.com/14368811/218323459-28f96818-ff7a-42eb-9520-50c8e84a7845.png)

**Comment by gingerXpat** [comment]
Ok, jetzt habe ich das Problem gefunden. Wenn unter die Spracheinstellungen von jarvis Englisch ausgewäht ist, funktioniert es nicht. Jetzt habe ich das auf Deutsch geändert und mein Kalendar wird geladen. Wieder auf Englisch, refresh, wird nicht geladen. Zurück auf Deutsch, refresh, wird geladen. 

![image](https://user-images.githubusercontent.com/38500626/218325958-5499c9a6-2c86-4b2f-b6d3-2576fa964bc8.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.34`

**Comment by gingerXpat** [comment]
Mit 3.1.3-beta.34 sieht es gut aus! Alles wieder auf Englisch geschaltet, refresh gemacht, lädt ohne Probleme. Vielen Dank!

**Comment by Scheuerschrauber** [comment]
> Ich habe leider auch mehrere Probleme mit dem Kalender. Vor dem Upgrade konnte ich schon nicht mehr auf meinen Google Kalender zugreifen - also noch vor 3.1 - daran seid ihr ja irgendwie :-) Nach dem Update habe ich nun Probleme mit unserem Müllkalender. Per Link [https://abfall.alzey-worms.de/WasteManagementAlzeyworms/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=8089270001&AboID=208146&Fra=R;R;B;P;L;S;C](url) aber auch als download ics [Leerungstermine190574.zip](https://github.com/Zefau/ioBroker.jarvis/files/10435477/Leerungstermine190574.zip) es erscheint nun statt dem Müllgut [object Ojbect]
> 
> 06:00-07:00, [object Object] Di., 17.01., vor etwa 9 Stunden 06:00-07:00, [object Object] Di., 17.01., vor etwa 9 Stunden 06:00-07:00, [object Object] Mi., 18.01., in etwa 15 Stunden
> 
> ![calendar](https://user-images.githubusercontent.com/17078568/212913232-a93c44a4-9280-4a21-b710-a228bdb83d9e.png)

Muss mich hier leider anschließen, bekomme auch nur [object Object] als Inhalt eines Termins angezeigt. Witzigerweise wohne ich im gleichen Landkreis. Wenn ich den Termin umkopiere in einen anderen, auch in Jarvis angezeigten Kalender umkopiere wird alles richtig gezeigt.

Hier im abonnierten Kalender:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/77098747/fd59ee4e-b539-4f4d-b259-d5426462391a)

Und hier ein Termin in eigenen Kalender umkopiert:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/77098747/bd946883-6e46-4c81-91e7-6f8423676f99)


Gruß

**Comment by HolgerDo** [comment]
Hallo,

 

das Problem ist mit der Beta 3.1.9-beta 2 behoben. Ich frage mich allerdings warum es noch kein offizielles Update gibt. Auch dauert es manchmal bis zu 30 Sek. Ist der Kalender lädt …

 

 



 

 



 



 

Von: Scheuerschrauber ***@***.***> 
Gesendet: Montag, 2. Oktober 2023 18:55
An: Zefau/ioBroker.jarvis ***@***.***>
Cc: HolgerDo ***@***.***>; Comment ***@***.***>
Betreff: Re: [Zefau/ioBroker.jarvis] nach Update auf 3.1.x funktioniert Calendar nicht mehr (401) (Issue #2082)

 

Ich habe leider auch mehrere Probleme mit dem Kalender. Vor dem Upgrade konnte ich schon nicht mehr auf meinen Google Kalender zugreifen - also noch vor 3.1 - daran seid ihr ja irgendwie :-) Nach dem Update habe ich nun Probleme mit unserem Müllkalender. Per Link https://abfall.alzey-worms.de/WasteManagementAlzeyworms/WasteManagementServiceServlet?ApplicationName=Calendar&SubmitAction=sync&StandortID=8089270001&AboID=208146&Fra=R;R;B;P;L;S;C aber auch als download ics Leerungstermine190574.zip <https://github.com/Zefau/ioBroker.jarvis/files/10435477/Leerungstermine190574.zip>  es erscheint nun statt dem Müllgut [object Ojbect]

06:00-07:00, [object Object] Di., 17.01., vor etwa 9 Stunden 06:00-07:00, [object Object] Di., 17.01., vor etwa 9 Stunden 06:00-07:00, [object Object] Mi., 18.01., in etwa 15 Stunden

 <https://user-images.githubusercontent.com/17078568/212913232-a93c44a4-9280-4a21-b710-a228bdb83d9e.png> 

Muss mich hier leider anschließen, bekomme auch nur [object Object] als Inhalt eines Termins angezeigt. Witzigerweise wohne ich im gleichen Landkreis. Wenn ich den Termin umkopiere in einen anderen, auch in Jarvis angezeigten Kalender umkopiere wird alles richtig gezeigt.

Hier im abonnierten Kalender:
 <https://user-images.githubusercontent.com/77098747/272034757-fd59ee4e-b539-4f4d-b259-d5426462391a.png> 

Und hier ein Termin in eigenen Kalender umkopiert:
 <https://user-images.githubusercontent.com/77098747/272034950-bd946883-6e46-4c81-91e7-6f8423676f99.png> 

Gruß
