### ISSUE TITLE
Lizenz Problem

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2083]
`jarvis v 3.1.2`
Bin jetzt auch vom Lizenz Problem betroffen.
Habe neuen Schlüssel bekommen und unter Info eingetragen.
Komme nur einmal auf die jarvis Seite, jeder weitere versuch ist blockiert, auch Optionen nicht erreichbar.

![2](https://user-images.githubusercontent.com/77005685/204785617-924f3e09-e71f-46cd-b6f8-b93d285ff50c.jpg)

![1](https://user-images.githubusercontent.com/77005685/204784376-6b1f0ffc-6a80-467f-831b-aa00b9e801fc.jpg)

Was ist zu tun ?

**Comment by Bernd9000** [comment]
Ich schreib mal per Mail, mache hier dicht

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2079
