### ISSUE TITLE
Fehler: d.map is not a function

### ISSUE THREAD

**Issue by Schimi1983** [Zefau/ioBroker.jarvis#2084]
nachdem heute das Abo gegriffen hat (ist schonwieder nen Jahr rum? :) ) ist mir unter "Pro Account" diese fehlermeldung aufgefallen....

Keine Ahnung, wie lange sie dort schon ist... scheint auch alles "normal" zu funktionieren

![image](https://user-images.githubusercontent.com/4581474/204843260-76537c91-4aa6-4d71-b36e-c5e62d9e1214.png)

**Comment by SlipKoRn88** [comment]
Das habe ich bei mir auch. Das Abo hat sich bei mir automatisch verlängert. Jedoch bin ich trotz der eben hinterlegten Lizenz kein PRO User mehr

**Comment by Bernd9000** [comment]
Dito, hier auch

**Comment by Schimi1983** [comment]
> Das habe ich bei mir auch. Das Abo hat sich bei mir automatisch verlängert. Jedoch bin ich trotz der eben hinterlegten Lizenz kein PRO User mehr

Ich habe die Lizenz aus der mail einfach am entsprechenden Datenpunkt eingefügt (wie in der Anleitung, grob mittig im Text)... Ob er es automatisch gemacht hätte... keine ahnung...

**Comment by Zefau** [comment]
Abruf sollte nun wieder klappen.

**Comment by SlipKoRn88** [comment]
Es funktioniert wieder. Ich bin nun auch wieder PRO. Besten Dank für die schnelle Arbeit
