### ISSUE TITLE
Change tab color 

### ISSUE THREAD

**Issue by duffy6** [Zefau/ioBroker.jarvis#2094]
It would be great to change the tab color if a value changes!

or is this already possible?

**Comment by Zefau** [comment]
In V3.1 mittels Binding bereits möglich

**Comment by Zefau** [comment]
@duffy6

**Comment by Zefau** [comment]
@mcuiobroker findet sich dazu zufällig etwas in der Doku? danke dir

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/layout/tab#beispiel-binding
