### ISSUE TITLE
Quick Jumper - Seiten/Tabs nicht verlinkt

### ISSUE THREAD

**Issue by Rookiestyle** [Zefau/ioBroker.jarvis#2097]
**Prerequisites / Voraussetzungen**
v3.1.2

**Describe the bug / Beschreibe den Fehler**
Der Quick Jumper zeigt mir alle Seiten und Tabs.
Leider sind das nur Text, verlinkt ist keiner davon und daher kann ich darüber nicht navigieren

![image](https://user-images.githubusercontent.com/36454520/206872176-a1f4fbeb-f82e-4263-994c-ebeea7728800.png)

![image](https://user-images.githubusercontent.com/36454520/206872294-b9406146-cf24-4371-b784-d3333e02633c.png)

**Comment by mcuiobroker** [comment]
`iob upload jarvis` auf der console?

**Comment by Rookiestyle** [comment]
Falls das noch ergänzt werden kann: Bei einigen Seiten und Tabs fehlen die Symbole

Der Link stand im Template für das Ticket drin und ich habe ihn versehentlich nicht gelöscht, ist jetzt raus.

 `iob upload jarvis` hat nichts geändert, nach wie vor keine Links

![image](https://user-images.githubusercontent.com/36454520/206872621-ff997b30-7783-4c02-988b-e9b14d02654c.png)

**Comment by Rookiestyle** [comment]
```
{
  "tourIntroduction": true,
  "tourInterface": true,
  "tourConfiguration": false,
  "configExpertMode": true,
  "configTab": "settings",
  "configDevicesFilter": null,
  "configDevicesGroupBy": "function",
  "language": "de-DE",
  "pageFavicon": "",
  "pageTitle": "jarvis - just another remarkable vis",
  "pageHome": "",
  "pageHomeReturn": 0,
  "hideProNotification": true,
  "quickJumper": "always",
  "reload": true,
  "drawerMiniMode": false,
  "drawerShowMenuButton": true,
  "drawerShowSettings": false,
  "tabsCollapse": false,
  "tabsDense": true,
  "tabsBottom": false,
  "tabsSwipe": "mobile",
  "tabsSwipeAnimation": "never",
  "tabsShow": "hide",
  "defaultBoxIcon": "",
  "themeDarkMode": false,
  "brandPrimary": "#1976d2",
  "brandSecondary": "#005c5c",
  "brandAccent": "#5c005c",
  "scrollbars": "always",
  "breakpoint-sm": 600,
  "breakpoint-md": 1024,
  "securePageType": false,
  "securePagePassword": "",
  "securePageGroups": [
    "system.group.administrator"
  ],
  "secureConfigurationType": false,
  "secureConfigurationPassword": "",
  "secureConfigurationGroups": [
    "system.group.administrator"
  ],
  "secureLogin": true,
  "LastChangeBody": "",
  "undefined": "",
  "token": "04f7a0509b1f350740b51430b9faf21a",
  "sendUsageData": true
}

**Comment by mcuiobroker** [comment]
das hier:
![image](https://user-images.githubusercontent.com/84818934/206873261-a7eb1b0f-f7b5-42e2-913c-1759580ae896.png)

**Comment by Rookiestyle** [comment]
![image](https://user-images.githubusercontent.com/36454520/206873401-98021a3e-3692-40b5-91e9-5d6b4c515401.png)

mpi ist der Names meines Pi.
Wenn ich da explizit die IP eintrage, ändert das auch nichts

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/206873502-2eafe21c-685f-4e79-961b-528f13d8e79d.png)
IP-Adresse eintragen
und / oder?? in die WhiteList eintragen

**Comment by Rookiestyle** [comment]
Wie schon geschrieben: 

> Wenn ich da explizit die IP eintrage, ändert das auch nichts

da = Im Feld "Socket Host / IP"

Hab das jetzt auch mit Name und IP bei der Whitelist versucht, ohne Erfolg

**Comment by mcuiobroker** [comment]
Dann muss @zefau sich das mal anschauen.

**Comment by mcuiobroker** [comment]
Wenn du ein hover über das Element machst erscheint unten was?

![image](https://user-images.githubusercontent.com/84818934/206873773-b0015699-1527-4bc9-8fe4-0a35666b8e1b.png)

**Comment by mcuiobroker** [comment]
Socket IP/Hostname
nur `mpi`
oder `192.168.178.xxx`

NICHT mpi /...

**Comment by Rookiestyle** [comment]
Bei Socket stand nur mpi oder die IP des Raspberry Pi.

Die Whitelist war:
Leer
mpi
IP des Pi, IP meines Laptops

**Comment by mcuiobroker** [comment]
Was hat denn jetzt geholfen?

**Comment by stony2k** [comment]
Gleiches Problem hier. Sehe zwar alle Seiten im Quick Jumper, aber leider sind keine Verlinkungen dahinter
<img width="1191" alt="Bildschirm­foto 2022-12-21 um 20 00 15" src="https://user-images.githubusercontent.com/16526471/208983216-97c091dc-477a-4774-bd5e-1b032edc8b18.png">

**Comment by rschneider1509** [comment]
Ich brauche den Quick-Jumper zwar nicht, aber als er nach dem Update erschien, habe ich mich gefragt wozu der Button ist - denn wenn ich drauf klicke passiert einfach gar nichts.
Ich habe nur eine Seite mit mehreren Tabs und Widgets, hat das damit zu tun? Aber mMn. sollte ich dann doch ein Menü sehen wo alle Tabs oder Widgets der Seite gelistet sind?

**Comment by ma-gu-16** [comment]
dito.  Quickjumper geht nicht. Grundsätzlich finde ich, sollten neue Features immer deaktiviert sein. Ein Hinweis im Changelog o.ä. sollte ja genügen.  

Der Quickjumper wenn er den funktioniert finde ich aber Praktisch, da das Hamburgermenu leider etwas umständlich ist und zu sehr in der Ecke platziert.

**Comment by Zefau** [comment]
@rschneider1509 @ma-gu-16  habt ihr Fehler in der Browser-Konsole via F12?

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.3-beta.0`

**Comment by Rookiestyle** [comment]
Habe 3.1.1-beta.0 installiert und Jarvis zeigt mir nur eine weiße Seite an.
Restart von Jarvis / Restart von IOBroker ändern nichts daran
Nach Downgrade auf 3.1.1 funktioniert wieder alles bis auf Quick Jumper


![image](https://user-images.githubusercontent.com/36454520/210306394-b22f2ba0-6cd4-4f94-b3cf-1c4229893af6.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.1`

**Comment by Rookiestyle** [comment]
Nach Installation von 3.1.3-beta.2 funktioniert die Navigation.

Die 3 Dinge sind mir aufgefallen.
Willst du neue Issues dafür oder machst du das hier mit?

1. Es werden nicht alle Tabs angezeigt
2. Bei einigen Tabs fehlt das Icon
3. Nicht sichtbare Tabs werden angezeigt

![Screenshot_20230104_061958_Chrome](https://user-images.githubusercontent.com/36454520/210490765-e08e36e8-9614-4501-91e4-4777271ec6f8.png)


![Screenshot_20230104_063200_Chrome](https://user-images.githubusercontent.com/36454520/210490787-f4fa7fac-e552-4499-a39a-ce5eb3f59f86.jpg)
Fehlende Icons hier: 

Tab "Wetterwarnungen" ist ausgeblendet über den Bodystil ``{"{0_userdata.0.nina.warningCount}==0":{"display":"none !important;"}}``
Das geht vermutlich eher in Richtung feature request

**Comment by Zefau** [comment]
>  Losgelöst von den Punkten den Quick Jumper betreffend: Wo kommt denn die Warnung im Log her?

Die WOFF Warnungen sind aufgrund der Schriftarten für die Icons. Keine Ahnung, wie man die weg bekommt.
Die andere Fehlermeldung mit dem `translating` sollte mit der aktuellen beta-11 behoben sein.

> Bei einigen Tabs fehlt das Icon

Wird mit der nächsten beta behoben.

> Nicht sichtbare Tabs werden angezeigt

Beim QuickJumper werden aktuell keine Styles berücksichtigt. Ich hab dazu bei Quasar ein Pull Request eröffnet (https://github.com/quasarframework/quasar/pull/15338).

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.13`

**Comment by Rookiestyle** [comment]
Es werden mehr Icons angezeigt, aber noch nicht alle.

Fehlende Icons bei mir:
icon-park-outline:sleep-two - wird weder auf dem Laptop noch auf dem Handy angezeigt
grommet-icons:configure - wird weder auf dem Laptop noch auf dem Handy angezeigt
mdi:chart-line - wird nur auf dem Laptop nicht angezeigt, auf dem Handy passt's
bi:fuel-pump-fill - wird nur auf dem Laptop nicht angezeigt, auf dem Handy passt's

Fehler im Log gibt es nicht, die Icons sind alle direkt ohne Bindings im Tab eingetragen.

Wenn ich statt `mdi:chart-line` `mdi-chart-line` verwende, dann wird das Icon auch auf dem Laptop angezeigt.
Wenn man Icons bei iconify sucht und dort kopiert, werden sie aber mit : kopiert
Scheint auch nur bei mdi zu funktionieren, bei anderen Sets funktioniert der Austausch von : mit - nicht.

Zusätzlich:
- Grüner Hintergrund ist nicht gut, rote Schrift auch nicht
- Kannst du bei der Anzeige der Widgets bei leerem Label den Widgetnamen statt des Typs anzeigen?

![image](https://user-images.githubusercontent.com/36454520/215316898-538745ac-6106-4de3-863e-5d85b3954758.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.15`

**Comment by Rookiestyle** [comment]
Farben und Iconanzeige funktioniert jetzt bei mir. 

Allerdings werden jetzt anders als bei 3.1.3-beta13 keine Widgets mehr angezeigt, nur noch Seiten und Tabs
![image](https://user-images.githubusercontent.com/36454520/215399833-714a3687-0630-4ed9-95cb-7611f0fd51a1.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.16`

**Comment by Rookiestyle** [comment]
Widgets sehe ich nach wie vor keine auf dem Handy

Zudem werden einige Icons jetzt wieder nicht angezeigt:
`fluent:conference-room-20-regular`
`ic:round-local-dining`
`icon-park-outline:sleep-two`
`game-icons:office-chair`
`game-icons:sewing-string`
`grommet-icons:configure`

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.17`

**Comment by Rookiestyle** [comment]
Icons werden alle angezeigt.
Widgets werden mobil nach wie vor nicht angezeigt, nur Seiten und Tabs

**Comment by Zefau** [comment]
Mit mobil meinst du aber nicht die Android App?

Es gibt keinen Unterschied zwischen mobil und Desktop bzgl der Web App. Hast du das Problem in jedem Browser auf mobil?

**Comment by Rookiestyle** [comment]
Ich habe das Phänomen mit Chrome, Firefox und Edge auf meinem Smartphone in der Webansicht. Die App nutze ich nicht

**Comment by Rookiestyle** [comment]
Kann es jetzt auch auf dem Rechner mit Edge nachstellen, indem ich den User Agent über die DevTools ändere

Vorher
![image](https://user-images.githubusercontent.com/36454520/216372943-fdcc0869-8e23-47a0-b60f-9b7f7cfb105e.png)

User Agent ändern
![image](https://user-images.githubusercontent.com/36454520/216372333-24c3c50c-fe8b-4457-9441-9916b0ee0f34.png)

Nachher
![image](https://user-images.githubusercontent.com/36454520/216372532-f6cbfca9-dcae-4096-8eae-bae2ece99d78.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.19`

**Comment by Zefau** [comment]
`v3.1.3-beta.22`

**Comment by Rookiestyle** [comment]
Funktioniert, vielen Dank!

Wenn jetzt noch dein PR für das style Attribut übernommen wird, ist's perfekt aber da müssen wir uns wohl noch etwas in Geduld üben

**Comment by Zefau** [comment]
Das sollte auch so funktionieren. Ich hab den Code in Jarvis angepasst.

**Comment by Zefau** [comment]
Zeig/ kopiere mir mal deinen Style bitte

**Comment by Rookiestyle** [comment]
Body Stil des Tabs
`{"{0_userdata.0.nina.warningCount}==0":{"display":"none !important;"}}`

**Comment by Zefau** [comment]
ohne `;`

**Comment by Rookiestyle** [comment]
Ohne `;` funktioniert's.

Ich dachte immer, dass `;` beim letzten Element einer Regel sei zwar optional aber nicht unzulässig. Wieder was gelernt

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1339#issuecomment-1425161243
> Allerdings werden mit 3.1.3-beta.31 wieder einige Icons nicht im Quick Jumper angezeigt, bspw. fluent:conference-room-20-regular oder ic:round-local-dining

**Comment by Zefau** [comment]
`v3.1.3-beta.32`

**Comment by Rookiestyle** [comment]
Icons sind wieder alle sichtbar, aber mein Wetterwarnungstab wird trotz `{"{0_userdata.0.nina.warningCount}==0":{"display":"none !important"}}` I'm Bodystil des Tab im Quick Jumper angezeigt. Wert des DP ist 0

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.34`

**Comment by Rookiestyle** [comment]
Jetzt funktioniert es.
