### ISSUE TITLE
Suggestion of new data structure

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#21]
```
   "...":{
      "name": ...
      "function": ...
      "groups":"Group 1, Group 2",
      "states":{
         "...":{
            "stateNode": ... // formerly state
            "actionNode": ... // formerly action
            "unit": ... // moved here from `jarvis`
            "label": ...
            "icon": ...  // moved here from `jarvis`
            "iconStyle": ...  // moved here from `jarvis`, formerly part of styles (being nested)
            "state": ...  // moved here from `jarvis`
            "stateStyle": ... // moved here from `jarvis`, formerly part of styles (being nested)
         },
          ... more states ...
      },
      "attributes":{
           ....
      },
      "jarvis":{
           ....
      }
   }
```

**Comment by Zefau** [comment]
@braindead1

**Comment by braindead1** [comment]
First sugestion and there is room for improvement.

"..." is a string
... may be a string or an object

"states.icon" may be a string representing a Material UI icon or a base64 icon, but it can also be an object containing the icon for specific state values

"states.state" is used to transform specific values into readable vales (e.g. "0": "Auto", "1": "Manual")

"states.style.icon" and "states.style.state" can either be used to based for specific state values or for each state value

``` js
"...":{
  "name": "..."
  "function": "..."
  "groups": ["Group 1", "Group 2", "..."],
  "states":{
    "...":{
      "nodes": {
        "state": "...",
        "action": "..."
      },
      "unit": "..."
      "label": {
        "de": "...",
        "en": "..."
      },
      "icon": ...
      "state": ...
      "style": {
        "icon": ...,
        "state": ...
      }
    },
    ... more states ...
  },
  "attributes":{
       ....
  },
  "jarvis":{
       ....
  }
}
```

**Comment by Zefau** [comment]
Why wrapping `state` and `action` into `nodes`? I think we should aim to reduce nesting. This is also why I split `style` with keys `icon`/`state` into `iconStyle`/`stateStyle`. From a developing perspective easier and also for the end user (in expert mode) I think.

Internationalization for `label` is not required I think because the user will always set a specific language than define more than one, don't you think?

`groups` can be both, either comma-separated string or an array. Just as of now already jarvis will handle this and convert comma-separated string into an array automatically.

**Comment by Zefau** [comment]
Sketch for adding a new device:

![image](https://user-images.githubusercontent.com/14368811/78075695-4ef99900-73a5-11ea-9c02-c982517c3969.png)
`function` will be a dropdown of already implemented functions as well as free solo (flexible user input).
`groups` will be a dropdown of already declared groups as well as free solo. 

_____
![image](https://user-images.githubusercontent.com/14368811/78075719-58830100-73a5-11ea-9739-c71ba6dd26a8.png)

What do you think? Is that more intuitive?

Third step will be defining unit, icon, state mapping and styles (not yet sketched).
Fourth step will be additionally `jarvis` options.

**Comment by Zefau** [comment]
EDIT: Sketch is a little wrong

`Welcher Datenpunkt aus ioBroker soll in jarvis angezeigt werden?` on the first screenshot is supposed to be `Name des Geräts` instead.

`Welcher Datenpunkt aus ioBroker soll in jarvis angezeigt werden?` will be the title of the second screenshot.

**Comment by braindead1** [comment]
In my opinion the screenshots above are not intuitive, because they strictly follow the currently used JSON. 

I think it's better to define everything that is related to the device on one tab (incl. optional parts). The second tab should show a list of existing states. Everything that is related to the state (incl. optional parts) should be defined in a pop-up.

Unfortunately I don't know how to sketch.

**Comment by braindead1** [comment]
What do you think will be the preferred way of users to configure Jarvis? Is it the UI or the JSON?

I believe that most users will use the UI and only a few will use the JSON. Therefore simplicity for users in expert mode is not that important. On the other side having a clean JSON that can be extended in future is more important.

I do not understand, why it is easier from development point of view to reduce nesting? I believe it's the other way around as everything that belongs together is linked. (Example: `iconStyle` and `stateStyle` vs. `style`). Even for experienced expert users this is easier to understand.

Besides that reducing _the magic_ while consuming the JSON will simplify the development. It will also be easier for expert users as they just have to stick to the JSON without having to know what _magic_ is available where. Example: The fact that Jarvis is able to convert the comma-separated `groups` string into an array automatically is due to the fact at the start of the development there was no UI.

**Comment by braindead1** [comment]
Another point that is missing, but may be important for the rest of the discussion is you vision for Jarvis. 

- How far away is the current version from your vision?
- In a previous version I saw a hamburger icon on the upper left corner, that is gone in the meantime. Do you have the intention to not only support one page with tabs, but maybe multiple by clicking on the hamburger icon to open a navigation panel?
- How far do you want to support different languages? Currently you can select a language and Jarvis translates some strings automatically. Do you only want to focus on UI elements (e.g. buttons) or do you also want to focus on state labels (e.g. for functions != default)?
- Once the UI configuration is fully working, do you want to remove the possibility to edit the JSON in the UI?

**Comment by Zefau** [comment]
> I think it's better to define everything that is related to the device on one tab (incl. optional parts). The second tab should show a list of existing states. Everything that is related to the state (incl. optional parts) should be defined in a pop-up.

So basically like it is now: Adding a device adds a new line to top of the table. Clicking the state button opens the popup and a single state will be added with all its contents?

Is that way you think its best? If not, we can Skype on Fri or Sat? In the week it is very busy with work and the little one.

> What do you think will be the preferred way of users to configure Jarvis? Is it the UI or the JSON?

I was hoping the JSON, because it seemed easiest to me, but the responses in the forum proofed me wrong. So, UI.

 > I do not understand, why it is easier from development point of view to reduce nesting? I believe it's the other way around as everything that belongs together is linked. (Example: iconStyle and stateStyle vs. style). Even for experienced expert users this is easier to understand.

Because in React a state actually shouldn't be nested at all. It is considered bad practice and leads to this:

https://github.com/Zefau/jarvis/blob/ec0336ad2d84a53da5e1df2d97ea8f341c9fe3f3/src/pages/DevicesPage.js#L166

> How far away is the current version from your vision?

Even though a lot is done, there are still many modules to go, such as:
- Input list (e.g. Shopping list via Alex Adapter)
- Home map / groundplan (most likely iFramed from ioBroker.vis)
- Avatar (e.g. user home)
- Display (e.g. Calendar)
- iFrame (e.g. Camera)
- Picture (e.g. Camera)
- Thermostats
- Wetter
- Alarm
- Multimedia Control (e.g. Sonos, Spotify)
- Timer
- Countdown
- any wishes by a certain majority of users

Additionally, notification messages (based on priority popup with timeout or popup, that actively has to be dismissed or snackbar).

> In a previous version I saw a hamburger icon on the upper left corner, that is gone in the meantime. Do you have the intention to not only support one page with tabs, but maybe multiple by clicking on the hamburger icon to open a navigation panel?

Sidebar / drawer is only planned for notification feature (shows list of notifications).  It is not planned to support multiple pages, but as stated before, if a majority of users votes for it, it will be implemented.

> How far do you want to support different languages? Currently you can select a language and Jarvis translates some strings automatically. Do you only want to focus on UI elements (e.g. buttons) or do you also want to focus on state labels (e.g. for functions != default)?

Everything will be i18n based.
This is done on different levels:
- global translations via language pack, see https://github.com/Zefau/jarvis/tree/master/src/i18n
- will be overwritten by:
  - translations done in modules, see https://github.com/Zefau/jarvis/blob/master/src/modules/AdapterStatus.js#L263 or
  - translations done in functions, see https://github.com/Zefau/jarvis/tree/master/src/functions/user
- will be eventually overwritten by the end user, see https://github.com/Zefau/ioBroker.jarvis/wiki/Einstellungen#einstellung-translations (means everything can be translated already now by the end user)

> Once the UI configuration is fully working, do you want to remove the possibility to edit the JSON in the UI?

No, that will most likely stay as expert option.

**Comment by braindead1** [comment]
Thank you for the detailed answer and insides on your vision and plans. I will send you my contact infos via chat in the forum. We can then have a skype session on the weekend.

**Comment by Zefau** [comment]
```
 "...":{
      "name": ...
      "function": ...
      "groups":"Group 1, Group 2",
      "states":{
         "...":{
            // label / name displayed for the state
            "label": ...

            // type (trigger, dropdown, etc.) for the state
            "type": ...

            // node of the state for value being retrieved and displayed
            "state": ...

            // custom style for state being displayed
            "stateStyle": ... // moved here from `jarvis`, formerly part of styles (being nested)

            // action to trigger (may be same as "state"
            "action": ...

            // unit of the state
            "unit": ... // moved here from `jarvis`

            // icon to be displayed
            "icon": ...  // moved here from `jarvis`

            // custom style for the icon being displayed
            "iconStyle": ...  // moved here from `jarvis`, formerly part of styles (being nested)

            // custom value being displayed based on retrieved state value
            "display": ...  // moved here from `jarvis`, formerly state
         },
          ... more states ...
      },
      "attributes":{
           ....
      },
      "jarvis":{
           ....
      }
   }
```

**Comment by Zefau** [comment]
71dbd01dbbe39b7712e168c9058a01c6926f6bf0
