### ISSUE TITLE
Weather Widget error

### ISSUE THREAD

**Issue by tipp88** [Zefau/ioBroker.jarvis#2100]
Hi,

I'm using Jarvis on my tablet with Fully Kiosk Browser which basically works fine.
For some reason after some time without page reload, the weather Widget displays an error. After manually refreshing the page it displays the weather. Half a day later without interaction it return same error again. Any idea?
![IMG_20221211_131153](https://user-images.githubusercontent.com/68737433/207049159-53daba47-5fb9-4ce7-a4af-c2d6806635d8.jpg)

**Comment by Zefau** [comment]
duplicate https://github.com/Zefau/ioBroker.jarvis/issues/1943
