### ISSUE TITLE
Mobile Ansicht, "Mehr..." reagiert nicht richtig 

### ISSUE THREAD

**Issue by mpl1337** [Zefau/ioBroker.jarvis#2102]
Hallo,

Ich habe das problem, dass seit version 3.1.2 der "Mehr..." button oben links in der mobilen Ansicht zwar aufblinkt beim antippen, aber das Menü sich erst nach mehrmaligen antippen tatsächlich öffnet.

**Comment by Lockerbee** [comment]
Ja das kann ich bestätigen, auc bei das selbe Verhalten

**Comment by funkymonkphun** [comment]
Bei mir das selbe Problem. Unter Android

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.3-beta.0`

**Comment by Zefau** [comment]
`v3.1.3-beta.1`

**Comment by mpl1337** [comment]
Scheint zu funktionieren, jedoch schließt sich das Menu jetzt nicht mehr wenn ich eine Seite öffne. Erst wenn ich ins leere Drücke geht es zu.

**Comment by Zefau** [comment]
behoben mit `v3.1.3-beta.13`

**Comment by Zefau** [comment]
@mpl1337 @funkymonkphun @Lockerbee
