### ISSUE TITLE
v3.1.2 Bei Erstellung von einer Notification -> Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2103]
![image](https://user-images.githubusercontent.com/84818934/207740380-dfdef15e-4ae0-468a-815d-ecf3552db861.png)

**Comment by Zefau** [comment]
Wie sieht die Struktur der Notification aus?

**Comment by mcuiobroker** [comment]
`{"title":"Wichtige Meldung","message":"<b>Post ist 5 da!</b><br>TEST","state":"unread","display":"popup","timeout":2000,"icon":"mdi-book-alert"}`

![image](https://user-images.githubusercontent.com/84818934/207793019-7c184ed9-21e5-4a70-975b-7acdc6ec2c9c.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.2`

**Comment by mcuiobroker** [comment]
Hab mir 2 Nachrichten geschickt.
![image](https://user-images.githubusercontent.com/84818934/210477960-5b54f24d-bfbe-40ea-a647-2d239cb185f7.png)

Wenn ich sie mir dann anschaue, sieht es bei der ersten so aus: 
- sieht so aus, als ob dahinter noch etwas ist?
- Icons werden nicht mehr angezeigt
![image](https://user-images.githubusercontent.com/84818934/210477782-ed83b927-f51b-4c97-85da-c4b1a64343fa.png)

bei der zweiten so: 
- plötzlich ganz schwarzer Hintergrund

![image](https://user-images.githubusercontent.com/84818934/210477819-78f999af-6e0b-4c01-a491-ba9dedb71ce8.png)

**Comment by Zefau** [comment]
Das mit dem Icon werde ich beheben.

Das andere liegt daran, dass du mehrere Notifications übereinander hast. Daher graut sich der Hintergrund immer weiter aus.

**Comment by mcuiobroker** [comment]
Die liegen nicht übereinander.  Ich schau sie mir doch nacheinander an.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by mcuiobroker** [comment]
Es ist noch was dahinter und beim Schließen ein Effekt?

![jarvis v313-beta31 Notifications Fehler in Anzeige](https://user-images.githubusercontent.com/84818934/217961119-5c2da794-b017-4a9f-85a3-ffe75973d9dc.gif)

**Comment by Zefau** [comment]
Guck mal bitte im DOM. Da solltest du sehen, was dahinter ist. Würde fast vermuten, dass die Notification doppelt auf geht.

Du bist im Chrome?

**Comment by mcuiobroker** [comment]
Problem scheint Mehrfach Aufruf vom portal-dialog zu sein?
![jarvis v313-beta31 Notifications Fehler in Anzeige Mehrfach Portalaufruf](https://user-images.githubusercontent.com/84818934/218233999-f0812c0e-4d6b-4931-a91f-34dbc77ea606.gif)

**Comment by Zefau** [comment]
Kannst du mir noch die Notification dazu schicken? Dann teste ich direkt damit

**Comment by mcuiobroker** [comment]
{"title":"Wichtige Meldung","message":"<b>Post ist 5 da!</b><br>TEST","state":"unread","display":"popup","timeout":2000,"icon":"mdi-book-alert"}

**Comment by Zefau** [comment]
Da ist ein Zeilenumbruch drin in der `message`. Das ist nicht gewollt, oder? Weil mit Zeilenumbruch klappt es gar nicht.

**Comment by Zefau** [comment]
Kannst du mir mal die `jarvis.0.notifications` schicken?

**Comment by mcuiobroker** [comment]
```
[{"title":"Wichtige Meldung","message":"<b>Post ist 5 da!</b><br>TEST","state":"unread","display":"popup","timeout":2000,"icon":"mdi-book-alert","id":"8c34b974-4443-42e5-8e0e-51d997cf8c82","ts":1675984554272},{"title":"Wichtige Meldung","message":"<b>Post ist 5 da!</b><br>TEST","state":"unread","display":"popup","timeout":5000,"icon":"mdi-book-alert","id":"b8ee3a78-92cb-4bef-a71c-a5a94d4cd6d3","ts":1675984567750}]
```

**Comment by Zefau** [comment]
`v3.1.3-beta.32`

**Comment by mcuiobroker** [comment]
Passt. Danke.
