### ISSUE TITLE
schwarzer Balken bei "Tab-Bar am unteren Rand der Seite ausrichten" auf Mobilgeräten

### ISSUE THREAD

**Issue by masterplan89** [Zefau/ioBroker.jarvis#2105]
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? 
 v3.1.2

Nutzt man die Option  "Tab-Bar am unteren Rand der Seite ausrichten" bleibt bei Mobilgeräten am oberen Rand ein schwarzer Balken anstelle der Tab-Bar zurück. Dies ist zum ersten mal nach dem Update von 3.0.15 auf 3.1.2 aufgetreten und lässt sich auf beliebigen mobilen Geräten reproduzieren:

![Screenshot 2022-12-17 000923](https://user-images.githubusercontent.com/79770891/208203439-3ac33be4-1b68-4ec8-871e-0101d24b6e53.png)

Untersuchung des Objekts mit der Konsole weist ebenfalls auf ein Relikt der Tab-bar hin:
![image](https://user-images.githubusercontent.com/79770891/208204059-d93f3837-1524-49ba-b6f3-39ea1c5633fe.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.2`

**Comment by masterplan89** [comment]
Damit klappt es. Danke!

**Comment by Zefau** [comment]
@masterplan89 könntest du nochmal deine Einstellungen screenshoten? Also die unter Konfiguration.

bzw. hast du nur einen Tab ohne Seiten? Weil bei dir ja der Öffner für den Drawer/Sidebar fehlt und auch keine Tabs da sind?

**Comment by mcuiobroker** [comment]
Die Korrektur führt dazu, dass man jetzt, wenn man das TAB-Menü oben hat, die Widgets hochgezogen werden um ca. 60px.
-> Überschrift von den Widgets liegt hinter dem TAB-Menü.

![image](https://user-images.githubusercontent.com/84818934/210899944-2569320e-e4af-4b36-a05b-59c77566b8c5.png)

**Comment by Zefau** [comment]
schaut bitte nochmal mit `v3.1.3-beta.3`

**Comment by Rookiestyle** [comment]
Ist mit v3.1.3-beta4 noch der Fall

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by Rookiestyle** [comment]
Sieht noch genauso aus, auch nach einem Upload.

**Comment by Zefau** [comment]
Kann ich leider nicht nachstellen. Auf meinem mobil geht es.

Der Code ist 
```
:style="{ 'padding': 0, 'margin-top': settings.tabsBottom || page.tabs.length <= 1 ? 0 : (settings.tabsDense ? '40px' : '60px') }"
```

Also wenn `tabsBottom` aktiviert ist, geht er auf `0`.  Das `q-tab-panel` ist korrekt, da sich darin die ganze Seite befindet (dass ist das, was der Tab quasi umschaltet).

Bist du sicher auf `v3.1.3-beta.9`?
Kannst du nochmal deine `Sidebar & Tabs Einstellungen` screenshoten und auch nochmal den Fehler im DOM tracken?

**Comment by Rookiestyle** [comment]
Es gibt keine Fehler im DOM.
Es gibt im DOM zwei div mit .q-tab-panel.
Beim ersten (grün) steht `margin: 0px;`, das scheint ok zu sein, ist bei Seiten mit mehreren Tabs auch so.
Beim zweiten (rot) steht `margin:top: 0px;`, das ist bei Seiten mit mehreren Tabs nicht der Fall - da sind es die 40px (tabDense) aus deinem Code.
Wenn ich am Laptop manuell `margin-top: 40px;`ergänze, dann passt alles bei der Seite mit einem Tab. 

Da ich genau 1 Tab auf der Seite habe: Ist `page.tabs.length <= 1` richtig, oder eher `< 1`?
 ![image](https://user-images.githubusercontent.com/36454520/215250406-65979e47-ece2-4766-bf43-ac2247457af1.png)

![image](https://user-images.githubusercontent.com/36454520/215251020-7605b575-f133-482d-baff-b3588b7a2950.png)

**Comment by Zefau** [comment]
`page.tabs.length <= 1` wenn es auf der Seite nur einen Tab gibt, dann bringt die Tab-Leiste nichts und daher soll auch bei einem Tab die Leiste ausgeblendet werden. Anders gesagt: Ab 2 Tabs ergibt die Leiste zum Navigieren Sinn.

Wobei ich jetzt gerade merke, dass ich das deaktiviert habe... haha. Also Rolle rückwärts: Es wird es ab `< 1` ausgeblendet, du hast recht. Ändere ich.

-----

Aber: Es ändert bei diesem Issue nichts.

Der Code oben sagt ja, dass wenn `settings.tabsBottom` aktiviert ist, dann ist der Wert direkt `0`. Das ist bei dir doch eigl. aktiviert, oder?  In deinem Post jetzt mit den Einstellungen ist es deaktiviert.

Erst wenn das nicht aktiviert ist, dann wertet er `tabsDense ` aus und nimmt dann entweder `40` (wenn aktiviert) oder `60` (wenn deaktiviert).

Ich erkenne da keinen Fehler, der dieses Issue mit dem schwarzen Balken verursacht? :-\

**Comment by Rookiestyle** [comment]
Ich glaube, wir haben aneinander vorbeigeschrieben.

Ich hatte #2173 aufgemacht und du hast es als duplicate geflaggt.
Danach hatte ich das Ticket hier gefunden mit mcuiobrokers Kommentar und dachte, dass du das als duplicate meintest:
> Die Korrektur führt dazu, dass man jetzt, wenn man das TAB-Menü oben hat, die Widgets hochgezogen werden um ca. 60px.

Darum geht es mir, meine Tab-Leiste ist oben und die Widgets werden hochgezogen bei genau einem Tab.

Wenn die Tab-Leiste unten ist, ist alles super.

Wenn die Tab-Leiste oben ist, dann braucht's aber ja entweder ein margin-top auch bei einem Tab oder sie wird bei einem Tab ausgeblendet und nur der Button für die Sidebar wird angezeigt

**Comment by Zefau** [comment]
Okay, verstanden! Dann ist `page.tabs.length <= 1` das Problem und mit deiner Lösung sollte es dann behoben sein. Release folgt..

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.11`

**Comment by Rookiestyle** [comment]
Funktioniert, danke

Hab's mit Tab-Leiste oben / unten, kompakten Tabs an / aus, Sidebar Minimode an / aus getestet.

**Comment by Zefau** [comment]
klasse! danke dir

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.11`
Auf einer Seite mit einem TAB wird die Tabzeile nicht mehr angezeigt.
https://forum.iobroker.net/topic/59201/jarvis-v3-1-x-just-another-remarkable-vis/383

**Comment by Zefau** [comment]
Wie sind die `Sidebar & Tabs Einstellungen`?

**Comment by Zefau** [comment]
![grafik](https://user-images.githubusercontent.com/14368811/215289110-9f5aa161-6c93-4476-bef9-7f1a8673c5df.png)

**Comment by mcuiobroker** [comment]
Und LevelBody werden nicht mehr angezeigt?
![image](https://user-images.githubusercontent.com/84818934/215289149-d06ee6d5-518a-4157-9e66-986c248be1a2.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/215289312-8708996a-0a11-4670-8df0-9c82ba213089.png)

**Comment by mcuiobroker** [comment]
Ist Mini-Mode deaktiviert ist der TAB wieder da.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/215290357-b27b0b7e-6874-483f-84a5-e08d3051b8c5.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.12`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/215291812-035cd758-5c1a-4552-93ff-60aae0a0f9cb.png)
