### ISSUE TITLE
V3.1.2 funktioniert nicht mehr unter iOS 12.5.6

### ISSUE THREAD

**Issue by Dachluke02** [Zefau/ioBroker.jarvis#2106]
Es lässt sich keine Verbindung mehr aufbauen mit der Version V3.1.2 unter iOS12.5.6 auf dem iPad.
Safari und chrome ausprobiert.

**Comment by git2206** [comment]
Hallo,
habe leider das gleiche Problem...
Bitte um Behebung..
Vielen Dank!

**Comment by Zefau** [comment]
Könnt ihr eine Verbindung zum ioBroker.admin bzw. zum Web-Adapter aufbauen? Nutzt ihr https mit selbst-signiertem Zertifikat?

Was steht im ioBroker Log zum Zeitpunkt des Versuchs eines Verbindungsaufbaus?

**Comment by git2206** [comment]
Hallo,
Also log kann ich derzeit nicht sagen... bin wieder zurück auf 3.0.15... vielleicht schaff ich es morgen nochmals zu tresten... Aber ich benutze nur http Verbindung... kein https.. vielleicht hilft das schon ein bißchen..

Vielen Dank

**Comment by Dachluke02** [comment]
Ich nutze eine http-Verbindung.
Der Web-Zugriff auf ioBroker.admin funktioniert - VIS auch.
Bei dem Verbindungsversuch zu Jarvis steht auf den iPad "Connecting... Show Log (0)" und der blaue Verbindungsbalken läuft.
Im ioBroker Log steht nichts.

**Comment by git2206** [comment]
Hab vorhin nochmals probiert - bei mir ist genau das selbe Verhalten... "Bei dem Verbindungsversuch zu Jarvis steht auf den iPad "Connecting... Show Log (0)" und der blaue Verbindungsbalken läuft."
Im IOBroker log auch kein Eintrag...

Mit freundlichen Grüßen

**Comment by Zefau** [comment]
Also auf meinen iPad Air mit iOS v12.5.5 geht es ebenfalls nicht. Ich kann aber auch die ioBroker-Seite nicht aufrufen.
Chrome kann ich gar nicht testen, da es erst ab iOS 14 installierbar ist.

Ich vermute das mit v3.1.2 aktualisierte Socket-IO funktioniert mit der alten iOS Version nicht mehr.
Da hilft nur ein Downgrade auf v3.0 bzw. der Feature-Request https://github.com/Zefau/ioBroker.jarvis/issues/866

**Comment by git2206** [comment]
Morgen,

ok, mit der version 3.0.15 kann ich derzeit noch gut leben... hätte da aber eine bitte... es gibt dafür ebenfalls ein kleines problem... und zwar mit dem Desktop/Smartphone Layout
https://github.com/Zefau/ioBroker.jarvis/discussions/2121

Kannst du ev. hierbei helfen?

Danke!

mfg
Flo

**Comment by git2206** [comment]
oh, sorry.. hab grad gemerkt, du hast schon darauf geantwortet...

mfg
Flo
