### ISSUE TITLE
Icon Stil 

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#211]
Make it possbile to use this json `{"<0":{"color":"#FFBF00"}}` in Icon-Stil

**Comment by Zefau** [comment]
@duczz This is already implemented and working fine for me. If this is not working for you, please share you device configuration.

**Comment by duczz** [comment]
![image](https://user-images.githubusercontent.com/25475385/96369587-43ac6600-115b-11eb-9f21-8a731ce51e42.png)

**Comment by Zefau** [comment]
Could you provide the whole value of icon as well? The bug is probably caused due to the combination of icon and icon style.

**Comment by Zefau** [comment]
I guess you have not provided an icon for the case of `<0`.

**Comment by duczz** [comment]
aahhhh, thats it. wrong query ^^ - Thanks

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/348
