### ISSUE TITLE
StateHTML with embedded CSS not working

### ISSUE THREAD

**Issue by sir0drake** [Zefau/ioBroker.jarvis#2111]
- [ ] Welche Version von jarvis nutzt du? 3.1.2

In der "alten" Version 3.x.x wurde der Inhalt der StateHTML mit der embedded CSS-Struktur und Fiktionalität
( hidden/visible Table-Rows, Farben, Format ) korrekt dargestellt.
Mit der 3.1.2 fehlt quasi alles was über css gesteuert wird.

**Screenshots**

**Darstellung in Jarvis**
![not working](https://user-images.githubusercontent.com/77205165/208404524-b08ac41f-d186-4563-96bb-c964cfab3cf1.png)

______

**Darstellung im Browser als HTML-File**
**Zuvor in Jarvis 1:1 inkl Funktionalität in css**
![working_2](https://user-images.githubusercontent.com/77205165/208405228-fd12df48-374c-4373-a1f6-0e6a81c38e4d.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/208551870-c05e45e3-0a78-4b78-8838-3edc91a72801.png)
![image](https://user-images.githubusercontent.com/84818934/208551894-4d727158-46d1-4353-a696-b81570c22797.png)
Wie sieht es bei dir aus?

**Comment by Zefau** [comment]
@sir0drake bist du Pro?

**Comment by Zefau** [comment]
Bitte sonst den Code mal bereitstellen, dann probiere ich gerne mal rum.

**Comment by sir0drake** [comment]
du hast post.

vielen Dank !

**Comment by Zefau** [comment]
@sir0drake die CSS und JavaScript-Sachen werden ab v3.1 nur mit Pro-Account übernommen.
