### ISSUE TITLE
Nach Update auf 3.1.2 wird Inhalt von iFrame nicht mehr geladen

### ISSUE THREAD

**Issue by jwlzlawl** [Zefau/ioBroker.jarvis#2113]
Hallo, 

ich habe kürzlich ein Update auf Version 3.1.2 gemacht. 
In Jarvis habe ich eine Seite, auf der ich mir über einen iFrame Grafana Diagramme anzeigen lasse.

Nach dem Update werden mir die Diagramme aber nicht mehr angezeigt. Die Visualisierung bleibt beim folgenden Bild stehen.

 
![image](https://user-images.githubusercontent.com/34967571/208600833-1327b467-a5f9-4032-9533-4192e3b3dc78.png)

Ist dieses Problem bereits bekannt? 
Wenn nein, welche Daten kann ich beisteuern, dass dieses Problem behoben werden kann?

**Comment by mcuiobroker** [comment]
Sandbox aktivieren und alle Optionen auswählen-> blau

**Comment by jwlzlawl** [comment]
Das war ja leicht. Vielen Dank!
