### ISSUE TITLE
Punkt statt Komma wird angezeigt als Nachkommastelle/Float-Teiler

### ISSUE THREAD

**Issue by duffy6** [Zefau/ioBroker.jarvis#2114]
Hallo zusammen,

obwohl ich in den Einstellungen von iobroker „Komma“ als Float-Teiler-Zeichen angegeben habe, wird in Jarvis aber ein Punkt statt Komma benutzt.
Nicht nur bei einem bestimmten Wert, sondern bei allen!!
Jarvis V3.1.2

**Comment by Zefau** [comment]
ioBroker Einstellungen haben keine Auswirkungen in jarvis. Kannst du mir mal screenshoten, was du meinst mit Float-Teiler-Zeichen?

**Comment by duffy6** [comment]
Ich meine die Trennung zwischen Vorkomma und Nachkommazahlen.
Bei mir wird hier immer ein „Punkt“ und kein Komma dargestellt:

![CB293A9E-429C-418C-A00A-3563C8276454](https://user-images.githubusercontent.com/30000750/208824073-2e20d113-26dc-4882-ba9e-9f9d4d2a5549.jpeg)

**Comment by Zefau** [comment]
schau nochmal mit `v.3.1.3-beta.0` (über GitHub installieren)

**Comment by Zefau** [comment]
`v3.1.3-beta.1`

**Comment by duffy6** [comment]
Es hat sich nichts geändert, die Darstellung ohne Komma besteht weiterhin

**Comment by Zefau** [comment]
@duffy6 schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by Zefau** [comment]
@duffy6
