### ISSUE TITLE
V3.1.2 Material not visible

### ISSUE THREAD

**Issue by treblada** [Zefau/ioBroker.jarvis#2117]
Version: V3.1.2

Seit dem Update auf Version 3.1.2 werden die Material Design Icons nicht mehr angezeigt.
Beispiel: für einen Steckdosenschalter habe ich das Icon floor-lamp-dual in der Konfiguration definiert. In der Tab erscheint aber nur eine einfach Glühbirne.

![Bildschirmfoto vom 2022-12-20 20-32-38](https://user-images.githubusercontent.com/1412243/208752968-5fb0cb70-f975-4825-8668-3017c90a397f.png)
![Bildschirmfoto vom 2022-12-20 20-33-01](https://user-images.githubusercontent.com/1412243/208752994-bfe5a76d-c6aa-4fca-bcf7-19bfe504c670.png)

Soweit ich weiß, solten Material Design Icons auch in der freien Variante unterstützt werden?

**Comment by mcuiobroker** [comment]
Bitte das ganze Gerät mit dem entsprechenden DP zeigen.

**Comment by Zefau** [comment]
Du hast das Icon beim Gerät eingetragen. Im Gewerk Licht zieht vorher aber der default im State. Du musst also im State `{}` eintragen um es quasi leer zu machen:

![image](https://user-images.githubusercontent.com/14368811/208764409-38bb540b-297b-41a5-adb7-e859f32c15ca.png)

@mcuiobroker ggf. ein Punkt für die Doku?

**Comment by mcuiobroker** [comment]
Gibt es sonst noch Ausnahmen bzgl. anderer Gewerke?

**Comment by Zefau** [comment]
Muss mich korrigieren: Das oben ist zwar ein gültiger Workaround, aber grundsätzlich ist es ein Bug.

Geräte-Icon soll eigentlich bevorzugt werden vor den defaults. 

Ich werde fixen..

**Comment by mcuiobroker** [comment]
Beim Icon ist die Reihenfolge primaryState(actionState) => bodyState => Gerät => Gewerk
Ist noch richtig?

**Comment by Zefau** [comment]
Jo

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.0`

**Comment by Zefau** [comment]
`v3.1.3-beta.1`

**Comment by Zefau** [comment]
@treblada
