### ISSUE TITLE
v3.1.2 Scripting - Bei Verlust der Verbindung kein resubscribe der DPs im scripts

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2118]
Nach dem Verbindungsverlust werden keine Änderungen von den DPs im script mehr wahrgenommen.
![image](https://user-images.githubusercontent.com/84818934/208970237-342b5310-9690-4c34-b407-b1b9c4e5920b.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.0`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/210285283-6eb4b799-d93c-4172-bf8f-9204e1060ea4.png)

**Comment by Zefau** [comment]
Wann kommt das? Steht da noch mehr im Log?

**Comment by mcuiobroker** [comment]
Direkt am Anfang / Start.
Sonst nix.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.1`

**Comment by mcuiobroker** [comment]
sieht gut aus. Danke.

**Comment by mcuiobroker** [comment]
`v3.1.4-beta.6`
Kein resubscribe bei Verbindungsverlust.

**Comment by Zefau** [comment]
Funktioniert bei mir.

Ich habe folgenden Code:
```
console.error("loaded");

window.Socket.subscribeState('0_userdata.0.3-LEVEL', () => {
   console.log("0_userdata.0.3-LEVEL updated");
});
```

Wenn ich bei offenem Browser Fenster einen Reload mache erhalte ich folgenden Log:

![grafik](https://user-images.githubusercontent.com/14368811/233473390-70975f65-914a-41e3-a3bc-e0f850cc8320.png)


Beim ersten Start bekomme ich ein `0_userdata.0.3-LEVEL updated` sowie auch nach dem Reconnect und dann habe ich es nochmal via Backend getriggert (daher `(2)` im Log).

**Comment by mcuiobroker** [comment]
Ich kann nochmal schauen, kannst du bitte eine Zeile für die scripts einfügen, wie bei den anderen.
![image](https://user-images.githubusercontent.com/84818934/233473978-80018cfe-6daa-48e2-b193-40006dbd0142.png)
-> scripts.

**Comment by mcuiobroker** [comment]
Hat er bei jetzt auch gemacht. Komisch.

**Comment by Zefau** [comment]
> Ich kann nochmal schauen, kannst du bitte eine Zeile für die scripts einfügen, wie bei den anderen.

Skripte sind alle geladen und die Datenpunkte laufen alle via `re-subscribe to states..`

**Comment by Zefau** [comment]
Kann das Issue dann zu?

**Comment by mcuiobroker** [comment]
ja
