### ISSUE TITLE
Tabelle wird nicht sortiert

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#2119]
Jarvis 3.1.2

Ich habe die Notifications als JSON Tabelle eingefügt und möchte die neusten 10 Einträge anzeigen. Die Standardsortierung ist von Alt nach Neu. Ich habe nur die Spalte "title" eingefügt.

![image](https://user-images.githubusercontent.com/2972703/209074085-7854faf7-afb5-4663-81c1-40667436595f.png)

Wenn ich die Sortierung in den Einstellungen ändere, hat das keinen Effekt.

![image](https://user-images.githubusercontent.com/2972703/209076241-dd290631-63d7-4fd3-aeba-46cac00fa448.png)

Wenn ich die Titelleiste einschalte, kann ich dort über den Pfeil die Tabelle korrekt sortieren. Es ist also kein Problem des Inhalts.

**Comment by Zefau** [comment]
Was ist denn konkret das Problem, das verstehe ich nicht. Sind es die falschen 10 Einträge auf Basis der Sortierung?

**Comment by mcuiobroker** [comment]
@stephan1827 
Stell mal in den Optionen statt "label" -> "field" ein und dann unter Spalte (Sortierung) title eintragen.
Dann testen und evtl. die Sortierrichtung umstellen.

**Comment by Zefau** [comment]
@stephan1827

**Comment by mcuiobroker** [comment]
@stephan1827 Du kannst es auch nach ts sortieren
`[{"field":"message"},{"field":"ts","format":""}]`
-> 
![image](https://user-images.githubusercontent.com/84818934/218288486-bd6d04e0-487c-4012-99fe-59077da220a4.png)
