### ISSUE TITLE
Sonoff smartplug state doesn't update itself

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#212]
I have some smartplugs that are flashed with Tasmota. They are communication via MTQQ with the sonoff adapter. The state power updates within the object list immediately. I display it in Jarvis with the power state (`sonoff.0.Steckdose Fernseher.POWER`) as datapoint and trigger. Switching the plug on and off works fine, but if I switch the device outside of Jarvis, the state doesn't update. The only way to update is to refresh the browser. My Homematice devices are beeing updated (in Jarvis) as expected.

**Comment by Zefau** [comment]
Please do not use a whitespace in the state, see https://github.com/Zefau/ioBroker.jarvis/issues/171. Since `v1.1.0-beta.26` it is not possible anymore to have such a state.

**Comment by stony2k** [comment]
Thanks, that solved the issue. I am very grateful, continue with this wonderful work :)
