### ISSUE TITLE
Bilder in Tabellen

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#2120]
Ich möchte gerne die Notifications als Tabelle in meine Visu einbauen. Leider wird die Spalte wo normalerweise die Bilder angezeigt, nur der Text angezeigt. Es wäre schön, wenn man in Tabellen auch Bilder anzeigen könnte. Man könnte dies auch auf Icons begrenzen, wenn das die Sache vereinfacht.

**Comment by Sineos** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1825
Kann das schon und viel mehr

**Comment by Zefau** [comment]
@stephan1827 kannst du das mal screenshoten, was du meinst und wie du das konfigurierst?

**Comment by stephan1827** [comment]
Ich filtere die letzten 10 Zeilen aus jarvis.0.notifications raus und möchte die genau so Anzeigen wie im Archiv, also so

<img width="421" alt="Bildschirm­foto 2023-01-03 um 07 28 56" src="https://user-images.githubusercontent.com/2972703/210622974-f929b094-bb7f-400f-8094-3eaff0bb77bd.png">
