### ISSUE TITLE
Nach Update 3.0.15 -> 3.1.2: "Error: Could not connect within 60 seconds"

### ISSUE THREAD

**Issue by Andr3asB** [Zefau/ioBroker.jarvis#2122]
Ich habe eben von 3.0.15 auf 3.1.2 aktualisiert. Host ist ein Debian Linux (alle Pakete aktuell), x64 Architektur, 6 GB RAM, Node.js 16.18.1, NPM 8.19.2, JS.Controller 4.0.23

Fehlerbild sieht wie folgt aus:
Bis hierhin noch alles normal:
![image](https://user-images.githubusercontent.com/44557554/209217108-9e83387b-3fc7-4157-aedc-a9c0ded7107c.png)
Und dann folgt mach langer Zeit (30 Sek?):
![image](https://user-images.githubusercontent.com/44557554/209215356-23ae5cc1-a7fd-4bec-91b8-59f09e3ff37c.png)

Das hier ist das letzte, was im DevTool des ChromeBrowsers passiert:
![image](https://user-images.githubusercontent.com/44557554/209215618-3d192ec6-7c67-4cac-9402-ef43aab9281a.png)

Hier noch ein zweiter Screenshot aus den BrowserDevTools:
![image](https://user-images.githubusercontent.com/44557554/209217946-486e8ec2-4d82-4eb3-bcca-84567e0fe8a0.png)

Das iob-Log für den Jarvis Adapter habe ich schon auf debug gestellt, aber auch dort nichts brauchbares gefunden:
![image](https://user-images.githubusercontent.com/44557554/209216315-153f4cf2-947a-4117-8386-5e0eb47e0085.png)

Ich bin für jeden Tipp dankbar, der mich der Lösung näher führt!

EDIT: Ich habe noch Infos ergänzt, die vielleicht helfen könnten

**Comment by Zefau** [comment]
Sieht eigentlich gut aus. Restart Web Adapter bzw. Notfalls ioBroker probiert?

**Comment by mcuiobroker** [comment]
Ist der DP nicht angelegt?
![image](https://user-images.githubusercontent.com/84818934/209218496-f1d937cd-5603-467a-996d-e6d07c8244da.png)

console
`iob upload jarvis`

**Comment by Andr3asB** [comment]
Ja, das war's - gelöst! 
Vielen Dank! - Toller Support!
