### ISSUE TITLE
Nach Update überall "letzte Änderung"

### ISSUE THREAD

**Issue by SKB-CGN** [Zefau/ioBroker.jarvis#2123]
Ich habe nun erneut bemerkt, das nach einem Update überall die Bereiche mit der letzten Änderung des Wertes aktiviert werden.
Dies ist sehr mühselig, überall wieder die Anzeige anzupassen.

Könnte man dies nicht aus den vorherigen Einstellungen übernehmen?

**Comment by Zefau** [comment]
Hast du noch die alte Struktur der Widgets? Und die nach deiner Änderung in v3.1? Ein Beispiel genügt. Dann übernehme ich das so.

**Comment by SKB-CGN** [comment]
Danke für die Rückmeldung. 

Wird nicht ein altes Backup angelegt?
Wenn ja, wo finde ich das? 😃

Hatte mich damit nicht beschäftigt.

**Comment by Hunduster** [comment]
Same here. Zerhaut mir aktuell mein ganzes Layout. Update von 3.0.15 auf 3.1.2

**Comment by Zefau** [comment]
@SKB-CGN @Hunduster schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by SKB-CGN** [comment]
Hi,
ich habe die aktuelle Version über Kätzchen -> Benutzerdefiniert installiert.

Leider hat sich hier noch nichts getan.
![2023-01-28 13_38_27-jarvis - just another remarkable vis — Mozilla Firefox](https://user-images.githubusercontent.com/58603329/215266849-e19502d8-4950-4edd-9ab2-f5653a9a0033.png)

**Comment by Zefau** [comment]
Kannst du mal das JSON dazu zeigen?

**Comment by SKB-CGN** [comment]
Klar, wenn Du mir sagen kannst, wo ich das finde?

**Comment by SKB-CGN** [comment]
Ah,
ich denke, es ist dies:

```
"cd76b863-59a5-4b38-9d94-d45fa1347b46": {
  "id": "cd76b863-59a5-4b38-9d94-d45fa1347b46",
  "config": {
    "dense": false,
    "horizontal": false,
    "stacked": false
  },
  "title": "Ioniq-Batterie",
  "icon": "battery-50",
  "module": "StateList",
  "hideSeparator": true,
  "items": [
    {
      "type": "device",
      "deviceId": "47f5bbda-4bd0-4410-a7d1-d8bca530ae8b",
      "id": "4319470e-c681-4c29-aaac-f8b8a81ea852",
      "primaryStateKey": "ladetyp",
      "bodyStateKey": "ladetyp",
      "bodyElement": ""
    },
    {
      "type": "device",
      "deviceId": "47f5bbda-4bd0-4410-a7d1-d8bca530ae8b",
      "id": "3fd33b45-e5a7-4708-9f76-ef4cfdb3781a",
      "primaryStateKey": "ladezustand",
      "bodyStateKey": "ladezustand",
      "bodyElement": ""
    },
    {
      "type": "device",
      "deviceId": "47f5bbda-4bd0-4410-a7d1-d8bca530ae8b",
      "id": "69abcdcf-c8d6-4573-b161-5f567602a9b5",
      "primaryStateKey": "ladezeit",
      "bodyStateKey": "ladezeit",
      "bodyElement": ""
    }
  ],
  "revision": "8f384",
  "label": "Batterie"
}
```

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.11`

**Comment by Zefau** [comment]
ACHTUNG: Vor dem Update bitte bei geschlossenem jarvis sicherzustellen, dass `jarvis.0.widgets` auf `version` `3` steht und nicht `3.1`.

**Comment by SKB-CGN** [comment]
Habe die aktuelle jarvis v3.1.3-beta.16 Version installiert.

Leider habe ich immer noch überall den "BodyState", der ja leer ist.

**Comment by Zefau** [comment]
Kannst du mir die Kopfdaten vom `jarvis.0.widgets` mal durchgeben? Also nur die obersten Schlüssel.

**Comment by SKB-CGN** [comment]
Anbei die ersten Schlüssel. Ich habe das JSON dann wieder "geschlossen". Hier sehe ich 1 mit BodyChange, welches ich auch benötige - das Andere hat keinen.

Änderung der Widgets von 3.1 auf 3.0 hatte ich vor Installation eingetragen.

```
{
  "version": 3.1,
  "signature": 4103387429344671,
  "widgets": {
    "96b2d097-a9b1-4053-9c2a-503ffaffe14c": {
      "id": "96b2d097-a9b1-4053-9c2a-503ffaffe14c",
      "config": {
        "size": "cover",
        "refresh": "30",
        "refreshMethod": "whitespace"
      },
      "module": "DisplayImage",
      "items": [
        {
          "type": "device",
          "deviceId": "5bf59282-8c47-4231-8e54-da2e7f364d75_ee006_8d156",
          "id": "a2185af6-468e-4fc8-9d99-55f0a64079d6",
          "primaryStateKey": "letztes_event",
          "bodyStateKey": "bewegung",
          "bodyElement": "LastChangeBody"
        }
      ],
      "revision": "4da97",
      "title": "Letzte_Bewegung_Haustür",
      "hideSeparator": true,
      "hideTitle": true
    },
    "895bad60-debb-4772-9607-c9775b41d2eb": {
      "id": "895bad60-debb-4772-9607-c9775b41d2eb",
      "config": {
        "dense": false,
        "horizontal": false,
        "stacked": false
      },
      "title": "KameraHaustür",
      "module": "StateList",
      "items": [
        {
          "type": "device",
          "deviceId": "5bf59282-8c47-4231-8e54-da2e7f364d75_ee006_8d156",
          "id": "7bbb6933-f95c-4538-b7bb-0062741e403b",
          "primaryStateKey": "online",
          "bodyStateKey": "online",
          "bodyElement": ""
        }
      ]
    }
  }
}
```

**Comment by Zefau** [comment]
Und die Browser Konsole dann gerne screenshoten

**Comment by SKB-CGN** [comment]
Perfekt. Nun klappt es. Danke Dir!

![2023-02-07 09_09_05-Window](https://user-images.githubusercontent.com/58603329/217188010-a38371aa-3074-4d72-a3c7-77ce2c01f96a.png)


Kannst Du dies nun auch "drin lassen", damit ich dieses Problem beim nächsten Update nicht mehr habe?
Vielleicht noch eine kurze Erklärung, woran es lag?

Danke!

**Comment by Zefau** [comment]
Wenn du dir `jarvis.0.widgets` anschaust, dann sollte dort nun statt `"bodyElement": ""` -> `"bodyElement": null` stehen. Die Konvertierung von 3.0 auf 3.1 hat dies korrigiert.

In v3.0 wurde `"bodyElement": ""` nicht angezeigt. In v3.1 ist es ein bewusster Fallback auf einen default-Wert. Der Fallback wird mit `"bodyElement": null` unterbunden.

**Comment by Hunduster** [comment]
Ich müsste mich hier mal einklinken, da ich selbigen Fehler habe, ihn aber nicht durch deine Angaben @Zefau beheben kann.

Installiert wurde `v3.1.3-beta.29` von 3.0.15 kommend.

Bei mir hat die `jarvis.0.widgets` folgenden Inhalt:

`{"7a0b073d-64e9-4ab4-8602-5af3a4f6901c":{"id":"7a0b073d-64e9-4ab4-8602-5af3a4f6901c","config":{"dense":false,"horizontal":false,"stacked":false},"title":"Hauptschalter","icon":"","module":"StateList","items":[{"type":"device","deviceId":"af418ed1-7f54-4aca-a308-2e77226073ad","id":"70dc7bf0-4a20-45f0-b557-fc32d855b0c9","primaryStateKey":"scene.0.Heizung_Ein/Aus","bodyStateKey":"scene.0.Heizung_Ein/Aus","bodyElement":"","showState":false,"actionElement":"SwitchAction","label":"Heizung"}],"revision":"eb15b","_updated":1672307475767},"aa02c9a7-97e5-4463-b2d4-8029f8b30b8f":{"id":"aa02c9a7-97e5-4463-b2d4-8029f8b30b8f","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"7f499958-68ac-449c-ab39-9ccab9bbd1fd","id":"f5d7de2d-a1de-4cb3-ae9b-a31c18c2fdc0","primaryStateKey":"Nächste Abholung Tonne","bodyStateKey":"Nächste Abholung Tonne","bodyElement":"","label":"Nächste Abholung","showState":true,"secondaryStatesKeys":["Nächste Abholung Tage"]},{"type":"divider","id":"b68c9090-a4aa-4a95-969a-dd7c73c7dec2"},{"type":"device","deviceId":"7f499958-68ac-449c-ab39-9ccab9bbd1fd","id":"caa24bc3-7f36-40ec-ba90-b23cc10144b2","primaryStateKey":"Graue Tonne","bodyStateKey":"Graue Tonne","bodyElement":"","label":"Graue Tonne","showState":true},{"type":"device","deviceId":"7f499958-68ac-449c-ab39-9ccab9bbd1fd","id":"780c4fe2-56fb-4c7f-8c09-43172ddd186c","primaryStateKey":"Gelbe Tonne","bodyStateKey":"Gelbe Tonne","bodyElement":"","showState":true,"label":"Gelbe Tonne"},{"type":"device","deviceId":"7f499958-68ac-449c-ab39-9ccab9bbd1fd","id":"52537399-89ff-4643-a82d-d2d60d3a54ad","primaryStateKey":"Blaue Tonne","bodyStateKey":"Blaue Tonne","bodyElement":"","showState":true,"label":"Blaue Tonne"}],"title":"Abfallkalender (copy)","revision":"824fd"},"8776417d-057d-4e04-b6fb-06dbeb2bc168":{"id":"8776417d-057d-4e04-b6fb-06dbeb2bc168","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"Günstigste","bodyStateKey":"Günstigste","bodyElement":"","label":"Aktuell günstigste Tankstelle:","secondaryStatesKeys":["Günstigste Öffnungszeiten"]}],"revision":"8422d","icon":"","label":"","hideTitle":true,"title":"Günstigste Tankstelle"},"ef1dd42d-edc3-45fd-af07-7da9a6117fe8":{"id":"ef1dd42d-edc3-45fd-af07-7da9a6117fe8","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"OIL Mönchengladbach e10","bodyStateKey":"OIL Mönchengladbach e10","bodyElement":"","label":"Super e10","secondaryStatesKeys":["OIL Mönchengladbach Öffnungszeiten"]}],"revision":"4b7d3","icon":"","label":"","hideTitle":false,"title":"OIL! | M'gladbach"},"d88cbb32-7220-45b3-b950-871743227591":{"id":"d88cbb32-7220-45b3-b950-871743227591","config":{"size":"unset","refresh":0,"refreshMethod":"whitespace","url":"mdi:heater"},"module":"DisplayImage","revision":"9cc07","items":[],"hideSeparator":false,"title":"","icon":"mdi:heater","hideTitle":true},"817e8a04-5281-4ca9-b621-c6bf325067db":{"id":"817e8a04-5281-4ca9-b621-c6bf325067db","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"HEM Mönchengladbach","bodyStateKey":"HEM Mönchengladbach","bodyElement":"","label":"Super e10","secondaryStatesKeys":["HEM Mönchengladbach Öffnungszeiten"]}],"revision":"3b211","icon":"","label":"","hideTitle":false,"title":"HEM | M'gladbach"},"cc4920d7-95a3-4281-a6be-1273f34cabbc":{"id":"cc4920d7-95a3-4281-a6be-1273f34cabbc","config":{"size":"contain","refresh":0,"refreshMethod":"whitespace","url":"https://www.hem-tankstelle.de/~/media/hem-logo_vertikal_rgb.png?h=442&la=de-DE&w=350&hash=9837A3EB12ACD1342948D5539DF5CC0AC3AED722"},"module":"DisplayImage","revision":"43c6e","items":[],"hideSeparator":false,"title":" (copy) (copy) (copy) (copy)","icon":"","hideTitle":true},"263c551a-0f92-4192-b638-cfa4dcf1e77d":{"id":"263c551a-0f92-4192-b638-cfa4dcf1e77d","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"Jet Willich","bodyStateKey":"Jet Willich","bodyElement":"","label":"Super e10","secondaryStatesKeys":["Jet Willich Öffnungszeiten"]}],"revision":"c29b7","icon":"","label":"","hideTitle":false,"title":"JET | Willich"},"3b4e01a9-f64e-4011-a361-08daf2592ca6":{"id":"3b4e01a9-f64e-4011-a361-08daf2592ca6","config":{"size":"cover","refresh":0,"refreshMethod":"whitespace","url":"https://upload.wikimedia.org/wikipedia/de/thumb/e/e5/JET.svg/1280px-JET.svg.png"},"module":"DisplayImage","revision":"596a8","items":[],"hideSeparator":false,"title":" (copy) (copy) (copy)","icon":"","hideTitle":true},"c5383c7a-d407-4631-a405-3089fd9b65e4":{"id":"c5383c7a-d407-4631-a405-3089fd9b65e4","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"Shell Willich e10","bodyStateKey":"Shell Willich e10","bodyElement":"","label":"Super e10","secondaryStatesKeys":["Shell Willich Öffnungszeiten"]}],"revision":"0ba7d","icon":"","label":"","hideTitle":false,"title":"Shell | Willich"},"c153ebd3-6fa6-4335-9530-77c854eaac39":{"id":"c153ebd3-6fa6-4335-9530-77c854eaac39","config":{"size":"contain","refresh":0,"refreshMethod":"whitespace","url":"https://upload.wikimedia.org/wikipedia/de/thumb/7/74/Royal_Dutch_Shell.svg/2194px-Royal_Dutch_Shell.svg.png"},"module":"DisplayImage","revision":"6102f","items":[],"hideSeparator":false,"title":" (copy) (copy)","icon":"","hideTitle":true},"1e711ab5-86ee-4d8b-9568-e51cdc463f10":{"id":"1e711ab5-86ee-4d8b-9568-e51cdc463f10","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"Total Willich e10","bodyStateKey":"Total Willich e10","bodyElement":"","label":"Super e10","secondaryStatesKeys":["Total Willich Öffnungszeiten"]}],"revision":"e556c","icon":"","label":"","hideTitle":false,"title":"Total | Willich"},"73be0cdd-4383-49a8-98d6-f634e1391e67":{"id":"73be0cdd-4383-49a8-98d6-f634e1391e67","config":{"size":"contain","refresh":0,"refreshMethod":"whitespace","url":"https://cdn.freebiesupply.com/logos/large/2x/total-3-logo-png-transparent.png"},"module":"DisplayImage","revision":"c671b","items":[],"hideSeparator":false,"title":" (copy)","icon":"","hideTitle":true},"f4a05774-7fb1-4904-a29e-101e0fe552ad":{"id":"f4a05774-7fb1-4904-a29e-101e0fe552ad","config":{"size":"contain","refresh":0,"refreshMethod":"whitespace","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Esso-Logo.svg/1024px-Esso-Logo.svg.png"},"module":"DisplayImage","revision":"819ce","items":[],"hideSeparator":false,"title":"","icon":"","hideTitle":true,"label":""},"64e78f03-e153-438d-a721-2d0cca65e388":{"id":"64e78f03-e153-438d-a721-2d0cca65e388","config":{"size":"contain","refresh":0,"refreshMethod":"whitespace","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Esso-Logo.svg/1024px-Esso-Logo.svg.png"},"module":"DisplayImage","revision":"6d2f3","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"bbdb6042-a5e9-48e1-8d9f-24cfe1693453","primaryStateKey":"Total Willich e10","bodyStateKey":"HEM Mönchengladbach","bodyElement":"LastChangeBody"}],"hideSeparator":false,"title":"Spritpreise e10 (copy)","icon":"mdi-gas-station","hideTitle":true},"061004b5-827a-43d7-b2f0-013635dbe542":{"id":"061004b5-827a-43d7-b2f0-013635dbe542","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"Esso Willich e10","bodyStateKey":"Esso Willich e10","bodyElement":"","label":"Esso | Willich","secondaryStatesKeys":["Esso Willich Öffnungszeiten"]}],"revision":"ff0d5","icon":"mdi-gas-station","label":"Spritpreise e10","hideTitle":true,"title":" (copy) (copy)"},"4ab4ff3f-aec7-4c71-a570-57686d1bef03":{"id":"4ab4ff3f-aec7-4c71-a570-57686d1bef03","config":{"size":"contain","refresh":0,"refreshMethod":"whitespace","url":"https://cdn.worldvectorlogo.com/logos/total-sa-logo.svg"},"module":"DisplayImage","revision":"9f444","items":[],"hideSeparator":false,"title":" (copy)","icon":"","hideTitle":true},"60384119-139e-4dd4-97d9-29c34c45bf5d":{"id":"60384119-139e-4dd4-97d9-29c34c45bf5d","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"Total Willich e10","bodyStateKey":"Total Willich e10","bodyElement":"","label":"Total | Willich","secondaryStatesKeys":["Total Willich Öffnungszeiten"]}],"revision":"a5087","icon":"mdi-gas-station","label":"Spritpreise e10","hideTitle":true,"title":" (copy)"},"034ed687-6d87-4c1a-bd0a-6668f4acb7e3":{"id":"034ed687-6d87-4c1a-bd0a-6668f4acb7e3","config":{"size":"contain","refresh":0,"refreshMethod":"whitespace","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Esso-Logo.svg/1024px-Esso-Logo.svg.png"},"module":"DisplayImage","revision":"8eb58","items":[],"hideSeparator":false,"title":"","icon":""},"232c9a69-1077-4b03-9c68-2d27eb148e6f":{"id":"232c9a69-1077-4b03-9c68-2d27eb148e6f","config":{},"module":"Map","items":[]},"3958dfb0-83da-48ae-96f3-e66969a92cac":{"config":{},"items":[],"module":"StateList","title":"Licht","id":"3958dfb0-83da-48ae-96f3-e66969a92cac","icon":"mdi-lightbulb-on"},"b073226b-14d9-40e9-bbd7-4a54080cfa87":{"config":{"dense":false,"horizontal":false,"stacked":false},"items":[],"module":"StateList","title":"Heizung","id":"b073226b-14d9-40e9-bbd7-4a54080cfa87","icon":"mdi-phone-bluetooth","revision":"0a847"},"99142690-4245-445b-bbc4-be8d09b93b83":{"config":{},"items":[],"module":"StateList","title":"Fenster","id":"99142690-4245-445b-bbc4-be8d09b93b83","icon":"mdi-window-closed-variant"},"2cbeb543-42fa-4ceb-afa2-cea4ec39a24a":{"id":"2cbeb543-42fa-4ceb-afa2-cea4ec39a24a","config":{"dense":false,"horizontal":false,"stacked":false,"filter":""},"title":"Bahnstraße 22","module":"StateList","revision":"bb2d1","items":[{"type":"device","deviceId":"haustür_d3670","id":"b8489859-402b-43b5-81d4-2cde4aefef66","primaryStateKey":"opened","bodyStateKey":"opened","bodyElement":""},{"type":"device","deviceId":"adf676b8-0c96-4639-a590-c1abd71c0346","id":"155fcce1-730f-42b7-b9ec-6449d7349f9c","primaryStateKey":"Post ist da","bodyStateKey":"Post ist da","bodyElement":""}],"link":""},"9f2829b5-33c5-477f-9c10-6a3ec6f32953":{"id":"9f2829b5-33c5-477f-9c10-6a3ec6f32953","config":{"dense":false,"horizontal":false,"stacked":false},"title":"Vogelzimmer","module":"StateList","items":[{"type":"device","deviceId":"hygrometervogelzimmer_893ef","id":"b3905f82-1494-4344-a24e-2c643d1e4a19","primaryStateKey":"temperature","bodyStateKey":"temperature","bodyElement":"","label":"Temperatur","isInGroup":false},{"type":"device","deviceId":"hygrometervogelzimmer_893ef","id":"cf1d8d5f-0f00-44f1-b04b-c3f8beb0b516","primaryStateKey":"humidity","bodyStateKey":"humidity","bodyElement":"","label":"Luftfeuchtigkeit","isInGroup":false},{"type":"divider","id":"f5f3dd66-eddb-4410-aa09-5c12299b860b","isInGroup":false},{"type":"device","deviceId":"ventaplug_b3f7b","id":"4f992aa2-5583-4ec5-9cb2-acab5a8ead5d","primaryStateKey":"state","bodyStateKey":"state","bodyElement":"","label":"Venta Luftwäscher","actionElement":"ButtonAction","showState":false,"ButtonActionConfig":{"state":{"buttonSize":"sm","labelTurnOff":"einschalten","labelTurnOn":"ausschalten"}},"isInGroup":false}],"revision":"e475d","_updated":1672280288374},"6b875809-7c97-4d47-90bb-ea7a0f775c0d":{"id":"6b875809-7c97-4d47-90bb-ea7a0f775c0d","config":{"dense":false,"horizontal":false,"stacked":false},"title":"Waschküche","module":"StateList","items":[{"type":"device","deviceId":"e0a12af5-0bf6-4c60-8e1c-33ab8e1d25c3","id":"880b835f-cc35-46a3-b81a-8aa3c111fc9c","primaryStateKey":"ON","bodyStateKey":"ON","bodyElement":"","isInGroup":false,"showState":true},{"type":"device","deviceId":"e0a12af5-0bf6-4c60-8e1c-33ab8e1d25c3_72006","id":"e88f99b1-f181-44e9-b48d-28a4aefa8fe1","primaryStateKey":"ON","bodyStateKey":"ON","bodyElement":"","isInGroup":false}],"revision":"1e0c8","_updated":1672306701345},"e8e30365-7315-460d-8cdc-f8e64ace930b":{"id":"e8e30365-7315-460d-8cdc-f8e64ace930b","config":{"dense":false,"horizontal":false,"stacked":false},"title":"Thermostate","icon":"","module":"StateList","items":[{"type":"device","deviceId":"thermowohnzimmer_27a87","id":"9a8cfd28-9743-49f9-b7d9-dec88419bc77","primaryStateKey":"aktuelle Temperatur","bodyStateKey":"aktuelle Temperatur","bodyElement":"CustomTextBody","label":"Wohnzimmer","showState":true,"secondaryStatesKeys":[],"CustomTextBodyConfig":{"Zieltemperatur":{"text":"aktuelle Temperatur"},"aktuelle Temperatur":{"text":"gemessene Temperatur"}}},{"type":"device","deviceId":"thermowohnzimmer_27a87","id":"0e1704f3-30d0-43ef-9d59-b77a4e83564d","primaryStateKey":"Zieltemperatur","bodyStateKey":"Zieltemperatur","bodyElement":"LevelBody","label":"eingestellte Temperatur","showState":true,"secondaryStatesKeys":[],"CustomTextBodyConfig":{"Zieltemperatur":{"text":"Zieltemperatur"}}},{"type":"divider","id":"302315a5-9cdb-4c32-af1e-87c0505d1835"},{"type":"device","deviceId":"thermobadezimmer_10ac6","id":"3758d6aa-9804-4f77-816b-9450edbd0e09","primaryStateKey":"aktuelle Temperatur","bodyStateKey":"aktuelle Temperatur","bodyElement":"CustomTextBody","showState":true,"secondaryStatesKeys":[],"actionElement":"","label":"Badezimmer","CustomTextBodyConfig":{"Zieltemperatur":{"text":"Zieltemperatur"},"aktuelle Temperatur":{"text":"gemessene Temperatur"}}},{"type":"device","deviceId":"thermobadezimmer_10ac6","id":"cacd1e72-4df9-4323-905d-2ac3229ab829","primaryStateKey":"Zieltemperatur","bodyStateKey":"Zieltemperatur","bodyElement":"LevelBody","showState":true,"secondaryStatesKeys":[],"actionElement":"","label":"eingestellte Temperatur","CustomTextBodyConfig":{"Zieltemperatur":{"text":"Zieltemperatur"}}},{"type":"divider","id":"e80f1012-3704-4716-893b-7c5ff9c25243"},{"type":"device","deviceId":"thermoschlafzimmer_3cf82","id":"a181f5c4-8643-4b45-a68e-d4988d36d247","primaryStateKey":"aktuelle Temperatur","bodyStateKey":"aktuelle Temperatur","bodyElement":"CustomTextBody","label":"Schlafzimmer","showState":true,"secondaryStatesKeys":[],"CustomTextBodyConfig":{"aktuelle Temperatur":{"text":"gemessene Temperatur"}}},{"type":"device","deviceId":"thermoschlafzimmer_3cf82","id":"d64d9f56-c4b4-46bb-adf8-cf9f7e838fc0","primaryStateKey":"Zieltemperatur","bodyStateKey":"Zieltemperatur","bodyElement":"LevelBody","label":"eingestellte Temperatur","showState":true,"secondaryStatesKeys":[],"CustomTextBodyConfig":{"aktuelle Temperatur":{"text":"Zieltemperatur"}}},{"type":"divider","id":"a9494ec3-9c22-46ac-9dc9-68b4d388452a"},{"type":"device","deviceId":"thermovogelzimmer_22941","id":"54496022-605f-41c9-97df-0833375b4165","primaryStateKey":"aktuelle Temperatur Zigbee","bodyStateKey":"aktuelle Temperatur Zigbee","bodyElement":"CustomTextBody","label":"Vogelzimmer","showState":true,"secondaryStatesKeys":[],"CustomTextBodyConfig":{"aktuelle Temperatur":{"text":"gemessene Temperatur"},"aktuelle Temperatur Zigbee":{"text":"gemessene Temperatur"}}},{"type":"device","deviceId":"thermovogelzimmer_22941","id":"4275df86-61d9-4453-a024-9edbe9e7b96a","primaryStateKey":"Zieltemperatur","bodyStateKey":"Zieltemperatur","bodyElement":"LevelBody","label":"eingestellte Temperatur","showState":true,"secondaryStatesKeys":[],"CustomTextBodyConfig":{"aktuelle Temperatur":{"text":"Zieltemperatur"}}},{"type":"divider","id":"80dd968d-2e79-4e93-aa47-413d468c22e0"},{"type":"device","deviceId":"thermoküche_c25a0","id":"b4017f53-3918-4066-9272-11d8924631d9","primaryStateKey":"aktuelle Temperatur","bodyStateKey":"aktuelle Temperatur","bodyElement":"CustomTextBody","label":"Küche","showState":true,"secondaryStatesKeys":[],"CustomTextBodyConfig":{"aktuelle Temperatur":{"text":"gemessene Temperatur"}}},{"type":"device","deviceId":"thermoküche_c25a0","id":"f2736f7d-6001-42a7-ad38-c88cd5a21734","primaryStateKey":"Zieltemperatur","bodyStateKey":"Zieltemperatur","bodyElement":"LevelBody","label":"eingestellte Temperatur","showState":true,"secondaryStatesKeys":[],"CustomTextBodyConfig":{"aktuelle Temperatur":{"text":"Zieltemperatur"}}}],"revision":"a257b","label":"Thermostate","hideTitle":false},"ac88b558-55d3-43cc-a2a2-874e7daeb0a0":{"id":"ac88b558-55d3-43cc-a2a2-874e7daeb0a0","config":{"dense":false,"horizontal":false,"stacked":false},"title":"Szenen","icon":"","module":"StateList","items":[{"type":"device","deviceId":"af418ed1-7f54-4aca-a308-2e77226073ad","id":"1a20ff22-06a8-46fe-b70a-c8b4289475b7","primaryStateKey":"scene.o.Gute_Nacht","bodyStateKey":"scene.o.Gute_Nacht","bodyElement":"","label":"Gute Nacht","showState":false,"actionElement":"ButtonAction","ButtonActionConfig":{"scene.o.Gute_Nacht":{"labelTurnOff":"aktivieren","labelTurnOn":"Aktiv","buttonSize":"sm","showState":false}},"isInGroup":false}],"revision":"51c65","_updated":1672307320543},"024016ae-11a3-481a-b4ce-c682309ba0b4":{"id":"024016ae-11a3-481a-b4ce-c682309ba0b4","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"6c35b9bd-95bc-4116-a51a-5a9520e52f82","id":"a0c4f5c6-03fc-4789-8a91-cd6dfb210dd2","primaryStateKey":"Esso Willich e10","bodyStateKey":"Esso Willich e10","bodyElement":"","label":"Super e10","secondaryStatesKeys":["Esso Willich Öffnungszeiten"]}],"revision":"45d27","icon":"","label":"","hideTitle":false,"title":"Esso | Willich"},"b04962b4-f162-430c-9f5f-695e1a959d8a":{"id":"b04962b4-f162-430c-9f5f-695e1a959d8a","config":{"size":"contain","refresh":0,"refreshMethod":"whitespace","url":"https://upload.wikimedia.org/wikipedia/commons/thumb/0/0e/Esso-Logo.svg/1024px-Esso-Logo.svg.png"},"module":"DisplayImage","revision":"509a9","items":[],"hideSeparator":false,"title":"Spritpreise e10","icon":"mdi-gas-station"},"b909c5d9-31d3-4b68-be6c-804728790d78":{"id":"b909c5d9-31d3-4b68-be6c-804728790d78","config":{"dense":false,"horizontal":false,"stacked":false},"module":"StateList","items":[{"type":"device","deviceId":"7f499958-68ac-449c-ab39-9ccab9bbd1fd","id":"f5d7de2d-a1de-4cb3-ae9b-a31c18c2fdc0","primaryStateKey":"Nächste Abholung Tonne","bodyStateKey":"Nächste Abholung Tonne","bodyElement":"","label":"Nächste Abholung","showState":true,"secondaryStatesKeys":["Nächste Abholung Wochentag","Nächste Abholung Tage"]},{"type":"divider","id":"b68c9090-a4aa-4a95-969a-dd7c73c7dec2"},{"type":"device","deviceId":"7f499958-68ac-449c-ab39-9ccab9bbd1fd","id":"caa24bc3-7f36-40ec-ba90-b23cc10144b2","primaryStateKey":"Graue Tonne","bodyStateKey":"Graue Tonne","bodyElement":"","label":"Graue Tonne","showState":true,"secondaryStatesKeys":["Graue Tonne Wochentag","Graue Tonne Datum"]},{"type":"device","deviceId":"7f499958-68ac-449c-ab39-9ccab9bbd1fd","id":"780c4fe2-56fb-4c7f-8c09-43172ddd186c","primaryStateKey":"Gelbe Tonne","bodyStateKey":"Gelbe Tonne","bodyElement":"","showState":true,"label":"Gelbe Tonne","secondaryStatesKeys":["Gelbe Tonne Wochentag","Graue Tonne Datum"]},{"type":"device","deviceId":"7f499958-68ac-449c-ab39-9ccab9bbd1fd","id":"52537399-89ff-4643-a82d-d2d60d3a54ad","primaryStateKey":"Blaue Tonne","bodyStateKey":"Blaue Tonne","bodyElement":"","showState":true,"label":"Blaue Tonne","secondaryStatesKeys":["Blaue Tonne Wochentag","Blaue Tonne Datum"]}],"title":"Abfallkalender","revision":"806a6"}}`

`"bodyElement": "" ` habe ich gefunden und in `"bodyElement": null` geändert aber hat leider nichts gebracht.

**Comment by Hunduster** [comment]
OK, hab's hinbekommen.

Downgrade auf die 3.0.15, Backup zurückgespielt. Update auf die 3.1.2 dann Update auf die 3.1.3-beta.29. Sieht alles gut aus. Danke!
