### ISSUE TITLE
Kein Trigger Popup

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#2124]
Seit mehreren Versionen ist es bereits so das einige Einträge keine visuellen Trigger angezeigt bekommen.
Meist sind dies jene die manuell ein Gewerk zugewiesen bekommen haben.
Hier hilft nur ein komplett löschen und neu hinzufügen damit es wieder klappt.

![tracklist](https://user-images.githubusercontent.com/25475385/209438434-2d60a556-faac-4d58-97d5-85bd44d1f2f0.gif)

**Comment by mcuiobroker** [comment]
Console?
`iob upload jarvis`

**Comment by duczz** [comment]
upload bringt nix,
Jup im Expertenmodus

**Comment by Zefau** [comment]
schau nochmal mit `v.3.1.3-beta.0`

**Comment by Zefau** [comment]
`v3.1.3-beta.1`
