### ISSUE TITLE
Pro Popup

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#2125]
Ist es möglich den Popup im nicht Pro Modus auszublenden ohne extra alle CSS und Formatierungen zu löschen?
![image](https://user-images.githubusercontent.com/25475385/209438776-7202bbe8-8902-4f17-bbe9-45fe2043543a.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.0`

**Comment by Zefau** [comment]
`v3.1.3-beta.1`

**Comment by duczz** [comment]
Wunderbar, danke
