### ISSUE TITLE
v3.1.2 Fehlendes Gewerk in einem Gerät führt zur Nicht-Anzeige von Geräte-Konfiguration

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2126]
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/3574

https://forum.iobroker.net/topic/59201/jarvis-v3-1-0-beta-just-another-remarkable-vis/178

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.0`

**Comment by Zefau** [comment]
`v3.1.3-beta.1`

**Comment by Zefau** [comment]
@mcuiobroker das hier passt?
