### ISSUE TITLE
v3.1.2: Notification area too small

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#2127]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

v3.1.2: Notification area is too small. I detected this on PC (MS Edge) as well as with Android (Fully Browser).

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![image](https://user-images.githubusercontent.com/79741077/209863369-ab3d469e-4dfc-4935-89cd-2b9eb0f13a0e.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by mcuiobroker** [comment]
Hab mal einige Notifications eingegeben. Sieht normal aus.

-> `iob upload jarvis` auf der console?

![image](https://user-images.githubusercontent.com/84818934/209886847-6d56bef0-b6e0-4c3b-8eeb-9a3c5fa493c6.png)

**Comment by RkcCorian** [comment]
@mcuiobroker : Nope, Problem ist auch nach ```iob upload jarivs``` noch da. Beim initialen Laden sieht es noch gut aus, aber wenn er alle ~282 Meldungen geladen hat passiert es. Evtl. liegt es an der höheren Anzahl an Meldungen?!

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.2`

**Comment by Zefau** [comment]
@RkcCorian

**Comment by RkcCorian** [comment]
@Zefau : Sorry für die späte Rückmeldung, hatte leider bislang keine Zeit. Hab es gerade mit der ```v3.1.3-beta.13``` versucht, wollte auch die Android App testen, allerdings konnte ich es nicht. Ich habe https, vielleicht macht das Probleme. Mit der v3.2.2 (und zuvor) bislang keine Probleme gehabt.

Zugriff über Fully lädt die erste Seite mit dem Log, was soweit normal aussieht, allerdings "verharrt" die Jarvis Seite aber dort und lädt nicht weiter. Letzter Eintrag "Valid Pro User: ..."
Die Android-App (3.1.3-beta.9) wirft lauter Fehlermeldungen, hatte "Trust Unsecure Certs" angehakt. Es kommt mit der App "Error: xhr poll error"

**Comment by Zefau** [comment]
Ich nutze jarvis auch über `https` mit selbst-signiertem Zertifikat. Wichtig ist, dass beide Optionen aktiviert sind, aber klingt, als hättest du das gemacht? 

Hast du ggf. das Problem mit der Konvertierung, siehe https://github.com/Zefau/ioBroker.jarvis/issues/2208. Wie sieht dein Datenpunkt `jarvis.0.widgets` aus?

**Comment by RkcCorian** [comment]
@Zefau : Hatte auch schon #2208 gesehen, habe das Problem aber nicht. Das Problem besteht mit Tablet und Android Handy, PC kein Problem, daher sollte ```jarvis.0.widgets``` ok sein, kann später nochmal schauen.
Musst diesen Issue nicht zwingend öffnen, ich konnten ihn nur leider nicht testen, aufgrund meines Problems.

**Comment by Zefau** [comment]
> Anmerkung: Über den PC lädt JARVIS soweit normal

Über PC kannst du es testen, oder? Dann verlagern wir das Android-Verbindungsproblem in ein dediziertes Issue.

**Comment by Zefau** [comment]
alles gut, so stressig ist es nicht ;-)

**Comment by RkcCorian** [comment]
@Zefau : So, nun ein Update...
Ich habe meinen TestContainer nochmal komplett aktualisiert (Node.js, etc.) Nun lädt die Seite auch auf dem Handy normal und ich kann bestätigen, dass dieser Issue behoben wurde. Der Notification-Bereich ist nun so groß wie er sein soll.

Kannst schließen :-)

Hab das apk mit beta.11 aufs Handy runtergeladen, allerdings gibt es weiterhin den "Error: xhr poll error". Einfach ein "normales" Issue erstellen oder muss ich das irgendwie markieren?
