### ISSUE TITLE
Modul Adapter Log:   ENOENT: no such file or directory

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#2128]
Hallo,

das Modul Adapter Log funktioniert bei mir nicht. Ev. wegen Windows?
Oder hat es was mit current zu tun? Den gibt es bei mir nicht! 

![Screenshot (5179)](https://user-images.githubusercontent.com/41079106/209865985-641eaaf4-c39f-45bf-99d5-6ca5d8021e08.png)

![Screenshot (5178)](https://user-images.githubusercontent.com/41079106/209866000-19426279-a539-43e4-8805-c83385b9f6ce.jpg)

Mein System:

Plattform: Windows
RAM: 16 GB 
NODE.JS: V16.19.0
NPM: 8.19.3
JS Controller: 4.0.24
Admin: 6.3.5
WS: 2.3.4
WEB: 5.4.1
Socket.io: 6.3.3
Script Engine: 6.1.4
IOT: 1.14.2
VIS: 1.4.15
VIS2. 2.0.10
Jarvis: 3.1.2

**Comment by Zefau** [comment]
schau nochmal mit `v.3.1.3-beta.0`

**Comment by sigi2345** [comment]
> schau nochmal mit `v3.1.3-beta.0`

Jarvis startet nicht mehr!

![Screenshot (5185)](https://user-images.githubusercontent.com/41079106/210315951-da87b4c6-19bc-443f-a4ff-2834f3ae8871.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.1`

**Comment by sigi2345** [comment]
> schau nochmal mit `v3.1.3-beta.1`

Super, funktioniert mit v3.1.3-beta.2
