### ISSUE TITLE
v3.1.2 - Icons werden verzögert geladen

### ISSUE THREAD

**Issue by pphlwmarcel** [Zefau/ioBroker.jarvis#2129]
In meiner Installation mit v3.1.2 werden Icons sehr verzögert bzw. garnicht geladen. Insbesondere auf Mobilen Devices (iPhone/Safari und FireTablett/Fully) werden die Icons teilweise nicht geladen bzw. die Verzögerung ist noch größer als auf einem Windows PC mit Firefox/Chrome)

Im Fully Browser betrift es insbesondere die Bilddateien des Wetter Widgets, die garnicht geladen werden.

`App Welcome to jarvis v3.1.2 index-ec356f16.js:96:593326
App using instance 0. index-ec356f16.js:96:593937
App Time - Router Ready: 657.00ms index-ec356f16.js:96:593985
15:28:23.754 | INFO | CONNECTION | Connecting to https://<IP>:8400 (#1)... index-ec356f16.js:30:570
15:28:23.904 | INFO | SOCKET | Connected to https://<IP>:8400. index-ec356f16.js:30:570
15:28:23.906 | INFO | SOCKET | Listen for messages.. index-ec356f16.js:30:570
App Time - Socket connected: 825.00ms index-ec356f16.js:96:594103
Received an Update for Settings. index-ec356f16.js:96:524787
15:28:24.036 | DEBUG | PRO | Using 933811fc-e1f6-83d9-c665-03dd1269b087 
Proxy { <target>: {…}, <handler>: {…} }
index-ec356f16.js:30:570
15:28:24.578 | INFO | PRO | Valid Pro User: *********** ********** index-ec356f16.js:30:570
App Time - Got Pro, Settings and ioBroker Meta: 1489.00ms index-ec356f16.js:96:595160
App Time - Got Users and Groups: 1490.00ms index-ec356f16.js:96:595478
Received an Update for Devices. index-ec356f16.js:96:528701
App Time - Got Devices: 1527.00ms index-ec356f16.js:96:595811
Received an Update for Widgets. index-ec356f16.js:96:522770
Received an Update for Layout. index-ec356f16.js:96:525103
Received an Update for Styles. index-ec356f16.js:96:522360
Received an Update for Scripts. index-ec356f16.js:96:522435
App Time - Got Devices, Layout and Widgets: 1938.00ms index-ec356f16.js:96:597374
App Sentry is turned on. You may deactivate it in the adapter settings. index-ec356f16.js:96:598135
App Time - Got Config, Adapter, Scripts: 5452.00ms index-ec356f16.js:5:229
App Time - Verified installation: 5454.00ms index-ec356f16.js:5:229
downloadable font: rejected by sanitizer (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:0) source: https://<IP>:8082/jarvis/woff2/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ-83be7b2f.woff2
downloadable font: rejected by sanitizer (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:0) source: https://<IP>:8082/jarvis/woff2/materialdesignicons-webfont-633d596f.woff2
Die Ressource unter "https://<IP>:8082/jarvis/js/components-d15d7107.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/_commonjsHelpers-55d1ff45.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QTooltip-4895c5f4.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/json-editor-9cfef536.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/AdapterLogs-cfb6b73e.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/index-ec356f16.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QTable-6e0d87a2.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QVirtualScroll-c62d05fa.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/AdapterStatus-30c168cf.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QBadge-5f7ee245.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/Calendar-e764fd7a.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/EventList-b2f7a476.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/index-d04f0f01.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/___vite-browser-external_commonjs-proxy-afe9cd7a.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/index-266be270.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/Chart-12eb223f.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/index-f28d4228.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/DateTime-1dc49da8.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/DisplayImage-bdce8aff.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/HistoryGraph-be6072cb.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/HomeKitTile-a409a6c1.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/HtmlTable-ba743516.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/iFrame-95835e5a.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/JsonTable-343903fc.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/Map-d0800d15.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/MediaControl-c24d6e83.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/ScriptStatus-1b4c4b03.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QTree-0bf2b30a.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QSlideTransition-796d53d0.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/StateHTML-f0fa7cff.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/StateList-c88a62f6.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/StateListGroup-0214a250.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/StateListItem-0b96fe52.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/Weather-2ab3c0b0.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/Jarvis-e5976d12.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QFooter-94911ea5.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QHeader-afaec04f.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QBtnDropdown-9de8b66f.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/marked.esm-56a8835f.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/Sidebar-01f7528f.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QToolbar-cf9b42ef.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/QDrawer-2c10888d.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
Die Ressource unter "https://<IP>:8082/jarvis/js/index-b774bb04.js" wurde vorab geladen ("link-preload"), aber nicht innerhalb der ersten Sekunden verwendet. Es wird eine Überprüfung empfohlen, ob alle preload-Attribute korrekt gesetzt sind. index.html
downloadable font: rejected by sanitizer (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:0) source: https://<IP>:8082/jarvis/woff2/materialdesignicons-webfont-633d596f.woff2
downloadable font: rejected by sanitizer (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:0) source: https://<IP>:8082/jarvis/woff2/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ-83be7b2f.woff2
`

**Comment by Zefau** [comment]
Material Design Icons werden lokal vorgehalten und geladen. Alle anderen Icons (wenn Pro) werden via Iconify aus dem Internet geladen, wodurch es zu einer geringen Latenz kommen kann.

> Im Fully Browser betrift es insbesondere die Bilddateien des Wetter Widgets, die garnicht geladen werden.

Das Problem mit den Wetter-Icons ist bekannt und wird in den nächsten Versionen hoffentlich behoben.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.2`

**Comment by SlipKoRn88** [comment]
Wäre es denn nicht sinnvoll und möglich die Iconify Icons lokal zu haben? Im Falle eines Internetausfalles würde Jarvis weiterhin mit Icons funktionieren.

**Comment by Zefau** [comment]
Jo, würde grundsätzlich gehen. Man kann die Iconify API auf dem ioBroker (bzw. eher dem Raspberry) als lokalen Server installieren (siehe https://github.com/iconify/api).

Dann müsste ich in jarvis nur eine Einstellmöglichkeit implementieren, um vom Online-Server auf den Offline-Server zu schwenken.

Wäre aber ein eigener Feature Request.

**Comment by Zefau** [comment]
@pphlwmarcel @SlipKoRn88
