### ISSUE TITLE
Bug: Widget Groups

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#213]
Widget Groups are default aktiv, but shows disabled after creation

![image](https://user-images.githubusercontent.com/25475385/96371944-c128a400-1164-11eb-9a8b-47a9f0337b72.png)

**Comment by Zefau** [comment]
Sollte mit `v1.1.0-beta.39` behoben sein. Im Standard ist nun alles deaktiviert.

**Comment by duczz** [comment]
Funktioniert
