### ISSUE TITLE
v3.1.2 - Zeit im Date/Time Widget weicht ab

### ISSUE THREAD

**Issue by pphlwmarcel** [Zefau/ioBroker.jarvis#2130]
Die Zeit im Date/Time Widget weicht teilweise ab. Leider habe ich es zwar bisher häufiger Beobachten, aber nicht reproduzieren können.
Nach einem Reload der Seite stimmt die Zeit wieder.

**Comment by SlipKoRn88** [comment]
Das Problem habe ich bei mir auch. Sobald mein Tablet den Sperrbildschirm einschaltet, scheint die Uhr nicht mehr weiter zu Zählen. Wird Jarvis wieder durch Bewegungserkennung aufgerufen und der Sperrbildschirm verschwindet, setzt die Uhr bei der Zeit fort, an der sie beim Eintreten des Sperrbildschirms gestoppt hat. Einmal Reload und die Zeit stimmt wieder.

**Comment by Zefau** [comment]
schaut nochmal mit `v.3.1.3-beta.0`

**Comment by SlipKoRn88** [comment]
@Zefau mit der 3.1.3-Beta erhalte ich nur einen weißen Bildschrim

**Comment by Juicytronic** [comment]
> @Zefau mit der 3.1.3-Beta erhalte ich nur einen weißen Bildschrim

Das selbe bei mir.

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.3-beta.1`

**Comment by Juicytronic** [comment]
> schaut nochmal mit `v3.1.3-beta.1`

Weiser Bildschirm weg, läuft wieder 👍🏼

**Comment by SlipKoRn88** [comment]
Funktioniert ohne weißen Bildschirm

**Comment by SlipKoRn88** [comment]
Ich habe es jetzt mal ein paar Stunden beobachtet. Die Zeit wird leider nicht aktualisiert. Es ist nicht behoben

**Comment by Zefau** [comment]
wie sieht es mit `v3.1.3-beta.3` aus?

**Comment by SlipKoRn88** [comment]
Leider keine Verbesserung

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by SlipKoRn88** [comment]
In der v3.1.3-beta.9 scheint es nun behoben zu sein. Was sagen denn die anderen dazu?
