### ISSUE TITLE
iFrame-Widget content springt, wenn sich ein StateList-popup öffnet

### ISSUE THREAD

**Issue by Andr3asB** [Zefau/ioBroker.jarvis#2133]
Wie immer: Das gesamte Sytem ist auf dem neuesten Stand und es läuft Jarvis 3.1.2

Hat man auf einer Seite die Not zu scrollen, scrollt also nach unten und hat iFrame auf der Seite, dann passiert folgendes wenn man auf ein StateList Gerät klickt um das popup zu öffnen: Der iFrame-Content "fällt wort-wörtlich aus dem Rahmen"! Siehe Screenshots:
![image](https://user-images.githubusercontent.com/44557554/210118285-98620de8-f789-48c7-9440-a8fb1a1e2500.png)

![image](https://user-images.githubusercontent.com/44557554/210118352-1b62ffe7-d744-4a6c-b2a0-620538963669.png)

Das ist jetzt kein Beinbruch, aber beim Konfigurieren am PC passt das Dashboard (Smarthomescreen hängt im Portrait-Modus) nicht auf den Bildschirm und dabei ist es mir aufgefallen.

**Comment by Zefau** [comment]
Du hast vermutlich die Option "Aufrechterhalten" aktiviert? Mit deaktivierter Funktion tritt der Fehler vermutlich nicht auf, kannst du das bestätigen?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/977

**Comment by Andr3asB** [comment]
Wenn ich die Funktion "Aufrechterhalten" deaktiviere, dann tritt der Fehler nicht auf. Für mich sollte das auch erstmal keinen Unterschied machen, denke ich.
Falls Du unterstützung brauchst, einen Fix zu testen, dann sag bitte einfach Bescheid (beim coden bin ich Dir leider keine Hilfe, fürchte ich).

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.2`
iFrame wird doppelt geladen?
![jarvis v313-beta2 Fehler iframe doppelt geladen](https://user-images.githubusercontent.com/84818934/210485627-cadc9d58-f131-47b1-aaa8-fa4f9e930db2.gif)

**Comment by Andr3asB** [comment]
> `v3.1.3-beta.2`
> 
> iFrame wird doppelt geladen?

@mcuiobroker, das sieht mir aber nach einem anderen Problem aus, oder was meintest Du damit?

**Comment by Zefau** [comment]
Fehler aufgrund der Option `Aufrechterhalten`. Nachverfolgung via https://github.com/Zefau/ioBroker.jarvis/issues/977
