### ISSUE TITLE
v3.1.2 - Lizenzerneuerung

### ISSUE THREAD

**Issue by pphlwmarcel** [Zefau/ioBroker.jarvis#2134]
Wenn die Pro-Lizenz automatisch erneuert wird, wird eine neue Lizenz erstellt und die Lizenz muss manuell im jarvis wieder eingespielt werden.
Da es keine Übergangsphase gibt sind sofort alle Pro-Features (inklusive des Passwortschutzes) aufgehoben und die Visualisierung funktioniert nur noch sehr sporadisch.

Entweder hier muss eine Grace-Period eingeführt werden oder im Idealfall die Lizenz automatisch erneuert werden.

**Comment by Zefau** [comment]
Auf welcher Version warst du beim Lizenzwechsel? Auf v3.1 soll diese eigl automatisch getauscht werden.

**Comment by pphlwmarcel** [comment]
Ich war auf Version 3.1.2. Der Lizenzwechsel hat am 29.12.2022 nicht automatisch funktioniert.

**Comment by Zefau** [comment]
ab `v3.1.3-beta.2` sollte es klappen
