### ISSUE TITLE
Can`t install iobroker.jarvis

### ISSUE THREAD

**Issue by csplkiller** [Zefau/ioBroker.jarvis#2135]
I can't install iobroker.jarvis, I have the latest stable versions of node and npm.

```
root@smarthome:/home/smarthome# iobroker add jarvis --debug --host smarthome

NPM version: 9.2.0
Installing iobroker.jarvis@3.1.2... (System call)
npm ERR! code EBADENGINE
npm ERR! engine Unsupported engine
npm ERR! engine Not compatible with your version of node/npm: iobroker.jarvis@3.1.2
npm ERR! notsup Not compatible with your version of node/npm: iobroker.jarvis@3.1.2
npm ERR! notsup Required: {"node":"^18 || ^16 || ^14.19","npm":">= 6.13.4","yarn":">= 1.21.1"}
npm ERR! notsup Actual:   {"npm":"9.2.0"}

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2023-01-02T15_08_29_188Z-debug-0.log
host.smarthome Cannot install iobroker.jarvis@3.1.2: 1
```

node -v
v19.3.0

npm -v
9.2.0

**Comment by Sineos** [comment]
`npm ERR! notsup Required: {"node":"^18 || ^16 || ^14.19","npm":">= 6.13.4","yarn":">= 1.21.1"}
`

NPM is already telling you what is wrong: v19 is not supported and is also not supported from iobroker itself. iobroker currently officially supports npm v8.x and node v16

**Comment by Zefau** [comment]
The in jarvis specified supported versions are outdated and will be updated with v3.1.3. Thus, Node.js v19 will be supported (even though it is not long-term-supported (LTS)).

**Comment by Zefau** [comment]
please check again with `v.3.1.3-beta.0`

**Comment by Zefau** [comment]
`v3.1.3-beta.1`

**Comment by csplkiller** [comment]
I can't figure out how to install this version adapter

**Comment by csplkiller** [comment]
> please check again with `v3.1.3-beta.0`

I can't figure out how to install this version adapter

**Comment by mcuiobroker** [comment]
v3.1.3-beta.0 was wrong, so use the last one v3.1.3-beta.4.

**Comment by csplkiller** [comment]
`root@smarthome:/home/smarthome# iobroker add iobroker.jarvis@3.1.3-beta.4 --debug --host smarthome
NPM version: 9.2.0
Installing iobroker.jarvis@3.1.3-beta.4... (System call)
npm ERR! code ETARGET
npm ERR! notarget No matching version found for iobroker.jarvis@3.1.3-beta.4.
npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! notarget a package version that doesn't exist.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/iobroker/.npm/_logs/2023-01-12T18_32_18_637Z-debug-0.log
host.smarthome Cannot install iobroker.jarvis@3.1.3-beta.4: 1
`

What am I doing wrong ?
I haven't installed beta adapters yet.

**Comment by mcuiobroker** [comment]
Why don't you install it from ioBroker Adapters?
Which Repository is active?
![image](https://user-images.githubusercontent.com/84818934/212151685-2f3c6f86-c5e4-444e-abd8-a74b34599b78.png)
Activate Expertmode
![image](https://user-images.githubusercontent.com/84818934/212151798-06c2b497-7d7f-4d2f-9f4e-f0dbdc6f5c92.png)
And then install via Cat -> from github
![image](https://user-images.githubusercontent.com/84818934/212151921-b5f50d87-c8c4-4a8c-b1ab-a527d5149093.png)

**Comment by Zefau** [comment]
@csplkiller is this solved?
