### ISSUE TITLE
Bug: States / Widget

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#214]
Nach neu Anlage eines neuen States, wird der Wert in dem Widgets welcher damals auf Platz eins war durch den neuen State auf Platz 1 ersetzt, sprich die Zuordnung wird nicht gespeichert. - Reproduzierbar

**Comment by Zefau** [comment]
Sollte mit `v1.1.0-beta.39` behoben sein. Das Widget muss aber erst 1x gespeichert werden (damit die Werte korrekt übernommen werden). Danach sollte das Hinzufügen eines neuen Datenpunkts die Widget Werte nicht mehr ändern.

Kannst du das bestätigen?

**Comment by duczz** [comment]
Klappt einwandfrei - Danke
