### ISSUE TITLE
Zugriff über iobroker.pro nicht möglich

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#2142]
Wenn ich Jarvis über [ioBroker.pro](http://iobroker.pro/) starte bekomme ich folgende Fehlermeldung: "Fehler beim Lesen der Geräte!"

![image](https://user-images.githubusercontent.com/61848539/210415892-e7ed9612-103b-4acb-8809-823b09aa801a.png)

**Comment by mcuiobroker** [comment]
Bekommst du jarvis denn in den Anwendungen angezeigt? Ich nicht.
![image](https://user-images.githubusercontent.com/84818934/210421236-3f6c6a30-269a-425f-9936-ade3e5bb06e5.png)

**Comment by uwe72** [comment]
Ich auch nicht,

**Comment by uwe72** [comment]
![image](https://user-images.githubusercontent.com/61848539/210422465-fed1e201-4989-43d7-b510-5dde48cd3cc0.png)

**Comment by uwe72** [comment]
Versuche es so direkt aufzurufen:
https://iobroker.pro/jarvis/index.html#/instance=0

**Comment by mcuiobroker** [comment]
#1430

**Comment by Zefau** [comment]
Hierzu gibt es bereits ein Issue, siehe https://github.com/Zefau/ioBroker.jarvis/issues/1430.
