### ISSUE TITLE
3.1.3-beta2 Smartphone: Widgetelemente werden nicht angezeigt

### ISSUE THREAD

**Issue by Rookiestyle** [Zefau/ioBroker.jarvis#2144]
Genutzte Version 3.1.3-beta2

Zu sehen auf den Screenshots: Widget - PC Anzeige - Smartphone Anzeige
`Rollo-All`ist ein BlindLevelAction mit dem ich alle Rollos im Haus steuere
`Erdgeschoss` ist eine Gruppe, also nur die "Überschrift"

![image](https://user-images.githubusercontent.com/36454520/210800212-da71a4cc-2872-4ffc-9d7b-595134f3cb53.png)
Auf dem Smartphone wird die Gruppe / Überschrift "Erdgeschoss" nicht angezeigt

![image](https://user-images.githubusercontent.com/36454520/210798380-4409afd1-03fb-42eb-8b51-e18537fead0b.png)
Auf dem Smartphone wird "Alle-Rollos" nicht angezeigt

Mit 3.1.2 stimmt die Anzeige noch

**Comment by Zefau** [comment]
schaut bitte nochmal mit `v3.1.3-beta.3`

**Comment by Rookiestyle** [comment]
Funktioniert, aber warum funktioniert mein Link nicht mehr und ich muss erst auf *Connect* Klicken?
Vor 3.1.3-beta3 gab es eine Weiterleitung zur ersten Seite bzw. zur Standardseite

`http://mpi:8082/jarvis/index.html#`

![Screenshot_20230108_235324_Chrome](https://user-images.githubusercontent.com/36454520/211223338-dfd0d94a-8d07-4380-9c37-f6aee23ac21d.jpg)

**Comment by Zefau** [comment]
schaut bitte nochmal mit `v3.1.3-beta.4`
