### ISSUE TITLE
Jarvis 3.1.2 lädt Grafana iFrame Widget nicht mehr

### ISSUE THREAD

**Issue by bkunrath** [Zefau/ioBroker.jarvis#2146]
Hi,

Grafana iFrame Widgets in einem Tab in dem IFrame und Statelists angezeigt werden werden nicht mehr korrekt geladen! Werden iFrame Widgets als einzige Widgets im Frame geladen -> kein Problem.

Unter 3.0 hat  das einwandfrei funktioniert. Was mach ich falsch?

![C1BAB912-62AA-4F60-B9B8-FB9E6680416D_1_10
![3FCA7E53-BEB7-4614-90EC-F65530771158_1_102_o](https://user-images.githubusercontent.com/6825396/210979999-e1273428-ef7d-4cae-b8b1-f5b15835d7d3.jpeg)
5_c](https://user-images.githubusercontent.com/6825396/210979277-6814e01f-d7ce-4f3d-a1f7-40d79d9290db.jpeg)

**Comment by mcuiobroker** [comment]
Sandbox aktivieren und alle Optionen auswählen.

**Comment by bkunrath** [comment]
Im Widget angeschalten und funkt! Super, danke für die schnelle Hilfe.
