### ISSUE TITLE
Bug: Save Layout Tab after save

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#215]
Currently the first Tab is default after click save, could you make it possible to stay on the current Tab?

**Comment by Zefau** [comment]
@duczz added in `v1.1.0-beta.40`.

**Comment by duczz** [comment]
Not working on Beta41

**Comment by Zefau** [comment]
Does this work for you now in beta.44`?`

**Comment by duczz** [comment]
not working on latest beta

**Comment by Zefau** [comment]
This is very weird. Maybe for clarification: You switch tabs in the configuration between devices, layout and settings. The latest tab selected will be remembered when the configuration is being saved.

This is reflected in `jarvis.0.settings` by `configTab` and `configExpertMode`, e.g.:
```
{
   "language":"de-DE",
   "themeDarkMode":true,
   "sendUsageData":true,
   "configExpertMode":false,
   "configTab":"devices"
}
```

Do you have such entries?

**Comment by duczz** [comment]
Ich glaub wir reden von 2 unterschiedlichen Punkten, ich mein das Layout "Vis" sprich nicht die Einstellungen.

**Comment by Zefau** [comment]
Dann haben wir uns falsch verstanden. Das genannte Anliegen wurde bereits angefragt: https://github.com/Zefau/ioBroker.jarvis/issues/230
