### ISSUE TITLE
v3.1.3-beta.2 Überschriften nicht sichtbar im lightMode

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2150]
PRO Account
![image](https://user-images.githubusercontent.com/84818934/211118351-670e3c70-4922-4d24-8dd6-53e06dba080c.png)

Hilfe
![image](https://user-images.githubusercontent.com/84818934/211118380-f4bc9623-b074-4e5f-95e6-37382aca5185.png)

**Comment by Zefau** [comment]
Sieht bei mir ok aus. Hast du was in den Styles?

![image](https://user-images.githubusercontent.com/14368811/211659411-a5db4dbf-3949-44f6-9af8-01172cab8024.png)

**Comment by mcuiobroker** [comment]
Mit `v3.1.3-beta.4` wieder ok.
