### ISSUE TITLE
v3.1.3-beta.4 App geht nur auf localhost -> nicht einstellbar?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2156]
![image](https://user-images.githubusercontent.com/84818934/211620314-a6537d97-20d8-4f62-b617-d46e249b4766.png)

**Comment by Zefau** [comment]
Hast du jetzt die Android app installiert? Der Fehler ist bekannt, weshalb ich es noch nicht "offiziell" released habe.

**Comment by mcuiobroker** [comment]
Ja.

**Comment by mcuiobroker** [comment]
`v3.1.3-beta7`
Zerstört komplett die Widgets.
![image](https://user-images.githubusercontent.com/84818934/214151482-325fddde-e48e-44eb-ac8f-b846e5ae32f4.png)
![image](https://user-images.githubusercontent.com/84818934/214151541-714672bc-a362-4c5f-8dfc-ea2ba44347e1.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.9`
