### ISSUE TITLE
v3.1.3-beta.4 iFrame Fehler bei google

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2157]
![image](https://user-images.githubusercontent.com/84818934/211627911-e30e5b56-2129-41a0-adba-fdb5e0e34abd.png)

Mit goggle Maps adresse
![image](https://user-images.githubusercontent.com/84818934/211628329-1ebe7e97-0f43-4463-bce6-14f21f114a90.png)

**Comment by Zefau** [comment]
https://stackoverflow.com/questions/8700636/how-to-show-google-com-in-an-iframe
