### ISSUE TITLE
Charts Y-Achse

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2159]
Hej,

wie kann ich die Y-Achse einstellen, sodass eine kleine Skalierung ist oder müsste er das theoretisch automatisch machen?

![image](https://user-images.githubusercontent.com/85995176/212345325-8fffc3da-9a86-4426-9f7d-a4d45671283d.png)

Grüße

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/module/historygraph#min-max-bereich-automatisch

**Comment by Mephisto090** [comment]
> https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/module/historygraph#min-max-bereich-automatisch

welche Temp. Sensoren benutzt du?

**Comment by mcuiobroker** [comment]
HUE-Sensoren

**Comment by Mephisto090** [comment]
Lässt sich auch sowas wie das hier machen?

`[{"min":"dataMin-10","max":"dataMax+10"}]`

**Comment by mcuiobroker** [comment]
Ich glaube nicht, probier's.

**Comment by Mephisto090** [comment]
Ne geht ja nicht, sonst hätte ich nicht gefragt :D

**Comment by Zefau** [comment]
Dass sind die Echart Optionen, daran kann ich nichts beeinflussen.

**Comment by mcuiobroker** [comment]
Also man kann mit der boundaryGap-Option die oberer "Lücke" zum Wert einstellen.
"min" muss gesetzt werden und kann leider nicht über boundaryGap beeinflusst werden.
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/module/historygraph/beispiele/y-achse/boundarygap

**Comment by Sineos** [comment]
Hab nicht getestet, ob es in Jarvis auch funktioniert, aber in normalerweise in eCharts:

```
min: function (value) {
    return value.min - 20;
}
```

bzw. das Pendant mit `max`

**Comment by mcuiobroker** [comment]
Leider funktioniert das in jarvis nicht. Noch nicht?

**Comment by Zefau** [comment]
Was ist hier offen? `min` / `max` Funktion für die Y-Achse?

**Comment by mcuiobroker** [comment]
Ja
```
"min": "function (value) {
    return value.min - 20;
}"
```

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.11`

**Comment by Rookiestyle** [comment]
v3.1.3-beta15
Konfiguration Y-Achse
`{   "min": "function (value) { return value.min - 10; }",   "max": "function (value) { return value.max + 10; }" }`

![image](https://user-images.githubusercontent.com/36454520/215576180-aae4bb4f-2aa5-4608-a668-fa2ad62daf09.png)

bei `dataMin` oder festen Werten für min wie bsp. `1` ist die Anzeige genauso, die Y-Achse fängt immer bei 0 an, nutze sql.0 statt history.0, falls das einen Unterschied macht

**Comment by Mephisto090** [comment]
> nutze sql.0 statt history.0, falls das einen Unterschied macht

geht bei history.0 auch nicht :)

**Comment by Zefau** [comment]
schaut nochmal mit `v3.1.3-beta.16`

**Comment by Rookiestyle** [comment]
Keine Änderung.
Die Y-Achse beginnt nach wie vor bei 0. Egal ob ich eine Funktion, dataMin oder einer Konstante wie 1 definiere.

**Comment by Zefau** [comment]
Funktioniert bei mir:
```
{"min":"value => value.min - 200","max":"value => value.max + 200"}
```

![grafik](https://user-images.githubusercontent.com/14368811/216153351-df103a6c-daa6-4171-90b9-695fcbd15d6e.png)

![grafik](https://user-images.githubusercontent.com/14368811/216153579-0c299fbf-9fba-4ea2-a024-5d6189f25766.png)

**Comment by Zefau** [comment]
Euer Beispiel
```
 {   "min": "function (value) { return value.min - 10; }",   "max": "function (value) { return value.max + 10; }" }
```
wirft die Warnung: 
> SyntaxError: Function statements require a function name

**Comment by Rookiestyle** [comment]
Stimmt. Mir deiner Variante funktioniert es.

Ist `{   "min": "1",   "max": "3" }` bzw `{   "min": "dataMin",   "max": "dataMax" }` auch falsch?
Sieht bei mir beides so aus:
![Screenshot_20230201_212701_Chrome](https://user-images.githubusercontent.com/36454520/216155990-57ddf7e3-a654-451d-870b-98e830058837.jpg)

Mit `value =>` geht das zwar auch,  aber dataMin ging ja mal

**Comment by Rookiestyle** [comment]
In einem anderen Fall mache ich es jetzt so. Das erfüllt alle meine Anforderungen/Wünsche, mehr brauche ich zumindest nicht. 

`{  "min": "value => Math.floor(value.min/5)*5",  "max": "value => Math.ceil(value.max/5)*5"}`
Damit ist die Y-Achse immer das nächstkleinere/-größere von 5

**Comment by Rookiestyle** [comment]
Keine Änderung zu 3.1.3-beta.16, die Konfiguration mit `dataMin` oder absoluten Werten wird bei mir ignoriert

`value => value.min` oder `value => 1` bringt das erwartete Ergebnis.

**Comment by Zefau** [comment]
> Ist `{   "min": "1",   "max": "3" } bzw {   "min": "dataMin",   "max": "dataMax" }` auch falsch?

Funktioniert beides bei mir mit `v3.1.3-beta.17`

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.19`

**Comment by Rookiestyle** [comment]
Jetzt funktioniert alles
