### ISSUE TITLE
Bug: Widget Device Label

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#216]
derzeit wird das Geräte label nach dem hinzufügen in die Widgets in der Vis nicht richtig dargestellt, er nutzt in der Vis dann den devicenamen, erst nach einem mnauellen rename wird dann das korrekt devicelabel angezeigt
![image](https://user-images.githubusercontent.com/25475385/96414158-04c6f080-11ed-11eb-9b6c-7db3537d8759.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/217
