### ISSUE TITLE
Karte (Map widget) in der Ausrichtung  drehen

### ISSUE THREAD

**Issue by SevenUp666** [Zefau/ioBroker.jarvis#2162]
Ich nutze den Karten Widget, um den Standort meines geparkten Autos zu sehen (Großstadt, schlechte Parkmöglichkeiten, man parkt mal hier, mal da, Partner muss das Auto dann in der Umgebung suchen). Das funktioniert recht gut.

Blöd ist nur, dass die Ausrichtung der Karte nicht mit der Ausrichtung meines Tablets übereinstimmt. Wenn ich auf das Tablet schaue, dann ist Norden laut Karte vor mir (ist aber hinter mir), Osten auf der linken Seite (eigentlich auf der rechten). Das bedeutet, dass ich die Darstellung vor innerem Auge drehen muss um zu verstehen, ob mein Auto nun in der Seitenstrasse rechts von meinem Haus steht, oder links; hinter dem Haus oder davor,...

Abhilfe wäre, wenn ich die die Ausrichtung der Karte drehen könnte.
Leatflet unterstützt es wohl, aber ist es mit wenig Aufwand auch in Jarvis realisierbar?
https://www.npmjs.com/package/leaflet-rotate-map/v/0.2.5
https://www.npmjs.com/package/leaflet-rotate

Den Tipp aus dem iobroker Forum habe ich getestet
`.leaflet-container{
    transform: rotate(90deg);
}`
Das Resultat ist aber nicht gut, da wirklich alles im Widget gedreht wird.

**Comment by SevenUp666** [comment]
schade, das Interesse an dem Feature scheint nicht da zu sein :-/

**Comment by SevenUp666** [comment]
@Zefau besteht die Hoffnung, dass du es auch ohne weitere Befürworter implementierst? :-) Außer mir + 1 hat leider keiner gevotet

**Comment by Zefau** [comment]
Jo, sollte auch schnell umgesetzt sein, aber werde ich vor 3.2 nicht schaffen / machen. Aktuell sind einige Bugs offen, die erst weg müssen.

**Comment by SevenUp666** [comment]
Hallo @Zefau,

siehst du noch eine Chance, dieses Feature zu implementieren?

**Comment by Zefau** [comment]
kommt mit der nächsten alpha

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.6` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.6`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by SevenUp666** [comment]
@Zefau die Karte kann nun in den Einstellungen des Widgets gedreht werden. Top!
Dabei wird nur die Darstellung der Karte gedreht, d.h. auch die Bezeichnungen (Straßennamen, Hausnummern).
Ich vermute, dass es die einzig mögliche Lösung ist?

<img width="325" alt="2023-11-08 21_39_47-Домовой" src="https://github.com/Zefau/ioBroker.jarvis/assets/76970669/7dcd2b56-aa46-49d4-a027-b10cb412eac6">

**Comment by Zefau** [comment]
Also in der Demo von `leaflet-rotate` (https://raruto.github.io/leaflet-rotate/examples/leaflet-rotate.html) scheinen die Labels nicht mit gedreht zu sein. Muss ich nochmal schauen.

**Comment by Zefau** [comment]
Ich muss mich korrigieren, in der Demo scheint es auch nicht korrekt dargestellt zu werden. Kannst du das bestätigen? Du hast 180° gedreht oder?

**Comment by SevenUp666** [comment]
Richtig, ich habe es um 180° gedreht.
Und auch richtig, dass auch in der Demo die Labels mitgedreht zu werden. :-/

**Comment by Zefau** [comment]
Dann befürchte ich geht es nicht anders. Mit `transform: rotate` war es dasselbe oder?

**Comment by SevenUp666** [comment]
Wenn ich es nun mit `.leaflet-container{ transform: rotate(90deg); }` probiere, dann sehe ich dadurch keine Veränderungen mehr?! Seltsam.
Wenn ich mich aber richtig erinnere, dann war das mit der Anpassung so, dass nicht nur die Karte und Labels (Straßennammen, Hausnummern) gedreht wurden, sondern auch die Labels von Jarvis (in meinem Fall die Icons von "Auto" und "Haus", oberer Screenshot)

--> ich bin mit der aktuellen Lösung aber trotzdem recht zufrieden! Ich danke dir!
Soll ich den Thread dann schließen?

**Comment by Zefau** [comment]
Klasse. Ja, wenn es passt, gerne schließen.
