### ISSUE TITLE
Warnungen für Callback Fehler bei NON-PRO begrenzen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2166]
Es führt teilweise dazu, dass man nicht mehr arbeiten kann und den "Fehler" rückgängig machen kann.
![image](https://user-images.githubusercontent.com/84818934/212558156-3e0b2a61-7aab-45f3-be51-465825e8dc01.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by Zefau** [comment]
@mcuiobroker
