### ISSUE TITLE
Einstellungen / Seiteneinstellungen / Homepage das Dashboard (Main Site - Dashboard) wird nicht gespeichert

### ISSUE THREAD

**Issue by reutli** [Zefau/ioBroker.jarvis#2167]
Habe versucht unter Einstellungen / Seiteneinstellungen / Homepage das Dashboard (Main Site - Dashboard) zu hinterlegen.
Leider wird der Wert nicht gespeichert.

Eingesetzte Version JARVIS 3.1.2 nicht PRO

Getestete Browser:
Safari Mac OS X
Chrome
Firefox

Damit funktioniert, das automatische Umschalten nach Zeit x (Homepage Rückkehr) natürlich nicht.

Ist dieser Fehler bekannt?

***

Tried to save the dashboard (Main Site - Dashboard) under Settings / Site Settings / Homepage.
Unfortunately, the value is not saved.

Used version JARVIS 3.1.2 not PRO

Tested browsers:
Safari Mac OS X
Chrome
Firefox

With this, the automatic switching after time x (homepage return) does not work, of course.

Is this error known?

**Comment by reutli** [comment]
Leider nicht, habe x-fach gespeichert in allen Browsern. Werde jetzt versuchsweise kompletten Neustart des Clients versuchen, damit ich alles versucht habe (Cache löschen etc. natürlich auch schon versucht).

**Comment by reutli** [comment]
Du meinst auf dem iobroker Rechner?

Hier der Fehler aus der Chrome Konsole:
`index-ec356f16.js:5 UNKNOWN STATE settings Proxy {tourIntroduction: true, tourInterface: true, tourConfiguration: false, configExpertMode: false, configTab: 'settings', …} pageHome undefined 0559b5e5-1c56-4ea4-8211-d51226417202
(anonymous) @ index-ec356f16.js:5
set @ index-ec356f16.js:96
(anonymous) @ index-ec356f16.js:29
l @ index-edf6fdb8.js:1
callWithErrorHandling @ index-ec356f16.js:1
callWithAsyncErrorHandling @ index-ec356f16.js:1
emit$1 @ index-ec356f16.js:1
onSelect @ components-d15d7107.js:60
callWithErrorHandling @ index-ec356f16.js:1
callWithAsyncErrorHandling @ index-ec356f16.js:1
emit$1 @ index-ec356f16.js:1
_ @ index-ec356f16.js:96
onClick @ index-ec356f16.js:96
callWithErrorHandling @ index-ec356f16.js:1
callWithAsyncErrorHandling @ index-ec356f16.js:1
emit$1 @ index-ec356f16.js:1
E @ index-ec356f16.js:1
D @ index-ec356f16.js:1
callWithErrorHandling @ index-ec356f16.js:1
callWithAsyncErrorHandling @ index-ec356f16.js:1
n @ index-ec356f16.js:1
o @ index-ec356f16.js:14`

<img width="720" alt="Bildschirmfoto 2023-01-16 um 14 10 15" src="https://user-images.githubusercontent.com/62477965/212686244-25e4fa59-e614-477e-ab5a-c9b2f1ac1a69.png">

**Comment by reutli** [comment]
Status:

- Client neu gestartet
- `iob upload jarvis` vollzogen
- iobroker neu gestartet
- andere Seite als Homepage versucht

Fehler bleibt.
Ideen?

**Comment by reutli** [comment]
> Gibt es bei dir den DP unter `settings` überhaupt?

Das wird es wohl sein....:
<img width="1960" alt="Bildschirmfoto 2023-01-16 um 19 38 31" src="https://user-images.githubusercontent.com/62477965/212746671-fbb5d2b8-7fae-428a-8b79-286743a8af09.png">

und jetzt?

**Comment by mcuiobroker** [comment]
Die `settings`speichern
![image](https://user-images.githubusercontent.com/84818934/212746925-eb30d194-23c4-4f42-8a9d-50e61302d202.png)
jarvis-Instanz stoppen
Dann das Verzeichnis `settings`löschen und jarvis-Instanz neu starten.
Die gespeicherten Settings wieder einfügen.

**Comment by reutli** [comment]
Damit es nicht schief geht:
Settings/Wert öffnen,
<img width="1875" alt="Bildschirmfoto 2023-01-16 um 20 38 03" src="https://user-images.githubusercontent.com/62477965/212754744-628b3267-bfa0-487b-ba58-47eee059e425.png">

 JSON kopieren, in Editor zwischenspeichern, Instanz stoppen, Verzeichnis "Settings" in iobroker löschen, Instanz starten, Wert öffnen und aus Speicherung einsetzen.

Korrekt?

**Comment by mcuiobroker** [comment]
Ja.

**Comment by reutli** [comment]
nope, hat nichts gebracht. Eigentlich auch klar, da die gleiche Struktur ja wieder angelegt wird... und damit pageHome ja immer noch nicht da (falls das der Fehler ist)

**Comment by mcuiobroker** [comment]
Welche Version hast du denn?

**Comment by reutli** [comment]
siehe oben, 3.1.2

**Comment by reutli** [comment]
gleicher Effekt auch mit 3.1.3 b4 - auch klar, weil vermutlich "pageHome" immer noch fehlt...

<img width="1461" alt="Bildschirmfoto 2023-01-16 um 20 55 19" src="https://user-images.githubusercontent.com/62477965/212756742-937cfbb1-5576-42c7-b361-ae6299cbcfcd.png">
<img width="808" alt="Bildschirmfoto 2023-01-16 um 20 55 53" src="https://user-images.githubusercontent.com/62477965/212756810-1bb720bc-8eb3-488d-b78f-4c6ff0def19c.png">

**Comment by mcuiobroker** [comment]
Keine Ahnung warum er den DP nicht anlegt. Bleibt nur ein komplettes Löschen und Neuanlegen von jarvis?
Versuch erst mal ein Objekt-Upload unter Objekte
[jarvis.0.settings.pageHome.txt](https://github.com/Zefau/ioBroker.jarvis/files/10429118/jarvis.0.settings.pageHome.txt)

![image](https://user-images.githubusercontent.com/84818934/212757328-337e862b-3faa-4594-a865-e68379439523.png)

**Comment by reutli** [comment]
Habe es gelöst:
Datenpunkt aus anderem angelegt und korrekt bezeichnet, Instant neu gestartet und gespeichert ==> jetzt da!

<img width="1854" alt="Bildschirmfoto 2023-01-16 um 21 03 52" src="https://user-images.githubusercontent.com/62477965/212757858-f2861150-20e1-47b5-bde6-165a387e368f.png">


Kann so einfach sein...

**Comment by Zefau** [comment]
schaut bitte nochmal mit `v3.1.3-beta.9`

**Comment by Zefau** [comment]
@reutli
