### ISSUE TITLE
bug: Devicelabel

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#217]
derzeit wird das Geräte label nach dem hinzufügen in die Widgets in der Vis nicht richtig dargestellt, er nutzt in der Vis dann den devicenamen, erst nach einem manuellen rename wird dann das devicelabel korrekt in der vis angezeigt.
![image](https://user-images.githubusercontent.com/25475385/96414158-04c6f080-11ed-11eb-9b6c-7db3537d8759.png)

**Comment by Zefau** [comment]
@duczz what's the actual issue? You expect the state label to be displayed instead of the device label?

**Comment by duczz** [comment]
I can't explain it, you have to see it, maybe via discord

**Comment by Zefau** [comment]
@duczz can we align this today and meet via Discord?

For clarification: The label defined in the Widget configuration will only apply in the widget - not the device details. The labels for the device details need to be configure in the device configuration.

**Comment by duczz** [comment]
@Zefau hättest du jetzt zeit?

**Comment by Zefau** [comment]
Jo

**Comment by duczz** [comment]
bist im iobroker discord?

**Comment by Zefau** [comment]
Ne. Heiße Zefau (#8011)

**Comment by Zefau** [comment]
@duczz hopefully resolved with `v1.1.0-beta.105`.

**Comment by cryptedx** [comment]
Ich weiß nicht genau ob es das selbe Problem ist, aber ich habe aktuell bei bete 105 auch diesen Fehler

<img width="245" alt="Bildschirmfoto 2020-11-15 um 17 46 05" src="https://user-images.githubusercontent.com/20707078/99191068-89644a80-276a-11eb-890b-58263c890e4f.png">

**Im Gerät:**
![image](https://user-images.githubusercontent.com/20707078/99191103-c597ab00-276a-11eb-9f3f-fa94f9b0665f.png)

**Im Widget:**
![image](https://user-images.githubusercontent.com/20707078/99191081-9f720b00-276a-11eb-8043-454e96a356cb.png)

Wenn ich es hier ändere, dann passt es sich an:
![image](https://user-images.githubusercontent.com/20707078/99191128-efe96880-276a-11eb-8ac5-d6be1cd225b9.png)

Also stimmt da etwas nicht.

**Comment by Zefau** [comment]
@duczz @cryptedx hopefully resolved with `v1.1.0-beta.112`.

**Comment by cryptedx** [comment]
Fix verified!

**Comment by duczz** [comment]
nope is not working

**Comment by Zefau** [comment]
@duczz did you test with a new widget or an existing widget (or both) ?

**Comment by duczz** [comment]
mit was bestehendem, weil es nur ein Anzeige Fehler ist.

**Comment by Zefau** [comment]
Ich musste etwas anpassen aufgrund von https://forum.iobroker.net/post/525462.

@duczz Könntest du diesen Bug nochmal testen, ob es mit `v1.1.0-beat.134` noch passt?

**Comment by duczz** [comment]
@Zefau nope geht nicht mehr, das richtige label kommt nun nur noch im popup (bei neuanlage, bestehende passen noch)

**Comment by Zefau** [comment]
@duczz kannst du die `v1.1.0-beta.138` bitte prüfen, ob es damit wieder passt?

**Comment by duczz** [comment]
nope, geht nicht ^^

**Comment by duczz** [comment]
nope, geht auch damit noch nicht

**Comment by Zefau** [comment]
@duczz Kannst du mal die `v1.1.0-beta.140` prüfen?

**Comment by duczz** [comment]
Top, nun klappts wieder
