### ISSUE TITLE
Widgethöhe dynamisch oder 100% Höhe im Vollbildmodus

### ISSUE THREAD

**Issue by Rookiestyle** [Zefau/ioBroker.jarvis#2174]
Ist eines der beiden Dinge möglich?

https://jbaysolutions.github.io/vue-grid-layout/guide/properties.html#autosize
Widgethöhe per Parameter auf  Autosize stellen

> Says if the container height should swells and contracts to fit contents.

Wenn "Vollbild erlauben" auch die Höhe ändern würde, wäre das auch eine super Alternative, leider wird das Widget bei mir damit nur auf 100% Breite gezogen und die Höhe bleibt unverändert.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1339
