### ISSUE TITLE
PRO Filter Error obwohl der Filter funktioniert

### ISSUE THREAD

**Issue by Eldron81** [Zefau/ioBroker.jarvis#2176]
JARVIS v3.1.2
![console_screen_jarvis](https://user-images.githubusercontent.com/98782407/213247134-24ace795-1dd3-4aba-a750-e4bd608590dc.JPG)

**Describe the bug / Beschreibe den Fehler**
Ich habe eine StateList angelegt wo möglichst nur relevante Infos aus einer langen Liste angezeigt werden sollen. Ich möchte alles filtern was:
- Als Zahl größer 0
- Als Text größer Länge 1 und
- Nicht "BSH......Ready/Run" (zwei Stati meiner Waschmaschine, soll nur anzeigen wenn "Finished")

Ich habe keine Ahnung von JavaScript, hab mir mit Algorithmen-Logik geholfen. Die Beschreibung wie der Filter funktioniert ist auch denkbar kurz ;). Allerdings habe ich mich sehr gefreut das dieser Filter genau so funktioniert und tut was er soll (4 von 6 gefiltert, genau die richtigen).

Wenn ich Jarvis aber neu aufrufe / komplett reloade dann kommt die Fehlermeldung: "Cannot read properties of undefined (reading 'length')".

Also entweder dürfte keine Fehlermeldung kommen? Oder ich habe nur Glück das es funktioniert weil der Browser meine Unwissenheit wegbügelt aber dennoch nörgelt.

PS: Gibt es irgendwo sonst eine Beschreibung wie die Callback Funktion genutzt werden sollte? Alternativ würde ich mal ein Feature Request aufmachen das man den Filter zusammen klicken kann.

Danke für deine Zeit und tolle Arbeit! -> PRO ;)

**Comment by mcuiobroker** [comment]
Bitte den Filtereintrag.

**Comment by Eldron81** [comment]
(value, val) => val > 0 ^ (val.length > 1 && val !== "BSH.Common.EnumType.OperationState.Ready" && val !== "BSH.Common.EnumType.OperationState.Run")

**Comment by mcuiobroker** [comment]
`(value, val) => val!=undefined && (val > 0 ^ (val.length > 1 && val !== "BSH.Common.EnumType.OperationState.Ready" && val !== "BSH.Common.EnumType.OperationState.Run"))`

**Comment by Eldron81** [comment]
Direkt getestet, funktioniert nicht. Fehlermeldung bleibt: 

StateList: Filter incorrect (Cannot read properties of undefined (reading 'length'))

**Comment by Eldron81** [comment]
> StateList: Filter incorrect (typeOf is not defined)

**Comment by mcuiobroker** [comment]
`(value, val) => val!=undefined && (val > 0 ^ (typeof(val)=='string' && val.length > 1 && val !== "BSH.Common.EnumType.OperationState.Ready" && val !== "BSH.Common.EnumType.OperationState.Run"))`

**Comment by Eldron81** [comment]
Sehr gut, funktioniert!
Danke 👍

**Comment by mcuiobroker** [comment]
Was soll denn in die Doku rein, damit man es besser versteht? Was fehlt?

**Comment by Zefau** [comment]
Ist das `^` in der Formel so gewollt?

**Comment by Eldron81** [comment]
> Was soll denn in die Doku rein, damit man es besser versteht? Was fehlt?
Mag alles recht selbsterklärend sein wenn man tief drin steckt. Wenn der letzte Quellcode lang zurück liegt und PHP war ist das nicht selbsterklärend. Was ist auf der Seite eine "value", eine "val" oder ein "state". Da könnte man jeweils ein Beispiel aufnehmen. Dann habe ich lange nach dem "=>" Pfeil gegoogelt weil ich dachte das wäre JavaScript. Mittlerweile glaube ich verstanden zu haben das wurde hier einfach so definiert und alles dahinter muss true sein, korrekt?

> Ist das `^` in der Formel so gewollt?
Ja, als "oder". Vielleicht geht es schlauer. Ziel ist es ja aus einer Liste mit 20 ToDos (e.g. noch 3 Tage Müllabfuhr, noch 83min Waschmaschine, morgen Pollenwarnung, 12 Tage nächster Feiertag, 3h seit der Briefkasten was bekommen hat...) die aktuell relevanten zu filtern.
Das würde natürlich auch gehen indem ich zig Objekte mit Scripten anlege, aber deutlich schneller und für mich an der richtigen Stelle nur im Filter bei der Anzeige...

Danke in jedem Fall nochmal 👍

**Comment by mcuiobroker** [comment]
Wenn es `oder` sein soll dann `||` <- ALT GR + <>
So nutzt ^ -> XOR

**Comment by mcuiobroker** [comment]
Hab die Doku angepasst, schau mal bitte, ob es so reicht?

**Comment by Eldron81** [comment]
Ok, fangen wir von vorne an (ich hab den ioBroker erst am WE erstmals installiert ;)). Mein Feedback aus Newbie Sicht:

1. Die Doku die ich gegoogelt hatte ist: https://zefau.gitbook.io/jarvis-v2/layout/modules
--> Da wird mir aber erst jetzt wo ich entdecke das es auch eine Wikiseite Jarvis V3 gibt klar, dass wohl nur die V2 abgedeckt ist. (Die Informationen sind strukturiert und ok, aber nicht besonders umfangreich.)

2. In der Linksammlung würde ich mal aufräumen: https://github.com/Zefau/ioBroker.jarvis/wiki
--> Die V3 Wiki ist nicht gefüllt, die würde ich dann doch aus der Linksammlung rauslassen oder?
--> YouTube ist leer. Wie wäre es mit Zefaus Updates zu V3: https://youtu.be/r8IFxrxQ8jQ
--> Ebenfalls für mich super hilfreich bei YouTube: https://www.youtube.com/@haus_automation (deutsch) und https://www.youtube.com/@verdrahtet (deutsch)
--> Ergänzen würde ich auch Smart-Home Tricks, das ist eine der umfangreichsten Quellen für Infos und Schritt-für-Schritt Anleitungen mit tollen UseCases: https://www.smarthome-tricks.de/uebersicht-iobroker-jarvis-visualisierung/

3. Dann habe ich vermutet, hast du das Update in deinem GitBook gemacht?
--> Hatte den Eintrag zum Filtern vor dem öffnen des Issues dort garnicht gefunden. Hätte es erst unter Tabs -> Widges... erwartet - als Neuling sind die Unterschiede V2 zu V3 völlig unklar ;)
--> Über die Suche dann jetzt aber gefunden: Vielen Dank, das hilft super weiter. Damit habe ich auch jetzt verstanden dass ich über die State Properties auch die kryptischen Waschmaschinen Werte umschreiben und dann nach denen Filtern kann?! Und über die direkte Verknüpfung `device.state.fertig_in...` den genauen Wert ansprechen und filtern kann. Das macht es einfacher!

Vielen DANK!

**Comment by Zefau** [comment]
> (value, val, state, device,widget) => console.log(widget);
> -> undefined

schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by mcuiobroker** [comment]
Es wird jetzt das Device angezeigt
![image](https://user-images.githubusercontent.com/84818934/214700126-3e696a52-cf8a-4d2f-9c2f-4fc981aa002b.png)
Ich sehe keine Widget-Infos?

**Comment by Zefau** [comment]
Das ist die Device Config. Die Reihenfolge ist nun `(value, val, state, device, deviceConfig, widget)` (statt `(value, val, state, device,widget)`)

**Comment by mcuiobroker** [comment]
Ja dann ist ok. Dann muss man ja alle Variablen mit angeben? Man nicht nur einige auswählen. Also nur die Variablen übergeben, die man abfragen möchte?

**Comment by Zefau** [comment]
`(, , , , , widget) => { .. }` sollte gehen

**Comment by mcuiobroker** [comment]
Mag er nicht.
![image](https://user-images.githubusercontent.com/84818934/214703326-75f4828e-a88c-462c-b276-8cfcc2449f9a.png)

**Comment by mcuiobroker** [comment]
Lassen wir erstmal so? Mache zu.
