### ISSUE TITLE
js/json-editor Not exist

### ISSUE THREAD

**Issue by Grufti68** [Zefau/ioBroker.jarvis#2177]
Hi@all

ich hab mich vor kurzem mit Io Brocker angefreundet und bin auf den Adapter jarvis 3.1.3-beta4 gestoßen welcher drei Tagen super Funktioniert hat.

Allerdings hab ich seit heute diese Warnung im Protokoll wenn ich mit dem Handy auf Jarvis zugreife.

Auch auf dem Handy hab ich eine Fehlermeldung und ich muss ca. alle 10 Sekunden neu Aktualisieren.

Wo ist der Fehler?

![image](https://user-images.githubusercontent.com/123099062/213492375-91b85224-d911-46bd-b9fb-60b964ec2359.png)
![WhatsApp Image 2023-01-19 at 17 06 06](https://user-images.githubusercontent.com/123099062/213493173-6bbbd684-d07a-4002-8782-b261b6a68ac6.jpeg)

**Comment by mcuiobroker** [comment]
Auf der console
`iob upload jarvis` 

Danach 
Web Adapter  neu starten

**Comment by Grufti68** [comment]
Leider ohne Erfolg die Warnmeldung bleibt weiterhin

**Comment by mcuiobroker** [comment]
Dann ist irgendetwas bei der Installation schief gelaufen?
`iob upgrade jarvis@3.1.2`

**Comment by Grufti68** [comment]
über den Adapterbereich in IO unter Benutzerdefiniert und dann die URL von github.

**Comment by mcuiobroker** [comment]
Wenn du jetzt auf die Beta möchtest, dann über diese Variante:
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/v3-fuer-einsteiger/installation-jarvis-v3#alternative-1

**Comment by mcuiobroker** [comment]
Wie sind die Systemdaten? 
`node -v`
`nodejs -v`
`npm -v`

**Comment by mcuiobroker** [comment]
nodejs nicht so installieren!

**Comment by Grufti68** [comment]
laut IO Info:
Plattform: linux
Betriebssystem: linux
Architektur: x64
CPUs: 2
Geschwindigkeit: 802 MHz
Modell: AMD E-350 Processor
RAM: 7.3 GB
System-Betriebszeit: 2 T. 19:07:32
Node.js: v16.19.0
time: 1674137539579
timeOffset: -60
Adapter-Anzahl: 455
NPM: 8.19.3
Datenträgergröße: 53.7 GB
Freier Festplattenspeicher: 43.8 GB
Betriebszeit: 2 T. 19:06:56
Aktive Instanzen: 12
Pfad: /opt/iobroker/
aktiv:

**Comment by mcuiobroker** [comment]
`sudo ln -s /usr/bin/node /usr/bin/nodejs`

**Comment by mcuiobroker** [comment]
`nodejs -v` sagt jetzt

**Comment by mcuiobroker** [comment]
Passt. Dann kann zu?

**Comment by Grufti68** [comment]
und was war jetzt der Fehler ? IO falsch installiert?

**Comment by Grufti68** [comment]
Super Danke dir für deine Hilfe

**Comment by mcuiobroker** [comment]
Gerne. Bitte schließen.
