### ISSUE TITLE
Jarvis 3.1.2 - Thermostate können nicht importiert werden

### ISSUE THREAD

**Issue by StephanRibbrock** [Zefau/ioBroker.jarvis#2178]
Ich habe versucht, 3 neue Heizköperthermostate in Jarvis zu importieren. Leider stehen diese immer unter den Geräten mit undefinierten Datenpunkten.
Bei genauerer Betrachtung wurden bisher alle anderen Thermostate erkannt und stehen mit der Typenbezeichnung HmIP-eTRV-2 in der CCU3. Die neuen Thermostate haben nun folgende Typenbezeichnung: HmIP-eTRV-2 I9F. Der Wandthermostat hat die Typenbezeichnung HmIP-WTH-1.
Die Geräte sind im ioBroker sichtbar:

![2022-12-25_13-32-29](https://user-images.githubusercontent.com/123153176/213663652-219324ae-541b-4dfc-b0ab-4b8bfd6873cd.jpg)

In Jarvis sieht es so aus:

![2022-12-25_13-34-35](https://user-images.githubusercontent.com/123153176/213663718-712dd0f6-f032-4eeb-8862-e2e7b182019d.jpg)

**Comment by Zefau** [comment]
Kannst du die genaue Geräte Bezeichnung mal aus den Objekt Daten screenshoten?

Für die Integration brauche ich eine Info welche Datenpunkte übernommen werden sollen. Sind das die gleichen wie beim HmIP-eTRV-2?

**Comment by StephanRibbrock** [comment]
Ich hoffe das passt so:


<img width="1320" alt="grafik" src="https://user-images.githubusercontent.com/123153176/213861885-c32b99c7-2e9b-4e01-94da-f13d5ca3e554.png">

**Comment by Zefau** [comment]
Du hattest oben geschrieben

> Die neuen Thermostate haben nun folgende Typenbezeichnung: HmIP-eTRV-2 I9F. Der Wandthermostat hat die Typenbezeichnung HmIP-WTH-1.

Kannst du das nochmal in den Objekt-Daten finden? 
Bei `HmIP-eTRV-2 I9F` frage ich mich, ob es mit `-` ist? `HmIP-eTRV-2-I9F`? Ein Leerzeichen wäre jedenfalls ungewöhnlich.

Das müsste im obersten Level bei `device` in den Objekt-Daten stehen, wenn du dort auf den Bleistift ganz rechts klickst.

**Comment by StephanRibbrock** [comment]
"native": {
    "TYPE": "HmIP-eTRV-2 I9F",
    "SUBTYPE": "TRV",

**Comment by Zefau** [comment]
Ok, ungewöhnlich mit dem Leerzeichen

**Comment by Zefau** [comment]
@StephanRibbrock sollte mit `v3.1.3-beta.15` nun importierbar sein

**Comment by Zefau** [comment]
@StephanRibbrock

**Comment by StephanRibbrock** [comment]
Hat wunderbar funktioniert. Also, erledigt ;-)
Vielen Dank
