### ISSUE TITLE
Wert 0 einen Datenpunktes wird nicht ausgegeben

### ISSUE THREAD

**Issue by reutli** [Zefau/ioBroker.jarvis#2179]
Wenn in der Statist ein DP den Wert 0 hat (z.B. Temperatur 0°C) wird dieser nicht in der VIS ausgegeben. Statt dessen steht dort dann " °C".
Dies scheint bei allen Datenpunkten (als number) so zu sein.

Wie kann erreicht werden, dass diese gezeigt werden?

**Comment by mcuiobroker** [comment]
Welche Version?

**Comment by reutli** [comment]
v3.1.3-beta.4

**Comment by mcuiobroker** [comment]
Anzeigevariante:
`{"0":"0"}`

**Comment by mcuiobroker** [comment]
@zefau Sollte optional einstellbar sein, ob man 0 angezeigt bekommen möchte oder nicht?

**Comment by reutli** [comment]
Im Ernst? "Zeige "Null" an wenn "Null"?

**Comment by mcuiobroker** [comment]
Damit überschreibt man den Standard, der die "0" ausblendet.

**Comment by Zefau** [comment]
`null` ist nicht `0`.

Dass `0` nicht angezeigt wird liegt daran, dass es als `false` interpretiert wird, was falsch ist. `0` wird in Zukunft auch so angezeigt.

`null` ist kein Wert (auch nicht `0`) daher wird nichts angezeigt.

**Comment by reutli** [comment]
Deshalb ja auch in Anführungszeichen gesetzt.
Natürlich ist `0 != null` und auch `0 != 'null' ` (usw.) ;o)

Aber warum ist `0` in einem DP des Typs  `number` kein Wert?

Wird also der Wert `0` in einem Datenpunkt des Typs `number` in einer künftigen Version angezeigt oder nicht?

Der Satz 
> Dass `0` nicht angezeigt wird liegt daran, dass es als `false` interpretiert wird, was falsch ist. `0` wird in Zukunft auch so angezeigt.

war mir da nicht klar genug bzw. ich habe die Aussage dahinter nicht zu interpretieren gewusst.

**Comment by Zefau** [comment]
> Aber warum ist 0 in einem DP des Typs number kein Wert?

jarvis nutzt den Typ des Datenpunkts nicht.

> Wird also der Wert 0 in einem Datenpunkt des Typs number in einer künftigen Version angezeigt oder nicht?

Ja, natürlich.

> Dass 0 nicht angezeigt wird liegt daran, dass es als false interpretiert 

Das ist eine Hintergrundinformation, wenn du so willst. jarvis ist in JavaScript geschrieben (wie auch ioBroker) und diese Sprache interpretiert den Zahlenwert `0` als `false`. Insofern muss ich als Programmierer hier ausdrücklich die `0` als Zahlenwert deklarieren.

**Comment by Zefau** [comment]
schaut bitte nochmal mit `v3.1.3-beta.9`

**Comment by hosabeni** [comment]
Bei mir passt es leider nicht

**Comment by Zefau** [comment]
Bitte nochmal mit `v3.1.3-beta.10` probieren (im Repo fälschlicherweise als `v3.1.3-beta.9` gelabelt)

**Comment by hosabeni** [comment]
Mit der `v3.1.3-beta.11` geht es bei mir.
