### ISSUE TITLE
Chart not working for "true" and "false" values

### ISSUE THREAD

**Issue by bmk666** [Zefau/ioBroker.jarvis#218]
The Chart cannot display "true" and "false" values, it is needed to see when a heater valve was open or closes. Or to see when a 
motion detector triggert over time.

THX

**Comment by Zefau** [comment]
A chart is used to display the history of a device / state. Is this what you are looking for? Have you activated the history for the state?

**Comment by bmk666** [comment]
Hi, yes, the history is active and i can see all values in the table. But as values i have "true" or "false", can the chart visualize "true" and "false" ? Or is there a need to translate "true" to 1 and "false" to 0? 

With other states like temperature i have no problems and the chart is working well!

THX

**Comment by Zefau** [comment]
Sounds incorrect. Could you screenshot the situation?

**Comment by bmk666** [comment]
![history](https://user-images.githubusercontent.com/47809644/96458871-b97b0500-1221-11eb-9d3a-1bed9d98fcd3.JPG)
![Garät](https://user-images.githubusercontent.com/47809644/96458880-bbdd5f00-1221-11eb-87c3-68258f103bea.JPG)
![widget config](https://user-images.githubusercontent.com/47809644/96458884-bda72280-1221-11eb-98ad-50bab07d1d8e.JPG)
![widget show](https://user-images.githubusercontent.com/47809644/96458894-bf70e600-1221-11eb-896a-220fd438730a.JPG)

**Comment by Zefau** [comment]
@bmk666 a conversion has been added with `1.1.0-beta.46`. Could you test and verify?

**Comment by bmk666** [comment]
Erstmal Danke für die schnelle Reaktion, ich schrieb mal in Deutsch :) oder is dir Englisch lieber damit jeder das lesen kann?

Hab jetzt Werte im Chart:

![image](https://user-images.githubusercontent.com/47809644/97540221-9c81c700-19c3-11eb-8d82-efcabc8eea91.png)

aber alle mit Wert 0.5, die Datenpunkte passen aber auch nicht zu den Daten:

![image](https://user-images.githubusercontent.com/47809644/97540404-dfdc3580-19c3-11eb-900a-e10219944ce5.png)

**Comment by Zefau** [comment]
`true` = 1 und `false` = 0. Aufgrund der zeitlichen Darstellung werden die Werte konsolidiert, wodurch 0,5 als Durchschnittswert entsteht.

Sprich: Du betrachtest die Werte stündlich, aber die Aufzeichnungen sind teilweise minütlich / viertelstündlich. Insofern ergibt sich die Konsolidierung.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/273

**Comment by bmk666** [comment]
Ja macht Sinn wenn man mal drüber nachdenkt....

wenn ich den Chart auf Minuten runterbreche klappts:

![image](https://user-images.githubusercontent.com/47809644/97560267-ba105a00-19de-11eb-85a3-eade52310857.png)

Für eine Solche Darstellung mit 0 und 1 wäre vielleicht eine Viereckige Verbindung der Punkte Sinnvoll für eine gute Darstellung. Aber das kann ich auch gerne in einem neuen feature request anlegen.

Dank dir!

**Comment by Zefau** [comment]
@bmk666 kann das Issue aus deiner Sicht geschlossen werden? Passt alles?

**Comment by bmk666** [comment]
Ja kann zu, das abschalten des Mittelwerte ist ja ein neues Feature! Danke für die tolle Unterstützung!

**Comment by balzreber** [comment]
Are there any plans to implement this feature in a later version? I have a rain sensor on my balcony that outputs true or false. And it would be nice to show that in a chart.

**Comment by Zefau** [comment]
This has been implemented with v2.0.0, which is why this issue is closed. True and false should be shown as 1 and 0 in the chart.

**Comment by balzreber** [comment]
Unfortunately does not work for me. I'm running 2.0.0-rc.3 and I'm using the SQL adapter for history keeping. Did I do something wrong or is this a bug?

History in ioBroker
<img width="2359" alt="Screenshot 2020-12-11 at 08 34 07" src="https://user-images.githubusercontent.com/9654244/101875983-eeee0000-3b8b-11eb-99be-26446e4c2330.png">

Device config
<img width="948" alt="Screenshot 2020-12-11 at 08 37 23" src="https://user-images.githubusercontent.com/9654244/101876082-2197f880-3b8c-11eb-8e1a-09b0d29fc956.png">

Normal display
<img width="587" alt="Screenshot 2020-12-11 at 08 33 00" src="https://user-images.githubusercontent.com/9654244/101876013-fd3c1c00-3b8b-11eb-8be3-0d467fc90a38.png">

Chart settings
<img width="2477" alt="Screenshot 2020-12-11 at 08 40 01" src="https://user-images.githubusercontent.com/9654244/101876352-90755180-3b8c-11eb-853c-c976e57024ea.png">

Chart
<img width="832" alt="Screenshot 2020-12-11 at 08 32 41" src="https://user-images.githubusercontent.com/9654244/101876021-0331fd00-3b8c-11eb-8c79-93be366c6fd1.png">
