### ISSUE TITLE
Windows-App

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2181]
https://github.com/Zefau/ioBroker.jarvis/issues/138

**Comment by Zefau** [comment]
Windows-App released: https://github.com/Zefau/ioBroker.jarvis/releases/tag/v3.1.3-beta.9

**Comment by mcuiobroker** [comment]
Im LOG jede Menge davon
![image](https://user-images.githubusercontent.com/84818934/214695815-db8745f0-2d6b-493c-b84a-5467212d96dc.png)

**Comment by Zefau** [comment]
Das ist nicht von jarvis. `main.xxx .. xx.js` gibt es bei jarvis nicht.

**Comment by mcuiobroker** [comment]
Deutsche Übersetzung vom Menü?
![image](https://user-images.githubusercontent.com/84818934/214712815-6c8b82bf-f953-4fe5-8d92-495779336c54.png)

**Comment by Zefau** [comment]
> Zoom-In Funktion per Tastenkombination funktioniert nicht (STRG+ +)

Scheint ein "offizieller" Fehler zu sein, siehe https://github.com/electron/electron/issues/29996

> Deutsche Übersetzung vom Menü?
> Help Link zum WIki?

Jo, kann ich umsetzen.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.11` (release der App dauert an, kommt in ca. 1h..)

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.13`
Windows-App zeigt falsche Server-Version an

![image](https://user-images.githubusercontent.com/84818934/215301054-85b21e2b-dee8-453f-9258-617cd47f0260.png)

Weiterhin wäre es gut bei Vollbild-Modus (F11) keine Menüzeile zu sehen? Oder abschaltbar als Option?

![image](https://user-images.githubusercontent.com/84818934/215301120-6e8da593-fe17-40f1-895f-11af3cf13306.png)

**Comment by Zefau** [comment]
> Windows-App zeigt falsche Server-Version an

Das ist die Client-Version. Habe ich mal entfernt, da verwirrend.

> Weiterhin wäre es gut bei Vollbild-Modus (F11) keine Menüzeile zu sehen? Oder abschaltbar als Option?

Ich nehme das Menü im Vollbild raus, aber ohne Option.

**Comment by mcuiobroker** [comment]
Wie bei Android schon erwähnt, sollte es für die Apps eigene Variablen geben, somit kann man die auch anzeigen und es hilft evtl. bei Problemlösungen?

**Comment by Zefau** [comment]
Das ist alles dieselbe Version. Die Web-App läuft lediglich in einem Container. Ein Android- bzw. ein Windows-Container. Die Code-Basis und auch die Version sind identisch.

**Comment by mcuiobroker** [comment]
Das bedeutet, wenn du die Apps so eingestellt hast, dass sie korrekt aussehen, werden diese Apps nie wieder verändert?
Denn bei jeder Veränderung der Apps, sollte der User wissen, welche Version er denn jetzt auf seinem System hat?

**Comment by Zefau** [comment]
> Das bedeutet, wenn du die Apps so eingestellt hast, dass sie korrekt aussehen, werden diese Apps nie wieder verändert?

?!

Die Apps werden wie die Web-App weiterentwickelt und steigen in den Versionen normal an. Rein technisch ist es nur, dass die Web-App einfach in einem Container läuft. Also wenn du beta-11 auf Android auf machst ist es dieselbe Code-Basis wie beta-11 als Web-App.

**Comment by mcuiobroker** [comment]
Bedeutet es, dass bei jeder neuen Version von jarvis (v3.1.3-betax -> v3.1.3-beta.y), dann auch die Apps aktualisiert werden müssen?

**Comment by Zefau** [comment]
Jo. Es sind quasi 3 Apps: Web, Windows und Android. Alle 3 haben zwar dieselbe Code-Basis, aber sind am Ende unabhängig compiliert / gepackt und (theoretisch*) eigenständig lauffähig.

*Theoretisch, weil alle den Server auf ioBroker brauchen, der nur mit der Web-Variante installiert wird.

**Comment by mcuiobroker** [comment]
Damit wäre ein Updateszenario komplizierter geworden, denn man muss dann alle Clients auch sofort mit updaten?
Oder kann eine niedrigere Version der Apss, eine höhere Version (Server) nutzen?

**Comment by mcuiobroker** [comment]
Also ich habe jetzt den Cache auf Windows gelöscht.
![image](https://user-images.githubusercontent.com/84818934/215332654-b19f7d5a-6800-44c1-a2d7-2fac67eb5f0b.png)
Auch beim Neulade-Prozess erscheint wieder die Version v3.1.3-beta.11.

**Comment by Zefau** [comment]
> Also ich habe jetzt den Cache auf Windows gelöscht.

Dann weiß ich auch nicht. Ist auch für mich alles neu. Müssen wir dann beobachten, wo was wir gecached wird.

**Comment by mcuiobroker** [comment]
Bei cordova steht?
![image](https://user-images.githubusercontent.com/84818934/215338750-c0e1f365-2a2f-4ed1-85d5-afd851a09058.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/215339492-eac22628-e7b2-4089-9a43-ce3115cfbafe.png)
Man braucht eine Möglichkeit wieder ins alte System zurückzukommen, falls das Neue angegebene nicht funktioniert.

**Comment by Sineos** [comment]
https://medium.com/codex/the-sunset-of-apache-cordova-alternatives-for-cross-platform-mobile-development-in-2022-9da34234c992

Interessant.

**Comment by Zefau** [comment]
> Auf dem Server ist v3.0.15 -> funktioniert aber nicht. 

Ja, das geht erst ab v3.1. Das stimmt. Dann stimmt meine Aussage oben nicht.

> Ja. Bei Minor-Changes gibt es keine Breaking Changes auf Server- oder App-Seite. Nur bei Major-Changes (also erste Zahl bei der Versionsnummer, wie bei v2.x.x auf v3.x.x).

Also bei Minor-Changes gibt es Breaking-Changes, aber nicht beim Patch-Level.

Ich orientiere mich an https://semver.org/lang/de/ (bzw. versuche es):

> Auf Grundlage einer Versionsnummer von MAJOR.MINOR.PATCH werden die einzelnen Elemente folgendermaßen erhöht:
> MAJOR wird erhöht, wenn API-inkompatible Änderungen veröffentlicht werden,
> MINOR wird erhöht, wenn neue Funktionalitäten, welche kompatibel zur bisherigen API sind, veröffentlicht werden, und
>  PATCH wird erhöht, wenn die Änderungen ausschließlich API-kompatible Bugfixes umfassen.
>
> Außerdem sind Bezeichner für Vorveröffentlichungen und Build-Metadaten als Erweiterungen zum MAJOR.MINOR.PATCH Format verfügbar.

**Comment by Zefau** [comment]
Also für das offizielle Release der Android- und Windows-Apps müsste ich auf v3.2 gehen.

**Comment by Zefau** [comment]
> Weiterhin wäre es gut bei Vollbild-Modus (F11) keine Menüzeile zu sehen? Oder abschaltbar als Option?

schau nochmal mit `v3.1.3-beta.16`

**Comment by mcuiobroker** [comment]
Release fehlt?

**Comment by Zefau** [comment]
siehe nun https://github.com/Zefau/ioBroker.jarvis/releases/tag/v3.1.3-beta.16

Upload ist abgebrochen. Leider sind es immer >100 MB, die ich hochladen muss - das dauert immer ewig.

**Comment by mcuiobroker** [comment]
Tut sich nix:
![image](https://user-images.githubusercontent.com/84818934/216149081-35d60461-967f-4e6d-a486-f24b21f098f7.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.17`

**Comment by mcuiobroker** [comment]
Wie lange dauert der Upload ungefähr?

**Comment by Zefau** [comment]
Ich sehe leider die Übertragungsrate nicht, aber der GitHub-Server kommt mir hier nicht gerade entgegen. Es sind ca. 110 Mb und ich meine es dauert gut eine Stunde.

**Comment by Zefau** [comment]
Ok, ging doch fix. Ist schon oben.

**Comment by mcuiobroker** [comment]
F11 sieht gut aus.
Wofür ist Menü umschalten? 
Wenn man das anklickt verschwindet die Menü-Zeile.
Man bekommt sie nur mit 2x F11 zurück.

**Comment by Zefau** [comment]
> Wofür ist Menü umschalten?
> Wenn man das anklickt verschwindet die Menü-Zeile.

Jo, kann man damit ausblenden.

**Comment by mcuiobroker** [comment]
dann evtl zur Reaktivierung eine Tastenkombination dahinter oder  Info 2x F11?
