### ISSUE TITLE
v3.1.3-beta.4 Nachkommastellen

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2183]
Hej @Zefau ,

bei meinen Temp.-DP wird die zweite Nachkommastelle nicht richtig ausgelesen. Ohne ` {"value":"val => parseFloat(val).toFixed(2)"}` wird nur eine Nachkommastelle angezeigt und mit immer eine 0. Bei Luftfeuchtigkeit funktioniert es richtig, das beide Nachkommastellen angezeigt werden. (Siehe Bilder)

VG

![image](https://user-images.githubusercontent.com/85995176/213794486-5ef7456d-9fab-45a8-bd5e-28e93d4cc5ba.png)
![image](https://user-images.githubusercontent.com/85995176/213794510-008c0353-811c-41e4-8c96-68f59db10852.png)

![image](https://user-images.githubusercontent.com/85995176/213794964-a9e7c9d2-5dee-47fe-949f-dde89f52927a.png)
![image](https://user-images.githubusercontent.com/85995176/213794692-5d0c6ac1-70d7-4c3e-83c5-a61159d21e3b.png)

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/213795823-273ee045-b0e4-4a79-ae44-7c2781ee2618.png)

Objektdaten vom DP Temperatur

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.9`

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/214918801-7ada7b30-3c6b-45ef-a6b2-7aab0f22ebd4.png)
![image](https://user-images.githubusercontent.com/85995176/214918861-850cac52-ae14-4781-a94c-941418bab9c7.png)


Nein leider nicht :(

**Comment by Zefau** [comment]
Kannst du mal im Layout `InputAction` aktivieren und in den Optionen auf `Rohwert (val)` stellen? Ist `val` (Rohwert) auch abgeschnitten oder betrifft es nur `value` (verarbeiteter Wert)?

Kannst du mal einen Screenshot des Geräts mit dem entsprechenden Datenpunkt machen?

**Comment by Mephisto090** [comment]
> Kannst du mal im Layout `InputAction` aktivieren und in den Optionen auf `Rohwert (val)` stellen? Ist `val` (Rohwert) auch abgeschnitten oder betrifft es nur `value` (verarbeiteter Wert)?
> 
> Kannst du mal einen Screenshot des Geräts mit dem entsprechenden Datenpunkt machen?

Ich finde leider nicht was du damit meinst

> Kannst du mal einen Screenshot des Geräts mit dem entsprechenden Datenpunkt machen?

ich hoffe du meinst das :(

![image](https://user-images.githubusercontent.com/85995176/215804879-be425af9-3348-4889-b202-531d6a43998a.png)

**Comment by Zefau** [comment]
in jarvis:

![grafik](https://user-images.githubusercontent.com/14368811/215852137-f645ae25-6189-4358-acb5-4efd67668924.png)

und neben InputAction auf das grüne Icon:

![grafik](https://user-images.githubusercontent.com/14368811/215852241-29cf0dbb-1a58-4b4e-aaff-da748c0ec14d.png)

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/215872568-31c473f0-63b9-4ce0-bf4f-74745ecd09a2.png)

mit den Einstellungen die du gesagt hast

**Comment by Mephisto090** [comment]
Kann es sein, dass es an °C liegt? Ich meine mit % bei Luftfeuchtigkeit funktioniert es ja.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.16`

**Comment by Mephisto090** [comment]
![image](https://user-images.githubusercontent.com/85995176/216114057-592c9541-18e4-4098-92f6-8c5a94f04b0e.png)
![image](https://user-images.githubusercontent.com/85995176/216114281-72b2049d-b41f-411a-8936-37b5dd1c206c.png)

Leider nein :(

**Comment by Zefau** [comment]
Was für ein Gewerk ist das Gerät? Kannst du mal die Geräte-Konfiguration screenshoten? Was für ein Datenpunkt-Schlüssel in jarvis ist das?

**Comment by Mephisto090** [comment]
Gewerk ist Sensor

Ich habe dir Luftfeuchtigkeit auch mit hinzugetan ist das gleiche Gerät und da funktioniert es ja :)

![image](https://user-images.githubusercontent.com/85995176/216141876-b2d7e88f-9c1e-4d9d-b5e5-98f501410c62.png)
![image](https://user-images.githubusercontent.com/85995176/216141787-0171d106-ab1f-406f-b202-6d73d4d8be3d.png)
![image](https://user-images.githubusercontent.com/85995176/216141628-be1cd718-6886-48e9-bd40-615007271cad.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.17`

**Comment by Mephisto090** [comment]
Funktioniert: :D
![image](https://user-images.githubusercontent.com/85995176/216355513-b241a214-71a6-42fb-bd78-d7b378c07d2f.png)
