### ISSUE TITLE
v3.1.3-beta.4 DatePickerAction Infos fehlen und Kompakt mit Verbotszeichen?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2185]
![image](https://user-images.githubusercontent.com/84818934/213925315-1eebd1a6-6f1b-4cc1-940a-0cccd1367f75.png)

Bei Komakt und Heute-button fehle die Infos
![image](https://user-images.githubusercontent.com/84818934/213925382-6d5d9144-b006-4ad4-9bcf-14cf052be62e.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.29`

**Comment by mcuiobroker** [comment]
Ja, passt. Danke.
