### ISSUE TITLE
Achsenbeschriftung nicht richtig sichbar - (v3.1.2)

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#2186]
Mittels `{"position": "right","name": "Strom"}, {"position": "left","name": "Gas"}` festgelegten Achsenbeschriftung werden nicht richtig dargestellt.
![image](https://user-images.githubusercontent.com/13101074/213933471-68966a01-a465-4945-aec4-c96a4d4cd1a1.png)

![image](https://user-images.githubusercontent.com/13101074/213933496-bdd5f9b0-4f14-4d67-9a45-501eb59f5b3b.png)

![image](https://user-images.githubusercontent.com/13101074/213933521-7e0ff9a7-6d70-4586-9ebb-760818aa36f1.png)

Wird die Legende nach unten verlegt, ist die Achsenbeschriftung nicht sichtbar.

**Comment by Zefau** [comment]
Kannst du mittels `grid` (`left`, `top`, `right`, `bottom`) steuern, siehe https://echarts.apache.org/en/option.html#grid

**Comment by Zefau** [comment]
Standard-Höhe ist 7px. Ich erhöhe es im Standard mal auf 10px.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.11`

**Comment by Zefau** [comment]
@AFPass
