### ISSUE TITLE
v3.1.3-beta.4 lastChangeBody und LastChangeBody vorhanden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2187]
Es sind im ExpertenModus unterschiedliche Body Elemente für `LastChangeBody`vorhanden. 
`lastChangeBody`ist die alte Variante?
Er hat aber nicht alle umgesetzt?
![image](https://user-images.githubusercontent.com/84818934/213939799-5d5375c3-1335-4461-a0ec-a2466d64040f.png)

![image](https://user-images.githubusercontent.com/84818934/213939817-77dd9db7-722d-420e-8055-2166a16bb8d4.png)

Solle man das glatt ziehen? Wird darauf geachtet? Unterschiede?

**Comment by Zefau** [comment]
Es war immer LastChangeBody. Wo das andere her kommt weiß ich nicht. Wenn Jarvis es richtig verwendet können wir es ignorieren.

**Comment by mcuiobroker** [comment]
Dann ändere ich die.
