### ISSUE TITLE
`v3.1.3-beta7` zerstört komplett die Widgets

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2191]
> `v3.1.3-beta7`
Zerstört komplett die Widgets.
![image](https://user-images.githubusercontent.com/84818934/214151482-325fddde-e48e-44eb-ac8f-b846e5ae32f4.png)
![image](https://user-images.githubusercontent.com/84818934/214151541-714672bc-a362-4c5f-8dfc-ea2ba44347e1.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/2156#issuecomment-1400989514_

**Comment by Zefau** [comment]
Danke für die schnelle Info. Release ist erst mal gelöscht. Du müsstest ein Backup einspielen.

**Comment by mcuiobroker** [comment]
Muss man erst den Server updaten, bevor man die App aufruft?

**Comment by Zefau** [comment]
:-\

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/214153657-71516f4c-69da-4123-a1b1-9effa3abe504.png)

**Comment by Zefau** [comment]
Jo, kenne den Fehler. Hatte den lokal auch schon und dachte er wäre gefixed. Sorry. Ich hoffe, du hast noch ein Backup via backitup?

**Comment by Zefau** [comment]
Du bist von beta-5 auf beta-7, richtig?

**Comment by mcuiobroker** [comment]
Auf dem Server noch nicht, da gibt es Probleme mit err-25.

**Comment by Zefau** [comment]
Die Dateien sind zu groß, deswegen muss ich die Android- und Windows-Dateien über Releases machen.

**Comment by mcuiobroker** [comment]
Zip-Datei hat aber keine .exe?
![image](https://user-images.githubusercontent.com/84818934/214154922-103e8d78-74a9-4461-b8de-e24b5f307b06.png)
Ist die zip für Windows?

**Comment by Zefau** [comment]
Nein. Das ist das ioBroker.jarvis Repository. Wie hast du das geladen?

**Comment by Zefau** [comment]
Die Windows-Zip hat es meine ich nicht hoch geschafft, da zu groß.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/214155407-8872b7a9-19ae-4156-b1f2-17d17c7c4f47.png)

**Comment by Zefau** [comment]
Ich meinte, wie du die Zip-Datei runtergeladen hast. Also woher hast du die?

**Comment by mcuiobroker** [comment]
https://github.com/Zefau/ioBroker.jarvis/releases/tag/v3.1.3-beta.7

**Comment by Zefau** [comment]
Du entdeckst auch alles. Den lösche ich auch mal. Da fehlen die Anhänge.

Der Source Code der da drin ist ist das Repository an sich. Also dasselbe als wenn du von der URL installierst.

**Comment by mcuiobroker** [comment]
beta.5 habe ich auf dem Server.

**Comment by Zefau** [comment]
Gleich kommt die `v3.1.3-beta.8`. Schau mal bitte, ob der Fehler damit behoben ist.

**Comment by mcuiobroker** [comment]
Kann ich die über github installieren oder zip?

**Comment by mcuiobroker** [comment]
Kann die App so bleiben? 
Reihenfolge der Installation einhalten? Wenn ja, welche?

**Comment by mcuiobroker** [comment]
Ist jetzt aber beta.7?
![image](https://user-images.githubusercontent.com/84818934/214158026-61aab398-b502-4be5-9fbd-547c86210d9c.png)

**Comment by Zefau** [comment]
> Kann ich die über github installieren

Immer über GitHub installieren. Das ändert sich nicht.

**Comment by mcuiobroker** [comment]
Läuft. We kann ich denn die IP in der App ändern?

**Comment by Zefau** [comment]
Beim Startscreen sollte eine Abfrage kommen.

**Comment by mcuiobroker** [comment]
Wenn es einmal eingestellt wurde und funktioniert, kommt nichts mehr. Beim nächsten Aufruf geht er direkt durch.
Wofür ist der Schalter neben dem Connect?

**Comment by Zefau** [comment]
> Wenn es einmal eingestellt wurde und funktioniert, kommt nichts mehr. Beim nächsten Aufruf geht er direkt durch.

Dann passt es doch? :-)

>  Wofür ist der Schalter neben dem Connect?

SSL Verbindung. Stimmt, da fehlt das Label.

**Comment by Zefau** [comment]
Ich mach hier mal zu. Wir können ja trotzdem weiter schreiben.

**Comment by mcuiobroker** [comment]
Nein. Ich muss es doch umstellen können, für Testsysteme usw.

**Comment by Zefau** [comment]
Jo, kann ich einbauen.

**Comment by mcuiobroker** [comment]
Wo kann man sich die Windows App herunterladen?

**Comment by mcuiobroker** [comment]
Was hat sich denn bzgl. Version 3.1 in den widgets geändert? Woher stand Version 3 drin.

**Comment by mcuiobroker** [comment]
Hat sich der Aufbau der window.Socket Abfragen verändert?
![image](https://user-images.githubusercontent.com/84818934/214170611-4ed17480-0bd1-48a5-98c7-d6601a00e931.png)
![image](https://user-images.githubusercontent.com/84818934/214170693-9f851fd3-b7a1-4bff-9812-2b865c0dfd71.png)
``` 
let ntvArr = [];
window.Socket.getState('0_userdata.0.jarvis.ntv.allgemein.ntvArr', ({ err, state }) => {
	ntvArr  = JSON.parse(state.val);
	if (logging){
		console.log('Getstate ntvArr: '+ ntvArr.length);
	}
});
``` 

![image](https://user-images.githubusercontent.com/84818934/214171041-623ad44c-2be3-4e3c-8ffb-99df36b74c55.png)

![image](https://user-images.githubusercontent.com/84818934/214171112-25ba2516-9232-430f-9206-bfa47c8ab5c8.png)

**Comment by mcuiobroker** [comment]
Keine Ahnung warum?
![image](https://user-images.githubusercontent.com/84818934/214403013-26bfbed7-ce01-4b32-acc4-facc94ad321d.png)

**Comment by mcuiobroker** [comment]
Wenn  die jarvis Instanz gestoppt ist sollte man im DOM-Log auch eine entsprechende Nachricht sehen?
![image](https://user-images.githubusercontent.com/84818934/214414448-9b45c6ca-5c3f-4370-b6b6-ca45f54adbc4.png)
Also, wenn man noch Connection zum Server hat, eben prüfen ob jarvis überhaupt gestartet ist?

**Comment by Zefau** [comment]
> Die widgets waren ja schon auf v3.1 jetzt plötzlich wieder auf v3?

Hast du ein Skript laufen mit dem du auf `jarvis.0.widgets` schreibst?

**Comment by mcuiobroker** [comment]
Nein, und wenn würde diese Script, keine Versionen anpassen, sondern nur die Widgets ändern.
Bei der App wird "dauernd/ öfter" Mismatch angezeigt:

![image](https://user-images.githubusercontent.com/84818934/214659233-ade8da8c-0e1c-4f9f-bd38-f05e766dffe1.png)

**Comment by Zefau** [comment]
`v3.1.3-beta.9`

> Hat sich der Aufbau der window.Socket Abfragen verändert?

Sollte wieder funktionieren.

>  Die widgets waren ja schon auf v3.1 jetzt plötzlich wieder auf v3?

Lag am Speichern der Konfiguration. Dadurch wurde wieder die `3` gesetzt. Sollte jetzt funktionieren.

> Wenn die jarvis Instanz gestoppt ist sollte man im DOM-Log auch eine entsprechende Nachricht sehen?

Nun auch mit Meldung im Frontend.

**Comment by mcuiobroker** [comment]
Doppelte Meldung?
![image](https://user-images.githubusercontent.com/84818934/214709843-11b81113-e86b-416f-a565-18c64d72614d.png)

**Comment by mcuiobroker** [comment]
jarvis wieder gestartet, PC erkennt aber nicht das es wieder verfügbar ist.
Sucht auf Port 80?

![image](https://user-images.githubusercontent.com/84818934/214712401-1265de1f-926e-489f-9a95-0c0b9f6054d3.png)
![image](https://user-images.githubusercontent.com/84818934/214712440-84c72f46-956a-445f-9828-f5f3845cf99b.png)

**Comment by LoDDl** [comment]
Hallo,

ich habe nun auch dieses Problem wie im ersten Post beschrieben. Mit dem Unterschied, dass bei mir noch die 3.1.2 läuft.

Ich habe weder Jarvis geupdated noch irgendetwas anderes mit Jarvis gemacht. Das Einzige war, dass ich gestern das Jarvis für Windows Programm heruntergeladen und ausgeführt habe. Da drin war noch alles in Ordnung, als ich 15 min später auf Jarvis geschaut habe, sah es dann aus wie in meinem Screenshot. So sieht es dann auf allen Geräten aus.

Ich habe dann erstmal versucht mit iob upload jarvis auf der Konsole etwas zu richten, ohne Erfolg. Dann habe ich das Backup von gestern morgen eingespielt. Danach lief die Visu wieder - aber auch nur für 15 min, dann war von allein wieder alles zerschossen. Ich habe keine Updates installiert, nichts an der Jarvis Config geändert, garnix. Woran kann das liegen?

![image](https://user-images.githubusercontent.com/52470482/215074260-0e100e63-9b2c-4a7d-bf7a-1ec4c6713b18.png)
![image](https://user-images.githubusercontent.com/52470482/215074719-4bb55ad3-3674-4fcc-ac70-d36ec026f904.png)

**Comment by Zefau** [comment]
@LoDDl bitte Backup wiederherstellen

**Comment by Zefau** [comment]
Bitte nochmal mit `v3.1.3-beta.10` probieren (im Repo fälschlicherweise als `v3.1.3-beta.9` gelabelt)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2211
