### ISSUE TITLE
Intl Funktionen als Anzeigevariante nutzen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2192]
Um die "deutsche" Schreibweise für Zahlen (12,34 statt 12.34) darzustellen (auch global? -> jarvis-Einstellungen), sollte man bei der Anzeigevariante auch die Möglichkeit haben diese Variation auswählen zu können?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/NumberFormat#examples
Datenpunkt-Eigenschaften (zurzeit)
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/geraet/datenpunkt-eigenschaft/intl-funktionen

Da wäre auch zu beachten, dass man die Objektdaten aus dem DP holen kann -> Einheit wird gesetzt, falls vorhanden, Objekt-states werden für die Anzeige-Variante (DropdownAction) genutzt , min und max , falls vorhanden, werden für LevelBody genutzt usw.

-> ändern auf Feature Request

**Comment by Zefau** [comment]
Kannst du mittels der Einstellung in ioBroker steuern, siehe https://github.com/Zefau/ioBroker.jarvis/issues/2114

Funktioniert aber noch nicht so richtig.
