### ISSUE TITLE
v3.1.3-beta.8 kein automatischer Reload am PC, wird als beta.9 in der App angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2195]
![image](https://user-images.githubusercontent.com/84818934/214692181-023dfed6-dc51-420d-b84f-7f03acf6c6b0.png)

DOM
![image](https://user-images.githubusercontent.com/84818934/214692783-3648195f-d232-48d8-9e66-c87409ccf568.png)
github
![image](https://user-images.githubusercontent.com/84818934/214692871-99d88675-2758-4fd9-8b87-80d8bf248797.png)

App zeigt nach Reload beta.7 an
EDIT: Hat sich mit der neuen App erledigt v3.1.3-beta.9
![image](https://user-images.githubusercontent.com/84818934/214693845-ea07b5ab-936c-479e-a4c4-59c3739450de.png)
![image](https://user-images.githubusercontent.com/84818934/214693900-e6b0a0c6-99df-4a52-9dd3-cff96ebaa4fb.png)

**Comment by mcuiobroker** [comment]
Bekommt man das mit beta.8 und beta.9 gerade?
![image](https://user-images.githubusercontent.com/84818934/214694664-2b422d64-7332-4430-b3f7-b574048d4034.png)
Weil er immer den mismatch erkennt?

**Comment by mcuiobroker** [comment]
Layout und Widgets vertauscht?
![image](https://user-images.githubusercontent.com/84818934/214699515-d052d094-ba96-49a6-a6db-3e49a77e495a.png)

**Comment by Zefau** [comment]
> Layout und Widgets vertauscht?

Ist gewollt.

> Bekommt man das mit beta.8 und beta.9 gerade?

Ist ein Fehler im Release-Skript. Das Release ist beta.9 und z.T. nur falsch gelabelt mit beta.8, aber das schränkt technisch nichts ein.

Kann das Issue zu?

**Comment by mcuiobroker** [comment]
ok
