### ISSUE TITLE
Kalender Widget - Display issue am Monatswechsel

### ISSUE THREAD

**Issue by Andr3asB** [Zefau/ioBroker.jarvis#2196]
jarvis 3.1.2 (main branch).

Die Visualisierung läuft über mehrere Tag und zeigt am Monatswechsel bei einer Vorschau über mehrere Tage folgenden Fehler: Der Ende-Bubble des lilanen Vorschaubalkens wird als Zahl dargestellt, obwohl der Tag gar nicht in den Monat gehört. Das war m.E. früher nicht so.

![image](https://user-images.githubusercontent.com/44557554/214832069-d7fbf46f-aabb-4d50-abaa-39cfcf5d2d8f.jpeg)

Wie immer ist es kein kritischer Bug, nur optisch ein klein wenig unansehnlich.

**Comment by Zefau** [comment]
sollte mit `v3.1.3-beta.12` behoben sein

**Comment by Andr3asB** [comment]
Ich schau es mir so bald wie möglich mal an, wird aber vermutlich frühestens am Wochenende sein.

**Comment by Zefau** [comment]
@Andr3asB
