### ISSUE TITLE
v3.1.3-beta.9: xhr poll error auf Tablet

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2199]
![20230127_120215](https://user-images.githubusercontent.com/85995176/215072057-578e27a1-5bfc-46be-aea4-44d9a0074c68.jpg)

Auf dem PC im Browser läuft es normal

**Comment by Mephisto090** [comment]
Nach einer weile kommt dann das

![20230127_130657](https://user-images.githubusercontent.com/85995176/215083173-0d291035-5b0b-4557-981b-5919e8917eb5.jpg)

**Comment by mcuiobroker** [comment]
Nimm mal Port 8400

**Comment by Mephisto090** [comment]
kommt aber erst, seitdem ich auf die beta 9 gegangen bin

**Comment by mcuiobroker** [comment]
Ja, man kann jetzt den Server auswählen.  Dafür gibt es in der Konfiguration auch ein neuen Tab Connections.

**Comment by Mephisto090** [comment]
im DarkMode ist das echt blöd zu lesen

![image](https://user-images.githubusercontent.com/85995176/215098968-1fe71ed3-a249-4097-993e-64b16ddb5813.png)

**Comment by Mephisto090** [comment]
> Tab Connections.

was bringt mir das eigentlich?

**Comment by mcuiobroker** [comment]
Ist ja gerade erst neu, also so weit ich verstehe, kann man damit zwischen der unterschiedlichen Servern (Prod, Test) umschalten.
Ich hoffe das man dort irgendwann auch die Instanzen wechseln kann.

**Comment by Zefau** [comment]
Instanzen via Port. 8400 ist Instanz 0, 8401 ist Instanz 1, etc.

**Comment by Zefau** [comment]
Was hast du denn für ein Tablet? Die Warnung ist nur optisch neu. Die Routine im Hintergrund ist unverändert.

Welche Version funktionierte denn zuletzt bei dir?

**Comment by Zefau** [comment]
Bitte nochmal mit `v3.1.3-beta.10` probieren (im Repo fälschlicherweise als `v3.1.3-beta.9` gelabelt)

**Comment by Mephisto090** [comment]
> Was hast du denn für ein Tablet? Die Warnung ist nur optisch neu. Die Routine im Hintergrund ist unverändert.

Fire HD 10-Tablet | 25,6 cm (10,1 Zoll) großes Full-HD-Display (1080p), 32 GB, schwarz

> Welche Version funktionierte denn zuletzt bei dir?

Ich bin lange nicht auf eine beta gegangen. Ist schon eine weile her

> Bitte nochmal mit v3.1.3-beta.10 probieren (im Repo fälschlicherweise als v3.1.3-beta.9 gelabelt)

Die gelbe Meldung unten ist weg. ich prüfe später noch mal ob nicht das weiße Fenster mit "Connect" wieder kommt

**Comment by Mephisto090** [comment]
Nach dem ich bei "Connection Details" auf "Connect" kommt das gelbe Fenster unten wieder.

**Comment by Zefau** [comment]
Mit v3.1.2 ging es noch? Was gibt's du denn ein, um zu verbinden? ioBroker IP und Port 8400? Hast du SSL aktiviert?

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/issues/2199#issuecomment-1406762909

Nicht den Web-Port, sondern den jarvis-socket-Port nehmen

**Comment by Mephisto090** [comment]
Das weiße Fenster (Verbindungsd.) taucht immer noch nach einer weile nicht benutzen (circa 1h keine Nutzung) des Tablets auf. Das gelbe Fenster unten ist weg.

**Comment by Mephisto090** [comment]
Das sollte im ioBroker auch angepasst werden. 

Also der Link: 
![image](https://user-images.githubusercontent.com/85995176/216142796-20888a9f-2b87-4b61-bb07-08415b6c70f2.png)

**Comment by Zefau** [comment]
8082 ist der Web-Port. Das ist an sich ja richtig und ich kann es dort auch gar nicht ändern, da ioBroker Funktionalität. 
8400 ist der Socket-Port, also der Port für die Datenübertragung.

**Comment by Zefau** [comment]
> Das weiße Fenster (Verbindungseinstellungen) taucht immer noch nach einer weile nicht benutzen (circa 1h keine Nutzung) des Tablets auf. Das gelbe Fenster unten ist weg.

Das Fenster mit den Verbindungseinstellungen kommt nur beim Start. Arbeitest du mit Skripten und / oder hast irgendwo einen Reload drin?

Speichert jarvis auf dem Tablet deine letzte Verbindung?

**Comment by Mephisto090** [comment]
Ich benutze auf dem Tablet (fully kiosk browser) der reloaded bei jedem aktiv werden. (Sprich, wenn die Frontkamera eine Bewegung feststellt)

**Comment by Zefau** [comment]
Bei mir klappt es mit Fully und Reload. Nutzt du Port `8400`? Hast du spezielle Einstellungen im Fully?

> Speichert jarvis auf dem Tablet deine letzte Verbindung?

?

> Ich benutze auf dem Tablet (fully kiosk browser) der reloaded bei jedem aktiv werden. (Sprich, wenn die Frontkamera eine Bewegung feststellt)

Warum denn das?

**Comment by Mephisto090** [comment]
> Bei mir klappt es mit Fully und Reload. Nutzt du Port `8400`? Klappt bei mir auf `8400`und `8082`. Hast du spezielle Einstellungen im Fully?

Jap, habe seit dem du gesagt hast auf Port 8400 umgestellt.


> Speichert jarvis auf dem Tablet deine letzte Verbindung?

i dont know :(


> Warum denn das?

Hm, ich dachte es ist sinnvoll. Ist es das nicht? :)

**Comment by Zefau** [comment]
> Ich benutze auf dem Tablet (fully kiosk browser) der reloaded bei jedem aktiv werden. (Sprich, wenn die Frontkamera eine Bewegung feststellt)

Ich würde nur 1x nachts aktualisieren um 3 Uhr oder so. Damit, falls sich was aufgehangen hat, sich das wieder gerade zieht. Bei jedem Mal einer Bewegung wirst du ja wahnsinnig? :-D

Das Speichern der letzten Verbindung siehst du daran, dass du bei "Letzte Verbindung" einen Eintrag hast. Der scheint aber nicht da zu sein?

Ich hab die Version `v1.49.3-play` von Fully, womit es wie gesagt geht. Auf welcher Version bist du? Was für ein Android hast du? Ggf. spielt WebView eine Rolle?

Wobei es generell ja bei dir mit v3.1.2 funktionierte, richtig?

Als Workaround kannst du sonst die Socket-Einstellungen in der URL mitgeben, die du in fully konfigurierst. Einfach `?socketUrl=http://192.168.178.70:8400/` dranhängen.

**Comment by Zefau** [comment]
Ok, jetzt kann ich den Bug nachstellen.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.19`

**Comment by Mephisto090** [comment]
> schau bitte nochmal mit `v3.1.3-beta.19`

Dauert noch etwas. Bin vor kurzem Vater geworden. :)

**Comment by mcuiobroker** [comment]
Herzlichen Glückwunsch.  Alles Gute.

**Comment by Mephisto090** [comment]
Scheint zu funktionieren :)
