### ISSUE TITLE
TAB Konfiguration Connections

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2201]
Da müsste auch ein Umschaltung zwischen den Instanzen hinein.
Dann kann man nicht nur zwischen den Server-Systemen hin- und herschalten, sondern auch zwischen den Instanzen?

**Comment by Zefau** [comment]
Jede Instanz hat einen eigenen Port. 0 ist 8400, 1 ist 8401, etc.
