### ISSUE TITLE
v3.1.3-beta.9 jsonTable Parameter style funktioniert nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2202]
`[{"label":"Zeit","field":"Zeit","style":"color: red;"},{"label":"Minuten","field":"Minuten"},{"label":"Besuch","field":"Besuch"}]`

`[{"label":"Zeit","field":"Zeit","style":"color:red !important; background-color:blue !important;"},{"label":"Minuten","field":"Minuten"},{"label":"Besuch","field":"Besuch"}]`

Einstellungen bzgl. `style` haben keine Auswirkung mehr.

siehe auch https://github.com/Zefau/ioBroker.jarvis/discussions/2200

**Comment by Zefau** [comment]
Bitte nochmal mit `v3.1.3-beta.10` probieren (im Repo fälschlicherweise als `v3.1.3-beta.9` gelabelt)

**Comment by mcuiobroker** [comment]
Alle jsonTable sind jetzt grün
![image](https://user-images.githubusercontent.com/84818934/215268669-d47bbdbf-2e9b-49c8-9c0d-687f64be3b05.png)

**Comment by Zefau** [comment]
Haha, mein Debugging Test :-D vergessen zu löschen..

**Comment by Zefau** [comment]
Ab der nächsten beta kann `style` ein String sein (wie in deinem Beispiel oben), aber auch ein Callback, siehe https://quasar.dev/vue-components/table#defining-the-columns
```
"style": "(rowIndex, row, props) => (rowIndex%2 === 0 ? ' ... ' : ' ... ')"
```

Und es gehen auch CSS-Klassen:
```
"classes": "my-special-class"
```
oder als Callback-Funktion:
```
"classes": "(rowIndex, row, props) => ... (return String)"
```

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.11`

**Comment by mcuiobroker** [comment]
Funktioniert. Danke.
