### ISSUE TITLE
v3.1.3-beta. 11 ze.format?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2204]
Wo kann ich nachschauen, zu wem / was es gehört?
![image](https://user-images.githubusercontent.com/84818934/215283838-059118b6-7a82-4428-85ac-5c9ba64ad9aa.png)

**Comment by Zefau** [comment]
Ist fast unmöglich es zuzuordnen. Ist vermutlich JsonTable und dort ist der `format` Parameter, der keine Funktion ist.

**Comment by Zefau** [comment]
Ist ein Fehler im Code vermute ich.

**Comment by mcuiobroker** [comment]
Kann das auch durch ein nicht zugeordnetes Widget vorkommen?
![image](https://user-images.githubusercontent.com/84818934/215284819-cab718d1-2b23-4911-b07a-fe7c86321284.png)

**Comment by mcuiobroker** [comment]
Nee ist HTMLtable
`[{   "field": "Plattform",   "format": "val => val === 'null' ? '-' : val" }]`

**Comment by Zefau** [comment]
Ok, danke für den Hinweis. HtmlTable und JsonTable ist intern dasselbe, dann wird es davon kommen.

**Comment by Zefau** [comment]
sollte mit `v3.1.3-beta.12` behoben sein

**Comment by Zefau** [comment]
@mcuiobroker

**Comment by mcuiobroker** [comment]
Ja. Passt. Hatte es vergessen.
