### ISSUE TITLE
v3.1.3-beta.13 HistoryGraph wird nicht aktualisiert?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2206]
![image](https://user-images.githubusercontent.com/84818934/215298032-494ec5da-6e10-4569-b9c1-28ac8595907c.png)
Nach F5 ok
![image](https://user-images.githubusercontent.com/84818934/215298058-6e033f8f-872e-4b71-a79c-9c7357fa1252.png)

**Comment by Zefau** [comment]
@mcuiobroker sollte mit v3.2 behoben sein

**Comment by mcuiobroker** [comment]
Dürfte behoben sein.
Aber jetzt werden nicht mehr alle Kurven angezeigt
![image](https://github.com/user-attachments/assets/dad3ef3e-64d0-4a19-a09e-38b5c7d085bb)

![image](https://github.com/user-attachments/assets/bbaef197-b6e9-4c86-9464-03d2a2202339)

**Comment by Zefau** [comment]
> Dabei fällt auf, dass Y-Axis nicht angezeigt wird

Wird nicht angezeigt, weil nicht ausgewählt? Oder hast du was ausgewählt und es ist leer?
