### ISSUE TITLE
Verhalten Standard-Datenpunkte

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2207]
> Habe nun die Standard-Datenpunkte verwendet, aber irgendwie funktioniert es nicht bzw. steh ich auf dem Schlauch ;-((( 
Obwohl ich den Regler "Level" noch unten auf "0" regle, schaltet der Schalter nicht auf aus...
Was nur mache ich falsch?
![Screenshot 2023-01-28 171213](https://user-images.githubusercontent.com/11274233/215277041-f4e30dd0-6c19-407d-9a4b-2da42c356ffe.jpg)

_Originally posted by @tschortschde in https://github.com/Zefau/ioBroker.jarvis/discussions/2203#discussioncomment-4804768_

**Comment by Zefau** [comment]
@tschortschde schau nochmal mit `v3.1.3-beta.31`

**Comment by tschortschde** [comment]
@Zefau 
Danke, es hat funktioniert
Nachdem ich meine Datenpunkte komplett aus iobroker entfernt habe und neu importierte.
vielen Dank für die Unterstützung und ein schönes Wochenende.
