### ISSUE TITLE
v3.1.3-beta.15 dateTime flackern bei Sekunden?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2210]
![jarvis v313-beta15 dateTime flackern](https://user-images.githubusercontent.com/84818934/215356518-6c2aedc7-c5e0-497d-abaf-bec6374cb21e.gif)
Teilweise werden auch Sekunden übersprungen. Systemüberlastung?

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.29`

**Comment by mcuiobroker** [comment]
Passt. Danke.
