### ISSUE TITLE
v3.1.2 and v3.1.3 > Corrupted widgets while switching JARVIS version while having browser open

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#2211]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [v3.2.1, v3.1.3-beta15] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

I switched between different JARVIS versions while testing via different container (I remember this bug also from the past). While doing this my browser windows is allways still open with the "other" version (upgrade or downgrade behaves the same). Once the browser window is still open I restart the "other" container which leads to a still open JARVIS. Once the other container was started I click on browser refrest, now all widgets are showing empty. I compared the devices, layout and widget DP and realized that the widgets DP is different, which means during this procedure the content of widgets DP has been written / corrupted.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

I attach the different configs for you (sorry for the format, I have it now only in this). So you can compare yourself.
[widgets.txt](https://github.com/Zefau/ioBroker.jarvis/files/10530945/widgets.txt)
[widgets_corrupted.txt](https://github.com/Zefau/ioBroker.jarvis/files/10530944/widgets_corrupted.txt)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by RkcCorian** [comment]
@Zefau : Might be related to #2208?!

**Comment by RkcCorian** [comment]
@Zefau : Jup, passiert immer nach der Versions-Mismatch Meldung reproduzierbar, wenn der Browser während dem Versionswechsel noch offen war

**Comment by RkcCorian** [comment]
@Zefau : Ergänzung... passiert auch wenn die App offen ist/war nach dem Versions-Mismatch. Ist vermutlich die gleiche Ursache und Du bist schon dran, wie ich Dich kenne 😋

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.16`

**Comment by RkcCorian** [comment]
@Zefau : Wie kann ich das am Besten testen? Browser mit der 3.1.2 offen lassen, Update machen und schauen ob es nun nicht mehr die Config zerschießt?!
Hintergrund der Frage: Je nachdem wo Du gefixt hast muss ich ggf. den Test anders durchführen

**Comment by Zefau** [comment]
Jo genau so.

**Comment by Zefau** [comment]
@RkcCorian und? :-)

**Comment by RkcCorian** [comment]
@Zefau: Konnte es gerade testen, leider besteht das Problem nach wie vor. Komme von v3.1.2 auf v3.1.3-beta.18.
[WidgetsFehler.txt](https://github.com/Zefau/ioBroker.jarvis/files/10582514/WidgetsFehler.txt)
[widgets.txt](https://github.com/Zefau/ioBroker.jarvis/files/10582515/widgets.txt)

**Comment by RkcCorian** [comment]
@Zefau: Verständnisfrage... wenn ich die 3.1.2 im Browser noch offen habe, der Adapter bereits Aktualisiert wurde...wirkt dann Dein BugFix? Sprich kommt das Korrumpieren der Widgetdaten durch den BrowserCode oder durch den AdapterCode?
Gibt es sonst noch was, was ich Dir an Daten geben kann, was Dir hilft? Bevor der Fehler nicht behoben wurde bin ich vorsichtig mit einem Update (und dem Testen der App) 😬 Hab zwar die Konfi gespeichert, so kann ich es schnell fixen, aber ich hab keine Kontrolle darüber wann bspw. meine Frau noch mit "altem" Browserfenster drauf zugreift.

**Comment by Zefau** [comment]
Das Korrumpieren der Widgetdaten kommt durch den Browser-Code und ist ein Bug in v3.1.2, der durch Änderungen in v3.1.3 triggert.

Habe eigl. wieder alles auf den Ausgangszustand zurückgestellt, daher bin ich aktuell etwas ratlos.

**Comment by RkcCorian** [comment]
Kannst Du durch Update der v3.1.3 das triggern des Browsers von der v3.1.2 unterbinden?

**Comment by Zefau** [comment]
die `version` in `jarvis.0.widgets` steht / stand beim Update auf `3.0`, nicht auf `3.1`, richtig?

**Comment by RkcCorian** [comment]
Sie steht auf "3", vgl. mitgeschickte Config

**Comment by RkcCorian** [comment]
> @Zefau: Konnte es gerade testen, leider besteht das Problem nach wie vor. Komme von v3.1.2 auf v3.1.3-beta.18. [WidgetsFehler.txt](https://github.com/Zefau/ioBroker.jarvis/files/10582514/WidgetsFehler.txt) [widgets.txt](https://github.com/Zefau/ioBroker.jarvis/files/10582515/widgets.txt)

Hier sind beide Configs. widgets.txt mit 3.1.2 und WidgetsFehler.txt mit 3.1.3

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.1.3-beta.19`

**Comment by Zefau** [comment]
@RkcCorian Hattest du schon Gelegenheit mal gegenzutesten? Danke dir!

**Comment by RkcCorian** [comment]
@Zefau : Leider nein, bin jetzt auch ne Woche beruflich in Indien, tut mir voll leid 😬

**Comment by Zefau** [comment]
kein Problem. klingt geil, viel Spaß :-)

**Comment by RkcCorian** [comment]
Danke Dir!! 😀

**Comment by RkcCorian** [comment]
@Zefau : Hab's getestet mit [v3.1.3-beta.46], leider besteht das Problem nach wie vor.

**Comment by Zefau** [comment]
oh echt? Ich hatte es extra auch nochmal dediziert getestet und bei mir ging es.

1. also downgrade auf v3.1.2.
2. diverse offene jarvis Fenster mit v3.1.2
3. upgrade auf v3.1.3-beta.xx

oder?

**Comment by Zefau** [comment]
Beim Downgrade kam es zu dem Fehler. Liegt aber daran, dass der Fehler ja schon in v3.1.2 existiert, aber wegen Änderungen in v3.1.3 trägt. Daran kann ich nichts mehr ändern, aber beim Upgrade von v3.1.2 auf v3.1.3 passiert es nicht.

**Comment by RkcCorian** [comment]
@Zefau : Verstehe ich nicht ganz... Fehler kommt zum Tragen, wenn Browser noch 3.1.2 geladen hat und Adapter schon auf 3.1.3 ist, anders herum nicht, richtig?! ... ich vermute ich muss da einmal durch und dann tut es, richtig?!

**Comment by RkcCorian** [comment]
@Zefau: Hab jetzt auf die 3.1.3 gewechselt. Damit sollte es bei mir nicht mehr auftreten Die Frage ist, wie ggf. andere User vor dem Update gewarnt werden den Widget-DP zu sichern, wenn Sie es nicht sowieso über BackitUp haben.
Frage ist damit, wie Du mit diesem Issue hier umgehst... ob ihn schließt oder für andere sichtbar noch offen lässt.
Viele Grüße!
