### ISSUE TITLE
v3.1.3-beta.15: Datumfehler (Komma nach Tag)

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2212]
Bei der Formatierung des Datums wird nach dem Tag immer ein `Komma` gesetzt

### Müll:
**DP:**
![image](https://user-images.githubusercontent.com/85995176/215844901-728c930f-2f9a-4a3a-bd72-a9fe4e99c7a5.png)
**Jarvis:**
![image](https://user-images.githubusercontent.com/85995176/215844034-0aee6c9a-5b46-4f76-8d9c-bffae365a007.png)

### Nächster Feiertag:
**DP:**
![image](https://user-images.githubusercontent.com/85995176/215845019-07d754ec-08ac-40e7-b8e4-413035e977f9.png)
**Jarvis:**
![image](https://user-images.githubusercontent.com/85995176/215844071-caaf2720-96e4-46d2-b00f-6c8b4dab0b2c.png)

### Fahrzeug:
**DP:**
![image](https://user-images.githubusercontent.com/85995176/215844445-b1be422c-a10c-4790-b5cd-9e9d9e83c759.png)
**Jarvis:**
![image](https://user-images.githubusercontent.com/85995176/215844192-f941e2b3-7624-4811-b9a8-3a3ae5ab0e02.png)

**Comment by Mephisto090** [comment]
IP-Adressen auch :D
![image](https://user-images.githubusercontent.com/85995176/215849637-a0b4170d-35e1-459b-97ce-93117cb0efdc.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.16`

**Comment by Mephisto090** [comment]
Jap passt! Danke.
