### ISSUE TITLE
Android-Kennung

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2214]
> Es gibt bei einem Tablet (android 11) mit App (jarvis) und Fully Kiosk Browser einen besonderen Effekt.
Dort wird in den clients kein Unterschied festgestellt. (nutzen anscheinend die gleiche Grundlage?)
-> nur ein Eintrag in den clients.
![image](https://user-images.githubusercontent.com/84818934/215343077-20c62d24-e10e-4933-9acb-33fe3eac2d6d.png)

> Beim Umschalten von einer "App" zur anderen wird die App neugeladen.

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/138#issuecomment-1407717404_

**Comment by Zefau** [comment]
@mcuiobroker mit "App" meinst du nicht die Android-App, sondern die Web-Variante, die in fully läuft, richtig?

**Comment by Zefau** [comment]
> Dort wird in den clients kein Unterschied festgestellt. (nutzen anscheinend die gleiche Grundlage?)

Es muss ja im User Agent auch nicht zwingend ein Unterschied bestehen, wenn es derselbe Browser ist?

**Comment by mcuiobroker** [comment]
Also ich dachte es gäbe einen Unterscheid, wenn man `jarvis` über `Fully` aufruft oder mit der `jarvis-Android-App`. 
Damit man es unterscheiden kann, ob der Aufruf durch die Android-App war? 
Scheint aber nicht zu sein.

**Comment by Zefau** [comment]
Du kannst den User Agent in Fully konfigurieren. Bei mir steht er auf `default`. Wahrscheinlich nimmt er dann denselben, wie die Android App, die ja auch nur eine Website in einem App-Container ist.

**Comment by Zefau** [comment]
Hinzufügen kann ich aber die Informationen von https://cordova.apache.org/docs/en/latest/reference/cordova-plugin-device/index.html

**Comment by mcuiobroker** [comment]
Wenn ich im Fully den Fake User Agent String auf "FullyBrowser" ändere:
![image](https://user-images.githubusercontent.com/84818934/217916796-ddce4151-0489-434e-b966-08873c0b3c27.png)
App bleibt aber trotzdem online?
![image](https://user-images.githubusercontent.com/84818934/217916974-653a0bc0-23bd-496d-92f1-f9767d12dbf1.png)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.41` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.41` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Wie müsste man die User Agent in Fully konfigurieren, damit du ihn dann als `Fully-Browser` erkennen und nutzen kannst?
Momentan erscheint da ja `no-browser-detected` bzw. bei `default`-> `Android-Browser`.

**Comment by Zefau** [comment]
Also ich kann in die Android-App einbauen, dass er zumindest die App erkennt. Dann bleibt aber noch, dass Fully identisch wäre mit dem mobilen Browser, oder?

**Comment by Zefau** [comment]
Der User-Agent wird interpretiert, siehe https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent und https://explore.whatismybrowser.com/useragents/parse/#parse-useragent. Bin mir unsicher, ob das einem Format folgt, was man faken kann.

**Comment by Zefau** [comment]
@mcuiobroker kann das hier zu oder ist hier noch was zu tun?

**Comment by mcuiobroker** [comment]
Ja.
