### ISSUE TITLE
v3.1.3-beta.17: Icon vom TimePickerAction wird nicht angezeigt

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#2217]
Das Icon vom TimePickerAction wird nicht angezeigt. Weder im Firefox auf Windows noch in der Android App.
![grafik](https://user-images.githubusercontent.com/77939385/216430603-b1c8eecb-43db-4829-8438-c65572f5005d.png)

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.18` 
LightColorAction hat auch kein Icon mehr.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.3-beta.19`

**Comment by hosabeni** [comment]
`v3.1.3-beta.20`
Das Icon vom TimePickerAction ist da, aber es fehlt noch das X vom Wetter Popup.


![Image](https://user-images.githubusercontent.com/77939385/217079250-d6fea69b-f31e-4e55-97f5-15295fbd6329.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.26`

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.26`-> wird als `3.1.3-beta.22`angezeigt
LightColorAction Icon ist wieder da.
![image](https://user-images.githubusercontent.com/84818934/217095933-e6942fc7-abc2-4784-8aaa-bfe16a5b6a5a.png)

**Comment by Zefau** [comment]
Ja, da hat sich wieder ein Fehler in mein build-Skript eingeschlichen. Sollte mit dem nächsten Release wieder passen, allerdings habe ich jetzt einige Versionen übersprungen.. :-\
