### ISSUE TITLE
Noch fehlende Homematic/Homematic IP Geräte

### ISSUE THREAD

**Issue by 63chris** [Zefau/ioBroker.jarvis#2221]
Hallo, ich habe noch ein paar Geräte mit undefinierten Datenpunktengefunden, die ja dem Entwickler gemeldet werden sollen :-)

Evtl können die ja noch eingepflegt werden. Insbesondere die virtuellen taster sind häufig in Gebrauch bei Homematic-ern.

Die ioBroker downloads im Anhang

Grüße
Christian
[fehlende Homematic-Geraete.zip](https://github.com/Zefau/ioBroker.jarvis/files/10611574/fehlende.Homematic-Geraete.zip)

**Comment by Zefau** [comment]
Welche Datenpunkte brauchst du denn für die Geräte?
`HM-Dis-EP-WM55` (Homematic Funk-Wandsender mit Display HM-PB-4Dis-WM.json)
`HB-OU-MP3-LED` (HM-LC-Sw4-PCB 4-fach Schaltaktor Niederspannung.json)
`HmIP-PS-2` (HmIP-PS-2 Schaltsteckdose.json)
`HmIP-RCV-50` (HmIP virtuelle Taster.json / HM Virtuelle Taster.json)

**Comment by 63chris** [comment]
Hallo,

die Datenpunkte sind ja in den ioBroker downloads in der ZIP Datei. Ist die Frage, welche davon übernommen werden sollen?

**Comment by Zefau** [comment]
Jo

**Comment by 63chris** [comment]
so, im Anhang die Liste der Datenpunkte, hoffe, das ist in dieser Form so OK.
habe auch noch mal die JSONs neu dazu gepackt.

für die virtuellen Taster denke ich, das nicht alle 50 vordefiniert sein müssen, habe mal 8 gelistet. Weitere kann man sich ja dann händisch hinzufügen

Gruß
Christian
[Homematic Geraete Datenpunkte.txt](https://github.com/Zefau/ioBroker.jarvis/files/10685779/Homematic.Geraete.Datenpunkte.txt)
[fehlende Homematic-Geraete.zip](https://github.com/Zefau/ioBroker.jarvis/files/10685782/fehlende.Homematic-Geraete.zip)

**Comment by themacmaus** [comment]
Hallo Zefau,

ich wollte mich erkundigen, ob der Device-Import für HmIP-WRC6 und HmIP-FBL schon geplant ist.

Mit Dank im voraus und Gruss,

Michael

**Comment by froemer4773** [comment]
Guten Morgen,
bin neu im jarvis Umfeld und habe auch viele Homematic Geräte im Einsatz und leider sehr viele davon werden derzeit nicht unterstützt. Um mir selber zu helfen, habe ich danach hier mal gesucht und würde gerne die vFB (virtuellen Taster der CCU2) aus der Datei als Gerät einbauen, was mache ich mit dem JSON aus dem ersten Eintrag des Threads hier? Kann ich selber diese Datei importieren?

Gruß
Frank

**Comment by 63chris** [comment]
Hallo,
würde mir auch wünschen, wenn mehr HM(IP) Geräte nativ unterstützt werden. Liste ist noch länger geworden.
denke, bei >400 offenen issues sind die Prioritäten z.Z. aber verständlicherweise woanders.
Ich behelfe mir damit, diese manuell einzubinden. Ist zwar etwas Fleißarbeit aber nur einmalig.

PS: m.E. würde es helfen, wenn es ein Definition-Template o.ä. geben würde, womit ein Benutzer so eine Gerätedefinition auch für die Allgemeinheit bereistellen könnte - oder Klarheit, welche Datei(en) man extrahieren und hier bereitstellen könnte, wenn man ein unbekanntes Gerät manuell definiert hat. Das würde den Entwickler auch entlasten.

**Comment by mcuiobroker** [comment]
https://github.com/Zefau/jarvis.adapters 

Hier sind die js für den Importer.

**Comment by 63chris** [comment]
och, gibt's also schon. Ich schau dann mal, ob ich die Geräte direkt dort einpflegen kann - ohne Sytaxfehler ;-)

Danke!

**Comment by Zefau** [comment]
@63chris
