### ISSUE TITLE
Modul DisplayImage auch Url aus Datenpunkt?

### ISSUE THREAD

**Issue by nicomania** [Zefau/ioBroker.jarvis#2223]
Hallo, 

kann man es möglich machen, im Modul "DisplayImage" als Url auch einen Datenpunkt (welcher die Url enthält) anzugeben? Unter Jarvis V2 war dies möglich, jetzt geht aber nur noch Url oder Base64. Von meiner Surveillance Station werden leider nur Live-Bild-Urls meiner Überwachungskameras in Datenpunkten bereit gestellt, die mit einem wechselnden Key aufgerufen werden. Ein "iframe" Modul ist leider auch nicht hilfreich. Auch hier kann ich nur eine statische Url angeben.

Danke, VG

**Comment by Zefau** [comment]
Du kannst die URL doch direkt in jarvis in der Modul Konfiguration hinterlegen?

**Comment by nicomania** [comment]
Nein, das ist nicht zielführend. Wie oben beschrieben ist die URL _dynamisch_ und ändert sich alle paar Stunden.

Beispiel, im Datenpunkt steht: `http://192.168.178.66:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Stream.VideoStreaming&version=1&method=Stream&format=mjpeg&cameraId=1&StmKey="242065cbde56a26e992eac3ccfe85767"`

Der "StmKey" ändert sich alle paar Stunden. Wenn ich die URL also manuell hinterlege habe ich nach kürzester Zeit kein Bild mehr in der Vis, sondern ein Platzhaltersymbol, weil die URL nicht mehr gültig ist.
In Jarvis V2 konnte man hier noch einen Datenpunkt hinterlegen und das hat auch prima geklappt.

**Comment by Zefau** [comment]
@nicomania gerade nochmal in den Quellcode geschaut: Also die URL wird vom Datenpunkt geladen und dann als Bild angezeigt. Screenshote mal bitte deine Konfiguration und das Ergebnis im Frontend. Hast du Fehler in der Browser-Konsole (via F12)?

**Comment by nicomania** [comment]
Man kann also entgegen der Beschreibung doch einen Datenpunkt angeben? Also URL, Base64 und Datenpunkt? Letzteres funktioniert bei mir leider nicht. Wenn ich den Datenpunkt wie folgt eingebe....


![image](https://user-images.githubusercontent.com/35151132/217923780-97dbcbe4-ff49-46b5-a469-f1f16686058d.png)


bekomme ich nur ein Platzhalterbild....

![image](https://user-images.githubusercontent.com/35151132/217924490-70c52d15-5e0f-42ec-b5f6-4aae6bf38d27.png)


Das ist auch klar, denn im Quelltext steht: 
`<img class="jarvis-DisplayImage-Image center top" src="data:image;base64,synology.0.SurveillanceStation.cameras.Carport.linkMjpegHttpPath" style="width: auto; height: 385px;">`


Also wird die URL aus dem Datenpunkt nicht gelesen, sondern einfach die Datenpunktadresse an den Browser übermittelt. Das bestätigt auch die Konsole:

![image](https://user-images.githubusercontent.com/35151132/217925588-225fd247-f236-459e-9539-903bcefd027b.png)

**Comment by Zefau** [comment]
Du wählst unten das Gerät aus mit dem Datenpunkt

**Comment by mcuiobroker** [comment]
1. Wer hat den Inhalt geschrieben? `<img ....>` -> der ist falsch!
2. Du musst den DP zuordnen `synology.0.SurveillanceStation.cameras.Carport.linkMjpegHttpPath` (dort steht http:// .... drin)
3. - also Gerät hinzufügen -> DP als state anlegen
4. Den angelegten stateKey (Geräte-DP) dann im displayImage zuordnen.

**Comment by nicomania** [comment]
Hat funktioniert, danke. Diese Konfiguration wurde übrigens, wie schon erwähnt, von Jarvis V3 automatisch aus V2 so übernommen. Ist mir unverständlich warum die Datenpunktangabe nun über "Gerät hinzufügen" gehandhabt wird, aber es wird schon einen Grund geben. Vielleicht wäre ein Hilfetext an der URL-Eingabe hilfreich.
Danke und einen schönen Abend noch!
