### ISSUE TITLE
Bild als Anzeigenvariante wird nicht aktualisiert

### ISSUE THREAD

**Issue by Missenberger79** [Zefau/ioBroker.jarvis#2224]
Hallo,
ich wollte, da es noch keine Sonos integration gibt mir das selber zusammen bauen. Soweit habe ich die wichtigsten Punkte zum laufen bekommen. Was jedoch nicht geht, das ich das Cover als Anzeigenvariante einbinde und über einen DP aktualisiere.

Ich habe als Anzeigenvariante folgenden Code hinterlegt:
```
{
  "false": "<img src='http://192.168.2.19:8082/state/sonos.0.root.192_168_2_211.cover_png ' width='200px' height='200px'>",
  "true": "<img src='http://192.168.2.19:8082/state/sonos.0.root.192_168_2_211.cover_png ' width='200px' height='200px'>"
}
```

Über einen boolschen Werte hätte ich das Cover aktualisieren lassen. Jedoch hat er immer das Cover das er beim Start von Jarvis aktuell ist und refresht das nicht.

**Comment by mcuiobroker** [comment]
Muss das in einer StateList angezeigt werden? displayImage?
Wie ist es zurzeit? Bitte ein Bild. (Frontend und Layout)

**Comment by Zefau** [comment]
Das ist doch dieselbe URL bei beiden Zuständen? Die URL muss anders sein, damit der Browser das Bild neu lädt.

**Comment by Missenberger79** [comment]
Das obere Cover ist als DisplayImage und wird alle 10 sec aktualisiert und zeigt das richtige auch an.
Die Url ist die gleiche wie die für True die als Anzeigenvariante konfiguriert ist.
Auch wenn ich für false eine andere URL konfiguriere, dann wird zwar das Bild umgeschaltet, angezeigt wird aber nur das was beim Seitenaufruf aktuell ist. Wenn sich in einer Playlist das Cover ändert, dann wird das nicht aktualiesert.

![image](https://user-images.githubusercontent.com/58929668/217335386-4685596e-5547-4b7c-8ffb-e94c798e564c.png)
![image](https://user-images.githubusercontent.com/58929668/217343871-57c981bd-7bd0-482b-b7a5-5f4d199ebf0f.png)


@mcuiobroker Wie kann ich sonos als MedieControl machen? Hier wird mir nur alexa und spotify angezeigt!
Bin auf der stable 3.1.2

**Comment by mcuiobroker** [comment]
Laut https://github.com/Zefau/ioBroker.jarvis/issues/173 soll es SONOS auch unterstützen seit v2?
https://github.com/Zefau/ioBroker.jarvis/issues/173#issuecomment-756339912_
Müsste @zefau was zu sagen, ob es damals doch nicht umgesetzt wurde oder mit v3 rausgeflogen ist?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/618

**Comment by Zefau** [comment]
@mcuiobroker ist das hier noch aktuell?

**Comment by mcuiobroker** [comment]
Ja, Sonos wird noch nicht unterstützt

**Comment by mcuiobroker** [comment]
Aber sonst das Problem mit der Anzeigevariante passt.
