### ISSUE TITLE
BlindLevelAction fehlt in Gruppenaktion

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2229]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/1507

<div type='discussions-op-text'>

<sup>Originally posted by **tofrie** January 16, 2022</sup>
In der Jarvis v2 gab es die Gruppenfunktionen hoch und runter, diese wird bei mir in v3 nicht angezeigt…

![43A2D22A-C944-4094-8C83-987BF468736B](https://user-images.githubusercontent.com/60553702/149661042-929c1f20-07ec-4146-b19e-81c54760e53e.png)
</div>

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1416

**Comment by Zefau** [comment]
@SKB-CGN @tofrie mit `v3.1.4-beta.5` ist es wieder verfügbar. Könntet ihr bitte prüfen, ob es wie gewünscht funktioniert?

**Comment by mcuiobroker** [comment]
Sollte es dort nicht auch ein "STOP"-Button geben?
![jarvis-v314-beta 8 Gruppenaktion blindLevelaction](https://user-images.githubusercontent.com/84818934/234997294-79986f2f-7339-4b04-ad94-8896fb7bfbd1.gif)
