### ISSUE TITLE
Binding erweitern für Icon und Icon Stil auf beiden Seiten (key, value)

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2230]
Um die Farbe von einem DP im Icon darzustellen , muss man ein Binding zum {val} oder zum DP {0_userdata.0.test1DP} setzen können.
Aber nicht nur mit der Farbe sondern grundsätzlich mit allen Properties. Diese sollten Binding-fähig sein.
#2225 

Probiert im Icon Stil:
`{"default":{"color":"'{0_userdata.0.jarvis.test.colHex}'"}}`
`{"color":"'{0_userdata.0.jarvis.test.colHex}'"}`
`{"color":"'{val}'"}` // val String

Weiterhin funktionieren Darstellungen mit LightColorState nicht
Named Colors und #ff00ff00 (mit alpha Kanal) und RGB?

**Comment by Zefau** [comment]
Sollte alles Binding-fähig sein

**Comment by mcuiobroker** [comment]
Er macht es aber nicht. Also ich habe es mit den Versuchen oben probiert. Die Farbe vom Icon bleibt weiß.

**Comment by Zefau** [comment]
`undefined` bzw. `false` ist der Datenpunkt-Wert, der im Modul ankommt.

**Comment by mcuiobroker** [comment]
Im DP steht aber #ff0000?

**Comment by mcuiobroker** [comment]
Alpha-Kanal wird nicht akzeptiert?
![image](https://user-images.githubusercontent.com/84818934/218281723-85f06838-73b9-4e21-807c-1580307a1307.png)

**Comment by Zefau** [comment]
Wie hast du `LightColorState` konfiguriert? Da musst du einstellen, dass er nicht die Datenpunkt-Styles nehmen soll.

**Comment by Zefau** [comment]
Achso sorry, hast du. Geht um Alpha-Kanal.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/218282183-5f28bfd1-41b8-4f71-865e-9b1d634de237.png)

**Comment by Zefau** [comment]
Wobei screenshote mal trotzdem die Komponenten-Optionen vom `LightColorState` bitte.

**Comment by Zefau** [comment]
`nur Icon anzeigen` raus nehmen und dann im Layout die Anzeige deaktivieren.

**Comment by Zefau** [comment]
> Alpha-Kanal wird nicht akzeptiert?

Funktioniert auch. Spiel mal mit den Werten. Wenn du alpha-Kanal auf `00` hast sieht man es einfach nicht. Versuch mal `#ff00ffaa`.

**Comment by djalexz** [comment]
Moin zusammen, also wie muss das richtig eingestellt werden damit mein Wunsch umgesetzt wird?
Ich habe den Überblick verloren 😅

**Comment by mcuiobroker** [comment]
Du wolltest nur links das Icon mit der Farbe vom Statewert?
-> Icon Stil : 
`{"color":"'{val}'"}`  
`{"color":"{val}"}` // hat auch funktioniert?

**Comment by djalexz** [comment]
Richtig, aber mit keiner Einstellung funktioniert es.
Weder mit LightColorState, noch ohne, noch sonst wie.

Ohne LightColorState und mit dem Gewerk Sonstiges:

![image](https://user-images.githubusercontent.com/11389551/218696808-5db58cd4-b12c-4fbe-822e-0bdb84d390c2.png)

![image](https://user-images.githubusercontent.com/11389551/218696879-50230e60-a838-4434-8dfb-7ab23c7a76a9.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/218697244-d1127374-6d9f-40e2-896c-b3c798594aa1.png)
`LightColorState` einstellen

**Comment by djalexz** [comment]
Sorry geht nicht:

![image](https://user-images.githubusercontent.com/11389551/218701255-cb60463b-e40f-417f-ba89-f72d90b2c238.png)

![image](https://user-images.githubusercontent.com/11389551/218701343-395659a1-ca10-4943-8da4-dce49322f692.png)


![image](https://user-images.githubusercontent.com/11389551/218701436-40263b4f-cef2-43c2-bf9e-af07b692fab6.png)

**Comment by mcuiobroker** [comment]
Welche Version hast du denn ?

**Comment by djalexz** [comment]
Version: 3.1.2
Bekomme irgendwie die neuste Beta nicht installiert via ioBroker GIT Installation...

Ja sorry, habe LightColorState eingestellt, aber leider immer noch das Gleiche.

**Comment by djalexz** [comment]
Ah ok, dann warte ich einfach noch etwas.
Sonst-> Expertenmodus -> Katze -> von github -> jarvis -> installieren bleibt er bei der 3.1.2...
Hat sonst immer so funktoniert.

Keine Ahnung

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/218703478-025c0b0a-73ab-47a0-bd97-156f34c4fd65.png)
??

**Comment by djalexz** [comment]
![image](https://user-images.githubusercontent.com/11389551/218704030-1d10f011-676e-46cc-818d-4fee43394832.png)

**Comment by djalexz** [comment]
Ja stimmt.
Dann werde ich mal Veeam anschmeißen und im Anschluss mal die neuste Beta draufschmeißen.

Danke dir.

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.41`
Jetzt funktioniert es mit dem LightColorState nicht mehr.
![image](https://user-images.githubusercontent.com/84818934/219891340-1ebd72d7-faf3-42f6-b995-ec4f0150f2c6.png)

**Comment by Zefau** [comment]
Ist doch rot? Hat ja noch ein alpha-Kanal auf 40% ?

**Comment by mcuiobroker** [comment]
Ja aber das linke Icon "printer" war vorher auch rot. -> {val} Binding funktinierte

**Comment by Zefau** [comment]
Ah, Icon. ok

**Comment by Zefau** [comment]
`3.1.3-beta.42`

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.45`
Binding wieder weg
![image](https://user-images.githubusercontent.com/84818934/219970051-fb3c84d3-7a90-4995-8f55-110c291fa656.png)

**Comment by Zefau** [comment]
`v3.1.3-beta.46`

**Comment by mcuiobroker** [comment]
sieht gut aus. Danke.
