### ISSUE TITLE
v3.1.3-beta.34 Fehlermeldung?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2233]
Bekomme jetzt diese Meldung?
Wo muss ich suchen?

![image](https://user-images.githubusercontent.com/84818934/218344606-7de5abc6-305c-4aa8-bf39-af0a3442842e.png)

**Comment by Zefau** [comment]
Hängt wahrscheinlich mit dem Bindung Fehler zusammen, dass Zeilen ausgeblendet werden.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.35`

**Comment by mcuiobroker** [comment]
Meldung kommt nicht mehr.
