### ISSUE TITLE
Icons mittig ausrichten Fehler 

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#2235]
Icons lassen sich nicht mittig ausrichten mit StateList (Übereinander)

https://forum.iobroker.net/topic/59201/jarvis-v3-1-x-just-another-remarkable-vis/6?_=1676409582026

![Screenshot (5356)](https://user-images.githubusercontent.com/41079106/218877287-303ed6fe-f755-4ec7-8757-dbfb10d1766d.jpg)

v3.1.3-beta.31

**Comment by Zefau** [comment]
via CSS?

**Comment by mcuiobroker** [comment]
hover passt auch nicht?
![image](https://user-images.githubusercontent.com/84818934/218878018-619c3204-7e81-4e10-a8c8-4b61dc531dde.png)

**Comment by Sascha8** [comment]
Sigi, welcher Staugsaubroboter ist das denn, der sich so schön in iobroker integrieren lässt?

**Comment by sigi2345** [comment]
> Sigi, welcher Staugsaubroboter ist das denn, der sich so schön in iobroker integrieren lässt?

https://forum.iobroker.net/topic/28717/vis-von-sigi234/2

**Comment by Zefau** [comment]
@sigi2345 ist das hier mit v3.2 noch aktuell?

**Comment by sigi2345** [comment]
Erledigt
