### ISSUE TITLE
v3.1.3-beta.40 hsl im Datenpunkt Stil wird nicht umgesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2237]
![image](https://user-images.githubusercontent.com/84818934/219123834-ac29abd4-b6a7-4bb6-98a8-deefee9e4a57.png)

```
{"0":{"color":"hsl(0,100%,50%)"}}
```

Es scheint dort einiges durcheinander?
![image](https://user-images.githubusercontent.com/84818934/219100693-304032f3-5414-4625-856b-009fb4ac28d5.png)

![image](https://user-images.githubusercontent.com/84818934/219100789-e2c6cfc0-2e89-4248-918b-22749025267d.png)
Woher holt er die 39?

Wohnzimmer FritzDect
v3.1.3-beta.40 bis 100
![image](https://user-images.githubusercontent.com/84818934/219100944-3cdbc1fa-9bbd-4ce3-b851-2b1b1b6bf740.png)
v3.1.3-beta.31 -bis 25°C
![image](https://user-images.githubusercontent.com/84818934/219101108-e0a90bdb-eb64-4ab4-82f7-75e93887082f.png)

**Comment by Zefau** [comment]
Überschrift ist `Datenpunkt Stil`, aber im Screenshot ist keiner hinterlegt?

**Comment by mcuiobroker** [comment]
Ja 2 Sachen in eins gepackt.

**Comment by Zefau** [comment]
Ist das erst mit beta-40 und davor gings?

**Comment by mcuiobroker** [comment]
Mit `v3.1.3-beta.31`ging es alles noch.

**Comment by Zefau** [comment]
aber mit beta-32 nicht mehr?

**Comment by mcuiobroker** [comment]
Müsste ich prüfen, mit `v3.1.3-beta.32` war der Icon-Stil nicht mehr korrekt.

**Comment by cooper1988** [comment]
Kann ich bestätigen. Ab Beta 32 gehen keine Styles mehr, teilweise wurden bei mir auch einige Datenpunkte nicht mehr angezeigt.

Beta 31 alles in Ordnung.

**Comment by Zefau** [comment]
`v3.1.3-beta.41`

**Comment by mcuiobroker** [comment]
Ja hier passt es wieder.
