### ISSUE TITLE
v3.1.3-beta.40 Icon Stil wird nicht umgesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2238]
Icon Stil
`{"default":{"color":"grey"}}`
![image](https://user-images.githubusercontent.com/84818934/219051828-3fd7215f-ebb9-4b62-a98d-995b229bee77.png)

**Comment by mcuiobroker** [comment]
Nicht nur HKT , auch normale StateList.

**Comment by Zefau** [comment]
`v3.1.3-beta.41`

**Comment by mcuiobroker** [comment]
wird nicht hochgeladen?

**Comment by Zefau** [comment]
Danke für den Hinweis. Jetzt ist es oben.

**Comment by mcuiobroker** [comment]
Icon-Stil ist wieder ok, aber LightColorState nicht.

**Comment by Zefau** [comment]
Gibt es für LightColorState noch ein offenes Issue? Was stimmt denn nicht?

**Comment by mcuiobroker** [comment]
`v3.1.3-beta.43` Stil wieder weg.

**Comment by Zefau** [comment]
Merkwürdig, bei mir geht es mit der `v3.1.3-beta.43`

**Comment by Bernd9000** [comment]
`v3.1.3-beta.43`
Benutze ich für Farbe im Icon Stil `rgba()` funktioniert es bei mir

**Comment by Zefau** [comment]
Hm, Hex geht nicht?

**Comment by Bernd9000** [comment]
`{"color":"red"}` oder `{"color":"#0F0"}` funktionieren **nicht**

 {"color":"rgba(255,0,0,1)"} funktioniert

Vielleicht irgendwo Funktionen mit den Farbmodellen vertauscht ?

**Comment by jvpihole** [comment]
V3.1.3-beta.43
Es gibt nicht nur bei den Farben ein Problem, sondern auch bei der font-size und bei der animation. 
Bsp.: 
{"0":{"color":"black","animation":"rotieren 4s infinite linear","font-size":"80px"},"1":{"color":"black","animation":"blinker 2s linear infinite","font-size":"70px"},"default":{"color":"black","font-size":"70px"}}
Icon Stil wird komplett nicht umgesetzt.

**Comment by Zefau** [comment]
`v3.1.3-beta.44`

**Comment by jvpihole** [comment]
V3.1.3-beta.44 
Alle beschriebenen Probleme sind behoben: color,font-size und animation
Danke
