### ISSUE TITLE
DasWetter Zugriff broken

### ISSUE THREAD

**Issue by 63chris** [Zefau/ioBroker.jarvis#2244]
Jarvis 3.1.3

seit heute ist die Anzeige der Wetterdaten verschwunden und es kommt u.a. Fehlermeldung. Die Daten wurden aber nicht verändert.
![daswetter](https://user-images.githubusercontent.com/34574073/220989326-b41f9f7f-566b-45a9-b153-6b2c00cb1198.png)

Der Adapter läuft, hat auch Zugriff auf DasWetter.com, Daten werden geladen, keine Fehler im ioBroker Log.

![daswetter 2](https://user-images.githubusercontent.com/34574073/220991244-189a9504-d484-4e7a-88e9-b0c7f834338d.png)

Gruß
Chris

**Comment by Zefau** [comment]
jarvis arbeitet unabhängig von dem `daswetter` Adapter und fragt direkt die API ab.

Die API von daswetter.de liefert ein Fehler zurück, daher geht es aktuell nicht. Fehler liegt bei daswetter.de

**Comment by 63chris** [comment]
läuft wieder, Danke
