### ISSUE TITLE
v3.1.3 callback in Datenpunkt-Eigenschaften funktioniert nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2245]
`{"value":"val=> val.substring(0,6)"}`
oder
`{"value":"val=> val.substr(4,val.length-10)"}`

Dies funktionierte in den Versionen davor. 
Ab wann genau der Fehler aufgetreten ist, kann ich nicht sagen.

![image](https://user-images.githubusercontent.com/84818934/221032782-7117acba-c32b-4155-99b9-906a6c675381.png)

**Comment by Zefau** [comment]
`{"value":"val=> !val ? '' : val.substr(4,val.length-10)"}`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/221033411-d0e7290b-168f-4a61-90ad-0bc45bc45fe5.png)

**Comment by mcuiobroker** [comment]
Passt
