### ISSUE TITLE
Binding für Icon Stil und andere Bindings auch mit value 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2246]
Es funktioniert ja schon der {val} als `color` für den Icon Stil.
-> `{"color":"{val}"}`
Wenn man den value auch als Zuordnung im Binding festlegen kann, hat man die Möglichkeit den val noch zu beeinflussen.

**Comment by Zefau** [comment]
Sollte bereits funktionieren mit `value`

**Comment by mcuiobroker** [comment]
Nein.
![image](https://user-images.githubusercontent.com/84818934/221034221-afb53a50-dce0-4d22-be07-058d39ff1e0c.png)
![image](https://user-images.githubusercontent.com/84818934/221034290-9eb2fe35-915c-4aee-8b6c-356551885ebf.png)

**Comment by Zefau** [comment]
`v3.1.4-beta.3`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/221714222-e0292097-d2a4-4446-a761-114e58a62078.png)

Bei Icon-Stil funktioniert es. Hast du es auch bei den anderen eingerichtet? Body-Stil usw?

**Comment by Zefau** [comment]
Sollte überall funktionieren

**Comment by mcuiobroker** [comment]
Ich prüfe es dann bei Gelegenheit. Mache hier erstmal zu. Danke.
