### ISSUE TITLE
Fehlende Homematic IP Geräte

### ISSUE THREAD

**Issue by Mikeg-82** [Zefau/ioBroker.jarvis#2250]
Hallo zusammen,

im Anhang befindet sich ein ZIP mit mehreren gewünschten Hometic-Geräten:

- HmIP-ASIR-B1
- HmIP-eTRV-B1
- HmIP-eTRV-E
- HmIP-FSI16

Ich wäre euch dankbar, wenn ihr diese integrieren würdet.

Herzlichen Dank

Michael

[JarvisFeatureRequest.zip](https://github.com/Zefau/ioBroker.jarvis/files/10833690/JarvisFeatureRequest.zip)

**Comment by Zefau** [comment]
@Mikeg-82 mit `v3.1.4-beta.5` nun verfügbar
