### ISSUE TITLE
v3.1.3 apk android 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2251]
9 bytes sind zu wenig
![image](https://user-images.githubusercontent.com/84818934/221415414-26ae7720-abc3-409d-864d-369fa60dcbba.png)

**Comment by mcuiobroker** [comment]
Keine apk und keine windows zip?
![image](https://user-images.githubusercontent.com/84818934/221447125-d817dacd-6806-4a75-9555-ae74ad7d64d0.png)

**Comment by Zefau** [comment]
Ne

**Comment by Zefau** [comment]
`v3.1.4-beta.3`
