### ISSUE TITLE
Error adding notification: Unexpected token < in JSON at position 1

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#2253]
Seit Jarvis V 3.1.2 erhalte ich im ioBroker Protokoll die oben genannte Fehlermeldung und das Notification Popup erscheint auch nicht mehr.

**Comment by Zefau** [comment]
Was ist denn dein Input?

**Comment by SlipKoRn88** [comment]
Ich schreibe über ein Blockly bei Erhalt von Post folgendes:

{
"title": "Briefkasten",
"message": "Post ist da",
"display": "popup",
"state": "read",
"progress": true,
"timeout": 2880000,
"iconColor": "red",
"textColor": "black",
"color": "yellow",
"spinner": true,
"icon": "bell-ring-outline"
}

**Comment by Zefau** [comment]
@SlipKoRn88 schau bitte nochmal mit `v3.1.4-beta.5`

**Comment by SlipKoRn88** [comment]
> @SlipKoRn88 schau bitte nochmal mit `v3.1.4-beta.5`

Funktioniert wieder
