### ISSUE TITLE
Error: Verify Licences: Cannot read properties of undefined

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#2254]
Ich nutze auf Windows das Programm Wallpaper Engine. Mit diesem kann ich Jarvis als Wallpaper auf einem Desktop verwenden. Vor v3.1.3-beta.27 funktionierte es einwandfrei. Seit v3.1.3-beta.47 erhalte ich:

![Fehler](https://user-images.githubusercontent.com/95069101/221488672-a0b790c1-d4c2-45f7-acb5-32e2a473b5d5.jpg)

Aktuell bin ich auf 3.1.2

**Comment by Zefau** [comment]
Und die finale v3.1.3?

**Comment by SlipKoRn88** [comment]
Mit der v3.1.3 besteht es weiterhin

**Comment by Zefau** [comment]
Bist du sicher, dass es mit `v3.1.3-beta.46` noch funktionierte? Die Änderungen zur `.47` waren nur im Release-Workflow, die keine Auswirkungen auf jarvis als solches haben.

**Comment by SlipKoRn88** [comment]
Sorry, vor v3.1.3-beta.27 funktionierte es. Ich bin von v3.1.3-beta.27 auf v3.1.3-beta.47

**Comment by Zefau** [comment]
@SlipKoRn88 schau bitte nochmal mit `v3.1.4-beta.5`

**Comment by SlipKoRn88** [comment]
> @SlipKoRn88 schau bitte nochmal mit `v3.1.4-beta.5`

Es funktioniert wieder
