### ISSUE TITLE
v3.1.4-beta.2 Einrichtung nach Kompletter Neuinstallation direkt auf beta schlägt fehl

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2257]
Neues System nur mit web-Adapter.
![image](https://user-images.githubusercontent.com/84818934/221644072-ca77d77c-d54a-40e2-bda2-ea5deeb563fc.png)
Objekte sind vorhanden.
![image](https://user-images.githubusercontent.com/84818934/221644302-8f367b4a-161d-4ccb-afe3-b69e17eeeb1d.png)

Meldungen im LOG
![image](https://user-images.githubusercontent.com/84818934/221644394-11da7130-8a3e-488f-9e01-d94026453ba5.png)

Komische Meldungen während der automatischen Generierung.
![image](https://user-images.githubusercontent.com/84818934/221644909-fd85a1d3-e1c8-481e-a900-dbc92fef217a.png)

Welche Vorrausetzungen sind notwendig?

**Comment by Zefau** [comment]
mit `v3.1.4-beta.3` sollte es nun passen

**Comment by mcuiobroker** [comment]
Kommentare sind jetzt ok, es fehlen aber die Vorrausetzungen. Man müsste einen Hinweis bekommen, welche Adapter gelesen werden und als Beispiel dargestellt werden?

Ergebnis ist
![image](https://user-images.githubusercontent.com/84818934/221697720-099f457e-84e4-4368-93a8-d1f7614da6b7.png)

**Comment by Zefau** [comment]
Hast du einen leeren ioBroker?

Gelesen werden 
```
'deconz',
'hm-rpc',
'hmip',
'hue',
'hue-extended',
'shelly',
'zigbee',
'zwave2'
```

**Comment by mcuiobroker** [comment]
Ja genau ein komplett leeres ioBroker-System nur WEB und jarvis. 
Da sollte halt eine Warnung kommen mit dem Inhalt der Vorrausetzungen?

**Comment by Zefau** [comment]
Der Screenshot ist von der zweiten Tour? Welcher Step ist das? 4?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/221698913-118dfe81-665b-485a-827f-637e5438851f.png)
Und dann next

**Comment by mcuiobroker** [comment]
Auch die Sprache sollte direkt auf Systemsprache eingestellt sein?

**Comment by mcuiobroker** [comment]
Aufgefallen ist auch der Traffic (Ereignisse)
`Jarvis nicht gestaret`

![image](https://user-images.githubusercontent.com/84818934/221705749-59412cbb-98ab-4769-a5d0-61b6222f9b2e.png)

`Jarvis gestartet`
![image](https://user-images.githubusercontent.com/84818934/221706000-a2755a52-06a5-4da7-b03c-4d7058747fbe.png)

**Comment by mcuiobroker** [comment]
`v3.1.4-beta.4`
Es werden jetzt keine Widgets mehr angelegt.
Es fehlt noch die direkt Spracheinstellung auf Systemsprache.
Sprache ist leer.
![image](https://user-images.githubusercontent.com/84818934/222269205-1aec5866-3acb-469c-9ee6-e34f1128118d.png)

**Comment by Zefau** [comment]
Bei mir springt er auf die korrekte Sprache. `jarvis.0.settings` steht initial auf `{}` und dann nach der Einführung sind die Einstellungen drin. Bei mir ohne Angabe einer Sprache in den `settings`, wodurch er auf den System-Standard springt.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/222552099-7e5bd922-5d04-45e6-8e67-36667bb84d8c.png)
![image](https://user-images.githubusercontent.com/84818934/222552230-ee1e3042-2206-4bb2-9932-5b85f4fa52f7.png)

**Comment by Zefau** [comment]
Was steht denn bei dir in `jarvis.0.settings`?

Mach bitte nochmal von vorne. Glaube da laufen paar Dinge inkorrekt zusammen.
1. jarvis Fenster schließen
2. `jarvis.0.settings` auf `{}` resetten
3. Einführung durchlaufen

**Comment by Zefau** [comment]
Jo, passt. `Target not found` kommt, weil er halt nichts geladen hat.

**Comment by mcuiobroker** [comment]
Warum kommt das?
![image](https://user-images.githubusercontent.com/84818934/222561706-edb01e5c-2377-4e85-909c-9b63ac6ef2f2.png)

**Comment by Zefau** [comment]
Kopier' mal den gesamten `jarvis.0.settings` Inhalt hier rein bitte

**Comment by mcuiobroker** [comment]
```
{"language":"","pageFavicon":"","pageTitle":"jarvis - just another remarkable vis","pageHome":"","pageHomeReturn":0,"hideProNotification":false,"quickJumper":"mobile","reload":true,"drawerMiniMode":true,"drawerShowMenuButton":true,"drawerShowSettings":true,"undefined":"","tabsCollapse":false,"tabsDense":false,"tabsBottom":false,"tabsSwipe":"mobile","tabsSwipeAnimation":"mobile","tabsShow":"hide","defaultBoxIcon":"","themeDarkMode":false,"brandPrimary":"#1976d2","brandSecondary":"#26a69a","brandAccent":"#9c27b0","scrollbars":"always","breakpoint-sm":600,"breakpoint-md":1024,"securePageType":false,"securePagePassword":"","securePageGroups":["system.group.administrator"],"secureConfigurationType":false,"secureConfigurationPassword":"","secureConfigurationGroups":["system.group.administrator"],"secureLogin":true,"LastChangeBody":"","tourIntroduction":true,"tourInterface":true}
```

**Comment by mcuiobroker** [comment]
`v3.1.4-beta.5` Sprache bleibt leer
![image](https://user-images.githubusercontent.com/84818934/222854491-0d4d4c0b-a053-4fba-8ba4-b63510921b21.png)
Tour wiederholt -> `settings` -> `{}` -> `language` -> leer

**Comment by Zefau** [comment]
Dass die Sprache leer ist, ist nicht schlimm. Dadurch erfolgt der Fallback zur Systemsprache.

Die leeren Widgets hingegen sind falsch.

**Comment by Zefau** [comment]
`v3.1.4-beta.6`

**Comment by mcuiobroker** [comment]
Passt so. Danke.
