### ISSUE TITLE
Kalender: Zeiten werden in UTC angezeigt.

### ISSUE THREAD

**Issue by gingerXpat** [Zefau/ioBroker.jarvis#2259]
Die in der Kalender-Widget angezeigten Zeiten sind in UTC angegeben. Der Kalender selbst hat die richtige Zeitzone von UTC+1.
Zum Beispiel wird ein Termin, der um 12:45 Uhr beginnt, im Widget als Beginn um 11:45 Uhr angezeigt.

Ich verwende derzeit 3.1.3-beta.44.

**Comment by gingerXpat** [comment]
Update:  Ich bin jetzt auf v3.1.4-beta.6, zeiten werden immernoch um eine Stunde falsch angezeigt.

**Comment by Zefau** [comment]
Hi @gingerXpat,

kannst du das Problem screenshoten? Ich kann es nicht ganz nachvollziehen.

Mein Termin:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/e02b1d84-69c4-4a82-a0ff-c81cba4e24c9)

Im Widget mit selber Zeit:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/d1fe759d-04cb-4e23-9d98-8e1e7597799c)

**Comment by gingerXpat** [comment]
Hi,

Hier die Termine in Outlook:
[cid:4ea779e0-07c5-4a00-9d1b-833bfb68fa5b]

[cid:2ff87836-35ea-4ba4-b5ea-5fb3e5f374c6]


Hier im Widget:

[cid:167d38a4-6d5f-4dd8-a0b4-78d0437ae76f]

Build: v3.1.9-beta.1


________________________________

**Comment by gingerXpat** [comment]
Hi,

Hier die Termine in Outlook:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/38500626/2634a887-de60-43cc-8a75-7819804fe746)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/38500626/ace8a3d7-771e-4bd9-93b4-2fea62ba6557)


Hier im Widget:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/38500626/4b69fe3d-f2ff-4dd6-8165-e4eba8d63ddf)

Build: v3.1.9-beta.1

**Comment by Zefau** [comment]
Kannst du für den Termin mal die ICAL Daten bereitstellen, damit ich den bei mir importieren kann?

Ich vermute mal, dass Outlook die Zeitzonen anders im ICAL Code angibt.

Danke.

**Comment by gingerXpat** [comment]
> Kannst du für den Termin mal die ICAL Daten bereitstellen, damit ich den bei mir importieren kann?
> 
> Ich vermute mal, dass Outlook die Zeitzonen anders im ICAL Code angibt.
> 
> Danke.

Hi, 
hier die Daten für einen Termin was von 12:45 bis 15:15 geht, aber im Widget mit eine Startzeit von 10:45 angezeigt wird, wie im letzten Screenshot.

`BEGIN:VCALENDAR
PRODID:-//Microsoft Corporation//Outlook 16.0 MIMEDIR//EN
VERSION:2.0
METHOD:PUBLISH
X-MS-OLK-FORCEINSPECTOROPEN:TRUE
BEGIN:VTIMEZONE
TZID:W. Europe Standard Time
BEGIN:STANDARD
DTSTART:16011028T030000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=10
TZOFFSETFROM:+0200
TZOFFSETTO:+0100
END:STANDARD
BEGIN:DAYLIGHT
DTSTART:16010325T020000
RRULE:FREQ=YEARLY;BYDAY=-1SU;BYMONTH=3
TZOFFSETFROM:+0100
TZOFFSETTO:+0200
END:DAYLIGHT
END:VTIMEZONE
BEGIN:VEVENT
CLASS:PUBLIC
CREATED:20230605T070059Z
DESCRIPTION:\n
DTEND;TZID="W. Europe Standard Time":20230406T151500
DTSTAMP:20230605T064652Z
DTSTART;TZID="W. Europe Standard Time":20230406T124500
EXDATE;TZID="W. Europe Standard Time":20230427T124500,20230511T124500,20230
	518T124500
LAST-MODIFIED:20230605T070059Z
PRIORITY:5
RRULE:FREQ=WEEKLY;COUNT=35;BYDAY=TH
SEQUENCE:0
SUMMARY;LANGUAGE=en-us:Justyna
TRANSP:OPAQUE
UID:040000008200E00074C5B7101A82E0080000000071C7CCC44571D901000000000000000
	010000000BA2413A8CEC169479417C1F0720559DF
X-ALT-DESC;FMTTYPE=text/html:<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2//E
	N">\n<HTML>\n<HEAD>\n<META NAME="Generator" CONTENT="MS Exchange Server ve
	rsion 16.0.16529.20000">\n<TITLE></TITLE>\n</HEAD>\n<BODY>\n\n<BR>\n\n</BODY>\n</HTML>
X-MICROSOFT-CDO-BUSYSTATUS:BUSY
X-MICROSOFT-CDO-IMPORTANCE:1
X-MICROSOFT-DISALLOW-COUNTER:FALSE
END:VEVENT
END:VCALENDAR
`

**Comment by Zefau** [comment]
Bei mir sieht es korrekt aus?

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/b5d91fae-fce0-4510-9aa5-9cb831647cda)

Kannst du mal schauen, ob die Zeit / die Zeitzone auf deinem Raspberry korrekt eingestellt ist?

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/5e34d9d3-5fa7-437a-a0f5-39e12c9f0b3e)

**Comment by gingerXpat** [comment]
Ok, das tut mir jetzt Leid. Der LXC hatte in der Tat UTC als Timezone konfiguriert. 🤦‍♂️

**sudo timedatectl set-timezone Europe/Berlin**

Jetzt passt alles. Sorry das ich deine Zeit verschwindet habe.

**Comment by Zefau** [comment]
alles gut, danke für das schnelle Feedback
