### ISSUE TITLE
2 Instanzen ?

### ISSUE THREAD

**Issue by bennigro** [Zefau/ioBroker.jarvis#226]
hallo kann man 2 Instanzen installieren mit unterschiedlichen ports?

**Comment by Zefau** [comment]
Zwei Instanzen ist möglich, aber der Port ist abhängig vom Web Adapter. Wenn es zwei Ports werden sollen, dann braucht es eine zweite Web Adapter Instanz.

**Comment by bennigro** [comment]
danke
