### ISSUE TITLE
Wetterwidget Gefühlte Temperatur

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#2261]
Hallo,
ich glaube die gefühlte Temperatur entspricht immer der Ist-Temperatur. Ich kann keinen Unterschied erkennen.
Aktuell bei diesem Wind müsste die gefühlte Temperatur viel tiefer sein. Im DP des daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_1.windchill_value steht bei -7. Ich weiss das dies etwas unterschiedliche Formeln sind.

Wie wird die gefühlte Temperatur  im Widget errechnet?
Klassisch:? 13,12 + 0,6215*t - 11,37*v0,16 + 0,3965*t*v0,16

![image](https://user-images.githubusercontent.com/104907692/222077545-6c78b4cb-29b5-450b-ad4b-8b8aa5df1898.png)

![image](https://user-images.githubusercontent.com/104907692/222077736-f6d2d1a4-6ab9-4c4d-98fe-622e33467fdb.png)

v3.1.2

Danke für die Prüfung.

**Comment by mcuiobroker** [comment]
`v3.1.4-beat.4`
Kommt von hier?
![image](https://user-images.githubusercontent.com/84818934/222280035-ac7e1ff8-5955-4eb3-aad1-7640f4e4968f.png)

**Comment by Zefau** [comment]
Arg, ja, danke für den Hinweis

**Comment by mcuiobroker** [comment]
Kannst du die Werte als --jarvis- Variablen freigeben?
![image](https://user-images.githubusercontent.com/84818934/222286843-8f208387-5e2a-4b2e-97ce-107a4f54f0a0.png)
`--jarvis-humidity`
`--jarvis-moon-in`
`--jarvis-moon-out`
`--jarvis-Pressure`
`--jarvis-rain`
`--jarvis-snowline`
`--jarvis-tempmax`
`--jarvis-tempmin`
...

**Comment by Zefau** [comment]
@bambi-arch  @mcuiobroker schaut bitte nochmal mit `v3.1.4-beta.5`

**Comment by bambi-arch** [comment]
@Zefau 
HI! Ich hab auf beta 6 getestet! Sieht sehr gut aus! Danke für das schnelle finden und umsetzen! Kannst du schon ungefähr sagen wann 3.1.4 als stable kommt?
![image](https://user-images.githubusercontent.com/104907692/223152394-56ab4bdf-f713-4e57-add2-1cd2d550f70b.png)

**Comment by bambi-arch** [comment]
@Zefau 
Ich kann leider immer noch nicht ganz nachvollziehen aus welchen DP die Werte für die Übersicht herkommen? Wenn diese von hier kommen: 
daswetter.0.NextDaysDetailed.Location_1.Day_1.Hour_1 stimmt die aktuelle Temperatur nicht! 
![image](https://user-images.githubusercontent.com/104907692/223198197-2053bec2-5393-476d-a8e4-0f5cc206fd87.png)

![Bildschirmfoto 2023-03-06 um 19 26 05](https://user-images.githubusercontent.com/104907692/223198766-3afcf05a-2693-4e13-839f-93a08a86e61b.png)

**Comment by Zefau** [comment]
Die Daten kommen direkt von der API, nicht vom Adapter. Einfach mal in die Rohdaten schauen, die der API-Link ausgibt.

**Comment by Zefau** [comment]
Dein Beispiel ist für 2 Uhr in der Nacht (`hour_value`), oder?

**Comment by mcuiobroker** [comment]
Mir ist aufgefallen, dass die Variablen nur dann Werte haben, wenn man das Modul Wetter nutzt.
Ich hätte sie gerne unabhängig davon. Also direkt nach Start. Ist das möglich?

**Comment by bambi-arch** [comment]
Hallo. 
Ich bin auf Version v3.1.8 gewechselt. Ich glaube das alte Problem besteht dort wieder und die gefühlte Temperatur ist wieder gleich der Ist-Temperatur.
![Bildschirmfoto 2023-10-22 um 17 30 39](https://github.com/Zefau/ioBroker.jarvis/assets/104907692/09bbf033-bb06-4696-9120-036a1213d906)
Danke fürs prüfen!
