### ISSUE TITLE
Docker: Jarvis 3.1.2 startet nicht

### ISSUE THREAD

**Issue by bikerbiker12** [Zefau/ioBroker.jarvis#2262]
Hallo zusammen, 

bin relativ neu in ioBroker und nicht so konform. Arbeite mich gerade ein. IoBroker ist auf einem NAS im Docker installiert. Nun benötige ich Jarvis. Hab den Adapter installiert, wenn ich die Instanz öffne, dauert es und dann kommt ein roter Screen mit Fehlermeldungen. Alle anderen Adapter laufen zuverlässig. 
Einstellungen habe ich auf Automatisch stehen lassen, die IP-Adresse stimmt, als Port wurde 8082 und als Socket 8400 gewählt, sollte auch soweit stimmen. 
Wer kann mir Tipps geben, habe schon mehrfach Neustarts (Docker, ioBroker etc.) ausgeführt, Jarvis neu aufgesetzt, aber alles ohne Erfolg

![Unbenannt](https://user-images.githubusercontent.com/126656972/222081803-aadc6627-411c-4668-850d-90347addaec2.JPG)

**Comment by Zefau** [comment]
Wenn du im Docker bist, musst du die Ports vom Docker ins Netzwerk freigeben. Hast du das gemacht?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1671

**Comment by bikerbiker12** [comment]
Ich kann im Docker selber keine Ports freigeben. Das müsste ich NAS selber machen. Die anderen Instanzen laufen ja alle. Lediglich der 8400 ist nicht freigeben!

**Comment by bikerbiker12** [comment]
Den 8400 habe ich nun im NAS eingerichtet, per TCP! Siehe da, es funktioniert. Danke dir herzlich!!!!

**Comment by roffinator3000** [comment]
Bei mir scheint das gleiche Problem aufzutreten, aber ohne Docker, iO-Broker läuft direkt auf dem raspi.

iO-Broker v6.3.5, jarvis v3.1.2

Beim Klick auf dem "Instanzlink"-Button öffnet sich ein neuer Tab mit einer "URL", die der Browser (Opera und Firefox) nicht auflösen kann (Zusammenhang zum eigentlichen Problem fraglich): https://192.168.1.9:8081/%web_protocol%://192.168.1.9:8082/jarvis/index.html#/0/&socketHost=&socketPort=8400&socketSecure=false

beim manuellen setzen der URL auf
 - 192.168.1.9:8082
 - 192.168.1.9:8082/jarvis
 - 192.168.1.9:8082/index.html
 - 192.168.1.9:8082/jarvis/index.html
 - 192.168.1.9:8082/jarvis/index.html#/0/&socketHost=&socketPort=8400&socketSecure=false
gibt es immer die Meldung der Browsers, dass die Verbindung fehlschlägt

Dabei scheint es keinen Unterschied zu machen, ob die Ports automatisch oder manuell auf 8082 & 8400 oder auf andere Werte gesetzt werden.

Laut [log (hier angehangen)](https://github.com/Zefau/ioBroker.jarvis/files/10865363/log_zu_2262-by_roffinator3000.txt) bekommt Jarvis nach dem start ein "kill" vom host, fährt runter und wieder hoch, bleit dann aber auch oben.

(192.168.1.9 ist die feste IP meines raspis, über 192.168.1.9:8081 komme ich problemlos auf die admin-Oberfläche des iO-Brokers)

**Comment by Zefau** [comment]
@roffinator3000 hast du das selbst-signierte Zertifikat (bei https) vorher angenommen? Einfach die URL direkt aufrufen und das Zertifikat annehmen, dann via jarvis aufrufen.

**Comment by roffinator3000** [comment]
https ist aktuell nicht aktiv, der Browser ignoriert das aktuell einfach.
Das Problem war, dass keine `web`-Instanz lief. Jezt, wo die aktiv ist, wird die Weiterleitung in der URL aufgelöst und ich lande auch auf Jarvis.

**Comment by mcuiobroker** [comment]
@bikerbiker12 
Kannst du kurz beschreiben, was du genau, wo gemacht hast, am Besten mit einem Bild, dann kann ich es in die Doku aufnehmen. Danke.
