### ISSUE TITLE
Jarvis Seite aus anderer Instanz wird ignoriert

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#2264]
Hi,

ich habe insgesamt 3 Jarvis Instanzen, mit unterschiedlichen Ansichten.
Eine davon rufe ich auf einem Android Tablet im FullyBrowser auf. Das hat auch bisher gut funktioniert,
Nach dem Update von 3.1,2 auf 3.1.3 geht das nun nicht mehr. 
Es wird nur noch die Ansicht der ersten Instanz angezeigt.  Dabei ist es egal, ob Fully oder Edge.
Auch wenn ich in Edge zwischen zwischen Mobil und Desktop wechsle, funktioniert es nicht.
Auf meinem Windows 11 Desktop geht alles ohne Probleme.
Wenn ich einen Downgrade auf 3.1.2 machen, ist alles wieder gut.
Leider kann ich keinen Log oder so beisteuern. Die Funktion finde ich auf dem Tablet nicht und iobroker ist da auch "leise".

**Comment by Zefau** [comment]
schau mal bitte mit `v3.1.4-beta.2`

**Comment by MarkSau** [comment]
Funktioniert wieder..Danke

**Comment by Yroge** [comment]
FuckEm 1 de mar. de 2023 12:42, MarkSau ***@***.***> escreveu:
Hi,
ich habe insgesamt 3 Jarvis Instanzen, mit unterschiedlichen Ansichten.
Eine davon rufe ich auf einem Android Tablet im FullyBrowser auf. Das hat auch bisher gut funktioniert,
Nach dem Update von 3.1,2 auf 3.1.3 geht das nun nicht mehr.
Es wird nur noch die Ansicht der ersten Instanz angezeigt.  Dabei ist es egal, ob Fully oder Edge.
Auch wenn ich in Edge zwischen zwischen Mobil und Desktop wechsle, funktioniert es nicht.
Auf meinem Windows 11 Desktop geht alles ohne Probleme.
Wenn ich einen Downgrade auf 3.1.2 machen, ist alles wieder gut.
Leider kann ich keinen Log oder so beisteuern. Die Funktion finde ich auf dem Tablet nicht und iobroker ist da auch "leise".
