### ISSUE TITLE
Iobroker automations lose performance when Jarvis is running

### ISSUE THREAD

**Issue by Nogger82** [Zefau/ioBroker.jarvis#2265]
- [ ] Which jarvis version are you running / Which version of jarvis are you using? --> V3.1.2

**Describe the bug**
When the adapter is installed and started, it doesn't take long and the automations (scripts) run heavily delayed. This can be light switching via motion detectors or queries that are carried out via Telegram. Everything is very sluggish. After uninstalling the Jarvis adapter (I did not test stopping the adapter), the system runs smoothly again.

Hardware is a Raspberry Pi 4 with 4GB Ram.

**Comment by Zefau** [comment]
Any errors or messages in the browser console?

**Comment by Nogger82** [comment]
> Any errors or messages in the browser console?

Since I uninstalled the adapter yesterday, I installed it again. When testing with telegram queries, the result is, as before, very sluggish. If I pause the JarvisAdpater, the responses from Telegram come back under a second. I can't test automations at the moment because I'm on the road.

Here is the log:

<html><body>


jarvis.0 | 2023-03-03 07:27:49.752 | info | terminating with timeout
-- | -- | -- | --
jarvis.0 | 2023-03-03 07:27:49.497 | info | terminating
jarvis.0 | 2023-03-03 07:27:48.895 | info | Terminated (NO_ERROR): Without reason
jarvis.0 | 2023-03-03 07:27:48.894 | info | terminating
jarvis.0 | 2023-03-03 07:27:48.887 | info | Got terminate signal TERMINATE_YOURSELF
jarvis.0 | 2023-03-03 07:27:48.251 | info | Adapter stopped und unloaded.
jarvis.0 | 2023-03-03 07:27:48.243 | info | Adapter is disabled => stop
jarvis.0 | 2023-03-03 07:27:25.863 | info | Client with IP 192.168.2.1 disconnected.
jarvis.0 | 2023-03-03 07:23:14.162 | info | Backup settings..
jarvis.0 | 2023-03-03 07:23:14.153 | info | Backup layout..
jarvis.0 | 2023-03-03 07:20:03.669 | info | Backup widgets..
jarvis.0 | 2023-03-03 07:20:02.081 | info | Backup devices..
jarvis.0 | 2023-03-03 07:20:00.146 | info | Backup settings..
jarvis.0 | 2023-03-03 07:20:00.137 | info | Backup widgets..
jarvis.0 | 2023-03-03 07:19:58.919 | info | Backup devices..
jarvis.0 | 2023-03-03 07:19:56.165 | info | Client with IP 192.168.2.1 connected.
jarvis.0 | 2023-03-03 07:18:53.999 | info | Backup settings..
jarvis.0 | 2023-03-03 07:18:53.997 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2023-03-03 07:18:53.691 | info | No Backup found for styles, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:53.689 | info | No Backup found for settings, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:53.687 | info | No Backup found for widgets, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:53.685 | info | No Backup found for layout, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:53.682 | info | No Backup found for devices, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:53.624 | info | starting. Version 3.1.2 in /opt/iobroker/node_modules/iobroker.jarvis, node: v16.17.0, js-controller: 4.0.24
jarvis.0 | 2023-03-03 07:18:39.119 | info | terminating with timeout
jarvis.0 | 2023-03-03 07:18:37.206 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
jarvis.0 | 2023-03-03 07:18:37.204 | info | terminating
jarvis.0 | 2023-03-03 07:18:37.203 | info | Adapter stopped und unloaded.
jarvis.0 | 2023-03-03 07:18:37.201 | info | Got terminate signal TERMINATE_YOURSELF
jarvis.0 | 2023-03-03 07:18:36.315 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2023-03-03 07:18:36.036 | info | No Backup found for styles, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:36.034 | info | No Backup found for settings, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:36.033 | info | No Backup found for widgets, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:36.031 | info | No Backup found for layout, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:36.029 | info | No Backup found for devices, thus backing up initially.
jarvis.0 | 2023-03-03 07:18:35.953 | info | starting. Version 3.1.2 in /opt/iobroker/node_modules/iobroker.jarvis, node: v16.17.0, js-controller: 4.0.24
jarvis.0 | 2023-03-03 07:18:25.537 | warn | TypeError:  Cannot read properties of undefined (reading 'msg')    at  Adapter.<anonymous>  (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:428:12)    at  Adapter.emit (node:events:513:28)    at change  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5307:34)     at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)     at processImmediate (node:internal/timers:466:21)
jarvis.0 | 2023-03-03 07:18:25.536 | warn | States  system pmessage io.messagebox.system.adapter.jarvis.0  {"command":"_backups","message":{"id":"theme"},"from":"system.adapter.admin.0","callback":{"message":{"id":"theme"},"id":46,"ack":false,"time":1677824305424},"_id":78161383}  Cannot read properties of undefined (reading 'msg')
jarvis.0 | 2023-03-03 07:18:25.534 | warn | TypeError:  Cannot read properties of undefined (reading 'msg')    at  Adapter.<anonymous>  (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:428:12)    at  Adapter.emit (node:events:513:28)    at change  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5307:34)     at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)     at processImmediate (node:internal/timers:466:21)
jarvis.0 | 2023-03-03 07:18:25.533 | warn | States  system pmessage io.messagebox.system.adapter.jarvis.0  {"command":"_backups","message":{"id":"styles"},"from":"system.adapter.admin.0","callback":{"message":{"id":"styles"},"id":45,"ack":false,"time":1677824305423},"_id":78161382}  Cannot read properties of undefined (reading 'msg')
jarvis.0 | 2023-03-03 07:18:25.532 | warn | TypeError:  Cannot read properties of undefined (reading 'msg')    at  Adapter.<anonymous>  (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:428:12)    at  Adapter.emit (node:events:513:28)    at change  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5307:34)     at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)     at processImmediate (node:internal/timers:466:21)
jarvis.0 | 2023-03-03 07:18:25.531 | warn | States  system pmessage io.messagebox.system.adapter.jarvis.0  {"command":"_backups","message":{"id":"settings"},"from":"system.adapter.admin.0","callback":{"message":{"id":"settings"},"id":44,"ack":false,"time":1677824305419},"_id":78161381}  Cannot read properties of undefined (reading 'msg')
jarvis.0 | 2023-03-03 07:18:25.530 | warn | TypeError:  Cannot read properties of undefined (reading 'msg')    at  Adapter.<anonymous>  (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:428:12)    at  Adapter.emit (node:events:513:28)    at change  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5307:34)     at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)     at processImmediate (node:internal/timers:466:21)
jarvis.0 | 2023-03-03 07:18:25.529 | warn | States  system pmessage io.messagebox.system.adapter.jarvis.0  {"command":"_backups","message":{"id":"widgets"},"from":"system.adapter.admin.0","callback":{"message":{"id":"widgets"},"id":43,"ack":false,"time":1677824305418},"_id":78161380}  Cannot read properties of undefined (reading 'msg')
jarvis.0 | 2023-03-03 07:18:25.526 | warn | TypeError:  Cannot read properties of undefined (reading 'msg')    at  Adapter.<anonymous>  (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:428:12)    at  Adapter.emit (node:events:513:28)    at change  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5307:34)     at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)     at processImmediate (node:internal/timers:466:21)
jarvis.0 | 2023-03-03 07:18:25.525 | warn | States  system pmessage io.messagebox.system.adapter.jarvis.0  {"command":"_backups","message":{"id":"layout"},"from":"system.adapter.admin.0","callback":{"message":{"id":"layout"},"id":42,"ack":false,"time":1677824305418},"_id":78161379}  Cannot read properties of undefined (reading 'msg')
jarvis.0 | 2023-03-03 07:18:25.518 | warn | TypeError:  Cannot read properties of undefined (reading 'msg')    at  Adapter.<anonymous>  (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:428:12)    at  Adapter.emit (node:events:513:28)    at change  (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5307:34)     at Immediate._onImmediate  (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37)     at processImmediate (node:internal/timers:466:21)
jarvis.0 | 2023-03-03 07:18:25.512 | warn | States  system pmessage io.messagebox.system.adapter.jarvis.0  {"command":"_backups","message":{"id":"devices"},"from":"system.adapter.admin.0","callback":{"message":{"id":"devices"},"id":41,"ack":false,"time":1677824305416},"_id":78161378}  Cannot read properties of undefined (reading 'msg')


</body>
</html>

**Comment by Zefau** [comment]
@Nogger82 please check again with `v3.1.4-beta.5`

**Comment by Nogger82** [comment]
Sorry, I installed version 3.1.4 beta 6 via git as I don't know how to explicitly select the beta 5.
However, the problem still persists in Beta 6. The delay is a good 5 seconds.
Can there be overlaps with other adapters?

**Comment by Zefau** [comment]
The challenge is the warning in the log:
> TypeError: Cannot read properties of undefined (reading 'msg') at Adapter. (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:428:12) at Adapter.emit (node:events:513:28) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5307:34) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37) at processImmediate (node:internal/timers:466:21)

Which occurs in an interval of a few milliseconds.

I do not understand the origin of it though, so it is challenging to fix it.

**Comment by Nogger82** [comment]
> The challenge is the warning in the log:
> 
> > TypeError: Cannot read properties of undefined (reading 'msg') at Adapter. (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:428:12) at Adapter.emit (node:events:513:28) at change (/opt/iobroker/node_modules/@iobroker/js-controller-adapter/build/lib/adapter/adapter.js:5307:34) at Immediate._onImmediate (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:322:37) at processImmediate (node:internal/timers:466:21)
> 
> Which occurs in an interval of a few milliseconds.
> 
> I do not understand the origin of it though, so it is challenging to fix it.

Can or should i do something to help fixing that?

**Comment by MarkSau** [comment]
I see the same behavior. If the Jarvis instances are running the CPU load increases by 15-20%, then my scripts also run delayed. For example, the bell message (pushover, Alexa) comes 5-10sec later. If I stop Jarvis, everything is fine.

**Comment by Zefau** [comment]
any improvement with `v3.1.4-beta.7`?

**Comment by Nogger82** [comment]
I´ve tried with my Telegram Routines and with Jarvis Instance active, the performance is still droping. May not so much as before, but it does. It was only a short test. I´ll do a longer Test on Weekend.

**Comment by Nogger82** [comment]
i´m now on the v3.1.9-beta.2 bur got still performance issues. My Telegram routines are between 2-3 seconds. When Jarvis ist deactivated it´s much faster. Maybe something is wrong on my System or does anyone else has the same problems?

**Comment by bambi-arch** [comment]
Hallo, ich hab das gleiche Problem seit 3.1.2. Aktuell habe ich 3.1.8 drauf und ich meine das es etwas besser geworden ist. Jarvis hat bei mir 10 Minuten nach einem Neustart 150 MB RAM. Nach ein paar Stunden liegt es zwischen 300 und 500 RAM.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.6` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.6` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@Nogger82
