### ISSUE TITLE
Homematic Rollladenaktor Broll-2 undefinierter Datenpunkt 

### ISSUE THREAD

**Issue by Matze2208** [Zefau/ioBroker.jarvis#2266]
Hi
Erstmal vielen Dank für diesen tollen Adapter auf eine Pro Version wird es hinauslaufen, aber momentan hab ich bei etwas wichtigem noch Probleme.

Ich habe Die Homematic RolladenAktoren   "HmIP-BROLL-2 eingebaut aber bekomme diese nicht importiert (RollladenGästeBad)

![JArvis datenpunkte](https://user-images.githubusercontent.com/126828899/222676974-82c28719-f6f5-4fe8-b3c8-3a286f9dc244.png)

Ich habe jetzt von der Version  3.1.2 auf die Beta 3.1.4-beta.4 gewechselt was leider auch nicht zum Erfolg führte.

![jarvis version](https://user-images.githubusercontent.com/126828899/222678644-8be9bb92-8955-4d1e-beda-415919e2777e.png)

Im iobroker wird eigentlich alles angezeigt 

![Rollladen iobroker](https://user-images.githubusercontent.com/126828899/222677725-47d0e555-7736-401b-91d7-84f35b68f6a7.png)

Die Datenpunkte 

![Datenpunkte 1iobroker](https://user-images.githubusercontent.com/126828899/222677960-7228df71-dca2-421a-a79a-509b38fb13df.png)

![datenpunkte 1-2 io](https://user-images.githubusercontent.com/126828899/222677994-f981e9eb-f236-4b11-8876-043b97d726af.png)

![datenpunkte 3-4](https://user-images.githubusercontent.com/126828899/222678015-ef7de4df-f61a-4642-bb6c-c8572de80d12.png)

wenn ich den Rollladen per Handy bediene sieht man wie sich im iobroker das Level von 100%auf 0% ändert.

vielleicht eine Idee?

Besten Dank für deine ganze Arbeit 

gruß Matze

**Comment by Zefau** [comment]
@Matze2208 mit `v3.1.4-beta.5` nun verfügbar

**Comment by Matze2208** [comment]
Vielen lieben dank läuft super Pro ist gekauft ;-) 😉
