### ISSUE TITLE
Skripte werden gelöscht

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2267]
Hallo, 
habe die Pro Version. und die letzte 3.1.4 beta 4 . Jarvis läuft auf zwei Tabletts im Haus dauerhaft auf dem Handy gelegentlich und bearbeiten tue ich es vom Rechner

Ich habe schon seit einigen Versionen (kann auch sein dass es schon immer so ist) das Problem dass wenn ich in den Edit Modus gehe und gleich wieder zurück gehe über Speichern und zurück alles unter Skripte gelöscht wird .
ich habe dort nur das Time Skript von hier laufen. https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/scripts-3.1.x-pro/tab/clocknearbell
Dieses lässt sich immer reproduzieren. Ich kann Jarvis nicht bearbeiten ohne dass das Skript gelöscht wird.

Grüße

**Comment by mcuiobroker** [comment]
Nutze mal die Importvariante.
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/scripts-3.1.x-pro#import-variante

**Comment by mcuiobroker** [comment]
@zefau wenn du so eine Zeit-Anzeige selbst integrieren kannst / möchtest, gerne machen.

**Comment by intruder7777** [comment]
@mcuiobroker in dem Link steht auch das man den HTML Anteil in den Scripte Tab einbringen muss. Nützt mir aber nichts wenn die dort jedesmal wieder gelöscht werden wenn ich Jarvis editieren will. Un dich habe aktuell nur dieses eine Uhrenscript am laufen

**Comment by mcuiobroker** [comment]
Zeig doch mal wie du es eingetragen hast. Als Bild

**Comment by mcuiobroker** [comment]
Hab es jetzt selbst nochmal mit normaler Scriptversion gemacht und kann es bestätigen. Das Script wird gelöscht.
![image](https://user-images.githubusercontent.com/84818934/222930341-2d6f365d-f0d1-49f1-8ad0-8c10660f09db.png)

**Comment by mcuiobroker** [comment]
@intruder7777 Du könntest die import-Version für die Scripte nutzen, bis der Fehler behoben ist.

**Comment by Zefau** [comment]
`v3.1.4-beta.6`

**Comment by mcuiobroker** [comment]
Funktioniert wieder. Danke.

**Comment by intruder7777** [comment]
Danke, Fehler scheint behoben. Wundere mich nur dass es nur mir so aufgefallen ist. Dabei ist die Scripte Nutzung doch recht interessant
