### ISSUE TITLE
Hiddenstate / ignoredstates

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#227]
How to use this options and whats results happens exactly?

![image](https://user-images.githubusercontent.com/25475385/96915831-091e3280-14a7-11eb-8af9-be53233f0ed5.png)

**Comment by Zefau** [comment]
`hiddenStates` will not be shown in device popup.
`ignoredStates` will be ignored. This might be useful if a state has been defined but is (temporarily) not necessary. Same as deactivation basically.

This options will most likely be changed with https://github.com/Zefau/ioBroker.jarvis/issues/40

**Comment by duczz** [comment]
Alles klar, hinterleg ich die OID wirds aber trotzdem im Popup angezeigt.

**Comment by Zefau** [comment]
Was meinst du mit OID? Du musst den Datenpunkt hinterlegen.

**Comment by Zefau** [comment]
This will be removed in the course of https://github.com/Zefau/ioBroker.jarvis/issues/40 and added directly to the state itself.

**Comment by duczz** [comment]
I use this for example "0_userdata.0.Systeminfos.ioBrokerPi.Raspberry_Updates" same ID as in datapoint and it will show in the popup

**Comment by Zefau** [comment]
you have to use the state key defined in jarvis

**Comment by Zefau** [comment]
Changed in `v1.1.0-beta.54` now. Removed `ignoredStates` and changed `hiddenStates` to a Switch for each state.
