### ISSUE TITLE
Geräteeinstellungen I JSON Editor I Öffnet sehr zeitverzögert

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#2270]
Hallo Ich hab der Version v3.1.2.

Beim Bearbeiten der Geräteeinstellung beim Klicken auf den Button für den Json-Editor dauert es bis zu 20 Sekunden bis dieser öffnet. Auch wenn das Feld leer ist?! An meinen System kann es eigentlich nicht liegen, es langweilt sich. Alle anderen Jarvis-Funktionen sind in der Geschwindigkeit wie immer. Danke im Voraus!
![Bildschirmfoto 2023-03-06 um 19 43 05](https://user-images.githubusercontent.com/104907692/223203153-dedf1797-79cc-4869-8ff3-bc17d6eb7bbb.png)

**Comment by mcuiobroker** [comment]
Versuch mal ein Upload.
console -> `iob upload jarvis`

**Comment by mcuiobroker** [comment]
Auf der `console`, wo du sonst die ioBroker-Befehle eingibst.

**Comment by Zefau** [comment]
Mit welchem Browser(n) hast du das Problem?

**Comment by tschortschde** [comment]
Ich habe das Problem im Edge

**Comment by mcuiobroker** [comment]
mögliche Ansatzpunkte wären noch:
- web-Instanz neu starten
- Browser-Cache löschen
- jarvis neu starten

**Comment by tschortschde** [comment]
Danke...
Bei mir dauert es nun ca. 5 Sekunden. 
ist das normal?

**Comment by mcuiobroker** [comment]
Nein. 0.2 s ist normal. 
Wie lange hat es vorher gedauert und was hast du gemacht. 
F12 Meldungen im Browser Log?

**Comment by tschortschde** [comment]
ich meine mehr als 5 sekunden...
ich habe: 
web-Instanz neu gestartet
Browser-Cache gelöscht
jarvis neu gestartet

Anbei die Browser Log (ist es das was was du wolltest?)
![Screenshot 2023-06-19 075142](https://github.com/Zefau/ioBroker.jarvis/assets/11274233/71c1b856-5be6-4f67-b3e9-c8fa2ea0c8ff)

**Comment by mcuiobroker** [comment]
Browser-Log ist unauffällig, du hattest aber vorher versucht den Editor zuöffnen?
Web-Version?

**Comment by tschortschde** [comment]
Web-Version: 5.4.1
Die Lizenz ist nur in der 1. Instanz eingetragen.
Die 2. Instanz (=blanko) habe ich nur zum testen angelegt um festzustellen, ob es an der 1. Instanz liegt...

Im Feld Notifications steht: 
![Screenshot 2023-06-19 082928](https://github.com/Zefau/ioBroker.jarvis/assets/11274233/c7690119-2ca4-4722-bad5-ce7c41b85561)

**Comment by mcuiobroker** [comment]
Vielleicht liegt es daran?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9d89754b-9b56-4faa-b7f3-d5faa6555229)

**Comment by mcuiobroker** [comment]
nodejs muss auf Version 16 sein. siehe Forum.

**Comment by tschortschde** [comment]
Okay habe ich gemacht und jarvis auf 3.1.8 aktualisiert
habe den Eindruck das jarvis deutlich schneller startet.
**Allerdings dauert der Aufruf des json Popup immer noch 5 Sekunden ;-((**

**Comment by tschortschde** [comment]
> Okay habe ich gemacht und jarvis auf 3.1.8 aktualisiert habe den Eindruck das jarvis deutlich schneller startet. **Allerdings dauert der Aufruf des json Popup immer noch 5 Sekunden ;-((**

haben andere auch noch das Problem?

**Comment by Rookiestyle** [comment]
> haben andere auch noch das Problem?

Ist bei mir auch so in Edge, Chrome und Opera.
In Firefox wird das Popup sofort angezeigt.

Jarvis ist bei mir ebenfalls in Version 3.1.8 installiert, war in früheren Versionen auch schon so.

**Comment by tschortschde** [comment]
Mit Version v3.1.9-beta.2 öffnet sich das  Popup sofort ;-)
Vielen Dank an den Entwickler !!!

**Comment by Zefau** [comment]
@bambi-arch ich mach hier zu. Sofern das Problem mit v3.2 noch besteht, gerne wieder öffnen
