### ISSUE TITLE
v3.1.4-beta.6 Vollbild erlauben funktioniert nicht auf dem Handy

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2275]
![image](https://user-images.githubusercontent.com/84818934/224070590-138a5959-91a5-4f51-87c7-bcdcfe0f50bf.png)

Klicken / Drücken auf das Dreieck funktioniert nicht und auch der Doppelklick /-tipp geht nicht.
Komischerweise, wenn man direkt nach dem Doppelklick /-tipp die Ausrichtung ändert (Portrait <->Landscape) wird es umgesetzt.
Aber nur einmal.

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.1.4-beta.8`

**Comment by mcuiobroker** [comment]
Leider nein.
Auf dem Handy nur einmal. Auch Doppelklick nach dem ersten Mal nicht mehr.

**Comment by tschortschde** [comment]
Seltsam !!?
Bei mir funktioniert der Vollbildmodus auf dem Handy immer, obwohl ich diesen konsequent in allen Widgets ausgeschalten habe.
Gibt es hierzu schon Neuigkeiten?

**Comment by mcuiobroker** [comment]
Nein, keine Neuigkeiten.  Dazu gibt es speziell noch ein anderen Issue.

**Comment by tschortschde** [comment]
Wo finde ich dieses?

**Comment by Zefau** [comment]
Weiterverfolgung via https://github.com/Zefau/ioBroker.jarvis/issues/2379
