### ISSUE TITLE
Button label are vice versa

### ISSUE THREAD

**Issue by Draygv2** [Zefau/ioBroker.jarvis#2276]
Hi, first of all your vis is amazing many thanks for that.

On the ButtonGroupAction the labels are vice versa. So I have to change them every time. 
![image](https://user-images.githubusercontent.com/62559741/224535575-a1d10bf0-c246-4d7d-8517-797bd6b371ae.png)

I use the Version 3.1.3

**Comment by Zefau** [comment]
What do you mean? ButtonGroupAction is always left off and right on. What specifically is incorrect?

**Comment by Zefau** [comment]
@Draygv2
