### ISSUE TITLE
v3.1.4-beta.6 Quick Jumper Es fehlen icons

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2277]
![image](https://user-images.githubusercontent.com/84818934/224551608-450d61d7-89c0-4c81-9d36-c5a84f9f5926.png)
Auf dem Handy und auf dem PC.

**Comment by Zefau** [comment]
Bitte Angabe welche Icons betroffen sind.

**Comment by mcuiobroker** [comment]
1. shield-home
2. music
3. motion-sensor
4. image
5. train
6. file-document
7. application
8. gauge

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.17` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.17` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Leider nein.
![image](https://user-images.githubusercontent.com/84818934/235327774-88121d41-8a86-4f36-b1fd-a0af0f41e56d.png)
![image](https://user-images.githubusercontent.com/84818934/235327800-9de13f23-f854-413a-b06b-f6b8fe272739.png)

**Comment by Zefau** [comment]
Habe jetzt auf Basis deiner Liste (https://github.com/Zefau/ioBroker.jarvis/issues/2277#issuecomment-1510411437) die Icons drin:

![grafik](https://user-images.githubusercontent.com/14368811/235366897-3981f307-917c-458f-a0db-f1e34305524e.png)

Das mit TV und dem doppelten `mdi-` behebe ich. 

Bei `energy` bin ich unschlüssig, warum es nicht geht. Laut https://pictogrammers.com/library/mdi/ kein Material Design Icon?

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.18` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.18` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
