### ISSUE TITLE
buttons konfigutrieren

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#228]
Hi. Gibt es eine möglichkeit buttons zu konfigurieren?
ich benötige unter anderem auch buttons, welche anstatt true auch false senden
oder auch buttons, welche befehle per http request starten.

Und diese buttons bitte auch frei beschriftbar. aktuell habe ich bei jarvis überall die "anschalten" buttons im einsatz
auf meiner node-red visu sind die buttons direkt beschriftet, z.b. mit "Messvorgang starten"

**Comment by Zefau** [comment]
>  ich benötige unter anderem auch buttons, welche anstatt true auch false senden
Geht mit der aktuellen beta in der Widget Konfiguration.

>  oder auch buttons, welche befehle per http request starten.
Hierzu einen Button in ioBroker erstellen, der den Request schickt. So würdest du es in vis auch machen müssen meine ich.

> Und diese buttons bitte auch frei beschriftbar. aktuell habe ich bei jarvis überall die "anschalten" buttons im einsatz
Geht mit der aktuellen beta in der Widget Konfiguration.

**Comment by Zefau** [comment]
Siehe auch `Datenpunkt Eigenschaften`: https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#datenpunkt-eigenschaften
