### ISSUE TITLE
Datenpunkt Stil wird nicht richtig umgesetzt v3.1.4-beta.6

### ISSUE THREAD

**Issue by Draygv2** [Zefau/ioBroker.jarvis#2281]
Wenn ich den Stil anpasse wird immer etwas anderes Angezeigt als beschrieben.

![image](https://user-images.githubusercontent.com/62559741/225133006-8c45e249-a1aa-4c06-a6d0-3dc407426880.png)
Gemass Beschreibung https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v2/beispiele/geraete-einstellungen/datenpunkt-stil jarvis nimmt immer den ersten richtigen Wert.

Resultat grün anstelle von rot
![image](https://user-images.githubusercontent.com/62559741/225133292-15d679dc-3e77-4dbb-a2ef-09d995ef9b0d.png)

**Comment by mcuiobroker** [comment]
Ist ja immer alles größer 0 oder?
Also immer <= nutzen. 
Außerdem nicht die Doku von v2 für v3 nehmen, außer es wird angezeigt..

**Comment by Draygv2** [comment]
Alles klar vielen Dank.
