### ISSUE TITLE
v3.1.3 : DropDownAction / Sortierung bestimmte Reihenfolge

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2284]
Für eine Zeitauswahl in einem DropDown ist in der Anzeigevariante  folgendes eingetragen:

```
{
  "1 Tag": "1 Tag",
  "2 Tage": "2 Tage",
  "Heute": "Heute",
  "_sort": [ 3, 1, 2 ]
}
```

"Heute" soll ganz oben stehen.
Ergebnis:

![Unbenannt](https://user-images.githubusercontent.com/77005685/225643283-aa2c9db6-f181-4a22-b992-c5283b6d0876.jpg)

[Referenz #1141](https://github.com/Zefau/ioBroker.jarvis/issues/1141)

**Comment by mcuiobroker** [comment]
@Zefau Gibt man zusätzlich order an, wird auch der "order"-Wert mit angezeigt.
![image](https://user-images.githubusercontent.com/84818934/225711411-ba28f8d0-8005-4a8e-8eb3-92309a15ab36.png)

**Comment by Zefau** [comment]
Korrekt wäre: `{"1 Tag":"1 Tag","2 Tage":"2 Tage","Heute":"Heute","_sort":[2,3,1]}`

Ich habe die Anleitung aktualisiert, siehe: https://github.com/Zefau/ioBroker.jarvis/issues/1141#issuecomment-1412625251:
> [ .. , .. ] -> bestimmte Reihenfolge: die Position in der Liste (im Array) entspricht der ursprünglichen Position im JSON. Der angegebenen Zahlenwert ist die Zielposition. Beispielsweise sort [ 1, 3, 2 ] das erste Element an 1, das zweite Element an 3 und das dritte Element an 2.

**Comment by Zefau** [comment]
@mcuiobroker nicht `order`, sondern `_order`.

**Comment by mcuiobroker** [comment]
Steht so in der Doku.
![image](https://user-images.githubusercontent.com/84818934/234964308-c58d4dd8-90b4-4e5d-8bdb-07a41ded5bbf.png)

**Comment by Zefau** [comment]
Jo, das stimmt. Ich kann mal schauen, ob sich das schnell umbauen lässt.

Bzgl. `order` zeig mal deine Konfiguration.

**Comment by Zefau** [comment]
Also mit 
![image](https://user-images.githubusercontent.com/14368811/234970568-f48a6f71-f33c-443a-9e6e-b82e9190773f.png)
erhalte ich
![image](https://user-images.githubusercontent.com/14368811/234970698-928c8308-285b-451d-b5af-7fc8f7bcdc8d.png)

Also kein `up` drin wie in https://github.com/Zefau/ioBroker.jarvis/issues/2284#issuecomment-1472461530

**Comment by mcuiobroker** [comment]
Ja das hattest du schon irgendwann korrigiert. kurz nach v3.1.3 alpha.17?

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.16` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.16` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Sieht gut aus, ich mach mal dicht
