### ISSUE TITLE
v3.1.4-beta.6 StateList Layout Anzeige ohne ActionElement aus dem Gerät

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2285]
Füge ich eine StateList hinzu und dort einen DP mit ActionElement, wird das Element nicht gegraut im Layout dargestellt.
![image](https://user-images.githubusercontent.com/84818934/225730785-f925e541-557d-4537-bbd5-f28d7efbcae2.png)

Es sollte jetzt `ButtonAction` im `TriggerElement` grau stehen?
![image](https://user-images.githubusercontent.com/84818934/225718694-88a38682-87b2-4505-ac22-e3cfb1642986.png)

**Comment by Zefau** [comment]
Erscheint dort nur, wenn bisher kein Eintrag drin war, der gelöscht wurde.

Wenn du das Element neu im Layout config hinzufügst sollte es ausgegraut angezeigt werden.

**Comment by mcuiobroker** [comment]
Es wird eben nicht ausgegraut angezeigt.

**Comment by Zefau** [comment]
@mcuiobroker ist das hier mit v3.2 noch aktuell?

**Comment by mcuiobroker** [comment]
Nein.
