### ISSUE TITLE
3.1.2 - HistoryGraph - falsche Darstellung bei Wechsel zwischen "0" und "1"

### ISSUE THREAD

**Issue by somansch** [Zefau/ioBroker.jarvis#2286]
Ich möchte den Zustand des Heizungsventils darstellen (true bzw. 1 = offen, false bzw. 0 = geschlossen). Hierbei ist mir aufgefallen, dass die Darstellung falsch ist. 

22:51 - Ventil geschlossen:
![image](https://user-images.githubusercontent.com/47367267/225754794-d895a887-a0a7-4375-b251-3dc7fdeae39f.png)
22:57 - Ventil offen:
![image](https://user-images.githubusercontent.com/47367267/225754873-0152edd2-46b9-4724-a280-208ecfb572fa.png)

Im geschlossenen Zustand ("0") darf die Linie nicht auf "1" gehen. Im eChart Modul von ioBroker wird es korrekt dargestellt:
![image](https://user-images.githubusercontent.com/47367267/225755231-64c3add5-8d4b-4ab7-8517-be828f27df8b.png)

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/module/historygraph/series-parameter-v3.1.x#boolean-werte-aus-iobroker-darstellen

**Comment by somansch** [comment]
Danke

**Comment by Zefau** [comment]
same issue https://github.com/Zefau/ioBroker.jarvis/issues/2296

**Comment by Zefau** [comment]
Der Bug ist berechtigt. Der Hinweis bzgl. https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/module/historygraph/series-parameter-v3.1.x#boolean-werte-aus-iobroker-darstellen ist ein Workaround.

Wird behoben und dann sollte es ohne Workaround funktionieren.

**Comment by Zefau** [comment]
bitte schau nochmal mit `v3.1.4-beta.7`

**Comment by Zefau** [comment]
@somansch
