### ISSUE TITLE
Forward-Slashes in URL gehen in JSONTable verloren

### ISSUE THREAD

**Issue by Zamuul** [Zefau/ioBroker.jarvis#2287]
jarvis Version v3.1.2

Ich versuche Momentan eine Tabelle mit Links aufzubauen. 
Ich habe ihn Formatiert, wie am Anfang dieser Seite beschrieben wird: 
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/module/jsontable

Allgemein wird ein JSON erstellt, das mehrere Linkeinträge abbildet:
[{"name":"<a href\"http://192.168.178.83:8082/set//bring.0.5fc8fa4e-a94c-73ddfffdb54f.saveItem?value=Test3\" target=\"_blank\">Test3</a>"},
{"name":"<a href\"http://192.168.178.83:8082/set//bring.0.5fc8fa4e-a94c-73ddfffdb54f.saveItem?value=Test2\" target=\"_blank\">Test2</a>"},
{"name":"<a href\"http://192.168.178.83:8082/set//bring.0.5fc8fa4e-a94c-73ddfffdb54f.saveItem?value=Test1\" target=\"_blank\">Test1</a>"}]

Das Schreiben in die Tabelle funktioniert auch Problemlos. Er übernimmt aber leider die Slashes einfach nicht. ich habe verschiedene Möglichkeiten ausprobiert.

Ich habe auch versucht das Ganze erst in der Modul Konfig zu ersetzen:
![image](https://user-images.githubusercontent.com/122809560/226057283-d183de6c-624b-4a21-93c6-878617027839.png)

Funktioniert ebenfalls nicht.

Am Ende kommt auf der Seite immer das hier raus:
<a href"http: 192.168.178.83:8082 set bring.0.5fc8fa4e-a94c-73ddfffdb54f.saveitem?value="Test2" "target="_blank">Test2</a>

Ich habe glaube ich inzwischen Alle Escape Zeichen durchprobiert.

Grüße
Johannes

**Comment by mcuiobroker** [comment]
Wenn, dann das Format beachten.
```
[{"name":"<a href=\"http://192.168.178.83:8082/set//bring.0.5fc8fa4e-a94c-73ddfffdb54f.saveItem?value=Test3\" target=\"_blank\">Test3</a>"},
{"name":"<a href=\"http://192.168.178.83:8082/set//bring.0.5fc8fa4e-a94c-73ddfffdb54f.saveItem?value=Test2\" target=\"_blank\">Test2</a>"},
{"name":"<a href=\"http://192.168.178.83:8082/set//bring.0.5fc8fa4e-a94c-73ddfffdb54f.saveItem?value=Test1\" target=\"_blank\">Test1</a>"}]
```

![image](https://user-images.githubusercontent.com/84818934/226060020-ee938b4d-b88f-419c-a9b3-14ac336ac29a.png)

**Comment by Zamuul** [comment]
Wo ich deine Vermutung lese, fällt mir noch ein Fehler auf... Es ist nicht saveItem, sondern removeItem. Es geht darum, sich die Liste anzeigen zu lassen, und mit einem Klick auf ein Item dieses runterwerfen zu können.

Ich Versuche ja das Format zu beachten, aber das ist ja das Problem. Im Datenpunkt sieht das noch ok aus, aber sobald das Widget dargestellt wird, löscht er die / einfach aus der URL.

**Comment by mcuiobroker** [comment]
Lösch mal die Einstellungen im Format.
![image](https://user-images.githubusercontent.com/84818934/226101245-23cc3607-6166-47f6-82bf-c257425702c3.png)
Wofür soll das sein?
![image](https://user-images.githubusercontent.com/84818934/226101256-c10338fe-a519-4637-8e97-0ce6ed8b012c.png)
Zeig mal Deine? Wo siehst du, dass er es löscht?

**Comment by mcuiobroker** [comment]
![bringRemoveItem Beispiel](https://user-images.githubusercontent.com/84818934/226104935-122d99ed-8367-4ca8-9895-1a1a06e2af4d.gif)

**Comment by Zefau** [comment]
Die `/` mit `\` escapen, also `\/`. Am besten Mal nach escapen googeln.

**Comment by Zamuul** [comment]
Wow... Das ist mal ein Support. Vielen Dank, ich habe es grade so eingerichtet, wie im gitbook beschrieben. Funktioniert einwandfrei, vielen Dank...

Grüße

**Comment by mcuiobroker** [comment]
Mit der neuen Version kann man auch eine Oldtems Liste (jsonTable) erstellen und von dort aus "alte" Items mit Specification zurückholen.

**Comment by mcuiobroker** [comment]
Fehlt noch was?
Kann der `bug`-Issue dann zu?

**Comment by Zamuul** [comment]
Vielen Dank, ja, kann zu.
