### ISSUE TITLE
Berücksichtigung der Benutzerrechte

### ISSUE THREAD

**Issue by IobUser** [Zefau/ioBroker.jarvis#2288]
Ich verwende das PRO-Feature 'Sicherheitseinstellungen>Zugriff Seiten: ioBroker User Management'
Der Zugriff auf die States erfolgt aber trotzdem immer als Benutzer Admin.
Für mich (Haus mit drei Familien) ist die Visualisierung nur brauchbar, wenn die gesetzten Rechte auf die States berücksichtigt werden.
Auch die Änderbarkeit von States sollte davon abhängig sein, ob der Benutzer das Recht dafür hat (nicht dass erst beim Ändern ein Fehler auftritt)
Toll wäre es in dem Zusammenhang, wenn die Sichtbarkeit von Objekten im Jarvis auch abhängig von Benutzerrechten gesetzt werden kann.

**Comment by Zefau** [comment]
@IobUser seit v3.1.x wird der eingeloggte Benutzer genutzt. Passt das so?

**Comment by IobUser** [comment]
Ich verwende derzeit die Version 3.1.2 - und da werden die States noch vom admin und nicht vom angemeldeten Benutzer gesetzt.
Bitte um Info, ab welcher Version das geändert ist.
Ich werde dann auf diese Version aktualisieren und Feedback geben.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.16` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.16` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
Neue Adapter-Konfiguration:



![Image](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/3a060dea-9211-45f4-9ed0-90fe171f316e)

**Comment by Zefau** [comment]
@mcuiobroker ich mein das Issue hier (auch bzgl. https://github.com/Zefau/ioBroker.jarvis/issues/2669#issuecomment-2181534776).

Fix kommt.

**Comment by mcuiobroker** [comment]
Jetzt kommt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/2d592c00-f7a9-40ca-8e91-6c4b3b014194)

**Comment by mcuiobroker** [comment]
Jetzt bin ich drin, aber
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/d97c3390-c5f3-4e5a-b895-54dd8216e186)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.19` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.19` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Sieht erstmal gut aus. Wie kann man jetzt mit Benutzerrechten ein Gerät oder Widget einschränken?

**Comment by Zefau** [comment]
Die Benutzerrechte greifen wie bekannt auf der Seite oder der Konfiguration. Der Unterschied ist, dass es nun nicht mehr in jarvis direkt, sondern in ioBroker gepflegt wird.

Dadurch fällt die komplette Abhängigkeit zum Web-Adapter weg, über den vorher die Authentifizierung lief. Dadurch sollte nun Reverse-Proxy auf dem jarvis Port uneingeschränkt funktionieren. Außerdem ist dieses Issue hier hoffentlich gelöst - also, dass die Benutzerrechte korrekt beim `setState` greifen, wenn mit unterschiedlichen Benutzer-Rechten gearbeitet wird.

**Comment by mcuiobroker** [comment]
Man kann trotz Benutzer Einschränkung den Switch schalten im Frontend, im ioBroker wird nicht geschaltet.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.55` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.55` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by IobUser** [comment]
Test mit der Version 3.2.0-rc.12:
- die States werden mit dem angemeldeten Benutzer verändert und nicht mehr als Admin > OK
- aber auch ohne Recht zum Ändern des States kann geschaltet werden und es wird dann ein Fehler angezeigt
![image](https://github.com/user-attachments/assets/256555a2-e94c-4ca7-885e-bcb4815b3682)
Hier sollte das Control deaktiviert angezeigt werden
