### ISSUE TITLE
Verzeichnis bei Tahoma wird als Datenpunkt angezeigt

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#2289]
Seit dem letzten Sommer muss etwas passiert sein! In meinem eingerichteten Geräten sind die Datenpunkte für die Anzeige jetzt leer. Nur DP-Trigger steht die Verknüpfung noch drin.
![Bildschirmfoto 2023-03-18 um 14 42 19](https://user-images.githubusercontent.com/104907692/226109845-7f2c868c-e265-4dfc-8508-3ea7fede2060.png)
Dann wollte ich diesen wieder einrichten. Jedoch wird im Auswahl-Dialog wird der Ordner als Datenpunkt angezeigt, d.h. die darunterliegenden DP werden nicht angezeigt. 
![Bildschirmfoto 2023-03-18 um 14 34 19](https://user-images.githubusercontent.com/104907692/226109898-86340d02-bf32-4646-9346-371dd05223bd.png)
![Bildschirmfoto 2023-03-18 um 14 34 51](https://user-images.githubusercontent.com/104907692/226109899-ef0c4d7b-1100-413c-aaad-7546b919263f.png)

Ich hab auch schon die Verzeichnisstruktur gelöscht und Tahoma und Jarvis neu gestartet, ohne Erfolg.

**Comment by mcuiobroker** [comment]
Du kannst den DP von ioBroker direkt kopieren und einfügen.
![image](https://user-images.githubusercontent.com/84818934/226183530-efabeb41-74d3-44b1-af5f-b1df57516071.png)
Einfügen -> STRG+v in jarvis

**Comment by Zefau** [comment]
Ist ein Fehler im Tahoma Adapter. Die Einträge sind klar als "state" angelegt (vgl. deinem Screenshot) und werden daher auch so in jarvis behandelt.
