### ISSUE TITLE
schieberegler konfigurieren

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#229]
Bei Rollos ist ein schieberegler 0-100% eingestellt
bei Heizung 0-35°C jeweils mit Schrittweite 1

ich würde gerne, vorallem bei der Heizung, den unteren und oberen Endwert einstellen können (z.b. 15-25°C) und die schrittweite mit 1° ist mir zu viel. ich würde es gerne auf 0,5 oder 0,1 grad einstellen.

aktuell ist meine sollraumtemperatur nämlich auf 22,5°C

**Comment by Zefau** [comment]
Geht mit der aktuellen beta in der Widget Konfiguration.

**Comment by Timmes123** [comment]
oh sorry. ich war noch nicht auf dem aktuellen stand :-) habs grad gesehen, entschuldige

**Comment by Zefau** [comment]
no problemo

**Comment by Zefau** [comment]
Siehe auch `Datenpunkt Eigenschaften`: https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#datenpunkt-eigenschaften

**Comment by blackship1** [comment]
Hallo, kann mir jemand sagen wo ich nachlesen kann wie ich die Steps kleiner als 1 (z.B 0.5 oder 0.1)einstellen kann, kanns echt ncht finden

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/geraet/body-element/levelbody

**Comment by blackship1** [comment]
super, vielen Dank
