### ISSUE TITLE
Nach Update von 3.1.2 zu 3.1.3 xhr poll error

### ISSUE THREAD

**Issue by derBruti** [Zefau/ioBroker.jarvis#2292]
Hallo zusammen, 

nachdem ich heute das Update auf 3.1.3 durchgeführt habe, bekomm ich folgenden Fehler: 

<img width="508" alt="image" src="https://user-images.githubusercontent.com/128311730/226189821-92d9ccaa-0618-4fcf-a162-3658eaa99293.png">

Hab auch schon verschiedene Port Einstellungen vorgenommen. Leider keine Besserung. 
Hier die Jarvis Config: 
<img width="707" alt="image" src="https://user-images.githubusercontent.com/128311730/226190021-95ca08f1-a158-44b3-9a3b-068c594ab35d.png">
hier die Web Config:
<img width="914" alt="image" src="https://user-images.githubusercontent.com/128311730/226190084-a18620a2-fcdf-477f-9bd0-8486f9f6bc5f.png">

Schon mal vorab danke für eure Hilfe! 

Thomas

**Comment by mcuiobroker** [comment]
`iob upload jarvis` auf der console ausführen.

**Comment by derBruti** [comment]
Das mit iob upload jarvis. Hab ich schon probiert, das hat leider nix gebracht. 
Das mit der IP probier ich später.

**Comment by derBruti** [comment]
Also, mit IP Adresse klappt es jetzt wieder. 
Muss ich was umstellen, damit es wieder via Hostnamen geht? 

Viele Grüße und danke

**Comment by mcuiobroker** [comment]
evtl den Hostnamen auch in die WhiteList eintragen?

**Comment by derBruti** [comment]
das hat leider nicht geklappt.

**Comment by mcuiobroker** [comment]
Neueste Version v3.1.4-beta.6 installieren?

**Comment by derBruti** [comment]
> Neueste Version v3.1.4-beta.6 installieren?
**Hab ich jetzt gemacht, leider keine Besserung.** 

> Welche Adresse nutzt du um jarvis aufzurufen?
> `http://192.168.178.xxx:8083/jarvis/index.html#/`
**mit dieser gehts**

> `http://pi-smarthome:8083/jarvis/index.html#/`
**mit dieser gehts nicht.** 

**Was ich jetzt noch rausgefunden habe, mit Firefox geht der Zugriff via Hostname,
mit Chrome/Edge nicht...**

**Comment by derBruti** [comment]
> 

Danke Dir trotzdem. Ich komme jetzt immerhin via IP-Adresse dran.

**Comment by Zefau** [comment]
@derBruti ich mach hier mal zu. Bitte auf v3.2 gehen, sofern der Fehler noch besteht.
