### ISSUE TITLE
Browseransicht wird teilweise nicht aktualisiert

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#2293]
Das Problem tritt teilweise auf - nicht immer. Ich konnte noch kein Muster oder Abhängigkeiten erkennen. Ich nutze Chrom-Kioskmode (Nachtaktualisierung ist an). Aber auch bei Edge hab ich es schon beobachtet. Raspi auf aktuellsten Stand. Jarvis v3.1.2 I Node 16.19.1 I NPM 4.0.24 I Mulithost im Einsatz (alles gleich)
Bei einem offenen Browser werden Werte der Datenpunkte nicht aktualisiert z.B. offenes/geschlossenes Fenster. Der Datenpunkt ist mit aktuellen Wert im ioBroker/Adapter.
Wenn ich den Tab wechsle und wieder zurück gehe, sind die Werte wieder aktuell.
Danke für die Prüfung.

**Comment by Bernd9000** [comment]
Hab ich Heute Morgen auch einmal gehabt.
Ein secondary State wurde nicht mehr aktualisiert.
jarvis Seite war ca. 1 Stunde offen, F5 und der Wert wird wieder aktualisiert.
Werde ich mal weiter beobachten....

Windows / Firefox
jarvis v3.1.3
Node.js  v18.15.0
NPM  9.5.0
js-controller 4.0.24

**Comment by bambi-arch** [comment]
Hallo, ich hab ein interessante Beobachtung gemacht. 
Es kommt immer wieder vor, das Jarvis von 170 MB auf 299 MB in der RAM Nutzung nach oben geht. Auch rauscht machmal Javaskript sehr nach oben. Meine CPU langweilt sich aber weiterhin auf dem Papier!
Subjektive Meinung: Jarvis v3.1.2 und Javaskript v6.1.4 scheinen sich auf meinen Host nicht ganz zu vertragen. 
Hab nun Javaskript auf meinen Slave verlagert und jetzt deutlich weniger Probleme in der Aktualisierungsgeschwindigkeit der DP.

**Comment by somansch** [comment]
Ich kann den Bug bestätigen. Nutze v3.1.8 in Verbindung mit dem Fully Kiosk Browser. Teilweise werden die Secondary States (in HomeKitTiles) nicht aktualisiert, auch bei Änderung des Primary States bzw. Icon State.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.6` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.6` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@bambi-arch
