### ISSUE TITLE
v3.1.4-beta.6 Anzeige ?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2294]
evtl hängt es auch mit nodejs v18 und npm 9.5.0 zusammen?
Kommt, wenn der Wertvom State  `null` ist.
![image](https://user-images.githubusercontent.com/84818934/226453789-00ee1445-f669-4721-874f-ed80c25a7ec9.png)

![image](https://user-images.githubusercontent.com/84818934/226453828-457ebdf3-9e03-4762-9190-64ed461d017c.png)

**Comment by Zefau** [comment]
Der Fehler kommt bei `null` sowie gleichzeitig aktivierter Option `isFloatComma` in den ioBroker Einstellungen. Wird mit dem nächsten Release behoben.

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.17` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.17` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Fehler wird nicht mehr angezeigt. Danke.
