### ISSUE TITLE
Transparentes Design nicht möglich!?

### ISSUE THREAD

**Issue by tschortschde** [Zefau/ioBroker.jarvis#2295]
Hallo,

obwohl ich der [Anleitung ](https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/styles/transparentes-design)für das transparente Design gefolgt bin, bekomme ich es nicht hin, dass die Widgets transparent sind.
Wo mache ich den Fehler?

![Screenshot 2023-03-21 151447](https://user-images.githubusercontent.com/11274233/226635008-a8a5685e-5aad-49fe-b6d7-29a551085f94.jpg)

Viele Grüße

**Comment by mcuiobroker** [comment]
PRO-Version vorhanden?

**Comment by mcuiobroker** [comment]
Nimm mal bitte die v3.1.4-beta.6.

**Comment by tschortschde** [comment]
Perfekt ;-) der Dark-Mode ist supi.
Kannst Du mir bitte noch sagen, ob ich den Background mit Jarvis etwas blasser erscheinen lassen kann?
So ähnlich wie dieses Foto oder muss ich dass mit einem Bildbearbeitungsprogramm machen?
![Screenshot 2023-03-21 172619](https://user-images.githubusercontent.com/11274233/226675746-4626cc47-a2d9-486e-95bc-9b972370d399.jpg)

**Comment by tschortschde** [comment]
Kein Problem, 
vielen Dank für Deine Hilfe

**Comment by mcuiobroker** [comment]
Bitte schließen.
