### ISSUE TITLE
True/False Verlaufsdiagramm wird im Widget "invertiert" dargestellt

### ISSUE THREAD

**Issue by bitvilla** [Zefau/ioBroker.jarvis#2296]
**Grundlage:**
In meiner Haussteuerung überwache ich meine Wärmepumpe mit einem Stromwandler. Dieser liefert ab einem Stromverbrauch von 2 Ampere ein "True"-Signal. Schaltet die Wärmepumpe ab, wird sie durch ein externes Signal für zwei Stunden gesperrt. 
Diesen Wert/Vorgang logge ich in iobroker über das History-Modul. Das Modul stellt den Verlauf des Stromsignales auch korrekt dar.
Die Einschaltdauer der Wärmepumpe und die Pausendauer von 2h sind eindeutig zu erkennen.

![History_01](https://user-images.githubusercontent.com/128739181/227315610-8feff39f-d901-4d71-a37a-a25f7be8fa3f.png)

**Beschreibung des Fehlers:**
Nehme ich nun diesen Wert aus dem ioBroker History-Modul um in Jarvis (3.1.2) über das HistoryGraph-Modul die gleiche Grafik zu erzeugen, dann wird die Kurve standardmäßig "invertiert" dargestellt. Anders gesagt, werden die 2h Pausenzeit als Einschaltzeit dargestellt und umgekehrt.

![Stromsignal_falsch](https://user-images.githubusercontent.com/128739181/227318164-bccd4176-dc68-4be6-9933-9a2b391eb29b.png)

Habe mir aktuell über die Callback-Funktion geholfen und einfach True&False vertauscht.
`val => {if (val == 0) {return 1;} else {return 0;}}`

![Stromsignal_richtig](https://user-images.githubusercontent.com/128739181/227323590-19ab674d-bb5b-4af8-a5b8-b29096fb0d70.png)

Die Grafik wird aus meiner Sicht nun richtig dargestellt. Habe aber nun das Problem, dass der letzte Status des Wertes immer flasch ist. Ein dauerhaftes False-Signal wird so zum dauerhaften True-Signal und umgekehrt.

**Auszug aus den Verlaufsdaten von ioBroker:**

23.3.2023 18:44:19.395 | true
23.3.2023 16:38:36.029 | false
23.3.2023 16:34:56.715 | true
...
23.3.2023 06:10:21.837 | true
23.3.2023 04:06:43.777 | false
23.3.2023 02:40:49.364 | true

**Comment by Zefau** [comment]
bitte schau nochmal mit `v3.1.4-beta.7`

**Comment by bitvilla** [comment]
Hallo Zefau, 

mit BETA-Tests habe ich noch wenig Erfahrung.
Habe einfach meine Docker-Produktivumgebung kopiert und über den Experten-Modus die "benutzerdefinierte URL" für die Jarvis-BETA Version eingegeben. Das Update lief ohne Probleme durch und die "installierte Version" wurde im Adapter-Feld korrekt angezeigt. Hoffe das waren alle Schritte die durchgeführt werden mussten um die BETA-Version zu testen!

Im Folgenden die Ergebnisse:
Test mit `v3.1.4-beta.8` 

Nach einem Testbetrieb von 24h hat die Darstellung der Diagramme noch den gleichen Fehler.
![Stromsignal_BETA01](https://user-images.githubusercontent.com/128739181/234265986-190e4eee-0b6d-4156-8e92-d179852621b1.png)

#### Auszug aus den Verlaufsdaten von ioBroker:
25.4.2023 12:15:34.940 | false
25.4.2023 11:38:45.682 | true
25.4.2023 09:33:02.029 | false
25.4.2023 09:27:58.650 | true
25.4.2023 07:22:15.002 | false
25.4.2023 07:17:13.768 | true
25.4.2023 05:11:29.885 | false
25.4.2023 05:06:23.548 | true
25.4.2023 03:00:37.530 | false
25.4.2023 02:56:16.765 | true
25.4.2023 00:50:33.963 | false
25.4.2023 00:45:47.767 | true

Für die korrekte Darstellung der Kurve sollte diese bei FALSE-Status von "EIN" auf "AUS" springen und bei TRUE-Status von "AUS" auf "EIN". Wie an den eingezeichneten Datenpunkten zu erkennen ist, springt die Kurve aber an einem Datenpunkt "FALSE" von "AUS" auf "EIN" und umgekehrt.

 Kann ich noch weiter unterstützen?

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.16` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.16` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by bitvilla** [comment]
Test erfolgreich! 
Mit der Version 'v3.1.4-beta.17' werden die Kurven richtig dargestellt.
