### ISSUE TITLE
Is it possible to add i18n support

### ISSUE THREAD

**Issue by yaming116** [Zefau/ioBroker.jarvis#23]
We are a group of smart home enthusiasts from China, and currently found that this program does not run well in the Chinese environment. We wanted to submit some translated text, but found that not all of these contents are in the i18n file. Can you make relevant improvements to facilitate us to submit the corresponding translation files。

   https://bbs.iobroker.cn/

![image](https://user-images.githubusercontent.com/2171071/82827112-ec260900-9ee0-11ea-8d15-d0686f76c0a9.png)

**Comment by Zefau** [comment]
The app is so far only translated to German and English. The development repository can be found via https://github.com/Zefau/jarvis. This repository is the compiled build.

You may translate from English to Chinese and I can add the translation to the build.
For that you need to translate the words given in https://github.com/Zefau/jarvis/tree/master/src/i18n (see the German translation `de.js` for an example).
Furthermore, it is necessary to translate every function (e.g. light, blind and so on). These translations can be found in each of the folders under https://github.com/Zefau/jarvis/tree/master/src/functions.

If you need any more help please let me know.

**Comment by yaming116** [comment]
I checked these files and found that not all the text is in it. Then I also found that https://github.com/Zefau/jarvis/blob/master/src/modules part of the set contains translation content

**Comment by Zefau** [comment]
@yaming116 jarvis (`1.0.0-beta.3`) should be running stable now even though a foreign language is set. It will fall back to English if no translations are given. 

Furthermore, you may find all translations in the German translation (English -> German), which you can use to translate it to your language. You need to search for `i18n/de.js` within https://github.com/Zefau/jarvis/tree/master/src. Every component handles its translation, which means you will find multiple translation files. Please create a fork of https://github.com/Zefau/jarvis and provide the language files. I will merge them then.

https://github.com/Zefau/jarvis/find/master:
![image](https://user-images.githubusercontent.com/14368811/92028348-2dda1180-ed64-11ea-8997-11fe04eae999.png)

**Comment by Zefau** [comment]
@braindead1 German translations are now completed with `v1.0.0-beta.3`. If you find any English texts which are not translated, please let me know.

**Comment by Zefau** [comment]
3c48101d4346b58911526fe798c5b4a029995ee2
