### ISSUE TITLE
Definierte Visuseite direkt per Link öffnen

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#230]
Ich würde gerne die verschiedenen erstellten Räume direkt öffnen können.

http://x.x.x.x:8082/jarvis/index.html?page=badezimmer

**Comment by Zefau** [comment]
@Timmes123 @duczz added with `1.1.0-beta.53`.

**Comment by Timmes123** [comment]
getestet mit beta53

ich kann jetzt zwar wenn ich die tabs wechsle adressen in der form sehen:
http://192.168.0.4:8082/jarvis/index.html#&tab=wohnbereich-2

allerdings wenn ich einen browser öffne und diese adresse in die adresszeile eingebe komme ich nicht aufs richtige tab,
sondern ich lande wieder bei http://192.168.0.4:8082/jarvis/index.html und somit auf dem ersten tab

**Comment by Timmes123** [comment]
mir ist ebenfalls aufgefallen das beim ersten tabwechsel hinter dem index.html nur ein #tab steht,
beim 2. tab wechsel steht #&tab in der adresse.
ich weis nicht ob das ein problem darstellt, ich wollte es nur anmerken

**Comment by Zefau** [comment]
Mit `v1.1.0-beta.54` sollte es nun passen. Das `#&` sollte nun auch nicht mehr vorkommen.

**Comment by Timmes123** [comment]
getestet mit beta 54

neues browserfenster mit http://192.168.0.4:8082/jarvis/index.html#tab=wohnbereich-2 öffnet direkt das richtige tab :-)

also für meine zwecke ist der bug beseitigt,
allerdings ist mir noch aufgefallen, dass wenn ich bereits jarvis offen habe auf irgendeinem raum und dann 
http://192.168.0.4:8082/jarvis/index.html#tab=wohnbereich-2 eingebe, dann wechselt er das tab nicht.

ist wie gesagt für mich nicht relevant, aber ich wollte es dir trotzdem sagen, falls du da nochmal hand anlegen willst.

wenn ich den link von extern öffne, dann lädt er die seite sowieso jedes mal neu, von daher passt es für mich

**Comment by Zefau** [comment]
Jo, das ist erstmal ok.
