### ISSUE TITLE
! jarvis-windows_v3.1.3-beta.11 löscht ebend mal alle Datebpunke in der Vis :-(

### ISSUE THREAD

**Issue by bmgs40** [Zefau/ioBroker.jarvis#2300]
Jarvis 3.1.2 keine Daten mehr in den Widgets,
Nach dem start von jarvis-windows_v3.1.3-beta.11

BMGS

**Comment by mcuiobroker** [comment]
Ist bekannt. Aber nicht alle DPs werden gelöscht sondern nur die Widgets, bzw. die sind nicht mehr nutzbar?
Man muss einmal die Widgets wieder in den jarvis-DP zurücksichern.
Warum nicht die neueste Version von Windows App? Wäre aber auch nicht anders.

**Comment by bmgs40** [comment]
Dsnke Probleme lies dich schnell lösen😀MfGBmgsAm 25.03.2023 um 22:46 schrieb mcuiobroker ***@***.***>:﻿
Ist bekannt. Aber nicht alle DPs werden gelöscht sondern nur die Widgets, bzw. die sind nicht mehr nutzbar?
Man muss einmal die Widgets wieder in den jarvis-DP zurücksichern.
Warum nicht die neueste Version von Windows App? Wäre aber auch nicht anders.
