### ISSUE TITLE
scripts-Meldung ? Initialwert (null)

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2302]
scripts - DP wird initial mit (null) gefüllt?
![image](https://user-images.githubusercontent.com/84818934/227802204-3691247c-cd1b-4d60-aa5e-cd19c69206a5.png)

**Comment by Zefau** [comment]
Was nutzt du denn da für eine Version, wenn der Fehler von `index-ec356f16` kommt? Die Datei finde ich nicht in der aktuellen bzw. den bisherigen Versionen?

**Comment by mcuiobroker** [comment]
Es war glaube ich v3.1.2. Kommt aber in v3.1.3 nicht vor.
Wollte es nochmal testen, aber bei Version Rückgang entstand das Widget Problem.
Würde es erstmal schließen.
