### ISSUE TITLE
v3.1.4-beta.6 Summieren auf value Binding-Seite funktioniert nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2303]
Anzeigevariante
`{"default":"(parseInt({val})+parseInt({0_userdata.0.jarvis.test.num2}))"}`
Beide sind Type `number`.

![image](https://user-images.githubusercontent.com/84818934/227802495-79d0f5e3-232c-494e-8f74-7b2f1ac7ffcd.png)

Ergebnis:
Direkt nach dem `Speichern und Zurück` ist ok

![image](https://user-images.githubusercontent.com/84818934/227802410-ce7a77e2-f529-4db2-b92c-cbdda70ca259.png)

Nach dem automatischen Neuladevorgang

![image](https://user-images.githubusercontent.com/84818934/227802441-ee01f034-4cf0-41a6-9859-20129c3bc453.png)

Versuch über Datenpunkt-Eigemschaften funktioniert auch nicht:
```
{
  "value": "(val) => {if(!val){ return;} else{ window.Socket.getState('0_userdata.0.jarvis.test.num2', ({ err, state }) => {    let wert = state.val; console.log(state.val); console.log(val); console.log(parseInt(wert+val));return parseInt(wert+val);}); }}"
}
```

**Comment by Zefau** [comment]
besteht das Problem mit v3.1.3 nicht? Erst mit v3.1.4?

**Comment by mcuiobroker** [comment]
Ja in 3.1.3 funktionierte es noch.

**Comment by mcuiobroker** [comment]
v3.1.4-beta.21
![image](https://user-images.githubusercontent.com/84818934/236012457-4c60f5fa-6b80-460c-acb8-39e88b60e65c.png)
![jarvisv314-beta 21 Anzeigevariante Summe bilden](https://user-images.githubusercontent.com/84818934/236012808-d85279c5-68f5-4419-8ed2-29b75ed949d4.gif)

**Comment by Zefau** [comment]
Das hier ist mit v3.2 noch aktuell?

**Comment by Zefau** [comment]
@mcuiobroker

**Comment by mcuiobroker** [comment]
Ja noch offen
![image](https://github.com/user-attachments/assets/ef3d71e4-61a0-4e4d-a359-b830a64ba2ce)
![image](https://github.com/user-attachments/assets/11fcc26e-f861-4431-a792-51d53f774b78)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.50` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.50` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
