### ISSUE TITLE
v3.1.4-beta. 6 Meldung device using "" ?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2304]
![image](https://user-images.githubusercontent.com/84818934/227810621-5708f30a-dfd7-40ff-8d00-4aa09d8ee19e.png)

![image](https://user-images.githubusercontent.com/84818934/227810648-2a3a39fb-ea50-4f17-8df3-d35b39b9bce0.png)

evtl Zusammenhang mit Number() auf value-Seite?
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/geraet/anzeigevariante/summe-anzeigen

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Ist noch da:
![image](https://user-images.githubusercontent.com/84818934/235770611-1eb8a7c1-919d-46b9-a988-9a0b9a01973d.png)

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.21` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.21` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Der Fehler ist weg.
Bleibt bei dem Gerät nur der Berechnungsfehler in Anzeigevariante
`"display": {
          "default": "(parseInt({val})+parseInt({0_userdata.0.jarvis.test.num2}))"
 },`
#2303
