### ISSUE TITLE
3.1.4-beta.6 - iframes werden in in iOS Safari und ioBroker App nicht angezeigt

### ISSUE THREAD

**Issue by pphlwmarcel** [Zefau/ioBroker.jarvis#2312]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
3.1.4-beta.6 unter iOS Safari bzw. ioBroker App (iOS 16.3.1)

**Describe the bug / Beschreibe den Fehler**
nicht alle iFrames werden in Safari bzw. der ioBroker App auf dem iPhone angezeigt.
Wenn Logfiles benötigt werden stelle ich diese gerne zur Verfügung.
In 3.1.2 funktionieren die iFrames ohne Probleme

**Comment by mcuiobroker** [comment]
Gibt es Fehler im Browser-Log? F12.

**Comment by pphlwmarcel** [comment]
Kann ich auf dem iPhone leider nicht einsehen. Am PC gibt es keine, da wird aber auch alles geladen.

**Comment by Zefau** [comment]
Ist die Option "Aufrechterhalten" aktiviert? Wenn ja, bitte deaktivieren.

**Comment by pphlwmarcel** [comment]
Nein die Option ist nicht aktiv.

**Comment by pphlwmarcel** [comment]
In 3.1.8 tritt das Problem nicht mehr auf.

**Comment by Zefau** [comment]
Ich schließe mal, wenn der Fehler nicht mehr auftritt.
