### ISSUE TITLE
v3.1.4-beta.6 Fehler bei Eingabe in InputAction

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2313]
Bei der Eingabe von Zahlen in der InputAction (egal ob val oder value) kommt dieser Fehler 
![image](https://user-images.githubusercontent.com/84818934/229907893-cd764ed3-c2e6-4592-8416-02dee1b73b56.png)

Es sollen mit der Eingabe mehrere DP - Werte in unterschiedlichen DPs mit val gesetzt werden.

Dies funktioniert auch, es kommt halt nur der Fehler.

Datenpunkt-Eigenaschaften
```
{"value":"val => { if(!val){return 0;} window.Socket.setState('0_userdata.0.jarvis.test.num2',val); window.Socket.setState('0_userdata.0.jarvis.test.num1',val); return val;}"}
```

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.16` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.16` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Eingabe nicht mehr möglich

**Comment by Bernd9000** [comment]
Dito, habe ich auch, keine Eingabe mehr möglich

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.18` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.18` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
