### ISSUE TITLE
v3.1.4-beta.6 - Verschieben vom Widget auf leere Tabseite -> Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2315]
Es kommt dann der Fehler:
`Anchor: target ".widgetOptions-834d7adf-5369-4934-8e2b-051720506a63" not found`

![image](https://user-images.githubusercontent.com/84818934/230742436-827d5a04-457a-4870-90a2-8b6713f3ecea.png)

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.16` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.16` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Kein Fehler mehr. Danke.
