### ISSUE TITLE
Webseite zeigt "Not existing" auf iobroker Visu App

### ISSUE THREAD

**Issue by umurcos** [Zefau/ioBroker.jarvis#2316]
**Voraussetzungen**
- [v3.1.2] Pro

**Beschreibe den Fehler**
Ich habe die iOS App "iobroker Visu" installiert und die IP Adresse als URL eingegeben. 192.168.1.X:8123. Es kommt jedoch ein weißer Screen mit der Meldung "Not existing". Sonst tut sich nichts. 

Ähnliche Fehler sind auch auf anderen Browser passiert. Ich musste vorher mich bei ioBroker anmelden, danach wieder auf die Jarvis URL drauf, dann ging es. Hier in der App ist jedoch ein Anmelden auf iobroker nicht möglich.

Web.0
<img width="1134" alt="image" src="https://user-images.githubusercontent.com/33093135/230979021-3185ea44-1cc5-4a38-8ec4-821e35ef7ca2.png">

**Comment by mcuiobroker** [comment]
Wie sind die Einstellungen in der App?
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/apps/iobroker-visu-app-2023

**Comment by mcuiobroker** [comment]
Weiß nicht wie das funktionieren soll, wenn der WEB-Adapter auf Port 8082 läuft.
![image](https://user-images.githubusercontent.com/84818934/230982188-02f2a3f0-f65b-425f-ac8f-b311112aa698.png)

**Comment by mcuiobroker** [comment]
Jarvis Einstellungen
![image](https://user-images.githubusercontent.com/84818934/230993819-d2f94adf-3409-47a1-902c-d9c52ff7527f.png)
App-Einstellungen siehe Link von oben.

**Comment by umurcos** [comment]
> Jarvis Einstellungen (automatisch ermitteln lassen) ![image](https://user-images.githubusercontent.com/84818934/230993819-d2f94adf-3409-47a1-902c-d9c52ff7527f.png) App-Einstellungen siehe Link von oben.
> 
> Welche web.0 Übersicht meinst du?
> 
> Solange Zefau nicht da ist, solltest du einen System Experten im ioBroker-Forum fragen. z.B. Thomas Braun

Ich habe den Fehler, es liegt an der iobroker Visu App, ich werde es reporten. Solange es noch da ist könnte man es in die Jarvis Doku aufnehmen: Es lag daran, dass das "H" in Http groß war. Es muss ein kleinen h -> "http".

**Comment by umurcos** [comment]
> Steht so in der Doku:
> ![image](https://user-images.githubusercontent.com/84818934/230995658-e00fd5bd-99a8-4447-8d82-76a40c501d83.png)
> Ich kann es ja mal als Hinweis aufnehmen, dass man darauf achten soll. OK?
> Doku angepasst.

Super passt, danke!
