### ISSUE TITLE
No Label for secondary datapoints does not work

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2317]
> Ich habe Jarvis v3.1.2 im Einsatz. Scheint dort nicht zu funktionieren. Siehe hier:
   https://forum.iobroker.net/post/970487

_Originally posted by @koalamusala in https://github.com/Zefau/ioBroker.jarvis/issues/690#issuecomment-1490977264_

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.17` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.17` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@koalamusala

**Comment by koalamusala** [comment]
Funktioniert! Danke!

**Comment by hosabeni** [comment]
Bei mir passt es nicht mehr. 
Bis zur Version `v3.1.4-beta.20` wurde der Secondary State mit `{"0":""}` in der Anzeigevariante ausgeblendet, das funktioniert jetzt nicht mehr. Jetzt wird der Wert immer angezeigt.



![Image](https://user-images.githubusercontent.com/77939385/236283303-65c34e84-776c-4b19-a887-63a6a8853a50.png)

**Comment by mcuiobroker** [comment]
Auch das Label wird nicht angezeigt bei default?
![image](https://user-images.githubusercontent.com/84818934/236326653-7adf0e97-9249-476f-8783-8d5a2df2ccfe.png)

Nur secondary-Wert
val = 100 
![image](https://user-images.githubusercontent.com/84818934/236326360-ea02ed64-f4db-44cb-ac77-6f45b77b53a9.png)
val = 0
![image](https://user-images.githubusercontent.com/84818934/236326448-0599f3c2-3189-4550-9609-be5e7eb7be33.png)

**Comment by hosabeni** [comment]
Gibt es hier Neuigkeiten? 
Werden die Bugs in der 3.1.x noch behoben oder geht es mit der 3.2.x weiter?

**Comment by hosabeni** [comment]
Das Problem besteht auch noch in der 3.2.0-alpha.7

**Comment by Zefau** [comment]
@hosabeni
