### ISSUE TITLE
v3.1.3 -> v3.1.2 Widgets werden verändert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2319]
![image](https://user-images.githubusercontent.com/84818934/232336353-7cd8d537-2c4d-43a2-9db3-3d0e3546f78c.png)

**Comment by Zefau** [comment]
Ich befürchte daran kann ich nichts mehr ändern. Das ist der Bug, der ist nun schon häufiger beschäftigt hat. Der ist in v3.1.3 behoben, aber eben nicht in v3.1.2.

Wenn du zurück gehst, dann greift der v3.1.2 Code mit dem Bug.

Der Fehler sollte demnächst nicht auftreten, wenn du von v3.1.4 auf v3.1.3 gehst.

**Comment by mcuiobroker** [comment]
War auch ehr zur Info.

**Comment by Zefau** [comment]
Jo, vielen Dank. Ich wünschte ich könnte das noch im Nachgang fixen, da der Bug schwer wiegt.
