### ISSUE TITLE
Support import of devices from ioBroker.zwave2 adapter

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#232]
https://forum.iobroker.net/post/507795
> ich verwende mehrere Heizkörper-Thermostate (Eurotronic Spirit Z-Wave Plus), welche nicht automatisch erkannt werden. Gibt es eine Möglichkeit diese automatisch hinzuzufügen?
![image](https://user-images.githubusercontent.com/14368811/96925444-78e6ea00-14b4-11eb-9cf6-f96dadc2b0b8.png)

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/507836

**Comment by Zefau** [comment]
function `heating` added with `1.1.0-beta.45`

**Comment by Zefau** [comment]
help wanted to implemented more functions

**Comment by ottk3** [comment]
This is working fine for me!

I've got a additional questions regarding the "Eurotronic Spirit Z-Wave Plus"

1.) In the "StateListHorizontal" Widget modal I get a "LevelBody" for the "normal heating temperature" but not to adjust the "energy-saving temperature".
![image](https://user-images.githubusercontent.com/5236802/97085424-c0d55080-161d-11eb-881d-220ed3744566.png)

2.) Could you add the valve opening degree to the device import?

**Comment by Zefau** [comment]
>  In the "StateListHorizontal" Widget modal I get a "LevelBody" for the "normal heating temperature" but not to adjust the "energy-saving temperature" (setTemperatureEnergySave).

Needs to be manually set up in the device configuration.

> Could you add the valve opening degree to the device import?

What state is that? `Multilevel_Switch.currentValue` is added already, but I guess this is something different?

**Comment by ottk3** [comment]
Hi @Zefau,
maybe I messed something up with the `currentValue`. Everything works now as expected. Thank you!

**Comment by Zefau** [comment]
I keep this open in case someone can contribute more device types.

**Comment by matthiasng** [comment]
> I keep this open in case someone can contribute more device types.

But how ? Not sure if im just blind, but it seems like you have only uploaded the webpack result

**Comment by Zefau** [comment]
If you have more device let me know and I will add them.

**Comment by matthiasng** [comment]
Alright, what do you need to add a new device ?
Is an example device configuration enought ?

And am i right with the adoption that the source of this project is "closed" ? Or am i just blind :-D

**Comment by Zefau** [comment]
You can see [the structure in the Wiki here](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices_Importer#function-heating-of-zwave2).

To translate into this structure I need to know the **device function** (heating, light, blind, etc.) and a screenshot / list of the states which shall be imported.
