### ISSUE TITLE
v3.1.4-beta.6 Theme scrollbars-Änderung wird nicht korrekt gespeichert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2320]
![image](https://user-images.githubusercontent.com/84818934/232344565-09a188b2-14d6-490e-89b7-27e05ee2a35d.png)
Nur Desktop und mobile werden gespeichert
![image](https://user-images.githubusercontent.com/84818934/232344591-82c8d802-5fc2-4e74-a9f1-404787a3f422.png)

![image](https://user-images.githubusercontent.com/84818934/232344616-0d64bbc2-81cc-456b-948b-701a746eddb8.png)

Always wird nicht gespeichert

**Comment by Zefau** [comment]
Funktioniert bei mir 1a. Sowohl auf Desktop einstellen, als auch wieder zurück auf `immer zeigen`. Hast du Fehler in der Browser Konsole?
