### ISSUE TITLE
TAB-Icon vergrößern durch Icon Stil nicht möglich

### ISSUE THREAD

**Issue by marsmaennchen** [Zefau/ioBroker.jarvis#2323]
v3.1.4-beta.6 (pro)

Ein vergrößern der Tab Icons mit font-size im TAB -> Icon Stil bewirkt keine Änderung.
 
![tabicon2](https://user-images.githubusercontent.com/33393715/232621848-37cb31ab-3c4d-40ca-8d8b-7d013350ae93.PNG)

Nur möglich in Styles alle zu ändern durch:
`.jarvis-tabs-container .tabIcon {
	transform: scale(2.5, 2.5);
}`

**Comment by Zefau** [comment]
1. Du musst `default` weglassen, da bei Tabs und Seiten keine State-Werte den Style beeinflussen, daher ist es nicht zu unterteilen
2. `font-size` funktioniert (dennoch) nicht, da es sich um ein SVG handelt (nicht um eine Schriftart, wie sonst oft der Fall). Du kannst die Größe aber mittels `zoom` beeinflussen.

Sollte das passen, gerne das Issue schließen

**Comment by marsmaennchen** [comment]
Kenne mich aus, danke.
