### ISSUE TITLE
v3.1.4-beta.7 Notification delete-Icon wird nicht angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2324]
![image](https://user-images.githubusercontent.com/84818934/232645216-29f9af9e-1b52-4fad-84ec-8bc2d7126823.png)

**Comment by mcuiobroker** [comment]
![Image](https://user-images.githubusercontent.com/84818934/233493038-f4b2f988-5547-495d-ab17-6ac5020f6e3c.png)

**Comment by Zefau** [comment]
`v3.1.4-beta.8`
