### ISSUE TITLE
3.1.2 Vergleichsoperation in Anzeigevariante liefert falsches Ergebnis

### ISSUE THREAD

**Issue by thoml95** [Zefau/ioBroker.jarvis#2325]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [3.1.2] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Ich vergleiche unter Anzeigevariante (JSON Format) zwei Datenpunkte miteinander (vom Typ Number).
Es scheint als macht das Vergleichen Probleme wenn die Zahlen eine unterschiedliche Anzahl an Ziffern haben.

Beispiel:
```
{ 
"default": "STANDART",
"{test.0.test1}>{test.0.test2}": "TEST"
}
```
test1 = 4-9
test2 = 3
Ausgabe = TEST

test1 = 10-19
test2 = 3
Ausgabe = STANDART

test1 = 20-29
test2 = 3
Ausgabe = STANDART

test1 = 30-99
test2 = 3
Ausgabe = TEST

test1 = 100-299
test2 = 3
Ausgabe = STANDART

test 1 = 23
test 2 = 23
Ausgabe = STANDART

test 1 = 24-99
test 2 = 23
Ausgabe = TEST

test 1 = 100
test 2 = 23
Ausgabe = STANDART

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Verstehe ich nicht genau. Wenn der Datenpunkt `test.0.test1` ist, dann steht da eine normal Zahl drin und keine Rechenoperation wie `4-9`. Ich vermute, dass `4-9` als Zeichenkette / String interpretiert wird und es daher vermeintlich falsch ist.

**Comment by thoml95** [comment]
Sorry, hab mich nicht ganz verständlich ausgedrückt.
Der Bindestrich stellt kein Minuszeichen dar, sondern ein „bis“ also z.B. 4 bis 9.

Im Endeffekt werden Zahlen nur richtig verglichen (egal ob < oder >) wenn sie die selbe Anzahl an Ziffern haben. Wenn ich also z.B. 3 > 29 habe wird die 3 als größer angesehen, bei 23 > 29 ist dann richtig die 29 größer. 

Ob dies nur auftritt wenn man in der Anzeigevariante zwischen Datenpunkten vergleicht oder auch wenn man direkt Zahlen vergleicht habe ich aber nicht getestet.

**Comment by Andr3asB** [comment]
Welchen Typ haben die Datenpunkte denn - Number oder String?
Als String wäre die Sortierreihenfolge 0,1,10,11,12,13,14,15,16,17,18,19,2,21,22,...29,3,30,31 ...
Damit ergibt sich dann der unlogisch klingende Vergleich der Zahlenwerte.

**Comment by thoml95** [comment]
> Ich vergleiche unter Anzeigevariante (JSON Format) zwei Datenpunkte miteinander (vom Typ Number).

Sind beide vom Typ Number.

**Comment by Zefau** [comment]
Klingt für mich auch als würde jarvis hier einen String-Vergleich durchführen. Ich schaue es mir an.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.16` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.16` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@thoml95
