### ISSUE TITLE
Gewerk Steckdose:  Schalter wird angezeigt, obwohl er nicht ausgewählt ist

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2326]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/2248

<div type='discussions-op-text'>

<sup>Originally posted by **mcuiobroker** February 25, 2023</sup>
Ist das so gewünscht?
https://forum.iobroker.net/topic/63355/jarvis-hmip-fsm-power-datenpunkt

Sollte ein graues Element angezeigt werden?</div>

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.18` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.18` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@mcuiobroker Könntest du dir das mal anschauen, ob das so passt?

**Comment by mcuiobroker** [comment]
Mach ich gleich.

**Comment by mcuiobroker** [comment]
Passt. Danke.
