### ISSUE TITLE
v3.1.4-beta. 6 Umschalten tabsCollapse wird erst nach Reload (F5) umgesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2329]
![image](https://user-images.githubusercontent.com/84818934/233139219-91f77879-423a-4691-b7ca-9bf0d523ec49.png)
Umstellen vom DP von `false`  auf `true` oder umgekehrt zieht nicht sofort, erst nach Reload.

Zeitweise auch bei Mini Sidebar so, obwohl keine Meldung wegen Socket.

**Comment by mcuiobroker** [comment]
Passt. Danke.

**Comment by Zefau** [comment]
`v3.1.4-beta.8`
