### ISSUE TITLE
BlindLevelAction true/false

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#233]
Ich verwende KNX Jalousieaktoren
Diese verwenden neben 0-100% auch Up/down/stop als boolschen eingang
false = rollo öffnen
true = rollo schliesen
wenn der rolle bereits fährt: true oder false = stop
Das kann ich denke ich mit dem BlindLevelAction nicht ansteuern
gleiches gibt es von anderen herstellern anstatt mit true/false mit 0,1,2 integer

**Comment by Zefau** [comment]
`level` mit dem Datenpunkt, der die Werte 0-100 nimmt konfigurieren.
`activity` mit dem Datenpunkt (Anzeige), der den Status hält und Datenpunkt (Trigger) mit dem Stop Boolean.

**Comment by Timmes123** [comment]
level ist klar, damit bediene ich ja aktuell
activity funktioniert so aber nicht.
ich hab den datenpunkt auf/ab jetzt bei anzeige und trigger drin.
wenn ich das popup für den rollo öffne und da die auf ab stop taste verwende, funktioniert es zwar wie es soll, aber auf und ab ist verdreht.
wenn ich im layout rechts den trigger anzeigen lasse fährt er mit beiden tasten nach oben, weil sich glaube ich nur zahlen in der widget konfig einstellen lassen. ich hab da mal true und false rein geschrieben, bringt aber auch nichts. zusätzlich steht wenn ich den trigger einfüge nicht mehr z.b.70% dort. sondern 70 undefined und beim fahren NaN undefined

**Comment by Timmes123** [comment]
![image](https://user-images.githubusercontent.com/73311538/96928862-7e92fe80-14b9-11eb-9f63-c7ee6b4b6fe5.png)

**Comment by Timmes123** [comment]
![image](https://user-images.githubusercontent.com/73311538/96929167-07aa3580-14ba-11eb-808b-46e9dbe102a1.png)
hier funktionieren die tasten zwar, allerdings up/down verdreht
und meine istwert anzeige funktioniert nicht mehr ist mir gerade aufgefallen

**Comment by Timmes123** [comment]
ah ok ich verstehe. du steuerst mit den buttons nicht true/false an, sondern schreibst 0 bzw 100 in den level. dh bei der widget konfig funktioniert es auch wenn ich level einstelle als trigger, nicht activity. allerdings ist das nicht die lösung des problems. den ich möchte ja das ich mit den auf ab buttons true bzw false in den bool datenpunkt schreiben

**Comment by Timmes123** [comment]
vielleicht als erklärung für dich warum ich die lösung mit den button schreibt 100 ins level für einen schwachpunkt halte ;-)
wenn ich meinen rollo mehrfach hoch und runter bewege ohne in eine endlage zu fahren. z.b. mehrfach zwischen 20 und 80% hin und her fahre, dann passt die mechanische position durch die motorreaktionszeiten usw nicht mehr ganz exakt -> der rollo denkt er steht auf 20% steht aber in wirklichkeit auf 25. wenn ich jetzt in den level 0 schreibe, dann bekomm ich den rollo nicht mehr ganz hoch. denn er bleibt bei 5% stehen, weil er denkt er wäre auf 0. ich hab dann auch keine chance den rollo weiter nach oben zu bewegen. ich müsste dann zuerst den rollo ganz nach unten fahren, damit ich wieder ganz nach oben komme.
der true/false button hingegen (bzw 0,1,2 bei anderen herstellern) ignoriert den prozentualen sollwert. der fährt einfach die maximal eingestellte zeit nach oben. heist wenn mein rollo bei 10% steht und ich drücke taste nach oben, müsste er sich zwar nur 3 sekunden bewegen, der ausgang bleibt aber dennoch die vollen 30 sekunden an.

**Comment by Zefau** [comment]
Valider Hinweis. Da es grundsätzlich funktioniert schaue ich mir das in der v1.2 Roadmap nochmal an.

**Comment by tango17b** [comment]
Hallo, ich verwende Dingz Schalter und die haben auch die Möglichkeit, up, down, stop direkt zu setzen.
Deshalb bin ich auch interessiert daran, auf  jeden der Buttons einen Triggerpunkt setzen zu können.
Das hätte dann auch den Vorteil, dass die Usability analog dem physischen Schalter dargestellt werden kann.

**Comment by Zefau** [comment]
@tango17b **Stimme für deinen Feature Request ab!**

Stimme für deinen Feature Requests ab indem du die Emoticons **beim ersten Beitrag** als Reaktion nutzt:
![Github Reactions](https://forum.iobroker.net/assets/uploads/files/1606215967286-1c3e566f-8d54-4f19-8948-eb8833c5b15f-image.png)
Siehe auch https://forum.iobroker.net/topic/30668/jarvis-v2-0-0-just-another-remarkable-vis/1986

_____

**Vote up your Feature Request!**

Vote up your feature request by selecting an emoticon **on the first post** as reaction:
![Github Reactions](https://forum.iobroker.net/assets/uploads/files/1606215967286-1c3e566f-8d54-4f19-8948-eb8833c5b15f-image.png)

**Comment by Zefau** [comment]
@tango17b  @Timmes123 ist der Feature Request noch aktuell? Sollte mit `min`/`max` (Datenpunkt Eigenschaften) umsetzbar sein?

**Comment by tango17b** [comment]
@Zefau : Danke für die Nachfrage, aus meiner  Sicht immer noch wünschbar, die Befehle  (up/down/stop) direkt  aus dem GUI abzugreifen statt den Weg über den Wertebereich zu nehmen.

**Comment by Timmes123** [comment]
@Zefau ich habs jetzt noch nicht getestet, war leider einige Zeit kaum am PC.
allerdings glaube ich nicht, dass die min/max Funktion das gleiche erfüllt.

![image](https://user-images.githubusercontent.com/73311538/103545410-cfec4080-4ea1-11eb-9b07-a3c56269c672.png)
 es geht hier ja darum, dass ich mit dem slider links einen sollwert 0-100 generiere, aber mit den rechten tasten (und nur mit denen) mit pfeil auf und ab auf einen datenpunkt true bzw false schicke (tauschbar natürlich) und mit dem stop befehl in der mitte einfach den gleichen befehl nochmal. Der stop muss dann nach kurzer zeit auch von selbst verschwinden bzw muss komplett ausblendbar sein. An meinen lokalen Tastern verwende ich nur Auf und Ab tasten.

true -> rollo fährt auf -> true(oder false) -> rollo stopt -> true -> rollo fährt weiter hoch,
das selbe wäre mit false beim runterfahren und je nach Aktor bzw Aktoreinstellung noch invertiert.

**Comment by Timmes123** [comment]
wenn das so umsetzbar ist mti den aktuellen möglichkeiten, dann ist es gut. Zum testen fehlt mir nur gerade leider die Zeit

**Comment by lind-home** [comment]
Hi Timmes123
hast du schon eine Loesung zu deinem problem in Jarvis gefunden. Ich steh vor dem gleichen problem. Zefau hat mir mal euren KNX Thread geschickt -> aber da hab ich auch nichts relevantes finden koennen (KNX Diskussion #301)

Dir zur info: Mein iobroker und KNX laufen mit meiner aktuellen VIS super -> ohne probleme

in Jarvis komm ich auch nur so weit wie das hier in dem Thread beschrieben ist
Aber bei auf/ab -> true false ueber die buttons gehen nicht

Gruss Juergen

**Comment by Zefau** [comment]
@emerq @Timmes123 @lind-home ich hab's mir nochmal angeschaut: https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#datenpunkt-eigenschaften

Versuch mal `min` / `max` statt `on` /  `off`. Also `{ "min": false, "max": true }` (oder umgekehrt, je nachdem, wie KNX das braucht).

**Comment by Zefau** [comment]
`v2.2.0-beta.21 `: Siehe auch https://github.com/Zefau/ioBroker.jarvis/issues/550#issuecomment-762475994
