### ISSUE TITLE
Sackgasse: PIN gesicherte Konfigseite ohne Tastatur im Kiosk-Modus 

### ISSUE THREAD

**Issue by Andr3asB** [Zefau/ioBroker.jarvis#2331]
Version 3.1.2:

Öffnet man die PIN-gesicherte Konfigseite im Kioskmodus ohne angeschlossene Tastatur (nur mit Maus/Touchscreen), dann kann die Seite mit der PIN-Abfrage nicht verlassen werden, weil der Abbrechen-Button am unteren Ende zwar sichtbar ist, aber nicht funktioniert.
Aktuell hilft nur ein Hard-Reset des Kiosk-Browsers/Reboot des Geräts.

Workaround: Konfigseiten in der Navigation ausblenden.

Lösung: Einen Abbrechen oder "Home-Dashboard"-Button auf der Seite mit der PIN-Abfrage einblenden.

**Comment by Zefau** [comment]
> weil der Abbrechen-Button am unteren Ende zwar sichtbar ist, aber nicht funktioniert.

Kannst du das mal screenshoten? Ein Abbrechen-Button sollte da nirgends zu sehen sein. Ich würde aber anhand deines Lösungsvorschlags einen implementieren.

**Comment by Andr3asB** [comment]
Hab das eben mal am PC simuliert (sitze gerade davor und dann muss ich nicht ins EG laufen 😁). Screen hängt bei mir im Portrait-Modus, daher der längliche Screenshot.

![image](https://user-images.githubusercontent.com/44557554/233448695-8ed8d0a5-8b4f-4adc-a3e6-a44fab31263e.png)

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.1.4-beta.8`

**Comment by Andr3asB** [comment]
Hab es getestet - läuft bei mir. Ich sehe jetzt einen "Cancel" Button und kann drauf klicken.
