### ISSUE TITLE
Scripts auch in die internen Sicherungen von jarvis aufnehmen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2334]
Zurzeit werden keine interne Sicherungen von scripts gemacht.

`/opt/iobroker/iobroker-data/jarvis/{Instanz}/scripts.json`

Sollte man das nicht auch machen?

![image](https://user-images.githubusercontent.com/84818934/233479118-e342e1f5-2fcd-4ac8-a30b-c29df874de12.png)

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.1.4-beta.21` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.1.4-beta.21`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Änderungen werden gespeichert, aber falsch.
siehe #2070

**Comment by Zefau** [comment]
Was wird denn falsch gespeichert?

**Comment by mcuiobroker** [comment]
Der "alte" Stand wird gespeichert.
Stimmt ja der soll ja auch gespeichert werden.
War ein Denkfehler von mir.
Passt.
