### ISSUE TITLE
v31.4-beta.8 Mini-Sidebar-Einstellung wird erst mit F5 aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2337]
Änderung vom DP `jarvis.0.settings.drawerMiniMode` lässt den Button verschwinden, es öffnet sich aber nicht die Mini-Auswahl.
Erst nach F5 wird sie angezeigt.

![image](https://user-images.githubusercontent.com/84818934/233728640-a14952cf-e370-44f9-be71-147693902ee5.png)

**Comment by mcuiobroker** [comment]
Ich mach es über den iobroker-DP.

**Comment by Zefau** [comment]
Funktioniert bei mir auch problemlos. Schau bitte nochmal mit `v3.1.4-beta.18`

**Comment by mcuiobroker** [comment]
Gleicher Effekt. Keine Besserung.
