### ISSUE TITLE
v3.1.4-beta.8 nächtlicher Reload 2x

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2338]
Der nächtliche Reload wird nachts um  03:00:00 Uhr gestartet und um 03:00:30 Uhr.
Soll das so?

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.19` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.19` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
