### ISSUE TITLE
JSONTable Laufband nach 3 Sekunden abschalten

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2339]
Hat man keine Daten in dem DP für die JsonTable, so läuft das Laufband (blau, `progressbar`) permanent. Dies sollte nach 3 Sekunden abgeschaltet werden oder einstellbar sein, es zu tun.
![image](https://user-images.githubusercontent.com/84818934/233861408-caf30dc4-3bc5-4c91-8e69-3d57fb8936de.png)

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.18` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.18` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
