### ISSUE TITLE
Allow TopBar / TabBar to be placed top, bottom, left or right

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#234]
https://forum.iobroker.net/post/507933
> Ist es in Zukunft möglich das Interface anders anzuordnen ... aktuell ich ja die Menüleiste oben Horizontal. Geht sowas auch unten Horizontal ?

**Comment by Flopsi75** [comment]
Ja das wäre super.

Hier noch ein Post dazu. Bitte voiting.

https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/3135
Die Möglichkeiten in Anlehnung an Gira wäre echt super.

**Comment by ChristianGrieger** [comment]
Ein Menü auf der linken, unteren und rechten Seite wäre super :) 
![83475a3e-1788-4e11-8756-b08ca8a53ebb](https://user-images.githubusercontent.com/8712219/105641126-b6c42780-5e82-11eb-9219-353f1c3a460d.jpg)

**Comment by Flopsi75** [comment]
Das sieht Mega aus @ChristianGrieger

**Comment by Zefau** [comment]
@Flopsi75 @ChristianGrieger 

**Vote up your Feature Request!**

Vote up your feature request by selecting an emoticon **on the FIRST POST** (NOT THIS POST) as reaction:
_____
**Stimme für deinen Feature Request ab!**

Stimme für deinen Feature Requests ab indem du die Emoticons **beim ERSTEN BEITRAG** (NICHT DIESER BEITRAG) als Reaktion nutzt:
Siehe auch https://forum.iobroker.net/topic/30668/jarvis-v2-0-0-just-another-remarkable-vis/1986

![Github Reactions](https://forum.iobroker.net/assets/uploads/files/1606215967286-1c3e566f-8d54-4f19-8948-eb8833c5b15f-image.png)

**Comment by Zefau** [comment]
added in `v3.0.0-alpha.10` (option for top and bottom; left and right is reserved for drawers)

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.61` TABs bottom eingestellt:
![image](https://user-images.githubusercontent.com/84818934/131903348-1ce41450-5e9e-45c5-8833-4636814f1700.png)

![image](https://user-images.githubusercontent.com/84818934/131903298-7dc52496-01b8-49f3-9774-5219e4b52a75.png)

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.70`.

**Comment by mcuiobroker** [comment]
Ja passt. Danke.
