### ISSUE TITLE
v3.1.4-beta.17 Fehler jsonTable

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2347]
welche jsonTable / HTMLTable ist das?
![image](https://user-images.githubusercontent.com/84818934/235326854-510862d9-2439-40ae-af8b-ab1e36e0ed5c.png)

Diese Einstellung?
```
[
  {
    "field": "Abfahrt"
  },
  {
    "field": "Verspätung"
  },
  {
    "field": "Plattform",
    "format": "val => val === 'null' ? '-' : val"
  },
  {
    "field": "Ankunft"
  },
  {
    "field": "Verspätung (2)"
  },
  {
    "field": "Plattform (2)",
    "format": "val => val === 'null' ? '-' : val"
  }
]
```
geändert auf -> keine Änderung
```
[
  {
    "field": "Abfahrt"
  },
  {
    "field": "Verspätung"
  },
  {
    "field": "Plattform",
    "format": "val => {if(!val){return '';} val === 'null' ? '-' : val}"
  },
  {
    "field": "Ankunft"
  },
  {
    "field": "Verspätung (2)"
  },
  {
    "field": "Plattform (2)",
    "format": "val => {if(!val){return '';} val === 'null' ? '-' : val}"
  }
]
```

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.18` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.18` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Kommt noch:
![image](https://user-images.githubusercontent.com/84818934/235527659-a94976f0-6bae-4284-a989-e36a753aa2b1.png)

**Comment by Zefau** [comment]
hm, also bei genauerer Betrachtung liegt der Fehler nicht in der JsonTable, sondern schon beim Verarbeiten des States (`prepareState`). jarvis kommt gar nicht bis zum Modul JsonTable, sondern bricht bereits davor ab.

Nach kurzer Analyse bricht er beim Parsen der Datenpunkt-Eigenschaften ab.

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.19` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.19` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Jetzt kommt kein Fehler mehr. Ist da jetzt noch ein Problem in irgendwelchen Datenpunkt-Eigenschaften drin und wird jetzt nicht mehr angezeigt?

**Comment by mcuiobroker** [comment]
Wenn ich dann in das Gerät auf den DP gehen will kommt:
![image](https://user-images.githubusercontent.com/84818934/235533576-95e7afec-2192-4c64-9acf-b576b1503f35.png)

**Comment by mcuiobroker** [comment]
Inhalt wäre:
```
 "a0301380-f9b0-42bf-a939-444804ce82f0": {
    "name": "BlindLevLev2",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "level2": {
        "_created": 1673784025642,
        "stateKey": "level2",
        "showState": true,
        "state": "0_userdata.0.jarvis.test.num2",
        "_updated": 1673784704592,
        "display": "",
        "actionElement": null,
        "bodyElement": null
      },
      "level": {
        "_created": 1673784014759,
        "stateKey": "level",
        "showState": true,
        "state": "0_userdata.0.jarvis.test.num1",
        "_updated": 1673802875839,
        "BlindLevelActionConfig": {
          "stopAction": null,
          "activityState": null
        },
        "properties": {
          "value": "val => {if (val=== 0 || val === 100) {window.Socket.setState('0_userdata.0.jarvis.test.num2',val);} return val;}"
        }
      },
      "activity": {
        "_created": 1673784014690,
        "stateKey": "activity",
        "showState": true
      },
      "stop": {
        "_created": 1673784014653,
        "stateKey": "stop",
        "showState": true
      }
    },
    "options": {},
    "id": "a0301380-f9b0-42bf-a939-444804ce82f0",
    "attributes": {
      "_created": 1673783988029,
      "_updated": 1673802826765
    },
    "revision": "0ea5b"
  },
```

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
