### ISSUE TITLE
v3.1.4-beta.17 - JSON Editor - 5 Sekunden Delay beim Start in Chrome

### ISSUE THREAD

**Issue by somansch** [Zefau/ioBroker.jarvis#2350]
Der JSON Editor braucht ca. 5 Sekunden nach Aufruf in der Gerätekonfiguration:
 
![image](https://user-images.githubusercontent.com/47367267/235440548-d23d5899-0186-43df-8d63-8a9a71f64b1d.png)
Browsercache wurde gelöscht, Web und jarvis-Instanz neugestartet, jedoch keine Änderung.

Das Problem tritt nur bei Chrome bzw. Edge (Chromium) auf, mit Firefox wird der Editor sofort gestartet.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2270
