### ISSUE TITLE
Kombinierte DateTimePickerAction, um eine Uhrzeit mit Datum angeben zu können

### ISSUE THREAD

**Issue by IobUser** [Zefau/ioBroker.jarvis#2352]
Mit den bestehenden Actions kann entweder eine Uhrzeit (TimePickerAction) oder ein Datum (DatePickerAction) ausgewählt werden.
Ich brauche die Auswahlmöglichkeit von Datum mit Uhrzeit.
Momentan habe ich das mit einer InputAction realisiert. Das ist für Touch-Devices etwas mühsam und es fehlt hier die Angabemöglichkeit einer Input-Mask (siehe Feature Request #438)
![image](https://user-images.githubusercontent.com/128219017/235493109-7d54adcf-0461-4976-8822-143fa737d414.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2175
