### ISSUE TITLE
v3.1.4-beta.18 / 19 Geräte-DPs können nicht mehr bearbeitet werden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2354]
Bei Änderungsversuch von Geräte-DP
![image](https://user-images.githubusercontent.com/84818934/235545259-093fe790-5490-4889-b8f9-4b3ba431bc67.png)

**Comment by Nonixnarrez** [comment]
Jau, eben auch gemerkt (v3.1.4-beta-19). Ergänzen/editieren über den "Expert Mode" funktioniert allerdings noch.

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
