### ISSUE TITLE
v3.1.4-beta.17/18/19 - StateList Secondary mit Geräte Label obwohl nicht definiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2355]
Woher kommt der Label `FritzDect` vom Gerät?
![image](https://user-images.githubusercontent.com/84818934/235546223-fb12320f-66a6-4abe-ac49-0940201a28e4.png)

StateList-Eintrag
![image](https://user-images.githubusercontent.com/84818934/235545846-b0982d11-48fe-4b1b-8038-0f5a750f7ca7.png)
WohnzimmerLinksBattery
![image](https://user-images.githubusercontent.com/84818934/235546009-d64606cf-a0eb-4762-ab1d-3a86d149dba3.png)
WohnzimmerRechtsBattery
![image](https://user-images.githubusercontent.com/84818934/235546043-e2a984d2-518d-4aec-a4be-83d19b6db528.png)
Wohnzimmer Rechts
![image](https://user-images.githubusercontent.com/84818934/235546134-fe8e9287-1abd-4743-bf98-f60868c16426.png)
WohnzimmerSollTemp
![image](https://user-images.githubusercontent.com/84818934/235546154-393b69c0-5653-4bab-ae22-4ab197f7584e.png)

**Comment by Zefau** [comment]
Label ergibt sich wie bekannt: State Label -> Device Label -> Device Name

**Comment by Zefau** [comment]
Ich reduziere mal auf State Label und danach nichts, oder?

**Comment by mcuiobroker** [comment]
Problem liegt ja darin, das in einem Label ein default definiert ist in den anderen aber gar nichts. Aus dem Nix macht er plötzlich ein Label?

**Comment by Zefau** [comment]
Die Version `v3.1.4-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.4-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
