### ISSUE TITLE
v3.1.4-beta.21: Binding Geräte Icon

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#2357]
Bis zur Version v3.1.4-beta.6 hat das folgende Binding im Geräte bei Icon immer funktioniert.
```
{
  "{smartmeter.0.1-0:16_7_0__255.value} > 0": "mdi-transfer-right `blink_red",
  "{smartmeter.0.1-0:16_7_0__255.value} < 0": "mdi-transfer-right transparent",
  "{smartmeter.0.1-0:16_7_0__255.value} == 0": "mdi-transfer-right transparent"
}
```
![grafik](https://user-images.githubusercontent.com/77939385/236286736-06e71fa3-095c-49b9-a2d6-d6c0624e7f10.png)

Jetzt wird dauerhaft ein HOME Icon angezeigt

![grafik](https://user-images.githubusercontent.com/77939385/236286872-2e27b90c-2be7-4d03-97ee-12ac5697899f.png)

**Comment by mcuiobroker** [comment]
Gibt es die Klasse denn?
`blink_red
Die Klasse ist eher "blink_red" ohne Graviszeichen?

**Comment by hosabeni** [comment]
Ja, die Klasse gibt es natürlich.  Das Graviszeichen war hier nur ein versehen bei der Eingabe. Im Screenshot ist ja nicht drin.
```
{
  "{smartmeter.0.1-0:16_7_0__255.value} > 0": "mdi-transfer-right blink_red",
  "{smartmeter.0.1-0:16_7_0__255.value} < 0": "mdi-transfer-right transparent",
  "{smartmeter.0.1-0:16_7_0__255.value} == 0": "mdi-transfer-right transparent"
}
```
```
@keyframes blink_red {
	0% {
		opacity: 0.2;
		color: transparent;
	}
	25% {
		opacity: 0.5;
	}
	50% {
		opacity: 1.0;
		color: #E91E63;
	}
	75% {
		opacity: 0.5;
	}
	100% {
		opacity: 0.2;
		color: transparent;
	}
}
```

**Comment by hosabeni** [comment]
Wenn ich diesen Datenpunkt als Binding Variable nutze funktioniert das mit der Klasse und dem keyframe.

![grafik](https://user-images.githubusercontent.com/77939385/236558284-cdfc1c5c-ec5f-470c-bc00-486754d50a8d.png)

![grafik](https://user-images.githubusercontent.com/77939385/236558407-43263b41-0e34-451b-aed5-b0ae59652657.png)

Wenn ich diesen Datenpunkt verwende geht beides nicht. 

![grafik](https://user-images.githubusercontent.com/77939385/236558608-42b27729-d131-424f-88b3-55cbc190c10b.png)

![grafik](https://user-images.githubusercontent.com/77939385/236559739-a6f64c00-e46c-4afc-bc6b-acc125e7e0c6.png)


Und der hatte bis `v3.1.4-beta.6 ` noch funktioniert. 

Hast du noch eine Idee?

**Comment by mcuiobroker** [comment]
Als Klasse funktioniert es bei mir, sonst leider nein, muss @Zefau sich anschauen.

**Comment by hosabeni** [comment]
Ich habe mir das nochmal angeschaut. 
Wenn ich einen Datenpunkt verwende der einen `:` enthält funktioniert das Binding an der Stelle nicht.
Zum Beispiel:
Das geht:
```
{
  "{0_userdata.0.Wert} > 0": "mdi-transfer-right blink_red",
  "{0_userdata.0.Wert} < 0": "mdi-transfer-right transparent",
  "{0_userdata.0.Wert} == 0": "mdi-transfer-right transparent"
}
```
Das nicht:
```
{
  "{0_userdata.0.Wert:Test} > 0": "mdi-transfer-right blink_red",
  "{0_userdata.0.Wert:Test} < 0": "mdi-transfer-right transparent",
  "{0_userdata.0.Wert:Test} == 0": "mdi-transfer-right transparent"
}
```

**Comment by Zefau** [comment]
@hosabeni besteht das Problem mit v3.2 noch?

**Comment by hosabeni** [comment]
Ja, ist noch aktuell mit 3.2 Beta 5.

**Comment by hosabeni** [comment]
Das Problem besteht bei der Version `3.2.0-beta.48` weiterhin. 

> Ich habe mir das nochmal angeschaut. Wenn ich einen Datenpunkt verwende der einen `:` enthält funktioniert das Binding an der Stelle nicht. Zum Beispiel: Das geht:
> 
> ```
> {
>   "{0_userdata.0.Wert} > 0": "mdi-transfer-right blink_red",
>   "{0_userdata.0.Wert} < 0": "mdi-transfer-right transparent",
>   "{0_userdata.0.Wert} == 0": "mdi-transfer-right transparent"
> }
> ```
> 
> Das nicht:
> 
> ```
> {
>   "{0_userdata.0.Wert:Test} > 0": "mdi-transfer-right blink_red",
>   "{0_userdata.0.Wert:Test} < 0": "mdi-transfer-right transparent",
>   "{0_userdata.0.Wert:Test} == 0": "mdi-transfer-right transparent"
> }
> ```

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.49` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.49` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by hosabeni** [comment]
Sieht gut aus.
Danke!
