### ISSUE TITLE
Connected to http://xxx.xxx.xxx.xxx:8400 Meldung deaktivierbar machen.

### ISSUE THREAD

**Issue by holofury** [Zefau/ioBroker.jarvis#2358]
Meldung taucht regelmäßig auf, wenn das Tablet geweckt wird.
Sinnvoller wäre, dass nur eine Meldung erscheint, wenn die Verbindung nicht hergestellt werden konnte.

Zumindest wäre eine Möglichkeit wünschenswert, die Meldung bei Bedarf abschalten zu können.

Siehe auch https://github.com/Zefau/ioBroker.jarvis/discussions/2353

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.68` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.68`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by holofury** [comment]
Toll! 👍 
Aber wo hast du das versteckt?
In der v3.2.0-beta.69 konnte ich dazu nichts finden?!

**Comment by Zefau** [comment]
Ist nun ein Button:

![grafik](https://github.com/user-attachments/assets/56793ea9-59fe-42f0-8a1b-3035906a300f)

**Comment by mcuiobroker** [comment]
Da der button aber ca 5- 7 Sekunden angezeigt wird, kann schon störend sein, gerade auf dem Handy. Insofern wäre ein Roter UnterStrich oder Umrahmung vielleicht besser?

**Comment by holofury** [comment]
Ach okay, hatte gehofft, dass du die Möglichkeit eingebaut hättest, die Meldung komplett zu deaktivieren.
Denn brauchen tu ich die Meldung eigentlich gar nicht.

**Comment by Zefau** [comment]
Ich will ungern für alles eine Option einbauen. Kann aber strategisch sonst gerne in die App gesamtheitlich in einen roten Rahmen packen (das meinst du doch @mcuiobroker ?)

**Comment by mcuiobroker** [comment]
Ja genau, es kam von einem User die Info, dass es störend ist, wenn die Anzeige auf dem Handy erscheint und somit bei ihm die Auswahl unmöglich macht.
Grundsätzlich reicht es bei der Anzeigezeit aber auch 2 Sekunden?

**Comment by holofury** [comment]
Schade.
Wofür braucht es denn die Meldung überhaupt bei jedem Einschalten?
Sprich wo ist der Mehrwert, dass man sie jedes Mal auftauchen muss?

**Comment by Zefau** [comment]
Für den initialen Connect nehme ich ihn raus. Mir geht es darum bei einem Reconnect anzuzeigen, dass jarvis nicht verbunden ist.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.70` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.70`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by holofury** [comment]
Perfekt, so gefällt es mir 👍
