### ISSUE TITLE
Internationalisation not working correctly

### ISSUE THREAD

**Issue by badenbaden** [Zefau/ioBroker.jarvis#236]
Hello! I have a problem. When I go to the jarvis page, I get a blank screen.

```
Uncaught RangeError: Maximum call stack size exceeded
    at parseFloat (<anonymous>)
    at Function.value (i18n.js:164)
    at Function.value (i18n.js:207)
    at Function.value (i18n.js:207)
    at Function.value (i18n.js:207)
    at Function.value (i18n.js:207)
    at Function.value (i18n.js:207)
    at Function.value (i18n.js:207)
    at Function.value (i18n.js:207)
    at Function.value (i18n.js:207)
```
![img-2020-10-23-10-05-07](https://user-images.githubusercontent.com/16225816/96966898-4f12df00-1517-11eb-8882-40517f079dbc.png)
![img-2020-10-23-10-06-16](https://user-images.githubusercontent.com/16225816/96966949-68b42680-1517-11eb-8ba9-a04b814a0590.png)

Web.0 settings:
![img-2020-10-23-10-06-57](https://user-images.githubusercontent.com/16225816/96967076-9600d480-1517-11eb-8c88-c23d59ac3c79.png)

socketio.0 settings:
![img-2020-10-23-10-07-57](https://user-images.githubusercontent.com/16225816/96967157-b761c080-1517-11eb-8372-8a5eaa0996ba.png)

What doesn't he like? How to fix it?

**Comment by Zefau** [comment]
Did you change any configuration? Which version are you running?

**Comment by Zefau** [comment]
@badenbaden should be resolved with `1.1.0-beta.48`. Could you test and verify?

**Comment by badenbaden** [comment]
Hello! Version 1.0.9 was installed. I installed version 1.1.0-beta 53 from the github. Everything also does not open, a blank screen. But new mistakes appeared. Here are the screenshots.

![jarvis](https://user-images.githubusercontent.com/16225816/97113795-ad011b80-16fd-11eb-80ac-8f503904c632.png)

![jarvis2](https://user-images.githubusercontent.com/16225816/97113803-b4282980-16fd-11eb-95f1-59c2664d2ec8.png)

**Comment by Zefau** [comment]
Could you share your layout (`jarvis.0.layout`) ? Please upload it to pastebin.com (with an expiration time) and post the password here.

**Comment by badenbaden** [comment]
it is empty, if I understood correctly what to put.
![jarvis3](https://user-images.githubusercontent.com/16225816/97115951-310dd000-170b-11eb-97d3-4e11e6b9686e.png)

**Comment by Zefau** [comment]
Ok, thanks for your patience. It was the i18n function for international languages. Should be resolved and working now with `v1.1.0-beta.54`.

**Comment by badenbaden** [comment]
Excellent! Now everything works. I will study further. Thanks!

**Comment by Zefau** [comment]
In case you are deciding for jarvis you could support by translating jarvis to your language (russian?). In that case, let me know and I will write a tutorial on how to translate.

**Comment by badenbaden** [comment]
Yes, it can be done with instructions. I don’t promise quickly, but I’ll try to help with this. And now it looks like this))
![jarvis4](https://user-images.githubusercontent.com/16225816/97118706-a59d3a80-171c-11eb-8a00-77bc29eaee57.png)

**Comment by Zefau** [comment]
Should not look like that. Should fall back to English. Thanks for reporting

**Comment by Zefau** [comment]
@badenbaden With `v1.1.0-beta.56` jarvis should correctly fall back to English if no translations are given for the detected language. Can you confirm that with your setup?

**Comment by badenbaden** [comment]
Hi. Now all in english. Thanks.
I noticed another bug. I connected from my phone, went to the jarvis page. As if something has loaded, but the screen is blank. I turned it over to portrait mode - everything appeared, but there is no setting button. Flipped back, again the screen is empty. Probably something with the markup.
