### ISSUE TITLE
Automatische Übersetzung vom Widgetnamen?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2361]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/03d65f66-c4e8-42ed-90c5-3806034c13bd)

**Comment by Zefau** [comment]
Die Version `v3.1.9-beta.2` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.9-beta.2` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
