### ISSUE TITLE
Nach Update auf Version 3.1.4 -> Fehler "Error: Verify Installation: Installation inconsistent"

### ISSUE THREAD

**Issue by hdering** [Zefau/ioBroker.jarvis#2369]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? 3.1.4 (Freigebene Version vom 18.05.2023)
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/3204979/54b8675c-24b5-4b4e-9ddf-d243319140fe)

(https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
Öffnet man Jarvis, sieht man die UI für 1-2 Sekunden, danach erfolgt der Fehler.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/3204979/ad6579d2-b849-44d2-b1b7-30acc77de004)

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by MiWoBln** [comment]
i can confirm that issue for 3.1.4, even with other objects. It makes no difference if i use Port 8082 or 8400. Both result in the above noted Error.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/83462355/b6f51499-311d-4e01-a381-345c3c75796a)

**Comment by teletapi** [comment]
Das gleiche Problem habe ich mit dem Update von 3.13 auf die3.14 ebenfalls

**Comment by Nonixnarrez** [comment]
+1

I (only) get the font decoding error after 3.1.4 (release) upgrade:

`index.html#/netzwerk0:1 Failed to decode downloaded font: http://192.168.178.245:8082/jarvis/assets/materialdesignicons-webfont.c1c004a9.woff2
OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/netzwerk0:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size`

Temporary remedy: Fallback to 3.1.4-beta.22 (worked for me),

Regards /// Noni

**Comment by StephanTexxpro** [comment]
+1

**Comment by Juicytronic** [comment]
> *Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker
> 
> 
> 
> **Prerequisites / Voraussetzungen**
> 
> - [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? 3.1.4 (Freigebene Version vom 18.05.2023)
> 
> - [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]
> 
> ![image](https://github.com/Zefau/ioBroker.jarvis/assets/3204979/54b8675c-24b5-4b4e-9ddf-d243319140fe)
> 
> 
> 
> (https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
> 
> 
> 
> **Describe the bug / Beschreibe den Fehler**
> 
> A clear and concise description of what the bug / problem is.
> 
> Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
> 
> Öffnet man Jarvis, sieht man die UI für 1-2 Sekunden, danach erfolgt der Fehler.
> 
> ![image](https://github.com/Zefau/ioBroker.jarvis/assets/3204979/ad6579d2-b849-44d2-b1b7-30acc77de004)
> 
> 
> 
> 
> 
> **Screenshots**
> 
> If applicable, add screenshots to help explain your problem.
> 
> Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
> 
> 
> 
> ____
> 
> 
> 
> **Please note that bug reports may be closed if the information above are not given!**
> 
> 
> 
> **Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**
> 
> 

Got the same error.
I did a backup then Uninstalled the adapter, reinstalled it and upload the backup. That worked for me.

**Comment by Crazyachmed** [comment]
How did you Backup/Restore? Using the Restore from backitup did not change anything (web adapter restarted)

**Comment by Nonixnarrez** [comment]
> How did you Backup/Restore? Using the Restore from backitup did not change anything (web adapter restarted)

Manually installing the last 3.1.4-beta.22 branch version via github was working fine for me.
- Switch on "expert mode" in ioBroker admin to enable installs from own/specific URLs
- Feed the cat in ioBroker admin with own/specific URL: https://github.com/Zefau/ioBroker.jarvis/tree/v3.1.4-beta.22

**Comment by vr6syncro** [comment]
That is not working for me.

Cant get it running even after downgrade to 3.0.9

**Comment by Zefau** [comment]
Die Version `v3.1.5` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.5` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by britta-hardung** [comment]
Ich hatte das gleiche Problem. Die Installation von der Beta Version aus dem github hatte schon geholfen.
Nach der schnellen Arbeit von @Zefau auch die 3.1.5 aus dem github installiert, ausprobiert und funktioniert für mich!
Danke für die schnelle Hilfe!

**Comment by StephanTexxpro** [comment]
3.1.5 funktioniert bei mir - thx!

**Comment by teletapi** [comment]
3.1.5 _>3.1.4 beta 40 fuinktioniert wieder lediglich der Kalender hat noch einen fehler. Danach noch die 3.1.8 installiert und geht ebendfalls hat aber den gleichen fehler im Kalender. Bin noch nicht sicher wo hier das Problem liegt

**Comment by mcuiobroker** [comment]
Versuch mal das / die Passwort(e) im Kalender neu zu setzen.

**Comment by teletapi** [comment]
Da hab ich kein Passwort vergeben
