### ISSUE TITLE
v3.1.5 wird als v3.1.3-beta.40 angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2370]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5d6002a5-469b-4890-9a31-8d5be4c5c3ef)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/43ccc09a-9506-4b4d-ab6f-c28a7e145fad)

**Comment by Nonixnarrez** [comment]
Jau, da hat sich in die package.json wohl die `"version": "3.1.3-beta.40"` eingeschlichen.

**Comment by Zefau** [comment]
Die Version `v3.1.6` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.6` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Leider nein.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/09bbdcfb-d63e-4136-acd3-a6c0c9913d39)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e9ad3b04-4f57-4d33-b924-67bc55f7c0d8)

**Comment by Zefau** [comment]
Die Version `v3.1.7` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.7` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
auch nicht.. oh man, kack Workflow

**Comment by mcuiobroker** [comment]
Leider nein.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0298ccef-b029-43b4-ad6e-d3f6d92f0380)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a5bae248-1940-45ce-be53-d4657cd42333)

**Comment by Zefau** [comment]
Die Version `v3.1.8` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.1.8` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6cc50318-10e0-4d89-a4f5-62025866223b)
