### ISSUE TITLE
v3.1.8 Fehler in Kalender-Anzeige

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2371]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/85ad02b0-5077-4623-8fe3-d2b0d63ff9aa)
undefined wird angezeigt.
Keine Fehlermeldung im Browser-Log.

https://forum.iobroker.net/topic/59201/jarvis-v3-1-x-just-another-remarkable-vis/835

**Comment by mcuiobroker** [comment]
Passt. Danke.

**Comment by aradhir** [comment]
Kurze Frage: Wenn ich es richtig sehe ist der Fehler in Version v3.1.9-beta.2 korrigiert worden. Gibt es schon ein release Datum für 3.1.9 oder 3.2.0?
