### ISSUE TITLE
Anzeigevariante: Leerer String wird nicht angezeigt

### ISSUE THREAD

**Issue by Rookiestyle** [Zefau/ioBroker.jarvis#2373]
v3.1.8 (betrifft auch ältere Releases)

Ich will den Text *Batterie schwach* sehen, wenn lowbat meiner Homematic IP Devices true ist.
Wenn das nicht der Fall ist, will ich nichts sehen

Anzeigevariante:
`{"true":"<span style=\"color:red;font-weight:bold;\">Batterie schwach<span>","false":""}`
Das zeigt mir im *false* Fall den Text *false*, also nicht das was ich will.
Ich finde es falsch, dass hier nicht "nichts" angezeigt wird.

`{"true":"<span style=\"color:red;font-weight:bold;\">Batterie schwach<span>","false":"x"}`
Das zeigt mir im *false* Fall den Text *x*, funktioniert also vom Prinzip her

`{"true":"<span style=\"color:red;font-weight:bold;\">Batterie schwach<span>","false":"<span></span>"}`
Das hat den gewünschten Effekt, fühlt sich aber nicht richtig an.

**Comment by Zefau** [comment]
Was passiert, wenn du ein Leerzeichen einfügst?

**Comment by Grizzelbee** [comment]
Habe hier das selbe Problem:
Wenn jemand im VPN Online ist (true/false), will ich den Text "Online" haben, sonst nichts.
Bei mir steht jetzt so aus:

Gerät:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/5459426/165b10c0-e1df-4e85-a4a9-36f99ee95063)

Widget:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/5459426/00bc462a-60f5-4294-b7cc-3ebf79dd4e22)


Output:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/5459426/000626d8-8cc2-42a9-b29a-962cecb470f6)


Wenn ich im Gerät `{"true":"Online","false":" "}` eintrage, werden die ausgegeben und man sieht nur noch die Kommas.

**Comment by mcuiobroker** [comment]
Besser ist
`{"true":"Online","false":""}`

**Comment by Grizzelbee** [comment]
@mcuiobroker 

> Besser ist {"true":"Online","false":""} -> es werden keine Kommas angezeigt

Das ist ja das, was ich im Screenshot stehen habe und was  dann zu `false, false, false` führt.
Mein letzter Satz war nur eine Variante (die ja auch schon weiter oben diskutiert wurde), die dann aber auch zu unerwünschten Ergebnissen führt - da habe ich keinen Screenshot mehr zu gemacht.

**Comment by Grizzelbee** [comment]
Ändert nichts:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/5459426/4b011062-790a-40b3-8324-c859a0bd591e)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/5459426/b80faefd-c3c4-4c45-b23c-50a6e74b8406)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/5459426/c391448e-d6d0-4f8c-9922-70784ee1a99c)

Mir fällt gerade noch etwas kurioses auf: Beim Obersten Eintrag stimmt die Anzahl der secondary state mit den `false` überein - unten nicht. Da "fehlt" ein `false`.

**Comment by mcuiobroker** [comment]
Sind auch alle DPs echte boolean?

**Comment by Zefau** [comment]
@Rookiestyle @Grizzelbee @mcuiobroker besteht das Problem mit v3.2 noch?

**Comment by Grizzelbee** [comment]
@Zefau 

Habe das gerade mal getestet und für mich sieht das sehr gut aus. Würde also sagen: `Fixed!`

**Comment by Rookiestyle** [comment]
Auch wenn's schon closed ist: Funktioniert bei mir auch, danke
