### ISSUE TITLE
Fully-Browser: Undefined DP

### ISSUE THREAD

**Issue by neo-licious** [Zefau/ioBroker.jarvis#2374]
Hallo,

seit dem Update auf 3.1.8 werden alle DP im Fully-Browser als "undefined" angezeigt. Cache leeren hat nichts geholfen.

In Chrome wird alles normal dargestellt.

**Comment by mcuiobroker** [comment]
Wie sieht der DP jarvis.0.widgets aus?
Evtl, die widgets zurücksichern.

**Comment by neo-licious** [comment]
Läuft auf 2 Tablets. Eins mit Fully v1.50.4-play und eins mit v1.46-fire. Neustart hat bei beiden leider nichts geholfen.

**Comment by mcuiobroker** [comment]
Kannst du mal ein Bild davon reinstellen, damit man einen Eindruck bekommt?

**Comment by holofury** [comment]
Ich kann das Problem bestätigen.
Tritt bei allen Versionen >3.1.3 auf, ein Downgrade behebt das Problem.
Darstellung in anderen Browsern auf dem gleichen Tablet ist korrekt.
Nur beim FullyBrowser kommen statt den entsprechenden Werten nur "undefined".

**Comment by neo-licious** [comment]
![20230523_191253](https://github.com/Zefau/ioBroker.jarvis/assets/80536993/a5e627bd-7c3a-41ea-9752-e780d590680d)

Es liegt vermutlich an der Webview version. Es handelt sich bei beiden Tablets um Amazon Fire HD 10 aktuell mit Amazon System Webview v84-4147.

**Comment by holofury** [comment]
Wenn es am WebView liegen sollte, müsste das Ergebnis in jedem Browser das gleiche sein, oder?
Ein Upgrade der WebView Version (bei mir von Huawei) hat bei mir keine Änderung gebracht.

**Comment by mcuiobroker** [comment]
Amazon Fire7 Tab(9.Generation) mit Webview v106 läuft auch.

**Comment by Bernd9000** [comment]
Schaut doch mal ob der entsprechende Client im jarvis IOB Datenpunkt auftaucht.

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/fb9389ea-afcb-4088-bff5-e0ef47cc30ed)

**Comment by neo-licious** [comment]
Erstmal Danke für eure Lösungsvorschläge.

@Bernd9000 : Die Clients wurden im IOB entsprechend angezeigt. 

Übers Handy lief es auch normal mit Android WebView V113. 

Zum Test habe ich eins der Tablets auf die neuste FireOS bzw. WebView V104-fire geupdatet, Damit ist die Darstellung im Fully nun wieder korrekt.

**Comment by mcuiobroker** [comment]
Kann es dann zu?

**Comment by holofury** [comment]
Bei mir ist das Problem noch aktuell.
Wenn es aber an Huawei WebView liegt und es hier keine Lösung für mich gibt, kann das Thema zu :-(

**Comment by mcuiobroker** [comment]
Kannst du nicht eine "google"-Webview installieren?

**Comment by holofury** [comment]
Hab den Android System WebView installiert, kann diesen aber in den Entwickleroptionen nicht aktivieren - dort gibt es nur den Huawei WebView als Option.

Die Huawei WebView Version ist 11.1.5.322 und es gibt aktuell kein Update.

Wo gibt es den aus deinem Screenshot?

**Comment by holofury** [comment]
Download gefunden, bringt aber keinen Unterschied zu der anderen Version von Android System WebView, die ich vorher installiert hatte.

**Comment by peer69** [comment]
Gleiches Phänomen hier mit einem Samsung Family Hub mit TizenOS. Downgrade auf 3.1.3 löst auch dort das Problem.

**Comment by Krausb3rt** [comment]
> Gleiches Phänomen hier mit einem Samsung Family Hub mit TizenOS. Downgrade auf 3.1.3 löst auch dort das Problem.

Moin Leute, bei mir leider auch. Habe gestern das Update von Jarvis auf 3.1.8 gemacht. Mit der Version und dem Samsung Family Hub auf meinem Kühlschrank mit aktuellem TizenOS und Browser habe ich das gleiche Phänomen. Leider hat man dort keinen Einfluss auf die WebView Version, sodass momentan die einzige Abhilfe anscheinend ein Downgrade von Jarvis auf 3.1.3 ist.

**Comment by stony2k** [comment]
Gleiches Problem hier seit dem Update auf Jarvis 3.18 mit dem FireHD 10 (11. Gen) Tablet und dem Fully Kiosk Browser in der Version 1.53. Habe im Google Play Store die Android Web View installiert, allerdings hat das auch nach einem Neustart nicht geholfen. In den Entwickleroptionen kann man nur die Amazon Web View auswählen.

**Comment by schneie** [comment]
Und auch bei mir das gleiche Problem - älteres Hanspree Tablet funktioniert nicht mehr nach dem Update auf 3.1.18.
Ich habe allerdings jetzt auch das Problem , dass nach dem Downgrade meine Pro-Version nicht mehr erkannt wird. All Neustarts und Rücksetzungen nützen nichts. Muss ich beim Downgrade irgendetwas besonderes beachten?
@Zefau: Bist du an einem Fix dran?

**Comment by mcuiobroker** [comment]
Du bist jetzt wieder auf 3.1.2? Hast du mal die PRO neu in den DP gesetzt?

**Comment by schneie** [comment]
Auf 3.1.18 funktioniert die Pro wieder, sobald ich downgrade (3.0.9 und darunter) kann ich keine Pro aktivieren. Felder sind gesperrt und ich bekomme nur Fehlermeldungen...
Auf meinem Uralt-Tablet läuft noch Android 4.4 :-D Was soll ich sagen bisher hat es eben funktioniert... Befürchte fast nach 8 Jahren muss ein Update her ;-)

**Comment by lolmeister77** [comment]
Ich habe das gleiche Problem mit einem alten ipad mini. Nur ein Downgrade auf 3.1.3 hat geholfen.
Das Gerät ist an sich gut für ein kleines Dashboard geeignet. Wäre Schade es dafür nicht verwenden zu können.

**Comment by Zefau** [comment]
besteht das Problem mit v3.2 noch?

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/fragen-probleme-v3#v3.2.0-alpha.xx-fully-kiosk-browser-zeigt-keine-widgets-an

**Comment by Krausb3rt** [comment]
Hi @mcuiobroker , der Hinweis mit dem Fully Kiosk aus dem issue #2525 war gut, hättest deinen Beitrag nicht löschen müssen ;) Ich habe den Cache bzw. die Daten des Tizen Browsers gelöscht, jetzt ist alles schick.

@Zefau : Es funktioniert wieder alles, keine undefined Datenpunkte mehr.

Einziger Nachteil beim Löschen der Daten aus dem Browser ist, dass man danach die Lesezeichen wieder eintragen muss... Danke für die Hinweise und Tipps.

**Comment by mcuiobroker** [comment]
Dann kann der Issue zu?
