### ISSUE TITLE
Widget AdapterLogs (Mulithost) I Es werden die Werte von Slave-Host nicht angezeigt

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#2381]
Hallo! Bin mir nicht sicher, ob es ein Bug ist. v3.1.2

Ich habe einen Master und Slave als Mulithost im Einsatz. Jarvis ist auf dem Master installiert inkl. Instanz. 
Auf dem Slave ist kein Jarvis installiert. Admin ist installiert, aber ohne Instanz.

Alle Adapter (Master und Slave) werden in der Jarvis-Konfig. zur Selektion im Widget angezeigt. Jedoch kommen nur Werte von Master inkl. Updates. 

Wie bekomme ich auch die Slave-Werte angezeigt?
Muss ich ggf. auch im Slave etwas installiert?

**Comment by Zefau** [comment]
@bambi-arch ist das hier mit v3.2 noch aktuell?

**Comment by bambi-arch** [comment]
Funktioniert jetzt, Danke
