### ISSUE TITLE
v3.1.9-beta.2 und vorher?? Man kann kein MAP-Widget mehr erstellen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2383]
Wählt man das Modul MAP aus erscheint eine leere Seite.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/361b2521-9d26-46e3-96bd-eb8ceeadba85)

siehe auch
https://forum.iobroker.net/topic/66115/jarvis-map-widget

**Comment by SKB-CGN** [comment]
Ah, diesen Fehler habe ich auch.

**Comment by mcuiobroker** [comment]
Kann man umgehen:
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/fragen-probleme-v3#map-kann-nicht-angelegt-werden-bzw.-leere-seite-wird-angezeigt

**Comment by SKB-CGN** [comment]
Das klappt bei mir leider mit der Version 3.1.3 nicht.

**Comment by Zefau** [comment]
@mcuiobroker @SKB-CGN ist das hier mit v3.2 noch aktuell?

**Comment by mcuiobroker** [comment]
Kein Fehler mehr
