### ISSUE TITLE
Reverse Proxy nach Update von 3.1.2 auf 3.1.8

### ISSUE THREAD

**Issue by rschneider1509** [Zefau/ioBroker.jarvis#2384]
@domi1893 Ohne Umstellen von Einstellungen den Reverse-Proxy auf Port `8400` konfigurieren.

_Originally posted by @Zefau in https://github.com/Zefau/ioBroker.jarvis/issues/1602#issuecomment-1407490412_

Hallo zusammen,
mit der 3.1.2 hat das mit dem Port 8400 bisher problemlos funktioniert.
Nachdem ich heute auf 3.1.8 aktualisiert habe, läuft meine Verbindung nicht mehr :D 
Ich hatte auch die ganze zeit den web.0 auf AUS, da es via :8400 ohne den Web Adapter lief. Mit der 3.1.8 benötige ich den web.0 definitiv wieder - aber von extern werde ich ständig auf die interne ip:8082 weitergeleitet, die natürlich nicht funktioniert.
Jemand das gleiche Problem oder ne idee?
Ich teste nochmal, die Einstellung von der 8400 auf die 8082 zu stellen.

**Comment by rschneider1509** [comment]
Ich muss dich enttäuschen - es ging sporadisch wieder und ich dachte mein Post wäre unnötig. Dann habe ich ihn geschlossen und es ging wieder nicht. 
Meine Zeit und Lust war zu dem Zeitpunkt begrenzt und ich bin zurück auf die 3.1.2, auf der ich mich bisher ausruhe :(
Ich warte auf das nächste Update und hoffe, dass es dort funktioniert :D ...

Triggert mich aber leider auch, dass ich auf ner alten Version hänge...

**Comment by only4joy** [comment]
Danke für deine Antwort. Ich bin leider nur so ein Prosumer was solche Dinge betrifft, die Frage wäre @Zefau können wir dich irgendwie unterstützen das Problem zu lösen? Wie bei rschneider funktioniert es bei mir seit dem Upgrade von 3.1.2 nicht mehr...

**Comment by Martin4us3** [comment]
Sorry, dass vielleicht habe ich etwas in den umfangreichen Chats übersehen.

Gibt es mittlerweile eine Lösung Jarvis mithilfe eines Revers-Proxies - nach außen - ausschließlich über Port 80 zu erreichen?

**Comment by Zefau** [comment]
Mit v3.2 auf Port `8400`

**Comment by only4joy** [comment]
Hi @Zefau 
Kann bestätigen, dass es mit v3.2 beta54 funktioniert -danke dir!
Dafür gehen bei mir jetzt die histographen nicht mehr, ist das ein bekannter Fehler? Passiert unabhängig vom Reverse Proxy oder Direktzugriff. Habe unter den Issues nichts dazu gefunden:
![grafik](https://github.com/user-attachments/assets/589e0598-3bd7-48e5-9cb4-3b0b694ab4bd)

**Comment by Zefau** [comment]
@only4joy HistoryGraph sollte wieder funktionieren, sonst bitte ein eigenes Issue öffnen.
