### ISSUE TITLE
Import hue-extendend funktioniert nicht mehr mit beta47

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#239]
![image](https://user-images.githubusercontent.com/73311538/97059654-4d85fd00-1591-11eb-98ee-1512c594f0e7.png)
![image](https://user-images.githubusercontent.com/73311538/97059671-5676ce80-1591-11eb-8eec-4f145bd5d811.png)

**Comment by Timmes123** [comment]
es waren keine neuen geräte zu finden

**Comment by Timmes123** [comment]
ich habe zum test geräte gelöscht und wollte diese neu einfügen.
Funktioniert trotzdem nicht

**Comment by Zefau** [comment]
should be resolved with `1.1.0-beta.48`. Could you test and verify?

**Comment by Timmes123** [comment]
getestet mit beta48

![image](https://user-images.githubusercontent.com/73311538/97081878-b73fee80-1605-11eb-8b34-754fce35c962.png)

funktioniert leider nicht

**Comment by Zefau** [comment]
Wie viele Geräte hast du drin? Hast du unter `lights`, `groups` oder `sensors` ein Gerät ohne den Datenpunkt `name` ? Scheinbar findet er bei einem Gerät den Namen nicht und bricht ab.

Versuch mal die `1.1.0-beta.50`, ob es damit passt.

**Comment by Timmes123** [comment]
getestet mit beta50

![image](https://user-images.githubusercontent.com/73311538/97082776-78616700-160c-11eb-9b69-ed1e483d935c.png)

du hast recht

![image](https://user-images.githubusercontent.com/73311538/97082824-c2e2e380-160c-11eb-997a-73666553e1b9.png)

ich habe die schlafzimmer lampen und gruppen in der hue App gelöscht, da nicht mehr vorhanden

muss ich das hier evtl anders einstellen?

![image](https://user-images.githubusercontent.com/73311538/97082861-00477100-160d-11eb-9b44-ea119265832b.png)

**Comment by Timmes123** [comment]
hab die ordner für gruppe und licht der gelöschten geräte aus dem adapter gelöscht,
jetzt geht der import auch wieder

**Comment by Zefau** [comment]
Ich hab noch ein paar Sachen geändert und hoffe, dass der Fehler trotzdem nicht mehr vorkommt.
