### ISSUE TITLE
v3.1.9-beta.2 HomeKit Tile Background

### ISSUE THREAD

**Issue by ScumbagSteve** [Zefau/ioBroker.jarvis#2392]
Wie im [mcuiubroker gitbook](https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/module/homekittile#senderbuttons-erstellen) beschrieben habe ich SenderButtons über HomeKit Tile mit Background erstellt: 
`
.jarvis-widget-46016a23-5155-4692-933e-eafee37e8f98 .HomeKitTile {
	background: no-repeat center/80% url("http://192.168.178.89/download/bilder/NDR2.png");}`

Seit Update auf 3.1.9-beta2 werden die Hintergründe nicht mehr angezeigt.

Downgrade von 3.1.9-beta2 scheint auch nicht zu funktionieren, denn anschließend wird meine Konfiguration nicht mehr korrekt geladen.

**Comment by mcuiobroker** [comment]
Anscheinend hat sich eine Klasse geändert:
```
.jarvis-widget-46016a23-5155-4692-933e-eafee37e8f98 .jarvis-HomeKitTile-Container{ 
   background: no-repeat center/80% url("http://192.168.178.89/download/bilder/NDR2.png");
}
```

**Comment by ScumbagSteve** [comment]
Danke, das hat das Problem behoben!
