### ISSUE TITLE
Tausender Trennzeichen und Nachkommastellen

### ISSUE THREAD

**Issue by tschortschde** [Zefau/ioBroker.jarvis#2395]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/2394

<div type='discussions-op-text'>

<sup>Originally posted by **tschortschde** July 11, 2023</sup>
Wer kann mir bitte sagen, wie der Code für die Datenpunkt Eigenschaften des Gerätes lautet, wenn man das Tausender-Trennzeichen und keine Nachkommastellen für einen Wert haben möchte? 
Ich suche speziell für die Helligkeitsanzeige: Der Wert "2000.75" soll gerundet folgendes Format haben: "2.001" 

</div>

Wäre echt super, wenn das implementiert werden könnte ;-)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2459
