### ISSUE TITLE
Support for nodejs 20

### ISSUE THREAD

**Issue by lamium2** [Zefau/ioBroker.jarvis#2396]
Under nodejs 20 you can install the adapter but not add an instance:

Invalid version of node. Required ^18 || ^16 || ^14.19. Current 20.4.0

**Comment by gwse** [comment]
Wir Empfehlen: Node.js 20.x :-)
https://forum.iobroker.net/topic/74831/wir-empfehlen-node-js-20-x
now node js is recommended so it should be supported as well, what do you think?

**Comment by mcuiobroker** [comment]
It works with nodejs 20.
