### ISSUE TITLE
Importierte Shelly Geräte werden nicht angezeigt.

### ISSUE THREAD

**Issue by Reto84** [Zefau/ioBroker.jarvis#2399]
Hallo zusammen,

**Prerequisites / Voraussetzungen**
- Jarvis 3.1.2 auch gleiches verhalten bei 3.1.19 Beta 2
- Admin 6.3.5
- Node.js v16.19.1 auch gleiches verhalten bei v18.16.1

**Describe the bug / Beschreibe den Fehler**
Ich möchte neu hinzugefügt Shelly Geräte in Jarvis importieren. Das hat mal ganz normal funktioniert. Jedoch sind diese dann aber nicht bei den Geräten verfügbar. Wenn ich nochmal importieren möchte, werden die neuen Gerät angezeigt als schon hinzugefügt:
<img width="503" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/81419898/a7338a9c-5150-4e75-9fef-2e5314b1645c">

<img width="485" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/81419898/6417c247-40b6-405b-8311-00ecdac2761a">

Ich habe sie dann probiert nochmal zu importieren:
<img width="498" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/81419898/56a14d79-ab75-4717-8f46-68a17fada76c">

das hat auch nichts gebracht.
(Adapter und Iobroker wurden schon neu gestartet)

Danke&Gruss 
Reto
____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Reto84** [comment]
Die Geräte sind nun "plötzlich" in Jarvis ersichtlich. Hat sich also erledigt.

Danke&Gruss Reto

**Comment by mcuiobroker** [comment]
Irgendetwas am System geändert? Updates?
