### ISSUE TITLE
HmIP-SWDO-2 wird nicht erkannt

### ISSUE THREAD

**Issue by mafris** [Zefau/ioBroker.jarvis#2400]
Hallo zusammen,
leider wird ein bei mir eingesetzter Homematic IP SWDO2 nicht erkannt.
Sollte der Sensor von Jarvis erkannt werden? 
Update des Adapters auf 3.1.9-beta2 brachte keinen Erfolg.

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du?                             v3.1.9-beta.2

![image](https://github.com/Zefau/ioBroker.jarvis/assets/139545571/e3b9b624-353d-4a54-9810-9ee8ba4c8641)

**Screenshots**
Screenshots aus dem iobroker des Sensors:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/139545571/ae9084a5-2225-4e84-b765-a7229761c190)

**Comment by Zefau** [comment]
@mafris
