### ISSUE TITLE
influxdb.0 not reachable!

### ISSUE THREAD

**Issue by Trrw** [Zefau/ioBroker.jarvis#2401]
Hallo,

ich benutze die Jarvis Version v3.1.8 (Pro).
Dabei habe ich das Problem, dass meine Graphen (influxDB 2) ab und zu nicht geladen werden können. Dies betrifft alle Graphen also nicht nur wie im Beispiel bei den Temperaturen. Das Ganze sieht so aus:

<img width="1084" alt="Bildschirmfoto 2023-07-15 um 23 09 08" src="https://github.com/Zefau/ioBroker.jarvis/assets/24519230/220c33ef-303a-4205-9d18-35ccdfdfb5d5">

Im Log von Jarvis (Debug) erscheint folgendes:
<img width="1730" alt="Bildschirmfoto 2023-07-15 um 22 58 05" src="https://github.com/Zefau/ioBroker.jarvis/assets/24519230/3c8c00f8-55fa-4128-ab8c-7b7740abdd66">
<img width="1707" alt="Bildschirmfoto 2023-07-15 um 22 57 52" src="https://github.com/Zefau/ioBroker.jarvis/assets/24519230/c6e988e5-d880-4029-ba99-291e890dc7e8">
<img width="1720" alt="Bildschirmfoto 2023-07-15 um 22 57 33" src="https://github.com/Zefau/ioBroker.jarvis/assets/24519230/a4cb1e75-aad0-4043-8654-0fb852dc68ef">

Im Log von influxDB 2 erscheint nichts, wenn der Fehler auftritt. Die influxDB läuft in einem anderen Container in Proxmox als der ioBroker. 

Ich habe das mit Firefox/Chrome/Safari getestet. Bei allen drei Browsern erscheint regelmäßig die Meldung, dass keine Verbindung besteht. Das Löschen des Cache hilft nicht. 
Wenn der Fehler auftritt, reicht es meist, die Seite einmal zu aktualisieren.

**Comment by Zefau** [comment]
@Trrw ist das mit v3.2 noch aktuell?

**Comment by Trrw** [comment]
Ich benutze immer noch die stabile v3.1.8, habe aber zwischenzeitlich ein Systemupgrade gemacht (schnelle Hardware). Der Fehler ist bei mir nicht mehr aufgetreten. Daher vermute ich, dass es an der Hardware liegt (Ladezeiten).
