### ISSUE TITLE
Theme Farbe Einstellungen

### ISSUE THREAD

**Issue by tschortschde** [Zefau/ioBroker.jarvis#2402]
Hallo durch das anpassen der Theme Einstellungen sind auch im Backend die Bereiche nicht mehr lesbar.
Wie kann ich das am einfachsten / besten lösen?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/11274233/64ee6cf5-f2df-4f37-b289-c630391f1f0d)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/11274233/c8b66dc6-88ea-421b-a62f-f69c64b95918)

**Comment by mcuiobroker** [comment]
Primärfarbe wird ja für bestimmte Anzeigen fest genutzt, auch für den Hintergrund von Widgets im Layout. Dies ist vorher zu bedenken, wenn man diese Globalen-Farben anpasst.
Was möchtest du eigentlich erreichen? Was soll denn in welcher Farbe zu sehen sein?

**Comment by tschortschde** [comment]
Ich möchte alle Icons in der Farbe weiß haben. 
wie setze ich das um?

**Comment by mcuiobroker** [comment]
```
.jarvis-icon {
	color: white!important;
}

.jarvis-icon svg {
	color: white!important;
}
```

**Comment by mcuiobroker** [comment]
red!important

**Comment by tschortschde** [comment]
Danke!

**Comment by tschortschde** [comment]
Wie kann ich die runden Buttons in einer anderen Farbe darstellen?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/11274233/c226b227-476b-4815-8daf-b748bab01ec0)

Muss ich es so machen, aber wo füge ich den Code in den Styles ein?

.text-primary {
    color: #d2193a!important;
}

**Comment by mcuiobroker** [comment]
Dort kann man die Farbe nicht so leicht ändern. Man müsste dort bei dem Button-Element die Klasse wechseln, z.B. text-primary -> text-red. Dort gingen dann auch nur die namedColors. Aber dafür gibt es noch kein Programm, mit dem man das machen könnte.

**Comment by mcuiobroker** [comment]
Hat sich dann erledigt?

**Comment by tschortschde** [comment]
Ja, hat sich erledigt; 
Vielen Dank für die Unterstüzung!
