### ISSUE TITLE
Blind Level Farbanpassung

### ISSUE THREAD

**Issue by tschortschde** [Zefau/ioBroker.jarvis#2406]
Dort kann man die Farbe nicht so leicht ändern. Man müsste dort bei dem Button-Element die Klasse wechseln, z.B. text-primary -> text-red. Dort gingen dann auch nur die namedColors. Aber dafür gibt es noch kein Programm, mit dem man das machen könnte.
Ausser du änderst die primary-Farbe, dann zeigt es in der Farbe an.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c7ade146-12b6-4ca4-b082-d8112cbcf7ad)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/2402#issuecomment-1646795821_

Wäre es möglich das umzusetzen, die Buttons der Blind Levels anzupassen?

**Comment by mcuiobroker** [comment]
Versuch es mal so:
```
.BlindLevelAction .q-btn {
	border: 1px solid red !important;
	color: transparent!important;
	/* #1976d2*/
}

.mdi-chevron-up,
.mdi-chevron-down,
.mdi-stop {
	border-color: transparent! important;
	color: red;
}
```

**Comment by tschortschde** [comment]
Hat leider nicht funktioniert ;-(

**Comment by mcuiobroker** [comment]
Dann hast du nicht v3.1.9-beta.2 im Einsatz?

**Comment by tschortschde** [comment]
Nein, noch nicht...
Ich probiere es aus und gebe Bescheid😉

**Comment by tschortschde** [comment]
Jetzt hat es funktioniert,
die .mdi-chevron-down und .mdi-chevron-up waren 2x definiert ;-(
Herzlichen Dank.
