### ISSUE TITLE
Schalter Entwicklung 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2409]
Bitte in die Einstellungen und auch iobroker-Objekte einen Schalter setzen, mit dem man die Auswirkungen von Styles und Scripts entfernen kann.
Somit kann man schneller testen, ob ein Problem mit den Einstellungen von Styles oder scripts zusammenhängt.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.6` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.6`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
- Kein Automatischer Reload / nur mit F5
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9ca6ef2c-7b68-4daa-823b-3319bdb5b0f1)

- Scripts und Styles eingeschaltet werden aber nicht angezeigt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/91ec0931-a43f-46c9-ba81-cd64cce73d35)
Bleibt Standard

**Comment by mcuiobroker** [comment]
Wenn man in die Konfiguration geht baut sich sich der Speicherbedarf plötzlich auf.


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5cee5b52-d449-4d14-b22f-b9c2a4ae7cff)

1 min später


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6c1f9486-cfec-4960-a6b6-a2577baf443e)

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.7` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.7`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
v3.2.0-alpha.30 Passt. Danke.
