### ISSUE TITLE
Subtabs

### ISSUE THREAD

**Issue by kaip2503** [Zefau/ioBroker.jarvis#241]
Es wäre schön, wenn es die Möglichkeit von Subtabs geben würde. Also ich klicke auf den Tab und bekomme dann unter der Tabbar die Subtabs angezeigt

**Comment by Zefau** [comment]
Ist das notwendig, wenn ein Drawer implementiert wird? Siehe https://github.com/Zefau/ioBroker.jarvis/issues/81

**Comment by kaip2503** [comment]
Ein drawer wäre wohl sogar die bessere Wahl, um auf Tablets etwas mehr Platz für den Content zu haben.
