### ISSUE TITLE
v3.1.9-beta.2 jsonTable format mit date -> Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2412]
Hintergrund
https://forum.iobroker.net/topic/67243/jarvis-v3-1-9-beta-2-json-table-inhalte-ts-in-datum/4

Beispiel-Parameter:
`[{"field":"threadTime","format":"val => val = date(val,'dd.MM.yyy HH:mm')"}]`

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/09d88b43-03af-4d47-97c4-104b05ce68fe)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/b4a4c912-485e-403f-a309-61174e999f31)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9afba04e-99e2-469c-a737-9319ee2c32df)

**Comment by Zefau** [comment]
@mcuiobroker ist das hier noch aktuell?

**Comment by Zefau** [comment]
jDate? Hatten wir hier schon was gemacht? Kann mich gerade nicht erinnern.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2457

**Comment by mcuiobroker** [comment]
`"format": "val => val = jDate(val,'dd.MM.yyy HH:mm')"`

**Comment by Zefau** [comment]
Jo, ok, da je für den reminder.

Laut code dasselbe wie
```
"format": "val => val = date(val,'dd.MM.yyy HH:mm')"
```

**Comment by mcuiobroker** [comment]
Funktioniert mit jDate.
