### ISSUE TITLE
Calender zeig undefined

### ISSUE THREAD

**Issue by Powerbolt1989** [Zefau/ioBroker.jarvis#2414]
Hallo Zusammen,

mein Calender zeigt mir oben in der Leiste undefined undefined für Monat ud Jahr an. Wie bekomme ich das hin das er mir wieder die normalen Werte anzeigt?

Version 3.1.8

![image](https://github.com/Zefau/ioBroker.jarvis/assets/78702305/6f070337-18b3-4bb2-803a-a495aa381eed)

**Comment by Powerbolt1989** [comment]
Hallo @mcuiobroker 

hab ich gemacht. 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/78702305/6e44cf08-309a-4f51-8696-e3efa939e5cd)
Leider kein Erfolg.
Iobroker ist nun auch auf dem neusten Stand. 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/78702305/b6a37394-1211-41a6-bc7c-4d63552fb448)

**Comment by Powerbolt1989** [comment]
Hallo @mcuiobroker ,

hat doch geholfen war zu ungeduldig. Jetzt passt es wieder. Danke für den Hinweis!

**Comment by KaJu99** [comment]
die beta steht allerdings nicht im Beta-Repository zur Verfügung sondern muss manuell installiert werden; die letzte Stable-Version ist 3.1.8; der Kalender-Bug besteht damit nun erstaunlich lange, es wäre gut, wenigstens das Beta-Repo entsprechend zu aktualisieren. Danke
