### ISSUE TITLE
Aufruf nicht möglich - State with ID jarvis.0.devices is not a valid state

### ISSUE THREAD

**Issue by sethpandor** [Zefau/ioBroker.jarvis#2417]
Ich nutze Jarvis 3.1.8 als Pro User.

Vor einiger Zeit hatte ich schon mal das nachfolgend geschilderte Problem, das ich nun auch aktuell wieder habe.

ioBroker läuft bei mir in Proxmox 8 als VM.

Jarvis kann ich aktuell nur aus dem Link in ioBroker aufrufen. Bei einem Aufruf über meine Lesezeichen oder per URL erhalte ich folgende Fehlermeldung:
![SCR-20230812-fof](https://github.com/Zefau/ioBroker.jarvis/assets/36777771/f9d51a35-ef02-4a92-9e2f-b79581638b36)

Wo setze ich mit der Fehlersuche an?
Den Hinweis hier https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/fehler-hinweise-v3-v3.1#error-xhr-poll-error kenne ich. Nutze jedoch keine sichere Verbindung.

An Browsern habe ich so ziemlich alles durchgetestet (Safari, Chrome, Firefox, Opera) und alles auch an zwei Macs sowie direkt in der VM (Debian / Safari) getestet.

In der Konsole von Safari (und Chrome) liefert er folgende Fehlermeldung:

![SCR-20230812-ghe](https://github.com/Zefau/ioBroker.jarvis/assets/36777771/0bd41139-96d7-42f1-b092-b9a943cf5b1b)

Einstellungen in Jarvis 
![SCR-20230812-fac](https://github.com/Zefau/ioBroker.jarvis/assets/36777771/9d050512-c49d-4392-96c1-e3193ab3341f)

und web.0

![SCR-20230815-p3n](https://github.com/Zefau/ioBroker.jarvis/assets/36777771/4f1ed3c6-240a-4abf-86aa-5c0b6f17dc14)

Für eine Hilfestellung wäre ich dankbar. Ich kann kein singuläres Ereignis/eine Handeln von mir ausmachen, seitdem der Fehler auftritt.

**Comment by Zefau** [comment]
@sethpandor sorry für die späte Reaktion. Besteht das Problem noch?

**Comment by Zefau** [comment]
@sethpandor
