### ISSUE TITLE
Manually trigger Socket reconnect...

### ISSUE THREAD

**Issue by disaster123** [Zefau/ioBroker.jarvis#2418]
Hi,

i'm running the pro version and want to add a custom script, which forces to reconnect the websocket. But there seem no function call to reconnect the websocket. If i manually call
window.Socket.disconnect()

no new connection is initiated.

Greets,
Stefan

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.1` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.1`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Zefau** [comment]
Ab v3.2 versuch mal mittels `reconnect()`

**Comment by disaster123** [comment]
Funktioniert leider nicht.

Ich habe folgende PRobleme:
1.) mein Chromium Fenster unter Linux stirbt quasi seit Alpha 3.2 - das Fenster wird ganz schnell unresponsive - Ursache keine Ahnung

2.) ich erhalte folgende Fehlermeldung:
```18:00:13.598 | WARN | SOCKET | Failed to execute 'send' on 'WebSocket': Still in CONNECTING state. ```

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.54` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.54`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by disaster123** [comment]
Also erneut window.Socket.reconnect(); versuchen?

**Comment by Zefau** [comment]
Jo
