### ISSUE TITLE
Min / Max not used in Action Element InputAction

### ISSUE THREAD

**Issue by manoloxxl** [Zefau/ioBroker.jarvis#2420]
**Prerequisites / Voraussetzungen**
nodejs v18.15.0
Jarvis 2.2.5 (shown in iobroker), 2.2.4 (shown in jarvis help)

I have configured a device to set water temperature with an InputAction Element with a min 30° and a max 36°:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/25949606/89d7fecd-fd0e-4708-861c-924db30e82e8)

**Describe the bug / Beschreibe den Fehler**
The Bar is working fine, i can just choose between 30 - 36. But i can click into the number at the right side and can use any value.
The value is saved and written when i click "close":
![image](https://github.com/Zefau/ioBroker.jarvis/assets/25949606/cc417a1c-e705-478c-82f3-57ae1471cb11)

Is there a way to disable (not to hide, just disable) the number input field at this place or to check if the value is > max-value?

Best Regards

**Comment by Juicytronic** [comment]
You have "Input Action" selected in the "Action Element" field of your device.
You just need to deselect/empty the field and save.

**Comment by manoloxxl** [comment]
Oh thanks, very easy....
