### ISSUE TITLE
Jarvis Dashboard öffnet sich nicht

### ISSUE THREAD

**Issue by kilian-f-za** [Zefau/ioBroker.jarvis#2425]
Ich habe Jarvis (3.1.2) auf den iob installiert und im Web (6.1.0) Adapter bei Socket.io auf integriert gestellt. Wenn ich dann Jarvis über die Instanzen öffnen will kommt erst der normale Bildschirm mit "Connection", dann "Connected Loading functions,modules" und danach ist der Bildschirm weiß. In den Protokollen im iob ist keine Fehlermeldung, nur Client xxx ist connected.
Ich habe es mit älteren Versionen probiert und da geht es auch nicht, bei einer Version konnte ich es starten aber das Speichern hat noch funktioniert. Was mache ich falsch oder voran kann es liegen? Danke ![Screenshot_20230904-075752.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/aa7e6917-799c-4d93-8496-1fe5355a76d9)

![Screenshot_20230904-075837.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/fb80bc80-42c6-4bcf-b405-8532c80010c9)

**Comment by mcuiobroker** [comment]
Zeig mal bitte die Einstellungen vom web.0.
Was zeigt das consolen-Log -> F12?

**Comment by kilian-f-za** [comment]
Hi, hier die Screenshots. Ich habe auf dem Rechner neu angefangen und die neueste Beta Mal installiert. Hat sich aber nichts verändert. ![Screenshot_20230906-090008.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/00ea608e-74f3-49e8-be79-1ceb818b2b7b)

![Screenshot_20230906-090352~2.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/471177cf-44bc-4c69-9225-4fa0cd03177c)

![Screenshot_20230906-090407~2.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/86eeedaa-0e67-4414-8c40-2fed29bf435f)

![Screenshot_20230906-090821.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/b1224bdb-a55a-4d21-b9f6-3414421c45ec)

**Comment by mcuiobroker** [comment]
- Setz mal diese beiden Werte auf false.
- dann web.0-Instanz neu starten
- dann jarvis.0-Instanz neu starten
- evtl Browser Cache löschen
- Frontend über InstanzLink aufrufen
-

**Comment by kilian-f-za** [comment]
Habe alles gemacht, es kam eine Meldung am Anfang und jetzt ist dieser Screen.
![Screenshot_20230906-095436.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/b847fc2e-107f-4502-9fd0-e517d8730691)

**Comment by mcuiobroker** [comment]
Dann hast du auf Automatisch generieren geklickt?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/d4b92e73-7fa1-4a70-9c67-29254855e1e2)

**Comment by kilian-f-za** [comment]
Nein automatisch generieren kam nicht. Ein ots parse error kommt.
![Screenshot_20230906-100131.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/44fdc574-a10f-4265-86c4-7000c8c0fde8)

**Comment by mcuiobroker** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3f2d7b87-8658-4afc-82b5-c3cdcbb9a4e7)
Die kannst du ignorieren.

Bitte ein Bild vom kompletten Frontend

**Comment by kilian-f-za** [comment]
Es ist nur ein grauer/weißer Screen.

![Screenshot_20230906-100545.png](https://github.com/Zefau/ioBroker.jarvis/assets/87258544/a129dba2-050a-4b97-bb11-b02dd0137d95)

**Comment by mcuiobroker** [comment]
Besonderes System?
```
iob diag
```
Bitte laufen lassen und hier als mit codeTags reinstellen. 
Oben das Zeichen 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c2b01956-3c8d-48be-89bf-9bfaf2195d92)
 klicken und einfügen

**Comment by kilian-f-za** [comment]
Ist ein Raspberry Pi 4 mit raspbian

`======== Start marking the full check here =========

```                                                                                       Skript v.2023-04-16

*** BASE SYSTEM ***                                                                       Model           : Raspberry Pi 4 Model B Rev 1.4
Architecture    : armv7l
Docker          : false
Virtualization  : none
Distributor ID: Raspbian
Description:    Raspbian GNU/Linux 11 (bullseye)
Release:        11
Codename:       bullseye

PRETTY_NAME="Raspbian GNU/Linux 11 (bullseye)"
NAME="Raspbian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=raspbian
ID_LIKE=debian
HOME_URL="http://www.raspbian.org/"
SUPPORT_URL="http://www.raspbian.org/RaspbianForums"
BUG_REPORT_URL="http://www.raspbian.org/RaspbianBugs"

Systemuptime and Load:
 10:16:10 up 4 days, 11:18,  1 user,  load average: 0.04, 0.16, 0.17
CPU threads: 4

Raspberry only:
throttled=0x0
Other values than 0x0 hint to temperature/voltage problems
temp=44.8'C
volt=0.9360V

*** Time and Time Zones ***
               Local time: Wed 2023-09-06 10:16:10 CEST
           Universal time: Wed 2023-09-06 08:16:10 UTC
                 RTC time: n/a
                Time zone: Europe/Berlin (CEST, +0200)
System clock synchronized: yes
              NTP service: active
          RTC in local TZ: no

*** User and Groups ***
pi
/home/pi
pi adm dialout cdrom sudo audio video plugdev games users input render netdev gpio i2c spi iobroker

*** X-Server-Setup ***
X-Server:       false
Desktop:
Terminal:       tty
Boot Target:    graphical.target

*** MEMORY ***
               total        used        free      shared  buff/cache   available
Mem:            3.8G        889M        1.6G        0.0K        1.3G        2.8G
Swap:            99M          0B         99M
Total:          3.9G        889M        1.7G

         3838 M total memory
          889 M used memory
          496 M active memory
         1502 M inactive memory
         1645 M free memory
          140 M buffer memory
         1163 M swap cache
           99 M total swap
            0 M used swap
           99 M free swap

Raspberry only:
oom events: 0
lifetime oom required: 0 Mbytes
total time in oom handler: 0 ms
max time spent in oom handler: 0 ms

*** FILESYSTEM ***
Filesystem     Type      Size  Used Avail Use% Mounted on
/dev/root      ext4       29G  4.6G   24G  17% /
devtmpfs       devtmpfs  1.8G     0  1.8G   0% /dev
tmpfs          tmpfs     1.9G     0  1.9G   0% /dev/shm
tmpfs          tmpfs     768M  820K  767M   1% /run
tmpfs          tmpfs     5.0M  4.0K  5.0M   1% /run/lock
/dev/mmcblk0p1 vfat      253M   50M  203M  20% /boot
tmpfs          tmpfs     384M     0  384M   0% /run/user/1000

Messages concerning ext4 filesystem in dmesg:
[Fri Sep  1 22:57:25 2023] Kernel command line: coherent_pool=1M 8250.nr_uarts=1 snd_bcm2835.enable_compat_alsa=0 snd_bcm2835.enable_hdmi=1  smsc95xx.macaddr=E4:5F:01:66:8D:E3 vc_mem.mem_base=0x3ec00000 vc_mem.mem_size=0x40000000  console=tty1 root=PARTUUID=c67bd2a3-02 rootfstype=ext4 fsck.repair=yes rootwait
[Fri Sep  1 22:57:26 2023] EXT4-fs (mmcblk0p2): mounted filesystem with ordered data mode. Opts: (null). Quota mode: none.
[Fri Sep  1 22:57:26 2023] VFS: Mounted root (ext4 filesystem) readonly on device 179:2.
[Fri Sep  1 22:57:28 2023] EXT4-fs (mmcblk0p2): re-mounted. Opts: (null). Quota mode: none.

Show mounted filesystems (real ones only):
TARGET  SOURCE         FSTYPE OPTIONS
/       /dev/mmcblk0p2 ext4   rw,noatime
`-/boot /dev/mmcblk0p1 vfat   rw,relatime,fmask=0022,dmask=0022,codepage=437,iocharset=ascii,shortname=mixed,flush,errors=remount-ro

Files in neuralgic directories:

/var:
1.4G    /var/
988M    /var/log
985M    /var/log/journal/1dc3fd342d2f47619afb6c953cd7d32f
985M    /var/log/journal
238M    /var/cache

Archived and active journals take up 984.2M in the file system.

/opt/iobroker/backups:
58M     /opt/iobroker/backups/

/opt/iobroker/iobroker-data:
334M    /opt/iobroker/iobroker-data/
250M    /opt/iobroker/iobroker-data/files
67M     /opt/iobroker/iobroker-data/files/minuvis
66M     /opt/iobroker/iobroker-data/backup-objects
52M     /opt/iobroker/iobroker-data/files/javascript.admin

The five largest files in iobroker-data are:
21M     /opt/iobroker/iobroker-data/files/web.admin/static/js/main.e564fb87.js.map
17M     /opt/iobroker/iobroker-data/objects.jsonl
15M     /opt/iobroker/iobroker-data/files/telegram.admin/rules/static/js/vendors-node_modules_iobroker_adapter-react-v5_assets_devices_parseNames_d_ts-node_modules_io-1d9f06.44fe4a3f.chunk.js.map
14M     /opt/iobroker/iobroker-data/files/minuvis/app/static/js/main.7447352f.js.map
8.3M    /opt/iobroker/iobroker-data/files/web.admin/static/js/main.e564fb87.js

*** NodeJS-Installation ***

/usr/bin/nodejs         v18.17.1
/usr/bin/node           v18.17.1
/usr/bin/npm            9.6.7
/usr/bin/npx            9.6.7


nodejs:
  Installed: 18.17.1-deb-1nodesource1
  Candidate: 18.17.1-deb-1nodesource1
  Version table:
 *** 18.17.1-deb-1nodesource1 500
        500 https://deb.nodesource.com/node_18.x bullseye/main armhf Packages
        100 /var/lib/dpkg/status
     12.22.12~dfsg-1~deb11u4 500
        500 http://raspbian.raspberrypi.org/raspbian bullseye/main armhf Packages

Temp directories causing npm8 problem: 0
No problems detected

*** ioBroker-Installation ***

ioBroker Status
iobroker is running on this host.


Objects type: jsonl
States  type: jsonl

MULTIHOSTSERVICE/enabled: false

Core adapters versions
js-controller:  4.0.24
admin:          6.8.0
javascript:     7.0.3

Adapters from github:   1

Adapter State
+ system.adapter.admin.0                  : admin                 : raspberrypi                              -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
  system.adapter.alias-manager.0          : alias-manager         : raspberrypi                              -  enabled
+ system.adapter.backitup.0               : backitup              : raspberrypi                              -  enabled
+ system.adapter.discovery.0              : discovery             : raspberrypi                              -  enabled
  system.adapter.habpanel.0               : habpanel              : raspberrypi                              -  enabled
+ system.adapter.history.0                : history               : raspberrypi                              -  enabled
+ system.adapter.info.0                   : info                  : raspberrypi                              -  enabled
+ system.adapter.jarvis.0                 : jarvis                : raspberrypi                              -  enabled
+ system.adapter.javascript.0             : javascript            : raspberrypi                              -  enabled
+ system.adapter.lovelace.0               : lovelace              : raspberrypi                              -  enabled, port: 8091, bind: 0.0.0.0, run as: admin
+ system.adapter.shelly.0                 : shelly                : raspberrypi                              -  enabled, port: 1885, bind: 0.0.0.0
+ system.adapter.sonoff.0                 : sonoff                : raspberrypi                              -  enabled, port: 1884, bind: 0.0.0.0
+ system.adapter.telegram.0               : telegram              : raspberrypi                              -  enabled, port: 8443, bind: 0.0.0.0
+ system.adapter.valuetrackerovertime.0   : valuetrackerovertime  : raspberrypi                              -  enabled
+ system.adapter.virtualpowermeter.0      : virtualpowermeter     : raspberrypi                              -  enabled
+ system.adapter.web.0                    : web                   : raspberrypi                              -  enabled, port: 8082, bind: 0.0.0.0, run as: admin

+ instance is alive

Enabled adapters with bindings
+ system.adapter.admin.0                  : admin                 : raspberrypi                              -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
+ system.adapter.lovelace.0               : lovelace              : raspberrypi                              -  enabled, port: 8091, bind: 0.0.0.0, run as: admin
+ system.adapter.shelly.0                 : shelly                : raspberrypi                              -  enabled, port: 1885, bind: 0.0.0.0
+ system.adapter.sonoff.0                 : sonoff                : raspberrypi                              -  enabled, port: 1884, bind: 0.0.0.0
+ system.adapter.telegram.0               : telegram              : raspberrypi                              -  enabled, port: 8443, bind: 0.0.0.0
+ system.adapter.web.0                    : web                   : raspberrypi                              -  enabled, port: 8082, bind: 0.0.0.0, run as: admin

ioBroker-Repositories
stable        : http://download.iobroker.net/sources-dist.json
beta          : http://download.iobroker.net/sources-dist-latest.json

Active repo(s): stable

Installed ioBroker-Instances
Used repository: stable
Adapter    "admin"        : 6.8.0    , installed 6.8.0
Adapter    "alias-manager": 1.2.4    , installed 1.2.4
Adapter    "backitup"     : 2.6.23   , installed 2.6.23
Adapter    "discovery"    : 3.1.0    , installed 3.1.0
Adapter    "habpanel"     : 0.5.0    , installed 0.5.0
Adapter    "history"      : 2.2.6    , installed 2.2.6
Adapter    "info"         : 1.9.26   , installed 1.9.26
Adapter    "jarvis"       : 3.1.2    , installed 3.1.9-beta.2
Adapter    "javascript"   : 7.0.3    , installed 7.0.3
Controller "js-controller": 4.0.24   , installed 4.0.24
Adapter    "lovelace"     : 3.0.1    , installed 3.0.1
Adapter    "minuvis"      : 2.2.0    , installed 2.2.0
Adapter    "shelly"       : 6.4.1    , installed 6.4.1
Adapter    "simple-api"   : 2.7.2    , installed 2.7.2
Adapter    "socketio"     : 6.5.2    , installed 6.5.2
Adapter    "sonoff"       : 2.5.3    , installed 2.5.3
Adapter    "telegram"     : 1.16.0   , installed 1.16.0
Adapter    "valuetrackerovertime": 1.0.0, installed 1.0.0
Adapter    "virtualpowermeter": 1.4.6, installed 1.4.6
Adapter    "web"          : 6.1.0    , installed 6.1.0
Adapter    "ws"           : 2.5.3    , installed 2.5.3

Objects and States
Please stand by - This may take a while
Objects:        1463
States:         1071

*** OS-Repositories and Updates ***
Hit:1 http://archive.raspberrypi.org/debian bullseye InRelease
Hit:2 http://raspbian.raspberrypi.org/raspbian bullseye InRelease
Hit:3 https://deb.nodesource.com/node_18.x bullseye InRelease
Reading package lists...
Pending Updates: 132

*** Listening Ports ***
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode      PID/Program name
tcp        0      0 0.0.0.0:8400            0.0.0.0:*               LISTEN      1001       1511882    17640/io.jarvis.0
tcp        0      0 0.0.0.0:22              0.0.0.0:*               LISTEN      0          12968      528/sshd: /usr/sbin
tcp        0      0 127.0.0.1:9001          0.0.0.0:*               LISTEN      1001       809215     21232/iobroker.js-c
tcp        0      0 127.0.0.1:9000          0.0.0.0:*               LISTEN      1001       809222     21232/iobroker.js-c
tcp        0      0 0.0.0.0:1884            0.0.0.0:*               LISTEN      1001       808891     21326/io.sonoff.0
tcp        0      0 0.0.0.0:1885            0.0.0.0:*               LISTEN      1001       808912     21341/io.shelly.0
tcp6       0      0 :::22                   :::*                    LISTEN      0          12970      528/sshd: /usr/sbin
tcp6       0      0 :::8082                 :::*                    LISTEN      1001       1511186    17625/io.web.0
tcp6       0      0 :::8081                 :::*                    LISTEN      1001       807811     21250/io.admin.0
tcp6       0      0 :::8091                 :::*                    LISTEN      1001       902925     14453/io.lovelace.0
udp        0      0 0.0.0.0:5353            0.0.0.0:*                           108        12828      387/avahi-daemon: r
udp        0      0 0.0.0.0:34282           0.0.0.0:*                           108        12830      387/avahi-daemon: r
udp        0      0 0.0.0.0:68              0.0.0.0:*                           0          11849      646/dhcpcd
udp6       0      0 :::5353                 :::*                                108        12829      387/avahi-daemon: r
udp6       0      0 :::52292                :::*                                108        12831      387/avahi-daemon: r

*** Log File - Last 25 Lines ***

2023-09-06 10:00:02.027  - info: host.raspberrypi "system.adapter.jarvis.0" enabled
2023-09-06 10:00:02.144  - info: host.raspberrypi instance system.adapter.jarvis.0 started with pid 17640
2023-09-06 10:00:05.057  - info: jarvis.0 (17640) starting. Version 3.1.9-beta.2 (non-npm:Copy text starting here:                                                                  
```                                                                                       ======================= SUMMARY =======================
                     v.2023-04-16                                                         

Operatingsystem:        Raspbian GNU/Linux 11 (bullseye)
Kernel:                 5.15.32-v7l+
Installation:           Native
Timezone:               Europe/Berlin (CEST, +0200)                                       User-ID:                1000
X-Server:               false                                                             Boot Target:            graphical.target
Pending OS-Updates:     132
Pending iob updates:    0                                                                 
Nodejs-Installation:    /usr/bin/nodejs         v18.17.1                                                          /usr/bin/node           v18.17.1
                        /usr/bin/npm            9.6.7                                                             /usr/bin/npx            9.6.7                                     
Recommended versions are nodejs 18.x.y and npm 9.x.y                                      Your nodejs installation is correct
MEMORY:                                                                                                  total        used        free      shared  buff/cache   available
Mem:            3.8G        913M        1.6G        0.0K        1.3G        2.8G          Swap:            99M          0B         99M                                              Total:          3.9G        913M        1.7G
Active iob-Instances:   15
Active repo(s): stable                                                                    
ioBroker Core:          js-controller           4.0.24
                        admin                   6.8.0

ioBroker Status:        iobroker is running on this host.


Objects type: jsonl
States  type: jsonl

Status admin and web instance:
+ system.adapter.admin.0                  : admin                 : raspberrypi                              -  enabled, port: 8081, bind: 0.0.0.0, run as: admin
+ system.adapter.web.0                    : web                   : raspberrypi                              -  enabled, port: 8082, bind: 0.0.0.0, run as: admin

Objects:                1463
States:                 1071

Size of iob-Database:

17M     /opt/iobroker/iobroker-data/objects.jsonl
1.2M    /opt/iobroker/iobroker-data/states.jsonl



=================== END OF SUMMARY ====================
```
`

**Comment by mcuiobroker** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/806bff3b-aa31-4769-8e85-36b7ad74b622)
Einige Updates sind offen, aber ob das mit dem Problem zu tun hat?
Bei Gelegenheit
```
iob stop
sudo apt update && sudo apt upgrade -y
sdo reboot
``` 
sonst sieht alles normal aus.
Beim Loading F12 steht nichts?

**Comment by mcuiobroker** [comment]
Vielleicht ist eine Schriftproblematik. Schalte mal den darkMode ein.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/056e24d6-20a7-41e1-b49f-913e25d88757)
-> true setzen

**Comment by kilian-f-za** [comment]
> ![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/806bff3b-aa31-4769-8e85-36b7ad74b622)
> Einige Updates sind offen, aber ob das mit dem Problem zu tun hat?
> Bei Gelegenheit
> ```
> iob stop
> sudo apt update && sudo apt upgrade -y
> sudo reboot
> ``` 
> sonst sieht alles normal aus.
> Beim Loading F12 steht nichts?

OK. Ich mache mal ein Update. Ich habe die nodejs Version und js-controller Version schon geupdated.

**Comment by kilian-f-za** [comment]
> Vielleicht ist eine Schriftproblematik. Schalte mal den darkMode ein.
> ![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/056e24d6-20a7-41e1-b49f-913e25d88757)
> -> true setzen

Bei darkmode kommt nur eine schwarze Seite.

**Comment by kilian-f-za** [comment]
> > ![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/806bff3b-aa31-4769-8e85-36b7ad74b622)
> > Einige Updates sind offen, aber ob das mit dem Problem zu tun hat?
> > Bei Gelegenheit
> > ```
> > iob stop
> > sudo apt update && sudo apt upgrade -y
> > sudo reboot
> > ``` 
> > sonst sieht alles normal aus.
> > Beim Loading F12 steht nichts?
> 
> OK. Ich mache mal ein Update. Ich habe die nodejs Version und js-controller Version schon geupdated. 

Update habe ich gemacht, aber leider keinen Erfolg. :(

**Comment by mcuiobroker** [comment]
Mir gehen die Ideen aus.
Also man könnte nochmal den kompletten Adapter löschen, dann iobroker neu starten und dann den Adapter neu installieren über die console
```
iob upgrade jarvis@3.1.9-beta.2
```
Eigentlich müsste etwas im LOG (F12) stehen, echt komisch.
Ich muss das mit der Konstellation auch noch auf einem System probieren. Mal schauen was da raus kommt, evtl heute Abend?

Ich hatte es damals mit nodejs 16 erfolgreich geschafft komplett neu zu beginnen.

**Comment by mcuiobroker** [comment]
Ja, dann geh mal über die Adapter
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/35196efc-7c7c-4c70-acff-e37a4e3276aa)

**Comment by kilian-f-za** [comment]
Habe jetzt so eine Meldung bekommen. Hatte vergessen auf Beta umzustellen und habe die 3.1.8 drauf. Dann habe ich auf Beta gestellt und wieder ein Error bekommen. 

`Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Sep  6 22:20:51 2023 from 192.168.110.40

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.

pi@raspberrypi:~ $ cat /home/iobroker/.npm/_logs/2023-09-06T20_39_47_534Z-debug-0.log     0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.7
2 info using node@v18.17.1
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 5ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 6ms
6 timing config:load:builtin Completed in 7ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/opt/iobroker/.npmrc Completed in 5ms
10 timing config:load:project Completed in 7ms
11 timing config:load:file:/home/iobroker/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 3ms
16 timing config:load Completed in 31ms
17 timing npm:load:configload Completed in 32ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm install Zefau/ioBroker.jarvis
21 verbose argv "install" "Zefau/ioBroker.jarvis"
22 timing npm:load:setTitle Completed in 4ms
23 timing config:load:flatten Completed in 9ms
24 timing npm:load:display Completed in 12ms
25 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs/2023-09-06T20_39_47_534Z-
26 verbose logfile /home/iobroker/.npm/_logs/2023-09-06T20_39_47_534Z-debug-0.log
27 timing npm:load:logFile Completed in 27ms
28 timing npm:load:timers Completed in 1ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 83ms
31 timing arborist:ctor Completed in 3ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 2225ms
35 timing arborist:ctor Completed in 0ms
36 timing idealTree Completed in 12428ms
37 timing command:install Completed in 12485ms
38 verbose stack Error: An unknown git error occurred
38 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
38 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
38 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
39 verbose cwd /opt/iobroker
40 verbose Linux 6.1.21-v8+
41 verbose node v18.17.1
42 verbose npm  v9.6.7
43 error code 128
44 error An unknown git error occurred
45 error command git --no-replace-objects ls-remote ssh://git@github.com/Zefau/ioBroker.jarvis.git
46 error ssh: connect to host github.com port 22: Network is unreachable
46 error fatal: Konnte nicht vom Remote-Repository lesen.
46 error
46 error Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
46 error und das Repository existiert.
47 verbose exit 128
48 timing npm Completed in 13197ms
49 verbose unfinished npm timer reify 1694032788231
50 verbose unfinished npm timer reify:loadTrees 1694032788277
51 verbose unfinished npm timer idealTree:userRequests 1694032790507
52 verbose code 128
53 error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2023-09-06T20_39_47_534Z-debug-0.log
pi@raspberrypi:~ $`

**Comment by kilian-f-za** [comment]
Habe jetzt so eine Meldung bekommen. Hatte vergessen auf Beta umzustellen und habe die 3.1.8 drauf. Dann habe ich auf Beta gestellt und wieder ein Error bekommen. 

`Linux raspberrypi 6.1.21-v8+ #1642 SMP PREEMPT Mon Apr  3 17:24:16 BST 2023 aarch64

The programs included with the Debian GNU/Linux system are free software;
the exact distribution terms for each program are described in the
individual files in /usr/share/doc/*/copyright.

Debian GNU/Linux comes with ABSOLUTELY NO WARRANTY, to the extent
permitted by applicable law.
Last login: Wed Sep  6 22:20:51 2023 from 192.168.110.40

Wi-Fi is currently blocked by rfkill.
Use raspi-config to set the country before use.

pi@raspberrypi:~ $ cat /home/iobroker/.npm/_logs/2023-09-06T20_39_47_534Z-debug-0.log     0 verbose cli /usr/bin/node /usr/bin/npm
1 info using npm@9.6.7
2 info using node@v18.17.1
3 timing npm:load:whichnode Completed in 4ms
4 timing config:load:defaults Completed in 5ms
5 timing config:load:file:/usr/lib/node_modules/npm/npmrc Completed in 6ms
6 timing config:load:builtin Completed in 7ms
7 timing config:load:cli Completed in 5ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:/opt/iobroker/.npmrc Completed in 5ms
10 timing config:load:project Completed in 7ms
11 timing config:load:file:/home/iobroker/.npmrc Completed in 0ms
12 timing config:load:user Completed in 1ms
13 timing config:load:file:/usr/etc/npmrc Completed in 0ms
14 timing config:load:global Completed in 1ms
15 timing config:load:setEnvs Completed in 3ms
16 timing config:load Completed in 31ms
17 timing npm:load:configload Completed in 32ms
18 timing npm:load:mkdirpcache Completed in 0ms
19 timing npm:load:mkdirplogs Completed in 1ms
20 verbose title npm install Zefau/ioBroker.jarvis
21 verbose argv "install" "Zefau/ioBroker.jarvis"
22 timing npm:load:setTitle Completed in 4ms
23 timing config:load:flatten Completed in 9ms
24 timing npm:load:display Completed in 12ms
25 verbose logfile logs-max:10 dir:/home/iobroker/.npm/_logs/2023-09-06T20_39_47_534Z-
26 verbose logfile /home/iobroker/.npm/_logs/2023-09-06T20_39_47_534Z-debug-0.log
27 timing npm:load:logFile Completed in 27ms
28 timing npm:load:timers Completed in 1ms
29 timing npm:load:configScope Completed in 0ms
30 timing npm:load Completed in 83ms
31 timing arborist:ctor Completed in 3ms
32 silly logfile start cleaning logs, removing 2 files
33 silly logfile done cleaning log files
34 timing idealTree:init Completed in 2225ms
35 timing arborist:ctor Completed in 0ms
36 timing idealTree Completed in 12428ms
37 timing command:install Completed in 12485ms
38 verbose stack Error: An unknown git error occurred
38 verbose stack     at makeError (/usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/make-error.js:28:13)
38 verbose stack     at /usr/lib/node_modules/npm/node_modules/@npmcli/git/lib/spawn.js:37:26
38 verbose stack     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
39 verbose cwd /opt/iobroker
40 verbose Linux 6.1.21-v8+
41 verbose node v18.17.1
42 verbose npm  v9.6.7
43 error code 128
44 error An unknown git error occurred
45 error command git --no-replace-objects ls-remote ssh://git@github.com/Zefau/ioBroker.jarvis.git
46 error ssh: connect to host github.com port 22: Network is unreachable
46 error fatal: Konnte nicht vom Remote-Repository lesen.
46 error
46 error Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehen
46 error und das Repository existiert.
47 verbose exit 128
48 timing npm Completed in 13197ms
49 verbose unfinished npm timer reify 1694032788231
50 verbose unfinished npm timer reify:loadTrees 1694032788277
51 verbose unfinished npm timer idealTree:userRequests 1694032790507
52 verbose code 128
53 error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2023-09-06T20_39_47_534Z-debug-0.log
pi@raspberrypi:~ $`

**Comment by mcuiobroker** [comment]
Wi-Fi is currently blocked by rfkill. ?

**Comment by kilian-f-za** [comment]
> Wi-Fi is currently blocked by rfkill. ?
> verbose stack Error: An unknown git error occurred
> error ssh: connect to host github.com port 22: Network is unreachable
> 46 error fatal: Konnte nicht vom Remote-Repository lesen.
> 
> ?? Netzwerk-Problem?

Ich habe kurz davor die 3.1.8 herunterladen und dann die Beta aber die geht nicht. Was meinst du mit ist nicht im npm die Version 3.1.9?

**Comment by mcuiobroker** [comment]
`3.1.9-beta.2` wird nicht als npm-Version angezeigt, so dass man sie nicht mit dem Befehl herunterladen kann.
Echt komisch, da ich der Meinung war, ich hätte es schon so installiert.

**Comment by kilian-f-za** [comment]
Land und alle Einstellungen für Standort habe ich eingestellt.

**Comment by mcuiobroker** [comment]
Hat es denn was gebracht?

**Comment by kilian-f-za** [comment]
Nein leider nicht :(

**Comment by mcuiobroker** [comment]
Du kannst im Forum ein Thread aufmachen und schauen ob der Thomas Braum noch was entdeckt bzgl Systemprobleme.

**Comment by kilian-f-za** [comment]
> Du kannst im Forum ein Thread aufmachen und schauen ob der Thomas Braum noch was entdeckt bzgl Systemprobleme.

In welchem Forum?

**Comment by mcuiobroker** [comment]
ioBroker-Forum
https://forum.iobroker.net/

**Comment by kilian-f-za** [comment]
> ioBroker-Forum
> https://forum.iobroker.net/

Ah da. Alles klar danke dir.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.6` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.6` should fix the bug - please verify. If the bug has been solved, you may close the issue.
