### ISSUE TITLE
Datatype for xxxx differs from expected, ignore state change! Please write correct datatype (number)

### ISSUE THREAD

**Issue by ch90045** [Zefau/ioBroker.jarvis#2428]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- Jarvis 3.1.2, getestet habe ich auch 3.1.8 und 3.1.9-beta-2
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]Datatype for 48281f85-2e54-456d-96f0-6c10eae9f136.climateControl.fanControl.operationModes.cooling.fanSpeed.currentMode differs from expected, ignore state change! Please write correct datatype (number)
- [ ] 
**Describe the bug / Beschreibe den Fehler**
Es soll DP daikin-cloud.0.48281f85-2e54-456d-96f0-6c10eae9f136.climateControl.fanControl.operationModes.cooling.fanSpeed.currentMode gesteuert werden. Dieser DP hat folgende Eigenschaften:

{
  "type": "state",
  "common": {
    "type": "number",
    "read": true,
    "write": true,
    "states": {
      "0": "auto",
      "1": "quiet",
      "2": "fixed"
    },
    "name": "currentMode",
    "role": "level"
  },
  "native": {
    "managementPoint": "climateControl",
    "dataPoint": "fanControl",
    "dataPointPath": "/operationModes/cooling/fanSpeed/currentMode",
    "values": [
      "auto",
      "quiet",
      "fixed"
    ]
  },
  "from": "system.adapter.daikin-cloud.0",
  "user": "system.user.admin",
  "ts": 1694068597924,
  "_id": "daikin-cloud.0.48281f85-2e54-456d-96f0-6c10eae9f136.climateControl.fanControl.operationModes.cooling.fanSpeed.currentMode",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.christian",
    "ownerGroup": "system.group.administrator"
  }
}

Das entsprechende Jarvis Gerät hat folgende Definition:

"62796c52-6a48-49b7-bcaf-9b497086c701": {
    "name": "DummyKlimaanlage",
    "icon": "",
    "label": "",
    "function": "_defaults",
    "states": {
      "CoolMode": {
        "_created": 1694091108632,
        "stateKey": "CoolMode",
        "showState": true,
        "state": "daikin-cloud.0.48281f85-2e54-456d-96f0-6c10eae9f136.climateControl.fanControl.operationModes.cooling.fanSpeed.currentMode",
        "_updated": 1694092437818,
        "display": {
          "auto": "Automatisch",
          "quiet": "Flüstermodus",
          "fixed": "Gleichmässig"
        }
      }
    },
    "options": {},
    "id": "62796c52-6a48-49b7-bcaf-9b497086c701",
    "attributes": {
      "_created": 1694091086017,
      "_updated": 1694092429200
    },
    "revision": "d43b2"
  }

  Das entsprechende Widget folgende:

  "_created": 1694091244370,
 "title": "DummyKlima",
 "module": "StateList",
 "items": [
   {
     "type": "device",
     "deviceId": "62796c52-6a48-49b7-bcaf-9b497086c701",
     "id": "1f88197c-39d7-47cb-9a09-467ccb1cd10a",
     "primaryStateKey": "CoolMode",
     "bodyStateKey": "CoolMode",
     "isInGroup": false,
     "actionElement": "DropdownAction",
     "bodyElement": null
   }
 ],
 "revision": "454e4",
 "_updated": 1694091359447
}

Wenn der DP über das Widget gesteuert wird, kommt folgende Fehlermeldung:

Datatype for 48281f85-2e54-456d-96f0-6c10eae9f136.climateControl.fanControl.operationModes.cooling.fanSpeed.currentMode differs from expected, ignore state change! Please write correct datatype (number)

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by ch90045** [comment]
Zwar wird der DP dann geschrieben, aber nicht an das Gerät gesendet

**Comment by mcuiobroker** [comment]
Dann evtl in Datenpunkt-Eigenschaften
```
{"value":"val => parseInt(val)"}
```

**Comment by ch90045** [comment]
Damit kommt die Fehlermeldung zurück

Datatype for 48281f85-2e54-456d-96f0-6c10eae9f136.climateControl.fanControl.operationModes.cooling.fanSpeed.currentMode differs from expected, ignore state change! Please write correct datatype (number)

**Comment by mcuiobroker** [comment]
Schade. Keine weitere Idee vorhanden.

**Comment by ch90045** [comment]
Was mich ein wenig irritiert ist 

![image](https://github.com/Zefau/ioBroker.jarvis/assets/2450761/999b380c-45b4-4040-9a2a-6c5efa2142d6)

Bin mir nicht sicher, ob die (0) vorher auch da war

**Comment by mcuiobroker** [comment]
Das ist jetzt der DP `currentMode` in den ioBroker-Objekten.
Ja das ist der eigentliche Wert, der weiter gegeben wird.

**Comment by Zefau** [comment]
@ch90045 @mcuiobroker ist das hier noch aktuell oder kann das zu?

**Comment by mcuiobroker** [comment]
@Zefau 
Das ist die Problematik, die tatsächliche Einheit aus iobroker zu lesen getObject.
Hatten wir irgendwo mal diskutiert.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2701
