### ISSUE TITLE
StateList Filter - Fehleranzeige trotzdem funktioniert es

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2429]
`v3.19.-beta.2`
Ich habe eine Fehlermeldung bzgl Filter in einer StateList, obwohl der Filter ausgeführt wird und auch korrekt ist.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5c6c9948-9a5e-4a4a-8f8d-3dc8f83bbc39)
```
(value, val, state, device, deviceConfig, widget) => (state.config.stateKey != 'SensorenAlleAn')
```
Jeder state hat eine config und dort ist immer ein stateKey vorhanden.
Zeit-Problem?

**Comment by Zefau** [comment]
Hast du den Fehler auch wenn du statt `state.config.stateKey` einfach `state.stateKey` benutzt?

**Comment by Zefau** [comment]
@mcuiobroker ist das hier noch aktuell?

**Comment by mcuiobroker** [comment]
Nein.
