### ISSUE TITLE
Feature: Ignore SSL on iframe

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#243]

**Comment by Zefau** [comment]
Do you have problems loading the content or why is this necessary? Do you have any error messages in the browser console?

**Comment by duczz** [comment]
the iframes cant be load, because it use ssl. i need to visit the side manually and accept the ssl cert, than it works on jarvis
These are camera pictures from town

**Comment by Zefau** [comment]
And how do I ignore this? I'm not sure if that is possible due to security reasons. Is it implemented that way in ioBroker.vis?

**Comment by duczz** [comment]
in the Vis is it the same Problem
