### ISSUE TITLE
StateList Filter -> Bei Änderung von state.val wird StateList nicht aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2430]
Ändert man bei bestehendem Filter den Zustand States, werden diese nicht korrekt dargestellt mit dem Filter.
erst nach F5 Aktualisierung erscheint die korrekte Anzeige.
Insbesondere, wenn der DP auf false gesetzt wird.

![FilterAktualisierung bei false nicht korrekt](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/d9ccecbf-027a-468c-bb09-fd5abf77de6c)

Wird der DP StatusNacht vom System auf true gesetzt erscheint er automatisch.

```
(value, val, state, device, deviceConfig, widget) => (state.stateKey == 'StatusNacht' && val == true) || (state.stateKey == 'umschaltung' && val == false) || (state.stateKey == 'Zuhause' || state.stateKey == 'BesuchDa' || state.stateKey == 'Urlaub') 
```

**Comment by Zefau** [comment]
@mcuiobroker ist das hier noch aktuell?

**Comment by mcuiobroker** [comment]
Nein
