### ISSUE TITLE
Add Mode to quickly sort devices in widgets

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2432]

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.1.9-beta.3` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.1.9-beta.3`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Wo kann man das einstellen? Für StateList?

**Comment by Zefau** [comment]
hm, ist ein alter Feature-Request aus v3.1. Ich schließe den mal. Meint meine ich die Schnellsortierung in der StateList, ja:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/c92018a9-cb91-4987-bf8b-38ef5337a274)

**Comment by mcuiobroker** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3277c09e-d5ad-4243-b414-dd2a8363d24a)
Übersetzung?
