### ISSUE TITLE
CSS für plain Widget auf das Widget einschränken

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2434]
Momentan bekommt man ein flaches Widget nur mit dieser CSS-Einstellung hin.
Die greift aber auch auf alle anderen Widgets, Konfiguration usw. ein.
Dort sollte es die Möglichkeit geben es auf ein Widget einzuschränken.
-> `.jarvis-widget-33458..... .paper`
```
.paper { 
  border-radius: 0px !important;
  box-shadow: 0 0 0 black;
}
```

**Comment by Zefau** [comment]
Du meinst die Box mit der CSS-Klasse `jarvis-widget-container` ? Da noch eine ID rein?

**Comment by mcuiobroker** [comment]
Das Problem ist die paper-Klasse

**Comment by Zefau** [comment]
Jo, aber bezogen auf das Widget ist `paper` ja auf demselben Element vergeben wie `jarvis-widget-container`. Ich würde dann bei `jarvis-widget-container` die Widget ID hinzufügen und dann können die Eigenschaften von `paper` ja überschrieben / zurückgesetzt werden.

**Comment by mcuiobroker** [comment]
Ok

**Comment by Zefau** [comment]
Mit v3.2.x ist das nun drin.

**Comment by mcuiobroker** [comment]
Wenn ich das jetzt in die Styles setze, hängt sich das System auf.
`.paper { 
  border-radius: 0px !important;
  box-shadow: 0 0 0 black;
}`

**Comment by Zefau** [comment]
@mcuiobroker kann das hier zu?

**Comment by mcuiobroker** [comment]
Ja, ich mache erstmal zu, habe zurzeit keine Zeit, um es zu testen. Grundsätzlich wird jetzt aber die Widget-Info gesetzt.
Danke.
