### ISSUE TITLE
Bar-Chart: Use device value function - keine Anzeige von Werten im popup

### ISSUE THREAD

**Issue by CaneTLOTW** [Zefau/ioBroker.jarvis#2435]
https://forum.iobroker.net/topic/49776/jarvis-v3-0-0-just-another-remarkable-vis/4103

Werte werden im popup nicht angezeigt.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/35076818/df5904e1-3247-4719-b43c-30aba166cd48)
Nachdem "Use device value function" aktiviert wurde
![image](https://github.com/Zefau/ioBroker.jarvis/assets/35076818/6c279477-9739-4b07-9ec8-e15fd6979060)

**Comment by Zefau** [comment]
Wie ist denn die Funktion im Gerät definiert?

**Comment by harman-f** [comment]
Bin jetzt allerdings auf eine Nachkommastelle runter:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/98130152/8f7aa00c-31f9-4f25-a5fd-d5e7ab2facf2)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.51` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.51` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@CaneTLOTW
