### ISSUE TITLE
Layout verzogen

### ISSUE THREAD

**Issue by mpl1337** [Zefau/ioBroker.jarvis#2437]
Hallo,

seit dem Update auf v3.1.9-beta.3 hat sich bei mir das Layout verzogen.

Wenn ich Jarvis im Browser öffne und warte bis die Seite geladen ist, sehe ich die Widgets noch richtig.

Layout Richtig:
![laden](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/b77bc525-e33f-4c05-9014-095c2e3795bd)

Sobald der Browser fertig geladen hat, verziehen sich die Widgets.

Layout verzogen:
![geladen](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/a8b50513-6635-4c95-8829-5f969817c8a7)

**Comment by Zefau** [comment]
Von welcher Version kommst du, wo es noch richtig war? Bekomme den Fehler bei mir nicht reproduziert.

Wie sind deine Einstellungen auf dem Tab?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/f726d8b7-e6dd-4ae9-be75-f70470bf6251)

**Comment by mpl1337** [comment]
Zuvor war ich bei 3.1.8

![Screenshot 2023-09-25 200636](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/16df13dc-40e1-400e-af6b-e60f5a0dbc17)

**Comment by mpl1337** [comment]
Hab das Problem gefunden.


![Screenshot 2023-09-25 200636](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/65c5dfa3-c088-4607-9d04-b9449e60653e)
