### ISSUE TITLE
Move from socket.io to WebSocket

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2438]

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.1` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.1`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by intruder7777** [comment]
nach Update auf 3.2.0 alpha 1 ließ sich bei mir absolut keine Verbindung mehr aufbauen. Habe alle Einstellungsmöglichkeiten in websocket,sockeito,web adapter ausprobiert. Er hat es nie geschafft eine Socketverbindung aufzubauen. Bin  dann wieder zurück auf die 3.1.8. Höher komme ich jetzt nicht mehr.

**Comment by Zefau** [comment]
Sollte mit der aktuellen alpha funktionieren?

**Comment by Zefau** [comment]
@intruder7777 wurde es besser mit der aktuellen alpha?

**Comment by Erwin40** [comment]
Ich frag jetzt mal blöd :-)

**Jarvis 3.2.0-beta.46**
Welchen Adapter sollte man denn am besten installieren?
Web Socket?
sockei.to?
oder WEB-Server?

Ich habe z.Z. den WEB-Server Adapter am Laufen und bin mit der Performance (Windows 10 + FireFox 128) nicht so ganz überzeugt. Da lief die 3.1.8 deutlich flotter. :-)
Auf meinen iPad 2 und 5 habe ich aber den Eindruck, dass es mit der 3.2.0-beta.X etwas flotter läuft.

**Comment by Zefau** [comment]
Jarvis v3.2 nutzt keinen Websocket, Socketio oder Web Adapter mehr

**Comment by Erwin40** [comment]
Ah, danke für die schnelle Antwort.
Das heißt ich brauchden Web Adapter eigentlich nur wenn innerhalb Jarvis auf Dateien im ioBroker, zugreifen möchte?
Z.B. für **import "http://192.168.177.13:8082/0_userdata.0/jarvisScripte/jarvisDPs.js";**
![grafik](https://github.com/user-attachments/assets/e36e7768-b0c1-4bfe-b52a-8214a054fcd7)

**Comment by Zefau** [comment]
Jo

**Comment by Erwin40** [comment]
Also auf meinem iPad 2 funktioniert alles super und auch noch flott.
Kann das Ding hier dann nicht eigentlich geschlossen werden? :-)
