### ISSUE TITLE
Aktualisierung von v3.1.9-beta.2 -> v3.2.x

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2439]
- Kein automatischer Reload
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6641a51b-1c28-4e45-b5d0-26aafdf4c4e2)
- Maus funktioniert nicht mehr im Auswahl-Menü -> hängt sich auf
- 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/527ef048-ae92-4578-bdb3-1c5d7e63a15e)

- 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/d7f75687-59e6-4a8a-8bfd-9056c232bdea)
- 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/491f65c3-12b9-41b5-8a3b-5c762222f3e6)

- 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/2c59d6c6-a4a4-484c-ad0b-20e0c6f5b58e)
- F2 -> keine Daten sichtbar
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ac78f0f2-7527-414e-9627-af363d50ff98)
sind aber vorhanden
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3efcec22-fe3c-4bef-8850-00f155fceecb)

**Comment by Zefau** [comment]
Kann das hier zu? Sollte alles behoben sein inzwischen (bzw. ggf. ein anderes Issue für offen sein).

**Comment by mcuiobroker** [comment]
Ja
