### ISSUE TITLE
operators not workin in icon json

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#244]
{"<=10": "battery-10","<=20": "battery-20","<=30": "battery-30","<=40": "battery-40","<=50": "battery-50","<=60": "battery-60","<=70": "battery-70","<=80": "battery-80","<=90": "battery-90","<=100": "battery-100"}

{"<=10":{"color":"FF0000"},"<=20":{"color":"FF5900"},"<=30":{"color":"FF8B00"},"<=40":{"color":"FFB600"},"<=50":{"color":"FBFF00"},"<=60":{"color":"00EE00"},"<=70":{"color":"48D000"},"<=80":{"color":"40B800"},"<=90":{"color":"38A100"},"<=120":{"color":"38A100"}}

**Comment by Zefau** [comment]
You are on v1.0.9 or the latest beta?

**Comment by duczz** [comment]
latest beta

**Comment by Zefau** [comment]
This is a bug indeed, but your hex is also missing `#` and the icon `battery-100` does not exist.

**Comment by Timmes123** [comment]
{">80":"battery-high","<=80":"battery-medium","<=30":"battery-low","<=10":"battery-outline","<=5":"battery-alert-variant-outline"} 
This works in lastest beta.
i think you have to go from high to low.

**Comment by Zefau** [comment]
yeah, this will be fixed though with the next beta

**Comment by Zefau** [comment]
should be resolved with `1.1.0-beta.48`.

**Comment by Timmes123** [comment]
{"<=5":"battery-alert-variant-outline","<=10":"battery-outline","<=30":"battery-low","<=80":"battery-medium",">80":"battery-high"} works now!
