### ISSUE TITLE
Pro licence is invalid!

### ISSUE THREAD

**Issue by mpl1337** [Zefau/ioBroker.jarvis#2441]
Hallo, heute hab ich im Log folgende Meldung bekommen.

<html>
<body>

jarvis.0 | 2023-09-26 11:57:00.131 | warn | Pro licence is invalid!
-- | -- | -- | --

</body>
</html>

Meine Lizenz:

_2023-06-26 12:30:32, #**********
gültig bis 26. Juni 2024, 12:30_

v3.1.9-beta.3

**Comment by Zefau** [comment]
Bitte wende dich an iobroker.jarvis@mailbox.org und schicke die Lizenz- bzw. Rechnungsnummer zur Identifizierung mit.

**Comment by mpl1337** [comment]
Mail ist raus.

**Comment by mpl1337** [comment]
![Screenshot 2023-10-30 124326](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/445d2729-2067-4c27-83df-8c89ab0cd9d9)

Täglich um 11:57 kommt die Info.

**Comment by tschortschde** [comment]
> ![Screenshot 2023-10-30 124326](https://private-user-images.githubusercontent.com/19016821/279044186-445d2729-2067-4c27-83df-8c89ab0cd9d9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDM4NDA2MzIsIm5iZiI6MTcwMzg0MDMzMiwicGF0aCI6Ii8xOTAxNjgyMS8yNzkwNDQxODYtNDQ1ZDI3MjktMjA2Ny00YzI3LTgzZGYtOGM4OWFiMGNkOWQ5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyMzEyMjklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjI5VDA4NTg1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJlNDc1ZWMyNGViZWFhMmRjYmNmNGFkNjE4OTRiZTgyYjNmZjUwMzhkNjRkYzRiNTY4OTY3N2I3NThmOTVjMzgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HvZs8VWRES-H0VQrWz3C3ODogrRZj1rIt1nAdUco2iI)
> 
> Täglich um 11:57 kommt die Info.

Diese Mitteilung bekomme ich übrigens auch.
Einschränkungen konnte ich jedoch keine feststellen...

Grüße und einen guten Rutsch

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.55` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.55` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Paradoxa** [comment]
Hallo @Zefau,
in der Android App wird mir angezeigt "Pro-Features not enabled due to invalid licence".
Über die Web App wird dies als gültig angezeigt und die Features funktionieren.
Was kann ich tun um es zu beheben?
