### ISSUE TITLE
Unsupported devices HM-LC-Dim1T-DR (HomeMatic ) and HmIP-WRC6 (HomeMatic IP)

### ISSUE THREAD

**Issue by cheinelt** [Zefau/ioBroker.jarvis#2443]
### Issue
While importing devices that are correctly identified by IOBroker, Jarvis does not know them (asking to report to developer):
* HomeMatic device HM-LC-Dim1T-DR - a dimmer [Product Link](https://de.elv.com/homematic-funk-dimmaktor-1-fach-hutschienenmontage-hm-lc-dim1t-dr-151589)
* homematic IP device HmIP-WRC6 - 6-times button [Product Link](https://de.elv.com/homematic-ip-wandtaster-hmip-wrc6-6-fach-142308)

Please add support for these devices.
### Hardware/Software Configuration
* Raspberry Pi 4B with 8GB
* latest version of piVCCU3. 
* IOBroker v6.10.1
* Jarvis (v3.1.2)

All devices work fine in the CCU3 and are also recognized correctly by IOBroker.

### How to Reproduce
In Jarvis Configuration Editor 
* go to _Devices_ tab, 
* press _Import Devices_,
* select _HomeMatic / HomeMatic IP via CCU_,
* press _Read Adapters_.
As a result you get HM-LC-Dim1T-DR and HmIP-WRC6 devices listed under _Devices with incorrect configuration (states not found)_ in case you have such in use on your CCU.

**Comment by Zefau** [comment]
Ich bräuchte einmal die Datenpunkte, die du vom Importer übernommen haben möchtest (da mir die Struktur für das Gerät nicht bekannt ist).

Beispielsweise:
```

		"HmIP-BSL": {
			"power": {
				"state": ".4.STATE",
				"action": ".4.STATE"
			},
			"levelTop": {
				"state": ".8.LEVEL",
				"action": ".8.LEVEL"
			},
			"colorTop": {
				"state": ".8.COLOR",
				"action": ".8.COLOR",
				"display": {
					"0": "BLACK",
					"1": "BLUE",
					"2": "GREEN",
					"3": "TURQUOISE",
					"4": "RED",
					"5": "PURPLE",
					"6": "YELLOW",
					"7": "WHITE"
				}
			},
			"levelBottom": {
				"state": ".12.LEVEL",
				"action": ".12.LEVEL"
			},
			"colorBottom": {
				"state": ".12.COLOR",
				"action": ".12.COLOR",
				"display": {
					"0": "BLACK",
					"1": "BLUE",
					"2": "GREEN",
					"3": "TURQUOISE",
					"4": "RED",
					"5": "PURPLE",
					"6": "YELLOW",
					"7": "WHITE"
				}
			}
		},
```

**Comment by cheinelt** [comment]
Wo finde ich die in IOBroker oder Jarvis? Dann stelle ich sie gerne bereit.

**Comment by Zefau** [comment]
@cheinelt sorry für die späte Rückmeldung. 

Einfach in den ioBroker Objekten jeweils zu den beiden Geräten navigieren und einen Screenshot machen und mir sagen, welche Datenpunkte du davon im jarvis brauchst.

**Comment by cheinelt** [comment]
Hi,
  hier kommen die Screenshots:
HM-LC-Dim1T-DR:￼
Hier wird eigentlich nur LEVEL benötigt - ist ein Dimmer für die Hutschiene
HmIP-WRC6:￼￼
Hier wird LOW_BAT, UNREACH aus Channel 0 benötigt und aus Channel 1-6 die gezeigten Taster (hier am Beispiel Channel 1 gezeigt).

Es gibt noch weitere nicht unterstützte Geräte, die ich inzwischen angeschafft habe und manuell zu Jarvis hinzugefügt habe:
HmIP-SMI55-2￼￼
Hier sind aus Channel 0 LOW_BAT und UNREACH wichtig. Channel 1 und 2 sind die Taster (alles benötigt). Channel 3 wird auch alles benötigt (Motion und Licht Sensor)
HmIP-BS2 (Doppelschalter/-aktor):￼
Aus Channel 4 und 8 wird STATE benötigt (Schalterstatus).
HmIP-BSL (Schalter mit LEDs):￼￼
Aus Channel 4 (Schaltaktor) benötige ich STATE. Aus Channel 8 und 12 (hier nur 8 gezeigt) benötige ich COLOR, COLOR_STATUS, DURATION_UNIT, DURATION_VALUE, LEVEL, LEVEL_STATUS, RAMP_TIME_UNIT, RAMP_TIME_VALUE

Viele Grüße,
  Carsten.

**Comment by Zefau** [comment]
Leider zeigt er keine Screenshots an. Kannst du die Email an iobroker.jarvis@mailbox.org schicken?

**Comment by cheinelt** [comment]
Habe ich gemacht gerade. Am 07.01.2024 um 22:26 schrieb Zefau ***@***.***>:﻿
Leider zeigt er keine Screenshots an. Kannst du die Email an ***@***.*** schicken?

**Comment by Zefau** [comment]
Hi,
  hier kommen die Screenshots:

HM-LC-Dim1T-DR: 
<img width="1327" alt="1" src="https://github.com/user-attachments/assets/93222a6e-d119-41c1-b7c9-76bc459dc362">

•	Hier wird eigentlich nur LEVEL benötigt - ist ein Dimmer für die Hutschiene
HmIP-WRC6:  
<img width="1369" alt="2" src="https://github.com/user-attachments/assets/e2e567e0-a50e-412a-afd9-d679a1c7bb1a">
<img width="1282" alt="3" src="https://github.com/user-attachments/assets/27d8e1d7-322b-4019-8735-751bba03bbde">

•	Hier wird LOW_BAT, UNREACH aus Channel 0 benötigt und aus Channel 1-6 die gezeigten Taster (hier am Beispiel Channel 1 gezeigt).

Es gibt noch weitere nicht unterstützte Geräte, die ich inzwischen angeschafft habe und manuell zu Jarvis hinzugefügt habe:

HmIP-SMI55-2  
<img width="1316" alt="4" src="https://github.com/user-attachments/assets/4e310910-0db0-4914-9cd8-f76ff3306806">
<img width="1326" alt="5" src="https://github.com/user-attachments/assets/c80f20bc-2568-4a37-ab50-78aa573a5a3b">

•	Hier sind aus Channel 0 LOW_BAT und UNREACH wichtig. Channel 1 und 2 sind die Taster (alles benötigt). Channel 3 wird auch alles benötigt (Motion und Licht Sensor)
HmIP-BS2 (Doppelschalter/-aktor): 
<img width="1337" alt="6" src="https://github.com/user-attachments/assets/aea9131b-a6ca-4448-9990-20ad0f24adba">
<img width="1318" alt="7" src="https://github.com/user-attachments/assets/d87f0d43-6f15-40a2-a6c5-fafe0bd76552">
<img width="1331" alt="8" src="https://github.com/user-attachments/assets/c4bf45bf-5e42-4bec-afab-2b2eb77be115">

•	Aus Channel 4 und 8 wird STATE benötigt (Schalterstatus).
HmIP-BSL (Schalter mit LEDs):  
•	Aus Channel 4 (Schaltaktor) benötige ich STATE. Aus Channel 8 und 12 (hier nur 8 gezeigt) benötige ich COLOR, COLOR_STATUS, DURATION_UNIT, DURATION_VALUE, LEVEL, LEVEL_STATUS, RAMP_TIME_UNIT, RAMP_TIME_VALUE

Viele Grüße,
  Carsten.


Am 07.01.2024 um 21:08 schrieb Zefau <[notifications@github.com](mailto:notifications@github.com)>:



@cheinelt sorry für die späte Rückmeldung.
Einfach in den ioBroker Objekten jeweils zu den beiden Geräten navigieren und einen Screenshot machen und mir sagen, welche Datenpunkte du davon im jarvis brauchst.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2448

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.57` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.57`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Zefau** [comment]
@cheinelt
