### ISSUE TITLE
Label von Datenpunkt eines Gerätes formatieren

### ISSUE THREAD

**Issue by axha74** [Zefau/ioBroker.jarvis#2444]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running    **V3.1.2**
- [ ] Fehler  :  Warum kann die Bezeichnung (Label) eines Datenpunktes nicht formatiert werden? Wie z.B. mit diesem JSON-Code:
- [ ] {
  "label": "Bad",
  "display": "xx",
  "color": "#ffa500",
  "fontWeight": "bold",
  "fontSize": "96px"
}

**Describe the bug / Beschreibe den Fehler**
Eingetragen im Feld Label bewirkt obiger Code keine Änderung. Auch mittels des Expertenmodus versucht einzutragen hat keinen Erfolg gebracht.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![Bildschirmfoto vom 2023-10-09 09-49-17](https://github.com/Zefau/ioBroker.jarvis/assets/86746345/ce59dac0-8fa9-45d9-a385-ecfb34f346c1)
![Bildschirmfoto vom 2023-10-09 10-03-36](https://github.com/Zefau/ioBroker.jarvis/assets/86746345/49d71e0a-2024-4a1b-97c0-cb91d86d667b)
![Bildschirmfoto vom 2023-10-09 10-04-56](https://github.com/Zefau/ioBroker.jarvis/assets/86746345/1333cc1b-6258-4511-8427-4559a3ac5840)
____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
@axha74 sorry für die späte Antwort. Du hast das JSON in dem Datenpunkt falsch formatiert. Der Schlüssel muss entweder `default` sein oder einer der Werte die der Datenobjekt annehmen kann, siehe https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/v3-fuer-einsteiger/get-started/erklaerung-zu-json bzw. https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/geraet/binding

**Comment by axha74** [comment]
ich habe Deine Hinweise ausprobiert und bin leider zu keinem Erfolg gekommen:
Ich möchte einfach nur das Label "Bad" formatieren (Farbe oder Größe definieren). Folgende Eintragungen habe ich gemacht mit den entsprechenden Ergebnissen

das Gerät ist mit "Bad" bezeichnet und unter Label die entsprechende Formatierung
![Bildschirmfoto vom 2024-02-11 23-03-03](https://github.com/Zefau/ioBroker.jarvis/assets/86746345/f9244fbf-ca5c-43ef-aeb5-ee0615cf3be9)
das Ergebnis in Jarvis als folgender Screenshot vom Gerät:
![Bildschirmfoto vom 2024-02-11 23-09-32](https://github.com/Zefau/ioBroker.jarvis/assets/86746345/76d0cbdb-2ced-4f62-a0d4-3d8e29679762)

und wenn ich das im Widget eintrage, habe ich folgendes Ergebnis
![Bildschirmfoto vom 2024-02-11 23-15-35](https://github.com/Zefau/ioBroker.jarvis/assets/86746345/87fb083e-a212-4ecd-9abc-c9a4757479d9)

Vermutlich kämpfe ich mit einem grundsätzlichen Problem, keine Ahnung welches.
Vielleicht kannst Du mir helfen?
Danke und Grüße

**Comment by mcuiobroker** [comment]
Das musst du im Body Stil setzen.
