### ISSUE TITLE
Nach Downgrade von v3.1.9-beta.2 auf Stable alle Widgets weg

### ISSUE THREAD

**Issue by Reto84** [Zefau/ioBroker.jarvis#2446]
**Prerequisites / Voraussetzungen**
- Version: v3.1.2

**Describe the bug / Beschreibe den Fehler**
Nach einem Downgrade von v3.1.9-beta.2 auf v3.1.2 sind alle Widgets verschwunden:
<img width="473" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/81419898/52d58ae4-0d71-49e4-bc9f-35c021bb8c3d">

Der Datenpunkt Widgets ist aber 3277 Zeilen Lang mit dem Inhalt:
<img width="333" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/81419898/39f436a5-6a7c-474c-a383-a01f7cbf12aa">

Somit ist dann meine ganze Visualisierung weg und nichts geht mehr:
<img width="283" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/81419898/e629ab00-2212-4662-bd36-6c9d6ac4f6e3">

Was könnte ich probieren?

Vielen Dank!
Gruss Reto

**Comment by only4joy** [comment]
@Reto84 Konntest du das Problem lösen?

**Comment by Reto84** [comment]
Hi,

Ja ich habe noch ein altes Backup gefunden, das konnte ich einspielen, mit diesem hat es funktioniert.

Danke&Gruss
Reto

**Comment by mcuiobroker** [comment]
Man kann die Widgets auch wieder aus der neuen Version (v3.19-beta.2) holen.

**Comment by only4joy** [comment]
Danke euch für die Hilfe, bin aber etwas unsicher was ich konkret machen muss.
Ich kann in den Backups (bei der Jarvis Instanz) den Widget Code holen, aber der steht bereits im Datenpunkt. Sorry für die blöde Frage @mcuiobroker , aber was muss ich von wo nach wo kopieren?

**Comment by only4joy** [comment]
Ich konnte das Problem lösen, falls jemand auch das Problem hat:
1. Das Up/Downgrade hat diese "undefined_rnd-d..." hinzugefügt. die muss man entfernen.
2. Bei den Layouts wurden alle Einträge gelöscht, hatte zum Glück noch ein Backup das ich einspielen konnte. Jetzt ist alles wieder da.
