### ISSUE TITLE
HM-LC-Dim1T-DR nicht unterstützt (Geräte mit unbekannten Datenpunkten)

### ISSUE THREAD

**Issue by cheinelt** [Zefau/ioBroker.jarvis#2449]
*HM-LC-Dim1T-DR wird noch nicht unterstützt

- [ ] Jarvis v3.1.2

Beim Importieren von Geräten von _HomeMatic / HomeMatic IP via CCU_ in jarvis wird der HM-LC-Dim1T-DR nicht erkannt, d.h. Jarvis meldet _Geräte mit unbekannten Datenpunkten (bitte dem Entwickler melden)_.

**Comment by Zefau** [comment]
Ich bräuchte einmal die Datenpunkte, die du vom Importer übernommen haben möchtest (da mir die Struktur für das Gerät nicht bekannt ist).

Beispielsweise:
```

		"HmIP-BSL": {
			"power": {
				"state": ".4.STATE",
				"action": ".4.STATE"
			},
			"levelTop": {
				"state": ".8.LEVEL",
				"action": ".8.LEVEL"
			},
			"colorTop": {
				"state": ".8.COLOR",
				"action": ".8.COLOR",
				"display": {
					"0": "BLACK",
					"1": "BLUE",
					"2": "GREEN",
					"3": "TURQUOISE",
					"4": "RED",
					"5": "PURPLE",
					"6": "YELLOW",
					"7": "WHITE"
				}
			},
			"levelBottom": {
				"state": ".12.LEVEL",
				"action": ".12.LEVEL"
			},
			"colorBottom": {
				"state": ".12.COLOR",
				"action": ".12.COLOR",
				"display": {
					"0": "BLACK",
					"1": "BLUE",
					"2": "GREEN",
					"3": "TURQUOISE",
					"4": "RED",
					"5": "PURPLE",
					"6": "YELLOW",
					"7": "WHITE"
				}
			}
		},
```

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@cheinelt
