### ISSUE TITLE
Layout: Add Widgets at any place within layout (not only at the end)

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2452]

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.2` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.2`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Momentan springt er aber immer noch auf festgelegte Stellen. Sollte das nicht aufgehoben werden bzw. verkleinert werden, damit man die Widgets noch besser setzen kann?

**Comment by Zefau** [comment]
Was meinst du mit festgelegte Stellen? Er sollte immer so springen, dass das neu hinzugefügt Widget ganz oben angezeigt wird. Wenn nicht genug Platz nach unten scrollbar ist, dann ist es ggf. mittig.

Was meinst du?

**Comment by mcuiobroker** [comment]
Ich kann die Widgets nur an bestimmte Stellen setzen.
Hab jetzt Grafik von v3.1.8 genommen, da da noch roter Hintergrund
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/774d11bb-f87e-41ca-bd85-7867a0ee66c0)

**Comment by Zefau** [comment]
Also die festgelegten Stellen sind ein Raster von 12.

Für mehr Punkte im Raster gab es schon einen Feature Request, siehe https://github.com/Zefau/ioBroker.jarvis/issues/1585
