### ISSUE TITLE
Nach einfügen vom Wetterwidget - Jarvis Oberfläche blank

### ISSUE THREAD

**Issue by mandragora666** [Zefau/ioBroker.jarvis#246]
Hallo 

Aktuell hab ich leider ein Problem mit dem Wetter Plugin.
Ich hab alles konfiguriert, jedoch wenn ich dann auf speichern gehen lädt die Visualisierung ganz kurz und dann verschwindet die Anzeige und alles ist weiß.
Wenn ich die Seite aktualisiere genau das gleich Phänomen.

Nun komm ich leider auch nicht mehr in den Konfigurationsbereich um das Wetterwidget zu löschen.
Hast jemand eine Ahnung was das sein könnte und wie ich das wieder beheben kann ?
Vor dem aktivieren des Wetterwidgets hat alles bestens funktioniert.

Vielen herzlichen Dank schon mal für die Hilfe und Ratschläge.

mandragora

Aktuell installiert:  1.1.0-beta.24

**Comment by Zefau** [comment]
Bitte auf die aktuelle beta gehen.
