### ISSUE TITLE
Tabs auf iPhones verdeckt durch Dynamic Island

### ISSUE THREAD

**Issue by apachelance** [Zefau/ioBroker.jarvis#2460]
Auf dem iPhone 15 Pro (und vermutlich weiteren Geräten) werden Tabs durch die Dynamic Island verdeckt:

![IMG_0244](https://github.com/Zefau/ioBroker.jarvis/assets/147073963/e18076fe-0803-4a11-8ed0-8531be1a7b3b)

Adapter Version: 3.1.8

**Comment by Juicytronic** [comment]
Also bei mir funktioniert es auf dem iPhone 14 Pro (ebenfalls Dynamic-Island, roter Bereich).

- jarvis-v3.1.8
- Chrome & Safari

Allerdings sieht man die Glocke nicht :,D

**Comment by apachelance** [comment]
Hab vergessen zu erwähnen, dass es in der ioBroker Visu App passiert. Im normalen Browser ist es ok.

**Comment by apachelance** [comment]
Hat sich erledigt. Wenn man in der ioBroker Visu App die Statusleiste aktiviert, rutscht die Anzeige nach unten, so dass die Tabs nicht verdeckt werden.
