### ISSUE TITLE
[Zukunft] wie geht es weiter?

### ISSUE THREAD

**Issue by mpl1337** [Zefau/ioBroker.jarvis#2461]
Hallo,

leider passierte in den letzten 6 Monaten wenig bis Garnichts. Wurde das Projekt eingestampft? geht's demnächst weiter? Könnte sich der Programmierer zu Wort melden und die Community aufklären?

**Comment by Zefau** [comment]
Gibt doch einen aktuellen Alpha Kanal?

**Comment by mpl1337** [comment]
Ist der Alpha Kanal in der Heatmap mit drin?

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/89dccdca-b906-46d6-883b-66b42c70ce18)

Ich habe vollstes Verständnis dafür, dass du aus privaten Gründen an dem Projekt nicht weiter arbeiten kannst/konntest.

Dennoch würde ich gerne wissen, wie es mit dem Projekt weiter geht. Bist du aktiv dran? Wirst du es in absehbarer Zeit sein? Machst du es alleine? Werden erst Bugfixes oder neue Funktionen gestellt?

**Comment by bsteimer** [comment]
Hallo @Zefau auch von mir meine größte Hochachtung vor der Leistung dieses Projekts. Und mir ist auch bewusst, dass das nicht deine Hauptjob ist. Du hast dich aber auch irgendwann entschiedenen eine Paidversion einzuführen (völlig in Ordnung) nur erwarte ich damit als "Kunde" auch ein bisschen gehört zu werden, so wie ich es von anderen Projekten gewohnt bin die Paidversionen oder Sponsorships anbieten. Mein Issue  https://github.com/Zefau/ioBroker.jarvis/issues/2457 hat seit zwei Wochen leider keine Aufmerksamkeit erfahren. Schade.

**Comment by apachelance** [comment]
@Zefau Würde mich auch interessieren, da ich die Visualisierung für sehr ansprechend und flexibel halte. Bin kürzlich ebenfalls auf Pro gegangen.

**Comment by Zefau** [comment]
Alpha-Kanal ist im vollen Gange. Kann das Issue zu?

**Comment by apachelance** [comment]
Ja, danke 👍

**Comment by mpl1337** [comment]
Von mir aus auch, jedoch mit der bitte die popup "Problematik" auch zu behandeln :)

**Comment by Zefau** [comment]
> Von mir aus auch, jedoch mit der bitte die popup "Problematik" auch zu behandeln :)

Welches Issue meinst du? Von dir gibt es nur https://github.com/Zefau/ioBroker.jarvis/issues/2441, oder?
