### ISSUE TITLE
Ab Version 3.1.4 probleme mit Socket-Port <> 8400

### ISSUE THREAD

**Issue by thoml95** [Zefau/ioBroker.jarvis#2464]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [3.1.8] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**

**Describe the bug / Beschreibe den Fehler**
Ich nutze zwei getrennte Instanzen von Jarvis um eine Visualisierung nur für mein NSPanelPro zu haben. Die zweite Instanz (.1) läuft über Socket-Port 8401, dies hat auch ohne Probleme funktioniert unter der 3.1.2. 
Alle Versionen die neuer sind (getestet bis zur 3.2.0-Alpha3) scheinen bei einem Reload der Seite auf den standart Port 8400 zugreifen zu wollen. 

**Screenshots**

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/89551652/baf9a3c8-f6c7-4475-ab99-812428fdcfbf)

**Comment by Zefau** [comment]
besteht das Problem noch mit der aktuellen Alpha?

**Comment by thoml95** [comment]
ich hab jetzt bis zur aktuellen beta getestet, leider funktioniert damit garnichts mehr. Mir fehlen mehrere Geräte und alle Widgets obwohl die Datenpunkte gefüllt sind.

Beim testen der Versionen wurde aber teilweise auf die Datenpunkte der Instanz 0 zugegriffen obwohl diese deaktiviert ist, dann aber über den Socket-Port der Instanz 1. 
Mit geschrieben hab ich aus Zeitmangel heute nicht, evtl. schaffe ich es demnächst nochmal. 

Bin jetzt zurück auf die 3.1.8 was aber nur durch einspielen eines Backups funktionierte.

Im Log gab es außerdem folgende Warnungen bei jeder getesteten Version.
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/89551652/aa249471-6bdf-4685-884c-0ce2144d9608)

**Comment by Zefau** [comment]
Beim Upgrade von 3.1 auf 3.2 musst du alles schließen. Socket-io wird abgeschafft und durch WebSocket ersetzt. Deine Fehlermeldungen werden dadurch verursacht, dass das Frontend nach Socket-IO verbinden will, was es mit 3.2 nicht mehr gibt.

**Comment by fladdie** [comment]
> Beim Upgrade von 3.1 auf 3.2 musst du alles schließen. Socket-io wird abgeschafft und durch WebSocket ersetzt. Deine Fehlermeldungen werden dadurch verursacht, dass das Frontend nach Socket-IO verbinden will, was es mit 3.2 nicht mehr gibt.

@Zefau was meinst du denn mit "alles schließen"? Ich habe das jetzt schon auf zwei verschiedenen IOBroker installationen versucht ein Update von 3.1.8 auf 3.2.10 zu machen. Kannst du genauer beschreiben was beim Update zu beachten ist?
