### ISSUE TITLE
v3.2.0-alpha.6 Filterung funktioniert nicht mehr korrekt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2466]
DP  `0_userdata.0.jarvis.deviceInfo.html`
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9bf8157e-bec1-412b-ba47-27bd0fe8bbbe)
Ist aber vohanden, wurde bislang auch gefunden, jetzt zeigt er nur noch bis `0_userdata.0.jarvis` was an

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/89fdfa19-b5b5-4b17-bdca-ae41f3498323)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.7` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.7` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@mcuiobroker kann das zu?

**Comment by mcuiobroker** [comment]
Hängt sich immer noch auf
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ea07f0e8-343e-4a11-aa30-a3415a0ff021)

**Comment by Zefau** [comment]
Das ist ja ein bekanntes, anderes Problem. Du kannst die Filterung dadurch bedingt aber nicht testen meinst du?

**Comment by mcuiobroker** [comment]
Ja ich kann gar nichts machen?

**Comment by mcuiobroker** [comment]
Fehler noch vorhanden. 


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8757e92d-295c-476b-b0ee-801dc9a66c3e)

er findet nur bis


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/14fd1888-ad72-4a12-bbdf-c93a241b2d4e)



![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a828c799-8956-418f-b038-307c4bd46be5)

**Comment by Zefau** [comment]
Kannst du das noch genauer darstellen? Ich bekomme es leider nicht reproduziert.

Habe zwei Geräte mit folgenden Datenpunkten:
1. `0_userdata.0._test.tests.html`
   
   ![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/c6968ef3-1b70-49ea-97ad-967172a6f195)

2. `0_userdata.0._test.jarvis._tests.testi`
   
   ![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/a2aa9afa-acb9-4faa-a079-7e224c683c5e)

Suche nach `0_userdata.0._test.jarvis._tests.testi` ergibt 1 Treffer:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/3c347b32-980d-4f0a-acfe-2e9d485386a3)


Suche nach `0_userdata.0._test` ergibt 2 Treffer:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/e3bc23d0-e1b4-4145-959a-d0245b78da0c)

**Comment by mcuiobroker** [comment]
Hab jetzt nochmal upload gemacht. Hat nicht geholfen.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/58ef1daf-fb5d-40e2-a77e-75ab3d5bd466)
Gebe ich `deviceInfo` ein -> nix
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/83e57f58-97a7-4b29-905b-1aa28dc545df)

bei `deviceinfo`
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5fd2fffd-6615-4b07-a1d5-dc7d9b29eb70)


![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/891a1c47-3d5d-40c2-8872-5a66c5022c8b)

**Comment by Zefau** [comment]
> Es hängt also sehr wahrscheinlich mit Groß-/Kleinschreibung zusammen?

Jo, das scheint es zu sein.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
