### ISSUE TITLE
v3.2.0-alpha.6 Unterschiedliche Darstellung der Elemente in der Geräte-Übersicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2467]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/38b4742c-59f5-46d2-a0d8-a4ff30e939ed)

Mal mit Trennstrich, mal ohne?
Müsste display:inline-block sein ist aber none.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/1110eb44-2716-4380-b905-18eac4f00863)

Hiermit wird der Strich angezeigt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/fa71b45d-eac1-4493-aef0-e39b1c5a1c78)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.7` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.7` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@mcuiobroker kann das zu?

**Comment by mcuiobroker** [comment]
Ja. Passt. Danke.
Wenn möglich bitte bei Geräte Liste optional in den Einstellungen "alle" statt "15" auswählbar. Danke.


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/72b0fc3d-e217-48eb-8094-479699fe76b7)

**Comment by Zefau** [comment]
`Alle` ist auswählbar. Du meinst sicherlich, dass es dauerhaft gespeichert wird?

**Comment by mcuiobroker** [comment]
Ja genau

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Wo ist die Einstellung? Kann sie nicht finden.

**Comment by Zefau** [comment]
Gibt keine. Die letzte Einstellung wird gespeichert.

**Comment by mcuiobroker** [comment]
Passt. Danke.
