### ISSUE TITLE
Seit 3.2.0 absolut keine Socketverbindung mehr

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2468]
ich bekomme seit der 3.2.0 keine Verbindung mehr zu Jarvis.
hier meine Einstellungen
Jarvis
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/1ae09438-5bf8-4a97-b07c-ffe1378f641e)
web
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/43d78ed4-af6d-4bbb-a5fe-8e3f15368cdd)
socketio
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/66cd4944-2c5f-4639-a0f0-8905cac2d6c8)
LOG ioBroker
`<html>
<body>

jarvis.0 | 2023-11-08 11:47:28.791 | info | State value to set for "jarvis.0.settings.pageHomeReturn" has to be type "number" but received type "string"
-- | -- | -- | --
jarvis.0 | 2023-11-08 11:47:28.626 | info | Found Backups for devices.
jarvis.0 | 2023-11-08 11:47:28.622 | error | Error opening web socket: Cannot read properties of null (reading 'on')
jarvis.0 | 2023-11-08 11:47:28.621 | error | WebSocketServer is not a constructor
jarvis.0 | 2023-11-08 11:47:28.620 | debug | Connection: Using options: {}
jarvis.0 | 2023-11-08 11:47:28.620 | debug | Connection: Using non-secure HTTP-Server
jarvis.0 | 2023-11-08 11:47:28.619 | debug | Connection: ioBroker host detected with NUC-ioBroker (IP: 192.168.100.85).
jarvis.0 | 2023-11-08 11:47:28.617 | debug | Web Configuration: {"port":8082,"auth":false,"secure":false,"bind":"0.0.0.0","cache":false,"socketio":"","simpleapi":false,"defaultUser":"admin","ttl":3600,"certPublic":"","certPrivate":"","certChained":"","addUserName":false,"forceWebSockets":false,"whiteListEnabled":false,"leEnabled":false,"leUpdate":false,"leCheckPort":80,"loginBackgroundColor":"","loginBackgroundImage":false,"basicAuth":false,"disableExtensions":false,"disableStates":false,"disableFilesObjects":false,"defaultRedirect":"","usePureWebSockets":false,"compatibilityV2":true,"staticAssetCacheMaxAge":60,"language":"","startDisabledExtensions":false,"showFolderIndex":false,"whiteListSettings":{"default":{"user":"admin"}}}
jarvis.0 | 2023-11-08 11:47:28.603 | info | Found Backups for styles.
jarvis.0 | 2023-11-08 11:47:28.598 | info | Found Backups for widgets.
jarvis.0 | 2023-11-08 11:47:28.594 | info | Found Backups for settings.
jarvis.0 | 2023-11-08 11:47:28.593 | info | Found Backups for scripts.
jarvis.0 | 2023-11-08 11:47:28.592 | info | Found Backups for layout.
jarvis.0 | 2023-11-08 11:47:28.519 | debug | Scheduled for 10:24
jarvis.0 | 2023-11-08 11:47:28.498 | info | starting. Version 3.2.0-alpha.6 (non-npm: Zefau/ioBroker.jarvis#a0d7b1e32f7eb46a810db4f25399812724383ca9) in /opt/iobroker/node_modules/iobroker.jarvis, node: v18.17.1, js-controller: 5.0.16

</body>
</html>`

LOG EDGE Browser

`App Welcome to jarvis v3.2.0-alpha.6
index-019a4f0f.js:117 App using instance 0.
index-019a4f0f.js:117 App Time - Router Ready: 6.00ms
index-019a4f0f.js:50 11:48:44.028 | INFO | CONNECTION | Connecting to ws://192.168.100.85:8400 (#1)...
index-019a4f0f.js:113  WebSocket connection to 'ws://192.168.100.85:8400/' failed: 
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
index-019a4f0f.js:50  11:48:46.079 | WARN | SOCKET | Connecting to ws://192.168.100.85:8400 errored!
_message @ index-019a4f0f.js:50
warn @ index-019a4f0f.js:51
socket.onerror @ index-019a4f0f.js:113
error (asynchron)
(anonymous) @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50  11:48:46.087 | ERROR | CONNECTION | Failed connecting to ws://192.168.100.85:8400 (#1)!
_message @ index-019a4f0f.js:50
error @ index-019a4f0f.js:51
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50 11:48:46.087 | INFO | CONNECTION | Connecting to http://192.168.100.85:8400 (#2)...
index-019a4f0f.js:113  WebSocket connection to 'ws://192.168.100.85:8400/' failed: 
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
index-019a4f0f.js:50  11:48:48.138 | WARN | SOCKET | Connecting to ws://192.168.100.85:8400 errored!
_message @ index-019a4f0f.js:50
warn @ index-019a4f0f.js:51
socket.onerror @ index-019a4f0f.js:113
error (asynchron)
(anonymous) @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50  11:48:48.144 | ERROR | CONNECTION | Failed connecting to http://192.168.100.85:8400 (#2)!
_message @ index-019a4f0f.js:50
error @ index-019a4f0f.js:51
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50 11:48:48.145 | INFO | CONNECTION | Connecting to https://192.168.100.85:8400 (#3)...
index-019a4f0f.js:113  WebSocket connection to 'wss://192.168.100.85:8400/' failed: 
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
index-019a4f0f.js:50  11:48:50.199 | WARN | SOCKET | Connecting to wss://192.168.100.85:8400 errored!
_message @ index-019a4f0f.js:50
warn @ index-019a4f0f.js:51
socket.onerror @ index-019a4f0f.js:113
error (asynchron)
(anonymous) @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50  11:48:50.205 | ERROR | CONNECTION | Failed connecting to https://192.168.100.85:8400 (#3)!
_message @ index-019a4f0f.js:50
error @ index-019a4f0f.js:51
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50 11:48:50.205 | INFO | CONNECTION | Connecting to https://192.168.100.85:443 (#4)...
index-019a4f0f.js:113  WebSocket connection to 'wss://192.168.100.85/' failed: 
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
index-019a4f0f.js:50  11:48:52.255 | WARN | SOCKET | Connecting to wss://192.168.100.85:443 errored!
_message @ index-019a4f0f.js:50
warn @ index-019a4f0f.js:51
socket.onerror @ index-019a4f0f.js:113
error (asynchron)
(anonymous) @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50  11:48:52.261 | ERROR | CONNECTION | Failed connecting to https://192.168.100.85:443 (#4)!
_message @ index-019a4f0f.js:50
error @ index-019a4f0f.js:51
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50 11:48:52.261 | INFO | CONNECTION | Connecting to http://192.168.100.85:80 (#5)...
index-019a4f0f.js:113  WebSocket connection to 'ws://192.168.100.85/' failed: 
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
index-019a4f0f.js:50  11:48:54.304 | WARN | SOCKET | Connecting to ws://192.168.100.85:80 errored!
_message @ index-019a4f0f.js:50
warn @ index-019a4f0f.js:51
socket.onerror @ index-019a4f0f.js:113
error (asynchron)
(anonymous) @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
connect @ index-019a4f0f.js:113
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:50  11:48:54.310 | ERROR | CONNECTION | Failed connecting to http://192.168.100.85:80 (#5)!
_message @ index-019a4f0f.js:50
error @ index-019a4f0f.js:51
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
(anonymous) @ index-019a4f0f.js:113
Promise.catch (asynchron)
discover @ index-019a4f0f.js:113
onConnect @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
created @ index-019a4f0f.js:117
callWithErrorHandling @ index-019a4f0f.js:1
callWithAsyncErrorHandling @ index-019a4f0f.js:1
callHook$1 @ index-019a4f0f.js:1
applyOptions @ index-019a4f0f.js:1
finishComponentSetup @ index-019a4f0f.js:1
handleSetupResult @ index-019a4f0f.js:1
setupStatefulComponent @ index-019a4f0f.js:1
setupComponent @ index-019a4f0f.js:1
ae @ index-019a4f0f.js:1
oe @ index-019a4f0f.js:1
F @ index-019a4f0f.js:1
ye @ index-019a4f0f.js:1
mount @ index-019a4f0f.js:1
r.mount @ index-019a4f0f.js:1
start$2 @ index-019a4f0f.js:117
await in start$2 (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
Promise.then (asynchron)
(anonymous) @ index-019a4f0f.js:117
(anonymous) @ index-019a4f0f.js:1
(anonymous) @ index-019a4f0f.js:1875
index-019a4f0f.js:117  App-hGejAmgnwn undefined Event {isTrusted: true, type: 'error', target: WebSocket, currentTarget: WebSocket, eventPhase: 2, …}`

LOG EDGE als Scrennpic

![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/7540c3ae-3169-4e93-b833-994918568667)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.7` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.7` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
@Zefau alpha 7 und 8 bisher ohne Auffälligkeiten
