### ISSUE TITLE
Slider as Show Only (no possibility to move the slider)

### ISSUE THREAD

**Issue by Benno-O** [Zefau/ioBroker.jarvis#2469]
I show the target temperature as slider where I can change the target temperature. 
In comparison I want to show the actual temperature as slider but the actual temperature should not be changed by the slider. So it should only show but no interaction. 

![image](https://github.com/Zefau/ioBroker.jarvis/assets/99363279/df7c435b-33f1-4af9-86ca-f06827f869ea)

The image above shows what I want to achieve. I did not find any easy way to do it. 

I can imagine that it is also helpful for others as well.

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/issues/1756

**Comment by mcuiobroker** [comment]
Bis es umgesetzt wurde:
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/scripts-3.1.x-pro/statelist/statelistitemlock
