### ISSUE TITLE
v3.2.0-alpha.7 nicht nutzbar Speicher läuft direkt voll

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2470]
Nach 10 Sekunden schon 600-700 MB.

**Comment by Zefau** [comment]
Der Adapter im ioBroker backend oder der Browser bzw. das jarvis frontend? Bei mir funktioniert es soweit.

**Comment by mcuiobroker** [comment]
Frontend. Was kann wo nachschauen?

**Comment by Zefau** [comment]
Backend wäre
![image](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/5963d036-60a1-4438-a9a0-6eb9ef3632cf)

Frontend wäre im Task Manager:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/73e6a12b-cd41-4bd6-a5cf-4d46be6258c3)

**Comment by mcuiobroker** [comment]
Ja da hab ich ja schon geschaut und gemerkt, dass der Speicher voll läuft.

**Comment by mcuiobroker** [comment]
HIlft das?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8c8af847-fff0-4cc7-b528-da155696d8d6)

**Comment by Zefau** [comment]
Keine Ahnung, woran es liegt. Muss mal schauen, was ich seit der letzten Version konkret geändert habe.

Passiert es denn direkt beim Zugriff auf jarvis? Oder nur bei der jarvis Konfiguration?

**Comment by mcuiobroker** [comment]
Sowohl als auch. Egal was ich mache. War aber schon ab alpha.

**Comment by hosabeni** [comment]
Ich kann das Verhalt bestätigen. Auch beim Firefox läuft der Speicher voll und das Browserfenster reagiert dann auch nicht mehr.

**Comment by mcuiobroker** [comment]
Hängt es evtl mit #2438 zusammen?
Läuft window.Socket.setState usw. dann noch oder ?

**Comment by Zefau** [comment]
Also ist das Problem neu mit alpha-7 oder waren schon frühere alpha Versionen betroffen?

**Comment by mcuiobroker** [comment]
War auch schon früher, aber nicht so schnell?

**Comment by mcuiobroker** [comment]
v8:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0a8a260e-64a9-4f05-b283-3e534cfa2d69)
Die Logs kommen erst gar nicht, obwohl er das Frontend anzeigt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/088b7635-5260-4725-a6b5-1fee5232585e)

**Comment by Zefau** [comment]
Hast du die Module ScriptStatus und / oder AdapterStatus drin und könntest die testweise mal rauslöschen? Ist es dann (nach einem full reload) besser?

**Comment by mcuiobroker** [comment]
Muss erst zurück auf v3.1.0-beta.2
in v8 kann man gar nichts machen.
Müssen alle Module raus aus allen TABs?

**Comment by mcuiobroker** [comment]
3.2.0-alpha.8

**Comment by Zefau** [comment]
genau

**Comment by mcuiobroker** [comment]
So darf es bleiben
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e8ff5b61-4c2f-4ec0-8731-9a7d16f48438)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/74a9f706-fac8-45f5-b913-586976d1d6ba)

**Comment by Zefau** [comment]
Ne passt so

**Comment by mcuiobroker** [comment]
Jetzt kommen die Logs
Aber jetzt ist es so wie bei der ersten alpha.
Widgets sind unterstrichen und es werden die Styles angezeigt.
Liegt daran, dass die Widgets erst gar nicht angezeigt wurden und ich auf Styles geklickt habe.

Speicher läuft weiterhin voll
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6cb38762-0bb3-441e-b36d-3b9fb723e780)

**Comment by mcuiobroker** [comment]
v3.20.-alpha.9 keine Verbesserung.

**Comment by cooper1988** [comment]
Kann ich bestätigen.
Alle Alpha-Versionen nicht nutzbar. Teilweise schaft es mein Wmadtablet nicht die Seiten zu laden und ich musste ebenfalls auf die 3.1.9 b2 zurück.

Adapter genau wie mcu.

**Comment by Bernd9000** [comment]
Dito, hier auch mit 3.2.0-alpha.9
Frontend und Backend betroffen.
Im Backend gehts hoch auf über 500MB und dann wird die jarvis Instanz neu gestartet.
IOB Admin Seite ist dann eine Zeitlang nicht erreichbar.

- Node.js v18.18.2
- NPM 9.8.1
- js-controller: 5.0.16

**Comment by Bernd9000** [comment]
Hab mal die Versionen getestet, der Fehler fing ab Version 3.1.9-beta.3 an. 
3.1.9-beta.2 war noch Okay

**Comment by Bernd9000** [comment]
@Zefau 
So, hab ein Auslöser herausgefunden.
Sobald ein Binding unter "Icon" oder "Icon Style" in einem Gerät eingetragen ist taucht der Fehler auf.
Getestet hatte ich bei einer Tasmota Steckdose mit dem "States" power und einem switchAction.
Das icon und di9e Frabe soll sich ändern wenn Gerät offline ist.
Sobald ich die Bindings raus nehme ist alles i.O.


Icon:
{"'{0_userdata.0.Tasmota.Heizung-Bad.Online}'='Offline'":"mdi:radiator blink","true":"mdi:radiator","false":"mdi:radiator"}

Icon Style:
{"'{0_userdata.0.Tasmota.Heizung-Bad.Online}'='Offline'":{"color":"#FF0"},"true":{"color":"#0F0"},"false":{"color":"#F00"}}

**Comment by Zefau** [comment]
Kann das Issue hier bzgl. des Volllaufens des Speichers zu?

**Comment by mcuiobroker** [comment]
Ja
