### ISSUE TITLE
3.1.9 beta 2 - Unterschiedlich Schriftfarben in States

### ISSUE THREAD

**Issue by apachelance** [Zefau/ioBroker.jarvis#2473]
States haben teils unterschiedliche Grau-Töne in den Widgets, so dass es zu Farbabweichungen in der Darstellung kommt. Das passiert in unterschiedlichen Widgets, als auch unterschiedlichen Gewerken, siehe Posts ab: https://forum.iobroker.net/topic/59201/jarvis-v3-1-x-just-another-remarkable-vis/1255

Teilweise wird #ffffffb3 verwendet und teils #999999 (RGB: 153,153,153).

<img width="413" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/147073963/66bdbf64-1b25-4fbc-b79b-7446008d44b6">

Getestet wurde auch mit deaktivierten Styles in Jarvis.

**Comment by Zefau** [comment]
Es gibt einige wenige vordefinierte Styles z.T. abhängig des Gewerks des Geräts, u.a. für `false` die Schriftfarbe `#999`. Mit https://github.com/Zefau/ioBroker.jarvis/issues/188 wird das durch den Benutzer editierbar sein.

**Comment by apachelance** [comment]
Ok, danke. Dann können wir das hier schließen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.6` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.6` should fix the bug - please verify. If the bug has been solved, you may close the issue.
