### ISSUE TITLE
[3.2.0-alpha.9] Lädt uneendlich

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2475]
Hej,

siehe Bild. Es lässt sich nichts mehr drücken.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/2dfcd03f-68c7-42db-8fe1-652f9700e23c)

VG

**Comment by mcuiobroker** [comment]
Wieder zurück auf v3.1.9-beta.2

**Comment by Zefau** [comment]
`v3.2.0-alpha.11`
