### ISSUE TITLE
Premium Lizens

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#2476]
Gefühlt haben wir jedes Jahr irgendetwas mit den Lizensen. 

Ja Paypal hat automatisch abgebucht - Check
Lizens Backup kam per Email - Check

Jedoch scheint die Lizens nicht automatisch zu wechseln oder zu erneuern im Jarvis. Das finde ich schade. Vorallem da ich aktuell in den Ferien bin und nur Zugriff auf das Jarvis Dashboard habe und mir die ganzen Premium funktionen / Seiten usw. entfernt wurden.  

Steuern ist nun nicht mehr wie gewohnt möglich. 

Ich finde da müsste was anderes her. z.b. 1 Hash bei welchem du halt eine DB bei dir führst und das Datetime immer wieder nach dem bezahlen um 1 Jahr+1 Woche oder so verlängerst. Dann wäre man an online gezwungen. Evtl kann man es optional machen, OfflineLizens und OnlineLizens. 

Jetzt ist es grad ärgerlich, weil ich nicht zuhause bin. 

Grüsse

**Comment by Bernd9000** [comment]
Hast Du Zugriff auf den IOBroker und kannst diesen neu starten ?
Wäre ein Versuch...
Hier hat es geklappt mit der neuen Lizens ohne das ich was umstellen mußte.
jarvis Version ist hier v3.1.9-beta.2

**Comment by ma-gu-16** [comment]
Guter call aber leider kein Zugriff derzeit.

Alternativ wäre gut wenn wenigstens die Option gibt den key via jarvis einzugeben. Also wenn das popup kommt Lizenz abgelaufen, ein Fenster hier erneuern oder so.

**Comment by Zefau** [comment]
Sorry dafür. Sollte eigentlich automatisch getauscht werden, aber irgendwie klappt das nicht immer. Ich wollte für v3.2 das ioBroker.jarvis backend re-factoren (also nochmal von Grund auf neu entwickeln), da über die Zeit viel hinzu kam. Im Rahmen dessen schaue ich mir das mal an.

**Comment by ma-gu-16** [comment]
> Sorry dafür. Sollte eigentlich automatisch getauscht werden, aber irgendwie klappt das nicht immer. Ich wollte für v3.2 das ioBroker.jarvis backend re-factoren (also nochmal von Grund auf neu entwickeln), da über die Zeit viel hinzu kam. Im Rahmen dessen schaue ich mir das mal an.

gibt es eine roadmap  des projekts? ich vermute mal das du ja schon pläne hast. wäre sicher interessant eine art roadmap mit erwarteten datum usw zu haben. vielleicht auch ein paar infos, ob das ganze projekt alleine oder im team umgesetzt wird, sowie haupt oder nebenberuflich. ich denke mal das würde auch viele andere tickets hier beantworten.  meine erwartung ist ja eine andere wenn ich jemand ein ticket ache, der das nebenberuflich untentgetlich mache oder ob ich z.b. einem konzern wie amazon eins mache :)  up to you natürlich.

**Comment by Zefau** [comment]
jarvis wird von mir alleine nebenberuflich entwickelt. Eine Roadmap gab es in der Vergangenheit, aber für v3.2 ist das nicht aktuell gepflegt, aber siehe https://github.com/users/Zefau/projects/2/views/14. Da fliegen aber noch paar Sachen raus.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.55` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.55` should fix the bug - please verify. If the bug has been solved, you may close the issue.
