### ISSUE TITLE
Beim HistoryGraph kann kein Sensor hinzugefügt werden

### ISSUE THREAD

**Issue by HolgerDoerrschuck** [Zefau/ioBroker.jarvis#2477]
Wenn man beim HistoryGraph einen Sensor hinzufügt, akann man keine ActionState auswählen

![Screenshot 2023-12-03 173046](https://github.com/Zefau/ioBroker.jarvis/assets/101668235/e7eb16fa-9b0e-4af1-a2c1-32f95a5ab809)

**Comment by HolgerDoerrschuck** [comment]
Das passt alles – ich musste heute den Sensor vom Gartenhaus neu anlernen. Bei den bestehenden Sensoren im Graph kommen auch alle Action States. Lege ich einen neuen Graph an, werden auch bei den bestehenden Sensoren kein States, Histry, Ack angezeigt

 



 

Von: mcuiobroker ***@***.***> 
Gesendet: Sonntag, 3. Dezember 2023 17:42
An: Zefau/ioBroker.jarvis ***@***.***>
Cc: HolgerDoerrschuck ***@***.***>; Author ***@***.***>
Betreff: Re: [Zefau/ioBroker.jarvis] Beim HistoryGraph kann kein Sensor hinzugefügt werden (Issue #2477)

 

Wie sieht denn der Geräte-DP lastupdated aus? Hat der eine History zugeordnet im ioBroker-DP. Bitte auch Objektdaten rein stellen.
Welche Version von jarvis?

**Comment by mcuiobroker** [comment]
Welche Version von jarvis?

**Comment by mcuiobroker** [comment]
Versionen > v3.1.9-beta.2 sind nicht einsatzfähig.

**Comment by HolgerDoerrschuck** [comment]
mit 3.1.9 ging mein Kalender nicht und mit >3.1.9-beta.2 geht der Graph nicht???
und wohin reporte ich Bug's zur Beta?

**Comment by mcuiobroker** [comment]
Mit Angabe der Version hier bei den Issues.

**Comment by Zefau** [comment]
Besteht das Problem noch mit der aktuellen v3.2 beta?

Wenn ja, kannst du das Problem nochmal genauer beschreiben? Ich versteh nicht genau, was nicht funktioniert.

**Comment by HolgerDoerrschuck** [comment]
Hi Zefau,

 

cool – it works now. Also the calendar is showing immediately. 

 

Thanks Holger

 

Von: Zefau ***@***.***> 
Gesendet: Sonntag, 11. Februar 2024 14:44
An: Zefau/ioBroker.jarvis ***@***.***>
Cc: HolgerDoerrschuck ***@***.***>; Author ***@***.***>
Betreff: Re: [Zefau/ioBroker.jarvis] Beim HistoryGraph kann kein Sensor hinzugefügt werden (Issue #2477)

 

Besteht das Problem noch mit der aktuellen v3.2 beta?

Wenn ja, kannst du das Problem nochmal genauer beschreiben? Ich versteh nicht genau, was nicht funktioniert.

**Comment by HolgerDoerrschuck** [comment]
works with the latest version
