### ISSUE TITLE
Expert Mode does not work

### ISSUE THREAD

**Issue by Coalado** [Zefau/ioBroker.jarvis#2479]
Jarvis v3.1.8:
If I click the <> Button nothing happens -  except for some errors in the console:
e.g. UNKNOWN State Settings: Proxy(Object) configExpertMode undefined true

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.54` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.54` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by kruegertom** [comment]
same issue here ... but  v3.1.8 works fine on one system with the same version and doesn't works on another:
https://forum.iobroker.net/topic/72949/jarvis-expert-mode-funktioniert-nicht

**Comment by dahljoa** [comment]
jarvis v3.1.8 on Synology DS224plus with ContainerManager 'portainer.io' und iobroker:latest the same issue!
