### ISSUE TITLE
Blankscreen after adding DateTime

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#248]
Ich habe gerade das Datetime Widget hinzugefügt.
jetzt öffnet sich die visu nur für ca 1 Sekunde, dann wird der bildschirm leer.
ich habe keine möglichkeit das widget wieder zu entfernen, da selbst wenn ich in der sekunde das Tab wechsle oder auf Einstellungen drücke, verschwindet der inhalt einfach sobald die sekunde vorbei ist. 

getestet auf beta47

**Comment by Timmes123** [comment]
![image](https://user-images.githubusercontent.com/73311538/97079281-e4cf6c80-15f2-11eb-95df-b352177c20a1.png)

**Comment by Zefau** [comment]
Bitte Screenshot der Konsole. Also rechts der zweite Reiter (du hast den ersten Reiter auf).

**Comment by Timmes123** [comment]
![image](https://user-images.githubusercontent.com/73311538/97079565-514b6b00-15f5-11eb-9fd0-b0a20bc76d68.png)

**Comment by Timmes123** [comment]
mir fällt gerade was dazu ein.
als ich das widget hinzugefügt habe, habe ich keinerlei einstellungen verändert.
einfach einfügen -> speichern
mir ist dabei aufgefallen, dass im format stand "d.mm. usw" also nur ein d
ich hab mich schon gefragt, ob das nicht "dd" sein müsste, aber hab mir dann nichts weiter dabei gedacht.

**Comment by Zefau** [comment]
Der Fehler liegt scheinbar bei der internen Formatierung der Zeiten für Sonnenauf- und Untergang.

**Comment by Zefau** [comment]
@Timmes123 hast du die Koordinaten im ioBroker gepflegt?

**Comment by Timmes123** [comment]
meinst du die hier?
![image](https://user-images.githubusercontent.com/73311538/97080248-40512880-15fa-11eb-9a4b-554fe6cbd751.png)

**Comment by Timmes123** [comment]
ja du hast recht. ich hab die koordinaten eingefügt, jetzt lädt die visu wieder :-)

**Comment by Zefau** [comment]
Ok, danke, ich werd jarvis dahingehend nochmal härten.

**Comment by Zefau** [comment]
should be resolved with `1.1.0-beta.48`.

**Comment by Timmes123** [comment]
getested mit beta 48
Koordinaten leer: visu lädt, sonnenauf/untergang bleibt leer
Koordinaten: NaN (keine ahnung woher der text bei mir kommt, bzw kam?
Visu blankscreen.
Evtl könntest du beim laden der koordinaten ob tatsächlich ne zahl drin steht, nicht nur das feld "nicht leer" ist

**Comment by Zefau** [comment]
Kannst du nochmal mit `v1.1.0-beta.51` probieren bitte?

**Comment by Timmes123** [comment]
getestet mit beta 52

sowohl koordinaten leer, als auch mit einem beliebigen string kein fehler mehr :-)
