### ISSUE TITLE
v3.2.0-alpha.11 Einige Fehler Anzeigen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2481]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5bb4184d-df0d-4899-8b87-3b86c574d7f8)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/b40d89bd-7f5e-4a38-a453-4a454bda7424)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5b02afe0-c88b-4bf2-85b5-2303c36a3c59)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e0a3c37a-0396-48e5-bce5-3b5766435052)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/33d446e7-903d-456f-a018-9cc9b44e0148)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.12` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.12` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Zurzeit keine Fehler
v3.2.0-alpha.30
