### ISSUE TITLE
v3.2.0-alpha.12 Geräte Liste ist leer

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2484]
Es werden keine Geräte angezeigt, Filter ist nicht gesetzt.

![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/944c87f6-c7ad-41aa-92b6-1494dc3a73a8)

Browser Log:

![2](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/44eebcc9-ff42-40dd-a3db-181608b0b819)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.13` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.13` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Jo, funktioniert
