### ISSUE TITLE
v3.2.0-alpha.13  State Explorer Keine Knoten verfügbar

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#2485]
State Explorer Keine Knoten verfügbar

![Screenshot (540)](https://github.com/Zefau/ioBroker.jarvis/assets/41079106/424d4c6c-952d-4d5c-99a5-1fc5403b348a)

Geräteliste ist bei allen so.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.13` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.13` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by sigi2345** [comment]
Works, Thx
