### ISSUE TITLE
Cannot use HTML or special char like m2 as Unit

### ISSUE THREAD

**Issue by manoloxxl** [Zefau/ioBroker.jarvis#2486]
**Prerequisites / Voraussetzungen**
- Jarvis 3.1.8

**Describe the bug / Beschreibe den Fehler**
I want to use ㎡ as Unit in an datapoint. But ㎡ is converted direct into m2. I also tried to use &#13217; as HTML entity (& # 1 3 2 1 7 ;), but it was shown as plain text.

Is there a way to use ㎡ or html as unit?

Best Regards 

Manuel

**Comment by mcuiobroker** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/59860c58-1406-4e49-bdaa-30f7cafd4bba)
```{"default":"m²"}```

**Comment by manoloxxl** [comment]
Crazy, thats working. Really dont understand why the copied value was converted into m2. Thanks!
