### ISSUE TITLE
Bindings im Datenpunkt Stil funktionieren nicht

### ISSUE THREAD

**Issue by aradhir** [Zefau/ioBroker.jarvis#2487]
Verwendete Jarvis Verison: [ 3.1.8 ] PRO
Fehler-Kurzfassung: Bindings können dazu verwendet werden, um die Farbe in einem Pop-Up einer Statelist zu bearbeiten. Dies funktioniert jedoch NICHT beim Datenpunkt-Stil

Detail-Fassung:
Ich nutzen u.a. den Tankkoenig-Adapter und lasse mir dabei min/max-Werte der letzte zwei Wochen berechnen (via influx-history und blockly). Danach erzeuge ich für die aktuellen Tankstellen eine Farb-Kodierung, welche ich in den Datenpunkte 0_userdata.0.Tanken.Farbe.Diesel.X ablege (als Hex: z.B: #ff0000). X steht dabei für die "Station-ID".
Diesen Datenpunkt lese ich nun bei der Erstellung eines Gerätes "Tankstelle" in jarvis aus, um die Elemente farblich zu kennzeichnen. Dabei funktioniert hier alles (Icon, Body), nur der Datenpunkt selbst lässt sich nicht formatieren. Wenn ich händisch eine Farbe (z.B. #ff0000) eingebe, wird der Wert formatiert. Aber über das Binding funktioniert es nicht. Siehe Screenshots

Screenshots:
![Bug-Color-1](https://github.com/Zefau/ioBroker.jarvis/assets/77203663/ee8374b5-2729-498b-8208-c41adfd94527)
![Bug-Color-2](https://github.com/Zefau/ioBroker.jarvis/assets/77203663/36845e16-09e5-4414-a934-b6a31d31afa4)

**Comment by Mephisto090** [comment]
Jetzt ist es komplett weg [v3.2.0-alpha.36]

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/a7250d4d-1e40-4268-8510-5790ffe8a2f3)

**Comment by Mephisto090** [comment]
Jetzt lädt er es manchmal nicht (v3.2.0-alpha.36)


![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/0f1f59bf-cd1f-42cb-9849-b8ceddfbd61f)

**Comment by Mephisto090** [comment]
Jetzt ist es sogar leer :(

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/c7736979-6fd9-425c-93f2-e969abb9d22e)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.37` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.37` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Mephisto090** [comment]
Meins ist leider immer noch rot und müsste grün sein

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/4681ec71-866c-4e2c-8ec3-86d49e920bb3)

**Comment by Mephisto090** [comment]
@Zefau gibt es hier schon neue Informationen, wann der Bug behoben wird?

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.50` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.50` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Mephisto090** [comment]
scheint zu funktionieren
