### ISSUE TITLE
v3.2.0-alpha.13 Konfiguration ohne Inhalte

### ISSUE THREAD

**Issue by NinjaKittn** [Zefau/ioBroker.jarvis#2488]
Ich verwende v3.2.0-alpha.13 (Pro)

Seit dem Update auf alpha.13 ist meine Konfiguration komplett leer. Der Fehler betrifft alle Seiten.
![Screenshot 2023-12-12 211320](https://github.com/Zefau/ioBroker.jarvis/assets/89083584/c4e2c422-befd-4f6b-ac76-ae3fb830dc49)

**Comment by fprobst170** [comment]
Ich hab mit der Version v3.2.0-alpha.13 das selbe Problem.

**Comment by fprobst170** [comment]
Ja in der Browser Konsole hab ich folgenden Fehler!
Ich hab nun auch auf die Version v3.2.0-alpha.20 aktualisiert, jedoch der selbe Fehler.

<img width="525" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/78404006/6c8c8a32-1bd3-48a7-8717-12210ac6b772">

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.21` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.21` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by fprobst170** [comment]
Hab soeben auf die Version `v3.2.0-alpha.21` aktualisiert, Konfiguration nun wieder mit Inhalten. 👍
