### ISSUE TITLE
Sie sind kein registrierter Benutzer der daswetter.com-API 

### ISSUE THREAD

**Issue by mandragora666** [Zefau/ioBroker.jarvis#249]
Hallo,

Habe noch ein kleines Problem mit wetter.com und Jarvis

Hab mir für die API bei wetter.com registriert.
URL hab ich und localidad und affiliate_id im Jarvis Wetter Widget eingetragen.
http://api.daswetter.com/index.php?api_lang=de&localidad=xxxxxx&affiliate_id=xxxxxx

Leider wird mir nichts angezeigt und im Log erhalte ich diese Meldung:

jarvis.0 | 2020-10-24 13:26:14.718 | error | (28077) Sie sind kein registrierter Benutzer der daswetter.com-API oder Ihr Konto wurde nicht aktiviert.

Finde bei wetter.com nichts wo ich noch zusätzlich was aktivieren kann und registriert bin ich ja sonst würde ich die URL nicht abrufen können.
Im Browser bekomm ich die XML mit dem richtigen Werten angezeigt.

Bitte um Ratschläge und Hilfe ob ich hier was falsch gemacht habe.

Vielen lieben Dank
mandragora

das Wetter 3.0.4
Jarvis 1.1.0-beta.47

**Comment by Zefau** [comment]
Bitte einen Screenshot der Widget Konfiguration

**Comment by mandragora666** [comment]
![image](https://user-images.githubusercontent.com/73381262/97080983-a12f2f80-15ff-11eb-9a98-e68becee70e8.png)
 Bitte sehr

**Comment by Zefau** [comment]
Sieht so aus als hättest du die Werte falsch herum eingetragen.

**Comment by mandragora666** [comment]
ohhhh Mann,,

shame on me...

Danke für deine Zeit und Hilfe

**Comment by mandragora666** [comment]
Bitte Link zu einer Bierspende für dich bekannt geben.
Super Arbeit die du da leistest. 
Vielen Dank

**Comment by Zefau** [comment]
https://paypal.me/chvoelkel ;-) Danke dir

**Comment by mandragora666** [comment]
Done :-D gerne geschehen
