### ISSUE TITLE
Refactor ioBroker.jarvis backend

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2490]

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.13` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.13`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Weiterhin nicht nutzbar, hängt sich immer noch auf.

**Comment by Zefau** [comment]
Das Build-Skript hat sich aufgehangen. Die alpha-13 ist alt und nicht aktualisiert. Bitte das nächste Release nutzen, das hoffentlich gleich durch geht.

**Comment by Bernd9000** [comment]
v3.2.0-alpha.19
Backend scheint jetzt gut zu laufen, Ram Nutzung bleibt stabil.
Frontend ist hier nach wie vor extrem träge oder funktioniert gar nicht.
Seite jarvis Konfiguration läuft schnell.
Bei der Geräteseite allerdings Fehler im Browser:

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/ce9c72a0-d2e6-4097-afa1-ed13fe6bd004)

**Comment by Bernd9000** [comment]
Nachtrag zu "Es tauchen Fehler auf die auf der aufgerufenen Seite gar nicht vorhanden sind."

Egal welche jarvis Seite man im Browser aufruft, es wird bei mir immer die erste Seite und der erste Tab kurz aufgerufen.
Dies geschieht so schnell das man es fast nicht mitkriegt.
Dies ist unabhängig von der in der jarvis Konfiguration unter "Homepage" eingestellten Seite.
Daher tauchen Fehler auf, die es der aktuellen Seite gar nicht geben dürfte.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.20` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.20`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Bernd9000** [comment]
Backend Fehler ist behoben

**Comment by Zefau** [comment]
Die Fehler aus https://github.com/Zefau/ioBroker.jarvis/issues/2490#issuecomment-1859321642 sollten auch behoben sein?

**Comment by Bernd9000** [comment]
Die "TypeError" Fehler sind bis jetzt nicht mehr aufgetaucht.
Valid Pro Prüfung läuft jetzt zweimal.
Nach wie vor wird eine andere Seite kurz geladen.
Danach u.a. wieder Binding Fehler von dieser anderen jarvis Seite.

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/943f08af-06a3-48eb-bf38-1cdb0d673af8)

**Comment by Zefau** [comment]
> Valid Pro Prüfung läuft jetzt zweimal.

Wie kommst du darauf?

> Nach wie vor wird eine andere Seite kurz geladen.

Ok, ich prüfe das nochmal

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.21` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.21`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Bernd9000** [comment]
Doppelte Anzeige der Valid Pro Prüfung ist jetzt weg.
Fehlermeldungen beim Edge und Chrome Browser sind geblieben.
Im Firefox erscheint keine Fehlermeldung.
Vielleicht ist das nur bei mir so ?
@mcuiobroker
Wie sieht es bei Dir aus ?

**Comment by mcuiobroker** [comment]
Hängt sich bei mir bei TAB-Wechsel nach Seitenwechel auf
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c02c3771-5903-4a9f-b688-ea71399c4de3)

**Comment by Bernd9000** [comment]
Ja, das mit dem hängen bleiben habe ich auch noch auf bestimmten jarvis Tabs.
Ich teste deswegen erstmal nur mit einer neu angelegten Seite mit nur einem Gerät (Schalter).

**Comment by Zefau** [comment]
Welche Module sind denn auf den Seiten, die bei euch hängen? Auf meiner Umgebung habe ich StateList, Datetime, Weather sowie AdapterStatus, ScriptStatus und AdapterLogs sowie Maps. Das läuft alles flüssig.

**Comment by mcuiobroker** [comment]
StateLists mit States, die evtl undefined (Kein States und keine Daten vorhanden, Testsystem, noch kein Prodsystem(defekt)) sind,  und "leere" jsonTable sind bei mir auf dem TAB, bei dem er sich aufgehängt hat.

**Comment by Bernd9000** [comment]
Bei mir : StateList, Datetime und IFrame
In allen betroffenen Seiten kommen auch Bindings vor, die das auch auslösen können.

**Comment by Bernd9000** [comment]
Und leider wird immer noch eine "fehlerhafte" Seite als erstes geladen, obwohl ich ein anderen Link in der Adressleiste eintippe.

**Comment by Zefau** [comment]
> Und leider wird immer noch eine "fehlerhafte" Seite als erstes geladen, obwohl ich ein anderen Link in der Adressleiste eintippe.

Das war vorher auch so. Der Ladevorgang ist allerdings nun schneller, wodurch es auffällt. Wie lang ist denn der zeitliche Versatz ?

**Comment by Bernd9000** [comment]
Ist nur sehr kurz, vielleicht 100 ms, manchmal auch schneller so das man es gar nicht sieht.

**Comment by intruder7777** [comment]
Muss mich auch mal melden... Bei mir hängt sich Jarvis regelmäßig auf.. Bis hin zum Sperren der Instanz seitens IoBroker. Hab ne Weile gebraucht bis ich da einen Zusammenhang festgestellt hatte.. Ich trigger eine Message über den Bewegungsmelder und lasse mir dann ein Kamerabild anzeigen. Dies passiert nicht mehr. Das ist der Punkt an dem sich Jarvis aufhängt.
Hier der Log zu diesem Zeitpunkt
`<html>
<body>

jarvis.0 | 2023-12-20 20:52:14.450 | debug | Scheduled for 10:24
-- | -- | -- | --
jarvis.0 | 2023-12-20 20:52:14.429 | info | starting. Version 3.2.0-alpha.21 (non-npm: Zefau/ioBroker.jarvis#e3a593f5d6edb73bc56a486d8b7b66efb995d13d) in /opt/iobroker/node_modules/iobroker.jarvis, node: v18.17.1, js-controller: 5.0.16
host.NUC-ioBroker | 2023-12-20 20:51:40.221 | error | instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
host.NUC-ioBroker | 2023-12-20 20:51:40.221 | error | Caught by controller[1]: Invalid initialization vector
host.NUC-ioBroker | 2023-12-20 20:51:40.220 | error | Caught by controller[0]: Invalid initialization vector
jarvis.0 | 2023-12-20 20:51:39.863 | info | terminating
jarvis.0 | 2023-12-20 20:51:39.364 | error | socket is not defined
jarvis.0 | 2023-12-20 20:51:39.364 | error | ReferenceError: socket is not defined at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.min.js:1:9471) at process.processImmediate (node:internal/timers:478:21)
jarvis.0 | 2023-12-20 20:51:39.363 | error | uncaught exception: socket is not defined
jarvis.0 | 2023-12-20 20:51:39.361 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
jarvis.0 | 2023-12-20 20:51:39.361 | info | terminating
jarvis.0 | 2023-12-20 20:51:39.360 | info | Adapter stopped und unloaded.
jarvis.0 | 2023-12-20 20:51:39.358 | error | socket is not defined
jarvis.0 | 2023-12-20 20:51:39.358 | error | ReferenceError: socket is not defined at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.min.js:1:9471) at process.processImmediate (node:internal/timers:478:21)
jarvis.0 | 2023-12-20 20:51:39.357 | error | uncaught exception: socket is not defined


</body>
</html>`

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.26` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.26`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/1acf5942-86c2-4b26-a8f7-a77b3641f605)

**Comment by Bernd9000** [comment]
![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/91bde8ed-b0c7-4570-93a2-2ec789f9e50d)

**Comment by Bernd9000** [comment]
Mit dem Aufruf über den Web Port funktioniert es ganz gut. :-)

**Comment by Zefau** [comment]
>  Bindings funktionieren nicht ? 

Hab ich alles umgebaut. Sollten funktionieren. Kannst du dein Binding mal posten, was nicht geht?

**Comment by Bernd9000** [comment]
Z.B.:
Icon:
{"'{0_userdata.0.Test.Testschalter10.status}'='Offline'":"pump blink","true":"pump","false":"pump"}

Icon Stil:
{"'{0_userdata.0.Test.Testschalter10.status}'='Offline'":{"color":"#FF0"},"true":{"color":"#0F0"},"false":{"color":"#F00"}}

Scheinbar alles was mit einem fremden Datenpunkt zu tun hat, funktioniert  nicht.
Hier wird bei true und false das Pumpen Icon rot und grün dargestellt = i.O.
Wenn bei dem fremden Datenpunkt als string "Offline" steht soll Icon gelb blinken

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.27` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.27`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
v.3.2.0-alpha.27
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6022318f-6748-4542-bc30-1d5421f10e74)
Kurze Anzeige
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/76cdaba2-f394-4a71-ab46-98286aed243e)

Sonst nix

**Comment by mcuiobroker** [comment]
Beim Speichern kommt:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/bdb9e1fb-2215-45e4-9582-65002fc20b44)

**Comment by Zefau** [comment]
@mcuiobroker kannst du nochmal sauber (drüber) installieren? Die Fehler sollten eigentlich behoben sein und treten bei mir auch nicht mehr auf.
@Bernd9000 wie sieht es bei dir aus?

**Comment by mcuiobroker** [comment]
Bezogen auf backend, mag sein. Es wird aber im Edge kein Widget mehr angezeigt, wie oben beschrieben.
Soll ich für die offenen Punkte extra Issues anlegen?

**Comment by Zefau** [comment]
Ne, bitte nicht noch mehr Issues ;-)

**Comment by mcuiobroker** [comment]
Also offen sind
- Edge , es werden keine Widgets angezeigt
- F2 -> direkt Fehleranzeige -> Eingaben blockiert
- Speichern nicht möglich da Fehler

Weiter kann ich nicht testen.

**Comment by Zefau** [comment]
Das Circle-Problem ist eigl. mit https://github.com/Zefau/ioBroker.jarvis/issues/2500 behoben, daher wundert's mich, dass es bei dir noch auftritt.

**Comment by mcuiobroker** [comment]
Ich hatte auch Meldungen, dass die scripts-Skripte schon vorhanden sind.

**Comment by Zefau** [comment]
Kannst du mal den Cache löschen? Das erscheint mir zu merkwürdig.

**Comment by mcuiobroker** [comment]
Cache gelöscht, dann kommt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/f53daa77-3f7b-4467-b391-ea5d0e5147b8)

**Comment by Zefau** [comment]
Circle-Fehler im ioBroker Log?

**Comment by mcuiobroker** [comment]
Ja
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5cdd2818-dcd8-442d-835e-b32a43b8d14a)

**Comment by mcuiobroker** [comment]
Nach Web-Neustart zeigt er jetzt die Widgets auch in Edge an.

**Comment by Zefau** [comment]
Die ganzen Socket Fehler kommen davon, dass der Adapter in ioBroker abstürzt und daher der WebSocket nicht erreichbar ist.

>  Irgendwie scheint er ein Problem zu haben, wenn ich von gleicher IP mit unterschiedlichen Browsern zugreife? 

Funktioniert bei mir.

> Jetz kam in chrome dies

Das ist nicht von jarvis.

**Comment by mcuiobroker** [comment]
Also jetzt war es so 2 Browser (edge, chrome) offen, chrome geschlossen, nach 1 Minute Chrome geöffnet -> ws-Fehler auf edge.

**Comment by Zefau** [comment]
Schau mal mit `v3.2.0-alpha.29`, das behebt den Fehler nicht, aber fügt mehr im Log hinzu.

**Comment by mcuiobroker** [comment]
ok

**Comment by mcuiobroker** [comment]
Ich hatte erst die Vermutung dass es mit den scripten zusammenhängt. -> disabled
Trotzdem tritt der circle-Fehler auf.
Browser Edge öffnen
Chrome mit der gleichen Seite öffnen  und auf eine andere Seite gehen. Dann Browser schließen.
evtl auch öfter als einmal öffnen und schließen.

Wieder Chrome öffnen nochmal die Seite aufrufen und dann schließen -> ws-Fehler in Edge

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.30` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.30`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Soweit ich es beurteilen sieht es mit dem circle-problem gut aus. Hatte einen reproduzierbaren Weg gefunden. Der geht jetzt nicht mehr.

**Comment by Bernd9000** [comment]
3.2.0-alpha.30
Binding mit einem fremden Datenpunkt funktioniert bei mir noch nicht.

**Comment by mcuiobroker** [comment]
Auf dem Handy werden keine Widget angezeigt.

**Comment by Bernd9000** [comment]
Auf dem Handy mit Google Chrome wird bei mir auch nichts angezeigt.
Nur die erste Seite wird kurz angezeigt

**Comment by mcuiobroker** [comment]
Handy edge funktioniert.
evtl auch in chrome auf dem handy Cache löschen?

**Comment by Bernd9000** [comment]
Komisch, nehme ich beim Handy statt dem Web Port den Socket Port wird wieder was angezeigt....

**Comment by mcuiobroker** [comment]
Bei mir wird im Chrome Handy responsive Anzeige nicht genutzt. Es wird die komplette Webseite angezeigt.

**Comment by Bernd9000** [comment]
> Handy edge funktioniert. evtl auch in chrome auf dem handy Cache löschen?

Hab ich mal versucht, keine Änderung

**Comment by Zefau** [comment]
>  Binding mit einem fremden Datenpunkt funktioniert bei mir noch nicht.

Das Binding aus https://github.com/Zefau/ioBroker.jarvis/issues/2470#issuecomment-1810346013 funktioniert bei mir.
Das Icon blink gelb, wenn der fremde Datenpunkt `Offline` ist. Wenn es nicht Offline ist, blinkt es nicht und zeigt die entsprechende Farbe.

**Comment by Bernd9000** [comment]
> Das Binding aus [#2470 (comment)](https://github.com/Zefau/ioBroker.jarvis/issues/2470#issuecomment-1810346013) funktioniert bei mir. Das Icon blink gelb, wenn der fremde Datenpunkt `Offline` ist. Wenn es nicht Offline ist, blinkt es nicht und zeigt die entsprechende Farbe.

Ich finde den Fehler leider nicht, bei v3.1.9-beta.2 funktioniert es noch.
Vielleicht komme ich noch drauf......

**Comment by Zefau** [comment]
@Bernd9000 Wie sieht es mit `v3.2.0-alpha.37` aus?

**Comment by Bernd9000** [comment]
Leider nein.
Ähnlich wie in [#2487](https://github.com/Zefau/ioBroker.jarvis/issues/2487)
Auch beim Datenpunkt Stil funktioniert es bei mir nicht.
Keine Ahnung woran es liegt.

**Comment by Zefau** [comment]
Hast du noch ein Beispiel, was bei dir nicht funktioniert? Gerne mit voller Konfiguration, damit ich es bei mir nachgestellt bekomme.

**Comment by Bernd9000** [comment]
Beispiel:
Gerät "Testschalter-10" mit zwei Datenpunkten `status` und `power`
status =  Werte = "Online" oder "Offline"
power =  Werte = "true" oder "false"

![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/7216809c-760c-4c4b-872e-be992cbab74b)

![2](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/64d480f3-314b-45c1-b384-5a0c716e5af7)


Expert Mode:

"b950c530-5728-43d7-a9ad-38ef0573c064": {
    "name": "Testschalter-10",
    "aliases": "",
    "tags": [],
    "icon": "mdi:pump",
    "label": "",
    "function": "_defaults",
    "states": {
      "status": {
        "stateKey": "status",
        "showState": true,
        "state": "0_userdata.0.Test.Testschalter10.status",
        "icon": {
          "Offline": "pump blink",
          "Online": "pump"
        },
        "_updated": 1704401016157,
        "iconStyle": {
          "Offline": {
            "color": "#FF0"
          },
          "Online": {
            "color": "#0F0"
          }
        }
      },
      "power": {
        "stateKey": "power",
        "showState": true,
        "state": "0_userdata.0.Test.Testschalter10.power",
        "icon": {
          "'{0_userdata.0.Test.Testschalter10.status}'='Offline'": "mdi:pump blink",
          "true": "mdi:pump",
          "false": "mdi:pump"
        },
        "iconStyle": {
          "'{0_userdata.0.test.Testschalter10.status}'='Offline'": {
            "color": "#FF0"
          },
          "true": {
            "color": "#0F0"
          },
          "false": {
            "color": "#F00"
          }
        },
        "_updated": 1704404937643,
        "actionElement": "SwitchAction",
        "stateStyle": {
          "'{0_userdata.0.test.Testschalter10.status}'='Offline'": {
            "color": "#FF0"
          },
          "true": {
            "color": "#0F0"
          },
          "false": {
            "color": "#F00"
          }
        },
        "addToCloud": []
      }
    },
    "options": {},
    "attributes": {
      "_created": 1703108388311,
      "_updated": 1704404885386
    },
    "id": "b950c530-5728-43d7-a9ad-38ef0573c064",
    "revision": "1a21e"
  },

**Comment by mcuiobroker** [comment]
Wie sehen die Einstellungen zum testschalter aus
![Uploading image.png…]()

**Comment by Bernd9000** [comment]
Hier die Einstellung.
Aber an dem liegt es nicht, denn wenn ich in IOB den Datenpunkt händisch ändere passiert auch nichts.

![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/0a1b09fc-2bcf-464e-9638-5d53cc8d0bc3)

**Comment by Bernd9000** [comment]
Ich werd später mal zum Test mit einer ganz neuen jarvis Instanz anfangen.
Mal sehen wie es dann aussieht.

**Comment by mcuiobroker** [comment]
Instanzen funktionieren momentan nicht so gut?
Testsystem?

**Comment by Bernd9000** [comment]
Ja, Testsystem in vmware mit Windows 11.
Es ist wie verhext...
js-controller und nodejs gewechselt = negativ
Als Instanz nur Admin, jarvis und vis laufen lassen = negativ
Nur ein Gerät, nur ein Widget, nur eine jarvis Seite = negativ

Das einzige was hilft ist zurück auf Version v3.1.9-beta.2

**Comment by mcuiobroker** [comment]
@Bernd9000 Kann doch dann dieser Issue hier zu? Das Binding wird dann ja mit dem Label behandelt.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.50` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.50`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Bernd9000** [comment]
> @Bernd9000 Kann doch dann dieser Issue hier zu? Das Binding wird dann ja mit dem Label behandelt.

Klar, kann dicht
