### ISSUE TITLE
Stacked Chart: Fixed order of datapoints

### ISSUE THREAD

**Issue by ScumbagSteve** [Zefau/ioBroker.jarvis#2491]
I try to recreate a fill-visualization (Füllstandsanzeige) with a stacked chart.
The visualization always seem to show the biggest value on the bottom. For this scenario this is not useful, as the bottom value should always show the remaining volume of pellets and the top value should always be the "empty" space.

<img width="492" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/8447146/54c254fd-cc58-49b5-942c-794509a4c46e">

Is it possible to fix the order of datapoints shown in the "stacked" chart?
Would be interesting for the documentation I guess.

**Comment by mcuiobroker** [comment]
Wie ist die Einstellung vom Chart?

**Comment by ScumbagSteve** [comment]
> Wie ist die Einstellung vom Chart?

<img width="1298" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/8447146/0d305123-a892-4d44-abc8-27f3824f6f19">

**Comment by mcuiobroker** [comment]
Und wenn du die Reihenfolge der DPs änderst, wird dasgleiche angezeigt?

**Comment by ScumbagSteve** [comment]
> Und wenn du die Reihenfolge der DPs änderst, wird dasgleiche angezeigt?

Same result, yes. It's sorted by value, when displayed.

**Comment by ScumbagSteve** [comment]
I am not sure what happened but it's working now. Maybe something was cached and showing an old version. Sorry for the confusion. Will close the ticket.
