### ISSUE TITLE
Double tab on a widget in mobile mode shows widget fullscreen

### ISSUE THREAD

**Issue by manoloxxl** [Zefau/ioBroker.jarvis#2492]
**Prerequisites / Voraussetzungen**

- Jarvis 3.1.8

**Describe the bug / Beschreibe den Fehler**

Hi,
I'm using Jarvis on a laptop and also on a fire tablet. When using the tablet i can double click any widget and the widget opens in fullscreen.
I've double checked any setting but was not able to find any setting about this behaviour that is active. Sure, when i edit the widget config, there is a switch to allow full screen - but it is set to inactive. Mobile devices are using the desktop layout, i did not configured any layout else. On my laptop i cannot double click the widgets.

Any idea what can i do to disble the fullscreen when double tabbing an widget on m fire tablet?

Best Regards

Manuel

**Comment by Zefau** [comment]
This is fixed with v3.2, which is alpha at the moment. Please be patient, this will eventually be fixed.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by manoloxxl** [comment]
Ist in v3.2.0-alpha.37 behoben. Beim Update ist mir zwar mein Design abgeflogen (die Farben) und ich lande immer wieder im Startscreen, aber generell ist dieses anliegen hier in der Version okay.
