### ISSUE TITLE
Jarvis forgets pro status

### ISSUE THREAD

**Issue by Tom54497** [Zefau/ioBroker.jarvis#2494]
I am using Jarvis 3.1.8 and after some time of standby Jarvis "forgets" the pro status.  It can be recognized with the history graphs using {"min":"dataMin","max":"dataMax"} which won't work any more showing data axis from zero to actual value instead of min value to actual value.

Any idea?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2441

**Comment by Tom54497** [comment]
> #2441

**Comment by Tom54497** [comment]
Different to #2441 I do not have any warnings in the log. Pro status vanishes after some time and will be there again when page is refreshed in browser or Fully browser is restarted.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.68` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.68` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Tom54497** [comment]
Solved by 3.2.0
