### ISSUE TITLE
Websocket with Reverse Proxy and SSL

### ISSUE THREAD

**Issue by TZanke** [Zefau/ioBroker.jarvis#2495]
**Prerequisites / Voraussetzungen**
v3.2.0-alpha.21

**Describe the bug / Beschreibe den Fehler**
Ich habe im nginx meine jarvis domain auf die Jarvis installation mit port 8400 gesetzt. Das funktioniert so weit wie es soll. (ohne SSL)
Dann schalte ich im nginx SSL ein, sodass ich per https auf die jarvis Domain zugreife. Intern holt nginx die Daten per HTTP, und verpackt sie dann verschlüsselt. Jarvis bekommt davon nichts mit und versucht den WebSocket ebenso ohne SSL zu initiieren. Das passt Chrome leider gar nicht. Die Option hat keinen Einfluss darauf:
![image](https://github.com/Zefau/ioBroker.jarvis/assets/1613368/e5821a0c-c2c5-466f-bb19-0a38b57371a2)

**Screenshots**
![image](https://github.com/Zefau/ioBroker.jarvis/assets/1613368/b39a8d88-739e-46c4-b4c2-7209c844f521)

Ich würde erwarten, dass die ```Sichere Verbindung (HTTPs``` Option dann auch versucht den WS**S** zu benutzen.
Scheinbar müsste ich im IOBroker auch ein Zertifikat hinterlegen, damit nginx per SSL an die Daten kommt, das will ich aber vermeiden, da nginx sich um Let's Encrypt kümmern soll.

**Comment by Zefau** [comment]
> Ich würde erwarten, dass die Sichere Verbindung (HTTPs Option dann auch versucht den WSS zu benutzen.

Dem ist auch so. Hast du im Web-Adapter auch die gesicherte Verbindung aktiviert? jarvis holt sich die Einstellungen von dort inkl. der Zertifikate. Mit v4 muss ich die Einstellungen unbedingt in die jarvis-Adaptereinstellungen holen, da das recht intransparent ist seit der Verwendung von Port 8400.

**Comment by TZanke** [comment]
Ich hab mal noch nebenbei auf die ```v3.2.0-alpha.22``` geupdated.

Ich habe jetzt im WebAdapter/Instanz die default Zertifikate eingeschalten.

Per ```https://192.168...../``` geht jetzt alles mit einem logischerweise invaliden Zertifikat. Soweit so gut.

Im Nginx habe ich auch auf SSL als Ziel umgestellt, so weit geht es auch mit einem validen Zertifikat auf, leider bleibt der Fehler, dass er auf ```ws``` zugreift statt auf ```wss```.

Bisher konnte ich das verstehen, aber jetzt wo er doch alles per SSL abfragt, komisch.

**Comment by Zefau** [comment]
Im Web-Adapter ist `HTTP` aktiviert?

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/c19e68ad-f350-4636-8209-93198b498c50)

Und dann nochmal schauen, dass die Einstellungen im Cache gelöscht sind: via F12 unter `Web-Speicher` beim `Local Storage` die `params` und `recentConnections` löschen:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/351949e2-3b8a-46c3-b3b3-a7942629e204)

**Comment by Zefau** [comment]
Alternativ sonst jarvis direkt mit den Einstellungen aufrufen: https://192.168.2.11:8082/jarvis/index.html#/0/&socketHost=&socketPort=8400&socketSecure=true

Also `socketSecure=true` an die URL hängen. Müsste auch so mit Port `8400` funktionieren.

**Comment by TZanke** [comment]
Danke für deine Hilfe. Genau, die HTTP**S** im Web Adapter hatte ich eingeschalten.

Nachdem ich nun die local Storage Daten gelöscht habe, ist nur die Meldung zum Fehler größer geworden:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/1613368/abb75957-223c-409a-aa86-05ac97e31131)

Mir fällt aber gerade auf: Er versucht erst ```wss``` und dann als Fallback ```ws```. 

![image](https://github.com/Zefau/ioBroker.jarvis/assets/1613368/a74dfcec-1102-437b-98f6-a251c41122fc)

Ich erkenne leider nicht was der Fehler beim ```wss``` ist, außer ```error```.
Websocket im Nginx ist eingeschalten.

**Comment by Zefau** [comment]
Hast du das selbst-signierte Zertifikat auf Port 8400 angenommen?

**Comment by TZanke** [comment]
Das Zertifikat, welches der Nginx verwendet ist Let's Encrypt, also sogar von sich aus valide. Das Zertifikat vom iobroker ist es natürlich nicht, der nginx sollte sich aber daran eigentlich nicht stören. Zusätlich hat der nginx die option ```proxy_ssl_verify off;``` gesetzt. Daran sollte es also nicht liegen.

Die ```v3.2.0-alpha.24``` zeigt den Socketfehler SSL vs !SSL jetzt direkt an, ich vermute, das hast du eingebaut. Danke!

Aus irgendeinem Grund ist der iobroker/jarvis der Meinung, die Anfrage wäre ohne SSL und versucht

--- 

OK, es geht. Ich weiß gerade aber nicht wieso: Ich hab gerade mal gedacht "Eigentlich muss er ja gar nicht die 8400 nehmen, da der nginx das ja von 443 entgegennimmt!" Ich hab also in der Konfiguration über der Fehlermeldung den Port komplett leer gelassen und dann verbinden geklickt. Tada, es geht. Allerdings steht jetzt wieder die 8400 im Feld (Default Wert?)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/1613368/4b5ab985-09e7-46fa-ba08-e1c05e7563cc)

So ergibt es jetzt für mich auch am meisten Sinn, die 443 vom nginx wird ja auf die 8400 weitergeleitet. Also sollte jarvis von der 8400 nichts wissen müssen, einfach 443 nehmen.

**Comment by Zefau** [comment]
Was passiert, wenn du die URL `https://jarvis...org` bzw. die interne URL zu jarvis direkt aufrufst? Also via `https` (nicht `wss`).

**Comment by Zefau** [comment]
Kannst du mal eine kurze Anleitung schreiben, wie du das alles eingerichtet und konfiguriert hast? Würde das bei mir auch gern mal umsetzen.

nginx via Proxmox inkl. Öffnung von Port 80 für LetsEncrypt Zertifikat holen? Was hast du in nginx noch eingestellt und darüber hinaus?

**Comment by TZanke** [comment]
@Zefau siehe https://github.com/Zefau/ioBroker.jarvis/issues/2506
