### ISSUE TITLE
webmanifest in die static-files aufnehmen, um die Webseite als PWA installierbar zu machen

### ISSUE THREAD

**Issue by dfoxg** [Zefau/ioBroker.jarvis#2497]
**Describe the solution you'd like**
Mit einem [Webmanifest](https://developer.mozilla.org/en-US/docs/Web/Manifest) lassen sich Webseiten als [PWA](https://de.wikipedia.org/wiki/Progressive_Web_App) installieren.

Dazu müsste man eine Datei mit z.B. folgenden Inhalt aufnehmen: 

```
{
    "theme_color": "#d632f0",
    "background_color": "#d632f0",
    "display": "standalone",
    "scope": "/",
    "start_url": "/",
    "name": "Jarvis",
    "short_name": "Jarvis",
    "icons": [
        {
            "src": "/icon-192x192.png",
            "sizes": "192x192",
            "type": "image/png"
        },
        {
            "src": "/icon-256x256.png",
            "sizes": "256x256",
            "type": "image/png"
        },
        {
            "src": "/icon-384x384.png",
            "sizes": "384x384",
            "type": "image/png"
        },
        {
            "src": "/icon-512x512.png",
            "sizes": "512x512",
            "type": "image/png"
        }
    ]
}
```
und diese dann in der index.html verlinken:
`<link rel="manifest" href="manifest.webmanifest" />`

Könntest du das ggf. mit aufnehmen? Wenig Aufwand, aber erleichtert die Bedienung :)

**Comment by Zefau** [comment]
So einfach ist das leider nicht. jarvis ist als SPA entwickelt und nicht als PWA. Eine PWA impliziert:

> Connectivity independent - Enhanced with service workers to work offline or on low quality networks.

Das kann jarvis nicht sein, da es immer auf ioBroker angewiesen ist. Siehe auch https://quasar.dev/quasar-cli-webpack/developing-pwa/introduction/.

Du meinst wahrscheinlich eher https://github.com/Zefau/ioBroker.jarvis/issues/2447, oder?

**Comment by dfoxg** [comment]
Ups, stimmt. Aber das Manifest könnte man ja trotzdem hinzufügen, ohne die Offline-Funktionalität, oder? Dann wird die SPA zumindest als eigene App auf dem Handy angezeigt
