### ISSUE TITLE
Dezimaltrennzeichen bei negativen Werten Punkt statt Komma

### ISSUE THREAD

**Issue by hengst12** [Zefau/ioBroker.jarvis#2498]
Normalerweise wird als Dezimaltrennzeichen ein Komma verwendet.
Wechselt der Wert aber ins Negative wird ein Punkt als Dezimaltrennzeichen verwendet.

Dem Datenpunkt habe ich folgende Eigenschaft hinzugefügt: {"value":"val => parseFloat(val).toFixed(1)"}
Das Entfernen dieser Eigenschaft hat aber keinen Einfluss.

Im ioBroker wird der Wert des Objekts immer mit einem Komma angezeigt, egal ob positiv oder negativ der Wert ist.

Beispielbilder:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/35632953/8ace9d8d-2c3f-4b5a-9e3c-1667d1b3c085)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/35632953/0267adbb-662b-4b11-9dd7-7ab55fbbd306)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.27` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.27` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by hengst12** [comment]
Passt - vielen Dank.

**Comment by hengst12** [comment]
Passt - vielen Dank.
