### ISSUE TITLE
`LightHueBody` plötzlich weg

### ISSUE THREAD

**Issue by BlackandGold1** [Zefau/ioBroker.jarvis#2502]
Jarvis 3.1.8 der Hue Slider für RGB farben ist plötzlich weg. Alle anderen Slider gehen. Wenn ich Jarvis öffne egal ob auf PC oder Android ist er kurz zu sehen und nach 2 Sekunden weg.

**Comment by mcuiobroker** [comment]
Zeig mal bitte die Einstellungen zur StateList und zum Geräte-DP.

**Comment by BlackandGold1** [comment]
<img width="320" alt="Screenshot 2023-12-30 122642" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/86619c31-e74a-4deb-85b6-caa8386bd704">
<img width="565" alt="Screenshot 2023-12-30 122854" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/63b320b0-a99b-4243-923a-37aedbd3299b">
<img width="556" alt="Screenshot 2023-12-30 122918" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/89488e92-4eaa-4e52-bd5e-74a8ec7d4cb2">

**Comment by Zefau** [comment]
Fehler in der Browser-Konsole via F12?

**Comment by BlackandGold1** [comment]
okay wie geht das.? Wie gesagt ich sitze Stunden um was zu machen weil es soviel gibt was man machen kann. Ich denke ich nutze das alles nur zu 5% aus. Ich habe mir da wirklich was tolles draus gebaut und es läuft aber ich habe Monate gesessen.

**Comment by BlackandGold1** [comment]
hab mal F12 gedrückt und bin erschlagen...Oh mein Gott. Sorry aber da seh ich nicht mehr durch.

<img width="343" alt="Screenshot 2023-12-30 130834" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/ae186c91-aef2-4042-b1a7-12c825e0b24b">

**Comment by Zefau** [comment]
Links ist der Fehler, aber der Anfang ist abgeschintten. Rechts die Barrierefreiheit kannst du ausblenden.

**Comment by mcuiobroker** [comment]
Scheint dieses zu sein
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/df24ad2a-b688-46c0-ab93-969777b1bebc)

**Comment by BlackandGold1** [comment]
Keine Ahnung. So besser?
<img width="780" alt="Screenshot 2023-12-30 191458" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/55b05b56-0522-4bd4-b696-2f6b4be2596a">
<img width="778" alt="Screenshot 2023-12-30 191513" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/c2f84353-2b28-4c82-a9fb-cf1365274a1e">

**Comment by BlackandGold1** [comment]
Jetzt ist das erschienen:
<img width="764" alt="Screenshot 2023-12-30 192631" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/f715e7fe-8649-458a-9c59-49ab69933a3f">

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by BlackandGold1** [comment]
Und wie installiere ich diese Version in Iobroker?

**Comment by Zefau** [comment]
Du hast die Alpha installiert und da erscheint derselbe Fehler? Kannst du mal zeigen wie du den Slider konfiguriert hast?

**Comment by BlackandGold1** [comment]
Genauso wie weiter oben gezeigt. Stelle ich den Datenpunkt auf dieses Mischfeld um funktioniert alles.

**Comment by Zefau** [comment]
Oben steht ja
> Die Version v3.2.0-alpha.30 sollte den Fehler beheben 

Hast du es mit der Version testen können? Auf der v3.18 wird der Fehler nicht einfach verschwinden.

Vermutlich ist er verursacht durch falsche `min`/`max` Werte. Also ggf. einfach Selbige mal anpassen.

**Comment by BlackandGold1** [comment]
Hey. Ja habe die v3.2.0-alpha30 installiert.  läuft super aber der Slider ist nicht da.
<img width="805" alt="Screenshot 2024-01-07 191229" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/0a26abfe-22f5-4c55-ae6b-3e73bfdaf9a9">
<img width="361" alt="Screenshot 2024-01-07 191324" src="https://github.com/Zefau/ioBroker.jarvis/assets/94290188/2d648c73-ae2d-481e-bb3e-ffd4affd774d">

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.40` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.40` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by BlackandGold1** [comment]
Würde ich gern. Bekomme die Installation aber leider nicht hin. Es bleibt bei der v3.2.0 alpha 30. Kleine Tipp wie man es in Iobroker installiert wäre super.

**Comment by mcuiobroker** [comment]
Expertenmodus einschalten
Auf die Katze klicken
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9d22df62-fd6b-41ed-97de-21dc1399bca5)
Jarvis eingeben
Installieren

**Comment by BlackandGold1** [comment]
Super.Danke. Das hat geklappt. Slider ist da lässt sich verstellen aber ändert nichts. Stelle ich auf ddiesen ColorBody geht alles wenn ich eine Farbe auswählen.

**Comment by Zefau** [comment]
Ich benötige mehr Informationen.

Also du benutzt den `LightHueBody`, richtig?

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/c591d693-f7b7-46c1-9bfb-eb9256d9dde0)

Im Layout wie folgt ausgewählt:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/eb3a4ef6-d389-423b-8a2c-46c2732bee16)

Hast du die Datenpunkt-Eigenschaft verändert?

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/8d618c83-ea57-4cd1-a8af-664eadaf8919)

**Comment by BlackandGold1** [comment]
Kann alle Fragen mit ja beantworten. Genauso sieht es aus. Sobald ich im Layout auf Colorbody stelle geht es.

**Comment by Zefau** [comment]
Bitte mehr Informationen zum Datenpunkt in ioBroker sowie im Gerät in jarvis. Am besten von allem mal einen Screenshot. Ich hab keine Glaskugel und kann dir schlecht helfen, wenn ich 0 Informationen habe.

> Aktuelles Problem ist das ich keine Datenknoten mehr habe unter Geräte.

Was meinst du damit?

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.57` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.57` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by BlackandGold1** [comment]
Leider keine Änderungen. Es werden nur Nullen geschrieben.

**Comment by Zefau** [comment]
> mir ist noch aufgefallen das wen ich den Hue Slider verstelle schreibt er immer 6 Nullen in den Datenpunkt also : 000000

6 Nullen ist der Hex-Code für Schwarz. Scheinbar stellt sich die Komponente nicht korrekt auf `hue` ein. Ich hab es bei mir nun 1-zu-1 so eingestellt wie bei dir, aber kann den Fehler nicht reproduzieren - bei mir geht es.

Kannst du für den Datenpunkt nochmal einen neuen State in jarvis im Gerät anlegen und neu im Layout hinzufügen? Vielleicht hat sich da irgendwas dauerhaft festgesetzt, was nur mit neu Hinzufügen raus geht.

**Comment by BlackandGold1** [comment]
Mit der Beta 3 geht es plötzlich wieder. Danke
