### ISSUE TITLE
[v3.2.0-alpha.27] Kalender funktioniert nicht richtig

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2503]
Hej,

irgendwie zeigt er seit ein paar Tagen meine Termine nicht mehr an. Manchmal habe ich auch ein Ladebalken ins unendliche.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/2dabbbaf-3770-401d-a385-24a46b118996)

VG

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.28` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.28` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Mephisto090** [comment]
funktioniert wieder
