### ISSUE TITLE
[v3.2.0-alpha.27] Installation inconsistent

### ISSUE THREAD

**Issue by TZanke** [Zefau/ioBroker.jarvis#2504]
v3.2.0-alpha.27

Auch Browserdaten löschen hilft nicht.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/1613368/4b7a2cf5-1684-4567-b0ea-e351a71d7ccf)

**Comment by TZanke** [comment]
Nachdem ich jarvis nicht über reverse proxy aufgerufen habe (8400 only), sondern einmalig über die normale ip mit port 8082 gehts auch auf dem reverse proxy wieder.

**Comment by mcuiobroker** [comment]
Kannst du mir bitte einige Bilder mit `nginx`- Einstellungen zur Verfügung stellen, damit ich es in die Doku aufnehmen kann. Wenn möglich mit genauer Beschreibung wie man wo was einstellen muss, damit man es mit jarvis nutzen kann. Danke.

**Comment by mcuiobroker** [comment]
Zum Problem?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/67df45b6-4567-431a-b65f-b75675dacb77)

**Comment by TZanke** [comment]
Ok sorry, das hatte ich bisher noch nie, daher dachte ich, ich frage direkt mal. Sorry.

Was die Anleitung angeht: sehr gern. Ich frickel aber gerade noch etwas rum und schreibe die dir dann, wenn ich alle Fragen für mich selbst beantworten konnte. Steht auf jeden Fall auf der TODO (für dieses Jahr :D )

**Comment by TZanke** [comment]
@mcuiobroker siehe https://github.com/Zefau/ioBroker.jarvis/issues/2506
