### ISSUE TITLE
[v3.2.0-alpha.27] Anzeigevariante zum ausblenden vom Wert greift nicht im Secondary State

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#2505]
Bisher konnte mit z.B. `{"0":""}` oder `{"true":""}` in der Anzeigevariante der Anzeigewert im Secondary State ausgeblendet werden. 
Wenn ich `{"0":" "}` in der Anzeigevariante eingebe wird der Wert zwar nicht angezeigt aber das Komma im Secondary State beliebt stehen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.37` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.37` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by hosabeni** [comment]
Passt. Danke!

**Comment by Zefau** [comment]
Gibt nun auch eine dedizierte Option:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/0ebdd175-611f-4abf-9a0d-763bfe6bdab8)
