### ISSUE TITLE
Änderung im Layout-DP -> keine automatische Akualisierung

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2508]
Kannst du bitte die Aktualisierung bei Änderung im layout-DP (ioBroker) mit aufnehmen. Danke.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt.Danke.
