### ISSUE TITLE
Eigener ioBroker DP für Reload / reconnect

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2509]
Bei bestimmten Scripten benötigt man die Info, ob ein reconnect durchgeführt wurde.
Da reicht dann kein reconnect, sondern es muss ein Reload durchgeführt werden.
Bitte als ioBroker-DP einfügen, so dass man darauf reagieren kann. Danke.

**Comment by Zefau** [comment]
In den Clients gibt es ein `connected` Datenpunkt, der angibt, ob der Client verbunden ist oder nicht. Außerdem gibt es die Client-Liste (`jarvis.0.clients.connected`) mit allen verbundenen (bzw. dann nicht mehr verbundenen Clients). Das wäre doch die Info, oder?

**Comment by mcuiobroker** [comment]
Leider nein. 
connected im DP wird gesetzt wenn der TAB im Focus ist.
Dadurch wird aber kein reconnect ausgelöst, wenn man zeitnah wieder zurückgeht.
Ich brauche die info, wenn er ein reconnect durchführt, oder eine Einstellung mit dem man festlegt, was er bei reconnect machen soll (reconnect oder reload).

**Comment by Zefau** [comment]
Dann aktualisiert der Datenpunkt aber nicht richtig, aber scheint mir schon das zu sein, was du brauchst. Ich wüsste nicht, was ich da sonst alternativ bauen soll. Entweder der Client ist zum Socket verbunden oder halt nicht. Ein Reconnect macht er ja, wenn er nicht connected ist.

**Comment by mcuiobroker** [comment]
Ok. Dann fixe das bitte und ich schau nochmal, ob es das ist?

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
