### ISSUE TITLE
Homematic Wandthermostat - keine Temperatur zum Einstellen

### ISSUE THREAD

**Issue by mandragora666** [Zefau/ioBroker.jarvis#251]
Hallo

Ich hab noch ein kleines Problemchen bei mir entdeckt
Ich habe meine HK Themostate (Homematic) so eingebunden
![image](https://user-images.githubusercontent.com/73381262/97082253-a8a70680-1608-11eb-9bb8-eff8a957a57e.png)

Nun wollte ich meinen Wandthermostat ebenfalls so einbinden jedoch kann ich hier beim primären und sekundären Datenpunkt nur unreach und low battery auswählen.
![image](https://user-images.githubusercontent.com/73381262/97082326-18b58c80-1609-11eb-99a1-4804c3a6fbe8.png)

Würde halt gerne meine gesamten Thermostate über den Wandthermostat einstellen. Ist jetzt auch so von mir konfiguriert das wenn ich die Temperatur am Wandthermostat verstelle alle Thermostate nachregeln.

Mache ich hier was falsch oder geht das "noch" nicht ?

vielen Dank schon im Voraus

lg
mandragora

**Comment by Zefau** [comment]
Was für eine Geräte-ID hat das Wandthermostat? `hm-cc-rt-dn` ?

**Comment by mandragora666** [comment]
HM-TC-IT-WM-W-EU OEQ1672892

**Comment by Zefau** [comment]
Das Gerät ist dem Importer noch nicht bekannt, daher müsstest du die Datenpunkte manuell anlegen.

Ich nehme es aber gerne mit auf. Du müsstest mir nur sagen, welche Datenpunkte ich übernehmen soll.
Also in folgender Form am Beispiel von `hm-cc-rt-dn`:

```

		"hm-cc-rt-dn": {
			"temperature": {
				"state": ".4.ACTUAL_TEMPERATURE"
			},
			"setTemperature": {
				"state": ".4.SET_TEMPERATURE",
				"action": ".4.SET_TEMPERATURE"
			},
			"boost": {
				"state": ".4.BOOST_MODE",
				"action": ".4.BOOST_MODE"
			}
		}
```

**Comment by mandragora666** [comment]
Hallo,

Danke dir für die Info.
Wenn du das zukünftig aufnimmst wäre das super.
Ich werde mich mal versuchen den Wandthermostat händisch einzubinden.

Die Datenpunkte sollten die gleichen wie bei den Heizkörperthermostaten sein.
Dann wäre hier alles abgedeckt.

Vielen herzlichen Dank schon im Voraus für deine Bemühungen.

lg
mandragora

**Comment by Zefau** [comment]
@mandragora666 ich kann das nur aufnehmen, wenn ich von jemanden den Input hinsichtlich der Datenpunkte bekomme. Kannst du mir das nicht mitgeben?

Ein Screenshot der Datenpunktstruktur aus ioBroker würde auch genügen, dann suche ich mir raus, was notwendig ist.

**Comment by mandragora666** [comment]
Ahh sorry.. jetzt check ich was du meinst :-D

Bitte sehr
![image](https://user-images.githubusercontent.com/73381262/97104684-19582c80-16b6-11eb-8cd0-e0e5921a9940.png)

Hab den Wandthermostat auch gleich mal manuell eingebunden. Funktioniert bestens
![image](https://user-images.githubusercontent.com/73381262/97104657-e877f780-16b5-11eb-91de-a78a3ff11781.png)

Danke und LG
mandragora

**Comment by Zefau** [comment]
Danke, ich bau es direkt ein. Was ist denn der Unterschied zwischen `.1.HUMIDTY` und `.2.ACTUAL_HUMIDITY` bzw. `.1.TEMPERATURE` und `.2.ACTUAL_TEMPERATURE` ?

**Comment by mandragora666** [comment]
Super.. herzlichen Dank dafür.
Also was die beiden Werte genau unterscheidet kann ich gerade auch nicht sagen.
Würde jetzt aber eher zu .1.HUMIDTY und .1.TEMPERATURE tendieren da die Werte besser zu meine HK Thermostat wo der Wandthermostat hängt passen.

**Comment by Zefau** [comment]
Hab die Datenpunkte mit `v1.1.0-beta.54` nun im Importer hinzugefügt. Würdest du testweise eins deiner Homematic Wandthermostat Geräte nochmal importieren?

**Comment by mandragora666** [comment]
Hallo Zefau,

Hab jetzt die aktuell beta.55 installiert und nochmals einen Import meiner Homeaticgeräte gemacht.
Blöde Frage aber muss ich vorher meine Wandthermostat den ich händisch angelegt habe nochmals löschen sodass er ihn beim Import kennt oder fügt er den Wandthermostat dann als zusätzliches Gerät unabhängig was ich jetzt händisch angelegt habe dazu ?

Hatte zuvor 73 Geräte und nach dem neuerlichen Import auch noch 73.

Danke 
LG
mandragora

**Comment by Zefau** [comment]
Vorhandene Geräte werden überschrieben. Du musst also nichts löschen, aber um nachzuvollziehen, dass alles funktioniert, wäre das praktisch. Danke dir im Voraus.

**Comment by mandragora666** [comment]
Hi

Hab den WT gelöscht und einen Import gemacht
Funktioniert wunderbar

![image](https://user-images.githubusercontent.com/73381262/97537025-6857d780-19be-11eb-9b09-5bc829cc00e5.png)


Vielen Dank fürs schnelle fixen.

lg
mandragora
