### ISSUE TITLE
v3.2.0-alpha.30 DesignFehler Layout

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2510]
Ab der zweiten zeile sind die Elemente mit Unterstrich zu weit unten.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/908225fe-3bfb-4b95-8a78-caea8491fdd1)
Hängt evtl. mit im "Layout verändert" zusammen?

Auch im Gerät
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ef4ee9d5-eae8-467d-be2e-784319aa70a5)

Beim HKT Reicht das Icon, wenn der DP nicht vorhanden ist?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ee4037e2-3abc-46b2-ac11-48c17f846855)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Update läuft nicht durch? Alte Version .30

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.36` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.36` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
