### ISSUE TITLE
v3.2.0-alpha.34 Fehler

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2511]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/4c19454f-7f07-4be9-b7e3-3b656edeb675)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/4e7133e4-4012-4538-b7ac-5514b73acfe9)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/677af220-6564-417f-95e6-c7393a5305f7)
Startet dauernd neu.

**Comment by Zefau** [comment]
Steht was im ioBroker log?

**Comment by mcuiobroker** [comment]
normale Einträge es wird nur immer neugestartet.

**Comment by Zefau** [comment]
`jarvis.0.scripts` bzw. `.css` ist nun auch mit Versionsnummer. Wie sehen da bei dir die Datenpunkte aus?

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/f940d3ed-0a5d-44b8-a01c-da9408a206b5)

**Comment by mcuiobroker** [comment]
ohne
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a1c1208d-94a0-4afc-82e4-ba5f0060fef9)

**Comment by mcuiobroker** [comment]
v3.2.0-alpha.35 genau das gleiche. Permanenter Neustart.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.36` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.36` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
