### ISSUE TITLE
[v3.2.0-alpha.30] Bodystilfehler

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2512]
Hej,

irgendwie funktionieren mit der neuen Version die Skripte nicht mehr

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/d074877b-d279-40be-936f-bd6b314f1467)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/6f58f09a-6d7a-46ab-8cdb-2f216555874b)

gehört das hier mit zu?
https://github.com/Zefau/ioBroker.jarvis/issues/2487

VG

**Comment by Zefau** [comment]
Der StateStyle ist falsch meinst du, weil alles grün ist? Hast du auch BodyStyle drin der nicht geht?

**Comment by Mephisto090** [comment]
ne eigentlich müsste alles weg sein und nur Sachen angezeigt werden die "offen" bzw. "an" sind

**Comment by Mephisto090** [comment]
die Farben sind richtig. Mein Fehler. Er dürfte alle einfach nicht anzeigen

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.36` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.36` should fix the bug - please verify. If the bug has been solved, you may close the issue.
