### ISSUE TITLE
v3.2.0-alpha.35 Einstellungen Fehler

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2513]
Wenn ich in der jarvis Konfiguration die `Einstellungen` aufrufe, kommt folgender Fehler:

![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/a1657f32-30b2-4645-90a8-f2bf54107a8f)

**Comment by Bernd9000** [comment]
Häufig bleibt die Einstellungs Seite leer.
Hab mal die jarvis Instanz auf debug gestellt.
Der Refresh wiederholt sich immer wieder ?


![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/be38e407-6d21-4c62-81a2-4fc42d231792)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.36` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.36` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Nein, noch vorhanden, Meldung hat sich verändert.
Der erste Aufruf der `Einstellungen` funktioniert noch, drückt man dann im Browser F5 kommt der Fehler.

![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/686b06c1-a425-4610-88f5-e8a02628288f)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.37` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.37` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Ja, Fehler ist weg
