### ISSUE TITLE
Das Wetter Widget findet sporadisch den Ort nicht

### ISSUE THREAD

**Issue by bsteimer** [Zefau/ioBroker.jarvis#2514]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? 3.1.8
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
In unregelmäßigen Abständen (ca. alle 4 Aufrufe) findet das Wetter Widget den Ort nicht und zeigt die Fehlermeldung:
`Der gesuchte Ort existiert nicht. Versuchen Sie es mit einer anderen Ortschaft oder wenden Sie sich an den Webmaster (info@daswetter.com).`

Es ist kein Fehler in der Konsole ersichtlich

**Screenshots**
<img width="1668" alt="image" src="https://github.com/Zefau/ioBroker.jarvis/assets/46819559/b99ab54a-183b-4f47-aa40-50c5cb672731">

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Hierzu gibt es bereits das Issue https://github.com/Zefau/ioBroker.jarvis/issues/1803. Wird mit v3.2 behoben.
