### ISSUE TITLE
[v3.2.0-alpha.36] Darkmode

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2515]
Hej,

der Darkmode funktioniert nicht mehr :(

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/ba26fda1-6433-4a1a-b38e-07210af4b079)

VG

**Comment by Zefau** [comment]
Sorry, hab viel umgebaut in der Alpha. Mit der nächsten Alpha heute wird das behoben sein.

**Comment by Mephisto090** [comment]
Ich bin schon blind :D

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.37` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.37` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Mephisto090** [comment]
Leider nein 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/61fbced6-66ae-4f05-bf26-d9e6e4049a86)

**Comment by intruder7777** [comment]
ich häng mich hier mal mit rein. Bei mir funktioniert der DarkMode auch nicht. Der Datenpunkt ist "true" aber in den Einstellungen steht der Toggle auf false. Im Browser Log zeigt er auch Fehler beim Laden der Einstellungen
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/1458fbec-3a19-4bfa-a26a-01538c2cd5a0)

Das Ändern des Toggles auf true speichert er auch nicht ab.
Dann ist auch beim Reload das PopUp zu sehen.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/644c6747-7c62-4d39-8fbf-d31487953ade)

ändere ich jarvis.0.settings.tourIntroduction auf false speichert er es zwar aber beim erneuten Reload setzt er es genau in dem Moment wenn ich auf "skip" drücke wieder auf true

**Comment by Bernd9000** [comment]
Vom Prinzip her funktioniert es hier wieder bei der Version v3.2.0-alpha.37.
Habt hier schon mal IOBroker neu gestartet ?

**Comment by intruder7777** [comment]
konnte mir nicht vorstellen das dies etwas bewirken soll. Getan und die selben Probleme wie vorher auch

**Comment by Mephisto090** [comment]
> Deaktivier mal die Option + speichern und danach wieder aktivieren.

Das hat bei mir etwas gebracht: `Dark Mode: False -> Gespeichert -> Dark Mode: True -> Gespeichert` und siehe da. Alles schwarz :D

**Comment by Mephisto090** [comment]
> > Deaktivier mal die Option + speichern und danach wieder aktivieren.
> 
> Das hat bei mir etwas gebracht auf Version [`v3.2.0-alpha.37`]: `Dark Mode: False -> Gespeichert -> Dark Mode: True -> Gespeichert` und siehe da. Alles schwarz :D
> 
> Das Willkommen zu Jarvis Fenster wie bei @intruder7777 habe ich nur am Tablet, nicht am PC

Also jetzt ist wieder alles weiß :(

**Comment by Mephisto090** [comment]
Sobald ich beim Willkommensfenster auf Skip drücke (Was nur im Tablet angezeigt wird) wird die ganze Seite wieder Weiß.

**Comment by intruder7777** [comment]
bei 39 keine Änderung

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.39` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.39` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
zusätzlich zum Problem Darkmode hab ich immer noch das Problem dass Einstellungen nicht gespeichert werden.
z.B
enable Styles
enable Skripts
usw

**Comment by Zefau** [comment]
Hast du Fehler in der Browser Konsole (via F12)?

**Comment by intruder7777** [comment]
im Moment wenn ich den Schalter für den Dark Mode auf True stelle
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/290aea03-6cd8-4907-9b1a-8d8dc03bf0f9)

im Moment wenn ich den Schalte Skripte enable auf True stelle

![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/9a63e6e9-f522-47b3-ab8a-c8a797dfd35b)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.42` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.42` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by djalexz** [comment]
Moin Zefau,

mit der `v3.2.0-alpha.42` funktioniert der Darkmode wieder.
Allerdings kommt das Willkommen-Fenster bei jedem neuladen der Seite immer wieder. Egal ob ich das skippe oder auf weiter mit manueller Konfiguration klicke.

Hierfür muss verm. ein neues issue öffnen oder?

LG Alex
