### ISSUE TITLE
[v3.2.0-alpha.36] Kalender

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2516]
Hej,

mal wieder was mit dem Kalender

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/105795ef-576a-4dae-a4d7-8b7065fbf53f)

VG

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.37` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.37` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Mephisto090** [comment]
funktioniert
