### ISSUE TITLE
[v3.2.0-alpha.36] Keine DPs mehr übernehmen

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2517]
Hej,

mit dieser Version kann ich bei einem vorhanden Gerät keine neuen DPs hinzufügen oder bearbeiten. Nach dem Übernehmen drücken werden sie nicht gepseichert bzw. übernommen.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/56cec5e7-3169-485b-bede-483af718a776)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/958d1079-ebf4-4ffb-9b4c-62731bcdbc11)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.37` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.37` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
der Fehler existiert noch bei mir

**Comment by Mephisto090** [comment]
Bei mir funktioniert es mit Version `v3.2.0-alpha.37`

**Comment by Mephisto090** [comment]
Bei mir will er jetzt nicht mehr das speichern:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/85995176/10ecde3b-00a0-4201-be91-bc2c755d94e4)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.39` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.39` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
auch wenn das Speichern an anderen Stellen immer noch nicht funktioniert, aber einen DP kann ich hinzufügen

**Comment by Zefau** [comment]
> Bei mir will er jetzt nicht mehr das speichern:

@Mephisto090  Das sollte nun behoben sein.

> auch wenn das Speichern an anderen Stellen immer noch nicht funktioniert, aber einen DP kann ich hinzufügen

@intruder7777 Ich schließe das hier mal. Für die anderen Stellen haben wir ja noch offene Issues.
