### ISSUE TITLE
v3.2.0-alpha.37 Fehlermeldungen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2518]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0acda558-4fe0-45fd-bb90-98c9cdc507de)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/aae366ce-5a68-4bdb-a1df-265f8f501b5f)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.39` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.39` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
im Moment wenn ich in die Einstellungen gehe
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/e966c40b-e8d2-4901-bf24-9ec2325e8269)

**Comment by intruder7777** [comment]
@Zefau bei mir erstmal gut mit der 42... Kalender noch gelbe Meldungen aber dafür gibt es ein eigenes Issue
