### ISSUE TITLE
[v3.2.0-alpha.37] invalid time value im ioBroker Log

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2519]
in der Version 37 ist die Meldung invalid time value die vorher im Kalendermodul auftauchte in den Log gewandert und flutet diesen quasi.

`<html>
<body>

jarvis.0 | 2024-01-06 10:40:00.661 | warn | Invalid time value
-- | -- | -- | --
jarvis.0 | 2024-01-06 10:40:00.602 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:40:00.544 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:40:00.432 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:35:00.558 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:35:00.510 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:35:00.486 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:35:00.355 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:30:00.561 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:30:00.510 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:30:00.453 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:30:00.413 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:25:01.082 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:25:00.980 | warn | Invalid time value
jarvis.0 | 2024-01-06 10:25:00.944 | warn | Invalid time value

</body>
</html>`

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.39` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.39` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
leider nein
zusätzlich zum veränderten Log im ioBroker
`<html>
<body>

jarvis.0 | 2024-01-08 15:45:00.385 | warn | Failed parsing ical of calendar Papa: Invalid time value
-- | -- | -- | --
jarvis.0 | 2024-01-08 15:45:00.342 | warn | Failed parsing ical of calendar Familie: Invalid time value
jarvis.0 | 2024-01-08 15:40:00.494 | warn | Failed parsing ical of calendar Papa: Invalid time value
jarvis.0 | 2024-01-08 15:40:00.458 | warn | Failed parsing ical of calendar Familie: Invalid time value
jarvis.0 | 2024-01-08 15:40:00.416 | warn | Failed parsing ical of calendar Papa: Invalid time value
jarvis.0 | 2024-01-08 15:40:00.328 | warn | Failed parsing ical of calendar Familie: Invalid time value


</body>
</html>`

ist jetzt wieder der Fehler im Widget. Vermutlich alle nicht ganztägigen Termine

![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/a0818b74-f826-424c-9f4f-76cb641020f5)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.55` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.55` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
@Zefau nope, immer noch Fehler im Calender Modul
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/95b83380-9cf3-4e53-bfa2-3cb2d5791e64)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/967cfaa2-5a6a-4bf3-bb91-f20276e627bd)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/90285e0a-52d3-47c8-8c90-28cf5f1e5fa9)

**Comment by Zefau** [comment]
Hast du Termine in den ical-Daten, die gern Start-Datum haben?

**Comment by Zefau** [comment]
Stell mal bitte die jarvis Instanz auf `debug`. Zu den Fehlermeldungen sollte es noch Debug-Meldungen geben für mehr Informationen.

**Comment by intruder7777** [comment]
einmal diese hier
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/9f326259-ff95-4720-a48a-ff3ee26c6f13)
console
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/8e3e0afd-24f2-47ba-a43f-76765f1f1b7a)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/f27ba25a-4679-4818-a9ae-5e48c70910cc)

Im Kalender fehlt auch die Datums und Zeitanzeige

**Comment by teletapi** [comment]
Nabend, ich hab jetzt mal bei mir die Frage nach dem umstellen auf Debug gemacht und folgendes ergebniss in der Konsole. die warnungen treten auf sobald man den Kalender zb von Januar auf februar weiterblättert. Die Syntaxfehler kommen sobald ich einen tag mit terminen anklicke. Zudem werden nach januar nichtmehr alle Kalender angezeigt, jährliche geburtstage werden zb. fehlen nach januar komplett.

Version 3.2.0 alpha57

[2024-01-31 003936.653 - info host.i.txt](https://github.com/Zefau/ioBroker.jarvis/files/14105568/2024-01-31.003936.653.-.info.host.i.txt)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
@Zefau im Widget selbst keine Fehler mehr. Datum und Zeit wird auch angezeigt.
Nur im ioBroker Log noch Fehler dazu
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/e75ff5f7-6a3f-4cad-af9c-b8b428945ffc)

**Comment by Zefau** [comment]
Kannst du mir für die beiden Beispiele die ical Rohdaten zur Verfügung stellen? Anhand des Codes fällt es mir schwer den Fehler zu identifizieren. Danke dir!

**Comment by intruder7777** [comment]
Hi, da das gerade die Kalender von mir und meiner Familie sind, ungern. Da stehen zu viele private Sachen drin. Beim Abfall Kalender wäre mir das egal. Aber der spuckt keine Fehler mehr aus.

**Comment by Zefau** [comment]
Ich brauche nicht das ganze ical File, nur den im Fehler genannten Termin und die Beschreibung kannst du da natürlich ändern.

**Comment by intruder7777** [comment]
das dürfte der Teil aus dem Familienkalender sein...
`TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT
DTSTART;TZID=Europe/Berlin:20230221T171500
DTEND;TZID=Europe/Berlin:20230221T190000
RRULE:FREQ=WEEKLY;WKST=MO;COUNT=17;BYDAY=TU
EXDATE;TZID=Europe/Berlin:20230404T171500
EXDATE;TZID=Europe/Berlin:20230411T171500
EXDATE;TZID=Europe/Berlin:20230530T171500
DTSTAMP:20240204T135934Z
UID:xxxxxxxx@google.com
CREATED:20230128T181729Z
LAST-MODIFIED:20230128T181854Z
LOCATION:xxxxxx
SEQUENCE:1
STATUS:CONFIRMED
SUMMARY:xxxxxx Schwimmen
TRANSP:OPAQUE
END:VEVENT
BEGIN:VEVENT`

**Comment by Zefau** [comment]
Seltsam, also mit den Daten zeigt er es mir sauber in jarvis an und ohne Fehlermeldung in ioBroker.

**Comment by intruder7777** [comment]
was soll ich sagen....auch jetzt nach der Beta 3 immer noch der ganze Log zu mit diesen Fehlermeldungen

**Comment by Zefau** [comment]
Sehr merkwürdig. Die Fehler hattest du mit v3.1 nicht? Kannst du einen der betroffenen Termine im Kalender mal bearbeiten? Tritt es dann immer noch auf?}

**Comment by intruder7777** [comment]
Es handelt sich in dem einen Kalender um eine vergangene Terminserie die immer am Samstag von  22:00 bis 04:30  bis zum 2.April 2016 einen Termin hatte.
habe auch im Google Kalender dort mal die Zeit geändert aber der Fehler kam trotzdem
Hier nochmal der ical Part von dem Termin

BEGIN:VEVENT
DTSTART;TZID=Europe/Amsterdam:20140208T220000
DTEND;TZID=Europe/Amsterdam:20140209T043000
RRULE:FREQ=WEEKLY;WKST=MO;UNTIL=20160402T195959Z;INTERVAL=2;BYDAY=SA
DTSTAMP:20240207T173732Z
UID:xxxxxxxxxxxx@google.com
CREATED:20140204T181919Z
LAST-MODIFIED:20240207T173033Z
LOCATION:xxxxxxx
SEQUENCE:0
STATUS:CONFIRMED
SUMMARY:xxxxx
TRANSP:OPAQUE
END:VEVENT
END:VCALENDAR

und hier der Log

<html>
<body>

jarvis.0 | 2024-02-07 18:40:00.596 | debug | {"start":"Sat Feb 08 2014 22:00:00 GMT+0100 (Mitteleuropäische Normalzeit)","end":"Sun Feb 09 2014 04:30:00 GMT+0100 (Mitteleuropäische Normalzeit)","isAllDay":false,"time":"22:00-04:30","multiDay":"true","duration":0}
-- | -- | -- | --
jarvis.0 | 2024-02-07 18:40:00.596 | debug | {"locale":{"code":"de","formatLong":{},"localize":{},"match":{},"options":{"weekStartsOn":1,"firstWeekContainsDate":4}},"start":"2014-02-08T21:00:00.000Z","end":"2014-02-09T03:30:00.000Z","isAllDay":false,"time":"22:00-04:30","multiDay":true,"duration":0}
jarvis.0 | 2024-02-07 18:40:00.596 | warn | Failed mapping a recurring event of calendar Papa: Invalid time value
jarvis.0 | 2024-02-07 18:40:00.596 | debug | {"start":"Sat Feb 08 2014 22:00:00 GMT+0100 (Mitteleuropäische Normalzeit)","end":"Sun Feb 09 2014 04:30:00 GMT+0100 (Mitteleuropäische Normalzeit)","isAllDay":false,"time":"22:00-04:30","multiDay":"true","duration":0}
jarvis.0 | 2024-02-07 18:40:00.596 | debug | {"locale":{"code":"de","formatLong":{},"localize":{},"match":{},"options":{"weekStartsOn":1,"firstWeekContainsDate":4}},"start":"2014-02-08T21:00:00.000Z","end":"2014-02-09T03:30:00.000Z","isAllDay":false,"time":"22:00-04:30","multiDay":true,"duration":0}
jarvis.0 | 2024-02-07 18:40:00.596 | warn | Failed mapping a recurring event of calendar Papa: Invalid time value


</body>
</html>

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.67` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.67` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@intruder7777
