### ISSUE TITLE
CustomHTML Scaling is not working correkt

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#252]
die Map meines Saugroboters liegt in deinem Datenpunkt im folgenden Format vor

<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAABUAAAAZ4CAYAAABQx21mAAAABmJLR0QA/wD/AP+gvaeTAAAgAElEQVR4nOzcv04jX57GYTPqDDkhcey+hw7nLogJmGQd0SIhGKTVSExAgprImywBMXexYd9DO3ZCYhEzQW/rRx1oqguXXVVvPU9W+N9x2djWV0efyQQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA

..... ewig so weiter

AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYkF/YXhJkZlhU6AAAAABJRU5ErkJggg==" style="width: auto ;height: 100%;" />

![image](https://user-images.githubusercontent.com/73311538/97082322-10f5e800-1609-11eb-8c66-3af4cf8aac01.png)
![image](https://user-images.githubusercontent.com/73311538/97082329-1c491380-1609-11eb-9636-854538a83547.png)

Map viel zu groß, egal ob "skaliere inhalte" ein oder aus ist

Maximalhöhe 300, Skalierung aus

![image](https://user-images.githubusercontent.com/73311538/97082367-60d4af00-1609-11eb-903a-3173d5aef35e.png)

Maximalhöhe 300, Skalierung an
Map ist nicht mehr im Widgetbereich
![image](https://user-images.githubusercontent.com/73311538/97082375-79dd6000-1609-11eb-84b9-a05c591235b8.png)

Wenn ich im Datenpunkt vom bild am ende den Style Händisch so abändere
style="width: 300px"
Wird das bild entsprechend kleiner.

Ist es möglich widget so anzupassen, dass das bild "hineingezwungen" wird?
Da width:auto im Datenpunkt steht müsste es ja irgendwie anpassbar sein

**Comment by Timmes123** [comment]
in einer versuchswebseite hat es geholfen im css style das hier festzulegen

img {
   max-width: 100%;
   max-height: 100%; 
   width: auto;
   height: auto;
}

**Comment by Zefau** [comment]
should be fixed with `v1.1.0-beta.52`.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/507007

**Comment by Timmes123** [comment]
gerade getestet mit beta 52
mit skalieren ein/aus passiert gar nichts
das einzige was hilft ist die maximale höhe einzugeben.
das hab ich jetzt z.b. auf 600 stehen. dann wird das bild kleiner.
ist aber fast zu klein für die visu am pc, aber zu groß fürs handy.
irgendwie müsste das noch etwas dynamischer gehen

**Comment by Timmes123** [comment]
gerade mit beta54 festgestellt, dass die mein <img> gar nicht mehr angezeigt wird. egal welche einstellungen ich in der konfig mache

**Comment by Zefau** [comment]
Sollte mit beta-55 wieder passen.

**Comment by Zefau** [comment]
Kannst du mal statt `px` die Einheit `vh` für die Höhe verwenden? Siehe auch https://wiki.selfhtml.org/wiki/CSS/Wertetypen/Zahlen,_Ma%C3%9Fe_und_Ma%C3%9Feinheiten#Relative_L.C3.A4ngenma.C3.9Fe

`vh` ist eine relative Einheit in Relation zur Höhe des Viewports. Damit solltest du ein gutes Ergebnis sowohl auf Desktop als auch mobil erreichen. `px` hingegen ist immer absolut.

**Comment by Timmes123** [comment]
Das hab ich nicht ganz verstanden..
meinst du ich soll an die stelle hier schreiben?
![image](https://user-images.githubusercontent.com/73311538/97714397-6591db00-1ac1-11eb-9d31-0298af5aeb1d.png)

**Comment by Timmes123** [comment]
Das hab ich nicht ganz verstanden,
meinst du so?
![image](https://user-images.githubusercontent.com/73311538/97714749-d6d18e00-1ac1-11eb-87ce-c815d2c0f478.png)
