### ISSUE TITLE
Tooltip bei mousemove über Layout-WidgetName - Type (Name)

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2524]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/16b13e90-4325-471d-8e17-e2eda8a5816b)

Geht man mit der Maus über den Namen vom Widget wird nur ein kleiner grauer Block angezeigt.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.42` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.42` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
