### ISSUE TITLE
[v3.2.0-alpha.41] Keine Widgets-Anzeige im Fully Kiosk Browser

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2525]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5936b971-5115-4566-89e0-1c6e28970c73)

**Comment by Zefau** [comment]
Funktioniert bei mir mit fully `1.54.1-play`. Hast du das bei jedem Tab?

**Comment by mcuiobroker** [comment]
Gleiche Version. Ja.

**Comment by mcuiobroker** [comment]
Kannst du sowas bei Dir einbauen, damit man das log in einen DP bekommt.
```
function logToDP(active){
	let originalConsoleLog = console.log;
	console.log('%clogDP aktiv','color:red;')
	if(active){	
		console.log = function() {
			originalConsoleLog.apply(console, arguments);
			let logMessage = Array.from(arguments).join(' '); 
			sendToDataPoint(logMessage); 
		};

		function sendToDataPoint(message) {
			//console.log('Protokoll an Datenpunkt senden:', message);
			window.Socket.setState(logDP, message);
		}
	}else{
		console.log = originalConsoleLog;	
	}
}
```

**Comment by mcuiobroker** [comment]
Irgendwie scheint es mit einer Größenabfrage zu tun?
Auf einem Tablet wird es zwar im Fully Kiosk Browser angezeigt, aber dort ist die Willkommens-Nachricht da.
Und die anderen Fehler, wie Styles wird nicht genutzt, usw...

**Comment by mcuiobroker** [comment]
Man musste den Cache löschen.
Jetzt habe ich auch auf dem Handy mit Fully Kiosk Die Willkommensmeldung.

**Comment by mcuiobroker** [comment]
Kann eigentlich zu da jetzt die gleichen Problem, wie bei allen anderen. Dies wurde schon in anderen Issue erklärt.
- Willkommens-Nachricht permanent
- keine Umsetzung von CSS
- keine Umsetzung von scripts
