### ISSUE TITLE
[v3.2.0-alpha.41] Änderungssymbole nicht erreichbar bei kleinen Widgets

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2526]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8c8f4951-e7b8-472e-9f19-a671217f5a13)
Größe 1w 2h
Elemente fehlen
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/4e476fdb-8db7-409c-90d0-8989b174b84a)

Verständllich, da zu wenig Platz.
evtl bei Klick in solchen Fällen Menü einblenden für Auswahl der Änderung?

Oder Infos (Breite, Höhe, usw) auf den hover verlagern in solchen Fällen.

**Comment by mcuiobroker** [comment]
Hast sich nichts verändert
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9449bc7a-055a-443f-aa65-73b24d89e05c)

**Comment by Zefau** [comment]
Rechtsklick gibt das nun ein Kontextmenu mit den Optionen.

**Comment by mcuiobroker** [comment]
Ah.. Ok. Passt.Danke
