### ISSUE TITLE
[v3.2.0-alpha.41]  Fehlermeldung evtl von scripts?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2527]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c7745dbf-7535-4dc4-ae50-a4fda32763fe)

Kann man dazu mehr Infos erhalten?
Ausgelöst durch Shift + Klick auf TAB (q-tab)

**Comment by Zefau** [comment]
Der tritt vor v3.2 nicht auf, richtig?

**Comment by mcuiobroker** [comment]
Doch in v3.1.8 auch.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/08634649-0de6-4585-b13f-7d0272b29408)

**Comment by Zefau** [comment]
Glaube das ist ein Fehler in vue-router. Ich kann das nachstellen, aber der Fehler kommt in der dev Umgebung dann von vue-router, nicht von jarvis. Ich schau mal, ob ich das in einer Sandbox außerhalb von jarvis nachgestellt bekomme und dann mache ich ein Ticket dort auf.

**Comment by Zefau** [comment]
https://github.com/quasarframework/quasar/issues/16791

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.52` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.52` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Kommt kein Fehler mehr. Danke.
