### ISSUE TITLE
[v3.2.0-alpha.41] Kopieren und Löschen beim Gerät wird nicht korrekt durchgeührt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2528]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8b7fcb3b-2076-4e05-ae5d-b839a64273d7)

Beim Löschen kommt keine Bestätigungsabfrage
Beim Kopieren wird teilweise nichts gemacht, erst wenn man auf SpeichernundZurück klick und wieder mit F2 rein geht ist die COPY da.
Teilweise ist die COPY aber auch sofort da.
??
Keine Fehler im F12-LOG

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.43` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.43` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
