### ISSUE TITLE
[v3.2.0-alpha.41] Date Picker Action - kein Heute Button

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2529]
Es wird kein Heute Button angezeigt, obwohl in den Einstellungen ausgewählt.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/023135e7-cb9f-4f1f-9119-c45f07b7a832)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a0b29a53-9e2f-4860-9eb4-365c6051d610)

**Comment by Zefau** [comment]
Den "Heute-Button" gibt es im kompakten Modus nicht. Ich werde die Option ausblenden.

**Comment by mcuiobroker** [comment]
Passt. Danke.
