### ISSUE TITLE
[v3.2.0-alpha.41] LightColorAction Nach Farbauswahl verschwindet ein Teil von der Eingabe

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2530]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/7fab8b6b-680e-4342-9598-d5e884a03e24)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/b42657e8-1346-4404-aff2-3929c2780e10)

**Comment by Zefau** [comment]
Kann ich nachstellen. Es scheint nach der Auswahl eines Wertes, dass die Box breiter wird und daher aus dem Sichtbereich "wandert".

**Comment by mcuiobroker** [comment]
Passt.Danke.
