### ISSUE TITLE
[v3.2.0-alpha.41] TimePickerAction Kompakter Modus mit Hover Verbotsschild

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2531]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ef37168e-aeb3-4a81-880d-1027712031f3)
Man sieht ein Verbotsschild, wenn man mit der Maus über den Schalter fährt.
Schalten ist aber möglich.
?

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.42` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.42` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Weiterhin mit Halteverbotschild
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/38ba8c5f-bec5-401b-96c9-1ce2faadf17a)
Jetzt kann man den Kompakt Modus nicht mehr wählen.

**Comment by Zefau** [comment]
Ist im Standard aktiviert und kann nicht deaktiviert werden für Action (nur für Body). Ich weiß allerdings auch nicht mehr, warum ich das so gebaut habe.

**Comment by mcuiobroker** [comment]
Bleibt dann so.
