### ISSUE TITLE
[v3.2.0-alpaha.41] Layout Bearbeitung - Fehlende Komplette Seitenübersicht 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2532]
Früher hatte man direkt gesehen, wie viel Platz noch auf einer Seite nach unten war.
Die Fläche wurde sofort in der Größe dargestellt (~) 
Das  fehlt jetzt. Man müsste eine Grenzlinie gezeigt bekommen, wo man erkennen kann,  
wie weit es noch bis zum Ende der Seite / Tab
ist?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ec30d682-776e-47fb-88c8-30a039d5446a)

**Comment by Zefau** [comment]
Was genau fehlt? Du meinst es waren vorher mehr Informationen im Widget?

**Comment by mcuiobroker** [comment]
Die Seiten / Tab-Höhe war größer, man konnte direkt mehr Element sehen.
Momentan ist die Höhe der Seite = Höhe vom 1. Widget.

**Comment by Zefau** [comment]
Die Höhe entspricht der Höhe aller Widgets. Du hast nur ein Widget drin im Screenshot, daher ist es nur so hoch. Wenn du da noch ein Widget (übereinander angeordnet) hinzufügst, dann sollte es so hoch sein wie beide Widgets.

**Comment by mcuiobroker** [comment]
Vorher hatte ich aber schon eine größere Höhe, so dass man direkt abschätzen konnte, was auf eine Seite passt.
Jetzt ist die Höhe ca 300px vorher ca 800px oder mehr.

**Comment by Zefau** [comment]
ok, verstehe. Ich schau nochmal rein.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.43` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.43` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Sieht schon gut aus. Problem ist noch, dass wenn man ein Widget hinzufügt er wieder noch oben springt.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/322d3251-8c35-412a-a3a2-739a269e514d)


Es sollte maximal bis zum Widget hinzufügen springen.


![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a55b774f-2a29-402c-87d4-bedd9245720b)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.44` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.44` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Ja. Passt. Danke.
