### ISSUE TITLE
[v3.2.0-alpha.42] Binding für Label funktioniert nicht mehr

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2534]
Hat mit v3.2.0-alpha41 noch funktioniert.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/19afa903-dd1c-457f-b853-61ea9fe8a703)

`{"default":"'{0_userdata.0.echarts.echartsDP}'"}`

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6180148d-ec40-42c9-b9b9-db17c691deb4)

Jetzt habe ich nochmal die aplha.41 installiert und dort geht es auch nicht mehr.

**Comment by mcuiobroker** [comment]
#2197 vielleicht passt das ja da gerade mit rein.

**Comment by Bernd9000** [comment]
@mcuiobroker 
Mal ne Zwischenfrage....
Funktionieren bei Dir denn die Bindings im `Icon` und `Icon Stil` mit fremden Datenpunkt ?

**Comment by Zefau** [comment]
Fehler ist dadurch verursacht, dass im Datenpunkt genau der Datenpunkt verwendet wird. Dadurch wird der Datenpunkt, aber nicht das Bindung durch jarvis verarbeitet. Alternativ würde `{val}` bzw. `{value}` funktionieren.

**Comment by mcuiobroker** [comment]
Also bei mir funktioniert die "normale" Umschaltung bei Icon. Also bei dem val -> false, true ok.
Bei Icon Stil bekomme ich gar keine Farbe angezeigt.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/cff4efb4-06dc-4235-b01c-c8b821ae0698)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/658f531c-1529-4570-a340-007bb88013bd)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6f1ccc64-b7e3-4d36-a175-ae1a8aebb3ec)
Fremd-DPs prüfe ich noch

**Comment by Bernd9000** [comment]
Icon Stil funktioniert bei mir dem  Zauberwort `color`
{"true":{"color":"green"},"false":{"color":"red"}}

**Comment by mcuiobroker** [comment]
Ja, hab noch die "alte" Version drin gehabt.

**Comment by Bernd9000** [comment]
Ich krieg es einfach nicht hin mit fremden Datenpunkten.
Gibt es für das `Binding` eigentlich irgendwelche erwieterte Logs/Meldungen die ich prüfen kann?

**Comment by mcuiobroker** [comment]
Zeig doch mal Dein Binding

**Comment by Bernd9000** [comment]
Z.B.:
[#2490](https://github.com/Zefau/ioBroker.jarvis/issues/2490#issuecomment-1878433044)

**Comment by mcuiobroker** [comment]
Ah, also ein besonderer Fremd-DP -> Type string. Muss ich probieren.

**Comment by Bernd9000** [comment]
Auch bei ohne      ` && {val}=false`

**Comment by mcuiobroker** [comment]
Ja.
```
{
  "'{0_userdata.0.jarvis.test.text3}'='aus'": "mdi:relative-scale",
  "{0_userdata.0.jarvis.test.boolean1} = false && {val}=false": "home-circle-outline",
  "true": "home-account",
  "default": "solar:home-outline"
}
```
IconStyle
```
{
  "true": {
    "color": "yellow"
  },
  "{0_userdata.0.jarvis.test.boolean1} = false && {val}=false": {
    "color": "red"
  },
  "default": {
    "color": "blue"
  }
}
```
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8b2902bb-e93b-4b7f-b06e-1ea187433c2a)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/b7129769-f8ee-437d-a34b-27c2a52b4e2f)

**Comment by mcuiobroker** [comment]
Ein Upload hast du schon mal gemacht?
```
iob upload jarvis
```

**Comment by Bernd9000** [comment]
Das ist aber wieder mit boolean, oder ?
Upload mach ich bei jeder neuen Version

**Comment by mcuiobroker** [comment]
Nee string
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/d79da105-522d-43e7-b4cf-34e59c220351)

**Comment by mcuiobroker** [comment]
Hab jetzt mal Dein Beispiel genommen .
Blinkt gelb bei true oder false, wenn Offine gesetzt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5013e23c-730f-4ef4-b189-7b92223adc68)

**Comment by Bernd9000** [comment]
Okay Danke,
Dann liegt es bei mir an was anderem.
Das wird schwierig.....

**Comment by mcuiobroker** [comment]
Ist der Type vom DP denn string oder was anderes?

**Comment by Bernd9000** [comment]
Sowohl `power` und `status` sind string

**Comment by Bernd9000** [comment]
@mcuiobroker 
Wie hast Du den Datenpunkt "0_userdata.0.jarvis.test.text3" angelegt ?
Mit einem script?

**Comment by mcuiobroker** [comment]
Hab die Frage per Mail bekommen, sehe sie aber nicht in github???
Ja per script angelegt.

**Comment by Bernd9000** [comment]
Ja, hatte ich gelöscht.

Hab den Fehler wohl gefunden.
Wenn ich Dein Pfad nehme funktionierte es plötzlich.
{0_userdata.0.jarvis.test.text3}

Es liegt wohl an dem GROßBUCHSTABEN im Verzeichnßnamen.
Mit {0_userdata.0.Jarvis.test.text3} funktioniert es nicht.

@Zefau 
Kannst Du das bestätigen ?

**Comment by mcuiobroker** [comment]
Das hatten wir auch bei der Geräte Filterung

**Comment by Zefau** [comment]
Danke euch für die Mühe!

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.50` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.50` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Einige Bindings gehen jetzt aber noch nicht alle.
Es kommt ein Binding Fehler im Log.
Wofür steht der `o.state` ?

Log:
 2024-01-22 14:42:51.509 | warn | 192.168.0.100  (Firefox) - Devices-jEk6S8dX, Error resolving bindings for device  Testschalter10 (b950c530-5728-43d7-a9ad-38ef0573c064): o.state is  undefined

**Comment by Bernd9000** [comment]
v3.2.0-alpha.50

Fehler :
Datenpunkt-Schlüssel darf nicht den Namen `power` haben.
Hab den Schlüssel hier unbenannt auf `power2` und dann funktionierte das Binding im "Icon" und "Icon Stil"
Beim "Datenpunkt Stil" darf ich bei der Version gar kein Binding eintragen sonst funktioniert es gar nicht.

![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/96db1a4a-8826-4243-b914-ad7b7ede2076)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.56` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.56` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Super, läuft, kann dicht.
