### ISSUE TITLE
[v3.2.0-alpha.42] CSS wird nicht korrekt angezeigt bzw. alte Version wird hartnäckig gehalten

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2535]
Bei Änderung im ioBroker DP  CSS wird es im Frontend nicht angepasst.
Auch bei F2 wird alte Version angezeigt.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a0b3cfb7-eb45-40b3-b24d-0a3300119083)
War anscheinend auch vorher schon der Fall. -alpha.41

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.48` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.48` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Sieht gut aus. Danke.
