### ISSUE TITLE
[v3.2.0-alpha.42]  tourIntroduction und tourInterface setzen sich immer wieder auf True

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2536]
da das Issue mit dem Darkmode zu funktionieren scheint, lege ich dafür mal ein  eigenes an.
Bei einem Reload kommt ständig 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/ec268100-ed7c-44a7-baba-12e4f47b5f54)

ein setzen der Objekte auf false ändert nicht daran und beim skippen werden sie jedesmal wieder auf true gesetzt.

**Comment by Zefau** [comment]
`true` ist korrekt und meint, dass die Tour bereits durchlaufen wurde. Ein Setzen auf `false` resultiert im Ausführen der Tour.

Tritt das Verhalten auf, wenn du in der Konfiguration speicherst oder ist das komplett unabhängig vom Speichern?

**Comment by djalexz** [comment]
Hi Zefau, ich antworte mal.
Das Verhalten ist komplett unabhängig vom Speichern in der Config.

Das Frontend ignoriert einfach die Einstellung und zeigt das Welcome Fenster an. Egal was in dem Datenpunkt eingestellt ist.

LG Alex

**Comment by mcuiobroker** [comment]
@djalexz Ist das Gerät ein Android oder PC ?

**Comment by djalexz** [comment]
> @djalexz Ist das Gerät ein Android oder PC ?

Sowohl, als auch und auch egal welcher Browser.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.44` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.44` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by djalexz** [comment]
Leider nicht.
In der Version ändern sich die Popups "Willkommen" und beim Neuladen der Seite "Erklärung Die Seitenleiste"
Beides kann geskippt werden und beim Neuladen wiederholt sich das Ganze.

Ebenso ist das Darfmode Problem mit der Verion wieder da.

Die Eisntellung für den Darkmode wird wieder ignoriert.

LG Alex

**Comment by mcuiobroker** [comment]
Kommt direkt, wen man in die Konfig geht F2.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0a4efdb2-54dc-438b-86c4-0a37e68a6dbe)

**Comment by intruder7777** [comment]
bei mir genauso wie Alex es beschrieben hat

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.45` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.45` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by djalexz** [comment]
Jawohl, nachdem leeren des Caches, alles gut. Vielen Dank für die schnelle Behebung. Ich teste weiter mit der neuen Version.

LG Alex
