### ISSUE TITLE
iFrame wird trotz Option `Aufrechterhalten` neu geladen

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2537]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/2533

<div type='discussions-op-text'>

<sup>Originally posted by **mcuiobroker** January 18, 2024</sup>
v3.2.0-alpha.42
Die Option "Aufrechterhalten" im Iframe soll doch das iFrame halten, so dass nicht bei TB-umschalten immer wieder neu geladen wird , oder?
Das funktioniert mit v3.2.0-alpha.42 nicht mehr</div>

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.47` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.47` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
wird immer noch neu geladen

**Comment by Zefau** [comment]
Besteht der Fehler noch mit der aktuellen beta, dass das iFrame neu geladen wird trotz aktivierter Option `Aufrechterhalten`?

**Comment by Zefau** [comment]
Wie sind denn deine iFrame Einstellungen? Bei mir lädt er nicht neu. Hast du Aufrechterhaltung aktiviert?

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/e2046ec0-5d18-4a2f-b07b-e56d79d7ff81)

`https://radar.wo-cloud.com/desktop/rr/compact?wrx=53.267,10.050&wrm=7&wry=53.267,10.050`

Schwierig zu erkennen, ob es noch ein Neuladen ist.
Gestern hat er es noch anders geladen als heute.

**Comment by Zefau** [comment]
xhr ist ein asynchroner Request. Das ist wahrscheinlich die Art der Website sich selbst mit aktuellen Daten zu versorgen. Quasi eine Alternative zum Socket.

Hast du noch ein statisches Beispiel? Ansonsten scheint es behoben du sein.

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/1a63ba8f-1a48-4d62-86f3-7aec3613548c)
![image](https://github.com/user-attachments/assets/1ec04699-3d98-4e19-a9be-75932051d8b3)
![image](https://github.com/user-attachments/assets/684cd3e4-5535-48f0-aeb0-03c36fd81662)
Verbindung dauert lange (VIS1)

**Comment by Zefau** [comment]
Das ist ein vis Fehler, kein jarvis Fehler, siehe https://github.com/ioBroker/ioBroker.web/issues/20.

Ich mach hier mal zu.
