### ISSUE TITLE
[v3.2.0-alpha.42] Designfehler bei DateTime Modul

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2538]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a9d85e83-82c4-470d-8378-3504408e0195)

**Comment by Zefau** [comment]
Das Format von Datum und Uhrzeit ist mehrzeilig. Ist kein Design-Fehler. Allerdings ist die Übersetzung inkorrekt.

**Comment by mcuiobroker** [comment]
Aber muss die Linie denn soweit unten sein?
Normalerweise hat man die Linie unter der Eingabe?

**Comment by Zefau** [comment]
Ist Absicht, damit der Benutzer versteht, dass die Eingabe mehrzeilig ist.

**Comment by mcuiobroker** [comment]
Würde da nicht ne Info reichen?
Und hab noch keinen Fall gesehen, wo einer ein mehrzeiliges Datum oder mehrzeilige Zeit einsetzt.
Hast du das schon genutzt?

**Comment by Zefau** [comment]
Ne, aber sei dir sicher, es ist da drin, weil jemand danach gefragt hat. Darauf komme ich nicht von selbst ;-)

**Comment by mcuiobroker** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3ddd3d6b-8c4f-4f1b-8f6c-7eb7eaafc54e)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a4d15e77-4938-4ce6-ae49-f648f8616110)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a8fe77ae-d5e8-408a-86c3-b94dc56052ee)

Müsste das so nicht im Widget sein?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.6` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.6` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Ok. Passt. Danke.
