### ISSUE TITLE
[v3.2.0-alpha.43] Löschvorgang Widgets unterschiedliche Kennung?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2540]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8cb94682-08c2-4560-8282-efc8758b6405)
Beide Widgets wurden als gelöscht markiert werden aber unterschiedlich angezeigt?
Mal mit rotem Background, mal ohne.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.44` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.44` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
