### ISSUE TITLE
[v3.2.0-alpha.43] Jarvis lädt nicht in einem "In Privat" Fenster

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2542]
Ich nutze den In Privat Modus immer um in einer sauberen Umgebung ohne Cache, Cookies oder anderes zu testen. In dieser Version lädt er dort nicht mehr die Seite. Folgende Fehler im Browser Log
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/e45c0aca-454e-498a-b687-a245e0bde869)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.44` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.44` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
sie lädt wieder aber jetzt wieder mit dem darkmode Problem
