### ISSUE TITLE
Auswahl Widgets wird nicht gespeichert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2543]
Sollte auch so wie bei den Geräten sein.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/92cf6e4d-264f-4a4c-805d-53a7969ebf90)
Man muss es immer wieder auf alle umstellen.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.44` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.44`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Leider nein. Wird nicht gespeichert.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.45` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.45`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt.Danke.
