### ISSUE TITLE
[v3.2.0-alpha.43] Jarvis lädt mobil nicht.

### ISSUE THREAD

**Issue by mpl1337** [Zefau/ioBroker.jarvis#2544]
Android 13 mit aktuellstem Chrome Browser lädt nur eine graue Seite.

Welche Daten kann ich wo abrufen und bereitstellen?

**Comment by mcuiobroker** [comment]
Cache vom Browser gelöscht?

**Comment by mpl1337** [comment]
jop

**Comment by mcuiobroker** [comment]
Web Adapter neu gestartet

``` 
iob upload jarvis 
```
Auf der console

**Comment by mpl1337** [comment]
Wie kann ich "F12" unter Android Chrome ausführen?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2550

**Comment by Zefau** [comment]
Mit `v3.2.0-alpha.46` könnt ihr die Meldungen im ioBroker.Log anzeigen lassen. Seht ihr dann mehr?

**Comment by mpl1337** [comment]
Mit der 46 funktioniert wieder alles.

Danke 🦸
