### ISSUE TITLE
[v3.2.0--alpha.xx] Laden der ersten Seite verhindern

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2545]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/2539

<div type='discussions-op-text'>

<sup>Originally posted by **mcuiobroker** January 19, 2024</sup>
Kann man das Laden der ersten Seite verhindern, wenn man eine andere im hash ausgewählt hat?
Evtl display der Seite erst dann einschalten, wenn gewünschte Seite vorhanden?</div>

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.46` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.46` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
