### ISSUE TITLE
[v3.2.0-alpha.44] Konfiguration F12 Fehler

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2546]
Bei jarvis Konfiguration kommt folgender Fehler bei den Geräten und beim Versuch Styles oder Scripts ein oder aus zu schalten:

![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/ed0d9b34-8b28-46af-be6d-49d553f29adb)
![2](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/84e6f7cf-33dd-4f22-b0eb-c24dbe4deae7)
![3](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/094e5a6a-ce7d-4740-bc77-865eaa361a58)

**Comment by Bernd9000** [comment]
Hinweis:
Ist seit Version v3.2.0-alpha.43

**Comment by intruder7777** [comment]
bei mir ähnlich wenn ich in die Einstellungen gehe.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/5cab42d7-605c-41fc-b92a-23b48005c03f)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.45` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.45` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Fehler ist beseitigt mit v3.2.0-alpha.46.
Merkwürdig war das die "Styles"auf einmal verschwunden waren.
Ich hab dann eine Kopie neu eingefügt und gespeichert.
Wie sieht es bei Dir aus @intruder7777 ?

**Comment by intruder7777** [comment]
bei mir war noch alles da... aktuell auch keine Fehler

**Comment by Bernd9000** [comment]
Okay, dann mach ich hier dicht
