### ISSUE TITLE
[v3.2.0-alpha.44] und wieder Darkmode

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2548]
Darkmode lässt sich wieder nicht aktivieren. Im inPrivat Fenster lädt er ohne und in den Einstellungen ist er deaktiviert. . Lässt sich umlegen, speichert aber nicht und aktiviert auch nicht

Fehler im Moment des Umlegens
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/47b65def-778c-4d5e-a3a5-a50d865efa84)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.45` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.45` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
Er speichert jetzt zwar, aktiviert ihn aber nach Speichern + zurück nicht vernünftig. also die visu ist im darkmode aber gehe ich auf konfiguration ist das layout noch weiß. erst nach einem reload der Seite ist auch die Konfiguration im darkmode.

**Comment by Zefau** [comment]
sorry, irgendwie ist der Wurm drin.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.46` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.46` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
aktuell gehts
