### ISSUE TITLE
[v3.2.0-alpha.44] - Config - Layout gibt leere Seite aus

### ISSUE THREAD

**Issue by StephanTexxpro** [Zefau/ioBroker.jarvis#2549]
Der Aufruf der Seite 'Config - Layout' führt zu einer leeren Seite. Sowohl unter FF, Chrome als auch Edge. Jeweils im privaten Modus getestet.

Der Code wird bis hierher gerendered:

![2024-01-20 13_16_40-view-source_https__--- cc_#_configuration_layout](https://github.com/Zefau/ioBroker.jarvis/assets/25078059/02391b41-4a7c-4f52-a14c-6d262d7c7b56)

Die Konsole zeigt Folgendes:

![2024-01-20 13_16_12-jarvis - just another remarkable vis](https://github.com/Zefau/ioBroker.jarvis/assets/25078059/c5ac4296-b2d1-44d2-a1ae-721c0968f0b7)

Danke für jegliche Hilfe, Stephan

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.45` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.45` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by StephanTexxpro** [comment]
Läuft wider - vielen Dank!
