### ISSUE TITLE
[v3.2.0-alpha.46} IFrame überdeckt auf Handy die nachfolgende StateList

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2551]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/f9ff2f78-eb63-4aac-b9b7-df58954a6481)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/154d3a28-7928-4f7a-8799-c3a341720e59)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/edae38fa-a88d-43fd-9dd2-0cabdc60c5c6)

**Comment by Zefau** [comment]
[Ist ein ](https://github.com/Zefau/ioBroker.jarvis/issues/977)
