### ISSUE TITLE
[v3.2.0-alpha.47] Zu wenig Platz unten auf der Seite für Paypal

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2552]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/93e94611-f8a0-4a13-aa13-14e3fe1d9b96)

**Comment by Zefau** [comment]
Kannst du mal die Elemente `q-page-container` bzw. `jarvis-configuration` prüfen? Da sollte eigl. `padding-bottom: 52px;"` drauf sein, das das verhindert.

**Comment by mcuiobroker** [comment]
Keine Ahnung was das los war, aber jetzt ist es wieder ok?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/486af61f-1db4-425b-bd7b-73ce7e0ea82d)
