### ISSUE TITLE
Info zu den Geräte Parametern

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2554]
Aliases, Geschoss, Raum, Tags

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/52638b0b-4e59-4652-8091-21551351e2f4)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/bd983b05-d491-465f-86ff-abe2ad746684)

Wo kann man sie nutzen?
Wie müssen Aliase getrennt werden? Wo kann man diese Aliases nutzen? Bei der Suche..., StateList Dynamische Liste

**Comment by Zefau** [comment]
Geschoss, Raum, Gewerk und Tags finden in der neuen dynamischen StateList Liste Anwendung (siehe https://github.com/Zefau/ioBroker.jarvis/issues/2480). Auf Basis dessen können die Geräte dynamisch geladen werden - also wenn ein Gerät hingezufügt wird muss die StateList nicht mehr bearbeitet werden.

**Comment by mcuiobroker** [comment]
Ich meinte als kleine Infosymbole eine Erklärung dazu schreiben.

**Comment by Zefau** [comment]
Der Alias wird bei der Aktivierung für den Cloud-Adapter verwendet. jarvis meldet im Cloud-Adapter das Gerät dann mit dem Label und den Aliases an. Über die Aliases können mehrere Geräte mit derselben Bezeichnung gruppiert werden. In meinem Fall `Licht Kücheninsel` und `Licht Küche Fenster` als `Licht Küche` (also `Licht Küche` bei beiden als Alias). Dann kann ich via Alexa die 2 Geräte jeweils getrennt steuern oder auch zusammen.

**Comment by mcuiobroker** [comment]
Für Geschoss wäre "Etage" evtl. besser?

**Comment by Zefau** [comment]
Jo, IoT-Adapter meinte ich.

**Comment by Zefau** [comment]
Vorschlag für die Hilfetexte:
- `Label`: Das Label dient der alternativen Bezeichnung des Geräts und wird im Frontend statt des Namens genutzt. Der Name dient zur Identifizierung im Backend.
- `Aliases`: Die Aliases werden von jarvis bei der Registrierung des Geräts im IoT-Adapter (und damit in Alexa) genutzt, sofern vom Benutzer ausgewählt (siehe Optionen im Datenpunkt). Mit dem Aliases können verschiedene Geräte gruppiert werden (z.B. die Geräte "Licht Küchenzeile" und "Licht Esstisch" erhalten beide jeweils den Alias "Licht Küche").
- `Tags`: Die Tags können genutzt werden, um Geräte zu verschlagworten und danach schnell suchen zu können.

Etage, Raum und Gewerk sind selbsterklärend, oder?

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.13` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.13`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
