### ISSUE TITLE
[v3.2.0-alpha.49] Styles werden auf dem Handy nicht angewendet

### ISSUE THREAD

**Issue by hosabeni** [Zefau/ioBroker.jarvis#2555]
Weder beim Chrome noch beim Firefox werden auf dem Handy die Styles angewendet. 
In Desktop Browser sieht es gut aus.

**Comment by mcuiobroker** [comment]
Cache gelöscht?

**Comment by hosabeni** [comment]
Ja, Cache hab ich gelöscht. Auch im Privat Modus werden die Styles nicht angewendet.

**Comment by mcuiobroker** [comment]
Manchmal bleibt irgendwo was hängen. Versuch mal mit auf der console.
```
iob upload jarvis
```
und evtl Web-Adapter neu starten?
Mehr fällt mir nicht ein.

**Comment by Zefau** [comment]
Was für Styles genau? Die allgemeinen jarvis Styles oder "nur" die von dir definierten Styles (via Pro)? Via jarvis Android-App oder Browser/Web? Safari, Chrome, Firefox? Welche Android-/iOS-Version bzw. welche WebView-Version?

**Comment by hosabeni** [comment]
Das Problem bestand in den Pro Styles. Ich habe da eben eine Änderungen (Farbe angepasst) gemacht, gespeichert und jetzt geht es auch auf dem Handy. 
Brauchte wohl nur einen kleinen anschubser.
