### ISSUE TITLE
[v3.2.0-alpha.49] Kalender Eintrag kann nicht geändert werden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2560]
Es steht ein Verbotszeichen über dem Link.
Den Link gibt es nicht mehr und ist nicht erreichbaar.

Aber man sollte ihn ändern können?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e63a9533-5e69-46a4-8198-fcb4b016360c)

Haut auch das Log voll
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/97fb1268-252e-43a8-8611-a9fc19948b45)

**Comment by Zefau** [comment]
Muss neu hinzugefügt werden. Die URL wird intern als ID genutzt, daher kann diese nach dem erstmaligen Hinzufügen nicht mehr geändert werden.

**Comment by mcuiobroker** [comment]
Ok.
