### ISSUE TITLE
JSON.parse(val) in Datenpunkt Stil

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2563]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/2562

<div type='discussions-op-text'>

<sup>Originally posted by **hosabeni** January 21, 2024</sup>
Sollte `{"JSON.parse(val).Battery < 30":{"color":"LightCoral"}}` im Datenpunkt Stil funktionieren oder muss ich das anders machen?
Version: v3.2.0-alpha.49

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/77939385/5496199c-cd02-41ff-957b-b1ee14b282b9)

</div>

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.50` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.50` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Funktioniert bei mir.
