### ISSUE TITLE
Nach Update leere Styles in der Konfiguraiton

### ISSUE THREAD

**Issue by sammie76-2** [Zefau/ioBroker.jarvis#2567]
![2024-01-22_20h20_04](https://github.com/Zefau/ioBroker.jarvis/assets/73701785/0b412804-3b0a-4395-93f2-2f0b8410a721)
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [3.2.0 alpha 50] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
Nach dem Update auf 3.2.0 alpha 49 und danach noch auf 50. Bleibt der Reiter Styles in der Jarvis Konfigration leer. Die alten Styles werden aber teilweise zumindest noch angewendet. In den Objekten des iobrokers stehen sie auch noch drin.
![2024-01-22_20h04_05](https://github.com/Zefau/ioBroker.jarvis/assets/73701785/ca6d06b8-d8bf-4b0b-8fea-50752cc7a508)

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![2024-01-22_21h06_20](https://github.com/Zefau/ioBroker.jarvis/assets/73701785/fba72aa8-ffb3-4dcd-93b2-2346c64da4c1)
[jarvis.0.css.txt](https://github.com/Zefau/ioBroker.jarvis/files/14014923/jarvis.0.css.txt)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by mcuiobroker** [comment]
Könnte mit dem Key zusammenhängen?
War anscheinend irgendwann `css`und jetzt `styles`.

**Comment by Zefau** [comment]
Jo, beim Konvertieren wird `css` eingetragen und `styles` ist aber richtig. Beim Speichern der Konfiguration wird bereits `styles` verwendet.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.54` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.54` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
CSS wird nicht mehr geladen bzw ausgeführt. Auf Mobile Browsern Edge, Fully, Chrome. 
Wenn man die Browserdaten gelöscht hat sind die CSS-Daten weg? Sie werden nicht nachgeladen?

**Comment by Zefau** [comment]
Du meinst, es wird initial geladen und korrekt angezeigt, aber bei Änderungen in der Konfiguration nicht aktualisiert?

**Comment by mcuiobroker** [comment]
Also wenn ich die Browserdaten lösche werden keine Css Daten geladen.  Erst wenn man die Signature ändert.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.55` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.55` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
