### ISSUE TITLE
[v3.2.0-alpha.50] Ausblenden von CSS-Code durch /* */ führte zum Löschen von CSS-Style Einträgen ab der */ Stelle

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2569]
Rest der CSS wurde komplett gelöscht
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/798d37c4-924d-4685-89bc-a236377b29ce)

**Comment by Zefau** [comment]
Bekommst du das wiederholt / nachgestellt? Bei mir tritt der Fehler - zumindest aufgrund der geschachtelten Kommentare - nicht auf.

**Comment by mcuiobroker** [comment]
Soweit ich mich erinnere war ich da schon auf der "neuen" Version und habe dann einen "Block" ausblenden /inaktiv setzen wollen.
Dann habe ich gespeichert und der Rest von CSS war weg.

**Comment by mcuiobroker** [comment]
Ich schließe dies erstmal.
