### ISSUE TITLE
Update Material Design Icons to v5.8.55

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#257]
ebenso sofa-single und sofa-single-outline
das normale sofa geht

**Comment by Zefau** [comment]
Sicher, dass die existieren? Auf https://cdn.materialdesignicons.com/5.4.55/ finde ich die nicht.

**Comment by Timmes123** [comment]
in deiner wiki hast du geschreiben

`beliebiges Icon von https://materialdesignicons.com/`

**Comment by Timmes123** [comment]
Ah ich hab des rätsels lösung :-) 
auf github gibts bereits v5.8.55

du verwendest noch die 5.4.55

**Comment by Zefau** [comment]
Meinen Link? Welchen Link? Mein Link in diesem Issue zeigt auf 5.4.55.

**Comment by Timmes123** [comment]
ja natürlich das meinte ich ja
dein link zeigt auf 5.4.55, das steht aber in deiner wiki nicht drin. da verweist du auf https://materialdesignicons.com/ welches etwas aktueller ist

wenn ich allerdings in https://cdn.materialdesignicons.com/5.8.55/ schaue, was laut github das aktuelle ist,
dann werden auch die icons gezeigt, welche dir in 5.4.55 fehlen

**Comment by Zefau** [comment]
Ok, in `v1.1.0-beta.54` nun auf 5.8.55 aktualisiert.

**Comment by Timmes123** [comment]
getestet, funkioniert :-)
