### ISSUE TITLE
Pro Lizenz wird in zweiter Jarvis Instanz nicht übernommen

### ISSUE THREAD

**Issue by djalexz** [Zefau/ioBroker.jarvis#2570]
Hallo Zefau,

ich weiß nicht genau seit welcher Version, da ich immer die neuesten Alphas installiere.
Aktuell läuft die `v3.2.0-alpha.45`

Hier ist mir aufgefallen, dass meine Pro Lizenz in einer zweiten Jarvis Instanz nicht übernommen wird.
Die Datenpunkte für Pro sind in beiden Instanzen identisch gefüllt.

Bild von der zweiten Jarvis Instanz:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/11389551/cebfb8a6-33cf-45b1-8fac-ce3be3788f32)

Anscheinend wird die Lizenz laut Konsole geladen, aber als Invalid angezeigt:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/11389551/330f85c2-c95b-4119-96f3-ff950fabf69c)

Das Object beinhaltet die Lizenz mit den korrekten Daten.

LG Alex

**Comment by mcuiobroker** [comment]
Bei mir auch so
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/7c52ed08-6e1d-465e-8ff6-c86b32bbccea)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.52` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.52` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Pro Lizenz wird nicht übernommen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.55` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.55` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Pro Lizenz wird nicht in den PRO-DP gesetzt, aber es wird die Lizenz erkannt.
Soll das so?

**Comment by djalexz** [comment]
Leider mit der `v3.2.0-alpha.55` als auch mit der letzten `v3.2.0-alpha.56` wird die Pro Lizenz bei der zweiten Instanz nicht erkannt.

**Comment by Zefau** [comment]
Jede Instanz größer 0 versucht `jarvis.X.info.pro` zu lesen. Sofern das leer ist, wird `jarvis.0.info.pro` genutzt.

**Comment by djalexz** [comment]
Jawohl, gerade gesendet

**Comment by Zefau** [comment]
> Jawohl, gerade gesendet

Funktioniert bei mir. Hab die Lizenz in `jarvis.2.info.pro` gesetzt und `jarvis.0.info.pro` leer gelassen. Bekomme in der Browser-Konsole die Meldung `Pro Valid Pro User: A*** Z***`

Ggf. musst du den Cache löschen? Also im Firefox via F12 unter "Web-Speicher" --> "Local Storage" bzw. im Chrome via F12 unter "Application" --> "Local Storage" den Eintrag der auf `.pro` endet.

**Comment by djalexz** [comment]
Ja alles klar.
Ich trottel, hab natürlich nicht den Application Cache der Seite gelöscht.
Es funktioniert tadellos.
Danke dir.

In der `v3.2.0-alpha.45` war wohl trotzdem ein Fehler drin, da es auch nach dem Löschen des Application Caches nicht funktioniert hatte. 😜
