### ISSUE TITLE
[v3.2.0-alpha.51] Geräte-DP löschen löscht das ganze Gerät

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2571]
![jarvis v320-alpha51 gereäteDP löschen löscht das Gerät](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/2a621b85-b15e-4068-afad-9047b52c47e0)

**Comment by Zefau** [comment]
Das Gerät wird nicht gelöscht, sondern deine Suche filtert das Gerät nicht mehr, weil du den Eintrag der bei deiner Suche / Filterung zum Treffer führt löschst.

**Comment by mcuiobroker** [comment]
Sorry, hab ich nicht gesehen.
