### ISSUE TITLE
[v3.2.0-alpha.53] Layout - Tab Vollbild Problem

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2574]
Man befindet sich im Layout.
Eine jarvis Seite besteht aus mehren Tabs.
Ein widget in einem Tab soll als Vollbild dargestellt werden.
Dazu wird der betreffende Schalter `Tab Vollbild` eingeschaltet.
Die Seite aktualisiert sich.

Fehler:
Gehe ich jetzt wieder zur selben jarvis Seite im Layout aber in einem  **anderen TAB** (nicht das mit dem Vollbild) werden hier die Widgets extrem schmal angezeigt bzw. es wird nur ein Widget von mehren angezeigt.

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/150bb836-0758-479d-be9e-95d8435c1cfe)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.55` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.55` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Kann ich noch nicht testen da jetzt das Layout in `v3.2.0-alpha.55` fehlt

**Comment by Zefau** [comment]
?

**Comment by Bernd9000** [comment]
[#2576](https://github.com/Zefau/ioBroker.jarvis/issues/2576)

**Comment by Bernd9000** [comment]
Okay, getestet, funktioniert
