### ISSUE TITLE
[v3.2.0-alpha.54]  kein Bearbeiten der widgets mehr möglich

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2576]
In der Runtime auf den ersten Blick keine Probleme. Aber im Editor sind offensichtlich keine Widgets mehr da zum Bearbeiten.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/bc2da446-8e85-4298-a619-e19c1781a674)

**Comment by intruder7777** [comment]
Anmerkung und strange.... ich habe unter iFrame mehr als 15 Widgets. Wenn ich dort also weiterblätter um die anderen Widgets anzuzeigen, dann versucht er bei allen anderen auch auf der 2. Seite welche zu finden. u d da ich dort nicht mehr als 15 habe, findet er auch keine. das sollte wohl so nicht sein.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/45670139/8aa7ec24-de10-4d77-beb3-c7612d1224d0)

**Comment by Bernd9000** [comment]
Jo, hab ich auch.
Geräte und Layout sind i.O.
Aber widgets werden nicht akzeptiert.
Kopiert man über `Expert Mode` eine Sicherheitskopie hinein, wird das auch nicht akzeptiert und wieder gelöscht.
Im IOB Datenpunkt `widgets` sind die Daten aber noch vorhanden.


![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/d3f98464-fb98-4dc1-acc6-5922e62e0999)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.55` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.55` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Von `v3.1.9-beta.2` nach `v3.2.0-alpha.55`
Bei mir sind jetzt die widgets wieder vorhanden.

Aber.....
Jetzt passiert der selbe Fehler mit dem `Layout`

Im Layout ist nur das standart Dashboard vorhanden.
Im IOB Datenpunkt layout ist die alte Version noch vorhanden.

**Comment by intruder7777** [comment]
@Bernd9000 Layout keine Probleme. Versuche mal die Browserdaten zu löschen. 
@Zefau Mein Problem von oben mit den Seiten im Widget Bereich ist mit der 55 gelöst.

**Comment by Bernd9000** [comment]
Wie bei jedem Versuch: Browser Cache gelöscht, IOB Upload jarvis, IOB Neustart, keine Änderung
Also nochmal von `v3.1.9-beta.2` nach `v3.2.0-alpha.55`
Durch Zufall hab ich dann mal wieder den Socket Port 8400 benutzt.
Und siehe da, alles wieder da.......????????
Nochmal mit web Port versucht, diesmal fehlen die Geräte.

Zur gleichen Zeit zeigt mir der Webport und der Socket Port unterschiedliche Einstellungen an.
Webport: Geräteliste (0)
Socketport: Geräteliste (145)
Kann mir das jemand erklären ?

Dann kann das hier wohl dicht.

**Comment by Bernd9000** [comment]
Falls das hier jemand noch liest.
Ich mußte bei allen Browsern nicht nur den `cache` sondern auch die  **`cookies`** löschen.
Seit dem funktionierte es wieder sowohl über den Web Port als auch mit dem Socket Port.
