### ISSUE TITLE
[v3.2.0-alpha.56] Doppelte Anzeige Gewerk bei Gerät hinzufügen für HistoryGraph

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2578]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e92e2076-078d-41a3-a9b9-6afd53863c1d)
In den identischen Gewerken sind aber unterschiedliche Geräte.

**Comment by Zefau** [comment]
Kann ich bestätigen. In der Geräte-Übersicht sieht man wieso: `_defaults` und `other`. Ich kümmer mich drum.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.57` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.57` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
