### ISSUE TITLE
[v3.2.0-alpha.56] Bei automatischem Reload plötzlich Anzeige von 2. Instanz und nicht der ausgewählten 1.

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2579]
home gibt es in der 2. Instanz nicht
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/bfef5552-cd8e-4e5f-8226-0e847943ef4e)
Auch ein Reload hat nicht geholfen. Da sollte er ja eigentlich erkennen, das home0 von der 1. Instanz ist, oder?

**Comment by Zefau** [comment]
Welcher automatische Reload ist das? Der aufgrund geänderter Skripts?

**Comment by Zefau** [comment]
>  Auch ein Reload hat nicht geholfen. Da sollte er ja eigentlich erkennen, das home0 von der 1. Instanz ist, oder?

Nein, das wird nicht erkannt und auch gar nicht ermittelt.

jarvis speichert die zuletzt genutzte Instanz ab und ruft dann immer die ab.

**Comment by mcuiobroker** [comment]
Automatischer Reload nachts um 03:00 Uhr z.B.
Ich hatte beide Instanzen auf, die 2. geschlossen, dann kam der Reload für die 1. und er holte sich die Daten von der 2.
Ich kam auch dann nur noch mit Start aus der Instanz-Übersicht wieder in die 1.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Aufruf 2.Instanz aus Instanz-Übersicht öffnet die 1.Instanz.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.1` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.1` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Jetz geht nix mehr
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/89ff2eac-3a0e-49a6-8a9f-4f73dae09d05)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/f555d742-5bb2-42a6-a018-8ff4b14f82a2)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.3` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.3` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
sieht gut aus. Danke.
