### ISSUE TITLE
[v3.2.0-alpha.56] DisplayImage wird nicht angezeigt CORS, obwohl `http://`

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2580]
`v3.1.8`
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a58b1486-feea-40c7-918a-d425af2aed06)
`v3.2.0-alpha.56`
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8a0adaf6-9e24-417b-af17-e78ba742d8d3)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9fe1bbec-0f6f-4ebc-b449-180ba4f1225c)

**Comment by Zefau** [comment]
Vermutlich wegen https://github.com/Zefau/ioBroker.jarvis/issues/2415

Tritt der Fehler bei `v3.2.0-alpha.42` bzw. davor auch auf?

**Comment by mcuiobroker** [comment]
Auch mit v3.20.-alpha.41 wird der Fehler angezeigt.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/60a1b137-bc10-4c6b-8028-d4e534180ed1)

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.57` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.57` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Weiterhin der Fehler
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/deb66da3-c11f-45da-927b-dd34db410fb5)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2415

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Ist wieder zu sehen. Danke.
