### ISSUE TITLE
[v3.2.0-alpha.56] MAP kann nicht angelegt werden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2581]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/28dbb40a-a1f1-4fb8-b728-f45cb999d711)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/4a7ad990-d950-4388-bb99-5e84750db402)

`Bei vorhandenen MAPs` -> hover map-marker

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/cc07f3df-4b36-4024-8386-82a2f444e688)

**Comment by Zefau** [comment]
Kannst du mal die JSON Rohdaten dazu schicken?

**Comment by mcuiobroker** [comment]
MAPOLD
```
"37c08a61-d062-485b-995e-e35c714eb3e4": {
    "id": "37c08a61-d062-485b-995e-e35c714eb3e4",
    "config": {
      "defaultPosition": "50.55,13.050049999999999",
      "defaultZoom": 8,
      "height": "400",
      "tooltipPermanent": true
    },
    "icon": "mdi:home",
    "title": "mapOld",
    "module": "Map",
    "items": [
      {
        "type": "device",
        "deviceId": "3310f5a1-2771-4796-8fcb-de513f3a6b3f",
        "primaryStateKey": "position",
        "id": "29a805a7-f47a-4b55-a14b-6723e8bcc4b1",
        "bodyStateKey": "position",
        "bodyElement": "LastChangeBody"
      },
      {
        "type": "device",
        "deviceId": "a4799e04-69c8-4de3-bfa5-2e43f8d253d0",
        "primaryStateKey": "position",
        "id": "1264c83d-e65c-4bb5-90ba-8e8b924a2573",
        "bodyStateKey": "position",
        "bodyElement": "LastChangeBody"
      }
    ],
    "hideTitle": false,
    "hideSeparator": true,
    "revision": "9f50c"
  },
```

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.57` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.57` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Beim hover über maparker
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9e120db9-ad6e-4f34-812c-af9b409cb51a)

**Comment by mcuiobroker** [comment]
Neu angelegte MAP
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c8eba287-3d79-4c03-9783-bcb9a3df1c49)
```
"5be84b48-bc12-457a-b9a6-bb85bf813020": {
    "id": "5be84b48-bc12-457a-b9a6-bb85bf813020",
    "config": {
      "defaultZoom": 10,
      "rotation": 0,
      "defaultPosition": "53.0,10.0",
      "followDevice": null,
      "tooltipPermanent": true
    },
    "_created": 1706566386727,
    "title": "Map Neu",
    "module": "Map",
    "revision": "efb1d",
    "items": [],
    "_updated": 1706569654968
  }
```

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.59` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.59` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt.Danke.
