### ISSUE TITLE
[v3.2.0-alpha.57] Layout wird nicht gespeichert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2583]
Layout Änderung
Widget hinzugefügt -> MAP
Speichern und zurück
-> Frontend kein Widget mehr
Weder mit `Speichern` noch mit `Speichern und Zurück`

**Comment by Bernd9000** [comment]
Hab es hier mal versucht, neue Map erstellt, nur Koordinaten eingetragen, funktioniert.
Hast Du eine Map aus einer "alten" Version genommen oder neu angelegt ?
cache und cookies vom Browser mal gelöscht ?

**Comment by mcuiobroker** [comment]
cache und cookies gelöscht.
-> Jetzt zeigt er das Widget an, welches er nicht gespeichert hatte?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e16c205e-f335-4b0b-92b8-20a2a518551c)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5f3d7371-a37b-404b-9dfa-ea4e34401fbf)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/eeee2fa1-c53f-40ad-a537-1155217be7cf)

**Comment by mcuiobroker** [comment]
Speicherungsproblem scheint damit (Cache und Cookies löschen) behoben zu sein.
@Bernd9000  Danke.
