### ISSUE TITLE
v3.1.8 Geräte importer Homatic

### ISSUE THREAD

**Issue by detafun** [Zefau/ioBroker.jarvis#2586]
Noch was, ich habe 3 neue Homatic IP Thermostatet an der ccu3 in Betrieb genommen. Wollte diese jetzt ins Jarvis mit Scannen. Geht nicht, besser findet Sie aber siehe Screen.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/44980055/9f6983bd-c5e6-478c-a497-b4a80852a9c7)

Es geht hier um Heizung Emilia, Inga und Lilly. Die anderen Thermostate sind damals bei der Erstinstall autoatisch installiert mit worden. Die neuen im Scan will er nicht.

**Comment by Zefau** [comment]
Welche Datenpunkte willst du aus ioBroker in jarvis übernommen haben? Genügt dir die folgende Aufstellung?

```
{
			"temperature": {
				"state": ".1.ACTUAL_TEMPERATURE"
			},
			"setTemperature": {
				"state": ".1.SET_POINT_TEMPERATURE",
				"action": ".1.SET_POINT_TEMPERATURE"
			},
			"frost": {
				"state": ".1.FROST_PROTECTION"
			},
			"boost": {
				"state": ".1.BOOST_MODE",
				"action": ".1.BOOST_MODE"
			},
			"boostTime": {
				"state": ".1.BOOST_TIME",
				"action": ".1.BOOST_TIME"
			},
			"windowState": {
				"state": ".1.WINDOW_STATE"
			},
			"partyMode": {
				"state": ".1.PARTY_MODE",
				"action": ".1.PARTY_MODE"
			}
		},
```

**Comment by detafun** [comment]
Ja das langt doch, wie bei den anderen auch

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.1` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.1`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by detafun** [comment]
Kann ich leider noch nicht sagen. da ich noch auf 3.1.8 bin. Sobald die Ach jetzt Beta , das ist gut, dann werde ich es dir sagen ob es geht. Ist die Beta soweit stabil, das man Sie einsetzen kann?

**Comment by Zefau** [comment]
Beta 1 bitte nicht probieren.

**Comment by Zefau** [comment]
@detafun probiere mal mit der beta-5 bitte

**Comment by detafun** [comment]
Hab mal auf beta-5 aktualliersiert. Sieht nun so aus.
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/44980055/f64895c3-c3fe-4705-9714-f5035135af41)

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.6` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.6`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by detafun** [comment]
Moin, gerade Probiert.
geht leider immer noch nicht.
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/44980055/4581d1ef-9b7d-4039-b199-a9eab4975833)

**Comment by Zefau** [comment]
Kannst du bitte in ioBroker im Objekt schauen wie dort die genaue Bezeichnung des Geräts ist? Glaube da ist ein Missmatch.

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/1c43f4a6-393b-4b3f-aa64-f0c443e47005)

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/07d0cebf-6261-414e-a6a6-45a22334a46d)

**Comment by detafun** [comment]
Das kommt raus:
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/44980055/035f7496-c462-4b75-9f82-2aa529e0fcda)

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.10` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.10`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by detafun** [comment]
Yes Beta 10 werden alle Datenpunkte richtig angezeigt. Danke
