### ISSUE TITLE
[v3.2.0-alpha.59] Meldung Incorrect Binding warum?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2587]
```
{
  "200": "mdi:lightbulb-group",
  "({hue-extended.0.lights.008-schreibtisch_unten.action.on}=false || {wifilight.0.192_168_178_62.on}=false) && {val}=0": "mdi:led-strip-variant",
  "({wifilight.0.192_168_178_62.on}=false || {hue-extended.0.lights.008-schreibtisch_unten.action.on}=false) && {val}=100": "mdi:lamps-outline",
  "{hue-extended.0.lights.008-schreibtisch_unten.action.on}=true  &&  {wifilight.0.192_168_178_62.on}=true": "mdi:lightbulb-group"
}
```
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/bdf1cf2d-e6c4-46e8-82da-108ab45bfa05)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a1a7f8c3-3ca1-4acf-b03f-a32a7ed4efd5)

**Comment by Bernd9000** [comment]
Ging das überhaupt mit Mehrfach Fremddatenpunkten ?
Bisher hatten wir doch immer ein Operationsvergleich mit **einem** Fremddatenpunkt und e**i**nem state Wert.

**Comment by mcuiobroker** [comment]
Ja das ging mit mehreren unterschiedlichen DPs.

**Comment by Bernd9000** [comment]
Okay, hab das auch mal nachgestellt mit den selben Datenpunten, kriege die selben Fehler.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.1` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.1` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Keine Meldungen mehr. Danke.
