### ISSUE TITLE
Bei Version Alpha 59 Kein Speichern der Styles möglich

### ISSUE THREAD

**Issue by teletapi** [Zefau/ioBroker.jarvis#2588]
Heute hab ich die Alpha 59 installiert und der Fehler mit dem Kalender aus Issue #2585 ist weg. Jetzt kann man sogar wieder die Termine aus den vergangenen Monaten und die nächsten Monate einsehen, das ist absolut Klasse, danke dafür.
Allerdings konnte ich jetzt die Styles nicht mehr speichern nach jedem Neustart von Jarvis sind die styles wieder weg.
LG

**Comment by mcuiobroker** [comment]
Was steht im DP `jarvis.0.css`?

**Comment by teletapi** [comment]
`"version": 3.2,
  "signature": 7983056520356523,
  "styles": "/*Michelle-Schlaf-und-Gaeste-Zimmer-Thermostat*/\n\n.jarvis-widget-18eb7734-aca7-4a85-8888-9cf311324f2b .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-18eb7734-aca7-4a85-8888-9cf311324f2b .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Schlafzimmer-Thermostat*/\n\n.jarvis-widget-50f32016-7a15-49ba-bedd-225ec8653c36 .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-50f32016-7a15-49ba-bedd-225ec8653c36 .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Wohn-und-Esszimmer-oben-Thermostat*/\n\n.jarvis-widget-b104a38e-e58b-4c15-bbe0-ee2da469e9cd .jarvis-StateListItem:nth-child(4) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-b104a38e-e58b-4c15-bbe0-ee2da469e9cd .jarvis-StateListItem:nth-child(4) .q-slider__track {\n\tcolor: transparent;\n}\n\n.jarvis-widget-b104a38e-e58b-4c15-bbe0-ee2da469e9cd .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-b104a38e-e58b-4c15-bbe0-ee2da469e9cd .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Wohnzimmer-Thermostat*/\n\n.jarvis-widget-4e1d0ea5-56ca-4d55-91a9-c6866df51c15 .jarvis-StateListItem:nth-child(14) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-4e1d0ea5-56ca-4d55-91a9-c6866df51c15 .jarvis-StateListItem:nth-child(14) .q-slider__track {\n\tcolor: transparent;\n}\n\n.jarvis-widget-4e1d0ea5-56ca-4d55-91a9-c6866df51c15 .jarvis-StateListItem:nth-child(11) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-4e1d0ea5-56ca-4d55-91a9-c6866df51c15 .jarvis-StateListItem:nth-child(11) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Wohnzimmer-Michelle-Thermostat*/\n\n.jarvis-widget-a8106082-167b-440d-aeb1-1f7910bb71c7 .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-a8106082-167b-440d-aeb1-1f7910bb71c7 .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Badezimmer-oben-Thermostat*/\n\n.jarvis-widget-27d20508-5288-4fdc-8012-c8603a7e7f3b .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-27d20508-5288-4fdc-8012-c8603a7e7f3b .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Buero-Thermostat*/\n\n.jarvis-widget-7ea433d7-fa50-4723-987e-c5b2b5138664 .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-7ea433d7-fa50-4723-987e-c5b2b5138664 .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Ankleidezimmer-Thermostat*/\n\n.jarvis-widget-3fb0f6ac-79d1-4949-b9c0-9fbfd1d86f0e .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-3fb0f6ac-79d1-4949-b9c0-9fbfd1d86f0e .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Badezimmer-unten-Thermostat*/\n\n.jarvis-widget-03bf6c62-3c99-4df2-bd15-bf0b26ec2d71 .jarvis-StateListItem:nth-child(5) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-03bf6c62-3c99-4df2-bd15-bf0b26ec2d71 .jarvis-StateListItem:nth-child(5) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Flur-Oben-Thermostat*/\n\n.jarvis-widget-81e44733-6665-46d7-b779-d4d0fe4de04c .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-81e44733-6665-46d7-b779-d4d0fe4de04c .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*GAESTE-WC-Thermostat*/\n\n.jarvis-widget-464cd68b-243b-45e5-b0e6-cf4aecb2f5f4 .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-464cd68b-243b-45e5-b0e6-cf4aecb2f5f4 .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/*Hausgarage-Thermostat*/\n\n.jarvis-widget-aa1e31e1-2cf1-4f85-a9fd-5870ac5aefd8 .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-aa1e31e1-2cf1-4f85-a9fd-5870ac5aefd8 .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n.jarvis-page-container {\n\tbackground-image: url(\"https://images.hdqwalls.com/download/3d-cgi-geometry-pattern-bo-3840x2160.jpg\");\n}\n\n.body--dark .jarvis-header {\n\tbackground-color: rgba(0,0,0,0.45) !important;\n}\n\n.jarvis-tabs-container {\n\tbackground-color: rgba(0,0,0,0.45) !important;\n}\n\n.jarvis-widget-container {\n\tbackground-color: rgba(0,0,0,0.45) !important;\n}\n\n.body--dark .jarvis-widget {\n\tbackground: rgba(0,0,0,0.45);\n}\n\n.body--light .jarvis-widget {\n\tbackground: rgba(255,255,255,1);\n}\n\n.body--dark .jarvis-tabs-container {\n\tbackground-color: rgba(0,0,0,0.45) !important;\n}\n\n/* für JsonTable ergänzt @mcu */\n\n.q-table__container {\n\tbackground-color: transparent !important;\n}\n\n/* für Trennstrich für TABs ergänzt @mcu */\n\n.q-header--bordered {\n\tborder: 1px solid transparent !important;\n}\n\n/* transparents Icon im Widget-Header @mcu */\n\n.jarvis-widget-icon {\n\tbackground: rgba(0,0,0,0.45);\n}\n\n/* MediaControl in transparentem Design @mcu */\n\n.cover {\n\tbackground-color: transparent !important;\n}\n\n.controls {\n\tbackground-color: transparent !important;\n}\n\n.track-information {\n\tbackground: rgba(25, 118, 210, 0) !important;\n}\n\n.track-duration {\n\tbackground-color: white;\n}\n\n.track-progress {\n\tbackground-color: blue;\n}\n\n.controls .jarvis-icon svg {\n\tcolor: white;\n}\n\n.controls .controlsLeft .q-btn__wrapper {\n\tbackground-color: transparent !important;\n}\n\n.controls .q-btn-group >.q-btn-item {\n\tbackground-color: transparent !important;\n}\n\n/* Bei JsonTable in Vergrößerung anderer Hintergrund nicht transparent @MCU */\n\n.fullscreen.scroll.jarvis-JsonTable.sticky-table-header {\n\tbackground-image: url(\"https://images.hdqwalls.com/download/black-gradient-b9-1920x1080.jpg\") !important;\n}\n\n.jarvis-sidebar {\n\tbackground-color: #8A2BE2;\n\tbackground-image: linear-gradient(315deg, #8A2BE2 0%, #00008B 74%);\n\t/* #661f64 old #380036*/\n}\n\n.jarvis-sidebar .items-center {\n\tbackground-color: #8A2BE2;\n\tbackground-image: linear-gradient(315deg, #8A2BE2 0%, #00008B 74%);\n\t/* #661f64 old #380036*/\n}\n\n[widgets=\"b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa\"] .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n[widgets=\"b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa\"] .q-slider__track {\n\tcolor: transparent;\n}\n\n/* ab v3.0.11 , mit v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .q-slider__track {\n\tcolor: transparent;\n}\n\n/* Bei mehreren Slidern im Widget, Einschänrkung auf das StateList-Element notwendig */\n\n[widgets=\"b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa\"] .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n[widgets=\"b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa\"] .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .jarvis-StateListItem:nth-child(2) .q-slider .q-slider__track {\n\tbackground: linear-gradient(to right, #000000 0%,  #ffffff 100%);\n\t/* height: 15px; */\n}\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .jarvis-StateListItem:nth-child(2) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .jarvis-StateListItem:nth-child(5) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .jarvis-StateListItem:nth-child(5) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .jarvis-StateListItem:nth-child(6) .q-slider .q-slider__track {\n\tbackground: linear-gradient(to right, #000000 0%,  #ffffff 100%);\n\t/* height: 15px; */\n}\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .jarvis-StateListItem:nth-child(6) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .jarvis-StateListItem:nth-child(11) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-b5f5d6dd-5320-4711-aa84-2f4dc50fcdfa .jarvis-StateListItem:nth-child(11) .q-slider__track {\n\tcolor: transparent;\n}\n\n[widgets=\"ee7d74b8-c08f-40f4-be86-0deebc0f0d50\"] .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n[widgets=\"ee7d74b8-c08f-40f4-be86-0deebc0f0d50\"] .q-slider__track {\n\tcolor: transparent;\n}\n\n/* ab v3.0.11 , mit v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-ee7d74b8-c08f-40f4-be86-0deebc0f0d50 .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-ee7d74b8-c08f-40f4-be86-0deebc0f0d50 .q-slider__track {\n\tcolor: transparent;\n}\n\n/* Bei mehreren Slidern im Widget, Einschänrkung auf das StateList-Element notwendig */\n\n[widgets=\"ee7d74b8-c08f-40f4-be86-0deebc0f0d50\"] .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n[widgets=\"ee7d74b8-c08f-40f4-be86-0deebc0f0d50\"] .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-ee7d74b8-c08f-40f4-be86-0deebc0f0d50 .jarvis-StateListItem:nth-child(2) .q-slider .q-slider__track {\n\tbackground: linear-gradient(to right, #000000 0%,  #ffffff 100%);\n\t/* height: 15px; */\n}\n\n.jarvis-widget-ee7d74b8-c08f-40f4-be86-0deebc0f0d50 .jarvis-StateListItem:nth-child(2) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-ee7d74b8-c08f-40f4-be86-0deebc0f0d50 .jarvis-StateListItem:nth-child(11) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-ee7d74b8-c08f-40f4-be86-0deebc0f0d50 .jarvis-StateListItem:nth-child(11) .q-slider__track {\n\tcolor: transparent;\n}\n\n[widgets=\"ec31c152-5dfe-4eff-9df2-dbcd9e73b65d\"] .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #009fff 0%, #00cfff 33%, #ffffff 50%, #fff000 83%, #ff5000 100% );\n\t/* height: 15px; */\n}\n\n[widgets=\"ec31c152-5dfe-4eff-9df2-dbcd9e73b65d\"] .q-slider__track {\n\tcolor: transparent;\n}\n\n/* ab v3.0.11 , mit v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-ec31c152-5dfe-4eff-9df2-dbcd9e73b65d .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-ec31c152-5dfe-4eff-9df2-dbcd9e73b65d .q-slider__track {\n\tcolor: transparent;\n}\n\n/* Bei mehreren Slidern im Widget, Einschänrkung auf das StateList-Element notwendig */\n\n[widgets=\"ec31c152-5dfe-4eff-9df2-dbcd9e73b65d\"] .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n[widgets=\"ec31c152-5dfe-4eff-9df2-dbcd9e73b65d\"] .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-ec31c152-5dfe-4eff-9df2-dbcd9e73b65d .jarvis-StateListItem:nth-child(2) .q-slider .q-slider__track {\n\tbackground: linear-gradient(to right, #000000 0%,  #ffffff 100%);\n\t/* height: 15px; */\n}\n\n.jarvis-widget-ec31c152-5dfe-4eff-9df2-dbcd9e73b65d .jarvis-StateListItem:nth-child(2) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-ec31c152-5dfe-4eff-9df2-dbcd9e73b65d .jarvis-StateListItem:nth-child(5) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-ec31c152-5dfe-4eff-9df2-dbcd9e73b65d .jarvis-StateListItem:nth-child(5) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-ec31c152-5dfe-4eff-9df2-dbcd9e73b65d .jarvis-StateListItem:nth-child(6) .q-slider .q-slider__track {\n\tbackground: linear-gradient(to right, #000000 0%,  #ffffff 100%);\n\t/* height: 15px; */\n}\n\n.jarvis-widget-ec31c152-5dfe-4eff-9df2-dbcd9e73b65d .jarvis-StateListItem:nth-child(6) .q-slider__track {\n\tcolor: transparent;\n}\n\n[widgets=\"53f7e560-4faa-4185-bea7-345fed6bd8d7\"] .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n[widgets=\"53f7e560-4faa-4185-bea7-345fed6bd8d7\"] .q-slider__track {\n\tcolor: transparent;\n}\n\n/* ab v3.0.11 , mit v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-53f7e560-4faa-4185-bea7-345fed6bd8d7 .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n.jarvis-widget-53f7e560-4faa-4185-bea7-345fed6bd8d7 .q-slider__track {\n\tcolor: transparent;\n}\n\n/* Bei mehreren Slidern im Widget, Einschänrkung auf das StateList-Element notwendig */\n\n[widgets=\"53f7e560-4faa-4185-bea7-345fed6bd8d7\"] .jarvis-StateListItem:nth-child(1) .q-slider .q-slider__track {\n\tbackground: linear-gradient( to right, #ff5000 0%, #fff000 33%, #ffffff 50%, #00cfff 83%, #009fff 100% );\n\t/* height: 15px; */\n}\n\n[widgets=\"53f7e560-4faa-4185-bea7-345fed6bd8d7\"] .jarvis-StateListItem:nth-child(1) .q-slider__track {\n\tcolor: transparent;\n}\n\n/* auch hier v3.0.11, ab v3.1.x nur noch so möglich !! */\n\n.jarvis-widget-53f7e560-4faa-4185-bea7-345fed6bd8d7 .jarvis-StateListItem:nth-child(2) .q-slider .q-slider__track {\n\tbackground: linear-gradient(to right, #000000 0%,  #ffffff 100%);\n\t/* height: 15px; */\n}\n\n.jarvis-widget-53f7e560-4faa-4185-bea7-345fed6bd8d7 .jarvis-StateListItem:nth-child(2) .q-slider__track {\n\tcolor: transparent;\n}"
}`

**Comment by teletapi** [comment]
"version": 3.2,
  "signature": 7983056520356523,
  "styles": "

**Comment by Bernd9000** [comment]
Hast Du vielleicht ein anderen Browser benutzt als vorher ?
Dann Browsercache und eventuell cookies löschen.

**Comment by teletapi** [comment]
Nein Browser ist Firefox aber ich teste das nochmal

**Comment by teletapi** [comment]
Der Fehler hat sich tatsächlich aufgelöst durch cache und cookies löschen
