### ISSUE TITLE
[3.2.0-beta.1] Keine Seite erreichbar

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2589]
Seit Update auf `3.2.0-beta.1` kann ich keine jarvis Seite mehr erreichen.
iob upload jarvis durchgeführt, iob neustart, cache und cookies gelöscht.

Fehler:  index.html/0: Not exists

Log beim Start:

jarvis.0	2024-02-03 09:50:29.891	info	Found Backups for jarvis.0.widgets.
jarvis.0	2024-02-03 09:50:29.885	info	Found Backups for jarvis.0.devices.
jarvis.0	2024-02-03 09:50:29.884	info	Found Backups for jarvis.0.scripts.
jarvis.0	2024-02-03 09:50:29.884	info	Found Backups for jarvis.0.css.
jarvis.0	2024-02-03 09:50:29.883	info	Found Backups for jarvis.0.settings.
jarvis.0	2024-02-03 09:50:29.881	info	Found Backups for jarvis.0.layout.
jarvis.0	2024-02-03 09:50:29.856	info	Connection: WebSocket opened on port 8400 using http...
jarvis.0	2024-02-03 09:50:29.638	info	starting. Version 3.2.0-beta.1 (non-npm: Zefau/ioBroker.jarvis#6a072312b959e4ed70dc13b9b50a5f43000fcea7) in C:/Software/iobroker/node_modules/iobroker.jarvis, node: v18.19.0, js-controller: 5.0.19

**Comment by teletapi** [comment]
Ohja gerade versucht bei mir das gleiche

**Comment by Zefau** [comment]
Guter erster Aufschlag für die Beta :-D

**Comment by BlackandGold1** [comment]
Dito

File index.html/0/&socketHost=&socketPort=8400&socketSecure=false not found: {}

**Comment by sammie76-2** [comment]
Bei mir exakt das gleiche. Link direkt vom Adapter geht nicht und die alten Links funktionieren auch nicht mehr.

Wenn man alte Links nimmt dann bleibt die Seite schwarz und wenn man den Link vom Adapter anklickt in ioBroker erscheint diese Meldung: 

File index.html/0/&socketHost=&socketPort=8400&socketSecure=false not found: {}

**Comment by intruder7777** [comment]
bei mir auch

**Comment by StephanTexxpro** [comment]
Hier auch.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.3` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.3` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by StephanTexxpro** [comment]
Läuft wieder - Danke!
