### ISSUE TITLE
[v3.2.0-beta.3] mdi:chevron-down wird nicht angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2592]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/1e62eebe-6891-458c-97b8-bac5ff1f18d1)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/28ba1fd6-c91c-4322-81ce-a0ea52923d76)

**Comment by Zefau** [comment]
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/810dab38-05cd-40cd-a43a-2d80c759638b)

**Comment by mcuiobroker** [comment]
Liegt anscheinend an den Styles.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0104a495-85e0-436f-87e7-90869050580c)
Schau noch weiter.

**Comment by mcuiobroker** [comment]
War Fehler in den Styles \\ vor .mdi-chevron-down , warum auch immer?
