### ISSUE TITLE
[v3.2.0-beta.3] F2 Klick auf Styles -Instanz fehlt -> keine Anzeige

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2593]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/56d4b4ca-1a2f-44f0-b89d-3b922b979a3f)
Nach Reload ist es wieder da.

**Comment by Zefau** [comment]
Wie bekomme ich das nachgestellt? Mit F2 oder STRG+F8 funktioniert es bei mir.

**Comment by mcuiobroker** [comment]
Passt. Danke.
