### ISSUE TITLE
[v3.2.0-beta.3] scripts window.Socket.setState() Interval 5 Sekunden wird nicht durchgereicht, wenn nicht im Fokus

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2594]
Es wird alle 5 Sekunden ein Wert gesetzt. Ist Jarvis nicht im Fokus, wird es nicht mehr durchgereicht.

Direkt nach der nächsten Minute nachdem jarvis nicht im Fokus ist.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/93c0c3da-12ab-4527-a624-1335e0ffc609)

**Comment by Zefau** [comment]
Jarvis ist eine Visualisierung. Nutze besser ioBroker.javascript, wenn du Logik brauchst.

**Comment by mcuiobroker** [comment]
In dem Fall ging es um Speicherverbrauch senden. 
Dies wird mit scripts erstellt. Warum gehen die window.Socket.SetState() alle 5 Sekunden nicht durch?
Dann ist mir später aufgefallen, dass dadurch der Speicher voll läuft.

**Comment by mcuiobroker** [comment]
Mit Erklärung von "Speicher läuft voll" verständlich. Danke.
#2597
