### ISSUE TITLE
Error adding notification: NOTIFICATIONS is not defined

### ISSUE THREAD

**Issue by djalexz** [Zefau/ioBroker.jarvis#2595]
Hallo mal wieder :-)

Weiß nicht genau seit wann, aber die Notifications funktionieren nicht mehr.

Beim Einfügen von folgedem Text in den Datenpunkt jarvis.0.AddNotification:

`{"title":"TestMeldung","message":"TEST","state":"unread","display":"popup","timeout":2000,"icon":"mdi-book-alert"}`

Kommt nur eine Fehlermeldung im Log:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/11389551/a6b6c5a2-199e-47e9-84e9-9785a6b42d6e)

Installiert ist die aktuellste `jarvis.0, v3.2.0-beta.5`

Vielen Dank

LG Alex

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.13` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.13` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@djalexz
