### ISSUE TITLE
[v3.2.0-beta.4] Initial Bild ausblenden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2596]
Bekommt man diese Anzeige evtl ausgeblendet. Ist auf dem Handy störend.
Oder für 1 Sekunde `display:none` setzen?
Durch ein animiertes "Jarvis"-Logo ersetzen?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/097bcfed-92e0-4687-a09a-f2fceb577014)

**Comment by Zefau** [comment]
Warum störend?

**Comment by Zefau** [comment]
Ist eigl. der "neue" Ladebildschirm von v3.2

**Comment by mcuiobroker** [comment]
Störend wenn man Dark Mode nutzt. 
Dunkel Hell Dunkel Wechsel kommt nicht gut.

Ich kann nur ein Logo empfehlen bzw. das schon vorhandene jarvis-Logo in Gross zu nutzen.

**Comment by mcuiobroker** [comment]
Dachte mehr an sowas
darkMode = false 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/57096193-0910-4a18-8196-4f9b1a82374d)

darkMode = true

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/2674f7ea-11ea-4975-bbcb-e1ffe4e313e6)

**Comment by Zefau** [comment]
Ich hätte jetzt einfach das Logo gezeigt, wie beim Android Splash Screen

**Comment by mcuiobroker** [comment]
Hier die Einstellungen dafür, kannst es Dir ja überlegen, wie du es haben möchtest.
HTML
```
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Jarvis LOGO</title>
    <!-- Weitere Metadaten, CSS-Dateien, Skripte usw. hier einfügen -->
</head>
<body style="width:100%; min-height:100%;">
    <header>
        <!-- Kopfzeile der Webseite, z.B. Logo, Menü usw. -->
    </header>
    
    <main>
        <!-- Hauptinhalt der Webseite -->
		<div class="logocontainer">
               <div>
			<div class = "TEXT">jarVIS</div>
			<div class = "TEXTVersion">Version 3</div>
		</div>
               </div>
        <!-- Weitere Inhalte wie Bilder, Videos, Listen usw. hier einfügen -->
    </main>
    
    <footer>
        <!-- Fußzeile der Webseite, z.B. Copyright-Informationen, Links usw. -->
    </footer>
</body>
</html>
```

CSS
```

.logocontainer {
	min-height: calc(100vh - 120px);
	align-items: center;
	display: flex;
	justify-content: center;
}

.TEXT {
	background-image: url("http://192.168.178.170/download/bilder/jarvisLogoBack.png");
	/* 	background-size: cover; */
	background-size: contain;
	background-clip: text;
	-webkit-background-clip: text;
	color: transparent;
	font-size: calc(20vw + 1vh);
	font-weight: bolder;
	text-align: center;
	-webkit-filter: drop-shadow(2px 2px #333);
	filter: drop-shadow(4px 4px rgba(25,118,210,0.6));
}

.TEXTVersion {
	/* background-image: url("http://192.168.178.170/download/bilder/BlindLevelSwitch.gif"); */
	background: linear-gradient(90deg, rgba(15,63,193,0.896796218487395) 34%, rgba(219,14,232,0.7371323529411764) 83%);
	background-size: cover;
	background-clip: text;
	-webkit-background-clip: text;
	color: transparent;
	font-size: calc(10vw + 1vh);
	font-weight: bolder;
	text-align: center;
	filter: drop-shadow(4px 4px rgba(255,255,255,0.8));
}
```

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.12` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.12`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Jarvis dreht seine Runden, mehr nicht.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/73dd87f1-9822-4455-9b49-651dcce03f0a)

**Comment by Zefau** [comment]
> Kannst du den Hintergrund in Abhängigkeit vom DarkMode dunkel gestalten, wenn true.

Ne, das geht nicht. Zum Zeitpunkt des Ladens weiß ich nicht, welcher Mode genutzt wird. Das wird ja erst noch geladen. Ich könnte es höchsten im Browser speichern.

**Comment by mcuiobroker** [comment]
Dann wäre es nur beim ersten Start hell, danach aus Cache, wäre es dann dunkel. Ist auf jeden Fall besser, als immer hell.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.13` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.13`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Jetzt hat man direkt, den Hintergrund auch in allen TABs.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6ff49551-660c-40ac-baea-cbb59b16b953)
