### ISSUE TITLE
[v3.2.0-beta.4] Speicher läuft voll

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2597]
Hat man längere Zeit nichts mit jarvis gemacht und es ist nicht im Fokus und kommt dann wieder zurück, haut er ab dem Zeitpunkt das console.log() voll mit Meldungen. Dabei erhöht sich dann der Speicher verbrauch von 1200 MB auf ca 5000MB.

Ich ändere die Settings nicht. Wodurch kommt das?

Kann es sein, dass es mit den window:Socket.setState-Kommandos zusammenhängt die nicht weitergeleitet werden?
Werden die irgendwo zwischengespeichert?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0838542c-0a72-4155-9730-c36dd371cc74)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/45c02043-e24e-4764-91aa-45c7b38176ef)

Ja also man sieht es .
Jetzt habe ich die Frequenz von window.Socket.setState() geringer gesetzt und es wird wesentlich weniger Speicher verbraucht.
Irgendwo wird also was zwischengespeichert.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6d3b8a26-20af-420e-8f0c-bdb9120be241)

**Comment by Zefau** [comment]
Moderne Browser führen Code nicht aus, wenn der Tab inaktiv ist. Das ist kein Jarvis Fehler. Beim aktiven Tab wird dann alles nachgeholt.

Versuch es mit https://stackoverflow.com/a/53944438 um das Skript zu stoppen oder alternativ mittels WebWorker https://stackoverflow.com/a/54414529

**Comment by Zefau** [comment]
Moderne Browser führen Code nicht aus, wenn der Tab inaktiv ist. Das ist kein Jarvis Fehler. Beim aktiven Tab wird dann alles nachgeholt.

Versuch es mit https://stackoverflow.com/a/53944438 um das Skript zu stoppen oder alternativ mittels WebWorker https://stackoverflow.com/a/54414529 / https://stackoverflow.com/a/75828547

**Comment by mcuiobroker** [comment]
Ok. Danke.
