### ISSUE TITLE
Repository `Zefau/jarvis.adapters` ins Deployment-Skript aufnehmen

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2600]
Aktuelle Liste der Adapter-Importer automatisch ins Repository https://github.com/Zefau/jarvis.adapters releasen bei einem Versionsupdate

**Comment by mcuiobroker** [comment]
Da müsste es auch eine Art Template geben, das man selber füllen kann und direkt in jarvis nutzen kann. Somit kann man für Exoten sein Importer definieren und freigeben?

**Comment by Zefau** [comment]
Du kannst das Repository forken und dann mittels Pull-Request Änderungen vorschlagen, die ich dann in die nächste Version übernehmen kann.

**Comment by mcuiobroker** [comment]
Was mir noch einfällt. Man sollte nur die Adapter im Importer sehen die man selber hat?

**Comment by Zefau** [comment]
Ja, machst du einen Feature Request auf? Dann baue ich das noch in die v3.2 ein.
