### ISSUE TITLE
Adapter Importer - Nur Adapter anzeigen, die man auch selber verwendet

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2601]
Zurzeit werden im Importer alle mögliche Adapter, die es im Importer gibt angezeigt.
Sinnvoll ist es nur die anzuzeigen, die man selber in Verwendung hat.
Denn die Liste wird schon ziemlich lang. Bevor man die Übersicht verliert sollte man sich auf die beschränken, die der User einsetzt.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.8` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.8`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Prinzipiell sieht es gut aus, bis auf ein Problem. Er deslektiert plötzlich die Adapter?
![jarvis v320-beta8 Geräte importieren Problem](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9289f7a9-f011-41da-81df-e042af2b8d5b)

**Comment by Zefau** [comment]
Man erkennt das im Screenshot schlecht: Was genau drückst du, dass er deselektiert? Oder passiert das einfach so?

**Comment by mcuiobroker** [comment]
Das Wetter zeigt auch keine Geräte?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9c266fb0-5e75-4c15-af14-1dc395d9ed2b)

**Comment by mcuiobroker** [comment]
Kann man das dort irgendwie erwähnen oder anzeigen?

**Comment by Zefau** [comment]
> Er deselektiert plötzlich die Adapter?

Bekomme ich leider nicht nachgestellt (mit Chrome). Also wenn man (bewusst) de-selektiert dann zeigt er nicht mehr an wie viele Geräte gefunden wurden.

Warum er bei dir plötzlich alle Adapter (ohne Klick) de-selektiert weiß ich nicht.

**Comment by mcuiobroker** [comment]
Hab es auch nicht immer. Hier noch die Vorgehensweise, wie ich den Fehler erhalten habe.
Werde es weiter beobachten. Mache hier erstmal zu. Danke.

Also es passiert nur einmal, wenn man Geräte importieren aufruft.
Man muss alle Adapter selektieren und dann Read Adapters klicken.
Warten und dann wieder die obere Liste mit den Adaptern öffnen.
Nach ca 10 Sekunden verschwindet dann die Selektion, nach ca 8 Sekunden ist sie wieder da.
