### ISSUE TITLE
[v3.2.0-beta.4] Importer für `tr-064` keine Geräte importierbar

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2604]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/568f1ac7-8c67-46b9-8889-1254dc870660)
Adapter ist vorhanden
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/92e2e4f4-2b28-4ae6-b11b-7a6a2e2681d5)

Importer (objectType "state"?)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/7d3187eb-ed36-401d-9bca-383fceb33e48)

CallList ist ein Device?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c4e33cae-3390-4835-b0c0-b96fe063fc6c)

**Comment by mcuiobroker** [comment]
Jetzt zeigt er die an?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/d363a958-d5e2-4967-b25f-bcd78df588da)
Passt nicht?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/acc6e2ff-1edf-49c7-8207-6721aff2eb8f)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.8` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.8` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
