### ISSUE TITLE
Viele Disconnect/Connect Meldungen

### ISSUE THREAD

**Issue by pphlwmarcel** [Zefau/ioBroker.jarvis#2606]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- Which jarvis version are you running / Welche Version von jarvis nutzt du? 3.1.8

**Describe the bug / Beschreibe den Fehler**
Ich betreibe ein FireHD10 mit Fullybrowser und rufe darauf Jarvis als Visualisierung auf. Seit eineiger Zeit tauchen im Log von Jarvis im ioBroker viele Connect/Disconnect Messages auf. Am Tablet selbst sind keine Probleme zu sehen und die Netzwerkverbindung scheint auch stabil zu sein.

`<html>
<body>

jarvis.0 | 2024-02-18 14:01:11.519 | info | Client with IP 192.168.20.90 disconnected.
jarvis.0 | 2024-02-18 14:01:08.831 | info | Client with IP 192.168.20.90 connected.
jarvis.0 | 2024-02-18 13:57:14.801 | info | Client with IP 192.168.20.90 disconnected.
jarvis.0 | 2024-02-18 13:57:06.152 | info | Client with IP 192.168.20.90 connected.
jarvis.0 | 2024-02-18 13:57:00.002 | info | Client with IP 192.168.20.90 disconnected.
jarvis.0 | 2024-02-18 13:54:21.746 | info | Client with IP 192.168.20.90 connected.
jarvis.0 | 2024-02-18 13:54:19.623 | info | Client with IP 192.168.20.90 disconnected.
jarvis.0 | 2024-02-18 13:51:42.489 | info | Client with IP 192.168.20.90 connected.
jarvis.0 | 2024-02-18 13:51:41.643 | info | Client with IP 192.168.20.90 disconnected.

</body>
</html>`

**Comment by Bernd9000** [comment]
Schau mal im Log deines Routers ob dort dein FireHD10 im Wlan ebenfalls ständig disconnect ist.
Dann könnte es vielleicht ein Dualband Problem sein oder Wifi disconnect wegen Inaktivität ?

**Comment by lamium2** [comment]
Bei mir sind nun so viele Connects/Disconnects, dass es nicht mehr nutzbar ist. Mehrmals pro Sekunde.

**Comment by Zefau** [comment]
@pphlwmarcel ist das hier noch aktuell?

**Comment by Zefau** [comment]
@pphlwmarcel @lamium2
