### ISSUE TITLE
[v3.2.0-beta.8] Tag-Filterung ok?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2607]
Soll es so sein?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/709329ac-84d9-4e54-a46e-0d383fb34c3c)
Ich filtere nach "tr" in den Tags und es werden auch Geräte von `hue-extended` angezeigt, da ist aber kein "tr" in hue-extended.
Und andere "OhneBezeichner".

**Comment by Zefau** [comment]
Ne, sieht falsch aus.

**Comment by Zefau** [comment]
Muss mich korrigieren, sieht doch richtig aus.

Bei "Gruppieren nach" hast du "Tags" ausgewählt. Danach ist es auch korrekt gruppiert.
Die Eingrenzung deiner Suche findest du im Filter-Symbol:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/41b88fd9-98fd-4962-b282-ad849ec26d02)

Dort kannst du auf "Tags" eingrenzen bei der Suche. Ohne Eingrenzung sucht er natürloch "tr" überall und findet es auch bei den Geräten von hue-extended.
