### ISSUE TITLE
[v3.2.0-beta.8] Widget Höhe verändert sich

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2608]
Ich glaube das sollte so auch nicht sein :-)
Widgets verändern automatisch ihre Höhe.
Ist seit beta.7

![Animation](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/93905d06-06ef-4f4e-bd57-839a3bcb0b43)

**Comment by Bernd9000** [comment]
Scheint an diesem Schalter zu liegen wenn eingeschaltet:

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/de3a22a2-cbb9-4035-b03d-cb102d0a8e0b)

**Comment by intruder7777** [comment]
bei mir auch so.

**Comment by Zefau** [comment]
@intruder7777 auch bei aktivierter Option oder auch bei deaktiverter Option?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.9` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.9` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Jetzt taucht der Fehler bei folgender Option auf:

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/fc36cf73-6c98-4543-bf26-9932ec1798bc)

Viele Widgets haben nicht mehr die richtige Höhe wie vorher und die Hintergrundfarbe ist bei einigen Seiten auf einmal sichtbar.

**Comment by Bernd9000** [comment]
jo, der Fehler selbst ist behoben.
Allerdings haufenweise neue Fehler, wie ich oben schon angedeutet habe.
Aber hier mach ich dicht.

**Comment by Zefau** [comment]
> Viele Widgets haben nicht mehr die richtige Höhe wie vorher und die Hintergrundfarbe ist bei einigen Seiten auf einmal sichtbar.
Also da stimmt was mit der Skalierung bei "Höhe aller Widgets identisch mit sichtbarer Seitenhöhe" nicht.

**Comment by Zefau** [comment]
Dann mach ich nochmal auf. Das habe ich vergessen mit den Widgets.

**Comment by Zefau** [comment]
Kannst du ein Beispiel screenshoten?

**Comment by Bernd9000** [comment]
Später,muß da noch genauer schauen, im Moment geht es nicht.
Ich mach dann ein neues Issue auf.

**Comment by Bernd9000** [comment]
Hier mal ein Problem mit dem Schalter "TAB Vollbild"
Hab folgendes Bild mit DisplayImage als widget eingefügt:
![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/6b63f1e8-a5d4-404e-b486-a00acf1a5db7)


Wenn ich jetzt die Seite das erste mal aufrufe fehlt der untere rote Rand (hier nur Teilausschnitt).
Es kann aber runter gescrollt werden.
![1](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/2ef60c8c-9303-44ed-8647-61a31b527a80)

Wenn ich jetzt die Seite mit F5 aktualisiere wird es vollständig angezeigt.
Wechsel ich die jarvis Seite und kehre wieder zurück fehlt wieder der untere rote Rand.


Problem mit "Höhe aller Widgets identisch mit sichtbarer Seitenhöhe:
Hier bleibt jetzt immer ein ca. 10 Pixel hoher unterer Rand.
Feine blaue Linie kennzeichnet das Widget.
Freiraum für Statusleiste ?

![2](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/c3bd28d7-1c52-4bc6-990a-f41072ed078e)

**Comment by Bernd9000** [comment]
Sind mehrere Widgets auf einer jarvis Seite im Spiel, kommt es auch zu Überschneidungen:

![3](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/5eaa702a-1d7b-4308-80da-723fa0d71331)

**Comment by mcuiobroker** [comment]
@Bernd9000 Ist auch noch mit Version v3.2.0-beta.45 so?

**Comment by Bernd9000** [comment]
Ja, leider.
Überschneidung:
Bei älteren Versionen wurde bei kleinerem Bildschirm die Schrift nur kleiner aber alles war lesbar und es kam nicht zu Überschneidung der Widgets.
Bei v3.2.0-beta.49 wird die Schrift nicht verkleinert, widgets überschneiden sich und es ist dann nichts mehr lesbar.

Nochmal das Beispiel mit kleinerem Bildschirm:

v3.2.0-beta.6
![1](https://github.com/user-attachments/assets/53d43a8b-8ab1-436b-a8f3-1641440d002f)

v3.2.0-beta.49
![2](https://github.com/user-attachments/assets/544641d7-97dc-4643-8337-35ea81bbb44d)

Das Vollbild Problem ist immer noch vorhanden.

**Comment by Bernd9000** [comment]
Oder ein weiteres Beispiel mit verkleinern des Browser Fenster.

Beta6, alles wird dynamisch angepaßt:

![Animation1](https://github.com/user-attachments/assets/15c93125-1d47-46e5-a198-29685d5c9d9e)

Beta49, es wird nur abgeschnitten:

![Animation2](https://github.com/user-attachments/assets/ae2b7195-1a30-42ce-9d21-7df84094cd55)

**Comment by Zefau** [comment]
> Beta6, alles wird dynamisch angepaßt:
> 
> ![Animation1](https://private-user-images.githubusercontent.com/77005685/352780327-15c93125-1d47-46e5-a198-29685d5c9d9e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTU4MTgsIm5iZiI6MTcyMjE1NTUxOCwicGF0aCI6Ii83NzAwNTY4NS8zNTI3ODAzMjctMTVjOTMxMjUtMWQ0Ny00NmU1LWExOTgtMjk2ODVkNWM5ZDllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzY5MDM3MzZiYmRlYjU0NTljMmE2ZmExZDZiNGQ1YjYzYmIyNWE3YzM5ZjJjZDUwNzRmNDY0MDcyNzI4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bpOOc7xcBwJfyP2t_qvLrZRbcRwQYgG4Q9-Jjl5rcTg) [ ![Animation1](https://private-user-images.githubusercontent.com/77005685/352780327-15c93125-1d47-46e5-a198-29685d5c9d9e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTU4MTgsIm5iZiI6MTcyMjE1NTUxOCwicGF0aCI6Ii83NzAwNTY4NS8zNTI3ODAzMjctMTVjOTMxMjUtMWQ0Ny00NmU1LWExOTgtMjk2ODVkNWM5ZDllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzY5MDM3MzZiYmRlYjU0NTljMmE2ZmExZDZiNGQ1YjYzYmIyNWE3YzM5ZjJjZDUwNzRmNDY0MDcyNzI4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bpOOc7xcBwJfyP2t_qvLrZRbcRwQYgG4Q9-Jjl5rcTg) ](https://private-user-images.githubusercontent.com/77005685/352780327-15c93125-1d47-46e5-a198-29685d5c9d9e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTU4MTgsIm5iZiI6MTcyMjE1NTUxOCwicGF0aCI6Ii83NzAwNTY4NS8zNTI3ODAzMjctMTVjOTMxMjUtMWQ0Ny00NmU1LWExOTgtMjk2ODVkNWM5ZDllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzY5MDM3MzZiYmRlYjU0NTljMmE2ZmExZDZiNGQ1YjYzYmIyNWE3YzM5ZjJjZDUwNzRmNDY0MDcyNzI4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bpOOc7xcBwJfyP2t_qvLrZRbcRwQYgG4Q9-Jjl5rcTg) [ ](https://private-user-images.githubusercontent.com/77005685/352780327-15c93125-1d47-46e5-a198-29685d5c9d9e.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTU4MTgsIm5iZiI6MTcyMjE1NTUxOCwicGF0aCI6Ii83NzAwNTY4NS8zNTI3ODAzMjctMTVjOTMxMjUtMWQ0Ny00NmU1LWExOTgtMjk2ODVkNWM5ZDllLmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTgwYzY5MDM3MzZiYmRlYjU0NTljMmE2ZmExZDZiNGQ1YjYzYmIyNWE3YzM5ZjJjZDUwNzRmNDY0MDcyNzI4M2MmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bpOOc7xcBwJfyP2t_qvLrZRbcRwQYgG4Q9-Jjl5rcTg)
> 
> Beta49, es wird nur abgeschnitten:
> 
> ![Animation2](https://private-user-images.githubusercontent.com/77005685/352780331-ae2b7195-1a30-42ce-9d21-7df84094cd55.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTU4MTgsIm5iZiI6MTcyMjE1NTUxOCwicGF0aCI6Ii83NzAwNTY4NS8zNTI3ODAzMzEtYWUyYjcxOTUtMWEzMC00MmNlLTlkMjEtN2RmODQwOTRjZDU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxY2NmNDcwZjI1YzdjNTU1ZTQwNzRmNmU5N2JiNDJmMGFmNGIwOGMyZTkxZWYzNmIyZjUyYjUwNDEyM2JiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fwBmRl9pq99CX0_5caOtVnBNTD0Lc7iSI07I1WkQSwo) [ ![Animation2](https://private-user-images.githubusercontent.com/77005685/352780331-ae2b7195-1a30-42ce-9d21-7df84094cd55.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTU4MTgsIm5iZiI6MTcyMjE1NTUxOCwicGF0aCI6Ii83NzAwNTY4NS8zNTI3ODAzMzEtYWUyYjcxOTUtMWEzMC00MmNlLTlkMjEtN2RmODQwOTRjZDU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxY2NmNDcwZjI1YzdjNTU1ZTQwNzRmNmU5N2JiNDJmMGFmNGIwOGMyZTkxZWYzNmIyZjUyYjUwNDEyM2JiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fwBmRl9pq99CX0_5caOtVnBNTD0Lc7iSI07I1WkQSwo) ](https://private-user-images.githubusercontent.com/77005685/352780331-ae2b7195-1a30-42ce-9d21-7df84094cd55.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTU4MTgsIm5iZiI6MTcyMjE1NTUxOCwicGF0aCI6Ii83NzAwNTY4NS8zNTI3ODAzMzEtYWUyYjcxOTUtMWEzMC00MmNlLTlkMjEtN2RmODQwOTRjZDU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxY2NmNDcwZjI1YzdjNTU1ZTQwNzRmNmU5N2JiNDJmMGFmNGIwOGMyZTkxZWYzNmIyZjUyYjUwNDEyM2JiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fwBmRl9pq99CX0_5caOtVnBNTD0Lc7iSI07I1WkQSwo) [ ](https://private-user-images.githubusercontent.com/77005685/352780331-ae2b7195-1a30-42ce-9d21-7df84094cd55.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjIxNTU4MTgsIm5iZiI6MTcyMjE1NTUxOCwicGF0aCI6Ii83NzAwNTY4NS8zNTI3ODAzMzEtYWUyYjcxOTUtMWEzMC00MmNlLTlkMjEtN2RmODQwOTRjZDU1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzI4VDA4MzE1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWUxY2NmNDcwZjI1YzdjNTU1ZTQwNzRmNmU5N2JiNDJmMGFmNGIwOGMyZTkxZWYzNmIyZjUyYjUwNDEyM2JiYzQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.fwBmRl9pq99CX0_5caOtVnBNTD0Lc7iSI07I1WkQSwo)

Hast du diese Option aktiviert?

![grafik](https://github.com/user-attachments/assets/1043faf9-0ca2-42d3-80e8-ce4190265a63)

**Comment by Bernd9000** [comment]
Ja,, ist aktiviert.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.50` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.50` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
v3.2.0-beta.50
Sieht gut aus.
Bitte nochmal bei der Option "Tab Vollbild" schauen, da funktioniert es noch nicht.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.51` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.51` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
v3.2.0-beta.51

widgets mit den Modulen `iFrames` und `DisplayImage` werden mit der Version nicht mehr angezeigt.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.52` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.52` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Leider noch nicht [#2726 ](https://github.com/Zefau/ioBroker.jarvis/issues/2726#issuecomment-2256760781)

**Comment by Zefau** [comment]
Ich schließe mal hier, da duplicate zu #2726
