### ISSUE TITLE
3.2.0 beta9 Seite läd ununterbrochen neu

### ISSUE THREAD

**Issue by SlipKoRn88** [Zefau/ioBroker.jarvis#2613]
Ich habe die beta 9 installiert. Jarvis neu gestartet, websocket neu gestartet, Browser Cache geleert.
Jedoch erhalte ich folgendes Fehlerbild:

![Jarvis 3 2 0 beta9](https://github.com/Zefau/ioBroker.jarvis/assets/95069101/6cbde690-19c8-4927-817c-61a22177340e)

**Comment by Zefau** [comment]
Was steht denn in der Browser-Konsole?

**Comment by SlipKoRn88** [comment]
![Grafik-9](https://github.com/Zefau/ioBroker.jarvis/assets/95069101/7898cad8-7ea3-49cd-99fa-bc29991586ff)

**Comment by mretich** [comment]
Hallo,

ich habe genau das gleiche Problem mit dem dauer Reload der Seite nach dem Upgrade..
Bei mir gint die Konsole folgende Warnings:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/4835520/3e4c76b9-8dd4-4185-85f9-4a298604e464)

**Comment by Zefau** [comment]
Von welcher Version kommt ihr?

**Comment by SlipKoRn88** [comment]
Von 3.1.8

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/issues/2464#issuecomment-1977268227

**Comment by SlipKoRn88** [comment]
Funktioniert bei mir leider nicht. Im ioBroker Protokoll habe ich nun folgendes:


jarvis.0
2024-03-05 09:07:11.931	warn	socket/?EIO=4&transport=polling&t=OuDfkYh: Not exists

jarvis.0
2024-03-05 09:07:09.201	warn	socket/?EIO=4&transport=polling&t=OuDfllV: Not exists

jarvis.0
2024-03-05 09:07:06.200	warn	socket/?EIO=4&transport=polling&t=OuDfjAK: Not exists

jarvis.0
2024-03-05 09:07:03.237	warn	socket/?EIO=4&transport=polling&t=OuDfkHl: Not exists

jarvis.0
2024-03-05 09:07:00.541	warn	socket/?EIO=4&transport=polling&t=OuDfhpF: Not exists

**Comment by Zefau** [comment]
Das Frontend in jarvis nutzt kein Socket-IO mehr, insofern deutet die Fehlermeldung `2024-03-05 09:07:00.541 warn socket/?EIO=4&transport=polling&t=OuDfhpF: Not exists` darauf hin, dass noch 3.1 im Frontend geladen wird.

Hast du den Adapter nochmal versucht upzuloaden?

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/5ad2e0f8-e9b1-4b6d-8c97-4031b4fbf50c)

**Comment by SlipKoRn88** [comment]
Mit der v3.2.0-beta.10 habe ich weiterhin das Problem. 

Jarvis, Web Server und Web Socket gestoppt
Jarvis Fenster im Browser geschlossen
Browser Cache geleert
Jarvis Beta10 installiert
Jarvis Upload
Alle Instanzen wieder gestartet

**Comment by SlipKoRn88** [comment]
Ich denke, ich habe das Problem gefunden. Es liegt an den Scripts in den Jarvis Einstellungen.
Mir ist aufgefallen, dass mein importiertes Script (import "http://192.168.178.92:8082/vis.0/JavaScripts/TabUhrRechts.js") in der beta10 nicht angezeigt wird.

Darauf habe ich das Script im Datenpunkt entfernt. Nach einem Reload von Jarvis,, stellte ich fest, dass nun im Datenpunkt eine Signatur angelegt wurde.
![script](https://github.com/Zefau/ioBroker.jarvis/assets/95069101/03bf7260-508a-45eb-9f20-96322cde6725)
Nun funktioniert es ohne das ständige neu Laden.

**Comment by mretich** [comment]
Hallo,

auch ich konnte das Problem jetzt lösen...
Nachdem ich nach genauerer Konsolenanalyse festgestellt hbe, dass es vor dem Relaod IMMER zu einem SIGNATURE change event kam bevor er neu geladen hat, dachte ich ich kann das wie @SlipKoRn88 lösen, indem ich den ensprechenden Eintrag lösche.
Jedoch hat das bei mir NICHT funktioniert.
Ich musste dem Datenpunkt zumindest eine LEERE signature property setzen.
Dadurch wurde der reload beendet.

Vielleicht wäre es nicht schlecht, wenn nach einem Upgrade überprüft wird, ob in den Objekten zumindest das property "signature" steht und dieses ggf. automatisch setzt...

**Comment by fladdie** [comment]
Hi,

also ich habe das Problem ebenfalls. Habe von 3.1.8 auf die aktuelle Beta v3.2.0-beta.10. 
Der Hinweis von mretich nach dem property "signature" hat letztlich zur Lösung geführt. 

Bei mehreren Datenpunkten hatte die Eigenschaft "signature" komplett gefehlt. Nach dem hinzufügen mit einer leeren "" Signatur läuft nun Jarvis wieder.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.
