### ISSUE TITLE
[3.2.0-beta.9][blind] DP Eigenschaften werden nicht mehr berücksichtigt

### ISSUE THREAD

**Issue by mpl1337** [Zefau/ioBroker.jarvis#2615]
Beim betätigen der Auf/Ab Buttons eines Rollladens werden 0 bzw 100 gesendet. Vor Update auf 3.2.0-beta.9 wurde true/false gesendet.

Hat sich hier was geändert?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/a55f9248-2529-430d-aa8c-ec4838385f46)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/9ed8088c-c5b8-473f-acf1-6420bd979633)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/8ad6cdf7-95c7-4751-a2df-0780251477f4)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/ecc9e849-3ae4-4c9b-a5f5-d62de39f5b01)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/6191e3c1-218d-45df-9690-fd049ce5a4d1)

**Comment by mpl1337** [comment]
habe nun durch Downgrade bis 3.2.0-alpha.53 herausgefunden, dass der Fehler mit alpha.54 sich eingeschlichen hat. Alpha53 funktionierte noch, 54 nicht mehr.

Vielleich hilft dir das ja weiter :)

**Comment by mpl1337** [comment]
Lösung in Sicht?

**Comment by Zefau** [comment]
Funktioniert bei mir (mit `v3.2.0-beta.47`).

![grafik](https://github.com/user-attachments/assets/107836db-7276-4cf6-a4ac-7282fa2a54c5)

![grafik](https://github.com/user-attachments/assets/5a25d939-912f-4984-ba1e-3cda4d26f857)

![grafik](https://github.com/user-attachments/assets/10d76b93-2ca1-48b6-bf58-bad186c796dc)

**Comment by mpl1337** [comment]
immernoch das selbe verhalten.

![image](https://github.com/user-attachments/assets/29ba23cc-bec4-4200-9c6a-bb5d1ad7df86)

![image](https://github.com/user-attachments/assets/bf83dc0c-60c0-446b-96e9-d03bb529d373)

![image](https://github.com/user-attachments/assets/99153295-ccde-4877-b53c-f201754af7a8)

![image](https://github.com/user-attachments/assets/fffacdb2-c8af-4a22-979e-c07293769ebd)

**Comment by mpl1337** [comment]
https://github.com/user-attachments/assets/ee0643c5-a2b9-4443-b8e7-8585affbddb0

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.70` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.70` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@mpl1337

**Comment by mpl1337** [comment]
> @mpl1337

Ich werde es am Wochenende testen.

**Comment by mpl1337** [comment]
jetzt geht nichts mehr

![image](https://github.com/user-attachments/assets/b459a49e-5bfd-4c48-ab97-0712a59002f8)
![image](https://github.com/user-attachments/assets/93c0ffe9-0de6-433b-8124-b687e0630a37)
![image](https://github.com/user-attachments/assets/f6d569aa-a13a-4c47-9664-1d4cfd7297a6)

upload all und reboot bereits durchgeführt. Mobile ansicht das selbe.

**Comment by Zefau** [comment]
Installiere bitte nochmal sauber drüber. Die Datei, die laut Warnung fehlt, ist nicht Teil von ` rc-5`.

**Comment by mcuiobroker** [comment]
@mpl1337 Browser-Cache gelöscht?

**Comment by mpl1337** [comment]
Habe es hinbekommen. Cache habe ich gelöscht ging jedoch immer noch nicht. Nach einem weiteren reboot ging es nun wieder.

Das eigentliche Problem ist jetzt auch behoben, Vielen Dank!
