### ISSUE TITLE
implement permission management

### ISSUE THREAD

**Issue by PackElend** [Zefau/ioBroker.jarvis#2617]
Currently, anyone can access Jarvis, I would like to limit access, on role basis.

According to https://github.com/ioBroker/ioBroker.vis-2/issues/94, it is feasible, in principle.
I could not find anything if the architecture of Jarvis allows permission management.

An example Venetian Blinds controlled by e.g. Shelly Shutter there shall be the following roles
- admin 
- configurator, allows two replace devices, rename, add function 
- technician (for the blinds), allowed to start recalibration, set time value for a full movement of the slats  
- user, close open blinds

**Comment by Zefau** [comment]
implemented with v3.2
