### ISSUE TITLE
[v3.2.0-beta.10] Map Marker nicht zentriert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2619]
Markierung ist nicht zentriert
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/59f8c044-a428-4cd9-a43a-bf93166e2d76)
Mit `justify-content:start` ist es wieder zentriert

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a62ceb20-03c3-4fe1-b128-73086ec77326)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/606f887e-d479-44c2-809f-ce396d131774)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.56` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.56` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
`v3.2.0-beta.57`
![image](https://github.com/user-attachments/assets/d84d0913-e79f-483d-9ff0-a8c864109120)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Jetzt wird er gar nicht mehr angezeigt.
![image](https://github.com/user-attachments/assets/2a6924a4-6572-4591-8a92-75d0ba63c2f3)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.59` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.59` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@mcuiobroker
