### ISSUE TITLE
[3.2.0-beta.10] Umschaltung `Sidebar Mini Mode` greift erst nach Reload

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2620]
- Eine Änderung greift erst nach Reload
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/f1582f0c-5f91-4e5c-b8d2-3826f4bef9ce)

- Bei Initialisierung von jarvis ist der Sidebar MiniMode auf true -> bei einer ersten Änderung der Einstellungen wird plötzlich Sidebar Mini Mode auch gesetzt und angezeigt, nach Reload 
-> verwirrend

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.47` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.47` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Setzen mit DP funktioniert nicht. `false` -> `true` geht nicht. Erst mit Reload wird es angezeigt.
![image](https://github.com/user-attachments/assets/296f5557-c7c1-47b9-ad48-9160d45c4b1b)
Schaut man in die Einstellungen in jarvis ist der Mini-Mode aber gesetzt.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.54` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.54` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Auf dem PC funktinoiert es nun.
Auf dem Handy nicht. (auch nach Reload nicht)

**Comment by Zefau** [comment]
Aus Platzgründen gibt es keinen Mini Mode auf dem Handy.

**Comment by mcuiobroker** [comment]
Auf dem Tablet wird es auch nicht angezeigt

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.
