### ISSUE TITLE
[3.2.0-beta.10] MAP -> `Zoom` beschränken auf max 19

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2621]
Man kann den Zoom größer als 19 wählen, obwohl es der größte Wert ist den `leaflet` verarbeitet.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3e890fec-bea9-43a6-82ff-f2e43e855832)

https://wiki.openstreetmap.org/wiki/DE:Zoom_levels

**Comment by mcuiobroker** [comment]
Ist mit `v3.2.0-beta.49` drin. Passt. Danke.

**Comment by mcuiobroker** [comment]
Label noch falsch gesetzt

**Comment by Zefau** [comment]
> Label noch falsch gesetzt

Was meinst du?
