### ISSUE TITLE
[3.2.0-beta.10] MAP wird auf Handy nicht korrekt angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2622]
- Anzeige auf dem Handy nur 2px hoch?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/55b7dfb2-7bf6-4662-b2b4-a5501958a723)

**Comment by Zefau** [comment]
Sieht bei mir i.O. aus. Ggf. ähnlich wie https://github.com/Zefau/ioBroker.jarvis/issues/2699 ?

**Comment by mcuiobroker** [comment]
Mit rc.5 ok
