### ISSUE TITLE
[3.2.0-beta.10] Fehlermeldungen von Calendar, obwohl nicht vorhanden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2623]
Es werden Fehlermeldungen angezeigt, aber es ist kein Calendar mehr installiert?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8fca58f4-4f2f-4bc5-9f76-e7fb418960e4)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3552dcff-02c3-4878-94f7-38266629b224)

Cache wurde gelöscht.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.67` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.67` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
@mcuiobroker

**Comment by mcuiobroker** [comment]
Kommt nicht mehr.
