### ISSUE TITLE
[3.2.0-beta.10] http connection reset during load

### ISSUE THREAD

**Issue by softwarecrash** [Zefau/ioBroker.jarvis#2624]
Hallo,

in der aktuellen beta scheint ein problem zu sein.

wenn man versucht jarvis über `https://10.10.10.10:8400` aufzurufen ist alles gut.
wenn man aber versucht mit `http//:10.10.10.10:8400` jarvis aufzurufen bekommen man ein `Die Verbindung zum Server wurde zurückgesetzt, während die Seite geladen wurde.` oder ein `Empty response`

das wäre an sich ja kein problem, aber ich habe das ganze mit authelia und traefik als reverse proxy laufen.
die traefik config für den docker container sieht so aus
```
      - traefik.enable=true
      - traefik.docker.network=proxy
      - traefik.http.routers.jarvis.entrypoints=http
      - traefik.http.routers.jarvis.rule=Host(`jarvis.server.de`)
      - traefik.http.middlewares.secure-https-redirect-jarvis.redirectscheme.scheme=https
      - traefik.http.routers.jarvis.middlewares=secure-https-redirect-jarvis
      - traefik.http.routers.jarvis.service=noop@internal
      - traefik.http.routers.jarvis-secure.entrypoints=https
      - traefik.http.routers.jarvis-secure.rule=Host(`jarvis.server.de`)
      - traefik.http.routers.jarvis-secure.tls=true
      - traefik.http.routers.jarvis-secure.tls.certresolver=http
      - traefik.http.routers.jarvis-secure.service=jarvis
      - traefik.http.services.jarvis.loadbalancer.server.port=8400
      - traefik.http.routers.jarvis-secure.middlewares=middlewares-authelia@file
```
selbst wenn man `https://jarvis.server.de` aufruft wird wohl im hintergrund versucht erst `http` aufzurufen, was im traefik dann zu einem `bad gateway` führt.

auch ein abschalten der sicheren verbindung in jarvis hat keinen effekt.

**Comment by softwarecrash** [comment]
das ganze wird noch etwas interessanter wenn man jarvis hinter einem ngnix proxy mit zertifikat und gesichertem websocket versteckt.
er will einen ws aufbauen aber da die seite gesichert ist bricht er ab weil er keinen wss hat
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/44615614/be565907-dc2c-4045-813b-400ec8c79363)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.31` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.31` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by softwarecrash** [comment]
sieht gut aus!
