### ISSUE TITLE
HomeMatic-IP - Geräte einer CCU3 werden nicht erkannt! Im ioBroker sind alle Datenpunkte vorhanden.

### ISSUE THREAD

**Issue by dahljoa** [Zefau/ioBroker.jarvis#2625]
Jarvis-Version: V3.1.8

Verschiedene HomeMatic-IP - Geräte meiner CCU3 werden in JARVIS nicht erkannt! Im ioBroker sind alle Datenpunkte vorhanden.

z.B.: Fensterkontakt Küche, ein HmIP-SWDO-2 wird nicht erkannt, der ältere HmIP-SWDO als Fensterkontakt Essecke funktioniert einwandfrei.
Ich kann keinen Unterschied der Datenpunkte erkennen.

![Geräte werden nicht importiert](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/1b710ce7-f692-4b6b-9d7d-ed9cfc9d2e22)
![_Fensterkontakt Essecke SWDO](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/2797c750-ce2b-4974-a08a-18f84cbb2714)
![_Fensterkontakt Küche SWDO-2](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/00962897-b0fb-4fc0-8cba-beb4bff7f7d2)

**Comment by Zefau** [comment]
Unter https://github.com/Zefau/jarvis.adapters/blob/main/hm-rpc.js findest du die aktuelle Definition der hm-rpc Geräte.

Sofern etwas fehlen sollte, gerne per pull-request oder hier im Issue (dann übernehme ich es) im entsprechenden Format angeben.

**Comment by Zefau** [comment]
@dahljoa
