### ISSUE TITLE
[v3.2.0-beta.10] Android App  - keine Verbindung möglich

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2628]
- Es kommt keine Verbindung zustande.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e083629f-cef0-4098-a3a7-13ab2efa8504)
Es kommt nur die Initialseite
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e03e621a-4498-4459-92f4-054334a643e1)

- StartIcon platt gedrückt?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/73cb6bda-55f7-4f74-9b79-97f46167eb30)

**Comment by Zefau** [comment]
Das müsste mit der aktuellen beta behoben sein?

**Comment by mcuiobroker** [comment]
Es wird nur der Hintergrund angezeigt.

**Comment by mcuiobroker** [comment]
Man muss die App einmal deinstallieren und dann neu installieren. Dann geht es.
