### ISSUE TITLE
Geräte-Bezeichnung in Klammern und Möglichkeit Titel auszublenden

### ISSUE THREAD

**Issue by mandragora666** [Zefau/ioBroker.jarvis#263]
Hallo Zefau

Mir ist aufgefallen das mit der beta.55 bei den Bezeichnungen sich Klammern hinzugefügt haben.
![image](https://user-images.githubusercontent.com/73381262/97166248-3f003700-1785-11eb-875e-d9ac0b5b674f.png)

Meiner Meinung nach war das zuvor nicht oder irre ich mich ?

Weiter hätte ich noch eine Frage zu selbst angelegten Geräten.
Habe meinen 3D Drucker angelegt und ein paar Werte eingebunden die ich mir gerne anzeigen lassen möchte.
Nun steht hier immer der Titel vom meinem Gerät davor.
![image](https://user-images.githubusercontent.com/73381262/97166416-81297880-1785-11eb-8137-a8e60a660e69.png)

Hat man hier eine Möglichkeit die Titel auszublenden da ich ja schon den Tab mit der Bezeichnung 3D Drucker Status betitelt habe und die einzelnen Bereich halt nur mehr mit Progress - Extruder Temperature etc. betiteln möchte.
Finde sieht dann irgendwie schöner aus.

Vielleicht hab ich das auch nur übersehen und es geht ja doch.
Dann bitte um kurze Info wo ich das ausblenden könnte.

Vielen lieben Dank schon mal
lg
mandragora

**Comment by Zefau** [comment]
Schwierig den richtigen Standard zu finden. Werden mehrere verschiedene Geräte kombiniert ist es sinnvoll den Geräte Namen zu zeigen. Werden mehrere Datenpunkte eines Geräts verwendet reicht das nicht und das State Label muss mit rein.

Überschreiben kannst du es in der Widget Konfiguration. Die Angabe dort sollte unverändert übernommen werden.

**Comment by mandragora666** [comment]
Alles klar.. verstehe.
Hab das irgendwie in der Widget Konfiguration zwar gefunden aber funktioniert bei mir irgendwie erst wenn ich es beim zweiten mal Eintrage. Dann wird das übernommen.

Wenns so geht bin ich wieder vollkommen zufrieden :-D

Danke 
lg
mandragora

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/217
