### ISSUE TITLE
[3.2.0-beta.10] Windows App -> Zitternde Widgets

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2630]
- Bei erstmalige Start werden MAP Widgets nicht angezeigt

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8e252a6c-e492-4f87-aa4f-82b25a5cb4fc)

-  wechselt man dann auf anderen TAB und zurück erscheinen die "zitterenden" Widgets und die MAP Widgets werden angezeigt.

![windowsApp-Fehler ZitterndeWidgets](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/7e53b9e1-15b7-4f73-bce7-c8d95225ce9b)

**Comment by Zefau** [comment]
besteht das Problem noch?

**Comment by mcuiobroker** [comment]
Wollte es probieren mit beta.38 windows fehlt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/b44777d6-c8bd-467b-8abd-bd235381303a)

**Comment by mcuiobroker** [comment]
Mit v3.2.0-beta.38 keine zitterende Widgets mehr. Passt. Danke.
