### ISSUE TITLE
Warum wird 3.1.9 nicht in stable Repo übernommen

### ISSUE THREAD

**Issue by reutli** [Zefau/ioBroker.jarvis#2631]
Hi,

ich habe 3.1.9.beta.2 am Start weil man mir geraten, wegen Problemen hat auf die Github Versionen umzusteigen. Eigentlich möchte ich aber in der Prod stable Versionen haben...
Bei der Durchsicht ist mir aufgefallen, dass es jetzt schon 3.2.x.alpha gibt. Warum wir ddenn die 3.1.9 nicht ins Stable-Repo übernommen?

Es wäre doch richtig uns schön, wenn weiterentwickelte stabile Versionen auch ins Repo übernommen werden.

Oder habe ich beim Konzept was falsch verstanden?
Aktuell weiss ich nicht, welche Version ich einigermaßen "ungestraft" updaten kann.

**Comment by mcuiobroker** [comment]
Ich vermute es hat was mit dem häuslichen Umzug von Zefau zu tun. Es wurde da der Server auch neu aufgesetzt. Weiterhin sind der Version 3.2.0 nochmal Dinge komplett umstrukturiert worden, um eine schnellere Performance zu erhalten. Dadurch sind aber auch einige (viele) fehlerhafte Kleinigkeiten entstanden, die nun behoben werden müssen. siehe Issues.
Die beste Version zurzeit ist die genutzte v3.19-beta.2.

**Comment by reutli** [comment]
Hi,
danke, wäre es dann aber nicht folgerichtig, die 3.1.9.beta.2 in den stable zu nehmen, damit man in iob wieder mit dem Adapter in den stable Pfad wechseln kann? Die 3.2.x kann dann ja wieder weiter entwickelt werden, bis stabil.
