### ISSUE TITLE
Homematic(IP), unbekannte Geräte und fehlende Datenpunkte 

### ISSUE THREAD

**Issue by TMatGH** [Zefau/ioBroker.jarvis#2634]
V. 3.1.8

Beim "Einlesen" von Homematic(IP)-Geräte sind diverse Devices unter "Sonstige" gelandet und damit auch keine passenden Datenpunkte angelegt worden => Nachricht an Entwickler

Hier die betroffenen Gerätetypen:

HM-RCV-50
HmIP-RCV-50	
HM-Sec-SC	
HM-CC-VG-1
HmIP-SWDO-2	
HM-OU-LED16
HM-LC-Sw1-PCB
HM-LC-Sw4-Ba-PCB
HB-UNI-SenAct-8-8-SC
HM-SwI-3-FM
HM-RC-Key4-2
HM-RC-4-2
HM-ES-TX-WM
HM-RC-12
HmIP-KRCA

Da es es sich hier um diverse Typen handelt, habe ich nicht von allen betroffenen Datenpunkten im iobroker Screen-Dumps gemacht. Falls JSON-Export-Dateien von den betroffenen Gerätetypen aus dem iobroker weiterhelfen, bitte kurze Info. Dann stelle ich diese zusammen.

**Comment by dahljoa** [comment]
Siehe auch meine Meldung:
https://github.com/Zefau/ioBroker.jarvis/issues/2625

**Comment by Zefau** [comment]
Unter https://github.com/Zefau/jarvis.adapters/blob/main/hm-rpc.js findest du die aktuelle Definition der hm-rpc Geräte.

Sofern etwas fehlen sollte, gerne per pull-request oder hier im Issue (dann übernehme ich es) im entsprechenden Format angeben.

**Comment by Zefau** [comment]
@TMatGH
