### ISSUE TITLE
scripts: hashchange Event wird nicht durchgelassen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2635]
```
window.addEventListener("hashchange", function(event) {
    console.log('Hash geändert');
});
```
Es erscheint trotz Tabwechsel keine Ausgabe.

**Comment by Zefau** [comment]
https://github.com/vuejs/vue-router/issues/1807
https://github.com/ecomplus/admin-marketplace/commit/9daa537b20448d765b6e53db68bc142ceae11fbb

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.3` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.3` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
