### ISSUE TITLE
Warum geht meine Pro Lizenz nicht mehr?

### ISSUE THREAD

**Issue by BlackandGold1** [Zefau/ioBroker.jarvis#2638]
Kaum das PayPal das Abo abgebucht hat geht nichts mehr. Die Überprüfung läuft positiv durch aber er speichert nichts.

**Comment by BlackandGold1** [comment]
Also auf Android und Windows hat sich das Problem erledigt. Nur auf mein IPad  Pro bin ich nicht pro. Leider weiß ich nicht was du mit  iob Upload Jarvis meinst.!?

**Comment by mcuiobroker** [comment]
Hat sich dann erledigt, wenn es auf Andriod und Windows läuft.
ipad neu gestartet?

**Comment by BlackandGold1** [comment]
Probier ich mal…

**Comment by BlackandGold1** [comment]
Unglaublich. Cache löschen in Safari war es. Danke für die Tipps und deine Zeit…. Super lieb und mach weiter so🙏😇

**Comment by mcuiobroker** [comment]
Dann bitte schließen.
