### ISSUE TITLE
[v3.2.0-beta.10] addToHistory erst bei erneuter Aktivierung im JSON

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2639]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/54bab7db-d0af-44a6-9291-ef863c7f9ee7)

Jarvis erkennt, dass bei dem DP die History eingeschaltet ist und erkennt auch den Adapter, aber es wird auch bei nachfolgendem Speichern nicht im JSON gespeichert.

addToHistory wird JSON erst aktualisiert, wenn man den Hstory-Adapter abwählt und wieder auswählt und speichert, falls dieser im System (ioBroker) schon aktiviert ist.

Dies sollte automatisch geschehen, damit man auf die JSON-Property zugreifen kann.

**Comment by Zefau** [comment]
Ich versteh es nicht so ganz glaube ich.

Also im JSON bleibt es nur kurzfristig - das ist richtig. Im JSON speichere ich temporär, dass der Datenpunkt zu einem History-Adapter hinzuzufügen ist.

Beim Speichern wird dies dann umgesetzt. Führend ist nach dem Speichern aber nicht mehr jarvis, sondern die jeweiligen History-Adapter.

jarvis lädt dann beim Start direkt zur Laufzeit aus den History-Adapter die dort hinterlegten Datenpunkte.
