### ISSUE TITLE
Nach Update auf die Beta-Version startet JARVIS nicht mehr.

### ISSUE THREAD

**Issue by dahljoa** [Zefau/ioBroker.jarvis#2640]
Ich habe seit ein paar Wochen erfolgreich mit JARVIS meine SmartHome-Konfi erstellt. Da die Expert-Fkt. nicht funktionierte habe ich von V3.1.8 auf die neueste Beta-Version aktualisiert. Seitdem geht nichts mehr unter JARVIS. Ich habe dann die Version V3.1.8 wieder installiert. iobroker läuft, die Adapter, Instanzen, Objekte sind vorhanden, doch JARVIS startet nicht mehr.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/5d2e2b73-4036-434e-aec2-3b412028ae69)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/66470936-6759-4e98-bf76-3d82a543e012)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/1feda6d9-d5f1-4dc7-aea4-7fb73e4df966)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/883b1c66-7aa4-4842-9f01-e439af53fdd6)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/2091579a-40bc-44a7-9e30-604e3b3462e2)

Andere Fehlermeldungen bzgl. Web-Port und Socket-Port bekomme ich im Moment nicht mehr auf den Bildschirm.

Ich habe ein Synology-NAS DS224plus mit Docker/Portainer-Image und buanet/iobroker:latest.

Wie bekomme ich diese JARVIS-Konfiguration unter V3.1.8 mit meiner erstellten Konfiguration wieder zum Laufen?
Was kann oder muss ich machen?
Kann mir einer dabei helfen?

**Comment by mcuiobroker** [comment]
Web-Adapter neu starten
Cache vom Browser löschen

**Comment by dahljoa** [comment]
zur Ergänzung:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/0466d08f-fd24-44f3-b9f5-2ee76928cd06)

**Comment by mcuiobroker** [comment]
Installiere mal wieder die aktuelle Jarvis-Version

**Comment by dahljoa** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/cf63ea56-7d87-479c-9618-6b0c8da497ac)

Container, ioBroker alles neu gestartet. JARVIS V3.1.8 installiert, Connection kommt nicht zustande. Die anderen Vorschläge gehe ich morgen (also in ein paar Stunden) durch. Danke erstmal.

**Comment by mcuiobroker** [comment]
Kann auch nicht, da Daten von v3.2. drin sind

**Comment by dahljoa** [comment]
Ich habe alle Neustarts ausgeführt und den Browser-Cache gelöscht. Bin dann erstmal bei V3.1.8 geblieben und habe ein Backup von vor 3 Tagen installiert, damit läuft JARVIS mit meinen Einstellungen jetzt wieder.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/2a1c7ccd-fd1e-4fcf-9b8f-f315f8a0952e)

Leider funktioniert der Expert-Mode im JARVIS nicht. Wie komme ich daran?
 
Auf jeden Fall hier einmal vielen Dank für die Unterstützung.

**Comment by mcuiobroker** [comment]
Normalerweise mit
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/f111db1f-a005-408f-95f9-6c10231b9cbb)
Welcher Browser? Bei mir funktioniert es mit Edge.

**Comment by dahljoa** [comment]
Expert-Mode funktioniert bei mir **nicht** auf Windows11-PC mit Edge, Firefox, Chrom auch nicht auf einem Win11-Laptop mit lokaler ioBroker-Installation und auch nicht auf einem iOS-Tablet (Zugriff auf zentralen ioBroker) mit Edge, Firefox oder Safari.
Habe Cockies, etc. gelöscht und alles zugelassen was möglich ist.
Da müsste es doch eine zentrale Einstellung sein, die dies verhindert, oder? 
Oder geht es erst wieder mit einem Update auf V3.2Beta?

Auf welcher Console (habe ich noch nicht gebraucht) soll ich ein Upload durchführen und was passiert dann?

Was hat es mit der Signature in den JARVIS-DPs auf sich? Bei mir stehen verschiedene Versionen mit unterschiedlichen Signaturen.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/90077d2f-7f6a-4b45-b7c5-f538ecb136e8)

**Comment by mcuiobroker** [comment]
>Was hat es mit der Signature in den JARVIS-DPs auf sich?

Bei Update auf v3.2.0-beta.10 kommt es vor, dass die signature für bestimmte DPs (CSS, scripts) nicht gesetzt wird. Diese ist aber für diese DPs (CSS, scripts) Voraussetzung, damit die v3.2.0-beta.10 laufen kann. Die DPs werden sonst als noch nicht "upgedatet" erkannt. Somit wird wieder ein Reload durchgeführt. Und immer weiter....

>Oder geht es erst wieder mit einem Update auf V3.2Beta?

Kann ich nicht sagen, da es bei mir (Windows 10, Frontend) immer funktioniert.
Ich probiere es gleich mal auf Windows 11.

>Auf welcher Console

Wo ist ioBroker installiert? Puuty-Console.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/b3491663-0ac4-4909-a442-bcc624ffe965)

**Comment by dahljoa** [comment]
Das mit dem "reload und ... immer weiter ....." sah gestern genau so aus. Aber ich kann doch sicherlich nicht irgendeine Signatur eintragen und macht das Sinn bei mir im System?

Console gefunden!
![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/413e26c2-968d-4645-a6ff-a7aa8409e467)

Welche JARVIS-Version wird dann mit "iob upload jarvis" geladen, wird es dann besser oder handele ich mir wieder mehr Ärger ein? Hast du einen Link zu einer passenden Doku für mich bevor ich starte?

**Comment by mcuiobroker** [comment]
> Aber ich kann doch sicherlich nicht irgendeine Signatur eintragen

Doch man kann irgendeine eintrag, da es darum geht das die Objekt Eigenschaft da ist. Sie wird sowieso permanent geändert.

> Welche JARVIS-Version wird dann mit "iob upload jarvis" geladen

Die aktuell installierte Version.

**Comment by dahljoa** [comment]
Seit den Problemen gestern habe ich seit heute in unregelmäßigen Abständen zusätzlich "xhr poll error", das war in den letzten Wochen nie der Fall. Nach 20-30 sec. kommt die Verbindung dann wieder als wäre nichts geschehen.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/99aedf9f-93a3-4eb8-96cd-96c566afad97)

**Comment by mcuiobroker** [comment]
Bezgl. Expert-Mode gibt es beim Umschaltversuch eine Meldung im LOG (F12)?

**Comment by dahljoa** [comment]
Moin, sind die aufgelisteten Fehler im o.g. Link (error-xhr-poll-error) alles mögliche Ursachen für diese Fehlermeldung? Ich habe einige Fehlermeldungen (Warnungen)  aus dem hue-Adapter die auf nicht eindeutige DPs hinweisen oder min/max-Wert-Überschreitungen auflisten. Die meisten konnte ich schon gestern Abend korrigieren, werden nicht mehr gemeldet.

Doch vor einer Stunde hat sich die JARVIS-Instanz verabschiedet und lässt sich nicht mehr starten. 
host.iobroker | 2024-04-25 13:24:28.654 | warn | instance system.adapter.jarvis.0 terminated due to SIGABRT
Ich habe heute keine Änderungen gemacht, lediglich von drei verschiedenen Browser auf verschieden Geräten JARVIS aufgerufen und zw. den Seiten gewechselt.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/07420b16-27ff-4366-9026-6252e7e2eaa6)


PS: ein LOG im JARVIS welches ich mit F12 öffnen könnte oder sonst wie ist mir bisher noch nicht aufgefallen!?

**Comment by mcuiobroker** [comment]
Dein System hat zu wenig Speicher.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/437af6eb-5e91-42eb-a4ca-0e3096a4745b)

**Comment by dahljoa** [comment]
Moin,
bei einem 6 GB-RAM System und 4 CPUs sind der Speicher und die CPU wohl nicht das Problem. Erst seit dem missglückten JARVIS-Update auf 3.2 und dem Downgrade auf 3.1.8 habe ich das diesen kurzzeitigen Ausfall.
Nachdem ich nun alle Warnungen aus dem hue- und CCU3-Instanzen beseitigen konnte, einen Resteintrag JARVIS.1 gelöscht habe und Signaturen eingetragen habe läuft das System weitestgehend stabil. Weitestgehend bedeutet, dass ich den "xhr poll error" erzeugen kann, wenn ich in meiner JARVIS-App unter SETTINGS den ADAPTER-LOGS nutze, der ioBroker.log anzeigen soll. Hier scheint seit meinem Updateversuch etwas schief zu laufen.
Man sieht an der Speicherauslastung, dass es genau zu dem Zeitpunkt eine extreme Last gibt und es zu dem Speicherüberlauf kommen kann. Also eine Programmschleife im JARVIS die Ursache sein dürfte.

![iobroker - Speicher und CPU](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/4a961c91-94d4-4788-98c9-71685094d08c)

![iobroker-container Memory und CPU Last - peaks beim Oeffnen der settings-Seite](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/381beaca-ebb9-47d6-983f-79784f8a3a64)


PS: ein LOG im JARVIS welches ich mit F12 öffnen könnte oder sonst wie ist mir bisher noch nicht aufgefallen!?

**Comment by mcuiobroker** [comment]
F12 gibt es in jedem Browser (Windows)  oder Apple (Mac (Cmd + Option + J))
Beispiel MS Edge
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/65688b53-c916-401e-80a8-33a34ab49939)

**Comment by dahljoa** [comment]
Sorry, da habe ich etwas falsch verstanden, ich habe nach einem LOG im Jarvis gesucht.

Eine Fehlermeldung taucht bei mir nach jeder Betätigung des "Expert Mode-Buttons" auf , sie lautet "UNKNOWN STATE Settings".
Damit kann ich allerdings NICHTS anfangen, gibt es hier einen Hinweis warum der "Expert Mode" nicht funktioniert?
Oder ist die Meldung davor "Uncaught SyntaxError: Unexpected token ":" at useCustomTag ......" eine mögliche Ursache.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/1723e81a-6cee-4afe-9fc9-d1ed7af764c6)

**Comment by mcuiobroker** [comment]
Zeig mal bitte Deine Browserzeile, wenn die Konfiguration aufrufst.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/62d5bc21-b828-4027-b8ba-9da887cf00f6)
Da scheint es in einer Definition ein Problem zu geben.
Seitentitel: SH_Kh34 ? 
Ich weiß nicht welcher Fehler er (Zefau) da ausgeben lässt

Wie sieht der DP in ioBroker aus? jarvis.0.settings.configExpertMode

**Comment by dahljoa** [comment]
Moin,
hier der Screenshot nach Aufruf der Seite.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/eb63f6e2-13bf-4469-b9ec-25eddeb93e35)


Und hier noch ein Screenshot nach Betätigung des <> ExpertMode.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/7922c159-6d2e-40f8-854c-54fb7f46c2ab)

Den DP configExpertMode gibt es bei mir nicht!!!!

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/ef01e95c-abb4-4ba9-98d4-94ec67978183)

**Comment by mcuiobroker** [comment]
Hattest du das mit dem Upload gemacht?
Ich vermute er noch Teile vom Update auf v3.2.0-beta.10 drin und fragt deswegen nach configExpertMode.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/7e3c15df-db1b-48da-9f3a-3c38ebcf127b)

useCustomTag kenne ich nicht.

**Comment by dahljoa** [comment]
Moin, den Upload über die Kommandozeile hatte ich nicht gemacht, sondern nur über das normale Adapter-Inst-Menue auf 3.1.8 zurück. Einen Eintrag von V3.2 sieht man noch bei den DPs hinter CSS.

Ich habe einmal eine lokale Installation auf Windows11 durchgeführt mit ioBroker und JARVIS 3.1.8. Auch dann gibt es sofort wieder den gleichen Fehler "configExpertMode undefined true" wenn ich den <>ExpertMode schalten will. Einen DP configExpertMode gibt es auch bei der Neuinstallation nicht. Hier scheint doch schon auf github etwas falsch zu laufen.

Bzgl. useCustomTag suche ich mal in meiner Konfi nach einem Fehler ( : an falscher Stelle).

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/4472d04b-b631-475f-ac74-133d05359eb9)

**Comment by mcuiobroker** [comment]
Setz doch mal den DP. Upload in den Objekten.
[jarvis.0.settings.configExpertMode.json](https://github.com/Zefau/ioBroker.jarvis/files/15193146/jarvis.0.settings.configExpertMode.json)

**Comment by dahljoa** [comment]
Moin,
das sieht gut aus. Ich habe die Datei im ioBroker als Objekt unter JARVIS hinzugefügt, den DP gibt es dann mit dem Wert (null). Ich habe den Wert auf true gesetzt, JARVIS neu gestartet und die WebSeite neu geladen: ExpertMode funktioniert!!!!
Ob der DP auf true oder false steht, spielt wohl keine Rolle. Bei beiden Werten funktioniert nun der ExpertMode.

Die Programmstelle "useCustomTag" gibt es bei mir, ich verstehe die Syntax jedoch nicht genug und weiß nicht ob der ":" an der richtigen Stelle ist. Vielleicht siehst du das? Ich suche mal, an welcher Stelle ich das wohl "eingebaut" habe.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/162341803/782d05fd-aeb3-4dc1-ad96-4bc8964ca325)

**Comment by mcuiobroker** [comment]
scripts hast du ja nicht im Einsatz, deswegen bleibt dort nur noch die Styles prüfen.

**Comment by dahljoa** [comment]
Moin,
die Fehlermeldung im useCustomTag konnte ich beseitigen. 
Unter "jarvis.0.scripts" hatte ich während der Fehlersuche Version/Signature manuell eingetragen!
{   "version": 3,  "signature": 7545630428782103 }
Ohne diesen Eintrag verschwindet der Fehler im useCustomTag wieder!

Damit habe ich im Moment ein stabiles System ohne Fehlermeldungen!
Vielen, vielen Dank für deine Unterstützung!

**Comment by mcuiobroker** [comment]
Gerne. Dann bitte Issue schließen.

**Comment by dahljoa** [comment]
Alles klar, vielen Dank für den Support!
