### ISSUE TITLE
Stable

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#2641]
Gibts schon ein Plan wann die nächste Stable released wird ? Ich glaube die letzte is doch sicher schon nen Jahr her ? 

Gruss

**Comment by StephanTexxpro** [comment]
Ist das Projekt noch aktiv?

**Comment by Zefau** [comment]
Jap. Geht nun weiter.

**Comment by Zefau** [comment]
> Gibts schon ein Plan wann die nächste Stable released wird ? Ich glaube die letzte is doch sicher schon nen Jahr her ?

Aktuelles Release ist bereits beta. Wenn die wesentlichen Bugs raus sind, geht es ins stable. Muss nur gerade für mich selbst rausfinden, was aktuell die wesentlichen Bugs sind.
