### ISSUE TITLE
[v3.2.0-beta.10] Mehrfach angelegte Kopien von jarvis DPs im Cache - unterschiedliche Namespaces für die gleiche Instanz

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2642]
Nutzt man für den Start der Instanzen den Instanz-Link aus den Instanzen, so werden die "korrekten" Namespaces genutzt.
Sobald man dann ein "Reload" (F5) durchführt, wird im Cache ein neuer Namespace ('jarvis.#xxxx) mit anderen "signatures" angelegt.
Die dort genutzten "signatures" passen nicht mit den signature aus den gespeicherten Jarvis-DPs überein.
Weiterhin werden die url im Cache falsch gesetzt. Teilweise gibt es im Cache für die Instanz 0 mehrere Namespaces, obwohl dieser Namespace zu einer anderen Instanz gehört.
Dies führt dazu, dass Instanzen nicht mehr korrekt geladen werden, wenn man mehrere Instanzen nutzt.

So bald man wieder alles schließt und von vorne startet mit den Instanz-Links, sind die Cache-Namespaces korrekt zugeordnet.
Man darf dann aber kein Reload durchführen.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9a463d25-049b-4e6b-bd7c-2a68515a40fb)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6b09ed84-71a2-4bd8-b944-f8b6ba2a56fb)

Schaut man sich die Einträge an ergibt sich der Ausdruck.
Im Speicher wird der Namespace als einer von Instanz 1 geführt , gehört aber zur Instanz 0 und der dort aktive Namespace.

**Comment by mcuiobroker** [comment]
Wenn möglich, Namespace als Variable zur Verfügung stellen, da man sonst alle vergleichen muss. Danke.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0ef3df8f-e66e-4323-8209-f5984e62d68e)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.31` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.31` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Variable fehlt noch, ich kann das Log nicht auslesen.
Anders wie kann ich auf die internen Daten für devices, widgets usw zugreifen (nur lesend), schreiben würde ich über Socket.

**Comment by Zefau** [comment]
Variable kommt mit der nächsten beta.

Wofür brauchst du in jarvis die devices, widgets und co.?
Bitte denk dran: Es ist besser Logik / Skripte in ioBroker.javascript zu haben. Das ist viel performanter als in jarvis.

**Comment by mcuiobroker** [comment]
Beispiel 
Darstellung für Widgets auf dem Handy, die nebeneinander dargestellt werden sollen

https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/scripts-3.1.x-pro/widgets/widgetgroup
Dort brauche ich die Info vom Layout
Und wenn es die Jarvis-DPs schon im Cache gibt, wäre es sinnvoll direkt darauf zurückzugreifen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.39` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.39` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
