### ISSUE TITLE
Socket Issue after Upgrade to Beta 12

### ISSUE THREAD

**Issue by StephanTexxpro** [Zefau/ioBroker.jarvis#2644]
After upgrade to beta.12 jarvis fails to load with 

`Failed to construct 'WebSocket': An insecure WebSocket connection may not be initiated from a page loaded over HTTPS.`

In the log I get 

`jarvis.0 | 2024-06-01 14:37:21.200 | error | Error opening web socket: this.loadNotifications is not a function`

Cache deleted, private browsing checked.

**Comment by sammie76-2** [comment]
Same here. Jarvis Beta 12 could not be started. Error is: "Error opening web socket: this.loadNotifications is not a function",

**Comment by StephanTexxpro** [comment]
@Zefau - could you please check, downgrade does not work for me. Thx!
