### ISSUE TITLE
Menu Breakpoints  auf Tablet. 

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#2647]
Schön wäre evtl auch wenn men das Seiten Menu immer offen haben lassen kann, je nach Device, also entweder nur die Icons oder Icons mit Text. 

![image](https://github.com/Zefau/ioBroker.jarvis/assets/22169074/694737d9-370d-4866-969d-37990ced47fd)

ungefähr so. Jedoch klappt das komplett weg auf dem Tablet.

_Originally posted by @ma-gu-16 in https://github.com/Zefau/ioBroker.jarvis/discussions/2645#discussioncomment-9644153_

**Comment by ma-gu-16** [comment]
samsung tab a9+

1920 x 1200 Pixels  auf 11 zoll

Desktop scheint mir das Menu  soweit offen zu sein das man die icons sieht und mousover zeigt den inhalt. 

Wäre schön wenn man bei 1920 zumindest die icons sieht und ggfl. darüber den Hamburger um alles zu öffnen. 
Ich vermute mal weil das ganze via mouseover umgesetzt ist und das aufm tablet ja nicht geht. 

Naja evtl gibts da ne Lösung für.

**Comment by Zefau** [comment]
![grafik](https://github.com/user-attachments/assets/16e44bfc-f540-4b8c-9e7d-ae103d0ed01f)

**Comment by ma-gu-16** [comment]
> ![grafik](https://private-user-images.githubusercontent.com/14368811/350794067-16e44bfc-f540-4b8c-9e7d-ae103d0ed01f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MzIyOTAsIm5iZiI6MTcyMTYzMTk5MCwicGF0aCI6Ii8xNDM2ODgxMS8zNTA3OTQwNjctMTZlNDRiZmMtZjU0MC00YjhjLTllN2QtYWUxMDNkMGVkMDFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzIyVDA3MDYzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0MmU2MzkzZTNlNDU2YzVkNDU5ZjU3Nzg5YjA0N2NjNWFhZjNhMjg0NWUxZjc5YWFhZWE1NDYwMTVhMDI4NGUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8mmCIJrsYwrsnzugJnVMoELPmxrZtJgLxEpMFJ0_R4o)

das habe ich bereits aktiv. bringt aber nix auf dem tablet. auf dem desktop ist es wie gewünscht.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.58` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.58`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Zefau** [comment]
@ma-gu-16
