### ISSUE TITLE
Neuer Datatype für LightColorBody 

### ISSUE THREAD

**Issue by magooffm** [Zefau/ioBroker.jarvis#2648]
Hi,

mir ist aufgefallen, dass mein MDT AKD-0424R2.02 KNX LED Controller für die RGB-Werte nur eine JSON-Datenstruktur im DP akzeptiert bzw. liefert.

Sieht dann als Beispiel so aus: {"red": 82,"green":0,"blue":163}

Damit kommt das LightColorBody-Element noch nicht zurecht - meine aktuelle Lösung ist, die Werte zur Anzeige in den DP-Eigenschaften in Hex umzuwandeln und anschließend in einen Helper-DP zu schreiben und von dort über ein Script (außerhalb von Jarvis) wieder in das JSON-Format zu wandeln und dann in den "richtigen" DP zu schreiben. Funktioniert, ist aber nicht besonders schön.

Mir fallen dazu zwei mögliche Lösungen ein:
1. Das LightColorBody-Element unterstützt einfach den neuen Datentyp
2. Eine Möglichkeit zur Transformation direkt aus Jarvis heraus, bevor ich den durch das Element generierten Wert in den Datenpunkt schreibe -> Evtl geht das ja schon und ich habs nur noch nicht verstanden?

Jarvis 3.1.8
OpenKNX 0.9.0

Danke vorab!

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.47` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.47`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Zefau** [comment]
@magooffm
