### ISSUE TITLE
[v3.2.0-beta.10] scripts: eigene Funktionen, werden nicht schnell genug geladen -> evtl Preload scripts?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2652]
Nutzt man in den Datenpunkt-Eigenschaften, eigene Funktionen aus scripts, werden diese nicht schnell genug geladen.
Vielleicht sollte man für diese Funktionen ein eigenen Bereich setzen, oder als PreLoad-Funktion für definierte Funktionen.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/4b8ab05d-3b30-4432-8611-3e00b79ce173)

**Comment by Zefau** [comment]
@mcuiobroker das sollte inzwischen behoben sein?

**Comment by mcuiobroker** [comment]
Nein. Eigene Callback-Funktionen werden nicht erkannt.
Ist auch bei Anzeigevariante so.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2777
