### ISSUE TITLE
[v3.2.0-beta.10] clients: `jarvis.0.clients.xxx.browserConsoleInLog` funktioniert nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2653]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/1de7c74a-2890-474a-8f9d-fc97df1d25ba)
Konsolen-Log ist eingeschaltet für das Device und für alle, trotzdem wird kein LOG für das device angezeigt.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/d14abe78-6ce5-46b4-a1c2-ce0cc713eb6b)

Dort sollte aber wesentlich mehr stehen
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/87d8de18-fc0a-48a7-af90-ce0670ab8166)

**Comment by mcuiobroker** [comment]
Dies wäre jetzt wichtig, da man dann besser feststellen kann, warum die APP nichts anzeigt?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.57` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.57` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
`debug `eingeschaltet -> es kommen nur Warnungen an, normalerweise steht auch im Browser-Log, von welchem Script der Log-Eintrag kommt. (ist auch nicht mehr da)
Browser-Log
![image](https://github.com/user-attachments/assets/0f0e9254-3c8e-4261-9bc5-6be11eebfe63)

iobroker-Log
![image](https://github.com/user-attachments/assets/e2984e2a-bf77-42bc-9b8b-e59fae2da34a)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Funktioniert leider nicht. Nach Reload kommt nur dies
![image](https://github.com/user-attachments/assets/07fd4979-f6b6-4865-a867-350967659456)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.59` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.59` should fix the bug - please verify. If the bug has been solved, you may close the issue.
