### ISSUE TITLE
Datenpunkt Formatierung z.B. via properties.value : "val=>val.toFixed(2)" klappt nicht mit   "actionElement": "InputAction"

### ISSUE THREAD

**Issue by Coalado** [Zefau/ioBroker.jarvis#2656]
Ich habe folgenden Datenpunkt in einer Statelist:

```
  "requestedLiter": {
        "_updated": 1717926081246,
        "_created": 1717926081246,
        "stateKey": "requestedLiter",
        "label": "Wasser anfordern",
        "showState": false,
        "state": "mqtt.1.waterbox3.relais.hecke.requestedLiter",
        "unit": "L",
        "icon": "water",
        "properties": {
          "value": "val=>val.toFixed(2)"
        },
        "actionElement": "InputAction"
      },

```

Durch  "actionElement": "InputAction" habe ich in der Statelist ein Eingabefeld (und im Popup).

Die Formatierung "value": "val=>val.toFixed(2)" funktioniert allerdings nicht im Eingabefeld.

**Comment by Zefau** [comment]
Ist `InputAction` auf `value` konfiguriert?

**Comment by Zefau** [comment]
@Coalado

**Comment by Coalado** [comment]
Sorry für die Verspätung. 

`
  "InputActionConfig": {
                        "requestedLiter": {
                            "val": "value"
                        }
                    }
`

hat das Problem gelöst - kann also geschlossen werden hier.
