### ISSUE TITLE
[v3.2.0-beta.13] Beim Hoch / Runterwischen hakelt es auf Phone und Tablet, Edge Handy -Ansicht verkleinert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2657]
Fully Kiosk Browser und Edge:
Die Ansicht läuft beim Hochwischen nicht sauber durch.
Chrome und Firefox läuft gut.

Edge Handy
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e748b5e1-e9dc-49b8-a3e2-374adf0cafc7)

**Comment by Zefau** [comment]
Hast du das Problem mit der aktuellen Beta noch?

**Comment by mcuiobroker** [comment]
Ja, ist noch da.

**Comment by mcuiobroker** [comment]
@media zieht da anscheinend nicht?

Anzeige Edge
![image](https://github.com/user-attachments/assets/511e6d01-933e-4f4a-8415-515dc62835c2)

Anzeige Chrome
![image](https://github.com/user-attachments/assets/4a2493b6-b267-465b-ac03-7cb9a1813b6c)

**Comment by mcuiobroker** [comment]
v128.0.2739.72

**Comment by mcuiobroker** [comment]
Habs gefunden, falsche Einstellung Desktop-Website-anzeigen war eingestellt.
