### ISSUE TITLE
[v3.2.0-beta.14] Geräte-DP: State Explorer findet den eingetragenen State nicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2658]
![stateExplorerFindetNicht gewähltenState](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/cca16b7a-2721-4660-91b4-023d25edaef7)

EDIT: 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c28e579d-0013-4c9b-af2e-593fcdfb2cd8)

**Comment by Bernd9000** [comment]
Hab ich hier auch schon bei beta.10

Fehler in der Browser Konsole:

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/2f129ee5-4d57-4fe7-8216-71ac6eb0d274)

**Comment by mcuiobroker** [comment]
Kein Fehler mehr, aber trotzdem genauso wie vorher, er wird nicht gefunden.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.16` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.16` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Jetzt möchte er ein Passwort haben?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/9199b7b3-720f-42be-8119-1ca36fcf1e4b)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6797f966-1b31-4dff-b167-723a3ef2f60f)

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/issues/2288#issuecomment-2181501133

Wie ist deine Adapter-Konfiguration?

**Comment by mcuiobroker** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/442a8d79-6e06-44d5-9ee1-904ff20243b8)

**Comment by Zefau** [comment]
Uploade mal den Adapter bitte

**Comment by Zefau** [comment]
Fix kommt, aber bitte zu dem Fehler das andere Issue nutzen.

**Comment by mcuiobroker** [comment]
Der DP wird jetzt gefunden, früher ging dies aber schneller?

**Comment by mcuiobroker** [comment]
Passt. Danke.
