### ISSUE TITLE
[v3.2.0-beta.14] Mouseover Layout bei kleinen Widgets zeigt nur Responsive Position -> Module, items und height soll gezeigt werden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2660]
Es soll aber Module, items und height angezeigt werden, da man es bei kleinen nicht sehen kann.
War früher auch so.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3a477f9f-a069-4634-ac5d-f3550d9c417e)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.15` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.15` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
