### ISSUE TITLE
[v3.2.0-beta.14] Automatische Sicherungen bei DP-Änderung werden nicht durchgeführt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2661]
Letzte automatische Sicherung im Januar?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3d4cea66-dc07-461a-bfd9-cbb46711d14d)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.15` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.15` should fix the bug - please verify. If the bug has been solved, you may close the issue.
