### ISSUE TITLE
[v3.2.0-beta.15] MAP Klick auf die map vergrößert plötzlich das Widget

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2662]
Aufgrund der Größe schlecht zu sehen, Widget hat eine Höhe von 3 und danach von 17 (881px)
scripts ausgeschaltet
![widgetMAPKlickvergrößert](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6247bff7-40e6-4478-8ad0-827a02967034)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.33` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.33` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Wird nicht mehr vergrößert. Passt. Danke.
