### ISSUE TITLE
[v3.2.0-beta.15} Fehleranzeige

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2663]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c62b12d1-79aa-4624-ade6-2ae9ae28fdc5)

**Comment by Zefau** [comment]
Hast du eine grobe Idee wo es herkommen könnte?

**Comment by mcuiobroker** [comment]
displayImage
```
 "a81b93c4-b63f-48a1-a7a7-30797e83df46": {
    "id": "a81b93c4-b63f-48a1-a7a7-30797e83df46",
    "config": {
      "url": "http://192.168.178.170/download/icons/HOME.png",
      "height": "30%",
      "width": "30%",
      "size": "contain",
      "repeat": "no-repeat",
      "refresh": 0,
      "refreshMethod": "whitespace"
    },
    "icon": "mdi:home",
    "title": "QR-CODE-HOME-GAST_WLAN",
    "module": "DisplayImage",
    "items": [],
    "hideTitle": true,
    "hideSeparator": true,
    "revision": "5df44"
  },
```

**Comment by Bernd9000** [comment]
Jo, hier auch Modul DisolayImage

Browser Console:


![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/a5045347-aa13-41b5-be2b-cb64e2a98449)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.31` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.31` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Sieht gut aus, Bild wird wieder angezeigt.
