### ISSUE TITLE
Failed mapping a recurring event of calendar : Invalid time value

### ISSUE THREAD

**Issue by sk8er-boi90** [Zefau/ioBroker.jarvis#2664]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
v3.2.0-beta.10

- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
Hier ist alles unauffällig

jarvis.0 | 2024-06-15 01:20:00.704 | warn | Failed mapping a recurring event of calendar : Invalid time value
-- | -- | -- | --
jarvis.0 | 2024-06-15 01:20:00.704 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.704 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.703 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.703 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.703 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.701 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.700 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.700 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.700 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.700 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.700 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.700 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.699 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.699 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.699 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.699 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.699 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.699 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.698 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.698 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.698 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.698 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.698 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.698 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.697 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.697 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.697 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.697 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.697 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.697 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.696 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.696 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.696 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.696 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.696 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.696 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.695 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.695 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.695 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.695 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.695 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.695 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.694 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.694 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.694 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.694 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.694 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.693 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.693 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.693 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.693 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.693 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.693 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.692 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.692 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.692 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.692 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.692 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.691 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.691 | warn | Failed parsing a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.642 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.642 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.641 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.641 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.631 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.631 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.631 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.630 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.630 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.630 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.630 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.629 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.629 | warn | Failed parsing a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.623 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.623 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.623 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.622 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.622 | warn | Failed mapping a recurring event of calendar : Invalid time value
jarvis.0 | 2024-06-15 01:20:00.621 | warn | Failed parsing a recurring event of calendar : Invalid time value

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Das Kalenderwidget wurde bereits gelöscht und neuangelegt.
Es handelt sich um einen google Kalender.
Des weiteren wurde der Cache etc. mehrfach gelöscht. 

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2519
