### ISSUE TITLE
Drop support of web adapter and thus web-port

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2666]
Solely rely on jarvis specified port (`8400`)

**Comment by mcuiobroker** [comment]
Bedeutet? 8082 funktioniert dann nicht mehr, nur direkt 8400?

**Comment by Zefau** [comment]
fixes https://github.com/Zefau/ioBroker.jarvis/issues/2642

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.21` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.21` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Bei mir ist der Port 8082 im Zusammenhang mit Jarvis beta.>45 nie wieder aufgetaucht.
Denke, kann geschlossen werden.
