### ISSUE TITLE
[v3.2.0-beta.15] Fehlerhafte DPs werden erst bei 2. Anzeige erkannt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2667]
Nach Reload erhält man die Ansicht mit den korrekten Icons, wenn die DPs errreichbar wären.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ed0456e6-734f-426b-b670-50ad376e32b5)
 So sollte es aber nicht aussehen.
Erst nach TAB-Wechsel und nochmaligem Aufruf des TABs, erscheint die korrekte Anzeige mit den fehlerhaften DPs und dem korrekten Icon (Ausrufezeichen)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/cb3da7f5-a21e-4a7d-af90-e12a875e044f)

Prüfung scheint also erst später zu beginnen?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.39` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.39` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
v3.2.0-beta.39
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/dea9cfd3-574e-44f8-90d1-de95b2a52913)
Icon und Actions werden teilweise nicht angezeigt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6e2001bd-5f60-4a39-a9be-15afc63417c0)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.40` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.40` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Bekomme jetzt seit v3.2.0-beta.39 
Frontend wird kurz angzeigt und dann inkonsistent
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/20057dc3-279f-494c-91eb-cfbef1a78134)

**Comment by mcuiobroker** [comment]
Cache löschen war notwendig. 
Problem ist die Web-Adresse
`http://192.168.178.150:8400/jarvis/index.html#/home0/home0`
Normal ist 
`http://192.168.178.150:8400/jarvis/index.html#/home0`

**Comment by mcuiobroker** [comment]
Passt. Danke.
