### ISSUE TITLE
[v3.2.0-beta.15] Änderungen in StateList speichern nicht

### ISSUE THREAD

**Issue by ScumbagSteve** [Zefau/ioBroker.jarvis#2668]
Ich habe in beta15 ein neues StateList widget erstellt.
Das Widget enthält das selbe Gerät mehrfach, mit unterschiedlichen Datenpunkten:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/8447146/7f3ead2d-d140-468d-937c-b56c285f3ef3)

Wenn ich eine Änderung an einem Gerät vornehme (z.B. den Datenpunkt ändern möchte) werden die Änderungen nicht gespeichert.
Es spielt dabei keine Rolle ob ich "direkt" auf das Widget zugreife, oder über den Menüpunkt "Layout" das Widget bearbeite.
Löschen und hinzufügen neuer Geräte funktioniert, aber ich kann die Default-settings eines Gerätes (mit dem sie ins Widget kommen) scheinbar nicht ändern.

**Comment by mcuiobroker** [comment]
Aber die Body States und Action States müssten doch unterschiedlich sein, sonst wird ja immer das gleiche angezeigt.
Du hast überall "Garten" drin?

**Comment by ScumbagSteve** [comment]
Ja, "Garten" ist der Standard, wenn ich das Gerät hinzufüge. Das möchte ich jetzt umstellen, kann es aber nicht speichern. 

Es speichert zwar laut GUI, aber wenn ich wieder in die Einstellungen gehe ist wieder überall "Garten" drin. 
Die Oberfläche selbst zeigt auch keine Umstellung.

**Comment by ScumbagSteve** [comment]
Widgeteinstellungen wie z.B. "kompakte Ansicht" werden übrigens gespeichert. Nur das ändern von Geräteeinstellungen (auf Zeilenebene) scheint nicht zu greifen. 
Das obere Gerät habe ich auch erst mit beta14 angelegt - eventuell liegt das Problem auch dort.

**Comment by StephanTexxpro** [comment]
Kann das Problem bestätigen, neue Geräte können in der StateList angelegt werden, Änderungen werden nicht gespeichert.

**Comment by StephanTexxpro** [comment]
Ist auch in der beta.19 kaputt.

**Comment by StephanTexxpro** [comment]
Läuft wieder (Test mit beta.37) 
Danke!
