### ISSUE TITLE
[v3.2.0-beta.10, beta.15] Notification werden nicht gesendet (beta.10), werden nicht angezeigt (beta.15)

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2669]
Die Notifications werden nicht als Popup angezeigt. Auch nicht aus der Notification-Verwaltung.
 
```
[
  {
    "title": "<b><u>Lebensmittel-Warnung Heute</u></b>\n<b>Saibling Filet, 750 Gramm</b>\n<a href=\"https://www.lebensmittelwarnung.de/___lebensmittelwarnung.de/Meldungen/2024/05_Mai/240527_1_BW_Saiblingfilet/240527_1_BW_Saiblingfilet_Bild.png?__blob=normal&v=\">Bild-URL</a>\n\nGrund: Krankheitserreger",
    "id": "ba40a669-c7fe-45f3-9be9-d6932969f987",
    "ts": 1718890369562
  }
]
```
Andere Keys caption, display usw. werden nicht an das Objekt weitergegeben

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/20ea7fc7-daa1-4eaf-b4c6-57f6536c4ef8)
HTML wird auch nicht umgesetzt.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.17` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.17` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Weiter Passwort Abfrage
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/600d9bd4-bc55-49a4-9573-7c77cb111c1e)

**Comment by mcuiobroker** [comment]
Weiterhin kein Popup, da die KEYs im JSON fehlen
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ad49f95e-e2f0-4cd3-a7e0-b34642fe9745)

html wird korrekt angezeigt

**Comment by Zefau** [comment]
für Popup musst du `display: "popup"` angeben, siehe https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/notifications-pro#json-aufbau-notification-v3

**Comment by mcuiobroker** [comment]
Ja, der Display Key wird nicht übertragen.

**Comment by mcuiobroker** [comment]
Jo. Sorry.

**Comment by mcuiobroker** [comment]
Trotzdem kein Popup

**Comment by mcuiobroker** [comment]
Passt. Danke.
