### ISSUE TITLE
Feature: Triggern sekundäre Datenpunkte zuweisen

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#267]

**Comment by Zefau** [comment]
@duczz kannst du hier darstellen, wie du dir das vorstellst? Also funktionell als auch optisch.

**Comment by duczz** [comment]
Eigentlich wie die bisherigen sekundär Punkte auch.
Ich würd z.b. einem Switch drunter gerne den Batterie Prozentsatz oder irgendeine zweitrangige Info zuteilen wollen um etwas platz zu sparen.

**Comment by Zefau** [comment]
ah ok verstehe, danke dir

**Comment by Zefau** [comment]
added with `v2.1.0-beta.22`:

![image](https://user-images.githubusercontent.com/14368811/103170398-2de6ab80-4844-11eb-8e33-37a3053eee23.png)

**Comment by kaip2503** [comment]
Klappt bei mir. Aber evtl. könnte der Standard auf "nicht angehakt" stehen. Es ist recht aufwendig an allen Datenpunkten mit Trigger den Haken jetzt wieder rauszunehmen.

**Comment by duczz** [comment]
Schaut gut aus, der sekundäre trigger bezieht sich aber auf den zuvor angegebenen datenpunkt wäre es möglich den variable zu machen, sprich einen anderen datenpunkt für den sekundären trigger zu nutzen?

**Comment by Zefau** [comment]
Gehen tut alles, aber irgendwann ist auch Schluss ;-)

Dan wäre auch der angezeigte Wert unterschiedlich zum Trigger. Sofern das gewünscht ist, einfach im Gerät unterschiedlichen Datenpunkt Anzeige und Datenpunkt Trigger auswählen.

**Comment by duczz** [comment]
Sonst muss ich die Geräte eben anders zuordnen.
Ne ich meine nen extra Trigger feld zum füllen für den sekundärwert. Dein Weg würde in meinem Fall nicht klappen, hab ich nämlich nen Trigger z.B. Heizperiode akitv? kann ich die anzeige schlecht auf batterie legen, denn dann hab ich keine Heizperioden aktiv status anzeige mehr :)

**Comment by Zefau** [comment]
Verstehe den Use Case nicht. Warum würdest du die Batterie-Anzeige wollen und als Trigger dann die Heizperiode aktivieren? Finde das passt logisch nicht zusammen.

**Comment by duczz** [comment]
Weil ich platz sparen will, und unter dem Trigger eben noch platz für einen sekundären Datenpunkt (er würde dort hald gut und sichtbar passen) wäre, gibt bestimmt auch andere use cases für

**Comment by duczz** [comment]
@Zefau Könntest du den Designfehler noch mit anpassen (Sekundär ist zu tief)
![image](https://user-images.githubusercontent.com/25475385/103201221-ac4c5780-48ef-11eb-9bab-5b514ed6626b.png)

**Comment by Zefau** [comment]
Ist das im Widget oder im Gerät / Popup?

Hast du mittels Custom CSS dort etwas angepasst?

**Comment by duczz** [comment]
Mir ist noch ein Fehler aufgefallen, die sekundär datenpunkte zeigen trotz abgehakten state den state in der vis an
Ich report ganz schön viel - haha ^^

![image](https://user-images.githubusercontent.com/25475385/103210899-38b64480-4907-11eb-9d63-f1ea18a4cdbb.png)

**Comment by Zefau** [comment]
Der Haken bezieht sich nur auf den PrimaryState

**Comment by duczz** [comment]
Kommt was für den sekundären?

**Comment by Zefau** [comment]
Dort einfach in der Liste abwählen

**Comment by duczz** [comment]
aah, ich hat'n denkfehler, nur beim trigger steht es dann zusätzlich da

**Comment by Zefau** [comment]
Designfehler sollte mit `v2.1.0-beta.28` behoben sein
