### ISSUE TITLE
[v3.2.0-beta.19] Aufruf vom Instanzlink -> undefined

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2670]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e55c12d5-0a3a-42cf-a18b-d178507f2dac)

Ändert man undefined in http ->
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/2f38441f-7d87-41cf-b8ed-98023372e7a1)
Falsche Instanz wird genutzt

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Es wird automatisch https verwendet, obwohl nicht eingestellt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e1c2e4e0-2a94-4c4f-908e-1fb37b0e1380)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/a754731b-a238-4047-9632-3bbeb31e9205)

**Comment by Zefau** [comment]
Von wo aus rufst du was auf? Aus dem ioBroker Dashboard?

**Comment by mcuiobroker** [comment]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/2afea789-f74b-418d-86f2-d87258e51326)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.31` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.31` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
v3.2.0-beta.37 es kommt weiterhin https

**Comment by Zefau** [comment]
Die initiale Konfiguration wird vom Web-Adapter übernommen. Ist der bei dir auf sichere Verbindung eingestellt?

Nochmal zum Verständnis: Du erstellst einen neue Instanz und dann ist direkt `https` eingestellt? Und deine Annahme wäre aber, dass `http` voreingestellt sein sollte?

Funktionsweise ist aktuell, dass die Web-Adapter-Konfiguration übernommen wird. Wenn dort `https` eingestellt ist, dann auch bei jarvis. Wenn kein `https` eingestellt ist, oder der Web-Adapter nicht installiert ist, dann läuft jarvis über `http`.

**Comment by Zefau** [comment]
Achso, verstehe. Also der normale Zugang steht auf "Keine Authentifikation" im Standard. Für die Konfiguration steht es auf "Benutzeranmeldung". Das ist so richtig.

Allerdings sollten natürlich die Gruppen geladen werden. Deine Box ist ja leer. Ist die Instanz aus?

**Comment by mcuiobroker** [comment]
Instanz gerade gestartet
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/70aaf375-53cc-4575-937e-29c1552374c0)

**Comment by Zefau** [comment]
> Dadurch dass die Konfiguration auf "Benutzeranmeldung" steht wird durch den Instanzlink https aufgerufen.

Nein, `https` wird nur über die Checkbox `Verwenden Sie eine sichere Verbindung` gesteuert. Ist diese aktiviert, dann `https`, sonst `http`.

Habe den Fehler aber gefunden, danke dir.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.38` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.38` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
