### ISSUE TITLE
[v3.2.0-beta.19] Instanz-Config: Sicherungen öffnen sich nur bei Klick auf den Typ-Namen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2672]
Sonst öffneten sich die Sicherungen bei Klick auf die Typ-Zeile.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c7d3f4b3-7daa-4a62-ab4b-ae2c72096a8f)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
