### ISSUE TITLE
[v3.2.0-beta.19] jarvis setzt bei Änderung vom iFrame Widget signature -> null (scripts und widgets) -> permanentes Neuladen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2673]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/06bb7b66-f83f-48b0-b364-1d6a424aa283)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt.Danke.
