### ISSUE TITLE
(v3.1.9-beta.2)  fonz-size in der anzeigevariante json

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#2676]
Anzeigevariante:
{"default":{"color":"red","font-size":"40px"}}

fontsize greift nicht, da jarvis-state-value die fonz-size setzt. 

![image](https://github.com/Zefau/ioBroker.jarvis/assets/22169074/24259be6-e9f9-4a65-a56a-543034d982e7)

**Comment by ma-gu-16** [comment]
bringt nix, wird ja vom innerchild überschrieben.

**Comment by mcuiobroker** [comment]
Dann nur mit CSS, solange kein Fix da ist.

**Comment by ma-gu-16** [comment]
ahh vergiss ess, sorry. der wert ist von mir. bzw ich setzte das style auf das span :P
