### ISSUE TITLE
Jarvis / Widget DisplayImage zeigt Bild nur auf Mobilbrowser an

### ISSUE THREAD

**Issue by Schnuckman79** [Zefau/ioBroker.jarvis#2677]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**3.1.8
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung] s. auch https://forum.iobroker.net/topic/75499/jarvis-widget-displayimage-funktioniert-nur-mobil/14, da habe ich mit MCU schon einiges zur Eingrenzung getan inkl F12 Konsolenausgaben (https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
Aus meinen beiden Überwachungskameras (Technaxx TX67) hole ich mir Bilder mit "[http://user:pw@IP/cgi-bin/snapshot.cgi?"](http://user:pw@ip/cgi-bin/snapshot.cgi?%22) in je ein DisplayImage-Widget, das klappt auch auf dem Handy sehr gut. Nur am PC im Browser (Edge und Chrome getestet, ebenfalls Edge unter Android auf einem Fire Tablet) bekomme ich keine Bilder angezeigt, als wenn die Bilder nicht geladen werden könnten. Übernehme ich die URL direkt in den Browser, werden mir die Bilder angezeigt.

**Screenshots**
![image](https://github.com/Zefau/ioBroker.jarvis/assets/153268381/9e716967-fc50-4d44-ab95-78a16006fbd2)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/153268381/1a1321f6-4083-402f-bc19-e91dc56e1d60)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Also wenn es auf dem Handy geht, aber nicht auf dem Desktop, dann kann es nicht am DisplayImage-Modul liegen. Dieses unterscheidet nicht zwischen den beiden.

Schau mal bitte unter F12 und dort unter `Network`, ob du in der Liste den Request an die genannte URL findest und welchen Status diese hat.

**Comment by Schnuckman79** [comment]
OK, die Debug-Konsole von Edge erschlägt mich. Einen Punkt "Network" finde ich da nicht, magst mich da einen Hauch mehr anleiten? Besten Dank...

VG
Schnuckman79

**Comment by Schnuckman79** [comment]
ah, ok, das Fenster geht auch größer :-)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/153268381/933cfe9d-c910-4bb7-a8eb-8fdc9ef71a59)

hilft das?

**Comment by Schnuckman79** [comment]
naja, wenn ich 0 Byte vorgesetzt bekomme, schaffe ich auch keine Typ-Bestimmung :-) Aber warum gehts am Handy? Mein Workaround ist jetzt anderer Link, den ich aus den Onvif-Daten gefischt habe, da bekommt DisplayImage ein Bild hin am PC (dafür am Handy nicht mehr): http://192.168.180.44/onvifsnapshot/media_service/snapshot?channel=0&subtype=0. Hab jetzt einfach 2 Widgets erstellt und nutze auf dem Handy einfach das passende, gibt Jarvis ja her. Jetzt muss ich nur noch dem größenwahnsinnigen Tablet-Browser beibringen, dass er eigentlich ein Mobilbrowser ist. Noch keinen Plan, wie das geht... Oder kann ich irgendwie über Jarvis regeln, dass einem "großen" Browser die Mobilseite serviert wird?

**Comment by Bernd9000** [comment]
Habe das auch mal getestet aber mit der v3.2.0-beta.39
Die 3.1.8 hatte die Einstellung  noch nicht.

Beim Firefox brauchte ich die URL nur einmal im Browser direkt aufrufen und bestätigen das ich mich mit Benutzername und Passwort beim Server anmelden möchte.
Beim Chrome und Edge funktionierte das nicht.
Hier mußte ich folgende Einstellung im widget bei `crossorgin` wählen (v3.2.0-beta.39)

![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/6c085c0e-d8b2-4d5f-8fdc-3de1aa6eb370)

**Comment by Erwin40** [comment]
Da sich hier keine weiteren Personen mit DisplayImage Probleme gemeldet haben, 
denke ich, der Issue kann geschlossen werden.
Ich habe mal ein Test-Widget erstellt und bei FF + Edge wird das Bild problemlos angezeigt.
URL: http://raspberrypi4-ede:8082/0_userdata.0/Image/QR-Code%20f%C3%BCr%20G%C3%A4ste-WLAN.png
