### ISSUE TITLE
Keine Web UI

### ISSUE THREAD

**Issue by BlackandGold1** [Zefau/ioBroker.jarvis#2678]
Nach Update auf 3.2.0 beta 19 hab ich keine Weboberfläche. 
Bei Port 8400 passiert nichts und bei Port 8082 muss ich alles neu einrichten.
Wie komme ich wieder zurück auf 3.2.0 beta 10 da lief alles?

**Comment by Zefau** [comment]
Bekommst du Fehlermeldungen in der Browser-Konsole via F12? Oder im ioBroker Log?

**Comment by BlackandGold1** [comment]
F12 hab ich nicht da kein PC. Im Log sehe ich nichts.

**Comment by BlackandGold1** [comment]
![Uploading Screenshot_2024-06-27-09-29-54-24.jpg…]()

**Comment by BlackandGold1** [comment]
Scheinbar lädt er immer ne
![Screenshot_2024-06-27-09-32-55-66](https://github.com/Zefau/ioBroker.jarvis/assets/94290188/56df2991-314c-41d8-a33a-85bca0f32155)

**Comment by Zefau** [comment]
Ich schau mir das gleich mal an.

by the way: Irgendwas stimmt mit deinem Javascript-Adapter nicht. Der ändert immer seinen `alive` Status. Hat jetzt nichts mit jarvis zu tun und ist auch nicht schlimm für jarvis.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.20` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.20` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by BlackandGold1** [comment]
Geht nicht.
![Screenshot_2024-06-27-10-41-33-25_40deb401b9ffe8e1df2f1cc5ba480b12](https://github.com/Zefau/ioBroker.jarvis/assets/94290188/7ddc800b-2848-470a-a5b1-c9319cb33bd2)

**Comment by BlackandGold1** [comment]
Es geht leider immer noch nicht.

**Comment by Zefau** [comment]
Stoppe den Adapter mal und warte paar Sekunden, bevor du ihn dann wieder startest. 

Die gelbe Warnung kommt nicht von jarvis, sondern vom js-controller. Der Prozess scheint sich zu verschlucken.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.32` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.32` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by BlackandGold1** [comment]
Geht nicht. Aufrufe per App lässt App blinken. Webseite geht nicht. Außerdem sind alle Daten weg und Backup einspielen geht auch nicht.

**Comment by BlackandGold1** [comment]
Mit der Beta 37 geht die App wieder. Browser nicht. Außerdem sind alle Daten weg. Backup Upload, Datei auswählen geht. Dann kommt ein kleines Viereck und das war es.

**Comment by Zefau** [comment]
Kleines Viereck?

**Comment by BlackandGold1** [comment]
Ja nach Datei auswählen komme ich wieder in die Instanz und dann erscheint ein unten ein kleines graus Viereck. Es geht dann nach ein paar Sekunden weg. Mittlerweile geht es jetzt. Neues Problem nur ein Backup ist aktuell die anderen sind ein halbes Jahr alt. Somit muss ich alles neu machen weil im letzten halben Jahr ich viel neues erstellt habe. Außerdem habe ich das Problem das alles nur in Chrome funktioniert und in der App. Auf dem iPad und am PC mit dem Internetexplorer läd er die Seite nur kurz und sagt incorect.

**Comment by Zefau** [comment]
> Auf dem iPad und am PC mit dem Internetexplorer läd er die Seite nur kurz und sagt incorect.

Vermutlich noch wegen inkonsistentem Cache. Wenn es aber grundsätzlich wieder funktioniert mache ich hier erstmal zu?
