### ISSUE TITLE
[v3.2.0-beta.21] Authentifzierung für Konfiguration aktiviert, keine nicht auswählbar

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2679]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6546ddfd-8a6e-4d11-9413-abbb07bcb44c)

**Comment by Zefau** [comment]
https muss aktiviert sein

**Comment by mcuiobroker** [comment]
Habe ich aber nicht im System aktiviert, dann müsste doch eigentlich dort "Keine Authentifikation" stehen, oder?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/33b8106a-173c-406f-97f9-e457df7b4a1a)

**Comment by mcuiobroker** [comment]
Ach so man muss sichere Verbindung erst aktivieren, dann kann man umschalten.
Trotzdem sollte dann die Standard-Anzeige auf keine Authentifizierung sthen, oder? War vorher so

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.31` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.31` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Hat sich mit v3.2.0-beta.38 erledigt. Passt. Danke.
