### ISSUE TITLE
Mobile view not displayed correctly

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#268]
> I noticed another bug. I connected from my phone, went to the jarvis page. As if something has loaded, but the screen is blank. I turned it over to portrait mode - everything appeared, but there is no setting button. Flipped back, again the screen is empty. Probably something with the markup.

_Originally posted by @badenbaden in https://github.com/Zefau/ioBroker.jarvis/issues/236#issuecomment-717497768_

**Comment by Zefau** [comment]
Same here: https://forum.iobroker.net/post/511188

**Comment by Zefau** [comment]
@badenbaden Could you check if this issue got resolved with `v1.1.0-beta.66` ?

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/512770

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/510491

> Ich habe das Problem, das beim Aufrufen der VIS über das Smartphone (Samsung S20, egal welcher Browser) der Bildschirm sich nicht nach unten scrollen lässt. der Bildschirm wird dann leer.... Dies tritt nur auf, falls man die TABs mit einem Label (Bezeichnung, egal wie viele Zeichen!) versehen hat. Lässt man nur die TAB-Icons anzeigen, so lässt sich sich der Bildschirm ganz normal scrollen.

**Comment by Zefau** [comment]
fixed https://forum.iobroker.net/post/512770 with `v1.1.0-beta.69`

**Comment by badenbaden** [comment]
> @badenbaden Could you check if this issue got resolved with `v1.1.0-beta.66` ?


Hey. I confirm that the mobile view is now working correctly. Thanks!

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/517012
