### ISSUE TITLE
Verify Installation: Installation inconsistent - beta.26

### ISSUE THREAD

**Issue by StephanTexxpro** [Zefau/ioBroker.jarvis#2680]
Nach dem Updatre auf beta.26, Cache löschen und dem Test mit verschiedneen Browsern (FF, Chrome) endet der Aufruf mit 'Verify Installation: Installation inconsistent'.

**Comment by Bernd9000** [comment]
Beim Chrome Browser hatte ich das auch.
Hab dann Browserverlauf + Cookies + Cache gelöscht und Fehler war weg.

**Comment by StephanTexxpro** [comment]
Danke, @Bernd9000 - hilft bei mir leider nicht, hab es jetzt parallel auch noch mit Safari getestet, selber Effekt. Sowohl bei Aufruf über IP (10.x.x.x:8400) als auch via Reverse-Proxy.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.31` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.31` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by StephanTexxpro** [comment]
Leider nein, siehe https://github.com/Zefau/ioBroker.jarvis/issues/2684.

**Comment by BlackandGold1** [comment]
Gibt es eine Version die funktioniert und wenn ja wie installiere ich die genau?
Meine Frau ist kurz davor das Tablet von der Wand zu reißen 😒

**Comment by Zefau** [comment]
> Gibt es eine Version die funktioniert und wenn ja wie installiere ich die genau?
Meine Frau ist kurz davor das Tablet von der Wand zu reißen 😒

Bitte in solchen Fällen nicht jedem Release auf GitHub folgen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.32` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.32` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by StephanTexxpro** [comment]
Läuft leider noch nicht:
Beim ersten Aufruf via https://IP:8400 bekomme ich nun 'Bitte Verbindungsdetails angeben', klicke ich dann (ohne as von den vorbelegten Feldern zu ändern (IP & Port passen)) auf 'Verbinden' lande ich wieder bei 'Verify Installation: Installation inconsistent'.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.33` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.33` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by StephanTexxpro** [comment]
beta.33: Cannot read properties of undefined (reading 'set')

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.34` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.34` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by StephanTexxpro** [comment]
Jetzt wieder 'Verify Installation: Installation inconsistent'
Sorry!

**Comment by StephanTexxpro** [comment]
beta.37 läuft. Danke!
