### ISSUE TITLE
Support for Homematic RGB-Controller (HmIP-RGBW)

### ISSUE THREAD

**Issue by tehmilcho** [Zefau/ioBroker.jarvis#2681]
Hey there,

the Device import via Adpater "HomeMatic / HomeMatic IP via CCU" cant handle the RGB-Controllers from Homematic:

![image](https://github.com/Zefau/ioBroker.jarvis/assets/22918349/ef0f8dd2-6461-43a3-a984-6c84797efa61)

`{
  "_id": "hm-rpc.0.XXXXXXXXXXXXX",
  "type": "device",
  "common": {
    "name": "Wohnzimmer-RGB-1",
    "icon": "/icons/225_hmip-rgbw_thumb.png"
  },
  "native": {
    "TYPE": "HmIP-RGBW",
    "SUBTYPE": "RGBW",
    "ADDRESS": "XXXXXXXXXXXXX",
    "RF_ADDRESS": 6109712,
    "CHILDREN": [
      "0033E0C9923F58:0",
      "0033E0C9923F58:1",
      "0033E0C9923F58:2",
      "0033E0C9923F58:3",
      "0033E0C9923F58:4",
      "0033E0C9923F58:5"
    ],
    "PARENT": "",
    "PARENT_TYPE": "",
    "INDEX": 0,
    "AES_ACTIVE": 1,
    "PARAMSETS": [
      "MASTER",
      "SERVICE"
    ],
    "FIRMWARE": "1.0.52",
    "AVAILABLE_FIRMWARE": "1.0.62",
    "UPDATABLE": true,
    "FIRMWARE_UPDATE_STATE": "NEW_FIRMWARE_AVAILABLE",
    "VERSION": 1,
    "FLAGS": 1,
    "LINK_SOURCE_ROLES": "",
    "LINK_TARGET_ROLES": "",
    "DIRECTION": 0,
    "GROUP": "",
    "TEAM": "",
    "TEAM_TAG": "",
    "TEAM_CHANNELS": [],
    "INTERFACE": "",
    "ROAMING": 0,
    "RX_MODE": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1719066564482,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

`{
  "_id": "hm-rpc.0.XXXXXXXXXXXXX.1",
  "type": "channel",
  "common": {
    "name": "Wohnzimmer-RGB-1:1"
  },
  "native": {
    "TYPE": "UNIVERSAL_LIGHT_RECEIVER",
    "SUBTYPE": "",
    "ADDRESS": "XXXXXXXXXXXXXX:1",
    "RF_ADDRESS": 0,
    "CHILDREN": [],
    "PARENT": XXXXXXXXXXXXX",
    "PARENT_TYPE": "HmIP-RGBW",
    "INDEX": 1,
    "AES_ACTIVE": 1,
    "PARAMSETS": [
      "MASTER",
      "VALUES",
      "LINK",
      "SERVICE"
    ],
    "FIRMWARE": "",
    "AVAILABLE_FIRMWARE": "",
    "UPDATABLE": true,
    "FIRMWARE_UPDATE_STATE": "",
    "VERSION": 1,
    "FLAGS": 1,
    "LINK_SOURCE_ROLES": "",
    "LINK_TARGET_ROLES": "CONDITIONAL_SWITCH LEVEL SWITCH REMOTE_CONTROL",
    "DIRECTION": 2,
    "GROUP": "",
    "TEAM": "",
    "TEAM_TAG": "",
    "TEAM_CHANNELS": [],
    "INTERFACE": "",
    "ROAMING": 0,
    "RX_MODE": 0
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1719089926903,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

![image](https://github.com/Zefau/ioBroker.jarvis/assets/22918349/93ecc054-562f-4200-ba6b-8b25a12787a9)

**Comment by Erwin40** [comment]
Ich würde das einfach schließen ;-)

**Comment by Zefau** [comment]
@tehmilcho

**Comment by tehmilcho** [comment]
![image](https://github.com/user-attachments/assets/568a8cf9-86fb-4280-b1fc-a92729c11c91)

Hi, sorry for Delay i think it looks fine
