### ISSUE TITLE
Pro Lizenz funktioniert nicht mehr

### ISSUE THREAD

**Issue by mpl1337** [Zefau/ioBroker.jarvis#2683]
Hallo,

gestern wurde mein Abo verlängert und wollte jetzt die neue Lizenz übernehmen, jedoch klappt es nicht.

v3.2.0-alpha.53 (ich kann aufgrund eines anderen Problems leider nicht auf eine höhere Version updaten)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/a862ae0e-02de-4aff-8af9-6be3fc017b81)

Wenn ich jetzt aus Speichern drücke, aktualisiert die Seite aber es erscheint invalid License

![image](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/33a5abb6-6d5b-4e6c-8859-2bb6a06341ae)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/19016821/4ed93802-d4d6-46da-b506-742e1b6b538c)

Cache gelöscht und iob upload jarvis ausgeführt. Der ganze host wurde auch neu gestartet.

Was kann ich noch versuchen?

**Comment by Zefau** [comment]
Hi,

klingt alles richtig. DIe Lizenz wird im Cache gespeichert, aber wenn du diesen gelöscht hast, sollte es eigentlich gehen.

Benutzt du Firefox oder Chrome?
Im Chrome via F12 unter `Application` -> `Locale Storage` findest du den Cache. Gibt es dort einen Eintrag `jarvis.#xx...xx.pro` ? Diesen löschen.

**Comment by mpl1337** [comment]
Ich nutze Chrome.

Danke, hat funktioniert.
