### ISSUE TITLE
Not exists - beta.31

### ISSUE THREAD

**Issue by StephanTexxpro** [Zefau/ioBroker.jarvis#2684]
Bei direktem Aufruf via IP:8400.

**Comment by StephanTexxpro** [comment]
Ergänzung aus dem Log:

jarvis.0 | 2024-06-28 00:11:03.764 | warn | /index.html: Not exists

**Comment by Bernd9000** [comment]
Die index.html ist hier jetzt in einem weiteren Unterordner ?
\iobroker-data\files\jarvis\jarvis\index.html
"iob upload jarvis" hilft nicht...

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.32` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.32` should fix the bug - please verify. If the bug has been solved, you may close the issue.
