### ISSUE TITLE
SSL Fehler nach Update auf Bete 31 und 32

### ISSUE THREAD

**Issue by OliWit82** [Zefau/ioBroker.jarvis#2685]
Ich habe bis heute Morgen die Beta 19 genutzt.
Eben das Update auf 31 gemacht, seit dem geht Jarvis nicht mehr.

![_Fehler](https://github.com/Zefau/ioBroker.jarvis/assets/62326314/e9bac47a-261c-4de9-aad7-d6b864c9cdf4)
![Jarvis](https://github.com/Zefau/ioBroker.jarvis/assets/62326314/7971eedb-ce5f-423f-952f-e86543429dbd)

**Comment by Zefau** [comment]
Schau mal bitte in der jarvis Adapter-Konfiguration. Hast du dort die Zertifikate ausgewählt?

**Comment by Zefau** [comment]
Da musst du, wenn du die sichere Verbindung auswählst auch die entsprechenden Zertifikate auswählen, sonst geht es natürlich nicht.

**Comment by OliWit82** [comment]
Ja, aber selbst wenn ich sage keine Sichere Verbindung komm ich nicht mehr drauf.

**Comment by Zefau** [comment]
Mit demselben Fehler?

**Comment by OliWit82** [comment]
![sichere aus](https://github.com/Zefau/ioBroker.jarvis/assets/62326314/ab2dacb6-6ec6-46fc-a272-8c62bdae7a36)
![2](https://github.com/Zefau/ioBroker.jarvis/assets/62326314/8fa0d173-ddce-45d1-8484-1d082ade5abf)
![3](https://github.com/Zefau/ioBroker.jarvis/assets/62326314/87e55730-c9cf-403d-bd70-97594de56b25)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.34` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.34` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by OliWit82** [comment]
Hmm, entweder bin ich gerade zu do** dafür....

Es hat sich nichts geändert

**Comment by Bernd9000** [comment]
Zur Info:
Ich benutzte keine sichere Verbindung und habe auch nur noch die Verbindungsseite von jarvis.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.37` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.37` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Jo, hier funktioniert es wieder (ohne sichere Verbindung)

**Comment by OliWit82** [comment]
Hier leider nicht, immer das gleiche.

Wenn ich alles von Jarvis lösche Ordner und Adapter und die 23.0.8 installiere geht es. (Natürlich alles leer)
Wenn ich dann auf 31, 32 oder 37  gehe kommt der Fehler wieder

**Comment by Zefau** [comment]
Also mit beta-37 sollte es nun gehen. Welchen Fehler bekommst du denn?
