### ISSUE TITLE
Dark Mode based on system-settings

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2686]
Dark Mode automatically based on the system settings.

**Comment by Zefau** [comment]
![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/65e652fd-7915-43be-ac81-15e60f78e257)

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.33` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.33`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Bernd9000** [comment]
In der Firefox Konsole kommt bei beta.33:
App-hGejAmgnwn window.darkMode is undefined TypeError: window.darkMode is undefined

**Comment by Zefau** [comment]
Jo, fix kommt

**Comment by Bernd9000** [comment]
Kein Fehler mehr seit beta.37
Ich mußte einmal den Darkmode in jarvis aus und wieder einschalten damit es funktioniert.

**Comment by mcuiobroker** [comment]
DarkMode geht gar nicht mehr. Umschalten in ioBroker hilft auch nicht. Browser Edge

**Comment by Bernd9000** [comment]
Stimmt, die Einstellungsteht jetzt immer auf "off".
Versucht man das zu ändert bleibt es bei "off" oder der Browser hängt.

**Comment by Zefau** [comment]
> Verbinden -> normaler Frontend (LightMode-Anzeige, obwohl "Dunkel" in Windows gewählt und themeDarkMode: true)

`themeDarkMode` muss auf ´auto` sein, dann greift die Windows-Einstellung. `true` gibt es nicht mehr, ist nun entweder `on` oder `off`.

**Comment by mcuiobroker** [comment]
Dann wird es beim Update nicht automatisch angepasst?

**Comment by Bernd9000** [comment]
Hab nur eine Instanz, hier ist es zum Type "string" geworden.

**Comment by Zefau** [comment]
Also passt alles, außer, dass der `type` nicht aktualisiert ist? `auto` schaltet bei euch auch korrekt hin und her?

**Comment by Bernd9000** [comment]
`auto` schaltet hier korrekt die drei Werte im Datenpunkt `themeDarkMode` : `on , off , auto`
Es wird auch korrekt umgeschaltet hier unter Windows 11.

Nur in den jarvis Einstellungen wird es beim ersten Aufruf oder nach F5 immer als `off` angezeigt obwohl im Datenpunkt ein anderer Wert steht.
Also ein Anzeigefehler bei beta.38

**Comment by mcuiobroker** [comment]
Fully Kiosk Browser - funktioniert nicht
Edge (Handy) - funktioniert 
Chrome (Handy) - funktioniert
Firefox (Handy) - funktioniert
Android APP - nur Hintergrund wird angezeigt, keine Widgets, keine Menüeinträge, keine Tabs

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.39` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.39`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Soll das so sein?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/bc1bfb83-4e52-4e20-a0ed-5786a35771c0)

Oder sollte es ein Dropdown mit states (auto, off, on) sein?

**Comment by Zefau** [comment]
Ne, passt so. Das Backend kennt die Werte gar nicht und schreibt nur stumpf weg.
