### ISSUE TITLE
[v3.2.0-beta.39] webadresse Problem

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2687]
Nach der `index.html#` kam sonst immer die Instanznummer in der webadresse.
Jetzt ist es die ID von der ersten jarvis Seite die hinten als letztes angehängt wird (aussen) und die Instanznummer fehlt.

Beispiel vorher:
http://xxxxxxxx:8400/jarvis/index.html#/0/aussen

Jetzt steht bei mir folgendes:
http://xxxxxxxx:8400/jarvis/index.html#/aussen/aussen

Oder ID Kamera:
http://xxxxxxxx:8400/jarvis/index.html#/kamera/aussen

Starte ich mit folgender Adresse wird "aussen" nicht mehr angehängt aber die Instanznummer fehlt weiterhin ?
http://xxxxxxxx:8400/jarvis/index.html

Oder wird nicht mehr mit der Instanznummer adressiert ?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2666

**Comment by Zefau** [comment]
Jede jarvis-Instanz hat einen eigenen Socket und damit einen eigenen Socket-Port. Dass das mit der URL mitgeliefert wurde war, weil die Seite selbst über den Web-Adapter ausgeliefert wurde. Dies führte aber u.a. zu Problemen mit Proxys.

Web-Adapter wurde nun rausgeworfen und jarvis übernimmt sowohl socket als auch web. Die Instanz in der URL ist daher nicht mehr notwendig, da es über den Port erfolgt.
