### ISSUE TITLE
[v3.2.0-beta.39] settings bei neuer Instanz werden erst bei Änderung einer der jarvis-Einstellungen gesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2688]
Dies ist evtl ungünstig bzgl der neuen Einstellung von `themeDarkMode`?
Wenn möglich sollten die settings -DPs beim 1. Start der Instanz gesetzt werden?

- Übersetzung für use system-setting anpassen für deutsch?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/122f21b3-8cb3-4d07-8a24-3b34cd907a1c)

**Comment by Zefau** [comment]
> Dies ist evtl ungünstig bzgl der neuen Einstellung von themeDarkMode?
Wenn möglich sollten die settings -DPs beim 1. Start der Instanz gesetzt werden?

Was genau ist ungünstig? Dass die Einstellung auf "automatisch" steht?

**Comment by mcuiobroker** [comment]
Stimmt wird ja intern gesetzt, bleibt nur die Übersetzung.

**Comment by mcuiobroker** [comment]
Passt mit v3.2.0-beta.40. Danke.
