### ISSUE TITLE
Nach Charts Erstellung keine VIS mehr

### ISSUE THREAD

**Issue by matzesutopia** [Zefau/ioBroker.jarvis#269]
Habe mir eine VIS erstellt und wollte dann meine Temperaturen über die Chart Funktion loggen. Doch leider baut sich danach die gesamte VIS nicht mehr auf. Habe die neueste Beta installiert und der Fehler bleibt bestehen. Wäre echt toll, wenn dieser Fehler irgendwie behoben werden könnte. Sonst ist es eine ziemlich geile Visualisierung

![Chart Fehler](https://user-images.githubusercontent.com/73564008/97373654-bda8c180-18b6-11eb-86ea-88da69432ce7.JPG)

**Comment by Zefau** [comment]
Bitte die `Deine Identifizierungs-ID` unter Hilfe mitteilen oder alternativ die Layout Konfiguration.

**Comment by Zefau** [comment]
should be fixed with `v1.1.0-beta.59`.

**Comment by Zefau** [comment]
@matzesutopia can you confirm?

**Comment by matzesutopia** [comment]
the vis is not crashing anymore, but the charts are not loading

**Comment by Zefau** [comment]
Do you have any error in the browser console?

**Comment by Zefau** [comment]
@matzesutopia any errors on the console?

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/523233
https://forum.iobroker.net/post/523338

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/526526

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/530700

**Comment by Zefau** [comment]
apparently fixed with `v2.0.0-rc.3`.
