### ISSUE TITLE
[v3.2.0-beta.40] displayImage Einstellungen passen nicht in das Fenster, Anzeige zu breit

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2692]
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6418416f-5eb4-455b-bcfb-326a383a3746)
Vielleicht kann man das noch korrigieren?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.47` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.47` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Bisschen viel Platz unten, aber sonst passt es.
![image](https://github.com/user-attachments/assets/a63d92fc-16ce-4bc6-9b56-fcae16df4e4d)
Prio: low setzen?

**Comment by Zefau** [comment]
Popup nimmt immer die gesamte Größe des Fensters ein, daher der Platz unten.
