### ISSUE TITLE
[v3.2.0-beta.40] Layoutbearbeitung Widget-Info nur bei kleinen Widgetgrößen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2694]
In einem großen Widget wird die Info trotzdem angezeigt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/b644b7fc-0a34-43f1-b1d6-a6cb1c08f844)

Dort ist sie aber schon zu sehen. Bitte dort die Info 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/1e39c15a-30a2-4290-93a1-e3f1ca054e30)
entfernen

Bei kleinen Widgets passt es.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/2dced5a8-cf03-4a7e-9030-fe8bfb735b06)

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.47` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.47`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt, Danke.
