### ISSUE TITLE
[v3.2.0-beta.40] "sichere Verbindung" Haken wird nicht gespeichert?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2695]
Ich möchte ja nur ein Password für das Frontend. Wenn ich jetzt "sichere Verbindung" wähle und für Frontend ein Passwort vergebe bekomme ich einen Fehler.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/6996c051-af47-4673-8b50-42a53a16c1a8)
Dabei ist mir aufgefallen, dass er die "Sichere Verbindung" wieder gelöscht hat? Haken raus, obwohl mit gespeichert.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/d3e0c989-a0fb-4e29-9581-8810e0f7df2c)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/discussions/2691#discussioncomment-9916842_

Das war auch im iobroker-LOG
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/7bea8f5f-2a7a-4b9d-a23e-a871b7e580ad)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/43a1b1e9-4e79-4aa8-83cf-4cba0fad1f4c)

**Comment by mcuiobroker** [comment]
defaultPublic zieht auch nicht
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/2b5ef059-3057-44af-a432-ae4e8fe07101)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/88e7eba1-6572-47ba-9487-11736c9f7a6c)

**Comment by Zefau** [comment]
Wie die Fehlermeldung im Log sagt, du musst wenn du sichere Verbindung auswählst auch ein Public sowie privates Zertifikat angeben, sonst setzt Jarvis es zurück.

**Comment by mcuiobroker** [comment]
Wenn ich jetzt beide Zertifikate auswähle, dann kommt die PIN-Abfrage -> schwarzer Bildschirm. 
Dann F5-Reload -> Anzeige ohne CSS
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/8c748324-7ba2-4b50-9036-c068450a2596)

**Comment by mcuiobroker** [comment]
Fehler gefunden. 
Offenes Problem:
- nach Eingabe der PIN kommt nur schwarzer Bildschirm
- PIN-Eingabe nur einmal nicht mehr nach Reload (F5)? evtl. Optional (es gab früher eine Einstellung wo man es setzen konnte)

**Comment by mcuiobroker** [comment]
iobroker muss letztendlich dann auch auf https laufen, da man sonst, wenn man z.B. VIS integriert wieder das Problem mit Mixed Content bekommt?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0b01e977-454e-46ed-b30d-f4cf1d2c1dde)

**Comment by Zefau** [comment]
Was hast du da mit Apache gemacht? Wofür ist das notwendig? 

Ja, du kannst kein http Content in https einbinden. Vis bzw Web Adapter muss dann auch auf https laufen.

**Comment by mcuiobroker** [comment]
Apache umgestellt auf https. Gebrauche ich als Dateiserver für die Scripts-Importe und CSS-Importe.

Habe jetzt Admin auf https umgestellt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0f8e668e-47f0-4f9d-8f6f-79e3f20bf4fd)
und Web umgestellt
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/00711a8b-c2b0-4e42-9aab-9a70644677e6)
Und trotzdem kommt "nicht sicher"
Im LOG
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ab8c0369-0c77-4d18-8f9c-aac2bbc64679)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/49406ba9-8d8c-4a65-817a-87cff43236b3)

**Comment by Bernd9000** [comment]
Ich meine das hängt doch von den Zertifikaten ab, oder ?
Ist es nicht so das selbstsignierte Zertifikate grundsätzlich im Browser als unsicher eingestufft werden ?

**Comment by mcuiobroker** [comment]
Das mag sein. Für mich als "http-User" ist es schwierig zu verstehen, warum ioBroker "https" unterstützt, dann aber z.B. für cloud.0 wieder sagt, installiere eine zusätzliche Instanz. Was soll da die Extra Instanz bringen?
Wenn es bei den Umstellungen dann doch "unsicher" ist und man keine Daten übertragen soll, warum das Ganze danneinstellen.
Letztendlich ist doch das Ziel jarvis mit einer / oder mehreren PINs / Passwörtern für bestimmte User eingrenzen zu können.
Wenn ich mir vorstelle, dass muss dann jeder User so machen, halte ich es für sehr schwierig das noch zu supporten, wenn man da nicht eine saubere Doku zu hat.
Für mich sind da offene Fragen
- was mache ich jetzt mit der cloud
- wie muss ich einstellen
- bei selbstsignierten Zertifikaten war sonst immer die Rede von "einmal" bestätigen und fertig, warum jetzt nicht?
- usw. und da kommen sicher noch zig andere Fragen und Probleme, die dann bei den anderen Usern auch auftreten werden

**Comment by mcuiobroker** [comment]
@Bernd9000 Ich hatte keine anderen zur Auswahl?

**Comment by Bernd9000** [comment]
Ich hab das auch noch nicht gemacht aber die Zertifikate müssen öffentlich signiert sein damit Sie im Browser akzeptiert werden.
Selbst signierte funktionieren auch aber es kommt dann eben eine Warnung im Browser.
Ich glaube für öffentlich signierte ist das "Let's encrypt Zertifikate" im web Adapter zuständig

**Comment by mcuiobroker** [comment]
Ja, aber wenn man bei `http` bleibt kann man keine Pin / Passwort für jarvis nutzen.
Und das möchten ja einige User, sei um die Anzeige / Konfiguration vor Kindern zu schützen oder Sontiges.

**Comment by Bernd9000** [comment]
Hab das jetzt auch getestet und es funktionierte mit Chrome, Edge und Firefox.
Hab einmal bestätigt das ich trotzdem die Seite aufrufen möchte und das blieb bei allen drei Browsern gespeichert.
Wenn dann cache/cookies gelöscht werden muß man es dann nochmal bestätigen.
Als "unsicher" gilt hier soviel ich weiß immer das selbst signierte Zertifikat.
Da man ja weiß das das Zertifikat von einem selbst kommt ist alles i.O.

Chrome Beispiel:
![Unbenannt](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/b96fc75d-8ca1-4dbc-bcd1-fae76ac81266)
 

![Unbenannt2](https://github.com/Zefau/ioBroker.jarvis/assets/77005685/4ba411eb-4a4a-4a5d-8775-8893a23106f1)

**Comment by mcuiobroker** [comment]
Jetzt steht aber in der Adresszeile immer nicht sicher , oder?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/98c9bb9d-a740-4ae2-ac7b-423976771a1b)

**Comment by Bernd9000** [comment]
Ja, das ist richtig.
Das sollte dann in die Doku.
Will man das vermeiden müssen öffentlich signierte Zertifikate her.

**Comment by mcuiobroker** [comment]
Ja, ich schreibe die Doku und hab davon keine Ahnung. Also das lässt hoffen.

**Comment by Bernd9000** [comment]
Oder Zefau müßte nochmal die Möglichkeit schaffen das eine PIN-Abfrage auch über http funktioniert.
Oder selbst programmieren mit einer vorgeschaltete Startseite in der man das Passwort eingeben muß

**Comment by Zefau** [comment]
Auch bei selbst signierten Zertifikaten ist die Übertragung verschlüsselt und Pin bzw. Passwort nicht im Klartext. Das Risiko ist lediglich, dass ein Dritter unbemerkt das Zertifikat austauscht, da es nicht signiert und damit extern bestätigt ist.

Funktioniert alles wie es soll.

Lediglich die Meldung würde ich noch etwas expliziter machen, warum Jarvis ggf. die Einstellungen zurücksetzt, wenn https nicht richtig konfiguriert ist.

**Comment by mcuiobroker** [comment]
Bleibt noch das Problem von oben
https://github.com/Zefau/ioBroker.jarvis/issues/2695#issuecomment-2198757969

**Comment by mcuiobroker** [comment]
@Bernd9000 Kannst du mal schauen, ob ich alles drin hab in der Beschreibung. Danke,
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/instanz-einstellungen-v3.2.0

**Comment by Bernd9000** [comment]
Ja, sieht gut aus.

**Comment by mcuiobroker** [comment]
@Zefau Auch bei ioBroker-User bekomme ich nach dem Login die schwarze Seite
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e9e85bdb-5c90-45e0-aaf1-0488d0c74486)
und diese Fehler
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/7ab81434-5e9f-44e9-9b1a-6419e29b620f)

**Comment by mcuiobroker** [comment]
dabei ist mir aufgefallen, dass dann die Clients nicht neu gestartet werden. Im Browser LOG erscheint.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/311be58e-df37-4182-b3b1-047910f8f322)

**Comment by mcuiobroker** [comment]
Problem sind auch Kameras mit camera-Adapter. Der stellt keine https zur Verfügung, obwohl das ja vom web abhängig sein sollte.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/01d0e2c3-9399-4dea-875b-e39684f719b3)

**Comment by mcuiobroker** [comment]
Dann habe ich mal ein Switch gesetzt, obwohl der User es ja nicht darf wird der Switch umgesetzt (false->true)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/933a019e-702d-4dbf-ac67-ad025d281a24)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/345d91d7-d7c3-4fff-ad8c-4edd7fb6692d)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3fcbb1da-e9e5-4d94-9566-651d0e31457c)

**Comment by mcuiobroker** [comment]
@zefau Soll ich die offenen Punkte mal in einzelne Issues setzen?

**Comment by Zefau** [comment]
sollte mit `v3.2.0-beta.46` passen

**Comment by mcuiobroker** [comment]
Offene Probleme:
- Anmeldung in jarvis als User -> ok -> Seite wird neu geladen -> Scripte werden doppelt ausgeführt. -> Reload (F5) -> ok

- Ist man einmal als User X angemeldet, kann man sich nur "ummelden", wenn man die Instanz stoppt. Der erste User bleibt solange als angemeldeter User im Cache.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.67` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.67` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Was wurde geändert? 
Wie kann man sich ummelden?
Scripte können nicht getestet werden siehe #2757

**Comment by Zefau** [comment]
Logout button in der Sidebar

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/51bc3669-64df-4dd1-9a3d-b309dd724d2d)
Keiner da?

**Comment by Zefau** [comment]
Aktiviert hast du es?

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/a1b75e29-8df1-4f38-8ce0-c97b88933008)
Wo?

**Comment by mcuiobroker** [comment]
Gefunden

**Comment by mcuiobroker** [comment]
Wenn er ausgeschaltet ist wird Logout nicht angezeigt. Das sollte aber trotzdem sein?
![image](https://github.com/user-attachments/assets/92a9cef3-b089-4005-8ddf-0bf5094621d9)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.68` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.68` should fix the bug - please verify. If the bug has been solved, you may close the issue.
