### ISSUE TITLE
[v3.2.0-beta.44] ActionElement wird im Layout nicht aus Geräte übernommen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2697]
DropDownAction im GeräteDP

![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/e9896b4f-457a-48a8-8bf7-0e814ddeb41a)

Bei Auswahl vom Geräte-DP ist das Feld ActionElement leer.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c2420f71-f008-40ca-b66f-40f97baeb752)

Wählt man es aus zeigt es nur default#off und default#on als Auswahl an, nicht die Liste
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ea936c21-2469-471b-9754-3fe29331a4f1)
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/25dcd8fe-9b7d-46a8-8a88-64255f99ea6a)

Löscht man die Auswahl wieder, wird jetzt das "Geräte-DP-Element" in grau angezeigt, aber es gibt keine Auswahl mehr im Frontend.
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5ebd9e98-ef42-4937-8562-ae99d907d590)

**Comment by mcuiobroker** [comment]
Zeile verruscht

**Comment by mcuiobroker** [comment]
Bedeutet nur, dass die Liste angezeigt wird man die DropdownAction auswählt. Die Automatik der Übernahme aus dem Geräte-DP fehlt.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.52` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.52` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Gerade getestet (werde noch zum Beta-Test hier :-) )
Leider nein, aber viel schlimmer, jetzt werden plötzlich Scrollbars angezeigt (FF auf PC), obwohl die Widgets ausreichend hoch sind.
Sogar im Kalender...
Nicht bei allen, aber bei denen wo es angezeigt wird, bekomme ich es nur weg wenn ich "Skaliere Inhalte zur Widget-Größe" aktiviere.
Aber zumindest funktioniert das Skalieren wieder, wenn das Widget zu klein ist (Aber nur bei FireFox auf PC)
![grafik](https://github.com/user-attachments/assets/4d5f6b94-69f4-48ed-bb97-800c993b7f4a)

Auf dem iPad 2:
Katastrophe ;-)
Bildschirm wird nach unten im Sekundentakt immer länger...
Ich glaub ich geh' wieder auf die 49 :-))

**Comment by Erwin40** [comment]
Gerade getestet (werde noch zum Beta-Test hier :-) )
Leider nein, aber viel schlimmer, jetzt werden plötzlich Scrollbars angezeigt, obwohl die Widgets ausreichend hoch sind.
Sogar im Kalender...
Nicht bei allen, aber bei denen wo es angezeigt wird, bekomme ich es nur weg wenn ich "Skaliere Inhalte zur Widget-Größe" aktiviere.
Aber zumindest funktioniert das Skalieren wieder, wenn das Widget zu klein ist (FireFox auf PC

**Comment by Erwin40** [comment]
Konnte es nicht lassen und hab die 51 probiert.
Gleiches "Fehlverhalten", also zurück zur 49

**Comment by Zefau** [comment]
Bitte die Issues nicht mischen. Bezogen auf das Original-Problem sollte das ActionElement nun übernommen werden. Bitte ggf. das Gerät nochmal neu ins Layout aufnehmen.

**Comment by Erwin40** [comment]
Ok, sorry.
Wird leider auch in der 52 nicht übernommen.
Habe neues Testseite angelegt, neues Gerät, neues Widget und dort das neues Gerät hinzugefügt.
Und Cache habe ich vorher auch gelöscht :-)

**Comment by mcuiobroker** [comment]
Im Geräte-DP vorhanden
![image](https://github.com/user-attachments/assets/c8e88206-d192-4f52-afa2-2a3abf68c93e)
Im Layout nicht vorhanden, sollte dort in grau auftauchen.
![image](https://github.com/user-attachments/assets/1a59f60f-c8dc-452e-b8af-2925e2875bb8)

**Comment by Zefau** [comment]
hm, geht bei mir?

![grafik](https://github.com/user-attachments/assets/bd1f93d2-55c9-4ec8-b42e-fac52847c9f7)

![grafik](https://github.com/user-attachments/assets/0676faf6-8bb5-446c-851e-994e31c66147)

**Comment by mcuiobroker** [comment]
Ist es im Layout ein neu angelegter Eintrag?
Ich habe jetzt keinen neuen Eintrag gesetzt.

**Comment by Zefau** [comment]
>  Ich habe jetzt keinen neuen Eintrag gesetzt.

Wenn du keinen neuen Eintrag setzt geht es nur, wenn du vorher nicht einen Wert drin hattest du aktiv rausgelöscht hast. Wenn du das Dropdown aktiv leer machst, dann bleibt es leer und auch ohne Vererbung (sonst gäbe es keine Option keinen Eintrag zu haben).

**Comment by mcuiobroker** [comment]
Mit beta.53 wird es angezeigt, wa noch auf 52.
