### ISSUE TITLE
[v3.2.0-beta.44] Seitenzahl höher 1 zeigt keine Selektion auf dem Handy an

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2699]
`Styles und Scripts sind ausgeschaltet`
1. Seite

PC
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c3369975-0748-4c3b-9888-4877509f52a1)

Android
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/203642fe-f44e-4120-89fa-55257f5e3d1e)

andere Seite

PC `hier fehlt auch die blue color` 
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3c873d98-56ec-4d48-afbc-fd3a2fee5801)

Android
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/47267b10-1e08-4aff-bbc7-ef93fdc1a12d)

**Comment by Zefau** [comment]
Hast du das Problem noch? Bei mir sieht es gut aus:

![Animation](https://github.com/user-attachments/assets/95bda4b2-d434-4cea-88b3-2c009e137de3)

**Comment by mcuiobroker** [comment]
Passt. Danke.
