### ISSUE TITLE
Calender: Support for local ical / ics files

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#270]

**Comment by Zefau** [comment]
What's the exact requirement you are asking for? `ics` or `ical` are parsed by jarvis. Are you asking for files to be parsed instead of an URL? What would be the use case?

**Comment by duczz** [comment]
im using a ics files in ical and it doesnt load in jarvis
![image](https://user-images.githubusercontent.com/25475385/97542675-76f6bc80-19c7-11eb-8cb6-b75c5109be5a.png)

**Comment by Zefau** [comment]
jarvis currently only supports URLs, not local paths.

**Comment by Zefau** [comment]
Support has been added with `v1.1.0-beta.60`. jarvis detects local files now and loads them accordingly. @duczz Could you verify and confirm?

**Comment by duczz** [comment]
It works fine, thanks

**Comment by duczz** [comment]
Derzeit werden local files nur im ical.0 unterstützt/ausgelesen teilt man diese aber in mehrere Instanzen auf erkennt es jarvis nicht auch ein manuelles einfügen der loaklen ics funktioniert im jarvis nicht

**Comment by Zefau** [comment]
jarvis arbeitet unabhängig vom ical Adapter und lädt nur die dort hinterlegten Kalender einmalig heraus. Einfach den lokalen Kalenderpfad direkt in jarvis hinterlegen, das sollte gehen.

**Comment by duczz** [comment]
das hab ich gemacht.

Pfad: /opt/iobroker/iobroker-data/files/vis.0/Penthouse/Kalender/Müllabfuhr_2021.ics
![image](https://user-images.githubusercontent.com/25475385/103226580-bccef300-492c-11eb-9b04-e353e94fa439.png)

**Comment by Zefau** [comment]
@duczz probier mal `v2.1.0-beta.29`.

**Comment by duczz** [comment]
klappt danke
