### ISSUE TITLE
[v3.2.0-beta.44] Obwohl kein BodyElement im Layout und Device -> LCBody wird angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2700]
Layout
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/c8bdd6a9-a73f-4996-8cb7-93de162a8311)
Geräte-DP
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/77b75f0b-c4ba-46dd-a205-31010a22ed4a)
Frontend
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ac3c122c-2f4d-4268-8820-f84fc1071f60)

**Comment by Zefau** [comment]
sollte mit `v3.2.0-beta.53` behoben sein

**Comment by mcuiobroker** [comment]
Passt. Danke.
