### ISSUE TITLE
Jarvis v3.1.8 APK meldet "Error: Verify Licences: Network Error"

### ISSUE THREAD

**Issue by mapietru** [Zefau/ioBroker.jarvis#2704]
**Prerequisites / Voraussetzungen**
Jarvis v3.1.8 PRO User und APK für Android

**Describe the bug / Beschreibe den Fehler**
Die Jarvis v3.1.8 APK startet und bringt direkt den Fehler -> Error: Verify Licences: Network Error.
Fehler tritt unabhängig vom Smartphone auf. Getestet und zuvor lauffähig mit Galaxy S24 (Android 14, Patchlevel Juni 24).
Meine Lizenz läuft noch eine Weile. Per Browser gibt es kein Problem.

**Screenshots**
![Screenshot_20240705_125054_jarvis](https://github.com/Zefau/ioBroker.jarvis/assets/87319110/313daeeb-ffcf-4f97-91fe-80e7bb678ad8)

**Comment by spike1986** [comment]
I have the same problem with v 3.2.0 beta 6.

**Comment by Zefau** [comment]
Bitte nochmal schauen, sollte nun behoben sein.

**Comment by mapietru** [comment]
Vielen Dank! Fixed!

**Comment by mapietru** [comment]
Problem besteht wieder seit heute Morgen.

**Comment by Erwin40** [comment]
Hat jemand die Android APK und kann das mit der aktuellen beta testen?
Ich habe leider kein Tamagochi 😁

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.66` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.66` should fix the bug - please verify. If the bug has been solved, you may close the issue.
