### ISSUE TITLE
Tunable WhiteSliderBody

### ISSUE THREAD

**Issue by tschortschde** [Zefau/ioBroker.jarvis#2705]
Hello,
im using the jarvis v3.1.9-beta.2.
I can't find the tunable slide body and so on.
Can you help me?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/11274233/9e5a9889-7a00-4fec-820b-d008d62843ab)

**Comment by mcuiobroker** [comment]
Geräte Gewerk muss Licht sein

**Comment by tschortschde** [comment]
> Geräte Gewerk muss Licht sein

Da wär ich nicht darauf gekommen; Herzlichen Dank!

**Comment by mcuiobroker** [comment]
Sollte man evtl. auch für andere Gewerke zulassen?
