### ISSUE TITLE
WidgetLabelChange - Click auf Titel mit Widget auf anderen Seite verknüpfen

### ISSUE THREAD

**Issue by tschortschde** [Zefau/ioBroker.jarvis#2706]
Hallo,
ich nutze das widgetLabelChange

Kann man zusätzlich zum Click auf das [Icon ](https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/scripts-3.1.x-pro/widgets/widgetlabelchange#ab-v1.0.5-klick-auf-icon-weiterleitung-auf-tab-seite)auch mit einem Click auf den Titel (WidgetLabel) zur anderen Seite springen?

Bei mir funktioniert das nicht!?

**Comment by mcuiobroker** [comment]
Das ist ein Zusatzprogramm. Dies gehört nicht hierhin. Zefau kennt die Programme nicht. Ist auch immer extra erwähnt.  Bitte schließen und im zugehörigen Thread , siehe Doku, einstellen.

**Comment by Zefau** [comment]
Kannst du im Forum nicht für jedes Zusatzprogramm einen Thread anlegen? Dann kannst du den für `widgetLabelChange` hier verlinken. Gibt es Zusatzprogramme, die ich in den core übernehmen soll?

**Comment by mcuiobroker** [comment]
So viele Nachfragen kommen nicht zu den einzelnen Zusatzprogrammen, daher gibt es einen Thread in dem man seine Probleme und Fragen dazu stellen kann.
> Gibt es Zusatzprogramme, die ich in den core übernehmen soll?

Ja jede Menge, aber lass uns erst mal eine komplett stabile Version erstellen, ohne Fehler, dann kannst du sicherlich die Zusatzprogramme einbauen.

Dies war sicherlich ein Versuch von @tschortschde diesen einen Punkt als Feature Request einzubringen.
