### ISSUE TITLE
[v3.2.0-beta.45] Widget keine Secondary States mehr möglich

### ISSUE THREAD

**Issue by Mephisto090** [Zefau/ioBroker.jarvis#2707]
Hej,

es lassen sich keine Secondary States mehr auswählen :(

vg

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.46` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.46` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Joylancer** [comment]
Super, Danke, geht wieder (hatte den Bug auch)

**Comment by Erwin40** [comment]
Wie hast du das geschaft?
Ich habe es über Katze + Benutzerdefinierte + URL versucht, erhalte aber nachfolgenden Fehler:

`$ iobroker url https://github.com/Zefau/ioBroker.jarvis/tree/v3.2.0-beta.46 --host RaspberryPi4-Ede --debug
install Zefau/ioBroker.jarvis#v3.2.0-beta.46

NPM version: 10.7.0Installing Zefau/ioBroker.jarvis#v3.2.0-beta.46... (System call)

npm error code 128

npm error Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.npm error git@github.com: Permission denied (publickey).npm error Schwerwiegend: Konnte nicht vom Remote-Repository lesen.npm errornpm error Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehennpm error und das Repository existiert.

npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-07-21T18_48_26_343Z-debug-0.log

npm error code 128npm error An unknown git error occurrednpm error command git --no-replace-objects ls-remote ssh://git@github.com/Zefau/ioBroker.jarvis.gitnpm error Warning: Permanently added 'github.com' (ED25519) to the list of known hosts.npm error git@github.com: Permission denied (publickey).npm error Schwerwiegend: Konnte nicht vom Remote-Repository lesen.npm errornpm error Bitte stellen Sie sicher, dass die korrekten Zugriffsberechtigungen bestehennpm error und das Repository existiert.npm error A complete log of this run can be found in: /home/iobroker/.npm/_logs/2024-07-21T18_48_26_343Z-debug-0.log

host.RaspberryPi4-Ede Cannot install Zefau/ioBroker.jarvis#v3.2.0-beta.46: 128

ERROR: Process exited with code 25`

**Comment by Joylancer** [comment]
ganz normal über die Katze-Github-Jarvis ausgewählt,
keine Probleme dabei.
Läuft bei mir allerdings im Backup-Testsystem (JS-Controller: 6.0.9 /Node.js: v20.15.1 / Admin: 7.0.17)

**Comment by Erwin40** [comment]
Hi.

Sorry, aber allein schon diese URL: https://github.com/Zefau/ioBroker.jarvis/tree/v3.2.0-beta.46
ist nicht erreichbar. Da kommt:
![grafik](https://github.com/user-attachments/assets/0bc326c7-ffa2-4808-90d2-079e00b969ac)

Hast du dein ioBroker Repository etwa auf Beta stehen?

Und hast du es so installiert? (Da sieht man aber keine Versionsnummer)
![grafik](https://github.com/user-attachments/assets/9152bbcf-f737-406d-b554-90b593748156)

**Comment by Zefau** [comment]
Einfach via `https://github.com/Zefau/ioBroker.jarvis`

**Comment by Erwin40** [comment]
Äh, ich glaub wir reden aneinander vorbei.
Ich hätte gerne die 3.2-beta.46 installiert.
Wenn ich die URL dort eingebe, bekomme ich sicher die 3.1.8, oder etwa nicht?
Ich habe gerade keine Ersatz SD-Karte (die hat es mir wohl zerschossen) und kann hier kein Risiko eingehen.
Z.Z. habe ich ja die beta-40 und kann damit erst Mal leben.

![grafik](https://github.com/user-attachments/assets/964e1f6d-f427-45cf-be26-21988705fa6e)

**Comment by Erwin40** [comment]
So, ich habe meine Ersatz SD-Karte erfolgreich bespielen können.
Und, huch...
Tatsächlich, ich hab jetzt die beta.46 *hurra* *freu*
Dann weiß ich das jetzt mal auch ;-)
Vielen Dank!
