### ISSUE TITLE
Please correct licenseinformation

### ISSUE THREAD

**Issue by mcm1957** [Zefau/ioBroker.jarvis#2709]
As jarvis requires a pro license for some functionality, this adapetr requires license type informtion at io-package.json.

Please replace "license":"MIT" with "licenseInformation":

```
    "licenseInformation": {
	"type": "limited",
	"license": "CC-BY-NC-ND-4.0",
	"link": "https://github.com/Zefau/ioBroker.jarvis/discussions/891"
}

```

Please note that this correction is required for release of next version.

See PR https://github.com/Zefau/ioBroker.jarvis/pull/2708

**Comment by Zefau** [comment]
merged, thanks for the correction 👍

**Comment by mcm1957** [comment]
Thanks for the ultrafast reaction.
