### ISSUE TITLE
Desktop vs. Mobil - Relative Höhe des Widgets

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#271]
> gerade getestet mit beta 52
mit skalieren ein/aus passiert gar nichts
das einzige was hilft ist die maximale höhe einzugeben.
das hab ich jetzt z.b. auf 600 stehen. dann wird das bild kleiner.
ist aber fast zu klein für die visu am pc, aber zu groß fürs handy.
irgendwie müsste das noch etwas dynamischer gehen

_Originally posted by @Timmes123 in https://github.com/Zefau/ioBroker.jarvis/issues/252#issuecomment-716061420_

**Comment by Zefau** [comment]
Kannst du mal statt `px` die Einheit `vh` für die Höhe verwenden? Siehe auch https://wiki.selfhtml.org/wiki/CSS/Wertetypen/Zahlen,_Ma%C3%9Fe_und_Ma%C3%9Feinheiten#Relative_L.C3.A4ngenma.C3.9Fe

`vh` ist eine relative Einheit in Relation zur Höhe des Viewports. Damit solltest du ein gutes Ergebnis sowohl auf Desktop als auch mobil erreichen. `px` hingegen ist immer absolut.

**Comment by Timmes123** [comment]
oh sorry ich hatte im anderen issue geantwortet und hab den hier gar nicht mitbekommen.
habs grad mit beta68 getestet
ich gebe bei max höhe z.b. 100 vh ein. dann ist auf beiden geräten einigermaßen ok.
wenn ich allerdings 120vh eingebe, dann passt es am pc gut, am handy ist es allerdings dann wieder zu groß und abgeschnitten
wenn ich statt 120vh 1200 eingebe (was dann ja laut deiner angabe in px ist? dann ist die größe am pc ähnlich, aber am handy viel viel größer. also das vh scheint schon zu skalieren, aber den dreh hab ich trotzdem noch nicht so raus

**Comment by Zefau** [comment]
Hast du die Informationen des Links gelesen?
> Die Einheit vh entspricht dem 100. Teil der Höhe des Anzeigebereichs (Viewport). Es gilt also: 100vh = Höhe des Viewports. 

Insofern wäre 100vh = 100% des Fensters (jeweils relativ zu Desktop / mobil, etc.).
Alles was über 100vh hinaus geht würde dann theoretisch über den Viewport (das sichtbare Fenster) gehen.

**Comment by Timmes123** [comment]
natürlich hab ich das gelesen, deswegen hab ichs ja nicht ganz verstanden warum bei 100 das bild auf dem Desktop trotzdem so klein ist.

**Comment by Zefau** [comment]
100 soll eigentlich den gesamten sichtbaren Bildschirm füllen laut Beschreibung. Ist bei mir aber tatsächlich auch nicht der Fall.

Unter'm Strich aber eine annehmbare Lösung für Desktop & mobil, oder?

**Comment by Timmes123** [comment]
ist denke ich ganz gut ja :-) auf jedenfall viel besser als statische pixelangaben :-)

**Comment by Timmes123** [comment]
ich weis nicht wie lange schon, ich war denke ich auf beta 108 oder so, und jetzt auf 119,
bei beiden funktionierte das nicht mehr. eingestellt sind immernoch 100vh, allerdings ist das bild mini klein

![image](https://user-images.githubusercontent.com/73311538/99837667-3fafa180-2b68-11eb-975d-369f2fa48acb.png)

hab mehrere einstellungen probiert, ich kriegs nicht mehr hin, dass das bild richtig angezeigt wird?
hast du da noch was geändert?

**Comment by Zefau** [comment]
Scheinbar. Ist jedenfalls wieder was krum.. :(

**Comment by Zefau** [comment]
Kannst du nochmal mit `v1.1.0-beta.120` probieren?

**Comment by Timmes123** [comment]
geht wieder :-)
