### ISSUE TITLE
Move from `cordova` to `capacitor`

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2710]

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.46` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.46`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Die App wurde nicht installiert, da das Paket offenbar ungültig ist.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.47` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.47`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Jetzt kommt noch weniger. Startet kurz und verschwindet sofort.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.48` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.48`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Bei mir funktioniert es leider nicht. Icon kurz sichtbar und dann Absturz.

**Comment by mcuiobroker** [comment]
Hab versucht es auf Android 9 zu installieren.
-> App wurde nicht installiert als Hinweis.

**Comment by Zefau** [comment]
Capacitor geht ab 22, aber Jarvis ist auf 28. Ich versuch mal 27

**Comment by Zefau** [comment]
KNOX scheint aber was von Samsung zu sein. Eigentlich steht die Android Version für ein bestimmtes API Level, siehe https://apilevels.com/

**Comment by mcuiobroker** [comment]
Ja, die unterscheiden sich aber kaum. Nur bei bestimmten API Level hat Samsung noch Zwischen API-Level eingeführt. Gibt es glaube ich auch eine Tabelle. Capacitor sollte ab API-Level 21 unterstützen bzw. funktionieren.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.48` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.48`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Also auf KNOX API Level 37 läuft es jetzt.
Auf KNOX Level 27 Android 9 nicht -> App wurde nicht installiert.

**Comment by Zefau** [comment]
Welches Handy hast du genau? Dann probiere ich das mal im Emulator aus.

**Comment by mcuiobroker** [comment]
SM-G955F Samsung S8+

**Comment by Zefau** [comment]
Leider gehen die Android Studio Emulatoren nur mit Pixel-Geräten bzw. nativen Android.

**Comment by mcuiobroker** [comment]
Ist auch nicht so wichtig. Läuft ja jetzt auf den meisten Geräten.
