### ISSUE TITLE
 Calender zeigt (vergl. #2414) - keine Updates/veröffentlichte Beta seit vielen Monaten 

### ISSUE THREAD

**Issue by KaJu99** [Zefau/ioBroker.jarvis#2711]
Hallo,

der im Betreff benannte Fehler besteht mit Version 3.1.8 seit über einem Jahr; kurzfristig war das mit der Beta-Version 3.1.9 gefixt, die aber nicht mehr im ioBroker (Beta-) Repository zur Verfügung steht, auch keine spätere Beta.
Vor diesem Hintergrund daher einfach die Frage, ob prinzipiell eine Weiterentwicklung erfolgt? Es mag ja gute Gründe geben, kein Problem; wenn nicht, wäre es nur schön, dass dann eben zu kommunizieren/wissen. 
Danke

**Comment by Zefau** [comment]
Es nervt, dass die Weiterentwicklung immer wieder infrage gestellt wird. Hier im Repository wird aktuell regelmäßig eine Beta veröffentlicht. Es tut sich viel, aber es dauert eben.

Einfach für ein Issue voten oder kommentieren, dann sehe ich anhand der Rückmeldung wie dringlich es ist.

**Comment by Zefau** [comment]
#2414

**Comment by Zefau** [comment]
Ist mit 3.1.9 behoben und sollte auch mit 3.2.x passen?

**Comment by Erwin40** [comment]
Funktioniert übrigens mit der beta.45-46 wieder super.
Kann geschlossen werden, meiner Meinung nach :-)

**Comment by Zefau** [comment]
@KaJu99 könntest du auch einmal mit der aktuellen beta schauen, ob es bei dir funktioniert?

**Comment by KaJu99** [comment]
> @KaJu99 könntest du auch einmal mit der aktuellen beta schauen, ob es bei dir funktioniert?

habe jetzt seit letzter Woche erfolgreich die beta.44 am laufen; mein vordringliches Problem mit dem Kalender ist damit auf jeden Fall gefixt; ob der Import von HM-Geräten vollständiger funktioniert muss ich noch prüfen, ein Problem dass ich schon seit der 3.0 mitschleppe

**Comment by Zefau** [comment]
> Import von HM-Geräten vollständiger funktioniert muss ich noch prüfen, ein Problem dass ich schon seit der 3.0 mitschleppe

Dafür gibt es schon ein Feature Request?

**Comment by KaJu99** [comment]
Hi, habe heute die letzte Beta installiert (beta.52); Kalender geht, die nachfolgend geschilderten Eigenheiten mögen bereits länger bestehen, ich hatte mich in letzter Zeit kaum mit Anpassungen in meiner GUI beschäftigt und ich habe jetzt nicht alle Release-Notes durchgesehen um zu beurteilen ob das beabsichtigte Änderungen waren/sind.
Zum Homematic Import gibt es ein Issue #2472; bei mir wurden von 71 HM-Geräten ca. 20 mit vermeintlich "undefinierten Datenpunkten" nicht importiert. Dabei handelt es sich hauptsächlich um HM-BidCos RF und Wired Geräte; aber auch HM-IP RF wie z.B. der 5V USB Schalter (Bausatz). Ich habe mir da bisher mit der manuellen Anlage geholfen. Etwas umständlich dabei ist, dass man bei der manuellen Anlage via GUI keinen Hersteller festlegen/angeben kann, die manuell angelegten Geräte somit nicht in der Gruppe der aut. importierten Geräte sind (habe ich dann mühselig im JSON-File editiert. Ich meine in der Version 2 von Jarvis wäre diese Option vorhanden gewesen. Heute ist mir (in der aktuellen beta.52 aufgefallen, dass es bei der Geräte-Anlage bzw. Import div. Änderungen gibt (ggf. schon länger?) So werden mir beim Import nur zwei Adapter angeboten (HomeMatic und "Das Wetter"?!?), für die gesucht werden kann (installiert sind 26 Adapter) und die bereits vorhandenen Geräte (Geräteliste) können nur nach vermeintlicher Funktion (Gewerk), Raum, Etage oder Tag gruppiert werden, die Gruppierung nach Hersteller (fand ich sehr hilfreich) gibt es gar nicht mehr. Woraus sich die Gruppierung jeweils ergibt, muss ich noch analysieren, auf den ersten Blick sind die Geräte einigermaßen durcheinander gewürfelt.

**Comment by Zefau** [comment]
> So werden mir beim Import nur zwei Adapter angeboten 

Das klingt falsch. Mach bitte ein Issue mit Screenshot und Fehlermeldung der Browser-Konsole (via F12) auf.
