### ISSUE TITLE
[v3.2.0-beta.40] "DistanceToNowStrict" aus Globale Einstellungen wird nicht in die Geräte DP übernommen

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2712]
Hallo erst Mal :-)

Nach einem Updaten von der 3.1.8 auf die 3.2.0-beta.40 (über Katze und GitHub Link) wird "DistanceToNowStrict" nicht in die Geräte Datenpunkte übernommen. Dort steht "distancetonow".

Desweiteren sind die "Body Elemente" in den StateListen leer, obwohl dort zuvor die Auswahl aus dem Geräte DP stand (in Grau)
Gibt man im jeweiligen StateList-Eintrag "LastChangeBody" an, steht dort korrekterweise standardmäßig der Inhalt "DistanceToNowStrict" aus der Globalen Einstellung drin.
Seltsamerweise sind davon nicht alle meine StateListen betroffen.

Browser-Cache gelöscht und Cache im Web-Adapter deaktiviert. RaspberryPI4 neu gestartet.

Vorher (3.1.8)
![grafik](https://github.com/user-attachments/assets/4484ed63-cd85-41e3-8eeb-d9643f22f33b)
![grafik](https://github.com/user-attachments/assets/f517ddb5-cbd9-41dc-90ae-d67b001e7297)

Nachher(3.2.0-beta.40)
![grafik](https://github.com/user-attachments/assets/8c8f62d0-032b-4f2f-8c38-3cb050bcbb99)
![grafik](https://github.com/user-attachments/assets/31e6ce1c-e52c-4d65-a86f-78f199190e36)

**Comment by Erwin40** [comment]
Nachtrag:

Der Fehler ist scheinbar auch in der 3.2.0-beta.14 drin.
Dort habe ich mal einen neuen Datenpunkt angelegt und bei "Body Element" "LastChangeBody" ausgewählt.
Geht man dort jetzt in die "Komponenten Optionen" steht auch dort "distancetonow".

![grafik](https://github.com/user-attachments/assets/17f46d9a-b839-4558-9dbb-afb350dc5d3d)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.57` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.57` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Wird nur noch `TS` angezeigt
![image](https://github.com/user-attachments/assets/41b3f2af-44be-4dcb-960b-71b15e91eeb0)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Hatte die 58 gar nicht getestet...
Jetzt bin ich auf beta.60
Der Fehler ist jetzt auf jeden Fall weg und `DistanceToNowStrict` wird sauber übernommen. 👍 
Ich schließe...
