### ISSUE TITLE
[v3.2.0-beta.20 - 40] Widget keine Secondary States mehr möglich

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2713]
Ich weiß, da gibt es schon einen issue [https://github.com/Zefau/ioBroker.jarvis/issues/2707](url)

Aber der Fehler ist schon mit der beta.20 reingekommen.
Somit kann ich mit keiner Beta-Release zw. 20 - 40 arbeiten um die neuen Funktionalitäten nutzen zu können.
**Ich habe bei der beta.20 sogar mal den Adapter gelöscht und neu installiert (Zwischendurch IOB Restart und Cache gelöscht)
Danach war wie erwartet alles weg und ich habe mit einem komplett nackten Jarvis neu angefangen. Ein paar Datenpunkte angelegt und ein einsames Widget.
Auch hier, der gleiche Fehler!**
NPM: 10.7.0
Node.js: v18.20.4
JS-Controller: 5.0.19
Gibt es denn hier keinen Workaround um diesen Fehler zu umgehen? :-)

Die Version 14 hat leider den Fehler, das bei den StateList Einträgen kein "Body State" und "Action State" änderbar ist.
Es steht nach dem Speichern IMMER der 1. Eintrag aus der Liste drin.

![grafik](https://github.com/user-attachments/assets/edc0bee2-8c51-4d4c-8401-d4f850ff0f9c)

Gruß Micha

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2707

**Comment by Erwin40** [comment]
Wenn das wirklich funktioniert, dreh ich durch :-)
Ich bin auf die 3.2.0 schon so heiß...
Und nur weil ich "stateListItemHistory" gesehen habe, und das auch unbedingt haben wollte.
Ja, soll scheinbar auch mit der 3.1.8 laufen, aber das habe ich erst später richtig gelesen, da war es schon zu spät und ich wollte nicht mehr zurück.

Ansonsten muss ich sagen: Das ist schon hart was du da so alles zusammencodierst!
Ich bin zwar auch schon seit über 20 Jahren als Anwendungsprogrammierer in unterschiedlichen Sprachen beruflich tätigt,
aber das übersteigt mein Niveau.
Also 👍 👍 👍
