### ISSUE TITLE
[v3.2.0-beta.46] Browser ID - 192-168-178-77_ no -browser-detected , Browser wird nicht erkannt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2715]
![image](https://github.com/user-attachments/assets/b85816f2-1195-445a-a7b1-b3689d6a63bf)

![image](https://github.com/user-attachments/assets/2043b1f7-05e2-4fb1-a601-5c949a99e985)
Microsoft Edge 126
![image](https://github.com/user-attachments/assets/04c58cd3-815f-4787-99a0-8fec0889d9e1)

Was beim UserAgent auffällt -> Anzeige mit URL-Kodierung?
```
Mozilla%2F5.0%20(Windows%20NT%2010.0%3B%20Win64%3B%20x64)%20AppleWebKit%2F537.36%20(KHTML%2C%20like%20Gecko)%20Chrome%2F126.0.0.0%20Safari%2F537.36%20Edg%2F126.0.0.0
```

Normal wäre
```
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/126.0.0.0 Safari/537.36 Edg/126.0.0.0
```

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.48` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.48` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
