### ISSUE TITLE
[v3.2.0-beta.X] Bitte kein pauschaler Reload (auf allen Geräten) beim Verlassen der Konfig mit "Abbrechen"

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2716]
Sind Scripte in Jarvis eingetragen, wird beim Verlassen der Konfiguration immer pauschal ein Reload auf allen Geräten durchgeführt.
Das sollte aber wenn "Enable Scripts" auf false steht, nicht so sein. Hier sollte es so sein, als ob keine Scripte eingetragen wären.

Zweitens, sollte beim "Abbrechen" kein Reload durchgeführt werden, denn man hat ja nix geändert.
Das führt gerade in der Entwicklungsphase zu unnötigen Wartezeiten :-)

Ansonsten, so langsam wird die 3.2.0... richtig super :-)
Tolle Leistung die du da vollbringst 👍

**Comment by Erwin40** [comment]
Hi.

### Aktuell beta.49
Editieren Jarvis auf dem PC

Mit **deaktivierten** Jarvis-Scripte:
Beim Abbrechen wird immer noch ein Reload ausgelöst.
Beim Speichern (egal ob mit oder ohne Änderung, zwei Reloads auf dem PC und einer auf den iPads.
Hier ist anzumerken, dass jeder Reload etwas länger dauert und kurzfristig ein lila Hintergrundbild mit dem Jarvis-Logo in der Mitte, angezeigt wird. Bei zwei Reloads wird das dann schon ziemlich holprig und ist bei der Entwicklung mit vielen klenen Änderung etwas störend.
Übrigens, der Jarvis-DP (jarvis.0.settings.reload) hat keinen Einfluss, egal ob der auf true oder false steht.

Mit **aktivierten** Jarvis-Scripte:
dito, kein Unterschied feststellbar.

Ohne Script (gelöscht in den Einstellungen):
Beim Abbrechen kein Reload mehr!
Beim Speichern nur ein kurzer und unauffälliger Reload, auch nicht auf den iPads. Die Änderungen werden sauber gespeichert und auf allen Geräten aktualisiert! *freu*
Leider eben ohne Jarvis-Scripte *heul*

Übrigens: Wird Jarvis oder der Raspi, neu gestartet, reconnecten sich zwar die Clients, aber die Werte werden nicht mehr aktualisiert!
Das war in der 3.1.8 definitiv nicht so und hat immer super funktioniert. Das fand ich immer echt toll.

So, ich hoffe ich konnte dir für die "Fehler" Suche weitere Detailinfos liefern.

**Comment by Zefau** [comment]
Der Reload erfolgt wegen `@import`

**Comment by mcuiobroker** [comment]
Kann man die nicht evtl. dynamisch Nachladen?
```
try {
    const module = await import('./additional-module.js');
    module.init(); 
    console.log('Module loaded successfully');
} catch (error) {
    console.error('Failed to load module', error);
}
```

**Comment by Erwin40** [comment]
Ich wüsste nicht mal, wo ich den Auszug hinpacken sollte :-)

Das bei Import Jarvis noch einmal lädt kenne ich schon von der 3.1.8
Aber eben nur einmal und nicht zweimal ;-)

**Comment by Zefau** [comment]
> Kann man die nicht evtl. dynamisch Nachladen?
> 
> ```
> try {
>     const module = await import('./additional-module.js');
>     module.init(); 
>     console.log('Module loaded successfully');
> } catch (error) {
>     console.error('Failed to load module', error);
> }
> 
> // oder mit eval?
> fetch('additional-script.js')
>     .then(response => response.text())
>     .then(scriptContent => {
>          eval(scriptContent);
>     })
>     catch(error => console.error('Script failed to load', error));
> ```
> 
> Wäre komplizierter, da man prüfen muss was ist schon geladen und evtl noch andere Dinge?

Jo, finde ich gut. Ich nehme das mal für v4 auf die Roadmap.

**Comment by Erwin40** [comment]
v4? 😱
Äh, gibt es da schon einen Zeitplan ☺️
Sorry wenn ich frage, aber ich kann ohne Jarvis nicht mehr leben 😉

**Comment by Zefau** [comment]
Gibt keinen Zeitplan. Ich bekomme ja nichtmal die v3.2 fertig.

Es sind ja 3 Dinge:
- beim Verlassen der Konfiguration nicht pauschal einen Reload durchführen: Hierfür muss ich die Lösung von mcuiobroker umsetzen, was im Zweifel wieder zu Bugs führt, daher v4
- wenn "Enable Scripts" auf false steht, sollte kein Reload ntowendig sein. Das ginge sicherlich noch in v3.2, aber stört dich wahrscheinlich nicht so stark?
- beim "Abbrechen" kein Reload durchgeführen -> analog zu Nr- 1

**Comment by Erwin40** [comment]
Ok, danke für die Info.

Am meisten eigentlich "Abbrechen".
Hier ist es so, dass ich oft einen zweiten Tab auf habe um dort Einstellungen von einem anderen Gerät / Widget anzuschauen und ggf. Daten/Einstellung dort herauskopiere. wenn ich dann in diesem zweiten Tab die Einstellungen verlasse, um das Layout zu begutachen, damit ich weiß was ich im ersten Tab vielleicht anders haben will, dann verhaut es mir die Seite im ersten Tab.
Das nervt etwas bei vielen kleinen Änderung in der Entwicklungsphase einen neuen Widgets :-)
Und früher habe ich Layout- und Änderungen an Geräten, auch auf dem iPad gegenkontrolliert.
Das geht jetzt mit aktivem und aktivieren Script gar nicht mehr. Der Reload dauert da solang, dass du gar nicht mehr siehst was du geändert hast ;-)
Und hier wäre der funktionierende "Enable Script" Schalter, schon ganz geschickt.
Hört sich vielleicht alles etwas verwirrend an, aber ich mache "leider" gerade viel mit Jarvis. Und meine Seiten "Leben" ungemein.
Liegt vielleicht auch daran, dass "kreativ" nicht meine stärkste Seite ist und ich oft feststelle, dass ich noch etwas "optimieren" kann.
Das Teil (Raspi und insbesondere Jarvis) machen mir einfach zu viel Spaß.
Daher auch mein großes Interesse an der v4 :-)

Ach ja, und das da, ist halt einfach nur geil, und der eigentliche Auslöser für die beta.x
![grafik](https://github.com/user-attachments/assets/eb7a1769-7b61-4b48-939d-47cab14e0374)

Ich könnte die ganze Zeit draufstarren 🤣

**Comment by mcuiobroker** [comment]
Schalte doch für die zeit Deiner Entwicklungsphase die Skripte aus.

**Comment by Erwin40** [comment]
Kleiner Witzbold :-)
Wenn das denn mit dem "Enable Script" DP gehen würde.
Hmmm, oder ich bastle mir ein Java-Script und manipulieren den Jarvis-DP `jarvis.0.scripts`

**Comment by mcuiobroker** [comment]
Ja, wenn `jarvis.0.settings.scriptsEnabled` -> `false` `jarvis.0.scripts` in einen anderen DP sichern und ihn löschen, bei `true` aus dem anderen DP Sicherung holen.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.55` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.55`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Erwin40** [comment]
Würde ich gerne. Aber wie komme ich an die ran?
Und was wurde behoben?
Kein Speichern bei "Abbrechen" ?
Doppelter Reconnect?
Abschalten der Scripts, ohne Einfluss auf Reconnect?

MfG

**Comment by Zefau** [comment]
> Würde ich gerne. Aber wie komme ich an die ran?

Liegt normal im Repo wie sonst auch.

> Und was wurde behoben?

`Kein Speichern bei "Abbrechen" ?` wurde behoben, sofern Scripts abgeschaltet sind.

> Übrigens: Wird Jarvis oder der Raspi, neu gestartet, reconnecten sich zwar die Clients, aber die Werte werden nicht mehr aktualisiert!

Sollte nicht vorkommen. Also mit Reconnect sollten sich die Werte trotzdem aktualisieren.

**Comment by Erwin40** [comment]
Hi.
Ja, jetzt sehe ich sie.
Konnte nun endlich testen.
Ja, wenn "scriptsEnabled" = false, dann wird bei "Abbrechen" kein Reconnect durchgeführt.
Aber warum wird bei "scriptsEnabled" = true und "Abbrechen" überhaupt ein Reconnect durchgeführt?
Liegt das an der Natur der Jarvis-Scripte, falls an diesen was geändert wurde?
Bei Imports werden diese ja extern editiert und das bekommt Jarvis ja eh nicht mit.
Wenn ich da was ändere mache ich sowieso immer eine F5 Aktualisierung.

Ich weiß, ich bin unverschähmt, aber auch bei "scriptsEnabled" = false und "Speichern..." hätte ich erwartet, dass gar kein Reconnect durchgeführt wird 😁 
Momentan behelfe ich mir tatsächlich mit einem Blockly-Script. Aber dann hätte ich den neuen Switch so nicht gebraucht und gleich einen eigenen State anlegen können ;-)

Und bei = true ist der doppelte Reconnect immer noch drin :-)
Der Unterschied zu true/false ist also momentan (am PC) das hier bei false nur noch ein Reconnect durchgeführt wird.
Sorry, dass ich hier vielleicht etwas penetrant bin. Aber diese ganze Reconnecterei macht die Entwicklung umfangreicher Tabs doch etwas holprig. 
Da bin ich von der doch tollen 3.1.8 vielleicht etwas verwöhnt.

**Comment by Zefau** [comment]
>  Bei Imports werden diese ja extern editiert und das bekommt Jarvis ja eh nicht mit.

Es gibt in Javascript kein `@import`. Die Idee ist von CSS geklaut und gibt es nur in jarvis.
jarvis liest das aus, extrahiert die Datei und lädt es dann wie ein normales Javascript via `<script>` Tag.

Ggf. funktioniert alternativ `import` (siehe https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import) statt `@import`?

**Comment by Zefau** [comment]
Ab der nächsten beta führt `@import` zu einem Reload, aber `import` nicht. Probier gerne mal rum, ob `import` zu Problemen in der Skript-Ausführung führt.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.60` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.60`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Erwin40** [comment]
Installiert und funktioniert 👍 
Aber, oops Fehlermeldung in der Browser Konsole entdeckt und StateListItemHistory funktioniert nicht mehr:
`00:44:50.618 Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://192.168.177.13:8082/0_userdata.0/jarvisScripte/jarvisDPs.js. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 200.

00:44:50.619 Modul-Quell-URI ist in diesem Dokument nicht erlaubt: "http://192.168.177.13:8082/0_userdata.0/jarvisScripte/jarvisDPs.js". [index.html](http://raspberrypi4-ede:8400/jarvis/index.html#/0559b5e5-1c56-4ea4-8211-d51226417202)
00:44:50.626 Quellübergreifende (Cross-Origin) Anfrage blockiert: Die Gleiche-Quelle-Regel verbietet das Lesen der externen Ressource auf http://192.168.177.13:8082/0_userdata.0/jarvisScripte/stateListeItemHistory2.js. (Grund: CORS-Kopfzeile 'Access-Control-Allow-Origin' fehlt). Statuscode: 200.

00:44:50.627 Modul-Quell-URI ist in diesem Dokument nicht erlaubt: "http://192.168.177.13:8082/0_userdata.0/jarvisScripte/stateListeItemHistory2.js". [index.html](http://raspberrypi4-ede:8400/jarvis/index.html#/0559b5e5-1c56-4ea4-8211-d51226417202)`

**Comment by Erwin40** [comment]
Anmerkung:
Ja, ich habe die Scripte nicht direkt unter `0_userdata.0` sondern im Unterordner `jarvisScripte`

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.60` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.60`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Erwin40** [comment]
beta.62
Da der ursprüngliche Issue erledigt ist, soll ich schließen und für den `Cross-Origin` Fehler einen neuen aufmachen?
_Den habe ich ürigens auch wenn ich die Scripte direkt unter `0_userdata.0` ablege._

**Comment by Erwin40** [comment]
Ok, aber das hier verstehe ich nicht ganz: `iobroker upload jarvis`
Das schiebt mir doch nicht die Scripte rüber, sondern macht nur den upload von Adapter Dateien
Ich muss die Scripte dann mit FileZille z.B. hochladen, oder?

**Comment by Erwin40** [comment]
Funktioniert leider nicht...
Das sind meine Imports (z.Z. noch alles ohne https):
import "http://raspberrypi4-ede:8400/user/jarvisDPs.js";
import "http://raspberrypi4-ede:8400/user/stateListeItemHistory2.js";

Browser-Console:
`10:26:41.721 Laden des Moduls von "http://raspberrypi4-ede:8400/user/jarvisDPs.js" wurde auf Grund eines nicht freigegebenen MIME-Typs ("") blockiert.
[index.html](http://raspberrypi4-ede:8400/jarvis/index.html#/351097ea-e3f7-4991-add6-0cba50b20afb?reload=false)
10:26:41.721 Laden fehlgeschlagen für das Modul mit der Quelle "http://raspberrypi4-ede:8400/user/jarvisDPs.js". [index.html](http://raspberrypi4-ede:8400/jarvis/index.html#/351097ea-e3f7-4991-add6-0cba50b20afb?reload=false)
10:26:41.721 Laden des Moduls von "http://raspberrypi4-ede:8400/user/stateListeItemHistory2.js" wurde auf Grund eines nicht freigegebenen MIME-Typs ("") blockiert.
[index.html](http://raspberrypi4-ede:8400/jarvis/index.html#/351097ea-e3f7-4991-add6-0cba50b20afb?reload=false)
10:26:41.722 Laden fehlgeschlagen für das Modul mit der Quelle "http://raspberrypi4-ede:8400/user/stateListeItemHistory2.js". [index.html](http://raspberrypi4-ede:8400/jarvis/index.html#/351097ea-e3f7-4991-add6-0cba50b20afb?reload=false)`

**Comment by Zefau** [comment]
Wenn du die URL direkt aufrufst, wird dann das Javascript im Browser angezeigt? Der Upload ist notwendig, um ioBroker zu sagen, dass es da eine Datei gibt.

**Comment by Erwin40** [comment]
Nein.
Dateien liegen dort wie von dir vorgeschlagen:
![grafik](https://github.com/user-attachments/assets/3405cd1a-fe60-4e37-86de-03dd2ea73ead)

**Comment by Zefau** [comment]
Wenn du die URL im Browser eingibst und die Datei nicht ausgegeben wird, dann musst du `ioBroker upload jarvis` machen, damit ioBroker die Datei kennt.

**Comment by Erwin40** [comment]
Ja, habe ich gemacht. Da tauchen die Dateien aber auch nicht auf.
Habe jauch schon einen Ordner tiefer versucht und auch mal direkt in die Ordner abgelegt.
Auch die Berechtigungen habe ich angepasst.
![grafik](https://github.com/user-attachments/assets/e6744bb5-1850-45da-bb4b-b6e9418835f7)

**Comment by Erwin40** [comment]
Mist!
Habe die Instanz mal gelöscht und neu hinzugefügt.
Jetzt ist alles weg :-(
Beim Start sagt mir das Log, dass er keine Backups gefunden hat:
![grafik](https://github.com/user-attachments/assets/0b5d6e61-b347-404f-8cfb-a0e36872ba6b)

Aber in der Adapter-Konfig unter Datensicherungen:
![grafik](https://github.com/user-attachments/assets/18117916-65b5-4e4c-ace8-afc5f7fda853)

**Comment by Erwin40** [comment]
Also ein Restore über die Jarvis Instanz habe ich nicht hinbekommen.
Ich musst den Adapter löschen, neu installieren, Instanz erstellen und über BackitUp restoren.
Da werden aber die Einstellungen nicht mit restored. Die konnte ich dann über das Jarvis-Backup wiederherstellen.
Jetzt läuft erst mal wieder alles.

**Comment by Zefau** [comment]
Schieb es mal bitte in `/opt/iobroker/node_modules/iobroker.jarvis/www/jarvis/user` dann sollte es nach einem `iobroker upload jarvis` automatisch unter `/opt/iobroker/iobroker-data/files/jarvis/user` liegen und via `http://<ip>:8400/user/script.js` aufrufbar sein.

**Comment by Erwin40** [comment]
Zeile 242:	`if ( (keypressedIP == browserIP) ) {`

**Comment by Erwin40** [comment]
Ich habe die beiden Scripte jetzt kurzerhand fusioniert.
Und es werden die stateListItemHistory's wieder angezeigt.
Aber das Ablegen der Scripte ist sehr umständlich. Zudem muss (so habe ich das Gefühl) die Jarvis-Instanz bei jeder Änderung, neu gestartet werden.
Da sollte man vielleicht doch den ursprünglichen `Cross-Origin` Fehler beheben.
Für mich soll es damit erst mal erledigt sein.
Wenn es mich nervt, mache ich zu gegebener Zeit einen neuen Issue auf :-)
