### ISSUE TITLE
Reloading the page or restarting the Android app is necessary after logging in

### ISSUE THREAD

**Issue by Paradoxa** [Zefau/ioBroker.jarvis#2718]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? 
   - v3.2.0-beta.40
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
   - No screenshot available.

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
* Android App bleibt nach Login scharz und muss geschlossen und wieder geöffnet werden
* Web App bleibt nach Login im weißen Screen und muss mit F5 neugeladen werden

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
- No screenshot available.
____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
sollte mit `v3.2.0-beta.48` passen

**Comment by Paradoxa** [comment]
I updated it today and will give you feedback on how it works.
It already works in the web app. Not yet on the Android app. Unfortunately, when installing the APK, the error message appears: "The app was not installed because the package is apparently invalid."
The last version that can be installed is "jarvis-android_v3.2.0-beta.40.apk". The phone is a Samsung Galaxy S23 Ultra.

**Comment by Paradoxa** [comment]
I can not open link.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/releases/tag/v3.2.0-beta.54

**Comment by Zefau** [comment]
Also generell auf der Release Page https://github.com/Zefau/ioBroker.jarvis/releases

**Comment by Paradoxa** [comment]
Thank you very much for the information. I had to uninstall the app so I could reinstall it.
The reloading has been fixed in this version. Thank you very much.
