### ISSUE TITLE
[v3.2.0-beta.47] Übersetzung der stateKey bei Auswahl im Widget?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2719]
![image](https://github.com/user-attachments/assets/de4752ef-c11d-47f9-b259-0ac3c183faf6)

![image](https://github.com/user-attachments/assets/06f80363-811b-4d35-9a28-ba669c4968e0)

**Comment by Zefau** [comment]
Wo ist da was übersetzt? Du hast einen Typo drin oder?

**Comment by mcuiobroker** [comment]
Da wo `on` stehen im Dropdown wird `an` angezeigt. Da kann ich gar nichts falsch eingaben, ist die Auswahl der stateKeys.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.50` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.50` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Warum der Wert in Klammern?
Sonst passt es. Danke.

**Comment by Zefau** [comment]
Das ist der eigentliche Wert. Das andere ist das Label. Wenn beides gleich ist, dann gibt es keine Klammer.
