### ISSUE TITLE
Request: Widgets in andere Spalten verschieben

### ISSUE THREAD

**Issue by mandragora666** [Zefau/ioBroker.jarvis#272]
Hallo Zefau,

Ich hätte hier ein Feature Request.
Fein wäre es wenn man bei den Spalten die Widgets auch verschieben könnte.

![image](https://user-images.githubusercontent.com/73381262/97538086-22037800-19c0-11eb-9027-afa7f045f8d5.png)

Ist vor allem fein wenn man seine VIS zusammenbaut und viel herumprobieren muss bis es passt.
So muss man die Widgets für jede Spalte immer neu anlegen.
So wäre es halt einfacher.

Vielleicht lässt sich das ja irgendwann mal machen.

Vielen Dank für deine Bemühungen.

lg
mandragora

**Comment by Zefau** [comment]
duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/175
