### ISSUE TITLE
Keine Speicherung von Daten im BodyElement bei den Widgets

### ISSUE THREAD

**Issue by Robbi12** [Zefau/ioBroker.jarvis#2721]
Wenn ich bei den Widgets bin und über das Hamburgermenü bei den BodyElements gehe, werden die Daten nicht gespeichert. Ich kann da was ändern. Wenn ich speichere und wieder zurück gehe, stehen die gleichen Werte drin. Auch in der Anzeige keine Änderungen,

Bin auf der letzten Beta

**Comment by Erwin40** [comment]
Hi.

Hast du mal ein ScreenShot? Eigentlich sollte das BodyElement funktionieren.
Aber ich kenne da gar kein Hamburgermenü...

**Comment by Robbi12** [comment]
Gerade nicht am Rechner. Vielleicht mit Hamburger Menü falsch bezeichnet. Den Bereich bei BodyElements wo man z.B. die Anzahl der Schitte einstellen kann

**Comment by Robbi12** [comment]
![Screenshot 2024-07-26 151838](https://github.com/user-attachments/assets/a509c323-389e-4066-a1ac-a935d302c062)
![Screenshot 2024-07-26 151909](https://github.com/user-attachments/assets/7f713041-185e-489d-ad39-8e68948753a1)

**Comment by Zefau** [comment]
Bei funktioniert es. Wähle ich ein BodyElement und gehe dort in die Optionen, dann speichert er dies bei mir. Hast du Fehler in der Browser-Konsole via F12?

**Comment by Robbi12** [comment]
Ich nutze Edge. Da tut sich gar nichts mit F12

**Comment by mcuiobroker** [comment]
Klar gibt es da F12
![image](https://github.com/user-attachments/assets/c0df4afe-fb5e-42f4-bb38-8b7d31f16480)

**Comment by Robbi12** [comment]
Ne ändert sich in der Konsole nichts. Geht bei mir nicht über F12 auf sondern über Weitere Tools. Das wird gezeigt

![image](https://github.com/user-attachments/assets/3246ccbe-be6a-41bc-916c-b15afb8adeca)
``

**Comment by mcuiobroker** [comment]
Das ist das Browswe Log.

**Comment by Robbi12** [comment]
Hab ich es jetzt richtig gemacht? Ich seh keine Fehler. Wenn ich aber die TAbs ändere, ändert sich im BrowserLog nichts.

**Comment by Zefau** [comment]
Ist das denn die Browser Konsole während du etwas im BodyElement speicherst? Die Frage ist ja nicht was generell so drin steht, sondern was drin steht, wenn bei dir der Fehler auftritt.

**Comment by Robbi12** [comment]
Ja das ist das wenn ich jarvis aufrufe. Wenn ich was speichere, ändert sich nichts in der Konsole. Also keine Fehler usw.

**Comment by Robbi12** [comment]
Gerade noch einmal getestet. Egal was ich dem Punkt ändere, es wird nicht gespeichert. Es ändert sich nichts. Wenn es bei dir funktioniert dann muss es doch was in meinen Einstellungen sein oder?

**Comment by Robbi12** [comment]
So. Jetzt wird es für mich ganz komisch.

Wenn ich die Datenpunkte ändere und auf speichere gehe, dann sind sie beim erneuten öffnen wieder auf dem Standard.

Wenn ich nun die Datenpunkte im Io-Broker und widgets nehme, dann ist die Änderung drin.

Aber. Sie wird trotzdem auf der Jarvis Seite ausgeführt.

Der Zeitstempel hat sich übrigens im Ordner Widget geändert

**Comment by Zefau** [comment]
Hab den Fehler gefunden, fix kommt.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.49` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.49` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Robbi12** [comment]
Super. Funktioniert
