### ISSUE TITLE
Map wird mit neuester Beta nicht mehr angezeigt

### ISSUE THREAD

**Issue by Robbi12** [Zefau/ioBroker.jarvis#2725]
Hallo, ich habe die Beta 51. Hier wird die Map nicht mehr angezeigt. Widget Bereich noch da, aber keine Map

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.52` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.52` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Robbi12** [comment]
Nein. Update auf die neueste funktioniert nicht

**Comment by Robbi12** [comment]
Ok. Funktioniert teilweise. Auf dem Tablet und am PC ja. Auf dem Handy nein.

**Comment by Zefau** [comment]
Handy meint via Browser oder Android-App?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.53` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.53` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Robbi12** [comment]
Ich habe die Version 54 nun drauf. Funktioniert nicht. IFrame ist ganz klein. Bilder werden abgeschnitten bzw. teilweise angezeigt.

Hier das Beispiel
![Screenshot 2024-08-01 085653](https://github.com/user-attachments/assets/492a54fe-0e24-4668-8b50-0ead5423159c)
![Screenshot 2024-08-01 085742](https://github.com/user-attachments/assets/6edb5dc5-a6f1-4dbd-9e17-28ddfb1b60e9)

**Comment by Robbi12** [comment]
Das Fahrzeug sollte im oberen Widget sein. Die Karte sollte ganz geladen werden

**Comment by Robbi12** [comment]
Bei der Version 50 hat es zuletzt funktioniert

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.56` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.56` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Robbi12** [comment]
Hallo. Gerade getestet. Bin aber nicht sicher ob aussagekräftig, da ich vom Ausland über VPN darauf zugreife. Sollte aber doch gleich sein.

Die Karte wird wieder angezeigt. Jedoch ist der Punkt (Ort) weg. Ich muss im Reiter aktualisieren dann kommt der Standort. Geht aber gleich wieder weg und zeigt mir meinen Wohnort an.

**Comment by Robbi12** [comment]
Bei der 56 wird das Bild angezeigt. Bei der 57 wird auf dem Handy wieder kein Bild angezeigt

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Robbi12** [comment]
Ok. Bilder werden angezeigt.

Das was ich hier geschrieben habe ist aber immer noch vorhanden:

"Ich versuche es genauer zu beschreiben. Ich habe einen Tab "Wohnmobil". Dieser stellt den Standort des Fahrzeugs auf der Karte dar. Wenn ich Jarvis mit der z.B. Hauptseite starte und auf den Tab "Wohnmobil" gehe, kommt nur als Bild mein Wohnort und nicht der Standort wie eingestellt. Gehe ich dann unten auf den Button fährt die Karte in Richtung Standort, der Punkt ist aber nicht da. Erst wenn ich im Tab aktualisiere, wird der Punkt dargestellt. Die Karte fährt dann aber auf meinen Wohnort. Dort dann unten auf den Button und sie fährt dann zu dem regulären Standort"

Ich muss im jeweiligen Tab immer aktualisieren dass mit die Standortnadel angezeigt wird. Es wird beim TAbwechsel nicht automatisiert.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.60` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.60` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Robbi12** [comment]
Passt
