### ISSUE TITLE
3.2.0 BETA 51 keine ausgabe von energiefluss in iframe mehr zu sehen

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#2726]
In Beta49 war der Inhalt des Frames noch zu sehen. Mit Beta 51 ist es jetzt leer.
Die Ausgabe aus dem Energiefluss Adapter sollte eigentlich zu sehen sein.

Fehler in der Ausgabe aus dem Browser kann ich nicht wirklich zuzuordnen:

![image](https://github.com/user-attachments/assets/9839326f-450a-4f1d-80b3-da631b49c3ce)

![image](https://github.com/user-attachments/assets/71ea9a8d-4e3d-45b3-a6a2-3aaee033f7b0)

**Comment by Bernd9000** [comment]
Der socket Fehler sollte eine andere Ursache haben.
Hier das selbe Problem mit iFrame aber in der Konsole kein Fehler

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.52` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.52` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
v3.2.0-beta.52
iFrame baut nur sehr langsam auf, Zeilenweise wird das Bild aufgebaut.
Sieht aus als wenn es nach jeder Pixelzeile aktualisiert wird.

**Comment by MarkSau** [comment]
es wird wieder alles bei mir angezeigt.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.53` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.53` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Nein, Höhe stimmt nicht.
Egal ob "Tab Vollbild" oder "Höhe aller widgets identisch mit sichtbarer Seitenhöhe"

**Comment by Zefau** [comment]
Was stimmt denn nicht?

**Comment by Bernd9000** [comment]
Bilder zeigen den kompletten Bildschirm bei einem IFrame Widget mit Option "Tab Vollbild"
beta.6 - Vollbild funktioniert
![1](https://github.com/user-attachments/assets/0d217e94-63db-4dd4-b7c8-9e59a1300285)

beta.53 - nur ca. die häfte vom Bildschirm wird gefüllt
![2](https://github.com/user-attachments/assets/c119f19f-1aa9-48f4-829c-69166432ddc0)

**Comment by Bernd9000** [comment]
"hälfte" ist aber nicht fest, hab hier einige iFrames die sehr schmal geworden sind.

**Comment by Bernd9000** [comment]
Da ist mir dochj ein Fehler unterlaufen....
Das da oben ist kein IFrame Modul, sonder das Modul DiplayImage, sorry....
Die IFrame Module haben nur noch eine Pixelhöhe von 150

**Comment by fprobst170** [comment]
Kann ich leider nur bestätigen.
Bei mir haben die IFrame Widgets auch nur eine Höhe von 150 Pixel.
Egal ob ich beim Layout, "Tab Vollbild" ein oder ausschalte.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.56` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.56` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
v3.2.0-beta.56 - Erster Test
"Tab Vollbild" bei "IFrame" funktioniert wohl wieder.
Allerdings klappt die dynamische Anpassung nicht immer, manchmal wird eine Änderung der Auflösung nicht wargenommen.
Und.... ab und zu ist das IFrame leer, das heißt es wird nichts angezeigt (z.B. Kamerabild).

Im IOB Log taucht jetzt öffters ein "Client-Connection timeout" auf.

Im Browser Log taucht u.a. diese Meldung auf:

index.html:
Speicherverbrauch von "will-change" ist zu hoch. Die Budget-Grenze ist die Fläche des Dokuments multipliziert mit 3 (499422 px). Vorkommen von "will-change", die das Budget überschreiten, werden ignoriert.

**Comment by Bernd9000** [comment]
Nachtrag zu "TAB Vollbild" bei Modul "IFrame" und "DisplayImage".
Wenn  nur die vertikale Auflösung (Höhe) des Bildschirm sich ändert wird der Inhalt **nicht** angepasst.

**Comment by Zefau** [comment]
Bei aktivierter Option meinst du?
![grafik](https://github.com/user-attachments/assets/2ab48493-41e0-4df4-9478-e072ea397de9)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.57` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.57` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
v3.2.0-beta.57
Modul "Iframe" und "Displayimage" 
Bild baut sich von oben nur ganz langsam Pixelweise auf nach unten.

**Comment by fprobst170** [comment]
v3.2.0-beta.57

Bei "Tab Vollbild" sind das Modul "Iframe" und "Displayimage" gar nicht mehr sichtbar.
Auch der für mich funktionierende Workaround der beta.54 
`.jarvis-widget-c2949283-1eba-460f-b553-3b29bf8bf49d iframe { height: 100vh; }`
funktioniert nun auch nicht mehr.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
`v3.2.0-beta.58` Iframe wird gar nicht mehr angezeigt, keine Fehlermeldung
![image](https://github.com/user-attachments/assets/a3878a57-4049-4730-baec-945482117c1c)

**Comment by Bernd9000** [comment]
Ab und zu funktionieren die IFrames nach F5
Scheint so als gäbe es ein Zeitfenster das man genau treffen muß

**Comment by mcuiobroker** [comment]
`https://radar.wo-cloud.com/desktop/rr/compact?wrx=53.267,10.050&wrm=7&wry=53.267,10.050`
Bei mir nicht, egal wie oft ich F5 nutze.

**Comment by Bernd9000** [comment]
Hängt wohl vom Inhalt ab.
Ich hab hier noch ein IFrame mit dem Energiefluss Adapter, der wird immer angezeigt.
Vielleicht ein Problem mit den Sandbox Optionen ?

**Comment by Bernd9000** [comment]
> `https://radar.wo-cloud.com/desktop/rr/compact?wrx=53.267,10.050&wrm=7&wry=53.267,10.050` Bei mir nicht, egal wie oft ich F5 nutze.

Den Link habe ich mal in mein IFrame gepackt und dieser wird sofort angezeigt.
Sehr schwierig herauszufinden woran es liegt.

**Comment by fprobst170** [comment]
Bei mir funktioniert wieder `IFrame` und `Displayimage` mit und ohne "Tab Vollbild"

**Comment by Bernd9000** [comment]
Hauptsächlich betrifft es bei mir ein Kamera Bild von der Software "Blue Iris" das ich als iFrame eingebunden habe.
Ursache ist hier im HTML Code ein zusätzlicher Container mit folgendem Inhalt:

`<div id="camimg_wrapper" style="width: 1440px; height: 374.721px; transform: translate(-236.999px, -255.5px) scale(0.000001);" draggable="false" unselectable="on"><canvas id="openh264_player_canvas" class="videoCanvas" width="1440" height="376"></canvas></div>`

Bei tranform: translate sind dann bei einem Bildausfall negative Werte und der scale Faktor sehr klein.
Das heißt das Bild ist da, aber so klein das es nichtmal in einem Pixel paßt.
Die Funktion wird verwendet um in das Kamerabild zu zoomen.
Ich frage mich warum da solche Werte bei rauskommen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.60` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.60` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
@Zefau 
Du meinst beta.61 ?
Die gibts nur als apk oder zip ß

**Comment by Bernd9000** [comment]
v3.2.0-beta.62
Video läuft bei mir wieder.
Beim iFrame und DisplayImage und der Option "Tab Vollbild" wird bei Höhenänderung das Bild nicht angepasst.
Erst nach drücken von F5 ist es richtig.
Bei Änderung der Breite läuft es.

**Comment by mcuiobroker** [comment]
Weiterhin so
![image](https://github.com/user-attachments/assets/e49d18fc-61bd-4c1e-a102-c2d118a954f5)

**Comment by Bernd9000** [comment]
Und `sandbox` ist bei dir aktiv ?
Ich kriege nur ein leeres Bild wenn ich das deaktiviere

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/85487ac9-46d9-40a2-8ec8-8190d79c5cc4)

**Comment by Bernd9000** [comment]
Jo, ist bei mir auch so.

**Comment by bogaboo** [comment]
Ja, wenn "Aufrechterhalten" ausgeschaltet ist, wird bei mir das iframe der Kamera wieder richtig skaliert / positioniert,
Jarvis Version: v3.2.0-beta.62.

Allerdings erhalte ich im Log noch einen Fehler:    " Devices._listener[((a + ":") + u)] is undefined "

**Comment by Erwin40** [comment]
Kam bei mir auch.
Diese Meldung sollte aber im > beta.64 behoben sein.
Bitte schließen wenn OK

**Comment by Zefau** [comment]
> Allerdings erhalte ich im Log noch einen Fehler: " Devices._listener[((a + ":") + u)] is undefined "

Genau, das sollte behoben sein.

> Ja, wenn "Aufrechterhalten" ausgeschaltet ist, wird bei mir das iframe der Kamera wieder richtig skaliert / positioniert,

Das ist leider immer noch ein Problem und steht auf der Agenda, siehe https://github.com/Zefau/ioBroker.jarvis/issues/2537

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2537
