### ISSUE TITLE
Chart fehlerhaft in mobiler Ansicht

### ISSUE THREAD

**Issue by ScumbagSteve** [Zefau/ioBroker.jarvis#2728]
In der mobilen Ansicht skalieren die HistoryGraphs unaufhaltsam immer höher. 

Ungefähr jede Sekunde werden die Graphen wieder ein Stück länger. 

Ich verwende die aktuellste Beta 52

![image](https://github.com/user-attachments/assets/8d75c397-adf4-485f-9ab8-ac0a0d58b77c)

**Comment by Erwin40** [comment]
Hi, passiert auch bei einigen StateList Widgets bei mir (beta.51 dito)
Wenn du im Layout bei dem betreffenden Widget das Skalieren aktivierst ist der Fehler weg.
Geh zurück auf die beta.49, da wird zwar auch nicht runterskaliert, aber zumindest läuft das Widget nicht davon ;-)
Und die 49 läuft auch richtig flott!

**Comment by Zefau** [comment]
Besser mit `v3.2.0-beta.53` ?

**Comment by ScumbagSteve** [comment]
Da gehen bei mir die Widgets jetzt gar nicht mehr auf der mobilen Version :(

**Comment by Erwin40** [comment]
Leider immer noch unverändert.
Also bei mir wirds am iPad2 was angezeigt, aber die Widgest laufen immer noch nach unten sukzessive raus im Sekundentakt.
Und die Scrollbalken sind am PC auch noch fast überall drin.
Gehe wieder auf 49

**Comment by Erwin40** [comment]
Nachtrag:
Nach dem ganz hin und hergewechsel 49>52>49>53>49 beobachte ich verhäuft Timeouts beim Verlassen der Konfiguration mit "Abbrechen" und "Speichern & zurück"
Nicht nicht immer, aber immer wieder. Manchmal verschluckt er sich auch nur und die Seite wird nach ca. 20s angezeigt ohne das ein Timeout kommt. Wenn einer kommt sieht der so aus (Das war bis vor kurzem nur nach vielen Änderungen so):

![grafik](https://github.com/user-attachments/assets/1bdada91-7dc0-4aea-938e-d3d513f139e5)

Muss ich Issue aufmachen, oder gibt es eine Möglichkeit irgendwas zur bereinigen?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.56` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.56` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Grundsätzlich ja, was dass davonlaufen der Wigets auf den iPad anbelangt.
Aber es werden keine Charts, JSON-Tables und State-Html Inhalte angezeigt.
Davon betroffen ist auch AdapterLogs.

Und seltsamerweise wird bei einem einzelnen State-List Widget immer noch der Scrollbalken angezeigt.
Obwohl beide Widgets gleich konfiguriert sind. Und am History-Chart kann es nicht liegen, das habe ich auch in einem anderen Widget.
![grafik](https://github.com/user-attachments/assets/625cc363-c3d3-4a67-9c11-b4f50ee16d54)

Ah, gefunden :-)
Wenn ich Scripts disable, dann ist auch dort der Scrollbalken verschwunden.
Vermutlich weil bei diesem Widget die History-Chart im letztes Gerät drin ist.

**Comment by ScumbagSteve** [comment]
Also bei mir funktioniert es immer noch nicht. Allerlei Widgets werden jetzt gar nicht mehr angezeigt. 

Wie hast du es denn zum laufen bekommen?

(Und aus Interesse, wie hast du das kleine Zeilenchart da ins Gerät bekommen?)

**Comment by Erwin40** [comment]
Zu Zeilenchart:
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/scripts-3.1.x-pro/statelist/statelistitemhistory/scripts-statelisteitemhistory

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Jain :-)
Auf dem PC mit Firefox sieht soweit alles ok aus. Nur der Scrollbalken ist bei einem einzelnen State-List Widget mit History-Chart als letzter Eintrag, noch vorhanden. Damit kann ich aber erst mal leben.
Am iPad2 und 5 sieht es leider durchwachsen anders aus.
Die Option `Skaliere Inhalte zur Widget-Größe` hat bei `StateList` auf beiden Geräten keine Auswirkungen.
Auf dem iPad2 wird das Widget dem Inhalt entsprechend immer vergrößert dargestellt.
Also genau umgekeht, wie es die Option vermuten lässt.
Beim iPad5 wird das Widget zwar nicht vergrößert, also der Größenvorgabe entspr. angezeigt, aber der Inhalt wird nicht verkleinert, auch nicht wenn die Option aktiv ist.
HistoryGraph:
Auf dem iPad5 funktioniert die Option `Skaliere Inhalte zur Widget-Größe` einwandfrei. Wobei Charts ja eh immer skaliert werden.
Auf dem iPad2 wird bei aktivierter Skalierung das Widget in der Höhe plötzlich verkleinert. Ich habe sie daher bei allen Charts deaktiviert.
Jetzt zu `DisplayImage`:
Hier komme ich auf dem iPad2 gar nicht klar. Hier läuft das Widget entweder nach unten weg, wie ganz Anfangs beschrieben, oder der Inhalt nach oben raus. Je nachdem was man bei `Größe / Anpassung` eingestellt hat.
Hier habe ich aber den Schuldigen eben gefunden. Ich hatte in Styles nachfolgenden Code drin:
`.jarvis-widget-2417605b-cf69-4398-8dff-d981aaed569f .jarvis-widget-content {
	/* Vergrößerung */
	transform: scale(1.18) translateX(-40px) !important;
	margin: 5px;
	width: initial !important;
	height: initial !important;
}
`
Also erst mal erldigt. :-)
Nun zu AdapterStatus und ScriptStatus.
Auf dem PC:
Die Option `Skaliere Inhalte zur Widget-Größe` funktioniert, aber wenn diese deaktiviert ist, sollte der Scrollbalken angezeigt werden.
Auf dem iPad2:
Hat die Option keine Auswirkungen. Widget wird auf den Inhalt immer vergrößert.
Auf dem iPad5:
Hier hat die Option ebenfalls keine Auswirkungen, jedoch ist das Widget der Vorgabe entspr. groß und es gibt keinen Scrollbalken und Möglichkeit zu scrollen.
Ich weiß, dass sollte eigentlich in einen neuen Issue, aber wären diese Nebeneffekte nicht, hätte ich gesagt, dieser Issue kann geschlossen werden.

**Comment by Erwin40** [comment]
beta.60
Scrollbalken beim Widget mit `stateListeItemHistory` ist jetzt ohne Scrollbalen, also erledigt 👍  

Die Option `Skaliere Inhalte zur Widget-Größe` hat bei `StateList` auf den iPad2+5 keine Auswirkungen.
Aber zumindest ist das Verhalten nun völlig identisch. Das Widget wird auf dem iPad2 also nicht vergrößert.
Aber eben auf beiden auch nicht verleinert, wenn die Option aktiv ist.

HistoryGraph:
Auf dem iPad5 funktioniert die Option `Skaliere Inhalte zur Widget-Größe` einwandfrei. Wobei Charts ja eh immer skaliert werden.
Auf dem iPad2 wird bei aktivierter Skalierung das Widget in der Höhe immer noch zu klein dargestellt (Höhe). Ich habe sie daher bei allen Charts deaktiviert.

Das Widget `ScriptStatusliste` hat wieder den Scrollbalken am PC und auf dem iPad5 lässt es sich wieder srollen.
Das wäre erledigt. 👍 
Fehlt nur noch `AdapterLog` :-)

Es geht voran... 👍

**Comment by Zefau** [comment]
>  Fehlt nur noch AdapterLog :-)

Was genau funktioniert nicht und welche Einstellungen hast du hier?

**Comment by Erwin40** [comment]
Zu:
_Die Option Skaliere Inhalte zur Widget-Größe hat bei StateList auf den iPad2+5 **keine Auswirkungen**.
Aber zumindest ist das Verhalten nun völlig identisch. Das Widget wird auf dem iPad2 also nicht vergrößert.
Aber eben auf beiden auch nicht verleinert, wenn die Option aktiv ist._
D.h. der Inhalt des Widgets wird unten einfach abgeschnitten.

![grafik](https://github.com/user-attachments/assets/6c10eb83-81c6-4017-99fc-1937ffdd12ec)
![Jarvis](https://github.com/user-attachments/assets/848ed781-c792-4722-a544-e465b21f292a)

Zu AdapterLog:
Hier mach ja Skalierung kein Sinn, deshalb ist sie bei mir deaktiviert. Dann müsste aber ein Scrollbalken da sein auf dem PC.
Auf den iPads gibt es auch keine Möglichkeit zu scrollen.
![grafik](https://github.com/user-attachments/assets/af7b7687-0f65-4d50-8234-1067c15f35d3)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.64` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.64` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Zu:
Die Option `Skaliere Inhalte zur Widget-Größe` hat bei StateList auf den iPad5 Auswirkungen.
Wenn Skalierung ausgeschaltet ist, kann einwandfrei gescrollt werden.
Ist sie an, kann nicht mehr gescrollt werden, aber der Inhalt wird auch nicht verkleinert und somit unten abgeschnitten.
Auf meinem iPhone11 wird ist es etwas anders:
Hier kann bei deaktivierter Option sauber gescrollt werden. Ist sie aktiv, wird das Widget vergrößert, so das alles angezeigt wird.

Zu AdapterLog:
Passt, jetzt ist der Scrollbalken wieder da 👍 

Meine persöhnliche Meinung, ohne dir zu Nahe treten zu wollen:
Wenn das so eklatante Probleme macht, diese Option zu realisieren, dass sie auf allen möglichen Geräten und Browsern funktioniert...
Würde ich die mittelfristig rausschmeißen ;-) Mir persöhnlich erschließt sich die Sinnhaftigkeit auch nicht so ganz. 
Wenn ein Widget zu klein ist um den Inhalt aufzunehmen und dann skaliert wird, dann kann ich den Inhalt meist eh nicht mehr lesen. (Ok, vielleicht in Grenzfällen, wenn das Widget ein paar Pixel zu klein ist)
Aber ich bin ja auch schon älter und die Augen nicht mehr so wie mit 30 ;-)
Deine Versuche das ans Laufen zu bekommen auf allen möglichen Geräten und Browsern, behindert halt alle anderen, wirklich wichtigen Fehlerbehebungen ;-)
Zum Beispiel mein Script Import-Problem 😁

Meiner Meinung nach, könnter der Issue geschlossen werden.
Was meinst du @ScumbagSteve ?

**Comment by Zefau** [comment]
Der Sinn von `Skaliere Inhalte zur Widget-Größe` ist ja, dass bei deaktivierter Option gescrollt werden kann, aber aktivierter dann der Inhalt aber max. so groß ist wie das Widget selbst. 

Ruf mal bitte https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/scale auf und vergleiche es dort mit deinem iPad 5. Werden die Elemente der Seite korrekt skaliert?

**Comment by Erwin40** [comment]
Ja, werden sie.
Aber hier wird ja immer ein bestimmter Scale-Factor gesetzt.
Du möchtest ja, dass automatisch Resized wird innerhalb des Widgets.
Ich müsste echt mal schauen, ob das mit der 3.1.8 auf dem iPad ehemals funktioniert hat.

**Comment by Erwin40** [comment]
So, auch das mal getestet.
Original 3.1.8 ohne Updates des Systems auf den aktuellen Stand.
Hier funktioniert das Skalieren von StateLists auf dem iPad2 + 5 auch nicht.
Beim iPad2 erweitert sich das Widget so, so dass alles reinpasst. Beim 5er wird Widget nicht erweitert und der Inhalt abgeschnitten.

**Comment by Erwin40** [comment]
@ScumbagSteve 
Wie sieht es bei dir aus?
Weil wenn der Chart jetzt korrekt angezeigt wird, kann das Teil hier geschlossen werden.
Alles andere wäre sowieso ein neuer Issue...

**Comment by ScumbagSteve** [comment]
Seit der letzten Beta funktionieren die Charts bei mir jetzt auch auf dem Mobilgerät wieder. Tablett ging schon eins, zwei Betas früher wieder. 
Wollte noch abwarten was bei dir raus kommt, bevor ich schließe, aber dann mache ich jetzt mal zu. 

Danke @Zefau
