### ISSUE TITLE
Probleme beim Binding mit String und Numerischen Datentypen in einer Condition

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2729]
Ich habe z.Z. die v3.2.0-beta.49 installiert, meine aber dass das noch nie so ganz richtig funktioniert hat bei mir.

Ich möchte über die Geräte-DP Einstellung das Icon abhängig von gleichzeitig zwei DPs haben.
Beim ersten DP, auf den sich val bezieht, handelt es sich um ein numerischen Datentyp.
Beim zweiten, der mit dem Binding per && verknüpft ist, um einen String.
In Icon Konfig habe ich folgendes drin:
```
{
"'{val}'='STOP' && '{0_userdata.0.jarvis.Rolladen.Rolladen_position_All}'<49": "mdi:temperature-chevron-down",
"'{val}'='STOP' && '{0_userdata.0.jarvis.Rolladen.Rolladen_position_All}'<100": "mdi:temperature-chevron-up"
}
```
Hier kommt der Fehler im ConsoleLog:
`15:51:28.841 StateList be31acad-6bb4-40ed-a9cf-24cd981d8545 Alle Rolläden position  Object { val: 11, ack: false, ts: 1722345664039, q: 0, from: "system.adapter.jarvis.0", user: "system.user.admin", lc: 1722345664039, id: "0_userdata.0.jarvis.Rolladen.Rolladen_position_All", stateKey: "position", revision: "57fa0212-d050-4fa1-a872-9317f47b6531", … } val}'='STOP' && '{0_userdata.0.jarvis.Rolladen.Rolladen_position_All is not a valid state (in getState) index-cc169059.js:1698:9661 `

Habe auch == und <= getestet, und {val} auch ohne Hochkommas, kein Unterschied.
Also so:
`"{val}=='STOP' && {0_userdata.0.jarvis.Rolladen.Rolladen_position_All}<=49": "mdi:temperature-chevron-down",`
`"{val}=='STOP' && {0_userdata.0.jarvis.Rolladen.Rolladen_position_All}<=100": "mdi:temperature-chevron-up"`

Hier kommt die Fehlermeldung: "numeric separators '_' not allowed in numbers that start with '0'"
![grafik](https://github.com/user-attachments/assets/0c5de414-0de4-439f-8696-298f4b152e10)

Irgendwas mache ich falsch, gell?

**Comment by Erwin40** [comment]
Nachtrag:
Habe übrigens auch mal mit String Datentyp beim Binding DP getestet.
Gleiche Fehlermeldung. Muss also eher an der Und-Verknüpfung liegen.
Kann leider das Topic nachträglich nicht ändern...

**Comment by Zefau** [comment]
Funktioniert bei mir. Der Datenpunkt aus dem er `{val}` ziehen sol liefert `null` zurück. Da scheint was bei dir nicht zu stimmen.

**Comment by Erwin40** [comment]
Das kann eigentlich nicht sein. Beim diesem handelt es sich übrigens um ein BlindlevelAction.
Hier die Definition von diesem Datenpunkt:
`{
  "common": {
    "name": "Rolladen_state All",
    "desc": "Manuell erzeugt",
    "role": "switch",
    "states": {
      "OPEN": "OPEN",
      "CLOSE": "CLOSE",
      "STOP": "STOP",
      " ": "nix"
    },
    "type": "string",
    "read": true,
    "write": true,
    "def": ""
  },
  "type": "state",
  "native": {},
  "_id": "0_userdata.0.jarvis.Rolladen.Rolladen_state_All",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1713052381826
}`

Und hier die Konfiguration des Geräte-DP aus dem JSON-File:
`      "state": {
        "_created": 1692351201215,
        "stateKey": "state",
        "showState": true,
        "state": "0_userdata.0.jarvis.Rolladen.Rolladen_state_All",
        "_updated": 1722452082985,
        "actionElement": "BlindLevelAction",
        "BlindLevelActionConfig": {
          "stopAction": "state",
          "activityState": "activity"
        },
        "properties": {
          "min": "CLOSE",
          "max": "OPEN",
          "stop": "STOP"
        },
        "icon": {
          "{val}='STOP'": "mdi:temperature-chevron-up",
          "{0_userdata.0.jarvis.Rolladen.Rolladen_position_All_C}<='50'": "mdi:temperature-chevron-down"
        },
        "stateStyle": {
          "OPEN": {
            "color": "#ffff00"
          },
          "CLOSE": {
            "color": "#00ff00"
          }
        },
        "bodyElement": null,
        "label": "",
        "iconStyle": {
          "filter": "brightness(0) saturate(100%) invert(78%) sepia(86%) saturate(1036%) hue-rotate(154deg) brightness(99%) contrast(86%)"
        }
      },
`

**Comment by Zefau** [comment]
Dann schau bitte gleich nochmal mit beta-54. Wundert mich nur, dass es bei mir geht. Ich probiere es sonst morgen nochmal mit einem Datenpunkt der einen Pfad analog zu deinem hat. Hatte jetzt irgendeinen genommen.

**Comment by Erwin40** [comment]
beta.54?
Gerne, aber nur wenn der Scrollbalken und iPad Fehler behoben sind ;-)

**Comment by Erwin40** [comment]
Hurra! Es funktioniert jetzt ohne Fehler.
Das habe ich jetzt drin:
{
  "CLOSE": "mdi:window-shutter-auto",
  "OPEN": "data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMjQiIGhlaWdodD0iMjQiIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyI+CgogPGc+CiAgPHRpdGxlPkxheWVyIDE8L3RpdGxlPgogIDxwYXRoIGlkPSJzdmdfMSIgZD0ibTIwLDE0bC0yLDBsLTMuMiw5bDEuOSwwbDAuNywtMmwzLjIsMGwwLjcsMmwxLjksMGwtMy4yLC05em0tMi4yLDUuN2wxLjIsLTMuN2wxLjIsMy43bC0yLjQsMHptLTEwLjgsLTEwLjdsOCwwbDAsMmwtOCwwbDAsLTJ6bTksLTFsLTEwLDBsMCwxMmwtMiwwbDAsLTEybC0yLDBsMCwtNGwxOCwwbDAsNGwtMiwwbDAsNGwtMS40LDBsLTAuNSwxLjNsLTAuMSwwLjRsMCwtNS43eiIgZmlsbD0iY3VycmVudENvbG9yIi8+CiA8L2c+Cjwvc3ZnPg==",
  "{val}='STOP' && {0_userdata.0.jarvis.Rolladen.Rolladen_position_All}<50": "mdi:temperature-chevron-down",
  "{val}='STOP' && {0_userdata.0.jarvis.Rolladen.Rolladen_position_All}<=100": "mdi:temperature-chevron-up"
}

Das die linke Seite bei Strings nicht mehr in Hochkommas müssen, sollte in die v4 Doku entsprechend aufgenommen werden.

Aber leider ist die 54 nicht zu gebrauchen, Scrollbalken Fehler ist noch da.
Und auch im Console.Log sind einige Fehler drin. Falls du das Log haben möchtest, gib Bescheid.

**Comment by Zefau** [comment]
Aber wenn das hier passt können wir es schließen?

**Comment by mcuiobroker** [comment]
@Erwin40 
> Das die linke Seite bei Strings nicht mehr in Hochkommas müssen, sollte in die v4 Doku entsprechend aufgenommen werden.

Das dürfte für die DPs weiterhin gelten. Hier ging es um `{val}`

@Zefau  evtl nochmal prüfen, ob da jetzt ein Unterschied entstanden ist?
Normalerweise müsste ja dann auch bei `'{val}'` die Hochkommata gesetzt werden für `'STOP'`.

**Comment by Zefau** [comment]
Ja, sollte. Wenn `{val}` ein String ist braucht es ein Hochkomma. Wenn Boolean oder Number, dann nicht.

**Comment by Erwin40** [comment]
Genau, hat definitiv bei allen 4 Bedingungen das richtige Icon angezeigt.
Und Console.Log habe ich geprüft, da war diesbezüglich nix mehr drin.

**Comment by Erwin40** [comment]
Erledigt wie oben beschrieben.
