### ISSUE TITLE
[v3.2.0-beta.53] Höhe vom HKT wird falsch gesetzt bzw. teilweise muss man timeout von 500ms um es aufzufangen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2732]
v3.2.0-beta.53
![image](https://github.com/user-attachments/assets/0a5dcdb8-8b92-46fc-86ab-4863cd94e2fe)
Die sollten zentriert in der Mitte stehen mit v3.2.0-beta.49 passt es.
![image](https://github.com/user-attachments/assets/769173a8-a0f8-4e6f-99e7-53cd812af4da)

v3.2.0.beta.49
![image](https://github.com/user-attachments/assets/0c4fbf67-9823-4708-aa58-4e9b53f23115)

![image](https://github.com/user-attachments/assets/5ae1dcbb-30b6-4ad3-971d-2b3a901df571)

**Comment by Erwin40** [comment]
Komisch..
Bei der beta.54 sieht es bei mir gut aus. Ich habe aber "Skaliere Inhalte zur Widget-Größe" aus.
![grafik](https://github.com/user-attachments/assets/f31c8318-69fc-4009-bea4-9084c00111a0)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
