### ISSUE TITLE
 v3.2.0-beta.54 : Keine Kalendereinträge

### ISSUE THREAD

**Issue by sk8er-boi90** [Zefau/ioBroker.jarvis#2734]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
 v3.2.0-beta.54
- Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors) --> nichts im Log oder in der Konsole

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Es wird ein neues KalenderWidget angelegt. Die Daten werden aus dem ICAL Adapter gezogen.  Anschließend wird der Monatskalender angezeigt allerdings scheint es so als ob der Kalender leer wäre. Es gibt weder im Log noch in der Konsole eine Fehlermeldung. Bei Version beta.50 war der Fehler ebenfalls.
Auch beim manuellen Anlegen ( privater Google Kalender Link ohne Passwort und Benutzer) erscheinen keine Termine.
Auch bei absichtlich falschen Benutzernamen erscheint keine Fehlermeldung.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Erwin40** [comment]
Passt es jetzt mit der beta.58?
Bei mir wird der Apple-Calender und die Termine einwandfrei angezeigt.

**Comment by Zefau** [comment]
@sk8er-boi90 wie sieht's bei dir aus?

**Comment by Erwin40** [comment]
Bitte schließen...
