### ISSUE TITLE
Drawer MiniMode dunk nicht auf dem Tablet.

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2735]
> > Jedoch klappt das komplett weg auf dem Tablet.
> 
> Bedeutet? Bild.

![image](https://github.com/Zefau/ioBroker.jarvis/assets/22169074/f855e96b-3c2b-4a57-9590-c150090c9122)

_Originally posted by @ma-gu-16 in https://github.com/Zefau/ioBroker.jarvis/discussions/2645#discussioncomment-9648957_

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
@ma-gu-16 Funktioniert auf dem Tablet -> kann zu?

**Comment by ma-gu-16** [comment]
> @ma-gu-16 Funktioniert auf dem Tablet -> kann zu?

Trau mich nicht die aktuelle beta zu installieren 😂 habe leider nur ein prod. System.  Sobald ne stabile Version kommt aktualisier ich.
