### ISSUE TITLE
[v3.2.0-beta.54] DisplayImage - Bild wird nicht skaliert

### ISSUE THREAD

**Issue by fprobst170** [Zefau/ioBroker.jarvis#2736]
Seit BETA 54 werden die Bilder im Widget DisplayImage nicht mehr skaliert.
Egal ob ich welche Anpassungsart ich auswähle - immer in Originalgröße.
Keine Fehlermeldung in der Konsole

<img width="1905" alt="Screenshot 2024-08-08 075618" src="https://github.com/user-attachments/assets/5274725b-f471-4477-a456-bcf2810c3430">

**Comment by fprobst170** [comment]
Workaround:
Mit folgendem  CSS-Code unter Styles funktioniert die Bildskalierung.
(Beispiel nur für ein DisplayImage Widget.)

`.jarvis-widget-22a08e99-3f12-4d2c-8f74-69d9378a8e68 img {
	object-fit: cover;
	width: 100%;
}`

<img width="1901" alt="Screenshot 2024-08-08 082754" src="https://github.com/user-attachments/assets/337c0a19-e526-41eb-b814-10dd214ebb72">

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by fprobst170** [comment]
Danke, Bilder werden wieder skaliert.
