### ISSUE TITLE
daswetter.com zeigt keine Inhalte mehr an

### ISSUE THREAD

**Issue by HolgerDoerrschuck** [Zefau/ioBroker.jarvis#2738]
Hallo, seit ein paar Tagen wird im Wetterwidget für daswetter.com keine Daten mehr angezeigt. Es wurde nichts geändert 

Info im ioBroker:  
Warning requesting data from http://api.daswetter.com/index.php?v=3.0&api_lang=de&localidad=102926&affiliate_id=xxxxxx  jemb: getaddrinfo EAI_AGAIN api.daswetter.com

**Comment by mcuiobroker** [comment]
Welche Version von jarvis?

**Comment by HolgerDoerrschuck** [comment]
sorry - war ein Problem mit dem Container DNS Eintrag

**Comment by HolgerDoerrschuck** [comment]
sorry - war ein Problem mit dem Container DNS Eintrag
