### ISSUE TITLE
Messages im Errorlog

### ISSUE THREAD

**Issue by schoemi** [Zefau/ioBroker.jarvis#274]
Hi, 
ich bekomme im ErrorLog sekündlich (wenn JARVIS irgendwo offen ist) die Meldung.

(29992) 400 - "WRONG DATA!"

Gibt es eine Möglichkeit das zu debuggen und zu schauen woher der Fehler kommt?
Also welches Gerät oder welches Widget das hervorruft?

**Comment by Zefau** [comment]
I saw that already and it should actually be fixed with the latest beta. Are you on the latest version and still facing that error?

**Comment by schoemi** [comment]
Hi Zefau,

I am on 1.1.0-beta.56. It could solve this issue by taking a look at the log after the config was stored. 
There was a notice about 2 invalid devices (homematic BidCos devices) that have not been properly configured during auto-configuration.
