### ISSUE TITLE
Einstellungen/Sicherheitseinstellungen/Zugriff Konfiguration (Pro) hat keine Wirkung

### ISSUE THREAD

**Issue by treblada** [Zefau/ioBroker.jarvis#2740]
Jarvis version 3.1.8

Die oben genannte Konfiguration scheint keine Wirkung zu haben.

Mein Setup
* Zwei user: "admin" und "pad"
* "admin" ist in der iobroker Gruppe "Administrator" (system.group.administrator), "pad" ist *nicht* in dieser Gruppe.
* Sicherheitseinstellungen für Konfiguration: "iobroker User Management" : system.group.administrator

Wenn ich mich anschließend 
* in einem Incognito-Fenster mit dem User "pad" anmelde (die normale ioBroker Anmeldung)
* zu Jarvis-Konfiguration navigiere

werde ich nach Usernamen/Passwort gefragt. 
Hier kann ich mich wieder als "pad" anmelden, obwohl "pad" nicht Mitglied in der Administrator-Gruppe ist.
Anschließend habe ich vollen Zugriff auf die Konfiguration.

**Comment by Zefau** [comment]
Wurde mit v3.2 überarbeitet.

**Comment by Erwin40** [comment]
Da sich `[treblada](https://github.com/treblada)` seither nicht mehr gemeldet hat, würde ich schließen.
Sorry, falls ich nerve :-)

**Comment by Zefau** [comment]
@treblada

**Comment by treblada** [comment]
Hallo, wenn es in 3.2 behoben is, dann ist es ok für mich. Ich bin kein JS/TS Entwickler und mein Mojo reicht nicht aus, um manuell eine Beta-Version in meinem iobroker zu installieren - ich will mir meine laufende Instanz nicht zerschießen.
Ich kann gerne Feedback geben, wenn die 3.2 mit den regulären Updates reinkommt.
