### ISSUE TITLE
[v3.2.0-beta.57] LastChangeBody - TimeStamp statt Zeitangabe

### ISSUE THREAD

**Issue by fprobst170** [Zefau/ioBroker.jarvis#2741]
Seit Update au die Version v3.2.0-beta.57 wird statt des Zeitpunktes der letzten Änderung eines Wertes, der Timestamp angezeigt.

<img width="527" alt="Screenshot 2024-08-12 143716" src="https://github.com/user-attachments/assets/05d80718-7ee4-4586-998f-3348d60cd0d9">

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by fprobst170** [comment]
Leider besteht bei mir das Problem in der Version `v3.2.0-beta.58` noch immer.  Anbei Screenshot mit Fehlermeldung in der Konsole.

![Screenshot 2024-08-20 070552](https://github.com/user-attachments/assets/b6e46cbe-0129-43c2-9b29-145999242d70)

**Comment by Erwin40** [comment]
Seltsam...
Bei mir funktioniert es einwandfrei auf allen Widgets.

**Comment by fprobst170** [comment]
Zufällig bei einem Screenshot eines anderes Issues auch gesehen das das LastChangeBody auch nicht funktioniert.
Bin somit nicht allein.

https://github.com/Zefau/ioBroker.jarvis/issues/2744#issuecomment-2298011018

**Comment by fprobst170** [comment]
Ich hab die Version beta.58
Fehler ist bei mir bei am PC bei Chrome, Firefox, Jarvis-Browser, Opera (soeben installiert) und auch auf Android Handy und Tablet.

<img width="796" alt="Screenshot 2024-08-20 171043" src="https://github.com/user-attachments/assets/a692664c-bda1-4493-8570-720e9cb03716">

![Screenshot 2024-08-20 171110](https://github.com/user-attachments/assets/b05cad8f-4f22-4a42-9204-93bc57b87ddd)

![Screenshot_20240820_171429_Firefox](https://github.com/user-attachments/assets/b8abf88f-0445-4367-86b0-0f895e6b1d20)

**Comment by mcuiobroker** [comment]
@fprobst170 Hast du mal den Cache gelöscht?

**Comment by fprobst170** [comment]
@mcuiobroker Ja natürlich. Hab sogar extra Opera auf meinem PC installiert.
Aber leider alles ohne Erfolg.

**Comment by StephanTexxpro** [comment]
Funktioniert bei mir ebenfalls nicht, Chrome.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.59` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.59` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by fprobst170** [comment]
Danke, hab soeben die Version `v3.2.0-beta.60` installiert da bereits verfügbar. 
"LastChangeBody" wird wieder richtig dargestellt.
