### ISSUE TITLE
[3.2.0-beta.49] AdapterLogs Überschriftszeile nicht in Darkmode + multiple identische Einträge

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2743]
Hi.
Ist mir schon beim Reboot/Shutdown aufgefallen, dass hier ein Eintrag mehrfach erscheint.
Nun ist es auch bei Backup Meldungen passiert:
![grafik](https://github.com/user-attachments/assets/557afa11-81c9-4e99-bb82-b20c1152d3d5)

Nach einem Refresh ist alles wieder ok.

Und die Zeilenüberschrift beachtet den DarkMode nicht korrekt.
Eingestellt ist das bei mir so:
![grafik](https://github.com/user-attachments/assets/d801e6a2-a328-42b2-b803-10982011fcaa)
****
Ach ja, und es gibt beim Backup immer den Fehler mit `theme` not found.
Kann ich den selber beheben?
![grafik](https://github.com/user-attachments/assets/3041b3ad-716b-402d-b43d-3188b15845d3)

**Comment by mcuiobroker** [comment]
Ist der DP jarvis.0.theme vorhanden?
https://github.com/simatec/ioBroker.backitup/issues/1026#issuecomment-1822335261

**Comment by Erwin40** [comment]
Nö, wie kommt der Zustande?

**Comment by mcuiobroker** [comment]
Der war "früher" als DP vorhanden. Vermutlich wurde er jetzt von `Zefa` raugenommen?
Entweder, du legst einen DP an (ist aber nur zeitweise sinnvoll, bei jedem Update wieder weg?), oder `Zefau` muss `simatec`, darüber informieren, dass es den DP nicht mehr geben soll?

**Comment by Erwin40** [comment]
Danke für die Info.
Ich leg den einfach mal an :-)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
backitup meckert trotzdem noch?
Ich hatte das Update schon vor der Sicherung gemacht.
![image](https://github.com/user-attachments/assets/04fa2471-2b7c-448e-ab85-79e96f60e521)

**Comment by Zefau** [comment]
Bitte dort melden. Die helle Zeile im AdapterLog sollte behoben sein
