### ISSUE TITLE
HistoryGraph wird nicht mehr angezeigt

### ISSUE THREAD

**Issue by only4joy** [Zefau/ioBroker.jarvis#2744]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- v3.2.0-beta.57 (Fehler besteht seit beta.54)

**Describe the bug / Beschreibe den Fehler**
Auf der Oberfläche werden keine Historygraphen oder auch andere Diagramme mehr angezeigt:
![grafik](https://github.com/user-attachments/assets/2b73ef12-18ff-4789-9f7f-fc11ed1c919b)

Wenn man den Graph im Vollbild öffnet, werden die Linien angezeigt:
![grafik](https://github.com/user-attachments/assets/0049d247-23b7-4c47-97f8-32976a9d122a)

Hier noch ein zweites Beispiel, es scheint als wäre die Grafik zwar da, aber im Dashboard auf 1px Höhe reduziert:
![image](https://github.com/user-attachments/assets/c8b12e0f-0bfc-40a7-84d9-4e9229110398)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.58` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.58` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by fprobst170** [comment]
Kann ich nur bestätigen - HistoryGraph wird wieder angezeigt.  👍

**Comment by only4joy** [comment]
@Zefau Auf dem Desktop funktioniert es wieder, danke dir. Auf dem Android Phone geht es noch nicht. Weder über den Browser, noch über die ioBroker Visu App.
![Screenshot_20240820_063933_Firefox](https://github.com/user-attachments/assets/2728b613-f99a-4588-a467-de2d38982e1c)
Was mir aufgefallen ist, wenn ich das Phone im Landscape (also Horizontal halte) Modus habe, funktioniert es.

**Comment by Erwin40** [comment]
Mit der beta.58 funktioniert es auf dem iPad und iPhone.
Auch der Timestamp wird richtig angezeigt.
Bitte unbedingt kompletten Browser-Cache löschen.
Außerdem die Widget-Option `Skaliere Inhalte zur Widget-Größe` deaktivieren.
Dann passt es immer.
Wenn Ok, bitte schließen...

**Comment by Zefau** [comment]
@only4joy zeig mal bitte die Settings deines Widgets was nicht funktioniert

**Comment by only4joy** [comment]
@Zefau hier ein Screenshot, meinst du das?
![grafik](https://github.com/user-attachments/assets/7ba384bf-ec9b-4249-a572-71ec3b0d2298)
Ich habe das probiert, wenn ich die Skalierung ausschalte, dann funktioniert es. Eingeschaltet, geht es nicht.

Übrigens, bei mir sind die Timestamps immer noch falsch: 
![grafik](https://github.com/user-attachments/assets/3bae5204-1add-4ed2-b8c2-385de7bc1003)

Habe ich noch was falsch gemacht?

**Comment by Erwin40** [comment]
Seltsam, bei funktioniert es, wenn ich das Browser-Fenster schmal mache:
![grafik](https://github.com/user-attachments/assets/1d1c8c27-89ee-418b-9b21-4bf66b472f01)
Ich würde mal alles Jarvis Tabs auf allen Geräten schließen, Cache löschen und den Raspi neu starten.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.60` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.60` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by only4joy** [comment]
@Erwin40 sobald ich zwei widgets nebeneinander habe, funktioniert es auch. Wenn ich nur eine Spalte Widgets habe, geht es nicht. 
![image](https://github.com/user-attachments/assets/a7cae19a-3199-45ed-aa3e-19067a0ea2c3)
Der Fehler tritt nicht auf, wenn man das Browserfenster einfach verkleinert, wenn man dann aber neu lädt, dann sind die Graphs weg.

@Zefau auch mit Beta.60 selber Fehler. Habe Cache gelöscht und sogar auf einem anderen Browser und anderem PC getestet. Timestamp funktioniert wieder. Workaround: Skalierung ausschalten funktioniert, dann sind die Vollbilder aber nicht brauchbar.

![image](https://github.com/user-attachments/assets/48efabb3-ce06-42d6-97ea-0d395ddc2cb5)

Danke dir für ein Effort :)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.60` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.60` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by only4joy** [comment]
@Zefau leider auch mit beta62 dasselbe verhalten. Wenn es nur eine Widget Spalte hat, sind die Graphen weg. Cookies und Sitedaten im Browser habe ich gelöscht...

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.63` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.63` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by only4joy** [comment]
beta.63 löst das Problem bei mir. Danke @Zefau

**Comment by only4joy** [comment]
Zu früh gefreut - sorry. Die Historygraphen funktionieren, die Barcharts dafür leider nicht mehr. Weder auf Desktop noch auf dem Mobile.
![grafik](https://github.com/user-attachments/assets/ac34b346-e819-4bd6-a2d1-cf7f99998b5d)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.64` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.64` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by only4joy** [comment]
Super, beta.64 löst das Problem bei mir. Danke dir.
