### ISSUE TITLE
Socket Neuaufbau Zeit anzeigen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2747]
Es sind teilweise sehr oft mehrere Neuverbindungen im Browser-Log (F12) zu sehen.
Dort sollte eine Zeit TimeStamp (TS) mit angezeigt werden.
![image](https://github.com/user-attachments/assets/0874d308-1cef-4a18-be74-1c370b1dcc28)

**Comment by mcuiobroker** [comment]
Standard-Log Einfärbung wird gefiltert
console.log('%cTest','color:red;')
![image](https://github.com/user-attachments/assets/ffb23801-a4f5-4916-aada-41c8f7452c13)

**Comment by Zefau** [comment]
Das liegt daran, dass ich durch das adden des Timestamps das Object verändern muss, wodurch die Information verloren geht. Die bekomme ich auch nicht erhalten.

Ich entferne den Zeitstempel jetzt wieder. Du kannst das in Chrome einfach über die Optionen aktivieren:

![grafik](https://github.com/user-attachments/assets/55f08aff-d24a-40a0-bf23-fb329e293b5b)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.59` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.59` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Auch im FireFox gibt es so eine Möglichkeit
![grafik](https://github.com/user-attachments/assets/cfd71297-4de2-405e-8aa2-b68b79411e15)

Könnte dann doch geschlossen werden, oder?

**Comment by Zefau** [comment]
@mcuiobroker kann das hier zu?

**Comment by mcuiobroker** [comment]
ja
