### ISSUE TITLE
Mehrfachauswahl von Geräten und Massenänderung von Etage, Raum, Gewerk oder Tags.

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2749]

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.58` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.58`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Wo ist etwas verändert worden? Bei Geräten sehe ich es nicht?

**Comment by Erwin40** [comment]
Mal ausprobiert?
Funktioniert halt nicht ;-)

**Comment by Zefau** [comment]
Kannst du das bitte konkretisieren? Was funktioniert nicht? @Erwin40

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.59` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.59`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Erwin40** [comment]
Installiert.
Mehrfach-Auswahl funktioniert ja doch. Nur muss man nicht auf die CheckBox klicken, sondern auf den Text.
![grafik](https://github.com/user-attachments/assets/fe655076-648f-4a06-9f8c-0c353c95f484)

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.60` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.60`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Erwin40** [comment]
beta.62
Yes, jetzt lassen sich die CheckBoxen anklicken 👍
