### ISSUE TITLE
Two charts - one device not possible?

### ISSUE THREAD

**Issue by DanielG1987** [Zefau/ioBroker.jarvis#275]
Is it not intended that one device can have more charts linked?

I'm using a device as Weather Station, which has Temperature, Humidity and Pressure.
Then i want to have 3 different charts, one for temperature, one for humidity and one for pressure, because all 3 charts have different scaling of the Y-Axis.

If i now add for example one Char for the Temperature of the Device, and one Chart for the Pressue of the device, only one chart is loaded, the other one keeps showing the loading symbol:

![Error](https://user-images.githubusercontent.com/71924209/97562813-8800f700-19e2-11eb-99fc-396db8ba2811.png)

As soon as i remove the first chart (linked to the Temperature), the 2nd with the presusre is loading correclty:

![Error2](https://user-images.githubusercontent.com/71924209/97562920-ab2ba680-19e2-11eb-9f85-dd66afc40cd8.png)

Is this simply not possible, or is this an error?

edit: No error is shown in the Console of the browser or Log of iobroker

Thank you 👍

**Comment by Zefau** [comment]
what version of jarvis are you on?

**Comment by DanielG1987** [comment]
> what version of jarvis are you on?

Its the latest, 1.1.0-beta.57.
But as far as i can remember this was also on beta.56 this way.

**Comment by Zefau** [comment]
I can confirm this. Of course a bug.

**Comment by Zefau** [comment]
should be solved with `v1.1.0-beta.58`.

**Comment by DanielG1987** [comment]
> should be solved with `v1.1.0-beta.58`.

Works now. Thank you :)
