### ISSUE TITLE
v3.2.0-beta.58 Fehler bei MediaPlayer?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2752]
![image](https://github.com/user-attachments/assets/d98b3e54-b1a2-423b-932b-86264e08b071)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.59` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.59` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Taucht nicht mehr auf.
