### ISSUE TITLE
v3.2.0-btea.58 debug-log?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2753]
![image](https://github.com/user-attachments/assets/fc5a0e38-89c1-44f7-96d3-a28051fb65c0)
`warn: jarvis.0 (1677198) Warning listening for messages from client: Cannot convert undefined or null to object. See debug-log for more details.`

Wo ist das debug-log?

**Comment by Zefau** [comment]
Wo kommt das denn her? ioBroker Log? Dann Instanz auf `debug` stellen. Oder Browser-Konsole? Dann unter `Default Levels` auf `Verbose`:

![grafik](https://github.com/user-attachments/assets/4d93b8e5-48da-4b79-ba12-2212efc7b3bb)

**Comment by Erwin40** [comment]
beta.49 installert, Instanz auf debug und `jarvis.0.clients.allBrowserConsoleInLog` auf warn gestellt.
Bischen auf den Tabs rumgeklickt, jetzt kommt das hier:
![grafik](https://github.com/user-attachments/assets/4d2137a2-ccc8-4a5c-91c3-0ecf499715a3)

**Comment by Erwin40** [comment]
beta.60
Meldungen sind bisher nicht wieder aufgetaucht 👍

**Comment by Erwin40** [comment]
Mist, zu früh gefreut...
![grafik](https://github.com/user-attachments/assets/ac77d3d5-50cc-4f80-8758-5f80ffdb7322)

Leider hatte ich da - aufgrund der vielen Warnings, den Log-Level schon wieder auf `off`

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.60` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.60` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
beta.60 immer noch?
Aber die habe ich doch installiert ;-)

**Comment by Erwin40** [comment]
Also mit der beta.62 habe ich seither keine Log-Einträge mehr.
Könnte dann doch geschlossen werden :-)
