### ISSUE TITLE
 Nach Upate auf 3.2.0-beta.58  Fehlereintrag /jarvis-socket/?EIO=4&transport=polling&t=P5kQUxZ: Not exists

### ISSUE THREAD

**Issue by Hohenbostler** [Zefau/ioBroker.jarvis#2754]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
Hallo, ich habe gestern ein Umzug meines kompletten iobroker von meinem Docker Container meiner NAS auf einen HP Elite . 
Das war noch Version 3.1.8 . Die lief Fehlerfrei. Heute morgen dann eine Update auf die aktuelle Version 3.2.0-beta.58 gemacht und nun bekomme ich im sekundenTakt log einträge. 

**Describe the bug / Beschreibe den Fehler**
Es gibt leider keine Fehlerbeschreibung außer den log

**Screenshots**
![iobroker](https://github.com/user-attachments/assets/a8bac36c-f797-43a8-bf7e-c2e86eb6d397)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Erwin40** [comment]
Keine Ahnung ob das damit zusammenhängt, abei bei mir werden bei der beta.58 diese Meldungen produziert wenn ich einzelne Tabs anzeige:
![grafik](https://github.com/user-attachments/assets/be78c1a9-8ecb-47f0-8d2b-a4465173d46d)

**Comment by Hohenbostler** [comment]
Diese Meldungen bekomme ich jetzt auch permanent nach ich alle Jarvis Verbindungen einmal getrennt habe.

**Comment by mcuiobroker** [comment]
Die Meldungen kommen eigentlich nur, wenn man Browser-Logging für ioBroker eingeschaltet hat.
`jarvis.0.clients.192-168-178-77_Microsoft-Edge.browserConsoleInLog` oder
`jarvis.0.clients.allBrowserConsoleInLog`

**Comment by mcuiobroker** [comment]
@Hohenbostler Cache gelöscht?

**Comment by Zefau** [comment]
Jarvis-socket gibt es nicht mehr aufgrund der Umstellung von Socket-io auf Websocket. Irgendein client ist noch auf 3.1 und versucht bei dir noch zu connecten.

**Comment by Erwin40** [comment]
Ooops, der DP `jarvis.0.clients.allBrowserConsoleInLog` stand auf 'warn', warum auch immer.
Das erklärt nicht warum hier unvollständige error/warn Meldungen erscheinen.
Aber das ist wohl ein anderes Thema :-)
Ich erlaube mir zu schließen @Hohenbostler

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.59` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.59` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Ist installiert und `jarvis.0.clients.allBrowserConsoleInLog` auf warn gestellt.
Jetzt kommt nur noch das hier. Ist das normal?
![grafik](https://github.com/user-attachments/assets/57b883de-aa19-4371-a126-4ec07ac17ae5)

Und das hier:
![grafik](https://github.com/user-attachments/assets/24a068a5-9fda-4cb2-a53b-aff9c60d2e47)

**Comment by Erwin40** [comment]
beta.60
Socket Fehlermeldung scheint weg zu sein.
Das andere kann ignieriert werden, ist nur bei einem iFrame für WetterRadar.
Kann also meiner Meinung nach geschlossen werden.
