### ISSUE TITLE
v3.2.0-beta.60 Einträge?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2757]
![image](https://github.com/user-attachments/assets/a7c9b64a-7cef-48e3-b88d-40125eba2ff9)

Scripts funktioniert gar nicht mehr

**Comment by Zefau** [comment]
Hast du `import` bei dir drin? Kannst du mal die Zeilen hier rein kopieren?

**Comment by mcuiobroker** [comment]
```
import "https://192.168.178.170/html/download/jarvisLoadAndMem.js";  
  import "https://192.168.178.170/html/download/system.js";
 // import "https://192.168.178.170/html/download/localStorageJarvis.js";
  import "https://192.168.178.170/html/download/stateListItemHistory.js";  
 // import "https://192.168.178.170/html/download/spinWheel.js";  

import "https://192.168.178.170/html/download/displayMark.js";  

  import "https://192.168.178.170/html/download/getioBrokerData.js";  

 // import "https://192.168.178.170/html/download/slideshowWithPin.js";  
 // import "https://192.168.178.170/html/download/dialog.js";  

  import "https://192.168.178.170/html/download/createFooter.js";  

  //import "https://192.168.178.170/html/download/tabLink.js";
  ```

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2716#issuecomment-2299688891

**Comment by Zefau** [comment]
Alle `import` Befehle stehen bei dir ganz oben, richtig? Kein Code zwischen den `import` Befehlen.

Seit der letzten beta gibt es einen Unterschied zwischen `@import` und `import` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import):
- `@import` erstellt einen eigenen `<script ..></script>` Tag je Import
- `import` erstellt __keinen__ eigenen `<script ..></script>` Tag (siehe auch https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#description)

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/ef8c49d6-bd8d-47ab-9a29-bbe9d0de80a5)
Variable ist aber unwichtig

**Comment by Zefau** [comment]
Nein, bei Styles ist es per offizieller Definition `@import`.
Bei Scripts gibt es `@import` nur in jarvis und `import` ist die offizielle Definition, die aber nur durch neue Browser unterstützt wird (daher zusätzlich `@import`)

**Comment by mcuiobroker** [comment]
Ist implementiert wird aber aber noch nicht in einer Version verwendet?

**Comment by Zefau** [comment]
Locally implemented ist, wenn ich es bei mir in der Dev Umgebung umgesetzt habe. Dann läuft es in die nächste Version rein, die ins Repo geht. Dann geht der Tag auf Testing und die Nachricht im Issue zum Test erscheint.

Ist also noch nicht im Repo.

**Comment by Zefau** [comment]
Das hier sollte gefixed sein. Hab den `v3.2` Tag vergessen. kommt der Fehler noch?

**Comment by Erwin40** [comment]
Also bei mir nicht 😁

**Comment by mcuiobroker** [comment]
Der Fehler kommt noc
![image](https://github.com/user-attachments/assets/86c4729c-1baa-47a4-9951-0749ffb47791)

**Comment by Zefau** [comment]
Was hast denn drin in den Scripts? Bin etwas ratlos wo das herkommt.

**Comment by mcuiobroker** [comment]
Der Fehler scheint vom `setTimout` zu kommen.
Nehme ich das raus, kommt dies.
![image](https://github.com/user-attachments/assets/a2713b3a-4492-4925-8667-6f8e1952314c)

**Comment by Zefau** [comment]
Sonst schreib hier rein, wie das Skript aussieht, sonst ist es Glaskugel

**Comment by mcuiobroker** [comment]
Welches Script, das mehrere Scripte?
Das Problem ist ein CORS Problem.
Zurzeit sieht es so aus in scripts
```
import "https://192.168.178.170/html/download/jarvisDPs.js";  
/* import "https://cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.js"; */

/* setTimeout(function(){ */
  import "https://192.168.178.170/html/download/jarvisLoadAndMem.js";  
  import "https://192.168.178.170/html/download/system.js";
  import "https://192.168.178.170/html/download/stateListItemHistory.js";  
  import "https://192.168.178.170/html/download/stateListItemClick.js";  
  import "https://192.168.178.170/html/download/displayMark.js";  
  import "https://192.168.178.170/html/download/getioBrokerData.js";  
  import "https://192.168.178.170/html/download/timer.js";
  import "https://code.jquery.com/jquery-3.7.1.min.js" 
/* },3000) */
```

Hat bis beta.49 auch funktioniert, dann nicht mehr.

**Comment by Zefau** [comment]
Weil jarvis nun `@import` und `import` unterscheidet. Ändere mal in `@import`

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2716#issuecomment-2299656998

**Comment by mcuiobroker** [comment]
Geändert auf
```
@import "https://192.168.178.170/html/download/jarvisDPs.js";  
/* import "https://cdn.jsdelivr.net/npm/handsontable/dist/handsontable.full.min.js"; */

/* setTimeout(function(){ */
  @import "https://192.168.178.170/html/download/jarvisLoadAndMem.js";  
  @import "https://192.168.178.170/html/download/system.js";
  @import "https://192.168.178.170/html/download/stateListItemHistory.js";  
  @import "https://192.168.178.170/html/download/stateListItemClick.js";  
  @import "https://192.168.178.170/html/download/displayMark.js";  
  @import "https://192.168.178.170/html/download/getioBrokerData.js";  
  @import "https://192.168.178.170/html/download/timer.js";
  @import "https://code.jquery.com/jquery-3.7.1.min.js" 
/* },3000) */
```
Gleicher Fehler (CORS) , gehe zurück auf beta.49 auch mit @import alles ok.

**Comment by mcuiobroker** [comment]
Ich hab es jetzt in den Griff bekommen. Musste auf dem Apache-Server eine zusätzlichen Eintrag erstellen.
`sudo nano /etc/apache2/sites-available/default-ssl.conf`
```
<Directory /var/www/html>
       AllowOverride All
</Directory>
```
jetzt kommt das nächste Problem 
![image](https://github.com/user-attachments/assets/31c2f5e1-68b6-4bb2-aafa-e43b0f762c87)

Früher durfte man in jarvis-scripts die "Globalen" Variablen nur einmal nutzen.
Dies gilt jetzt anscheinend nicht mehr?
Kann das sein?

**Comment by mcuiobroker** [comment]
Läuft jetzt, ist aber aufgrund der Änderung bzgl. der Variablen ein wenig inkompatibel zu v3.1.x.
Dann muss man halt die Skripte anpassen.
Gefällt so aber besser, da man nicht mehr darauf achten muss ob eine Variable schon genutzt wurde in einem Skript.

**Comment by Erwin40** [comment]
Den Fehler `Access-Control-Allow-Origin` hatte ich auch.
Musste meine Scripte fusionieren, da auch bei mir Script übergreifende Variablen nicht mehr funktioniert haben, dann in den Adapter Ordner `/opt/iobroker/node_modules/iobroker.jarvis/www/jarvis/user/` verschieben, Upload und Jarvis restart machen.
Und das bei jedem Update, was mir gar nicht so gut gefällt.
Ich möchte jetzt auch nicht einen http Server aufsetzen, nur damit die Script Importe wieder laufen.
Und nein, VIS ist bei mir nicht installiert ;-)
Also mir würde es schon gefallen, wenn der obige Fehler weg wäre und ich wieder wie gewohnt in `0_userdata.0/jarvisScripte/` ablegen könnte 😁

**Comment by mcuiobroker** [comment]
@Erwin40 
Das geht technisch nicht mehr, da man aus Sicherheitsgründen nicht von unterschiedlichen Ports die Daten beziehen kann.
Früher hat man noch die Daten über Port 8082 geholt, das wird aber nicht mehr gemacht. Jetzt geht man über Port 8400.
-> CORS Fehler da man versucht von Port 8400 Daten von Port 8082 zu holen und das ist NICHT erlaubt. Kann kein Browser.
Das kann man nicht mehr rückgängig machen, da Zefau anscheinend sein APP auf Port 8400 laufen lassen möchte?
Dies hat also technische Gründe, soweit ich es verstanden habe.

Und VIS würde da auch nicht helfen, da auch VIS über Port 8082 läuft und somit einen CORS-Fehler verursacht.

**Comment by Zefau** [comment]
> Man kann nicht mehr die VIS2-APP für jarvis mit Cloud-Anbindung nutzen.

Das ging aber nie auch unabhängig der Scripts, oder?

**Comment by Zefau** [comment]
Die Frage ist ob man bei Web Adapter nicht die CORS Policy steuern und das freigeben kann.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2782

**Comment by Erwin40** [comment]
Dann verstehe ich aber nicht, warum es mit der beta.49 funktioniert hat.
Da wurde doch auch schon der Port 8400 genutzt, oder habe ich da was verpasst?

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/issues/2716

**Comment by Erwin40** [comment]
Sorry, aber 2716 erklärt nicht warum es mit der beta.49 noch ging, obwohl Jarvis dort auch schon mit Port 8400 gearbeitet hat ;-)

**Comment by Zefau** [comment]
Nachverfolgung via https://github.com/Zefau/ioBroker.jarvis/issues/2782
