### ISSUE TITLE
v3.2.0-beta.60  IFrame - TabVollbild nur 300px hoch

### ISSUE THREAD

**Issue by fprobst170** [Zefau/ioBroker.jarvis#2758]
Bei der `beta.60` werden IFrame bei aktivem "TabVollbild"  nur 300px hoch dargestellt.
Bei der Version `beta.59` funktionierte es noch richtig.

<img width="1057" alt="Screenshot 2024-08-21 092251" src="https://github.com/user-attachments/assets/0bace4f5-99e9-4fb5-9a97-8bf9d62b801e">

Wenn ich "TabVollbild" ausschalte fehlt ein Teil der IFrame Webseite (Menüleiste unten - Bereich rot markiert!)

<img width="1325" alt="Screenshot 2024-08-21 093723" src="https://github.com/user-attachments/assets/35f0e02a-8365-45c2-b64f-82cad5d24208">

Wenn ich beim Widget die Sandbox **ausschalte**  wird nichts mehr angezeigt und in der Konsole wird angezeigt 
" ...document's frame is sandboxed"

![Screenshot 2024-08-21 093847](https://github.com/user-attachments/assets/ad34308e-9d19-43da-bfc6-c87461824f9b)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.60` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.60` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by fprobst170** [comment]
Das IFrame Widget wird wieder bei "TabVollbild" richtig dargestellt.
Jedoch das verhalten bei ausgeschaltenten "TabVollbild" ist noch gleich. Es fehlt ein Teil der IFrame Webseite - Menüleiste unten (2 Screenshot im1 Post) - klar kann da die Webseite die ich im IFrame lade schuld sein. (Wollte es nur erwähnen - ist für mich nicht wichtig da ich "TabVollbild" habe.

Was jedoch noch immer ist, das ist das umgekehrte Verhalten der Sandboxeinstellung. 
Sandbox beim IFrame Widget ausgeschaltet - In der Ansicht dann keine Anzeige und in der Konsole steht das die Sandbox aktiv ist und die Scriptausführung blokiert.
Sanbox beim IFrame Widget eingeschaltet und alles zugelassen - funktioniert die Ansicht

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.64` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.64` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Yes, wird wieder korrekt angezeigt 👍 
Bitte schließen.
