### ISSUE TITLE
v3.2.0-beta.60 und früher, Calender Widget geht über die eigentliche Größe

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2759]
Der Inhalt des Kalenderwidgets geht über die eigentlich Widgetgröße hinaus und überdeckt andere Widgets. Früher konnte man innerhalb des Widgets scrollen.

![image](https://github.com/user-attachments/assets/58afbbf9-9992-47dc-a816-c207d446c4f6)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.60` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.60` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
@Zefau v3.2.0-beta.60 ? wirklich jetzt? ich habe dieses Issue mit dieser version erstellt

**Comment by Zefau** [comment]
Ne, build failed. Die Nachricht ist ja automatisch und lief, obwohl der build auf die Bretter gegangen ist

**Comment by intruder7777** [comment]
@Zefau auch mit der 62 geht es über den Rand und man kann nicht innerhalb des Widgets scrollen

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.63` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.63` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
passt jetzt
