### ISSUE TITLE
DisplayImage - Refresh not work

### ISSUE THREAD

**Issue by welanco** [Zefau/ioBroker.jarvis#276]
The image from ipCam will not refresh with given interval.

<img width="961" alt="Screenshot 2020-10-29 160559" src="https://user-images.githubusercontent.com/46993165/97592228-b55c9d80-1a00-11eb-8055-3e686529f785.png">

Thank you

André

**Comment by Zefau** [comment]
should be solved with `v1.1.0-beta.58`.

**Comment by welanco** [comment]
Installed v1.1.0-beta.59 - refresh not work for me

tried out:

1. deinstalled old version v1.1.0-beta.57
2. restart io broker
3. installed new version v1.1.0-beta.59

result => No autorefresh of image

also tried:

1. add new page
2. add new col
3. add new widget with modul DisplayImage

result => No autorefresh of image

Manual refresh page works fine ;-)

**Comment by Zefau** [comment]
Could you try again with `v1.1.0-beta.63` ?

**Comment by welanco** [comment]
1. removed old jarvis version
2. restart iobroker
3. install new version v1.1.0-beta.62
4. create new config

result ==> image not refreshed

**Comment by Zefau** [comment]
The repo didn't get updated. You have to use beta-63, not 62. Please try again with latest beta.

Though, I have the problem that the Image is flashing now.

**Comment by Zefau** [comment]
@welanco Could you please try again with the latest beta? I think this should work now as expected. Thanks

**Comment by Zefau** [comment]
@welanco

**Comment by duczz** [comment]
@Zefau nope geht noch nicht, trotz refresh intervall

**Comment by Zefau** [comment]
@duczz hast du ein Image für mich zum testen?

**Comment by Zefau** [comment]
@duczz Kannst du mal die `v1.1.0-beta.133` probieren?

**Comment by duczz** [comment]
@Zefau Funktioniert jetzt
