### ISSUE TITLE
v3.2.0-beta.62 - Popup von Geräten leer

### ISSUE THREAD

**Issue by fprobst170** [Zefau/ioBroker.jarvis#2762]
Seit dem Update sind auf die beta.62 sind die Popups leer.

![Screenshot 2024-08-22 132300](https://github.com/user-attachments/assets/52336620-fc5f-4095-80ee-2263b0a34736)

Fehler in der Konsole
`TypeError: Cannot read properties of undefined (reading 'maxHeight')`

**Comment by Erwin40** [comment]
Mist, bei mir auch 😭

**Comment by Bernd9000** [comment]
Fehler Browser Konsole:
`TypeError: t.widgetSize is undefined`

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.63` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.63` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by fprobst170** [comment]
Leider sind die Popups bei mir in der `beta.63` noch immer leer. 
Anbei Screenshot mit Konsole.
![Screenshot 2024-08-24 102044](https://github.com/user-attachments/assets/f4591f82-f3fa-4042-924e-e091be379a15)
Getestet am PC unter Crome, Opera und Android Firefox

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.64` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.64` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Poups sind wieder da, bitte schließen.
