### ISSUE TITLE
Android App geht nicht

### ISSUE THREAD

**Issue by BlackandGold1** [Zefau/ioBroker.jarvis#2764]
Hab seit Wochen das Problem das die App nicht geht. Ich komme nur bis zur Aufforderung das Servernetzwerk einzutragen aber beim bestätigen passiert nichts.

**Comment by Zefau** [comment]
Welche Version? Irgendeinen Fehler in F12 bei der Browser Variante? Irgendwas im ioBroker Log?

**Comment by BlackandGold1** [comment]
Die letzte App war die Beta 40 alle anderen gehen nicht mehr. Keine Fehlermeld

**Comment by Zefau** [comment]
Also wir reden von der jarvis Android App, die du unter https://github.com/Zefau/ioBroker.jarvis/releases/tag/v3.2.0-beta.63 als `.apk` runterladen kannst, richtig?

Die ist bei mir installierbar und funktioniert auch.

Was für eine Android-Version hast du?
Wie ist deine jarvis Instanz konfiguriert? Hast du `Verwenden Sie eine sichere Verbindung` aktiviert? Hast du die `Authentifizierung` aktiviert? Hast du den Port geändert oder läuft jarvis auf `8400`?

**Comment by BlackandGold1** [comment]
Genau von der. Bei mir läuft Android 14. wie gesagt installieren klappt aber im Startbilds Hirn wo ich die Ip und den Port einstellen kann. Dort kann ich machen was ich will sobald ich Verbinden drücke bleibe ich dort und als ip steht wider localhorst und 8400 als Port.
![IMG_0376](https://github.com/user-attachments/assets/71cba46d-e651-43be-a6a5-71dfefdf921b)

**Comment by Zefau** [comment]
Nimm mal den Haken bei `sichere Verbindung` raus. Hast du ja nicht aktiviert.

**Comment by BlackandGold1** [comment]
Wie gesagt das ändert nichts außer siehe Screenvideo

https://github.com/user-attachments/assets/d53d87dc-df39-4aa7-bc06-8af5cf80bbaf

**Comment by Zefau** [comment]
Jo, stimmt, geht irgendwie nur mit verschlüsselter Verbindung. Wenn ich bei mir auf unverschlüsselt gehe, bricht es ab.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.64` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.64` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by BlackandGold1** [comment]
Adapter aktualisieren. App alle Daten gelöscht und entfernt.Neue App installiert und genau das gleiche. Also es geht nicht.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.66` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.66` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by BlackandGold1** [comment]
Geht jetzt. Habe aber Anzeigefehler. Hier der Energieflüsse Adapter erweitert.
![Screenshot_2024-08-27-22-54-59-92_0634c2e64f6d258c835660a56c888c0b](https://github.com/user-attachments/assets/7d8b1345-d9fe-498f-982d-b69e46306037)

**Comment by Zefau** [comment]
Was ist der EnergieflussAdapter  ?

**Comment by Zefau** [comment]
ggf. https://github.com/Zefau/ioBroker.jarvis/issues/2726 ?
