### ISSUE TITLE
F1-Hilfe -> Browser-Hilfe und nicht Jarvis-Hilfe

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2765]
Für F1 fehlt anscheinend ein event.preventDefault().
Drückt man F1 wird die Browser-Hilfe angezeigt und nicht die Jarvis-Hilfe
```
document.addEventListener("keydown", (event) => {
if (event.keyCode == 112){
	event.preventDefault()
}	
});
```

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.64` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.64` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Funktioniert wieder 👍

**Comment by mcuiobroker** [comment]
Bei mir nicht. 
Chrome und Edge funktionieren nicht, Firefox geht.

**Comment by Erwin40** [comment]
Huch...
Sowas nutze ich nur in Notfällen (Edge) 😁

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.65` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.65` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
