### ISSUE TITLE
--var Meldung?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2766]
![image](https://github.com/user-attachments/assets/8e6c15ef-55d8-4da1-b1fa-f10068fe7d68)
https://github.com/w3c/csswg-drafts/issues/4805

**Comment by Zefau** [comment]
Was ist denn das?

**Comment by mcuiobroker** [comment]
Keine Ahnung, kam nach Edge-Update

**Comment by Erwin40** [comment]
Also mit der beta.67 bekomme ich die Console-Meldung nicht mehr.

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/2e57b67b-b032-4994-8734-d94427eaa494)

**Comment by Zefau** [comment]
Kein Plan, was damit gemeint ist und was ich da wie ändern muss :-\

**Comment by mcuiobroker** [comment]
ChatGPT sagt
![image](https://github.com/user-attachments/assets/74e999cd-2d69-4aa8-9f1a-5ea5782a308a)

**Comment by Zefau** [comment]
Jo, das hatte ich mir schon gegoogelt. Aber was ist denn `:--open` (bzw. `:--xxx`)? Wüsste nicht, dass ich das irgendwo nutze. Weiß nichtmal, was das ist :-D

**Comment by mcuiobroker** [comment]
Also das sollen variable Pseudoklassen sein. Normal sind ja :hover, ::before usw. Ansscheinend gibt es auch Entwickler die `:--var1` einsetzen.
Vielleicht kommt dieser Fehler, nur als Hinweis bei edge, oder es steckt noch irgendwo in einem CSS versteckt.

Ich schließe erstmal, bis evtl. mehr dazu weiß oder was findet.

**Comment by mcuiobroker** [comment]
es gibt die Kombination :-- ?

`/opt/iobroker/node_modules/iobroker.jarvis/www/jarvis/js/index-b69790d7.js`
z(null,{prefix:I.getCompletionPrefix(V),matches:J,finished:--ne==0}

**Comment by Zefau** [comment]
Kommt wahrscheinlich aus den Dependencies.

**Comment by mcuiobroker** [comment]
#2779

**Comment by mcuiobroker** [comment]
`v3.2.0-rc.4` Meldung kommt nicht mehr? Was wurde geändert?

**Comment by Zefau** [comment]
hm, eigentlich nichts

**Comment by mcuiobroker** [comment]
Ich schließe es , da nicht mehr da. Kann es ja wieder öffnen, wenn es erneut kommt.

**Comment by mcuiobroker** [comment]
Kommt nur noch im Chrome.
![image](https://github.com/user-attachments/assets/919d2add-57d9-4a8e-a485-3e7d8404e7db)
