### ISSUE TITLE
Popup mit Version 63 immer noch leer und viele Warnmeldungen in IOBroker

### ISSUE THREAD

**Issue by Robbi12** [Zefau/ioBroker.jarvis#2768]
Hallo. Die Popups sind immer noch leer.

Außerdem habe ich extrem viele Warnmeldungen im Iobroker.

![Screenshot 2024-08-24 083444](https://github.com/user-attachments/assets/2f66a27b-3e49-4a06-94fb-4db7eb90fcdc)

**Comment by Robbi12** [comment]
Gerade gesehen. Wurde schon gepostet.

**Comment by Zefau** [comment]
Sind Debugging Meldungen
