### ISSUE TITLE
[beta.64] Fehler im ioBroker Protokoll: - M is null bei Aufruf Jarvis Konfiguration (F2)

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2769]
Immer wenn ich in Jarvis in die Konfiguration gehe, erscheint im Log nachfolgende Meldung:
![grafik](https://github.com/user-attachments/assets/e6df2a0f-a92e-4f2a-8bb5-18c2b4fd1a08)

Und in der Browser-Console:
![grafik](https://github.com/user-attachments/assets/3781cf31-f7f4-4bc8-9233-142e6c397bcb)

**Comment by Zefau** [comment]
Kannst du das in einem anderen Browser reproduzieren und von dort nochmal die Fehlermeldung posten? 

Siehst du in der Browser-Zeile, was aufgerufen wird in der Konfiguration? Also Devices, Layout, Widgets, ... ?

**Comment by Erwin40** [comment]
Edge Browser, unmittelbar nach F2:
![grafik](https://github.com/user-attachments/assets/75eddc47-afce-4c65-9c32-154fa0560e0b)

Klick auf `index-6ed954a2.js:106`:
![grafik](https://github.com/user-attachments/assets/8db93967-67e6-4cad-9298-c4b5aa1435a7)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.66` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.66` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Ist weg, erledigt.
