### ISSUE TITLE
Connect-Anzeige muss nach oben, wenn man das Menü unten hat?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2770]
![image](https://github.com/user-attachments/assets/0f5fe5eb-be4a-4d0d-8d33-7df46dd3c145)
oder ausblendbar bzw als kleines Symbol, so dass es die Tab-Auswahl nicht behindert.

**Comment by Zefau** [comment]
hm, das hab ich vor geraumer Zeit ausgebaut. Ist das die v3.1? In der v3.2 ist ein Fab-Button:

![grafik](https://github.com/user-attachments/assets/b6e7f5eb-0c23-485d-95f9-ad50989cb4e6)

**Comment by mcuiobroker** [comment]
War vom Forum mit v3.1.8

**Comment by Zefau** [comment]
Gibt es mit v3.2 ja nicht mehr. Und ja, in v3.2 wird es auch nur paar Sekunden angezeigt und dann ausgeblendet.
