### ISSUE TITLE
[beta.64] Redundante Einträge im AdapterLog

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2771]
Seit einigen Beta-Releases kommt es immer wieder vor, dass Einträge im AdapterLog mehrfach angezeigt werden, obwohl nur ein Eintrag vorhanden ist.
Nach F5 Aktualisierung, ist nur noch jweils ein Eintrag vorhanden.
Das Verhalten tritt immer auf, auch wenn der Tab mit dem AdapterLog ausgewählt und im Vordergrund ist.

![grafik](https://github.com/user-attachments/assets/3400bf8d-92c5-4a00-8784-c56d442f2005)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.66` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.66` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Leider immer noch, diesmal sogar >20 Einträge:
![grafik](https://github.com/user-attachments/assets/21988a08-ef26-4c48-bf85-9af7bf2d2a57)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.67` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.67` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Scheinen weg zu sein 👍 
Ich schließe...
