### ISSUE TITLE
Signature Kontrolle direkt beim Start

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2772]
Es muss bei Start direkt kontrolliert werden, ob  alle jarvis-DPs eine korrekt Signature haben.
https://forum.iobroker.net/topic/68566/jarvis-v3-2-x-just-another-remarkable-vis-alpha-testing/222
Es gab wieder einen Fall, wo für CSS als Signature null vergeben wurde und dies zu Problemen führt.

-  auch direkt den localStorage mit löschen
`localStorage.clear()`

**Comment by Zefau** [comment]
Dem ist eigentlich schon so. Local Storage löschen mach ich nicht, das ist eine gute Idee 

Es gibt aber für das Upgrade auf 3.2 schon zwei offene Bug issues.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2671
