### ISSUE TITLE
iFrame Positionierung fehlerhaft

### ISSUE THREAD

**Issue by danickel** [Zefau/ioBroker.jarvis#2773]
iFrame nicht mehr im Widget sondern verschoben nach Update von 3.2.0-beta.46 auf beta.66

![image](https://github.com/user-attachments/assets/ec81b8b1-1cfd-43d6-b8be-08398f0b67cf)

**Comment by Zefau** [comment]
Ist die Option `Aufrechterhalten` an? Passiert das auch, wenn die Option aus ist?

**Comment by danickel** [comment]
Hab gerade das Issue https://github.com/Zefau/ioBroker.jarvis/issues/2726 gefunden. Wenn ich "Aufrechterhalten" ausschalte geht es. Sorry für das Duplikat
