### ISSUE TITLE
Seit beta.62: Quellübergreifende (Cross-Origin) Anfrage blockiert

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2774]
Seit der ~beta.62 können Scripte über: `import "http://raspberrypi4-ede:8082/0_userdata.0/jarvisScripte/jarvisDPs.js";`
nicht mehr geladen werden.

F12 Browser-Log:
![grafik](https://github.com/user-attachments/assets/74c2d4db-9241-4284-b1a6-3986c16069e5)

Die Methode über:
Ablegen in: `/opt/iobroker/node_modules/iobroker.jarvis/www/jarvis/user`
und `iobroker upload jarvis`
ist etwas umständlich und muss nach jedem Adapter Update wiederholt werden.

**Comment by Zefau** [comment]
Stehe https://github.com/Zefau/ioBroker.jarvis/issues/2716#issuecomment-2307581027

Das hat nichts mit jarvis zu tun, sondern, dass die Datei, die du einbindest von einem fremden Port kommt. Jarvis nutzt `8400`, aber deine URL ist `8082`. Google die Fehlermeldung mal.

Lösung ist https://github.com/Zefau/ioBroker.jarvis/issues/2716#issuecomment-2308952519. Dann solltest du es via `https:// ... :8400/user/script.js` aufrufen können.

**Comment by Erwin40** [comment]
Hi,
sorry das ich widerspreche. Aber in der beta.49 hat es definitiv funktioniert :-)
![grafik](https://github.com/user-attachments/assets/93bbf65f-40c3-4dea-8c91-baa069edd774)

![grafik](https://github.com/user-attachments/assets/3aa42e1e-16c4-49be-a3cc-3c0cfa8dccff)

**Comment by mcuiobroker** [comment]
@Erwin40 
Ist aufgrund der CORS-Policy nicht mehr möglich.
![image](https://github.com/user-attachments/assets/398a120a-a5eb-4411-b647-551e350420d4)

Also gehen nur noch die Varianten:
- eigener Fileserver
- Upload in jarvis-Dateien + Upload jarvis + F5

**Comment by Zefau** [comment]
Ich muss mir das nochmal anschauen. `@import` habe ich nicht verändert und sollte so funktionieren wie immer. Lediglich `import`, also ohne `@` kann ich nicht steuern, da das der Javascript Standard ist.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/2757

**Comment by Zefau** [comment]
Nachverfolgung via https://github.com/Zefau/ioBroker.jarvis/issues/2782
