### ISSUE TITLE
v3.2.0-beta.66 - DisplayImage Skalierung

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2775]
Ein Widget mit Modul DisplayImage enthält ein Base64 Bild.

Folgende Optionen sind eingeschaltet:
1.) "Widget Label und Icon verstecken" = aus
2.) "Tab Vollbild" = an

Fehler:
1.) Es wird nicht auf Höhenänderung der Bildschirmauflösung reagiert, nur bei Breitenänderung.
Nach F5 oder Tab wechsel wird richtig skaliert.

2.) Wird "Widget Label und Icon" angezeigt wird das Bild vermutlich um die Pixelhöhe des Labels gekürzt.
Das Bild ist dann nicht vollständig zu sehen und Scrollbalken tauchen auf.
F5 oder Tab wechsel hilft hier nicht.

**Comment by danickel** [comment]
Kann ich bestätigen:
DisplayImage mit einem gelinkten Gerät. Gerät enthält Datenpunkt zu einem Base64 Image.
Skalierung auf "contain" gestellt. Skalierung passt nicht mehr. Bild wird nicht korrekt angezeigt.

Das zweite DisplayImage Widget enthält direkt die URL und die Skalierung steht auf "cover" -> Hier gibt es kein Problem

Widget/Label verstecken ist bei beiden = ein
Vollbild = aus

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.72` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.72` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Kann ich im Moment nicht testen weil jarvis nicht mehr läuft [#2782](https://github.com/Zefau/ioBroker.jarvis/issues/2782)
Teste ich später

**Comment by Bernd9000** [comment]
Läuft, mache dicht
