### ISSUE TITLE
Fully Browser auf Tablet zeigt keinerlei Werte an

### ISSUE THREAD

**Issue by Robbi12** [Zefau/ioBroker.jarvis#2776]
Hallo. Mit der letzten und vorletzten Version ist bei meinem Tablet mit FullyBrowser alles leer.

Der Hintergrund wird angezeigt, jedoch keinerlei Widget etc. Schon alles probiert. Cache gelöscht etc.

Bei der 64 hat es noch funktioniert

**Comment by Zefau** [comment]
Hast du das Problem mit der aktuellen beta noch?

**Comment by Robbi12** [comment]
Version 70 und 71 starten nicht. Es kommt immer, dass ein Script fehlt

**Comment by mcuiobroker** [comment]
Nutzt du Scripts? -> Unter Dateien / Files im Ordner (0_userdata.0 / Benutzerdaten) einen Ordner
`jarvis-scripts` anlegen.
![image](https://github.com/user-attachments/assets/af2b8837-c012-4362-a1b5-f566a64f749a)

Kannst du den Fehler zeigen?

**Comment by Robbi12** [comment]
Exception-Code: ENOENT: ENOENT: no such file or directory, stat '/opt/iobroker/iobroker-data/files/0_userdata.0/jarvis-scripts'

Ich habe veruscht gemäß dem image einen Ordner jarvis-scripts anzulegen.

Funktioniert nicht. Kann in der Maske nichts eingeben.

Dann habe ich direkt versucht bei files den Ordner 0_userdata.0 zu suchen. Der ist nicht vorhanden.

Ich habe ihn manuell angelegt und eine datei jarvis-scripts angelegt.

Nun startet es

Ob das alles richtig war, kann ich nicht sagen. Keine Ahnung

**Comment by Robbi12** [comment]
Und das Tablet zeigt nichts mit FullyBrowser an.


Ich kann wenn ich die Config als Startseite aufrufe auch nichts bedienen.

**Comment by Zefau** [comment]
Mit der Informationslage ist es schwierig zu helfen. Bei mir lädt jarvis im FullyBrowser.

Geht es denn normal im Browser? Nutzt du `https` oder `http`? Nutzt du Port `8400` (bzw. `840x` abhängig der Instanz)?

**Comment by Robbi12** [comment]
Das ist ja das komische. Version 49 und auch noch ein paar spätere funktionieren

Die neueste zeigt dann lediglich die Tableiste an. Sonst nichts.

Port 8400

Kein HTTPS

In einem anderen Browser funktioniert es.

Kannst du mir noch sagen wie ich den Ordner jarvis-scripts im IoBroker anlegen kann? Ich mache den Punkt neuen Ordner auf, dann kommt ein Eingabefeld. Hier nimmt er mir aber keine Buchstaben etc.an. Es tut sich nichts

**Comment by mcuiobroker** [comment]
Zeig doch mal Deine Dateien / Benutzerdaten geöffnet

**Comment by Robbi12** [comment]
Hallo. Ich habe die Version 7.1.0. Ich kann aber dort wo du jarvis-scripts eingibts nichts eingeben. Es nimmt mir keinen Buchstaben etc. an

**Comment by Zefau** [comment]
Ist ein ioBroker Bug. Ging bei mir auch nicht. Die neuste jarvis beta sollte es anlegen.

**Comment by Robbi12** [comment]
Hab jetzt die 73 drauf. Funktioniert. Kann also geschlossen werden.
