### ISSUE TITLE
[beta.66] Fehlende Icons bei Adapter-Start

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2778]
Laut Protokolldatei fehlen nachfolgende Icons:
```
/jarvis/apple-touch-icon-152x152.png: Not exists
/jarvis/apple-touch-icon-152x152-precomposed.png: Not exists
```

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.67` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.67` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Soll das so sein?
jarvis-Verzeichnis im jarvis-Verzeichnis
![image](https://github.com/user-attachments/assets/5c0a9318-a97f-499c-b918-24d1a09fad40)

**Comment by Zefau** [comment]
Jo, ist so richtig. Liegt an der Abspaltung vom Web Adapter und, dass Jarvis nun alles übernimmt.

**Comment by Erwin40** [comment]
Icons sind jetzt da, ich schließe...
