### ISSUE TITLE
v3.2.0-beta.55 t.device is null

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2779]
@teletapi
https://forum.iobroker.net/topic/68566/jarvis-v3-2-x-just-another-remarkable-vis-alpha-testing/245

![image](https://github.com/user-attachments/assets/24b2e1aa-d3ff-4e5b-9081-ede017d6ecec)

**Comment by Zefau** [comment]
Hast du mehr Informationen oder die Browser Konsole mit Stack Trace? Sonst ist es die Nadel im Heuhaufen

**Comment by mcuiobroker** [comment]
![image](https://github.com/user-attachments/assets/fefd1176-2f1f-48c0-a7cb-42d471fab0a8)
Browser-Console kommt vielleicht noch, wie gesagt ist vom User @teletapi.

**Comment by Erwin40** [comment]
Ich hatte diese Meldungen auch mal. Waren aber in einer späteren beta wieder weg.
Probier doch mal die beta.67
Die läuft momentan super...

**Comment by mcuiobroker** [comment]
Infos von @teletapi mit v3.2.0-beta.67, beta.68 und  beta.69

![image](https://github.com/user-attachments/assets/3be55d44-b0ef-428d-9935-249a66dedc59)


![image](https://github.com/user-attachments/assets/1da5d9c9-a7ea-4626-9269-c29ed88082fa)
![image](https://github.com/user-attachments/assets/91ae146e-d413-4391-8e1d-e1213a8b9735)
```
downloadable font: download failed (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:0): status=2147746065 source: 
http://192.168.178.82:8400/jarvis/assets/materialdesignicons-webfont.662fefa8.woff2
 
Eine Notification-Anfrage kann nur in einem sicheren Kontext gestartet werden. index.html
GET
http://192.168.178.82:8400/jarvis/assets/materialdesignicons-webfont.662fefa8.woff2
[HTTP/1.1 404 Not Found 0ms]
 
downloadable font: download failed (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:0): status=2147746065 source:
http://192.168.178.82:8400/jarvis/assets/materialdesignicons-webfont.662fefa8.woff2
 
```

Dort ist auch in einem Bild `--var` erkennbar 
![image](https://github.com/user-attachments/assets/2c4ba4bf-6e49-42ac-a2ab-1d738e024c6d)

**Comment by Zefau** [comment]
Hat aber alles nichts mit `t.device is null` zu tun. Für `--var` haben wir ein Issue und auch für `woff2`. Ich mach hier zu.
