### ISSUE TITLE
Devices - self set icons via interface won't work / escaped doublequotes in string 

### ISSUE THREAD

**Issue by ottk3** [Zefau/ioBroker.jarvis#278]
I noticed that self set icons won't show up anymore.
The icon-string gets surrounded by escaped double-quotes automatically and the icon won't work.

![image](https://user-images.githubusercontent.com/5236802/97640379-e0ff7800-1a40-11eb-8b47-2e3ad49e7725.png)
![image](https://user-images.githubusercontent.com/5236802/97640419-f83e6580-1a40-11eb-9711-31e9a5ac8236.png)

This is the related JSON:

	{
	  "firmware":{
		"state":{
		  "node":"zwave2.0.Node_002.Version.firmwareVersions"
		},
		"action":"",
		"icon":"\"memory\""
	  }
	}

_Version: 1.1.0-beta.59_

**Comment by welanco** [comment]
Hi Ottk3,

this works with the right JSON-format:

{
   "default": "memory"
}

See wiki for more examples: https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices

**Comment by ottk3** [comment]
Oh! I didn't notice that changed lately. Thank you!

**Comment by Zefau** [comment]
It is json formatted when it comes to complex statements including the current state. Generally though only providing an icon should work as you expected it. 

I will check this tonight.

**Comment by Zefau** [comment]
Should be resolved with `v1.1.0-beta.62`.

**Comment by ottk3** [comment]
can confirm, works fine now! Thank you!
