### ISSUE TITLE
v3.2.0-beta.66 Protokollfehler und Warnungen unhandled promise rejection: null

### ISSUE THREAD

**Issue by Hohenbostler** [Zefau/ioBroker.jarvis#2780]
Guten Morgen.

leider sagen mir diese Fehler nichts aber sie tauchen jeden Tag auf. 

**Prerequisites / Voraussetzungen**
v3.2.0-beta.66
![Warnings](https://github.com/user-attachments/assets/be103a81-8748-44dd-b0d0-7ff1ef839472)
![Error](https://github.com/user-attachments/assets/f1adffbe-2618-443b-b7ef-37c567c50c9a)

- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Comment by Zefau** [comment]
Die kommen schon direkt beim connecten? Oder auf einer bestimmten Seite?

**Comment by Hohenbostler** [comment]
Ich weiß gar nicht genau wann ich weiß nur das ich nachts um 4 Uhr nicht wach bin -> Aber die Browser sind natürlich trotzdem an wo Jarvis drauf läuft .

**Comment by Erwin40** [comment]
Mal auf allen Geräten Jarvis-Seite schließen, Cache komplett löschen und ioBroker neu starten.

**Comment by Hohenbostler** [comment]
> Mal auf allen Geräten Jarvis-Seite schließen, Cache komplett löschen und ioBroker neu starten.

Naja die Gelbe Warning meldung kommt alles von dem PC auf dem ich das bereits gemacht habe.

**Comment by Zefau** [comment]
Hast du irgendeine grobe Idee wo es herkommt? Beta-65 war noch ohne Fehler?

**Comment by Erwin40** [comment]
Irgendwie kommt mir das bekannt vor...

Wichtig nach Adapter-Update und solche komischen Fehler:
Auf ALLEN Geräten Jarvis Tab schließen und erst dann Cache vollständig löschen (insbesondere auf Apple-Geräte).
(Nur wenn Jarvis Tab geschlossen ist, kann auch der Cache vollständig gecleart werden)
Ja, das ist extrem lästig. Alle Anmeldungen und Web-Site Einstellungen, gehen flöten.
Hilft aber alles nix...
Zefau findet irgendwann dafür sicher eine elegantere Lösung.

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.68` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.68` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Hohenbostler** [comment]
Also der Error scheint jetzt weg zu sein. Ich bekomme jetzt nur immer wieder die ganzen Warnings.

**Comment by Zefau** [comment]
Analog zu deinem Screenshot Warnungen zu `"command": "log"` ?

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.70` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.70` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Hohenbostler** [comment]
Guten Morgen, 
leider nicht. Was komisch ist das kommt nur wenn ich am Jarvis garnichts mache. Der Tab ist nur offen auf einem Opera Browser
![1](https://github.com/user-attachments/assets/c9c25c64-ac08-41a7-abef-246949b0e195)

**Comment by Hohenbostler** [comment]
Guten Morgen. 
In der 3.2.0.beta71 tritt der Fehler wieder auf.

![iobroker](https://github.com/user-attachments/assets/87bb2686-859f-4630-b6b7-5a333d9cafaa)
