### ISSUE TITLE
v3.2.0-beta.71 - widget und layout Problem

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2786]
Wollte jarvis von beta.6 nach beta.74 aktualisieren.
Beim ersten starten erblickte ich aber nur ein leeren Bildschirm.
Dann erstmal testweise zurück zu älteren Versionen.
Der Fehler ist seit bata.71

Ursache:
Layout und widgets werden nicht geladen.
Die iob Datenpunkte sind zwar vorhanden, werden von jarvis aber wohl nicht akzeptiert.
Was noch funktioniert ist die jarvis Konfiguration.
Bei den widgets steht: widgets (0)
Layout ist leer.
Geräre sind vorhanden.
Keine Fehler im Log.

Wurde vielleicht seit beta.71 die Signaturen geändert ?

**Comment by Zefau** [comment]
Die Datenpunkte sollten in etwa so aussehen:

Widget
```
{
  "version": 3.1,
  "signature": 5307344557358072,
  "widgets": {
    ...
  }
}
```

Layout
```
{
  "version": 3,
  "signature": 7122358612391562,
  "layout": [
    ...
  ]
}
```

Mit einem anderen Wert bei `signature`, aber strukturell genauso.

**Comment by Bernd9000** [comment]
Okay, bei mir:

```
{
 "version": 3.1,
  "signature": 3752144589808410,
  "widgets": {
    ...
  }
}
```

Layout
```
"version": 3,
  "signature": 5919475249026683,
  "layout": [
    ...
  ]
}
```

Wonach könnte ich noch schauen ?

**Comment by Zefau** [comment]
Cache löschen. Benutzt du Firefox oder Chrome?

Cache löschen via Firefox über F12 -> `Local Storage` (dort Rechtsklick `alles löschen`):

![grafik](https://github.com/user-attachments/assets/c2d896c5-4230-47b4-946e-24444be44e4c)

**Comment by Bernd9000** [comment]
Jo, hab ich auch gerade dran gedacht und das war es auch.
 "Cookies und Website-Daten" gelöscht, hab ich länger nicht mehr gemacht....
Es läuft wieder.
Ich mache dicht....
