### ISSUE TITLE
[v3.2.0-beta.74 und früher] Statelist widget - Inhalt wird nicht skaliert

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#2787]
`Höhe aller widgets identisch mit sichtbarer Seitenhöhe` ist an
`Tab Vollbild` ist aus

Inhalt im widget mit Statelist werden nicht mehr skaliert.
Schriftgröße wird nicht geändert.
Browser F5 hilft nicht.

Wie bei beta.49 schon einmal [#2608](https://github.com/Zefau/ioBroker.jarvis/issues/2608#issuecomment-2254273728)

**Comment by Zefau** [comment]
Die Version `v3.2.0-beta.75` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-beta.75` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Bernd9000** [comment]
Funktioniert erstmal wieder wobei es schwieriger geworden ist die richtige Größe der widgets zu wählen.
Hat man z.B. ein schmales widget mit der Höhe 1h wird hier die widget Größe und auch der Inhalt nicht mehr skaliert.
Die Folge sind gewaltige Unterchiede der Schriftgröße.
Mach ich dieses widget auf 2h ist in dem widget ein viel zu großer leerer Freiraum.
Vermutlich spielt hier auch die Option "Widget Label und Icon verstecken" eine Rolle.

Könnte man bei widgets mit Höhe 1h die Skalierung noch aktivieren ?

**Comment by Bernd9000** [comment]
Nachtrag:
Seit dieser Version werden die widgets mit iFrames mit der Option "Tab Vollbild" = aus nicht mehr skaliert.

**Comment by Zefau** [comment]
> Könnte man bei widgets mit Höhe 1h die Skalierung noch aktivieren ?

Skalierung ist immer aktiv, wenn die Option aktiviert ist, egal wie hoch das Widget ist.

> Hat man z.B. ein schmales widget mit der Höhe 1h wird hier die widget Größe und auch der Inhalt nicht mehr skaliert.
Die Folge sind gewaltige Unterschiede der Schriftgrößen.
Mach ich dieses widget auf 2h ist in dem widget ein viel zu großer leerer Freiraum.

Mach gerne mal Screenshots, damit ich das besser nachvollziehen / nachstellen kann.

**Comment by Zefau** [comment]
>  Seit dieser Version werden die widgets mit iFrames mit der Option "Tab Vollbild" = aus nicht mehr skaliert.
Es wird nicht auf Höhenänderung reagiert.

Kann ich nicht bestätigen. Bei mir wird im Firefox und Chrome mitskaliert.

**Comment by Bernd9000** [comment]
Erstmal das mit dem IFrame Problem.
Zum verdeutlichen hab ich es als Gif aufgenommen.
9 Widgets, 8 sind StateLists und in der Mitte das IFrame.
Verändert man die Breite ist alles Okay.
Wenn man aber die Höhe ändert wird entweder das IFrame Fenster in den darunter liegenden StateList geschoben oder es entsteht eine Lücke.

![Animation1](https://github.com/user-attachments/assets/defbfa2d-676e-4ab0-b4fe-c3c09611f30e)

**Comment by Zefau** [comment]
Also dieses Issue ist für `StateList`. Die werden aber korrekt skaliert laut deinem gif. Also hier kein ToDo, richtig?

`iFrame` wird nicht korrekt skaliert. Das wäre dann noch offen, richtig?

**Comment by Bernd9000** [comment]
Moment:

Hier das mit dem StateList.
Das ober StateList widget mit dem Datum und Uhrzeit hat Höhe 1h und wird nicht skaliert.

Version RC1
![Animation2](https://github.com/user-attachments/assets/e0c87d86-b149-46f3-aca1-08a2c0cf7616)


Und hier nochmal die beta6 wo es funktionierte:
![Animation3](https://github.com/user-attachments/assets/9fbc177a-9c13-45e0-9d83-94d4cca94c7a)

**Comment by Bernd9000** [comment]
Das Modul DateTime ist auch betroffen, ist also nicht nut StateList

**Comment by Bernd9000** [comment]
Funktioniert mit rc.7
