### ISSUE TITLE
[v3.2.0-beta.74] Eine Notification-Anfrage kann nur aus einem ...

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2788]
Firefox
![image](https://github.com/user-attachments/assets/a1d2a337-c145-46f5-9af6-76994b8aaf14)

**Comment by Zefau** [comment]
https://stackoverflow.com/a/61475985

**Comment by Zefau** [comment]
Dabei handelt es sich um die Abfrage, ob native Notifications von jarvis geschickt werden dürfen. Die sind ja neu mit v3.2, auch für Android.

Scheinbar muss die Anfrage zur Bestätigung aber in einen Button packen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.1` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.1` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Erwin40** [comment]
Ich frag mal blöd...
Die Meldung sehe ich bei FF schon seit einigen betas:
![grafik](https://github.com/user-attachments/assets/ec9e09e8-10eb-4500-8a9b-60917d8d33d1)

Geht es hier um den gleichen Fehler?

**Comment by mcuiobroker** [comment]
Ja. Ist aber erledigt. Danke.

**Comment by Zefau** [comment]
Fehler kommt wegen den nativen Benachrichtigungen, siehe https://github.com/Zefau/ioBroker.jarvis/issues/873

Die Abfrage muss über einen Button gestartet werden und kam bisher einfach so.
