### ISSUE TITLE
3.2.0-beta.75 does not start up

### ISSUE THREAD

**Issue by Tom54497** [Zefau/ioBroker.jarvis#2789]
It simply does not start up and stucks on the rotating Jarvis circle at intro screen

**Comment by Zefau** [comment]
Hast du Fehler in der Browser Konsole (via F12)?

Do you have errors in the browser console via F12?

**Comment by Tom54497** [comment]
Yes:

index-8e6349ca.js:106 styles Received payload with error: Unexpected end of JSON input

index-8e6349ca.js:106 App-McGn2K9ZAg Unexpected end of JSON input
index-8e6349ca.js:106 scripts Received payload with error: Unexpected end of JSON input
index-8e6349ca.js:106 App-cXn2MZAgK7 Unexpected end of JSON input
index.html#/:1 [Deprecation] Custom state pseudo classes have been changed from ":--var" to ":state(var)". See more here: https://github.com/w3c/csswg-drafts/issues/4805
﻿

**Comment by Zefau** [comment]
Error Message reflects that your Style is broken. What is the contents of `jarvis.0.css` / `jarvis.0.styles`?

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.3` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.3` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by bambi-arch** [comment]
Hab das gleiche Problem. Auch mit 3.2.0-rc.3. 
Browserdaten alle gelöscht.

**Comment by mcuiobroker** [comment]
Haben alle jarvis DPs die signature drin?

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.4` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.4` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Tom54497** [comment]
Nun funktioniert es.

Update auf v3.2.0-rc.5

1. Datenpunkt Wert in CSS setzen:
{
  "version": 3.2,
  "signature": 1234,
  "styles": ""
}

2. Datenpunkt Wert in SCRIPTS setzen:
{
  "version": 3.2,
  "signature": 3338908027751811,
  "scripts": ""
}

3. Browser Cache löschen

**Comment by Tom54497** [comment]
Nun funktioniert es.

Update auf v3.2.0-rc.5

1. Datenpunkt Wert in CSS setzen:
{
  "version": 3.2,
  "signature": 1234,
  "styles": ""
}

2. Datenpunkt Wert in SCRIPTS setzen:
{
  "version": 3.2,
  "signature": 3338908027751811,
  "scripts": ""
}

3. Browser Cache löschen
