### ISSUE TITLE
Modul Chart - Is where a max limit for history-values? Chart stopped after 9 hours

### ISSUE THREAD

**Issue by welanco** [Zefau/ioBroker.jarvis#279]
I have a history in mysql-db for temp-sensors with history values ==> interval 60 seconds.

The chart in the chart module stops after 9 hours. Smaller intervals in charts work fine and show all data.

Is where a max limit for the amount of history-values?
<img width="952" alt="Screenshot 2020-10-30 093128" src="https://user-images.githubusercontent.com/46993165/97679194-3e251900-1a95-11eb-9e84-1b944021f615.png">
<img width="944" alt="Screenshot 2020-10-30 093356" src="https://user-images.githubusercontent.com/46993165/97679205-42513680-1a95-11eb-989a-7f3c8a38eb72.png">
<img width="935" alt="Screenshot 2020-10-30 094517" src="https://user-images.githubusercontent.com/46993165/97679213-454c2700-1a95-11eb-87cd-682559ae31c2.png">
<img width="941" alt="Screenshot 2020-10-30 094600" src="https://user-images.githubusercontent.com/46993165/97679220-48dfae00-1a95-11eb-8021-ae0be8c4c264.png">

Thank you for your Commitment

**Comment by Zefau** [comment]
Is this issue resolved when you reload the page? Means is it caused because the values are not updated? Or is it also cut off after a page reload?

**Comment by welanco** [comment]
The vlaues are also cut off after page reload and after adapter and iobroker restart.

It seems, that where is a limit. Smaller intervalls show all values.

I also tried:

1. delete sql-history
2. create new history
3. restart iobroker

But without success.

**Comment by funky4t** [comment]
Same here with my history data chart. In 1.0.9 chart was perfectly showing outside temp history backwards 2 days. After update to beta 59 I'm missing the last hours (~10-12h). When reducing history to 1 instead of 2 days automatically generated update-chart is working fine.

**Comment by Zefau** [comment]
Should be resolved with `v1.1.0-beta.62`.

**Comment by welanco** [comment]
1. removed old jarvis version
2. restart iobroker
3. install new version v1.1.0-beta.62
4. create new config

result ==> chart data not loaded ==> no errors in console or log

![Screenshot 2020-10-31 090533](https://user-images.githubusercontent.com/46993165/97774488-80fbf500-1b58-11eb-861c-0457d54c9f4d.png)

![Screenshot 2020-10-31 090349](https://user-images.githubusercontent.com/46993165/97774481-69bd0780-1b58-11eb-8698-cda09a349daf.png)

**Comment by Zefau** [comment]
There's no need for uninstalling and rebooting. Only reinstall the latest beta over your installation, that should be fine.

I will further investigate on this. Thanks for your feedback.

**Comment by funky4t** [comment]
Works for me, just re-installed the Beta62 and my chart is back working fine. Also my weather widget is now loading....
Thanks

**Comment by Zefau** [comment]
@funky4t can you confirm as well with beta-63 ?

**Comment by funky4t** [comment]
@Zefau yes, because I thought I was on Beta62, but after checking, I'm already on Beta63. :)

**Comment by Zefau** [comment]
@welanco are you using `history.0` ?

**Comment by Zefau** [comment]
@welanco could you check `v1.1.0-beta.65` ? This considers both `history` and `influxdb`.

**Comment by welanco** [comment]
Hi Zefau,

i use the "SQL History (sql.0)" and mysql-db:

![image](https://user-images.githubusercontent.com/46993165/97788928-d5d15700-1bbc-11eb-86f9-7b7cec10affe.png)

Testet with v1.1.0-beta.64 ==> same result ==> data not loaded

**Comment by Zefau** [comment]
ah, true, you wrote that already. Ok, I have a look at that.

**Comment by Zefau** [comment]
Could you check `v1.1.0-beta.67` ?

**Comment by funky4t** [comment]
Hi sorry to get back again,
I moved to beta.68 and now my chart is broken again. all time loading circle....
When changing days from 2 to 1 a system error appears.
Datapoint has not been changed and was working in .63, history table shows entries

<img width="1433" alt="Bildschirmfoto 2020-10-31 um 23 53 32" src="https://user-images.githubusercontent.com/57875762/97791600-72532380-1bd4-11eb-8e3a-763fc6a7c3d6.png">

**Comment by Zefau** [comment]
Could you check `v1.1.0-beta.70` ?

**Comment by funky4t** [comment]
Beta.70 and chart is back again. Thanks! :)
