### ISSUE TITLE
3.2.0-beta.75 Adapter schmiert jedes mal ab 

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2790]
Ich meine seit der 70er Version startet der Adapter nicht mehr
folgendes im Log
`
host.NUC-ioBroker | 2024-09-12 12:23:35.951 | warn | Do not restart adapter system.adapter.jarvis.0 because restart loop detected
-- | -- | -- | --
host.NUC-ioBroker | 2024-09-12 12:23:35.951 | error | instance system.adapter.jarvis.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
jarvis.0 | 2024-09-12 12:23:35.348 | error | Exception-Code: ERR_FEATURE_UNAVAILABLE_ON_PLATFORM: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
jarvis.0 | 2024-09-12 12:23:35.348 | error | TypeError [ERR_FEATURE_UNAVAILABLE_ON_PLATFORM]: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js at new NodeError (node:internal/errors:405:5) at watch (node:fs:2416:11) at JarvisServer.init (/opt/iobroker/node_modules/iobroker.jarvis/lib/jarvis.server.js:1:2460) at /opt/iobroker/node_modules/iobroker.jarvis/jarvis.min.js:1:2631
jarvis.0 | 2024-09-12 12:23:35.348 | error | unhandled promise rejection: The feature watch recursively is unavailable on the current platform, which is being used to run Node.js
jarvis.0 | 2024-09-12 12:23:35.347 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
`

**Comment by Zefau** [comment]
Welche Nodejs Version hast du?

**Comment by Zefau** [comment]
Bitte Node.js >= 20 sicherstellen.

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.1` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.1` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by intruder7777** [comment]
lag an Node,js. erledigt
