### ISSUE TITLE
Können die iFrame Logs wieder raus?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2791]
![image](https://github.com/user-attachments/assets/0ac190a0-c7a1-4398-a997-551fa97ac111)

**Comment by Zefau** [comment]
ah, jo, danke für den Hinweis.

**Comment by mcuiobroker** [comment]
Ist mir erst durch ein anderes Issue aufgefallen. undefined bei maxHeight.

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.2` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.2` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Sind weg. Danke
