### ISSUE TITLE
[v3.2.0-rc.1] Link nicht vorhanden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2794]
`https://github.com/Zefau/ioBroker.jarvis/wiki/de-Modules#liste-der-module`
![image](https://github.com/user-attachments/assets/ed856f01-21b9-4dae-ae08-ded9161d6bf5)
![image](https://github.com/user-attachments/assets/dd99febc-c68a-4d42-b02c-e9e5eb69fcdc)

**Comment by Zefau** [comment]
Ist nicht mehr im Wiki vorhanden. Hast du hier etwas zum Nachlesen in deinem Wiki? Sonst nehme ich den Link erstmal raus.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/v3-fur-einsteiger/module

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.2` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.2` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
