### ISSUE TITLE
HistoryGraph zeigt Graphen nicht bei mehreren Y-Achsen

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#2795]
> Aber jetzt werden nicht mehr alle Kurven angezeigt
> ![image](https://github.com/user-attachments/assets/dad3ef3e-64d0-4a19-a09e-38b5c7d085bb)

> ![image](https://github.com/user-attachments/assets/bbaef197-b6e9-4c86-9464-03d2a2202339)

> Dabei fällt auf, dass Y-Axis nicht angezeigt wird
![image](https://github.com/user-attachments/assets/08f5a5ee-08f1-485d-a1fa-6994892600c9)
> ![image](https://github.com/user-attachments/assets/07bec0d9-f984-43c7-928c-071832111e2f)

> "Bad" (Orange) sollte da sein
> ![image](https://github.com/user-attachments/assets/86151188-f095-415c-a333-e6d6ffe04bbd)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/2206#issuecomment-2347378546_

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.5` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.5` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
