### ISSUE TITLE
using jarvis with authentication doesn't work anymore after upgrade to 3.2

### ISSUE THREAD

**Issue by schluo** [Zefau/ioBroker.jarvis#2797]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
Version:  v3.2.0-rc.1
Console Error:
`App-hGejAmgnwn Authentication failed! User not logged-in for "authentication"! `

**Describe the bug / Beschreibe den Fehler**
After upgrading to 3.2.0-rc1 starting jarvis is only possible if deactivating authentication. Otherwise start screen hangs. Before upgrading login works fine.
Futhermore, some setting changes within jarvis GUI (maybe all pro-account setting?!) can not be saved. Save buttons/mouse pointer are deactivated)

![issue 01](https://github.com/user-attachments/assets/81861331-adf3-4ac0-9196-0645581ffbc2)
![issue 03](https://github.com/user-attachments/assets/57163250-7a53-48fd-a38e-acbae97ba182)
![issue 02](https://github.com/user-attachments/assets/0e7a647a-740c-482e-ace6-793e09d69ccc)

**Comment by Zefau** [comment]
Authentication method has changed from 3.1 to 3.2. From which version are you coming?

What are your adapter settings specifically?

**Comment by schluo** [comment]
> Authentication method has changed from 3.1 to 3.2. From which version are you coming?
> 3.1.8
> What are your adapter settings specifically?
see attached screenshot
![issue 04](https://github.com/user-attachments/assets/373b5bb1-eb87-4a96-8f6c-5bed9459594a)

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.2` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.2` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by schluo** [comment]
Thank you for providing  3.2.0 rc2. Authentication issues is solved. The issue regarding pro-feature enablement still exists.

**Comment by Zefau** [comment]
It is greyed out because somewhere in the configuration is an error (which prevents from saving). I will add more info about the errors in the next release candidate (rc).

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.3` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.3` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by schluo** [comment]
> It is greyed out because somewhere in the configuration is an error (which prevents from saving). I will add more info about the errors in the next release candidate (rc).

the issues seems to be related to css which I heavily used before I updated -->` **styles:null**`

**Comment by Zefau** [comment]
Oh, after updating to 3.2 everything got erased to `null`? Do you have a backup? I will fix the issue, thanks for the feedback

**Comment by schluo** [comment]
Slightly different situation. After uprading to 3.2 and during hanging start screen the browser console told me there were issues with the css dp. After replacing the content in the dp with `{}` I was able to start.
What should I do to reset all css related settings? I already tried blank, `[]` and `{}`. 
After resetting I would be able to insert the backuped css content via webui.
BTW: thank you very much for your unbelievable swift feedbacks :-)

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.3` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.3` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Zefau** [comment]
`v3.2.0-rc.4` fixes the incorrect way of converting the v3.1 structure to v3.2. Thus, you should be able to convert correctly when restoring a backup once you have `rc.4` installed.
