### ISSUE TITLE
Fehlermeldung bei allen iframes (v3.2.0-rc.1)

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#2798]
Seit der Version v3.2.0-rc.1 erhalte ich bei allen "iframes" eine Fehlermeldung:

10.0.2.2 (Chrome) - true, {}, {"width":"560px","height":"291px","containerHeight":"291px","maxHeight":"undefinedpx","intWidth":560,"intHeight":291,"intContainerHeight":291}, true

Bei der Darstellung des iframe ist alles richtig.

**Comment by mcuiobroker** [comment]
Wird bei der nächsten Version wieder raus genommen, war notwendig, um Problemfälle zu erkennen.

**Comment by sigi2345** [comment]
> Wird bei der nächsten Version wieder raus genommen, war notwendig, um Problemfälle zu erkennen. Obwohl es hier doch interessant ist da bei Dir maxHeight falsch gesetzt ist. -> undefined
> 
> @bogaboo Ist dieses undefined auch bei den anderen iFrames?

Ist bei mir auch so, bei allen

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.2` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.2` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by sigi2345** [comment]
Bei mir mit v3.2.0-rc.3 Fehler weg

**Comment by bogaboo** [comment]
Bin jetzt auf v3.2.0-rc.3 die Fehlermeldungen sind weg !

@sigi2345  Ja, das "undefined" hatte ich bei alles iframes.
