### ISSUE TITLE
[v3.2.0-rc.1] Haut das Log voll bis 4GB

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2799]
![image](https://github.com/user-attachments/assets/146ee433-81ac-47f2-ad19-60a4b51a89b8)
![image](https://github.com/user-attachments/assets/2ba9e404-7255-487e-8cee-a8ac47e28ae7)
Hat evtl. etwas mit Zertifikatverlust zu tun?
Ich musste nachdem erneuten Aufruf, dass Zertifikat bestätigen, bzw. unsicher klicken und weiter.

**Comment by Zefau** [comment]
Glaube das ist eins deiner Skripte? Die Wortreihenfolge `Reconnect durchgeführt` gibt es in jarvis nicht. Kannst du Skripte mal abstellen?

**Comment by Zefau** [comment]
Du hast bei der Meldung leider die Spalte ausgeblendet. Also Zeile `:106` und danach fehlt was.

**Comment by mcuiobroker** [comment]
> Du hast bei der Meldung leider die Spalte ausgeblendet.

Mehr kommt da nicht
Normalerweise wird ja das script angezeigt, von dem es kommt. Dies ist aber seit einigen Versionen nicht mehr.

**Comment by Zefau** [comment]
Ja, weil das Logging ja zentral erfasst wird, damit es ins Backend gehen kann. Sonst muss ich das abschaltbar machen.

**Comment by mcuiobroker** [comment]
Das wäre schön, dann kann man beim Testen sehen, wo es herkommt.

**Comment by mcuiobroker** [comment]
Hab die Ursache gefunden.
Es werden wieder mehrere IDs im localStorage für eine Instanz abgelegt.
Instanz 0
![image](https://github.com/user-attachments/assets/035eefd1-0bce-480f-abfd-1cf0f6dd5032)

Instanz 1
![image](https://github.com/user-attachments/assets/42136d75-7356-4efc-889a-fc5348f7ad78)

Deswegen hat ein Script geloggt, weil ich dort ein reload deaktiviert hatte. 
Das Problem hatte wir aber schon mal mit den mehrfachen IDs im localStorage.

**Comment by Zefau** [comment]
Der Namespace, den du dort siehst, errechnet nach `socket.url + '#' + socket.instance + '#' + version`.

Der Cache wird nur gelöscht, wenn die Fehlermeldung kommt, dass die Version unterschiedlich ist. Sonst nicht.

**Comment by mcuiobroker** [comment]
Es sind aber 2 unterschiedliche drin, von denen er nur einen nutzt.

**Comment by Zefau** [comment]
Ich weiß es nicht. Wie gesagt wird je Kombination von URL, Instanz und Version ein solcher Namespace angelegt.

Insofern ja, vermutlich wegen der zweiten Instanz.

**Comment by Zefau** [comment]
![grafik](https://github.com/user-attachments/assets/180eacc4-7b9d-4fc3-aaa9-cded450e573c)

**Comment by mcuiobroker** [comment]
Trotzdem weise ich nochmal darauf hin, dass der localStorage beim Upgrade nicht gelöscht wird.
NachUpgrade hat man dann 2x alle DPs im LocalStorage und nach dem nächsten Upgrade 3x usw.
-> Es haut den localStorage voll.

**Comment by Zefau** [comment]
Ist doch aber egal?
