### ISSUE TITLE
Empty spaces in datapoints not allowed

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#280]
Hi, I tried to insert snmp datapoints like "Temp HDD 1" to a device and a warning came up. I used the exact same DPs in 1.0.9 and they worked fine. Instead of re-build all DPs from the ground I successfully copied structure of NAS1 to NAS2 in codeview. I just made some slight correction for the ip of the DP in codeview and everything worked fine.

As a non programming user: is it a bug in the beta or should DPs in general not contain empty spaces and 1.0.9 did not care about that so far? I guess it is the last, right? 😆

**Comment by Zefau** [comment]
Whitespaces are not supported in the states. That's not a bug. This is simply not validated in the expert view. States with a whitespace will most likely not update their values.

**Comment by funky4t** [comment]
Thank you, I changed to "_" instead of blank spaces.
