### ISSUE TITLE
[v3.2.0-rc.1] StateList, Device with ID xxxxxxxxxxxx not found

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#2800]
Hallo,

habe seit dem Update auf v3.2.0-rc.1 folgende Fehler:

`
jarvis.0
2024-09-13 18:26:11.834	error	1 (Chrome) - Cannot read properties of null (reading 'id')
 
jarvis.0
2024-09-13 18:26:11.833	error	1 (Chrome) - Cannot read properties of null (reading 'id')
 
jarvis.0
2024-09-13 18:26:11.830	warn	1 (Chrome) - StateList, Device with ID b185b12a-27f8-421a-b57b-3176b43f2701 not found!
 
jarvis.0
2024-09-13 18:26:11.830	warn	1 (Chrome) - StateList, Device with ID 8df5305e-c80e-4486-9337-771ec7107c18 not found!
`
![Screenshot (961)](https://github.com/user-attachments/assets/a3a840fa-9b45-439a-b3cf-af505dde7caa)
![Screenshot (960)](https://github.com/user-attachments/assets/3784313f-fa10-40cb-8871-3846f20d51f0)

Forum Beitrag:

https://forum.iobroker.net/topic/68566/jarvis-v3-2-x-just-another-remarkable-vis/7

**Comment by Zefau** [comment]
Jo, schon gesehen. Mit der nächsten rc behoben.

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.2` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.2` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by sigi2345** [comment]
> Die Version `v3.2.0-rc.2` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.
> 
> The version `v3.2.0-rc.2` should fix the bug - please verify. If the bug has been solved, you may close the issue.

Im Protokoll weg aber unter F12 noch da

![Screenshot (963)](https://github.com/user-attachments/assets/0aa4b02f-88c1-42a5-b15f-43eaaa9cd88c)

**Comment by sigi2345** [comment]
Fehler weg, Fehlerhafte ID gefunden
