### ISSUE TITLE
3.1.8 adapter settings lead to 404 error

### ISSUE THREAD

**Issue by Tom54497** [Zefau/ioBroker.jarvis#2806]
Cannot access settings any more. See pic.
![Screenshot (186)](https://github.com/user-attachments/assets/131c5e1e-c0a7-40db-9268-cea28a26b55b)

**Comment by mcuiobroker** [comment]
Try an upload

**Comment by Zefau** [comment]
Have you updated or anything? If yes, please upload as mcu stated or try to reinstall.
