### ISSUE TITLE
Adapter Settings laden nicht

### ISSUE THREAD

**Issue by simatec** [Zefau/ioBroker.jarvis#2808]
Nach einem Update auf v3.2.0-rc.5 laden die Settings in einer Endlosschleife.
Sie werden für 1-2 Sekunden angezeigt und die Seite lädt neu...
In der Browser-Konsole sind keine Fehler oder Warnungen

**Comment by Zefau** [comment]
Hast du den Web Adapter installiert?

**Comment by mcuiobroker** [comment]
Ist web.0 installiert? Da war doch mal was, bzgl. man muss bei web immer die Instanz 0 haben, damit jarvis läuft?

**Comment by Zefau** [comment]
Web wird nicht mehr benötigt für jarvis, aber es werden initial die Einstellungen daraus geladen. Hab selbst nicht getestet was passiert, wenn es den gar nicht gibt, daher die Frage.

**Comment by simatec** [comment]
web.0 gibt es… er schein auch daraus die Settings zu holen… also was ich für eine Sekunde so sehen kann

**Comment by Zefau** [comment]
Kannst du mal auf debug stellen und das Log teilen?

**Comment by simatec** [comment]
Im Log war nichts zu sehen... Hab es behoben, indem ich im web.0 die Zertifikate deaktiviert habe.
Aber mal ne Frage am Rande... Wir versuchen ja gerade iob ein wenig zu standardisieren und wollen gerade auch in den Configs der Adapter mehr einheitliches Design und vor allem responsive Design umsetzen.
Kannst du da mal drüber nachdenken, ob es nicht sinnvoll wäre json Config einzusetzen? Oder wenn es aus technischen Gründen nicht geht, dann halt wenigstens vom Design her sich an dem iob Standard orientieren? 

Wäre cool, wenn jarvis da mit beitragen würde, etwas mehr zu standardisieren

**Comment by Erwin40** [comment]
Bitte schließen.

**Comment by Zefau** [comment]
@simatec mach dafür gerne einen Feature Request auf. Hab mich da allerdings noch nicht eingelesen und i.d.R. sind die Sachen bei ioBroker unglaublich schlecht bis gar nicht dokumentiert. Die Frage, die ich mir stelle ist, ob `jsonConfig` unterstützt auf Basis einzelner Elemente andere Elemente zu `disablen`?

**Comment by mcuiobroker** [comment]
Problem mit den Einstellungen zur Instanz ist doch noch da?

**Comment by Zefau** [comment]
Was genau?

**Comment by mcuiobroker** [comment]
Der Fehler von oben.
```
Nach einem Update auf v3.2.0-rc.5 laden die Settings in einer Endlosschleife.
Sie werden für 1-2 Sekunden angezeigt und die Seite lädt neu...
In der Browser-Konsole sind keine Fehler oder Warnungen
```

**Comment by Zefau** [comment]
Ich kann den Fehler bei mir nicht reproduzieren. Ich erstelle eine neue Instanz bei mir und das funktioniert ohne Probleme. Wenn ich im Web-Adapter Zertifikate eingestellt habe - wie von [simatec](https://github.com/simatec) beschrieben - funktioniert es auch bei mir.

**Comment by mcuiobroker** [comment]
Kein Ahnung vielleicht muss man noch einige Sachen beim Update prüfen?
- nodejs>=20
- jarvis-DPs haben den korrekten Aufbau nach der Umstellung (ist ja auch beim anderen Problem sinnvoll) Nummer kommt

es muss ja einen Grund dafür geben und der ist bislang nicht bekannt
