### ISSUE TITLE
Modul Weather - new bug with 1.1.0-beta.59 - Data not loaded

### ISSUE THREAD

**Issue by welanco** [Zefau/ioBroker.jarvis#281]
Since i updated to 1.1.0-beta.59 - no data in weather loaded.

1.1.0-beta.57 worked fine.

<img width="951" alt="Screenshot 2020-10-30 154810" src="https://user-images.githubusercontent.com/46993165/97719421-5b72db00-1ac7-11eb-9ab5-a1f087b5edac.png">

<img width="954" alt="Screenshot 2020-10-30 154507" src="https://user-images.githubusercontent.com/46993165/97719069-f4552680-1ac6-11eb-853c-54a968ccd141.png">

**Comment by Zefau** [comment]
Do you have any errors in the browser console (F12) ?

**Comment by welanco** [comment]
No errors - no data

tried complete reinstall from jarvis - nothing

Chart module also not loading data !

<img width="1103" alt="Screenshot 2020-10-30 200509" src="https://user-images.githubusercontent.com/46993165/97746899-69d2ee00-1aeb-11eb-8cac-ea0d693481f1.png">

**Comment by Zefau** [comment]
ah ok, I think it is because I changed the dependency from `request` to `got`. You may install `got` manually by `npm i got` in the ioBroker.jarvis directory or wait for the next beta tonight.

**Comment by welanco** [comment]
That didn't work for me. 

I installed got in dir:

<img width="892" alt="Screenshot 2020-10-30 202824" src="https://user-images.githubusercontent.com/46993165/97749230-fdf28480-1aee-11eb-89ed-308e4917f027.png">

Same result ==> wait for nightly beta

thank you for the support

**Comment by Zefau** [comment]
Could you check `v1.1.0-beta.60`? Thanks

**Comment by welanco** [comment]
PERFECT JOB !!! But chart module is still not receiving any data => new issue?

<img width="959" alt="Screenshot 2020-10-30 205326" src="https://user-images.githubusercontent.com/46993165/97750944-fe404f00-1af1-11eb-8522-895637b16568.png">

**Comment by Zefau** [comment]
No, not necessary. Does `v1.1.0-beta.61` solves it?

**Comment by simatec** [comment]
I have the same problem with Beta 64. The weather data is not loaded

`Log.js:55 Weather # Unexpected token < in JSON at position 0 in "http://api.daswetter.com/index.php?v=3.0&api_lang=de&localidad=xxxxxx&affiliate_id=xxxxxxxxxx"`

**Comment by welanco** [comment]
Hi Zefau,

das Weather-Modul läuft seit der v1.1.0-beta.61 und auch mit der aktuellen v1.1.0-beta.64.

**Comment by simatec** [comment]
Bei mir leider nicht. Auf meinen Testsystem läuft Beta 24. da geht das Wetter. Auf dem Hauptsystem ist Beta 24. da lädt es nicht

**Comment by Zefau** [comment]
@simatec du bist noch auf beta.**24**? Oder hast du dich verschrieben?

**Comment by simatec** [comment]
auf dem testsystem ... hab es jetzt mit Beta 64 aber zum laufen bekommen. Musste an der api etwas ändern ... dann ging es

**Comment by Zefau** [comment]
Was war denn falsch? Ggf. kann ich noch was einbauen, um es zu härten?

**Comment by simatec** [comment]
Das muss ich erstmal noch ergründen. Habe aus der api Zeichen wegnehmen müssen, was aber bei der Beta 24 noch ging. Hatte die Api nur kopiert

**Comment by Zefau** [comment]
Wenn's erstmal passt ist es ja ok.
