### ISSUE TITLE
[v3.2.0-rc.5] Problem wenn man den Trigger geändert hatte

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2810]
![image](https://github.com/user-attachments/assets/7ffec1fa-b876-464b-b4e2-712458e27d2a)
Hat man den Trigger DP einmal verändert und nimmt die Änderung wieder raus, steht zwar in grau der Anzeige DP drin, aber möchte man dann eine z.B SwitchAction nutzen und nur umschalten, kommt die Meldung.
Man muss dann den Anzeige-DP nochmal in den Trigger-DP setzen, damit die Meldung weggeht.
![image](https://github.com/user-attachments/assets/0e9e9283-b447-4cda-8288-6a0f1203454e)

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.9` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.9` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt, danke.
