### ISSUE TITLE
HistoryGraph wird nur der letzte DP angezeigt

### ISSUE THREAD

**Issue by bambi-arch** [Zefau/ioBroker.jarvis#2814]
Hallo,
nach dem Update von 3.18 auf v3.2.0-rc.3 wird bei mehreren DP immer nur der letzte in der Liste angezeigt. Das Problem betrifft mehr als 10 Diagramme.

Danke für die Prüfung.

![image](https://github.com/user-attachments/assets/9c11dbf7-87a0-4cc0-a85b-4bcaa84318cf)
![image](https://github.com/user-attachments/assets/69e2c440-a144-4069-8e3f-d51831c20d1c)
![image](https://github.com/user-attachments/assets/3d1b332f-4b19-4a36-ac39-aa1dbf5aa636)
![image](https://github.com/user-attachments/assets/034c8f8d-75e3-4916-b9ce-0a60feb0924f)

**Comment by mcuiobroker** [comment]
Und mit rc.5?

**Comment by bambi-arch** [comment]
Mit rc5 funktioniert es wieder. Danke
