### ISSUE TITLE
[3.2.0-rc.5] Geräteliste leer wenn "Gewerk" gelöscht wird

### ISSUE THREAD

**Issue by Joylancer** [Zefau/ioBroker.jarvis#2815]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ jarvis 3.2.0-rc.5] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
Wenn beim Anlegen das "Gewerk" gelöscht wird und dann mit "Übernehmen" gespeichert wird, bleibt bei einem Reload die Seite "Geräteliste" leer.
Wiederherstellen ging bei mir nur mit einem Restore der Geräteliste.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Gewerk löschen und Speichern verursacht bei mir keinen Fehler: 

![2815](https://github.com/user-attachments/assets/38979ecf-40f3-4102-993d-50deb9b026c9)

Was genau machst du anders, dass es bei dir crasht?
Welcher Fehler wird via F12 angezeigt?

**Comment by Joylancer** [comment]
![grafik](https://github.com/user-attachments/assets/0389499e-cc19-4881-9b54-cba4999575ed)

**Comment by Joylancer** [comment]
lösch mal bitte bei einem eingebundenen Gerät (Widget und Layout) das Gewerk.
Dann sieht es bei mir so aus.
Momentan speichert Jarvis auch keine neuen Geräte im Widget, muss mal schauen, was da los ist.

**Comment by Joylancer** [comment]
![grafik](https://github.com/user-attachments/assets/c35280d1-ccdf-4d00-8931-901c97cceeb4)
So sieht dann das jason "Devices" an der Stelle aus.
Sobald ich das korrigiere, erscheinen auch die Geräte wieder

**Comment by Zefau** [comment]
Kannst du in der Browser Konsole mal "Konsole" auf machen? Dort sollte eine Fehlermeldung stehen

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.7` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.7` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Joylancer** [comment]
Updatet to 3.2.0-rc10 ... solved, thx
