### ISSUE TITLE
[v3.2.0-rc.5] Alias Adapter Geräte Import nicht da

### ISSUE THREAD

**Issue by Chris25122** [Zefau/ioBroker.jarvis#2824]
Ich wollte seit langem neue Objekte importieren. Dabei ist mir aufgefallen, dass der Alias Adapter nicht mehr zur Auswahl steht. Ich vermute, dass es ein Bug ist, da es in früheren Versionen immer zur Verfügung stand.

![image](https://github.com/user-attachments/assets/9ea49d46-5911-48fc-bc42-66a76869b67a)

**Comment by mcuiobroker** [comment]
Es werden nur die Adapter angezeigt, die installiert sind.
Evtl. hängt es damit zusammen.

**Comment by Chris25122** [comment]
Danke für den Hinweis, der Alias Adapter ist natürlich installiert.

**Comment by Chris25122** [comment]
@Zefau könntest du dir das bei Gelegenheit bitte anschauen ? Ohne den automatischen Import ist es extrem mühselig neue Geräte per Hand einzubinden

**Comment by Zefau** [comment]
Ne, scheint https://github.com/ioBroker/ioBroker.devices/ zu sein.

**Comment by Chris25122** [comment]
> Das ist https://github.com/iobroker-community-adapters/ioBroker.alias-manager richtig?

Der hier ist es. Das hatte in früheren Versionen auch immer problemlos funktioniert

**Comment by mcuiobroker** [comment]
Ich hab keinen alias-Adapter und trotzdem habe ich alias.0-DPs (createAlias). Werden die dann gefunden?

**Comment by mcuiobroker** [comment]
Ja, javascript Standard-Funktion

**Comment by Zefau** [comment]
Ich kann es auch an `discovery` binden; ich selbst habe es aber deinstalliert. Hast du es noch installiert? Dann kannst du ja theoretisch auch einfach den Alias-Adapter installieren.

**Comment by mcuiobroker** [comment]
Lass mal ich installiere dann Alias.

**Comment by Chris25122** [comment]
Gibt es Neuigkeiten dazu ? Braucht ihr noch Input von mir ?

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.5` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.5` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by Chris25122** [comment]
> Die Version `v3.2.0-rc.5` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.
> 
> The version `v3.2.0-rc.5` should fix the bug - please verify. If the bug has been solved, you may close the issue.

Der Bug besteht leider auch mit Version v3.2.0-rc.5 weiterhin.

**Comment by Chris25122** [comment]
@Zefau brauchst du noch weitere Infos von mir ?

**Comment by Chris25122** [comment]
Nein ich habe den Adapter ( der in den letzten Versionen immer funktioniert hat )

![image](https://github.com/user-attachments/assets/cd49aeb0-7fc2-4de3-af03-af5f472fd922)

**Comment by Zefau** [comment]
Schau mal bitte nochmal mit der aktuellen `rc`.

![grafik](https://github.com/user-attachments/assets/603202f4-71c1-4345-a79b-fb06f87652de)

![grafik](https://github.com/user-attachments/assets/e4cb0d1b-0e2b-471b-b1ba-81803994ad70)

![grafik](https://github.com/user-attachments/assets/660bfe57-ae0d-46f0-894f-fb254d9e2e1a)

**Comment by Chris25122** [comment]
Damit funktioniert es danke :) Habe nur ein Problem wenn ich es in Edge öffne ( auch nur eine Instanz betroffen )
![image](https://github.com/user-attachments/assets/fe260ddb-e7d4-4871-b1d3-eea7fd327c7a)
