### ISSUE TITLE
[v3.2.0-rc.5] HistoryGraph - Kurven verschwinden nach Tabwechsel

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2830]
scripts sind ausgeschaltet

F5 -> Kurven sind da -> Tabwechsel -> wieder zurück zum HistoryGraph Kurven sind weg.

![historySubscriptionVerschwindet](https://github.com/user-attachments/assets/9b337b5b-3027-4c84-bedd-bd8bbe46149f)

**Comment by neo-licious** [comment]
Bei mir das gleiche Problem. Gibt es diesbezüglich schon eine Lösung?

**Comment by bastian-mer** [comment]
Bei mir, auch mit dem heutigen GitHub-Stand, das selbe Problem. Egal welcher Browser (Firefox, Chrome), egal ob Laptop oder Android-Handy.

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.12` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.12` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke.
