### ISSUE TITLE
[v3.2.0-rc.5] tryToReconnect wird nicht gesetzt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2831]
Nach dem ein Reconnect versucht wurde sollte window.Socket.tryToReconnect gesetzt werden, damit man erkennen kann, dass dies versucht wurde. Es wird aber nicht gesetzt, wie man im Bild erkennen kann.

![image](https://github.com/user-attachments/assets/c0c8c125-21ea-4fb3-94fc-805f506d0ed2)

**Comment by Zefau** [comment]
`tryToReconnect` ist `true` während jarvis reconnected. Der Status geht auf `false` wenn jarvis wieder connected ist, also mit der Meldung `Connected to wss:// ...` ist es wieder `false`.
