### ISSUE TITLE
[v3.2.0-rc.5] mediaProgressTime falsch berechnet

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2832]
Zeit gibt es nicht 02:62:55

![image](https://github.com/user-attachments/assets/d63f2ef7-390b-4e0d-b806-46e7d0e9c4e7)

![image](https://github.com/user-attachments/assets/2f31d321-35a4-4d96-87a8-d818e7397c58)

**Comment by Zefau** [comment]
Was steht bei `.progress` im Datenpunkt?
Der ist Grundlage für die Anzeige. Die Umrechnung erfolgt mittels:
```js

	time = parseInt(time);
	withHours = withHours || (time > 3600);
	
	if (Number.isNaN(time)) {
		return withHours ? '00:00:00' : '00:00';
	}
	
	const hours = '0' + Math.floor(time / 3600);
	const minutes = '0' + Math.floor(time / 60);
	const seconds = '0' + (time % 60);
	
	return withHours ? [ hours.substr(-2), minutes.substr(-2), seconds.substr(-2) ].join(':') : [ minutes.substr(-2), seconds.substr(-2) ].join(':');
```

**Comment by mcuiobroker** [comment]
Es gibt doch in den Objekten schon den String?
![image](https://github.com/user-attachments/assets/0ee89d04-3fd7-4267-8a10-cbd5a6711590)

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.12` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.12` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by mcuiobroker** [comment]
Passt. Danke
