### ISSUE TITLE
HM-PB-2-FM wird nicht unterstützt (Geräte mit unbekannten Datenpunkten)

### ISSUE THREAD

**Issue by hdering** [Zefau/ioBroker.jarvis#2839]
Ich habe ein Homematic Gerät, welches von Jarvis nicht erkannt wird:
HM-PB-2-FM

Ob es mit der stabilen Version 3.1.2 (?) funktioniert hatte, kann ich ehrlich gesagt nicht sagen.

Kann man die benötigten Datenpunkte irgendwie aus iobroker einfach exportieren?

- [ ]  jarvis.0, v3.2.0-rc.5

Geräte mit undefinierten Datenpunkten (bitte dem Entwickler melden)

**Comment by Zefau** [comment]
Kannst du mir sagen, welche Datenpunkte es im ioBroker beim gibt, die du einbinden möchtest? Dann übernehme ich das entsprechend.

**Comment by hdering** [comment]
@Zefau Reicht dir dieser Screenshot?
![image](https://github.com/user-attachments/assets/668c7fe8-c6ef-40d8-bc30-e439459f8165)

Ich habe noch weitere 12 Geräte die nicht importiert werden. Soll ich jeweils einen eigenen Issue erstellen oder alles hier rein?

**Comment by Zefau** [comment]
Kann alles hier rein. Alternativ kannst du es auch unter https://github.com/Zefau/jarvis.adapters/blob/main/hm-rpc.js selbst hinzufügen und einen pull request machen.

Also ich brauch es im Format:

```
		"HM-PB-2-FM": {
			"PRESS_CONT1": {
				"state": ".1.PRESS_CONT",
				"action": ".1.PRESS_CONT"
			},
			"PRESS_LONG1": {
				"state": ".1.PRESS_LONG",
				"action": ".1.PRESS_LONG"
			},
			"PRESS_SHORT1": {
				"state": ".1.PRESS_SHORT",
				"action": ".1.PRESS_SHORT"
			},
			"PRESS_CONT2": {
				"state": ".2.PRESS_CONT",
				"action": ".2.PRESS_CONT"
			},
			"PRESS_LONG2": {
				"state": ".2.PRESS_LONG",
				"action": ".2.PRESS_LONG"
			},
			"PRESS_SHORT2": {
				"state": ".2.PRESS_SHORT",
				"action": ".2.PRESS_SHORT"
			}
		}
```

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-rc.12` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-rc.12`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by hdering** [comment]
Der Schalter HM-PB-2-FM wird wieder korrekt erkannt.
