### ISSUE TITLE
State Explorer - Eieruhr des Todes

### ISSUE THREAD

**Issue by SarasarMQ** [Zefau/ioBroker.jarvis#2840]
Jarvis Version = jarvis.0, v3.2.0-rc.5

Ich habe gersde versucht ein neues State in Jarvis einzubinden. Dieser liegt in dem Unterordner von sourceanalytix. Jarvis kann ab der Version 3.2 diesen Baum nicht mehr darstellen. in der Version davon 3.09 ging es einwandfrei.,
Alle anderen Ordner können aufgemacht werden, es betreifft nur diesen einen Ordner.

![image](https://github.com/user-attachments/assets/d9ca1297-85ce-45cc-b2b8-f4e673b6f4fa)

Gruß Marcus

**Comment by Zefau** [comment]
Hast du einen Fehler in der Browser Konsole via F12?

**Comment by SarasarMQ** [comment]
meinst du das ?
![image](https://github.com/user-attachments/assets/b57a005d-a8b9-474b-993e-9116db7ef1bb)

**Comment by Zefau** [comment]
Die Version `v3.2.0-rc.7` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-rc.7` should fix the bug - please verify. If the bug has been solved, you may close the issue.

**Comment by SarasarMQ** [comment]
RC7 und aktuelle RC9 starten bei mir nicht:
RC5 geht einwandfrei, leider aber mit der Eieruhr

<img width="1274" alt="image" src="https://github.com/user-attachments/assets/3fce4862-03bc-464c-80f0-c3c4b4b6c79c">

**Comment by Zefau** [comment]
Lösch mal den Cache.

**Comment by SarasarMQ** [comment]
Einwandfrei, Heute habe jetzt den RC11 installiert. Den Cache gelöscht und nun wird der Ordner im State Explorer einwandrei angezeigt.

![image](https://github.com/user-attachments/assets/01c4f10f-b97e-46b6-8566-64680fdfda04)

Vielen Dank !!
