### ISSUE TITLE
[v3.2.0-rc.11] iFrame wird immer wieder neu geladen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#2848]
![image](https://github.com/user-attachments/assets/5a0148e0-da5d-4af4-bd99-7f3ad37c1c95)

![image](https://github.com/user-attachments/assets/81f3f9b8-8103-41ea-8810-14c136765878)

Einstellungen
![image](https://github.com/user-attachments/assets/d97a4bda-82ba-4b62-b6b7-b8292416488a)

**Comment by Zefau** [comment]
Ist wahrscheinlich kein Fehler in jarvis. Jarvis nutzt kein `socket.io` und auch `main.41cee985` ist keine Datei von jarvis.

Das, was du versuchst einzubinden, kann sich scheinbar nicht mit dem `socket.io` verbinden, was dort konfiguriert ist. Du müsstest das einmal prüfen.

**Comment by mcuiobroker** [comment]
Ja, war tatsächlich eine falsche Einstellung in proxy-Instanz-Pfad.
