### ISSUE TITLE
discarded X devices due to incorrect configuration - log entry

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#285]
Hi Zefau,

I still found this entry in Beta63 log. 

<img width="1264" alt="Bildschirmfoto 2020-10-31 um 10 06 31" src="https://user-images.githubusercontent.com/57875762/97775477-2fa43380-1b61-11eb-88fc-b64a1dc926cb.png">

I guess there are some old devices not configured properly, but it's quite hard to find the right device for fixing or even deleting it. I can imagine I auto-added some of my deconz-devices in Jarvis1.0.9. These were not configured quite well, so I manually deleted most of them. Is it possible these devices show up in log with "incorrect config" although already deleted?

Thanks for your great adapter and keep on going

**Comment by Zefau** [comment]
With `v1.1.0-beta.64` you will have a list of discarded devices in the browser console log.

**Comment by welanco** [comment]
Worked with v1.1.0-beta.64 => found it under "warnings" in browser console

![image](https://user-images.githubusercontent.com/46993165/97789247-39f51a80-1bbf-11eb-9a98-c72fe75ec161.png)

**Comment by Zefau** [comment]
Additionally, the message `App # Processed xxx devices and discarded x devices due to incorrect configuration. Ssee browser console log for more details` holds the data, which devices are discarded.

![image](https://user-images.githubusercontent.com/14368811/97789890-6fe8cd80-1bc4-11eb-8b2b-72e21fcccd2b.png)

**Comment by funky4t** [comment]
@Zefau ich muss dich zu diesem Thema nochmal nerven:
Ich hab jetzt eine Stunde damit zugebracht, in meiner Browserconsole die Liste der discarded devices zu finden, leider völlig erfolglos. Ich brauch da zum Verständnis mal deinen Support:

1. Dein gelbe Markierung ist doch eine Liste der in Jarvis nicht verarbeiteten und somit verworfenen Geräte?
2. Finde ich die in Jarvis denn noch in der "Expertenansicht"? Sprich, sollte ich die Geräte dort aus dem Code "entfernen", um eventuell die Performance zu verbessern? Oder werden die da eh schon "rausgenommen" und nicht verarbeitet?
3. Wie komme ich jetzt an diese Objektliste dran, wenn ich keine Ahnung von der Browserconsole habe? :(

Ich werfe das nur mal so in den Raum, aber wäre es nicht super, wenn die Geräte mittelfristig unter Jarvis selbst als "Devices"->"Discarded" ausgewiesen wären und der Anwender ohne Consolen-Kenntnisse dort die Geräte entweder korrigieren oder aber auch einfach löschen könnte? Nicht dass mein eigenes Interesse da irgendwie durchscheint, aber ich könnte mir vorstellen, dass einige Jarvis durchaus gern nutzen würden ohne aber Plan von Browserconsole etc. zu haben! ;)

**Comment by Zefau** [comment]
Die `discardedDevices` findest du in der Browser-Konsole (F12) beim Log-Eintrag:
![image](https://user-images.githubusercontent.com/14368811/98462170-72de5200-21b2-11eb-8474-b5a7d3a64bf3.png)

Dort einfach hinten aufklappen, dann hast du die nötigen Informationen.

**Comment by funky4t** [comment]
Lach bitte ich, aber ich hab den ioBroker Log auf und starte dann auf dem Mac in Safari unter Entwickler die JS-Console, mit F12 rennt da bei mir nix. Shift+Command+C startet hier laut Google die Console. Da hab ich dann folgenden Screen.... und da klappt bei mir nix auf :( Oder ich bin zu blöd...


<img width="1307" alt="Bildschirmfoto 2020-11-08 um 11 15 54" src="https://user-images.githubusercontent.com/57875762/98462336-03696200-21b4-11eb-89d5-6795a39f9937.png">

**Comment by Zefau** [comment]
Du musst in jarvis die Konsole öffnen, nicht im ioBroker.

**Comment by funky4t** [comment]
Autsch....okay...wieder was gelernt! 👍 🙈
Da kriege ich auch was "zum Ausklappen" allerdings tauchen im Gegensatz  zu added nach dem Ausklappen bei Discarded meines Erachtens für mich nix Brauchbares raus, während 41 von 57 devices sauber aufgelistet werden... Aber mit #329 wird das ja eventuell auch für "Anwender" einfacher, also no panic.
<img width="816" alt="Bildschirmfoto 2020-11-08 um 11 37 05" src="https://user-images.githubusercontent.com/57875762/98462853-7f18de00-21b7-11eb-9c8a-1f85b1bf2730.png">

**Comment by Zefau** [comment]
Dann wurden wohl keine verworfen. Es gibt noch die ignorierten Geräte, die beim Importer entsprechend markiert wurden. Die werden hier nicht dargestellt (habe ich für die nächste beta angepasst).
