### ISSUE TITLE
Nach Neuinstallation auf Pi5 und Restore zwei Jarvis Kacheln im Dashboard

### ISSUE THREAD

**Issue by Erwin40** [Zefau/ioBroker.jarvis#2852]
Verflixt, ich bin mir sicher, das hatte schon mal einer.
Finde aber den Issue nicht mehr :-(

Also, ich habe einen Pi5 komplett neu aufgesetzt.
Alle Adapter neu installiert und mauell konfiguriert.
Jarvis-Adapter Stable 3.18 installiert und anschließend die Beta RC12.
Restore aus BackitUp.
Eigentlich funktioniert (mit kleinen Nacharbeiten) alles super.
Nur habe ich jetzt im Übersicht-DashBoard zwei Jarvis Kacheln:
![grafik](https://github.com/user-attachments/assets/01c626fe-1663-485c-8362-61d6361beefd)

Wie bekomme ich die `undefined` wieder wech?

**Comment by mcuiobroker** [comment]
Kann man im admin löschen.

**Comment by Erwin40** [comment]
Oh mann, das Icon rechts unten hab ich ja noch nie wahrgenommen...
Vielen Dank! 🙏
