### ISSUE TITLE
[v3.2.0-rc.12] Label in Geräte als Binding geht aber trotzdem Fehler

### ISSUE THREAD

**Issue by intruder7777** [Zefau/ioBroker.jarvis#2856]
Folgende Situation: Ich habe mehrere Pflanzensensoren die Pflanzensensor 1 bis x heißen. Alle besitzen einen Datenpunkt über den ich den Ort festlege. Also Pflanzensensor 1 ist z.B. Wohnzimmer Elephantenfuss. Den Datenpunkt Name nutze ich als Eingabefeld. So dass ich zu jeder Zeit die Verwendung ändern kann. Jetzt habe ich eine StateList erstellt als Liste. Und das Label als Binding zum Feld Name. Im Editor eingetragen "{alias.0.Zigbee.Pflanzensensoren.Pflanzensensor_1.Name}". Dies akzeptiert er auch im Editor und es funktioniert dann auch wie es soll aber im Nachgang bemängelt er ein falsches JSON Format.
![image](https://github.com/user-attachments/assets/1624a97c-1b9f-45e3-a41e-83fc97a95a23)

**Comment by mcuiobroker** [comment]
```
{"default":"{alias.0.Zigbee....}"}
```

**Comment by intruder7777** [comment]
@mcuiobroker Hmmm... was soll ich sagen. Es geht!! :-) Danke dir. War ja einfach
