### ISSUE TITLE
Custom HTML Widget macht VISU Blank

### ISSUE THREAD

**Issue by mandragora666** [Zefau/ioBroker.jarvis#286]
Hallo Zefau

Hab gerade ein Problem.
Hab mich mit dem Custom HTML Widget herumgespielt und als ich es hinzugefügt und gespeichert habe ist meine VISU nun blank.
Kann leider nichts mehr machen.

Latest beta ist installiert.
LOG ist auf debug aber zeigt auch nichts brauchbares an.

![image](https://user-images.githubusercontent.com/73381262/97778959-317af080-1b7b-11eb-96b0-e94c10acaf01.png)

Was könnte das jetzt hervorgerufen haben bzw. wie kann ich das wieder beheben ?
Vielen Dank schon im Voraus für deine Hilfe.

lg
mandragora

**Comment by Zefau** [comment]
Schau mal bitte in der Browser Konsole, ob dort mehr steht
Stell mal bitte das JSON des Layout bereit (der Abschnitt mit CustomHTML reicht sicherlich)
Ggf. wäre auch das HTML interessant, was du reingepackt hast.

**Comment by mandragora666** [comment]
Hallo Zefau

In der Konsole sehe ich mal das hier
![image](https://user-images.githubusercontent.com/73381262/97785269-44ee8180-1ba4-11eb-9144-bf2894f4d138.png)

Wo finde ich bitte das JSON des Layouts?

Was ich da reingepackt habe?
Ich hab hier anscheinend versehentlich einen Adapter ausgewählt da soweit ich mich noch erinnern konnte nichts anderes zum Auswählen war.

Danke
lg
mandragora

**Comment by Zefau** [comment]
Den Datenpunkt `jarvis.0.layout` kopieren und auf pastebin.com mit Passwort und Verfallsdatum packen. Dann mir das PW hier posten (ich lösche dann) oder über ioBroker forum.

**Comment by mandragora666** [comment]
Hi

Alles klar
ist gemacht

https://pastebin.com/X1LaSH6Q
DC6pSgTukj

Danke dir
lg
mandragora

**Comment by Zefau** [comment]
Probier mal bitte `v1.1.0-beta.67`.

**Comment by mandragora666** [comment]
Jaaaa... perfekt. 
Vielen herzlichen Dank für das schnelle fixen.
Nun funktioniert wieder alles.

Schönen Sonntag wünsch ich dir.
lg
mandragora
