### ISSUE TITLE
Hide Scrollbar 

### ISSUE THREAD

**Issue by kwittwer** [Zefau/ioBroker.jarvis#287]
Hi, could you add an option to hide all scrollbars? I use Chromium for my Walldisplay and it display all scollbars permanently. 
In Biobroker vis I added the the following css to hide them but keep the possibility to scroll.
```
/* Hide scrollbar for Chrome, Safari and Opera */
.example::-webkit-scrollbar {
  display: none;
}

/* Hide scrollbar for IE and Edge */
.example {
  -ms-overflow-style: none;
}
```

**Comment by Zefau** [comment]
implemented with `v3.1.0-alpha.26`
