### ISSUE TITLE
Issue running two instances

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#290]
> In Safari bleibt die 2. Instanz weiterhin weiß, kein Layout oder Gerät wird angezeigt obwohl beides konfiguriert ist und auch im Layout DP so steht. Im 2. Safari Tab ist Jarvis der ersten Instanz geöffnet. Bei Refresh der Seite komme ich dann nicht wie erwartet auf die Jarvis Visa der Instanz 1 sondern zum ebenfalls weißen Screen...der 2. Instanz?
Wenn ich dann ALLE Jarvis Tab schließe und wieder über iobroker gehe öffnen sich die jeweiligen Instanzen in zwei neuen Tabs. Instanz 1 wie gewohnt, Instanz 2 mit Whitescreen. Geh ich wieder auf Command+R bekomme ich auf BEIDEN Tabs den Whitescreen.

> Auf Firefox lässt sich das ebenfalls reproduzieren, jedoch mit dem Unterschied, dass das Testgerät und Layout der Instanz 2 hier auch angezeigt wird. Mit Command+R "verliere" ich dann aber im Tab auch meine Ursprungskonfig und bekomme die Testanzeigeder Instanz 2. In der URL beider Browser steht auch immer nur IP:8082/jarvis/index.html Kommt er da beim einfachen Refresh irgendwie "durcheinander"?

> ich öffne im Tab 1 die Instanz1 und in Tab2 die Instanz2, aktualisiere ich nun Tab1, erhalte ich als Aktualisierung die Instanz2 angezeigt. Beim aktualisieren öffnet sich immer die Instanz im zuletzt geöffneten Browser Tabs. Ebenso im Safari nur eben weiterhin mit weißem Startscreen ohne Geräte und Layout... 😞 Ich hab schon Cache geleert aber leider erfolglos....

**Comment by funky4t** [comment]
ich klink mich hier mal ein, mir kommt der Text so bekannt vor! :)
Mit Beta70 öffnen sich beim URL Klick ein zweiter Tab mit Jarvis, allerdings lädt dann auch im erste Tab das Jarvis Layout und die iObroker Admin verschwindet.....
Das Refresh Verhalten bei 2 Tabs mit beiden Instanzen ist unverändert, soweit ich das jetzt getestet habe. Aber solange man das weiß, ist das nicht sooo tragisch.

**Comment by Zefau** [comment]
Could you check again with the latest beta?

**Comment by funky4t** [comment]
Beta.72: Jarvis tabs opens in parent tab of ioBroker and not in a new tab - teste in Firefox.
The refresh behavior in each tab didn't change, means refresh in the first opened tab opens the last Jarvis VIS - so there is no change.

**Comment by funky4t** [comment]
![image](https://user-images.githubusercontent.com/57875762/97874123-d5e66980-1d18-11eb-9ccc-7af31fb5cd9e.png)

Getting an error message when starting Jarvis from iOS Homescreen-Link. Safari via URL is working... 
I do not know if this has to do with the second instance or Beta72. As far as I remeber, the Homescreen-Link was working yesterday with two instances and Problem came with Beta72. But I'm not 100% sure..

**Comment by funky4t** [comment]
Ahh and yes I removed "old link" from the homescreen and created a new one from the working URL in Safari, still no change, same error.

**Comment by Zefau** [comment]
@funky4t probier bitte nochmal mit `v1.1.0-beta.100`.

**Comment by funky4t** [comment]
@zefau: sorry war mal ein paar Tage nicht vorm Rechner.... ALSO: Bin auf der Beta.107 und der Shortcut vom Homescreen läuft soweit. Beim Öffnen der beiden Instanzen in 2 Tabs im Safari verhält es sich jedoch unverändert. Ich öffne I0 und dann I1, dann Command+R im I0 Tab und es öffnet sich die Visu von I1 - als quasi "last one wins". Stört mich aber nicht mehr so, hab der Erzeugerfraktion die komplette URL mit Sockets als Link gegeben. ;)

**Comment by Zefau** [comment]
@funky4t Das geht technisch leider auch nicht anders. jarvis hat keine Möglichkeit sich die Instanz zu merken außer, wenn das über die URL mitgegeben wird. Ich könnte es im Browser speichern, aber dann würde sich 0 und 1 immer gegenseitig überschreiben und der Fehler wäre identisch. Also ohne die Instanz über die URL mitzugeben geht es leider nicht.
