### ISSUE TITLE
automatische Seitenwechsel nach x Minuten

### ISSUE THREAD

**Issue by simatec** [Zefau/ioBroker.jarvis#293]
Erst einmal danke für den super Adapter.
Ich habe aber einen Wunsch. Ich habe bisher in meiner VIS immer eine automatische Umschaltung nach x Minuten auf dem Home Bildschirm gehabt.
Könnte man die in jarvis noch mit einbauen?  Halt am sinnvollsten konfigurierbar

**Comment by Zefau** [comment]
wurde in v3 hinzugefügt

**Comment by mcuiobroker** [comment]
Funktioniert.
