### ISSUE TITLE
Connection error: "Connect an into timeout"

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#295]
I am using Jarvis on my Android device (placed a shortcut with Chrome at my homescreen).  When I reopen Jarvis and after a small peroid of time I need to reload Jarvis because of "Connect an into timeout". Is this a Jarvis or iobroker releated setting?

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/514212
https://forum.iobroker.net/post/514181

**Comment by Zefau** [comment]
Could you try `v1.1.0-beta.77` ? Does this help?

**Comment by stony2k** [comment]
For sure. How do I install this beta version?

**Comment by Zefau** [comment]
Via the cat in ioBroker using the Github url

**Comment by stony2k** [comment]
Could you give me the beta url? Tried https://github.com/Zefau/ioBroker.jarvis.git but it install 1.0.9

**Comment by cryptedx** [comment]
Why url just select it!

![image](https://user-images.githubusercontent.com/20707078/98343145-ad5cb900-2011-11eb-930d-189ef4640edd.jpeg)

**Comment by stony2k** [comment]
Ok tried to install it this way, but the previously installed 1.0.9 still persists. Do I need to uninstall 1.0.9 (are all settings beeing deleted then)?

**Comment by cryptedx** [comment]
Try to switch to beta in settings:

<img width="652" alt="Bildschirmfoto 2020-11-06 um 09 30 45" src="https://user-images.githubusercontent.com/20707078/98343945-dc275f00-2012-11eb-83d4-1c1ff0465387.png">

Be careful! Now every adapter will show you beta versions!

**Comment by cryptedx** [comment]
BTW https://github.com/Zefau/ioBroker.jarvis.git is also working for me. It must be the "Beta" switch.

![image](https://user-images.githubusercontent.com/20707078/98344408-7d161a00-2013-11eb-8274-1c45e34429b8.png)

**Comment by stony2k** [comment]
This is funny. To install jarvis (1.0.8 back then) I had to set ioBroker to the lastest "Verwahrungsort" (don't know the English term). I will switch the "Verwahrungsort". I will toggle the setting and update all adapters hoping iobroker will install all stable versions over the betas.

**Comment by stony2k** [comment]
Installed beta 1.1.0-beta.79 and testing the timeout issue.

**Comment by stony2k** [comment]
Sorry, the timeout issue still persists :(

**Comment by Zefau** [comment]
Could you verify `v1.1.0-beta.94` (or later) if this error got solved?

**Comment by stony2k** [comment]
Issue seems kind of solved but still a bit buggy. Jarvis still displays a transport close message after a short period. In some cases a timeout message follows and Jarvis reconnects itself. But as I am writing this message: The transport close message appeared, I closed it with the x, but this time Jarvis didn't reconnect itself while it's opened. In this case I had to refresh the browser as in the past.

But you are getting close to solve the issue, thanks! 👍

**Comment by Zefau** [comment]
Please try again with `v1.1.0-beta.101`.

jarvis now reconnects on both errors and disconnects (before jarvis only handled errors, because I forgot disconnects..).
Furthermore, if no connection is given for 30 seconds, jarvis reloads the page itself.

**Comment by stony2k** [comment]
Updated to beta 101. Issue seems to be solved. Had one time a transport error and no auto reconnect and one time no error, but no action seemed to be forwarded to ioBroker. I would like to test it a couple of days, if it's ok.

**Comment by Zefau** [comment]
Ok, shall I reduce 30s to something less, e.g. 10s ?

**Comment by stony2k** [comment]
Let's try it low with 5 seconds. I would like to test if there is any
disturbance or negative effect then.

Am So., 15. Nov. 2020 um 12:13 Uhr schrieb Zefau <notifications@github.com>:

**Comment by Zefau** [comment]
I reduced the time with `v1.1.0-beta.106`.

**Comment by stony2k** [comment]
Reconnect works in 9/10 times. When it doesn't work, my Chrome browser (Android) display that it has no connection to the website. After hitting the reload button Jarvis reloads a appears. I would like leave it to you: Should we conside the issues as solved or watch it over the following betas?

**Comment by Zefau** [comment]
Most likely related to https://github.com/Zefau/ioBroker.jarvis/issues/357

**Comment by Zefau** [comment]
I'm closing this again in the favor of #357
