### ISSUE TITLE
StateList: Keine Aktualisierung des "LastChangeBody" Elements bei Trigger-Event

### ISSUE THREAD

**Issue by ninja-warrior** [Zefau/ioBroker.jarvis#296]
Guten Morgen,

zunächst einmal vielen Dank für die grandiose Arbeit. Mir gefällt die Visualisierung mit jarvis sehr gut und ich habe bereits fast alle Elemente aus meiner VIS in jarvis umgezogen. Ich betreibe den jarvis Adapters derzeit in der Version 1.1.0-beta.72

Mir ist aufgefallen, dass seit einiger Zeit in der StateList das "LastChangeBody" Element nach triggern des Datenpunkts in der Anzeige nicht automatisch aktualisiert. Erst nach Neuaufbau der Seite ändert sich der Text. Die Aktualisierung der primären und sekundären Datenpunkten klappt in der Anzeige der StateList hingegen einwandfrei. Wenn ich die Visualisierung bspw. mit zwei separaten Endgeräten öffne und mit einem Endgerät einen Datenpunkt trigger, erscheint die Änderung auch direkt auf dem zweiten Endgerät. Einzig für das Element "LastChangeBody" funktioniert das nicht unmittelbar.

Vielleicht kannst du danach ja mal bei Gelegenheit schauen. Ich habe auf die Schnelle keinen offenen Bug dazu gefunden.

Viele Grüße!

**Comment by ninja-warrior** [comment]
Kleine Korrektur: Ich habe eben festgestellt, dass das "LastChangeBody" Element mit zeitlicher Verzögerung des Trigger-Events in der Visualisierung auch ohne Neuaufbau der Seite aktualisiert wird. Ich war scheinbar zu ungeduldig. Aus meiner Sicht kann der Issue geschlossen werden.

**Comment by Zefau** [comment]
Ich schau heut Abend mal, ob ich die Verzögerung reduzieren kann.

**Comment by Zefau** [comment]
Sollte mit `v1.1.0-beta.83` wieder zeitnah aktualisieren.
