### ISSUE TITLE
Shortcut zu Jarvis funktioniert nicht unter IOS

### ISSUE THREAD

**Issue by ninja-warrior** [Zefau/ioBroker.jarvis#297]
Hallo zusammen,

ich habe gerade ein seltsames Verhalten festgestellt, dass bei mir erst mit Version 1.1.0-beta.72 aufgetreten ist:

Derzeit habe ich auf jedem Endgerät einen Shortcut zur Jarvis-Instanz (per Weblink) auf dem "Home-Bildschirm" hinterlegt. Unter Android funktioniert das auch wunderbar. Unter IOS habe ich sowohl mit iPad als auch mit iPhone jedoch das Problem, dass ich zwar über Safari auf die Jarvis-Instanz zugreifen kann, wenn ich diese direkt eingebe. Steige ich jedoch über den Shortcut auf dem Home-Bildschirm auf Jarvis zu, wird nur die Fehlermeldung "Connection failed! ..." angezeigt.

Siehe Screenshots anbei. 

![IMG_0347](https://user-images.githubusercontent.com/73721169/97865935-4a1a1080-1d0b-11eb-809e-73c18a8f1efe.PNG)
![IMG_0348](https://user-images.githubusercontent.com/73721169/97865938-4b4b3d80-1d0b-11eb-90c4-495c6051b9d6.PNG)
![IMG_0349](https://user-images.githubusercontent.com/73721169/97865940-4be3d400-1d0b-11eb-83fe-aa0843b651f5.PNG)

Viele Grüße!

**Comment by funky4t** [comment]
#290 geht mir ebenso :)

**Comment by Timmes123** [comment]
@ninja-warrior @funky4t 
ihr könnte das erstmal lösen, indem ihr die jarvis von der adapterliste aus aufmacht.
beim erstmaligen öffnen werden nämlich diese parameter hier gesetzt
http://192.168.0.33:8082/jarvis/index.html#instance=0&socketPort=8082
sobald ihr einmal eure vis über den link geöffnet habt gehts

**Comment by Timmes123** [comment]
Ist übrigens nicht nur bei IOS, sondern bei mir bei Android auch, bzw. vermutlich generell bei allen Geräten, bei denen instance und socketport noch nicht gesetzt wurde

**Comment by funky4t** [comment]
@Timmes123 
Über den Link klappt es über den jeweiligen Browser, das stimmt. Aber der Weg über das "Lesezeichen" auf dem Homescreen bleibt leider bei mir weiterhin rot...weil Instanz & Port fehlen. Auch beim Browser Refresh entfällt der Hinweis, wenn du zwei Instanzen in 2 Tabs offen hast, wird der Refresh beider Tabs dich auf eine Instanz zurückführen. Dazu hab ich auch nen Issue hier eröffnet. Scheinbar zeigt sich das Problem in ähnliche Form nun auch beim Öffnen über ein "Home-Screen"-Lesezeichen.

Hab auch leider bei iOS noch keine Option gefunden, die URL im Lesezeichen auf dem Homescreen anzuhängen, hätte ja eine einmalige einfache Lösung sein können... :(

**Comment by Zefau** [comment]
Es scheint so, als würde der Web Adapter den integrierten Socket nicht abstellen, wenn man auf socket-io stellt. Auch socket-io stellt nicht ab, wenn über Web integriert ausgewählt wird.

Wahrscheinlich ist das der Fehler. jarvis findet mehrere Verbindungen, wodurch am Ende scheinbar gar nichts mehr geht.

**Comment by Zefau** [comment]
Habe jetzt einige Sachen versucht und so richtig mag es nicht gelingen. 

Es liegt nicht an den fehlenden Parametern. Sofern diese fehlen, fällt jarvis auf Standardwerte zurück. Also Instanz ist immer `0`, wenn nicht gegeben und Port wird immer `8082` und `8084` probiert.

Ich selbst habe das Problem, dass der fully Browser ebenfalls nicht verbindet. Die Socket-URL in der Fehlermeldung ist eigentlich korrekt, aber der Socket kann scheinbar nicht verbinden. 

Habt ihr mit `v1.1.0-beta.77` mehr Erfolg?

**Comment by funky4t** [comment]
Werde morgen mal wieder komplett updaten und berichten. Komisch ist es, weil es ja schonmal lief und auch mit mehreren Instanzen... BTW in .74 ist bei mir auch das Problem mit der Anzeige der Charts wieder drin, schau ich morgen mal nach.

**Comment by skue-hash** [comment]
Guten Morgen,

seit ich gestern morgen die aktuellste Version hier von Github gezogen hatte, hab ich auch das Problem mit dem Homescreen Shortcut. Habe gerade eben nochmal Jarvis aus Github gezogen und das Problem ist immer noch. Allerdings ist es Version 079_beta. Und da muss ich jetzt leider mal dumm fragen ;-), wie kann ich von Github die 77 ziehen? Github ist noch ein unbekanntes Gebiet für mich. Und an dieser Stelle noch ein Riesen Dank für den Adapter, der macht echt süchtig :)).

**Comment by funky4t** [comment]
....
> 
> Habt ihr mit `v1.1.0-beta.77` mehr Erfolg?

Bin auf die .79 gegangen, da leider auch bei mir keine Änderung. Muss ich zurück auf .77? Dann brauch auch ich die Info, wie... :)

**Comment by Zefau** [comment]
Hat jemand die Möglichkeit eine Testinstanz mit v1.0.9 aufzusetzen und dies mit mobil / iOS zu testen?

**Comment by funky4t** [comment]
ich hab eine 1.0.9 in nem Qnap Container...in 1.0.9 läuft der Homescreen Link, also jedenfalls für iOS. Ich freue mich, dir als Newbie überhaupt helfen zu können und der Adapter ist super und zum Laufen kriegen wir den auch! ;)))

**Comment by CreatsheR** [comment]
Also bei mir lief es unter 1.0.9 und iOS 14 nur "halb". Wenn ich es länger nicht geöffnet hatte, kam beim erneuten Öffnen ein Web-Socket Error

**Comment by funky4t** [comment]
> Also bei mir lief es unter 1.0.9 und iOS 14 nur "halb". Wenn ich es länger nicht geöffnet hatte, kam beim erneuten Öffnen ein Web-Socket Error

Wenn ich mich genau erinnere war es bei mir ähnlich. Wenn "die App/der Link" im Hintergrund war, wurde bei mir beim erneuten Aufruf nur ein weißer Bildschirm geladen. Dann musste ich das Ganze mit Doppelklick aus der App Übersicht beenden und komplett neu starten. Hab es grad auch nochmal im Container geprüft... Aber in jedem Fall funktionierte der Homescreen Link dann nach dem vollständigen Schließen wieder.

**Comment by Zefau** [comment]
Schaut euch mal bitte `v1.1.0-beta.81` an.

**Comment by funky4t** [comment]
Sorry...nach rund 30s wechselt der Screen mit .81 von schwarz über weiß und grau auf den roten Fehlerbildschirm. Hab die Instanz auch mal neu gestartet, ändert nix. Aber wie geschrieben, es dauert jetzt deutlich länger bis zur Fehlermeldung....also irgendwas ist "anders"... 
![image](https://user-images.githubusercontent.com/57875762/98417125-ae78ff00-2080-11eb-9624-78ec7d5fbbe8.png)

**Comment by Zefau** [comment]
Please try `v1.1.0-beta.86`. Thanks for your support guys.

**Comment by skue-hash** [comment]
funktioniert!! thx :)

**Comment by Zefau** [comment]
@skue-hash siehe https://github.com/Zefau/ioBroker.jarvis/issues/323. Meinst du das?

**Comment by Zefau** [comment]
@skue-hash nochmal eine Nachfrage hierzu: Du bestätigst, dass es auf iOS funktioniert, richtig? Oder hast du ein anderes Gerät im Einsatz?

**Comment by skue-hash** [comment]
zum Shortcut:

ja auf iOS funktiniert es, gerade beim IPhone11 und iPhone 10 getestet. andere Geräte habe ich leider nicht.

zum Adapterwidget, was soll ich sagen funktioniert aufeinmal :)). 

vielen Dank und ein großes Lob von mir

**Comment by CreatsheR** [comment]
Es funktioniert zumindest bei mir wieder nur "halb":

![B3F2FAD5-78D6-45C8-AB03-F0E4614129A4](https://user-images.githubusercontent.com/72187841/98449479-4552c380-2134-11eb-92be-e76ddc7ff65b.png)

Die Meldung kommt, wenn die Seite länger im Hintergrund war.

**Comment by Zefau** [comment]
Ist aber ein anderer Fehler, wofür es auch ein eigenes Issue gibt, siehe https://github.com/Zefau/ioBroker.jarvis/issues/295

**Comment by CreatsheR** [comment]
Den hab ich gar nicht wahrgenommen. Sorry 🤦‍♂️

**Comment by funky4t** [comment]
Kann auch bestätigen, Beta88 und der Homescreenshortcut rennt wieder auf iOS14.
Top Danke! :)

**Comment by Herginator** [comment]
Hallo,
ich habe genau das oben beschriebene Problem mit dem Fehler "websocket error", sobald ich unter iOS (iPhone 12) die Seite (auch gesichert im Homescreen) nochmals öffne. Nach ca. 10 sek. lädt es dann neu, aber anfangs kommt immer diese Meldung.
Habe ich irgendeine Einstellung übersehen?

![image](https://user-images.githubusercontent.com/76481999/102893178-6744a300-4461-11eb-8ba4-06582148c6f6.png)

**Comment by CreatsheR** [comment]
Nein, der Reload nach 10 sek ist die "Lösung" für das Problem des Web-Socket-Abrisses

**Comment by Zefau** [comment]
> Nein, der Reload nach 10 sek ist mWn. die "Lösung" für das Problem des Web-Socket-Abrisses

Korrekt. Ist der letzte Ausweg den jarvis zieht, wenn keine Verbindung mehr aufgebaut werden kann.

**Comment by Herginator** [comment]
Heißt das, aktuell gibt es keine Lösung für das Problem? Anfang Nov. hieß es doch, das wäre nun gefixed?
Ich finde diese Visualisierung sehr toll gemacht, wenn ich jedoch jedesmal auf dem Handy/Ipad so lange warten muss, bis der screen neu geladen wird, dann wäre das schon schade.

**Comment by Zefau** [comment]
Ich kann nochmal schauen, aber habe bereits viel Zeit in diese Thematik investiert und die Erfolge halten sich leider in Grenzen.

**Comment by CreatsheR** [comment]
Nach meinem Verständnis lässt sich da nicht viel machen, außer vielleicht die Zeit bis zum Reload konfigurierbar zu machen. Da Apple alles im Hintergrund mehr oder minder direkt in "Tiefschlaf" versetzt reißt die Verbindung unumgänglich ab. Da Jarvis "nur" eine WebApp ist, kann die meines Wissens nach nicht angreifen, ob es in den Hintergrund gesetzt oder daraus hervor geholt wurde.

**Comment by Zefau** [comment]
Wie verhält sich denn ioBroker.vis bei euch in diesem Zusammenhang?

**Comment by CreatsheR** [comment]
Kann ich nichts zu sagen, da ich das nie verwendet habe und auf dem Handy auch nicht verwenden würde. 

Aber Gegenfrage: Wie ist denn die Server-Client-Architektur von Jarvis? Wäre es möglich ne App gegen den WebSocket zu verbinden?

**Comment by Zefau** [comment]
jarvis als Client verbindet sich via socket.io mit ioBroker.web oder ioBroker.socketio. socket.io nutzt WebSocket oder Polling, je nachdem, was zur Verfügung steht. Die Auswahl passiert automatisch.

Von der Architektur her funktioniert auch ioBroker.vis auf diese Art. Im Zweifel unterscheidet es sich aber in Details.

**Comment by Zefau** [comment]
mit der nächsten beta habe ich die Reload-Zeit von 10s auf 3s reduziert.

**Comment by uneart** [comment]
Super, danke @Zefau !
Eine Alternative wäre noch, für Android und iOS eine eigene Wrapper App zu bauen, die das Handling übernimmt. So macht es VIS soweit ich es verstehe, auch.

**Comment by Zefau** [comment]
@uneart siehe https://github.com/Zefau/ioBroker.jarvis/issues/138

**Comment by Zefau** [comment]
@ninja-warrior @uneart @Herginator @cryptedx die Neuverbindung des Sockets sollte nun mit `v2.2.0-beta.29` ohne Neuladen von jarvis klappen. Könntet ihr das bitte testen und bestätigen?

**Comment by WW1983** [comment]
Ich es wie folgt getestet: 
Ich habe die auf dem iPhone und auf dem Tablet aufgerufen. Habe dann auf dem iPhone das WLAN getrennt und neu verbunden. Die App zeigt zwar die JARVIS Oberfläche unverändert. Allerdings funktioniert JARVIS nicht. Sprich es werden keine Änderungen angezeigt und ich kann auch keine Lichter schalten.

**Comment by hacki11** [comment]
Kann ich bestätigen, passiert bei mir auch ohne das wlan zu verlassen. iOS wird die "App" killen wenn die es möchte und man muss selbst feststellen ob man gekillt wurde. Vielleicht relevant https://stackoverflow.com/questions/10336135/ios-added-to-home-screen-website-wont-refresh

**Comment by ninja-warrior** [comment]
Bei mir ist der Fehler nicht mehr aufgetreten. Zur Hygiene der Issues würde ich diesen Bug damit schließen.
