### ISSUE TITLE
Support import of devices from ioBroker.tasmota adapter

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#299]

**Comment by Timmes123** [comment]
du meinst vermutlich den sonoff adapter oder?

**Comment by Zefau** [comment]
haha, ja, hast recht. Ich lese nur immer wieder, dass die Leute vom Tasmota schreiben. Aber scheinen einfach geflashte Sonoff's zu sein?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/79

**Comment by Timmes123** [comment]
tasmota ist ne eigene firmware, welche man auf viele geräte packen kann, z.b. tuya, gosund, sonoff und noch viele andere. eigentlich alle geräte die den ESP8266 eingebaut haben. 
tasmota baut (meistens) per mqtt ne verbindung zum iobroker auf, welches der sonoff adapter ja zur verfügung stellt 

ansicht ist abhängig vom gerät (glaub ich)

![image](https://user-images.githubusercontent.com/73311538/97920491-d2bf9d80-1d59-11eb-8cb2-83ddde9fba5f.png)
![image](https://user-images.githubusercontent.com/73311538/97920521-dd7a3280-1d59-11eb-93f9-57a88dc4c011.png)

**Comment by Timmes123** [comment]
hier ein kurzer ausschnitt einer sehr langen liste
und was da nicht drin steht, kann händisch konfiguriert werden 

![image](https://user-images.githubusercontent.com/73311538/97920919-7ad56680-1d5a-11eb-940f-2dba9738bdb9.png)

**Comment by Zefau** [comment]
Ist denn die Datenstruktur im Adapter einigermaßen einheitlich?
