### ISSUE TITLE
Please add you adapter to our repository

### ISSUE THREAD

**Issue by ioBrokerChecker** [Zefau/ioBroker.jarvis#3]
We saw your adapter and if it is ready please request that it is added to the repository. With this it becomes available for all users. Please consult https://github.com/ioBroker/ioBroker.repositories#add-a-new-adapter-to-the-latest-repository and the following sections for more details.
If you need help, contact us in the forum https://forum.iobroker.net/ or in the developer chat https://github.com/iobroker-community-adapters/info .

Thank you for your support.

**Comment by Zefau** [comment]
https://github.com/ioBroker/ioBroker.repositories/pull/681

**Comment by Zefau** [comment]
duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/2
