### ISSUE TITLE
Integration of Multiroom Audio Devices

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#300]
Sorry for the next new idea, but your adapter is so fantastic, I always think about new ideas to visualise in my personal Jarvis.

First step could be the integration of a very simple Player visualisation with play/pause/skip options and maybe a cover section. I'm thinking of a simple interface for controlling services like Sonos, TuneIn, Amazon Music etc... Datapoints are coming manually from different adapters and have to be assigned by the user.

2nd step or even a Pro-Feature could be a more detailed player with library search or playlist function using datastructure of common brands as Sonos, Bose, Yamaha or so... I guess Step 2 is quite hard in programming compared to Step 1.

Any testing support needed, let me know ;)

**Comment by Zefau** [comment]
Is on the agenda https://github.com/Zefau/ioBroker.jarvis/issues/173 :)
