### ISSUE TITLE
DisplayImage not working

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#302]
Current Beta

![image](https://user-images.githubusercontent.com/25475385/97962606-d8e36780-1db5-11eb-9f11-135b1dcae844.png)
![image](https://user-images.githubusercontent.com/25475385/97962633-e567c000-1db5-11eb-9257-8e64cbb698d1.png)

**Comment by Zefau** [comment]
Has this been working in earlier versions? You are using jarvis on `https` and trying to load a `http` resource. This is not working by browser design as state in the warning.

**Comment by Zefau** [comment]
https://blog.chromium.org/2019/10/no-more-mixed-messages-about-https.html

**Comment by Zefau** [comment]
Can you confirm this behavior with Firefox?

**Comment by Zefau** [comment]
For Chrome please also see https://superuser.com/a/881431

**Comment by duczz** [comment]
kopier ich den Link von Jarvis in Chrome (manueller test) geht es aber

**Comment by Zefau** [comment]
Ja, natürlich, da es ein direkter Zugriff ist.

Es geht bei der Warnung darum, dass unsichere http Inhalte in einer sicheren https Seite geladen werden. Das ist beim direkten Aufruf ja nicht der Fall.

Das ist kein jarvis spezifischer Sachverhalt, sondern von Chrome.

Wie verhält sich hier ein anderer deiner Browser? 

Was passiert bei ioBroker.vis? Läuft das überhaupt auf https?

**Comment by duczz** [comment]
achso meinst es, ja das Zertifikat muss man bestätigen da nicht vertrauenswürdig.
Kann man in Jarvis vertrauenswürdige Sites hinterlegen ohne sie an allen entgeräte einzeln zu hinterlegen? Schaffst du da evtl eine übergabe zum browser?

**Comment by Zefau** [comment]
Wüsste nicht, dass das technisch geht. Hattest du das Problem in vis nicht ? Wenn es dort funktioniert, würde ich mir das nochmal anschauen / abgucken.

**Comment by duczz** [comment]
Ich glaub ich hatte das in der Vis auch, habs dort aber nicht so häufig genutzt, dann mach ich das einfach manuell in die trusted sites rein - danke
