### ISSUE TITLE
Namen

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#303]
Seit der aktuellen Beta werden die State Namen vom Device + Layout zusammen angezeigt, wo kann man das wieder umstellen?
Devicename (Layoutname)

![image](https://user-images.githubusercontent.com/25475385/97963264-14cafc80-1db7-11eb-93c5-f1674cc2ebc6.png)

**Comment by Zefau** [comment]
Actually not a bug, because I added it on purpose. But it sucks so I removed it now in `v1.1.0-beta.74`.

**Comment by duczz** [comment]
Namen sind weg, jedoch werden nun die Device Bezeichner als namen angezeigt und nicht die hinterlegten label, wo wir wieder bei dem issue wären https://github.com/Zefau/ioBroker.jarvis/issues/217

![image](https://user-images.githubusercontent.com/25475385/98077544-bf532600-1e70-11eb-9057-08d2a7f75a16.png)
![image](https://user-images.githubusercontent.com/25475385/98077583-d09c3280-1e70-11eb-91f5-2932eb837736.png)
![image](https://user-images.githubusercontent.com/25475385/98077601-d7c34080-1e70-11eb-9310-4b21a59e0d1c.png)

**Comment by Zefau** [comment]
Aus meiner Sicht kein Bug.

Du guckst im Widget. Dort greift das Label das du in der Widget Konfiguration definierst. Ist dort keines hingelegt, greift der Geräte Name.

Das Geräte label greift in den Geräte Details (Popup).

**Comment by duczz** [comment]
Okay, ich verstehe, dann liegt das Problem daran das ich eine Gruppe definiert habe, und dort mehrere Geräte hinterlegt habe.
Ich wollte in Jarvis nie jedes Gerät ohne passender Zuweisung bzw namentlicher erkennung eintragen daraus entstanden dann Geräte welche ich als gruppen nutze, hmm das ist doof gelaufen

**Comment by Zefau** [comment]
Hatte es heute tagsüber nur auf mobil gesehen, jetzt nochmal richtig geschaut. Es ist ein Bug, aber ein duplicated zu https://github.com/Zefau/ioBroker.jarvis/issues/217.
