### ISSUE TITLE
JARVIS hinter Reverse Proxy

### ISSUE THREAD

**Issue by KoMa1978** [Zefau/ioBroker.jarvis#304]
Hallo,

Ich nutze iobroker hinter einem nginx Reverse Proxy.

Alle Anfragen an "iobroker.domain.de" werden dann vom nginx an 127.0.0.1:8082 weitergeleitet.
Das funktioniert soweit wunderbar. JARVIS nutzt auch den Hostnamen, versucht aber scheinbar immer direkt auf die Ports 8082 oder 8084 zu verbinden.

Ich erhalte daraufhin nach einem Aufruf von "https://iobroker.domain.de/jarvis" den roten Bildschirm mit "Connection failed".

Chrome meldet folgenden Fehler:
polling-xhr.js:268 Mixed Content: The page at 'https://iobroker.domain.de/jarvis/' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://iobroker.domain.de:8082/socket.io/?ws=true&EIO=3&transport=polling&t=NMDpmIX'. This request has been blocked; the content must be served over HTTPS.

Besten Dank,

**Comment by Zefau** [comment]
Please try appending `#socketPort=0000` to your url to change and customize your port

**Comment by KoMa1978** [comment]
Hi Zefau,

thats not working but https://iobroker.domain.de/jarvis/index.html#socketPort=443&socketSecure=true is working.

Maybe you can add something like a configuration setting for the port or first try the port the connect is established to ...

Marco

**Comment by Zefau** [comment]
5 options are tested:
1. the URL jarvis is opened with
2. the URL jarvis is opened with replacing the port with 8082
3. #2 with https
4. the URL jarvis is opened with replacing the port with 8084
5. #4 with https

What additional option are you suggesting?

**Comment by KoMa1978** [comment]
In my case it Is #1 with HTTPS but this is not working unless I add the socket option and the Secure Option. 

Is #1 supported with HTTPS?

**Comment by Zefau** [comment]
#1 is `window.location.href`, so the whole URL including everything. 

Could you try `v1.1.0-beta.74`? I changed it to `window.location.href.substr(0, window.location.href.indexOf('/', 8))` (which is cutting off the path at the end).

**Comment by KoMa1978** [comment]
Hmm how do I install it?
I installed this one (1.0.9) from iobroker UI.
Or is there maybe a file where I can change this in the installed version to verify if it helps?

**Comment by Zefau** [comment]
via the cat in the ioBroker ui you need to type in the Github repo URL `https://github.com/Zefau/ioBroker.jarvis`.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/316#issuecomment-722685196
> 10.10.0.1 is the IP of the docker host which maps it's own (real or external) ports to ports inside the container. I'd give 8082 and 8084 other external ports like 28082 and 28084 if I could specify them somewhere in configuration.

You may use following parameters in the URL:

Parameter | Bedeutung
-- | --
socketHost | Socket Host, zu dem verbunden werden soll, i.d.R ioBroker IP.
socketPort | Socket Port, zu dem verbunden werden soll. In der Regel 8082 beim Einsatz des integrierten Sockets des Web-Adapters oder 8084 im Falle der Nutzung des socket.io Adapters.
socketSecure | Socket Transportverschlüsselung, die genutzt werden soll: false für http:// oder true für https://.
debug | Aktiviert das ausführliche Development-Debugging in der Browser-Konsole.

**Comment by zech** [comment]
> You may use following parameters in the URL:
> 
> Parameter	Bedeutung
> `socketHost`	Socket Host, zu dem verbunden werden soll, i.d.R ioBroker IP.
> `socketPort`	Socket Port, zu dem verbunden werden soll. In der Regel `8082` beim Einsatz des integrierten Sockets des Web-Adapters oder `8084` im Falle der Nutzung des socket.io Adapters.
> `socketSecure`	Socket Transportverschlüsselung, die genutzt werden soll: `false` für `http://` oder `true` für `https://`.
> `debug`	Aktiviert das ausführliche Development-Debugging in der Browser-Konsole.

Danke werde ich versuchen. :-)
Eine Möglichkeit das statisch zu Konfigurieren gibt es nicht? Oder ist ggf. geplant?

**Comment by Zefau** [comment]
Statisch in der ioBroker Adapter-Konfiguration selbst meinst du? Das würde gehen. Bringt aber nur den Vorteil, dass die oben genannten Optionen dem Link hinzugefügt werden.

In jarvis direkt geht das nicht, da ich eine Verbindung brauche, um Daten zu laden und diese Optionen ja für die Verbindung nötig sind.

**Comment by zech** [comment]
> Statisch in der ioBroker Adapter-Konfiguration selbst meinst du?

Ganz genau. Für Personen die mehr als einen Jarvis-Adapter benötigen natürlich ggf. je Adapter.

> Das würde gehen. Bringt aber nur den Vorteil, dass die oben genannten Optionen dem Link hinzugefügt werden.

Genau. Den Link nutze ich bei mir ja und jetzt wird halt einfach im Standard 8082 hinzugefügt was der interne Port im Container ist. Tatsächlich brauche ich in meinem Fall aber 18082, so dass die IP eben so aussieht:

`http://<docker-host-ip>:18082/jarvis/index.html#instance=0&socketPort=18082`

Es könnte auch zu folgendem werden je nachdem was gesetzt wurde:

`http://<docker-host-ip>:18082/jarvis/index.html#instance=0&socketHost=<docker-host-ip>&socketPort=18082`

Aber diese IPs sind bei mir ja identisch. In Containern braucht man ja eig. selten die Container-IP selbst. Nur die Host-IP.

> In jarvis direkt geht das nicht, da ich eine Verbindung brauche, um Daten zu laden und diese Optionen ja für die Verbindung nötig sind.

Richtig. Müsste schon direkt im Adapter erfolgen. Oder sonst eine übergeordnete Konfiguration.

**Comment by KoMa1978** [comment]
Ich nutze Docker nicht, aber das weiterleiten an die Docker-Instanz macht doch dann Docker ...

Am entspanntesten wäre es doch, wenn die Daten direkt über den Weg (IP und Port und Methode (SSL oder Plain)) erfolgen würde, über den auch die Seite aufgerufen wurde.

So wie du es unten schon beschrieben hattest, die Option "1":

> 1. the URL jarvis is opened with

und zwar die URL mit dem Port, der genutzt wird. wenn http dann "plain", wenn https dann "secure" und wenn ein Port dahinter steht, dann über den Port, sonst 80 oder 443.

Dann zickt auch eine Firewall zwischen Client und iobroker nicht.

**Comment by Zefau** [comment]
@zech Habe mit `v1.1.0-beta.95` Optionen für Socket Host und IP in den Adapter-Einstellungen hinzugefügt.

**Comment by zech** [comment]
Danke für die Optionen. Ich dachte dieser Link:

![image](https://user-images.githubusercontent.com/460040/98871485-486feb80-2475-11eb-9abe-1a16fa6dac76.png)

würde sich dadurch ebenfalls anpassen.

Aber geöffnet wird immer noch mit

`http://10.10.0.1:8082/jarvis/index.html#instance=0&socketHost=10.10.0.1&socketPort=8082`

![image](https://user-images.githubusercontent.com/460040/98871650-91c03b00-2475-11eb-8913-e63902814517.png)

Ich vermute der Port wird nicht persistiert. Nach speichern und danach `Ctrl + Shift + R` steht hier leider noch der alte Port drin mit `8082`

**Comment by Zefau** [comment]
@zech probier bitte nochmal mit `v1.1.0-beta.100`.

**Comment by zech** [comment]
@Zefau danke ich merke keine unterschied, außer der weiteren Option.

Muss eine neue Instanz anlegen? Die Bestehende lässt sich nicht konfigurieren.

**Comment by Zefau** [comment]
Wenn du den Web Port bearbeitest, sollte die öffnende URL um diesen angepasst werden.

**Comment by zech** [comment]
Ja das war meine Erwartung. Ich trage in die Felder die Ports ein, Speichere, Schließe und öffne die Einstellungen erneut. Dann steht wieder 8082 drin.

**Comment by Zefau** [comment]
Bei mir ging's, aber ich schaue mir das morgen dann nochmal an.

**Comment by zech** [comment]
@Zefau Ich will nicht ausschließen, dass ich irgendeinen schiefstand habe. Fällt Dir irgendwas ein, nachdem ich mich umsehen könnte? Also wieso das nicht gespeichert wird?

**Comment by Zefau** [comment]
Die Checkbox hast du auch drin und Haken ist nicht gesetzt?

**Comment by Zefau** [comment]
@zech Er hat nicht alles ins Repo übernommen. Versuch nochmal die `v1.1.0-beta.102` bitte.

**Comment by zech** [comment]
Sorry für die späte Rückmeldung.

Es funktioniert teilweise. Vorgehen:

1. Portnr. Eintragen (in meinem Fall 18082)
2. Save & Close
3. Link klicken bevor Instanz grün wird
=> Funktioniert

4. Link nochmal klicken nachdem Instanz grün.
=> Funktioniert nicht mehr

Link öffnet mit 8082

Kontrolliere ich die Einstellungen ist der Port auch wieder auf 8082 zurückgesetzt.

**Comment by Zefau** [comment]
So sieht / funktioniert es bei mir:

![jarvis](https://user-images.githubusercontent.com/14368811/99440195-7c845a00-2916-11eb-91cd-709c8aae509c.gif)

**Comment by Zefau** [comment]
@zech Kannst du nochmal auf die letzte beta gehen und den Adapter ggf. nochmal bewusst selbst uploaden?

**Comment by zech** [comment]
> nochmal bewusst selbst uploaden?

Hi, bevor ich anfange was meinst du mit uploaden? Updaten? Löschen und neu installieren?

**Comment by Zefau** [comment]
Der Pfeil nach oben:
![image](https://user-images.githubusercontent.com/14368811/99445342-b86eed80-291d-11eb-9d0e-3ce4b95f5e1b.png)

**Comment by zech** [comment]
> Der Pfeil nach oben

Danke!

Leider kein Erfolg bei mir. Ich vermute, dass irgendetwas anderes nicht stimmt.

![jarvis_01](https://user-images.githubusercontent.com/460040/99450697-6334db00-2921-11eb-99cc-22caad037353.gif)

**Comment by Zefau** [comment]
Probier bitte nochmal `v1.1.0-beta.112`.

**Comment by zech** [comment]
Die hat jetzt funktioniert. Danke!
