### ISSUE TITLE
keine icons bei neuinstallation von beta73

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#306]
ich habe gerade auf einem neuen gerät jarvis beta73 direkt installiert.
nun hab ich keine icons bei den geräten

![image](https://user-images.githubusercontent.com/73311538/97988479-553d7100-1ddd-11eb-8bd9-01728f1be912.png)

**Comment by Zefau** [comment]
What does the console log state ?

**Comment by Timmes123** [comment]
liegt das evtl an unserer firmen firewall? 
auf die material designs website komm ich allerdings drauf

![image](https://user-images.githubusercontent.com/73311538/98082896-cc284780-1e79-11eb-8506-d37319dd7e3f.png)

**Comment by Zefau** [comment]
Kann sein. Ich schau mal ob ich das lokal laden kann  in der nächsten beta.

**Comment by Timmes123** [comment]
ich hab grad vom admin die firewall checken lassen, UDP 443 wurde geblockt.
Das ist dieses neue QUIC Protokoll. keine ahnung ob das damit zusammen hängt.
Der Port wurde für mich jetzt mal geöffnet, allerdings geht es trotzdem noch nicht.

lokal fände ich aber generell besser, weil nicht jeder nutzer wird dauerhaft online sein.
Gerade in anderen ländern sind internet ausfälle häufiger, italien z.b.
Wenn deine visu dauerhaft auf eine internet verbindung angewiesen ist, wäre das sowieso nicht die beste wahl

**Comment by Timmes123** [comment]
Mein Laptop (Jarvis Client) versucht allerdings gerade noch über Port 7788 zu kommunizieren. Ich weis nicht ob Jarvis das ist oder was anderes. Das wird aktuell von der Firewall noch geblockt, weil laut definition ist das ein Port für Unreal Tournament. Und ich glaube nicht, dass UT auf meinem Arbeitslaptop installiert ist ^^

**Comment by Timmes123** [comment]
ok 7788 ist es nicht, der wird von acronis und HP verwendet, hat mit dir also nichts zu tun.
Nach meinem ermessen sollte also die verbindung komplett offen sein

**Comment by Timmes123** [comment]
wenn ich bei mir im browser den link aus der konsole öffne, also
http://cdn.materialdesignicons.com/5.8.55/fonts/materialdesignicons-webfont.woff2?v=5.8.55
dann kommt ein download der datei materialdesignicons-webfont.woff2
also scheint das ja schon erreichbar zu sein

**Comment by Zefau** [comment]
Die Ressource wird über Port 80 angeordnet, da Web. Ist der cdn ggf. geblockt? 

Aber wie gesagt, ich zieh es ins package, dann ist es lokal.

**Comment by Timmes123** [comment]
cdn? aber vermutlich nein, da in der firewall aktuell keinerlei deny meldungen mehr stehn von meinem laptop

**Comment by Zefau** [comment]
Prüf' mal bitte `v1.1.0-beta.75`. Damit sind die Icons nun im Package enthalten.

**Comment by Timmes123** [comment]
gestestet und funktioniert :-)
