### ISSUE TITLE
nach Update auf Beta 73 - Connection failed!

### ISSUE THREAD

**Issue by blackluzie** [Zefau/ioBroker.jarvis#307]
nach Update auf Beta 73 - Connection failed!

auf mobilen Browsern - getestet auf iPhone in Safari und Chrome und auf fireOS

Im Chrome auf dem PC funktioniert es.

**Comment by blackluzie** [comment]
gleicher Fehler ist schon gemeldet

**Comment by xCruziX** [comment]
Auf meinem Mi9 leider auch.

![image](https://user-images.githubusercontent.com/59866158/98388664-57a90080-2053-11eb-92fe-de247e6dd5a7.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/297
