### ISSUE TITLE
Gerätekonfiguration: hiddenStates/ignoredStates akzeptiert nur einen state

### ISSUE THREAD

**Issue by Yammi900** [Zefau/ioBroker.jarvis#308]
**Prerequisites**
- [ x] Are you on the latest stable or latest beta of jarvis?

**Versions**
- Which jarvis version are you running: 1.0.9
- Please provide your `Support-ID` (in jarvis via Settings -> Help): ?

**Describe the bug**
Wenn ich versuche mehr als einen **state** bei **hiddenStates** anzugeben, dann wird die Eingabe vollständig ignoriert, d.h. auch die angegebenen **states** werden weiterhin angezeigt. Ursache liegt darin, dass der Inhalt des Eingabefeld für **hiddenStates** nicht korrekt in ein Array konvertiert wird, sondern im Jason als einzelner String gespeichert wird.

Beispiel:
Ich möchte die **states** ACTUAL,HUMIDITY,SET in einer Gerätekonfiguration ausblenden.

Dies wird als 
         _"hiddenStates": [
            "ACTUAL,HUMIDITY,SET"
         ]_
gespeichert. Als Resultat wird nichts ausgeblendet, die **states** werden weiterhin angezeigt. Ändere ich das manuell in
         _"hiddenStates": [
            "ACTUAL",
            "HUMIDITY",
            "SET"
         ]_
funktioniert die Anzeige wie erwartet.  Das Verhalten bei **ignoredStates** ist analog. Da wird also nicht richtig geparst. Speichert man eine geänderte Gerätekonfiguration nach einer Änderung ab, bleibt alles ok solange man die Felder **hiddenStates** und **ignoredStates** nicht anfasst (was vermutlich daran liegt, dass Du nur geänderte Felder neu schreibts, ich wollte es nur der Vollständigkeit halber erwähnen).

Für die Eingabehilfe (das kleine i am Feld) wäre es sinnvoll ein Bespiel zu zeigen, damit auch immer der richtige **delimiter** vom Benutzer angegeben wird (i.R. sind das ja Kommas, andere wollen aber auch mal nur Leerzeichen oder Semikolons).

LG Chris

**Comment by Zefau** [comment]
@Yammi900 Sorry für meine späte Rückmeldung und vielen Dank für das ausführliche Melden des Fehlers!

Mit Blick auf das bevorstehende Release von **v1.1.0** (gegen Ende November / Anfang Dezember) werde ich diesen Fehler nicht mehr beheben.
- `ignoredStates` wird entfernt.
- `hiddenStates` wird mit einem im Datenpunkt spezifischen Switch ersetzt, um gezielter einen Datenpunkt zu verstecken:
   ![image](https://user-images.githubusercontent.com/14368811/99114787-ad505080-25f1-11eb-96ef-5b5f84810133.png)
