### ISSUE TITLE
Where is the code

### ISSUE THREAD

**Issue by redxeagle** [Zefau/ioBroker.jarvis#309]
It feels like that jarvis is a react application, but it is complete hidden here,

Are there any plans that the code will be public? 
Wanted to check also some ways to help here and investigate a little bit. Also based on the amount of issues and feature wished would be great if others could participant.

**Comment by cryptedx** [comment]
Me too. I have also searched for the code but it seams to be closed source...

**Comment by Zefau** [comment]
The react code has its own repository, which is not public.

**Comment by redxeagle** [comment]
Hi Zefau, can you make it public? ;)

Any reason behind having it secret? 
"Asking for a friend" :-)

I really like Jarvis and it's awesome that you, I guess, developed this project yourself alone. 
Switched some days before from Pimatic to ioBroker now and Jarvis is currently from the look and feel quite familiar. 
Also why I am asking is that I always choose the Home Automation project based on a common programming language I want to get better with, so here I am, here I am asking. :-)

Also tried yesterday a little bit to reverse engineer the behavior of how Jarvis get the data to find out why the Graph part does not work for me, but for a friend (we are using both Influxes as persistence adapter, but for me, the GetHistory WS messages are now answered for some reason. For that I will open another issue soon. :-)

**Comment by daolis** [comment]
Hi Zefau,

I also really like jarvis, and it would be really cool if you could make it public.

I think there are a lot of developers with a few free resources and ideas out there to contribute to this project. ;-)

**Comment by menkej** [comment]
Hi @Zefau !
I started playing around with Jarvis this weekend. Pretty nice!

Unfortunately some of my (homematic IP wired) devices seem not to be supported. I wanted to add them myself and submit a pull request but ran into this issue: no code. So how can I support adding

- HmIPW-SPI
- HmIPW-DRS4
- HmIPW-DRS8
- HmIPW-DRD3
- HmIPW-DRBL4
- HmIPW-DRI32
- HmIPW-SMI55
- HmIPW-DRAP
- ...

? Or don't you want help on this project?

cheers
Jörg
