### ISSUE TITLE
Possibility to add "Gewerk" or modify/extend defaults

### ISSUE THREAD

**Issue by CC1337** [Zefau/ioBroker.jarvis#310]
iGude, 

I am curently setting up a vis using jarvis and I really like the concept of default action/view options configured by the device type / "Gewerk". However, I'd like to extend defaults or add new ones - not sure if there is any option for it (or planned).
Use cases: 
- minor: For all data points called "reachable" use state depending wifi icon (instead of copy pasting into each device as custom config)
- major: configure/map actions triggered by the datapoint name to on/off, 0-100% etc. As a sample I have a blind and would like to have an additional datapoint to toggle on/off. Or I have a light where I could use three 0-100% bars for 3 sub devices - but currently if I _misuse_ "level" and "dimmer" name I can get max 2.
![grafik](https://user-images.githubusercontent.com/4866744/98155144-13dcbc80-1ed6-11eb-929a-073e3ac54d15.png)

Sample 1 would only reduce manual effort while request 2 will add a ton of possibilities for compact dahsboards with a lot of possibilities in the modal.

I possibly could also support with PRs.
As first step editing plain JSON might be enough instead of a UI.

Best,
CC

**Comment by Zefau** [comment]
Your first request is covered by https://github.com/Zefau/ioBroker.jarvis/issues/188.

Your second request is already possible in the beta. Which version are you on? 
Via https://github.com/Zefau/ioBroker.jarvis/issues/40 the body and action elements are supported in the device details (popup).

**Comment by CC1337** [comment]
wow cool, I am on the release 1.0.9 installed from the adapter list... so I should install via github from master, or what to pick?

**Comment by Zefau** [comment]
Install via the cat and the Github repository URL or wait for the "official" release end of November (hopefully).
