### ISSUE TITLE
Reformatting/rounding values to show - e.g. lambda function in device config

### ISSUE THREAD

**Issue by CC1337** [Zefau/ioBroker.jarvis#312]
As seen in the samples for displaying the unit depending on value in the wiki, maybe lambda functions could be handy to reformat the value to display? 
Such as `val => val..toFixed(1)`
If it's not intended, of course it's solvable by first creating custom data points by a script doing the preprocessing as well...

**Comment by schweigel** [comment]
Hi,

in an other visualisation [numeral.js](http://numeraljs.com) is used to format numbers.
I would like to see this feature here.

Matthias

**Comment by Zefau** [comment]
will be done through https://github.com/Zefau/ioBroker.jarvis/issues/416

**Comment by Zefau** [comment]
implemented through `v2.2.0-beta.46`, please see https://github.com/Zefau/ioBroker.jarvis/issues/416
