### ISSUE TITLE
Wie kann ich Geräte und Layout direkt editieren

### ISSUE THREAD

**Issue by cryptedx** [Zefau/ioBroker.jarvis#313]
Hallo,

ich möchte gerne Geräte und Layout direkt per SSH und VSCODE editieren können. Wo sind die Dateien gespeichert?

![image](https://user-images.githubusercontent.com/20707078/98254265-607ad300-1f7c-11eb-8148-0cf3b02bab06.png)

Grüße
crypted

**Comment by Zefau** [comment]
Everything is saved in `jarvis.0.devices`, `jarvis.0.layout` and `jarvis.0.settings`.

**Comment by cryptedx** [comment]
Sorry but I am too dumb to find the root folder with this files! I tried a search over the whole filesystem. Can you tell me the path please?

**Comment by Zefau** [comment]
Sorry for the confusion. Those I listed are states in ioBroker. Jarvis does not store anything in files.

**Comment by cryptedx** [comment]
OK then #98 is the way to go. Thanks anyway.

**Comment by cryptedx** [comment]
> Everything is saved in `jarvis.0.devices`, `jarvis.0.layout` and `jarvis.0.settings`.

Where are these files placed? I have to restore them form a backup.

Thanks.
