### ISSUE TITLE
"Turn on" button not localized and alkso shown when already on in 1.1.0-beta76

### ISSUE THREAD

**Issue by CC1337** [Zefau/ioBroker.jarvis#314]
Ip updated from 1.0.0 to latest beta 1.1.0-beta76 and the button "ANSCHALTEN" which was used to turn on a variable is now behaving different.
- It is English although UI language is DE:
![grafik](https://user-images.githubusercontent.com/4866744/98280899-5c5ead80-1f9c-11eb-886e-d3b2a021e0c1.png)
- When using one state (of the plug) to display and as action a trigger to enable it read by some scripts (to prevent it from switching it off), before it was shown as "An" instead of the button if the first state was true. Now the button stays "TURN ON" even if it's on already.

In the config dropdown of the action element it is still in German.

**Comment by Zefau** [comment]
Fixed with `v1.1.0-beta.82`.

**Comment by CC1337** [comment]
Now in .82 it looks like 
![grafik](https://user-images.githubusercontent.com/4866744/98421436-9fe31580-2089-11eb-868c-9fc7284eac9c.png)

I wonder how it should be in which state combination.
Previously it was:
deconz.0.Lights.2.on = false -> Button "Anschalten" triggering true on javascript.0.data.1OG.Büro.PCStateTrigger
deconz.0.Lights.2.on = true-> green text "An"

That was perfect for my needs but maybe not as wou wanted to implement it :D

Config:
```
"1ogbürosteckdosepc_25601": {
      "id": "1ogbürosteckdosepc_25601",
      "name": "1OG Büro Steckdose PC",
      "function": "other",
      "states": {
         "power": {
            "state": {
               "node": "deconz.0.Lights.2.on"
            },
            "action": "javascript.0.data.1OG.Büro.PCStateTrigger",
            "icon": {
               "true": "desktop-mac-dashboard",
               "false": "desktop-mac"
            },
            "actionElement": "ButtonAction",
            "label": "PC",
            "display": {
               "default": "Anschalten"
            }
         },
         "watt": {
            "state": {
               "node": "deconz.0.Sensors.3.power"
            },
            "label": "Verbrauch",
            "unit": "W",
            "icon": {
               "default": "transmission-tower"
            }
         },
         "powerCounter": {
            "state": {
               "node": "deconz.0.Sensors.2.consumption"
            },
            "unit": "Wh",
            "label": "Summe",
            "icon": {
               "default": "sigma"
            }
         },
         "voltage": {
            "label": "Spannung",
            "state": {
               "node": "deconz.0.Sensors.3.voltage"
            },
            "unit": "V",
            "icon": {
               "default": "lightning-bolt"
            }
         },
         "reachable": {
            "state": {
               "node": "deconz.0.Sensors.2.reachable"
            },
            "display": {
               "true": "ja",
               "false": "nein"
            },
            "label": "Erreichbar",
            "icon": {
               "true": "wifi",
               "false": "wifi-alert"
            }
         }
      },
      "options": {
         "hiddenStates": []
      },
      "attributes": {
         "imported": true,
         "manufacturer": {
            "name": "Deconz",
            "namespace": "deconz"
         },
         "_updated": 1604702459642
      }
   },
```

**Comment by Zefau** [comment]
Could you verify this again with `v1.1.0-beta.94` ?

**Comment by CC1337** [comment]
Can you explain what the config values should do so I don't misunderstand what happens?
![grafik](https://user-images.githubusercontent.com/4866744/98740081-c3200480-23aa-11eb-8945-85b1cb152d0f.png)
Because now the label is taken, but the "power" icon is gone and overridden by the datapoint's icon:
![grafik](https://user-images.githubusercontent.com/4866744/98740138-de8b0f80-23aa-11eb-9b5d-5669f458add6.png)
And the button is shown although deconz.0.lights.2.on is true. But maybe this is wanted? I'd like more if it would be hidden in this case as it was in 1.0.9 but that's not a very big wish :) and maybe it is possible if I would configure it correctly?

**Comment by Zefau** [comment]
@CC1337 has this all been resolved as expected ?
