### ISSUE TITLE
"Hilfe" button is going away when "Expertenmodus" has been activated

### ISSUE THREAD

**Issue by cryptedx** [Zefau/ioBroker.jarvis#315]
![image](https://user-images.githubusercontent.com/20707078/98285588-0c371980-1fa3-11eb-8c21-d4cef7fb5ab8.png)

![image](https://user-images.githubusercontent.com/20707078/98285636-21ac4380-1fa3-11eb-985f-a11fdb4c8193.png)

This will be an easy one ;-)

**Comment by Zefau** [comment]
Fixed with `v1.1.0-beta.82`.

**Comment by cryptedx** [comment]
fixed!
