### ISSUE TITLE
Color Chart all the same colors

### ISSUE THREAD

**Issue by cryptedx** [Zefau/ioBroker.jarvis#317]
beta 79
------------

Hi,

I haven't found an actual bug report regarding "Chart Line Color". When I set them all to different ones then it will stay at one color. 

![image](https://user-images.githubusercontent.com/20707078/98354706-61197500-2021-11eb-8313-6316eabbf624.png)

![image](https://user-images.githubusercontent.com/20707078/98354918-b190d280-2021-11eb-8b4e-193af69872de.png)

Even when I set it back to auto it will stay at one color. With auto set it's now grey:

![image](https://user-images.githubusercontent.com/20707078/98355060-ed2b9c80-2021-11eb-89e8-786e3a2e1638.png)

Values are comming from the same device:

![image](https://user-images.githubusercontent.com/20707078/98356056-4ea03b00-2023-11eb-85d4-57e8a3e59f1f.png)

**Comment by cryptedx** [comment]
Also if I hover over one date point then all chart-line data points will be highlighted. 

![image](https://user-images.githubusercontent.com/20707078/98356414-d7b77200-2023-11eb-8119-df035ba8214d.png)

There is also another weird behaviour. Highlighting is different with some data points:

![Nov-06-2020 11-43-45](https://user-images.githubusercontent.com/20707078/98357398-6ed0f980-2025-11eb-9b40-6da84ff9e072.gif)

**Don't be surprised that one chart line is missing. There is no data there yet.**

**Comment by Zefau** [comment]
Should be resolved with `v1.1.0-beta.81`.

**Comment by cryptedx** [comment]
It is, just the firstly created chat hasn't been fixed:

![image](https://user-images.githubusercontent.com/20707078/98461307-6276a900-21ab-11eb-9cf9-e923540a0acb.png)

**Comment by Zefau** [comment]
Why did you close it? Does the first chart work now?

**Comment by cryptedx** [comment]
I have set my colors and it is working. This problem shouldn't appear anymore, because you fixed it? That's why i closed it.

Now I have checked what will happen when I set it to "auto" at the first chart. It's like in the screenshot above. Only grey. Let's reopen it! I have also tested the lower one. Same behaviour. "auto" is not working?

![image](https://user-images.githubusercontent.com/20707078/98462424-b0dc7580-21b4-11eb-97af-a64a60bcb9a3.png)

**Comment by Zefau** [comment]
I can confirm - it does work for me either. Is supposed to work though.

**Comment by Zefau** [comment]
Resolved with `v1.1.0-beta.89`.

**Comment by cryptedx** [comment]
FIXED!
