### ISSUE TITLE
Button 'Speichern und schließen' für die Einstellungen

### ISSUE THREAD

**Issue by Yammi900** [Zefau/ioBroker.jarvis#318]
Könntest Du bitte Button "Speichern" in "Speichern und schließen" ändern und dem Einstellungsdialog einen Button "Speichern" hinzufügen, der nur die aktuellen Änderungen speichert ohne den Dialog zu schließen. Wenn ich mehrere Änderungen am Stück durchführe würde ich gerne zwischenspeichern können, ohne jedes mal rauszufliegen und die Dialog neu starten zu müssen. Das wäre eine echte Arbeitserleichterung.

LG Chris

**Comment by Zefau** [comment]
added with `v1.1.0-beta.89`.

**Comment by cryptedx** [comment]
Super Idee!! Jetzt kann ich einen weiteren Tab mit Jarvis offen haben und die Änderungen gleich direkt ansehen, ohne komplett rausgehen zu müssen.
