### ISSUE TITLE
add new module JsonTable

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#320]
- [x] visualize a JSON structure to a HTML table.
- [x] ~~read HTML tables from state and convert to jarvis HTML table (design-wise)~~ done via https://github.com/Zefau/ioBroker.jarvis/issues/676
- [x] ~~convert arrays to HTML table~~ done via https://github.com/Zefau/ioBroker.jarvis/issues/676

**Comment by SevenUp666** [comment]
@Zefau kannst du schon eine ganz vorsichtige und unverbindliche Aussage machen, wann JSON für Tabellen möglich sein wird?
Ich möchte gerne in Jarvis einen oder mehrere Auszüge aus dem Log  anzeigen lassen, erstellt mit dem Adapter logparser.
Das wäre echt eine coole Sache, wenn alle Errors sofort in der Jarvis sichtbar wären.

**Comment by Zefau** [comment]
die v2.2 ist für Ende Januar / Anfang Februar geplant, abhängig davon, wie ich durch komme. Danach kommt die v2.3. Ich würde mit Mitte / Ende Februar in der beta rechnen.

**Comment by duczz** [comment]
Könnte man den HTML String in der JSON mit berücksichtigen?
"severity":"<span class='logInfo logSeverity'>info</span>"
