### ISSUE TITLE
AdapterStatus: Nur bestimmte Adapter auflisten

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#323]
Um im Modul AdapterStatus nur bestimmte Adapter zu zeigen ist der Namespace des Adapters in die `blacklist` aufzunehmen, z. B.: `hm-rpc,shelly`.

**Comment by tschortschde** [comment]
Hallo ist es möglich, 
nur die Adapter anzuzeigen, die deaktiviert sind?
