### ISSUE TITLE
Support import wifilight.0 Objects

### ISSUE THREAD

**Issue by testit2020** [Zefau/ioBroker.jarvis#325]
Feature Einfügen von Import der Objekte von wifilight.0, um Steuerung von LED-Bändern in jarvis zu nutzen

![grafik](https://user-images.githubusercontent.com/68483974/98450474-42100580-213d-11eb-865c-3cfdd17e7414.png)

Beispiel für die Objekte:

![grafik](https://user-images.githubusercontent.com/68483974/98450496-653ab500-213d-11eb-8091-c3e5e1f1f5c3.png)
Vielen Dank.

**Comment by Zefau** [comment]
Users 2439

**Comment by Zefau** [comment]
@testit2020 added with `v2.2.0-beta.14`.

**Comment by testit2020** [comment]
https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/2976

**Comment by Zefau** [comment]
Bitte schau nochmal mit `v2.2.0-beta.16`.

Dropdown-Werte sollten nun übernommen werden und für rgb bzw. bri die richtigen Body / Action Trigger ausgewählt werden.

**Comment by testit2020** [comment]
bri kommt jetzt mit InputAction, LevelBody ist korrekt.
![image](https://user-images.githubusercontent.com/68483974/104821200-83f2b180-583a-11eb-947e-e64e7023b6f4.png)
progOn ist boolean und braucht kein InputAction
![image](https://user-images.githubusercontent.com/68483974/104821231-bef4e500-583a-11eb-8905-a41c619d12a0.png)
rgb braucht auch kein InputAction
![image](https://user-images.githubusercontent.com/68483974/104821292-14c98d00-583b-11eb-87a0-4a8adbb466a3.png)
refresh ist ein Boolean, wäre SwitchAction sinnvoll
![image](https://user-images.githubusercontent.com/68483974/104821326-47738580-583b-11eb-8333-2bbbb54e089b.png)

**Comment by Zefau** [comment]
@testit2020 prüf' mal bitte nochmal mit `v2.2.0-beta.17`.

**Comment by testit2020** [comment]
sieht gut aus. Danke.
