### ISSUE TITLE
Chart secondary y axis

### ISSUE THREAD

**Issue by cryptedx** [Zefau/ioBroker.jarvis#326]
Hey,

please can you add a secondary y axis so that we can have two different values in one chart?

Here is my example:
![image](https://user-images.githubusercontent.com/20707078/98461352-bc776e80-21ab-11eb-985b-76d28eb7c38c.png)

Left it should be °C on the right it should be %. Just as example. It should simply accept what is given as unity.

**Comment by Zefau** [comment]
@mcuiobroker implemented with `v3.0.0-alpha.84`

In dem Feld für y-Achsen ist nun ein Array anzugeben (also `[ ... ]`) mit den einzelnen Achsen als Object (also `[{ ... }, { ... }]`).
Beispiel siehe 
- https://echarts.apache.org/examples/en/editor.html?c=mix-line-bar
- https://echarts.apache.org/examples/en/editor.html?c=multiple-y-axis

**Comment by mcuiobroker** [comment]
Läuft. Prima. Danke.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/134993858-071fcb0d-6bd6-4b99-9fab-0b9b03ab5406.png)

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-alpha.85`

**Comment by cryptedx** [comment]
Sorry, kann nicht mehr testen. Bin seit längerem zu Home Assistant gewechselt.

**Comment by Zefau** [comment]
ok, schade

**Comment by mcuiobroker** [comment]
Es kommt keine Fehler-Anzeige mehr. Kannst du erstmal schließen.

**Comment by Timbo10071982** [comment]
> @mcuiobroker implemented with `v3.0.0-alpha.84`
> 
> In dem Feld für y-Achsen ist nun ein Array anzugeben (also `[ ... ]`) mit den einzelnen Achsen als Object (also `[{ ... }, { ... }]`). Beispiel siehe
> 
> * https://echarts.apache.org/examples/en/editor.html?c=mix-line-bar
> * https://echarts.apache.org/examples/en/editor.html?c=multiple-y-axis

Hey @mcuiobroker & @Zefau , 

can you guys make a code example here, how it should be entered in the field?

That would be brilliant. 

Thanks

**Comment by mcuiobroker** [comment]
Look at WIKI. Just my PC hang up, Hardware defect. So cant Help you directly

**Comment by Timbo10071982** [comment]
> Look at WIKI. Just my PC hang up, Hardware defect. So cant Help you directly
> 
> https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/historygraph

Works like a charm! Thanks for the hint!

**Comment by TZanke** [comment]
Thank you @Zefau for the feature!
Thank you @mcuiobroker for the hint!

But nevertheless i stumbled about some tiny detail till i got it to work properly.
JSON `integers` and `boolean` need to be without quotes. :weary:

![image](https://user-images.githubusercontent.com/1613368/181937326-24175a71-655c-4885-a843-56201f44c66d.png)



Also you should move the data to the correct axis, but the fields will only be available after saving the JSON.
![image](https://user-images.githubusercontent.com/1613368/181937502-7f18d059-cb79-42ca-8a08-bd9c930ee751.png)

My settings:
```
[
  {
    "name": "Temperatur",
    "min": "dataMin",
    "max": "dataMax",
    "axisLabel": {
      "formatter": "{value} °C"
    },
    "axisLine": {
      "show": true
    }
  },
  {
    "name": "abs. Feuchte",
    "position": "right",
    "min": "dataMin",
    "max": "dataMax",
    "axisLine": {
      "show": true
    }
  },
  {
    "position": "right",
    "min": 0,
    "max": 100,
    "offset": 50,
    "axisLine": {
      "show": true
    },
    "axisLabel": {
      "formatter": "{value} %"
    }
  }
]
```
