### ISSUE TITLE
[Chart] Order of items: Chart visualisation != json

### ISSUE THREAD

**Issue by cryptedx** [Zefau/ioBroker.jarvis#327]
**Prerequisites**
- [yes] Are you on the latest stable or latest beta of jarvis?

**Versions**
Beta 88

**Describe the bug**
Order of items is wrong. "Ist", "Stellantrieb", "Soll".

**Expected behavior**
Order of items should be  "Soll", "Ist", "Stellantrieb".

**Screenshots**
<img width="1253" alt="Bildschirmfoto 2020-11-08 um 10 41 29" src="https://user-images.githubusercontent.com/20707078/98461921-825c9b80-21b0-11eb-89b2-229946aff734.png">
<img width="1468" alt="Bildschirmfoto 2020-11-08 um 10 42 02" src="https://user-images.githubusercontent.com/20707078/98461922-84265f00-21b0-11eb-9b2d-747d32316a29.png">

```json
{
                     "moduleConfig": {
                        "chartFilterTimeRangeValue": "3",
                        "chartConfigyLeftAxisUnitBefore": "",
                        "chartConfigyLeftAxisUnitAfter": "°C"
                     },
                     "module": "Chart",
                     "title": "Schlafzimmer",
                     "devices": [
                        {
                           "type": "device",
                           "deviceId": "93d62a6b-f2c3-44e2-afa9-b88cefcdf68f",
                           "primaryStateKey": "settemperature",
                           "label": "Soll",
                           "color": "#D82929"
                        },
                        {
                           "type": "device",
                           "deviceId": "93d62a6b-f2c3-44e2-afa9-b88cefcdf68f",
                           "primaryStateKey": "temperature",
                           "label": "Ist",
                           "color": "#1FC537"
                        },
                        {
                           "type": "device",
                           "deviceId": "93d62a6b-f2c3-44e2-afa9-b88cefcdf68f",
                           "primaryStateKey": "stellantrieb",
                           "label": "Stellantrieb",
                           "color": "black"
                        }
                     ],
                     "id": "c96b56a0-36c7-4090-8817-527862061fde",
                     "index": 1
                  }
```

**Comment by Zefau** [comment]
The charts are shown in the order that their data has been retrieved from the backend. This is also why the sortation differs on every page render.

Why is this a problem?

**Comment by cryptedx** [comment]
Take my screenshot as example. If I have many of them for all rooms, then I would expect that every item/datapoint "Soll" is the first one and not mixed. Sometimes here and there. It should be just as I have configured it in the chart. It makes analysing a bit difficult.

**Comment by Zefau** [comment]
I don't see that there would be a difference in the chart when the sorting is different. Especially when you assigned static colors in the widget configuration.

**Comment by cryptedx** [comment]
When I want to deactivate all "Soll" items in e. g. 5 charts, then I would just have to focus at the first item. So I have to search for the color or text. No perfect UX.
I know it's just a small thing, but somehow for me it's important and maybe for others too?

**Comment by cryptedx** [comment]
Maybe we have a misunderstanding. Let's look at is as a table. Then there would be two different values in the columns. It would be great to have the same order.

<img width="321" alt="Bildschirmfoto 2020-11-08 um 11 29 59" src="https://user-images.githubusercontent.com/20707078/98462669-3ca2d180-21b6-11eb-9e92-672e6121b201.png">

1. Soll
2. Ist
3. Stellantrieb

Order like in here:

<img width="1253" alt="Bildschirmfoto 2020-11-08 um 10 41 29" src="https://user-images.githubusercontent.com/20707078/98462685-63610800-21b6-11eb-9965-22dfc0c5e9b1.png">

**Comment by Zefau** [comment]
In v3 the order is according to its configuration.
