### ISSUE TITLE
Nach Update auf beta 88 Konfiguration weg ?

### ISSUE THREAD

**Issue by mandragora666** [Zefau/ioBroker.jarvis#328]
Hallo,

Ich habe gerade auf die aktuelle beta 88 hochgezogen und anscheinend ist jetzt meine Konfig nicht mehr vorhanden bzw. kann darauf nicht mehr zugegriffen werden.
Bekomme jetzt nur mehr den Startscreen wie beim ersten Start zu sehen

![image](https://user-images.githubusercontent.com/73381262/98462133-167b3280-21b2-11eb-9bfa-429cbaa52264.png)

in der layout.json stehen die Einstellungen noch korrekt drinn.
![image](https://user-images.githubusercontent.com/73381262/98462205-a5884a80-21b2-11eb-9fcd-807229d77913.png)

Bitte um kurze Info und Hilfe was ich hier tun kann.

Danke 
lg
mandragora

**Comment by Zefau** [comment]
Versuch mal den Browser Cache zu löschen

**Comment by cryptedx** [comment]
Ja, mach das. Das hatte ich gestern auch und dann habe ich es mit einem anderen Browser versucht und es ging wieder.

**Comment by mandragora666** [comment]
jupp... so einfach.... hing echt nur am cache...
Danke.. geht wieder

lg
mandragora
