### ISSUE TITLE
Customize icons / avatars shown on Map

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#33]

**Comment by Zefau** [comment]
@braindead1 are you using the Map Widget?

`1.0.0-beta.16` implements avatars now. You may parse an image to a base64 and use it in the `icon` input (including `iconStyle` when using `{ "default": { ...style... }}`) and it will be applied as an avatar in the Map Widget:

![image](https://user-images.githubusercontent.com/14368811/92415964-8130d300-f15b-11ea-9c0c-409792a39fbc.png)

Of course, material icons can be used as well (including styling).

**Comment by braindead1** [comment]
I don't track my family member. Therefore I do not use the widget. Can you provide an example of which states are needed in ioBroker. I can then set them up manually and give it a short test.

**Comment by Zefau** [comment]
Much appreciated!

You only need to configure a device with `position` state, which holds the gps coordinates, e.g.:

![image](https://user-images.githubusercontent.com/14368811/92880606-7782c600-f40e-11ea-8545-55c9083dac3e.png)
(`location` state is not necessary)

![image](https://user-images.githubusercontent.com/14368811/92880862-b6188080-f40e-11ea-95f3-b7633c3aa7a4.png)

**Comment by braindead1** [comment]
Position is working in `v1.0.0-beta.26`. I was not able to test icon and styling as I did not understand which JSON is expected.

**Comment by Zefau** [comment]
Great, thank you!

I forgot to mention the JSON. This would be, e.g.
```
{
   "default":{
      "backgroundColor":"#a00"
   }
}
```
