### ISSUE TITLE
Möglichkeit Widgets / Spalten zentral auszurichten.

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#332]
Es wäre schön wenn man Spalten zentral ausrichten könnte. Es macht z.B. Sinn wenn man nur eine Spalte hat, diese zentral ausrichten zu können, damit es optisch etwas schöner wirkt.

![Screenshot 2020-11-10 101009](https://user-images.githubusercontent.com/56581564/98653851-d5178e00-233d-11eb-9fff-6a10de2c30a8.png)

**Comment by Zefau** [comment]
Das ist eigl. auch so. 

Ich gehe davon aus, dass dein Layout nur eine Spalte hat? 

Kannst du mal deine Theme Einstellungen screenshoten?

**Comment by WW1983** [comment]
Stimmt. War mein Fehler. Ich habe eine zweite Spalte hinzugefügt. Allerdings hatte es einen Grund. Das Bild lässt sich nicht skalieren. Es streckt sich über das ganze Bild und ist damit nicht zu gebrauchen.
![Screenshot 2020-11-10 135849](https://user-images.githubusercontent.com/56581564/98677906-056f2480-235e-11eb-93bb-39e4cf6e9704.png)


Die Begrenzung der Höhe wird dabei nicht angenommen.
![Screenshot 2020-11-10 140757](https://user-images.githubusercontent.com/56581564/98677988-29326a80-235e-11eb-8619-fdaabcb493e9.png)

**Comment by Zefau** [comment]
Sollte mit `v1.1.0-beta.91` passen.

**Comment by WW1983** [comment]
Scheint zu funktionieren. Danke!
