### ISSUE TITLE
Widget "Buttons"

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#333]
Was cool wäre, wäre ein Widget "Buttons". Damit hätte man Optisch etwas Abwechslung.

Hier ein Beispiel aus Lovelace:
![Screenshot 2020-11-11 125646](https://user-images.githubusercontent.com/56581564/98809332-aec91f80-241d-11eb-8b29-7670b0720436.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/240

**Comment by Zefau** [comment]
added through module `HomeKitTile` in v3 (https://github.com/Zefau/ioBroker.jarvis/issues/235)

**Comment by WW1983** [comment]
Bei dem HomeKitTile habe ich zwar die Möglichkeit die gesamte Schaltfläche zu verlinken, allerdings finde ich keine Möglichkeit die  gesamte Fläche als Trigger zu nutzen. Habe ich das übersehen?

**Comment by WW1983** [comment]
Funktioniert wunderbar! (die Triggerfunktion)
