### ISSUE TITLE
Add push-button element to trigger devices/actors

### ISSUE THREAD

**Issue by JRossbach** [Zefau/ioBroker.jarvis#334]
Although there are several buttons / checkboxes / switches available for actors/devices, I'm missing a push button (Taster) functionality. Another approach would be to allow customization of the label that is shown on the button ("anschalten").

**Comment by funky4t** [comment]
Genau so hab ich es mit der Beta auch gelöst! ;) Halt nur mit Start... 😉 sind Szenen die nur per Push angerufen werden, also keinen ON/OFF State haben.

![image](https://user-images.githubusercontent.com/57875762/98864906-e0b4a300-246a-11eb-890a-fe2df617e243.png)

**Comment by cryptedx** [comment]
Wie könnte ich es lösen wenn ich z. B. zwei Szenen habe. Szene Nr. 0 = Schlafen und Nr. 1 = Aufstehen. Ich möchte das die aktuell aktive Szene auch als aktiv+farblich gekennzeichnet wird.

**Comment by funky4t** [comment]
Naja eigentlich sind deine Szenen wie du es dir wünscht dann doch eher States. Man könnte jeder Szene einen eigenen Datenpunkt (Active) verpassen und dann in einem Script beim Aktivieren einer anderen Szene, die jeweilige "Gegen"Szene auf FALSE setzen. Dann lässt du dir in Jarvis den State anzeigen und nutzt den Push nur als Trigger. Mit Bordmitteln Jarvis kommst du da meines Erachtens nicht weiter. Also meine beiden Szenen haben nur einen Push BUTTON und keinen SWITCH, da musst du dann selber aktiv werden und definieren, dass Aufstehen automatisch den State Aktiv von Schlafen auf FALSE bringt. Woher soll der ioBroker das sonst wissen?

**Comment by cryptedx** [comment]
Dachte das ich es evtl. mit JSON machen kann z. B. {"0":"Schlafen","!0":"inaktiv"}. Aber ich komm nicht auf den Trichter. Ich glaube schon, dass es mit Jarvis machbar wäre. Die Informationen dafür sind ja durch den Datenpunkt vorhanden.

Push button ist ja ok.

Ich habe es jetzt temp. so gelöst:

![image](https://user-images.githubusercontent.com/20707078/99192349-abfa6180-2772-11eb-9650-c622d2b4db1c.png)

Die Benennung ist noch ein Jarvis Bug.

**Comment by Zefau** [comment]
`{"0":"Schlafen","!=0":"inaktiv"}` (man beachte das `!=`)

**Comment by cryptedx** [comment]
Danke. Hab es hier nur falsch geschrieben. Ich meinte != nur weiß ich nicht wo/wie genau ich das eintragen soll.

**Comment by Zefau** [comment]
Dafür ist die Option `showState` da. Wenn der Datenpunkt `true` ist wird der Wert gezeigt. Ist der Datenpunkt `false` wird der Button gezeigt. Ist das das, was du brauchst? Klingt für mich so.

**Comment by cryptedx** [comment]
Den habe ich auch versucht mit dem zu befüllen: {"0":"true","!=0":"false"} damit ich true und false herbekomme dafür. Aber hat nicht funktioniert. Heute wills echt nicht laufen bei mir.

**Comment by Zefau** [comment]
Warum `0` ? Was ist das für ein Datenpunkt im ioBroker? Wenn es in ioBroker ein Button ist, dann brauchst du
```
{ "true": "...", "false": "..." }
```

Hast du die `showState` Option im Widget gesetzt?

**Comment by cryptedx** [comment]
> Warum `0` ? Was ist das für ein Datenpunkt im ioBroker? Wenn es in ioBroker ein Button ist, dann brauchst du

Der Datenpunkt ist eine Zahl. Es sind KNX Szenen. Jede Szene ist eine andere Zahl. Man ordnet das was man haben möchte, der Szenenzahl zu.

![image](https://user-images.githubusercontent.com/20707078/99195241-dc4afb80-2784-11eb-918f-d06f45327ef5.png)

> Hast du die `showState` Option im Widget gesetzt?

ja

Ich hatte mir halt vorgestellt, dass der Button nur anklickbar ist, wenn die Szene nicht aktiv ist. Deswegen das ganze.

**Comment by Zefau** [comment]
Dann im Gerät `on` setzen mittels `{"true": 0 }

**Comment by cryptedx** [comment]
Sorry aber ich blicks echt nicht. Wo genau muss ich {"true": 0 } hineinschreiben? So funktioniert es jedenfalls nicht Es sollte bei inaktiv der "IconButtonAction" zu sehen sein.

![image](https://user-images.githubusercontent.com/20707078/99293425-ee8b6f00-2842-11eb-8e9a-b9c6f3082e79.png)

![image](https://user-images.githubusercontent.com/20707078/99293330-ce5bb000-2842-11eb-9bcc-fc7b73438b05.png)

![image](https://user-images.githubusercontent.com/20707078/99293631-34e0ce00-2843-11eb-89fc-b6438427ea5c.png)

**Comment by Zefau** [comment]
@JRossbach does this fix your initial requirement as well?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/450
