### ISSUE TITLE
Warnung Material Design Icons: Failed to decode font

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#336]
hier das hab ich grad in der konsole zufällig gesehen,
dachte ich melde es einfach mal

![image](https://user-images.githubusercontent.com/73311538/98992750-d90a0280-252d-11eb-87de-3de315b9aaca.png)

**Comment by Zefau** [comment]
To be supported with https://iconify.design/

**Comment by Zefau** [comment]
@Timmes123 could you check with `v2.1.0-beta.29` ?

**Comment by DNC74** [comment]
@Zefau it seems the issue is still there on ``2.1.0.beta-33`` 

[iobroker-1609282420914.log](https://github.com/Zefau/ioBroker.jarvis/files/5752492/iobroker-1609282420914.log)

**Comment by Zefau** [comment]
In `v2.2.0-beta.4` Material Design Icons has been replace with Iconify (https://iconify.design/), see https://iconify.design/icon-sets/ for all available icons (which includes Material Design Icons, Font Awesome, Fluent UI System Icons and many many others.

Usage: `namespace:icon`, e.g. `mdi:home` or `fa-solid:address-card` (https://iconify.design/icon-sets/fa-solid/) or `fluent:alert-on-24-filled` (https://iconify.design/icon-sets/fluent/).
