### ISSUE TITLE
blankscreen after deconz import lamp popup

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#337]
Ich habe von der hue bridge auf deconz umgerüstet.
ich hab alle lampen von jarvis automatisch importieren lassen.
wenn ich die lampe jetzt anklicke um das popup zu öffnen bekomm ich nen blankscreen mit dem fehler hier

![image](https://user-images.githubusercontent.com/73311538/98993600-f7bcc900-252e-11eb-9941-631b67876b5d.png)

ich hab jetzt festgestellt, dass du bei colortemperature 2000-6500 als min und max festgelegt hast
bei mir ist es aber min 153 (ganz kalt) und max 500 (ganz warm)

hab min und max in der gerätekonfig mal angepasst, aber der fehler bleibt der gleiche

ein refresh der seite brint jarvis wieder, ein erneutes anklicken der lampe bringt wieder den blankscreen

**Comment by Zefau** [comment]
Ist das mit `v1.1.0-beta.96` behoben?

**Comment by Timmes123** [comment]
getestet mit beta 96 

![image](https://user-images.githubusercontent.com/73311538/98996862-e0340f00-2533-11eb-91e8-79452f2a4a01.png)

:-)

jetzt muss ich nur noch herausfinden, warum ich so doofe zahlen habe? also 153-500? sind normale hue colors

**Comment by Zefau** [comment]
Nein, 0-360° ist der Hue-Slider.

**Comment by Timmes123** [comment]
> Nein, 0-360° ist der Hue-Slider.

sorry, aber nein. 
ich mein es schon so wie ich es sage.
im deconz datenpunkt ct gehen nur werte von 153-500 bei mir.
ich hab die philips hue color e27 glühbirnen.
hab grad im internet gelesen, dass das bei vielen geräten anscheinend so ist?
aber mit verschiedenen zahlen.. andere haben z.b. 250-450... keine ahnung warum das so ist
hab jetzt bei dir die min und max werte entsprechend geändert, jetzt kann ichs zumindest bedienen, auch wenns mit °K nicht ganz korrekt ist

**Comment by Zefau** [comment]
Dann musst du ein Issue bei deconz öffnen. Sehe auch Diskussion hier: https://forum.iobroker.net/topic/24936/diskussion-objektdefinition-licht/2:
> level.color.hue:    Vorgabe Einheit und Wertebereich: °, 0-360

Temporär sonst einen Konverter-Datenpunkt erstellen.

**Comment by Zefau** [comment]
Oder wechsle auf hue-extended, der kann auch deconz.

**Comment by Timmes123** [comment]
> Oder wechsle auf hue-extended, der kann auch deconz.

oh gott nein bitte nicht :D ich hab hue extendend grad gelöscht und alle lampen angepasst in jarvis, weil ich dachte ich muss den deconz nehmen ^^

**Comment by Timmes123** [comment]
anscheinend muss ich wieder zurück bauen...
