### ISSUE TITLE
Improve mobile view

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#34]

**Comment by Zefau** [comment]
@braindead1 are you using jarvis on a mobile device? Do you have anything that you think should be improved on a mobile device? I opened this issue, but I forgot why ;)

**Comment by braindead1** [comment]
Yes, I sometimes use jarvis on my mobile to get a quick overview. I usually do not use it to set states. Nevertheless the following could be improved/implemented.

- When opening the state dialogue in portrait mode the `level` states do not display well as the slider overlaps the state value.
- I split my tabs into 2-3 columns. In portrait mode these columns are stacked with nearly space between each other. Adding some space more would make it more appealing.

**Comment by Zefau** [comment]
Could you screenshot the problem in #1?
Jarvis is actually calculating the correct width, which works for me:

![image](https://user-images.githubusercontent.com/14368811/92786785-d7468600-f3a8-11ea-8776-55fab7784302.png)

**Comment by braindead1** [comment]
When I was writing the comment I had no access to my LAN. Therefore I was commenting out of my memory and I remembered that I had this issue some time ago. It's true, that the issue is gone in the meantime.

**Comment by Zefau** [comment]
Added divider between stacked columns with `1.0.0-beta.26`. I think that's better and enough?

**Comment by braindead1** [comment]
It's better than before, but in my opinion it's sufficient to just add half of the space without divider.

**Comment by Zefau** [comment]
What do you think of `1.0.0-beta.28` ?

**Comment by braindead1** [comment]
Looks good in `v1.0.0-beta.28`
