### ISSUE TITLE
Jarvis not initializing every other config change "please create a configuration"

### ISSUE THREAD

**Issue by CC1337** [Zefau/ioBroker.jarvis#340]
**Prerequisites/Versions**
- beta101 but started way earlier, likely after updating from 1.0.9 stable - could be related?
- start of discussion in https://forum.iobroker.net/topic/30668/jarvis-just-another-remarkable-vis/1675

**Describe the bug**
After switching tab and then editing the configuration, the configuration is saved, but no data is fetched from the server. Page stays "empty" and suggests to create a configuration first.
It can be solved by deleting the LocalStorage entry "jarvis.0.params:"{"tab":"eg-3"}" and hitting F5. It works until editing configuration next time after switching tab.
Does not happen between config changes without switching tab.
Happens in Chrome and FF, latest, Windows 10, various PCs.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/4866744/99132655-5bbabc80-2617-11eb-9591-035a51f7f411.png)
![grafik](https://user-images.githubusercontent.com/4866744/99132717-958bc300-2617-11eb-9a4b-322001fa4b1c.png)

I can supply more config values directly if needed and also can show on a call with screenshare (e.g. Discord).

**Comment by Zefau** [comment]
Thanks for creating the issue. It is hard to keep track of everything in the forum. I will follow up on this.

**Comment by Zefau** [comment]
@CC1337 are the states in ioBroker in fact empty (`jarvis.0.layout` and `jarvis.0.devices`) ? Reloading the pages (without emptying the local storage) does not help either?

As I understand, the states in ioBroker are correctly set and reloading the page does not help - the local storage has to be emptied?

**Comment by Zefau** [comment]
Please try `v1.1.0-beta.102`. Not sure if that resolves the problem, but it adds more information to the console log.

**Comment by Zefau** [comment]
I can confirm this issue now.

**Comment by CC1337** [comment]
... and did you fix it really quick in 103? because I cannot repro right now o.O

**Comment by Zefau** [comment]
yeah, I fixed it apparently. Could not reproduce it on the development machine (only in "production"). Now after updating production from 101 to 103 I think it is solved indeed.

**Comment by Zefau** [comment]
Let's keep an eye on this. But looks good so far.

**Comment by tehmilcho** [comment]
Hi there,

i just installed today Jarvis 1.0.9 and get the same Error. =( 

In the Log is only when i hit the "Save-Button".
web.0 | 2020-11-14 18:05:48.203 | info | (457) ==>Connected system.user.admin from ::ffff:192.168.178.XX
web.0 | 2020-11-14 18:05:48.053 | info | (457) <==Disconnect system.user.admin from ::ffff:192.168.178.XX

**Comment by Zefau** [comment]
This issue applies to v1.1.x, which will replace v1.0.x soon in latest repo.
