### ISSUE TITLE
Iframe Aktualisierung alle x Sekunden funktioniert nicht

### ISSUE THREAD

**Issue by simatec** [Zefau/ioBroker.jarvis#341]
Ich habe noch ein kleines Problem feststellen müssen.
Meine Tabs mit Grafana Iframe habe ich auf Aktualisierung alle 5 Minuten in Jarvis eingestellt. Grafana selbst hat auch diesen Intervall ...

Die Aktualisierung erfolgt aber nicht.

So wie es aussieht, erfolgt diese nur, wenn der Tab aktiv ist.

Hab ich den Tab geöffnet (aktiv) scheint er sauber zu aktualisieren.

**Comment by simatec** [comment]
Hab das ganze jetzt noch einmal intensiv getestet. 
Wenn ich die Aktualisierung des Iframes im Jarvis auf 0 stelle hat das den selben Effekt. Die Iframes aktualisieren nur, wenn der Tab akiv ist und auch dann nimmt er den in Grafana eingestellten Intervall. D.h. ich habe nie einen aktuellen Stand. Ich müsste erst die in Grafana eingestellte Zeit abwarten und den Tab in Jarvis aktiv haben.
Hier wäre eine Hintergrundaktualisierung auch bei nicht aktiven Tab sicher sinnvoll.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/521111

**Comment by Zefau** [comment]
Bitte `v1.1.0-beta.114` prüfen, ob es damit behoben ist.

**Comment by Zefau** [comment]
@simatec is this working as expected ?

**Comment by simatec** [comment]
Its works perfect 👍🏻
