### ISSUE TITLE
Deleting state causes widgets to be emptied

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#342]

**Comment by Zefau** [comment]
hopefully resolved with `v1.1.0-beta.105`.

**Comment by Zefau** [comment]
@duczz can you confirm?

**Comment by duczz** [comment]
Wenn ich den state lösche verursacht es folgenden fehler "(7499) Insufficent properties provided for device test (no states defined)!" und ich hab nur nochn greyscreen

**Comment by Zefau** [comment]
@duczz Liest sich so, als hättest du den einzigen Datenpunkt gelöscht? Die Warnung erscheint, wenn keine Datenpunkte definiert sind (`no states defined`).

**Comment by duczz** [comment]
Das stimmt, das war zu dem Zeitpunkt der einizge Datenpunkt in dem Widget, dann sollte aber nicht komplett jarvis grau sein oder?

**Comment by Zefau** [comment]
Nein das natürlich nicht.Ich schau nochmal

**Comment by Zefau** [comment]
@duczz Also bei mir funktioniert es soweit. Kannst du nochmal deine Ausgangssituation und was du konkret gemacht hast darstellen?

Ich hatte ein Gerät in einem Widget (im primären Datenpunkt). Habe dann im Gerät den Datenpunkt gelöscht und alles gespeichert. Im Widget habe ich nichts geändert.

Ich bekomme dann die Warnung im Log, aber jarvis lädt normal.

**Comment by duczz** [comment]
mit aktueller Beta nicht mehr reproduzierbar, somit close
