### ISSUE TITLE
SwitchAction not working with hue-extended "on" any more

### ISSUE THREAD

**Issue by DanielG1987** [Zefau/ioBroker.jarvis#343]
**Versions**
- Which jarvis version are you running: 1.1.0-beta.106

**Describe the bug**
Since one of the 1.1.0-beta.9x the SwitchAction is not working any more correctly in combination with hue-extended. I have my lights linked to e.g. "hue-extended.0.lights.005-schalter_küche.action.on". Using the SwitchAction switching to "On" state in the UI switches the light on and the ".action.on" state to "true". Switching the SwitchAction to "Off" in the UI does not switch the light off any more - in the objects browser of iobroker the ".action.on" state is switched to an empty string. In the UI the SwitchAction is showing "Off" then. 

This only happends with the hue-extended actions as far as i have seen on short, if I use for example another bool variable in my javascript adapter to switch to true / false it is working. 

Do i have to define the "off" state to "false"? 

Device config:
![SwitchAction_1](https://user-images.githubusercontent.com/71924209/99184523-bcdfae80-2743-11eb-88ee-7bd2a61d90ba.png)

Layout config:
![SwitchAction_2](https://user-images.githubusercontent.com/71924209/99184526-c0733580-2743-11eb-9c1a-8de5f91be25a.png)

Light switched on:
![SwitchAction_3](https://user-images.githubusercontent.com/71924209/99184550-f1ec0100-2743-11eb-8c83-ed66c6b448dc.png)

And then switched off via UI:
![SwitchAction_4](https://user-images.githubusercontent.com/71924209/99184553-f6b0b500-2743-11eb-9235-fb7ebec48456.png)

**Comment by WW1983** [comment]
Den selben Fehler habe ich auch!
https://forum.iobroker.net/post/521713

**Comment by Zefau** [comment]
Resolved with `1.1.0-beta.110`.

**Comment by WW1983** [comment]
Hat funktioniert. Danke!
