### ISSUE TITLE
JSON editing in device is being blocked if not valid JSON. Too aggressiv.

### ISSUE THREAD

**Issue by cryptedx** [Zefau/ioBroker.jarvis#345]
**Versions**
Installierte Version:1.1.0-beta.105

**Describe the bug**
I tried to edit it and just put in a komma and then something kicks in and blocks it! I have to close the window and redo it again!

**Screenshots**
![json edit fails](https://user-images.githubusercontent.com/20707078/99190884-874dbc00-2769-11eb-9ac5-a6ec06379a86.gif)

**Comment by Zefau** [comment]
fixed with `v1.1.0-beta.109`.

**Comment by cryptedx** [comment]
Fix verified!
