### ISSUE TITLE
Add Info Type from the Adapter Updates 

### ISSUE THREAD

**Issue by testit2020** [Zefau/ioBroker.jarvis#346]
Bitte eine Info über den Typ von den Adaptereinstellungen hinzufügen:

Welcher Verwahrungsort wurde eingestellt: stable / latest

Vielleicht sogar mit entsprechender Farbe kennzeichnen:
stable -> green
latest -> red

https://forum.iobroker.net/topic/30668/jarvis-just-another-remarkable-vis/1727

**Comment by Zefau** [comment]
added with v3

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.67`
Funktioniert.
Ich halte es nachwievor für sinnvoll hier ein Scrollbalken In Abhängigkeit der Höhe vom Widget einzuführen.
Man muss bei jedem zusätzlichen Adapter die Liste im Layout neu konfigurieren.
![image](https://user-images.githubusercontent.com/84818934/132253275-40afba40-855b-46ae-b85e-502735285b83.png)

**Comment by Zefau** [comment]
Kannst du im Widget auch einstellen

**Comment by Zefau** [comment]
![image](https://user-images.githubusercontent.com/14368811/132254532-9298f5bc-ff22-4628-b7d1-f452c5ee467a.png)

`Scale contents` option deaktivieren, dann sollte es passen?

**Comment by mcuiobroker** [comment]
Ja. Passt. Wir haben in letzter Zeit so viel geändert, da kommt man nicht mehr mit bei allen Änderungen. Danke.
Kann geschlossen werden.
