### ISSUE TITLE
last change body of state determined wrong

### ISSUE THREAD

**Issue by CreatsheR** [Zefau/ioBroker.jarvis#351]
**Prerequisites**
- [x] Are you on the latest stable or latest beta of jarvis?
- [x] Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Versions**
- Which jarvis version are you running: 1.1.0-beta.109 
- Please provide your `Support-ID` (in jarvis via Settings -> Help): 1ef8d78141f72c240535a04d4a2f3160028d19b5b1f384b464e23d2c1659d70f

**Describe the bug**
The last change body in jarvis seems not to be the last change of the state but the timestamp.

**Expected behavior**
Show the last change, not the timestamp.

**Screenshots**
![Bildschirmfoto 2020-11-17 um 08 01 07](https://user-images.githubusercontent.com/72187841/99357000-6f7e5100-28ab-11eb-9241-4e2540d28b78.png)
![Bildschirmfoto 2020-11-17 um 08 02 40](https://user-images.githubusercontent.com/72187841/99357003-70af7e00-28ab-11eb-80b0-e88ca4970bec.png)

**Comment by Zefau** [comment]
Resolved with `1.1.0-beta.110`. Change the default back to `lc` (last change). You may change to `ts` (timestamp) within the Widget configuration.

**Comment by CreatsheR** [comment]
Works. I would suggest to rename the ts-setting to last update. I believe timestamp or in german Zeitstempel is misleading.

**Comment by Zefau** [comment]
Will be changed with the next beta.
