### ISSUE TITLE
dateTime-widget is left aligned instead of center

### ISSUE THREAD

**Issue by CreatsheR** [Zefau/ioBroker.jarvis#353]
**Prerequisites**
- [x] Are you on the latest stable or latest beta of jarvis?
- [x] Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Versions**
- Which jarvis version are you running: 1.1.0-beta.112
- Please provide your `Support-ID` (in jarvis via Settings -> Help): 1ef8d78141f72c240535a04d4a2f3160028d19b5b1f384b464e23d2c1659d70f

**Describe the bug**
Like mentioned in the title, the text in the dateTime-widget is left aligned instead of center.

**Expected behavior**
The text should be aligned to center. If I'm right the property "display: flex" of the class jss25 is the "wrongdoer".

**Screenshots**
![grafik](https://user-images.githubusercontent.com/72187841/99495432-f0ece680-2972-11eb-881b-ddd9de696fc9.png)
![grafik](https://user-images.githubusercontent.com/72187841/99495437-f4806d80-2972-11eb-95b5-e67f8d25574d.png)

**Comment by Zefau** [comment]
Did you configure the widget to center its contents within the widget configuration?

**Comment by CreatsheR** [comment]
God what am I dumb sometimes. I didn't recognize, that there is a setting since 1.1.0  unlike 1.0.9... I'm sorry
