### ISSUE TITLE
Devices cannot be added to StateList

### ISSUE THREAD

**Issue by funker** [Zefau/ioBroker.jarvis#354]
**Versions**
- Which jarvis version are you running: 1.1.0-beta.112
- Please provide your `Support-ID` (in jarvis via Settings -> Help): `2b9fa3d7f5df1534960298c3838aad0bd7321cdc23e4d6f27e7fcebd2e19228a`

**Describe the bug**
I used the stable build until today, but now I switched to the latest beta, because of the many new features added.

Now I can add new devices as before, but when I want to add any device to a widget via the dropdown box different browsers switch to a URL like http://[hostname]:[port]/jarvis/index.html#tab=obergeschoss-1. In my case, "obergeschoss-1" is a different floor but not exactly named like this.
All changed are discarded then.
This only seems to happen when "StateList" is chosen. "StateListHorizontal" works normally.
I can switch to "StateListHorizontal" on existing widgets, add the devices and switch back to "StateList" as a workaround.

**Expected behavior**
The device should be able to be added to the StateList as before ;-)

**Screenshots**
Screenshot cannot really be made. A video would better show what is going on.

I love jarvis. Thanks for this fancy piece of software 🥇

**Comment by Zefau** [comment]
Thanks for the bug report. This should be resolved with `v1.1.0-beta.113`.

**Comment by Zefau** [comment]
@funker can you confirm?

**Comment by funker** [comment]
Yes, it's solved. Thanks a lot :-)
Man, I like the new collapsable style in the devices. Great job!
