### ISSUE TITLE
Einbinden Grafana über IFrame führt zu langen Ladezeiten seit Version 1.1.0-beta.115

### ISSUE THREAD

**Issue by ninja-warrior** [Zefau/ioBroker.jarvis#356]
Guten Morgen!

Mir ist gestern aufgefallen, dass meine Grafana Statistiken (Einbetten mittels IFrame) seit Jarvis Version 1.1.0-beta.115 störend lange laden. Zuvor wurden die Grafiken innerhalb von max. 2 Sekunden aufgebaut. Seit dem Update dauert der Aufbau der Statistiken mindestens 60 Sekunden. Rufe ich den Link zur Grafana Statistik direkt im Browser oder über das Webinterface von Grafana auf, wird diese unmittelbar angezeigt... Vielleicht kannst du ja mal einen Blick darauf werfen.

Vielen Dank vorab und viele Grüße!

Beispielhafte Konfiguration:
![image](https://user-images.githubusercontent.com/73721169/99632002-cff0c800-2a3c-11eb-83ff-26e9360fe66e.png)
![image](https://user-images.githubusercontent.com/73721169/99632119-fb73b280-2a3c-11eb-9574-d071b7d4c997.png)

Ansicht bei Aufruf des Tabs:
![image](https://user-images.githubusercontent.com/73721169/99632199-1cd49e80-2a3d-11eb-8925-989d081359f9.png)

Ansicht nach etwa 60 Sekunden:
![image](https://user-images.githubusercontent.com/73721169/99632288-4261a800-2a3d-11eb-9710-68a9c7d5d409.png)

**Comment by Zefau** [comment]
Könntest du `v1.1.0-beta.117` probieren, ob es damit wieder passt?

**Comment by ninja-warrior** [comment]
Danke, passt wieder!
