### ISSUE TITLE
States stop updating

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#357]
https://forum.iobroker.net/post/523238
https://forum.iobroker.net/post/523831

**Comment by Zefau** [comment]
added additional logging with `v1.1.0-beta.125`.

**Comment by Zefau** [comment]
another try with `v1.1.0-beta.127`.

**Comment by WW1983** [comment]
Bei mir Läuft Jarvis nun 2 Tage durch. Das Problem schein behoben zu sein. Die States werden durchgehen aktualisiert.

**Comment by cryptedx** [comment]
May I also insert my problem here?

This one is also not updating. It worked for some minutes.

![image](https://user-images.githubusercontent.com/20707078/100135138-80b9f580-2e89-11eb-980c-055fb1a18afb.png)

![image](https://user-images.githubusercontent.com/20707078/100135214-99c2a680-2e89-11eb-9a3a-4ddd884e30b1.png)
