### ISSUE TITLE
Anzeige auf Fire 7 hochformat

### ISSUE THREAD

**Issue by blackluzie** [Zefau/ioBroker.jarvis#359]
Hallo, habe 2 Fire 7 im Einsatz leider ist hier die Anzeige buggy- siehe Foto -bekomme es mit de Einstellungen nicht hin.

Die Spaten sollen komplette Bildbreite haben

Am PC und am iPad ist alles richtig

Vielen Dank für diesen super Adapter

![00B371A0-FA9E-48DB-BDC8-5FF96278AC18](https://user-images.githubusercontent.com/56870555/99852494-64644300-2b81-11eb-8b04-6d293e54335c.jpeg)

**Comment by Zefau** [comment]
In den Einstellungen gibt es Optionen für die Spalten:

![image](https://user-images.githubusercontent.com/14368811/99856014-6382df80-2b88-11eb-8d0a-7cbc4c78dff9.png)

**Comment by blackluzie** [comment]
Das war es vielen Dank - hat mich schon Stunden gekostet 🤣
