### ISSUE TITLE
Add option to send usage data to developer

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#36]
Opt-in (option in settings) to share usage data with developer

- [x] ioBroker version, jarvis version
- [x] Web adapter version and settings
- [x] Socket-io adapter version and settings
- [x] Devices configuration
- [x] Layout configuration
- [x] Settings configuration
- [x] Browser information
- [x] Console errors / Exceptions

_____

- [x] opt-out in ioBroker adapter settings
- [x] ~~opt-out in jarvis settings~~ including identifier and last sent time
- [x] add interval on daily basis

**Comment by braindead1** [comment]
Maybe you should think about implementing Sentry, which has just been recently introduced with js-controller 3.0.x

**Comment by Zefau** [comment]
implemented with `v1.1.0-beta.43`.
