### ISSUE TITLE
Support import of devices from ioBroker.modbus adapter

### ISSUE THREAD

**Issue by Bjoern3003** [Zefau/ioBroker.jarvis#360]
Ich würde mich gerne zur Verfügung stellen, um Modbus Geräte für Jarvis les- und schreibbar zu machen.

Welche Informationen bräuchtest du von mir? Wie kann ich unterstützend helfen? Oder sollte man gar den Umweg über Alias Objekte gehen?

**Comment by Zefau** [comment]
Danke für die Unterstützung. Ich brauche:

1. [ ] einen Screenshot der Adapter-Struktur, um diese zu verstehen
2. [ ] die Experten-Ansicht eines Geräts, was importiert werden soll
3. [ ] eine Liste der Datenpunkte, die übernommen werden sollen
4. [ ] eine Idee, wie die verschiedenen Gewerke unterschieden werden können (auf Basis von 1)

Gerne können wir auch kurz discorden oder teamviewen.

**Comment by Zefau** [comment]
https://github.com/ioBroker/ioBroker.modbus

**Comment by Bjoern3003** [comment]
Teamviewer habe ich hier. Discord leider nicht. 

Wir können uns aber gerne über Skype verbinden und währenddessen noch sprechen :-)

**Comment by Zefau** [comment]
Ca. 2738 users

**Comment by Zefau** [comment]
@Bjoern3003 kannst du mir einen Screenshot der ioBroker Objektstruktur posten?

**Comment by Bjoern3003** [comment]
Hi, ich denke wie damals schon gesagt, dass Modbus sich vermutlich gar nicht wirklich automatisiert einbinden lässt. Es gibt dort keine "Geräte". Man legt einfach nur ein Objekt für "irgendwas" an. Das Objekt kann aber alles sein, sodass man anhand des Objektes gar nicht feststellen kann, um was für ein Gerät es sich handelt.

**Comment by Zefau** [comment]
Ich kann es trotzdem gerne versuchen. Klingt wie linkeddevices Adapter. Dort ist auch alles frei definierbar.
