### ISSUE TITLE
Mehrere Trigger Punkte

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#362]
Wäre es möglich mehrere Trigger für einen State zu hinterlegen?
Wäre z.b. sinnvoll wenn man pro Tag (mo,di,mi ...) eine Temperatur hinterlegen will, aber nicht alles pro zeile machen will

**Comment by Zefau** [comment]
Wäre das https://github.com/Zefau/ioBroker.jarvis/issues/165 ?

**Comment by duczz** [comment]
Sorry 😅
