### ISSUE TITLE
Switch acknowledgment

### ISSUE THREAD

**Issue by OberstVonGatow** [Zefau/ioBroker.jarvis#363]
Hi when i switch of my lights the state get set to "false" but the deconz adapter does not turn off the lights.
If i check the acknowledgment (german "Bestätigung") the light is turning off.
![image](https://user-images.githubusercontent.com/6384996/99918604-4aa93400-2d18-11eb-89c1-9da087c41c76.png)

**Comment by duczz** [comment]
@OberstVonGatow Current Beta? Was a Bug in older Beta's

**Comment by OberstVonGatow** [comment]
You are absolutly right. My bad.
