### ISSUE TITLE
StateListHorizontal zeigt keine sekundären Datenpunkte

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#364]
Im StateListHorozontal werden die sekundär Datenpunkte nicht mit angezeigt, man muss derzeit das normale nutzen und eintragen und dann umschalten, dann gehts

![image](https://user-images.githubusercontent.com/25475385/99937015-e3fe3780-2d64-11eb-9e30-e12481d3faa5.png)

StateList normal
![image](https://user-images.githubusercontent.com/25475385/99937027-e95b8200-2d64-11eb-9a0c-beb7bc2f0ab1.png)

**Comment by Zefau** [comment]
`StateListHorizontal` soll per Design keine sekundären Datenpunkte haben.

Habe das selbst nie probiert. Wie sieht es denn im Widget aus? Kannst du das mal screenshoten?

**Comment by duczz** [comment]
achso okay, dann passt der Workaround für mich auch :)
![image](https://user-images.githubusercontent.com/25475385/99941034-9d610b00-2d6d-11eb-9b20-5c1d78a6cde3.png)

**Comment by Zefau** [comment]
Sekundäre States sind mit `v1.1.0-beta.131` nun im Standard möglich.

**Comment by duczz** [comment]
Sekundäre States klappen, bezüglich des Abstand wurde/wird nichts gemacht oder?

**Comment by Zefau** [comment]
Du hast mich verloren. Was meinst du?

**Comment by Zefau** [comment]
Hab's mal geschlosen, weil der originäre Grund gelöst ist.

Meinst du ggf. https://github.com/Zefau/ioBroker.jarvis/issues/184 ?

**Comment by duczz** [comment]
Das Horizontal Widget hat ja auch nen Abstand zu den rändern. Dieser wäre mir am FullHD Tablet etwas zu groß (paar mm), weswegen ein zeilenumbruch stattfindet, nun war die frage ob man die ränder verkleinert (ähnlich wie damals beim wetter widget) oder im widget eine fixe breite hinterlegt (wie bereits auch bei der höhe machbar ist nur für die breite fehlt es noch)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/117
