### ISSUE TITLE
CustomHTML

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#365]
Wenn der Wert des CustomHTML's leer ist kommt folgender Fehler (In Kombi mit ical sprich kein Termin vorhanden)
![image](https://user-images.githubusercontent.com/25475385/99973298-e631b780-2d9f-11eb-8ef3-ce8ac467f640.png)

**Comment by Zefau** [comment]
fixed with `v1.1.0-beta.131`.

**Comment by duczz** [comment]
Perfekt, danke
