### ISSUE TITLE
Notification in der Header Leiste

### ISSUE THREAD

**Issue by Bjoern3003** [Zefau/ioBroker.jarvis#367]
In meiner aktuellen vis habe ich mir kleine Icons oben in der Statusleiste darstellen lassen, wenn bestimmte Bedingungen eingetroffen sind.

(z.B. wenn etwas im Briefkasten ist, oder noch Fenster geöffnet sind).

![23112020184752](https://user-images.githubusercontent.com/13675579/99996709-68c87000-2dbc-11eb-830f-26b5a8ee48f6.png)

**Comment by duczz** [comment]
Dazu gibt's bereits einen Issue
https://github.com/Zefau/ioBroker.jarvis/issues/200
