### ISSUE TITLE
Wetter Widget

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#368]
Könnte man die Ränder etwas verkleinern damit die Temperatur einzeilig wird?
![image](https://user-images.githubusercontent.com/25475385/99998815-864b0900-2dbf-11eb-81ad-ce8c7253000d.png)

**Comment by duczz** [comment]
Gibt's eigentlich nen Grund für die Minuse oder könnte man die auch wegnehmen?

**Comment by Zefau** [comment]
Das ist der Regen. Wenn du in Hamburg wohnst, haste da auch Werte ;-)

**Comment by duczz** [comment]
aaaahh alles klar :), vllt könnte man die auch ausblenden anstatt nem minus?

**Comment by Zefau** [comment]
Jo, würde gehen, aber dann wäre es eine zusätzliche Leerzeile. Sonst sieht's blöd aus, wenn eine Regenmenge an einem Tag angezeigt wird und an einem Tag nicht.

![image](https://user-images.githubusercontent.com/14368811/100005314-09bd2800-2dc9-11eb-91ad-ca30efec5583.png)

**Comment by duczz** [comment]
ah okay, ne dann lassen wirs so, sonst wird's widget noch größer - danke

Wird ja schon kleiner wenn die Temp n einzeiler wird ;)

**Comment by Zefau** [comment]
hab die Temperatur-Anzeige einzeilig gemacht mit `v1.1.0-beta.132`.

**Comment by duczz** [comment]
Funktioniert
