### ISSUE TITLE
Datenpunkt einen Text anfügen oder voranstellen

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#369]
Wäre es noch möglich vor einem State einen Text anzufügen wie es bereits derzeit bei "Einheit" hinten möglich ist?

**Comment by Zefau** [comment]
Kannst du nicht die Einheit entsprechend nutzen?

**Comment by duczz** [comment]
Theoretisch schon, aber dann steht der Text ja dahinter, ich hätte gerne hin und wieder davor und dahinter etwas stehen.
Könnte man das evtl. im Experten Modus ändern damit du nicht extra ein Fehler machen musst?

**Comment by Zefau** [comment]
_Originally posted by @Bjoern3003 in https://github.com/Zefau/ioBroker.jarvis/issues/583#issuecomment-782811534_

> Für bestimmte Szenarien wäre es klasse, wenn man dem Dargestellten Wert noch einige Informationen an- oder vorstellen könnte.

> Ein Beispiel:
> ![10012021134724](https://user-images.githubusercontent.com/13675579/104123262-64dfb580-534a-11eb-894c-c772826e97e1.png)

> Das "Raum lüften" in Grün sollte z.b. erscheinen, sobald die Schwelle über 60 ist. Alternativ z.b. wenn der Wert unter 40 fällt, dass dann dort steht "Raum befeuchten".

**Comment by mcuiobroker** [comment]
Das ist jetzt schon möglich über die Datenpunkt-Eigenschaft:
{"value":"val =>"'Dieser Text steht davor' + String(val)'"}
Tage bis der Müll geholt wird:
{"value":"val => 'In ' +String(val)"} -> In x Tagen (Tagen ist die EINHEIT)

**Comment by Zefau** [comment]
Jo stimmt. Danke dir

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/416
