### ISSUE TITLE
Weisse Seite bei Änderung am Kalender

### ISSUE THREAD

**Issue by Bjoern3003** [Zefau/ioBroker.jarvis#370]
Habe gerade an den Kalendereinstellungen etwas verändert. (von 2 auf 7 Tage in die Zukunft gegangen).

Nun kommt kurz jarvis und dann direkt eine  weisse seite.

![23112020224245](https://user-images.githubusercontent.com/13675579/100018785-45fa8380-2ddd-11eb-9e28-0c54d9f3d996.png)

**Comment by Zefau** [comment]
Da fehlt die Fehlermeldung (32 Nachrichten sind ausgeblendet). Kannst du nochmal schauen, ob sich da noch Nachrichten verstecken?

**Comment by Bjoern3003** [comment]
Oh shit. Guter Hinweis, ich habe nämlich selber schon die Fehler gesucht. War noch aus eine anderen Projekt nur in der info Kategorie der Konsole.

![24112020092447](https://user-images.githubusercontent.com/13675579/100068055-4c1d4e00-2e37-11eb-9058-495327ac7253.png)
Vielleicht in die Exception noch den Wert ausgeben, den er als Fehler moniert?

Habe gerade im ical Adapter auch bereits probiert, alles am Datum zu verändern, was mir der Adapter erlaubt.

**Comment by Zefau** [comment]
Should be resolved with `v1.1.0-beat.134`.

**Comment by Bjoern3003** [comment]
Leider bleibt der Fehler bei mir nach wie vor.

- [ ] Update auf Beta 134
- [ ] Cache geleert
- [ ] Strg+F5 (hard Reload)
- [ ] Datumskonfigurationen im ical durchprobiert, ob irgendeine Kombination funktioniert (ohne Erfolg)

Fehler ist immer noch der gleiche, wie oben von mir im Screenshot

**Comment by Zefau** [comment]
Jo, hab schon im Forum gesehen und heut morgen die `v1.1.0-beta.135` raus gehauen. Ich hoffe, es geht damit?

**Comment by Bjoern3003** [comment]
Kannst du die ins Master mergen? :-) Die spezifische Beta kann ich glaube ich in ioBroker nicht über die "Katze" installieren, oder?

**Comment by Bjoern3003** [comment]
So, die weisse Seite kommt nun mit der Beta 135 nicht mehr, dafür aber weiterhin nichts im Kalender, aber eine Fehledermeldung in der Konsole.

Habe auch wieder alles durchgespielt und im ical versucht umzustellen.

![25112020160946](https://user-images.githubusercontent.com/13675579/100245853-ca154e00-2f38-11eb-9f44-82c3e4be2ea7.png)
![25112020161006](https://user-images.githubusercontent.com/13675579/100245855-caade480-2f38-11eb-932f-fc3f6f369fd6.png)

**Comment by Zefau** [comment]
Bitte schau nochmal mit `v1.1.0-beta.136`. Darin sollte der Event als Warnung zu sehen sein. Kannst du mir das (gerne anonymisiert) bereitstellen? Bei dir scheint der Startzeitpunkt anders formatiert als normal. Das müsste ich mir mal anschauen.

**Comment by Bjoern3003** [comment]
Bitteschön 👍 

![25112020213540](https://user-images.githubusercontent.com/13675579/100279147-440ffc00-2f66-11eb-977a-a148180088d8.png)

**Comment by Zefau** [comment]
Kannst du das kopieren? Rechtsklick -> Objekt kopieren oder so?

**Comment by Zefau** [comment]
bzw. "start" sonst aufklappen

**Comment by Bjoern3003** [comment]
``created: Sat Oct 31 2020 18:05:47 GMT+0100 (Mitteleuropäische Normalzeit) {tz: undefined}
description: ""
dtstamp: Wed Nov 25 2020 21:34:45 GMT+0100 (Mitteleuropäische Normalzeit) {tz: undefined}
lastmodified: Sat Oct 31 2020 18:05:47 GMT+0100 (Mitteleuropäische Normalzeit) {tz: undefined}
location: ""
params: []
sequence: "0"
start: Fri Nov 27 2020 09:00:00 GMT+0100 (Mitteleuropäische Normalzeit)
tz: undefined
__proto__: Object

**Comment by Zefau** [comment]
Der Termin hat scheinbar kein End-Datum ? Wieso das?

**Comment by Zefau** [comment]
Könntest du mal die jüngste Version `v1.1.0-beta.136` über deine aktuell Installation drüber bügeln? Hab gerade aktualisiert (aber Versionsnummer nicht geändert).

**Comment by Zefau** [comment]
Kannst du mal die `v1.1.0-beta.137` probieren?

**Comment by Bjoern3003** [comment]
Oh yes, funktioniert ❤️ 

Wieso kein Enddatum gesetzt ist: Im Google Kalender ist Start und Enddatum (bewusst) auf die gleiche Zeit gesetzt.

**Comment by Zefau** [comment]
https://cdn.discordapp.com/attachments/768034497299611708/781299506851348490/unknown.png

**Comment by Zefau** [comment]
added additional warning with `v1.1.0-beta.139`.
