### ISSUE TITLE
SwitchAction Trigger Element / Settings für eigenen Objektwert fehlt

### ISSUE THREAD

**Issue by robert-ke** [Zefau/ioBroker.jarvis#371]
Hallo,

bis vor kurzem war bei dem Trigger Element "SwitchAction" der Schraubenschlüssel daneben zu finden, siehe hier ein älterer Screenshot:
![image](https://user-images.githubusercontent.com/74955542/100078562-f26f5080-2e43-11eb-998b-d1da3b682bd4.png)

Aktuell setze ich Beta 133 ein - dort ist dieser Schlüssel weg - Die Funktion, einen eigenen Wert als Value bei ON und bei OFF in das Trigger-Objekt zu schreiben war super und würde ich benötigen. Wurde die Funktion umgebaut oder <<versteckt>> und ich finde Sie nicht mehr?

Vielen Dank & Gruß,
Robert

**Comment by Zefau** [comment]
Die Komponenten `SwitchAction` hat keine eigenen Optionen mehr, daher fehlt der Schraubenschlüssel. Die Konfiguration ist in das Gerät bzw. direkt in den Datenpunkt gewandert, siehe https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#datenpunkt-eigenschaften.

**Comment by robert-ke** [comment]
Perfekt, genau das hab ich gesucht und klappt einwandfrei. Die Stelle ist zentraler und stimmiger als zuvor! Prima, vielen Dank für diese tolle Arbeit - das Projekt ist TOP!
