### ISSUE TITLE
Chart: Dividing values does not calculate correct results

### ISSUE THREAD

**Issue by ffetsred** [Zefau/ioBroker.jarvis#372]
1.1.0-beta.133

**Describe the bug**
I use a chart to visualize download rate of the internet connection. The datapoint is in bit/s.
To have a more readable scale I multiply the values by 1/1024=0,000976 to have kbit/s.
As I have a 50MBit/s connection I would expect 50000kbit/s as max value. But using above multiplier it shows 5kbit/s.
If I use 0,0000976 (additional divide by 10) it displays 500kbit/s (factor 100) which doesn't make sense.

**Expected behavior**
I would expect a max value of 50000kbit/s as max value.

**Comment by Zefau** [comment]
Should be resolved with `v1.1.0-beat.134`.

**Comment by ffetsred** [comment]
This doesn't seem to be fixed by `1.1.0-beta.134`.
It looks like that the data point is multiplied by multiplier^2 (e.g. 64 for multiplier of 8).

**Comment by Zefau** [comment]
Please try again `v1.1.0-beta.136`. Please reconfigure your widget. Only a float / number input is allowed.

**Comment by ffetsred** [comment]
Ok, ˋv1.1.0-beta.136ˋ seems to fix it.
Thank you!
