### ISSUE TITLE
Non-default tab icon does not display in top left corner

### ISSUE THREAD

**Issue by ffetsred** [Zefau/ioBroker.jarvis#373]
1.0.9 and 1.1.0-beta133

**Describe the bug**
If a tab icon is selected which is different from the default "home" icon, then it is not displayed in the top left corner, if the tab is selected.

**Expected behavior**
The selected icon is displayed.

**Screenshots**
Default "home" icon is shown in upper left corner.
<img width="484" alt="Bildschirmfoto 2020-11-24 um 17 05 07" src="https://user-images.githubusercontent.com/9626539/100119591-53fce280-2e77-11eb-8e12-44a95bfd007c.png">

Non-default "mdi-car-outline" from "Material Design Icons" does not display in upper left corner.
<img width="484" alt="Bildschirmfoto 2020-11-24 um 17 06 33" src="https://user-images.githubusercontent.com/9626539/100119789-8c9cbc00-2e77-11eb-9ac9-1de91427e63b.png">

**Comment by duczz** [comment]
@Zefau Den Fehler kann ich so nicht bestätigen, klappt bei mir einwandfrei (aktuelle beta)

**Comment by Zefau** [comment]
Sofern `mdi-` verwendet wird, erscheint das Icon nicht. Der Bug ist schon korrekt. Wird mit der nächsten beta behoben.

**Comment by Zefau** [comment]
Should be resolved with `v1.1.0-beat.134`.

**Comment by ffetsred** [comment]
The bug is fixed in `1.1.0-beta134`
Thank you!
