### ISSUE TITLE
Chart with history data from influx does not work

### ISSUE THREAD

**Issue by redxeagle** [Zefau/ioBroker.jarvis#374]
**Prerequisites**
- [x] Latest stable

**Versions**
- Jarvis 1.0.9

**Describe the bug**
I have a installed version of an influx dB and log all values into this one.
Activated for some of my zigbee sensor but also some other nativ one. 
None of them are shown inside jarvis. 
The Websocket message call to get the historic data does not return anything. 
compared to a friend who has a similar setup, showed us that this works fine for him. He get here data. No idea why this call is lost somehwere

**Expected behavior**
That the graph should show data

**Screenshots**
![image](https://user-images.githubusercontent.com/727418/100219811-c07aee80-2f16-11eb-9123-7fdf389e3743.png)

**Comment by Zefau** [comment]
Unfortunately v1.0.x only supports the history adapter with instance 0. In some cases InfluxDb works, but it is not fully supported.


The upcoming v2.0.0 (v1.1.x-beta.xx in Github) additionally supports InfluxDb and sql with any instance.

**Comment by redxeagle** [comment]
This sounds perfect.

How to update to the beta version?
Or when does 2.0.0 is coming out? So I could simply wait.

And still, the offer is here to participant ;)

**Comment by Zefau** [comment]
For the beta I would appreciate if you could join testing. Simply install the beta from Github directly.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/269
