### ISSUE TITLE
NaN und undefined bei BlindLevelAction

### ISSUE THREAD

**Issue by Bjoern3003** [Zefau/ioBroker.jarvis#376]
Wurde bereits in https://github.com/Zefau/ioBroker.jarvis/issues/233#issuecomment-714756240 kurz diskutiert, da es aber dort um was grundsätzlich anderes geht und der Bug noch vorhanden ist, hier als neuen Issue eröffnet.

Ebenso scheint bei mir in der `Beta 137` der BlindLevelAction aus der Übersicht heruas nicht mehr zu funktionieren. Im PopUp des Gerätes hingegen funktioniert es wunderbar. (Im PopUp wird im übrigen auch Der definierte Prefix anstelle des undefined angezeigt).

![25112020225819](https://user-images.githubusercontent.com/13675579/100285766-be924900-2f71-11eb-92d8-dc9679f1386a.png)

**Comment by Zefau** [comment]
Kannst du die Device Config mal screenshoten?

**Comment by Bjoern3003** [comment]
![26112020094900](https://user-images.githubusercontent.com/13675579/100328311-a996d380-2fcc-11eb-8bc8-99871e825a13.png)

**Comment by Bjoern3003** [comment]
Die Datenunkt Eigenschaft wird irgendwie auch nicht berücksichtigt.

**Comment by Zefau** [comment]
Bitte nochmal genau im Wiki lesen. Das Feld ist nicht dafür gedacht

**Comment by Bjoern3003** [comment]
Sorry, hast recht. Habe mir noch mal dein Video angesehen: https://youtu.be/6Cwuke2Bhog?t=651 Habe es nun versucht, in das Feld `Anzeigevariante (JSON Format)` einzubauen. Ergebnis bleibt aber das gleiche.

![26112020103152](https://user-images.githubusercontent.com/13675579/100333234-a3a3f100-2fd2-11eb-85bc-4bcd8c2f805a.png)

**Comment by Zefau** [comment]
Versuch mal `default` statt 100.

**Comment by Bjoern3003** [comment]
Bleibt alles wie gehabt. Ändert sich nichts im Frontend. 

Davon ab, wäre das aber vermutlich auch falsch. Ich möchte ja NUR bei 0 UND 100 einen anderen Anzeigewert. Alle Werte dazwischen (1 - 99) sollen auch als 1 - 99 dargestellt werden.

Jetzt vermischen wir aber wieder 2 Probleme :-D Hast du das noch im Blick, oder soll ich ein zweites Issue aufmachen?

**Comment by Zefau** [comment]
Der Datenpunkt `activity` muss in der Anzeige den Status halten und im Trigger einen Stop, z. B. bi Shelly:

```
         "activity": {
            "state": "shelly.0.SHSW-25#8CAAB50580C6#1.Shutter.state",
            "action": "shelly.0.SHSW-25#8CAAB50580C6#1.Shutter.Pause"
         },
```

**Comment by Bjoern3003** [comment]
Wenn ich das so konfiguriere, ist zwar das Prozentzeichen da, aber die hoch/runter Buttons haben keine Funktion.

Im Modal hingegen funktioniert es wunderbar. Aber dort wurde ja vorher auch das Prozentzeichen korrekt angezeigt ;-)

**Comment by Zefau** [comment]
@Bjoern3003 bist du bei Discord oder TeamViewer?

**Comment by Zefau** [comment]
@Bjoern3003 bzw. ginge auch Skype, dann können wir das gleich mit dem Modbus verbinden.

**Comment by Bjoern3003** [comment]
@Zefau hatte dich diesbezüglich bereits privat im iobroker forum angeschrieben. 🙂

**Comment by Zefau** [comment]
Problem mit `NaN` behoben, aber JSON Anzeigevariante wird nicht übernommen.

**Comment by Zefau** [comment]
@Bjoern3003 kannst du dir jarvis nochmal aktuell aus Github ziehen und drüber bügeln ?

**Comment by Bjoern3003** [comment]
Habe dir am SA noch mal in Skype umfangreich geantwortet :-)

**Comment by Zefau** [comment]
fixed with `2.0.0-rc.3`.

**Comment by Zefau** [comment]
@Bjoern3003 Installation via Katze in ioBroker mit der URL https://github.com/Zefau/ioBroker.jarvis/tarball/v2.0.x
