### ISSUE TITLE
Gruppierungen für States wie im Layout bereits möglich

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#379]

**Comment by Zefau** [comment]
?

**Comment by duczz** [comment]
Ich will diese Funktion als optische Trennung in states
![image](https://user-images.githubusercontent.com/25475385/100418925-d3f79800-3083-11eb-9c18-5d4f80eebabd.png)

**Comment by Zefau** [comment]
Du willst die wie in der Device Konfiguration gruppiert und collapsible haben?

**Comment by duczz** [comment]
Jup, collapsible könntest auch noch mit ins Widget integrieren. (Bessere Übersicht)

**Comment by Zefau** [comment]
Aber ist das das, was du mit dem Ticket meinst?

**Comment by duczz** [comment]
Ich glaube wir meinen in etwa das selbe, wir können es ja wenn du Zeit hast mal via Discord kurz besprechen bzw ich zeigs dir
