### ISSUE TITLE
Support import of devices from ioBroker.tr-064

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#381]

**Comment by Zefau** [comment]
added with `v2.1.0-beta.1`.

**Comment by Zefau** [comment]
@sigi2345 are you using the ioBroker.tr-064 adapter ? Could you verify and test the import as well? thanks in advanced

**Comment by sigi2345** [comment]
> @sigi2345 are you using the ioBroker.tr-064 adapter ? Could you verify and test the import as well? thanks in advanced

Ja, habe es überlesen.

**Comment by DNC74** [comment]
I'm using this adapter too and tested the import of devices with 2.1.0-beta.28:
the node "devices" is not imported:
`No correct defined states found. The device may be unknown. Please help the developer to add support for this device and report to Github.`
Data-Structure from iobroker:
![2020-12-28 19_40_08-objects - ioBroker und 4 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/72687758/103236330-ed228b80-4944-11eb-90b3-a4ed0f563c23.png)

**Comment by Zefau** [comment]
@DNC74 die Daten haben keinen Mehrwert in jarvis, oder? Würde daher den Fehler ausblenden.

**Comment by DNC74** [comment]
@Zefau Doch, für mich schon. Ich benutze diese u.a. zur Bestimmung der Präsenz. Ich habe dort den Zustand greifbar, ob unsere Mobiltelefone im WLAN eingeloggt sind, oder nicht. Oder ob z.B. ein anderes Netzwerk-Gerät aktiv ist, oder nicht. Der Channel ist das Gerät, der darunterliegende State 'active' gibt die Aktivität/Eingeloggt-sein an.

**Comment by sigi2345** [comment]
> @Zefau Doch, für mich schon. Ich benutze diese u.a. zur Bestimmung der Präsenz. Ich habe dort den Zustand greifbar, ob unsere Mobiltelefone im WLAN eingeloggt sind, oder nicht. Oder ob z.B. ein anderes Netzwerk-Gerät aktiv ist, oder nicht. Der Channel ist das Gerät, der darunterliegende State 'active' gibt die Aktivität/Eingeloggt-sein an.

Ja, sehr Wichtig und ziemlich genau.

**Comment by Zefau** [comment]
@DNC74 @sigi2345 könntet ihr nochmal mit `v2.1.0-beta.32` probieren?

**Comment by sigi2345** [comment]
> @DNC74 @sigi2345 könntet ihr nochmal mit `v2.1.0-beta.32` probieren?

Jupp, Devices kommen jetzt. Es ist aber sehr unübersichtlich da sie einzeln da sind.

**Comment by Zefau** [comment]
Jedes Gerät des Adapters wird als ein Gerät in jarvis geparsed. Was ist die Alternative?

**Comment by sigi2345** [comment]
> Jedes Gerät des Adapters wird als ein Gerät in jarvis geparsed. Was ist die Alternative?

Ok, geht mit Filter active

**Comment by DNC74** [comment]
getestet mit ``v2.1.0-beta.34`` : 
Funktioniert prima. :)
Ich hätte jedoch noch einen kleinen Verbesserungsvorschlag:
![2020-12-30 12_47_28-JarVis und 3 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/72687758/103349671-c6c43380-4a9d-11eb-940d-fec8676a1b4a.png)

Meiner Meinung nach braucht die beiden States "last*-ts" niemand in Jarvis. Kannst Du die beim Import ignorieren?

**Comment by Zefau** [comment]
Jo, das geht. Wird dann ab rc.2 greifen.
