### ISSUE TITLE
Height of the TopBar is too big in vertical direction

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#383]
I don't know if it is a bug or not, but especially when i turn off the "Icon and Title of the TopBar" the height of the title bar is too high.

I am using Version 2.0.0-rc.1

If this is the intention, feel free to mark this ticket as "won't fix"

![image](https://user-images.githubusercontent.com/61848539/100488774-82491f00-3110-11eb-94cc-8b376bba7b92.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/124

**Comment by Zefau** [comment]
Thanks for reporting. It is not intended, but a Feature Request for this already exists.
