### ISSUE TITLE
Visualization under NUC/Linux: No widgets are shown

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#388]
It is strange. My Jarvis Visualization is shown correctly on my Windows PC, see screenshot on the right. When i open the same URL on my NUC/Linux, the widgets are shown up shortly after open the webpage, but after some ms the widgets are invisible.

What i am doing wrong? I am using Version 2.0.0RC

![image](https://user-images.githubusercontent.com/61848539/100546881-ff38dd80-3263-11eb-83ad-008d2a700e5e.png)

**Comment by uwe72** [comment]
Please delete this ticket. I installed chrome instead of chromian. now it works.

**Comment by Zefau** [comment]
Do you have errors in the browser console?
