### ISSUE TITLE
Label for devices

### ISSUE THREAD

**Issue by Pla5ma** [Zefau/ioBroker.jarvis#389]
I like to use the device as shown in the IOBroker object structure as a device name in Jarvis. This helps me a lot to maintain overview in Jarvis even with many devices added. But if I do so the device popup is showing the real name and this doesn't look good. Due to this I would like to have the option to add a label to the device itself.

Example:

IOBroker
![image](https://user-images.githubusercontent.com/57805183/100548337-314e3d80-326c-11eb-8c64-1ba47c27b005.png)

Jarvis devices configuration tab
![image](https://user-images.githubusercontent.com/57805183/100548354-4a56ee80-326c-11eb-93f0-5a9ae47b6fbd.png)

Jarvis device popup
![image](https://user-images.githubusercontent.com/57805183/100548363-5b9ffb00-326c-11eb-8021-16fbc0abefb0.png)

Thanks in advance,
Daniel

**Comment by Zefau** [comment]
@Pla5ma added with `v2.1.0-beta.1`.
