### ISSUE TITLE
Databinding for Labels / Titles

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#390]
In my current visualizations (VIS) i am using often the feature of databinding (from data states) instead of using static labels.

Would be very nice to have the same in jarvices

For example, instead of a static text "Lights in the house" i would like to use databinding:
{javascript.0.clement.shelly.vis.subtitle_tablet}

Then the dynamic label could be like "There are 7 from 23 lights switched on"

Would be very useful also for tabtitles. My usecase on tabs is that i want to visualize that "something is wrong" within this tab, like a error or something like this.

**Comment by Zefau** [comment]
Create a device with a state `javascript.0.clement.shelly.vis.subtitle_tablet` and use it. That should be it?

**Comment by uwe72** [comment]
But can i use this devices to replace this titles here:
![image](https://user-images.githubusercontent.com/61848539/100611072-05d15e80-3311-11eb-8a1a-2d3518c6110e.png)

**Comment by Zefau** [comment]
No, the widget titles are static.

**Comment by manoloxxl** [comment]
> Create a device with a state `javascript.0.clement.shelly.vis.subtitle_tablet` and use it. That should be it?

Hi,

I've tried to understand this hint but was not able to create it. It just shows the string that i write into "label". Must it be placed in brackets or is the way i'm trying totaly wrong?

![iobroker](https://user-images.githubusercontent.com/25949606/140603670-d47234c0-230f-4dea-8956-402305f382ca.png)

![jarvis-setting](https://user-images.githubusercontent.com/25949606/140603667-919c08de-14b6-4689-952d-d0bf42b28986.png)

![jarvis](https://user-images.githubusercontent.com/25949606/140603669-f8716db6-2319-45f5-924b-2a0ff13b1c13.png)

**Comment by Zefau** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/binding

**Comment by manoloxxl** [comment]
> https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/binding

Also auf die v3 gehen. Okay, schaue ich mir an. Danke.

**Comment by w0nk1** [comment]
@Zefau Thank you for your amazing work! 12 € spent very well! ;-) 
May you help out with the given example of @manoloxxl ? To be honest, I can't find the "label case" inside the binding help section. Thank you in advance!

Cheers,
Markus

**Comment by Zefau** [comment]
Make sure you are on V3.

Then following the syntax as in https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/geraet/binding

```
{ "{0_userdata.0.Power0}>10 && {val}=100": "mdi-trash", "{0_userdata.0.Power0}<10 && {val}=100": "mdi-power" }
```

**Comment by w0nk1** [comment]
@Zefau Thanks for your answer, but that is not the case? In your given case the dynamic part is on the left side and a fix value for these is set. I need just the name of the feast day without any substitution.

Something like: {feiertage.0.naechster.Name}

<img width="956" alt="Bildschirmfoto 2022-04-18 um 11 44 00" src="https://user-images.githubusercontent.com/6522814/163790544-cd26950b-1466-4836-af27-c8ee552ea238.png">

**Comment by Zefau** [comment]
Ah, understood now. Binding values are not yet possible, see feature request https://github.com/Zefau/ioBroker.jarvis/issues/1021.

So far only conditions are possible

**Comment by w0nk1** [comment]
Okay! ;) Thank you for the clarification!
