### ISSUE TITLE
"Display Last Update" can only be changed in the StateListHorizontal, but not in the normal StateList

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#391]
The attribute "Display Last Update" can only be changed in the StateListHorizontal, but not in the normal StateList. As a aworkarround i change it in the StateListHorizontal to false and change back to the StateList

![image](https://user-images.githubusercontent.com/61848539/100554271-d7616e00-3293-11eb-8b57-85bb61ea0896.png)

Version 2.0.0RC

**Comment by Zefau** [comment]
What do you want to change in StateList ? You may select last update as body element in StateList.

**Comment by uwe72** [comment]
I want to disable "Display Last Update" in StateList.

For me this ticket is not too important because i have a easy workaround (switch to HorizontalStateList, turn off "Display Last Update" and switch back to StateList.

Maybe i also think wrong or there is another way...but in my view the setting "Display Last Update" is initial on in StateList and cannot be turned off?

**Comment by CreatsheR** [comment]
In the normal StateList you need to select the "lastChangeBody" as Body Element first:
![Bildschirmfoto 2020-12-01 um 12 32 23](https://user-images.githubusercontent.com/72187841/100735469-8a83b180-33d1-11eb-98d0-c6fa65d888e3.png)

Then you can click on the wrenge to select either last update or last change:
![Bildschirmfoto 2020-12-01 um 12 32 33](https://user-images.githubusercontent.com/72187841/100735464-86f02a80-33d1-11eb-8394-58815f95abc8.png)

**Comment by uwe72** [comment]
ok, thanks
