### ISSUE TITLE
Icons roller shutter in StateList

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#392]
I like that also the icons changes depending the level of the roller shutter.

For me is just not logical that when the level is, for example 30% that the icon is closed. The icon should be open when the level is >0  (or there should be a third icon for medium)

Priority "nice to have".

![image](https://user-images.githubusercontent.com/61848539/100554890-49d44d00-3298-11eb-8d8e-dee8d112058a.png)

**Comment by Zefau** [comment]
Did you solve this yourself?

**Comment by uwe72** [comment]
No, i just thought i don't want to annoy/nerve with this small topic. But actually i still think it should be changed :-)

**Comment by Zefau** [comment]
How did you configure the device? This is not the intended behavior.

The standard is
```
{
			"default": "window-shutter-open",
			">90": "window-shutter-open",
			"<=90": "window-shutter"
		}
```

**Comment by uwe72** [comment]
but the standard fits to my screenshot. 
So if i understand your code, if the level is less or equal than 90 (so means like in my screenshot 30%) the icon is closed. So in extreme if the roller shutter is almost open (90%) the icon is still not open, but closed?

**Comment by Zefau** [comment]
Yes. If you'd like to override the default, see https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#json-eingabefelder

**Comment by uwe72** [comment]
Works perfect. Thanks for the advice with the overwritting. Thats fine for me. Thanks
