### ISSUE TITLE
Wheater Module: more config settings

### ISSUE THREAD

**Issue by uwe72** [Zefau/ioBroker.jarvis#393]
Very nice module!!

Would be nice that everything is more compact or in other words would be nice, if there are some additional settings to hide some informations, like the yellow marked:

![image](https://user-images.githubusercontent.com/61848539/100616679-b6dbf700-3319-11eb-9453-58bbe93042ec.png)

**Comment by Zefau** [comment]
Feel free to share your version. I could implement different designs instead of 100 different options.

**Comment by uwe72** [comment]
I need this informations, so everything without this red marked things:
![image](https://user-images.githubusercontent.com/61848539/101022587-dec59780-3571-11eb-9d7e-f1c5367b037a.png)

**Comment by uwe72** [comment]
I did for me now this weather visualization. It shows the for me important informations:
![image](https://user-images.githubusercontent.com/61848539/101140452-467fef00-3613-11eb-8dc7-5692c78b672d.png)

But of course everybody has a different opinion.

May i ask a question? Where your blue small icons come from? is this also SVG and where are they from? Thanks

**Comment by Zefau** [comment]
The icons are all Material icons
