### ISSUE TITLE
Set a device-name to find it quick

### ISSUE THREAD

**Issue by homecineplexx** [Zefau/ioBroker.jarvis#394]
would be nice to set a "Name" or a "label" to find a special device quick,when the devices all have a very similar name

![image](https://user-images.githubusercontent.com/43374575/100629934-2d80f080-332a-11eb-9197-aabaff5b4491.png)

**Comment by uwe72** [comment]
I don't wan't to interfere, but i think in this case also helps to change the Devicenames in IObroker, like i did with my Shellys:
![image](https://user-images.githubusercontent.com/61848539/100634035-10025580-332f-11eb-8192-d3d341cea6a9.png)

Then after importing them in jarvis they have the same "nice" or readable names.

Sorry for commenting :-)

**Comment by homecineplexx** [comment]
Sorry, but this doesn't help, because my shellies aren't connected via Shelly Adapter. I used MQTT. So i cant import them and the name in ioBroker i will never see in Jarvis, so for me it would be great to set a name there.

**Comment by homecineplexx** [comment]
i found a way....thanks and sorry
