### ISSUE TITLE
Sekundeäre Datenpunkte

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#395]
Sekundäre Datenpunkte können nicht scheinbar nicht eingefärbt werden

**Comment by Zefau** [comment]
@duczz bitte nehme dir etwas mehr Zeit beim Anlegen von Issues bzgl. Rechtschreibung und Verständlichkeit.

**Comment by Zefau** [comment]
Würde das über https://github.com/Zefau/ioBroker.jarvis/issues/117 lösen
