### ISSUE TITLE
DeviceStateDetails: Custom Device popup configuration

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#40]
Allow users to individually configure device popup regarding the shown states (~~including last update timestamp~~) and its actions.

Also add possibility to deactivate the popup.

**Comment by Zefau** [comment]
added with `1.1.0-beta.54`.

**Comment by Zefau** [comment]
#115

**Comment by CreatsheR** [comment]
In 1.1.0-beta.109 the switch isn't in on-state despite the property is set and visible in expertmode

**Comment by Zefau** [comment]
Reads like it is related to https://github.com/Zefau/ioBroker.jarvis/issues/343 ?

**Comment by CreatsheR** [comment]
No I don't think so. I'm speaking of the property "suppressPopup" at the device itself:

![grafik](https://user-images.githubusercontent.com/72187841/99432898-16dfa000-290d-11eb-842a-74f776ccb281.png)

**Comment by Zefau** [comment]
Could you check `1.1.0-beta.110` if this resolves the bug?

**Comment by CreatsheR** [comment]
Yes works great 👍
