### ISSUE TITLE
Homematic IP Dimmer 

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#400]
Hauptlicht ist ein HomematicIP FunkDimmer, dieser hat nur einen LEVEL State und kennt kein true/false.

Wenn ich nun folgende Gruppe mache, mit "an/aus" wird dieser nicht "an" geschaltet. 
Bei Power ist die Datenpunkt Eigenschaft : {"on":100,"off":0}

würde an/aus die entspr. on/off der Datenpunkte schalte sollte das gelöst sein? Ist das ein BUG oder habe ich etwas falsch konfiguriert ? 

![image](https://user-images.githubusercontent.com/22169074/100932358-0a05a380-34ec-11eb-925a-1eac6e2cced5.png)

DAnke.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/178

**Comment by Zefau** [comment]
Behoben mit `v2.1.0-beta.7`. Nun sollten die in den Datenpunkt Eigenschaften definierten `on`/`off` Werte greifen.

**Comment by ma-gu-16** [comment]
funktioniert :-)

**Comment by Zefau** [comment]
@ma-gu-16 du kannst die Komponente wieder auf die Buttons umstellen in der Widget Konfiguration.
