### ISSUE TITLE
DRBL4 HomematicIP Jalousien/Storen/Blinds

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#404]
Hi,

ich habe die DRBL4 Wired Jalousienaktoren, folgende States:

![image](https://user-images.githubusercontent.com/22169074/101014230-cf405180-3565-11eb-8050-e41ca0948a69.png)

Ich habe nun ein Gerät  eingerichtet alles Default, bis auf die Anzeige und Aktorstates. 
![image](https://user-images.githubusercontent.com/22169074/101014366-10d0fc80-3566-11eb-81d6-ccbb9e3d523d.png)

Aktuell ist es nicht möglich das sich die Lamellen verändern, der Wert wird gesetzt aber der Aktor braucht noch irgendeine Bestätigung. Wenn ich jetzt einfach STOP drücke, werden die Lamellen gesetzt. 

Das ist etwas mühsam, ich habe das unter iobroker mit dem CombinedParameter gelöst, bei welchem der Aktor sofort reagiert. 
Ich kann das Gerät auch via JS-Scripte lösen aber ich denke du möchtest das sicher out-of-thebox haben. 

Vielleicht ist dieses Verhalten ja schon bekannt. 

Hatte das Verhalten mal beschrieben, siehe: 
https://forum.iobroker.net/topic/35312/gel%C3%B6st-homematic-hmipw-drbl4-jalousien-storen-steuern

Gruss

**Comment by ma-gu-16** [comment]
Was man auch verbessern könnte die Ansicht der eingestellten Werte: 
![image](https://user-images.githubusercontent.com/22169074/101017607-99ea3280-356a-11eb-8ae9-ae8f6c8ddc5a.png)

Grüsse :-)

**Comment by Zefau** [comment]
Das ist sehr HomeMatic spezifisch, insofern würde ich das nicht in jarvis lösen. Einfach im ioBroker (z.B. mittels Blocky) abfangen.

**Comment by ma-gu-16** [comment]
Hab ich via scripte in iobroker gelöst.

Danke.
