### ISSUE TITLE
Cannot delete Adapter from ioBroker

### ISSUE THREAD

**Issue by DanielWeeber** [Zefau/ioBroker.jarvis#405]
**Prerequisites**
- [x] Are you on the latest stable or latest beta of jarvis?
- [ ] Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Versions**
- Which jarvis version are you running: ...
- Please provide your `Support-ID` (in jarvis via Settings -> Help): ...

**Describe the bug**
Cannot delete Adapter from ioBroker

**Expected behavior**
Successful deletion

**Screenshots**
Log:
```
$ ./iobroker del jarvis
Delete adapter "jarvis"
npm uninstall iobroker.jarvis --error --prefix "/opt/iobroker" (System call)
npm
 ERR! code ELOOPnpm ERR! syscall opennpm ERR! path /opt/iobroker/node_modules/iobroker.objects-redis/package.jsonnpm ERR! 
errno -40
npm
 ERR! ELOOP: too many symbolic links encountered, open '/opt/iobroker/node_modules/iobroker.objects-redis/package.json'

npm ERR! A complete log of this run can be found in:npm ERR!     /root/.npm/_logs/2020-12-03T13_28_32_685Z-debug.log
ERROR: Error deleting adapter jarvis from disk: Error: host.iobroker: Cannot uninstall iobroker.jarvis: 216
ERROR: You might have to delete it yourself!
process exited with code 0

```

**Comment by Zefau** [comment]
@DanielWeeber did you solve this meanwhile? (Un)Installation is done by ioBroker and has nothing to do with the adapter (jarvis) itself.
