### ISSUE TITLE
Page size is calculated wrong

### ISSUE THREAD

**Issue by simonssoftware** [Zefau/ioBroker.jarvis#406]
**Prerequisites**
- [x] Are you on the latest stable or latest beta of jarvis?
- [ ] Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Versions**
- Which jarvis version are you running: v2.0.0-rc.1
- Please provide your `Support-ID` (in jarvis via Settings -> Help): Not available...

**Describe the bug**
Scrolling is enabled even if there is enough space for the widget(s).

**Expected behavior**
Scrolling will be disabled when the widget(s) have enough space.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50638485/101062353-d5e4be00-3591-11eb-844f-3cbe9ae57b85.png)

**Comment by uwe72** [comment]
Thank you for reporting. I have the same problem.

**Comment by Zefau** [comment]
Please try `2.0.0-rc.3` from Github (via installation via URL https://github.com/Zefau/ioBroker.jarvis/tarball/v2.0.x).

**Comment by uwe72** [comment]
Works very nice now with 2.0.0-rc.3. Just tested. Thanks!!

**Comment by simonssoftware** [comment]
I can only confirm uwe72, works as expected thanks :+1:
