### ISSUE TITLE
Automatic refresh breaks an iFrame

### ISSUE THREAD

**Issue by simonssoftware** [Zefau/ioBroker.jarvis#407]
**Prerequisites**
- [x] Are you on the latest stable or latest beta of jarvis?
- [ ] Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Versions**
- Which jarvis version are you running: v2.0.0-rc1
- Please provide your `Support-ID` (in jarvis via Settings -> Help): Not available...

**Describe the bug**
After an automatic refresh of an iFrame a new parameter "&_=" (I think it's a timestamp?) is added to the src tag.
Example:
Before refresh:
https://www.google.com/maps/embed/v1/directions?key=APIKEY&origin=48.1548895,11.4717969&destination=50.9576819,6.8972835

After refresh:
https://www.google.com/maps/embed/v1/directions?key=APIKEY&origin=48.1548895,11.4717969&destination=50.9576819,6.8972835&_=1607018587759

In my case the google api throws the error "Google Maps Platform rejected your request. Invalid request. Unexpected parameter '_'."

**Expected behavior**
Don't add the parameter &_= to the src tag on refresh.

**Screenshots**

**Comment by Zefau** [comment]
It will not refresh without changing the URL. The alternative is not re-render the iFrame itself, which looks buggy, because it will disappear and re-appear within a short time.

**Comment by Zefau** [comment]
Does the URL work for you with a `#` instead?

**Comment by simonssoftware** [comment]
I have just added a '#' instead of a '_' to the URL that it looks like "https://www.google.com/maps/embed/v1/directions?key=API_KEY&origin=48.1548895,11.4717969&destination=50.9576819,6.8972835&#=1607160859063" after an refresh and it works!

**Comment by Zefau** [comment]
resolved with `v2.1.0-beta.1`.

**Comment by Zefau** [comment]
Could you test that with `v2.1.0-beta.1` ? If that is successful, I will adapt it in `v2.0.0`.

**Comment by simonssoftware** [comment]
The request to the google api is now working, but I don't know if the iFrame is reloaded. 
I tried it with a mini html site, which only displays the current time

```
<html>
    <body>
        <p id="date"></p>
        <script>
            n =  new Date();
            document.getElementById("date").innerHTML = n.toString();
        </script>
    </body>
</html>
```

and the time is not updated. So I think the iFrame is not reloaded.

I saw you only add an '#' sign to the url and i've tested it with the '#' sign as a parameter (&#=), was that on purpose?
But I also think that it was just luck that the Google API accepts the parameter '#'.

**Comment by Zefau** [comment]
Could you check and verify with `v2.1.0-beta.2` ?

**Comment by Zefau** [comment]
@simonssoftware

**Comment by simonssoftware** [comment]
Yes, it works! Thank you! 👍
