### ISSUE TITLE
ToogleMode for ButtonAction / IconButtonAction

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#408]
Wäre schön wenn man ne Art toggle machen könnte mit dem IconStateButton.

d.h. Klick->ein, wenn ein Klick -> aus. 

![image](https://user-images.githubusercontent.com/22169074/101078917-169b0200-35a7-11eb-94f2-d6bea8e5fecf.png)

**Comment by Zefau** [comment]
Dafür ist der SwitchAction gedacht

**Comment by ma-gu-16** [comment]
> Dafür ist der SwitchAction gedacht

ja klar, dann wäre es schön wenn man anstelle des switches 2 icons hinterlegen könnte, true == on icon //  off== off icon 
ähnlich dem power icons, actives bzw inactives icon oder evtl farbe.

**Comment by Zefau** [comment]
@ma-gu-16 sollte mit v3 nun möglich sein

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.70`
Wo kann es einstellen? z.B. IconButtonAction, müsste da nicht ein extra-Toggleschalter sein?
![image](https://user-images.githubusercontent.com/84818934/132381667-c9b664d7-cbea-4049-a4be-7037f81edb06.png)

**Comment by Zefau** [comment]
Wahrscheinlich hab ich den Feature Request nicht verstanden. ToggleMode bedeutet an + aus. Das geht mit den Buttons nun. Entweder an oder - wenn an - dann aus. Mit v2 ging ja nur an.

**Comment by mcuiobroker** [comment]
mit v2 ging nur an, wo ist in v3 jetzt der "toggle"-Unterschied?
Also im Detail, vielleicht hab ich es noch nicht verstanden:
Statwert= true
ButtonAction als Taster eingestellt ->  
Klicke auf Button -> true
Klicke auf Button -> true
? Wodurch wird der Button jetzt umgestellt auf Toggle, damit ich beim nächsten Klick ein False bekomme,wenn Statewert vorher true war?
Mach ich das in den DP-Eigenschaften?

**Comment by Zefau** [comment]
Muss ich es wohl auch nochmal testen.

Beim Button Klick vergleicht jarvis den Datenpunkt Wert mit den Geräten Eigenschaften `on` (also `true` im default) und schaltet dann entweder `off` oder `on`.

**Comment by Zefau** [comment]
Der Taster schaltet ebenfalls nach der Logik und nach dem Schalten (nach 500ms) aber wieder auf den vorherigen Wert zurück.

**Comment by Zefau** [comment]
> Die Labelwerte stimmen aber im toggle Modus nicht
Wenn das Gerät aus ist, steht im Label turn off

Ist Geschmackssache oder? Ne nachdem ob das Label den aktuellen oder den Ziel Zustand beschreibt.

Siehe auch Diskussion hier https://github.com/Zefau/ioBroker.jarvis/issues/926#issuecomment-911070966

**Comment by ma-gu-16** [comment]
Hi , 

ich habe nun auch mal v3 installiert. Mir ist das mit dem Button nicht ganz klar. 

Mein Verständnis ist: 
Taster = senden bei klick immer true oder immer false, je nach dem was man möchte. 
und ein Schalter = schaltet true und wenn bereits true dann false und wenn false dann wieder true. (wie du es bereits hast, entweder via abfrage des datenpunktes oder interner value).

Sehe ich das falsch? Evtl könnte man auch die Labels Taster/Schalter nutzen wie bei der Elektroinstallation. 

Wie konfiguriere ich den in der aktuellen Version einen Taster, der immer TRUE sendet wenn ich klicke, egal welchen State irgendetwas hat. 

Danke.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/discussions/1175
