### ISSUE TITLE
Jalousien Action doppelte Werte

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#409]
Kann man diese doppelten Prozentzahlen entfernen, oder ist das ein BUG ? 

![image](https://user-images.githubusercontent.com/22169074/101093508-29b7cd00-35bb-11eb-8e14-032abde7c095.png)

Danke dir. 
Gruss

**Comment by Zefau** [comment]
is fixed with `rc-3`.

**Comment by ma-gu-16** [comment]
danke dir :-) Wird immer geiler Jarvis !

**Comment by ma-gu-16** [comment]
Leider noch nicht 100%, in der Detailansicht passt der Slider nicht ganz. 

![image](https://user-images.githubusercontent.com/22169074/101283289-b0e28c00-37d9-11eb-8a61-5fc4658713a9.png)

**Comment by Zefau** [comment]
please override your installation with the most recent `v2.0.0-rc.3` (even though you're on rc-3 already, please override). This should resolve this design issue.

**Comment by ma-gu-16** [comment]
Hi, still same issue. 

i just reinstalled via iobroker (github)
im on 2.1.0-beta-2

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/451
