### ISSUE TITLE
Newly created devices / states are not directly available in widget configuration

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#41]
Currently, the newly created devices and states must be saved (which includes a page reload) before being available in the Layout / Widget configuration.
Devices and states shall directly be usable without the necessity of saving.

**Comment by Zefau** [comment]
Fixed with `1.0.0-beta.9`. @braindead1 Could you cross check this one as well? thanks!

**Comment by braindead1** [comment]
This is working in `v1.0,0-beta-9`

**Comment by Zefau** [comment]
162b6769f42e873cb8f671603947645e9e8c0f6f
