### ISSUE TITLE
SQL History

### ISSUE THREAD

**Issue by balzreber** [Zefau/ioBroker.jarvis#410]
Hi there.
First: Great adapter. Thanks very much for your work.
Quick question: Are you still planning on implementing SQL History support in V2?
According to Issue #374 you do, but I couldn't find any more info on this. And issue #374 is closed and labeled "wontfix".

**Comment by Zefau** [comment]
History, InfluxDB and SQL are supported with v2.0.0 for. 

Do you have issues within jarvis using SQL as history adapter ?

**Comment by Zefau** [comment]
`wontfix` is meant for v1.0.x, as that is the version used by the author of the issue.

Later in the issue I'm stating:
> The upcoming v2.0.0 (v1.1.x-beta.xx in Github) additionally supports InfluxDb and sql with any instance.

**Comment by balzreber** [comment]
Oh, sorry, I didn't get that this is already implemented. I didn't find it in the feature list. Just installed v2.0.0-rc1. But it doesn't seem to work. I don't get the "missing data" message anymore, but the graph loads to infinity. Do I have to specify anywhere in jarvis that I want to use SQL? Or does it automatically detect if I have History or Sql activated for a given value?

**Comment by Zefau** [comment]
Please try `2.0.0-rc.3` from Github (via installation via URL https://github.com/Zefau/ioBroker.jarvis/tarball/v2.0.x).

**Comment by balzreber** [comment]
I can confirm that it works with 2.0.0.-rc.3. Thank you so much!
