### ISSUE TITLE
Meta Theme Color mit Primärer Farbe belegen

### ISSUE THREAD

**Issue by Bjoern3003** [Zefau/ioBroker.jarvis#411]
Wäre es möglich, dass der Meta Tag mit eingebaut wird und dort der primäre Farbcode benutzt wird?

`<meta name="theme-color" content="">`

Sieht auf den Smartphones einfach schicker aus, wenn die Topbar auch entsprechend im Schema der Seite eingefärbt ist.

**Comment by Zefau** [comment]
added with `v2.1.0-beta.2`.

**Comment by Bjoern3003** [comment]
Perfekt. Funktioniert. 👍
