### ISSUE TITLE
DisplayImage == iobroker state

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#413]
wäre ganz praktisch wenn man beim displayImage, neben base64,url, auch einen iobroker state angeben kann in welchem beispielsweise eine http url zu einem bild steht. 

z.b. handhabt der synology adapter das so, alle mpeg streams als states.

gruss

**Comment by Zefau** [comment]
Das ist bereits möglich.

**Comment by ma-gu-16** [comment]
> Das ist bereits möglich

korrekt, steht sogar im label :-)
Hätte wetten können das war eben nicht da, haha

Danke dir :-)
