### ISSUE TITLE
Support import of more devices from ioBroker.hm-rpc

### ISSUE THREAD

**Issue by Buddinski88** [Zefau/ioBroker.jarvis#414]
Hi Zefau,

thanks for the great adapter! 👍 

You said we can contact you, if devices don't yet have a configuration for automatic import.
I use a lot of Homematic, also do-it-yourself actuators (AsksinPP).

Could you include the following devices in Jarvis?

Model: HM-LC-Sw1-DR
Type: Switch used for lights or powerplugs
Datapoints: 0.UNREACH, 1.STATE

Model: HM-Sec-SD-2
Type: Smoke detector
Datapoints: 0.UNREACH, 0.LOWBAT, 1.STATE

Model: HM-WDS40-TH-I
Type: Temperature and Air humidity
Datapoints: 0.UNREACH, 1.TEMPERATURE, 1.HUMIDITY

Model: HM-Sen-MDIR-O-2
Type: Motion detector
Datapoints: 0.UNREACH, 1.BRIGHTNESS, 1.MOTION

Model: HM-Sec-Key
Type: Door lock
Datapoints: 0.UNREACH, 0.LOWBAT, 1.ERROR, 1.OPEN

Model: HM-PB-2-WM55
Type: Switch
Datapoints: 0.UNREACH, 0.LOWBAT, 1.PRESS_LONG, 1.PRESS_SHORT, 2.PRESS_LONG, 2.PRESS_SHORT

Model: HM-WDS30-OT2-SM
Type: Temperature
Datapoints: 0.UNREACH, 0.LOWBAT, 1.TEMPERATURE, 2.TEMPERATURE

Model: HB-UNI-SenAct-4-4-RC
Type: Switch
Datapoints: 0.UNREACH, 1.STATE, 2.STATE, 3.STATE, 4.STATE, 5PRESS_LONG, 5.PRESS_SHORT, 6.PRESS_LONG, 6.PRESS_SHORT, 7.PRESS_LONG, 7.PRESS_SHORT, 8.PRESS_LONG, 8.PRESS_SHORT

**Comment by Zefau** [comment]
added with `v2.1.0-beta.1`.

**Comment by Zefau** [comment]
@Buddinski88 passt der Import der neuen Geräte soweit?

**Comment by Zefau** [comment]
@Buddinski88

**Comment by Buddinski88** [comment]
@Zefau, sorry für die späte Rückmeldung, ich bin leider nicht früher dazugekommen. Folgende Gerätetypen werden noch nicht richtig importiert:

**HM-Sec-SD-2**
- Sie werden dem richtigen Gewerk "Rauchmelder" zugeordnet
- Es werden **keine States** angezeigt
![image](https://user-images.githubusercontent.com/50332516/103334037-57841a80-4a70-11eb-8004-3b81ade208df.png)

**HM-Sec-Key**
- Sie werden dem richtigen Gewerk "Tür" zugeordnet
- Es wird **nur** der **State unreach angezeigt**, **0.LOWBAT, 1.ERROR, 1.OPEN fehlen**
![image](https://user-images.githubusercontent.com/50332516/103334324-2526ed00-4a71-11eb-9711-c2b545cf62ca.png)

**HM-PB-2-WM55**
- Werden dem **Gewerk other** zugeordnet und **nicht Switch/Taster**
- Der **State Lowbat fehlt** noch
![image](https://user-images.githubusercontent.com/50332516/103334446-9797cd00-4a71-11eb-9deb-405020197ba8.png)

**HM-WDS30-OT2-SM**
- Werden dem richtigen Gewerk Heizung zugeordnet
- Der **State Lowbat fehlt** noch
![image](https://user-images.githubusercontent.com/50332516/103334488-c6ae3e80-4a71-11eb-8556-6bf0e00067b4.png)

**HB-UNI-SenAct-4-4-RC**
- Werden dem **Gewerk other** zugeordnet und **nicht Switch/Taster**
![image](https://user-images.githubusercontent.com/50332516/103334531-fcebbe00-4a71-11eb-89a5-8df7439f897e.png)

**Comment by Buddinski88** [comment]
@Zefau, bitte noch mal überprüfen/korrigieren. Ich danke dir.

**Comment by Zefau** [comment]
Kannst du nochmal mit `v2.1.0-beta.34` prüfen bitte?

Anmerkung: Es gibt kein Gewerk "Switch/Taster", daher ist es Sonstiges (other) zugeordnet. Außerdem waren die Gewerke in der Geräte-Liste nicht übersetzt - das habe ich nun korrigiert.

**Comment by Buddinski88** [comment]
@Zefau, hab es eben geprüft (2.1.0-beta.34):

**HM-Sec-SD-2**, **HM-Sec-Key**, **HM-PB-2-WM55**, **HM-WDS30-OT2-SM**, **HB-UNI-SenAct-4-4-RC**
- _No correct defined states found. The device may be unknown. Please help the developer to add support for this device and report to Github._

Sprich nun werden alle der genannten Typen nicht mehr erkannt.

**Comment by Zefau** [comment]
@Buddinski88 Kannst du nochmal mit `v2.1.0-rc.2` prüfen?

**Comment by Buddinski88** [comment]
@Zefau, eben getestet mit `v2.1.0-rc.2`

**HM-Sec-Key**, **HM-PB-2-WM55**
- Hier fehlt noch noch der 0.LOWBAT State

**HB-UNI-SenAct-4-4-RC**
- Hier fehlen wieder alle States, außer config, uncreach und connectivity
![image](https://user-images.githubusercontent.com/50332516/103396306-b27e4600-4b32-11eb-9e89-5345b802dd9a.png)
- Waren zuvor: 0.UNREACH, 1.STATE, 2.STATE, 3.STATE, 4.STATE, 5PRESS_LONG, 5.PRESS_SHORT, 6.PRESS_LONG, 6.PRESS_SHORT, 7.PRESS_LONG, 7.PRESS_SHORT, 8.PRESS_LONG, 8.PRESS_SHORT

**Comment by Zefau** [comment]
Danke für die Geduld. Probiere bitte nochmal mit `v2.1.0-rc.3`.

**Comment by Buddinski88** [comment]
@Zefau ich danke für deine Mühen. Leider werden nun alle Homematic-Geräte unter dem Punkt "Geräte mit inkorrekter Konfiguration (Datenpunkte nicht gefunden)" aufgeführt.

**Comment by Zefau** [comment]
Kannst du nochmal mit `2.1.0-rc.5` probieren?

**Comment by Buddinski88** [comment]
**HM-Sec-SD-2**,  **HM-PB-2-WM55**
- Grundsätzlich soweit in Ordnung, aber eine Frage: Der State LOWBAT gibt in ioBroker True/False zurück. JARVIS verwendest momentan den State LOWBAT_ALARM, welcher "NO ALARM(0) ALARM(1),ACKNOWLEDGED(2). Warum kein LOWBAT?

![image](https://user-images.githubusercontent.com/50332516/103464548-d4471b00-4d34-11eb-92d0-ed22a4572884.png)

**HM-Sec-Key**
- _No correct defined states found. The device may be unknown. Please help the developer to add support for this device and report to Github._

Frage: Mir sind noch zwei weitere Gerätetypen aufgefallen (sorry habe ich übersehen), welche nicht importiert werden können. Soll ich diese in einem neuen Ticket eintragen oder reicht es hier?

Model: HM-ES-PMSw1-DR
Type: Power with measuring
Datapoints: 0.UNREACH, 1.STATE, 1.CURRENT, 1.ENERGY_COUNTER,1.FREQUENZY, 1.POWER, 1.VOLTAGE

![image](https://user-images.githubusercontent.com/50332516/103464748-68fe4880-4d36-11eb-8c08-3d0dac1327f6.png)


Model: HM-PB-6-WM55
Type: Switch
Datapoints: 0.UNREACH, 0.LOWBAT, 1.PRESS_LONG, 1.PRESS_SHORT, 2.PRESS_LONG, 2.PRESS_SHORT, 3.PRESS_LONG, 3.PRESS_SHORT, 4.PRESS_LONG, 4.PRESS_SHORT, 5.PRESS_LONG, 5.PRESS_SHORT, 6.PRESS_LONG, 6.PRESS_SHORT

**Comment by SevenUp666** [comment]
ich habe 6 weitere Homematic-Geräte gefunden, die in jarvis noch nicht erkannt werden.
Da ich in jarvis recht frisch bin, kann ich nicht genau abschätzen, welche Datenpunkte hier wichtig und interessant sind. Deshalb stelle ich hier die Screenshots und json-Exporte rein.

**[json-Exporte](https://filehorst.de/d/dCtyHcBJ)**

**HmIP-SWD - [Wassermelder](https://de.elv.com/homematic-ip-wassersensor-hmip-swd-ip44-151694?fs=405470823)**
[![Bild 2021-01-0421_01_59-ob8xkyz.png auf abload.de](https://abload.de/img/2021-01-0421_01_59-ob8xkyz.png)](https://abload.de/image.php?img=2021-01-0421_01_59-ob8xkyz.png)


**HmIP-FSM - [Schalt-Mess-Aktor](https://de.elv.com/homematic-ip-schalt-mess-aktor-hmip-fsm-5-a-unterputz-142721)**
[![Bild 2021-01-0421_09_46-obzvjwg.png auf abload.de](https://abload.de/img/2021-01-0421_09_46-obzvjwg.png)](https://abload.de/image.php?img=2021-01-0421_09_46-obzvjwg.png)
[![Bild 2021-01-0421_11_06-ob2wkpp.png auf abload.de](https://abload.de/img/2021-01-0421_11_06-ob2wkpp.png)](https://abload.de/image.php?img=2021-01-0421_11_06-ob2wkpp.png)


**HmIP-SLO - [Lichtsensor außen](https://de.elv.com/homematic-ip-lichtsensor-hmip-slo-aussen-fertiggeraet-151566?fs=651822690)**
[![Bild 2021-01-0421_14_21-obtijmb.png auf abload.de](https://abload.de/img/2021-01-0421_14_21-obtijmb.png)](https://abload.de/image.php?img=2021-01-0421_14_21-obtijmb.png)


**HmIP-SWDM - [Fenster- und Türkontakt mit Magnet](https://de.elv.com/homematic-ip-fenster-und-tuerkontakt-mit-magnet-hmip-swdm-151363?fs=3747862501)**
[![Bild 2021-01-0421_18_27-ob0yjbd.png auf abload.de](https://abload.de/img/2021-01-0421_18_27-ob0yjbd.png)](https://abload.de/image.php?img=2021-01-0421_18_27-ob0yjbd.png)


**HMIP-WTH / HMIP-WTH-2 - [Wandthermostat mit Luftfeuchtigkeitssensor](https://de.elv.com/homematic-ip-wandthermostat-hmip-wth-2-mit-luftfeuchtigkeitssensor-wth-2-fuer-smart-home-hausautomation-143159?fs=281668337)**
[![Bild 2021-01-0421_20_13-obh7kuu.png auf abload.de](https://abload.de/img/2021-01-0421_20_13-obh7kuu.png)](https://abload.de/image.php?img=2021-01-0421_20_13-obh7kuu.png)
[![Bild 2021-01-0421_20_26-obyzka1.png auf abload.de](https://abload.de/img/2021-01-0421_20_26-obyzka1.png)](https://abload.de/image.php?img=2021-01-0421_20_26-obyzka1.png)


**HM-RC-2-PBU-FM - [Funk-Sender 2-fach für Markenschalter](https://de.elv.com/elv-homematic-komplettbausatz-funk-sender-2-fach-fuer-markenschalter-230-v-unterputzmontage-kein-aktor-hm-rc-2-pbu-fm-fuer-smart-home-hausautomation-140906?fs=2037852388)**
[![Bild 2021-01-0421_37_40-obyrjue.png auf abload.de](https://abload.de/img/2021-01-0421_37_40-obyrjue.png)](https://abload.de/image.php?img=2021-01-0421_37_40-obyrjue.png)

**Comment by Zefau** [comment]
@Buddinski88 mit `2.2.0-beta.6`:
- HM-Sec-SD-2, HM-PB-2-WM55 sollte nun auch den LOWBAT haben.
- HM-Sec-Key sollte jetzt passen
- die zwei neuen Geräte sollten mit drin sein

**Comment by Zefau** [comment]
@SevenUp666 mit `2.2.0-beta.6` sollten auch deine Geräte entsprechend gefunden werden. Danke dir für die Zusammenstellung.

**Comment by SevenUp666** [comment]
> @SevenUp666 mit `2.2.0-beta.6` sollten auch deine Geräte entsprechend gefunden werden. Danke dir für die Zusammenstellung.

vielen Dank für die schnelle Umsetzung! Die Geräte sind drin.

**Comment by Buddinski88** [comment]
> @Buddinski88 mit `2.2.0-beta.6`:
> 
> * HM-Sec-SD-2, HM-PB-2-WM55 sollte nun auch den LOWBAT haben.
> * HM-Sec-Key sollte jetzt passen
> * die zwei neuen Geräte sollten mit drin sein

Danke dir @Zefau 👍 
Hab es eben getestet und nun werden die Geräte mit den richtigen States importiert und angelegt.
Ich schließe das Ticket somit mal.
