### ISSUE TITLE
Hide Setupicon on Tablet

### ISSUE THREAD

**Issue by kwittwer** [Zefau/ioBroker.jarvis#415]
Hey, is it possible to hide the Setupicon also on Tablets? I use an fire HD 8 in landscape mode and I would like to hide the Icons on top right corner. How can I do this? 
Regards

**Comment by Zefau** [comment]
Should be hidden on tablets with `v2.1.0-beta.2`.

**Comment by ma-gu-16** [comment]
v2.1.0-beta.16 , Samsung Galaxy TAB A - 10.1 zoll ist es nicht der Fall ;-)

**Comment by Zefau** [comment]
Ist was nicht der Fall? Bitte konkret benennen, sonst entstehen Missverständnisse. Du meinst, dass Icon ist noch immer zu sehen auf dem Tablet?

Das Icon wird bei einer Auflösung von 960px und weniger versteckt (Breakpoint `md`, siehe auch https://material-ui.com/customization/breakpoints/).

**Comment by ma-gu-16** [comment]
Genau das Icon, darum ging es ja hier ;-) 

Ok, der Breakpoint ist halt wirklich gering wie ich finde. Zumal die Auflösungen von neueren Tablets immer Grösser und besser werden. 

Evtl via JS checken ob es ein Device ist? 
```
const userAgent = navigator.userAgent.toLowerCase();
const isTablet = /(ipad|tablet|(android(?!.*mobile))|(windows(?!.*phone)(.*touch))|kindle|playbook|silk|(puffin(?!.*(IP|AP|WP))))/.test(userAgent);
```

**Comment by Zefau** [comment]
Sollte mit `2.1.0-beta.17` nun passen.

**Comment by ma-gu-16** [comment]
korrekt ist weg. 
Ich denke mal dein Herzchen willst du via PRO Version entfernen ;-) Man könnte sich so die oberste Zeile komplett sparen. 
Evtl das Herzchen rechts und die Navigation 50px weniger breit ? 

Gruss

**Comment by Zefau** [comment]
Dafür gibt es ein Feature Request. Ist mir etwas Arbeit verbunden.

**Comment by kaip2503** [comment]
Bei mir wird das Icon in Beta 19 auf meinem MacBook Air M1 nicht mehr angezeigt. Browser: Chrome und Safari getestet.

**Comment by Zefau** [comment]
fixed with `v2.1.0-beta.21`.

**Comment by kaip2503** [comment]
Auch mit beta 21 wird nach wie vor das Icon für die Config nicht angezeigt. Ich sehe nur das Herz.  Sowohl im Vollbildmodus, als auch vergrößertem Fenster ausprobiert.

**Comment by kwittwer** [comment]
Hi, also auf meinem Fire HD 8 werden beide Icons immer noch angezeigt (ich benutze das ganze im Querformat).

**Comment by Zefau** [comment]
hopefully resolved with `v2.1.0-beta.22`.

**Comment by kaip2503** [comment]
Klappt bei mir jetzt auf dem Macbook. Setup Icon wird wieder angezeigt. Am Tab A von Samsung wird es korrekterweise ausgeblendet.
