### ISSUE TITLE
Formatieren von Werten via Formeln / Callback function

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#416]
Hi, 

ist es möglich Werte zu formatieren ? 

![image](https://user-images.githubusercontent.com/22169074/101265435-c35fb580-3746-11eb-8881-8f3bdc7a638f.png)

zb. WetterStation zeigt die Sonnenscheindauer an , vermutlich in Sekunden, wär schön wenn man evtl im json, eine Formel mitgeben kann. Oder irgendwo einstellen das es Sekunden sind und diese in Stunden haben möchte. 

Vielleicht auch wie viele Nachkommastellen. 

Oder zu spezifisch ? man könnte es natürlich auch im iobroker mittels script lösen. 

Grüsse

**Comment by Zefau** [comment]
added with `v2.2.0-beta.46`.

Usage: Provide a callback function via state properties (Datenpunkt Eigenschaften) using `value` key, e.g.:

![image](https://user-images.githubusercontent.com/14368811/108589689-e1a97a80-735f-11eb-918c-adf835f93d92.png)

![image](https://user-images.githubusercontent.com/14368811/108589695-ea9a4c00-735f-11eb-81a9-2c1f6d06f4d1.png)

This example is an arrow function, which only uses the first param, which is `val` (raw state value).
Available params are (in the following order):
1. raw value (`mixed`, depending on the state either `string`, `number`, `boolean`, etc.)
2. full state (including `val`, `ts`, `lc`, etc.; as object)
3. all states of the device (as object)
4. device object

**Comment by Zefau** [comment]
@ma-gu-16 Beispiel zur Konvertierung von Sekunden zu Stunden (ungetestet):
```
{
  "value": "val => Math.round(parseInt(val)/3600)"
}
```

**Comment by mcuiobroker** [comment]
Wie muss die Funktion denn aussehen, wenn man ein Geräteobjekt mit nutzen möchte und dessen Wert?
![image](https://user-images.githubusercontent.com/84818934/132408527-9d09b3af-f164-45a8-a40a-cd177f1f1c6e.png)
![image](https://user-images.githubusercontent.com/84818934/132408556-580e0495-8527-46cd-af9a-ccb52960d19f.png)

**Comment by Zefau** [comment]
```
{
  "value": "(val, state, states, device) => {
      console.log(val, state, states, device);
      return val;
   }
}
```

Dann siehst du die 4 Einträge in der Konsole.

**Comment by Kaskadeur111** [comment]
Also ich bekomme es nicht hin.

Ich möchte einfach nur einen Minutenwert in Stunden umrechnen.

dazu habe ich

{
  "value": "val => parseInt(val)/60"
}

oder auch 

{
  "value": "val => val/60"
}

als Datenpunkt EIgenschaft hinterlegt... es passiert leider garnichts. der Wert wird unverändert ausgegeben.

Was mach ich falsch? Hilfe :-)

**Comment by Zefau** [comment]
Sieht richtig aus. Bist du Pro?

**Comment by Kaskadeur111** [comment]
Danke. Nein bin ich noch nicht. Im Kopf schon, es kommen täglich Sachen dazu die ein Pro unumgänglich machen ;-).
Am 3. Jan. 2022, 16:44 +0100 schrieb Zefau ***@***.***>:

**Comment by JayBa31** [comment]
> @ma-gu-16 Beispiel zur Konvertierung von Sekunden zu Stunden (ungetestet):
> 
> ```
> {
>   "value": "val => Math.round(parseInt(val)/3600)"
> }
> ```
Klappt super. Kannst du mir verraten wie ich das auf 2 Dezimalstellen erweitere?

**Comment by Zefau** [comment]
`.toFixed(2)`:
```
{
  "value": "val => Math.round(parseInt(val)/3600).toFixed(2)"
}
```

**Comment by IggePop** [comment]
> `.toFixed(2)`:
> 
> ```
> {
>   "value": "val => Math.round(parseInt(val)/3600).toFixed(2)"
> }
> ```

Leider nicht ganz. Math.round rundet immer auf Ganzzahlen auf/ab. toFixed ändert daran nichts.

So geht es:

```
{
  "value": "val => Math.round(parseInt(val)/3600 * 100)/100"
}
```
