### ISSUE TITLE
Grid: Zeilen über mehrere Spalten

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#417]
Wäre cool, wenn man das bestimmte Widgets über 2 Spalten machen könnte und darunter wieder 2-Spaltig weiter. 

Grüsse

**Comment by Zefau** [comment]
Do you mean https://github.com/Zefau/ioBroker.jarvis/issues/129 ?

**Comment by ma-gu-16** [comment]
yep :)
