### ISSUE TITLE
Object Object 

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#419]
Beim Datenpunkt. 

![image](https://user-images.githubusercontent.com/22169074/101266008-ab3e6500-374b-11eb-8c66-7038259f90e4.png)

Habe die aktuellste Version.

**Comment by Zefau** [comment]
Was sind denn die aktuellste Version? ;-) rc-2, rc-3oder beta-1?

**Comment by Zefau** [comment]
Und was konkret hast du gemacht, dass das entstand?

**Comment by ma-gu-16** [comment]
![image](https://user-images.githubusercontent.com/22169074/101267831-936fdc80-375d-11eb-8ad4-b9321a9437d1.png)

![image](https://user-images.githubusercontent.com/22169074/101267861-dcc02c00-375d-11eb-84bb-d83f45f08c1a.png)

Habe von 2.0. rc1 update gemacht und dann ist mir das bei dem Datenpunkt aufgefallen. Es betrifft aber nur  Geräte die wie s.o. konfiguriert sind. Alle anderen scheinen i.o.

**Comment by Zefau** [comment]
Kannst du mal das `raw` (Expertenansicht) des Geräts zur Verfügung stellen?

**Comment by ma-gu-16** [comment]
Oh sorry, hab die datenpunkte bereits neu gesetzt und gespeichert. Werde ich beim nächsten mal.

Gruss

**Comment by ma-gu-16** [comment]
und da ist wieder Fehler. Bei einem Sonoff Gerät, selbst angelegt. 

![image](https://user-images.githubusercontent.com/22169074/103105567-f0f59b80-462e-11eb-91a4-648902bb7057.png)

RAW: 
```

"kueche_ee162": {
    "id": "kueche_ee162",
    "name": "Küchen Rückwand",
    "function": "light",
    "states": {
      "power": {
        "state": {
          "node": "sonoff.0.kueche.POWER"
        },
        "action": "sonoff.0.kueche.POWER",
        "actionElement": "SwitchAction",
        "label": "an / aus",
        "icon": "",
        "IconButtonActionConfig": {
          "showState": false
        },
        "bodyElement": null
      },
      "dimmer": {
        "state": {
          "node": "sonoff.0.kueche.Dimmer"
        },
        "action": "sonoff.0.kueche.Dimmer",
        "unit": "",
        "label": "Dimmer",
        "icon": {},
        "LevelBodyConfig": {
          "step": "10"
        }
      },
      "hue": {
        "state": {
          "node": "sonoff.0.kueche.Hue"
        },
        "action": "sonoff.0.kueche.Hue",
        "label": "Farbe",
        "icon": ""
      },
      "on": {
        "state": {
          "node": ""
        },
        "action": "sonoff.0.kueche.CW_POWER",
        "actionElement": "IconButtonAction",
        "label": "Weiss schalten",
        "icon": {
          "default": "palette"
        },
        "bodyElement": null
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Sonoff",
        "namespace": "sonoff"
      },
      "_created": 1606824239924,
      "_updated": 1606942256788
    }
  },
  
```

**Comment by ma-gu-16** [comment]
Der Datenpunkt scheint leer zu sein, naja gelöscht habe ich den mit Sicherheit nicht ;-) 

Ich hoffe das hilft dir ;-) ich speichere mal nicht falls du noch weitere Infos benötigst.

**Comment by Zefau** [comment]
Und der Fehler ist "neu"? Also vor kurzem war das Gerät noch korrekt gepflegt ? 

oder könnte das noch aus der Zeit von vor 18 Tagen sein, als wir das hatten?

**Comment by ma-gu-16** [comment]
Gute Frage, könnte natürlich auch schon älter sein, ist mir nur gerade aufgefallen, weil ich den Sonoffimport getestet habe. 

Sonst lassen wir das, ich setzte die Punkte alle neu und beobachte.

**Comment by Zefau** [comment]
Super, so machen wir das. Ich hatte beim letzten Mal ja intensiv geschaut und mir ist nicht so recht was eingefallen. Beobachte das gerne mit Geräten, die Stand heute ok sind.
