### ISSUE TITLE
Expertenmodus , 2. Ansicht plaintext

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#421]
Ich persönlich finde den neuen "editor" im Expertenmodus sehr umständlich. 
Übersicht ist super, aber zum Editieren oder neue Objekte z.b. Beispielcode einzufügen ist es sehr mühsam, da war der PLAINtext deutlich komfortabler. 

Wäre schön wenn man zwischen den Ansichten umschalten kann. 

Grüsse

**Comment by Zefau** [comment]
re-added with `v2.1.0-beta.4`.

**Comment by ma-gu-16** [comment]
Gut das man nun wechseln kann.

**Comment by cryptedx** [comment]
Kannst du dort auch den Darkmode bitte synchronisieren mit dem aktuell aktiven Design? Das killt mir die Augen. ;-)

![image](https://user-images.githubusercontent.com/20707078/102007889-fdbfe880-3d2c-11eb-8218-25ca12c5ad46.png)
