### ISSUE TITLE
Music Player

### ISSUE THREAD

**Issue by Jockelator** [Zefau/ioBroker.jarvis#423]
Is it possible to integrate a Music/Media Player with current cover, song, artist volume etc ?
Something like this for example: https://github.com/instalator/ioBroker.vis-players/blob/master/widgets/players/img/sonos.png

**Comment by ma-gu-16** [comment]
agree. esp. a SONOS compatible player widget would be awesome ;-)

**Comment by Zefau** [comment]
This is meant with https://github.com/Zefau/ioBroker.jarvis/issues/173
Please vote that up
