### ISSUE TITLE
V1.0.9 Problem beim Laden der Oberfläche

### ISSUE THREAD

**Issue by Piramos669** [Zefau/ioBroker.jarvis#425]
Hallo,

seit einer kleinen Änderung habe ich das Problem, dass die Oberfläche nicht mehr geladen wird.
Ich habe quasi nur noch eine graue Seite, so dass ich nicht einmal Änderung rückgängig machen kann. In der Adresszeile steht "*:8082/jarvis/index.html.

![Screenshot 2020-12-06 181358](https://user-images.githubusercontent.com/75580411/101287362-1f324900-37f0-11eb-9c0a-67c63fbe7794.jpg)
![Screenshot 2020-12-06 181413](https://user-images.githubusercontent.com/75580411/101287364-20fc0c80-37f0-11eb-8a74-68cb46554386.jpg)

Neustart des Adpaterbzw. des IoBrokers haben nichts geholfen.
Was kann ich noch machen? Ich will ungern den Adpater neu installieren und alles neu machen müssen.

Ich habe inzwischen eine zweite Insantz hinzugefügt & die erste pausiert. Auch mit der "frischen" Instanz habe ich das gleiche Ergebnis.

**Comment by Zefau** [comment]
Wäre dir dankbar, wenn du auf v2.0.0-rc.3 upgraden könntest. Damit wird es sicherlich funktionieren.

Zuvor gerne `jarvis.0.devices`, `jarvis.0.layout`, `jarvis.0.settings` in eine Textdatei speichern. Die 3 Datenpunkte enthalten alle deine jarvis Daten.

Alternativ kannst du mir sonst gerne (per ioBroker forum oder Discord) dein Layout schicken (`jarvis.0.layout`). Dann suche ich den Fehler und bereinige diesen.

**Comment by Piramos669** [comment]
Vielen Dank für die schnelle Hilfe! Es klappt wieder alles.
Mir war nicht klar, das es schon eine neuere Version gibt.
Morgen muss ich gleich mal schauen, was man da alles neues machen kann.
Der Adapter gefällt mir bisher sehr gut. 
Grüße und Danke
Sebastian
--
Gesendet über myMail für Android Sonntag, 06 Dezember 2020, 07:16PM +01:00 von Zefau  notifications@github.com :

**Comment by Zefau** [comment]
Siehe https://www.facebook.com/groups/440499112958264/?multi_permalinks=1363904557284377&notif_id=1606513647714960&notif_t=feedback_reaction_generic&ref=notif, falls du Facebook hast.

**Comment by Piramos669** [comment]
Facebook habe ich schon lange nicht mehr. Ich versuche im Forum dabei zu bleiben. 
Grüße
Sebastian
--
Gesendet über myMail für Android Sonntag, 06 Dezember 2020, 08:44PM +01:00 von Zefau  notifications@github.com :
