### ISSUE TITLE
Open Camera Stream in Popup

### ISSUE THREAD

**Issue by dabbeljuh22** [Zefau/ioBroker.jarvis#426]
I have one single tab with multiple camera streams embeddet via iFrame widget. The single views are a bit too small to see much details. Because of that I would like to open a chosen stream in a popup in full screen mode.

**Comment by Zefau** [comment]
Ist doppelt zu https://github.com/Zefau/ioBroker.jarvis/issues/292. Bitte für https://github.com/Zefau/ioBroker.jarvis/issues/292 voten.
