### ISSUE TITLE
StateList mit Popup Iframe Funktion

### ISSUE THREAD

**Issue by 7845258** [Zefau/ioBroker.jarvis#429]
Hi Zefau, 

Danke für den super coolen Adapter "Jarvis".

Im Moment realisiere ich meine Visualisierung mittels deinem Jarvis Adapter.

Was noch super cool wäre:

Wenn sich z.B. bei einer Temperaturanzeige (StateList) ein Popup mit Iframe Funktion öffnen liesse.

So könnte man z.B. im Popup ein Grafana Diagramm mit dem Temperaturverlauf anzeigen lassen.

**Comment by Zefau** [comment]
Thanks for your feature request. This is a duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/292 though. Thus, I will close this issue. Please vote for https://github.com/Zefau/ioBroker.jarvis/issues/292 instead.
