### ISSUE TITLE
Preview for the Action Elements in widget configuration

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#43]
- [x] Use (small) screenshots as a preview for the Action Elements (`SwitchAction`, `ButtonAction`, etc.) in the widget configuration
- [x] Only show actions which are valid for the device function

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/20

**Comment by Zefau** [comment]
Added with `1.0.0-beta.14`.
Breaking Change because Components were renamed:
- `HeatingSetTemperatureBody` to `LevelBody`
- `LightLevelAction` to `SwitchAction`
- `LightColorAction` to `LightColorState`
- `LightColorTemperatureBody` to `LightTemperatureBody`

@braindead1 Could you have a look at this?

**Comment by braindead1** [comment]
I have a clean installation of `v1.0.0-beta.14`. Importing of alias devices worked well. When I select a device in the widget configuration dialogue the screen turns gray and I get the following error messages in the console.

![image](https://user-images.githubusercontent.com/2136249/92329115-9cb9b200-f065-11ea-90b0-bf090a35dcba.png)

**Comment by Zefau** [comment]
True story. I wanted to change something and forgot about it. My bad.

**Comment by Zefau** [comment]
Could you check `1.0.0-beta.15` ? Thanks

**Comment by braindead1** [comment]
I have a clean installation of `v1.0.0-beta.15`. The import of alias devices works as expected.

After selecting a device in the widget configuration dialogue, the selection stays visible. Is this by intention? In previous versions the selection disappeared after selecting a device.

Besides that it's not possible to close the dialogue as "Übernehmen" is disabled.

![image](https://user-images.githubusercontent.com/2136249/92348963-fdcc9e80-f0d4-11ea-81b0-6f00b31470f4.png)

For testing puposes I then pasted my working JSON as expert into jarvis. The problem with the selection of devices remains, but "Übernehmen" is working.

The console shows the following messages, but the dialogue is working.

![image](https://user-images.githubusercontent.com/2136249/92349842-86e4d500-f0d7-11ea-869a-55f3a8bc1fa5.png)

I am able to set the body and trigger element and both is working as expected. By the way, the idea of including images is nice!

An issue that was introduced with (the not working) `v1.0.0-beta.14` remains: The slider and the label of the `setTemprature` state is not visible in the pop-up. I did not configure anything besides display and trigger states.

![image](https://user-images.githubusercontent.com/2136249/92349536-b3e4b800-f0d6-11ea-8025-90d47474e6c9.png)

**Comment by Zefau** [comment]
> After selecting a device in the widget configuration dialogue, the selection stays visible. Is this by intention? In previous versions the selection disappeared after selecting a device.

This is the wanted behavior now. This way its easier to add multiple devices quickly. Furthermore, you are able to search for a manufacturer (e.g. shelly) and get all respective devices.

> Besides that it's not possible to close the dialogue as "Übernehmen" is disabled.

- [ ] This is of course a bug. Have you filled in a title for the Widget box? That input is hidden behind the Dropdown. The button is disabled because a required field is not filled in correctly. Still a bug and I will have a look at that.

> The console shows the following messages, but the dialogue is working.

- [ ] A bug.

> An issue that was introduced with (the not working) v1.0.0-beta.14 remains: The slider and the label of the setTemprature state is not visible in the pop-up. I did not configure anything besides display and trigger states.

- [ ] This is due to the Breaking Chance I think. The component has been renamed. I probably did not rename it in the popup configuration. I will have a look at that.

**Comment by braindead1** [comment]
> This is the wanted behavior now. This way its easier to add multiple devices quickly. Furthermore, you are able to search for a manufacturer (e.g. shelly) and get all respective devices.

Great improvement!

> * [ ]  This is of course a bug. Have you filled in a title for the Widget box? That input is hidden behind the Dropdown. The button is disabled because a required field is not filled in correctly. Still a bug and I will have a look at that.

OMG I forgot to enter the title. Sorry. It's working as expected.

**Comment by Zefau** [comment]
Should be resolved with `1.0.0-beta.16`.

**Comment by braindead1** [comment]
In `v1.0.0-beta.17` all of the above is working as expected.
