### ISSUE TITLE
Zeiteinstellung auf Datum/Uhrzeit änderbar machen

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#430]
Hallo,

bitte die Zeiteinstellung auf Datum/Uhrzeit änderbar machen.

![Screenshot (2884)_LI](https://user-images.githubusercontent.com/41079106/101402673-57ab5300-38d4-11eb-8d18-a0bf22ed4169.jpg)

https://forum.iobroker.net/topic/30668/jarvis-v2-0-0-just-another-remarkable-vis/2151

**Comment by Zefau** [comment]
@sigi2345 added an option with `v2.1.0-beta.4`.

For each entry in the widget via component options:
![image](https://user-images.githubusercontent.com/14368811/101825151-8b34ea00-3b2d-11eb-9e36-a405d4326cb9.png)

or globally:
![image](https://user-images.githubusercontent.com/14368811/101825219-a0aa1400-3b2d-11eb-89a6-a08166f5a916.png)
