### ISSUE TITLE
Farben mit LightHueBody bzw. LightColorBody beim hue-extended sind falsch

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#431]
Die Option `Verwenden von XY anstelle von hue (nur für nicht-Philips-Geräte)` ist zu deaktivieren, siehe https://forum.iobroker.net/post/533641.

**Comment by TicoM1** [comment]
> Steht doch im Link, in den hue-extended-Instanzeinstellungen

Was ist hue-extended? Wo in Jarvis ist das?

**Comment by TicoM1** [comment]
Ich bin im Jarvis Issue tracker zu einem Jarvis feature. Von einem extra Adapter war gar keine Rede. Das ist ja das Problem. Der wurde hier einfach angenommen.
