### ISSUE TITLE
Wie konfiguriere ich ein Dropdown Feld?

### ISSUE THREAD

**Issue by aiko929** [Zefau/ioBroker.jarvis#432]
Wie kann ich einen bestimmten Text in das DropDown Feld packen dass dann einen bestimmten Wert in das ioBroker Objekt tut?

**Comment by Zefau** [comment]
Mittels Anzeigevariante in der Geräte Konfiguration, siehe https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#display
