### ISSUE TITLE
Calender-Widget zeigt keine wiederkehrenden Termine an

### ISSUE THREAD

**Issue by franky1966** [Zefau/ioBroker.jarvis#433]
Erst einmal vielen Dank für das tolle Modul. Ich verwende Jarvis in der aktuellen Version 2.0 und habe festgestellt, daß wenn ich das Calender-Widget verwende, nur einzelne Termine aus einer Kalenderdatei angezeigt werden. Sind im Kalender jedoch sich wiederholende Termine vorhanden, werden diese nicht angezeigt. 
Es wäre schön, wenn dies noch behoben werden könnte.

Grüße
Frank

**Comment by Zefau** [comment]
Die wiederkehrenden Termine habe ich bei der Implementierung schlicht vergessen.

Ich habe dies nun mit der `v2.1.0-beta.6` nachgezogen, allerdings ist diese Thematik äußerst komplex, da es viele Kombinationsmöglichkeiten umfasst (die ich hoffentlich alle abgedeckt habe):

- [x] unterschiedliche Typen: täglich, wöchentlich, monatlich, jährlich
- [x] unterschiedliche Intervalle (jeden Tag / Woche / Monat / Jahr oder jeden X (z. B. zweiten oder dritten) Tag / Woche / Monat / Jahr)
- [x] Wiederholung an beliebig kombinierbaren Wochentagen
- [x] unterschiedliche End-Angaben: endet niemals, endet nach X Wiederholungen, endet am bestimmten Datum

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/540356

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/542370
