### ISSUE TITLE
Alternative Anzeigewerte

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#434]
Hi,
die Werte gehen von -600 bis -100

![image](https://user-images.githubusercontent.com/22169074/101669846-be567b00-3a52-11eb-9b7c-cfbf65c34da6.png)

ist es möglich eine alternative Anzeige zu haben, also 0-100, die Werte aber die gleichen bleiben.
Habe es mit der Anzeige JSON versucht, aber scheint nicht zu greifen. Wie muss das JSON aussehen ? 

Danke dir.

**Comment by Zefau** [comment]
Nein, es können nur Werte des Wertebereichs angezeigt werden, der auch ausgewählt werden kann. In der Konfiguration wird ein min / max Wert angegeben, woraus der Slider berechnet wird. Im Slider selbst können noch die Stufen definiert werden. 

Was aber nicht geht ist ein Wertebereich für die Anzeige und ein anderer Wertebereich für die Selektion.

**Comment by ma-gu-16** [comment]
Das wäre ja evtl ein Feature für die Zukunft? 
Oder eher via ioBroker "umwandeln" ? 

Falls iobroker, kannst du das Ticket schliessen ;-) Danke dir.

**Comment by Zefau** [comment]
Kannst du mir den Use Case erläutern? Warum sollte ich auf z. B. 50 sliden und dann aber 220 (oder so) an ioBroker schicken?

**Comment by ma-gu-16** [comment]
Siehe den Screenshot, bei den Zahlen erkennt man ja nix ;-) und der Yamaha Adapter bzw Receiver arbeitet in diesem minus Bereich.  Ich hätte jetzt einen Slider 0-60 gemacht und die Werte -600  bis -100  oder so ;-)

**Comment by Zefau** [comment]
Du kannst -600 bis -100 machen und dann im Slider die `Schrittweite (Anzahl Markierungen)` auf 5 stellen oder so.

**Comment by ma-gu-16** [comment]
Ja klar, ist aber nicht so sexy ;-)  Ist okay ich löse es via scripts. Danke dir.
