### ISSUE TITLE
Anzeigefehler beim Wetterwidget

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#435]
Anzeigefehler beim Wetterwidget  ,meine Version: 2.1.0-beta.2

![image](https://user-images.githubusercontent.com/22169074/101670553-9c112d00-3a53-11eb-9038-808f94238903.png)

**Comment by Zefau** [comment]
@ma-gu-16 probier mal bitte `v2.1.0-beta.8`, ob es damit behoben ist.

**Comment by ma-gu-16** [comment]
![image](https://user-images.githubusercontent.com/22169074/102712027-560f6100-42be-11eb-9be5-99a0a826a289.png)

Sieht gut aus, evtl müsste man noch ein Alternatives Label bei geringem Breakpoint machen. Donnerstag ist schon ausserhalb. "Do" würde ja genügen.

**Comment by Zefau** [comment]
Ist auch so eingestellt, aber scheint bei dir nicht zu greifen. Was ist denn das für eine Auflösung ?

**Comment by ma-gu-16** [comment]
Ja hab ich grad gesehen, auf Mobile klappts. 
Auf Desktop im Browser ab 1280 ca.    sobald es 4 spaltig wird. 
Tablet ebenso nicht, 1280 × 800 Pixeln breite.  Samsung Galaxy Tab A 10.1 Zoll

**Comment by Zefau** [comment]
Versuch nochmal mit `2.1.0-beta.18` bitte.

**Comment by ma-gu-16** [comment]
Sieht deutlich besser aus. 

![image](https://user-images.githubusercontent.com/22169074/103105324-5f395e80-462d-11eb-8d21-7ea51034ffb7.png)

da noch ein kleines padding, damit früher ein Zeilenumbruch des Textes passiert und dann ist wohl TOP :-D

grüsse

**Comment by Zefau** [comment]
Du bist aber anspruchsvoll ;-) Passt es mit `v2.1.0-beta.19` ?

**Comment by ma-gu-16** [comment]
passt !. Danke
