### ISSUE TITLE
Navbar links und ggfl versteckt

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#436]
Wäre vielleicht gut wenn man die Topbar zu einer Seitennavigation wechseln könnte und diese fixed oder auch versteckt via Hamburger-Menu.

**Comment by Zefau** [comment]
Die Navigation links ist dem Drawer (https://github.com/Zefau/ioBroker.jarvis/issues/81) reserviert.

**Comment by Zefau** [comment]
Deine Beschreibung klingt auch nach einem Drawer, insofern vote das Issue gerne hoch.

**Comment by ma-gu-16** [comment]
Ja Drawer, links, oder rechts, versteckt oder fixed. Variable oder fixe breite.
