### ISSUE TITLE
Settings ausblenden

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#437]
Ich finde es noch wichtig wenn man das Zahnrad/Settings verstecken könnte oder gar das die Editview separat wäre.  

Hintergrund: Bei mir ist das Tablet im Wohnraum und auch zb. Gäste haben dort Zugriff. 
So kann ein "versehentliches" Umstellen vermieden werden. 

Was denkst du ?

**Comment by Zefau** [comment]
Ist https://github.com/Zefau/ioBroker.jarvis/issues/166 ggf. ausreichend ?

**Comment by KoMa1978** [comment]
Eins von beiden (oder beides) fände ich auch gut und sinnvoll

**Comment by ma-gu-16** [comment]
> Ist #166 ggf. ausreichend ?

Ich denke beides. Ich finde auch das diese Zeile eigentlich unnötig ist. und nur Höhe wegnimmt. Und von Höhe hat man ja eh zu wenig vor allem auf Mobile oder Tablet. ;-)

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.70`
Einstellungen können ja jetzt über ObjectID oder in den Tab-Einstellungen abgeschaltet werden. 
Zusätzlich sollte es aber eine ObjectID in ioBroker, die verhindert das man über die HTTP-Adresse auf die configuration zugreifen kann.

**Comment by Zefau** [comment]
Dafür dann #166 :-)
