### ISSUE TITLE
Bitte eine Konfiguration erstellen. Siehe auch Dokumentation

### ISSUE THREAD

**Issue by NewGitHubUser11** [Zefau/ioBroker.jarvis#439]
Hallo,
Sobald ich die Jarvis Oberfläche starte erscheint unten ein Rotes Feld mit 
"Bitte eine Konfiguration erstellen. Siehe auch Dokumentation"

Ich kann nun etwas konfigurieren, Geräte suchen lassen und abspeichern, aber die Visulisierung bleibt immer leer und beim neuen Aufrufen werde ich auch immer wieder auf die Konfigurationsseite geleitet.
In der Dokumentation finde ich keine andere Info, was ich noch machen müsste.

Hab es auf zwei Raspi's Probiert, und bei einem Den Adapter auch mal komplett neu Installiert. Alles ohne Erfolg.

**Comment by Zefau** [comment]
Sind sowohl Geräte angelegt als auch ein Layout? 

Hast du die YouTube Videos gesehen?

**Comment by NewGitHubUser11** [comment]
Hallo Zefau,

Es ist ganz merkwürdig, ich hab es die letzten Tage mehrere Male probiert gehabt, und auch die Geräte mal neu gestartet zwischendrin, aber sie haben die Einstellungen nie behalten, sondern gleich wieder vergessen. Einer der beiden Raspis hat auch beim automatischen Suchen keine Geräte gefunden, obwohl die teilweise identisch zum anderen sind.
Jetzt heute findet der eine plötzlich Geräte und beide behalten ihre Änderungen, obwohl ich eigentlich nichts geändert habe. Hab danach noch das Update auf 2.0 gemacht, läuft immer noch :-)

Eine andere Frage noch, mit welchem Element würdest du eine Zeiteingabe realisieren für einen Wecker, also nur Stunden und Minuten z.b. 08:00
