### ISSUE TITLE
LevelBody for blinds not working as expected

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#44]
I have to differentiate my initial comment that the LevelBody is not working at all:

* The LevelBody is working for dimmable lights as described and expected.
* The LevelBody is not working for blinds.

There is no error in the console.

**Comment by Zefau** [comment]
What type of object is it? `Number` or `String` ?

**Comment by braindead1** [comment]
Both, blinds and lights, are aliases generated with the Alias Adapter. All my blinds are HomeMatic and my lights are HomeMatic IP.

Following is the definition of the SET object of one of my blinds:

    {
      "_id": "alias.0.Büro_Rolladen.SET",
      "common": {
        "name": "SET",
        "role": "level.blind",
        "type": "number",
        "read": true,
        "write": true,
        "alias": {
          "id": "hm-rpc.1.XXXXXXXXXX.1.LEVEL"
        },
        "smartName": {
          "de": "Büro Rolladen"
        }
      },
      "native": {},
      "type": "state",
      "from": "system.adapter.admin.0",
      "user": "system.user.admin",
      "ts": 1594146679102,
      "acl": {
        "object": 1636,
        "state": 1636,
        "owner": "system.user.admin",
        "ownerGroup": "system.group.administrator"
      }
    }

Following is the definition of the SET object of one of my dimmable lights:

    {
      "_id": "alias.0.Büro_Deckenleuchte.SET",
      "common": {
        "name": "SET",
        "role": "level.dimmer",
        "type": "number",
        "read": true,
        "write": true,
        "alias": {
          "id": "hm-rpc.2.XXXXXXXXXXXXXX.4.LEVEL"
        },
        "smartName": {
          "de": "Büro Deckenleuchte, Büro Licht",
          "smartType": "LIGHT",
          "byON": "40"
        }
      },
      "native": {},
      "type": "state",
      "from": "system.adapter.admin.0",
      "user": "system.user.admin",
      "ts": 1594146634727,
      "acl": {
        "object": 1636,
        "state": 1636,
        "owner": "system.user.admin",
        "ownerGroup": "system.group.administrator"
      }
    }

**Comment by Zefau** [comment]
What does `The LevelBody is not working for blinds.` specifically means? Is the component showing and you are able to set a value, but the value is not applied? Or won't the component show up at all?

**Comment by braindead1** [comment]
My understandig is that `LevelBody` enables a slider for the state `level` in the pop-up, which is not working.

![image](https://user-images.githubusercontent.com/2136249/92304680-622a1980-ef80-11ea-8e7e-510d479dbc70.png)

![image](https://user-images.githubusercontent.com/2136249/92304686-7241f900-ef80-11ea-9012-39941f73f797.png)

**Comment by Zefau** [comment]
No, the configuration only applies on the widget, not the popup. Though, the popup is not working.

**Comment by Zefau** [comment]
Should be fixed with `v1.0.0-beta.10`.

**Comment by Zefau** [comment]
Furthermore, see https://github.com/Zefau/ioBroker.jarvis/issues/40

**Comment by braindead1** [comment]
Label and slider in pop-up are working in `v1.0.0-beta.10`.

I just noticed that using the LevelBody slider opens the pop-up for blinds and lights. This should be my last finding. :-)

**Comment by Zefau** [comment]
Should be resolved with `1.0.0-beta.11`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.11`

**Comment by Zefau** [comment]
e40aa01797fd1ffc1ec0035f00d40aaa92cbf52f
