### ISSUE TITLE
CUXD Devices - Import erfolgt unvollständig

### ISSUE THREAD

**Issue by KoMa1978** [Zefau/ioBroker.jarvis#442]
Hallo,

Ich habe diverse virtuelle Schalter in CUXD konfiguriert. Als Geräte Symbol habe ich "Schaltaktor 1Fach" gewählt, was zur Folge hat, dass das Gerät als "HM-LC-Sw1PBU-FM" in der CCU dargestellt wird.

Dies wiederum hat zur Folge, dass Jarvis beim Schalter nur den ersten Kanal "hm-rpc.2.CUX4000001.1.STATE" einliest, obwohl der Schalter in der CCU insgesamt 16 virtuelle Kanäle hat (hm-rpc.2.CUX4000001.1.STATE - hm-rpc.2.CUX4000001.16.STATE).

Die Nutzung z.B. eines 19 Kanal Fernbedienungs - Aktors klappt leider nicht, da ich Schalter brauche und keine Taster ...

Das ist aber eher kosmetik, denn ein manuelles Ändern des Kanals klappt wunderbar.

Viele Grüße,

**Comment by Zefau** [comment]
Werden alle CUxD als `HM-LC-Sw1PBU-FM` dargestellt? Haben die immer 16 Kanäle? Inwiefern ist das fest bzw. flexibel?

Hast du da noch mehr Informationen, ggf. Screenshots, damit ich das nachvollziehen und korrekt in jarvis integrieren kann?

**Comment by Zefau** [comment]
@KoMa1978

**Comment by KoMa1978** [comment]
Das ganze heißt unter CUXD "(40) 16 Kanal Universalsteuerung".

Es kann Taster, Schalter, Tür/Fensterkontakt, Bewegungsmelder, Gefahrenmelder, Jalousie, Dimmer, Drehgriffkontakt oder Keymatic sein. Aber ich vermute ganz stark, dass die 16 Kanäle immer da sind.

**Comment by Zefau** [comment]
Kannst du mir ein CUxD Gerät aus ioBroker als json exportieren (Button mit dem Pfeil nach unten) ?

![image](https://user-images.githubusercontent.com/14368811/104130124-5788f200-536f-11eb-8e8c-a4f9b6211658.png)

**Comment by KoMa1978** [comment]
Hi,

kein Thema:
[hm-rpc.2.CUX4000002.json.txt](https://github.com/Zefau/ioBroker.jarvis/files/5794636/hm-rpc.2.CUX4000002.json.txt)

**Comment by Zefau** [comment]
Ok, vielen Dank. Letzte Frage: Es gibt ja neben `STATE` noch andere Datenpunkte. Soll ich nur `STATE` für alle 16 Channels einlesen oder noch mehr Datenpunkte?

**Comment by KoMa1978** [comment]
Hmm ich nutze nur STATE, aber das muss nichts heißen.

**Comment by Zefau** [comment]
Schau mal bitte mit `v2.2.0-beta.14`, ob es damit passt.

**Comment by KoMa1978** [comment]
Hmmm

Habs eben installiert, aber damit tritt wieder das Problem aus "Issue 304" glaube ich ist es auf, dass ich keine Connection bekomme, da Javis und der iobroker bei mir hinter einem Reverse Proxy läuft. Auch mit den Parametern in der URL klappt es nicht.

**Comment by Zefau** [comment]
@KoMa1978 funktioniert der Import inzwischen? Sofern es an #304, bitte dort nochmal öffnen.
