### ISSUE TITLE
LightColorBody (Color Picker) can not show current color

### ISSUE THREAD

**Issue by MichaelKorn** [Zefau/ioBroker.jarvis#443]
**Versions**
- Version: 2.1.0-beta.4 and 2.0.0

**Describe the bug**
LightColorBody can not show the current color value.
The Browser console shows:
```i18n # Word "" not found in language en!      Log.js:56```
This log is created in i18n.js:203 because the color string (eg. "#f6ca80") is translated. In addition, '#' is the split character in that function (line 185). This results in a misleading log (Word "" not found).

**Expected behavior**
Selected color should be shown, when:
1. LightColorBody is opened (use current state)
2. After changing the color with the color picker (LightColorBody).

**Comment by Zefau** [comment]
The translation is misleading and has nothing to do with this.

What state have you combined with HueColorBody? Could you provide a screenshot of your configuration?

**Comment by MichaelKorn** [comment]
I'm using ioBroker.zigbee. I tried different devices and several configurations
Here is my current configuration of the rgb data point of a hue bulb:
```javascript
{
  "type": "state",
  "common": {
    "name": "Wohnzimmer_Leuchte_Herd Color",
    "type": "string",
    "read": true,
    "write": true,
    "role": "level.color.rgb"
  },
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1581813913204,
  "_id": "zigbee.0.001788010340d1dd.color",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "native": {}
}
```
jarvis device config:
```javascript
"wohnzimmer_leuchte_herd_94f46": {
    "id": "wohnzimmer_leuchte_herd_94f46",
    "name": "Wohnzimmer_Leuchte_Herd",
    "function": "light",
    "states": {
      "reachability": {
        "state": {
          "node": "zigbee.0.001788010340d1dd.available"
        },
        "action": ""
      },
      "link_quality": {
        "state": {
          "node": "zigbee.0.001788010340d1dd.link_quality"
        },
        "action": ""
      },
      "power": {
        "state": {
          "node": "zigbee.0.001788010340d1dd.state"
        },
        "action": "zigbee.0.001788010340d1dd.state"
      },
      "level": {
        "state": {
          "node": "zigbee.0.001788010340d1dd.brightness"
        },
        "action": "zigbee.0.001788010340d1dd.brightness"
      },
      "colorTemperature": {
        "state": {
          "node": "zigbee.0.001788010340d1dd.colortemp"
        },
        "action": "zigbee.0.001788010340d1dd.colortemp"
      },
      "rgb": {
        "state": {
          "node": "zigbee.0.001788010340d1dd.color"
        },
        "action": "zigbee.0.001788010340d1dd.color"
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Zigbee",
        "namespace": "zigbee"
      },
      "_created": 1607630000481
    }
  },
```
![image](https://user-images.githubusercontent.com/3801648/101989439-965c5700-3ca0-11eb-9ea5-7b20daeb2aba.png)


jarvis layout config:
```javascript
         [
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "wohnzimmer_leuchte_herd_94f46",
                  "primaryStateKey": "level",
                  "actionType": "state",
                  "actionElement": "",
                  "secondaryStatesKeys": [
                    "rgb"
                  ],
                  "bodyStateKey": "reachability"
                }
              ],
              "module": "StateList",
              "title": "test",
              "id": "661b5902-97bb-4b40-8906-9e001635bb0c",
              "index": 0
            }
          ]
        ],
```
If I open the setting of a device, the color in LightTemperatureBody is always 000000. For a short moment after a click the chosen color is shown, when 000000 again.
The bulb uses the chosen color.
![colorPicker](https://user-images.githubusercontent.com/3801648/101989209-21d4e880-3c9f-11eb-9785-76419ff58bb1.gif)

> What state have you combined with HueColorBody?
I am unsure of the names of the controls. But to be clear: I'm not using any setting in the Hue color space, all my data points expect RGB.

**Comment by Zefau** [comment]
@MichaelKorn What value is the state `zigbee.0.001788010340d1dd.color` initially holding?

Please rename the state key to `hex` if that is what is required by the state in the zigbee adapter.
The state key `rgb` will return a comma separated red,green,blue value.

**Comment by MichaelKorn** [comment]
@Zefau thx, for your support.
At first I didn't understand what you mean by "state key". Then I realized that the device setting is meant in jarvis.
Changing this from "rgb" to "hex" solved my problem.
In [ioBroker.zigbee .color](https://github.com/ioBroker/ioBroker.zigbee/blob/b531900a80a99d6eea4675612052142e6a01ad93/lib/states.js#L1156) is always represented in hex.
I think the real problem here is that the Zigbee importer in jarvis imports .color as "rgb" and not as "hex" (preferably directly with the label "color"): https://github.com/Zefau/ioBroker.jarvis/blame/master/wiki/de-Devices_Importer.md#L1203-L1206

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/498
