### ISSUE TITLE
iFrame size and/or scrollbar settings broken on tab change

### ISSUE THREAD

**Issue by Pla5ma** [Zefau/ioBroker.jarvis#444]
Version 2.0.0-rc1

I embedded several Grafana dashboards in different tabs. If I am in a specific tab and I refresh the page everything in that tab is fine. But if I change to another tab with iFrames the embedded page shows scrollbars. If I do it the other way around it will be the other way around.

Example:

Tab Startseite after page refresh:
![image](https://user-images.githubusercontent.com/57805183/101984398-897c3b00-3c81-11eb-9864-34561e64de83.png)

Tab Haushaltsgeräte after page refresh:
![image](https://user-images.githubusercontent.com/57805183/101984408-9bf67480-3c81-11eb-8d36-1d711097cbbe.png)

Tab Haushaltgeräte after I was on Startseite, refreshed the page and switched to tab Haushaltsgeräte:
![image](https://user-images.githubusercontent.com/57805183/101984430-bc263380-3c81-11eb-9f27-7fd972512471.png)

**Comment by Pla5ma** [comment]
PS: A solution would be to refresh the screen on tab change. Maybe as tab setting?

**Comment by Zefau** [comment]
Please upgrade to `v2.0.0` if you are on `rc` and confirm this bug

**Comment by Zefau** [comment]
@Pla5ma

**Comment by Zefau** [comment]
@Pla5ma

**Comment by Zefau** [comment]
@Pla5ma
