### ISSUE TITLE
Support import of devices from ioBroker.mihome

### ISSUE THREAD

**Issue by lordnaicon** [Zefau/ioBroker.jarvis#448]
Hallo,

ist es möglich das Importieren der MI Home adapters zu integireren.

PS: du machst ein tollen Job 

Mfg lordnaicon

**Comment by Zefau** [comment]
Users 3808

**Comment by Zefau** [comment]
@lordnaicon Welche Geräte hast du im Adapter drin? Nur Lichter?

Ich selbst habe nur das Gateway:
![image](https://user-images.githubusercontent.com/14368811/103155035-52874880-479c-11eb-974f-4a8735a6dbb8.png)

**Comment by lordnaicon** [comment]
hi ich habe

- Fensterkontakte
- Luft und Feuchtigkeitssensoren
- Wasserleck Sensoren

![tempsnip](https://user-images.githubusercontent.com/34775745/103157342-2676c200-47b2-11eb-9c34-36174d5f959a.png)


Mfg lordnaicon

**Comment by Zefau** [comment]
@lordnaicon added with `2.2.0-beta.9`. Please test and confirm everything is imported as required.

**Comment by lordnaicon** [comment]
Hi das importieren funktioniert so weit gut, das einzige was mir aufgefallen ist.
Der Luft und Temperatur Sensor wir als Schalter (switch) erkannt bzw zugeordnet, die Kategorie ist eigentlich Sensor hätte ich gesagt.

Mfg lordnaicon

**Comment by Zefau** [comment]
Das ist der letzte deines Screenshot, der mit `weather` beginnt?

**Comment by lordnaicon** [comment]
ja genau das ist der Luft und Temperatur Sensor
![Uploading LuT.PNG…]()

**Comment by Zefau** [comment]
Das Gewerk wird automatisch auf Basis des Namens und der Datenpunkte erkennt. Aufgrund von `doublePress` und das `press` in `pressure` wird es als Switch übernommen.

Mit der nächsten beta habe ich das Gewicht im Sensor-Gewerk mal erhöht, so dass es hoffentlich dann dort zugeordnet wird.

**Comment by lordnaicon** [comment]
Ok vielen Dank

**Comment by Zefau** [comment]
probier bitte nochmal mit `v2.2.0-beta.11`.

**Comment by lordnaicon** [comment]
Ja jetzt wird es richtig zugeordnet. Danke

Mfg lordnaicon
