### ISSUE TITLE
Problems in settings dialogue after changing language

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#45]
I have a clean installation with `v1.0.0-beta.4`.

After switching the language from German to English there is a problem with the translation of this dialogue. Besides that German is still selected, although in the JSON the language is set to "en-GB".

![image](https://user-images.githubusercontent.com/2136249/92207127-03ce3f80-ee89-11ea-97e1-82c0c816adf7.png)

To switch back to German again you have to select English, then select German and then save the dialogue.

There is no message in the console.

**Comment by Zefau** [comment]
Once again: Your help and support is very much appreciated! Without your testing and feedback, jarvis wouldn't grow as good! Thanks for that. Also thank you very much for your donation! I wisely invested it in beer :) 🍺 

This issue should be resolved `1.0.0-beta.5`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.7`

**Comment by Zefau** [comment]
59d662110dd83f36fe004a168fc3dfd46123ca18
