### ISSUE TITLE
Layout Fehler in BlindLevelAction

### ISSUE THREAD

**Issue by Bjoern3003** [Zefau/ioBroker.jarvis#451]
Siehe Anhang.

Wenn man hoch oder runter drückt, wird durch den Stop Button der Text links von den Buttons unter den Slider geschoben.

![14122020180208](https://user-images.githubusercontent.com/13675579/102111460-b6258380-3e36-11eb-8973-ab381fb833bb.png)

**Comment by Zefau** [comment]
probiere bitte nochmal mit `v2.1.0-beta.16`.
