### ISSUE TITLE
Farbliche Sekundäre Datenpunkte

### ISSUE THREAD

**Issue by Loi83** [Zefau/ioBroker.jarvis#456]
Hey, ich weiß nicht ob es ein Bug oder ein Feature ist. Wäre es möglich das man die Sekundären Datenpunkte auch farblich hinterlegen kann?

**Comment by Zefau** [comment]
- [ ] https://forum.iobroker.net/post/547934

**Comment by Zefau** [comment]
added with `2.2.0-beta.1`.

**Comment by testit2020** [comment]
![image](https://user-images.githubusercontent.com/68483974/103477203-8aa21300-4dbc-11eb-8824-8caa58b61361.png)
![image](https://user-images.githubusercontent.com/68483974/103477208-9392e480-4dbc-11eb-9f28-062eedc3274a.png)
Die Kommas sind auch mit 2.2.0-beta.2 noch zu sehen.

**Comment by Zefau** [comment]
@testit2020 probier bitte nochmal mit `2.2.0-beta.3`.

**Comment by testit2020** [comment]
Mit 2.2.0-beta.4 sieht es so aus:
![image](https://user-images.githubusercontent.com/68483974/103493650-e14a3400-4e32-11eb-94cb-2c6a376610ef.png)
![image](https://user-images.githubusercontent.com/68483974/103493658-e9a26f00-4e32-11eb-91e2-5ee82ed98d95.png)
Es fehlt nur noch die Prüfung vom letzten Wert, so wie aussieht.

**Comment by Zefau** [comment]
@testit2020 probier bitte nochmal mit `v2.2.0-beta.5`.

**Comment by testit2020** [comment]
Mit `v2.2.0-beta.5` sieht es so aus:
![image](https://user-images.githubusercontent.com/68483974/103728507-87866d00-4fde-11eb-8361-73ed8fe3c82c.png)
![image](https://user-images.githubusercontent.com/68483974/103728527-92410200-4fde-11eb-9690-57694fb501f5.png)

**Comment by duczz** [comment]
Das Problem besteht noch vereinzelt, eine farbliche Anpassung ist auch schon mit drin (wo setz ich diese)?

**Comment by Zefau** [comment]
@duczz Was für ein Problem?

**Comment by duczz** [comment]
Das noch vereinzelt n Komma am Ende ist, wie siehts mit der Farbanpassung aus?
![image](https://user-images.githubusercontent.com/25475385/104817796-d5437680-5823-11eb-80e0-06d78c36e984.png)

**Comment by Zefau** [comment]
Die Farbanpassung ist längst umgesetzt.

**Comment by duczz** [comment]
und wo stell ichs ein?

**Comment by Zefau** [comment]
Datenpunkt Stil, wie normal auch beim primären Datenpunkt

**Comment by Zefau** [comment]
@testit2020 Schau mal bitte mit `v2.2.0-beta.16`. Damit sollte es nun mit den Kommas passen.

Die Einfärbung der sekundären Datenpunkte geht bei dir bereits, richtig?

**Comment by testit2020** [comment]
Die Einfärbung funktioniert mit Standard. Habe da jetzt nichts eingestellt.
![image](https://user-images.githubusercontent.com/68483974/104821049-6a9d3580-5839-11eb-9067-b35d026e1ff5.png)
![image](https://user-images.githubusercontent.com/68483974/104821056-80125f80-5839-11eb-87ce-021926307f4a.png)
Fehlergrund-Objekt:
{
  "common": {
    "name": "HAUS.LICHT.TISCH.FEHLER_GRUND",
    "role": "state",
    "type": "mixed"
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.javascript.0",
  "user": "system.user.admin",
  "ts": 1609410961597,
  "_id": "javascript.0.HAUS.LICHT.TISCH.FEHLER_GRUND",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}

**Comment by Zefau** [comment]
@testit2020 prüf mal bitte mit `v2.2.0-beta.17`.

**Comment by duczz** [comment]
das komma ist mit b17 wieder da, b16 hat gepasst (siehe mein screen)

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/575093

**Comment by duczz** [comment]
Immernoch 
![image](https://user-images.githubusercontent.com/25475385/107112731-0aa71700-685a-11eb-9299-abbb3cf24e09.png)

**Comment by Zefau** [comment]
another try with `2.2.0-beta.33`.

**Comment by Zefau** [comment]
@duczz mit `2.2.0-beta.34` sollte es nun endlich passen

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/575705
