### ISSUE TITLE
Changing colors has no effect

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#46]
I have a clean installation of `v1.0.0-beta.4`.

Changing the colors has no effect, although it is correctly saved in the JSON.

![image](https://user-images.githubusercontent.com/2136249/92208269-22cdd100-ee8b-11ea-9f8f-4c7138a2efa3.png)

There is no message in the console.

**Comment by Zefau** [comment]
This issue should be resolved `1.0.0-beta.5`.

**Comment by Zefau** [comment]
`1.0.0-beta.7`: Incorrect colors will now fall back to default colors. Furthermore, the placeholder `pink` has been changed to a correct color.

**Comment by braindead1** [comment]
In `v1.0.0-beta.7` this is working.

**Comment by Zefau** [comment]
59d662110dd83f36fe004a168fc3dfd46123ca18
