### ISSUE TITLE
States Spracheinstellungen

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#464]
Hi Zefau,
Hab etwas beobachtet und kann mir grad selbst nicht helfen. Hatte gestern einen kleinen IOBroker "Neuinstallationsfall" am Ende aber alles wieder hinbekommen und auch Jarvis lief erstmal top. 

Heute hab ich jedoch gesehen, dass eigentlich alle States auf Englisch und nicht mehr auf deutsch sind. Ich hab sowohl die Spracheinstellungen in Seiteneinstellungen in Jarvis geprüft als auch die globalen in IOBroker. Steht alles auf deutsch. Switche ich in Jarvis kurz auf Englisch, sehe ich das "Last change" und komme durch Switch auf deutsch auch wieder zu "Letzte Änderung". Allerdings bleiben die States weiterhin auf Englisch. Der Datenpunkt hat im Original True und False. Ich bin auf der aktuellsten Beta 2.1.0 beta6. 

Hier mal der Screen dazu:

![image](https://user-images.githubusercontent.com/57875762/102723587-4701d080-4309-11eb-9125-18fdfd6e9f6c.jpeg)

Gibt es noch ne Stelle, wo ich umstellen kann oder liegt der Fehler nicht bei mir? 

Danke übrigens für den ganze Adapter und die 2.1! die Änderungen bis hier sind suuuuper! Vor allem das Widget-Verschieben ist megaaaa!
LG funky4t

**Comment by Zefau** [comment]
Muss ich prüfen. Ich melde mich

**Comment by Zefau** [comment]
Sollte mit `2.1.0-beta.12` behoben sein.

**Comment by funky4t** [comment]
Hiermit bestätigt! Läuft! Danke für den wie immer hervorragend schnellen Fix! 🥇
