### ISSUE TITLE
Support import of devices from ioBroker.ble

### ISSUE THREAD

**Issue by Thanadus** [Zefau/ioBroker.jarvis#465]
Hi Zefau,

du machst einen super Job und ich liebe deine Vis!
Könntest du auch die BLE Devices mit importieren?

Vielen Dank

Gruß Tilo

**Comment by Zefau** [comment]
Kannst du mir die Adapter-Struktur bitte screenshoten?

**Comment by Thanadus** [comment]
So ?
![image](https://user-images.githubusercontent.com/76424056/102790162-5b93a680-43a5-11eb-9495-e151fdcd49f6.png)

**Comment by Zefau** [comment]
Ca. 2994 users

**Comment by Zefau** [comment]
Bitte für eines der Geräte (`device`) aus den Screenshots die Experten-Ansicht hier rein kopieren:

![image](https://user-images.githubusercontent.com/14368811/103154939-93329200-479b-11eb-85ef-61f25fb0e564.png)

**Comment by Thanadus** [comment]
Frohes Neues!

![image](https://user-images.githubusercontent.com/76424056/103467412-209f5480-4d4f-11eb-9aeb-ede141d288b3.png)

**Comment by Zefau** [comment]
Gibt es eine Möglichkeit das Gewerk zu erkennen? Also ob Licht, Sensor, etc. ?

**Comment by Zefau** [comment]
Kannst du den Screenshot bitte von `blue.0.58:2d:34:37:f5:c0` (also vom `device`, nicht vom `state`) machen?

**Comment by Thanadus** [comment]
![image](https://user-images.githubusercontent.com/76424056/103475701-f467f000-4daf-11eb-8881-839e53eb8a61.png)

**Comment by Thanadus** [comment]
Hallo Zefau,

es sind alles nur Senoren. Vielleicht kannst du es so direkt zu ordnen ohne eine extra abfrage.
Vielen Danke für deine mega super Arbeit!

https://github.com/AlCalzone/ioBroker.ble

**Comment by Zefau** [comment]
@Thanadus added with `2.2.0-beta.9`. Please test and confirm everything is imported as required.

**Comment by Thanadus** [comment]
@Zefau Very very Perfect! Thanks you for your work!
![image](https://user-images.githubusercontent.com/76424056/104122561-f4369a00-5345-11eb-9bf9-49c77f771988.png)
