### ISSUE TITLE
Gerätekonfiguration kann nicht gespeichert werden

### ISSUE THREAD

**Issue by watcherkb** [Zefau/ioBroker.jarvis#466]
**Prerequisites**
- [ ] Are you on the latest stable or latest beta of jarvis? --> BETA10

**Versions**
- Which jarvis version are you running: BETA10

**Describe the bug**
Ich kann die Gerätekonfiguration nicht abspeichern. Die konfigurierten Werte sind nach dem Speichern nicht mehr da.

**Screenshots**

![image](https://user-images.githubusercontent.com/35189947/102776778-a86c8280-438f-11eb-865d-e0d77adfbaee.png)

**Comment by Zefau** [comment]
Works fine for me. Could you video your issue or describe it more in detail what you are exactly doing? Do you have any errors in the Browser Console (F12)? Does it maybe help if you delete the Browser Cache? 

![Issue_#466](https://user-images.githubusercontent.com/14368811/102884403-d914f080-4451-11eb-8634-57de06e5b891.gif)

**Comment by watcherkb** [comment]
@Zefau this issue seems to be fixed with beta13. But I still have an issue with "expert-mode". The settings are not saved. In version 2.0 everything is ok.

https://user-images.githubusercontent.com/35189947/102971140-14b6c580-44f9-11eb-88ee-a7846f6e73c2.mp4

**Comment by Zefau** [comment]
That bug is reported already here https://github.com/Zefau/ioBroker.jarvis/issues/476 and has been solved with beta-14.
