### ISSUE TITLE
Support import of devices from ioBroker.linkeddevices

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#467]

**Comment by Zefau** [comment]
Siehe Facebook

**Comment by Zefau** [comment]
Ca. 1543 users

**Comment by DNC74** [comment]
@Zefau Ich habe den Adapter im Einsatz und nutze ihn auch sehr gerne. Wie kann ich helfen? (Facebook habe ich nicht verfolgt)

**Comment by Zefau** [comment]
Ich kenne den Adapter gar nicht. Folgt er irgendwelchen Richtlinien? Also dass die Datenpunkte in bestimmter Art und Weise angelegt werden müssen? Beim Devices Adapter ist dem leider nicht so. Dort importieren ich alle Datenpunkte, die einem Channel angeordnet sind.

Kannst du mir einen Screenshot deines Objekt-Baums als Orientierung zur Verfügung stellen?

**Comment by DNC74** [comment]
Das ist der Vorteil (und für dich gleichzeitig Nachteil) von 'linkeddevices': es gibt keinen Standard oder Richtlinien. Das kann jeder frei handhaben und seine Aliase/Geräte so definieren wie er möchte. Ich würde daher vorschlagen, du verfährts analog zum Devices Adapter. Hier mal meine Struktur, aber wie gesagt, frei erstellt nach meinem Geschmack. Die "Folder" habe ich selbst angelegt, alles ab der Ebene "Channel" ist original von Linkeddevices und daher vermutlich für dich interessant... müsstest eben rekursiv drüber rennen
![2020-12-28 23_28_49-Window](https://user-images.githubusercontent.com/72687758/103246722-c83e1080-4964-11eb-8243-c14b7f94ecbc.png)

und hier nur zum Verständnis, wie Linkedevices arbeitet den passenden Screenshot aus dessen Config: links meine Alias-DPs und rechts die originalen DPs:
![2020-12-28 23_36_05-instances - ioBroker und 3 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/72687758/103247143-27505500-4966-11eb-95bf-420c4b731160.png)

**Comment by Zefau** [comment]
@DNC74 @FredF63 added support in `v2.2.0-beta.12`.

**Comment by FredF63** [comment]
> 
> 
> @DNC74 @FredF63 added support in `v2.2.0-beta.12`.

Topp, testen geht aber erst am Wochenende

**Comment by djalexz** [comment]
Hi Zefau,

ich habe den Import vom linkeddevices Adapter mal getestet.
Leider funktioniert es nicht.
Es wird einfach garnichts erkannt.
Habe die Datenpunkte bereits auf den Typ undefined gesetzt.

Bitte um Info ob du noch weitere Informationen brauchst.

Danke dir

LG Alex

**Comment by Zefau** [comment]
Kannst du deine Objekt Struktur mal screenshoten?

**Comment by djalexz** [comment]
Hoffe das passt so.
Bin zur Zeit nur mit Handy online. 

![Uploading Screenshot_20210122-215341_Samsung Internet.jpg…]()

**Comment by Zefau** [comment]
dort wo `undefined` steht bitte `device` draus machen

**Comment by djalexz** [comment]
Klasse, das funktioniert.
Danke dir vielmals.
Du müsstest dann nur noch den Tooltip anpassen.
Denn da steht in undefined umbenennen:

![image](https://user-images.githubusercontent.com/11389551/105563154-58316900-5d1d-11eb-8e9a-5f20a2960706.png)

**Comment by Zefau** [comment]
Oh ja, danke für den Hinweis

**Comment by Zefau** [comment]
@djalexz mit `v2.2.0-beta.24` sollte der Hinweis nun korrekt sein. Kannst du das nochmal prüfen?

**Comment by djalexz** [comment]
Jawohl, danke dir für die schnelle Umsetzung und den tollen Adapter.

![image](https://user-images.githubusercontent.com/11389551/105613738-d5fc7f80-5dc4-11eb-8b14-ae8bd5c79574.png)
