### ISSUE TITLE
Import of blind alias devices

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#47]
I have a clean installation of `v1.0.0-beta-4`. I imported my alias devices. My blinds are correctly recognized as blinds. The "SET" state is automatically transferred into "level".

To get the blind widget correctly to work I have to manually create the "activity" state and match it to the "WORKING" state of the alias device. Addtionally I have to enter the "STOP" state as trigger datapoint. 

For the "level" state I have to manually enter the "SET" state as trigger datapoint.

The configuration of blind alias devices should automatically be done as on the screenshot below.

![image](https://user-images.githubusercontent.com/2136249/92210264-b05ef000-ee8e-11ea-8d05-14840819be95.png)

**Comment by Zefau** [comment]
This is the same as the additional comments in https://github.com/Zefau/ioBroker.jarvis/issues/31#issuecomment-683462948?

**Comment by Zefau** [comment]
This issue should be resolved `1.0.0-beta.6`.

**Comment by braindead1** [comment]
Neither `v1.0.0-beta-5` nor `v1.0.0-beta-6` are loading correctly. I get the following messages in the console when I do not delete my configuration.

![image](https://user-images.githubusercontent.com/2136249/92278493-9c9aa480-eef5-11ea-9110-8c7e29b1ca71.png)

After deleting the configuration and reimporting alias devices, the JSON is saved, but the devices are not shown in the dialogue once the configuration dialogue is shown again due to missing layout configuration. The following is shown in the console.

![image](https://user-images.githubusercontent.com/2136249/92278923-7fb2a100-eef6-11ea-86aa-a7dc805cc401.png)

**Comment by Zefau** [comment]
This is because https://github.com/Zefau/ioBroker.jarvis/issues/46 has been "fixed" and resulting in `pink` not being a correct color code. I will have a look at this again.

**Comment by braindead1** [comment]
Hehe, I just entered pink, because it used as placeholder.

![image](https://user-images.githubusercontent.com/2136249/92279594-edab9800-eef7-11ea-873b-72314d362e7e.png)

Nevertheless, the issue with newly imported alias devices remains the same. They are not shown in the dialogue after import and save, although they are recognized as already imported.

![image](https://user-images.githubusercontent.com/2136249/92279866-7e827380-eef8-11ea-8988-fa6b4e14c79a.png)

**Comment by Zefau** [comment]
Should be fixed with `1.0.0-beta.7`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta-7`

**Comment by Zefau** [comment]
59d662110dd83f36fe004a168fc3dfd46123ca18
