### ISSUE TITLE
add HmIP-BROLL to ioBroker.hmip adapter import

### ISSUE THREAD

**Issue by nicojako** [Zefau/ioBroker.jarvis#471]
Hallo habe das Problem das ich beim HMIP-BROLL kein Channel 3 habe nur 1 und 2 und somit die Rollade nicht richtig erkannt wird.

Gibt es hier einen Lösungsweg?

**Comment by nicojako** [comment]
![Screenshot 2020-12-22 120436](https://user-images.githubusercontent.com/76476988/102881927-e0d29600-444d-11eb-97a0-7338d20709c1.png)

**Comment by Zefau** [comment]
Es gibt meines Wissens nach auch keinen Channel 3. HmIP-BROLL war bisher nicht unterstützt von jarvis. Habe das nun mit der `v2.1.0-beta.12` hinzugefügt. Bitte probiere den Importer nochmal (Gerät dann einfach mittels Importer überschreiben). 

Hast du noch mehr HmIP Geräte?

**Comment by nicojako** [comment]
Ich habe noch Fenster Kontakte und Heizkörper Thermostate die funktionieren super.

PS: Klasse Arbeit habe genau nach Jarvis Monate gesucht!!!

**Comment by nicojako** [comment]
dann werde ich mir mal die Beta ziehen

**Comment by nicojako** [comment]
Leider immer noch keine Level anzeige.
![Screenshot 2020-12-22 140022](https://user-images.githubusercontent.com/76476988/102891173-0cf61300-445e-11eb-87a2-5dc39f067266.png)

**Comment by Zefau** [comment]
Im Browser Log steht, dass die beta installiert ist?

**Comment by Zefau** [comment]
Also sprich du hast jarvis korrekt direkt von Github installiert?

**Comment by nicojako** [comment]
Jap hatte ich dirket über github hab auch jedes mal ein Popup bekommen das vorher in der Stable ja nicht drin ist.

**Comment by Zefau** [comment]
probier bitte nochmal `v2.1.0-beta.14`, damit sollte es nun klappen.

**Comment by nicojako** [comment]
Das Hinzufügen hat nun funktioniert. allerdings arbeitet der HmIP-BROLL mit 0 bis 1 wobei die 1 für "closed" steht und die 0 für "open".

Daher gibt es immer noch einen fehler.

Ich habe es hinbekommen die 0 und 100 auf 0 und 1 zu setzen damit ist aber alles trotzdem invertiert.

![Screenshot 2020-12-22 223057](https://user-images.githubusercontent.com/76476988/102934969-777e7180-44a5-11eb-8554-53ad72bf452a.png)
"Danke an der stelle für deine YouTube Videos die helfen mir als Anfänger in Sachen JSON sehr."
Und als Verständnisses deines Adapters sehr.

Leider finde ich es nicht schön das ich bei allen anderen 0 bis 100%habe und hier 0 bis 1 kann man dies irgendwie lösen?
Gerne können wir uns auch mal direkt austauschen um es zu testen.

Danke und
Gruß Nico

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/416
