### ISSUE TITLE
Widget Hinzufügen oder bearbeiten in Beta12 funktioniert nicht

### ISSUE THREAD

**Issue by nicojako** [Zefau/ioBroker.jarvis#472]
Hallo Zefau,

leider funktioniert das bearbeiten von Widgets nicht mehr nach dem Update auf Beta12 bei mir hängt er sich immer auf.

Er öffnet nur eine leere Seite.

Des weiteren hängt sich die suche nach Adaptern direkt auf.

**Comment by funky4t** [comment]
Kann ich leider seit Beta 12 auch hier bestätigen :(
Zudem kommt der neue Welcome Screen auch bei JEDEM Refresh der Site neu. Beim ersten Start fände ich den super, bei jedem Refresh eher weniger..

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/469

**Comment by Zefau** [comment]
fixed with `v2.1.0-beta.13`.

**Comment by funky4t** [comment]
Hi Zefau,
mit Beta15 kann ich die Widgets wieder bearbeiten.

2 Sachen fallen mir jedoch auf:
a) bei jedem Update auf eine neue Verion ist Levebody bei diversen Geräten leer. Ich glaub, ich hab meiner Wohnzimmerlampe jetzt bestimmt 20x den Levelbody Slider neu verpasst, da nach jedem Jarvis Update dieser fehlt. Hast ne Idee warum? Ist eines der Geräte die ich noch in 1.0.9, der ersten Stable angelegt habe?! Liegts daran?

b) Hab ich jetzt zumindest bei Schlißekontakten ein Mix aus der States in Englisch und des Change in Deutsch, bei verschiedenen Geräten. Mein Fensterkontakt z.B. sieht so aus:

![grafik](https://user-images.githubusercontent.com/57875762/103020251-5d499f80-4548-11eb-96b6-4017687c2041.png)

Beim BWM passt interessanter Weise beides:
![grafik](https://user-images.githubusercontent.com/57875762/103020353-88cc8a00-4548-11eb-8431-2ef39f7b1820.png)

Hab leider bisher nur einen Fensterkontakt, sonst hätte ich beim 2. nachgesehen...oder hast du closed noch nicht übersetzt? ;)

Wie immer Danke für die schnellen Korrekturen und diesen einmaligen Adapter!!! :) Genieße die Feiertage!


Aktualisierung Deutsch / State englisch // Korrekturswitch in den Seiteneinstellungen blieb erfolglos.
