### ISSUE TITLE
ExpertenModus speichert nicht

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#476]
Hi,

scheinbar gehen alle Änderungen verloren welche ich via Experten-Modus mache. 

:-(

2.1.0-beta.13

**Comment by DNC74** [comment]
kann ich für 2.1.0-beta.13 bestätigen.

**Comment by Zefau** [comment]
behoben mit `v2.1.0-beta.14`.

**Comment by DNC74** [comment]
getestet und bestätigt, Einstellungen werden wieder gespeichert.
