### ISSUE TITLE
Show calendar names (e.g. owner) in widget

### ISSUE THREAD

**Issue by dabbeljuh22** [Zefau/ioBroker.jarvis#477]
It would be nice to see the names of the calendar's owner in front of an item.
---
Es wäre schön, wenn vor einem Element der Name des Besitzers des Kalenders angezeigt würde.

**Comment by Zefau** [comment]
Kannst du das genauer ausführen? Inwiefern der Besitzer? In v3 wird nun der Kalender-Name vorangestellt und auch die Kalender-Farbe. Passt das?

**Comment by dabbeljuh22** [comment]
Ohne dass ich es jetzt explizit getestet habe, sollte das passen. Mir ging es darum, die einzelnen Termine besser auseinanderhalten zu können. Das würde damit dann wohl klappen. Danke.

**Comment by tschortschde** [comment]
Wird es dieses Feature noch geben?

**Comment by Zefau** [comment]
Wurde geschlossen, da die Anforderung zu unkonkret war.

Ich kann es gerne wieder öffnen, wenn du konkret sagst was gewünscht ist.

**Comment by tschortschde** [comment]
Das wäre schön...
Ich habe mehrere Kalender in einem Widget im Einsatz und möchte gerne die Vornamen anzeigen, also wem der Kalender gehört😉
Ist das möglich?

**Comment by Zefau** [comment]
Welches Feld im ical ist das denn?

**Comment by tschortschde** [comment]
Hierbei handelt es sich eigentlich um das Feld "Label" im Jarvis-Widget... ;-)  
![Screenshot 2023-02-13 093651](https://user-images.githubusercontent.com/11274233/218412439-4e5753e1-6de6-4c13-814b-7d5744f3cce2.jpg)

**Comment by Zefau** [comment]
Achso

**Comment by Zefau** [comment]
Wo soll der Kalender-Name denn eingeblendet werden? Wenn man mit der Maus über den Punkt links eines Termins geht wird der Kalender ja im Tooltip angezeigt. Soll er da stattdessen dann stehen?

**Comment by Zefau** [comment]
@tschortschde mit `v3.1.4-beta.5` nun verfügbar inkl. Option

**Comment by tschortschde** [comment]
@Zefau perfekt vielen Dank 
teste es demnächst...
schönes Wochenende
