### ISSUE TITLE
Option zur Sicherung der Jarvis Dateien

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#478]
Bitte eine Option einbauen für eine externe Sicherung der jarvis Dateien um sie gegeben Falls wieder zurück zu spielen.

Danke 

Sigi234

**Comment by Zefau** [comment]
Nutzt jemand redis für die Objekte (nicht States) ? 
Ich selbst nutze `file` (dateibasiert) für Objekte und redis nur für States.

Frage an die, die redis auch für Objekte nutzen: Sind die Backups nach dem Update gelöscht? Also gibt es (nach dem updaten) noch Einträge in der ioBroker Adapterkonfiguration?

**Comment by Zefau** [comment]
added foundation with `2.2.0-beta.7`.

**Comment by Zefau** [comment]
ab v1.8.4 von ioBroker.backitup verfügbar.
