### ISSUE TITLE
Support import of devices from ioBroker.innogy-smarthome

### ISSUE THREAD

**Issue by smash-666** [Zefau/ioBroker.jarvis#479]
Bitte Geräte des folgenden Adapters unterstützen:
innogy-smarthome.0
(früher RWE, dann innogy, jetzt Livisi (in iobroker noch unter Adapter innogy-smarthome.0)

Beispiel (Baumansicht):
innogy-smarthome
 -- Raum
        -- Fenstersensor
        -- Heizkörperthermostat (HKT) 
        -- Raumklima
![grafik](https://user-images.githubusercontent.com/76499484/102939910-718d8e00-44af-11eb-84f9-1d252a544ee9.png)

Fernbedienung:
![grafik](https://user-images.githubusercontent.com/76499484/102940213-1c05b100-44b0-11eb-81b1-dce17ad8fd81.png)

Heizkörperthermostat(HKT):
![grafik](https://user-images.githubusercontent.com/76499484/102940277-3f306080-44b0-11eb-972f-b20e3be9287c.png)

Raumklima:
![grafik](https://user-images.githubusercontent.com/76499484/102940322-566f4e00-44b0-11eb-9e64-597d246edb7c.png)

Wandsender (Schalter):
![grafik](https://user-images.githubusercontent.com/76499484/102940357-7141c280-44b0-11eb-9719-541393bdd2a7.png)

Rauchmelder Typ1:
![grafik](https://user-images.githubusercontent.com/76499484/102940426-99c9bc80-44b0-11eb-9d75-1292361f55d0.png)

Rauchmelder Typ2:
![grafik](https://user-images.githubusercontent.com/76499484/102940660-1ceb1280-44b1-11eb-9059-981af14e9321.png)

Bewegungsmelder (Aussen)
![grafik](https://user-images.githubusercontent.com/76499484/102940505-c087f300-44b0-11eb-9f21-4633047133a8.png)

Zwischenstecker (Schalter):
![grafik](https://user-images.githubusercontent.com/76499484/102940576-eca37400-44b0-11eb-845f-36b48ce95ef2.png)

Fenstersensor:
![grafik](https://user-images.githubusercontent.com/76499484/102940712-3ab87780-44b1-11eb-90a0-5d2550ab249d.png)

**Comment by Zefau** [comment]
Ca. 520 users

**Comment by Zefau** [comment]
Bitte für eines der Geräte (`device`) aus den Screenshots die Experten-Ansicht hier rein kopieren:

![image](https://user-images.githubusercontent.com/14368811/103154939-93329200-479b-11eb-85ef-61f25fb0e564.png)

**Comment by smash-666** [comment]
device raw view:

![grafik](https://user-images.githubusercontent.com/76499484/103166888-db4ac680-4826-11eb-8ea2-8fc2c08461ff.png)

**Comment by Zefau** [comment]
@smash-666 added with `2.2.0-beta.9`.

**Comment by smash-666** [comment]
Hallo,

**super Job!**
Alle  meine Geräte wurden korrekt erkannt und importiert (getestet mit der beta.11).
Könntest du bei der Frostwarnung eine Schneeflocke als Default Symbol verwenden?
z.B dieses hier: 
![grafik](https://user-images.githubusercontent.com/76499484/104138206-e95e2280-53a2-11eb-82f1-ccff374b1a76.png)


![grafik](https://user-images.githubusercontent.com/76499484/104138148-a439f080-53a2-11eb-99d8-ce56403f0b95.png)

**Comment by Zefau** [comment]
hab ich in `v2.2.0-beta.12` hinzugefügt.
