### ISSUE TITLE
Label of blinds states not used in widget

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#48]
I have a clean installation of `v1.0.0-beta-4`. I imported my alias devices. My blinds are correctly recognized as blinds.

I entered labels for the states and they are saved in the JSON, but they are not used in the widget.

![image](https://user-images.githubusercontent.com/2136249/92248512-1a948680-eec9-11ea-88ae-bf4faa0326d7.png)

![image](https://user-images.githubusercontent.com/2136249/92248661-4dd71580-eec9-11ea-9341-cf6b0f57927f.png)

There is no error message in the console.

**Comment by Zefau** [comment]
Should be resolved with `1.0.0-beta.8`.

**Comment by braindead1** [comment]
Labels are fixed in `v1.0.0-beta-8`.

**Comment by Zefau** [comment]
aa13283a3eac314bd9a01ae3f0d2f86ae37a68b3
