### ISSUE TITLE
Uncheck all devices option in the "Import Devices" menu

### ISSUE THREAD

**Issue by watcherkb** [Zefau/ioBroker.jarvis#485]
**Describe the solution you'd like**

In the "Import Devices" section all checkboxes are checked by default. Would be nice to uncheck all at once or by default check the one I need.

![image](https://user-images.githubusercontent.com/35189947/102982019-2785c600-450a-11eb-8a83-895d9eed9d61.png)

**Comment by Zefau** [comment]
added with `v2.2.0-beta.3`.
