### ISSUE TITLE
Mehrere Trigger einem Device zuweisen

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#487]
Ich würde gerne mehrere Trigger einem Device zuordnen.

**Comment by Zefau** [comment]
Was wäre hier der Use Case? Kann sonst recht einfach über ioBroker gelöst werden?

**Comment by duczz** [comment]
Im Hinblick auf den Adapter HeatingControl, muss man Zeiten + Temperaturen definieren und dies immer pro Zeile zu machen würde die Kachel extrem vergrößern

Beispiel Vis
https://github.com/Pittini/iobroker-heatingcontrol-vis

**Comment by duczz** [comment]
Noch was wofür man mehrere Trigger brauchen könnte, eine Zeile wäre auch hier schöner
![image](https://user-images.githubusercontent.com/25475385/104121420-61dec800-533e-11eb-826c-11f7fa1cde7a.png)

**Comment by Zefau** [comment]
Da ist doch gar kein Trigger drin?

**Comment by duczz** [comment]
Dann nenn es in diesem Fall nicht Trigger sonst Sekundärer Datenpunkt Horizontaler anstatt drunter

**Comment by Zefau** [comment]
Du musst deine Feature Request ordentlich formulieren, sonst versteh ich nicht, was du willst! Das fängt bei einem klaren Wording an. Außerdem müssen es im Zweifel auch andere verstehen, damit ein voting möglich ist.

Wenn du von Trigger sprichst aber das nicht meinst, dann setze ich am Ende was ganz anderes rum.

_____

Wenn du dort eine Zeile haben willst, dann nutze einfach nur sekundäre Datenpunkte?

**Comment by duczz** [comment]
Im sekundären Datenpunkt gehts dank.

Anbei nochmal ein usecase um Platz zu sparen
![image](https://user-images.githubusercontent.com/25475385/104561330-880aad80-5647-11eb-9209-81d0da0c3ccb.png)

**Comment by Zefau** [comment]
Duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/695
