### ISSUE TITLE
Skalierung mit v2.1.0 geht nur noch bedingt

### ISSUE THREAD

**Issue by simatec** [Zefau/ioBroker.jarvis#488]
Bin jetzt mal von der 2.0.0 auf die aktuelle v2.1.0 Beta15 und da ist bei mir alles was vorher ordentlich skaliert war nun komplett verschoben und verkleinert.
Irgendwie war die Lösung des skalierens unter der Version 2.0.0 besser gelöst. 

Kann dort eventuell wieder beim skalieren der Version 2.0.0 angesetzt werden. 
aktuell sieht jeder Widget-Inhalt von der Größe anders aus und zerstört eine ordentliche View

**Comment by Zefau** [comment]
@simatec Was genau ist aus deiner Sicht anders in v2.1 ?

Nachfolgend ein Beispiel zweier Widget (Module Wetter und Kalender) mit maximaler Höhe 300px und Skalierung:

![image](https://user-images.githubusercontent.com/14368811/103083949-00002d80-45de-11eb-84f0-fe9791a30464.png)

Beide sind auf gleicher Höhe. Was war in v2.0 anders?

**Comment by simatec** [comment]
Mir geht es um den Inhalt. Dieser wird in der aktuellen Betta extrem verkleinert. 
in meinem Fall geht es um States in einem horizontalen State Widget. Der Inhalt also die States werden extrem klein dargestellt. Dies war in der 2.0.0 nicht der Fall

**Comment by Zefau** [comment]
Kannst du das Widget und die Widget Konfiguration mal jeweils screenshoten?

**Comment by simatec** [comment]
Hier mal zwei Screenshots
![fully-screenshot (2)](https://user-images.githubusercontent.com/39792461/103092171-ae17d180-45f6-11eb-9339-869c97ef5be6.png)
Hier sieht man die unterschiedlichen Größen der Widget Inhalte

![fully-screenshot (3)](https://user-images.githubusercontent.com/39792461/103092177-b112c200-45f6-11eb-8e0a-ae5d281e5901.png)
Im zweiten Bild sieht man, wie verschoben die Inhalte sind.
Des Weiteren lassen sich Frames nicht mehr positionieren und skalieren
Auf dem Bild sieht man, dass der Frame nicht mehr unten ins Widget passt

**Comment by Zefau** [comment]
Kannst du mir die Layout Konfiguration schicken? Also den Inhalt von `jarvis.0.layout`.

**Comment by simatec** [comment]
[layout.txt](https://github.com/Zefau/ioBroker.jarvis/files/5740011/layout.txt)
Anbei die etwas bearbeitete Config

**Comment by Zefau** [comment]
Bitte probier mal mit `2.1.0-beta.17`, ob es das wieder bessert.

**Comment by simatec** [comment]
Leider keine wirkliche Veränderung mit der Beta 19. Die states werden nun in der horizontalen Statelist nicht mehr auseinander gezogen, aber die States werden weiterhin so klein dargestellt

**Comment by simatec** [comment]
@Zefau bin jetzt zwecks der Auflösung bzw Skalierung wieder zurück auf 2.0.0. willst du hier nochmal Screenshots haben, wie dort die Skalierung ausschaut?

**Comment by Zefau** [comment]
Jo kann nicht schaden

**Comment by simatec** [comment]
So hier noch einmal die Vergleich wie gewünscht.
In den beiden Screenshots sieht man, dass in den Widgets die States in Version 2.1.0 beta  die States zu klein und verschoben skaliert bzw. verkleinert werden. Auf dem Tablet bewirkt das auch teilweise eine recht verschwommene Auflösung und ist aufgrund der extrem Verkleinerung kaum noch lesbar.
Auch eine zentrierte Positionierung ist mit der Beta nicht mehr möglich. In den Screenshot sieht man dort sehr gut die Unterschiede.

An den Einstellungen der VIS habe ich zwischen den Versionen nichts geändert.

Hier das Beispiel mit Version 2.1.0 Beta 19
![fully-screenshot (2)](https://user-images.githubusercontent.com/39792461/103168199-6f219000-4831-11eb-924d-f4354020026b.png)

Hier dagegen die Version 2.0.0 rc1
![fully-screenshot (4)](https://user-images.githubusercontent.com/39792461/103168213-8791aa80-4831-11eb-8286-1a26801d7054.png)

Ich hoffe, dass ich dir bei der Fehlersuche damit etwas helfen konnte

**Comment by duczz** [comment]
Das Problem liegt daran das die Ränder größer wurden

**Comment by simatec** [comment]
OK das kann sein. Allerdings bei fertigen Views halt etwas schwierig. Wie in meinen Screenshots zu sehen, kann ich da leider nix mehr verschieben oder vergrößern

**Comment by Zefau** [comment]
bitte nochmal mit `v2.1.0-beta.24` prüfen.

**Comment by duczz** [comment]
@Zefau Ich find aber auch das die Abstände vom Device zum Rand größer wurden (auch mit dem Fix vom Vollbild), aber das wird sich später ja noch via Custom Layout regeln lassen
![image](https://user-images.githubusercontent.com/25475385/103176722-7918b280-4874-11eb-8f8a-fe6dd8f100d9.png)

**Comment by Zefau** [comment]
Daran habe ich jetzt nichts geändert - im Gegenteil: habe die Abstände für Vollbild wieder auf 0 korrigiert.

Custom CSS ist bereits freigeschaltet, siehe https://github.com/Zefau/ioBroker.jarvis/issues/117

**Comment by duczz** [comment]
aah Top, dann spiel ich mich daran gleich mal

**Comment by Zefau** [comment]
@simatec kannst du auch bestätigen, dass es so passt?

**Comment by simatec** [comment]
Ich teste gleich mal und berichte 😉

**Comment by simatec** [comment]
Die Auflösung bzw. Skalierung scheint nun wieder in Ordnung. Musste nur sehr viele "ShowState" in die Settings aktivieren, damit meine Views wieder passen.
PS: dieses Info Popup kommt aktuell bei jedem Aufruf der Config und ich persönlich finde das sehr störend
