### ISSUE TITLE
Link via Browser ausführen - Custom HTML/iFrame

### ISSUE THREAD

**Issue by hardToGetUsername** [Zefau/ioBroker.jarvis#489]
Aufgrund von Restriktionen seitens einiger (?) Websitebetreiber [https://support.mozilla.org/de/kb/website-erlaubt-firefox-nicht-die-seite-anzuzeigen](url) scheint es bei den entsprechenden Seiten nicht möglich zu sein, die Inhalte bei customhtml oder iFrame in jarvis direkt anzuzeigen. Es funktioniert wohl nur über ein neues browserfenster/tab. Ich habe Chrome und Firefox ausprobiert.

Kann man hier einen button einfügen der alternativ den Link in einem neuen Browserfenster öffnet? Der obere screenshot ist aus Chrome.

Da es ein relativ einfaches widget ist, nehme ich an, dass ich in jarvis alles korrekt eingetragen habe.

![Link Chrome](https://user-images.githubusercontent.com/44637121/103000328-2022e480-452b-11eb-9eb8-8f493afcc60f.jpg)
![Link Firefox](https://user-images.githubusercontent.com/44637121/103000329-20bb7b00-452b-11eb-9bec-33db1552cc25.jpg)

**Comment by Zefau** [comment]
Leider ist es so, dass der HTML `iFrame` Tag keine verlässlichen Informationen bietet, ob das Laden der Inhalte bzw. der Seite fehlgeschlagen ist. Insofern habe ich keine Grundlage den Status abzufragen und etwas entsprechend in jarvis darzustellen.
