### ISSUE TITLE
Icons of blinds states not working

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#49]
I just noticed that icons are not working as well. I entered icons for the states and they are saved in the JSON, but they are not used in the widget.

![image](https://user-images.githubusercontent.com/2136249/92283940-4e8b9e00-ef01-11ea-8eb1-ffd5070da985.png)

![image](https://user-images.githubusercontent.com/2136249/92283963-5c412380-ef01-11ea-9ea7-b5109267ff60.png)

**Comment by braindead1** [comment]
I just noticed that there is a misunderstanding on my side and it will potentially be the case for all users.

To get icons to work, you have to enter their name without the prefix "mdi-". When you go to the Material Design Icons cheatsheet and click on an icon, it's name is copied with the prefix. To make this convenient for the users, you should allow both.

Link to cheatsheet: https://cdn.materialdesignicons.com/5.4.55/

**Comment by Zefau** [comment]
Should be fixed with `v1.0.0-beta.10`

**Comment by braindead1** [comment]
For states this is fixed in `v1.0.0-beta.10`. To be consistent, this fix should also be implemented for tabs and widget-boxes.

**Comment by Zefau** [comment]
Should also be working with tabs and widgets now in `1.0.0-beta.11`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.11`

**Comment by Zefau** [comment]
e40aa01797fd1ffc1ec0035f00d40aaa92cbf52f
