### ISSUE TITLE
DropDownBox

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#490]
It would be nice to have DropDownBox widget. Something like this

<img width="196" alt="Bildschirmfoto 2020-12-23 um 16 19 24" src="https://user-images.githubusercontent.com/2972703/103011711-aa267980-453a-11eb-9781-b42035089cf2.png">

**Comment by Zefau** [comment]
What about the DropdownAction component within the StateList module?

**Comment by stephan1827** [comment]
That would work as well

**Comment by Zefau** [comment]
Then give it a try :-)
