### ISSUE TITLE
LevelBody empties on update

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#491]
_Originally posted by @funky4t in https://github.com/Zefau/ioBroker.jarvis/issues/472#issuecomment-750390163_

> bei jedem Update auf eine neue Verion ist Levebody bei diversen Geräten leer. Ich glaub, ich hab meiner Wohnzimmerlampe jetzt bestimmt 20x den Levelbody Slider neu verpasst, da nach jedem Jarvis Update dieser fehlt. Hast ne Idee warum? Ist eines der Geräte die ich noch in 1.0.9, der ersten Stable angelegt habe?! Liegts daran?

**Comment by Zefau** [comment]
Meinst du LevelBody im Gerät oder im Widget oder beides?

**Comment by funky4t** [comment]
![grafik](https://user-images.githubusercontent.com/57875762/103023135-a51ef580-454d-11eb-9884-86030bc775a3.png)

Der Body Datenpunkt ist bei mir immer leer wenn ich die Beta update. Dann spring ich rein ins Layout, wähle im Dropdown wieder Level aus und mein Slider ist wieder da. In den Geräten muss ich nix ändern, nur jedes Mal den BodyDP neu auswählen. Interessant nur, dass das nicht bei allen Geräten bei mir ist. Meine Rollos sind okay....

Hab grad nochmal alle Tabs überflogen, bei meinen Hues sind die Slider nach dem Update auch raus:
Visu
![grafik](https://user-images.githubusercontent.com/57875762/103023469-5160dc00-454e-11eb-962b-c1bbf706db15.png)
Layout
![grafik](https://user-images.githubusercontent.com/57875762/103023682-b74d6380-454e-11eb-9f16-bfb652fe79bd.png)

Das Wohnzimmer Tab und die darin befindlichen Geräte sind aber auch eins der ersten Dinge die ich damal mit deinen ersten Versionen des Adapters generiert hab. Vielleicht liegt es daran und ich muss die Geräte rauswerfen und nochmal neu anlegen?!

**Comment by Zefau** [comment]
@funky4t Kannst du mir das json des Widgets / des Layouts schicken?

**Comment by funky4t** [comment]
@Zefau herzlich gerne, wenn du mir kurz verrätst wo/wie ich das finde/erstelle? Du meinst nicht die Backups bei den Objekten oder? Sorry, ich komme mehr von der Anwenderseite... 🙈

**Comment by Zefau** [comment]
Der Inhalt von `jarvis.0.layout`.

**Comment by funky4t** [comment]
here we go...
[Layout.txt](https://github.com/Zefau/ioBroker.jarvis/files/5739514/Layout.txt)

**Comment by Zefau** [comment]
Ich kann's mir leider nicht erklären. Bei einem Update erfolgt keinerlei Anpassung des Layouts oder sonst eine Änderung an der Konfiguration.

Auch, dass nur bestimmte Geräte im Widget (scheinbar nur Gewerk Licht?) betroffen sind, ist äußerst merkwürdig.

Ich habe eine Anpassung im Code vorgenommen in der Hoffnung, dass das hilft. Ist aber mehr blind, da ich keine Idee habe, worin der Fehler begründet liegt.

Bitte installiere dir mal `v2.1.0-beta.16` und beobachte beim Wechsel auf die irgendwann erscheinende `v2.1.0-beta.17`, ob es wieder auftritt. 
Wenn du jarvis nach dem Update das erste Mal öffnest, dann schau bitte mal in die Browser Konsole (F12), ob es dort Hinweise auf Fehler / Unstimmigkeiten gibt.

**Comment by funky4t** [comment]
Ich behalte es mal "im Auge". Notfalls werde ich das Device mal raus und lege es neu an um zu schauen, ob das dann zukünftig auch betroffen ist. Ist ja nix wirklich Dramatisches!

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/543786

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/501#issuecomment-751507705
