### ISSUE TITLE
Load custom scripts

### ISSUE THREAD

**Issue by techducks** [Zefau/ioBroker.jarvis#492]
Hi, 
in meinen Augen wäre es Sinnvoll, wenn man ein eigenes Javascript laden kann? 
Realisierbar wäre das zum Beispiel, indem man ein Script aus dem JavaScript-Adapter läd (wird dann im Admin von Jarvis konfiguriert).

Mir ist die Idee bei folgendem Problem gekommen:
Ich wollte Jarvis aus dem Internet via Reverse Proxy erreichbar machen. Dem Proxy habe ich dann gesagt, dass er nur ein Redict machen soll, wenn in der URL ein ?key=abc Parameter ist. (Zur Authentifierung)
Hat auch geklappt. Das Problem ist nur, dass die Javascripte und CSS Files nicht nachgeladen werden, weil diese in der index.html fest einprogrammiert sind. Mein Browser will sich also die Scripte holen, aber entfernt die Parameter aus der URL.

Also entweder dynamische URLs oder Custom Scripte 😄 
ps. ich finde Jarvis richtig geil! Weiter sooo

**Comment by Zefau** [comment]
Du kannst mittels Custom HTML eigene Javascript laden.

**Comment by techducks** [comment]
@Zefau Du meinst das Modul CustomHTML?

**Comment by Zefau** [comment]
Jo. Ist nicht genau das, was du meinst, aber wäre eine temporäre Lösung.

**Comment by techducks** [comment]
Ja, ich schaue mal, ob das klappt. Du kannst entscheiden, ob es eventuell mal eingebaut werden soll.
Wahrscheinlich ist das für die wenigsten relevant, aber ich würde die Vis jetzt schon gerne via Internet erreichen. (Ohne Basic Auth)

**Comment by fmranger** [comment]
Hi,

ich würde gerne in einem JsonTable Widget mit der Format-Option pro Zeile einen Button hinzufügen, der eine Javascript-Funktion aufruft.

Das mit dem Button bekomme ich hin, aber die Funktion wird nicht gefunden obwohl ich sie in einem anderen Widget (HTML) auf der gleichen Seite definiert habe. 

Beispiel: format":"val => val = '<button type=\\'button\\'  onclick=\\'MeineFunktion(&quot;' + val + '&quot;)\\'>Ausschalten</button>';"

Fehlermeldung:
Uncaught ReferenceError: MeineFunktion is not defined
    at HTMLButtonElement.onclick
    
Wie kann ich eigene Javascript-Funktionen hinzuladen?

Habe eine Jarvis Pro-Lizenz.
Der Adapter ist echt der Hammer.
Du machst eine tolle Arbeit.
Vielen Dank.

**Comment by Zefau** [comment]
Eigene / Custom Scripts nun (mit Pro) mit `v3.1.0-alpha.9` verfübar:

![image](https://user-images.githubusercontent.com/14368811/171283636-440dde10-4d7f-43ac-a0e8-7367baed73b4.png)

**Comment by mcuiobroker** [comment]
Wie kann man dort die bestehende socket-Verbindung mit nutzen, um Daten aus ioBroker-DPs abzufragen?

**Comment by Zefau** [comment]
ab `v3.1.0-alpha.10` via `window.Socket`, z.B. `getState(stateId, callback)`:
```
window.Socket.getState('0_userdata.0.boolean', ({ err, state }) => {
   ...
});
```

Weitere Befehle:
- `getState(stateId, callback)`
- `subscribeState(stateId, callback)`
- `setState(stateId, value, ack, callback)`
- `getObjectView(design, search, params, callback)`
- `getObjects(pattern, callback)`
- `getObject(id, callback)`

**Comment by mcuiobroker** [comment]
subscribeState , bzw. die callback() wird dann auch bei Änderung von einem Wert ausgelöst?

**Comment by Zefau** [comment]
> subscribeState , bzw. die callback() wird dann auch bei Änderung von einem Wert ausgelöst?

Ja.

>  on()-Funktion? on({id: instanceExImportDP, change: "any"}, function (obj)

Nicht notwendig.

**Comment by uwe72** [comment]
@Zefau 

Ich würde gerne in meiner HTML-Tabelle  (welches über StateHtml-Widget in Jarvis dargestellt ist) pro Zeile einen Button darstellen. Dieser Button soll dann Datenpunkte verändern.

`<button  onclick=\"doMySpecificCode(123)"></button>`

Wie kann ich darauf reagieren? Wo kann ich meine Methode 

```
function doMySpecificCode() {

}

```

platzieren?

Kann ich das Script in ioBroker (JS-Script-Adapter) einfügen oder eher in Jarvis im Reiter "Scripts"? Bin ich generell auf dem richtigen Weg?

**Comment by mcuiobroker** [comment]
Hier ein Beispiel für jsonTable:
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/scripts-3.1.x-pro/jsontable

**Comment by uwe72** [comment]
@mcuiobroker Danke dir!!!

Leider funktioniert dies nicht. Hast Du eine Idee?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/61848539/4de15513-d406-4c99-ae38-8f74da2b673c)

![image](https://github.com/Zefau/ioBroker.jarvis/assets/61848539/5baa7995-3b47-401a-9d32-d44100a43263)

`<button type=\"button\" onclick=\"test()\">Test!</button>`

**Comment by mcuiobroker** [comment]
setState so ibt es in jarvis nicht->
`window.Socket.setState(stateId, value, ack, callback)`

**Comment by uwe72** [comment]
> setState so gibt es in jarvis nicht-> `window.Socket.setState(stateId, value, ack, callback)`

Hat super funktioniert. Wirklich DANKE!!!!!!

Wo wird eigentlich das Ganze geloggt, wo finde ich die Logausgaben?

![image](https://github.com/Zefau/ioBroker.jarvis/assets/61848539/e148de07-f2b2-44a0-9531-5a9383d73a30)

**Comment by mcuiobroker** [comment]
F12
