### ISSUE TITLE
Expertenmodus volle Höhe

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#493]
![image](https://user-images.githubusercontent.com/22169074/103034095-647ea680-4564-11eb-9b70-b404a22c463a.png)

Aktuellste Beta. und Browser aktuellster Chrome. das Fenster bekommt irgendwo inlinestyle mit paar hunder pixel, anstelle 100% höhe.

**Comment by Zefau** [comment]
probiere bitte nochmal mit `v2.1.0-beta.16`.

**Comment by ma-gu-16** [comment]
Leider nein. 

ab .jsoneditor-outer alle parents bis zu 
.MuiPaper-root  
  height 100%

dann gehts oder 

.jsoneditor.jsoneditor-mode-text
    height: calc(100vh - 335px);

das passt dann auch.

grüsse

**Comment by Zefau** [comment]
bitte probier nochmal mit `2.1.0-beta.17`.

Sollte es nicht gehen, mach mal bitte einen Screenshot von der Browser Konsole.

**Comment by ma-gu-16** [comment]
2.1.0-beta.18

noch immer ein problem: 

![image](https://user-images.githubusercontent.com/22169074/103106992-7a5e9b00-463a-11eb-87ab-00792743426e.png)

![image](https://user-images.githubusercontent.com/22169074/103107000-94987900-463a-11eb-9373-d4a68915606c.png)

**Comment by Zefau** [comment]
@ma-gu-16 bitte schau dir nochmal die `v2.1.0-beta.30`. Ggf. müsstest du deinen Cache löschen, da laut deinem Screenshot die `id` `ConfigurationPage` auf dem falschen Element hängt, daher geht es auch bei dir nicht. Kein Plan, warum das so ist.

**Comment by ma-gu-16** [comment]
klappt. danke dir.
