### ISSUE TITLE
Einzelne Tabs/Widgets/Popups via URL öffnen

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#495]
Anwendungsfall: Es Klingelt und das TAB mit den Kameras geht auf. Schön wäre auch ein Popup mit einem LiveStream oder ähnliches. Da müssten einzelne Widget via URL adressierbar sein.

Grüsse

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/111
