### ISSUE TITLE
Display Image Refreshrate

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#496]
Hi,

habe den Synology jpegsnapshot datenpunkt eingetragen und 10sek refresh. 

![image](https://user-images.githubusercontent.com/22169074/103040597-31441380-4574-11eb-9b9d-b6c5ac68e3d6.png)

da scheint irgendetwas nicht zu stimmen, siehe console. 

Grüsse

**Comment by Zefau** [comment]
Was soll ich mit dem Screenshot anfangen? Da ist nicht viel zu erkennen. Was ist denn der HTTP Error Code?

Würde behaupten, dass der Fehler auf der Gegenseitige liegt.

**Comment by ma-gu-16** [comment]
naja gibt keinen, "canceled" sieht so aus als werden immer wieder neue timestamps hinten drangepackt. 
&_=1608761791568&_=1608761807622&_=1608761814075

die ersten 4-5 aufrufe sind okay und danach kommen die fehler. 

die originale url:
https://xxx/webapi/entry.cgi?api=SYNO.SurveillanceStation.Camera&method=GetSnapshot&version=7&cameraId= 7&_sid=3_xxxxhU

die aufgerufene: 
/webapi/entry.cgi?api=SYNO.SurveillanceStation.Camera&method=GetSnapshot&version=7&cameraId=%207&_sid=xxxxxx&_=1608761785422&_=1608761791568&_=1608761843106&_=1608762165103


Grüsse

**Comment by ma-gu-16** [comment]
Ebenso versucht er manchmal den Datenpunkt als http image aufzurufen.
Nach ein paar reloads des dashboards. ist wirklich reproduzierbar. 

![image](https://user-images.githubusercontent.com/22169074/103041381-7ff2ad00-4576-11eb-8c48-eac52ac258b7.png)

**Comment by Zefau** [comment]
auf welcher jarvis Version bist du?

**Comment by ma-gu-16** [comment]
2.1.0-beta.15

**Comment by Zefau** [comment]
probiere bitte nochmal mit `v2.1.0-beta.16`.

**Comment by ma-gu-16** [comment]
jetzt geht es gar nicht mehr ;-) 
![image](https://user-images.githubusercontent.com/22169074/103095231-2fc02d00-4600-11eb-8dfe-af32344efce7.png)

synology.0.surveillancestation.cameras.aussen%20cam.linksnapshot/:1 GET http://synology.0.surveillancestation.cameras.aussen%20cam.linksnapshot/ net::ERR_NAME_NOT_RESOLVED

er versucht jetzt nur noch den datenpunkt aufzurufen anstatt ihn korrekt aufzulösen. 

Grüsse

**Comment by ma-gu-16** [comment]
v2.1.0-beta.16  , Samsung Galaxy TAB A - 10.1 zoll   ist es nicht der Fall ;-)

**Comment by Zefau** [comment]
Ist was nicht der Fall? Der Fehler? Also du meinst da geht es? Dann lösche mal bitte den Cache bei dem Gerät, wo es nicht geht.

**Comment by ma-gu-16** [comment]
Hi, 

ich teste auf dem Desktop Chrome. Cache gelöscht, wie immer ;-) 

![image](https://user-images.githubusercontent.com/22169074/103096375-03a6ab00-4604-11eb-9be7-287aeae9ce89.png)

er interpretiert den Datenpunkt als URL und somit kann der Request nicht erfolgreich sein. 
vermutlich geht deshalb auch ein weiterer Refresh/timeout nicht.

Gruss

**Comment by Zefau** [comment]
bitte probier nochmal mit `2.1.0-beta.17`.

**Comment by ma-gu-16** [comment]
> bitte probier nochmal mit `2.1.0-beta.17`.

ich bekomm nur die 2.1.0-beta.16  via github iobroker installiert.

**Comment by Zefau** [comment]
Jetzt ist's online.

**Comment by ma-gu-16** [comment]
Der Fehler in der Console ist weg, er scheint den Pfad korrekt aufzulösen. 

Jedoch funktioniert der aktualisierungsintervall nicht.

**Comment by Zefau** [comment]
Funktioniert es mit `v2.1.0-beta.19` ?

**Comment by Zefau** [comment]
@ma-gu-16

**Comment by ma-gu-16** [comment]
auch das passt nun. der request scheint in ordnung zu sein.
