### ISSUE TITLE
Stockmarket Widget

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#497]
https://www.alphavantage.co/

evtl eine Idee, iobroker selber hat da nichts vernünftiges, 
wäre sicher für einige interessant und evtl auch ein "alleinstellungsmerkmal" ;-)

**Comment by Zefau** [comment]
Dafür solltest du parallel nochmal bei https://github.com/ioBroker/AdapterRequests/issues ein Feature Request öffnen. Das Implementieren der kompletten API zusätzlich zu einem jarvis Modul ist schon erheblich Aufwand.

**Comment by Zefau** [comment]
https://github.com/ioBroker/AdapterRequests/issues/534

**Comment by ma-gu-16** [comment]
Ich habe mir ein Script geschrieben und nutzte das HTML Widget. 
Dank dem CSS Input, passt das für mich so.
