### ISSUE TITLE
Configure colors

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#5]
Currently jarvis uses blue as primary colour. A possibility to configure primary and secondary color would be great.

**Comment by Zefau** [comment]
Added with v0.0.5. Could you please test and verify? Thanks
See docs: https://github.com/Zefau/ioBroker.jarvis/wiki/Einstellungen#einstellung-theme-

**Comment by braindead1** [comment]
This is working in v0.0.5.

**Comment by Zefau** [comment]
Remark: I had to change the parameters for the primary and secondary color, see https://github.com/Zefau/ioBroker.jarvis/wiki/Einstellungen#verf%C3%BCgbare-einstellungen for the updated documentation.

**Comment by braindead1** [comment]
I guess due to this change, the feature to hide the label of tabs (tabsHideLabels) is broken. Can you please check and fix this?

**Comment by Zefau** [comment]
Should be fixed with v0.0.7. Could you please test and verify? Thanks

**Comment by braindead1** [comment]
In v0.0.7 the problem is fixed.
