### ISSUE TITLE
Dupliziert Devices lassen keine Änderung der ursprünlichen DPs zu

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#501]
Hi Zefau, 
ich schon wieder! ;)
Hab einen Bug beim Kopieren/Duplizieren von Devices entdeckt, glaub ich jedenfalls:

Habe meinen funktionierenden FensterTürKontakt Wohnzimmer in den Devices dupliziert und wollte danach im neuen Device "Bad" lediglich die DP für das Bad korrigieren. In der Visu sah das Ergebnis dann so aus, obwohl das Bad offen ist und Battery nicht wie WZ 29% sind...

![grafik](https://user-images.githubusercontent.com/57875762/103155396-d262e200-479f-11eb-82e5-3b402d5dc692.png)

Im kopierten Device (Bad) kann ich so oft wie ich auch will den DP "Lock" und "Bat" zwar ändern und speichern aber beide springen dann nach speichern wieder zurück auf die Datenpunkte des Wohnzimmers. Scheint als wäre das neue Device und seine Datenpunkte "schreibgeschützt" gegen jegliche Änderungen.

Ich hab auch extra nochmal auf 2.1.0-beta.21 upgedatet, leider bleib der Effekt der gleiche. 
LG Funky4t

**Comment by funky4t** [comment]
Kurzes Update, ich hab noch etwa experimentiert:
Ich hab einen neuen FTK als Device angelegt und auch da lassen sich keine DPs speichern. Hat also scheinbar weniger was mit duplizierten Devices zu tun sondern es scheint, als würden (zumindest bei mir) generell die DPs nicht anlegbar sein. Das wäre noch allerdings doch etwas kritischer als nur bei kopierten Devices.

**Comment by Zefau** [comment]
@funky4t das betrifft aber "nur" die Auswahl über den Objekt-Explorer, oder? Da kann ich es zumindest nachstellen. Die manuelle Eingabe funktioniert bei mir.

**Comment by Zefau** [comment]
Hopefully resolved with `2.1.0-beta.22`.

**Comment by funky4t** [comment]
@Zefau jupp du hast richtig geraten! Sorry an das Einfügen der DP ohne den Explorer hab ich nicht gedacht. Also manuelle Eingabe läuft. Das kann ich auch für das duplizierte Gerät so bestätigen. Liegt also ausschließlich dran, dass ich die Punkte über den Objektexplorer eingefügt habe.

**Comment by Zefau** [comment]
@funky4t mit Objekt Explorer sollte es mit der neuen beta nun auch passen

**Comment by funky4t** [comment]
Teste ich heute Abend und berichte! Mal sehen ob die Level Bodies nach Update auch noch da sind! 🙃😉

**Comment by funky4t** [comment]
Hi Zefau,
a) Level Bodies nach Update diesmal noch vorhanden - Top.
b) Auswahl über Objektexplorer läuft.

Zwei Sachen sind aber neu, wenn ich die Dropdowns in den Devices aufrufe, schließen sich diese nur bei Klick auf den DropDown Pfeil und nicht mehr beim Klick auf einen leeren Bereich der Seite. Ist mir jetzt grade stark aufgefallen. (siehe Dropdownpfeil z.B. Bodyelement im angehängten Screen)

Ferner stehen in den vorgefertigten Datenpunkten teils JSON Infos in "invertierter" Darstellung (ICON im Screen). Leider nicht in denen für Stil und Co. Ich bin was JSON betrifft völlig unerfahren, habe aber einem FTK der mit "Gekippt" aus der Reihe tanzt mir helfen können, was die Stati und Icons betrifft. Leider ergibt sich aber noch in der Ansicht ein "Stil"-Problem im Sinne der textlichen Darstellung des "geschlossen". 

<img width="935" alt="Bildschirmfoto 2020-12-27 um 20 20 10" src="https://user-images.githubusercontent.com/57875762/103178299-e3841f80-4881-11eb-84fe-57998409a784.png">

<img width="674" alt="Bildschirmfoto 2020-12-27 um 20 14 31" src="https://user-images.githubusercontent.com/57875762/103178317-11696400-4882-11eb-9ce8-2d0669b0e471.png">

Würden die Standardvorgaben im JSON Style auch schon invertiert stehen, könnte ich mir vermutlich (vielleicht) selber helfen.... Darum meine zwei Fragen dazu:

1. Spricht etwas dagegen die da bei Datenpunkt Stil und Eigenschaften auch invertiert darzustellen? Oder gar im Editor hinter dem Schraubenschlüsselsymbol? Dummies wie ich könnte man im Editor ja eventuell sogar Beispiele anzeigen...
 
2. Hast du ansonsten mal nen Link wo sich nen Noobie wie ich zu den JSON Optionen einlesen kann? Im bisherigen Jarvis Manual bin ich da leider nicht fündig geworden... Kann aber verstehen, dass bei soviel geilen neuen Features die Doku und insbesondere die vom vermeintlich als im Vorfeld als bekannt angenommenen JSON oft hinten ansteht. Letztlich ist Jarvis selbst ja auch super intuitiv, nur an diesen JSON Befehlen scheitere ich bisher massiv, was mich aber nicht abhält, daran zu probieren.

**Comment by Zefau** [comment]
> Zwei Sachen sind aber neu, wenn ich die Dropdowns in den Devices aufrufe, schließen sich diese nur bei Klick auf den DropDown Pfeil und nicht mehr beim Klick auf einen leeren Bereich der Seite. Ist mir jetzt grade stark aufgefallen. (siehe Dropdownpfeil z.B. Bodyelement im angehängten Screen)

Das ist auch nicht vorgesehen, dass diese schließen, wenn man raus klickt.

> Ferner stehen in den vorgefertigten Datenpunkten teils JSON Infos in "invertierter" Darstellung (ICON im Screen). Leider nicht in denen für Stil und Co. Ich bin was JSON betrifft völlig unerfahren, habe aber einem FTK der mit "Gekippt" aus der Reihe tanzt mir helfen können, was die Stati und Icons betrifft. Leider ergibt sich aber noch in der Ansicht ein "Stil"-Problem im Sinne der textlichen Darstellung des "geschlossen".

Mit "invertiert" meinst du sicher ausgegraut? Die ausgegrauten Informationen sind die Standardwerte die greifen, wenn kein Eintrag vorgenommen wird. 
Dein JSON im zweiten Screenshot ist grundsätzlich richtig, aber du musst die Rohwerte (aus ioBroker) nehmen und nicht `closed` oder `tilted`.

> Spricht etwas dagegen die da bei Datenpunkt Stil und Eigenschaften auch invertiert darzustellen? Oder gar im Editor hinter dem Schraubenschlüsselsymbol? Dummies wie ich könnte man im Editor ja eventuell sogar Beispiele anzeigen...

Siehe Wiki und es gibt hierzu auch viel Hilfe im Forum. Wie gesagt handelt es sich bei den ausgegrauten Werten streng genommen nicht um eine Hilfestellung, sondern um die Standardwerte.

> Hast du ansonsten mal nen Link wo sich nen Noobie wie ich zu den JSON Optionen einlesen kann? Im bisherigen Jarvis Manual bin ich da leider nicht fündig geworden... Kann aber verstehen, dass bei soviel geilen neuen Features die Doku und insbesondere die vom vermeintlich als im Vorfeld als bekannt angenommenen JSON oft hinten ansteht. Letztlich ist Jarvis selbst ja auch super intuitiv, nur an diesen JSON Befehlen scheitere ich bisher massiv, was mich aber nicht abhält, daran zu probieren.

Dein JSON ist strukturell richtig, sonst würde jarvis auch einen Fehler anzeigen.

Inhaltlich ist es immer vom Rohwert aus ioBroker ausgehend, siehe auch https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#json-eingabefelder.
Frag sonst am besten einfach im Forum nach.
