### ISSUE TITLE
Add options for custom background and text color to Theme Settings

### ISSUE THREAD

**Issue by dabbeljuh22** [Zefau/ioBroker.jarvis#503]
For better customization it would be nice to have above mentionend options in the Theme Settings page (at least as long as there's no option to add complete custom css).

**Comment by Zefau** [comment]
Custom CSS (https://github.com/Zefau/ioBroker.jarvis/issues/117) will arrive with the next beta. Please check if that is sufficient for your needs.

**Comment by Zefau** [comment]
Done via https://github.com/Zefau/ioBroker.jarvis/issues/884
