### ISSUE TITLE
Kamerabild wird nur noch kurzzeitig angezeigt.

### ISSUE THREAD

**Issue by kaip2503** [Zefau/ioBroker.jarvis#505]
Bis ca. Beta 16 hat die Anzeige meiner Kamerabilder korrekt funktioniert. Seit dem wird das Bild kurzzeitig angezeigt und verschwindet dann. 

<img width="833" alt="Bildschirmfoto 2020-12-27 um 13 33 07" src="https://user-images.githubusercontent.com/73375585/103170894-29bc8d00-4848-11eb-9195-7a91abc65a86.png">

Eingebunden ist es wie folgt: 

Hätte gerne einen Screenshot gezeigt, allerdings stürzt Jarvis dann ab und zeigt nur noch eine weiße Seite. 
Auch in den Expertenmodus komme ich nicht mehr rein. -> Weiße Seite. 

Ist evtl. der Umlaut bei Haustür ein Problem?

**Comment by kaip2503** [comment]
Habs das Modul mal aus dem Datenpunkt rausgeholt. So sieht es aus: 

{"moduleConfig":{"url":"synology.0.SurveillanceStation.cameras.Haustuer.linkMjpegHttpPath","height":"400px","refresh":"2"},"devices":[],"module":"DisplayImage","title":"Haustürkamera","icon":"cctv","id":"704cbf6a-aeae-4fd1-9238-769d80847d6e","index":1}

**Comment by Zefau** [comment]
Mach mal bitte rechtsklick auf das Bild, wenn dieses verschwunden ist und poste das hier rein.

**Comment by kaip2503** [comment]
http://192.168.178.28:8082/jarvis/synology.0.SurveillanceStation.cameras.Haustuer.linkMjpegHttpPath?ts=1609075984513&undefined -> Wenn es weg ist 

http://192.168.178.21:5000/webapi/entry.cgi?api=SYNO.SurveillanceStation.Stream.VideoStreaming&version=1&method=Stream&format=mjpeg&cameraId=6&StmKey=%229c1d3d03cdfdcff80fea2017257e8be2%22 -> Wenn es da ist

**Comment by Zefau** [comment]
sollte mit `v2.1.0-beta.23` wieder passen

**Comment by kaip2503** [comment]
Geht wieder alles. Top!
