### ISSUE TITLE
Implement two rows of tab selection

### ISSUE THREAD

**Issue by Torrid16V** [Zefau/ioBroker.jarvis#506]
Enable two rows or more of Tab selection.
Reason: faster navigation on mostly used 10 inch tablets

**Comment by Zefau** [comment]
Please describe your feature request more in detail. Bitte etwas mehr Details.

**Comment by Torrid16V** [comment]
Actual Solution:
![image](https://user-images.githubusercontent.com/76655086/103174566-89746180-4863-11eb-931c-bae52fb3703e.png)

New Solution:
![image](https://user-images.githubusercontent.com/76655086/103174615-e1ab6380-4863-11eb-93d9-4645ce114bee.png)

So two rows would make navigation a little bit faster instead of scrolling long distances on visualisations that use a lot of tabs.

**Comment by Zefau** [comment]
Will be done via tabs dropdown https://github.com/Zefau/ioBroker.jarvis/issues/638
