### ISSUE TITLE
iframe Bug

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#507]
Hab nach langem mal wieder ne beta porbiert - iframe wird nicht mehr komplett dargestellt (scrollbalken) in kombi einer hinterlegten max höhe
![image](https://user-images.githubusercontent.com/25475385/103174532-3a2e3100-4863-11eb-9129-05f365b89f0f.png)

**Comment by duczz** [comment]
Beispiel frame:
`<script src="https://widgets.coingecko.com/coingecko-coin-price-static-headline-widget.js"></script> <coingecko-coin-price-static-headline-widget coin-ids="bitcoin" currency="eur" locale="de" background-color="#ffffff"></coingecko-coin-price-static-headline-widget>`

**Comment by Zefau** [comment]
wie sieht es mit `v2.1.0-beta.23` aus?

**Comment by duczz** [comment]
Danke
