### ISSUE TITLE
iframe spalte

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#508]
iframe spalten lassen sich in der aktuellen beta nicht mehr öffnen (greyscreen)

**Comment by Zefau** [comment]
Bitte nicht "aktuelle beta" schreiben. Aufgrund der kurzen Release-Zyklen ist das immer stark relativ ;-)

Mit `v2.1.0-beta.22` sollte der Bug nicht mehr auftreten?

**Comment by duczz** [comment]
Danke
