### ISSUE TITLE
Button is pulsating

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#51]
I have a clean installation of `v1.0.0-beta.8` and no configuration. The config dialogue pops-up and now the "Abbrechen" button is pulsating until you click somewhere else. I tried Google Chrome and Microsoft Edge. In both browsers it's the same.

![image](https://user-images.githubusercontent.com/2136249/92284304-00c36580-ef02-11ea-8a39-a7c25885608c.png)

_Originally posted by @braindead1 in https://github.com/Zefau/ioBroker.jarvis/issues/31#issuecomment-687381403_

**Comment by Zefau** [comment]
Should be resolved with `1.0.0-beta.11`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.11`

**Comment by Zefau** [comment]
e40aa01797fd1ffc1ec0035f00d40aaa92cbf52f
