### ISSUE TITLE
Trigger/Button Layout

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#510]
Optik/Abstand anpassen
![image](https://user-images.githubusercontent.com/25475385/103174716-b2492680-4864-11eb-854a-8e86ee225709.png)

**Comment by Zefau** [comment]
sollte mit `v2.1.0-beta.23` wieder passen

**Comment by duczz** [comment]
Wurde schlechter :)
![image](https://user-images.githubusercontent.com/25475385/103175946-4e2b6000-486e-11eb-9e95-eba445e72e9d.png)

**Comment by Zefau** [comment]
Was ist das für ein Browser und OS? Bei mir zeigt er es korrekt an:

![image](https://user-images.githubusercontent.com/14368811/103176269-a6fbf800-4870-11eb-84f7-5d0d3880c4bc.png)

**Comment by duczz** [comment]
Mit der B24 passts wieder danke
