### ISSUE TITLE
Widget ecken

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#511]
Ist im Layout Widget ecken aktiv fehlen gelegentlich die Trennlinien (siehe rot)
Edit: Problem tritt nur im Google Chrome auf, im MS Edge Chrom gehts - ob sichs um'n jarvis bug dadurch handelt weiß ich nicht

![image](https://user-images.githubusercontent.com/25475385/103174916-65664f80-4866-11eb-9199-1f9496a8e7a2.png)

**Comment by duczz** [comment]
Setz ich folgende CSS Settings sind die Trennlinien auch im Chrome da

`/* Überschrift */
.MuiCardHeader-root {
    display: flex;
    padding: 8px;
    align-items: center;
}

/* Rand */
.MuiCardContent-root:last-child {
    padding-bottom: 10px;
}

/* Unter und Über Datenpunkt */
.MuiList-padding {
    padding-top: 0px;
    padding-bottom: 0px;
}
`

**Comment by Zefau** [comment]
mit `v2.1.0-beta.26` behoben

**Comment by duczz** [comment]
Über der Temperatur fehlt der Trennstrich noch, beim Vollbild ist er nun da

**Comment by duczz** [comment]
nope B27

**Comment by duczz** [comment]
b28 geht

**Comment by duczz** [comment]
In der B30 fehlt der Strich wieder über Temperatur, allerdings mit aktiven CSS Settings überall anders passt es aber.

Das Problem tritt nur auf wenn man "padding-bottom:" nicht als erstes auf 0 setzt sondern als letztes (live test) - Jarvis Thema?

.MuiList-padding {
    padding-top: 0px;
    padding-bottom: 0px;
}

**Comment by duczz** [comment]
close
