### ISSUE TITLE
Vollbild

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#512]
War es bis dato nicht immer so das "Vollbild" das Widget komplett ausgefüllt hat? - Geht dann nun nicht mehr

![image](https://user-images.githubusercontent.com/25475385/103176015-ca25a800-486e-11eb-9715-89e4288f729c.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/488

**Comment by Zefau** [comment]
bitte nochmal mit `v2.1.0-beta.24` prüfen.

**Comment by duczz** [comment]
Top
