### ISSUE TITLE
Layout - Ausrichtung des Primär und sekundärer Datenpunkt

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#513]
Ausrichtung des Primär und sekundärer Datenpunktes passt nicht (sekundär zu weit rechts)
![image](https://user-images.githubusercontent.com/25475385/103176684-0a3b5980-4874-11eb-9bc8-d3300eacf12b.png)

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/544969

**Comment by DNC74** [comment]
eher https://forum.iobroker.net/post/545073 
;-)

**Comment by Zefau** [comment]
mit `v2.1.0-beta.26` behoben

**Comment by duczz** [comment]
Danke

**Comment by duczz** [comment]
Das Layout muss scheinbar noch für den kleinen Button mit angepasst werden
![image](https://user-images.githubusercontent.com/25475385/103304943-325cc100-4a0a-11eb-9c0c-eb2ac8583cac.png)

**Comment by Zefau** [comment]
Meinst du den schwarzen Strich? Hast du den über Custom CSS drin?

**Comment by duczz** [comment]
Den hab ich via Paint gemacht damit du den Unterschied/verschiebung direkt siehst :)

**Comment by Zefau** [comment]
Wobei es nicht zwingend auf einer Linie gedacht ist.
