### ISSUE TITLE
"Are you sure?" dialog on delete

### ISSUE THREAD

**Issue by dabbeljuh22** [Zefau/ioBroker.jarvis#514]
It could be helpful if there were a dialog appearing on deleting a tab or column, because it can be a bit annoying to restore such an accidentally deleted item.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/76

**Comment by dabbeljuh22** [comment]
Sorry, den Eintrag hatte ich nicht gesehen.

**Comment by Zefau** [comment]
alles gut, sind inzwischen einfach zu viele Issues um die Übersicht zu behalten. Ich hatte nur dieselbe Idee, daher hatte ich es schon angelegt :)

**Comment by dabbeljuh22** [comment]
Ja, hast ne ganze schöne Lawine losgetreten. ;) Dein Adapter ist aber wirklich top!
