### ISSUE TITLE
Geräte-Popup: Anzeige des Values trotz Action Element

### ISSUE THREAD

**Issue by DNC74** [Zefau/ioBroker.jarvis#518]
Javis 2.1.0-beta.24
Es wird bei einem konfigurierten "Action Element" auch der aktuelle Wert angezeigt. 
Screenshots siehe https://forum.iobroker.net/post/544969

**Comment by Zefau** [comment]
@DNC74 sollte mit `v2.1.0-beta.29` behoben sein.

**Comment by DNC74** [comment]
beim mir passt es, danke Dir! 👍
