### ISSUE TITLE
Trotz manuell geänderter Anzeigevariante wird Wert aus Datenpunkt visualisiert - Fehler?

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#519]
Ich hab die Wikiseite zu JSON gefunden und durch Spielerei in den Devices noch Einiges hinbekommen ;)
Eins blieb mir jedoch unklar:

Ich habe aktuell einen FensterTürKontakt, der den Battery in % rausgibt, die anderen FTKs geben nur BatteryLow=True raus. Hab mir überlegt den einen FTK aus optischen Gründen dann halt mit <=10% als "Batterie schwach" und alles >10% als "Batterie OK" darzustellen. Das funktioniert in sofern, dass der Text zwar dort steht, aber die 29(%) vom Datenpunkt stellt Jarvis dennoch dar. 
Ich hatte gehofft, durch Eintrag der Schwellen in der Anzeigevariante wird der eigentliche Wert automatisch vollständig ausgeblendet. Hab ich das falsch verstanden? Und falls ja, bekomme ich die 29(%) vom Datenpunkt hinter dem Text dann auf eine andere Art  ausgeblendet?

<img width="574" alt="Bildschirmfoto 2020-12-28 um 01 37 37" src="https://user-images.githubusercontent.com/57875762/103182944-8e5f0280-48af-11eb-8383-6b71e5e145c6.png">

<img width="964" alt="Bildschirmfoto 2020-12-28 um 01 44 41" src="https://user-images.githubusercontent.com/57875762/103182947-928b2000-48af-11eb-97d1-e1e5a2518099.png">

**Comment by Zefau** [comment]
@funky4t screenshote mal bitte die zugehörige Widget Konfiguration

**Comment by Zefau** [comment]
@funky4t bekomme das bei mir leider nicht nachgestellt. Es funktioniert bei mir wunderbar, sprich, der Wert wird komplett ersetzt.

**Comment by funky4t** [comment]
Habs schon befürchtet, dass in meiner Konfiguration was falsch ist...

{
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "0b338a0c-91a0-4dee-a1a9-2be8d6206a4d_fc956",
                  "label": "Wohnen Tür",
                  "bodyStateKey": "open",
                  "primaryStateKey": "open",
                  "showState": true,
                  "secondaryStatesKeys": [
                    "battery"
                  ]
                },

oder

<img width="1364" alt="Bildschirmfoto 2020-12-28 um 13 20 52" src="https://user-images.githubusercontent.com/57875762/103214478-ca767f80-4910-11eb-874d-c1f5464c2f1e.png">

Das Device sieht so aus:

"0b338a0c-91a0-4dee-a1a9-2be8d6206a4d_fc956": {
    "id": "0b338a0c-91a0-4dee-a1a9-2be8d6206a4d_fc956",
    "function": "window",
    "states": {
      "battery": {
        "state": {
          "node": "alias.0.Wohnen.Sensoren.FTK.Türkontakt_Batterie"
        },
        "display": {
          "<=10": "Batterie schwach",
          ">10": "Batterie OK"
        },
        "unit": {},
        "properties": ""
      },
      "open": {
        "state": {
          "node": "alias.0.Wohnen.Sensoren.FTK.Türkontakt"
        },
        "icon": {
          "closed": "window-closed-variant",
          "tilted": "window-open-variant",
          "open": "window-open-variant"
        },
        "display": {
          "closed": "window#open#false",
          "tilted": "gekippt",
          "open": "window#open#true"
        },
        "stateStyle": {
          "open": {
            "color": "#f01b0c",
            "fontWeight": "bold"
          },
          "tilted": {
            "color": "#f01b0c",
            "fontWeight": "bold"
          },
          "closed": {
            "color": "#999"
          }
        }
      }
    },
    "options": {},
    "attributes": {
      "_created": 1609009874238,
      "_updated": 1609158353510
    },
    "name": "Wohnen Tür",
    "label": "Wohnen Tür"
  },

<img width="960" alt="Bildschirmfoto 2020-12-28 um 13 31 59" src="https://user-images.githubusercontent.com/57875762/103214578-16292900-4911-11eb-8b32-b9b151514e8e.png">

**Comment by funky4t** [comment]
Kurze Info zur Dropdownauswahl:
Probier mal Drop Down "primärer Datenpunkt" und klick bei geöffneter Liste auf irgendeine freie Fläche im Hintergrund ->Dropdownliste schließt.
Das gleiche bei "sekundärer Datenpunkt", hier schließt die Dropdownliste erst/nur, wenn ich gezielt wieder auf den Dropdownpfeil klicke, nicht bei Klick auf Hintergrund.

Variante 1 würde ich beim Klicken bevorzugen, aber am Ende bleibt es eine Geschmacksache.

**Comment by funky4t** [comment]
Bei den anderen drei Geräten hab ich True/False ja auch durch "Batterie OK/schwach" ersetzt, ohne dass hinter dem Batterietext nochmal True bzw. False auftaucht. 
Bleiben eigentlich nur 2 Unterschiede: 
1. Datenpunkt liefert ein Zahl statt True/False und 
2. wird die gelieferte Zahl mit <> Operanden in visuelle Bereiche geteilt statt mit "=".

**Comment by funky4t** [comment]
Ich glaub ich nähere mich dem Problem.
Ich hab im Widgetlayout unter Einheit {Leerezeichen} eingesetzt, um die Einheit "%" auszublenden. 
Nehme ich bei den Einheiten das wieder raus, verschwinden die "29" hinter dem Batteriestand, dafür taucht "%" wieder auf.

![image](https://user-images.githubusercontent.com/57875762/103218996-d0725d80-491c-11eb-8888-e50c5ffdd910.jpeg)

Wieso hat aber die Änderung der Einheit Einfluss auf die Darstellung des Wertes? Wie blende ich denn nun die % hinter der Anzeigevariante aus?

**Comment by Zefau** [comment]
Wenn ich bei Einheit `" "` für ein Leerzeichen eintrage geht es bei mir trotzdem. Wenn ich nur ein Leerzeichen eintrage (ohne `"`), dann bekomme ich einen JSON Fehler.

Was konkret hast du bei Einheit eintragen, damit ich es nachstellen kann?

**Comment by funky4t** [comment]
@Zefau ich mache hier zu, ich hab MEINEN Fehler gefunden! 🙈
ich hab im JSON Editor einfach `{ }` eingegeben, da waren "%"  bei den Units zwar weg, aber der Wert tauchte irgendwie wieder auf. 
Mit `" "`sind die Units weg und die Visu stimmt... Sorry fürs Issue....aber Danke für deine Hilfe und Zeit. Ich schick dir die Tage mal ne Maß aus dem Süden über Paypal, Jarvis is ein so geiler Adapter und unfassbar, wie gut du ihn supportest!!! Mach weiter so und bleib gesund da oben im Norden! :)
