### ISSUE TITLE
Function not recognized while importing alias devices

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#52]
While importing alias devices the function of windows and thermostats are not automatically recognized as "windows" and "heating". Instead the function is set to "other".

**Comment by Zefau** [comment]
True story. Since I never worked with alias, I only implemented lights so far. 

I will have a look at the other functions.

**Comment by Zefau** [comment]
Should be working now with `1.0.0-beta.12`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.13`

**Comment by Zefau** [comment]
ea53cb6c1a3d13c43b788c7b26874351f84fb324
