### ISSUE TITLE
Gruppen verschieben

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#520]
Wäre es möglich gruppen zu verschieben, ist leichter wie zig states in die gruppe zu verschieben
Edit: Derzeit kann man states auch nicht verschieben
![image](https://user-images.githubusercontent.com/25475385/103200580-ff250f80-48ed-11eb-9301-a1a66d9de7e7.png)

**Comment by Zefau** [comment]
Was meinst du mit "derzeit kann man States nicht verschieben" ?

**Comment by duczz** [comment]
Früher konnte man doch die Anordnung der states im Layout verschieben, z.b. Batterie soll vor Temperatur stehen, geht nicht mehr die buttons fehlen

**Comment by Zefau** [comment]
Ist doch jetzt Drag and Drop?

**Comment by duczz** [comment]
ahhhh sorry, hat bei mir ne 2 sek verzögerung bis was passiert, klappt - mein fehler
