### ISSUE TITLE
Gerätekonfiguration 

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#521]
Die Gerätekonfiguration lässt sich nicht mehr speichern Botton ohne Funktion

**Comment by testit2020** [comment]
Die Kopierfunktion bei den Geräten ist auch betroffen.
https://forum.iobroker.net/topic/30668/jarvis-v2-0-0-just-another-remarkable-vis/2480

**Comment by Zefau** [comment]
sollte mit `v2.1.0-beta.27` wieder passen.

**Comment by duczz** [comment]
Mein Fehler ist nun korrigiert
