### ISSUE TITLE
Leeres / kein Label in StateList

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#523]
1. Jarvis konvertiert OID Werte? Beginn sollte wie folgt aussehen "Mon Dec 28 2020 15:00:00 GMT+0100 (Mitteleuropäische Normalzeit)"
2. Ein Leeres Label wird in der Vis trotzdem dargestellt (mit dem Wert den es vor der Löschung hatte in diesem Fall "Beschreibung")

![image](https://user-images.githubusercontent.com/25475385/103209288-ff7bd580-4902-11eb-9bd8-99cba87d4d84.png)

**Comment by Zefau** [comment]
Was sind OID Werte?

**Comment by duczz** [comment]
Der Iobroker Datenpunkt Wert

**Comment by Zefau** [comment]
Dann meinst du IOD ? Und nein, jarvis konvertiert eine Werte. Aber `Mon Dec 28 2020 15:00:00 GMT+0100 (Mitteleuropäische Normalzeit)` ist im ioBroker ein View auf den Zahlenwert `160916,..` nehme ich an.

**Comment by duczz** [comment]
Nene heißt schon oid, okay dann bleibt nur noch der letzte punkt über

**Comment by Zefau** [comment]
hmm, leere Labels sind nicht vorgesehen.

Zum Verstädnis: Im Widget hast du das Label leer gemacht, aber als placeholder (schattig) steht da noch was drin, oder? Also das Label des Datenpunkts aus dem Gerät?

**Comment by duczz** [comment]
Ja genau, weil ich in diesem fall kein Label bräuchte

**Comment by duczz** [comment]
@Zefau Ich habs nun via CustomHTML gelöst, könnte man nun theoretisch schließen. 
Wäre es sinnvoll die timestamp konvertierung mit in Jarvis einzubinden? Man könnte es anhand der OID Rolle "value.time" erkennen und dann automatisch konvertieren lassen

**Comment by Zefau** [comment]
>  Wäre es sinnvoll die timestamp konvertierung mit in Jarvis einzubinden? Man könnte es anhand der OID Rolle "value.time" erkennen und dann automatisch konvertieren lassen

Ja, es soll eine Möglichkeit geben eine eigene Callback Funktion zu hinterlegen, um Werte zu bearbeiten. Dann könnte man das konvertieren oder auch andere Werte anpassen.

Ich finde das Issue nur nicht mehr. Ich finde nur https://github.com/Zefau/ioBroker.jarvis/issues/312, was ebenfalls in die Richtung geht.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/416 ist es
