### ISSUE TITLE
Button / Switch Size

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#526]
Mir ist gerade aufgefallen das die Spalten Größe unterschiedlich ist z.b. zwischen Switch und Button, kannst du das anpassen oder muss man dies auch via css lösen?

![image](https://user-images.githubusercontent.com/25475385/103238990-98830e80-494c-11eb-9955-7de4f8750bd5.png)
![image](https://user-images.githubusercontent.com/25475385/103239026-ae90cf00-494c-11eb-8546-d06ffd596fa3.png)

**Comment by Zefau** [comment]
Du kannst beim Button die Größe wählen und auf klein stellen.

**Comment by duczz** [comment]
Dann ist er aber schon ziemlich klein, aber das padding passt dann bei weitem besser wie zuvor. 
Den Rest dann über CSS oder? 1,5 fänd ich besser wie 1,125

**Comment by Zefau** [comment]
kann ich nochmal schauen

**Comment by Zefau** [comment]
Schau dir nochmal die `2.1.0-beta.30` an. Dort habe ich es angepasst.

**Comment by duczz** [comment]
Ein Traum danke
