### ISSUE TITLE
Import of window alias devices

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#53]
While importing window alias devices, the state `open` should automatically mapped to the `ACTUAL` state.

**Comment by Zefau** [comment]
Sure. For all device types or only specific ones?

**Comment by braindead1** [comment]
That's a good question. The ioBroker devices adapter distinguishes between `window` and `window tilt`, whereas jarvis only kowns `window`. I used `window` in the adapter, becaue for me it doesn't matter if the window is really open or just tilted.

jarvis should mimic the functions of the devices adapter. The type of window can be recognized by the role of the `ACTUAL` state.

Below is a screenshot of `window`.
![image](https://user-images.githubusercontent.com/2136249/92319697-60f9fa80-f01b-11ea-9666-f44b9fd6ab4e.png)

The below screenshot shows `window tilt`.
![image](https://user-images.githubusercontent.com/2136249/92319701-70794380-f01b-11ea-993b-8f88e0da46cf.png)

**Comment by Zefau** [comment]
For me `tilt` is a state of `window` and not an own function. Might be easier to mimic the functions of the devices adapter, but some things are logically inconsistent to me.

**Comment by braindead1** [comment]
I fully agree with your opinion. Therefore I propose to map `open` to `ACTUAL` no matter if the window can really be opened or just tilted.

**Comment by Zefau** [comment]
Same applies to `door`. I will add that.

**Comment by Zefau** [comment]
Should be working now with `1.0.0-beta.12`.

**Comment by braindead1** [comment]
For my setup (window and not window tilt) it's working in `v1.0.0-beta.13`.

**Comment by Zefau** [comment]
ea53cb6c1a3d13c43b788c7b26874351f84fb324
