### ISSUE TITLE
Support import of devices from ioBroker.fb-checkpresence

### ISSUE THREAD

**Issue by kaip2503** [Zefau/ioBroker.jarvis#531]
Es wäre cool, wenn der Adapter Fritzbox CheckPresence als Import zur Verfügung stehen würde.

**Comment by Zefau** [comment]
@kaip2503 bitte einen Screenshot der Objekt-Struktur des Adapters bereitstellen

**Comment by kaip2503** [comment]
Anbei ein paar Screenshots. Ich hoffe das passt so, ansonsten gerne kurz bescheid geben. 

Über den Adapter lasse ich zum einen die Anwesenheit prüfen und zum anderen bietet es eine Liste aller an der FB angebundenen Geräte inkl. "aktiv Status" und IP. Ebenso ein paar Informationen zum Gast WLAN.

<img width="78" alt="Bildschirmfoto 2020-12-29 um 12 06 48" src="https://user-images.githubusercontent.com/73375585/103279768-dde82000-49ce-11eb-9128-7a7e24529101.png">
<img width="1410" alt="Bildschirmfoto 2020-12-29 um 12 07 42" src="https://user-images.githubusercontent.com/73375585/103279772-e04a7a00-49ce-11eb-9645-71d6510a59e9.png">
<img width="1403" alt="Bildschirmfoto 2020-12-29 um 12 08 00" src="https://user-images.githubusercontent.com/73375585/103279778-e3456a80-49ce-11eb-8459-32d2625c3c41.png">
<img width="1407" alt="Bildschirmfoto 2020-12-29 um 12 08 54" src="https://user-images.githubusercontent.com/73375585/103279782-e6405b00-49ce-11eb-80ac-a202d7081ec4.png">
<img width="1401" alt="Bildschirmfoto 2020-12-29 um 12 09 17" src="https://user-images.githubusercontent.com/73375585/103279783-e6d8f180-49ce-11eb-9b47-00a04d126bdd.png">
