### ISSUE TITLE
Use Icon Stil property in secondary data point

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#535]
Right now all secondary data points are grey
<img width="486" alt="Bildschirmfoto 2020-12-29 um 20 33 41" src="https://user-images.githubusercontent.com/2972703/103309563-b8323980-4a15-11eb-8cbf-19945df282eb.png">

It would be great if the secondary data points also use the Icon Stil property like this
<img width="486" alt="2" src="https://user-images.githubusercontent.com/2972703/103309611-d730cb80-4a15-11eb-8c75-81bff76ca69e.png">

**Comment by Zefau** [comment]
@stephan1827 @voyage200 @testit2020 bitte für https://github.com/Zefau/ioBroker.jarvis/issues/456 voten. Habe erst jetzt gesehen, dass dies hier ein Duplikat ist.
