### ISSUE TITLE
Allow usage of Json-Format for Device Label also

### ISSUE THREAD

**Issue by DNC74** [Zefau/ioBroker.jarvis#536]
Hi, it would be nice to have the ability to format the Label of a Device by usage of Json-Format like at the other fields also
![2020-12-29 23_42_57-JarVis und 10 weitere Seiten - Persönlich – Microsoft​ Edge](https://user-images.githubusercontent.com/72687758/103318748-b2e1e880-4a2f-11eb-8d7b-c8c39eb802bd.png)
.

**Comment by Zefau** [comment]
@DNC74 added in v3
