### ISSUE TITLE
Remote Control by ioBroker DP

### ISSUE THREAD

**Issue by testit2020** [Zefau/ioBroker.jarvis#537]
In ioBroker.vis there is the possiblity to remote control the view which should be shown on the browser. Therefore it would be nice to have that function also in jarvis. 
I would imagine some Datapoints in iobroker.jarvis which have the content of:

**browserConnectedNumber**: How many connections using jarvis
**browserIdsJson**:  Array of Ids from the browser (Android Tablets andsoon..)
**browserSend**: (false/true) or as Command {} to send to a certain browser a message to open there a certain tab-x from jarvis
**browserCmd**: ""
**browserTab**: selection of the tab-x which are used in jarvis, automatically updated by jarvis
**browserID**: which should be used

Then everybody has the possibility to change the tab-x in jarvis by iobroker control. In some cases for sensor actions.

Thank you.
see https://forum.iobroker.net/topic/30668/jarvis-v2-0-0-just-another-remarkable-vis/2612

**Comment by daolis** [comment]
@testit2020 duplicate of #111 ?!

**Comment by mcuiobroker** [comment]
Kann auch geschlossen werden. Ist ja schon alles umgesetzt.

**Comment by Zefau** [comment]
danke für's Nachhalten
