### ISSUE TITLE
HMIP-SWDO open wird nicht richtig dargestellt

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#538]
Der HMIP-SWDO liefert 0 und 1 anstatt true und false. Die Anzeigevariante muss daher {"0":"window#open#false","1":"window#open#true"} sein und der Icon Stil entsprechend {"0":"window-closed-variant","1":"window-open-variant"}

**Comment by Zefau** [comment]
Kannst du nochmal mit `v2.1.0-beta.34` prüfen bitte?

**Comment by stephan1827** [comment]
Fast, Icon muss auch noch auf 0 und 1

<img width="303" alt="Bildschirmfoto 2020-12-30 um 11 42 54" src="https://user-images.githubusercontent.com/2972703/103346415-346b6200-4a94-11eb-9934-139254bb7960.png">

**Comment by Zefau** [comment]
Sollte bereits so passen. In der Konfiguration zeigt er ausgegraut die allgemeine Fallback-Konfiguration, jedoch sollte es in der vis selbst passen.

Ist es in der vis nach wie vor nicht funktional?

**Comment by stephan1827** [comment]
Nope, wird auch mit beta 34 nicht richtig angezeigt
<img width="495" alt="Bildschirmfoto 2020-12-30 um 12 22 59" src="https://user-images.githubusercontent.com/2972703/103348289-dc375e80-4a99-11eb-877d-56e65344cfac.png">

**Comment by Zefau** [comment]
Über welchen Adapter (hm-rpc oder hmip) hast du SWDO importiert? Ist das Gewerk richtig auf "Fenster" (`window`) gesetzt?

**Comment by Zefau** [comment]
Schau bitte nochmal mit `v2.1.0-rc.1`.

**Comment by stephan1827** [comment]
Sorry, auch mit RC1 geht das nicht, kann das denn überhaupt gehen wenn unter Icon immer noch true und false steht?

<img width="403" alt="Bildschirmfoto 2020-12-30 um 12 51 03" src="https://user-images.githubusercontent.com/2972703/103349715-e4919880-4a9d-11eb-91b0-d964940def24.png">

**Comment by Zefau** [comment]
Im Backend steht:
```
	"open": {
		"bodyElement": null,
		"actionElement": null,
		
		"icon": {
			"0": "window-closed-variant",
			"1": "window-open-variant",
			"false": "window-closed-variant",
			"true": "window-open-variant"
		},
		"display": {
			"0": "window#open#closed",
			"1": "window#open#opened",
			"2": "window#open#opened",
			"false": "window#open#closed",
			"true": "window#open#opened"
		}
	}
```

**Comment by stephan1827** [comment]
So sieht der Code aus wenn ich es von Hand ändere und es funktioniert
<img width="1277" alt="Bildschirmfoto 2020-12-30 um 14 29 58" src="https://user-images.githubusercontent.com/2972703/103354368-aa2ef800-4aab-11eb-8f1d-4a33e7f29f57.png">

Und so sieht es aus wenn ich es automatisch importiere
<img width="1273" alt="Bildschirmfoto 2020-12-30 um 14 30 11" src="https://user-images.githubusercontent.com/2972703/103354400-b6b35080-4aab-11eb-8942-f8cbb98f74ea.png">

**Comment by Zefau** [comment]
Wie heißt der Datenpunkt-Bezeichner bei dir? Der muss  `open` sein, damit die Standard-Werte greifen.

**Comment by stephan1827** [comment]
Mit dem aktuellen RC3 funktioniert es
