### ISSUE TITLE
Import of heating alias devices

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#54]
While importing heating alias devices, the following mapping should be applied:

`temperature`: Display state = `ACTUAL`
`setTemperature`: Display state = `SET`, trigger state = `SET`

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/52

**Comment by Zefau** [comment]
Should be working now with `1.0.0-beta.12`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.13`

**Comment by Zefau** [comment]
ea53cb6c1a3d13c43b788c7b26874351f84fb324
