### ISSUE TITLE
Import lowBattery for homematic device HM-Sec-SCo

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#540]
For HM-Sec-SCo the data point lowBattery is missing

<img width="935" alt="Bildschirmfoto 2020-12-30 um 11 46 24" src="https://user-images.githubusercontent.com/2972703/103346657-f15dbe80-4a94-11eb-84b5-4ae15fc19935.png">

This is the additional data point that is missin

<img width="912" alt="Bildschirmfoto 2020-12-30 um 11 48 02" src="https://user-images.githubusercontent.com/2972703/103346674-fe7aad80-4a94-11eb-93c2-30880db8abec.png">

**Comment by Zefau** [comment]
The is already considered, but in the past betas was a mistake which prevented it from being handed through. However, please try to import that device with `v2.1.0-beta.34`, which should be working correctly.

**Comment by Buddinski88** [comment]
> The is already considered, but in the past betas was a mistake which prevented it from being handed through. However, please try to import that device with `v2.1.0-beta.34`, which should be working correctly.

Same issue for me with the mentioned version.

**Comment by Zefau** [comment]
@stephan1827 Kannst du nochmal mit `v2.1.0-rc.2` prüfen?

**Comment by Buddinski88** [comment]
@Zefau, meinerseits passt nun alles. Danke dir 👍

**Comment by stephan1827** [comment]
Yep, jetzt passts
