### ISSUE TITLE
Homematic/Raspberrymatic-Geräte werden doppelt beim Import angezeigt

### ISSUE THREAD

**Issue by Buddinski88** [Zefau/ioBroker.jarvis#542]
** Voraussetzungen**
- Getestet mit Jarvis Version **2.1.0-beta.34**

**Beschreibe den Fehler**
Beim Import von Geräten aus Homematic/Rapsberrymatic, werden diese doppelt aufgelistet. Einmal mit dem Namen und dann noch mal mit der Seriennummer.

Info: In ioBroker habe ich mehrere Instanzen (ich glaube das wurde automatisch so erstellt, wenn ich mich richtig erinnere) von Homematic/Raspberrymatic. 

**Erwartetes Verhalten**
Ich habe in Homematic/Raspberrymatic meine Geräte nach folgendem Schema angelegt:
- RAUMKURZBEZEICHNUNG_FUNKTIONKURZBEZEICHNUNG
- Bsp.: ![image](https://user-images.githubusercontent.com/50332516/103374197-37d40d00-4ad7-11eb-94d2-d16101ed033a.png)

Aktuell zeigt der Importer dann das Gerät BUE_DL und dann noch mal das Gerät mit der Seriennummer OEQ1147364.

![image](https://user-images.githubusercontent.com/50332516/103374315-900b0f00-4ad7-11eb-8ba1-8e75ba18ab30.png)

![image](https://user-images.githubusercontent.com/50332516/103374351-ac0eb080-4ad7-11eb-838e-476803cf329f.png)

Meines Verständnisses nach reicht der Import der Geräte anhand des in Homematic/Raspberrymatic definierten Namens. So würde es nicht doppelt beim Import auftauchen. Inhaltlich sehen beide Geräte nämlich identisch aus.

**Mögliche Ursache**
Im ioBroker habe ich mehrere Instanzen von Homematic/Raspberrymatic, welche sofern ich mich nicht täusche, automatisch so angelegt wurden. Darin finde ich die Geräte jeweils mit Namen und Seriennummer. Das wird sicher die Ursache sein?

**Comment by Zefau** [comment]
@Buddinski88 Could you check this with v3?

**Comment by Buddinski88** [comment]
@Zefau i will do the tests this evening and give you a Feedback.

**Comment by Buddinski88** [comment]
@Zefau, unfortunately a test is not possible, because after the installation of v3.0.0-alpha.70 the page gets into a loading loop after the first load. http://iobroker-prod:8082/jarvis/index.html#/instance=0&socketHost=&socketPort=8082 is reloaded again and again.

**Comment by Zefau** [comment]
The URL is wrong for v3. Socket Port has changed (to `8400`). I recommend to open it up from ioBroker Dashboard once. 

Furthermore you need to whitelist the host in the adapter settings.

**Comment by Buddinski88** [comment]
Ok, now it is working.

After perfom the automatic device import it is still the same behaviour.
The Homematic devices are created twice. Once with the name and then again with the serial number.

Can I provide more data for analysis?

**Comment by Zefau** [comment]
Lese gerade, dass du schon selbst geschrieben hast das es dann den zwei Instanzen liegt. Der ist korrekt und die Ursache. Insofern wäre es auch kein Bug sondern richtig, dass er die findet.

Die zwei Instanzen brauchst du nicht oder hast du zwei CCU?

ich kann aber trotzdem doppelte raussortieren.
