### ISSUE TITLE
Introduce new functions

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#546]
- [x] household appliances
- [x] scenes
- [x] switches

**Comment by Zefau** [comment]
added with `v2.2.0-beta.9`.

**Comment by SevenUp666** [comment]
@Zefau ist mit "scenes" der Szenen-Adapter gemeint?
Wenn ja, dann wird er mit beim Geräte Import nicht angezeigt

**Comment by Zefau** [comment]
Nein, es geht um die Liste der verfügbaren Gewerke:

![image](https://user-images.githubusercontent.com/14368811/104514260-3cc5b000-55f1-11eb-8884-269b7dacf397.png)

**Comment by testit2020** [comment]
https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/2964

**Comment by Zefau** [comment]
@testit2020 die Liste sollte mit `v2.2.0-beta.16` nun auch in Chrome sortiert sein.

**Comment by Zefau** [comment]
@testit2020 passt das eigentlich nun bei dir?

**Comment by testit2020** [comment]
Wird sauber sortiert. Chrome,Firefox,Edge geprüft.
