### ISSUE TITLE
Import of light alias devices

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#55]
Using the role of the `ACTUAL` state it is possible to distinguish between dimmers and on/off lights.

![image](https://user-images.githubusercontent.com/2136249/92321014-8e987100-f026-11ea-847e-ba7a4a42a30e.png)

For dimmers (role = `value.dimmer`) the following mapping should be applied:
`level`: Display state = `SET`, trigger state = `SET`

For on/off lights (role = `switch.light`) the following mapping should be applied:
`power`: Display state = `SET`, trigger state = `SET`

**Comment by Zefau** [comment]
Resolved with `1.0.0-beta.13`.

**Comment by braindead1** [comment]
In `v1.0.0-beta.13` it's working for dimmers, but not for on/off lights.

**Comment by Zefau** [comment]
How about `1.0.0-beta.14`?

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.14`

**Comment by Zefau** [comment]
232a27d483902e17ae3b99272605606db57212af
