### ISSUE TITLE
iframe - relative url

### ISSUE THREAD

**Issue by michiproep** [Zefau/ioBroker.jarvis#556]
Ich habe ein Problem mit dem iFrame widget. Es scheint so, als ob das widget automatisch ein "http://" der Url voranstellt und somit die Möglichkeit zur Verwendung von relativen Urls ausschließt.
Da ich iobroker sowohl intern als auch via DynDns nutze führt das zu dem Problem, dass ich entweder nur von intern oder extern den iframe angezeigt bekomme. Nebeneffekt bei absoluten Urls ist auch, dass man sich ggf. mehrmals authentifizieren muss, je nachdem ob der iframe mit seiner absoluten Url faktisch in einer anderen toplevel domain liegt.

Zusätzlich wäre es super, wenn man einen Datenpunkt als Url-Quelle hat, wenn es eine Option gäbe, die den Link in eine relative Url umwandelt. (gilt auch für DisplayImage widget)
Manche Adapter, zB Ring, erstellen einen Datenpunkt "SnapshotUrl" mit "http://iobroker:8082/..." was dann natürlich zum selben Problem führt.

**Comment by Zefau** [comment]
Welche Version von jarvis nutzt du?

**Comment by michiproep** [comment]
Die 2.0.0

**Comment by Zefau** [comment]
Dann bitte auf die 2.1 gehen, da ist das mit dem vorangestellten `http` raus.

**Comment by Zefau** [comment]
Beim DisplayImage Modul kann auch ein Datenpunkt angegeben werden. Beim iFrame aktuell noch nicht.

**Comment by michiproep** [comment]
Wann wird denn 2.1 released?

Holen Sie sich Outlook für iOS<https://aka.ms/o0ukef>
________________________________
Von: Zefau <notifications@github.com>
Gesendet: Saturday, January 2, 2021 9:46:23 AM
An: Zefau/ioBroker.jarvis <ioBroker.jarvis@noreply.github.com>
Cc: Proepster, Michael <M.Proepster@bkr.de>; Author <author@noreply.github.com>
Betreff: Re: [Zefau/ioBroker.jarvis] iframe - relative url (#556)


Dann bitte auf die 2.1 gehen, da ist das mit dem vorangestellten http raus.

**Comment by Zefau** [comment]
@michiproep 2.1 ist bereits im latest repository

**Comment by michiproep** [comment]
Danke. Habe jetzt auf 2.1 upgegradet. Leider besteht das Problem immer noch.
Habe verschiedene Varianten der Url in verschiedenen Browsern ausprobiert, immer das selbe Ergebnis: http:// wird vorangestellt.

[cid:image001.png@01D6E20D.F43B0850]


Von: Zefau <notifications@github.com>
Gesendet: Sonntag, 3. Januar 2021 19:55
An: Zefau/ioBroker.jarvis <ioBroker.jarvis@noreply.github.com>
Cc: Proepster, Michael <M.Proepster@bkr.de>; Mention <mention@noreply.github.com>
Betreff: Re: [Zefau/ioBroker.jarvis] iframe - relative url (#556)


@michiproep<https://github.com/michiproep> 2.1 ist bereits im latest repository

**Comment by Zefau** [comment]
jo, hast recht, sorry, hab's im Code übersehen

**Comment by Zefau** [comment]
Sollte mit `v2.2.0-beta.3` behoben sein.

**Comment by Zefau** [comment]
@michiproep kannst du das mit der beta gegenprüfen, ob es passt?
