### ISSUE TITLE
Jährliche Termine werden in "Calendar" nicht angezeigt

### ISSUE THREAD

**Issue by Bibo1984** [Zefau/ioBroker.jarvis#557]
Hallo Erstmal danke für diesen Hammer Adapter!!!!

ich wollte gerade einen weiteren Kalender in der Vis integrieren, dieser enthält nur Jährliche Termine (Geburtstage, etc.)
diese werden alle nicht angezeigt. Wenn ich einen "normalen Termin hinzufüge wird dieser sofort angezeigt.

habe es mit der aktuellen Beta getestet: v2.1.0-rc.5
Kalender importiere ich über google ICS (Privat)

**Comment by Zefau** [comment]
@Bibo1984 sollte mit `2.2.0-beta.6` behoben sein.

**Comment by Bibo1984** [comment]
@Zefau Ja & Nein...

Es werden in der neuen Beta zwar Termine angezeigt aber nicht alle und manche im falschen Monat.
Siehe Beispielbilder, ich hoffe es ist klar?!


![1](https://user-images.githubusercontent.com/71224792/103894137-c3a8f300-50ee-11eb-82b0-6549c155bfdf.png)
![2](https://user-images.githubusercontent.com/71224792/103894149-c7d51080-50ee-11eb-94f0-a7049a369c4f.png)
![3](https://user-images.githubusercontent.com/71224792/103894154-c99ed400-50ee-11eb-8df0-e0bb13b91d42.png)
![4](https://user-images.githubusercontent.com/71224792/103894158-cad00100-50ee-11eb-90cf-95e4569156fc.png)
![5](https://user-images.githubusercontent.com/71224792/103894162-cc99c480-50ee-11eb-8226-956b8c9fcdce.png)

**Comment by Zefau** [comment]
@Bibo1984 kannst du etwas zu den Terminen sagen? Sind das wiederkehrende Termine? Haben die spezielle Einstellungen hinsichtlich der Wiederkehr (also wöchentlich; nur alle zwei Wochen; jährlich am ersten eines Monats, etc.) ?

**Comment by Zefau** [comment]
@Bibo1984 mit `v2.2.0-beta.17` sollten ein paar fehlende Events wieder da sein. Die falsch platzierten Events müssten wir gemeinsam aber nochmal näher untersuchen.

**Comment by simonweimar** [comment]
Bei mir sind es Serientermine die nicht angezeigt werden. Diese Termine wiederholen sich wöchentlich immer, also ohne Ende im Kalender.
Habe die 2.2.0-beta.17 installiert.

**Comment by Bibo1984** [comment]
@Zefau Hab mir die Beta 17 drauf geladen und leider hat sich hier keine Besserung ergeben.
es handelt sich bei mir beim allen Terminen um Jährlich wiederkehrende Termine (Geburtstage etc.) ohne Enddatum.
Von den Einstellungen her denke ich sonst nichts besonderes (Siehe Screenshot)
![n1](https://user-images.githubusercontent.com/71224792/104844615-8ce29200-58d1-11eb-87a5-38804ff438f7.png)

Hatte auch noch einen Jährlichen Termin der nicht ganztägig war, dieser wurde nicht angezeigt.

Einen Wöchentlichen Termin (Ganztägig) habe ich mal testweise bei mir eingefügt (auch früher schon mal) und dieser wurde bei mir korrekt angezeigt. Einen nicht ganztägigen wurde wie von simonweimar erläutert nicht angezeigt. 
@simonweimar: Bei dir war es kein ganztägiger Termin oder?

ich habe mir auch noch mal ganz genau durchgeschaut:
Januar - OK
Februar - Termine vom Februar da + Termin 1.3.
März - Termin 1.3 korrekt, Restliche Termine Fehlen + Termine vom Februar sind da
April - Alle Termine da + Termin vom 1.5.
Mai - Termin 1.5. korrekt, restliche fehlen + Termine vom April sind da
Juni - OK
Juli - OK
August - Termine August da + Termin 1.9.
September - Termin 1.9. korrekt, restlich Termine fehlen + Termine vom August sind da
Oktober - OK
November - OK
Dezember - OK

Was auffällt ist, dass immer wenn ein Termin auf den 1. fällt wird dieser zusätzlich im Vormonat angezeigt und der Monat in dem der Termin ist nicht korrekt. Konte dies auch nachstellen als ich im Dezember einen Termin erstellt habe wurde dieser wie beschrieben zusätzlich im November angezeigt und im Dezember waren abgesehen vom 1. nur noch die Termine vom November drin.

Anbei mal noch mein Kalender als ICS das du es leichter nachstellen kannst. 
Die Termine sind umbenannt und durchnummeriert, sonst habe ich aber nichts daran geändert. 
(Nummern kommen nicht alle hintereinander)
[KALENDER.zip](https://github.com/Zefau/ioBroker.jarvis/files/5826205/KALENDER.zip)

**Comment by simonweimar** [comment]
Ja, es sind keine ganztägigen Termine.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/573897

**Comment by Zefau** [comment]
@Bibo1984 Vielen dank nochmal für den Kalender-Download. Das hilft sehr.

Wie müsste das Zielbild aussehen?
Januar: 4 Einträge am 10., 11., 18. und 19. ?
Februar: 2 Einträge am 18. und 20. ?
März: 3 Einträge am 01., 24. und 27. ?
...

**Comment by Zefau** [comment]
Bitte schau mal mit `v2.2.0-beta.33`

**Comment by Bibo1984** [comment]
@Zefau das sieht wirklich gut aus! Bei mir passt das jetzt mit allen Terminen die ich drin habe.

**Comment by SWE1008** [comment]
Bei mir werden die Termine leider immer noch nicht angezeigt. Ich habe iCloud Kalender. Habe alles neu gestartet und Browser Cache gelöscht.

**Comment by Zefau** [comment]
GF a

**Comment by Zefau** [comment]
@SWE1008 alle Termine werden nicht angezeigt oder wie du oben geschrieben hast nur Serientermine  nicht?
> Bei mir sind es Serientermine die nicht angezeigt werden. Diese Termine wiederholen sich wöchentlich immer, also ohne Ende im Kalender.

**Comment by SWE1008** [comment]
Nur die Serientermine. Alles andere wird korrekt angezeigt.

**Comment by Zefau** [comment]
Kannst du mir das CalDav zur Verfügung stellen, damit ich das analysieren kann? Auch gerne nur Auszüge.

**Comment by SWE1008** [comment]
Ich habe mal ein Neuen Kalender mit Test Terminen erstellt. Ist ein öffentlicher Kalender, wie der um den es eigentlich geht auch. Auch bei diesem werden die Termine nicht angezeigt. Es sind wöchentliche Termine ohne Ende.
Hier der Link: http://p51-caldav.icloud.com/published/2/MTAxNDU1OTAzMjEwMTQ1NSZE_FhgifNEpz_kDKa31a90DTDVIutuEmvQQDZndWJR

So ist er im iCal Adapter auch eingebunden. Da werden alle Termine angezeigt.

**Comment by Zefau** [comment]
Bei mir scheint es zu gehen:

![image](https://user-images.githubusercontent.com/14368811/107126842-892fa300-68b2-11eb-9559-db0197ebdf7b.png)

und dann weiter z. B. im September:
![image](https://user-images.githubusercontent.com/14368811/107126941-14a93400-68b3-11eb-9216-71bcd538e091.png)

In den Daten sind 3 Termine enthalten, davon 2 wiederkehrend:
- `Test Termin`: Wöchentlich jeden Freitag ab 20210226
- `Test1 Termin`: Wöchentlich jeden Samstag ab 20210206 (also heute)

Diese funktionieren beide bei mir mit `v2.2.0-beta.33`. Getestet mit Firefox und Chrome (auf Windows).

**Comment by SWE1008** [comment]
Ok, nun funktioniert es. Naja fast.
Ich habe das Widget eben gelöscht und neu angelegt. Dann wurden die wiederkehrenden Termine vom neuen Kalender auch angezeigt. Wenn ich nun beim bestehenden Kalender wiederkehrende Termine neu anlege werden die auch angezeigt. Nur die bereits bestehenden Termine werden nicht angezeigt. Macht aber nichts, ich leg die einfach neu an. Dann passt das.
Kannst das Issue also schließen.
Vielen Dank für die Hilfe.

**Comment by Zefau** [comment]
Alles klar. Natürlich sehr merkwürdig. Aber immerhin konnten wir es lösen :-)

**Comment by itsme1893** [comment]
@Zefau Funktioniert bei mir leider immer noch nicht
https://forum.iobroker.net/post/573897

Termin mit Start und Endzeit: Wiederkehrende Termine (wöchentlich, monatlich oder jährlich) funktionieren nicht. 
Ganztages Termine: Jährlich und wöchentlich funktionieren // monatlich funktioniert nicht - macht den Eintrag täglich rein.

Die Probleme mit den falschen Daten (immer +1 Tag) bei den Geburtstagen (jrl. wiederkehrende, ganztages Termine) besteht auch noch.

Danke Dir schonmal für Deine Unterstützung

**Comment by itsme1893** [comment]
@Zefau Funktioniert bei mir leider immer noch nicht
https://forum.iobroker.net/post/573897

Termin mit Start und Endzeit: Wiederkehrende Termine (wöchentlich, monatlich oder jährlich) funktionieren nicht.
Ganztages Termine: Jährlich und wöchentlich funktionieren // monatlich funktioniert nicht - macht den Eintrag täglich rein.

Die Probleme mit den falschen Daten (immer +1 Tag) bei den Geburtstagen (jrl. wiederkehrende, ganztages Termine) besteht auch noch.

Danke Dir schonmal für Deine Unterstützung

**Comment by Zefau** [comment]
Kannst du mir den Kalender irgendwie zum testen zur Verfügung stellen? 

Hast du mal versucht das Widget neu anzulegen? Das scheint ja paradoxerweise zu klappen.

**Comment by SWE1008** [comment]
Ich habe es nochmal bei mir getestet. Meine wiederkehrenden Termine sind alles ganztägige Termine. Diese werden korrekt angezeigt.
Allerdings ist es so wie @itsme1893 schreibt: Wiederkehrende Termine mit Start und End Datum werden nicht angezeigt.

Du kannst meinen Test Kalender gerne nochmal verwenden. Hier ist ein wiederkehrender ganztägiger Termin (ab Fr. 26.02.) drin und ein wiederkehrender mit Start und End Zeit (ab heute). Du kannst hier Testweiße auch selbst Termine einstellen falls das nötig sein sollte.

**Comment by itsme1893** [comment]
@Zefau: 
Sorry, bin jetzt erst wieder an meiner Visualisierung dran - reicht Dir der Testkalender von @SWE1008 aus oder kann ich noch mit Input helfen?

Bezgl. den falschen Daten im Geburtstagskalender (Situation B in Foren Eintrag - Link oben) habe ich eben etwas rumprobiert, neue angelegte Termine werden korrekt angezeigt. Wenn ich einen der falschen Einträge verschiebe, bleiben sie im jarvis dennoch auf dem initial Datum stehen. Insgesamt ein merkwürdiges Verhalten, da sich aber auch im Forum niemand mit ähnlichem Problem gemeldet hat, gehe ich von einem individuellen Problem aus - werde jetzt die Einträge nochmal anlegen.

**Comment by Zefau** [comment]
Informationslage passt soweit. Ich bin gerade dran.

**Comment by Zefau** [comment]
`2.2.0-beta.36`

**Comment by itsme1893** [comment]
Hi @Zefau !
Ich habe die neue beta36 getestet.
Soweit ich das getestet habe funktioniert es soweit, dass die Termine wiederkehrend angezeigt werden.

Jedoch gibt es noch Probleme bei der Anzeige der Datumswerte - mache ich ein anderes Issue auf, da das nichts mehr mit jährlich wiederkehrenden Terminen zu tun hat. 

Danke!

**Comment by SWE1008** [comment]
Kann ich bestätigen. Die Termine werden nun alle angezeigt. Das Problem mit der Anzeige der Datumswerte habe ich ebenfalls.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/654
