### ISSUE TITLE
iframe

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#558]
Ich hab ein Problem mit VIS iFrames in Jarvis siehe Video, die iFrames werden auf den zuletzt geöffneten iFrame zurückgesetzt obwohl ein anderer fixer Wert in jedem iframe hinterlegt ist

Öffne ich die URLS manuell passt alles, die iframes haben keine Aktualisierung drin wurde auch mit getestet

![jarvis](https://user-images.githubusercontent.com/25475385/103458400-e1014a00-4d07-11eb-9801-5c7e73c20d4b.gif)

**Comment by Zefau** [comment]
Hast du das nur, wenn du ioBroker.vis einbindest oder auch mit anderen Seiten ?

**Comment by duczz** [comment]
Hab ich nur mit einem VIS iframe (scheinbar auch erst seit ich zurück auf http bin, muss ich mal nochmal auf https umstellen und testen) - vllt ist es mir auch nur nicht aufgefallen

**Comment by duczz** [comment]
also auch mit https ist es so, scheinbar hab ichs nicht bemerkt oder das problem gabs in früheren versionen nicht

**Comment by testit2020** [comment]
Aktualisierungs Problem:
https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/3048

**Comment by testit2020** [comment]
Bei kleinerer Breite wird kein Scrollbalken dargestellt (kann, soll)? Ist es überhaupt möglich?
https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/3011

**Comment by testit2020** [comment]
Scrollbalken auf dem Handy kaum erkennbar:
https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/3065

**Comment by Zefau** [comment]
Sind die ioBroker.vis Seiten mit einem Refresh oder irgendwie speziell konfiguriert?

Ich hab zwei sehr einfache vis Seiten eingebunden und kann den Effekt nicht beobachten.
Liegt es ggf. am HeatingControl vis?

**Comment by duczz** [comment]
Die einzigen Einstellungen dazu sind folgende:
![image](https://user-images.githubusercontent.com/25475385/105147403-6e62dd80-5b01-11eb-98ec-293f91f1aef2.png)

**Comment by duczz** [comment]
@Zefau So nach einem Tag intensivem rumspielen, lag das Problem an der VIS Seite, auf die er immer zurück gesprungen ist, ich bin darauf gekommen weil das in der Vis auch passiert ist allerdings nur wenn man den Browser verkleinert hatte, den Fehler konnte man aber nirgends in der VIS sehen, erst nach dem kopieren aller Widgets in eine neue View und dem löschen der alten View gings wieder. - Strange & sorry für das Missverständnis, aber passierte nur im Browser wenn man ihn verkleinerte hat, und nicht direkt weswegen ich auf Jarvis tippte

**Comment by Zefau** [comment]
@duczz gibt es denn einen Fix / Workaround für jarvis, den du in ioBroker.vis umgesetzt hast? Dann kann ich das in das FAQ aufnehmen.

**Comment by duczz** [comment]
@Zefau Der Fix war lediglich eine neue View zu erstellen und die ganzen Widgets von der defekten View dort wieder rein zu kopieren. Die View hatte einen nicht sichtbaren Fehler, kein Plan wie der zustande kam
