### ISSUE TITLE
Columns on a medium screen "alle" breaks layout

### ISSUE THREAD

**Issue by simonssoftware** [Zefau/ioBroker.jarvis#559]
**Prerequisites / Voraussetzungen**
- v2.1.0

**Describe the bug / Beschreibe den Fehler**
See screenshot below.

**Expected behavior**
Same as "Columns on an (extra-)large screen".

**Screenshots**
![grafik](https://user-images.githubusercontent.com/50638485/103461834-8248ca00-4d21-11eb-854a-fc154df5ab0e.png)

**Comment by Zefau** [comment]
@simonssoftware should be resolved with `v2.2.0-beta.3`.

**Comment by simonssoftware** [comment]
Works, thanks! 👍
