### ISSUE TITLE
Levelbody -> NaN -> Keine Werte mehr seit 2.2.0 Beta 2

### ISSUE THREAD

**Issue by kaip2503** [Zefau/ioBroker.jarvis#560]
Seit Beta 2 werden bei allen meine Levelbodys nicht mehr korrekt angezeigt. 

<img width="826" alt="Bildschirmfoto 2021-01-03 um 09 11 11" src="https://user-images.githubusercontent.com/73375585/103474409-d2687080-4da3-11eb-9cdb-175db1a01f9c.png">

**Comment by kaip2503** [comment]
https://forum.iobroker.net/post/550935

**Comment by Zefau** [comment]
probiert bitte nochmal mit `v2.2.0-beta.5`.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/551084
