### ISSUE TITLE
Fehler im Browser

### ISSUE THREAD

**Issue by jayjay2601** [Zefau/ioBroker.jarvis#561]
Hallo ich habe den Fehler, das wenn man im Browser hoch oder runter fährt eine Fehlermeldung kommt.
 
![2021_01_02_13_22_57_](https://user-images.githubusercontent.com/42781232/103478478-554ef280-4dc7-11eb-9cad-4e7fab357d97.jpg)

Dies kommt in allen verwendeten Browser vor.
Ich habe auch die Logdatei von einem Browser hinzugefugt.

[192.168.178.51-1609590321633.log](https://github.com/Zefau/ioBroker.jarvis/files/5761583/192.168.178.51-1609590321633.log)

Ansonsten möchten ich noch sagen ganz tolle Arbeit die Du bzw. Ihr gemacht habt.
Danke noch mal.

**Comment by Zefau** [comment]
Hast du mit Custom CSS etwas angepasst?

**Comment by jayjay2601** [comment]
Nein habe ich nicht.

**Comment by Zefau** [comment]
@jayjay2601 kommt der Fehler direkt beim Öffnen von jarvis ? Oder war das einmalig?

**Comment by Zefau** [comment]
Es sieht so aus als würde der Fehler etwas mit deinen Tabs zu tun haben. Kannst du mir dein Layout bereitstellen bzw. zumindest die Bezeichnung der Tabs?

**Comment by jayjay2601** [comment]
Der Fehler kommt wenn ich die Seite schnell nach unten ziehe, und das auf jedem gerät, wie z.B. PC, Handy, Tablet. ich habe auch verschiedene Browser verwendet. wenn ich auf wieder auffrischen gehen und langsamen nach unten ziehen geht es wieder.
Klar kannst du das Layout haben, ich helfe wo ich kann. Sorry jetzt muss ich fragen wie kann ich es dir geben?

**Comment by Zefau** [comment]
Hast du unter Hilfe (in den jarvis Einstellungen) eine ID?

**Comment by jayjay2601** [comment]
10c74ec1bd3512b1e0c9d2163c4e06ba59ffc92b046c1dabce580496b09a4653

**Comment by jayjay2601** [comment]
Hoffe das ist das richtige

**Comment by Zefau** [comment]
Finde leider nichts mit der ID. Kannst du mir `jarvis.0.layout` an zefau@mailbox.org schicken?
