### ISSUE TITLE
Datenpunkte (Anzeige) in Devices werden nicht gespeichert / Gelöschte tauchen wieder auf

### ISSUE THREAD

**Issue by funky4t** [Zefau/ioBroker.jarvis#564]
Hi Zefau,
hab soeben auf dein 2.2.0-beta.4 upgedatet und wollte mal meinen Tankerkönig visualisieren.

Hab ein Device Tankstelle 1 erstellt und wollte zwei Datenpunkte `E10-Preis` und `Diesel-Preis` mit `Datenpunkt(ANZEIGE)` füllen lassen. Trigger und Co. nutzen mir an dieser Stelle ja nix. Aus damaligen Erfahrung mit dem kurzzeitig defekten Explorer hab ich zuerst die Daten-Punkte aus iobroker mit copy/paste übernommen.
Nach dem Speichern war das Device inklusive der beiden Datenpunkte angelegt worden, allerdings fehlten in beiden Punkten der Eintrag unter `Datenpunkt(ANZEIGE)`. Noch kurioser ist, dass ich auf einmal zwei alte und zuvor gelöschte Datenpunkte `E10` und `Diesel` ohne Zusatz -Preis wieder im Device hatte - also es jetzt 4 statt gewollter 2 sind.

Hab das Device gelöscht und nochmal ganz neu angelegt, vom Start nur mit 2 DP - zack waren wieder 4 Datenpunkte drin und alle leer - als wenn Jarvis das gelöschte Device am Namen wiedererkannt und automatisch mit den 4 alten Datenpunkten füllt, von denen aber ebenfalls 2 gelöscht sein sollten.

Hab das Ganze wiederholt und die Datenpunkte auch mit dem Explorer gefüllt, leider identisches Verhalten.
Es scheint, als könne ich weder Datenpunkte noch Devices final löschen....bzw. Datenpunkte und Devices werden nicht sauber angelegt. 

Ich hab es jetzt mehrfach getestet, Namen variiert, völlig neue Namen verwendet und selbst da hab ich trotz 2 angelegter DP aufeinmal 4 DP und dann noch ohne Inhalt.... 

Konfiguration Device 1:
<img width="644" alt="Bildschirmfoto 2021-01-04 um 00 03 37" src="https://user-images.githubusercontent.com/57875762/103491158-a8ee2a00-4e21-11eb-8c1a-e105adb5c30f.png">

Nach Speichern:
<img width="632" alt="Bildschirmfoto 2021-01-04 um 00 05 17" src="https://user-images.githubusercontent.com/57875762/103491163-b7d4dc80-4e21-11eb-80cd-ee71fd2f73f7.png">

Konfiguration Device 2 mit geändertem Namen und ID:
<img width="1075" alt="Bildschirmfoto 2021-01-04 um 00 09 36" src="https://user-images.githubusercontent.com/57875762/103491173-d0dd8d80-4e21-11eb-806c-d3c0a142e8de.png">

Übersicht beider Devices
<img width="1021" alt="Bildschirmfoto 2021-01-04 um 00 09 04" src="https://user-images.githubusercontent.com/57875762/103491184-e18e0380-4e21-11eb-80c1-23486b9318e6.png">

**Comment by funky4t** [comment]
Nachtrag:
Es muss mit zuvor gelöschten/geänderten DP in einem Device zutun haben. 
Device Test1 habe ich nur mit DP `E10` angelegt nach Speichern hatte ich `E10` und `E10-Preis` Woher holt Jarvis den `E10-Preis`? Beide DP sind leer.

Device Test 2 habe ich ebenfalls mit DP `E10` angelegt, aber diesmal habe ich statt Tankerkönig DP die Temperatur eines meiner Xiaomis aus dem BLE Adapter ausgewählt, hier verlief alles reibungslos nach Plan, es blieb bei EINEM `E10` Datenpunkt im Device. 

Ist es denkbar, dass Jarvis bei der ersten Device-Anlage mit 4 DP und Löschung von 2 DP die gelöschten nicht "vergisst" und bei zukünftiger Integration in ein Device, diese anhand eines vermeintlich bekannten DP aus iobroker.Tankerkönig "wiederbelebt"? Es hängt ja weder am Devicenamen, noch am DP-Namen in Jarvis. Bleibt also nur noch der DP-Name aus dem iobroker Adapter. Und die Frage warum alle leer sind? Hab da leider bei der allerersten Deviceanlage nicht aktiv drauf geachtet, weiß nur noch, dass ich einige DP im Ursprungsdevice gelöscht und wieder umbenannt habe.

Ich teste mal morgen noch mit einer anderen Tankstelle aus dem Adapter, nicht dass es irgendwie am Tankerkönig Adapter hängt. Aber vielleicht kannst Du das Phänomen bereits reproduzieren oder hast ne Idee?

<img width="1329" alt="Bildschirmfoto 2021-01-04 um 00 19 24" src="https://user-images.githubusercontent.com/57875762/103491555-1b143e00-4e25-11eb-81f5-ea54c633c76b.png">

**Comment by funky4t** [comment]
Weitere Test nach Reboot des Raspi und somit Neustart aller Adapter. Phänomen immer noch vorhanden. Anbei der Screenshot zu den zwei Tests:

<img width="1186" alt="Bildschirmfoto 2021-01-04 um 09 46 34" src="https://user-images.githubusercontent.com/57875762/103518158-8be24700-4e73-11eb-9d2c-cf2c6eca9090.png">

Gerät Test3 als Sensor mit `E10-Preis` und Tanker-DP einer bisher nicht genutzten Station angelegt, es taucht ein weiterer DP `E10` ohne Zusatz im Gerät auf. Beide DP sind danach leer.
Im Test3 einen Datenpunkt `E5-Preis` mit Tanker-DP hinzugefügt. Es erscheint ein zweiter DP `E5`, wieder sind beide nicht befüllt. 

Device Test4 erstellt, Datenpunkt `E10ohneminuspreis` mit dem exakt gleichen Tanker-DP wie in Test3 verwendet gefüllt. Ergebnis: Es bleibt bei dem einen angelegten DP und dieser hat auch den gewünschten Tanker-DP unter Anzeige.

Zusätzlich beobachtet: Schreibe ich in Test3 in die automatisch erstellten DP `E10` und `E5` nachträglich nochmal den Tanker-DP, wird dieser übernommen. Bei `E10-Preis` und `E5-Preis` kann ich den Tanker-DP sooft speichern wie ich will, beim erneuten Öffnen ist er wieder leer.



Kann es sein, dass das Minus in "-Preis" Probleme verursacht?

**Comment by funky4t** [comment]
<img width="1308" alt="Bildschirmfoto 2021-01-04 um 10 03 40" src="https://user-images.githubusercontent.com/57875762/103518515-2c386b80-4e74-11eb-978e-43ca4c4ae201.png">

Der Test5 macht aus `E22-Preis` den zusätzlichen DP `E22`. `E23_Preis` bleibt wie er ist ohne ungewolltes Duplikat. Der Tanker-DP wird in in der Anzeige bei `E22` und `E23_Preis` übernommen, in `E22-Preis` hingegen nicht, trotz mehrfacher Versuche.

**Comment by funky4t** [comment]
Kann es sein, dass die beta4 buggy mit Devices ist?
Ich hab dich doch in #519 mal zu einem Fensterkontakt und dessen Batterieanzeige gefragt. Das Dingen hatte ich super in der Visu und hab es danach auch nicht mehr geändert. Das Device ist "verschwunden". Ich hab mir aus der JSON Konfig mal die ID genommen und meine Devices danach durchsuchen lassen. Bleibt leider weg!

ABER da wir ja auf Beta sind, dacht ich mir, ich mache es halt NEU! Gesagt, getan, neu angelegt und zwecks alter Konfig mal schnell in #519 nachgesehen. Noch bevor ich mich versah, is das neue Device wie von Zauberhand auch weg... 

Etwas spooky, aber irgendwie passt meines Erachtens bei der Device-Verwaltunge etwas ganz und garnicht.

**Comment by Zefau** [comment]
Sehr ausführliche Fehlerherleitung, vielen Dank! `-` ist ein jarvis interner Operator, der scheinbar nicht korrekt gegen Benutzereingabe abgeschirmt ist. Ich werde es mit der kommenden beta fixen.

**Comment by Zefau** [comment]
probier bitte nochmal mit `v2.2.0-beta.5`.

**Comment by funky4t** [comment]
Moin @Zefau nach Update auf beta5 ist bei mir im Browser ALLES weiß und es wird nix mehr angezeigt.
Hab auch meine 2. Instanz geprüft, leider gleiches Spiel. 
Adapter neu gestartet....nix gebracht
Raspi Reboot....nix gebracht

Zum Glück sind die Devices und das Layout noch da! Wobei leider besagter Fensterkontakt auch darin nicht mehr zu finden ist...

**Comment by Zefau** [comment]
Fehler in der Browser Konsole (F12) ?

**Comment by funky4t** [comment]
Vor Reset aller Cookies im Firefox:
![grafik](https://user-images.githubusercontent.com/57875762/103648957-f53e8480-4f5d-11eb-82fc-c77adbb88a3a.png)

nach Cookie Reset im FF:
![grafik](https://user-images.githubusercontent.com/57875762/103649020-0e473580-4f5e-11eb-983b-92732b19fb3e.png)

**Comment by funky4t** [comment]
Moin Zefau,
ich hab zwischenzeitlich mal ein Downgrade auf 2.1.0 gemacht, da lief Jarvis wieder. Erneutes Upgrade auf beta5 hat jetzt funktioniert. 
Das Problem mit dem "-" zwischen den Datenpunkten ist gelöst und auch die darin angezeigten Datenpunkte werden jetzt sauber übernommen. 
Mein Fensterkontakt bleibt aber irgendwie im Nirvana.... Egal, das übt dann eben die Neuanlage! :)

**Comment by funky4t** [comment]
Wobei die Sprachumstellung bei der Anzeigevariante nochmal klemmt, das sollt aber nix Tragisches sein.

![grafik](https://user-images.githubusercontent.com/57875762/103766019-604f9000-501e-11eb-8398-6c4df925eb00.png)
