### ISSUE TITLE
Support import of devices from ioBroker.deconz adapter

### ISSUE THREAD

**Issue by macpo** [Zefau/ioBroker.jarvis#565]
The import of devices for the deconz adapter is limited to lights with restricted functionality. The following devices shall be supported by the import.

Additional data points like battery, lowbattery, lastupdated, reachable shall be supported if possible.

### White bulp
Expected data points: power, level, light temperatur
![image](https://user-images.githubusercontent.com/17279799/103491257-86104580-4e22-11eb-9a07-337d0516140e.png)
### Color bulp
Expected data points: power, level, light temperatur, light color, light hue
![image](https://user-images.githubusercontent.com/17279799/103491262-90324400-4e22-11eb-9392-816d456de0d3.png)
### Temperature sensor
Expected data points: temperature
![image](https://user-images.githubusercontent.com/17279799/103491268-99231580-4e22-11eb-985a-e06e5182e03f.png)
### Humidity sensor
Expected data points: humidity
![image](https://user-images.githubusercontent.com/17279799/103491271-a17b5080-4e22-11eb-8341-cd63853b3fd2.png)
### Pressure sensor 
Expected data points: pressure
![image](https://user-images.githubusercontent.com/17279799/103491275-ab04b880-4e22-11eb-9d34-78133a820c86.png)
### Water leak sensor
Expected data points: water, temperature
![image](https://user-images.githubusercontent.com/17279799/103491285-bb1c9800-4e22-11eb-9bc6-6ba6a5bf3499.png)
### Light level sensor
Expected data points: lux, temperature, (optional: lightlevel, dark, daylight)
![image](https://user-images.githubusercontent.com/17279799/103491295-c40d6980-4e22-11eb-9510-fa3bd0b8ddd1.png)
### Door sensor
Expected data points: open, temperature
![image](https://user-images.githubusercontent.com/17279799/103491297-cff92b80-4e22-11eb-96b5-be4a1dc00e8d.png)
### Presence sensor
Expected data points: presence, temperature
![image](https://user-images.githubusercontent.com/17279799/103491299-d5567600-4e22-11eb-918a-044aa3236adb.png)

**Comment by macpo** [comment]
@Zefau Offtopic: Kannst Du das Bild bei "Stimme für Deinen Feature Request ab!" nur einmal einfügen, damit der Eintrag nicht so viel Platz einnimmt?
PS: Wie kann ich Dir solche Infos besser zukommen lassen?

**Comment by Zefau** [comment]
@macpo added with `2.2.0-beta.9`. Please test and confirm everything is imported as required.

**Comment by macpo** [comment]
Alle erwarteten Objekte mit allen Werten werden importiert. Vielen Dank
