### ISSUE TITLE
Devices im Layout verschieben

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#566]
Wenn man Devices in nem Widget verschiebt wird alles zerschossen, die Werte passen dann bei vielen Devices nicht mehr zusammen bzw wurden random gewechselt

**Comment by Zefau** [comment]
Passt bei mir. 

Auf welche Version beziehst du dich? Was genau machst du und wann tritt der Fehler auf (erst beim Speichern oder direkt?) ?
Kannst du es ggf. giffen?

**Comment by duczz** [comment]
2.2.0-beta.4 - Total strange, ich hoffe via gif checkt man's, mega merkwürdiges verhalten.
![jarvis2](https://user-images.githubusercontent.com/25475385/103572700-4d797600-4ecd-11eb-86cb-f8d7e208ed77.gif)

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/552637

**Comment by Zefau** [comment]
@duczz passiert das nur, wenn du das gleiche Gerät mit unterschiedlichen Datenpunkten verwendest oder auch bei verschiedenen Geräten? 

Löst sich das Problem, wenn du nach dem Drag n' Drop 1-2 Sekunden wartest, damit es noch "ordentlich" verarbeitet wird?

**Comment by duczz** [comment]
@Zefau nope, das warten ändert nichts, und ist bei allen Geräten

**Comment by Zefau** [comment]
puh, schwieriger Fehler. Nochmal eine Nachfrage: Passiert das nur, wenn du Geräte hinzufügst oder auch, wenn du das Widget öffnest und ohne Hinzufügen Geräte verschiebst?

**Comment by duczz** [comment]
Es passiert leider immer, auch ohne neuhinzufügen

**Comment by Zefau** [comment]
@duczz könntest du prüfen, ob dies mit `v2.2.0-beta.13` behoben ist?

**Comment by duczz** [comment]
Jetzt passt es wieder danke
