### ISSUE TITLE
Value provided for LevelBody not a number!

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#567]
aktuellste version. 

habe nichts geändert seitens deconz, gab auch kein update o.ä. 

![image](https://user-images.githubusercontent.com/22169074/103560361-f026fa00-4eb7-11eb-878c-1f608eaa517c.png)

**Comment by Zefau** [comment]
probier bitte nochmal mit `v2.2.0-beta.5`.

**Comment by ma-gu-16** [comment]
ja passt.
