### ISSUE TITLE
Zeitsteuerung & Timer

### ISSUE THREAD

**Issue by hssteuerung** [Zefau/ioBroker.jarvis#569]
Würde mich freuen über eine Zeitsteuerung, dass ich verschiedene Zeitschalten programmieren kann, welche an verschieden Tagen ein und aus schaltet automatisch 

& 

Einen Timer dem ich sagen kann das x Gerät 30 Minuten an ist.

**Comment by smile-albion** [comment]
Sinnvoll wäre meiner Ansicht nach hier ein Time Picker, wie bei Android wo du eine runde Uhr hast und entsprechend erst die Stunden HH/hh und danach die Minuten MM/mm auswählen kannst.
Dann könnte man auch sehr gut Dinge wie z.B. Wecker damit bauen.

**Comment by smile-albion** [comment]
Time Picker Android-Like, siehe iobroker Forum: https://forum.iobroker.net/post/592265

**Comment by Zefau** [comment]
Der Feature Request liest sich stark wie eine eigene Logik, die besser in ioBroker.javascript bzw. Blockly realisierbar ist als in einer Visualisierung?

**Comment by smile-albion** [comment]
Nunja, bei dem Time Picker geht es ja aber im wesentlichem um die Oberfläche ion Jarvis? Diese jedenfalls wüsste ich nicht wie ich die in blockly programmieren sollte.
Das Verarbeiten der Zahlen nachher natürlich schon. Nur ist ein Time Picker auf jedem Smartphohne einfach die angenehmste Möglichkeit, eine Uhrzeit einzugeben. Insbesondere für Wecker - Scripte, aber auch alle anderen Zeitbasierten Logiken von Vorteil.

**Comment by Zefau** [comment]
> Nunja, bei dem Time Picker geht es ja aber im wesentlichem um die Oberfläche ion Jarvis?

Ja, stimmt, den kann ich einbauen. Hab falsch gedacht.

**Comment by smile-albion** [comment]
Super klasse, dass du hier weiter dran bist!

**Comment by flkontakt** [comment]
Ich schließe mich hier an, würde mich über eine Zeitschaltuhr sehr freuen, würde das ganze nochmal einfacher bedienbar machen, insbesondere bei Szenen. GIRA macht es im Homeserver auch sehr Nutzerfreundlich, siehe Bilder. 

Hat mir zu Weihnachten echt gefehlt ;-). Einfach meine Weihnachtsbeleuchtung und Zwischenstecker in eine Gruppenaktion packen und die Gruppe dann mit einer "einfachen" Zeitschaltuhr einstellen. Muss man in der Komplexität sicherlich reduzieren, die "richtigen" Programmierung dann per Blocky in iobroker

![01](https://user-images.githubusercontent.com/77227687/150671082-460305a0-4ec2-41b2-a1ca-75558168fb31.JPG)

![02](https://user-images.githubusercontent.com/77227687/150671085-b8f14972-7fdb-4696-8773-48bf36b5f14f.JPG)

![03](https://user-images.githubusercontent.com/77227687/150671086-1f404030-c5ce-44e0-aa23-7fc628b8be8b.JPG)

**Comment by Zefau** [comment]
ist in v3.1-alpha umgesetzt

**Comment by mcuiobroker** [comment]
Kannst du bitte direkt dort auch eigene jarvis-Klassen zuordnen? 
z.B. jarvis-dateAction (DatePickerAction) und jarvis-timeAction (TimePickerAction)
![image](https://user-images.githubusercontent.com/84818934/165595835-41ef886a-0d21-4688-b4df-3a8decd7a279.png)

Danke.

**Comment by Zefau** [comment]
Trigger Elemente `TimePickerAction` und `DatePickerAction` nun mit `v3.1.0-alpha.9` verfügbar.

**Comment by MarkSau** [comment]
Ich habe eine Anmerkung zum Timepickeraction. Wenn ich z.B. von 06:00 auf 07:00 umstellen will, kann ich das nur, wenn ich auf 07:0x stelle , speichere, neu öffne und dann auf 07:00 stelle. Ist etwas umständlich.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.35`

**Comment by MarkSau** [comment]
Funktioniert fast...zumindest die Auswahl Stunde / Minute. Leider wird aber trotz Maskierung HH:mm z.b. eine 6:0 geschrieben, statt 06:00.

<img width="943" alt="Screenshot 2022-08-17 at 22 28 55" src="https://user-images.githubusercontent.com/22911084/185236936-4f770218-c4c7-4a1b-bb7c-9b30c85a9455.png">

<img width="486" alt="Screenshot 2022-08-17 at 22 30 54" src="https://user-images.githubusercontent.com/22911084/185237270-ebd23120-ff52-4b5e-ac21-6652944353c6.png">

**Comment by Zefau** [comment]
@MarkSau sollte mit `v3.1.0-alpha.37` passen

**Comment by MarkSau** [comment]
@Zefau Ja danke, klappt jetzt.

**Comment by ossisp1** [comment]
Moin, welche Art von Zeitsteuerung soll das denn sein? Ein richtiger Timer mit Wochenzeitschaltuhr ists ja nicht.
Gruß
