### ISSUE TITLE
WidgetPage: Only show Body / Actions which are valid for the type of state (boolean, number, string, etc.)

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#57]
### Actions
`boolean` (or `number` with `min`/`max` `0`/`1`)
- `SwitchAction`
- `ButtonAction`
- `DropdownAction`

`number`
- `BlindLevelAction` (for function `blind`)
- `HeatingSetTemperatureBody` (for function `heating`)
- `LightLevelAction` (for function `light`)

`number` or `string`
- `LightColorAction` (for function `light`)

### Body
`number`
- `LevelBody`
- `LightColorTemperatureBody` (for function `light`)
- `LightHueBody` (for function `light`)

`number` or `string`
- `LightColorBody` (for function `light`)

**Comment by Zefau** [comment]
### Actions
`boolean` (or `number` with `min`/`max` `0`/`1`)
- `SwitchAction`
- `ButtonAction`
- `DropdownAction`

`number`
- `BlindLevelAction` (for function `blind`)
- `HeatingSetTemperatureBody` (for function `heating`)
- `LightLevelAction` (for function `light`)

`number` or `string`
- `LightColorAction` (for function `light`)

### Body
`number`
- `LevelBody`
- `LightColorTemperatureBody` (for function `light`)
- `LightHueBody` (for function `light`)

`number` or `string`
- `LightColorBody` (for function `light`)

**Comment by Erwin40** [comment]
Der ist aber sehr alt und wahrscheinlich längst erledigt, deshalb hole ich den mal hoch ;-)

**Comment by mcuiobroker** [comment]
Ja, ist erledigt.
