### ISSUE TITLE
scrollen auf tab

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#570]
hi, kann es sein das das scrollen auf dem tablet nicht mehr geht ? 

samsung galaxy tab a, yarvis aktuellste version.

**Comment by Zefau** [comment]
Was ist die "aktuellste Version"? Bitte genau benennen.

Und was genau geht beim Scrollen nicht?

**Comment by ma-gu-16** [comment]
2.2.0-beta.5

scrollen geht nicht, mit dem finger von oben nach unten ;-)

**Comment by duczz** [comment]
Test ich heute Abend mal bei mir

**Comment by duczz** [comment]
Klappt bei mir einwandfrei

**Comment by Zefau** [comment]
@ma-gu-16 kannst mal dein Layout screenshoten ?

**Comment by ma-gu-16** [comment]
hab aktualisiert, läuft nun. danke.
