### ISSUE TITLE
Widget Mobile Sortierung angeben

### ISSUE THREAD

**Issue by ma-gu-16** [Zefau/ioBroker.jarvis#571]
Wäre cool wenn man eine Reihenfolge angeben könnte wie die Elemente auf Desktop bzw vor allem auf Mobile erscheinen. 
Sobald es 1 bzw 2 spaltig wird passt die Desktop Ansicht nicht mehr 100%. 

Evtl pro Widget ein JSON mit den breakpoints und deren order.

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/system-effektprog./v3-systemprogramme/move-widget-ordernumber-in-layout

**Comment by Zefau** [comment]
implementiert mit `v3.1.0-alpha.42`

![image](https://user-images.githubusercontent.com/14368811/189987927-39ab3b47-6b89-4ba4-bffe-f9a1dd973061.png)
