### ISSUE TITLE
Zwei Taster (Ein/Aus) als "Action Element"

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#572]
Statt eines "SwitchAction" als Schalter wäre ein getrennter Ein und Aus Schalter wünschenswert.
Hintergrund: 
Es gibt z.B. Dimmer die beim ersten mal "Ein" Schalten die Lampe einschalten.
Beim zweiten mal "Ein" schalten wird das dimmen gestartet.
Beim dritten mal "Ein" schalten wird das dimmen gestoppt.

**Comment by Phil-Rei** [comment]
Wäre auch dafür. Es gibt auch Geräte, bei denen man den Status nicht kennt. z.B. 433MHz Funksteckdosen oder Markise.
Hierfür bräuchte ich zwei Buttons. Einmal für Ein(fahren) und das andere mal für Aus(fahren)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/871

**Comment by Zefau** [comment]
@Bernd9000 mit `v3.1` ist dies nun via `ButtonGroupAction` möglich. Im Standard mit zwei Buttons aus / an und mit der Anzeige-Variante beliebig viele Buttons.

**Comment by Bernd9000** [comment]
Super, funktioniert.
