### ISSUE TITLE
add additional device Types to ioBroker.hmip adapter import

### ISSUE THREAD

**Issue by dentro-git** [Zefau/ioBroker.jarvis#573]
Hey, ich habe Jarvis gerade installiert und wegen dem BROLL auch schon auf die neueste Beta aus dem jithub upgedated.

Ich habe noch weitere Geräte hier im Einsatz die super wären wenn sie funktionieren. Ich habe mal die Datenstruktur als Screenshot mit dran gepackt. Wenn ich unterstützten kann, immer gerne. Ich hab das alles im Einsatz und kann jederzeit testen :-)

- **HmIP-SWDO-I** (gleiche Konfiguration wie HMIP-SWDO, nur andere Bauform) , sollte also ein Quick Win sein 
![image](https://user-images.githubusercontent.com/77006779/103652847-fc689100-4f63-11eb-9570-b68c09d3a5fa.png)

- **HmIP-SRH** Fenstergriffsensor, fast gleich wie Türkontakt, kann nur zusätzlich zu Open und Closed noch Tilted 
![image](https://user-images.githubusercontent.com/77006779/103653275-93354d80-4f64-11eb-9a10-9cc015567798.png)

- **HmIP-STH** Temperatur und Luftfeuchte Sensor ohne Display und ohne Rad 
![image](https://user-images.githubusercontent.com/77006779/103652404-5cab0300-4f63-11eb-9615-22d5379ddba6.png)
- **HmIP-WTH-2** Wandthermostat mit Einstellrad und Display 
![image](https://user-images.githubusercontent.com/77006779/103652581-9845cd00-4f63-11eb-8c14-13155f48757c.png)

-  **HmIP-STHO** Temperatur und Luftfeuchte Sensor Aussenbereich, wie STHO nur ohne Solltemperatur  
![image](https://user-images.githubusercontent.com/77006779/103653731-3c7c4380-4f65-11eb-9b71-6d7416c21740.png)

- **HMIP-PS** Schaltsteckdose Universal 
![image](https://user-images.githubusercontent.com/77006779/103652714-c88d6b80-4f63-11eb-9424-7a42bae9dd5b.png)

Gruß und Dank für die tolle Arbeit

**Comment by Zefau** [comment]
@dentro-git danke dir für die Zusammenstellung. Mit `2.2.0-beta.6` sollten die Geräte nun gefunden werden. Könntest du das prüfen?

**Comment by dentro-git** [comment]
Hey Zefau, jetzt kategorisiert er alle, leider legt er jetzt alle ohne jegliche Datenpunkte an. 
![image](https://user-images.githubusercontent.com/77006779/103900484-23f06280-50f8-11eb-8fea-b2ac1b8ae0b8.png)
![image](https://user-images.githubusercontent.com/77006779/103900629-4d10f300-50f8-11eb-8552-382ba89e968c.png)
Mach ich was falsch?

**Comment by Zefau** [comment]
probier bitte nochmal `v2.2.0-beta.8`.

**Comment by dentro-git** [comment]
Bekomm nur die v.2.2.0-beta.7 von GitHub!? 
![image](https://user-images.githubusercontent.com/77006779/103985195-ca844400-5188-11eb-96e0-028a41084069.png)

**Comment by joe-sinclair** [comment]
Hallo Zefau, und Hallo dentro-git,
ich beschäftige mich jetzt seit gestern mit Jarvis! Gefällt mir gut und ich würde gerne mithelfen! Hab hier ein paar Sachen an Homematic IP und Shelly Geräten.
Vielen Dank für Jarvis !!!
Geräte die z.B nicht erkannt werden HmIP-STHD, SWDM, SWSD, eTRV, WRC2, FROLL, SWD.
Reichen die Screenshots wie oben für dich zum einfügen, oder brauchst du noch mehr Infos?

Von was ist es abhängig, das Shellys richtig erkannt werden? z.B. als light?

Ich bekomme im übrigen auch nur die v.2.2.0-beta 7 angezeigt!

**Comment by Zefau** [comment]
@joe-sinclair ein Screenshot je Gerät wie oben zu sehen genügt.

**Comment by joe-sinclair** [comment]
Vielen Dank und los gehts :-)

- **HmIP-FROLL** Rolladenaktor
![Bildschirmfoto FROLL 1](https://user-images.githubusercontent.com/77187899/104087852-0be92200-5263-11eb-83e5-9d386cec4707.png)
![Bildschirmfoto FROLL 2](https://user-images.githubusercontent.com/77187899/104087860-15728a00-5263-11eb-816f-ee3d76da72c3.png)


- **HmIP-WRC2** Schalter
![Bildschirmfoto WRC2](https://user-images.githubusercontent.com/77187899/104087869-20c5b580-5263-11eb-9ab5-3e14830adf52.png)

- **HmIP-eTRV** Heizkörperthermostat
![Bildschirmfoto eTRV](https://user-images.githubusercontent.com/77187899/104087967-aa758300-5263-11eb-8b9e-9b0da13a170a.png)

- **HmIP-eTRV2** Heizkörperthermostat
![Bildschirmfoto eTRV-2](https://user-images.githubusercontent.com/77187899/104087972-b103fa80-5263-11eb-89d3-ba84ed2af0fa.png)

- **HmIP-SWD** Wassersensor
![Bildschirmfoto SWD](https://user-images.githubusercontent.com/77187899/104087976-b6614500-5263-11eb-9308-961dc8ec36f9.png)

- **HmIP-SWSD** Rauchmelder
![Bildschirmfoto SWSD](https://user-images.githubusercontent.com/77187899/104087987-c24d0700-5263-11eb-8ec6-0de7faaebc6d.png)

- **HmIP-SWDM** Fenstersensor mit Magnet
![Bildschirmfoto SWDM](https://user-images.githubusercontent.com/77187899/104087990-c711bb00-5263-11eb-808d-69db58797e89.png)

- **HmIP-STHD** Raumtemperatur/ Feuchtigkeit mit Display
![Bildschirmfoto STHD](https://user-images.githubusercontent.com/77187899/104087993-cc6f0580-5263-11eb-8443-9a5c176edbf4.png)

Wenn ich etwas helfen kann...jederzeit! Hab alle Geräte im Einsatz!

**Comment by dentro-git** [comment]
Hey, mit der v.2.2.0-beta 8 scheinen auf den ersten Blick alle relevanten Datenpunkte angelegt zu sein.
Dann mal sehen was mit den übrigen Geräten wird.
Die meisten davon hängen auch bei mir rum, hatte sie nur nicht priorisiert :-)

@zefau: Danke nochmal für die tolle Arbeit! 
Ich spiel dann mal weiter. Melde dich wenn ich was testen soll.

**Comment by Zefau** [comment]
@joe-sinclair das ist aber ioBroker.hm-rpc, nicht ioBroker.hmip, richtig?

**Comment by joe-sinclair** [comment]
@Zefau  stimmt, du hast recht! sorry!
Du hast deiner "Unterstützte Geräte" Liste  immer HM-prc geschrieben. Soll wohl HM-rpc heißen, oder?

Ich hab die .hmip gar nicht! Was ist der Unterschied? CCU vs Access Point ?

**Comment by Zefau** [comment]
Ja, genau. Ich hab's mit dem rpc verlinkt und setze es zeitnah um. Den Schreibfehler mit "prc" habe ich korrigiert. Danke für den Hinweis.

**Comment by Zefau** [comment]
@joe-sinclair kannst du mir für `HmIP-SWSD` den Expertenansicht hierein kopieren?

**Comment by joe-sinclair** [comment]
meinst du so ?
ich sehe da keinen großen unterschied bis auf die zwei kleinen Zahlen vorne

![Bildschirmfoto SWSD-Ex](https://user-images.githubusercontent.com/77187899/104120968-30b0c880-533b-11eb-99f1-490af3250374.png)

**Comment by Zefau** [comment]
Bei den Datenpunkt ist rechts ein Stift. Dahinter ist die Expertenansicht.

**Comment by Zefau** [comment]
Jo genau

**Comment by joe-sinclair** [comment]
`{
  "_id": "hm-rpc.0.00XXXXXXXXXXF5",
  "type": "device",
  "common": {
    "name": "1.OG - Flur - Rauch",
    "icon": "/icons/104_hm-sec-sd-2_thumb.png"
  },
  "native": {
    "TYPE": "HmIP-SWSD",
    "SUBTYPE": "SD",
    "ADDRESS": "00XXXXXXXXXXF5",
    "RF_ADDRESS": 4015654,
    "CHILDREN": [
      "00XXXXXXXXXXF5:0",
      "00XXXXXXXXXXF5:1"
    ],
    "PARENT": "",
    "PARENT_TYPE": "",
    "INDEX": 0,
    "AES_ACTIVE": 1,
    "PARAMSETS": [
      "MASTER",
      "SERVICE"
    ],
    "FIRMWARE": "1.0.12",
    "AVAILABLE_FIRMWARE": "0.0.0",
    "UPDATABLE": true,
    "FIRMWARE_UPDATE_STATE": "UP_TO_DATE",
    "VERSION": 1,
    "FLAGS": 1,
    "LINK_SOURCE_ROLES": "",
    "LINK_TARGET_ROLES": "",
    "DIRECTION": 0,
    "GROUP": "",
    "TEAM": "",
    "TEAM_TAG": "",
    "TEAM_CHANNELS": [],
    "INTERFACE": "",
    "ROAMING": 0,
    "RX_MODE": 3
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1608887109276,
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

hoffe das passt so!

**Comment by Zefau** [comment]
Sorry, ich hab mich unklar ausgedrückt. Ich meinte von `SMOKE_DETECTOR_ALARM_STATUS`. Damit kann ich die dargestellten Werte (im Screenshot `0`) mit den Labeln ersetzen.

Geht aber erst mal auch so. Hab deine Geräte nun mit `v2.2.0-beta.10` aufgenommen.
Probier gerne mal, ob alles durch den Importer gefunden und korrekt eingelesen wird.

**Comment by joe-sinclair** [comment]
Null Problemo

`{
  "type": "state",
  "common": {
    "def": "IDLE_OFF",
    "type": "number",
    "read": true,
    "write": false,
    "min": 0,
    "max": 3,
    "states": {
      "0": "IDLE_OFF",
      "1": "PRIMARY_ALARM",
      "2": "INTRUSION_ALARM",
      "3": "SECONDARY_ALARM"
    },
    "name": "HmIP-SWSD 00XXXXXXXXXXF5:1.SMOKE_DETECTOR_ALARM_STATUS"
  },
  "native": {
    "MIN": "IDLE_OFF",
    "OPERATIONS": 5,
    "MAX": "SECONDARY_ALARM",
    "FLAGS": 1,
    "ID": "SMOKE_DETECTOR_ALARM_STATUS",
    "TYPE": "ENUM",
    "DEFAULT": "IDLE_OFF",
    "VALUE_LIST": [
      "IDLE_OFF",
      "PRIMARY_ALARM",
      "INTRUSION_ALARM",
      "SECONDARY_ALARM"
    ],
    "CONTROL": "DANGER.STATE"
  },
  "from": "system.adapter.hm-rega.0",
  "user": "system.user.admin",
  "ts": 1577633102360,
  "_id": "hm-rpc.0.00XXXXXXXXXXF5.1.SMOKE_DETECTOR_ALARM_STATUS",
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}`

**Comment by joe-sinclair** [comment]
so. habe eben die beta 11 inst.
ich habe jetzt nur mal die fester Kontakte importiert.
eingelesen werden sie richtig, allerdings erfolgt keine status Änderung in der vis!

die thermostate werden nicht erkannt!

**Comment by Zefau** [comment]
@joe-sinclair beim `HmIP-SWDM` wird `.1.STATE` importiert. Was wird denn angezeigt?
Der `HmIP-eTRV` ist mir tatsächlich durchgerutscht.

Probier bitte nochmal `v2.2.0-beta.14` .

**Comment by joe-sinclair** [comment]
SWDM...geht! War mein Fehler...der primäre Datenpunkt war auf config und nicht auf open!

Beim SRH zeigt er aber folgendes an: bei geschlossener Tür = aus, bei offener Tür = an, gekippt = gekippt

Bei den Rauchmeldern wird das Icon nicht angezeigt!
Ob die richtig funktionieren werde ich am Wochenende testen!

Es gibt auch einen HmIP-eTRV-2, der scheint dir auch durchgerutscht zu sein ;)

Sonst scheint alles soweit richtig erkannt zu werden!
Vielen Dank :)

**Comment by Zefau** [comment]
`v2.2.0-beta.20`:
- [x] Es sollte nun offen, geschlossen und gekippt stehen.
- [ ] Mit dem Icon müsste eigl. gehen. Finde da keinen Fehler im Code. Kannst du das mal screenshoten? Also die Geräte-Konfiguration und dort, wo das Icon fehlt. Andere Icons gehen ohne Probleme, es ist nur das Gerät?
- [x] Der `HmIP-eTRV-2` sollte nun passen.

**Comment by joe-sinclair** [comment]
So siehts im Vis aus. Mittlere Spalte
![Bildschirmfoto 2021-01-18 um 20 46 06](https://user-images.githubusercontent.com/77187899/104957754-09a76600-59cf-11eb-9968-cc8da009c26c.png)

und so in der Geräte config:
![Bildschirmfoto 2021-01-18 um 20 53 01](https://user-images.githubusercontent.com/77187899/104957960-74f13800-59cf-11eb-9025-c634f4692878.png)

Die eTRV-2 werden erkannt :)

Danke

**Comment by Zefau** [comment]
Der Datenpunkt Bezeichner `config` hat im Standard kein Icon - hier musst du selbst eins vergeben. 

Hast du einen Datenpunkt Bezeichner `alarm` in der Liste? Der ist spezifisch für das Gerät und hat auch ein Icon.

**Comment by joe-sinclair** [comment]
@Zefau den Datenpunkt habe ich! Ist auch ausgewählt. Aber kein Icon zu sehen!
![Bildschirmfoto 2021-01-21 um 23 21 16](https://user-images.githubusercontent.com/77187899/105420039-fcdd7900-5c3f-11eb-871a-25d89a120484.png)
![Bildschirmfoto 2021-01-21 um 23 20 36](https://user-images.githubusercontent.com/77187899/105420059-05ce4a80-5c40-11eb-8b17-61a121a2712d.png)

**Comment by joe-sinclair** [comment]
Shelly RGBW-2 hat keinen Switch Datenpunkt! Gibt es für Shellys ein eigenes Issue? Habe keins gefunden!

**Comment by Zefau** [comment]
@joe-sinclair mit `v2.2.0-beta.24` sollte da Icon für `alarm` nun dargestellt werden. Kannst du das bitte prüfen?

**Comment by joe-sinclair** [comment]
Geprüft! und funktioniert! :-)

Danke
