### ISSUE TITLE
Blank Screen on Light Popup with Lightcolorbody with empfty Datapoint

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#574]
sorry, pic upload dont work

react-dom.production.min.js:209 TypeError: Cannot read property 'length' of undefined
    at LightColorBody (components.js:133)
    at Gi (react-dom.production.min.js:153)
    at gs (react-dom.production.min.js:261)
    at lu (react-dom.production.min.js:246)
    at su (react-dom.production.min.js:246)
    at Qs (react-dom.production.min.js:239)
    at react-dom.production.min.js:123
    at t.unstable_runWithPriority (scheduler.production.min.js:19)
    at Br (react-dom.production.min.js:122)
    at Vr (react-dom.production.min.js:123)

**Comment by Zefau** [comment]
@Timmes123 sollte mit `2.2.0-beta.6` behoben sein.

**Comment by Timmes123** [comment]
getestet mit beta 8
jap kann ich bestätigen :-) stürzt nicht mehr ab
allerdings wenn die datenpunkte leer sind sieht es so aus

![image](https://user-images.githubusercontent.com/73311538/104089504-fc240a80-526f-11eb-9e88-3742929dd05d.png)


meinst du es wäre möglich bei leeren datenpunkten trotzdem den slider einzublenden? damit ich das "leer" wenigstens mit was beschreiben könnte? also sozusagen annehmen "" wäre "0", allerdings nur für die anzeige?

**Comment by Timmes123** [comment]
ich teste gerade den zigbee adapter wegen meinen neuen rauchmeldern. da hab ich die beleuchtung mit rüber genommen. scheinbar ist das noch nicht ganz ausgereift, weil die datenpunkte der lampe so aussiehen

![image](https://user-images.githubusercontent.com/73311538/104089683-00045c80-5271-11eb-9ec6-fa1f82f7a083.png)

daher kommt auch das problem im jarvis.
klar ist das eigentlich nicht dein problem, wenn die datenpunkte schlecht vorliegen, allerdings wäre es cool wenn jarvis sich davon nciht beeindrucken lässt :-)

**Comment by Zefau** [comment]
@Timmes123 ich hab kein Zigbee, aber mit einem manuell angelegten Datenpunkt wird `0` gesetzt, wenn kein Wert vorhanden ist. Also eigentlich sollte der Fehler so nicht vorkommen.

Kannst du mal die Expertenansicht des Datenpunkts hierein kopieren? Ist der Datenpunkt als String angelegt? Ist der Wert leer oder `null` oder was anderes?

**Comment by Timmes123** [comment]
{
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1609886230139,
  "common": {
    "name": "Brightness",
    "type": "number",
    "unit": "",
    "role": "level.dimmer",
    "min": 0,
    "max": 100,
    "read": true,
    "write": true
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "zigbee.0.0017880103542975.brightness",
  "type": "state"
}

**Comment by Timmes123** [comment]
"from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1609886230139,
  "common": {
    "name": "Color",
    "type": "string",
    "role": "level.color.rgb",
    "read": true,
    "write": true
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "zigbee.0.0017880103542975.color",
  "type": "state"
}

**Comment by Timmes123** [comment]
{
  "from": "system.adapter.zigbee.0",
  "user": "system.user.admin",
  "ts": 1609886230139,
  "common": {
    "name": "Color temperature",
    "type": "number",
    "role": "level.color.temperature",
    "read": true,
    "write": true
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "zigbee.0.0017880103542975.colortemp",
  "type": "state"
}

**Comment by Timmes123** [comment]
![image](https://user-images.githubusercontent.com/73311538/104110937-fdd7e780-52dc-11eb-9022-4dcaf5c623e7.png)
ich weis nciht warum dieser blöde adapter die werte nicht automatisch von der lampe holt wenn noch nichts vorhanden ist.. scheinbar ein fehler von denen. da wo jetzt die beiden roten "0" sind hab ich nur rein und wieder raus geklickt. vorher hat es so ausgesehen

**Comment by Timmes123** [comment]
![image](https://user-images.githubusercontent.com/73311538/104110949-25c74b00-52dd-11eb-838f-ec89a559bf1b.png)
da ist quasi einfach gar kein wert drin

**Comment by Zefau** [comment]
Kannst du mir einen Gefallen tun und mal einen eigenen Datenpunkt anlegen mit den gleichen Eckdaten wie der Zigbee Datenpunkt?

Ich selbst habe mir den folgenden Datenpunkt angelegt, kann den Fehler damit aber nicht nachvollziehen, wenn ich diesen leer mache:
```
{
  "_id": "0_userdata.0.number",
  "type": "state",
  "common": {
    "name": "number",
    "role": "level.color.temperature",
    "type": "number",
    "read": true,
    "write": true,
    "desc": "Manually created"
  },
  "native": {},
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1604945257680,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by Timmes123** [comment]
ich kriegs nicht hin nen datenpunkt zu erzeugen, ohne das direkt ne 0 drin steht ^^

**Comment by Timmes123** [comment]
ich hab mir mal den wert mit nem script ausgeben lassen der drin steht. es ist: null

**Comment by Zefau** [comment]
Probier mal mit `v2.2.0-beta.10`.

**Comment by Timmes123** [comment]
getestet mit beta11

funktioniert perfekt :-)
