### ISSUE TITLE
Layout: Device verbergen wenn leer

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#576]
Ist es möglich n Device nur anzeigen zu lassen wenn es gefüllt ist?

![image](https://user-images.githubusercontent.com/25475385/103804190-fcdf5580-5051-11eb-920f-f8a611149886.png)

**Comment by Zefau** [comment]
Meinst du das Gerät oder den Datenpunkt im Gerät? Was genau meinst du mit befüllt? Warum löscht du es nicht einfach raus? Was ist der Use Case?

**Comment by duczz** [comment]
Nun ja, n Feiertag ist nun mal nicht jeden Tag :)
Wenn der Werte also leer ist will ich das Device im Layout auch nicht sehen (Platzverschwendung)

**Comment by Zefau** [comment]
dann wäre es https://github.com/Zefau/ioBroker.jarvis/issues/283 ?

**Comment by duczz** [comment]
joa, könnte man so sehen
