### ISSUE TITLE
Gruppe schalten

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#577]
Mehrere Geräte lassen sich in einer Gruppe nicht schalten.
Meistens wird nur ein Gerät geschaltet, "SwitchAction" Element wird rot.
Sowohl mit als auch ohne Trennstreifen.
Version 2.2.0-beta.7
![Bild](https://user-images.githubusercontent.com/77005685/104006306-9ae43480-51a6-11eb-8be2-c1754e60c636.jpg)

**Comment by Zefau** [comment]
Wie sieht die Widget Konfiguration aus?

**Comment by Bernd9000** [comment]
![Bild1](https://user-images.githubusercontent.com/77005685/104008065-31195a00-51a9-11eb-8253-0a2fb809a0a8.jpg)
![Bild2](https://user-images.githubusercontent.com/77005685/104008070-32e31d80-51a9-11eb-9e1d-dcb8d9a46272.jpg)

**Comment by Zefau** [comment]
Das SwitchAction wird rot, weil dies die sekundäre Farbe hast. Hast du Fehler in der Browser Konsole (F12) ?

**Comment by Zefau** [comment]
Hast du `min`/`max` in einem der Geräte konfiguriert?

**Comment by Bernd9000** [comment]
min/max kenne ich jetzt gar nicht bei den Geräten, die meisten Geräte sind gewöhnliche Steckdosen mit Tasmota eine Garagensteuerung mit ESP8266 (Tasmota) ,der Rest Intertechno Funkschalter die aber über ein Datenpunkt (MQTT) gesteuert werden.

Hier mal die Log vom Edge Browser, bei anderen Browsern ist es aber das gleiche, Browser Cache mehrfach gelöscht:

App # Welcome to jarvis 2.2.0-beta.7
Log.js:56 App # You are on instance jarvis.0.
Connection.js:58 Connecting to http://192.168.0.100:8082 ..
Connection.js:62 Connected to http://192.168.0.100:8082.
Log.js:56 App # Processed 20 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  {devices: {…}, states: Array(58), processedDevices: 20, addedDevices: 20, ignoredDevices: 0, …}addedDevices: 20devices: {d029147d-3e22-47d7-bf49-14aef9a65122: i, 20ce4702-f242-403a-bd26-bc00b4249c71: i, 20ce4702-f242-403a-bd26-bc00b4249c71_e9544: i, 20ce4702-f242-403a-bd26-bc00b4249c71_e3044: i, 20ce4702-f242-403a-bd26-bc00b4249c71_05aaa: i, …}20ce4702-f242-403a-bd26-bc00b4249c71: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_05aaa: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_010e1: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_56ce2: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_78c68: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_681b3: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_2677e: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_74945: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_a8b14: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_a5101: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_af508: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_daf5f: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_e3044: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}20ce4702-f242-403a-bd26-bc00b4249c71_e9544: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "other", functionId: "other", …}d029147d-3e22-47d7-bf49-14aef9a65122: i {_events: {…}, _eventsCount: 1, _maxListeners: 0, function: "socket", functionId: "socket", …}attributes: {_created: 1609743537279, _updated: 1610053223649}configurations: {_any: {…}, power: {…}, consumption: {…}, meter: {…}}defaults: {_any: {…}, battery: {…}, firmware: {…}, humidity: {…}, level: {…}, …}function: "socket"functionIcon: "power-socket-eu"functionId: "socket"icon: undefinedid: "d029147d-3e22-47d7-bf49-14aef9a65122"label: nullname: "Steckdose 2"options: {suppressPopup: false}primaryStateKey: "power"room: nullsocket: n {_events: {…}, _eventsCount: 4, _maxListeners: undefined, _isConnected: true, dataChange: ƒ, …}stateSubscriptions: (3) ["power", "Ein", "Aus"]states: {power: {…}, Ein: {…}, Aus: {…}}_events: {error: ƒ}_eventsCount: 1_isDevice: true_maxListeners: 0__proto__: nd029147d-3e22-47d7-bf49-14aef9a65122_7f893: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "socket", functionId: "socket", …}d029147d-3e22-47d7-bf49-14aef9a65122_710ad: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "socket", functionId: "socket", …}d029147d-3e22-47d7-bf49-14aef9a65122_41923: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "socket", functionId: "socket", …}d029147d-3e22-47d7-bf49-14aef9a65122_71843: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "socket", functionId: "socket", …}d029147d-3e22-47d7-bf49-14aef9a65122_b3f17: i {_events: {…}, _eventsCount: 2, _maxListeners: 0, function: "socket", functionId: "socket", …}__proto__: ObjectdiscardedDevices: {}ignoredDevices: 0processedDevices: 20states: (58) [{…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}, {…}]0: {status: "fulfilled", value: {…}}status: "fulfilled"value: {success: true, stateKey: "power", cached: false}__proto__: Object1: {status: "fulfilled", value: {…}}2: {status: "fulfilled", value: {…}}3: {status: "fulfilled", value: {…}}4: {status: "fulfilled", value: {…}}5: {status: "fulfilled", value: {…}}6: {status: "fulfilled", value: {…}}7: {status: "fulfilled", value: {…}}8: {status: "fulfilled", value: {…}}9: {status: "fulfilled", value: {…}}10: {status: "fulfilled", value: {…}}11: {status: "fulfilled", value: {…}}12: {status: "fulfilled", value: {…}}13: {status: "fulfilled", value: {…}}14: {status: "fulfilled", value: {…}}15: {status: "fulfilled", value: {…}}16: {status: "fulfilled", value: {…}}17: {status: "fulfilled", value: {…}}18: {status: "fulfilled", value: {…}}19: {status: "fulfilled", value: {…}}20: {status: "fulfilled", value: {…}}21: {status: "fulfilled", value: {…}}22: {status: "fulfilled", value: {…}}23: {status: "fulfilled", value: {…}}24: {status: "fulfilled", value: {…}}25: {status: "fulfilled", value: {…}}26: {status: "fulfilled", value: {…}}27: {status: "fulfilled", value: {…}}28: {status: "fulfilled", value: {…}}29: {status: "fulfilled", value: {…}}30: {status: "fulfilled", value: {…}}31: {status: "fulfilled", value: {…}}32: {status: "fulfilled", value: {…}}33: {status: "fulfilled", value: {…}}34: {status: "fulfilled", value: {…}}35: {status: "fulfilled", value: {…}}36: {status: "fulfilled", value: {…}}37: {status: "fulfilled", value: {…}}38: {status: "fulfilled", value: {…}}39: {status: "fulfilled", value: {…}}40: {status: "fulfilled", value: {…}}41: {status: "fulfilled", value: {…}}42: {status: "fulfilled", value: {…}}43: {status: "fulfilled", value: {…}}44: {status: "fulfilled", value: {…}}45: {status: "fulfilled", value: {…}}46: {status: "fulfilled", value: {…}}47: {status: "fulfilled", value: {…}}48: {status: "fulfilled", value: {…}}49: {status: "fulfilled", value: {…}}50: {status: "fulfilled", value: {…}}51: {status: "fulfilled", value: {…}}52: {status: "fulfilled", value: {…}}53: {status: "fulfilled", value: {…}}54: {status: "fulfilled", value: {…}}55: {status: "fulfilled", value: {…}}56: {status: "fulfilled", value: {…}}57: {status: "fulfilled", value: {…}}length: 58__proto__: Array(0)__proto__: Objectconstructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()
react-dom.production.min.js:218 Resource interpreted as Document but transferred with MIME type multipart/x-mixed-replace: "http://192.168.0.100:88/mjpg/Kamera7/video.mjpg".
e @ react-dom.production.min.js:218
e @ react-dom.production.min.js:218
e @ react-dom.production.min.js:218
e @ react-dom.production.min.js:218
e @ react-dom.production.min.js:218
e @ react-dom.production.min.js:218
e @ react-dom.production.min.js:218
e @ react-dom.production.min.js:218
e @ react-dom.production.min.js:218
ls @ react-dom.production.min.js:217
hu @ react-dom.production.min.js:252
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
fu @ react-dom.production.min.js:248
Qs @ react-dom.production.min.js:239
(anonymous) @ react-dom.production.min.js:123
t.unstable_runWithPriority @ scheduler.production.min.js:19
Br @ react-dom.production.min.js:122
Vr @ react-dom.production.min.js:123
Ur @ react-dom.production.min.js:122
qs @ react-dom.production.min.js:230
enqueueSetState @ react-dom.production.min.js:132
w.setState @ react.production.min.js:12
(anonymous) @ App.js:310
Promise.then (async)
(anonymous) @ App.js:308

**Comment by Bernd9000** [comment]
Vielleicht mache ich ja auch was falsch, gibts eine Anleitung für das anlegen einer Gruppe?
Im Wiki habe ich es nicht gefunden

**Comment by Zefau** [comment]
Die Gruppe ist korrekt angelegt. 

Ich finde leider keinen Fehler im Quellcode. Kannst du nochmal prüfen, ob es noch einen Fehler in der Browser Konsole gibt, nachdem du die Gruppe geschaltet hast?
Wenn du die Geräte in der Widget Konfiguration tauscht, tritt der Fehler dann auch auf? Wenn ja, tritt der Fehler mit demselben Gerät auf der hängt der Fehler an der Position des Geräts?

**Comment by Bernd9000** [comment]
Im Browser kommt kein weiterer Fehler.
Folgendes habe ich jetzt festgestellt:
Wenn ich bei dem "Gruppenschalter" im Feld "Element Aktion" statt "SwitchAction" den "ButtonAction" wähle, dann wird das erste Gerät nach dem "Gruppenschalter" korrekt geschaltet.In welcher Reihenfolge die Geräte sind ist egal.
Alle weiteren Gerät ab der zweiten Position in der Gruppe verhalten sich merkwürdig:

Wenn alle weiteren Geräte aus sind, lassen Sie sich mit dem "Gruppenschalter" egal ob ich "Ein" oder "Aus" drücke, genau einmal einschalten. Danach reagieren Sie weder auf "Ein" noch "Aus" und bleiben im eingeschaltetem Zustand.

Im IOBroker unter "Ereignisse" wird genau das tatsächlich auch von der Quelle web.0 so gesendet und unter mqtt.0 eingetragen.Mir erscheint es so als wenn der "Gruppenschalter" nicht erkennen kann im welchen Zustand die Geräte sind.

**Comment by Bernd9000** [comment]
Nachtrag:
Wenn ich bei den Geräten im Feld "Datenpunkt Eigenschaften" den Wert komplett lösche werden alle Geräte geschaltet.
Hier hatte ich folgendes stehen: {"on":"ON","off":"OFF"}
Jetzt wird beim schalten der Wert "true" bzw "false" an den Broker gesendet.
Allerdings spielt jetzt das "SwitchAction" Element der einzelnen Geräte verrückt.

**Comment by Zefau** [comment]
Die Einträge `{"on":"ON","off":"OFF"}` sind für MQTT notwendig?

**Comment by Zefau** [comment]
Wirklich sehr hilfreiche Fehleranalyse!! Vielen Dank dafür, das macht es wirklich einfacher.

Probier mal bitte `v2.2.0-beta.10`, ob ich es damit beheben konnte.

**Comment by Bernd9000** [comment]
Der Dank gilt Dir, Du hast da ein schönes Projekt auf die Beine gestellt.
1.) Für die Tasmota Firmware muss "ON" und "OFF" groß geschrieben werden als cmnd Befehl im MQTT Broker
    Das "true" und "false" auch funktionieren, wußte ich noch nicht.

2.) Zum Fehler
Es funktioniert jetzt richtig, wenn ich
a.) Als Gruppenschalter "ButtonAction" oder "IconButtonAction" benutzte
b.) Bei den Geräten im Feld "Datenpunkt Eigenschaften (JSON Format)" den Wert {"on":"ON","off":"OFF"} eintrage.
Perfekt !

Aber.....
Wenn ich jetzt zum Test bei den Geräten den Wert im Feld "Datenpunkt Eigenschaften (JSON Format)" lösche passiert folgendes:
1.) Die Steckdosen schalten mit dem Gruppenschalter korrekt
2.) Die Anzeige des "SwitchAction" Schalter der einzelnen Geräte wird nicht mehr korrekt gezeichnet (siehe Bild - roter Rahmen).Obwohl die Steckdosen eingeschaltet sind, zeigt der Geräteschalter "Aus" an.
3.) Versucht man die Geräte einzeln über den "SwitchAction" Schalter zu schalten gibt es folgendes Fehlerbild:
   a) Im Zustand "Aus" drücke ich den Schalter
      Steckdose schaltet ein, die Anzeige des "SwitchAction" Schalter geht sofort wieder auf "Aus"
  b) Drücke ich nochmal, geht die Anzeige des "SwitchAction" Schalter  auf "An", Steckdose bleibt eingeschaltet
  c) Beim dritten mal drücken wird die Steckdose ausgeschaltet und die Anzeige des "SwitchAction" Schalter geht auf "Aus"

Das könnte bedeuten das jetzt andere Benutzer, die im Feld "Datenpunkt Eigenschaften" der Geräte nichts angegeben haben, Probleme kriegen. Ich glaube das Thema Gruppe schalten wird nicht so einach zu lösen sein.

Eine Alternative die ich gerade probiert habe ist ein virtuelles Gerät "Gruppe schalten" zu erstellen der im Broker den Wert "on" und "off" erstellt. Über ein Script kann man das dann auswerten und dann weitere Geräte über MQTT schalten.

![Bild](https://user-images.githubusercontent.com/77005685/104136962-b82d2480-5399-11eb-87a9-7d414d0f39f5.jpg)

**Comment by Zefau** [comment]
@Bernd9000 ich bin überzeugt, dass ich das hinbekomme ;-)

Probier mal bitte `v2.2.0-beta.17`. Damit sollte nun auch der Switch mit Datenpunkt Eigenschaften funktionieren.
Bei mir ohne definierte Datenpunkt Eigenschaften geht es noch nach wie vor.

**Comment by Bernd9000** [comment]
Wie ich gerade feststellen mußte, tritt der Anzeige Fehler bei mir jetzt auch ohne "Gruppenschalter" auf.
Das heißt der Gruppenschalter funktioniert.

Fazit:
Der "SwitchAction" Schalter bei den einzelnen Geräten funktioniert bei mir nur dann richtig , wenn ich als Datenpunkt Eigenschaften den Wert {"on":"ON","off":"OFF"} eintrage.
Merkwürdig....

**Comment by Zefau** [comment]
Nicht merkwürdig, dass ist doch logisch und richtig. `on` und `off` ist im Standard `true` bzw. `false`. Wenn dein Gerät aber beides nicht nimmt. sondern `ON` und `OFF` (als String) ist es doch richtig, dass es damit funktioniert und logisch, dass es ohne nicht richtig geht, weil dann die Werte falsch sind.

Oder verstehe ich es falsch?

Bei mir funktioniert es ohne Datenpunkt Eigenschaften für Geräte, die standardmäßig `true`/ `false` verwenden.

**Comment by Bernd9000** [comment]
Es ist so, das die Steckdosen unter der Tasmota Firmware  im MQTT Broker im Topic "cmnd" mehrere Varianten als Payload verarbeiten können:
"0,1" "true,false" "On,Off" "ON,OFF" "on,off"
Bestätigt wird das von den Geräten im MQTT Broker im Topic "stat" aber **IMMER** als "ON" oder als "OFF", egal was in "cmnd" eingetragen wird.
Und deswegen funktioniert bei mir der "SwitchAction" Schalter nicht richtig.
Dieser erwartet, wenn ich **nichts** unter Datenpunkt Eigenschaften eintrage, ein "true" oder "false".
Das hat dann aber nichts mehr mit Gruppe schalten zu tun.
Das heißt Du hast alles richtig gemacht, Gruppe schalten funktioniert.

**Comment by Zefau** [comment]
@Bernd9000 also kann ich das Issue schließen? Bin mir nicht sicher, ob ich dich richtig verstanden habe.

Mit MQTT musst du auf jeden Fall die Datenpunkt Eigenschaften benutzen, um ein Mapping auf `ON` und `OFF` vorzunehmen, also `{"on":"ON","off":"OFF"}`. Nur dann überschreibst du den Standard, der als `{"on":"true","off":"false"}` definiert ist.

**Comment by Bernd9000** [comment]
Ja, Bitte Issue schliessen.
