### ISSUE TITLE
Unterstützung für relative Pfade

### ISSUE THREAD

**Issue by SevenUp666** [Zefau/ioBroker.jarvis#578]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **v2.2.0-beta.6**

**Describe the bug / Beschreibe den Fehler**
Mit dem Widget "DisplayImage" möchte ich eine Grafik anzeigen lassen (Karte von dem Xiaomi Staubsauger). Auf die Grafik kann über den relativen Pfad zugegriffen werden:
./opt/iobroker/iobroker-data/files/mihome-vacuum.admin/actualMap_0.png

Jarvis kann über den relativen Pfad die Grafik aber nicht laden, da relative Pfade nicht unterstützt wird.
Siehe auch https://forum.iobroker.net/post/553952

**Expected behavior**
Relative Pfade werden unterstützt

**Comment by voyage200** [comment]
Hallo,

ich lasse mir die Karte des Xiaomi Staubsaugers (S5) mit dem **CustomHTML**-Widget  anstatt des **DisplayImage**-Widget anzeigen. Dazu habe ich den **map64** Datenpunkt in der Gerätekonfiguration angelegt:

![08-01-_2021_17-29-13](https://user-images.githubusercontent.com/76617424/104043178-b87fc100-51db-11eb-9db3-f9c5d04f9a27.png)

![08-01-_2021_17-32-35](https://user-images.githubusercontent.com/76617424/104043394-0a284b80-51dc-11eb-96ee-80a637a8d69a.png)

![08-01-_2021_17-34-20](https://user-images.githubusercontent.com/76617424/104043405-0dbbd280-51dc-11eb-8264-9b9d119089ca.png)

**Comment by SevenUp666** [comment]
@voyage200
danke, das wäre schon mal eine Lösung in die richtige Richtung. Für mich passt es aber noch nicht ganz, da ich das vom Sauger erstellte Grafik erstmal zuschneiden und erst dann in Jarvis darstellen möchte. Dazu speichere ich die Karte in einer neuen Datei und auf den Inhalt der Datei möchte ich dann in Jarvis mir anzeigen lassen. Da der Pfad immer konstant ist, muss es nicht unbedingt in einem Datenpunkt drin stehen.

**Comment by florian84z** [comment]
So mache ich es auch, aber die Karte ist unvollständig und veraltet. Ich weiß nicht, ob das dir/hier hilft?!


![image](https://user-images.githubusercontent.com/23108104/104048427-78bcd780-51e3-11eb-977d-b1178b85c221.png)

**Comment by SevenUp666** [comment]
mir geht es hier eher um die relativen Pfade und nicht um die Karte :-)

**Comment by florian84z** [comment]
> mir geht es hier eher um die relativen Pfade und nicht um die Karte :-)

Okay, da komme ich schon nicht mehr mit. Aber hast du eine Idee, warum die Karte nur so angezeigt wird?

**Comment by SevenUp666** [comment]
leider nicht. Das liegt aber vermutlich gar nicht an Jarvis, sondern an dem Sauger oder an dem Mi Vacuum Adapter. Mit Google sollte man dazu einiges finden können (z.b. xiaomi vacuum karte gedreht)

**Comment by Zefau** [comment]
@SevenUp666 added with `v2.2.0-beta.9`.

**Comment by SevenUp666** [comment]
@Zefau 
vielen Dank für die schnelle Umsetzung!

irgendwo hackt es bei mir aber noch (vermutlich sitzt der Fehler wie meistens vor dem Bildschirm)...
Ich möchte die Datei "actualMap_0_crop.png" aus dem Verzeichnis "/opt/iobroker/iobroker-data/files/mihome-vacuum.admin" anzeigen lassen:
[![Bild 2021-01-1000_25_07-mi4ajrm.png auf abload.de](https://abload.de/img/2021-01-1000_25_07-mi4ajrm.png)](https://abload.de/image.php?img=2021-01-1000_25_07-mi4ajrm.png)

Wenn ich im Widget nun
`./opt/iobroker/iobroker-data/files/mihome-vacuum.admin/actualMap_0_crop.png`
eintrage, dann wird im Jarvis diese Adresse generiert und keine Datei gefunden:
`http://xxx.xxx.x.xxx:8082/jarvis/opt/iobroker/iobroker-data/files/mihome-vacuum.admin/actualMap_0_crop.png`

Lasse ich den Punkt am Anfang der relativen Adresse weg, dann kommt es zu dieser Adresse und weiterhin keine Grafik gefunden:
`http://xxx.xxx.x.xxx:8082/opt/iobroker/iobroker-data/files/mihome-vacuum.admin/actualMap_0_crop.png`

**Comment by Zefau** [comment]
@SevenUp666 Ich habe es mir nochmal im Detail angesehen und muss leider sagen, dass es technisch nicht geht. Keine Ahnung wie ioBroker.vis das macht auf relative Pfade zuzugreifen.

Die Funktionsweise ist so, dass ioBroker.web einen Web-Server auf macht. Die Dateien werden nur zur Verfügung gestellt, wenn diese ioBroker bekannt sind (mittels `writeFile` erstellt, siehe https://github.com/ioBroker/ioBroker.javascript/blob/master/docs/en/javascript.md#writefile).

Mit einer Anpassung deines Skripts solltest du es daher via http URL aufrufen können. Mit dem relativen Pfad kann ich leider nicht helfen, tut mir Leid.

Wie sieht dein Skript aus? Kannst du es hier posten, damit auch andere davon profitieren? Dann können wir es gerne gemeinsam so ausgestalten, dass es mit URL funktioniert.

**Comment by voyage200** [comment]
> 
> 
> > mir geht es hier eher um die relativen Pfade und nicht um die Karte :-)
> 
> Okay, da komme ich schon nicht mehr mit. Aber hast du eine Idee, warum die Karte nur so angezeigt wird?

Das Problem hatte ich anfänglich auch gehabt: alte Karte und keine Aktualisierung der Karte während der Reinigung. 

Abhilfe hat bei mir das löschen des **mihome-vacuum.0** _Objektes_ gebracht. Nachdem ich den iobroker neu gestartet und das Objekt (automatisch) neu angelegt wurde, wird auch die aktuelle Karte und die "live" Bewegung des Roboters in jarvis korrekt angezeigt.

**Comment by SevenUp666** [comment]
@Zefau 
mein Problem bezieht sich eher nicht auf die relative Pfade, sondern allgemein auf den Zugriff auf eine von mir abgelegte Grafik. Durch die Verwendung der relativen Pfade hatte ich die Hoffnung, dass ich so auf die Grafik zugreifen kann. Ein absoluter Pfad würde mir auch reichen, wenn es funktionieren würde.

Jarvis kann die Karte des Staubsauger bereits anzeigen, die aus einem Datenpunkt geladen wird. Bei meiner Karte gibt es aber sehr viele transparente Fläche um die eigentliche Karte drumherum (wohne nicht in einem Palast und brauche die gesamte Kartenfläche nicht :-) ). Deshalb schneide ich die Karte nach meinen Wünsche zu und speichere sie unter dem neuen Namen.
Auf die ungeschnittene Karte kann ich über den absoluten Pfad zugreifen und auch in Jarvis darstellen. Auf die zugeschnittene Karte aber nicht. Es ist also gar kein Jarvis Problem.

Es muss doch möglich sein, auf die im ioObroker Ordner gespeicherten Dateien über den Browser zuzugreifen? :-)

Mein Blockly für das Zuschneiden mit Imagemagik:
[![Bild 2021-01-1014_23_48-jaizjc6.png auf abload.de](https://abload.de/img/2021-01-1014_23_48-jaizjc6.png)](https://abload.de/image.php?img=2021-01-1014_23_48-jaizjc6.png)

**Comment by Zefau** [comment]
>  mein Problem bezieht sich eher nicht auf die relative Pfade, sondern allgemein auf den Zugriff auf eine von mir abgelegte Grafik. Durch die Verwendung der relativen Pfade hatte ich die Hoffnung, dass ich so auf die Grafik zugreifen kann. Ein absoluter Pfad würde mir auch reichen, wenn es funktionieren würde.

Das verstehe ich schon. Und wie beschrieben liegt es daran, dass ioBroker (bzw. ioBroker.web) die Datei nicht kennt. Du musst diese mittels `writeFile` schreiben - wobei ich das blocky Pendant nicht kenne. Es hat nichts damit zu tun, ob die Datei beschnitten ist oder nicht. Du kannst jede beliebige Datei in das Verzeichnis kopieren - ioBroker wird es nicht erkennen.

**Comment by SevenUp666** [comment]
Okay, verstehe.

Kurios ist das Ganze für mich weiterhin.
Wie geschrieben, kann ich auf die Original Datei zugreifen
`http://192.168.1.240:8082/mihome-vacuum.admin/actualMap_0.png`
lösche ich die Datei, dann bekomme ich richtigerweise die Meldung, dass die Datei nicht da ist.
Ersetze ich die Datei mit einer anderen, dann wird mir weiterhin die alte Grafik angezeigt (Browser Cache habe ich gelöscht).

Ich werde im ioBroker mal rumfragen. Jemand hat schon mal ganz sicher ein eigenes Bild hochgeladen und verwendet.
Ansonsten brauchen wir dafür einen neuen Adapter, der die Dateien per writeFile hochlädt ;-)

**Comment by Zefau** [comment]
Die Originaldatei ist auch ioBroker bekannt, da ordnungsgemäß durch den Adapter angelegt! Deswegen zeigt er auch die alte an, wenn du diese löscht / ersetzt oder was auch immer! Das ist von ioBroker gecached. Es aktualisiert NUR mit `writeFile` (das schreibe ich nun zum dritten Mal!)

**Comment by Zefau** [comment]
Und du brauchst keinen neuen Adapter, du musst nur dein Skript geringfügig anpassen.

**Comment by SevenUp666** [comment]
meine Unkenntnis bitte ich zu entschuldigen.

**Comment by florian84z** [comment]
> Hallo,
> 
> ich lasse mir die Karte des Xiaomi Staubsaugers (S5) mit dem **CustomHTML**-Widget anstatt des **DisplayImage**-Widget anzeigen. Dazu habe ich den **map64** Datenpunkt in der Gerätekonfiguration angelegt:
> 
> ![08-01-_2021_17-29-13](https://user-images.githubusercontent.com/76617424/104043178-b87fc100-51db-11eb-9db3-f9c5d04f9a27.png)
> 
> ![08-01-_2021_17-32-35](https://user-images.githubusercontent.com/76617424/104043394-0a284b80-51dc-11eb-96ee-80a637a8d69a.png)
> 
> ![08-01-_2021_17-34-20](https://user-images.githubusercontent.com/76617424/104043405-0dbbd280-51dc-11eb-8264-9b9d119089ca.png)


> > > mir geht es hier eher um die relativen Pfade und nicht um die Karte :-)
> > 
> > 
> > Okay, da komme ich schon nicht mehr mit. Aber hast du eine Idee, warum die Karte nur so angezeigt wird?
> 
> @florian84z
> Das Problem hatte ich anfänglich auch gehabt: alte Karte und keine Aktualisierung der Karte während der Reinigung.
> 
> Abhilfe hat bei mir das löschen des **mihome-vacuum.0** _Objektes_ gebracht. Nachdem ich den iobroker neu gestartet und das Objekt (automatisch) neu angelegt wurde, wird auch die aktuelle Karte und die "live" Bewegung des Roboters in jarvis korrekt angezeigt.

Danke Dir, hast du nur den zweig "map" gelöscht oder alles? Welchen Sauger nutzt du und hast du "use new Map format with roomcolors" aktiviert?

Ich probiere das gleich mal.

**Comment by voyage200** [comment]
> > Hallo,
> > ich lasse mir die Karte des Xiaomi Staubsaugers (S5) mit dem **CustomHTML**-Widget anstatt des **DisplayImage**-Widget anzeigen. Dazu habe ich den **map64** Datenpunkt in der Gerätekonfiguration angelegt:
> > ![08-01-_2021_17-29-13](https://user-images.githubusercontent.com/76617424/104043178-b87fc100-51db-11eb-9db3-f9c5d04f9a27.png)
> > ![08-01-_2021_17-32-35](https://user-images.githubusercontent.com/76617424/104043394-0a284b80-51dc-11eb-96ee-80a637a8d69a.png)
> > ![08-01-_2021_17-34-20](https://user-images.githubusercontent.com/76617424/104043405-0dbbd280-51dc-11eb-8264-9b9d119089ca.png)
> 
> > > > mir geht es hier eher um die relativen Pfade und nicht um die Karte :-)
> > > 
> > > 
> > > Okay, da komme ich schon nicht mehr mit. Aber hast du eine Idee, warum die Karte nur so angezeigt wird?
> > 
> > 
> > @florian84z
> > Das Problem hatte ich anfänglich auch gehabt: alte Karte und keine Aktualisierung der Karte während der Reinigung.
> > Abhilfe hat bei mir das löschen des **mihome-vacuum.0** _Objektes_ gebracht. Nachdem ich den iobroker neu gestartet und das Objekt (automatisch) neu angelegt wurde, wird auch die aktuelle Karte und die "live" Bewegung des Roboters in jarvis korrekt angezeigt.
> 
> Danke Dir, hast du nur den zweig "map" gelöscht oder alles? Welchen Sauger nutzt du und hast du "use new Map format with roomcolors" aktiviert?
> 
> Ich probiere das gleich mal.

@florian84z 

ich hatte direkt alles gelöscht: 

![10-01-_2021_16-25-50](https://user-images.githubusercontent.com/76617424/104127214-20134900-5361-11eb-8dc3-daafb9938114.png)

Ich benutze den **Xiaomi Roborock S50**. Habe dafür diese Einstellungen aktiviert:

![10-01-_2021_16-28-19](https://user-images.githubusercontent.com/76617424/104127310-bba4b980-5361-11eb-8f10-b2ee87fab227.png)

![10-01-_2021_16-28-35](https://user-images.githubusercontent.com/76617424/104127312-be9faa00-5361-11eb-9eca-d6c26590bd65.png)




Die Karte wird bei mir wie in der Handy App dargestellt, allerdings ohne die gesetzten Sperrzonen:

![10-01-_2021_16-37-57](https://user-images.githubusercontent.com/76617424/104127468-86e53200-5362-11eb-9cdd-2918b5da6d63.png)

**Comment by Zefau** [comment]
@SevenUp666 
> meine Unkenntnis bitte ich zu entschuldigen.

Sorry, ich wollte dich nicht angreifen oder so. Ich will nur unterstreichen, dass ich leider keine relativen Pfade in jarvis darstellen kann, aber deine Anforderung umsetzbar ist. Ich helfe gerne dein Skript entsprechend anzupassen, allerdings kenne ich mich mit Blockly nicht aus und könnte dies nur in Javascript umsetzen.

**Comment by SevenUp666** [comment]
@Zefau die relativen Pfade hast du ja umgesetzt :-) das hat funktioniert und dafür ein Danke!
Dass nun das drum-herum etwas tricky ist, liegt ja nicht mehr an deinem Adapter.

Ich bin nun weitergekommen und habe ein für mich zu 90% zufriedenstellendes Ergebnis erreicht.

Mein Blockly habe ich erweitert (Screenshot unten), und zwar mit der [writefile Funktion](https://www.iobroker.net/docu/index-98.htm?page_id=3971&lang=de#iobroker_file_write), die man auch aus exec aufrufen kann:
`iobroker file write /opt/myfile.png /vis.0/main/img/picture.png`

Noch habe ich einen kleine Verzögerung von 1 Sekunden eingebaut, bevor ich auf die Dateien zugreife. So möchte ich verhindern, dass der Schreibvorgang noch nicht beendet war.
Da die "Indexierung" (file write) bei mir auch 1-2 Sek in der Ausführung dauert und ich das System nicht so hoch belasten möchte, habe ich eine weitere Verzögerung von 8 Sek eingebaut. So habe ich alle 10 Sekunden eine aktuelle und zugeschnittene Karte.

Die Karte ist dann hier gespeichert:
`/opt/iobroker/iobroker-data/files/mihome-vacuum.admin/actualMap_0_crop.png`

Und im Jarvis-Widget gebe ich das als relativen Pfad ein:
`/mihome-vacuum.admin/actualMap_0_crop.png`
--> relativer Pfad funktioniert prächtig!

Warum ist es noch keine 100% Lösung?
Weil ich durch die Verzögerungen das aller letztes Bild der Karte nicht mehr mitbekomme. Wenn der Sauger also wieder auf der Basis steht, fehlt mir dazu das zugeschnittene Bild. Lässt sich sicherlich irgendwie lösen, habe aber noch keine Idee.  :-)


[![Bild 2021-01-1017_13_50-jahlkb7.png auf abload.de](https://abload.de/img/2021-01-1017_13_50-jahlkb7.png)](https://abload.de/image.php?img=2021-01-1017_13_50-jahlkb7.png)

[![Bild 2021-01-1017_14_10-6gjfl.png auf abload.de](https://abload.de/img/2021-01-1017_14_10-6gjfl.png)](https://abload.de/image.php?img=2021-01-1017_14_10-6gjfl.png)

[![Bild 2021-01-1017_14_24-cukqx.png auf abload.de](https://abload.de/img/2021-01-1017_14_24-cukqx.png)](https://abload.de/image.php?img=2021-01-1017_14_24-cukqx.png)
