### ISSUE TITLE
Blind level state in pop-up not consistent

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#58]
The level state of blinds in the pop-up is not consistent compared to dimmers and heating. Instead of offering the possibility to drive up and down, it should only show the percent value. The user should use the slider to set a value like it is done for dimmers and heating.

![image](https://user-images.githubusercontent.com/2136249/92326755-c4544e80-f054-11ea-90e6-ad8fb12d34fc.png)

![image](https://user-images.githubusercontent.com/2136249/92326759-d3d39780-f054-11ea-836e-28622e28b553.png)

**Comment by Zefau** [comment]
The percentage value is shown next to the up/down buttons. The user can use both the Slider or the Buttons. Why is so bad that it is (a little bit) inconsistent? ;-)

With https://github.com/Zefau/ioBroker.jarvis/issues/40 the user will be able to configure the Popup like the Widgets, so this will be obsolete as well.

**Comment by braindead1** [comment]
I love consistency. While I was able to make the rest of jarvis consistent using state styles and display variants, the above mentioned is the only part I cannot influence. 

I know that this is whine on a very high level, but I really want to help to make jarvis a success story. I can only imagine how much time you already invested and as I'm not able to help coding, I want to give as many tips as possible.

**Comment by Zefau** [comment]
Remove it would mean there is no stop button though. This one is obviously not necessary for lights / heating, but for blinds it is quite handy, isn't it?

**Comment by braindead1** [comment]
From my experience the stop button is only needed in case you can only drive up and down. When it's possible to set the blind to a precise level it's not needed, as I usually know the level I need right at that moment.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/40

**Comment by Zefau** [comment]
Will be done via https://github.com/Zefau/ioBroker.jarvis/issues/40
