### ISSUE TITLE
Deaktivieren der Reduzierung Tab-Leiste in der TopBar beim Scrollen

### ISSUE THREAD

**Issue by flkontakt** [Zefau/ioBroker.jarvis#581]
Siehe https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/2877

Kann die Tab-Leiste dauerhaft eingeblendet werden? Beim Scrollen reduziert sich diese auf die Icons, ich würde die Leiste gerne komplett sehen wollen.

**Comment by SevenUp666** [comment]
Dann lieber 3 Modis machen:
- dauerhaft sichtbar
- dauerhaft minimiert
- Automatik

Und wenn das noch abhängig von der Desktop- oder mobiler Ansicht wäre, dann wäre es das i-Tüpfelchen :-)

Sehe das aber eher als Kosmetik und einige andere Themen wäre mir wichtiger.

**Comment by hase747** [comment]
Auch für mich wäre die Option "dauerhaft minimiert" sinnvoll, dann müsste ich nicht immer erst ein bisschen nach unten scrollen bis die gesamte Seite auf meinem 7" Tab zu sehen ist.

**Comment by Zefau** [comment]
@hase747 wie selektiert man denn die Tabs, wenn die Leiste dauerhaft minimiert ist?

**Comment by Zefau** [comment]
added an option in v3 to either "show always" or to "hide on scroll"

**Comment by mcuiobroker** [comment]
Funktioniert.
