### ISSUE TITLE
Vorstellen, Anstelle von Informationen an Wert

### ISSUE THREAD

**Issue by Bjoern3003** [Zefau/ioBroker.jarvis#583]
Für bestimmte Szenarien wäre es klasse, wenn man dem Dargestellten Wert noch einige Informationen an- oder vorstellen könnte.

Ein Beispiel:

![10012021134724](https://user-images.githubusercontent.com/13675579/104123262-64dfb580-534a-11eb-894c-c772826e97e1.png)

Das "Raum lüften" in Grün sollte z.b. erscheinen, sobald die Schwelle über 60 ist. Alternativ z.b. wenn der Wert unter 40 fällt, dass dann dort steht "Raum befeuchten".

**Comment by Zefau** [comment]
same as https://github.com/Zefau/ioBroker.jarvis/issues/369 ?

**Comment by Bjoern3003** [comment]
Ja stimmt, das ähnelt sich. Irgendwie habe ich mit den falschen Suchbegriffen gearbeitet, bevor ich das Request eröffnet hatte.

**Comment by Zefau** [comment]
Kein Problem. Sind nach wie vor noch zu viele Sachen offen, um alles finden zu können.
