### ISSUE TITLE
DateTime: Time incorrect when seconds are not used

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#587]
https://forum.iobroker.net/post/555666
> wenn ich im Date Widget die Sekunden ausblende geht die Zeit falsch.

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/557732

**Comment by duczz** [comment]
läuft bei mir ohne Probleme, auch ohne Sekunden

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/557795

**Comment by Zefau** [comment]
Funktioniert auch bei mir problemlos.

**Comment by simonweimar** [comment]
Sobald ich das „:ss“ weg mache und speichere, fängt die Minute ab da an zu laufen. 
Also wenn ich um 12:30:59 speichere sollte die Zeit ja dann sofort auf 12:31 gehen. Aber es geht erst eine Minute später auf 12:31. Heißt in dem Moment geht die Uhr dann 1 Minute hinterher. 
Ich hoffe das ist verständlich so...

**Comment by Zefau** [comment]
Das ist es ja, hörte sich aber im ersten Moment total anders (also das es komplett falsch ist) an ;-)

**Comment by Zefau** [comment]
@SWE1008 sollte mit `v2.2.0-beta.18` nun passen.

**Comment by SWE1008** [comment]
Ja es ist besser geworden. Allerdings geht die Uhr ca. 7-8 Sekunden nach. Das ist für mich aber nicht so tragisch.

**Comment by Zefau** [comment]
@SWE1008 ja, max 10s. Wenn du Sekunden einblendest dann aktualisiert sich das Modul jede Sekunde. Wenn du Sekunden ausblendest dann aktualisiert sich das Modul alle 10s, um Performance zu sparen (vorher war es jede Minute). Daher kommt die Differenz.
