### ISSUE TITLE
Geräteliste schließt sich nach jeder "Kopie" eines bestehenden Geräts

### ISSUE THREAD

**Issue by dalig83** [Zefau/ioBroker.jarvis#588]
version: 2.1.0
OS: macOS
Browser: Google Chrome & Safari

_- Beschreibung:_

Fenster: Konfiguration-Geräte-Geräteliste
Wenn ich in einer bestehenden Gruppe ein Gerät kopiere, schließt sich der jeweilige Reiter immer gleich, nachdem das neue Gerät erstellt wurde.

_- Erwartetes Verhalten:_

Reiter bleibt offen, damit das manuelle hinzufügen neuer Geräte effizienter abläuft.

**Comment by Zefau** [comment]
duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/551

**Comment by dalig83** [comment]
Can be closed - didn't see #551
