### ISSUE TITLE
Widget per Button als Vollbild darstellen

### ISSUE THREAD

**Issue by SevenUp666** [Zefau/ioBroker.jarvis#589]
Wenn das Layout aus mehr als 1 Spalte besteht, dann wird ein Charts entsprechend in der Größe der Spalte angezeigt und belegt somit nur 1/2 oder 1/3 des Bildschirmes. Für die grobe Übersicht reicht es meistens.
Es wäre aber hilfreich, wenn das Chart beim Klick auf einen Button kurzzeitig im Vollbild angezeigt wird (ähnlich zu dem Geräte-Popup)

**Comment by SevenUp666** [comment]
oder, wenn es möglich wäre: den Inhalt eines beliebigen Widgets in Vollbild schalten.

**Comment by Zefau** [comment]
added with `v3.1.0-alpha.0`

![image](https://user-images.githubusercontent.com/14368811/163692619-c551a7e2-a974-48e0-b3da-4e3fd4fff453.png)
