### ISSUE TITLE
Add action to imported devices

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#59]
Currently, only states will be added and action omitted.
- [x] deconz
- [x] hm-rpc
  - [x] heating
  - [x] blind
  - [x] light
  - [x] light dimmer
- [x] hue
- [x] hue-extended
- [x] shelly

**Comment by Zefau** [comment]
@braindead1 Do you have any HomeMatic or HomeMatic IP devices that you could help me with regarding the adapter structure?

I only own `hmip-bwth`, which structure is
```
{
   "temperature":".1.ACTUAL_TEMPERATURE",
   "setTemperature":".1.SET_POINT_TEMPERATURE",
   "humidity":".1.HUMIDITY",
   "boost":".1.BOOST_MODE"
}
``` 

Could you share the structure of Dimmers, Switches and Blinds, if you own those?

**Comment by Zefau** [comment]
Action states added with `1.0.0-beta.19`.

**Comment by braindead1** [comment]
@Zefau Most of my smart home stuff is HomeMatic and HomeMatic IP. I'll test the import and I can provide the structure asap.

**Comment by Zefau** [comment]
No need to test the import. I have not implemented any other devices than heating (`hmip-bwth`), because that's the only thing I have.
I mean the hm-rpc structure of a Dimmer, Switch and Blind. As I remember the state was in channel `.3.` and the action is any of `.4.`, `.5.` or `.6.` (at least for Dimmers / Switches).

**Comment by Zefau** [comment]
I googled and found this for blind switches:

![image](https://user-images.githubusercontent.com/14368811/92524139-e0f1b180-f221-11ea-98d6-6d24ae6faec2.png)

So blind switches will be:
```
"level":{
   "state":".3.LEVEL",
   "action":".4.LEVEL"
},
"activity":{
   "state":".3.ACTIVITY_STATE",
   "action":".4.STOP"
},
```

**Comment by braindead1** [comment]
To be honest, I'm not 100% sure that channel 4 is always the correct one. As far as I know, it is possible to set the level of 4, 5 and 6 to different values and depending on the configurationof the device the real level is calculated, but I never used that with my devices.

**Comment by Zefau** [comment]
True, that's how I read as well it is working.
Which channel are you using? I was always using 4 when I had Dimmers and Switches (before I sold them).

Generally, imported devices have a suggested structure which can always be changed if required.

**Comment by braindead1** [comment]
I'm also using channel 4 with my HomeMatic IP devices. Therefore I believe most of the user users will do that, too. I guess you already know that the state structure of HomeMatic and HomeMatic IP devices is totally different? It's important for the import.

**HomeMatic blind:**

    "level": {
        "state": ".1.LEVEL",
        "action": ".1.LEVEL"
    },
    "activity": {
        "state": ".1.WORKING",
        "action": ".1.STOP"
    }

**HomeMatic switch:**

    "power": {
        "state": ".1.STATE",
        "action": ".1.STATE"
    }

Please note, that a switch might have up to eight (?) channels. I can test it with 1, 2 and 4 channels.

**HomeMatic heating:**

    {
       "temperature": ".4.ACTUAL_TEMPERATURE",
       "setTemperature": ".4.SET_TEMPERATURE",
       "boost": ".4.BOOST_MODE"
    }

**HomeMatic window sensor (tilt):**

    {
        "open": ".1.STATE"
    }

**HomeMatic IP light dimmer:**

    {
        "level": ".4.LEVEL"
    }

**HomeMatic IP switch:**

    {
        "power": ".4.STATE"
    }

Please note, that I only have one channel switches. Therefore I don't know how many are possible in theory and how they are numbered.

**HomeMatic IP blind:**

    "level": {
        "state": ".4.LEVEL",
        "action": ".4.LEVEL"
    },
    "activity": {
        "state": ".4.ACTIVITY_STATE",
        "action": ".4.STOP"
    }

**Comment by Zefau** [comment]
I didn't know that. Is there any state in the object tree to tell the difference between both?

**Comment by Zefau** [comment]
@braindead1 Can you confirm the following device IDs? I googeled them and not sure if they are correct. You can find them in the object definition of the device in the ioBroker object tree.

![image](https://user-images.githubusercontent.com/14368811/92638309-5c169e80-f2da-11ea-83e1-ab0f398ee205.png)


- [ ] HomeMatic blind `HM-LC-Bl1PBU-FM`
- [ ] HomeMatic switch `HM-LC-Sw1PBU-FM`
- [ ] HomeMatic heating `HM-CC-RT-DN`
- [ ] HomeMatic window sensor (tilt) `HM-Sec-SCo` / `HM-Sec-SC-2`
- [ ] HomeMatic IP light dimmer `HmIP-BDT`
- [ ] HomeMatic IP switch `HmIP-BRC2`
- [x] HomeMatic IP blind `hmip-broll`

**Comment by Zefau** [comment]
@braindead1 Can you confirm these device identifiers? thanks in advanced.

**Comment by braindead1** [comment]
Yes, I can confirm the above identifiers, but there are many more e.g.

`HM-LC-Sw4-DR` HomeMatic 4fach Hutschienenaktor
`HM-LC-Sw2-FM` HomeMatic 2fach Unterputzaktor
`HM-LC-Sw4-PCB` HomeMatic 4fach Schaltaktor
`HM-ES-PMSw1-Pl` HomeMatic 1fach Zwischenstecker
`HM-LC-Bl1-FM` HomeMatic Unterputz Rolladenaktor

Just to mention some of the devices I use which as of now are supported by a function in jarvis.

**Comment by Zefau** [comment]
Absolutely true. I just needed the confirmation for the specific one, so I know their types and so I'm able to tell the difference between HomeMatic and HomeMatic IP.

You can see that here https://github.com/Zefau/jarvis/blob/master/src/config/adapters/hm-prc.js#L36?

**Comment by Zefau** [comment]
Added with `1.0.0-beta.26`.

**Comment by braindead1** [comment]
I have a clean installation of `v1.0.0-beta.26`. I noticed that the original states are not created. 

Besides of that a lot of my devices are not automatically recognized:
`HM-LC-Bl1-FM`
`HM-Sec-SCo`
`HM-ES-PMSw1-Pl`
`HM-LC-Sw4-DR`
...

As HomeMatic devices can be used for different things, I guess automatically recognizing is not easy. I have 3 `HM-LC-Sw4-DR` in my garden. One is used for lights, the second is used for the watering of my lawn and the third is used for plug sockets.

**Comment by Zefau** [comment]
`HM-Sec-SCo` I have misspelled in the code. This should work with the next release.
Besides that, I have NOT added the others:
- HM-LC-Bl1-FM
- HM-ES-PMSw1-Pl
- HM-LC-Sw4-DR

Though, added are:
- HomeMatic IP heating `HmIP-BWTH`
- HomeMatic IP blind `HmIP-BROLL`
- HomeMatic IP switch `HmIP-BRC2`
- HomeMatic IP light dimmer `HmIP-BDT`

- HomeMatic window sensor (tilt) `HM-Sec-SCo` / `HM-Sec-SC-2`
- HomeMatic heating `HM-CC-RT-DN`
- HomeMatic blind `HM-LC-Bl1PBU-FM`
- HomeMatic switch `HM-LC-Sw1PBU-FM`

So, these should be working.

**Comment by Zefau** [comment]
With "_I noticed that the original states are not created._" you mean adopting all states with regards to alias devices? This works for me.

**Comment by braindead1** [comment]
In `v1.0.0-beta.28` `HM-Sec-SCo` is working fine. I suggest that `HM-LC-Bl1-FM` should be included as it's for blinds.  I'm fine with not including the others.

Regarding my comment: I though that it could make sense to also create the original states (like with the alias devices), but maybe it's fine the way it is.

**Comment by Zefau** [comment]
Has `HM-LC-Bl1-FM` the same structure as `HM-LC-Bl1PBU-FM` ? If not, could you provide the structure? I will add it then.

**Comment by braindead1** [comment]
Yes, the structure is exctly the same.

**Comment by Zefau** [comment]
Could you try `1.0.0-beta.29` ?

**Comment by braindead1** [comment]
`v1.0.0-beta.29` is working fine for me.

**Comment by Zefau** [comment]
Thanks for all the help! Almost a wrap now  :)
