### ISSUE TITLE
Gerätekonfiguration "vertauscht" nach manuellem neu-ordnen der Geräte im Widgetkonfigurator

### ISSUE THREAD

**Issue by dalig83** [Zefau/ioBroker.jarvis#590]
version: 2.1.0
OS: macOS
Browser: Google Chrome

_- Beschreibung_

Fenster: Konfiguration-Layout-Widget Konfiguration

_- Randbedingungen_
Kind1 (Datenpunkt = power)
Alle anderen Lichter (Datenpunkt = dimmer)

1. Geräte hinzufügen und konfigurieren
2. Speichern & Anwenden (--> Licht_Kind1 an 1. Position)
<img width="556" alt="Schritt 1" src="https://user-images.githubusercontent.com/64753305/104137003-f4608500-5399-11eb-9f44-8c11305c90d8.png">

3. Neu-ordnen der Geräte im Widget Konfigurator (Licht_Kind1 --> an die letzte Position) 
<img width="1588" alt="Schritt 2" src="https://user-images.githubusercontent.com/64753305/104137022-1fe36f80-539a-11eb-84d2-f039af98fdb1.png">

4. Speichern & Anwenden
5. BUG: Letztes Gerät nimmt Eigenschaften von verschobenem Gerät an (WC_OG hat Eigenschaften von Licht_Kind1 angenommen und vice-versa) 
<img width="553" alt="Schritt 3" src="https://user-images.githubusercontent.com/64753305/104137048-443f4c00-539a-11eb-8f1b-396c9077bd9c.png">
<img width="1602" alt="Schritt 4" src="https://user-images.githubusercontent.com/64753305/104137051-49040000-539a-11eb-9d26-0fa56ab29b06.png">

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/566

**Comment by Zefau** [comment]
@dalig83 könntest du prüfen, ob dies mit `v2.2.0-beta.13` behoben ist?

**Comment by dalig83** [comment]
@Zefau gerne, leider muss ich gestehen, dass ich nicht weiß, wie ich die beta installieren kann. Finde auf die Schnelle auch keine Doku oder Erklärung. Hast du da etwas zur Hand? Bin da noch relativ frisch...

**Comment by Zefau** [comment]
in ioBroker im Reiter Adapter über die "Katze" (drittes Icon von rechts):

![image](https://user-images.githubusercontent.com/14368811/104374520-46ccad80-5522-11eb-8f80-3c2aa257144e.png)

dann dort

![image](https://user-images.githubusercontent.com/14368811/104374643-7085d480-5522-11eb-9781-e578d8d3f5f6.png)

**Comment by dalig83** [comment]
1. Danke für die Anleitung, hat funktioniert!
2. Ja, das issue ist behoben in der beta13 - DANKE
