### ISSUE TITLE
Support of Lifx devices in the importer

### ISSUE THREAD

**Issue by macstone23** [Zefau/ioBroker.jarvis#592]
It would be great to have support for Lifx devices.

<img width="1163" alt="Lifx-Lampe" src="https://user-images.githubusercontent.com/68864439/104186517-cff6be00-5416-11eb-9c48-8fee6ceea1fa.png">

**Comment by Zefau** [comment]
ca 125 users

**Comment by Zefau** [comment]
@macstone23 kann ich gerne zum Importer hinzufügen, aber es scheint mir, als hättest du nur ein Gerät? Das könntest du auch manuell anlegen? ;-)

**Comment by Zefau** [comment]
@macstone23 added with `v2.2.0-beta.14`.

**Comment by macstone23** [comment]
@Zefau klar, bei nur einer Lampe kann man es auch manuell anlegen, hab ich auch gemacht. Wenn es aber mehrere Leute nutzen, macht ja ein Hinzufügen zum Importer Sinn, falls es für dich kein großer Aufwand ist. ;-)
Ich teste mal, ob es funktioniert.

**Comment by Zefau** [comment]
@macstone23 funktioniert's? :)

**Comment by macstone23** [comment]
Ja, das funktioniert. Komme leider momentan nicht viel fürs Smarthome,
sorry, weil ich nicht gleich geantwortet habe.

Am Fr., 5. Feb. 2021 um 23:07 Uhr schrieb Zefau <notifications@github.com>:
