### ISSUE TITLE
Rename of DP name in devices causes wrong select of Body DP and primary DP in widget

### ISSUE THREAD

**Issue by testit2020** [Zefau/ioBroker.jarvis#594]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker
![image](https://user-images.githubusercontent.com/68483974/104191484-da688600-541d-11eb-84d3-e4dc0fe95dd4.png)
DP **on** was renamed to **meross_on**.
![image](https://user-images.githubusercontent.com/68483974/104191282-9b3a3500-541d-11eb-96c9-61a6591cd083.png)
In the widget the DP changed to the second DP 'energy_sparen', but the trigger element is not changed.

`2.2.0-beta.11`

**Comment by testit2020** [comment]
And the position of the DP in the device is changed to the top. Before it was the second, after change it is the first poition in the device.

**Comment by testit2020** [comment]
Perhaps the same sort Problem:
After added a device to widget, move above some other, and save and close.
![image](https://user-images.githubusercontent.com/68483974/104192727-878fce00-541f-11eb-909f-349798e8ca05.png)
Then is a expression in the DP which is not defined in all the devices, which are used for the widget.

**Comment by Zefau** [comment]
- [ ] https://forum.iobroker.net/post/554826

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/555

**Comment by Zefau** [comment]
@testit2020 Könntest du das nochmal mit `v2.2.0-beta.16` prüfen? Ein Löschen des Datenpunkts entfernt diesen auch in den Widgets (im Body wird gelöscht und im Action auf den ersten Datenpunkt zurückgesetzt). Ein Umbenennen im Gerät benennt es nun auch korrekt im Widget um.

**Comment by testit2020** [comment]
bri(led-k-oben) geändert in brightness:
![image](https://user-images.githubusercontent.com/68483974/104823409-249c9d80-584a-11eb-805d-3db55b308713.png)
wird plötzlich bei LED-K-unten eingefügt
![image](https://user-images.githubusercontent.com/68483974/104823435-485fe380-584a-11eb-856d-fe9ce0718b79.png)

**Comment by Zefau** [comment]
@testit2020 kannst du mal prüfen, ob das mit `v2.2.0-beta.19` behoben ist?

**Comment by testit2020** [comment]
`2.2.0-beta.20`
Trotz Änderung vom Namen bri -> brightness, keinerlei Änderung in der Widget-Konfiguration:
![image](https://user-images.githubusercontent.com/68483974/104939795-2cc31d00-59b1-11eb-86ee-6e7d8e3306d1.png)

**Comment by Zefau** [comment]
@testit2020 kannst du das nochmal mit `v2.2.0-beta.27` probieren? 

Bei mir funktioniert es kurioserweise soweit.

**Comment by testit2020** [comment]
Mit `2.2.0-beta.27`funktioniert es. Änderung vom DP-Namen werden korrekt weitergegeben.
