### ISSUE TITLE
Support of homematic device HM-LC-RGBW-WM (RGBW Dimmer) in the importer

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#596]
It would be great to have support for this homematic device

![image](https://user-images.githubusercontent.com/22911084/104420967-f897c880-557a-11eb-8f03-4cedcaac6a3c.png)
Channel 0
![image](https://user-images.githubusercontent.com/22911084/104421195-51fff780-557b-11eb-9baf-a3128876c393.png)
Channel1 (Dimmer)
![image](https://user-images.githubusercontent.com/22911084/104421281-6f34c600-557b-11eb-83f3-040541e0e728.png)
Channel2 (Colour)
![image](https://user-images.githubusercontent.com/22911084/104421356-870c4a00-557b-11eb-9897-c89f8dd5eb92.png)
Channel 3 (Program)
![image](https://user-images.githubusercontent.com/22911084/104421430-9db2a100-557b-11eb-8592-42b5c640fe79.png)

[hm-rpc.0.XXXXXXXX.json.txt](https://github.com/Zefau/ioBroker.jarvis/files/5807141/hm-rpc.0.XXXXXXXX.json.txt)

**Comment by Zefau** [comment]
added with `v2.2.0-beta.14`.

**Comment by MarkSau** [comment]
Vielen Dank für die rasche Implementierung. Ich weiß nicht genau wie Homematic das macht, aber wenn ich über die HM Gui einschalte (Level) dann wir der zuletzt eingestellter Level genommen. D.h. wenn ich über Jarvis einschalte, geht der Level auf 100% und nicht z.b. 50%, wie zuletzt. Die Implementierung wird aber schwieriger, da Javis sich den letzten Level merken müsste. Oder es müsste beim Einschalten das Objekt "OLD_LEVEL" auf true und direkt wieder auf false gesetzt werden. In dem Fall schaltet der Dimmer auf 50%. Ausschalten geht aber trotzdem nur über Level=0.

**Comment by Zefau** [comment]
Das geht aktuell in jarvis nicht und wäre auch etwas aufwändiger einzubauen.

Du könntest in den Geräte-Eigenschaften `level` definieren. Dieser Wert würde dann beim initialen Schalten greifen. Siehe Wiki: https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#datenpunkt-eigenschaften
Ist dann nicht der zuletzt gewählte Wert, aber geht immerhin in die Richtung.

Ansonsten könntest du für `OLD_LEVEL` noch einen Datenpunkt im Gerät in jarvis anlegen und mittels Trigger ansprechen, um das Gerät anzuschalten. Dies müsstest du dann aber in Kombination mit dem anderen Datenpunkt machen.
