### ISSUE TITLE
KNX Import does not work

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#597]
> Hi @Zefau , ich hab das neue Release (2.2.0.beta13) bei mir gerade mal getestet. Es erkennt gar keine KNX Geräte mehr. Irgendwas scheine ich komplett anders zu machen.
Danke schon mal, dass Du an dem Thema weiter entwickelst.

_Originally posted by @Andr3asB in https://github.com/Zefau/ioBroker.jarvis/issues/231#issuecomment-759298053_

**Comment by Zefau** [comment]
fixed with `v2.2.0-beta.14`.

**Comment by Andr3asB** [comment]
@Zefau, es funktioniert wieder. Der Import findet wieder die KNX Objekte und legt die Geräte auch wieder an.
