### ISSUE TITLE
Kalendervorschau wird nicht unter Safari Browser angezeigt

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#598]
Aktuell wir bei mir die Kalendervorschau nicht auf meinen iOS Geräten angezeigt. Unter Windows mit dem Edge Browser hingegen schon

**Comment by Zefau** [comment]
Mit Kalendervorschau ist der Mini-Kalender gemeint, richtig? Oder der darunter gezeigte List- bzw. Grid-View?

**Comment by WW1983** [comment]
Damit ist die Liste gemeint

**Comment by Zefau** [comment]
Funktioniert denn der Grid-View in Safari und nur der ListView geht nicht? Oder geht beides nicht?

Ich hab leider kein Safari auf Windows, insofern kann ich es nicht nachstellen.

**Comment by SWE1008** [comment]
Funktioniert beides nicht. Termine werden erst angezeigt wenn man auf ein bestimmtes Datum drückt an dem Termine vorhanden sind. Dann werden aber auch nur die Termine dieses Tages angezeigt.

**Comment by Zefau** [comment]
Das ist auch so beabsichtigt. Was ist denn eure Erwartungshaltung? 

Initial erfolgt die Rückschau / Vorschau auf Basis der Konfiguration. Die Tage die in diese Rückschau / Vorschau fallen sind auch im Mini-Kalender farblich hinterlegt. Beim Klick auf ein Datum wird nur das spezifische Datum gezeigt.

**Comment by SWE1008** [comment]
Und genau diese Initiale Vor / Rückschau wird eben nicht angezeigt. Erst wenn man ein Datum anklickt wird überhaupt was angezeigt, vorher nicht. 

Ich habe die Konfiguration auf 7 Tage Vorschau eingestellt. So wie ich das verstehe müsste dann bei der initialen Anzeige alle Termine in diesen kommenden 7 Tagen angezeigt werden, oder?
Es wird nichts initial angezeigt. Soll das so? Dann könnte man sich die Vorschau sparen.

**Comment by Zefau** [comment]
Nein, soll nicht so, ist dann tatsächlich falsch.

**Comment by Ash2k80** [comment]
Kann ich bestätigen, hier Safari auf iPhone wird nichts angezeigt: 
![IMG_E5835](https://user-images.githubusercontent.com/45003777/105779465-c0c35480-5f6e-11eb-892e-bd95d7342684.JPG)


Gleiche Problem mit Chrome auf iPhone.

Unter Windows mit Chrome funktioniert es:
![jarvis](https://user-images.githubusercontent.com/45003777/105779218-295e0180-5f6e-11eb-90d1-88258f0b8792.PNG)

**Comment by WW1983** [comment]
@Zefau Brauchst du für das Problem noch irgendeinen Input oder weißt du woran es liegen könnte? Wenn wir dir irgendwie helfen könne, sag bescheid.

**Comment by Ash2k80** [comment]
Hab hier noch meine weiteren Probleme mit dem Kalender-Widget niedergeschrieben:

[(https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/3336?_=1612356415548)]

**Comment by Zefau** [comment]
Anzeige in Safari sollte mit `2.2.0-beta.34` funktionieren.

**Comment by Ash2k80** [comment]
Danke klappt jetzt!

**Comment by SWE1008** [comment]
Kann ich bestätigen. Funktioniert auch bei mir.
