### ISSUE TITLE
add option in Device configuration to add state to ioBroker.iot

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#599]

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.2` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.2`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
- Es wird nur in iot was angelegt, wenn im Label etwas drin steht. Dazu sollte es ein Popup geben, wenn dem nicht so ist, wenn man den Schalter einschaltett.


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/f1126758-c064-4a70-a6a2-49c4d7678b10)
- Die Typen werden nicht gesetzt. Da sollte es auch einen Hinweis geben, dass man da noch was machen muss?
Oder direkt den Type auswählbar setzen?
In diesem Fall ein JSON als Type string, vielleicht deswegen keine Zuordnung im Feld in iot?

-  es kommt keine Warnung wenn iot-Instanz gar nicht aktiv ist?

**Comment by mcuiobroker** [comment]
Auch hier ist das allgemeine Proble, dass man die Daten erst mit Speichern sichern muss und dann erst mit Speichern und zurück zum Frontend darf. Der direkte Weg über Speichern und zurück funktioniert nicht.

**Comment by Zefau** [comment]
> Es wird nur in iot was angelegt, wenn im Label etwas drin steht. Dazu sollte es ein Popup geben, wenn dem nicht so ist, wenn man den Schalter einschaltett.

Es wird der Geräte-Name, das Geräte-Label sowie Geräte-Aliases und State-Label genommen. Wie sieht denn dein Gerät aus?

> Die Typen werden nicht gesetzt. Da sollte es auch einen Hinweis geben, dass man da noch was machen muss?

Es wird das Gewerk des Geräts genommen.

> es kommt keine Warnung wenn iot-Instanz gar nicht aktiv ist?

Ja, ohne IoT muss ich es deaktivieren, stimmt.

**Comment by mcuiobroker** [comment]
Da man nicht immer möchte, dass alle Geräte (Name, Label und Aliase in IOT hinzugefügt werden, wäre eine Optionale Einstellung sinnvoll?

**Comment by Zefau** [comment]
Jo, ich lass es erstmal so und später kann ich es ausbauen. Analog zur History-Aktivierung mit den Detail-Optionen.

Warum ging es bei dir mit dem Gerät initial nicht? Also warum war dein Eintrag leer?

**Comment by mcuiobroker** [comment]
Ich weiß nicht genua,kann auch sein, dass es mit dem "nicht" speichern zusammen hing.
Das war mein Gerät. Erst ohne Label.


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/0a4db26d-5d09-4562-9717-7b65ae5872e7)

**Comment by Zefau** [comment]
> Vielleicht sollte es auch in den iot-Geräten dann einen Hinweis geben, dass es von jarvis kommt?

Inwiefern? Im Log meinst du?

**Comment by mcuiobroker** [comment]
Ich dachte man könnte hier den Text beeinflussen


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/5b12acee-01a4-4be2-8b9e-bb02b3dbb9df)

Und dort halt `from Jarvis` ergänzen?

**Comment by Zefau** [comment]
Wüsste nicht, ob / wie das geht. Im Objekt selbst gibt es nur die Konfiguration:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/96d2ed84-585d-4f4f-bf98-ba97eb0c08ad)

Das ist quasi das, was ich mit jarvis auslese bzw. setze.

**Comment by mcuiobroker** [comment]
ok. Dann wie gesagt einen Hinweis, wenn der Type vom Gerät nicht passend ist zum "SmartType" vom IOT.
Also da ich ja "Sonstige" verwendet hatte, müsste ein hinweis erscheinen -> Geht nicht da SmartType nicht passt, oder so?

**Comment by Zefau** [comment]
Ich kann auch einfach einen anderen nehmen dann. Die Frage ist, was passiert, wenn der SmartType falsch ist? Hat das Auswirkungen? Alternativ erscheint mir "SWITCH" immer ein guter Standard.

**Comment by mcuiobroker** [comment]
#2070 hatte damit zu tun.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.6` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.6`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Zefau** [comment]
@mcuiobroker mit `v3.2.0-alpha.6` kann nun gewählt werden welche Bezeichnungen für die IoT-Cloud genutzt werden sollen
