### ISSUE TITLE
Skip non existing groups while parsing the layout definition

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#6]
It is possible to configure groups of devices and not use it in the layout, which is fine. Using a group in the layout without having it defined under devices causes jarvis to not render the layout. Instead the screen stays gray.

Possible solution: While parsing the layout definition, check if a group is available. If not, skip the group or handle it appropriately.

**Comment by Zefau** [comment]
Should be fixed with v0.0.2. Could you please test and verify? Thanks

**Comment by braindead1** [comment]
I just tested the v0.0.2 and the bug is fixed in that version.
