### ISSUE TITLE
Stop button of blind level state not working in pop-up

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#60]
I just noticed that the stop button of the blind level state is not working in the pop-up, but it is working on the widget. Maybe this is another reason to make sliders consistent in jarvis as I mentioned in #58 :-)

![image](https://user-images.githubusercontent.com/2136249/92350189-8436af80-f0d8-11ea-9ba5-c50d9ed5f38e.png)

**Comment by Zefau** [comment]
Should be resolved with `1.0.0-beta.21`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.21`

**Comment by gu3nter** [comment]
Hi,

first of all, great work.
I wanted to ask which device you are using for blind control.
I´m using shelly 2.5 and for me the stop button is not working. (for me it´s not working in pop-up and on the widget)
Could you please have a look a agein into this topic?

**Comment by Zefau** [comment]
Shelly config:

![image](https://user-images.githubusercontent.com/14368811/93125252-23583a00-f6cb-11ea-9c64-b4a629eecd30.png)

What's your config ?
Do you any errors in the browser console (not ioBroker log) ?

**Comment by gu3nter** [comment]
Hi,

thanks for the fast reply. Changing the activity trigger to *.Pause did the trick. Now everything is working great.

Yeah ;)

**Comment by Zefau** [comment]
added to documentation with `v1.0.0-rc.3`, see https://github.com/Zefau/ioBroker.jarvis/wiki/de-Devices#beispielkonfigurationen
