### ISSUE TITLE
add option in Device configuration to add state to any history adapter

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#600]

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.2` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.2`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Wenn man ein history db auswählt wird diese nur aktiviert.


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/ae02a8d7-a141-4bba-aa42-fe28e7ffb60e)

- Man sollte dort sein Standard-Einstellungen in den jarvis-Einstellungen hinterlegen können. Da man ja sonst wieder in jeden aktivierten DP gehen muss um diese dort zu ändern

**Comment by Zefau** [comment]
Die Standardeinstellungen triffst du in den Instanzeinstellungen des jeweiligen History-Adapters. Diese default-Einstellungen wendet jarvis dann an. Historie geht nur auf Anzeige.

**Comment by mcuiobroker** [comment]
ok
