### ISSUE TITLE
Color Picker for HEX RGB Lamps

### ISSUE THREAD

**Issue by Zreeper** [Zefau/ioBroker.jarvis#602]
Der Farbpicker für HEX RGB Lampen ist nicht so praktisch auf mobilen Geräten oder Tablets.
Umso besser ist der Farbpicker für HUE RGB Lampen, leider kann man diesen nicht für HEX RGB Lampen nutzen, da dieser keine HEX-Farben zurückgibt. Wäre es möglich einen besseren Farbpicker auch für HEX Lampen anzubieten?

**Comment by mcuiobroker** [comment]
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/5007

**Comment by Zefau** [comment]
In v3 Hue Pickerl can be used for Hue, RGB or Hex. Output Format is detected based on Input Format.

**Comment by Zefau** [comment]
With `v3.1.0-alpha.9` introduced the Trigger Elements `LightHueAction` / `LightColorAction` (as a color picker).
