### ISSUE TITLE
Charts als Popup

### ISSUE THREAD

**Issue by Zreeper** [Zefau/ioBroker.jarvis#603]
Es wäre praktisch wenn man Charts auch als Popup anzeigen könnte wenn man auf ein Gerät / Thermometer klickt und hierfür kein extra Widget erstellen muss, welches viel Platz auf einer Seite/Tab einnimmt

**Comment by Zefau** [comment]
Ist doppelt zu https://github.com/Zefau/ioBroker.jarvis/issues/292. Bitte für https://github.com/Zefau/ioBroker.jarvis/issues/292 voten.
