### ISSUE TITLE
Support of homematic device HmIPW-DRBL4 (4x shutters / blinds) in the importer

### ISSUE THREAD

**Issue by Hosenroller** [Zefau/ioBroker.jarvis#604]
can you support the device HmIPW-DRBL4, too?
One Hadware module controle 4 shutters / blinds.

THANK YOU

![image](https://user-images.githubusercontent.com/15867313/104834235-6bb47e00-589e-11eb-8998-8279bf526b4d.png)
![image](https://user-images.githubusercontent.com/15867313/104834250-82f36b80-589e-11eb-86e4-d52aa30d91cd.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/550

**Comment by Zefau** [comment]
@Hosenroller I implemented the device in the Importer, so you'll be able to find. Though, due to the current implementation of BlindLevelAction, you will currently not be able to use the STOP button of that component.

This will be changed with #550.

**Comment by Zefau** [comment]
added with `v2.2.0-beta.20`.

**Comment by dentro-git** [comment]
Hey @Zefau, mein Importer für den HMIP Access Point läuft sei v2.2.0-beta.15 garnicht mehr. Also er sucht, aber das endlos ohne was zu finden. Die anderen Adapter laufen durch wenn ich HMIP Access Point deaktiviere! Hab die v2.2.0-beta.20 gerade getestet, leider das gleiche.
![image](https://user-images.githubusercontent.com/77006779/104895561-57dc4b00-5976-11eb-8d00-e3b1f6277039.png)


Wenn es kein generelles Problem ist muss ich mal weiter suchen. Neu gestartet usw. habe ich natürlich schon.

Gruß Dennis

PS: Die werte der importierten Devices funktionieren. Also generell ist alles gut.

**Comment by Hosenroller** [comment]
> @Hosenroller I implemented the device in the Importer, so you'll be able to find. Though, due to the current implementation of BlindLevelAction, you will currently not be able to use the STOP button of that component.
> 
> This will be changed with #550.

 @Zefau Ich habe die Version 2.2.0.beta.20 getestet.
Die Geräte werden gefunden, angelegt, und Level funktioniert
Ich hätte allerdings erwartet das ich 4 Geräte in der Visualisierung bekomme die ich jeweils mit Pfeil nach oben und unten steuern kann. Wäre das möglich?

**Comment by Zefau** [comment]
@dentro-git hast du einen Fehler im Browser Log (F12) ?

**Comment by Zefau** [comment]
@Hosenroller mit `v2.2.0-beta.21` siehe https://github.com/Zefau/ioBroker.jarvis/issues/550#issuecomment-762475994

Beim Auswählen von `BlindLevelAction` den Datnepunkt `activity` und `stop` in den Optionen auswählen.

**Comment by dentro-git** [comment]
@Zefau Ja, ich habe einen Fehler wenn ich den Adapter lesen will...

![image](https://user-images.githubusercontent.com/77006779/105010892-92102000-5a3c-11eb-9771-bc9ded2d7530.png)

**Comment by Zefau** [comment]
@dentro-git probier bitte nochmal mit `v2.2.0-beta.22`.

**Comment by dentro-git** [comment]
@Zefau hab mit der v2.2.0-beta.22 das gleiche.
Aber #615 scheit ja 100% das gleiche Problem zu sein. Werde da also weiter dem Geschehen folgen. Dann haben wir das Zentral.
![image](https://user-images.githubusercontent.com/77006779/105159207-1af78c00-5b0f-11eb-819b-c39fb278c4c7.png)

**Comment by Hoempi** [comment]
Ich vermute, dass ich hier richtig bin ;-) 

Auch bei mir werden nun die kompakten Thermostate und Wandthermostate mit Stellrad und Display richtig erkannt, die Datenpunkte habe ich noch nicht geprüft.

Aber: nach dem Import mit der aktuellen Beta habe ich auf einmal 30 Einträge in Rolladen / Jalouise, obwohl ich nicht ein Gerät dieser Klasse besitze:
![image](https://user-images.githubusercontent.com/40570297/105464665-38a12e80-5c92-11eb-8d04-54a8e4005fbc.png)
Ich erkenne zumindest folgende Dinge wieder: Räume (z.B. Flur, Büro), Access Point und Clients (z.B. Pixel 4, Google Assistand Client, ioBroker)

Auch in anderen Bereichen scheinen sich eher Konfigurationsdaten eingeschlichen zu haben:
![image](https://user-images.githubusercontent.com/40570297/105465033-b5cca380-5c92-11eb-82c2-f86c5c0a142f.png)

**Comment by Zefau** [comment]
@dentro-git kannst du mir deine Objekt-Struktur von hmip exportieren und per zefau@mailbox.org schicken? Dann kann ich es einfacher durchprobieren. danke dir.

**Comment by Zefau** [comment]
@Hoempi das Gewerk wird automatisch auf Basis der Datenpunkte und des Namens ermittelt, insofern wurde hier scheinbar `blind` (= Jalousien / Rollladen) für die von dir gezeigten Geräte ermittelt.

Nachdem du den Importer laufen gelassen hast, hast du dann alles ausgewählt und übernommen? Oder bist du selektiv vorgegangen? 

Kannst du mir im Zweifel auch deinen Objekt-Baum mal exportieren und zuschicken? Dann kann ich mir das besser im Detail anschauen.

**Comment by Zefau** [comment]
@dentro-git danke dir. Mit `v2.2.0-beta.24` sollte es jetzt passen.

@Hoempi die merkwürdigen Geräte sollten mit `v2.2.0-beta.24` nun auch verschwinden.

**Comment by Zefau** [comment]
@dentro-git  @Hoempi passt das soweit aus eurer Sicht? Kann ich das Issue schließen?

**Comment by dentro-git** [comment]
@Zefau Bezüglich dem HmIPW-DRBL4 kann ich nichts sagen da ich das Gerät nicht besitze.. Aber der Bug das man über den HMIP Adapter nicht mehr suchen kann ist in jedem Fall behoben. Also denke der kann zu!

Ps.: Generell finde ich übrigens das jetzt übertrieben viele Signale pro Gerät importiert werden. Das macht die Sache etwas unhandlich gegenüber den Stable Versionen. Aber denke das gehört hier nicht her und ist sicher auch Geschmackssache..

**Comment by Zefau** [comment]
Was meinst du mit "viele Signale pro Gerät importiert werden"? Dass zu viele Datenpunkte importiert werden? Bzgl. dessen weiß ich persönlich nicht, was notwendig ist und bin da auf die Community angewiesen. Was kann denn deiner Ansicht nach raus?

**Comment by Hoempi** [comment]
@Zefau Entschuldige, dass ich nicht mehr geantwortet hatte. Nachdem ich die Geräte rausgeschmissen hatte erkennt der Importer jetzt fast alles richtig. Folgende Punkte fallen noch auf:

1. Der Access Point selbst wird in als Rollladen / Jalouise eingeordnet:
![image](https://user-images.githubusercontent.com/40570297/107128305-ed576480-68bc-11eb-856c-ebdee4c8d89b.png)
2. Eine Steckdose die bereits konfiguriert ist, wird erneut erkannt:
![image](https://user-images.githubusercontent.com/40570297/107128358-53dc8280-68bd-11eb-95bf-56791d763b8a.png)
Bereits in Nutzung:
![image](https://user-images.githubusercontent.com/40570297/107128363-5ccd5400-68bd-11eb-92d7-9dd352779f98.png)

Das könnte ggf. daran liegen, dass ich den Namen der Steckdose zwischenzeitlich in der Homematic-App geändert hatte. Aber das wären dann ja eher neue Issues, denke ich. Das eigentliche Thema der Unterstützung von HmIPW-DRBL4 dürfte davon ja nicht betroffen sein.

**Comment by Zefau** [comment]
alles klar, danke für die Rückmeldung. Ich schaue mir das mal an.
