### ISSUE TITLE
CustomHTML Sizing

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#606]
Kann man dem CustomHTML die Größe noch mitgeben (wie z.b. im iframe)? Ich hab ein SVG eingebettet und würde dies gerne auf eine bestimmte Größe skalieren

![image](https://user-images.githubusercontent.com/25475385/104839225-f5287800-58bf-11eb-8620-afbe14d5c58a.png)

**Comment by Zefau** [comment]
Geht das nicht über die Höhe des Widgets zu steuern?

**Comment by duczz** [comment]
Dann wird nicht skaliert sondern abgeschnitten

**Comment by Zefau** [comment]
Obsolete with v3, because Widget has fixed height and module will adapt it
