### ISSUE TITLE
Weekday does not refresh/change after midnight

### ISSUE THREAD

**Issue by Andr3asB** [Zefau/ioBroker.jarvis#607]
Pre-requisites: 
Jarvis 2.2.0.beta13
Weather widget box, set up for one location.

Expected behavior:
After midnight the 5 day preview should be updated properly for the new day plus the next 4 days.
the widget in the screenshot e.g. should say "Tuesday" and "19th January" (instead of Monday).

Observed behavior (multiple days):
The fields with the weekdays (monday/tuesday/..) are not updated, but the dates below are updated.
So after midnight you will see a invalid combination of weekday and date, e.g. "monday" and "19th Jan 2021".
See the attached screenshot, which was taken on Sunday 17th Jan 2021.
To refresh the widget it requires a browser page refresh as it will never refresh over the day automatically.
This issue occurs only, if the visualization is running over midnight.

Thanks for picking up and fixing this issue.

Andreas
![weather-widget-issue](https://user-images.githubusercontent.com/44557554/104850269-68e17980-58ee-11eb-8fe1-9a8b49897640.jpg)

**Comment by Zefau** [comment]
@Andr3asB kannst du mal prüfen, ob das mit `v2.2.0-beta.19` behoben ist?

**Comment by Andr3asB** [comment]
Update ist installiert, jetzt abwarten bis 0:01 - oder morgen früh ;-) 
Ich melde mich dann wieder.

Ich bin begeistert mit welchem Tempo und Elan Du hier dabei bist!

**Comment by Andr3asB** [comment]
@Zefau hab erst um 0:10 Uhr nochmal geschaut, aber da war auch der Tageswechsel noch nicht vollzogen (Kann es sein, dass da noch ein Zeitzonen-Thema existiert, weil die Wetterdaten ja UTC sind?). Habe um 0:10 die Seite im Browser auch sicherheitshalber neu geladen.
Der Screen war dann über Nacht im Bildschirmschoner-Modus und heute morgen stand da "Dienstag, 20. Januar" - schein also noch nicht behoben zu sein.

**Comment by Zefau** [comment]
With `v2.2.0-beta.21` this should be finally resolved now.

**Comment by Andr3asB** [comment]
Hi @Zefau , Problem is solved now. Verified the issue has gone over two days now. Thanks for fixing this.
