### ISSUE TITLE
Gewerk manuell vergeben

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#608]
Kannst du dort das Gewerk manuell editierbar machen, ohne immer extra in den Editor gehen zu müssen.

![image](https://user-images.githubusercontent.com/25475385/104853161-47d55480-58ff-11eb-9639-95974fb4d404.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/188

**Comment by Zefau** [comment]
Wird mit https://github.com/Zefau/ioBroker.jarvis/issues/188 möglich sein
