### ISSUE TITLE
HmIP-STHO support

### ISSUE THREAD

**Issue by onlyKlausM** [Zefau/ioBroker.jarvis#610]
Nutze ein Homematic **HmIP-STHO** Außentemperatur Sensor, der beim Import neuer Geräte nicht erkannt wird. 

![image](https://user-images.githubusercontent.com/59437453/104909287-ec02de00-5987-11eb-8551-5a4e1e10ac0d.png)

**Comment by Zefau** [comment]
This has already been added in `v2.2.0-beta.20`. Could you test and verify?

**Comment by onlyKlausM** [comment]
thanks ! it works with v2.2.0-beta.20

**Comment by onlyKlausM** [comment]
thanks ! it works with v2.2.0-beta.20
