### ISSUE TITLE
Zeitleiste des Charts: nicht sichtbar bei 3 Spalten und geringer Auflösung

### ISSUE THREAD

**Issue by SevenUp666** [Zefau/ioBroker.jarvis#611]
Ich stelle in 3 Spalten 3x Charts da. Am PC ist alles Bestens. Am Handy ebenfalls, da dort auf 1 Spalte Ansicht gewechselt wird.
Beim Fire HD 10 mit 1920x1200 px Auflösung werden ebenfalls 3 Spalten angezeigt, aber die Zahl für die Zeitleiste ist nicht mehr sichtbar. (Kann auch am PC nachgestellt werden, wenn das Fenster kleiner gemacht wird).
[![Bild 2021-01-1819_51_41-wi8cje4.png auf abload.de](https://abload.de/img/2021-01-1819_51_41-wi8cje4.png)](https://abload.de/image.php?img=2021-01-1819_51_41-wi8cje4.png)

Kann man das optimieren?
- die einzelnen Elemente näher beieinander
- oder Uhr-Symbol ausblenden
- oder Einheit (Tage, Monate, ...) ausblenden lassen und nur den Drop-Down-Pfeil anzeigen

[![Bild 2021-01-1819_51_41-wissjj7.png auf abload.de](https://abload.de/img/2021-01-1819_51_41-wissjj7.png)](https://abload.de/image.php?img=2021-01-1819_51_41-wissjj7.png)

**Comment by Zefau** [comment]
Ich würde eine Option für die Anzahl der Spalten auf Tablet hinzufügen, ähnlich wie es aktuell für die Auflösungen der Fall ist.

**Comment by SevenUp666** [comment]
Anzahl 3 finde ich aber genau richtig. 
Die Größe finde ich optimal, man hat alles auf dem Blick ohne scrollen zu müssen. Auf 2 runterzugehen möchte ich auch nicht unbedingt.
Ist sonst einer der oben genannten Vorschläge umsetzbar?

**Comment by Zefau** [comment]
Jo, ich werd mal schauen, dass ich es stärker responsive mache

**Comment by Zefau** [comment]
Wie gestaltet sich die Situation in v3?
