### ISSUE TITLE
Nach Update auf Beta 21 nur noch weiße Seite

### ISSUE THREAD

**Issue by kaip2503** [Zefau/ioBroker.jarvis#613]
Moin, habe gerade das Update auf Beta 21 durchgeführt. Jetzt erhalte ich nur noch eine weiße Seite auf allen Devices.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors

**Comment by kaip2503** [comment]
Besten Dank für den Hinweis. Anbei 2 Screenshots. 

Jarvis aufgerufen und dann das Log geöffnet: 
<img width="572" alt="Bildschirmfoto 2021-01-19 um 08 43 44" src="https://user-images.githubusercontent.com/73375585/105003131-933c4f80-5a32-11eb-950d-d54ff226e7d9.png">

Jarvis dann nochmal neu geladen:
<img width="598" alt="Bildschirmfoto 2021-01-19 um 08 43 52" src="https://user-images.githubusercontent.com/73375585/105003163-9afbf400-5a32-11eb-8108-6e030202306e.png">

**Comment by kaip2503** [comment]
Ich habe für den Adapter gerade nochmal ein Update gemacht. Natürlich wieder auf Beta 21. Jetzt geht es wieder ganz normal.
