### ISSUE TITLE
HM-LC-Dim1T-FM no support

### ISSUE THREAD

**Issue by onlyKlausM** [Zefau/ioBroker.jarvis#614]
Unterputz-Dimmer HM-LC-Dim1T-FM wird leider beim Import neuer Geräte nicht erkannt. getestet mit v2.2.0-beta.21.
vielen Dank !

![image](https://user-images.githubusercontent.com/59437453/105044112-9f420480-5a66-11eb-8e68-e87e5455a1d2.png)

**Comment by Zefau** [comment]
added with `v2.2.0-beta.22`.

**Comment by Zefau** [comment]
@onlyKlausM klappt der Import?
