### ISSUE TITLE
hmip: importing devices does not finish

### ISSUE THREAD

**Issue by Hoempi** [Zefau/ioBroker.jarvis#615]
**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
2.2.0-beta.22
- [x] Provide your device and / or layout configuration / Bitte Geräte- und / oder Layout-Konfiguration bereitstellen 

jarvis.0.devices
`{"fensterkind_151b3":{"id":"fensterkind_151b3","name":"Fenster Kind","function":"window","states":{"unreach":{"state":{"node":"hmip.0.devices.3014F711A00000D709955ACD.channels.0.unreach"},"action":""},"lowBattery":{"state":{"node":"hmip.0.devices.3014F711A00000D709955ACD.channels.0.lowBat"},"action":""},"open":{"state":{"node":"hmip.0.devices.3014F711A00000D709955ACD.channels.1.windowOpen"},"display":{"0":"CLOSED","1":"OPEN"},"action":""}},"options":{},"attributes":{"imported":true,"manufacturer":{"name":"HomeMatic IP via Access Point","namespace":"hmip"},"_created":1610307540520}},"thermostatbad_22a39":{"id":"thermostatbad_22a39","name":"Thermostat Bad","function":"heating","states":{"unreach":{"state":{"node":"hmip.0.devices.3014F711A0000A17099908C5.channels.0.unreach"},"action":""},"lowBattery":{"state":{"node":"hmip.0.devices.3014F711A0000A17099908C5.channels.0.lowBat"},"action":""},"temperature":{"state":{"node":"hmip.0.devices.3014F711A0000A17099908C5.channels.1.valveActualTemperature"},"action":""},"setTemperature":{"state":{"node":"hmip.0.devices.3014F711A0000A17099908C5.channels.1.setPointTemperature"},"action":"hmip.0.devices.3014F711A0000A17099908C5.channels.1.setPointTemperature"}},"options":{},"attributes":{"imported":true,"manufacturer":{"name":"HomeMatic IP via Access Point","namespace":"hmip"},"_created":1610307540521}},"fensterbad_9cb3b":{"id":"fensterbad_9cb3b","name":"Fenster Bad","function":"window","states":{"unreach":{"state":{"node":"hmip.0.devices.3014F711A00000D7099583A6.channels.0.unreach"},"action":""},"lowBattery":{"state":{"node":"hmip.0.devices.3014F711A00000D7099583A6.channels.0.lowBat"},"action":""},"open":{"state":{"node":"hmip.0.devices.3014F711A00000D7099583A6.channels.1.windowOpen"},"display":{"0":"CLOSED","1":"OPEN"},"action":""}},"options":{},"attributes":{"imported":true,"manufacturer":{"name":"HomeMatic IP via Access Point","namespace":"hmip"},"_created":1610307540521}},"fensterstube_93247":{"id":"fensterstube_93247","name":"Fenster Stube","function":"window","states":{"unreach":{"state":{"node":"hmip.0.devices.3014F711A00000D569961539.channels.0.unreach"},"action":""},"lowBattery":{"state":{"node":"hmip.0.devices.3014F711A00000D569961539.channels.0.lowBat"},"action":""},"open":{"state":{"node":"hmip.0.devices.3014F711A00000D569961539.channels.1.windowOpen"},"display":{"0":"CLOSED","1":"OPEN"},"action":""}},"options":{},"attributes":{"imported":true,"manufacturer":{"name":"HomeMatic IP via Access Point","namespace":"hmip"},"_created":1610307540521}},"thermostateltern_f211d":{"id":"thermostateltern_f211d","name":"Thermostat Eltern","function":"heating","states":{"unreach":{"state":{"node":"hmip.0.devices.3014F711A0000A1709990898.channels.0.unreach"},"action":""},"lowBattery":{"state":{"node":"hmip.0.devices.3014F711A0000A1709990898.channels.0.lowBat"},"action":""},"temperature":{"state":{"node":"hmip.0.devices.3014F711A0000A1709990898.channels.1.valveActualTemperature"},"action":""},"setTemperature":{"state":{"node":"hmip.0.devices.3014F711A0000A1709990898.channels.1.setPointTemperature"},"action":"hmip.0.devices.3014F711A0000A1709990898.channels.1.setPointTemperature"}},"options":{},"attributes":{"imported":true,"manufacturer":{"name":"HomeMatic IP via Access Point","namespace":"hmip"},"_created":1610307540521}},"thermostatbüro_7fbb4":{"id":"thermostatbüro_7fbb4","name":"Thermostat Büro","function":"heating","states":{"unreach":{"state":{"node":"hmip.0.devices.3014F711A0000A1709ACCF1A.channels.0.unreach"},"action":""},"lowBattery":{"state":{"node":"hmip.0.devices.3014F711A0000A1709ACCF1A.channels.0.lowBat"},"action":""},"temperature":{"state":{"node":"hmip.0.devices.3014F711A0000A1709ACCF1A.channels.1.valveActualTemperature"},"action":""},"setTemperature":{"state":{"node":"hmip.0.devices.3014F711A0000A1709ACCF1A.channels.1.setPointTemperature"},"action":"hmip.0.devices.3014F711A0000A1709ACCF1A.channels.1.setPointTemperature"}},"options":{},"attributes":{"imported":true,"manufacturer":{"name":"HomeMatic IP via Access Point","namespace":"hmip"},"_created":1610307540521}},"heizkörperkind_02039":{"id":"heizkörperkind_02039","name":"Heizkörper Kind","function":"heating","states":{"unreach":{"state":{"node":"hmip.0.devices.3014F711A0000A17099904AE.channels.0.unreach"},"action":""},"lowBattery":{"state":{"node":"hmip.0.devices.3014F711A0000A17099904AE.channels.0.lowBat"},"action":""},"temperature":{"state":{"node":"hmip.0.devices.3014F711A0000A17099904AE.channels.1.valveActualTemperature"},"action":""},"setTemperature":{"state":{"node":"hmip.0.devices.3014F711A0000A17099904AE.channels.1.setPointTemperature"},"action":"hmip.0.devices.3014F711A0000A17099904AE.channels.1.setPointTemperature"}},"options":{},"attributes":{"imported":true,"manufacturer":{"name":"HomeMatic IP via Access Point","namespace":"hmip"},"_created":1610307540521}},"fensterküche_8cdcd":{"id":"fensterküche_8cdcd","name":"Fenster Küche","function":"window","states":{"unreach":{"state":{"node":"hmip.0.devices.3014F711A00000D7099583F9.channels.0.unreach"},"action":""},"lowBattery":{"state":{"node":"hmip.0.devices.3014F711A00000D7099583F9.channels.0.lowBat"},"action":""},"open":{"state":{"node":"hmip.0.devices.3014F711A00000D7099583F9.channels.1.windowOpen"},"display":{"0":"CLOSED","1":"OPEN"},"action":""}},"options":{},"attributes":{"imported":true,"manufacturer":{"name":"HomeMatic IP via Access Point","namespace":"hmip"},"_created":1610307540521}},"09f2b38e-f91b-4f3f-b61f-f2fb148a7f8c":{"id":"09f2b38e-f91b-4f3f-b61f-f2fb148a7f8c","function":"light","states":{"battery":{"state":{"node":"tradfri.0.RC-65536.batteryPercentage"},"icon":{"default":"battery-80"},"label":"Batterie"},"power":{"state":{"node":"tradfri.0.G-131073.state"},"action":"tradfri.0.G-131073.state","label":"An"},"dimmer":{},"level":{"state":{"node":"tradfri.0.G-131073.brightness"},"action":"tradfri.0.G-131073.brightness"},"ct":{},"colortemperature":{},"hue":{},"rgb":{"state":{"node":"tradfri.0.G-131073.color"},"action":"tradfri.0.G-131073.color"},"hsv":{},"hex":{}},"options":{},"attributes":{"_created":1610433334522,"_updated":1610527779334},"name":"Büro"},"e7c66abc-0279-4916-a92b-3b47be234dad":{"id":"e7c66abc-0279-4916-a92b-3b47be234dad","function":"light","states":{"battery":{"state":{"node":"tradfri.0.MS-65540.batteryPercentage"},"icon":{"default":"battery-80"},"label":"Batterie"},"on":{"state":{"node":""},"action":""},"power":{"state":{"node":"tradfri.0.L-65541.lightbulb.state"},"action":"tradfri.0.L-65541.lightbulb.state"},"dimmer":{"state":{"node":"tradfri.0.L-65541.lightbulb.brightness"},"action":"tradfri.0.L-65541.lightbulb.brightness"},"level":{},"ct":{},"colortemperature":{},"hue":{},"rgb":{},"hsv":{},"hex":{}},"options":{},"attributes":{"_created":1610840382969,"_updated":1610840553237},"name":"Licht Flut"},"0319d378-65a7-4e68-a89b-3f6df3d26087":{"id":"0319d378-65a7-4e68-a89b-3f6df3d26087","function":"tv","states":{"currentApp":{"state":{"node":"lgtv.0.states.currentApp"},"icon":{"default":"application"}},"connected":{"state":{"node":"lgtv.0.info.connection"},"icon":{"default":"connection"}},"volume":{"state":{"node":"lgtv.0.states.volume"},"icon":{"default":"volume-high"},"label":"Lautstärke"},"power":{"state":{"node":"lgtv.0.states.on"}}},"options":{},"attributes":{"_created":1610840708242,"_updated":1610841114038},"name":"Fernseher Stube","icon":"television"},"60d0cdd2-280b-4e06-afa6-385d25aef180":{"id":"60d0cdd2-280b-4e06-afa6-385d25aef180","function":"other","states":{"htmlTable":{"state":{"node":"bring.0.3d84f640-dba8-42b4-a413-8ce9b93f7613.contentHtmlNoHead"}}},"options":{},"attributes":{"_created":1610905499417,"_updated":1610919430510},"name":"ShoppingList","suppressPopup":true,"icon":"format-list-checkbox"}}`

**Describe the bug / Beschreibe den Fehler**
Prior to updating to 2.2.0-beta.22 I was running 2.0.0. I updated to the beta to take advantage of issue #573 as I do use some of the devices added there. When I now use "Geräte importieren" with "HomeMatic IP via Access Point Adapter" the search just keeps running and does not yield a result. I already tried restarting the jarvis instance but to no avail.

**Expected behavior**
I was expecting a list of devices, seperated into new devices, prior known devices, incorrectly configured devices and ignored devices, just like before or when using another adapter.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![image](https://user-images.githubusercontent.com/40570297/105095938-a7ba2f80-5aa6-11eb-9bea-9d2d8b8e47a9.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Thanks for the detailed issue. Could you check for error in the browser console? See https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors

**Comment by Hoempi** [comment]
Sure, no problem at all. I am using MS Edge (Chromium). I'll try using Firefox and Chrome tomorrow, if it helps.
![image](https://user-images.githubusercontent.com/40570297/105097215-88bc9d00-5aa8-11eb-94d6-82698ee9b029.png)

**Comment by dentro-git** [comment]
Wie unter #604 bereits berichtet habe ich das Problem auch. Bei mir ist der IOBroker inkl. dem Pi auf dem neuesten Stand.

**Comment by Zefau** [comment]
@Hoempi @dentro-git probiert mal bitte mit `v2.2.0-beta.23`.

**Comment by Hoempi** [comment]
Ich sehe leider noch keine v2.2.0-beta.23, weder im ioBroker wenn ich GitHub auswähle, noch hier. Oder finde ich die an anderer Stelle?

**Comment by Zefau** [comment]
`v2.2.0-beta.23` ist nun oben.

**Comment by Hoempi** [comment]
Installiert, Geräte gesucht und gefunden. Top!

Nebenher kommt mir das ganze etwas schneller vor, wurde auch die Performance optimiert seit der letzten Stable, oder ist einfach nur mein NAS weniger unter Last?

**Comment by dentro-git** [comment]
Perfekt! Jetzt läuft es wieder und erkennt fast alle Geräte :-) Super Arbeit.!!!
