### ISSUE TITLE
Versionsnummer beim Stable release

### ISSUE THREAD

**Issue by Timmes123** [Zefau/ioBroker.jarvis#620]
Hi,

ich verwende für ein paar Tests auf der Arbeit die Stable Version von Jarvis.

![image](https://user-images.githubusercontent.com/73311538/105343335-c83ad480-5be1-11eb-871e-66ee07b7688c.png)

Es wird allerdings ständig ein mögliches Update angezeigt, allerdings ist die aktuelle Version installiert, es gibt anscheinend nur einen "Versionsnamenkonflikt"

**Comment by Zefau** [comment]
Ist ein Fehler in ioBroker bzw. in ioBroker.admin. Der Versionsvergleich dort ist falsch und erkennt nicht, dass `2.0.0` größer ist als `2.0.0-rc.1`.

**Comment by Apollon77** [comment]
welche admin version?

**Comment by Zefau** [comment]
should be resolved with latest ioBroker.admin
