### ISSUE TITLE
Shelly RGBW-2 hat keinen Switch Datenpunkt

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#621]
_Originally posted by @joe-sinclair in https://github.com/Zefau/ioBroker.jarvis/issues/573#issuecomment-765551376_
> Shelly RGBW-2 hat keinen Switch Datenpunkt! Gibt es für Shellys ein eigenes Issue? Habe keins gefunden!

**Comment by Zefau** [comment]
@joe-sinclair kannst du mir die Objekt-Struktur von dem Gerät mal screenshoten?

**Comment by joe-sinclair** [comment]
Klar :-)

![Bildschirmfoto 2021-01-22 um 20 22 00](https://user-images.githubusercontent.com/77187899/105535957-e131ab80-5cef-11eb-9dca-a839f60cae6c.png)

**Comment by Zefau** [comment]
Die Channels `white1`, `white2` und `white3` sind ohne Funktion?

**Comment by Zefau** [comment]
@joe-sinclair probier nochmal bitte mit `v2.2.0-beta.24`.

**Comment by joe-sinclair** [comment]
@Zefau den Shelly kann man Einstellen, in meinem Fall werden damit 4 White Kanäle gesteuert!
Diese können einzeln geschalten und gedimmt werden

**Comment by joe-sinclair** [comment]
also....
Was mir bei den Shelly auffällt, das der Status nicht bleibt, wenn ich einschalte! Heißt der schiebe Button geht sofort wieder auf off, der Schaltzustand bleibt aber!
- Power müsste eigentlich die Watt anzeigen und keinen Schaltzustand
- Brightness bei jedem White steuert die Dimmung (man bräuchte also 4 mal Brightness)
- 4x Schaltzustand bei White (Switch White.0, Switch White.1 usw...)

**Comment by joe-sinclair** [comment]
mir ist noch etwas aufgefallen... habe jetzt eine Fritz.Dect Steckdose manuell angelegt. Wenn ich den "switch" state auf Datenpunkt (Trigger), Body Element "LastChangeBody", Action Element "SwitchAction" stelle bleibt das Action Element auf "off" obwohl es "on" sein müsste!

**Comment by Zefau** [comment]
Welcher Datenpunkt steht denn in der Anzeige?

**Comment by joe-sinclair** [comment]
der selbe wie beim trigger

**Comment by joe-sinclair** [comment]
kann das bei der fritz dect Steckdose daran liegen, das sie statt true und false, 0 und 1 ausgibt?

**Comment by Zefau** [comment]
dann über https://zefau.gitbook.io/jarvis-de/geraete/devices#datenpunkt-eigenschaften und `on`/`off`

**Comment by joe-sinclair** [comment]
hmm... da passiert gar nichts... auch wenn ich das "Action Element" ändere bleibt immer der Switch.
![Bildschirmfoto 2021-01-31 um 00 05 54](https://user-images.githubusercontent.com/77187899/106370312-f09c9e80-6358-11eb-8588-1a5d91998b0c.png)
bei "an" sollte der Schalter ja eigentlich rechts stehen.
![Bildschirmfoto 2021-01-31 um 00 06 31](https://user-images.githubusercontent.com/77187899/106370327-14f87b00-6359-11eb-973a-cce91516ae99.png)
Hab jetzt schon alle Einstellungen durch....ohne Änderung :(

**Comment by Zefau** [comment]
geht ` { "0": "false", "1": "true" }` ?

**Comment by Zefau** [comment]
Im Datenpunkt Eigenschaften stehen nur die im Wiki dargestellten Attribute (u.a. `on`, `off`) zur Verfügung.

Probier mal: `{ "on": "1", "off": "0" }`

**Comment by joe-sinclair** [comment]
oh...man.. das wars.... vielen Dank !!

**Comment by Zefau** [comment]
@joe-sinclair `v2.2.0-beta.43`:

> Power müsste eigentlich die Watt anzeigen und keinen Schaltzustand (*auch beim 2.5 Shelly)
`power` ist der an/aus Status. Die Watt Zustände findest du ab dieser Version in `powerMeter`.

> Brightness bei jedem White steuert die Dimmung (man bräuchte also 4 mal Brightness)
Ist nun für jeden Kanal drin.

> 4x Schaltzustand bei White (Switch White.0, Switch White.1 usw...)
Ist nun für jeden Kanal drin.
