### ISSUE TITLE
Shelly Importer

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#622]
RELAYS
- [x] Shelly 1
- [x] Shelly 1L
- [x] Shelly 1PM
- [x] Shelly 2.5
- [x] Shelly RGBW2
- [x] Shelly Dimmer
- [x] Shelly Dimmer 2
- [x] Shelly i3
- [ ] Shelly EM
- [x] Shelly 3EM
- [ ] Shelly Uni
- [ ] Shelly 4Pro

PLUG&PLAY
- [x] Shelly Plug
- [x] Shelly Plug S
- [ ] Shelly Bulb
- [ ] Shelly Vintage
- [x] Shelly Duo
- [ ] Shelly Button1
- [ ] Shelly Air
- [ ] Shelly Eye

SENSORS
- [x] Shelly H&T
- [x] Shelly Flood
- [x] Shelly Door / Window 2
- [ ] Shelly Gas
- [ ] Shelly Smoke

**Comment by Zefau** [comment]
Kann jemand zu den nicht angehakten Geräten einen Screenshot der Objekt-Struktur (inkl. der relevanten Unterordner) bereitstellen?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/621#issuecomment-765634206

**Comment by voyage200** [comment]
- Shelly **Plug S**

![image](https://user-images.githubusercontent.com/76617424/105609837-39c67e80-5dac-11eb-95e9-18f126839c3a.png)

- Shelly **H&T**

![image](https://user-images.githubusercontent.com/76617424/105609860-5b276a80-5dac-11eb-911b-3553dfa08c1b.png)

- Shelly **Door / Window (1)**

![image](https://user-images.githubusercontent.com/76617424/105609896-975acb00-5dac-11eb-82b5-3c46a3c5760e.png)

**Comment by voyage200** [comment]
- Shelly **i3**

![image](https://user-images.githubusercontent.com/76617424/105610281-397bb280-5daf-11eb-9ad8-cbdaf3ec7a22.png)

**Comment by itsme1893** [comment]
**Shelly Flood**
![Shelly Flood Objektstruktur - ioBroker](https://user-images.githubusercontent.com/76392481/105616066-642c3200-5dd4-11eb-8790-cb31b97e6b10.png)

**Comment by krekssus** [comment]
Mit einem 3EM kann ich aushelfen :)
![image](https://user-images.githubusercontent.com/77919836/105627760-0c73e200-5e39-11eb-80f3-35f8a1c2c203.png)

**Comment by macpo** [comment]
Shell Plug
![image](https://user-images.githubusercontent.com/17279799/106141765-eb7cfb00-6170-11eb-879f-2eb0f681378d.png)

**Comment by SWE1008** [comment]
Shelly 1L

![grafik](https://user-images.githubusercontent.com/49527041/106378928-acd18580-63a8-11eb-8d3b-5e2279f7f069.png)

**Comment by jardleex** [comment]
Shelly Duo
![SHBDUO](https://user-images.githubusercontent.com/16123075/108065788-cb00dc00-705e-11eb-81a2-27a60f4358bb.jpg)

**Comment by Zefau** [comment]
@jardleex @SWE1008 @macpo @krekssus @itsme1893 @voyage200 danke euch.

In `v2.2.0-beta.45` sind nun alle von euch zur Verfügung gestellten Geräte mit den wesentlichen Datenpunkten drin.
Sollte euch noch was fehlen, gebt gerne Bescheid. Eine Rückmeldung, ob es passt, wäre klasse.

RELAYS
- [x] Shelly 1
- [x] Shelly 1L
- [x] Shelly 1PM
- [x] Shelly 2.5
- [x] Shelly RGBW2
- [x] Shelly Dimmer
- [x] Shelly Dimmer 2
- [x] Shelly i3
- [x] Shelly 3EM

PLUG&PLAY
- [x] Shelly Plug
- [x] Shelly Plug S
- [x] Shelly Duo

SENSORS
- [x] Shelly H&T
- [x] Shelly Flood
- [x] Shelly Door / Window 2

**Comment by macpo** [comment]
@Zefau Shelly Plug passt.
