### ISSUE TITLE
Inetergirern an error display

### ISSUE THREAD

**Issue by chrineuh** [Zefau/ioBroker.jarvis#623]
Hi there,

Would it be possible to integrate an error display?

I mean something like iobroker.vis material design

But a list with error texts that is then simply visible via a state (bool) would be more practical. (Siemens HMI)

https://www.google.com/url?sa=i&url=https%3A%2F%2Fm.youtube.com%2Fwatch%3Fv%3DfKrz8PHNOMk&psig=AOvVaw1DQtLtYP6BEZgiJslUVEWl&ust=1611509116038000&source=images&cd=vfe&ved=0CAIQjRxqFwoTCJCtxLfJsu4CFQAAAAAdAAAAABAD

Dear Christoph

**Comment by Zefau** [comment]
> I mean something like iobroker.vis material design

Could you provide a screenshot of that to get an idea of what you mean?

**Comment by chrineuh** [comment]
[cid:image001.png@01D6F1C0.8E9E1D30]

Like this.

I schuld Pop up if something in the house happens like the heating have an error or something.
If everthimg is ok the it should not to be seen.

If you know About simens HMI there you make an table where you wirte in the message and in a coum nex to it the Trigger variable.
It is much easyer to use that way as the way of material design alerts there you ned to make an json string .


https://github.com/Scrounger/ioBroker.vis-materialdesign#alerts

Thanks



Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

Von: Zefau<mailto:notifications@github.com>
Gesendet: Samstag, 23. Jänner 2021 18:40
An: Zefau/ioBroker.jarvis<mailto:ioBroker.jarvis@noreply.github.com>
Cc: chrineuh<mailto:christoph.neuhold@outlook.com>; Author<mailto:author@noreply.github.com>
Betreff: Re: [Zefau/ioBroker.jarvis] Inetergirern an error display (#623)


I mean something like iobroker.vis material design

Could you provide a screenshot of that to get an idea of what you mean?

**Comment by Zefau** [comment]
sounds like https://github.com/Zefau/ioBroker.jarvis/issues/56 ?

**Comment by chrineuh** [comment]
Yes like this,

It is not work no or?

And what das the time mean can i don t set it that ist goes away when ther is no fault any more

Von: Zefau <notifications@github.com>
Gesendet: Samstag, 23. Jänner 2021 20:06
An: Zefau/ioBroker.jarvis <ioBroker.jarvis@noreply.github.com>
Cc: chrineuh <christoph.neuhold@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [Zefau/ioBroker.jarvis] Inetergirern an error display (#623)


sounds like #56<https://github.com/Zefau/ioBroker.jarvis/issues/56> ?

**Comment by chrineuh** [comment]
[cid:image001.png@01D6F22C.4973D8A0]

Von: Zefau <notifications@github.com>
Gesendet: Samstag, 23. Jänner 2021 20:06
An: Zefau/ioBroker.jarvis <ioBroker.jarvis@noreply.github.com>
Cc: chrineuh <christoph.neuhold@outlook.com>; Author <author@noreply.github.com>
Betreff: Re: [Zefau/ioBroker.jarvis] Inetergirern an error display (#623)


sounds like #56<https://github.com/Zefau/ioBroker.jarvis/issues/56> ?

**Comment by Zefau** [comment]
Closing this in favor of https://github.com/Zefau/ioBroker.jarvis/issues/56
