### ISSUE TITLE
Datenpunkt State/Trigger Picker

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#625]
Da es bei einer sehr großen Menge von Geräten unterschiedliche states und trigger Datenpunkte im JSON Format gibt, wäre es wünschenswert wenn:
1.) Datenpunkt (Anzeige und Trigger) das JSON Format direkt unterstützt
2.) Ein "Picker" eingebaut wird, mit dem ich per Mausklick diesen state/trigger direkt auswählen kann

**Comment by Zefau** [comment]
@Bernd9000 welche jarvis Version nutzt du?

Einen StateExplorer gibt es bereits:

![image](https://user-images.githubusercontent.com/14368811/105759419-beea9880-5f50-11eb-9adb-afe5a295e93f.png)
via Schraubenschlüssel:
![image](https://user-images.githubusercontent.com/14368811/105759485-d45fc280-5f50-11eb-8c3c-6ad1b0e00c61.png)


Was meinst du mit 
>  1.) Datenpunkt (Anzeige und Trigger) das JSON Format direkt unterstützt

**Comment by Bernd9000** [comment]
Ich nutze aktuell jarvis 2.2.0-beta.25.
Ja, den Datenexplorer kenn ich, 
Wenn aber genau bei diesem Datenpunkt der Wert (Value) durch ein Gerät als JSON Format hinterlegt ist, fangen die Probleme an.Hier z.b. die Datenstruktur eines BME280 Sensor der an ein ESP8266 mit Tasmota Firmware angeschlossen ist:

`**_{"Time":"2021-01-25T22:10:08","BME280":{"Temperature":0.3,"Humidity":91.2,"DewPoint":-1.0,"Pressure":1008.1},"PressureUnit":"hPa","TempUnit":"C"}_**`

Hier muß ich jetzt ein Script schreiben, das die einzelnen Werte aus der JSON-Struktur heraus liest und als einzelne Werte in mehreren virtuellen Datenpunkten schreibt, damit ich Sie in jarvis als Datenpunkt Anzeige oder Trigger mit Hilfe des Datenexplorer öffnen kann.
Da wäre es doch Praktisch wenn der Datenexplorer auch gleich ein "JSON Explorer" hätte um den gewünschten Wert auszuwählen.
Hier als Beispiel mal ein Online Daten Picker:
[https://jsonpathfinder.com/](url)

**Comment by Zefau** [comment]
Das Problem hast du aber auch mit anderen Visualisierungen oder nicht?

Wenn der "Wert" des Datenpunkts das von dir gezeigte JSON ist, dann entspricht das ja schon gar nicht der Idee von ioBroker, dass ein Datenpunkt = State einen bestimmten Wert hat.

**Comment by Bernd9000** [comment]
Naja, wenn ich hier bei meinem ioBroker unter Objekte bei den verschiedenen Adaptern rein schaue, finde ich haufenweise Werte im JSON Format. Übrigens auch bei deinem jarvis selbst :-)
