### ISSUE TITLE
StateListHorizontal wrong display

### ISSUE THREAD

**Issue by testit2020** [Zefau/ioBroker.jarvis#626]
`2.2.0-beta.26`

https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/3183

Anzeige nicht mehr zentriert
Anzeige von LastUpdate-Werten , obwohl sie ausgeschaltet sind

**Comment by Zefau** [comment]
fixed with `2.2.0-beta.27`

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/569705
