### ISSUE TITLE
Kalender widget - Refresh nach Mitternacht

### ISSUE THREAD

**Issue by Andr3asB** [Zefau/ioBroker.jarvis#629]
JarVis Version: 2.2.0-beta.21 (die aktuellste Beta teste ich heute Nacht)

![image](https://user-images.githubusercontent.com/44557554/105871990-2ad50b80-5ffa-11eb-8525-dfd4a8cc8fe4.png)

Fehler: Ist die Visu über Mitternacht offen, dann aktualisiert sich dieses Widget nicht beim Tageswechsel sondern bleibt auf dem bisherigen Tag stehen. Die hellblau unterlegten Tage werden auch nicht aktualisiert.

Erwartetes Verhalten: Ab Mitternacht wird der neue Tag dunkelblau hinterlegt und die hellblau unterlegten Tage werden entsprechend der Konfiguration aktualisiert.

Workaround: Einmal am Morgen über F5 den Browser refreshen.

**Comment by Zefau** [comment]
@Andr3asB sollte mit `2.2.0-beta.27` behoben sein.

**Comment by Andr3asB** [comment]
läuft! :-)
