### ISSUE TITLE
Bedienung möglich trotz "Transport Close"

### ISSUE THREAD

**Issue by hase747** [Zefau/ioBroker.jarvis#631]
Jarvis läuft aktuell mit der Version 2.0.

Sobald die Webseite im Hintergrund war und wieder vorgeholt wird bekomme ich die Meldung "transport close", nach 5Sekunden verbindet sich die Seite neu. Warum dies so ist konnte ich hier in alten Beiträgen bereits lesen.

Ich kann jedoch auch vor dem Neuladen die Webseite normal bedienen. Dies bringt mich zu folgernder Frage.
Gibt es eine Möglichkeit das Neuladen und Anzeigen der Fehlermeldung zu unterbinden?

web.0 | 2021-01-26 23:40:49.884 | info | (45022) ==>Connected system.user.admin from 
web.0 | 2021-01-26 23:40:48.046 | info | (45022) <==Disconnect system.user.admin from 
jarvis.0 | 2021-01-26 23:40:38.749 | warn | (45040) Wiederverbinden..
jarvis.0 | 2021-01-26 23:40:38.692 | warn | (45040) Wiederverbinden..
jarvis.0 | 2021-01-26 23:40:38.675 | warn | (45040) transport close

**Comment by skywalker3201** [comment]
Jarvis läuft bei mir mit 2.1.
Ich suche schon seit einiger Zeit eine Lösung für die ständigen Reloads nach längerer Abwesenheit. So ist das VIS eigentlich kaum brauchbar auf meinem Android-Tablet. Ich habe die gleichen Meldungen im Log.
"Warum dies so ist konnte ich hier in alten Beiträgen bereits lesen.": Wo genau? Ich konnte nichts finden. 
"Gibt es eine Möglichkeit das Neuladen und Anzeigen der Fehlermeldung zu unterbinden?": Gibt es darauf eine Antwort bzw Lösung?
