### ISSUE TITLE
Widget Ecken - Form im Label umdrehen

### ISSUE THREAD

**Issue by macpo** [Zefau/ioBroker.jarvis#633]
# Aktuelle Situation
Im Layout kann man rechts bei einem Tab kann man bestimmen, ob die Ecken eckig oder rund dargestellt werden sollen. Das Label und der Tooltip haben eine andere Reihenfolge: Label - eckig oder rund/Tooltip: rund oder eckig
![image](https://user-images.githubusercontent.com/17279799/106142994-75799380-6172-11eb-94dd-5d4263af11b3.png)

# Erwartetes Verhalten
Das Label soll "Widget Ecken (rund oder eckig)" lauten, da es der optischen Darstellung des Schalters entspricht.

So werden runde Ecken dargestellt:
![image](https://user-images.githubusercontent.com/17279799/106143456-1405f480-6173-11eb-8c30-82b466014d04.png)

So werden eckige Ecken dargestellt:
![image](https://user-images.githubusercontent.com/17279799/106143475-1a946c00-6173-11eb-8880-fd2dba9b3b92.png)

**Comment by macpo** [comment]
Getestet mit 2.2.0 beta 26

**Comment by Zefau** [comment]
@macpo fixed with `2.2.0-beta.27`.
