### ISSUE TITLE
Missing translation of functions

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#64]
In the device configuration dialogue not all functions are translated into German. Besides that I would remove the "Id" from "Datenpunkt Id" to be consistent. :-)

![image](https://user-images.githubusercontent.com/2136249/92554230-22578080-f265-11ea-9ed9-a03145acb565.png)

**Comment by Zefau** [comment]
“Datenpunkt“ holds the object path (`hue-extended.0.lights....`) while "Datenpunkt Id" is meant for the key / the identifier of the combination of state, action, icon, etc.

Shouldn't be the same name, but a more specific name might be good. Do you have an idea? Maybe  "Datenpunkt Schlüssel“ ?

**Comment by Zefau** [comment]
Actually just wondering if that information is necessary for the end user at all or if I just remove the input and generate an ID.

**Comment by Zefau** [comment]
Resolved with `1.0.0-beta.23`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.24`
