### ISSUE TITLE
Notification state archived does not work

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#640]
Using state archived still shows message in sidecar in Beta 28. Using the following message

{"title":"Keller Aufgang Heizung geändert","display":"snackbar", "state": "archived", "autoHideDuration":"3000","snackbarOrigin": { "horizontal": "left", "vertical":"bottom" }}

The sidecar looks like this

<img width="501" alt="Bildschirmfoto 2021-01-31 um 10 29 29" src="https://user-images.githubusercontent.com/2972703/106379875-3f752300-63af-11eb-9df2-881fc00d1a6f.png">

I would expect the message to be archived automatically

**Comment by Zefau** [comment]
should be fixed with `v2.2.0-beta.29`.

**Comment by Zefau** [comment]
@stephan1827 is this fixed from your perspective?
