### ISSUE TITLE
DisplayImage

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#641]
Wenn ich versuche folgendes Bild einzubinden wird nichts angezeigt.

`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 35 35"><path d="M1 1h7v7h-7zM9 1h3v1h-2v2h-1zM14 1h1v1h1v1h1v1h-1v1h-1v-133h1v1h-1z ......................"/></svg>`
![image](https://user-images.githubusercontent.com/25475385/106381807-a8629800-63bb-11eb-85ab-69f6df7a8886.png)

**Comment by Zefau** [comment]
Das `<svg ..` steht in einem Datenpunkt oder einer URL?

**Comment by duczz** [comment]
Ist der Wert eines Datenpunktes

**Comment by Zefau** [comment]
behoben mit `v2.2.0-beta.30`.

**Comment by duczz** [comment]
Nun ist das Image komplett weg
![image](https://user-images.githubusercontent.com/25475385/106425839-cd5f1580-6464-11eb-9593-798d19c95e4a.png)

**Comment by Zefau** [comment]
Bei mir geht's ?

![image](https://user-images.githubusercontent.com/14368811/106521315-5a928080-64de-11eb-923b-1df02b8342af.png)

![image](https://user-images.githubusercontent.com/14368811/106521352-69793300-64de-11eb-8c65-3c732f1d4af7.png)

![image](https://user-images.githubusercontent.com/14368811/106521374-7007aa80-64de-11eb-9c5e-5cf378238e41.png)

**Comment by Zefau** [comment]
Kannst du mir den svg code sonst teilen?

**Comment by Zefau** [comment]
@duczz wie ist der Stand mit der jüngsten beta? Geht es nach wie vor nicht?

Der Code von DisplayImage prüft auf den String `<svg` und zeigt dann einfach ein HTML:

```
	if (img === null) {
		return null;
	}
	else if (typeof img === 'string' && img.indexOf('<svg') > -1) {
		return <div dangerouslySetInnerHTML={{ __html: img }} />
	}
```

Bei mir geht das wie gesagt.

**Comment by Zefau** [comment]
![image](https://user-images.githubusercontent.com/14368811/107091782-9ab97200-6802-11eb-8c3a-52279634cead.png)

**Comment by duczz** [comment]
Ja besteht leider immer noch, ich hab aber im ganzen Seitenquelltext auch nix von einem svg dann drinstehen, mit html gehts nur wird dann nix skaliert

**Comment by Zefau** [comment]
Ok, es liegt am Chrome. Im Firefox geht es.

**Comment by Zefau** [comment]
another try with `2.2.0-beta.33`.

**Comment by duczz** [comment]
Funktioniert nun - danke
