### ISSUE TITLE
(11501) Could not load locale for language en-DE or en!

### ISSUE THREAD

**Issue by kuumaur** [Zefau/ioBroker.jarvis#644]
I see a lot of
(11501) Could not load locale for language en-DE or en!
warnings in the log, from jarvis.0
What can i do to remove these entries?

Debian 10 x64
ioBroker 3.1.6
nodejs 12.20.1
Jarvis 2.0.0

**Comment by Zefau** [comment]
Could you install v2.1 from latest repository (or v2.2-beta from Github) and verify with one of these version if the error is still present?

`en-DE` is a combination which jarvis does not know and falls back to `en`. You jarvis should be in English then, but no more warnings should appear.

**Comment by kuumaur** [comment]
My OS is in en and my Browser Firefox is in en. Jarvis is set to english.
My locales on Server machine is en-gb utf-8.
Time zone data is Europe/Berlin.
I have had no luck with 2.2.
Until now i am glade, that i have a stable system.
How serious is the 2.1 version?

**Comment by Zefau** [comment]
What do you mean by how serious v2.1 is? Currently v2.1 is in the latest repository, whilst v2.0 is in stable. v2.2 is still beta and only available on Github. 

Could you screenshot the warnings in the browser console so I get an idea of the structure?
Do you have these issues as well with v2.2 respectively v2.1 or only in v2.0?

**Comment by kuumaur** [comment]
I have had a lot of trouble with 2.2.
I had to start from scratch with 2.0.
I can give 2.1 a try.
How can a backup my config?

**Comment by Zefau** [comment]
https://zefau.gitbook.io/jarvis-de/sonstiges/backup-and-restore

**Comment by Zefau** [comment]
@kuumaur any news on this? Did you get v2.1 (or latest v2.2.-beta) to run? Did it solve the issue with the language warnings?

**Comment by Zefau** [comment]
I managed to confirm this bug. Will be resolved with next 2.2-beta.

**Comment by Zefau** [comment]
resolved with `v2.2.0-beta.34`.

**Comment by kuumaur** [comment]
I no longer see the entries.
Iam still at 2.0 (no time to do the change, sorry)
But, what i did was to update/change my locales and tzdata.
I dont no if that is a valid solution, but my logs are cleaner now.
Thanx Kuu Maur
