### ISSUE TITLE
iFrames - dimension not correct and not "touchable"

### ISSUE THREAD

**Issue by CloneBro** [Zefau/ioBroker.jarvis#645]
- Jarvis v2.2.0-beta.31

- If i say height 100% its not correct.
- iFrames are not touchable

**Screenshots**
![Bildschirmfoto 2021-02-02 um 16 53 48](https://user-images.githubusercontent.com/77991335/106625930-75fd9a00-6577-11eb-8056-15e64466cb45.png)
![Bildschirmfoto 2021-02-02 um 16 54 14](https://user-images.githubusercontent.com/77991335/106625948-7c8c1180-6577-11eb-8241-7f8684145432.png)
![Bildschirmfoto 2021-02-02 um 16 48 06](https://user-images.githubusercontent.com/77991335/106625996-8877d380-6577-11eb-9518-702afe6380ed.png)

**Comment by Tob1a5** [comment]
Kanns das Problem von mit 2.2.1 bestätigen.
Habe wieder auf 2.1.0 downgegraded. 
Da meine Home View ein VIS Iframe ist ist Jarvis mit diesem Bug für mich nicht nutzbar.

**Comment by CloneBro** [comment]
> Kanns das Problem von mit 2.2.1 bestätigen.
> Habe wieder auf 2.1.0 downgegraded.
> Da meine Home View ein VIS Iframe ist ist Jarvis mit diesem Bug für mich nicht nutzbar.

Ich nutze jetzt 2.2.2. Soweit geht alles (Bedienbarkeit). 
Beim einbinden einer VIS (Fullscreen) muss man jedoch in der Höhe die PX eintragen. 
100% funktioniert hier leider nicht. Nur in der Breite funktioniert es.

**Comment by Zefau** [comment]
@CloneBro @Tob1a5 besteht das Problem in v3 noch?

**Comment by Zefau** [comment]
besteht das Problem in v3.1 noch?
