### ISSUE TITLE
Socket issues

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#646]
https://forum.iobroker.net/post/572611

**Comment by Zefau** [comment]
Reworked with v3

**Comment by mcuiobroker** [comment]
Dies konnte ich bislang nicht mehr feststellen. Da ist ja nur noch der Punkt mit den "connected"-States. Der steht aber in einem anderen Issue schon drin. Somit kann dies geschlossen werden.
![image](https://user-images.githubusercontent.com/84818934/132382873-92437fb8-4873-4e0b-9b98-c888063cf3fa.png)
