### ISSUE TITLE
Acknowledge flag missing on switch action button

### ISSUE THREAD

**Issue by SliX185** [Zefau/ioBroker.jarvis#647]
- 2.2.0-beta.22

Hi,
Is there a way to set States with ack flag?
Like in Node Red with "command" and "value"?

Didn't find an option.

Thanks in advanced!

Und noch einen herzlichen Dank für diesen tollen Adapter!!!
Top Arbeit!

**Comment by Zefau** [comment]
This is currently not implemented but generally possible.

**Comment by Zefau** [comment]
@SliX185 mit `v3.1.0-alpha.18` kann nun der `ack` für `SwitchAction` nun auf entweder `true` oder `false` eingestellt werden.

**Comment by Schimi1983** [comment]
würde das auch bei DropownAction gehen? Das wäre super :-)

**Comment by Zefau** [comment]
@Schimi1983 schau mal mit `v3.1.0-alpha.40`

**Comment by Schimi1983** [comment]
> @Schimi1983 schau mal mit `v3.1.0-alpha.40`

Funzt (zumindest beim "DropdownAction" habe ich es getestet und "in betrieb" genommen).....

Das gibt definitiv eine Abo Verlängerung ;-)

**Comment by Schimi1983** [comment]
habe nun ein Problem...

wenn ich über "DropdownAction" umschalte bekomme ich im Log

"State value to set for "0_userdata.0.Heizung.WW-Betrieb-An" has to be type "boolean" but received type "string""

Bei "SwitchAction" funktioniert alles... was ja logisch ist.... der Switch schaltet nur um....

Bin aber überfragt was ich anpassen muss damit "DropdownAction" auch funktioniert....

Zur Zeit sieht es so aus:
![image](https://user-images.githubusercontent.com/4581474/189725497-fb67185e-c2a4-43b0-bdc0-9d52e91c8df2.png)

**Comment by Zefau** [comment]
Wie sieht deine Anzeige Variante aus?

**Comment by Schimi1983** [comment]
meinst du den Datenpunkt? Der steht auf "Logikwert"

oder wie es in der Anzeige aussieht?
![image](https://user-images.githubusercontent.com/4581474/189727876-bf3d49b7-44de-4e31-8d04-c5cfac9a3f8c.png)

ansonsten versehe ich die Frage nicht so ganz...

**Comment by Zefau** [comment]
Im Gerät musst du ja definieren welche Werte zum Dropdown angeboten werden. Dort musst du darauf achten, dass du den Boolean Wert nicht in `"` setzt.

**Comment by Schimi1983** [comment]
Also dann bei "Anzeigevariante (JSON Format)"  aus dem jetzigen

{"false":"Automatik","true":"WW-forcieren"}

quasi ein: {false:"Automatik",true:"WW-forcieren"}

machen? Aber das geht ja nicht weil der editor das erwartet...

Habe das gefühl ich bin total falsch......

**Comment by Zefau** [comment]
Jo, ist kein valides JSON stimmt. Ich kümmer mich.

**Comment by Schimi1983** [comment]
phu... also war ich zumindest richtig..... Das hilft schon auch nen bissel :-)

DANKE!!

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.0-alpha.42`

**Comment by Schimi1983** [comment]
funktioniert... brauchte mein JSON auch nicht zu ändern (ging auch nicht, war "wrong format")
