### ISSUE TITLE
Keine Notification mit FullyBrowser

### ISSUE THREAD

**Issue by simatec** [Zefau/ioBroker.jarvis#649]
Ich habe aktuell das Problem, dass die Notification mit dem FullyBrowser nicht funktioniert.
Auf meinem Rechner unter Chrome geht alles, aber mit dem Fully auf dem Wandtablet kommen weder die Popups und auch die Notificationsliste bleibt leer.
Das Popup-Fenster zur Bestätigung kommt beim Start zwar, kann aber nicht bestätigt werden

**Comment by SWE1008** [comment]
Kann ich bestätigen. Ist an meinem iPad genau gleich.

**Comment by Zefau** [comment]
sollte mit `2.2.0-beta.35` passen, könntet ihr das prüfen?

**Comment by simatec** [comment]
Kann ich bestätigen.  Mit Beta 35 geht es auch mit Fully

**Comment by SWE1008** [comment]
Passt auch mit dem iPad. Notifications kommen an.
