### ISSUE TITLE
Add possibility for boolean battery state

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#65]
As of now the `battery` state in jarvis is meant for numeric / percentage usage. Alias and HomeMatic / HomeMatic IP devices can have a boolean `LOWBAT` state. It would be great if this could automatically be handled by jarvis.

**Comment by Zefau** [comment]
Added with `1.0.0-beta.22`.

**Comment by braindead1** [comment]
In `v1.0.0-beta.24` the state `lowBattery` is created, but the pop-up needs improvement.

![image](https://user-images.githubusercontent.com/2136249/92647701-9be48280-f2e8-11ea-9a65-eccf2bd3e93e.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/66#issuecomment-689794391
