### ISSUE TITLE
Homematic IP Fenstersensor wird nicht mehr importiert

### ISSUE THREAD

**Issue by SaschaWeiher** [Zefau/ioBroker.jarvis#650]
Hi Zefau,

bei mir klappt es nicht mehr mit dem Geräte-Import von Homematic IP Fensterkontakten via Homematic IP CCU3 Adapter.

Hier meine Infos:
Jarvis 2.2.0 beta.35
HomeMatic IP CCU3 3.55.10
HomeMatic ReGaHSS Adapter: 3.0.16
HomeMatic RPC Adapter: 1.14.33

**Fehlerbeschreibung:**
Beim automatischen Import von Devices, werden die Geräte wie folgt aufgeführt:
Geräte mit inkorrekter Konfiguration (Datenpunkte nicht gefunden)

Gewerk: Sonstige other
No correct defined states found. The device may be unknown. Please help the developer to add support for this device and report to Github.

![image](https://user-images.githubusercontent.com/40891355/107149673-2a256900-695a-11eb-927d-8674bd26c62f.png)

Seltsam ist, dass ich vor zwei Tagen einen Fensterkontakt hinzufügen konnte, danach habe ich mindestens ein Update des Jarvis Adapters durchgeführt.

**Hier hat es noch funktioniert:**
![image](https://user-images.githubusercontent.com/40891355/107149411-b9ca1800-6958-11eb-8b2c-718cc8fd28a4.png)

**Comment by Zefau** [comment]
Was ist das für ein Gerät? Also Geräte-ID? Ist das Gerät im Wiki (https://zefau.gitbook.io/jarvis-de/geraete/devices/devices-importer#function-window-of-hm-rpc) gelistet?

**Comment by SaschaWeiher** [comment]
Hi Zefau,

es handelt sich um folgenden Gerätetyp:

HmIP-SWDO-PL

Homematic IP Fenster- und Türkontakt – optisch, plus
Ich konnte ihn nicht im Wiki sehen.

Danke für deine schnelle Reaktion.

Viele Grüße

________________________________
Von: Zefau <notifications@github.com>
Gesendet: Sonntag, Februar 7, 2021 22:02
An: Zefau/ioBroker.jarvis
Cc: SaschaWeiher; Author
Betreff: Re: [Zefau/ioBroker.jarvis] Homematic IP Fenstersensor wird nicht mehr importiert (#650)


Was ist das für ein Gerät? Also Geräte-ID? Ist das Gerät im Wiki (https://zefau.gitbook.io/jarvis-de/geraete/devices/devices-importer#function-window-of-hm-rpc) gelistet?

**Comment by Zefau** [comment]
Gibt es bei dem mehr als den `open` Datenpunkt den ich hinzufügen soll?

**Comment by SaschaWeiher** [comment]
Hi Zefau,

ich habe die Datenpunkte gerade mit dem HmIP-SWDO-I verglichen. Die stimmen überein.

Hier sind die Datenpunkte vom **HmIP-SWDO-PL** und die gelb markierten stimmen mit dem HmIP-SWDO-I überein und sollten ausreichen. Vermutlich reicht da schon ein Copy&Paste. ;-)
 
![image](https://user-images.githubusercontent.com/40891355/107254340-7db9b480-6a37-11eb-99fe-59f220de5284.png)

Beste Grüße,
Sascha

**Comment by Zefau** [comment]
schau mal bitte mit `v2.2.0-beta.36`.

**Comment by SaschaWeiher** [comment]
Hallo Zefau,

das hat funktioniert. Aber mit v2.2.0-beta.36 hat sich ein neuer Bug eingeschlichen. Ich bin mir gerade nicht sicher, ob ich den hier einstelle oder in einem neuen Issue.

![image](https://user-images.githubusercontent.com/40891355/107391296-d69d5180-6af8-11eb-8b57-98afa6b9031b.png)

Das "Body Element" wird plötzlich englisch ausgegeben, obwohl die Config den LanguageCode "de-DE" ausweist. Ein Wechsel auf "en-GB" führt dann zum Crash:

![image](https://user-images.githubusercontent.com/40891355/107391855-68a55a00-6af9-11eb-93b9-a635e5c092ca.png)

Wenn ich den Datenpunkt wieder händisch auf "de-DE" ändere kommt es nicht zum Crash, das "Body Element" ist dann aber weiterhin auf Englisch,

**Comment by Zefau** [comment]
geht es wieder mit `2.2.0-beta.37`?

**Comment by SaschaWeiher** [comment]
Hey Zefau,

der Language Bug ist nun behoben und die HomeMatic IP Sensoren werden importiert. Er skaliert die Inhalte aber nun anders.

Als würde er den vorhandenen Platz nicht ausnutzen.

![image](https://user-images.githubusercontent.com/40891355/107437490-6231d500-6b2f-11eb-885d-08dc4cae3581.png)

Ich konfiguriere Morgen nochmal etwas um, aber ich denke jetzt passt es an einer anderen Stellen nicht.
