### ISSUE TITLE
MediaPlayer Darstellungsfehler Alexa

### ISSUE THREAD

**Issue by Ash2k80** [Zefau/ioBroker.jarvis#651]
Beim Mediaplayer habe ich das Problem in Verbindung mit Alexa das die aktuelle Auswahl eines Echo Dot folgendes Phänomen hat:

https://user-images.githubusercontent.com/45003777/107151241-d1f26500-6961-11eb-87a5-b8eb6cd9afc0.MP4

installiert ist die Version 2.2.0 Beta 35
Alexa ist Version 3.7.1

**Comment by Zefau** [comment]
Kann den Fehler bei mir nicht darstellen. Hast du das nur auf mobil? Welche Plattform und welcher Browser sind betroffen? Gibt es Ausnahmen?

**Comment by Ash2k80** [comment]
> Kann den Fehler bei mir nicht darstellen. Hast du das nur auf mobil? Welche Plattform und welcher Browser sind betroffen? Gibt es Ausnahmen?

Das obere Video ist von Safari unter iOS aufm iPhone.

Jedoch habe ich das auch bei Chrome unter Windows 10. Hier mal ein Video davon, meine Mutmaßung ist das es etwas mit dem aktualisieren der Objekte zu tun hat, daher die auch mal im Hintergrund auf dem Video.
Bin mittlerweile auf beta .45


https://user-images.githubusercontent.com/45003777/108571296-29a0b100-7310-11eb-80ad-947f4269a893.mp4

**Comment by Zefau** [comment]
Warum werden die Datenpunkte denn so häufig aktualisiert? Insbesondere, wenn der Player aus ist?

Wie ist ist dein Alexa2 Adapter konfiguriert?

![image](https://user-images.githubusercontent.com/14368811/108589977-78c30200-7361-11eb-86c3-404801962c52.png)

**Comment by Zefau** [comment]
Welche Adapter Version hast du im Einsatz?

**Comment by Ash2k80** [comment]
Ich hatte bei Daten-Update, warum auch immer, 1 Sekunde...war eigentlich nich so schlimm weil ich die Push-Verbindung drin hatte...aber eben nur drin hatte...beim letzten Problem mit dem Adapter vor 2-3 Wochen hatte ich den testweise rausgenommen und wohl nach dem Update auf 3.7.1 nicht wieder reingenommen. Also vermutlich meine eigene Schuld ;-(

Jetzt hab ich nur noch das Problem das, wenn man mehrere Player-Widgets auf einer Seite hat die anderen sich teilweise auch aktualisieren obwohl nicht aktiv ein Gerät ausgewählt, aber da warte ich auf dein Update wenn du einen Default-Player beim Widget implementiert hast. [https://github.com/Zefau/ioBroker.jarvis/issues/616
](https://github.com/Zefau/ioBroker.jarvis/issues/616
)

Von daher würde ich sagen ist das hier erstmal erledigt, danke für deinen Support!
