### ISSUE TITLE
iFrame Modul: Inhalte werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by itsme1893** [Zefau/ioBroker.jarvis#655]
jarvis 2.2.0-beta.36

Ich musste leider feststellen, dass meine ganzseitig via iframe Modul eingebundenen Seiten nun plötzlich abgeschnitten dargestellt werden. (siehe Grafik)

![image](https://user-images.githubusercontent.com/76392481/107376452-33ddd680-6aea-11eb-9e46-79c1d59acfcb.png)

Ich habe bereits das Modul gelöscht und neu angelegt - leider keine Änderung.

Hinweis: Laut einem User im ioBroker Forum ist dies seit der Beta28 der Fall.

**Comment by Zefau** [comment]
sollte mit `2.2.0-beta.37` wieder passen.

**Comment by itsme1893** [comment]
Leider keine Veränderung mit 2.2.0-beta.37 
Es wird immer noch abgeschnitten, wie auf dem Screenshot oben.

Modul löschen und wieder anlegen hat nichts gebracht.

**Comment by Zefau** [comment]
@itsme1893 wie sieht es mit der aktuellen beta `v2.2.0-beta.50` aus?

**Comment by DNC74** [comment]
@Zefau ``2.2.0-Stable``: stelle ich ein Tab mit einem iframe-Widget auf "Tab als Vollbild" ein, wird es mit zu kleiner "viewheigth" dargestellt. Mit "Tab als Vollbild" auf aus bekommt man es zwar für Desktop-Browser "hingefummelt", indem man im Widget selbst mit den Werten "Mindest-Höhe", "Maximal-Höhe" spielt, aber ich denke, dass ist so nicht gedacht. Auf dem Handy-Browser bekomme ich es jedoch nicht manuell korrigiert. Höhe und Breite des iFrame-Fensters machen bei mir keinen Unterschied, sprich werden ignoriert. Mit ``2.1.0-Stable`` war das noch gut. Die Betas dazwischen habe ich mangels Zeit ausgelassen. 

Problematisch ist immer nur die Höhe, bei der Breite gibt's keinerlei Probleme.

So gings noch mit ``2.1.0-Stable``
``
      {
        "title": "Wetter",
        "icon": "weather-partly-snowy-rainy",
        "id": "72716318-ce2f-439f-bee5-831f7d9a666a",
        "index": 3,
        "_fullscreen": {
          "moduleConfig": {
            "url": "https://embed.windy.com/embed2.html?lat=48.950&lon=8.454&detailLat=49.000&detailLon=8.400&zoom=8&level=surface&overlay=temp&product=ecmwf&menu=&message=true&marker=true&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=bft&metricTemp=default",
            "height": "",
            "width": "",
            "refresh": "900"
          },
          "devices": [],
          "module": "iFrame",
          "title": "Windy",
          "fullscreen": true,
          "id": "87ca7f35-e80c-4634-9a27-7e7c06c5865f",
          "icon": "weather-partly-snowy-rainy",
          "index": 0
        },
        "columns": []
      },
``
So sieht es im Code dann aus, wenn man das Tab auf Vollbild stellt:
![iframe](https://user-images.githubusercontent.com/72687758/109398188-82d59980-793b-11eb-84f4-45687eb2a0a8.png)

``
...style="border: 0px; display: block; height: 26vh; width: 100%;"...
``

und so muss man sich mit ``2.2.0-Stable`` für den Desktop-Browser behelfen:

``
      {
        "title": "Wetter",
        "icon": "weather-partly-snowy-rainy",
        "id": "wetter3",
        "index": 3,
        "columns": [
          [
            {
              "moduleConfig": {
                "url": "https://embed.windy.com/embed2.html?lat=48.950&lon=8.454&detailLat=49.000&detailLon=8.400&zoom=8&level=surface&overlay=temp&product=ecmwf&menu=&message=true&marker=true&calendar=now&pressure=&type=map&location=coordinates&detail=&metricWind=bft&metricTemp=default",
                "refresh": "900",
                "height": "",
                "width": ""
              },
              "devices": [],
              "module": "iFrame",
              "title": "Windy",
              "id": "b7354b60-c92c-4797-9141-e67caf8a0ca3",
              "minHeight": "90vh",
              "maxHeight": "90vh",
              "fullscreen": true,
              "scaleContents": false,
              "justification": "center",
              "icon": "weather-partly-snowy-rainy",
              "index": 0
            }
          ]
        ]
      },
``
Gruß DNC

**Comment by itsme1893** [comment]
@Zefau 
Aus meiner Sicht funktioniert das Modul nun.  Danke

Allerdings steht noch der Beitrag von @DNC74 aus.

**Comment by masgo** [comment]
Kann das Problem von @DNC74 mit der Version `2.2.0-Stable` bestätigen.

**Comment by Tob1a5** [comment]
Kanns das Problem von @DNC74 und @masgo mit 2.2.1 bestätigen.
Habe wieder auf 2.1.0 downgegraded. 
Da meine Home View ein VIS Iframe ist ist Jarvis mit diesem Bug für mich nicht nutzbar.

**Comment by Zefau** [comment]
Besteht der Fehler mit v3 noch?

**Comment by Tob1a5** [comment]
> Besteht der Fehler mit v3 noch?

Mit 2.2.3 besteht der Fehler noch.
