### ISSUE TITLE
Unterschiedliche Darstellung von Farben auf Rechner und Tablet

### ISSUE THREAD

**Issue by noffycws** [Zefau/ioBroker.jarvis#656]
Sowohl im Datenpunkt-Stil und Icon-Stil folgenden Code hinterlegt (wie in der Dokumentation beschrieben):

```
{
   ">199":{"color":"#c96cef","fontWeight":"bold"},
   "<=199":{"color":"#ec1500","fontWeight":"bold"},
   "<150":{"color":"#cb4335","fontWeight":"bold"},
   "<100":{"color":"#f1c40f","fontWeight":"bold"},
   "<50":{"color":"#1e8449"}
}
```

Dieser wird auf dem Rechner (Windows mit Firefox / Chrome) wie folgt **richtig** dargestellt:

![Screenshot 2021-02-08 213852](https://user-images.githubusercontent.com/78761005/107438197-6a3e4480-6b30-11eb-92ba-6929e135668d.jpg)

Auf meinem Tablet (Android 11, Chrome und andere Browser) wird es aber wie folgt **falsch** dargestellt:

![Screenshot_20210208-213939_Chrome](https://user-images.githubusercontent.com/78761005/107438239-7a562400-6b30-11eb-9a8c-8fa004a5b482.jpg)

Ich nutze derzeit `2.2.0-beta-37` - der Fehler ist aber schon länger, mindestens seit `2.1.0`

**Comment by Zefau** [comment]
sollte mit `v2.2.0-beta.38` behoben sein

**Comment by noffycws** [comment]
Jepp ... jetzt passt es
