### ISSUE TITLE
Änderung an Datenpunkt eines Geräts erzeugt Änderungen im Layout - obwohl dort nichts geändert wurde

### ISSUE THREAD

**Issue by noffycws** [Zefau/ioBroker.jarvis#657]
Ich habe ein neues Gerät (PV-Anlage) manuell angelegt.

![Screenshot 2021-02-09 234545](https://user-images.githubusercontent.com/78761005/107438810-6e1e9680-6b31-11eb-88f2-5e80649e7817.jpg)

Wenn ich nun an einem Datenpunkt des Gerät etwas ändere (egal was, egal welcher Datenpunkt), dann ändert sich auch die Darstellung der Datenpunkte im Layout:

Hier wird anstatt `strom-bat` und `strom-netzbezug` der Datenpunkt `update` als sekundärer Datenpunkt überschrieben.
Aus 
![Screenshot 2021-02-09 234659](https://user-images.githubusercontent.com/78761005/107438986-ade57e00-6b31-11eb-8b01-832779236e39.jpg)
wird
![Screenshot 2021-02-09 234623](https://user-images.githubusercontent.com/78761005/107439005-b2aa3200-6b31-11eb-8daf-a81722392f8e.jpg)

Gleiches hier: Aus `strom-bat` bei `akku-level`
![Screenshot 2021-02-09 234754](https://user-images.githubusercontent.com/78761005/107439065-c81f5c00-6b31-11eb-9906-0105245802e2.jpg)
wird wieder `update`
![Screenshot 2021-02-09 234839](https://user-images.githubusercontent.com/78761005/107439085-d0779700-6b31-11eb-8ff4-d59baa32d0a4.jpg)

Aber auch primäre Datenpunkte werden verändert. Hier wird aus `pv-dach-strasse-unten`
![Screenshot 2021-02-09 234839](https://user-images.githubusercontent.com/78761005/107439165-f0a75600-6b31-11eb-8d90-d6bfd234ef4c.jpg)
`pv-status`
![Screenshot 2021-02-09 234815](https://user-images.githubusercontent.com/78761005/107439193-fb61eb00-6b31-11eb-9e0c-4fc7705d7d36.jpg)

Ich verwende derzeit die Version `2.2.0-beta-37`

Bei Änderungen an dem Datenpunkt werden immer die gleichen Anpassungen am Layout gemacht.

**Comment by Zefau** [comment]
Mit `v2.2.0-beta.39` wird das Layout nur geändert, wenn du
- Datenpunkte löscht, die im Layout verwendet werden (diese werden dann entfernt) oder
- Datenpunkte umbenannt werden, die dann auch im Layout umbenannt werden.

Alle weiteren Änderungen haben keinen Einfluss (mehr) auf das Layout.

**Comment by noffycws** [comment]
Der Fehler ist weiterhin da.
Habe einen neuen Datenpunkt manuell hinzugefügt ... der ist dann am Anfang der Liste der Datenpunkte. Der Datenpunkt wird befüllt und im Layout zur Anzeige gebracht - sonst nix geändert.
Das verändert dann wieder die Anzeige von anderen - manuell angelegten - Datenpunkten. Vermutlich, da sich die Position der Datenpunkte innerhalb des Gerätes geändert hat.

Problem damit noch nicht gelöst.
Verwende mittlerweile die `2.2.0-beta.49`

**Comment by Zefau** [comment]
Also bei mir geht es. Kannst du bitte mal Cache löschen + Web & Socket-io Adapter neustarten?
Steht in der Browser-Konsole die korrekte Version?

**Comment by noffycws** [comment]
Alles gemacht - Browser-Cache geleert, Adapater neu gestartet.

In der Browser-Konsole steht "Welcome to jarvis 2.2.0" - es kommt aber ein Fehler bzgl. der Notification.js ("Cannot read property 'val' of null; at n.value (Notifications.js:169)
    at Notifications.js:51
value @ Notifications.js:176)

Es kommt dann "Processed 88 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:"

Es bleibt dabei: Wenn ich einen Datenpunkt hinzufüge, ändere oder lösche, dann wird im Layout der Status "pv-strasse-dach-unten" in "pv-status" geändert. Hat sich übrigens seit der initialen Meldung verändert. Also muss doch was geändert worden sein mit einem der letzten Updates.

Hängt es vielleicht an der Schreibweise der Datenpunkte? beginnend mit "pv-" - oder, dass zwei Datenpunkte nahezu gleich lauten "pv-strasse-dach-feld" und pv-strasse-dach-unten"?

Benutze mittlerweile die 2.2.0-final.

**Comment by Zefau** [comment]
please move to v3
