### ISSUE TITLE
JSON Editor schließt sich sofort wenn richtiges JSON erkannt / überschreibt gemachte Einträge

### ISSUE THREAD

**Issue by noffycws** [Zefau/ioBroker.jarvis#658]
Dass man die JSON-Elemente nun mit dem Schlüssel in einem richtigen Editor bearbeiten kann finde ich super. Allerdings schließt sich der Editor bei mir sofort, wenn das JSON-Element scheinbar richtig ist. Somit kann man in dem Editor gar nicht richtig arbeiten.

Schreibt man in dem normalen Eingabefeld das JSON-Element, dann kommt es während der Eingabe zu einem Fehler (was ja richtig ist, man ist ja noch am Schreiben). Manchmal öffnet sich dann der Editor. Dort fehlen dann die gemachten Eingaben und es werden nur die geschweiften Klammern angezeigt. Recht nervig, da dann auch das, was man selbst geschrieben hat weg ist und man von vorne anfangen darf.

Gilt noch bei Version `2.2.0-beta-37`

**Comment by Ash2k80** [comment]
Kann ich (leider) bestätigen, sehr anstrengend wenn man etwas ändern will.

**Comment by Zefau** [comment]
sollte mit `v2.2.0-beta.38` behoben sein

**Comment by SWE1008** [comment]
Funktioniert wieder.
