### ISSUE TITLE
falsche Größe des Widgets

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#659]
_Originally posted by @SaschaWeiher in https://github.com/Zefau/ioBroker.jarvis/issues/650#issuecomment-776290712_

> Er skaliert die Inhalte aber nun anders.

> Als würde er den vorhandenen Platz nicht ausnutzen.

> ![image](https://user-images.githubusercontent.com/40891355/107437490-6231d500-6b2f-11eb-885d-08dc4cae3581.png)

> Ich konfiguriere Morgen nochmal etwas um, aber ich denke jetzt passt es an einer anderen Stellen nicht.

**Comment by Zefau** [comment]
@saschaweiher wie sind die Widgets konfiguriert?

**Comment by SaschaWeiher** [comment]
Hi Zefau,

wenn ich das Widget wie folgt konfiguriere, kommt es zum Scroll-Balken, obwohl genug Platz für den Inhalt vorhanden wäre.

![image](https://user-images.githubusercontent.com/40891355/107632483-d8852300-6c66-11eb-8fe8-f9a9516dff9c.png)

![image](https://user-images.githubusercontent.com/40891355/107632596-fd799600-6c66-11eb-8f87-5d5b1b515069.png)

Nehme ich nun Maximal-Höhe raus, sieht es wieder auf dem einen Tablet wieder gut aus, ein anderer Browser zeigt es dann wieder verschoben an, da keine standardisierte Maximal-Größe konfiguriert wurde.

![image](https://user-images.githubusercontent.com/40891355/107632762-387bc980-6c67-11eb-8d98-051328a88ea2.png)

Versuche ich es nun über "Skaliere Inhalte" abzufangen, schaut es wie folgt aus:

![image](https://user-images.githubusercontent.com/40891355/107633113-cc4d9580-6c67-11eb-871c-431f5ca5b769.png)

![image](https://user-images.githubusercontent.com/40891355/107633166-e4bdb000-6c67-11eb-856b-cf7b0cdc5289.png)

Der Text wird extrem kleiner skaliert, das Widget wird plötzlich auch kleiner.

Entweder ein Bug, oder ich habe die Min., Max. und Skalierung nicht verstanden. ;-)

Erhöhe ich die Maximal-Größe, wird es auf dem einen Device (Referenz) passend angezeigt und auf dem zweiten Device viel zu groß.

Aktuell komme ich damit klar, dass ich komplett auf Skalierung verzichte und die Maximal-Größe entfernt habe.

![image](https://user-images.githubusercontent.com/40891355/107633715-c4422580-6c68-11eb-8bd6-a51ebebd4380.png)

![image](https://user-images.githubusercontent.com/40891355/107633770-d4f29b80-6c68-11eb-9b3f-f044dde1824c.png)

Ich bin mir nicht ganz sicher, ob es ein Bug ist oder falsche Handhabe von mir.

**Comment by Zefau** [comment]
sollte mit `v2.2.0-beta.41` behoben sein.

**Comment by SaschaWeiher** [comment]
Hallo Zefau,

ich würde mal sagen Punktlandung. Meine Widgets skalieren nun wieder richtig. Vielen lieben Dank für die Anpassung.
