### ISSUE TITLE
Add unreach state

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#66]
Alias and HomeMatic / HomeMatic IP devices can have a boolean `UNREACH` state. Please add automatic support in form of an `unreach` state in jarvis as well.

**Comment by Zefau** [comment]
`UNREACH` is the state `.0.UNREACH` both in HomeMatic and HomeMatic IP?

**Comment by braindead1** [comment]
Correct.

**Comment by Zefau** [comment]
Added with `1.0.0-beta.22`.

**Comment by braindead1** [comment]
In `v1.0.0-beta.24` the state `lowBattery` is created for alias devices, but the pop-up needs improvement.

![image](https://user-images.githubusercontent.com/2136249/92647767-bb7bab00-f2e8-11ea-834b-4e4e821b5b79.png)

Besides that I noticed that all original states are missing in the device configuration. Is this by intention?

![image](https://user-images.githubusercontent.com/2136249/92647990-10b7bc80-f2e9-11ea-8214-fe89691f4344.png)

**Comment by Zefau** [comment]
Yes, removed the other states, because most of them are adapted now and they are very redundant.

**Comment by braindead1** [comment]
You should only remove states that are really transferred as otherwise the user has to manually create them. In the above screenshot you can see that e.g. `Büro Klimaanlage` has no states, although there should be states.

**Comment by Zefau** [comment]
added icon, label and style to `unreach` and `lowBattery` as well as `battery` (to be consistent ;-) ) with `1.0.0-beta.25`.

I will add the original states again with the next release tomorrow.

**Comment by braindead1** [comment]
In `v1.0.0-beta.25` the state `unreach` is fine now. The translation of `lowBattery` is not working. Besides that `nicht leer` is technically correct, but maybe something like `niedrig` and `voll` is better. What do you think?

![image](https://user-images.githubusercontent.com/2136249/92864322-3e8e2580-f3fd-11ea-9d51-31e947ea174a.png)

I also checked the English pop-up and you should adopt the display names of the states to `Unreach` and `Battery`.

![image](https://user-images.githubusercontent.com/2136249/92865039-25d23f80-f3fe-11ea-90e2-538baa95fdaa.png)

**Comment by Zefau** [comment]
I agree. I don't like `leer` and `nicht leer` either. `niedrig` is good, but `voll` would also apply to 30% battery. But I guess it is still better than `leer` / `nicht leer`.

**Comment by Zefau** [comment]
Resolved with `1.0.0-beta.26`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.26`

**Comment by Zefau** [comment]
81f79049f92dd894e769156d494d815f3590aa21
