### ISSUE TITLE
Browser back button (history back) not working as expected

### ISSUE THREAD

**Issue by SliX185** [Zefau/ioBroker.jarvis#661]
2.2.0-beta.22

Hi,
i just noticed, that "history back" in every browser don't work as expected.
If you change tabs, the URL is changing  like:
`.../jarvis/index.html#instance=0&socketHost=&socketPort=8082&tab=home-0`
to 
`.../jarvis/index.html#instance=0&socketHost=&socketPort=8082&tab=lights-1`
when now using the back button, the URL change back as expected, but the view won't change.

In addition, it would be great, if the back button will close open dialogboxes (modal windows).

**Comment by Zefau** [comment]
Could you please check this with v3?

**Comment by SliX185** [comment]
In v3 it is working as expected.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.80`
Browser back button auf dem Handy führt dazu, dass die Seite komplett neu geladen wird mit "connection"-Anzeige.
Er springt dann aber zum korrekten TAB-Fenster.
