### ISSUE TITLE
Log in / Authentication

### ISSUE THREAD

**Issue by orhan77971** [Zefau/ioBroker.jarvis#662]
Ein Feature für ein Log in wäre super, damit nicht jeder im Netzwerk auf das Vis Zugriff hat.

**Comment by Zefau** [comment]
@orhan77971 implemented with `v3.1.0-alpha.40`

**Comment by Zefau** [comment]
![image](https://user-images.githubusercontent.com/14368811/189452444-666c177d-5e55-46b3-94a9-07ecac70364a.png)
