### ISSUE TITLE
Kalender Widget aktualisiert nicht

### ISSUE THREAD

**Issue by SWE1008** [Zefau/ioBroker.jarvis#663]
Das Kalender Widget aktualisiert nicht. Ich habe als Intervall 5 min eingestellt. Es aktualisiert nur bei einem Refresh von Jarvis. Ich verwende die 2.2.0-Beta 39 und den Safari Browser am iPad.

**Comment by Zefau** [comment]
sollte mit `2.2.0-beta.40` behoben sein

**Comment by SWE1008** [comment]
Also das aktualisieren des Kalender funktioniert nun. Es gibt nun aber wieder ein Problem bei ganztägigen wiederkehrenden Terminen. Sie werden entweder gar nicht oder um 1 Monat versetzt angezeigt. 
Beispiel: Eine Person hat am 07.02. Geburtstag, ist als ganztägiger Termin eingetragen. Dieser Termin wird nun am 06.03. angezeigt. Eine andere Person hat am 10.04. Geburtstag und wird am 09.05. angezeigt.
Mein Testkalender ist auch noch geteilt, da werden die Termine auch nicht mehr angezeigt. Diesen kannst du gerne nochmal als Referenz her nehmen.
Soll ich hierfür nochmal ein Issue aufmachen?

**Comment by Zefau** [comment]
`2.2.0-beta.42` ?

**Comment by SWE1008** [comment]
Die Geburtstage passen wieder, die Termine aus dem Test Kalender werden nicht angezeigt.

**Comment by SWE1008** [comment]
Mir ist auch noch aufgefallen das um 0:00 Uhr das Kalender Widget zwar auf den nächsten Tag aktualisiert aber die markierten Tage (Vorschau) nicht weiter gehen.

**Comment by Zefau** [comment]
@SWE1008 bitte schau nochmal mit `v2.2.0-beta.43`.

**Comment by SWE1008** [comment]
Also irgendwie ist hier der Wurm drin. Die Termine werden in der Liste nun in der falschen Reihenfolge angezeigt. 
Generell werden neu angelegte ganztägige wiederkehrende Termine nun wieder ein Tag vorher angezeigt.
Der Rest passt denke ich soweit nun.

**Comment by Zefau** [comment]
@SWE1008 die Reihenfolge sollte in der aktuellsten beta korrekt sortiert sein.

Bzgl. der falsch angelegten wiederkehrenden Tage passt es bei mir bei meinem Kalender und auch einem Testkalender eines Users.
Lediglich Termine am 1. eines Monats scheinen noch inkorrekt, aber das meinst du nicht, oder?

Hast du ein Beispiel?

**Comment by Zefau** [comment]
Die Termine am 1. sollten nun ebenfalls behoben sein. Aus meiner Sicht sollte es nun passen.

**Comment by SWE1008** [comment]
Ja die Reihenfolge passt, danke.

Meine Beobachtungen zu den wiederkehrenden Terminen:
1. Wiederkehrende Termine, NICHT ganztägig, werden von Montag bis Samstag korrekt angezeigt. Sonntags werden keine angezeigt,
2. Wiederkehrende Termine, ganztägig, werden überhaupt nicht angezeigt.
Getestet mit der Beta46

**Comment by Zefau** [comment]
Hast du einen Beispiel-Kalender? Das mit Sonntag kann ich einfach prüfen bei mir. Das mit den ganztägigen Termine funktioniert bei mir aber. Welche Frequenz hast du eingestellt? Jährlich, monatlich und wöchentlich funktioniert bei mir.

**Comment by SWE1008** [comment]
Hier der Beispiel Kalender: webcal://p51-caldav.icloud.com/published/2/MTAxNDU1OTAzMjEwMTQ1NSZE_FhgifNEpz_kDKa31a90DTDVIutuEmvQQDZndWJR

**Comment by SWE1008** [comment]
Hier noch ein Screenshot:

![B1F553FA-491A-4836-AA32-54635457DDF9](https://user-images.githubusercontent.com/49527041/108594603-3c040480-737b-11eb-81af-fe52b77cfa70.jpeg)

**Comment by Zefau** [comment]
Auf den Link kann ich nicht zugreifen leider.

**Comment by SWE1008** [comment]
Versuche es bitte nochmal. Habe vergessen das „webcal“ in „https“ zu ändern

**Comment by Zefau** [comment]
probier nochmal bitte mit `v2.2.0-beta.48`.

**Comment by SWE1008** [comment]
Passt leider immer noch nicht. Die Sonntage werden jetzt angezeigt. Einige andere Termine werden jetzt wieder um 1 Tag verspätet angezeigt.
Hier nochmal ein Screenshot, links ist die HTML vom iCal Adapter. Da stimmen alle Termine:

![7604FC84-F523-4A9A-BF11-8EB9ABBB304A](https://user-images.githubusercontent.com/49527041/108624193-9ec0d300-7443-11eb-9c2d-4e512127ad0b.jpeg)

**Comment by itsme1893** [comment]
Hi, selbes Problem habe ich auch - einige Termine aus dem Geburtstagskalender werden um ein Tag nach hinten verschoben angezeigt (z.B. reales Datum: 23.04. - Anzeige: 24.04.). Das ist aber nur bei manchen Einträgen so, andere Einträge im selben Kalender werden korrekt angezeigt.

**Comment by Zefau** [comment]
Wo kommen die Geburtstage denn her? Sind die manuell eingetragen?

Könnt ihr mir da ein Beispiel-ical fertig machen bzw. @SWE1008 kannst du das in deinen oben einfügen bzw. ein nicht-funktionierendes Beispiel nachstellen?

**Comment by SWE1008** [comment]
Es handelt sich bei mir nicht speziell um Geburtstage. Ich kann leider auch kein Muster mehr erkennen bei welchen Terminen es stimmt und bei welchen nicht.

Ich habe in den Kalender oben jetzt mal ein paar Termine eingefügt:

1. Termin - "Test" 11 -12 Uhr sollte heute drin stehen --> steht für morgen drin (Einzelner Termin, nicht wiederkehrend)
2. Termin - "Zefau Test 2" 11 - 12 Uhr steht am Freitag 26.02. drin --> ist richtig (Einzelner Termin, nicht wiederkehrend)
3. Termin - "Zefau Test" 10 - 11 Uhr steht am Samstag 27.02. drin --> sollte auch am Freitag 26.02. drin stehen (Wiederkehrender Termin, wöchentlich)
4. Termin - "123456" ganztägig steht am 26.02. drin --> ist richtig (Wiederkehrender Termin, wöchentlich)
5. Termin - "Test123456789" 13 - 14 Uhr steht am Sonntag 27.02. drin --> ist richtig (Wiederkehrender Termin, wöchentlich)

Wie gesagt, ich kann leider kein Muster erkennen. Und im iCal Adapter werden alle Termine korrekt angezeigt...

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/586645

**Comment by Zefau** [comment]
please move to v3
