### ISSUE TITLE
URL Parameter springt nicht zum gewünschtem TAB

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#664]
Version 2.2.0 Beta 39

Bei Angabe der URL mit TAB Parameter im Browser springt jarvis nicht zu diesem gewünschtem TAB.
Z.B.:
index.html#tab=temperaturen-5

**Comment by Zefau** [comment]
Beim Laden der Seite funktioniert es bei mir bestens.

Wie genau ist dein Anwendungsfall, dass es nicht geht?

**Comment by Bernd9000** [comment]
Ein Beispiel:
jarvis im Browser öffnen, irgend ein TAB öffnen und URL aus Adressleiste in die Zwischenablage kopieren.
Jetzt irgend ein anderen TAB in jarvis per Mausklick auswählen.
In Adressleiste des Browsers die Adresse aus der Zwischenablage einfügen und Enter drücken
Ergebnis:
Es wird immer die letzte TAB Seite angezeigt, die neue URL mit TAB Parameter wird nicht akzeptiert.

Fehler hab ich sowohl bei Firefox als auch beim Edge Browser.

**Comment by Zefau** [comment]
in `2.2.0-beta.41` werden die Parameter nun mit `?` statt mit `#` abgetrennt. Nun sollte es bei einer Änderungen passen.

**Comment by Bernd9000** [comment]
Leider nein, auch mit Fragezeichen keine Änderung.
Ich kann nicht gezielt ein bestimmten TAB öffnen, egal ob im Browser oder als iFrame.
Es wird nach wie vor die zuletzt angezeigte jarvis Seite angezeigt, egal was als TAB Parameter angegeben wird.
Wo wird diese Information eigentlich gespeichert ?
Woher weiß jarvis welche TAB Seite ich zuletzt geöffnet habe? cookies ?

**Comment by Bernd9000** [comment]
Ich hab weiter getestet.....
Es ist jetzt so das man das # Zeichen benutzen muß um gezielt eine TAB Seite aufzurufen.
Das ? funktioniert nicht.
Und ganz wichtig ! Es darf keine jarvis Instanz laufen.
Wenn jarvis bereits läuft funktioniert es nicht.
Wenn das so beabsichtigt war kann dieses Issues geschlossen werden.
So kann ich meine Datenflaterate doch noch retten :-)

**Comment by Zefau** [comment]
`2.2.0-beta.42` ?

**Comment by Bernd9000** [comment]
Ja, jetzt funktioniert es auch mit dem "?" als Parameter-Trenner.
Es gibt allerdings ein Anzeige Problem in der Adressleiste im Browser.
jarvis verarbeitet intern noch das "#" Zeichen und mischt dieses sogar in der Adressleiste im Browser.
Beispiel:
Ich öffne den Browser und tippe folgendes ein:
http://192.168.0.100:8082/jarvis/index.html?tab=garage-1
TAB Garage wird geöffnet.
Und wenn ich jetzt in der jarvis Oberfläche in der Tab Leiste mit der Maustaste z.B. das Tab "Kamera" klicke steht folgendes in der Adressleiste des Browsers:
http://192.168.0.100:8082/jarvis/index.html?tab=garage-1#tab=kamera-3
Also eine Mischung aus der Ursprüngliche URL mit der neuen Tab Adresse.

**Comment by Zefau** [comment]
Bitte schau nochmal mit `v2.2.0-beta.43`. Ich habe das Zeichen wieder auf `#` geändert. Sollte nun funktionieren.

**Comment by Bernd9000** [comment]
Im Browser funktioniert es jetzt mit "#", in der Adresszeile im Browser wird es auch richtig angezeigt.
Leider kann ich jarvis, um meine Datenflaterate zu schützen, nicht alleine laufen lassen sondern muß es in einer übergeordneten Homepage als iFrame einbinden.
In einem iFrame funktioniert das "#" Zeichen als Trenner nicht.
Hier muß man jetzt das "?" benutzen.

**Comment by Zefau** [comment]
Es geht nur eins von beiden und `?` dürfte gar nicht mehr funktionieren.

Was genau machst du denn in der übergeordneten Seite?

**Comment by Bernd9000** [comment]
Es funktioniert aber auch mit "?". 
Ich weiß nicht wie Du im Code die Parameter herausfilterst aber vielleicht liegts an den Browsern selbst, die ja das Fragezeichen als Standart Trennzeichen zwischen Adresse und Parameter akzeptieren.

In der übergeordneten Webseite trenne ich jarvis von den Blue Iris Videostreams.
Ich wußte am Anfang nicht das  jarvis **alle** eingebundene iFrames in den verschiedenen TAB's sofort beim Aufruf startet.
Da ich 12 Videostreams in verschiedenen TAB's eingebunden habe war meine Mobil Flaterate schnell aufgebraucht.
Außerdem gibt es in zusammenhang mit Firefox Probleme wenn bestimmte Videostream zur gleichen Zeit laufen.
Und bei einer nicht so guten Mobil Verbindung wurde der Seitenaufruf immer schlechter oder gar nicht möglich.
Daher bin ich gerade dabei alle Kameras aus jarvis zu entfernen und verwende jetzt jarvis nur für Schaltvorgänge.
Die Videostreams laufen in der übergeordneten Webseite nur dann wenn ich Sie aufrufe.
Daher auch der Wunsch nach diesem "future":
issue: https://github.com/Zefau/ioBroker.jarvis/issues/660

**Comment by Zefau** [comment]
Ok, verstehe. Wie änderst du denn aus der übergeordneten Instanz heraus das iFrame bzw. das iFrame URL?

**Comment by Bernd9000** [comment]
Aus Bequemlichkeit benutze ich natürlich ein Website Editor.
Aufgerufen wird dann, wie üblich bei externen Inhalten, die gewünschte TAB Seite von jarvis so:

<iframe name="IFrame1" frameBorder="0" src="http://192.168.0.100:8082/jarvis/index.html?tab=haussteuerung-0" scrolling="auto" id="iframe_348eafcd"></iframe>

**Comment by Zefau** [comment]
Und wie änderst du den Tab dann dynamisch? Also ist das Issue behoben?

**Comment by Bernd9000** [comment]
Da ist nichts dynamisches, fest hinterlegte Links in der Menüleiste die die gewünschten Seiten aufrufen.
Issue ist behoben und kann geschlossen werden.
