### ISSUE TITLE
iPad Anzeige Spalten werden zusammen gestaucht

### ISSUE THREAD

**Issue by Schaxxe** [Zefau/ioBroker.jarvis#665]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [2.0.0, aber auch schon aktuellste Beta versucht *36 ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]
 Ich will Jarvis auf zwei iPads nutzen (iPad Air 2, ipad Air 4, jeweils im Querformat mit Safari bzw. der ioBroker App, testweise auch mit Firefox ausprobiert). Die Browser Caches wurden gelöscht, am PC kann man es nachvollziehen, wenn man das Browserfenster auf die iPad Größe verkleinert
Auf dem PC sieht alles super aus:
Startseite mit drei Spalten, Wetter-Tab (eine Spalte) über die ganze Breite, meine Wegstrecke ins Büro (eigener Tab, ein iFrame) ebenfalls über die ganze Breite.
Auf dem iPad ist die Startseite auf 3 Spalten, das Wetter Widghet und das Maps-iFrame werden aber angezeigt, als ob drei Spalten vorhanden wären, es ist also 2/3 des Bildschirms leer.
Mache ich das Wetter Tab auf Vollbild, passt es, allerdings kann ich im Darkmode dann kaum noch was lesen

Ideal wäre es, wenn man je Tab die Spalten angeben könnte, nicht nur global, so wäre ich variabler und verliere nicht so viel Platz. Die Höhe und Breite der iFrames habe ich auch schon nach % und fix in px angegeben, hat alles nicht interessiert.

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
siehe https://zefau.gitbook.io/jarvis-de/sonstiges/faq#falsche-darstellung-der-spalten-auf-dem-tablet bzw. https://github.com/Zefau/ioBroker.jarvis/issues/359

**Comment by Schaxxe** [comment]
Danke. Geht aber mit dem im Link beschriebenen Weg auch nicht
[https://ibb.co/3C2jkTD](url)

Meine ausführliche Beschreibung ist hier, genauso ein Lösungsansatz für die iFrames, jedoch leider nicht für das Wetter Widget
https://forum.iobroker.net/topic/30668/jarvis-v2-1-0-just-another-remarkable-vis/3588

**Comment by Zefau** [comment]
Ich verstehe das Problem nicht. Du stellst es global fest auf 3 Spalten ein und wunderst dich, dass 3 Spalten im Layout (auch für Wetter mit dann zwei Leerspalten) angezeigt wird?

Glaube wir sollten uns per Discord kurz abstimmen.

Nimm die globale Einstellung raus und stell es auf "auto". Dann passt sich jarvis an die im Layout angegebenen Spalten - je Tab - an. Also das, was du meinem Verständnis nach haben willst?

**Comment by Schaxxe** [comment]
Kann sein, dass ich das System "Jarvis" falsch verstehe.
Ich erstelle meine Views am PC (24" Monitor 1920x1080) und nicht am Tablet. Ich hatte grundsätzlich 3 Spalten für sämtliche Größen im Layout drin. Wenn ich den Wetter Tab öffne war die Anzeige schön über die gesamte Breite des Bildschirms sichtbar. Daher dachte ich, dann passts beim iPad auch. Ist aber nicht so. 
Wenn ich es einstelle wie du sagst ("auto" finde ich nicht, ich nehmen an du meinst "alle") dann sieht es aus wie hier: https://ibb.co/3C2jkTD
Also entweder bin ich zu doof für Jarvis, oder es gibt hier ein Problem das ausschließlich iOS Geräte betrifft.

**Comment by Zefau** [comment]
Kannst du mal auf 2.1 updaten oder 2.2. Ist es damit auch so?

**Comment by Schaxxe** [comment]
Ja, mit 2.1 ist es auch so. 2.2 finde ich nicht, nur die aktuellste Beta 46 (und mit den Betas hab ich das Problem, dass ich dann keine Icons mehr habe, nur noch Rechtecke)

**Comment by Zefau** [comment]
Habe gerade nochmal in die Github commits geschaut. Seit v2.2-beta.28 ist das behoben. Installier' die mal bitte die beta und lass uns dann das Problem mit den Icons separat beheben. Sonst auf einer Testinstanz?

Da wäre die Frage, ob du einen Fehler bzgl. der Icons in der Browser Konsole hast, wenn du auf v2.2 bist?
Mit v2.2 werden die Icons dynamisch (in kleinen Paketen) aus dem Internet nachgeladen. Mit v2.1 und davor ist alles in einem großen Paket enthalten.

**Comment by Schaxxe** [comment]
Wie installiere ich die konkrete Beta 28? Wenn ich über Git installiere habe ich immer die neueste Beta (44)  und über die erweiterte Ansicht im ioBroker kann ich max. bis 2.1.0 downgraden.
Muss dazu sagen, dass ich normalerweise alle Adapter im Stable nutze und keine Erfahrung habe Adapter hin und her up- und downzugraden.
Ich würde ein iOS Problem auch ausschließen, da man das Problem ja nachstellen kann, wenn ich das Browser Fenster am PC auf die iPad größe zusammen ziehe. Hast du das mal versucht oder gehts tatsächlich nur bei mir auf 4 Endgeräten nicht?

Fehler sehe ich keine im Log, seit gestern sind da nur die Quadrate in der Visualisierung.

**Comment by Schaxxe** [comment]
Ja

**Comment by Zefau** [comment]
Also dein Ziel ist auf dem iPad die Spalten so zu haben, wie du sie konfiguriert hast.
d.h. auf der Startseite 3 Spalten anzeigen von 3 Spalten, die auch konfiguriert sind.
Auf den anderen Seite eine Spalte anzeigen, wo auch nur eine Spalte konfiguriert ist.

Die Einstellungen hast du wie folgt vorgenommen:
![](https://forum.iobroker.net/assets/uploads/files/1612798794709-theme-einstellungen-3.jpg)

Mein Ergebnis (identische Einstellungen wie du + 3 Spalten Startseite):

![jarvisResponsibleColumns](https://user-images.githubusercontent.com/14368811/108594080-145f6d00-7378-11eb-8571-23a17edc8f9d.gif)

Leider ist das gif abgeschnitten, aber initial sieht man, dass bei kleinem Bildschirm eine Spalte sichtbar ist und beim größer ziehen dann (alle) 3 Spalten.

**Comment by Schaxxe** [comment]
Ja, das kann ich nachvollziehen. ABER: Nimm mal einen Tab bei dem du NUR das Wetter Widget hast. Dann hast du es erst über die ganze Breite, beim auseinanderziehen dann in einer Ansicht, als wären da noch zwei Spalten und irgendwann springt es wieder auf die ganze Breite. Die Auflösung meines iPads ist halt genau in dem Bereich, wo das Wetter Widget (oder andere Spalten) so angezeigt werden, als wären da noch zwei Spalten die es nicht gibt.
Ich glaube du verstehst mein Problem langsam. 
Mit den drei Spalten hatte ich erst Probleme, als du geschrieben hattest ich soll mal statt 3 auf "alle" im Layout gehen. Dann hab ich drei Spalten von ca 2cm breite.

**Comment by Zefau** [comment]
![jarvisResponsibleColumns2](https://user-images.githubusercontent.com/14368811/108896249-ef3b5a80-7614-11eb-87cf-f4683417ccdd.gif)

**Comment by Schaxxe** [comment]
![Jarvis](https://user-images.githubusercontent.com/77201278/109015482-717b5b80-76b5-11eb-89aa-20448ac4e414.gif)

**Comment by Zefau** [comment]
Was steht in der Browser Konsole für eine Version?

**Comment by Schaxxe** [comment]
![Screenshot 2021-02-24 163446](https://user-images.githubusercontent.com/77201278/109024631-3df0ff00-76be-11eb-97f9-6239849989a0.jpg)
Meinst Du das?
Oder die Version im ioBroker: 2.2.0-beta.46
"Browser Konsole" sagt mir erstmal nichts

**Comment by Zefau** [comment]
Ja, die Version. ioBroker ist aktuell, aber jarvis nicht. Die Version siehst du auch in der Browser Konsole über F12.

Restarte mal den Web-Adapter.

**Comment by Schaxxe** [comment]
Genial.
Nach dem Motto "Kaum macht mans richtig, schon funktionierts": Web Adapter neu gestartet, Icons da, iPad zeigt alles sauber an. Hätte das Problem längst von alleine gelöst, wenn mein ioBroker nicht schon seit Monaten laufen würde 
Ein großes Dankeschön!!!

**Comment by Zefau** [comment]
top :-) Hast du die Puffer Option im Web Adapter an?

**Comment by Schaxxe** [comment]
Ja hab ich

**Comment by Zefau** [comment]
besser rausnehmen
