### ISSUE TITLE
Sonnenauf- und Untergangszeiten werden nicht angezeigt....

### ISSUE THREAD

**Issue by stmiko** [Zefau/ioBroker.jarvis#666]
Sonnenauf- und Untergang wird trotz Aktivierung im Date/Time-Widget nicht angezeit.

getestete Version: 2.2.0 beta 42
Browser: -Safari iPad
. Chrome iPad

**Comment by Zefau** [comment]
Sind die Koordinaten im ioBroker gepflegt?

![image](https://user-images.githubusercontent.com/14368811/108111215-ade70000-7094-11eb-953a-4fefb9df9fe1.png)

**Comment by stmiko** [comment]
Land und Stadt sind eingetragen......Längen- und Breitengrad nicht!

**Comment by stmiko** [comment]
Ok, sorry.....nach eintragen der Werte funktioniert es.

Vielen Dank für Deine Arbei!!!
