### ISSUE TITLE
Einstellungs-Button ausblenden

### ISSUE THREAD

**Issue by voxid70** [Zefau/ioBroker.jarvis#669]
Ich denke es wäre gut den Einstellungsbutton ausblenden oder deaktivieren zu können, das Wie muss noch diskutiert werden. Evtl. über einen langen Press o.ä. Der Grund: es sollen keine versehentlichen Änderungen gemacht werden durch Gäste, Kinder etc.
Gruß
Carsten

**Comment by Zefau** [comment]
Duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/437 / https://github.com/Zefau/ioBroker.jarvis/issues/166 ?

**Comment by voxid70** [comment]
Same, same, but different. I don t think #166 (Password or PIN) is useable.

**Comment by GitBaer** [comment]
Kann ich nur unterstützen. Im Zweifel z.B. eine Liste mit Usernamen (durch Semikolon getrennt) in einen neuen Datenpunkt einpflegen, für welche der Einstellungs-Button dann nur angezeigt wird. 

Die Einstellungsmöglichkeiten selbst lassen sich zur Not auch über das ioBroker-Berechtigungssystem sperren.

**Comment by ChrisWoehrle** [comment]
> Ich denke es wäre gut den Einstellungsbutton ausblenden oder deaktivieren zu können, das Wie muss noch diskutiert werden. Evtl. über einen langen Press o.ä. Der Grund: es sollen keine versehentlichen Änderungen gemacht werden durch Gäste, Kinder etc.
> Gruß
> Carsten

Ja. oder durch 2 verschiedene Ansichtsvarianten: Admin und User

**Comment by Zefau** [comment]
Implemented through https://github.com/Zefau/ioBroker.jarvis/issues/437
