### ISSUE TITLE
Unterschiedliche Farben in Firefox und Chromium / Edge

### ISSUE THREAD

**Issue by DummerJunge** [Zefau/ioBroker.jarvis#671]
**Prerequisites / Voraussetzungen**
Jarvis 2.1.0

**Describe the bug / Beschreibe den Fehler**
Im Gerät bei Datenpunkt und Icon: `{">27":{"color":"red"},"<=27":{"color":"orange"},"<=24":{"color":"green"},"<=18":{"color":"LightBlue"},"<15":{"color":"Blue"},"<=5":{"color":"red"}}`

In Chromium / Edge wird dies unerwartet umgesetzt.

**Screenshots**

***Erwartete Ansicht in Firefox***
![Firefox](https://user-images.githubusercontent.com/7841822/108591176-a8750880-7367-11eb-8450-0e62df0d87bb.png)
****HTML****
![Firefox HTML](https://user-images.githubusercontent.com/7841822/108591231-ebcf7700-7367-11eb-9968-58d9878e7c5f.png)
****CSS****
![Firefox CSS](https://user-images.githubusercontent.com/7841822/108591235-f722a280-7367-11eb-86cc-8d0c895e2a9a.png)

***Unerwartete Ansicht in Chromium / Edge***
![Chromium](https://user-images.githubusercontent.com/7841822/108591280-3650f380-7368-11eb-9d35-deda3359a6fd.png)
****HTML****
![Chromium HTML](https://user-images.githubusercontent.com/7841822/108591294-4ff23b00-7368-11eb-8313-c4a91a82a294.png)
****CSS****
![Chromium CSS](https://user-images.githubusercontent.com/7841822/108591299-5e405700-7368-11eb-9325-d6063f1d24d5.png)

_Danke, Grüße_

**Comment by Zefau** [comment]
please upgrade to 2.2 (even though it is beta, but almost finished). should be fixed here

**Comment by DummerJunge** [comment]
Oh, da habe ich nicht dran gedacht, mit 2.2.0-beta.46 gelöst, Dank, Gruß
