### ISSUE TITLE
Alarm / Warnung Meldung

### ISSUE THREAD

**Issue by X-Renegade-X** [Zefau/ioBroker.jarvis#672]
Hi Zefau,

zuerst mal, ein echt angenehmer Adapter, was du da programmiert hast. Richtig fein.

Was mir noch fehlt, wäre eine Alarmmeldung / Warnung in form eines Popups oder eines Statussymbols, welches von jedem Tab aus zu sehen ist. Wenn z.B. eines der Smarthome Geräte nicht mehr erreichbar oder die Batterie leer ist. Oder auch, wenn ein Alarm einer Kamera, bzw. eines anderen Alarmkontakts anschlägt.
Ich will ja nicht ständig alle Kontakte manuell checken müssen, drum hab ich ein Script, welches mir die States alle überprüft und mir dann einen Datenpunkt setzt, aber diesen würde ich halt gerne von jeder view aus sehen können.

mfg
Rene

**Comment by Zefau** [comment]
via https://github.com/Zefau/ioBroker.jarvis/issues/56 ?

**Comment by Zefau** [comment]
@X-Renegade-X genügt dir das Notification Feature oder brauchst du hier etwas spezielles?
