### ISSUE TITLE
Verschwinden von Herz, Glocke und Einstellungsrad

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#677]
https://forum.iobroker.net/post/587514
> Mir ist aufgefallen, das es bei mir verschwindet, wenn die Ansichtsseite länger ist und rechts der Scrollbalken für die ganze Seite angezeigt wird. Scroll ich dann nach unten verschwindet das Trio und kommt nicht mehr zurück.

**Comment by mcuiobroker** [comment]
Nach dem Update auf v3 und wieder zurück auf v2.2.0 funktioniert es plötzlich wieder, bislang auch bei längeren Seiten bleiben die Button da.

**Comment by Zefau** [comment]
this has been changed with v3
