### ISSUE TITLE
Improve module JsonTable

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#679]
https://forum.iobroker.net/post/588155

- [x] function to format values
- [x] custom column titles
- [x] html within json

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/320#issuecomment-786454278

**Comment by Zefau** [comment]
JsonTable improved with v3 (including support for direct HTML) via ` v3.0.0-alpha.11`

**Comment by mcuiobroker** [comment]
Überschriften selbst festlegen: War das nicht schon mit title möglich? Funktioniert nicht mehr mit v3.0.0-alpha.46
`[{"label":"name","title":"Name"},{"label":"dateFormat"},{"label":"age"},{"label":"daysLeft"}]`
![image](https://user-images.githubusercontent.com/84818934/127989978-33824fe5-be06-46db-a10d-28ed173dffd2.png)

**Comment by Zefau** [comment]
`name` ist der unique identifier. Wie ist die Struktur des JSON? Versuch mal, dass `name` die Original-Bezeichner aufgreift. `label` ist dann dein individuelles Label.
Mit `visible: false` kannst du Spalten ausblenden.

**Comment by Zefau** [comment]
zur Orientierung: https://quasar.dev/vue-components/table#defining-the-columns

**Comment by mcuiobroker** [comment]
Struktur vom JSON kommt vom birthday-Adapter:
`[{"name":"TestUSer","birthYear":2000,"dateFormat":"16.02.","age":22,"daysLeft":21,"_nextBirthday":"2021-02-15T23:00:00.000Z"}]`

Der Eintrag wird nicht berücksichtigt:
`[{"name":"name","label":"Name"},{"label":"dateFormat"},{"label":"age"},{"label":"daysLeft"}]`

**Comment by mcuiobroker** [comment]
Wie kann ich denn records per Page auf "ALL" festlegen, ohne es immer auswählen zu müssen?

**Comment by Zefau** [comment]
Also funktioniert alles?

**Comment by mcuiobroker** [comment]
Bzgl der eigenen Labelvergabe in v3 ja. Es sollte aber die obere Zeile mit der Suche und den Columns ausblendbar sein als Option im Widget.

**Comment by Zefau** [comment]
`v3.0.0-alpha.53`

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/130279889-22f379b9-56a7-4084-9aff-07f3f7f87fad.png)
Überschriften passen noch nicht (DenseMode)
Sonst super. Danke.

**Comment by mcuiobroker** [comment]
Habe den letzten Punkt hier als einzelnen Issue angelegt. Sonst sind wir hier durch. Kannst diesen schließen.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1013
