### ISSUE TITLE
Unknown Error durch LightColorBody nach Update auf 2.1.0

### ISSUE THREAD

**Issue by malbreitenbach** [Zefau/ioBroker.jarvis#683]
**Prerequisites / Voraussetzungen**
- [ ] Version 2.1.0 (ARM / Raspberry Pi)
- [ ] Fehler 
![grafik](https://user-images.githubusercontent.com/38527505/109416691-15b81780-79c0-11eb-861d-4a6556431fe8.png)

**Describe the bug / Beschreibe den Fehler**
Nach dem Update von 2.0.0 auf 2.1.0 führt ein schon länger verwendeter LightColorBody zu einem "Unknown error". Sobald der entsprechende LightColorBody aus dem Design entfernt wurde, funktioniert wieder alles wie zuvor. Auch ein manuelles Update auf 2.2.0 hat das Problem nicht behoben.

**Screenshots**
Betreffender Tab (Außerhalb des Expertenmodus automatisch generiert):
```
{
	"title":"Licht",
	"icon":"lightbulb-multiple",
	"columns":
	[
		[
			{"moduleConfig":{},"devices":[{"type":"device","deviceId":"9e712680-89f0-43a8-9938-610b5987d7cd","label":"Helligkeit","bodyStateKey":"Brightness","bodyElement":"LevelBody","primaryStateKey":"on","showState":false,"actionElement":"SwitchAction"},{"type":"device","deviceId":"9e712680-89f0-43a8-9938-610b5987d7cd","bodyStateKey":"hex","bodyElement":"LightColorBody","primaryStateKey":"hex","showState":false,"actionElement":null,"label":"Farbe"}],"module":"StateList","title":"Esstisch","icon":"palette","id":"15d0626b-ecbd-4566-8fd0-e65bd2818d37","index":0},
			{"moduleConfig":{},"devices":[{"type":"device","deviceId":"d5a2917b-4962-45c9-b048-cb0f5c533f8d","label":"Helligkeit","bodyStateKey":"level","bodyElement":"LevelBody","showState":false,"primaryStateKey":"level"},{"type":"device","deviceId":"d5a2917b-4962-45c9-b048-cb0f5c533f8d","label":"Farbe","showState":false,"bodyElement":"LightColorBody"}],"module":"StateList","title":"Regal","icon":" led-strip-variant","id":"9d2a2ccf-4ce5-4943-968d-985fa9bce335","index":1} #<-- Führt zum Fehler
		]
	],
	"id":"dbfc66cf-f6a1-498a-85b9-a4efff9465dd",
	"index":1
}
```

____

PS: Super Projekt, hat mir schon sehr viel Freude bereitet!

**Comment by malbreitenbach** [comment]
Update: Hängt vermutlich damit zusammen, dass das dahinterliegende Gerät nur einen Datenpunkt als **Trigger** und nicht als **Anzeige** angelegt hatte. Vielleicht ließe sich das in einem zukünftigen Release abfangen oder eine konkrete Fehlermeldung generieren.

**Comment by Zefau** [comment]
bitte auf v3 gehen
