### ISSUE TITLE
Absturz beim scrollen

### ISSUE THREAD

**Issue by fragman89** [Zefau/ioBroker.jarvis#685]
- [ ] Version 2.2.0
- [ ] Fehler tritt beim scrollen nach unten auf aber auch nur wenn gescrollt wird unberührt passiert nichts
![Jarvuis](https://user-images.githubusercontent.com/37341567/109640244-7d04d180-7b50-11eb-96ea-42f41daef7ba.png)

PS: Danke für deine Leistung für das Projekt ist wirklich einer der besten Frontend die es derzeit gibt und wird stätig verbessert

**Comment by Zefau** [comment]
please move to v3
