### ISSUE TITLE
JsonTable Modul verursacht Jarvis Absturz

### ISSUE THREAD

**Issue by Nonixnarrez** [Zefau/ioBroker.jarvis#686]
- [ ] Jarvis 2.2.0
- [ ] Bei Verwendung des JsonTable Moduls mit validem Json Input aus DP und korrekter Formatierung wird ein Absturz verursacht  

Absturzmeldung - Screenshot:
![210301_JsonTable_Issue_03](https://user-images.githubusercontent.com/79873877/109694030-9d518200-7b8a-11eb-871b-4af739ea7a51.jpg)

Datenreihe - Tabellendaten (Json aus Datenpunkt):
`[
   {
      "active":true,
      "ip":"192.168.178.23",
      "name":"Rockrobo-Sauger",
      "mac":"7C:49:EB:XX:XX:XX"
   },
   {
      "active":true,
      "ip":"192.168.178.100",
      "name":"Sonoff-Gartenhaus",
      "mac":"2C:3A:E8:XX:XX:XX"
   },
   {
      "active":true,
      "ip":"192.168.178.101",
      "name":"Sonoff-Hauseingang",
      "mac":"DC:4F:22:XX:XX:XX"
   },
   {
      "active":true,
      "ip":"192.168.178.25",
      "name":"Teufel-3Sixty-Julia",
      "mac":"30:58:90:XX:XX:XX"
   },
   {
      "active":true,
      "ip":"192.168.178.250",
      "name":"XigmaNAS",
      "mac":"AC:1F:6B:XX:XX:XX"
   }
]
`

Formatierung - Spalten (Json Format):
`[{"label":"active","align":"left"},{"label":"ip","align":"left"},{"label":"name","align":"left"},{"label":"mac","align":"left"}]`

Feedback/Vermutung aus io.broker Forum (User @MCU):
"DP muss so aussehen. Ich denke ist noch ein Bug in jarvis. Boolean wird nicht erkannt."

Referenz:
https://forum.iobroker.net/post/591158

P.S.: Klasse Projekt - keep up the good work!

**Comment by MacGyverBeta** [comment]
Scheinbar liegt es nicht nur an nicht escape-ten Strings.
Ich habe folgendes (valides) JSON, nur mit Strings und bekomme ebenfalls den Fehler.
`[{
	"Hostname": "Gerät1",
	"IP-Address": "xxx.xxx.xxx.xx",
	"MAC-Address": "yy:yy:yy:yy:yy:yy",
	"Active": "1",
	"Type": "-"
}, {
	"Hostname": "Gerät2",
	"IP-Address": "xxx.xxx.xxx.xx",
	"MAC-Address": "yy:yy:yy:yy:yy:yy",
	"Active": "1",
	"Type": "-"
}]`

**Comment by mikekaldig** [comment]
Hey, ich bekomme auch Fehlermeldungen (Redscreen)

{"start":"2021-03-20T22:30:00.000Z"}
{"start":"2021-03-20T22:30:00Z","setting":{"type":"HEATING","power":"ON","temperature":{"celsius":21,"fahrenheit":69.8}}}

**Comment by Zefau** [comment]
please move to v3
