### ISSUE TITLE
Anzeigevariante meldet NaN 

### ISSUE THREAD

**Issue by mpl1337** [Zefau/ioBroker.jarvis#688]
Seit neustem bekomme ich NaN bei 0 und 100. Wenn der wert zwischen 1 und 99 liegt kommt das NaN nicht.

wenn ich "anzeigevariante: {"0":"Offen","100":"geschlossen"}" entferne bekomme ich 0 bzw 100. 

![objekte](https://user-images.githubusercontent.com/19016821/109843538-760eb980-7c4b-11eb-81b1-e23432acbebf.png)
![jarvis](https://user-images.githubusercontent.com/19016821/109843540-76a75000-7c4b-11eb-8239-7ffc93846391.png)
![gerät](https://user-images.githubusercontent.com/19016821/109843542-773fe680-7c4b-11eb-9db7-66c0b1683646.png)

**Comment by stephan1827** [comment]
Gibt es hierfür schon eine Lösung? Ich habe dasselbe Problem

**Comment by Zefau** [comment]
plesae move to v3

**Comment by RkcCorian** [comment]
@Zefau : Du hast dieses Issue geschlossen, allerdings habe ich das bei v3.0.0 alpha-61 ebenfalls. Ich vermute dass es ein Datentypproblem ist? Anzeige von Integer ist kein Problem, wie oben geschrieben, aber sobald es ein String ist, bspw. "Oben 0%". Daher solltest Du den Issue m.E. für v3 noch fixen.

**Comment by Zefau** [comment]
@RkcCorian bei mir geht es. Kannst du bitte die gesamte Konfiguration des Geräts teilen, die zu dem Fehler führt, damit ich es nachstellen kann?

**Comment by RkcCorian** [comment]
@Zefau : Anbei die Konfig, hoffe so ist es verständlich :-)

```
  "balkonrollladenrechts_d6d1c": {
    "name": "Balkonrollladen Rechts",
    "icon": "",
    "label": "",
    "function": "blind",
    "states": {
      "STATUS": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Rechts.STATUS",
        "icon": {
          "0": "account",
          "1": "lock-off-outline",
          "2": "tailwind",
          "3": "weather-sunset-down",
          "4": "shield-sun",
          "5": "human-greeting-proximity",
          "6": "weather-sunset-up"
        },
        "display": {
          "0": "Benutzer",
          "1": "Aussperrschutz",
          "2": "Lüften",
          "3": "Sonnenuntergang",
          "4": "Beschattung",
          "5": "Anwesenheitssimulation",
          "6": "Sonnenaufgang"
        },
        "label": "Betriebsmodus",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "STATUS"
      },
      "LEVEL": {
        "showState": false,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Rechts.LEVEL",
        "action": "alias.0.Wohnzimmer.Balkonrollladen_Rechts.BLIND_COMMAND",
        "actionElement": "BlindLevelAction",
        "icon": {
          "100": "window-shutter",
          "<100": "window-shutter-open"
        },
        "display": {
          "0": "Oben 0",
          "50": "Mitte 50",
          "100": "Unten 100"
        },
        "iconStyle": {
          "100": {
            "color": "#acacac"
          }
        },
        "label": "Level",
        "properties": {
          "max": 0,
          "min": 100
        },
        "bodyElement": "LevelBody",
        "stateKey": "LEVEL",
        "BlindLevelActionConfig": {
          "stopAction": "LEVEL",
          "activityState": "LEVEL"
        }
      },
      "AZIMUTH": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Rechts.AZIMUTH",
        "label": "Rollladenausrichtung",
        "icon": "axis-z-rotate-clockwise",
        "unit": "°",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "AZIMUTH"
      },
      "AZIMUTH_RANGE_SHIELD_SUN": {
        "showState": true,
        "state": "alias.0.Wohnzimmer.Balkonrollladen_Rechts.AZIMUTH_RANGE_SHIELD_SUN",
        "label": "Beschattungsbereich (+/-)",
        "icon": "angle-acute",
        "unit": "°",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "AZIMUTH_RANGE_SHIELD_SUN"
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Alias Devices",
        "namespace": "alias"
      },
      "_created": 1613171884976,
      "_updated": 1623909319658
    },
    "id": "balkonrollladenrechts_d6d1c"
  },
```

**Comment by Zefau** [comment]
Funktioniert bei mir ;-) Seltsam.

![BlindLevelAction](https://user-images.githubusercontent.com/14368811/131967161-9994ade8-9d34-455b-b58b-99614d155d61.gif)


Was für ein Datentyp ist denn der Datenpunkt `alias.0.Wohnzimmer.Balkonrollladen_Rechts.LEVEL` ?

**Comment by RkcCorian** [comment]
@Zefau : Im Folgenden meine Konfig des ALIAS. Einen Unterschied welchen ich sehe... Du hast "nur" einen String (offen/geschlossen). Bei mir steht Text+etwas was als String oder Zahl interpretiert werden kann ```{"0":"Oben 0","50":"Mitte 50","100":"Unten 100"}```. Würde mich zwar überraschen, aber wer weiß :-)

```
{
  "_id": "alias.0.Wohnzimmer.Balkonrollladen_Rechts.LEVEL",
  "common": {
    "name": "LEVEL",
    "role": "value.blind",
    "type": "number",
    "read": true,
    "write": false,
    "alias": {
      "id": "bshb.0.hdm:HomeMaticIP:3014F711A00018DA1859B678.ShutterControl.level",
      "read": "Math.round(((val * 100) * -1) + 100)",
      "write": "((Math.round(val) * -1) + 100) / 100"
    },
    "unit": "%",
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "retention": "31536000",
        "changesRelogInterval": "3600",
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    },
    "smartName": false
  },
  "native": {},
  "type": "state",
  "from": "system.adapter.admin.0",
  "user": "system.user.admin",
  "ts": 1613171495480,
  "acl": {
    "object": 1636,
    "state": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  }
}
```

**Comment by Zefau** [comment]
Was macht denn `alias.0.Wohnzimmer.Balkonrollladen_Rechts.BLIND_COMMAND` ? Das ist ja der Datenpunkt, der beschrieben wird bei einer Änderung.

**Comment by RkcCorian** [comment]
@Zefau : BLIND_COMMAND nimmt das Kommando entgegen. Mit Skript unterscheide ich ob 0-100 kommandiert wurde oder STOP. Wenn 0-100 mache ich weitere Tricks, wie Lüftungserkennung, Aussperrschutz, etc. Erst nach der Vorbearbeitung in meinem Skript schicke ich den daraus resultierenden finalen LEVEL an den Rollladen.

**Comment by Zefau** [comment]
Dann bin ich etwas ratlos.

![BlindLevelAction](https://user-images.githubusercontent.com/14368811/131977213-78e0490b-8833-426c-af47-aad143c60afc.gif)

**Comment by Zefau** [comment]
![BlindLevelAction2](https://user-images.githubusercontent.com/14368811/131977287-ec0c0d92-8c40-4a66-a28c-8af47e979749.gif)

**Comment by Zefau** [comment]
jetzt hab ich den Fehler auch. Ich hatte noch `{"0":"","100":"",">=1":"%","<=99":"%"}` bei der Einheit drin stehen.

**Comment by RkcCorian** [comment]
@Zefau Top! Wenn der Fehler reproduzierbar ist, ist auch der Fix nicht weit :-)

**Comment by stephan1827** [comment]
Gibt es irgendein Workaround das wir in der Version 2.2.3 verwenden können?

**Comment by Zefau** [comment]
Was spricht gegen v3?

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.63` behoben.

**Comment by RkcCorian** [comment]
@Zefau : Funktioniert, vielen Dank! :-)
![image](https://user-images.githubusercontent.com/79741077/132140389-9431c015-4b32-4376-835f-54a634a6ee9a.png)
