### ISSUE TITLE
Adapter wird nicht grün. Kalender/Wetter widget geht nicht

### ISSUE THREAD

**Issue by Feleye** [Zefau/ioBroker.jarvis#689]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] jarvis 2.2.0
- [ ] ![image](https://user-images.githubusercontent.com/79642186/110096143-eb8a9f00-7d9d-11eb-8963-7cee4738ad4d.png)

**Describe the bug / Beschreibe den Fehler**
Hallo,

vorweg: Spitzen Arbeit, danke!

Leider bekomme meinen jarvis adapter seit einem Neustart meines Systems nichtmehr auf grün =(
![image](https://user-images.githubusercontent.com/79642186/110096324-17a62000-7d9e-11eb-80c7-ecfa20994093.png)
Alle Funktionen funktionieren aber, außer das Kalender sowie das Wetter widget

**Screenshots**

![image](https://user-images.githubusercontent.com/79642186/110094753-75396d00-7d9c-11eb-9959-c7477cf9d335.png)

**Comment by Zefau** [comment]
please move to v3
