### ISSUE TITLE
No Label for secondary datapoints

### ISSUE THREAD

**Issue by Sev7eNup** [Zefau/ioBroker.jarvis#690]
Ich habe ein Widget erstellt, um mir die Spritpresie der Tankstellen meiner Umgebung anzeigen zu lassen. Im Haushalt fahren wir mit unterschiedlichen Brennstoffen, sodass ich mir für eine bestimmte Tankstelle alle Spritpreise anzeigen lassen möchte. Das klappt zwar, jedoch werden bei den sekundären Datenpunkten die Werte des definierten Gerätelabels nicht angezeigt. Lediglich beim primären Datenpunkt wird das Gerätelabel angezeigt. 

- Which jarvis version are you running / Welche Version von jarvis nutzt du?
Version 2.2.0

- Fehler / Screenshot 
![image](https://user-images.githubusercontent.com/79143581/110108872-fdc00980-7dac-11eb-8c1f-025481a32594.png)

![image](https://user-images.githubusercontent.com/79143581/110107070-bfc1e600-7daa-11eb-861c-4901868fab4d.png)
![image](https://user-images.githubusercontent.com/79143581/110107099-c9e3e480-7daa-11eb-8eb8-a2413e10f302.png)
![image](https://user-images.githubusercontent.com/79143581/110108381-6a86d400-7dac-11eb-9e8e-1d9e520e545b.png)

Es wäre schön, wenn bei den sekundären Datenpunkten ebenfalls die Labels angezeigt werden, sofern im Gerät definiert. Im konkreten Fall ist es mir nicht möglich die einzelnen Brennstoffe den Preisen aus den sekundären Datenpunkten zuzuordnen, da die Bezeichnung des Labels fehlt.

Herleitung: Mittels der API von Tankerkönig können die Tankstellendaten geholt werden. Anschließend habe ich in Jarvis ein Gerät namens "Tanken" angelegt welches die Spritpreise der drei Sorten (Diesel, Super, Benzin) für eine spezifische Tankstelle als einzelne Datenpunkte enthält. Darüber hinaus habe ich in dem Gerät noch den Namen der Tankstelle als einzelnen Datenpunkt hinzugefügt. Dann habe ich ein Widget (stateHorizontal) erstellt welches als primären Datenpunkt den Namen der Tankstelle beinhaltet. Das Widget hat 3 sekundäre Datenpunkte (Spritpreise). 

![image](https://user-images.githubusercontent.com/79143581/110107932-d4eb4480-7dab-11eb-8f50-c69fe3d126ad.png)

**Comment by mcuiobroker** [comment]
Ist mit Eintrag in Datenpunkt-Eigenschaft möglich:
`{"value":"val => 'Dark: ' + String(val)"}`
![image](https://user-images.githubusercontent.com/84818934/133191800-614b25e9-76d8-4a6e-b88f-d2c9c079615a.png)

**Comment by Zefau** [comment]
Labels können mit `v3.1.0-alpha.9` nun (de)aktiviert werden für Secondary States:

![image](https://user-images.githubusercontent.com/14368811/171282863-4c201158-6f08-4ea6-a793-2e2b0ca66213.png)

**Comment by koalamusala** [comment]
@Zefau 
Ich habe Jarvis v3.1.2 im Einsatz. Scheint dort nicht zu funktionieren. Siehe hier:

https://forum.iobroker.net/post/970487

**Comment by mcuiobroker** [comment]
Solange es nicht funktioniert kann man diese "Alternative" nutzen? siehe oben.

Ist mit Eintrag in Datenpunkt-Eigenschaft möglich:
`{"value":"val => 'Dark: ' + String(val)"}`
