### ISSUE TITLE
LastChangeBody letzte Aktualisierung fehlerhaft

### ISSUE THREAD

**Issue by testit2020** [Zefau/ioBroker.jarvis#693]
2.2.0 
Obwohl die letzte Aktualiserung ausgewählt wurde wird sie nicht berücksichtigt bei der Berechnung der distancetonow Zeit:
Im Gerät und auch im Layout so definiert.
Zeit: 17:41
![image](https://user-images.githubusercontent.com/68483974/110213938-88366500-7ea2-11eb-81e6-ffc28b4b2c6a.png)

![image](https://user-images.githubusercontent.com/68483974/110214070-27f3f300-7ea3-11eb-8b06-19f50d7552fb.png)

![image](https://user-images.githubusercontent.com/68483974/110214040-05fa7080-7ea3-11eb-999e-5a6b4e046984.png)

**Comment by Zefau** [comment]
please verify fix with v3

**Comment by mcuiobroker** [comment]
`v.3.0.0-alpha.67`
Funktioniert. (mcuiobroker=test2020)

**Comment by Zefau** [comment]
hast du zwei Accounts? :-)
