### ISSUE TITLE
Multiple Trigger

### ISSUE THREAD

**Issue by duczz** [Zefau/ioBroker.jarvis#695]
Wäre es möglich im Trigger unterschiedliche OIDs zu hinterlegen? (OID für true & anderen OID für false)

Beispiel. True = WakeOnLan OID, false = PowerOff TV OID

**Comment by reutli** [comment]
beinhaltet dieses "feature" dann auch, mir einer switch action mehrere Geräte zu schalten?
Das tag "Pro" verheisst wohl, dass wenn es kommt, nur für die Pro-Version?
Ist das feature bereits auf der roadmap?

**Comment by Zefau** [comment]
Bot test

**Comment by Zefau** [comment]
Bot test

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.34` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.34`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Wenn der Datenpunk Trigger nicht gesetzt ist kann man kein weiteren mit + wählen. Auf dem + erscheint ein Verbotszeichen.


![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/3098d9d4-8bd5-49ef-905b-213463347055)

Soll das so? Dann muss man ja immer erst den Datenpunkt Anzeige nochmal reinsetzen?
Wie steuert man dann, falls es mehrere Trigger gibt unterschiedlich an?
Bei z.B. `false` soll der eine DP auf 5 gesetzt werden und der andere mit 2, falls `true` dann der eine mit 7 und der andere mit 6.

**Comment by Zefau** [comment]
> Soll das so? Dann muss man ja immer erst den Datenpunkt Anzeige nochmal reinsetzen?

Ja, das soll so. Verhalten ist korrekt.

>  Wie steuert man dann, falls es mehrere Trigger gibt unterschiedlich an?

Geht aktuell nicht. An jeden Trigger wird derselbe Wert gesetzt. Ist die Frage, wie man das geschickt noch einbaut. Geht eigentlich nur in den Datenpunkt-Eigeschaften.

**Comment by mcuiobroker** [comment]
Vorschlag oder ab 0 beginnen
Unterschiedliche Beispiele, DPs können auch unterschiedliche Typen sein.
`{1} = 1. DP = AnzeigeDP`
`{2} = 2. DP`
usw.
`{"false":"{1}=1;{2}=2","true":"{1}=true;{2}='TEST'"}`

**Comment by Zefau** [comment]
Hab's jetzt do gemacht: in den Datenpunkt-Eigenschaften im Schlüssel `trigger` die laufende Nummer (also 2 für den zweiten Eintrag):

```
{
   "trigger":{
      "2":{
         "true":"an",
         "false":"aus"
      }
   }
}
``

**Comment by mcuiobroker** [comment]
Die Key's beziehen sich dann immer auf den Trigger "1" beziehungsweise Anzeige-DP-Wert val oder auf value, der durch andere Einstellungen in Datenpunkt-Eigenschaften gesetzt wird?

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.54` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.54`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Zefau** [comment]
@duczz Hast du all deine Issues geschlossen? Das hier ist mit v3.2 implementiert.
