### ISSUE TITLE
Fehler bei der Installation (beim Durchklicken der Einführung)

### ISSUE THREAD

**Issue by Thomas-Doc** [Zefau/ioBroker.jarvis#698]
Gerade bei der Erstinstallation passiert. Automatische Konfiguration angewählt. Dann die Einführung durchgeklickt, und dann kam der rote Schirm. 

iobroker unter Docker, auf Synology. 
 Adapter allesamt aktuell, keine sonstigen Probleme.
Jarvis 2.2.0 gerade installiert.
Besonderheit: Hab das Ganze über iobroker.pro im Fernzugriff gemacht. Vielleicht hierdurch ein Problem?
Browser: chrome

Infos zu meinem iobroker unter docker / synology:

Plattform: linux
Betriebssystem: linux
Die Architektur: x64
CPUs: 2
Geschwindigkeit: 2001 MHz
Modell: Intel(R) Celeron(R) CPU J3355 @ 2.00GHz
RAM: 7.6 GB
System-Betriebszeit: 25 T. 01:38:46
Node.js: v10.24.0
NPM: 6.14.11
Datenträgergröße: 14.0 TiB
Datenträger verfügbar: 12.5 TiB
Adapter-Anzahl: 334
Betriebszeit: 9 T. 03:05:32
Aktive Instanzen: 28

[jarvis_error.log](https://github.com/Zefau/ioBroker.jarvis/files/6117102/jarvis_error.log)

**Comment by Zefau** [comment]
please move to v3
