### ISSUE TITLE
Tab labels

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#7]
If a tab only consists of an icon and no label is given, there is also just an icon in the title row above. 

![tab](https://user-images.githubusercontent.com/2136249/76165351-a5810800-6156-11ea-882b-bc3292d6f5ad.png)

Instead of leaving out the label of tabs to just show an icon, please implement an option to show only the icon as tab and show icon and label in the title row.

As this is mainly interesting on small displays, another possibility would be to hide the label on small screens.

**Comment by Zefau** [comment]
Feature added in `v0.0.4`, please test & verify.
New option is added to wiki here: https://github.com/Zefau/ioBroker.jarvis/wiki/Einstellungen#verf%C3%BCgbare-einstellungen

**Comment by braindead1** [comment]
In v0.0.4 this is working as described in the wiki.
