### ISSUE TITLE
add new module Calendar

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#70]
Add a widget to show calendar entries including different views, e.g. agenda, ~~weekly~~, monthly, ~~yearly~~
- [x] optimize mobile view

USES CASES / SOURCES
- [x] iCal Adapter
- [x] ~~Trash Schedule Adapter~~ (Trash Schedule Adapter links to ical itself, thus not required)

CONFIGURATION
- [x] Icon per Calendar
- [x] days looking back
- [x] days looking ahead
- [x] ~~week start~~

**Comment by Machinimo** [comment]
Hi Zefau, 
I would really appreciate if you could implement a popup window to show all calendar entries for the selected day (similar to Weather or StateList widget). I don't know if it's possible but in my opinion the grid and list layout would break the UI experience  a bit. All other widgets have almost a popup behavior. What do you think?

**Comment by Zefau** [comment]
Thanks for your suggestion. Please check out `v1.1.0-beta.75`. This finalizes the Calendar Module from my perspective and introduces a popup functionality as well.

**Comment by Machinimo** [comment]
Good job, works as exptected. 

But it seems the calendar entries are greyed out in the popup which are within the current week. Entries of the succeeding weeks have a normal black font color. Can you verify this?

One more note besides the popup functionality: When I initially load the dashboard, the last 5 days (from today) have a blue background color. When I click on any calendar entry, the background color disappears. I assume that's not intended, is it?

Is this new that the current day is also marked with a blue background color?

**Comment by Zefau** [comment]
Events in the past are greyed out. Do I understand correctly, that this is not working correctly for you? For the current week you should have both greyed out in case the event is in the past or not greyed out if it is upcoming.

Light blue marked days are part of the review / preview of events. When the calendar initially loads, this includes the days looking back / forward (defined in the configuration). When you click a day, events are only shown for that day (no looking back / forward).
Dark blue marked is today.

Sounds all correctly to me, but probably not intuitive enough?

**Comment by Machinimo** [comment]
Ah, I did not realize in my calendar that the entries from today are in the past. Then it's all fine.

I just got it now. I thought the entries marked with light blue are randomly marked for some reason. These marked days are only a hint for the user to show him which are the recent/upcoming entries, right?

**Comment by Zefau** [comment]
> These marked days are only a hint for the user to show him which are the recent/upcoming entries, right?

You may configure this in the Widget configuration (past & upcoming days to show events of).

>  But when I click on any entry these marks disappear, apart from today. Is this intended?

Yes, because the selection changes from past / upcoming to focus the day that you've clicked.
