### ISSUE TITLE
Red Screen bzw. unendliche Ladezeiten

### ISSUE THREAD

**Issue by eule66** [Zefau/ioBroker.jarvis#701]
Hallo Zefau

ich möchte gern Jarvis nutzen bekomme aber ständig einen Red Screen oder unendliche Ladezeiten.
Ich habe die Version 2.1.0 auf einem Rock64 mit Armbian 21.02.03 Buster mit Linuxkernel 5.10.21 das ganze läuft über eine 120gb SSD 

Zum Hergang: ich habe iobroker komplett neu installiert, weil ich vorher dieselben Probleme mit Jarvis hatte.
Jarvis installiert, dann die Weboberfläche aufgerufen , wurde durch die Einrichtung geleitet, bin dann auf automatisch erstellen gegangen und habe dann eine Steckdose angelegt, habe das Maps Widget gelöscht und die Steckdose hinzugefügt. Habe gespeichert und anwenden gedrückt, hatte die richtige Ansicht und konnte die Steckdose auch schalten. Dann die nächste Steckdose hinzugefügt auf speichern und anwenden geklickt und da kam der red screen. Wenn ich jetzt Jarvis in der Weboberfläche aufrufe kommt der Ladekreis, unter Chrome baut sich keine Ansicht auf unter Firefox kommt ich soll eine Konfiguration erstellen.  will ich das machen, speichere ich ein gerät und dann steht das gleiche da bitte konfiguration erstellen.

anbei der Screenshot
![jarvis_Fehler_red_screen](https://user-images.githubusercontent.com/23139933/111026319-f40c5680-83e9-11eb-87ca-968b9ca31606.png)

Hallo ich nochmal

nachdem ich mit Microsoft Edge eine Konfiguration erstellen konnte, öffnete ich jarvis wieder über Chrome, das ging auch gleich sofort, dann 30 sek später erhielte ich folgende Meldung im Log 
`

jarvis.0 | 2021-03-15 13:58:06.251 | warn | (2737) Wiederverbinden..
-- | -- | -- | --
jarvis.0 | 2021-03-15 13:58:06.167 | warn | (2737) transport close
jarvis.0 | 2021-03-15 13:58:06.160 | warn | (2737) Wiederverbinden..
jarvis.0 | 2021-03-15 13:58:06.131 | warn | (2737) Wiederverbinden
jarvis.0 | 2021-03-15 13:57:23.220 | warn | (2737) Wiederverbinden..
jarvis.0 | 2021-03-15 13:57:23.148 | warn | (2737) transport close
jarvis.0 | 2021-03-15 13:57:23.141 | warn | (2737) Wiederverbinden..
jarvis.0 | 2021-03-15 13:57:23.115 | warn | (2737) Wiederverbinden
jarvis.0 | 2021-03-15 13:56:49.786 | info | (2737) Processed 7 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details: ["devices","states","processedDevices","addedDevices","ignoredDevices","di
jarvis.0 | 2021-03-15 13:56:38.200 | warn | (2737) Wiederverbinden..
jarvis.0 | 2021-03-15 13:56:38.196 | warn | (2737) Wiederverbinden..
jarvis.0 | 2021-03-15 13:56:38.191 | warn | (2737) ping timeout
jarvis.0 | 2021-03-15 13:56:38.117 | warn | (2737) Wiederverbinden
jarvis.0 | 2021-03-15 13:56:33.464 | warn | (2737) Wiederverbinden..
jarvis.0 | 2021-03-15 13:56:33.448 | warn | (2737) Wiederverbinden..
jarvis.0 | 2021-03-15 13:56:33.431 | warn | (2737) transport close
jarvis.0 | 2021-03-15 13:56:33.309 | warn | (2737) Wiederverbinden

`

Da stand dasselbe in der Konsole wie oben und nach einer Weile kam die normal Anzeige wieder,da habe ich F12 gedrückt und habe die Meldung mit angehangen

![Screenshot 2021-03-15 140954](https://user-images.githubusercontent.com/23139933/111158306-2a87d400-8598-11eb-9c08-820c53b1e9b3.png)

**Comment by Zefau** [comment]
please move to v3
