### ISSUE TITLE
JSON Tabelle - Sortierung nach Datum

### ISSUE THREAD

**Issue by eraxar** [Zefau/ioBroker.jarvis#702]
Jarvis 2.2.0

Die JSON Tabelle scheint das Datum nur anhand der Zahl des Tages zu sortieren anstatt Tag+Monat bzw. Monat+Tag. 
Im Screenshot müsste z.b. die Reihenfolge eigentlich: 13.3 , 7.3 , 6.3 , 28.2 usw. sein

![grafik](https://user-images.githubusercontent.com/29177516/111039032-32c30080-842c-11eb-9b29-3283cad57dc0.png)

**Comment by stony2k** [comment]
Gleiches Problem hier (Jarvis 2.2.0). Sieht bei mir genauso aus. Als Beispiel mal die Rohdaten aus dem Datenpunkt:

`[{"Datum":"14.3","Start":"15:45","Saugzeit":"37 min","Fläche":"33.87 m²","Error":0,"Ende":true},{"Datum":"12.3","Start":"22:11","Saugzeit":"0 min","Fläche":"0 m²","Error":0,"Ende":false},{"Datum":"12.3","Start":"08:36","Saugzeit":"22 min","Fläche":"23.84 m²","Error":0,"Ende":true},{"Datum":"10.3","Start":"07:12","Saugzeit":"41 min","Fläche":"38.22 m²","Error":0,"Ende":true},{"Datum":"8.3","Start":"07:49","Saugzeit":"43 min","Fläche":"38.59 m²","Error":0,"Ende":true},{"Datum":"5.3","Start":"07:24","Saugzeit":"43 min","Fläche":"38.09 m²","Error":0,"Ende":true},{"Datum":"28.2","Start":"14:56","Saugzeit":"40 min","Fläche":"36.17 m²","Error":0,"Ende":true},{"Datum":"27.2","Start":"15:20","Saugzeit":"14 min","Fläche":"13.21 m²","Error":0,"Ende":true},{"Datum":"27.2","Start":"15:09","Saugzeit":"8 min","Fläche":"4.97 m²","Error":0,"Ende":true},{"Datum":"23.2","Start":"07:27","Saugzeit":"41 min","Fläche":"37.92 m²","Error":0,"Ende":true},{"Datum":"18.2","Start":"07:23","Saugzeit":"41 min","Fläche":"37.38 m²","Error":0,"Ende":true},{"Datum":"17.2","Start":"13:36","Saugzeit":"15 min","Fläche":"14.69 m²","Error":0,"Ende":true},{"Datum":"15.2","Start":"07:13","Saugzeit":"39 min","Fläche":"36.23 m²","Error":0,"Ende":true},{"Datum":"13.2","Start":"17:52","Saugzeit":"37 min","Fläche":"35.27 m²","Error":0,"Ende":true},{"Datum":"12.2","Start":"10:42","Saugzeit":"29 min","Fläche":"23.74 m²","Error":0,"Ende":true},{"Datum":"10.2","Start":"07:31","Saugzeit":"40 min","Fläche":"36.4 m²","Error":0,"Ende":true},{"Datum":"8.2","Start":"06:45","Saugzeit":"37 min","Fläche":"35.43 m²","Error":0,"Ende":true},{"Datum":"5.2","Start":"07:18","Saugzeit":"42 min","Fläche":"36.77 m²","Error":0,"Ende":true},{"Datum":"2.2","Start":"20:17","Saugzeit":"0 min","Fläche":"0.12 m²","Error":0,"Ende":false},{"Datum":"2.2","Start":"20:13","Saugzeit":"0 min","Fläche":"0 m²","Error":0,"Ende":false}]0=`

**Comment by Zefau** [comment]
Fixed with v3

**Comment by mcuiobroker** [comment]
Wie kann man in v3 eine IP-Spalte sortieren:
![image](https://user-images.githubusercontent.com/84818934/131904993-10c3bbac-04b1-45e4-8e68-571b9fbf55b3.png)
Es ändert sich nichts, wenn ich umschalte.

**Comment by Zefau** [comment]
Das Backitup-Datum ist kein Datum. Ist auch nicht International und einfach kein gängiges Format. Das muss im Adapter angepasst werden.

Das mit der IP schaue ich mir nochmal an. Kannst du mir das JSON als Beispiel posten, damit ich es zum Test verwenden kann?

**Comment by mcuiobroker** [comment]
[json.txt](https://github.com/Zefau/ioBroker.jarvis/files/7101348/json.txt)

**Comment by mcuiobroker** [comment]
Datumformat 15.02. funktioniert nicht:
![v3-alpha61-Datumsformat sortieren jsontable funktioniert nicht](https://user-images.githubusercontent.com/84818934/131910868-70e49440-f273-4f48-8ad6-ea7560dcb404.gif)

**Comment by Zefau** [comment]
should be resolved with `3.0.0-alpha.70`.

**Comment by mcuiobroker** [comment]
Ja passt. Danke.
