### ISSUE TITLE
States in Layout Ansicht bei Bedarf / durch Bedingungen ausblenden

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#703]
Ich würde mir die Möglichkeit wünschen, z. B. bei einem Gerät nur die von mir eingestellten States sichtbar zu machen, wenn dieses z. B. eingeschaltet ist. Ich habe mal einen Screenshot als Beispiel angehangen.

![layout2](https://user-images.githubusercontent.com/16526471/111044276-cb1aae80-8447-11eb-9414-8df2e4004ac7.jpg)

**Comment by Zefau** [comment]
duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/283
