### ISSUE TITLE
Links als Aktion erstellen

### ISSUE THREAD

**Issue by Choleriker** [Zefau/ioBroker.jarvis#708]
Ich habe mit OwnTracks die Geo Koordinaten der Mobiltelefone gespeichert und wuerde diese gern cool anzeigen. Hiermit generiere ich einen link mit google maps, wo ich einfach die Geo Koordinaten anhänge und dann öffnet sich schön Google Maps.

Die Liste mit den Links habe ich aktuell in HTML programmiert, das sieht nicht so cool aus. Also anstatt einen Dialog zu öffnen bei Klick, wäre es cool, wenn man einfach einen Datenpunkt als HREF einhängen könnte.

**Comment by Zefau** [comment]
Meinst du auf der Karte im Map Module, wenn man dort auf einen Ort bzw. einen Benutzer klickt?

Oder bezogen auf StateList statt des Gerätes Popups?

**Comment by Zefau** [comment]
@Choleriker vielleicht kannst du ein Beispiel zeigen / screenshoten?
