### ISSUE TITLE
iPad Support

### ISSUE THREAD

**Issue by Merexor** [Zefau/ioBroker.jarvis#709]
Hallo,

Leider wird mir auf den iPad 3 die Jarvis Seite nicht angezeigt (weißer Bildschirm). An was könnte das liegen ?
Würde es gerne als Wandtablet nützen.

Liebe Grüße,
Markus

**Comment by Ash2k80** [comment]
Könnte mir vorstellen das es hiermit zu tun hat?!?

https://forum.iobroker.net/topic/29855/wichtig-updates-von-socketio-web-admin-latest-vorerst

**Comment by Ash2k80** [comment]
Schade das manche dann einfach nicht mehr reagieren 🙃

**Comment by Merexor** [comment]
Tut mir leid.. aber das wird wohl dir Lösung sein. Leid wird, aus welchen Grund auch immer, alle Geräte (meiner Meinung nach) die bis iOS 9 laufen .. keine VIS von ioBroker.

**Comment by Ash2k80** [comment]
Das hat mit veralteter Software zu tun, irgendwann kann man alte Software eben nur noch begrenzt supporten. Leider aber ist so. Und iOS 9 ist halt auch schon 5 bzw 6 Jahre alt.

**Comment by Merexor** [comment]
Ja das stimmt. Und ich auch klar, irgendwann muss auch mal ein Strich gezogen werden. Dachte nur das es bei "Webseiten" nicht so tragisch ist. Zudem wäre es halt eine schöne Lösung gewesen .. günstig, iOS ohne irgendwelche Service und ein edlere Optik mit Glas und Alu. Aber ist halt so.

**Comment by Merexor** [comment]
Dann schließ ich den Issue ? 
Wäre aber toll mal generell vielleicht eine Liste zu machen welche Tablet's für die Vis geeignet sind. Da findet man so gut wie nichts dazu.
