### ISSUE TITLE
Refresh button next to notification icon

### ISSUE THREAD

**Issue by Schiri** [Zefau/ioBroker.jarvis#712]
So I'm using an iPhone and opened my Jarvis instance in Safari and created a shortcut for my homescreen. When I use this "app"-button, I can use Jarvis in a very lovely fullscreen app-like way.

But after some time, the open webapp displays a lot of outdated data for sensors etc. and some triggers don't work anmore. I assume, the server closed the session.

Point is: fullscreen apps based on safari bookmarks don't display the browser buttons such as refresh and and pull to refresh doesn't work either. Only way to get an working "app" again is to kill the app via Task Manager and reload the website.

So I think a refresh button in the UI would be very nice.

**Comment by Schiri** [comment]
...while I'm thinking about it: would be cool if the refresh as well kills the caching :)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/775

**Comment by Zefau** [comment]
_Originally posted by @Zefau in https://github.com/Zefau/ioBroker.jarvis/issues/775#issuecomment-912082914_

> mit `v3.0.0-alpha.62` gibt es nun ein Pull-to-Refresh auf mobilen Geräten
