### ISSUE TITLE
Weather-Modul aktualisiert nicht 

### ISSUE THREAD

**Issue by voxid70** [Zefau/ioBroker.jarvis#713]
- Jarvis v2.2, Tablet Galaxy, Fully Browser 
Beim Weatherwidget fällt mir auf, dass die Tage erst durch aktualisieren des Browsers richtig dargestellt sind. Im Bild die korrekte Darstellung von heute. Vor der manuellen Aktualisierung  (7:00) war hier Heute, Morgen, Donnerstag,..

![Unbenannt](https://user-images.githubusercontent.com/76115848/112266606-875c4c00-8c74-11eb-93e7-e2a7e34748b7.png)

**Comment by gre000** [comment]
Hi, nicht nur das, die große Temperatur in der Mitte ist falsch (auch nach dem Aktualisieren)
![image](https://user-images.githubusercontent.com/53404825/112769168-e7aa0f80-901f-11eb-8a8f-2b3b6df849e3.png)

Es waren keine 7 Grad :-)

**Comment by Zefau** [comment]
fixed with v3
