### ISSUE TITLE
wiederkehrende Termine

### ISSUE THREAD

**Issue by OllyAusLippe** [Zefau/ioBroker.jarvis#714]
Hallo,
ich hab mich schon durch einige der Issues gewühlt - aber ich habe mit wiederkehrenden Terminen Probleme. Meine Kalender befinden sich in OwnCloud. Meine beiden Probleme:
1. Ganztägig wiederkehrende Termine werden einen Tag zu früh angezeigt
2. Wiederkehrende Termine mit Start-/End-Zeit werden gar nicht angezeigt.
Viele Grüße
 Andreas

**Comment by BasWeg** [comment]
Bei mir werden Wöchentliche Termine mit Start-/End-Zeit einen Tag später angezeigt. Quelle ist hier Nextcloud...
Viele Grüße
Bastian

**Comment by Zefau** [comment]
please move to v3
