### ISSUE TITLE
Chart: Anzeige vom Datenpunkt ohne Änderung wird nicht bis jetzigen Zeitpunkt gefüllt

### ISSUE THREAD

**Issue by stony2k** [Zefau/ioBroker.jarvis#716]
-> Jarvis 2.2.0

Wird der Datenpunkt, in meinem Beispiel Badezimmer oder auch Wohnzimmer, nicht aktualisiert wird für den Zeitraum der letzten Aktualisierung bis jetzt nichts angezeigt. Aber der Wert hat sich schlichtweg nicht verändert. Hier wäre es gut, wenn man zumindest eine gerade Linie einblendet, damit die Anzeige vernünftig aussieht.

![Screenshot 2021-04-04 232207](https://user-images.githubusercontent.com/16526471/113522022-c7d59700-959d-11eb-8599-844f1436b2a1.jpg)

Hier im Vergleich wie es mit Grafana aussieht (wie die Jarvis Darstellung der Graphen optisch viel angenehmer):

![Screenshot 2021-04-04 233031](https://user-images.githubusercontent.com/16526471/113522037-dc199400-959d-11eb-9a3f-ef38b5b6b286.jpg)

**Comment by Zefau** [comment]
Könntest du den Sachverhalt bei v3 prüfen?

**Comment by stony2k** [comment]
Ich hatte im ioBroker (als Workaround) eingestellt, dass auch gleiche Werte geloggt werden sollen. Diese Einstellung habe ich nun Rückgängig gemacht, damit nur geänderte Werte in der Datenbank gespeichert werden sollen. Habe Jarvis schonmal auf die Alpha 3 Build 78 geupdatet, muss allerdings nun Daten Sammeln um den Sachverhalt zu prüfen.

**Comment by Zefau** [comment]
konntest du schon etwas rausfinden?

**Comment by stony2k** [comment]
Habe schön Daten gesammelt nur um festzustellen, dass der ioBroker leider immer noch gleiche Temperaturwerte speichert, obwohl er nur Änderungen in die influxDB speichern soll. Ich muss da nochmal ran.
