### ISSUE TITLE
Blind level shown as null if level is 0

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#72]
I have a clean installation of `v1.0.0-beta.29`. This morning I noticed that the level of blinds is `null` after loading/refreshing jarvis in case the level is `0` in ioBroker.

![image](https://user-images.githubusercontent.com/2136249/92988938-8cc02900-f4d0-11ea-97a8-44c903622133.png)

**Comment by Zefau** [comment]
Should be resolved with `1.0.0-beta.30`.

**Comment by braindead1** [comment]
Fixed in `v1.0.0-beta.30`
