### ISSUE TITLE
Farbgestaltung geht nicht merh richtig

### ISSUE THREAD

**Issue by hgschiller** [Zefau/ioBroker.jarvis#722]
**Prerequisites / Voraussetzungen**
- [ 2.2.0 ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ? ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
In der Version 2.1.0 im Browser edge, konnte ich mit folgendem Eintrag die Farbe eines Datenpunktes verändern:
{"default":{"color":"#1976d2"},">26":{"color":"#ff0000"},">24":{"color":"#ffd426"},">20":{"color":"#00e30b"},">17":{"color":"#00e3e3"},">1":{"color":"#2600e6"}}
Dies scheint so jetzt nicht mehr zu funktionieren.  Auch das Umstellen der Json bringt keine Änderung.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/78852559/114392484-2354e580-9b99-11eb-9e74-721c1bbac1c7.png)

Hier sollte jetzt das erste Icon in Farbe #ffd426 dargestellt werden und beim zweiten Icon in Farbe #00e30b

**Comment by Zefau** [comment]
Bitte mit v3 probieren
