### ISSUE TITLE
Farbgestalltung der sekundären Datenpunkte an oder ausschalten im Layout

### ISSUE THREAD

**Issue by hgschiller** [Zefau/ioBroker.jarvis#723]
**Is your feature request related to a problem? Please describe.**
In der Version 2.2.0 werden die sekundären Datenpunkte jetzt auch farblich dargestellt, was ich super finde. Jetzt führt das leider dazu, das ich meine Datenpunkte teilweise doppelt anlegen muss, damit ich im Layout die Farbgestaltung an oder aus habe. Schöner wäre, wenn ich im Widget bei Layout angeben könnte, ob ich die sekundären Datenpunkte mit der Farbgestaltung angezeigt bekommen möchte oder nicht. Also einfach ein Schalter im entsprechenden Layout Eintrag:

![grafik](https://user-images.githubusercontent.com/78852559/114396247-a5470d80-9b9d-11eb-89ac-95f97b88bea4.png)

**Comment by Zefau** [comment]
Farben können mit `v3.1.0-alpha.9` nun (de)aktiviert werden für Secondary States:

![image](https://user-images.githubusercontent.com/14368811/171282863-4c201158-6f08-4ea6-a793-2e2b0ca66213.png)
