### ISSUE TITLE
Modul Chart auch für SQL-History

### ISSUE THREAD

**Issue by Harry423** [Zefau/ioBroker.jarvis#726]
Leider geht scheinbar das Modul "Charts" nur für den iobroker.history-Adapter.
Es wäre schön, wenn man auch Datenpunkte aus dem sql-Adapter verwenden könnte.
Ich benutze eigentlich nur den sql-Adapter, da sich die Daten der besser sicher lassen.

**Comment by Zefau** [comment]
Das geht bereits

**Comment by Harry423** [comment]
Ok, danke.
