### ISSUE TITLE
Sidebar notifications contain html tags

### ISSUE THREAD

**Issue by micbuh** [Zefau/ioBroker.jarvis#727]
on V2.2.0 Sidebar notifications contain html tags. A popup renders fine.
Tags to be stripped in sidebar.

![Screenshot_2021-04-18 jarvis](https://user-images.githubusercontent.com/9218614/115146393-a1f8c980-a056-11eb-9163-69ae540b7dc7.png)

**Comment by Zefau** [comment]
resolved in v3

**Comment by mcuiobroker** [comment]
Ja. Passt die HTML tags werden in der Sidebar nicht mehr angezeigt.
