### ISSUE TITLE
Habe Json Element mit Fritzbox Datenpunkt erstellt - 

### ISSUE THREAD

**Issue by itsolon** [Zefau/ioBroker.jarvis#729]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
- [ ] 2.20 Version
- [ ] 
**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**
![image](https://user-images.githubusercontent.com/10437947/115225691-a97ba980-a10e-11eb-8dc5-dec3f7e64366.png)

wie komme ich aus der Nummer wieder raus?
**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Backup wiederherstellen.

**Comment by Zefau** [comment]
Bitte mit v3 probieren
