### ISSUE TITLE
jarvis not reachable when ioBroker is run in VM

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#73]

**Comment by Zefau** [comment]
Resolved with `1.0.0-rc.3`.

**Comment by Zefau** [comment]
duplicated issue https://github.com/Zefau/ioBroker.jarvis/issues/74 (too much beer 🍺 )

**Comment by braindead1** [comment]
My ioBroker is running in a Proxmox VM. I have no issues as you most likely know. 😄
