### ISSUE TITLE
Spotify Player integration 

### ISSUE THREAD

**Issue by E-Stegemann** [Zefau/ioBroker.jarvis#730]
Guten Morgen, 

Ich bin auf der Suche nach einer Lösung, wie ich Spotify in meine Jarvis Oberfläche integrieren kann. Ich habe bereits das Media Control Widget integriert, doch bietet mir dieses aktuell nur die Möglichkeit der Steuerung, wenn Spotify bereits auf einem Gerät läuft. Was ich jedoch suche ist, die Möglichkeit Spotify als solches einzubinden und daraus das abspielen auf den verknüpften Geräten zu starten. Lässt sich das aktuell irgendwie realisieren? 

Danke und Gruß,
Eric

**Comment by Zefau** [comment]
Die v3 (ich meine auch die v2) bietet die Möglichkeit den Player auszuwählen. Meinst du das?
