### ISSUE TITLE
Kein Modul JSON-Table

### ISSUE THREAD

**Issue by Harry423** [Zefau/ioBroker.jarvis#732]
Hallo,

ist das Modul JSON-Table ein neues Feature? Ich habe Version 2.1.0 und bei mir wird das nicht angezeigt.
![Bildschirmfoto 2021-04-21 um 16 29 10](https://user-images.githubusercontent.com/73777886/115570993-dc649f80-a2be-11eb-9841-2a93cfd3c313.jpg)

**Comment by testit2020** [comment]
Du musst die Version 2.2.0 installieren.

**Comment by Harry423** [comment]
Danke
