### ISSUE TITLE
Mobile View - Swipe Mode

### ISSUE THREAD

**Issue by StefCGN** [Zefau/ioBroker.jarvis#734]
Hi,
thanks for the great enhancement of jarvis.

I would like to ask, if it would be possible, to add "swipe" to the page for switching between the tabs like it is in many apps on the phone.

Thanks!

**Comment by Zefau** [comment]
Will be added with v3

**Comment by Zefau** [comment]
same as https://github.com/Zefau/ioBroker.jarvis/issues/19
