### ISSUE TITLE
Connection issues when using socket.io as separated adapter (not socket via integrated web adapter)

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#74]
https://forum.iobroker.net/post/489382 bzw. https://forum.iobroker.net/post/489387

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/489382 bzw. https://forum.iobroker.net/post/489387

**Comment by Zefau** [comment]
Hopefully resolved with `v1.0.0-rc.4`.

**Comment by Zefau** [comment]
@briandead1 would you do me a favor and try this as well?

Install socket.io adapter and choose socket.io in the Web adapter settings (instead of integrated).

The jarvis link in the ioBroker dashboard should then contain a `socketPort=8084` and jarvis should be working normally.

**Comment by braindead1** [comment]
I installed `v1.0.0-rc.4`. socket.io `v3.0.13` was already installed. For me it's working as described. The jarvis link is `http://192.168.10.3:8082/jarvis/index.html#socketPort=8084&socketSecure=false`.

![image](https://user-images.githubusercontent.com/2136249/93375223-27659280-f858-11ea-8cdf-d5695f77d808.png)

![image](https://user-images.githubusercontent.com/2136249/93375284-3c422600-f858-11ea-883f-b21a2ca1b64a.png)

![image](https://user-images.githubusercontent.com/2136249/93375375-5c71e500-f858-11ea-82a9-7e59a1caa0e3.png)

**Comment by Zefau** [comment]
That was quick, thank you very much! Same config and result for me. Very weird it is not working for crunchip (https://forum.iobroker.net/post/489557).

The only difference I see is that he is running a VM.
