### ISSUE TITLE
Jarvis Crash ChunkLoadError: Loading chunk 0 failed

### ISSUE THREAD

**Issue by technicallife** [Zefau/ioBroker.jarvis#741]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? 2.2.0
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
![grafik](https://user-images.githubusercontent.com/6833257/116142363-1d531e80-a6da-11eb-8eac-9a7f3ba98eca.png)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Aufruf von Jarvis nicht möglich, siehe Screenshot

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![grafik](https://user-images.githubusercontent.com/6833257/116142105-cb11fd80-a6d9-11eb-9cb2-a42c0818c7ac.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by technicallife** [comment]
Habs jetzt mit 2.1.0 probiert, damit klappts wieder einwandfrei.

**Comment by Zefau** [comment]
please move to v3
