### ISSUE TITLE
Wert für Datenpunkt setzen

### ISSUE THREAD

**Issue by E-Stegemann** [Zefau/ioBroker.jarvis#743]
Servus, 

gibt es mit Jarvis die Möglichkeit auch Werte an einen Datenpunkt zu übergeben? 
Ich frage, weil ich für meinen Luftbefeuchter bspw. über die Visualisierung den Modus setzen möchte. Soll heißen, es gibt den Modus Auto/ Sleep/ Power. Jetzt möchte ich über ein Dropdown Menü direkt aus Jarvis heraus den Modus ändern können. Bspw. von Auto auf Sleep. Geht das aktuell? Wenn ja, wie? 

Danke und Gruß, 
Eric

**Comment by Zefau** [comment]
Das geht. Siehe Wiki
