### ISSUE TITLE
Module for custom HTML

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#75]
Please add a widget to show custom HTML stored in a state.

**Comment by Zefau** [comment]
Added with `v1.1.0-beta.1 `.

**Comment by braindead1** [comment]
I installes `v1.1.0-beta.1` and it's not working as expected. The HTML is shown as plain text.

![image](https://user-images.githubusercontent.com/2136249/93645188-cc709e80-fa03-11ea-8703-4ccf2bc7b3da.png)

![image](https://user-images.githubusercontent.com/2136249/93645224-d85c6080-fa03-11ea-8a8e-4ab4f136fb3b.png)

I want to include the picture of one of my IP cams, but instead of creating a specic widget for cams, I think it's better to have a HTML widget.

**Comment by Zefau** [comment]
I thought you meant a dedicated one, but you meant within StateList. For now there is a dedicated module.

**Comment by braindead1** [comment]
Sorry, that was a misunderstanding on my side. It's working as expected. For me there is no need to change it from widget to module. Although having the possibility to use custom HTML in a module might be good for other users., 

![image](https://user-images.githubusercontent.com/2136249/93663138-ca3f2c00-fa65-11ea-9ab4-310fae8bef61.png)

**Comment by Zefau** [comment]
I will add that divinity to the StateList module as well later today.

**Comment by Zefau** [comment]
Should be available now with `v1.0.0-beta.2`. Not sure though, if the contents are too big for the `StateList` module. It is actually intended for state values and not such contents. For me the content is a big scrambled.

**Comment by braindead1** [comment]
Sorry for my late reply. This is acutally working for me.
