### ISSUE TITLE
Object-ID in JSON-Formatierung

### ISSUE THREAD

**Issue by thstickel** [Zefau/ioBroker.jarvis#751]
Moin,

Es wäre schön, wenn man in der Formatierung durch JSON auch einen Datenpunkt aus dem broker verwenden könnte.

**In diesem Beispiel:** Einem Widget nicht eine festformatierte Farbe mitgeben sondern bereits die eingestellte Farbe über den Adapter. Also nicht `{"color":"#ffffff"}` sonder `"color":"hue-extended.0.lights.003-stehlampe.action.hex"`

![Bildschirmfoto 2021-05-10 um 14 16 22](https://user-images.githubusercontent.com/25841553/117658354-eaf5f680-b19a-11eb-835d-55f74b3be268.png)

Viele Grüße
Thorsten

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/158
