### ISSUE TITLE
iFrame Aktualisierung bei Tab Wechsel

### ISSUE THREAD

**Issue by Pla5ma** [Zefau/ioBroker.jarvis#753]
iFrame Aktualisierung der in einem Tab vorhandenen iFrames sollte bei einem TAB Wechsel erfolgen.

**Comment by Zefau** [comment]
implemented with v3

**Comment by mcuiobroker** [comment]
Passt hier am Besten hin: Wenn ich von einem TAB zum anderen  wechsle und dann zurück gehe.
![v3-alpha61-Umschalten TAB-iFrame Position ändert sich](https://user-images.githubusercontent.com/84818934/131919243-03a88787-2c6f-4fdf-832d-d2fa5f9d4bd3.gif)

**Comment by Zefau** [comment]
Ich schließe diesen Feature Request (da erfüllt und originärer Nutzen funktionell), da der aktuelle Bug nochmal dediziert unter https://github.com/Zefau/ioBroker.jarvis/issues/977 angelegt wurde
