### ISSUE TITLE
allow specific values for trigger action

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#757]
_Originally posted by @robert-ke in https://github.com/Zefau/ioBroker.jarvis/discussions/756#discussioncomment-741392_

> Eben getestet - ja, in der Tat geht der Button dann mit:
![image](https://user-images.githubusercontent.com/74955542/118356174-4138b000-b574-11eb-89e1-9e98d126f5d2.png)

> Krieg ich das trotzdem unter einen Hut?
Ich brauche die Möglichkeit, definierte Texte für ON Action und OFF Action in den Trigger-Datenpunkt zu schreiben. Meine Datenpunkte sind voneinander entkoppelt - heißt, ich habe einen Datenpunkt für die Anzeige der liefert den Status und muss in einen anderen einen Text für die Action reinschreiben - das geht dann zu einer SPS... in diesem Beispiel wäre das wie folgt:

> Switch Action auf Ein -> TVTerrasseStromEin
Switch Action auf Aus -> TVTerrasseStromAus

> beides muss in einen Trigger-Datenpunkt, ein Script schickt die Befehle an die SPS weiter....

**Comment by Zefau** [comment]
implemented with `v3.0.0-alpha.71` via `setOn` and `setOff` in the state properties (Datenpunkt Eigenschaften).

**Comment by mcuiobroker** [comment]
Kannst du da mal bitte ein Beispiel einstellen?

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/discussions/756#discussion-3366769

wenn "Datenpunkt (Anzeige)" und "Datenpunkt (Trigger)" unterschiedliche Datenpunkte ansprechen, dann ist es ggf. notwendig andere Werte zu schicken.

![image](https://user-images.githubusercontent.com/14368811/133160121-e9421d85-7a67-438f-aeed-fdd76337babb.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/133163176-1fe21d36-1f41-4642-9b9b-cf8089625ce7.png)

Es kommt nur true und false  im Trigger-DP. Ist irgendwo ein Fehler bei den Einstellungen?

**Comment by Zefau** [comment]
Flüchtigkeitsfehler. Schau nochmal mit `v3.0.0-alpha.76` bitte.

**Comment by mcuiobroker** [comment]
.76
Jetzt kann ich gar nicht schalten, bleibt auf "true".

**Comment by Zefau** [comment]
Wie hast du denn dein Gerät konfiguriert? Der State wird auch nicht verändert, sondern der Trigger.

**Comment by mcuiobroker** [comment]
Musste aufgrund der neuen Konvertierungstest, den DP neu anlegen:
![image](https://user-images.githubusercontent.com/84818934/133198634-760d45df-b482-4502-869c-2c9fb35537ce.png)

In dem State ist Switch-State und in dem Trigger der Text-State.

![image](https://user-images.githubusercontent.com/84818934/133198706-9115aec7-dbf4-46c1-8246-1278dd385822.png)

**Comment by Zefau** [comment]
Klappt also? :-)

**Comment by mcuiobroker** [comment]
Nein. Ich kann ihn nicht schalten.

**Comment by mcuiobroker** [comment]
![v3-alpha76 schaltet nicht um textDP](https://user-images.githubusercontent.com/84818934/133199777-c4a4cc86-5809-4955-b0ce-0ceed7a80760.gif)

**Comment by Zefau** [comment]
Der Switch ändert sich nicht, weil du kein `on` / `off` definiert hast. Sofern du in ioBroker den State dann mit dem Trigger verbunden hast slollte es gehen.

Also jarvis verändert durch das Schalten des Triggers den State nicht. Das muss in ioBroker erfolgen.

**Comment by robert-ke** [comment]
Ein Traum @Zefau  👍 
Ich habs eben auch getestet, es klappt perfekt! Jetzt ist es sauber entkoppelt. Ich kann beliebige Trigger Befehle absenden und sobald die Datenpunkte aktualisiert wurden, springt auch der Switch in die passende Stellung! TOP! Vielen Dank

**Comment by mcuiobroker** [comment]
@robert-ke Stellst du bitte ein funktionierendes Beispiel rein. (Geräteeinstellungen usw.) Ich komme da irgendwie nicht weiter. Danke.

**Comment by robert-ke** [comment]
@mcuiobroker, gern - hier das Gerät:
![image](https://user-images.githubusercontent.com/74955542/133229007-ad3912ee-9e6d-445b-a94d-961e31ad225a.png)

Zur Erklärung: Im Datenpunkt (Anzeige) steht bei mir true/false, was den tatsächlichen Zustand des Geräts liefert. Das läuft bei mir über ein eigenes Script, sprich, egal was im Jarvis geschalten wird, dieser Wert zeigt immer den aktuellen Zustand an.

Im Datenpunkt (Trigger) muss ich VortexBrunnenEin oder VortexBrunnenAus schreiben, damit meine Gebäudesteuerung loslegt - sprich, ich habe immer das gleiche Feld - ein Script dahinter nimmt den Befehl und schickt ihn an die übergeordnete Steuerung.

Im Layout habe ich dann ein das StateList Widget und das Gerät wie folgt übernommen:
![image](https://user-images.githubusercontent.com/74955542/133229480-3e9a28ff-1eed-4ab9-a4e2-892c5cd1843d.png)

**Comment by Hartmut-vonBerg** [comment]
@Zefau schöne Lösung. Ich habe ein ähnliches Problem mit der Rolladensteuerung. Mein Stop trigger akzeptier nur 2 Textwerte: STOPPED und MOVING. STOPPED kann gesetzt werden um den Rolladen anzuhalten. MOVING ist der Status, wenn der Rolladen sich bewegt. Die Stop Trigger aus der BlindLevelAction liefert allerdings immer nur true zurück. 
setON, setOff habe ich schon ausprobiert, funktioniert allerdings hier leider nicht.

**Comment by Zefau** [comment]
Also dein Stop-Trigger-Datenpunkt und dein Status-Datenpunkt sind ein-und-derselbe Datenpunkt, verstehe ich das so richtig?

In den Datenpunkt-Eigenschaften kannst du mittels `stop` definieren, welcher Wert geschickt wird, wenn im BlindLevelAction die Stop-Taste gedrückt wird. Im default ist das `true`.

Der Activity-Datenpunkt erwartet aber aktuell einen Boolean ( `true` oder `false`).
Das Verhalten kann ich aber anpassen und noch einen Eintrag `active` für die Datenpunkt-Eigenschaften aktiviert.

**Comment by Zefau** [comment]
schau nochmal mit `v.3.1.3-beta.0`, damit sollte es mittels `active` in den Datenpunkt-Eigenschaften einstellbar sein

**Comment by Hartmut-vonBerg** [comment]
super, danke. ich teste gerne kann aber die beta nicht installieren 
npm install iobroker.jarvis@3.1.3-beta.0 
=> npm ERR! code ETARGET
in ioBroker wird sie auch nicht als verfügbare version angezeigt.

**Comment by Zefau** [comment]
schau nochmal mit `v3.1.3-beta.1`, siehe "letzte Version von jarvis" https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v2/beispiele/allgemeines/installation#installation-ueber-katze-github

**Comment by Hartmut-vonBerg** [comment]
Vielen Dank. Update hat funktioniert. Stop button tut jetzt was er soll :-).

**Comment by mcuiobroker** [comment]
Stellst du bitte die Einstellungen hier ein, dann nehme ich das in die Doku. Am besten mit ioBroker DPs und Typ vom Rollladen. Danke.

**Comment by Hartmut-vonBerg** [comment]
Noch eine Anmerkung: Das setzten des "stop" commands hat gereicht um mein ursprüngliches Problem zu lösen. Das neue "active" ist mir noch unklar wie es gedacht ist.

**Comment by Hartmut-vonBerg** [comment]
ioBroker Adapter
<img width="305" alt="image" src="https://user-images.githubusercontent.com/117438565/210621544-a748417d-3182-4c90-bb84-38b1fc15b5c4.png">

Bosch-Smart-Home Licht/Rolladensteuerung II
<img width="657" alt="image" src="https://user-images.githubusercontent.com/117438565/210622029-d71a53fc-3b05-49e8-abf7-5317e2ec5630.png">

level akzeptiert werte zwischen 0 und 1 
operationState akzeptiert "STOPPED" als Trigger, um fahrenden Rolladen anzuhalten und zeigt "MOVING", wenn der Rolladen fährt.

Und hier die Konfiguration in Jarvis
<img width="989" alt="image" src="https://user-images.githubusercontent.com/117438565/210622519-b0fb87f8-0631-41ae-a0ba-63b9df0dab22.png">

stop DP -> operationState
<img width="963" alt="image" src="https://user-images.githubusercontent.com/117438565/210622668-a83e06eb-c298-4371-b5a8-5813ae2dc96f.png">

activity DP <- operationState
<img width="956" alt="image" src="https://user-images.githubusercontent.com/117438565/210622794-a0348926-d51a-499b-9195-246f70afd5e8.png">

level DP <-> level
<img width="956" alt="image" src="https://user-images.githubusercontent.com/117438565/210622900-8147cd16-57b0-46c8-98b2-09f3a76256a1.png">

LevelBody
<img width="498" alt="image" src="https://user-images.githubusercontent.com/117438565/210623100-c70cc5b8-7529-4784-9fc4-72619bde9899.png">

BlindLevelAction
<img width="502" alt="image" src="https://user-images.githubusercontent.com/117438565/210623319-93ef69d4-b5c5-4d4e-b6ab-6ebdfd359bd8.png">

und so sieht's dann in der UI aus:
<img width="412" alt="image" src="https://user-images.githubusercontent.com/117438565/210624067-05006336-a2c9-426e-8e22-2abe3385ffbf.png">

<img width="395" alt="image" src="https://user-images.githubusercontent.com/117438565/210624194-d6439074-a73f-499e-83b3-2c4d9ec00f75.png">

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis-v3/besonderheiten-v3/geraet/gewerk/rolllaeden-blind-v3/bosch-smart-home-bridge

**Comment by Hartmut-vonBerg** [comment]
@mcuiobroker cool, danke. Wenn ihr wollt, kann ich bei Gelegenheit noch ein paar andere Sachen dokumentieren (Lichtsteuerung mit Bewegungsmeldern, Heizkörpersteuerung mit Interation von Fensterkontakten, und was mir sonst noch so einfällt während ich das System erweitere.- hier ist aber nicht der richtige thread - wohin damit?

**Comment by mcuiobroker** [comment]
Immer her damit. Wenn möglich direkt mit der Stelle wo es hin soll. Danke.
https://github.com/mcuiobroker/docuJarvis/issues
