### ISSUE TITLE
Sekundäre DP - Einheit wird plötzlich mit Geräte Name ergänzt

### ISSUE THREAD

**Issue by testit2020** [Zefau/ioBroker.jarvis#760]
'v2.2.0'

![jarvis_fehler_nach_einheit_plötzlich](https://user-images.githubusercontent.com/68483974/118380891-d0ca7700-b5e5-11eb-8627-ed81ba2d12c0.gif)

Schwarz am Anfang ist der refresh (F5) Browser.

![image](https://user-images.githubusercontent.com/68483974/118380930-299a0f80-b5e6-11eb-97aa-521f127944c3.png)

Im Gerät ist nur die Einheit eingetragen:
![image](https://user-images.githubusercontent.com/68483974/118380949-551cfa00-b5e6-11eb-8b89-3fd22493f121.png)

**Comment by martinkoenig** [comment]
Habe ein ähnliches Problem, nur dass bei mir die Einheit ganz verschwindet und nur noch die nackte Zahl dasteht. 
Gleiches Verhalten mit Page reload, zuerst ist die Einheit da, doch nach dem ersten Update des Werts, ist die Einheit weg.

Hab leider keine Lösung dafür, wollte mich dem Problem nur anschließen. Ein Downgrade auf 2.1.0 bringt leider auch nix.

Anfangs passierte das nur mit einem Wert, nun habe ich das Problem bei glaub ich 8 verschiedenen Werten, überall verschwinden die Einheiten

**Comment by Zefau** [comment]
könntet ihr das bitte in v3 testen?

**Comment by mcuiobroker** [comment]
Gerätenamen und Einheiten-Probleme wie oben beschrieben, bei mir nicht mehr. Nur noch das offene "," Problem. #791
