### ISSUE TITLE
die Jarvis Instanz lässt sich nicht öffnen

### ISSUE THREAD

**Issue by maximinus333** [Zefau/ioBroker.jarvis#763]
Ich habe den aktuellen Adapter 2.2.0 installiert. er wird grün in der Übersicht aber nach dem Anklicken erscheinen kurz einige Rechtecke bevor diese Fehlermeldung kommt:

(https://user-images.githubusercontent.com/9280514/118712124-b203f480-b820-11eb-97c7-97e8a8901555.jpg)

Ich bin noch nicht so fit mit ioBroker und Linux so dass mir diese Meldungen nichts sagen.
Die Hardware ist ein Raspberry Pi4 mit SSD der ansonsten sehr zuverlässig läuft.
Ich habe einige Geräte in ioBroker angelegt und auch einige Skripte laufen. Jetzt geht es um die Auswahl der Visualisierung.
Diese Anfrage habe ich zuvor im allgemeinen Teil Visualisierung gepostet wurde aber darauf hingewiesen sie hier zu platzieren.
LG Gerhard

**Comment by Elwood75** [comment]
Hallo Zusammen,
ich habe leider das gleiche Problem. Bei mir läuft iobroker über den Docker auf einer Synology Diskstation. Meine Gerätschaften sind eingebunden und alles läuft wunderbar. Nach mehrstündigem Einlesen habe ich mich dann für jarvis als Tool für meine geplanten Visualisierungen entschieden. Also kurzerhand den Adapter installiert, dieser wird auch grün. Nach dem Klick auf Adapter-Webseite öffnen bekomme ich 2 Auswahlmöglichkeiten: 
web.0 und web.1
Beide führen nach einem Klick zu der roten Seite Fehlermeldung wie bei maximinius333:

TypeError: Cannot read property 'click' of null

Woran kann das liegen?
Für eine kurze Hilfestellung besten Dank im Voraus.

**Comment by mcuiobroker** [comment]
Soweit ich es verstehe habt Ihr beide übehaupt keine Daten in jarvis eintragen können? Versucht mal in die DPs die unter dem Link beschriebenen Daten einzugeben?
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/4048

**Comment by Zefau** [comment]
bitte auf v3 gehen
