### ISSUE TITLE
TypeError: J.sort is not a function

### ISSUE THREAD

**Issue by sir0drake** [Zefau/ioBroker.jarvis#764]
![image](https://user-images.githubusercontent.com/77205165/119395541-f46f7a80-bcd3-11eb-8230-5acf6d38f2d3.png)

V 2.2.0
added json table to widged
let json table content empty

brgds

**Comment by Zefau** [comment]
You may recover jarvis using a backup.

This bug will be fixed with v3, which will land as an alpha end of May and hopefully as beta in June.

**Comment by Zefau** [comment]
please move to v3
