### ISSUE TITLE
v3 open topics and issues

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#770]
- [x] ~~ButtonAction (pushButton)~~
- [x] Hilfetexte noch "mdi-plus" in der Device-Configuration
- [x] #872
- [x] statekey deletion also in widget
- [x] delete widget -> delete in layout
- [x] #873
- [x] allow to switch instance via change in URL
- [x] Drawer open when no tab bar

**HistoryGraph**
- [x] -> optionen + achsenwerte
- [x] -> Configuration

**MediaControl**
- [x] shuffle, repeat

**StateList** 
- [x] - label json
- [x] - style body

_____
- [x] Introduction Tour
_____

- [x] RESPONSIVE / BREAKPOINTS
- [x] GAPS
- [x] EDGES
- [x] Starttab (startpage) + return after timer

**Comment by mcuiobroker** [comment]
- [ ] Icons laden dauert sehr lange (10 Sekunden)
- [ ] Übersetzung im Menü rechts (Nach dem Laden englisch, obwohl Deutsch eingestellt ist) -> Configuration and Help und nicht Konfiguration und Hilfe

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/772

**Comment by Zefau** [comment]
@mcuiobroker 
>  HomeKitTile kann anscheinend nur ein Element verarbeiten?

Wie hast du da zwei Geräte rein bekommen? Zwischen den Module gewechselt?

**Comment by mcuiobroker** [comment]
Die zwei Geräte werden bei der Konvertierung auf v3 anscheinend da zugeordnet.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/discussions/769#discussioncomment-830763

**Comment by mcuiobroker** [comment]
- [ ] Galaxy Tab A (2016) meldet nur Connection delayed und Timeout

**Comment by MarkTyr** [comment]
Hallo,

bei mir leider auch der timeout. Egal welches Endgerät oder Browser.

- [ Inhalt jarvis.0.info.error
`{"criticality":"error","message":"Incorret DateTime parameter provided!"}`]

Wechsel von 2.2.0 auf 3.0.0-alpha.5

In Jarvis war auf jedem Tab oben rechts die aktuelle Uhrzeit dargestellt. DateTime kommt ingsgesamt 5x vor.

**Comment by mcuiobroker** [comment]
- [ ] Komisches Phänomen auf TEST:
Auf dem System war erst jarvis 2.2.0 wurde dann upgedatet auf v3. Danach mit restore von backitup wieder auf v2.2.0. Die Daten eingespielt aus Datei (nicht von backitup oder jarvis, da die Daten schon v3).
Jetzt ist also die installierte Version v2.2.0:
![image](https://user-images.githubusercontent.com/84818934/121419707-8af69980-c96c-11eb-9954-0f2fae4d4425.png)
Starte ich nun die Webseite erscheint v3.
![image](https://user-images.githubusercontent.com/84818934/121419801-a6fa3b00-c96c-11eb-8931-e59b438c586f.png)
![image](https://user-images.githubusercontent.com/84818934/121419838-b24d6680-c96c-11eb-845b-e047904632d0.png)

**Comment by Zefau** [comment]
@mcuiobroker danke für die zahlreichen Issue. Da es doch so viele sind, lass uns diese gerne (für die weiteren / zukünftigen) in ein Issue je Modul gruppieren.

**Comment by Zefau** [comment]
@MarkTyr hast du noch andere Fehler in der Browser Konsole via F12?

**Comment by mcuiobroker** [comment]
@Zefau Können wir gerne machen. Ich habe einfach erstmall alles aufgeschrieben, was mir aufgefallen ist. Legst du dann die entsprechenden Issues vorab an?

**Comment by Zefau** [comment]
Mach gerne eins auf, wenn noch keines für v3 offen ist (aktuell ist noch keins offen).

**Comment by Zefau** [comment]
>  Widget Height ist eine Prozentzahl und keine Pixel, dann sollte auch Prozent dahinter stehen als Einheit.

Ist in Pixel. Keine Prozentzahl. Wie kommst du auf Prozent?

**Comment by Zefau** [comment]
@mcuiobroker bitte auch (aufgrund der Masse) erstmal nur die Dringenden priorisieren. Also Bugs, aufgrund derer jarvis nicht funktioniert. Schönheitsfehler machen wir dann in der beta mit einem breiteren User-Publikum.

**Comment by mcuiobroker** [comment]
In einem neuen v3 Issue?

**Comment by Zefau** [comment]
Wollte eigentlich alles hier sammeln, aber es ist zu viel.

Lass es uns so wie gewohnt machen: Mach einfach für alles ein eigenes Issue auf.
Dann tagge ich den Meilenstein (v3.0 oder v3.1) je nach Priorität und auch ob Bug oder Feature Request.

Danke nochmal für deine Unterstützung!

**Comment by mcuiobroker** [comment]
Ok. Gerne, freue mich auf die neue Version. Danke für Deine schnelle Bearbeitung und die Bereitschaft für andere so ein Super-Tool zu schreiben. Da unterstützen andere und ich gerne.

**Comment by Zefau** [comment]
Gibt es außer `face-man` weitere Icons, die du nicht findest?

Ich suche den Fehler jetzt seit 2h und glaube, es liegt an Material Design Icons.

Ich finde das Icon in der Suche, aber nicht in der Liste unter https://pictogrammers.github.io/@mdi/font/5.9.55/. Dort findet sich nur `face`, welches genauso aussieht.

**Comment by mcuiobroker** [comment]
Ich gehe nach der Liste: https://iconify.design/icon-sets/
![image](https://user-images.githubusercontent.com/84818934/121752969-9a631780-cb11-11eb-94ba-c42371a387c2.png)

**Comment by Zefau** [comment]
Schau mal - wenn du Zeit hast - in der ` v3.0.0-alpha.5`, ob die oben in den Beiträgen abgehakten Punkte passen.

**Comment by mcuiobroker** [comment]
Ist v3.0.0-alpha.6
Bei der Statelist wäre eine Anzeige der Anzahl der eingtragenen Objekte in Layoutansicht zur Abschätzung besser:
-> kann keine Unterscheid feststellen
![image](https://user-images.githubusercontent.com/84818934/121756560-cdf66f80-cb1a-11eb-9d0d-e4d4b84239b6.png)
Sonst sieht es mit den Haken gut aus.

**Comment by mcuiobroker** [comment]
@Zefau Ich habe jetzt die wichtigsten Punkte einzeln als Bug eingetragen.

**Comment by Zefau** [comment]
@mcuiobroker danke dir soweit

Beim Wechsel auf alpha-6 bitte nochmal neu von v2 auf v3 konvertieren, siehe https://github.com/Zefau/ioBroker.jarvis/issues/781#issuecomment-860176717

**Comment by Zefau** [comment]
Icons sollten nun wieder normal funktionieren (`face-man`).

**Comment by Zefau** [comment]
NEU mit alpha-7
- (feat) Modul Charts: eigene Charts Datenpunkte (bar, pie und circle)
  ![image](https://user-images.githubusercontent.com/14368811/121801146-1c4c6100-cc36-11eb-95b8-ab90b771b478.png)

- (feat) Trennabstände zwischen Widgets konfigurierbar
  ![image](https://user-images.githubusercontent.com/14368811/121801193-633a5680-cc36-11eb-8a21-dadcec83bae5.png)

- (fix) Tabs ohne Labels Option funktioniert nun

**Comment by Zefau** [comment]
>  Bei der Statelist wäre eine Anzeige der Anzahl der eingtragenen Objekte in Layoutansicht zur Abschätzung besser:

Ist nun auch drin:
![image](https://user-images.githubusercontent.com/14368811/121801243-aa284c00-cc36-11eb-9cfa-b58f9e1899f6.png)

**Comment by Zefau** [comment]
>  Die Mindesthöhe von einem Fensterelement ist zu hoch? Bei einem Element im Fenster wirkt es verloren?

Die Mindesthöhe kannst du in den Einstellungen anpassen.

**Comment by Zefau** [comment]
>  Bei der Adapterliste sollte es einen Scrollbalken geben, falls die komplette Anzahl nicht passt.

Generell soll es keine Scroll-Balken geben (mit JSON Table als einzige Ausnahme bisher). Inhalte werden immer auf die Höhe skaliert.

**Comment by Zefau** [comment]
> Texte im Dark-Modus nicht zu erkennen:

Das liegt an deinen Stiles würde ich behaupten.

> Beim Verschieben der FensterElemente kommt man sehr schnell auf den delete Button, dort sollte es eine Abfrage geben, sonst kann es schnell passieren, das man save & exit klickt, und weg sind die Einstellungen.

Sicherheitsabfrage ist eingefügt.

**Comment by Zefau** [comment]
>  Icons im Widget JSONtable werden nicht angezeigt

Sollte nun ebenfalls passen.

**Comment by Zefau** [comment]
> JSONtable, man muss jedesmal das ausblenden der Spalten wiederholen, das sollte in den Einstellungen einmalig gemacht werden und dann als option im Chart verfügbar sein:

Das geht. Du musst die Spalte explizit in den Einstellungen angeben und dann die Option `visible: false`. Kannst du das mal probieren?

```
[{ "field": "???", "visible": false }]
```

**Comment by mcuiobroker** [comment]
[{ "field": "???", "visible": false }]
Funktioniert. Super.

**Comment by mcuiobroker** [comment]
Was leider ein bisschen nervt, ich bin da mal ganz offen: Jedesmal, wenn man eine Änderung macht aus einem TAB heraus. Springt er nach der Änderung immer wieder auf den Start-TAB. Ich wäre Dir sehr dankbar, wenn es möglich wäre, das er nach der Änderung wieder zum entsprechenden TAB springt. Vielen Dank.

**Comment by mcuiobroker** [comment]
>Generell soll es keine Scroll-Balken geben (mit JSON Table als einzige Ausnahme bisher). Inhalte werden immer auf die Höhe skaliert.
Man kann doch nicht jedesmal, wenn man neue Adapter installiert die Höhe vom Widget anpassen, damit es gut aussieht?

**Comment by mcuiobroker** [comment]
Mit v3.0.0-alpha.8 ist es wesentlich besser geworden:
![image](https://user-images.githubusercontent.com/84818934/121822237-4d607c00-cc9e-11eb-9d13-4c88e8732828.png)
Nur noch bei Leerem Text und 0-Werten 
![image](https://user-images.githubusercontent.com/84818934/121822281-91538100-cc9e-11eb-84ae-66f5659853ad.png)
![image](https://user-images.githubusercontent.com/84818934/121822307-b647f400-cc9e-11eb-8b83-0233dc24c8ec.png)
![image](https://user-images.githubusercontent.com/84818934/121822312-bf38c580-cc9e-11eb-9f48-33c2ff7eb428.png)

**Comment by mcuiobroker** [comment]
>Das liegt an deinen Styles würde ich behaupten.

Ich kann mit den Styles nicht Eingabe-Oberfläche beeinflussen? Das sind Elemente der Konfigurationsoberfläche:
![image](https://user-images.githubusercontent.com/84818934/121823394-56088080-cca5-11eb-9908-f1f9c31683b2.png)

**Comment by noffycws** [comment]
3.0.0-alpha9
Wenn man mehrere Seiten hat, aber auf der Seite nur eine Widget-Seite ist, dann wird der Drawer (drei Balken links) nicht mehr angezeigt und man hat keine Möglichkeit auf die anderen Seiten und Konfiguration etc. zuzugreifen.

**Comment by Zefau** [comment]
neue Optionen mit `v3.0.0-alpha.10`: 

![image](https://user-images.githubusercontent.com/14368811/122684332-17267d80-d205-11eb-8e35-7837b98a4142.png)

1. Tabbar entweder oben oder unten
2. DrawerMiniMode:
   ![image](https://user-images.githubusercontent.com/14368811/122684357-3a512d00-d205-11eb-96a8-0c26073adaac.png)

**Comment by Zefau** [comment]
> Man kann doch nicht jedesmal, wenn man neue Adapter installiert die Höhe vom Widget anpassen, damit es gut aussieht? Ausser du kannst die Höhe vom Widget automatisch anpassen. (Was sowieso sinnvoll wäre, gerade jetzt bei der Umstellung von v2.2.0 auf v3) Denn da werden viele User fragen, warum es nicht automatisch geht, oder?

Dann einfach die Skalierungsoption deaktivieren?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/122804236-eeb38780-d2c7-11eb-8af6-88435a355a9b.png)
Ja passt.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.13` behoben sein

**Comment by mcuiobroker** [comment]
Leider nein. Zeigt kurz x an und dreht dann dauerschleife, aber nur bei einigen:
![image](https://user-images.githubusercontent.com/84818934/123004468-eab16380-d3b4-11eb-8cf4-ded28ee7f71e.png)

**Comment by Pissbirne** [comment]
Bei mir ist in der  v3.0.0-alpha.13 der Layout Button in der Kofiguration ohne Funktion.
Der Link http://xxx.xxx.xxx.xxx:8082/jarvis/index.html#/configuration/layout wird aufgerufen, es passiert jedoch nichts.

**Comment by mcuiobroker** [comment]
Funktioniert bei mir:
![image](https://user-images.githubusercontent.com/84818934/123107473-df544b80-d439-11eb-9bbc-3d51c698a07e.png)
Versuch nochmal ein Upload, Browser-Daten löschen, ...

**Comment by Zefau** [comment]
@Pissbirne hast du einen Fehler in der Browser Konsole?

**Comment by Pissbirne** [comment]
> @Pissbirne hast du einen Fehler in der Browser Konsole?

Mir war die Geduld ausgegangen. Instanz gelöscht, Adapter gelöscht, 2.2 installiert, Backup zurück, v3.0.0-alpha.13  wieder drauf....geht.

Mir ist aber noch ein Fehler beim History Graph aufgefallen. Beim öffnen wird er angezeigt. Wechsel ich auf einen anderen Tab und dann wieder zurück ist er verschwunden. kommt erst nach F5 wieder.

**Comment by mcuiobroker** [comment]
Fehler mit History ist #783.

**Comment by Zefau** [comment]
@mcuiobroker
Prüf bitte nochmal 
- https://github.com/Zefau/ioBroker.jarvis/issues/770#issuecomment-855408270,
- https://github.com/Zefau/ioBroker.jarvis/issues/770#issuecomment-855452189 und
- https://github.com/Zefau/ioBroker.jarvis/issues/770#issuecomment-856123515

Die Punkte sollten alle so passen (bzw. ggf. habe ich ein neues Issue geöffnet).
Wenn nicht, dann je Bug gerne (wie gewohnt) ein neues Issue aufmachen. Danke dir.

**Comment by mcuiobroker** [comment]
Ja passt so und wenn ich noch was feststelle, mach ein Issue auf. Kannst du schließen.

**Comment by mcuiobroker** [comment]
Ich schreib mal hier rein:
Fehler in der Konsole (F12): v.3.0.0-alpha.15
`Failed to decode downloaded font: <URL>
index.html#/configuration/layout:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/configuration/layout:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/configuration/layout:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/configuration/layout:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
vue.esm.js:8110 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
Sa @ vue.esm.js:8110
vue.esm.js:8110 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
Sa @ vue.esm.js:8110
vue.esm.js:8110 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
Sa @ vue.esm.js:8110
vue.esm.js:8110 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
Sa @ vue.esm.js:8110
index.html#/configuration/devices:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/configuration/devices:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/configuration/devices:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/configuration/devices:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
colors.js:288 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
m @ colors.js:288
colors.js:288 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
m @ colors.js:288
colors.js:288 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
m @ colors.js:288
colors.js:288 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
m @ colors.js:288
index.html#/wohnen5:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/wohnen5:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/b%C3%BCro4:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/b%C3%BCro4:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
colors.js:288 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
m @ colors.js:288
colors.js:288 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
m @ colors.js:288
index.html#/b%C3%BCro4:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/b%C3%BCro4:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/b%C3%BCro4:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/b%C3%BCro4:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/b%C3%BCro4:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/b%C3%BCro4:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
28`


`OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/configuration/layout:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/configuration/layout:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/configuration/layout:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/configuration/layout:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
vue.esm.js:8110 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
Sa @ vue.esm.js:8110
vue.esm.js:8110 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
Sa @ vue.esm.js:8110
vue.esm.js:8110 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
Sa @ vue.esm.js:8110
vue.esm.js:8110 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
Sa @ vue.esm.js:8110
index.html#/configuration/devices:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/configuration/devices:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/configuration/devices:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/configuration/devices:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
colors.js:288 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
m @ colors.js:288
colors.js:288 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
m @ colors.js:288
colors.js:288 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
m @ colors.js:288
colors.js:288 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
m @ colors.js:288
index.html#/wohnen5:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/wohnen5:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/b%C3%BCro4:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/b%C3%BCro4:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
colors.js:288 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
m @ colors.js:288
colors.js:288 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
m @ colors.js:288
index.html#/b%C3%BCro4:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/b%C3%BCro4:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/b%C3%BCro4:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/b%C3%BCro4:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/b%C3%BCro4:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/b%C3%BCro4:1 `


Und Socket Fehler, da es aber Testsystem weiß ich nicht ob es jetzt an jarvis liegt?
`Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
Socket.js:62 Connected to http://192.168.178.70:8400.
Socket.js:191 MESSAGE TIMEOUT:  4a4b7602-75a6-432f-88db-771503214767 Object
(anonymous) @ Socket.js:191
Socket.js:106 Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
Socket.js:62 Connected to http://192.168.178.70:8400.
Socket.js:191 MESSAGE TIMEOUT:  27ab13d6-3f94-4716-a9eb-0d48930bc0c3 Object
(anonymous) @ Socket.js:191
Socket.js:106 Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
Socket.js:62 Connected to http://192.168.178.70:8400.
Socket.js:191 MESSAGE TIMEOUT:  ab0d0364-26d0-4433-9eca-7988541dd985 Object
(anonymous) @ Socket.js:191
Socket.js:106 Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
Socket.js:62 Connected to http://192.168.178.70:8400.
Socket.js:191 MESSAGE TIMEOUT:  20136856-0646-41f8-bfe7-cba3785bf91a Object
(anonymous) @ Socket.js:191
Socket.js:106 Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
Socket.js:62 Connected to http://192.168.178.70:8400.
Socket.js:191 MESSAGE TIMEOUT:  4fc10669-bf06-4b76-9510-06a00b1d8d6f Object
(anonymous) @ Socket.js:191
Socket.js:106 Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
Socket.js:62 Connected to http://192.168.178.70:8400.
Socket.js:191 MESSAGE TIMEOUT:  b2620f1c-3655-4179-bc34-c282b2921759 Object
(anonymous) @ Socket.js:191
Socket.js:106 Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
Socket.js:62 Connected to http://192.168.178.70:8400.
Socket.js:191 MESSAGE TIMEOUT:  71f5ceab-1d6c-495d-a3ec-4cfa2bf9b57c Object
(anonymous) @ Socket.js:191
Socket.js:106 Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
Socket.js:62 Connected to http://192.168.178.70:8400.
Socket.js:191 MESSAGE TIMEOUT:  fd0d534c-f86b-43ef-86db-c64bbe178419 Object`

**Comment by mcuiobroker** [comment]
Beispiel getadapterinfo:
`MESSAGE TIMEOUT:  e6a02d59-d426-4b40-9bec-a57c92bacafd {messageId: "e6a02d59-d426-4b40-9bec-a57c92bacafd", command: "getAdapterInstances", params: Array(1)}command: "getAdapterInstances"messageId: "e6a02d59-d426-4b40-9bec-a57c92bacafd"params: Array(1)0: undefinedlength: 1__proto__: Array(0)concat: ƒ concat()constructor: ƒ Array()copyWithin: ƒ copyWithin()entries: ƒ entries()every: ƒ every()fill: ƒ fill()filter: ƒ filter()find: ƒ find()findIndex: ƒ findIndex()flat: ƒ flat()flatMap: ƒ flatMap()forEach: ƒ forEach()includes: ƒ includes()indexOf: ƒ indexOf()join: ƒ join()keys: ƒ keys()lastIndexOf: ƒ lastIndexOf()length: 0map: ƒ map()pop: ƒ pop()push: ƒ push()reduce: ƒ reduce()reduceRight: ƒ reduceRight()reverse: ƒ reverse()shift: ƒ shift()slice: ƒ slice()some: ƒ some()sort: ƒ sort()splice: ƒ splice()toLocaleString: ƒ toLocaleString()toString: ƒ toString()unshift: ƒ unshift()values: ƒ values()Symbol(Symbol.iterator): ƒ values()Symbol(Symbol.unscopables): {copyWithin: true, entries: true, fill: true, find: true, findIndex: true, …}__proto__: Object__proto__: constructor: ƒ Object()hasOwnProperty: ƒ hasOwnProperty()isPrototypeOf: ƒ isPrototypeOf()propertyIsEnumerable: ƒ propertyIsEnumerable()toLocaleString: ƒ toLocaleString()toString: ƒ toString()valueOf: ƒ valueOf()__defineGetter__: ƒ __defineGetter__()__defineSetter__: ƒ __defineSetter__()__lookupGetter__: ƒ __lookupGetter__()__lookupSetter__: ƒ __lookupSetter__()get __proto__: ƒ __proto__()set __proto__: ƒ __proto__()`

**Comment by mcuiobroker** [comment]
Details zum Socket Fehler:
`Socket.js:106 Connection to http://192.168.178.70:8400 lost!
(anonymous) @ Socket.js:106
i.emit @ index.js:145
emitReserved @ typed-events.js:59
onclose @ socket.js:191
i.emit @ index.js:145
emitReserved @ typed-events.js:59
onclose @ manager.js:310
i.emit @ index.js:145
onClose @ socket.js:634
(anonymous) @ socket.js:220
i.emit @ index.js:145
onClose @ transport.js:115
onClose @ websocket.js:179
Socket.js:62 Connected to http://192.168.178.70:8400.`

**Comment by Zefau** [comment]
`v3.0.0-alpha.22`:
- Label nun abhängig des States konfigurierbar (`json`)
- Body Stil eingeführt, womit der gesamte Datenpunkt-Container gestyled werden kann

**Comment by mcuiobroker** [comment]
Kannst du mal bitte ein Beispiel geben, wie ich den Label in Abhängigkeit von einem anderen (nicht der DP) State ändern kann.
Ist der Body-Stil auch von fremden States beeinflussbar.

**Comment by Zefau** [comment]
Binding geht nicht.

**Comment by mcuiobroker** [comment]
Schade. Da warten schon viele drauf.

**Comment by mcuiobroker** [comment]
Mit `v3.0.0-alpha.23`kommt jetzt plötzlich in allen Modulen ein Trennstrich zwischen Überschrift und Modul
![image](https://user-images.githubusercontent.com/84818934/125211767-f9e74b00-e2a8-11eb-99b6-daff7a2ffed6.png)
Wenn das so sein soll, dann bitte als Option. Dort ohne Ternnstrich glaube ich gefällt einigen besser. Und wenn dann sollte der Typ auswählbar (-.-.-.-,  - - - - -,  . . . . .  ) .
