### ISSUE TITLE
Gerät hinzufügen

### ISSUE THREAD

**Issue by rudi-liebl** [Zefau/ioBroker.jarvis#771]
Bitte folgende Geräte hinzufügen:

Die unten autgeführten Geräte werden nicht korrekt in die jarvis importiert.
Bittte in die Geräteliste aufnehmen.
Ich habe auch eine Wetterstation virtuell angelegt mit Open Weathermap diese wird auch nicht übernommen.

HM-WDS100-C6-O = Wetterstation OpenWeathermap
HmIP-WTH-B = Wandthermostat
HmIP-FALMOT-C12 = Fußbodenheizungsaktor

Vielen Dank

**Comment by Zefau** [comment]
Bitte mit Screenshot der Objekt Struktur

**Comment by rudi-liebl** [comment]
![Bildschirmfoto vom 2021-06-05 12-18-48](https://user-images.githubusercontent.com/83752736/120888394-66ab5d80-c5f8-11eb-907d-f9cae58b5adc.png)

**Comment by rudi-liebl** [comment]
![Bildschirmfoto vom 2021-06-05 12-23-20](https://user-images.githubusercontent.com/83752736/120888498-df121e80-c5f8-11eb-9133-624860983683.png)

**Comment by Zefau** [comment]
Ich brauch einen Screenshot von den State die übernommen werden sollen. Schau mal in den anderen issues

**Comment by rudi-liebl** [comment]
Ich kann dies auch selbst eintragen. Kannst du mir Bitte sagen wo die Geräte eingefügt werden müssen.

Vielen Dank

**Comment by Zefau** [comment]
Dann einfach im forum nachfragen https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/4499

**Comment by rudi-liebl** [comment]
MIt dieser Beschreibung bin ich nicht klar gekommen.
Ich Bitte dich dies doch zuübernehmen.

![HmIP-WTH-B _Wandthermostat](https://user-images.githubusercontent.com/83752736/120889600-3666bd80-c5fe-11eb-93a5-5898b0e2ab1e.png)
![HM-WDS100-C6-O_OpenWeathermap](https://user-images.githubusercontent.com/83752736/120889601-36ff5400-c5fe-11eb-86c3-4b09107e491d.png)
Vielen Dank
