### ISSUE TITLE
v3 läuft nicht unter admin v5.0.26 

### ISSUE THREAD

**Issue by metzger304** [Zefau/ioBroker.jarvis#772]
Beim öffnen von Jarvis kommt immer die Meldung connection delayed. und dann timeout error. Mit Jarvis 2.2.0 hat es unter admin 5.0.26 geklappt.

**Comment by Zefau** [comment]
Ich selbst nutze v5, also es geht definitiv mit. Der Fehler liegt daran, dass jarvis nicht connecten kann. Rufst du mit Verbindungsparametern über das Dashboard auf?

**Comment by Zefau** [comment]
Hast du einen Fehler in der Browser Konsole?

**Comment by djalexz** [comment]
Nabend Zefau,

ich antworte mal auf deine Frage, da ich das gleiche Problem habe.
Hier das Log aus der Konsole:

`app.d85bba96.js:1 Using instance 0.
app.d85bba96.js:1 Connecting to http://192.168.0.9:8402 ..
vendor.b938c301.js:139 GET http://192.168.0.9:8402/jarvis-socket/?EIO=4&transport=polling&t=NdeCdCL net::ERR_EMPTY_RESPONSE
create @ vendor.b938c301.js:139
d @ vendor.b938c301.js:139
request @ vendor.b938c301.js:139
doPoll @ vendor.b938c301.js:139
poll @ vendor.b938c301.js:1
doOpen @ vendor.b938c301.js:1
open @ vendor.b938c301.js:1
open @ vendor.b938c301.js:139
c @ vendor.b938c301.js:139
t.exports @ vendor.b938c301.js:82
open @ vendor.b938c301.js:20
u @ vendor.b938c301.js:20
a @ vendor.b938c301.js:80
connect @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
connect @ app.d85bba96.js:1
discover @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
setTimeout (async)
created @ app.d85bba96.js:1
ie @ vendor.b938c301.js:14
Pn @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
s @ vendor.b938c301.js:14
an @ vendor.b938c301.js:14
init @ vendor.b938c301.js:14
f @ vendor.b938c301.js:14
p @ vendor.b938c301.js:14
(anonymous) @ vendor.b938c301.js:14
t._update @ vendor.b938c301.js:14
i @ vendor.b938c301.js:14
ii.get @ vendor.b938c301.js:14
ii @ vendor.b938c301.js:14
Fn @ vendor.b938c301.js:14
Ii.$mount @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
Ii @ vendor.b938c301.js:14
ae @ app.d85bba96.js:1
async function (async)
ae @ app.d85bba96.js:1
2f39 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
0 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
n @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
vendor.b938c301.js:139 GET http://192.168.0.9:8402/jarvis-socket/?EIO=4&transport=polling&t=NdeCdV9 net::ERR_EMPTY_RESPONSE
create @ vendor.b938c301.js:139
d @ vendor.b938c301.js:139
request @ vendor.b938c301.js:139
doPoll @ vendor.b938c301.js:139
poll @ vendor.b938c301.js:1
doOpen @ vendor.b938c301.js:1
open @ vendor.b938c301.js:1
open @ vendor.b938c301.js:139
c @ vendor.b938c301.js:139
t.exports @ vendor.b938c301.js:82
open @ vendor.b938c301.js:20
(anonymous) @ vendor.b938c301.js:20
setTimeout (async)
reconnect @ vendor.b938c301.js:20
maybeReconnectOnOpen @ vendor.b938c301.js:20
(anonymous) @ vendor.b938c301.js:20
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:139
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:1
(anonymous) @ vendor.b938c301.js:139
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:139
(anonymous) @ vendor.b938c301.js:139
setTimeout (async)
hasXDR.e.onreadystatechange @ vendor.b938c301.js:139
XMLHttpRequest.send (async)
create @ vendor.b938c301.js:139
d @ vendor.b938c301.js:139
request @ vendor.b938c301.js:139
doPoll @ vendor.b938c301.js:139
poll @ vendor.b938c301.js:1
doOpen @ vendor.b938c301.js:1
open @ vendor.b938c301.js:1
open @ vendor.b938c301.js:139
c @ vendor.b938c301.js:139
t.exports @ vendor.b938c301.js:82
open @ vendor.b938c301.js:20
u @ vendor.b938c301.js:20
a @ vendor.b938c301.js:80
connect @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
connect @ app.d85bba96.js:1
discover @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
setTimeout (async)
created @ app.d85bba96.js:1
ie @ vendor.b938c301.js:14
Pn @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
s @ vendor.b938c301.js:14
an @ vendor.b938c301.js:14
init @ vendor.b938c301.js:14
f @ vendor.b938c301.js:14
p @ vendor.b938c301.js:14
(anonymous) @ vendor.b938c301.js:14
t._update @ vendor.b938c301.js:14
i @ vendor.b938c301.js:14
ii.get @ vendor.b938c301.js:14
ii @ vendor.b938c301.js:14
Fn @ vendor.b938c301.js:14
Ii.$mount @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
Ii @ vendor.b938c301.js:14
ae @ app.d85bba96.js:1
async function (async)
ae @ app.d85bba96.js:1
2f39 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
0 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
n @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
vendor.b938c301.js:139 GET http://192.168.0.9:8402/jarvis-socket/?EIO=4&transport=polling&t=NdeCe1T net::ERR_EMPTY_RESPONSE
create @ vendor.b938c301.js:139
d @ vendor.b938c301.js:139
request @ vendor.b938c301.js:139
doPoll @ vendor.b938c301.js:139
poll @ vendor.b938c301.js:1
doOpen @ vendor.b938c301.js:1
open @ vendor.b938c301.js:1
open @ vendor.b938c301.js:139
c @ vendor.b938c301.js:139
t.exports @ vendor.b938c301.js:82
open @ vendor.b938c301.js:20
(anonymous) @ vendor.b938c301.js:20
setTimeout (async)
reconnect @ vendor.b938c301.js:20
(anonymous) @ vendor.b938c301.js:20
(anonymous) @ vendor.b938c301.js:20
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:139
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:1
(anonymous) @ vendor.b938c301.js:139
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:139
(anonymous) @ vendor.b938c301.js:139
setTimeout (async)
hasXDR.e.onreadystatechange @ vendor.b938c301.js:139
XMLHttpRequest.send (async)
create @ vendor.b938c301.js:139
d @ vendor.b938c301.js:139
request @ vendor.b938c301.js:139
doPoll @ vendor.b938c301.js:139
poll @ vendor.b938c301.js:1
doOpen @ vendor.b938c301.js:1
open @ vendor.b938c301.js:1
open @ vendor.b938c301.js:139
c @ vendor.b938c301.js:139
t.exports @ vendor.b938c301.js:82
open @ vendor.b938c301.js:20
(anonymous) @ vendor.b938c301.js:20
setTimeout (async)
reconnect @ vendor.b938c301.js:20
maybeReconnectOnOpen @ vendor.b938c301.js:20
(anonymous) @ vendor.b938c301.js:20
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:139
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:1
(anonymous) @ vendor.b938c301.js:139
i.emit @ vendor.b938c301.js:73
onError @ vendor.b938c301.js:139
(anonymous) @ vendor.b938c301.js:139
setTimeout (async)
hasXDR.e.onreadystatechange @ vendor.b938c301.js:139
XMLHttpRequest.send (async)
create @ vendor.b938c301.js:139
d @ vendor.b938c301.js:139
request @ vendor.b938c301.js:139
doPoll @ vendor.b938c301.js:139
poll @ vendor.b938c301.js:1
doOpen @ vendor.b938c301.js:1
open @ vendor.b938c301.js:1
open @ vendor.b938c301.js:139
c @ vendor.b938c301.js:139
t.exports @ vendor.b938c301.js:82
open @ vendor.b938c301.js:20
u @ vendor.b938c301.js:20
a @ vendor.b938c301.js:80
connect @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
connect @ app.d85bba96.js:1
discover @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
setTimeout (async)
created @ app.d85bba96.js:1
ie @ vendor.b938c301.js:14
Pn @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
s @ vendor.b938c301.js:14
an @ vendor.b938c301.js:14
init @ vendor.b938c301.js:14
f @ vendor.b938c301.js:14
p @ vendor.b938c301.js:14
(anonymous) @ vendor.b938c301.js:14
t._update @ vendor.b938c301.js:14
i @ vendor.b938c301.js:14
ii.get @ vendor.b938c301.js:14
ii @ vendor.b938c301.js:14
Fn @ vendor.b938c301.js:14
Ii.$mount @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
Ii @ vendor.b938c301.js:14
ae @ app.d85bba96.js:1
async function (async)
ae @ app.d85bba96.js:1
2f39 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
0 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
n @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
app.d85bba96.js:1 Failed connecting to http://192.168.0.9:8402!
(anonymous) @ app.d85bba96.js:1
Promise.catch (async)
discover @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
setTimeout (async)
created @ app.d85bba96.js:1
ie @ vendor.b938c301.js:14
Pn @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
s @ vendor.b938c301.js:14
an @ vendor.b938c301.js:14
init @ vendor.b938c301.js:14
f @ vendor.b938c301.js:14
p @ vendor.b938c301.js:14
(anonymous) @ vendor.b938c301.js:14
t._update @ vendor.b938c301.js:14
i @ vendor.b938c301.js:14
ii.get @ vendor.b938c301.js:14
ii @ vendor.b938c301.js:14
Fn @ vendor.b938c301.js:14
Ii.$mount @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
Ii @ vendor.b938c301.js:14
ae @ app.d85bba96.js:1
async function (async)
ae @ app.d85bba96.js:1
2f39 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
0 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
n @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
app.d85bba96.js:1 App # Error: Connection delayed
    at app.d85bba96.js:1
_ @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
Promise.catch (async)
(anonymous) @ app.d85bba96.js:1
setTimeout (async)
created @ app.d85bba96.js:1
ie @ vendor.b938c301.js:14
Pn @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
s @ vendor.b938c301.js:14
an @ vendor.b938c301.js:14
init @ vendor.b938c301.js:14
f @ vendor.b938c301.js:14
p @ vendor.b938c301.js:14
(anonymous) @ vendor.b938c301.js:14
t._update @ vendor.b938c301.js:14
i @ vendor.b938c301.js:14
ii.get @ vendor.b938c301.js:14
ii @ vendor.b938c301.js:14
Fn @ vendor.b938c301.js:14
Ii.$mount @ vendor.b938c301.js:14
Ti.t._init @ vendor.b938c301.js:14
Ii @ vendor.b938c301.js:14
ae @ app.d85bba96.js:1
async function (async)
ae @ app.d85bba96.js:1
2f39 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
0 @ app.d85bba96.js:1
r @ app.d85bba96.js:1
n @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1
(anonymous) @ app.d85bba96.js:1`

**Comment by Zefau** [comment]
@djalexz @metzger304 besteht das Problem noch? Tritt der Fehler auch auf, wenn ihr jarvis über die Kachel aus dem ioBroker Dashboard aufruft?

**Comment by metzger304** [comment]
> @djalexz @metzger304 besteht das Problem noch? Tritt der Fehler auch auf, wenn ihr jarvis über die Kachel aus dem ioBroker Dashboard aufruft?

leider lässt es sich weder über das dashboard noch über die Instanzenübersicht öffnen

**Comment by metzger304** [comment]
![image](https://user-images.githubusercontent.com/77586694/124974121-b97b9900-e02c-11eb-9708-71722124ce4b.png)

läuft immer noch in einen timeout rein

**Comment by metzger304** [comment]
![image](https://user-images.githubusercontent.com/77586694/125121505-505f5880-e0f4-11eb-9814-2b12f81e9ebb.png)

hilft diese Info?

**Comment by metzger304** [comment]
![image](https://user-images.githubusercontent.com/77586694/125187355-848b6400-e22f-11eb-9e35-6625eb2cdb93.png)
 Hilft das auch ?

**Comment by Zefau** [comment]
Kannst du mir noch einen Screenshot deiner Web Adapter Einstellungen machen?

**Comment by metzger304** [comment]
![image](https://user-images.githubusercontent.com/77586694/125192791-db9e3280-e249-11eb-8715-6b90b45a1e43.png)

**Comment by Zefau** [comment]
@metzger304 probier bitte nochmal mit `v3.0.0-alpha.24`.

**Comment by metzger304** [comment]
sieht besser aus! Danke
Morgen teste ich mehr aus!

![image](https://user-images.githubusercontent.com/77586694/125211121-5d22ae80-e2a4-11eb-98e6-24407f24b90f.png)

**Comment by metzger304** [comment]
![image](https://user-images.githubusercontent.com/77586694/125211264-6eb88600-e2a5-11eb-8d76-8e7c08638168.png)

das habe ich eben im log gesehen. WIchtig?

**Comment by daolis** [comment]
Habe das selbe Problem.
* Jarvis ist bei mir hinter einem reverse proxy mit https.
* der client versucht eine Verbindung mit dem Server auf port 8400 herzustellen. Allerdings mit https;//, was auf auf diesem port nicht funktioniert. `GET https://vis.local:8400/jarvis-socket/?EIO=4&transport=polling&t=NgRgit9 net::ERR_SSL_PROTOCOL_ERROR`

Ich habe auch versucht jarvis direkt mit dem iobroker port aufzurufen... (http://mcp.local:8082/jarvis/index.html#/instance=0)
Dann wird wird vom die url http://mcp.local:8082/jarvis-socket/?EIO=4&transport=polling..... aufgerufen... Warum hier nicht 8400? War meine Hoffnung dass der call auf port 8082 die NICHT https URL von 8400 verwendent....

**Comment by Zefau** [comment]
@metzger304 funktioniert alles soweit? Kam der JSON Fehler nochmal?

Wenn ja, dann bitte mal die Datenpunkte (`jarvis.0.layout`, `jarvis.0.widgets`, etc.) nacheinander in https://jsonformatter.curiousconcept.com/ parsen und schauen, wo der Fehler liegt.

**Comment by Zefau** [comment]
@daolis kannst du mal deine Web Adapterkonfiguration posten? Hast du die Port-Konfiguration in jarvis geändert?

jarvis läuft zwar über den Web Adapter und auf dem Port; socket-io ist aber nativ in jarvis drin (ohne socket-io Adapter) und läuft auf 8400 (sofern nicht in den Adapter-Einstellungen geändert).

**Comment by Zefau** [comment]
@metzger304 das Problem sollte inzwischen behoben sein. Kannst du das bestätigen?

**Comment by metzger304** [comment]
> @metzger304 funktioniert alles soweit? Kam der JSON Fehler nochmal?
> 
> Wenn ja, dann bitte mal die Datenpunkte (`jarvis.0.layout`, `jarvis.0.widgets`, etc.) nacheinander in https://jsonformatter.curiousconcept.com/ parsen und schauen, wo der Fehler liegt.

@Zefau: vielen Dank, aktuell läuft es für meine Bedürfnisse ohne irgendwelche Fehler...!
