### ISSUE TITLE
Iphone jarvis als app kein refresh möglich

### ISSUE THREAD

**Issue by cyberopi** [Zefau/ioBroker.jarvis#775]
wenn jarvis als web app installiert ist habe ich teilweise keine Funktion mehr. Ich muss app beenden und dann wieder neu starten . Gibt keine reload Funktion

**Comment by ciddi89** [comment]
Kann ich bestätigen. Habe leider das selbe Problem. iOS Version ist 14.6 und Jarvis Version ist: 2.2.0

**Comment by rschneider1509** [comment]
gleiches Problem in meinem Chrome auf dem Androiden. (Der Refresh funktioniert dann, aber ein erzwungener Refresh wäre besser, denn meist klicke ich dann einen Button und merke erst später, dass die Funktion gar nicht getriggert hat)

**Comment by WW1983** [comment]
Ich nutze dafür die IoBroker App. Der Vorteil ist, dass man VPN (wenn man einen Server eingerichtet hat) direkt in der APP hinterlegen kann. So habe ich auch von außen Zugriff.

Und der Refresh ist bei der APP auch möglich

**Comment by Zefau** [comment]
Ich kann einen pull to refresh in v3 einbauen?

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.62` gibt es nun ein Pull-to-Refresh auf mobilen Geräten

**Comment by ciddi89** [comment]
Hallo @Zefau 
du hast ja die Pull to Refresh Funktion mit eingebaut. Ich muss nun aber sagen das sich irgendwie das Refresh verhalten geändert hat. Im positivem Sinne. Wenn ich Jarvis öffne (auch wenn diese als Bookmark auf den Homescreen gespeichert worden ist) Aktualisiert er es jetzt innerhalb von Sekunden automatisch. Dafür ist nun aber die Pull to Refresh Funktion auf den Tablet, zumindest bei mir auf dem iPad, ein grauss... Sobald man nämlich innerhalb in einem Widget scrollen möchte, funkt diese Pull to Refresh Funktion immer dazwischen und man braucht viele versuche bis man den richtigen Punkt zum scrollen innerhalb dieses Widgets gefunden hat. Wäre es also eine Möglichkeit in den Settings ein Menüpunkt einzubauen um die Funktion komplett zu deaktivieren? Wobei, wenn sich das sowieso nun vernünftig beim öffnen refreshed, könnte man auf den zusätzlichen Code komplett verzichten und die Funktion wieder entfernen. Änderungen werden nämlich nun auch komplett übernommen obwohl die Seite geöffnet ist, ohne das man selbst refreshen braucht. Ist halt die Frage wie sich die Funktion in der breiten Masse verhält. 

Ich danke dir schon mal für die Mühe.

Aktuelle Jarvis Version: v3.0.0-alpha.84

**Comment by Zefau** [comment]
Ich würde das irgendwie drin lassen aber woanders hin schieben, wo es weniger stört. Die Frage ist, wo das sein könnte.

Eine Option zur Deaktivierung wäre wahrscheinlich bei allen immer aktiviert, wenn es tatsächlich so nervt wie du es darstellst. Dann lieber umbauen.

**Comment by ciddi89** [comment]
Ja das verstehe ich. Kann nun aber auch nur für mich und meine iOS Geräte reden. Habe sicherheitshalber noch einen anderen Browser ausprobiert um auszuschliessen das es an Safari liegt. Da ist aber das selbe verhalten. Weiss nun nur nich wie es bei Android Tabletts ist. Ansonsten muss ich sagen läuft das System sehr gut. :) Danke das du da soviel Arbeit und Zeit reinsteckst.

**Comment by Zefau** [comment]
Hab's nochmal durchdacht und werde es erst mal entfernen. Wenn du sagst, dass es nun insgesamt zufriedenstellend läuft sollte das passen. Mir fällt keine gute Möglichkeit ein die Funktion sonst zu integrieren.

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.87` entfernt

**Comment by ciddi89** [comment]
Danke nun läuft es perfekt. 👍🏻 Und mir ist gerade aufgefallen: Die Browser auf mein iPad haben schon alle native Pull to refresh. Nur wenn es als Bookmark auf dem Homescreen gespeichert ist geht das nicht. Ist ja aber auch egal weil er sich trotzdem sofort automatisch aktualisiert.
