### ISSUE TITLE
Chart module is not refreshing automatically / Chart Modul aktualisiert nicht automatisch

### ISSUE THREAD

**Issue by Sev7eNup** [Zefau/ioBroker.jarvis#779]
I use the chart module for several datapoints and would like to refresh the charts automatically. To do so I checked the option "Live-Aktualisierung" but nothing happens after the graph is displayed for the first time. The graphes show me the most recent data correctly. But from this point nothing is getting refreshed. No Data refresh for any graph. My configuration should be ok. Everything works quite smooth, but not the auto refresh function.

Ich nutze das Chart Modul für diverse Datenpunkt und würde diese gerne in den entsprechenden Graphen automatisch aktualisieren lassen.  Hierfür habe ich für jeden Graph die Option "Live-Aktualisierung" angehakt, jedoch findet keine automatische Aktualisierung nach dem initialen Laden des Graphen statt. Der Graph zeigt mir zunächst korrekte und aktuelle Daten, aber dann passiert nichts mehr. Die Konfiguration sollte ok sein, da alles funktioniert bis auf die Live-Aktualisierung.

![screen](https://user-images.githubusercontent.com/79143581/121756062-37757e80-cb19-11eb-8c92-e9e6ca09d81a.png)

**Comment by Zefau** [comment]
please move to v3
