### ISSUE TITLE
v3: Objektwerte werden nicht aktualisiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#780]
v3.0.0-alpha.6
Die Objektwerte hier im Beispiel 10° werden nach einem Tabwechsel und zurück nicht mehr im Browser aktualisiert.
Werte werden vom Script alle 5 Sekunden geändert und 1 Sekunde später wieder.
![image](https://user-images.githubusercontent.com/84818934/121774312-45131e80-cb82-11eb-94e5-a8317b533e70.png)
![jarvis3_Werte werden nicht aktualisiert2](https://user-images.githubusercontent.com/84818934/121774372-81df1580-cb82-11eb-9506-38df4b31f571.gif)

**Comment by mcuiobroker** [comment]
mit v3.0.0-alpha.8 scheint es, soweit ich es bis jetzt feststellen kann, behoben

**Comment by Zefau** [comment]
Dann mach ich es erst mal zu. Mach es gerne wieder auf, sofern du es erneut beobachtest.
