### ISSUE TITLE
v3: ICON-Style wird nicht umgesetzt, alle Icons haben blaue Farbe, obwohl andere definiert sind.

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#782]
`{"default":{"color":"black"}}`
![image](https://user-images.githubusercontent.com/84818934/120941177-930ec900-c721-11eb-9457-34f5103664ea.png)

**Comment by Zefau** [comment]
Fixed with `v3.0.0-alpha.7`

**Comment by mcuiobroker** [comment]
Farbe ist jetzt wieder da, jetzt funktioniert aber das blinken nicht mehr. (CSS)

**Comment by Zefau** [comment]
Wie war der css Code für das blinken?

**Comment by testit2020** [comment]
Bin gerade unterwegs.Code ist auch im Forum. Wenn ich zuhause bin schick ich ihn nochmal.

**Comment by Zefau** [comment]
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/2750

Gefunden, danke dir!

**Comment by mcuiobroker** [comment]
Bei mir sieht es so aus:
.blink {   animation: blinker 2s linear infinite;} 
@keyframes blinker {  50% {opacity: 0;}}

**Comment by Zefau** [comment]
Styles werden nicht konvertiert. Nur Devices, Layout und Settings.

Probiert bitte nochmal mit `3.0.0-alpha.8`. SwitchAction sollte wieder funktionieren und auch (blinkende) Icons.

**Comment by mcuiobroker** [comment]
Jetzt wird eine andere Farbe gewählt: (sollte eigentlich blau sein)?
![image](https://user-images.githubusercontent.com/84818934/121822113-9237e300-cc9d-11eb-9821-7b7bfe3a19a7.png)

**Comment by mcuiobroker** [comment]
Blinken funktioniert jetzt mit v3.0.0-alpha.8

**Comment by mcuiobroker** [comment]
Ein ICON wird im POPUP nicht gefunden:
![image](https://user-images.githubusercontent.com/84818934/121822877-cad9bb80-cca1-11eb-9342-e4aa98deecd3.png)
![jarvis3_ICON_wird_nicht_gefunden](https://user-images.githubusercontent.com/84818934/121822881-d1683300-cca1-11eb-9270-5df9b8adb379.gif)

**Comment by mcuiobroker** [comment]
ICON wird nicht gelb:
![image](https://user-images.githubusercontent.com/84818934/121823120-71728c00-cca3-11eb-89d7-0c820a7cc97c.png)
![jarvis3_ICON_wird_nicht_gelb](https://user-images.githubusercontent.com/84818934/121823129-79cac700-cca3-11eb-9ab7-0805f50227d1.gif)

**Comment by Zefau** [comment]
Bitte probier nochmal mit `v3.0.0-alpha.15`

**Comment by mcuiobroker** [comment]
Das funktioniert. Jetzt bekomme ich unterschiedliche Farben für den Link:
`{"false":"<span class='alarm ' style ='background-color:yellow'></span>","true":"<a href='https://www.google.de'>GoogleDE</a>"}`
in v2.2.0 ist der Link weiß, in v3 ist Link violet.
![image](https://user-images.githubusercontent.com/84818934/123513260-76b0dd00-d68c-11eb-933d-8454c602dc9c.png)
v3:
![image](https://user-images.githubusercontent.com/84818934/123513256-6f89cf00-d68c-11eb-9471-34bda35b9307.png)

**Comment by Zefau** [comment]
Violet = besuchter Link.

Sollte mit `v3.0.0-alpha.22` nun immer die Primary Color haben.

**Comment by mcuiobroker** [comment]
`v.3.0.0-alpha.33` 
Kannst du erstmal schließen, bislang keine Probleme bzgl Icon Color festgestellt.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.34`
Jetzt sind die Icon mit Effekten komplett weg.
![image](https://user-images.githubusercontent.com/84818934/126398983-028f474e-dfda-46c3-86f3-fd36d5f4bb53.png)
![image](https://user-images.githubusercontent.com/84818934/126399016-b3b8ede3-3640-4b87-b10a-82e1a76b9b2e.png)

**Comment by Zefau** [comment]
Was für'n Code/ Icon ist hinterlegt?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/126499460-5fca5fe1-24e3-4cef-8d25-d5e4f99a3a81.png)

**Comment by Zefau** [comment]
schreib mal `mdi-` bzw `mdi:` davor.

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.0-alpha.35`.

**Comment by mcuiobroker** [comment]
Mit mdi- davor klappt es.

**Comment by Zefau** [comment]
Jo, war aber auch ein Fehler im Code. Sollte nun auch wieder ohne gehen.
