### ISSUE TITLE
v3: HistoryGraph

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#783]
Es wird nichts angezeigt. Da muss ich nochmal genauer schauen. (TEST-System)
UPDATE huetemperaturesensor6_00e6c temperature
(anonymous) @ vendor.d87ce6a3.js:129

`Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/corona9:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/corona9:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/corona9:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/corona9:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/corona9:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/corona9:1 Failed to decode downloaded font: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/corona9:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
vendor.d87ce6a3.js:129 UPDATE huetemperaturesensor6_00e6c temperature`

**Comment by Zefau** [comment]
Welchen Adapter nutzt du? History, Influx oder sql? Hast du den angegeben?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/121785456-2a5c9c00-cbba-11eb-893e-f58cfb8b3d11.png)

**Comment by Zefau** [comment]
Fixed with `v3.0.0-alpha.7`

INFO: Die ganzen Optionen sind noch ohne Wirkung, aber der Chart sollte angezeigt werden.

**Comment by mcuiobroker** [comment]
Wird angezeigt: Schrift im Dark Modus nicht zu lesen:
![image](https://user-images.githubusercontent.com/84818934/121807083-f1243a80-cc52-11eb-9ed7-cb7732a36af6.png)
Kann da irgendwo ein X zum schließen hin?
![image](https://user-images.githubusercontent.com/84818934/121807155-4b250000-cc53-11eb-830e-3e003ea6e101.png)

**Comment by mcuiobroker** [comment]
Bei der Konvertierung zu v3 werden die Farben nicht vordefiniert, so dass alle Linien in der gleichen Farbe erscheinen:
![image](https://user-images.githubusercontent.com/84818934/121822700-c8c32d00-cca0-11eb-8398-328721b4c7ac.png)

**Comment by mcuiobroker** [comment]
v3.0.0-alpha.9 Beim Tabwechsel verschwindet der Graph:
![jarvis3_HistoryGraph_nach_tabWecshel_weg](https://user-images.githubusercontent.com/84818934/121957734-17d19680-cd63-11eb-8346-84b6a262f649.gif)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.20` nicht mehr verschwinden

**Comment by mcuiobroker** [comment]
Stimmt, verschwindet nicht mehr. Problem mit den DP bleibt.
Weiterhin haben die unterschiedlichen DP die gleiche Farbe und es wird nur einer bei mir angezeigt in der Legende oben, obwohl 2 da sind.

**Comment by Zefau** [comment]
> Wird angezeigt: Schrift im Dark Modus nicht zu lesen:

Sollte bereits mit der aktuellen alpha passen, kannst du das bestätigen?

>  Höhe variabel? Und zweiter Wert wird in der Legende nicht angezeigt?

Das passiert bei gleichen Label-Bezeichnern in eCharts.

> Bei der Konvertierung zu v3 werden die Farben nicht vordefiniert, so dass alle Linien in der gleichen Farbe erscheinen:

Sollte ebenfalls behoben sein. Kannst du das bestätigen?

**Comment by mcuiobroker** [comment]
Ja man muss entsprechend die Label anpassen, dann passt es auch mit den Farben. Mit der Konvertierung prüf ich ebenfalls morgen.

**Comment by mcuiobroker** [comment]
Also es kommt wieder zu dem Problem des Verschwindens der kompletten Historygraph-Anzeige, nur Überschrift bleibt:
![image](https://user-images.githubusercontent.com/84818934/125980133-4dbe773f-1a89-44ba-ac00-ed3e42534cae.png)
Bei der Konvertierung werden die Label nicht mit den Wertenamen gefüllt:
DP mit History: coronavirus-statistics.0.Germany.Stadt.xxx.cases7_per_100k 
DP2 : coronavirus-statistics.0.Germany.Stadt.xxx.deaths
er nimmt davon jeweils "corona" anstatt "cases7_per_100k" bzw "deaths".

**Comment by mcuiobroker** [comment]
Mit `v3.0.0-alpha.29` wird ein Fehler angezeigt:

![image](https://user-images.githubusercontent.com/84818934/126049236-8a74d30a-3d23-4c49-b930-b1e2dda27935.png)

**Comment by Zefau** [comment]
aktuell lädt HistoryGraph alle historischen Daten eines Datenpunkts ohne zeitliche Einschränkung. Das scheint einfach zu viel zu sein, da muss ich nochmal ran und eine Eingrenzung wie in v2 hinzufügen.

**Comment by Zefau** [comment]
Mit `v3.0.0-alpha.41` ist das Modul jetzt v3 ready (sofern bug-free).

Nun ist wie in v2 eine Zeitangabe festzulegen. Vorher wurden alle History-Daten eines Datenpunkts geladen, was einfach zu viele Daten sind und zu in-performant ist. Nun kann ein festes Von-Bis-Datum ausgewählt werden oder es kann ein bestimmter Zeitraum in die Vergangenheit geschaut werden (bekannt aus v2).

Beim Chart-Typ kann zwischen Linie und Bar gewählt werden, wobei Bar die Säulen bei vielen Daten kaum erkennbar sind. Hierfür gibt es eine Aggregationsmöglichkeit, um auch die Performance zu erhöhen. Diese zeigt dann aber (logischerweise) weniger Daten / weniger Details an.

Die Legende kann nun ausgeblendet werden. Wird diese ausgeblendet, können die Datenpunkte identische Namen haben. Sofern diese eingeblendet ist und es Datenpunkte mit identischen Namen gibt, dann fügt jarvis `(2)` an, um diese zu unterscheiden.

Die Achsen können nun frei konfiguriert werden (siehe https://echarts.apache.org/en/option.html#xAxis bzw. https://echarts.apache.org/en/option.html#yAxis für alle Optionen). Dies inkludiert insbesondere `min` / `max` für die y-Achse.

Außerdem kann die Zeitangabe auf der X-Achse frei definiert werden.

**Comment by mcuiobroker** [comment]
Kann leider erst nächste Woche testen. Hab zurzeit kein System. Melde mich dann.

**Comment by mcuiobroker** [comment]
v3.0.0-alpha.53
Bei Größenänderung von Gesamt-index.html wird der Graph nicht kleiner (bzw angepasst), er bleibt in seiner Ursprungsgröße.
![image](https://user-images.githubusercontent.com/84818934/130284290-663be7e0-026e-4f1b-b9f2-e58413c4239a.png)

**Comment by mcuiobroker** [comment]
Bekomme auch folgende Fehler angezeigt in der F12-Konsole:
![image](https://user-images.githubusercontent.com/84818934/130288557-b67427f7-7ebb-4d9d-9814-ec0b00d5a20b.png)
Wann kann man denn den Pro-User anmelden? Ich kann sonst bestimmte Sachen gar nicht mehr testen?

**Comment by Zefau** [comment]
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/4868 ist kein Fehler in Verbindung mit Pro.
Vielmehr scheint hier das parsen der Notifications fehlzuschlagen, also `jarvis.X.notifications` ist kein JSON-Array.

In v3 ist Pro nun implementiert, aber noch nicht aktiviert. Eigentlich sollte alles wie normal funktionieren.
Ich schau mir das gleich mal an.

**Comment by mcuiobroker** [comment]
Mit `v3.0.0-alpha.61` ist nur noch der Effekt mit den zusätzlichen Zahlen in Klammern aufgefallen: 
Corona (1) (2) (3)

![image](https://user-images.githubusercontent.com/84818934/131876801-eb83b042-7c5d-466d-9119-dffc969d6f02.png)

Vergrößerung und Verkleinerung von BrowserSeite passen. Anuf dem Handy nicht. Dort wird der HistoryGraph zu breit dargestellt. Im Querformat fehlen auf der rechten Seite ca 10%. Im Hochformat ca 50%.

**Comment by Zefau** [comment]
besteht das Problem mit `(1)` noch mit `v3.0.0-alpha.81` ?

**Comment by mcuiobroker** [comment]
Momentan werden die Daten gar nicht angezeigt. Ich würde damit warten, bis die anderen Sachen wieder funktionieren und dann nutze ich mal Prod-Daten.

**Comment by Zefau** [comment]
Das Hochformat / Querformat Problem sollte mit `v3.0.0-alpha.82` behoben sein.

**Comment by mcuiobroker** [comment]
Das Hoch-Querformat Verhalten tritt nicht mehr auf. 
Problem mit der (1) auch nicht, da ich gerade nicht mehr weiß, wie man die unterschiedlichen Kurven einstellen kann.
![image](https://user-images.githubusercontent.com/84818934/134825038-33f2e2bb-8599-411e-9617-de5f0a4011d2.png)

**Comment by mcuiobroker** [comment]
Von den einstellbaren Werten für yAxis (https://echarts.apache.org/en/option.html#yAxis)  ziehen nur: 
`{"position":"right","name":"Anzahl"}`
Liegt es am Pro Account?

**Comment by Zefau** [comment]
Achsen sind nur mit Pro Account, der aber in der Alpha generell aktiviert ist. Es sollte also alles gehen.

Was versuchst du denn genau?

Das mit dem Neuladen kann sein, da er das gechached hat. Da kann ich nochmal schauen.

**Comment by mcuiobroker** [comment]
Wollte Color, fontSize usw. testen und hatte übersehen, dass es in ein JSON `nameTextStyle` muss. Funktioniert.
Was ich noch nicht herausgefunden habe ist, wie kann man bei zwei unterschidlichen Kurven die linke yAchse für die eine verwenden und die rechte yAchse für die andere. Da es ja vorkommt, das ein Kurve eine Zahl zeigt und die andere z.B. %-Werte.

**Comment by Zefau** [comment]
Vom ursprünglichen Bug Report ist alles weg, richtig (mit Berücksichtigung von #953)? Offen ist nur die Frage bzgl. zweiter y-Achse?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/326

**Comment by Zefau** [comment]
kommt mit der nächsten alpha
