### ISSUE TITLE
v3: LightColorBody und -state haben keine Funktion

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#785]
![image](https://user-images.githubusercontent.com/84818934/120942654-affbca00-c72a-11eb-9dfc-e263e9025604.png)
![image](https://user-images.githubusercontent.com/84818934/120942663-c1dd6d00-c72a-11eb-908f-dfb9c8e590e6.png)

**Comment by Zefau** [comment]
Prüf bitte nochmal mit `v3.0.0-alpha.8`.

**Comment by mcuiobroker** [comment]
Weiterhin ohne Wählmöglichkeit:
![image](https://user-images.githubusercontent.com/84818934/121823741-7cc7b680-cca7-11eb-8a5d-31655502be21.png)
Extrem lange Wartezeit bzw. es kann nicht geändert werden:
![image](https://user-images.githubusercontent.com/84818934/121823788-bb5d7100-cca7-11eb-8bdb-b18d35a42884.png)
Ich würde behaupteen, es hängt mit der Grupeenfunktion zusammen die in diesem Statelist drin ist und nicht funktioniert?
![image](https://user-images.githubusercontent.com/84818934/121823830-fe1f4900-cca7-11eb-8b89-eaffca8b613f.png)

**Comment by Zefau** [comment]
Bist du laut Konsole auch auf alpha.8 oder arbeitest du ggf. auf einer cached version?

Bei mir:
![image](https://user-images.githubusercontent.com/14368811/121947981-fbc7f800-cd56-11eb-96d0-7545230ea591.png)

![image](https://user-images.githubusercontent.com/14368811/121948099-1d28e400-cd57-11eb-8ebb-cb97d29eff73.png)

**Comment by mcuiobroker** [comment]
Für HUE-Lampen geht es:
![image](https://user-images.githubusercontent.com/84818934/121948868-18b0fb00-cd58-11eb-9332-c16da757f865.png)
Mit dem rgb Wert, war mein Fehler, ich hatte dort in dem Wert die Colorbody und-state schon in v2.2.0 rausgenommen. Sorry.

**Comment by Zefau** [comment]
Bitte probier nochmal mit `v3.0.0-alpha.15`

**Comment by mcuiobroker** [comment]
Die Daten werden jetzt gespeichert. Kann man das Auswahlfenster für die Farbe vielleicht verkleinern? Oder evtl. per Prozentzahl selber einstellen? Ein wenig zu groß?

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.22` nun kleiner dargestellt.

**Comment by mcuiobroker** [comment]
Leider zu klein:
![image](https://user-images.githubusercontent.com/84818934/123544498-d32aff80-d753-11eb-963d-83a626f88117.png)

**Comment by mcuiobroker** [comment]
Die Einstellung war bei mir plötzlich weg? Keine Ahnung warum. passt.
