### ISSUE TITLE
v3: Aufteilung, LevelBody keine Einstellungen, Werte verloren (Konvertierung v3)?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#786]
![image](https://user-images.githubusercontent.com/84818934/120942730-1a146f00-c72b-11eb-8112-4cba51e4ef43.png)
![image](https://user-images.githubusercontent.com/84818934/120942738-2c8ea880-c72b-11eb-965e-8dfc7a2209c9.png)

**Comment by Zefau** [comment]
Prüf bitte nochmal mit `v3.0.0-alpha.8`.

**Comment by mcuiobroker** [comment]
LevelBody:
![image](https://user-images.githubusercontent.com/84818934/121822511-b8f71900-cc9f-11eb-98b5-6421d71cb2fe.png)
![jarvis3_Levelbody_nicht_definierbar](https://user-images.githubusercontent.com/84818934/121822516-c2808100-cc9f-11eb-86d7-30c2c94b830d.gif)

**Comment by Zefau** [comment]
@mcuiobroker Besteht der Fehler aktuell noch?

**Comment by mcuiobroker** [comment]
Nach Konvertierung von v2.2.0 auf v3 ist jetzt die Einstellung weg: Schrittweite fehlt
![image](https://user-images.githubusercontent.com/84818934/123512575-83cbcd00-d688-11eb-8636-8caac01fb68f.png)
Geändert auf Scchrittweite 10: Zieht aber nicht
![image](https://user-images.githubusercontent.com/84818934/123512613-b1187b00-d688-11eb-8fef-3cf2b8b1bd68.png)
weil die Änderung auf 10 nicht mit Übernehmen gespeichert wird.

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.0-alpha.20`.

**Comment by Zefau** [comment]
@mcuiobroker das müsste behoben sein? danke dir

**Comment by Bernd9000** [comment]
Version 3.0.0-alpha.50
Bei mir funktioniert das leider auch nicht mit Schrittweite.
Und "Schritte/Markierung zeigen" läuft nicht richtig unter "Component Option"
Ich kann Sie nur einmal ausschalten aber dann nicht wieder einschalten.
Was geht nach dem öffnen ist die Reihenfolge  aus/ein   und dann speichern, dann wird es gespeichert.
Aber beim Aufruf wird es immer als eingeschaltet angezeigt.

**Comment by mcuiobroker** [comment]
In v3 werden bei einer Schrittweite von 1 auch alle angezeigt unabhängig von der Anzahl der Markierungspunkte:
![image](https://user-images.githubusercontent.com/84818934/132385922-fbe4b2a0-a33f-4c64-810a-b82f51333cc2.png)

![image](https://user-images.githubusercontent.com/84818934/132386375-19a6e344-e2cc-499c-98b6-2d6fefd822c0.png)
Dann zeigt er 100 Punkte an:
![image](https://user-images.githubusercontent.com/84818934/132386431-416dff3f-9b23-4ee5-bd93-e79b60265595.png)


Schritte/Markierungen anzeigen ausschalten hat auch keinen Effekt. Es bleiben die vielen Punkte.

In v2:
![image](https://user-images.githubusercontent.com/84818934/132386666-fc00f7a7-6ce5-492d-85c8-625d32625e59.png)
Wurden nur die Markierungspunkte angezeigt und trotzdem konnte man die Werte dazwischen Auswahl, je nach Angabe der Schrittweite.

**Comment by mcuiobroker** [comment]
Mit `v3.0.0-alpha.77` hat dies auch erledigt.
