### ISSUE TITLE
v3: LightColorState nicht in der auswählbaren Liste

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#787]
![image](https://user-images.githubusercontent.com/84818934/120942793-7b3c4280-c72b-11eb-8e61-e1a691921395.png)

**Comment by Zefau** [comment]
Prüf bitte nochmal mit `v3.0.0-alpha.8`.

**Comment by mcuiobroker** [comment]
LevelBody:
![image](https://user-images.githubusercontent.com/84818934/121822511-b8f71900-cc9f-11eb-98b5-6421d71cb2fe.png)
![jarvis3_Levelbody_nicht_definierbar](https://user-images.githubusercontent.com/84818934/121822516-c2808100-cc9f-11eb-86d7-30c2c94b830d.gif)
