### ISSUE TITLE
v3: Zweite Instanz übernimmt die Daten von der ersten:

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#788]
![image](https://user-images.githubusercontent.com/84818934/121209348-1132b300-c87b-11eb-900f-19b7a2cd0fd2.png)
pagetitle wird in allen Instanzen auf den gleichen Namen geändert, egal wo man ihn ändert (.0,.1)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/121785574-d900dc80-cbba-11eb-8f2f-9afae195396f.png)
Aus dem Link wird: http://192.168.178.70:8082/jarvis/index.html#/

**Comment by Zefau** [comment]
Fixed with `v3.0.0-alpha.7`

**Comment by mcuiobroker** [comment]
Weiterhin werden die Daten von der 0. Instanz in die 1.Instanz übernommen

**Comment by mcuiobroker** [comment]
mit v3.0.0-alpha.8 bekommt man bei vorhandener 2ter Instanz nur noch ein Timeout bei nicht vorhandenen Daten.
![image](https://user-images.githubusercontent.com/84818934/121906246-387dfa00-cd2b-11eb-82c8-b5b553e4c3b4.png)
Es wird nur diese Adresse: http://192.168.178.70:8082/jarvis/index.html#/1/ angezeigt.

**Comment by Zefau** [comment]
Bei mir geht es. Mit alpha-8 ist die alte Schreibweise wieder supported, allerdings mit einem Reload (um es ins neue Format zu bringen).

Wenn du vom ioBroker Dashboard kommst, sollte es direkt problemlos gehen.
Aber auch der direkte Aufruf von:
- https://192.168.178.29:8082/jarvis/index.html#/0 bzw
- https://192.168.178.29:8082/jarvis/index.html#/1

Sollte problemlos klappen.

**Comment by mcuiobroker** [comment]
Ja das funktioniert auch, ich wollte nur darauf hinweisen, dass man ja von der v2.2.0 kommt .

**Comment by Zefau** [comment]
Versuch mal bitte mit v2 Syntax. Sollte mit alpha-8 funktionieren.
