### ISSUE TITLE
v3: Label wird nicht angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#789]
![image](https://user-images.githubusercontent.com/84818934/121089041-d97a2b80-c7e6-11eb-80eb-018806e7e92f.png)
![image](https://user-images.githubusercontent.com/84818934/121089107-f0b91900-c7e6-11eb-84dc-ff5286865b56.png)
Bei Änderung vom Body State wird der Label-Wert auch nicht neu gesetzt.
![image](https://user-images.githubusercontent.com/84818934/121089543-966c8800-c7e7-11eb-9d56-d18b74152a9e.png)

**Comment by Zefau** [comment]
Fixed with `v3.0.0-alpha.7`

**Comment by mcuiobroker** [comment]
Komisch:
![image](https://user-images.githubusercontent.com/84818934/121806406-09468a80-cc50-11eb-8d74-2d7e329720fb.png)
Testsystem deswegen vor einem Monat
![image](https://user-images.githubusercontent.com/84818934/121806441-28451c80-cc50-11eb-8621-63b46d1f07ba.png)

**Comment by Zefau** [comment]
might be same as https://github.com/Zefau/ioBroker.jarvis/issues/798

**Comment by Zefau** [comment]
sollte mit ` v3.0.0-alpha.10` behoben sein

**Comment by mcuiobroker** [comment]
Ja stimmt, funktioniert.
