### ISSUE TITLE
Support import of devices from ioBroker.sonoff adapter

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#79]
https://forum.iobroker.net/post/490256

**Comment by Zefau** [comment]
added with `1.1.0-beta.9`.

**Comment by Zefau** [comment]
Currently the following devices / states are supported:
```
{
   'version':'.Version',
   'reachability':'.alive',
   'power':{
      "state":".POWER",
      "action":".POWER"
   },
   'consumption':'.ENERGY_Total',
   'meter':'.ENERGY_Power',
}
```

**Comment by Zefau** [comment]
@Timmes123 Was hast du für Sonoff-Geräte, die wir dem Importer hinzufügen können?

**Comment by funky4t** [comment]
Ich könnte dir 
Gosund Sp111 mit Powermetering
Sonoff R2 POW mit Powermetering
Gosund Sp1 mit Powermetering
Wemos D1 mit Temperaturfühler und 
Wemos D1 mit Ultraschallsensor zur Distanzmessung (Ölstand)
anbieten.

Reicht dir ne Copy der Datenpunkte oder wie kann ich supporten?

**Comment by Zefau** [comment]
1. von einem Gerät ( `channel`) das `RAW` json
2. Screenshot der Geräte (oder eines Geräts, sofern die alle gleich sind).

**Comment by Timmes123** [comment]
@Zefau funky4t hat viel mehr als ich, also lass dir von ihm sein Sortiment geben :-) dann hast du direkt alles von einem ;-)

**Comment by Zefau** [comment]
@funky4t

**Comment by funky4t** [comment]
@Zefau ich mach dir das RAW heut Abend fertig! 👍🏼

**Comment by funky4t** [comment]
@Zefau Ich denke du bist mit Intergration der RAW Daten schneller, leider musst du nem Dummy dann erklären, wie ich die finde. Da ich immer gern was dazulerne, versuche ich es dann. Ansonsten bleiben mir nur mehrere Screenshots...

Ich hab bereits das Device aufgerufen und unter RAW (Experten) nachgesehen, da steht aber meines Erachtens nicht alle Datenpunkte die sich im Ordner befinden.... Was mach ich falsch?!

Beispiel in den Screens
 
<img width="1283" alt="Bildschirmfoto 2020-11-03 um 18 19 54" src="https://user-images.githubusercontent.com/57875762/98018880-6304ed80-1e01-11eb-9a76-b5b281a83a4f.png">
<img width="1287" alt="Bildschirmfoto 2020-11-03 um 18 20 26" src="https://user-images.githubusercontent.com/57875762/98018886-64ceb100-1e01-11eb-995a-b83909c79777.png">

Ich "bieg" doch da irgendwo falsch ab, oder? ;)

**Comment by funky4t** [comment]
Also ich hab nochmal nachgesehen, ich kann dir für jeden Datenpunkt eines Gerätes die einzelnen Raw Dateien senden. Also im Fall oben 18 einzelne Raw Dateien für die SP111 Steckdose. Aber es müsste doch ne Option geben, die alle Datenpunkte en Block für das jeweilige Gerät ausgibt, oder irre ich mich?....

**Comment by Zefau** [comment]
Brauch ich nicht, der Screenshot reicht. Ich hatte gehofft, dass im `native` Teil des Adapters mehr Informationen über das Gerät hinterlegt sind, die ich nutzen kann. Leider ist dem nicht so.

Ich brauche eine Information (entweder ein Datenpunkt oder im RAW), um welches Gewerk (Licht, Rollo, Steckdose, Sensor, etc.) es sich handelt.

Ist die Datenpunkt-Struktur des Screenshots bei all deinen 18 Geräten identisch? (dann bräuchte ich die Screenshots nicht, ansonsten wären die sehr hilfreich, um die Unterschiede zu sehen).

Danke dir

**Comment by funky4t** [comment]
Nur damit ICH des verstehe Aber bitte nicht lachen ;):
das Gerät ist ja "Kühlschrank", darunter befinden sich doch die 18 Datenpunkte dieses einen Gerätes und soweit ich das sehr unterscheiden sich die RAWs da schon teilweise....aber nicht stark.
Andere Geräte erzeugen weniger Datenpunkte mit unterschiedlichen Strukturen. 
Dumme Frage vom Nicht-Programmierer, du benötigst die Struktur der DP in den oberen geschweiften Klammern oder? Sprich du importierst die von MQTT und dem Sonoff erzeugten Datenpunkte richtig?

Also Gewerke erkenne ich da im Sonoff nicht, die muss ich manuell hinzufügen. Da Tasmota extrem universell ist und mit hunderten von Sensoren läuft, stell ich mir die Frage wie das beim Auto-Import nach Gewerken gehen soll? Wie du siehst, hab ich Sockets, die aber Licht, Kühlschrank oder Waschmaschine schalten und messen und genauso hab ich Tasmota die Abstände oder Temperaturen messen. Nur mal ne Idee, falls ich es richtig verstehe, macht es Sinn ein Gewerk "Tasmota" zu generieren, wo man nachträglich manuell korrigiert, so wie im Sonoff Adapter selbst? 

Ich häng hier mal ne ZIP rein mit Screenshots der drei Geräte und deren Datenpunkte...

Hilft dir das so weiter?
[Tasmotas.zip](https://github.com/Zefau/ioBroker.jarvis/files/5483385/Tasmotas.zip)

**Comment by Zefau** [comment]
puh, schwierig. Also die aktueller Version des Importers übernimmt den Datenpunkt `POWER`. Alle anderen Datenpunkten erscheinen mir extrem individuell abhängig des jeweiligen Geräts.

Was für Datenpunkte soll ich übernehmen? :-\

**Comment by Timmes123** [comment]
schau mal auf die website des adapters

https://github.com/ioBroker/ioBroker.sonoff

da steht eine liste, welche datenpunkte dort erwartet werden.
Die liste kannst du denk ich 1:1 übernehmen als input.

allerdings welches gerät dahinter steckt ist wohl absolut flexibel, weil du mit nem wemos halt zusammen basteln kannst was du willst

**Comment by funky4t** [comment]
Ich frag mal so...
1. Import eines Switches mit POWER
2. Import eines Switches mit POWER und ENERGYstates da wo vorhanden. Das Metering ist da spannende bei Gosunds und Sonoff Steckdosen.
3. Import eines SENSORS, wenn verschiedene Datenpunkt vorhanden sind, die nicht in 1 und 2 enthalten sind? Deckt dann Wemos und Sensoren ab.
Ich fände es jetzt nicht schlimm bei 3. ein paar manuelle Korrekturen anzulegen, je nach Sensor und gemessener Unit

Aber in der Tat gibt es aus RGBW Lampen und Stripeconverter die über Tasmota laufen... :/

Mal ne ganz doofe Frage, kann man aus der Tasmota.bin und Tasmota-Sensor.bin was ableiten? Gibt bei Theo Arendts irgendwo auch ne Liste mit Sensoren, die Tasmota supportet.

Und zum Schluss spinnt der "Anwender" sprich ich nochmal:

Viel Arbeit macht es grundsätzlich 18 Datenpunkte beim Device Kühlschrank mit Copy Paste aus der Objektliste anzulegen. Angenommen du importierst ALLE Datenpunkte, notfalls per Index mit DP1,DP2 aus dem Sonoff, dann kann ich doch die,welche ich nicht benötige mit einem Klick wieder rauswerfen. Das wäre oft z.B. bei 18 automatischen Datenpunkten und 5 zu löschenden komfortabler als die 13 benötigten manuell anzulegen...
Is nur ne Idee als Anwender, mir fehlt da der geschulte Blick unter die Hauben der Systeme.

**Comment by Zefau** [comment]
#1 und #2 deiner Liste werden durch den Importer aktuell bereits übernommen. Ich würde ungern alle 18 Datenpunkte durch den Importer übernehmen. Umso Datenpunkte in jarvis sind, umso langsamer wird jarvis. Insofern möchte ich hier gerne so viel wie nötig aber so wenig wie möglich übernehmen.

**Comment by funky4t** [comment]
Okay, das kann ich nachvollziehen. Sorry #1 und #2 hab ich damals nur kurz getestet, da ich bei mir fast durchgängig mit Aliasen arbeite und die manuell reinnehme. Also die Energy Werte werden m.E. bei vielen Tasmota Usern genutzt, deren Import ist halt etwas zeitaufwändig. Ansonsten verfolge ich Tasmota Diskussionen auf Facebook mit dem DB18 Temp-Sensor und seltener die Distanzmessung. Sorry dass ich dir da nicht mehr helfen kann, da kommt uns die Flexibilität von Tasmota zum Nachteil..... :(

**Comment by Zefau** [comment]
https://forum.iobroker.net/post/517305

**Comment by Timmes123** [comment]
Also aufgrund des Themas hier habe ich mich mal etwas mehr mit MQTT beschäftigt.
Ich habe mal ein System von mir von Web API auf MQTT umgestellt um zu schauen wie es sich verhält.
Also der Sonoff Adapter erwartet zwar gewisse States wie „POWER“ oder die, welche ich oben schon als link reingepackt hab.
Damit kannst du meiner Meinung nach 99% der Geräte definieren.
Ich habe z.b. Steckdosen über den Adapter und jetzt auch mal zum Testen ein paar Wemos gekauft, welche ich mit Tasmota eingebunden habe.
Beide greifen auf die Standard States wie „Power“ und „Energy“ usw. zurück.
Ich habe allerdings auch bei meiner eigenen MQTT Schnittstelle (Daten meiner Pflanzensensoren per Nodered über MQTT dem iobroker übergeben) meine States komplett selbst und frei definiert.
Das heißt es ist auch möglich, dass mal komplett andere States drinstehen könnten, das ist dann aber sowieso benutzerdefiniert und wenn das nicht automatisch einlesbar ist, ist das denke ich ok.
Ein Channel entspricht immer einem Device
Unterordner existieren soweit ich gesehen habe nicht. Diese entstehen nur dadurch, dass die Datenpunkte z.b. Info.Hostname heißen


Mein Vorschlag zur Gruppierung der Geräte wäre wie folgt.
Ein Channel -> Ein Device

Check ab ob States wie Power und Energy vorkommen, falls ja ist es wahrscheinlich eine Steckdose oder ähnliches mit Leistungsmessung
In dem Fall würde ich folgende Werte für die breite Masse an Usern als interessant sehen:
POWER (ein/ausschalten)
ENERGY_Power (aktuelle Leistung in W)
ENERGY_Today (heutige Arbeit in kw/h) -> es gibt auch noch yesterday, aber, wenn man aufzeichnen will, zeichnet man ja eher den Today auf, also würde ich yesterday nicht immer übernehmen
ENERGY_Total (gesammte Arbeit in kw/h) -> Stromzähler

Den Rest halte ich für überflüssig, Werte wie Current, Factor, Voltage usw. sind zwar vorhanden, aber für den User zuhause eigentlich irrelevant. Im Ausnahmefall würde ich wieder sagen -> benutzerdefinierte Ausnahme -> selbst einstellen.

Auf Basis davon würde ich mir von verschiedenen Geräten mal die Infos zeigen lassen.
Z.b. Gibt es Temperaturfühler per MQTT, diese haben dann wahrscheinlich den State temperature mit drin. Aber Achtung hier! Es gibt auch Geräte die z.b. eine Gerätetemperatur übermitteln, diese ist dann eigentlich auch weniger interesannt.
Gleiches gilt für Feuchtigkeit, Helligkeit usw…
Viele Geräte haben ein Battery State mit dabei, das könntest du falls vorhanden auch übernehmen. Ist bei meinen Steckdosen jetzt aber nicht dabei.

Ich hoffe das Hilft dir ein bisschen weiter 😊

**Comment by Timmes123** [comment]
RAW vom Channel:

{
  "from": "system.adapter.sonoff.0",
  "user": "system.user.admin",
  "ts": 1604691664784,
  "common": {
    "name": "Gosund_SP1_Kuehlschrank",
    "desc": ""
  },
  "native": {
    "clientId": "Gosund_SP1_Kuehlschrank"
  },
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator"
  },
  "_id": "sonoff.0.Gosund_SP1_Kuehlschrank",
  "type": "channel"
}

**Comment by Timmes123** [comment]
RAW von Energy_Power
(Den InfluxDB teil kannst du ignorieren)

{
  "from": "system.adapter.sonoff.0",
  "user": "system.user.admin",
  "ts": 1604691670173,
  "common": {
    "name": "Gosund_SP1_Kuehlschrank ENERGY  Power",
    "type": "number",
    "role": "value.power.consumption",
    "unit": "W",
    "read": true,
    "write": false,
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "retention": 0,
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "sonoff.0.Gosund_SP1_Kuehlschrank.ENERGY_Power",
  "type": "state"
}

**Comment by Timmes123** [comment]
RAW von ENERGY_Today

{
  "from": "system.adapter.sonoff.0",
  "user": "system.user.admin",
  "ts": 1604691670167,
  "common": {
    "name": "Gosund_SP1_Kuehlschrank ENERGY  Today",
    "type": "number",
    "role": "value.power.consumption",
    "unit": "kWh",
    "read": true,
    "write": false,
    "custom": {
      "influxdb.0": {
        "enabled": true,
        "changesOnly": true,
        "debounce": "1000",
        "retention": 0,
        "changesRelogInterval": 0,
        "changesMinDelta": 0,
        "storageType": "",
        "aliasId": ""
      }
    }
  },
  "native": {},
  "acl": {
    "object": 1636,
    "owner": "system.user.admin",
    "ownerGroup": "system.group.administrator",
    "state": 1636
  },
  "_id": "sonoff.0.Gosund_SP1_Kuehlschrank.ENERGY_Today",
  "type": "state"
}

**Comment by Timmes123** [comment]
> https://forum.iobroker.net/post/517305

Zu deinem Link.
Dort wird wie es aussieht ein Wemos D1 Mini verwendet
Der hat 8 i/os und hier verwendet er alle 8 als Power Signale.. deswegen hast du POWER bis POWER7
das sind dann 8 Schaltsignale um z.b. Lichter oder irgendwas beliebiges zu schalten.

**Comment by Zefau** [comment]
@Timmes123 fehlt von den hier genannten Datenpunkten noch welche in der aktuellen Version des Importers?

**Comment by Timmes123** [comment]
@Zefau wo kann ich nachschauen was alles import wird? in der wiki steht es noch nicht

**Comment by Zefau** [comment]
```
{
					//...deviceStructure.states, // results in duplicated entries
					'version': [ '.Version', '.INFO.Version' ],
					'reachability': '.alive',
					'ip': '.INFO.IPAddress',
					'signal': '.Wifi_Signal',
					'alive': '.alive',
					
					'dataReceived': '.RfReceived_Data',
					
					'power': {
						"state": ".POWER",
						"action": ".POWER"
					},
					'powerCurrent': {
						"state": ".ENERGY_Current",
						"unit": " A"
					},
					'powerMeter': {
						"state": ".ENERGY_Power",
						"unit": " W"
					},
					'powerConsumption': {
						"state": ".ENERGY_Total",
						"unit": " kWh"
					},
					'powerConsumptionToday': {
						"state": ".ENERGY_Today",
						"unit": " kWh"
					},
					'powerConsumptionYesterday': {
						"state": ".ENERGY_Yesterday",
						"unit": " kWh"
					},
					
					'power1': {
						"state": ".POWER1",
						"action": ".POWER1"
					},
					'power2': {
						"state": ".POWER2",
						"action": ".POWER2"
					},
					'power3': {
						"state": ".POWER3",
						"action": ".POWER3"
					},
					'power4': {
						"state": ".POWER4",
						"action": ".POWER4"
					},
					'power5': {
						"state": ".POWER5",
						"action": ".POWER5"
					},
					'power6': {
						"state": ".POWER6",
						"action": ".POWER6"
					},
					'power7': {
						"state": ".POWER7",
						"action": ".POWER7"
					},
					'power8': {
						"state": ".POWER8",
						"action": ".POWER8"
					},
					'power9': {
						"state": ".POWER9",
						"action": ".POWER9"
					},
```

**Comment by ma-gu-16** [comment]
Hallo, 
ich habe eben Jarvis installiert und möchte das ganze mal testen. 
nun wollte ich meine  Sonoff WLAN RGBW Strips hinzufügen. 

scheint nicht zu gehen, ich habe alles importiert jedoch habe ich nur folgende States: 
reachability
ip
alive
power
version

kann es sein das diese nicht supportet werden, kommen die noch ? oder mache ich etwas falsch :-P 
Danke. 

Auf den RGBW WLAN Controllern läuft Tasmota https://github.com/arendst/Tasmota

**Comment by Zefau** [comment]
Es werden nur ausgewählte Datenpunkte importiert und nicht alles. Was fehlt dir konkret? Im schlimmsten Fall kannst du es manuell anlegen.

**Comment by ma-gu-16** [comment]
> Es werden nur ausgewählte Datenpunkte importiert und nicht alles. Was fehlt dir konkret? Im schlimmsten Fall kannst du es manuell anlegen.

ja hab ich grad gesehen. Es fehlen im Grunde alles für RGBW , dimmer, ct,sat,farbe usw. 


![Screenshot 2020-12-01 124052](https://user-images.githubusercontent.com/22169074/100736088-8a37e600-33d2-11eb-8d9f-51ebc9474c2e.png)

Willst du die noch hinzufügen, oder soll ich es manuell machen ?

**Comment by Zefau** [comment]
@ma-gu-16 added with `v2.1.0-beta.1`.

**Comment by Timmes123** [comment]
> @Timmes123 fehlt von den hier genannten Datenpunkten noch welche in der aktuellen Version des Importers?

@Zefau Sorry für die verspätete Antwort.
Die Datenpunkte die du hast sind jetzt aktuell nur für Steckdosen oder ähnliches mit Leistungsmessung.

Das was @ma-gu-16 beschreibt, ist genau das was ich mit meinem vorherigen Post meinte.
Man kann über Tasmota verschiedenste Geräte/Gewerke einbinden, daher müsste man im Gerät nachschauen, welche Datenpunkte vorhanden sind und dementsprechend entscheiden. Es ist genau so möglich Tür/Fensterkontakte, Feuchtigkeits- oder Temperaturmessgeräte, Beleuchtung usw. einzubinden. Diese hätten dann neben Power auch noch andere Datenpunkte. Das müsste quasi vorher irgendwie gecheckt werden. Was ist vorhanden? -> Gewerk entscheiden -> Datenpunkte entsprechend Gewerk einfügen.
@ma-gu-16 wäre zum Beispiel geholfen, wenn der Importer erkannt hätte, dass es sich um Beleuchtung handelt und du dann einfach deine Beleuchtung Standard Datenpunkte importierst, wie es z.b. bei HUE der fall ist.

**Comment by Zefau** [comment]
Jo klar, aber das kann ich nur, wenn ich die Datenpunkte kenne.

**Comment by Zefau** [comment]
@ma-gu-16  @Timmes123 passt der Import für iobroker.sonoff soweit aus eurer Sicht?

**Comment by ma-gu-16** [comment]
reachability und alive sind identisch, macht aus meiner Sicht keinen Sinn. 

Sonst sieht es gut aus.

**Comment by Bernd9000** [comment]
Meiner Meinung nach macht es kein Sinn Tasmota zu unterstützen.
Wie Timmes123 schon angedeutet hat, Tasmota ist hochflexibel und hat Millionen von möglichen Datenpunkten.
Aber es ist eben beliebt, wer möchte schon gern den Chinesen verraten das er gerade die Haustür öffnet.....

**Comment by Zefau** [comment]
@ma-gu-16 das stimmt, habe ich nun entfernt

@Bernd9000 Tasmata bzw. MQTT und Sonoff verwenden in jarvis dieselbe Routine zum Einlesen von Geräten. Zunächst wird nach bekannten / vordefinierten Geräten gesucht. Sofern nichts gefunden wird, wird alles eingelesen. Dadurch ist dann (leider) sehr viel in jarvis, was ich eigentlich immer vermeiden wollte. Aber damit begegne ich der zu starken Individualität der vorgenannten Adapter.
