### ISSUE TITLE
v3: Keine Sicherungen mehr vorhanden

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#790]
![image](https://user-images.githubusercontent.com/84818934/121248308-96ca5900-c8a3-11eb-8d31-543f69e89f96.png)

**Comment by Zefau** [comment]
Bei mir geht's. Hast du einen Fehler in der Browser-Konsole, wenn du in den ioBroker.jarvis Adapter-Einstellungen bist?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/121785368-c0dc8d80-cbb9-11eb-8c10-10c7ef48aae2.png)

**Comment by Zefau** [comment]
Seltsam. Sieht gut aus. Hast du denn die JSON files unter /opt/iobroker/iobroker-data/jarvis/0 ?

**Comment by mcuiobroker** [comment]
Das scheint ein Browser-Problem zu sein, Chrome zeigt was an, Firefox und Edge nicht.
![image](https://user-images.githubusercontent.com/84818934/121786787-74498000-cbc2-11eb-9aa5-39d49410e966.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/121786854-d73b1700-cbc2-11eb-9981-3213edc389a3.png)

**Comment by Zefau** [comment]
Bei mir geht's nun mit `v3.0.0-alpha.22` sowohl in Firefox als auch in Chrome. Kannst du das bestätigen?

**Comment by mcuiobroker** [comment]
Ja Firefox ok, Chrome ok, Edge nein.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.67`
Es kommen diese Meldungen, vielleicht hilft es?
![image](https://user-images.githubusercontent.com/84818934/132252287-b1c66def-a786-4a3a-8718-d88e808b0afc.png)

![image](https://user-images.githubusercontent.com/84818934/132252318-5e4146b4-cadc-4a12-a035-41348cd3cfb1.png)

![image](https://user-images.githubusercontent.com/84818934/132252342-36b61a05-acbc-47d0-bdf8-b2c8028d00ab.png)

**Comment by Zefau** [comment]
Chrome und FF reichen mir. Edge ist nicht wichtig.

**Comment by mcuiobroker** [comment]
Ich arbeite dauernd mit Edge.

**Comment by Zefau** [comment]
Ich hab den leider nicht installiert, daher kann ich es nicht nachstellen.

Der Code hierfür ist hier
https://github.com/Zefau/ioBroker.jarvis/blob/155b8dd5c554d678e3c6a6b85dafa21d12c2d3c4/admin/index_m.html#L68

sowie hier
https://github.com/Zefau/ioBroker.jarvis/blob/155b8dd5c554d678e3c6a6b85dafa21d12c2d3c4/jarvis.js#L393

**Comment by Zefau** [comment]
Bekommt du die Meldungen `Get backups for...` sowie danach `Got backups for...` in der Browser Konsole?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/132254915-1ab85e08-3bd5-4629-9300-38c2c1b26347.png)

**Comment by Zefau** [comment]
schau nochmal mit Edge unter `v3.0.0-alpha.69`.

**Comment by mcuiobroker** [comment]
Jetzt passt es: Woran lag es denn?
![image](https://user-images.githubusercontent.com/84818934/132257686-a950eafc-9073-4a38-a142-26068e608d8e.png)
Hab alle Browser nochmal getestet -> Passt. Super.

**Comment by mcuiobroker** [comment]
Funktioniert auch mit `v3.0.0-alpha.77`.
