### ISSUE TITLE
v3: Problem mit den Kommas in Secondary State hatten wir auch in v2.2.0 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#791]
Bei NullWerten oder Leer kein Komma davor und Einheit ausblenden

![image](https://user-images.githubusercontent.com/84818934/121775918-85769a80-cb8a-11eb-90fa-bb900f128150.png)
Grundsätzlich erscheint immer ein Komma vor den Werten.
![image](https://user-images.githubusercontent.com/84818934/121775934-9de6b500-cb8a-11eb-8d57-af7fa8b01c7c.png)

**Comment by Zefau** [comment]
Ist es mit der `v3.0.0-alpha.8` besser?

**Comment by mcuiobroker** [comment]
Mit v3.0.0-alpha.8 ist es wesentlich besser geworden:
![image](https://user-images.githubusercontent.com/84818934/121822237-4d607c00-cc9e-11eb-9d13-4c88e8732828.png)
Nur noch bei Leerem Text und 0-Werten 
![image](https://user-images.githubusercontent.com/84818934/121822281-91538100-cc9e-11eb-84ae-66f5659853ad.png)
![image](https://user-images.githubusercontent.com/84818934/121822307-b647f400-cc9e-11eb-8b83-0233dc24c8ec.png)
![image](https://user-images.githubusercontent.com/84818934/121822312-bf38c580-cc9e-11eb-9f48-33c2ff7eb428.png)
Leerer text:
![image](https://user-images.githubusercontent.com/84818934/121822322-d4155900-cc9e-11eb-95ca-74223c737b7d.png)
Und leeren Wert die Einheit verschwinden lassen, so wie in 2.2.0

**Comment by Zefau** [comment]
bitte schau nochmal mit `v3.0.0-alpha.32`.

**Comment by mcuiobroker** [comment]
Bei Leerwerten bleibt das Komma da:
![image](https://user-images.githubusercontent.com/84818934/126224352-d680e771-b5a0-4268-98ca-3c1b7998d9d9.png)
Bei Nullwerten bleibt die Einheit und das Komma da:
![image](https://user-images.githubusercontent.com/84818934/126224419-a657bc6c-4670-4326-8929-eeac8b8308ef.png)

**Comment by Zefau** [comment]
bitte schau nochmal mit `v3.0.0-alpha.33`.

**Comment by mcuiobroker** [comment]
Leerwerte werden noch falsch angezeigt:
![image](https://user-images.githubusercontent.com/84818934/126229977-25c8025a-9d25-4774-b286-8ac0703da98f.png)
Dahinter steht Fehlergrund und der ist ein Text.
![image](https://user-images.githubusercontent.com/84818934/126230233-85330f7e-adb8-469b-a6fb-e4d530f3fa4e.png)

**Comment by Zefau** [comment]
Leerwerte werden raus gesammelt eigentlich. Ist das ein Leerzeichen oder was genau?

**Comment by mcuiobroker** [comment]
Da steht nichts drin, also null?

**Comment by Zefau** [comment]
```
		hasValue(val) {
			return val !== undefined && val !== null && val !== '' && val !== 0 && val !== '0';
		}
```

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.33` bleibt nur noch https://github.com/Zefau/ioBroker.jarvis/issues/791#issuecomment-882875705, aber die zwei aus https://github.com/Zefau/ioBroker.jarvis/issues/791#issuecomment-882846147 sind behoben, oder?

**Comment by mcuiobroker** [comment]
Ja , genauso war es auch schon mit v2.2.0

**Comment by Zefau** [comment]
Ok, also alter Zustand wiederhergestellt, aber noch nicht optimal? 

Bei https://github.com/Zefau/ioBroker.jarvis/issues/791#issuecomment-882875705 handelt es sich um einen validen Wert, der ein Komma hat. Das sollte ich noch hinbekommen.

**Comment by mcuiobroker** [comment]
Vielleicht hilft es in den Code von v2.2.0 zu schauen, wie du es dort gemacht hast?

**Comment by Zefau** [comment]
> Vielleicht hilft es in den Code von v2.2.0 zu schauen, wie du es dort gemacht hast?

Dachte der aktuelle Zustand entspricht dem aus v2.2.0?

**Comment by mcuiobroker** [comment]
Nein. Die Komma Problem sind dort behoben.

**Comment by Zefau** [comment]
Dann haben wir aneinander vorbei geredet. Ich hab es so gelesen, dass es auch in v3 behoben ist?

**Comment by Zefau** [comment]
Nur https://github.com/Zefau/ioBroker.jarvis/issues/791#issuecomment-882875705 ist noch offen, wobei es ja kein Leerwert ist, aber das Komma natürlich falsch gesetzt.

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
Schau nochmal mit `v3.0.0-alpha.36`.

**Comment by mcuiobroker** [comment]
Mach ich, wenn sie da ist.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.36`
![image](https://user-images.githubusercontent.com/84818934/126556144-df5c4142-485c-4388-88b1-9ec1a6aa1382.png)
Jetzt fehlt ein Komma, wenn Fehlergrund gefüllt ist mit einem Text.

**Comment by Zefau** [comment]
Kannst du `v3.0.0-alpha.36` nochmal drüber installieren? Zweiter Versuche ohne neue Versionsnummer.

**Comment by mcuiobroker** [comment]
Jetzt werden die Werte zwar korrekt angezeigt, aber nicht mehr aktualisiert.
Wenn ich F5 (Browser) drücke ist alles richtig. Ändere ich den Wert wird dieser nicht aktualisiert.

**Comment by Zefau** [comment]
Funktioniert bei mir tadellos. Hast du einen Fehler in der Browser Konsole?

**Comment by mcuiobroker** [comment]
Tja, das liegt mal wieder am Browser. Mit Chrome funktioniert es ohne Probleme, mit Edge nicht.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.38`.

**Comment by mcuiobroker** [comment]
Jetzt ist wieder ein Komma zuviel
![jarvis_v300-alpha38-wiederKomma](https://user-images.githubusercontent.com/84818934/126714029-c81804b9-e7ad-41ed-b60a-ed0f3d51d801.gif)

**Comment by Zefau** [comment]
siehe `v3.0.0-alpha.39`

**Comment by mcuiobroker** [comment]
Auch mit .39:
![image](https://user-images.githubusercontent.com/84818934/126716432-b67285c9-8497-4c07-93e5-c0503827fb49.png)

**Comment by Zefau** [comment]
Wie ist der Status mit `v3.0.0-alpha.46` ?

**Comment by mcuiobroker** [comment]
v.46 Kein Unterschied  oben mit v.39. Komma bleibt hinter den 100% stehen.

**Comment by rschneider1509** [comment]
Eine Frage/Anmerkung zum Thema, allerdings leicht Offtopic; wenn gewünscht mache ich einen eigenen Fall auf:
Wenn man die sekundären Datenpunkte anders Färbt, bleibt das Komma im standard Grau (schon in 2.2)

**Comment by Zefau** [comment]
@rschneider1509 korrekt

**Comment by mcuiobroker** [comment]
Nicht ganz?
![image](https://user-images.githubusercontent.com/84818934/133162750-90790bd8-c36b-4925-a3f5-363eff8265b8.png)

**Comment by Zefau** [comment]
oh, stimmt, ist auch laut Code mit in der Färbung inkludiert.

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.0.0-alpha.76`.

**Comment by mcuiobroker** [comment]
.76
![image](https://user-images.githubusercontent.com/84818934/133164539-91056af1-0c7c-4a13-b2f0-704e810babbb.png)

**Comment by mcuiobroker** [comment]
.77
Hier ist jetzt eine Einheit dazugekommen
![image](https://user-images.githubusercontent.com/84818934/133282524-126fafe6-0dee-4d86-aa11-a6b1dea4e07a.png)
Hier ist der Hintergrund an Werten wie oben schon gezeigt:
![image](https://user-images.githubusercontent.com/84818934/133284134-96f8e253-fd63-448a-923d-9bd576796e48.png)
Hier ist die Einstellung für die Anzeigevarainte aber 0 ausblenden -> Komma davor nicht anzeigen:
![image](https://user-images.githubusercontent.com/84818934/133284374-749611ba-a170-43a9-8f3a-e66d69729b7c.png)

-------

Nächster Fall:


![image](https://user-images.githubusercontent.com/84818934/133282600-7e8e22b6-4437-49a0-890d-e3c8c1b95620.png)
Das Komma hat diesen Hintergrund an Werten, vorher stand immer 0,0 dort (was eigentlich richtig war, da man Nullwerte ja in der Anzeigevarainte ausblenden "0":"" soll v2.2.0 ):
![image](https://user-images.githubusercontent.com/84818934/133283728-917dfbe7-53a0-468a-85a7-0223eb64f18d.png)

**Comment by Zefau** [comment]
Okay, jetzt blick ich durch. Ich hab die ganze Zeit `val` (also den Rohwert). Ich stell es nun auf `value` um (also den verarbeiteten Wert mit `display`), dann sollte es passen.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.78`.

**Comment by mcuiobroker** [comment]
`.78`passt nocht nicht:
![image](https://user-images.githubusercontent.com/84818934/133456653-ea8dda0a-e6cf-48c0-907a-f40413ae6069.png)
![image](https://user-images.githubusercontent.com/84818934/133456707-0909fc0a-fa28-4737-b777-0a00e3688c19.png)

**Comment by mcuiobroker** [comment]
Also mit `v3.0.0-alpha.79` passt es. Ich schließe den Punkt, falls noch etwas auffallen sollte, erstelle ich einen neuen.
Danke.
