### ISSUE TITLE
Sonoff-Adapter Probleme mit Jarvis

### ISSUE THREAD

**Issue by KayThe95** [Zefau/ioBroker.jarvis#793]
Ich habe ausschliesslich mit dem Sonoff Adapter Probleme und weiß nicht an was das liegen könnte.
Sobald ich einen anderen Datenpunkt hinzufügen möchte, sehe ich nur rot durchgestrichene Datenpunkte im Sonoff Adapter.

Weiß jemand an was das liegen könnte?

![Unbenannt](https://user-images.githubusercontent.com/59337787/121807512-c20ec880-cc54-11eb-8e05-c6bea1e8d0c0.PNG)

**Comment by Zefau** [comment]
Datenpunkte mit Leerzeichen werden nicht unterstützt

**Comment by KayThe95** [comment]
Vielen Dank das hat das Problem gelöst (;
