### ISSUE TITLE
Absturz nach upgrade auf 2.2.0

### ISSUE THREAD

**Issue by X-Renegade-X** [Zefau/ioBroker.jarvis#794]
Hab grad den 2.1 klassisch installiert, dann über das REpository ubgedatet auf Alpha und direkt auf die 2.2.0.
Sobald ich auf editieren ging, kam folgender Screen

![grafik](https://user-images.githubusercontent.com/78879042/121809557-85939a80-cc5d-11eb-94f7-7500cccfbfe8.png)

**Comment by Zefau** [comment]
Du kannst nicht von 2.1 auf 3.0 gehen und dann wieder zurück. Das gesamte Layout wird auf v3 Struktur konvertiert.

Du musst dein Layout / Geräte aus einem Backup wiedereinspielen.
