### ISSUE TITLE
v3: Überschriften fehlen bzw Widget Labels und Icons

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#795]
Ist mir jetzt erst aufgefallen.
v2.2.0:
![image](https://user-images.githubusercontent.com/84818934/121821614-58191200-cc9a-11eb-81db-83d6eb7e3334.png)
v3:
![image](https://user-images.githubusercontent.com/84818934/121821623-623b1080-cc9a-11eb-895a-956d9de5c84f.png)
Scheint in v3 standardmäßig eingestellt zu sein? Fehler in der Konvertierung zu v3?
![image](https://user-images.githubusercontent.com/84818934/121821666-a62e1580-cc9a-11eb-8a96-656050f22cd9.png)
Ist es entsprechend eingeschaltet sieht es so aus:
![image](https://user-images.githubusercontent.com/84818934/121821710-e7bec080-cc9a-11eb-99ee-15e89e1cc9c4.png)

**Comment by Zefau** [comment]
@mcuiobroker kannst du mit der aktuellen alpha nochmal schauen, ob die Konvertierung nun die Einstellungen (Widget Title / Icon) korrekt übernimmt?

1. jarvis schließen
2. v2 layout in den Datenpunkt `jarvis.0.layout` kopieren
3. jarvis starten und schauen, ob's geht

Wenn du dir vorher das aktuelle v3 Layout sicherst, dann kannst du danach auch einfach wieder direkt zurück gehen.

**Comment by mcuiobroker** [comment]
Es kommt immer die Meldung:
jarvis.0 | 2021-06-19 13:11:50.139 | error | (5032) Cannot configure secure web server, because no certificates found: , ,
Obwohl im web.0 keine secure https definiert ist.
Es erscheint immer timeout. Und er werden nur die devices konvertiert.
![image](https://user-images.githubusercontent.com/84818934/122640606-c7f72480-d100-11eb-9b09-74cd0662d89d.png)

**Comment by Zefau** [comment]
Hast du ein JSON-Beispiel vom v2 Layout mit aktivierten Widget Titel / Icon? Würde das mal bei mir übernehmen und konvertieren. Meine Beispiele funktionieren alle, insofern muss ich was übersehen.

**Comment by mcuiobroker** [comment]
`{
        "id": "dateien8",
        "title": "Dateien",
        "icon": "content-save-cog-outline",
        "columns": [
          [
            {
              "moduleConfig": {
                "thead": [
                  {
                    "label": "date",
                    "align": "left"
                  },
                  {
                    "label": "type",
                    "align": "left"
                  },
                  {
                    "label": "error",
                    "align": "left"
                  }
                ]
              },
              "devices": [
                {
                  "type": "device",
                  "deviceId": "4c7414aa-1d1f-4579-8b88-af593171bc6d",
                  "primaryStateKey": "json"
                }
              ],
              "module": "JsonTable",
              "title": "BackitUp",
              "id": "71affc14-ed24-4b85-9462-61c8693627e8",
              "icon": "iobroker",
              "index": 0
            }
          ],
          [
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "539a17ed-f422-4ba5-994f-cb87ddffc09d",
                  "bodyStateKey": "htmlIcons",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "htmlIcons",
                  "showState": false,
                  "actionElement": null
                }
              ],
              "module": "CustomHTML",
              "title": "Icons",
              "id": "368b23d3-9c1b-4f2c-a975-6ce0ed2692c6",
              "icon": "iobroker",
              "index": 0
            }
          ],
          [
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "2258653e-5ca9-40c9-ba31-ca4124cf60c3",
                  "bodyStateKey": "htmlErstellen",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "htmlErstellen",
                  "showState": false,
                  "actionElement": "SwitchAction"
                }
              ],
              "module": "StateList",
              "title": "HTML Batterien",
              "fullscreen": true,
              "id": "cf44b0cc-e7b3-462a-a06b-eb23e90d9e65",
              "index": 0
            },
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "2258653e-5ca9-40c9-ba31-ca4124cf60c3",
                  "primaryStateKey": "ZustandHTML"
                }
              ],
              "module": "CustomHTML",
              "title": "HTML Batteriezustände",
              "id": "2811704b-1d8e-48c0-887b-2610b03b3c3c",
              "fullscreen": true,
              "index": 1
            },
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "2ef9aacb-8614-4591-9fe2-274aaae22342",
                  "primaryStateKey": "html"
                }
              ],
              "module": "CustomHTML",
              "title": "Adapter Liste",
              "id": "4d4d28b6-47b6-4c51-91c4-d02e2c739ed4",
              "scaleContents": false,
              "minHeight": "",
              "maxHeight": "",
              "icon": "iobroker",
              "index": 2
            }
          ]
        ],
        "index": 8
      },`

**Comment by mcuiobroker** [comment]
Obiges Beispiel TV:

`{
        "title": "TV",
        "icon": "television-classic",
        "id": "tv7",
        "index": 7,
        "columns": [
          [
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "67f1377d-5f8a-4664-98f2-9d63b5652203",
                  "primaryStateKey": "html"
                }
              ],
              "module": "CustomHTML",
              "title": "TV-Sendungen",
              "id": "68473795-bfd3-4c02-ac87-533199617bc2",
              "icon": "television-classic",
              "maxHeight": "",
              "index": 0
            },
            {
              "moduleConfig": {
                "url": "http://192.168.178.89:8082/vis/index.html?TV#JETZT",
                "height": "400"
              },
              "devices": [],
              "module": "iFrame",
              "title": "TV-JETZT",
              "id": "dee9195e-ad9d-4bae-b393-334824b93923",
              "minHeight": "450",
              "index": 1
            }
          ],
          [
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "ea39cc16-cd12-4039-af3a-76a63bbe7cab",
                  "bodyStateKey": "show_logos",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "show_logos",
                  "showState": false,
                  "actionElement": "CheckboxAction",
                  "label": "Logos anzeigen"
                },
                {
                  "type": "device",
                  "deviceId": "ea39cc16-cd12-4039-af3a-76a63bbe7cab",
                  "bodyStateKey": "Zeit",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "Zeit",
                  "showState": true,
                  "actionElement": "DropdownAction",
                  "label": "Zeit"
                },
                {
                  "type": "device",
                  "deviceId": "ea39cc16-cd12-4039-af3a-76a63bbe7cab",
                  "bodyStateKey": "HtmlSet",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "HtmlSet",
                  "showState": false,
                  "actionElement": "IconButtonAction",
                  "label": "HTML Neu"
                },
                {
                  "type": "device",
                  "deviceId": "aa540bd0-f51d-4c16-bcfd-16fbb373dab5",
                  "bodyStateKey": "nextNews",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "nextNews",
                  "showState": false,
                  "actionElement": "IconButtonAction"
                },
                {
                  "type": "device",
                  "deviceId": "aa540bd0-f51d-4c16-bcfd-16fbb373dab5",
                  "bodyStateKey": "progSuche",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "progSuche",
                  "showState": false,
                  "actionElement": "InputAction"
                }
              ],
              "module": "StateList",
              "title": "TV-HTML-Einstellungen",
              "id": "aabf309d-6458-48b0-b233-3b33ff9dfe3b",
              "icon": "television-classic",
              "index": 0
            },
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "group",
                  "name": "Änderung bei nächster Aktualisierung"
                },
                {
                  "type": "device",
                  "deviceId": "501961c6-6b12-44f4-944c-09a816c90a21",
                  "label": "",
                  "bodyStateKey": "Farbe_Überschrift",
                  "actionType": "action",
                  "actionElement": "InputAction",
                  "primaryStateKey": "Farbe_Überschrift",
                  "showState": false,
                  "useInGroup": false,
                  "bodyElement": "LastChangeBody"
                },
                {
                  "type": "device",
                  "deviceId": "501961c6-6b12-44f4-944c-09a816c90a21",
                  "label": "",
                  "actionType": "action",
                  "actionElement": "InputAction",
                  "primaryStateKey": "Farbe_Zeile",
                  "showState": false,
                  "useInGroup": false,
                  "bodyStateKey": "Farbe_Zeile",
                  "bodyElement": "LastChangeBody"
                }
              ],
              "module": "StateList",
              "title": "Farbe",
              "id": "007098ec-26cf-4fb5-a68c-4441cbeceb9d",
              "index": 1
            }
          ],
          [
            {
              "moduleConfig": {},
              "devices": [
                {
                  "type": "device",
                  "deviceId": "ec9b6244-b7ad-4ef2-857e-6585fc7d764a",
                  "bodyStateKey": "Logging_einschalten",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "Logging_einschalten",
                  "showState": false,
                  "actionElement": "SwitchAction"
                },
                {
                  "type": "device",
                  "deviceId": "ec9b6244-b7ad-4ef2-857e-6585fc7d764a",
                  "label": "HTML erneuern",
                  "showState": false,
                  "actionElement": "SwitchAction",
                  "bodyStateKey": "makeHtml",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "makeHtml"
                },
                {
                  "type": "device",
                  "deviceId": "ec9b6244-b7ad-4ef2-857e-6585fc7d764a",
                  "bodyStateKey": "makeHtmlFile",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "makeHtmlFile",
                  "showState": false,
                  "actionElement": "SwitchAction",
                  "label": "HTML speichern"
                },
                {
                  "type": "device",
                  "deviceId": "ec9b6244-b7ad-4ef2-857e-6585fc7d764a",
                  "bodyStateKey": "makeFile",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "makeFile",
                  "showState": false,
                  "actionElement": "SwitchAction",
                  "label": "File speichern",
                  "secondaryStatesKeys": [
                    "Log_Anzahl"
                  ]
                },
                {
                  "type": "device",
                  "deviceId": "ec9b6244-b7ad-4ef2-857e-6585fc7d764a",
                  "label": "HTML falsch",
                  "bodyStateKey": "Log_Html_Wrong",
                  "bodyElement": "LastChangeBody",
                  "primaryStateKey": "Log_Html_Wrong",
                  "showState": true,
                  "actionElement": null
                }
              ],
              "module": "StateList",
              "title": "Logs",
              "id": "5f656d1a-be23-4054-bac5-77d8d5aa3f56",
              "index": 0
            },
            {
              "moduleConfig": {
                "thead": [
                  {
                    "label": "Nr"
                  },
                  {
                    "label": "ZEIT"
                  },
                  {
                    "label": "KANAL"
                  },
                  {
                    "label": "TITEL"
                  }
                ],
                "max": "10"
              },
              "devices": [
                {
                  "type": "device",
                  "deviceId": "aa540bd0-f51d-4c16-bcfd-16fbb373dab5",
                  "primaryStateKey": "nextNewsJSON"
                }
              ],
              "module": "JsonTable",
              "title": "Nachrichten",
              "id": "51971055-ca08-4289-9606-f19c626b412a",
              "index": 1
            }
          ]
        ]
      },`

**Comment by mcuiobroker** [comment]
Überschriften werden entsprechend mit der Konvertierung umgesetzt:
v2:
![image](https://user-images.githubusercontent.com/84818934/126051170-11d56427-0ea0-496f-beef-5ed16a933be8.png)
v3:
![image](https://user-images.githubusercontent.com/84818934/126051174-8789d83c-05aa-4e9b-a70b-4da9ab3b5e08.png)

Auffällt, dass die Icons in v3 größer sind und damit das ganze größer wirkt?
Ansonsten ist das Thema durch.

**Comment by Zefau** [comment]
Solche Individualisierung sollen via CSS erfolgen
