### ISSUE TITLE
Invalid Time Error - nach Wiederherstellung

### ISSUE THREAD

**Issue by KayThe95** [Zefau/ioBroker.jarvis#796]
Ich habe leider nach der Wiederherstellung meiner Jarvis Konfiguration beim Abrufen meines Datenpunktbaumes, folgenden Fehler:

Ich denke das es halt damit zusammenhängt dass das Backup vom 09.06.21 ist...irgendwie steht da irgendwo ne komische Zeit drin.
Gibt es da einen Ansatz wo ich da nachschauen kann?

Vielen Dank für die Mühe vorab.

![image](https://user-images.githubusercontent.com/59337787/121925571-59e7e180-cd3d-11eb-8c60-637e47732a1a.png)

**Comment by Zefau** [comment]
Im Datenpunkt `jarvis.0.layout` stehen alle deine Informationen bzgl. des Layouts. Mittels https://jsonformatter.curiousconcept.com/ bekommst du es lesbar formatiert.

Dann dort nach `DateTime` suchen und den Fehler beheben.

**Comment by KayThe95** [comment]
Danke, damit habe ich das Problem lösen können.

**Comment by KayThe95** [comment]
Leider besteht das Problem wieder. Ganz seltsam. Zu DateTime finde ich auch nichts im layout-Objekt..

**Comment by AFPass** [comment]
Nach dem ich von v3 wieder auf v2 bin und ein neues Gerät anlegen will, bekomme ich auch den Fehler wenn ich einen Datenpunkt zuweisen möchte.

<img width="1106" alt="image" src="https://user-images.githubusercontent.com/13101074/130302498-faa97bff-97c9-4279-ba3d-9bdfa9ef3f3f.png">

**Comment by Zefau** [comment]
Warum bist du denn wieder von v3 weg?

**Comment by AFPass** [comment]
Weil ich die GUI eigentlich zum steuern von ioBroker nehmen möchte. Dazu nehme ich mein Telefon. Dort passt Layout noch nicht. Zum Beispiel die Schrift geht über die Boxen. Die Boxen sind nur halbe Bildschirmbreite.

Ich würde gerne Testen und Dich unterstützen und v3 Testen und Fehler melden. Kann man v2 und v3 parallel installieren und 2 Jarvis Instanzen nutzen?

**Comment by Zefau** [comment]
Das geht technisch aufgrund von iobroker leider nicht. Du brauchst zwei Installationen. Geht mit keinem Adapter.

Ich nehme heute Abend die mobile Optimierung auf die Agenda.

**Comment by AFPass** [comment]
Hab ich schon vermutet. 
mal sehen, vielleicht gehe ich heute nochmal auf 3.

**Comment by Zefau** [comment]
Mit `v3.0.0-alpha.55` hab ich ein paar Optimierungen in der mobilen Ansicht gemacht. Kannst du dir das mal anschauen?

Feedback gerne via https://github.com/Zefau/ioBroker.jarvis/issues/805

**Comment by AFPass** [comment]
Ok. Mache ich

**Comment by braintr84** [comment]
Hi, hab das selbe Problem, bin auf v3 gegangen, jedoch zeigt mein IPAD 4 dann nur noch einen weißen Bildschirm im Safari, Chrome oder anderer Browser kann nicht mehr geladen werden ( IOS outdated) da es aber für die Anzeige absolut ausreichend ist, möchte ich kein neues Tab kaufen müssen, kann mir jemand helfen ? danke
