### ISSUE TITLE
v3: Menü zu anderen Seiten und Konfiguration verschwindet, wenn nur ein Tab auf der Seite

### ISSUE THREAD

**Issue by noffycws** [Zefau/ioBroker.jarvis#797]
Wenn man auf einer Seite nur ein Tab mit Widgets hat, aber mehrere andere Seiten vorhanden sind, dann verschwindet das Menü (drei Balken) und man hat keine Möglichkeit in die Konfiguration zu wechseln und dort zu ändern.

Widget-Tab ist nicht als Fullscreen konfiguriert.

v3.0.0-alpha9

**Comment by Zefau** [comment]
sollte mit ` v3.0.0-alpha.10` behoben sein

**Comment by noffycws** [comment]
Ja, funktioniert als Lösung in `alpha.10`
