### ISSUE TITLE
v3: Widget StateList gibt nicht Label nicht aus

### ISSUE THREAD

**Issue by noffycws** [Zefau/ioBroker.jarvis#798]
v3.0.0.-alpha9:

In der Konfiguration ist im Widget StateList jeweils ein Label angegeben:
![image](https://user-images.githubusercontent.com/78761005/122565276-90c43d00-d046-11eb-9ef1-a607f59f733c.png)

In der Anzeige wird jedoch jeweils nur das Label des Gerätenamens und die Werte angezeigt:
![image](https://user-images.githubusercontent.com/78761005/122565563-ec8ec600-d046-11eb-814e-5e7d60ce2292.png)

Hier noch die Konfiguration des Gerätes:
![image](https://user-images.githubusercontent.com/78761005/122565480-d254e800-d046-11eb-98ed-97950d0ac178.png)

**Comment by Zefau** [comment]
sollte mit ` v3.0.0-alpha.10` behoben sein

**Comment by noffycws** [comment]
Ja, funktioniert mit ´alpha.10´
