### ISSUE TITLE
v3: Objekt wird nicht immer mit Trigger-Element dargestellt

### ISSUE THREAD

**Issue by noffycws** [Zefau/ioBroker.jarvis#800]
`alpha.09`, `alpha.10`

Ein Datenpunkt wird in mehreren Widgets verwendet. Einmal wird das Trigger-Element angeboten und einmal nicht:
![image](https://user-images.githubusercontent.com/78761005/122688221-48aa4380-d21b-11eb-8a74-c37f75e106fa.png)

Das gilt auch für die Konfigurationen (Modul StateList).

Hier wird das Trigger-Element in der Layout/Widget-Konfiguration angeboten:
![image](https://user-images.githubusercontent.com/78761005/122688264-9e7eeb80-d21b-11eb-93ed-38492a0a254a.png)

Hier nicht (egal, ob man den BodyState angibt oder nicht):
![image](https://user-images.githubusercontent.com/78761005/122688298-c40bf500-d21b-11eb-96d1-510ff1d94f35.png)

Und hier nochmal die Konfiguration des Gerätes mit dem einen Datenpunkt:
![image](https://user-images.githubusercontent.com/78761005/122688451-85c30580-d21c-11eb-8dd9-4f09d8e28dcd.png)
**btw:** Ist es normal, dass `Datenpunkt (Anzeige)` und `Datenpunkt (Trigger)` doppelt dargestellt wird?

Der Fehler tritt auch bei anderen Geräten auf. Das o.g. Gerät mit Datenpunkt ist nur ein Beispiel. Liegt auch nicht an Homematic, tritt auch bei Hue-Geräten auf.

Darüber hinaus wird das Trigger-Element in der Geräte-Konfiguration nicht gespeichert (`alpha.10`). Das führt zu folgender Anzeige im PopUp zu dem Gerät:
![image](https://user-images.githubusercontent.com/78761005/122688495-ccb0fb00-d21c-11eb-97bf-03d5613a51d6.png)

Hier wird auch nicht das Geräte-Label ausgegeben.

**Comment by Zefau** [comment]
Hast du einen Fehler in der Browser Konsole (F12)?

**Comment by noffycws** [comment]
Als Fehler kommt nur das raus:

`Failed to decode downloaded font: https://192.168.XX.XX:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/a89332bf-56c9-495a-84c4-c94720b76b90:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/a89332bf-56c9-495a-84c4-c94720b76b90:1 Failed to decode downloaded font: https://192.168.XX.XX:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
index.html#/a89332bf-56c9-495a-84c4-c94720b76b90:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/a89332bf-56c9-495a-84c4-c94720b76b90:1 Failed to decode downloaded font: https://192.168.XX.XX:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/a89332bf-56c9-495a-84c4-c94720b76b90:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size
index.html#/a89332bf-56c9-495a-84c4-c94720b76b90:1 Failed to decode downloaded font: https://192.168.XX.XX:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
index.html#/a89332bf-56c9-495a-84c4-c94720b76b90:1 OTS parsing error: Size of decompressed WOFF 2.0 is less than compressed size`

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.0-alpha.20`.

**Comment by noffycws** [comment]
getestet mit `alpha.22` ... dort behoben. Man muss dann nur etwas nacharbeiten und die Trigger-Elemente neu auswählen.
