### ISSUE TITLE
v3: Keine sprechende ID für Pages und Tabs in URL

### ISSUE THREAD

**Issue by noffycws** [Zefau/ioBroker.jarvis#801]
`alpha.10`

Für die einzelnen Pages und Tabs werden nur die GUID als ID generiert und in der URL angezeigt. Nicht wie bei `v.2.2.0` ein sprechender Name (bspw. `dashboard0`), mit dem man auch per Direkt-Link auf eine Seite usw. zugreifen konnte.

Um per Deeplink auf eine Seite / Tab zugreifen zu können wäre folgende Struktur für die URL denkenswert:
`index.html#/seitenname/tabname`

Am Beispiel:
Seitenname = Dashboard
Tabname = Geräte
Ergibt die URL = `index.html#/dashboard/geraete`

Für Fälle wie `Klima / Geräte / Licht` werden die Trenner durch `-` ersetzt und Leerzeichen gelöscht. Ergibt also `klima-geraete-licht`

Ggf. kann man die ID's für die URL sogar selbst vergeben. Problematisch wäre nur, wenn es einen URL-Kenner bereits gibt (bspw. `configuration`

**Comment by Zefau** [comment]
Der Name ist nicht eindeutig, insofern wird es das nicht mehr geben. Du kannst mittels Tab ID hin und her springen bzw.  auch direkt per Bookmark auf einen bestimmten Tab springen. Die Seite wird dabei anhand der Tab ID automatisch ermittelt.
