### ISSUE TITLE
v3: MediaPlayer

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#804]
add missing options
- [x] shuffle
- [x] repeat

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/770#issuecomment-855452189_
> hat man einmal einen Player ausgewählt auf der Seite und die Seite wird aktualisiert, so dauert es ca 7 Sekunden bis der Media Player mit Daten gefültt wird?
Beim Umschalten von TAB zu TAB und wieder zurück verliert der MediaPlayer seine Daten, ist wieder ganz Blau und es dauert wieder 7 Sekunden bis die Daten da sind.

**Comment by mcuiobroker** [comment]
Wenn du an das Modul ran gehst, würde ich vorschlagen, dass du dort auch ein Art Dropliste für die unterschiedlichen Felder zulässt  bzw definierst:
    Feld                                                                                               Dropliste (JSON)
1. alexa2.0.Echo-Devices.xxx.Music-Provider.Amazon-Music           {"Helene Fischer":"Helene Fischer", "POP":"POP",...}
2. alexa2.0.Echo-Devices.xxx.Music-Provider.Amazon-Music-Playlist

![image](https://user-images.githubusercontent.com/84818934/126000083-2673f32e-4786-4973-9579-61b6a17ccf7d.png)


Diese Felder als Auswahl, so dass man dann nur die Listen als Drop erstellt, die man haben möchte.
Als Vorschlag

**Comment by Zefau** [comment]
Was steht denn in den Datenpunkten drin, die du da im Screenshot hast?

**Comment by mcuiobroker** [comment]
Ich persönlich nutze meistens  alexa2.0.Echo-Devices.GXXX.Music-Provider.TuneIn: radio ffn
oder
alexa2.0.Echo-Devices.GXXX.Music-Provider.Amazon-Music: Helene Fischer 
oder direkt der Titel 
alexa2.0.Echo-Devices.GXXX.Music-Provider.Amazon-Music: Atemlos

**Comment by Zefau** [comment]
Das Feld ist Freitext und spielt dann das ab was drin steht?

**Comment by mcuiobroker** [comment]
Ja

**Comment by Zefau** [comment]
@mcuiobroker nutzt du das Widget eigl. aktiv? Passt das soweit wie es aktuell implementiert ist (vorbehaltlich der offenen Feature Requests)?

**Comment by mcuiobroker** [comment]
Also ich habe es nochmal getestet. Ich musste F5 drücken, damit ich das laufende Programm sehe. Sonst funktioniert es: man kann den Raum auswählen, man kann starten, stoppen und bei Titelauswahl weiter und zurückgehen.
Man muss aber noch extra ein DP anlegen, damit Alexa einen Titel abspielt oder einen Radio-Sender startet. Das sollte zukünftig in einem Popup einstellbar sein. Die einzelnen Optionen könnte man dann im Widget definieren.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.127`
Auf dem Handy wird es so angezeigt:
![image](https://user-images.githubusercontent.com/84818934/142702561-76efc0a3-2dd2-42d0-a238-f2883c14e4cf.png)
Das letzte Element wird gar nicht mehr angezeigt und der Text fehlt auch. Den Typ, welcher Echo das ist, weiß man, braucht man eigentlich nicht als Info?
Dauer zum Laden nachdem Refresh 5 Sekunden.

**Comment by mcuiobroker** [comment]
Vielleicht kann man es für das Volume nutzen?
![image](https://user-images.githubusercontent.com/84818934/143295166-8eea2a10-6ac9-4ea3-98ef-426dc426509e.png)

**Comment by Zefau** [comment]
Da sind nun viele neue Sachen bei. Die werden mit https://github.com/Zefau/ioBroker.jarvis/issues/616 umgesetzt.

Mir geht es nur darum, dass das was bereits implementiert funktioniert.
Also insbesondere F5 und Handy sollte mit `v3.0.0-rc.1` wieder passen.
