### ISSUE TITLE
v3: Optimize mobile layout

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#805]
_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/770#issuecomment-856123515_
> Benachrichtigungen können auf dem Tablet nicht geschlossen werden, wenn man mit einem Wisch nach links zufälllig diese geöffnet hat. Sie werden nur teilweise angezeigt. Man muss danach den Browser refreshen, sonst tut sich da nichts:

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/803#issuecomment-877869002

**Comment by mcuiobroker** [comment]
Zurzeit mit `v3.0.0-alpha.28`ist es so. Hat man das Benachrichtigungsfenster mit einem Wisch von rechts nach links geöffnet, kann man das Benachritigungsfenster mit einem Wisch von links nach rechts wieder schließen, wenn man nicht mit dem Finger auf dem ganzen Benachrichtigungsfeld ist. Man kann es aber nicht mit dem "Dreieck" "Pfeil" schließen.

**Comment by mcuiobroker** [comment]
Ich schreib es mal hier rein:
![image](https://user-images.githubusercontent.com/84818934/126000804-6dfffe89-bd14-485a-b58f-6fc9c17e65f4.png)

Die Abstände zwischen den Statelist-Einträgen sind ungünstig. 
![image](https://user-images.githubusercontent.com/84818934/126000922-349cd66d-a4e5-4010-9ec3-68630a4fdbb2.png)

Der Abstand hier ist zu groß.
![image](https://user-images.githubusercontent.com/84818934/126000954-ed20f644-4f44-48e5-a403-ec08949780cc.png)

Der Abstand zwischen den Schaltern und Secondary ist zu klein.
Da es aber eine subjektive Einschätzung, sollte es einstellbar sein. Dann kann es jeder machen wie er es möchte.

**Comment by mcuiobroker** [comment]
Tab-Leiste verschwindet bei längeren Seiten, ab ca 50% der Seitenlänge, wenn man nach unten scrollt.
![image](https://user-images.githubusercontent.com/84818934/126003375-4737bfe7-f960-4d2e-96d8-a8d42cc1e225.png)
Soll das so? Man muss dann erst wieder nach oben scrollen, um ein TAB-Wechsel machen zu können.

**Comment by Zefau** [comment]
Soll so, ja. Kannst du in den Theme-Einstellungen auch ändern.

**Comment by mcuiobroker** [comment]
Mit `v3.0.0-alpha.29`ist das Menue minimiert dauernd da:
![image](https://user-images.githubusercontent.com/84818934/126048981-32fa3b78-8b7e-4000-a912-35d76eaf2e4a.png)
Das vorherige mit den drei Strichen war besser, da man so wieder Anzeige-Platz "verschwendet"?

**Comment by Zefau** [comment]
Dann in den Einstellungen umstellen.

**Comment by mcuiobroker** [comment]
Hier muss man es umstellen:
![image](https://user-images.githubusercontent.com/84818934/126549781-8da73c7a-c017-441b-8ff9-933178890b30.png)

**Comment by Zefau** [comment]
Erste Optimierungen mit `v3.0.0-alpha.55`.

**Comment by WW1983** [comment]
Wäre schön wenn man den Button "more" ausblenden und stattdessen wie bei der Version 2 scrollen könnte

![image](https://user-images.githubusercontent.com/56581564/130418220-3372a865-8eee-4074-9141-1cf7feb859e8.jpeg)

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.59` implementiert, siehe neue Option in den Einstellungen

**Comment by Zefau** [comment]
Gibt es noch weitere Verbesserungspunkte bzgl. der mobilen Ansicht?

**Comment by WW1983** [comment]
Mit der aktuellen Version komme ich nicht in die Einstellungen. Dafür fehlt der Button:
![image](https://user-images.githubusercontent.com/56581564/130562064-45c7013e-f1f6-4c38-9c86-9b032493759f.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/906

**Comment by mcuiobroker** [comment]
`3.0.0-alpha.60`
TAB-Selektionsfläche nicht symmetrisch
![image](https://user-images.githubusercontent.com/84818934/131233444-a1d11588-fa53-4028-a05e-38fc2f75d42a.png)

> Normale Anzeige:

![Screenshot_20210829-002734_Chrome](https://user-images.githubusercontent.com/84818934/131233475-10ae3153-4f10-4c41-9a24-e282ffcb0ebd.jpg)

> Werte auf der rechten Seite fehlen, ohne Änderung im Layout

![Screenshot_20210829-002725_Chrome](https://user-images.githubusercontent.com/84818934/131233479-4369b0e7-5482-429d-bdc0-49e36757110d.jpg)

> HomekitTyle Elemente werden gar nicht angezeigt, auf anderer Seite schon?

![Screenshot_20210829-002711_Chrome](https://user-images.githubusercontent.com/84818934/131233500-41566426-f3d7-44d8-add1-07cad5416b4e.jpg)

![Screenshot_20210829-002658_Chrome](https://user-images.githubusercontent.com/84818934/131233528-ede23f9a-d278-4a1b-b5a4-55bd7048c243.jpg)

**Comment by RkcCorian** [comment]
@WW1983 : Wie hast Du das mit dem Hintergrundbild gemacht, sowie Luftfeuchtigkeitskachel, etc. Sieht echt geil aus. Da dies hier aber vermutlich nicht der richtige Ort ist, ich aber nicht weiß wie ich Dich sonst und wo kontaktieren kann wäre ich auch für die Info dankbar 🙈
@Zefau : Saugeil was man mit JARVIS alles machen kann, vielen Dank! Hab bereits gespendet 😁

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.61` 
iFrame : http://192.168.178.89:8082/vis/index.html?TV#JETZT wird auf dem PC dargestellt, auf dem Handy nicht (drehende Kreise, von VIS)

**Comment by Zefau** [comment]
auf allen Browsern auf dem Handy? Ich wüsste gar nicht, was ich da als Entwickler anders machen soll. Ich unterscheide bei iFrame nicht zwischen Desktop oder Mobil. Hast du mal mit der neuen Sandbox-Option gespielt?

**Comment by mcuiobroker** [comment]
Sandbox ausgeschaltet -> keine Änderung.

**Comment by mcuiobroker** [comment]
Ist grundsätzlich ein Problem mit Chrome auch auf dem PC:
![image](https://user-images.githubusercontent.com/84818934/131896062-afe2211c-8a54-4528-9161-8ae300706073.png)

![image](https://user-images.githubusercontent.com/84818934/131896118-5896254e-b2e9-4b61-87f5-ffff366b2f5f.png)

**Comment by mcuiobroker** [comment]
Dieser Fehler kommt in allen Browsern: 
Edge:
![image](https://user-images.githubusercontent.com/84818934/131897097-22140b60-6ba3-4b27-bc53-712cfeef5b51.png)
Firefox:
![image](https://user-images.githubusercontent.com/84818934/131897256-4ceb4556-e89c-4410-b01d-f568d9293b86.png)
Chrome:
![image](https://user-images.githubusercontent.com/84818934/131897319-b7d6bbea-3394-4d80-ad2f-bdee195ab300.png)

**Comment by Zefau** [comment]
Der Paypal Fehler hat damit nichts zu tun. Den bekomme ich auch nicht weg. Ist für den Paypal-Button auf der Account-Übersicht (noch nicht freigeschaltet).

**Comment by Zefau** [comment]
Du hast zu viele iFrame drin, die Fehler produzieren. Der `localStorage` Fehler ist nicht von jarvis, sondern von vis. Siehst du auch in der URL. Der Fehler von `widgets.min.js` kommt ebenfalls nicht von jarvis, sondern einem iFrame. Die müsstest du reparieren, dann geht's möglicherweise.

**Comment by mcuiobroker** [comment]
Die Fehler kommen ja nur mit Chrome. Ich hab jetzt mal iobroker fix laufen lassen. Sonst wüste ich nicht, was ich noch reparieren kann.

**Comment by mcuiobroker** [comment]
Aufgefallen: Bei Verkleinerung der Breite auf dem PC: Aus 3 Spalten werden direkt 1.
![v3-alpha61-Verkleinerung direkt von 3 auf 1 Spalten](https://user-images.githubusercontent.com/84818934/131902505-b325a67b-788a-4444-9925-a575e650e520.gif)

**Comment by Zefau** [comment]
> Die Fehler kommen ja nur mit Chrome. Ich hab jetzt mal iobroker fix laufen lassen. Sonst wüsste ich nicht, was ich noch reparieren kann.

Die vis-Seite selbst ist defekt. Dort tritt ja der Fehler auf. Wenn du die vis-Seite direkt öffnest, wirst du den / die Fehler ebenfalls in der Browser-Konsole vorfinden.

**Comment by mcuiobroker** [comment]
vis-Seite meldet andere Fehler, aber keine Zugriffsfehler. localstorage usw.

**Comment by mcuiobroker** [comment]
mit `v3.0.0-alpha.63`wird man den dense-mode ausgeschaltet -> Icon und Label übereinander die erste Widget-Zeile verdeckt:
![image](https://user-images.githubusercontent.com/84818934/132140929-88852f7a-dd8e-4883-bd6f-d2e8d5fbada7.png)

**Comment by mcuiobroker** [comment]
'v3.0.0-alpha.63`
collapse Tabs ausgeschaltet
![image](https://user-images.githubusercontent.com/84818934/132141022-47353fad-60bd-4011-8286-634e0393df8f.png)
-> bei mehreren Tabs erscheint auf dem Handy rechts keine Glocke mehr direkt, erst wenn man ganz nach rechts wischt kommt auch die Glocke. Diese sollte aber immer zu sehen sein?

**Comment by RkcCorian** [comment]
@zefau: Überlagerung auch bei mir: 
![image](https://user-images.githubusercontent.com/79741077/132141229-0823c639-42b3-4803-b819-a119656120f2.png)

**Comment by mcuiobroker** [comment]
Würde vorschlagen wir machen hier Schluss und aus den offenen Punkten - >Einzelpunkte? Es wird unübersichtlich?

**Comment by RkcCorian** [comment]
@mcuiobroker : Hast Du für den folgenden Punkt bereits ein neues Issue angelegt?

> mit `v3.0.0-alpha.63`wird wenn man den dense-mode ausgeschaltet -> Icon und Label übereinander die erste Widget-Zeile verdeckt:
> ![image](https://user-images.githubusercontent.com/84818934/132140929-88852f7a-dd8e-4883-bd6f-d2e8d5fbada7.png)

**Comment by mcuiobroker** [comment]
Nein, noch nicht wollte erst Fragen. Kann ich aber machen.

**Comment by Zefau** [comment]
ist alles einzeln angelegt, kann das Issue dann zu?

**Comment by mcuiobroker** [comment]
Ja kann vorerst geschlossen werden.
