### ISSUE TITLE
v3: Connection issues

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#806]
_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/770#issuecomment-856123515_
>  Client Connected wird nicht erkannt: alle clients sind als nicht connected dargestellt, obwohl einer connected ist
EDIT: Liegt anscheinend am Browser (Fully Kiosk Browser(Android) und Firefox und Chrome (PC) funktionieren, Edge funktioniert nicht)
Wenn man von einem Gerät mit unterschiedlichen Browsern zugreift, werden dann die Nachrichten noch korrekt übermittelt?

**Comment by Zefau** [comment]
- [ ] Fully Kiosk Browser
- [x] Wenn man von einem Gerät mit unterschiedlichen Browsern zugreift, werden dann die Nachrichten noch korrekt übermittelt?

**Comment by mcuiobroker** [comment]
Hab 3 Browser parallel laufen lassen auf dem PC: Edge,Chrome,Firefox -> Alle zeigen korrekte Werte an zeitgleich, auch nach Wechsel der TABs. Unter Nachrichten hast du nicht Notifications verstanden, denn die kann ich momentan nicht testen, aufgrund der Glockenproblematik.

**Comment by mcuiobroker** [comment]
jarvis.0.clients.ffff192-168-178-34.connected wechselt bei v3.0.0-alpha.22 hinundher false/true, obwohl 3 Browser verbunden sind.
Im Useragent steht: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.64

**Comment by mcuiobroker** [comment]
Wird dies schon unterstützt? jarvis.0.clients.ffff192-168-178-34.newNotifications In welcher Form muss man da die Eingaben machen?

**Comment by mcuiobroker** [comment]
jarvis.0.info.connected wird nicht gefüllt
![image](https://user-images.githubusercontent.com/84818934/124626514-0883cb80-de7f-11eb-9ea0-0c9e98e91d8b.png)

**Comment by Zefau** [comment]
@mcuiobroker der Fully Browser funktioniert bei mir bzgl. des Online-Status mit `v3.0.0-alpha.23`. Kannst du das bestätigen?

Wenn nicht: Welcher User Agent wird bei dir angezeigt?
Bei mir:
```
Mozilla/5.0 (Linux; Android 10; H8324 Build/52.1.A.3.49; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Mobile Safari/537.36
```

**Comment by mcuiobroker** [comment]
Grundsätzlich funktioniert es. Komisch ist nur das er alle Browsertypen anzeigt.
Fully Browser: 
`Mozilla/5.0 (Linux; Android 8.1.0; SM-T580 Build/M1AJQ; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/91.0.4472.120 Safari/537.36`
Windows 10
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.67`
So wie es aussieht werden alle Browsertypen, die auf dem System installiert wurden angezeigt, nicht nur der aktive Browser.

**Comment by Zefau** [comment]
Kannst du mal unter https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_nav_useragent prüfen, was dort angezeigt wird? Sind es dort andere ?

**Comment by Zefau** [comment]
Auf die installierten Browser im System kann ich nicht zugreifen. Nur auf den aktiven.

Das überall Mozilla steht, ist hier erklärt: https://de.wikipedia.org/wiki/User_Agent#Mozilla-Standard

**Comment by Zefau** [comment]
Zeigt ioBroker.vis was anderes an?

**Comment by mcuiobroker** [comment]
https://stackoverflow.com/questions/9847580/how-to-detect-safari-chrome-ie-firefox-and-opera-browser

![image](https://user-images.githubusercontent.com/84818934/125514491-418eeaa1-e795-4190-87fc-9c15d8f43351.png)

**Comment by mcuiobroker** [comment]
Vis zeigt gar nichts an. Sonst sind die Einträge auch mit w3schools identisch.

**Comment by Zefau** [comment]
Also passt dann so?

**Comment by mcuiobroker** [comment]
Ich würde es als offenen Punkt für v3.x.x halten, in Bezug auf die genaue Feststellung vom Browser. Also damit man auch erkennen kann welcher Browsertyp geöffnet ist. Ist aber nicht unbedingt vorrangig, da die Funktionalität für den einzelnen Browser IP-bezogen da ist. Somit kannst du gerne diesen Punkt schließen, bzw ihn als Feature Request einordnen.

**Comment by Zefau** [comment]
Schau dir nochmal `v3.0.0-alpha.28` an. Dort gibt es nun einen State `jarvis.0.clients.XYZ.userBrowser` mit mehr Details (im JSON Format). Bei mir:
```
{
   "description":"Firefox 90.0 on Windows 10 64-bit",
   "layout":"Gecko",
   "manufacturer":null,
   "name":"Firefox",
   "prerelease":null,
   "product":null,
   "ua":"Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0",
   "version":"90.0",
   "os":{
      "architecture":64,
      "family":"Windows",
      "version":"10"
   }
}
```

**Comment by mcuiobroker** [comment]
Ja. Passt. Super. Danke.

**Comment by mcuiobroker** [comment]
Aufgrund der vielen Einträge auch zu einer IP-Adresse, kommt die Frage auf, wann wird eine neue ID für den einzelnen Browser angelegt? Bei jedem Browser-Update? Welche Kennwerte sind entscheidend, damit eine neue ID entsteht?
![image](https://user-images.githubusercontent.com/84818934/129350533-46534245-2280-41ca-ab3b-ce1690d7253d.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/blob/1e2a9c9219e4723211330a55f01c0a9cd34ccb9f/lib/websocket.io.js#L236

IP und User Agent

**Comment by Zefau** [comment]
Wie viele Browser nutzt du denn mit der 34iger IP?

**Comment by mcuiobroker** [comment]
Edge, Chrome, Firefox (PC) 
Kann es evtl damit zusammenhängen, da ich ja auf dem Testsystem immer wieder von v2 auf v3 das Update durchgeführt habe, dass diese Connections vom alten v3 dann nicht mehr erkannt werden? Ich könnte mir vorstellen, dass es damit zu tun hat?

**Comment by Zefau** [comment]
Die User Agents werden ja auch in den Objekten gespeichert. Kannst du die mal vergleichen? Also von zwei Einträgen mit identischer IP und identischem Browser, was sich dort im User Agent String unterscheidet?

**Comment by mcuiobroker** [comment]
Das sind alle Einträge zur IP 34:
`Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.62
Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:90.0) Gecko/20100101 Firefox/90.0
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36 Edg/91.0.864.70Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36 Edg/92.0.902.67
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36 Edg/92.0.902.55
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.107 Safari/537.36
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.164 Safari/537.36 Edg/91.0.864.71`

**Comment by mcuiobroker** [comment]
Mit `v3.0.0-alpha.61` kommt eine Meldung hoch:


<html>
<body>


jarvis.0 | 2021-09-02 18:05:46.927 | warn | (1352) State "jarvis.0.clients.69aeb6e9-5fc9-50a3-ac6b-f3e2c7f1e57b.connected" has no existing object, this might lead to an error in future versions
-- | -- | -- | --



</body>
</html>

In den Objekten stehen nicht die sonstigen Elemente:

![image](https://user-images.githubusercontent.com/84818934/131887493-bc63fa68-5c27-4847-a98d-42a83d50b5fb.png)

Er nutzt auch nicht die schon vorhandenen Einträge zur IP.

Im DP: jarvis.0.clients.connected steht:
{"69aeb6e9-5fc9-50a3-ac6b-f3e2c7f1e57b":{"user-agent":"Mozilla/5.0 (Linux; Android 9; SM-G955F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.62 Mobile Safari/537.36","ip":"::ffff:192.168.178.58","id":"69aeb6e9-5fc9-50a3-ac6b-f3e2c7f1e57b"}}

Nur im Zusammenhang mit dem Handy: .58 /. 34 PC kommt keine Meldung:
<html>
<body>


jarvis.0 | 2021-09-02 19:05:11.286 | info | (1352) Client with IP ::ffff:192.168.178.58 connected
-- | -- | -- | --
jarvis.0 | 2021-09-02 18:05:46.927 | warn | (1352) State "jarvis.0.clients.69aeb6e9-5fc9-50a3-ac6b-f3e2c7f1e57b.connected" has no existing object, this might lead to an error in future versions
jarvis.0 | 2021-09-02 18:00:54.907 | info | (1352) Client with IP ::ffff:192.168.178.58 connected
jarvis.0 | 2021-09-02 17:49:21.658 | info | (1352) Client with IP ::ffff:192.168.178.34 connected
jarvis.0 | 2021-09-02 16:49:12.066 | info | (1352) Client with IP ::ffff:192.168.178.34 connected


</body>
</html>
