### ISSUE TITLE
v3: AdapterStatus

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#807]
_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/770#issuecomment-866361746_
> Bei gestoppten Adaptern dreht er Dauerrunden:
> Zeigt kurz x an und dreht dann dauerschleife, aber nur bei einigen:
![image](https://user-images.githubusercontent.com/84818934/123004468-eab16380-d3b4-11eb-8cf4-ded28ee7f71e.png)

**Comment by Zefau** [comment]
@mcuiobroker should finally be resolved with `v3.0.0-alpha.23`.

**Comment by mcuiobroker** [comment]
Keine Ahnung woran es gelegen hat, aber plötzlich nach einer Weile waren die Adapter weg in der Anzeige:
![jarvisv300-alpha23-adapter](https://user-images.githubusercontent.com/84818934/125211904-1637b780-e2aa-11eb-81ba-22abfc402d23.gif)

**Comment by Zefau** [comment]
Fehler im Log?

**Comment by mcuiobroker** [comment]
Grundsätzlichen Fehler gab es, ob es mit dem Adapterstatus zu tun hat?
`
<html>
<body>


jarvis.0 | 2021-07-12 00:21:40.370 | error | (31192) Cannot read property 'emit' of undefined
-- | -- | -- | --
jarvis.0 | 2021-07-12 00:21:40.369 | error | at processImmediate (internal/timers.js:463:21)
jarvis.0 | 2021-07-12 00:21:40.369 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:312:41)
jarvis.0 | 2021-07-12 00:21:40.369 | error | (31192) TypeError: Cannot read property 'emit' of undefined
jarvis.0 | 2021-07-12 00:21:40.368 | error | (31192) uncaught exception: Cannot read property 'emit' of undefined
jarvis.0 | 2021-07-12 00:21:40.363 | error | (31192) Cannot read property 'emit' of undefined
jarvis.0 | 2021-07-12 00:21:40.362 | error | at processImmediate (internal/timers.js:463:21)
jarvis.0 | 2021-07-12 00:21:40.362 | error | at Immediate.<anonymous> (/opt/iobroker/node_modules/iobroker.jarvis/jarvis.js:312:41)
jarvis.0 | 2021-07-12 00:21:40.362 | error | (31192) TypeError: Cannot read property 'emit' of undefined
jarvis.0 | 2021-07-12 00:21:40.349 | error | (31192) uncaught exception: Cannot read property 'emit' of undefined


</body>
</html>`

**Comment by mcuiobroker** [comment]
In der Konsole gibt es auf der Seite mit dem Adapterstatus folgende Fehler:
`Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.168.178.89:8082/lib/js/socket.io.js.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404,net::ERR_HTTP_RESPONSE_CODE_FAILURE
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.168.178.70:8082/jarvis/js/vendor.743d07b7.js.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404,net::ERR_HTTP_RESPONSE_CODE_FAILURE
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.168.178.70:8082/jarvis/js/app.6c2c94f9.js.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404,net::ERR_HTTP_RESPONSE_CODE_FAILURE
Fehler beim Laden der Quell Zuordnung durch devtools: Der Inhalt für http://192.168.178.70:8082/jarvis/js/2.15faab94.js.map konnte nicht geladen werden: HTTP Fehler: Statuscode 404,net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.25`.

**Comment by mcuiobroker** [comment]
js-controller ist in der Liste der Adapter-Aktualisierungen aber nicht in der Liste?
![image](https://user-images.githubusercontent.com/84818934/125360747-9c1c3700-e36c-11eb-8585-1964ba5e1d59.png)

![image](https://user-images.githubusercontent.com/84818934/125360690-8b6bc100-e36c-11eb-9a2d-7c2a5a60b5cc.png)

**Comment by mcuiobroker** [comment]
Folgendes muss nicht unbedingt was mit den Adaptern zu tun haben: Fehler in der Console auf der Adapter-Seite.
![image](https://user-images.githubusercontent.com/84818934/125360996-fae1b080-e36c-11eb-8c04-aed164ad4200.png)

**Comment by Zefau** [comment]
Ich werd in der kommenden Version js-controller aus der Liste der Updates entfernen.

In einer zukünftigen Version werde ich mal schauen, ob ich js-controller in die Gesamtliste integriert bekomme. Ein erster Blick darauf erscheint etwas umständlich.
