### ISSUE TITLE
v3: IconButtons werden nicht richtig angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#809]
v3.0.0-alpha.20
![image](https://user-images.githubusercontent.com/84818934/123526019-683ae380-d6d5-11eb-8c7e-78c17d3c50a5.png)
sollte so aussehen:
![image](https://user-images.githubusercontent.com/84818934/123526045-93253780-d6d5-11eb-96fc-625bf512417c.png)

**Comment by Zefau** [comment]
Was ist konkret das Problem?

IconButtons unterstützen nun `false` und `true`. Leerer Ring = `false` im Standard. Meinst du das?

**Comment by mcuiobroker** [comment]
Das ist aber neu, vorher in v2.2.0 konnte man nur Icon Button angeben (power). Muss man sich nur drauf einstellen.
