### ISSUE TITLE
Add navigation drawer

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#81]
As of now I have a tab per function (e.g. lights), but It would be great to have the possibility to also have a tab per room (e.g. living room). Currently it's only posible to have one set of tabs. I don't want to mix these tabs, therefore please add another level of navigation in dorm of a drawer.

https://material.io/components/navigation-drawer

**Comment by ma-gu-16** [comment]
Ja Drawer, links, oder rechts, versteckt oder fixed. Variable oder fixe breite.

**Comment by Zefau** [comment]
added with ` v3.0.0-alpha.10`
