### ISSUE TITLE
v3: Gruppe anlegen führt zum Einfrieren

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#810]
v.3.0.0-alpha.21
![image](https://user-images.githubusercontent.com/84818934/123526714-00d36280-d6da-11eb-8c82-374d5395d972.png)

**Comment by Zefau** [comment]
Merkwürdig. Funktioniert bei mir total problemlos. Hast du das Verhalten in Firefox und Chrome?

**Comment by mcuiobroker** [comment]
Chrome:
![image](https://user-images.githubusercontent.com/84818934/123544659-99a6c400-d754-11eb-9a7a-9a9e6c6b1d75.png)
Firefox:
![image](https://user-images.githubusercontent.com/84818934/123544742-face9780-d754-11eb-9b17-aa3192d4effd.png)
Dort kann man aber noch was bewegen

Fehlermeldungen:
`StateListItem (Primary State Key nextNews): app.849a0ef2.js:1:955805
StateListItem (Body State Key undefined): app.849a0ef2.js:1:956251
StateListItem (Secondary State Key VerbleibendeZeit100): app.849a0ef2.js:1:956534
Script terminated by timeout at:
get@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:7597
n/<@http://192.168.178.70:8082/jarvis/js/4.b7d829fa.js:1:10682
Ze@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:17097
n@http://192.168.178.70:8082/jarvis/js/4.b7d829fa.js:1:7710
e/e.render/<@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:101:9679
Jt@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:101:9434
e/e.render@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:101:9653
_n/t.prototype._render@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:23978
i@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:28019
a026/</oi.prototype.get@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:30904
a026/</oi.prototype.run@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:31637
Qn@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:29844
ve/<@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:12887
de@http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js:87:12282
vendor.674748a4.js:87:7597
Speicherverbrauch von "will-change" ist zu hoch. Die Budget-Grenze ist die Fläche des Dokuments multipliziert mit 3 (1201920 px). Vorkommen von "will-change", die das Budget überschreiten, werden ignoriert. index.html
downloadable font: Size of decompressed WOFF 2.0 is less than compressed size (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:0) source: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
downloadable font: rejected by sanitizer (font-family: "Material Design Icons" style:normal weight:400 stretch:100 src index:0) source: http://192.168.178.70:8082/jarvis/fonts/materialdesignicons-webfont.e9db4005.woff2
downloadable font: Size of decompressed WOFF 2.0 is less than compressed size (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:0) source: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
downloadable font: rejected by sanitizer (font-family: "Material Icons" style:normal weight:400 stretch:100 src index:0) source: http://192.168.178.70:8082/jarvis/fonts/flUhRq6tzZclQEJ-Vdg-IuiaDsNcIhQ8tQ.044abb9e.woff2
Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.70:8082/jarvis/js/app.849a0ef2.js
Source-Map-Adresse: app.849a0ef2.js.map

Source-Map-Fehler: Error: request failed with status 404
Ressourcen-Adresse: http://192.168.178.70:8082/jarvis/js/vendor.674748a4.js
Source-Map-Adresse: vendor.674748a4.js.map

`

**Comment by Zefau** [comment]
besser mit `v3.0.0-alpha.23` ?

Wie viele Geräte hast du in deiner StateList ?
Funktioniert es mit (neuen) StateList's, die wenig Geräte haben?

**Comment by mcuiobroker** [comment]
Bei der Problematik mit der Gruppe Weihnachten von v2.2.0 nach v3 kommt man jetzt erstmalig die Bearbeitung rein, hängt sich dann aber auch wieder auf.
![image](https://user-images.githubusercontent.com/84818934/125212094-5ba8b480-e2ab-11eb-8d8d-cb567d94361c.png)
Ungünstiges Anzeigeverhalten bei der Eingabe der Werte:
![image](https://user-images.githubusercontent.com/84818934/125212253-54ce7180-e2ac-11eb-89eb-0fb0de71b71e.png)
NEUE Kleine Gruppe funktioniert
![image](https://user-images.githubusercontent.com/84818934/125212290-a24ade80-e2ac-11eb-9d9e-7c9f04038458.png)

**Comment by mcuiobroker** [comment]
In der Statelist von v2.2.0 sind 13 Geräte und 3 divider: Grupe Weihnachten:
![image](https://user-images.githubusercontent.com/84818934/125212344-0ff70a80-e2ad-11eb-8784-cbdd21585929.png)

**Comment by Zefau** [comment]
Kannst du mir das konvertierte JSON der Gruppe bereitstellen?

**Comment by mcuiobroker** [comment]
Funktioniert das?
![image](https://user-images.githubusercontent.com/84818934/125510599-fe12993d-351c-45d0-8fdd-4d25db97ab0c.png)

**Comment by Zefau** [comment]
Nein, nicht mehr. Muss ich in v3 noch rausnehmen.

**Comment by mcuiobroker** [comment]
Es ist so das er bei der Konvertierung zwar ein Widget angelegt hat mit Nummer. Dies aber nicht zu Ende geführt wurde. Somit sind dort keine Daten zum Widget (i:).

**Comment by Zefau** [comment]
Das ist das Layout. Mit der ID des Layouts findest du dann den entsprechenden Eintrag in den Widgets (`jarvis.0.widgets`).

**Comment by mcuiobroker** [comment]
Ja genau und dort ist ist halt nichts zu dieser Nummer zu finden.

**Comment by Zefau** [comment]
Steht denn bei dir in der Übersicht `undefined` ?

![image](https://user-images.githubusercontent.com/14368811/125677689-8205e9b3-a9fb-4af0-b0bd-8d16fb78af8a.png)

**Comment by Zefau** [comment]
Also die ID unter `i` ist die eigene ID, keine Fremd-ID des Widgets.
Die Fremd-ID der Widgets ist unter `items`:

```
{
   "id":"0559b5e5-1c56-4ea4-8211-d51226417202",
   "title":"Dashboard",
   "icon":"mdi-monitor-dashboard",
   "widgetsDesktop":[
      {
         "x":0,
         "y":4,
         "w":4,
         "h":24,
         "i":"77ac22da-738d-4646-b0f5-940298bd6571",     <-- kein Bezug zu Widgets
         "moved":false,
         "items":[
            "3958dfb0-83da-48ae-96f3-e66969a92cac"         <-- zu finden in den Widgets
         ]
      }
   ]
}
```

**Comment by Zefau** [comment]
Wie sieht denn bei dir der komplett Eintrag im Layout aus (wie von mir gepostet) und findest du die ID, die unter `items` angegeben ist in den Widgets? Und wie sieht dort der Eintrag aus?

Danke dir!

**Comment by mcuiobroker** [comment]
In der Übersicht sieht so aus:
![image](https://user-images.githubusercontent.com/84818934/125685097-dfff891e-bbcc-4f6b-b887-7111562e693c.png)

**Comment by mcuiobroker** [comment]
`{"id":"wohnen5","icon":"sofa","title":"Wohnen","iconColor":"","color":"","backgroundColor":"","widgetConfig":{},"widgetsDesktop":[{"x":0,"y":0,"w":4,"h":4,"i":"b55022be-d4f0-430b-9fc9-387f1ce7f9f9","items":["c08eb364-7c73-4b23-b460-e7619a386cd2"],"scaleToFitContents":true,"alignmentVertical":"top","alignmentHorizontal":"center"}`

![image](https://user-images.githubusercontent.com/84818934/125685384-9d03a4df-bbea-4ec9-a427-860dd4821693.png)

**Comment by Zefau** [comment]
Vielen Dank! Sollte nun endlich mit `v3.0.0-alpha.27` behoben sein.

**Comment by mcuiobroker** [comment]
Ja, muss noch die Konvertierung prüfen. Bearbeitung klappt soweit gut. Prima.

**Comment by mcuiobroker** [comment]
Konvertierung passt noch nicht:
![image](https://user-images.githubusercontent.com/84818934/125979370-f96f29b4-d66a-4a31-818c-e6b22a2eeeeb.png)
Der Schalter für die Gruppe wird nicht mit eingeschaltet.
![image](https://user-images.githubusercontent.com/84818934/125979492-02dbd1c7-5678-4e0c-b5f4-7dfc9b90bdda.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.29` nun passen

**Comment by mcuiobroker** [comment]
Ja. Passt einwandfrei. Super.
