### ISSUE TITLE
v3: Konvertierung oder Update löscht Bodyelement

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#812]
evtl erst mit v3.0.0-alpha.22
v2.2.0
![image](https://user-images.githubusercontent.com/84818934/123545322-bbee1100-d757-11eb-973f-794bfd8786ac.png)
v3
![image](https://user-images.githubusercontent.com/84818934/123545342-c6100f80-d757-11eb-8e9e-eaecdd4f65d4.png)
Kann auch mit dem LightColorBoy-Problem zusammenhängen

**Comment by Zefau** [comment]
Datenpunkt Trigger ist doch drin? Oder meinst du BodyElement?

**Comment by mcuiobroker** [comment]
Ja meinte das Bodyelement hab es noch mit der alten Position verwechselt.

**Comment by Zefau** [comment]
@mcuiobroker kannst du das JSON für v2 und v3 für das Beispiel einmal zur Verfügung stellen? Also vor und nach der Konvertierung. Danke!!

**Comment by mcuiobroker** [comment]
Meinst du jetzt JSON aus dem Expertenmodus? Kann auch durch das Update passiert sein? Ich geh dann nochmal zurück auf v2 und mach nochmal direktes Update auf v3.0.0-alpha.22?

**Comment by Zefau** [comment]
Das JSON, was du für v2 im Backup hast.

**Comment by mcuiobroker** [comment]
v2: aus dem Expertenmodus Geräte
`"LichtAn": {
        "state": {
          "node": "javascript.0.HAUS.LICHT.KARTE.LICHT_AN"
        },
        "action": "javascript.0.HAUS.LICHT.KARTE.LICHT_AN",
        "actionElement": "SwitchAction",
        "label": "",
        "iconStyle": {
          "true": {
            "color": "yellow"
          }
        }
      },

`

v3: (jetzt aus der .22, ohne nochmals neu konvertiert zu haben)
`"LichtAn": {
        "state": "javascript.0.HAUS.LICHT.KARTE.LICHT_AN",
        "action": "javascript.0.HAUS.LICHT.KARTE.LICHT_AN",
        "actionElement": "SwitchAction",
        "label": "",
        "iconStyle": {
          "true": {
            "color": "yellow"
          }
        },
        "stateKey": "LichtAn"
      },`
Meinstest du das?

**Comment by Zefau** [comment]
Genau das meinte ich, danke dir. Dann hat er zumindest alles richtig übernommen. Der Fehler ist dann, dass die Standardeinstellung mit `LastChangeBody` nicht korrekt zieht.

**Comment by mcuiobroker** [comment]
Zur Info, gehört nicht unbeding hier hin:
Ich hatte nochmals von der v2.2.0 nach v3.0.0-alpha.22 ein Update eingespielt und danach direkt die Seite aufgerufen über Instanzen
![image](https://user-images.githubusercontent.com/84818934/123555824-6aaa4580-d788-11eb-8b88-3247fdc726fe.png)
In der Anzeige gab es nur die Überschriften
![image](https://user-images.githubusercontent.com/84818934/123555853-93323f80-d788-11eb-99d6-6e2582182a5b.png)
Sonst konnte man nur die Fensterstrukturen sehen ohne Objekte.
Nach F5 Aktualisierung war wieder alles normal.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.30` Konvertierungsfehler Datenpunkt (Anzeige) fehlt
v2.2.2:
![image](https://user-images.githubusercontent.com/84818934/126077103-df0af718-2932-4c09-8821-52957f9fab87.png)

v3:
![image](https://user-images.githubusercontent.com/84818934/126077112-2bb54e05-5b0e-4a09-8fb0-4c554f6e7bd5.png)

**Comment by mcuiobroker** [comment]
Bin nicht sicher ob hier hin gehört:
Problem Icon wird nicht gefunden, weil keins definiert wurde:
![image](https://user-images.githubusercontent.com/84818934/126077191-f37e2c23-febb-45ea-b3ad-9b17f93b6d69.png)
Ergebnis ist er dreht dann einige Suchrunden:
![image](https://user-images.githubusercontent.com/84818934/126077205-13959a6d-ccc7-4c68-9711-b26e36873b32.png)

Bis dann nur noch das erscheint:
![image](https://user-images.githubusercontent.com/84818934/126077211-2723822c-b0b8-41fc-8b76-5cbb8f9cc836.png)

Das Feld für ein ICON sollte dann frei bleiben und da nichts eingestellt nicht suchen.

v3:
![image](https://user-images.githubusercontent.com/84818934/126077169-a7b7e168-9bd0-4804-a933-67e78cea5a8e.png)

**Comment by mcuiobroker** [comment]
Die Überschriften werden anscheinend bei dem Vorschlag zur Widget-Höhe nicht berücksichtigt:
![image](https://user-images.githubusercontent.com/84818934/126077323-6381cd45-5881-4dfd-8109-7f3ac7d14138.png)

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.31`
Fehler taucht am Anfang auf:
![image](https://user-images.githubusercontent.com/84818934/126082389-3e44c409-a41a-436a-83a1-7bfaf5a507bf.png)

**Comment by Zefau** [comment]
>  Sonst konnte man nur die Fensterstrukturen sehen ohne Objekte.

Sollte das nochmal vorkommen, schau mal, ob du einen Fehler in der Browser-Konsole hast.

Alle anderen Kommentare sind mit `v3.0.0-alpha.43` hoffentlich behoben (habe ich mit Checkbox abgehakt).

**Comment by Zefau** [comment]
Nachtrag: `v3.0.0-alpha.44` behebt nun auch die eigentliche Fehlermeldung dieses Issues :-)

Bezogen auf das Layout wird ab der Version `LastChangeBody` nun korrekt konvertiert (und auch spezifisch im JSON eingetragen, da der default im v2 zu fehleranfällig war). Beim Hinzufügen im Layout eines neuen Geräts wird `LastChangeBody` nun ebenfalls als Standard ausgewählt und kann abgewählt werden. Beim Gerät

**Comment by mcuiobroker** [comment]
Der Punkt kann erstmal geschlossen werden. In `v3.0.0-alpha.61`ok.
