### ISSUE TITLE
v3: Konfiguration bei kleineren Breiten fehlen Elemente in der Anzeige

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#813]
v.3.0.0-alpha.22 (war auch vorher so)
Verkleinert man die Breite von der Konfigurationsdarstellung kleiner 1500px(~) werden die Elemente nicht mehr komplett dargestellt. Dort ist noch keine responsive Darstellung eingestellt.
![jarvisv3_KonfigurationBeiKleinenBildschirmBreitenFehltScrollFürX](https://user-images.githubusercontent.com/84818934/123551918-2b71f980-d774-11eb-99f6-682ce7a6705c.gif)
Ist momentan nicht extrem wichtig, aber damit man es nicht vergisst, habe ich es eingetragen.

**Comment by Zefau** [comment]
Sollte inzwischen behoben sein. Responsive habe ich aus der Konfiguration erstmal entfernt, da recht komplex. Die Nummerierung zeigt die Reihenfolge.

**Comment by mcuiobroker** [comment]
Ok. So wie es jetzt in `v3.0.0-alpha.87` ist es ok.
