### ISSUE TITLE
v3: Konvertierung PixelHöhe vom Widget automatisch anpassen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#814]
![image](https://user-images.githubusercontent.com/84818934/123556113-c2957c00-d789-11eb-83ba-4394c5a9f87e.png)

Zurzeit werden die WidgetHöhen immer mit 400px vorbelegt. Die Höhe einiger Statelist sind wesentlich höher oder manchmal auch kleiner. Das führt bei vielen User dazu, dass man sehr nachjustieren muss.
Frage: Kann man die vorberechneten Höhen (Statelist) nicht auch direkt in die Höhe vom Widget eintragen lassen bei der Konvertierung? Immer im Vielfachen von 100px -> Mein Beipiel: 11h

Da es in v3 keine StatelistHorizontal mehr gibt, wäre es sinnvoll für diese Widget eine Warnung zu bekommen, bzw, wenn möglich dort auch eine Konvertierung zum HomekitTyle.

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.29` wird nun die Höhe für StateList berechnet (bzw. überschlagen) und auch `StatelistHorizontal` wird in `HomeKitTile` geändert.

**Comment by mcuiobroker** [comment]
Das sieht schon sehr gut aus. Eine Kleinigkeit noch: Du nimmst die Höhe in Abhängigkeit der Anzahl der Element. Die Element sind nur oftmals "divider". Diese haben nicht die Höhe von einem normalen Statelist-Element. Vielleicht kannst du das noch berücksichtigen. Vielen Dank.
Höhe = Anzahl Elemente (Überschrift, Statelist-Elemente, Gruppe(n)) * 50px + (divider * 15px) wäre mein Ansatz und dann aufrunden auf Vielfaches von 100px.

**Comment by mcuiobroker** [comment]
v2.2.2:
![image](https://user-images.githubusercontent.com/84818934/126049069-955bc3f1-e12c-4b73-aacb-97f26c4b5a94.png)
![image](https://user-images.githubusercontent.com/84818934/126049093-45f1311e-67dc-440c-a740-0b45a949eaae.png)
v3:
![image](https://user-images.githubusercontent.com/84818934/126049100-adcff878-63fe-4bc3-aa34-e48b9358bf64.png)
![image](https://user-images.githubusercontent.com/84818934/126049116-b6c85b9d-c17f-46a4-948a-1e36f0a33554.png)

Die secundären Datenpunkte fehlen.

**Comment by Zefau** [comment]
Die Anpassung der Höhe mit Berücksichtigung des Dividers übernehme ich so in der nächsten alpha (Divider = 5px, Gerät = 46px).
Auch das Routing auf HOME bei Klick ist ein Bug in HomeKitTile und mit der nächsten alpha behoben.

Die sekundären Datenpunkte bitte manuell nachziehen. Den Standard den ich festgelegt habe ist: (mittig von oben nach unten): Icon, Label, State, da nur 3 vertikal passen.

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/126222049-543d0172-e31b-424a-86c3-76c27fc03906.png)
Die Höhe passt nicht, da die Übeschrift nicht berücksichtigt wurde. Wie schon im anderen Post beschrieben.
Jetzt wurde sogar ein Element gar nicht mehr angezeigt. Es wurde also auch der Bereich nicht verkleinert, sondern einfach weggelassen. (war nur direkt nach der Konvertierung)
Nachdem ich dann selbst die PixelHöhe angepasst hatte, wude das Geräte-Element dann auch angezeigt.
Das letzte Gerät war weg:
![image](https://user-images.githubusercontent.com/84818934/126222425-7f6ecbc4-6bc9-465d-ac1e-d32458201d2e.png)

**Comment by mcuiobroker** [comment]
Als Grundlage für die Berechnungen sollte nicht 100px gelten sondern 50px, wie schon im anderen Post beschrieben. Grund: Man kann sonst nicht nur eine Zeile erstellen. Oder du nimmst die Aktualisierung raus, wenn man den PIXEL-Wert von 100px auf 50px ändert. So werden momentan alle Module entsprechend angepasst.
Zur Vorschlags-Höhe der Module:
Die Überschrift ist momentan sehr groß ca 75px, diese sind in der Berechnung nicht enthalten. Diese fehlen.

![image](https://user-images.githubusercontent.com/84818934/126226746-895d0bfb-6c15-49bd-9791-35328f4dce83.png)
In dem Beispiel sieht man beide haben nur ein Statelist-Element und trotzdem sind sie unterschiedlich.
Da auch zwischen den Statelist-Elementen ein Zwischenraum ist sollte dieser auch mit berücksichtigt werden. Dies kannst aber besser abschätzen, da dort die Padding-Werte entscheidend sind.

**Comment by Zefau** [comment]
> Als Grundlage für die Berechnungen sollte nicht 100px gelten sondern 50px, wie schon im anderen Post beschrieben. Grund: Man kann sonst nicht nur eine Zeile erstellen. 

Die Höhe kannst du beliebig umstellen. Ich kann den Standard aber auf 50px einstellen.

>  Die Überschrift ist momentan sehr groß ca 75px, diese sind in der Berechnung nicht enthalten. Diese fehlen.

Die Überschrift ist 56px und ist mit der nächsten alpha berücksichtigt.

>  Da auch zwischen den Statelist-Elementen ein Zwischenraum ist sollte dieser auch mit berücksichtigt werden. Dies kannst du aber besser abschätzen, da dort die Padding-Werte entscheidend sind. Auch die Padding-Werte für die "divider" berücksichtigen (5px werden da nicht reichen).

Die Unterschrift ist nicht berücksichtigt. Auch Secondary States nicht. Auch andere Trigger als Switch nicht (Buttons sind meine ich größer). Das soll auch keine Raketenwissenschaft werden, sondern nur eine grobe Orientierung.
Der Divider ist 1px.

**Comment by Zefau** [comment]
Mit 50px als Standardhöhe wird es frickelig im Backend die Boxen zu bearbeiten. Aber mach dir mit `3.0.0-alpha.39` mal selbst ein Bild. Was meinst du?

**Comment by mcuiobroker** [comment]
Grundsätzlich ist die Einstellung mit 50px richtig, du musst natürlich die Faktoren anpassen:
![image](https://user-images.githubusercontent.com/84818934/126715583-2d742f3a-5166-4245-b9aa-c0ed3679534c.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/126717068-82fd827b-b8f0-4716-9524-f7f779f97ce6.png)
Homekittile immer 100px
customHtml immer 450px? Kann man die Werte aus v2 bekommen?
iFrame immer 450px? Werte auch v2?

**Comment by Zefau** [comment]
wenn deine Instanz wieder steht, dann probier gerne nochmal mit `v3.0.0-alpha.42`, ob die Konvertierung passt.

**Comment by mcuiobroker** [comment]
Habe mit einem Tablet doch noch ne Möglichkiet gefunden upzudaten.
Das sieht schon fast PERFEKT aus. Echt Klasse. Ein paar Kleinigkeiten noch gefunden:
Hat man nur eine Überschrift und ein Statelist-Element wird das Widget um 1 Element zu groß angezeigt (vorgeschlagen). 
Bei meinem HOME-Allgemeines werden die Elemente zwar alle angezeigt, nur der Widget-Bereich ist etwas (um 50px) zu klein). Ich kann dir das jetzt alles nicht zeigen, arbeite über den Raspi, habe kein PC mehr bis nächste Woche.

Was mir noch aufgefallen ist, bei dem neuen "snake-Effekt", wird dieser nicht mehr korrekt dargestellt, nach der Konvertierung. Das Bild werde ich über die App versuchen hinzuzufügen.
Sonst, wie gesagt echt Klasse gemacht.

**Comment by mcuiobroker** [comment]
![20210731_233609.jpg](https://user-images.githubusercontent.com/84818934/127753134-f8a772ef-dbd5-4b69-9d63-9f6e0cc93316.jpg)

**Comment by Zefau** [comment]
Das passt dann erst mal so. Um den Snake-Effekt kümmern wir uns dann in der beta.

**Comment by mcuiobroker** [comment]
Die Höhe von einer Zeile scheint höher als 46px zu sein?
![image](https://user-images.githubusercontent.com/84818934/127968355-e63baba2-4aba-4d6d-92a5-9f742d9556ce.png)
Man erkennt daran, dass der selektierte Bereicht nicht über die ganze Zeile gewählt wird.
In normaler Zeile sieht es so aus bei Selektion:
![image](https://user-images.githubusercontent.com/84818934/127968485-06b5e397-dc5d-450e-a496-1c80c9ad0e18.png)
Liegt es daran?

**Comment by Zefau** [comment]
48px müsste eine Zeile hoch sein (bzgl StateList).

Generell kommt noch der Abstand / Zwischenraum der benachbarten Widgets dazu.
