### ISSUE TITLE
v3: Notifications

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#815]
- [x] Klick auf die Glocke führt zum Aufgehen von dem Auswahlfenster zur Konfiguration und MainSite (ab v3.0.0-alpha.20-22)
![image](https://user-images.githubusercontent.com/84818934/123556508-e22da400-d78b-11eb-936e-27e636b5b345.png)
![jarvisv3_GlockeDrücken_Konfigurationsmenü](https://user-images.githubusercontent.com/84818934/123556769-587ed600-d78d-11eb-94e6-67c82c2ab77d.gif)

- [x] Notification wird nicht mehr automatisch gelöscht, sondern bleibt auf dem Bildschirm stehen, obwohl autohideDuration mit 5 Sekunden gesetzt
`[{"icon":"mdi-book-alert","title":"Achtung","message":"Temperatur Aussenfühler 0°C","display":"popup","autoHideDuration":5000,"state":"unread","id":"fd26027d-0059-4cd3-a182-e5bf4114beb5","ts":1624820828337}]`

- [x] Es werden 2 angezeigt, aber nur eine davon war ungelesen 
![image](https://user-images.githubusercontent.com/84818934/123556902-130ed880-d78e-11eb-8182-d0fcf51e52fa.png)
Also er setzen bein Neuanlage einer Notification alle wieder auf unread.
`[{"icon":"mdi-book-alert","title":"Achtung","message":"Temperatur Aussenfühler 0°C","display":"popup","autoHideDuration":5000,"state":"unread","id":"fd26027d-0059-4cd3-a182-e5bf4114beb5","ts":1624820828337},{"icon":"mdi-book-alert","title":"Achtung","message":"Temperatur Aussenfühler 0°C","display":"popup","autoHideDuration":5000,"state":"unread","id":"6354e28f-690f-4f31-ab84-6449d33bdbc5","ts":1624821834912},{"icon":"mdi-book-alert","title":"Achtung","message":"Temperatur Aussenfühler 0°C","display":"popup","autoHideDuration":5000,"state":"unread","id":"98a86a9d-4343-4576-9938-b885c30e7c86","ts":1624822030612}]`
3 zur Kontrolle.

**Comment by noffycws** [comment]
Außerdem "springt" die Glocke unter das Menü, wenn nur ein Tab auf einer Seite ist:
![image](https://user-images.githubusercontent.com/78761005/123701404-1a071b00-d862-11eb-8aec-e95d83f1f601.png)

Wenn mehrere Seiten vorhanden sind, dann bleibt es brav auf der rechten Seite.

**Comment by Zefau** [comment]
everything should be resolved with `v3.0.0-alpha.23`.

**Comment by noffycws** [comment]
Die "verwaiste" Glocke ist bei ´alpha.23´ wieder an Ort uns Stelle.

**Comment by mcuiobroker** [comment]
Notification wird in der Glocke korrekt angezeigt, aber es kommt kein Popup.
![image](https://user-images.githubusercontent.com/84818934/125211544-5b0e1f00-e2a7-11eb-9ff1-7bc13bb21c04.png)
Wird hier schon als gelesen markiert angezeigt, obwohl Popup nicht da war.
Titel fehlt
Nach Auswahl verschwindet es nach der angegebenen Zeit 5Sek, soll das so? Im Popup ja, aber nicht bei Auswahl, oder?
![image](https://user-images.githubusercontent.com/84818934/125211574-8d1f8100-e2a7-11eb-8283-a7f7fc85af69.png)
Kann man so machen, das dort die Anzahl der ungelesenen / Gesamtzahl steht?
Nicht 1, sondern 1/1.

**Comment by mcuiobroker** [comment]
Muss man noch die Notification für den TAB-Wechsel nutzen oder geht das über die Tab-id?

**Comment by mcuiobroker** [comment]
Wenn man die Nachrichten in Archive gestellt hat wird es nicht korrekt angezeigt, falsche Farbwahl?
![image](https://user-images.githubusercontent.com/84818934/125212616-0373b180-e2af-11eb-82ce-2fcec119f925.png)

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.0-alpha.26`.

**Comment by mcuiobroker** [comment]
Das einzige was noch nicht passt, ist der Popup kommt nicht. Er soll ja 5 Sekunden direkt angezeigt werden. Da kommt so nichts. Sonst Spitze.
Wenn mal Zeit ist, sollte es auch Clientspezifisch sein.
![image](https://user-images.githubusercontent.com/84818934/125688771-fc5a0675-d7d5-45e7-acf8-c641996d8120.png)

**Comment by Zefau** [comment]
Was genau meinst du mit 5 Sekunden?

Client spezifisch ist es. In der notification json mittels `devices` und dann die ID des Gerätes.

**Comment by mcuiobroker** [comment]
`"autoHideDuration":5000`

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.28` sollte es nun endlich passen

**Comment by mcuiobroker** [comment]
Sehr schön. Passt.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.36`
Notifications werden zwar gelöscht, aber bei neuer Notification wieder geladen aus dem "Nichts", denn in den Objekten steht nichts drin.
![image](https://user-images.githubusercontent.com/84818934/126570085-8a3d6549-9589-48c1-9220-abfb8e85b341.png)
![jarvis_v300-alpha-36-NotificationsAusdemNichtsGeladen2](https://user-images.githubusercontent.com/84818934/126570110-72a5deb4-4db4-41ba-851b-d9581cfbb75a.gif)

Erst wenn man in die Objekte geht und dort nochmal "[]" eingibt und bestätigt sind die Notifications wirklich gelöscht.

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.37`.

**Comment by mcuiobroker** [comment]
Ja, passt wieder. Danke.

**Comment by noffycws** [comment]
Also irgendwie klappt das mit den Benachrichtigungen bei der `alpha.39` nicht.

Ich gebe folgenden Text in den Datenpunkt `jarvis.0.addNotification`:
`{"title":"PeakShaving","message":"PeakShaving geht heute bis","icon":"bi:hourglass-split","iconColor": "#f1c40f"}`

Das ioBroker-Log spuckt dann diese Fehlermeldung aus:
`NOTIFICATIONS.push is not a function`

Mach ich da was falsch mit den Benachrichtigungen - finde dazu auch keine richtige Anleitung im Wiki - oder ist das tatsächlich ein Fehler?

**Comment by mcuiobroker** [comment]
War man in der Konfiguration und speichert und schickt dann eine Notification, so wird die autoHideDuration nicht überall eingehalten. Auf dem PC werden plötzlich aus geforderten 30 Sek-> 10 Sek.
Nach F5 und anschließender Notification wird die Zeit wieder eingehalten.

Komischerweise sind die Zeiten auf Tablet und PC unterschiedlich. Tablet lässt die Notification 2 Sekunden früher verschwinden, obwohl sie gleichzeitig angezeigt werden. (Nur zur Info).

**Comment by Zefau** [comment]
>  War man in der Konfiguration und speichert und schickt dann eine Notification, so wird die autoHideDuration nicht überall eingehalten. Auf dem PC werden plötzlich aus geforderten 30 Sek-> 10 Sek.

Schau nochmal bitte mit `v3.0.0-alpha.118`.

> Komischerweise sind die Zeiten auf Tablet und PC unterschiedlich. Tablet lässt die Notification 2 Sekunden früher verschwinden, obwohl sie gleichzeitig angezeigt werden. (Nur zur Info).

Glaube, dass ich das mit jarvis nicht eingefangen bekomme. Der Timeout wird auf dem Gerät selbst berechnet und kann auf Basis der Hardware und unterschiedlicher Faktoren einfach unterschiedlich ausgehen.

> Hat man mehrere Browser geöffnet und einer ist nicht aktiv (Bildschirm ist nicht an) und man schickt jetzt Notification an alle, verarbeitet diese auf den aktiven Bildschirmen, löscht sogar die Notifications, so werden, wenn man den inaktiven Browser öffnet, komplett alle bis dahin aufgelaufenen Notifications angezeigt, obwohl sie schon gelöscht wurden.

Das ist gewollt. Sofern die Notification an alle Geräte geschickt wird, wird es überall angezeigt. Alternativ kannst du die Notification nur an bestimmte Geräte schicken.

**Comment by mcuiobroker** [comment]
Unabhängig davon, kannst du bitte die "state":"delete"-Option mit einbauen. Wir hatten da schon mal drüber gesprochen.

**Comment by Zefau** [comment]
Was soll das heißen? Funktioniert es, oder nicht?

Für das andere Thema ist doch ein Issue offen.. also abwarten

**Comment by mcuiobroker** [comment]
Ja, funktioniert. Mit dem anderen Issue hatte ich gerade nicht auf dem Schirm, sorry.
