### ISSUE TITLE
v3: Label JSON 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#816]
Label JSON
![image](https://user-images.githubusercontent.com/84818934/123672184-56754f80-d83f-11eb-9dd9-dc0740223c0f.png)
beeinflusst nicht das Label sondern den DP Bezeichner
![image](https://user-images.githubusercontent.com/84818934/123672049-3776bd80-d83f-11eb-99a7-627bb87dc37d.png)

![image](https://user-images.githubusercontent.com/84818934/123672096-4493ac80-d83f-11eb-8981-f63384b5dd10.png)
Wird nicht in dem Layout überschrieben, wenn dort schon was drin steht.
Ob man da tätig werden sollte?? Ein Hinweis nachdem man es im Gerät angepasst hat, könnte sinnvoll sein?

**Comment by Zefau** [comment]
>  Wird nicht in dem Layout überschrieben, wenn dort schon was drin steht.

Das ist das korrekte Verhalten. Ein Hinweis wäre aufwändig insbesondere im Vergleich dazu, dass man es ja recht schnell merken sollte.

Das Label greift im Popup und im Layout, sofern der entsprechende Body State Key gewählt ist und kein anderes Label vorher eingegeben wurde.
