### ISSUE TITLE
v3: Geräte Datenpunkt Explorer Verzeichnisse fehlen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#817]
![image](https://user-images.githubusercontent.com/84818934/123700137-5c2f5d00-d860-11eb-8183-c282cd118a41.png)

![image](https://user-images.githubusercontent.com/84818934/123700182-6a7d7900-d860-11eb-8aee-3e117f1cc91d.png)

Die Verzeichnisse kann man nicht auswählen.

**Comment by Zefau** [comment]
siehe auch https://github.com/Zefau/ioBroker.jarvis/issues/802

Ist inkorrekt im ioBroker angelegt vermute ich. Aber werde ich in jarvis auch korrigieren, da v3 hier strenger ist als v2.

**Comment by mcuiobroker** [comment]
DIe DPs sind mit createState angelegt. ? Woran erkenne ich das es inkorrekt ist?

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/123701720-7ff3a280-d862-11eb-8711-6e2400e9e669.png)
Weil "channel" fehlt?

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.23`.

**Comment by mcuiobroker** [comment]
Ja korrekt. Ist erledigt.
