### ISSUE TITLE
Reduze menu bar height

### ISSUE THREAD

**Issue by ScumbagSteve** [Zefau/ioBroker.jarvis#819]
The menu bar takes up an  (unnecessary) lot of space.
I tried to reduce the min-height of the MuiToolbar-regular to 0, according to a forum post
```
.MuiToolbar-regular {
min-height: 5px !important;
}

.MuiToolbar-regular button {
padding: 4px 12px 0 12px;
}

.MuiTab-root {
min-width: 120px;
min-height: 0 !important;
}
```

This doesn't work for me. The style I enter in the "Styles" tab doesn't get applied.
Am I doing something wrong?

A more denser layout might be interesting for other users as well. Especially on mobiles / tablets a lot of space is wasted.

**Comment by Zefau** [comment]
Please move to v3. The layout is denser there.
