### ISSUE TITLE
Styles / CSS wird nicht mehr angewandt

### ISSUE THREAD

**Issue by SliX185** [Zefau/ioBroker.jarvis#820]
Version: 2.2.0

Es werden bei mir keinerlei custom CSS Einstellungen mehr angewandt,
ohne jeglicher Änderung am System?!

z.B:
![css](https://user-images.githubusercontent.com/47434006/124020732-f6bba780-d9ea-11eb-8b59-c9be8bececd6.JPG)

wird nicht angewendet, zuvor jedoch ohne Probelme?
Was hat sich geändert?

Danke im voraus.

**Comment by Zefau** [comment]
versuch mal bitte, ob es mit 2.2.1 behoben ist: https://github.com/Zefau/ioBroker.jarvis/tarball/v2.2.x/

**Comment by SliX185** [comment]
Danke für die schnelle Antwort!!

Leider nun mit Error:
![jarvis err](https://user-images.githubusercontent.com/47434006/124029019-fa542c00-d9f4-11eb-8065-9af99b85dbb1.JPG)

... Aber ich sehe kurz davor mein eigenes Farbschema, also die Richtung stimmt?!

**Comment by SaschaWeiher** [comment]
Hi Zefau,

ich habe das Problem mit dem Styles Pro (CSS) ebenfalls seit ein paar Tagen.

**Comment by Zefau** [comment]
@SliX185 @SaschaWeiher bitte nochmal die aktuelle Version von Github via https://github.com/Zefau/ioBroker.jarvis/tarball/v2.2.x/ probieren

**Comment by SliX185** [comment]
@Zefau BESTEN DANK!! Bei mir funktioniert wieder alles. Danke für die schnelle Hilfe! Schönen Abend noch.

**Comment by SaschaWeiher** [comment]
Na, was mach ich denn diesmal wieder falsch? Ich habe das Update via Kätzchen reingeholt, aber es hat keine Verbesserung gebracht. Ist wohl nicht mein Tag. ;-)

**Comment by Zefau** [comment]
Was für einen Fehler hast du noch?

**Comment by SliX185** [comment]
Achte bitte darauf den letzten Slash "/" weg zu lassen....
Also so:
https://github.com/Zefau/ioBroker.jarvis/tarball/v2.2.x

dann solllte es funktionieren.

**Comment by SaschaWeiher** [comment]
Heute seid ihr meine Helden. Besten Dank! Das war es. Issue kann geschlossen werden.

**Comment by SliX185** [comment]
Guten morgen @Zefau 

seit heute werden leider wieder keine CSS Styles angewandt. 
Version: 2.2.3

Ich gehe davon aus, dass das was mit deiner Pro Version zu zun hat. 
Gerne schließe ich das Abo ab, aber ist es denn möglich die Version 2 auch weiter zu nutzen oder liegt das Problem wo anders?
Die Version 2 läuft bei bir 1a und alles ist schön angepasst, bei Version 3 hab ich für mich noch so einige Bausttellen...

**Comment by Zefau** [comment]
Ist ein Bug. Ein Abo für v2 gibt es nicht und wird es nicht geben.

**Comment by SliX185** [comment]
OK, wird behoben oder is v2 End of life?

Frage: Kann man die Pro Lizenz auf verschiedene Systeme übertragen? (Test und Produktiv System)

**Comment by jayjojayson** [comment]
Super, habe mich heute auch gewundert, warum das css nicht mehr angewandt wird. Ich hoffe es kann behoben werden. Sobald ein stable Version von der v3 existiert, werde ich mir die auch zulegen, aber bis dahin wollte ich die v2 nutzen. Grüße

**Comment by Zefau** [comment]
Schaut mal mit 2.2.5

**Comment by jayjojayson** [comment]
Jup, vielen Dank, läuft wieder. :)
