### ISSUE TITLE
Jarvis Fehler IObroker

### ISSUE THREAD

**Issue by bayern07** [Zefau/ioBroker.jarvis#821]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

*![image](https://user-images.githubusercontent.com/84627506/124115514-2d86d180-da6e-11eb-8d10-e760aebc5733.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
> Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!

Ohne Beschreibung, was du gemacht hast, dass der Fehler auftritt oder sonst irgendwelchen Informationen ist es schwierig den Fehler zu beheben.
