### ISSUE TITLE
Fehler beim öffnen Roter Bildschirm mit "Unknown error"

### ISSUE THREAD

**Issue by luft-post** [Zefau/ioBroker.jarvis#822]
Moin,

nach der Installation des Adapters bekomme ich einen Roten Bildschirm mit "Unknown error"

Mein System:
Platform linux
Betriebssystem linux
Architektur arm
CPUs 4
Geschwindigkeit 1500 MHz
Modell ARMv7 Processor rev 3 (v7l)
RAM 7.69 GB
System Betriebszeit 14 T. 13:56:37
Node.js v12.22.1
NPM 6.14.12
Festplatte Größe 117.07 GB
Festplatte frei 94.15 GB
Anzahl der Adapter 348
Betriebszeit 4 T. 10:26:23
Aktive Instanzen 42
Hostname iobroker

und hier der Chrome Konsolen log:
![1](https://user-images.githubusercontent.com/40865649/124117332-4b553600-da70-11eb-8c44-e66545f19247.JPG)

![2](https://user-images.githubusercontent.com/40865649/124117335-4bedcc80-da70-11eb-9106-3b9c21a8d499.JPG)

Ich hoffe Ihr könnt damit was anfangen.

gruß und Dank
Matthias

**Comment by luft-post** [comment]
Moin,
leider besteht der Fehler immer noch :-( 
hab versucht selbst was zu finden, komme aber nicht weiter.

Gruß
Matthias

**Comment by Zefau** [comment]
Jarvis nochmal drüber installieren. Scheinbar findet er einige Dateien nicht

**Comment by luft-post** [comment]
einmal neu installiert. Jetzt kommt eine andere Fehlermeldung.

![3](https://user-images.githubusercontent.com/40865649/124628849-29e5b700-de81-11eb-8074-9b4ed12bfd97.JPG)

**Comment by Zefau** [comment]
Wie installierst du? Hast du 2.2 mal probiert?

**Comment by luft-post** [comment]
ich lösche die Instanz und füge den Adapter wieder neu hinzu.
Bei Version 2.2.0 bekomme ich die selbe Fehlermeldung mit etwas anderen zahlen.

**Comment by luft-post** [comment]
Hier auch nochmal ein Bild dazu...
![4](https://user-images.githubusercontent.com/40865649/124890576-768fd600-dfd8-11eb-9468-5d4eb6b1d988.JPG)

**Comment by luft-post** [comment]
Kann ich den Adapter anders löschen?

**Comment by Zefau** [comment]
Was liegt im iobroker-data Ordner im jarvis Verzeichnis? Das sonst mal manuell löschen und danach neu uploaden.

**Comment by luft-post** [comment]
Hi,
im jarvis/0/ Ordner waren nur vier Bakup.json Dateien. Habe ich manuell gelöscht und Jarvis wieder neu Installiert leider ohne Erfolg! Hab auch mal versucht die 2.1 zu installieren aber auch die geht nicht. Gibt es eine Change etwas mehr Infos über den Fehler zu bekommen? Gibt es Anhängigkeiten zu anderen Adaptern?

gruß

**Comment by Zefau** [comment]
Abhängigkeiten bestehen zu Web-Adapter und Socket-io.
Puffer im Web-Adapter muss aus sein.

Der Inhalte von `/opt/iobroker/node_modules/iobroker.jarvis/www` muss sich in `/opt/iobroker/iobroker-data/files/jarvis` wiederfinden. Das stellt der Befehl `iobroker upload jarvis` grundsätzlich auch sicher (also der allgemeine Adapter-Upload).

Hast du sonst mal komplett neugestartet?

**Comment by luft-post** [comment]
hi,
Web und Socket Adapter sind da und Puffer ist aus.
Hatte unterschiede im Ordnerinhalt festgestellt und dabei rechte Probleme erkannt, diese dann mit den Fixer bereinigt, jarvis gelöscht und wieder neu installiert, neu gestartet aber nach wie vor den selben Fehler :-(

Was sagt den der angezeigte Fehler aus? reactjs.org ist nach meinen Recherchen ja ein online Übersetzung Tool und in diesen Prozess gibt es Schwierigkeiten? Kann ich diesen Vorgang umgehen z.B. jarvis in englich belassen?

Gruß
Matthias

**Comment by luft-post** [comment]
Habe gerade Festgestellt, dass der Fehler nur in der automatischen VIS Erstellung auftritt, wenn ich den Manuellen Weg gehe ist der Fehler nicht da. Kann es sein das sich die Automatik an seltenen HmIP Geräten Stört?

gruß
MAtthias

**Comment by Zefau** [comment]
geh sonst mal auf v3

**Comment by luft-post** [comment]
Moin,
mit V3 geht es jetzt ohne Fehler.

vielen Dank
