### ISSUE TITLE
HTML in StateList Module is only available to Pro users.

### ISSUE THREAD

**Issue by tofrie** [Zefau/ioBroker.jarvis#824]
Kann mir hier bei jemand helfen oder den Fehler erklären? Ich möchte gerne in Jarvis ein Bild meiner Haustür anzeigen lassen. Hierfür greife ich auf einen State in iobroker zu. In dem State ist ein html code hinterlegt. In Jarvis bekomme ich dann die oben genannte Fehlermeldung.

**Comment by Zefau** [comment]
Bitte auf 2.2.1 gehen

**Comment by tofrie** [comment]
Bei mir wird 2.2.0 als latest angezeigt. Ich kann aus ioBroker heraus kein Update starten?

**Comment by Zefau** [comment]
Dann Adapter Liste aktualisieren.

![Screenshot_20210702-075130.png](https://user-images.githubusercontent.com/14368811/124227076-607ea300-db0a-11eb-96cc-a028a9cab600.png)

**Comment by tofrie** [comment]
Fehler ist behoben, vielen Dank!

**Comment by Harry423** [comment]
Hallo seit ein paar Tagen habe ich diese Fehler auch wieder:

![Bildschirmfoto 2021-12-04 um 08 49 28](https://user-images.githubusercontent.com/73777886/144702057-1cb177fa-b314-4aef-b784-18e95a1ed483.jpg)

Version ist (seit längerem) die 2.2.1.

**Comment by Zefau** [comment]
Bitte auf 2.2.5 oder v3 gehen

**Comment by Harry423** [comment]
Ok, danke. Muss ich manuell machen - ist noch nicht im Repository von ioBroker...

**Comment by Zefau** [comment]
2.2.5 sollte im latest sein. Bist du auf stable?

**Comment by Harry423** [comment]
Ja, bin ich auf Github wird es auch angezeigt, im iobroker Admin aber nicht, auch nicht, wenn ich manuell auf updates prüfe...
![Bildschirmfoto 2021-12-04 um 09 04 14](https://user-images.githubusercontent.com/73777886/144702447-fc9d4092-c6e5-47d0-9039-d94eaf920f2f.jpg)

**Comment by Harry423** [comment]
Wenn ich im Exper
![Bildschirmfoto 2021-12-04 um 09 05 54](https://user-images.githubusercontent.com/73777886/144702497-0b3b1a6a-e606-474b-b99b-a56f572419f6.jpg)
tenmodus eine bestimmte Version installieren will geht es nur bis 2.2.1:

**Comment by Harry423** [comment]
manuell auf der Shell geht es auch nicht:

![Bildschirmfoto 2021-12-04 um 09 09 51](https://user-images.githubusercontent.com/73777886/144702589-f0a7f484-8443-4df0-a14f-03051749ec9f.jpg)

**Comment by Zefau** [comment]
Wie gesagt, du hast **stable** eingestellt. v2.2.5 ist im **latest**

**Comment by Zefau** [comment]
In der Konfiguration:

![image](https://user-images.githubusercontent.com/14368811/144702710-1dc12941-1921-4b69-b892-69c4df49da2a.png)

siehe

https://raw.githubusercontent.com/Zefau/ioBroker.jarvis/master/io-package.json

**Comment by Harry423** [comment]
genau:

![Bildschirmfoto 2021-12-04 um 09 20 09](https://user-images.githubusercontent.com/73777886/144702814-a73d8f0a-7cd1-4fbf-ad98-9aabaf0285b6.jpg)

**Comment by Harry423** [comment]
![Bildschirmfoto 2021-12-04 um 09 21 37](https://user-images.githubusercontent.com/73777886/144702853-70f733b5-63f9-471f-a221-4f180261556a.jpg)

**Comment by Zefau** [comment]
Nochmal:
> Wie gesagt, du hast stable eingestellt. v2.2.5 ist im latest

Die Version im stable ist NICHT v2.2.5. Du musst auf latest wechseln, damit dir die Version angezeigt wird.

**Comment by Harry423** [comment]
Sorry, wer lesen kann ist klar im Vorteil :-) Jetzt hat es geklappt und die 2.2.5 ist isntalliert und der Fehler ist weg. Danke für die Geduld...

**Comment by manoloxxl** [comment]
Ich würde mich hier gerne kurz einhängen. Ich versuche aufgrund dieses Fehlers auch meine 2.2.3 auf 2.2.5 zu aktualisieren. Allerdings bekomme ich nur noch 3.x Versionen angezeigt (Stable) und im Latest die Meldung "Bitte wählen Sie eine bestimmte Version von jarvis aus" - allerdings ohne die Chance etwas auszuwählen.

Gibt es noch einen anderen, manuellen Weg von 2.2.3 auf die 2.2.5 zu aktualisieren?

**Comment by mcuiobroker** [comment]
Grundsätzlich sollte man auf die v3 gehen.
Console
`iob upgrade jarvis@2.2.5`

**Comment by manoloxxl** [comment]
> Grundsätzlich sollte man auf die v3 gehen.
> Console
> `iob upgrade jarvis@2.2.5`

Danke!

Ich hab beim Update noch etwas bedenken bezüglich der Nacharbeiten :(
