### ISSUE TITLE
Mini Graph Modul

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#825]
Es wäre schön wenn es eine Möglichkeit gäbe eine kleinen Verlauf ungefähr in der Optik darstellen zu können:
![image](https://user-images.githubusercontent.com/56581564/124245153-0092f700-db20-11eb-8906-ee9257c70dce.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/635
