### ISSUE TITLE
Wetter Modul zeigt keine Icons und Pictogramme

### ISSUE THREAD

**Issue by BurnGerRubber** [Zefau/ioBroker.jarvis#827]
Moin Zefau, ich habe heute erfolgreich das Wettermodul mit daswetter.com eingerichtet. Im Screenshoot auf https://www.smarthome-tricks.de/software-iobroker/iobroker-jarvis-teil-13-darstellung-von-wetter-informationen/ werden schöne Pictogramme für die Bewölkung und die Windrichtung dargestellt:
![image](https://user-images.githubusercontent.com/86915944/124384833-62479280-dcd3-11eb-88d3-64f9980272d2.png)

Diese werden bei mir nicht dargestellt. Auch das umstellen auf ein anderes Iconset oder auf das deaktivieren des Dark Mode in den Theme Einstellungen bringt keinerlei Veränderung:
![image](https://user-images.githubusercontent.com/86915944/124384747-08df6380-dcd3-11eb-9c05-277f3758e2d3.png)

Ich nutze die aktuelle V2.2.1 auf einer aktuellen IOBroker Installation in einem Dockercontainer.
Gruß, Frank.

**Comment by Andi19851985** [comment]
Hallo,

bei mir werden die Symbole seit dem letzten Update von 2.2.0 auf 2.2.1 auch nicht mehr angezeigt.

Gruß Andreas

**Comment by Zefau** [comment]
probiert mal bitte v2.2.2 von Github via https://github.com/Zefau/ioBroker.jarvis/tarball/v2.2.x

**Comment by Andi19851985** [comment]
v2.2.2 zeigt zwar was an sind aber die falschen Symbole.
Anstatt Wetter Icons wird die Windrichtung angezeigt
![Bildschirmfoto 2021-07-05 um 00 48 16](https://user-images.githubusercontent.com/42984555/124401669-f3962380-dd2a-11eb-83e7-983145a70b6a.png)
![Bildschirmfoto 2021-07-05 um 00 48 29](https://user-images.githubusercontent.com/42984555/124401672-fa249b00-dd2a-11eb-81e7-61302c6dabd7.png)

**Comment by Zefau** [comment]
Sehr merkwürdig. Bei mir funktioniert es wieder tadellos. @BurnGerRubber ist das bei dir auch so?
@Andi19851985 kannst du mal einen anderen Browser probieren bzw. den Cache mal löschen?

**Comment by kago76** [comment]
Danke für den Fix. Bei mir funktioniert es auch wieder.
Die Windsymbole hatte ich auch unter "Set 1" - und habe nun auf Icon Set Wetter "Set 5" und Wind auf "Set 2" geändert.
![2021-07-05_163219](https://user-images.githubusercontent.com/30898567/124487330-dd31ab80-ddae-11eb-8f88-f9aace462143.png)

**Comment by Andi19851985** [comment]
Habe es eben nochmal mit den anderen Wetter Icons versucht und siehe da es funktioniert.
Wetter Icons 1-2 wird nur die Windrichtung angezeigt und ab Icons 3 funktioniert alles wie es soll.
Danke für den Fix

**Comment by BurnGerRubber** [comment]
> Sehr merkwürdig. Bei mir funktioniert es wieder tadellos. @BurnGerRubber ist das bei dir auch so?
> @Andi19851985 kannst du mal einen anderen Browser probieren bzw. den Cache mal löschen?

Moin Zefau, mit deiner Version 2.2.2 funzt es, bis auf das Set 1,2 und 5 (White): dort kommen bei mir auch nur Windfähnchen (Browser Cache wurde gelöscht, Problem auf Testsystem reproduzierbar, in Chrome wie in FF). 

Wo kommen die Icons eigentlich her, werden die von daswetter.com recharged oder liegen die direkt im Adapter? Selbige Frage wenn Ich z.B. den Wind nicht in km/h sondern in m/s anzeigen möchte (bin da berufsbedingt etwas vorbelastet): werden diese Einstellungen von daswetter.com vorgegeben?

Gruß, Frank.

**Comment by julknows** [comment]
Hello Guys,

when would this fix - Jarvis 2.2.2 - be available in Std IOBroker update? Is this possible to answer?

MfG
Jul

**Comment by Zefau** [comment]
I can release it tonight if I dont forget

**Comment by julknows** [comment]
Oh, that is fast. But not nessesary. This is not the Main function on earth. Jul
I will wait for the official Release. Thx to all.

**Comment by Zefau** [comment]
released now

**Comment by opl-git** [comment]
Hi, thank you very much for all your hard work on jarvis!

I am looking in iobroker, but can't see the update to 2.2.2. Does it take some time to come up?
Thanks!

**Comment by Zefau** [comment]
Are you on `latest`?

**Comment by opl-git** [comment]
I am on 2.2.1
I can try to use the files you provided here. Do I just have to overwrite the old files in my iobroker folder?

**Comment by Zefau** [comment]
Manually upgrade via https://github.com/Zefau/ioBroker.jarvis/tarball/v2.2.x

**Comment by opl-git** [comment]
Manual upgrade = overwrite old files?

**Comment by Zefau** [comment]
Either via cat Button in iobroker or via cli `iobroker URL <url>`

**Comment by opl-git** [comment]
Thank you!!!
Jarvis and your support is awesome!

**Comment by julknows** [comment]
Hello,

on my PROD iobroker System with wonderful jarvis I have no Icons since a while.
Today I had a little time and did a test install on my 2nd Rasp4B.
- default Raspi without Desktop
- default iobroker
- default jarvis (2.2.1)
- default settings
- jarvis manual

Info iobroker
PlatformBetriebssystem:linux
Architektur:arm
CPUs:4
Geschwindigkeit:1500 MHz
Modell:ARMv7 Processor rev 3 (v7l)
RAM:3.7 GB
System-Betriebszeit:00:04:41
Node.js:v14.18.2
NPM:6.14.15
Datenträgergröße:109.8 GB
Festplatte frei:107.6 GB
Adapter-Anzahl:364
Betriebszeit:00:04:48
Aktive Instanzen:3
Pfad:/opt/iobroker/

![Screenshot_20211209_192155](https://user-images.githubusercontent.com/87308746/145454103-e259215e-8b30-4254-8b02-2b44fb28f818.png)
![Screenshot_20211209_192414](https://user-images.githubusercontent.com/87308746/145454112-86720803-d207-435d-b4b7-5b73e1a97d0e.png)

Maybe I did an mistake. I can share further Information to fix to Issue.

Berti

**Comment by mcuiobroker** [comment]
You have to update to 2.2.5 (beta) and look to forum
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/5820

**Comment by julknows** [comment]
Hello,

sorry - i did read the history of THIS.
Upgrade to "latest" did fix it - jarvis 2.2.5 - when it comes to "stable"?

![Screenshot_20211209_193938](https://user-images.githubusercontent.com/87308746/145456093-9bbbb4cb-e8ea-4d04-ac68-41b9e0056fae.png)

Berti
