### ISSUE TITLE
Icons could not be loaded after update to 2.2.1

### ISSUE THREAD

**Issue by wzwerch** [Zefau/ioBroker.jarvis#830]
I'm using currently jarvis 2.2.1 with IOBroker 4.2.1 (nodejs 14.0.0, npm 6.14.4)

After the update to 2.2.1 the icons are disappeared (see screenshot)  and even manually change some entries did not help.

![image](https://user-images.githubusercontent.com/36817146/125195162-c084f000-e254-11eb-958e-9302f0f036c8.png)

Browser Konsole:
main.839b8a57.chunk.js:1 App # Welcome to jarvis 2.1.0
main.839b8a57.chunk.js:1 App # You are on instance jarvis.0.
main.839b8a57.chunk.js:1 Connection # Connection URL (undefined) found in cache.
main.839b8a57.chunk.js:1 Connecting to http://ubuntuserver:8084 ..
main.839b8a57.chunk.js:1 Connected to http://ubuntuserver:8084.
main.839b8a57.chunk.js:1 App # Processed 74 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  Object
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
15a4cbef:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
15a4cbef:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
materialdesignicons-webfont.woff2:1 Failed to load resource: the server responded with a status of 404 (Not Found)
az416426.vo.msecnd.net/scripts/b/ai.2.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
az416426.vo.msecnd.net/scripts/b/ai.2.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
15a4cbef:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
15a4cbef:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
az416426.vo.msecnd.net/scripts/b/ai.2.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
az416426.vo.msecnd.net/scripts/b/ai.2.min.js:1 Failed to load resource: net::ERR_BLOCKED_BY_CLIENT
materialdesignicons-webfont.woff:1 Failed to load resource: the server responded with a status of 404 (Not Found)
materialdesignicons-webfont.ttf:1 Failed to load resource: the server responded with a status of 404 (Not Found)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
snapshot_720.jpg:1 Failed to load resource: the server responded with a status of 403 (Forbidden)
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/js/4.0dffea49.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/js/main.839b8a57.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/js/7.1d0b13aa.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/js/8.d097babb.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/js/1.87816d5e.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/js/0.52344b92.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/js/6.f498920d.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/js/5.934bcae2.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/vendor/materialdesignicons.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/css/5.1a719957.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
DevTools failed to load source map: Could not load content for http://ubuntuserver:8082/jarvis/static/css/main.45d5d0e8.chunk.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)
snapshot_720.jpg:1 GET https://prodvpn-eu-5.netatmo.net/restricted/10.255.83.238/3d1c7e8b8205b23e77ff1e1e5abf102a/MTYxODc3NjAwMDqWKzlyRDB8cQ0jQ_OKVThIBcssCA,,/live/snapshot_720.jpg 403 (Forbidden)

Every help his highly appreciated. 

Thanks

Wolfgang

**Comment by Zefau** [comment]
Probier mal bitte die v2.2.2, siehe https://github.com/Zefau/ioBroker.jarvis/issues/827#issuecomment-873675042

**Comment by Zefau** [comment]
btw: das Log (das du oben gepostet hast) sagt, dass du noch auf 2.2.0 bist. Insofern müsstest du den Cache nochmal leeren, damit 2.2.1 im Frontend aktualisiert wird.
