### ISSUE TITLE
V3 alpha 24: Sonnenauf- und Untergang

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#831]
Bei der Uhr lässt sich Sonnenauf- und Untergang nicht ausstellen:
![image](https://user-images.githubusercontent.com/56581564/125244665-e14e5380-e2ef-11eb-9a52-71e1420c8f2e.png)

![image](https://user-images.githubusercontent.com/56581564/125244710-ef9c6f80-e2ef-11eb-8e26-ee209e870764.png)

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.25`.

**Comment by WW1983** [comment]
Funktioniert. Kann geschlossen werden.

Danke.
