### ISSUE TITLE
V3 alpha 24: Kalender zeigt keinen Inhalt

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#832]
Kalender wird links, nicht zetriert angezeigt. Zudem werden keine Termine angezeigt:
![image](https://user-images.githubusercontent.com/56581564/125244941-3ab68280-e2f0-11eb-91c6-3f7f33fd5931.png)

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.25`.

**Comment by WW1983** [comment]
Kalender zeigt wieder Inhalt an.

Lässt sich aber im Widget nicht zentrieren. Kann man auch den Hintergrund des Kalenders transparent machen, oder einstellbar?`
Hier mal zum Vergleich:
Version 3:
![image](https://user-images.githubusercontent.com/56581564/125397307-0b664b00-e3ae-11eb-9bde-c9aea6c9d926.png)


Version 2.2
![image](https://user-images.githubusercontent.com/56581564/125397368-220ca200-e3ae-11eb-9056-669784f71fca.png)

**Comment by Zefau** [comment]
Ist bei mir eigentlich ohne Rahmen und auch zentral. Kannst du mal in den Styles schauen, ob die drin sind und ggf.  überschrieben werden?

**Comment by WW1983** [comment]
Ich habe den Style Inhalt mal komplett gelöscht. Leider immer noch das selbe Ergebnis

**Comment by WW1983** [comment]
Falls es hilft. Hier ist die Console:
![image](https://user-images.githubusercontent.com/56581564/125400238-f4c1f300-e3b1-11eb-92c3-a3858ae5de5e.png)

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.0-alpha.26`.

**Comment by WW1983** [comment]
Leider nein.
![image](https://user-images.githubusercontent.com/56581564/125740174-8c858025-426e-4c3c-8001-8fb6ef683f37.png)


Aber ich frage mich ob deine Vermutung vielleicht stimmt und es am CSS Style liegt. Ich habe zwar alles raus gelöscht, aber die Farben im Darkmode haben sich nicht verändert (hatte über CSS Style etwas dunklerer Töne als im original Darkmode). Vielleicht hängt die Info noch irgendwo im Hintergrund?

Vielleicht kann jemand anderes mal testen ob er das selbe Problem hat.

**Comment by Zefau** [comment]
`Horizontal alignment` hast du auf `center` ?

![image](https://user-images.githubusercontent.com/14368811/125985853-75ef6dde-b151-4a65-a8da-86c19921fd47.png)


Kannst du mal in den DevTools schauen, was er dort hinterlegt?
Rechtsklick -> Inspect und dann auf das Element fokussieren.

![image](https://user-images.githubusercontent.com/14368811/125985797-2e520a9d-c3bd-4b8b-8760-335a0b5b9fca.png)


Das `div` mit der `class` `widget-scaler` muss im `style` die folgenden Einträge haben (siehe Screenshot; rechte Sidebar unter `element`):
```
transform: scale(0.644654);
transform-origin: 50% top 0px;
```

Wobei der Wert bei `scale` ein anderer sein könnte.

**Comment by WW1983** [comment]
![image](https://user-images.githubusercontent.com/56581564/126135250-a8a78f62-ddf7-45bf-8a2f-036bebed34a3.png)
Steht bei mir eigentlich so.

Auch bei der Einstellungen ist bei Horizontal alignment "center" ausgewählt
![image](https://user-images.githubusercontent.com/56581564/126135526-709c9d03-ebd9-48e9-b708-46b8ae79c632.png)

**Comment by Zefau** [comment]
@WW1983 besteht das Problem mit der aktuellen v3 alpha noch? Du bist glaube ich von ioBroker weg oder? Hatte ich das richtig in Erinnerung?

Ich verstehe leider nicht, warum es bei dir nicht funktioniert.

Die Sachen werden korrekt übernommen, also insbesondere
```
    transform: scale(1);
    transform-origin: 50% top 0;
```

Bei mir sieht es nicht viel anders aus bzgl. dessen. Allerdings funktioniert das Zentrieren.

![image](https://user-images.githubusercontent.com/14368811/133443015-2cd90a58-c8d8-4ba9-ac3e-2c0889021831.png)

**Comment by Zefau** [comment]
@mcuiobroker wird der Kalender bei dir korrekt zentriert, wenn im Widget so konfiguriert?

**Comment by Zefau** [comment]
@mcuiobroker

**Comment by mcuiobroker** [comment]
Es kommt keine Agenda
![image](https://user-images.githubusercontent.com/84818934/135707876-ac1dc274-683b-4340-9294-1f8bdfd4de3c.png)

**Comment by Zefau** [comment]
Seltsam, bei mir funktioniert es in Firefox und Chrome.
