### ISSUE TITLE
V3 alpha 24: Wetter wird nicht geladen

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#833]
Das Wetter wird  nicht geladen:
![image](https://user-images.githubusercontent.com/56581564/125245181-89641c80-e2f0-11eb-8993-9f070843b362.png)

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.25`.

**Comment by WW1983** [comment]
Funktioniert. Kann geschlossen werden.

Danke.
