### ISSUE TITLE
V3 alpha 24: Return to Homepage ohne Funktion

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#834]
Die Funktion "Return to Homepage" scheint nicht zu funktionieren.

![image](https://user-images.githubusercontent.com/56581564/125245615-114a2680-e2f1-11eb-8fc5-d00d3975ac0d.png)

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.25`.

**Comment by WW1983** [comment]
Funktioniert. Kann geschlossen werden.

Danke.
