### ISSUE TITLE
V3 Höhe Widgets u. Schriftgröße Uhrzeit / Datum

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#835]
Könntest du vielleicht die Mindesthöhe der Widgets etwas geringer einstellen. Bei Uhrzeit u. Datum ist recht viel Platz da drunter.

Bei der Uhrzeit konnte man in der Version 2.2 die Schriftgröße einstellen. Das fehlt bei der V3

![image](https://user-images.githubusercontent.com/56581564/125437507-12fab9ad-9f97-436c-b211-564b917eedde.png)

**Comment by Zefau** [comment]
Du kannst die Mindesthöhe der Widgets selbst einstellen im Layout.

**Comment by WW1983** [comment]
> Du kannst die Mindesthöhe der Widgets selbst einstellen im Layout:
> 
> ![image](https://user-images.githubusercontent.com/14368811/125509047-5084ac56-2fdc-4f41-996b-ac6af4b4048c.png)

Stimmt! Habe ich übersehen. Danke. So funktioniert es

**Comment by Zefau** [comment]
Und Schriftgröße geht mit CSS, oder?

**Comment by WW1983** [comment]
Im Grunde sollte es mit CSS gehen (habs aber noch nicht getestet). Weiss nur nicht wie

**Comment by WW1983** [comment]
Scheint irgendwie nicht zu funktionieren:
![image](https://user-images.githubusercontent.com/56581564/125747677-4bdea04f-725b-4b7d-ab71-4dd974d1bbea.png)

**Comment by WW1983** [comment]
Habe ich was falsches eingegeben?

**Comment by Zefau** [comment]
Versuch Mal mit `!important` hinter dem Befehl

**Comment by WW1983** [comment]
Habe gesehen das ich die falsche Classe ausgewählt habe... aber funktioniert denoch bedingt.

Wenn ich die Schriftgröße ändere. Merke ich Änderungen bis 35px (auch hier zentriert er nicht). Danach verschiebt sich alles:

![image](https://user-images.githubusercontent.com/56581564/125761667-f53ab378-5c33-491d-a1cd-aeaf0d22f682.png)

Bei 40px:
![image](https://user-images.githubusercontent.com/56581564/125761738-8162b080-3027-4e72-bf14-1e645e4ccc15.png)

**Comment by WW1983** [comment]
Hat sich gerade erledigt. Wenn die Textgröße nicht genügend Platz hat, wird es sich so aus. Habe die eben größer gezogen und schon geht es 
![image](https://user-images.githubusercontent.com/56581564/125762579-9deceb80-0927-4a2b-9f16-ec43dc94276f.png)


Das Thema kann also geschlossen werden. 

Danke
