### ISSUE TITLE
V3 - HomeKitTile

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#836]
DIe Anordnung der Elemente scheint bei HomeKitTile nicht zu passen:
![image](https://user-images.githubusercontent.com/56581564/125438424-421b0364-b394-4aae-a09b-a94f490528fe.png)

Einstellung:
![image](https://user-images.githubusercontent.com/56581564/125438534-bd09b868-4cf3-4a13-a5a9-4c58bac6879e.png)

Es wäre auch schön wenn man die gesamte Fläche als Trigger nutzen könnte

**Comment by Zefau** [comment]
Wie sind denn die Devices im unteren Bereich konfiguriert? Das ist im Screenshot abgeschnitten?
Welche Größe haben die Widgets?

Bei mir passt es:

![image](https://user-images.githubusercontent.com/14368811/125993012-746ac0a8-f15e-44b3-807f-6dc933f7b70e.png)
(das eine Widget ist bewusst leer; die anderen beiden Widgets verweisen auf dieselbe Konfiguration)

![image](https://user-images.githubusercontent.com/14368811/125993122-8ba50876-5a88-46e6-ab6b-0aa2d561538a.png)

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.29`
Input-Action funktioniert nicht.
![image](https://user-images.githubusercontent.com/84818934/126049561-5183c049-ccf4-4e87-bd27-378d5298389b.png)
![image](https://user-images.githubusercontent.com/84818934/126049567-b839179a-b8c2-481b-874c-88a44e53fd13.png)
![image](https://user-images.githubusercontent.com/84818934/126049573-26fcbfd4-517d-4c94-866e-cd32e623ffb6.png)

Trigger-Element wird als actionElement angezeigt:
![image](https://user-images.githubusercontent.com/84818934/126049584-f138d17f-d421-4354-9ea9-b99450f219dc.png)

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.30` behoben. Auch gibt es eine zusätzliche Option im Modul bzgl. des Popups, interner Seite oder externer Website.

**Comment by WW1983** [comment]
Ich weiß nicht woran es lag. Zeigt es aber jetzt normal an.

Du hast mehrer Funktion hinzugefügt das beim Klick zB Popup aufgerufen werden kann.

Kannst du auch eine Funktion hinzufügen das es Trigger ausgelöst wird. ZB Licht und die einschalten. Also wie ein großer Button

**Comment by mcuiobroker** [comment]
Standard-Einstellung bei Konvertierung sollte diese sein, da es in v2.2.2 auch so war.
![image](https://user-images.githubusercontent.com/84818934/126076768-205a606e-e58f-4534-8ffa-8a42a0da82bf.png)

**Comment by mcuiobroker** [comment]
Icon-Farbe wird nicht angepasst
![image](https://user-images.githubusercontent.com/84818934/126077754-fd9f3ffe-9f75-42c8-83b6-967575b6b731.png)
![image](https://user-images.githubusercontent.com/84818934/126077763-99db2568-0665-4753-bd3c-092fdcc969e4.png)

**Comment by Zefau** [comment]
@WW1983 mit `v3.0.0-alpha.31` gibt's die Option nun. 
@mcuiobroker Standardeinstellung und Style des Icons sollte passen.

**Comment by mcuiobroker** [comment]
Style passt, Standardeinstellung?
Für die Elemente, die z.B. IconButton als Trigger-Element haben, hatte man in v2.2.2 ja mehr als 3 Elemente zur Verfügung. Jetzt sollte in v3, da nur 3 Elemente vorhanden sind, das Icon auch das IconButton sein.
v3:
![image](https://user-images.githubusercontent.com/84818934/126082520-a7bd4432-3e65-44d0-ac0f-07ea5c3f9a06.png)
Klicke ich auf das Icon wird das Popup aufgerufen.
Sinnvoller wäre die Funktion auszuführen vom IconButton(Trigger-Element). Und dort entsprechend das Icon anzupassen (normalerweise ist es mdi:power, dort wäre mdi:play).
Aussderdem erkennt man nach der Änderung im PLAY auf IconButton oben, dass es in der Ansicht nicht mehr zu den anderen Elementen passt. Man hat also für Elemente (HomeKitTile unterschiedliche Höhe in den Bereichen).
![image](https://user-images.githubusercontent.com/84818934/126082662-f045fde6-56fe-4ba6-bfbf-c2dc29bb2fd3.png)
Das Play-Icon scheint nicht an der gleichen Stelle zu sein als Trigger-Element und Icon.
Trigger Action ist ja jetzt auch möglich, dann sollte man bei Konvertierung mit vorhandenem Trigger-Element dort im Action bei Klick 
![image](https://user-images.githubusercontent.com/84818934/126082790-119bcd1f-2b3b-42f9-ac0e-fff807adccaf.png)
Trigger-Action als Standard eintragen.

Wo kann man denn die Secondary Werte eintragen (waren in v2.2.2 da) ? Die fehlen?

**Comment by Zefau** [comment]
> Jetzt sollte in v3, da nur 3 Elemente vorhanden sind, das Icon auch das IconButton sein.

Dann einfach statt `Icon` den `IconButtonAction` nehmen?

>  Sinnvoller wäre die Funktion auszuführen vom IconButton(Trigger-Element). Und dort entsprechend das Icon anzupassen (normalerweise ist es mdi:power, dort wäre mdi:play).

Ist mit drin. Kannst du im Dropdown wählen.

>  Aussderdem erkennt man nach der Änderung im PLAY auf IconButton oben, dass es in der Ansicht nicht mehr zu den anderen Elementen passt. Man hat also für Elemente (HomeKitTile unterschiedliche Höhe in den Bereichen).

Behoben mit `v3.0.0-alpha.32`.

> Wo kann man denn die Secondary Werte eintragen (waren in v2.2.2 da) ? Die fehlen?

Hinzugefügt mit `v3.0.0-alpha.32`.

**Comment by mcuiobroker** [comment]
State wird nicht mehr angezeigt und Blink-Effekt nicht mehr, nur im Popup
![image](https://user-images.githubusercontent.com/84818934/126224855-0012b81f-bcaf-4c6c-9b00-b7b448663711.png)
![image](https://user-images.githubusercontent.com/84818934/126224995-0c44d8fa-203c-4d7e-a06a-4ca95384ff12.png)
![jarvis_v300-alpha-32-homekittile-State-blink](https://user-images.githubusercontent.com/84818934/126225240-41f81458-7ad7-4414-9682-871d1a254ad0.gif)

**Comment by Zefau** [comment]
bitte schau nochmal mit `v3.0.0-alpha.33`.

**Comment by mcuiobroker** [comment]
State wird angezeigt und es blinkt wieder. Prima.

**Comment by mcuiobroker** [comment]
Mit v3.0.0-alpha.42
Einträge sind auf dem Tablet nicht zentriert bzw. Werden nicht korrekt angezeigt.
![20210801_045659.jpg](https://user-images.githubusercontent.com/84818934/127757685-c8991733-8fd2-437f-b8cf-eb6cf77dfb3c.jpg)

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.0.0-alpha.45`.

**Comment by mcuiobroker** [comment]
Ist wieder ok:
![image](https://user-images.githubusercontent.com/84818934/127975842-bbd79ac7-ba84-4682-867e-7a2395443490.png)

**Comment by mcuiobroker** [comment]
Selektionsfläche onFocus fehlt bzw. wird nicht angezeigt:
![image](https://user-images.githubusercontent.com/84818934/128147740-bceb8bd3-921c-4e93-87aa-7fff2636342f.png)

**Comment by Zefau** [comment]
Was ist das?

**Comment by Zefau** [comment]
probier mal `v3.0.0-alpha.48`

**Comment by mcuiobroker** [comment]
Ja passt.

**Comment by Zefau** [comment]
besteht der Fehler mit `v3.0.0-alpha.49` noch? Hast du einen Fehler in der Browser-Konsole?

**Comment by mcuiobroker** [comment]
Ja:
![image](https://user-images.githubusercontent.com/84818934/128550534-5234b053-5468-43bf-8f82-885e7ad547b6.png)

**Comment by Zefau** [comment]
Verstehe nicht, warum er bei dir keine Werte mehr im Popup zeigt. Funktioniert bei mir völlig normal mit Firefox und Chrome. Du hast keine Fehler (rot) in der Browser-Konsole, oder? Sehe nur Warnungen (die - außer die Fonts - alle nichts mit jarvis zu tun haben).

**Comment by mcuiobroker** [comment]
Mit `v3.0.0-alpha.61`bekomme ich nur am Anfang eine Meldung:
![image](https://user-images.githubusercontent.com/84818934/131734986-283bc016-4c5f-4cdf-84b5-4783cc8d1a10.png)

Auch mit Firefox keine Anzeige von den Elementen:
![image](https://user-images.githubusercontent.com/84818934/131735097-e88b6932-ffa9-4205-ab84-8f6ac55379ba.png)

**Comment by mcuiobroker** [comment]
Vielleicht noch zur Info js-controller: 3.3.15, node-js:12.22.5

**Comment by mcuiobroker** [comment]
Wurde in `v3.0.0-alpha.63` was in der Konvertierung für Homekittile gemacht? Soll ich nochmal auf `v2.2.3` zurück um es zu testen?

**Comment by Zefau** [comment]
Nein. Sofern ich etwas anpasse kommentiere ich das entsprechend.

**Comment by Zefau** [comment]
Den Fehler im Popup verstehe ich nach wie vor nicht. Die Größe des HomeKitTile ist kein Fehler, sondern einfach zu klein. Musst du manuell vergrößern?

**Comment by mcuiobroker** [comment]
Dies "zu klein" kommt von der Konvertierung, war vorher nicht so. Das wird bei allen anderen dann auch so sein.

**Comment by Zefau** [comment]
ah ok

**Comment by Zefau** [comment]
> Dies "zu klein" kommt von der Konvertierung, war vorher nicht so. Das wird bei allen anderen dann auch so sein.

Ist mit `v3.0.0-alpha.62` beseitigt. Das andere schaue ich mir morgen nochmal genauer an.

Der Fehler mit den Popups kommt in allen Popups vor? Auch, wenn du deine individuellen CSS Styles entfernst und sowohl im Black- als auch White-Mode?

**Comment by mcuiobroker** [comment]
Ja. Der Fehler mit den Popups kommt in allen Popups vor. Dort werden nur Inputs und Schalter angezeigt.
Auch in Dark (off/on).

**Comment by Zefau** [comment]
Versuch nochmal mit `v3.0.0-alpha.65`. Sollte das nicht gehen, muss ich ein Debug-Release mit vielen Debug-Meldungen machen, um dem Fehler auf den Grund zu gehen.

**Comment by mcuiobroker** [comment]
Das mache ich sofort. Den Rest morgen.

**Comment by mcuiobroker** [comment]
Siehe Ausführungen zur Versionanzeige neben Konfiguration. 
Durch die Konvertierung (.61) wurde im Gerät oder in den Geräten Datenpunkt-Wert anzeigen.... standardmäßig auf "off".

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/issues/944 bzgl. Popup

> Konvertierung anpassen bzgl Höhe in der Ausgabe vom HomeKitTile

HomeKitTile sollte mit `v3.0.0-alpha.65` nun nach der Konvertierung 2 Einheiten hoch sein, also 2 * 50px = 100px. 


Ist in diesem Issue noch etwas offen außer die Höhe von HomeKitTile?

**Comment by Zefau** [comment]
done via `v3.0.0-alpha.65` / `v3.0.0-alpha.66`

**Comment by mcuiobroker** [comment]
Hab den offenen Punkt rausgenommen. Dies kann sonst geschlossen werden.
