### ISSUE TITLE
Crash whilse scrolling

### ISSUE THREAD

**Issue by Tim2605** [Zefau/ioBroker.jarvis#837]
Using a Samsung A70 with chrome.
If I open a jarvis visualization and scroll down, at the end I get a crash. On a Samsung S20 with the same Andriod version and chrome version all works fine. Settings in chrome are the same. Undepending which tab. My tabs have most 3 columns.  If I reach the end the crash happens. Jarvis 2.2.1 is running.
There is no diffference if I connect via iobroker.pro or locally direct via IP. Problem is the same. 

![IMG-20210711-WA0001](https://user-images.githubusercontent.com/87369855/125443018-712d74a6-72f6-4ca9-bc3b-70b244a02b4d.jpg)

**Comment by Zefau** [comment]
please move to v3
