### ISSUE TITLE
Trennstrich zwischen Überschrift und Modul (als Option)

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#838]
_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/770#issuecomment-877871293_
> Mit `v3.0.0-alpha.23`kommt jetzt plötzlich in allen Modulen ein Trennstrich zwischen Überschrift und Modul
![image](https://user-images.githubusercontent.com/84818934/125211767-f9e74b00-e2a8-11eb-99b6-daff7a2ffed6.png)
Wenn das so sein soll, dann bitte als Option. Dort ohne Trennstrich glaube ich gefällt es einigen besser. Und wenn dann sollte der Typ auswählbar (-.-.-.-,  - - - - -,  . . . . .  ) .

**Comment by mcuiobroker** [comment]
Da es in v2 nicht drin war, sollte es jetzt als Option in den Theme-Einstellungen möglich sein, es abzuschalten. Danke.

**Comment by Zefau** [comment]
implemented with `v3.0.0-alpha.79`.

**Comment by mcuiobroker** [comment]
Kannst du bitte in der Konvertierung diesen Wert (Hide speparator) dann standardmäßig auf "true" setzen. Denn so war es ja auch in v2.
Danke.

**Comment by Zefau** [comment]
Konvertierung setzt den Wert nun im Standard auf `true` mit `v3.0.0-alpha.80`.

**Comment by mcuiobroker** [comment]
Funktioniert.
