### ISSUE TITLE
No Weather Icons after upgrade to 2.2.1 - no fix with 2.2.2

### ISSUE THREAD

**Issue by julknows** [Zefau/ioBroker.jarvis#839]
ioBroker jarvis Adapter works fine
![118E9F7B-39FA-4791-B259-7A8340426B7F](https://user-images.githubusercontent.com/87308746/125562574-95df9165-8040-499c-ad9c-71d9e1593977.png)
. 
Only my weather Widget does make problems and would not show Weather Icons.

**Prerequisites / Voraussetzungen**
I switched on Beta an use jarvis 2.2.2

**Describe the bug / Beschreibe den Fehler**
There are no Icons (sun, cloud, …) for day or overview - see screen.
Nothing to jarvis found in ioBroker log.
No change after upgrade to 2.2.2 and restart and define new Widget Witz default settings.
No Icons with other Sets.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by duczz** [comment]
Same Problem

**Comment by Zefau** [comment]
did you try the different sets?

**Comment by julknows** [comment]
Hello,
Yes I did. I am not Sure that each combi. But all Sets testet.
Jul

**Comment by duczzz** [comment]
Any News?

**Comment by duczzz** [comment]
@Zefau Funktioniert in 2.2.3 auch noch nicht, bleibt das so, lief ja davor wäre echt schade wenn's nur in der v3 gefixt wird?
Es wird der Wind anstatt dem Wetter angezeigt

**Comment by duczz** [comment]
Passiert hier noch was?
![image](https://user-images.githubusercontent.com/25475385/140020564-91ab807a-ba3b-421d-9ed3-940422ff8a55.png)

**Comment by Zefau** [comment]
Bitte auf v3 gehen
