### ISSUE TITLE
no access to jarvis adapter

### ISSUE THREAD

**Issue by t2d234** [Zefau/ioBroker.jarvis#840]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by t2d234** [comment]
I am using jarvis version 2.2.1
Opening the adapter web site is not possible (see Screenshot). I tried to delete the instance and to delete the adapter itself from iobroker with reinstalling afterwards -> no success.
![Unbenannt](https://user-images.githubusercontent.com/87430889/125633250-a6afd537-e586-4b11-9a0e-714bf8ce0e9a.png)

**Comment by Zefau** [comment]
Do you have the Web Adapter installed? Did you try to upload the jarvis instance?

**Comment by t2d234** [comment]
Oh no, that was the problem. 
Thanks for your quick answer.
