### ISSUE TITLE
Error #31 after auto-generating the configuartion

### ISSUE THREAD

**Issue by TheKilroy** [Zefau/ioBroker.jarvis#842]
I have just installed Jarvis 2.2.2 on a Raspberry Pi4
Install was OK and while generating an automatic configuration the error message #31 appeared (see attached screenshot)

Important might be the fact that the server and the devices are in a remote network. The browser with the desktop is located in a local network.

Remote network: 192.168.1.0/24
Local network: 192.168.99.0/24
The connection between both networks is not very fast. It is a WiFi connection between to buildings. The remote network must route all traffic to the internet via the local network.

I will try to remove the adapter and will NOT generate an automatic configuration.

![grafik](https://user-images.githubusercontent.com/10958959/125962844-8d6adea4-eb29-45a1-962a-2adb88e8a569.png)

**Comment by TheKilroy** [comment]
Re-installed the instance and used manual creation and now I got a step further. 
Clicking the continue button now brought another error.

![grafik](https://user-images.githubusercontent.com/10958959/125964626-4f5c4290-438a-44fe-9760-515489227d95.png)

**Comment by TheKilroy** [comment]
Works when adding devices manually.

I also have a Raspberry Pi4 for testing in the local network. Here it worked fine and generated a usable configuration.

**Comment by Zefau** [comment]
Probably best if you start with v3

**Comment by TheKilroy** [comment]
OK ... will give it a try.

**Comment by Zefau** [comment]
please move to v3
