### ISSUE TITLE
v3: iFrame wird bei jedem TAB-Aufruf neu aufgebaut

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#843]
`v3.0.0-alpha.28 und vorher` Der Inhalt vom iFrame wird immer beim TAB-Wechsel neu aufgebaut.

![image](https://user-images.githubusercontent.com/84818934/125999155-2d78adb4-05b5-4d05-b549-2b70f1180f20.png)

Dies sollte nur dann neu aufgebaut werden, wenn sich die Ihalte ändern oder die angebene Zeit abgelaufen ist.

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.30` nun mit neuer Option mit der der Benutzer entscheiden kann, ob das iFrame im Hintergrund offen bleiben kann oder geschlossen werden soll (z. B. bei Video-Streams)

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha-30` trotz neuer Einstellung bleibt das Problem bestehen:
![image](https://user-images.githubusercontent.com/84818934/126076519-988dda54-3497-4945-b910-6d0b1f355b34.png)
Bei TAB-Wechsel wird neuaufgebaut.

**Comment by Zefau** [comment]
Könntest du ein kurzes Video machen, wie es bei dir aussieht?

**Comment by mcuiobroker** [comment]
![jarvis_v300-alpha30-iFrame-update-Problem](https://user-images.githubusercontent.com/84818934/126078037-01e01803-08b1-417d-898d-1f05c030317b.gif)

**Comment by mcuiobroker** [comment]
Den Slider-Effekt bei TAB-Wechsel kann man den abschalten?

**Comment by Zefau** [comment]
Ein kleiner Delay lässt sich mit v3 nicht vermeiden.

In v2 sind alle Tabs immer geöffnet, nur versteckt. Ein Trick für die Geschwindigkeit. In v3 werden Tabs geschlossen, da sonst insbesondere bei iFrame für Kameras viele Daten anfallen, wenn diese geöffnet bleiben (https://github.com/Zefau/ioBroker.jarvis/issues/660).

Die mit diesem Issue hinzugefügte Option verschiebt das iFrame aus dem Tab heraus in eine übergeordnet Instanz. Ein frickliger Workaround. Dadurch aber der kleine zeitliche Versatz, der in deinem Video zu sehen ist. Bei iFrame mit großen Daten aber hilfreich.

Kannst du das Flot-Chart nicht theoretisch über DisplayImage einbinden?

**Comment by mcuiobroker** [comment]
DisplayImage funktioniert nicht mit HTTP
![image](https://user-images.githubusercontent.com/84818934/126080924-79896fc1-5573-49a9-9a4e-783e892bd04c.png)
![image](https://user-images.githubusercontent.com/84818934/126080945-efb16a6b-b2a1-47c0-8006-c8541ba4a17e.png)
![image](https://user-images.githubusercontent.com/84818934/126080951-fa768d74-2bd4-493f-9bba-a9908e885747.png)
![image](https://user-images.githubusercontent.com/84818934/126080957-728c41de-6122-408d-ad5c-bd689cb0889c.png)

**Comment by Zefau** [comment]
Kannst du mal via Rechtsklick -> Inspect im DOM (also in der gerenderten Seite) schauen, was dort drin steht?

**Comment by mcuiobroker** [comment]
Momentan ohne Image:
`<div class="box" style="grid-area: 1 / 9 / span 4 / span 4;"><div class="jarvis-widget widget bgcolor paper jarvis-widget-26a30160-30fe-43a2-9c5f-148c827fd02e"><div class="jarvis-module module full-width full-height q-card q-card--dark q-dark q-card--flat no-shadow jarvis-module-iFrame"><div class="q-item q-item-type row no-wrap jarvis-widget-header q-item--dark"><div class="q-item__section column q-item__section--side justify-center cursor-pointer"><div class="q-avatar widget-icon jarvis-widget-icon rounded-borders"><div class="q-avatar__content row flex-center overflow-hidden" style="font-size: 24px;"><span><span><svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" aria-hidden="true" role="img" class="iconify iconify--mdi icon-sm" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 24 24" data-icon="mdi:home" style="vertical-align: text-bottom;"><path d="M10 20v-6h4v6h5v-8h3L12 3L2 12h3v8h5z" fill="currentColor"></path></svg></span></span></div></div></div><div class="q-item__section column q-item__section--main justify-center"><div class="q-item__label text-h6 cursor-pointer">
					Temperaturen
				</div></div></div><hr role="separator" aria-orientation="horizontal" class="q-separator q-separator q-separator--horizontal q-separator--dark"><div class="jarvis-widget-content widget-content q-card__section q-card__section--horiz row no-wrap"><div class="widget-scaler full-width" style="transform: scale(1); transform-origin: 50% top;"><div class="full-height full-width" _widgetsize="[object Object]" containersize="[object Object]" config="[object Object]" widgets="26a30160-30fe-43a2-9c5f-148c827fd02e" page="[object Object]"><div role="progressbar" aria-valuemin="0" aria-valuemax="1" class="q-linear-progress" style="display: none;"><div class="q-linear-progress__track absolute-full q-linear-progress__track--with-transition q-linear-progress__track--dark" style="transform: scale3d(1, 1, 1);"></div><div class="q-linear-progress__model absolute-full q-linear-progress__model--with-transition q-linear-progress__model--indeterminate" style="transform: scale3d(1, 1, 1);"></div></div><div data-v-de492ae0="" class="Alert q-ma-sm" style="background-color: rgba(242, 192, 55, 0.2); color: rgb(242, 192, 55); border-color: rgb(242, 192, 55); display: none;"><div data-v-de492ae0="" class="AlertIcon"><i data-v-de492ae0="" aria-hidden="true" role="presentation" class="mdi mdi-alert q-icon notranslate" style="font-size: 38px;"> </i></div><div data-v-de492ae0="" class="AlertBox"><p data-v-de492ae0="" class="AlertMessage">false</p></div></div><div></div></div></div></div></div></div></div>`

Meintest Du zum DisplayImage?

**Comment by mcuiobroker** [comment]
in Chrome mit Displayimage:
`Cross-Origin Read Blocking (CORB) blocked cross-origin response http://192.168.178.89:8082/flot/index.html?l%5B0%5D%5Bid%5D=zigbee.0.00158d0002b6fcf8.temperature&l%5B0%5D%5Binstance%5D=history.0&l%5B0%5D%5Boffset%5D=0&l%5B0%5D%5Baggregate%5D=minmax&l%5B0%5D%5Bcolor%5D=%23FF0000&l%5B0%5D%5Bmin%5D=18&l%5B0%5D%5Bmax%5D=30&l%5B0%5D%5Bthickness%5D=3&l%5B0%5D%5Bshadowsize%5D=3&l%5B0%5D%5Bunit%5D=%C2%B0C&l%5B0%5D%5Bname%5D=K%C3%BCche&l%5B0%5D%5Byaxe%5D=left&l%5B0%5D%5Bxaxe%5D=top&l%5B0%5D%5Bfill%5D=0&l%5B0%5D%5Bpoints%5D=false&l%5B0%5D%5BcommonYAxis%5D=1&l%5B0%5D%5BafterComma%5D=2&l%5B0%5D%5Bdashes%5D=false&l%5B0%5D%5BdashLength%5D=10&l%5B0%5D%5BspaceLength%5D=10&l%5B0%5D%5BchartType%5D=line&l%5B1%5D%5Bid%5D=zigbee.0.00158d0002b6fac7.temperature&l%5B1%5D%5Binstance%5D=history.0&l%5B1%5D%5Boffset%5D=0&l%5B1%5D%5Baggregate%5D=minmax&l%5B1%5D%5Bcolor%5D=%2300FF00&l%5B1%5D%5Bmin%5D=18&l%5B1%5D%5Bmax%5D=30&l%5B1%5D%5Bthickness%5D=3&l%5B1%5D%5Bshadowsize%5D=3&l%5B1%5D%5Bunit%5D=%C2%B0C&l%5B1%5D%5Bname%5D=Schlafzimmer&l%5B1%5D%5Byaxe%5D=off&l%5B1%5D%5Bfill%5D=0&l%5B1%5D%5Bxaxe%5D=off&l%5B1%5D%5BcommonYAxis%5D=1&l%5B1%5D%5BafterComma%5D=2&l%5B1%5D%5Bdashes%5D=false&l%5B1%5D%5BdashLength%5D=10&l%5B1%5D%5BspaceLength%5D=10&l%5B2%5D%5Bid%5D=zigbee.0.00158d00025ea1d6.temperature&l%5B2%5D%5Binstance%5D=history.0&l%5B2%5D%5Boffset%5D=0&l%5B2%5D%5Baggregate%5D=minmax&l%5B2%5D%5Bcolor%5D=%230000FF&l%5B2%5D%5Bmin%5D=18&l%5B2%5D%5Bmax%5D=30&l%5B2%5D%5Bthickness%5D=3&l%5B2%5D%5Bshadowsize%5D=3&l%5B2%5D%5Bunit%5D=%C2%B0C&l%5B2%5D%5Bname%5D=Wohnzimmer&l%5B2%5D%5Bfill%5D=0&l%5B2%5D%5Byaxe%5D=off&l%5B2%5D%5Bxaxe%5D=off&l%5B2%5D%5BcommonYAxis%5D=1&l%5B2%5D%5BafterComma%5D=2&l%5B2%5D%5Bdashes%5D=false&l%5B2%5D%5BdashLength%5D=10&l%5B2%5D%5BspaceLength%5D=10&l%5B3%5D%5Bid%5D=zigbee.0.00158d00025e9517.temperature&l%5B3%5D%5Binstance%5D=history.0&l%5B3%5D%5Boffset%5D=0&l%5B3%5D%5Baggregate%5D=minmax&l%5B3%5D%5Bcolor%5D=%23FFFF00&l%5B3%5D%5Bmin%5D=18&l%5B3%5D%5Bmax%5D=30&l%5B3%5D%5Bthickness%5D=3&l%5B3%5D%5Bshadowsize%5D=3&l%5B3%5D%5Bunit%5D=%C2%B0C&l%5B3%5D%5Bname%5D=Bad&l%5B3%5D%5Byaxe%5D=off&l%5B3%5D%5Bfill%5D=0&l%5B3%5D%5Bxaxe%5D=off&timeType=relative&relativeEnd=now&range=1440&live=600&aggregateType=count&aggregateSpan=1000&legend=ne&hoverDetail=true&useComma=false&zoom=false&noedit=false&animation=0&title=Temperaturen+(Aqara+Zigbee)&titlePos=bottom%3A5%3Bleft%3A50 with MIME type text/html. See https://www.chromestatus.com/feature/5629709824032768 for more details.`

**Comment by Zefau** [comment]
Hab gerade nochmal geschaut, geht leider nicht. Die Flot-Seite liefert leider keine Grafik oder etwas, was ich mit jarvis verarbeiten könnte. Daher geht leider tatsächlich nur iFrame.
