### ISSUE TITLE
v3 Behaviour with many tabs

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#844]
_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/803#issuecomment-881666076_
> `v3.0.0-alpha.28 und vorher` Wenn man auf dem Tablet ein TAB unter den MORE auswählt wird es angezeigt, aber nicht in der TAB-Auswahl. Unter v2.2.x konnte man die TABs verschieben, das war eigentlich aus meiner Sicht besser, sowohl auf dem Handy als auch auf dem Tablet.

Dieser Feature Request führt eine Option ein: `Tab-Leiste zusammenfassen` (ja = Dropdown, nein = volle Tab-Leiste)

**Comment by mcuiobroker** [comment]
Volle Tab-Leiste bedeutet dann, das man die TABs wieder verschieben kann, falls sie nicht alle in eine Reihe zur Anzeige gebracht werden können? Dann sollte es auch so wie in v2.2.x sein, das die ICONs oberhalb vom TAB-Text sein können und nicht nur daneben, wie bei v3.
v2.2.x
![image](https://user-images.githubusercontent.com/84818934/126002236-2ae39378-60dc-4ab0-8d7f-c9077047a80e.png)
v3
![image](https://user-images.githubusercontent.com/84818934/126002279-088bca58-10af-47ad-9dcf-327ac1eca6b9.png)
Denn auf dem Handy kann man in v3 kaum auf die TABs klicken.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/638

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.62` gibt es nun eine `dense` Option in den Einstellungen. Aktiviert = eine Zeile; deaktiviert = zwei Zeilen

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.77` 
Ist soweit alles bearbeitet. Kann geschlossen werden.
