### ISSUE TITLE
Inverse BlindLevelAction to control shutter level

### ISSUE THREAD

**Issue by ninja-warrior** [Zefau/ioBroker.jarvis#845]
Hey guys,

I just added some new Homematic IP shutters (HMIP-BROLL) to my jarvis instance. When I use the import functionalilty jarvis automatically added the required data points to my configuration. To control the shutter level jarvis is using LevelBody and InputAction. But for several reason I find it better to use BlindLevelAction instead of InputAction.

Now, I got the following challenge: The definition of the data point says that value "0" is linked to "Shutter completely opened" and "1" is linked to "Shutter completely closed". The BlindLevelAction is currently working the other way around, as far as I see.

So right now, I need to press the UP-Button on BlindLevelAction to close the shutter completely and need to press the DOWN-Button on BlindLevelAction to open the shutter completely. As far as I know, I can not manipulate that behaviour so far. 

Did I miss something or could we add this functionality as a feature request?

Best regards,
David

Btw: I am currently using Jarvis Version 2.2.2

Some screenshots: 
![image](https://user-images.githubusercontent.com/73721169/126029405-28899f75-969e-4e3f-8f80-2c6c1d473531.png)

![image](https://user-images.githubusercontent.com/73721169/126029457-d69fcc66-d240-4c47-a7ab-c787565247f0.png)

**Comment by Zefau** [comment]
Should be possible with `min` / `max` in the device properties, See https://zefau.gitbook.io/jarvis-de/geraete/devices#datenpunkt-eigenschaften

**Comment by ninja-warrior** [comment]
Thanks for your reply!

{"min":"100","max":"0"} works for me ... even it looks a little bit confusing - But nevertheless it works..
