### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by RdTrxx** [Zefau/ioBroker.jarvis#846]
**Prerequisites / Voraussetzungen**
- Welche Version von jarvis nutzt du? 
2.2.2
- Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]
![image](https://user-images.githubusercontent.com/81949574/126038240-8dcc0795-55c6-407e-90a6-2748e659e740.png)

**Beschreibe den Fehler**
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
Erstes Starten von jarvis. Durchlaufen der Anleitung. Automatisches Erstellen der Visualisierung durch Jarvis angewählt. Danach wurde die Visu generiert. Gehen zu "Einstellungen". Durchlaufen der Einleitung. Absturz nach/wöhrend der Einleitung. Genauer Zeitpunkt nicht mehr bekannt. 
Danach Restart Adapter Jarvis, und alles funktioniert.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![Bild_2021-07-17_150941](https://user-images.githubusercontent.com/81949574/126037990-7ced666d-a1ea-401d-9ad6-95d539dad9c4.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Please move to v3
