### ISSUE TITLE
jarvis hinter reverse proxy

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#847]
_Originally posted by @daolis in https://github.com/Zefau/ioBroker.jarvis/issues/772#issuecomment-878450078_
> Habe das selbe Problem.
> * Jarvis ist bei mir hinter einem reverse proxy mit https.
> * der client versucht eine Verbindung mit dem Server auf port 8400 herzustellen. Allerdings mit https;//, was auf auf diesem port nicht funktioniert. `GET https://vis.local:8400/jarvis-socket/?EIO=4&transport=polling&t=NgRgit9 net::ERR_SSL_PROTOCOL_ERROR`

> Ich habe auch versucht jarvis direkt mit dem iobroker port aufzurufen... (http://mcp.local:8082/jarvis/index.html#/instance=0)
Dann wird wird vom die url http://mcp.local:8082/jarvis-socket/?EIO=4&transport=polling..... aufgerufen... Warum hier nicht 8400? War meine Hoffnung dass der call auf port 8082 die NICHT https URL von 8400 verwendent....

**Comment by daolis** [comment]
> @daolis kannst du mal deine Web Adapterkonfiguration posten? Hast du die Port-Konfiguration in jarvis geändert?
> jarvis läuft zwar über den Web Adapter und auf dem Port; socket-io ist aber nativ in jarvis drin (ohne socket-io Adapter) und läuft auf 8400 (sofern nicht in den Adapter-Einstellungen geändert).

Nichts geändert. Ist auf `Auto detect`.

**Comment by Zefau** [comment]
Wenn die aufgerufene URL `https` hat, dann connected Jarvis via `https`. Der Port ist immer `8400` für den Jarvis socket.

Was brauchst du damit es funktioniert?

**Comment by daolis** [comment]
https funktionert hier nicht weil jarvis auf 8400 nichts mit https anfangen kann.
Und nur die jarvis calls mit http auf 8400 während der rest auf https läuft funktioniert auch nicht.

Ich könnte mal versuchen den RP auch für port 8400 (incl. ssl termination) zu konfigirieren. Dazu wäre aber eine Einstellung nur für da bind port in jarvis notwendig. An den client müsste weiterhin 8400 geschickt werden, obwohl das port z.B. auf 8401 geöffnet wird.

---> 8400 [ RP ] ---> 8401 [ jarvis ]

**Comment by daolis** [comment]
Warum machst du genau einen eigenen socket server auf?! WebSocket auf einem eigenen Endpoint würde hier vermutlich wengier Probleme machen...
Nginx würde dann die SSL termininierung machen und es direkt weiterleiten...

**Comment by Zefau** [comment]
> https funktionert hier nicht weil jarvis auf 8400 nichts mit https anfangen kann.

Das stimmt nicht. Ich selbst nutze jarvis via https. Der Port 8400 konfiguriert https abhängig von den Einstellungen im Web Adapter (und zieht sich dort die Zertifikate). 

Daher auch meine Frage (https://github.com/Zefau/ioBroker.jarvis/issues/772#issuecomment-881952143) wie dein Web Adapter konfiguriert ist. Hast du dort SSL aktiviert und die Zertifikate ausgewählt?

> WebSocket auf einem eigenen Endpoint würde hier vermutlich wengier Probleme machen...

Wie meinst du das? So ist es doch? Socket-io (nicht WebSocket) ist auf einem eigenen Endpoint / Port, nämlich 8400 (bzw. 8401 für Instanz 1, 8402 für Instanz 2, etc.). Der Web Zugriff läuft über den Web-Adapter via dort eingestelltem Port (default 8082 oder so).

**Comment by daolis** [comment]
oh, das erklärt es
Habe kein Cert im iobroker eingestellt. Auf IOBroker Seite läuft alles mit http. 
Terminierung erfolgt am NGINX. Somit nichts mit https auf 8400.

Ich meinte z.B. Websocket auf https:/URL:8082/jarvis/ws (Aber keine Ahnung wie es in iobroker geht)

Aber Danke, ich werde es mal mit https direkt am iobroker versuchen...

**Comment by ChrizZz90** [comment]
wie habt ihr denn die NGINX Weiterleitung aufgesetzt bekommen? Ich verzweifle daran gerade und bin auch mit den Portweiterleitung etwas verwirrt. Um über DDNS auf Jarvis (wenn möglich nur Jarvis) zugreifen zu können, habe ich meinen Reverse Proxy auf die 8082 eingestellt. Dazu im Webadapter das Zertifikat hinterlegt, HTTPS und Auth aktiviert. Doch die Weiterleitung führt ins leere: 502 - Bad Gateway.

Zusätzlich wirds vielleicht noch kompliziert, denn mein Ziel war Jarvis über subdomain.ddns.tld/jarvis aufrufen zu können. Alle weiteren Ports/Services sollten "unerreichbar" sein, sofern denn möglich.

Das sollte eigentlich schon funktionieren oder ist deshalb noch dieses Issue offen?

**Comment by Zefau** [comment]
Ich hab den Use Case bei mir nicht im Einsatz und kann daher dazu wenig Hilfestellung geben. Ist es kompliziert einen Reverse Proxy aufzusetzen? 

Wichtig ist zu wissen, dass sich Web zwar auf 8082 verbindet, aber der Socket auf 8400.

**Comment by ChrizZz90** [comment]
Ist nicht kompliziert, per NGINX einen Reverse Proxy einzurichten...aber vielleicht die Einrichtung für mehrere Services, denn daran scheitere ich aktuell noch.

An der Anleitung habe ich mich orientiert: https://pimylifeup.com/raspberry-pi-bitwarden/#nginxproxy

**Comment by daolis** [comment]
Sorry, leider erst jetzt dazugekommen.
Habe ein paar scenarien versucht.

host blaa am DNS eingestelt (oder hosts eintrag)
`10.0.0.1 blaa`

| | Vis | Socket |  Status |
|--|--|--|--|
 iobroker web ohne ssl|
|1. | http://10.0.0.1:8082 |  http://10.0.0.1:8400/jarvis-socket/ | funktioniert
|2. | http://blaa:8082 |  http://blaa:8400/jarvis-socket/ |  Access to XMLHttpRequest at 'http://blaa:8400/jarvis-socket/?EIO=4&transport=polling&t=NiSJ71l' from origin 'http://blaa:8082' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
 iobroker web mit ssl|
|3. | https://10.0.0.1 |  http://10.0.0.1:8400/jarvis-socket/ | funktioniert
|4. | https://blaa |  https://blaa:8400 |  Access to XMLHttpRequest at 'https://blaa:8400/jarvis-socket/?EIO=4&transport=polling&t=NiS4SG8' from origin 'https://blaa:8082' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.
 iobroker ohne ssl, ssl terminierung am nginx |
|5.| https://blaa | https://blaa:8400 | Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR
ReverseProxy ohne ssl terminierung, iobroker mit ssl
|7.| https://10.0.0.1 | https://10.0.0.1:8400 | funktioniert (nginx server_name 10.0.0.1)
|8.| https://blaa | https://blaa:8400 | Access to XMLHttpRequest at 'http://blaa:8400/jarvis-socket/?EIO=4&transport=polling&t=NiSJ71l' from origin 'http://blaa:8082' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.


5 is klar, http != http

## 1, 3 & 7 vs. 2, 4 & 8

Bei den Requests die die IP verwenden (3 & 7) wird vom server (jarvis-socket) der http header
`Access-Control-Allow-Origin: https://10.0.0.1` gesetzt. \
**Bei denen mit blaa nicht!!!**

@Zefau könntest du bitte den header auch bei den Requests mit URL setzen?

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.50` nun funktionieren.

**Comment by ChrizZz90** [comment]
@daolis kannst du deine NGINX Einstellungen teilen? Ich versuche Jarvis über einen DynDNS Service aufzurufen, NGINX soll die Anfrage weiterleiten, aber näher dran als mit dieser Einstellung komme ich nicht. Hier läd allerdings der Inhalt der Seite nicht (aber der Webseitentitel und ich sehe, dass alle Elemente auf 404 laufen. Vermutlich, weil ich den Socket 8400 nicht freigegeben habe?

```
server {
  listen 443 ssl http2;
  server_name host1.dyndns
    ssl_certificate /etc/letsencrypt/...; 
    ssl_certificate_key /etc/letsencrypt/...; 

  ssl_dhparam /etc/ssl/...;

  # Allow large attachments
  client_max_body_size 128M;

  location / {
    proxy_pass http://0.0.0.0:8082/jarvis/index.html;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload";
    add_header Referrer-Policy "same-origin";
  }
}
```

**Comment by daolis** [comment]
@zefau leider nein... siehe Screenshots...
![Jarvis1](https://user-images.githubusercontent.com/2550938/128591489-626e459d-064f-4ab9-9f79-35aa42ed744e.png)
![Jarvis2](https://user-images.githubusercontent.com/2550938/128591492-b3c4cec6-4c3f-47ae-968d-416670b7ec49.png)

**Comment by daolis** [comment]
@ChrizZz90 Lieg ich da richtig, dass du den iobroker über das internet erreichen willst. Dann musst du mehrere ports forwarden... (2082 & 8400)
Wenn es so ist, dann würde ich mal abraten! Mach es eher per VPN!

ad. NGINX Deinen Server hast du mit ssl term konfiguriert. (listen 443 **ssl**), das geht leider nicht. Siehe meine Tabelle Punkt 5.
Die IP bei deinem proxy_pass ist nicht rout-bar das ist nur der platzhalter beim listen, und bedeutet dass das port auf allen lokalen IPs geöffnet wird (127.0.0.1, und von meinem beispiel 10.1.2.6)
Die proxy_set_header werden bei simpler weiterleiotung auch nicht verwendet.

1. server section: Redirect HTTP -> HTTPS (moved permanently)
2. server Workaround: Redirect DNS -> IP
3. HTTPS: ohne terminierung (kein Certifikat). Leitet alle requests auf https://vis.local auf https://localhost:8082 weiter

```nginx
server {
  listen 0.0.0.0:80;
  server_name vis.local;
  server_tokens off;
  location / {
    return 301 https://$http_host$request_uri;
  }
}

## Workaroud to redirect vis.local to IP
#server {
#  listen 0.0.0.0:443;
#  server_name vis.local;
#  location / {
#    return 302 https://10.1.2.6$request_uri;
#  }
#}

## HTTPS host
server {
  listen 0.0.0.0:443;
  # enable this when unsing the redirect....
  #server_name 10.1.2.6; 
  server_name vis.local;
  server_tokens off;

  access_log  /var/log/nginx/vis_access.log;
  error_log   /var/log/nginx/vis_error.log;

  # redirect request without path (only https://vis.local to https://vis.local/jarvis/index.html)
  location ~ ^/$ {
    return 301 https://vis.local/jarvis/index.html;
  }

  location / {
    client_max_body_size 0;
    gzip on;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_pass https://127.0.0.1:8082;
  }
}
```

**Comment by daolis** [comment]
@Zefau Wäre es mötglcih die adapter config etwas um ein bind zu erweitern.
z.B. bind auf 8401, URL im frontend wird aber 8400 verwendet.
Dann könnte der NGINX (mit ssl terminirung) dazwischen geschaltet werden. Das ist natürlich nur notwendig wenn sie auf dem gleichen host laufen.
Es geht zwar dass die SSL Zertifikate am iobroker konfiguriert werden, aber ich würde das gern trennen.

**Comment by Zefau** [comment]
Bitte poste das debug Log von iobroker beim connected.

**Comment by daolis** [comment]
jarvis.0	2021-08-08 09:03:08.982	debug	(14812) Connection: Origin detected with https://blaa:8082 (rejected)

**Comment by Zefau** [comment]
Und beim Start von Jarvis, was steht da, welcher Host ermittelt wurde?

**Comment by ChrizZz90** [comment]
@daolis danke für die Config. Ja, der Plan war über das Internet auf bestimmte Ports zuzugreifen und mit Authentifizierung sowie Fail2Ban abzusichern. Mein Verständnis ist, dass ich über den NGINX Reverse Proxy nur die relevanten Ports "öffne", bzw. von außen zugänglich mache. Habe ich da etwas missachtet, weshalb das sicherheitskritisch ist?

Um den weiteren Port hinzuzufügen muss ich wahrscheinlich "nur" eine weitere Location Sektion erstellen?

```
location /login {
    client_max_body_size 0;
    gzip on;

    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";

    proxy_pass https://127.0.0.1:8400;
  }
```

**Comment by daolis** [comment]
Ports nach aussen aufzumachen ist immer ein Risiko. Versuch mal port 22 (SSH) aufzumachen und schau was dann da los ist...
Du bracuhst nicht unbedingt NGINX. Eigentlich passiert das auf dem router/firewall unter port forwarding.
Ein VPN (z.b. openvpn) ist auf fälle um einiges sicherer und kann z.B auch von einem Smartphone aufgemacht werden.

Location alleine hilft hier nicht, da es auf einem anderen Port läuft. Da müsstest du eine weitere server config hinzufügen. Siehe https://socket.io/docs/v3/reverse-proxy/

Als FW mit so ziemlich jedem Feature das man brauchen könnte wäre z.B. OPNSense (https://opnsense.org/) und den router vom internetanbieter im modem modus.. = FW bekommt die public IP, und da läufter der opennpn server. Somit ist nur das openvpn port offen, du kommst nur mit gültigem Zertifikat, username & passwort rein, und ist natürlich verschlüsselt

**Comment by Zefau** [comment]
@daolis @ChrizZz90 muss ich hier jarvis-seitig noch etwas tun / implementieren?

**Comment by ChrizZz90** [comment]
von mir aus nicht, ich habs dann doch auf VPN umgestellt.

**Comment by Zefau** [comment]
Ok.

Also für Reverse-Proxy braucht jarvis 8400 für den Socket (Instanz 0) bzw. 8401 für Instanz 1 (und so weiter.. 840n).
Außerdem den Web-Port 8082 (je nach Konfiguration).

**Comment by daolis** [comment]
Hi,
komme dereit lerder nicht viel zum probieren. 
Ich hab nur kurz eine der letzten versionen (v3.0.0-alpha.70) ausprobiert und hatte noch immer CORS probleme.
Derzeit geht es mit der HTTP & IP. IOBroker auf Secure ging dann auch nicht mehr. SSL Probleme auf Prot 8400.

a.d.: Und beim Start von Jarvis, was steht da, welcher Host ermittelt wurde?
- Hoffentlich keiner. IOBroker weiss nichts von der URL. Das macht der Reverse Proxy. Ich hab die URL die am NGINX verwendet wird mal bei 'Socke Host/IP' in den Jarvis settings eingetragen, hat aber auch nicht funktionert.

Ich werde es demnächst noch genauer anschauen und schicke dann ein update.

**Comment by Zefau** [comment]
@ChrizZz90 @daolis wie habt ihr den Reverse Proxy gesichert, dass nicht jeder auf jarvis rauf kommt?

**Comment by ChrizZz90** [comment]
Ich hab das Thema Reverse Proxy nicht mehr weiter verfolgt und nutze nun den VPN Tunnel

**Comment by Zefau** [comment]
funktioniert nun mit v3.1, siehe https://github.com/Zefau/ioBroker.jarvis/issues/1602
