### ISSUE TITLE
v3: Pro-User Effekte

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#848]
`v3.0.0-alpha-31`
Fehler-Anzeige im Chrome
![image](https://user-images.githubusercontent.com/84818934/126083066-3861e21e-94d4-4ed2-adce-b62a961a3726.png)

**Comment by Zefau** [comment]
Das kommt nicht von Jarvis sondern einem deiner iFrames

**Comment by Zefau** [comment]
Oder einem Chrome Addon
