### ISSUE TITLE
v3: StateList Probleme

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#850]
`v3.0.0-alpha.31` aber sehr wahrscheinlich auch schon vorher
Statelist-Werte werden nicht korrekt angezeigt:

![image](https://user-images.githubusercontent.com/84818934/126204267-998e92d8-de9e-4aac-a13e-56b852954757.png)
---
![image](https://user-images.githubusercontent.com/84818934/126204637-eff11726-730b-453a-8467-c4be76613f1a.png)
---
![image](https://user-images.githubusercontent.com/84818934/126204565-95e13d92-b5e2-458b-8db0-5847804a1fde.png)
---

Es findet kein Umbruch statt.
![image](https://user-images.githubusercontent.com/84818934/126204801-074fb767-8fec-4960-a32c-2397250bf34a.png)
Der Wert wird bis in andere Module geschrieben.

Im Popup wird plötzlich zu dem DP auch ein LevelBody gezeigt, obwohl der nicht drin steht.
![image](https://user-images.githubusercontent.com/84818934/126205043-fc99c710-a32d-4af6-8db8-39499cb96c29.png)

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.32`
LevelBody nach der Knvertierung im Popup
![image](https://user-images.githubusercontent.com/84818934/126223046-41efcd7a-f47e-41d6-b0d5-bcf3c7d6d14d.png)
![image](https://user-images.githubusercontent.com/84818934/126223152-aa7ecc16-6707-46a3-b847-d7586067310a.png)
Nach Übernehmen genau dasselbe Ergebnis.
Wenn man dann die Schrittweite auf 10 ändert, anschließend Speichert, stimmt die Anzeige. Geht man dannzurück ist die Schrittweite wieder auf 1?
![jarvis_v300-alpha-32-levelbody-problem](https://user-images.githubusercontent.com/84818934/126223764-3ac9f435-a22a-40ad-a457-8aafcc5cef70.gif)

**Comment by Zefau** [comment]
Gibt es Fehler im Log? Das zweite Thema bekomme ich bei mir leider nicht nachgestellt.

Kannst du bzgl. des ersten Themas mal im JSON schauen, ob da `LevelBody` drin steht?

**Comment by mcuiobroker** [comment]
Also im JSON steht Levelbody:
`"1c2203c4-b873-42e4-a489-02a7579ac34e": {
    "id": "1c2203c4-b873-42e4-a489-02a7579ac34e",
    "function": "light",
    "states": {
      "bri": {
        "state": "hue-extended.0.lights.008-schreibtisch_unten.action.level",
        "action": "hue-extended.0.lights.008-schreibtisch_unten.action.level",
        "unit": "%",
        "actionElement": null,
        "bodyElement": "LevelBody",
        "properties": "",
        "label": ""
      },
      "onHUE": {
        "state": "hue-extended.0.lights.008-schreibtisch_unten.action.on",
        "action": "hue-extended.0.lights.008-schreibtisch_unten.action.on",
        "actionElement": "SwitchAction",
        "iconStyle": {
          "true": {
            "color": "yellow"
          }
        },
        "label": ""
      },
      "FehlerGrund": {
        "state": "javascript.0.HAUS.LICHT.TISCH.FEHLER_GRUND",
        "label": "",
        "action": ""
      },`

![image](https://user-images.githubusercontent.com/84818934/126229828-83fd118b-4804-4071-b067-2276a050ace8.png)

**Comment by Zefau** [comment]
Das ist aber nicht das Gerät aus dem ersten Post. Die ID ist anders.

**Comment by mcuiobroker** [comment]
Ja, aber ich hatte es ja schon geändert, deswegen musste ich jetzt eins ohne Änderung nehmen.

**Comment by Zefau** [comment]
Und da ist der Wert im Dropdown auch nicht gewählt? Ist ja seltsam

**Comment by Zefau** [comment]
Ne, nicht nochmal zurück. Daran sollte es nicht liegen. Ich schaue morgen mal.

**Comment by mcuiobroker** [comment]
Welchen Dropdown meinst du?

**Comment by Zefau** [comment]
In der Geräte Konfiguration für das Element

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/126231607-8350d4b3-ebc7-4bd7-8e00-914b936c27ca.png)
Genauso wie bei den anderen.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.33` oder vorher?
Plötzlich wird hue als hex-Wert angezeigt mit Einheit  °?
![image](https://user-images.githubusercontent.com/84818934/126233605-ec6afa98-10d3-4ef3-a833-af8b0ae3ff48.png)

**Comment by Zefau** [comment]
Schau dir die Fehler bitte nochmal mit `v3.0.0-alpha.46` an.

>  Statelist-Werte werden nicht korrekt angezeigt

Lange Texte sollten nun umgebrochen werden.

>  Wenn man dann die Schrittweite auf 10 ändert, anschließend Speichert, stimmt die Anzeige. Geht man dann zurück ist die Schrittweite wieder auf 1?

Schrittweite sollte nun korrekt gespeichert und auch korrekt wieder in der Konfiguration angezeigt werden.

>  Plötzlich wird hue als hex-Wert angezeigt mit Einheit °?

Bekomme ich bei mir so nicht nachgestellt. Hast du das Problem noch mit der aktuellen alpha? Welchen Wert hat `hue` in diesem Fall?

**Comment by mcuiobroker** [comment]
>Bekomme ich bei mir so nicht nachgestellt. Hast du das Problem noch mit der aktuellen alpha? 
Im objekt stand ein hex-Wert #598803, hab ihn geändert auf 200. Danach im Popup zum Gerät diesen Wert über LightHUEBody geändert und es steht wieder ein HEX-Wert drin mit ° als Einheit. Wenn ich den PC wieder hab, mach ich ein Video. Jetzt erstmal Video via App.

Schrittweite sieht gut aus.

Umbuch setzt zu spät ein. Wenn die Zeile mit Statelist-Beschreibung und Statelist-State-Wert und unter der Zeile die LastChangeBody steht, wird der Wert unter der Statelist Beschreibung angezeigt und erst umgebrochen, wenn der LastChangeBody betroffen ist oder in Nähe zum Statelist-StateWert. Foto via App

**Comment by Zefau** [comment]
> Im objekt stand ein hex-Wert #598803, hab ihn geändert auf 200. Danach im Popup zum Gerät diesen Wert über LightHUEBody geändert und es steht wieder ein HEX-Wert drin mit ° als Einheit. Wenn ich den PC wieder hab, mach ich ein Video. Jetzt erstmal Video via App.

ah ok, also jarvis schickt schon einen falschen Wert, wenn du mit jarvis schaltest?

**Comment by mcuiobroker** [comment]
![20210801_212614.jpg](https://user-images.githubusercontent.com/84818934/127783056-15f69c32-97c1-485f-ae32-239152abe8d8.jpg)

**Comment by mcuiobroker** [comment]
https://user-images.githubusercontent.com/84818934/127783143-a9bdc691-94ac-451e-8297-59a87dc7e8ee.mp4

**Comment by mcuiobroker** [comment]
v3.0.0-alpha.47 behebt das Problem mit dem Umbruch bei Statelist.
hue-Problem ist noch offen.

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.0-alpha.54`.

**Comment by mcuiobroker** [comment]
Nein, jetzt rgb(0,0,0) °-Wert egal bei welcher Auswahl:
![image](https://user-images.githubusercontent.com/84818934/130299961-31c6775f-ac0d-4dd7-a64e-ab867a557a49.png)
Momentan ist aber das Popup-Problem noch da. Werte werden im Popup nicht angezeigt. Nur Input-Werte:
![image](https://user-images.githubusercontent.com/84818934/130300022-f9b668ad-beef-4e5a-9fdd-14a7d6b10839.png)

**Comment by Zefau** [comment]
wenn du zurück bist, probier gerne nochmal mit `v3.0.0-alpha.55`.

**Comment by mcuiobroker** [comment]
Mit `3.0.0-alpha.60` wird es so angezeigt bzw geändert in dem DP:
![image](https://user-images.githubusercontent.com/84818934/131233233-3a46937b-b43f-4d98-bee3-30829045b56b.png)

**Comment by mcuiobroker** [comment]
Konvertierung Jalousie fehlerhaft? Soll er das dann so leer lassen?
Geräte-DP war in v2 leer, ohne Objekt-DPs:
![image](https://user-images.githubusercontent.com/84818934/132146214-51a97a34-00ba-4c4f-a4be-33e2ac4708d1.png)


v2
![image](https://user-images.githubusercontent.com/84818934/132146139-36059add-3b9d-4769-bf46-998e6f1bc034.png)
v3
![image](https://user-images.githubusercontent.com/84818934/132146153-259aef58-0494-4cb7-be8c-5e2985177fa1.png)

**Comment by Zefau** [comment]
Was hat er denn in v3 konvertiert? Gar nichts?

Leere DPs aus V2 werden in v3 raus gefiltert. Warum sind die denn leer? Dann geht es ja eh nicht und soll auch nicht angezeigt werden.
Verhalten erscheint mir korrekt.

**Comment by Zefau** [comment]
Was ist in diesem Issue jetzt noch offen?

>  Obwohl ich 25.5 als Schrittweite angebe macht er 25,5 draus:

Ist ja nicht schlimm? Und ja auch richtig, da `.` im Deutschen ein 1000er Trennzeichen ist und `,` ein Komma. So ist es ja auch gemeint?

**Comment by mcuiobroker** [comment]
Das Problem ist doch das er keine 10 Schritt korrekt angibt.
![image](https://user-images.githubusercontent.com/84818934/132215771-77951552-54a3-4512-9c45-9848bca29526.png)
Es sind 11. Der 10.te liegt auf 250. Und sollte auf 255 liegen.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/982

>  Es sind 11. Der 10.te liegt auf 250. Und sollte auf 255 liegen.

Es sind 10 +1. Der +1 ist der Nullpunkt. Wenn du 100 hast und 10 Schritte angibst, dann ist es immer eine 10er Weite (100 / 10 = 10). Würde ich es ändern, wäre das hier verwirrend.

Sollte nun aber mit `v3.0.0-alpha.75` passen. Ansonsten lass uns gerne unter https://github.com/Zefau/ioBroker.jarvis/issues/982 weiter diskutieren. Sonst ist von diesem Issue nichts mehr offen, oder?

**Comment by mcuiobroker** [comment]
Ich möchte eine Schrittweite von 5 , aber nur 10 insgesamt angezeigt bekommen:
![image](https://user-images.githubusercontent.com/84818934/133164980-b95d03b4-8871-4cb4-9e2d-aebaa62c6994.png)

Es werden 20 Punkte angezeigt
![image](https://user-images.githubusercontent.com/84818934/133164919-42368a01-6705-4e75-9d7c-f6824bf8146d.png)


Mit ",5" -Werten schau ich noch.
