### ISSUE TITLE
v3: Einstellungen Instanz

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#851]
Damit es nicht vergessen wird, es verwirrt sonst.
![image](https://user-images.githubusercontent.com/84818934/126232352-c28c3f04-3eb0-495c-9af3-1bdbba77e09a.png)

Konfigurationsdaten schicken raus nehmen ,da nicht mehr in Funktion.

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.34` auf Sentry geändert

**Comment by mcuiobroker** [comment]
Fehler-Anzeige bei der Einstellungsseite:
![image](https://user-images.githubusercontent.com/84818934/126397146-40297caf-4807-46e1-a10e-3e73db304afa.png)

**Comment by mcuiobroker** [comment]
`v.3.0.0-alpha.34`
Firefox keine Anzeige der Sicherungen mehr:
![image](https://user-images.githubusercontent.com/84818934/126397354-f2f3ed0e-4019-427e-bf67-92f22972a236.png)

**Comment by Zefau** [comment]
Ist derselbe Fehler? Oder was anderes?

**Comment by mcuiobroker** [comment]
Ja. Das ist noch übrig geblieben. Das andere hattest du ersetzt durch SENTRY.

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/790#issuecomment-913817768
