### ISSUE TITLE
V3: Option zur Anordnung der Menüleiste links, oder rechts

### ISSUE THREAD

**Issue by WW1983** [Zefau/ioBroker.jarvis#852]
Es wäre schön wenn man die Menüleiste links oder rechts (vertikal) anordnen könnte:

![image](https://user-images.githubusercontent.com/56581564/126269942-fe0c215e-09b8-4bcf-9273-5ea08a8c3e9e.png)

**Comment by Zefau** [comment]
Die Tab Leiste geht oben oder unten.

Du kannst den Drawer / Sidebar per Option als Menüleiste ebenfalls einblenden.

**Comment by WW1983** [comment]
> Die Tab Leiste geht oben oder unten.
> 
> Du kannst den Drawer / Sidebar per Option als Menüleiste ebenfalls einblenden.

Die Option habe ich gesehen. Vielleicht kann man es so variieren, dass man die Positionen von beidem flexibler gestalten kann.

**Comment by Zefau** [comment]
Es lassen sich ja 3 von 4 Seiten nutzen. Eine Seite ist den Notifications vorbehalten. Ich kann ggf. noch eine Option einbauen, die beiden zu tauschen (Drawer <-> Notifications). Das wäre mit vertretbarem Aufwand machbar. 

Optional Tabs oder den Drawer jeweils überall platzieren zu können hat keinen Mehrwert zur aktuellen Situation, bedeutet aber einiges an Aufwand dies umzusetzen.

**Comment by WW1983** [comment]
Mir ging es eher darum die normale Menüleiste auf die Linke Seit platzieren zu können. Der Drawer ist für mich aktuell uninteressant. Vielleicht kann man ja eine Option einfügen diesen auszublenden und die Menüleiste links platzieren zu können.

Wenn das zu viel Aufwand ist, dann kann das Issue geschlossen werden und ggf. irgendwann mal aufgegriffen werden.
