### ISSUE TITLE
V3: Icon custom Styles funktionieren nicht. 

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#853]
jarvis Version:  v3.0.0-alpha.0 -  v3.0.0-alpha.33

In den "Styles" Einstellungen  konfigurierte Styles funktionieren nicht, 
es wird kein Icon angezeigt.

Hier eine Beispiel aus den meinen Styles:

.anime { animation: turner 4s infinite linear !important  }
@keyframes turner {
                                     from{  transform: rotateY(0deg)  }
                                     to  {  transform: rotateY(360deg) }
                                  } 

und hier der Aufruf im Gerät: (Icon JSON Fromat):
{"true":"mdi-moped-electric anime","false":"mdi-moped-electric"}

Es funktioniert nur blink und alles was mit "spin" beginnt auch wenn nicht in den styles eingetragen.

Unter der V2 wird alles korrekt angezeigt.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.34` wieder passen

**Comment by bogaboo** [comment]
Prima, mit der v3.0.0-alpha.34 ist der Fehler behoben.
