### ISSUE TITLE
V3: Datenpunkt Stil wird nicht berücksichtigt bei "<span class... in der Anzeigevariante"

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#854]
jarvis Version:  v3.0.0-alpha.0 -  v3.0.0-alpha.33

Wenn ich im Gerät unter Anzeigevariante (JSON Format) ein "<span class..." 
eintrage wird der eingetragene Wert (Anzeigevariante (JSON Format)) nicht benutzt.

![Bildschirmfoto 2021-07-20 um 15 42 50](https://user-images.githubusercontent.com/48379591/126335446-c2970530-e761-4eec-b542-faafcb18caae.jpg)

In diesem Fall sollte bei "true" der Text in der Farbe "#03fcfc" blinken.

Das Blinken funktioniert allerdings wird die Farbe nicht übernommen,  der Text wird in der "Standard" Farbe,
in meinem Fall, weiß dargestellt.

Unter der V2 wird alles korrekt angezeigt.

**Comment by Zefau** [comment]
Du nutzt den Datenpunkt in `StateList` ?
Kannst du mir den Style mal zeigen?

Wie sieht der DOM / Quelltext bei dir aus (via Rechtsklick --> Inspect) ?
Bei mir funktioniert es soweit (nur in roter Farbe getestet; ohne blinken):

![image](https://user-images.githubusercontent.com/14368811/126373677-eb51d6cb-85aa-4fcb-8e52-021f9711f772.png)

**Comment by bogaboo** [comment]
> Du nutzt den Datenpunkt in StateList ?

Ja, der Datenpunkt wird in StateList benutzt.

> Kannst du mir den Style mal zeigen?

`.blinklangsam { animation: blinker 4s linear infinite; }
@keyframes blinker { 50% { opacity: 0; }}`

> Bei mir funktioniert es soweit (nur in roter Farbe getestet; ohne blinken):

Also einzeln geht es:

1. Farbe setzten - ohne blinken --> geht
2. Blinken - ohne Farbe setzten --> geht

Nur die Kombination klappt nicht, also blinken in der angegebenen Farbe.

In diesem Fall sollte der Text blinken in der Farbe: #03fcfc,
dieser blinkt auch aber die Farbe wird nicht benutzt, 
stattdessen wird der Text in weiß dargestellt, ist wohl die Standad Farbe im Darkmode. 

![Bildschirmfoto 2021-07-21 um 15 09 52](https://user-images.githubusercontent.com/48379591/126510494-599ec3de-56f4-4089-8e36-35a1a1cded30.jpg)

**Comment by Zefau** [comment]
Aber der Style `blinklangsam` hat keine Farbe?

**Comment by Zefau** [comment]
ah sorry, jetzt hab ich's verstanden

**Comment by Zefau** [comment]
probier bitte nochmal mit `v3.0.0-alpha.35`.

**Comment by bogaboo** [comment]
Ja, jetzt klappe es !

Vielen Dank für die tolle Arbeit....
