### ISSUE TITLE
Error: Minified React error #31

### ISSUE THREAD

**Issue by Elvermann** [Zefau/ioBroker.jarvis#855]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [ ] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**

Linux iobroker 4.19.0-8-amd64 #1 SMP Debian 4.19.98-1+deb10u1 (2020-04-27) x86_64 
iobroker 4.2.2
 **Jarvis 2.2.1**
socket.io 3.1.4
web 3.4.1                                                                    
Node.js v12.22.3
NPM 6.14.13

- [ ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

> jarvis ist wegen eines Fehlers abgestürzt
> Bitte screenshote diese Seite und melde es dem Entwickler (via Github oder ioBroker Forum)
> 
> Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
> Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
>     at _i (http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1780522)
>     at http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1785410
>     at To (http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1794892)
>     at vs (http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1835420)
>     at lu (http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1825929)
>     at su (http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1825854)
>     at Qs (http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1822863)
>     at http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1774248
>     at t.unstable_runWithPriority (http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1849830)
>     at Ha (http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js:2:1773957)

**Browser Console ( Chrome 61.0.4472.164 64bit)**

> App # Welcome to jarvis 2.2.0
> main.93ac68a8.chunk.js:1 App # You are on instance jarvis.0.
> main.93ac68a8.chunk.js:1 Connecting to http://iobroker.fritz.box:8082 ..
> main.93ac68a8.chunk.js:1 Connected to http://iobroker.fritz.box:8082.
> main.93ac68a8.chunk.js:1 App # Processed 0 devices and discarded 0 devices due to incorrect configuration. See browser console log for more details:  Object
> 11.bc83b712.chunk.js:2 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
>     at _i (11.bc83b712.chunk.js:2)
>     at 11.bc83b712.chunk.js:2
>     at To (11.bc83b712.chunk.js:2)
>     at vs (11.bc83b712.chunk.js:2)
>     at lu (11.bc83b712.chunk.js:2)
>     at su (11.bc83b712.chunk.js:2)
>     at Qs (11.bc83b712.chunk.js:2)
>     at 11.bc83b712.chunk.js:2
>     at t.unstable_runWithPriority (11.bc83b712.chunk.js:2)
>     at Ha (11.bc83b712.chunk.js:2)
> es @ 11.bc83b712.chunk.js:2
> main.93ac68a8.chunk.js:1 Error: Minified React error #31; visit https://reactjs.org/docs/error-decoder.html?invariant=31&args[]=object%20with%20keys%20%7B%7D&args[]= for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
>     at _i (11.bc83b712.chunk.js:2)
>     at 11.bc83b712.chunk.js:2
>     at To (11.bc83b712.chunk.js:2)
>     at vs (11.bc83b712.chunk.js:2)
>     at lu (11.bc83b712.chunk.js:2)
>     at su (11.bc83b712.chunk.js:2)
>     at Qs (11.bc83b712.chunk.js:2)
>     at 11.bc83b712.chunk.js:2
>     at t.unstable_runWithPriority (11.bc83b712.chunk.js:2)
>     at Ha (11.bc83b712.chunk.js:2) Object
> value @ main.93ac68a8.chunk.js:1
> main.f3e4a4d9.chunk.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> 2.830695a1.chunk.css:1 Failed to load resource: the server responded with a status of 404 (Not Found)
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/11.bc83b712.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/main.93ac68a8.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/3.22c19388.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/8.a31625f7.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/5.07b7efb4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/6.75ea19a4.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/30.444580ea.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/0.516f712a.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/2.192604ee.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/1.336941be.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/32.5c36a3dd.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
> DevTools failed to load source map: Could not load content for http://iobroker.fritz.box:8082/jarvis/static/js/13.4fb44439.chunk.js.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE

**iobroker Log**
> jarvis.0 | 2021-07-20 19:21:28.291 | info | (2748) starting. Version 2.2.1 in /opt/iobroker/node_modules/iobroker.jarvis, node:v12.22.3, js-controller: 3.2.16

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.

Bei dem ersten Start des Adapters kommt man zur Auswahl ob manuell oder automatisch die Seiten angelegt werden sollen. 
Der Absturz folgt direkt nach anlegen der Seiten (erster Versuch war automatisch).
Jedoch auch anscheinend bei manuell.

Versuch um Fehler zu umgehen wie in #674 
Entfernen der Instanz jarvis.0 
Neustart von web.0 und socketio.0
Hinzufügen der Instanz 

Leider ohne Erfolg. 

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
bitte v2.2.2 (https://github.com/Zefau/ioBroker.jarvis/tarball/v2.2.x) probieren oder auf v3 (noch alpha) gehen

**Comment by Elvermann** [comment]
Mit v3.0.0 alpha sind die Fehler weg und es startet problemlos.

Danke für die schnelle Rückmeldung.
