### ISSUE TITLE
v3: Fehler im Layout - Widgets der rechten Seite abgeschnitten 

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#856]
Jarvis Version 3.0.0-alpha.36

Im Layout befinden sich 2 Widget nebeneinander, beide Widget teilen sich den Platz je 50%
alle Widget auf der rechten Seiten werden abgeschnitten.

![Bildschirmfoto 2021-07-22 um 14 55 57](https://user-images.githubusercontent.com/48379591/126643226-430449ba-e360-4478-adef-aca1d8fc1cc6.jpg)

verkleinere ich das Widget im Layout wird es korret angezeigt.

![Bildschirmfoto 2021-07-22 um 14 56 56](https://user-images.githubusercontent.com/48379591/126643335-1c50476e-d95b-4561-818c-27183b3ec03f.jpg)

**Comment by Zefau** [comment]
Off topic: Sind die Charts iFrame aus Grafana oder was ist das?

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.37`.

**Comment by bogaboo** [comment]
Prima, alles wieder gut.

Ja, richtig ist mit Grafana gemacht.
