### ISSUE TITLE
v3:  Datenpunkte mit Wert 0 werden im Widget (Layout) nicht angezeigt

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#857]
Jarvis Version 3.0.0-alpha.36

Wenn im Gerät ein konfigurierter Datenpunkt den Wert 0 enthält,
wird dieser im Laypout (Widget) nicht angezeigt.

Hier im Beispiel sollte "0 mm" angezeigt werden, der Wert fehlt aber komplett inkl. der Einheit.

![Bildschirmfoto 2021-07-22 um 15 34 51](https://user-images.githubusercontent.com/48379591/126648520-7e8d9416-737b-4c32-8f4a-990037fb852c.jpg)

Wenn ich den Datenpunkt ändere in diesem Fall eine "1", wird es richtig angezeigt.

![Bildschirmfoto 2021-07-22 um 15 34 17](https://user-images.githubusercontent.com/48379591/126648767-974adea7-ba9f-49d8-ae75-c41537bc29fb.jpg)

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.37`.

**Comment by bogaboo** [comment]
Top, klappt wieder !
