### ISSUE TITLE
Jarvis 2.2.1 stürzt nach Durchführung des Welcome-Wizards ab

### ISSUE THREAD

**Issue by Shamal2008** [Zefau/ioBroker.jarvis#858]
Hallo,

habe iobroker mit dem neuen Image auf Raspi4 1GB Ram installiert, jarvis hinzugefügt und beim ersten (und auch wiederholten Aufruf nach restart des Adapters) wird der Wizard ausgeführt und danach kommt ein "red-screen-of-death":

![rsod-jarvis](https://user-images.githubusercontent.com/33907376/126653040-2ce59e22-8fde-4b90-adc4-c1231a5c4ee9.JPG)

iobroker info:

iobroker-pi
Platform
linux
Betriebssystem
linux
Architektur
arm
CPUs
4
Geschwindigkeit
1500 MHz
Modell
ARMv7 Processor rev 3 (v7l)
RAM
903.92 MB
System Betriebszeit
01:45:44
Node.js
v12.22.2 (Es gibt eine neuere Version: v12.22.3)
NPM
6.14.13
Festplatte Größe
28.95 GB
Festplatte frei
26.44 GB
Anzahl der Adapter
348
Betriebszeit
01:45:37
Aktive Instanzen
21
Hostname
iobroker-pi

any idea?

Danke!

**Comment by Zefau** [comment]
Bitte auf v3 gehen
