### ISSUE TITLE
Erstellung von eigene Gewerken

### ISSUE THREAD

**Issue by derdoerk** [Zefau/ioBroker.jarvis#859]
Hallo, 

ich würde gerne eigene Gewerke anlegen wie z.B. "Bewässerung" um mir die VAriablen auf Schalter zu legen. oder gibt es hier auch andere Möglichkeiten?

Gruß
Dirk

**Comment by Zefau** [comment]
Was meinst du mit `Variablen auf Schalter legen` ?

**Comment by derdoerk** [comment]
Ich habe für das Ausführen von bestimmten Scripten Variablen (0_userdata.0. ...) die dann verschiedene Abläufe starten bzw. steuern. Diese würde ich gerne über Schalter in der Oberfläche sehen, oder geht das irgendwie anders?

**Comment by Zefau** [comment]
Einfach als Datenpunkt in einem Geräte anlegen und dann ins Layout aufnehmen

**Comment by derdoerk** [comment]
Genau das will ich ja machen, dafür würde ich ein Gerät anlegen und diesem den DatenPunkt zuweisen. Ich würde diese halt nur gerne sauber Clustern in verschieden Gewerken, der eine ist für Bewässerung, der nächste für Rollladensteuerung etc.

**Comment by Zefau** [comment]
Jo, ok. Also im Dropdown der Gewerke willst du eigene Gewerke hinzufügen können? Das geht aktuell nicht.

**Comment by Zefau** [comment]
siehe https://github.com/Zefau/ioBroker.jarvis/issues/188

**Comment by derdoerk** [comment]
OK wurde also schon als wunsch geäußert :-)

**Comment by Zefau** [comment]
Jo, kannst du gerne hoch-voten.
