### ISSUE TITLE
Jarvis via ioBroker App auf Android

### ISSUE THREAD

**Issue by derdoerk** [Zefau/ioBroker.jarvis#861]
Hallo, 

ich habe mir eine Jarvis view erstellt und diese auch mittels iobroker App auf meine IPhone zum laufen bekommen, wo ich auch den Cloud dienst nutze. 

Das zweite Handy in der Familie ist aber ein Android Handy, hier gibt es zwar auch die ioBroker App mit der Cloudanbindung, aber keine Möglichkeit die mit der Jarvis view zu verknüpfen. 

Gibt es hier die Möglichkeit dieses auch zu nutzen? oder kennt jemand die Einstellungen für Android?

**Comment by mcuiobroker** [comment]
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/iobroker-app

**Comment by Zefau** [comment]
done via https://github.com/Zefau/ioBroker.jarvis/issues/138 and https://github.com/Zefau/ioBroker.jarvis/issues/71
