### ISSUE TITLE
Schalten von Geräten nur bedingt möglich, wenn der selbe Datenpunkt für mehr als ein einziges Gerät verwendet wird.

### ISSUE THREAD

**Issue by danfuh** [Zefau/ioBroker.jarvis#864]
Ich verwende Version v3.0.0-alpha.39 (der Fehler ist mir auch in frühern v3.x aufgefallen, ich konnte ihn aber bis jetzt nicht eingrenzen oder rekonstruieren)

Wenn ein Datenpunkt bei mehr als einem Gerät verwendet wird, dann wird beim Schalten eines beliebigen anderen Gerätes der Schaltzustand nicht aktualisiert. Dies hat zur Folge, dass sich z.B. das Licht nur ein, aber nicht mehr ausschalten lässt. Wenn alle mehrfach verwendeten Datenpunkte wieder entfernt werden, funktioniert alles wie gewünscht. Der Fehler ist somit rekonstruierbar.

Beispiel:
Device 1
Datenpunkt für power: scene.0.00_DG_Office_Papa.Decke_Mitte_Alle_OnOff

Device 2
Datenpunkt für power: scene.0.00_DG_Office_Papa.Schreibtisch_OnOff

Device 3 (der selbe Datenpunkt wie bei Device 1)
Datenpunkt für power: scene.0.00_DG_Office_Papa.Decke_Mitte_Alle_OnOff

In einem StateList Widget befinden sich alle drei Devices, jeweils mit SwitchAcrion als Trigger Element.
Device 1 lässt sich wunderbar schalten
Device 2 und Device 3 lässt sich nur ein, bzw. aus schalten (falls es eingeschaltet war). Der Status wird nicht aktualisiert.

Selbst wenn Device 3 aus der StateList entfernt wird und nur noch Device 1 und Device 3 in der Liste stehen besteht dieser Fehler weiterhin. 
Erst die vollständige Löschung von Device 3 aus der Devices JSON löst das Problem (es reicht auch nicht das Device für die Löschung frei zu geben).

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.40` wieder passen.

**Comment by danfuh** [comment]
Ja, sieht gut aus (getestet mit .50). Danke!
