### ISSUE TITLE
v3: Connection delayed 

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#865]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [**3.0.0-alpha.39**] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [ **Im Browser kommt die Fehlermeldung: Connection delayed** ] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
**Jarvis installiert. Im Browser Jarvis geöffnet.**

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Welche URL rufst du genau auf? Hast du https aktiviert? Irgendwelche Besonderheiten wie Docker oder Reverse Proxy? Wie ist dein Web Adapter konfiguriert? Jarvis grün?

**Comment by AFPass** [comment]
Kurz vor dem Connection delayed kommt ein Time Out.
Ich rufe folgende URL auf https://iobroker:8082/jarvis/index.html#/0/.
ioBroker läuft als VM in einer Proxmox Umgebung. Docker oder Reverse Proxy habe ich nicht im Einsatz.
Jarvis ist grün.

Was meinst Du mit: Wie ist dein Web Adapter konfiguriert?

**Comment by Zefau** [comment]
Was steht in der Browser Konsole (F12) ?

**Comment by Zefau** [comment]
jarvis verbindet über den Web Adapter. Hast du dort die https Zertifikate ausgewählt?

**Comment by AFPass** [comment]
![grafik](https://user-images.githubusercontent.com/13101074/127387619-ba3518e2-d6c2-4a3e-adb8-b212797bfb4b.png)

**Comment by AFPass** [comment]
![grafik](https://user-images.githubusercontent.com/13101074/127387781-f3542c48-44ec-4cc3-b9f1-58e4bfa57b28.png)

**Comment by Zefau** [comment]
v2 geht?

**Comment by AFPass** [comment]
Ja. Die Stable lief. Bis zur Roten Fehlermeldung bei Wizard.

**Comment by Zefau** [comment]
Benutz mal bitte die IP

**Comment by AFPass** [comment]
![grafik](https://user-images.githubusercontent.com/13101074/127388909-41dfe402-8dbe-4cfe-89cd-5cc445a4a354.png)

Das gleiche.

**Comment by Zefau** [comment]
Was passiert, wenn du `https://192.168.178.9:8400/` direkt im Browser aufrufst?

**Comment by AFPass** [comment]
Da hab ich eine Ausgabe bekommen. Bin aber im Moment auf Version 2.xx

**Comment by Zefau** [comment]
Also insgesamt liegt es daran, dass keine Socket Verbindung aufgebaut werden kann. Der Port 8400 lehnt es wegen CORS ab, also wegen den Zertifikaten.

**Comment by Zefau** [comment]
bitte installiert `v3.0.0-alpha.47` und stellt den Adapter in ioBroker auf `debug`. Wenn ihr dann mit jarvis verbindet, was steht im ioBroker Log?

**Comment by o0shojo0o** [comment]
Klappt nun wunderbar :) 
<html>
<body>


jarvis.0 | 2021-08-04 09:03:18.097 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
-- | -- | -- | --
jarvis.0 | 2021-08-04 09:03:18.093 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-04 09:03:18.082 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-04 09:03:18.078 | info | Client with IP ::ffff:192.168.0.1 connected
jarvis.0 | 2021-08-04 09:03:18.077 | debug | Websocket-Handler for client initialized
jarvis.0 | 2021-08-04 09:03:18.076 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-04 09:03:18.072 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-04 09:03:17.490 | debug | Client with IP ::ffff:192.168.0.1 disconnected: transport close


</body>
</html>

**Comment by Zefau** [comment]
Super ;-)
@AFPass bei dir auch?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/847

**Comment by AFPass** [comment]
Kann ich erst nächste Woche sagen. 
Bin unterwegs. 

Grüße

**Comment by o0shojo0o** [comment]
Ah ich sehe schon er nimmt die IP von 2. Interface.
<html>
<body>


jarvis.0 | Zeit | debug | Nachricht
-- | -- | -- | --
jarvis.0 | 2021-08-12 18:11:40.855 | debug | Push update of instances..
jarvis.0 | 2021-08-12 18:11:40.721 | info | Found Backups for styles.
jarvis.0 | 2021-08-12 18:11:40.683 | info | Found Backups for devices.
jarvis.0 | 2021-08-12 18:11:40.647 | info | Found Backups for layout.
jarvis.0 | 2021-08-12 18:11:40.635 | info | Found Backups for settings.
jarvis.0 | 2021-08-12 18:11:40.634 | info | Found Backups for widgets.
jarvis.0 | 2021-08-12 18:11:40.630 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2021-08-12 18:11:40.621 | debug | Connection: Using non-secure HTTP-Server
jarvis.0 | 2021-08-12 18:11:40.621 | debug | Connection: ioBroker host detected with iobroker (IP: 172.18.0.20)
jarvis.0 | 2021-08-12 18:11:40.569 | info | starting. Version 3.0.0-alpha.50 in /opt/iobroker/node_modules/iobroker.jarvis, node: v12.22.2, js-controller: 3.3.15
jarvis.0 | 2021-08-12 18:11:36.297 | info | Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
jarvis.0 | 2021-08-12 18:11:36.297 | info | terminating
jarvis.0 | 2021-08-12 18:11:36.296 | info | Adapter stopped und unloaded.
jarvis.0 | 2021-08-12 18:11:36.295 | info | Got terminate signal TERMINATE_YOURSELF


</body>
</html>

**Comment by Zefau** [comment]
Interface 1 / 2 ist LAN und WLAN oder wie? Und du hast beides angeschlossen und er nimmt das falsche? Die IPs müssen stimmen, sonst lehnt er die Verbindung ab. Ich kann bei Gelegenheit nochmal eine Whitelist reinbauen.

**Comment by o0shojo0o** [comment]
Das ist eine Docker Container, mit MacVLAN: 192.168.0.203 und die Bridge: 172.18.0.20 .
Ja es das wäre ratsam ein Interface zu wählen oder wie Du schon sagtes eine Whitelist zu pflegen zu können. 

Gruß
Dennis

**Comment by o0shojo0o** [comment]
Noch zu Erläuterung, das Bridge Netzwerk wird genutzt um Dockerintern mit anderen Container zu kommunizieren, wie z.B. die RedisDB. 
Und das Bridge Netzwerk ist nicht von Außen erreichbar.

**Comment by AFPass** [comment]
Ich konnte heute testen und die Alpha ließ sich installieren und danach normal ausführen.

Andere Frage, die Grafik bei den Charts schaut jetzt anders aus. Bleibt das so oder kommt der Style von Version 2 wieder?

**Comment by Zefau** [comment]
@o0shojo0o mit `v3.0.0-alpha.51` gibt es nun die Möglichkeit in den ioBroker Adapter-Einstellungen eine Whitelist zu pflegen.

**Comment by o0shojo0o** [comment]
@Zefau will leider noch nicht funktionieren: 
<html>
<body>


jarvis.0 | Zeit | debug | Nachricht
-- | -- | -- | --
jarvis.0 | 2021-08-18 15:41:04.532 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-18 15:40:59.508 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-18 15:40:54.704 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-18 15:40:53.159 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-18 15:40:51.660 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)


</body>
</html>

**Comment by Zefau** [comment]
schau mal bitte mit der `v3.0.0-alpha.52`.

**Comment by o0shojo0o** [comment]
Scheint nun zu laufen, oder weil er nun zufällig die richtige IP hat? 
`Connection: ioBroker host detected with iobroker (IP: 192.168.0.203)`
<html>
<body>


jarvis.0 | Zeit | debug | Nachricht
-- | -- | -- | --
jarvis.0 | 2021-08-19 23:53:43.597 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-19 23:53:43.590 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-19 23:53:43.585 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-19 23:53:43.579 | info | Client with IP ::ffff:192.168.0.1 connected
jarvis.0 | 2021-08-19 23:53:43.576 | debug | Websocket-Handler for client initialized
jarvis.0 | 2021-08-19 23:53:43.570 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-19 23:53:43.547 | debug | Connection: Origin detected with http://192.168.0.203:8082 (allowed)
jarvis.0 | 2021-08-19 23:53:43.077 | info | Found Backups for styles.
jarvis.0 | 2021-08-19 23:53:43.040 | info | Found Backups for devices.
jarvis.0 | 2021-08-19 23:53:43.038 | debug | Push update of instances..
jarvis.0 | 2021-08-19 23:53:42.861 | info | Found Backups for layout.
jarvis.0 | 2021-08-19 23:53:42.856 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2021-08-19 23:53:42.847 | debug | Connection: Using non-secure HTTP-Server
jarvis.0 | 2021-08-19 23:53:42.847 | debug | Connection: ioBroker host detected with iobroker (IP: 192.168.0.203)
jarvis.0 | 2021-08-19 23:53:42.842 | info | Found Backups for settings.
jarvis.0 | 2021-08-19 23:53:42.842 | info | Found Backups for widgets.
jarvis.0 | 2021-08-19 23:53:42.790 | info | starting. Version 3.0.0-alpha.52 in /opt/iobroker/node_modules/iobroker.jarvis, node: v12.22.2, js-controller: 3.3.15


</body>
</html>

**Comment by Zefau** [comment]
Wieso zufällig? Er nimmt die iobroker IP und deine Whitelist.

**Comment by o0shojo0o** [comment]
Weil er sonst oft die IP von der Bridge (172.18.0.20) genommen hat anstatt die vom MACVlan (192.168.0.203), war aber nur ein Gedanke.

**Comment by Zefau** [comment]
Kann ich tatsächlich nicht beantworten wie das aufgelöst wird.

Ich würde das Ticket aber dann erstmal schließen, da e funktioniert. Sollte sich das ändern, öffne es gerne wieder.

**Comment by o0shojo0o** [comment]
Ich muss das Issues leider wieder aufmachen.
<html>
<body>


jarvis.0 | Zeit | debug | Nachricht
-- | -- | -- | --
jarvis.0 | 2021-08-23 12:00:55.833 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:55.782 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:55.729 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:55.678 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:50.589 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:50.533 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:50.480 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:45.390 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:42.503 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:40.931 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:40.269 | debug | Connection: Origin detected with http://192.168.0.203:8082 (rejected, not in 192.168.0.203, localhost, 127.0.0.1, 172.18.0.20, iobroker)
jarvis.0 | 2021-08-23 12:00:38.072 | debug | Push update of instances..
jarvis.0 | 2021-08-23 12:00:37.958 | info | Found Backups for styles.
jarvis.0 | 2021-08-23 12:00:37.924 | info | Found Backups for devices.
jarvis.0 | 2021-08-23 12:00:37.900 | info | Found Backups for layout.
jarvis.0 | 2021-08-23 12:00:37.890 | info | Found Backups for settings.
jarvis.0 | 2021-08-23 12:00:37.890 | info | Found Backups for widgets.
jarvis.0 | 2021-08-23 12:00:37.885 | info | Connection: WebSocket opened on port 8400 using http...
jarvis.0 | 2021-08-23 12:00:37.876 | debug | Connection: Using non-secure HTTP-Server
jarvis.0 | 2021-08-23 12:00:37.876 | debug | Connection: ioBroker host detected with iobroker (IP: 172.18.0.20)
jarvis.0 | 2021-08-23 12:00:37.827 | info | starting. Version 3.0.0-alpha.52 in /opt/iobroker/node_modules/iobroker.jarvis, node: v12.22.5, js-controller: 3.3.15


</body>
</html>

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.59` nun funktionieren.
