### ISSUE TITLE
native Android Notifications

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#873]

**Comment by Zefau** [comment]
via `"display": "app"` (or `"display": [ "app", "popup" ]` to use multiple modes).

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-beta.41` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-beta.41`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by Zefau** [comment]
@mcuiobroker du nutzt Android oder? Notification sind nun nativ auf Android. Kannst du das mit in die Doku aufnehmen?

**Comment by mcuiobroker** [comment]
Ja. Ist drin.
