### ISSUE TITLE
v3: Datenpunkt-Eigenschaft mit value: val-Umrechnung - normale Einheit wird nicht angezeigt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#874]
Hat man bei Datenpunkt-Eigenschaft eine Umrechnung eingetragen:
`{"value":"val => String(val).substr(0,4)+'<sup>'+String(val).substr(4,1)+'</sup>'"}`
wird die Einheit nicht angezeigt:
![image](https://user-images.githubusercontent.com/84818934/127975176-7dec45ef-f82d-4ced-a852-5004a02c3e0b.png)
![image](https://user-images.githubusercontent.com/84818934/127975303-126c0849-4d11-497b-a01c-8642c9e38149.png)
Man muss sie in der Umrechnung eintragen:
`{"value":"val => String(val).substr(0,4)+'<sup>'+String(val).substr(4,1)+'</sup>'+' €'"}`

**Comment by Zefau** [comment]
Das liegt nicht daran, dass du den `callback` (Umrechnung) verwendest, sondern wegen dem HTML. Daher ist das das gewollte Verhalten.

Anders betrachtet: Hast du noch andere Geräte in der `StateList` bei denen HTML drin ist? Da würde die Einheit ggf. stören? 

In der aktuellen Ausgestaltung kannst du es im `callback` angegeben oder nicht. Wenn ich es aber im Standard (bei HTML) hinzufüge, könnte der Benutzer es nicht wieder entfernen.

**Comment by mcuiobroker** [comment]
Wenn der User dann dort keine Einheit haben wollen würde, würde er dort keine Standard-Einheit angeben? Man kann das Feld ja leer lassen, wenn man nur das HTML-Element im Wert nutzen möchte.
