### ISSUE TITLE
v3: iFrame Skalierung fehlt

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#875]
![image](https://user-images.githubusercontent.com/84818934/127979547-b9255364-59ca-4933-a5af-16574570c4a8.png)

führt z.B. dazu, dass die Volle Breite nicht genutzt wird:
![image](https://user-images.githubusercontent.com/84818934/127979668-65007163-e0a8-480e-a87b-c4784e9b4b48.png)

Bei kleineren Größen sollte man auch wieder die Zentriermöglichkeit haben und Angabe von Höhe und Breite fehlt, wie in v2:
![image](https://user-images.githubusercontent.com/84818934/127982097-64d082e6-d947-4c06-97dd-810521227293.png)

**Comment by Zefau** [comment]
Sicher, dass es am iFrame und nicht dem Inhalt liegt? Kannst du mal im Inspektor kontrollieren wie breit das iFrame ist?

**Comment by mcuiobroker** [comment]
Liegt am Browser unter Firefox passt es prima:
![image](https://user-images.githubusercontent.com/84818934/128005834-eb73e71e-af37-4f7c-a9d0-7c068635f4bb.png)
Unter Edge nicht:
![image](https://user-images.githubusercontent.com/84818934/128005949-3cbb63e4-4076-474f-9308-0c9e67bd4510.png)

In Chrome folgenden Fehlermeldungen:
![image](https://user-images.githubusercontent.com/84818934/128006058-9d26d540-f5c2-408d-b079-183f31a82554.png)

![image](https://user-images.githubusercontent.com/84818934/128005412-e153fd88-1660-4518-8dbf-549a676e9fe8.png)

**Comment by mcuiobroker** [comment]
![image](https://user-images.githubusercontent.com/84818934/128007541-6ad85059-845b-46ed-949a-0229a8ff9ca4.png)
![image](https://user-images.githubusercontent.com/84818934/128007597-d2d914b1-60b9-4098-a07c-ec3e6f134a1a.png)

**Comment by Zefau** [comment]
Ist hier noch etwas offen? Mit https://github.com/Zefau/ioBroker.jarvis/issues/967 wurde ja ein Teil hiervon nochmal separat angelegt.

**Comment by Zefau** [comment]
Ich sehe gerade, es ging um die fehlerhafte Skalierung? Kannst du das bei mehreren iFrames beobachten oder nur bei dem TVGuide?

**Comment by mcuiobroker** [comment]
Die Skalierung passt aber jetzt. Das andere #967  ist ein browserspezifisches Problem bei Chrome (PC und Handy).
