### ISSUE TITLE
jarvis ist wegen eines Fehlers abgestürzt

### ISSUE THREAD

**Issue by mueckeflo** [Zefau/ioBroker.jarvis#878]
![image](https://user-images.githubusercontent.com/3601605/128090314-cd35dc34-c433-400e-aeb8-073256daf272.png)

**Comment by Zefau** [comment]
Bitte auf v3 gehen

**Comment by mueckeflo** [comment]
Wie? Ich bekomme nur ver2 angeboten:
![image](https://user-images.githubusercontent.com/3601605/128159485-021ec7f7-0a39-4254-98f6-95663d32471d.png)

**Comment by mueckeflo** [comment]
Lass uns den Bug hier zumachen, nachdem ich nicht mal weiß wie ich den Fall reproduzieren könnte...
Ich mach n neues Ticket auf sollte sich das Wiederholen und on demand reproduzieren lassen.
Hab jetzt für den Anfang den Adapter deinstalliert und die latest version (allerdings wohl v2) installiert.
