### ISSUE TITLE
v3: stateHTML Unterschiedliche Darstellungsformen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#879]
StateHTML sollte eigentlich immer gleich dargestellt werden (Grundsätzlich)

- [ ] Angepasst auf die Seite bzw das Widget mit Breite und Höhe (wird evtl verkleinert oder ähnliches)
- [ ] Angepasst auf die Seite bzw. das Widget mit Breite und flexibler Höhe (Scrollbalken)
- [ ] Nicht angepasst auf die Seite bzw das Widget sondern mit flexibler Breite und flexibler Höhe

Diese 3 Optionen sollte man wählen können.

Zurzeit ist es so das man bei unterschiedliche HTML Seiten teils unterschiedliche Darstellungsform erhält, die man nicht auswählen kann.
Beispiel:
![image](https://user-images.githubusercontent.com/84818934/128188093-d53ded8f-26f2-4ae4-83ea-751186f683bb.png)

Diese HTML-Seite ICONS wird als iFrame dargestellt, obwohl es eine HTML-Seite ist. Dieses iFrame wird in dem Widget mit fester Breite fixiert und ist in der Höhe flexible bzw scollbar eingestellt (warum auch immer, denn man kann es nicht einstellen)
![image](https://user-images.githubusercontent.com/84818934/128188376-472be011-9208-455d-86bf-2f70bee6232c.png)

2. Beispiel Auch HTML-Seite
TV-Seite wird auf den festgelegten Widget-Bereich verkleinert
![image](https://user-images.githubusercontent.com/84818934/128188605-6b7403b4-ca02-4625-80ae-5421b06e740c.png)
Dort würde es auch besser aussehen, könnte man es einstellen, dass auch dort ein Scrollbalken in der Höhe verwendet werden soll.
Ausserdem wird dieses HTML nicht als iFrame dargestellt?
Es scheint so, als wenn die HTML-Seite mit in jarvis integriert wird?
![image](https://user-images.githubusercontent.com/84818934/128189319-0a851405-0f9e-4328-b495-ae7f4de65e4d.png)

**Comment by Zefau** [comment]
Die Inhalte eines iFrames kann ich nicht beeinflussen. Wie ist die Situation in v2? Meiner Meinung nach müssten die iFrame in sich geändert werden.

**Comment by mcuiobroker** [comment]
Beide Objekte sind als Widget "stateHTML" eingetragen. Auch in v2 werden sie als iFrame erkannt, obwohl sie dort auch als customHTML zugeordnet sind. Deswegen ja meine Verwunderung. 

![image](https://user-images.githubusercontent.com/84818934/128247238-c43417a3-7341-47b6-af84-959bfa0e2be3.png)
![image](https://user-images.githubusercontent.com/84818934/128247390-87b92e6c-f5b0-4cf7-8d88-1ecc70d02e00.png)

**Comment by Zefau** [comment]
Weil du `<script>` drin hast. Das funktioniert nur mit iFrame.

**Comment by mcuiobroker** [comment]
Mit dem Hinweis reicht es erstmal. Falls noch Problem sein sollten, mach ich einen neuen Issue.
