### ISSUE TITLE
v3: HistoryGraph Bugs

### ISSUE THREAD

**Issue by bmk666** [Zefau/ioBroker.jarvis#880]
Hi,

- [x] 1. 

Ein Problem ist das bei mir nicht immer alle Daten im historischem Chart angezeigt, die letzten Werte liegen immer ein paar Stunden in der Vergangenheit (Auch nach aktualisieren der Seite):

![image](https://user-images.githubusercontent.com/47809644/128993451-34d93d71-57f8-4dfc-af17-16ec2c511212.png)

Werte sind aber bis zum jetzigen Zeitpunkz forhanden:

![image](https://user-images.githubusercontent.com/47809644/128993753-9df8078e-1daa-45ff-a4ca-c8579fe19774.png)
_____

- [x] 2. 

Ich bekomme nur Werte angezeigt wenn ich mehr als einen Datenpunkt im Chart habe.
_____

- [x] 3.

Wenn ich mehr als 1 chart pro tab habe kann ich nur auf dem ersten chart den Zeitraum ändern und bei Änderungen des Zeitraums des ersten Charts scheint es Auswirkungen auf den zweiten zu haben!
_____

- [x] 4.

Die Legende ist nicht lesbar (schriftfarbe vielleicht weiß?), nur wenn ich einen Filter auf einen Datenpunkt setze ist der Name des ausgeblendeten Datenpunktes sichtbar:

![image](https://user-images.githubusercontent.com/47809644/128995029-ce4dea63-7cd9-4fa9-8f1b-53972a8884ce.png)

![image](https://user-images.githubusercontent.com/47809644/128995082-0f4df07b-b3c1-481f-b990-5caf9e4946b3.png)

Danke & Grüße,
Sascha

**Comment by bmk666** [comment]
Installierte Version:  
3.0.0-alpha.49

**Comment by bmk666** [comment]
Hab grad noch was festgestellt. Hatte bei dem Obersten Screenshot die Agregation der Werte deaktiviert, aber nach erneutem aktivieren komm ich trozdem nur an 2 Stunden in der Vergangenheit

**Comment by Zefau** [comment]
schau mal bitte mit der `v3.0.0-alpha.52`.

**Comment by bmk666** [comment]
Hi, leider keine Besserung:

oben ein flot chart unten von jarvis:

![image](https://user-images.githubusercontent.com/47809644/130212039-03fff6fc-c916-4338-b72a-5569a1fe2700.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.54`. Aggregation hast du aus?

**Comment by bmk666** [comment]
Hi, leider immer noch nicht, ja agregation is aus!

was ich aber festgestellt habe, es werden glaube ich alle werte angezeigt, aber die Zeit vom jarvis chart ist falsch!

jarvis chart:

![grafik](https://user-images.githubusercontent.com/47809644/130316069-0108bf88-d482-4a9b-8d9a-e63598e8d8a4.png)

flot:

![grafik](https://user-images.githubusercontent.com/47809644/130316096-95086bf6-5d35-475f-a8ce-fe973bd2a1d5.png)

gleiche Temperatur nur andere Zeit!

![grafik](https://user-images.githubusercontent.com/47809644/130316112-a83c5d49-2b5e-4553-b43a-8b4a048590da.png)

**Comment by bmk666** [comment]
Also bei mir ist der Fehler leider immer noch da, was mir aufgefallen ist, ist das die Werte unten wo man den Zoom einstellen kann, anscheind richtig dargestellt werden:

![image](https://user-images.githubusercontent.com/47809644/132482303-409cc3a0-e0ed-4d5f-b04f-7e7b94649a62.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/discussions/930

**Comment by Zefau** [comment]
die zeitliche Darstellung sollte mit `v3.0.0-alpha.81` nun passen.

**Comment by Zefau** [comment]
@Bernd9000 (#1037) schau bitte nochmal mit `v3.0.0-alpha.83`.

**Comment by Bernd9000** [comment]
Sieht gut aus, Zoombereich ist jetzt richtig.
@bmk666
Und bei Dir?

**Comment by bmk666** [comment]
Ja ich kann auch bestätigen, schaut jetzt alles gut aus!

**Comment by bmk666** [comment]
Funktioniert jetzt mit 3.0.0-alpha.84
