### ISSUE TITLE
KNX Import

### ISSUE THREAD

**Issue by bmk666** [Zefau/ioBroker.jarvis#881]
Hi,

Der Import der KNX Geräte funktioniert, nur ist die Benamsung nicht ideal so das ich mit dem meisten importrierten Devices nichts anfangen kann. 

So schauen bei mir die KNX Objekte im IOBroker aus:

![image](https://user-images.githubusercontent.com/47809644/129026791-15ca7031-d65f-4ab2-94c0-f1fa216bad6d.png)

Und so die Devices in Jarvis:

![image](https://user-images.githubusercontent.com/47809644/129027005-84cb2142-de2e-40d9-bb2f-f838fbea8e14.png)

Ich kann nicht mehr auseinanderhalten aus welchen Räumen die Devices sind, liegt vielleicht auch an Meiner benamsung der KNX Objekte, aber hier würde es helfen wenn die Ordnerstruktur wie auf dem Screenshot der IOBroker Objekte zu sehen in den Namen der Devices in Jarvis mit einfließen könnte beim Import.

Also das dann z.B. "**Licht DECKE Schalten**" so aussehen könnte "**OG - Flur - Licht DECKE Schalten**"

Grüße,
Sascha

**Comment by Zefau** [comment]
Der Name kommt aus dem Objekt. Dort findest du unter `common` den Namen. Was steht da bei dir drin?

**Comment by bmk666** [comment]
Hi,

hier einmal von meinem KNX Objekt:

![image](https://user-images.githubusercontent.com/47809644/130582920-4e2d8dbf-ff9e-4f84-9ec9-a8e0f0b87cd7.png)

vielleicht wäre es besser das Feld "_id" als Namen in Jarvis zu nehmen, da wäre der komplette Pfad mit drin!

**Comment by Zefau** [comment]
schau mal mit `v3.0.0-alpha.61`.

**Comment by bmk666** [comment]
schaut perfekt aus dank!

![image](https://user-images.githubusercontent.com/47809644/132641552-c2b086e1-5f83-467c-aa0c-acba219381e3.png)
