### ISSUE TITLE
v3: Farbauswahl für Background und Color für alle Standard-Elemente in Theme-Einstellungen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#884]
Viele Farben sind jetzt schon als Variablen in jarvis definiert. Diese sollte man möglichst über die Theme-Einstellungen anpassen können. Somit braucht man nicht mehr den komplizierten CSS-weg gehen.
z.B. 
:root {
    --q-color-dark: #303030;
}
.body--dark .body {
    background-color: #303030;
}
Somit kann sich jeder sein eigenes Theme zusammenstellen. 
Diese Einstellungen sollte man exportieren und importieren können, da sich einige User auch austauschen und evtl eine optimale Theme-Konfiguration nutzen möchten.
#503

**Comment by Zefau** [comment]
Was spricht gegen CSS?

Und welche Farben wären das außer dark? Der Rest ist ja schon drin?

**Comment by mcuiobroker** [comment]
Momentan muss ich mir die einzelnen Variablen raussuchen, bis es passt. Wenn man sie schon alle als Übersicht in den Theme-Einstellungen hat, weiss man was man steuern kann. Bei einigen geht es jetzt mit der Variablen und bei nur mit Klassenzuordnung. Und Import / export hilft den User die eine Gute Kombination von Farben gezeigt bekommen und diese übernehmen möchten, ohne lange darüber zu diskutieren, welche CSS Einstellungen ich für welche Farbe dann machen muss. Denn in den CSS-Einstellungen sind ja auch noch andere Einträgen für Effekte usw.

**Comment by mcuiobroker** [comment]
#tabBar > div > div.row.nowrap > a:nth-child(4)
{background-color: #ff00ff}

In v2 konnte man den TABs eine grundlegende Farbe zuordnen, das geht in v3 nicht (oder hat sich was geändert?):
.jarvis-Tab-home {
 background-color: blue;
}

Weiterhin geht es auch darum, dass man bestimmte Felder eine Farbe zuordnen kann und auch Effekte (Blinkendes TAB -> schau mal da rein, da ist was besonderes) unabhänigg von der TAB-Umschaltung.

**Comment by mcuiobroker** [comment]
Wie kann ich der Box eine eigene Hintergrundfarbe festlegen oder Effekte zuordnen?
![image](https://user-images.githubusercontent.com/84818934/129446007-9d388670-c9fd-4a33-b6da-ce20a4404c35.png)

**Comment by Zefau** [comment]
Duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/503. Closing this because the other Feature Request has votes on it.
