### ISSUE TITLE
v3: Einstellungen werden nicht gespeichert

### ISSUE THREAD

**Issue by noffycws** [Zefau/ioBroker.jarvis#888]
`alpha.50`:
Ich füge einem Gerät einen Datenpunkt hinzu, packe den auf ein StateListe-Widget und möchte dann die Konfiguration über "Save&Exit" speichern. Da tut sich nichts. In der Browser-Konsole kommt folgender Fehler:

```
vendor.34faf99f.js:1 TypeError: Cannot read property 'forEach' of undefined
    at 6.28362303.js:1
    at Array.forEach (<anonymous>)
    at a.save (6.28362303.js:1)
    at click (6.28362303.js:1)
    at oe (vendor.34faf99f.js:1)
    at a.n (vendor.34faf99f.js:1)
    at oe (vendor.34faf99f.js:1)
    at a.t.$emit (vendor.34faf99f.js:1)
    at a.click (vendor.34faf99f.js:1)
    at oe (vendor.34faf99f.js:1)
    at HTMLButtonElement.n (vendor.34faf99f.js:1)
    at HTMLButtonElement.Po.o._wrapper (vendor.34faf99f.js:1)
    at HTMLButtonElement.i (vendor.34faf99f.js:1)
```

Somit kann ich derzeit keine Änderungen an der Konfiguration vornehmen. "Cancel" geht.

Btw: Ich habe auch den englischen für die Buttons. Ist das normal und sind die nur noch englisch? Habe im Hinterkopf, dass die mal deutsch beschriftet waren.

**Comment by Zefau** [comment]
An welcher Stelle kommt der Fehler im Log, kannst du das mal parallel nachverfolgen? Also kommt dieser, wenn du den Datenpunkt im Gerät pflegst oder erst mit dem Hinzufügen im Widget?

Ist das ein neues oder bereits existierendes Widget?

Dann kann ich es besser eingrenzen. Danke dir.

**Comment by Zefau** [comment]
Laut meiner Analyse kommt der Fehler scheinbar genau beim Speichern (also beim Drücken des Knopfes).

**Comment by noffycws** [comment]
Oh sorry, nicht präzise genug:
Ja, wenn man auf "Save" oder auf "Save+Exit" klickt ... und erst dann. Alles andere erzeugt keine Fehler.
Es kommt auch, wenn man einfach die Einstellungsseite öffnet und dann mit den Buttons wieder schließen möchte.

Ist es auch richtig, dass zwar die Buttons unten in Englisch sind, der Rest (Geräte, Widgets usw.) aber in Deutsch? Ist mit der alpha.51 weiterhin so.

**Comment by Zefau** [comment]
schau mal bitte mit der `v3.0.0-alpha.52`.

**Comment by noffycws** [comment]
Heute mal mit der ´alpha.58´ getestet und schein gefixt zu sein.
