### ISSUE TITLE
Webseite als webapp auf smartphones

### ISSUE THREAD

**Issue by Bjoern3003** [Zefau/ioBroker.jarvis#889]
Wäre es möglich, die meta Tags in jarvis zu integrieren, damit die Webseite als webapp betrieben werden kann. 

`

    <meta name="apple-mobile-web-app-capable" content="yes">
    
    
    <meta name="mobile-web-app-capable" content="yes">
`

**Comment by Zefau** [comment]
schau mal bitte mit der `v3.0.0-alpha.52`.

**Comment by Bjoern3003** [comment]
Perfekt, danke. Funktioniert. 👍
