### ISSUE TITLE
v3: Datenpunkte werden doppelt angezeigt

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#893]
Version:  3.0.0 Alpha 55

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/13101074/130334849-ce068716-4861-4388-80f5-630a59c00d0d.png">

Datenpunkte werden doppelt angezeigt

**Comment by Zefau** [comment]
Wie sieht denn die Struktur darunter aus und wie sieht es im ioBroker aus?

Sind das die einzigen doppelten Einträge? Mir scheint da was im linkeddevices inkorrekt?

**Comment by AFPass** [comment]
Das ist bei jedem Node den ich öffne so. Nicht nur bei Linkeddevice.

(Kann gerade leider kein Bild hochladen)

**Comment by Zefau** [comment]
Besteht das Problem mit `v3.0.0-alpha.58` eigentlich noch? Ich bekomme das bei mir nicht nachgestellt. Bei mir ist alles nur einmal vorhanden.

**Comment by AFPass** [comment]
Sieht gut aus.
