### ISSUE TITLE
v3: Datenpunkt kann nicht hinzugefügt werde 

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#894]
Version: 3.0.0 alpha 55

Wenn ich ein Gerät anlege, und auf "DATENPUNKT HINZUFÜGEN" klicke passiert nichts.

Der Fehler tritt sporadisch auf. Nach Reload der JARVIS Seite funktioniert es eine Weile.

**Comment by Zefau** [comment]
Fehler in der Browser Konsole?

**Comment by AFPass** [comment]
Ok. Mach ich wenn der Fehler wieder kommt

**Comment by AFPass** [comment]
<img width="1647" alt="image" src="https://user-images.githubusercontent.com/13101074/130335921-2f6d2847-eb8b-47ab-b29b-e7c3fbdcddc9.png">

Hier ein Screenshot von der Konsole.

**Comment by Zefau** [comment]
Probier nochmal bitte mit `v3.0.0-alpha.57`. Sollte das nicht gehen, dann schicke mir mal bitte dein Layout (`jarvis.0.layout`) via https://pastebin.com/ (inkl. Passwort und Ablaufzeit).

**Comment by AFPass** [comment]
Hier noch mal ein aktuellen Screenshot mit Goggle Chrome.

<img width="1557" alt="image" src="https://user-images.githubusercontent.com/13101074/130357090-05862707-56bd-4679-80be-58b31472a2e8.png">

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.58` nun funktionieren (bzw. einen Fehler ausgeben, sofern die Benutzer-Eingabe inkorrekt ist).

**Comment by AFPass** [comment]
Werde ich heute Abend genauer prüfen.

**Comment by Zefau** [comment]
@AFPass und? :-)

**Comment by mcuiobroker** [comment]
Passt.
