### ISSUE TITLE
v3: Gerät - Datenpunkt ändern

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#896]
Wenn bei einem Gerät ein Datenpunkt hinterleget ist und man auf den Datenpunkt Explorer klickt, währe es gut, wenn der Explorer den aktuellen Datenpunkt selektiert.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.58` nun so funktionieren.

**Comment by AFPass** [comment]
Ja. Eintrag wird markiert. Focus zum Eintrag fehlt noch.

**Comment by Zefau** [comment]
Was meinst du mit Fokus?

**Comment by AFPass** [comment]
Wenn ein Datenpunkt zugewiesen ist und man den DP Explorer wieder öffnet, ist die Liste ganz oben.
![grafik](https://user-images.githubusercontent.com/13101074/130516985-fab1454a-afb0-43cc-aaaa-91628092b5c1.png)

Schön wäre es, wenn die Liste schon zu den DP "scrollt"
![grafik](https://user-images.githubusercontent.com/13101074/130517079-56101049-027e-4cef-88af-1d9fde712dd1.png)

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.62` sollte nun der Fokus korrekt gesetzt werden, nachdem der StateExplorer geladen ist.

**Comment by mcuiobroker** [comment]
Funktioniert nicht. Setzt zwar den Fokus, springt aber nicht zum DP. Er bleibt oben nach dem Laden stehen.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
Passt.
