### ISSUE TITLE
v3: TimeOut Fehler

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#898]
Version: 3.0.0 alpha 56

Plötzlich kommt nur noch eine TimeOut Meldung.
Neustart von ioBroker Server hat nicht geholfen.

<img width="1646" alt="image" src="https://user-images.githubusercontent.com/13101074/130337573-f31bc1ee-14a0-4f90-a8b8-c1a035e881d0.png">

**Comment by Zefau** [comment]
Probier nochmal bitte mit `v3.0.0-alpha.57`. Sollte das nicht gehen, dann schicke mir mal bitte dein Layout (`jarvis.0.layout`) via https://pastebin.com/ (inkl. Passwort und Ablaufzeit).

**Comment by AFPass** [comment]
Geht wieder. Danke.
