### ISSUE TITLE
v3: Fehlende Datenpunkte

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#899]
Version 3.0.0 alpha 57

Über den Explorer habe ich einen DP ausgewählt. Gehe ich später in dieEigenschaften, wird der Datenpunkt nicht angezeigt.
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/13101074/130355577-3b1d8fec-b923-4616-9aed-97ecefc99f10.png">

Ich habe 01_currentDay ausgewählt.

Hier fehlt der Wert aber.
<img width="1021" alt="image" src="https://user-images.githubusercontent.com/13101074/130355523-13e26729-8f1d-4c56-be4a-7d91d4a6a628.png">

Später in der Anzeige wird der Wert auch nicht angezeigt.
<img width="1616" alt="image" src="https://user-images.githubusercontent.com/13101074/130355632-21935969-a939-4b01-a74e-4d6cf4cb97ca.png">

**Comment by Zefau** [comment]
versuch bitte nochmal mit `v3.0.0-alpha.58`. Das Dropdown zeigt nur max. 7 Einträge an. Nichtsdestotrotz sollte die Auswahl im StateExplorer natürlich den kompletten Datenpunkt übernehmen und nicht nur einen Teil davon (jedenfalls sieht es so aus, als wäre nicht alles übernommen worden?)

**Comment by AFPass** [comment]
Sieht gut aus. Im Explorer wird auch der entsprechende Eintrag markiert. Fehlt nur noch der Fokus dahin.

**Comment by Zefau** [comment]
Was meinst du mit Fokus?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/896#issuecomment-903680150
