### ISSUE TITLE
States in popup window not correct

### ISSUE THREAD

**Issue by braindead1** [Zefau/ioBroker.jarvis#9]
The state in the popup window does not fit to the state shown in the overview.

The following JSON is used in the devices JSON to create the state on the screenshot.

```
{
  "alarm_aktiviert": {
    "name": "Status",
    "function": "default",
    "states": {
      "activated": {
        "state": "alarm.0.status.activated"
      }
    },
    "jarvis": {
      "group": "alarm",
      "state": {
        "true": "aktiviert",
        "false": "deaktiviert"
      },
      "icon": "alarm-check"
    }
  }
}
```

![state](https://user-images.githubusercontent.com/2136249/76170675-75e8f480-6184-11ea-840f-4c6a5886e7c5.png)

**Comment by Zefau** [comment]
Should be fixed with v0.0.3. Could you please test and verify? Thanks

**Comment by braindead1** [comment]
I installed v0.0.4 and the value of the state is correct now. 

Regarding the name of the state ("default#activated" on the screenshot above) what is the correct way to "translate" it? Translations in jarvis.0.settings or is there another option I'm not aware of?

**Comment by Zefau** [comment]
Great it works. 

Please find details regarding translations on the updated wiki page: https://github.com/Zefau/ioBroker.jarvis/wiki/Einstellungen#einstellung-translations

**Comment by braindead1** [comment]
Although I understand your intention to implement translations, I assume that most users will only use one language. Besides that I think that there will be situations where a state name may have different translations depending on the device. 

Instead of translating states in jarvis.0.settings it may be a good idea to implement the possibility to set the name (label) of the state in the state.

`{"esszimmer_fenster": {
    "name": "Esszimmer",
    "room": "esszimmer",
    "function": "window",
    "states": {
      "open": {
        "state": "hm-rpc.1.XXXXXXXXXX.1.STATE",
        "label": "Status"
      }
    },
    "jarvis": {
      "group": "fenster_erdgeschoss"
    }
  }
}`
