### ISSUE TITLE
v3: Infomeldung wenn History Offline

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#901]
Ich habe beim Testen der History Anzeige meinen History Adapter gestoppt. In diesem Fall InfluxDB.
Bevor die leere Anzeige kommt, wartet das Widget lange auf Antwort. Vielleicht kannst Du vorher eine Prüfung einbauen ob die Verbindung besteht und eine entsprechende Meldung im Widget anzeigen.

![grafik](https://user-images.githubusercontent.com/13101074/130440840-af95fc72-fea5-4793-b4e5-89b04c5c818b.png)

**Comment by fprobst170** [comment]
Ich bekomme bei der History Anzeige die Meldung `history.0 not reachable!`. Seit welcher Version dies so ist kann ich nicht sagen.  Ich verwende `SQL-Protokollierung` mit MySQL.

![image](https://user-images.githubusercontent.com/78404006/140601638-f6873df7-c9c2-43e8-97e7-aabdf41b2e05.png)

**Comment by Zefau** [comment]
In der Konfiguration hast du sql ausgewählt?

Bitte mal testweise reingehen und was anderes auswählen und speichern und danach wieder umstellen.

**Comment by fprobst170** [comment]
Ja da hab ich SQL gewählt. Ist bei mir die einzige Möglichkeit. Hab schon versucht so einiges umzustellen bzw. auch neu anzulegen. Anbei ein Screenshot mit meinen Einstellungen. 
![image](https://user-images.githubusercontent.com/78404006/140604162-ec1e903c-4fa7-47b0-b376-0787350a6ad2.png)

**Comment by Zefau** [comment]
Aber hast du wie geschrieben mal history.0 eingestellt und gespeichert und danach nochmal umgestellt?

**Comment by fprobst170** [comment]
Meine Instanz des Adapters ist sql.0

![image](https://user-images.githubusercontent.com/78404006/140604693-075467ed-f9f6-4df9-96a5-f26aeec378e3.png)

So wie in den Einstellungen eingestellt. Ich hab nur sql.0 zur Auswahl da ich nur eine Instanz zur Protokollierung hab.
![image](https://user-images.githubusercontent.com/78404006/140604836-0ba09df8-d39d-4da3-816f-a2bf26907bde.png)

In der Ansicht wird aber dann history.0 geschrieben.
![image](https://user-images.githubusercontent.com/78404006/140604869-86268d9a-28b9-4f61-a4df-bc32007aae65.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1149
