### ISSUE TITLE
v3: icon Auswahl

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#902]
Kannst Du bei den Feldern, bei denen ein Icon ausgewählt wird ein Suchbox einbauen?
Also ich gebe zum Beispiel light ein und bekomme in einer DropDown Box möglich Icons mit light im Namen angezeigt. Und/oder ein Link zum Beispiel nach https://materialdesignicons.com/ zur Icon Auswahl.

**Comment by dfoxg** [comment]
Wird aktuell https://materialdesignicons.com/ verwendet? Weil einige Icons aus dem ["offiziellen" Google Material Icon-Set](https://fonts.google.com/icons) funktionieren nicht.

**Comment by mcuiobroker** [comment]
https://icon-sets.iconify.design/mdi/

**Comment by dfoxg** [comment]
> https://icon-sets.iconify.design/mdi/

Danke!

**Comment by flyinghuman** [comment]
Das Feature wäre echt praktisch; damit wäre das alles etwas "Runder" und man müsste nicht immer auf die anderen Webseiten schauen wenn man ein Icon benötigt. Die anderen Visualisierungen machen es teilweise auch; bspw. hier: 
![icon-chooser](https://user-images.githubusercontent.com/3713548/176173281-6f41f0bf-b2d2-4c51-810e-465c3dbb79b7.gif)

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.27` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.27`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Man kennt den Namen von dem Icon, welches man sucht doch nicht?

![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/68df0dcb-1eaf-43a6-84ce-8a194b1b6fa7)

**Comment by Zefau** [comment]
> Man kennt den Namen von dem Icon, welches man sucht doch nicht?

Wofür dann der Feature-Request? Man kann nach Stichwörtern suchen und bekommt dann die Icons, die den Suchbegriff im Namen haben bzw. einen entsprechenden Alias haben.

> Klickt nach Auswahl von einem Icon auf die Klammern

Fixe ich.

**Comment by mcuiobroker** [comment]
In grau hinterlegen "Suchbegrif eingeben"?

**Comment by Zefau** [comment]
Verwirrt das nicht noch mehr? Müsste ich dann ja auch beim `Datenpunkt (Anzeige)` machen, da dort ja auch nach Datenpunkten gesucht werden kann?

**Comment by mcuiobroker** [comment]
Da hat man ja den DB-Button.

**Comment by Zefau** [comment]
Was meinst du mit DB-Button?

Ich mein das Dropdown, wie bei den Icons auch:

![grafik](https://github.com/Zefau/ioBroker.jarvis/assets/14368811/ae8b602d-f015-487b-9d8b-9da1f9e2cb22)

**Comment by mcuiobroker** [comment]
![Image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/425eb927-6855-4d91-8288-257d4084d17d)

**Comment by Zefau** [comment]
Der öffnet den StateExplorer. Das Dropdown steht ja auch so zur Verfügung.

**Comment by Zefau** [comment]
Die Version `v3.2.0-alpha.30` sollte den Fehler beheben - bitte einmal prüfen. Sofern es behoben ist, gerne das Issue schließen.<br /><hr />The version `v3.2.0-alpha.30` should fix the bug - please verify. If the bug has been solved, you may close the issue.
