### ISSUE TITLE
v3: Geräteauswahl beim Widget anlegen nicht scrollbar

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#903]
Version 3.0.0 alpha 59

Die Geräteliste beim anlegen eines Widget ist nicht scrollbar.

![grafik](https://user-images.githubusercontent.com/13101074/130564997-0300acef-e8e4-4c08-bb23-379410df2d50.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.18`

**Comment by kevinhaybach** [comment]
Bei mir besteht der Fehler immer noch in Version 3.0.11 mit Google Chrome

<img width="772" alt="image" src="https://user-images.githubusercontent.com/83004345/196036554-014ed2c3-a6d4-4a5a-a300-4d7f78dc6345.png">

**Comment by Zefau** [comment]
Schau mal bitte mit  V3.1.0-alpha

**Comment by kevinhaybach** [comment]
Dafür muss ich wie in .. beschrieben https://github.com/Zefau/ioBroker.jarvis.git mit dem Link installieren oder? Da es sich dabei nicht um eine stable Version handelt. Kann ich von meinem Projekt vorher ein Backup erzeugen? Bzw. Es werden ja automatisch Backups erzeugt aber da steht so ein Satz "Please be aware that backups will be deleted when the adapter is updated." 
Ich würde jetzt ungern mein Projekt verlieren :D

**Comment by mcuiobroker** [comment]
Du kannst die einzelnen DPs(jarvis) als txt-Dateien sichern oder nutzt ein Programm dafür.
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/system-effektprog./v3-systemprogramme/savejarvisdps

**Comment by kevinhaybach** [comment]
So neue Version installiert und immer noch das gleiche 
<img width="787" alt="image" src="https://user-images.githubusercontent.com/83004345/196043017-9d80bc9a-fe05-4499-8f9a-70c976cdcab6.png">
aber nach dem hinzufügen des ersten Devices springt es um vorher ist er erst beim dritten hinzufügen umgesprungen
<img width="765" alt="image" src="https://user-images.githubusercontent.com/83004345/196043095-4f91398a-9127-457f-a939-89062aa4aaf3.png">

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.1.0-alpha.59`

**Comment by kevinhaybach** [comment]
Mit v3.1.0-alpha.59 kann ich es nicht mehr reproduzieren und scheint somit gelöst zu sein
