### ISSUE TITLE
v3: Widget - fill full width

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#905]
Version 3.0.0 alpha 59

Ich habe bei einem Widget "fill full width" ausgewählt.
![grafik](https://user-images.githubusercontent.com/13101074/130567543-385ca0af-bb2b-4397-94cc-50bebfea118b.png)

Trotzdem wird das Widget im Desktopmodus mit der Breite angezeigt die im Editor festgelegt ist angezeigt.
![grafik](https://user-images.githubusercontent.com/13101074/130567689-695d4f92-7efe-4e76-9734-9b7665682bdb.png)

**Comment by Zefau** [comment]
Die Option bezieht sich auf die Inhalte des Widgets in Relation zum Widget. Es bezieht sich nicht auf das Widget bzw. auf das Widget in Relation zur Seite.
