### ISSUE TITLE
v3: Layout Reihnfolge auf Smartphone nicht richtig

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#907]
Version: 3.0.0 alpha 59

Im Tab ist definiert, dass 2 Widgets untereinander sind. Auf dem Desktop wird die Reihenfolge richtig dargestellt. Auf dem Smartphone ist die Reihenfolge vertauscht.

**Comment by Zefau** [comment]
In der Konfiguration steht eine kleine Zahl in Widget. Das ist die responsive Position. Aktuell abhängig vom Hinzufügen; später konfigurierbar
