### ISSUE TITLE
v3: HistorGraph - Aggregation

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#908]
Version 3.0.0 alpha 59

Wird die Aggregation ausgeschalten, werden keine Daten mehr angezeigt.
![grafik](https://user-images.githubusercontent.com/13101074/130607746-1678636a-6c05-45a3-9c71-547e85058884.png)

![grafik](https://user-images.githubusercontent.com/13101074/130607818-fef3229e-186a-468d-935f-822e03e766d6.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/880

**Comment by Zefau** [comment]
ich schließe dieses Issue, da in #880 bereits viel darüber diskutiert wird.

Liegt an der 2h Zeitverschiebung zu UTC. Alles über 2h wird angezeigt. Ich bin dran, dass zu fixen.
