### ISSUE TITLE
v3: Map Ansicht

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#910]
Versio: 3.0.0 alpha 59

Kannst Du die zwei Kreise um das Logo wieder entfernen? Macht es meiner Meinung nach unübersichtlich.
![grafik](https://user-images.githubusercontent.com/13101074/130731278-2aa325b1-2dbe-4326-9eae-1a1bd7bfb291.png)

Auch währe es gut, wenn das Gerät in der Karte zentriert wird und nicht so weit unten angezeigt wird.
So in etwa:
![grafik](https://user-images.githubusercontent.com/13101074/130731422-41e34fcc-0ea4-456d-adbc-e47e754edc42.png)

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1390
