### ISSUE TITLE
v3: Geräten Räumen zuweisen

### ISSUE THREAD

**Issue by bmk666** [Zefau/ioBroker.jarvis#911]
Aktuell gibt es ja nur feste "Funktionen" in denen man Geräte aufnehmen kann (z.B. "Licht"). Das schränkt ziemlich ein.
Hier wäre es vielleicht gut eine neue Ebene zu schaffen wie z.B. Räume

Raum: **Küche**
Funktion: **Lampe**

und es wäre schön wenn man eigene Funktionstype erstellen könnte wo man dann auch vorgeben kann was es für eigenschaften gibt und welche ions und so benutzt werden sollen für diesen Typ!

- [ ] Möglichkeit die Funktionen und Räume von ioBroker bei dem Import der Geräte zu übernehmen.

**Comment by Zefau** [comment]
Eigene Gewerke siehe https://github.com/Zefau/ioBroker.jarvis/issues/188

Wofür die Raumzuweisung ?

**Comment by palsch** [comment]
Hi @Zefau, gibt es eigentlich eine Möglichkeit die Funktionen und Räume von ioBroker bei dem Import der Geräte zu übernehmen?

**Comment by Zefau** [comment]
Kann ich gerne mit in den Feature Request aufnehmen.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.6` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.6`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.

**Comment by mcuiobroker** [comment]
Worauf bezieht sich der Aliases? Wo sieht man den / die, wann wird dieser genutzt?
![image](https://github.com/Zefau/ioBroker.jarvis/assets/84818934/7b8dbc17-9946-4d2b-a100-42cde2234c59)

Dürfen bei Tags mehrere Bbegriffe enthalten sein, damit die Sortierung der Geräte noch läuft?

**Comment by Zefau** [comment]
> Worauf bezieht sich der Aliases? Wo sieht man den / die, wann wird dieser genutzt?

Gute Frage! Der Alias dient (mir) zur Gruppierung im IoT-Adapter. Ich habe z.B. ein Gerät "Licht Küchenzeile" und ein "Gerät Licht Küchendecke". Bei beiden habe ich im Alias "Licht Küche" hinterlegt. Durch die neue Funktion die Geräte im IoT Adapter zu registrieren kann ich durch den Alias die beiden Geräte quasi zeitgleich ansteuern (= gruppieren).

> Dürfen bei Tags mehrere Bbegriffe enthalten sein, damit die Sortierung der Geräte noch läuft?

Kannst du das näher erklären? Mehrere Begriffe in einem Tag funktioniert - also Leerzeichen sind erlaubt. Was meinst du mit Sortierung? Das ist alphabetisch und nur nach dem ersten Buchstaben, falls das die Frage beantwortet.

>  Floor wird nicht in der Übersicht angezeigt?

Doch, vor in der Spalte Raum vor dem Raum.

>  Gruppiering nach Floor?

Nehme ich auf.

>  Übersetzung in Deutsch?

Jo, kommt bei mir immer zu kurz.

**Comment by Zefau** [comment]
Dieser Feature Request wurde mit `v3.2.0-alpha.7` implementiert. Bitte bestätigen und auf Fehler prüfen. Wenn alles in Ordnung ist, gerne das Issue schließen.<br /><hr />This feature request has been implemented with `v3.2.0-alpha.7`. Please verify and test the feature for any bugs. If everything works as expected, you may close the issue.
