### ISSUE TITLE
Label in Abhängigkeit vom Wert ändern

### ISSUE THREAD

**Issue by hardl1** [Zefau/ioBroker.jarvis#915]
- [ V3.0.0-alpha.59} 

**Describe the bug / Beschreibe den Fehler**
Das Label bei "N-ERGIE" abhängig vom Wert ändern, {">0":"Ertrag", "<=0":"Bezug"} bleibt leer.

<img width="526" alt="Bildschirmfoto 2021-08-26 um 14 00 48" src="https://user-images.githubusercontent.com/38688960/130959110-8c60d98d-ccc9-4d56-b357-321c111086b7.png">

**Screenshots**

<img width="1034" alt="Bildschirmfoto 2021-08-26 um 13 49 33" src="https://user-images.githubusercontent.com/38688960/130958675-849f8ef4-ff16-4bc6-8611-7ca3b72f626b.png">

**Comment by hardl1** [comment]
Ich muss mich nochmals korrigieren:
Unter Objekte Alias ändern sich die Werte nur wenn im Browser automatische oder permanente Übersetzung von Englisch auf Deutsch eingestellt ist. Wenn dann aktualisiert wird, springt die Anzeige von 12,345 auf 12.345, allerdings nur bei Werten >0,99.

Bei Englisch immer auf Deutsch übersetzen führt das auch zu den Angaben "vor über 51 Jahren"

Auch wenn ich die Übersetzung ausschalte komme ich allerdings nicht mehr in Jarvis auf Komma-Werte.
Beispiel: Ertrag laut solarlog 2.000 Watt -> im Alias-Adapter konvertiert mit val/1000 = 2,000 -> im Jarvis3 = 2.000

**Comment by hardl1** [comment]
Das Hauptproblem scheint tatsächlich am Alias-Adapter zu liegen, Issue ist eröffnet.
Ohne Übersetzung im Browser ist auch das "51 Jahre" weg und mit der Anzeige "12.345" statt "12,345" kann ich leben.
Kannst Du mir bitte noch einen Weg aufzeigen, wie oder ob ich das Label mit: `{">0":"Einspeisung","<=0":"Bezug"}` anzeigen kann, dann würde ich das Issue schließen.

**Comment by Zefau** [comment]
Kannst du das Issue vom Alias-Adapter hier posten?

**Comment by Zefau** [comment]
Der Eintrag `{">0":"Einspeisung","<=0":"Bezug"}` sollte so funktionieren. Handelt es sich bei dem Wert denn um eine Nummer oder ist es eine Nummer vom Typ String/Zeichenkette?

**Comment by hardl1** [comment]
Es ist ein nummerischer Wert aus dem Alias.

https://github.com/sbormann/ioBroker.alias-manager/issues/16

**Comment by Zefau** [comment]
Jetzt hab ich es mit Fokus auf das Foreign Issue geschlossen. Hast du das mit dem Label jetzt hinbekommen?

**Comment by hardl1** [comment]
Das mit dem Label hat nicht geklappt, aber ich habe das anders gelöst.
Vielen Dank nochmals.

**Comment by Zefau** [comment]
Wie hast du es denn gelöst? :-)

@mcuiobroker könntest du nochmal schauen, ob du das Label in Abhängigkeit vom Wert verändert bekommst?

**Comment by hardl1** [comment]
Ich habe statt "feed", "feedin" und "feedout" als zwei getrennte Datenpunkte verwendet.

**Comment by mcuiobroker** [comment]
Kann es sein das Label auch in Abhängigkeit von "value" ist und nicht "val"?
Da er ja den value in Datenpunkt-Eigenschaften angepasst hatte, dürfte es da in der Anzeige-Variante nicht passen, da er da keine "value"-Werte genutzt hat.

**Comment by Zefau** [comment]
@hardl1 schau nochmal mit `v3.0.0-alpha.78`.

**Comment by mcuiobroker** [comment]
Wo zieht den "value", wo zieht der "val". Das sollte in den "i" stehen.
Der Wert, der angezeigt wird- "value", wird ja nur in den Datenpunkt-Eigenschaften beeinflusst, oder?
Auch die Einheit ist glaub ich in Abhnängigkeit vom "Value", sollte auch auf "val" sein.
Quasi alle ausser "Datenpunkt-Eigenschaften" auf "val".

**Comment by mcuiobroker** [comment]
Passt noch nicht:

![image](https://user-images.githubusercontent.com/84818934/133471798-9514fb06-f4a8-40c5-a825-c2fd829b230d.png)

![image](https://user-images.githubusercontent.com/84818934/133471662-5873cc2c-bedc-4ec1-9332-e6dfee4b672d.png)

![image](https://user-images.githubusercontent.com/84818934/133471963-6ff0e75d-2373-425c-ad70-f01ffeceae4d.png)


Ich hab es ja nur ein einem geändert? Betrifft aber alle?

![image](https://user-images.githubusercontent.com/84818934/133472265-753b1f65-1249-491d-ace4-0cd02ca34d7b.png)

![image](https://user-images.githubusercontent.com/84818934/133472333-fde6b3f8-9b8b-4d9c-ab37-b33402119411.png)


Oder jetzt wird value gar nicht mehr berücksichtigt in der Anzeige?
Der Anzeigewert muss aus "value"-Wert von Anzeigevariante und Datenpunkt-Eigenschaften "value" gebastelt werden.
Da komme ich shcon fast zur Einstellung das bei in dem "value"-Wert in der Anzeigevariante zu lassen, wie vorher.
Und dann den Hinweis in "i" zu geben, das der AnzeigeVarianten-Wert auf "value" vom Datenpunkt-Eigenschaften beruht. Ist der leer wird dann normal der Value=val sein.

**Comment by mcuiobroker** [comment]
Überlegungen:
Oder man baut für die Fälle mit "vorangestellten Werten: Strings" ein extra Feld. 

Berechnungen werden ja weiterhin im Eigenschaftsfeld gemacht.
Und wenn "val"-Type ungleich "value"-Type dann nehme "value" als Grundlage für die AnzeigeVariante.
Ist der Type (val) = Type(value) dann muss auch wieder "value" nehmen,da sich der Wert durch die Berechnung verändert hat.


Ergebnis: Man muss wieder auf value umschalten und dann für vorangestellte Werte ein extra Feld erzeugen.
In den Datenpunkt-Eigenschaften, darf man dann aber auch nur Berechungen durchführen mit dem gleichen Type-Ergebnis.

**Comment by hardl1** [comment]
@Zefau Die v3.0.0-alpha.78 habe ich installiert, aber ich komme nicht in die Konfiguration.
Ist aber nicht weiter schlimm. Ich bin momentan wieder zur ioBrker-VIS zurück, da ich bei Jarvis keine Möglichkeit finde meine Daten von unterwegs auf dem Iphone abzurufen.
VPN geht nicht mehr seit Dt.Glasfaser, da kein öffentliches IP4. IP6 kann mein Provider O2 nicht. Ich zahle schon die ioBroker.et Cloud und die geht scheinbar nur mit VIS.

**Comment by hardl1** [comment]
@Zefau @mcuiobroker  Heute bin ich problemlos in die Konfiguration gekommen.
Ich denke nicht, dass es mit "val" und "value" zusammenhängt.
Ich habe testweise statt dem Alias-Wert den Solarlog-feed genommen, der nicht beeinflusst wird und auch die Einheit weggelassen, aber das Label bleibt verschwunden.

**Comment by mcuiobroker** [comment]
Ist die Konfig vom Gerät so wie oben?
Du musst die Einheit entfernen.

**Comment by Zefau** [comment]
should be working now with `v3.0.0-alpha.80`.

**Comment by mcuiobroker** [comment]
"<=0" wird erkannt. Dafür aber "1" nicht mehr?
![image](https://user-images.githubusercontent.com/84818934/133791780-57c42724-6ffc-4c46-be69-cf36afeef35d.png)

![image](https://user-images.githubusercontent.com/84818934/133792365-ffb563c6-3bc8-499a-9d20-03053300b869.png)


Sollte da nicht auch Klassenzuordnung möglich sein wie beim StateWert, Icon.
![image](https://user-images.githubusercontent.com/84818934/133791175-89fc62e1-0f8a-4902-b750-28be21c0419d.png)
Und Label-Stil? Wo kann man die farblichen Einstellungen für Label machen?

**Comment by hardl1** [comment]
@zefau Die v3.0.0-alpha.80 habe ich installiert, aber es kommt erst:
Connecting...
Show Log (4)

und dann nach ca. 30 Sekunden:

Error
Hide Log (14)

Im Protokoll steht nur alle 40 Sekunden:
` 
jarvis.0 | 2021-09-17 18:53:09.026 | info | Client with IP ::ffff:192.168.178.21 connected
`

**Comment by hardl1** [comment]
Im debug-Mode:
`


jarvis.0 | 2021-09-17 19:07:52.059 | debug | Connection: Origin detected with http://192.168.178.65:8082 (allowed due to all)
-- | -- | -- | --
jarvis.0 | 2021-09-17 19:07:52.047 | debug | Connection: Origin detected with http://192.168.178.65:8082 (allowed due to all)
jarvis.0 | 2021-09-17 19:07:50.477 | debug | Client with IP ::ffff:192.168.178.21 disconnected: ping timeout
jarvis.0 | 2021-09-17 19:07:05.504 | debug | Connection: Origin detected with http://192.168.178.65:8082 (allowed due to all)
jarvis.0 | 2021-09-17 19:07:05.495 | info | Client with IP ::ffff:192.168.178.21 connected
jarvis.0 | 2021-09-17 19:07:05.494 | debug | Websocket-Handler for client initialized

`

**Comment by Zefau** [comment]
Was steht denn in der Browser Konsole?

**Comment by hardl1** [comment]
@Zefau Sorry, genügt das? Ich bekomme das nicht formatiert
<img width="1446" alt="Bildschirmfoto 2021-09-18 um 10 12 25" src="https://user-images.githubusercontent.com/38688960/133881899-286a313e-e9ec-4403-a518-dec826cd3b4e.png">
.

**Comment by Zefau** [comment]
Kannst du mir einen Screenshot deiner Datenpunkte unter jarvis.0 machen? Da scheint was falsch zu sein, denn ein JSON ist korrekt laut der Meldung.

**Comment by hardl1** [comment]
@Zefau Meinst Du das?
<img width="1594" alt="Bildschirmfoto 2021-09-18 um 11 55 46" src="https://user-images.githubusercontent.com/38688960/133884959-8776de50-58a7-4d46-a5a7-066f389d1f05.png">

<img width="1646" alt="Bildschirmfoto 2021-09-18 um 11 56 07" src="https://user-images.githubusercontent.com/38688960/133884972-a45678ce-6a7f-49ce-9346-19e39a712873.png">

**Comment by Zefau** [comment]
Geb mal bei `notifications` ein leeres Objekt ein: `{}`

**Comment by Zefau** [comment]
sorry, es muss `[]` sein

**Comment by hardl1** [comment]
Neustart Jarvis -> Keine Änderung, 
Falls ich nicht mehr antworte, ich muss gleich weg.

**Comment by hardl1** [comment]
Die Klammer wurde rot, dann habe ich bei AddNotification die null auch durch eine leere Klammer ersetzt, jetzt kommt unter Notification
<img width="1030" alt="Bildschirmfoto 2021-09-18 um 12 21 49" src="https://user-images.githubusercontent.com/38688960/133885696-7de6d535-492c-435e-a414-32f4fc03f089.png">
:

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.81` nun endlich funktionieren

**Comment by mcuiobroker** [comment]
Angezeigt werden sollte eigentlich 2:
![image](https://user-images.githubusercontent.com/84818934/134807948-5096ac70-8b02-4495-9afb-17557aafaac3.png)

![image](https://user-images.githubusercontent.com/84818934/134807959-4397630e-b984-483d-9973-1ef8a3d2e731.png)

![image](https://user-images.githubusercontent.com/84818934/134807975-22e9a90d-0b2f-4cd0-8e6e-be2be6bcbd97.png)

**Comment by Zefau** [comment]
Wieso 2? Sieht richtig aus, da `>1`.

**Comment by Zefau** [comment]
er nimmt den Rohwert `val`, nicht `value`.

**Comment by mcuiobroker** [comment]
> Wieso 2? Sieht richtig aus, da `>1`.

Aufgrund der Datenpunkt-Eigenschaften.

**Comment by Zefau** [comment]
Er nimmt `val`. Das ist immer der Rohwert. `value` ist der transformierte Wert. Auch die Anzeige-Variante nimmt `val`. Wir hatten doch ein Issue auf Basis dessen das umgestellt wurde.

**Comment by mcuiobroker** [comment]
> Er nimmt `val`. Das ist immer der Rohwert. `value` ist der transformierte Wert. Auch die Anzeige-Variante nimmt `val`. Wir hatten doch ein Issue auf Basis dessen das umgestellt wurde.

Das ist ja dieser hier, danach hattest du wieder umgestellt, sonst würde das obere ja nicht funktionieren. ("In 0" usw).
Muss jetzt erst weg. Später weiter.

**Comment by Zefau** [comment]
Wir müssen uns für einen Weg entscheiden und `val` erscheint mir weniger verwirrend für den Benutzer (wie dieses Issue zeigt).

**Comment by mcuiobroker** [comment]
Hab den Fehler bei mir gefunden. War ein falsch geschriebenes parsefloat-> parseFloat bringt jetzt natürlich 2.
![image](https://user-images.githubusercontent.com/84818934/134815644-10f49752-aaaa-426a-bf46-973de2084f61.png)
Schreib bitte in Info "i" rein auf welchen Wert die Anzeige oder Berechnung zugrundeliegt. 
Datenpunkt-Eigenschaft ändert den Anzeigewert, wenn man "value" nutzt.
Alle anderen beziehen sich auf den "val".
Ja dann bleibt es so, muss halt drin stehen, dann gibt es keine Missverständnisse.
