### ISSUE TITLE
v3: Label Feld für Widget

### ISSUE THREAD

**Issue by AFPass** [Zefau/ioBroker.jarvis#916]
Zur Übersicht bei den Labels habe ich im Namen immer den Ort des Gerätes mit angegeben da sonst die Liste mit10-15-20 Einträgen von Licht oder Steckdose unübersichtlich wird.

![grafik](https://user-images.githubusercontent.com/13101074/131075985-64710f8a-ec12-4738-b1cc-951dd2fa965c.png)

Ist einem Layout nun ein Widget zugeordnet wird immer der Name des Widget angezeigt. Hier würde aber ein einfacher Name reichen.

![grafik](https://user-images.githubusercontent.com/13101074/131076073-cfb6b3e9-2e2e-4985-8d64-46d2c0a198b0.png)

**Comment by Zefau** [comment]
This has been introduced with v3
