### ISSUE TITLE
v3: Reihenfolge im Secondary State falsch

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#921]
3.0.0-alpha.60
Habe in jarvis vorgegeben das zuerst die Scheinleistung einer Steckdose und dann der Online Status im Secondary State angezeigt werden soll.Aber egal welche Reihenfolge ich im Widget vorgebe, der Onlinestatus wird immer links angezeigt.

![2](https://user-images.githubusercontent.com/77005685/131193359-3511219c-f0ed-4ec5-a5e0-1eb820d230d2.jpg)
![1](https://user-images.githubusercontent.com/77005685/131193366-1b94f0b5-32f9-409e-8116-327b9f3028ba.jpg)

**Comment by Bernd9000** [comment]
Nachtrag:
Einige Datenpunktbezeichner bei den Geräten haben hier ein Großbuchstaben im Namen am Anfang.
Wenn ich nur Kleinbuchstaben verwende, kann ich die Reihenfolge wieder bestimmen.
Also z.B.  statt "Status" "status"

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.61` passen.
