### ISSUE TITLE
v3: Reihenfolge bei "DropdownAction" wird nicht richtig angezeigt

### ISSUE THREAD

**Issue by bogaboo** [Zefau/ioBroker.jarvis#923]
Die Reihenfolge im "DropdownAction" stimmt nicht mit der Reihenfolge im Feld "Anzeigevariante (JSON Format)"
überein, es wird eine falsche Sortierung benutzt.

![Bildschirmfoto 2021-08-29 um 12 30 16](https://user-images.githubusercontent.com/48379591/131247265-4398c080-42ab-4655-9f04-22bd0aa5503e.jpg)

So sieht die Anzeige dann aus:

![Bild](https://user-images.githubusercontent.com/48379591/131247268-3c6d688e-d045-43fe-9883-f5a643cabed2.jpg)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.61` passen.

**Comment by bogaboo** [comment]
Alles klar, mit v3.0.0-alpha.61 ist das Problem behoben.
