### ISSUE TITLE
v3: ButtonAction zeigt Text und Button immer an trotz "Zeige Datenpunkt Wert" = true

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#926]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
_Version: 3.0.0-alpha.60, läuft in einer eigenen Test-Umgebung, kopiert von der Produktivumgebung, welche mit JARVIS 2.1.0 läuft_

- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
_Fehlerbeschreibung siehe im Folgenden. Weitere Infos kann ich gerne liefern, müsste nur wissen wie 🙈_

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
_ActionElement = ButtonAction, soll Text anzeigen bei false und Button bei true. In der Button-Config ist "Zeige Datenpunkt Wert" = true (ausgewählt). Leider ist sowohl Text als auch Button immer sichtbar_

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![image](https://user-images.githubusercontent.com/79741077/131657906-1df814ae-1fa7-448b-9a25-d4e69e759780.png)
![image](https://user-images.githubusercontent.com/79741077/131657993-0cfa5a63-33ed-4d79-bb1c-bd4c37f812a3.png)
![image](https://user-images.githubusercontent.com/79741077/131658056-2ae2448b-60b4-4778-b7b5-7235fce402c6.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.61` passen.

**Comment by RkcCorian** [comment]
@Zefau : Grundsätzlich funktioniert es nun. Was etwas verwirrend ist (und ich bin nicht sicher ob das so sein soll), dass bei Wert = false Button Label (an) genommen wird. Sollte das nicht Button Level (aus) sein?
Hinweis: Im folgenden Bild habe ich den Wert bewusst neben dem Button angezeigt, dass ist nicht mehr der Fehler von v60 :-)
![JARVIS_Button](https://user-images.githubusercontent.com/79741077/131772814-9b9757b9-0a6b-49e5-9c54-4a481342e8dc.png)
![JARVIS_Button2](https://user-images.githubusercontent.com/79741077/131772836-f58418be-b39b-4427-aae6-5021e2bf612b.png)

Darüber hinaus, vermutlich aber eher ein Feature-Request: Ich setze den Wohnungsstatus (und andere mehr) auf den Status true, wenn irgendetwas in der Wohnung an ist, was ausgeschaltet werden soll (Nutze die Rollen state, sowie switch.enable). Daher wäre es sinnvoll den Button beim Zustand true anzuzeigen (Ausschalten-Button). Da der Button aber nach Deiner Implementierung immer nur bei false "auftauchen" kann musste ich den Status für die VIS invertieren und jeweils extra ALIAS anlegen. Das geht natürlich, ist halt "nicht schön". Kann man das evtl. ändern oder konfigurierbar machen? (Falls gewünscht stelle ich auch einen eigenen Feature-Request)

**Comment by Zefau** [comment]
Das Label kehre ich nochmal um. Hatte das jetzt geändert weil es mich verwirrt hatte, aber jetzt verwirrt es noch mehr ;-)

Das Verhalten mit umkehren erreichst du mit den Datenpunkt Eigenschaften, wenn du in / off umkehrst.

**Comment by RkcCorian** [comment]
@Zefau : Super!
Umgekehren: Ahhhh, d.h. in den Datenpunkt Eigenschaften kann ich eine Invertierung vornehmen. Das würde helfen. Was muss ich dort genau eintragen? Verstehe "in / off" leider nicht 🙈

**Comment by Zefau** [comment]
Siehe https://zefau.gitbook.io/jarvis-v2/geraete/devices#datenpunkt-eigenschaften

`{ "on": false, "off": true }`

**Comment by RkcCorian** [comment]
@Zefau : Danke, das funktioniert allerdings leider bei meinen boolean DP nicht (bei number geht es) > Soll ich einen eigenen Issue erstellen?
- Konfiguration Datenpunkt Eigenschaften `{ "on": false, "off": true }` bei einem boolean DP
- Reaktion für ButtonAction: v2.1.0 und v3.0.0 alpha 61: Button bleibt immer stehen / ist immer da
- Reaktion für SwitchAction: v2.1.0: Aus JARIVS heraus: Ausschalten einer Lampe geht, aber Einschalten muss 2 mal betätigt werden; Aus ioBroker-Objekteansicht, wenn DP sich ändert, bleibt der Switch in JARIVS "stehen"; v3.0.0 alpha 61: Keine Reaktion an der Lampe, Ein-/Ausschalten findet nicht statt

**Comment by RkcCorian** [comment]
@Zefau : Wie machen wir mit diesem Issue weiter? :-)
- Wichtig ist für mich, dass der Button richtig reagiert, d.h. im Wechsel mit dem Text da ist. Ich habe verstanden mit einer kl. Änderung (Verwendung von "Button Label (aus)") funktioniert das. => Für meine VIS bislang ein Blocker für Umstieg auf v3
- Bzgl. der nicht richtig funktionierenden Invertierung bei boolean-Werten... lässt Du das unter diesem Issue laufen oder soll ich einen neuen aufmachen? => Für meine VIS ein Bug, welcher behoben werden sollte, aber kein Blocker, da ich bislang auch mit zusätzlichen ALIAS gelebt habe, welche mir die Logik umkehrt

**Comment by RkcCorian** [comment]
@Zefau: Hab die Version 67 installiert, Button reagiert korrekt bzgl. Wechsel mit dem Text. LabelAus stimmt jetzt auch.

**Noch offen**: Nicht richtig funktionierende Invertierung bei boolean-Werten bei Button, Switches, (evtl. auch weitere, welche ich nicht getestet habe?) > _Soll ich ein eigenen neuen Issue aufmachen?!_

**Comment by Zefau** [comment]
zeig mal deine Konfiguration der Invertierung bitte

**Comment by RkcCorian** [comment]
@Zefau : Eine Konfig von einem Button:

```
"wohnung_269a9": {
    "name": "Wohnung",
    "icon": "",
    "label": "",
    "function": "other",
    "states": {
      "STATUS_INVERTED": {
        "showState": false,
        "state": "alias.0.Wohnung.Wohnung.STATUS_INVERTED",
        "action": "alias.0.Wohnung.Wohnung.STATUS_COMMAND_INVERTED",
        "actionElement": "ButtonAction",
        "ButtonActionConfig": {
          "showState": true,
          "label": "Ausschalten",
          "icon": "power",
          "pushButton": false,
          "flat": true,
          "labelTurnOff": "Ausschalten",
          "iconTurnOff": "mdi-power",
          "iconTurnOn": "mdi-power",
          "labelTurnOn": "ButtonLabelAn"
        },
        "display": {
          "true": "Alles Aus"
        },
        "iconStyle": {
          "true": {
            "color": "#acacac"
          }
        },
        "icon": {
          "true": "home-outline",
          "false": "home"
        },
        "label": "Status",
        "bodyElement": "LastChangeBody",
        "stateKey": "STATUS_INVERTED",
        "properties": {
          "on": false,
          "off": true
        }
      },
      "ON_NAME": {
        "showState": true,
        "state": "alias.0.Wohnung.Wohnung.ON_NAME",
        "label": "An",
        "icon": "clipboard-list-outline",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "ON_NAME"
      }
    },
    "options": {},
    "attributes": {
      "imported": true,
      "manufacturer": {
        "name": "Alias Devices",
        "namespace": "alias"
      },
      "_created": 1615834523453,
      "_updated": 1618064825421
    },
    "id": "wohnung_269a9"
  }
```

**Comment by Zefau** [comment]
`properties` ist das. Steht drin.

**Comment by RkcCorian** [comment]
@Zefau : Ich brauch Urlaub...

**Comment by Zefau** [comment]
Kannst du nochmal genau beschreiben, was konkret nicht funktioniert und wie die Erwartung ist?

**Comment by RkcCorian** [comment]
Klar...

**Was will ich erreichen**
ALIAS / Gerät: An mehreren Stellen habe ich Geräte angelegt, welche es physikalisch nicht gibt. Es sind "zusammengefasste" Geräte, bspw. für die Beleuchtung, Lautsprecher und eben die gesamte Wohnung. Ich habe Datenpunkte für den Status dieser Geräte (und auch weitere welche mir sagen was genau noch an ist). Der Status für "etwas ist an" ist logisch true.
Visualisierung: Wenn der Status eines solchen Gerätes "alles ist aus" ist, sprich boolean false soll der Text "Alles aus" angezeigt werden. Sobald der Status aber boolean true ist soll der Button erscheinen mit welchem ich alles ausschalten kann.

**Wie habe ich es aktuell gelöst**
Mit Version 2.1.0 (und der aktuelle 3.x-alpha) habe ich das jedoch mit der true/false Logik nicht hinbekommen (mag an meiner Unfähigkeit liegen, keine Ahnung). Jedenfalls habe ich es über zusätzliche <Alias-Name>_INVERTED jeweils invertiert (!val). Dann habe ich meinen Zielzustand erstmal erreicht. Unschön: Ich musste für die Invertierung extra ALIAS anlegen, da der Rest meiner kl. Smart-Home-Welt "richtig" auf true/false Logik reagiert/agiert, u.a. auch Alexa, mit welcher meine Frau und ich damit die gesamte Wohnung ausschalten können.

**Was habe ich auf Basis meiner aktuellen Lösung probiert und erwartet**
In der Datenpunkt-Eigenschaft habe ich "{ "on": false, "off": true }" eingefügt. Damit hatte ich gehofft die Logik zu invertieren, alles andere habe ich erstmal gelassen. Ich hatte jetzt gehofft, dass wenn bislang der Text sicherbar war nun den Button sichtbar wird und wenn der Button sichtbar war nun der Text erscheint, sprich "einfach" invertiert. Das hat allerdings nicht so funktioniert. 
_Evtl. ist mein Test auch falsch / zu einfach gedacht und ich hätte parallel auch die Datenpunkt-Invertierung rausnehmen müssen?_

**Comment by Zefau** [comment]
schau nochmal bitte mit `v3.0.0-alpha.75`. Sollte mit deiner Einstellung nun so auch deiner Erwartungshaltung entsprechen.

**Comment by RkcCorian** [comment]
@Zefau: Mit alpha-76 getested, Verhalten ist grundsätzlich OK. Lediglich die Anzeige stimmt nicht.
Wenn false dann wird der DP Wert grau markiert, vermutlich passiert das automatisch bei false?! Vgl. Screenshot, Wohnung und Wohnungslautsprecher wären korrekt, basieren aber noch auf dem INVERTED, d.h. der Wert ist hier true.
![image](https://user-images.githubusercontent.com/79741077/133202557-27614e16-b506-4760-9a8f-33d66c7d35e9.png)

**Comment by RkcCorian** [comment]
@Zefau : Mit alpha-76 getestet, funktioniert einwandfrei! :-) Muss nur daran denken jetzt die DP Wert Anzeige zu formatieren, war vorher nicht notwendig.
Vielen Dank!

**Comment by Zefau** [comment]
Jo, musst du mit Datenpunkt Stil korrigieren
