### ISSUE TITLE
CSS Classes

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#933]
https://github.com/Zefau/ioBroker.jarvis/discussions/928#discussioncomment-1269530

**Comment by mcuiobroker** [comment]
Vielleicht kannst du #884 berüchsichtigen.

**Comment by RkcCorian** [comment]
Konfigurieren von Widget-/JARVIS-Hintergründen und Transparenteffekten wäre echt super!
Aktuell kenne ich nicht alle "Variablen" (hoffe die werden so bezeichnet) um mehr damit zu machen.

**Comment by Zefau** [comment]
## Page
`.jarvis-page`

## Sidebar
`.jarvis-sidebar-container` (+ `.jarvis-sidebar-minimode`
`.jarvis-sidebar`
`.jarvis-sidebar-items`
`.jarvis-sidebar-item` (`jarvis-sidebar-item-page`, `jarvis-sidebar-item-header`, ``jarvis-sidebar-item-divider``)

## Tabs
`.jarvis-header`
`.jarvis-tabs-container` (+ `.jarvis-tabs-bottom`)
`.jarvis-tabs`
`.jarvis-tab`

## Module / Widget
`.jarvis-module`
`.jarvis-module-[MODULE]`, e.g. `jarvis-module-StateList`

`.jarvis-widget`
`.jarvis-widget-header`
`.jarvis-widget-content`

## Übergreifend
`.jarvis-icon`

**Comment by RkcCorian** [comment]
Gehe alle auch mit der alpha-80 oder erst mit 81 oder 82?

**Comment by RkcCorian** [comment]
Kann man den Header von Widgets von denen der Geräte (für alle Popups) getrennt einstellen?!

**Comment by Zefau** [comment]
Im Pop-up gibt es doch gar keine Header?

**Comment by RkcCorian** [comment]
Ich versuche die Widgets etwas transparent zu machen, die Popups jedoch nicht. Evtl. mache ich es auch falsch, ich habe bislang andere CSS benutzt, blicke es aber vermutlich auch zu wenig. Ich wäre super dankbar, wenn jemand schreiben könnte wie es "richtig" / besser geht!!! 😘
```
.body--dark .q-header {
	background-color: rgba(0,0,0,0.5) !important;
}

.body--dark .bgcolor,
.body--dark .paper .q-dark {
	background: rgba(0,0,0,0.5);
}

.q-card {
	background: rgba(255,255,255,0.5);
}

.body--light .bgcolor,
.body--light .paper .q-light {
	background: rgba(255,255,255,1);
}
```
Führt zu folgendem Ergebnis...
![image](https://user-images.githubusercontent.com/79741077/134811411-94808f7a-d9f4-461b-a7da-d74c62f3c0bc.png)

Bei einem Popup passiert aber leider Folgendes, der Header ist nicht lesbar...
![image](https://user-images.githubusercontent.com/79741077/134811464-c9aa09a2-800c-4919-84fd-8fb95465d66a.png)

**Comment by RkcCorian** [comment]
Ahh, habe .q-card rausgenommen, dann ist es besser. Dennoch... wie müsste ich es "richtig" machen, d.h. am Besten mit den Mitteln die Du oben gepostet hast

**Comment by Zefau** [comment]
Klassen mit `v3.0.0-alpha.82` hinzugefügt.

@RkcCorian So?
```
.body--dark .jarvis-header {
	background-color: rgba(0,0,0,0.5) !important;
}

.body--dark .jarvis-widget {
	background: rgba(0,0,0,0.5);
}

.body--light .jarvis-widget {
	background: rgba(255,255,255,1);
}
```

**Comment by RkcCorian** [comment]
Hab's gerade ausprobiert, das hat mir aber leider JARIVS komplett zurück gesetzt :-( Keine Ahnung wie das passieren kann. Spiele jetzt Backup ein

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1029

**Comment by RkcCorian** [comment]
> Klassen mit `v3.0.0-alpha.82` hinzugefügt.
> 
> @RkcCorian So?
> 
> ```
> .body--dark .jarvis-header {
> 	background-color: rgba(0,0,0,0.5) !important;
> }
> 
> .body--dark .jarvis-widget {
> 	background: rgba(0,0,0,0.5);
> }
> 
> .body--light .jarvis-widget {
> 	background: rgba(255,255,255,1);
> }
> ```

Zum Beispiel. Funktioniert allerdings leider nicht mit alpha-85. Wird nicht transparent...
![image](https://user-images.githubusercontent.com/79741077/135683781-9e3165a5-e49d-4ed0-ad86-13c174571d25.png)

**Comment by RkcCorian** [comment]
Ggü. alpha-80 ist mit alpha-85 das obere Menüband nicht mehr transparent. Geht das auch hier wieder?!

Vgl. mit alpha-80
![image](https://user-images.githubusercontent.com/79741077/135684067-869a1ae5-50fb-4a36-a266-3f3ab51896c0.png)

**Comment by Zefau** [comment]
ab `v3.0.0-alpha.86`:

```
.jarvis-page-container {
	background-image: url(' ... your image ...');
}

.body--dark .jarvis-header {
	background-color: rgba(0,0,0,0.5) !important;
}

.jarvis-tabs-container,
.jarvis-widget-container {
	background-color: transparent !important;
}

.body--dark .jarvis-widget {
	background: rgba(0,0,0,0.5);
}

.body--light .jarvis-widget {
	background: rgba(255,255,255,1);
}
```

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by RkcCorian** [comment]
@Zefau: Header (bzw. Tabs) funktioniert leider immer noch nicht. Rest geht.

```
.jarvis-page-container {
	background-image: url("https://images.hdqwalls.com/download/3d-cgi-geometry-pattern-bo-3840x2160.jpg");
}

.body--dark .jarvis-header {
	background-color: rgba(0,0,0,0.45) !important;
}

.jarvis-tabs-container {
	background-color: rgba(0,0,0,0.45) !important;
}

.jarvis-widget-container {
	background-color: rgba(0,0,0,0.45) !important;
}

.body--dark .jarvis-widget {
	background: rgba(0,0,0,0.45);
}

.body--light .jarvis-widget {
	background: rgba(255,255,255,1);
}
```
![image](https://user-images.githubusercontent.com/79741077/135756579-14c135c8-35cd-46cf-8c11-b0a78424e617.png)

**Comment by Zefau** [comment]
Und mit
```
.jarvis-tabs-container,
.jarvis-widget-container {
	background-color: transparent !important;
}
```

**Comment by RkcCorian** [comment]
Hatte ich zuerst probiert, ging aber leider nicht

**Comment by Zefau** [comment]
Dann müsstest du mal im DOM via Entwickler Tools schauen wo die Farbe bekommt

**Comment by RkcCorian** [comment]
Und wir geht das? 😬

**Comment by RkcCorian** [comment]
Hab gegoogelt und versuche mal mein Glück

**Comment by RkcCorian** [comment]
@Zefau: Hab's gefunden... 
![image](https://user-images.githubusercontent.com/79741077/135760184-b14743bc-8d4c-47ea-8128-617376f59e79.png)

Mit Folgendem geht's
```
.jarvis-page-container {
	background-image: url("https://images.hdqwalls.com/download/3d-cgi-geometry-pattern-bo-3840x2160.jpg");
}

.body--dark .jarvis-header {
	background-color: rgba(0,0,0,0.45) !important;
}

.body--dark .jarvis-tabs-container {
	background-color: rgba(0,0,0,0.45) !important;
}

.jarvis-tabs-container {
	background-color: rgba(0,0,0,0.45) !important;
}

.jarvis-widget-container {
	background-color: rgba(0,0,0,0.45) !important;
}

.body--dark .jarvis-widget {
	background: rgba(0,0,0,0.45);
}

.body--light .jarvis-widget {
	background: rgba(255,255,255,1);
}
```

**Comment by Zefau** [comment]
Dann schließe ich mal
