### ISSUE TITLE
Alarmpanel als Widget

### ISSUE THREAD

**Issue by pphlwmarcel** [Zefau/ioBroker.jarvis#936]
Zur Aktivierung/Deaktivierung der Alarmanlage wäre ein Widget sehr hilfreich (Home Assistant hat das z.B. heute bereits schon).

Wichtig wäre ein Eingabefeld für PIN/Passwort und ggf. eine von der Gerätetastatur unabhängiges Zahlenfeld zur Eingabe.
Ggf mit zwei Buttons zum intern / extern scharf schalten und einer Anzeige ob die Alarmanlage scharf ist oder nicht. 
Im Backend müssten die entsprechenden Datenpunkte einzutragen sein.

z.B. so:
![Alarm Panel Card -](https://user-images.githubusercontent.com/14854093/131849023-a53b4bf8-4ba2-47b8-976e-c1dca89152b0.png)

**Comment by Zefau** [comment]
Duplicate to https://github.com/Zefau/ioBroker.jarvis/issues/262. Please vote there.
