### ISSUE TITLE
State `connected` has no existing object

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#937]
_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/806#issuecomment-911894166_

Mit `v3.0.0-alpha.61` kommt eine Meldung hoch:

<html>
<body>

jarvis.0 | 2021-09-02 18:05:46.927 | warn | (1352) State "jarvis.0.clients.69aeb6e9-5fc9-50a3-ac6b-f3e2c7f1e57b.connected" has no existing object, this might lead to an error in future versions
-- | -- | -- | --

</body>
</html>

In den Objekten stehen nicht die sonstigen Elemente:

![image](https://user-images.githubusercontent.com/84818934/131887493-bc63fa68-5c27-4847-a98d-42a83d50b5fb.png)

Er nutzt auch nicht die schon vorhandenen Einträge zur IP.

Im DP: jarvis.0.clients.connected steht:
{"69aeb6e9-5fc9-50a3-ac6b-f3e2c7f1e57b":{"user-agent":"Mozilla/5.0 (Linux; Android 9; SM-G955F) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.62 Mobile Safari/537.36","ip":"::ffff:192.168.178.58","id":"69aeb6e9-5fc9-50a3-ac6b-f3e2c7f1e57b"}}

Nur im Zusammenhang mit dem Handy: .58 /. 34 PC kommt keine Meldung:
<html>
<body>

jarvis.0 | 2021-09-02 19:05:11.286 | info | (1352) Client with IP ::ffff:192.168.178.58 connected
-- | -- | -- | --
jarvis.0 | 2021-09-02 18:05:46.927 | warn | (1352) State "jarvis.0.clients.69aeb6e9-5fc9-50a3-ac6b-f3e2c7f1e57b.connected" has no existing object, this might lead to an error in future versions
jarvis.0 | 2021-09-02 18:00:54.907 | info | (1352) Client with IP ::ffff:192.168.178.58 connected
jarvis.0 | 2021-09-02 17:49:21.658 | info | (1352) Client with IP ::ffff:192.168.178.34 connected
jarvis.0 | 2021-09-02 16:49:12.066 | info | (1352) Client with IP ::ffff:192.168.178.34 connected

</body>
</html>

**Comment by mcuiobroker** [comment]
Nachdem ich mal alle clients gelöscht habe, kommt die Fehlermeldung auch für alle anderen:
<html>
<body>


jarvis.0 | 2021-09-02 21:02:29.661 | warn | (1352) State "jarvis.0.clients.connected" has no existing object, this might lead to an error in future versions
-- | -- | -- | --
jarvis.0 | 2021-09-02 21:02:29.647 | warn | (1352) State "jarvis.0.clients.7f038168-0f18-5c71-ba6c-edafa8bda689.connected" has no existing object, this might lead to an error in future versions
jarvis.0 | 2021-09-02 21:01:12.969 | warn | (1352) State "jarvis.0.clients.connected" has no existing object, this might lead to an error in future versions
jarvis.0 | 2021-09-02 21:01:12.953 | info | (1352) Client with IP ::ffff:192.168.178.34 connected
jarvis.0 | 2021-09-02 21:01:12.044 | warn | (1352) State "jarvis.0.clients.connected" has no existing object, this might lead to an error in future versions
jarvis.0 | 2021-09-02 21:01:12.031 | warn | (1352) State "jarvis.0.clients.588f342d-fa62-5b28-a6a6-6f77a747b341.connected" has no existing object, this might lead to an error in future versions
jarvis.0 | 2021-09-02 20:26:52.801 | info | (1352) Client with IP ::ffff:192.168.178.34 connected
jarvis.0 | 2021-09-02 20:26:05.666 | warn | (1352) State "jarvis.0.clients.1edfb464-0c2f-5651-88dc-0e33253010a4.connected" has no existing object, this might lead to an error in future versions
jarvis.0 | 2021-09-02 20:23:06.734 | warn | (1352) State "jarvis.0.clients.67e2f13a-569c-57c8-a422-6581b08c4921.connected" has no existing object, this might lead to an error in future versions
jarvis.0 | 2021-09-02 20:23:03.073 | info | (1352) Client with IP ::ffff:192.168.178.58 connected


</body>
</html>

![image](https://user-images.githubusercontent.com/84818934/131901936-b12b4f6a-e309-4f34-80eb-52f7b78a97c7.png)

**Comment by Zefau** [comment]
Objekt sollte eigentlich erstellt werden, wenn es hier vorhanden ist, siehe https://github.com/Zefau/ioBroker.jarvis/blob/master/lib/websocket.io.js#L381

**Comment by MarkSau** [comment]
Hi, Ich bekommen den gleichen Fehler, Mobile und PC, aber erst, wenn ich das Fenster schließe, d.h. die Sitzung beende.
Vielleicht hilft das, ja
Javis V3 Alpha 70

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.75`.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.77`
![image](https://user-images.githubusercontent.com/84818934/133290596-2111c714-d76e-47db-bdf5-6b438ac4dab8.png)

**Comment by Zefau** [comment]
Schau nochmal mit `v3.0.0-alpha.78`. Bitte vorher den `clients` Baum löschen, um aufzuräumen.

**Comment by mcuiobroker** [comment]
Die Elemente sind wieder da.
Die Funktion von connect/disconnect zum Handy wird nicht sauber angezeigt. Mal ja , mal nein?
Obwohl jarvis auf dem Handy geöffnet wird, wird als `connected` : `false` angezeigt.

**Comment by Zefau** [comment]
Dann funktioniert es und ich mach erstmal zu und wir beobachten es?

**Comment by mcuiobroker** [comment]
ok
