### ISSUE TITLE
Slide Effekt deaktivieren

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#939]
_Originally posted by @o0shojo0o in https://github.com/Zefau/ioBroker.jarvis/discussions/922_

> Kann man den Slide Effekt zwischen den Tabs deaktivieren?

**Comment by mcuiobroker** [comment]
War in v2.2.3 nicht vorhanden.

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.62` gibt es nun eine entsprechende Option in den Einstellungen

**Comment by mcuiobroker** [comment]
Danke. Schau ich mir an, wenn sie da ist.

**Comment by mcuiobroker** [comment]
Ja passt.
