### ISSUE TITLE
Fehler Timeout

### ISSUE THREAD

**Issue by ciddi89** [Zefau/ioBroker.jarvis#942]
Hallo,

leider bekomme ich bei v3 immer wieder ein Timeout Fehler und komme garnicht in das Interface von Jarvis. 

Was habe ich schon gemacht? 
- Cache geleert
- ioBroker neu gestertet
- in der Konsole "iobroker upload Jarvis"
- zurück auf v2 funktioniert dann wieder alles.

<img width="1708" alt="Bildschirmfoto 2021-09-03 um 09 33 37" src="https://user-images.githubusercontent.com/66088020/131969396-f4f845fa-41af-4a00-94e4-66f8b4ea12e3.png">

Vielen Dank schonmal

LG

**Comment by Zefau** [comment]
Dein Socket-Port ist falsch. Wie ist die ioBroker.jarvis Adapter-Einstellung? Hast du die Verbindungseinstellung auf `auto`?

**Comment by ciddi89** [comment]
> Dein Socket-Port ist falsch. Wie ist die ioBroker.jarvis Adapter-Einstellung? Hast du die Verbindungseinstellung auf `auto`?

Ja steht alles auf Auto. Siehe Screenshot 
<img width="755" alt="Bildschirmfoto 2021-09-03 um 10 29 53" src="https://user-images.githubusercontent.com/66088020/131975551-7902e964-e063-47c4-a9dc-19890e810229.png">

**Comment by ciddi89** [comment]
Anstatt des 404 not found Fehlers bekomme ich nun das in der Browser Konsole ausgegeben wenn ich die Seite Aktualisiere:
<img width="696" alt="Bildschirmfoto 2021-09-03 um 10 34 02" src="https://user-images.githubusercontent.com/66088020/131976120-21da13ac-f2b0-46b1-8ef7-37b4bdd7481e.png">

**Comment by Zefau** [comment]
Dann trag mal `iobroker` in die Whitelist ein (in den Adapter-Einstellungen; rechts neben Eingabefeldern, die auf deinem Screenshot zu sehen sind).

**Comment by ciddi89** [comment]
Wow das war's!  Vielen Dank für die schnelle Hilfe! 🤩 Habe zur Sicherheit neben dem Hostnamen auch die ip Adresse eingegeben. Nun läuft es bei beiden. 👍🏻
