### ISSUE TITLE
Versionsnummer neben Konfiguration

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#944]
Versionsnummernanzeige neben das Wort "Konfiguration", somit kann man direkt erkennen mit welcher Version man arbeitet.

![image](https://user-images.githubusercontent.com/84818934/132052602-fe85b7fe-4cb5-406e-9f85-59d05030d886.png)

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.62` integriert

**Comment by mcuiobroker** [comment]
`.64`?

**Comment by Zefau** [comment]
Jo, stimmt, schon zu spät ;-)

**Comment by mcuiobroker** [comment]
Leider nicht ganz: `v3.0.0-alpha.65`
![image](https://user-images.githubusercontent.com/84818934/132142777-f8eed244-9c34-4943-b1c1-5c1805abc9af.png)

**Comment by mcuiobroker** [comment]
Kein Layout mehr in `v3.0.0-alpha.65`:
![image](https://user-images.githubusercontent.com/84818934/132143878-79f4dd2d-c851-4d26-9a22-3f95a3ed090d.png)

**Comment by mcuiobroker** [comment]
Daten im Popup ausblenden?? Früher gab es doch im Gerät ein Punkt im Popup nicht anzeigen:
![image](https://user-images.githubusercontent.com/84818934/132143936-95588a78-beca-407e-b5b1-cda11d98caf2.png)

![image](https://user-images.githubusercontent.com/84818934/132143921-72a8e4de-7c5f-489e-ab7f-88188495b202.png)

**Comment by mcuiobroker** [comment]
Wenn der Datenpunkt-Wert anzeigen an ist, dann wird der Wert im Popup angezeigt. Das scheint das Problem zu sein.
![image](https://user-images.githubusercontent.com/84818934/132144020-64b44f79-a444-42a5-878a-19c2b5537935.png)

**Comment by mcuiobroker** [comment]
Mit den vorherigen Version war dieser immer mit der Konvertierung auf "on". Deswegen ist es auch nicht sofort aufgefallen.

**Comment by mcuiobroker** [comment]
Hide popup ist verruscht als Geräteoption?
![image](https://user-images.githubusercontent.com/84818934/132145977-54dacdda-3dec-4cf9-9f57-8a4ca6a96260.png)

**Comment by Zefau** [comment]
> Kein Layout mehr in v3.0.0-alpha.65:
image

Fehler in der Browser Konsole?

**Comment by Zefau** [comment]
> Daten im Popup ausblenden?? Früher gab es doch im Gerät ein Punkt im Popup nicht anzeigen:

Hab ich in v3 vergessen und ist nun drin.

> Wenn der Datenpunkt-Wert anzeigen an ist, dann wird der Wert im Popup angezeigt. Das scheint das Problem zu sein.

`showState` ist nun mit der Konvertierung im Standard an - außer es ist ein ActionElement ausgewählt.

Ansonsten ist das Verhalten korrekt, dass der Wert komplett ausgeblendet werden kann.

> Hide popup ist verruscht als Geräteoption? War sonst zu jedem Datenpunkt.

Ist im Gerät korrekt. Das ist die Option um das komplette Popup zu deaktivieren.

**Comment by Zefau** [comment]
implemented with `v3.0.0-alpha.66`.

**Comment by mcuiobroker** [comment]
Versionsnummer passt.
