### ISSUE TITLE
v3 - Widget DisplayImage keine Möglichkeit Link einzufügen 

### ISSUE THREAD

**Issue by ciddi89** [Zefau/ioBroker.jarvis#945]
Hallo Zefau,

in v3 beim Widget DisplayImage gibt es keine Möglichkeiten mehr einen Link oder base64-Wert einzufügen. Man kann nur Module Devices angeben und dort habe ich noch keine Möglichkeiten entdeckt ein Bild mit einzufügen. Oder habe ich was übersehen? Anbei ein Screenshot.

Vielen Dank und liebe Grüße

<img width="1397" alt="Bildschirmfoto 2021-09-04 um 12 23 20" src="https://user-images.githubusercontent.com/66088020/132091325-c4aba503-a964-47b4-988e-7771f0ce9374.png">

**Comment by mcuiobroker** [comment]
Du kannst ja einen DP in iobroker anlegen und den entsprechend in jarvis zuordnen. Aber ich hoffe, dass dies wieder, wie in v2, auch per Link möglich sein wird.

**Comment by ciddi89** [comment]
> Du kannst ja einen DP in iobroker anlegen und den entsprechend in jarvis zuordnen. Aber ich hoffe, dass dies wieder, wie in v2, auch per Link möglich sein wird.

Ah soweit habe ich garnicht gedacht. 🤦🏼‍♂️ Hat auf Anhieb funktioniert. Danke für den Hinweis. 😊

**Comment by Zefau** [comment]
Link option has been re-introduced with `v3.0.0-alpha.79`.

**Comment by mcuiobroker** [comment]
Funktioniert.
