### ISSUE TITLE
v3: JSON Editor öffnet sich im Standard falsch

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#947]
`v3.0.0-alpha.65`
Der JSON Editor hat nur "" drin, sollte aber {"":""} drin haben.
{
"":""  
}
Direkt ein richtiges Beispiel eintragen.
![image](https://user-images.githubusercontent.com/84818934/132144816-299f16eb-f626-41b9-ab0b-6892ac8ef179.png)

**Comment by Zefau** [comment]
Wieso das? Das wäre kein valides JSON und falsch.

**Comment by mcuiobroker** [comment]
v2:
![image](https://user-images.githubusercontent.com/84818934/132200039-ce186e4f-243a-43c3-a749-fad74cf46980.png)

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.68`.

**Comment by mcuiobroker** [comment]
Ja Passt. Wie gesagt: Eine Hilfe direkt im Editor wäre gut, mit Beispielen usw.

**Comment by Zefau** [comment]
Ich könnte auf das Wiki verlinken und dort sammeln wir? Oder denkst du an das bestimmtes?
