### ISSUE TITLE
v3: Layout keine Anzeige

### ISSUE THREAD

**Issue by sigi2345** [Zefau/ioBroker.jarvis#950]
### Discussed in https://github.com/Zefau/ioBroker.jarvis/discussions/949

<div type='discussions-op-text'>

<sup>Originally posted by **sigi2345** September  6, 2021</sup>
Hallo,

nach einen update auf 3.0.65 ist das Layout weg?

![Screenshot (4264)_LI](https://user-images.githubusercontent.com/41079106/132170145-a10d083d-2e32-4492-9779-4d8fbc8185b0.jpg)
</div>

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.66`.

**Comment by sigi2345** [comment]
> fixed with `v3.0.0-alpha.66`.

Danke, works.
