### ISSUE TITLE
Weather widget API language

### ISSUE THREAD

**Issue by xachopin** [Zefau/ioBroker.jarvis#951]
Hi,
I see in the weather API that we can set language.
Could it be possible to add this possibility to the widget, so we can choose other language that German?
![image](https://user-images.githubusercontent.com/90180715/132183782-a6374043-63ad-4563-9244-bd16811bb5b5.png)

**Comment by Zefau** [comment]
I can inherit the language settings from jarvis here.

**Comment by Zefau** [comment]
Seems like this does not affect the unit (e.g. `km/h` for wind) ?

**Comment by Zefau** [comment]
please check with `v3.0.0-alpha.66` and let me know if something is not or incorrectly translated. Might not be caused by the URL parameter.

**Comment by xachopin** [comment]
It works fine with v3.0.0-alpha.66, but there is a small bug when a click on a day to see the full forecast: the name of the window is on the left instead of being on the top.

![image](https://user-images.githubusercontent.com/90180715/132256158-2994be8a-6804-419f-9c4a-f9cd541dcc06.png)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.69`.

**Comment by xachopin** [comment]
> schau nochmal mit `v3.0.0-alpha.69`.

It works! Thanks for the fast response!
