### ISSUE TITLE
v3: Konvertierung v2 -> v3

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#952]
Ich mach mal einen eigenen Punkt:
Mit `v3.0.0-alpha.66` kommt ein Konsolenfehler hoch:
![image](https://user-images.githubusercontent.com/84818934/132197162-91700fc6-bbaf-4bcd-87cb-7d3aca2ec085.png)

![image](https://user-images.githubusercontent.com/84818934/132197300-165ddaa6-1d05-4392-8ecf-7068f9486478.png)
Bleibt mit timeout stehen.
![image](https://user-images.githubusercontent.com/84818934/132197433-f23f132e-70f1-43ca-b417-7d7b1ec5a78d.png)

![image](https://user-images.githubusercontent.com/84818934/132197963-595443b3-d440-41c6-9950-c24df3860723.png)

**Comment by Zefau** [comment]
probier nochmal mit `v3.0.0-alpha.67`.

**Comment by mcuiobroker** [comment]
Habe versucht einen commit  zu installieren (.65) mit:
https://github.com/Zefau/ioBroker.jarvis.git#5410541f02ddfcd83d74f163eff243afcffff9b6
Das funktioniert nicht.

**Comment by mcuiobroker** [comment]
Passt mit `v3.0.0-alpha.67` wieder.

**Comment by mcuiobroker** [comment]
Hab jetzt die "neue" Option Settings auf off gestellt, wie kommt man jetzt wieder an die Settings?

**Comment by Zefau** [comment]
URL manuell aufrufen: `.../#/configuration`

**Comment by mcuiobroker** [comment]
Klappt. Danke.

**Comment by mcuiobroker** [comment]
Vielleicht sollte man diesen Hinweis dann noch bestätigen lassen, damit man weiß, das man gerade die Möglichkeit wegnimmt, auf die Einstellungen über das Menü zuzugreifen. Hinweis "configuration nur noch über ..../#/configuration" möglich oder so.
