### ISSUE TITLE
v3: Fehlende Objekte auf Handyansicht

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#953]
#805 
Damit es nicht vergessen wird, lieber als Einzelpunkt.
HomeKitTile Element werden nicht angezeigt. Sie blinken kurz auf (oder werden gesucht , laufendes blaues Band) und sind dann weg.
Dann sind alle Elemente auf der Seite weg. (`v3.0.0-alpha.67`)
Zusammenhang ist nicht nur in den HomeKiTile zu sehen. Auch auf anderen Seiten, wo diese Elemente nicht vorkommen, fehlen die Objekte (Statewert, Schalter usw), Label wird agezeigt.
![image](https://user-images.githubusercontent.com/84818934/132219671-d14647e3-e903-4c99-8ca3-20b55b2c1874.png)
![image](https://user-images.githubusercontent.com/84818934/132219698-4f22e811-5754-431f-9330-57369e71abf9.png)

**Comment by mcuiobroker** [comment]
Damit du einen Eindruck bekommst:

https://user-images.githubusercontent.com/84818934/132256101-b6b57829-4ec6-4814-ad7b-d89bb856814d.mp4

**Comment by Zefau** [comment]
besteht das Problem mit `v3.0.0-alpha.79` noch?

**Comment by mcuiobroker** [comment]
Ja auch mit `v3.0.0-alpha.79`bleibt das Problem bestehen.

**Comment by Zefau** [comment]
Hast du Fehler oder Warnings im Log, die hiermit verbunden sein könnten?

**Comment by Zefau** [comment]
Und hast du das mit allen Browsern oder ist das ein Chrome-Problem?

**Comment by mcuiobroker** [comment]
Auf dem Handy, gibt es keine F12-Möglichkeit.
Im Hochformat gibt es das Problem. Im Querformat wird was angezeigt. Bilder kommen gleich.

**Comment by Zefau** [comment]
Jo, auf dem Handy gibt es keine Konsole. Das ist echt mist. Muss ich direkt in jarvis einbauen.

**Comment by mcuiobroker** [comment]
Welche Breite wird denn bei Homekittile verwendet, da scheint es ein Problem zu geben?
Im Hochformat scheint die Gesamtbreite für das Element (Homekittile) zu breit zu sein?

**Comment by mcuiobroker** [comment]
Wie im Bild zu sehen ist, ist zwar eine "width" von 33.4167 vorgegeben, sie wird aber nicht berücksichtigt.
![image](https://user-images.githubusercontent.com/84818934/133868134-4d329510-b1e9-4a8f-9ef4-c4913cc80927.png)

**Comment by mcuiobroker** [comment]
Passt mit `v3.0.0-alpha.88`.
Neues Problem ist, dass man auf dem Handy die jsonTable nicht verschieben kann, wenn der Inhalt breiter ist als angezeigt. Dazu mach ich aber ein neues Issue auf.
