### ISSUE TITLE
v3: dense Tab

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#954]
- [x] Objektwert wird nicht geändert, wenn man in den Einstellungen Dense Tabs umschaltet

![image](https://user-images.githubusercontent.com/84818934/132222273-ade4f81b-2fb3-4f76-88cd-fb77600854c0.png)

![image](https://user-images.githubusercontent.com/84818934/132221878-5e2e399f-be0c-486f-b166-a93ac5ed48a6.png)

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.68`.

**Comment by mcuiobroker** [comment]
erledigt
