### ISSUE TITLE
v3: collapse Tabs

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#955]
#803 wurde teilweise schon umgesetzt.
Problem ist noch:
Stellt man collapse TABs auf true, so wird diese erst nach Refresh der Seite umgesetzt oder, wenn man auf einen anderen TAB klickt/drückt. (Wenn die Seite parallel zur Umstellung z.B. auf dem Handy geöffnet ist)

- [x] Neuer Vorfall collapseTabs auf false gestellt -> "more" wid augeblendet und steht nicht mehr zur Verfügung. Kann nicht sofort nachgestellt werden.

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.68`.

**Comment by mcuiobroker** [comment]
Die Handyseite bleibt unverändert, bei Änderung auf dem PC für collapseTABs.
collapse auf false gestellt -> Handyseite weiterhin mit (collapseTab:true) dargestellt.
Klicke ich auf dem Handy dann einen anderen Tab ist 'more' weg. Trotzdem keine Änderung bzgl collapseTabs:false.

**Comment by mcuiobroker** [comment]
Hat sich auch erledigt mit `v3.0.0-alpha.70` mit einem kleinen negativen Effekt.
Da hätte noch ein TAB mehr gepasst, war auf jeden Fall vorher so:
![image](https://user-images.githubusercontent.com/84818934/132260395-0035e8f2-f4ea-48b0-8479-e6239789c23c.png)

**Comment by Zefau** [comment]
Ich hab's angehoben weil es die Glocke überlagert, aber ich kann nochmal reduzieren und mit den Wert spielen.

**Comment by mcuiobroker** [comment]
Fällt mir gerade auf, müsste bei More das Icon nicht auch über dem "more" sein?

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.75` habe ich den Wert wieder etwas reduziert und den `More`-Button optisch an die anderen Tabs angepasst.

**Comment by mcuiobroker** [comment]
Wenn man einen "Pfeil nach unten" in der Größe der Glocke macht hat man viel Platz gespart?
.76
![image](https://user-images.githubusercontent.com/84818934/133167473-42573423-4d4d-438d-82ed-ed7f8a7d7218.png)
