### ISSUE TITLE
v3: dense-mode ausgeschaltet -> Icon und Label überlappen erste Widget-Zeile

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#956]
mit `v3.0.0-alpha.63`wird wenn man den dense-mode ausgeschaltet -> Icon und Label übereinander die erste Widget-Zeile verdeckt:
![image](https://user-images.githubusercontent.com/84818934/132140929-88852f7a-dd8e-4883-bd6f-d2e8d5fbada7.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/805#issuecomment-913224940_

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.68`.

**Comment by mcuiobroker** [comment]
Die TABs überlappen zwar nicht mehr die oberste Widgetzeile. Aber die obersten Widgets werden verkleinert.
Alle Widgets sollten eigentlich dadurch (dense:false) nach unten verschoben werden und nicht verkleinert.

**Comment by mcuiobroker** [comment]
Ist mit `v3.0.0-alpha.70` auch erledigt.
