### ISSUE TITLE
v3: collapse Tabs ausgeschaltet -> rechts keine Glocke

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#957]
`v3.0.0-alpha.63`
collapse Tabs ausgeschaltet
![image](https://user-images.githubusercontent.com/84818934/132141022-47353fad-60bd-4011-8286-634e0393df8f.png)
-> bei mehreren Tabs erscheint auf dem Handy rechts keine Glocke mehr direkt, erst wenn man ganz nach rechts wischt kommt auch die Glocke. Diese sollte aber immer zu sehen sein?

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/805#issuecomment-913225292_

**Comment by Zefau** [comment]
should be resolved with `v3.0.0-alpha.68`.

**Comment by mcuiobroker** [comment]
Glocke ist wieder da. Passt. Danke.
