### ISSUE TITLE
v3: Verkleinerung der Seitenbreite  PC-> Sprung von 3 Spalten auf 1

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#958]
Aufgefallen: Bei Verkleinerung der Breite auf dem PC: Aus 3 Spalten werden direkt 1. Es verschwinden in der Reihe die Widgets.
![v3-alpha61-Verkleinerung direkt von 3 auf 1 Spalten](https://user-images.githubusercontent.com/84818934/131902505-b325a67b-788a-4444-9925-a575e650e520.gif)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/805#issuecomment-911977695_

**Comment by Zefau** [comment]
Hast du das bei jedem Tab? Ich vermute das passiert, weil die Inhalte eines Widgets sehr viel Breite beanspruchen. Also eher ein Feature und kein Bug. ;-)

**Comment by mcuiobroker** [comment]
Also es lief ja in v2.

**Comment by Zefau** [comment]
Das beantwortet die Frage nicht ;-)
V3 funktioniert mit den Grid System ganz anders und ist nicht mehr vergleichbar zu v2

**Comment by mcuiobroker** [comment]
Also Nicht bei allen. 
Grundsätzlich hat sich die Sortierreihenfolge geändert.
v2: Alle Widget die in der 1. Spalte sind, werden auf dem Handy untereinander dargestellt und erst danach kommen die 2. Spalte usw.
v3: Die Widgets, die in der 1 Reihe stehen, werden auf dem Handy untereinander dargestellt.

Ein anderer TAB mit Verkleinerung:
![v3-alpha67 - Sortierreihenfolge bei Verkleinerung Widget verschwinden](https://user-images.githubusercontent.com/84818934/132250384-214b50a3-ef14-4894-a89e-6e57462804d3.gif)

**Comment by Zefau** [comment]
> Er vergibt ja dem Widget auf dem Layout eine Nummer.
So wie es aussieht wird diese mit bei der Sortierung der Widget-Elemente im Grid genutzt.

Korrekt. Das ist die Grundlage für die Sortierung beim Reponsive Layout. Das wird auch noch editierbar sein irgendwann.
