### ISSUE TITLE
v3: Lange Suchzeit der Icon bei fehlendem DP

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#959]
Die Suchzeit für einen DP beträge anscheinend 1 Minute.
Solange wird das Icon, welches dem Gerät zugeordnet ist  als drehender Viertelkreis angezeigt.
Sollte man das nicht auf, 5 Sekunde reduzieren, wenn alle anderen DP direkt geladen werden konnten?
Bei langsamen Verbindungen kann ich mir das vorstellen, aber 1 Minute?
Nach 1 Minute wird das korrekte Icon im Layout normal angezeigt. Der DP ist nicht vorhanden. (hier: Testsystem)
Ist es da nicht besser direkt ein Icon (besonderes) anzuzeigen, welches besagt, DP fehlt und dann direkt mit der Suche aufzuhören?

**Comment by Zefau** [comment]
same as https://github.com/Zefau/ioBroker.jarvis/issues/1003 ?

**Comment by mcuiobroker** [comment]
Nein. Hier liegt an einem nicht vorhandenen DP.
Hier ist der timeout anscheinend bei 60 Sekunden.

**Comment by Zefau** [comment]
ah ok, der DP existiert nicht. Steht ja auch oben; hab ich überlesen.

**Comment by Zefau** [comment]
I reduce the time for `getState` to 5s and for `getHistory` to 20s

**Comment by Zefau** [comment]
Time reduced with `v3.0.0-alpha.80`.

**Comment by mcuiobroker** [comment]
Zeit muss wohl etwas höher sein: Es kommen wieder die HomeKittile-Fehler:
![image](https://user-images.githubusercontent.com/84818934/133832611-5d8dec19-4926-4157-a19e-e19a26fd3f97.png)
Ausserdem hat man den Eindruck das der Anfang mit dem Aufbau der Connection immer länger dauert.

**Comment by Zefau** [comment]
Schau mal bitte mit v3.0.0-alpha.81. Habe nun die gesamte Architektur nochmal umgebaut. Es sollte nun wesentlich schneller sein.

Dadurch, dass ich so extrem viel anpassen musste, kann es sein, dass es im Zusammenhang mit der Anzeige oder dem Schalten von States zu (neuen) Fehlern kommt.

**Comment by mcuiobroker** [comment]
`getState`-Wert scheint jetzt auf unendlich zu stehen. Er dreht jedenfalls ohne Ende. Vielleicht ist es bei fehlendem DP ja auch sinnvoll. Besser wäre ein STOP-Schild oder sowas und nicht dauernd das drehende Element.

**Comment by RkcCorian** [comment]
@Zefau : INFO: Nachdem ich bei mir 2 fehlende DPs erkennen und aufräumen konnte (@mcuiobroker : vielen Dank!!!!!) hat sich die Ladezeit drastisch reduziert (alpha-80). Ist aber vermutlich keine Überraschung wenn ich den Verlauf lesen. :-)

**Comment by Zefau** [comment]
Fehlende DPs werden mit `v3.0.0-alpha.86` nun im Log angezeigt. Die Ladezeit für fehlende DPs ist deutlich reduziert. Eine Fehlermeldung erscheint in der Browser-Konsole.

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.86` nun passen

**Comment by mcuiobroker** [comment]
Bzgl der DP Kontrolle habe ich ein eigenes Issue geöffnet, somit würde ich das hier erstmal schließen.
