### ISSUE TITLE
v3: Falsche Einheit im Popup

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#960]
bri hat die Einheit %
![image](https://user-images.githubusercontent.com/84818934/132261065-339eb956-460b-4b33-9862-8e2ee9138773.png)

![image](https://user-images.githubusercontent.com/84818934/132261121-52e3f9b8-c4f2-474e-9436-5dce66146293.png)
Dort wird ° angezeigt. Dort wird der lightColorState angezeigt.

**Comment by Zefau** [comment]
Kannst du die ganze Geräte Konfiguration (JSON) rein kopieren?

**Comment by mcuiobroker** [comment]
`"5210cf66-e17e-4353-bd77-aeced4dc1d94_3e95f": {
    "name": "Küche oben",
    "icon": "led-strip",
    "label": "",
    "function": "light",
    "states": {
      "LichtAn": {
        "showState": false,
        "state": "javascript.0.HAUS.LICHT.OBEN.LICHT_AN",
        "action": "javascript.0.HAUS.LICHT.OBEN.LICHT_AN",
        "actionElement": "SwitchAction",
        "label": "",
        "iconStyle": {
          "true": {
            "color": "yellow"
          }
        },
        "bodyElement": "LastChangeBody",
        "stateKey": "LichtAn"
      },
      "Dauerhaft_An": {
        "showState": false,
        "state": "javascript.0.HAUS.LICHT.OBEN.LICHT_DAUERHAFT_AN",
        "action": "javascript.0.HAUS.LICHT.OBEN.LICHT_DAUERHAFT_AN",
        "actionElement": "SwitchAction",
        "unit": "(permanent)",
        "label": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "Dauerhaft_An"
      },
      "RestSekunden": {
        "showState": true,
        "state": "javascript.0.HAUS.LICHT.OBEN.COUNTDOWN_REST_SEKUNDEN",
        "action": "",
        "bodyElement": null,
        "label": "",
        "unit": "Sek.",
        "display": {
          "0": ""
        },
        "stateKey": "RestSekunden"
      },
      "reachable": {
        "showState": true,
        "state": "wifilight.0.192_168_178_32.reachable",
        "unit": "(reachable)",
        "label": "",
        "action": "",
        "bodyElement": "LastChangeBody",
        "stateKey": "reachable"
      },
      "bri": {
        "showState": false,
        "state": "wifilight.0.192_168_178_32.bri",
        "action": "wifilight.0.192_168_178_32.bri",
        "bodyElement": "LevelBody",
        "actionElement": "LightColorState",
        "label": "",
        "unit": "%",
        "stateKey": "bri",
        "LevelBodyConfig": {
          "step": "10"
        }
      },
      "on": {
        "showState": true,
        "state": "wifilight.0.192_168_178_32.on",
        "action": "wifilight.0.192_168_178_32.on",
        "icon": {
          "default": "led-strip"
        },
        "unit": "(on)",
        "label": "",
        "iconStyle": {
          "true": {
            "color": "yellow"
          }
        },
        "bodyElement": "LastChangeBody",
        "stateKey": "on"
      }
    },
    "options": {},
    "attributes": {
      "_created": 1608768491742,
      "_updated": 1625353267597
    },
    "id": "5210cf66-e17e-4353-bd77-aeced4dc1d94_3e95f"
  },`

**Comment by Zefau** [comment]
`LightColorState` als `actionElement` ist inkorrekt, da dein Datenpunkt keine Farbe ist. jarvis versucht zu ermitteln was für eine Farb-Art es ist (RGB, hex oder hue), um es entsprechend darzustellen. Bei hue wird `°` hinzugefügt. Der Wert `100` wird als hue erkannt:

```
	// hex
	if (typeof color === 'string' && color.indexOf(',') === -1 && (color.length === 6 || (color.length === 7 && color.startsWith('#')))) {
		return color.startsWith('#') ? '#hex' : 'hex';
	}
	
	// hexa
	else if (typeof color === 'string' && color.indexOf(',') === -1 && (color.length === 8 || (color.length === 9 && color.startsWith('#')))) {
		return color.startsWith('#') ? '#hexa' : 'hexa';
	}
	
	// hue
	else if ((typeof color === 'string' && color.indexOf(',') === -1 && color.length <= 3) || (typeof color === 'number' && color <= 360 && color.toString().length <= 3)) {
		return 'hue';
	}
	
	// rgb or hex
	if (!Array.isArray(color) && typeof color === 'string') {
		color = color.split(',');
	}
	
	// hsv
	if (color[0] > 255) {
		return 'hsv';
	}
	
	// rgb (respectively fallback)
	return 'rgb';
```

**Comment by mcuiobroker** [comment]
Stimmt.
![image](https://user-images.githubusercontent.com/84818934/133164180-0e3a36c3-3a00-44d5-8cd0-3df5ba4537f2.png)
