### ISSUE TITLE
v3: Bei Iconstate in Gerätedefinition fehlt ein Icon / Schaubild

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#961]
`v3.0.0-alpha.70` war vorher auch so
![image](https://user-images.githubusercontent.com/84818934/132261811-7102da4f-f6f1-4b72-a2c9-6d1e6e12803d.png)
Bei den anderen ist eins da.

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.78`.

**Comment by mcuiobroker** [comment]
Passt mit `v3.0.0-alpha.78`.
