### ISSUE TITLE
v3: Falsche Anzeige der Version

### ISSUE THREAD

**Issue by Bernd9000** [Zefau/ioBroker.jarvis#962]
Installiert : 3.0.0-alpha.70
In der Konfiguration wird eine falsche Version angezeigt.

![1](https://user-images.githubusercontent.com/77005685/132263463-a72f7eb0-ed4c-46b9-83b4-8b6888bb415d.jpg)

**Comment by Zefau** [comment]
Was steht für eine Version in der Browser Konsole? Kannst du die Änderungen von 70 nachvollziehen? Ansonsten musst du Cache leeren vermute ich.

**Comment by Bernd9000** [comment]
Hab erst auch gedacht das es am Browsercache liegt, aber nach dem löschen ändert sich nichts.

Browserkonsole:
![1](https://user-images.githubusercontent.com/77005685/132301874-24209b0f-bf26-4505-b423-905d16b9d3cb.jpg)


In der io-package.json steht:
`{
  "common": {
    "name": "jarvis",
    "version": "3.0.0-alpha.70",`

**Comment by Zefau** [comment]
Du bist im Quellcode. Die Browser-Konsole kannst du mittels F12 öffnen:

![image](https://user-images.githubusercontent.com/14368811/132310227-e39bdeeb-edfe-4065-ae3d-2d9fd0ce7b4c.png)

**Comment by Bernd9000** [comment]
Stimmt. zweiter Versuch :-)
![1](https://user-images.githubusercontent.com/77005685/132358787-9225c9df-b339-4e6b-bbab-6d98986c4ae4.jpg)

**Comment by Bernd9000** [comment]
Ich hab ioBroker komplett neu gestartet, jetzt wird die richtige Version angezeigt.
Hat sich erledigt.
