### ISSUE TITLE
v3: Bei Konvertierung wird CSS-Struktur minimiert

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#966]
Obwohl die CSS-Werte im Editor struktiert standen wird durch die Konvertierung oder anderes diese zerstört:
![image](https://user-images.githubusercontent.com/84818934/131737373-582c4b84-fa06-4242-94a3-70ea0c568c92.png)

_Originally posted by @mcuiobroker in https://github.com/Zefau/ioBroker.jarvis/issues/836#issuecomment-910675105_

**Comment by Zefau** [comment]
Kannst du das als Text posten, damit ich damit etwas experimentieren kann?

**Comment by mcuiobroker** [comment]
`/* .jss253{   background-color:lightblue; } */ /* .MuiButtonGroup-root{   transform: scale(1.5); }   .jarvis-Tab-home {  background-color: blue; }  .jarvis-Tab-home span svg{  color: black; }    .jarvis-Tab-bad {  background-color: lightblue; } .jarvis-Tab-flur {  background-color: orange; } .jarvis-Tab-büro {  background-color: lightgreen; }  .jarvis-Tab-küche {  background-color: #ff00ff; } */  .bubbles {animation: bubble 2s infinite;}   @keyframes bubble {     0%   { transform:scale(0.2); opacity:1.0; }     50%  { transform:scale(2.0); opacity:1.0; }     100% { transform:scale(1.0); opacity:1.0; } }   /* // Wenn man den thumb nur einfarbig haben möchte, unabhängig vom Zustand .MuiIconButton-label .MuiSwitch-thumb  {   background-color: yellow;   color:yellow;   outline:dotted white;   height: 15px;   width: 15px; } */  /* // Alle Popup's inkl. Der Konfiguration bekommen dieses CSS-Styles [role='presentation'] .MuiInput-input {   background-color: yellow;   color:black;    } */ iframe:hover {   outline: dotted white; }  .blink  {    animation: blinker 3s linear infinite; }  @keyframes blinker  {   50% {opacity: 0;} }   .blink5  {    animation: blinker5 5s linear infinite; }  @keyframes blinker5  {   50% {opacity: 0.5;} }   #nurdies {background-color: blue}  .MuiTab-wrapper:hover {    background-color: #00ff00;      color: black;   // font-size: 80%;   font-weight:bold;   outline: dotted white; }  [aria-selected = 'true'] [role='img']  {      background-color: #00ff00;   color: black; }  [aria-selected = 'true']  {    background-color: #00ff00;   color: black; }  .MuiTab-wrapper:active {      background-color: #00ff00; }  /*  // Damit kann man den Schalter einfarbig in allen Zuständen (false,true) gestalten .MuiSwitch-thumb  {   background-color:yellow;   color:yellow; } */  @keyframes mymove {   from {background-color: red;}   to {background-color: blue;} }  @keyframes mymovecol {   from {color: red;}   to {color: blue;} }  .rotated {  transform: rotate(45deg); /* Equal to rotateZ(45deg) */  background-color: pink;}  .glowRed {animation: glow_red 2s ease-in-out infinite alternate;}  @-webkit-keyframes glow_red  {   from {text-shadow: 0 0 10px #fff, 0 0 11px #fff, 0 0 12px #000073;}       to {text-shadow: 0 0 12px #ff0000, 0 0 13px #ff4da6, 0 0 14px #ff4da6;} }  .background-test  {   display: inline-block;   width: 1em;   height: 1em;   vertical-align: -0.125em;   background: url('https://api.iconify.design/bi/bell-fill.svg') no-repeat center center / contain; }  .alarm  {   display:inline-block;   width: 1.5em;   height: 1.5em;   vertical-align: -0.125em;   background: url('https://api.iconify.design/mdi:shield-home.svg?color=blue') no-repeat center center / contain; }  .bubbles  {   animation: bubble 2s infinite; }  @keyframes bubble {0%   { transform:scale(0.2); opacity:1.0; }                    50%  { transform:scale(2.0); opacity:1.0; }                    100% { transform:scale(1.0); opacity:1.0; }                     }  .rainbow-text  {    background: linear-gradient(55deg,#FFD33D 0,#FB8532 16.02%,#EA4A5A 28.06%,#8A63D2 56.92%,#2188FF 72.93%,#34D058 84%,#FFD33D 100%);   background-size: auto;   background-clip: border-box;   background-clip: text;   display: inline-block;   color: transparent;   text-fill-color: transparent;   -webkit-background-clip: text;   -webkit-text-fill-color: transparent;   animation: shine 1.5s alternate infinite;   animation-duration: 4s;   background-size: 200%; }  @keyframes shine { 0% {  background-position:200% center }                   50% {  background-position:100% center }                  100% {  background-position:200% center }                  }     .impuls  {    animation: schatten-puls 1s infinite; }  @keyframes schatten-puls {  0% {    box-shadow: 0 0 0 0px rgba(255, 255, 0, 0.9); }                           100% {    box-shadow: 0 0 0 10px rgba(255, 255, 0, 0);  }                          }  .contai {   width:auto;   display:flex;   jusitfy-content: center;   align-items:center;   -moz-hyphens: auto;   -o-hyphens: auto;   -webkit-hyphens: auto;   -ms-hyphens: auto;   hyphens: auto; }  .card  {   position: relative;   width: auto;   height: 25px;   display:flex;   justify-content: center;   align-items: center;   margin: 0px;   overflow:hidden; }  .card .content  {   padding: 10px;   text-align: center; }  .card span {   transition: 1; }  .card span:nth-child(1)  {   position: absolute;   top:0;   left:0;   width:100%;   height:3px;   background: linear-gradient(to right, transparent, red);   animation: animate1 2s linear 3 forwards; } @keyframes animate1 {     0% { transform: translateX(-100%);}   100% { transform: translateX(100%);} }  .card span:nth-child(2) {   position: absolute;   top:0;   right:0;   width:3px;   height:100%;   background: linear-gradient(to bottom, transparent, red);   animation: animate2 2s linear 3 forwards;   animation-delay: 1s; } @keyframes animate2 {     0% { transform: translateY(-100%);}   100% { transform: translateY(100%);} }  .card span:nth-child(3)  {     position: absolute;     bottom:0;   left:0;   width:100%;   height:3px;   background: linear-gradient(to left, transparent, red);   animation: animate3 2s linear 3 forwards; } @keyframes animate3 {   0% { transform: translateX(100%);}   100% { transform: translateX(-100%);} }  .card span:nth-child(4)  {   position: absolute;   top:0;   left:0;   width:3px;   height:100%;   background: linear-gradient(to top, transparent, red);   animation: animate4 2s linear 3 forwards;   animation-delay: 1s; } @keyframes animate4 {   0% { transform: translateY(100%);}   100% { transform: translateY(-100%);} }  #büro-4 {   background-color: white; }   .marquee {     width: 100%;     margin: 0 auto;     white-space: nowrap;     overflow: hidden;     box-sizing: border-box;     display: inline-flex;     }  .marquee span {     display: flex;             flex-basis: 100%;     animation: marquee-reset;     animation-play-state: paused;                 }  .marquee:hover> span {     animation: marquee 4s linear infinite;     animation-play-state: running; }  @keyframes marquee {     0% {         transform: translate(0%, 0);     }         50% {         transform: translate(-100%, 0);     }     50.001% {         transform: translate(100%, 0);     }     100% {         transform: translate(0%, 0);     } } @keyframes marquee-reset {     0% {         transform: translate(0%, 0);     }   }   .alert {      animation: alerter 2s linear infinite; }  @keyframes alerter {   0%   {top: 0px; background: orange; width: 50px;}   50%  {top: 100px; background: lightred; width: 100px;}   100% {top: 200px; background: red; width: 150px;} }`

**Comment by Zefau** [comment]
Das CSS ist nicht korrekt. `//` ist kein valider Kommentar in CSS:

> // font-size: 80%

Siehe auch https://jigsaw.w3.org/css-validator/validator.

**Comment by mcuiobroker** [comment]
Also alles mit /* */ auskommentieren?

**Comment by Zefau** [comment]
Jo, dann ist es valide. Formatiert wird es trotzdem nicht. Dann baue ich nun ein (in der nächsten alpha wird dann korrekter Code formatiert).

**Comment by mcuiobroker** [comment]
Ok. Danke.

**Comment by Zefau** [comment]
added with `v3.0.0-alpha.71` (please note that unfortunately comments will not be formatted).

**Comment by mcuiobroker** [comment]
Funktioniert mit .v74.
