### ISSUE TITLE
v3: Handy-Ansicht  iFrame Link (ioBroker VIS) drehender blauer Kreis (Browser abhängig)

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#967]
Chrome: Fehler -> Permanent drehender blauer Kreis

![image](https://user-images.githubusercontent.com/84818934/132601758-8092ecae-b4ec-4002-b6bd-22bfedac4775.png)

FireFox: Ok und Edge: Ok

![image](https://user-images.githubusercontent.com/84818934/132601735-20caf589-2724-4e5e-9352-381acbe930b9.png)

**Comment by Zefau** [comment]
Liegt aus meiner Sicht nicht den jarvis. Wusste auch nicht, was ich da machen soll :-/

**Comment by mcuiobroker** [comment]
Fehlermeldungen, die nur in Chrome kommen:
![image](https://user-images.githubusercontent.com/84818934/134644704-1868f607-8734-406c-88f6-8375f8a06bf2.png)

**Comment by Zefau** [comment]
Kann das geschlossen werden?

**Comment by mcuiobroker** [comment]
Ja. Problem besteht nicht mehr.
