### ISSUE TITLE
V3: error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

### ISSUE THREAD

**Issue by MarkSau** [Zefau/ioBroker.jarvis#968]
Javis v3 Alpha 70

Bekomme im Log folgende Fehlermeldungen, wenn ich die Seite über mein Android 10 Mobile aufrufe:

`
<html>
<body>

jarvis.0 | 2021-09-09 14:41:06.268 | warn | error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
-- | -- | -- | --
jarvis.0 | 2021-09-09 14:41:06.267 | warn | error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt
jarvis.0 | 2021-09-09 14:41:06.265 | warn | error:06065064:digital envelope routines:EVP_DecryptFinal_ex:bad decrypt

</body>
</html>`

Browser: Chrome und Edge Chromium

**Comment by Zefau** [comment]
Liegt am Upgrade von v2. Aktualisiere mal bitte dein Passwort im Kalender. Geht es dann?

**Comment by MarkSau** [comment]
tatsächlich war das die Lösung. Aber auch erst nachdem ich den Jarvis Adapter neu gestartet habe,
Danke für die schnelle Antwort

**Comment by MarkSau** [comment]
ha...zu früh gefreut...
Jetzt sind alle Kalender Einträge weg

Dafür kommt jetzt:
`
<html>
<body>


jarvis.0 | 2021-09-09 17:47:08.624 | warn | URI malformed
-- | -- | -- | --
jarvis.0 | 2021-09-09 17:47:08.622 | warn | URI malformed
jarvis.0 | 2021-09-09 17:47:08.619 | warn | URI malformed
jarvis.0 | 2021-09-09 17:47:08.343 | warn | Invalid IV length
jarvis.0 | 2021-09-09 17:47:08.340 | warn | Invalid IV length


</body>
</html>`

**Comment by Zefau** [comment]
bitte mit `v3.0.0-alpha.75` nochmal das Passwort neu eingeben und speichern.

**Comment by Zefau** [comment]
`Invalid IV length` sagt, dass etwas beim Ver- oder Entschlüsseln fehlgeschlagen ist (Passwort wird verschlüsselt).

**Comment by MarkSau** [comment]
alles klar..funktioniert jetzt

**Comment by MarkSau** [comment]
habe meine letzten Post gelöscht, weil es immer noch genau das gleiche Fehlerbild zeigt.

**Comment by MarkSau** [comment]
Gibt es hierzu schon was neues?

**Comment by Zefau** [comment]
bin dran

**Comment by Zefau** [comment]
@MarkSau welche Node.js Version hast du drauf?

**Comment by MarkSau** [comment]
node: v14.17.6, npm 6

**Comment by Zefau** [comment]
Ich weiß ehrlich gesagt nicht, warum es bei dir nicht funktioniert. Bei mir geht es.

Ich hab in der `v3.0.0-alpha.82` mal den AES Algorithmus geändert. Ändere nochmal bitte das Passwort im Kalender-Widget, dann sollte es hoffentlich gehen.

**Comment by MarkSau** [comment]
Immer noch Fehler. Ich habe vorher auch nur noch einen meiner 3 Kalender neu hinzugefügt.
`
<html>
<body>


2021-09-26 22:47:00.097 - info: jarvis.0 (286586) starting. Version 3.0.0-alpha.82 in /opt/iobroker/node_modules/iobroker.jarvis, node: v14.17.6, js-controller: 3.3.18
2021-09-26 22:47:00.168 - info: jarvis.0 (286586) Found Backups for widgets.
2021-09-26 22:47:00.169 - info: jarvis.0 (286586) Found Backups for layout.
2021-09-26 22:47:00.176 - info: jarvis.0 (286586) Found Backups for settings.
2021-09-26 22:47:00.177 - info: jarvis.0 (286586) Found Backups for styles.
2021-09-26 22:47:00.193 - info: jarvis.0 (286586) Found Backups for devices.
2021-09-26 22:47:00.285 - info: jarvis.0 (286586) Connection: WebSocket opened on port 8400 using https...
2021-09-26 22:47:00.361 - info: jarvis.0 (286586) State value to set for "jarvis.0.settings.pageHomeReturn" has to be type "number" but received type "string"
2021-09-26 22:51:20.804 - info: jarvis.0 (286586) Client with IP ::ffff:192.168.0.150 connected
2021-09-26 22:51:22.136 - warn: jarvis.0 (286586) Invalid IV length
2021-09-26 22:51:22.261 - warn: jarvis.0 (286586) URI malformed
2021-09-26 22:52:09.342 - warn: jarvis.0 (286586) Invalid IV length
2021-09-26 22:52:09.801 - warn: jarvis.0 (286586) URI malformed


</body>
</html>
`

**Comment by Zefau** [comment]
Nutzt du den ical Adapter?

Wo trägst du genau das Passwort ein? In der jarvis GUI oder im JSON? Oder ganz woanders?

**Comment by MarkSau** [comment]
ich habe den ical jetzt extra mal installiert.  der ruft meine Kalender einwandfrei ab.
Dass Password trage ich in der GUI ein.
![image](https://user-images.githubusercontent.com/22911084/134853285-fe3f25a8-9986-48dc-bc5f-5985f44c5f57.png)

**Comment by Zefau** [comment]
sollte mit `v3.0.0-alpha.91` nun passen.

**Comment by mcuiobroker** [comment]
Sieht gut aus. 
CSS:
`
.q-separator--horizontal {
	background-color: green;
}`
Im Kalender wird die Farbe dann als Schriftfarbe übernommen?
![image](https://user-images.githubusercontent.com/84818934/137593628-762d70b3-f115-4175-8c20-7a2f53813144.png)

**Comment by Zefau** [comment]
Die Fehler kommen nicht von jarvis. Dann würde rechts `app.XXXXXXXX.js` oder `vendor.XXXXXXXX.js` stehen (`XXXXXXXX` = z.B. `0e8348fa`).

**Comment by Zefau** [comment]
@mcuiobroker kannst du nochmal mit `v3.0.0-alpha.93` schauen, wie die Navigation durch die Monate funktioniert?

Scheint leider nicht sehr performant, aber ich kann wenig machen.

**Comment by mcuiobroker** [comment]
Oder hängt es mit den Fonts zusammen?
![image](https://user-images.githubusercontent.com/84818934/137601967-26ea4252-0131-4139-8fc5-5cad57fd2513.png)

**Comment by Zefau** [comment]
Das mit den Fonts ist ein Mysterium für sich

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.94` sollte es jetzt passen

**Comment by mcuiobroker** [comment]
Jetzt braucht er für jeden Monat ca 15 Sekunden.
Ausserdem ist jetzt der Ladevorgang nicht mehr sichtbar (blauer Balken).
Der Fehler kommt nicht mehr.

**Comment by Bernd9000** [comment]
Bei mir ist es so, habe im Moment zwei jarvis Versionen installiert v92 und v94
Bei beiden Installationen sind vier Google Kalender angelegt in jarvis

Bei v92:
Alle Kalender werden angezeigt.
Beim Umschaltung zum nächsten Monat dauerte es 4:40 Minuten bis die Daten angezeigt wurden.

Bei v 94:
Es wird nur noch ein Kalender angezeigt
Die Umschaltung erfolgt innerhalb von 5 Sekunden.

**Comment by Bernd9000** [comment]
Nachtrag:
Sehr kurios, lege ich in jarvis ein neuen Tab an und füge jetzt das Kalender widget, ohne es zu verändern wieder ein, werden alle Kalender wieder angezeigt.Beim umschalten des Kalender Monats verschwinden wieder alle Kalender bis auf einen.

**Comment by Zefau** [comment]
Die Kalender werden gecached. Da scheint der Cache nicht ordentlich zu funktionieren. Gibt es Fehler im Log?

**Comment by Bernd9000** [comment]
Nein, kein Fehler.
Wo befindet sich der Cache?
Würde da gern Mal nachschauen

**Comment by Zefau** [comment]
F12 und dort Storage

**Comment by Bernd9000** [comment]
Du meinst den Browser cache ?
Da werden die Kalender gespeichert, alles OK.
Den Fehler habe ich auch in unterschiedlichen Browsern, das sollte dann nicht am Browser cache liegen.

**Comment by MarkSau** [comment]
Vielleicht kann ich auch etwas dazu beitragen.  Ich habe jetzt 3 Kalender im Widget. Wenn ich Jarvis aufrufe zeigt er nicht alle an Eigentlich habe ich Mülltermine
![image](https://user-images.githubusercontent.com/22911084/137628969-3bc16cf0-ac24-4743-8e39-8540a093e86c.png)

Wenn ich jetzt das Widget editiere, steht im User/PW was drin.

![image](https://user-images.githubusercontent.com/22911084/137629071-dcafe006-4172-4043-bef3-9b3dc53d8d0b.png)

User/PW lösche ich raus und speichere ab. Danach sehe ich auch die Mülltermine.

![image](https://user-images.githubusercontent.com/22911084/137629111-59660f3e-77a0-4cbf-9985-f72976312275.png)

Schliesse ich das Fenster jetzt und öffne es neu, sieht es wie auf dem ersten Bild aus.

**Comment by Bernd9000** [comment]
@Zefau
Also ist es so, das jarvis die Daten vom ical Adapter holt, richtig?

**Comment by Zefau** [comment]
Nein. Da werden nur initial Kalender geholt, sonst nichts. Jarvis ist sonst autark.

**Comment by Bernd9000** [comment]
Vielleicht ein Timeout Problem?
Also das nicht lange genug auf die Daten gewartet wird ?

**Comment by Zefau** [comment]
Schaut bitte nochmal mit `v3.0.0-alpha.95`. Bitte unbedingt das Passwort / die Passwörter der Kalender in jarvis neu setzen / speichern.

**Comment by MarkSau** [comment]
Ich wollte mal vermelden, das meine Kalender jetzt alle soweit funktionieren. Allein der Monatswechsel, das ist mir aufgefallen, ist unschön, da erst ab dem ersten Tag im Monat die dann folgenden Termine angezeigt werden. Schöner wäre, wenn die angegeben 7 Tage auch vollständig da wären.

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-alpha.125`
