### ISSUE TITLE
v3: Hue-Slider für RGB-Werte nutzen

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#969]
https://forum.iobroker.net/topic/30668/jarvis-v2-2-0-just-another-remarkable-vis/5007
Wenn möglich diese Funktion oder eine ähnliche mit einbauen?
Hier wird immer Format "#xxxxxx" zurückgegeben.
#602

**Comment by Zefau** [comment]
Sollte mit v3 bereits so funktionieren. Output Format entspricht Input Format.

**Comment by mcuiobroker** [comment]
Ja mit v3 funktioniert es so. Kannst beide issues schließen. Danke.
