### ISSUE TITLE
v3: Trotz Sprache = Deutsch ist die PopupButton-Beschriftung "Close"

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#970]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)
v3.0.0-alpha.70
Screenshot siehe unten

**Describe the bug / Beschreibe den Fehler**
A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können.
Trotz Sprache = Deutsch ist die PopupButton-Beschriftung "Close"

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.
![image](https://user-images.githubusercontent.com/79741077/132839567-19f84a70-f1b5-4308-8e04-428401615307.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.71`

**Comment by RkcCorian** [comment]
@Zefau: Funktioniert, danke!
