### ISSUE TITLE
v3: Funktiontasten (PC) zur Bearbeitung für Jarvis

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#973]
F1: Direkt zur verlinkten Dokumentation springen
F2: Bearbeitung der Konfiguration (Geräteansicht oder Layoutansicht, die letzte Aktive Ansicht)
F3-F7 belegt durch Aktionen im Browser
F8: Direkt auf Styles springen
F9: Direkt auf Theme Einstellungen springen

**Comment by Zefau** [comment]
implemented with `v3.0.0-alpha.71`.

**Comment by mcuiobroker** [comment]
Keinerlei Anzeige mit .71

**Comment by Zefau** [comment]
Funktioniert bei mir. Geht vielleicht nur im FF? Hab es nur dort getestet.

**Comment by mcuiobroker** [comment]
.72
![image](https://user-images.githubusercontent.com/84818934/133093805-53e6f9ca-710d-4775-8c07-ccd59234615a.png)

**Comment by mcuiobroker** [comment]
.73
Chrome
![image](https://user-images.githubusercontent.com/84818934/133140298-499cf18a-05ab-4b4f-abda-e22734c270ef.png)
Edge
![image](https://user-images.githubusercontent.com/84818934/133140334-8b9b0df3-1ea2-43ea-86a6-7b901cc09969.png)
FireFox
![image](https://user-images.githubusercontent.com/84818934/133140380-d19c62ef-cf0a-4569-aca1-63fdfc6acdd9.png)

**Comment by Zefau** [comment]
das ist https://github.com/Zefau/ioBroker.jarvis/issues/985, nicht dieses Issue

**Comment by mcuiobroker** [comment]
Funktioiniert. Danke. Aufgefallen ist mir, dass auch Shift + F8 -> Styles aufruft
Vielleicht, wenn es unterstützt wird, dann
Shift+F8 -> Geräte
Shift+F9 -> Layout
Dann kann man die auch direkt erreichen.

**Comment by Zefau** [comment]
Shift+F9 ist bereits vom Browser belegt (zumindest im FF)

**Comment by Zefau** [comment]
in der nächsten alpha mittels `STRG` umgesetzt

**Comment by mcuiobroker** [comment]
Da man Geräte und Layout öfter braucht sollte es so sein:
F8 -> Geräte
F9 -> Layout
STRG+F8 -> Styles
STRG+F9 -> Einstellungen
?

**Comment by Zefau** [comment]
ok

**Comment by Zefau** [comment]
mit `v3.0.0-alpha.75` nun so umgesetzt

**Comment by mcuiobroker** [comment]
Passt wunderbar. Danke.
