### ISSUE TITLE
v3: JsonTable CSS 

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#975]
JsonTable lassen sich mit Hilfe von CSS-Einträgen etwas steuern bzw verändern:

`.q-table tr:nth-child(2n+1) {
   background-color: grey;
}`

entspricht tr:nth-child(odd)

![image](https://user-images.githubusercontent.com/84818934/132928273-e3fa84b3-baaf-4456-86d8-7a15b2c6ce4b.png)
thead wird mit formatiert.

tr:nth-child(even) wird nicht akzeptiert bzw. nicht umgesetzt.

thead -Beeinflussung der Tabelle mit der ID funktioniert:

`[widgets="8871870a-def2-41e0-aeff-c4d6fb496956"] thead {
 background-color:yellow;
}`

wird durch die obige Einstellungen durch das fehlerhafte thead überschrieben.

Ist es daher sinnvoll in das Modul JsonTable einige Farbeinstellungen mitgeben zu können:
Für thead, tr:nth-child(odd), tr:nth-child(even)

**Comment by Zefau** [comment]
Versuch mal `! important`

**Comment by mcuiobroker** [comment]
Leider mit `!important` keine Verbesserung.

**Comment by Zefau** [comment]
CSS-Klassen:
`jarvis-JsonTable-Container`
`jarvis-JsonTable`
`jarvis-JsonTable-row-odd`
`jarvis-JsonTable-row-even`

**Comment by Zefau** [comment]
mit `v3.0.0-beta.19` gibt es nun wie gewünscht zusätzliche CSS-Klassen, die du nutzen kannst

**Comment by mcuiobroker** [comment]
jarvis-JsonTable-Container funktioniert nicht siehe Doku:
Es wird nichts verändert? Was soll verändert werden?
https://mcuiobroker.gitbook.io/jarvis-infos/jarvis/besonderheiten-v3/styles/.jarvis-module-jsontable#jsontable-css

**Comment by Zefau** [comment]
`.jarvis-JsonTable-Container` ist einfach der übergreifende Container. 

>  Es wird nichts verändert? Was soll verändert werden?

Es wird normal alles verändert. Hintergrundfarbe wird nicht genommen, weil darunter liegende Elemente selbst eine Farbe definieren. Was du da verändern kannst weiß ich nicht. Die Höhe beispielsweise. 

Mein Gefühl ist aber, dass der CSS-Selektor eher eine untergeordnete Rolle spielt.

**Comment by mcuiobroker** [comment]
Mit welchem kann ich die Überschrift von dem Inhalt der JsonTable beeinflussen?
Habe nur Einfluß auf die Zeilen?
![image](https://user-images.githubusercontent.com/84818934/149987956-72f46baf-fecd-4271-bc27-56794944731d.png)
