### ISSUE TITLE
v3: Erste Jarvis Seite ist auf mobilen Chrome Browsern leer

### ISSUE THREAD

**Issue by daolis** [Zefau/ioBroker.jarvis#976]
Jarvis Version: 3.0.0-alpha.70

Die erste Seite ist auf Mobilen Chrome Browsern leer. (Android)
Ist mit dem  Desktop Chrome reproduzierbar. Siehe Screenshot. 
Funktioniert mit Firefox!
Der Fehler existiert nicht erst mit der letzten Version. Habe das Problem shon seit längerem.

**Screenshots**
![JarvisScreenshot001](https://user-images.githubusercontent.com/2550938/132944159-7999c2c5-ba26-42e4-8680-2b492b538a2d.png)

**Comment by Zefau** [comment]
@daolis besteht das Problem noch? Kannst du nochmal kompletten Screenshot von F12 machen und auch von der Konfiguration des Tabs?

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.88` auf Chrome ist bei mir alles zu sehen.

**Comment by RkcCorian** [comment]
`v3.0.0-alpha.86` Nicht sicher ob mit Chrome direkt vergleichbar, aber mit Chromium Edge auf Handy und PC ebenfalls keine Probleme

**Comment by daolis** [comment]
Werde es heute Abend testen.

**Comment by daolis** [comment]
Ok, falscher Alarm. Sieht so aus als ob es eine config auf der ersten Seite auslöst.
Wenn ich die Ursache finden und es ein Fehler ist erstelle ich einen neuen Issue.
Danke
