### ISSUE TITLE
add JSON Editor for inputs fields in Devices configuration

### ISSUE THREAD

**Issue by Zefau** [Zefau/ioBroker.jarvis#98]
https://forum.iobroker.net/post/492078

**Comment by cryptedx** [comment]
Verwende doch das: https://github.com/josdejong/jsoneditor oder?

**Comment by Zefau** [comment]
added proper json editor for expert view with `v2.1.0-beta.1`.
JSON editor for input fields will follow.

**Comment by cryptedx** [comment]
Amazing! Thanks!

**Comment by cryptedx** [comment]
Aktuell ist nur der Tree mode aktiv? Kannst du bitte auch den Code mode und Text mode verfügbar machen?

**Comment by Zefau** [comment]
@cryptedx siehe https://github.com/Zefau/ioBroker.jarvis/issues/421

**Comment by Zefau** [comment]
added with `2.1.0-beta.5`.
