### ISSUE TITLE
v3: LightColorBody overlap

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#981]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
_- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
_- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)__

v3.0.0 alpha-70

**Describe the bug / Beschreibe den Fehler**
_A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können._

Im Widget überlagert der LightColorBody andere Elemente in der "Blockselektion" (mir fällt kein besserer Name ein, vgl. Screenshot)

**Screenshots**
_If applicable, add screenshots to help explain your problem.
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern._

![Screenshot 2021-09-12 010155](https://user-images.githubusercontent.com/79741077/132963701-a8db2c0e-4cf8-4df0-8f1e-b0e5fc1c7d64.jpg)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
fixed with `v3.0.0-alpha.71`.

**Comment by RkcCorian** [comment]
@Zefau: Funktioniert! Außerdem ist die feiner Rasterung super!! Danke!
