### ISSUE TITLE
Level steps are incorrect

### ISSUE THREAD

**Issue by stephan1827** [Zefau/ioBroker.jarvis#982]
**Prerequisites / Voraussetzungen**
- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung]

v3.0.0 alpha-70

**Describe the bug / Beschreibe den Fehler**
Level steps do not show up correct. For the radiator at the top there are no steps at all where it should be 10 in total with a step width of 0.5. For the light it should also be 10 but there the steps are doubled. Both worked correct in jarvis V2. Changing the number of steps does not seem to have any effect on the actual steps that are displayed.

**Screenshots**
Radiator and Lights
<img width="801" alt="Bildschirmfoto 2021-09-12 um 14 35 29" src="https://user-images.githubusercontent.com/2972703/132987968-9f131eb8-6592-4bda-9e27-ddf2036e199c.png">

Configuration for lights
<img width="507" alt="Bildschirmfoto 2021-09-12 um 14 36 09" src="https://user-images.githubusercontent.com/2972703/132987984-2bd17119-21cb-4c20-8d6c-b4cb67739a47.png">

Configuration for radiator
<img width="504" alt="Bildschirmfoto 2021-09-12 um 14 35 58" src="https://user-images.githubusercontent.com/2972703/132987986-2e756914-3350-45af-82ad-617d72bb5945.png">

**Comment by Zefau** [comment]
Mit `v3.0.0-alpha.75` sollte die Schrittweite nun auch Komma-Werte korrekt akzeptieren (wurden vorher aufgerundet).

Die Schrittweite beeinflusst nicht die Anzahl der gezeigten Markierungen. Dafür ist das Feld "Anzahl der Markierungen" zuständig. Diese zeigt 10 (+1 für den Null-Punkt) Markierungen an (bzw. die eingestellte Anzahl +1).

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/850#issuecomment-918634081

@mcuiobroker was ist dein min/max bei dem Gerät?

**Comment by mcuiobroker** [comment]
Ich habe keine "min" oder "max" Werte in Datenpunkt-Eigenschaften eingetragen. Standard ist ja 0 - 100.

**Comment by Zefau** [comment]
schau dir nochmal mit `v3.0.0-alpha.77` an
