### ISSUE TITLE
v3: apha-71 does not load / lädt gar nicht mehr

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#985]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
_- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)_

v3.0.0 alpha-71

**Describe the bug / Beschreibe den Fehler**
_A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können._

@Zefau: 
JARVIS does not load anymore :-(

**Screenshots**
_If applicable, add screenshots to help explain your problem.
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern._

![image](https://user-images.githubusercontent.com/79741077/133041474-e92908b6-b516-41bd-acc1-0fa28103bf79.png)

____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
Bitte mal die Registerkarte "Konsole" zeigen

**Comment by RkcCorian** [comment]
@Zefau 
![image](https://user-images.githubusercontent.com/79741077/133042627-af89b175-2512-439f-a9f4-514f5c39b62c.png)

**Comment by RkcCorian** [comment]
@Zefau : FYI
**alpha-71** verhält sich über alle meine Browser gleich, sprich lädt nicht.
**alpha-70**: Ich bin mir nicht sicher ob es hilft oder eher verwirrt. Mit der **alpha-70** habe ich zusätzlich das Problem, dass es **nur** mit Firefox auch nicht lädt, dort aber mit einem etwas anderen Fehlerbild. Ob die zusammenhängen weiß ich nicht. (Vgl. Screenshot)
![image](https://user-images.githubusercontent.com/79741077/133045670-2e0ccd07-c120-40b7-9d44-ca8bb14a67a6.png)

**Comment by Zefau** [comment]
Der Screenshot sagt dass die https Verbindung nicht aufgebaut werden kann. Wahrscheinlich muss das Zertifikat erst akzeptiert werden, da selbst signiert?

**Comment by Bernd9000** [comment]
v3.0.0 alpha-71

Nur zur Info, habe exakt den selben Fehler in der Konsole:

![Unbenannt](https://user-images.githubusercontent.com/77005685/133053577-101d44e6-c98f-4df4-bf1c-e4e8c5803c79.jpg)

**Comment by RkcCorian** [comment]
@Zefau : Kann mir nicht vorstellen, dass es mit dem Zertifikat zusammen hängt. Bin nicht der Experte für Zertifikate, allerdings nutze ich das gleiche Zertifikat für ioBroker, Grafana und influxDB. Alle drei haben kein Problem. Außerdem hat es mit alpha-70 funktioniert und erst ab alpha-71 nicht. (Bis auf den evtl. "anderen" Fehler in FireFox, welcher bereits seit alpha-70 da ist)

**Comment by RkcCorian** [comment]
> v3.0.0 alpha-71
> 
> Nur zur Info, habe exakt den selben Fehler in der Konsole:
> 
> ![Unbenannt](https://user-images.githubusercontent.com/77005685/133053577-101d44e6-c98f-4df4-bf1c-e4e8c5803c79.jpg)

Mit alpha-71?!

**Comment by Zefau** [comment]
Nein, der Fehler aus deinem zweiten Post (bzw. der von Bernd9000) hängt nicht damit zusammen. Dein zweiter Post (aus alpha-70) möglicherweise schon.

**Comment by RkcCorian** [comment]
@Zefau: Hab gerade geschaut, jedoch habe ich eine Ausnahme in Firefox. 
![image](https://user-images.githubusercontent.com/79741077/133072610-f192a2b2-6b5f-4e51-82ab-dbaf1ccc97fc.png)

Vermutlich ist der Fehler der alpha-71 aktuell der wichtigere, insb. falls alpha-70 Problem nur bei mir lokal ein Problem wäre.

**Comment by Zefau** [comment]
versuch mal mit `v3.0.0-alpha.72`.

**Comment by RkcCorian** [comment]
@Zefau : Ein anderer Fehler, aber das gleiche Ergebnis :-(
![image](https://user-images.githubusercontent.com/79741077/133090610-82fe3e4e-f9c9-497d-9e38-df5b1e5cf695.png)

**Comment by Bernd9000** [comment]
@Zefau
Was ist mit Zeile 81040 in der vendor.dfa1d3c3.js ?
Wurde da was verändert ?

![Unbenannt](https://user-images.githubusercontent.com/77005685/133096725-187e94ee-4ca1-4e50-ba34-fb278f4dcb0f.jpg)

**Comment by Ceel84** [comment]
Ich lese hier mal mit! Dann wird das Forum nicht voll gespamt

**Comment by RkcCorian** [comment]
@Zefau: Ich hab gerade mal mit Halbwissen auf die Konsole geschaut. Was mir auffällt... im Fehlerfall wird der falsche Port angesprochen, nämlich 8400 angesprochen, ich habe aber 8083. Mit alpha-70 sehe ich auch in der Konsole, dass 8083 angesprochen wird. Hilft das weiter?
![image](https://user-images.githubusercontent.com/79741077/133143920-a5cc4d72-7b70-407e-9548-07127441a2f5.png)

**Comment by Zefau** [comment]
Es lag an einem syntaktisch-falschem Kommentar im Source Code. Sollte nun mit `v3.0.0-alpha.74` passen.

**Comment by Zefau** [comment]
@RkcCorian ist oben. Kannst du mal schauen?

**Comment by mcuiobroker** [comment]
.74 Passt Es kommt am Anfang:
![image](https://user-images.githubusercontent.com/84818934/133145785-5cdcfbac-221f-4e71-a2c4-2a1acff0faae.png)

**Comment by RkcCorian** [comment]
@Zefau: Ja, genau, wie @mcuiobroker schreibt. Musste erst meinen Container neu starten, danach hat es erst geklappt
