### ISSUE TITLE
v3: Konvertierung v2.2.3 -> v3

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#989]
Direkt nach der Konvertierung erscheint folgendes Bild:

zwischen dem 3. und 4. Schritt braucht er ca 20-30 Sekunden.
![image](https://user-images.githubusercontent.com/84818934/133184503-83bd9214-03c2-418a-ae53-ffad9df2cd06.png)
Man muss dann die jarvis-Instanz neustarten, danach erscheint wieder normal die index.html.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.80`
Der Dark-Mode wird nicht mit übernommen.

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.84` neu sind hier die jarvis-socket Fehler siehe #1055.

**Comment by Zefau** [comment]
Diese jarvis Socket Fehler sind dieselben wie hier im ersten Post meine ich.

**Comment by mcuiobroker** [comment]
Da war es nur einmal nach der Konvertierung. Jetzt ist es bei jedem Reload so.

**Comment by Zefau** [comment]
- [ ] save correct connection details

**Comment by mcuiobroker** [comment]
Wie macht man das?

**Comment by Zefau** [comment]
Ist mein To-Do :-)

**Comment by mcuiobroker** [comment]
Icon nicht in der Flucht?
![image](https://user-images.githubusercontent.com/84818934/138575200-2a49c10d-df17-4e99-9169-7ad06400f7bf.png)

Spracheinstellung noch auf "de", obwohl man nur "deutsch" oder "english" auswählen kann.
![image](https://user-images.githubusercontent.com/84818934/138575216-2f4ccd6b-f466-41e0-8700-14182893d719.png)

Obwohl die DPs vorhanden sind wird trotzdem das Warndreieck gezeigt
![image](https://user-images.githubusercontent.com/84818934/138575317-f2341f01-a450-445f-b47e-54f6a215463c.png)

Erst nachdem ich manuell das Gewerk geändert habe und wieder zurück und dann gespeichert hab, wird das StandardIcon angezeigt.

Sonst finde ich momentan keine Fehler.

**Comment by Zefau** [comment]
Das mit dem Icon sollte behoben sein

**Comment by Zefau** [comment]
> Mit dem Icon hat ja nichts mit der Konvertierung zu tun, aber sieht blöd aus:
  ![image](https://user-images.githubusercontent.com/84818934/138598180-59172a2f-843f-47c4-a02b-46f702c5e55b.png)

Müsste mit der aktuellen alpha auch behoben sein?

**Comment by mcuiobroker** [comment]
Noch nicht ganz, Icon wird nicht immer gesetzt:
![image](https://user-images.githubusercontent.com/84818934/139595501-763d4280-f7ad-45c9-a2cd-cc0832e26dc2.png)
Büro
![image](https://user-images.githubusercontent.com/84818934/139595540-ebe19485-79ce-445e-b23b-9163a30b5394.png)
Flur
![image](https://user-images.githubusercontent.com/84818934/139595551-36caeabf-1d14-46fe-86bb-24935f1c82de.png)

**Comment by Zefau** [comment]
schau bitte nochmal mit `v3.0.0-alpha.112`

**Comment by mcuiobroker** [comment]
Passt.
