### ISSUE TITLE
v3: Neuer Startbildschirm erscheint bei jedem Refresh?

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#990]
Neuer Startbildschirm
![image](https://user-images.githubusercontent.com/84818934/133186982-6ee909f2-09b1-412d-814c-d1d2556acac4.png)

erscheint bei jedem Refresh. 
Gibt es einen DP in ioBroker unter jarvis mit dem man diese Anzeige abschalten kann?
Es sinnvoll für den ersten Start oder bei Problemen, aber nicht unbedingt jedesmal?

**Comment by Zefau** [comment]
Ist das so schlimm?

**Comment by mcuiobroker** [comment]
Ja, weil man das so nicht gewöhnt ist und sofort denkt, ach schon wieder ein Fehler und das bei jedem Refresh.
Besser man kann es abschalten oder sieht es nur, wenn es wirklich wichtig ist. (z.B. vorher schon mal auf einen Fehler gelaufen oder so).

**Comment by Zefau** [comment]
schau dir nochmal mit `v3.0.0-alpha.77` an

**Comment by mcuiobroker** [comment]
Es ist besser, trotzdem fragt man sich in welches LOG schreibt er?
![image](https://user-images.githubusercontent.com/84818934/133291782-13571294-69d3-438b-b395-bc420f6f4241.png)
Es wirft halt evtl Fragen auf?
Wo kann ich die Fehler, wenn sie entstehen prüfen?
Werden die Fehler in einen DP geschrieben und dort kann man sie dann weiterschicken?
Wird, wenn ein Fehler auftritt, automatisch Sentry aktiviert, damit sofort der FehlerCode weitergeschickt wird?
Sonst ok.

**Comment by Zefau** [comment]
Ist das Log das sonst nur in der Konsole steht. Für solche Benutzer die damit nicht umgehen können.
