### ISSUE TITLE
v3: blind level not readable / pushed together on mobile phone

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#997]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
_- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**
_- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)__

alpha-76

**Describe the bug / Beschreibe den Fehler**
_A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können._

blind level not readable / pushed together on mobile phone

**Screenshots**
_If applicable, add screenshots to help explain your problem.
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern._

![Screenshot_20210914_090951_com chimbori hermitcrab](https://user-images.githubusercontent.com/79741077/133211983-4da72f30-5c20-40a9-b3ef-d463453e7725.jpg)
____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
schau dir nochmal mit `v3.0.0-alpha.77` an

**Comment by RkcCorian** [comment]
@Zefau: Schon viel besser. Einen kl. Änderungswunsch hätte ich noch ☺... den Platz besser nutzen, falls möglich...

Jetzt neu mit alpha-77
![Screenshot_20210914_171731_com chimbori hermitcrab](https://user-images.githubusercontent.com/79741077/133286407-394e39d7-20a4-477b-ae3a-208666324c57.jpg)

Slider etwas weiter nach rechts rausziehen, sodass Mittig über der 100, vgl. rot markierte Stelle...
![InkedScreenshot_20210914_171731_com chimbori hermitcrab_LI](https://user-images.githubusercontent.com/79741077/133286432-6e69befd-8e89-4549-a92c-2bc0d051bdad.jpg)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-alpha.78`.

**Comment by RkcCorian** [comment]
@Zefau : Viel besser.

Was ich außerdem noch meinte ist, dass die Zahl "100" ggü. der Linie etwas nach rechts verschoben ist, wodurch es für mich "unruhig" wird. Ich fände es schöner, wenn die 0...100 unterhalb der Bedienleiste wären. Sprich Links oberhalb der 0 beginnt die Linie und rechts der 100 endet sie.
Wir kommen nun allerdings in den Bereich des optischen Empfindens. Da dies unterschiedlich gesehen werden kann überlasse ich es Dir zu entscheiden ob Du diesen Issue schließen willst oder eine weitere Änderung machen möchtest :-)

**Comment by RkcCorian** [comment]
@Zefau: Hab's mir nochmal im Details angeschaut. Ggü. der oben vorgeschlagenen Lösung die 100 Rechtsbündig mit dem rechten Ende der Linie zu machen wäre es wahrscheinlich besser "einfach nur" die 100 mittig unter den Punkt auf der Linie zu setzen. Es ist leicht verschoben.
Siehe Screenshot vom Handy: Grün: Mitte der Punkts, Rot: Mitte der 10
![Screenshot_20210917_081339_com chimbori hermitcrab](https://user-images.githubusercontent.com/79741077/133733867-a2c8ccd6-cc8f-433d-8e44-713585b7eef1.jpg)
0

**Comment by RkcCorian** [comment]
@Zefau: Wir sind im Bereich schöner Wohnen :-)
Hab mal 3 Screenshots wie es aktuell auf 3 unterschiedlichen Geräten aussieht. Wie @Bernd9000 schreibt ist es sehr nahe dem Bedienelement rechts. Ansonsten stört zumindest mich, dass auf dem Handy die 100 nicht mittig unter dem Punkt ist. Auf PC und Tablet passt es.

Surface Book 2
![image](https://user-images.githubusercontent.com/79741077/133794404-83112a56-ada0-4b0c-bbb3-6ca677482d72.png)

Tablet Samsung Galaxy 7
![Tablet](https://user-images.githubusercontent.com/79741077/133795659-c0982dfd-83ee-4f9a-9f99-096aa58e54f7.jpg)

Handy Huawei Mate 20 Pro
![Handy](https://user-images.githubusercontent.com/79741077/133795550-415f57f3-8baf-4101-b45e-b205493c5095.jpg)

**Comment by RkcCorian** [comment]
@Zefau: Nochmal ein Bild am PC mit Wertanzeige ohne Bedienelement. Denke auch, dass es zu nah beieinander ist. :-|
![image](https://user-images.githubusercontent.com/79741077/133799001-f1a7348b-5eae-4aae-addb-bf1715a6d9fa.png)

**Comment by Bernd9000** [comment]
Viel zu Nah, es werden nun leider auch Secodary State verdeckt so das man die Werte nicht mehr ablesen kann.

![Unbenannt](https://user-images.githubusercontent.com/77005685/133802842-42dab557-7c9f-4d19-969d-cddfe4ca5354.jpg)

**Comment by Zefau** [comment]
Ich kümmer mich drum. Es gab dazu inzwischen diverse Issues und ich hab's verstanden ;-)

**Comment by Bernd9000** [comment]
Weiß zwar nicht ob das in anderen Elementen in jarvis Auswirkungen hat.
Hab es aber für mich erstmal unter styles provisorisch korrigiert:

.q-slider {
	right: 10px;
	border-right-width: 0px;
	border-right-style: solid;
}

.markers {
	padding-right: 30px;
}

**Comment by Zefau** [comment]
Abstand im Standard mit `v3.0.0-alpha.81` wieder etwas vergrößert

**Comment by RkcCorian** [comment]
@Zefau: Getestet mit alpha-86: Position auf Handy und Tablet stimmt nicht. Position Zahlen ggü. Schieberegler verschoben...

![processed-092a2771-e4cb-41fe-978d-bc339161d20f_Urg6SiVr](https://user-images.githubusercontent.com/79741077/135757020-b926bce3-bb9e-4773-a1be-ee9235af103d.jpeg)
![IMG_20211003_155637](https://user-images.githubusercontent.com/79741077/135757023-b4ca8770-1bf4-4323-9b60-ea745cfc755e.jpg)

**Comment by Zefau** [comment]
Hast du da einen Fehler in der Browser Konsole (auf dem Desktop oder Mobil, egal) ? Weil das Icon noch dreht, als du das Foto gemacht hast?

Was ist das für ein Browser? Fully?

**Comment by Bernd9000** [comment]
@ RkcCorian
Hast Du vielleicht noch was in den styles bei jarvis drin stehen was die Anzeige verschiebt ?

**Comment by RkcCorian** [comment]
@Bernd9000 : Ich habe im CSS Folgendes drin. Das habe ich aber zum Test auskommentiert, es hat keine Auswirkung

.BlindLevelAction .q-btn__wrapper {
	padding-left: 12px !important;
	padding-right: 12px !important;
	padding-top: 1px !important;
	padding-bottom: 1px !important;
}

**Comment by RkcCorian** [comment]
@Zefau: Das Icon dreht sich, wie auch bei #1065 beschreiben. Betroffen ist immer der LEVEL der Rollläden, welcher endlos lädt.

**Comment by RkcCorian** [comment]
alpha-122: Am PC ok, am Tablet leicht verschoben, am Handy stärker verschoben. Denke ein kl. Rechenfehler. Vgl. Bilder vom Handy, wo der Fehler am deutlichsten sichtbar ist... hab die Mitte der Zahlen und die Mitte der linken und rechten Enden des Sliders mit rot markiert um es zu zeigen. Evtl. musst Du reinzoomen 🙈
![Screenshot_20211111_212746_de ozerov fully](https://user-images.githubusercontent.com/79741077/141364909-29c144bf-8bf4-4e97-8ef8-d240aa91740d.jpg)
![Screenshot_20211111_212729_de ozerov fully](https://user-images.githubusercontent.com/79741077/141364912-0df30d32-705b-490d-84fa-6880d8e2b52f.jpg)
.

**Comment by Zefau** [comment]
`v3.0.0-alpha.127`

**Comment by RkcCorian** [comment]
Am Laptop passt es, auf dem Handy ist es schlimmer :-|

**Comment by RkcCorian** [comment]
Evtl. eine Schnaps-Idee: Kannst Du evtl. den Code zur "Extra"-Behandlung für mobile Geräte temporär rausnehmen? Dann hast Du vermutlich zu viele Zahlen für das Display, aber dann bekommen wir evtl. raus, ob es mit dieser Unterscheidung zusammen hängt, und damit die Skalierung stimmt. Was denkst Du?
Mit ```alpha-127``` sieht es am Handy so aus...
![Screenshot_20211120_074421_de ozerov fully](https://user-images.githubusercontent.com/79741077/142717498-481b66f0-00dd-469e-b173-230e83d546d9.jpg)

**Comment by RkcCorian** [comment]
Weißt Du, wie das CSS für die Ränder der Zahlen, als auch des Sliders heißt? Würde das gerne am Handy anschauen

**Comment by RkcCorian** [comment]
Schau gerade nochmal mit ```alpha-125```

Versuche es zu verstehen. Initial (margin: 0px 0%) sind Slider und Text gleich Breit und untereinander...
![image](https://user-images.githubusercontent.com/79741077/142719844-58f3e808-9cdd-4595-bf1c-510e0347d2f9.png)

Auf welche Breite bezieht sich das folgende ```width```, welches zur Berechnung der Skalierung verwendet wird? ```marker``` scheint es nicht zu sein, ```marker nowrap``` passt aber auch nicht, da das Ergebnis nicht zu einer "einfachen" Division durch 2 passt.
```.toFixed``` convertiert nur die Zahl nach String, korrekt?
![image](https://user-images.githubusercontent.com/79741077/142719867-707d7d72-89ad-4fdb-9399-5e90be122ccb.png)

**Comment by RkcCorian** [comment]
Ich glaube, selbst wenn sich ```width``` auf ```marker``` bezieht geht diese "einfache" Rechnung nicht auf. Ich habe mal einen Test gemacht.

Margin auf 0% und die Größe in Pixel notiert
Margin auf -100% geändert und die Größe der Pixel notiert. Erwartet habe ich eine Verdoppelung, das war aber nicht der Fall. Denke hier ist der Fehler. Tue mir schwer mit der Lösung, da ich den genauen Zusammenhang zw. ```margin``` und ```width``` nicht kenne.

![image](https://user-images.githubusercontent.com/79741077/142720778-56f878bd-2d5a-4bf1-98e3-f07e7030ea7a.png)

**Comment by RkcCorian** [comment]
@Zefau : Hast Du eine Idee?

**Comment by RkcCorian** [comment]
So, komme jetzt auch auf die errechneten 5% von der Version ```alpha-125```. Bekomme das aber nicht mit dem oben gezeigten Code zusammen....

![image](https://user-images.githubusercontent.com/79741077/142722754-4ccbc1bc-3b9e-44df-84d5-957964b0db17.png)

![image](https://user-images.githubusercontent.com/79741077/142722820-6df24c39-78c7-41ac-9e91-92a1c54e8bb6.png)

Verstehe noch nicht warum es trotzdem ein ganz kleines wenig zu groß ist, wäre aber Mathematisch richtig. Sind da noch irgendwelche Linienbreiten o.ä. mit drin?

Denke das ist dann am Handy auch so, Größe würde grundsätzlich stimmen, aber auch da ein kleines wenig zu groß. Was aber bei mobilen Geräten leider noch dazu kommt ist eine Verschiebung nach rechts.
![image](https://user-images.githubusercontent.com/79741077/142722706-7c47b90e-0fbb-429a-9d15-d85e4442a3ab.png)

**Comment by RkcCorian** [comment]
@Zefau: So, jetzt will ich es wissen 😁 Hab USB Debugging aktiviert und schaue es mir gerade auf dem Handy in Edge an... 😄
Kann nochmal anbieten zu telefonieren, wenn es Dir hilft, ansonsten schreib mir, falls ich noch was Anderes anschauen soll.
Ansonsten im folgenden die Fehler auf mobilen Geräten, welche mir aufgefallen sind....

```maker```
```element.style``` > ```text-align```ist auf mobilen Geräte falsch, dort sollte auch center sein.

Surface:
![Slider_Desktop](https://user-images.githubusercontent.com/79741077/142758341-f4525009-3ed4-42c9-87e1-0c4d77187f13.jpg)

Android-Handy:
![image](https://user-images.githubusercontent.com/79741077/142758645-daacfca4-d011-4e9d-966e-1a8881550241.png)

```marker nowrap```
Bei ```margin``` fehlt die prozentuale Skalierung komplett
Android-Handy:
![image](https://user-images.githubusercontent.com/79741077/142758779-4a028f80-b6bb-43f6-8d9f-0c2d45cf9f9d.png)

**Comment by Zefau** [comment]
Aufgrund von https://github.com/Zefau/ioBroker.jarvis/issues/1188#issuecomment-975733716 habe ich es nun mit `v3.0.0-alpha.131` umgestellt.

Die Marker haben nun die identische Breite zum Slider. Der linke (also 0) und rechte Werte (also 100) wird links- bzw. rechtsbündig dargestellt.

**Comment by Zefau** [comment]
@ma-gu-16 könntest du mal schauen, ob es mit `v3.0.0-alpha.131` bzgl. https://github.com/Zefau/ioBroker.jarvis/issues/1188#issuecomment-975733716 passt?

**Comment by RkcCorian** [comment]
@Zefau : Um ehrlich zu sein, ich finde die Änderung nicht gut und würde sie lieber rückgängig machen. Warum im Folgenden...
- Zum einen ist es jetzt noch schlimmer (Screenshot vom Handy)
![Screenshot_20211125-231906](https://user-images.githubusercontent.com/79741077/143504389-d9ececdd-8f1f-41de-b07d-9d93dfadc4d3.jpg)
- Jetzt ist die Einheit mit drin und verbraucht Platz
- Grundsätzlich wird jetzt (ob ALIAS oder nicht) nur noch ein Dreieck angezeigt

Die Hinweise von meinem USB Debugging haben nicht geholfen?

**Comment by Zefau** [comment]
https://github.com/Zefau/ioBroker.jarvis/issues/1215

**Comment by Zefau** [comment]
schau mal bitte mit `v3.0.0-beta.6`, damit sollte die  mobile Ansicht jetzt passen.

**Comment by Zefau** [comment]
Für die Einheit kann ich noch eine Option einbauen. Die Nummern unter dem Strich sind aber schlicht zu aufwendig; vor allem aber führt es zu vielen Seiteneffekten, dass bei einigen Usern Inhalte außerhalb angezeigt werden. Du kannst es gerne via CSS für dich so einstellen.

**Comment by RkcCorian** [comment]
@Zefau: betha-7: Wenn man die Einheit über eine Einstellung "auskonfigurieren" kann für den Slider wäre es für mich ok. Am Handy passt die Darstellung auch. Ich sehe nur tlw. ein komisches Verhalten bzgl. der 0, bzw. der Anzeige der Einheit.

Keine Einheit, aber anstelle 0 die Einheit
![image](https://user-images.githubusercontent.com/79741077/144321173-737ba4a7-490e-421c-a884-e1c75849d2d5.png)

Überall Einheit
![image](https://user-images.githubusercontent.com/79741077/144321281-03e8ca8f-b0d8-47a2-b64f-decd5a72fe0a.png)

**Comment by RkcCorian** [comment]
Am Handy sieht man am deutlichsten dass die Einheit stört...
![Screenshot_20211201-230556](https://user-images.githubusercontent.com/79741077/144321950-09067fde-88ff-4b78-9d4d-ab26a668ae83.jpg)

**Comment by Zefau** [comment]
schau nochmal mit `v3.0.0-beta.8`

**Comment by RkcCorian** [comment]
Und ich wollte gerade ins Bett gehen... 🙈
Passt!
Hab's angeschaut, und auch mit eingeschalteter Einheit ausprobiert. Die Zahlen sind glaub kleiner geworden, ist aber OK.
Bin jetzt auch Produktiv auf die beta-8 umgestiegen

**Comment by ma-gu-16** [comment]
Einheit: 
{"0":"Oben","100":"Unten","default":" %"}

ist nun nicht mehr vorhanden.....

![image](https://user-images.githubusercontent.com/22169074/144917972-d3ccdb99-ee0a-4b46-8650-e4052a6cffda.png)

**Comment by Zefau** [comment]
Kannst du via Option im LevelBody aktivieren

**Comment by ma-gu-16** [comment]
perfekt. sorry. auf mobile jedes 2. ausgeblendet, auch gut!
