### ISSUE TITLE
v3: Adapter-Widget: Black and White list not working for me

### ISSUE THREAD

**Issue by RkcCorian** [Zefau/ioBroker.jarvis#998]
*Please note that you may restore an old layout via jarvis adapter configuration directly within ioBroker

**Prerequisites / Voraussetzungen**
_- [x] Which jarvis version are you running / Welche Version von jarvis nutzt du? **BITTE GENAUE ANGABE!**_
_- [x] Fehler / Screenshot der Browser Konsole (F12), siehe [Fehleranalyse und -Meldung](https://github.com/Zefau/ioBroker.jarvis/wiki/de-Errors)_

alpha-76

**Describe the bug / Beschreibe den Fehler**
_A clear and concise description of what the bug / problem is.
Eine genaue Beschreibung des Fehlers inkl. Herleitung, um diesen Nachstellen zu können._

Adapter-Widget: Black and White list not working for me. E.g. I tried to whitelist / blacklist the admin adapter.

**Screenshots**
Sofern möglich, bitte Screenshots einfügen, um den Fehler bildlich zu erläutern.

![Screenshot 2021-09-14 092322](https://user-images.githubusercontent.com/79741077/133213559-ecdcdf1a-362b-4d58-b73d-112526553477.jpg)
____

**Please note that bug reports may be closed if the information above are not given!**

**Bitte beachte, dass Bug-Reports ggf. einfach geschlossen werden, wenn die oben genannten Kriterien nicht angemessen gegeben sind!**

**Comment by Zefau** [comment]
What is your config?

**Comment by RkcCorian** [comment]
@Zefau: AdapterUpdates = true, ansonsten habe ich die Konfig geleert und nur "Admin" oder auch "admin" reingeschrieben, jedoch ohne Auswirkung

**Comment by Zefau** [comment]
Schreib man bei Blacklist rein und nach einen full reload der Seite

**Comment by RkcCorian** [comment]
@Zefau: Auch mit Fill-Refresh keine Auswirkung

**Comment by RkcCorian** [comment]
@Zefau: Hab es auch nochmal mit einem komplett neuen Adapter-Widget ausprobiert, gleicher Fehler.

Konfig bisheriges Widget
```
  "30fa521d-624d-4daa-8b99-1fa24e262c1d": {
    "id": "30fa521d-624d-4daa-8b99-1fa24e262c1d",
    "config": {
      "blacklist": "admin,daswetter,firetv,ham,history,info,javascript,mercedesme,scenes,sql,terminal,vis,web",
      "list": ""
    },
    "icon": "iobroker",
    "title": "ioBroker Adapter",
    "module": "AdapterStatus",
    "items": [],
    "hideTitle": false
  },
```

Konfig neues Widget nur mit Admin in List
```
  "6ac41e67-030a-411e-bd00-95f4b28b636d": {
    "id": "6ac41e67-030a-411e-bd00-95f4b28b636d",
    "config": {
      "list": "admin"
    },
    "title": "Test",
    "module": "AdapterStatus",
    "items": []
  }
```

**Comment by RkcCorian** [comment]
@Zefau: Funktioniert! Läuft ja wie geschnitten Brot! :-)
