### ISSUE TITLE
v3: Reihenfolge TABs auf Handy anders als auf PC

### ISSUE THREAD

**Issue by mcuiobroker** [Zefau/ioBroker.jarvis#999]
`v3.0.0-alpha.77`

PC: (...,Wohnen, Schlafen,...)
![image](https://user-images.githubusercontent.com/84818934/133303841-5d49e02b-95c9-4cd7-9ebd-817b4098cb09.png)

Handy (Querformat):  (....,Wohnen, TV, Schlafen,.....)
![image](https://user-images.githubusercontent.com/84818934/133304029-8a8521ab-04d4-48a7-9ee4-b26c33858793.png)

Im Hochformat ist alles ok, die Reihenfolge stimmt. Dreht man es in das Querformat so entsteht die Vertauschung.

**Comment by RkcCorian** [comment]
@mcuiobroker Hab's gerade mal mit der alpha-80 bei mir geprüft. Bei mir stimmt die Reihenfolge. Besteht das Problem nach wie vor oder war das ein alpha-77 Problem?

**Comment by mcuiobroker** [comment]
`v3.0.0-alpha.80` Die Reihenfolge stimmt momentan auch im Quer-Modus auf dem Handy.

**Comment by Zefau** [comment]
Der Collapse Modus blendet zu breite Tabs aus, die nicht angezeigt werden können. Sollte nach einem breiten ein schmaler Tab kommen wird dieser angezeigt wenn es der Platz zulässt.

Die Frage ist, ist das ein Bug ist ein Feature? Soll ich das ändern, weil es verwirrt oder drin lassen?

**Comment by mcuiobroker** [comment]
Das ist definitiv ein Bug, da er die Reihenfolge vertauscht.

**Comment by RkcCorian** [comment]
Ahhh, ok. Dann habe ich einfach Glück aufgrund meiner Tabbezeichnungen :-)

**Comment by Zefau** [comment]
hopefully resolved with `v3.0.0-alpha.88`

**Comment by mcuiobroker** [comment]
Passt.
Eine Sache viellicht noch. Hat aber keine Prio:
Wenn man in der Portrait-Ansicht die More-Auswahl-Box geöffnet hat und dreht dann in den Landscape-Modus bleibt ein Teil von "more" auf dem Bildschirm. Man muss dann einmal daneben auswählen und es verschwindet.
